ECCE @ EIC Software: DicomFilePET Class Reference
DicomFilePET Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomFilePET.hh>
Public Member Functions
DicomFilePET ()
DicomFilePET (DcmDataset *dset)
~DicomFilePET ()
void BuildActivities ()
void DumpActivitiesToTextFile (std::ofstream &fout)
Public Member Functions inherited from DicomVFileImage
DicomVFileImage ()
DicomVFileImage (DcmDataset *dset)
~DicomVFileImage ()
virtual void ReadData ()
void operator+= (const DicomVFileImage &rhs)
DicomVFileImage operator+ (const DicomVFileImage &rhs)
void DumpHeaderToTextFile (std::ofstream &fout)
G4int GetNoVoxelX () const
G4int GetNoVoxelY () const
G4int GetNoVoxelZ () const
G4int GetNoVoxels () const
G4double GetMinX () const
G4double GetMinY () const
G4double GetMinZ () const
G4double GetMaxX () const
G4double GetMaxY () const
G4double GetMaxZ () const
void SetNoVoxelX (const G4int &val)
void SetNoVoxelY (const G4int &val)
void SetNoVoxelZ (const G4int &val)
void SetMinX (const G4double &val)
void SetMaxX (const G4double &val)
void SetMinY (const G4double &val)
void SetMaxY (const G4double &val)
void SetMinZ (const G4double &val)
void SetMaxZ (const G4double &val)
const G4double & GetLocation () const
void SetLocation (const G4double &val)
G4ThreeVector GetOrientationRows () const
G4ThreeVector GetOrientationColumns () const
Public Member Functions inherited from DicomVFile
DicomVFile ()
DicomVFile (DcmDataset *dset)
~DicomVFile ()
void SetFileName (G4String fName)
Private Attributes
std::vector< size_t > fActivities
Additional Inherited Members
Protected Member Functions inherited from DicomVFile
virtual std::vector< G4double > Read1Data (DcmDataset *dset, DcmTagKey tagKey, G4int nData)
virtual OFString Read1DataStr (DcmDataset *dset, DcmTagKey tagKey)
Protected Attributes inherited from DicomVFileImage
G4double fLocation
G4double fBitAllocated
G4double fRescaleSlope
G4double fRescaleIntercept
G4int fNoVoxelX
G4int fNoVoxelY
G4int fNoVoxelZ
G4double fMinX
G4double fMinY
G4double fMinZ
G4double fMaxX
G4double fMaxY
G4double fMaxZ
G4double fVoxelDimX
G4double fVoxelDimY
G4double fVoxelDimZ
G4ThreeVector fOrientationRows
G4ThreeVector fOrientationColumns
std::vector< int > fHounsfieldV
DicomFileMgr * theFileMgr
Detailed Description
Definition at line 31 of file DicomFilePET.hh.
View newest version in sPHENIX GitHub at line 31 of file DicomFilePET.hh
Constructor & Destructor Documentation
DicomFilePET::DicomFilePET ()
Definition at line 42 of file DicomFilePET.cc.
View newest version in sPHENIX GitHub at line 42 of file DicomFilePET.cc
DicomFilePET::DicomFilePET (DcmDataset * dset)
Definition at line 47 of file DicomFilePET.cc.
View newest version in sPHENIX GitHub at line 47 of file DicomFilePET.cc
DicomFilePET::~DicomFilePET () inline
Definition at line 36 of file DicomFilePET.hh.
View newest version in sPHENIX GitHub at line 36 of file DicomFilePET.hh
Member Function Documentation
void DicomFilePET::BuildActivities ()
Definition at line 52 of file DicomFilePET.cc.
View newest version in sPHENIX GitHub at line 52 of file DicomFilePET.cc
References fActivities, FatalException, DicomVFileImage::fHounsfieldV, DicomVFileImage::fNoVoxelX, DicomVFileImage::fNoVoxelY, G4Exception(), DicomFileMgr::GetCompression(), min, DicomVFileImage::theFileMgr, and nlohmann::to_string().
void DicomFilePET::DumpActivitiesToTextFile (std::ofstream & fout)
Definition at line 84 of file DicomFilePET.cc.
View newest version in sPHENIX GitHub at line 84 of file DicomFilePET.cc
References fActivities, DicomVFile::fFileName, DicomVFileImage::fLocation, DicomVFileImage::fNoVoxelX, DicomVFileImage::fNoVoxelY, G4cout, G4endl, DicomFileMgr::GetCompression(), DicomVFileImage::theFileMgr, DicomFileMgr::verbose, and warningVerb.
Member Data Documentation
std::vector<size_t> DicomFilePET::fActivities private
Definition at line 43 of file DicomFilePET.hh.
View newest version in sPHENIX GitHub at line 43 of file DicomFilePET.hh
Referenced by BuildActivities(), and DumpActivitiesToTextFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomFilePET.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomFilePET.cc