ECCE @ EIC Software: G4ElectricFieldModel Class Reference
G4ElectricFieldModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ElectricFieldModel.hh>
Public Member Functions
G4ElectricFieldModel (G4int nDataPointsPerHalfExtent=3, Representation representation=Representation::fullArrow, G4int arrow3DLineSegmentsPerCircle=6, const G4VisExtent &extentForField=G4VisExtent(), const std::vector< G4PhysicalVolumesSearchScene::Findings > &pvFindings=std::vector< G4PhysicalVolumesSearchScene::Findings >())
virtual ~G4ElectricFieldModel ()
Public Member Functions inherited from G4VFieldModel
G4VFieldModel (const G4String &typeOfField, const G4String &symbol="", const G4VisExtent &extentForField=G4VisExtent(), const std::vector< G4PhysicalVolumesSearchScene::Findings > &pvFindings=std::vector< G4PhysicalVolumesSearchScene::Findings >(), G4int nDataPointsPerHalfScene=10, Representation representation=Representation::fullArrow, G4int arrow3DLineSegmentsPerCircle=6)
virtual ~G4VFieldModel ()
virtual void DescribeYourselfTo (G4VGraphicsScene &sceneHandler)
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Protected Member Functions
virtual void GetFieldAtLocation (const G4Field *field, const G4Point3D &position, G4double time, G4Point3D &result) const
Private Member Functions
G4ElectricFieldModel (const G4ElectricFieldModel &)
G4ElectricFieldModel & operator= (const G4ElectricFieldModel &)
Additional Inherited Members
Public Types inherited from G4VFieldModel
enum Representation { fullArrow, lightArrow }
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 41 of file G4ElectricFieldModel.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ElectricFieldModel.hh
Constructor & Destructor Documentation
G4ElectricFieldModel::G4ElectricFieldModel (G4int nDataPointsPerHalfExtent = 3, Representation representation = Representation::fullArrow, G4int arrow3DLineSegmentsPerCircle = 6, const G4VisExtent & extentForField = G4VisExtent(), const std::vector< G4PhysicalVolumesSearchScene::Findings > & pvFindings = std::vector<G4PhysicalVolumesSearchScene::Findings>()) inline
Definition at line 46 of file G4ElectricFieldModel.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ElectricFieldModel.hh
virtual G4ElectricFieldModel::~G4ElectricFieldModel () inline virtual
Definition at line 57 of file G4ElectricFieldModel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ElectricFieldModel.hh
G4ElectricFieldModel::G4ElectricFieldModel (const G4ElectricFieldModel &) private
Member Function Documentation
void G4ElectricFieldModel::GetFieldAtLocation (const G4Field * field, const G4Point3D & position, G4double time, G4Point3D & result) const protected virtual
Implements G4VFieldModel.
Definition at line 43 of file G4ElectricFieldModel.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ElectricFieldModel.cc
References G4Field::GetFieldValue(), HepGeom::BasicVector3D< T >::set(), HepGeom::BasicVector3D< T >::x(), xyzt, HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
G4ElectricFieldModel& G4ElectricFieldModel::operator= (const G4ElectricFieldModel &) private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ElectricFieldModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4ElectricFieldModel.cc