ECCE @ EIC Software: StepMaxMessenger Class Reference
StepMaxMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/StepMaxMessenger.hh>
Public Member Functions
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
virtual ~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMaxProcess *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
virtual ~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
StepMaxMessenger (StepMax *)
~StepMaxMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
StepMax * fStepMax
G4UIcmdWithADoubleAndUnit * fStepMaxCmd
G4UIcmdWithADoubleAndUnit * fStepMax1Cmd
G4UIcmdWithABool * fStepMax2Cmd
StepMaxProcess * fStepMax
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 44 of file StepMaxMessenger.hh.
View newest version in sPHENIX GitHub at line 44 of file StepMaxMessenger.hh
Constructor & Destructor Documentation
StepMaxMessenger::StepMaxMessenger (StepMax * stepM)
Definition at line 40 of file StepMaxMessenger.cc.
View newest version in sPHENIX GitHub at line 40 of file StepMaxMessenger.cc
References fStepMaxCmd, G4UIcommand::SetGuidance(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
StepMaxMessenger::~StepMaxMessenger ()
Definition at line 52 of file StepMaxMessenger.cc.
View newest version in sPHENIX GitHub at line 52 of file StepMaxMessenger.cc
References fStepMaxCmd.
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
virtual StepMaxMessenger::~StepMaxMessenger () virtual
StepMaxMessenger::StepMaxMessenger (StepMaxProcess * stepM)
Definition at line 41 of file StepMaxMessenger.cc.
View newest version in sPHENIX GitHub at line 41 of file StepMaxMessenger.cc
References fStepMax1Cmd, fStepMax2Cmd, G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
virtual StepMaxMessenger::~StepMaxMessenger () virtual
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
StepMaxMessenger::StepMaxMessenger (StepMax *)
StepMaxMessenger::~StepMaxMessenger ()
Member Function Documentation
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void StepMaxMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 59 of file StepMaxMessenger.cc.
View newest version in sPHENIX GitHub at line 59 of file StepMaxMessenger.cc
References fStepMax, fStepMaxCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), and StepMax::SetMaxStep().
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void StepMaxMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
Member Data Documentation
StepMax * StepMaxMessenger::fStepMax private
Definition at line 53 of file StepMaxMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file StepMaxMessenger.hh
Referenced by SetNewValue().
StepMaxProcess* StepMaxMessenger::fStepMax private
Definition at line 54 of file StepMaxMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMaxMessenger.hh
G4UIcmdWithADoubleAndUnit * StepMaxMessenger::fStepMax1Cmd private
Definition at line 55 of file StepMaxMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file StepMaxMessenger.hh
Referenced by StepMaxMessenger().
G4UIcmdWithABool * StepMaxMessenger::fStepMax2Cmd private
Definition at line 56 of file StepMaxMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file StepMaxMessenger.hh
Referenced by StepMaxMessenger().
G4UIcmdWithADoubleAndUnit * StepMaxMessenger::fStepMaxCmd private
Definition at line 54 of file StepMaxMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMaxMessenger.hh
Referenced by SetNewValue(), StepMaxMessenger(), and ~StepMaxMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/StepMaxMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/StepMaxMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/StepMaxMessenger.cc