ECCE @ EIC Software: G4PSPassageCellFluxForCylinder3D Class Reference
G4PSPassageCellFluxForCylinder3D Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSPassageCellFluxForCylinder3D.hh>
Public Member Functions
G4PSPassageCellFluxForCylinder3D (G4String name, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
G4PSPassageCellFluxForCylinder3D (G4String name, const G4String &unit, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
virtual ~G4PSPassageCellFluxForCylinder3D ()
void SetCylinderSize (G4double dr, G4double dz)
void SetNumberOfSegments (G4int nSeg[3])
Public Member Functions inherited from G4PSPassageCellFlux3D
G4PSPassageCellFlux3D (G4String name, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
G4PSPassageCellFlux3D (G4String name, const G4String &unit, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
virtual ~G4PSPassageCellFlux3D ()
Public Member Functions inherited from G4PSPassageCellFlux
G4PSPassageCellFlux (G4String name, G4int depth=0)
G4PSPassageCellFlux (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSPassageCellFlux ()
void Weighted (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4double ComputeVolume (G4Step *, G4int idx)
Protected Member Functions inherited from G4PSPassageCellFlux3D
virtual G4int GetIndex (G4Step *)
Protected Member Functions inherited from G4PSPassageCellFlux
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual G4bool IsPassed (G4Step *)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4ThreeVector cylinderSize
G4int nSegment [3]
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 49 of file G4PSPassageCellFluxForCylinder3D.hh.
View newest version in sPHENIX GitHub at line 49 of file G4PSPassageCellFluxForCylinder3D.hh
Constructor & Destructor Documentation
G4PSPassageCellFluxForCylinder3D::G4PSPassageCellFluxForCylinder3D (G4String name, G4int ni = 1, G4int nj = 1, G4int nk = 1, G4int depi = 2, G4int depj = 1, G4int depk = 0)
Definition at line 46 of file G4PSPassageCellFluxForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PSPassageCellFluxForCylinder3D.cc
References nSegment.
G4PSPassageCellFluxForCylinder3D::G4PSPassageCellFluxForCylinder3D (G4String name, const G4String & unit, G4int ni = 1, G4int nj = 1, G4int nk = 1, G4int depi = 2, G4int depj = 1, G4int depk = 0)
Definition at line 54 of file G4PSPassageCellFluxForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PSPassageCellFluxForCylinder3D.cc
References nSegment.
G4PSPassageCellFluxForCylinder3D::~G4PSPassageCellFluxForCylinder3D () virtual
Definition at line 62 of file G4PSPassageCellFluxForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PSPassageCellFluxForCylinder3D.cc
Member Function Documentation
G4double G4PSPassageCellFluxForCylinder3D::ComputeVolume (G4Step * , G4int idx) protected virtual
Reimplemented from G4PSPassageCellFlux.
Definition at line 75 of file G4PSPassageCellFluxForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 75 of file G4PSPassageCellFluxForCylinder3D.cc
References cylinderSize, nSegment, pi, r1, and v.
void G4PSPassageCellFluxForCylinder3D::SetCylinderSize (G4double dr, G4double dz)
Definition at line 65 of file G4PSPassageCellFluxForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 65 of file G4PSPassageCellFluxForCylinder3D.cc
References cylinderSize, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and twopi.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4PSPassageCellFluxForCylinder3D::SetNumberOfSegments (G4int nSeg[3])
Definition at line 70 of file G4PSPassageCellFluxForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 70 of file G4PSPassageCellFluxForCylinder3D.cc
References nSegment.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
Member Data Documentation
G4ThreeVector G4PSPassageCellFluxForCylinder3D::cylinderSize private
Definition at line 68 of file G4PSPassageCellFluxForCylinder3D.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PSPassageCellFluxForCylinder3D.hh
Referenced by ComputeVolume(), and SetCylinderSize().
G4int G4PSPassageCellFluxForCylinder3D::nSegment[3] private
Definition at line 69 of file G4PSPassageCellFluxForCylinder3D.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSPassageCellFluxForCylinder3D.hh
Referenced by ComputeVolume(), G4PSPassageCellFluxForCylinder3D(), and SetNumberOfSegments().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSPassageCellFluxForCylinder3D.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSPassageCellFluxForCylinder3D.cc