ECCE @ EIC Software: G4ExtDEDXTable Class Reference
G4ExtDEDXTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4ExtDEDXTable.hh>
Public Member Functions
G4ExtDEDXTable ()
virtual ~G4ExtDEDXTable ()
virtual G4bool BuildPhysicsVector (G4int ionZ, const G4String &matName)
virtual G4bool BuildPhysicsVector (G4int ionZ, G4int matZ)
virtual G4bool IsApplicable (G4int atomicNumberIon, G4int atomicNumberElem)
virtual G4bool IsApplicable (G4int atomicNumberIon, const G4String &matIdentifier)
virtual G4PhysicsVector * GetPhysicsVector (G4int atomicNumberIon, G4int atomicNumberElem)
virtual G4PhysicsVector * GetPhysicsVector (G4int atomicNumberIon, const G4String &matIdenfier)
G4double GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, G4int atomicNumberElem)
G4double GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, const G4String &matIdenfier)
G4bool AddPhysicsVector (G4PhysicsVector *physicsVector, G4int atomicNumberIon, const G4String &matIdenfier, G4int atomicNumberElem=0)
G4bool RemovePhysicsVector (G4int atomicNumberIon, const G4String &matIdentifier)
G4bool StorePhysicsTable (const G4String &fileName)
G4bool RetrievePhysicsTable (const G4String &fileName)
void ClearTable ()
void DumpMap ()
Public Member Functions inherited from G4VIonDEDXTable
G4VIonDEDXTable ()
virtual ~G4VIonDEDXTable ()
Private Types
typedef std::pair< G4int, G4int > G4IonDEDXKeyElem
typedef std::pair< G4int,
G4String > G4IonDEDXKeyMat
typedef std::map
< G4IonDEDXKeyElem,
G4PhysicsVector * > G4IonDEDXMapElem
typedef std::map
< G4IonDEDXKeyMat,
G4PhysicsVector * > G4IonDEDXMapMat
Private Member Functions
G4ExtDEDXTable (G4ExtDEDXTable &)=delete
const G4ExtDEDXTable & operator= (const G4ExtDEDXTable &)=delete
G4PhysicsVector * CreatePhysicsVector (G4int vectorType)
G4int FindAtomicNumberElement (G4PhysicsVector *physicsVector)
Private Attributes
G4IonDEDXMapElem dedxMapElements
G4IonDEDXMapMat dedxMapMaterials
Detailed Description
Definition at line 63 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ExtDEDXTable.hh
Member Typedef Documentation
typedef std::pair<G4int, G4int> G4ExtDEDXTable::G4IonDEDXKeyElem private
Definition at line 161 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ExtDEDXTable.hh
typedef std::pair<G4int, G4String> G4ExtDEDXTable::G4IonDEDXKeyMat private
Definition at line 162 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ExtDEDXTable.hh
typedef std::map<G4IonDEDXKeyElem, G4PhysicsVector*> G4ExtDEDXTable::G4IonDEDXMapElem private
Definition at line 164 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 164 of file G4ExtDEDXTable.hh
typedef std::map<G4IonDEDXKeyMat, G4PhysicsVector*> G4ExtDEDXTable::G4IonDEDXMapMat private
Definition at line 165 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ExtDEDXTable.hh
Constructor & Destructor Documentation
G4ExtDEDXTable::G4ExtDEDXTable () explicit
Definition at line 72 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ExtDEDXTable.cc
G4ExtDEDXTable::~G4ExtDEDXTable () virtual
Definition at line 78 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ExtDEDXTable.cc
References ClearTable().
G4ExtDEDXTable::G4ExtDEDXTable (G4ExtDEDXTable &) private delete
Member Function Documentation
G4bool G4ExtDEDXTable::AddPhysicsVector (G4PhysicsVector * physicsVector, G4int atomicNumberIon, const G4String & matIdenfier, G4int atomicNumberElem = 0)
Definition at line 189 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 189 of file G4ExtDEDXTable.cc
References dedxMapElements, dedxMapMaterials, FatalException, and G4Exception().
Referenced by RetrievePhysicsTable().
G4bool G4ExtDEDXTable::BuildPhysicsVector (G4int ionZ, const G4String & matName) virtual
Implements G4VIonDEDXTable.
Definition at line 93 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ExtDEDXTable.cc
References IsApplicable().
G4bool G4ExtDEDXTable::BuildPhysicsVector (G4int ionZ, G4int matZ) virtual
Implements G4VIonDEDXTable.
Definition at line 85 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ExtDEDXTable.cc
References IsApplicable().
void G4ExtDEDXTable::ClearTable ()
Definition at line 519 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 519 of file G4ExtDEDXTable.cc
References dedxMapElements, dedxMapMaterials, and second.
Referenced by ~G4ExtDEDXTable().
G4PhysicsVector * G4ExtDEDXTable::CreatePhysicsVector (G4int vectorType) private
Definition at line 458 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 458 of file G4ExtDEDXTable.cc
References T_G4LPhysicsFreeVector, T_G4PhysicsFreeVector, T_G4PhysicsLinearVector, T_G4PhysicsLnVector, T_G4PhysicsLogVector, and T_G4PhysicsOrderedFreeVector.
Referenced by RetrievePhysicsTable().
void G4ExtDEDXTable::DumpMap ()
Definition at line 537 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 537 of file G4ExtDEDXTable.cc
References dedxMapMaterials, FindAtomicNumberElement(), G4cout, G4endl, right, and second.
G4int G4ExtDEDXTable::FindAtomicNumberElement (G4PhysicsVector * physicsVector) private
Definition at line 496 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 496 of file G4ExtDEDXTable.cc
References dedxMapElements.
Referenced by DumpMap(), and StorePhysicsTable().
G4double G4ExtDEDXTable::GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, G4int atomicNumberElem)
Definition at line 157 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 157 of file G4ExtDEDXTable.cc
References dedxMapElements.
G4double G4ExtDEDXTable::GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, const G4String & matIdenfier)
Definition at line 173 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 173 of file G4ExtDEDXTable.cc
References dedxMapMaterials.
G4PhysicsVector * G4ExtDEDXTable::GetPhysicsVector (G4int atomicNumberIon, G4int atomicNumberElem) virtual
Implements G4VIonDEDXTable.
Definition at line 129 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 129 of file G4ExtDEDXTable.cc
References dedxMapElements.
G4PhysicsVector * G4ExtDEDXTable::GetPhysicsVector (G4int atomicNumberIon, const G4String & matIdenfier) virtual
Implements G4VIonDEDXTable.
Definition at line 143 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 143 of file G4ExtDEDXTable.cc
References dedxMapMaterials.
G4bool G4ExtDEDXTable::IsApplicable (G4int atomicNumberIon, G4int atomicNumberElem) virtual
Implements G4VIonDEDXTable.
Definition at line 101 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ExtDEDXTable.cc
References dedxMapElements.
Referenced by BuildPhysicsVector().
G4bool G4ExtDEDXTable::IsApplicable (G4int atomicNumberIon, const G4String & matIdentifier) virtual
Implements G4VIonDEDXTable.
Definition at line 115 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 115 of file G4ExtDEDXTable.cc
References dedxMapMaterials.
const G4ExtDEDXTable& G4ExtDEDXTable::operator= (const G4ExtDEDXTable &) private delete
G4bool G4ExtDEDXTable::RemovePhysicsVector (G4int atomicNumberIon, const G4String & matIdentifier)
Definition at line 245 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 245 of file G4ExtDEDXTable.cc
References dedxMapElements, dedxMapMaterials, FatalException, G4Exception(), and it.
G4bool G4ExtDEDXTable::RetrievePhysicsTable (const G4String & fileName)
Definition at line 348 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 348 of file G4ExtDEDXTable.cc
References AddPhysicsVector(), CreatePhysicsVector(), FatalException, G4cout, G4endl, G4Exception(), in, and pos().
G4bool G4ExtDEDXTable::StorePhysicsTable (const G4String & fileName)
Definition at line 286 of file G4ExtDEDXTable.cc.
View newest version in sPHENIX GitHub at line 286 of file G4ExtDEDXTable.cc
References dedxMapMaterials, FatalException, FindAtomicNumberElement(), G4endl, G4Exception(), and second.
Member Data Documentation
G4IonDEDXMapElem G4ExtDEDXTable::dedxMapElements private
Definition at line 167 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ExtDEDXTable.hh
Referenced by AddPhysicsVector(), ClearTable(), FindAtomicNumberElement(), GetDEDX(), GetPhysicsVector(), IsApplicable(), and RemovePhysicsVector().
G4IonDEDXMapMat G4ExtDEDXTable::dedxMapMaterials private
Definition at line 168 of file G4ExtDEDXTable.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ExtDEDXTable.hh
Referenced by AddPhysicsVector(), ClearTable(), DumpMap(), GetDEDX(), GetPhysicsVector(), IsApplicable(), RemovePhysicsVector(), and StorePhysicsTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4ExtDEDXTable.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4ExtDEDXTable.cc