ECCE @ EIC Software: G4ICRU90StoppingData Class Reference
G4ICRU90StoppingData Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4ICRU90StoppingData.hh>
Public Member Functions
G4ICRU90StoppingData ()
~G4ICRU90StoppingData ()
void Initialise ()
G4double GetElectronicDEDXforProton (const G4Material *, G4double kinEnergy) const
G4double GetElectronicDEDXforAlpha (const G4Material *, G4double scaledKinEnergy) const
G4int GetIndex (const G4Material *) const
G4int GetIndex (const G4String &) const
G4double GetElectronicDEDXforProton (G4int idx, G4double kinEnergy) const
G4double GetElectronicDEDXforAlpha (G4int idx, G4double scaledKinEnergy) const
G4bool IsApplicable (const G4Material *) const
Private Member Functions
G4double GetDEDX (G4LPhysicsFreeVector *, G4double e) const
void FillData ()
G4LPhysicsFreeVector * AddData (G4int n, const G4double *e, const G4float *dedx)
G4ICRU90StoppingData & operator= (const G4ICRU90StoppingData &right)=delete
G4ICRU90StoppingData (const G4ICRU90StoppingData &)=delete
Private Attributes
const G4Material * materials [nvectors]
G4LPhysicsFreeVector * sdata_proton [nvectors]
G4LPhysicsFreeVector * sdata_alpha [nvectors]
G4bool isInitialized
Static Private Attributes
static constexpr G4int nvectors = 3
Detailed Description
Definition at line 56 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ICRU90StoppingData.hh
Constructor & Destructor Documentation
G4ICRU90StoppingData::G4ICRU90StoppingData () explicit
Definition at line 53 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ICRU90StoppingData.cc
References FillData(), Initialise(), materials, nvectors, sdata_alpha, and sdata_proton.
G4ICRU90StoppingData::~G4ICRU90StoppingData ()
Definition at line 68 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 68 of file G4ICRU90StoppingData.cc
References nvectors, sdata_alpha, and sdata_proton.
G4ICRU90StoppingData::G4ICRU90StoppingData (const G4ICRU90StoppingData &) private delete
Member Function Documentation
G4LPhysicsFreeVector * G4ICRU90StoppingData::AddData (G4int n, const G4double * e, const G4float * dedx) private
Definition at line 163 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 163 of file G4ICRU90StoppingData.cc
References CLHEP::cm2, fac, G4PhysicsVector::FillSecondDerivatives(), CLHEP::g, CLHEP::MeV, n, G4LPhysicsFreeVector::PutValues(), and G4PhysicsVector::SetSpline().
Referenced by FillData().
void G4ICRU90StoppingData::FillData () private
Definition at line 134 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 134 of file G4ICRU90StoppingData.cc
References AddData(), sdata_alpha, and sdata_proton.
Referenced by G4ICRU90StoppingData().
G4double G4ICRU90StoppingData::GetDEDX (G4LPhysicsFreeVector * data, G4double e) const inline private
Definition at line 134 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ICRU90StoppingData.hh
References CEMC_TOWER::emin, G4PhysicsVector::Energy(), and G4PhysicsVector::Value().
Referenced by GetElectronicDEDXforAlpha(), and GetElectronicDEDXforProton().
G4double G4ICRU90StoppingData::GetElectronicDEDXforAlpha (const G4Material * mat, G4double scaledKinEnergy) const
Definition at line 125 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ICRU90StoppingData.cc
References GetDEDX(), GetIndex(), incremental_prev_tag::idx, and sdata_alpha.
Referenced by G4BetheBlochModel::ComputeDEDXPerVolume(), and G4BraggIonModel::DEDX().
G4double G4ICRU90StoppingData::GetElectronicDEDXforAlpha (G4int idx, G4double scaledKinEnergy) const inline
Definition at line 151 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ICRU90StoppingData.hh
References GetDEDX(), nvectors, and sdata_alpha.
G4double G4ICRU90StoppingData::GetElectronicDEDXforProton (const G4Material * mat, G4double kinEnergy) const
Definition at line 116 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 116 of file G4ICRU90StoppingData.cc
References GetDEDX(), GetIndex(), incremental_prev_tag::idx, and sdata_proton.
Referenced by G4BetheBlochModel::ComputeDEDXPerVolume(), and G4BraggModel::DEDX().
G4double G4ICRU90StoppingData::GetElectronicDEDXforProton (G4int idx, G4double kinEnergy) const inline
Definition at line 142 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ICRU90StoppingData.hh
References GetDEDX(), nvectors, and sdata_proton.
G4int G4ICRU90StoppingData::GetIndex (const G4Material * mat) const inline
Definition at line 111 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ICRU90StoppingData.hh
References incremental_prev_tag::idx, and materials.
Referenced by G4BetheBlochModel::ComputeDEDXPerVolume(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), GetElectronicDEDXforAlpha(), and GetElectronicDEDXforProton().
G4int G4ICRU90StoppingData::GetIndex (const G4String & nam) const inline
Definition at line 122 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ICRU90StoppingData.hh
References incremental_prev_tag::idx, and materials.
void G4ICRU90StoppingData::Initialise ()
Definition at line 78 of file G4ICRU90StoppingData.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ICRU90StoppingData.cc
References G4Material::GetMaterialTable(), G4Material::GetName(), G4Material::GetNumberOfMaterials(), isInitialized, mat, materials, and nvectors.
Referenced by G4ICRU90StoppingData(), G4BetheBlochModel::Initialise(), G4BraggIonModel::Initialise(), and G4BraggModel::Initialise().
G4bool G4ICRU90StoppingData::IsApplicable (const G4Material * mat) const inline
Definition at line 106 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ICRU90StoppingData.hh
References materials.
G4ICRU90StoppingData& G4ICRU90StoppingData::operator= (const G4ICRU90StoppingData & right) private delete
Member Data Documentation
G4bool G4ICRU90StoppingData::isInitialized private
Definition at line 101 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ICRU90StoppingData.hh
Referenced by Initialise().
const G4Material* G4ICRU90StoppingData::materials[nvectors] private
Definition at line 98 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ICRU90StoppingData.hh
Referenced by G4ICRU90StoppingData(), GetIndex(), Initialise(), and IsApplicable().
constexpr G4int G4ICRU90StoppingData::nvectors = 3 static private
Definition at line 97 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ICRU90StoppingData.hh
Referenced by G4ICRU90StoppingData(), GetElectronicDEDXforAlpha(), GetElectronicDEDXforProton(), Initialise(), and ~G4ICRU90StoppingData().
G4LPhysicsFreeVector* G4ICRU90StoppingData::sdata_alpha[nvectors] private
Definition at line 100 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ICRU90StoppingData.hh
Referenced by FillData(), G4ICRU90StoppingData(), GetElectronicDEDXforAlpha(), and ~G4ICRU90StoppingData().
G4LPhysicsFreeVector* G4ICRU90StoppingData::sdata_proton[nvectors] private
Definition at line 99 of file G4ICRU90StoppingData.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ICRU90StoppingData.hh
Referenced by FillData(), G4ICRU90StoppingData(), GetElectronicDEDXforProton(), and ~G4ICRU90StoppingData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4ICRU90StoppingData.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4ICRU90StoppingData.cc