ECCE @ EIC Software: G4UserStackingAction Class Reference
G4UserStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4UserStackingAction.hh>
Public Member Functions
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Protected Attributes
G4StackManager * stackManager
Detailed Description
Definition at line 43 of file G4UserStackingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file G4UserStackingAction.hh
Constructor & Destructor Documentation
G4UserStackingAction::G4UserStackingAction ()
Definition at line 36 of file G4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 36 of file G4UserStackingAction.cc
References FatalException, G4Exception(), and G4ParticleTable::GetParticleTable().
G4UserStackingAction::~G4UserStackingAction () virtual
Definition at line 53 of file G4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file G4UserStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack G4UserStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented in G4AdjointStackingAction, StackingAction, StackingAction, DMXStackingAction, StackingAction, StackingAction, G4StackChecker, StackingAction, StackingAction, StackingAction, ExN04StackingAction, RE05StackingAction, StackingAction, StackingAction, StackingAction, CCalStackingAction, WLSStackingAction, ExN04StackingAction, OpNoviceStackingAction, B3StackingAction, B3StackingAction, StackingAction, StackingAction, StackingAction, RE01StackingAction, pyG4UserStackingAction::CB_G4UserStackingAction, LXeStackingAction, XPhononStackingAction, F04StackingAction, and PHG4PhenixStackingAction.
Definition at line 57 of file G4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UserStackingAction.cc
References fUrgent.
Referenced by pyG4UserStackingAction::CB_G4UserStackingAction::ClassifyNewTrack(), CCalStackingAction::ClassifyNewTrack(), G4AdjointStackingAction::ClassifyNewTrack(), export_G4UserStackingAction(), G4StackManager::PrepareNewEvent(), G4StackManager::PushOneTrack(), and G4StackManager::ReClassify().
void G4UserStackingAction::NewStage () virtual
Reimplemented in G4AdjointStackingAction, DMXStackingAction, StackingAction, pyG4UserStackingAction::CB_G4UserStackingAction, G4StackChecker, StackingAction, StackingAction, ExN04StackingAction, RE05StackingAction, CCalStackingAction, WLSStackingAction, ExN04StackingAction, StackingAction, StackingAction, StackingAction, OpNoviceStackingAction, RE01StackingAction, LXeStackingAction, F04StackingAction, and StackingAction.
Definition at line 62 of file G4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 62 of file G4UserStackingAction.cc
Referenced by export_G4UserStackingAction(), pyG4UserStackingAction::CB_G4UserStackingAction::NewStage(), G4AdjointStackingAction::NewStage(), and G4StackManager::PopNextTrack().
void G4UserStackingAction::PrepareNewEvent () virtual
Reimplemented in G4AdjointStackingAction, pyG4UserStackingAction::CB_G4UserStackingAction, DMXStackingAction, G4StackChecker, ExN04StackingAction, RE05StackingAction, CCalStackingAction, WLSStackingAction, ExN04StackingAction, OpNoviceStackingAction, RE01StackingAction, LXeStackingAction, F04StackingAction, and PHG4PhenixStackingAction.
Definition at line 65 of file G4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 65 of file G4UserStackingAction.cc
Referenced by export_G4UserStackingAction(), pyG4UserStackingAction::CB_G4UserStackingAction::PrepareNewEvent(), G4AdjointStackingAction::PrepareNewEvent(), and G4StackManager::PrepareNewEvent().
void G4UserStackingAction::SetStackManager (G4StackManager * value) inline
Definition at line 51 of file G4UserStackingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file G4UserStackingAction.hh
References stackManager.
Referenced by G4StackManager::SetUserStackingAction().
Member Data Documentation
G4StackManager* G4UserStackingAction::stackManager protected
Definition at line 49 of file G4UserStackingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file G4UserStackingAction.hh
Referenced by RE01StackingAction::NewStage(), StackingAction::NewStage(), ExN04StackingAction::NewStage(), CCalStackingAction::NewStage(), RE05StackingAction::NewStage(), G4AdjointStackingAction::NewStage(), and SetStackManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4UserStackingAction.hh
geant4/tree/geant4-10.6-release/source/event/src/G4UserStackingAction.cc