ECCE @ EIC Software: CLHEP::HepBoostZ Class Reference
CLHEP::HepBoostZ Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/BoostZ.h>
Public Member Functions
HepBoostZ ()
HepBoostZ (const HepBoostZ &b)
HepBoostZ (HepBoostZ &&b)=default
HepBoostZ & operator= (const HepBoostZ &m)
HepBoostZ & operator= (HepBoostZ &&m)=default
HepBoostZ & set (double beta)
HepBoostZ (double beta)
double beta () const
double gamma () const
Hep3Vector boostVector () const
Hep3Vector getDirection () const
double xx () const
double xy () const
double xz () const
double xt () const
double yx () const
double yy () const
double yz () const
double yt () const
double zx () const
double zy () const
double zz () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
HepRep4x4 rep4x4 () const
HepRep4x4Symmetric rep4x4Symmetric () const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
int compare (const HepBoostZ &b) const
bool operator== (const HepBoostZ &b) const
bool operator!= (const HepBoostZ &b) const
bool operator<= (const HepBoostZ &b) const
bool operator>= (const HepBoostZ &b) const
bool operator< (const HepBoostZ &b) const
bool operator> (const HepBoostZ &b) const
bool isIdentity () const
double distance2 (const HepBoostZ &b) const
double distance2 (const HepBoost &b) const
double distance2 (const HepRotation &r) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoostZ &b) const
double howNear (const HepBoost &b) const
double howNear (const HepRotation &r) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoostZ &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepBoost &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepBoostZ operator* (const HepBoostZ &b) const
HepLorentzRotation operator* (const HepBoost &b) const
HepLorentzRotation operator* (const HepRotation &r) const
HepLorentzRotation operator* (const HepLorentzRotation &lt) const
HepBoostZ inverse () const
HepBoostZ & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepLorentzVector vectorMultiplication (const HepLorentzVector &w) const
HepLorentzRotation matrixMultiplication (const HepRep4x4 &m) const
HepLorentzRotation matrixMultiplication (const HepRep4x4Symmetric &m) const
HepBoostZ (double beta, double gamma)
Protected Attributes
double beta_
double gamma_
Friends
HepBoostZ inverseOf (const HepBoostZ &b)
Detailed Description
Author
Definition at line 41 of file BoostZ.h.
View newest version in sPHENIX GitHub at line 41 of file BoostZ.h
Constructor & Destructor Documentation
CLHEP::HepBoostZ::HepBoostZ () inline
Referenced by operator*().
CLHEP::HepBoostZ::HepBoostZ (const HepBoostZ & b) inline
CLHEP::HepBoostZ::HepBoostZ (HepBoostZ && b) inline default
CLHEP::HepBoostZ::HepBoostZ (double beta) inline
CLHEP::HepBoostZ::HepBoostZ (double beta, double gamma) inline protected
Member Function Documentation
double CLHEP::HepBoostZ::beta () const inline
Referenced by operator*().
Hep3Vector CLHEP::HepBoostZ::boostVector () const inline
Referenced by decompose().
HepLorentzVector CLHEP::HepBoostZ::col1 () const inline
HepLorentzVector CLHEP::HepBoostZ::col2 () const inline
HepLorentzVector CLHEP::HepBoostZ::col3 () const inline
HepLorentzVector CLHEP::HepBoostZ::col4 () const inline
int CLHEP::HepBoostZ::compare (const HepBoostZ & b) const inline
void CLHEP::HepBoostZ::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 56 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 56 of file BoostZ.cc
References boostVector().
void CLHEP::HepBoostZ::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 63 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 63 of file BoostZ.cc
References boostVector().
void CLHEP::HepBoostZ::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 68 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 68 of file BoostZ.cc
References boostVector().
void CLHEP::HepBoostZ::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 75 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 75 of file BoostZ.cc
References boostVector().
double CLHEP::HepBoostZ::distance2 (const HepBoostZ & b) const inline
Referenced by distance2(), and isNear().
double CLHEP::HepBoostZ::distance2 (const HepBoost & b) const
Definition at line 82 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 82 of file BoostZ.cc
References CLHEP::HepBoost::distance2().
double CLHEP::HepBoostZ::distance2 (const HepRotation & r) const
Definition at line 86 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 86 of file BoostZ.cc
References norm2(), and CLHEP::HepRotation::norm2().
double CLHEP::HepBoostZ::distance2 (const HepLorentzRotation & lt) const
Definition at line 92 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 92 of file BoostZ.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
double CLHEP::HepBoostZ::gamma () const inline
Hep3Vector CLHEP::HepBoostZ::getDirection () const inline
static double CLHEP::HepBoostZ::getTolerance () inline static
double CLHEP::HepBoostZ::howNear (const HepBoostZ & b) const inline
double CLHEP::HepBoostZ::howNear (const HepBoost & b) const inline
double CLHEP::HepBoostZ::howNear (const HepRotation & r) const inline
double CLHEP::HepBoostZ::howNear (const HepLorentzRotation & lt) const inline
HepBoostZ CLHEP::HepBoostZ::inverse () const inline
HepBoostZ& CLHEP::HepBoostZ::invert () inline
bool CLHEP::HepBoostZ::isIdentity () const inline
bool CLHEP::HepBoostZ::isNear (const HepBoostZ & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoostZ::isNear (const HepBoost & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoostZ::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 101 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 101 of file BoostZ.cc
References norm2(), and CLHEP::HepRotation::norm2().
bool CLHEP::HepBoostZ::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 108 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 108 of file BoostZ.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
HepLorentzRotation CLHEP::HepBoostZ::matrixMultiplication (const HepRep4x4 & m) const protected
HepLorentzRotation CLHEP::HepBoostZ::matrixMultiplication (const HepRep4x4Symmetric & m) const protected
double CLHEP::HepBoostZ::norm2 () const inline
Referenced by distance2(), and isNear().
bool CLHEP::HepBoostZ::operator!= (const HepBoostZ & b) const inline
HepLorentzVector CLHEP::HepBoostZ::operator() (const HepLorentzVector & w) const inline
HepLorentzVector CLHEP::HepBoostZ::operator* (const HepLorentzVector & w) const inline
HepBoostZ CLHEP::HepBoostZ::operator* (const HepBoostZ & b) const
Definition at line 138 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 138 of file BoostZ.cc
References beta(), and HepBoostZ().
HepLorentzRotation CLHEP::HepBoostZ::operator* (const HepBoost & b) const
Definition at line 141 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 141 of file BoostZ.cc
References b.
HepLorentzRotation CLHEP::HepBoostZ::operator* (const HepRotation & r) const
Definition at line 145 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 145 of file BoostZ.cc
References r.
HepLorentzRotation CLHEP::HepBoostZ::operator* (const HepLorentzRotation & lt) const
Definition at line 149 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 149 of file BoostZ.cc
bool CLHEP::HepBoostZ::operator< (const HepBoostZ & b) const inline
bool CLHEP::HepBoostZ::operator<= (const HepBoostZ & b) const inline
HepBoostZ& CLHEP::HepBoostZ::operator= (const HepBoostZ & m) inline
HepBoostZ& CLHEP::HepBoostZ::operator= (HepBoostZ && m) inline default
bool CLHEP::HepBoostZ::operator== (const HepBoostZ & b) const inline
bool CLHEP::HepBoostZ::operator> (const HepBoostZ & b) const inline
bool CLHEP::HepBoostZ::operator>= (const HepBoostZ & b) const inline
std::ostream & CLHEP::HepBoostZ::print (std::ostream & os) const
Definition at line 156 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 156 of file BoostZ.cc
References beta_, and gamma_.
void CLHEP::HepBoostZ::rectify ()
Definition at line 121 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 121 of file BoostZ.cc
References beta_, and gamma_.
HepRep4x4 CLHEP::HepBoostZ::rep4x4 () const
Definition at line 38 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 38 of file BoostZ.cc
References beta_, and gamma_.
HepRep4x4Symmetric CLHEP::HepBoostZ::rep4x4Symmetric () const
Definition at line 46 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 46 of file BoostZ.cc
References beta_, and gamma_.
HepLorentzVector CLHEP::HepBoostZ::row1 () const inline
HepLorentzVector CLHEP::HepBoostZ::row2 () const inline
HepLorentzVector CLHEP::HepBoostZ::row3 () const inline
HepLorentzVector CLHEP::HepBoostZ::row4 () const inline
HepBoostZ & CLHEP::HepBoostZ::set (double beta)
Definition at line 22 of file BoostZ.cc.
View newest version in sPHENIX GitHub at line 22 of file BoostZ.cc
References beta_, and gamma_.
static double CLHEP::HepBoostZ::setTolerance (double tol) inline static
double CLHEP::HepBoostZ::tt () const inline
double CLHEP::HepBoostZ::tx () const inline
double CLHEP::HepBoostZ::ty () const inline
double CLHEP::HepBoostZ::tz () const inline
HepLorentzVector CLHEP::HepBoostZ::vectorMultiplication (const HepLorentzVector & w) const inline protected
double CLHEP::HepBoostZ::xt () const inline
double CLHEP::HepBoostZ::xx () const inline
double CLHEP::HepBoostZ::xy () const inline
double CLHEP::HepBoostZ::xz () const inline
double CLHEP::HepBoostZ::yt () const inline
double CLHEP::HepBoostZ::yx () const inline
double CLHEP::HepBoostZ::yy () const inline
double CLHEP::HepBoostZ::yz () const inline
double CLHEP::HepBoostZ::zt () const inline
double CLHEP::HepBoostZ::zx () const inline
double CLHEP::HepBoostZ::zy () const inline
double CLHEP::HepBoostZ::zz () const inline
Friends And Related Function Documentation
HepBoostZ inverseOf (const HepBoostZ & b) friend
Member Data Documentation
double CLHEP::HepBoostZ::beta_ protected
Definition at line 210 of file BoostZ.h.
View newest version in sPHENIX GitHub at line 210 of file BoostZ.h
Referenced by print(), rectify(), rep4x4(), rep4x4Symmetric(), and set().
double CLHEP::HepBoostZ::gamma_ protected
Definition at line 211 of file BoostZ.h.
View newest version in sPHENIX GitHub at line 211 of file BoostZ.h
Referenced by print(), rectify(), rep4x4(), rep4x4Symmetric(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/BoostZ.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/BoostZ.cc