ECCE @ EIC Software: B1PrimaryGeneratorAction Class Reference
B1PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B1/include/B1PrimaryGeneratorAction.hh>
Public Member Functions
B1PrimaryGeneratorAction ()
virtual ~B1PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
B1PrimaryGeneratorAction ()
virtual ~B1PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
B1PrimaryGeneratorAction ()
virtual ~B1PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
G4Box * fEnvelopeBox
Detailed Description
The primary generator action class with particle gun.
The default kinematic is a 6 MeV gamma, randomly distribued in front of the phantom across 80% of the (X,Y) phantom size.
Definition at line 46 of file B1PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 46 of file B1PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
B1PrimaryGeneratorAction::B1PrimaryGeneratorAction ()
Definition at line 44 of file B1PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 44 of file B1PrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), MeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), and G4ParticleGun::SetParticleMomentumDirection().
B1PrimaryGeneratorAction::~B1PrimaryGeneratorAction () virtual
Definition at line 64 of file B1PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 64 of file B1PrimaryGeneratorAction.cc
References fParticleGun.
B1PrimaryGeneratorAction::B1PrimaryGeneratorAction ()
virtual B1PrimaryGeneratorAction::~B1PrimaryGeneratorAction () virtual
B1PrimaryGeneratorAction::B1PrimaryGeneratorAction ()
virtual B1PrimaryGeneratorAction::~B1PrimaryGeneratorAction () virtual
Member Function Documentation
void B1PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 71 of file B1PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 71 of file B1PrimaryGeneratorAction.cc
References fEnvelopeBox, fParticleGun, G4Exception(), G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetSolid(), G4LogicalVolumeStore::GetVolume(), G4Box::GetXHalfLength(), G4Box::GetZHalfLength(), JustWarning, G4VPrimaryGenerator::SetParticlePosition(), and G4InuclParticleNames::z0.
virtual void B1PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void B1PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
const G4ParticleGun* B1PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 56 of file B1PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file B1PrimaryGeneratorAction.hh
References fParticleGun.
const G4ParticleGun* B1PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 56 of file B1PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file B1PrimaryGeneratorAction.hh
References fParticleGun.
Referenced by B1RunAction::EndOfRunAction(), and B1ConRunAction::EndOfRunAction().
const G4ParticleGun* B1PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 56 of file B1PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file B1PrimaryGeneratorAction.hh
References fParticleGun.
Member Data Documentation
G4Box * B1PrimaryGeneratorAction::fEnvelopeBox private
Definition at line 60 of file B1PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file B1PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4ParticleGun * B1PrimaryGeneratorAction::fParticleGun private
Definition at line 59 of file B1PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file B1PrimaryGeneratorAction.hh
Referenced by B1PrimaryGeneratorAction(), GeneratePrimaries(), GetParticleGun(), and ~B1PrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B1/include/B1PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/include/B1PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B1/src/B1PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/src/B1PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/src/B1PrimaryGeneratorAction.cc