ECCE @ EIC Software: G4FragmentingString Class Reference
G4FragmentingString Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4FragmentingString.hh>
Public Member Functions
G4FragmentingString (const G4FragmentingString &right)
G4FragmentingString (const G4ExcitedString &excited)
G4FragmentingString (const G4FragmentingString &old, G4ParticleDefinition *newdecay, const G4LorentzVector *momentum)
G4FragmentingString (const G4FragmentingString &old, G4ParticleDefinition *newdecay)
~G4FragmentingString ()
G4FragmentingString & operator= (const G4FragmentingString &)
G4bool operator== (const G4FragmentingString &right) const
G4bool operator!= (const G4FragmentingString &right) const
G4LorentzVector Get4Momentum () const
G4ThreeVector StablePt ()
G4ThreeVector DecayPt ()
G4double LightConePlus ()
G4double LightConeMinus ()
G4double LightConeDecay ()
G4double Mass () const
G4double Mass2 () const
G4double MassT2 () const
G4ParticleDefinition * GetLeftParton (void) const
G4ParticleDefinition * GetRightParton (void) const
G4ParticleDefinition * GetStableParton () const
G4ParticleDefinition * GetDecayParton () const
void SetLeftPartonStable ()
void SetRightPartonStable ()
G4int GetDecayDirection () const
G4bool DecayIsQuark ()
G4bool StableIsQuark ()
G4bool IsAFourQuarkString (void) const
G4LorentzVector GetPstring ()
G4LorentzVector GetPleft ()
void SetPleft (G4LorentzVector a4momentum)
G4LorentzVector GetPright ()
void SetPright (G4LorentzVector a4momentum)
void LorentzRotate (const G4LorentzRotation &rotation)
G4LorentzRotation TransformToCenterOfMass ()
G4LorentzRotation TransformToAlignedCms ()
void Boost (G4ThreeVector &Velocity)
Private Types
enum DecaySide { None, Left, Right }
Private Attributes
G4ParticleDefinition * LeftParton
G4ParticleDefinition * RightParton
G4ThreeVector Ptleft
G4ThreeVector Ptright
G4double Pplus
G4double Pminus
G4ParticleDefinition * theStableParton
G4ParticleDefinition * theDecayParton
G4LorentzVector Pstring
G4LorentzVector Pleft
G4LorentzVector Pright
DecaySide decaying
Detailed Description
Definition at line 49 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FragmentingString.hh
Member Enumeration Documentation
enum G4FragmentingString::DecaySide private
Enumerator:
None
Left
Right
Definition at line 113 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 113 of file G4FragmentingString.hh
Constructor & Destructor Documentation
G4FragmentingString::G4FragmentingString (const G4FragmentingString & right)
Definition at line 46 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 46 of file G4FragmentingString.cc
References decaying, LeftParton, Pleft, Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, RightParton, theDecayParton, and theStableParton.
G4FragmentingString::G4FragmentingString (const G4ExcitedString & excited)
Definition at line 84 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 84 of file G4FragmentingString.cc
References decaying, CLHEP::HepLorentzVector::e(), G4Parton::Get4Momentum(), G4ExcitedString::Get4Momentum(), G4Parton::GetDefinition(), G4ExcitedString::GetDirection(), G4ExcitedString::GetLeftParton(), G4ExcitedString::GetRightParton(), Left, LeftParton, P, Pleft, Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, CLHEP::HepLorentzVector::pz(), Right, RightParton, CLHEP::Hep3Vector::setZ(), theDecayParton, theStableParton, and CLHEP::HepLorentzVector::vect().
G4FragmentingString::G4FragmentingString (const G4FragmentingString & old, G4ParticleDefinition * newdecay, const G4LorentzVector * momentum)
Definition at line 108 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 108 of file G4FragmentingString.cc
References CLHEP::HepLorentzVector::boostVector(), decaying, CLHEP::HepLorentzVector::e(), GetLeftParton(), GetRightParton(), Left, LeftParton, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::minus(), None, Pleft, CLHEP::HepLorentzVector::plus(), Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, Right, RightParton, CLHEP::Hep3Vector::setZ(), theDecayParton, theStableParton, and CLHEP::HepLorentzVector::vect().
G4FragmentingString::G4FragmentingString (const G4FragmentingString & old, G4ParticleDefinition * newdecay)
Definition at line 175 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 175 of file G4FragmentingString.cc
References decaying, Left, LeftParton, None, Pleft, Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, Right, RightParton, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), theDecayParton, and theStableParton.
G4FragmentingString::~G4FragmentingString ()
Definition at line 209 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 209 of file G4FragmentingString.cc
Member Function Documentation
void G4FragmentingString::Boost (G4ThreeVector & Velocity)
G4bool G4FragmentingString::DecayIsQuark ()
Definition at line 252 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 252 of file G4FragmentingString.cc
References G4ParticleDefinition::GetParticleSubType(), and theDecayParton.
Referenced by G4QGSMFragmentation::SplitLast(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
G4ThreeVector G4FragmentingString::DecayPt ()
Definition at line 272 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 272 of file G4FragmentingString.cc
References decaying, Left, Ptleft, Ptright, and Right.
G4LorentzVector G4FragmentingString::Get4Momentum () const
Definition at line 301 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 301 of file G4FragmentingString.cc
References momentum, Pminus, Pplus, Ptleft, Ptright, CLHEP::HepLorentzVector::setE(), and CLHEP::HepLorentzVector::setPz().
G4int G4FragmentingString::GetDecayDirection () const
Definition at line 233 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 233 of file G4FragmentingString.cc
References decaying, Left, and Right.
Referenced by G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::Loop_toFragmentString(), G4LundStringFragmentation::SplitEandP(), and G4QGSMFragmentation::SplitEandP().
G4ParticleDefinition * G4FragmentingString::GetDecayParton () const inline
Definition at line 137 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 137 of file G4FragmentingString.hh
References theDecayParton.
Referenced by G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
G4ParticleDefinition * G4FragmentingString::GetLeftParton (void) const inline
Definition at line 143 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 143 of file G4FragmentingString.hh
References LeftParton.
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4FragmentingString(), G4VLongitudinalStringDecay::PossibleHadronMass(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), SetLeftPartonStable(), G4VLongitudinalStringDecay::SetMinimalStringMass(), SetRightPartonStable(), G4QGSMFragmentation::SplitLast(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
G4LorentzVector G4FragmentingString::GetPleft ()
Definition at line 331 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 331 of file G4FragmentingString.cc
References Pleft.
G4LorentzVector G4FragmentingString::GetPright ()
Definition at line 336 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 336 of file G4FragmentingString.cc
References Pright.
G4LorentzVector G4FragmentingString::GetPstring ()
Definition at line 326 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 326 of file G4FragmentingString.cc
References Pstring.
G4ParticleDefinition * G4FragmentingString::GetRightParton (void) const inline
Definition at line 149 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 149 of file G4FragmentingString.hh
References RightParton.
Referenced by G4FragmentingString(), G4VLongitudinalStringDecay::PossibleHadronMass(), SetLeftPartonStable(), G4VLongitudinalStringDecay::SetMinimalStringMass(), SetRightPartonStable(), G4QGSMFragmentation::SplitLast(), G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
G4ParticleDefinition * G4FragmentingString::GetStableParton () const inline
Definition at line 131 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 131 of file G4FragmentingString.hh
References theStableParton.
G4bool G4FragmentingString::IsAFourQuarkString (void) const
Definition at line 244 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 244 of file G4FragmentingString.cc
References G4ParticleDefinition::GetParticleSubType(), LeftParton, and RightParton.
Referenced by G4LundStringFragmentation::FragmentString(), G4VLongitudinalStringDecay::PossibleHadronMass(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::StopFragmenting(), and G4LundStringFragmentation::StopFragmenting().
G4double G4FragmentingString::LightConeDecay ()
Definition at line 292 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 292 of file G4FragmentingString.cc
References decaying, Left, Pminus, Pplus, and Right.
G4double G4FragmentingString::LightConeMinus ()
Definition at line 287 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 287 of file G4FragmentingString.cc
References Pminus.
G4double G4FragmentingString::LightConePlus ()
Definition at line 282 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 282 of file G4FragmentingString.cc
References Pplus.
void G4FragmentingString::LorentzRotate (const G4LorentzRotation & rotation) inline
Definition at line 156 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 156 of file G4FragmentingString.hh
References CLHEP::HepLorentzVector::minus(), Pleft, CLHEP::HepLorentzVector::plus(), Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, SetPleft(), SetPright(), and CLHEP::Hep3Vector::setZ().
Referenced by G4LundStringFragmentation::Loop_toFragmentString().
G4double G4FragmentingString::Mass () const
Definition at line 315 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 315 of file G4FragmentingString.cc
References CLHEP::HepLorentzVector::mag(), and Pstring.
Referenced by G4VLongitudinalStringDecay::ProduceOneHadron(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4QGSMFragmentation::Splitup(), G4QGSMFragmentation::StopFragmenting(), and G4LundStringFragmentation::StopFragmenting().
G4double G4FragmentingString::Mass2 () const
Definition at line 309 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 309 of file G4FragmentingString.cc
References CLHEP::HepLorentzVector::mag2(), and Pstring.
G4double G4FragmentingString::MassT2 () const
Definition at line 321 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 321 of file G4FragmentingString.cc
References Pminus, and Pplus.
G4bool G4FragmentingString::operator!= (const G4FragmentingString & right) const inline
Definition at line 124 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 124 of file G4FragmentingString.hh
References right.
G4FragmentingString & G4FragmentingString::operator= (const G4FragmentingString & old)
Definition at line 62 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 62 of file G4FragmentingString.cc
References decaying, LeftParton, Pleft, Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, RightParton, theDecayParton, and theStableParton.
G4bool G4FragmentingString::operator== (const G4FragmentingString & right) const inline
Definition at line 118 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 118 of file G4FragmentingString.hh
References right.
void G4FragmentingString::SetLeftPartonStable ()
Definition at line 215 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 215 of file G4FragmentingString.cc
References decaying, GetLeftParton(), GetRightParton(), Right, theDecayParton, and theStableParton.
void G4FragmentingString::SetPleft (G4LorentzVector a4momentum) inline
Definition at line 206 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 206 of file G4FragmentingString.hh
References Pleft.
Referenced by LorentzRotate().
void G4FragmentingString::SetPright (G4LorentzVector a4momentum) inline
Definition at line 212 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 212 of file G4FragmentingString.hh
References Pright.
Referenced by LorentzRotate().
void G4FragmentingString::SetRightPartonStable ()
Definition at line 224 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 224 of file G4FragmentingString.cc
References decaying, GetLeftParton(), GetRightParton(), Left, theDecayParton, and theStableParton.
G4bool G4FragmentingString::StableIsQuark ()
Definition at line 257 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 257 of file G4FragmentingString.cc
References G4ParticleDefinition::GetParticleSubType(), and theStableParton.
Referenced by G4QGSMFragmentation::SplitLast().
G4ThreeVector G4FragmentingString::StablePt ()
Definition at line 264 of file G4FragmentingString.cc.
View newest version in sPHENIX GitHub at line 264 of file G4FragmentingString.cc
References decaying, Left, Ptleft, Ptright, and Right.
G4LorentzRotation G4FragmentingString::TransformToAlignedCms () inline
Definition at line 184 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 184 of file G4FragmentingString.hh
References CLHEP::HepLorentzVector::boostVector(), CLHEP::HepLorentzVector::minus(), momentum, Pleft, CLHEP::HepLorentzVector::plus(), Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, CLHEP::HepLorentzVector::rotateY(), and CLHEP::HepLorentzVector::rotateZ().
Referenced by G4LundStringFragmentation::Loop_toFragmentString().
G4LorentzRotation G4FragmentingString::TransformToCenterOfMass () inline
Definition at line 168 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 168 of file G4FragmentingString.hh
References CLHEP::HepLorentzVector::boostVector(), CLHEP::HepLorentzVector::minus(), momentum, Pleft, CLHEP::HepLorentzVector::plus(), Pminus, Pplus, Pright, Pstring, Ptleft, Ptright, CLHEP::Hep3Vector::setZ(), and CLHEP::HepLorentzVector::vect().
Member Data Documentation
DecaySide G4FragmentingString::decaying private
Definition at line 114 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 114 of file G4FragmentingString.hh
Referenced by DecayPt(), G4FragmentingString(), GetDecayDirection(), LightConeDecay(), operator=(), SetLeftPartonStable(), SetRightPartonStable(), and StablePt().
G4ParticleDefinition* G4FragmentingString::LeftParton private
Definition at line 106 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 106 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), GetLeftParton(), IsAFourQuarkString(), and operator=().
G4LorentzVector G4FragmentingString::Pleft private
Definition at line 112 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 112 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), GetPleft(), LorentzRotate(), operator=(), SetPleft(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4double G4FragmentingString::Pminus private
Definition at line 108 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 108 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), Get4Momentum(), LightConeDecay(), LightConeMinus(), LorentzRotate(), MassT2(), operator=(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4double G4FragmentingString::Pplus private
Definition at line 108 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 108 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), Get4Momentum(), LightConeDecay(), LightConePlus(), LorentzRotate(), MassT2(), operator=(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4LorentzVector G4FragmentingString::Pright private
Definition at line 112 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 112 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), GetPright(), LorentzRotate(), operator=(), SetPright(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4LorentzVector G4FragmentingString::Pstring private
Definition at line 112 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 112 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), GetPstring(), LorentzRotate(), Mass(), Mass2(), operator=(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4ThreeVector G4FragmentingString::Ptleft private
Definition at line 107 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 107 of file G4FragmentingString.hh
Referenced by DecayPt(), G4FragmentingString(), Get4Momentum(), LorentzRotate(), operator=(), StablePt(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4ThreeVector G4FragmentingString::Ptright private
Definition at line 107 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 107 of file G4FragmentingString.hh
Referenced by DecayPt(), G4FragmentingString(), Get4Momentum(), LorentzRotate(), operator=(), StablePt(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4ParticleDefinition * G4FragmentingString::RightParton private
Definition at line 106 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 106 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), GetRightParton(), IsAFourQuarkString(), and operator=().
G4ParticleDefinition * G4FragmentingString::theDecayParton private
Definition at line 110 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 110 of file G4FragmentingString.hh
Referenced by DecayIsQuark(), G4FragmentingString(), GetDecayParton(), operator=(), SetLeftPartonStable(), and SetRightPartonStable().
G4ParticleDefinition* G4FragmentingString::theStableParton private
Definition at line 110 of file G4FragmentingString.hh.
View newest version in sPHENIX GitHub at line 110 of file G4FragmentingString.hh
Referenced by G4FragmentingString(), GetStableParton(), operator=(), SetLeftPartonStable(), SetRightPartonStable(), and StableIsQuark().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4FragmentingString.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/src/G4FragmentingString.cc