ECCE @ EIC Software: G4HadronPhysicsFTF_BIC Class Reference
G4HadronPhysicsFTF_BIC Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTF_BIC.hh>
Public Member Functions
G4HadronPhysicsFTF_BIC (G4int verbose=1)
G4HadronPhysicsFTF_BIC (const G4String &name, G4bool quasiElastic=false)
virtual ~G4HadronPhysicsFTF_BIC ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Member Functions
virtual void CreateModels ()
virtual void Neutron ()
virtual void Proton ()
virtual void Pion ()
virtual void Kaon ()
virtual void Others ()
virtual void DumpBanner ()
virtual void ExtraConfiguration ()
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes
G4bool QuasiElastic
G4double maxBIC_pion
G4double minBERT_pion
G4double maxBERT_pion
G4double maxBERT_kaon
G4double maxBIC_proton
G4double maxBIC_neutron
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 51 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 51 of file G4HadronPhysicsFTF_BIC.hh
Constructor & Destructor Documentation
G4HadronPhysicsFTF_BIC::G4HadronPhysicsFTF_BIC (G4int verbose = 1)
Definition at line 76 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 76 of file G4HadronPhysicsFTF_BIC.cc
G4HadronPhysicsFTF_BIC::G4HadronPhysicsFTF_BIC (const G4String & name, G4bool quasiElastic = false)
Definition at line 79 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsFTF_BIC.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), GeV, G4HadronicParameters::Instance(), maxBERT_kaon, maxBERT_pion, maxBIC_neutron, maxBIC_pion, maxBIC_proton, and minBERT_pion.
G4HadronPhysicsFTF_BIC::~G4HadronPhysicsFTF_BIC () virtual
Definition at line 89 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 89 of file G4HadronPhysicsFTF_BIC.cc
Member Function Documentation
void G4HadronPhysicsFTF_BIC::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 182 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 182 of file G4HadronPhysicsFTF_BIC.cc
References G4MesonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsFTF_BIC::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 194 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 194 of file G4HadronPhysicsFTF_BIC.cc
References CreateModels(), DumpBanner(), ExtraConfiguration(), and G4Threading::IsMasterThread().
void G4HadronPhysicsFTF_BIC::CreateModels () protected virtual
Definition at line 92 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 92 of file G4HadronPhysicsFTF_BIC.cc
References Kaon(), Neutron(), Others(), Pion(), and Proton().
Referenced by ConstructProcess().
virtual void G4HadronPhysicsFTF_BIC::DumpBanner () inline protected virtual
Definition at line 70 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HadronPhysicsFTF_BIC.hh
Referenced by ConstructProcess().
void G4HadronPhysicsFTF_BIC::ExtraConfiguration () protected virtual
Definition at line 205 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 205 of file G4HadronPhysicsFTF_BIC.cc
References G4HadronicProcess::AddDataSet(), G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindInelasticProcess(), G4InuclParticleNames::neutron, G4Neutron::Neutron(), and G4HadronicProcess::RegisterMe().
Referenced by ConstructProcess().
void G4HadronPhysicsFTF_BIC::Kaon () protected virtual
Definition at line 154 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 154 of file G4HadronPhysicsFTF_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), k, maxBERT_kaon, and QuasiElastic.
Referenced by CreateModels().
void G4HadronPhysicsFTF_BIC::Neutron () protected virtual
Definition at line 101 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 101 of file G4HadronPhysicsFTF_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), maxBIC_neutron, G4InuclParticleNames::neu, and QuasiElastic.
Referenced by CreateModels().
void G4HadronPhysicsFTF_BIC::Others () protected virtual
Definition at line 168 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 168 of file G4HadronPhysicsFTF_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), and QuasiElastic.
Referenced by CreateModels().
void G4HadronPhysicsFTF_BIC::Pion () protected virtual
Definition at line 135 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 135 of file G4HadronPhysicsFTF_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), maxBERT_pion, maxBIC_pion, minBERT_pion, pi, and QuasiElastic.
Referenced by CreateModels().
void G4HadronPhysicsFTF_BIC::Proton () protected virtual
Definition at line 121 of file G4HadronPhysicsFTF_BIC.cc.
View newest version in sPHENIX GitHub at line 121 of file G4HadronPhysicsFTF_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), maxBIC_proton, G4InuclParticleNames::pro, and QuasiElastic.
Referenced by CreateModels().
Member Data Documentation
G4double G4HadronPhysicsFTF_BIC::maxBERT_kaon protected
Definition at line 77 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HadronPhysicsFTF_BIC.hh
Referenced by G4HadronPhysicsFTF_BIC(), and Kaon().
G4double G4HadronPhysicsFTF_BIC::maxBERT_pion protected
Definition at line 76 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadronPhysicsFTF_BIC.hh
Referenced by G4HadronPhysicsFTF_BIC(), and Pion().
G4double G4HadronPhysicsFTF_BIC::maxBIC_neutron protected
Definition at line 79 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsFTF_BIC.hh
Referenced by G4HadronPhysicsFTF_BIC(), and Neutron().
G4double G4HadronPhysicsFTF_BIC::maxBIC_pion protected
Definition at line 74 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadronPhysicsFTF_BIC.hh
Referenced by G4HadronPhysicsFTF_BIC(), and Pion().
G4double G4HadronPhysicsFTF_BIC::maxBIC_proton protected
Definition at line 78 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronPhysicsFTF_BIC.hh
Referenced by G4HadronPhysicsFTF_BIC(), and Proton().
G4double G4HadronPhysicsFTF_BIC::minBERT_pion protected
Definition at line 75 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HadronPhysicsFTF_BIC.hh
Referenced by G4HadronPhysicsFTF_BIC(), and Pion().
G4bool G4HadronPhysicsFTF_BIC::QuasiElastic protected
Definition at line 62 of file G4HadronPhysicsFTF_BIC.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HadronPhysicsFTF_BIC.hh
Referenced by Kaon(), Neutron(), Others(), Pion(), and Proton().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTF_BIC.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsFTF_BIC.cc