ECCE @ EIC Software: G4ParticleHPFissionFS Class Reference
G4ParticleHPFissionFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionFS.hh>
Public Member Functions
G4ParticleHPFissionFS ()
~G4ParticleHPFissionFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aFSType, G4ParticleDefinition *)
G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)
G4ParticleHPFinalState * New ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
virtual G4double GetXsec (G4double)
virtual G4ParticleHPVector * GetXsec ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Attributes
G4ParticleHPFSFissionFS theFS
G4ParticleHPFCFissionFS theFC
G4ParticleHPSCFissionFS theSC
G4ParticleHPTCFissionFS theTC
G4ParticleHPLCFissionFS theLC
G4ParticleHPFFFissionFS theFF
G4bool produceFissionFragments
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 46 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPFissionFS.hh
Constructor & Destructor Documentation
G4ParticleHPFissionFS::G4ParticleHPFissionFS () inline
Definition at line 50 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPFissionFS.hh
References G4ParticleHPFinalState::hasXsec, and produceFissionFragments.
Referenced by New().
G4ParticleHPFissionFS::~G4ParticleHPFissionFS () inline
Definition at line 51 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPFissionFS.hh
Member Function Documentation
G4HadFinalState * G4ParticleHPFissionFS::ApplyYourself (const G4HadProjectile & theTrack) virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 64 of file G4ParticleHPFissionFS.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPFissionFS.cc
References G4HadFinalState::AddSecondary(), G4ParticleHPFCFissionFS::ApplyYourself(), G4ParticleHPSCFissionFS::ApplyYourself(), G4ParticleHPTCFissionFS::ApplyYourself(), G4ParticleHPLCFissionFS::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4HadFinalState::Clear(), e, G4endl, G4Exception(), G4Log(), G4UniformRand, G4Cache< VALTYPE >::Get(), G4HadProjectile::Get4Momentum(), G4ParticleHPFFFissionFS::GetAFissionFragment(), G4Nucleus::GetBiasedThermalNucleus(), G4HadProjectile::GetDefinition(), G4ParticleHPFSFissionFS::GetEnergyRelease(), G4ParticleHPFissionERelease::GetFragmentKinetic(), G4HadProjectile::GetGlobalTime(), G4ParticleHPManager::GetInstance(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4ParticleHPFSFissionFS::GetMass(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4HadFinalState::GetNumberOfSecondaries(), G4ParticleDefinition::GetPDGMass(), G4ParticleHPFSFissionFS::GetPhotons(), G4ParticleHPManager::GetProduceFissionFragments(), G4HadFinalState::GetSecondary(), G4Material::GetTemperature(), G4ParticleHPFissionBaseFS::GetXsec(), it, JustWarning, G4ReactionProduct::Lorentz(), phi, produceFissionFragments, pt, G4Cache< VALTYPE >::Put(), G4ParticleHPFSFissionFS::SampleNeutronMult(), G4ReactionProduct::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4HadFinalState::SetLocalEnergyDeposit(), G4ReactionProduct::SetMomentum(), G4ParticleHPFissionBaseFS::SetNeutronRP(), G4ParticleHPFSFissionFS::SetNeutronRP(), G4HadFinalState::SetStatusChange(), G4ParticleHPFissionBaseFS::SetTarget(), G4ParticleHPFSFissionFS::SetTarget(), stopAndKill, G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theFC, theFF, theFS, theLC, G4ParticleHPFinalState::theResult, theSC, theta(), theTarget, theTC, Acts::VectorHelpers::time(), twopi, and CLHEP::HepLorentzVector::vect().
void G4ParticleHPFissionFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aFSType, G4ParticleDefinition * projectile) virtual
Implements G4ParticleHPFinalState.
Definition at line 43 of file G4ParticleHPFissionFS.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPFissionFS.cc
References G4cout, G4endl, G4ParticleHPManager::GetInstance(), G4ParticleHPFinalState::HasFSData(), G4ParticleHPTCFissionFS::Init(), G4ParticleHPLCFissionFS::Init(), G4ParticleHPSCFissionFS::Init(), G4ParticleHPFCFissionFS::Init(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPFSFissionFS::Init(), produceFissionFragments, theFC, theFF, theFS, theLC, theSC, and theTC.
G4ParticleHPFinalState* G4ParticleHPFissionFS::New () inline virtual
Implements G4ParticleHPFinalState.
Definition at line 54 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPFissionFS.hh
References G4ParticleHPFissionFS().
Member Data Documentation
G4bool G4ParticleHPFissionFS::produceFissionFragments private
Definition at line 69 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), G4ParticleHPFissionFS(), and Init().
G4ParticleHPFCFissionFS G4ParticleHPFissionFS::theFC private
Definition at line 63 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPFFFissionFS G4ParticleHPFissionFS::theFF private
Definition at line 68 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPFSFissionFS G4ParticleHPFissionFS::theFS private
Definition at line 62 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPLCFissionFS G4ParticleHPFissionFS::theLC private
Definition at line 66 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPSCFissionFS G4ParticleHPFissionFS::theSC private
Definition at line 64 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPTCFissionFS G4ParticleHPFissionFS::theTC private
Definition at line 65 of file G4ParticleHPFissionFS.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPFissionFS.hh
Referenced by ApplyYourself(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPFissionFS.cc