ECCE @ EIC Software: G4SynchrotronRadiation Class Reference
G4SynchrotronRadiation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4SynchrotronRadiation.hh>
Public Member Functions
G4SynchrotronRadiation (const G4String &pName="SynRad", G4ProcessType type=fElectromagnetic)
virtual ~G4SynchrotronRadiation ()
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &Step) override
G4double GetPhotonEnergy (const G4Track &trackData, const G4Step &stepData)
G4double GetRandomEnergySR (G4double, G4double, G4double)
G4double InvSynFracInt (G4double x)
G4double Chebyshev (G4double a, G4double b, const G4double c[], G4int n, G4double x)
virtual G4bool IsApplicable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual void PrintInfoDefinition ()
void SetAngularGenerator (G4VEmAngularDistribution *p)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4SynchrotronRadiation & operator= (const G4SynchrotronRadiation &right)
G4SynchrotronRadiation (const G4SynchrotronRadiation &)
Private Attributes
G4LossTableManager * theManager
G4VEmAngularDistribution * genAngle
G4ParticleDefinition * theGamma
G4PropagatorInField * fFieldPropagator
G4bool FirstTime
G4bool FirstTime1
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 64 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 64 of file G4SynchrotronRadiation.hh
Constructor & Destructor Documentation
G4SynchrotronRadiation::G4SynchrotronRadiation (const G4String & pName = "SynRad", G4ProcessType type = fElectromagnetic) explicit
Definition at line 57 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 57 of file G4SynchrotronRadiation.cc
References fFieldPropagator, FirstTime, FirstTime1, fSynchrotronRadiation, genAngle, G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetTransportationManager(), G4LossTableManager::Instance(), G4LossTableManager::Register(), SetAngularGenerator(), G4VProcess::SetProcessSubType(), theManager, and G4VProcess::verboseLevel.
G4SynchrotronRadiation::~G4SynchrotronRadiation () virtual
Definition at line 81 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 81 of file G4SynchrotronRadiation.cc
References G4LossTableManager::DeRegister(), genAngle, and theManager.
G4SynchrotronRadiation::G4SynchrotronRadiation (const G4SynchrotronRadiation &) private
Member Function Documentation
void G4SynchrotronRadiation::BuildPhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Definition at line 408 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 408 of file G4SynchrotronRadiation.cc
References G4Electron::Electron(), PrintInfoDefinition(), and G4VProcess::verboseLevel.
G4double G4SynchrotronRadiation::Chebyshev (G4double a, G4double b, const G4double c[], G4int n, G4double x) inline
Definition at line 114 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 114 of file G4SynchrotronRadiation.hh
References b, d, y, and y2.
Referenced by InvSynFracInt().
G4double G4SynchrotronRadiation::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Implements G4VDiscreteProcess.
Definition at line 112 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 112 of file G4SynchrotronRadiation.cc
References source.hepunit::c_light, CLHEP::Hep3Vector::cross(), DBL_MAX, e3, eplus, fFieldPropagator, G4PropagatorInField::FindAndSetFieldManager(), source.hepunit::fine_structure_const, FirstTime, G4BestUnit, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Field::GetFieldValue(), G4Track::GetGlobalTime(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Track::GetPosition(), CLHEP::Hep3Vector::getR(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetVolume(), CLHEP::Hep3Vector::mag(), MeV, NotForced, tesla, CLHEP::Hep3Vector::theta(), G4VProcess::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4SynchrotronRadiation::GetPhotonEnergy (const G4Track & trackData, const G4Step & stepData)
G4double G4SynchrotronRadiation::GetRandomEnergySR (G4double gamma, G4double perpB, G4double mass_c2)
Definition at line 377 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 377 of file G4SynchrotronRadiation.cc
References source.hepunit::c_light, eplus, FirstTime1, G4BestUnit, G4cout, G4endl, G4UniformRand, source.hepunit::hbar_Planck, InvSynFracInt(), CLHEP::prec, and G4VProcess::verboseLevel.
Referenced by PostStepDoIt().
G4double G4SynchrotronRadiation::InvSynFracInt (G4double x)
Definition at line 318 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 318 of file G4SynchrotronRadiation.cc
References Chebyshev(), G4Log(), and y.
Referenced by GetRandomEnergySR().
G4bool G4SynchrotronRadiation::IsApplicable (const G4ParticleDefinition & particle) override virtual
Reimplemented from G4VProcess.
Definition at line 100 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 100 of file G4SynchrotronRadiation.cc
References G4ParticleDefinition::GetPDGCharge(), and G4ParticleDefinition::IsShortLived().
G4SynchrotronRadiation& G4SynchrotronRadiation::operator= (const G4SynchrotronRadiation & right) private
G4VParticleChange * G4SynchrotronRadiation::PostStepDoIt (const G4Track & track, const G4Step & Step) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 215 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 215 of file G4SynchrotronRadiation.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, CLHEP::Hep3Vector::cross(), e3, fFieldPropagator, G4PropagatorInField::FindAndSetFieldManager(), genAngle, G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Field::GetFieldValue(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Track::GetPosition(), GetRandomEnergySR(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetVolume(), G4ParticleChange::Initialize(), CLHEP::Hep3Vector::mag(), G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VEmAngularDistribution::SampleDirection(), G4VParticleChange::SetNumberOfSecondaries(), G4DynamicParticle::SetPolarization(), theGamma, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4SynchrotronRadiation::PrintInfoDefinition () virtual
Definition at line 418 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 418 of file G4SynchrotronRadiation.cc
References G4cout, G4endl, and G4VProcess::GetProcessName().
Referenced by BuildPhysicsTable().
void G4SynchrotronRadiation::SetAngularGenerator (G4VEmAngularDistribution * p)
Definition at line 91 of file G4SynchrotronRadiation.cc.
View newest version in sPHENIX GitHub at line 91 of file G4SynchrotronRadiation.cc
References genAngle.
Referenced by G4SynchrotronRadiation().
Member Data Documentation
G4PropagatorInField* G4SynchrotronRadiation::fFieldPropagator private
Definition at line 106 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 106 of file G4SynchrotronRadiation.hh
Referenced by G4SynchrotronRadiation(), GetMeanFreePath(), and PostStepDoIt().
G4bool G4SynchrotronRadiation::FirstTime private
Definition at line 107 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 107 of file G4SynchrotronRadiation.hh
Referenced by G4SynchrotronRadiation(), and GetMeanFreePath().
G4bool G4SynchrotronRadiation::FirstTime1 private
Definition at line 108 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4SynchrotronRadiation.hh
Referenced by G4SynchrotronRadiation(), and GetRandomEnergySR().
G4VEmAngularDistribution* G4SynchrotronRadiation::genAngle private
Definition at line 102 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 102 of file G4SynchrotronRadiation.hh
Referenced by G4SynchrotronRadiation(), PostStepDoIt(), SetAngularGenerator(), and ~G4SynchrotronRadiation().
G4ParticleDefinition* G4SynchrotronRadiation::theGamma private
Definition at line 104 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 104 of file G4SynchrotronRadiation.hh
Referenced by PostStepDoIt().
G4LossTableManager* G4SynchrotronRadiation::theManager private
Definition at line 101 of file G4SynchrotronRadiation.hh.
View newest version in sPHENIX GitHub at line 101 of file G4SynchrotronRadiation.hh
Referenced by G4SynchrotronRadiation(), and ~G4SynchrotronRadiation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4SynchrotronRadiation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/src/G4SynchrotronRadiation.cc