ECCE @ EIC Software: G4GDMLWriteSetup Class Reference
G4GDMLWriteSetup Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteSetup.hh>
Public Member Functions
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)
Public Member Functions inherited from G4GDMLWriteSolids
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
G4GDMLWriteSetup ()
virtual ~G4GDMLWriteSetup ()
Protected Member Functions inherited from G4GDMLWriteSolids
G4GDMLWriteSolids ()
virtual ~G4GDMLWriteSolids ()
void MultiUnionWrite (xercesc::DOMElement *solElement, const G4MultiUnion *const)
void BooleanWrite (xercesc::DOMElement *, const G4BooleanSolid *const)
void ScaledWrite (xercesc::DOMElement *, const G4ScaledSolid *const)
void BoxWrite (xercesc::DOMElement *, const G4Box *const)
void ConeWrite (xercesc::DOMElement *, const G4Cons *const)
void ElconeWrite (xercesc::DOMElement *, const G4EllipticalCone *const)
void EllipsoidWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void EltubeWrite (xercesc::DOMElement *, const G4EllipticalTube *const)
void XtruWrite (xercesc::DOMElement *, const G4ExtrudedSolid *const)
void HypeWrite (xercesc::DOMElement *, const G4Hype *const)
void OrbWrite (xercesc::DOMElement *, const G4Orb *const)
void ParaWrite (xercesc::DOMElement *, const G4Para *const)
void ParaboloidWrite (xercesc::DOMElement *, const G4Paraboloid *const)
void PolyconeWrite (xercesc::DOMElement *, const G4Polycone *const)
void GenericPolyconeWrite (xercesc::DOMElement *, const G4GenericPolycone *const)
void PolyhedraWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void SphereWrite (xercesc::DOMElement *, const G4Sphere *const)
void TessellatedWrite (xercesc::DOMElement *, const G4TessellatedSolid *const)
void TetWrite (xercesc::DOMElement *, const G4Tet *const)
void TorusWrite (xercesc::DOMElement *, const G4Torus *const)
void GenTrapWrite (xercesc::DOMElement *, const G4GenericTrap *const)
void TrapWrite (xercesc::DOMElement *, const G4Trap *const)
void TrdWrite (xercesc::DOMElement *, const G4Trd *const)
void TubeWrite (xercesc::DOMElement *, const G4Tubs *const)
void CutTubeWrite (xercesc::DOMElement *, const G4CutTubs *const)
void TwistedboxWrite (xercesc::DOMElement *, const G4TwistedBox *const)
void TwistedtrapWrite (xercesc::DOMElement *, const G4TwistedTrap *const)
void TwistedtrdWrite (xercesc::DOMElement *, const G4TwistedTrd *const)
void TwistedtubsWrite (xercesc::DOMElement *, const G4TwistedTubs *const)
void ZplaneWrite (xercesc::DOMElement *, const G4double &, const G4double &, const G4double &)
void RZPointWrite (xercesc::DOMElement *, const G4double &, const G4double &)
void OpticalSurfaceWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
void PropertyWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
Protected Member Functions inherited from G4GDMLWriteMaterials
G4GDMLWriteMaterials ()
virtual ~G4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from G4GDMLWriteDefine
G4GDMLWriteDefine ()
virtual ~G4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from G4GDMLWrite
G4GDMLWrite ()
virtual ~G4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (G4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Protected Attributes inherited from G4GDMLWriteSolids
std::vector< const G4VSolid * > solidList
xercesc::DOMElement * solidsElement
Static Protected Attributes inherited from G4GDMLWriteSolids
static const G4int maxTransforms = 8
Detailed Description
Definition at line 44 of file G4GDMLWriteSetup.hh.
View newest version in sPHENIX GitHub at line 44 of file G4GDMLWriteSetup.hh
Constructor & Destructor Documentation
G4GDMLWriteSetup::G4GDMLWriteSetup () protected
Definition at line 38 of file G4GDMLWriteSetup.cc.
View newest version in sPHENIX GitHub at line 38 of file G4GDMLWriteSetup.cc
G4GDMLWriteSetup::~G4GDMLWriteSetup () protected virtual
Definition at line 42 of file G4GDMLWriteSetup.cc.
View newest version in sPHENIX GitHub at line 42 of file G4GDMLWriteSetup.cc
Member Function Documentation
void G4GDMLWriteSetup::SetupWrite (xercesc::DOMElement * gdmlElement, const G4LogicalVolume * const logvol) virtual
Implements G4GDMLWrite.
Definition at line 46 of file G4GDMLWriteSetup.cc.
View newest version in sPHENIX GitHub at line 46 of file G4GDMLWriteSetup.cc
References G4cout, G4endl, G4GDMLWrite::GenerateName(), G4LogicalVolume::GetName(), G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteSetup.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLWriteSetup.cc