ECCE @ EIC Software: G4INCL::PionResonanceDecayChannel Class Reference
G4INCL::PionResonanceDecayChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLPionResonanceDecayChannel.hh>
Public Member Functions
PionResonanceDecayChannel (Particle *, ThreeVector const &)
virtual ~PionResonanceDecayChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Static Public Member Functions
static G4double computeDecayTime (Particle *p)
Private Member Functions
void sampleAngles (G4double *, G4double *, G4double *)
INCL_DECLARE_ALLOCATION_POOL (PionResonanceDecayChannel)
Private Attributes
Particle * theParticle
ThreeVector const incidentDirection
Static Private Attributes
static const G4double angularSlope = 0.
Detailed Description
Definition at line 49 of file G4INCLPionResonanceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4INCLPionResonanceDecayChannel.hh
Constructor & Destructor Documentation
G4INCL::PionResonanceDecayChannel::PionResonanceDecayChannel (Particle * p, ThreeVector const & dir)
Definition at line 51 of file G4INCLPionResonanceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLPionResonanceDecayChannel.cc
G4INCL::PionResonanceDecayChannel::~PionResonanceDecayChannel () virtual
Definition at line 55 of file G4INCLPionResonanceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLPionResonanceDecayChannel.cc
Member Function Documentation
G4double G4INCL::PionResonanceDecayChannel::computeDecayTime (Particle * p) static
Definition at line 58 of file G4INCLPionResonanceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLPionResonanceDecayChannel.cc
References G4INCL::Particle::getEnergy(), G4INCL::Particle::getMass(), G4INCL::Particle::getType(), G4INCL::PhysicalConstants::hc, INCL_FATAL, m, G4INCL::Omega, and G4INCL::Random::shoot().
Referenced by G4INCL::StandardPropagationModel::generateDecays().
void G4INCL::PionResonanceDecayChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 87 of file G4INCLPionResonanceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 87 of file G4INCLPionResonanceDecayChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), G4INCL::Particle::adjustEnergyFromMomentum(), e, G4INCL::Eta, G4INCL::PhaseSpaceGenerator::generate(), G4INCL::ParticleTable::getINCLMass(), G4INCL::Particle::getMass(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), incidentDirection, INCL_FATAL, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Neutron, G4INCL::Omega, G4INCL::ThreeVector::perp(), G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, sampleAngles(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), G4INCL::Random::shoot(), t1, t2, theParticle, and zero.
G4INCL::PionResonanceDecayChannel::INCL_DECLARE_ALLOCATION_POOL (PionResonanceDecayChannel) private
void G4INCL::PionResonanceDecayChannel::sampleAngles (G4double * ctet_par, G4double * stet_par, G4double * phi_par) private
Definition at line 79 of file G4INCLPionResonanceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 79 of file G4INCLPionResonanceDecayChannel.cc
References kdfinder::abs(), G4INCL::Random::shoot(), G4INCL::Math::sign(), and G4INCL::Math::twoPi.
Referenced by fillFinalState().
Member Data Documentation
const G4double G4INCL::PionResonanceDecayChannel::angularSlope = 0. static private
Definition at line 60 of file G4INCLPionResonanceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLPionResonanceDecayChannel.hh
ThreeVector const G4INCL::PionResonanceDecayChannel::incidentDirection private
Definition at line 63 of file G4INCLPionResonanceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4INCLPionResonanceDecayChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::PionResonanceDecayChannel::theParticle private
Definition at line 62 of file G4INCLPionResonanceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4INCLPionResonanceDecayChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLPionResonanceDecayChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLPionResonanceDecayChannel.cc