ECCE @ EIC Software: G4HnManager Class Reference
G4HnManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4HnManager.hh>
Public Member Functions
G4HnManager (const G4String &hnType, const G4AnalysisManagerState &state)
virtual ~G4HnManager ()
G4HnInformation * AddHnInformation (const G4String &name, G4int nofDimensions)
G4HnInformation * GetHnInformation (G4int id, G4String functionName="", G4bool warn=true) const
G4HnDimensionInformation * GetHnDimensionInformation (G4int id, G4int dimension, G4String functionName="", G4bool warn=true) const
const std::vector
< G4HnInformation * > & GetHnVector () const
G4int GetNofHns () const
G4String GetHnType () const
G4bool IsActive () const
G4bool IsAscii () const
G4bool IsPlotting () const
void SetActivation (G4bool activation)
void SetActivation (G4int id, G4bool activation)
void SetAscii (G4int id, G4bool ascii)
void SetPlotting (G4bool plotting)
void SetPlotting (G4int id, G4bool plotting)
G4bool SetXAxisIsLog (G4int id, G4bool isLogAxis)
G4bool SetYAxisIsLog (G4int id, G4bool isLogAxis)
G4bool SetZAxisIsLog (G4int id, G4bool isLogAxis)
G4String GetName (G4int id) const
G4double GetXUnit (G4int id) const
G4double GetYUnit (G4int id) const
G4double GetZUnit (G4int id) const
G4bool GetXAxisIsLog (G4int id) const
G4bool GetYAxisIsLog (G4int id) const
G4bool GetZAxisIsLog (G4int id) const
G4bool GetActivation (G4int id) const
G4bool GetAscii (G4int id) const
G4bool GetPlotting (G4int id) const
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Attributes
G4String fHnType
G4int fNofActiveObjects
G4int fNofAsciiObjects
G4int fNofPlottingObjects
std::vector< G4HnInformation * > fHnVector
Additional Inherited Members
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 42 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 42 of file G4HnManager.hh
Constructor & Destructor Documentation
G4HnManager::G4HnManager (const G4String & hnType, const G4AnalysisManagerState & state)
Definition at line 35 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 35 of file G4HnManager.cc
G4HnManager::~G4HnManager () virtual
Definition at line 47 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 47 of file G4HnManager.cc
References fHnVector.
Member Function Documentation
G4HnInformation * G4HnManager::AddHnInformation (const G4String & name, G4int nofDimensions)
Definition at line 59 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 59 of file G4HnManager.cc
References fHnVector, and fNofActiveObjects.
G4bool G4HnManager::GetActivation (G4int id) const
Definition at line 321 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 321 of file G4HnManager.cc
References GetHnInformation().
G4bool G4HnManager::GetAscii (G4int id) const
Definition at line 331 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 331 of file G4HnManager.cc
References GetHnInformation().
G4HnDimensionInformation * G4HnManager::GetHnDimensionInformation (G4int id, G4int dimension, G4String functionName = "", G4bool warn = true) const
Definition at line 91 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 91 of file G4HnManager.cc
References GetHnInformation().
Referenced by GetXUnit(), GetYUnit(), and GetZUnit().
G4HnInformation * G4HnManager::GetHnInformation (G4int id, G4String functionName = "", G4bool warn = true) const
Definition at line 69 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 69 of file G4HnManager.cc
References G4BaseAnalysisManager::fFirstId, fHnType, fHnVector, G4Exception(), and JustWarning.
Referenced by GetActivation(), GetAscii(), GetHnDimensionInformation(), GetName(), GetPlotting(), GetXAxisIsLog(), GetYAxisIsLog(), GetZAxisIsLog(), SetActivation(), SetAscii(), SetPlotting(), SetXAxisIsLog(), SetYAxisIsLog(), and SetZAxisIsLog().
G4String G4HnManager::GetHnType () const inline
Definition at line 123 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4HnManager.hh
References fHnType.
Referenced by G4HnMessenger::G4HnMessenger().
const std::vector< G4HnInformation * > & G4HnManager::GetHnVector () const inline
Definition at line 126 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4HnManager.hh
References fHnVector.
G4String G4HnManager::GetName (G4int id) const
Definition at line 251 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 251 of file G4HnManager.cc
References GetHnInformation().
G4int G4HnManager::GetNofHns () const inline
Definition at line 120 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4HnManager.hh
References fHnVector.
G4bool G4HnManager::GetPlotting (G4int id) const
Definition at line 341 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 341 of file G4HnManager.cc
References GetHnInformation().
G4bool G4HnManager::GetXAxisIsLog (G4int id) const
Definition at line 291 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 291 of file G4HnManager.cc
References GetHnInformation(), and G4Analysis::kX.
G4double G4HnManager::GetXUnit (G4int id) const
Definition at line 261 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 261 of file G4HnManager.cc
References GetHnDimensionInformation(), and G4Analysis::kX.
G4bool G4HnManager::GetYAxisIsLog (G4int id) const
Definition at line 301 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 301 of file G4HnManager.cc
References GetHnInformation(), and G4Analysis::kY.
G4double G4HnManager::GetYUnit (G4int id) const
Definition at line 271 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 271 of file G4HnManager.cc
References GetHnDimensionInformation(), and G4Analysis::kY.
G4bool G4HnManager::GetZAxisIsLog (G4int id) const
Definition at line 311 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 311 of file G4HnManager.cc
References GetHnInformation(), and G4Analysis::kZ.
G4double G4HnManager::GetZUnit (G4int id) const
Definition at line 281 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 281 of file G4HnManager.cc
References GetHnDimensionInformation(), and G4Analysis::kZ.
G4bool G4HnManager::IsActive () const
Definition at line 102 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 102 of file G4HnManager.cc
References fNofActiveObjects.
G4bool G4HnManager::IsAscii () const
Definition at line 108 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 108 of file G4HnManager.cc
References fNofAsciiObjects.
G4bool G4HnManager::IsPlotting () const
Definition at line 114 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 114 of file G4HnManager.cc
References fNofPlottingObjects.
void G4HnManager::SetActivation (G4bool activation)
Definition at line 140 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 140 of file G4HnManager.cc
References fHnVector, and fNofActiveObjects.
Referenced by G4HnMessenger::SetNewValue().
void G4HnManager::SetActivation (G4int id, G4bool activation)
Definition at line 120 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 120 of file G4HnManager.cc
References fNofActiveObjects, and GetHnInformation().
void G4HnManager::SetAscii (G4int id, G4bool ascii)
Definition at line 163 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 163 of file G4HnManager.cc
References fNofAsciiObjects, and GetHnInformation().
Referenced by G4HnMessenger::SetNewValue().
void G4HnManager::SetPlotting (G4bool plotting)
Definition at line 199 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 199 of file G4HnManager.cc
References fHnVector, and fNofPlottingObjects.
Referenced by G4HnMessenger::SetNewValue().
void G4HnManager::SetPlotting (G4int id, G4bool plotting)
Definition at line 181 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 181 of file G4HnManager.cc
References fNofPlottingObjects, and GetHnInformation().
G4bool G4HnManager::SetXAxisIsLog (G4int id, G4bool isLogAxis)
Definition at line 218 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 218 of file G4HnManager.cc
References GetHnInformation(), and G4Analysis::kX.
G4bool G4HnManager::SetYAxisIsLog (G4int id, G4bool isLogAxis)
Definition at line 229 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 229 of file G4HnManager.cc
References GetHnInformation(), and G4Analysis::kY.
G4bool G4HnManager::SetZAxisIsLog (G4int id, G4bool isLogAxis)
Definition at line 240 of file G4HnManager.cc.
View newest version in sPHENIX GitHub at line 240 of file G4HnManager.cc
References GetHnInformation(), and G4Analysis::kZ.
Member Data Documentation
G4String G4HnManager::fHnType private
Definition at line 111 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 111 of file G4HnManager.hh
Referenced by GetHnInformation(), and GetHnType().
std::vector<G4HnInformation*> G4HnManager::fHnVector private
Definition at line 117 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4HnManager.hh
Referenced by AddHnInformation(), GetHnInformation(), GetHnVector(), GetNofHns(), SetActivation(), SetPlotting(), and ~G4HnManager().
G4int G4HnManager::fNofActiveObjects private
Definition at line 112 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 112 of file G4HnManager.hh
Referenced by AddHnInformation(), IsActive(), and SetActivation().
G4int G4HnManager::fNofAsciiObjects private
Definition at line 113 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4HnManager.hh
Referenced by IsAscii(), and SetAscii().
G4int G4HnManager::fNofPlottingObjects private
Definition at line 114 of file G4HnManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4HnManager.hh
Referenced by IsPlotting(), and SetPlotting().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4HnManager.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4HnManager.cc