ECCE @ EIC Software: G4LindhardRobinsonPartition Class Reference
G4LindhardRobinsonPartition Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4LindhardPartition.hh>
Public Member Functions
G4LindhardRobinsonPartition ()
virtual ~G4LindhardRobinsonPartition ()
virtual G4double PartitionNIEL (G4int z1, G4double a1, const G4Material *material, G4double energy) const
Public Member Functions inherited from G4VNIELPartition
G4VNIELPartition ()
virtual ~G4VNIELPartition ()
Public Attributes
G4double z23 [120]
size_t max_z
Detailed Description
Definition at line 55 of file G4LindhardPartition.hh.
View newest version in sPHENIX GitHub at line 55 of file G4LindhardPartition.hh
Constructor & Destructor Documentation
G4LindhardRobinsonPartition::G4LindhardRobinsonPartition ()
Definition at line 65 of file G4LindhardPartition.cc.
View newest version in sPHENIX GitHub at line 65 of file G4LindhardPartition.cc
References max_z, and z23.
virtual G4LindhardRobinsonPartition::~G4LindhardRobinsonPartition () inline virtual
Definition at line 59 of file G4LindhardPartition.hh.
View newest version in sPHENIX GitHub at line 59 of file G4LindhardPartition.hh
Member Function Documentation
G4double G4LindhardRobinsonPartition::PartitionNIEL (G4int z1, G4double a1, const G4Material * material, G4double energy) const virtual
Implements G4VNIELPartition.
Definition at line 71 of file G4LindhardPartition.cc.
View newest version in sPHENIX GitHub at line 71 of file G4LindhardPartition.cc
References source.hepunit::amu, source.hepunit::Avogadro, eps, eV, G4Element::GetA(), G4Material::GetElement(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZ(), k, z1, z2, and z23.
Member Data Documentation
size_t G4LindhardRobinsonPartition::max_z
Definition at line 66 of file G4LindhardPartition.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LindhardPartition.hh
Referenced by G4LindhardRobinsonPartition().
G4double G4LindhardRobinsonPartition::z23[120]
Definition at line 65 of file G4LindhardPartition.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LindhardPartition.hh
Referenced by G4LindhardRobinsonPartition(), and PartitionNIEL().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4LindhardPartition.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/G4LindhardPartition.cc