ECCE @ EIC Software: G4HadronPhysicsShielding Class Reference
G4HadronPhysicsShielding Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsShielding.hh>
Public Member Functions
G4HadronPhysicsShielding (G4int verbose=1)
G4HadronPhysicsShielding (const G4String &name, G4bool)
G4HadronPhysicsShielding (const G4String &name, G4int verbose=1, G4double minFTFPEnergy=G4HadronicParameters::Instance() ->GetMinEnergyTransitionFTF_Cascade(), G4double maxBertiniEnergy=G4HadronicParameters::Instance() ->GetMaxEnergyTransitionFTF_Cascade())
virtual ~G4HadronPhysicsShielding ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
void UseLEND (G4String ss="")
void UnuseLEND ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
virtual void CreateModels ()
virtual void Neutron ()
virtual void Proton ()
virtual void Pion ()
virtual void Kaon ()
virtual void Others ()
virtual void DumpBanner ()
virtual void ExtraConfiguration ()
Private Attributes
G4bool useLEND_
G4String evaluation_
const G4double minFTFPEnergy_
const G4double maxBertiniEnergy_
const G4double minNonHPNeutronEnergy_
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 52 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 52 of file G4HadronPhysicsShielding.hh
Constructor & Destructor Documentation
G4HadronPhysicsShielding::G4HadronPhysicsShielding (G4int verbose = 1) explicit
Definition at line 108 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 108 of file G4HadronPhysicsShielding.cc
G4HadronPhysicsShielding::G4HadronPhysicsShielding (const G4String & name, G4bool) explicit
Definition at line 117 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 117 of file G4HadronPhysicsShielding.cc
G4HadronPhysicsShielding::G4HadronPhysicsShielding (const G4String & name, G4int verbose = 1, G4double minFTFPEnergy = G4HadronicParameters::Instance()->GetMinEnergyTransitionFTF_Cascade(), G4double maxBertiniEnergy = G4HadronicParameters::Instance()->GetMaxEnergyTransitionFTF_Cascade()) explicit
Definition at line 126 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 126 of file G4HadronPhysicsShielding.cc
G4HadronPhysicsShielding::~G4HadronPhysicsShielding () virtual
Definition at line 137 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 137 of file G4HadronPhysicsShielding.cc
Member Function Documentation
void G4HadronPhysicsShielding::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 150 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 150 of file G4HadronPhysicsShielding.cc
References G4MesonConstructor::ConstructParticle(), G4IonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsShielding::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 267 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 267 of file G4HadronPhysicsShielding.cc
References CreateModels(), DumpBanner(), ExtraConfiguration(), and G4Threading::IsMasterThread().
void G4HadronPhysicsShielding::CreateModels () private virtual
Definition at line 166 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 166 of file G4HadronPhysicsShielding.cc
References Kaon(), Neutron(), Others(), Pion(), and Proton().
Referenced by ConstructProcess().
void G4HadronPhysicsShielding::DumpBanner () private virtual
Definition at line 141 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 141 of file G4HadronPhysicsShielding.cc
References G4cout, G4endl, GeV, maxBertiniEnergy_, and minFTFPEnergy_.
Referenced by ConstructProcess().
void G4HadronPhysicsShielding::ExtraConfiguration () private virtual
Definition at line 277 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 277 of file G4HadronPhysicsShielding.cc
References G4CrossSectionDataStore::AddDataSet(), G4HadronicProcess::AddDataSet(), G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4HadronicProcess::GetCrossSectionDataStore(), G4HadronicParameters::Instance(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), minNonHPNeutronEnergy_, G4InuclParticleNames::neutron, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
Referenced by ConstructProcess().
void G4HadronPhysicsShielding::Kaon () private virtual
Definition at line 234 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 234 of file G4HadronPhysicsShielding.cc
References G4VPhysicsConstructor::AddBuilder(), k, maxBertiniEnergy_, and minFTFPEnergy_.
Referenced by CreateModels().
void G4HadronPhysicsShielding::Neutron () private virtual
Definition at line 176 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 176 of file G4HadronPhysicsShielding.cc
References G4VPhysicsConstructor::AddBuilder(), evaluation_, maxBertiniEnergy_, minFTFPEnergy_, minNonHPNeutronEnergy_, G4InuclParticleNames::neu, and useLEND_.
Referenced by CreateModels().
void G4HadronPhysicsShielding::Others () private virtual
Definition at line 250 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 250 of file G4HadronPhysicsShielding.cc
References G4VPhysicsConstructor::AddBuilder().
Referenced by CreateModels().
void G4HadronPhysicsShielding::Pion () private virtual
Definition at line 218 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 218 of file G4HadronPhysicsShielding.cc
References G4VPhysicsConstructor::AddBuilder(), maxBertiniEnergy_, minFTFPEnergy_, and pi.
Referenced by CreateModels().
void G4HadronPhysicsShielding::Proton () private virtual
Definition at line 202 of file G4HadronPhysicsShielding.cc.
View newest version in sPHENIX GitHub at line 202 of file G4HadronPhysicsShielding.cc
References G4VPhysicsConstructor::AddBuilder(), maxBertiniEnergy_, minFTFPEnergy_, and G4InuclParticleNames::pro.
Referenced by CreateModels().
void G4HadronPhysicsShielding::UnuseLEND () inline
Definition at line 67 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HadronPhysicsShielding.hh
References useLEND_.
void G4HadronPhysicsShielding::UseLEND (G4String ss = "") inline
Definition at line 66 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 66 of file G4HadronPhysicsShielding.hh
References evaluation_, and useLEND_.
Member Data Documentation
G4String G4HadronPhysicsShielding::evaluation_ private
Definition at line 81 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadronPhysicsShielding.hh
Referenced by Neutron(), and UseLEND().
const G4double G4HadronPhysicsShielding::maxBertiniEnergy_ private
Definition at line 84 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HadronPhysicsShielding.hh
Referenced by DumpBanner(), Kaon(), Neutron(), Pion(), and Proton().
const G4double G4HadronPhysicsShielding::minFTFPEnergy_ private
Definition at line 83 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HadronPhysicsShielding.hh
Referenced by DumpBanner(), Kaon(), Neutron(), Pion(), and Proton().
const G4double G4HadronPhysicsShielding::minNonHPNeutronEnergy_ private
Definition at line 85 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 85 of file G4HadronPhysicsShielding.hh
Referenced by ExtraConfiguration(), and Neutron().
G4bool G4HadronPhysicsShielding::useLEND_ private
Definition at line 80 of file G4HadronPhysicsShielding.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HadronPhysicsShielding.hh
Referenced by Neutron(), UnuseLEND(), and UseLEND().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsShielding.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsShielding.cc