ECCE @ EIC Software: G4ForwardXrayTR Class Reference
G4ForwardXrayTR Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4ForwardXrayTR.hh>
Public Member Functions
G4ForwardXrayTR (const G4String &matName1, const G4String &matName2, const G4String &processName="XrayTR")
G4ForwardXrayTR (const G4String &processName="XrayTR")
virtual ~G4ForwardXrayTR ()
void BuildXrayTRtables ()
G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *condition) override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
G4double GetEnergyTR (G4int iMat, G4int jMat, G4int iTkin) const
G4double GetThetaTR (G4int iMat, G4int jMat, G4int iTkin) const
G4double SpectralAngleTRdensity (G4double energy, G4double varAngle) const override
G4double AngleDensity (G4double energy, G4double varAngle) const
G4double EnergyInterval (G4double energy1, G4double energy2, G4double varAngle) const
G4double AngleSum (G4double varAngle1, G4double varAngle2) const
G4double SpectralDensity (G4double energy, G4double x) const
G4double AngleInterval (G4double energy, G4double varAngle1, G4double varAngle2) const
G4double EnergySum (G4double energy1, G4double energy2) const
G4PhysicsTable * GetAngleDistrTable ()
G4PhysicsTable * GetEnergyDistrTable ()
Public Member Functions inherited from G4TransitionRadiation
G4TransitionRadiation (const G4String &processName="TR", G4ProcessType type=fElectromagnetic)
virtual ~G4TransitionRadiation ()
G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
G4double IntegralOverEnergy (G4double energy1, G4double energy2, G4double varAngle) const
G4double IntegralOverAngle (G4double energy, G4double varAngle1, G4double varAngle2) const
G4double AngleIntegralDistribution (G4double varAngle1, G4double varAngle2) const
G4double EnergyIntegralDistribution (G4double energy1, G4double energy2) const
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static G4int GetSympsonNumber ()
static G4int GetBinTR ()
static G4double GetMinProtonTkin ()
static G4double GetMaxProtonTkin ()
static G4int GetTotBin ()
Protected Attributes
G4ParticleDefinition * fPtrGamma
const std::vector< G4double > * fGammaCutInKineticEnergy
G4double fGammaTkinCut
G4PhysicsTable * fAngleDistrTable
G4PhysicsTable * fEnergyDistrTable
G4PhysicsLogVector * fProtonEnergyVector
G4double fMinEnergyTR
G4double fMaxEnergyTR
G4double fMaxThetaTR
G4double fGamma
G4double fSigma1
G4double fSigma2
Protected Attributes inherited from G4TransitionRadiation
G4int fMatIndex1
G4int fMatIndex2
G4double fGamma
G4double fEnergy
G4double fVarAngle
G4double fMinEnergy
G4double fMaxEnergy
G4double fMaxTheta
G4double fSigma1
G4double fSigma2
Static Protected Attributes
static G4int fSympsonNumber = 100
static G4double fTheMinEnergyTR = 1.0*keV
static G4double fTheMaxEnergyTR = 100.0*keV
static G4double fTheMaxAngle = 1.0e-3
static G4double fTheMinAngle = 5.0e-6
static G4int fBinTR = 50
static G4double fMinProtonTkin = 100.0*GeV
static G4double fMaxProtonTkin = 100.0*TeV
static G4int fTotBin = 50
static G4double fPlasmaCof
static G4double fCofTR = fine_structure_const/pi
Static Protected Attributes inherited from G4TransitionRadiation
static const G4int fSympsonNumber = 100
static const G4int fGammaNumber = 15
static const G4int fPointNumber = 100
Private Member Functions
G4ForwardXrayTR (const G4ForwardXrayTR &right)=delete
G4ForwardXrayTR & operator= (const G4ForwardXrayTR &right)=delete
Additional Inherited Members
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Detailed Description
Definition at line 65 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ForwardXrayTR.hh
Constructor & Destructor Documentation
G4ForwardXrayTR::G4ForwardXrayTR (const G4String & matName1, const G4String & matName2, const G4String & processName = "XrayTR") explicit
Definition at line 82 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ForwardXrayTR.cc
References FW::Geometry::build(), BuildXrayTRtables(), fAngleDistrTable, fEnergyDistrTable, fGamma, fGammaCutInKineticEnergy, fGammaTkinCut, G4TransitionRadiation::fMatIndex1, G4TransitionRadiation::fMatIndex2, fMaxEnergyTR, fMaxProtonTkin, fMaxThetaTR, fMinEnergyTR, fMinProtonTkin, fProtonEnergyVector, fPtrGamma, fSigma1, fSigma2, fTotBin, G4Exception(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetName(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), and JustWarning.
G4ForwardXrayTR::G4ForwardXrayTR (const G4String & processName = "XrayTR") explicit
Definition at line 146 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 146 of file G4ForwardXrayTR.cc
References fAngleDistrTable, fEnergyDistrTable, fGamma, fGammaCutInKineticEnergy, fGammaTkinCut, G4TransitionRadiation::fMatIndex1, G4TransitionRadiation::fMatIndex2, fMaxEnergyTR, fMaxProtonTkin, fMaxThetaTR, fMinEnergyTR, fMinProtonTkin, fProtonEnergyVector, fPtrGamma, fSigma1, fSigma2, and fTotBin.
G4ForwardXrayTR::~G4ForwardXrayTR () virtual
Definition at line 169 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 169 of file G4ForwardXrayTR.cc
References fAngleDistrTable, fEnergyDistrTable, and fProtonEnergyVector.
G4ForwardXrayTR::G4ForwardXrayTR (const G4ForwardXrayTR & right) private delete
Member Function Documentation
G4double G4ForwardXrayTR::AngleDensity (G4double energy, G4double varAngle) const
Definition at line 339 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 339 of file G4ForwardXrayTR.cc
References c, d, energy, f, fGamma, fSigma1, fSigma2, x, and x2.
Referenced by EnergyInterval().
G4double G4ForwardXrayTR::AngleInterval (G4double energy, G4double varAngle1, G4double varAngle2) const
Definition at line 426 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 426 of file G4ForwardXrayTR.cc
References SpectralDensity().
Referenced by EnergySum().
G4double G4ForwardXrayTR::AngleSum (G4double varAngle1, G4double varAngle2) const
Definition at line 381 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 381 of file G4ForwardXrayTR.cc
References EnergyInterval(), fMaxEnergyTR, fMinEnergyTR, fSympsonNumber, and Acts::UnitConstants::h.
Referenced by BuildXrayTRtables().
void G4ForwardXrayTR::BuildXrayTRtables ()
Definition at line 188 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 188 of file G4ForwardXrayTR.cc
References AngleSum(), EnergySum(), fAngleDistrTable, fBinTR, fCofTR, fEnergyDistrTable, fGamma, fGammaCutInKineticEnergy, fGammaTkinCut, G4TransitionRadiation::fMatIndex1, G4TransitionRadiation::fMatIndex2, fMaxEnergyTR, fMaxThetaTR, fMinEnergyTR, fPlasmaCof, fProtonEnergyVector, fSigma1, fSigma2, fTheMaxAngle, fTheMaxEnergyTR, fTheMinAngle, fTheMinEnergyTR, fTotBin, G4Material::GetElectronDensity(), G4ProductionCutsTable::GetEnergyCutsVector(), G4PhysicsVector::GetLowEdgeEnergy(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), idxG4GammaCut, G4PhysicsTable::insertAt(), source.hepunit::proton_mass_c2, and G4PhysicsVector::PutValue().
Referenced by G4ForwardXrayTR().
G4double G4ForwardXrayTR::EnergyInterval (G4double energy1, G4double energy2, G4double varAngle) const
Definition at line 367 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 367 of file G4ForwardXrayTR.cc
References AngleDensity().
Referenced by AngleSum().
G4double G4ForwardXrayTR::EnergySum (G4double energy1, G4double energy2) const
Definition at line 440 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 440 of file G4ForwardXrayTR.cc
References AngleInterval(), fMaxThetaTR, fSympsonNumber, and Acts::UnitConstants::h.
Referenced by BuildXrayTRtables().
G4PhysicsTable* G4ForwardXrayTR::GetAngleDistrTable ()
G4int G4ForwardXrayTR::GetBinTR () static
Definition at line 813 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 813 of file G4ForwardXrayTR.cc
References fBinTR.
G4PhysicsTable* G4ForwardXrayTR::GetEnergyDistrTable ()
G4double G4ForwardXrayTR::GetEnergyTR (G4int iMat, G4int jMat, G4int iTkin) const
Definition at line 695 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 695 of file G4ForwardXrayTR.cc
References fBinTR, fTotBin, G4cout, G4endl, G4Poisson(), G4UniformRand, G4PhysicsVector::GetLowEdgeEnergy(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4Material::GetState(), G4ProductionCutsTable::GetTableSize(), kStateLiquid, and kStateSolid.
G4double G4ForwardXrayTR::GetMaxProtonTkin () static
Definition at line 823 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 823 of file G4ForwardXrayTR.cc
References fMaxProtonTkin.
G4double G4ForwardXrayTR::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition * condition) override virtual
Reimplemented from G4TransitionRadiation.
Definition at line 176 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 176 of file G4ForwardXrayTR.cc
References DBL_MAX, and Forced.
G4double G4ForwardXrayTR::GetMinProtonTkin () static
Definition at line 818 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 818 of file G4ForwardXrayTR.cc
References fMinProtonTkin.
G4int G4ForwardXrayTR::GetSympsonNumber () static
Definition at line 808 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 808 of file G4ForwardXrayTR.cc
References fSympsonNumber.
G4double G4ForwardXrayTR::GetThetaTR (G4int iMat, G4int jMat, G4int iTkin) const
Definition at line 803 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 803 of file G4ForwardXrayTR.cc
G4int G4ForwardXrayTR::GetTotBin () static
Definition at line 828 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 828 of file G4ForwardXrayTR.cc
References fTotBin.
G4ForwardXrayTR& G4ForwardXrayTR::operator= (const G4ForwardXrayTR & right) private delete
G4VParticleChange * G4ForwardXrayTR::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4TransitionRadiation.
Definition at line 465 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 465 of file G4ForwardXrayTR.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, charge, fAngleDistrTable, fBinTR, fEnergyDistrTable, fGeomBoundary, G4TransitionRadiation::fMatIndex1, G4TransitionRadiation::fMatIndex2, fProtonEnergyVector, fTotBin, G4Poisson(), G4UniformRand, G4Gamma::Gamma(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4MaterialCutsCouple::GetIndex(), G4GeometryTolerance::GetInstance(), G4DynamicParticle::GetKineticEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Material::GetState(), G4Track::GetStepLength(), G4StepPoint::GetStepStatus(), G4GeometryTolerance::GetSurfaceTolerance(), G4ParticleChange::Initialize(), kStateLiquid, kStateSolid, phi, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), source.hepunit::proton_mass_c2, CLHEP::Hep3Vector::rotateUz(), G4VParticleChange::SetNumberOfSecondaries(), theta(), and twopi.
G4double G4ForwardXrayTR::SpectralAngleTRdensity (G4double energy, G4double varAngle) const override virtual
Implements G4TransitionRadiation.
Definition at line 316 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 316 of file G4ForwardXrayTR.cc
References fGamma, fSigma1, and fSigma2.
G4double G4ForwardXrayTR::SpectralDensity (G4double energy, G4double x) const
Definition at line 407 of file G4ForwardXrayTR.cc.
View newest version in sPHENIX GitHub at line 407 of file G4ForwardXrayTR.cc
References a, b, energy, fGamma, fSigma1, and fSigma2.
Referenced by AngleInterval().
Member Data Documentation
G4PhysicsTable* G4ForwardXrayTR::fAngleDistrTable protected
Definition at line 148 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), G4ForwardXrayTR(), PostStepDoIt(), and ~G4ForwardXrayTR().
G4int G4ForwardXrayTR::fBinTR = 50 static protected
Definition at line 162 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), GetBinTR(), GetEnergyTR(), and PostStepDoIt().
G4double G4ForwardXrayTR::fCofTR = fine_structure_const/pi static protected
Definition at line 170 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables().
G4PhysicsTable* G4ForwardXrayTR::fEnergyDistrTable protected
Definition at line 149 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), G4ForwardXrayTR(), PostStepDoIt(), and ~G4ForwardXrayTR().
G4double G4ForwardXrayTR::fGamma protected
Definition at line 167 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ForwardXrayTR.hh
Referenced by AngleDensity(), BuildXrayTRtables(), G4ForwardXrayTR(), SpectralAngleTRdensity(), and SpectralDensity().
const std::vector<G4double>* G4ForwardXrayTR::fGammaCutInKineticEnergy protected
Definition at line 144 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), and G4ForwardXrayTR().
G4double G4ForwardXrayTR::fGammaTkinCut protected
Definition at line 146 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), and G4ForwardXrayTR().
G4double G4ForwardXrayTR::fMaxEnergyTR protected
Definition at line 158 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ForwardXrayTR.hh
Referenced by AngleSum(), BuildXrayTRtables(), and G4ForwardXrayTR().
G4double G4ForwardXrayTR::fMaxProtonTkin = 100.0*TeV static protected
Definition at line 165 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ForwardXrayTR.hh
Referenced by G4ForwardXrayTR(), and GetMaxProtonTkin().
G4double G4ForwardXrayTR::fMaxThetaTR protected
Definition at line 161 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), EnergySum(), and G4ForwardXrayTR().
G4double G4ForwardXrayTR::fMinEnergyTR protected
Definition at line 157 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ForwardXrayTR.hh
Referenced by AngleSum(), BuildXrayTRtables(), and G4ForwardXrayTR().
G4double G4ForwardXrayTR::fMinProtonTkin = 100.0*GeV static protected
Definition at line 164 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 164 of file G4ForwardXrayTR.hh
Referenced by G4ForwardXrayTR(), and GetMinProtonTkin().
G4double G4ForwardXrayTR::fPlasmaCof static protected
Initial value:
= 4.0*pi*fine_structure_const*
                                       hbarc*hbarc*hbarc/electron_mass_c2
Definition at line 169 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables().
G4PhysicsLogVector* G4ForwardXrayTR::fProtonEnergyVector protected
Definition at line 151 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), G4ForwardXrayTR(), PostStepDoIt(), and ~G4ForwardXrayTR().
G4ParticleDefinition* G4ForwardXrayTR::fPtrGamma protected
Definition at line 142 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ForwardXrayTR.hh
Referenced by G4ForwardXrayTR().
G4double G4ForwardXrayTR::fSigma1 protected
Definition at line 172 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ForwardXrayTR.hh
Referenced by AngleDensity(), BuildXrayTRtables(), G4ForwardXrayTR(), SpectralAngleTRdensity(), and SpectralDensity().
G4double G4ForwardXrayTR::fSigma2 protected
Definition at line 173 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ForwardXrayTR.hh
Referenced by AngleDensity(), BuildXrayTRtables(), G4ForwardXrayTR(), SpectralAngleTRdensity(), and SpectralDensity().
G4int G4ForwardXrayTR::fSympsonNumber = 100 static protected
Definition at line 153 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ForwardXrayTR.hh
Referenced by AngleSum(), EnergySum(), and GetSympsonNumber().
G4double G4ForwardXrayTR::fTheMaxAngle = 1.0e-3 static protected
Definition at line 159 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables().
G4double G4ForwardXrayTR::fTheMaxEnergyTR = 100.0*keV static protected
Definition at line 156 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables().
G4double G4ForwardXrayTR::fTheMinAngle = 5.0e-6 static protected
Definition at line 160 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables().
G4double G4ForwardXrayTR::fTheMinEnergyTR = 1.0*keV static protected
Definition at line 155 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables().
G4int G4ForwardXrayTR::fTotBin = 50 static protected
Definition at line 166 of file G4ForwardXrayTR.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ForwardXrayTR.hh
Referenced by BuildXrayTRtables(), G4ForwardXrayTR(), GetEnergyTR(), GetTotBin(), and PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4ForwardXrayTR.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/src/G4ForwardXrayTR.cc