ECCE @ EIC Software: G4NeutronEvaporationProbability Class Reference
G4NeutronEvaporationProbability Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4NeutronEvaporationProbability.hh>
Public Member Functions
G4NeutronEvaporationProbability ()
~G4NeutronEvaporationProbability () override
Public Member Functions inherited from G4EvaporationProbability
G4EvaporationProbability (G4int anA, G4int aZ, G4double aGamma)
~G4EvaporationProbability () override
virtual G4double TotalProbability (const G4Fragment &fragment, G4double minKinEnergy, G4double maxKinEnergy, G4double CB, G4double exEnergy)
G4double ComputeProbability (G4double K, G4double CB) override
G4double SampleKineticEnergy (G4double minKinEnergy, G4double maxKinEnergy, G4double CB)
Public Member Functions inherited from G4VEmissionProbability
G4VEmissionProbability (G4int Z, G4int A)
virtual ~G4VEmissionProbability ()
void Initialise ()
virtual G4double EmissionProbability (const G4Fragment &fragment, G4double anEnergy)
G4int GetZ (void) const
G4int GetA (void) const
void SetDecayKinematics (G4int Z, G4int A, G4double rmass, G4double fmass)
G4double GetRecoilExcitation () const
void SetEvapExcitation (G4double exc)
G4double GetProbability () const
void ResetProbability ()
G4double SampleEnergy ()
Protected Member Functions
G4double CalcAlphaParam (const G4Fragment &fragment) override
G4double CalcBetaParam (const G4Fragment &fragment) override
Private Member Functions
G4NeutronEvaporationProbability (const G4NeutronEvaporationProbability &right)
const
G4NeutronEvaporationProbability & operator= (const G4NeutronEvaporationProbability &right)
G4bool operator== (const G4NeutronEvaporationProbability &right) const
G4bool operator!= (const G4NeutronEvaporationProbability &right) const
Additional Inherited Members
Protected Attributes inherited from G4VEmissionProbability
G4int OPTxs
G4int pVerbose
G4int theZ
G4int theA
G4int resZ
G4int resA
G4double pMass
G4double pEvapMass
G4double pResMass
G4double pProbability
G4NuclearLevelData * pNuclearLevelData
G4Pow * pG4pow
Detailed Description
Definition at line 42 of file G4NeutronEvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 42 of file G4NeutronEvaporationProbability.hh
Constructor & Destructor Documentation
G4NeutronEvaporationProbability::G4NeutronEvaporationProbability () explicit
Definition at line 40 of file G4NeutronEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 40 of file G4NeutronEvaporationProbability.cc
G4NeutronEvaporationProbability::~G4NeutronEvaporationProbability () override
Definition at line 44 of file G4NeutronEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 44 of file G4NeutronEvaporationProbability.cc
G4NeutronEvaporationProbability::G4NeutronEvaporationProbability (const G4NeutronEvaporationProbability & right) private
Member Function Documentation
G4double G4NeutronEvaporationProbability::CalcAlphaParam (const G4Fragment & fragment) override protected virtual
Reimplemented from G4EvaporationProbability.
Definition at line 47 of file G4NeutronEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 47 of file G4NeutronEvaporationProbability.cc
References G4Fragment::GetA_asInt(), G4VEmissionProbability::pG4pow, and G4Pow::Z13().
Referenced by CalcBetaParam().
G4double G4NeutronEvaporationProbability::CalcBetaParam (const G4Fragment & fragment) override protected virtual
Reimplemented from G4EvaporationProbability.
Definition at line 52 of file G4NeutronEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 52 of file G4NeutronEvaporationProbability.cc
References CalcAlphaParam(), G4Fragment::GetA_asInt(), CLHEP::MeV, G4VEmissionProbability::pG4pow, and G4Pow::Z23().
G4bool G4NeutronEvaporationProbability::operator!= (const G4NeutronEvaporationProbability & right) const private
const G4NeutronEvaporationProbability& G4NeutronEvaporationProbability::operator= (const G4NeutronEvaporationProbability & right) private
G4bool G4NeutronEvaporationProbability::operator== (const G4NeutronEvaporationProbability & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4NeutronEvaporationProbability.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4NeutronEvaporationProbability.cc