ECCE @ EIC Software: G3DetTableEntry Class Reference
G3DetTableEntry Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3DetTableEntry.hh>
Public Member Functions
G3DetTableEntry (G4String &set, G4String &det, G4int id, G4VSensitiveDetector *D)
~G3DetTableEntry ()
G4VSensitiveDetector * GetSD ()
G4String GetSet ()
G4String GetDet ()
G4int GetID ()
Private Attributes
G4String _set
G4String _det
G4int _id
G4VSensitiveDetector * _detpt
Detailed Description
Definition at line 37 of file G3DetTableEntry.hh.
View newest version in sPHENIX GitHub at line 37 of file G3DetTableEntry.hh
Constructor & Destructor Documentation
G3DetTableEntry::G3DetTableEntry (G4String & set, G4String & det, G4int id, G4VSensitiveDetector * D)
Definition at line 32 of file G3DetTableEntry.cc.
View newest version in sPHENIX GitHub at line 32 of file G3DetTableEntry.cc
References _det, _detpt, _id, _set, and D().
G3DetTableEntry::~G3DetTableEntry ()
Definition at line 40 of file G3DetTableEntry.cc.
View newest version in sPHENIX GitHub at line 40 of file G3DetTableEntry.cc
Member Function Documentation
G4String G3DetTableEntry::GetDet ()
Definition at line 53 of file G3DetTableEntry.cc.
View newest version in sPHENIX GitHub at line 53 of file G3DetTableEntry.cc
References _det.
G4int G3DetTableEntry::GetID ()
Definition at line 58 of file G3DetTableEntry.cc.
View newest version in sPHENIX GitHub at line 58 of file G3DetTableEntry.cc
References _id.
Referenced by G3DetTable::GetID().
G4VSensitiveDetector * G3DetTableEntry::GetSD ()
Definition at line 43 of file G3DetTableEntry.cc.
View newest version in sPHENIX GitHub at line 43 of file G3DetTableEntry.cc
References _detpt.
Referenced by G3DetTable::GetSD(), and G3DetTable::PrintAll().
G4String G3DetTableEntry::GetSet ()
Definition at line 48 of file G3DetTableEntry.cc.
View newest version in sPHENIX GitHub at line 48 of file G3DetTableEntry.cc
References _set.
Member Data Documentation
G4String G3DetTableEntry::_det private
Definition at line 40 of file G3DetTableEntry.hh.
View newest version in sPHENIX GitHub at line 40 of file G3DetTableEntry.hh
Referenced by G3DetTableEntry(), and GetDet().
G4VSensitiveDetector* G3DetTableEntry::_detpt private
Definition at line 42 of file G3DetTableEntry.hh.
View newest version in sPHENIX GitHub at line 42 of file G3DetTableEntry.hh
Referenced by G3DetTableEntry(), and GetSD().
G4int G3DetTableEntry::_id private
Definition at line 41 of file G3DetTableEntry.hh.
View newest version in sPHENIX GitHub at line 41 of file G3DetTableEntry.hh
Referenced by G3DetTableEntry(), and GetID().
G4String G3DetTableEntry::_set private
Definition at line 39 of file G3DetTableEntry.hh.
View newest version in sPHENIX GitHub at line 39 of file G3DetTableEntry.hh
Referenced by G3DetTableEntry(), and GetSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3DetTableEntry.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3DetTableEntry.cc