ECCE @ EIC Software: G4BertiniKaonBuilder Class Reference
G4BertiniKaonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BertiniKaonBuilder.hh>
Public Member Functions
G4BertiniKaonBuilder ()
virtual ~G4BertiniKaonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VKaonBuilder
G4VKaonBuilder ()=default
virtual ~G4VKaonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4VCrossSectionDataSet * KaonMinusCrossSection
G4VCrossSectionDataSet * KaonPlusCrossSection
G4VCrossSectionDataSet * KaonZeroCrossSection
G4CascadeInterface * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BertiniKaonBuilder.hh
Constructor & Destructor Documentation
G4BertiniKaonBuilder::G4BertiniKaonBuilder ()
Definition at line 50 of file G4BertiniKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 50 of file G4BertiniKaonBuilder.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), KaonMinusCrossSection, KaonPlusCrossSection, KaonZeroCrossSection, G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual G4BertiniKaonBuilder::~G4BertiniKaonBuilder () inline virtual
Definition at line 56 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BertiniKaonBuilder.hh
Member Function Documentation
virtual void G4BertiniKaonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VKaonBuilder.
Definition at line 59 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BertiniKaonBuilder.hh
void G4BertiniKaonBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 62 of file G4BertiniKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 62 of file G4BertiniKaonBuilder.cc
References G4HadronicProcess::AddDataSet(), KaonPlusCrossSection, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4BertiniKaonBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 71 of file G4BertiniKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 71 of file G4BertiniKaonBuilder.cc
References G4HadronicProcess::AddDataSet(), KaonMinusCrossSection, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4BertiniKaonBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 80 of file G4BertiniKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 80 of file G4BertiniKaonBuilder.cc
References G4HadronicProcess::AddDataSet(), KaonZeroCrossSection, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4BertiniKaonBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 89 of file G4BertiniKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 89 of file G4BertiniKaonBuilder.cc
References G4HadronicProcess::AddDataSet(), KaonZeroCrossSection, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4BertiniKaonBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 66 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BertiniKaonBuilder.hh
References theMax.
virtual void G4BertiniKaonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 65 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BertiniKaonBuilder.hh
References theMin.
Referenced by G4HadronPhysicsINCLXX::Kaon().
Member Data Documentation
G4VCrossSectionDataSet* G4BertiniKaonBuilder::KaonMinusCrossSection private
Definition at line 70 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BertiniKaonBuilder.hh
Referenced by Build(), and G4BertiniKaonBuilder().
G4VCrossSectionDataSet* G4BertiniKaonBuilder::KaonPlusCrossSection private
Definition at line 71 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BertiniKaonBuilder.hh
Referenced by Build(), and G4BertiniKaonBuilder().
G4VCrossSectionDataSet* G4BertiniKaonBuilder::KaonZeroCrossSection private
Definition at line 72 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BertiniKaonBuilder.hh
Referenced by Build(), and G4BertiniKaonBuilder().
G4double G4BertiniKaonBuilder::theMax private
Definition at line 76 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4BertiniKaonBuilder.hh
Referenced by Build(), G4BertiniKaonBuilder(), and SetMaxEnergy().
G4double G4BertiniKaonBuilder::theMin private
Definition at line 75 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BertiniKaonBuilder.hh
Referenced by Build(), G4BertiniKaonBuilder(), and SetMinEnergy().
G4CascadeInterface* G4BertiniKaonBuilder::theModel private
Definition at line 74 of file G4BertiniKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4BertiniKaonBuilder.hh
Referenced by Build(), and G4BertiniKaonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BertiniKaonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4BertiniKaonBuilder.cc