ECCE @ EIC Software: G4InuclElementaryParticle Class Reference
G4InuclElementaryParticle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclElementaryParticle.hh>
Public Member Functions
G4InuclElementaryParticle ()
G4InuclElementaryParticle (G4int ityp, Model model=DefaultModel)
G4InuclElementaryParticle (const G4DynamicParticle &dynPart, Model model=DefaultModel)
G4InuclElementaryParticle (const G4LorentzVector &mom, G4int ityp, Model model=DefaultModel)
G4InuclElementaryParticle (G4double ekin, G4int ityp, Model model=DefaultModel)
G4InuclElementaryParticle (const G4LorentzVector &mom, const G4ParticleDefinition *pd, Model model=DefaultModel)
G4InuclElementaryParticle (const G4InuclElementaryParticle &right)
G4InuclElementaryParticle & operator= (const G4InuclElementaryParticle &right)
void fill (G4int ityp, Model model=DefaultModel)
void fill (const G4LorentzVector &mom, G4int ityp, Model model=DefaultModel)
void fill (G4double ekin, G4int ityp, Model model=DefaultModel)
void fill (const G4LorentzVector &mom, const G4ParticleDefinition *pd, Model model=DefaultModel)
void setType (G4int ityp)
G4int type () const
G4bool valid () const
G4bool isPhoton () const
G4bool isMuon () const
G4bool isElectron () const
G4bool isNeutrino () const
G4bool pion () const
G4bool nucleon () const
G4bool antinucleon () const
G4int baryon () const
G4bool antibaryon () const
G4bool hyperon () const
G4bool quasi_deutron () const
G4int getStrangeness () const
virtual void print (std::ostream &os) const
Public Member Functions inherited from G4InuclParticle
G4InuclParticle ()
G4InuclParticle (const G4DynamicParticle &dynPart, Model model=DefaultModel)
G4InuclParticle (const G4LorentzVector &mom, Model model=DefaultModel)
virtual ~G4InuclParticle ()
G4InuclParticle (const G4InuclParticle &right)
G4InuclParticle & operator= (const G4InuclParticle &right)
G4bool operator== (const G4InuclParticle &right)
G4bool operator!= (const G4InuclParticle &right)
void setEnergy ()
void setMomentum (const G4LorentzVector &mom)
void setKineticEnergy (G4double ekin)
void setMass (G4double mass)
G4double getMass () const
G4double getCharge () const
G4double getKineticEnergy () const
G4double getEnergy () const
G4double getMomModule () const
G4LorentzVector getMomentum () const
const G4ParticleDefinition * getDefinition () const
const G4DynamicParticle & getDynamicParticle () const
void setModel (Model model)
Model getModel () const
Static Public Member Functions
static G4int type (const G4ParticleDefinition *pd)
static G4bool valid (G4int ityp)
static G4int getStrangeness (G4int type)
static G4double getParticleMass (G4int type)
Static Protected Member Functions
static const G4ParticleDefinition * makeDefinition (G4int ityp)
Additional Inherited Members
Public Types inherited from G4InuclParticle
enum Model {
DefaultModel, bullet, target, EPCollider,
INCascader, NonEquilib, Equilib, Fissioner,
BigBanger, PreCompound, Coalescence
}
Protected Member Functions inherited from G4InuclParticle
G4InuclParticle (const G4ParticleDefinition *pd, Model model=DefaultModel)
G4InuclParticle (const G4ParticleDefinition *pd, const G4LorentzVector &mom, Model model=DefaultModel)
G4InuclParticle (const G4ParticleDefinition *pd, G4double ekin, Model model=DefaultModel)
void setDefinition (const G4ParticleDefinition *pd)
Detailed Description
Definition at line 58 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 58 of file G4InuclElementaryParticle.hh
Constructor & Destructor Documentation
G4InuclElementaryParticle::G4InuclElementaryParticle () inline
Definition at line 60 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 60 of file G4InuclElementaryParticle.hh
G4InuclElementaryParticle::G4InuclElementaryParticle (G4int ityp, Model model = DefaultModel) inline
Definition at line 63 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 63 of file G4InuclElementaryParticle.hh
G4InuclElementaryParticle::G4InuclElementaryParticle (const G4DynamicParticle & dynPart, Model model = DefaultModel) inline
Definition at line 66 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 66 of file G4InuclElementaryParticle.hh
G4InuclElementaryParticle::G4InuclElementaryParticle (const G4LorentzVector & mom, G4int ityp, Model model = DefaultModel) inline
Definition at line 70 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 70 of file G4InuclElementaryParticle.hh
G4InuclElementaryParticle::G4InuclElementaryParticle (G4double ekin, G4int ityp, Model model = DefaultModel) inline
Definition at line 74 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 74 of file G4InuclElementaryParticle.hh
G4InuclElementaryParticle::G4InuclElementaryParticle (const G4LorentzVector & mom, const G4ParticleDefinition * pd, Model model = DefaultModel) inline
Definition at line 79 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 79 of file G4InuclElementaryParticle.hh
G4InuclElementaryParticle::G4InuclElementaryParticle (const G4InuclElementaryParticle & right) inline
Definition at line 85 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 85 of file G4InuclElementaryParticle.hh
Member Function Documentation
G4bool G4InuclElementaryParticle::antibaryon () const inline
Definition at line 123 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 123 of file G4InuclElementaryParticle.hh
References baryon().
G4bool G4InuclElementaryParticle::antinucleon () const inline
Definition at line 117 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 117 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::antinucleon(), and type().
G4int G4InuclElementaryParticle::baryon () const inline
Definition at line 119 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 119 of file G4InuclElementaryParticle.hh
References G4ParticleDefinition::GetBaryonNumber(), and G4InuclParticle::getDefinition().
Referenced by antibaryon(), G4CascadeCheckBalance::collide(), G4CascadeHistory::GuessTarget(), hyperon(), and G4IntraNucleiCascader::setupCascade().
void G4InuclElementaryParticle::fill (G4int ityp, Model model = DefaultModel) inline
Definition at line 91 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 91 of file G4InuclElementaryParticle.hh
References fill().
Referenced by G4CascadeInterface::createBullet(), G4IntraNucleiCascader::createTarget(), G4CascadeInterface::createTarget(), fill(), G4IntraNucleiCascader::processSecondary(), and G4IntraNucleiCascader::releaseSecondary().
void G4InuclElementaryParticle::fill (const G4LorentzVector & mom, G4int ityp, G4InuclParticle::Model model = DefaultModel)
Definition at line 179 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 179 of file G4InuclElementaryParticle.cc
void G4InuclElementaryParticle::fill (G4double ekin, G4int ityp, G4InuclParticle::Model model = DefaultModel)
Definition at line 186 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 186 of file G4InuclElementaryParticle.cc
void G4InuclElementaryParticle::fill (const G4LorentzVector & mom, const G4ParticleDefinition * pd, G4InuclParticle::Model model = DefaultModel)
Definition at line 193 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 193 of file G4InuclElementaryParticle.cc
G4double G4InuclElementaryParticle::getParticleMass (G4int type) static
Definition at line 215 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 215 of file G4InuclElementaryParticle.cc
References G4ParticleDefinition::GetPDGMass(), GeV, and MeV.
Referenced by G4EquilibriumEvaporator::deExcite(), G4ElementaryParticleCollider::fillOutgoingMasses(), G4NucleiModel::fillPotentials(), G4IntraNucleiCascader::finishCascade(), G4BigBanger::generateMomentumModules(), G4NucleiModel::generateNucleonMomentum(), G4NucleiModel::getFermiKinetic(), and G4LightTargetCollider::SingleNucleonScattering().
G4int G4InuclElementaryParticle::getStrangeness () const inline
Definition at line 131 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 131 of file G4InuclElementaryParticle.hh
References getStrangeness(), and type().
Referenced by G4CascadeCheckBalance::collide(), getStrangeness(), and hyperon().
G4int G4InuclElementaryParticle::getStrangeness (G4int type) static
Definition at line 210 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 210 of file G4InuclElementaryParticle.cc
References G4ParticleDefinition::GetAntiQuarkContent(), and G4ParticleDefinition::GetQuarkContent().
G4bool G4InuclElementaryParticle::hyperon () const inline
Definition at line 125 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 125 of file G4InuclElementaryParticle.hh
References baryon(), and getStrangeness().
Referenced by G4IntraNucleiCascader::processTrappedParticle().
G4bool G4InuclElementaryParticle::isElectron () const inline
Definition at line 113 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 113 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::isElectron(), and type().
Referenced by G4InuclCollider::photonuclearOkay().
G4bool G4InuclElementaryParticle::isMuon () const inline
Definition at line 112 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 112 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::isMuon(), and type().
Referenced by G4ElementaryParticleCollider::collide(), and G4NucleiModel::forceFirst().
G4bool G4InuclElementaryParticle::isNeutrino () const inline
Definition at line 114 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 114 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::isNeutrino(), and type().
Referenced by G4ElementaryParticleCollider::collide(), and G4NucleiModel::inverseMeanFreePath().
G4bool G4InuclElementaryParticle::isPhoton () const inline
Definition at line 111 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 111 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::isPhoton(), and type().
Referenced by G4NucleiModel::forceFirst(), and G4InuclCollider::photonuclearOkay().
const G4ParticleDefinition * G4InuclElementaryParticle::makeDefinition (G4int ityp) static protected
Definition at line 57 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 57 of file G4InuclElementaryParticle.cc
References G4InuclParticleNames::alpha, G4InuclParticleNames::antiAlpha, G4InuclParticleNames::antiDeuteron, G4InuclParticleNames::antiElectronNu, G4InuclParticleNames::antiHe3, G4InuclParticleNames::antiMuonNu, G4InuclParticleNames::antiNeutron, G4InuclParticleNames::antiProton, G4InuclParticleNames::antiTauNu, G4InuclParticleNames::antiTriton, G4Diproton::Definition(), G4UnboundPN::Definition(), G4Dineutron::Definition(), G4KaonMinus::Definition(), G4XiMinus::Definition(), G4NeutrinoE::Definition(), G4OmegaMinus::Definition(), G4AntiNeutrinoE::Definition(), G4MuonMinus::Definition(), G4KaonZero::Definition(), G4MuonPlus::Definition(), G4NeutrinoMu::Definition(), G4AntiNeutrinoMu::Definition(), G4TauMinus::Definition(), G4PionMinus::Definition(), G4TauPlus::Definition(), G4AntiKaonZero::Definition(), G4PionZero::Definition(), G4AntiNeutrinoTau::Definition(), G4Lambda::Definition(), G4AntiProton::Definition(), G4PionPlus::Definition(), G4AntiNeutron::Definition(), G4NeutrinoTau::Definition(), G4KaonPlus::Definition(), G4SigmaPlus::Definition(), G4SigmaZero::Definition(), G4SigmaMinus::Definition(), G4XiZero::Definition(), G4Electron::Definition(), G4Positron::Definition(), G4Neutron::Definition(), G4Deuteron::Definition(), G4Triton::Definition(), G4Alpha::Definition(), G4He3::Definition(), G4AntiDeuteron::Definition(), G4AntiTriton::Definition(), G4AntiHe3::Definition(), G4AntiAlpha::Definition(), G4Proton::Definition(), G4Gamma::Definition(), G4InuclParticleNames::deuteron, G4InuclParticleNames::dineutron, G4InuclParticleNames::diproton, G4InuclParticleNames::electron, G4InuclParticleNames::electronNu, G4cerr, G4endl, G4InuclParticleNames::He3, G4InuclParticleNames::kaonMinus, G4InuclParticleNames::kaonPlus, G4InuclParticleNames::kaonZero, G4InuclParticleNames::kaonZeroBar, G4InuclParticleNames::lambda, G4InuclParticleNames::muonMinus, G4InuclParticleNames::muonNu, G4InuclParticleNames::muonPlus, G4InuclParticleNames::neutron, G4InuclParticleNames::omegaMinus, G4InuclParticleNames::photon, G4InuclParticleNames::pionMinus, G4InuclParticleNames::pionPlus, G4InuclParticleNames::pionZero, G4InuclParticleNames::positron, G4InuclParticleNames::proton, G4InuclParticleNames::sigmaMinus, G4InuclParticleNames::sigmaPlus, G4InuclParticleNames::sigmaZero, G4InuclParticleNames::tauMinus, G4InuclParticleNames::tauNu, G4InuclParticleNames::tauPlus, G4InuclParticleNames::triton, G4InuclParticleNames::unboundPN, G4InuclParticleNames::xiMinus, and G4InuclParticleNames::xiZero.
G4bool G4InuclElementaryParticle::nucleon () const inline
Definition at line 116 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 116 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::nucleon(), and type().
Referenced by G4CascadeCoalescence::allNucleons(), G4CascadeCoalescence::clusterType(), G4ElementaryParticleCollider::collide(), G4NucleiModel::generateParticleFate(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4IntraNucleiCascader::processTrappedParticle(), G4CascadeFinalStateAlgorithm::SaveKinematics(), and G4NucleiModel::worthToPropagate().
G4InuclElementaryParticle & G4InuclElementaryParticle::operator= (const G4InuclElementaryParticle & right)
Definition at line 204 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 204 of file G4InuclElementaryParticle.cc
References G4InuclParticle::operator=().
G4bool G4InuclElementaryParticle::pion () const inline
Definition at line 115 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 115 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::pion(), and type().
void G4InuclElementaryParticle::print (std::ostream & os) const virtual
Reimplemented from G4InuclParticle.
Definition at line 223 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 223 of file G4InuclElementaryParticle.cc
References G4endl, and G4InuclParticle::print().
G4bool G4InuclElementaryParticle::quasi_deutron () const inline
Definition at line 127 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 127 of file G4InuclElementaryParticle.hh
References G4InuclParticleNames::quasi_deutron(), and type().
Referenced by G4ElementaryParticleCollider::collide(), G4NucleiModel::generateParticleFate(), and G4CascadeInterface::makeDynamicParticle().
void G4InuclElementaryParticle::setType (G4int ityp)
Definition at line 172 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 172 of file G4InuclElementaryParticle.cc
G4int G4InuclElementaryParticle::type () const inline
Definition at line 103 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 103 of file G4InuclElementaryParticle.hh
References G4InuclParticle::getDefinition(), and type().
Referenced by G4CollisionOutput::addOutgoingParticles(), antinucleon(), G4NucleiModel::boundaryTransition(), G4CascadeCoalescence::clusterType(), G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4CascadeFinalStateAlgorithm::Configure(), G4IntraNucleiCascader::copyWoundedNucleus(), G4CascadeInterface::createBullet(), G4IntraNucleiCascader::decayTrappedParticle(), G4NucleiModel::generateInteractionPartners(), G4NucleiModel::generateParticleFate(), G4ElementaryParticleCollider::generateSCMfinalState(), G4ElementaryParticleCollider::generateSCMmuonAbsorption(), G4ElementaryParticleCollider::generateSCMpionAbsorption(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), getStrangeness(), G4NucleiModel::inverseMeanFreePath(), G4CascadeInterface::IsApplicable(), isElectron(), isMuon(), isNeutrino(), isPhoton(), G4CascadeInterface::makeDynamicParticle(), nucleon(), G4IntraNucleiCascader::particleCanInteract(), pion(), G4IntraNucleiCascader::processSecondary(), G4IntraNucleiCascader::processTrappedParticle(), quasi_deutron(), G4InteractionCase::set(), G4LightTargetCollider::SingleNucleonScattering(), type(), valid(), and G4NucleiModel::worthToPropagate().
G4int G4InuclElementaryParticle::type (const G4ParticleDefinition * pd) static
Definition at line 115 of file G4InuclElementaryParticle.cc.
View newest version in sPHENIX GitHub at line 115 of file G4InuclElementaryParticle.cc
References G4InuclParticleNames::alpha, G4InuclParticleNames::antiAlpha, G4InuclParticleNames::antiDeuteron, G4InuclParticleNames::antiElectronNu, G4InuclParticleNames::antiHe3, G4InuclParticleNames::antiMuonNu, G4InuclParticleNames::antiNeutron, G4InuclParticleNames::antiProton, G4InuclParticleNames::antiTauNu, G4InuclParticleNames::antiTriton, G4Diproton::Definition(), G4UnboundPN::Definition(), G4Dineutron::Definition(), G4KaonZero::Definition(), G4NeutrinoE::Definition(), G4AntiNeutrinoE::Definition(), G4OmegaMinus::Definition(), G4MuonMinus::Definition(), G4MuonPlus::Definition(), G4KaonZeroShort::Definition(), G4NeutrinoMu::Definition(), G4AntiNeutrinoMu::Definition(), G4AntiKaonZero::Definition(), G4TauMinus::Definition(), G4TauPlus::Definition(), G4NeutrinoTau::Definition(), G4AntiNeutrinoTau::Definition(), G4Lambda::Definition(), G4AntiProton::Definition(), G4KaonZeroLong::Definition(), G4PionPlus::Definition(), G4SigmaPlus::Definition(), G4AntiNeutron::Definition(), G4PionZero::Definition(), G4PionMinus::Definition(), G4SigmaZero::Definition(), G4KaonPlus::Definition(), G4SigmaMinus::Definition(), G4XiZero::Definition(), G4KaonMinus::Definition(), G4XiMinus::Definition(), G4Electron::Definition(), G4Proton::Definition(), G4Deuteron::Definition(), G4Triton::Definition(), G4Positron::Definition(), G4AntiDeuteron::Definition(), G4AntiTriton::Definition(), G4AntiHe3::Definition(), G4AntiAlpha::Definition(), G4Alpha::Definition(), G4He3::Definition(), G4Neutron::Definition(), G4Gamma::Definition(), G4InuclParticleNames::deuteron, G4InuclParticleNames::dineutron, G4InuclParticleNames::diproton, G4InuclParticleNames::electron, G4InuclParticleNames::electronNu, G4UniformRand, G4InuclParticleNames::He3, G4InuclParticleNames::kaonMinus, G4InuclParticleNames::kaonPlus, G4InuclParticleNames::kaonZero, G4InuclParticleNames::kaonZeroBar, G4InuclParticleNames::lambda, G4InuclParticleNames::muonMinus, G4InuclParticleNames::muonNu, G4InuclParticleNames::muonPlus, G4InuclParticleNames::neutron, G4InuclParticleNames::omegaMinus, G4InuclParticleNames::photon, G4InuclParticleNames::pionMinus, G4InuclParticleNames::pionPlus, G4InuclParticleNames::pionZero, G4InuclParticleNames::positron, G4InuclParticleNames::proton, G4InuclParticleNames::sigmaMinus, G4InuclParticleNames::sigmaPlus, G4InuclParticleNames::sigmaZero, G4InuclParticleNames::tauMinus, G4InuclParticleNames::tauNu, G4InuclParticleNames::tauPlus, G4InuclParticleNames::triton, G4InuclParticleNames::unboundPN, G4InuclParticleNames::xiMinus, and G4InuclParticleNames::xiZero.
static G4bool G4InuclElementaryParticle::valid (G4int ityp) inline static
Definition at line 108 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 108 of file G4InuclElementaryParticle.hh
G4bool G4InuclElementaryParticle::valid () const inline
Definition at line 109 of file G4InuclElementaryParticle.hh.
View newest version in sPHENIX GitHub at line 109 of file G4InuclElementaryParticle.hh
References type(), and valid().
Referenced by G4CascadeInterface::createBullet(), and valid().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclElementaryParticle.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InuclElementaryParticle.cc