ECCE @ EIC Software: G4VBiasingInteractionLaw Class Reference
G4VBiasingInteractionLaw Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4VBiasingInteractionLaw.hh>
Public Member Functions
G4VBiasingInteractionLaw (G4String name)
virtual ~G4VBiasingInteractionLaw ()
const G4String & GetName () const
virtual G4double ComputeNonInteractionProbabilityAt (G4double length) const =0
virtual G4double ComputeEffectiveCrossSectionAt (G4double length) const =0
virtual G4bool IsSingular () const
virtual G4bool IsEffectiveCrossSectionInfinite () const
G4double Sample ()
G4double UpdateForStep (G4double truePathLength)
G4double GetSampledInteractionLength () const
Protected Member Functions
virtual G4double SampleInteractionLength ()=0
virtual G4double UpdateInteractionLengthForStep (G4double)
Private Attributes
G4String fName
G4double fSampledInteractionLength
Detailed Description
Definition at line 61 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VBiasingInteractionLaw.hh
Constructor & Destructor Documentation
G4VBiasingInteractionLaw::G4VBiasingInteractionLaw (G4String name) inline
Definition at line 63 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VBiasingInteractionLaw.hh
virtual G4VBiasingInteractionLaw::~G4VBiasingInteractionLaw () inline virtual
Definition at line 64 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VBiasingInteractionLaw.hh
Member Function Documentation
virtual G4double G4VBiasingInteractionLaw::ComputeEffectiveCrossSectionAt (G4double length) const pure virtual
Implemented in G4ILawCommonTruncatedExp, G4ILawForceFreeFlight, G4InteractionLawPhysical, and G4ILawTruncatedExp.
Referenced by G4BiasingProcessInterface::PostStepDoIt().
virtual G4double G4VBiasingInteractionLaw::ComputeNonInteractionProbabilityAt (G4double length) const pure virtual
Implemented in G4ILawCommonTruncatedExp, G4ILawForceFreeFlight, G4InteractionLawPhysical, and G4ILawTruncatedExp.
const G4String& G4VBiasingInteractionLaw::GetName (void) const inline
Definition at line 67 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VBiasingInteractionLaw.hh
References fName.
Referenced by G4BiasingProcessInterface::AlongStepDoIt(), G4ILawCommonTruncatedExp::ComputeNonInteractionProbabilityAt(), G4ILawTruncatedExp::UpdateInteractionLengthForStep(), and G4InteractionLawPhysical::UpdateInteractionLengthForStep().
G4double G4VBiasingInteractionLaw::GetSampledInteractionLength () const inline
Definition at line 107 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VBiasingInteractionLaw.hh
References fSampledInteractionLength.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength().
virtual G4bool G4VBiasingInteractionLaw::IsEffectiveCrossSectionInfinite () const inline virtual
Reimplemented in G4ILawCommonTruncatedExp.
Definition at line 90 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VBiasingInteractionLaw.hh
Referenced by G4ILawCommonTruncatedExp::IsEffectiveCrossSectionInfinite(), and G4BiasingProcessInterface::PostStepDoIt().
virtual G4bool G4VBiasingInteractionLaw::IsSingular () const inline virtual
Reimplemented in G4ILawForceFreeFlight, G4ILawCommonTruncatedExp, and G4ILawTruncatedExp.
Definition at line 88 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VBiasingInteractionLaw.hh
Referenced by G4BiasingProcessInterface::PostStepDoIt().
G4double G4VBiasingInteractionLaw::Sample () inline
Definition at line 97 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 97 of file G4VBiasingInteractionLaw.hh
References fSampledInteractionLength, and SampleInteractionLength().
Referenced by G4BOptnChangeCrossSection::Sample(), and G4BOptnForceCommonTruncatedExp::Sample().
virtual G4double G4VBiasingInteractionLaw::SampleInteractionLength () protected pure virtual
Implemented in G4ILawCommonTruncatedExp, G4ILawForceFreeFlight, G4InteractionLawPhysical, and G4ILawTruncatedExp.
Referenced by Sample().
G4double G4VBiasingInteractionLaw::UpdateForStep (G4double truePathLength) inline
Definition at line 102 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VBiasingInteractionLaw.hh
References fSampledInteractionLength, and UpdateInteractionLengthForStep().
Referenced by G4BOptnChangeCrossSection::UpdateForStep(), and G4BOptnForceCommonTruncatedExp::UpdateForStep().
virtual G4double G4VBiasingInteractionLaw::UpdateInteractionLengthForStep (G4double) inline protected virtual
Reimplemented in G4ILawCommonTruncatedExp, G4ILawForceFreeFlight, G4InteractionLawPhysical, and G4ILawTruncatedExp.
Definition at line 83 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 83 of file G4VBiasingInteractionLaw.hh
References DBL_MAX.
Referenced by UpdateForStep().
Member Data Documentation
G4String G4VBiasingInteractionLaw::fName private
Definition at line 111 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VBiasingInteractionLaw.hh
Referenced by GetName().
G4double G4VBiasingInteractionLaw::fSampledInteractionLength private
Definition at line 112 of file G4VBiasingInteractionLaw.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VBiasingInteractionLaw.hh
Referenced by GetSampledInteractionLength(), Sample(), and UpdateForStep().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4VBiasingInteractionLaw.hh