ECCE @ EIC Software: G4ParticleHPInterpolator Class Reference
G4ParticleHPInterpolator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInterpolator.hh>
Public Member Functions
G4ParticleHPInterpolator ()
~G4ParticleHPInterpolator ()
G4double Lin (G4double x, G4double x1, G4double x2, G4double y1, G4double y2)
G4double Interpolate (G4InterpolationScheme aScheme, G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double Interpolate2 (G4InterpolationScheme aScheme, G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double GetBinIntegral (const G4InterpolationScheme &aScheme, const G4double x1, const G4double x2, const G4double y1, const G4double y2)
G4double GetWeightedBinIntegral (const G4InterpolationScheme &aScheme, const G4double x1, const G4double x2, const G4double y1, const G4double y2)
Private Member Functions
G4double Histogram (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double LinearLinear (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double LinearLogarithmic (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double LogarithmicLinear (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double LogarithmicLogarithmic (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double Random (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const
Detailed Description
Definition at line 44 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPInterpolator.hh
Constructor & Destructor Documentation
G4ParticleHPInterpolator::G4ParticleHPInterpolator () inline
Definition at line 48 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPInterpolator.hh
G4ParticleHPInterpolator::~G4ParticleHPInterpolator () inline
Definition at line 49 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPInterpolator.hh
Member Function Documentation
G4double G4ParticleHPInterpolator::GetBinIntegral (const G4InterpolationScheme & aScheme, const G4double x1, const G4double x2, const G4double y1, const G4double y2)
Definition at line 36 of file G4ParticleHPInterpolator.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPInterpolator.cc
References a, b, CHISTO, CLINLIN, CLINLOG, CLOGLIN, CLOGLOG, G4Exp(), G4Log(), G4Pow::GetInstance(), HISTO, LINLIN, LINLOG, LOGLIN, LOGLOG, G4Pow::powA(), UHISTO, ULINLIN, ULINLOG, ULOGLIN, ULOGLOG, x1, y1, and y2.
Referenced by G4ParticleHPVector::GetMeanX(), G4ParticleHPVector::IntegrateAndNormalise(), and G4ParticleHPContAngularPar::Sample().
G4double G4ParticleHPInterpolator::GetWeightedBinIntegral (const G4InterpolationScheme & aScheme, const G4double x1, const G4double x2, const G4double y1, const G4double y2)
Definition at line 97 of file G4ParticleHPInterpolator.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPInterpolator.cc
References a, b, CHISTO, CLINLIN, CLINLOG, CLOGLIN, CLOGLOG, G4Exp(), G4Log(), G4Pow::GetInstance(), HISTO, LINLIN, LINLOG, LOGLIN, LOGLOG, G4Pow::powA(), UHISTO, ULINLIN, ULINLOG, ULOGLIN, ULOGLOG, x1, y1, and y2.
Referenced by G4ParticleHPVector::GetMeanX(), and G4ParticleHPContAngularPar::Sample().
G4double G4ParticleHPInterpolator::Histogram (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 163 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ParticleHPInterpolator.hh
References y1.
Referenced by Interpolate2().
G4double G4ParticleHPInterpolator::Interpolate (G4InterpolationScheme aScheme, G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline
Definition at line 91 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPInterpolator.hh
References CSTART_, G4cout, G4endl, LinearLinear(), LinearLogarithmic(), LogarithmicLinear(), LogarithmicLogarithmic(), and Random().
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation(), G4ParticleHPAngularP::GetCosTh(), CCalDataSet::getCrossSection(), G4ParticleHPVector::GetXsec(), G4ParticleHPPartial::GetY(), G4ParticleHPVector::Merge(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPPartial::Sample(), G4ParticleHPLegendreStore::SampleDiscreteTwoBody(), G4ParticleHPLegendreStore::SampleElastic(), and G4ParticleHPLegendreStore::SampleMax().
G4double G4ParticleHPInterpolator::Interpolate2 (G4InterpolationScheme aScheme, G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline
Definition at line 128 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleHPInterpolator.hh
References CSTART_, G4cout, G4endl, Histogram(), LinearLinear(), LinearLogarithmic(), LogarithmicLinear(), LogarithmicLogarithmic(), and Random().
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation().
G4double G4ParticleHPInterpolator::Lin (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) inline
Definition at line 54 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPInterpolator.hh
References y, and y1.
Referenced by G4ParticleHPVector::Get50percentBorder(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPVector::SampleLin(), and G4ParticleHPVector::ThinOut().
G4double G4ParticleHPInterpolator::LinearLinear (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 171 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ParticleHPInterpolator.hh
References y, and y1.
Referenced by Interpolate(), Interpolate2(), LinearLogarithmic(), LogarithmicLinear(), and LogarithmicLogarithmic().
G4double G4ParticleHPInterpolator::LinearLogarithmic (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 182 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 182 of file G4ParticleHPInterpolator.hh
References G4Log(), LinearLinear(), y1, and y2.
Referenced by Interpolate(), and Interpolate2().
G4double G4ParticleHPInterpolator::LogarithmicLinear (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 193 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 193 of file G4ParticleHPInterpolator.hh
References G4Exp(), G4Log(), and LinearLinear().
Referenced by Interpolate(), and Interpolate2().
G4double G4ParticleHPInterpolator::LogarithmicLogarithmic (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 206 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 206 of file G4ParticleHPInterpolator.hh
References G4Exp(), G4Log(), LinearLinear(), y1, and y2.
Referenced by Interpolate(), and Interpolate2().
G4double G4ParticleHPInterpolator::Random (G4double x, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 222 of file G4ParticleHPInterpolator.hh.
View newest version in sPHENIX GitHub at line 222 of file G4ParticleHPInterpolator.hh
References G4UniformRand, and y1.
Referenced by Interpolate(), and Interpolate2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInterpolator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPInterpolator.cc