ECCE @ EIC Software: G4NuclearLevelData Class Reference
G4NuclearLevelData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4NuclearLevelData.hh>
Public Member Functions
~G4NuclearLevelData ()
const G4LevelManager * GetLevelManager (G4int Z, G4int A)
G4bool AddPrivateData (G4int Z, G4int A, const G4String &filename)
G4int GetMinA (G4int Z) const
G4int GetMaxA (G4int Z) const
G4double GetMaxLevelEnergy (G4int Z, G4int A) const
G4float MaxLevelEnergy (G4int Z, G4int A) const
G4double GetLevelEnergy (G4int Z, G4int A, G4double energy)
G4double GetLowEdgeLevelEnergy (G4int Z, G4int A, G4double energy)
G4double FindLevel (G4int Z, G4int A, G4double resMass, G4double Mass, G4double partMass, G4double T)
G4DeexPrecoParameters * GetParameters ()
G4PairingCorrection * GetPairingCorrection ()
G4ShellCorrection * GetShellCorrection ()
G4double GetLevelDensity (G4int Z, G4int A, G4double U)
G4double GetPairingCorrection (G4int Z, G4int A)
void UploadNuclearLevelData (G4int Z)
void StreamLevels (std::ostream &os, G4int Z, G4int A)
G4NuclearLevelData (G4NuclearLevelData &)=delete
G4NuclearLevelData & operator= (const G4NuclearLevelData &right)=delete
Static Public Member Functions
static G4NuclearLevelData * GetInstance ()
Private Member Functions
G4NuclearLevelData ()
Private Attributes
G4DeexPrecoParameters * fDeexPrecoParameters
G4LevelReader * fLevelReader
G4PairingCorrection * fPairingCorrection
G4ShellCorrection * fShellCorrection
G4Pow * fG4calc
G4bool fInitialized
std::vector< const
G4LevelManager * > fLevelManagers [ZMAX]
std::vector< G4bool > fLevelManagerFlags [ZMAX]
Static Private Attributes
static G4NuclearLevelData * theInstance = nullptr
static const G4int ZMAX = 118
static const G4int AMIN [ZMAX]
static const G4int AMAX [ZMAX]
static const G4int LEVELIDX [ZMAX]
Detailed Description
Definition at line 60 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 60 of file G4NuclearLevelData.hh
Constructor & Destructor Documentation
G4NuclearLevelData::G4NuclearLevelData () private
Definition at line 438 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 438 of file G4NuclearLevelData.cc
References AMAX, AMIN, fDeexPrecoParameters, fG4calc, fInitialized, fLevelManagerFlags, fLevelManagers, fLevelReader, fPairingCorrection, fShellCorrection, G4Pow::GetInstance(), Z, and ZMAX.
G4NuclearLevelData::~G4NuclearLevelData ()
Definition at line 452 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 452 of file G4NuclearLevelData.cc
References fDeexPrecoParameters, fLevelManagers, fLevelReader, fPairingCorrection, fShellCorrection, G4InuclParticleNames::nn, Z, and ZMAX.
G4NuclearLevelData::G4NuclearLevelData (G4NuclearLevelData &) delete
Member Function Documentation
G4bool G4NuclearLevelData::AddPrivateData (G4int Z, G4int A, const G4String & filename)
Definition at line 487 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 487 of file G4NuclearLevelData.cc
References AMAX, AMIN, FatalException, fLevelManagerFlags, fLevelManagers, fLevelReader, G4cout, G4endl, G4Exception(), G4MUTEXLOCK, G4MUTEXUNLOCK, incremental_prev_tag::idx, G4LevelReader::MakeLevelManager(), and Z.
Referenced by G4RadioactiveDecayBaseMessenger::SetNewValue(), and G4RadioactiveDecaymessenger::SetNewValue().
G4double G4NuclearLevelData::FindLevel (G4int Z, G4int A, G4double resMass, G4double Mass, G4double partMass, G4double T)
Definition at line 592 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 592 of file G4NuclearLevelData.cc
References GetLevelManager(), GetMaxLevelEnergy(), incremental_prev_tag::idx, G4LevelManager::LevelEnergy(), max, G4LevelManager::NearestLevelIndex(), G4LevelManager::NumberOfTransitions(), and T.
G4NuclearLevelData * G4NuclearLevelData::GetInstance (void) static
Definition at line 421 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 421 of file G4NuclearLevelData.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and theInstance.
Referenced by BiasedRDPhysics::BiasedRDPhysics(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4GNASHTransitions::CalculateProbability(), LBE::ConstructGeneral(), DMXPhysicsList::DMXPhysicsList(), G4CompetitiveFission::G4CompetitiveFission(), G4Evaporation::G4Evaporation(), G4EvaporationChannel::G4EvaporationChannel(), G4EvaporationLevelDensityParameter::G4EvaporationLevelDensityParameter(), G4FermiFragmentsPoolVI::G4FermiFragmentsPoolVI(), G4FissionBarrier::G4FissionBarrier(), G4FissionLevelDensityParameter::G4FissionLevelDensityParameter(), G4FissionLevelDensityParameterINCLXX::G4FissionLevelDensityParameterINCLXX(), G4FissionProbability::G4FissionProbability(), G4GEMChannel::G4GEMChannel(), G4GEMChannelVI::G4GEMChannelVI(), G4GEMProbability::G4GEMProbability(), G4GNASHTransitions::G4GNASHTransitions(), G4IonINCLXXPhysics::G4IonINCLXXPhysics(), G4IonPhysicsPHP::G4IonPhysicsPHP(), G4IonPhysicsXS::G4IonPhysicsXS(), G4IonQMDPhysics::G4IonQMDPhysics(), G4LevelManager::G4LevelManager(), G4PhotonEvaporation::G4PhotonEvaporation(), G4PreCompoundEmission::G4PreCompoundEmission(), G4PreCompoundModel::G4PreCompoundModel(), G4PreCompoundTransitions::G4PreCompoundTransitions(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), G4UnstableFragmentBreakUp::G4UnstableFragmentBreakUp(), G4VEmissionProbability::G4VEmissionProbability(), G4VPreCompoundFragment::G4VPreCompoundFragment(), G4ExcitationHandler::Initialise(), G4FermiFragmentsPoolVI::Initialise(), G4NeutronRadCapture::InitialiseModel(), G4RadioactiveDecayBaseMessenger::SetNewValue(), G4RadioactiveDecaymessenger::SetNewValue(), G4ExcitationHandler::SetParameters(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4double G4NuclearLevelData::GetLevelDensity (G4int Z, G4int A, G4double U)
Definition at line 634 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 634 of file G4NuclearLevelData.cc
References fDeexPrecoParameters, fG4calc, G4DeexPrecoParameters::GetLevelDensity(), G4DeexPrecoParameters::GetLevelDensityFlag(), GetLevelManager(), G4LevelManager::LevelDensity(), and G4Pow::Z13().
Referenced by G4PreCompoundEmission::AngularDistribution(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4GEMProbabilityVI::ComputeProbability(), G4EvaporationProbability::ComputeProbability(), G4GEMProbabilityVI::ComputeTotalProbability(), G4PreCompoundModel::DeExcite(), G4PhotonEvaporation::GetEmissionProbability(), G4HETCFragment::IntegrateEmissionProbability(), G4FissionLevelDensityParameter::LevelDensityParameter(), G4EvaporationLevelDensityParameter::LevelDensityParameter(), G4FissionLevelDensityParameterINCLXX::LevelDensityParameter(), G4PreCompoundNucleon::ProbabilityDistributionFunction(), G4PreCompoundIon::ProbabilityDistributionFunction(), G4HETCChargedFragment::SampleKineticEnergy(), G4HETCNeutron::SampleKineticEnergy(), and G4EvaporationProbability::TotalProbability().
G4double G4NuclearLevelData::GetLevelEnergy (G4int Z, G4int A, G4double energy)
Definition at line 566 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 566 of file G4NuclearLevelData.cc
References e, energy, GetLevelManager(), GetMaxLevelEnergy(), G4LevelManager::NearestLevelEnergy(), and G4LevelManager::NumberOfTransitions().
const G4LevelManager * G4NuclearLevelData::GetLevelManager (G4int Z, G4int A)
Definition at line 467 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 467 of file G4NuclearLevelData.cc
References AMAX, AMIN, G4LevelReader::CreateLevelManager(), fLevelManagerFlags, fLevelManagers, fLevelReader, G4MUTEXLOCK, G4MUTEXUNLOCK, incremental_prev_tag::idx, Z, and ZMAX.
Referenced by G4Evaporation::BreakFragment(), G4UnstableFragmentBreakUp::BreakUpChain(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), FindLevel(), G4VEmissionProbability::FindRecoilExcitation(), G4GEMChannelVI::G4GEMChannelVI(), GetLevelDensity(), GetLevelEnergy(), GetLowEdgeLevelEnergy(), G4FermiFragmentsPoolVI::Initialise(), G4PhotonEvaporation::InitialiseLevelManager(), and StreamLevels().
G4double G4NuclearLevelData::GetLowEdgeLevelEnergy (G4int Z, G4int A, G4double energy)
Definition at line 579 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 579 of file G4NuclearLevelData.cc
References e, GetLevelManager(), GetMaxLevelEnergy(), and G4LevelManager::NearestLowEdgeLevelEnergy().
G4int G4NuclearLevelData::GetMaxA (G4int Z) const
Definition at line 524 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 524 of file G4NuclearLevelData.cc
References AMAX, Z, and ZMAX.
Referenced by G4FermiFragmentsPoolVI::Initialise().
G4double G4NuclearLevelData::GetMaxLevelEnergy (G4int Z, G4int A) const
Definition at line 554 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 554 of file G4NuclearLevelData.cc
References AMAX, AMIN, LEVELIDX, and LEVELMAX.
Referenced by FindLevel(), GetLevelEnergy(), and GetLowEdgeLevelEnergy().
G4int G4NuclearLevelData::GetMinA (G4int Z) const
Definition at line 519 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 519 of file G4NuclearLevelData.cc
References AMIN, Z, and ZMAX.
Referenced by G4FermiFragmentsPoolVI::Initialise().
G4PairingCorrection * G4NuclearLevelData::GetPairingCorrection ()
Definition at line 624 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 624 of file G4NuclearLevelData.cc
References fPairingCorrection.
Referenced by G4GEMProbability::CalcProbability(), G4GEMProbabilityVI::ComputeTotalProbability(), G4CompetitiveFission::G4CompetitiveFission(), G4FissionProbability::G4FissionProbability(), G4GEMChannelVI::G4GEMChannelVI(), G4GEMProbability::GetCoulombBarrier(), G4EvaporationChannel::GetEmissionProbability(), G4GEMChannel::GetEmissionProbability(), G4GEMChannel::SampleKineticEnergy(), and G4EvaporationProbability::TotalProbability().
G4double G4NuclearLevelData::GetPairingCorrection (G4int Z, G4int A)
Definition at line 644 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 644 of file G4NuclearLevelData.cc
References A(), fDeexPrecoParameters, fPairingCorrection, G4DeexPrecoParameters::GetLevelDensityFlag(), G4PairingCorrection::GetPairingCorrection(), CLHEP::MeV, N, x, and Z.
G4DeexPrecoParameters * G4NuclearLevelData::GetParameters ()
Definition at line 619 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 619 of file G4NuclearLevelData.cc
References fDeexPrecoParameters.
Referenced by BiasedRDPhysics::BiasedRDPhysics(), LBE::ConstructGeneral(), DMXPhysicsList::DMXPhysicsList(), G4FermiFragmentsPoolVI::G4FermiFragmentsPoolVI(), G4GNASHTransitions::G4GNASHTransitions(), G4IonINCLXXPhysics::G4IonINCLXXPhysics(), G4IonPhysicsPHP::G4IonPhysicsPHP(), G4IonPhysicsXS::G4IonPhysicsXS(), G4IonQMDPhysics::G4IonQMDPhysics(), G4LevelReader::G4LevelReader(), G4PreCompoundEmission::G4PreCompoundEmission(), G4PreCompoundTransitions::G4PreCompoundTransitions(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), G4VPreCompoundFragment::G4VPreCompoundFragment(), G4VEmissionProbability::Initialise(), G4PhotonEvaporation::Initialise(), G4ExcitationHandler::Initialise(), G4Evaporation::InitialiseChannels(), G4NeutronRadCapture::InitialiseModel(), G4PreCompoundModel::InitialiseModel(), G4ExcitationHandler::SetParameters(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4ShellCorrection * G4NuclearLevelData::GetShellCorrection ()
Definition at line 629 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 629 of file G4NuclearLevelData.cc
References fShellCorrection.
Referenced by G4FissionBarrier::G4FissionBarrier(), and G4LevelManager::G4LevelManager().
G4float G4NuclearLevelData::MaxLevelEnergy (G4int Z, G4int A) const
Definition at line 560 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 560 of file G4NuclearLevelData.cc
References AMAX, AMIN, f, LEVELIDX, LEVELMAX, and Z.
Referenced by G4FermiFragmentsPoolVI::Initialise().
G4NuclearLevelData& G4NuclearLevelData::operator= (const G4NuclearLevelData & right) delete
void G4NuclearLevelData::StreamLevels (std::ostream & os, G4int Z, G4int A)
Definition at line 655 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 655 of file G4NuclearLevelData.cc
References GetLevelManager(), G4LevelManager::NumberOfTransitions(), and G4LevelManager::StreamInfo().
void G4NuclearLevelData::UploadNuclearLevelData (G4int Z)
Definition at line 529 of file G4NuclearLevelData.cc.
View newest version in sPHENIX GitHub at line 529 of file G4NuclearLevelData.cc
References A(), AMAX, AMIN, G4LevelReader::CreateLevelManager(), fInitialized, fLevelManagerFlags, fLevelManagers, fLevelReader, G4MUTEXLOCK, G4MUTEXUNLOCK, incremental_prev_tag::idx, Z, and ZMAX.
Referenced by G4ExcitationHandler::SetParameters().
Member Data Documentation
const G4int G4NuclearLevelData::AMAX static private
Initial value:
= {1,
    6,10,11,14,17,22,24,26,30,30,
   37,40,42,44,46,48,51,53,56,58,
   61,63,66,68,71,74,76,79,82,85,
   87,90,92,95,98,101,103,107,109,112,
  114,117,120,124,126,128,129,133,135,138,
  140,143,145,148,151,152,153,155,155,161,
  163,165,167,169,171,173,175,177,179,181,
  184,189,192,194,198,202,204,205,210,216,
  217,220,224,227,229,229,233,234,235,238,
  239,242,244,247,248,252,253,256,257,259,
  260,262,266,265,270,269,274,277,278,277,
  282,281,286,0,290,0,294}
Definition at line 129 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 129 of file G4NuclearLevelData.hh
Referenced by AddPrivateData(), G4NuclearLevelData(), GetLevelManager(), GetMaxA(), GetMaxLevelEnergy(), MaxLevelEnergy(), and UploadNuclearLevelData().
const G4int G4NuclearLevelData::AMIN static private
Initial value:
= {1,
    1,3,4,5,7,8,10,12,14,16,
   20,19,21,22,25,27,29,31,35,35,
   39,39,42,42,44,45,50,48,53,54,
   60,60,63,64,69,69,73,73,76,78,
   81,83,85,88,90,91,93,96,98,100,
  104,105,108,109,112,114,117,121,121,125,
  128,129,130,134,135,139,140,143,144,149,
  150,153,155,158,159,161,164,166,170,171,
  176,178,184,186,191,193,199,201,206,208,
  212,217,225,228,230,233,234,237,241,241,
  245,248,252,253,255,258,260,263,266,269,
  272,277,282,0,289,0,293}
Definition at line 128 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 128 of file G4NuclearLevelData.hh
Referenced by AddPrivateData(), G4NuclearLevelData(), GetLevelManager(), GetMaxLevelEnergy(), GetMinA(), MaxLevelEnergy(), and UploadNuclearLevelData().
G4DeexPrecoParameters* G4NuclearLevelData::fDeexPrecoParameters private
Definition at line 120 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 120 of file G4NuclearLevelData.hh
Referenced by G4NuclearLevelData(), GetLevelDensity(), GetPairingCorrection(), GetParameters(), and ~G4NuclearLevelData().
G4Pow* G4NuclearLevelData::fG4calc private
Definition at line 124 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 124 of file G4NuclearLevelData.hh
Referenced by G4NuclearLevelData(), and GetLevelDensity().
G4bool G4NuclearLevelData::fInitialized private
Definition at line 125 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 125 of file G4NuclearLevelData.hh
Referenced by G4NuclearLevelData(), and UploadNuclearLevelData().
std::vector<G4bool> G4NuclearLevelData::fLevelManagerFlags[ZMAX] private
Definition at line 133 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 133 of file G4NuclearLevelData.hh
Referenced by AddPrivateData(), G4NuclearLevelData(), GetLevelManager(), and UploadNuclearLevelData().
std::vector<const G4LevelManager*> G4NuclearLevelData::fLevelManagers[ZMAX] private
Definition at line 132 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 132 of file G4NuclearLevelData.hh
Referenced by AddPrivateData(), G4NuclearLevelData(), GetLevelManager(), UploadNuclearLevelData(), and ~G4NuclearLevelData().
G4LevelReader* G4NuclearLevelData::fLevelReader private
Definition at line 121 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 121 of file G4NuclearLevelData.hh
Referenced by AddPrivateData(), G4NuclearLevelData(), GetLevelManager(), UploadNuclearLevelData(), and ~G4NuclearLevelData().
G4PairingCorrection* G4NuclearLevelData::fPairingCorrection private
Definition at line 122 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 122 of file G4NuclearLevelData.hh
Referenced by G4NuclearLevelData(), GetPairingCorrection(), and ~G4NuclearLevelData().
G4ShellCorrection* G4NuclearLevelData::fShellCorrection private
Definition at line 123 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 123 of file G4NuclearLevelData.hh
Referenced by G4NuclearLevelData(), GetShellCorrection(), and ~G4NuclearLevelData().
const G4int G4NuclearLevelData::LEVELIDX static private
Initial value:
= {0,
     0,      6,     14,     22,     32,     43,     58,     73,     88,    105,
   120,    138,    160,    182,    205,    227,    249,    272,    295,    317,
   341,    364,    389,    414,    441,    469,    499,    526,    558,    588,
   620,    648,    679,    709,    741,    771,    804,    835,    870,    904,
   939,    973,   1008,   1044,   1081,   1118,   1156,   1193,   1231,   1269,
  1308,   1345,   1384,   1422,   1462,   1502,   1541,   1578,   1613,   1648,
  1685,   1721,   1758,   1796,   1832,   1869,   1904,   1940,   1975,   2011,
  2044,   2079,   2116,   2154,   2191,   2231,   2273,   2314,   2354,   2395,
  2441,   2483,   2526,   2567,   2609,   2648,   2685,   2720,   2754,   2784,
  2815,   2843,   2869,   2889,   2909,   2928,   2948,   2968,   2988,   3005,
  3024,   3040,   3055,   3070,   3083,   3099,   3111,   3126,   3141,   3154,
  3163,   3174,   3179,   3184,   3184,   3186,   3186}
Definition at line 130 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 130 of file G4NuclearLevelData.hh
Referenced by GetMaxLevelEnergy(), and MaxLevelEnergy().
G4NuclearLevelData * G4NuclearLevelData::theInstance = nullptr static private
Definition at line 66 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 66 of file G4NuclearLevelData.hh
Referenced by GetInstance().
const G4int G4NuclearLevelData::ZMAX = 118 static private
Definition at line 127 of file G4NuclearLevelData.hh.
View newest version in sPHENIX GitHub at line 127 of file G4NuclearLevelData.hh
Referenced by G4NuclearLevelData(), GetLevelManager(), GetMaxA(), GetMinA(), UploadNuclearLevelData(), and ~G4NuclearLevelData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4NuclearLevelData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/src/G4NuclearLevelData.cc