ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/readHits.C File Reference
readHits.C File Reference
#include "TROOT.h"
#include "TFile.h"
#include "TSystem.h"
#include "TKey.h"
#include "include/ExP01TrackerHit.hh"
Functions
void hits ()
Function Documentation
void hits ()
Definition at line 15 of file readHits.C.
View newest version in sPHENIX GitHub at line 15 of file readHits.C
Referenced by TrackEvaluation::add_truth_information(), TrackEvaluation::add_truth_information_micromegas(), G4GMocrenFileSceneHandler::AddCompound(), G4VSceneHandler::AddCompound(), CylindricalHough::addHits(), SvtxClusterEval::all_clusters_from(), SvtxHitEval::all_hits_from(), SvtxTrackEval::all_tracks_from(), SvtxHitEval::best_hit_from(), BOOST_DATA_TEST_CASE(), kdfinder::CircleFit< T >::CircleFitByChernovHoussam(), kdfinder::CircleFit< T >::CircleFitByHyper(), kdfinder::CircleFit< T >::CircleFitByPratt(), kdfinder::CircleFit< T >::CircleFitByTaubin(), PHHoughSeeding::CleanupSeeds(), Acts::TrackingVolume::compatibleSurfacesFromHierarchy(), oncsSub_idfnalmwpc::dump(), oncsSub_idfnalmwpcv2::dump(), LXeRun::EndOfRun(), QAG4SimulationMicromegas::evaluate_clusters(), FW::TruthTrackFinder::execute(), FW::HitSmearing::execute(), FW::DigitizationAlgorithm::execute(), FW::FatrasAlgorithm< simulator_t >::execute(), kdfinder::export_candidates_json(), kdfinder::export_json(), B0TrackFastSimEval::fill_track_tree(), PHG4TrackFastSimEval::fill_track_tree(), TrackFastSimEval::fill_track_tree(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), sPHENIXTracker::finalize(), sPHENIXSeedFinder::finalize(), kdfinder::find_tracks(), kdfinder::find_tracks_iterative(), HelixHough::findHelices(), HelixHough::findSeededHelices_run(), SvtxClusterEval::get_energy_contribution(), G4HitTTree::Init(), B0TrackFastSimEval::InitRun(), PHG4TrackFastSimEval::InitRun(), sPHENIXTrackerTpc::initSplitting(), sPHENIXTracker::initSplitting(), sPHENIXSeedFinder::initSplitting(), Acts::TrackingVolume::intersectSearchHierarchy(), oncsSub_idfnalmwpc::iValue(), oncsSub_idfnalmwpcv2::iValue(), main(), kdfinder::make_triplets(), SvtxHitEval::max_truth_hit_by_energy(), SvtxClusterEval::max_truth_hit_by_energy(), kdfinder::TrackCandidate< T >::mergeCandidate(), G4HitTTree::process_event(), CreateCZHitContainer::process_event(), PHG4DstCompressReco::process_event(), G4EdepNtuple::process_event(), EICG4RPHitTree::process_event(), EICG4ZDCHitTree::process_event(), EICG4ZDCNtuple::process_event(), G4SnglNtuple::process_event(), G4SnglTree::process_event(), SimpleNtuple::process_event(), G4HitNtuple::process_event(), G4DIRCTree::process_event(), TPCDataStreamEmulator::process_event(), PHG4DSTReader::process_event(), TpcRS::process_event(), CaloAna::process_g4hits(), FarForwardEvaluator::process_g4hits_B0(), FarForwardEvaluator::process_g4hits_RomanPots(), FarForwardEvaluator::process_g4hits_ZDC(), CellularAutomaton_v1::process_single_track(), CellularAutomaton_v1::process_single_triplet(), PHG4TruthEventAction::ProcessShowers(), PHTpcTrackFollower::propagateTrack(), FW::CsvPlanarClusterReader::read(), FW::Options::readFatrasConfig(), kdfinder::CircleFit< T >::RegularFit(), kdfinder::LinearFit< T >::RegularFit(), kdfinder::CircleFit< T >::RobustFit(), kdfinder::LinearFit< T >::RobustFit(), kdfinder::LinearFit< T >::rofunc(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::shift_coordinate_system(), PHHoughSeeding::shift_coordinate_system(), ActsFatras::Simulator< charged_selector_t, charged_simulator_t, neutral_selector_t, neutral_simulator_t >::simulate(), kdfinder::TrackCandidate< T >::TrackCandidate(), sPHENIXTrackerTpc::tripletRejection(), sPHENIXTracker::tripletRejection(), sPHENIXSeedFinder::tripletRejection(), and FW::TrackFinderPerformanceWriter::Impl::write().