ECCE @ EIC Software: G4InteractionCase Class Reference
G4InteractionCase Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InteractionCase.hh>
Public Member Functions
G4InteractionCase ()
G4InteractionCase (G4InuclParticle *part1, G4InuclParticle *part2)
void set (G4InuclParticle *part1, G4InuclParticle *part2)
void clear ()
G4InuclParticle * getBullet () const
G4InuclParticle * getTarget () const
G4bool valid () const
G4bool twoNuclei () const
G4bool hadNucleus () const
G4int hadrons () const
G4int code () const
Private Attributes
G4InuclParticle * bullet
G4InuclParticle * target
G4int inter_case
Detailed Description
Definition at line 39 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 39 of file G4InteractionCase.hh
Constructor & Destructor Documentation
G4InteractionCase::G4InteractionCase () inline
Definition at line 41 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 41 of file G4InteractionCase.hh
G4InteractionCase::G4InteractionCase (G4InuclParticle * part1, G4InuclParticle * part2) inline
Definition at line 43 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 43 of file G4InteractionCase.hh
Member Function Documentation
void G4InteractionCase::clear (void) inline
Definition at line 49 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 49 of file G4InteractionCase.hh
References bullet, and inter_case.
Referenced by set().
G4int G4InteractionCase::code () const inline
Definition at line 64 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 64 of file G4InteractionCase.hh
References inter_case.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::newCascade().
G4InuclParticle* G4InteractionCase::getBullet () const inline
Definition at line 54 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 54 of file G4InteractionCase.hh
References bullet.
Referenced by G4InuclCollider::collide(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4IntraNucleiCascader::initialize(), and G4InuclCollider::photonuclearOkay().
G4InuclParticle* G4InteractionCase::getTarget () const inline
Definition at line 55 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 55 of file G4InteractionCase.hh
References target.
Referenced by G4InuclCollider::collide(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4IntraNucleiCascader::initialize(), and G4InuclCollider::photonuclearOkay().
G4bool G4InteractionCase::hadNucleus () const inline
Definition at line 60 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 60 of file G4InteractionCase.hh
References inter_case.
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::setupCascade().
G4int G4InteractionCase::hadrons () const inline
Definition at line 61 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 61 of file G4InteractionCase.hh
References inter_case.
Referenced by G4ElementaryParticleCollider::collide(), and G4ElementaryParticleCollider::pionNucleonAbsorption().
void G4InteractionCase::set (G4InuclParticle * part1, G4InuclParticle * part2)
Definition at line 38 of file G4InteractionCase.cc.
View newest version in sPHENIX GitHub at line 38 of file G4InteractionCase.cc
References bullet, clear(), G4InuclNuclei::getA(), inter_case, and G4InuclElementaryParticle::type().
Referenced by G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), and G4IntraNucleiCascader::initialize().
G4bool G4InteractionCase::twoNuclei () const inline
Definition at line 59 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 59 of file G4InteractionCase.hh
References inter_case.
Referenced by G4InuclCollider::photonuclearOkay().
G4bool G4InteractionCase::valid () const inline
Definition at line 57 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 57 of file G4InteractionCase.hh
References inter_case.
Referenced by G4InuclCollider::collide().
Member Data Documentation
G4InuclParticle* G4InteractionCase::bullet private
Definition at line 67 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 67 of file G4InteractionCase.hh
Referenced by clear(), getBullet(), and set().
G4int G4InteractionCase::inter_case private
Definition at line 70 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 70 of file G4InteractionCase.hh
Referenced by clear(), code(), hadNucleus(), hadrons(), set(), twoNuclei(), and valid().
G4InuclParticle* G4InteractionCase::target private
Definition at line 68 of file G4InteractionCase.hh.
View newest version in sPHENIX GitHub at line 68 of file G4InteractionCase.hh
Referenced by getTarget().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InteractionCase.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InteractionCase.cc