ECCE @ EIC Software: G4VisCommandSceneAddEventID Class Reference
G4VisCommandSceneAddEventID Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh>
Classes
struct EventID
Public Member Functions
G4VisCommandSceneAddEventID ()
virtual ~G4VisCommandSceneAddEventID ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommandScene
G4VVisCommandScene ()
virtual ~G4VVisCommandScene ()
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Types
enum ForWhat { forEndOfEvent, forEndOfRun }
Private Member Functions
G4VisCommandSceneAddEventID (const G4VisCommandSceneAddEventID &)
G4VisCommandSceneAddEventID & operator= (const G4VisCommandSceneAddEventID &)
Private Attributes
G4UIcommand * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommandScene
G4String CurrentSceneName ()
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 131 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 131 of file G4VisCommandsSceneAdd.hh
Member Enumeration Documentation
enum G4VisCommandSceneAddEventID::ForWhat private
Enumerator:
forEndOfEvent
forEndOfRun
Definition at line 140 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VisCommandsSceneAdd.hh
Constructor & Destructor Documentation
G4VisCommandSceneAddEventID::G4VisCommandSceneAddEventID ()
Definition at line 626 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 626 of file G4VisCommandsSceneAdd.cc
References fpCommand.
G4VisCommandSceneAddEventID::~G4VisCommandSceneAddEventID () virtual
Definition at line 652 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 652 of file G4VisCommandsSceneAdd.cc
References fpCommand.
G4VisCommandSceneAddEventID::G4VisCommandSceneAddEventID (const G4VisCommandSceneAddEventID &) private
Member Function Documentation
G4String G4VisCommandSceneAddEventID::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 656 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 656 of file G4VisCommandsSceneAdd.cc
G4VisCommandSceneAddEventID& G4VisCommandSceneAddEventID::operator= (const G4VisCommandSceneAddEventID &) private
void G4VisCommandSceneAddEventID::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 660 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 660 of file G4VisCommandsSceneAdd.cc
References G4Text::centre, G4VVisCommand::CheckSceneAndNotifyHandlers(), G4VisManager::confirmations, G4VisManager::errors, forEndOfEvent, forEndOfRun, G4VVisCommand::fpVisManager, G4cerr, G4cout, G4endl, G4VVisCommand::G4VisCommandsSceneAddUnsuccessful(), G4VisManager::GetCurrentScene(), G4VisManager::GetVerbosity(), G4Text::left, G4Text::right, G4VModel::SetGlobalDescription(), G4VModel::SetGlobalTag(), G4VModel::SetType(), G4VisManager::warnings, x, and y.
Member Data Documentation
G4UIcommand* G4VisCommandSceneAddEventID::fpCommand private
Definition at line 153 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 153 of file G4VisCommandsSceneAdd.hh
Referenced by G4VisCommandSceneAddEventID(), and ~G4VisCommandSceneAddEventID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSceneAdd.cc