ECCE @ EIC Software: G4VDiscreteProcess Class Reference
G4VDiscreteProcess Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4VDiscreteProcess.hh>
Inherits G4VProcess.
Inherited by F04StepMax, G4AnnihiToMuPair, G4Channeling, G4ElectronCapture, G4ElectronCapture, G4ElectronCapture, G4ElectronCapture, G4ErrorTrackLengthTarget, G4GammaConversionToMuons, G4HadronicProcess, G4LowECapture, G4LowEnergyCompton, G4LowEnergyGammaConversion, G4LowEnergyPhotoElectric, G4LowEnergyPolarizedCompton, G4LowEnergyRayleigh, G4NeutronKiller, G4OpAbsorption, G4OpBoundaryProcess, G4OpMieHG, G4OpRayleigh, G4OpWLS, G4ScreenedNuclearRecoil, G4SynchrotronRadiation, G4SynchrotronRadiationInMat, G4TransitionRadiation, G4UCNAbsorption, G4UCNBoundaryProcess, G4UCNLoss, G4UCNMultiScattering, G4UnknownDecay, G4VAdjointReverseReaction, G4VEmProcess, G4VErrorLimitProcess, G4VPhononProcess, G4VTransitionRadiation, G4VXTRenergyLoss, HadrontherapyStepMax, IORTStepMax, ML2StepMax, StepLimiter, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMaxProcess, XrayFluoStepMax, and XrayTelStepCut.
Public Member Functions
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)=0
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Member Functions
G4VDiscreteProcess ()
G4VDiscreteProcess & operator= (const G4VDiscreteProcess &right)
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 57 of file G4VDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VDiscreteProcess.hh
Constructor & Destructor Documentation
G4VDiscreteProcess::G4VDiscreteProcess (const G4String & aName, G4ProcessType aType = fNotDefined)
Definition at line 53 of file G4VDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VDiscreteProcess.cc
References G4VProcess::enableAlongStepDoIt, and G4VProcess::enableAtRestDoIt.
G4VDiscreteProcess::G4VDiscreteProcess (G4VDiscreteProcess & right)
Definition at line 65 of file G4VDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VDiscreteProcess.cc
G4VDiscreteProcess::~G4VDiscreteProcess () virtual
Definition at line 61 of file G4VDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VDiscreteProcess.cc
G4VDiscreteProcess::G4VDiscreteProcess () private
Definition at line 46 of file G4VDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VDiscreteProcess.cc
References G4Exception(), and JustWarning.
Member Function Documentation
virtual G4VParticleChange* G4VDiscreteProcess::AlongStepDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Reimplemented in G4NuclearStopping.
Definition at line 101 of file G4VDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VDiscreteProcess.hh
virtual G4double G4VDiscreteProcess::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double , G4double , G4double & , G4GPILSelection *) inline virtual
Implements G4VProcess.
Reimplemented in G4NuclearStopping.
Definition at line 82 of file G4VDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VDiscreteProcess.hh
virtual G4VParticleChange* G4VDiscreteProcess::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Reimplemented in G4HadronStoppingProcess, and G4eplusAnnihilation.
Definition at line 96 of file G4VDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 96 of file G4VDiscreteProcess.hh
virtual G4double G4VDiscreteProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Reimplemented in G4eplusAnnihilation, and G4HadronStoppingProcess.
Definition at line 90 of file G4VDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VDiscreteProcess.hh
virtual G4double G4VDiscreteProcess::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) protected pure virtual
Implemented in G4VEmProcess, G4ScreenedNuclearRecoil, G4OpBoundaryProcess, G4GammaGeneralProcess, G4HadronicProcess, G4UCNBoundaryProcess, G4UnknownDecay, G4PolarizedCompton, G4UCNAbsorption, G4UCNLoss, G4UCNMultiScattering, G4LowEnergyPhotoElectric, G4LowEnergyPolarizedCompton, G4VXTRenergyLoss, G4VAdjointReverseReaction, G4AnnihiToMuPair, G4ElectronCapture, G4GammaConversionToMuons, G4ElectronCapture, G4ElectronCapture, G4NeutronKiller, G4OpWLS, XrayTelStepCut, G4SynchrotronRadiationInMat, G4OpRayleigh, G4LowECapture, G4ForwardXrayTR, G4LowEnergyGammaConversion, G4ElectronCapture, G4OpAbsorption, G4LowEnergyCompton, G4LowEnergyRayleigh, G4eplusPolarizedAnnihilation, G4SynchrotronRadiation, G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, ML2StepMax, IORTStepMax, G4TransitionRadiation, StepMax, F04StepMax, G4VTransitionRadiation, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMaxProcess, StepMax, StepMax, G4OpMieHG, StepMax, StepMax, StepLimiter, StepMax, StepMax, XrayFluoStepMax, StepMax, HadrontherapyStepMax, G4Channeling, G4PhononDownconversion, G4PhononReflection, and G4PhononScattering.
Referenced by PostStepGetPhysicalInteractionLength().
G4VDiscreteProcess& G4VDiscreteProcess::operator= (const G4VDiscreteProcess & right) private
G4VParticleChange * G4VDiscreteProcess::PostStepDoIt (const G4Track & , const G4Step &) virtual
Implements G4VProcess.
Reimplemented in G4ScreenedNuclearRecoil, G4OpBoundaryProcess, G4VEmProcess, G4UCNBoundaryProcess, G4GammaGeneralProcess, G4GammaConversionToMuons, G4UCNAbsorption, G4UCNLoss, G4UCNMultiScattering, G4AnnihiToMuPair, G4HadronicProcess, G4OpWLS, G4VXTRenergyLoss, G4OpRayleigh, G4SynchrotronRadiationInMat, G4ForwardXrayTR, G4OpAbsorption, G4ElectronCapture, G4VAdjointReverseReaction, G4NeutronKiller, G4ElectronCapture, G4ElectronCapture, G4LowEnergyPolarizedCompton, G4LowECapture, G4ElectronCapture, G4ErrorTrackLengthTarget, G4SynchrotronRadiation, XrayTelStepCut, G4LowEnergyPhotoElectric, G4VErrorLimitProcess, G4LowEnergyGammaConversion, G4TransitionRadiation, G4LowEnergyCompton, G4VTransitionRadiation, CexmcHadronicProcess, G4LowEnergyRayleigh, ML2StepMax, G4OpMieHG, G4UnknownDecay, IORTStepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, F04StepMax, StepMaxProcess, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepLimiter, G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, StepMax, StepMax, StepMax, StepMax, XrayFluoStepMax, G4HadronElasticProcess, StepMax, HadrontherapyStepMax, G4Channeling, G4PhononReflection, G4PhononDownconversion, G4PhononScattering, G4EicDircOpBoundaryProcess, and PrtOpBoundaryProcess.
Definition at line 111 of file G4VDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 111 of file G4VDiscreteProcess.cc
References G4VProcess::ClearNumberOfInteractionLengthLeft(), and G4VProcess::pParticleChange.
Referenced by G4PhononScattering::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4UCNLoss::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), and G4ScreenedNuclearRecoil::PostStepDoIt().
G4double G4VDiscreteProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Reimplemented in G4VEmProcess, G4GammaGeneralProcess, G4PolarizedCompton, G4UnknownDecay, G4ElectronCapture, G4NeutronKiller, G4ElectronCapture, G4ElectronCapture, G4HadronStoppingProcess, G4eplusPolarizedAnnihilation, G4LowECapture, G4ElectronCapture, G4ErrorTrackLengthTarget, XrayTelStepCut, ML2StepMax, G4VErrorLimitProcess, G4ErrorStepLengthLimitProcess, G4ErrorMagFieldLimitProcess, IORTStepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, F04StepMax, StepMaxProcess, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepLimiter, StepMax, StepMax, StepMax, StepMax, XrayFluoStepMax, StepMax, and HadrontherapyStepMax.
Definition at line 70 of file G4VDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 70 of file G4VDiscreteProcess.cc
References cm, G4VProcess::currentInteractionLength, DBL_MAX, G4DynamicParticle::DumpInfo(), G4cout, G4endl, G4Track::GetDynamicParticle(), G4Track::GetMaterial(), GetMeanFreePath(), G4Material::GetName(), G4VProcess::GetProcessName(), NotForced, G4VProcess::ResetNumberOfInteractionLengthLeft(), G4VProcess::SubtractNumberOfInteractionLengthLeft(), G4VProcess::theNumberOfInteractionLengthLeft, and G4VProcess::verboseLevel.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4VDiscreteProcess.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4VDiscreteProcess.cc