ECCE @ EIC Software: G4ParticleChangeForTransport Class Reference
G4ParticleChangeForTransport Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForTransport.hh>
Public Member Functions
G4ParticleChangeForTransport ()
virtual ~G4ParticleChangeForTransport ()
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
virtual G4Step * UpdateStepForPostStep (G4Step *Step)
virtual void Initialize (const G4Track &)
const G4TouchableHandle & GetTouchableHandle () const
void SetTouchableHandle (const G4TouchableHandle &fTouchable)
G4Material * GetMaterialInTouchable () const
void SetMaterialInTouchable (G4Material *fMaterial)
const G4MaterialCutsCouple * GetMaterialCutsCoupleInTouchable () const
void SetMaterialCutsCoupleInTouchable (const G4MaterialCutsCouple *fMaterialCutsCouple)
G4VSensitiveDetector * GetSensitiveDetectorInTouchable () const
void SetSensitiveDetectorInTouchable (G4VSensitiveDetector *fSensitiveDetector)
G4bool GetMomentumChanged () const
void SetMomentumChanged (G4bool b)
virtual void DumpInfo () const
void SetPointerToVectorOfAuxiliaryPoints (std::vector< G4ThreeVector > *theNewVectorPointer)
std::vector< G4ThreeVector > * GetPointerToVectorOfAuxiliaryPoints () const
Public Member Functions inherited from G4ParticleChange
G4ParticleChange ()
virtual ~G4ParticleChange ()
G4bool operator== (const G4ParticleChange &right) const
G4bool operator!= (const G4ParticleChange &right) const
const G4ThreeVector * GetMomentumDirection () const
void ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
void ProposeMomentumDirection (const G4ThreeVector &Pfinal)
const G4ThreeVector * GetPolarization () const
void ProposePolarization (G4double Px, G4double Py, G4double Pz)
void ProposePolarization (const G4ThreeVector &finalPoralization)
G4double GetEnergy () const
void ProposeEnergy (G4double finalEnergy)
G4double GetVelocity () const
void ProposeVelocity (G4double finalVelocity)
G4double GetProperTime () const
void ProposeProperTime (G4double finalProperTime)
const G4ThreeVector * GetPosition () const
void ProposePosition (G4double x, G4double y, G4double z)
void ProposePosition (const G4ThreeVector &finalPosition)
void ProposeGlobalTime (G4double t)
void ProposeLocalTime (G4double t)
G4double GetGlobalTime (G4double timeDelay=0.0) const
G4double GetLocalTime (G4double timeDelay=0.0) const
G4double GetMass () const
void ProposeMass (G4double finalMass)
G4double GetCharge () const
void ProposeCharge (G4double finalCharge)
G4double GetMagneticMoment () const
void ProposeMagneticMoment (G4double finalMagneticMoment)
G4ThreeVector GetGlobalPosition (const G4ThreeVector &displacement) const
G4ThreeVector CalcMomentum (G4double energy, G4ThreeVector direction, G4double mass) const
void AddSecondary (G4Track *aSecondary)
void AddSecondary (G4DynamicParticle *aSecondary, G4bool IsGoodForTracking=false)
void AddSecondary (G4DynamicParticle *aSecondary, G4ThreeVector position, G4bool IsGoodForTracking=false)
void AddSecondary (G4DynamicParticle *aSecondary, G4double time, G4bool IsGoodForTracking=false)
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChangeForTransport (const G4ParticleChangeForTransport &right)
G4ParticleChangeForTransport & operator= (const G4ParticleChangeForTransport &right)
Protected Member Functions inherited from G4ParticleChange
G4ParticleChange (const G4ParticleChange &right)
G4ParticleChange & operator= (const G4ParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Protected Attributes
G4TouchableHandle theTouchableHandle
Protected Attributes inherited from G4ParticleChange
G4ThreeVector theMomentumDirectionChange
G4ThreeVector thePolarizationChange
G4double theEnergyChange
G4double theVelocityChange
G4bool isVelocityChanged
G4ThreeVector thePositionChange
G4double theGlobalTime0
G4double theLocalTime0
G4double theTimeChange
G4double theProperTimeChange
G4double theMassChange
G4double theChargeChange
G4double theMagneticMomentChange
const G4Track * theCurrentTrack
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Private Attributes
G4bool isMomentumChanged
G4Material * theMaterialChange
const G4MaterialCutsCouple * theMaterialCutsCoupleChange
G4VSensitiveDetector * theSensitiveDetectorChange
std::vector< G4ThreeVector > * fpVectorOfAuxiliaryPointsPointer
Additional Inherited Members
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 54 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleChangeForTransport.hh
Constructor & Destructor Documentation
G4ParticleChangeForTransport::G4ParticleChangeForTransport ()
Definition at line 47 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleChangeForTransport.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForTransport::~G4ParticleChangeForTransport () virtual
Definition at line 58 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleChangeForTransport.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForTransport::G4ParticleChangeForTransport (const G4ParticleChangeForTransport & right) protected
Definition at line 67 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ParticleChangeForTransport.cc
References G4cout, G4endl, isMomentumChanged, theMaterialChange, theMaterialCutsCoupleChange, theSensitiveDetectorChange, theTouchableHandle, and G4VParticleChange::verboseLevel.
Member Function Documentation
void G4ParticleChangeForTransport::DumpInfo () const virtual
Reimplemented from G4ParticleChange.
Definition at line 254 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 254 of file G4ParticleChangeForTransport.cc
References G4ParticleChange::DumpInfo(), G4cout, G4endl, and theTouchableHandle.
const G4MaterialCutsCouple* G4ParticleChangeForTransport::GetMaterialCutsCoupleInTouchable () const
G4Material* G4ParticleChangeForTransport::GetMaterialInTouchable () const
G4bool G4ParticleChangeForTransport::GetMomentumChanged () const
std::vector<G4ThreeVector>* G4ParticleChangeForTransport::GetPointerToVectorOfAuxiliaryPoints () const inline
G4VSensitiveDetector* G4ParticleChangeForTransport::GetSensitiveDetectorInTouchable () const
const G4TouchableHandle& G4ParticleChangeForTransport::GetTouchableHandle () const
virtual void G4ParticleChangeForTransport::Initialize (const G4Track &) virtual
Reimplemented from G4ParticleChange.
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), and G4ITTransportation::PostStepDoIt().
G4ParticleChangeForTransport & G4ParticleChangeForTransport::operator= (const G4ParticleChangeForTransport & right) protected
Definition at line 84 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleChangeForTransport.cc
References G4cout, G4endl, G4ParticleChange::theEnergyChange, G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, theMaterialChange, theMaterialCutsCoupleChange, G4ParticleChange::theMomentumDirectionChange, G4VParticleChange::theNumberOfSecondaries, G4ParticleChange::thePolarizationChange, G4ParticleChange::thePositionChange, theSensitiveDetectorChange, G4VParticleChange::theSizeOftheListOfSecondaries, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, G4ParticleChange::theTimeChange, theTouchableHandle, G4VParticleChange::theTrueStepLength, G4ParticleChange::theVelocityChange, and G4VParticleChange::verboseLevel.
void G4ParticleChangeForTransport::SetMaterialCutsCoupleInTouchable (const G4MaterialCutsCouple * fMaterialCutsCouple)
Referenced by G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), and G4ITTransportation::PostStepDoIt().
void G4ParticleChangeForTransport::SetMaterialInTouchable (G4Material * fMaterial)
Referenced by G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), and G4ITTransportation::PostStepDoIt().
void G4ParticleChangeForTransport::SetMomentumChanged (G4bool b)
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), and G4DNABrownianTransportation::Diffusion().
void G4ParticleChangeForTransport::SetPointerToVectorOfAuxiliaryPoints (std::vector< G4ThreeVector > * theNewVectorPointer) inline
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), and G4ITTransportation::AlongStepDoIt().
void G4ParticleChangeForTransport::SetSensitiveDetectorInTouchable (G4VSensitiveDetector * fSensitiveDetector)
Referenced by G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), and G4ITTransportation::PostStepDoIt().
void G4ParticleChangeForTransport::SetTouchableHandle (const G4TouchableHandle & fTouchable)
Referenced by G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), and G4ITTransportation::PostStepDoIt().
G4Step * G4ParticleChangeForTransport::UpdateStepForAlongStep (G4Step * Step) virtual
Reimplemented from G4ParticleChange.
Definition at line 130 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 130 of file G4ParticleChangeForTransport.cc
References G4StepPoint::AddGlobalTime(), G4StepPoint::AddLocalTime(), G4StepPoint::AddPolarization(), G4StepPoint::AddPosition(), G4StepPoint::AddProperTime(), G4ParticleChange::CalcMomentum(), G4ParticleChange::CheckIt(), G4VParticleChange::debugFlag, energy, fpVectorOfAuxiliaryPointsPointer, G4Track::GetDynamicParticle(), G4StepPoint::GetKineticEnergy(), G4StepPoint::GetLocalTime(), G4DynamicParticle::GetMass(), G4StepPoint::GetMomentum(), G4StepPoint::GetPolarization(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProperTime(), G4Step::GetTrack(), isMomentumChanged, G4ParticleChange::isVelocityChanged, CLHEP::Hep3Vector::mag(), mass, G4Step::SetControlFlag(), G4StepPoint::SetKineticEnergy(), G4StepPoint::SetMomentumDirection(), G4Step::SetPointerToVectorOfAuxiliaryPoints(), G4StepPoint::SetVelocity(), G4ParticleChange::theEnergyChange, G4ParticleChange::theMomentumDirectionChange, G4ParticleChange::thePolarizationChange, G4ParticleChange::thePositionChange, G4ParticleChange::theProperTimeChange, G4VParticleChange::theSteppingControlFlag, G4ParticleChange::theTimeChange, and G4ParticleChange::theVelocityChange.
G4Step * G4ParticleChangeForTransport::UpdateStepForAtRest (G4Step * Step) virtual
Reimplemented from G4ParticleChange.
Definition at line 117 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleChangeForTransport.cc
References G4cout, G4endl, G4ParticleChange::UpdateStepInfo(), and G4VParticleChange::verboseLevel.
G4Step * G4ParticleChangeForTransport::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4ParticleChange.
Definition at line 212 of file G4ParticleChangeForTransport.cc.
View newest version in sPHENIX GitHub at line 212 of file G4ParticleChangeForTransport.cc
References G4Step::ClearFirstStepFlag(), G4Step::ClearLastStepFlag(), G4VParticleChange::GetFirstStepInVolume(), G4StepPoint::GetKineticEnergy(), G4VParticleChange::GetLastStepInVolume(), G4Step::GetPostStepPoint(), G4Step::SetFirstStepFlag(), G4Step::SetLastStepFlag(), G4StepPoint::SetMaterial(), G4StepPoint::SetMaterialCutsCouple(), G4StepPoint::SetSensitiveDetector(), G4StepPoint::SetTouchableHandle(), theMaterialChange, theMaterialCutsCoupleChange, theSensitiveDetectorChange, and theTouchableHandle.
Member Data Documentation
std::vector<G4ThreeVector>* G4ParticleChangeForTransport::fpVectorOfAuxiliaryPointsPointer private
Definition at line 134 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ParticleChangeForTransport.hh
Referenced by UpdateStepForAlongStep().
G4bool G4ParticleChangeForTransport::isMomentumChanged private
Definition at line 125 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleChangeForTransport.hh
Referenced by G4ParticleChangeForTransport(), and UpdateStepForAlongStep().
G4Material* G4ParticleChangeForTransport::theMaterialChange private
Definition at line 127 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ParticleChangeForTransport.hh
Referenced by G4ParticleChangeForTransport(), operator=(), and UpdateStepForPostStep().
const G4MaterialCutsCouple* G4ParticleChangeForTransport::theMaterialCutsCoupleChange private
Definition at line 128 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleChangeForTransport.hh
Referenced by G4ParticleChangeForTransport(), operator=(), and UpdateStepForPostStep().
G4VSensitiveDetector* G4ParticleChangeForTransport::theSensitiveDetectorChange private
Definition at line 129 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ParticleChangeForTransport.hh
Referenced by G4ParticleChangeForTransport(), operator=(), and UpdateStepForPostStep().
G4TouchableHandle G4ParticleChangeForTransport::theTouchableHandle protected
Definition at line 113 of file G4ParticleChangeForTransport.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleChangeForTransport.hh
Referenced by DumpInfo(), G4ParticleChangeForTransport(), operator=(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForTransport.hh
geant4/tree/geant4-10.6-release/source/track/src/G4ParticleChangeForTransport.cc