ECCE @ EIC Software: ElectronRun Class Reference
ElectronRun Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/ElectronRun.hh>
Public Member Functions
ElectronRun ()
virtual ~ElectronRun ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
void DumpData (G4String &) const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Member Functions
void Print (const std::vector< G4String > &title, const std::map< G4int, std::vector< G4double > > &out, G4String &) const
Private Attributes
std::map< G4int, G4THitsMap
< G4double > * > fMap
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Definition at line 42 of file ElectronRun.hh.
View newest version in sPHENIX GitHub at line 42 of file ElectronRun.hh
Constructor & Destructor Documentation
ElectronRun::ElectronRun ()
Definition at line 39 of file ElectronRun.cc.
View newest version in sPHENIX GitHub at line 39 of file ElectronRun.cc
References fMap.
ElectronRun::~ElectronRun () virtual
Definition at line 50 of file ElectronRun.cc.
View newest version in sPHENIX GitHub at line 50 of file ElectronRun.cc
References fMap.
Member Function Documentation
void ElectronRun::DumpData (G4String & outputFileSpec) const
Definition at line 94 of file ElectronRun.cc.
View newest version in sPHENIX GitHub at line 94 of file ElectronRun.cc
References fMap, G4VTHitsMap< T, Map_t >::GetMap(), G4VHitsCollection::GetName(), Print(), and title().
Referenced by ElectronRunAction::EndOfRunAction().
void ElectronRun::Merge (const G4Run * aRun) virtual
Reimplemented from G4Run.
Definition at line 197 of file ElectronRun.cc.
View newest version in sPHENIX GitHub at line 197 of file ElectronRun.cc
References fMap, and G4Run::Merge().
void ElectronRun::Print (const std::vector< G4String > & title, const std::map< G4int, std::vector< G4double > > & out, G4String & outputFileSpec) const private
Definition at line 143 of file ElectronRun.cc.
View newest version in sPHENIX GitHub at line 143 of file ElectronRun.cc
References G4cout, G4endl, and mm.
Referenced by DumpData().
void ElectronRun::RecordEvent (const G4Event * anEvent) virtual
Reimplemented from G4Run.
Definition at line 63 of file ElectronRun.cc.
View newest version in sPHENIX GitHub at line 63 of file ElectronRun.cc
References fMap, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), and G4Run::RecordEvent().
Member Data Documentation
std::map<G4int, G4THitsMap<G4double>* > ElectronRun::fMap private
Definition at line 57 of file ElectronRun.hh.
View newest version in sPHENIX GitHub at line 57 of file ElectronRun.hh
Referenced by DumpData(), ElectronRun(), Merge(), RecordEvent(), and ~ElectronRun().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/ElectronRun.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/src/ElectronRun.cc