ECCE @ EIC Software: G4MuNeutrinoNucleusProcess Class Reference
G4MuNeutrinoNucleusProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4MuNeutrinoNucleusProcess.hh>
Public Member Functions
G4MuNeutrinoNucleusProcess (G4String anEnvelopeName, const G4String &procName="mu-neutrino-nucleus")
virtual ~G4MuNeutrinoNucleusProcess ()
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void SetLowestEnergy (G4double)
virtual void ProcessDescription (std::ostream &outFile) const
void SetBiasingFactors (G4double bfCc, G4double bfNc)
void SetBiasingFactor (G4double bf)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *)
Public Member Functions inherited from G4HadronicProcess
G4HadronicProcess (const G4String &processName="Hadronic", G4ProcessType procType=fHadronic)
G4HadronicProcess (const G4String &processName, G4HadronicProcessType subType)
~G4HadronicProcess () override
void RegisterMe (G4HadronicInteraction *a)
G4double GetElementCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4double GetMicroscopicCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
void BuildPhysicsTable (const G4ParticleDefinition &) override
void DumpPhysicsTable (const G4ParticleDefinition &p)
void AddDataSet (G4VCrossSectionDataSet *aDataSet)
std::vector
< G4HadronicInteraction * > & GetHadronicInteractionList ()
G4HadronicInteraction * GetHadronicModel (const G4String &)
const G4Nucleus * GetTargetNucleus () const
const G4Isotope * GetTargetIsotope ()
void BiasCrossSectionByFactor (G4double aScale)
void MultiplyCrossSectionBy (G4double factor)
G4double CrossSectionFactor () const
void SetIntegral (G4bool val)
void SetEpReportLevel (G4int level)
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
G4CrossSectionDataStore * GetCrossSectionDataStore ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4MuNeutrinoNucleusProcess & operator= (const G4MuNeutrinoNucleusProcess &right)
G4MuNeutrinoNucleusProcess (const G4MuNeutrinoNucleusProcess &)
Private Attributes
G4double lowestEnergy
G4bool isInitialised
G4bool fBiased
G4LogicalVolume * fEnvelope
G4String fEnvelopeName
G4MuNeutrinoNucleusTotXsc * fTotXsc
G4double fNuNuclCcBias
G4double fNuNuclNcBias
G4double fNuNuclTotXscBias
G4SafetyHelper * safetyHelper
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4HadronicProcess
G4HadronicInteraction * ChooseHadronicInteraction (const G4HadProjectile &aHadProjectile, G4Nucleus &aTargetNucleus, const G4Material *aMaterial, const G4Element *anElement)
G4Nucleus * GetTargetNucleusPointer ()
void DumpState (const G4Track &, const G4String &, G4ExceptionDescription &)
G4HadronicInteraction * GetHadronicInteraction () const
G4double GetLastCrossSection ()
void FillResult (G4HadFinalState *aR, const G4Track &aT)
G4HadFinalState * CheckResult (const G4HadProjectile &thePro, const G4Nucleus &targetNucleus, G4HadFinalState *result)
void CheckEnergyMomentumConservation (const G4Track &, const G4Nucleus &)
Protected Attributes inherited from G4HadronicProcess
G4HadProjectile thePro
G4ParticleChange * theTotalResult
G4double fWeight
G4int epReportLevel
Detailed Description
Definition at line 52 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 52 of file G4MuNeutrinoNucleusProcess.hh
Constructor & Destructor Documentation
G4MuNeutrinoNucleusProcess::G4MuNeutrinoNucleusProcess (G4String anEnvelopeName, const G4String & procName = "mu-neutrino-nucleus")
Definition at line 69 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 69 of file G4MuNeutrinoNucleusProcess.cc
References fEnvelope, fEnvelopeName, fNuNuclCcBias, fNuNuclNcBias, fNuNuclTotXscBias, fTotXsc, G4TransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), G4SafetyHelper::InitialiseHelper(), keV, lowestEnergy, and safetyHelper.
G4MuNeutrinoNucleusProcess::~G4MuNeutrinoNucleusProcess () virtual
Definition at line 84 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 84 of file G4MuNeutrinoNucleusProcess.cc
References fTotXsc.
G4MuNeutrinoNucleusProcess::G4MuNeutrinoNucleusProcess (const G4MuNeutrinoNucleusProcess &) private
Member Function Documentation
G4double G4MuNeutrinoNucleusProcess::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition *) virtual
Reimplemented from G4HadronicProcess.
Definition at line 113 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 113 of file G4MuNeutrinoNucleusProcess.cc
References G4CrossSectionDataStore::ComputeCrossSection(), DBL_MAX, G4HadronicProcess::DumpState(), FatalException, fEnvelopeName, fNuNuclTotXscBias, G4endl, G4Exception(), G4HadronicProcess::GetCrossSectionDataStore(), G4Track::GetDynamicParticle(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMaterial(), G4Region::GetName(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4LogicalVolume::GetRegion(), G4Track::GetStep(), and G4HadronicException::Report().
G4MuNeutrinoNucleusProcess& G4MuNeutrinoNucleusProcess::operator= (const G4MuNeutrinoNucleusProcess & right) private
G4VParticleChange * G4MuNeutrinoNucleusProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
! is not needed for models inheriting G4MuNeutrinoNucleus
Reimplemented from G4HadronicProcess.
Definition at line 161 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 161 of file G4MuNeutrinoNucleusProcess.cc
References G4ParticleChange::AddSecondary(), G4HadronicInteraction::ApplyYourself(), Acts::backward, G4HadFinalState::Clear(), G4VParticleChange::Clear(), G4VProcess::ClearNumberOfInteractionLengthLeft(), Acts::Test::delta, G4VSolid::DistanceToOut(), G4HadronicProcess::DumpState(), edep, fAlive, FatalException, fEnvelopeName, G4HadronicProcess::FillResult(), fKillTrackAndSecondaries, fNuNuclCcBias, fNuNuclNcBias, Acts::forward, fPostponeToNextEvent, fStopAndKill, fStopButAlive, fSuspend, fTotXsc, G4cout, G4endl, G4Exception(), G4UniformRand, G4Nucleus::GetA_asInt(), G4ProcessManager::GetAtRestProcessVector(), G4MuNeutrinoNucleusTotXsc::GetCcTotRatio(), G4HadronicProcess::GetCrossSectionDataStore(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4MuNeutrinoNucleusTotXsc::GetElementCrossSection(), G4HadFinalState::GetEnergyChange(), G4ProductionCutsTable::GetEnergyCutsVector(), G4StepPoint::GetGlobalTime(), G4Track::GetGlobalTime(), G4HadronicProcess::GetHadronicInteractionList(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4HadFinalState::GetLocalEnergyDeposit(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4HadronicInteraction::GetModelName(), G4HadFinalState::GetMomentumChange(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4Region::GetName(), G4Element::GetName(), G4Material::GetName(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4ParticleDefinition::GetParticleName(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4ParticleDefinition::GetProcessManager(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetRegion(), G4VTouchable::GetRotation(), G4HadFinalState::GetSecondary(), G4LogicalVolume::GetSolid(), G4Track::GetStep(), G4HadronicProcess::GetTargetNucleusPointer(), G4StepPoint::GetTouchable(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4HadProjectile::GetTrafoToLab(), G4VTouchable::GetTranslation(), G4Track::GetVelocity(), G4Track::GetVolume(), G4Track::GetWeight(), G4Element::GetZ(), G4Nucleus::GetZ_asInt(), incremental_prev_tag::idx, G4HadProjectile::Initialise(), G4ParticleChange::Initialize(), G4AffineTransform::Invert(), it, JustWarning, lowestEnergy, material(), part, phi, position, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeNonIonizingEnergyDeposit(), G4ParticleChange::ProposePosition(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4SafetyHelper::ReLocateWithinVolume(), G4HadronicException::Report(), CLHEP::Hep3Vector::rotate(), CLHEP::Hep3Vector::rotateUz(), safetyHelper, G4CrossSectionDataStore::SampleZandA(), G4DynamicParticle::SetMomentumDirection(), G4VParticleChange::SetNumberOfSecondaries(), G4HadronicInteraction::SetRecoilEnergyThreshold(), G4Track::SetTouchableHandle(), G4HadFinalState::SetTrafoToLab(), G4Track::SetWeight(), G4ProcessVector::size(), t, G4HadronicProcess::thePro, G4HadronicProcess::theTotalResult, Acts::Test::transform, G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), CLHEP::twopi, G4VProcess::verboseLevel, and weight.
void G4MuNeutrinoNucleusProcess::PreparePhysicsTable (const G4ParticleDefinition & part) virtual
Reimplemented from G4HadronicProcess.
Definition at line 443 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 443 of file G4MuNeutrinoNucleusProcess.cc
References eV, isInitialised, lowestEnergy, G4Neutron::Neutron(), and G4HadronicProcess::PreparePhysicsTable().
void G4MuNeutrinoNucleusProcess::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicProcess.
Definition at line 149 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 149 of file G4MuNeutrinoNucleusProcess.cc
void G4MuNeutrinoNucleusProcess::SetBiasingFactor (G4double bf)
Definition at line 91 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 91 of file G4MuNeutrinoNucleusProcess.cc
References fNuNuclTotXscBias, fTotXsc, and G4MuNeutrinoNucleusTotXsc::SetBiasingFactor().
Referenced by G4EmExtraPhysics::ConstructProcess().
void G4MuNeutrinoNucleusProcess::SetBiasingFactors (G4double bfCc, G4double bfNc)
Definition at line 101 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 101 of file G4MuNeutrinoNucleusProcess.cc
References fNuNuclCcBias, fNuNuclNcBias, and fTotXsc.
void G4MuNeutrinoNucleusProcess::SetLowestEnergy (G4double val) virtual
Definition at line 453 of file G4MuNeutrinoNucleusProcess.cc.
View newest version in sPHENIX GitHub at line 453 of file G4MuNeutrinoNucleusProcess.cc
References lowestEnergy.
Member Data Documentation
G4bool G4MuNeutrinoNucleusProcess::fBiased private
Definition at line 82 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 82 of file G4MuNeutrinoNucleusProcess.hh
G4LogicalVolume* G4MuNeutrinoNucleusProcess::fEnvelope private
Definition at line 83 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 83 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess().
G4String G4MuNeutrinoNucleusProcess::fEnvelopeName private
Definition at line 84 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 84 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), GetMeanFreePath(), and PostStepDoIt().
G4double G4MuNeutrinoNucleusProcess::fNuNuclCcBias private
Definition at line 86 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), PostStepDoIt(), and SetBiasingFactors().
G4double G4MuNeutrinoNucleusProcess::fNuNuclNcBias private
Definition at line 86 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), PostStepDoIt(), and SetBiasingFactors().
G4double G4MuNeutrinoNucleusProcess::fNuNuclTotXscBias private
Definition at line 86 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), GetMeanFreePath(), and SetBiasingFactor().
G4MuNeutrinoNucleusTotXsc* G4MuNeutrinoNucleusProcess::fTotXsc private
Definition at line 85 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), PostStepDoIt(), SetBiasingFactor(), SetBiasingFactors(), and ~G4MuNeutrinoNucleusProcess().
G4bool G4MuNeutrinoNucleusProcess::isInitialised private
Definition at line 82 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 82 of file G4MuNeutrinoNucleusProcess.hh
Referenced by PreparePhysicsTable().
G4double G4MuNeutrinoNucleusProcess::lowestEnergy private
Definition at line 81 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 81 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), PostStepDoIt(), PreparePhysicsTable(), and SetLowestEnergy().
G4SafetyHelper* G4MuNeutrinoNucleusProcess::safetyHelper private
Definition at line 87 of file G4MuNeutrinoNucleusProcess.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MuNeutrinoNucleusProcess.hh
Referenced by G4MuNeutrinoNucleusProcess(), and PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4MuNeutrinoNucleusProcess.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/src/G4MuNeutrinoNucleusProcess.cc