ECCE @ EIC Software: G4DNAWaterDissociationDisplacer Class Reference
G4DNAWaterDissociationDisplacer Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNAWaterDissociationDisplacer.hh>
Public Member Functions
G4DNAWaterDissociationDisplacer ()
virtual ~G4DNAWaterDissociationDisplacer ()
std::vector< G4ThreeVector > GetProductsDisplacement (const G4MolecularDissociationChannel *) const override
G4ThreeVector GetMotherMoleculeDisplacement (const G4MolecularDissociationChannel *) const override
G4ThreeVector radialDistributionOfElectron () const
G4ThreeVector radialDistributionOfProducts (G4double r_rms) const
Public Member Functions inherited from G4VMolecularDissociationDisplacer
virtual ~G4VMolecularDissociationDisplacer ()=default
void SetVerbose (G4int verbose)
Static Public Member Functions
static G4double ElectronProbaDistribution (G4double r)
Private Attributes
G4double ke
G4DNAModelSubType dnaSubType
Additional Inherited Members
Protected Member Functions inherited from G4VMolecularDissociationDisplacer
G4VMolecularDissociationDisplacer ()=default
Protected Attributes inherited from G4VMolecularDissociationDisplacer
G4int fVerbose
Detailed Description
Definition at line 57 of file G4DNAWaterDissociationDisplacer.hh.
View newest version in sPHENIX GitHub at line 57 of file G4DNAWaterDissociationDisplacer.hh
Constructor & Destructor Documentation
G4DNAWaterDissociationDisplacer::G4DNAWaterDissociationDisplacer ()
G4DNAWaterDissociationDisplacer::~G4DNAWaterDissociationDisplacer () virtual
Definition at line 156 of file G4DNAWaterDissociationDisplacer.cc.
View newest version in sPHENIX GitHub at line 156 of file G4DNAWaterDissociationDisplacer.cc
Member Function Documentation
static G4double G4DNAWaterDissociationDisplacer::ElectronProbaDistribution (G4double r) static
G4ThreeVector G4DNAWaterDissociationDisplacer::GetMotherMoleculeDisplacement (const G4MolecularDissociationChannel * theDecayChannel) const override virtual
Implements G4VMolecularDissociationDisplacer.
Definition at line 165 of file G4DNAWaterDissociationDisplacer.cc.
View newest version in sPHENIX GitHub at line 165 of file G4DNAWaterDissociationDisplacer.cc
References G4P6DECAYER::decayType, G4MolecularDissociationChannel::GetDisplacementType(), and nanometer.
vector< G4ThreeVector > G4DNAWaterDissociationDisplacer::GetProductsDisplacement (const G4MolecularDissociationChannel * pDecayChannel) const override virtual
Implements G4VMolecularDissociationDisplacer.
Definition at line 204 of file G4DNAWaterDissociationDisplacer.cc.
View newest version in sPHENIX GitHub at line 204 of file G4DNAWaterDissociationDisplacer.cc
References G4P6DECAYER::decayType, G4H3O::Definition(), G4OH::Definition(), G4Hydrogen::Definition(), G4H2::Definition(), G4Electron_aq::Definition(), G4cout, G4endl, G4UniformRand, G4MolecularDissociationChannel::GetDisplacementType(), G4MolecularDissociationChannel::GetName(), G4MolecularDissociationChannel::GetNbProducts(), G4MolecularDissociationChannel::GetProduct(), and nanometer.
G4ThreeVector G4DNAWaterDissociationDisplacer::radialDistributionOfElectron () const
Definition at line 440 of file G4DNAWaterDissociationDisplacer.cc.
View newest version in sPHENIX GitHub at line 440 of file G4DNAWaterDissociationDisplacer.cc
References fKreipl2009eSolvation, fMeesungnoensolid2002eSolvation, fRitchie1994eSolvation, fTerrisol1990eSolvation, DNA::Penetration::Meesungnoen2002::GetPenetration(), DNA::Penetration::Meesungnoen2002_amorphous::GetPenetration(), DNA::Penetration::Kreipl2009::GetPenetration(), DNA::Penetration::Terrisol1990::GetPenetration(), and DNA::Penetration::Ritchie1994::GetPenetration().
G4ThreeVector G4DNAWaterDissociationDisplacer::radialDistributionOfProducts (G4double r_rms) const
Definition at line 427 of file G4DNAWaterDissociationDisplacer.cc.
View newest version in sPHENIX GitHub at line 427 of file G4DNAWaterDissociationDisplacer.cc
References G4INCL::DeJongSpin::shoot(), x, y, and z.
Member Data Documentation
G4DNAModelSubType G4DNAWaterDissociationDisplacer::dnaSubType private
Definition at line 83 of file G4DNAWaterDissociationDisplacer.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DNAWaterDissociationDisplacer.hh
G4double G4DNAWaterDissociationDisplacer::ke private
Definition at line 82 of file G4DNAWaterDissociationDisplacer.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DNAWaterDissociationDisplacer.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNAWaterDissociationDisplacer.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/src/G4DNAWaterDissociationDisplacer.cc