ECCE @ EIC Software: G4ScintillationTrackInformation Class Reference
G4ScintillationTrackInformation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4ScintillationTrackInformation.hh>
Public Member Functions
G4ScintillationTrackInformation (const G4ScintillationType &aType=Slow)
virtual ~G4ScintillationTrackInformation ()
void * operator new (size_t)
void operator delete (void *aScintillationTI)
G4ScintillationTrackInformation (const G4ScintillationTrackInformation &)
G4ScintillationTrackInformation & operator= (const G4ScintillationTrackInformation &)
virtual void Print () const override
const G4ScintillationType & GetScintillationType () const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Static Public Member Functions
static G4bool IsScintillationTrackInformation (const G4VUserTrackInformation *const)
static
G4ScintillationTrackInformation * Cast (const G4VUserTrackInformation *const)
Private Attributes
G4ScintillationType scintillationType
Static Private Attributes
static const G4String BaseType = "G4ScintillationTrackInformation"
Additional Inherited Members
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Definition at line 48 of file G4ScintillationTrackInformation.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ScintillationTrackInformation.hh
Constructor & Destructor Documentation
G4ScintillationTrackInformation::G4ScintillationTrackInformation (const G4ScintillationType & aType = Slow) explicit
Definition at line 42 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ScintillationTrackInformation.cc
G4ScintillationTrackInformation::~G4ScintillationTrackInformation () virtual
Definition at line 48 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ScintillationTrackInformation.cc
G4ScintillationTrackInformation::G4ScintillationTrackInformation (const G4ScintillationTrackInformation & right)
Definition at line 52 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ScintillationTrackInformation.cc
Member Function Documentation
G4ScintillationTrackInformation * G4ScintillationTrackInformation::Cast (const G4VUserTrackInformation * const aTI) static
Definition at line 76 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ScintillationTrackInformation.cc
References IsScintillationTrackInformation().
const G4ScintillationType& G4ScintillationTrackInformation::GetScintillationType () const inline
Definition at line 65 of file G4ScintillationTrackInformation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ScintillationTrackInformation.hh
References scintillationType.
G4bool G4ScintillationTrackInformation::IsScintillationTrackInformation (const G4VUserTrackInformation * const aTI) static
Definition at line 70 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ScintillationTrackInformation.cc
References BaseType, and G4VUserTrackInformation::GetType().
Referenced by Cast().
void G4ScintillationTrackInformation::operator delete (void * aScintillationTI) inline
Definition at line 101 of file G4ScintillationTrackInformation.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ScintillationTrackInformation.hh
References aScintillationTIAllocator().
void * G4ScintillationTrackInformation::operator new (size_t) inline
Definition at line 95 of file G4ScintillationTrackInformation.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ScintillationTrackInformation.hh
References aScintillationTIAllocator().
G4ScintillationTrackInformation & G4ScintillationTrackInformation::operator= (const G4ScintillationTrackInformation & right)
Definition at line 58 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ScintillationTrackInformation.cc
References G4VUserTrackInformation::operator=(), and scintillationType.
void G4ScintillationTrackInformation::Print (void) const override virtual
Reimplemented from G4VUserTrackInformation.
Definition at line 65 of file G4ScintillationTrackInformation.cc.
View newest version in sPHENIX GitHub at line 65 of file G4ScintillationTrackInformation.cc
References G4cout, and G4endl.
Member Data Documentation
const G4String G4ScintillationTrackInformation::BaseType = "G4ScintillationTrackInformation" static private
Definition at line 77 of file G4ScintillationTrackInformation.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ScintillationTrackInformation.hh
Referenced by IsScintillationTrackInformation().
G4ScintillationType G4ScintillationTrackInformation::scintillationType private
Definition at line 75 of file G4ScintillationTrackInformation.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ScintillationTrackInformation.hh
Referenced by GetScintillationType(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4ScintillationTrackInformation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/src/G4ScintillationTrackInformation.cc