ECCE @ EIC Software: G4Cons Class Reference
G4Cons Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Cons.hh>
Public Member Functions
G4Cons (const G4String &pName, G4double pRmin1, G4double pRmax1, G4double pRmin2, G4double pRmax2, G4double pDz, G4double pSPhi, G4double pDPhi)
~G4Cons ()
G4double GetInnerRadiusMinusZ () const
G4double GetOuterRadiusMinusZ () const
G4double GetInnerRadiusPlusZ () const
G4double GetOuterRadiusPlusZ () const
G4double GetZHalfLength () const
G4double GetStartPhiAngle () const
G4double GetDeltaPhiAngle () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
void SetInnerRadiusMinusZ (G4double Rmin1)
void SetOuterRadiusMinusZ (G4double Rmax1)
void SetInnerRadiusPlusZ (G4double Rmin2)
void SetOuterRadiusPlusZ (G4double Rmax2)
void SetZHalfLength (G4double newDz)
void SetStartPhiAngle (G4double newSPhi, G4bool trig=true)
void SetDeltaPhiAngle (G4double newDPhi)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Cons (__void__ &)
G4Cons (const G4Cons &rhs)
G4Cons & operator= (const G4Cons &rhs)
G4double GetRmin1 () const
G4double GetRmax1 () const
G4double GetRmin2 () const
G4double GetRmax2 () const
G4double GetDz () const
G4double GetSPhi () const
G4double GetDPhi () const
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Types
enum ESide {
kNull, kRMin, kRMax, kSPhi,
kEPhi, kPZ, kMZ
}
enum ENorm {
kNRMin, kNRMax, kNSPhi, kNEPhi,
kNZ
}
Private Member Functions
void Initialize ()
void CheckSPhiAngle (G4double sPhi)
void CheckDPhiAngle (G4double dPhi)
void CheckPhiAngles (G4double sPhi, G4double dPhi)
void InitializeTrigonometry ()
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double kRadTolerance
G4double kAngTolerance
G4double fRmin1
G4double fRmin2
G4double fRmax1
G4double fRmax2
G4double fDz
G4double fSPhi
G4double fDPhi
G4double sinCPhi
G4double cosCPhi
G4double cosHDPhi
G4double cosHDPhiOT
G4double cosHDPhiIT
G4double sinSPhi
G4double cosSPhi
G4double sinEPhi
G4double cosEPhi
G4bool fPhiFullCone = false
G4double halfCarTolerance
G4double halfRadTolerance
G4double halfAngTolerance
Additional Inherited Members
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 77 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 77 of file G4Cons.hh
Member Enumeration Documentation
enum G4Cons::ENorm private
Enumerator:
kNRMin
kNRMax
kNSPhi
kNEPhi
kNZ
Definition at line 211 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 211 of file G4Cons.hh
enum G4Cons::ESide private
Enumerator:
kNull
kRMin
kRMax
kSPhi
kEPhi
kPZ
kMZ
Definition at line 207 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 207 of file G4Cons.hh
Constructor & Destructor Documentation
G4Cons::G4Cons (const G4String & pName, G4double pRmin1, G4double pRmax1, G4double pRmin2, G4double pRmax2, G4double pDz, G4double pSPhi, G4double pDPhi)
Definition at line 72 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 72 of file G4Cons.cc
References CheckPhiAngles(), e3, FatalException, fRmin1, fRmin2, G4endl, G4Exception(), G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4VSolid::GetName(), G4GeometryTolerance::GetRadialTolerance(), halfAngTolerance, halfCarTolerance, halfRadTolerance, kAngTolerance, G4VSolid::kCarTolerance, kRadTolerance, and message().
Referenced by Clone().
G4Cons::~G4Cons ()
Definition at line 136 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 136 of file G4Cons.cc
G4Cons::G4Cons (__void__ & a)
Definition at line 122 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 122 of file G4Cons.cc
G4Cons::G4Cons (const G4Cons & rhs)
Definition at line 144 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 144 of file G4Cons.cc
Member Function Documentation
G4ThreeVector G4Cons::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 523 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 523 of file G4Cons.cc
References cosEPhi, cosSPhi, G4VSolid::DumpInfo(), fDPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, G4Exception(), JustWarning, kNEPhi, kNRMax, kNRMin, kNSPhi, kNZ, norm, phi, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4Cons::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 261 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 261 of file G4Cons.cc
References G4GeomTools::DiskExtent(), G4VSolid::DumpInfo(), dz, G4Exception(), GetCosEndPhi(), GetCosStartPhi(), GetDeltaPhiAngle(), GetInnerRadiusMinusZ(), GetInnerRadiusPlusZ(), G4VSolid::GetName(), GetOuterRadiusMinusZ(), GetOuterRadiusPlusZ(), GetSinEndPhi(), GetSinStartPhi(), GetZHalfLength(), JustWarning, max, message(), min, pMax, rmax(), CLHEP::Hep3Vector::set(), twopi, CLHEP::Hep2Vector::x(), CLHEP::Hep3Vector::x(), CLHEP::Hep2Vector::y(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Cons::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 304 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 304 of file G4Cons.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), deg, dz, GetCosEndPhi(), GetCosStartPhi(), GetDeltaPhiAngle(), GetInnerRadiusMinusZ(), GetInnerRadiusPlusZ(), GetOuterRadiusMinusZ(), GetOuterRadiusPlusZ(), GetSinEndPhi(), GetSinStartPhi(), GetZHalfLength(), k, pMax, and twopi.
void G4Cons::CheckDPhiAngle (G4double dPhi) inline private
void G4Cons::CheckPhiAngles (G4double sPhi, G4double dPhi) inline private
Referenced by G4Cons().
void G4Cons::CheckSPhiAngle (G4double sPhi) inline private
G4VSolid * G4Cons::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 2103 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2103 of file G4Cons.cc
References G4Cons().
void G4Cons::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 250 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 250 of file G4Cons.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Cons::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 2230 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2230 of file G4Cons.cc
References fDPhi, fDz, fRmax1, fRmax2, fRmin1, fRmin2, and fSPhi.
void G4Cons::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 2225 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2225 of file G4Cons.cc
References G4VGraphicsScene::AddSolid().
G4double G4Cons::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 661 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 661 of file G4Cons.cc
References b, c, cosCPhi, cosEPhi, cosHDPhiIT, cosHDPhiOT, cosSPhi, d, CLHEP::Hep3Vector::dot(), fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, halfCarTolerance, halfRadTolerance, kInfinity, kRadTolerance, sinCPhi, sinEPhi, sinSPhi, t1, t2, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Cons::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1331 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 1331 of file G4Cons.cc
References cosCPhi, cosEPhi, cosHDPhi, cosSPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Cons::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 1393 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 1393 of file G4Cons.cc
References b, c, cosCPhi, cosEPhi, cosSPhi, d, degree, CLHEP::Hep3Vector::dot(), G4VSolid::DumpInfo(), false, fDPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, G4cout, G4endl, G4Exception(), halfAngTolerance, halfCarTolerance, halfRadTolerance, JustWarning, G4VSolid::kCarTolerance, kEPhi, kInfinity, kMZ, kNull, kPZ, kRadTolerance, kRMax, kRMin, kSPhi, message(), mm, pi, sinCPhi, sinEPhi, sinSPhi, t1, t2, true, twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Cons::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 2016 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2016 of file G4Cons.cc
References cosCPhi, cosEPhi, cosSPhi, degree, G4VSolid::DumpInfo(), fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, G4cout, G4endl, G4Exception(), Inside(), JustWarning, kInfinity, kOutside, mm, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Cons::GetCosEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Cons::GetCosStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Cons::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
G4double G4Cons::GetDeltaPhiAngle () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationConsRho::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4ParameterisationConsPhi::G4ParameterisationConsPhi(), G4VParameterisationCons::G4VParameterisationCons(), G4ParameterisationConsPhi::GetMaxParameter(), and G4tgbGeometryDumper::GetSolidParams().
G4double G4Cons::GetDPhi () const inline
G4double G4Cons::GetDz () const inline
G4GeometryType G4Cons::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 2094 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2094 of file G4Cons.cc
G4double G4Cons::GetInnerRadiusMinusZ () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationConsRho::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4ParameterisationConsRho::G4ParameterisationConsRho(), G4VParameterisationCons::G4VParameterisationCons(), G4ParameterisationConsRho::GetMaxParameter(), and G4tgbGeometryDumper::GetSolidParams().
G4double G4Cons::GetInnerRadiusPlusZ () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationConsRho::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4ParameterisationConsRho::G4ParameterisationConsRho(), G4VParameterisationCons::G4VParameterisationCons(), and G4tgbGeometryDumper::GetSolidParams().
G4double G4Cons::GetOuterRadiusMinusZ () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4ParameterisationConsRho::G4ParameterisationConsRho(), G4VParameterisationCons::G4VParameterisationCons(), G4ParameterisationConsRho::GetMaxParameter(), and G4tgbGeometryDumper::GetSolidParams().
G4double G4Cons::GetOuterRadiusPlusZ () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationConsRho::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4VParameterisationCons::G4VParameterisationCons(), and G4tgbGeometryDumper::GetSolidParams().
G4ThreeVector G4Cons::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 2139 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2139 of file G4Cons.cc
References cosEPhi, cosSPhi, fDPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, G4CSGSolid::GetRadiusInRing(), phi, G4INCL::DeJongSpin::shoot(), sinEPhi, and sinSPhi.
G4double G4Cons::GetRmax1 () const inline
G4double G4Cons::GetRmax2 () const inline
G4double G4Cons::GetRmin1 () const inline
G4double G4Cons::GetRmin2 () const inline
G4double G4Cons::GetSinEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Cons::GetSinStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Cons::GetSPhi () const inline
G4double G4Cons::GetStartPhiAngle () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationConsRho::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4VParameterisationCons::G4VParameterisationCons(), and G4tgbGeometryDumper::GetSolidParams().
G4double G4Cons::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
G4double G4Cons::GetZHalfLength () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationConsRho::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4ParameterisationConsZ::ComputeTransformation(), G4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteParamvol::Cone_dimensionsWrite(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), export_G4Cons(), G4ParameterisationConsZ::G4ParameterisationConsZ(), G4VParameterisationCons::G4VParameterisationCons(), G4ParameterisationConsZ::GetMaxParameter(), and G4tgbGeometryDumper::GetSolidParams().
void G4Cons::Initialize () inline private
void G4Cons::InitializeTrigonometry () inline private
EInside G4Cons::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 195 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 195 of file G4Cons.cc
References fDPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, halfAngTolerance, halfCarTolerance, halfRadTolerance, in, kInside, kOutside, kSurface, r2, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToOut().
G4Cons & G4Cons::operator= (const G4Cons & rhs)
Definition at line 162 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 162 of file G4Cons.cc
References cosCPhi, cosEPhi, cosHDPhi, cosHDPhiIT, cosHDPhiOT, cosSPhi, fDPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, halfAngTolerance, halfCarTolerance, halfRadTolerance, kAngTolerance, kRadTolerance, G4CSGSolid::operator=(), sinCPhi, sinEPhi, and sinSPhi.
void G4Cons::SetDeltaPhiAngle (G4double newDPhi) inline
Referenced by G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), and export_G4Cons().
void G4Cons::SetInnerRadiusMinusZ (G4double Rmin1) inline
Referenced by UltraFresnelLensParameterisation::ComputeDimensions(), G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), export_G4Cons(), and GammaKnifeDetectorConstruction::UpdateHelmet().
void G4Cons::SetInnerRadiusPlusZ (G4double Rmin2) inline
Referenced by UltraFresnelLensParameterisation::ComputeDimensions(), G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), export_G4Cons(), and GammaKnifeDetectorConstruction::UpdateHelmet().
void G4Cons::SetOuterRadiusMinusZ (G4double Rmax1) inline
Referenced by UltraFresnelLensParameterisation::ComputeDimensions(), G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), and export_G4Cons().
void G4Cons::SetOuterRadiusPlusZ (G4double Rmax2) inline
Referenced by UltraFresnelLensParameterisation::ComputeDimensions(), G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), and export_G4Cons().
void G4Cons::SetStartPhiAngle (G4double newSPhi, G4bool trig = true) inline
Referenced by G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), and export_G4Cons().
void G4Cons::SetZHalfLength (G4double newDz) inline
Referenced by UltraFresnelLensParameterisation::ComputeDimensions(), G4ParameterisationConsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), and export_G4Cons().
std::ostream & G4Cons::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 2112 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 2112 of file G4Cons.cc
References degree, fDPhi, fDz, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, G4VSolid::GetName(), and mm.
G4ThreeVector G4Cons::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 419 of file G4Cons.cc.
View newest version in sPHENIX GitHub at line 419 of file G4Cons.cc
References ApproxSurfaceNormal(), cosEPhi, cosSPhi, fDPhi, fDz, fPhiFullCone, fRmax1, fRmax2, fRmin1, fRmin2, fSPhi, G4Exception(), halfAngTolerance, halfCarTolerance, JustWarning, kInfinity, norm, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Cons::cosCPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Cons::cosEPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Cons::cosHDPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Cons::cosHDPhiIT private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Cons::cosHDPhiOT private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Cons::cosSPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Cons::fDPhi private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Cons::fDz private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4bool G4Cons::fPhiFullCone = false private
Definition at line 226 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 226 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), and SurfaceNormal().
G4double G4Cons::fRmax1 private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Cons::fRmax2 private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Cons::fRmin1 private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Cons(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Cons::fRmin2 private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Cons(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Cons::fSPhi private
Definition at line 217 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Cons::halfAngTolerance private
Definition at line 230 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Cons.hh
Referenced by DistanceToOut(), G4Cons(), Inside(), operator=(), and SurfaceNormal().
G4double G4Cons::halfCarTolerance private
Definition at line 230 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Cons.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Cons(), Inside(), operator=(), and SurfaceNormal().
G4double G4Cons::halfRadTolerance private
Definition at line 230 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Cons.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Cons(), Inside(), and operator=().
G4double G4Cons::kAngTolerance private
Definition at line 213 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Cons.hh
Referenced by G4Cons(), and operator=().
G4double G4Cons::kRadTolerance private
Definition at line 213 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Cons.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Cons(), and operator=().
G4double G4Cons::sinCPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Cons::sinEPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Cons::sinSPhi private
Definition at line 221 of file G4Cons.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cons.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Cons.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4Cons.cc