ECCE @ EIC Software: G4ShortLivedConstructor Class Reference
G4ShortLivedConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ShortLivedConstructor.hh>
Public Member Functions
G4ShortLivedConstructor ()
~G4ShortLivedConstructor ()
Static Public Member Functions
static void ConstructParticle ()
Static Protected Member Functions
static void ConstructResonances ()
static void ConstructBaryons ()
static void ConstructMesons ()
static void ConstructQuarks ()
static void ConstructAntiNuclei ()
Static Private Attributes
static G4bool isConstructed = false
Detailed Description
Definition at line 38 of file G4ShortLivedConstructor.hh.
View newest version in sPHENIX GitHub at line 38 of file G4ShortLivedConstructor.hh
Constructor & Destructor Documentation
G4ShortLivedConstructor::G4ShortLivedConstructor ()
Definition at line 49 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ShortLivedConstructor.cc
G4ShortLivedConstructor::~G4ShortLivedConstructor ()
Definition at line 53 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ShortLivedConstructor.cc
Member Function Documentation
static void G4ShortLivedConstructor::ConstructAntiNuclei () static protected
void G4ShortLivedConstructor::ConstructBaryons () static protected
Definition at line 623 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 623 of file G4ShortLivedConstructor.cc
References eplus, GeV, G4DecayTable::Insert(), MeV, particle, G4ParticleDefinition::SetDecayTable(), and G4ExcitedBaryons::SetMultipletName().
Referenced by ConstructResonances().
void G4ShortLivedConstructor::ConstructMesons () static protected
Definition at line 823 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 823 of file G4ShortLivedConstructor.cc
References eplus, G4DecayTable::Insert(), MeV, ns, particle, G4ParticleDefinition::SetAntiPDGEncoding(), G4ParticleDefinition::SetDecayTable(), and G4ExcitedMesons::SetMultipletName().
Referenced by ConstructResonances().
void G4ShortLivedConstructor::ConstructParticle (void) static
Definition at line 58 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ShortLivedConstructor.cc
References ConstructQuarks(), ConstructResonances(), and isConstructed.
Referenced by B03PhysicsList::ConstructAllShortLiveds(), XrayTelPhysicsList::ConstructAllShortLiveds(), DMXPhysicsList::ConstructMyShortLiveds(), EICPhysicsList::ConstructParticle(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), Particles::ConstructParticle(), G4HadronPhysicsQGS_BIC::ConstructParticle(), G4DecayPhysics::ConstructParticle(), G4HadronPhysicsFTF_BIC::ConstructParticle(), G4HadronPhysicsShieldingLEND::ConstructParticle(), G4VHadronPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC::ConstructParticle(), G4HadronPhysicsFTFP_BERT::ConstructParticle(), G4HadronPhysicsQGSP_BERT::ConstructParticle(), G4HadronPhysicsShielding::ConstructParticle(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructParticle(), G4HadronPhysicsINCLXX::ConstructParticle(), G4HadronPhysicsQGSP_BIC_HP::ConstructParticle(), G4HadronPhysicsFTFQGSP_BERT::ConstructParticle(), G4BinaryCascade::G4BinaryCascade(), G4CollisionNNToNDelta::G4CollisionNNToNDelta(), G4ParticleTypeConverter::G4ParticleTypeConverter(), G4ResonanceNames::G4ResonanceNames(), and G4VPartonStringModel::G4VPartonStringModel().
void G4ShortLivedConstructor::ConstructQuarks () static protected
Definition at line 70 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ShortLivedConstructor.cc
References eplus, GeV, keV, MeV, particle, and G4ParticleDefinition::SetAntiPDGEncoding().
Referenced by ConstructParticle().
void G4ShortLivedConstructor::ConstructResonances () static protected
Definition at line 590 of file G4ShortLivedConstructor.cc.
View newest version in sPHENIX GitHub at line 590 of file G4ShortLivedConstructor.cc
References G4ExcitedBaryonConstructor::Construct(), G4ExcitedMesonConstructor::Construct(), ConstructBaryons(), and ConstructMesons().
Referenced by ConstructParticle().
Member Data Documentation
G4bool G4ShortLivedConstructor::isConstructed = false static private
Definition at line 58 of file G4ShortLivedConstructor.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ShortLivedConstructor.hh
Referenced by ConstructParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ShortLivedConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ShortLivedConstructor.cc