ECCE @ EIC Software: G4tgbIsotope Class Reference
G4tgbIsotope Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbIsotope.hh>
Public Member Functions
G4tgbIsotope ()
~G4tgbIsotope ()
G4tgbIsotope (G4tgrIsotope *hg)
G4Isotope * BuildG4Isotope ()
const G4String & GetName () const
Private Attributes
G4tgrIsotope * theTgrIsot
G4Isotope * theG4Isot
Detailed Description
Definition at line 52 of file G4tgbIsotope.hh.
View newest version in sPHENIX GitHub at line 52 of file G4tgbIsotope.hh
Constructor & Destructor Documentation
G4tgbIsotope::G4tgbIsotope ()
Definition at line 39 of file G4tgbIsotope.cc.
View newest version in sPHENIX GitHub at line 39 of file G4tgbIsotope.cc
G4tgbIsotope::~G4tgbIsotope ()
Definition at line 45 of file G4tgbIsotope.cc.
View newest version in sPHENIX GitHub at line 45 of file G4tgbIsotope.cc
G4tgbIsotope::G4tgbIsotope (G4tgrIsotope * hg)
Definition at line 50 of file G4tgbIsotope.cc.
View newest version in sPHENIX GitHub at line 50 of file G4tgbIsotope.cc
References theG4Isot, and theTgrIsot.
Member Function Documentation
G4Isotope * G4tgbIsotope::BuildG4Isotope ()
Definition at line 57 of file G4tgbIsotope.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgbIsotope.cc
References G4cout, G4endl, G4tgrIsotope::GetA(), G4tgrIsotope::GetN(), G4tgrIsotope::GetName(), G4tgrMessenger::GetVerboseLevel(), G4tgrIsotope::GetZ(), theG4Isot, and theTgrIsot.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Isotope().
const G4String& G4tgbIsotope::GetName (void) const inline
Definition at line 66 of file G4tgbIsotope.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgbIsotope.hh
References G4tgrIsotope::GetName(), and theTgrIsot.
Referenced by G4tgbMaterialMgr::CopyIsotopes().
Member Data Documentation
G4Isotope* G4tgbIsotope::theG4Isot private
Definition at line 71 of file G4tgbIsotope.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgbIsotope.hh
Referenced by BuildG4Isotope(), and G4tgbIsotope().
G4tgrIsotope* G4tgbIsotope::theTgrIsot private
Definition at line 70 of file G4tgbIsotope.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgbIsotope.hh
Referenced by BuildG4Isotope(), G4tgbIsotope(), and GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbIsotope.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbIsotope.cc