ECCE @ EIC Software: G4AnyType Class Reference
G4AnyType Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyType.hh>
Classes
class Placeholder
class Ref
Public Member Functions
G4AnyType ()
template<typename ValueType >
G4AnyType (ValueType &value)
G4AnyType (const G4AnyType &other)
~G4AnyType ()
operator bool ()
G4AnyType & Swap (G4AnyType &rhs)
template<typename ValueType >
G4AnyType & operator= (const ValueType &rhs)
G4AnyType & operator= (const G4AnyType &rhs)
bool Empty () const
const std::type_info & TypeInfo () const
void * Address () const
std::string ToString () const
void FromString (const std::string &val)
Private Attributes
Placeholder * fContent
Friends
template<typename ValueType >
ValueType * any_cast (G4AnyType *)
Detailed Description
This class represents any data type. The class only holds a reference to the type and not the value.
Definition at line 62 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 62 of file G4AnyType.hh
Constructor & Destructor Documentation
G4AnyType::G4AnyType () inline
Constructor
Definition at line 65 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 65 of file G4AnyType.hh
Referenced by operator=().
template<typename ValueType > G4AnyType::G4AnyType (ValueType & value) inline
Constructor
Definition at line 69 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 69 of file G4AnyType.hh
G4AnyType::G4AnyType (const G4AnyType & other) inline
Copy Constructor
Definition at line 73 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 73 of file G4AnyType.hh
G4AnyType::~G4AnyType () inline
Dtor
Definition at line 77 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AnyType.hh
References fContent.
Member Function Documentation
void* G4AnyType::Address () const inline
Adress
Definition at line 109 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AnyType.hh
References G4AnyType::Placeholder::Address(), and fContent.
bool G4AnyType::Empty () const inline
Query
Definition at line 101 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AnyType.hh
References fContent.
Referenced by operator bool().
void G4AnyType::FromString (const std::string & val) inline
String conversion
Definition at line 117 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AnyType.hh
References fContent, and G4AnyType::Placeholder::FromString().
Referenced by G4GenericMessenger::SetNewValue().
G4AnyType::operator bool () inline
bool operator
Definition at line 82 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 82 of file G4AnyType.hh
References Empty().
template<typename ValueType > G4AnyType& G4AnyType::operator= (const ValueType & rhs) inline
Modifier
Definition at line 91 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 91 of file G4AnyType.hh
References G4AnyType().
G4AnyType& G4AnyType::operator= (const G4AnyType & rhs) inline
Modifier
Definition at line 96 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AnyType.hh
References G4AnyType().
G4AnyType& G4AnyType::Swap (G4AnyType & rhs) inline
Modifier
Definition at line 86 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 86 of file G4AnyType.hh
References fContent, and boost::swap().
std::string G4AnyType::ToString () const inline
String conversion
Definition at line 113 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AnyType.hh
References fContent, and G4AnyType::Placeholder::ToString().
Referenced by G4GenericMessenger::GetCurrentValue().
const std::type_info& G4AnyType::TypeInfo () const inline
Query
Definition at line 105 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AnyType.hh
References fContent, G4AnyType::Placeholder::TypeInfo(), and void().
Referenced by any_cast(), G4GenericMessenger::DeclareProperty(), and G4GenericMessenger::DeclarePropertyWithUnit().
Friends And Related Function Documentation
template<typename ValueType > ValueType* any_cast (G4AnyType * operand) friend
representation
value
Definition at line 212 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 212 of file G4AnyType.hh
Member Data Documentation
Placeholder* G4AnyType::fContent private
representation
Definition at line 175 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 175 of file G4AnyType.hh
Referenced by Address(), any_cast(), Empty(), FromString(), Swap(), ToString(), TypeInfo(), and ~G4AnyType().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyType.hh