ECCE @ EIC Software: G4TwistTrapFlatSide Class Reference
G4TwistTrapFlatSide Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistTrapFlatSide.hh>
Public Member Functions
G4TwistTrapFlatSide (const G4String &name, G4double PhiTwist, G4double pDx1, G4double pDx2, G4double pDy, G4double pDz, G4double pAlpha, G4double pPhi, G4double pTheta, G4int handedness)
virtual ~G4TwistTrapFlatSide ()
virtual G4ThreeVector GetNormal (const G4ThreeVector &, G4bool isGlobal=false)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate=kValidateWithTol)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[])
virtual G4ThreeVector SurfacePoint (G4double x, G4double y, G4bool isGlobal=false)
virtual G4double GetBoundaryMin (G4double u)
virtual G4double GetBoundaryMax (G4double u)
virtual G4double GetSurfaceArea ()
virtual void GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside)
G4TwistTrapFlatSide (__void__ &)
Public Member Functions inherited from G4VTwistSurface
G4VTwistSurface (const G4String &name)
G4VTwistSurface (const G4String &name, const G4RotationMatrix &rot, const G4ThreeVector &tlate, G4int handedness, const EAxis axis1, const EAxis axis2, G4double axis0min=-kInfinity, G4double axis1min=-kInfinity, G4double axis0max=kInfinity, G4double axis1max=kInfinity)
virtual ~G4VTwistSurface ()
virtual G4int AmIOnLeftSide (const G4ThreeVector &me, const G4ThreeVector &vec, G4bool withTol=true)
virtual G4double DistanceToBoundary (G4int areacode, G4ThreeVector &xx, const G4ThreeVector &p)
virtual G4double DistanceToIn (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceToOut (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceTo (const G4ThreeVector &gp, G4ThreeVector &gxx)
void DebugPrint () const
virtual G4String GetName () const
virtual void GetBoundaryParameters (const G4int &areacode, G4ThreeVector &d, G4ThreeVector &x0, G4int &boundarytype) const
virtual G4ThreeVector GetBoundaryAtPZ (G4int areacode, const G4ThreeVector &p) const
G4double DistanceToPlaneWithV (const G4ThreeVector &p, const G4ThreeVector &v, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &t1, const G4ThreeVector &t2, G4ThreeVector &xx, G4ThreeVector &n)
G4double DistanceToLine (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &d, G4ThreeVector &xx)
G4bool IsAxis0 (G4int areacode) const
G4bool IsAxis1 (G4int areacode) const
G4bool IsOutside (G4int areacode) const
G4bool IsInside (G4int areacode, G4bool testbitmode=false) const
G4bool IsBoundary (G4int areacode, G4bool testbitmode=false) const
G4bool IsCorner (G4int areacode, G4bool testbitmode=false) const
G4bool IsValidNorm () const
G4bool IsSameBoundary (G4VTwistSurface *surface1, G4int areacode1, G4VTwistSurface *surface2, G4int areacode2) const
G4int GetAxisType (G4int areacode, G4int whichaxis) const
G4ThreeVector ComputeGlobalPoint (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &gp) const
G4ThreeVector ComputeGlobalDirection (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalDirection (const G4ThreeVector &gp) const
void SetAxis (G4int i, const EAxis axis)
void SetNeighbours (G4VTwistSurface *ax0min, G4VTwistSurface *ax1min, G4VTwistSurface *ax0max, G4VTwistSurface *ax1max)
G4int GetNode (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetFace (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetEdgeVisibility (G4int i, G4int j, G4int m, G4int n, G4int number, G4int orientation)
G4VTwistSurface (__void__ &)
Protected Member Functions
virtual G4int GetAreaCode (const G4ThreeVector &xx, G4bool withTol=true)
Protected Member Functions inherited from G4VTwistSurface
G4VTwistSurface ** GetNeighbours ()
G4int GetNeighbours (G4int areacode, G4VTwistSurface *surfaces[])
G4ThreeVector GetCorner (G4int areacode) const
void GetBoundaryAxis (G4int areacode, EAxis axis[]) const
void GetBoundaryLimit (G4int areacode, G4double limit[]) const
virtual void SetBoundary (const G4int &axiscode, const G4ThreeVector &direction, const G4ThreeVector &x0, const G4int &boundarytype)
void SetCorner (G4int areacode, G4double x, G4double y, G4double z)
Private Member Functions
virtual void SetCorners ()
virtual void SetBoundaries ()
double xAxisMax (G4double u, G4double fTanAlpha) const
Private Attributes
G4double fDx1
G4double fDx2
G4double fDy
G4double fDz
G4double fPhiTwist
G4double fAlpha
G4double fTAlph
G4double fPhi
G4double fTheta
G4double fdeltaX
G4double fdeltaY
Additional Inherited Members
Public Types inherited from G4VTwistSurface
enum EValidate { kDontValidate = 0, kValidateWithTol = 1, kValidateWithoutTol = 2, kUninitialized = 3 }
Static Public Attributes inherited from G4VTwistSurface
static const G4int sOutside = 0x00000000
static const G4int sInside = 0x10000000
static const G4int sBoundary = 0x20000000
static const G4int sCorner = 0x40000000
static const G4int sC0Min1Min = 0x40000101
static const G4int sC0Max1Min = 0x40000201
static const G4int sC0Max1Max = 0x40000202
static const G4int sC0Min1Max = 0x40000102
static const G4int sAxisMin = 0x00000101
static const G4int sAxisMax = 0x00000202
static const G4int sAxisX = 0x00000404
static const G4int sAxisY = 0x00000808
static const G4int sAxisZ = 0x00000C0C
static const G4int sAxisRho = 0x00001010
static const G4int sAxisPhi = 0x00001414
static const G4int sAxis0 = 0x0000FF00
static const G4int sAxis1 = 0x000000FF
static const G4int sSizeMask = 0x00000303
static const G4int sAxisMask = 0x0000FCFC
static const G4int sAreaMask = 0XF0000000
Protected Attributes inherited from G4VTwistSurface
EAxis fAxis [2]
G4double fAxisMin [2]
G4double fAxisMax [2]
CurrentStatus fCurStatWithV
CurrentStatus fCurStat
G4RotationMatrix fRot
G4ThreeVector fTrans
G4int fHandedness
G4SurfCurNormal fCurrentNormal
G4bool fIsValidNorm
G4double kCarTolerance
Detailed Description
Definition at line 39 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 39 of file G4TwistTrapFlatSide.hh
Constructor & Destructor Documentation
G4TwistTrapFlatSide::G4TwistTrapFlatSide (const G4String & name, G4double PhiTwist, G4double pDx1, G4double pDx2, G4double pDy, G4double pDz, G4double pAlpha, G4double pPhi, G4double pTheta, G4int handedness)
Definition at line 36 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 36 of file G4TwistTrapFlatSide.cc
References fAlpha, G4VTwistSurface::fAxis, G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, G4VTwistSurface::fCurrentNormal, fdeltaX, fdeltaY, fDx1, fDx2, fDy, fDz, G4VTwistSurface::fHandedness, G4VTwistSurface::fIsValidNorm, fPhi, fPhiTwist, G4VTwistSurface::fRot, fTAlph, fTheta, G4VTwistSurface::fTrans, kInfinity, kXAxis, kYAxis, G4VTwistSurface::G4SurfCurNormal::normal, CLHEP::HepRotation::rotateZ(), CLHEP::Hep3Vector::set(), SetBoundaries(), and SetCorners().
G4TwistTrapFlatSide::~G4TwistTrapFlatSide () virtual
Definition at line 105 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 105 of file G4TwistTrapFlatSide.cc
G4TwistTrapFlatSide::G4TwistTrapFlatSide (__void__ & a)
Definition at line 95 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 95 of file G4TwistTrapFlatSide.cc
Member Function Documentation
G4int G4TwistTrapFlatSide::DistanceToSurface (const G4ThreeVector & gp, const G4ThreeVector & gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate = kValidateWithTol) virtual
Implements G4VTwistSurface.
Definition at line 128 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 128 of file G4TwistTrapFlatSide.cc
References G4VTwistSurface::ComputeGlobalPoint(), G4VTwistSurface::ComputeLocalDirection(), G4VTwistSurface::ComputeLocalPoint(), G4VTwistSurface::fCurStatWithV, G4cerr, G4endl, GetAreaCode(), G4VTwistSurface::CurrentStatus::GetAreacode(), G4VTwistSurface::CurrentStatus::GetDistance(), G4VTwistSurface::GetName(), G4VTwistSurface::CurrentStatus::GetNXX(), G4VTwistSurface::CurrentStatus::GetXX(), G4VTwistSurface::CurrentStatus::IsDone(), G4VTwistSurface::IsInside(), G4VTwistSurface::IsOutside(), G4VTwistSurface::CurrentStatus::IsValid(), kInfinity, G4VTwistSurface::kValidateWithoutTol, G4VTwistSurface::kValidateWithTol, G4VTwistSurface::CurrentStatus::ResetfDone(), CLHEP::Hep3Vector::set(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), G4VTwistSurface::sInside, G4VTwistSurface::sOutside, v, xx, and CLHEP::Hep3Vector::z().
G4int G4TwistTrapFlatSide::DistanceToSurface (const G4ThreeVector & gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[]) virtual
Implements G4VTwistSurface.
Definition at line 253 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 253 of file G4TwistTrapFlatSide.cc
References G4VTwistSurface::ComputeGlobalPoint(), G4VTwistSurface::ComputeLocalPoint(), G4VTwistSurface::fCurStat, G4VTwistSurface::CurrentStatus::GetAreacode(), G4VTwistSurface::CurrentStatus::GetDistance(), G4VTwistSurface::CurrentStatus::GetNXX(), G4VTwistSurface::CurrentStatus::GetXX(), G4VTwistSurface::CurrentStatus::IsDone(), G4VTwistSurface::kCarTolerance, G4VTwistSurface::kDontValidate, kInfinity, G4VTwistSurface::CurrentStatus::ResetfDone(), CLHEP::Hep3Vector::set(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), G4VTwistSurface::sInside, G4VTwistSurface::sOutside, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4int G4TwistTrapFlatSide::GetAreaCode (const G4ThreeVector & xx, G4bool withTol = true) protected virtual
Implements G4VTwistSurface.
Definition at line 312 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 312 of file G4TwistTrapFlatSide.cc
References FatalException, G4VTwistSurface::fAxis, G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, fTAlph, G4Exception(), G4VTwistSurface::kCarTolerance, kXAxis, kYAxis, G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, G4VTwistSurface::sAxisX, G4VTwistSurface::sAxisY, G4VTwistSurface::sBoundary, G4VTwistSurface::sCorner, G4VTwistSurface::sInside, CLHEP::Hep3Vector::x(), xAxisMax(), and CLHEP::Hep3Vector::y().
Referenced by DistanceToSurface().
G4double G4TwistTrapFlatSide::GetBoundaryMax (G4double u) inline virtual
Implements G4VTwistSurface.
Definition at line 139 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 139 of file G4TwistTrapFlatSide.hh
References fTAlph, and xAxisMax().
Referenced by GetFacets().
G4double G4TwistTrapFlatSide::GetBoundaryMin (G4double u) inline virtual
Implements G4VTwistSurface.
Definition at line 133 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 133 of file G4TwistTrapFlatSide.hh
References fTAlph, and xAxisMax().
Referenced by GetFacets().
void G4TwistTrapFlatSide::GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside) virtual
Implements G4VTwistSurface.
Definition at line 521 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 521 of file G4TwistTrapFlatSide.cc
References fDy, G4VTwistSurface::fHandedness, GetBoundaryMax(), GetBoundaryMin(), G4VTwistSurface::GetEdgeVisibility(), G4VTwistSurface::GetFace(), G4VTwistSurface::GetNode(), k, n, SurfacePoint(), CLHEP::Hep3Vector::x(), x, xmax, xmin, CLHEP::Hep3Vector::y(), y, and CLHEP::Hep3Vector::z().
G4ThreeVector G4TwistTrapFlatSide::GetNormal (const G4ThreeVector & , G4bool isGlobal = false) virtual
Implements G4VTwistSurface.
Definition at line 112 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 112 of file G4TwistTrapFlatSide.cc
References G4VTwistSurface::ComputeGlobalDirection(), G4VTwistSurface::fCurrentNormal, and G4VTwistSurface::G4SurfCurNormal::normal.
G4double G4TwistTrapFlatSide::GetSurfaceArea () inline virtual
Implements G4VTwistSurface.
Definition at line 145 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 145 of file G4TwistTrapFlatSide.hh
References fDx1, fDx2, and fDy.
void G4TwistTrapFlatSide::SetBoundaries () private virtual
Implements G4VTwistSurface.
Definition at line 473 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 473 of file G4TwistTrapFlatSide.cc
References FatalException, G4VTwistSurface::fAxis, G4endl, G4Exception(), G4VTwistSurface::GetCorner(), kXAxis, kYAxis, message(), G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, G4VTwistSurface::sAxisX, G4VTwistSurface::sAxisY, G4VTwistSurface::sC0Max1Max, G4VTwistSurface::sC0Max1Min, G4VTwistSurface::sC0Min1Max, G4VTwistSurface::sC0Min1Min, G4VTwistSurface::SetBoundary(), and CLHEP::Hep3Vector::unit().
Referenced by G4TwistTrapFlatSide().
void G4TwistTrapFlatSide::SetCorners () private virtual
Implements G4VTwistSurface.
Definition at line 426 of file G4TwistTrapFlatSide.cc.
View newest version in sPHENIX GitHub at line 426 of file G4TwistTrapFlatSide.cc
References FatalException, G4VTwistSurface::fAxis, fDx1, fDx2, fDy, fTAlph, G4endl, G4Exception(), kXAxis, kYAxis, message(), G4VTwistSurface::sC0Max1Max, G4VTwistSurface::sC0Max1Min, G4VTwistSurface::sC0Min1Max, G4VTwistSurface::sC0Min1Min, G4VTwistSurface::SetCorner(), x, y, and z.
Referenced by G4TwistTrapFlatSide().
G4ThreeVector G4TwistTrapFlatSide::SurfacePoint (G4double x, G4double y, G4bool isGlobal = false) inline virtual
Implements G4VTwistSurface.
Definition at line 124 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 124 of file G4TwistTrapFlatSide.hh
References G4VTwistSurface::fRot, and G4VTwistSurface::fTrans.
Referenced by GetFacets().
G4double G4TwistTrapFlatSide::xAxisMax (G4double u, G4double fTanAlpha) const inline private
Definition at line 118 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 118 of file G4TwistTrapFlatSide.hh
References fDx1, fDx2, and fDy.
Referenced by GetAreaCode(), GetBoundaryMax(), and GetBoundaryMin().
Member Data Documentation
G4double G4TwistTrapFlatSide::fAlpha private
Definition at line 105 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 105 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
G4double G4TwistTrapFlatSide::fdeltaX private
Definition at line 109 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 109 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
G4double G4TwistTrapFlatSide::fdeltaY private
Definition at line 110 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 110 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
G4double G4TwistTrapFlatSide::fDx1 private
Definition at line 100 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 100 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide(), GetSurfaceArea(), SetCorners(), and xAxisMax().
G4double G4TwistTrapFlatSide::fDx2 private
Definition at line 101 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 101 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide(), GetSurfaceArea(), SetCorners(), and xAxisMax().
G4double G4TwistTrapFlatSide::fDy private
Definition at line 102 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 102 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide(), GetFacets(), GetSurfaceArea(), SetCorners(), and xAxisMax().
G4double G4TwistTrapFlatSide::fDz private
Definition at line 103 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 103 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
G4double G4TwistTrapFlatSide::fPhi private
Definition at line 107 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 107 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
G4double G4TwistTrapFlatSide::fPhiTwist private
Definition at line 104 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 104 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
G4double G4TwistTrapFlatSide::fTAlph private
Definition at line 106 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 106 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide(), GetAreaCode(), GetBoundaryMax(), GetBoundaryMin(), and SetCorners().
G4double G4TwistTrapFlatSide::fTheta private
Definition at line 108 of file G4TwistTrapFlatSide.hh.
View newest version in sPHENIX GitHub at line 108 of file G4TwistTrapFlatSide.hh
Referenced by G4TwistTrapFlatSide().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistTrapFlatSide.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4TwistTrapFlatSide.cc