ECCE @ EIC Software: G4HadronInelasticQBBC Class Reference
G4HadronInelasticQBBC Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronInelasticQBBC.hh>
Public Member Functions
G4HadronInelasticQBBC (G4int ver=1)
G4HadronInelasticQBBC (const G4String &name, G4int ver=1, G4bool ftf=false, G4bool bert=false, G4bool chips=false, G4bool hp=false, G4bool glauber=false)
virtual ~G4HadronInelasticQBBC ()
void ConstructProcess () override
Public Member Functions inherited from G4VHadronPhysics
G4VHadronPhysics (const G4String &name="hInelastic", G4int verbose=0)
virtual ~G4VHadronPhysics ()
virtual void ConstructParticle ()
G4HadronicInteraction * BuildModel (G4VHadronModelBuilder *, G4double emin, G4double emax)
G4HadronicInteraction * NewModel (G4HadronicInteraction *, G4double emin, G4double emax)
void AddInelasticCrossSection (const G4String &, G4VCrossSectionDataSet *)
void AddInelasticCrossSection (const G4ParticleDefinition *, G4VCrossSectionDataSet *)
void AddElasticCrossSection (const G4String &, G4VCrossSectionDataSet *)
void AddElasticCrossSection (const G4ParticleDefinition *, G4VCrossSectionDataSet *)
void AddCaptureCrossSection (G4VCrossSectionDataSet *)
void AddFissionCrossSection (G4VCrossSectionDataSet *)
G4CrossSectionInelastic * InelasticXS (const G4String &componentName)
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
G4HadronInelasticQBBC (G4HadronInelasticQBBC &)
G4HadronInelasticQBBC & operator= (const G4HadronInelasticQBBC &right)
Private Attributes
G4int verbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VHadronPhysics
G4HadronicProcess * FindInelasticProcess (const G4String &)
G4HadronicProcess * FindInelasticProcess (const G4ParticleDefinition *)
G4HadronicProcess * FindElasticProcess (const G4String &)
G4HadronicProcess * FindElasticProcess (const G4ParticleDefinition *)
G4HadronicProcess * FindCaptureProcess ()
G4HadronicProcess * FindFissionProcess ()
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 47 of file G4HadronInelasticQBBC.hh.
View newest version in sPHENIX GitHub at line 47 of file G4HadronInelasticQBBC.hh
Constructor & Destructor Documentation
G4HadronInelasticQBBC::G4HadronInelasticQBBC (G4int ver = 1)
Definition at line 83 of file G4HadronInelasticQBBC.cc.
View newest version in sPHENIX GitHub at line 83 of file G4HadronInelasticQBBC.cc
G4HadronInelasticQBBC::G4HadronInelasticQBBC (const G4String & name, G4int ver = 1, G4bool ftf = false, G4bool bert = false, G4bool chips = false, G4bool hp = false, G4bool glauber = false)
Definition at line 87 of file G4HadronInelasticQBBC.cc.
View newest version in sPHENIX GitHub at line 87 of file G4HadronInelasticQBBC.cc
G4HadronInelasticQBBC::~G4HadronInelasticQBBC () virtual
Definition at line 91 of file G4HadronInelasticQBBC.cc.
View newest version in sPHENIX GitHub at line 91 of file G4HadronInelasticQBBC.cc
G4HadronInelasticQBBC::G4HadronInelasticQBBC (G4HadronInelasticQBBC &) private
Member Function Documentation
void G4HadronInelasticQBBC::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 94 of file G4HadronInelasticQBBC.cc.
View newest version in sPHENIX GitHub at line 94 of file G4HadronInelasticQBBC.cc
References G4HadronicProcess::AddDataSet(), G4VHadronPhysics::BuildModel(), G4ComponentGGHadronNucleusXsc::Default_Name(), emax, G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindInelasticProcess(), G4HadronicInteractionRegistry::FindModel(), G4cout, G4endl, G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), GeV, G4VHadronPhysics::InelasticXS(), G4HadronicInteractionRegistry::Instance(), G4HadronicParameters::Instance(), G4VHadronPhysics::NewModel(), particle, pname(), G4HadronicProcess::RegisterMe(), G4CascadeInterface::usePreCompoundDeexcitation(), and verbose.
G4HadronInelasticQBBC& G4HadronInelasticQBBC::operator= (const G4HadronInelasticQBBC & right) private
Member Data Documentation
G4int G4HadronInelasticQBBC::verbose private
Definition at line 72 of file G4HadronInelasticQBBC.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HadronInelasticQBBC.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronInelasticQBBC.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronInelasticQBBC.cc