ECCE @ EIC Software: G4HyperonFTFPBuilder Class Reference
G4HyperonFTFPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4HyperonFTFPBuilder.hh>
Public Member Functions
G4HyperonFTFPBuilder ()
virtual ~G4HyperonFTFPBuilder ()
virtual void Build () finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * HyperonFTFP
G4TheoFSGenerator * AntiHyperonFTFP
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4LundStringFragmentation * theLund
G4CascadeInterface * theBertini
G4LambdaInelasticProcess * theLambdaInelastic
G4AntiLambdaInelasticProcess * theAntiLambdaInelastic
G4SigmaMinusInelasticProcess * theSigmaMinusInelastic
G4AntiSigmaMinusInelasticProcess * theAntiSigmaMinusInelastic
G4SigmaPlusInelasticProcess * theSigmaPlusInelastic
G4AntiSigmaPlusInelasticProcess * theAntiSigmaPlusInelastic
G4XiZeroInelasticProcess * theXiZeroInelastic
G4AntiXiZeroInelasticProcess * theAntiXiZeroInelastic
G4XiMinusInelasticProcess * theXiMinusInelastic
G4AntiXiMinusInelasticProcess * theAntiXiMinusInelastic
G4OmegaMinusInelasticProcess * theOmegaMinusInelastic
G4AntiOmegaMinusInelasticProcess * theAntiOmegaMinusInelastic
G4VCrossSectionDataSet * theInelasticCrossSection
G4bool wasActivated
Detailed Description
Definition at line 68 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HyperonFTFPBuilder.hh
Constructor & Destructor Documentation
G4HyperonFTFPBuilder::G4HyperonFTFPBuilder ()
Definition at line 48 of file G4HyperonFTFPBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4HyperonFTFPBuilder.cc
References AntiHyperonFTFP, HyperonFTFP, G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), theBertini, theCascade, theInelasticCrossSection, theLund, theStringDecay, and theStringModel.
G4HyperonFTFPBuilder::~G4HyperonFTFPBuilder () virtual
Definition at line 96 of file G4HyperonFTFPBuilder.cc.
View newest version in sPHENIX GitHub at line 96 of file G4HyperonFTFPBuilder.cc
References theLund, and theStringDecay.
Member Function Documentation
void G4HyperonFTFPBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 102 of file G4HyperonFTFPBuilder.cc.
View newest version in sPHENIX GitHub at line 102 of file G4HyperonFTFPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), AntiHyperonFTFP, G4AntiLambda::AntiLambda(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), G4ParticleDefinition::GetProcessManager(), HyperonFTFP, G4Lambda::Lambda(), G4OmegaMinus::OmegaMinus(), G4HadronicProcess::RegisterMe(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), theAntiLambdaInelastic, theAntiOmegaMinusInelastic, theAntiSigmaMinusInelastic, theAntiSigmaPlusInelastic, theAntiXiMinusInelastic, theAntiXiZeroInelastic, theBertini, theInelasticCrossSection, theLambdaInelastic, theOmegaMinusInelastic, theSigmaMinusInelastic, theSigmaPlusInelastic, theXiMinusInelastic, theXiZeroInelastic, wasActivated, G4XiMinus::XiMinus(), and G4XiZero::XiZero().
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), and G4HadronPhysicsQGSP_BIC_HP::ConstructProcess().
Member Data Documentation
G4TheoFSGenerator* G4HyperonFTFPBuilder::AntiHyperonFTFP private
Definition at line 79 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HyperonFTFPBuilder.hh
Referenced by Build(), and G4HyperonFTFPBuilder().
G4TheoFSGenerator* G4HyperonFTFPBuilder::HyperonFTFP private
Definition at line 78 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HyperonFTFPBuilder.hh
Referenced by Build(), and G4HyperonFTFPBuilder().
G4AntiLambdaInelasticProcess* G4HyperonFTFPBuilder::theAntiLambdaInelastic private
Definition at line 86 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4AntiOmegaMinusInelasticProcess* G4HyperonFTFPBuilder::theAntiOmegaMinusInelastic private
Definition at line 96 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 96 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4AntiSigmaMinusInelasticProcess* G4HyperonFTFPBuilder::theAntiSigmaMinusInelastic private
Definition at line 88 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 88 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4AntiSigmaPlusInelasticProcess* G4HyperonFTFPBuilder::theAntiSigmaPlusInelastic private
Definition at line 90 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4AntiXiMinusInelasticProcess* G4HyperonFTFPBuilder::theAntiXiMinusInelastic private
Definition at line 94 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 94 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4AntiXiZeroInelasticProcess* G4HyperonFTFPBuilder::theAntiXiZeroInelastic private
Definition at line 92 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4CascadeInterface* G4HyperonFTFPBuilder::theBertini private
Definition at line 84 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HyperonFTFPBuilder.hh
Referenced by Build(), and G4HyperonFTFPBuilder().
G4GeneratorPrecompoundInterface* G4HyperonFTFPBuilder::theCascade private
Definition at line 80 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HyperonFTFPBuilder.hh
Referenced by G4HyperonFTFPBuilder().
G4VCrossSectionDataSet* G4HyperonFTFPBuilder::theInelasticCrossSection private
Definition at line 98 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 98 of file G4HyperonFTFPBuilder.hh
Referenced by Build(), and G4HyperonFTFPBuilder().
G4LambdaInelasticProcess* G4HyperonFTFPBuilder::theLambdaInelastic private
Definition at line 85 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4LundStringFragmentation* G4HyperonFTFPBuilder::theLund private
Definition at line 83 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HyperonFTFPBuilder.hh
Referenced by G4HyperonFTFPBuilder(), and ~G4HyperonFTFPBuilder().
G4OmegaMinusInelasticProcess* G4HyperonFTFPBuilder::theOmegaMinusInelastic private
Definition at line 95 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 95 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4SigmaMinusInelasticProcess* G4HyperonFTFPBuilder::theSigmaMinusInelastic private
Definition at line 87 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4SigmaPlusInelasticProcess* G4HyperonFTFPBuilder::theSigmaPlusInelastic private
Definition at line 89 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4ExcitedStringDecay* G4HyperonFTFPBuilder::theStringDecay private
Definition at line 82 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HyperonFTFPBuilder.hh
Referenced by G4HyperonFTFPBuilder(), and ~G4HyperonFTFPBuilder().
G4FTFModel* G4HyperonFTFPBuilder::theStringModel private
Definition at line 81 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HyperonFTFPBuilder.hh
Referenced by G4HyperonFTFPBuilder().
G4XiMinusInelasticProcess* G4HyperonFTFPBuilder::theXiMinusInelastic private
Definition at line 93 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 93 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4XiZeroInelasticProcess* G4HyperonFTFPBuilder::theXiZeroInelastic private
Definition at line 91 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
G4bool G4HyperonFTFPBuilder::wasActivated private
Definition at line 99 of file G4HyperonFTFPBuilder.hh.
View newest version in sPHENIX GitHub at line 99 of file G4HyperonFTFPBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4HyperonFTFPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4HyperonFTFPBuilder.cc