ECCE @ EIC Software: CLHEP::HepRotationY Class Reference
CLHEP::HepRotationY Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/RotationY.h>
Public Member Functions
HepRotationY ()
HepRotationY (double delta)
HepRotationY (const HepRotationY &orig)
HepRotationY (HepRotationY &&orig)=default
HepRotationY & operator= (const HepRotationY &r)
HepRotationY & operator= (HepRotationY &&r)=default
HepRotationY & set (double delta)
~HepRotationY ()
Hep3Vector colX () const
Hep3Vector colY () const
Hep3Vector colZ () const
Hep3Vector rowX () const
Hep3Vector rowY () const
Hep3Vector rowZ () const
double xx () const
double xy () const
double xz () const
double yx () const
double yy () const
double yz () const
double zx () const
double zy () const
double zz () const
HepRep3x3 rep3x3 () const
double getPhi () const
double getTheta () const
double getPsi () const
double phi () const
double theta () const
double psi () const
HepEulerAngles eulerAngles () const
double getDelta () const
Hep3Vector getAxis () const
double delta () const
Hep3Vector axis () const
HepAxisAngle axisAngle () const
void getAngleAxis (double &delta, Hep3Vector &axis) const
double phiX () const
double phiY () const
double phiZ () const
double thetaX () const
double thetaY () const
double thetaZ () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
double xt () const
double yt () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepRep4x4 rep4x4 () const
void setDelta (double delta)
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
bool isIdentity () const
int compare (const HepRotationY &r) const
bool operator== (const HepRotationY &r) const
bool operator!= (const HepRotationY &r) const
bool operator< (const HepRotationY &r) const
bool operator> (const HepRotationY &r) const
bool operator<= (const HepRotationY &r) const
bool operator>= (const HepRotationY &r) const
double distance2 (const HepRotationY &r) const
double distance2 (const HepRotation &r) const
double howNear (const HepRotationY &r) const
double howNear (const HepRotation &r) const
bool isNear (const HepRotationY &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
double distance2 (const HepBoost &lt) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &lt) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoost &lt, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
Hep3Vector operator() (const Hep3Vector &p) const
Hep3Vector operator* (const Hep3Vector &p) const
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepRotationY operator* (const HepRotationY &ry) const
HepRotationY & operator*= (const HepRotationY &r)
HepRotationY & transform (const HepRotationY &r)
HepRotationY inverse () const
HepRotationY & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepRotationY (double dd, double ss, double cc)
Static Protected Member Functions
static double proper (double delta)
Protected Attributes
double its_d
double its_s
double its_c
Friends
HepRotationY inverseOf (const HepRotationY &r)
Detailed Description
Author
Definition at line 42 of file RotationY.h.
View newest version in sPHENIX GitHub at line 42 of file RotationY.h
Constructor & Destructor Documentation
CLHEP::HepRotationY::HepRotationY () inline
CLHEP::HepRotationY::HepRotationY (double delta)
Definition at line 31 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 31 of file RotationY.cc
CLHEP::HepRotationY::HepRotationY (const HepRotationY & orig) inline
CLHEP::HepRotationY::HepRotationY (HepRotationY && orig) inline default
CLHEP::HepRotationY::~HepRotationY () inline
CLHEP::HepRotationY::HepRotationY (double dd, double ss, double cc) inline protected
Member Function Documentation
Hep3Vector CLHEP::HepRotationY::axis () const inline
HepAxisAngle CLHEP::HepRotationY::axisAngle () const inline
HepLorentzVector CLHEP::HepRotationY::col1 () const inline
HepLorentzVector CLHEP::HepRotationY::col2 () const inline
HepLorentzVector CLHEP::HepRotationY::col3 () const inline
HepLorentzVector CLHEP::HepRotationY::col4 () const inline
Hep3Vector CLHEP::HepRotationY::colX () const inline
Hep3Vector CLHEP::HepRotationY::colY () const inline
Hep3Vector CLHEP::HepRotationY::colZ () const inline
int CLHEP::HepRotationY::compare (const HepRotationY & r) const inline
void CLHEP::HepRotationY::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 112 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 112 of file RotationY.cc
References CLHEP::Hep3Vector::set().
void CLHEP::HepRotationY::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 118 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 118 of file RotationY.cc
References CLHEP::Hep3Vector::set().
void CLHEP::HepRotationY::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 124 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 124 of file RotationY.cc
References CLHEP::HepBoost::set().
void CLHEP::HepRotationY::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 130 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 130 of file RotationY.cc
References CLHEP::HepBoost::set().
double CLHEP::HepRotationY::delta () const inline
double CLHEP::HepRotationY::distance2 (const HepRotationY & r) const
Definition at line 135 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 135 of file RotationY.cc
References its_c, and its_s.
Referenced by distance2(), howNear(), and isNear().
double CLHEP::HepRotationY::distance2 (const HepRotation & r) const
Definition at line 140 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 140 of file RotationY.cc
References sum, xx(), CLHEP::HepRotation::xx(), xz(), CLHEP::HepRotation::xz(), CLHEP::HepRotation::yy(), zx(), CLHEP::HepRotation::zx(), zz(), and CLHEP::HepRotation::zz().
double CLHEP::HepRotationY::distance2 (const HepBoost & lt) const
Definition at line 158 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 158 of file RotationY.cc
References distance2().
double CLHEP::HepRotationY::distance2 (const HepLorentzRotation & lt) const
Definition at line 148 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 148 of file RotationY.cc
References a, b, CLHEP::Hep3Vector::beta(), CLHEP::HepLorentzRotation::decompose(), distance2(), and r.
HepEulerAngles CLHEP::HepRotationY::eulerAngles () const
Definition at line 66 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 66 of file RotationY.cc
References phi(), psi(), and theta().
void CLHEP::HepRotationY::getAngleAxis (double & delta, Hep3Vector & axis) const inline
Hep3Vector CLHEP::HepRotationY::getAxis () const inline
double CLHEP::HepRotationY::getDelta () const inline
double CLHEP::HepRotationY::getPhi () const inline
double CLHEP::HepRotationY::getPsi () const inline
double CLHEP::HepRotationY::getTheta () const inline
static double CLHEP::HepRotationY::getTolerance () inline static
double CLHEP::HepRotationY::howNear (const HepRotationY & r) const
Definition at line 162 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 162 of file RotationY.cc
References distance2().
double CLHEP::HepRotationY::howNear (const HepRotation & r) const
Definition at line 165 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 165 of file RotationY.cc
References distance2().
double CLHEP::HepRotationY::howNear (const HepBoost & lt) const
Definition at line 168 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 168 of file RotationY.cc
References distance2().
double CLHEP::HepRotationY::howNear (const HepLorentzRotation & lt) const
Definition at line 171 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 171 of file RotationY.cc
References distance2().
HepRotationY CLHEP::HepRotationY::inverse () const inline
HepRotationY& CLHEP::HepRotationY::invert () inline
bool CLHEP::HepRotationY::isIdentity () const inline
bool CLHEP::HepRotationY::isNear (const HepRotationY & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 174 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 174 of file RotationY.cc
References distance2().
bool CLHEP::HepRotationY::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 177 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 177 of file RotationY.cc
References distance2().
bool CLHEP::HepRotationY::isNear (const HepBoost & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 180 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 180 of file RotationY.cc
References distance2().
bool CLHEP::HepRotationY::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 183 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 183 of file RotationY.cc
References distance2().
double CLHEP::HepRotationY::norm2 () const
Definition at line 188 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 188 of file RotationY.cc
References its_c.
bool CLHEP::HepRotationY::operator!= (const HepRotationY & r) const inline
Hep3Vector CLHEP::HepRotationY::operator() (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotationY::operator() (const HepLorentzVector & w) const inline
Hep3Vector CLHEP::HepRotationY::operator* (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotationY::operator* (const HepLorentzVector & w) const inline
HepRotationY CLHEP::HepRotationY::operator* (const HepRotationY & ry) const inline
HepRotationY& CLHEP::HepRotationY::operator*= (const HepRotationY & r) inline
bool CLHEP::HepRotationY::operator< (const HepRotationY & r) const inline
bool CLHEP::HepRotationY::operator<= (const HepRotationY & r) const inline
HepRotationY& CLHEP::HepRotationY::operator= (const HepRotationY & r) inline
HepRotationY& CLHEP::HepRotationY::operator= (HepRotationY && r) inline default
bool CLHEP::HepRotationY::operator== (const HepRotationY & r) const inline
bool CLHEP::HepRotationY::operator> (const HepRotationY & r) const inline
bool CLHEP::HepRotationY::operator>= (const HepRotationY & r) const inline
double CLHEP::HepRotationY::phi () const
Definition at line 42 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 42 of file RotationY.cc
References CLHEP::halfpi, its_d, and CLHEP::pi.
Referenced by eulerAngles().
double CLHEP::HepRotationY::phiX () const
Definition at line 78 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 78 of file RotationY.cc
References xx(), and yx().
double CLHEP::HepRotationY::phiY () const
Definition at line 83 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 83 of file RotationY.cc
References xy(), and yy().
double CLHEP::HepRotationY::phiZ () const
Definition at line 88 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 88 of file RotationY.cc
References xz(), and yz().
std::ostream & CLHEP::HepRotationY::print (std::ostream & os) const
Definition at line 192 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 192 of file RotationY.cc
References its_c, its_d, and its_s.
static double CLHEP::HepRotationY::proper (double delta) inline static protected
Referenced by set().
double CLHEP::HepRotationY::psi () const
Definition at line 56 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 56 of file RotationY.cc
References CLHEP::halfpi, its_d, and CLHEP::pi.
Referenced by eulerAngles().
void CLHEP::HepRotationY::rectify () inline
HepRep3x3 CLHEP::HepRotationY::rep3x3 () const inline
HepRep4x4 CLHEP::HepRotationY::rep4x4 () const inline
HepLorentzVector CLHEP::HepRotationY::row1 () const inline
HepLorentzVector CLHEP::HepRotationY::row2 () const inline
HepLorentzVector CLHEP::HepRotationY::row3 () const inline
HepLorentzVector CLHEP::HepRotationY::row4 () const inline
Hep3Vector CLHEP::HepRotationY::rowX () const inline
Hep3Vector CLHEP::HepRotationY::rowY () const inline
Hep3Vector CLHEP::HepRotationY::rowZ () const inline
HepRotationY & CLHEP::HepRotationY::set (double delta)
Definition at line 35 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 35 of file RotationY.cc
References its_c, its_d, its_s, and proper().
void CLHEP::HepRotationY::setDelta (double delta)
Definition at line 107 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 107 of file RotationY.cc
static double CLHEP::HepRotationY::setTolerance (double tol) inline static
double CLHEP::HepRotationY::theta () const
Definition at line 52 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 52 of file RotationY.cc
References its_d.
Referenced by eulerAngles().
double CLHEP::HepRotationY::thetaX () const
Definition at line 93 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 93 of file RotationY.cc
References CLHEP::safe_acos(), and zx().
double CLHEP::HepRotationY::thetaY () const
Definition at line 97 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 97 of file RotationY.cc
References CLHEP::safe_acos(), and zy().
double CLHEP::HepRotationY::thetaZ () const
Definition at line 102 of file RotationY.cc.
View newest version in sPHENIX GitHub at line 102 of file RotationY.cc
References CLHEP::safe_acos(), and zz().
HepRotationY& CLHEP::HepRotationY::transform (const HepRotationY & r) inline
double CLHEP::HepRotationY::tt () const inline
double CLHEP::HepRotationY::tx () const inline
double CLHEP::HepRotationY::ty () const inline
double CLHEP::HepRotationY::tz () const inline
double CLHEP::HepRotationY::xt () const inline
double CLHEP::HepRotationY::xx () const inline
Referenced by distance2(), and phiX().
double CLHEP::HepRotationY::xy () const inline
Referenced by phiY().
double CLHEP::HepRotationY::xz () const inline
Referenced by distance2(), and phiZ().
double CLHEP::HepRotationY::yt () const inline
double CLHEP::HepRotationY::yx () const inline
Referenced by phiX().
double CLHEP::HepRotationY::yy () const inline
Referenced by phiY().
double CLHEP::HepRotationY::yz () const inline
Referenced by phiZ().
double CLHEP::HepRotationY::zt () const inline
double CLHEP::HepRotationY::zx () const inline
Referenced by distance2(), and thetaX().
double CLHEP::HepRotationY::zy () const inline
Referenced by thetaY().
double CLHEP::HepRotationY::zz () const inline
Referenced by distance2(), and thetaZ().
Friends And Related Function Documentation
HepRotationY inverseOf (const HepRotationY & r) friend
Member Data Documentation
double CLHEP::HepRotationY::its_c protected
Definition at line 265 of file RotationY.h.
View newest version in sPHENIX GitHub at line 265 of file RotationY.h
Referenced by distance2(), norm2(), print(), and set().
double CLHEP::HepRotationY::its_d protected
Definition at line 261 of file RotationY.h.
View newest version in sPHENIX GitHub at line 261 of file RotationY.h
Referenced by phi(), print(), psi(), set(), and theta().
double CLHEP::HepRotationY::its_s protected
Definition at line 264 of file RotationY.h.
View newest version in sPHENIX GitHub at line 264 of file RotationY.h
Referenced by distance2(), print(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/RotationY.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationY.cc