ECCE @ EIC Software: G4INCL::PhaseSpaceGenerator Namespace Reference
G4INCL::PhaseSpaceGenerator Namespace Reference
Functions
void generate (const G4double sqrtS, ParticleList &particles)
Generate an event in the CM system.
void generateBiased (const G4double sqrtS, ParticleList &particles, const size_t index, const G4double slope)
Generate a biased event in the CM system.
void setPhaseSpaceGenerator (IPhaseSpaceGenerator *g)
IPhaseSpaceGenerator * getPhaseSpaceGenerator ()
void deletePhaseSpaceGenerator ()
void initialize (Config const *const theConfig)
Function Documentation
void G4INCL::PhaseSpaceGenerator::deletePhaseSpaceGenerator ()
Definition at line 117 of file G4INCLPhaseSpaceGenerator.cc.
View newest version in sPHENIX GitHub at line 117 of file G4INCLPhaseSpaceGenerator.cc
Referenced by G4INCL::INCL::~INCL().
void G4INCL::PhaseSpaceGenerator::generate (const G4double sqrtS, ParticleList & particles)
Generate an event in the CM system.
Definition at line 94 of file G4INCLPhaseSpaceGenerator.cc.
View newest version in sPHENIX GitHub at line 94 of file G4INCLPhaseSpaceGenerator.cc
Referenced by G4INCL::PionResonanceDecayChannel::fillFinalState(), G4HadPhaseSpaceGenbod::FillRandomBuffer(), generateBiased(), G4HadPhaseSpaceNBodyAsai::GenerateMultiBody(), G4ElementaryParticleCollider::generateSCMfinalState(), FW::EventGenerator::read(), and G4LightTargetCollider::SingleNucleonScattering().
void G4INCL::PhaseSpaceGenerator::generateBiased (const G4double sqrtS, ParticleList & particles, const size_t index, const G4double slope)
Generate a biased event in the CM system.
This method first generates a "flat" event by calling generate(). The particles are subsequently rotated in such a way that one of them (identified by the parameter index) is biased towards the collisionAxis with an exponential distribution of the form
where is the usual Mandelstam variable. The incoming momentum is taken to be the momentum of particles[index] at the moment of the call.
Parameters
sqrtS total energy in the centre of mass, in MeV
particles list of particles for which the event will be generated (modified on exit)
index index of the particle to be biased; all the other particles will follow
slope slope of the angular distribution: , in (GeV/c)^(-2)
Definition at line 98 of file G4INCLPhaseSpaceGenerator.cc.
View newest version in sPHENIX GitHub at line 98 of file G4INCLPhaseSpaceGenerator.cc
References generate(), and G4INCL::ThreeVector::mag().
Referenced by G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), and G4INCL::NDeltaOmegaProductionChannel::fillFinalState().
IPhaseSpaceGenerator * G4INCL::PhaseSpaceGenerator::getPhaseSpaceGenerator ()
Definition at line 113 of file G4INCLPhaseSpaceGenerator.cc.
View newest version in sPHENIX GitHub at line 113 of file G4INCLPhaseSpaceGenerator.cc
void G4INCL::PhaseSpaceGenerator::initialize (Config const *const theConfig)
Definition at line 122 of file G4INCLPhaseSpaceGenerator.cc.
View newest version in sPHENIX GitHub at line 122 of file G4INCLPhaseSpaceGenerator.cc
References G4INCL::Config::getPhaseSpaceGeneratorType(), G4INCL::KopylovType, G4INCL::RauboldLynchType, and setPhaseSpaceGenerator().
Referenced by G4INCL::INCL::INCL().
void G4INCL::PhaseSpaceGenerator::setPhaseSpaceGenerator (IPhaseSpaceGenerator * g)
Definition at line 109 of file G4INCLPhaseSpaceGenerator.cc.
View newest version in sPHENIX GitHub at line 109 of file G4INCLPhaseSpaceGenerator.cc
References Acts::UnitConstants::g.
Referenced by initialize().