ECCE @ EIC Software: G4MuonRadiativeDecayChannelWithSpin Class Reference
G4MuonRadiativeDecayChannelWithSpin Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonRadiativeDecayChannelWithSpin.hh>
Public Member Functions
G4MuonRadiativeDecayChannelWithSpin (const G4String &theParentName, G4double theBR)
virtual ~G4MuonRadiativeDecayChannelWithSpin ()
virtual G4DecayProducts * DecayIt (G4double)
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Protected Member Functions
G4MuonRadiativeDecayChannelWithSpin (const G4MuonRadiativeDecayChannelWithSpin &)
G4MuonRadiativeDecayChannelWithSpin & operator= (const G4MuonRadiativeDecayChannelWithSpin &)
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Private Member Functions
G4MuonRadiativeDecayChannelWithSpin ()
G4double fron (G4double Pmu, G4double x, G4double y, G4double cthetaE, G4double cthetaG, G4double cthetaEG)
void rn3dim (G4double &x, G4double &y, G4double &z, G4double xlong)
G4double atan4 (G4double x, G4double y)
Additional Inherited Members
Protected Attributes inherited from G4VDecayChannel
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 61 of file G4MuonRadiativeDecayChannelWithSpin.hh.
View newest version in sPHENIX GitHub at line 61 of file G4MuonRadiativeDecayChannelWithSpin.hh
Constructor & Destructor Documentation
G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin (const G4String & theParentName, G4double theBR)
Definition at line 59 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 59 of file G4MuonRadiativeDecayChannelWithSpin.cc
References G4cout, G4endl, G4VDecayChannel::GetVerboseLevel(), G4VDecayChannel::SetBR(), G4VDecayChannel::SetDaughter(), G4VDecayChannel::SetNumberOfDaughters(), and G4VDecayChannel::SetParent().
G4MuonRadiativeDecayChannelWithSpin::~G4MuonRadiativeDecayChannelWithSpin () virtual
Definition at line 91 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 91 of file G4MuonRadiativeDecayChannelWithSpin.cc
G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin (const G4MuonRadiativeDecayChannelWithSpin & right) protected
Definition at line 95 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 95 of file G4MuonRadiativeDecayChannelWithSpin.cc
G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin () private
Definition at line 53 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 53 of file G4MuonRadiativeDecayChannelWithSpin.cc
Member Function Documentation
G4double G4MuonRadiativeDecayChannelWithSpin::atan4 (G4double x, G4double y) inline private
Definition at line 124 of file G4MuonRadiativeDecayChannelWithSpin.hh.
View newest version in sPHENIX GitHub at line 124 of file G4MuonRadiativeDecayChannelWithSpin.hh
References phi, and CLHEP::pi.
Referenced by DecayIt().
G4DecayProducts * G4MuonRadiativeDecayChannelWithSpin::DecayIt (G4double) virtual
if(i<10000000)goto leap1:
Implements G4VDecayChannel.
Definition at line 129 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 129 of file G4MuonRadiativeDecayChannelWithSpin.cc
References atan4(), CLHEP::HepLorentzVector::boost(), G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), Acts::Test::delta, G4DecayProducts::DumpInfo(), E, eps, fron(), G, G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4DynamicParticle::Get4Momentum(), G4VDecayChannel::GetParentName(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), G4VDecayChannel::GetVerboseLevel(), keV, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), MeV, G4VDecayChannel::parent_polarization, G4DecayProducts::PushProducts(), rad, rn3dim(), CLHEP::Hep3Vector::rotateUz(), G4DynamicParticle::Set4Momentum(), twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), x, xx, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and zz.
G4double G4MuonRadiativeDecayChannelWithSpin::fron (G4double Pmu, G4double x, G4double y, G4double cthetaE, G4double cthetaG, G4double cthetaEG) private
Definition at line 434 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 434 of file G4MuonRadiativeDecayChannelWithSpin.cc
References Acts::Test::delta, eps, source.hepunit::fine_structure_const, twopi, x, and y.
Referenced by DecayIt().
G4MuonRadiativeDecayChannelWithSpin & G4MuonRadiativeDecayChannelWithSpin::operator= (const G4MuonRadiativeDecayChannelWithSpin & right) protected
Definition at line 100 of file G4MuonRadiativeDecayChannelWithSpin.cc.
View newest version in sPHENIX GitHub at line 100 of file G4MuonRadiativeDecayChannelWithSpin.cc
References G4VDecayChannel::ClearDaughtersName(), G4VDecayChannel::daughters_name, G4VDecayChannel::kinematics_name, G4VDecayChannel::numberOfDaughters, G4VDecayChannel::parent_name, G4VDecayChannel::parent_polarization, G4VDecayChannel::rbranch, and G4VDecayChannel::verboseLevel.
void G4MuonRadiativeDecayChannelWithSpin::rn3dim (G4double & x, G4double & y, G4double & z, G4double xlong) inline private
Definition at line 102 of file G4MuonRadiativeDecayChannelWithSpin.hh.
View newest version in sPHENIX GitHub at line 102 of file G4MuonRadiativeDecayChannelWithSpin.hh
References a, b, c, G4UniformRand, and r.
Referenced by DecayIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonRadiativeDecayChannelWithSpin.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4MuonRadiativeDecayChannelWithSpin.cc