ECCE @ EIC Software: G4TheMTRayTracer Class Reference
G4TheMTRayTracer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4TheMTRayTracer.hh>
Public Member Functions
G4TheMTRayTracer (G4VFigureFileMaker *figMaker=0, G4VRTScanner *scanner=0)
virtual ~G4TheMTRayTracer ()
virtual void Trace (const G4String &fileName)
Public Member Functions inherited from G4TheRayTracer
G4TheRayTracer (G4VFigureFileMaker *figMaker=0, G4VRTScanner *scanner=0)
virtual ~G4TheRayTracer ()
void SetFigureFileMaker (G4VFigureFileMaker *figMaker)
G4VFigureFileMaker * GetFigureFileMaker ()
void SetScanner (G4VRTScanner *scanner)
G4VRTScanner * GetScanner ()
void SetNColumn (G4int val)
G4int GetNColumn () const
void SetNRow (G4int val)
G4int GetNRow () const
void SetEyePosition (const G4ThreeVector &val)
G4ThreeVector GetEyePosition () const
void SetTargetPosition (const G4ThreeVector &val)
G4ThreeVector GetTargetPosition () const
void SetLightDirection (const G4ThreeVector &val)
G4ThreeVector GetLightDirection () const
void SetUpVector (const G4ThreeVector &val)
G4ThreeVector GetUpVector () const
void SetHeadAngle (G4double val)
G4double GetHeadAngle () const
void SetViewSpan (G4double val)
G4double GetViewSpan () const
void SetAttenuationLength (G4double val)
G4double GetAttenuationLength () const
void SetDistortion (G4bool val)
G4bool GetDistortion () const
void SetBackgroundColour (const G4Colour &val)
G4Colour GetBackgroundColour () const
Protected Member Functions
virtual G4bool CreateBitMap ()
virtual void StoreUserActions ()
virtual void RestoreUserActions ()
Protected Member Functions inherited from G4TheRayTracer
void CreateFigureFile (const G4String &fileName)
G4bool GenerateColour (G4Event *anEvent)
G4Colour GetSurfaceColour (G4RayTrajectoryPoint *point)
G4Colour GetMixedColour (const G4Colour &surfCol, const G4Colour &transCol, G4double weight=0.5)
G4Colour Attenuate (G4RayTrajectoryPoint *point, const G4Colour &sourceCol)
G4bool ValidColour (const G4VisAttributes *visAtt)
Protected Attributes
const G4UserWorkerInitialization * theUserWorkerInitialization
G4RTWorkerInitialization * theRTWorkerInitialization
const G4UserRunAction * theUserRunAction
G4RTRunAction * theRTRunAction
Protected Attributes inherited from G4TheRayTracer
G4RayShooter * theRayShooter
G4VFigureFileMaker * theFigMaker
G4RTMessenger * theMessenger
G4VRTScanner * theScanner
G4EventManager * theEventManager
G4UserEventAction * theUserEventAction
G4UserStackingAction * theUserStackingAction
G4UserTrackingAction * theUserTrackingAction
G4UserSteppingAction * theUserSteppingAction
G4UserEventAction * theRayTracerEventAction
G4UserStackingAction * theRayTracerStackingAction
G4RTTrackingAction * theRayTracerTrackingAction
G4RTSteppingAction * theRayTracerSteppingAction
unsigned char * colorR
unsigned char * colorG
unsigned char * colorB
G4int nColumn
G4int nRow
G4ThreeVector eyePosition
G4ThreeVector targetPosition
G4ThreeVector eyeDirection
G4ThreeVector lightDirection
G4ThreeVector up
G4double headAngle
G4double viewSpan
G4double attenuationLength
G4bool distortionOn
G4bool antialiasingOn
G4Colour rayColour
G4Colour backgroundColour
Static Private Attributes
static G4TheMTRayTracer * theInstance = nullptr
Friends
class G4RTPrimaryGeneratorAction
class G4RTRun
class G4RayTracerViewer
Detailed Description
Definition at line 70 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 70 of file G4TheMTRayTracer.hh
Constructor & Destructor Documentation
G4TheMTRayTracer::G4TheMTRayTracer (G4VFigureFileMaker * figMaker = 0, G4VRTScanner * scanner = 0)
Definition at line 50 of file G4TheMTRayTracer.cc.
View newest version in sPHENIX GitHub at line 50 of file G4TheMTRayTracer.cc
References FatalException, G4Exception(), theInstance, theRTRunAction, theRTWorkerInitialization, theUserRunAction, and theUserWorkerInitialization.
G4TheMTRayTracer::~G4TheMTRayTracer () virtual
Definition at line 65 of file G4TheMTRayTracer.cc.
View newest version in sPHENIX GitHub at line 65 of file G4TheMTRayTracer.cc
References theRTRunAction, and theRTWorkerInitialization.
Member Function Documentation
G4bool G4TheMTRayTracer::CreateBitMap () protected virtual
Reimplemented from G4TheRayTracer.
Definition at line 151 of file G4TheMTRayTracer.cc.
View newest version in sPHENIX GitHub at line 151 of file G4TheMTRayTracer.cc
References G4UImanager::ApplyCommand(), col, G4TheRayTracer::colorB, G4TheRayTracer::colorG, G4TheRayTracer::colorR, G4UIcommand::ConvertToString(), G4VRTScanner::Coords(), G4VRTScanner::Draw(), G4Colour::GetBlue(), G4VVisManager::GetConcreteInstance(), G4RunManager::GetCurrentRun(), G4Colour::GetGreen(), G4RTRun::GetMap(), G4VTHitsMap< T, Map_t >::GetMap(), G4MTRunManager::GetMasterRunManager(), G4Colour::GetRed(), G4UImanager::GetUIpointer(), G4VVisManager::IgnoreStateChanges(), G4VRTScanner::Initialize(), G4TheRayTracer::nColumn, G4TheRayTracer::nRow, RestoreUserActions(), StoreUserActions(), and G4TheRayTracer::theScanner.
Referenced by Trace().
void G4TheMTRayTracer::RestoreUserActions () protected virtual
Reimplemented from G4TheRayTracer.
Definition at line 144 of file G4TheMTRayTracer.cc.
View newest version in sPHENIX GitHub at line 144 of file G4TheMTRayTracer.cc
References G4MTRunManager::GetMasterRunManager(), G4MTRunManager::SetUserAction(), G4MTRunManager::SetUserInitialization(), theUserRunAction, and theUserWorkerInitialization.
Referenced by CreateBitMap().
void G4TheMTRayTracer::StoreUserActions () protected virtual
Reimplemented from G4TheRayTracer.
Definition at line 131 of file G4TheMTRayTracer.cc.
View newest version in sPHENIX GitHub at line 131 of file G4TheMTRayTracer.cc
References G4MTRunManager::GetMasterRunManager(), G4RunManager::GetUserRunAction(), G4RunManager::GetUserWorkerInitialization(), G4MTRunManager::SetUserAction(), G4MTRunManager::SetUserInitialization(), theRTRunAction, theRTWorkerInitialization, theUserRunAction, and theUserWorkerInitialization.
Referenced by CreateBitMap().
void G4TheMTRayTracer::Trace (const G4String & fileName) virtual
Reimplemented from G4TheRayTracer.
Definition at line 79 of file G4TheMTRayTracer.cc.
View newest version in sPHENIX GitHub at line 79 of file G4TheMTRayTracer.cc
References G4UImanager::ApplyCommand(), G4TheRayTracer::backgroundColour, G4TheRayTracer::colorB, G4TheRayTracer::colorG, G4TheRayTracer::colorR, G4UIcommand::ConvertToString(), CreateBitMap(), G4TheRayTracer::CreateFigureFile(), G4TheRayTracer::eyeDirection, G4TheRayTracer::eyePosition, G4cerr, G4endl, G4State_Idle, G4Colour::GetBlue(), G4UImanager::GetCurrentIntValue(), G4StateManager::GetCurrentState(), G4Colour::GetGreen(), G4Colour::GetRed(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4UImanager::GetUIpointer(), G4TheRayTracer::nColumn, G4TheRayTracer::nRow, G4TheRayTracer::targetPosition, G4TheRayTracer::theFigMaker, and CLHEP::Hep3Vector::unit().
Friends And Related Function Documentation
friend class G4RayTracerViewer friend
Definition at line 74 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 74 of file G4TheMTRayTracer.hh
friend class G4RTPrimaryGeneratorAction friend
Definition at line 72 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TheMTRayTracer.hh
friend class G4RTRun friend
Definition at line 73 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 73 of file G4TheMTRayTracer.hh
Member Data Documentation
G4TheMTRayTracer * G4TheMTRayTracer::theInstance = nullptr static private
Definition at line 77 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 77 of file G4TheMTRayTracer.hh
Referenced by G4RTRun::G4RTRun(), G4TheMTRayTracer(), and G4RTPrimaryGeneratorAction::SetUp().
G4RTRunAction* G4TheMTRayTracer::theRTRunAction protected
Definition at line 112 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 112 of file G4TheMTRayTracer.hh
Referenced by G4TheMTRayTracer(), StoreUserActions(), and ~G4TheMTRayTracer().
G4RTWorkerInitialization* G4TheMTRayTracer::theRTWorkerInitialization protected
Definition at line 110 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 110 of file G4TheMTRayTracer.hh
Referenced by G4TheMTRayTracer(), StoreUserActions(), and ~G4TheMTRayTracer().
const G4UserRunAction* G4TheMTRayTracer::theUserRunAction protected
Definition at line 111 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 111 of file G4TheMTRayTracer.hh
Referenced by G4TheMTRayTracer(), RestoreUserActions(), and StoreUserActions().
const G4UserWorkerInitialization* G4TheMTRayTracer::theUserWorkerInitialization protected
Definition at line 109 of file G4TheMTRayTracer.hh.
View newest version in sPHENIX GitHub at line 109 of file G4TheMTRayTracer.hh
Referenced by G4TheMTRayTracer(), RestoreUserActions(), and StoreUserActions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4TheMTRayTracer.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4TheMTRayTracer.cc