ECCE @ EIC Software: G4QMDNucleus Class Reference
G4QMDNucleus Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDNucleus.hh>
Public Member Functions
G4QMDNucleus ()
G4LorentzVector Get4Momentum ()
G4int GetMassNumber ()
G4int GetAtomicNumber ()
void CalEnergyAndAngularMomentumInCM ()
G4double GetNuclearMass ()
void SetTotalPotential (G4double x)
G4double GetExcitationEnergy ()
G4int GetAngularMomentum ()
Public Member Functions inherited from G4QMDSystem
G4QMDSystem ()
virtual ~G4QMDSystem ()
void SetParticipant (G4QMDParticipant *particle)
void SetSystem (G4QMDSystem *, G4ThreeVector, G4ThreeVector)
void SubtractSystem (G4QMDSystem *)
G4QMDParticipant * EraseParticipant (G4int i)
void DeleteParticipant (G4int i)
void InsertParticipant (G4QMDParticipant *particle, G4int j)
G4int GetTotalNumberOfParticipant ()
G4QMDParticipant * GetParticipant (G4int i)
void IncrementCollisionCounter ()
G4int GetNOCollision ()
void ShowParticipants ()
void Clear ()
Private Attributes
G4double hbc
std::vector< G4ThreeVector > rcm
std::vector< G4ThreeVector > pcm
std::vector< G4double > es
G4int jj
G4double potentialEnergy
G4double excitationEnergy
Additional Inherited Members
Protected Attributes inherited from G4QMDSystem
std::vector< G4QMDParticipant * > participants
Detailed Description
Definition at line 43 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 43 of file G4QMDNucleus.hh
Constructor & Destructor Documentation
G4QMDNucleus::G4QMDNucleus ()
Definition at line 38 of file G4QMDNucleus.cc.
View newest version in sPHENIX GitHub at line 38 of file G4QMDNucleus.cc
References excitationEnergy, G4QMDParameters::Get_hbc(), G4QMDParameters::GetInstance(), hbc, jj, Dataset::parameters, and potentialEnergy.
Member Function Documentation
void G4QMDNucleus::CalEnergyAndAngularMomentumInCM ()
Definition at line 138 of file G4QMDNucleus.cc.
View newest version in sPHENIX GitHub at line 138 of file G4QMDNucleus.cc
References G4InuclSpecialFunctions::bindingEnergy(), CLHEP::HepLorentzVector::e(), es, excitationEnergy, CLHEP::HepLorentzVector::gamma(), Get4Momentum(), GetAtomicNumber(), G4NucleiProperties::GetBindingEnergy(), G4Pow::GetInstance(), G4QMDParticipant::GetMass(), GetMassNumber(), G4QMDParticipant::GetMomentum(), G4QMDSystem::GetParticipant(), G4QMDParticipant::GetPosition(), G4QMDSystem::GetTotalNumberOfParticipant(), GeV, hbc, int(), jj, n, pcm, potentialEnergy, rcm, and CLHEP::HepLorentzVector::v().
Referenced by G4QMDReaction::ApplyYourself(), and G4QMDMeanField::SetNucleus().
G4LorentzVector G4QMDNucleus::Get4Momentum ()
Definition at line 56 of file G4QMDNucleus.cc.
View newest version in sPHENIX GitHub at line 56 of file G4QMDNucleus.cc
References it, and G4QMDSystem::participants.
Referenced by CalEnergyAndAngularMomentumInCM().
G4int G4QMDNucleus::GetAngularMomentum () inline
Definition at line 65 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QMDNucleus.hh
G4int G4QMDNucleus::GetAtomicNumber ()
Definition at line 89 of file G4QMDNucleus.cc.
View newest version in sPHENIX GitHub at line 89 of file G4QMDNucleus.cc
References it, G4QMDSystem::participants, G4Proton::Proton(), and Z.
Referenced by CalEnergyAndAngularMomentumInCM(), GetNuclearMass(), and G4QMDGroundStateNucleus::packNucleons().
G4double G4QMDNucleus::GetExcitationEnergy (void) inline
Definition at line 63 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 63 of file G4QMDNucleus.hh
References excitationEnergy.
G4int G4QMDNucleus::GetMassNumber ()
Definition at line 68 of file G4QMDNucleus.cc.
View newest version in sPHENIX GitHub at line 68 of file G4QMDNucleus.cc
References A(), it, G4Neutron::Neutron(), G4QMDSystem::participants, and G4Proton::Proton().
Referenced by CalEnergyAndAngularMomentumInCM(), G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), GetNuclearMass(), G4QMDGroundStateNucleus::killCMMotionAndAngularM(), G4QMDGroundStateNucleus::packNucleons(), and G4QMDGroundStateNucleus::samplingMomentum().
G4double G4QMDNucleus::GetNuclearMass (void)
Definition at line 103 of file G4QMDNucleus.cc.
View newest version in sPHENIX GitHub at line 103 of file G4QMDNucleus.cc
References A(), G4Pow::A13(), G4Pow::A23(), GetAtomicNumber(), G4Pow::GetInstance(), GetMassNumber(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), mass, MeV, N, G4Neutron::Neutron(), G4Proton::Proton(), and Z.
void G4QMDNucleus::SetTotalPotential (G4double x) inline
Definition at line 62 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 62 of file G4QMDNucleus.hh
References potentialEnergy, and x.
Referenced by G4QMDReaction::ApplyYourself(), and G4QMDMeanField::SetNucleus().
Member Data Documentation
std::vector< G4double > G4QMDNucleus::es private
Definition at line 72 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM().
G4double G4QMDNucleus::excitationEnergy private
Definition at line 76 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM(), G4QMDNucleus(), and GetExcitationEnergy().
G4double G4QMDNucleus::hbc private
Definition at line 65 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM(), and G4QMDNucleus().
G4int G4QMDNucleus::jj private
Definition at line 73 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM(), and G4QMDNucleus().
std::vector< G4ThreeVector > G4QMDNucleus::pcm private
Definition at line 71 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM().
G4double G4QMDNucleus::potentialEnergy private
Definition at line 75 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM(), G4QMDNucleus(), and SetTotalPotential().
std::vector< G4ThreeVector > G4QMDNucleus::rcm private
Definition at line 71 of file G4QMDNucleus.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDNucleus.hh
Referenced by CalEnergyAndAngularMomentumInCM().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDNucleus.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDNucleus.cc