ECCE @ EIC Software: G4PolarizationTransition Class Reference
G4PolarizationTransition Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4PolarizationTransition.hh>
Public Member Functions
G4PolarizationTransition ()
~G4PolarizationTransition ()
void SampleGammaTransition (G4NuclearPolarization *np, G4int twoJ1, G4int twoJ2, G4int L0, G4int Lp, G4double mpRatio, G4double &cosTheta, G4double &phi)
G4double FCoefficient (G4int K, G4int L, G4int Lprime, G4int twoJ2, G4int twoJ1) const
G4double F3Coefficient (G4int K, G4int K2, G4int K1, G4int L, G4int Lprime, G4int twoJ2, G4int twoJ1) const
G4double GammaTransFCoefficient (G4int K) const
G4double GammaTransF3Coefficient (G4int K, G4int K2, G4int K1) const
void DumpTransitionData (const POLAR &pol) const
void SetVerbose (G4int val)
Private Types
typedef std::vector
< std::vector< G4complex > > POLAR
Private Member Functions
G4PolarizationTransition (const G4PolarizationTransition &right)=delete
const G4PolarizationTransition & operator= (const G4PolarizationTransition &right)=delete
G4double GenerateGammaCosTheta (const POLAR &)
G4double GenerateGammaPhi (G4double &cosTheta, const POLAR &)
G4double LnFactorial (int k) const
Private Attributes
G4int fVerbose
G4int fTwoJ1
G4int fTwoJ2
G4int fLbar
G4int fL
G4double fDelta
G4double kEps
G4PolynomialPDF kPolyPDF
G4LegendrePolynomial fgLegendrePolys
Detailed Description
Definition at line 58 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PolarizationTransition.hh
Member Typedef Documentation
typedef std::vector< std::vector<G4complex> > G4PolarizationTransition::POLAR private
Definition at line 60 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 60 of file G4PolarizationTransition.hh
Constructor & Destructor Documentation
G4PolarizationTransition::G4PolarizationTransition () explicit
Definition at line 49 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PolarizationTransition.cc
G4PolarizationTransition::~G4PolarizationTransition ()
Definition at line 54 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PolarizationTransition.cc
G4PolarizationTransition::G4PolarizationTransition (const G4PolarizationTransition & right) private delete
Member Function Documentation
void G4PolarizationTransition::DumpTransitionData (const POLAR & pol) const
Definition at line 387 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 387 of file G4PolarizationTransition.cc
References fDelta, fL, fLbar, fTwoJ1, fTwoJ2, G4cout, G4endl, and k.
Referenced by GenerateGammaCosTheta(), GenerateGammaPhi(), and SampleGammaTransition().
G4double G4PolarizationTransition::F3Coefficient (G4int K, G4int K2, G4int K1, G4int L, G4int Lprime, G4int twoJ2, G4int twoJ1) const
Definition at line 68 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 68 of file G4PolarizationTransition.cc
References G4Clebsch::Wigner3J(), and G4Clebsch::Wigner9J().
Referenced by GammaTransF3Coefficient().
G4double G4PolarizationTransition::FCoefficient (G4int K, G4int L, G4int Lprime, G4int twoJ2, G4int twoJ1) const
Definition at line 57 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PolarizationTransition.cc
References G4Clebsch::Wigner3J(), and G4Clebsch::Wigner6J().
Referenced by GammaTransFCoefficient().
G4double G4PolarizationTransition::GammaTransF3Coefficient (G4int K, G4int K2, G4int K1) const
Definition at line 94 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 94 of file G4PolarizationTransition.cc
References F3Coefficient(), fDelta, fL, fLbar, fTwoJ1, and fTwoJ2.
Referenced by SampleGammaTransition().
G4double G4PolarizationTransition::GammaTransFCoefficient (G4int K) const
Definition at line 85 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 85 of file G4PolarizationTransition.cc
References FCoefficient(), fDelta, fL, fLbar, fTwoJ1, and fTwoJ2.
Referenced by GenerateGammaCosTheta(), and GenerateGammaPhi().
G4double G4PolarizationTransition::GenerateGammaCosTheta (const POLAR & pol) private
Definition at line 104 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 104 of file G4PolarizationTransition.cc
References kdfinder::abs(), DumpTransitionData(), fgLegendrePolys, fVerbose, G4cout, G4endl, G4UniformRand, GammaTransFCoefficient(), G4LegendrePolynomial::GetCoefficient(), G4LegendrePolynomial::GetNCoefficients(), G4PolynomialPDF::GetRandomX(), k, kEps, kPolyPDF, BTOF::length, and G4PolynomialPDF::SetCoefficients().
Referenced by SampleGammaTransition().
G4double G4PolarizationTransition::GenerateGammaPhi (G4double & cosTheta, const POLAR & pol) private
Definition at line 143 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 143 of file G4PolarizationTransition.cc
References kdfinder::abs(), DumpTransitionData(), G4LegendrePolynomial::EvalAssocLegendrePoly(), fgLegendrePolys, fVerbose, G4cout, G4endl, G4Exp(), G4UniformRand, GammaTransFCoefficient(), k, kEps, BTOF::length, LnFactorial(), phase(), phi, and CLHEP::twopi.
Referenced by SampleGammaTransition().
G4double G4PolarizationTransition::LnFactorial (int k) const inline private
Definition at line 95 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PolarizationTransition.hh
References G4Pow::GetInstance(), and G4Pow::logfactorial().
Referenced by GenerateGammaPhi(), and SampleGammaTransition().
const G4PolarizationTransition& G4PolarizationTransition::operator= (const G4PolarizationTransition & right) private delete
void G4PolarizationTransition::SampleGammaTransition (G4NuclearPolarization * np, G4int twoJ1, G4int twoJ2, G4int L0, G4int Lp, G4double mpRatio, G4double & cosTheta, G4double & phi)
Definition at line 231 of file G4PolarizationTransition.cc.
View newest version in sPHENIX GitHub at line 231 of file G4PolarizationTransition.cc
References kdfinder::abs(), DumpTransitionData(), G4LegendrePolynomial::EvalAssocLegendrePoly(), fDelta, fgLegendrePolys, fL, fLbar, fTwoJ1, fTwoJ2, fVerbose, G4cout, G4endl, G4Exp(), G4UniformRand, GammaTransF3Coefficient(), GenerateGammaCosTheta(), GenerateGammaPhi(), G4NuclearPolarization::GetPolarization(), k, k1, k2, kEps, LnFactorial(), G4NuclearPolarization::SetPolarization(), CLHEP::twopi, G4NuclearPolarization::Unpolarize(), and G4Clebsch::Wigner3J().
Referenced by G4GammaTransition::SampleDirection().
void G4PolarizationTransition::SetVerbose (G4int val) inline
Definition at line 83 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PolarizationTransition.hh
References fVerbose.
Referenced by G4GammaTransition::SetVerbose().
Member Data Documentation
G4double G4PolarizationTransition::fDelta private
Definition at line 100 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PolarizationTransition.hh
Referenced by DumpTransitionData(), GammaTransF3Coefficient(), GammaTransFCoefficient(), and SampleGammaTransition().
G4LegendrePolynomial G4PolarizationTransition::fgLegendrePolys private
Definition at line 103 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PolarizationTransition.hh
Referenced by GenerateGammaCosTheta(), GenerateGammaPhi(), and SampleGammaTransition().
G4int G4PolarizationTransition::fL private
Definition at line 99 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 99 of file G4PolarizationTransition.hh
Referenced by DumpTransitionData(), GammaTransF3Coefficient(), GammaTransFCoefficient(), and SampleGammaTransition().
G4int G4PolarizationTransition::fLbar private
Definition at line 99 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 99 of file G4PolarizationTransition.hh
Referenced by DumpTransitionData(), GammaTransF3Coefficient(), GammaTransFCoefficient(), and SampleGammaTransition().
G4int G4PolarizationTransition::fTwoJ1 private
Definition at line 98 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 98 of file G4PolarizationTransition.hh
Referenced by DumpTransitionData(), GammaTransF3Coefficient(), GammaTransFCoefficient(), and SampleGammaTransition().
G4int G4PolarizationTransition::fTwoJ2 private
Definition at line 98 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 98 of file G4PolarizationTransition.hh
Referenced by DumpTransitionData(), GammaTransF3Coefficient(), GammaTransFCoefficient(), and SampleGammaTransition().
G4int G4PolarizationTransition::fVerbose private
Definition at line 97 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 97 of file G4PolarizationTransition.hh
Referenced by GenerateGammaCosTheta(), GenerateGammaPhi(), SampleGammaTransition(), and SetVerbose().
G4double G4PolarizationTransition::kEps private
Definition at line 101 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PolarizationTransition.hh
Referenced by GenerateGammaCosTheta(), GenerateGammaPhi(), and SampleGammaTransition().
G4PolynomialPDF G4PolarizationTransition::kPolyPDF private
Definition at line 102 of file G4PolarizationTransition.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PolarizationTransition.hh
Referenced by GenerateGammaCosTheta().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4PolarizationTransition.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/src/G4PolarizationTransition.cc