ECCE @ EIC Software: G4QMDSystem Class Reference
G4QMDSystem Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDSystem.hh>
Public Member Functions
G4QMDSystem ()
virtual ~G4QMDSystem ()
void SetParticipant (G4QMDParticipant *particle)
void SetSystem (G4QMDSystem *, G4ThreeVector, G4ThreeVector)
void SubtractSystem (G4QMDSystem *)
G4QMDParticipant * EraseParticipant (G4int i)
void DeleteParticipant (G4int i)
void InsertParticipant (G4QMDParticipant *particle, G4int j)
G4int GetTotalNumberOfParticipant ()
G4QMDParticipant * GetParticipant (G4int i)
void IncrementCollisionCounter ()
G4int GetNOCollision ()
void ShowParticipants ()
void Clear ()
Protected Attributes
std::vector< G4QMDParticipant * > participants
Private Attributes
G4int numberOfCollision
Detailed Description
Definition at line 45 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 45 of file G4QMDSystem.hh
Constructor & Destructor Documentation
G4QMDSystem::G4QMDSystem ()
Definition at line 31 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 31 of file G4QMDSystem.cc
References numberOfCollision, and participants.
G4QMDSystem::~G4QMDSystem () virtual
Definition at line 39 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 39 of file G4QMDSystem.cc
References Clear().
Member Function Documentation
void G4QMDSystem::Clear ()
Definition at line 68 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 68 of file G4QMDSystem.cc
References GetTotalNumberOfParticipant(), and participants.
Referenced by G4QMDReaction::ApplyYourself(), and ~G4QMDSystem().
void G4QMDSystem::DeleteParticipant (G4int i) inline
Definition at line 57 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 57 of file G4QMDSystem.hh
References participants.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
G4QMDParticipant* G4QMDSystem::EraseParticipant (G4int i) inline
Definition at line 56 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 56 of file G4QMDSystem.hh
References participants, and particle.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision().
G4int G4QMDSystem::GetNOCollision () inline
Definition at line 65 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QMDSystem.hh
References numberOfCollision.
Referenced by G4QMDReaction::ApplyYourself().
G4QMDParticipant* G4QMDSystem::GetParticipant (G4int i) inline
Definition at line 62 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 62 of file G4QMDSystem.hh
References participants.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDMeanField::Cal2BodyQuantities(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDMeanField::CalGraduate(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4QMDMeanField::calPauliBlockingFactor(), G4QMDMeanField::DoClusterJudgment(), G4QMDMeanField::DoPropagation(), G4QMDMeanField::GetPotential(), G4QMDMeanField::GetTotalPotential(), G4QMDMeanField::IsPauliBlocked(), and SubtractSystem().
G4int G4QMDSystem::GetTotalNumberOfParticipant () inline
Definition at line 60 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 60 of file G4QMDSystem.hh
References participants.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDMeanField::Cal2BodyQuantities(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDMeanField::CalGraduate(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4QMDMeanField::calPauliBlockingFactor(), Clear(), G4QMDMeanField::DoClusterJudgment(), G4QMDMeanField::DoPropagation(), G4QMDMeanField::GetPotential(), G4QMDMeanField::GetTotalPotential(), G4QMDMeanField::SetSystem(), and SubtractSystem().
void G4QMDSystem::IncrementCollisionCounter () inline
Definition at line 64 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QMDSystem.hh
References numberOfCollision.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
void G4QMDSystem::InsertParticipant (G4QMDParticipant * particle, G4int j)
Definition at line 110 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 110 of file G4QMDSystem.cc
References G4cout, G4endl, it, n, and participants.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision().
void G4QMDSystem::SetParticipant (G4QMDParticipant * particle) inline
Definition at line 51 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 51 of file G4QMDSystem.hh
References participants.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4QMDMeanField::DoClusterJudgment(), G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), and SetSystem().
void G4QMDSystem::SetSystem (G4QMDSystem * nucleus, G4ThreeVector dp, G4ThreeVector dr)
Definition at line 46 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 46 of file G4QMDSystem.cc
References it, participants, r, and SetParticipant().
void G4QMDSystem::ShowParticipants ()
Definition at line 79 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 79 of file G4QMDSystem.cc
References G4cout, G4endl, it, CLHEP::Hep3Vector::mag(), and participants.
void G4QMDSystem::SubtractSystem (G4QMDSystem * nucleus)
Definition at line 59 of file G4QMDSystem.cc.
View newest version in sPHENIX GitHub at line 59 of file G4QMDSystem.cc
References GetParticipant(), GetTotalNumberOfParticipant(), and participants.
Referenced by G4QMDMeanField::DoClusterJudgment().
Member Data Documentation
G4int G4QMDSystem::numberOfCollision private
Definition at line 75 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QMDSystem.hh
Referenced by G4QMDSystem(), GetNOCollision(), and IncrementCollisionCounter().
std::vector< G4QMDParticipant* > G4QMDSystem::participants protected
Definition at line 72 of file G4QMDSystem.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QMDSystem.hh
Referenced by Clear(), DeleteParticipant(), EraseParticipant(), G4QMDSystem(), G4QMDNucleus::Get4Momentum(), G4QMDNucleus::GetAtomicNumber(), G4QMDNucleus::GetMassNumber(), GetParticipant(), GetTotalNumberOfParticipant(), InsertParticipant(), G4QMDGroundStateNucleus::killCMMotionAndAngularM(), G4QMDGroundStateNucleus::packNucleons(), G4QMDGroundStateNucleus::samplingMomentum(), G4QMDGroundStateNucleus::samplingPosition(), SetParticipant(), SetSystem(), ShowParticipants(), and SubtractSystem().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDSystem.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDSystem.cc