ECCE @ EIC Software: MarshaledExN04TrackerHit Class Reference
MarshaledExN04TrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledExN04TrackerHit.h>
Public Member Functions
MarshaledExN04TrackerHit (ExN04TrackerHit *objptr)
MarshaledExN04TrackerHit (void *buf, char chIsUnmarshaling= 'u')
~MarshaledExN04TrackerHit ()
ExN04TrackerHit * unmarshal ()
void unmarshalTo (ExN04TrackerHit *obj)
void marshal1 ()
void unmarshal1 ()
void marshal2 ()
void unmarshal2 ()
Public Member Functions inherited from MarshaledObj
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
Public Attributes
ExN04TrackerHit * param
ShadowedMarshaledExN04TrackerHit * Shadowed_param
Additional Inherited Members
Static Public Member Functions inherited from MarshaledObj
static int ROUND_UP (int x)
static int ROUND_UP (int x)
Protected Attributes inherited from MarshaledObj
int msh_typechoice
char * msh_buffer
char * msh_field_begin
size_t msh_size
char * msh_cursor
size_t msh_extent
bool msh_isUnmarshalDone
Detailed Description
Definition at line 22 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 22 of file MarshaledExN04TrackerHit.h
Constructor & Destructor Documentation
MarshaledExN04TrackerHit::MarshaledExN04TrackerHit (ExN04TrackerHit * objptr) inline
Definition at line 31 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 31 of file MarshaledExN04TrackerHit.h
References marshal1(), marshal2(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledExN04TrackerHit::MarshaledExN04TrackerHit (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 42 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 42 of file MarshaledExN04TrackerHit.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledExN04TrackerHit::~MarshaledExN04TrackerHit () inline
Definition at line 47 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 47 of file MarshaledExN04TrackerHit.h
Member Function Documentation
void MarshaledExN04TrackerHit::marshal1 () inline
Definition at line 86 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 86 of file MarshaledExN04TrackerHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN04TrackerHit::GetPos(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN04TrackerHit().
void MarshaledExN04TrackerHit::marshal2 () inline
Definition at line 143 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 143 of file MarshaledExN04TrackerHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN04TrackerHit::GetEdep(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN04TrackerHit().
ExN04TrackerHit* MarshaledExN04TrackerHit::unmarshal () inline
Definition at line 53 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 53 of file MarshaledExN04TrackerHit.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, unmarshal1(), and unmarshal2().
Referenced by MarshaledG4HitsCollection::unmarshal1().
void MarshaledExN04TrackerHit::unmarshal1 () inline
Definition at line 127 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 127 of file MarshaledExN04TrackerHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN04TrackerHit::SetPos().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN04TrackerHit::unmarshal2 () inline
Definition at line 184 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 184 of file MarshaledExN04TrackerHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN04TrackerHit::SetEdep().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN04TrackerHit::unmarshalTo (ExN04TrackerHit * obj) inline
Definition at line 71 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 71 of file MarshaledExN04TrackerHit.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, unmarshal1(), and unmarshal2().
Member Data Documentation
ExN04TrackerHit* MarshaledExN04TrackerHit::param
Definition at line 24 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 24 of file MarshaledExN04TrackerHit.h
Referenced by marshal1(), marshal2(), MarshaledExN04TrackerHit(), unmarshal(), unmarshal1(), unmarshal2(), and unmarshalTo().
ShadowedMarshaledExN04TrackerHit* MarshaledExN04TrackerHit::Shadowed_param
Definition at line 25 of file MarshaledExN04TrackerHit.h.
View newest version in sPHENIX GitHub at line 25 of file MarshaledExN04TrackerHit.h
Referenced by MarshaledExN04TrackerHit(), unmarshal(), and unmarshalTo().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledExN04TrackerHit.h