ECCE @ EIC Software: G4ProtonEvaporationProbability Class Reference
G4ProtonEvaporationProbability Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4ProtonEvaporationProbability.hh>
Public Member Functions
G4ProtonEvaporationProbability ()
~G4ProtonEvaporationProbability () override
Public Member Functions inherited from G4EvaporationProbability
G4EvaporationProbability (G4int anA, G4int aZ, G4double aGamma)
~G4EvaporationProbability () override
virtual G4double TotalProbability (const G4Fragment &fragment, G4double minKinEnergy, G4double maxKinEnergy, G4double CB, G4double exEnergy)
G4double ComputeProbability (G4double K, G4double CB) override
G4double SampleKineticEnergy (G4double minKinEnergy, G4double maxKinEnergy, G4double CB)
Public Member Functions inherited from G4VEmissionProbability
G4VEmissionProbability (G4int Z, G4int A)
virtual ~G4VEmissionProbability ()
void Initialise ()
virtual G4double EmissionProbability (const G4Fragment &fragment, G4double anEnergy)
G4int GetZ (void) const
G4int GetA (void) const
void SetDecayKinematics (G4int Z, G4int A, G4double rmass, G4double fmass)
G4double GetRecoilExcitation () const
void SetEvapExcitation (G4double exc)
G4double GetProbability () const
void ResetProbability ()
G4double SampleEnergy ()
Protected Member Functions
G4double CalcAlphaParam (const G4Fragment &fragment) override
G4double CalcBetaParam (const G4Fragment &fragment) override
Private Member Functions
G4ProtonEvaporationProbability (const G4ProtonEvaporationProbability &right)
const
G4ProtonEvaporationProbability & operator= (const G4ProtonEvaporationProbability &right)
G4bool operator== (const G4ProtonEvaporationProbability &right) const
G4bool operator!= (const G4ProtonEvaporationProbability &right) const
Additional Inherited Members
Protected Attributes inherited from G4VEmissionProbability
G4int OPTxs
G4int pVerbose
G4int theZ
G4int theA
G4int resZ
G4int resA
G4double pMass
G4double pEvapMass
G4double pResMass
G4double pProbability
G4NuclearLevelData * pNuclearLevelData
G4Pow * pG4pow
Detailed Description
Definition at line 41 of file G4ProtonEvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ProtonEvaporationProbability.hh
Constructor & Destructor Documentation
G4ProtonEvaporationProbability::G4ProtonEvaporationProbability () explicit
Definition at line 38 of file G4ProtonEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 38 of file G4ProtonEvaporationProbability.cc
G4ProtonEvaporationProbability::~G4ProtonEvaporationProbability () override
Definition at line 42 of file G4ProtonEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ProtonEvaporationProbability.cc
G4ProtonEvaporationProbability::G4ProtonEvaporationProbability (const G4ProtonEvaporationProbability & right) private
Member Function Documentation
G4double G4ProtonEvaporationProbability::CalcAlphaParam (const G4Fragment & fragment) override protected virtual
Reimplemented from G4EvaporationProbability.
Definition at line 46 of file G4ProtonEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ProtonEvaporationProbability.cc
References C(), e, G4VEmissionProbability::GetZ(), and G4Fragment::GetZ_asInt().
G4double G4ProtonEvaporationProbability::CalcBetaParam (const G4Fragment & fragment) override protected virtual
Reimplemented from G4EvaporationProbability.
Definition at line 64 of file G4ProtonEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ProtonEvaporationProbability.cc
G4bool G4ProtonEvaporationProbability::operator!= (const G4ProtonEvaporationProbability & right) const private
const G4ProtonEvaporationProbability& G4ProtonEvaporationProbability::operator= (const G4ProtonEvaporationProbability & right) private
G4bool G4ProtonEvaporationProbability::operator== (const G4ProtonEvaporationProbability & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4ProtonEvaporationProbability.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4ProtonEvaporationProbability.cc