ECCE @ EIC Software: G4tgbElement Class Reference
G4tgbElement Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbElement.hh>
Public Member Functions
G4tgbElement ()
~G4tgbElement ()
G4tgbElement (G4tgrElement *hg)
G4Element * BuildG4ElementSimple ()
G4Element * BuildG4ElementFromIsotopes ()
const G4String & GetName () const
const G4String & GetType () const
Private Attributes
G4tgrElement * theTgrElem
G4Element * theG4Elem
Detailed Description
Definition at line 52 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 52 of file G4tgbElement.hh
Constructor & Destructor Documentation
G4tgbElement::G4tgbElement () inline
Definition at line 57 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 57 of file G4tgbElement.hh
G4tgbElement::~G4tgbElement () inline
Definition at line 58 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 58 of file G4tgbElement.hh
G4tgbElement::G4tgbElement (G4tgrElement * hg)
Definition at line 43 of file G4tgbElement.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgbElement.cc
References theG4Elem, and theTgrElem.
Member Function Documentation
G4Element * G4tgbElement::BuildG4ElementFromIsotopes ()
Definition at line 82 of file G4tgbElement.cc.
View newest version in sPHENIX GitHub at line 82 of file G4tgbElement.cc
References G4Element::AddIsotope(), FatalException, G4tgbMaterialMgr::FindOrBuildG4Isotope(), G4cout, G4endl, G4Exception(), G4tgrElementFromIsotopes::GetAbundance(), G4tgrElementFromIsotopes::GetComponent(), G4tgbMaterialMgr::GetInstance(), G4tgrElement::GetName(), G4tgrElementFromIsotopes::GetNumberOfIsotopes(), G4tgrElement::GetSymbol(), G4tgrMessenger::GetVerboseLevel(), theG4Elem, and theTgrElem.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Element().
G4Element * G4tgbElement::BuildG4ElementSimple ()
Definition at line 51 of file G4tgbElement.cc.
View newest version in sPHENIX GitHub at line 51 of file G4tgbElement.cc
References G4cout, G4endl, G4tgrElementSimple::GetA(), G4tgrElement::GetName(), G4tgrElement::GetSymbol(), G4tgrMessenger::GetVerboseLevel(), G4tgrElementSimple::GetZ(), theG4Elem, and theTgrElem.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Element().
const G4String& G4tgbElement::GetName (void) const inline
Definition at line 67 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 67 of file G4tgbElement.hh
References G4tgrElement::GetName(), and theTgrElem.
Referenced by G4tgbMaterialMgr::CopyElements().
const G4String& G4tgbElement::GetType () const inline
Definition at line 71 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgbElement.hh
References G4tgrElement::GetType(), and theTgrElem.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Element().
Member Data Documentation
G4Element* G4tgbElement::theG4Elem private
Definition at line 79 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 79 of file G4tgbElement.hh
Referenced by BuildG4ElementFromIsotopes(), BuildG4ElementSimple(), and G4tgbElement().
G4tgrElement* G4tgbElement::theTgrElem private
Definition at line 78 of file G4tgbElement.hh.
View newest version in sPHENIX GitHub at line 78 of file G4tgbElement.hh
Referenced by BuildG4ElementFromIsotopes(), BuildG4ElementSimple(), G4tgbElement(), GetName(), and GetType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbElement.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbElement.cc