ECCE @ EIC Software: G4MuonicAtom Class Reference
G4MuonicAtom Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonicAtom.hh>
Public Member Functions
G4MuonicAtom (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifeTime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType, G4Ions const *baseion, G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0, G4double DIOLifeTime=-1.0, G4double NCLifeTime=-1.0)
virtual ~G4MuonicAtom ()
G4MuonicAtom * MuonicAtomDefinition ()
G4MuonicAtom * MuonicAtom ()
G4Ions const * GetBaseIon () const
G4double GetDIOLifeTime () const
void SetDIOLifeTime (G4double lt)
G4double GetNCLifeTime () const
void SetNCLifeTime (G4double lt)
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Member Functions
G4MuonicAtom ()
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Private Attributes
G4Ions const * baseIon
G4double fDIOLifeTime
G4double fNCLifeTime
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 41 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 41 of file G4MuonicAtom.hh
Constructor & Destructor Documentation
G4MuonicAtom::G4MuonicAtom () inline protected
Definition at line 44 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 44 of file G4MuonicAtom.hh
Referenced by G4GenericMuonicAtom::Definition().
G4MuonicAtom::G4MuonicAtom (const G4String & aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String & pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifeTime, G4DecayTable * decaytable, G4bool shortlived, const G4String & subType, G4Ions const * baseion, G4int anti_encoding = 0, G4double excitation = 0.0, G4int isomer = 0, G4double DIOLifeTime = -1.0, G4double NCLifeTime = -1.0)
Definition at line 38 of file G4MuonicAtom.cc.
View newest version in sPHENIX GitHub at line 38 of file G4MuonicAtom.cc
References G4ParticleDefinition::isGeneralIon, G4ParticleDefinition::isMuonicAtom, and G4Ions::SetFloatLevelBase().
G4MuonicAtom::~G4MuonicAtom () virtual
Definition at line 70 of file G4MuonicAtom.cc.
View newest version in sPHENIX GitHub at line 70 of file G4MuonicAtom.cc
Member Function Documentation
G4Ions const * G4MuonicAtom::GetBaseIon () const inline
Definition at line 93 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MuonicAtom.hh
References baseIon.
Referenced by G4MuonicAtomDecay::DecayIt().
G4double G4MuonicAtom::GetDIOLifeTime () const inline
Definition at line 99 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 99 of file G4MuonicAtom.hh
References fDIOLifeTime.
Referenced by G4MuonicAtomDecay::DecayIt().
G4double G4MuonicAtom::GetNCLifeTime () const inline
Definition at line 111 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 111 of file G4MuonicAtom.hh
References fNCLifeTime.
Referenced by G4MuonicAtomDecay::DecayIt().
G4MuonicAtom * G4MuonicAtom::MuonicAtom () inline
Definition at line 87 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MuonicAtom.hh
G4MuonicAtom * G4MuonicAtom::MuonicAtomDefinition () inline
Definition at line 81 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 81 of file G4MuonicAtom.hh
void G4MuonicAtom::SetDIOLifeTime (G4double lt) inline
Definition at line 105 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 105 of file G4MuonicAtom.hh
References fDIOLifeTime.
void G4MuonicAtom::SetNCLifeTime (G4double lt) inline
Definition at line 117 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 117 of file G4MuonicAtom.hh
References fNCLifeTime.
Member Data Documentation
G4Ions const* G4MuonicAtom::baseIon private
Definition at line 75 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 75 of file G4MuonicAtom.hh
Referenced by GetBaseIon().
G4double G4MuonicAtom::fDIOLifeTime private
Definition at line 76 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MuonicAtom.hh
Referenced by GetDIOLifeTime(), and SetDIOLifeTime().
G4double G4MuonicAtom::fNCLifeTime private
Definition at line 77 of file G4MuonicAtom.hh.
View newest version in sPHENIX GitHub at line 77 of file G4MuonicAtom.hh
Referenced by GetNCLifeTime(), and SetNCLifeTime().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonicAtom.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4MuonicAtom.cc