ECCE @ EIC Software: F02ElectricFieldSetup Class Reference
F02ElectricFieldSetup Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02ElectricFieldSetup.hh>
Public Member Functions
F02ElectricFieldSetup (G4ThreeVector)
F02ElectricFieldSetup ()
virtual ~F02ElectricFieldSetup ()
void SetStepperType (G4int i)
void SetMinStep (G4double s)
void SetFieldValue (G4ThreeVector fieldVector)
void SetFieldZValue (G4double fieldValue)
G4ThreeVector GetConstantFieldValue ()
void UpdateIntegrator ()
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
void CreateStepper ()
Private Attributes
G4double fMinStep
G4bool fVerbose
G4FieldManager * fFieldManager
G4ChordFinder * fChordFinder
G4EqMagElectricField * fEquation
G4ElectricField * fEMfield
G4ThreeVector fElFieldValue
G4MagIntegratorStepper * fStepper
G4MagInt_Driver * fIntgrDriver
G4int fStepperType
F02FieldMessenger * fFieldMessenger
Detailed Description
A class for control of the Electric Field of the detector. The field for this case is uniform.
The field for this case is uniform. It is simply a 'setup' class that creates the field and necessary other parts
Definition at line 57 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 57 of file F02ElectricFieldSetup.hh
Constructor & Destructor Documentation
F02ElectricFieldSetup::F02ElectricFieldSetup (G4ThreeVector fieldVector)
Definition at line 94 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 94 of file F02ElectricFieldSetup.cc
References fEMfield, fEquation, fFieldManager, fFieldMessenger, GetGlobalFieldManager(), and UpdateIntegrator().
F02ElectricFieldSetup::F02ElectricFieldSetup ()
Definition at line 70 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 70 of file F02ElectricFieldSetup.cc
References cm, fEMfield, fEquation, fFieldManager, fFieldMessenger, GetGlobalFieldManager(), kilovolt, and UpdateIntegrator().
F02ElectricFieldSetup::~F02ElectricFieldSetup () virtual
Definition at line 117 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 117 of file F02ElectricFieldSetup.cc
References fChordFinder, fEMfield, fEquation, fFieldMessenger, and fStepper.
Member Function Documentation
void F02ElectricFieldSetup::CreateStepper () protected
Definition at line 182 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 182 of file F02ElectricFieldSetup.cc
References fEquation, fIntgrDriver, fStepper, fStepperType, G4cout, G4endl, and G4MagInt_Driver::RenewStepperAndAdjust().
Referenced by SetStepperType(), and UpdateIntegrator().
G4ThreeVector F02ElectricFieldSetup::GetConstantFieldValue ()
G4FieldManager * F02ElectricFieldSetup::GetGlobalFieldManager () protected
Definition at line 288 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 288 of file F02ElectricFieldSetup.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by F02ElectricFieldSetup(), and SetFieldValue().
void F02ElectricFieldSetup::SetFieldValue (G4ThreeVector fieldVector)
Definition at line 263 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 263 of file F02ElectricFieldSetup.cc
References fEMfield, fEquation, GetGlobalFieldManager(), G4FieldManager::SetDetectorField(), and G4EquationOfMotion::SetFieldObj().
Referenced by SetFieldZValue(), and F02FieldMessenger::SetNewValue().
void F02ElectricFieldSetup::SetFieldZValue (G4double fieldValue)
Definition at line 252 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 252 of file F02ElectricFieldSetup.cc
References SetFieldValue().
Referenced by F02FieldMessenger::SetNewValue().
void F02ElectricFieldSetup::SetMinStep (G4double s) inline
Definition at line 68 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 68 of file F02ElectricFieldSetup.hh
References fMinStep.
Referenced by F02FieldMessenger::SetNewValue().
void F02ElectricFieldSetup::SetStepperType (G4int i) inline
Definition at line 66 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 66 of file F02ElectricFieldSetup.hh
References CreateStepper(), and fStepperType.
Referenced by F02FieldMessenger::SetNewValue().
void F02ElectricFieldSetup::UpdateIntegrator ()
Definition at line 132 of file F02ElectricFieldSetup.cc.
View newest version in sPHENIX GitHub at line 132 of file F02ElectricFieldSetup.cc
References CreateStepper(), fChordFinder, fEMfield, fEquation, fFieldManager, fIntgrDriver, fMinStep, fStepper, G4cout, G4endl, G4MagIntegratorStepper::GetNumberOfVariables(), mm, G4FieldManager::SetChordFinder(), and G4FieldManager::SetDetectorField().
Referenced by F02ElectricFieldSetup(), and F02FieldMessenger::SetNewValue().
Member Data Documentation
G4ChordFinder* F02ElectricFieldSetup::fChordFinder private
Definition at line 95 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 95 of file F02ElectricFieldSetup.hh
Referenced by UpdateIntegrator(), and ~F02ElectricFieldSetup().
G4ThreeVector F02ElectricFieldSetup::fElFieldValue private
Definition at line 101 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 101 of file F02ElectricFieldSetup.hh
G4ElectricField* F02ElectricFieldSetup::fEMfield private
Definition at line 99 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 99 of file F02ElectricFieldSetup.hh
Referenced by F02ElectricFieldSetup(), SetFieldValue(), UpdateIntegrator(), and ~F02ElectricFieldSetup().
G4EqMagElectricField* F02ElectricFieldSetup::fEquation private
Definition at line 97 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 97 of file F02ElectricFieldSetup.hh
Referenced by CreateStepper(), F02ElectricFieldSetup(), SetFieldValue(), UpdateIntegrator(), and ~F02ElectricFieldSetup().
G4FieldManager* F02ElectricFieldSetup::fFieldManager private
Definition at line 93 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 93 of file F02ElectricFieldSetup.hh
Referenced by F02ElectricFieldSetup(), and UpdateIntegrator().
F02FieldMessenger* F02ElectricFieldSetup::fFieldMessenger private
Definition at line 109 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 109 of file F02ElectricFieldSetup.hh
Referenced by F02ElectricFieldSetup(), and ~F02ElectricFieldSetup().
G4MagInt_Driver* F02ElectricFieldSetup::fIntgrDriver private
Definition at line 104 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 104 of file F02ElectricFieldSetup.hh
Referenced by CreateStepper(), and UpdateIntegrator().
G4double F02ElectricFieldSetup::fMinStep private
Definition at line 90 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 90 of file F02ElectricFieldSetup.hh
Referenced by SetMinStep(), and UpdateIntegrator().
G4MagIntegratorStepper* F02ElectricFieldSetup::fStepper private
Definition at line 103 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 103 of file F02ElectricFieldSetup.hh
Referenced by CreateStepper(), UpdateIntegrator(), and ~F02ElectricFieldSetup().
G4int F02ElectricFieldSetup::fStepperType private
Definition at line 106 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 106 of file F02ElectricFieldSetup.hh
Referenced by CreateStepper(), and SetStepperType().
G4bool F02ElectricFieldSetup::fVerbose private
Definition at line 91 of file F02ElectricFieldSetup.hh.
View newest version in sPHENIX GitHub at line 91 of file F02ElectricFieldSetup.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02ElectricFieldSetup.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field02/src/F02ElectricFieldSetup.cc