ECCE @ EIC Software: G4RDAtomicDeexcitation Class Reference
G4RDAtomicDeexcitation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAtomicDeexcitation.hh>
Public Member Functions
G4RDAtomicDeexcitation ()
~G4RDAtomicDeexcitation ()
std::vector< G4DynamicParticle * > * GenerateParticles (G4int Z, G4int shellId)
void SetCutForSecondaryPhotons (G4double cut)
void SetCutForAugerElectrons (G4double cut)
void ActivateAugerElectronProduction (G4bool val)
Private Member Functions
G4int SelectTypeOfTransition (G4int Z, G4int shellId)
G4DynamicParticle * GenerateFluorescence (G4int Z, G4int shellId, G4int provShellId)
G4DynamicParticle * GenerateAuger (G4int Z, G4int shellId)
Private Attributes
G4int newShellId
G4double minGammaEnergy
G4double minElectronEnergy
G4bool fAuger
G4int augerVacancyId
Detailed Description
Definition at line 51 of file G4RDAtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RDAtomicDeexcitation.hh
Constructor & Destructor Documentation
G4RDAtomicDeexcitation::G4RDAtomicDeexcitation ()
Definition at line 48 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 48 of file G4RDAtomicDeexcitation.cc
G4RDAtomicDeexcitation::~G4RDAtomicDeexcitation ()
Definition at line 54 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 54 of file G4RDAtomicDeexcitation.cc
Member Function Documentation
void G4RDAtomicDeexcitation::ActivateAugerElectronProduction (G4bool val)
Definition at line 505 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 505 of file G4RDAtomicDeexcitation.cc
References fAuger.
Referenced by G4LowEnergyPhotoElectric::ActivateAuger(), and G4LowEnergyIonisation::ActivateAuger().
G4DynamicParticle * G4RDAtomicDeexcitation::GenerateAuger (G4int Z, G4int shellId) private
Definition at line 275 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 275 of file G4RDAtomicDeexcitation.cc
References G4RDAugerTransition::AugerTransitionEnergy(), G4RDAugerTransition::AugerTransitionProbabilities(), G4RDAugerTransition::AugerTransitionProbability(), G4Electron::Electron(), FatalException, fAuger, G4RDAugerTransition::FinalShellId(), G4Exception(), G4UniformRand, G4RDAtomicTransitionManager::Instance(), newShellId, G4RDAtomicTransitionManager::NumberOfReachableAugerShells(), pos(), G4RDAtomicTransitionManager::ReachableAugerShell(), G4RDAugerTransition::TransitionOriginatingShellIds(), and twopi.
Referenced by GenerateParticles().
G4DynamicParticle * G4RDAtomicDeexcitation::GenerateFluorescence (G4int Z, G4int shellId, G4int provShellId) private
Definition at line 209 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 209 of file G4RDAtomicDeexcitation.cc
References G4UniformRand, G4Gamma::Gamma(), G4RDAtomicTransitionManager::Instance(), newShellId, G4RDAtomicTransitionManager::NumberOfReachableShells(), and twopi.
Referenced by GenerateParticles().
std::vector< G4DynamicParticle * > * G4RDAtomicDeexcitation::GenerateParticles (G4int Z, G4int shellId)
Definition at line 57 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 57 of file G4RDAtomicDeexcitation.cc
References FatalException, G4Exception(), GenerateAuger(), GenerateFluorescence(), newShellId, and SelectTypeOfTransition().
Referenced by G4LowEnergyIonisation::DeexciteAtom(), G4LowEnergyPhotoElectric::PostStepDoIt(), and G4LowEnergyIonisation::PostStepDoIt().
G4int G4RDAtomicDeexcitation::SelectTypeOfTransition (G4int Z, G4int shellId) private
Definition at line 134 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 134 of file G4RDAtomicDeexcitation.cc
References FatalException, G4RDFluoTransition::FinalShellId(), G4Exception(), G4UniformRand, G4RDAtomicTransitionManager::Instance(), G4RDAtomicTransitionManager::NumberOfReachableShells(), G4RDFluoTransition::OriginatingShellId(), G4RDAtomicTransitionManager::ReachableShell(), G4RDFluoTransition::TransitionProbabilities(), and G4RDFluoTransition::TransitionProbability().
Referenced by GenerateParticles().
void G4RDAtomicDeexcitation::SetCutForAugerElectrons (G4double cut)
Definition at line 500 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 500 of file G4RDAtomicDeexcitation.cc
References minElectronEnergy.
Referenced by G4LowEnergyPhotoElectric::SetCutForLowEnSecElectrons(), and G4LowEnergyIonisation::SetCutForLowEnSecElectrons().
void G4RDAtomicDeexcitation::SetCutForSecondaryPhotons (G4double cut)
Definition at line 495 of file G4RDAtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 495 of file G4RDAtomicDeexcitation.cc
References minGammaEnergy.
Referenced by G4LowEnergyPhotoElectric::SetCutForLowEnSecPhotons(), and G4LowEnergyIonisation::SetCutForLowEnSecPhotons().
Member Data Documentation
G4int G4RDAtomicDeexcitation::augerVacancyId private
Definition at line 94 of file G4RDAtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RDAtomicDeexcitation.hh
G4bool G4RDAtomicDeexcitation::fAuger private
Definition at line 90 of file G4RDAtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RDAtomicDeexcitation.hh
Referenced by ActivateAugerElectronProduction(), and GenerateAuger().
G4double G4RDAtomicDeexcitation::minElectronEnergy private
Definition at line 89 of file G4RDAtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RDAtomicDeexcitation.hh
Referenced by SetCutForAugerElectrons().
G4double G4RDAtomicDeexcitation::minGammaEnergy private
Definition at line 88 of file G4RDAtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RDAtomicDeexcitation.hh
Referenced by SetCutForSecondaryPhotons().
G4int G4RDAtomicDeexcitation::newShellId private
Definition at line 86 of file G4RDAtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RDAtomicDeexcitation.hh
Referenced by GenerateAuger(), GenerateFluorescence(), and GenerateParticles().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAtomicDeexcitation.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDAtomicDeexcitation.cc