ECCE @ EIC Software: RunAction Class Reference
RunAction Class Reference
Run action class.
#include <geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/RunAction.hh>
Inherits G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, G4UserRunAction, and G4UserRunAction.
Classes
struct MinMaxData
class ParticleStatistics
Public Member Functions
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
void GetCuts ()
void CriticalEnergy ()
RunAction (DetectorConstruction *det, PrimaryGeneratorAction *prim=0)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (const DetectorConstruction *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetRndmFreq (G4int val)
G4int GetRndmFreq () const
void AddDoseN (G4double dose)
void SetDoseN (G4double dose)
G4double GetDoseN () const
void AddDoseC (G4double dose)
void SetDoseC (G4double dose)
G4double GetDoseC () const
G4int GetNumEvent () const
void SetNumEvent (G4int i)
G4int GetNbOfHitsGas () const
void AddNbOfHitsGas ()
void SetMassNucleus (G4double mN)
G4double GetMassNucleus () const
void SetMassCytoplasm (G4double mC)
G4double GetMassCytoplasm () const
void AddDoseBox (G4int i, G4double x)
G4double GetDoseBox (G4int i) const
G4ThreeVector GetVectCell (G4int i) const
RunAction ()
~RunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
G4int GetRow ()
void AddRow ()
void AddToXVector (float v)
void AddToYVector (float v)
void AddToThetaVector (float v)
void AddToPhiVector (float v)
RunAction ()
~RunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
RunAction (HistoManager *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void FillPerEvent (G4double, G4double, G4double, G4double)
RunAction (HistoManager *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void FillPerEvent (G4double, G4double, G4double, G4double)
RunAction (HistoManager *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void FillPerEvent (G4double, G4double, G4double, G4double)
RunAction (HistoManager *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void FillPerEvent (G4double, G4double, G4double, G4double)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void GetCuts ()
void CriticalEnergy ()
RunAction (const DetectorConstruction *det, PrimaryGeneratorAction *prim=nullptr)
~RunAction () override
G4Run * GenerateRun () override
void BeginOfRunAction (const G4Run *) override
void EndOfRunAction (const G4Run *) override
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetRndmFreq (G4int val)
G4int GetRndmFreq ()
RunAction (DetectorConstruction *, PhysicsList *, PrimaryGeneratorAction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction (DetectorConstruction *, PhysicsList *, PrimaryGeneratorAction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *det, PrimaryGeneratorAction *prim=0)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CountProcesses (G4String)
void SumPathLength (G4double truepl, G4double geompl)
void SumLateralDisplacement (G4double displa)
void SumPsi (G4double psi)
void SumTetaPlane (G4double teta)
void SumPhiCorrel (G4double correl)
G4double ComputeMscHighland (G4double pathLength)
RunAction ()
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *, HistoManager *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CountProcesses (const G4String &)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CountProcesses (G4String procName)
void TrackLength (G4double step)
void EnergyDeposited (G4double edepPrim, G4double edepSecond)
void EnergyTransferedByProcess (G4String procName, G4double energy)
void EnergyTransfered (G4double energy)
void TotalEnergyLost (G4double energy)
void EnergyBalance (G4double energy)
void TotalEnergyDeposit (G4double energy)
void EnergySpectrumOfSecondaries (G4String particleName, G4double ekin)
G4double GetEnergyFromRestrictedRange (G4double, G4ParticleDefinition *, G4Material *, G4double)
G4double GetEnergyFromCSDARange (G4double, G4ParticleDefinition *, G4Material *, G4double)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetVerbose (G4int val)
void SetHistoName (G4String &val)
void SetEdepAndRMS (G4ThreeVector)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *prim=0)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetEdepAndRMS (G4int, G4double, G4double, G4double)
void SetApplyLimit (G4bool val)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *det, PrimaryGeneratorAction *prim=0)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CountProcesses (G4String)
RunAction (DetectorConstruction *, PhysicsList *, PrimaryGeneratorAction *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void FillTallyEdep (G4int n, G4double e)
void FillEdep (G4double de, G4double eni)
void AddProjRange (G4double x)
void AddPrimaryStep ()
RunAction ()
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetBinSize (G4double size)
RunAction (const DetectorConstruction *det=0)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetPrintFlag (G4bool)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CreateHistogram ()
void WriteHistogram ()
void SetHistoName (G4String &val)
RunAction ()
~RunAction () override
void BeginOfRunAction (const G4Run *) override
void EndOfRunAction (const G4Run *) override
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *run)
virtual void EndOfRunAction (const G4Run *run)
RunAction (PrimaryGeneratorAction *prim=0)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *run)
virtual void EndOfRunAction (const G4Run *run)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *run)
virtual void EndOfRunAction (const G4Run *run)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetRndmFreq (G4int val)
G4int GetRndmFreq ()
virtual G4Run * GenerateRun ()
G4double GetEdepALL ()
void SetEdepALL (G4double vall)
void AddEdepALL (G4double vall)
G4double GetEdepMedium ()
void SetEdepMedium (G4double vall)
void AddEdepMedium (G4double vall)
G4double GetEdepSlice ()
void SetEdepSlice (G4double vall)
void AddEdepSlice (G4double vall)
G4double GetEdepSoma ()
void SetEdepSoma (G4double vall)
void AddEdepSoma (G4double vall)
G4double GetEdepDend ()
void SetEdepDend (G4double vall)
void AddEdepDend (G4double vall)
G4double GetEdepAxon ()
void SetEdepAxon (G4double vall)
void AddEdepAxon (G4double vall)
G4double GetEdepNeuron ()
void SetEdepNeuron (G4double vall)
void AddEdepNeuron (G4double vall)
G4int GetNumEvent ()
void SetNumEvent (G4int i)
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction ()
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction (DetectorConstruction *, PrimaryGeneratorAction *prim=0)
~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *prim)
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
RunAction (PrimaryGeneratorAction *=nullptr)
virtual ~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction ()
~RunAction ()
virtual void BeginOfRunAction (const G4Run *arun)
virtual void EndOfRunAction (const G4Run *arun)
RunAction ()
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *arun)
virtual void EndOfRunAction (const G4Run *arun)
RunAction (G4bool useNtuple, G4bool mergeNtuple)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *arun)
virtual void EndOfRunAction (const G4Run *arun)
RunAction (const G4String &fileName)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (const G4String &fileName)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (const G4String &fileName)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (const G4String &fileName)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
virtual ~RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CountProcesses (G4String)
void FillData (const G4ParticleDefinition *particle, G4double kinEnergy, G4double costheta, G4double phi, G4double longitudinalPolarization)
void EventFinished ()
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
RunAction (DetectorConstruction *, PrimaryGeneratorAction *)
~RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Member Functions
void CreateHistogram ()
void WriteHistogram ()
void BeginMaster (const G4Run *)
void EndMaster (const G4Run *)
void InitializeWorker (const G4Run *)
void BeginWorker (const G4Run *)
void EndWorker (const G4Run *)
void PrintRunInfo (const G4Run *run)
void BookHisto ()
G4double ComputeTheory (const G4String &, G4int)
G4double GetEnergyCut (const G4Material *, G4int)
void BookHisto ()
void BookHisto ()
void Book ()
void Book ()
void Book ()
void CreateNtuple (const G4String &fileName)
void WriteNtuple ()
void CreateHistogram ()
void WriteHistogram ()
void BeginMaster (const G4Run *)
void EndMaster (const G4Run *)
void InitializeWorker (const G4Run *)
void BeginWorker (const G4Run *)
void EndWorker (const G4Run *)
void PrintRunInfo (const G4Run *run)
void CreateHistogram ()
void WriteHistogram ()
void PrintRunInfo (const G4Run *run)
void CreateNtuple ()
void WriteNtuple ()
void BeginMaster (const G4Run *)
void EndMaster (const G4Run *)
void InitializeWorker (const G4Run *)
void BeginWorker (const G4Run *)
void EndWorker (const G4Run *)
void PrintRunInfo (const G4Run *run)
void BookHisto ()
void SaveHisto (G4int nevents)
Private Attributes
DetectorConstruction * detector
PrimaryGeneratorAction * primary
G4double rangeCut [3]
G4double energyCut [3]
DetectorConstruction * fDetector
PrimaryGeneratorAction * fPrimary
Run * fRun
HistoManager * fHistoManager
const DetectorConstruction * fDetector
G4int fSaveRndm
G4int fNumEvent
G4int fNbOfPixels
G4int fNbOfHitsGas
G4double fDoseN
G4double fDoseC
G4double fMassCytoplasm
G4double fMassNucleus
G4double * fDose3DDose
G4ThreeVector * fMapVoxels
TrackingAction * fpTrackingAction
G4String fFileName
bool fInitialized
bool fDebug
G4int fRow
CLHEP::HepVector fXVector
CLHEP::HepVector fYVector
CLHEP::HepVector fThetaVector
CLHEP::HepVector fPhiVector
CLHEP::HepMatrix fBeamMatrix
G4double fSumEAbs
G4double fSum2EAbs
G4double fSumEGap
G4double fSum2EGap
G4double fSumLAbs
G4double fSum2LAbs
G4double fSumLGap
G4double fSum2LGap
G4double fRangeCut [3]
G4double fEnergyCut [3]
RunMessenger * fRunMessenger
G4int fRndmFreq
PhysicsList * fPhysics
ProcessesCount * fProcCounter
G4int fTotalCount
G4double fTruePL
G4double fTruePL2
G4double fGeomPL
G4double fGeomPL2
G4double fLDispl
G4double fLDispl2
G4double fPsiSpa
G4double fPsiSpa2
G4double fTetPrj
G4double fTetPrj2
G4double fPhiCor
G4double fPhiCor2
MuCrossSections * fMucs
std::map< G4String, G4int > fProcCounter
G4long fNbSteps
G4double fTrackLength
G4double fStepMin
G4double fStepMax
G4double fEdepPrimary
G4double fEdepPrimMin
G4double fEdepPrimMax
std::map< G4String, MinMaxData > fEtransfByProcess
G4double fEnergyTransfered
G4double fEtransfMin
G4double fEtransfMax
G4double fEnergyLost
G4double fElostMin
G4double fElostMax
G4double fEnergyBalance
G4double fEbalMin
G4double fEbalMax
G4double fEdepSecondary
G4double fEdepSecMin
G4double fEdepSecMax
G4double fEdepTotal
G4double fEdepTotMin
G4double fEdepTotMax
std::map< G4String, MinMaxData > fEkinOfSecondaries
DetectorConstruction * fDet
PrimaryGeneratorAction * fKin
RunActionMessenger * fRunMessenger
G4AnalysisManager * fAnalysisManager
G4int fVerbose
G4String fHistoName [2]
G4double fEdeptrue
G4double fRmstrue
G4double fLimittrue
G4Timer * fTimer
G4AnalysisManager * fAnalysis
G4Material * fMat
G4double fMinE
G4double fMaxE
G4int fnBin
G4int fNtColId [3]
PrimaryGeneratorAction * fKinematic
G4double * fTallyEdep
G4double fProjRange
G4double fProjRange2
G4double fEdeptot
G4double fEniel
G4int fNbPrimarySteps
G4int fRange
RunActionMessenger * fMessenger
G4double fBinLength
HistoManager * fHisto
G4bool fPrint
RunActionMessenger * fpRunMessenger
G4double fEdepAll
G4double fEdepAll_err
G4double fEdepMedium
G4double fEdepMedium_err
G4double fEdepSlice
G4double fEdepSlice_err
G4double fEdepSoma
G4double fEdepSoma_err
G4double fEdepDend
G4double fEdepDend_err
G4double fEdepAxon
G4double fEdepAxon_err
G4double fEdepNeuron
G4double fEdepNeuron_err
const DetectorConstruction * fpDetector
Run * fpRun
HistoManager * fpHistoManager
const G4ParticleDefinition * fGamma
const G4ParticleDefinition * fElectron
const G4ParticleDefinition * fPositron
G4int fTotalEventCount
ParticleStatistics fPhotonStats
ParticleStatistics fElectronStats
ParticleStatistics fPositronStats
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Run action class.
Run action class
It accumulates statistic and computes dispersion of the energy deposit and track lengths of charged particles with use of analysis tools: H1D histograms are created in BeginOfRunAction() for the following physics quantities:
Edep in absorber
Edep in gap
Track length in absorber
Track length in gap The same values are also saved in the ntuple. The histograms and ntuple are saved in the output file in a format accoring to a selected technology in Analysis.hh.
In EndOfRunAction(), the accumulated statistic and computed dispersion is printed.
Definition at line 44 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 44 of file RunAction.hh
Constructor & Destructor Documentation
RunAction::RunAction (DetectorConstruction * det, PrimaryGeneratorAction * kin)
Definition at line 45 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 45 of file RunAction.cc
RunAction::~RunAction ()
Definition at line 51 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file RunAction.cc
RunAction::RunAction (DetectorConstruction * det, PrimaryGeneratorAction * prim = 0)
RunAction::~RunAction ()
RunAction::RunAction (const DetectorConstruction * det)
Definition at line 43 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 43 of file RunAction.cc
References fSaveRndm.
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
Definition at line 41 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 41 of file RunAction.cc
References fDebug, fFileName, fInitialized, and fpTrackingAction.
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction (HistoManager * histo)
Definition at line 43 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 43 of file RunAction.cc
virtual RunAction::~RunAction () virtual
RunAction::RunAction (HistoManager *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (HistoManager *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (HistoManager *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (const DetectorConstruction * det, PrimaryGeneratorAction * prim = nullptr)
Definition at line 45 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 45 of file RunAction.cc
References fHistoManager.
RunAction::~RunAction () override
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * det, PhysicsList * phys, PrimaryGeneratorAction * kin)
Definition at line 50 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 50 of file RunAction.cc
References fHistoManager.
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PhysicsList * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * det, PrimaryGeneratorAction * prim = 0)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * det, PrimaryGeneratorAction * prim, HistoManager * HistM)
Definition at line 51 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file RunAction.cc
References fMucs.
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction * prim = 0)
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * det, PrimaryGeneratorAction * prim = 0)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * det)
Definition at line 55 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 55 of file RunAction.cc
References fMaxE, fMinE, fnBin, fNtColId, and GeV.
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PhysicsList * , PrimaryGeneratorAction *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (const DetectorConstruction * det = 0)
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
RunAction::~RunAction () override
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction (PrimaryGeneratorAction * prim = 0)
Definition at line 42 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 42 of file RunAction.cc
References fDetector, fHistoManager, G4RunManager::GetRunManager(), and G4RunManager::GetUserDetectorConstruction().
RunAction::~RunAction ()
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction * prim = 0)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction * prim)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (PrimaryGeneratorAction * = nullptr)
virtual RunAction::~RunAction () virtual
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction ()
RunAction::~RunAction ()
RunAction::RunAction (G4bool useNtuple, G4bool mergeNtuple)
Definition at line 43 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 43 of file RunAction.cc
References Analysis::Book(), G4cout, G4endl, Analysis::GetAnalysis(), G4MPImanager::GetManager(), Analysis::SetMergeNtuple(), and Analysis::SetUseNtuple().
RunAction::~RunAction ()
RunAction::RunAction (const G4String & fileName)
Definition at line 40 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 40 of file RunAction.cc
References fFileName, G4cout, G4endl, and G4ToolsAnalysisManager::Instance().
virtual RunAction::~RunAction () virtual
RunAction::RunAction (const G4String & fileName)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (const G4String & fileName)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (const G4String & fileName)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
virtual RunAction::~RunAction () virtual
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (PrimaryGeneratorAction *)
RunAction::~RunAction ()
RunAction::RunAction (DetectorConstruction * , PrimaryGeneratorAction *)
RunAction::~RunAction ()
Member Function Documentation
void RunAction::AddDoseBox (G4int i, G4double x) inline
Definition at line 80 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 80 of file RunAction.hh
References fDose3DDose, and x.
void RunAction::AddDoseC (G4double dose) inline
Definition at line 64 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RunAction.hh
References dose, and fDoseC.
void RunAction::AddDoseN (G4double dose) inline
Definition at line 60 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file RunAction.hh
References dose, and fDoseN.
void RunAction::AddEdepALL (G4double vall) inline
Definition at line 75 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 75 of file RunAction.hh
References fEdepAll, and fEdepAll_err.
void RunAction::AddEdepAxon (G4double vall) inline
Definition at line 117 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 117 of file RunAction.hh
References fEdepAxon, and fEdepAxon_err.
void RunAction::AddEdepDend (G4double vall) inline
Definition at line 108 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 108 of file RunAction.hh
References fEdepDend, and fEdepDend_err.
void RunAction::AddEdepMedium (G4double vall) inline
Definition at line 83 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 83 of file RunAction.hh
References fEdepMedium, and fEdepMedium_err.
void RunAction::AddEdepNeuron (G4double vall) inline
Definition at line 126 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 126 of file RunAction.hh
References fEdepNeuron, and fEdepNeuron_err.
void RunAction::AddEdepSlice (G4double vall) inline
Definition at line 91 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 91 of file RunAction.hh
References fEdepSlice, and fEdepSlice_err.
void RunAction::AddEdepSoma (G4double vall) inline
Definition at line 99 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 99 of file RunAction.hh
References fEdepSoma, and fEdepSoma_err.
void RunAction::AddNbOfHitsGas () inline
Definition at line 72 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RunAction.hh
References fNbOfHitsGas.
void RunAction::AddPrimaryStep () inline
Definition at line 105 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 105 of file RunAction.hh
References fNbPrimarySteps.
void RunAction::AddProjRange (G4double x) inline
Definition at line 96 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 96 of file RunAction.hh
References fProjRange, fProjRange2, fRange, and x.
void RunAction::AddRow () inline
Definition at line 53 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 53 of file RunAction.hh
References fRow.
void RunAction::AddToPhiVector (float v) inline
Definition at line 58 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file RunAction.hh
References fPhiVector, fRow, and v.
void RunAction::AddToThetaVector (float v) inline
Definition at line 57 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 57 of file RunAction.hh
References fRow, fThetaVector, and v.
void RunAction::AddToXVector (float v) inline
Definition at line 55 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 55 of file RunAction.hh
References fRow, fXVector, and v.
void RunAction::AddToYVector (float v) inline
Definition at line 56 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file RunAction.hh
References fRow, fYVector, and v.
void RunAction::BeginMaster (const G4Run * run) private
Definition at line 83 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 83 of file RunAction.cc
References CreateHistogram(), fDebug, fInitialized, G4cout, G4endl, G4RunManager::GetRunManager(), G4RunManager::GetRunManagerType(), InitializeWorker(), PrintRunInfo(), and G4RunManager::sequentialRM.
void RunAction::BeginMaster (const G4Run *) private
void RunAction::BeginMaster (const G4Run *) private
virtual void RunAction::BeginOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run *) override virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run * run) virtual
G4cout << "\n&mdash;> stepMax from histos 1 and 8 = " << G4BestUnit(stepMax,"Length") << G4endl;
Reimplemented from G4UserRunAction.
Definition at line 56 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 56 of file RunAction.cc
References A(), charge, cm, G4EmCalculator::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4EmCalculator::ComputeDEDX(), CriticalEnergy(), DBL_MAX, detector, G4Electron::Electron(), energy, energyCut, fElectromagnetic, G4BestUnit, G4cout, G4endl, G4Material::GetA(), G4EmCalculator::GetCrossSectionPerVolume(), G4EmCalculator::GetCSDARange(), GetCuts(), G4EmCalculator::GetDEDX(), G4Material::GetDensity(), DetectorConstruction::GetMaterial(), G4EmCalculator::GetMeanFreePath(), G4Material::GetName(), G4Material::GetNumberOfElements(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), PrimaryGeneratorAction::GetParticleGun(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4Material::GetRadlen(), G4EmCalculator::GetRangeFromRestricteDEDX(), G4Material::GetZ(), G4InuclParticleNames::lambda, BTOF::length, material(), particle, CLHEP::prec, primary, rangeCut, G4ProcessVector::size(), and Z.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run *) override virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::BeginWorker (const G4Run * run) private
Definition at line 108 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 108 of file RunAction.cc
References CreateHistogram(), fDebug, fInitialized, G4cout, G4endl, InitializeWorker(), and PrintRunInfo().
void RunAction::BeginWorker (const G4Run *) private
void RunAction::BeginWorker (const G4Run *) private
void RunAction::Book () private
void RunAction::Book () private
Definition at line 68 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 68 of file RunAction.cc
References G4VAnalysisManager::CreateH1(), fAnalysisManager, TestParameters::GetFactorALICE(), TestParameters::GetMaxCluster(), TestParameters::GetMaxEnergy(), TestParameters::GetNumberBins(), TestParameters::GetNumberBinsCluster(), TestParameters::GetPointer(), keV, G4VAnalysisManager::OpenFile(), and G4VAnalysisManager::SetFirstHistoId().
void RunAction::Book () private
void RunAction::BookHisto () private
fHistoName[0] = "testem2";
Definition at line 64 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 64 of file RunAction.cc
References G4VAnalysisManager::CreateH1(), G4ToolsAnalysisManager::Instance(), k, kMaxHisto, G4VAnalysisManager::SetActivation(), G4VAnalysisManager::SetFileName(), G4VAnalysisManager::SetFirstHistoId(), G4VAnalysisManager::SetH1Activation(), G4VAnalysisManager::SetVerboseLevel(), and title().
void RunAction::BookHisto () private
void RunAction::BookHisto () private
void RunAction::BookHisto () private
G4double RunAction::ComputeMscHighland (G4double pathLength)
Definition at line 233 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 233 of file RunAction.cc
References kdfinder::abs(), DBL_MIN, eplus, fDetector, fPrimary, DetectorConstruction::GetMaterial(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), PrimaryGeneratorAction::GetParticleGun(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Material::GetRadlen(), MeV, T, t, and z.
G4double RunAction::ComputeTheory (const G4String & process, G4int NbOfMu) private
Definition at line 183 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 183 of file RunAction.cc
References MuCrossSections::CR_Macroscopic(), source.hepunit::electron_mass_c2, fDetector, fHistoManager, fMucs, fPrimary, HistoManager::GetBinWidth(), GetEnergyCut(), G4ToolsAnalysisManager::GetH1(), HistoManager::GetHistoID(), DetectorConstruction::GetMaterial(), HistoManager::GetNbins(), G4ParticleGun::GetParticleEnergy(), PrimaryGeneratorAction::GetParticleGun(), DetectorConstruction::GetSize(), HistoManager::GetVmax(), HistoManager::GetVmin(), HistoManager::HistoExist(), G4ToolsAnalysisManager::Instance(), ln10, and MeV.
void RunAction::CountProcesses (G4String)
void RunAction::CountProcesses (G4String procName)
Definition at line 90 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 90 of file RunAction.cc
References fProcCounter.
void RunAction::CountProcesses (const G4String & procName)
Definition at line 81 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 81 of file RunAction.cc
References OneProcessCount::Count(), fProcCounter, and n.
void RunAction::CountProcesses (G4String procName)
void RunAction::CountProcesses (G4String)
void RunAction::CreateHistogram ()
void RunAction::CreateHistogram () private
Definition at line 204 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 204 of file RunAction.cc
References G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), fFileName, G4VAnalysisManager::FinishNtuple(), G4cout, G4endl, G4VAnalysisManager::GetType(), G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), and G4VAnalysisManager::SetVerboseLevel().
Referenced by BeginMaster(), and BeginWorker().
void RunAction::CreateHistogram () private
void RunAction::CreateHistogram () private
void RunAction::CreateNtuple (const G4String & fileName) private
Definition at line 61 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 61 of file RunAction.cc
References G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4VAnalysisManager::CreateNtupleSColumn(), G4VAnalysisManager::FinishNtuple(), G4cout, G4endl, G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), G4VAnalysisManager::SetFirstNtupleId(), G4VAnalysisManager::SetNtupleDirectoryName(), and G4VAnalysisManager::SetVerboseLevel().
void RunAction::CreateNtuple () private
Definition at line 179 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 179 of file RunAction.cc
References G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::FinishNtuple(), G4cout, G4endl, G4DNAPARSER::CommandLineParser::GetCommandIfActive(), G4DNAPARSER::Command::GetOption(), G4VAnalysisManager::GetType(), G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), parser(), and G4VAnalysisManager::SetVerboseLevel().
void RunAction::CriticalEnergy ()
Definition at line 299 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 299 of file RunAction.cc
References kdfinder::abs(), G4EmCalculator::ComputeDEDX(), detector, G4Electron::Electron(), check_license::err(), G4BestUnit, G4cout, DetectorConstruction::GetMaterial(), G4Material::GetNumberOfElements(), G4Material::GetRadlen(), G4Material::GetState(), G4Material::GetZ(), kStateGas, material(), and MeV.
Referenced by BeginOfRunAction().
void RunAction::CriticalEnergy ()
void RunAction::EndMaster (const G4Run * run) private
Definition at line 125 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 125 of file RunAction.cc
References EndWorker(), G4RunManager::GetRunManager(), G4RunManager::GetRunManagerType(), and G4RunManager::sequentialRM.
void RunAction::EndMaster (const G4Run *) private
void RunAction::EndMaster (const G4Run *) private
virtual void RunAction::EndOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run *) override virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 259 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 259 of file RunAction.cc
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run *) override virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void RunAction::EndWorker (const G4Run * run) private
Definition at line 135 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 135 of file RunAction.cc
References fDebug, fpTrackingAction, G4cout, G4endl, TrackingAction::GetNParticlesCreatedInTarget(), TrackingAction::GetNParticlesCreatedInWorld(), G4Run::GetNumberOfEvent(), G4ToolsAnalysisManager::Instance(), PrintNParticles(), PrintRunInfo(), and WriteHistogram().
Referenced by EndMaster().
void RunAction::EndWorker (const G4Run *) private
void RunAction::EndWorker (const G4Run *) private
void RunAction::EnergyBalance (G4double energy)
Definition at line 173 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 173 of file RunAction.cc
References energy, fEbalMax, fEbalMin, and fEnergyBalance.
void RunAction::EnergyDeposited (G4double edepPrim, G4double edepSecond)
Definition at line 122 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 122 of file RunAction.cc
References fEdepPrimary, fEdepPrimMax, fEdepPrimMin, fEdepSecMax, fEdepSecMin, and fEdepSecondary.
void RunAction::EnergySpectrumOfSecondaries (G4String particleName, G4double ekin)
Definition at line 191 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 191 of file RunAction.cc
References emax, CEMC_TOWER::emin, energy, RunAction::MinMaxData::fCount, fEkinOfSecondaries, RunAction::MinMaxData::fVmax, RunAction::MinMaxData::fVmin, RunAction::MinMaxData::fVsum, and particle.
void RunAction::EnergyTransfered (G4double energy)
Definition at line 155 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 155 of file RunAction.cc
References energy, fEnergyTransfered, fEtransfMax, and fEtransfMin.
void RunAction::EnergyTransferedByProcess (G4String procName, G4double energy)
Definition at line 135 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 135 of file RunAction.cc
References emax, CEMC_TOWER::emin, energy, RunAction::MinMaxData::fCount, fEtransfByProcess, RunAction::MinMaxData::fVmax, RunAction::MinMaxData::fVmin, and RunAction::MinMaxData::fVsum.
void RunAction::EventFinished ()
Definition at line 245 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 245 of file RunAction.cc
References RunAction::ParticleStatistics::EventFinished(), fElectronStats, fPhotonStats, fPositronStats, and fTotalEventCount.
void RunAction::FillData (const G4ParticleDefinition * particle, G4double kinEnergy, G4double costheta, G4double phi, G4double longitudinalPolarization)
Definition at line 93 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 93 of file RunAction.cc
References fAnalysisManager, fElectron, fElectronStats, fGamma, RunAction::ParticleStatistics::FillData(), G4VAnalysisManager::FillH1(), fPhotonStats, fPositron, and fPositronStats.
void RunAction::FillEdep (G4double de, G4double eni) inline
Definition at line 88 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 88 of file RunAction.hh
References fEdeptot, and fEniel.
void RunAction::FillPerEvent (G4double , G4double , G4double , G4double)
void RunAction::FillPerEvent (G4double EAbs, G4double EGap, G4double LAbs, G4double LGap)
Definition at line 75 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 75 of file RunAction.cc
References fSum2EAbs, fSum2EGap, fSum2LAbs, fSum2LGap, fSumEAbs, fSumEGap, fSumLAbs, and fSumLGap.
void RunAction::FillPerEvent (G4double , G4double , G4double , G4double)
void RunAction::FillPerEvent (G4double , G4double , G4double , G4double)
void RunAction::FillTallyEdep (G4int n, G4double e) inline
Definition at line 81 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 81 of file RunAction.hh
References e, fTallyEdep, and n.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
G4Run* RunAction::GenerateRun () override virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
G4Run * RunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 65 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 65 of file RunAction.cc
References fDetector, and fRun.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
virtual G4Run* RunAction::GenerateRun () virtual
Reimplemented from G4UserRunAction.
void RunAction::GetCuts ()
Definition at line 268 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 268 of file RunAction.cc
References detector, energyCut, G4ProductionCutsTable::GetEnergyCutsVector(), DetectorConstruction::GetMaterial(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetRangeCutsVector(), G4ProductionCutsTable::GetTableSize(), idxG4ElectronCut, idxG4GammaCut, idxG4PositronCut, and rangeCut.
Referenced by BeginOfRunAction().
void RunAction::GetCuts ()
G4double RunAction::GetDoseBox (G4int i) const inline
Definition at line 81 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 81 of file RunAction.hh
References fDose3DDose.
G4double RunAction::GetDoseC () const inline
Definition at line 66 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file RunAction.hh
References fDoseC.
G4double RunAction::GetDoseN () const inline
Definition at line 62 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file RunAction.hh
References fDoseN.
G4double RunAction::GetEdepALL () inline
Definition at line 73 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RunAction.hh
References fEdepAll.
G4double RunAction::GetEdepAxon () inline
Definition at line 115 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 115 of file RunAction.hh
References fEdepAxon.
G4double RunAction::GetEdepDend () inline
Definition at line 106 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 106 of file RunAction.hh
References fEdepDend.
G4double RunAction::GetEdepMedium () inline
Definition at line 81 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 81 of file RunAction.hh
References fEdepMedium.
G4double RunAction::GetEdepNeuron () inline
Definition at line 124 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 124 of file RunAction.hh
References fEdepNeuron.
G4double RunAction::GetEdepSlice () inline
Definition at line 89 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 89 of file RunAction.hh
References fEdepSlice.
G4double RunAction::GetEdepSoma () inline
Definition at line 97 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 97 of file RunAction.hh
References fEdepSoma.
G4double RunAction::GetEnergyCut (const G4Material * material, G4int idParticle) private
Definition at line 247 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 247 of file RunAction.cc
References G4ProductionCutsTable::GetEnergyCutsVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), and material().
Referenced by ComputeTheory().
G4double RunAction::GetEnergyFromCSDARange (G4double range, G4ParticleDefinition * particle, G4Material * material, G4double Etry)
Definition at line 464 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 464 of file RunAction.cc
References kdfinder::abs(), G4EmCalculator::ComputeTotalDEDX(), dE, check_license::err(), G4BestUnit, G4cout, G4endl, G4EmCalculator::GetCSDARange(), and r.
G4double RunAction::GetEnergyFromRestrictedRange (G4double range, G4ParticleDefinition * particle, G4Material * material, G4double Etry)
Definition at line 432 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 432 of file RunAction.cc
References kdfinder::abs(), dE, check_license::err(), G4BestUnit, G4cout, G4endl, G4EmCalculator::GetDEDX(), G4EmCalculator::GetRangeFromRestricteDEDX(), and r.
G4double RunAction::GetMassCytoplasm () const inline
Definition at line 78 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 78 of file RunAction.hh
References fMassCytoplasm.
G4double RunAction::GetMassNucleus () const inline
Definition at line 75 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 75 of file RunAction.hh
References fMassNucleus.
G4int RunAction::GetNbOfHitsGas () const inline
Definition at line 71 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file RunAction.hh
References fNbOfHitsGas.
G4int RunAction::GetNumEvent () const inline
Definition at line 68 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file RunAction.hh
References fNumEvent.
G4int RunAction::GetNumEvent () inline
Definition at line 132 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 132 of file RunAction.hh
References fNumEvent.
G4int RunAction::GetRndmFreq () const inline
Definition at line 58 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file RunAction.hh
References fSaveRndm.
G4int RunAction::GetRndmFreq () inline
Definition at line 59 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 59 of file RunAction.hh
References fRndmFreq.
G4int RunAction::GetRndmFreq () inline
Definition at line 69 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file RunAction.hh
References fSaveRndm.
G4int RunAction::GetRow () inline
Definition at line 52 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 52 of file RunAction.hh
References fRow.
G4ThreeVector RunAction::GetVectCell (G4int i) const inline
Definition at line 83 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 83 of file RunAction.hh
References fMapVoxels.
void RunAction::InitializeWorker (const G4Run *) private
Definition at line 185 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 185 of file RunAction.cc
References FatalException, fInitialized, fpTrackingAction, G4Exception(), G4RunManager::GetRunManager(), G4RunManager::GetUserTrackingAction(), and G4UserRunAction::isMaster.
Referenced by BeginMaster(), and BeginWorker().
void RunAction::InitializeWorker (const G4Run *) private
void RunAction::InitializeWorker (const G4Run *) private
void RunAction::PrintRunInfo (const G4Run * run) private
Definition at line 257 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 257 of file RunAction.cc
References G4cout, G4endl, G4Run::GetNumberOfEvent(), G4Run::GetNumberOfEventToBeProcessed(), G4Run::GetRunID(), G4RunManager::GetRunManager(), and G4RunManager::GetRunManagerType().
Referenced by BeginMaster(), BeginWorker(), and EndWorker().
void RunAction::PrintRunInfo (const G4Run * run) private
void RunAction::PrintRunInfo (const G4Run * run) private
void RunAction::PrintRunInfo (const G4Run * run) private
void RunAction::SaveHisto (G4int nevents) private
Definition at line 162 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 162 of file RunAction.cc
References G4VAnalysisManager::CloseFile(), fAnalysisManager, norm, G4VAnalysisManager::ScaleH1(), and G4VAnalysisManager::Write().
void RunAction::SetApplyLimit (G4bool val)
Definition at line 131 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 131 of file RunAction.cc
References fRun, and Run::SetApplyLimit().
void RunAction::SetBinSize (G4double size)
Definition at line 108 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 108 of file RunAction.cc
References fBinLength, fDetector, and DetectorConstruction::GetMaxStepSize().
void RunAction::SetDoseC (G4double dose) inline
Definition at line 65 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RunAction.hh
References dose, and fDoseC.
void RunAction::SetDoseN (G4double dose) inline
Definition at line 61 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 61 of file RunAction.hh
References dose, and fDoseN.
void RunAction::SetEdepALL (G4double vall) inline
Definition at line 74 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 74 of file RunAction.hh
References fEdepAll.
void RunAction::SetEdepAndRMS (G4int i, G4double edep, G4double rms, G4double lim)
Definition at line 124 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 124 of file RunAction.cc
References fRun, and Run::SetEdepAndRMS().
void RunAction::SetEdepAndRMS (G4ThreeVector Value)
Definition at line 184 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 184 of file RunAction.cc
References fEdeptrue, fLimittrue, and fRmstrue.
Referenced by RunActionMessenger::SetNewValue().
void RunAction::SetEdepAxon (G4double vall) inline
Definition at line 116 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 116 of file RunAction.hh
References fEdepAxon.
void RunAction::SetEdepDend (G4double vall) inline
Definition at line 107 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 107 of file RunAction.hh
References fEdepDend.
void RunAction::SetEdepMedium (G4double vall) inline
Definition at line 82 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 82 of file RunAction.hh
References fEdepMedium.
void RunAction::SetEdepNeuron (G4double vall) inline
Definition at line 125 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 125 of file RunAction.hh
References fEdepNeuron.
void RunAction::SetEdepSlice (G4double vall) inline
Definition at line 90 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file RunAction.hh
References fEdepSlice.
void RunAction::SetEdepSoma (G4double vall) inline
Definition at line 98 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 98 of file RunAction.hh
References fEdepSoma.
void RunAction::SetHistoName (G4String & val) inline
Definition at line 55 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 55 of file RunAction.hh
References fFileName.
void RunAction::SetHistoName (G4String & val)
Definition at line 140 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 140 of file RunAction.cc
References fHistoName.
Referenced by RunActionMessenger::SetNewValue().
void RunAction::SetMassCytoplasm (G4double mC) inline
Definition at line 77 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 77 of file RunAction.hh
References fMassCytoplasm.
void RunAction::SetMassNucleus (G4double mN) inline
Definition at line 74 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 74 of file RunAction.hh
References fMassNucleus.
void RunAction::SetNumEvent (G4int i) inline
Definition at line 69 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file RunAction.hh
References fNumEvent.
void RunAction::SetNumEvent (G4int i) inline
Definition at line 133 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 133 of file RunAction.hh
References fNumEvent.
void RunAction::SetPrintFlag (G4bool flag)
Definition at line 116 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 116 of file RunAction.cc
References fPrint.
void RunAction::SetRndmFreq (G4int val) inline
Definition at line 57 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 57 of file RunAction.hh
References fSaveRndm.
Referenced by RunMessenger::SetNewValue().
void RunAction::SetRndmFreq (G4int val) inline
Definition at line 58 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file RunAction.hh
References fRndmFreq.
void RunAction::SetRndmFreq (G4int val) inline
Definition at line 68 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file RunAction.hh
References fSaveRndm.
void RunAction::SetVerbose (G4int val)
Definition at line 192 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 192 of file RunAction.cc
References fRun, fVerbose, and Run::SetVerbose().
Referenced by RunActionMessenger::SetNewValue().
void RunAction::SumLateralDisplacement (G4double displa) inline
Definition at line 66 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file RunAction.hh
References fLDispl, and fLDispl2.
void RunAction::SumPathLength (G4double truepl, G4double geompl) inline
Definition at line 60 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file RunAction.hh
References fGeomPL, fGeomPL2, fTotalCount, fTruePL, and fTruePL2.
void RunAction::SumPhiCorrel (G4double correl) inline
Definition at line 75 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 75 of file RunAction.hh
References fPhiCor, and fPhiCor2.
void RunAction::SumPsi (G4double psi) inline
Definition at line 69 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file RunAction.hh
References fPsiSpa, and fPsiSpa2.
void RunAction::SumTetaPlane (G4double teta) inline
Definition at line 72 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RunAction.hh
References fTetPrj, and fTetPrj2.
void RunAction::TotalEnergyDeposit (G4double energy)
Definition at line 182 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 182 of file RunAction.cc
References energy, fEdepTotal, fEdepTotMax, and fEdepTotMin.
void RunAction::TotalEnergyLost (G4double energy)
Definition at line 164 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 164 of file RunAction.cc
References energy, fElostMax, fElostMin, and fEnergyLost.
void RunAction::TrackLength (G4double step)
Definition at line 113 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 113 of file RunAction.cc
References fNbSteps, fStepMax, fStepMin, fTrackLength, and Acts::Test::step().
void RunAction::WriteHistogram ()
void RunAction::WriteHistogram () private
Definition at line 243 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 243 of file RunAction.cc
References G4VAnalysisManager::CloseFile(), G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
Referenced by EndWorker().
void RunAction::WriteHistogram () private
void RunAction::WriteHistogram () private
void RunAction::WriteNtuple () private
Definition at line 102 of file RunAction.cc.
View newest version in sPHENIX GitHub at line 102 of file RunAction.cc
References G4VAnalysisManager::CloseFile(), G4cout, G4endl, G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
void RunAction::WriteNtuple () private
Member Data Documentation
DetectorConstruction* RunAction::detector private
Definition at line 58 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file RunAction.hh
Referenced by BeginOfRunAction(), CriticalEnergy(), and GetCuts().
G4double RunAction::energyCut[3] private
Definition at line 61 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 61 of file RunAction.hh
Referenced by BeginOfRunAction(), and GetCuts().
G4AnalysisManager* RunAction::fAnalysis private
Definition at line 64 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RunAction.hh
G4AnalysisManager * RunAction::fAnalysisManager private
Definition at line 76 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 76 of file RunAction.hh
Referenced by Book(), FillData(), and SaveHisto().
CLHEP::HepMatrix RunAction::fBeamMatrix private
Definition at line 73 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RunAction.hh
G4double RunAction::fBinLength private
Definition at line 69 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file RunAction.hh
Referenced by SetBinSize().
bool RunAction::fDebug private
Definition at line 83 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 83 of file RunAction.hh
Referenced by BeginMaster(), BeginWorker(), EndWorker(), and RunAction().
DetectorConstruction* RunAction::fDet private
Definition at line 73 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RunAction.hh
DetectorConstruction * RunAction::fDetector private
Definition at line 62 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file RunAction.hh
Referenced by ComputeMscHighland(), ComputeTheory(), GenerateRun(), RunAction(), and SetBinSize().
const DetectorConstruction* RunAction::fDetector private
Definition at line 87 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 87 of file RunAction.hh
G4double* RunAction::fDose3DDose private
Definition at line 98 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 98 of file RunAction.hh
Referenced by AddDoseBox(), and GetDoseBox().
G4double RunAction::fDoseC private
Definition at line 95 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 95 of file RunAction.hh
Referenced by AddDoseC(), GetDoseC(), and SetDoseC().
G4double RunAction::fDoseN private
Definition at line 94 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 94 of file RunAction.hh
Referenced by AddDoseN(), GetDoseN(), and SetDoseN().
G4double RunAction::fEbalMax private
Definition at line 115 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 115 of file RunAction.hh
Referenced by EnergyBalance().
G4double RunAction::fEbalMin private
Definition at line 115 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 115 of file RunAction.hh
Referenced by EnergyBalance().
G4double RunAction::fEdepAll private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepALL(), GetEdepALL(), and SetEdepALL().
G4double RunAction::fEdepAll_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepALL().
G4double RunAction::fEdepAxon private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepAxon(), GetEdepAxon(), and SetEdepAxon().
G4double RunAction::fEdepAxon_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepAxon().
G4double RunAction::fEdepDend private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepDend(), GetEdepDend(), and SetEdepDend().
G4double RunAction::fEdepDend_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepDend().
G4double RunAction::fEdepMedium private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepMedium(), GetEdepMedium(), and SetEdepMedium().
G4double RunAction::fEdepMedium_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepMedium().
G4double RunAction::fEdepNeuron private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepNeuron(), GetEdepNeuron(), and SetEdepNeuron().
G4double RunAction::fEdepNeuron_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepNeuron().
G4double RunAction::fEdepPrimary private
Definition at line 111 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 111 of file RunAction.hh
Referenced by EnergyDeposited().
G4double RunAction::fEdepPrimMax private
Definition at line 111 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 111 of file RunAction.hh
Referenced by EnergyDeposited().
G4double RunAction::fEdepPrimMin private
Definition at line 111 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 111 of file RunAction.hh
Referenced by EnergyDeposited().
G4double RunAction::fEdepSecMax private
Definition at line 117 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 117 of file RunAction.hh
Referenced by EnergyDeposited().
G4double RunAction::fEdepSecMin private
Definition at line 117 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 117 of file RunAction.hh
Referenced by EnergyDeposited().
G4double RunAction::fEdepSecondary private
Definition at line 117 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 117 of file RunAction.hh
Referenced by EnergyDeposited().
G4double RunAction::fEdepSlice private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepSlice(), GetEdepSlice(), and SetEdepSlice().
G4double RunAction::fEdepSlice_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepSlice().
G4double RunAction::fEdepSoma private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepSoma(), GetEdepSoma(), and SetEdepSoma().
G4double RunAction::fEdepSoma_err private
Definition at line 164 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 164 of file RunAction.hh
Referenced by AddEdepSoma().
G4double RunAction::fEdeptot private
Definition at line 74 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 74 of file RunAction.hh
Referenced by FillEdep().
G4double RunAction::fEdepTotal private
Definition at line 118 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 118 of file RunAction.hh
Referenced by TotalEnergyDeposit().
G4double RunAction::fEdepTotMax private
Definition at line 118 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 118 of file RunAction.hh
Referenced by TotalEnergyDeposit().
G4double RunAction::fEdepTotMin private
Definition at line 118 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 118 of file RunAction.hh
Referenced by TotalEnergyDeposit().
G4double RunAction::fEdeptrue private
Definition at line 83 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 83 of file RunAction.hh
Referenced by SetEdepAndRMS().
std::map<G4String,MinMaxData> RunAction::fEkinOfSecondaries private
Definition at line 120 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 120 of file RunAction.hh
Referenced by EnergySpectrumOfSecondaries().
const G4ParticleDefinition* RunAction::fElectron private
Definition at line 91 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 91 of file RunAction.hh
Referenced by FillData().
ParticleStatistics RunAction::fElectronStats private
Definition at line 103 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 103 of file RunAction.hh
Referenced by EventFinished(), and FillData().
G4double RunAction::fElostMax private
Definition at line 114 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 114 of file RunAction.hh
Referenced by TotalEnergyLost().
G4double RunAction::fElostMin private
Definition at line 114 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 114 of file RunAction.hh
Referenced by TotalEnergyLost().
G4double RunAction::fEnergyBalance private
Definition at line 115 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 115 of file RunAction.hh
Referenced by EnergyBalance().
G4double RunAction::fEnergyCut[3] private
Definition at line 64 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RunAction.hh
G4double RunAction::fEnergyLost private
Definition at line 114 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 114 of file RunAction.hh
Referenced by TotalEnergyLost().
G4double RunAction::fEnergyTransfered private
Definition at line 113 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 113 of file RunAction.hh
Referenced by EnergyTransfered().
G4double RunAction::fEniel private
Definition at line 74 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 74 of file RunAction.hh
Referenced by FillEdep().
std::map<G4String,MinMaxData> RunAction::fEtransfByProcess private
Definition at line 112 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 112 of file RunAction.hh
Referenced by EnergyTransferedByProcess().
G4double RunAction::fEtransfMax private
Definition at line 113 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 113 of file RunAction.hh
Referenced by EnergyTransfered().
G4double RunAction::fEtransfMin private
Definition at line 113 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 113 of file RunAction.hh
Referenced by EnergyTransfered().
G4String RunAction::fFileName private
Definition at line 81 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 81 of file RunAction.hh
Referenced by CreateHistogram(), RunAction(), and SetHistoName().
const G4ParticleDefinition* RunAction::fGamma private
Definition at line 90 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file RunAction.hh
Referenced by FillData().
G4double RunAction::fGeomPL private
Definition at line 88 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 88 of file RunAction.hh
Referenced by SumPathLength().
G4double RunAction::fGeomPL2 private
Definition at line 88 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 88 of file RunAction.hh
Referenced by SumPathLength().
HistoManager* RunAction::fHisto private
Definition at line 71 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file RunAction.hh
HistoManager * RunAction::fHistoManager private
Definition at line 65 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RunAction.hh
Referenced by ComputeTheory(), and RunAction().
G4String RunAction::fHistoName[2] private
Definition at line 81 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 81 of file RunAction.hh
Referenced by SetHistoName().
bool RunAction::fInitialized private
Definition at line 82 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 82 of file RunAction.hh
Referenced by BeginMaster(), BeginWorker(), InitializeWorker(), and RunAction().
PrimaryGeneratorAction* RunAction::fKin private
Definition at line 74 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 74 of file RunAction.hh
PrimaryGeneratorAction * RunAction::fKinematic private
Definition at line 71 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file RunAction.hh
G4double RunAction::fLDispl private
Definition at line 89 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 89 of file RunAction.hh
Referenced by SumLateralDisplacement().
G4double RunAction::fLDispl2 private
Definition at line 89 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 89 of file RunAction.hh
Referenced by SumLateralDisplacement().
G4double RunAction::fLimittrue private
Definition at line 85 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 85 of file RunAction.hh
Referenced by SetEdepAndRMS().
G4ThreeVector* RunAction::fMapVoxels private
Definition at line 100 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 100 of file RunAction.hh
Referenced by GetVectCell().
G4double RunAction::fMassCytoplasm private
Definition at line 96 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 96 of file RunAction.hh
Referenced by GetMassCytoplasm(), and SetMassCytoplasm().
G4double RunAction::fMassNucleus private
Definition at line 97 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 97 of file RunAction.hh
Referenced by GetMassNucleus(), and SetMassNucleus().
G4Material* RunAction::fMat private
Definition at line 65 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RunAction.hh
G4double RunAction::fMaxE private
Definition at line 68 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file RunAction.hh
Referenced by RunAction().
RunActionMessenger* RunAction::fMessenger private
Definition at line 67 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file RunAction.hh
G4double RunAction::fMinE private
Definition at line 67 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file RunAction.hh
Referenced by RunAction().
MuCrossSections* RunAction::fMucs private
Definition at line 73 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RunAction.hh
Referenced by ComputeTheory(), and RunAction().
G4int RunAction::fnBin private
Definition at line 69 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file RunAction.hh
Referenced by RunAction().
G4int RunAction::fNbOfHitsGas private
Definition at line 92 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 92 of file RunAction.hh
Referenced by AddNbOfHitsGas(), and GetNbOfHitsGas().
G4int RunAction::fNbOfPixels private
Definition at line 91 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 91 of file RunAction.hh
G4int RunAction::fNbPrimarySteps private
Definition at line 75 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 75 of file RunAction.hh
Referenced by AddPrimaryStep().
G4long RunAction::fNbSteps private
Definition at line 108 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 108 of file RunAction.hh
Referenced by TrackLength().
G4int RunAction::fNtColId[3] private
Definition at line 71 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file RunAction.hh
Referenced by RunAction().
G4int RunAction::fNumEvent private
Definition at line 90 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file RunAction.hh
Referenced by GetNumEvent(), and SetNumEvent().
const DetectorConstruction * RunAction::fpDetector private
Definition at line 53 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 53 of file RunAction.hh
G4double RunAction::fPhiCor private
Definition at line 92 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 92 of file RunAction.hh
Referenced by SumPhiCorrel().
G4double RunAction::fPhiCor2 private
Definition at line 92 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 92 of file RunAction.hh
Referenced by SumPhiCorrel().
HistoManager * RunAction::fpHistoManager private
Definition at line 55 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 55 of file RunAction.hh
CLHEP::HepVector RunAction::fPhiVector private
Definition at line 72 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RunAction.hh
Referenced by AddToPhiVector().
ParticleStatistics RunAction::fPhotonStats private
Definition at line 102 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 102 of file RunAction.hh
Referenced by EventFinished(), and FillData().
PhysicsList * RunAction::fPhysics private
Definition at line 60 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file RunAction.hh
const G4ParticleDefinition* RunAction::fPositron private
Definition at line 92 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 92 of file RunAction.hh
Referenced by FillData().
ParticleStatistics RunAction::fPositronStats private
Definition at line 104 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 104 of file RunAction.hh
Referenced by EventFinished(), and FillData().
PrimaryGeneratorAction * RunAction::fPrimary private
Definition at line 63 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file RunAction.hh
Referenced by ComputeMscHighland(), and ComputeTheory().
G4bool RunAction::fPrint private
Definition at line 72 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RunAction.hh
Referenced by SetPrintFlag().
ProcessesCount * RunAction::fProcCounter private
Definition at line 83 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 83 of file RunAction.hh
Referenced by CountProcesses().
std::map<G4String,G4int> RunAction::fProcCounter private
Definition at line 106 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 106 of file RunAction.hh
G4double RunAction::fProjRange private
Definition at line 73 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RunAction.hh
Referenced by AddProjRange().
G4double RunAction::fProjRange2 private
Definition at line 73 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RunAction.hh
Referenced by AddProjRange().
Run * RunAction::fpRun private
Definition at line 54 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file RunAction.hh
RunActionMessenger* RunAction::fpRunMessenger private
Definition at line 62 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file RunAction.hh
G4double RunAction::fPsiSpa private
Definition at line 90 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file RunAction.hh
Referenced by SumPsi().
G4double RunAction::fPsiSpa2 private
Definition at line 90 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file RunAction.hh
Referenced by SumPsi().
TrackingAction * RunAction::fpTrackingAction private
Definition at line 80 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 80 of file RunAction.hh
Referenced by EndWorker(), InitializeWorker(), and RunAction().
G4int RunAction::fRange private
Definition at line 76 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 76 of file RunAction.hh
Referenced by AddProjRange().
G4double RunAction::fRangeCut[3] private
Definition at line 63 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file RunAction.hh
G4double RunAction::fRmstrue private
Definition at line 84 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 84 of file RunAction.hh
Referenced by SetEdepAndRMS().
G4int RunAction::fRndmFreq private
Definition at line 66 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file RunAction.hh
Referenced by GetRndmFreq(), and SetRndmFreq().
G4int RunAction::fRow private
Definition at line 67 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file RunAction.hh
Referenced by AddRow(), AddToPhiVector(), AddToThetaVector(), AddToXVector(), AddToYVector(), and GetRow().
Run * RunAction::fRun private
Definition at line 64 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RunAction.hh
Referenced by GenerateRun(), SetApplyLimit(), SetEdepAndRMS(), and SetVerbose().
RunMessenger * RunAction::fRunMessenger private
Definition at line 65 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RunAction.hh
RunActionMessenger* RunAction::fRunMessenger private
Definition at line 75 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 75 of file RunAction.hh
G4int RunAction::fSaveRndm private
Definition at line 89 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 89 of file RunAction.hh
Referenced by GetRndmFreq(), RunAction(), and SetRndmFreq().
G4double RunAction::fStepMax private
Definition at line 109 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 109 of file RunAction.hh
Referenced by TrackLength().
G4double RunAction::fStepMin private
Definition at line 109 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 109 of file RunAction.hh
Referenced by TrackLength().
G4double RunAction::fSum2EAbs private
Definition at line 61 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 61 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSum2EGap private
Definition at line 62 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSum2LAbs private
Definition at line 64 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSum2LGap private
Definition at line 65 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSumEAbs private
Definition at line 61 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 61 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSumEGap private
Definition at line 62 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSumLAbs private
Definition at line 64 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RunAction.hh
Referenced by FillPerEvent().
G4double RunAction::fSumLGap private
Definition at line 65 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RunAction.hh
Referenced by FillPerEvent().
G4double* RunAction::fTallyEdep private
Definition at line 72 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RunAction.hh
Referenced by FillTallyEdep().
G4double RunAction::fTetPrj private
Definition at line 91 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 91 of file RunAction.hh
Referenced by SumTetaPlane().
G4double RunAction::fTetPrj2 private
Definition at line 91 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 91 of file RunAction.hh
Referenced by SumTetaPlane().
CLHEP::HepVector RunAction::fThetaVector private
Definition at line 71 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file RunAction.hh
Referenced by AddToThetaVector().
G4Timer * RunAction::fTimer private
Definition at line 72 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RunAction.hh
G4int RunAction::fTotalCount private
Definition at line 86 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 86 of file RunAction.hh
Referenced by SumPathLength().
G4int RunAction::fTotalEventCount private
Definition at line 100 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 100 of file RunAction.hh
Referenced by EventFinished().
G4double RunAction::fTrackLength private
Definition at line 109 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 109 of file RunAction.hh
Referenced by TrackLength().
G4double RunAction::fTruePL private
Definition at line 87 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 87 of file RunAction.hh
Referenced by SumPathLength().
G4double RunAction::fTruePL2 private
Definition at line 87 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 87 of file RunAction.hh
Referenced by SumPathLength().
G4int RunAction::fVerbose private
Definition at line 79 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 79 of file RunAction.hh
Referenced by SetVerbose().
CLHEP::HepVector RunAction::fXVector private
Definition at line 69 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file RunAction.hh
Referenced by AddToXVector().
CLHEP::HepVector RunAction::fYVector private
Definition at line 70 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 70 of file RunAction.hh
Referenced by AddToYVector().
PrimaryGeneratorAction* RunAction::primary private
Definition at line 59 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 59 of file RunAction.hh
Referenced by BeginOfRunAction().
G4double RunAction::rangeCut[3] private
Definition at line 60 of file RunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file RunAction.hh
Referenced by BeginOfRunAction(), and GetCuts().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/RunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/factory/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/genericPL/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/shared/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/channeling/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/include/RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/include/RunAction.hh
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/RunAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/channeling/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/factory/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/genericPL/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/shared/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/src/RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/src/RunAction.cc