ECCE @ EIC Software: G4BOptnChangeCrossSection Class Reference
G4BOptnChangeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnChangeCrossSection.hh>
Public Member Functions
G4BOptnChangeCrossSection (G4String name)
virtual ~G4BOptnChangeCrossSection ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &proposeForceCondition)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
G4InteractionLawPhysical * GetBiasedExponentialLaw ()
void SetBiasedCrossSection (G4double xst, bool updateInteractionLength=false)
G4double GetBiasedCrossSection () const
void Sample ()
void UpdateForStep (G4double stepLength)
G4bool GetInteractionOccured () const
void SetInteractionOccured ()
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4InteractionLawPhysical * fBiasedExponentialLaw
G4bool fInteractionOccured
Detailed Description
Definition at line 46 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 46 of file G4BOptnChangeCrossSection.hh
Constructor & Destructor Documentation
G4BOptnChangeCrossSection::G4BOptnChangeCrossSection (G4String name)
Definition at line 31 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 31 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw.
G4BOptnChangeCrossSection::~G4BOptnChangeCrossSection () virtual
Definition at line 38 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 38 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw.
Member Function Documentation
virtual G4VParticleChange* G4BOptnChangeCrossSection::ApplyFinalStateBiasing (const G4BiasingProcessInterface * , const G4Track * , const G4Step * , G4bool &) inline virtual
Implements G4VBiasingOperation.
Definition at line 61 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BOptnChangeCrossSection.hh
virtual G4double G4BOptnChangeCrossSection::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) inline virtual
Implements G4VBiasingOperation.
Definition at line 65 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BOptnChangeCrossSection.hh
References DBL_MAX.
virtual G4VParticleChange* G4BOptnChangeCrossSection::GenerateBiasingFinalState (const G4Track * , const G4Step *) inline virtual
Implements G4VBiasingOperation.
Definition at line 68 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BOptnChangeCrossSection.hh
G4double G4BOptnChangeCrossSection::GetBiasedCrossSection () const
Definition at line 54 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 54 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw, and G4InteractionLawPhysical::GetPhysicalCrossSection().
G4InteractionLawPhysical* G4BOptnChangeCrossSection::GetBiasedExponentialLaw () inline
Definition at line 75 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BOptnChangeCrossSection.hh
References fBiasedExponentialLaw.
G4bool G4BOptnChangeCrossSection::GetInteractionOccured () const inline
Definition at line 85 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BOptnChangeCrossSection.hh
References fInteractionOccured.
Referenced by GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
const G4VBiasingInteractionLaw * G4BOptnChangeCrossSection::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition & proposeForceCondition) virtual
Implements G4VBiasingOperation.
Definition at line 43 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 43 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw.
void G4BOptnChangeCrossSection::Sample ()
Definition at line 59 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 59 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw, fInteractionOccured, and G4VBiasingInteractionLaw::Sample().
Referenced by GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
void G4BOptnChangeCrossSection::SetBiasedCrossSection (G4double xst, bool updateInteractionLength = false)
Definition at line 48 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 48 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw, G4InteractionLawPhysical::SetPhysicalCrossSection(), and UpdateForStep().
Referenced by GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
void G4BOptnChangeCrossSection::SetInteractionOccured () inline
Definition at line 86 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 86 of file G4BOptnChangeCrossSection.hh
References fInteractionOccured.
Referenced by G4ChannelingOptrChangeCrossSection::OperationApplied(), and GB01BOptrChangeCrossSection::OperationApplied().
void G4BOptnChangeCrossSection::UpdateForStep (G4double stepLength)
Definition at line 65 of file G4BOptnChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 65 of file G4BOptnChangeCrossSection.cc
References fBiasedExponentialLaw, and G4VBiasingInteractionLaw::UpdateForStep().
Referenced by GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and SetBiasedCrossSection().
Member Data Documentation
G4InteractionLawPhysical* G4BOptnChangeCrossSection::fBiasedExponentialLaw private
Definition at line 91 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BOptnChangeCrossSection.hh
Referenced by G4BOptnChangeCrossSection(), GetBiasedCrossSection(), GetBiasedExponentialLaw(), ProvideOccurenceBiasingInteractionLaw(), Sample(), SetBiasedCrossSection(), UpdateForStep(), and ~G4BOptnChangeCrossSection().
G4bool G4BOptnChangeCrossSection::fInteractionOccured private
Definition at line 92 of file G4BOptnChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BOptnChangeCrossSection.hh
Referenced by GetInteractionOccured(), Sample(), and SetInteractionOccured().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnChangeCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptnChangeCrossSection.cc