ECCE @ EIC Software: G4PlotParameters Class Reference
G4PlotParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4PlotParameters.hh>
Public Member Functions
G4PlotParameters ()
void SetLayout (G4int columns, G4int rows)
void SetDimensions (G4int width, G4int height)
void SetStyle (const G4String &style)
G4int GetMaxColumns ()
G4int GetMaxRows ()
G4String GetAvailableStyles ()
G4int GetColumns () const
G4int GetRows () const
G4int GetWidth () const
G4int GetHeight () const
G4float GetScale () const
G4String GetStyle () const
Private Attributes
std::unique_ptr< G4PlotMessenger > fMessenger
G4int fDefaultColumns
G4int fDefaultRows
G4int fDefaultWidth
G4int fDefaultHeight
G4String fDefaultStyle
G4float fDefaultScale
G4int fMaxColumns
G4int fMaxRows
G4String fAvailableStyles
G4int fColumns
G4int fRows
G4int fWidth
G4int fHeight
G4float fScale
G4String fStyle
Detailed Description
Definition at line 40 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 40 of file G4PlotParameters.hh
Constructor & Destructor Documentation
G4PlotParameters::G4PlotParameters ()
Definition at line 35 of file G4PlotParameters.cc.
View newest version in sPHENIX GitHub at line 35 of file G4PlotParameters.cc
References fMessenger.
Member Function Documentation
G4String G4PlotParameters::GetAvailableStyles () inline
Definition at line 94 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PlotParameters.hh
References fAvailableStyles.
Referenced by G4PlotMessenger::SetStyleCmd().
G4int G4PlotParameters::GetColumns () const inline
Definition at line 97 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4PlotParameters.hh
References fColumns.
Referenced by G4PlotManager::G4PlotManager(), G4PlotManager::GetNofPlotsPerPage(), and G4PlotManager::PlotAndWrite().
G4int G4PlotParameters::GetHeight () const inline
Definition at line 106 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 106 of file G4PlotParameters.hh
References fHeight.
Referenced by G4PlotManager::G4PlotManager().
G4int G4PlotParameters::GetMaxColumns () inline
Definition at line 88 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PlotParameters.hh
References fMaxColumns.
Referenced by G4PlotMessenger::SetLayoutCmd().
G4int G4PlotParameters::GetMaxRows () inline
Definition at line 91 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PlotParameters.hh
References fMaxRows.
Referenced by G4PlotMessenger::SetLayoutCmd().
G4int G4PlotParameters::GetRows () const inline
Definition at line 100 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PlotParameters.hh
References fRows.
Referenced by G4PlotManager::G4PlotManager(), G4PlotManager::GetNofPlotsPerPage(), and G4PlotManager::PlotAndWrite().
G4float G4PlotParameters::GetScale () const inline
Definition at line 109 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 109 of file G4PlotParameters.hh
References fScale.
Referenced by G4PlotManager::WritePage().
G4String G4PlotParameters::GetStyle () const inline
Definition at line 112 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PlotParameters.hh
References fStyle.
Referenced by G4PlotManager::PlotAndWrite().
G4int G4PlotParameters::GetWidth () const inline
Definition at line 103 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PlotParameters.hh
References fWidth.
Referenced by G4PlotManager::G4PlotManager().
void G4PlotParameters::SetDimensions (G4int width, G4int height)
Definition at line 93 of file G4PlotParameters.cc.
View newest version in sPHENIX GitHub at line 93 of file G4PlotParameters.cc
References fHeight, and fWidth.
Referenced by G4PlotMessenger::SetNewValue().
void G4PlotParameters::SetLayout (G4int columns, G4int rows)
Definition at line 72 of file G4PlotParameters.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PlotParameters.cc
References fColumns, fMaxColumns, fMaxRows, fRows, G4endl, G4Exception(), and JustWarning.
Referenced by G4PlotMessenger::SetNewValue().
void G4PlotParameters::SetStyle (const G4String & style)
Definition at line 100 of file G4PlotParameters.cc.
View newest version in sPHENIX GitHub at line 100 of file G4PlotParameters.cc
References fAvailableStyles, fDefaultScale, fScale, fStyle, G4endl, G4Exception(), and JustWarning.
Referenced by G4PlotMessenger::SetNewValue().
Member Data Documentation
G4String G4PlotParameters::fAvailableStyles private
Definition at line 76 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PlotParameters.hh
Referenced by GetAvailableStyles(), and SetStyle().
G4int G4PlotParameters::fColumns private
Definition at line 78 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PlotParameters.hh
Referenced by GetColumns(), and SetLayout().
G4int G4PlotParameters::fDefaultColumns private
Definition at line 67 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PlotParameters.hh
G4int G4PlotParameters::fDefaultHeight private
Definition at line 70 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PlotParameters.hh
G4int G4PlotParameters::fDefaultRows private
Definition at line 68 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PlotParameters.hh
G4float G4PlotParameters::fDefaultScale private
Definition at line 72 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PlotParameters.hh
Referenced by SetStyle().
G4String G4PlotParameters::fDefaultStyle private
Definition at line 71 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PlotParameters.hh
G4int G4PlotParameters::fDefaultWidth private
Definition at line 69 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PlotParameters.hh
G4int G4PlotParameters::fHeight private
Definition at line 81 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 81 of file G4PlotParameters.hh
Referenced by GetHeight(), and SetDimensions().
G4int G4PlotParameters::fMaxColumns private
Definition at line 74 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PlotParameters.hh
Referenced by GetMaxColumns(), and SetLayout().
G4int G4PlotParameters::fMaxRows private
Definition at line 75 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 75 of file G4PlotParameters.hh
Referenced by GetMaxRows(), and SetLayout().
std::unique_ptr<G4PlotMessenger> G4PlotParameters::fMessenger private
Definition at line 65 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PlotParameters.hh
Referenced by G4PlotParameters().
G4int G4PlotParameters::fRows private
Definition at line 79 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 79 of file G4PlotParameters.hh
Referenced by GetRows(), and SetLayout().
G4float G4PlotParameters::fScale private
Definition at line 82 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 82 of file G4PlotParameters.hh
Referenced by GetScale(), and SetStyle().
G4String G4PlotParameters::fStyle private
Definition at line 83 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PlotParameters.hh
Referenced by GetStyle(), and SetStyle().
G4int G4PlotParameters::fWidth private
Definition at line 80 of file G4PlotParameters.hh.
View newest version in sPHENIX GitHub at line 80 of file G4PlotParameters.hh
Referenced by GetWidth(), and SetDimensions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4PlotParameters.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4PlotParameters.cc