ECCE @ EIC Software: RootIO Class Reference
RootIO Class Reference
Root IO implementation for the persistency example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/RootIO.hh>
Public Member Functions
virtual ~RootIO ()
void Write (std::vector< ExP01TrackerHit * > *)
void Close ()
Static Public Member Functions
static RootIO * GetInstance ()
Protected Member Functions
RootIO ()
Private Attributes
TFile * fFile
int fNevents
Detailed Description
Root IO implementation for the persistency example.
Author
Witold POKORSKI
Date
2005-10-27
Definition at line 48 of file RootIO.hh.
View newest version in sPHENIX GitHub at line 48 of file RootIO.hh
Constructor & Destructor Documentation
RootIO::~RootIO () virtual
Definition at line 62 of file RootIO.cc.
View newest version in sPHENIX GitHub at line 62 of file RootIO.cc
RootIO::RootIO () protected
Definition at line 49 of file RootIO.cc.
View newest version in sPHENIX GitHub at line 49 of file RootIO.cc
References fFile.
Referenced by GetInstance().
Member Function Documentation
void RootIO::Close ()
Definition at line 95 of file RootIO.cc.
View newest version in sPHENIX GitHub at line 95 of file RootIO.cc
References fFile.
Referenced by ExP01TrackerSD::~ExP01TrackerSD().
RootIO * RootIO::GetInstance (void) static
Definition at line 67 of file RootIO.cc.
View newest version in sPHENIX GitHub at line 67 of file RootIO.cc
References instance, and RootIO().
Referenced by ExP01TrackerSD::EndOfEvent(), and ExP01TrackerSD::~ExP01TrackerSD().
void RootIO::Write (std::vector< ExP01TrackerHit * > * hcont)
Definition at line 78 of file RootIO.cc.
View newest version in sPHENIX GitHub at line 78 of file RootIO.cc
References fFile, fNevents, G4cout, and G4endl.
Referenced by ExP01TrackerSD::EndOfEvent().
Member Data Documentation
TFile* RootIO::fFile private
Definition at line 62 of file RootIO.hh.
View newest version in sPHENIX GitHub at line 62 of file RootIO.hh
Referenced by Close(), RootIO(), and Write().
int RootIO::fNevents private
Definition at line 63 of file RootIO.hh.
View newest version in sPHENIX GitHub at line 63 of file RootIO.hh
Referenced by Write().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/RootIO.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/src/RootIO.cc