ECCE @ EIC Software: G4GeneralParticleSourceMessenger Class Reference
G4GeneralParticleSourceMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4GeneralParticleSourceMessenger.hh>
Public Member Functions
void SetParticleGun (G4SingleParticleSource *fpg)
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Static Public Member Functions
static
G4GeneralParticleSourceMessenger * GetInstance (G4GeneralParticleSource *)
static void Destroy ()
Private Member Functions
G4GeneralParticleSourceMessenger (G4GeneralParticleSource *)
~G4GeneralParticleSourceMessenger ()
void IonCommand (G4String newValues)
void IonLvlCommand (G4String newValues)
Private Attributes
G4GeneralParticleSource * fGPS
G4SingleParticleSource * fParticleGun
G4ParticleTable * particleTable
G4String histtype
G4UIdirectory * gpsDirectory
G4UIdirectory * sourceDirectory
G4UIcmdWithADouble * addsourceCmd
G4UIcmdWithoutParameter * listsourceCmd
G4UIcmdWithoutParameter * clearsourceCmd
G4UIcmdWithoutParameter * getsourceCmd
G4UIcmdWithAnInteger * setsourceCmd
G4UIcmdWithADouble * setintensityCmd
G4UIcmdWithAnInteger * deletesourceCmd
G4UIcmdWithABool * multiplevertexCmd
G4UIcmdWithABool * flatsamplingCmd
G4UIdirectory * positionDirectory
G4UIcmdWithAString * typeCmd1
G4UIcmdWithAString * shapeCmd1
G4UIcmdWith3VectorAndUnit * centreCmd1
G4UIcmdWith3Vector * posrot1Cmd1
G4UIcmdWith3Vector * posrot2Cmd1
G4UIcmdWithADoubleAndUnit * halfxCmd1
G4UIcmdWithADoubleAndUnit * halfyCmd1
G4UIcmdWithADoubleAndUnit * halfzCmd1
G4UIcmdWithADoubleAndUnit * radiusCmd1
G4UIcmdWithADoubleAndUnit * radius0Cmd1
G4UIcmdWithADoubleAndUnit * possigmarCmd1
G4UIcmdWithADoubleAndUnit * possigmaxCmd1
G4UIcmdWithADoubleAndUnit * possigmayCmd1
G4UIcmdWithADoubleAndUnit * paralpCmd1
G4UIcmdWithADoubleAndUnit * partheCmd1
G4UIcmdWithADoubleAndUnit * parphiCmd1
G4UIcmdWithAString * confineCmd1
G4UIdirectory * angularDirectory
G4UIcmdWithAString * angtypeCmd1
G4UIcmdWith3Vector * angrot1Cmd1
G4UIcmdWith3Vector * angrot2Cmd1
G4UIcmdWithADoubleAndUnit * minthetaCmd1
G4UIcmdWithADoubleAndUnit * maxthetaCmd1
G4UIcmdWithADoubleAndUnit * minphiCmd1
G4UIcmdWithADoubleAndUnit * maxphiCmd1
G4UIcmdWithADoubleAndUnit * angsigmarCmd1
G4UIcmdWithADoubleAndUnit * angsigmaxCmd1
G4UIcmdWithADoubleAndUnit * angsigmayCmd1
G4UIcmdWith3VectorAndUnit * angfocusCmd
G4UIcmdWithABool * useuserangaxisCmd1
G4UIcmdWithABool * surfnormCmd1
G4UIdirectory * energyDirectory
G4UIcmdWithAString * energytypeCmd1
G4UIcmdWithADoubleAndUnit * eminCmd1
G4UIcmdWithADoubleAndUnit * emaxCmd1
G4UIcmdWithADoubleAndUnit * monoenergyCmd1
G4UIcmdWithADoubleAndUnit * engsigmaCmd1
G4UIcmdWithADouble * alphaCmd1
G4UIcmdWithADouble * tempCmd1
G4UIcmdWithADouble * ezeroCmd1
G4UIcmdWithADouble * gradientCmd1
G4UIcmdWithADouble * interceptCmd1
G4UIcmdWithADouble * arbeintCmd1
G4UIcmdWithoutParameter * calculateCmd1
G4UIcmdWithABool * energyspecCmd1
G4UIcmdWithABool * diffspecCmd1
G4UIdirectory * histDirectory
G4UIcmdWith3Vector * histpointCmd1
G4UIcmdWithAString * histfileCmd1
G4UIcmdWithAString * histnameCmd1
G4UIcmdWithAString * arbintCmd1
G4UIcmdWithAString * resethistCmd1
G4UIcmdWithAnInteger * verbosityCmd
G4UIcommand * ionCmd
G4UIcommand * ionLvlCmd
G4UIcmdWithAString * particleCmd
G4UIcmdWithADoubleAndUnit * timeCmd
G4UIcmdWith3Vector * polCmd
G4UIcmdWithAnInteger * numberCmd
G4UIcmdWith3VectorAndUnit * positionCmd
G4UIcmdWith3Vector * directionCmd
G4UIcmdWithADoubleAndUnit * energyCmd
G4UIcmdWithoutParameter * listCmd
G4bool fShootIon
G4int fAtomicNumber
G4int fAtomicMass
G4int fIonCharge
G4double fIonExciteEnergy
G4int fAtomicNumberL
G4int fAtomicMassL
G4int fIonChargeL
G4int fIonEnergyLevel
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Andrea Dotti Feb 2015 GPS messenger design requires some explanation for what distributions parameters are concerned : Each thread has its own GPS since primary generation is a user action. However to save memory the underlying structures that provide the GPS functionalities (the G4SPS*Distribution classes and the G4SPSRandomGenerator class) are shared among threads. This implies that modifying parameters of sources requires some attention: 1- Only one thread should change source parameters. 2- Changing of parameters can happen only between runs, when is guaranteed that no thread is accessing them 2- UI commands require that even if messenger is instantiated in a thread the commands are executed in the master (this is possible since V10.1) The simplest solution is to use UI commands to change GPS parameters and avoid C++ APIs. If this is inevitable a simple solution is to instantiate an instance of G4GeneralParticleSource explicitly in the master thread (for example in G4VUserActionInitialization::BuildForMaster() and set the defaults parameter there).
Definition at line 130 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 130 of file G4GeneralParticleSourceMessenger.hh
Constructor & Destructor Documentation
G4GeneralParticleSourceMessenger::G4GeneralParticleSourceMessenger (G4GeneralParticleSource * fPtclGun) private
Definition at line 103 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 103 of file G4GeneralParticleSourceMessenger.cc
References G4ParticleTable::GetParticleTable(), pi, and G4UIparameter::SetDefaultValue().
Referenced by GetInstance().
G4GeneralParticleSourceMessenger::~G4GeneralParticleSourceMessenger () private
Definition at line 867 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 867 of file G4GeneralParticleSourceMessenger.cc
References addsourceCmd, alphaCmd1, angfocusCmd, angrot1Cmd1, angrot2Cmd1, angsigmarCmd1, angsigmaxCmd1, angsigmayCmd1, angtypeCmd1, angularDirectory, arbeintCmd1, arbintCmd1, calculateCmd1, centreCmd1, clearsourceCmd, confineCmd1, deletesourceCmd, diffspecCmd1, directionCmd, emaxCmd1, eminCmd1, energyCmd, energyDirectory, energyspecCmd1, energytypeCmd1, engsigmaCmd1, ezeroCmd1, flatsamplingCmd, getsourceCmd, gpsDirectory, gradientCmd1, halfxCmd1, halfyCmd1, halfzCmd1, histDirectory, histfileCmd1, histnameCmd1, histpointCmd1, interceptCmd1, ionCmd, ionLvlCmd, listCmd, listsourceCmd, maxphiCmd1, maxthetaCmd1, minphiCmd1, minthetaCmd1, monoenergyCmd1, multiplevertexCmd, numberCmd, paralpCmd1, parphiCmd1, partheCmd1, particleCmd, polCmd, positionCmd, positionDirectory, posrot1Cmd1, posrot2Cmd1, possigmarCmd1, possigmaxCmd1, possigmayCmd1, radius0Cmd1, radiusCmd1, resethistCmd1, setintensityCmd, setsourceCmd, shapeCmd1, sourceDirectory, surfnormCmd1, tempCmd1, timeCmd, typeCmd1, useuserangaxisCmd1, and verbosityCmd.
Member Function Documentation
void G4GeneralParticleSourceMessenger::Destroy (void) static
Definition at line 93 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 93 of file G4GeneralParticleSourceMessenger.cc
Referenced by G4GeneralParticleSource::~G4GeneralParticleSource().
G4String G4GeneralParticleSourceMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 1723 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 1723 of file G4GeneralParticleSourceMessenger.cc
G4GeneralParticleSourceMessenger * G4GeneralParticleSourceMessenger::GetInstance (G4GeneralParticleSource * psc) static
Definition at line 86 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 86 of file G4GeneralParticleSourceMessenger.cc
References G4GeneralParticleSourceMessenger().
Referenced by G4GeneralParticleSource::G4GeneralParticleSource().
void G4GeneralParticleSourceMessenger::IonCommand (G4String newValues) private
Definition at line 1745 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 1745 of file G4GeneralParticleSourceMessenger.cc
References G4UIcommand::CommandFailed(), eplus, fAtomicMass, fAtomicNumber, fIonCharge, fIonExciteEnergy, fParticleGun, fShootIon, G4IonTable::GetIon(), G4IonTable::GetIonTable(), ionCmd, G4String::isNull(), keV, G4SingleParticleSource::SetParticleCharge(), G4SingleParticleSource::SetParticleDefinition(), G4UImessenger::StoD(), and G4UImessenger::StoI().
Referenced by SetNewValue().
void G4GeneralParticleSourceMessenger::IonLvlCommand (G4String newValues) private
Definition at line 1794 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 1794 of file G4GeneralParticleSourceMessenger.cc
References G4UIcommand::CommandFailed(), eplus, fAtomicMassL, fAtomicNumberL, fIonChargeL, fIonEnergyLevel, fParticleGun, fShootIon, G4IonTable::GetIon(), G4IonTable::GetIonTable(), ionLvlCmd, G4String::isNull(), G4SingleParticleSource::SetParticleCharge(), G4SingleParticleSource::SetParticleDefinition(), and G4UImessenger::StoI().
Referenced by SetNewValue().
void G4GeneralParticleSourceMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 1008 of file G4GeneralParticleSourceMessenger.cc.
View newest version in sPHENIX GitHub at line 1008 of file G4GeneralParticleSourceMessenger.cc
References a, G4GeneralParticleSource::AddaSource(), addsourceCmd, alphaCmd1, angfocusCmd, angrot1Cmd1, angrot2Cmd1, angsigmarCmd1, angsigmaxCmd1, angsigmayCmd1, angtypeCmd1, arbeintCmd1, G4SPSEneDistribution::ArbEnergyHisto(), G4SPSEneDistribution::ArbEnergyHistoFile(), arbintCmd1, G4SPSEneDistribution::ArbInterpolate(), G4SPSEneDistribution::Calculate(), calculateCmd1, centreCmd1, CHECKPG, G4GeneralParticleSource::ClearAll(), clearsourceCmd, confineCmd1, G4SPSPosDistribution::ConfineSourceToVolume(), G4SPSAngDistribution::DefineAngRefAxes(), G4GeneralParticleSource::DeleteaSource(), deletesourceCmd, diffspecCmd1, directionCmd, G4ParticleTable::DumpTable(), emaxCmd1, eminCmd1, energyCmd, energyspecCmd1, energytypeCmd1, engsigmaCmd1, G4SPSEneDistribution::EpnEnergyHisto(), ezeroCmd1, FatalException, fGPS, G4ParticleTable::FindParticle(), flatsamplingCmd, fParticleGun, fShootIon, G4cout, G4endl, G4Exception(), G4SingleParticleSource::GetAngDist(), G4SingleParticleSource::GetBiasRndm(), G4UIcommand::GetCommandName(), G4UIcommand::GetCommandPath(), G4GeneralParticleSource::GetCurrentSourceIndex(), G4GeneralParticleSource::GetCurrentSourceIntensity(), G4SingleParticleSource::GetEneDist(), G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4GeneralParticleSource::GetNumberofSource(), G4SingleParticleSource::GetPosDist(), getsourceCmd, gradientCmd1, halfxCmd1, halfyCmd1, halfzCmd1, histfileCmd1, histnameCmd1, histpointCmd1, histtype, G4SPSEneDistribution::InputDifferentialSpectra(), G4SPSEneDistribution::InputEnergySpectra(), interceptCmd1, ionCmd, IonCommand(), ionLvlCmd, IonLvlCommand(), listCmd, G4GeneralParticleSource::ListSource(), listsourceCmd, maxphiCmd1, maxthetaCmd1, minphiCmd1, minthetaCmd1, monoenergyCmd1, multiplevertexCmd, numberCmd, paralpCmd1, parphiCmd1, partheCmd1, particleCmd, particleTable, polCmd, positionCmd, posrot1Cmd1, posrot2Cmd1, possigmarCmd1, possigmaxCmd1, possigmayCmd1, radius0Cmd1, radiusCmd1, G4SPSRandomGenerator::ReSetHist(), G4SPSAngDistribution::ReSetHist(), G4SPSEneDistribution::ReSetHist(), resethistCmd1, G4SPSEneDistribution::SetAlpha(), G4SPSAngDistribution::SetAngDistType(), G4SPSAngDistribution::SetBeamSigmaInAngR(), G4SPSAngDistribution::SetBeamSigmaInAngX(), G4SPSAngDistribution::SetBeamSigmaInAngY(), G4SPSEneDistribution::SetBeamSigmaInE(), G4SPSPosDistribution::SetBeamSigmaInR(), G4SPSPosDistribution::SetBeamSigmaInX(), G4SPSPosDistribution::SetBeamSigmaInY(), G4SPSEneDistribution::SetBiasAlpha(), G4SPSPosDistribution::SetCentreCoords(), G4GeneralParticleSource::SetCurrentSourceIntensity(), G4GeneralParticleSource::SetCurrentSourceto(), G4SPSEneDistribution::SetEmax(), G4SPSEneDistribution::SetEmin(), G4SPSRandomGenerator::SetEnergyBias(), G4SPSEneDistribution::SetEnergyDisType(), G4SPSEneDistribution::SetEzero(), G4GeneralParticleSource::SetFlatSampling(), G4SPSAngDistribution::SetFocusPoint(), G4SPSEneDistribution::SetGradient(), G4SPSPosDistribution::SetHalfX(), G4SPSPosDistribution::SetHalfY(), G4SPSPosDistribution::SetHalfZ(), setintensityCmd, G4SPSEneDistribution::SetInterCept(), G4SPSAngDistribution::SetMaxPhi(), G4SPSAngDistribution::SetMaxTheta(), G4SPSAngDistribution::SetMinPhi(), G4SPSAngDistribution::SetMinTheta(), G4SPSEneDistribution::SetMonoEnergy(), G4GeneralParticleSource::SetMultipleVertex(), G4SingleParticleSource::SetNumberOfParticles(), G4SPSPosDistribution::SetParAlpha(), G4SPSPosDistribution::SetParPhi(), G4SPSPosDistribution::SetParTheta(), G4SingleParticleSource::SetParticleDefinition(), G4SPSAngDistribution::SetParticleMomentumDirection(), G4SingleParticleSource::SetParticlePolarization(), G4SingleParticleSource::SetParticleTime(), G4SPSRandomGenerator::SetPhiBias(), G4SPSPosDistribution::SetPosDisShape(), G4SPSPosDistribution::SetPosDisType(), G4SPSRandomGenerator::SetPosPhiBias(), G4SPSPosDistribution::SetPosRot1(), G4SPSPosDistribution::SetPosRot2(), G4SPSRandomGenerator::SetPosThetaBias(), G4SPSPosDistribution::SetRadius(), G4SPSPosDistribution::SetRadius0(), setsourceCmd, G4SPSEneDistribution::SetTemp(), G4SPSRandomGenerator::SetThetaBias(), G4SPSAngDistribution::SetUserWRTSurface(), G4SPSAngDistribution::SetUseUserAngAxis(), G4GeneralParticleSource::SetVerbosity(), G4SPSRandomGenerator::SetXBias(), G4SPSRandomGenerator::SetYBias(), G4SPSRandomGenerator::SetZBias(), shapeCmd1, sn, surfnormCmd1, tempCmd1, timeCmd, typeCmd1, G4SPSAngDistribution::UserDefAngPhi(), G4SPSAngDistribution::UserDefAngTheta(), G4SPSEneDistribution::UserEnergyHisto(), useuserangaxisCmd1, and verbosityCmd.
void G4GeneralParticleSourceMessenger::SetParticleGun (G4SingleParticleSource * fpg) inline
Definition at line 134 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 134 of file G4GeneralParticleSourceMessenger.hh
References fParticleGun.
Referenced by G4GeneralParticleSource::AddaSource(), G4GeneralParticleSource::G4GeneralParticleSource(), and G4GeneralParticleSource::SetCurrentSourceto().
Member Data Documentation
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::addsourceCmd private
Definition at line 164 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 164 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::alphaCmd1 private
Definition at line 250 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 250 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3VectorAndUnit* G4GeneralParticleSourceMessenger::angfocusCmd private
Definition at line 225 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 225 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::angrot1Cmd1 private
Definition at line 216 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 216 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::angrot2Cmd1 private
Definition at line 217 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 217 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::angsigmarCmd1 private
Definition at line 222 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 222 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::angsigmaxCmd1 private
Definition at line 223 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 223 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::angsigmayCmd1 private
Definition at line 224 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 224 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::angtypeCmd1 private
Definition at line 215 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 215 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIdirectory* G4GeneralParticleSourceMessenger::angularDirectory private
Definition at line 214 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 214 of file G4GeneralParticleSourceMessenger.hh
Referenced by ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::arbeintCmd1 private
Definition at line 255 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 255 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::arbintCmd1 private
Definition at line 285 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 285 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithoutParameter* G4GeneralParticleSourceMessenger::calculateCmd1 private
Definition at line 256 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 256 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3VectorAndUnit* G4GeneralParticleSourceMessenger::centreCmd1 private
Definition at line 178 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 178 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithoutParameter* G4GeneralParticleSourceMessenger::clearsourceCmd private
Definition at line 166 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 166 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::confineCmd1 private
Definition at line 192 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 192 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAnInteger* G4GeneralParticleSourceMessenger::deletesourceCmd private
Definition at line 170 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 170 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithABool* G4GeneralParticleSourceMessenger::diffspecCmd1 private
Definition at line 258 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 258 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::directionCmd private
Definition at line 298 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 298 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::emaxCmd1 private
Definition at line 247 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 247 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::eminCmd1 private
Definition at line 246 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 246 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::energyCmd private
Definition at line 299 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 299 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIdirectory* G4GeneralParticleSourceMessenger::energyDirectory private
Definition at line 244 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 244 of file G4GeneralParticleSourceMessenger.hh
Referenced by ~G4GeneralParticleSourceMessenger().
G4UIcmdWithABool* G4GeneralParticleSourceMessenger::energyspecCmd1 private
Definition at line 257 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 257 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::energytypeCmd1 private
Definition at line 245 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 245 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::engsigmaCmd1 private
Definition at line 249 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 249 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::ezeroCmd1 private
Definition at line 252 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 252 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4int G4GeneralParticleSourceMessenger::fAtomicMass private
Definition at line 306 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 306 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand().
G4int G4GeneralParticleSourceMessenger::fAtomicMassL private
Definition at line 311 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 311 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonLvlCommand().
G4int G4GeneralParticleSourceMessenger::fAtomicNumber private
Definition at line 305 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 305 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand().
G4int G4GeneralParticleSourceMessenger::fAtomicNumberL private
Definition at line 310 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 310 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonLvlCommand().
G4GeneralParticleSource* G4GeneralParticleSourceMessenger::fGPS private
Definition at line 154 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue().
G4int G4GeneralParticleSourceMessenger::fIonCharge private
Definition at line 307 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 307 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand().
G4int G4GeneralParticleSourceMessenger::fIonChargeL private
Definition at line 312 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 312 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonLvlCommand().
G4int G4GeneralParticleSourceMessenger::fIonEnergyLevel private
Definition at line 313 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 313 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonLvlCommand().
G4double G4GeneralParticleSourceMessenger::fIonExciteEnergy private
Definition at line 308 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 308 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand().
G4UIcmdWithABool* G4GeneralParticleSourceMessenger::flatsamplingCmd private
Definition at line 172 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 172 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4SingleParticleSource* G4GeneralParticleSourceMessenger::fParticleGun private
Definition at line 155 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 155 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand(), IonLvlCommand(), SetNewValue(), and SetParticleGun().
G4bool G4GeneralParticleSourceMessenger::fShootIon private
Definition at line 303 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 303 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand(), IonLvlCommand(), and SetNewValue().
G4UIcmdWithoutParameter* G4GeneralParticleSourceMessenger::getsourceCmd private
Definition at line 167 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 167 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIdirectory* G4GeneralParticleSourceMessenger::gpsDirectory private
Definition at line 160 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 160 of file G4GeneralParticleSourceMessenger.hh
Referenced by ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::gradientCmd1 private
Definition at line 253 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 253 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::halfxCmd1 private
Definition at line 181 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 181 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::halfyCmd1 private
Definition at line 182 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 182 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::halfzCmd1 private
Definition at line 183 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 183 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIdirectory* G4GeneralParticleSourceMessenger::histDirectory private
Definition at line 276 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 276 of file G4GeneralParticleSourceMessenger.hh
Referenced by ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::histfileCmd1 private
Definition at line 283 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 283 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::histnameCmd1 private
Definition at line 284 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 284 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::histpointCmd1 private
Definition at line 282 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 282 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4String G4GeneralParticleSourceMessenger::histtype private
Definition at line 157 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 157 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::interceptCmd1 private
Definition at line 254 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 254 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcommand* G4GeneralParticleSourceMessenger::ionCmd private
Definition at line 291 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 291 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonCommand(), SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcommand* G4GeneralParticleSourceMessenger::ionLvlCmd private
Definition at line 292 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 292 of file G4GeneralParticleSourceMessenger.hh
Referenced by IonLvlCommand(), SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithoutParameter* G4GeneralParticleSourceMessenger::listCmd private
Definition at line 300 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 300 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithoutParameter* G4GeneralParticleSourceMessenger::listsourceCmd private
Definition at line 165 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 165 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::maxphiCmd1 private
Definition at line 221 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 221 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::maxthetaCmd1 private
Definition at line 219 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 219 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::minphiCmd1 private
Definition at line 220 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 220 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::minthetaCmd1 private
Definition at line 218 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 218 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::monoenergyCmd1 private
Definition at line 248 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 248 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithABool* G4GeneralParticleSourceMessenger::multiplevertexCmd private
Definition at line 171 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 171 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAnInteger* G4GeneralParticleSourceMessenger::numberCmd private
Definition at line 296 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 296 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::paralpCmd1 private
Definition at line 189 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 189 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::parphiCmd1 private
Definition at line 191 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 191 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::partheCmd1 private
Definition at line 190 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 190 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::particleCmd private
Definition at line 293 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 293 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4ParticleTable* G4GeneralParticleSourceMessenger::particleTable private
Definition at line 156 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 156 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::polCmd private
Definition at line 295 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 295 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3VectorAndUnit* G4GeneralParticleSourceMessenger::positionCmd private
Definition at line 297 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 297 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIdirectory* G4GeneralParticleSourceMessenger::positionDirectory private
Definition at line 175 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 175 of file G4GeneralParticleSourceMessenger.hh
Referenced by ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::posrot1Cmd1 private
Definition at line 179 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 179 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWith3Vector* G4GeneralParticleSourceMessenger::posrot2Cmd1 private
Definition at line 180 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 180 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::possigmarCmd1 private
Definition at line 186 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 186 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::possigmaxCmd1 private
Definition at line 187 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 187 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::possigmayCmd1 private
Definition at line 188 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 188 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::radius0Cmd1 private
Definition at line 185 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 185 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::radiusCmd1 private
Definition at line 184 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 184 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::resethistCmd1 private
Definition at line 286 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 286 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::setintensityCmd private
Definition at line 169 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 169 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAnInteger* G4GeneralParticleSourceMessenger::setsourceCmd private
Definition at line 168 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 168 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::shapeCmd1 private
Definition at line 177 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 177 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIdirectory* G4GeneralParticleSourceMessenger::sourceDirectory private
Definition at line 163 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 163 of file G4GeneralParticleSourceMessenger.hh
Referenced by ~G4GeneralParticleSourceMessenger().
G4UIcmdWithABool* G4GeneralParticleSourceMessenger::surfnormCmd1 private
Definition at line 227 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 227 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADouble* G4GeneralParticleSourceMessenger::tempCmd1 private
Definition at line 251 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 251 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithADoubleAndUnit* G4GeneralParticleSourceMessenger::timeCmd private
Definition at line 294 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 294 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAString* G4GeneralParticleSourceMessenger::typeCmd1 private
Definition at line 176 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 176 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithABool* G4GeneralParticleSourceMessenger::useuserangaxisCmd1 private
Definition at line 226 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 226 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
G4UIcmdWithAnInteger* G4GeneralParticleSourceMessenger::verbosityCmd private
Definition at line 288 of file G4GeneralParticleSourceMessenger.hh.
View newest version in sPHENIX GitHub at line 288 of file G4GeneralParticleSourceMessenger.hh
Referenced by SetNewValue(), and ~G4GeneralParticleSourceMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4GeneralParticleSourceMessenger.hh
geant4/tree/geant4-10.6-release/source/event/src/G4GeneralParticleSourceMessenger.cc