ECCE @ EIC Software: G4H3Messenger Class Reference
G4H3Messenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4H3Messenger.hh>
Public Member Functions
G4H3Messenger (G4VAnalysisManager *manager)
virtual ~G4H3Messenger ()
virtual void SetNewValue (G4UIcommand *command, G4String value) final
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void CreateH3Cmd ()
void SetH3Cmd ()
Private Attributes
G4VAnalysisManager * fManager
Associated class.
std::unique_ptr
< G4AnalysisMessengerHelper > fHelper
std::unique_ptr< G4UIdirectory > fDirectory
std::unique_ptr< G4UIcommand > fCreateH3Cmd
std::unique_ptr< G4UIcommand > fSetH3Cmd
std::unique_ptr< G4UIcommand > fSetH3XCmd
std::unique_ptr< G4UIcommand > fSetH3YCmd
std::unique_ptr< G4UIcommand > fSetH3ZCmd
std::unique_ptr< G4UIcommand > fSetH3TitleCmd
std::unique_ptr< G4UIcommand > fSetH3XAxisCmd
std::unique_ptr< G4UIcommand > fSetH3YAxisCmd
std::unique_ptr< G4UIcommand > fSetH3ZAxisCmd
std::unique_ptr< G4UIcommand > fSetH3XAxisLogCmd
std::unique_ptr< G4UIcommand > fSetH3YAxisLogCmd
std::unique_ptr< G4UIcommand > fSetH3ZAxisLogCmd
G4int fXId
G4int fYId
G4AnalysisMessengerHelper::BinData fXData
G4AnalysisMessengerHelper::BinData fYData
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 45 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 45 of file G4H3Messenger.hh
Constructor & Destructor Documentation
G4H3Messenger::G4H3Messenger (G4VAnalysisManager * manager) explicit
Definition at line 42 of file G4H3Messenger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4H3Messenger.cc
References CreateH3Cmd(), fDirectory, fHelper, fSetH3TitleCmd, fSetH3XAxisCmd, fSetH3XAxisLogCmd, fSetH3XCmd, fSetH3YAxisCmd, fSetH3YAxisLogCmd, fSetH3YCmd, fSetH3ZAxisCmd, fSetH3ZAxisLogCmd, and SetH3Cmd().
G4H3Messenger::~G4H3Messenger () virtual
Definition at line 81 of file G4H3Messenger.cc.
View newest version in sPHENIX GitHub at line 81 of file G4H3Messenger.cc
Member Function Documentation
void G4H3Messenger::CreateH3Cmd () private
Definition at line 89 of file G4H3Messenger.cc.
View newest version in sPHENIX GitHub at line 89 of file G4H3Messenger.cc
References fCreateH3Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4H3Messenger().
void G4H3Messenger::SetH3Cmd () private
Definition at line 217 of file G4H3Messenger.cc.
View newest version in sPHENIX GitHub at line 217 of file G4H3Messenger.cc
References fSetH3Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4H3Messenger().
void G4H3Messenger::SetNewValue (G4UIcommand * command, G4String value) final virtual
Reimplemented from G4UImessenger.
Definition at line 331 of file G4H3Messenger.cc.
View newest version in sPHENIX GitHub at line 331 of file G4H3Messenger.cc
References G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToInt(), G4VAnalysisManager::CreateH3(), fCreateH3Cmd, fHelper, fManager, G4AnalysisMessengerHelper::BinData::fNbins, G4AnalysisMessengerHelper::BinData::fSbinScheme, fSetH3Cmd, fSetH3TitleCmd, fSetH3XAxisCmd, fSetH3XAxisLogCmd, fSetH3XCmd, fSetH3YAxisCmd, fSetH3YAxisLogCmd, fSetH3YCmd, fSetH3ZAxisCmd, fSetH3ZAxisLogCmd, fSetH3ZCmd, G4AnalysisMessengerHelper::BinData::fSfcn, G4AnalysisMessengerHelper::BinData::fSunit, G4AnalysisMessengerHelper::BinData::fVmax, G4AnalysisMessengerHelper::BinData::fVmin, fXData, fXId, fYData, fYId, G4UIcommand::GetParameterEntries(), G4Analysis::GetUnitValue(), Dataset::parameters, G4VAnalysisManager::SetH3(), G4VAnalysisManager::SetH3Title(), G4VAnalysisManager::SetH3XAxisIsLog(), G4VAnalysisManager::SetH3XAxisTitle(), G4VAnalysisManager::SetH3YAxisIsLog(), G4VAnalysisManager::SetH3YAxisTitle(), G4VAnalysisManager::SetH3ZAxisIsLog(), G4VAnalysisManager::SetH3ZAxisTitle(), title(), G4Analysis::Tokenize(), and xaxis.
Member Data Documentation
std::unique_ptr<G4UIcommand> G4H3Messenger::fCreateH3Cmd private
Definition at line 62 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4H3Messenger.hh
Referenced by CreateH3Cmd(), and SetNewValue().
std::unique_ptr<G4UIdirectory> G4H3Messenger::fDirectory private
Definition at line 60 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4H3Messenger.hh
Referenced by G4H3Messenger().
std::unique_ptr<G4AnalysisMessengerHelper> G4H3Messenger::fHelper private
Definition at line 59 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
G4VAnalysisManager* G4H3Messenger::fManager private
Associated class.
Definition at line 58 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 58 of file G4H3Messenger.hh
Referenced by SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3Cmd private
Definition at line 63 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4H3Messenger.hh
Referenced by SetH3Cmd(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3TitleCmd private
Definition at line 67 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3XAxisCmd private
Definition at line 68 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3XAxisLogCmd private
Definition at line 71 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3XCmd private
Definition at line 64 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3YAxisCmd private
Definition at line 69 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3YAxisLogCmd private
Definition at line 72 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3YCmd private
Definition at line 65 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3ZAxisCmd private
Definition at line 70 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3ZAxisLogCmd private
Definition at line 73 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4H3Messenger.hh
Referenced by G4H3Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H3Messenger::fSetH3ZCmd private
Definition at line 66 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4H3Messenger.hh
Referenced by SetNewValue().
G4AnalysisMessengerHelper::BinData G4H3Messenger::fXData private
Definition at line 77 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4H3Messenger.hh
Referenced by SetNewValue().
G4int G4H3Messenger::fXId private
Definition at line 75 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4H3Messenger.hh
Referenced by SetNewValue().
G4AnalysisMessengerHelper::BinData G4H3Messenger::fYData private
Definition at line 78 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4H3Messenger.hh
Referenced by SetNewValue().
G4int G4H3Messenger::fYId private
Definition at line 76 of file G4H3Messenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4H3Messenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4H3Messenger.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4H3Messenger.cc