ECCE @ EIC Software: G4ScoreLogColorMap Class Reference
G4ScoreLogColorMap Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoreLogColorMap.hh>
Public Member Functions
G4ScoreLogColorMap (G4String mName)
virtual ~G4ScoreLogColorMap ()
virtual void GetMapColor (G4double val, G4double color[4])
virtual void DrawColorChartBar (G4int nPoint)
virtual void DrawColorChartText (G4int nPoint)
Public Member Functions inherited from G4VScoreColorMap
G4VScoreColorMap (G4String mName)
virtual ~G4VScoreColorMap ()
G4String GetName () const
void SetFloatingMinMax (G4bool vl=true)
G4bool IfFloatMinMax () const
void SetMinMax (G4double minVal, G4double maxVal)
G4double GetMin () const
G4double GetMax () const
virtual void DrawColorChart (G4int nPoint=5)
void SetPSUnit (G4String &unit)
void SetPSName (G4String &psName)
Additional Inherited Members
Protected Attributes inherited from G4VScoreColorMap
G4String fName
G4bool ifFloat
G4double fMinVal
G4double fMaxVal
G4VVisManager * fVisManager
G4String fPSUnit
G4String fPSName
Detailed Description
Definition at line 35 of file G4ScoreLogColorMap.hh.
View newest version in sPHENIX GitHub at line 35 of file G4ScoreLogColorMap.hh
Constructor & Destructor Documentation
G4ScoreLogColorMap::G4ScoreLogColorMap (G4String mName)
Definition at line 43 of file G4ScoreLogColorMap.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ScoreLogColorMap.cc
G4ScoreLogColorMap::~G4ScoreLogColorMap () virtual
Definition at line 47 of file G4ScoreLogColorMap.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ScoreLogColorMap.cc
Member Function Documentation
void G4ScoreLogColorMap::DrawColorChartBar (G4int nPoint) virtual
Reimplemented from G4VScoreColorMap.
Definition at line 141 of file G4ScoreLogColorMap.cc.
View newest version in sPHENIX GitHub at line 141 of file G4ScoreLogColorMap.cc
References c, col, G4VVisManager::Draw2D(), G4VScoreColorMap::fMaxVal, G4VScoreColorMap::fMinVal, G4VScoreColorMap::fVisManager, GetMapColor(), max, min, Acts::Test::rb, G4Visible::SetVisAttributes(), smax, Acts::Test::step(), and y.
void G4ScoreLogColorMap::DrawColorChartText (G4int nPoint) virtual
Reimplemented from G4VScoreColorMap.
Definition at line 170 of file G4ScoreLogColorMap.cc.
View newest version in sPHENIX GitHub at line 170 of file G4ScoreLogColorMap.cc
References a, b, c, color(), G4VVisManager::Draw2D(), G4VScoreColorMap::fMaxVal, G4VScoreColorMap::fMinVal, G4VScoreColorMap::fPSName, G4VScoreColorMap::fPSUnit, G4VScoreColorMap::fVisManager, GetMapColor(), max, min, n, G4VMarker::SetScreenSize(), G4Visible::SetVisAttributes(), and v.
void G4ScoreLogColorMap::GetMapColor (G4double val, G4double color[4]) virtual
Implements G4VScoreColorMap.
Definition at line 51 of file G4ScoreLogColorMap.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ScoreLogColorMap.cc
References a, b, G4UIcommand::ConvertToString(), G4VScoreColorMap::fMaxVal, G4VScoreColorMap::fMinVal, G4Exception(), JustWarning, and message().
Referenced by DrawColorChartBar(), and DrawColorChartText().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoreLogColorMap.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoreLogColorMap.cc