ECCE @ EIC Software: G4OpWLS Class Reference
G4OpWLS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/optical/include/G4OpWLS.hh>
Public Member Functions
G4OpWLS (const G4String &processName="OpWLS", G4ProcessType type=fOptical)
virtual ~G4OpWLS ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &aParticleType) override
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4PhysicsTable * GetIntegralTable () const
virtual void DumpPhysicsTable () const
void UseTimeProfile (const G4String name)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Attributes
G4VWLSTimeGeneratorProfile * WLSTimeGeneratorProfile
G4PhysicsTable * theIntegralTable
Private Member Functions
G4OpWLS (const G4OpWLS &right)=delete
G4OpWLS & operator= (const G4OpWLS &right)=delete
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Detailed Description
Definition at line 71 of file G4OpWLS.hh.
View newest version in sPHENIX GitHub at line 71 of file G4OpWLS.hh
Constructor & Destructor Documentation
G4OpWLS::G4OpWLS (const G4String & processName = "OpWLS", G4ProcessType type = fOptical) explicit
Definition at line 67 of file G4OpWLS.cc.
View newest version in sPHENIX GitHub at line 67 of file G4OpWLS.cc
References fOpWLS, G4cout, G4endl, G4VProcess::GetProcessName(), G4VProcess::SetProcessSubType(), theIntegralTable, G4VProcess::verboseLevel, and WLSTimeGeneratorProfile.
G4OpWLS::~G4OpWLS () virtual
Definition at line 84 of file G4OpWLS.cc.
View newest version in sPHENIX GitHub at line 84 of file G4OpWLS.cc
References G4PhysicsTable::clearAndDestroy(), theIntegralTable, and WLSTimeGeneratorProfile.
G4OpWLS::G4OpWLS (const G4OpWLS & right) private delete
Member Function Documentation
void G4OpWLS::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 296 of file G4OpWLS.cc.
View newest version in sPHENIX GitHub at line 296 of file G4OpWLS.cc
References G4PhysicsTable::clearAndDestroy(), G4PhysicsVector::Energy(), G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), G4MaterialPropertiesTable::GetProperty(), G4PhysicsVector::GetVectorLength(), G4PhysicsTable::insertAt(), kWLSCOMPONENT, and theIntegralTable.
void G4OpWLS::DumpPhysicsTable () const inline virtual
Definition at line 134 of file G4OpWLS.hh.
View newest version in sPHENIX GitHub at line 134 of file G4OpWLS.hh
References G4PhysicsVector::DumpValues(), G4PhysicsTable::entries(), theIntegralTable, and v.
G4PhysicsTable * G4OpWLS::GetIntegralTable () const inline virtual
Definition at line 128 of file G4OpWLS.hh.
View newest version in sPHENIX GitHub at line 128 of file G4OpWLS.hh
References theIntegralTable.
G4double G4OpWLS::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition *) override virtual
Implements G4VDiscreteProcess.
Definition at line 392 of file G4OpWLS.cc.
View newest version in sPHENIX GitHub at line 392 of file G4OpWLS.cc
References DBL_MAX, G4Track::GetDynamicParticle(), G4Track::GetMaterial(), G4Material::GetMaterialPropertiesTable(), G4DynamicParticle::GetTotalEnergy(), and kWLSABSLENGTH.
G4bool G4OpWLS::IsApplicable (const G4ParticleDefinition & aParticleType) inline override virtual
Reimplemented from G4VProcess.
Definition at line 122 of file G4OpWLS.hh.
View newest version in sPHENIX GitHub at line 122 of file G4OpWLS.hh
References G4OpticalPhoton::OpticalPhoton().
G4OpWLS& G4OpWLS::operator= (const G4OpWLS & right) private delete
G4VParticleChange * G4OpWLS::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 101 of file G4OpWLS.cc.
View newest version in sPHENIX GitHub at line 101 of file G4OpWLS.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, G4MaterialPropertiesTable::ConstPropertyExists(), CLHEP::Hep3Vector::cross(), fStopAndKill, G4cout, G4endl, G4Poisson(), G4UniformRand, G4VWLSTimeGeneratorProfile::GenerateTime(), G4Track::GetDynamicParticle(), G4PhysicsOrderedFreeVector::GetEnergy(), G4StepPoint::GetGlobalTime(), G4Material::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterial(), G4Material::GetMaterialPropertiesTable(), G4PhysicsOrderedFreeVector::GetMaxValue(), G4VParticleChange::GetNumberOfSecondaries(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4MaterialPropertiesTable::GetProperty(), G4Track::GetTouchableHandle(), G4Track::GetTrackID(), G4ParticleChange::Initialize(), kWLSCOMPONENT, kWLSMEANNUMBERPHOTONS, kWLSTIMECONSTANT, ns, G4OpticalPhoton::OpticalPhoton(), Acts::VectorHelpers::perp(), phi, G4VDiscreteProcess::PostStepDoIt(), G4VParticleChange::ProposeTrackStatus(), G4DynamicParticle::SetKineticEnergy(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetParentID(), G4DynamicParticle::SetPolarization(), G4Track::SetTouchableHandle(), theIntegralTable, twopi, CLHEP::Hep3Vector::unit(), G4VProcess::verboseLevel, WLSTimeGeneratorProfile, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4OpWLS::UseTimeProfile (const G4String name)
Definition at line 426 of file G4OpWLS.cc.
View newest version in sPHENIX GitHub at line 426 of file G4OpWLS.cc
References FatalException, G4Exception(), and WLSTimeGeneratorProfile.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetWLSTimeProfile().
Member Data Documentation
G4PhysicsTable* G4OpWLS::theIntegralTable protected
Definition at line 109 of file G4OpWLS.hh.
View newest version in sPHENIX GitHub at line 109 of file G4OpWLS.hh
Referenced by BuildPhysicsTable(), DumpPhysicsTable(), G4OpWLS(), GetIntegralTable(), PostStepDoIt(), and ~G4OpWLS().
G4VWLSTimeGeneratorProfile* G4OpWLS::WLSTimeGeneratorProfile protected
Definition at line 108 of file G4OpWLS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4OpWLS.hh
Referenced by G4OpWLS(), PostStepDoIt(), UseTimeProfile(), and ~G4OpWLS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/optical/include/G4OpWLS.hh
geant4/tree/geant4-10.6-release/source/processes/optical/src/G4OpWLS.cc