ECCE @ EIC Software: G4GFlashSpot Class Reference
G4GFlashSpot Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/G4GFlashSpot.hh>
Public Member Functions
G4GFlashSpot (const GFlashEnergySpot *aSpot, const G4FastTrack *aTrack, G4TouchableHandle aH)
~G4GFlashSpot ()
const GFlashEnergySpot * GetEnergySpot () const
const G4FastTrack * GetOriginatorTrack () const
G4TouchableHandle GetTouchableHandle () const
G4ThreeVector GetPosition () const
Private Attributes
const GFlashEnergySpot * theSpot
const G4FastTrack * theTrack
G4TouchableHandle theHandle
Detailed Description
Definition at line 47 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 47 of file G4GFlashSpot.hh
Constructor & Destructor Documentation
G4GFlashSpot::G4GFlashSpot (const GFlashEnergySpot * aSpot, const G4FastTrack * aTrack, G4TouchableHandle aH) inline
Definition at line 51 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 51 of file G4GFlashSpot.hh
G4GFlashSpot::~G4GFlashSpot () inline
Definition at line 55 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 55 of file G4GFlashSpot.hh
Member Function Documentation
const GFlashEnergySpot* G4GFlashSpot::GetEnergySpot () const inline
Definition at line 57 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 57 of file G4GFlashSpot.hh
References theSpot.
Referenced by ExGflash1SensitiveDetector::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash2SensitiveDetector::ProcessHits().
const G4FastTrack* G4GFlashSpot::GetOriginatorTrack () const inline
Definition at line 59 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 59 of file G4GFlashSpot.hh
References theTrack.
Referenced by GetPosition(), and G4VGFlashSensitiveDetector::Hit().
G4ThreeVector G4GFlashSpot::GetPosition () const inline
Definition at line 63 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GFlashSpot.hh
References GetOriginatorTrack(), G4Track::GetPosition(), and G4FastTrack::GetPrimaryTrack().
Referenced by G4VGFlashSensitiveDetector::Hit().
G4TouchableHandle G4GFlashSpot::GetTouchableHandle () const inline
Definition at line 61 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 61 of file G4GFlashSpot.hh
References theHandle.
Referenced by G4VGFlashSensitiveDetector::Hit(), ExGflash2SensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash1SensitiveDetector::ProcessHits().
Member Data Documentation
G4TouchableHandle G4GFlashSpot::theHandle private
Definition at line 70 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 70 of file G4GFlashSpot.hh
Referenced by GetTouchableHandle().
const GFlashEnergySpot* G4GFlashSpot::theSpot private
Definition at line 68 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 68 of file G4GFlashSpot.hh
Referenced by GetEnergySpot().
const G4FastTrack* G4GFlashSpot::theTrack private
Definition at line 69 of file G4GFlashSpot.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GFlashSpot.hh
Referenced by GetOriginatorTrack().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/G4GFlashSpot.hh