ECCE @ EIC Software: G4ErrorMessenger Class Reference
G4ErrorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorMessenger.hh>
Public Member Functions
G4ErrorMessenger (G4ErrorStepLengthLimitProcess *lengthAct, G4ErrorMagFieldLimitProcess *magAct, G4ErrorEnergyLoss *elossAct)
~G4ErrorMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4ErrorStepLengthLimitProcess * StepLengthAction
G4ErrorMagFieldLimitProcess * MagFieldAction
G4ErrorEnergyLoss * EnergyLossAction
G4UIdirectory * myDir
G4UIdirectory * myDirLimits
G4UIcmdWithADoubleAndUnit * StepLengthLimitCmd
G4UIcmdWithADouble * MagFieldLimitCmd
G4UIcmdWithADouble * EnergyLossCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 52 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ErrorMessenger.hh
Constructor & Destructor Documentation
G4ErrorMessenger::G4ErrorMessenger (G4ErrorStepLengthLimitProcess * lengthAct, G4ErrorMagFieldLimitProcess * magAct, G4ErrorEnergyLoss * elossAct)
Definition at line 47 of file G4ErrorMessenger.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ErrorMessenger.cc
References G4UIcommand::AvailableForStates(), EnergyLossCmd, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_PreInit, MagFieldLimitCmd, myDir, myDirLimits, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcommand::SetGuidance(), and StepLengthLimitCmd.
G4ErrorMessenger::~G4ErrorMessenger ()
Definition at line 74 of file G4ErrorMessenger.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ErrorMessenger.cc
References EnergyLossCmd, MagFieldLimitCmd, myDir, myDirLimits, and StepLengthLimitCmd.
Member Function Documentation
void G4ErrorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 85 of file G4ErrorMessenger.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ErrorMessenger.cc
References EnergyLossAction, EnergyLossCmd, G4cout, G4endl, G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), MagFieldAction, MagFieldLimitCmd, G4ErrorEnergyLoss::SetStepLimit(), G4VErrorLimitProcess::SetStepLimit(), StepLengthAction, StepLengthLimitCmd, and G4ErrorPropagatorData::verbose().
Member Data Documentation
G4ErrorEnergyLoss* G4ErrorMessenger::EnergyLossAction private
Definition at line 67 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ErrorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADouble* G4ErrorMessenger::EnergyLossCmd private
Definition at line 74 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ErrorMessenger.hh
Referenced by G4ErrorMessenger(), SetNewValue(), and ~G4ErrorMessenger().
G4ErrorMagFieldLimitProcess* G4ErrorMessenger::MagFieldAction private
Definition at line 66 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ErrorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADouble* G4ErrorMessenger::MagFieldLimitCmd private
Definition at line 73 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ErrorMessenger.hh
Referenced by G4ErrorMessenger(), SetNewValue(), and ~G4ErrorMessenger().
G4UIdirectory* G4ErrorMessenger::myDir private
Definition at line 69 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ErrorMessenger.hh
Referenced by G4ErrorMessenger(), and ~G4ErrorMessenger().
G4UIdirectory* G4ErrorMessenger::myDirLimits private
Definition at line 70 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ErrorMessenger.hh
Referenced by G4ErrorMessenger(), and ~G4ErrorMessenger().
G4ErrorStepLengthLimitProcess* G4ErrorMessenger::StepLengthAction private
Definition at line 65 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ErrorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit* G4ErrorMessenger::StepLengthLimitCmd private
Definition at line 72 of file G4ErrorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ErrorMessenger.hh
Referenced by G4ErrorMessenger(), SetNewValue(), and ~G4ErrorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorMessenger.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorMessenger.cc