ECCE @ EIC Software: G4VecpssrMiModel Class Reference
G4VecpssrMiModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VecpssrMiModel.hh>
Public Member Functions
G4VecpssrMiModel ()
virtual ~G4VecpssrMiModel ()
virtual G4double CalculateM1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
virtual G4double CalculateM2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
virtual G4double CalculateM3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
virtual G4double CalculateM4CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
virtual G4double CalculateM5CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
Private Member Functions
G4VecpssrMiModel (const G4VecpssrMiModel &)
G4VecpssrMiModel & operator= (const G4VecpssrMiModel &right)
Detailed Description
Definition at line 48 of file G4VecpssrMiModel.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VecpssrMiModel.hh
Constructor & Destructor Documentation
G4VecpssrMiModel::G4VecpssrMiModel ()
Definition at line 45 of file G4VecpssrMiModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VecpssrMiModel.cc
G4VecpssrMiModel::~G4VecpssrMiModel () virtual
Definition at line 50 of file G4VecpssrMiModel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VecpssrMiModel.cc
G4VecpssrMiModel::G4VecpssrMiModel (const G4VecpssrMiModel &) private
Member Function Documentation
virtual G4double G4VecpssrMiModel::CalculateM1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrFormFactorMixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
virtual G4double G4VecpssrMiModel::CalculateM2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrFormFactorMixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
virtual G4double G4VecpssrMiModel::CalculateM3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrFormFactorMixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
virtual G4double G4VecpssrMiModel::CalculateM4CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrFormFactorMixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
virtual G4double G4VecpssrMiModel::CalculateM5CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrFormFactorMixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
G4VecpssrMiModel& G4VecpssrMiModel::operator= (const G4VecpssrMiModel & right) private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VecpssrMiModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VecpssrMiModel.cc