ECCE @ EIC Software: G4tgbRotationMatrixMgr Class Reference
G4tgbRotationMatrixMgr Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbRotationMatrixMgr.hh>
Public Member Functions
~G4tgbRotationMatrixMgr ()
G4RotationMatrix * FindOrBuildG4RotMatrix (const G4String &name)
G4RotationMatrix * FindG4RotMatrix (const G4String &name)
G4tgbRotationMatrix * FindOrBuildTgbRotMatrix (const G4String &name)
G4tgbRotationMatrix * FindTgbRotMatrix (const G4String &name)
const G4mstgbrotm GetTgbRotMatList () const
const G4msg4rotm & GetG4RotMatList () const
Static Public Member Functions
static G4tgbRotationMatrixMgr * GetInstance ()
Private Member Functions
G4tgbRotationMatrixMgr ()
void CopyRotMats ()
Private Attributes
G4mstgbrotm theTgbRotMats
G4msg4rotm theG4RotMats
Static Private Attributes
static G4ThreadLocal
G4tgbRotationMatrixMgr * theInstance = 0
Detailed Description
Definition at line 55 of file G4tgbRotationMatrixMgr.hh.
View newest version in sPHENIX GitHub at line 55 of file G4tgbRotationMatrixMgr.hh
Constructor & Destructor Documentation
G4tgbRotationMatrixMgr::~G4tgbRotationMatrixMgr ()
Definition at line 65 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 65 of file G4tgbRotationMatrixMgr.cc
References theInstance, and theTgbRotMats.
G4tgbRotationMatrixMgr::G4tgbRotationMatrixMgr () private
Definition at line 47 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 47 of file G4tgbRotationMatrixMgr.cc
Referenced by GetInstance().
Member Function Documentation
void G4tgbRotationMatrixMgr::CopyRotMats () private
Definition at line 79 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 79 of file G4tgbRotationMatrixMgr.cc
References G4tgrRotationMatrixFactory::GetInstance(), G4tgbRotationMatrix::GetName(), G4tgrRotationMatrixFactory::GetRotMatMap(), and theTgbRotMats.
Referenced by GetInstance().
G4RotationMatrix * G4tgbRotationMatrixMgr::FindG4RotMatrix (const G4String & name)
Definition at line 116 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 116 of file G4tgbRotationMatrixMgr.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4RotMats.
Referenced by FindOrBuildG4RotMatrix().
G4RotationMatrix * G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix (const G4String & name)
Definition at line 95 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 95 of file G4tgbRotationMatrixMgr.cc
References G4tgbRotationMatrix::BuildG4RotMatrix(), FindG4RotMatrix(), FindOrBuildTgbRotMatrix(), G4cout, G4endl, and G4tgrMessenger::GetVerboseLevel().
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::FindOrConstructG4Solid(), and G4tgbPlaceParameterisation::G4tgbPlaceParameterisation().
G4tgbRotationMatrix * G4tgbRotationMatrixMgr::FindOrBuildTgbRotMatrix (const G4String & name)
Definition at line 140 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 140 of file G4tgbRotationMatrixMgr.cc
References FatalException, FindTgbRotMatrix(), and G4Exception().
Referenced by FindOrBuildG4RotMatrix().
G4tgbRotationMatrix * G4tgbRotationMatrixMgr::FindTgbRotMatrix (const G4String & name)
Definition at line 156 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 156 of file G4tgbRotationMatrixMgr.cc
References theTgbRotMats.
Referenced by FindOrBuildTgbRotMatrix().
const G4msg4rotm& G4tgbRotationMatrixMgr::GetG4RotMatList () const inline
Definition at line 78 of file G4tgbRotationMatrixMgr.hh.
View newest version in sPHENIX GitHub at line 78 of file G4tgbRotationMatrixMgr.hh
References theG4RotMats.
Referenced by G4tgbVolumeMgr::DumpSummary().
G4tgbRotationMatrixMgr * G4tgbRotationMatrixMgr::GetInstance (void) static
Definition at line 53 of file G4tgbRotationMatrixMgr.cc.
View newest version in sPHENIX GitHub at line 53 of file G4tgbRotationMatrixMgr.cc
References CopyRotMats(), G4tgbRotationMatrixMgr(), and theInstance.
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbVolumeMgr::DumpSummary(), G4tgbVolume::FindOrConstructG4Solid(), and G4tgbPlaceParameterisation::G4tgbPlaceParameterisation().
const G4mstgbrotm G4tgbRotationMatrixMgr::GetTgbRotMatList () const inline
Definition at line 77 of file G4tgbRotationMatrixMgr.hh.
View newest version in sPHENIX GitHub at line 77 of file G4tgbRotationMatrixMgr.hh
References theTgbRotMats.
Member Data Documentation
G4msg4rotm G4tgbRotationMatrixMgr::theG4RotMats private
Definition at line 90 of file G4tgbRotationMatrixMgr.hh.
View newest version in sPHENIX GitHub at line 90 of file G4tgbRotationMatrixMgr.hh
Referenced by FindG4RotMatrix(), and GetG4RotMatList().
G4ThreadLocal G4tgbRotationMatrixMgr * G4tgbRotationMatrixMgr::theInstance = 0 static private
Definition at line 85 of file G4tgbRotationMatrixMgr.hh.
View newest version in sPHENIX GitHub at line 85 of file G4tgbRotationMatrixMgr.hh
Referenced by GetInstance(), and ~G4tgbRotationMatrixMgr().
G4mstgbrotm G4tgbRotationMatrixMgr::theTgbRotMats private
Definition at line 89 of file G4tgbRotationMatrixMgr.hh.
View newest version in sPHENIX GitHub at line 89 of file G4tgbRotationMatrixMgr.hh
Referenced by CopyRotMats(), FindTgbRotMatrix(), GetTgbRotMatList(), and ~G4tgbRotationMatrixMgr().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbRotationMatrixMgr.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbRotationMatrixMgr.cc