ECCE @ EIC Software: IORTDetectorConstruction Class Reference
IORTDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/include/IORTDetectorConstruction.hh>
Public Member Functions
IORTDetectorConstruction (G4VPhysicalVolume *)
~IORTDetectorConstruction ()
G4ThreeVector GetDetectorToWorldPosition ()
G4ThreeVector GetDetectorToPhantomPosition ()
void SetDetectorPosition ()
bool IsInside (G4double detectorX, G4double detectorY, G4double detectorZ, G4double phantomX, G4double phantomY, G4double phantomZ, G4ThreeVector detToPhantomPosition)
G4bool SetPhantomMaterial (G4String material)
void SetVoxelSize (G4double sizeX, G4double sizeY, G4double sizeZ)
void SetDetectorSize (G4double sizeX, G4double sizeY, G4double sizeZ)
void SetPhantomSize (G4double sizeX, G4double sizeY, G4double sizeZ)
void SetPhantomPosition (G4ThreeVector)
void SetDetectorToPhantomPosition (G4ThreeVector DetectorToPhantomPosition)
void UpdateGeometry ()
void DeleteDisc ()
void ConstructDisc ()
void PrintParameters ()
G4LogicalVolume * GetDetectorLogicalVolume ()
G4bool SetDiscoMaterialIORT (G4String material)
void SetOuterRadiusDiscoIORT (G4double outerr)
void SetinnerRadiusDiscoIORT (G4double innerr)
void SetheightDiscoIORT (G4double height)
void SetDiscoXPositionIORT (G4double xpos)
void SetDiscoYPositionIORT (G4double ypos)
void SetDiscoZPositionIORT (G4double zpos)
G4bool SetDiscoMaterialIORT1 (G4String material)
void SetOuterRadiusDiscoIORT1 (G4double outerr)
void SetinnerRadiusDiscoIORT1 (G4double innerr)
void SetheightDiscoIORT1 (G4double height)
void SetDiscoXPositionIORT1 (G4double xpos)
void SetAngleDiscoIORT0 (G4double phi0)
Private Member Functions
void ConstructPhantom ()
void ConstructDetector ()
void ConstructSensitiveDetector ()
void ParametersCheck ()
Private Attributes
IORTDetectorMessenger * detectorMessenger
G4VisAttributes * red
G4VPhysicalVolume * motherPhys
G4Box * phantom
G4Box * detector
G4LogicalVolume * phantomLogicalVolume
G4LogicalVolume * detectorLogicalVolume
G4VPhysicalVolume * phantomPhysicalVolume
G4VPhysicalVolume * detectorPhysicalVolume
G4double phantomSizeX
G4double phantomSizeY
G4double phantomSizeZ
G4double detectorSizeX
G4double detectorSizeY
G4double detectorSizeZ
G4ThreeVector phantomPosition
G4ThreeVector detectorPosition
G4ThreeVector detectorToPhantomPosition
G4Material * phantomMaterial
G4Material * detectorMaterial
G4Region * aRegion
G4Tubs * solidDiscoIORT0
G4LogicalVolume * logicDiscoIORT0
G4VPhysicalVolume * physiDiscoIORT0
G4double AngleDiscoIORT0
G4VisAttributes * white
G4VisAttributes * gray
G4VisAttributes * gray1
G4double innerRadiusDiscoIORT
G4double OuterRadiusDiscoIORT
G4double heightDiscoIORT
G4double DiscoXPositionIORT
G4double DiscoYPositionIORT
G4double DiscoZPositionIORT
G4Tubs * solidDiscoIORT
G4LogicalVolume * logicDiscoIORT
G4VPhysicalVolume * physiDiscoIORT
G4Material * DiscoMaterialIORT
G4double innerRadiusDiscoIORT1
G4double OuterRadiusDiscoIORT1
G4double heightDiscoIORT1
G4double DiscoXPositionIORT1
G4Tubs * solidDiscoIORT1
G4LogicalVolume * logicDiscoIORT1
G4VPhysicalVolume * physiDiscoIORT1
G4Material * DiscoMaterialIORT1
Detailed Description
Definition at line 55 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file IORTDetectorConstruction.hh
Constructor & Destructor Documentation
IORTDetectorConstruction::IORTDetectorConstruction (G4VPhysicalVolume * physicalTreatmentRoom)
Definition at line 69 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 69 of file IORTDetectorConstruction.cc
References cm, deg, detectorMessenger, detectorSizeX, detectorSizeY, detectorSizeZ, mm, SetAngleDiscoIORT0(), SetDetectorSize(), SetDetectorToPhantomPosition(), SetDiscoMaterialIORT(), SetDiscoMaterialIORT1(), SetDiscoXPositionIORT(), SetDiscoXPositionIORT1(), SetDiscoYPositionIORT(), SetDiscoZPositionIORT(), SetheightDiscoIORT(), SetheightDiscoIORT1(), SetinnerRadiusDiscoIORT(), SetinnerRadiusDiscoIORT1(), SetOuterRadiusDiscoIORT(), SetOuterRadiusDiscoIORT1(), SetPhantomMaterial(), SetPhantomPosition(), SetPhantomSize(), and UpdateGeometry().
IORTDetectorConstruction::~IORTDetectorConstruction ()
Definition at line 139 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 139 of file IORTDetectorConstruction.cc
References detectorMessenger.
Member Function Documentation
void IORTDetectorConstruction::ConstructDetector () private
Definition at line 205 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 205 of file IORTDetectorConstruction.cc
References aRegion, detector, detectorLogicalVolume, detectorMaterial, detectorPhysicalVolume, detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, G4cout, G4endl, and phantomPhysicalVolume.
Referenced by UpdateGeometry().
void IORTDetectorConstruction::ConstructDisc ()
Definition at line 248 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 248 of file IORTDetectorConstruction.cc
References AngleDiscoIORT0, deg, detectorMaterial, detectorPhysicalVolume, DiscoMaterialIORT, DiscoMaterialIORT1, DiscoXPositionIORT, DiscoYPositionIORT, DiscoZPositionIORT, gray, gray1, heightDiscoIORT, heightDiscoIORT1, innerRadiusDiscoIORT, innerRadiusDiscoIORT1, OuterRadiusDiscoIORT, OuterRadiusDiscoIORT1, phi, physiDiscoIORT, physiDiscoIORT0, physiDiscoIORT1, CLHEP::HepRotation::rotateY(), solidDiscoIORT, solidDiscoIORT0, solidDiscoIORT1, and white.
Referenced by UpdateGeometry().
void IORTDetectorConstruction::ConstructPhantom () private
Definition at line 151 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 151 of file IORTDetectorConstruction.cc
References motherPhys, phantom, phantomLogicalVolume, phantomMaterial, phantomPhysicalVolume, phantomPosition, phantomSizeX, phantomSizeY, phantomSizeZ, and red.
Referenced by UpdateGeometry().
void IORTDetectorConstruction::ConstructSensitiveDetector () private
void IORTDetectorConstruction::DeleteDisc ()
Definition at line 599 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 599 of file IORTDetectorConstruction.cc
References pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), logicDiscoIORT, logicDiscoIORT0, logicDiscoIORT1, physiDiscoIORT, physiDiscoIORT0, physiDiscoIORT1, solidDiscoIORT, solidDiscoIORT0, and solidDiscoIORT1.
G4LogicalVolume* IORTDetectorConstruction::GetDetectorLogicalVolume () inline
Definition at line 167 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 167 of file IORTDetectorConstruction.hh
References detectorLogicalVolume.
G4ThreeVector IORTDetectorConstruction::GetDetectorToPhantomPosition () inline
Definition at line 82 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file IORTDetectorConstruction.hh
References detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), phantomSizeX, phantomSizeY, and phantomSizeZ.
G4ThreeVector IORTDetectorConstruction::GetDetectorToWorldPosition () inline
Definition at line 75 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file IORTDetectorConstruction.hh
References detectorPosition, and phantomPosition.
bool IORTDetectorConstruction::IsInside (G4double detectorX, G4double detectorY, G4double detectorZ, G4double phantomX, G4double phantomY, G4double phantomZ, G4ThreeVector detToPhantomPosition) inline
Definition at line 104 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file IORTDetectorConstruction.hh
References G4cout, G4endl, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), and CLHEP::Hep3Vector::getZ().
Referenced by ParametersCheck().
void IORTDetectorConstruction::ParametersCheck () private
Definition at line 344 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 344 of file IORTDetectorConstruction.cc
References detectorSizeX, detectorSizeY, detectorSizeZ, detectorToPhantomPosition, FatalException, G4Exception(), IsInside(), phantomSizeX, phantomSizeY, and phantomSizeZ.
Referenced by UpdateGeometry().
void IORTDetectorConstruction::PrintParameters ()
Definition at line 618 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 618 of file IORTDetectorConstruction.cc
References detector, G4BestUnit, G4cout, G4endl, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), phantom, and phantomPosition.
Referenced by UpdateGeometry().
void IORTDetectorConstruction::SetAngleDiscoIORT0 (G4double phi0)
Definition at line 539 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 539 of file IORTDetectorConstruction.cc
References AngleDiscoIORT0.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetDetectorPosition () inline
Definition at line 92 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file IORTDetectorConstruction.hh
References detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, detectorToPhantomPosition, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), phantomSizeX, phantomSizeY, phantomSizeZ, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by UpdateGeometry().
void IORTDetectorConstruction::SetDetectorSize (G4double sizeX, G4double sizeY, G4double sizeZ)
Definition at line 452 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 452 of file IORTDetectorConstruction.cc
References detectorSizeX, detectorSizeY, and detectorSizeZ.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetDetectorToPhantomPosition (G4ThreeVector DetectorToPhantomPosition)
Definition at line 470 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 470 of file IORTDetectorConstruction.cc
References detectorToPhantomPosition.
Referenced by IORTDetectorConstruction().
G4bool IORTDetectorConstruction::SetDiscoMaterialIORT (G4String material)
Definition at line 390 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 390 of file IORTDetectorConstruction.cc
References DiscoMaterialIORT, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), G4NistManager::Instance(), logicDiscoIORT, and EmPlot::SetMaterial().
Referenced by IORTDetectorConstruction().
G4bool IORTDetectorConstruction::SetDiscoMaterialIORT1 (G4String material)
Definition at line 417 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 417 of file IORTDetectorConstruction.cc
References DiscoMaterialIORT1, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), G4NistManager::Instance(), logicDiscoIORT1, and EmPlot::SetMaterial().
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetDiscoXPositionIORT (G4double xpos)
Definition at line 494 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 494 of file IORTDetectorConstruction.cc
References DiscoXPositionIORT.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetDiscoXPositionIORT1 (G4double xpos)
Definition at line 533 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 533 of file IORTDetectorConstruction.cc
References DiscoXPositionIORT1.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetDiscoYPositionIORT (G4double ypos)
Definition at line 501 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 501 of file IORTDetectorConstruction.cc
References DiscoYPositionIORT.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetDiscoZPositionIORT (G4double zpos)
Definition at line 508 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 508 of file IORTDetectorConstruction.cc
References DiscoZPositionIORT, and BTOF::zpos.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetheightDiscoIORT (G4double height)
Definition at line 488 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 488 of file IORTDetectorConstruction.cc
References heightDiscoIORT.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetheightDiscoIORT1 (G4double height)
Definition at line 527 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 527 of file IORTDetectorConstruction.cc
References heightDiscoIORT1.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetinnerRadiusDiscoIORT (G4double innerr)
Definition at line 482 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 482 of file IORTDetectorConstruction.cc
References innerRadiusDiscoIORT.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetinnerRadiusDiscoIORT1 (G4double innerr)
Definition at line 521 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 521 of file IORTDetectorConstruction.cc
References innerRadiusDiscoIORT1.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetOuterRadiusDiscoIORT (G4double outerr)
Definition at line 476 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 476 of file IORTDetectorConstruction.cc
References OuterRadiusDiscoIORT.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetOuterRadiusDiscoIORT1 (G4double outerr)
Definition at line 515 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 515 of file IORTDetectorConstruction.cc
References OuterRadiusDiscoIORT1.
Referenced by IORTDetectorConstruction().
G4bool IORTDetectorConstruction::SetPhantomMaterial (G4String material)
Definition at line 362 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 362 of file IORTDetectorConstruction.cc
References detectorLogicalVolume, detectorMaterial, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), G4NistManager::Instance(), phantomLogicalVolume, phantomMaterial, and EmPlot::SetMaterial().
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetPhantomPosition (G4ThreeVector pos)
Definition at line 464 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 464 of file IORTDetectorConstruction.cc
References phantomPosition, and pos().
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetPhantomSize (G4double sizeX, G4double sizeY, G4double sizeZ)
Definition at line 444 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 444 of file IORTDetectorConstruction.cc
References phantomSizeX, phantomSizeY, and phantomSizeZ.
Referenced by IORTDetectorConstruction().
void IORTDetectorConstruction::SetVoxelSize (G4double sizeX, G4double sizeY, G4double sizeZ)
Definition at line 460 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 460 of file IORTDetectorConstruction.cc
References G4cout, and G4endl.
void IORTDetectorConstruction::UpdateGeometry ()
Definition at line 549 of file IORTDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 549 of file IORTDetectorConstruction.cc
References ConstructDetector(), ConstructDisc(), ConstructPhantom(), detector, detectorPhysicalVolume, detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, pyG4RunManager::GeometryHasBeenModified, G4GeometryManager::GetInstance(), G4RunManager::GetRunManager(), logicDiscoIORT, logicDiscoIORT0, logicDiscoIORT1, ParametersCheck(), phantom, phantomPhysicalVolume, phantomPosition, phantomSizeX, phantomSizeY, phantomSizeZ, physiDiscoIORT, physiDiscoIORT0, physiDiscoIORT1, PrintParameters(), SetDetectorPosition(), solidDiscoIORT, solidDiscoIORT0, and solidDiscoIORT1.
Referenced by IORTDetectorConstruction().
Member Data Documentation
G4double IORTDetectorConstruction::AngleDiscoIORT0 private
Definition at line 214 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 214 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetAngleDiscoIORT0().
G4Region* IORTDetectorConstruction::aRegion private
Definition at line 208 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 208 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector().
G4Box * IORTDetectorConstruction::detector private
Definition at line 193 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 193 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), PrintParameters(), and UpdateGeometry().
G4LogicalVolume * IORTDetectorConstruction::detectorLogicalVolume private
Definition at line 194 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 194 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorLogicalVolume(), and SetPhantomMaterial().
G4Material * IORTDetectorConstruction::detectorMaterial private
Definition at line 207 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 207 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructDisc(), and SetPhantomMaterial().
IORTDetectorMessenger* IORTDetectorConstruction::detectorMessenger private
Definition at line 187 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 187 of file IORTDetectorConstruction.hh
Referenced by IORTDetectorConstruction(), and ~IORTDetectorConstruction().
G4VPhysicalVolume * IORTDetectorConstruction::detectorPhysicalVolume private
Definition at line 195 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 195 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructDisc(), and UpdateGeometry().
G4ThreeVector IORTDetectorConstruction::detectorPosition private
Definition at line 205 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 205 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorToPhantomPosition(), GetDetectorToWorldPosition(), SetDetectorPosition(), and UpdateGeometry().
G4double IORTDetectorConstruction::detectorSizeX private
Definition at line 201 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 201 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorToPhantomPosition(), IORTDetectorConstruction(), ParametersCheck(), SetDetectorPosition(), SetDetectorSize(), and UpdateGeometry().
G4double IORTDetectorConstruction::detectorSizeY private
Definition at line 202 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 202 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorToPhantomPosition(), IORTDetectorConstruction(), ParametersCheck(), SetDetectorPosition(), SetDetectorSize(), and UpdateGeometry().
G4double IORTDetectorConstruction::detectorSizeZ private
Definition at line 203 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 203 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorToPhantomPosition(), IORTDetectorConstruction(), ParametersCheck(), SetDetectorPosition(), SetDetectorSize(), and UpdateGeometry().
G4ThreeVector IORTDetectorConstruction::detectorToPhantomPosition private
Definition at line 205 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 205 of file IORTDetectorConstruction.hh
Referenced by ParametersCheck(), SetDetectorPosition(), and SetDetectorToPhantomPosition().
G4Material* IORTDetectorConstruction::DiscoMaterialIORT private
Definition at line 229 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 229 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetDiscoMaterialIORT().
G4Material* IORTDetectorConstruction::DiscoMaterialIORT1 private
Definition at line 240 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 240 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetDiscoMaterialIORT1().
G4double IORTDetectorConstruction::DiscoXPositionIORT private
Definition at line 223 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 223 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetDiscoXPositionIORT().
G4double IORTDetectorConstruction::DiscoXPositionIORT1 private
Definition at line 236 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 236 of file IORTDetectorConstruction.hh
Referenced by SetDiscoXPositionIORT1().
G4double IORTDetectorConstruction::DiscoYPositionIORT private
Definition at line 224 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 224 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetDiscoYPositionIORT().
G4double IORTDetectorConstruction::DiscoZPositionIORT private
Definition at line 225 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 225 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetDiscoZPositionIORT().
G4VisAttributes* IORTDetectorConstruction::gray private
Definition at line 218 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 218 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc().
G4VisAttributes* IORTDetectorConstruction::gray1 private
Definition at line 219 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 219 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc().
G4double IORTDetectorConstruction::heightDiscoIORT private
Definition at line 222 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 222 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetheightDiscoIORT().
G4double IORTDetectorConstruction::heightDiscoIORT1 private
Definition at line 235 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 235 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetheightDiscoIORT1().
G4double IORTDetectorConstruction::innerRadiusDiscoIORT private
Definition at line 220 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 220 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetinnerRadiusDiscoIORT().
G4double IORTDetectorConstruction::innerRadiusDiscoIORT1 private
Definition at line 233 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 233 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetinnerRadiusDiscoIORT1().
G4LogicalVolume* IORTDetectorConstruction::logicDiscoIORT private
Definition at line 227 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 227 of file IORTDetectorConstruction.hh
Referenced by DeleteDisc(), SetDiscoMaterialIORT(), and UpdateGeometry().
G4LogicalVolume* IORTDetectorConstruction::logicDiscoIORT0 private
Definition at line 212 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 212 of file IORTDetectorConstruction.hh
Referenced by DeleteDisc(), and UpdateGeometry().
G4LogicalVolume* IORTDetectorConstruction::logicDiscoIORT1 private
Definition at line 238 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 238 of file IORTDetectorConstruction.hh
Referenced by DeleteDisc(), SetDiscoMaterialIORT1(), and UpdateGeometry().
G4VPhysicalVolume* IORTDetectorConstruction::motherPhys private
Definition at line 191 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 191 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom().
G4double IORTDetectorConstruction::OuterRadiusDiscoIORT private
Definition at line 221 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 221 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetOuterRadiusDiscoIORT().
G4double IORTDetectorConstruction::OuterRadiusDiscoIORT1 private
Definition at line 234 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 234 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), and SetOuterRadiusDiscoIORT1().
G4Box* IORTDetectorConstruction::phantom private
Definition at line 193 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 193 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), PrintParameters(), and UpdateGeometry().
G4LogicalVolume* IORTDetectorConstruction::phantomLogicalVolume private
Definition at line 194 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 194 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), and SetPhantomMaterial().
G4Material* IORTDetectorConstruction::phantomMaterial private
Definition at line 207 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 207 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), and SetPhantomMaterial().
G4VPhysicalVolume* IORTDetectorConstruction::phantomPhysicalVolume private
Definition at line 195 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 195 of file IORTDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructPhantom(), and UpdateGeometry().
G4ThreeVector IORTDetectorConstruction::phantomPosition private
Definition at line 205 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 205 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), GetDetectorToWorldPosition(), PrintParameters(), SetPhantomPosition(), and UpdateGeometry().
G4double IORTDetectorConstruction::phantomSizeX private
Definition at line 197 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 197 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), GetDetectorToPhantomPosition(), ParametersCheck(), SetDetectorPosition(), SetPhantomSize(), and UpdateGeometry().
G4double IORTDetectorConstruction::phantomSizeY private
Definition at line 198 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 198 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), GetDetectorToPhantomPosition(), ParametersCheck(), SetDetectorPosition(), SetPhantomSize(), and UpdateGeometry().
G4double IORTDetectorConstruction::phantomSizeZ private
Definition at line 199 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 199 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom(), GetDetectorToPhantomPosition(), ParametersCheck(), SetDetectorPosition(), SetPhantomSize(), and UpdateGeometry().
G4VPhysicalVolume* IORTDetectorConstruction::physiDiscoIORT private
Definition at line 228 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 228 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), DeleteDisc(), and UpdateGeometry().
G4VPhysicalVolume* IORTDetectorConstruction::physiDiscoIORT0 private
Definition at line 213 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 213 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), DeleteDisc(), and UpdateGeometry().
G4VPhysicalVolume* IORTDetectorConstruction::physiDiscoIORT1 private
Definition at line 239 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 239 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), DeleteDisc(), and UpdateGeometry().
G4VisAttributes* IORTDetectorConstruction::red private
Definition at line 189 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 189 of file IORTDetectorConstruction.hh
Referenced by ConstructPhantom().
G4Tubs* IORTDetectorConstruction::solidDiscoIORT private
Definition at line 226 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 226 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), DeleteDisc(), and UpdateGeometry().
G4Tubs* IORTDetectorConstruction::solidDiscoIORT0 private
Definition at line 211 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 211 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), DeleteDisc(), and UpdateGeometry().
G4Tubs* IORTDetectorConstruction::solidDiscoIORT1 private
Definition at line 237 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 237 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc(), DeleteDisc(), and UpdateGeometry().
G4VisAttributes* IORTDetectorConstruction::white private
Definition at line 217 of file IORTDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 217 of file IORTDetectorConstruction.hh
Referenced by ConstructDisc().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/include/IORTDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/src/IORTDetectorConstruction.cc