ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/include/G3G4Interface.hh File Reference
G3G4Interface.hh File Reference
#include "globals.hh"
Functions
void G4gsvolu (G4String name, G4String shape, G4int nmed, G4double *par, G4int npar)
void G4gspos (G4String name, G4int num, G4String moth, G4double x, G4double y, G4double z, G4int irot, G4String only)
void G4gsposp (G4String name, G4int num, G4String moth, G4double x, G4double y, G4double z, G4int irot, G4String only, G4double Rpar[], G4int npar)
void G4gsbool (G4String volName, G4String manyVolName)
void G4gsrotm (G4int irot, G4double theta1, G4double phi1, G4double theta2, G4double phi2, G4double theta3, G4double phi3)
void G4gsatt (G4String name, G4String attr, G4int ival)
void G4gsdvn (G4String vname, G4String vmoth, G4int ndiv, G4int iaxis)
void G4gsdvt (G4String name, G4String moth, G4double Step, G4int iaxis, G4int numed, G4int ndvmx)
void G4gsdvx (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double Step, G4double c0, G4int numed, G4int ndvmx)
void G4gsdvn2 (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double c0, G4int numed)
void G4gsdvt2 (G4String name, G4String moth, G4double Step, G4int iaxis, G4double c0, G4int numed, G4int ndvmx)
void G4gsmate (G4int imate, G4String name, G4double a, G4double z, G4double dens, G4double radl, G4int nwbf, G4double *ubuf)
void G4gsmixt (G4int imate, G4String name, G4double a[], G4double *z, G4double dens, G4int nlmat, G4double *wmat)
void G4gstmed (G4int itmed, G4String name, G4int nmat, G4int isvol, G4int ifield, G4double fieldm, G4double tmaxfd, G4double stemax, G4double deemax, G4double epsil, G4double stmin, G4double *par, G4int npar)
void G4gstpar (G4int itmed, G4String chpar, G4double parval)
void G4gspart (G4int ipart, G4String chnpar, G4int itrtyp, G4double amass, G4double charge, G4double tlife, G4double *ubuf, G4int nwb)
void G4gsdk (G4int ipart, G4double *bratio, G4int *mode)
void G4gsdet (G4String chset, G4String chdet, G4int nv, G4String *chnmsv, G4int *nbitsv, G4int idtyp, G4int nwhi, G4int nwdi)
void G4gsdetv (G4String chset, G4String chdet, G4int idtyp, G4int nwhi, G4int nwdi)
void G4gsdeta (G4String chset, G4String chdet, G4String chali, G4int nwhi, G4int nwdi)
void G4gsdeth (G4String chset, G4String chdet, G4int nh, G4String *chnamh, G4int *nbitsh, G4double *orig, G4double *fact)
void G4gsdetd (G4String chset, G4String chdet, G4int nd, G4String *chnmsd, G4int *nbitsd)
void G4gsdetu (G4String chset, G4String chdet, G4int nupar, G4double *upar)
void G4ggclos ()
G4LogicalVolume * G4BuildGeom (G4String &inFile)
Function Documentation
G4LogicalVolume* G4BuildGeom (G4String & inFile)
Definition at line 54 of file G4BuildGeom.cc.
View newest version in sPHENIX GitHub at line 54 of file G4BuildGeom.cc
References checkVol(), G3CLRead(), G3Det, G3Part, G3toG4BuildTree(), G3Vol, G4cout, G4endl, G4gsrotm(), G3VolTable::GetFirstVTE(), G4VisAttributes::GetInvisible(), G3VolTableEntry::GetLV(), G3VolTableEntry::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetVisAttributes(), G3DetTable::PrintAll(), G3PartTable::PrintAll(), G3VolTable::PrintAll(), and G4LogicalVolume::SetVisAttributes().
Referenced by G3toG4DetectorConstruction::Construct().
void G4ggclos ()
Definition at line 35 of file G4ggclos.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ggclos.cc
References G3Vol, G4cout, G4endl, and G3VolTable::SetFirstVTE().
Referenced by PG4ggclos().
void G4gsatt (G4String name, G4String attr, G4int ival)
Definition at line 45 of file G4gsatt.cc.
View newest version in sPHENIX GitHub at line 45 of file G4gsatt.cc
References G4cerr, and G4endl.
Referenced by PG4gsatt().
void G4gsbool (G4String volName, G4String manyVolName)
Definition at line 34 of file G4gsbool.cc.
View newest version in sPHENIX GitHub at line 34 of file G4gsbool.cc
References G3VolTableEntry::AddOverlap(), FatalException, G3Vol, G4cerr, G4endl, G4Exception(), and G3VolTable::GetVTE().
void G4gsdet (G4String chset, G4String chdet, G4int nv, G4String * chnmsv, G4int * nbitsv, G4int idtyp, G4int nwhi, G4int nwdi)
Definition at line 50 of file G4gsdet.cc.
View newest version in sPHENIX GitHub at line 50 of file G4gsdet.cc
References G4gsdetv().
Referenced by PG4gsdet().
void G4gsdeta (G4String chset, G4String chdet, G4String chali, G4int nwhi, G4int nwdi)
Definition at line 52 of file G4gsdeta.cc.
View newest version in sPHENIX GitHub at line 52 of file G4gsdeta.cc
References G3Det, G4gsdetv(), and G3DetTable::GetID().
Referenced by PG4gsdeta().
void G4gsdetd (G4String chset, G4String chdet, G4int nd, G4String * chnmsd, G4int * nbitsd)
Definition at line 49 of file G4gsdetd.cc.
View newest version in sPHENIX GitHub at line 49 of file G4gsdetd.cc
Referenced by PG4gsdetd().
void G4gsdeth (G4String chset, G4String chdet, G4int nh, G4String * chnamh, G4int * nbitsh, G4double * orig, G4double * fact)
Definition at line 51 of file G4gsdeth.cc.
View newest version in sPHENIX GitHub at line 51 of file G4gsdeth.cc
Referenced by PG4gsdeth().
void G4gsdetu (G4String chset, G4String chdet, G4int nupar, G4double * upar)
Definition at line 44 of file G4gsdetu.cc.
View newest version in sPHENIX GitHub at line 44 of file G4gsdetu.cc
Referenced by PG4gsdetu().
void G4gsdetv (G4String chset, G4String chdet, G4int idtyp, G4int nwhi, G4int nwdi)
Definition at line 50 of file G4gsdetv.cc.
View newest version in sPHENIX GitHub at line 50 of file G4gsdetv.cc
References G4cout, and G4endl.
Referenced by G4gsdet(), G4gsdeta(), and PG4gsdetv().
void G4gsdk (G4int ipart, G4double * bratio, G4int * mode)
Definition at line 45 of file G4gsdk.cc.
View newest version in sPHENIX GitHub at line 45 of file G4gsdk.cc
Referenced by PG4gsdk().
void G4gsdvn (G4String vname, G4String vmoth, G4int ndiv, G4int iaxis)
Definition at line 102 of file G4gsdvn.cc.
View newest version in sPHENIX GitHub at line 102 of file G4gsdvn.cc
References FatalException, G3Vol, G4CreateCloneVTEWithDivision(), G4Exception(), G3VolTable::GetVTE(), and kDvn.
Referenced by PG4gsdvn().
void G4gsdvn2 (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double c0, G4int numed)
Definition at line 55 of file G4gsdvn2.cc.
View newest version in sPHENIX GitHub at line 55 of file G4gsdvn2.cc
Referenced by G4gsdvx(), and PG4gsdvn2().
void G4gsdvt (G4String name, G4String moth, G4double Step, G4int iaxis, G4int numed, G4int ndvmx)
Definition at line 56 of file G4gsdvt.cc.
View newest version in sPHENIX GitHub at line 56 of file G4gsdvt.cc
References FatalException, G3Vol, G4CreateCloneVTEWithDivision(), G4Exception(), G3VolTable::GetVTE(), and kDvt.
Referenced by PG4gsdvt().
void G4gsdvt2 (G4String name, G4String moth, G4double Step, G4int iaxis, G4double c0, G4int numed, G4int ndvmx)
Definition at line 57 of file G4gsdvt2.cc.
View newest version in sPHENIX GitHub at line 57 of file G4gsdvt2.cc
Referenced by G4gsdvx(), and PG4gsdvt2().
void G4gsdvx (G4String name, G4String moth, G4int ndiv, G4int iaxis, G4double Step, G4double c0, G4int numed, G4int ndvmx)
Definition at line 57 of file G4gsdvx.cc.
View newest version in sPHENIX GitHub at line 57 of file G4gsdvx.cc
References G4gsdvn2(), and G4gsdvt2().
Referenced by PG4gsdvx().
void G4gsmate (G4int imate, G4String name, G4double a, G4double z, G4double dens, G4double radl, G4int nwbf, G4double * ubuf)
Definition at line 104 of file G4gsmate.cc.
View newest version in sPHENIX GitHub at line 104 of file G4gsmate.cc
References a, G4Material::AddElement(), G4String::both, cm3, Acts::UnitConstants::g, G3Ele, G3Mat, G4gsmixt(), G3EleTable::GetEle(), kelvin, kStateGas, material(), mole, n, pascal, G3MatTable::put(), G4String::strip(), source.hepunit::universe_mean_density, z, and zz.
Referenced by PG4gsmate().
void G4gsmixt (G4int imate, G4String name, G4double a[], G4double * z, G4double dens, G4int nlmat, G4double * wmat)
Referenced by G4gsmate(), and PG4gsmixt().
void G4gspart (G4int ipart, G4String chnpar, G4int itrtyp, G4double amass, G4double charge, G4double tlife, G4double * ubuf, G4int nwb)
Definition at line 50 of file G4gspart.cc.
View newest version in sPHENIX GitHub at line 50 of file G4gspart.cc
Referenced by PG4gspart().
void G4gspos (G4String name, G4int num, G4String moth, G4double x, G4double y, G4double z, G4int irot, G4String only)
Definition at line 64 of file G4gspos.cc.
View newest version in sPHENIX GitHub at line 64 of file G4gspos.cc
References G3VolTableEntry::AddDaughter(), G3VolTableEntry::AddG3Pos(), G3VolTableEntry::AddMother(), cm, FatalException, G3Vol, G4CreateCloneVTE(), G4Exception(), G3VolTableEntry::GetClone(), G3VolTableEntry::GetNoClones(), G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTable::GetVTE(), G3VolTableEntry::HasNegPars(), num, offset, x, y, and z.
Referenced by PG4gspos().
void G4gsposp (G4String name, G4int num, G4String moth, G4double x, G4double y, G4double z, G4int irot, G4String only, G4double Rpar[], G4int npar)
Definition at line 296 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 296 of file G4gsposp.cc
References FatalException, G3Vol, G4CreateCloneVTE(), G4Exception(), and G3VolTable::GetVTE().
Referenced by PG4gsposp().
void G4gsrotm (G4int irot, G4double theta1, G4double phi1, G4double theta2, G4double phi2, G4double theta3, G4double phi3)
Definition at line 53 of file G4gsrotm.cc.
View newest version in sPHENIX GitHub at line 53 of file G4gsrotm.cc
References kdfinder::abs(), CLHEP::Hep3Vector::cross(), FatalException, G3Rot, G4cerr, G4endl, G4Exception(), pi, G3RotTable::Put(), G3toG4RotationMatrix::SetRotationMatrixByRow(), x, y, and z.
Referenced by G4BuildGeom(), and PG4gsrotm().
void G4gstmed (G4int itmed, G4String name, G4int nmat, G4int isvol, G4int ifield, G4double fieldm, G4double tmaxfd, G4double stemax, G4double deemax, G4double epsil, G4double stmin, G4double * par, G4int npar)
Definition at line 67 of file G4gstmed.cc.
View newest version in sPHENIX GitHub at line 67 of file G4gstmed.cc
References cm, G3Mat, G3Med, G3MatTable::get(), material(), G3MedTable::put(), and G4UserLimits::SetMaxAllowedStep().
Referenced by PG4gstmed().
void G4gstpar (G4int itmed, G4String chpar, G4double parval)
Definition at line 44 of file G4gstpar.cc.
View newest version in sPHENIX GitHub at line 44 of file G4gstpar.cc
References G4cerr, and G4endl.
Referenced by PG4gstpar().
void G4gsvolu (G4String name, G4String shape, G4int nmed, G4double * par, G4int npar)
Definition at line 72 of file G4gsvolu.cc.
View newest version in sPHENIX GitHub at line 72 of file G4gsvolu.cc
References FatalException, G3Vol, G4CreateVTE(), G4Exception(), and G3VolTable::GetVTE().
Referenced by PG4gsvolu().