ECCE @ EIC Software: G4KL3DecayChannel Class Reference
G4KL3DecayChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4KL3DecayChannel.hh>
Public Member Functions
G4KL3DecayChannel (const G4String &theParentName, G4double theBR, const G4String &thePionName, const G4String &theLeptonName, const G4String &theNutrinoName)
virtual ~G4KL3DecayChannel ()
virtual G4DecayProducts * DecayIt (G4double)
void SetDalitzParameter (G4double aLambda, G4double aXi)
G4double GetDalitzParameterLambda () const
G4double GetDalitzParameterXi () const
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Protected Types
enum { idPi =0, idLepton =1, idNutrino =2 }
Protected Member Functions
G4KL3DecayChannel (const G4KL3DecayChannel &)
G4KL3DecayChannel & operator= (const G4KL3DecayChannel &)
void PhaseSpace (G4double Mparent, const G4double *Mdaughter, G4double *Edaughter, G4double *Pdaughter)
G4double DalitzDensity (G4double parentmass, G4double Epi, G4double El, G4double Enu, G4double massPi, G4double massL, G4double massNu)
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Private Member Functions
G4KL3DecayChannel ()
Private Attributes
G4double pLambda
G4double pXi0
Additional Inherited Members
Protected Attributes inherited from G4VDecayChannel
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 42 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 42 of file G4KL3DecayChannel.hh
Member Enumeration Documentation
anonymous enum protected
Enumerator:
idPi
idLepton
idNutrino
Definition at line 67 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4KL3DecayChannel.hh
Constructor & Destructor Documentation
G4KL3DecayChannel::G4KL3DecayChannel (const G4String & theParentName, G4double theBR, const G4String & thePionName, const G4String & theLeptonName, const G4String & theNutrinoName)
Definition at line 53 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4KL3DecayChannel.cc
References G4VDecayChannel::DumpInfo(), G4cout, G4endl, G4VDecayChannel::GetVerboseLevel(), pLambda, and pXi0.
G4KL3DecayChannel::~G4KL3DecayChannel () virtual
Definition at line 106 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 106 of file G4KL3DecayChannel.cc
G4KL3DecayChannel::G4KL3DecayChannel (const G4KL3DecayChannel & right) protected
Definition at line 110 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 110 of file G4KL3DecayChannel.cc
G4KL3DecayChannel::G4KL3DecayChannel () private
Definition at line 46 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4KL3DecayChannel.cc
Member Function Documentation
G4double G4KL3DecayChannel::DalitzDensity (G4double parentmass, G4double Epi, G4double El, G4double Enu, G4double massPi, G4double massL, G4double massNu) protected
Definition at line 314 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 314 of file G4KL3DecayChannel.cc
References E, F, G4cout, G4endl, G4VDecayChannel::GetVerboseLevel(), GeV, pLambda, and pXi0.
Referenced by DecayIt().
G4DecayProducts * G4KL3DecayChannel::DecayIt (G4double) virtual
Implements G4VDecayChannel.
Definition at line 149 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 149 of file G4KL3DecayChannel.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), DalitzDensity(), G4VDecayChannel::daughters_name, G4DecayProducts::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4ParticleDefinition::GetPDGMass(), G4VDecayChannel::GetVerboseLevel(), GeV, idLepton, idNutrino, idPi, PhaseSpace(), phi, G4DecayProducts::PushProducts(), r, rad, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), twopi, and w.
G4double G4KL3DecayChannel::GetDalitzParameterLambda () const inline
Definition at line 112 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4KL3DecayChannel.hh
References pLambda.
G4double G4KL3DecayChannel::GetDalitzParameterXi () const inline
Definition at line 118 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4KL3DecayChannel.hh
References pXi0.
G4KL3DecayChannel & G4KL3DecayChannel::operator= (const G4KL3DecayChannel & right) protected
Definition at line 118 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 118 of file G4KL3DecayChannel.cc
References G4VDecayChannel::ClearDaughtersName(), G4VDecayChannel::daughters_name, G4VDecayChannel::kinematics_name, G4VDecayChannel::numberOfDaughters, G4VDecayChannel::parent_name, pLambda, pXi0, G4VDecayChannel::rbranch, and G4VDecayChannel::verboseLevel.
void G4KL3DecayChannel::PhaseSpace (G4double Mparent, const G4double * Mdaughter, G4double * Edaughter, G4double * Pdaughter) protected
Definition at line 248 of file G4KL3DecayChannel.cc.
View newest version in sPHENIX GitHub at line 248 of file G4KL3DecayChannel.cc
References energy, G4cout, G4endl, G4UniformRand, G4VDecayChannel::GetVerboseLevel(), and GeV.
Referenced by DecayIt().
void G4KL3DecayChannel::SetDalitzParameter (G4double aLambda, G4double aXi) inline
Definition at line 105 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4KL3DecayChannel.hh
References pLambda, and pXi0.
Member Data Documentation
G4double G4KL3DecayChannel::pLambda private
Definition at line 95 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 95 of file G4KL3DecayChannel.hh
Referenced by DalitzDensity(), G4KL3DecayChannel(), GetDalitzParameterLambda(), operator=(), and SetDalitzParameter().
G4double G4KL3DecayChannel::pXi0 private
Definition at line 96 of file G4KL3DecayChannel.hh.
View newest version in sPHENIX GitHub at line 96 of file G4KL3DecayChannel.hh
Referenced by DalitzDensity(), G4KL3DecayChannel(), GetDalitzParameterXi(), operator=(), and SetDalitzParameter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4KL3DecayChannel.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4KL3DecayChannel.cc