ECCE @ EIC Software: G4CompositeDataSet Class Reference
G4CompositeDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4CompositeDataSet.hh>
Public Member Functions
G4CompositeDataSet (G4IInterpolator *argAlgorithm, G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn, G4int zMin=1, G4int zMax=99)
virtual ~G4CompositeDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4IDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4IDataSet *dataSet)
virtual size_t NumberOfComponents () const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int componentId) const
Public Member Functions inherited from G4IDataSet
G4IDataSet ()
virtual ~G4IDataSet ()
Private Member Functions
void CleanUpComponents (void)
G4CompositeDataSet ()
G4CompositeDataSet (const G4CompositeDataSet &copy)
G4CompositeDataSet & operator= (const G4CompositeDataSet &right)
Private Attributes
std::vector< G4IDataSet * > components
G4IInterpolator * algorithm
G4double unitEnergies
G4double unitData
G4int minZ
G4int maxZ
Detailed Description
Definition at line 54 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4CompositeDataSet.hh
Constructor & Destructor Documentation
G4CompositeDataSet::G4CompositeDataSet (G4IInterpolator * argAlgorithm, G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn, G4int zMin = 1, G4int zMax = 99)
Definition at line 44 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 44 of file G4CompositeDataSet.cc
References algorithm, FatalException, and G4Exception().
G4CompositeDataSet::~G4CompositeDataSet () virtual
Definition at line 65 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 65 of file G4CompositeDataSet.cc
References algorithm, and CleanUpComponents().
G4CompositeDataSet::G4CompositeDataSet () private
G4CompositeDataSet::G4CompositeDataSet (const G4CompositeDataSet & copy) private
Member Function Documentation
virtual void G4CompositeDataSet::AddComponent (G4IDataSet * dataSet) inline virtual
Implements G4IDataSet.
Definition at line 72 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CompositeDataSet.hh
References components.
Referenced by LoadData().
void G4CompositeDataSet::CleanUpComponents (void) private
Definition at line 168 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 168 of file G4CompositeDataSet.cc
References components.
Referenced by LoadData(), and ~G4CompositeDataSet().
G4double G4CompositeDataSet::FindValue (G4double x, G4int componentId = 0) const virtual
Implements G4IDataSet.
Definition at line 72 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 72 of file G4CompositeDataSet.cc
References FatalException, G4IDataSet::FindValue(), G4Exception(), GetComponent(), and message().
virtual const G4IDataSet* G4CompositeDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4IDataSet.
Definition at line 69 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 69 of file G4CompositeDataSet.hh
References components.
Referenced by FindValue(), GetData(), GetEnergies(), PrintData(), RandomSelect(), and SaveData().
virtual const G4DataVector& G4CompositeDataSet::GetData (G4int componentId) const inline virtual
Implements G4IDataSet.
Definition at line 81 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 81 of file G4CompositeDataSet.hh
References GetComponent(), and G4IDataSet::GetData().
virtual const G4DataVector& G4CompositeDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4IDataSet.
Definition at line 78 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 78 of file G4CompositeDataSet.hh
References GetComponent(), and G4IDataSet::GetEnergies().
G4bool G4CompositeDataSet::LoadData (const G4String & fileName) virtual
Implements G4IDataSet.
Definition at line 126 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 126 of file G4CompositeDataSet.cc
References AddComponent(), algorithm, CleanUpComponents(), G4IInterpolator::Clone(), G4IDataSet::LoadData(), maxZ, minZ, unitData, unitEnergies, and z.
virtual size_t G4CompositeDataSet::NumberOfComponents (void) const inline virtual
Implements G4IDataSet.
Definition at line 75 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CompositeDataSet.hh
References components.
Referenced by PrintData().
G4CompositeDataSet& G4CompositeDataSet::operator= (const G4CompositeDataSet & right) private
void G4CompositeDataSet::PrintData (void) const virtual
Implements G4IDataSet.
Definition at line 89 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 89 of file G4CompositeDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4IDataSet::PrintData().
G4double G4CompositeDataSet::RandomSelect (G4int componentId) const virtual
Implements G4IDataSet.
Definition at line 179 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 179 of file G4CompositeDataSet.cc
References components, GetComponent(), and G4IDataSet::RandomSelect().
G4bool G4CompositeDataSet::SaveData (const G4String & fileName) const virtual
Implements G4IDataSet.
Definition at line 145 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 145 of file G4CompositeDataSet.cc
References FatalException, G4Exception(), GetComponent(), maxZ, message(), minZ, G4IDataSet::SaveData(), and z.
void G4CompositeDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * data, G4int componentId) virtual
Implements G4IDataSet.
Definition at line 106 of file G4CompositeDataSet.cc.
View newest version in sPHENIX GitHub at line 106 of file G4CompositeDataSet.cc
References components, FatalException, G4Exception(), message(), and G4IDataSet::SetEnergiesData().
Member Data Documentation
G4IInterpolator* G4CompositeDataSet::algorithm private
Definition at line 102 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 102 of file G4CompositeDataSet.hh
Referenced by G4CompositeDataSet(), LoadData(), and ~G4CompositeDataSet().
std::vector<G4IDataSet*> G4CompositeDataSet::components private
Definition at line 100 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 100 of file G4CompositeDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), GetComponent(), NumberOfComponents(), RandomSelect(), and SetEnergiesData().
G4int G4CompositeDataSet::maxZ private
Definition at line 108 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4CompositeDataSet.hh
Referenced by LoadData(), and SaveData().
G4int G4CompositeDataSet::minZ private
Definition at line 107 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 107 of file G4CompositeDataSet.hh
Referenced by LoadData(), and SaveData().
G4double G4CompositeDataSet::unitData private
Definition at line 105 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 105 of file G4CompositeDataSet.hh
Referenced by LoadData().
G4double G4CompositeDataSet::unitEnergies private
Definition at line 104 of file G4CompositeDataSet.hh.
View newest version in sPHENIX GitHub at line 104 of file G4CompositeDataSet.hh
Referenced by LoadData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4CompositeDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/src/G4CompositeDataSet.cc