ECCE @ EIC Software: G4INCL::CrossSectionsStrangeness Class Reference
G4INCL::CrossSectionsStrangeness Class Reference
Multipion, mesonic Resonances and strange cross sections.
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsStrangeness.hh>
Public Member Functions
CrossSectionsStrangeness ()
virtual G4double total (Particle const *const p1, Particle const *const p2)
second new total particle-particle cross section
virtual G4double elastic (Particle const *const p1, Particle const *const p2)
second new elastic particle-particle cross section
virtual G4double piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2)
correction to old cross section
virtual G4double NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NN Channel.
virtual G4double NYelastic (Particle const *const p1, Particle const *const p2)
elastic scattering for Nucleon-Strange Particles cross sections
virtual G4double NKbelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NKelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Nucleon to Stange particles cross sections.
virtual G4double NNToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NNToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Delta to Stange particles cross sections.
virtual G4double NDeltaToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK (Particle const *const p1, Particle const *const p2)
Nucleon-Pion to Stange particles cross sections.
G4double p_pimToLK0 (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSK (Particle const *const p1, Particle const *const p2)
G4double p_pipToSpKp (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSzKz (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSmKp (Particle const *const p1, Particle const *const p2)
virtual G4double p_pizToSzKp (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NLToNS (Particle const *const p1, Particle const *const p2)
Nucleon-Hyperon quasi-elastic cross sections.
virtual G4double NSToNL (Particle const *const p1, Particle const *const p2)
virtual G4double NSToNS (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK (Particle const *const p1, Particle const *const p2)
Nucleon-Kaon cross sections.
virtual G4double NKToNKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb (Particle const *const p1, Particle const *const p2)
Nucleon-antiKaon cross sections.
virtual G4double NKbToSpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToLpi (Particle const *const p1, Particle const *const p2)
virtual G4double p_kmToL_pz (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToS2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToL2pi (Particle const *const p1, Particle const *const p2)
virtual G4double p_kmToL_pp_pm (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKbpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb2pi (Particle const *const p1, Particle const *const p2)
Public Member Functions inherited from G4INCL::CrossSectionsMultiPionsAndResonances
CrossSectionsMultiPionsAndResonances ()
virtual G4double piNToEtaN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance production - piN Channel.
virtual G4double piNToOmegaN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->OmegaN.
virtual G4double piNToEtaPrimeN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->EtaPrimeN.
virtual G4double etaNToPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - piN Channel.
virtual G4double omegaNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for OmegaN->PiN.
virtual G4double etaPrimeNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for EtaPrimeN->PiN.
virtual G4double etaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
virtual G4double NNToNNEta (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (inclusive) - NN entrance channel.
virtual G4double NNToNNEtaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNOmega (Particle const *const particle1, Particle const *const particle2)
Cross section for Omega production (inclusive) - NN entrance channel.
virtual G4double NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Omega production (exclusive) - NN entrance channel.
virtual G4double NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNEta Channel.
virtual G4double NNToNDeltaEta (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNEta Channel.
virtual G4double NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNOmega Channel.
virtual G4double NNToNDeltaOmega (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNOmega Channel.
Public Member Functions inherited from G4INCL::CrossSectionsMultiPions
CrossSectionsMultiPions ()
virtual G4double NDeltaToNN (Particle const *const p1, Particle const *const p2)
Cross section for NDelta->NN.
virtual G4double NNToNDelta (Particle const *const p1, Particle const *const p2)
Cross section for Delta production - NN Channel.
virtual G4double piNToDelta (Particle const *const p1, Particle const *const p2)
Cross section for Delta production - piN Channel.
virtual G4double calculateNNAngularSlope (G4double energyCM, G4int iso)
Calculate the slope of the NN DDXS.
Public Member Functions inherited from G4INCL::ICrossSections
ICrossSections ()
virtual ~ICrossSections ()
Protected Attributes
const HornerC7 s11pzHC
Horner coefficients for s11pz.
const HornerC8 s01ppHC
Horner coefficients for s01pp.
const HornerC4 s01pzHC
Horner coefficients for s01pz.
const HornerC4 s11pmHC
Horner coefficients for s11pm.
const HornerC5 s12pmHC
Horner coefficients for s12pm.
const HornerC3 s12ppHC
Horner coefficients for s12pp.
const HornerC4 s12zzHC
Horner coefficients for s12zz.
const HornerC4 s02pzHC
Horner coefficients for s02pz.
const HornerC6 s02pmHC
Horner coefficients for s02pm.
const HornerC4 s12mzHC
Horner coefficients for s12mz.
Protected Attributes inherited from G4INCL::CrossSectionsMultiPionsAndResonances
const HornerC7 s11pzHC
Horner coefficients for s11pz.
const HornerC8 s01ppHC
Horner coefficients for s01pp.
const HornerC4 s01pzHC
Horner coefficients for s01pz.
const HornerC4 s11pmHC
Horner coefficients for s11pm.
const HornerC5 s12pmHC
Horner coefficients for s12pm.
const HornerC3 s12ppHC
Horner coefficients for s12pp.
const HornerC4 s12zzHC
Horner coefficients for s12zz.
const HornerC4 s02pzHC
Horner coefficients for s02pz.
const HornerC6 s02pmHC
Horner coefficients for s02pm.
const HornerC4 s12mzHC
Horner coefficients for s12mz.
Protected Attributes inherited from G4INCL::CrossSectionsMultiPions
const HornerC7 s11pzHC
Horner coefficients for s11pz.
const HornerC8 s01ppHC
Horner coefficients for s01pp.
const HornerC4 s01pzHC
Horner coefficients for s01pz.
const HornerC4 s11pmHC
Horner coefficients for s11pm.
const HornerC5 s12pmHC
Horner coefficients for s12pm.
const HornerC3 s12ppHC
Horner coefficients for s12pp.
const HornerC4 s12zzHC
Horner coefficients for s12zz.
const HornerC4 s02pzHC
Horner coefficients for s02pz.
const HornerC6 s02pmHC
Horner coefficients for s02pm.
const HornerC4 s12mzHC
Horner coefficients for s12mz.
Static Protected Attributes
static const G4int nMaxPiNN = 4
Maximum number of outgoing pions in NN collisions.
static const G4int nMaxPiPiN = 4
Maximum number of outgoing pions in piN collisions.
Static Protected Attributes inherited from G4INCL::CrossSectionsMultiPionsAndResonances
static const G4int nMaxPiNN = 4
Maximum number of outgoing pions in NN collisions.
static const G4int nMaxPiPiN = 4
Maximum number of outgoing pions in piN collisions.
static const G4double s11pzOOT = 0.0035761542037692665889
One over threshold for s11pz.
static const G4double s01ppOOT = 0.003421025623481919853
One over threshold for s01pp.
static const G4double s01pzOOT = 0.0035739814152966403123
One over threshold for s01pz.
static const G4double s11pmOOT = 0.0034855350296270480281
One over threshold for s11pm.
static const G4double s12pmOOT = 0.0016672224074691565119
One over threshold for s12pm.
static const G4double s12ppOOT = 0.0016507643038726931312
One over threshold for s12pp.
static const G4double s12zzOOT = 0.0011111111111111111111
One over threshold for s12zz.
static const G4double s02pzOOT = 0.00125
One over threshold for s02pz.
static const G4double s02pmOOT = 0.0016661112962345883443
One over threshold for s02pm.
static const G4double s12mzOOT = 0.0017047391749062392793
One over threshold for s12mz.
Static Protected Attributes inherited from G4INCL::CrossSectionsMultiPions
static const G4int nMaxPiNN = 4
Maximum number of outgoing pions in NN collisions.
static const G4int nMaxPiPiN = 4
Maximum number of outgoing pions in piN collisions.
static const G4double s11pzOOT = 0.0035761542037692665889
One over threshold for s11pz.
static const G4double s01ppOOT = 0.003421025623481919853
One over threshold for s01pp.
static const G4double s01pzOOT = 0.0035739814152966403123
One over threshold for s01pz.
static const G4double s11pmOOT = 0.0034855350296270480281
One over threshold for s11pm.
static const G4double s12pmOOT = 0.0016672224074691565119
One over threshold for s12pm.
static const G4double s12ppOOT = 0.0016507643038726931312
One over threshold for s12pp.
static const G4double s12zzOOT = 0.0011111111111111111111
One over threshold for s12zz.
static const G4double s02pzOOT = 0.00125
One over threshold for s02pz.
static const G4double s02pmOOT = 0.0016661112962345883443
One over threshold for s02pm.
static const G4double s12mzOOT = 0.0017047391749062392793
One over threshold for s12mz.
Additional Inherited Members
Protected Member Functions inherited from G4INCL::CrossSectionsMultiPionsAndResonances
G4double piMinuspToEtaN (Particle const *const p1, Particle const *const p2)
Internal function for pion cross sections.
G4double piMinuspToEtaN (const G4double ECM)
G4double piMinuspToOmegaN (Particle const *const p1, Particle const *const p2)
G4double piMinuspToOmegaN (const G4double ECM)
virtual G4double NNToNNEtaIso (const G4double ener, const G4int iso)
Cross section for One (more) pion production - piN entrance channel.
virtual G4double NNToNNEtaExcluIso (const G4double ener, const G4int iso)
Isotopic Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNEtaOnePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNEta channel.
virtual G4double NNToNNEtaOnePiOrDelta (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNEta channel.
virtual G4double NNToNNEtaTwoPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 2-pion production - NNEta channel.
virtual G4double NNToNNEtaThreePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 3-pion production - NNEta channel.
virtual G4double NNToNNEtaFourPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 4-pion production - NNEta channel.
virtual G4double NNToNNOmegaIso (const G4double ener, const G4int iso)
Isotopic Cross section for Omega production (inclusive) - NN entrance channel.
virtual G4double NNToNNOmegaExcluIso (const G4double ener, const G4int iso)
Isotopic Cross section for Omega production (exclusive) - NN entrance channel.
virtual G4double NNToNNOmegaOnePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNOmega channel.
virtual G4double NNToNNOmegaOnePiOrDelta (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNOmega channel.
virtual G4double NNToNNOmegaTwoPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 2-pion production - NNOmega channel.
virtual G4double NNToNNOmegaThreePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 3-pion production - NNOmega channel.
virtual G4double NNToNNOmegaFourPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 4-pion production - NNOmega channel.
virtual G4double etaNElastic (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - elastic Channel.
virtual G4double omegaNElastic (Particle const *const p1, Particle const *const p2)
virtual G4double omegaNInelastic (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - inelastic Channel.
virtual G4double omegaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross sections for omega-induced 2Pi emission on nucleon.
Detailed Description
Multipion, mesonic Resonances and strange cross sections.
Definition at line 55 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLCrossSectionsStrangeness.hh
Constructor & Destructor Documentation
G4INCL::CrossSectionsStrangeness::CrossSectionsStrangeness ()
Definition at line 66 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 66 of file G4INCLCrossSectionsStrangeness.cc
Member Function Documentation
G4double G4INCL::CrossSectionsStrangeness::elastic (Particle const *const p1, Particle const *const p2) virtual
second new elastic particle-particle cross section
Reimplemented from G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 119 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 119 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic(), G4INCL::Particle::isAntiKaon(), G4INCL::Particle::isDelta(), G4INCL::Particle::isEta(), G4INCL::Particle::isHyperon(), G4INCL::Particle::isKaon(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isPion(), NKbelastic(), NKelastic(), and NYelastic().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 831 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 831 of file G4INCLCrossSectionsStrangeness.cc
References a, kdfinder::abs(), b, c, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4InuclParticleNames::s0, and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 875 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 875 of file G4INCLCrossSectionsStrangeness.cc
References a, kdfinder::abs(), b, c, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4InuclParticleNames::s0, and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NDeltaToNLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Delta to Stange particles cross sections.
NDelta to strange cross sections.
No experimental data Parametrization from Phys.Rev.C 59 1 (369) (1999)
Correction are applied on the isospin symetry provided in the paper
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 732 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 732 of file G4INCLCrossSectionsStrangeness.cc
References a, kdfinder::abs(), b, c, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4InuclParticleNames::s0, and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NDeltaToNNKKb (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 937 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 937 of file G4INCLCrossSectionsStrangeness.cc
References kdfinder::abs(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NDeltaToNSK (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 778 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 778 of file G4INCLCrossSectionsStrangeness.cc
References a, kdfinder::abs(), b, c, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4InuclParticleNames::s0, and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbelastic (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 372 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 372 of file G4INCLCrossSectionsStrangeness.cc
References E, G4INCL::Particle::isAntiKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by elastic().
G4double G4INCL::CrossSectionsStrangeness::NKbToL2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1865 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1865 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4InuclParticleNames::nucleon(), and p_kmToL_pp_pm().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbToLpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1764 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1764 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4InuclParticleNames::nucleon(), and p_kmToL_pz().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbToNKb (Particle const *const p1, Particle const *const p2) virtual
Nucleon-antiKaon cross sections.
NKb cross sections.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1663 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1663 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), and G4INCL::Proton.
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbToNKb2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1957 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1957 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbToNKbpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1911 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1911 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbToS2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1813 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1813 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKbToSpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1715 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1715 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isAntiKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKelastic (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 335 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 335 of file G4INCLCrossSectionsStrangeness.cc
References e, G4INCL::Particle::isKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by elastic().
G4double G4INCL::CrossSectionsStrangeness::NKToNK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Kaon cross sections.
NK cross sections.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1526 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1526 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isKaon(), G4INCL::KinematicsUtils::momentumInLab(), and G4INCL::Proton.
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKToNK2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1607 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1607 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isKaon(), and G4INCL::KinematicsUtils::momentumInLab().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NKToNKpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1563 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1563 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isKaon(), and G4INCL::KinematicsUtils::momentumInLab().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NLToNS (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Hyperon quasi-elastic cross sections.
NY cross sections.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1423 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1423 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::Particle::isLambda(), and G4INCL::KinematicsUtils::momentumInLab().
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NNToMissingStrangeness (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 700 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 700 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), and G4INCL::KinematicsUtils::momentumInLab().
Referenced by NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Nucleon to Stange particles cross sections.
NN to strange cross sections.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 403 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 403 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::Particle::getType(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::Neutron, and G4INCL::Proton.
Referenced by NNToNLKpi(), and NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNLK2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 597 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 597 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), NNToNLKpi(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNLKpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 491 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 491 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), NNToNLK(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNLK2pi(), and NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNNKKb (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 669 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 669 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNSK (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 445 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 445 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::Particle::getType(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::Neutron, and G4INCL::Proton.
Referenced by NNToNSKpi(), and NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNSK2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 633 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 633 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), NNToNSKpi(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToNSKpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 543 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 543 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), NNToNSK(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNSK2pi(), and NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NN Channel.
Reimplemented from G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 213 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 213 of file G4INCLCrossSectionsStrangeness.cc
References NNToMissingStrangeness(), NNToNLK(), NNToNLK2pi(), NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEta(), NNToNNKKb(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmega(), NNToNSK(), NNToNSK2pi(), NNToNSKpi(), and G4INCL::CrossSectionsMultiPions::NNToxPiNN().
G4double G4INCL::CrossSectionsStrangeness::NpiToLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Pion to Stange particles cross sections.
piN to strange cross sections
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 987 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 987 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4InuclParticleNames::nucleon(), p_pimToLK0(), G4InuclParticleNames::pion(), and G4INCL::PiZero.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToLK2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1225 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1225 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), and G4INCL::PiZero.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToLKpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1134 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1134 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), and G4INCL::PiZero.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1383 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1383 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::Neutron, G4InuclParticleNames::nucleon(), G4INCL::PiMinus, G4InuclParticleNames::pion(), G4INCL::PiPlus, G4INCL::PiZero, and G4INCL::Proton.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToNKKb (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1332 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1332 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::Neutron, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, and G4INCL::Proton.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToSK (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1033 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1033 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4InuclParticleNames::nucleon(), p_pimToSmKp(), p_pimToSzKz(), p_pipToSpKp(), p_pizToSzKp(), G4InuclParticleNames::pion(), and G4INCL::PiZero.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToSK2pi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1270 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1270 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), and G4INCL::PiZero.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NpiToSKpi (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1174 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1174 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), and G4INCL::PiZero.
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::NSToNL (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1458 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1458 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isSigma(), G4INCL::KinematicsUtils::momentumInLab(), and G4INCL::SigmaZero.
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NSToNS (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1497 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1497 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isSigma(), G4INCL::KinematicsUtils::momentumInLab(), and G4INCL::Neutron.
Referenced by total().
G4double G4INCL::CrossSectionsStrangeness::NYelastic (Particle const *const p1, Particle const *const p2) virtual
elastic scattering for Nucleon-Strange Particles cross sections
elastic cross sections
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 300 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 300 of file G4INCLCrossSectionsStrangeness.cc
References e, G4InuclParticleNames::hyperon(), G4INCL::Particle::isHyperon(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by elastic().
G4double G4INCL::CrossSectionsStrangeness::p_kmToL_pp_pm (Particle const *const p1, Particle const *const p2) virtual
Definition at line 1898 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1898 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::KinematicsUtils::momentumInLab().
Referenced by NKbToL2pi().
G4double G4INCL::CrossSectionsStrangeness::p_kmToL_pz (Particle const *const p1, Particle const *const p2) virtual
Definition at line 1796 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1796 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::KinematicsUtils::momentumInLab().
Referenced by NKbToLpi().
G4double G4INCL::CrossSectionsStrangeness::p_pimToLK0 (Particle const *const p1, Particle const *const p2)
Definition at line 1020 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1020 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::KinematicsUtils::momentumInLab().
Referenced by NpiToLK().
G4double G4INCL::CrossSectionsStrangeness::p_pimToSmKp (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1073 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1073 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::KinematicsUtils::momentumInLab().
Referenced by NpiToSK().
G4double G4INCL::CrossSectionsStrangeness::p_pimToSzKz (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1118 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1118 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::Particle::getType(), G4INCL::KinematicsUtils::momentumInLab(), and G4INCL::PiZero.
Referenced by NpiToSK().
G4double G4INCL::CrossSectionsStrangeness::p_pipToSpKp (Particle const *const p1, Particle const *const p2)
Definition at line 1088 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1088 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::KinematicsUtils::momentumInLab().
Referenced by NpiToSK().
G4double G4INCL::CrossSectionsStrangeness::p_pizToSzKp (Particle const *const p1, Particle const *const p2) virtual
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1103 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::KinematicsUtils::momentumInLab().
Referenced by NpiToSK().
G4double G4INCL::CrossSectionsStrangeness::piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
correction to old cross section
Reimplemented from G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 143 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 143 of file G4INCLCrossSectionsStrangeness.cc
References e, NpiToLK(), NpiToLK2pi(), NpiToLKpi(), NpiToMissingStrangeness(), NpiToNKKb(), NpiToSK(), NpiToSK2pi(), NpiToSKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToOmegaN(), and G4INCL::CrossSectionsMultiPions::piNToxPiN().
G4double G4INCL::CrossSectionsStrangeness::total (Particle const *const p1, Particle const *const p2) virtual
second new total particle-particle cross section
redefining previous cross sections
Reimplemented from G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 82 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 82 of file G4INCLCrossSectionsStrangeness.cc
References elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaPrimeNToPiN(), G4INCL::Particle::isAntiKaon(), G4INCL::Particle::isDelta(), G4INCL::Particle::isEta(), G4INCL::Particle::isEtaPrime(), G4INCL::Particle::isKaon(), G4INCL::Particle::isLambda(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isOmega(), G4INCL::Particle::isPion(), G4INCL::Particle::isSigma(), NDeltaToDeltaLK(), NDeltaToDeltaSK(), NDeltaToNLK(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), NDeltaToNNKKb(), NDeltaToNSK(), NKbToL2pi(), NKbToLpi(), NKbToNKb(), NKbToNKb2pi(), NKbToNKbpi(), NKbToS2pi(), NKbToSpi(), NKToNK(), NKToNK2pi(), NKToNKpi(), NLToNS(), G4INCL::CrossSectionsMultiPions::NNTot(), NSToNL(), NSToNS(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNInelastic(), and G4INCL::CrossSectionsMultiPions::piNTot().
Member Data Documentation
const G4int G4INCL::CrossSectionsStrangeness::nMaxPiNN = 4 static protected
Maximum number of outgoing pions in NN collisions.
Definition at line 133 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 133 of file G4INCLCrossSectionsStrangeness.hh
const G4int G4INCL::CrossSectionsStrangeness::nMaxPiPiN = 4 static protected
Maximum number of outgoing pions in piN collisions.
Definition at line 136 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 136 of file G4INCLCrossSectionsStrangeness.hh
const HornerC8 G4INCL::CrossSectionsStrangeness::s01ppHC protected
Horner coefficients for s01pp.
Definition at line 141 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 141 of file G4INCLCrossSectionsStrangeness.hh
const HornerC4 G4INCL::CrossSectionsStrangeness::s01pzHC protected
Horner coefficients for s01pz.
Definition at line 143 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 143 of file G4INCLCrossSectionsStrangeness.hh
const HornerC6 G4INCL::CrossSectionsStrangeness::s02pmHC protected
Horner coefficients for s02pm.
Definition at line 155 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 155 of file G4INCLCrossSectionsStrangeness.hh
const HornerC4 G4INCL::CrossSectionsStrangeness::s02pzHC protected
Horner coefficients for s02pz.
Definition at line 153 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 153 of file G4INCLCrossSectionsStrangeness.hh
const HornerC4 G4INCL::CrossSectionsStrangeness::s11pmHC protected
Horner coefficients for s11pm.
Definition at line 145 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 145 of file G4INCLCrossSectionsStrangeness.hh
const HornerC7 G4INCL::CrossSectionsStrangeness::s11pzHC protected
Horner coefficients for s11pz.
Definition at line 139 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 139 of file G4INCLCrossSectionsStrangeness.hh
const HornerC4 G4INCL::CrossSectionsStrangeness::s12mzHC protected
Horner coefficients for s12mz.
Definition at line 157 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 157 of file G4INCLCrossSectionsStrangeness.hh
const HornerC5 G4INCL::CrossSectionsStrangeness::s12pmHC protected
Horner coefficients for s12pm.
Definition at line 147 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 147 of file G4INCLCrossSectionsStrangeness.hh
const HornerC3 G4INCL::CrossSectionsStrangeness::s12ppHC protected
Horner coefficients for s12pp.
Definition at line 149 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 149 of file G4INCLCrossSectionsStrangeness.hh
const HornerC4 G4INCL::CrossSectionsStrangeness::s12zzHC protected
Horner coefficients for s12zz.
Definition at line 151 of file G4INCLCrossSectionsStrangeness.hh.
View newest version in sPHENIX GitHub at line 151 of file G4INCLCrossSectionsStrangeness.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsStrangeness.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsStrangeness.cc