ECCE @ EIC Software: B1ConRunAction Class Reference
B1ConRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1ConRunAction.hh>
Public Member Functions
B1ConRunAction ()
virtual ~B1ConRunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4ConvergenceTester * fdose_tally
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Run action class
In EndOfRunAction(), it calculates the dose in the selected volume from the energy deposit accumulated via stepping and event actions. The computed dose is then printed on the screen.
Definition at line 46 of file B1ConRunAction.hh.
View newest version in sPHENIX GitHub at line 46 of file B1ConRunAction.hh
Constructor & Destructor Documentation
B1ConRunAction::B1ConRunAction ()
Definition at line 43 of file B1ConRunAction.cc.
View newest version in sPHENIX GitHub at line 43 of file B1ConRunAction.cc
References gray, microgray, and milligray.
B1ConRunAction::~B1ConRunAction () virtual
Definition at line 62 of file B1ConRunAction.cc.
View newest version in sPHENIX GitHub at line 62 of file B1ConRunAction.cc
Member Function Documentation
void B1ConRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 74 of file B1ConRunAction.cc.
View newest version in sPHENIX GitHub at line 74 of file B1ConRunAction.cc
References fdose_tally, G4cout, G4endl, G4Run::GetRunID(), G4RunManager::GetRunManager(), G4UserRunAction::IsMaster(), and G4RunManager::SetRandomNumberStore().
void B1ConRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 90 of file B1ConRunAction.cc.
View newest version in sPHENIX GitHub at line 90 of file B1ConRunAction.cc
References G4ConvergenceTester::AddScore(), dose, edep, fdose_tally, G4BestUnit, G4cout, G4endl, B1Run::GetEdep(), B1Run::GetEdep2(), B1ConRun::GetEdepPerEvent(), G4LogicalVolume::GetMass(), B1ConRun::GetNumberOfEvent(), G4Run::GetNumberOfEvent(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), B1PrimaryGeneratorAction::GetParticleGun(), G4ParticleDefinition::GetParticleName(), G4RunManager::GetRunManager(), B1DetectorConstruction::GetScoringVolume(), G4RunManager::GetUserDetectorConstruction(), G4RunManager::GetUserPrimaryGeneratorAction(), gray, G4UserRunAction::IsMaster(), mass, G4ConvergenceTester::ShowHistory(), and G4ConvergenceTester::ShowResult().
G4Run * B1ConRunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 67 of file B1ConRunAction.cc.
View newest version in sPHENIX GitHub at line 67 of file B1ConRunAction.cc
Member Data Documentation
G4ConvergenceTester* B1ConRunAction::fdose_tally private
Definition at line 56 of file B1ConRunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file B1ConRunAction.hh
Referenced by BeginOfRunAction(), and EndOfRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1ConRunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/src/B1ConRunAction.cc