ECCE @ EIC Software: ExN03DetectorMessenger Class Reference
ExN03DetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ExN03geom/ExN03DetectorMessenger.hh>
Public Member Functions
ExN03DetectorMessenger (ExN03DetectorConstruction *)
~ExN03DetectorMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
ExN03DetectorConstruction * ExN03Detector
G4UIdirectory * N03Dir
G4UIdirectory * detDir
G4UIcmdWithAString * AbsMaterCmd
G4UIcmdWithAString * GapMaterCmd
G4UIcmdWithADoubleAndUnit * AbsThickCmd
G4UIcmdWithADoubleAndUnit * GapThickCmd
G4UIcmdWithADoubleAndUnit * SizeYZCmd
G4UIcmdWithAnInteger * NbLayersCmd
G4UIcmdWithADoubleAndUnit * MagFieldCmd
G4UIcmdWithoutParameter * UpdateCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 48 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN03DetectorMessenger.hh
Constructor & Destructor Documentation
ExN03DetectorMessenger::ExN03DetectorMessenger (ExN03DetectorConstruction * ExN03Det)
Definition at line 44 of file ExN03DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 44 of file ExN03DetectorMessenger.cc
References AbsMaterCmd, AbsThickCmd, G4UIcommand::AvailableForStates(), detDir, G4State_Idle, G4State_PreInit, GapMaterCmd, GapThickCmd, MagFieldCmd, N03Dir, NbLayersCmd, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), SizeYZCmd, and UpdateCmd.
ExN03DetectorMessenger::~ExN03DetectorMessenger ()
Definition at line 107 of file ExN03DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 107 of file ExN03DetectorMessenger.cc
References AbsMaterCmd, AbsThickCmd, detDir, GapMaterCmd, GapThickCmd, MagFieldCmd, N03Dir, NbLayersCmd, SizeYZCmd, and UpdateCmd.
Member Function Documentation
void ExN03DetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 120 of file ExN03DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 120 of file ExN03DetectorMessenger.cc
References AbsMaterCmd, AbsThickCmd, ExN03Detector, GapMaterCmd, GapThickCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), MagFieldCmd, NbLayersCmd, ExN03DetectorConstruction::SetAbsorberMaterial(), ExN03DetectorConstruction::SetAbsorberThickness(), ExN03DetectorConstruction::SetCalorSizeYZ(), ExN03DetectorConstruction::SetGapMaterial(), ExN03DetectorConstruction::SetGapThickness(), ExN03DetectorConstruction::SetMagField(), ExN03DetectorConstruction::SetNbOfLayers(), SizeYZCmd, UpdateCmd, and ExN03DetectorConstruction::UpdateGeometry().
Member Data Documentation
G4UIcmdWithAString* ExN03DetectorMessenger::AbsMaterCmd private
Definition at line 61 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIcmdWithADoubleAndUnit* ExN03DetectorMessenger::AbsThickCmd private
Definition at line 63 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIdirectory* ExN03DetectorMessenger::detDir private
Definition at line 60 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), and ~ExN03DetectorMessenger().
ExN03DetectorConstruction* ExN03DetectorMessenger::ExN03Detector private
Definition at line 57 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN03DetectorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* ExN03DetectorMessenger::GapMaterCmd private
Definition at line 62 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIcmdWithADoubleAndUnit* ExN03DetectorMessenger::GapThickCmd private
Definition at line 64 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIcmdWithADoubleAndUnit* ExN03DetectorMessenger::MagFieldCmd private
Definition at line 67 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIdirectory* ExN03DetectorMessenger::N03Dir private
Definition at line 59 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), and ~ExN03DetectorMessenger().
G4UIcmdWithAnInteger* ExN03DetectorMessenger::NbLayersCmd private
Definition at line 66 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIcmdWithADoubleAndUnit* ExN03DetectorMessenger::SizeYZCmd private
Definition at line 65 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
G4UIcmdWithoutParameter* ExN03DetectorMessenger::UpdateCmd private
Definition at line 68 of file ExN03DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file ExN03DetectorMessenger.hh
Referenced by ExN03DetectorMessenger(), SetNewValue(), and ~ExN03DetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ExN03geom/ExN03DetectorMessenger.hh
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ExN03geom/ExN03DetectorMessenger.cc