ECCE @ EIC Software: G4EvaporationProbability Class Reference
G4EvaporationProbability Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4EvaporationProbability.hh>
Public Member Functions
G4EvaporationProbability (G4int anA, G4int aZ, G4double aGamma)
~G4EvaporationProbability () override
virtual G4double TotalProbability (const G4Fragment &fragment, G4double minKinEnergy, G4double maxKinEnergy, G4double CB, G4double exEnergy)
G4double ComputeProbability (G4double K, G4double CB) override
G4double SampleKineticEnergy (G4double minKinEnergy, G4double maxKinEnergy, G4double CB)
Public Member Functions inherited from G4VEmissionProbability
G4VEmissionProbability (G4int Z, G4int A)
virtual ~G4VEmissionProbability ()
void Initialise ()
virtual G4double EmissionProbability (const G4Fragment &fragment, G4double anEnergy)
G4int GetZ (void) const
G4int GetA (void) const
void SetDecayKinematics (G4int Z, G4int A, G4double rmass, G4double fmass)
G4double GetRecoilExcitation () const
void SetEvapExcitation (G4double exc)
G4double GetProbability () const
void ResetProbability ()
G4double SampleEnergy ()
Protected Member Functions
virtual G4double CalcAlphaParam (const G4Fragment &fragment)
virtual G4double CalcBetaParam (const G4Fragment &fragment)
Protected Member Functions inherited from G4VEmissionProbability
void ResetIntegrator (size_t nbin, G4double de, G4double eps)
G4double IntegrateProbability (G4double elow, G4double ehigh, G4double CB)
Private Member Functions
G4double CrossSection (G4double K, G4double CB)
G4EvaporationProbability (const G4EvaporationProbability &right)
const G4EvaporationProbability & operator= (const G4EvaporationProbability &right)
G4bool operator== (const G4EvaporationProbability &right) const
G4bool operator!= (const G4EvaporationProbability &right) const
Private Attributes
G4int index
G4double resA13
G4double muu
G4double freeU
G4double a0
G4double delta1
G4double fGamma
G4double pcoeff
Additional Inherited Members
Protected Attributes inherited from G4VEmissionProbability
G4int OPTxs
G4int pVerbose
G4int theZ
G4int theA
G4int resZ
G4int resA
G4double pMass
G4double pEvapMass
G4double pResMass
G4double pProbability
G4NuclearLevelData * pNuclearLevelData
G4Pow * pG4pow
Detailed Description
Definition at line 41 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 41 of file G4EvaporationProbability.hh
Constructor & Destructor Documentation
G4EvaporationProbability::G4EvaporationProbability (G4int anA, G4int aZ, G4double aGamma) explicit
Definition at line 59 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 59 of file G4EvaporationProbability.cc
References a0, delta1, fGamma, freeU, CLHEP::hbarc, index, CLHEP::MeV, CLHEP::millibarn, muu, pcoeff, G4VEmissionProbability::pEvapMass, CLHEP::pi, resA13, G4VEmissionProbability::ResetIntegrator(), G4VEmissionProbability::theA, and G4VEmissionProbability::theZ.
G4EvaporationProbability::~G4EvaporationProbability () override
Definition at line 79 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 79 of file G4EvaporationProbability.cc
G4EvaporationProbability::G4EvaporationProbability (const G4EvaporationProbability & right) private
Member Function Documentation
G4double G4EvaporationProbability::CalcAlphaParam (const G4Fragment & fragment) protected virtual
Reimplemented in G4TritonEvaporationProbability, G4DeuteronEvaporationProbability, G4NeutronEvaporationProbability, G4AlphaEvaporationProbability, G4ProtonEvaporationProbability, and G4He3EvaporationProbability.
Definition at line 82 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 82 of file G4EvaporationProbability.cc
Referenced by TotalProbability().
G4double G4EvaporationProbability::CalcBetaParam (const G4Fragment & fragment) protected virtual
Reimplemented in G4TritonEvaporationProbability, G4DeuteronEvaporationProbability, G4NeutronEvaporationProbability, G4AlphaEvaporationProbability, G4ProtonEvaporationProbability, and G4He3EvaporationProbability.
Definition at line 87 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 87 of file G4EvaporationProbability.cc
Referenced by TotalProbability().
G4double G4EvaporationProbability::ComputeProbability (G4double K, G4double CB) override virtual
Reimplemented from G4VEmissionProbability.
Definition at line 151 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 151 of file G4EvaporationProbability.cc
References a0, CrossSection(), delta1, freeU, G4Exp(), G4NuclearLevelData::GetLevelDensity(), pcoeff, G4VEmissionProbability::pEvapMass, G4VEmissionProbability::pMass, G4VEmissionProbability::pNuclearLevelData, G4VEmissionProbability::pResMass, G4VEmissionProbability::resA, and G4VEmissionProbability::resZ.
G4double G4EvaporationProbability::CrossSection (G4double K, G4double CB) private
Definition at line 180 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 180 of file G4EvaporationProbability.cc
References G4ChatterjeeCrossSection::ComputeCrossSection(), G4KalbachCrossSection::ComputeCrossSection(), index, muu, G4VEmissionProbability::OPTxs, G4VEmissionProbability::resA, resA13, G4VEmissionProbability::theA, and G4VEmissionProbability::theZ.
Referenced by ComputeProbability().
G4bool G4EvaporationProbability::operator!= (const G4EvaporationProbability & right) const private
const G4EvaporationProbability& G4EvaporationProbability::operator= (const G4EvaporationProbability & right) private
G4bool G4EvaporationProbability::operator== (const G4EvaporationProbability & right) const private
G4double G4EvaporationProbability::SampleKineticEnergy (G4double minKinEnergy, G4double maxKinEnergy, G4double CB)
Definition at line 196 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 196 of file G4EvaporationProbability.cc
References a0, explim, G4AblaRandom::flat(), CLHEP::HepRandomEngine::flat(), freeU, G4Exp(), G4Log(), max, MeV, nmax, G4InuclParticleNames::nn, G4VEmissionProbability::OPTxs, resA13, G4VEmissionProbability::SampleEnergy(), T, and G4VEmissionProbability::theZ.
G4double G4EvaporationProbability::TotalProbability (const G4Fragment & fragment, G4double minKinEnergy, G4double maxKinEnergy, G4double CB, G4double exEnergy) virtual
Definition at line 92 of file G4EvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 92 of file G4EvaporationProbability.cc
References a0, Alpha, CalcAlphaParam(), CalcBetaParam(), G4KalbachCrossSection::ComputePowerParameter(), delta1, explim, CLHEP::fermi, fGamma, freeU, G4Exp(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4NuclearLevelData::GetPairingCorrection(), G4Fragment::GetZ_asInt(), CLHEP::hbar_Planck, source.hepunit::hbar_Planck, index, G4VEmissionProbability::IntegrateProbability(), min, muu, G4VEmissionProbability::OPTxs, G4VEmissionProbability::pEvapMass, G4VEmissionProbability::pG4pow, G4VEmissionProbability::pNuclearLevelData, G4VEmissionProbability::pProbability, G4VEmissionProbability::resA, resA13, G4VEmissionProbability::resZ, CLHEP::twopi, and G4Pow::Z13().
Referenced by G4EvaporationChannel::GetEmissionProbability().
Member Data Documentation
G4double G4EvaporationProbability::a0 private
Definition at line 94 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 94 of file G4EvaporationProbability.hh
Referenced by ComputeProbability(), G4EvaporationProbability(), SampleKineticEnergy(), and TotalProbability().
G4double G4EvaporationProbability::delta1 private
Definition at line 95 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 95 of file G4EvaporationProbability.hh
Referenced by ComputeProbability(), G4EvaporationProbability(), and TotalProbability().
G4double G4EvaporationProbability::fGamma private
Definition at line 99 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 99 of file G4EvaporationProbability.hh
Referenced by G4EvaporationProbability(), and TotalProbability().
G4double G4EvaporationProbability::freeU private
Definition at line 93 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 93 of file G4EvaporationProbability.hh
Referenced by ComputeProbability(), G4EvaporationProbability(), SampleKineticEnergy(), and TotalProbability().
G4int G4EvaporationProbability::index private
Definition at line 89 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 89 of file G4EvaporationProbability.hh
Referenced by CrossSection(), G4EvaporationProbability(), and TotalProbability().
G4double G4EvaporationProbability::muu private
Definition at line 92 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 92 of file G4EvaporationProbability.hh
Referenced by CrossSection(), G4EvaporationProbability(), and TotalProbability().
G4double G4EvaporationProbability::pcoeff private
Definition at line 100 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 100 of file G4EvaporationProbability.hh
Referenced by ComputeProbability(), and G4EvaporationProbability().
G4double G4EvaporationProbability::resA13 private
Definition at line 91 of file G4EvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 91 of file G4EvaporationProbability.hh
Referenced by CrossSection(), G4EvaporationProbability(), SampleKineticEnergy(), and TotalProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4EvaporationProbability.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4EvaporationProbability.cc