ECCE @ EIC Software: G4LundStringFragmentation Class Reference
G4LundStringFragmentation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4LundStringFragmentation.hh>
Public Member Functions
G4LundStringFragmentation ()
virtual ~G4LundStringFragmentation ()
virtual G4KineticTrackVector * FragmentString (const G4ExcitedString &theString)
Public Member Functions inherited from G4VLongitudinalStringDecay
G4VLongitudinalStringDecay ()
virtual ~G4VLongitudinalStringDecay ()
void AddNewParticles ()
void EraseNewParticles ()
void SetMinMasses ()
void SetMinimalStringMass (const G4FragmentingString *const string)
void SetMinimalStringMass2 (const G4double aValue)
G4int SampleQuarkFlavor (void)
G4ThreeVector SampleQuarkPt (G4double ptMax=-1.)
void SetSigmaTransverseMomentum (G4double aQT)
void SetStrangenessSuppression (G4double aValue)
void SetDiquarkSuppression (G4double aValue)
void SetDiquarkBreakProbability (G4double aValue)
void SetVectorMesonProbability (G4double aValue)
void SetSpinThreeHalfBarionProbability (G4double aValue)
void SetScalarMesonMixings (std::vector< G4double > aVector)
void SetVectorMesonMixings (std::vector< G4double > aVector)
void SetStringTensionParameter (G4double aValue)
void SetProbCCbar (G4double aValue)
void SetProbEta_c (G4double aValue)
void SetProbBBbar (G4double aValue)
void SetProbEta_b (G4double aValue)
Private Member Functions
G4LundStringFragmentation (const G4LundStringFragmentation &right)
const G4LundStringFragmentation & operator= (const G4LundStringFragmentation &right)
G4bool operator== (const G4LundStringFragmentation &right) const
G4bool operator!= (const G4LundStringFragmentation &right) const
virtual G4bool StopFragmenting (const G4FragmentingString *const string)
virtual G4bool IsItFragmentable (const G4FragmentingString *const string)
virtual G4bool SplitLast (G4FragmentingString *string, G4KineticTrackVector *LeftVector, G4KineticTrackVector *RightVector)
virtual void Sample4Momentum (G4LorentzVector *Mom, G4double Mass, G4LorentzVector *AntiMom, G4double AntiMass, G4double InitialMass)
virtual G4KineticTrack * Splitup (G4FragmentingString *string, G4FragmentingString *&newString)
virtual G4LorentzVector * SplitEandP (G4ParticleDefinition *pHadron, G4FragmentingString *string, G4FragmentingString *newString)
virtual G4double GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition *pHadron, G4double Px, G4double Py)
G4double lambda (G4double s, G4double m1_Sqr, G4double m2_Sqr)
virtual G4ParticleDefinition * DiQuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
G4bool Loop_toFragmentString (const G4ExcitedString &theStringInCMS, G4KineticTrackVector *&LeftVector, G4KineticTrackVector *&RightVector)
G4bool Diquark_AntiDiquark_belowThreshold_lastSplitting (G4FragmentingString *&string, G4ParticleDefinition *&LeftHadron, G4ParticleDefinition *&RightHadron)
G4bool Diquark_AntiDiquark_aboveThreshold_lastSplitting (G4FragmentingString *&string, G4ParticleDefinition *&LeftHadron, G4ParticleDefinition *&RightHadron)
G4bool Quark_AntiQuark_lastSplitting (G4FragmentingString *&string, G4ParticleDefinition *&LeftHadron, G4ParticleDefinition *&RightHadron)
G4bool Quark_Diquark_lastSplitting (G4FragmentingString *&string, G4ParticleDefinition *&LeftHadron, G4ParticleDefinition *&RightHadron)
G4int SampleState (void)
Additional Inherited Members
Public Attributes inherited from G4VLongitudinalStringDecay
G4double Mass_of_light_quark
G4double Mass_of_s_quark
G4double Mass_of_c_quark
G4double Mass_of_b_quark
G4double Mass_of_string_junction
G4double minMassQQbarStr [5][5]
G4double minMassQDiQStr [5][5][5]
G4double MinimalStringMass
G4double MinimalStringMass2
G4int Qcharge [5]
G4int Meson [5][5][7]
G4double MesonWeight [5][5][7]
G4int Baryon [5][5][5][4]
G4double BaryonWeight [5][5][5][4]
G4double Prob_QQbar [5]
G4int DecayQuark
G4int NewQuark
G4ParticleDefinition * FS_LeftHadron [350]
G4ParticleDefinition * FS_RightHadron [350]
G4double FS_Weight [350]
G4int NumberOf_FS
Protected Types inherited from G4VLongitudinalStringDecay
typedef std::pair
< G4ParticleDefinition
*, G4ParticleDefinition * > pDefPair
typedef G4ParticleDefinition
*(G4HadronBuilder::* Pcreate)(G4ParticleDefinition *, G4ParticleDefinition *)
Protected Member Functions inherited from G4VLongitudinalStringDecay
virtual void SetMassCut (G4double aValue)
G4double GetMassCut ()
G4KineticTrackVector * ProduceOneHadron (const G4ExcitedString *const theString)
G4double PossibleHadronMass (const G4FragmentingString *const string, Pcreate build=0, pDefPair *pdefs=0)
G4ParticleDefinition * FindParticle (G4int Encoding)
G4ExcitedString * CopyExcited (const G4ExcitedString &string)
virtual G4ParticleDefinition * QuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
pDefPair CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks=true)
void CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector *)
void ConstructParticle ()
G4ParticleDefinition * CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin)
G4double GetDiquarkSuppress ()
G4double GetDiquarkBreakProb ()
G4double GetStrangeSuppress ()
G4int GetClusterLoopInterrupt ()
G4double GetProbCCbar ()
G4double GetProbEta_c ()
G4double GetProbBBbar ()
G4double GetProbEta_b ()
G4double GetStringTensionParameter ()
Protected Attributes inherited from G4VLongitudinalStringDecay
G4double MassCut
G4double SigmaQT
G4double DiquarkSuppress
G4double DiquarkBreakProb
G4double StrangeSuppress
G4int StringLoopInterrupt
G4int ClusterLoopInterrupt
G4HadronBuilder * hadronizer
G4double pspin_meson
G4double pspin_barion
std::vector< G4double > vectorMesonMix
std::vector< G4double > scalarMesonMix
G4double ProbCCbar
G4double ProbEta_c
G4double ProbBBbar
G4double ProbEta_b
G4double ProbCB
G4double MaxMass
G4bool PastInitPhase
G4double Kappa
std::vector
< G4ParticleDefinition * > NewParticles
Detailed Description
Definition at line 41 of file G4LundStringFragmentation.hh.
View newest version in sPHENIX GitHub at line 41 of file G4LundStringFragmentation.hh
Constructor & Destructor Documentation
G4LundStringFragmentation::G4LundStringFragmentation ()
Definition at line 49 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 49 of file G4LundStringFragmentation.cc
References fermi, GeV, MeV, G4VLongitudinalStringDecay::SetDiquarkBreakProbability(), G4VLongitudinalStringDecay::SetDiquarkSuppression(), G4VLongitudinalStringDecay::SetMassCut(), G4VLongitudinalStringDecay::SetMinMasses(), G4VLongitudinalStringDecay::SetProbBBbar(), G4VLongitudinalStringDecay::SetProbCCbar(), G4VLongitudinalStringDecay::SetStrangenessSuppression(), G4VLongitudinalStringDecay::SetStringTensionParameter(), and G4VLongitudinalStringDecay::SigmaQT.
G4LundStringFragmentation::~G4LundStringFragmentation () virtual
Definition at line 1274 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 1274 of file G4LundStringFragmentation.cc
G4LundStringFragmentation::G4LundStringFragmentation (const G4LundStringFragmentation & right) private
Member Function Documentation
G4bool G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting (G4FragmentingString *& string, G4ParticleDefinition *& LeftHadron, G4ParticleDefinition *& RightHadron) private
Definition at line 830 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 830 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4VLongitudinalStringDecay::Baryon, G4VLongitudinalStringDecay::BaryonWeight, G4ParticleTable::FindParticle(), G4VLongitudinalStringDecay::FS_LeftHadron, G4VLongitudinalStringDecay::FS_RightHadron, G4VLongitudinalStringDecay::FS_Weight, G4endl, G4Exception(), G4FragmentingString::GetLeftParton(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), JustWarning, lambda(), G4VLongitudinalStringDecay::NumberOf_FS, G4VLongitudinalStringDecay::Prob_QQbar, and sqr().
Referenced by SplitLast().
G4bool G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting (G4FragmentingString *& string, G4ParticleDefinition *& LeftHadron, G4ParticleDefinition *& RightHadron) private
Definition at line 784 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 784 of file G4LundStringFragmentation.cc
References G4HadronBuilder::Build(), G4VLongitudinalStringDecay::ClusterLoopInterrupt, G4VLongitudinalStringDecay::FindParticle(), G4UniformRand, G4ParticleDefinition::GetPDGMass(), and G4VLongitudinalStringDecay::hadronizer.
Referenced by SplitLast().
G4ParticleDefinition * G4LundStringFragmentation::DiQuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 422 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 422 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4HadronBuilder::Build(), G4VLongitudinalStringDecay::CreatePartonPair(), G4VLongitudinalStringDecay::DiquarkBreakProb, G4VLongitudinalStringDecay::FindParticle(), G4UniformRand, G4ParticleDefinition::GetPDGEncoding(), G4VLongitudinalStringDecay::GetStrangeSuppress(), G4VLongitudinalStringDecay::hadronizer, max, min, and G4VLongitudinalStringDecay::StrangeSuppress.
Referenced by Splitup().
G4KineticTrackVector * G4LundStringFragmentation::FragmentString (const G4ExcitedString & theString) virtual
Implements G4VLongitudinalStringDecay.
Definition at line 72 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 72 of file G4LundStringFragmentation.cc
References G4cout, G4endl, G4Parton::Get4Momentum(), G4ExcitedString::Get4Momentum(), G4ExcitedString::GetDirection(), G4ExcitedString::GetLeftParton(), G4VLongitudinalStringDecay::GetMassCut(), G4Parton::GetPDGcode(), G4ExcitedString::GetPosition(), G4ExcitedString::GetRightParton(), G4ExcitedString::GetTimeOfCreation(), G4FragmentingString::IsAFourQuarkString(), IsItFragmentable(), Loop_toFragmentString(), CLHEP::HepLorentzVector::mag(), MeV, G4VLongitudinalStringDecay::PastInitPhase, G4VLongitudinalStringDecay::ProduceOneHadron(), G4VLongitudinalStringDecay::SetMassCut(), and G4VLongitudinalStringDecay::SetMinimalStringMass().
G4double G4LundStringFragmentation::GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition * pHadron, G4double Px, G4double Py) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 579 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 579 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4InuclParticleNames::an, G4Exp(), G4UniformRand, G4Pow::GetInstance(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, G4Pow::powA(), sqr(), and z.
Referenced by SplitEandP().
G4bool G4LundStringFragmentation::IsItFragmentable (const G4FragmentingString *const string) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 154 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 154 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4VLongitudinalStringDecay::MinimalStringMass, and G4VLongitudinalStringDecay::SetMinimalStringMass().
Referenced by FragmentString().
G4double G4LundStringFragmentation::lambda (G4double s, G4double m1_Sqr, G4double m2_Sqr) private
Definition at line 1267 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 1267 of file G4LundStringFragmentation.cc
References G4InuclParticleNames::lam, and sqr().
Referenced by Diquark_AntiDiquark_aboveThreshold_lastSplitting(), Quark_AntiQuark_lastSplitting(), and Quark_Diquark_lastSplitting().
G4bool G4LundStringFragmentation::Loop_toFragmentString (const G4ExcitedString & theStringInCMS, G4KineticTrackVector *& LeftVector, G4KineticTrackVector *& RightVector) private
Definition at line 166 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 166 of file G4LundStringFragmentation.cc
References source.hepunit::c_light, fermi, G4cout, G4endl, G4Parton::Get4Momentum(), G4KineticTrack::Get4Momentum(), G4FragmentingString::GetDecayDirection(), G4KineticTrack::GetDefinition(), G4ExcitedString::GetDirection(), G4KineticTrack::GetFormationTime(), G4ExcitedString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4Parton::GetPDGcode(), G4ExcitedString::GetPosition(), G4KineticTrack::GetPosition(), G4ExcitedString::GetRightParton(), G4ExcitedString::GetTimeOfCreation(), CLHEP::HepLorentzRotation::inverse(), G4FragmentingString::LorentzRotate(), G4KineticTrack::Set4Momentum(), G4KineticTrack::SetFormationTime(), G4KineticTrack::SetPosition(), SplitLast(), Splitup(), StopFragmenting(), G4VLongitudinalStringDecay::StringLoopInterrupt, and G4FragmentingString::TransformToAlignedCms().
Referenced by FragmentString().
G4bool G4LundStringFragmentation::operator!= (const G4LundStringFragmentation & right) const private
const G4LundStringFragmentation& G4LundStringFragmentation::operator= (const G4LundStringFragmentation & right) private
G4bool G4LundStringFragmentation::operator== (const G4LundStringFragmentation & right) const private
G4bool G4LundStringFragmentation::Quark_AntiQuark_lastSplitting (G4FragmentingString *& string, G4ParticleDefinition *& LeftHadron, G4ParticleDefinition *& RightHadron) private
Definition at line 1045 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 1045 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4ParticleTable::FindParticle(), G4VLongitudinalStringDecay::FS_LeftHadron, G4VLongitudinalStringDecay::FS_RightHadron, G4VLongitudinalStringDecay::FS_Weight, G4endl, G4Exception(), G4FragmentingString::GetLeftParton(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), JustWarning, lambda(), G4VLongitudinalStringDecay::Meson, G4VLongitudinalStringDecay::MesonWeight, G4VLongitudinalStringDecay::NumberOf_FS, G4VLongitudinalStringDecay::Prob_QQbar, G4VLongitudinalStringDecay::Qcharge, and sqr().
Referenced by SplitLast().
G4bool G4LundStringFragmentation::Quark_Diquark_lastSplitting (G4FragmentingString *& string, G4ParticleDefinition *& LeftHadron, G4ParticleDefinition *& RightHadron) private
Definition at line 931 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 931 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4VLongitudinalStringDecay::Baryon, G4VLongitudinalStringDecay::BaryonWeight, G4ParticleTable::FindParticle(), G4VLongitudinalStringDecay::FS_LeftHadron, G4VLongitudinalStringDecay::FS_RightHadron, G4VLongitudinalStringDecay::FS_Weight, G4endl, G4Exception(), G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetParticleSubType(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), JustWarning, lambda(), G4VLongitudinalStringDecay::Meson, G4VLongitudinalStringDecay::MesonWeight, G4VLongitudinalStringDecay::NumberOf_FS, G4VLongitudinalStringDecay::Prob_QQbar, and sqr().
Referenced by SplitLast().
void G4LundStringFragmentation::Sample4Momentum (G4LorentzVector * Mom, G4double Mass, G4LorentzVector * AntiMom, G4double AntiMass, G4double InitialMass) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 1207 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 1207 of file G4LundStringFragmentation.cc
References G4cout, G4endl, CLHEP::HepLorentzVector::getT(), CLHEP::Hep3Vector::getX(), CLHEP::HepLorentzVector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::HepLorentzVector::getY(), CLHEP::HepLorentzVector::getZ(), CLHEP::Hep3Vector::mag2(), G4VLongitudinalStringDecay::SampleQuarkPt(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), CLHEP::Hep3Vector::setZ(), G4VLongitudinalStringDecay::SigmaQT, and sqr().
Referenced by SplitLast().
G4int G4LundStringFragmentation::SampleState (void) private
Definition at line 1179 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 1179 of file G4LundStringFragmentation.cc
References G4VLongitudinalStringDecay::FS_Weight, G4endl, G4Exception(), G4UniformRand, JustWarning, and G4VLongitudinalStringDecay::NumberOf_FS.
Referenced by SplitLast().
G4LorentzVector * G4LundStringFragmentation::SplitEandP (G4ParticleDefinition * pHadron, G4FragmentingString * string, G4FragmentingString * newString) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 477 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 477 of file G4LundStringFragmentation.cc
References G4cout, G4endl, G4Log(), G4UniformRand, G4FragmentingString::GetDecayDirection(), G4FragmentingString::GetDecayParton(), GetLightConeZ(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), G4FragmentingString::Mass(), G4VLongitudinalStringDecay::MinimalStringMass, phi, pi, G4VLongitudinalStringDecay::SetMinimalStringMass(), CLHEP::HepLorentzVector::setPz(), CLHEP::Hep3Vector::setZ(), sqr(), G4VLongitudinalStringDecay::StringLoopInterrupt, CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and z.
Referenced by Splitup().
G4bool G4LundStringFragmentation::SplitLast (G4FragmentingString * string, G4KineticTrackVector * LeftVector, G4KineticTrackVector * RightVector) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 635 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 635 of file G4LundStringFragmentation.cc
References kdfinder::abs(), G4FragmentingString::DecayIsQuark(), Diquark_AntiDiquark_aboveThreshold_lastSplitting(), Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4VLongitudinalStringDecay::FS_LeftHadron, G4VLongitudinalStringDecay::FS_RightHadron, G4VLongitudinalStringDecay::FS_Weight, G4cout, G4endl, G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzRotation::inverse(), G4FragmentingString::IsAFourQuarkString(), G4VLongitudinalStringDecay::MinimalStringMass, G4VLongitudinalStringDecay::NumberOf_FS, Quark_AntiQuark_lastSplitting(), Quark_Diquark_lastSplitting(), Sample4Momentum(), SampleState(), G4VLongitudinalStringDecay::SetMinimalStringMass(), tmp, and CLHEP::HepLorentzVector::z().
Referenced by Loop_toFragmentString().
G4KineticTrack * G4LundStringFragmentation::Splitup (G4FragmentingString * string, G4FragmentingString *& newString) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 304 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 304 of file G4LundStringFragmentation.cc
References G4FragmentingString::DecayIsQuark(), DiQuarkSplitup(), G4cout, G4endl, G4UniformRand, G4FragmentingString::GetDecayParton(), G4VLongitudinalStringDecay::GetDiquarkSuppress(), G4Pow::GetInstance(), G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetPDGEncoding(), G4FragmentingString::GetRightParton(), G4VLongitudinalStringDecay::GetStrangeSuppress(), G4Pow::powA(), G4VLongitudinalStringDecay::QuarkSplitup(), G4VLongitudinalStringDecay::SetDiquarkSuppression(), G4VLongitudinalStringDecay::SetStrangenessSuppression(), SplitEandP(), and sqr().
Referenced by Loop_toFragmentString().
G4bool G4LundStringFragmentation::StopFragmenting (const G4FragmentingString *const string) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 276 of file G4LundStringFragmentation.cc.
View newest version in sPHENIX GitHub at line 276 of file G4LundStringFragmentation.cc
References e, G4cout, G4endl, G4Exp(), G4UniformRand, G4FragmentingString::IsAFourQuarkString(), G4FragmentingString::Mass(), G4VLongitudinalStringDecay::MinimalStringMass, and G4VLongitudinalStringDecay::SetMinimalStringMass().
Referenced by Loop_toFragmentString().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4LundStringFragmentation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/src/G4LundStringFragmentation.cc