ECCE @ EIC Software: G4VPartonStringModel Class Reference
G4VPartonStringModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4VPartonStringModel.hh>
Public Member Functions
G4VPartonStringModel (const G4String &modelName="Parton String Model")
virtual ~G4VPartonStringModel ()
void SetFragmentationModel (G4VStringFragmentation *aModel)
G4KineticTrackVector * Scatter (const G4Nucleus &theNucleus, const G4DynamicParticle &thePrimary)
virtual G4V3DNucleus * GetWoundedNucleus () const =0
virtual void ModelDescription (std::ostream &outFile) const
virtual G4V3DNucleus * GetProjectileNucleus () const
Public Member Functions inherited from G4VHighEnergyGenerator
G4VHighEnergyGenerator (const G4String &modelName="High Energy Generator")
~G4VHighEnergyGenerator () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &, G4Nucleus &) final
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Member Functions
virtual void Init (const G4Nucleus &theNucleus, const G4DynamicParticle &thePrimary)=0
virtual G4ExcitedStringVector * GetStrings ()=0
void SetThisPointer (G4VPartonStringModel *aPointer)
G4bool EnergyAndMomentumCorrector (G4KineticTrackVector *Output, G4LorentzVector &TotalCollisionMomentum)
Private Member Functions
G4VPartonStringModel (const G4VPartonStringModel &right)
const G4VPartonStringModel & operator= (const G4VPartonStringModel &right)
G4bool operator== (const G4VPartonStringModel &right) const
G4bool operator!= (const G4VPartonStringModel &right) const
Private Attributes
G4VStringFragmentation * stringFragmentationModel
G4VPartonStringModel * theThis
Additional Inherited Members
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 50 of file G4VPartonStringModel.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VPartonStringModel.hh
Constructor & Destructor Documentation
G4VPartonStringModel::G4VPartonStringModel (const G4String & modelName = "Parton String Model")
Definition at line 46 of file G4VPartonStringModel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VPartonStringModel.cc
References G4ShortLivedConstructor::ConstructParticle().
G4VPartonStringModel::~G4VPartonStringModel () virtual
Definition at line 56 of file G4VPartonStringModel.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VPartonStringModel.cc
G4VPartonStringModel::G4VPartonStringModel (const G4VPartonStringModel & right) private
Member Function Documentation
G4bool G4VPartonStringModel::EnergyAndMomentumCorrector (G4KineticTrackVector * Output, G4LorentzVector & TotalCollisionMomentum) protected
G4V3DNucleus * G4VPartonStringModel::GetProjectileNucleus () const virtual
Reimplemented from G4VHighEnergyGenerator.
Reimplemented in G4FTFModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Definition at line 377 of file G4VPartonStringModel.cc.
View newest version in sPHENIX GitHub at line 377 of file G4VPartonStringModel.cc
Referenced by Scatter().
virtual G4ExcitedStringVector* G4VPartonStringModel::GetStrings () protected pure virtual
Implemented in G4FTFModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Referenced by Scatter().
virtual G4V3DNucleus* G4VPartonStringModel::GetWoundedNucleus () const pure virtual
Implements G4VHighEnergyGenerator.
Implemented in G4FTFModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Referenced by Scatter().
virtual void G4VPartonStringModel::Init (const G4Nucleus & theNucleus, const G4DynamicParticle & thePrimary) protected pure virtual
Implemented in G4FTFModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Referenced by Scatter().
void G4VPartonStringModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4VHighEnergyGenerator.
Reimplemented in G4FTFModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Definition at line 372 of file G4VPartonStringModel.cc.
View newest version in sPHENIX GitHub at line 372 of file G4VPartonStringModel.cc
References G4HadronicInteraction::GetModelName().
G4bool G4VPartonStringModel::operator!= (const G4VPartonStringModel & right) const private
const G4VPartonStringModel& G4VPartonStringModel::operator= (const G4VPartonStringModel & right) private
G4bool G4VPartonStringModel::operator== (const G4VPartonStringModel & right) const private
G4KineticTrackVector * G4VPartonStringModel::Scatter (const G4Nucleus & theNucleus, const G4DynamicParticle & thePrimary) virtual
Implements G4VHighEnergyGenerator.
Definition at line 60 of file G4VPartonStringModel.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VPartonStringModel.cc
References G4Nucleon::AreYouHit(), G4VStringFragmentation::FragmentStrings(), G4cout, G4endl, G4Exception(), G4Nucleon::Get4Momentum(), G4DynamicParticle::Get4Momentum(), G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetBaryonNumber(), G4Nucleon::GetBindingEnergy(), G4Nucleon::GetDefinition(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetMass(), G4V3DNucleus::GetNextNucleon(), G4V3DNucleus::GetOuterRadius(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), GetProjectileNucleus(), GetStrings(), GetWoundedNucleus(), G4Nucleus::GetZ_asInt(), G4Nucleon::Hit(), Init(), CLHEP::HepLorentzRotation::inverse(), JustWarning, CLHEP::HepLorentzVector::mag(), G4Neutron::Neutron(), CLHEP::HepLorentzVector::phi(), G4Proton::Proton(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4DynamicParticle::Set4Momentum(), G4Nucleon::SetMomentum(), G4V3DNucleus::StartLoop(), stringFragmentationModel, CLHEP::HepLorentzVector::theta(), theThis, and tmp.
void G4VPartonStringModel::SetFragmentationModel (G4VStringFragmentation * aModel) inline
Definition at line 81 of file G4VPartonStringModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VPartonStringModel.hh
References stringFragmentationModel.
Referenced by BiasingOperation::BiasingOperation(), G4BertiniElectroNuclearBuilder::Build(), G4FTFBuilder::BuildModel(), G4QGSBuilder::BuildModel(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder(), G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder(), G4QGSBinaryPiKBuilder::G4QGSBinaryPiKBuilder(), G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder(), G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder(), G4QGSPKaonBuilder::G4QGSPKaonBuilder(), G4QGSPLundStrFragmProtonBuilder::G4QGSPLundStrFragmProtonBuilder(), G4QGSPNeutronBuilder::G4QGSPNeutronBuilder(), G4QGSPPiKBuilder::G4QGSPPiKBuilder(), G4QGSPPionBuilder::G4QGSPPionBuilder(), and G4QGSPProtonBuilder::G4QGSPProtonBuilder().
void G4VPartonStringModel::SetThisPointer (G4VPartonStringModel * aPointer) inline protected
Definition at line 86 of file G4VPartonStringModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VPartonStringModel.hh
References theThis.
Referenced by G4FTFModel::G4FTFModel().
Member Data Documentation
G4VStringFragmentation* G4VPartonStringModel::stringFragmentationModel private
Definition at line 77 of file G4VPartonStringModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VPartonStringModel.hh
Referenced by Scatter(), and SetFragmentationModel().
G4VPartonStringModel* G4VPartonStringModel::theThis private
Definition at line 78 of file G4VPartonStringModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VPartonStringModel.hh
Referenced by Scatter(), and SetThisPointer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4VPartonStringModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/src/G4VPartonStringModel.cc