ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/plot_hist.C File Reference
plot_hist.C File Reference
Functions
TFile f ("testem6_0.root")
gPad SetLogy ()
h7 SetMinimum (minY)
h7 SetMaximum (maxY)
h7 GetXaxis () -> SetLimits(std::log10(minE), std::log10(maxE))
h7 SetTitle ("Comparison of e+ Annihilation Processes(totcrsPerAtom)")
h7 GetYaxis () -> SetTitle("microbarn")
h7 SetLineColor (kRed)
h9 SetLineColor (kBlue)
h11 SetMarkerColor (kRed)
h11 SetMarkerStyle (22)
c1 cd ()
h7 Draw ("HIST")
h8 Draw ("HIST SAME")
h10 Draw ("HIST P SAME")
xaxis SetTitle ("GeV")
xaxis Draw ()
gStyle SetOptStat (0)
leg AddEntry (h8,"to 2 gammas","l")
leg AddEntry (h7,"to MuPair","l")
leg AddEntry (h9,"to Hadrons","l")
h15 SetMinimum (minY1)
h15 SetMaximum (maxY1)
h15 SetTitle ("Comparison of EM Processes(totcrsPerVolume)")
h12 SetLineColor (6)
h13 SetLineColor (kGreen)
leg1 AddEntry (h15,"to 2 gammas","l")
leg1 AddEntry (h14,"to MuPair","l")
leg1 AddEntry (h16,"to Hadrons","l")
leg1 AddEntry (h12,"Bremsstrahlung","l")
leg1 AddEntry (h13,"Ionization","l")
Variables
double minE = 40
double maxE = 10000
double minY = 1e-2
double maxY = 1e+2
double minY1 = 1e-8
double maxY1 = 1
TH1D * h7 = (TH1D*)f.Get("h7")
TH1D * h8 = (TH1D*)f.Get("h8")
TH1D * h9 = (TH1D*)f.Get("h9")
TH1D * h10 = (TH1D*)f.Get("h10")
TH1D * h11 = (TH1D*)f.Get("h11")
TH1D * h12 = (TH1D*)f.Get("h12")
TH1D * h13 = (TH1D*)f.Get("h13")
TH1D * h14 = (TH1D*)f.Get("h14")
TH1D * h15 = (TH1D*)f.Get("h15")
TH1D * h16 = (TH1D*)f.Get("h16")
TH1D * h17 = (TH1D*)f.Get("h17")
TCanvas * c1 = new TCanvas("c1", " ")
TGaxis * xaxis = new TGaxis(std::log10(minE),minY,std::log10(maxE),minY,minE,maxE,510,"G")
TLegend * leg = new TLegend(0.78,0.59,0.98,0.76)
TCanvas * c2 = new TCanvas("c2", " ")
TGaxis * xaxis1 = new TGaxis(std::log10(minE),minY1,std::log10(maxE),minY1,minE,maxE,510,"G")
TLegend * leg1 = new TLegend(0.78,0.59,0.98,0.76)
Function Documentation
leg AddEntry (h8 , "to 2 gammas" , "l")
leg AddEntry (h7 , "to MuPair" , "l")
leg AddEntry (h9 , "to Hadrons" , "l")
leg1 AddEntry (h15 , "to 2 gammas" , "l")
leg1 AddEntry (h14 , "to MuPair" , "l")
leg1 AddEntry (h16 , "to Hadrons" , "l")
leg1 AddEntry (h12 , "Bremsstrahlung" , "l")
leg1 AddEntry (h13 , "Ionization" , "l")
c1 cd ()
h7 Draw ("HIST")
h8 Draw ("HIST SAME")
h11 Draw ("HIST P SAME")
xaxis Draw ()
TFile f ("testem6_0.root")
h7 GetXaxis () -> SetLimits(std::log10(minE), std::log10(maxE))
h7 GetYaxis () -> SetTitle("microbarn")
h7 SetLineColor (kRed)
h9 SetLineColor (kBlue)
h12 SetLineColor (6)
h13 SetLineColor (kGreen)
gPad SetLogy ()
h11 SetMarkerColor (kRed)
h10 SetMarkerStyle (22)
h7 SetMaximum (maxY)
h15 SetMaximum (maxY1)
h7 SetMinimum (minY)
h15 SetMinimum (minY1)
gStyle SetOptStat (0)
h7 SetTitle ("Comparison of e+ Annihilation Processes(totcrsPerAtom)")
xaxis1 SetTitle ("GeV")
h15 SetTitle ("Comparison of EM Processes(totcrsPerVolume)")
Variable Documentation
TCanvas* c1 = new TCanvas("c1", " ")
Definition at line 38 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 38 of file plot_hist.C
TCanvas* c2 = new TCanvas("c2", " ")
Definition at line 75 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 75 of file plot_hist.C
Referenced by __example_6.f__(), __example_7.f__(), __example_8.f__(), G4ExtrudedSolid::AddGeneralPolygonFacets(), airy1(), airy1d(), airy2(), airy2d(), kdfinder::angle_between_vectors(), boundParamResolution(), G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4SPSEneDistribution::CalculateBbodySpectrum(), G4VLongitudinalStringDecay::CalculateHadronTimePosition(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4BetheHeitlerModel::ComputeCrossSectionPerAtom(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4JTPolynomialSolver::ComputeNewEstimate(), G4PairProductionRelModel::ComputeParametrizedXSectionPerAtom(), G4INCL::CoulombNonRelativistic::distortOut(), G4INCL::PiNToEtaChannel::fillFinalState(), FitNewton::NewtonMinimizerGradHessian::findSaddlePoint(), G4PolyhedraSide::G4PolyhedraSide(), gauss1(), gauss2(), gauss3(), gauss4(), CLHEP::RandGauss::get(), G4VXTRenergyLoss::GetComptonPerAtom(), G4NuclNuclDiffuseElastic::GetCoulombIntegralXsc(), G4DiffuseElastic::GetCoulombIntegralXsc(), TabulatedField3D::GetFieldValue(), EMField::GetFieldValue(), G4CrystalUnitCell::GetIntCosAng(), G4CrystalUnitCell::GetIntSp2(), G4CrystalUnitCell::GetRecIntSp2(), AnnularFieldSim::GetStepDistortion(), G4Abla::guet(), FitNewton::NewtonMinimizerGradHessian::minimize(), perigeeParamResolution(), plot(), pyeig4(), pygau2(), pygaus(), pyhiscat(), pyrvch(), pyrvne(), pyscat(), pysghf(), G4NuclearRadii::RadiusECS(), G4InitXscPAI::RePartDielectricConst(), G4PAIySection::RePartDielectricConst(), G4PAIxSection::RePartDielectricConst(), CLHEP::RandGauss::restoreDistState(), CLHEP::RandFlat::restoreDistState(), G4InitXscPAI::RutherfordIntegral(), G4PAIySection::RutherfordIntegral(), G4PAIxSection::RutherfordIntegral(), G4hRDEnergyLoss::SetStepFunction(), G4RDVeLowEnergyLoss::SetStepFunction(), G4BetaDecayCorrections::ShapeFactor(), G4RKG3_Stepper::StepNoErr(), G4DormandPrinceRK56::Stepper(), and streqci().
TH1D* h10 = (TH1D*)f.Get("h10")
Definition at line 23 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 23 of file plot_hist.C
TH1D* h11 = (TH1D*)f.Get("h11")
Definition at line 24 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 24 of file plot_hist.C
TH1D* h12 = (TH1D*)f.Get("h12")
Definition at line 27 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 27 of file plot_hist.C
Referenced by G4Physics2DVector::BicubicInterpolation(), and plotResults::main().
TH1D* h13 = (TH1D*)f.Get("h13")
Definition at line 28 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 28 of file plot_hist.C
Referenced by G4Physics2DVector::BicubicInterpolation().
TH1D* h14 = (TH1D*)f.Get("h14")
Definition at line 29 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 29 of file plot_hist.C
TH1D* h15 = (TH1D*)f.Get("h15")
Definition at line 30 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 30 of file plot_hist.C
TH1D* h16 = (TH1D*)f.Get("h16")
Definition at line 31 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 31 of file plot_hist.C
TH1D* h17 = (TH1D*)f.Get("h17")
Definition at line 34 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 34 of file plot_hist.C
TH1D* h7 = (TH1D*)f.Get("h7")
Definition at line 20 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 20 of file plot_hist.C
Referenced by plotResults::main().
TH1D* h8 = (TH1D*)f.Get("h8")
Definition at line 21 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 21 of file plot_hist.C
Referenced by plotResults::main().
TH1D* h9 = (TH1D*)f.Get("h9")
Definition at line 22 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 22 of file plot_hist.C
Referenced by plotResults::main().
TLegend* leg = new TLegend(0.78,0.59,0.98,0.76)
Definition at line 67 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 67 of file plot_hist.C
TLegend* leg1 = new TLegend(0.78,0.59,0.98,0.76)
Definition at line 105 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 105 of file plot_hist.C
Referenced by G4MIRDLeftLeg::Construct(), and G4MIRDRightLeg::Construct().
double maxE = 10000
Definition at line 8 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 8 of file plot_hist.C
Referenced by G4HadLeadBias::Bias(), G4CollisionComposite::BufferCrossSection(), G4LowEnergyIonisation::DeexciteAtom(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4RDVCrossSectionHandler::Initialise(), G4VCrossSectionHandler::Initialise(), G4PixeCrossSectionHandler::Initialise(), and G4ParticleHPNBodyPhaseSpace::Sample().
double maxY = 1e+2
Definition at line 10 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 10 of file plot_hist.C
Referenced by Acts::adjustBinUtility(), G4GenericTrap::ComputeBBox(), G4VSolid::EstimateCubicVolume(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnABoxBoundary(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), PDBlib::Load(), FW::RootBFieldWriter< bfield_t >::run(), and NeuronLoadDataFile::SingleNeuronSWCfile().
double maxY1 = 1
Definition at line 12 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 12 of file plot_hist.C
double minE = 40
Definition at line 7 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 7 of file plot_hist.C
Referenced by G4FermiFragmentsPoolVI::Initialise(), G4RDVCrossSectionHandler::Initialise(), G4VCrossSectionHandler::Initialise(), G4PixeCrossSectionHandler::Initialise(), and PHActsTrackProjection::updateSvtxTrack().
double minY = 1e-2
Definition at line 9 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 9 of file plot_hist.C
Referenced by Acts::adjustBinUtility(), G4GenericTrap::ComputeBBox(), G4VSolid::EstimateCubicVolume(), G4VSolid::EstimateSurfaceArea(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnABoxBoundary(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), TrentoPassiveProtonBeamLine::HadrontherapyRidgeFilter(), PDBlib::Load(), FW::RootBFieldWriter< bfield_t >::run(), and NeuronLoadDataFile::SingleNeuronSWCfile().
double minY1 = 1e-8
Definition at line 11 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 11 of file plot_hist.C
TGaxis* xaxis = new TGaxis(std::log10(minE),minY,std::log10(maxE),minY,minE,maxE,510,"G")
Definition at line 61 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 61 of file plot_hist.C
Referenced by G4TwistTubsSide::GetAreaCode(), G4P2Messenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4P1Messenger::SetNewValue(), G4H2Messenger::SetNewValue(), G4H1Messenger::SetNewValue(), and TpcSpaceChargeReconstructionHelper::split().
TGaxis* xaxis1 = new TGaxis(std::log10(minE),minY1,std::log10(maxE),minY1,minE,maxE,510,"G")
Definition at line 99 of file plot_hist.C.
View newest version in sPHENIX GitHub at line 99 of file plot_hist.C