ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Trd.cc File Reference
pyG4Trd.cc File Reference
#include <boost/python.hpp>
#include "G4Trd.hh"
Namespaces
namespace pyG4Trd
Functions
G4Trd * pyG4Trd::CreateTrd (const G4String &name, G4double pdx1, G4double pdx2, G4double pdy1, G4double pdy2, G4double pdz)
void export_G4Trd ()
Function Documentation
void export_G4Trd ()
Definition at line 54 of file pyG4Trd.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Trd.cc
References pyG4Trd::CreateTrd(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), init(), G4Trd::SetXHalfLength1(), G4Trd::SetXHalfLength2(), G4Trd::SetYHalfLength1(), G4Trd::SetYHalfLength2(), and G4Trd::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().