ECCE @ EIC Software: FFPrimaryGeneratorAction Class Reference
FFPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/hadronic/FissionFragment/include/FFPrimaryGeneratorAction.hh>
Public Member Functions
FFPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *event)
virtual ~FFPrimaryGeneratorAction ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Member Functions
G4ThreeVector GetNeutronSourceCenter (void)
Private Attributes
G4long fEventNumber
G4VPhysicalVolume * fH2OPhysical
G4VPhysicalVolume * fNeutronPhysical
G4Tubs * fNeutronSolid
G4ParticleGun *const fParticleGun
G4VPhysicalVolume * fTankPhysical
Detailed Description
Definition at line 55 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file FFPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
FFPrimaryGeneratorAction::FFPrimaryGeneratorAction ()
Definition at line 67 of file FFPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 67 of file FFPrimaryGeneratorAction.cc
References G4Neutron::Definition(), fParticleGun, MeV, G4ParticleGun::SetParticleDefinition(), and G4ParticleGun::SetParticleEnergy().
FFPrimaryGeneratorAction::~FFPrimaryGeneratorAction () virtual
Definition at line 199 of file FFPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 199 of file FFPrimaryGeneratorAction.cc
References fParticleGun.
Member Function Documentation
void FFPrimaryGeneratorAction::GeneratePrimaries (G4Event * event) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 84 of file FFPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 84 of file FFPrimaryGeneratorAction.cc
References deg, fEventNumber, fNeutronSolid, fParticleGun, G4cout, G4endl, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), GetNeutronSourceCenter(), G4Tubs::GetOuterRadius(), G4Tubs::GetZHalfLength(), radius, G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), CLHEP::Hep3Vector::setRThetaPhi(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and z.
G4ThreeVector FFPrimaryGeneratorAction::GetNeutronSourceCenter (void) private
Definition at line 123 of file FFPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 123 of file FFPrimaryGeneratorAction.cc
References EventMustBeAborted, fH2OPhysical, fNeutronPhysical, fNeutronSolid, fTankPhysical, G4Exception(), G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetSolid(), G4VPhysicalVolume::GetTranslation(), G4LogicalVolumeStore::GetVolume(), and G4PhysicalVolumeStore::GetVolume().
Referenced by GeneratePrimaries().
Member Data Documentation
G4long FFPrimaryGeneratorAction::fEventNumber private
Definition at line 71 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file FFPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4VPhysicalVolume* FFPrimaryGeneratorAction::fH2OPhysical private
Definition at line 73 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file FFPrimaryGeneratorAction.hh
Referenced by GetNeutronSourceCenter().
G4VPhysicalVolume* FFPrimaryGeneratorAction::fNeutronPhysical private
Definition at line 74 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 74 of file FFPrimaryGeneratorAction.hh
Referenced by GetNeutronSourceCenter().
G4Tubs* FFPrimaryGeneratorAction::fNeutronSolid private
Definition at line 75 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 75 of file FFPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and GetNeutronSourceCenter().
G4ParticleGun* const FFPrimaryGeneratorAction::fParticleGun private
Definition at line 76 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 76 of file FFPrimaryGeneratorAction.hh
Referenced by FFPrimaryGeneratorAction(), GeneratePrimaries(), and ~FFPrimaryGeneratorAction().
G4VPhysicalVolume* FFPrimaryGeneratorAction::fTankPhysical private
Definition at line 77 of file FFPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file FFPrimaryGeneratorAction.hh
Referenced by GetNeutronSourceCenter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/hadronic/FissionFragment/include/FFPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/FissionFragment/src/FFPrimaryGeneratorAction.cc