ECCE @ EIC Software: G4DNAMoleculeEncounterStepper Class Reference
G4DNAMoleculeEncounterStepper Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAMoleculeEncounterStepper.hh>
Classes
class Utils
Public Member Functions
G4DNAMoleculeEncounterStepper ()
virtual ~G4DNAMoleculeEncounterStepper ()
G4DNAMoleculeEncounterStepper (const G4DNAMoleculeEncounterStepper &)=delete
G4DNAMoleculeEncounterStepper & operator= (const G4DNAMoleculeEncounterStepper &)=delete
virtual void Prepare ()
virtual G4double CalculateStep (const G4Track &, const G4double &)
void SetReactionModel (G4VDNAReactionModel *)
G4VDNAReactionModel * GetReactionModel ()
void SetVerbose (int)
Public Member Functions inherited from G4VITTimeStepComputer
G4VITTimeStepComputer ()
virtual ~G4VITTimeStepComputer ()
G4VITTimeStepComputer (const G4VITTimeStepComputer &)
G4VITTimeStepComputer & operator= (const G4VITTimeStepComputer &other)
virtual void Initialize ()
G4TrackVectorHandle GetReactants ()
virtual void ResetReactants ()
G4double GetSampledMinTimeStep ()
void SetReactionTable (const G4ITReactionTable *)
const G4ITReactionTable * GetReactionTable ()
Private Member Functions
void InitializeForNewTrack ()
void CheckAndRecordResults (const Utils &, G4KDTreeResultHandle &)
Private Attributes
G4bool fHasAlreadyReachedNullTime
const
G4DNAMolecularReactionTable *& fMolecularReactionTable
G4VDNAReactionModel * fReactionModel
G4int fVerbose
Additional Inherited Members
Static Public Member Functions inherited from G4VITTimeStepComputer
static void SetTimes (const G4double &, const G4double &)
Protected Attributes inherited from G4VITTimeStepComputer
G4double fSampledMinTimeStep
G4TrackVectorHandle fReactants
const G4ITReactionTable * fpReactionTable
Static Protected Attributes inherited from G4VITTimeStepComputer
static G4ThreadLocal G4double fCurrentGlobalTime = -1
static G4ThreadLocal G4double fUserMinTimeStep = -1
Detailed Description
Given a molecule G4DNAMoleculeEncounterStepper will calculate for its possible reactants what will be the minimum encounter time and the associated molecules.*
This model includes dynamical time steps as explained in "Computer-Aided Stochastic Modeling of the Radiolysis of Liquid Water", V. Michalik, M. Begusová, E. A. Bigildeev, Radiation Research, Vol. 149, No. 3 (Mar., 1998), pp. 224-236
Definition at line 68 of file G4DNAMoleculeEncounterStepper.hh.
View newest version in sPHENIX GitHub at line 68 of file G4DNAMoleculeEncounterStepper.hh
Constructor & Destructor Documentation
G4DNAMoleculeEncounterStepper::G4DNAMoleculeEncounterStepper ()
Definition at line 68 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 68 of file G4DNAMoleculeEncounterStepper.cc
G4DNAMoleculeEncounterStepper::~G4DNAMoleculeEncounterStepper () virtual default
G4DNAMoleculeEncounterStepper::G4DNAMoleculeEncounterStepper (const G4DNAMoleculeEncounterStepper &) delete
Member Function Documentation
G4double G4DNAMoleculeEncounterStepper::CalculateStep (const G4Track & trackA, const G4double & userMinTimeStep) virtual
Implements G4VITTimeStepComputer.
Definition at line 119 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 119 of file G4DNAMoleculeEncounterStepper.cc
References G4DNAMolecularReactionTable::CanReactWith(), CheckAndRecordResults(), DBL_MAX, G4DNAMoleculeEncounterStepper::Utils::fConstant, fHasAlreadyReachedNullTime, fMolecularReactionTable, G4VITTimeStepComputer::fReactants, fReactionModel, G4VITTimeStepComputer::fSampledMinTimeStep, G4VITTimeStepComputer::fUserMinTimeStep, fVerbose, G4BestUnit, G4cout, G4endl, GetMolecule(), G4Molecule::GetName(), G4VDNAReactionModel::GetReactionRadius(), G4Track::GetTrackID(), G4VDNAReactionModel::Initialise(), InitializeForNewTrack(), G4ITFinder< T >::Instance(), it, r, Acts::IntegrationTest::R, and r2.
void G4DNAMoleculeEncounterStepper::CheckAndRecordResults (const Utils & utils, G4KDTreeResultHandle & results) private
Definition at line 311 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 311 of file G4DNAMoleculeEncounterStepper.cc
References fAlive, FatalErrorInArgument, G4DNAMoleculeEncounterStepper::Utils::fpMoleculeA, G4DNAMoleculeEncounterStepper::Utils::fpMoleculeB, G4DNAMoleculeEncounterStepper::Utils::fpTrackA, G4VITTimeStepComputer::fReactants, fVerbose, G4BestUnit, G4cout, G4endl, G4Exception(), G4Track::GetGlobalTime(), G4Molecule::GetName(), G4MolecularConfiguration::GetName(), G4Track::GetPosition(), G4IT::GetTrack(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), and r2.
Referenced by CalculateStep().
G4VDNAReactionModel * G4DNAMoleculeEncounterStepper::GetReactionModel ()
Definition at line 427 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 427 of file G4DNAMoleculeEncounterStepper.cc
References fReactionModel.
void G4DNAMoleculeEncounterStepper::InitializeForNewTrack () private
Definition at line 101 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 101 of file G4DNAMoleculeEncounterStepper.cc
References DBL_MAX, fHasAlreadyReachedNullTime, G4VITTimeStepComputer::fReactants, and G4VITTimeStepComputer::fSampledMinTimeStep.
Referenced by CalculateStep().
G4DNAMoleculeEncounterStepper& G4DNAMoleculeEncounterStepper::operator= (const G4DNAMoleculeEncounterStepper &) delete
void G4DNAMoleculeEncounterStepper::Prepare () virtual
Reimplemented from G4VITTimeStepComputer.
Definition at line 79 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 79 of file G4DNAMoleculeEncounterStepper.cc
References G4cout, G4endl, G4ITFinder< T >::Instance(), G4MemStat::MemoryUsage(), G4VITTimeStepComputer::Prepare(), and G4ITFinder< T >::UpdatePositionMap().
void G4DNAMoleculeEncounterStepper::SetReactionModel (G4VDNAReactionModel * pReactionModel)
Definition at line 422 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 422 of file G4DNAMoleculeEncounterStepper.cc
References fReactionModel.
void G4DNAMoleculeEncounterStepper::SetVerbose (int flag)
Definition at line 432 of file G4DNAMoleculeEncounterStepper.cc.
View newest version in sPHENIX GitHub at line 432 of file G4DNAMoleculeEncounterStepper.cc
References fVerbose.
Member Data Documentation
G4bool G4DNAMoleculeEncounterStepper::fHasAlreadyReachedNullTime private
Definition at line 96 of file G4DNAMoleculeEncounterStepper.hh.
View newest version in sPHENIX GitHub at line 96 of file G4DNAMoleculeEncounterStepper.hh
Referenced by CalculateStep(), and InitializeForNewTrack().
const G4DNAMolecularReactionTable*& G4DNAMoleculeEncounterStepper::fMolecularReactionTable private
Definition at line 98 of file G4DNAMoleculeEncounterStepper.hh.
View newest version in sPHENIX GitHub at line 98 of file G4DNAMoleculeEncounterStepper.hh
Referenced by CalculateStep().
G4VDNAReactionModel* G4DNAMoleculeEncounterStepper::fReactionModel private
Definition at line 99 of file G4DNAMoleculeEncounterStepper.hh.
View newest version in sPHENIX GitHub at line 99 of file G4DNAMoleculeEncounterStepper.hh
Referenced by CalculateStep(), GetReactionModel(), and SetReactionModel().
G4int G4DNAMoleculeEncounterStepper::fVerbose private
Definition at line 100 of file G4DNAMoleculeEncounterStepper.hh.
View newest version in sPHENIX GitHub at line 100 of file G4DNAMoleculeEncounterStepper.hh
Referenced by CalculateStep(), CheckAndRecordResults(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAMoleculeEncounterStepper.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAMoleculeEncounterStepper.cc