ECCE @ EIC Software: G4RPGPiPlusInelastic Class Reference
G4RPGPiPlusInelastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGPiPlusInelastic.hh>
Public Member Functions
G4RPGPiPlusInelastic ()
~G4RPGPiPlusInelastic ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
Public Member Functions inherited from G4RPGPionInelastic
G4RPGPionInelastic (const G4String &modelName="RPGPionInelastic")
~G4RPGPionInelastic ()
Public Member Functions inherited from G4RPGInelastic
G4RPGInelastic (const G4String &modelName="RPGInelastic")
virtual ~G4RPGInelastic ()
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
void InitialCollision (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged, G4bool &targetHasChanged)
Additional Inherited Members
Protected Types inherited from G4RPGInelastic
enum {
pi0, pip, pim, kp,
km, k0, k0b, pro,
neu, lam, sp, s0,
sm, xi0, xim, om,
ap, an
}
Protected Member Functions inherited from G4RPGPionInelastic
G4int GetMultiplicityT12 (G4double KE) const
G4int GetMultiplicityT32 (G4double KE) const
std::vector< G4int > GetFSPartTypesForT32 (G4int mult, G4double KE, G4int tindex) const
std::vector< G4int > GetFSPartTypesForT12 (G4int mult, G4double KE, G4int tindex) const
std::vector< G4int > GetFSPartTypesForPipP (G4int mult, G4double KE) const
std::vector< G4int > GetFSPartTypesForPimN (G4int mult, G4double KE) const
std::vector< G4int > GetFSPartTypesForPipN (G4int mult, G4double KE) const
std::vector< G4int > GetFSPartTypesForPimP (G4int mult, G4double KE) const
Protected Attributes inherited from G4RPGInelastic
G4RPGFragmentation fragmentation
G4RPGTwoCluster twoCluster
G4RPGPionSuppression pionSuppression
G4RPGStrangeProduction strangeProduction
G4RPGTwoBody twoBody
G4ParticleDefinition * particleDef [18]
Static Protected Attributes inherited from G4RPGPionInelastic
static const G4int pipPindex [8][2]
static const G4int pimPindex [8][2]
static const G4int T32_2bfs [2][2][2]
static const G4int T32_3bfs [2][7][3]
static const G4int T32_4bfs [2][15][4]
static const G4int T32_5bfs [2][24][5]
static const G4int T32_6bfs [2][5][6]
static const G4int T32_7bfs [2][6][7]
static const G4int T32_8bfs [2][7][8]
static const G4int T32_9bfs [2][8][9]
static const G4int T12_2bfs [2][5][2]
static const G4int T12_3bfs [2][13][3]
static const G4int T12_4bfs [2][22][4]
static const G4int T12_5bfs [2][31][5]
static const G4int T12_6bfs [2][6][6]
static const G4int T12_7bfs [2][7][7]
static const G4int T12_8bfs [2][8][8]
static const G4int T12_9bfs [2][9][9]
static G4ThreadLocal G4double pipPtot [30]
static G4ThreadLocal G4double pimPtot [30]
static G4ThreadLocal G4double t12_dSigma_dMult [8][30]
static G4ThreadLocal G4double t32_dSigma_dMult [8][30]
static const G4float pipPCrossSections [74][30]
static const G4float pimPCrossSections [101][30]
Detailed Description
Definition at line 40 of file G4RPGPiPlusInelastic.hh.
View newest version in sPHENIX GitHub at line 40 of file G4RPGPiPlusInelastic.hh
Constructor & Destructor Documentation
G4RPGPiPlusInelastic::G4RPGPiPlusInelastic () inline
Definition at line 44 of file G4RPGPiPlusInelastic.hh.
View newest version in sPHENIX GitHub at line 44 of file G4RPGPiPlusInelastic.hh
G4RPGPiPlusInelastic::~G4RPGPiPlusInelastic () inline
Definition at line 47 of file G4RPGPiPlusInelastic.hh.
View newest version in sPHENIX GitHub at line 47 of file G4RPGPiPlusInelastic.hh
Member Function Documentation
G4HadFinalState * G4RPGPiPlusInelastic::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 33 of file G4RPGPiPlusInelastic.cc.
View newest version in sPHENIX GitHub at line 33 of file G4RPGPiPlusInelastic.cc
References kdfinder::abs(), G4RPGInelastic::CalculateMomenta(), G4Nucleus::Cinema(), G4Nucleus::EvaporationEffects(), G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4ParticleDefinition::GetPDGMass(), InitialCollision(), G4FastVector< Type, N >::Initialize(), isAlive, momentum, G4InuclParticleNames::pp, G4Nucleus::ReturnTargetParticle(), G4HadFinalState::SetEnergyChange(), G4ReactionProduct::SetMomentum(), G4HadFinalState::SetMomentumChange(), G4ReactionProduct::SetSide(), G4HadFinalState::SetStatusChange(), G4RPGInelastic::SetUpChange(), G4HadronicInteraction::theParticleChange, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
void G4RPGPiPlusInelastic::InitialCollision (G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4bool & incidentHasChanged, G4bool & targetHasChanged) private
Definition at line 122 of file G4RPGPiPlusInelastic.cc.
View newest version in sPHENIX GitHub at line 122 of file G4RPGPiPlusInelastic.cc
References G4RPGInelastic::CheckQnums(), G4UniformRand, G4ReactionProduct::GetDefinition(), G4RPGPionInelastic::GetFSPartTypesForPipN(), G4RPGPionInelastic::GetFSPartTypesForPipP(), G4ReactionProduct::GetKineticEnergy(), G4RPGPionInelastic::GetMultiplicityT12(), G4RPGPionInelastic::GetMultiplicityT32(), GeV, G4RPGInelastic::neu, G4RPGInelastic::particleDef, G4RPGInelastic::pim, G4RPGInelastic::pip, G4RPGInelastic::pro, G4ReactionProduct::SetDefinition(), G4FastVector< Type, N >::SetElement(), G4ReactionProduct::SetMayBeKilled(), and G4ReactionProduct::SetSide().
Referenced by ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGPiPlusInelastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/src/G4RPGPiPlusInelastic.cc