ECCE @ EIC Software: G4VPolarizedCrossSection Class Reference
G4VPolarizedCrossSection Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4VPolarizedCrossSection.hh>
Public Member Functions
G4VPolarizedCrossSection ()
virtual ~G4VPolarizedCrossSection ()
virtual void Initialize (G4double, G4double, G4double, const G4StokesVector &p0, const G4StokesVector &p1, G4int flag=0)
virtual G4double XSection (const G4StokesVector &pol2, const G4StokesVector &pol3)=0
virtual G4double TotalXSection (G4double xmin, G4double xmax, G4double y, const G4StokesVector &pol0, const G4StokesVector &pol1)
virtual G4StokesVector GetPol2 ()
virtual G4StokesVector GetPol3 ()
G4double GetYmin ()
virtual G4double GetXmin (G4double y)
virtual G4double GetXmax (G4double y)
void SetMaterial (G4double A, G4double Z, G4double coul)
Protected Member Functions
void SetXmin (G4double xmin)
void SetXmax (G4double xmax)
void SetYmin (G4double ymin)
Protected Attributes
G4double fXmin
G4double fXmax
G4double fYmin
G4double theA
G4double theZ
G4double fCoul
Detailed Description
Definition at line 49 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VPolarizedCrossSection.hh
Constructor & Destructor Documentation
G4VPolarizedCrossSection::G4VPolarizedCrossSection ()
Definition at line 45 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VPolarizedCrossSection.cc
G4VPolarizedCrossSection::~G4VPolarizedCrossSection () virtual
Definition at line 50 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VPolarizedCrossSection.cc
Member Function Documentation
G4StokesVector G4VPolarizedCrossSection::GetPol2 () virtual
Reimplemented in G4PolarizedComptonCrossSection, G4PolarizedAnnihilationCrossSection, G4PolarizedBhabhaCrossSection, G4PolarizedMollerCrossSection, G4PolarizedBremsstrahlungCrossSection, G4PolarizedPEEffectCrossSection, and G4PolarizedPairProductionCrossSection.
Definition at line 61 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VPolarizedCrossSection.cc
References G4StokesVector::P1, G4StokesVector::P2, G4StokesVector::P3, XSection(), and G4StokesVector::ZERO.
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), and G4PolarizedMollerBhabhaModel::SampleSecondaries().
G4StokesVector G4VPolarizedCrossSection::GetPol3 () virtual
Reimplemented in G4PolarizedComptonCrossSection, G4PolarizedAnnihilationCrossSection, G4PolarizedBhabhaCrossSection, G4PolarizedMollerCrossSection, G4PolarizedBremsstrahlungCrossSection, G4PolarizedPEEffectCrossSection, and G4PolarizedPairProductionCrossSection.
Definition at line 72 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VPolarizedCrossSection.cc
References G4StokesVector::P1, G4StokesVector::P2, G4StokesVector::P3, XSection(), and G4StokesVector::ZERO.
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), and G4PolarizedMollerBhabhaModel::SampleSecondaries().
G4double G4VPolarizedCrossSection::GetXmax (G4double y) virtual
Reimplemented in G4PolarizedAnnihilationCrossSection.
Definition at line 89 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VPolarizedCrossSection.cc
References fXmax.
G4double G4VPolarizedCrossSection::GetXmin (G4double y) virtual
Reimplemented in G4PolarizedAnnihilationCrossSection.
Definition at line 83 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 83 of file G4VPolarizedCrossSection.cc
References fXmin.
G4double G4VPolarizedCrossSection::GetYmin () inline
Definition at line 70 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VPolarizedCrossSection.hh
References fYmin.
void G4VPolarizedCrossSection::Initialize (G4double , G4double , G4double , const G4StokesVector & p0, const G4StokesVector & p1, G4int flag = 0) virtual
Reimplemented in G4PolarizedComptonCrossSection, G4PolarizedAnnihilationCrossSection, G4PolarizedBremsstrahlungCrossSection, G4PolarizedMollerCrossSection, G4PolarizedBhabhaCrossSection, G4PolarizedPairProductionCrossSection, and G4PolarizedPEEffectCrossSection.
Definition at line 54 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VPolarizedCrossSection.cc
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), and G4PolarizedMollerBhabhaModel::SampleSecondaries().
void G4VPolarizedCrossSection::SetMaterial (G4double A, G4double Z, G4double coul) inline
Definition at line 80 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VPolarizedCrossSection.hh
References A(), fCoul, theA, theZ, and Z.
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), and G4PolarizedPEEffectModel::SampleSecondaries().
void G4VPolarizedCrossSection::SetXmax (G4double xmax) inline protected
Definition at line 85 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VPolarizedCrossSection.hh
References fXmax, and xmax.
Referenced by G4PolarizedMollerCrossSection::G4PolarizedMollerCrossSection(), and G4PolarizedBhabhaCrossSection::Initialize().
void G4VPolarizedCrossSection::SetXmin (G4double xmin) inline protected
Definition at line 84 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VPolarizedCrossSection.hh
References fXmin, and xmin.
void G4VPolarizedCrossSection::SetYmin (G4double ymin) inline protected
Definition at line 86 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VPolarizedCrossSection.hh
References fYmin, and ymin.
Referenced by G4PolarizedComptonCrossSection::G4PolarizedComptonCrossSection().
G4double G4VPolarizedCrossSection::TotalXSection (G4double xmin, G4double xmax, G4double y, const G4StokesVector & pol0, const G4StokesVector & pol1) virtual
Reimplemented in G4PolarizedComptonCrossSection, G4PolarizedAnnihilationCrossSection, G4PolarizedBhabhaCrossSection, and G4PolarizedMollerCrossSection.
Definition at line 144 of file G4VPolarizedCrossSection.cc.
View newest version in sPHENIX GitHub at line 144 of file G4VPolarizedCrossSection.cc
References G4cout, and G4endl.
virtual G4double G4VPolarizedCrossSection::XSection (const G4StokesVector & pol2, const G4StokesVector & pol3) pure virtual
Implemented in G4PolarizedComptonCrossSection, G4PolarizedAnnihilationCrossSection, G4PolarizedBremsstrahlungCrossSection, G4PolarizedMollerCrossSection, G4PolarizedBhabhaCrossSection, G4PolarizedPairProductionCrossSection, and G4PolarizedPEEffectCrossSection.
Referenced by GetPol2(), GetPol3(), and G4PolarizedMollerBhabhaModel::SampleSecondaries().
Member Data Documentation
G4double G4VPolarizedCrossSection::fCoul protected
Definition at line 92 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VPolarizedCrossSection.hh
Referenced by G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), and SetMaterial().
G4double G4VPolarizedCrossSection::fXmax protected
Definition at line 89 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VPolarizedCrossSection.hh
Referenced by GetXmax(), and SetXmax().
G4double G4VPolarizedCrossSection::fXmin protected
Definition at line 89 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VPolarizedCrossSection.hh
Referenced by GetXmin(), and SetXmin().
G4double G4VPolarizedCrossSection::fYmin protected
Definition at line 89 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VPolarizedCrossSection.hh
Referenced by GetYmin(), and SetYmin().
G4double G4VPolarizedCrossSection::theA protected
Definition at line 91 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VPolarizedCrossSection.hh
Referenced by SetMaterial().
G4double G4VPolarizedCrossSection::theZ protected
Definition at line 91 of file G4VPolarizedCrossSection.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VPolarizedCrossSection.hh
Referenced by G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), SetMaterial(), and G4PolarizedComptonCrossSection::TotalXSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4VPolarizedCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4VPolarizedCrossSection.cc