ECCE @ EIC Software: G4GDMLParameterisation Class Reference
G4GDMLParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLParameterisation.hh>
Classes
struct PARAMETER
Public Member Functions
G4int GetSize () const
void AddParameter (const PARAMETER &)
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
std::vector< PARAMETER > parameterList
Detailed Description
Definition at line 65 of file G4GDMLParameterisation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4GDMLParameterisation.hh
Member Function Documentation
void G4GDMLParameterisation::AddParameter (const PARAMETER & newParameter)
Definition at line 42 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 42 of file G4GDMLParameterisation.cc
References parameterList.
Referenced by G4GDMLReadParamvol::ParametersRead().
void G4GDMLParameterisation::ComputeDimensions (G4Box & box, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 55 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 55 of file G4GDMLParameterisation.cc
References parameterList, G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
void G4GDMLParameterisation::ComputeDimensions (G4Trd & trd, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 63 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GDMLParameterisation.cc
References parameterList, G4Trd::SetXHalfLength1(), G4Trd::SetXHalfLength2(), G4Trd::SetYHalfLength1(), G4Trd::SetYHalfLength2(), and G4Trd::SetZHalfLength().
void G4GDMLParameterisation::ComputeDimensions (G4Trap & trap, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 73 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 73 of file G4GDMLParameterisation.cc
References parameterList, and G4Trap::SetAllParameters().
void G4GDMLParameterisation::ComputeDimensions (G4Cons & cons, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 99 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 99 of file G4GDMLParameterisation.cc
References parameterList, G4Cons::SetDeltaPhiAngle(), G4Cons::SetInnerRadiusMinusZ(), G4Cons::SetInnerRadiusPlusZ(), G4Cons::SetOuterRadiusMinusZ(), G4Cons::SetOuterRadiusPlusZ(), G4Cons::SetStartPhiAngle(), and G4Cons::SetZHalfLength().
void G4GDMLParameterisation::ComputeDimensions (G4Sphere & sphere, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 111 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 111 of file G4GDMLParameterisation.cc
References parameterList, G4Sphere::SetDeltaPhiAngle(), G4Sphere::SetDeltaThetaAngle(), G4Sphere::SetInnerRadius(), G4Sphere::SetOuterRadius(), G4Sphere::SetStartPhiAngle(), and G4Sphere::SetStartThetaAngle().
void G4GDMLParameterisation::ComputeDimensions (G4Orb & orb, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 122 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 122 of file G4GDMLParameterisation.cc
References parameterList, and G4Orb::SetRadius().
void G4GDMLParameterisation::ComputeDimensions (G4Ellipsoid & ellipsoid, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 128 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 128 of file G4GDMLParameterisation.cc
References parameterList, G4Ellipsoid::SetSemiAxis(), and G4Ellipsoid::SetZCuts().
void G4GDMLParameterisation::ComputeDimensions (G4Torus & torus, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 138 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 138 of file G4GDMLParameterisation.cc
References parameterList, and G4Torus::SetAllParameters().
void G4GDMLParameterisation::ComputeDimensions (G4Para & para, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 148 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 148 of file G4GDMLParameterisation.cc
References parameterList, G4Para::SetAlpha(), G4Para::SetTanAlpha(), G4Para::SetThetaAndPhi(), G4Para::SetXHalfLength(), G4Para::SetYHalfLength(), and G4Para::SetZHalfLength().
void G4GDMLParameterisation::ComputeDimensions (G4Hype & hype, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 159 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 159 of file G4GDMLParameterisation.cc
References parameterList, G4Hype::SetInnerRadius(), G4Hype::SetInnerStereo(), G4Hype::SetOuterRadius(), G4Hype::SetOuterStereo(), and G4Hype::SetZHalfLength().
void G4GDMLParameterisation::ComputeDimensions (G4Tubs & tubs, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 89 of file G4GDMLParameterisation.cc
References parameterList, G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
void G4GDMLParameterisation::ComputeDimensions (G4Polycone & pcone, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 169 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 169 of file G4GDMLParameterisation.cc
References G4Polycone::GetOriginalParameters(), G4PolyconeHistorical::Num_z_planes, G4PolyconeHistorical::Opening_angle, parameterList, G4Polycone::Reset(), G4PolyconeHistorical::Rmax, G4PolyconeHistorical::Rmin, G4Polycone::SetOriginalParameters(), G4PolyconeHistorical::Start_angle, and G4PolyconeHistorical::Z_values.
void G4GDMLParameterisation::ComputeDimensions (G4Polyhedra & polyhedra, const G4int index, const G4VPhysicalVolume *) const private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 191 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 191 of file G4GDMLParameterisation.cc
References G4Polyhedra::GetOriginalParameters(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, parameterList, G4Polyhedra::Reset(), G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4Polyhedra::SetOriginalParameters(), G4PolyhedraHistorical::Start_angle, and G4PolyhedraHistorical::Z_values.
void G4GDMLParameterisation::ComputeTransformation (const G4int index, G4VPhysicalVolume * physvol) const private virtual
Implements G4VPVParameterisation.
Definition at line 48 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GDMLParameterisation.cc
References parameterList, G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
G4int G4GDMLParameterisation::GetSize () const
Definition at line 37 of file G4GDMLParameterisation.cc.
View newest version in sPHENIX GitHub at line 37 of file G4GDMLParameterisation.cc
References parameterList.
Referenced by G4GDMLReadParamvol::ParamvolRead().
Member Data Documentation
std::vector<PARAMETER> G4GDMLParameterisation::parameterList private
Definition at line 101 of file G4GDMLParameterisation.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GDMLParameterisation.hh
Referenced by AddParameter(), ComputeDimensions(), ComputeTransformation(), and GetSize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLParameterisation.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLParameterisation.cc