ECCE @ EIC Software: G4TwistedTrap Class Reference
G4TwistedTrap Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistedTrap.hh>
Public Member Functions
G4TwistedTrap (const G4String &pName, G4double pPhiTwist, G4double pDx1, G4double pDx2, G4double pDy, G4double pDz)
G4TwistedTrap (const G4String &pName, G4double pPhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph)
virtual ~G4TwistedTrap ()
G4double GetY1HalfLength () const
G4double GetX1HalfLength () const
G4double GetX2HalfLength () const
G4double GetY2HalfLength () const
G4double GetX3HalfLength () const
G4double GetX4HalfLength () const
G4double GetZHalfLength () const
G4double GetPhiTwist () const
G4double GetTiltAngleAlpha () const
G4double GetPolarAngleTheta () const
G4double GetAzimuthalAnglePhi () const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4TwistedTrap (__void__ &)
G4TwistedTrap (const G4TwistedTrap &rhs)
G4TwistedTrap & operator= (const G4TwistedTrap &rhs)
Public Member Functions inherited from G4VTwistedFaceted
G4VTwistedFaceted (const G4String &pname, G4double PhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph)
virtual ~G4VTwistedFaceted ()
virtual void ComputeDimensions (G4VPVParameterisation *, const G4int, const G4VPhysicalVolume *)
virtual void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
virtual G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
virtual G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
virtual G4double DistanceToIn (const G4ThreeVector &p) const
virtual G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcnorm=false, G4bool *validnorm=nullptr, G4ThreeVector *n=nullptr) const
virtual G4double DistanceToOut (const G4ThreeVector &p) const
virtual EInside Inside (const G4ThreeVector &p) const
virtual G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4ThreeVector GetPointOnSurface () const
G4ThreeVector GetPointInSolid (G4double z) const
virtual G4double GetCubicVolume ()
virtual G4double GetSurfaceArea ()
virtual void DescribeYourselfTo (G4VGraphicsScene &scene) const
virtual G4Polyhedron * CreatePolyhedron () const
virtual G4Polyhedron * GetPolyhedron () const
G4double GetTwistAngle () const
G4double GetDx1 () const
G4double GetDx2 () const
G4double GetDx3 () const
G4double GetDx4 () const
G4double GetDy1 () const
G4double GetDy2 () const
G4double GetDz () const
G4double GetPhi () const
G4double GetTheta () const
G4double GetAlpha () const
G4double Xcoef (G4double u, G4double phi, G4double ftg) const
G4double GetValueA (G4double phi) const
G4double GetValueB (G4double phi) const
G4double GetValueD (G4double phi) const
virtual G4VisExtent GetExtent () const
G4VTwistedFaceted (__void__ &)
G4VTwistedFaceted (const G4VTwistedFaceted &rhs)
G4VTwistedFaceted & operator= (const G4VTwistedFaceted &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4VTwistedFaceted
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 60 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 60 of file G4TwistedTrap.hh
Constructor & Destructor Documentation
G4TwistedTrap::G4TwistedTrap (const G4String & pName, G4double pPhiTwist, G4double pDx1, G4double pDx2, G4double pDy, G4double pDz)
Definition at line 38 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 38 of file G4TwistedTrap.cc
Referenced by Clone().
G4TwistedTrap::G4TwistedTrap (const G4String & pName, G4double pPhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph)
Definition at line 50 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 50 of file G4TwistedTrap.cc
G4TwistedTrap::~G4TwistedTrap () virtual
Definition at line 79 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 79 of file G4TwistedTrap.cc
G4TwistedTrap::G4TwistedTrap (__void__ & a)
Definition at line 71 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 71 of file G4TwistedTrap.cc
G4TwistedTrap::G4TwistedTrap (const G4TwistedTrap & rhs)
Definition at line 86 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 86 of file G4TwistedTrap.cc
References G4VTwistedFaceted::fpPolyhedron, and G4VTwistedFaceted::GetPolyhedron().
Member Function Documentation
G4VSolid * G4TwistedTrap::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 153 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 153 of file G4TwistedTrap.cc
References G4TwistedTrap().
G4double G4TwistedTrap::GetAzimuthalAnglePhi () const inline
Definition at line 100 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 100 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetPhi().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4GeometryType G4TwistedTrap::GetEntityType () const virtual
Reimplemented from G4VTwistedFaceted.
Definition at line 145 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 145 of file G4TwistedTrap.cc
G4double G4TwistedTrap::GetPhiTwist () const inline
Definition at line 97 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 97 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetTwistAngle().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetPolarAngleTheta () const inline
Definition at line 99 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 99 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetTheta().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetTiltAngleAlpha () const inline
Definition at line 98 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 98 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetAlpha().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetX1HalfLength () const inline
Definition at line 91 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 91 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDx1().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetX2HalfLength () const inline
Definition at line 92 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 92 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDx2().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetX3HalfLength () const inline
Definition at line 94 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 94 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDx3().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetX4HalfLength () const inline
Definition at line 95 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 95 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDx4().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetY1HalfLength () const inline
Definition at line 90 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 90 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDy1().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetY2HalfLength () const inline
Definition at line 93 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 93 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDy2().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4double G4TwistedTrap::GetZHalfLength () const inline
Definition at line 96 of file G4TwistedTrap.hh.
View newest version in sPHENIX GitHub at line 96 of file G4TwistedTrap.hh
References G4VTwistedFaceted::GetDz().
Referenced by G4tgbGeometryDumper::GetSolidParams(), StreamInfo(), PHG4GDMLWriteSolids::TwistedtrapWrite(), and G4GDMLWriteSolids::TwistedtrapWrite().
G4TwistedTrap & G4TwistedTrap::operator= (const G4TwistedTrap & rhs)
Definition at line 95 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 95 of file G4TwistedTrap.cc
References G4VTwistedFaceted::fpPolyhedron, G4VTwistedFaceted::GetPolyhedron(), and G4VTwistedFaceted::operator=().
std::ostream & G4TwistedTrap::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4VTwistedFaceted.
Definition at line 112 of file G4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 112 of file G4TwistedTrap.cc
References cm, degree, G4endl, GetAzimuthalAnglePhi(), G4VSolid::GetName(), GetPhiTwist(), GetPolarAngleTheta(), GetTiltAngleAlpha(), GetX1HalfLength(), GetX2HalfLength(), GetX3HalfLength(), GetX4HalfLength(), GetY1HalfLength(), GetY2HalfLength(), and GetZHalfLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistedTrap.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4TwistedTrap.cc