ECCE @ EIC Software: CLHEP::HepAxisAngle Class Reference
CLHEP::HepAxisAngle Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/AxisAngle.h>
Public Types
typedef double Scalar
Public Member Functions
HepAxisAngle ()
HepAxisAngle (const Hep3Vector axis, Scalar delta)
Hep3Vector getAxis () const
Hep3Vector axis () const
AA & setAxis (const Hep3Vector axis)
double getDelta () const
double delta () const
AA & setDelta (Scalar delta)
AA & set (const Hep3Vector axis, Scalar delta)
int compare (const AA &aa) const
bool operator== (const AA &aa) const
bool operator!= (const AA &aa) const
bool operator< (const AA &aa) const
bool operator<= (const AA &aa) const
bool operator> (const AA &aa) const
bool operator>= (const AA &aa) const
bool isNear (const AA &aa, Scalar epsilon=tolerance) const
double howNear (const AA &aa) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (Scalar tol)
Protected Types
typedef HepAxisAngle AA
Protected Member Functions
double distance (const HepAxisAngle &aa) const
Static Protected Attributes
static Scalar tolerance = Hep3Vector::ToleranceTicks * 1.0e-08
Private Attributes
Hep3Vector axis_
double delta_
Friends
std::ostream & operator<< (std::ostream &os, const AA &aa)
std::istream & operator>> (std::istream &is, AA &aa)
Detailed Description
Author
Definition at line 36 of file AxisAngle.h.
View newest version in sPHENIX GitHub at line 36 of file AxisAngle.h
Member Typedef Documentation
typedef HepAxisAngle CLHEP::HepAxisAngle::AA protected
Definition at line 42 of file AxisAngle.h.
View newest version in sPHENIX GitHub at line 42 of file AxisAngle.h
typedef double CLHEP::HepAxisAngle::Scalar
Definition at line 39 of file AxisAngle.h.
View newest version in sPHENIX GitHub at line 39 of file AxisAngle.h
Constructor & Destructor Documentation
CLHEP::HepAxisAngle::HepAxisAngle () inline
CLHEP::HepAxisAngle::HepAxisAngle (const Hep3Vector axis, Scalar delta) inline
Member Function Documentation
Hep3Vector CLHEP::HepAxisAngle::axis () const inline
Referenced by CLHEP::HepRotation::HepRotation(), CLHEP::operator<<(), and CLHEP::HepRotation::set().
int CLHEP::HepAxisAngle::compare (const AA & aa) const inline
double CLHEP::HepAxisAngle::delta () const inline
Referenced by CLHEP::HepRotation::HepRotation(), CLHEP::operator<<(), CLHEP::Hep3Vector::rotate(), CLHEP::HepRotation::set(), and CLHEP::ZMpvAxisAngleRep().
double CLHEP::HepAxisAngle::distance (const HepAxisAngle & aa) const protected
Definition at line 45 of file AxisAngle.cc.
View newest version in sPHENIX GitHub at line 45 of file AxisAngle.cc
References d, sum, and CLHEP::ZMpvAxisAngleRep().
Referenced by howNear(), and isNear().
Hep3Vector CLHEP::HepAxisAngle::getAxis () const inline
Referenced by CLHEP::Hep3Vector::rotate(), and CLHEP::ZMpvAxisAngleRep().
double CLHEP::HepAxisAngle::getDelta () const inline
static double CLHEP::HepAxisAngle::getTolerance () inline static
double CLHEP::HepAxisAngle::howNear (const AA & aa) const
Definition at line 71 of file AxisAngle.cc.
View newest version in sPHENIX GitHub at line 71 of file AxisAngle.cc
References distance().
bool CLHEP::HepAxisAngle::isNear (const AA & aa, Scalar epsilon = tolerance) const
Definition at line 64 of file AxisAngle.cc.
View newest version in sPHENIX GitHub at line 64 of file AxisAngle.cc
References distance(), and epsilon().
bool CLHEP::HepAxisAngle::operator!= (const AA & aa) const inline
bool CLHEP::HepAxisAngle::operator< (const AA & aa) const inline
bool CLHEP::HepAxisAngle::operator<= (const AA & aa) const inline
bool CLHEP::HepAxisAngle::operator== (const AA & aa) const inline
bool CLHEP::HepAxisAngle::operator> (const AA & aa) const inline
bool CLHEP::HepAxisAngle::operator>= (const AA & aa) const inline
AA& CLHEP::HepAxisAngle::set (const Hep3Vector axis, Scalar delta) inline
Referenced by CLHEP::operator>>().
AA& CLHEP::HepAxisAngle::setAxis (const Hep3Vector axis) inline
AA& CLHEP::HepAxisAngle::setDelta (Scalar delta) inline
static double CLHEP::HepAxisAngle::setTolerance (Scalar tol) inline static
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const AA & aa) friend
std::istream& operator>> (std::istream & is, AA & aa) friend
Member Data Documentation
Hep3Vector CLHEP::HepAxisAngle::axis_ private
Definition at line 96 of file AxisAngle.h.
View newest version in sPHENIX GitHub at line 96 of file AxisAngle.h
double CLHEP::HepAxisAngle::delta_ private
Definition at line 97 of file AxisAngle.h.
View newest version in sPHENIX GitHub at line 97 of file AxisAngle.h
double CLHEP::HepAxisAngle::tolerance = Hep3Vector::ToleranceTicks * 1.0e-08 static protected
Definition at line 43 of file AxisAngle.h.
View newest version in sPHENIX GitHub at line 43 of file AxisAngle.h
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/AxisAngle.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/AxisAngle.cc