ECCE @ EIC Software: G4LivermoreGammaConversionModelRC Class Reference
G4LivermoreGammaConversionModelRC Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreGammaConversionModelRC.hh>
Public Member Functions
G4LivermoreGammaConversionModelRC (const G4ParticleDefinition *p=0, const G4String &nam="LivermoreGammaConversionRC_1")
virtual ~G4LivermoreGammaConversionModelRC ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0, G4double cut=0, G4double emax=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void ReadData (size_t Z, const char *path=0)
G4double ScreenFunction1 (G4double screenVariable)
G4double ScreenFunction2 (G4double screenVariable)
G4LivermoreGammaConversionModelRC & operator= (const G4LivermoreGammaConversionModelRC &right)
G4LivermoreGammaConversionModelRC (const G4LivermoreGammaConversionModelRC &)
G4double fbeta (G4double x)
G4double Dilog (G4double x)
Private Attributes
G4ParticleChangeForGamma * fParticleChange
G4double lowEnergyLimit
G4bool isInitialised
G4int verboseLevel
G4double smallEnergy
Static Private Attributes
static G4int maxZ = 99
static G4LPhysicsFreeVector * data [100] = {nullptr}
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 39 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 39 of file G4LivermoreGammaConversionModelRC.hh
Constructor & Destructor Documentation
G4LivermoreGammaConversionModelRC::G4LivermoreGammaConversionModelRC (const G4ParticleDefinition * p = 0, const G4String & nam = "LivermoreGammaConversionRC_1")
Definition at line 51 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 51 of file G4LivermoreGammaConversionModelRC.cc
References source.hepunit::electron_mass_c2, G4cout, and G4endl.
G4LivermoreGammaConversionModelRC::~G4LivermoreGammaConversionModelRC () virtual
Definition at line 72 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 72 of file G4LivermoreGammaConversionModelRC.cc
References maxZ.
G4LivermoreGammaConversionModelRC::G4LivermoreGammaConversionModelRC (const G4LivermoreGammaConversionModelRC &) private
Member Function Documentation
G4double G4LivermoreGammaConversionModelRC::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0, G4double cut = 0, G4double emax = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 219 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 219 of file G4LivermoreGammaConversionModelRC.cc
References G4cout, G4endl, G4PhysicsVector::GetVectorLength(), maxZ, MeV, n, and G4PhysicsVector::Value().
G4double G4LivermoreGammaConversionModelRC::Dilog (G4double x) private
Definition at line 580 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 580 of file G4LivermoreGammaConversionModelRC.cc
References y.
G4double G4LivermoreGammaConversionModelRC::fbeta (G4double x) private
Definition at line 558 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 558 of file G4LivermoreGammaConversionModelRC.cc
References d, Acts::VectorHelpers::eta(), and x.
void G4LivermoreGammaConversionModelRC::Initialise (const G4ParticleDefinition * particle, const G4DataVector & cuts) virtual
Implements G4VEmModel.
Definition at line 86 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 86 of file G4LivermoreGammaConversionModelRC.cc
References G4cout, G4endl, G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), GeV, material(), maxZ, MeV, and Z.
void G4LivermoreGammaConversionModelRC::InitialiseForElement (const G4ParticleDefinition * , G4int Z) virtual
Reimplemented from G4VEmModel.
Definition at line 604 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 604 of file G4LivermoreGammaConversionModelRC.cc
References G4TemplateAutoLock< _Mutex_t >::unlock().
void G4LivermoreGammaConversionModelRC::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) virtual
Reimplemented from G4VEmModel.
Definition at line 139 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 139 of file G4LivermoreGammaConversionModelRC.cc
References G4VEmModel::GetElementSelectors().
G4double G4LivermoreGammaConversionModelRC::MinPrimaryEnergy (const G4Material * , const G4ParticleDefinition * , G4double) virtual
Reimplemented from G4VEmModel.
Definition at line 148 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 148 of file G4LivermoreGammaConversionModelRC.cc
G4LivermoreGammaConversionModelRC& G4LivermoreGammaConversionModelRC::operator= (const G4LivermoreGammaConversionModelRC & right) private
void G4LivermoreGammaConversionModelRC::ReadData (size_t Z, const char * path = 0) private
Definition at line 157 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 157 of file G4LivermoreGammaConversionModelRC.cc
References FatalException, fin, G4cout, G4endl, G4Exception(), and Z.
void G4LivermoreGammaConversionModelRC::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicGamma, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 268 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 268 of file G4LivermoreGammaConversionModelRC.cc
References a, b, bb, c, d, e, G4Electron::Electron(), source.hepunit::electron_mass_c2, epsilon(), f, ff, fStopAndKill, G4cout, G4endl, G4Exp(), G4Log(), G4UniformRand, G4Gamma::Gamma(), G4DynamicParticle::GetDefinition(), G4Element::GetfCoulomb(), G4Element::GetIonisation(), G4DynamicParticle::GetKineticEnergy(), G4IonisParamElm::GetlogZ3(), G4DynamicParticle::GetMomentumDirection(), G4IonisParamElm::GetZ3(), Acts::UnitConstants::h, hh, k, max, MeV, min, particle, phi, G4Positron::Positron(), r1, r2, CLHEP::Hep3Vector::rotateUz(), twopi, and Acts::UnitConstants::u.
G4double G4LivermoreGammaConversionModelRC::ScreenFunction1 (G4double screenVariable) private
Definition at line 526 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 526 of file G4LivermoreGammaConversionModelRC.cc
References G4Log().
G4double G4LivermoreGammaConversionModelRC::ScreenFunction2 (G4double screenVariable) private
Definition at line 542 of file G4LivermoreGammaConversionModelRC.cc.
View newest version in sPHENIX GitHub at line 542 of file G4LivermoreGammaConversionModelRC.cc
References G4Log().
Member Data Documentation
G4LPhysicsFreeVector * G4LivermoreGammaConversionModelRC::data = {nullptr} static private
Definition at line 96 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LivermoreGammaConversionModelRC.hh
G4ParticleChangeForGamma* G4LivermoreGammaConversionModelRC::fParticleChange private
Definition at line 76 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 76 of file G4LivermoreGammaConversionModelRC.hh
G4bool G4LivermoreGammaConversionModelRC::isInitialised private
Definition at line 80 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 80 of file G4LivermoreGammaConversionModelRC.hh
G4double G4LivermoreGammaConversionModelRC::lowEnergyLimit private
Definition at line 78 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 78 of file G4LivermoreGammaConversionModelRC.hh
G4int G4LivermoreGammaConversionModelRC::maxZ = 99 static private
Definition at line 95 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 95 of file G4LivermoreGammaConversionModelRC.hh
G4double G4LivermoreGammaConversionModelRC::smallEnergy private
Definition at line 88 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 88 of file G4LivermoreGammaConversionModelRC.hh
G4int G4LivermoreGammaConversionModelRC::verboseLevel private
Definition at line 81 of file G4LivermoreGammaConversionModelRC.hh.
View newest version in sPHENIX GitHub at line 81 of file G4LivermoreGammaConversionModelRC.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreGammaConversionModelRC.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4LivermoreGammaConversionModelRC.cc