ECCE @ EIC Software: G4XXXStoredSceneHandler Class Reference
G4XXXStoredSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXStoredSceneHandler.hh>
Public Member Functions
G4XXXStoredSceneHandler (G4VGraphicsSystem &system, const G4String &name)
virtual ~G4XXXStoredSceneHandler ()
void AddSolid (const G4Box &)
void AddSolid (const G4Cons &cons)
void AddSolid (const G4Tubs &tubs)
void AddSolid (const G4Trd &trd)
void AddSolid (const G4Trap &trap)
void AddSolid (const G4Sphere &sphere)
void AddSolid (const G4Para &para)
void AddSolid (const G4Torus &torus)
void AddSolid (const G4Polycone &polycone)
void AddSolid (const G4Polyhedra &polyhedra)
void AddSolid (const G4Orb &orb)
void AddSolid (const G4Ellipsoid &ellipsoid)
void AddSolid (const G4TessellatedSolid &tess)
void AddSolid (const G4VSolid &solid)
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
void PostAddSolid ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Polymarker &polymarker)
void AddPrimitive (const G4Scale &scale)
void BeginPrimitives (const G4Transform3D &objectTransformation)
void EndPrimitives ()
void ClearStore ()
void ClearTransientStore ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void AddCompound (const G4VTrajectory &)
virtual void AddCompound (const G4VHit &)
virtual void AddCompound (const G4VDigi &)
virtual void AddCompound (const G4THitsMap< G4double > &)
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Protected Types
typedef std::list< G4String > Store
typedef std::list< G4String >
::iterator StoreIterator
Protected Attributes
Store fStore
StoreIterator fCurrentItem
std::vector< StoreIterator > fPermanents
std::vector< StoreIterator > fTransients
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Static Protected Attributes
static G4int fSceneIdCount = 0
Friends
class G4XXXStoredViewer
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Detailed Description
Definition at line 40 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 40 of file G4XXXStoredSceneHandler.hh
Member Typedef Documentation
typedef std::list<G4String> G4XXXStoredSceneHandler::Store protected
Definition at line 128 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 128 of file G4XXXStoredSceneHandler.hh
typedef std::list<G4String>::iterator G4XXXStoredSceneHandler::StoreIterator protected
Definition at line 129 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 129 of file G4XXXStoredSceneHandler.hh
Constructor & Destructor Documentation
G4XXXStoredSceneHandler::G4XXXStoredSceneHandler (G4VGraphicsSystem & system, const G4String & name)
Definition at line 56 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 56 of file G4XXXStoredSceneHandler.cc
G4XXXStoredSceneHandler::~G4XXXStoredSceneHandler () virtual
Definition at line 61 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 61 of file G4XXXStoredSceneHandler.cc
Member Function Documentation
void G4XXXStoredSceneHandler::AddPrimitive (const G4Polyline & polyline) virtual
Implements G4VSceneHandler.
Definition at line 217 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 217 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, G4cout, and G4endl.
void G4XXXStoredSceneHandler::AddPrimitive (const G4Text & text) virtual
Implements G4VSceneHandler.
Definition at line 233 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 233 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, G4cout, and G4endl.
void G4XXXStoredSceneHandler::AddPrimitive (const G4Circle & circle) virtual
Implements G4VSceneHandler.
Definition at line 251 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 251 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, G4cout, G4endl, G4VSceneHandler::GetMarkerSize(), G4VSceneHandler::screen, and G4VSceneHandler::world.
void G4XXXStoredSceneHandler::AddPrimitive (const G4Square & square) virtual
Implements G4VSceneHandler.
Definition at line 281 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 281 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, G4cout, G4endl, G4VSceneHandler::GetMarkerSize(), G4VSceneHandler::screen, square(), and G4VSceneHandler::world.
void G4XXXStoredSceneHandler::AddPrimitive (const G4Polyhedron & polyhedron) virtual
Implements G4VSceneHandler.
Definition at line 311 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 311 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, G4VSceneHandler::fpViewer, G4cout, G4endl, G4VSceneHandler::GetDrawingStyle(), G4ViewParameters::hlr, G4ViewParameters::hsr, and G4ViewParameters::wireframe.
void G4XXXStoredSceneHandler::AddPrimitive (const G4Polymarker & polymarker) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 101 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 101 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4XXXStoredSceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 103 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 103 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4XXXStoredSceneHandler::AddSolid (const G4Box & box) virtual
Reimplemented from G4VSceneHandler.
Definition at line 199 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 199 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, G4cout, G4endl, G4VSolid::GetName(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), and G4Box::GetZHalfLength().
void G4XXXStoredSceneHandler::AddSolid (const G4Cons & cons) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 55 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 55 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Tubs & tubs) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 57 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 57 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Trd & trd) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 59 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 59 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Trap & trap) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 61 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 61 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Sphere & sphere) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 63 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 63 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Para & para) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 65 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 65 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Torus & torus) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 67 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 67 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Polycone & polycone) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 69 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 69 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Polyhedra & polyhedra) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 71 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 71 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Orb & orb) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 73 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 73 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 75 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 75 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4TessellatedSolid & tess) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 77 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 77 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::AddSolid (const G4VSolid & solid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 79 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 79 of file G4XXXStoredSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXStoredSceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
Definition at line 164 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 164 of file G4XXXStoredSceneHandler.cc
References G4VSceneHandler::BeginPrimitives().
void G4XXXStoredSceneHandler::ClearStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 369 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 369 of file G4XXXStoredSceneHandler.cc
References fPermanents, fStore, and fTransients.
void G4XXXStoredSceneHandler::ClearTransientStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 376 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 376 of file G4XXXStoredSceneHandler.cc
References G4VSceneHandler::fpViewer, fStore, and fTransients.
void G4XXXStoredSceneHandler::EndPrimitives () virtual
Reimplemented from G4VSceneHandler.
Definition at line 182 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 182 of file G4XXXStoredSceneHandler.cc
References G4VSceneHandler::EndPrimitives(), fCurrentItem, and G4VSceneHandler::fProcessingSolid.
void G4XXXStoredSceneHandler::PostAddSolid () virtual
Reimplemented from G4VSceneHandler.
Definition at line 157 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 157 of file G4XXXStoredSceneHandler.cc
References fCurrentItem, and G4VSceneHandler::PostAddSolid().
void G4XXXStoredSceneHandler::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes & visAttribs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 93 of file G4XXXStoredSceneHandler.cc.
View newest version in sPHENIX GitHub at line 93 of file G4XXXStoredSceneHandler.cc
References G4AttCheck::Check(), G4VisAttributes::CreateAttValues(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4cout, G4endl, G4VisAttributes::GetAttDefs(), G4PhysicalVolumeModel::GetAttDefs(), G4VSceneHandler::PreAddSolid(), and G4AttCheck::Standard().
Friends And Related Function Documentation
friend class G4XXXStoredViewer friend
Definition at line 42 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 42 of file G4XXXStoredSceneHandler.hh
Member Data Documentation
StoreIterator G4XXXStoredSceneHandler::fCurrentItem protected
Definition at line 131 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 131 of file G4XXXStoredSceneHandler.hh
Referenced by AddPrimitive(), AddSolid(), EndPrimitives(), and PostAddSolid().
std::vector<StoreIterator> G4XXXStoredSceneHandler::fPermanents protected
Definition at line 134 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 134 of file G4XXXStoredSceneHandler.hh
Referenced by ClearStore().
G4int G4XXXStoredSceneHandler::fSceneIdCount = 0 static protected
Definition at line 123 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 123 of file G4XXXStoredSceneHandler.hh
Store G4XXXStoredSceneHandler::fStore protected
Definition at line 130 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 130 of file G4XXXStoredSceneHandler.hh
Referenced by ClearStore(), and ClearTransientStore().
std::vector<StoreIterator> G4XXXStoredSceneHandler::fTransients protected
Definition at line 135 of file G4XXXStoredSceneHandler.hh.
View newest version in sPHENIX GitHub at line 135 of file G4XXXStoredSceneHandler.hh
Referenced by ClearStore(), and ClearTransientStore().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXStoredSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/XXX/src/G4XXXStoredSceneHandler.cc