ECCE @ EIC Software: G4ITModelProcessor Class Reference
G4ITModelProcessor Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITModelProcessor.hh>
Public Member Functions
G4ITModelProcessor ()
G4ITModelProcessor (const G4ITModelProcessor &other)=delete
G4ITModelProcessor & operator= (const G4ITModelProcessor &other)=delete
virtual ~G4ITModelProcessor ()
void SetModelHandler (G4ITModelHandler *)
void SetTrackingManager (G4ITTrackingManager *trackingManager)
void Initialize ()
void RegisterModel (double time, G4VITStepModel *)
void CleanProcessor ()
G4double CalculateMinTimeStep (G4double currentGlobalTime, G4double definedMinTimeStep)
void ComputeTrackReaction (G4ITStepStatus fITStepStatus, G4double fGlobalTime, G4double currentTimeStep, G4double previousTimeStep, G4bool reachedUserTimeLimit, G4double fTimeTolerance, G4UserTimeStepAction *fpUserTimeStepAction, G4int fVerbose)
void InitializeStepper (G4double currentGlobalTime, G4double userMinTime)
bool GetComputeTimeStep () const
void CalculateTimeStep (const G4Track *, G4double userMinTimeStep)
void DoCalculateStep ()
void FindReaction (G4ITReactionSet *pReactionSet, double currentStepTime, double previousStepTime, bool reachedUserStepTimeLimit)
const G4Track * GetTrack () const
Protected Member Functions
void SetTrack (const G4Track *)
void ExtractTimeStepperData ()
Protected Attributes
G4double fTSTimeStep
G4ITReactionSet * fReactionSet
G4ITTrackingManager * fpTrackingManager
G4ITTrackHolder * fpTrackContainer
G4bool fInitialized
G4ITModelHandler * fpModelHandler
const G4Track * fpTrack
G4double fUserMinTimeStep
std::vector< G4VITStepModel * > fActiveModels
G4VITStepModel * fpActiveModelWithMinTimeStep
std::vector< std::unique_ptr
< G4ITReactionChange > > fReactionInfo
bool fComputeTimeStep
bool fComputeReaction
Detailed Description
The G4ITModelProcessor will call the two processes defined in G4VITModel. This processes act at the beginning and end of each step. The first one, the TimeStepper will calculate a time step to propagate all the track and eventually it can return some tracks that can likely react at the end of the step. The second one, the ReactionProcess will make the tracks reacting.
Deprecated:
This class will be removed
Definition at line 71 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ITModelProcessor.hh
Constructor & Destructor Documentation
G4ITModelProcessor::G4ITModelProcessor ()
Definition at line 53 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ITModelProcessor.cc
References DBL_MAX.
G4ITModelProcessor::G4ITModelProcessor (const G4ITModelProcessor & other) delete
G4ITModelProcessor::~G4ITModelProcessor () virtual default
Member Function Documentation
G4double G4ITModelProcessor::CalculateMinTimeStep (G4double currentGlobalTime, G4double definedMinTimeStep)
Definition at line 93 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ITModelProcessor.cc
References DBL_MAX, FatalErrorInArgument, fStopAndKill, fStopButAlive, G4cout, G4endl, G4Exception(), GetIT(), G4IT::GetName(), G4MemStat::MemoryUsage(), and track.
Referenced by G4Scheduler::Stepping().
void G4ITModelProcessor::CalculateTimeStep (const G4Track * pTrack, G4double userMinTimeStep)
Definition at line 236 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 236 of file G4ITModelProcessor.cc
References FatalErrorInArgument, and G4Exception().
void G4ITModelProcessor::CleanProcessor ()
Restore the original state. This method should be called only by G4Scheduler
Definition at line 541 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 541 of file G4ITModelProcessor.cc
void G4ITModelProcessor::ComputeTrackReaction (G4ITStepStatus fITStepStatus, G4double fGlobalTime, G4double currentTimeStep, G4double previousTimeStep, G4bool reachedUserTimeLimit, G4double fTimeTolerance, G4UserTimeStepAction * fpUserTimeStepAction, G4int fVerbose)
Definition at line 267 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 267 of file G4ITModelProcessor.cc
References eCollisionBetweenTracks, FatalErrorInArgument, fStopAndKill, G4BestUnit, G4cout, G4endl, G4Exception(), G4Track::GetGlobalTime(), GetIT(), G4IT::GetName(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4Track::GetStep(), G4Track::GetTrackID(), G4IT::SetParentID(), and G4UserTimeStepAction::UserReactionAction().
Referenced by G4Scheduler::Stepping().
void G4ITModelProcessor::DoCalculateStep ()
Definition at line 257 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 257 of file G4ITModelProcessor.cc
void G4ITModelProcessor::ExtractTimeStepperData () protected
Definition at line 156 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 156 of file G4ITModelProcessor.cc
void G4ITModelProcessor::FindReaction (G4ITReactionSet * pReactionSet, double currentStepTime, double previousStepTime, bool reachedUserStepTimeLimit)
Definition at line 453 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 453 of file G4ITModelProcessor.cc
References FatalErrorInArgument, fStopAndKill, G4Exception(), G4ITReactionSet::GetReactionMap(), G4Track::GetTrackStatus(), it, G4VITReactionProcess::MakeReaction(), G4ITReactionSet::SelectThisReaction(), and G4VITReactionProcess::TestReactibility().
bool G4ITModelProcessor::GetComputeTimeStep () const
Definition at line 546 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 546 of file G4ITModelProcessor.cc
Referenced by G4Scheduler::Stepping().
const G4Track * G4ITModelProcessor::GetTrack () const
Definition at line 551 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 551 of file G4ITModelProcessor.cc
void G4ITModelProcessor::Initialize ()
Definition at line 75 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ITModelProcessor.cc
References G4ITTrackHolder::Instance(), and G4ITReactionSet::Instance().
Referenced by G4Scheduler::Process().
void G4ITModelProcessor::InitializeStepper (G4double currentGlobalTime, G4double userMinTime)
Definition at line 210 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 210 of file G4ITModelProcessor.cc
References G4cout, G4endl, G4MemStat::MemoryUsage(), and G4VITTimeStepComputer::SetTimes().
G4ITModelProcessor& G4ITModelProcessor::operator= (const G4ITModelProcessor & other) delete
void G4ITModelProcessor::RegisterModel (double time, G4VITStepModel * model)
Definition at line 70 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ITModelProcessor.cc
void G4ITModelProcessor::SetModelHandler (G4ITModelHandler * pModelHandler)
Definition at line 528 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 528 of file G4ITModelProcessor.cc
References FatalErrorInArgument, and G4Exception().
Referenced by G4Scheduler::Initialize().
void G4ITModelProcessor::SetTrack (const G4Track * track) protected
Definition at line 523 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 523 of file G4ITModelProcessor.cc
References track.
void G4ITModelProcessor::SetTrackingManager (G4ITTrackingManager * trackingManager)
Definition at line 556 of file G4ITModelProcessor.cc.
View newest version in sPHENIX GitHub at line 556 of file G4ITModelProcessor.cc
Referenced by G4Scheduler::Initialize().
Member Data Documentation
std::vector<G4VITStepModel*> G4ITModelProcessor::fActiveModels protected
Definition at line 133 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ITModelProcessor.hh
bool G4ITModelProcessor::fComputeReaction protected
Definition at line 139 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ITModelProcessor.hh
bool G4ITModelProcessor::fComputeTimeStep protected
Definition at line 138 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ITModelProcessor.hh
G4bool G4ITModelProcessor::fInitialized protected
Definition at line 127 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ITModelProcessor.hh
G4VITStepModel* G4ITModelProcessor::fpActiveModelWithMinTimeStep protected
Definition at line 134 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ITModelProcessor.hh
G4ITModelHandler* G4ITModelProcessor::fpModelHandler protected
Definition at line 128 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ITModelProcessor.hh
const G4Track* G4ITModelProcessor::fpTrack protected
Definition at line 130 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ITModelProcessor.hh
G4ITTrackHolder* G4ITModelProcessor::fpTrackContainer protected
Definition at line 125 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ITModelProcessor.hh
G4ITTrackingManager* G4ITModelProcessor::fpTrackingManager protected
Definition at line 124 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ITModelProcessor.hh
std::vector<std::unique_ptr<G4ITReactionChange> > G4ITModelProcessor::fReactionInfo protected
Definition at line 136 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ITModelProcessor.hh
G4ITReactionSet* G4ITModelProcessor::fReactionSet protected
Definition at line 123 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ITModelProcessor.hh
G4double G4ITModelProcessor::fTSTimeStep protected
Definition at line 122 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ITModelProcessor.hh
G4double G4ITModelProcessor::fUserMinTimeStep protected
Definition at line 131 of file G4ITModelProcessor.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ITModelProcessor.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITModelProcessor.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITModelProcessor.cc