ECCE @ EIC Software: CML2Acc1Messenger Class Reference
CML2Acc1Messenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Acc1Messenger.hh>
Public Member Functions
CML2Acc1Messenger (CML2Acc1 *acc1)
~CML2Acc1Messenger (void)
void SetNewValue (G4UIcommand *cmd, G4String newValue)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CML2Acc1 * pAcc1
G4UIcmdWithAnInteger * idEnergy
G4UIcmdWithADoubleAndUnit * aperture1X
G4UIcmdWithADoubleAndUnit * aperture2X
G4UIcmdWithADoubleAndUnit * aperture1Y
G4UIcmdWithADoubleAndUnit * aperture2Y
G4UIcmdWithADoubleAndUnit * leavesA
G4UIcmdWithADoubleAndUnit * leavesB
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 56 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 56 of file ML2Acc1Messenger.hh
Constructor & Destructor Documentation
CML2Acc1Messenger::CML2Acc1Messenger (CML2Acc1 * acc1)
Definition at line 53 of file ML2Acc1Messenger.cc.
View newest version in sPHENIX GitHub at line 53 of file ML2Acc1Messenger.cc
References aperture1X, aperture1Y, aperture2X, aperture2Y, idEnergy, leavesA, leavesB, mm, pAcc1, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), CML2Accelerator::setidEnergy(), CML2Accelerator::setJaw1X(), CML2Accelerator::setJaw1Y(), CML2Accelerator::setJaw2X(), CML2Accelerator::setJaw2Y(), CML2Accelerator::setLeavesAx(), and CML2Accelerator::setLeavesBx().
CML2Acc1Messenger::~CML2Acc1Messenger (void)
Definition at line 90 of file ML2Acc1Messenger.cc.
View newest version in sPHENIX GitHub at line 90 of file ML2Acc1Messenger.cc
References aperture1X, aperture1Y, aperture2X, aperture2Y, idEnergy, leavesA, and leavesB.
Member Function Documentation
void CML2Acc1Messenger::SetNewValue (G4UIcommand * cmd, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 100 of file ML2Acc1Messenger.cc.
View newest version in sPHENIX GitHub at line 100 of file ML2Acc1Messenger.cc
References aperture1X, aperture1Y, aperture2X, aperture2Y, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4UIcmdWithADoubleAndUnit::GetNewUnitValue(), idEnergy, leavesA, leavesB, pAcc1, CML2Accelerator::setidEnergy(), CML2Accelerator::setJaw1X(), CML2Accelerator::setJaw1Y(), CML2Accelerator::setJaw2X(), CML2Accelerator::setJaw2Y(), CML2Accelerator::setLeavesAx(), and CML2Accelerator::setLeavesBx().
Member Data Documentation
G4UIcmdWithADoubleAndUnit* CML2Acc1Messenger::aperture1X private
Definition at line 66 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
G4UIcmdWithADoubleAndUnit * CML2Acc1Messenger::aperture1Y private
Definition at line 66 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
G4UIcmdWithADoubleAndUnit * CML2Acc1Messenger::aperture2X private
Definition at line 66 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
G4UIcmdWithADoubleAndUnit * CML2Acc1Messenger::aperture2Y private
Definition at line 66 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
G4UIcmdWithAnInteger* CML2Acc1Messenger::idEnergy private
Definition at line 65 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 65 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
G4UIcmdWithADoubleAndUnit * CML2Acc1Messenger::leavesA private
Definition at line 66 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
G4UIcmdWithADoubleAndUnit * CML2Acc1Messenger::leavesB private
Definition at line 66 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), SetNewValue(), and ~CML2Acc1Messenger().
CML2Acc1* CML2Acc1Messenger::pAcc1 private
Definition at line 63 of file ML2Acc1Messenger.hh.
View newest version in sPHENIX GitHub at line 63 of file ML2Acc1Messenger.hh
Referenced by CML2Acc1Messenger(), and SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Acc1Messenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Acc1Messenger.cc