ECCE @ EIC Software: G4VPreCompoundEmissionFactory Class Reference
G4VPreCompoundEmissionFactory Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4VPreCompoundEmissionFactory.hh>
Classes
struct DeleteFragment
Public Member Functions
G4VPreCompoundEmissionFactory ()
virtual ~G4VPreCompoundEmissionFactory ()
std::vector
< G4VPreCompoundFragment * > * GetFragmentVector ()
Protected Member Functions
virtual std::vector
< G4VPreCompoundFragment * > * CreateFragmentVector ()=0
Private Member Functions
G4VPreCompoundEmissionFactory (const G4VPreCompoundEmissionFactory &)
const
G4VPreCompoundEmissionFactory & operator= (const G4VPreCompoundEmissionFactory &val)
G4bool operator== (const G4VPreCompoundEmissionFactory &val) const
G4bool operator!= (const G4VPreCompoundEmissionFactory &val) const
Private Attributes
std::vector
< G4VPreCompoundFragment * > * fragvector
Detailed Description
Definition at line 36 of file G4VPreCompoundEmissionFactory.hh.
View newest version in sPHENIX GitHub at line 36 of file G4VPreCompoundEmissionFactory.hh
Constructor & Destructor Documentation
G4VPreCompoundEmissionFactory::G4VPreCompoundEmissionFactory ()
Definition at line 31 of file G4VPreCompoundEmissionFactory.cc.
View newest version in sPHENIX GitHub at line 31 of file G4VPreCompoundEmissionFactory.cc
G4VPreCompoundEmissionFactory::~G4VPreCompoundEmissionFactory () virtual
Definition at line 35 of file G4VPreCompoundEmissionFactory.cc.
View newest version in sPHENIX GitHub at line 35 of file G4VPreCompoundEmissionFactory.cc
References fragvector.
G4VPreCompoundEmissionFactory::G4VPreCompoundEmissionFactory (const G4VPreCompoundEmissionFactory &) private
Member Function Documentation
virtual std::vector<G4VPreCompoundFragment*>* G4VPreCompoundEmissionFactory::CreateFragmentVector () protected pure virtual
Implemented in G4HETCEmissionFactory, and G4PreCompoundEmissionFactory.
Referenced by GetFragmentVector().
std::vector< G4VPreCompoundFragment * > * G4VPreCompoundEmissionFactory::GetFragmentVector () inline
Definition at line 72 of file G4VPreCompoundEmissionFactory.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VPreCompoundEmissionFactory.hh
References CreateFragmentVector(), and fragvector.
Referenced by G4PreCompoundEmission::G4PreCompoundEmission(), G4PreCompoundEmission::SetDefaultModel(), and G4PreCompoundEmission::SetHETCModel().
G4bool G4VPreCompoundEmissionFactory::operator!= (const G4VPreCompoundEmissionFactory & val) const private
const G4VPreCompoundEmissionFactory& G4VPreCompoundEmissionFactory::operator= (const G4VPreCompoundEmissionFactory & val) private
G4bool G4VPreCompoundEmissionFactory::operator== (const G4VPreCompoundEmissionFactory & val) const private
Member Data Documentation
std::vector<G4VPreCompoundFragment*>* G4VPreCompoundEmissionFactory::fragvector private
Definition at line 58 of file G4VPreCompoundEmissionFactory.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VPreCompoundEmissionFactory.hh
Referenced by GetFragmentVector(), and ~G4VPreCompoundEmissionFactory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4VPreCompoundEmissionFactory.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4VPreCompoundEmissionFactory.cc