ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_target_heated.cc File Reference
MCGIDI_target_heated.cc File Reference
#include <map>
#include <string.h>
#include <cmath>
#include <xDataTOM.h>
#include "MCGIDI.h"
#include "MCGIDI_misc.h"
#include "MCGIDI_private.h"
Functions
static int MCGIDI_target_heated_parsePOPs (statusMessageReporting *smr, MCGIDI_target_heated *target, xDataTOM_element *element, xDataTOM_element *particleAliases)
static int MCGIDI_target_heated_parseParticle (statusMessageReporting *smr, MCGIDI_target_heated *target, xDataTOM_element *element, xDataTOM_element *particleAliases)
static int MCGIDI_target_heated_parseParticleLevel (statusMessageReporting *smr, MCGIDI_target_heated *target, xDataTOM_element *element, MCGIDI_POP *parent, double mass_MeV, xDataTOM_element *particleAliases)
static int MCGIDI_target_heated_parseParticleGammas (statusMessageReporting *smr, MCGIDI_target_heated *target, xDataTOM_element *element, char const *name)
static int MCGIDI_target_heated_parseReaction (statusMessageReporting *smr, xDataTOM_element *child, MCGIDI_target_heated *target, MCGIDI_POPs *pops, MCGIDI_reaction *reaction)
MCGIDI_target_heated * MCGIDI_target_heated_new (statusMessageReporting *smr)
int MCGIDI_target_heated_initialize (statusMessageReporting *smr, MCGIDI_target_heated *target)
MCGIDI_target_heated * MCGIDI_target_heated_newRead (statusMessageReporting *smr, const char *fileName)
MCGIDI_target_heated * MCGIDI_target_heated_free (statusMessageReporting *smr, MCGIDI_target_heated *target)
int MCGIDI_target_heated_release (statusMessageReporting *, MCGIDI_target_heated *target)
int MCGIDI_target_heated_read (statusMessageReporting *smr, MCGIDI_target_heated *target, const char *fileName)
int MCGIDI_target_heated_numberOfReactions (statusMessageReporting *, MCGIDI_target_heated *target)
int MCGIDI_target_heated_numberOfProductionReactions (statusMessageReporting *, MCGIDI_target_heated *)
MCGIDI_reaction * MCGIDI_target_heated_getReactionAtIndex (MCGIDI_target_heated *target, int index)
MCGIDI_reaction * MCGIDI_target_heated_getReactionAtIndex_smr (statusMessageReporting *smr, MCGIDI_target_heated *target, int index)
MCGIDI_POP * MCGIDI_target_heated_getPOPForProjectile (statusMessageReporting *, MCGIDI_target_heated *target)
MCGIDI_POP * MCGIDI_target_heated_getPOPForTarget (statusMessageReporting *, MCGIDI_target_heated *target)
double MCGIDI_target_heated_getProjectileMass_MeV (statusMessageReporting *, MCGIDI_target_heated *target)
double MCGIDI_target_heated_getTargetMass_MeV (statusMessageReporting *, MCGIDI_target_heated *target)
double MCGIDI_target_heated_getTotalCrossSectionAtE (statusMessageReporting *smr, MCGIDI_target_heated *target, MCGIDI_quantitiesLookupModes &modes, bool sampling)
double MCGIDI_target_heated_getIndexReactionCrossSectionAtE (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, MCGIDI_quantitiesLookupModes &modes, bool sampling)
int MCGIDI_target_heated_sampleIndexReactionProductsAtE (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productDatas)
double MCGIDI_target_heated_getReactionsThreshold (statusMessageReporting *, MCGIDI_target_heated *target, int index)
int MCGIDI_target_heated_getReactionsDomain (statusMessageReporting *, MCGIDI_target_heated *target, int index, double *EMin, double *EMax)
double MCGIDI_target_heated_getIndexReactionFinalQ (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, MCGIDI_quantitiesLookupModes &modes)
std::map< int, enum
MCGIDI_transportability >
const * MCGIDI_target_heated_getUniqueProducts (statusMessageReporting *, MCGIDI_target_heated *target)
int MCGIDI_target_heated_recast (statusMessageReporting *smr, MCGIDI_target_heated *target, GIDI_settings &settings)
Function Documentation
MCGIDI_target_heated* MCGIDI_target_heated_free (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 64 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 64 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_release(), and smr_freeMemory().
Referenced by MCGIDI_target_release().
double MCGIDI_target_heated_getIndexReactionCrossSectionAtE (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 496 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 496 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_getCrossSectionAtE(), and MCGIDI_target_heated_getReactionAtIndex_smr().
Referenced by MCGIDI_target_getIndexReactionCrossSectionAtE().
double MCGIDI_target_heated_getIndexReactionFinalQ (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, MCGIDI_quantitiesLookupModes & modes)
Definition at line 542 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 542 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_getFinalQ(), and MCGIDI_target_heated_getReactionAtIndex_smr().
Referenced by MCGIDI_target_getIndexReactionFinalQ().
MCGIDI_POP* MCGIDI_target_heated_getPOPForProjectile (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 433 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 433 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::projectilePOP.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
MCGIDI_POP* MCGIDI_target_heated_getPOPForTarget (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 440 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 440 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::targetPOP.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
double MCGIDI_target_heated_getProjectileMass_MeV (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 447 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 447 of file MCGIDI_target_heated.cc
References MCGIDI_POP_getMass_MeV(), and MCGIDI_target_heated_s::projectilePOP.
Referenced by MCGIDI_reaction_getProjectileMass_MeV().
MCGIDI_reaction* MCGIDI_target_heated_getReactionAtIndex (MCGIDI_target_heated * target, int index)
Definition at line 401 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 401 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::reactions.
Referenced by G4GIDI_target::getChannelIDs(), G4GIDI_target::init(), MCGIDI_target_getReactionAtIndex(), MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_target_heated_getReactionsDomain(), MCGIDI_target_heated_getReactionsThreshold(), and MCGIDI_target_sampleReaction().
MCGIDI_reaction* MCGIDI_target_heated_getReactionAtIndex_smr (statusMessageReporting * smr, MCGIDI_target_heated * target, int index)
Definition at line 409 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 409 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_getReactionAtIndex(), MCGIDI_POP_s::name, MCGIDI_target_heated_s::projectilePOP, smr_setReportError2, smr_unknownID, and MCGIDI_target_heated_s::targetPOP.
Referenced by G4GIDI_target::getChannelsID(), G4GIDI_target::getElasticFinalState(), MCGIDI_target_getReactionAtIndex_smr(), MCGIDI_target_getReactionTypeAtIndex(), MCGIDI_target_heated_getIndexReactionCrossSectionAtE(), MCGIDI_target_heated_getIndexReactionFinalQ(), and MCGIDI_target_heated_sampleIndexReactionProductsAtE().
int MCGIDI_target_heated_getReactionsDomain (statusMessageReporting * , MCGIDI_target_heated * target, int index, double * EMin, double * EMax)
Definition at line 530 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 530 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, and MCGIDI_target_heated_getReactionAtIndex().
Referenced by G4GIDI_target::getReactionsDomain(), and MCGIDI_target_getDomain().
double MCGIDI_target_heated_getReactionsThreshold (statusMessageReporting * , MCGIDI_target_heated * target, int index)
Definition at line 520 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 520 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_s::EMin, and MCGIDI_target_heated_getReactionAtIndex().
Referenced by G4GIDI_target::getReactionsThreshold().
double MCGIDI_target_heated_getTargetMass_MeV (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 454 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 454 of file MCGIDI_target_heated.cc
References MCGIDI_POP_getMass_MeV(), and MCGIDI_target_heated_s::targetPOP.
Referenced by MCGIDI_reaction_getTargetMass_MeV().
double MCGIDI_target_heated_getTotalCrossSectionAtE (statusMessageReporting * smr, MCGIDI_target_heated * target, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 461 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 461 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::crossSection, MCGIDI_target_heated_s::crossSectionGrouped, MCGIDI_target_heated_s::crossSectionGroupedForSampling, MCGIDI_target_heated_s::EMax, MCGIDI_target_heated_s::EMin, MCGIDI_quantitiesLookupModes::getCrossSectionMode(), MCGIDI_quantitiesLookupModes::getGroupIndex(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_quantityLookupMode_grouped, MCGIDI_quantityLookupMode_pointwise, ptwX_getPointAtIndex(), ptwX_length(), ptwXY_getValueAtX(), smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_target_getTotalCrossSectionAtTAndE().
std::map<int, enum MCGIDI_transportability> const* MCGIDI_target_heated_getUniqueProducts (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 553 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 553 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::transportabilities.
Referenced by MCGIDI_target_getUniqueProducts().
int MCGIDI_target_heated_initialize (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 43 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 43 of file MCGIDI_target_heated.cc
References MCGIDI_POPs_initial(), MCGIDI_target_heated_s::pops, and MCGIDI_target_heated_s::transportabilities.
Referenced by MCGIDI_target_heated_new().
MCGIDI_target_heated* MCGIDI_target_heated_new (statusMessageReporting * smr)
Definition at line 32 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 32 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_initialize(), smr_freeMemory(), and smr_malloc2.
Referenced by MCGIDI_target_heated_newRead().
MCGIDI_target_heated* MCGIDI_target_heated_newRead (statusMessageReporting * smr, const char * fileName)
Definition at line 53 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 53 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_new(), MCGIDI_target_heated_read(), and smr_freeMemory().
Referenced by MCGIDI_target_readHeatedTarget().
int MCGIDI_target_heated_numberOfProductionReactions (statusMessageReporting * , MCGIDI_target_heated *)
Definition at line 394 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 394 of file MCGIDI_target_heated.cc
Referenced by MCGIDI_target_numberOfProductionReactions().
int MCGIDI_target_heated_numberOfReactions (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 387 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 387 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::numberOfReactions.
Referenced by MCGIDI_target_numberOfReactions().
static int MCGIDI_target_heated_parseParticle (statusMessageReporting * smr, MCGIDI_target_heated * target, xDataTOM_element * element, xDataTOM_element * particleAliases) static
Definition at line 235 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 235 of file MCGIDI_target_heated.cc
References check_license::err(), mass, MCGIDI_AMU2MeV, MCGIDI_misc_PQUStringToDouble(), MCGIDI_POPs_addParticleIfNeeded(), MCGIDI_target_heated_parseParticleLevel(), xDataTOM_element_s::name, MCGIDI_target_heated_s::pops, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_getAttributesValueInElement(), xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_target_heated_parsePOPs().
static int MCGIDI_target_heated_parseParticleGammas (statusMessageReporting * smr, MCGIDI_target_heated * target, xDataTOM_element * element, char const * name) static
Definition at line 331 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 331 of file MCGIDI_target_heated.cc
References check_license::err(), MCGIDI_POP_s::gammas, MCGIDI_POPs_findParticle(), xDataTOM_element_s::name, MCGIDI_POP_s::numberOfGammaBranchs, MCGIDI_target_heated_s::pops, smr_freeMemory(), smr_malloc2, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_getAttributesValueInElement(), xDataTOME_convertAttributeToDouble(), xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_target_heated_parseParticleLevel().
static int MCGIDI_target_heated_parseParticleLevel (statusMessageReporting * smr, MCGIDI_target_heated * target, xDataTOM_element * element, MCGIDI_POP * parent, double mass_MeV, xDataTOM_element * particleAliases) static
Definition at line 296 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 296 of file MCGIDI_target_heated.cc
References check_license::err(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_POPs_addParticleIfNeeded(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_s::pops, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_getAttributesValueInElement(), xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_target_heated_parseParticle().
static int MCGIDI_target_heated_parsePOPs (statusMessageReporting * smr, MCGIDI_target_heated * target, xDataTOM_element * element, xDataTOM_element * particleAliases) static
Definition at line 215 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 215 of file MCGIDI_target_heated.cc
References check_license::err(), MCGIDI_target_heated_parseParticle(), xDataTOM_element_s::name, smr_setReportError2, smr_unknownID, xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_target_heated_read().
static int MCGIDI_target_heated_parseReaction (statusMessageReporting * smr, xDataTOM_element * child, MCGIDI_target_heated * target, MCGIDI_POPs * pops, MCGIDI_reaction * reaction) static
Definition at line 372 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 372 of file MCGIDI_target_heated.cc
References check_license::err(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_s::numberOfReactions, smr_setReportError2, smr_unknownID, and xDataTOM_getAttributesValueInElement().
Referenced by MCGIDI_target_heated_read().
int MCGIDI_target_heated_read (statusMessageReporting * smr, MCGIDI_target_heated * target, const char * fileName)
Definition at line 92 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 92 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::absPath, xDataTOM_element_s::attributes, MCGIDI_target_heated_s::attributes, MCGIDI_reaction_s::crossSection, MCGIDI_target_heated_s::crossSection, e, e1, MCGIDI_target_heated_s::EMax, MCGIDI_target_heated_s::EMin, check_license::err(), MCGIDI_misc_getUnitConversionFactor(), MCGIDI_misc_pointerToTOMAttributeIfAllOk3, MCGIDI_misc_updateTransportabilitiesMap(), MCGIDI_POPs_findParticle(), MCGIDI_reaction_fixDomains(), MCGIDI_reaction_getDomain(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_release(), n, xDataTOM_element_s::name, nfu_statusMessage(), MCGIDI_target_heated_s::numberOfReactions, MCGIDI_target_heated_s::path, MCGIDI_target_heated_s::pops, printf(), MCGIDI_target_heated_s::projectilePOP, ptwXY_add_ptwXY(), ptwXY_create(), ptwXY_free(), ptwXY_interpolationLinLin, MCGIDI_target_heated_s::reactions, smr_allocateCopyString2, smr_isOk(), smr_malloc2, smr_setReportError2, smr_unknownID, MCGIDI_target_heated_s::targetPOP, MCGIDI_target_heated_s::temperature_MeV, MCGIDI_reaction_s::transportabilities, MCGIDI_target_heated_s::transportabilities, xDataTOM_freeTOM(), xDataTOM_getAttributesValueInElement(), xDataTOM_getDocumentsElement(), xDataTOM_importFile(), xDataTOM_numberOfElementsByName(), xDataTOMAL_copyAttributionList(), xDataTOME_getFirstElement(), xDataTOME_getNextElement(), xDataTOME_getOneElementByName(), and xDataTOMMisc_getAbsPath().
Referenced by MCGIDI_target_heated_newRead().
int MCGIDI_target_heated_recast (statusMessageReporting * smr, MCGIDI_target_heated * target, GIDI_settings & settings)
Definition at line 560 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 560 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::crossSectionGrouped, MCGIDI_target_heated_s::crossSectionGroupedForSampling, check_license::err(), GIDI_settings_particle::getNumberOfGroups(), GIDI_settings::getParticle(), MCGIDI_POP_s::globalPoPsIndex, GIDI_settings_particle::isEnergyMode_grouped(), MCGIDI_reaction_recast(), MCGIDI_POP_s::name, nfu_statusMessage(), MCGIDI_target_heated_s::numberOfReactions, MCGIDI_target_heated_s::projectilePOP, ptwX_clone(), ptwX_createLine(), ptwX_free(), ptwX_getPointAtIndex_Unsafely(), ptwX_setPointAtIndex(), MCGIDI_target_heated_s::reactions, smr_setReportError2, smr_unknownID, MCGIDI_target_heated_s::temperature_MeV, MCGIDI_reaction_s::thresholdGroupedDeltaCrossSection, and MCGIDI_reaction_s::thresholdGroupIndex.
Referenced by MCGIDI_target_recast().
int MCGIDI_target_heated_release (statusMessageReporting * , MCGIDI_target_heated * target)
Definition at line 73 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 73 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::absPath, MCGIDI_target_heated_s::attributes, MCGIDI_target_heated_s::crossSection, MCGIDI_target_heated_s::crossSectionGrouped, MCGIDI_target_heated_s::crossSectionGroupedForSampling, MCGIDI_POPs_release(), MCGIDI_reaction_release(), MCGIDI_target_heated_s::numberOfReactions, MCGIDI_target_heated_s::path, MCGIDI_target_heated_s::pops, ptwX_free(), ptwXY_free(), MCGIDI_target_heated_s::reactions, smr_freeMemory(), MCGIDI_target_heated_s::transportabilities, and xDataTOMAL_release().
Referenced by MCGIDI_target_heated_free(), and MCGIDI_target_heated_read().
int MCGIDI_target_heated_sampleIndexReactionProductsAtE (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productDatas)
Definition at line 508 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 508 of file MCGIDI_target_heated.cc
References MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_sampledProductsDatas_s::numberOfProducts, and MCGIDI_reaction_s::outputChannel.
Referenced by G4GIDI_target::getFinalState(), and MCGIDI_target_sampleIndexReactionProductsAtE().