ECCE @ EIC Software: F04GlobalField Class Reference
F04GlobalField Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04GlobalField.hh>
Public Member Functions
virtual ~F04GlobalField ()
virtual void GetFieldValue (const G4double *point, G4double *field) const
virtual G4bool DoesFieldChangeEnergy () const
DoesFieldChangeEnergy() returns true.
void AddElementField (F04ElementField *f)
void Clear ()
void ConstructField ()
constructs all field tracking objects
void SetStepperType (G4int i)
Set the Stepper types.
void SetStepper ()
Set the Stepper.
void SetMinStep (G4double stp)
Set the minimum step length.
void SetDeltaChord (G4double dcr)
Set the delta chord length.
void SetDeltaOneStep (G4double stp)
Set the delta one step length.
void SetDeltaIntersection (G4double its)
Set the delta intersection length.
void SetEpsMin (G4double eps)
Set the minimum eps length.
void SetEpsMax (G4double eps)
Set the maximum eps length.
FieldList * GetFields ()
Return the list of Element Fields.
Public Member Functions inherited from G4ElectroMagneticField
G4ElectroMagneticField ()
virtual ~G4ElectroMagneticField ()
G4ElectroMagneticField (const G4ElectroMagneticField &r)
G4ElectroMagneticField & operator= (const G4ElectroMagneticField &p)
virtual void GetFieldValue (const G4double Point[4], G4double *Bfield) const =0
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
virtual G4Field * Clone () const
Static Public Member Functions
static F04GlobalField * GetObject (F04DetectorConstruction *const)
static F04GlobalField * GetObject ()
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
Get the global field manager.
Private Member Functions
F04GlobalField (F04DetectorConstruction *const)
F04GlobalField (const F04GlobalField &)
F04GlobalField & operator= (const F04GlobalField &)
void SetupArray ()
Private Attributes
G4int fNfp
G4bool fFirst
FieldList * fFields
const F04ElementField ** fFp
G4int fStepperType
G4double fMinStep
G4double fDeltaChord
G4double fDeltaOneStep
G4double fDeltaIntersection
G4double fEpsMin
G4double fEpsMax
G4EqEMFieldWithSpin * fEquation
G4FieldManager * fFieldManager
G4PropagatorInField * fFieldPropagator
G4MagIntegratorStepper * fStepper
G4ChordFinder * fChordFinder
F04FieldMessenger * fFieldMessenger
F04DetectorConstruction * fDetectorConstruction
Static Private Attributes
static G4ThreadLocal
F04GlobalField * fObject = 0
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 67 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 67 of file F04GlobalField.hh
Constructor & Destructor Documentation
F04GlobalField::F04GlobalField (F04DetectorConstruction * const det) private
Definition at line 54 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 54 of file F04GlobalField.cc
References ConstructField(), fFieldMessenger, fFields, fFirst, fFp, fNfp, fObject, and fStepperType.
Referenced by GetObject().
F04GlobalField::F04GlobalField (const F04GlobalField &) private
F04GlobalField::~F04GlobalField () virtual
Definition at line 90 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 90 of file F04GlobalField.cc
References Clear(), fChordFinder, fEquation, fFieldMessenger, fFields, and fStepper.
Member Function Documentation
void F04GlobalField::AddElementField (F04ElementField * f) inline
AddElementField() adds the ElementField object for a single element to the global field.
Definition at line 98 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 98 of file F04GlobalField.hh
References fFields.
Referenced by F04ElementField::F04ElementField().
void F04GlobalField::Clear ()
Clear() removes all ElementField-s from the global object, and destroys them. Used before the geometry is completely re-created.
Definition at line 291 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 291 of file F04GlobalField.cc
References fFields, fFirst, fFp, and fNfp.
Referenced by ConstructField(), and ~F04GlobalField().
void F04GlobalField::ConstructField ()
constructs all field tracking objects
Definition at line 105 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 105 of file F04GlobalField.cc
References B(), Clear(), fChordFinder, fDeltaChord, fDeltaIntersection, fDeltaOneStep, fDetectorConstruction, fEpsMax, fEpsMin, fEquation, fFieldManager, fFieldPropagator, fFields, fMinStep, fStepper, G4cout, G4endl, F04DetectorConstruction::GetCaptureMgnt(), F04DetectorConstruction::GetCaptureMgntB1(), F04DetectorConstruction::GetCaptureMgntB2(), F04DetectorConstruction::GetCaptureMgntCenter(), GetGlobalFieldManager(), G4TransportationManager::GetPropagatorInField(), F04DetectorConstruction::GetTransferMgnt(), F04DetectorConstruction::GetTransferMgntB(), F04DetectorConstruction::GetTransferMgntCenter(), G4TransportationManager::GetTransportationManager(), mm, G4FieldManager::SetAccuraciesWithDeltaOneStep(), G4FieldManager::SetChordFinder(), F04ElementField::SetColor(), G4ChordFinder::SetDeltaChord(), G4FieldManager::SetDeltaIntersection(), G4FieldManager::SetDetectorField(), G4FieldManager::SetFieldChangesEnergy(), G4PropagatorInField::SetMaximumEpsilonStep(), F04ElementField::SetMaxStep(), G4PropagatorInField::SetMinimumEpsilonStep(), and SetStepper().
Referenced by F04GlobalField().
virtual G4bool F04GlobalField::DoesFieldChangeEnergy () const inline virtual
DoesFieldChangeEnergy() returns true.
Implements G4ElectroMagneticField.
Definition at line 94 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 94 of file F04GlobalField.hh
FieldList* F04GlobalField::GetFields () inline
Return the list of Element Fields.
Definition at line 136 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 136 of file F04GlobalField.hh
References fFields.
void F04GlobalField::GetFieldValue (const G4double * point, G4double * field) const virtual
GetFieldValue() returns the field value at a given point[]. field is really field[6]: Bx,By,Bz,Ex,Ey,Ez. point[] is in global coordinates: x,y,z,t.
Definition at line 266 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 266 of file F04GlobalField.cc
References F04ElementField::AddFieldValue(), fFirst, fFp, fNfp, and F04ElementField::IsInBoundingBox().
G4FieldManager * F04GlobalField::GetGlobalFieldManager () protected
Get the global field manager.
Definition at line 258 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 258 of file F04GlobalField.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by ConstructField().
F04GlobalField * F04GlobalField::GetObject (F04DetectorConstruction * const det) static
GetObject() returns the single F04GlobalField object. It is constructed, if necessary.
Definition at line 200 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 200 of file F04GlobalField.cc
References F04GlobalField(), and fObject.
F04GlobalField * F04GlobalField::GetObject () static
Definition at line 208 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 208 of file F04GlobalField.cc
References fObject.
Referenced by F04DetectorConstruction::ConstructSDandField(), and F04ElementField::F04ElementField().
F04GlobalField& F04GlobalField::operator= (const F04GlobalField &) private
void F04GlobalField::SetDeltaChord (G4double dcr) inline
Set the delta chord length.
Definition at line 121 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 121 of file F04GlobalField.hh
References fDeltaChord.
Referenced by F04FieldMessenger::SetNewValue().
void F04GlobalField::SetDeltaIntersection (G4double its) inline
Set the delta intersection length.
Definition at line 127 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 127 of file F04GlobalField.hh
References fDeltaIntersection.
void F04GlobalField::SetDeltaOneStep (G4double stp) inline
Set the delta one step length.
Definition at line 124 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 124 of file F04GlobalField.hh
References fDeltaOneStep.
void F04GlobalField::SetEpsMax (G4double eps) inline
Set the maximum eps length.
Definition at line 133 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 133 of file F04GlobalField.hh
References eps, and fEpsMax.
Referenced by F04FieldMessenger::SetNewValue().
void F04GlobalField::SetEpsMin (G4double eps) inline
Set the minimum eps length.
Definition at line 130 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 130 of file F04GlobalField.hh
References eps, and fEpsMin.
Referenced by F04FieldMessenger::SetNewValue().
void F04GlobalField::SetMinStep (G4double stp) inline
Set the minimum step length.
Definition at line 118 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 118 of file F04GlobalField.hh
References fMinStep.
Referenced by F04FieldMessenger::SetNewValue().
void F04GlobalField::SetStepper ()
Set the Stepper.
Definition at line 216 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 216 of file F04GlobalField.cc
References fEquation, fStepper, fStepperType, G4cout, and G4endl.
Referenced by ConstructField().
void F04GlobalField::SetStepperType (G4int i) inline
Set the Stepper types.
Definition at line 112 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 112 of file F04GlobalField.hh
References fStepperType.
Referenced by F04FieldMessenger::SetNewValue().
void F04GlobalField::SetupArray () private
Definition at line 309 of file F04GlobalField.cc.
View newest version in sPHENIX GitHub at line 309 of file F04GlobalField.cc
References fFields, fFirst, fFp, and fNfp.
Member Data Documentation
G4ChordFinder* F04GlobalField::fChordFinder private
Definition at line 174 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 174 of file F04GlobalField.hh
Referenced by ConstructField(), and ~F04GlobalField().
G4double F04GlobalField::fDeltaChord private
Definition at line 159 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 159 of file F04GlobalField.hh
Referenced by ConstructField(), and SetDeltaChord().
G4double F04GlobalField::fDeltaIntersection private
Definition at line 161 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 161 of file F04GlobalField.hh
Referenced by ConstructField(), and SetDeltaIntersection().
G4double F04GlobalField::fDeltaOneStep private
Definition at line 160 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 160 of file F04GlobalField.hh
Referenced by ConstructField(), and SetDeltaOneStep().
F04DetectorConstruction* F04GlobalField::fDetectorConstruction private
Definition at line 178 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 178 of file F04GlobalField.hh
Referenced by ConstructField().
G4double F04GlobalField::fEpsMax private
Definition at line 163 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 163 of file F04GlobalField.hh
Referenced by ConstructField(), and SetEpsMax().
G4double F04GlobalField::fEpsMin private
Definition at line 162 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 162 of file F04GlobalField.hh
Referenced by ConstructField(), and SetEpsMin().
G4EqEMFieldWithSpin* F04GlobalField::fEquation private
Definition at line 169 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 169 of file F04GlobalField.hh
Referenced by ConstructField(), SetStepper(), and ~F04GlobalField().
G4FieldManager* F04GlobalField::fFieldManager private
Definition at line 171 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 171 of file F04GlobalField.hh
Referenced by ConstructField().
F04FieldMessenger* F04GlobalField::fFieldMessenger private
Definition at line 176 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 176 of file F04GlobalField.hh
Referenced by F04GlobalField(), and ~F04GlobalField().
G4PropagatorInField* F04GlobalField::fFieldPropagator private
Definition at line 172 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 172 of file F04GlobalField.hh
Referenced by ConstructField().
FieldList* F04GlobalField::fFields private
Definition at line 150 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 150 of file F04GlobalField.hh
Referenced by AddElementField(), Clear(), ConstructField(), F04GlobalField(), GetFields(), SetupArray(), and ~F04GlobalField().
G4bool F04GlobalField::fFirst private
Definition at line 148 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 148 of file F04GlobalField.hh
Referenced by Clear(), F04GlobalField(), GetFieldValue(), and SetupArray().
const F04ElementField** F04GlobalField::fFp private
Definition at line 152 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 152 of file F04GlobalField.hh
Referenced by Clear(), F04GlobalField(), GetFieldValue(), and SetupArray().
G4double F04GlobalField::fMinStep private
Definition at line 158 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 158 of file F04GlobalField.hh
Referenced by ConstructField(), and SetMinStep().
G4int F04GlobalField::fNfp private
Definition at line 147 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 147 of file F04GlobalField.hh
Referenced by Clear(), F04GlobalField(), GetFieldValue(), and SetupArray().
G4ThreadLocal F04GlobalField * F04GlobalField::fObject = 0 static private
Definition at line 145 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 145 of file F04GlobalField.hh
Referenced by F04GlobalField(), and GetObject().
G4MagIntegratorStepper* F04GlobalField::fStepper private
Definition at line 173 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 173 of file F04GlobalField.hh
Referenced by ConstructField(), SetStepper(), and ~F04GlobalField().
G4int F04GlobalField::fStepperType private
Definition at line 156 of file F04GlobalField.hh.
View newest version in sPHENIX GitHub at line 156 of file F04GlobalField.hh
Referenced by F04GlobalField(), SetStepper(), and SetStepperType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04GlobalField.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04GlobalField.cc