ECCE @ EIC Software: G4CascadeHistory Class Reference
G4CascadeHistory Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeHistory.hh>
Classes
struct HistoryEntry
Public Member Functions
G4CascadeHistory (G4int verbose=0)
~G4CascadeHistory ()
void setVerboseLevel (G4int verbose=0)
void Clear ()
G4int AddEntry (G4CascadParticle &cpart)
G4int AddVertex (G4CascadParticle &cpart, std::vector< G4CascadParticle > &daug)
void DropEntry (const G4CascadParticle &cpart)
void Print (std::ostream &os) const
Protected Member Functions
void AssignHistoryID (G4CascadParticle &cpart)
void FillDaughters (G4int iEntry, std::vector< G4CascadParticle > &daug)
void PrintEntry (std::ostream &os, G4int iEntry) const
void PrintParticle (std::ostream &os, const G4CascadParticle &cpart) const
G4bool PrintingDone (G4int iEntry) const
const char * GuessTarget (const HistoryEntry &entry) const
G4int size () const
Private Member Functions
G4CascadeHistory (const G4CascadeHistory &rhs)
G4CascadeHistory & operator= (const G4CascadeHistory &rhs)
Private Attributes
G4int verboseLevel
std::vector< HistoryEntry > theHistory
std::set< G4int > entryPrinted
Detailed Description
Definition at line 40 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 40 of file G4CascadeHistory.hh
Constructor & Destructor Documentation
G4CascadeHistory::G4CascadeHistory (G4int verbose = 0) inline
Definition at line 42 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 42 of file G4CascadeHistory.hh
G4CascadeHistory::~G4CascadeHistory () inline
Definition at line 43 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 43 of file G4CascadeHistory.hh
G4CascadeHistory::G4CascadeHistory (const G4CascadeHistory & rhs) private
Member Function Documentation
G4int G4CascadeHistory::AddEntry (G4CascadParticle & cpart)
Definition at line 105 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 105 of file G4CascadeHistory.cc
References AssignHistoryID(), G4cout, G4endl, G4CascadParticle::getHistoryId(), size(), theHistory, and verboseLevel.
Referenced by AddVertex(), FillDaughters(), and G4IntraNucleiCascader::generateCascade().
G4int G4CascadeHistory::AddVertex (G4CascadParticle & cpart, std::vector< G4CascadParticle > & daug)
Definition at line 58 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 58 of file G4CascadeHistory.cc
References AddEntry(), FillDaughters(), G4cout, G4endl, theHistory, and verboseLevel.
Referenced by G4IntraNucleiCascader::generateCascade().
void G4CascadeHistory::AssignHistoryID (G4CascadParticle & cpart) protected
Definition at line 136 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 136 of file G4CascadeHistory.cc
References G4cout, G4endl, G4CascadParticle::getHistoryId(), G4CascadParticle::setHistoryId(), size(), and verboseLevel.
Referenced by AddEntry().
void G4CascadeHistory::Clear ()
Definition at line 49 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 49 of file G4CascadeHistory.cc
References entryPrinted, G4cout, G4endl, theHistory, and verboseLevel.
Referenced by G4IntraNucleiCascader::newCascade().
void G4CascadeHistory::DropEntry (const G4CascadParticle & cpart)
Definition at line 126 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 126 of file G4CascadeHistory.cc
References G4cout, G4endl, G4CascadParticle::getHistoryId(), theHistory, and verboseLevel.
Referenced by G4IntraNucleiCascader::processTrappedParticle().
void G4CascadeHistory::FillDaughters (G4int iEntry, std::vector< G4CascadParticle > & daug) protected
Definition at line 79 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 79 of file G4CascadeHistory.cc
References AddEntry(), G4cout, G4endl, theHistory, and verboseLevel.
Referenced by AddVertex().
const char * G4CascadeHistory::GuessTarget (const HistoryEntry & entry) const protected
Definition at line 204 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 204 of file G4CascadeHistory.cc
References G4InuclElementaryParticle::baryon(), G4CascadeHistory::HistoryEntry::cpart, G4CascadeHistory::HistoryEntry::dId, G4cout, G4endl, G4InuclParticle::getCharge(), G4CascadParticle::getParticle(), G4CascadeHistory::HistoryEntry::n, theHistory, and verboseLevel.
Referenced by PrintEntry().
G4CascadeHistory& G4CascadeHistory::operator= (const G4CascadeHistory & rhs) private
void G4CascadeHistory::Print (std::ostream & os) const
Definition at line 155 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 155 of file G4CascadeHistory.cc
References PrintEntry(), PrintingDone(), size(), and verboseLevel.
Referenced by G4IntraNucleiCascader::collide(), operator<<(), and G4IntraNucleiCascader::rescatter().
void G4CascadeHistory::PrintEntry (std::ostream & os, G4int iEntry) const protected
Definition at line 168 of file G4CascadeHistory.cc.
View newest version in sPHENIX GitHub at line 168 of file G4CascadeHistory.cc
References G4CascadeHistory::HistoryEntry::cpart, G4CascadeHistory::HistoryEntry::dId, entryPrinted, G4CascadParticle::getCurrentZone(), G4InuclParticle::getDefinition(), G4CascadParticle::getGeneration(), G4CascadParticle::getMomentum(), G4CascadParticle::getParticle(), G4ParticleDefinition::GetParticleName(), G4CascadParticle::getPosition(), GuessTarget(), left, G4CascadeHistory::HistoryEntry::n, PrintingDone(), size(), theHistory, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and CLHEP::Hep3Vector::z().
Referenced by Print().
G4bool G4CascadeHistory::PrintingDone (G4int iEntry) const inline protected
Definition at line 82 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CascadeHistory.hh
References entryPrinted.
Referenced by Print(), and PrintEntry().
void G4CascadeHistory::PrintParticle (std::ostream & os, const G4CascadParticle & cpart) const protected
void G4CascadeHistory::setVerboseLevel (G4int verbose = 0) inline
Definition at line 45 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 45 of file G4CascadeHistory.hh
References verboseLevel.
Referenced by G4IntraNucleiCascader::setVerboseLevel().
G4int G4CascadeHistory::size (void) const inline protected
Definition at line 89 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 89 of file G4CascadeHistory.hh
References theHistory.
Referenced by AddEntry(), AssignHistoryID(), Print(), and PrintEntry().
Member Data Documentation
std::set<G4int> G4CascadeHistory::entryPrinted mutable private
Definition at line 95 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 95 of file G4CascadeHistory.hh
Referenced by Clear(), PrintEntry(), and PrintingDone().
std::vector<HistoryEntry> G4CascadeHistory::theHistory private
Definition at line 94 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CascadeHistory.hh
Referenced by AddEntry(), AddVertex(), Clear(), DropEntry(), FillDaughters(), GuessTarget(), PrintEntry(), and size().
G4int G4CascadeHistory::verboseLevel private
Definition at line 92 of file G4CascadeHistory.hh.
View newest version in sPHENIX GitHub at line 92 of file G4CascadeHistory.hh
Referenced by AddEntry(), AddVertex(), AssignHistoryID(), Clear(), DropEntry(), FillDaughters(), GuessTarget(), Print(), and setVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeHistory.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeHistory.cc