ECCE @ EIC Software: G4HETCNeutron Class Reference
G4HETCNeutron Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCNeutron.hh>
Public Member Functions
G4HETCNeutron ()
~G4HETCNeutron ()
virtual G4double SampleKineticEnergy (const G4Fragment &aFragment)
Public Member Functions inherited from G4HETCFragment
G4HETCFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4HETCFragment ()
G4double CalcEmissionProbability (const G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundFragment
G4VPreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4VPreCompoundFragment ()
void Initialize (const G4Fragment &aFragment)
G4bool IsItPossible (const G4Fragment &aFragment) const
G4ReactionProduct * GetReactionProduct () const
G4int GetA () const
G4int GetZ () const
G4int GetRestA () const
G4int GetRestZ () const
G4double GetBindingEnergy () const
G4double GetEnergyThreshold () const
G4double GetEmissionProbability () const
G4double GetNuclearMass () const
G4double GetRestNuclearMass () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Protected Member Functions
virtual G4double GetAlpha () const
virtual G4double GetBeta () const
virtual G4double GetSpinFactor () const
virtual G4double K (const G4Fragment &aFragment)
Protected Member Functions inherited from G4HETCFragment
G4double BetaRand (G4int N, G4int L) const
Private Member Functions
G4HETCNeutron (const G4HETCNeutron &right)
const G4HETCNeutron & operator= (const G4HETCNeutron &right)
G4bool operator== (const G4HETCNeutron &right) const
G4bool operator!= (const G4HETCNeutron &right) const
Private Attributes
G4NeutronCoulombBarrier theNeutronCoulombBarrier
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundFragment
G4NuclearLevelData * fNucData
G4DeexPrecoParameters * theParameters
G4Pow * g4calc
G4int theA
G4int theZ
G4int theResA
G4int theResZ
G4int theFragA
G4int theFragZ
G4double theResA13
G4double theBindingEnergy
G4double theMinKinEnergy
G4double theMaxKinEnergy
G4double theResMass
G4double theReducedMass
G4double theMass
G4double theEmissionProbability
G4double theCoulombBarrier
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 40 of file G4HETCNeutron.hh.
View newest version in sPHENIX GitHub at line 40 of file G4HETCNeutron.hh
Constructor & Destructor Documentation
G4HETCNeutron::G4HETCNeutron ()
Definition at line 39 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HETCNeutron.cc
G4HETCNeutron::~G4HETCNeutron ()
Definition at line 43 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 43 of file G4HETCNeutron.cc
G4HETCNeutron::G4HETCNeutron (const G4HETCNeutron & right) private
Member Function Documentation
G4double G4HETCNeutron::GetAlpha () const protected virtual
Implements G4HETCFragment.
Definition at line 46 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 46 of file G4HETCNeutron.cc
References G4VPreCompoundFragment::theResA13.
Referenced by GetBeta().
G4double G4HETCNeutron::GetBeta () const protected virtual
Implements G4HETCFragment.
Definition at line 51 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HETCNeutron.cc
References GetAlpha(), MeV, and G4VPreCompoundFragment::theResA13.
Referenced by SampleKineticEnergy().
G4double G4HETCNeutron::GetSpinFactor () const protected virtual
Implements G4HETCFragment.
Definition at line 56 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 56 of file G4HETCNeutron.cc
G4double G4HETCNeutron::K (const G4Fragment & aFragment) protected virtual
Implements G4HETCFragment.
Definition at line 62 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 62 of file G4HETCNeutron.cc
References G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), H, max, P, r, G4VPreCompoundFragment::theA, G4VPreCompoundFragment::theResA, G4VPreCompoundFragment::theResZ, and G4VPreCompoundFragment::theZ.
G4bool G4HETCNeutron::operator!= (const G4HETCNeutron & right) const private
const G4HETCNeutron& G4HETCNeutron::operator= (const G4HETCNeutron & right) private
G4bool G4HETCNeutron::operator== (const G4HETCNeutron & right) const private
G4double G4HETCNeutron::SampleKineticEnergy (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundFragment.
Definition at line 83 of file G4HETCNeutron.cc.
View newest version in sPHENIX GitHub at line 83 of file G4HETCNeutron.cc
References G4HETCFragment::BetaRand(), Emax, G4VPreCompoundFragment::fNucData, G4UniformRand, GetBeta(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), H, max, pi2, G4VPreCompoundFragment::theFragA, G4VPreCompoundFragment::theFragZ, G4VPreCompoundFragment::theMaxKinEnergy, and x.
Member Data Documentation
G4NeutronCoulombBarrier G4HETCNeutron::theNeutronCoulombBarrier private
Definition at line 68 of file G4HETCNeutron.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HETCNeutron.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCNeutron.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4HETCNeutron.cc