ECCE @ EIC Software: G4PSCylinderSurfaceFlux Class Reference
G4PSCylinderSurfaceFlux Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSCylinderSurfaceFlux.hh>
Public Member Functions
G4PSCylinderSurfaceFlux (G4String name, G4int direction, G4int depth=0)
G4PSCylinderSurfaceFlux (G4String name, G4int direction, const G4String &unit, G4int depth=0)
virtual ~G4PSCylinderSurfaceFlux ()
void Weighted (G4bool flg=true)
void DivideByArea (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
G4int IsSelectedSurface (G4Step *, G4Tubs *)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4int fDirection
G4THitsMap< G4double > * EvtMap
G4bool weighted
G4bool divideByArea
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 58 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PSCylinderSurfaceFlux.hh
Constructor & Destructor Documentation
G4PSCylinderSurfaceFlux::G4PSCylinderSurfaceFlux (G4String name, G4int direction, G4int depth = 0)
Definition at line 57 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PSCylinderSurfaceFlux.cc
References DefineUnitAndCategory(), and SetUnit().
G4PSCylinderSurfaceFlux::G4PSCylinderSurfaceFlux (G4String name, G4int direction, const G4String & unit, G4int depth = 0)
Definition at line 66 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 66 of file G4PSCylinderSurfaceFlux.cc
References DefineUnitAndCategory(), and SetUnit().
G4PSCylinderSurfaceFlux::~G4PSCylinderSurfaceFlux () virtual
Definition at line 77 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PSCylinderSurfaceFlux.cc
Member Function Documentation
void G4PSCylinderSurfaceFlux::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 203 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 203 of file G4PSCylinderSurfaceFlux.cc
References G4VTHitsMap< T, Map_t >::clear(), and EvtMap.
void G4PSCylinderSurfaceFlux::DefineUnitAndCategory () protected virtual
Definition at line 239 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 239 of file G4PSCylinderSurfaceFlux.cc
References cm2, m2, and mm2.
Referenced by G4PSCylinderSurfaceFlux().
void G4PSCylinderSurfaceFlux::DivideByArea (G4bool flg = true) inline
Definition at line 69 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSCylinderSurfaceFlux.hh
References divideByArea.
void G4PSCylinderSurfaceFlux::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 207 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 207 of file G4PSCylinderSurfaceFlux.cc
void G4PSCylinderSurfaceFlux::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 200 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 200 of file G4PSCylinderSurfaceFlux.cc
void G4PSCylinderSurfaceFlux::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 192 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 192 of file G4PSCylinderSurfaceFlux.cc
References G4HCofThisEvent::AddHitsCollection(), EvtMap, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetMultiFunctionalDetector(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
G4int G4PSCylinderSurfaceFlux::IsSelectedSurface (G4Step * aStep, G4Tubs * tubsSolid) protected
Definition at line 149 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 149 of file G4PSCylinderSurfaceFlux.cc
References fFlux_In, fFlux_Out, fGeomBoundary, G4VTouchable::GetHistory(), G4Tubs::GetInnerRadius(), G4GeometryTolerance::GetInstance(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4GeometryTolerance::GetSurfaceTolerance(), G4NavigationHistory::GetTopTransform(), G4StepPoint::GetTouchableHandle(), G4Tubs::GetZHalfLength(), kCarTolerance, G4AffineTransform::TransformPoint(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ProcessHits().
void G4PSCylinderSurfaceFlux::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 210 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 210 of file G4PSCylinderSurfaceFlux.cc
References G4VPrimitiveScorer::detector, G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), G4VPrimitiveScorer::GetUnit(), and G4VPrimitiveScorer::GetUnitValue().
G4bool G4PSCylinderSurfaceFlux::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 80 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 80 of file G4PSCylinderSurfaceFlux.cc
References G4VTHitsMap< T, Map_t >::add(), G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), divideByArea, EvtMap, FALSE, fDirection, fFlux_In, fFlux_InOut, fFlux_Out, G4Tubs::GetDeltaPhiAngle(), G4VTouchable::GetHistory(), G4VPrimitiveScorer::GetIndex(), G4Tubs::GetInnerRadius(), G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetMomentumDirection(), G4VPhysicalVolume::GetParameterisation(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopTransform(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4StepPoint::GetWeight(), G4Tubs::GetZHalfLength(), incremental_prev_tag::idx, G4VPrimitiveScorer::indexDepth, IsSelectedSurface(), radian, square(), G4AffineTransform::TransformAxis(), TRUE, weighted, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4PSCylinderSurfaceFlux::SetUnit (const G4String & unit) virtual
Definition at line 224 of file G4PSCylinderSurfaceFlux.cc.
View newest version in sPHENIX GitHub at line 224 of file G4PSCylinderSurfaceFlux.cc
References G4VPrimitiveScorer::CheckAndSetUnit(), divideByArea, G4Exception(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::GetUnit(), JustWarning, G4VPrimitiveScorer::unitName, and G4VPrimitiveScorer::unitValue.
Referenced by G4PSCylinderSurfaceFlux(), and G4PSCylinderSurfaceFlux3D::G4PSCylinderSurfaceFlux3D().
void G4PSCylinderSurfaceFlux::Weighted (G4bool flg = true) inline
Definition at line 66 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 66 of file G4PSCylinderSurfaceFlux.hh
References weighted.
Member Data Documentation
G4bool G4PSCylinderSurfaceFlux::divideByArea private
Definition at line 94 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PSCylinderSurfaceFlux.hh
Referenced by DivideByArea(), ProcessHits(), and SetUnit().
G4THitsMap<G4double>* G4PSCylinderSurfaceFlux::EvtMap private
Definition at line 92 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PSCylinderSurfaceFlux.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int G4PSCylinderSurfaceFlux::fDirection private
Definition at line 91 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PSCylinderSurfaceFlux.hh
Referenced by ProcessHits().
G4int G4PSCylinderSurfaceFlux::HCID private
Definition at line 90 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PSCylinderSurfaceFlux.hh
Referenced by Initialize().
G4bool G4PSCylinderSurfaceFlux::weighted private
Definition at line 93 of file G4PSCylinderSurfaceFlux.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PSCylinderSurfaceFlux.hh
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSCylinderSurfaceFlux.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSCylinderSurfaceFlux.cc