ECCE @ EIC Software: G4Absorber Class Reference
G4Absorber Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4Absorber.hh>
Public Member Functions
G4Absorber (G4double cutOnP)
~G4Absorber ()
G4bool WillBeAbsorbed (const G4KineticTrack &kt)
G4bool Absorb (G4KineticTrack &kt, G4KineticTrackVector &tgt)
G4KineticTrackVector * GetAbsorbers ()
G4KineticTrackVector * GetProducts ()
G4bool FindAbsorbers (G4KineticTrack &kt, G4KineticTrackVector &tgt)
G4bool FindProducts (G4KineticTrack &kt)
Private Member Functions
G4Absorber (const G4Absorber &right)
const G4Absorber & operator= (const G4Absorber &right)
G4bool operator== (const G4Absorber &right) const
G4bool operator!= (const G4Absorber &right) const
G4ThreeVector GetRandomDirection ()
Private Attributes
G4double theCutOnP
G4KineticTrackVector * theAbsorbers
G4KineticTrackVector * theProducts
Detailed Description
Definition at line 34 of file G4Absorber.hh.
View newest version in sPHENIX GitHub at line 34 of file G4Absorber.hh
Constructor & Destructor Documentation
G4Absorber::G4Absorber (G4double cutOnP)
Definition at line 38 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 38 of file G4Absorber.cc
References theAbsorbers, theCutOnP, and theProducts.
G4Absorber::~G4Absorber ()
Definition at line 46 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 46 of file G4Absorber.cc
References theAbsorbers, and theProducts.
G4Absorber::G4Absorber (const G4Absorber & right) private
Member Function Documentation
G4bool G4Absorber::Absorb (G4KineticTrack & kt, G4KineticTrackVector & tgt)
Definition at line 72 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 72 of file G4Absorber.cc
References FindAbsorbers(), and FindProducts().
G4bool G4Absorber::FindAbsorbers (G4KineticTrack & kt, G4KineticTrackVector & tgt)
Definition at line 80 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 80 of file G4Absorber.cc
References charge, DBL_MAX, eplus, G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4KineticTrack::GetPosition(), pos(), and theAbsorbers.
Referenced by Absorb(), and G4BinaryCascade::Absorb().
G4bool G4Absorber::FindProducts (G4KineticTrack & kt)
Definition at line 174 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 174 of file G4Absorber.cc
References CLHEP::HepLorentzVector::boostVector(), charge, eplus, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4KineticTrack::GetPosition(), GetRandomDirection(), G4Neutron::Neutron(), G4Proton::Proton(), and theProducts.
Referenced by Absorb(), and G4BinaryCascade::Absorb().
G4KineticTrackVector * G4Absorber::GetAbsorbers () inline
Definition at line 66 of file G4Absorber.hh.
View newest version in sPHENIX GitHub at line 66 of file G4Absorber.hh
References theAbsorbers.
Referenced by G4BinaryCascade::Absorb().
G4KineticTrackVector * G4Absorber::GetProducts () inline
Definition at line 71 of file G4Absorber.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Absorber.hh
References theProducts.
Referenced by G4BinaryCascade::Absorb().
G4ThreeVector G4Absorber::GetRandomDirection () private
Definition at line 286 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 286 of file G4Absorber.cc
References G4UniformRand, phi, pi, and theta().
Referenced by FindProducts().
G4bool G4Absorber::operator!= (const G4Absorber & right) const private
const G4Absorber& G4Absorber::operator= (const G4Absorber & right) private
G4bool G4Absorber::operator== (const G4Absorber & right) const private
bool G4Absorber::WillBeAbsorbed (const G4KineticTrack & kt)
Definition at line 53 of file G4Absorber.cc.
View newest version in sPHENIX GitHub at line 53 of file G4Absorber.cc
References CLHEP::HepLorentzVector::e(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), G4KineticTrack::GetDefinition(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), and theCutOnP.
Referenced by G4BinaryCascade::Absorb().
Member Data Documentation
G4KineticTrackVector* G4Absorber::theAbsorbers private
Definition at line 57 of file G4Absorber.hh.
View newest version in sPHENIX GitHub at line 57 of file G4Absorber.hh
Referenced by FindAbsorbers(), G4Absorber(), GetAbsorbers(), and ~G4Absorber().
G4double G4Absorber::theCutOnP private
Definition at line 56 of file G4Absorber.hh.
View newest version in sPHENIX GitHub at line 56 of file G4Absorber.hh
Referenced by G4Absorber(), and WillBeAbsorbed().
G4KineticTrackVector* G4Absorber::theProducts private
Definition at line 58 of file G4Absorber.hh.
View newest version in sPHENIX GitHub at line 58 of file G4Absorber.hh
Referenced by FindProducts(), G4Absorber(), GetProducts(), and ~G4Absorber().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4Absorber.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4Absorber.cc