ECCE @ EIC Software: G4UIArrayString Class Reference
G4UIArrayString Class Reference
#include <geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4UIArrayString.hh>
Public Member Functions
G4UIArrayString (const G4String &stream)
~G4UIArrayString ()
void Show (G4int ncol)
Private Member Functions
G4String * GetElement (G4int icol, G4int irow) const
G4int GetNRow (G4int icol) const
G4int GetNField (G4int icol) const
G4int CalculateColumnWidth () const
Private Attributes
G4String * stringArray
G4int nElement
G4int nColumn
Detailed Description
Definition at line 40 of file G4UIArrayString.hh.
View newest version in sPHENIX GitHub at line 40 of file G4UIArrayString.hh
Constructor & Destructor Documentation
G4UIArrayString::G4UIArrayString (const G4String & stream)
Definition at line 35 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 35 of file G4UIArrayString.cc
References G4String::both, G4String::index(), nColumn, nElement, stringArray, and G4String::strip().
G4UIArrayString::~G4UIArrayString ()
Definition at line 80 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 80 of file G4UIArrayString.cc
References stringArray.
Member Function Documentation
int G4UIArrayString::CalculateColumnWidth () const private
Definition at line 138 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 138 of file G4UIArrayString.cc
References GetNField(), and nColumn.
Referenced by Show().
G4String * G4UIArrayString::GetElement (G4int icol, G4int irow) const private
Definition at line 87 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 87 of file G4UIArrayString.cc
References G4cerr, and G4endl.
Referenced by Show().
G4int G4UIArrayString::GetNField (G4int icol) const private
Definition at line 117 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 117 of file G4UIArrayString.cc
References G4cout, G4endl, BTOF::length, and strESC.
Referenced by CalculateColumnWidth(), and Show().
G4int G4UIArrayString::GetNRow (G4int icol) const private
Definition at line 102 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 102 of file G4UIArrayString.cc
References G4InuclParticleNames::nn.
Referenced by Show().
void G4UIArrayString::Show (G4int ncol)
Definition at line 154 of file G4UIArrayString.cc.
View newest version in sPHENIX GitHub at line 154 of file G4UIArrayString.cc
References CalculateColumnWidth(), G4cout, G4endl, GetElement(), GetNField(), GetNRow(), left, nColumn, nElement, and strESC.
Referenced by G4VUIshell::ListCommand().
Member Data Documentation
G4int G4UIArrayString::nColumn private
Definition at line 44 of file G4UIArrayString.hh.
View newest version in sPHENIX GitHub at line 44 of file G4UIArrayString.hh
Referenced by CalculateColumnWidth(), G4UIArrayString(), and Show().
G4int G4UIArrayString::nElement private
Definition at line 43 of file G4UIArrayString.hh.
View newest version in sPHENIX GitHub at line 43 of file G4UIArrayString.hh
Referenced by G4UIArrayString(), and Show().
G4String* G4UIArrayString::stringArray private
Definition at line 42 of file G4UIArrayString.hh.
View newest version in sPHENIX GitHub at line 42 of file G4UIArrayString.hh
Referenced by G4UIArrayString(), and ~G4UIArrayString().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4UIArrayString.hh
geant4/tree/geant4-10.6-release/source/interfaces/basic/src/G4UIArrayString.cc