ECCE @ EIC Software: G4ENDFYieldDataContainer Class Reference
G4ENDFYieldDataContainer Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ENDFYieldDataContainer.hh>
Public Member Functions
G4ENDFYieldDataContainer (G4int YieldSlots)
G4FFGEnumerations::MetaState GetMetaState (void)
G4int GetProduct (void)
G4double * GetYieldError (void)
G4double * GetYieldProbability (void)
G4int GetYieldSlots (void)
void SetMetaState (G4FFGEnumerations::MetaState MetaState)
void SetProduct (G4int Product)
void SetYieldError (G4double *YieldError)
void SetYieldProbability (G4double *YieldProbability)
void SetYieldSlots (G4int NumberOfSlots)
~G4ENDFYieldDataContainer (void)
Protected Attributes
G4int YieldSlots_
G4int Product_
G4FFGEnumerations::MetaState MetaState_
G4double * YieldProbability_
G4double * YieldError_
Detailed Description
G4ENDFYieldDataContainer is a simple data storage class that handles the memory management internally. One instance stores the information for one fission product. In the event of a non-spontaneous fission, it can store the yield probabilities and errors at each of the fission- inducing particles energy levels. For ENDF data and neutron-induced fission these energies are typically 0.0253 eV, 1 MeV, and 5 MeV.
Definition at line 47 of file G4ENDFYieldDataContainer.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ENDFYieldDataContainer.hh
Constructor & Destructor Documentation
G4ENDFYieldDataContainer::G4ENDFYieldDataContainer (G4int YieldSlots)
Default constructor
Definition at line 40 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ENDFYieldDataContainer.cc
References G4FFGEnumerations::GROUND_STATE, MetaState_, Product_, YieldError_, YieldProbability_, and YieldSlots_.
G4ENDFYieldDataContainer::~G4ENDFYieldDataContainer (void)
Default deconstructor
Definition at line 112 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 112 of file G4ENDFYieldDataContainer.cc
References YieldError_, and YieldProbability_.
Member Function Documentation
G4FFGEnumerations::MetaState G4ENDFYieldDataContainer::GetMetaState (void)
Get the meta state
Definition at line 51 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ENDFYieldDataContainer.cc
References MetaState_.
Referenced by G4FissionProductYieldDist::SortProbability().
G4int G4ENDFYieldDataContainer::GetProduct (void)
Get the product
Definition at line 57 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ENDFYieldDataContainer.cc
References Product_.
Referenced by G4FissionProductYieldDist::SortProbability().
G4double * G4ENDFYieldDataContainer::GetYieldError (void)
Get the yield error
Definition at line 63 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ENDFYieldDataContainer.cc
References YieldError_.
G4double * G4ENDFYieldDataContainer::GetYieldProbability (void)
Get the yield probability
Definition at line 69 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ENDFYieldDataContainer.cc
References YieldProbability_.
Referenced by G4FissionProductYieldDist::SortProbability().
G4int G4ENDFYieldDataContainer::GetYieldSlots (void)
Get the number of yield slots
Definition at line 75 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ENDFYieldDataContainer.cc
References YieldSlots_.
void G4ENDFYieldDataContainer::SetMetaState (G4FFGEnumerations::MetaState MetaState)
Set the meta state
Definition at line 81 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ENDFYieldDataContainer.cc
References MetaState_.
Referenced by G4ENDFTapeRead::ReadInData().
void G4ENDFYieldDataContainer::SetProduct (G4int Product)
Set the product
Definition at line 87 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 87 of file G4ENDFYieldDataContainer.cc
References Product_.
Referenced by G4ENDFTapeRead::ReadInData().
void G4ENDFYieldDataContainer::SetYieldError (G4double * YieldError)
Set the yield error
Definition at line 93 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ENDFYieldDataContainer.cc
References G4ArrayOps::Copy(), YieldError_, and YieldSlots_.
Referenced by G4ENDFTapeRead::ReadInData().
void G4ENDFYieldDataContainer::SetYieldProbability (G4double * YieldProbability)
Set the yield probability
Definition at line 99 of file G4ENDFYieldDataContainer.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ENDFYieldDataContainer.cc
References G4ArrayOps::Copy(), YieldProbability_, and YieldSlots_.
Referenced by G4ENDFTapeRead::ReadInData().
void G4ENDFYieldDataContainer::SetYieldSlots (G4int NumberOfSlots)
Set the number of yield slots
Member Data Documentation
G4FFGEnumerations::MetaState G4ENDFYieldDataContainer::MetaState_ protected
Metastable state information of the stored isotope
Definition at line 83 of file G4ENDFYieldDataContainer.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ENDFYieldDataContainer.hh
Referenced by G4ENDFYieldDataContainer(), GetMetaState(), and SetMetaState().
G4int G4ENDFYieldDataContainer::Product_ protected
ZZZAAA identifier of the stored isotope
Definition at line 81 of file G4ENDFYieldDataContainer.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ENDFYieldDataContainer.hh
Referenced by G4ENDFYieldDataContainer(), GetProduct(), and SetProduct().
G4double* G4ENDFYieldDataContainer::YieldError_ protected
Array of the yield probability errors, one per yield slot
Definition at line 87 of file G4ENDFYieldDataContainer.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ENDFYieldDataContainer.hh
Referenced by G4ENDFYieldDataContainer(), GetYieldError(), SetYieldError(), and ~G4ENDFYieldDataContainer().
G4double* G4ENDFYieldDataContainer::YieldProbability_ protected
Array of yield probabilities, one per yield slot
Definition at line 85 of file G4ENDFYieldDataContainer.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ENDFYieldDataContainer.hh
Referenced by G4ENDFYieldDataContainer(), GetYieldProbability(), SetYieldProbability(), and ~G4ENDFYieldDataContainer().
G4int G4ENDFYieldDataContainer::YieldSlots_ protected
The number of energy groups, or yield slots, that are stored
Definition at line 79 of file G4ENDFYieldDataContainer.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ENDFYieldDataContainer.hh
Referenced by G4ENDFYieldDataContainer(), GetYieldSlots(), SetYieldError(), and SetYieldProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ENDFYieldDataContainer.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ENDFYieldDataContainer.cc