ECCE @ EIC Software: G4HyperNucleiProperties Class Reference
G4HyperNucleiProperties Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4HyperNucleiProperties.hh>
Public Member Functions
~G4HyperNucleiProperties ()
G4HyperNucleiProperties ()
Static Public Member Functions
static G4double GetAtomicMass (G4int A, G4int Z, G4int L)
static G4double GetNuclearMass (G4int A, G4int Z, G4int L)
Detailed Description
Definition at line 44 of file G4HyperNucleiProperties.hh.
View newest version in sPHENIX GitHub at line 44 of file G4HyperNucleiProperties.hh
Constructor & Destructor Documentation
G4HyperNucleiProperties::~G4HyperNucleiProperties () inline
Definition at line 55 of file G4HyperNucleiProperties.hh.
View newest version in sPHENIX GitHub at line 55 of file G4HyperNucleiProperties.hh
G4HyperNucleiProperties::G4HyperNucleiProperties () inline
Definition at line 58 of file G4HyperNucleiProperties.hh.
View newest version in sPHENIX GitHub at line 58 of file G4HyperNucleiProperties.hh
Member Function Documentation
G4double G4HyperNucleiProperties::GetAtomicMass (G4int A, G4int Z, G4int L) static
Definition at line 101 of file G4HyperNucleiProperties.cc.
View newest version in sPHENIX GitHub at line 101 of file G4HyperNucleiProperties.cc
References source.hepunit::electron_mass_c2, G4cout, G4endl, GetNuclearMass(), G4ParticleTable::GetParticleTable(), and MeV.
G4double G4HyperNucleiProperties::GetNuclearMass (G4int A, G4int Z, G4int L) static
Definition at line 41 of file G4HyperNucleiProperties.cc.
View newest version in sPHENIX GitHub at line 41 of file G4HyperNucleiProperties.cc
References eps, G4ParticleTable::FindParticle(), G4cout, G4endl, G4NucleiProperties::GetNuclearMass(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4ParticleTable::GetVerboseLevel(), G4InuclParticleNames::lambda, mass, MeV, and mLL.
Referenced by GetAtomicMass(), and G4IonTable::GetNucleusMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4HyperNucleiProperties.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4HyperNucleiProperties.cc