ECCE @ EIC Software: G4AllITFinder Class Reference
G4AllITFinder Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4AllITFinder.hh>
Public Member Functions
~G4AllITFinder ()
G4VITFinder * GetInstance (G4ITType)
G4ITBox * GetBox (const G4Track *)
void RegisterManager (G4VITFinder *manager)
void Push (G4Track *track)
void SetVerboseLevel (G4int level)
G4int GetVerboseLevel ()
void UpdatePositionMap ()
template<typename T >
G4KDTreeResultHandle FindNearest (const G4ThreeVector &pos, const T *it)
template<typename T >
G4KDTreeResultHandle FindNearest (const T *it0, const T *it)
template<typename T >
G4KDTreeResultHandle FindNearestInRange (const G4ThreeVector &pos, const T *it, G4double range)
template<typename T >
G4KDTreeResultHandle FindNearestInRange (const T *it0, const T *it, G4double range)
Static Public Member Functions
static G4AllITFinder * Instance ()
static void DeleteInstance ()
Private Member Functions
G4AllITFinder ()
Private Attributes
std::map< G4ITType, G4VITFinder * > fITSubManager
int fVerbose
Static Private Attributes
static G4ThreadLocal
G4AllITFinder * fpInstance = 0
Detailed Description
Holds all IT Manager, and take care of deleting them when AllITManager is deleted Set general verbose for all IT Manager
Definition at line 70 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4AllITFinder.hh
Constructor & Destructor Documentation
G4AllITFinder::~G4AllITFinder ()
To delete the Instance you should use DeleteInstance() rather than the destructor
Definition at line 61 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 61 of file G4AllITFinder.cc
References it.
G4AllITFinder::G4AllITFinder () private
Definition at line 41 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 41 of file G4AllITFinder.cc
Member Function Documentation
void G4AllITFinder::DeleteInstance () static
Definition at line 52 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 52 of file G4AllITFinder.cc
Referenced by G4Scheduler::ClearList().
template<typename T > G4KDTreeResultHandle G4AllITFinder::FindNearest (const G4ThreeVector & pos, const T * it) inline
Definition at line 126 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 126 of file G4AllITFinder.hh
References G4ITFinder< T >::FindNearest(), and G4ITFinder< T >::Instance().
template<typename T > G4KDTreeResultHandle G4AllITFinder::FindNearest (const T * it0, const T * it) inline
Definition at line 133 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 133 of file G4AllITFinder.hh
References G4ITFinder< T >::FindNearest(), and G4ITFinder< T >::Instance().
template<typename T > G4KDTreeResultHandle G4AllITFinder::FindNearestInRange (const G4ThreeVector & pos, const T * it, G4double range) inline
Definition at line 140 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 140 of file G4AllITFinder.hh
References G4ITFinder< T >::FindNearestInRange(), and G4ITFinder< T >::Instance().
template<typename T > G4KDTreeResultHandle G4AllITFinder::FindNearestInRange (const T * it0, const T * it, G4double range) inline
Definition at line 148 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 148 of file G4AllITFinder.hh
References G4ITFinder< T >::FindNearestInRange(), and G4ITFinder< T >::Instance().
G4ITBox* G4AllITFinder::GetBox (const G4Track *)
G4VITFinder * G4AllITFinder::GetInstance (G4ITType type)
Definition at line 86 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 86 of file G4AllITFinder.cc
References it.
G4int G4AllITFinder::GetVerboseLevel () inline
Definition at line 96 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AllITFinder.hh
References fVerbose.
G4AllITFinder * G4AllITFinder::Instance (void) static
Definition at line 46 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 46 of file G4AllITFinder.cc
void G4AllITFinder::Push (G4Track * track)
Definition at line 100 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 100 of file G4AllITFinder.cc
References GetIT(), and G4IT::GetITType().
void G4AllITFinder::RegisterManager (G4VITFinder * manager)
Definition at line 95 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 95 of file G4AllITFinder.cc
References G4VITFinder::GetITType().
void G4AllITFinder::SetVerboseLevel (G4int level) inline
Set General verbose for all IT Manager See ITManager builder
Definition at line 92 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4AllITFinder.hh
References fVerbose.
void G4AllITFinder::UpdatePositionMap ()
Definition at line 76 of file G4AllITFinder.cc.
View newest version in sPHENIX GitHub at line 76 of file G4AllITFinder.cc
References it.
Member Data Documentation
std::map<G4ITType, G4VITFinder*> G4AllITFinder::fITSubManager private
Definition at line 120 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 120 of file G4AllITFinder.hh
G4ThreadLocal G4AllITFinder * G4AllITFinder::fpInstance = 0 static private
Definition at line 119 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 119 of file G4AllITFinder.hh
int G4AllITFinder::fVerbose private
Definition at line 122 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 122 of file G4AllITFinder.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4AllITFinder.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4AllITFinder.cc