ECCE @ EIC Software: CLHEP::RanluxEngine Class Reference
CLHEP::RanluxEngine Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RanluxEngine.h>
Public Member Functions
RanluxEngine (std::istream &is)
RanluxEngine ()
RanluxEngine (long seed, int lux=3)
RanluxEngine (int rowIndex, int colIndex, int lux)
virtual ~RanluxEngine ()
double flat ()
void flatArray (const int size, double *vect)
void setSeed (long seed, int lux=3)
void setSeeds (const long *seeds, int lux=3)
void saveStatus (const char filename[]="Ranlux.conf") const
void restoreStatus (const char filename[]="Ranlux.conf")
void showStatus () const
int getLuxury () const
operator double ()
operator float ()
operator unsigned int ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Public Attributes
static const unsigned int VECTOR_STATE_SIZE = 31
Private Attributes
int nskip
int luxury
float float_seed_table [24]
int i_lag
int j_lag
float carry
int count24
Static Private Attributes
static const int int_modulus = 0x1000000
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Definition at line 44 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 44 of file RanluxEngine.h
Constructor & Destructor Documentation
CLHEP::RanluxEngine::RanluxEngine (std::istream & is)
Definition at line 118 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 118 of file RanluxEngine.cc
CLHEP::RanluxEngine::RanluxEngine ()
Definition at line 75 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 75 of file RanluxEngine.cc
References kdfinder::abs(), CLHEP::HepRandom::getTheTableSeeds(), luxury, mask, seed, setSeed(), setSeeds(), and CLHEP::HepRandomEngine::theSeed.
CLHEP::RanluxEngine::RanluxEngine (long seed, int lux = 3)
Definition at line 61 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 61 of file RanluxEngine.cc
References CLHEP::lux, luxury, setSeed(), setSeeds(), and CLHEP::HepRandomEngine::theSeed.
CLHEP::RanluxEngine::RanluxEngine (int rowIndex, int colIndex, int lux)
Definition at line 97 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 97 of file RanluxEngine.cc
References kdfinder::abs(), col, CLHEP::HepRandom::getTheTableSeeds(), CLHEP::lux, luxury, mask, seed, setSeed(), setSeeds(), and CLHEP::HepRandomEngine::theSeed.
CLHEP::RanluxEngine::~RanluxEngine () virtual
Definition at line 124 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 124 of file RanluxEngine.cc
Member Function Documentation
std::string CLHEP::RanluxEngine::beginTag () static
Definition at line 473 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 473 of file RanluxEngine.cc
static std::string CLHEP::RanluxEngine::engineName () inline static
Definition at line 103 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 103 of file RanluxEngine.h
Referenced by restoreStatus().
double CLHEP::RanluxEngine::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 310 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 310 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, j_lag, CLHEP::HepRandomEngine::mantissa_bit_12(), CLHEP::HepRandomEngine::mantissa_bit_24(), and nskip.
void CLHEP::RanluxEngine::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 360 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 360 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, j_lag, CLHEP::HepRandomEngine::mantissa_bit_12(), CLHEP::HepRandomEngine::mantissa_bit_24(), and nskip.
std::istream & CLHEP::RanluxEngine::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 455 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 455 of file RanluxEngine.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::RanluxEngine::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 518 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 518 of file RanluxEngine.cc
References getState().
int CLHEP::RanluxEngine::getLuxury () const inline
Definition at line 90 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 90 of file RanluxEngine.h
References luxury.
Referenced by G4WorkerRunManager::G4WorkerRunManager(), and G4UserWorkerThreadInitialization::SetupRNGEngine().
std::istream & CLHEP::RanluxEngine::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 477 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 477 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, j_lag, luxury, CLHEP::MarkerLen, nskip, CLHEP::possibleKeywordInput(), CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
Referenced by get(), and restoreStatus().
bool CLHEP::RanluxEngine::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 527 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 527 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, j_lag, luxury, CLHEP::HepRandomEngine::mantissa_bit_24(), nskip, and VECTOR_STATE_SIZE.
std::string CLHEP::RanluxEngine::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 59 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 59 of file RanluxEngine.cc
CLHEP::RanluxEngine::operator double () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 413 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 413 of file RanluxEngine.cc
References G4AblaRandom::flat().
CLHEP::RanluxEngine::operator float () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 417 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 417 of file RanluxEngine.cc
References G4AblaRandom::flat().
CLHEP::RanluxEngine::operator unsigned int () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 421 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 421 of file RanluxEngine.cc
References G4AblaRandom::flat(), and int().
std::ostream & CLHEP::RanluxEngine::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 428 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 428 of file RanluxEngine.cc
References put(), and v.
std::vector< unsigned long > CLHEP::RanluxEngine::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 439 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 439 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, j_lag, luxury, CLHEP::HepRandomEngine::mantissa_bit_24(), nskip, and v.
Referenced by put(), and saveStatus().
void CLHEP::RanluxEngine::restoreStatus (const char filename[] = "Ranlux.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 260 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 260 of file RanluxEngine.cc
References carry, CLHEP::HepRandomEngine::checkFile(), count24, engineName(), float_seed_table, getState(), i_lag, in, j_lag, luxury, nskip, CLHEP::possibleKeywordInput(), CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
void CLHEP::RanluxEngine::saveStatus (const char filename[] = "Ranlux.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 248 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 248 of file RanluxEngine.cc
References put(), and v.
void CLHEP::RanluxEngine::setSeed (long seed, int lux = 3) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 126 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 126 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, int_modulus, j_lag, CLHEP::lux, luxury, CLHEP::HepRandomEngine::mantissa_bit_24(), nskip, seed, and CLHEP::HepRandomEngine::theSeed.
Referenced by RanluxEngine(), and setSeeds().
void CLHEP::RanluxEngine::setSeeds (const long * seeds, int lux = 3) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 182 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 182 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, int_modulus, j_lag, CLHEP::lux, luxury, CLHEP::HepRandomEngine::mantissa_bit_24(), nskip, setSeed(), CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
Referenced by RanluxEngine().
void CLHEP::RanluxEngine::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 295 of file RanluxEngine.cc.
View newest version in sPHENIX GitHub at line 295 of file RanluxEngine.cc
References carry, count24, float_seed_table, i_lag, j_lag, luxury, nskip, and CLHEP::HepRandomEngine::theSeed.
Member Data Documentation
float CLHEP::RanluxEngine::carry private
Definition at line 116 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 116 of file RanluxEngine.h
Referenced by flat(), flatArray(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
int CLHEP::RanluxEngine::count24 private
Definition at line 117 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 117 of file RanluxEngine.h
Referenced by flat(), flatArray(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
float CLHEP::RanluxEngine::float_seed_table[24] private
Definition at line 114 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 114 of file RanluxEngine.h
Referenced by flat(), flatArray(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
int CLHEP::RanluxEngine::i_lag private
Definition at line 115 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 115 of file RanluxEngine.h
Referenced by flat(), flatArray(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
const int CLHEP::RanluxEngine::int_modulus = 0x1000000 static private
Definition at line 118 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 118 of file RanluxEngine.h
Referenced by setSeed(), and setSeeds().
int CLHEP::RanluxEngine::j_lag private
Definition at line 115 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 115 of file RanluxEngine.h
Referenced by flat(), flatArray(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
int CLHEP::RanluxEngine::luxury private
Definition at line 113 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 113 of file RanluxEngine.h
Referenced by getLuxury(), getState(), put(), RanluxEngine(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
int CLHEP::RanluxEngine::nskip private
Definition at line 113 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 113 of file RanluxEngine.h
Referenced by flat(), flatArray(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
const unsigned int CLHEP::RanluxEngine::VECTOR_STATE_SIZE = 31 static
Definition at line 109 of file RanluxEngine.h.
View newest version in sPHENIX GitHub at line 109 of file RanluxEngine.h
Referenced by getState(), and restoreStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RanluxEngine.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RanluxEngine.cc