ECCE @ EIC Software: G4VGraphicsSystem Class Reference
G4VGraphicsSystem Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VGraphicsSystem.hh>
Public Types
enum Functionality {
noFunctionality, nonEuclidian, twoD, twoDStore,
threeD, threeDInteractive, virtualReality, fileWriter
}
Public Member Functions
G4VGraphicsSystem (const G4String &name, Functionality f)
G4VGraphicsSystem (const G4String &name, const G4String &nickname, Functionality f)
G4VGraphicsSystem (const G4String &name, const G4String &nickname, const G4String &description, Functionality f)
virtual ~G4VGraphicsSystem ()
virtual G4VSceneHandler * CreateSceneHandler (const G4String &name)=0
virtual G4VViewer * CreateViewer (G4VSceneHandler &, const G4String &name)=0
const G4String & GetName () const
const G4String & GetNickname () const
const std::vector< G4String > & GetNicknames () const
const G4String & GetDescription () const
Functionality GetFunctionality () const
virtual G4bool IsUISessionCompatible () const
void AddNickname (const G4String &nickname)
Protected Attributes
G4String fName
std::vector< G4String > fNicknames
G4String fDescription
Functionality fFunctionality
Detailed Description
Definition at line 45 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VGraphicsSystem.hh
Member Enumeration Documentation
enum G4VGraphicsSystem::Functionality
Enumerator:
noFunctionality
nonEuclidian
twoD
twoDStore
threeD
threeDInteractive
virtualReality
fileWriter
Definition at line 49 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VGraphicsSystem.hh
Constructor & Destructor Documentation
G4VGraphicsSystem::G4VGraphicsSystem (const G4String & name, Functionality f)
Definition at line 38 of file G4VGraphicsSystem.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VGraphicsSystem.cc
References fNicknames.
G4VGraphicsSystem::G4VGraphicsSystem (const G4String & name, const G4String & nickname, Functionality f)
Definition at line 47 of file G4VGraphicsSystem.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VGraphicsSystem.cc
References fNicknames.
G4VGraphicsSystem::G4VGraphicsSystem (const G4String & name, const G4String & nickname, const G4String & description, Functionality f)
Definition at line 57 of file G4VGraphicsSystem.cc.
View newest version in sPHENIX GitHub at line 57 of file G4VGraphicsSystem.cc
References fNicknames.
G4VGraphicsSystem::~G4VGraphicsSystem () virtual
Definition at line 36 of file G4VGraphicsSystem.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VGraphicsSystem.cc
Member Function Documentation
void G4VGraphicsSystem::AddNickname (const G4String & nickname) inline
Definition at line 85 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VGraphicsSystem.hh
References fNicknames.
virtual G4VSceneHandler* G4VGraphicsSystem::CreateSceneHandler (const G4String & name) pure virtual
Implemented in G4GMocrenFile, G4RayTracer, G4DAWNFILE, G4HepRepFile, G4OpenInventor, G4ASCIITree, G4OpenGLImmediateWt, G4VRML1File, G4VRML2File, G4XXX, G4XXXFile, G4XXXSG, G4XXXStored, G4HepRep, G4OpenGLImmediateX, G4OpenGLImmediateXm, G4OpenGLStoredX, G4OpenGLStoredXm, G4OpenGLImmediateQt, G4OpenGLImmediateWin32, G4OpenGLStoredQt, and G4OpenGLStoredWin32.
virtual G4VViewer* G4VGraphicsSystem::CreateViewer (G4VSceneHandler & , const G4String & name) pure virtual
Implemented in G4GMocrenFile, G4RayTracer, G4DAWNFILE, G4HepRepFile, G4ASCIITree, G4OpenGLImmediateWt, G4OpenInventorXtExtended, G4VRML1File, G4VRML2File, G4XXX, G4XXXFile, G4XXXSG, G4XXXStored, G4HepRep, G4OpenGLImmediateX, G4OpenGLImmediateXm, G4OpenGLStoredX, G4OpenGLStoredXm, G4OpenInventorXt, G4OpenGLImmediateQt, G4OpenGLImmediateWin32, G4OpenGLStoredQt, G4OpenGLStoredWin32, and G4OpenInventorWin.
const G4String& G4VGraphicsSystem::GetDescription () const inline
Definition at line 82 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VGraphicsSystem.hh
References fDescription.
Referenced by operator<<().
Functionality G4VGraphicsSystem::GetFunctionality () const inline
Definition at line 83 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 83 of file G4VGraphicsSystem.hh
References fFunctionality.
Referenced by G4VisManager::EndOfRun(), and operator<<().
const G4String& G4VGraphicsSystem::GetName (void) const inline
Definition at line 79 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VGraphicsSystem.hh
References fName.
Referenced by G4VSceneHandler::G4VSceneHandler(), and operator<<().
const G4String& G4VGraphicsSystem::GetNickname () const inline
Definition at line 80 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VGraphicsSystem.hh
References fNicknames.
Referenced by G4VisCommandViewerList::SetNewValue().
const std::vector<G4String>& G4VGraphicsSystem::GetNicknames () const inline
Definition at line 81 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VGraphicsSystem.hh
References fNicknames.
Referenced by operator<<().
G4bool G4VGraphicsSystem::IsUISessionCompatible () const virtual
Reimplemented in G4OpenInventor, G4OpenGLQt, and G4OpenGLXm.
Definition at line 68 of file G4VGraphicsSystem.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VGraphicsSystem.cc
Member Data Documentation
G4String G4VGraphicsSystem::fDescription protected
Definition at line 90 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VGraphicsSystem.hh
Referenced by GetDescription().
Functionality G4VGraphicsSystem::fFunctionality protected
Definition at line 91 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VGraphicsSystem.hh
Referenced by GetFunctionality().
G4String G4VGraphicsSystem::fName protected
Definition at line 88 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VGraphicsSystem.hh
Referenced by GetName().
std::vector<G4String> G4VGraphicsSystem::fNicknames protected
Definition at line 89 of file G4VGraphicsSystem.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VGraphicsSystem.hh
Referenced by AddNickname(), G4VGraphicsSystem(), GetNickname(), and GetNicknames().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VGraphicsSystem.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VGraphicsSystem.cc