ECCE @ EIC Software: G4Paraboloid Class Reference
G4Paraboloid Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Paraboloid.hh>
Public Member Functions
G4Paraboloid (const G4String &pName, G4double pDz, G4double pR1, G4double pR2)
virtual ~G4Paraboloid ()
G4double GetZHalfLength () const
G4double GetRadiusMinusZ () const
G4double GetRadiusPlusZ () const
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
G4double CalculateSurfaceArea () const
void SetZHalfLength (G4double dz)
void SetRadiusMinusZ (G4double R1)
void SetRadiusPlusZ (G4double R2)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4ThreeVector GetPointOnSurface () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Polyhedron * GetPolyhedron () const
G4Paraboloid (__void__ &)
G4Paraboloid (const G4Paraboloid &rhs)
G4Paraboloid & operator= (const G4Paraboloid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Attributes
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Private Attributes
G4double fSurfaceArea = 0.0
G4double fCubicVolume = 0.0
G4double dz
G4double r1
G4double r2
G4double k1
G4double k2
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Detailed Description
Definition at line 67 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 67 of file G4Paraboloid.hh
Constructor & Destructor Documentation
G4Paraboloid::G4Paraboloid (const G4String & pName, G4double pDz, G4double pR1, G4double pR2)
Definition at line 62 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 62 of file G4Paraboloid.cc
References dz, FatalErrorInArgument, G4Exception(), G4VSolid::GetName(), k1, k2, message(), r1, and r2.
Referenced by Clone().
G4Paraboloid::~G4Paraboloid () virtual
Definition at line 105 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 105 of file G4Paraboloid.cc
References fpPolyhedron.
G4Paraboloid::G4Paraboloid (__void__ & a)
Definition at line 96 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 96 of file G4Paraboloid.cc
G4Paraboloid::G4Paraboloid (const G4Paraboloid & rhs)
Definition at line 114 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 114 of file G4Paraboloid.cc
Member Function Documentation
void G4Paraboloid::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 149 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 149 of file G4Paraboloid.cc
References G4VSolid::DumpInfo(), dz, G4Exception(), G4VSolid::GetName(), JustWarning, message(), pMax, r2, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Paraboloid::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 175 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 175 of file G4Paraboloid.cc
References BoundingLimits(), and G4BoundingEnvelope::CalculateExtent().
G4double G4Paraboloid::CalculateSurfaceArea () const inline
Referenced by GetPointOnSurface().
G4VSolid * G4Paraboloid::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 861 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 861 of file G4Paraboloid.cc
References G4Paraboloid().
G4Polyhedron * G4Paraboloid::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 927 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 927 of file G4Paraboloid.cc
References dz, r1, r2, and twopi.
Referenced by GetPolyhedron().
void G4Paraboloid::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 922 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 922 of file G4Paraboloid.cc
References G4VGraphicsScene::AddSolid().
G4double G4Paraboloid::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 331 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 331 of file G4Paraboloid.cc
References A(), B(), dz, G4endl, G4Exception(), G4VSolid::GetName(), Inside(), JustWarning, k1, k2, G4VSolid::kCarTolerance, kInfinity, kInside, message(), mm, CLHEP::normal(), CLHEP::Hep3Vector::perp2(), r1, r2, sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Paraboloid::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 464 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 464 of file G4Paraboloid.cc
References dz, k1, k2, kInfinity, r2, tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Paraboloid::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 500 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 500 of file G4Paraboloid.cc
References A(), B(), CLHEP::Hep3Vector::dot(), dz, G4endl, G4Exception(), Inside(), JustWarning, k1, k2, G4VSolid::kCarTolerance, kInfinity, kOutside, message(), CLHEP::normal(), CLHEP::Hep3Vector::perp2(), r, r1, r2, sqr(), CLHEP::Hep3Vector::unit(), v, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Paraboloid::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 811 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 811 of file G4Paraboloid.cc
References G4VSolid::DumpInfo(), dz, G4cout, G4endl, G4Exception(), Inside(), JustWarning, G4VSolid::kCarTolerance, kOutside, message(), mm, CLHEP::Hep3Vector::perp(), r1, r2, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Paraboloid::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
G4GeometryType G4Paraboloid::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 852 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 852 of file G4Paraboloid.cc
G4ThreeVector G4Paraboloid::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 891 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 891 of file G4Paraboloid.cc
References A(), CalculateSurfaceArea(), dz, fSurfaceArea, k1, k2, phi, pi, r1, r2, G4INCL::DeJongSpin::shoot(), sqr(), twopi, and z.
G4Polyhedron * G4Paraboloid::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 932 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 932 of file G4Paraboloid.cc
References CreatePolyhedron(), fpPolyhedron, fRebuildPolyhedron, HepPolyhedron::GetNumberOfRotationSteps(), G4Polyhedron::GetNumberOfRotationStepsAtTimeOfCreation(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4double G4Paraboloid::GetRadiusMinusZ () const inline
Referenced by PHG4GDMLWriteSolids::ParaboloidWrite(), and G4GDMLWriteSolids::ParaboloidWrite().
G4double G4Paraboloid::GetRadiusPlusZ () const inline
Referenced by PHG4GDMLWriteSolids::ParaboloidWrite(), and G4GDMLWriteSolids::ParaboloidWrite().
G4double G4Paraboloid::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
G4double G4Paraboloid::GetZHalfLength () const inline
Referenced by PHG4GDMLWriteSolids::ParaboloidWrite(), and G4GDMLWriteSolids::ParaboloidWrite().
EInside G4Paraboloid::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 194 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 194 of file G4Paraboloid.cc
References A(), dz, k1, k2, G4VSolid::kCarTolerance, kInside, kOutside, kSurface, CLHEP::Hep3Vector::perp2(), sqr(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToIn(), and DistanceToOut().
G4Paraboloid & G4Paraboloid::operator= (const G4Paraboloid & rhs)
Definition at line 125 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 125 of file G4Paraboloid.cc
References dz, fCubicVolume, fpPolyhedron, fRebuildPolyhedron, fSurfaceArea, k1, k2, G4VSolid::operator=(), r1, and r2.
void G4Paraboloid::SetRadiusMinusZ (G4double R1) inline
void G4Paraboloid::SetRadiusPlusZ (G4double R2) inline
void G4Paraboloid::SetZHalfLength (G4double dz) inline
std::ostream & G4Paraboloid::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 870 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 870 of file G4Paraboloid.cc
References dz, G4VSolid::GetName(), mm, r1, and r2.
G4ThreeVector G4Paraboloid::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 237 of file G4Paraboloid.cc.
View newest version in sPHENIX GitHub at line 237 of file G4Paraboloid.cc
References A(), dz, G4endl, G4Exception(), JustWarning, k1, k2, G4VSolid::kCarTolerance, CLHEP::Hep3Vector::mag2(), message(), mm, n, CLHEP::Hep3Vector::perp2(), r1, r2, sqr(), CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Paraboloid::dz private
Definition at line 150 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Paraboloid.hh
Referenced by BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Paraboloid(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Paraboloid::fCubicVolume = 0.0 private
Definition at line 148 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 148 of file G4Paraboloid.hh
Referenced by operator=().
G4Polyhedron* G4Paraboloid::fpPolyhedron = nullptr mutable protected
Definition at line 141 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 141 of file G4Paraboloid.hh
Referenced by GetPolyhedron(), operator=(), and ~G4Paraboloid().
G4bool G4Paraboloid::fRebuildPolyhedron = false mutable protected
Definition at line 140 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 140 of file G4Paraboloid.hh
Referenced by GetPolyhedron(), and operator=().
G4double G4Paraboloid::fSurfaceArea = 0.0 mutable private
Definition at line 147 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 147 of file G4Paraboloid.hh
Referenced by GetPointOnSurface(), and operator=().
G4double G4Paraboloid::k1 private
Definition at line 151 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 151 of file G4Paraboloid.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Paraboloid(), GetPointOnSurface(), Inside(), operator=(), and SurfaceNormal().
G4double G4Paraboloid::k2 private
Definition at line 151 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 151 of file G4Paraboloid.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Paraboloid(), GetPointOnSurface(), Inside(), operator=(), and SurfaceNormal().
G4double G4Paraboloid::r1 private
Definition at line 150 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Paraboloid.hh
Referenced by CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Paraboloid(), GetPointOnSurface(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Paraboloid::r2 private
Definition at line 150 of file G4Paraboloid.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Paraboloid.hh
Referenced by BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Paraboloid(), GetPointOnSurface(), operator=(), StreamInfo(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Paraboloid.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4Paraboloid.cc