ECCE @ EIC Software: RE02Run Class Reference
RE02Run Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/include/RE02Run.hh>
Public Member Functions
RE02Run (const std::vector< G4String > mfdName)
virtual ~RE02Run ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4int GetNumberOfHitsMap () const
G4THitsMap< G4double > * GetHitsMap (G4int i)
G4THitsMap< G4double > * GetHitsMap (const G4String &detName, const G4String &colName)
G4THitsMap< G4double > * GetHitsMap (const G4String &fullName)
void DumpAllScorer ()
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
std::vector< G4String > fCollName
std::vector< G4int > fCollID
std::vector< G4THitsMap
< G4double > * > fRunMap
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
User run class
(Description) An example implementation for the multi-functional-detector and primitive scorers. This RE02Run class has collections which accumulate event information into run information.
constructor gets HitsCollection names, collection IDs and HitsMaps of primitive scorers from the muti-functional detector
void RecordEvent(const G4Event*) accumulates HitsMaps over all events into a run HitsMap
G4int GetNumberOfHitsMap() const gets the size of the run HitsMap
G4THitsMap<G4double>* GetHitsMap(G4int i) gets a run HitsMap of the i-th primitive scorer
G4THitsMap<G4double>* GetHitsMap(const G4String& detName, const G4String& colName) gets a run HitsMap with the detName and the colName
G4THitsMap<G4double>* GetHitsMap(const G4String& fullName) gets a run HitsMap with the fullName
void DumpAllScorer() shows all HitsMap information of this run. This method calls G4THisMap::PrintAll() for individual HitsMap.
Definition at line 74 of file RE02Run.hh.
View newest version in sPHENIX GitHub at line 74 of file RE02Run.hh
Constructor & Destructor Documentation
RE02Run::RE02Run (const std::vector< G4String > mfdName)
Definition at line 69 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 69 of file RE02Run.cc
References fCollID, fCollName, G4SDManager::FindSensitiveDetector(), fRunMap, G4cout, G4endl, G4SDManager::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4MultiFunctionalDetector::GetNumberOfPrimitives(), G4MultiFunctionalDetector::GetPrimitive(), and G4SDManager::GetSDMpointer().
RE02Run::~RE02Run () virtual
Definition at line 117 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 117 of file RE02Run.cc
References fCollID, fCollName, and fRunMap.
Member Function Documentation
void RE02Run::DumpAllScorer ()
Definition at line 215 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 215 of file RE02Run.cc
References G4VTHitsMap< T, Map_t >::entries(), G4cout, G4endl, GetHitsMap(), G4VHitsCollection::GetName(), GetNumberOfHitsMap(), G4VHitsCollection::GetSDname(), and n.
Referenced by RE02RunAction::EndOfRunAction().
G4THitsMap<G4double>* RE02Run::GetHitsMap (G4int i) inline
Definition at line 95 of file RE02Run.hh.
View newest version in sPHENIX GitHub at line 95 of file RE02Run.hh
References fRunMap.
Referenced by DumpAllScorer(), RE02RunAction::EndOfRunAction(), and GetHitsMap().
G4THitsMap< G4double > * RE02Run::GetHitsMap (const G4String & detName, const G4String & colName)
Definition at line 188 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 188 of file RE02Run.cc
References GetHitsMap().
G4THitsMap< G4double > * RE02Run::GetHitsMap (const G4String & fullName)
Definition at line 200 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 200 of file RE02Run.cc
References fCollName, and fRunMap.
G4int RE02Run::GetNumberOfHitsMap () const inline
Definition at line 91 of file RE02Run.hh.
View newest version in sPHENIX GitHub at line 91 of file RE02Run.hh
References fRunMap.
Referenced by DumpAllScorer().
void RE02Run::Merge (const G4Run * aRun) virtual
Reimplemented from G4Run.
Definition at line 165 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 165 of file RE02Run.cc
References fCollID, fRunMap, and G4Run::Merge().
void RE02Run::RecordEvent (const G4Event * aEvent) virtual
Reimplemented from G4Run.
Definition at line 134 of file RE02Run.cc.
View newest version in sPHENIX GitHub at line 134 of file RE02Run.cc
References fCollID, fRunMap, G4cout, G4endl, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), and G4Run::numberOfEvent.
Member Data Documentation
std::vector<G4int> RE02Run::fCollID private
Definition at line 105 of file RE02Run.hh.
View newest version in sPHENIX GitHub at line 105 of file RE02Run.hh
Referenced by Merge(), RE02Run(), RecordEvent(), and ~RE02Run().
std::vector<G4String> RE02Run::fCollName private
Definition at line 104 of file RE02Run.hh.
View newest version in sPHENIX GitHub at line 104 of file RE02Run.hh
Referenced by GetHitsMap(), RE02Run(), and ~RE02Run().
std::vector<G4THitsMap<G4double>*> RE02Run::fRunMap private
Definition at line 106 of file RE02Run.hh.
View newest version in sPHENIX GitHub at line 106 of file RE02Run.hh
Referenced by GetHitsMap(), GetNumberOfHitsMap(), Merge(), RE02Run(), RecordEvent(), and ~RE02Run().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/include/RE02Run.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/src/RE02Run.cc