ECCE @ EIC Software: G4HadronInelasticDataSet Class Reference
G4HadronInelasticDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronInelasticDataSet.hh>
Public Member Functions
G4HadronInelasticDataSet (const G4String &name="GheishaInelastic")
virtual ~G4HadronInelasticDataSet ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsElementApplicable (const G4DynamicParticle *aParticle, G4int, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *aParticle, G4int Z, const G4Material *)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4int theZ
G4double fInelasticXS
G4double fKinEnergy
const G4ParticleDefinition * fParticle
G4HadronCrossSections * fGheishaXS
G4NistManager * fNIST
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 44 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 44 of file G4HadronInelasticDataSet.hh
Constructor & Destructor Documentation
G4HadronInelasticDataSet::G4HadronInelasticDataSet (const G4String & name = "GheishaInelastic")
Definition at line 39 of file G4HadronInelasticDataSet.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HadronInelasticDataSet.cc
References fGheishaXS, fNIST, G4HadronCrossSections::Instance(), and G4NistManager::Instance().
G4HadronInelasticDataSet::~G4HadronInelasticDataSet () virtual
Definition at line 47 of file G4HadronInelasticDataSet.cc.
View newest version in sPHENIX GitHub at line 47 of file G4HadronInelasticDataSet.cc
Member Function Documentation
void G4HadronInelasticDataSet::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 49 of file G4HadronInelasticDataSet.cc.
View newest version in sPHENIX GitHub at line 49 of file G4HadronInelasticDataSet.cc
G4double G4HadronInelasticDataSet::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 66 of file G4HadronInelasticDataSet.cc.
View newest version in sPHENIX GitHub at line 66 of file G4HadronInelasticDataSet.cc
References A(), fGheishaXS, fInelasticXS, fKinEnergy, fNIST, fParticle, G4lrint(), G4NistManager::GetAtomicMassAmu(), G4DynamicParticle::GetDefinition(), G4HadronCrossSections::GetInelasticCrossSection(), G4DynamicParticle::GetKineticEnergy(), theZ, and Z.
G4bool G4HadronInelasticDataSet::IsElementApplicable (const G4DynamicParticle * aParticle, G4int , const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 59 of file G4HadronInelasticDataSet.cc.
View newest version in sPHENIX GitHub at line 59 of file G4HadronInelasticDataSet.cc
Member Data Documentation
G4HadronCrossSections* G4HadronInelasticDataSet::fGheishaXS private
Definition at line 68 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HadronInelasticDataSet.hh
Referenced by G4HadronInelasticDataSet(), and GetElementCrossSection().
G4double G4HadronInelasticDataSet::fInelasticXS private
Definition at line 65 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 65 of file G4HadronInelasticDataSet.hh
Referenced by GetElementCrossSection().
G4double G4HadronInelasticDataSet::fKinEnergy private
Definition at line 66 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 66 of file G4HadronInelasticDataSet.hh
Referenced by GetElementCrossSection().
G4NistManager* G4HadronInelasticDataSet::fNIST private
Definition at line 69 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 69 of file G4HadronInelasticDataSet.hh
Referenced by G4HadronInelasticDataSet(), and GetElementCrossSection().
const G4ParticleDefinition* G4HadronInelasticDataSet::fParticle private
Definition at line 67 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HadronInelasticDataSet.hh
Referenced by GetElementCrossSection().
G4int G4HadronInelasticDataSet::theZ private
Definition at line 64 of file G4HadronInelasticDataSet.hh.
View newest version in sPHENIX GitHub at line 64 of file G4HadronInelasticDataSet.hh
Referenced by GetElementCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronInelasticDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4HadronInelasticDataSet.cc