ECCE @ EIC Software: CML2Accelerator Class Reference
CML2Accelerator Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Accelerator.hh>
Public Member Functions
CML2Accelerator (void)
virtual ~CML2Accelerator (void)
virtual void Construct (G4VPhysicalVolume *PVWorld, G4double iso)
void reset ()
void setJaw1X (G4double val)
void setJaw2X (G4double val)
void setJaw1Y (G4double val)
void setJaw2Y (G4double val)
void setIsoCentre (G4double val)
void setidEnergy (G4int val)
void setLeavesAx (G4double val)
void setLeavesBx (G4double val)
int getidEnergy ()
virtual G4double getBeforeJaws_Z_PhaseSpacePosition ()
virtual void writeInfo ()
Public Attributes
G4double jaw1XAperture
G4double jaw2XAperture
G4double jaw1YAperture
G4double jaw2YAperture
G4double isoCentre
std::vector< G4double > vec_leavesA
std::vector< G4double > vec_leavesB
G4int idEnergy
Detailed Description
Definition at line 62 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 62 of file ML2Accelerator.hh
Constructor & Destructor Documentation
CML2Accelerator::CML2Accelerator (void)
Definition at line 47 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 47 of file ML2Accelerator.cc
References idEnergy, isoCentre, jaw1XAperture, jaw1YAperture, jaw2XAperture, and jaw2YAperture.
CML2Accelerator::~CML2Accelerator (void) virtual
Definition at line 57 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 57 of file ML2Accelerator.cc
Member Function Documentation
void CML2Accelerator::Construct (G4VPhysicalVolume * PVWorld, G4double iso) virtual
Reimplemented in CML2Acc2, CML2Acc1, and CML2AccSaturn.
Definition at line 61 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 61 of file ML2Accelerator.cc
virtual G4double CML2Accelerator::getBeforeJaws_Z_PhaseSpacePosition () inline virtual
Reimplemented in CML2Acc2, CML2Acc1, and CML2AccSaturn.
Definition at line 78 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 78 of file ML2Accelerator.hh
int CML2Accelerator::getidEnergy ()
Definition at line 111 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 111 of file ML2Accelerator.cc
References idEnergy.
void CML2Accelerator::reset ()
Definition at line 65 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 65 of file ML2Accelerator.cc
References vec_leavesA, and vec_leavesB.
void CML2Accelerator::setidEnergy (G4int val)
Definition at line 96 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 96 of file ML2Accelerator.cc
References idEnergy.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void CML2Accelerator::setIsoCentre (G4double val)
Definition at line 91 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 91 of file ML2Accelerator.cc
References isoCentre.
void CML2Accelerator::setJaw1X (G4double val)
Definition at line 71 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 71 of file ML2Accelerator.cc
References jaw1XAperture.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void CML2Accelerator::setJaw1Y (G4double val)
Definition at line 81 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 81 of file ML2Accelerator.cc
References jaw1YAperture.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void CML2Accelerator::setJaw2X (G4double val)
Definition at line 76 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 76 of file ML2Accelerator.cc
References jaw2XAperture.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void CML2Accelerator::setJaw2Y (G4double val)
Definition at line 86 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 86 of file ML2Accelerator.cc
References jaw2YAperture.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void CML2Accelerator::setLeavesAx (G4double val)
Definition at line 101 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 101 of file ML2Accelerator.cc
References vec_leavesA.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void CML2Accelerator::setLeavesBx (G4double val)
Definition at line 106 of file ML2Accelerator.cc.
View newest version in sPHENIX GitHub at line 106 of file ML2Accelerator.cc
References vec_leavesB.
Referenced by CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
virtual void CML2Accelerator::writeInfo () inline virtual
Reimplemented in CML2Acc2, CML2Acc1, and CML2AccSaturn.
Definition at line 79 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2Accelerator.hh
Member Data Documentation
G4int CML2Accelerator::idEnergy
Definition at line 84 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2Accelerator.hh
Referenced by CML2Accelerator(), getidEnergy(), and setidEnergy().
G4double CML2Accelerator::isoCentre
Definition at line 82 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 82 of file ML2Accelerator.hh
Referenced by CML2Accelerator(), and setIsoCentre().
G4double CML2Accelerator::jaw1XAperture
Definition at line 79 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2Accelerator.hh
Referenced by CML2Accelerator(), and setJaw1X().
G4double CML2Accelerator::jaw1YAperture
Definition at line 79 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2Accelerator.hh
Referenced by CML2Accelerator(), and setJaw1Y().
G4double CML2Accelerator::jaw2XAperture
Definition at line 79 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2Accelerator.hh
Referenced by CML2Accelerator(), and setJaw2X().
G4double CML2Accelerator::jaw2YAperture
Definition at line 79 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2Accelerator.hh
Referenced by CML2Accelerator(), and setJaw2Y().
std::vector<G4double> CML2Accelerator::vec_leavesA
Definition at line 83 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 83 of file ML2Accelerator.hh
Referenced by reset(), and setLeavesAx().
std::vector<G4double> CML2Accelerator::vec_leavesB
Definition at line 83 of file ML2Accelerator.hh.
View newest version in sPHENIX GitHub at line 83 of file ML2Accelerator.hh
Referenced by reset(), and setLeavesBx().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Accelerator.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Accelerator.cc