ECCE @ EIC Software: B2aDetectorMessenger Class Reference
B2aDetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/include/B2aDetectorMessenger.hh>
Public Member Functions
B2aDetectorMessenger (B2aDetectorConstruction *)
virtual ~B2aDetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
B2aDetectorConstruction * fDetectorConstruction
G4UIdirectory * fB2Directory
G4UIdirectory * fDetDirectory
G4UIcmdWithAString * fTargMatCmd
G4UIcmdWithAString * fChamMatCmd
G4UIcmdWithADoubleAndUnit * fStepMaxCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Messenger class that defines commands for B2aDetectorConstruction.
It implements commands:
/B2/det/setTargetMaterial name
/B2/det/setChamberMaterial name
/B2/det/stepMax value unit
Definition at line 50 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file B2aDetectorMessenger.hh
Constructor & Destructor Documentation
B2aDetectorMessenger::B2aDetectorMessenger (B2aDetectorConstruction * Det)
Definition at line 39 of file B2aDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 39 of file B2aDetectorMessenger.cc
References G4UIcommand::AvailableForStates(), fB2Directory, fChamMatCmd, fDetDirectory, fStepMaxCmd, fTargMatCmd, G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
B2aDetectorMessenger::~B2aDetectorMessenger () virtual
Definition at line 68 of file B2aDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 68 of file B2aDetectorMessenger.cc
References fB2Directory, fChamMatCmd, fDetDirectory, fStepMaxCmd, and fTargMatCmd.
Member Function Documentation
void B2aDetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 79 of file B2aDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 79 of file B2aDetectorMessenger.cc
References fChamMatCmd, fDetectorConstruction, fStepMaxCmd, fTargMatCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), B2aDetectorConstruction::SetChamberMaterial(), B2aDetectorConstruction::SetMaxStep(), and B2aDetectorConstruction::SetTargetMaterial().
Member Data Documentation
G4UIdirectory* B2aDetectorMessenger::fB2Directory private
Definition at line 61 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file B2aDetectorMessenger.hh
Referenced by B2aDetectorMessenger(), and ~B2aDetectorMessenger().
G4UIcmdWithAString* B2aDetectorMessenger::fChamMatCmd private
Definition at line 65 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file B2aDetectorMessenger.hh
Referenced by B2aDetectorMessenger(), SetNewValue(), and ~B2aDetectorMessenger().
G4UIdirectory* B2aDetectorMessenger::fDetDirectory private
Definition at line 62 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file B2aDetectorMessenger.hh
Referenced by B2aDetectorMessenger(), and ~B2aDetectorMessenger().
B2aDetectorConstruction* B2aDetectorMessenger::fDetectorConstruction private
Definition at line 59 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file B2aDetectorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit* B2aDetectorMessenger::fStepMaxCmd private
Definition at line 67 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file B2aDetectorMessenger.hh
Referenced by B2aDetectorMessenger(), SetNewValue(), and ~B2aDetectorMessenger().
G4UIcmdWithAString* B2aDetectorMessenger::fTargMatCmd private
Definition at line 64 of file B2aDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file B2aDetectorMessenger.hh
Referenced by B2aDetectorMessenger(), SetNewValue(), and ~B2aDetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/include/B2aDetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/src/B2aDetectorMessenger.cc