ECCE @ EIC Software: G4ErrorPlaneSurfaceTarget Class Reference
G4ErrorPlaneSurfaceTarget Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4ErrorPlaneSurfaceTarget.hh>
Public Member Functions
G4ErrorPlaneSurfaceTarget (G4double a=0., G4double b=0., G4double c=0., G4double d=0.)
G4ErrorPlaneSurfaceTarget (const G4Normal3D &n, const G4Point3D &p)
G4ErrorPlaneSurfaceTarget (const G4Point3D &p1, const G4Point3D &p2, const G4Point3D &p3)
~G4ErrorPlaneSurfaceTarget ()
virtual G4ThreeVector Intersect (const G4ThreeVector &point, const G4ThreeVector &direc) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &point, const G4ThreeVector &direc) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &pt) const
virtual G4Plane3D GetTangentPlane (const G4ThreeVector &point) const
virtual void Dump (const G4String &msg) const
Public Member Functions inherited from G4ErrorSurfaceTarget
G4ErrorSurfaceTarget ()
virtual ~G4ErrorSurfaceTarget ()
Public Member Functions inherited from G4ErrorTanPlaneTarget
G4ErrorTanPlaneTarget ()
virtual ~G4ErrorTanPlaneTarget ()
Public Member Functions inherited from G4ErrorTarget
G4ErrorTarget ()
virtual ~G4ErrorTarget ()
virtual G4bool TargetReached (const G4Step *)
G4ErrorTargetType GetType () const
Additional Inherited Members
Protected Attributes inherited from G4ErrorTarget
G4ErrorTargetType theType
Private Member Functions inherited from HepGeom::Plane3D< T >
Plane3D ()
Plane3D (T a1, T b1, T c1, T d1)
Plane3D (const Normal3D< T > &n, const Point3D< T > &p)
Plane3D (const Point3D< T > &p1, const Point3D< T > &p2, const Point3D< T > &p3)
Plane3D (const Plane3D< T > &)=default
template<typename U = T, typename = typename std::enable_if<!std::is_same<U,float>::value >::type>
Plane3D (const Plane3D< float > &p)
Plane3D (Plane3D< T > &&)=default
~Plane3D ()=default
Plane3D< T > & operator= (const Plane3D< T > &)=default
Plane3D< T > & operator= (Plane3D< T > &&)=default
T a () const
T b () const
T c () const
T d () const
Normal3D< T > normal () const
Plane3D< T > & normalize ()
T distance (const Point3D< T > &p) const
Point3D< T > point (const Point3D< T > &p) const
Point3D< T > point () const
bool operator== (const Plane3D< T > &p) const
bool operator!= (const Plane3D< T > &p) const
Plane3D< T > & transform (const Transform3D &m)
Related Functions inherited from HepGeom::Plane3D< T >
std::ostream & operator<< (std::ostream &os, const Plane3D< float > &p)
std::ostream & operator<< (std::ostream &os, const Plane3D< double > &p)
Detailed Description
Definition at line 42 of file G4ErrorPlaneSurfaceTarget.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ErrorPlaneSurfaceTarget.hh
Constructor & Destructor Documentation
G4ErrorPlaneSurfaceTarget::G4ErrorPlaneSurfaceTarget (G4double a = 0., G4double b = 0., G4double c = 0., G4double d = 0.)
Definition at line 43 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ErrorPlaneSurfaceTarget.cc
References Dump(), G4ErrorTarget_PlaneSurface, G4ErrorTarget::theType, and G4ErrorPropagatorData::verbose().
G4ErrorPlaneSurfaceTarget::G4ErrorPlaneSurfaceTarget (const G4Normal3D & n, const G4Point3D & p)
Definition at line 59 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ErrorPlaneSurfaceTarget.cc
References Dump(), G4ErrorTarget_PlaneSurface, G4ErrorTarget::theType, and G4ErrorPropagatorData::verbose().
G4ErrorPlaneSurfaceTarget::G4ErrorPlaneSurfaceTarget (const G4Point3D & p1, const G4Point3D & p2, const G4Point3D & p3)
Definition at line 75 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ErrorPlaneSurfaceTarget.cc
References Dump(), G4ErrorTarget_PlaneSurface, G4ErrorTarget::theType, and G4ErrorPropagatorData::verbose().
G4ErrorPlaneSurfaceTarget::~G4ErrorPlaneSurfaceTarget ()
Definition at line 92 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ErrorPlaneSurfaceTarget.cc
Member Function Documentation
void G4ErrorPlaneSurfaceTarget::Dump (const G4String & msg) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 172 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 172 of file G4ErrorPlaneSurfaceTarget.cc
References G4cout, G4endl, HepGeom::Plane3D< T >::normal(), and HepGeom::Plane3D< T >::point().
Referenced by G4ErrorPlaneSurfaceTarget().
G4double G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint (const G4ThreeVector & point, const G4ThreeVector & direc) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 118 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ErrorPlaneSurfaceTarget.cc
References HepGeom::Plane3D< T >::a_, HepGeom::Plane3D< T >::b_, HepGeom::Plane3D< T >::c_, HepGeom::Plane3D< T >::d_, E, G4cout, G4endl, G4Exception(), JustWarning, CLHEP::Hep3Vector::mag(), message(), G4ErrorPropagatorData::verbose(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Intersect().
G4double G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint (const G4ThreeVector & pt) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 145 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 145 of file G4ErrorPlaneSurfaceTarget.cc
References G4cout, G4endl, HepGeom::Plane3D< T >::normal(), HepGeom::Plane3D< T >::point(), pt, and G4ErrorPropagatorData::verbose().
G4Plane3D G4ErrorPlaneSurfaceTarget::GetTangentPlane (const G4ThreeVector & point) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 165 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 165 of file G4ErrorPlaneSurfaceTarget.cc
G4ThreeVector G4ErrorPlaneSurfaceTarget::Intersect (const G4ThreeVector & point, const G4ThreeVector & direc) const virtual
Definition at line 99 of file G4ErrorPlaneSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ErrorPlaneSurfaceTarget.cc
References dir, G4cout, G4endl, GetDistanceFromPoint(), G4InuclParticleNames::lam, and G4ErrorPropagatorData::verbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4ErrorPlaneSurfaceTarget.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4ErrorPlaneSurfaceTarget.cc