ECCE @ EIC Software: G4MultiSensitiveDetector Class Reference
G4MultiSensitiveDetector Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4MultiSensitiveDetector.hh>
Public Types
using sds_t = std::vector< G4VSensitiveDetector * >
using sdsConstIter = sds_t::const_iterator
Public Member Functions
G4MultiSensitiveDetector (G4String name)
G4MultiSensitiveDetector (const G4MultiSensitiveDetector &rhs)
virtual ~G4MultiSensitiveDetector ()
G4MultiSensitiveDetector & operator= (const G4MultiSensitiveDetector &rhs)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual G4VSensitiveDetector * Clone () const
G4VSensitiveDetector * GetSD (const int i) const
sds_t::size_type GetSize () const
sdsConstIter GetBegin () const
sdsConstIter GetEnd () const
void ClearSDs ()
void AddSD (G4VSensitiveDetector *sd)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
Protected Member Functions
virtual G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
virtual G4int GetCollectionID (G4int i) final
Private Attributes
sds_t fSensitiveDetectors
Additional Inherited Members
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 40 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 40 of file G4MultiSensitiveDetector.hh
Member Typedef Documentation
using G4MultiSensitiveDetector::sds_t = std::vector<G4VSensitiveDetector*>
Definition at line 73 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 73 of file G4MultiSensitiveDetector.hh
using G4MultiSensitiveDetector::sdsConstIter = sds_t::const_iterator
Definition at line 74 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 74 of file G4MultiSensitiveDetector.hh
Constructor & Destructor Documentation
G4MultiSensitiveDetector::G4MultiSensitiveDetector (G4String name)
Definition at line 40 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 40 of file G4MultiSensitiveDetector.cc
References VDBG, and G4VSensitiveDetector::verboseLevel.
Referenced by Clone().
G4MultiSensitiveDetector::G4MultiSensitiveDetector (const G4MultiSensitiveDetector & rhs)
Definition at line 55 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 55 of file G4MultiSensitiveDetector.cc
References G4VSensitiveDetector::GetName(), and VDBG.
G4MultiSensitiveDetector::~G4MultiSensitiveDetector () virtual
Definition at line 49 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 49 of file G4MultiSensitiveDetector.cc
References ClearSDs(), G4VSensitiveDetector::GetName(), and VDBG.
Member Function Documentation
void G4MultiSensitiveDetector::AddSD (G4VSensitiveDetector * sd) inline
Definition at line 80 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 80 of file G4MultiSensitiveDetector.hh
References fSensitiveDetectors.
Referenced by Clone(), and G4VUserDetectorConstruction::SetSensitiveDetector().
void G4MultiSensitiveDetector::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 90 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 90 of file G4MultiSensitiveDetector.cc
References fSensitiveDetectors.
void G4MultiSensitiveDetector::ClearSDs () inline
Definition at line 79 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 79 of file G4MultiSensitiveDetector.hh
References fSensitiveDetectors.
Referenced by ~G4MultiSensitiveDetector().
G4VSensitiveDetector * G4MultiSensitiveDetector::Clone () const virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 128 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 128 of file G4MultiSensitiveDetector.cc
References AddSD(), fSensitiveDetectors, G4MultiSensitiveDetector(), G4VSensitiveDetector::GetName(), and VDBG.
void G4MultiSensitiveDetector::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 96 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 96 of file G4MultiSensitiveDetector.cc
References fSensitiveDetectors.
void G4MultiSensitiveDetector::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 82 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 82 of file G4MultiSensitiveDetector.cc
sdsConstIter G4MultiSensitiveDetector::GetBegin () const inline
Definition at line 77 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 77 of file G4MultiSensitiveDetector.hh
References fSensitiveDetectors.
G4int G4MultiSensitiveDetector::GetCollectionID (G4int i) final protected virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 117 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 117 of file G4MultiSensitiveDetector.cc
References FatalException, G4Exception(), and G4VSensitiveDetector::GetName().
sdsConstIter G4MultiSensitiveDetector::GetEnd () const inline
Definition at line 78 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 78 of file G4MultiSensitiveDetector.hh
References fSensitiveDetectors.
G4VSensitiveDetector* G4MultiSensitiveDetector::GetSD (const int i) const inline
Definition at line 75 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 75 of file G4MultiSensitiveDetector.hh
References fSensitiveDetectors.
sds_t::size_type G4MultiSensitiveDetector::GetSize () const inline
Definition at line 76 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MultiSensitiveDetector.hh
References fSensitiveDetectors.
void G4MultiSensitiveDetector::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 74 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 74 of file G4MultiSensitiveDetector.cc
G4MultiSensitiveDetector & G4MultiSensitiveDetector::operator= (const G4MultiSensitiveDetector & rhs)
Definition at line 63 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 63 of file G4MultiSensitiveDetector.cc
References fSensitiveDetectors, and G4VSensitiveDetector::operator=().
void G4MultiSensitiveDetector::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 102 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 102 of file G4MultiSensitiveDetector.cc
References fSensitiveDetectors.
G4bool G4MultiSensitiveDetector::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) protected virtual
Implements G4VSensitiveDetector.
Definition at line 108 of file G4MultiSensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 108 of file G4MultiSensitiveDetector.cc
References fSensitiveDetectors, G4VSensitiveDetector::GetName(), G4Step::GetTotalEnergyDeposit(), and VDBG.
Member Data Documentation
sds_t G4MultiSensitiveDetector::fSensitiveDetectors private
Definition at line 82 of file G4MultiSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 82 of file G4MultiSensitiveDetector.hh
Referenced by AddSD(), clear(), ClearSDs(), Clone(), DrawAll(), GetBegin(), GetEnd(), GetSD(), GetSize(), operator=(), PrintAll(), and ProcessHits().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4MultiSensitiveDetector.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4MultiSensitiveDetector.cc