ECCE @ EIC Software: G4MagInt_Driver Class Reference
G4MagInt_Driver Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4MagIntegratorDriver.hh>
Public Member Functions
G4MagInt_Driver (G4double hminimum, G4MagIntegratorStepper *pItsStepper, G4int numberOfComponents=6, G4int statisticsVerbosity=0)
virtual ~G4MagInt_Driver () override
G4MagInt_Driver (const G4MagInt_Driver &)=delete
G4MagInt_Driver & operator= (const G4MagInt_Driver &)=delete
virtual G4double AdvanceChordLimited (G4FieldTrack &track, G4double stepMax, G4double epsStep, G4double chordDistance) override
virtual void OnStartTracking () override
virtual void OnComputeStep () override
virtual G4bool DoesReIntegrate () override
virtual G4bool AccurateAdvance (G4FieldTrack &y_current, G4double hstep, G4double eps, G4double hinitial=0.0) override
virtual G4bool QuickAdvance (G4FieldTrack &y_val, const G4double dydx[], G4double hstep, G4double &dchord_step, G4double &dyerr) override
G4bool QuickAdvance (G4FieldTrack &y_posvel, const G4double dydx[], G4double hstep, G4double &dchord_step, G4double &dyerr_pos_sq, G4double &dyerr_mom_rel_sq)
G4double GetHmin () const
G4double Hmin () const
G4double GetSafety () const
G4double GetPshrnk () const
G4double GetPgrow () const
G4double GetErrcon () const
virtual void GetDerivatives (const G4FieldTrack &y_curr, G4double dydx[]) const override
virtual void GetDerivatives (const G4FieldTrack &track, G4double dydx[], G4double field[]) const override
virtual G4EquationOfMotion * GetEquationOfMotion () override
virtual void SetEquationOfMotion (G4EquationOfMotion *equation) override
virtual void RenewStepperAndAdjust (G4MagIntegratorStepper *pItsStepper) override
void ReSetParameters (G4double new_safety=0.9)
void SetSafety (G4double valS)
void SetPshrnk (G4double valPs)
void SetPgrow (G4double valPg)
void SetErrcon (G4double valEc)
G4double ComputeAndSetErrcon ()
virtual const
G4MagIntegratorStepper * GetStepper () const override
virtual G4MagIntegratorStepper * GetStepper () override
void OneGoodStep (G4double ystart[], const G4double dydx[], G4double &x, G4double htry, G4double eps, G4double &hdid, G4double &hnext)
virtual G4double ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) override
G4double ComputeNewStepSize_WithinLimits (G4double errMaxNorm, G4double hstepCurrent)
G4int GetMaxNoSteps () const
void SetMaxNoSteps (G4int val)
void SetHmin (G4double newval)
virtual void SetVerboseLevel (G4int newLevel) override
virtual G4int GetVerboseLevel () const override
G4double GetSmallestFraction () const
void SetSmallestFraction (G4double val)
Public Member Functions inherited from G4VIntegrationDriver
virtual ~G4VIntegrationDriver ()=default
Public Member Functions inherited from G4ChordFinderDelegate< G4MagInt_Driver >
virtual ~G4ChordFinderDelegate ()
G4double AdvanceChordLimitedImpl (G4FieldTrack &track, G4double hstep, G4double eps, G4double chordDistance)
void ResetStepEstimate ()
void TestChordPrint (G4int noTrials, G4int lastStepTrial, G4double dChordStep, G4double fDeltaChord, G4double nextStepTrial)
G4int GetNoCalls ()
G4int GetNoTrials ()
G4int GetNoMaxTrials ()
void SetFractions_Last_Next (G4double fractLast=0.90, G4double fractNext=0.95)
void SetFirstFraction (G4double fractFirst)
G4double GetFirstFraction ()
G4double GetFractionLast ()
G4double GetFractionNextEstimate ()
G4double GetLastStepEstimateUnc ()
void SetLastStepEstimateUnc (G4double stepEst)
Protected Member Functions
void WarnSmallStepSize (G4double hnext, G4double hstep, G4double h, G4double xDone, G4int noSteps)
void WarnTooManyStep (G4double x1start, G4double x2end, G4double xCurrent)
void WarnEndPointTooFar (G4double endPointDist, G4double hStepSize, G4double epsilonRelative, G4int debugFlag)
void PrintStatus (const G4double *StartArr, G4double xstart, const G4double *CurrentArr, G4double xcurrent, G4double requestStep, G4int subStepNo)
void PrintStatus (const G4FieldTrack &StartFT, const G4FieldTrack &CurrentFT, G4double requestStep, G4int subStepNo)
void PrintStat_Aux (const G4FieldTrack &aFieldTrack, G4double requestStep, G4double actualStep, G4int subStepNo, G4double subStepSize, G4double dotVelocities)
void PrintStatisticsReport ()
Private Types
using ChordFinderDelegate = G4ChordFinderDelegate< G4MagInt_Driver >
Private Attributes
G4double fMinimumStep = 0.0
G4double fSmallestFraction = 1.0e-12
const G4int fNoIntegrationVariables = 0
const G4int fMinNoVars = 12
const G4int fNoVars = 0
G4int fMaxNoSteps
G4int fMaxStepBase = 250
G4double safety
G4double pshrnk
G4double pgrow
G4double errcon
G4int fStatisticsVerboseLevel = 0
G4MagIntegratorStepper * pIntStepper = nullptr
unsigned long fNoTotalSteps =0
unsigned long fNoBadSteps =0
unsigned long fNoSmallSteps =0
unsigned long fNoInitialSmallSteps =0
unsigned long fNoCalls =0
G4double fDyerr_max =0.0
G4double fDyerr_mx2 =0.0
G4double fDyerrPos_smTot =0.0
G4double fDyerrPos_lgTot =0.0
G4double fDyerrVel_lgTot =0.0
G4double fSumH_sm =0.0
G4double fSumH_lg =0.0
G4int fVerboseLevel = 0
Additional Inherited Members
Static Protected Attributes inherited from G4VIntegrationDriver
static constexpr G4double max_stepping_increase = 5
static constexpr G4double max_stepping_decrease = 0.1
Detailed Description
Definition at line 44 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 44 of file G4MagIntegratorDriver.hh
Member Typedef Documentation
using G4MagInt_Driver::ChordFinderDelegate = G4ChordFinderDelegate<G4MagInt_Driver> private
Definition at line 261 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 261 of file G4MagIntegratorDriver.hh
Constructor & Destructor Documentation
G4MagInt_Driver::G4MagInt_Driver (G4double hminimum, G4MagIntegratorStepper * pItsStepper, G4int numberOfComponents = 6, G4int statisticsVerbosity = 0)
Definition at line 45 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 45 of file G4MagIntegratorDriver.cc
References fMaxNoSteps, fMaxStepBase, fMinimumStep, fStatisticsVerboseLevel, fVerboseLevel, G4cout, G4endl, G4MagIntegratorStepper::IntegratorOrder(), pIntStepper, and RenewStepperAndAdjust().
G4MagInt_Driver::~G4MagInt_Driver () override virtual
Definition at line 81 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 81 of file G4MagIntegratorDriver.cc
References fStatisticsVerboseLevel, and PrintStatisticsReport().
G4MagInt_Driver::G4MagInt_Driver (const G4MagInt_Driver &) delete
Member Function Documentation
G4bool G4MagInt_Driver::AccurateAdvance (G4FieldTrack & y_current, G4double hstep, G4double eps, G4double hinitial = 0.0) override virtual
Implements G4VIntegrationDriver.
Definition at line 92 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 92 of file G4MagIntegratorDriver.cc
References ComputeNewStepSize(), G4FieldTrack::DumpToArray(), eps, EventMustBeAborted, FatalException, fDyerr_max, fDyerrPos_smTot, fMaxNoSteps, fMinimumStep, fNoBadSteps, fNoInitialSmallSteps, fNoIntegrationVariables, fNoSmallSteps, fNoTotalSteps, fNoVars, fSmallestFraction, fSumH_sm, G4cerr, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4FieldTrack::GetCurveLength(), Acts::UnitConstants::h, Hmin(), JustWarning, G4FieldTrack::LoadFromArray(), message(), G4FieldTrack::ncompSVEC, OneGoodStep(), perMillion, perThousand, pIntStepper, CLHEP::prec, PrintStatus(), QuickAdvance(), G4MagIntegratorStepper::RightHandSide(), G4FieldTrack::SetCurveLength(), WarnEndPointTooFar(), WarnSmallStepSize(), WarnTooManyStep(), x, x1, x2, and y.
Referenced by G4RKPropagation::FieldTransport().
virtual G4double G4MagInt_Driver::AdvanceChordLimited (G4FieldTrack & track, G4double stepMax, G4double epsStep, G4double chordDistance) inline override virtual
Implements G4VIntegrationDriver.
G4double G4MagInt_Driver::ComputeAndSetErrcon () inline
G4double G4MagInt_Driver::ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) override virtual
Implements G4VIntegrationDriver.
Definition at line 722 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 722 of file G4MagIntegratorDriver.cc
References GetPgrow(), GetPshrnk(), GetSafety(), and G4VIntegrationDriver::max_stepping_increase.
Referenced by AccurateAdvance(), and QuickAdvance().
G4double G4MagInt_Driver::ComputeNewStepSize_WithinLimits (G4double errMaxNorm, G4double hstepCurrent)
Definition at line 755 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 755 of file G4MagIntegratorDriver.cc
References errcon, GetPgrow(), GetPshrnk(), GetSafety(), G4VIntegrationDriver::max_stepping_decrease, and G4VIntegrationDriver::max_stepping_increase.
virtual G4bool G4MagInt_Driver::DoesReIntegrate () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 66 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 66 of file G4MagIntegratorDriver.hh
virtual void G4MagInt_Driver::GetDerivatives (const G4FieldTrack & y_curr, G4double dydx[]) const override virtual
Implements G4VIntegrationDriver.
void G4MagInt_Driver::GetDerivatives (const G4FieldTrack & track, G4double dydx[], G4double field[]) const override virtual
Implements G4VIntegrationDriver.
Definition at line 984 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 984 of file G4MagIntegratorDriver.cc
References G4FieldTrack::DumpToArray(), G4FieldTrack::ncompSVEC, pIntStepper, and G4MagIntegratorStepper::RightHandSide().
G4EquationOfMotion * G4MagInt_Driver::GetEquationOfMotion () override virtual
Implements G4VIntegrationDriver.
Definition at line 993 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 993 of file G4MagIntegratorDriver.cc
References G4MagIntegratorStepper::GetEquationOfMotion(), and pIntStepper.
G4double G4MagInt_Driver::GetErrcon () const inline
G4double G4MagInt_Driver::GetHmin () const inline
G4int G4MagInt_Driver::GetMaxNoSteps () const inline
G4double G4MagInt_Driver::GetPgrow () const inline
Referenced by ComputeNewStepSize(), ComputeNewStepSize_WithinLimits(), and OneGoodStep().
G4double G4MagInt_Driver::GetPshrnk () const inline
Referenced by ComputeNewStepSize(), ComputeNewStepSize_WithinLimits(), and OneGoodStep().
G4double G4MagInt_Driver::GetSafety () const inline
Referenced by ComputeNewStepSize(), ComputeNewStepSize_WithinLimits(), and OneGoodStep().
G4double G4MagInt_Driver::GetSmallestFraction () const inline
const G4MagIntegratorStepper * G4MagInt_Driver::GetStepper () const override virtual
Implements G4VIntegrationDriver.
Definition at line 1003 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 1003 of file G4MagIntegratorDriver.cc
References pIntStepper.
G4MagIntegratorStepper * G4MagInt_Driver::GetStepper () override virtual
Implements G4VIntegrationDriver.
Definition at line 1008 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 1008 of file G4MagIntegratorDriver.cc
References pIntStepper.
virtual G4int G4MagInt_Driver::GetVerboseLevel () const override virtual
Implements G4VIntegrationDriver.
G4double G4MagInt_Driver::Hmin () const inline
Referenced by AccurateAdvance(), and WarnSmallStepSize().
virtual void G4MagInt_Driver::OnComputeStep () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 65 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 65 of file G4MagIntegratorDriver.hh
void G4MagInt_Driver::OneGoodStep (G4double ystart[], const G4double dydx[], G4double & x, G4double htry, G4double eps, G4double & hdid, G4double & hnext)
Definition at line 480 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 480 of file G4MagIntegratorDriver.cc
References errcon, fMinimumStep, fNoIntegrationVariables, G4endl, G4Exception(), G4ThreadLocal, GetPgrow(), GetPshrnk(), GetSafety(), Acts::UnitConstants::h, JustWarning, k, CLHEP::Hep3Vector::mag2(), max, G4VIntegrationDriver::max_stepping_increase, message(), G4FieldTrack::ncompSVEC, pIntStepper, and sqr().
Referenced by AccurateAdvance().
virtual void G4MagInt_Driver::OnStartTracking () inline override virtual
Implements G4VIntegrationDriver.
G4MagInt_Driver& G4MagInt_Driver::operator= (const G4MagInt_Driver &) delete
void G4MagInt_Driver::PrintStat_Aux (const G4FieldTrack & aFieldTrack, G4double requestStep, G4double actualStep, G4int subStepNo, G4double subStepSize, G4double dotVelocities) protected
Definition at line 875 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 875 of file G4MagIntegratorDriver.cc
References G4cout, G4endl, G4ThreadLocal, G4FieldTrack::GetCurveLength(), G4FieldTrack::GetKineticEnergy(), G4FieldTrack::GetMomentumDir(), G4FieldTrack::GetPosition(), CLHEP::Hep3Vector::mag2(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by PrintStatus().
void G4MagInt_Driver::PrintStatisticsReport () protected
Definition at line 940 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 940 of file G4MagIntegratorDriver.cc
References fNoBadSteps, fNoInitialSmallSteps, fNoSmallSteps, fNoTotalSteps, G4cout, and G4endl.
Referenced by ~G4MagInt_Driver().
void G4MagInt_Driver::PrintStatus (const G4double * StartArr, G4double xstart, const G4double * CurrentArr, G4double xcurrent, G4double requestStep, G4int subStepNo) protected
Definition at line 787 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 787 of file G4MagIntegratorDriver.cc
References fNoIntegrationVariables, G4FieldTrack::LoadFromArray(), and G4FieldTrack::SetCurveLength().
Referenced by AccurateAdvance(), and QuickAdvance().
void G4MagInt_Driver::PrintStatus (const G4FieldTrack & StartFT, const G4FieldTrack & CurrentFT, G4double requestStep, G4int subStepNo) protected
Definition at line 812 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 812 of file G4MagIntegratorDriver.cc
References CLHEP::Hep3Vector::dot(), fVerboseLevel, G4cout, G4endl, G4FieldTrack::GetCurveLength(), G4FieldTrack::GetMomentumDir(), G4FieldTrack::GetPosition(), and PrintStat_Aux().
G4bool G4MagInt_Driver::QuickAdvance (G4FieldTrack & y_val, const G4double dydx[], G4double hstep, G4double & dchord_step, G4double & dyerr) override virtual
Reimplemented from G4VIntegrationDriver.
Definition at line 625 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 625 of file G4MagIntegratorDriver.cc
References ComputeNewStepSize(), G4FieldTrack::DumpToArray(), eps, fNoIntegrationVariables, fVerboseLevel, G4cout, G4endl, G4ThreadLocal, G4FieldTrack::GetCurveLength(), G4FieldTrack::LoadFromArray(), G4FieldTrack::ncompSVEC, pIntStepper, PrintStatus(), G4FieldTrack::SetCurveLength(), and sqr().
Referenced by AccurateAdvance().
G4bool G4MagInt_Driver::QuickAdvance (G4FieldTrack & y_posvel, const G4double dydx[], G4double hstep, G4double & dchord_step, G4double & dyerr_pos_sq, G4double & dyerr_mom_rel_sq)
Definition at line 606 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 606 of file G4MagIntegratorDriver.cc
References FatalException, G4Exception(), G4FieldTrack::GetPosition(), and CLHEP::Hep3Vector::mag2().
void G4MagInt_Driver::RenewStepperAndAdjust (G4MagIntegratorStepper * pItsStepper) override virtual
Reimplemented from G4VIntegrationDriver.
Definition at line 1014 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 1014 of file G4MagIntegratorDriver.cc
References pIntStepper, and ReSetParameters().
Referenced by F02ElectricFieldSetup::CreateStepper(), and G4MagInt_Driver().
void G4MagInt_Driver::ReSetParameters (G4double new_safety = 0.9) inline
Referenced by RenewStepperAndAdjust().
void G4MagInt_Driver::SetEquationOfMotion (G4EquationOfMotion * equation) override virtual
Implements G4VIntegrationDriver.
Definition at line 998 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 998 of file G4MagIntegratorDriver.cc
References pIntStepper, and G4MagIntegratorStepper::SetEquationOfMotion().
void G4MagInt_Driver::SetErrcon (G4double valEc) inline
void G4MagInt_Driver::SetHmin (G4double newval) inline
void G4MagInt_Driver::SetMaxNoSteps (G4int val) inline
void G4MagInt_Driver::SetPgrow (G4double valPg) inline
void G4MagInt_Driver::SetPshrnk (G4double valPs) inline
void G4MagInt_Driver::SetSafety (G4double valS) inline
void G4MagInt_Driver::SetSmallestFraction (G4double val)
Definition at line 957 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 957 of file G4MagIntegratorDriver.cc
References e, fSmallestFraction, G4endl, G4Exception(), JustWarning, and message().
virtual void G4MagInt_Driver::SetVerboseLevel (G4int newLevel) override virtual
Implements G4VIntegrationDriver.
void G4MagInt_Driver::WarnEndPointTooFar (G4double endPointDist, G4double hStepSize, G4double epsilonRelative, G4int debugFlag) protected
Definition at line 444 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 444 of file G4MagIntegratorDriver.cc
References eps, G4endl, G4Exception(), G4ThreadLocal, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), JustWarning, and message().
Referenced by AccurateAdvance().
void G4MagInt_Driver::WarnSmallStepSize (G4double hnext, G4double hstep, G4double h, G4double xDone, G4int noSteps) protected
Definition at line 395 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 395 of file G4MagIntegratorDriver.cc
References fVerboseLevel, G4endl, G4Exception(), G4ThreadLocal, Hmin(), JustWarning, and message().
Referenced by AccurateAdvance().
void G4MagInt_Driver::WarnTooManyStep (G4double x1start, G4double x2end, G4double xCurrent) protected
Definition at line 427 of file G4MagIntegratorDriver.cc.
View newest version in sPHENIX GitHub at line 427 of file G4MagIntegratorDriver.cc
References G4endl, G4Exception(), JustWarning, and message().
Referenced by AccurateAdvance().
Member Data Documentation
G4double G4MagInt_Driver::errcon private
Definition at line 238 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 238 of file G4MagIntegratorDriver.hh
Referenced by ComputeNewStepSize_WithinLimits(), and OneGoodStep().
G4double G4MagInt_Driver::fDyerr_max =0.0 private
Definition at line 253 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 253 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance().
G4double G4MagInt_Driver::fDyerr_mx2 =0.0 private
Definition at line 253 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 253 of file G4MagIntegratorDriver.hh
G4double G4MagInt_Driver::fDyerrPos_lgTot =0.0 private
Definition at line 254 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 254 of file G4MagIntegratorDriver.hh
G4double G4MagInt_Driver::fDyerrPos_smTot =0.0 private
Definition at line 254 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 254 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance().
G4double G4MagInt_Driver::fDyerrVel_lgTot =0.0 private
Definition at line 254 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 254 of file G4MagIntegratorDriver.hh
G4int G4MagInt_Driver::fMaxNoSteps private
Definition at line 231 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 231 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), and G4MagInt_Driver().
G4int G4MagInt_Driver::fMaxStepBase = 250 private
Definition at line 232 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 232 of file G4MagIntegratorDriver.hh
Referenced by G4MagInt_Driver().
G4double G4MagInt_Driver::fMinimumStep = 0.0 private
Definition at line 221 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 221 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), G4MagInt_Driver(), and OneGoodStep().
const G4int G4MagInt_Driver::fMinNoVars = 12 private
Definition at line 228 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 228 of file G4MagIntegratorDriver.hh
unsigned long G4MagInt_Driver::fNoBadSteps =0 private
Definition at line 251 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 251 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), and PrintStatisticsReport().
unsigned long G4MagInt_Driver::fNoCalls =0 private
Definition at line 252 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 252 of file G4MagIntegratorDriver.hh
unsigned long G4MagInt_Driver::fNoInitialSmallSteps =0 private
Definition at line 252 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 252 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), and PrintStatisticsReport().
const G4int G4MagInt_Driver::fNoIntegrationVariables = 0 private
Definition at line 227 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 227 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), OneGoodStep(), PrintStatus(), and QuickAdvance().
unsigned long G4MagInt_Driver::fNoSmallSteps =0 private
Definition at line 252 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 252 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), and PrintStatisticsReport().
unsigned long G4MagInt_Driver::fNoTotalSteps =0 private
Definition at line 251 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 251 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), and PrintStatisticsReport().
const G4int G4MagInt_Driver::fNoVars = 0 private
Definition at line 229 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 229 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance().
G4double G4MagInt_Driver::fSmallestFraction = 1.0e-12 private
Definition at line 223 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 223 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), and SetSmallestFraction().
G4int G4MagInt_Driver::fStatisticsVerboseLevel = 0 private
Definition at line 241 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 241 of file G4MagIntegratorDriver.hh
Referenced by G4MagInt_Driver(), and ~G4MagInt_Driver().
G4double G4MagInt_Driver::fSumH_lg =0.0 private
Definition at line 255 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 255 of file G4MagIntegratorDriver.hh
G4double G4MagInt_Driver::fSumH_sm =0.0 private
Definition at line 255 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 255 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance().
G4int G4MagInt_Driver::fVerboseLevel = 0 private
Definition at line 258 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 258 of file G4MagIntegratorDriver.hh
Referenced by G4MagInt_Driver(), PrintStatus(), QuickAdvance(), and WarnSmallStepSize().
G4double G4MagInt_Driver::pgrow private
Definition at line 237 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 237 of file G4MagIntegratorDriver.hh
G4MagIntegratorStepper* G4MagInt_Driver::pIntStepper = nullptr private
Definition at line 246 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 246 of file G4MagIntegratorDriver.hh
Referenced by AccurateAdvance(), G4MagInt_Driver(), GetDerivatives(), GetEquationOfMotion(), GetStepper(), OneGoodStep(), QuickAdvance(), RenewStepperAndAdjust(), and SetEquationOfMotion().
G4double G4MagInt_Driver::pshrnk private
Definition at line 236 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 236 of file G4MagIntegratorDriver.hh
G4double G4MagInt_Driver::safety private
Definition at line 235 of file G4MagIntegratorDriver.hh.
View newest version in sPHENIX GitHub at line 235 of file G4MagIntegratorDriver.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4MagIntegratorDriver.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4MagIntegratorDriver.cc