ECCE @ EIC Software: G4Polyline Class Reference
G4Polyline Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Polyline.hh>
Public Types
typedef G4Point3DList::iterator iterator
Public Types inherited from G4Point3DList
typedef std::vector< G4Point3D >
::iterator iterator
Public Member Functions
G4Polyline ()
virtual ~G4Polyline ()
G4Polyline & transform (const G4Transform3D &)
Public Member Functions inherited from G4Visible
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Public Member Functions inherited from G4Point3DList
virtual ~G4Point3DList ()
Friends
std::ostream & operator<< (std::ostream &os, const G4Polyline &)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Protected Attributes inherited from G4Visible
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Detailed Description
Definition at line 46 of file G4Polyline.hh.
View newest version in sPHENIX GitHub at line 46 of file G4Polyline.hh
Member Typedef Documentation
typedef G4Point3DList::iterator G4Polyline::iterator
Definition at line 52 of file G4Polyline.hh.
View newest version in sPHENIX GitHub at line 52 of file G4Polyline.hh
Constructor & Destructor Documentation
G4Polyline::G4Polyline ()
Definition at line 33 of file G4Polyline.cc.
View newest version in sPHENIX GitHub at line 33 of file G4Polyline.cc
G4Polyline::~G4Polyline () virtual
Definition at line 35 of file G4Polyline.cc.
View newest version in sPHENIX GitHub at line 35 of file G4Polyline.cc
Member Function Documentation
G4Polyline & G4Polyline::transform (const G4Transform3D & transformation)
Definition at line 37 of file G4Polyline.cc.
View newest version in sPHENIX GitHub at line 37 of file G4Polyline.cc
References transform().
Referenced by G4VSceneHandler::AddPrimitive(), and transform().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4Polyline & line) friend
Definition at line 42 of file G4Polyline.cc.
View newest version in sPHENIX GitHub at line 42 of file G4Polyline.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Polyline.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4Polyline.cc