ECCE @ EIC Software: G4TypeKey Class Reference
G4TypeKey Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4TypeKey.hh>
Public Types
typedef unsigned long Key
Public Member Functions
G4TypeKey ()
virtual ~G4TypeKey ()
G4bool IsValid ()
Key operator() () const
G4bool operator== (const G4TypeKey &rhs) const
G4bool operator!= (const G4TypeKey &rhs) const
G4bool operator< (const G4TypeKey &rhs) const
G4bool operator> (const G4TypeKey &rhs) const
Protected Member Functions
Key NextKey () const
Protected Attributes
Key fMyKey
Friends
std::ostream & operator<< (std::ostream &out, const G4TypeKey &key)
Detailed Description
Definition at line 37 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 37 of file G4TypeKey.hh
Member Typedef Documentation
typedef unsigned long G4TypeKey::Key
Definition at line 41 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 41 of file G4TypeKey.hh
Constructor & Destructor Documentation
G4TypeKey::G4TypeKey () inline
Definition at line 44 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 44 of file G4TypeKey.hh
virtual G4TypeKey::~G4TypeKey () inline virtual
Definition at line 47 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 47 of file G4TypeKey.hh
Member Function Documentation
G4bool G4TypeKey::IsValid (void) inline
Definition at line 49 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 49 of file G4TypeKey.hh
References fMyKey.
Referenced by G4AttFilterUtils::GetNewFilter().
Key G4TypeKey::NextKey () const inline protected
Definition at line 66 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 66 of file G4TypeKey.hh
References G4ThreadLocal.
Referenced by G4TypeKeyT< T >::G4TypeKeyT().
G4bool G4TypeKey::operator!= (const G4TypeKey & rhs) const inline
Definition at line 56 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 56 of file G4TypeKey.hh
References operator==().
Key G4TypeKey::operator() () const inline
Definition at line 54 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 54 of file G4TypeKey.hh
References fMyKey.
G4bool G4TypeKey::operator< (const G4TypeKey & rhs) const inline
Definition at line 57 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 57 of file G4TypeKey.hh
References fMyKey.
G4bool G4TypeKey::operator== (const G4TypeKey & rhs) const inline
Definition at line 55 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 55 of file G4TypeKey.hh
References fMyKey.
Referenced by operator!=().
G4bool G4TypeKey::operator> (const G4TypeKey & rhs) const inline
Definition at line 58 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 58 of file G4TypeKey.hh
References fMyKey.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4TypeKey & key) friend
Definition at line 60 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 60 of file G4TypeKey.hh
Member Data Documentation
Key G4TypeKey::fMyKey protected
Definition at line 73 of file G4TypeKey.hh.
View newest version in sPHENIX GitHub at line 73 of file G4TypeKey.hh
Referenced by G4TypeKeyT< T >::G4TypeKeyT(), IsValid(), operator()(), operator<(), operator==(), and operator>().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4TypeKey.hh