ECCE @ EIC Software: CLHEP::RanshiEngine Class Reference
CLHEP::RanshiEngine Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RanshiEngine.h>
Public Member Functions
RanshiEngine ()
RanshiEngine (std::istream &is)
RanshiEngine (long seed)
RanshiEngine (int rowIndex, int colIndex)
virtual ~RanshiEngine ()
double flat ()
void flatArray (const int size, double *vect)
void setSeed (long seed, int)
void setSeeds (const long *seeds, int)
void saveStatus (const char filename[]="RanshiEngine.conf") const
void restoreStatus (const char filename[]="RanshiEngine.conf")
void showStatus () const
operator double ()
operator float ()
operator unsigned int ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Private Types
enum { numBuff = 512 }
Private Attributes
unsigned int halfBuff
unsigned int numFlats
unsigned int buffer [numBuff]
unsigned int redSpin
Static Private Attributes
static const unsigned int VECTOR_STATE_SIZE = numBuff + 4
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Definition at line 51 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 51 of file RanshiEngine.h
Member Enumeration Documentation
anonymous enum private
Enumerator:
numBuff
Definition at line 102 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 102 of file RanshiEngine.h
Constructor & Destructor Documentation
CLHEP::RanshiEngine::RanshiEngine ()
Definition at line 62 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 62 of file RanshiEngine.cc
References flat(), int(), CLHEP::L, numBuff, redSpin, and CLHEP::HepRandomEngine::theSeed.
Referenced by setSeed().
CLHEP::RanshiEngine::RanshiEngine (std::istream & is)
Definition at line 78 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 78 of file RanshiEngine.cc
CLHEP::RanshiEngine::RanshiEngine (long seed)
Definition at line 85 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 85 of file RanshiEngine.cc
References flat(), int(), numBuff, redSpin, seed, and CLHEP::HepRandomEngine::theSeed.
CLHEP::RanshiEngine::RanshiEngine (int rowIndex, int colIndex)
Definition at line 100 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 100 of file RanshiEngine.cc
References flat(), int(), numBuff, redSpin, and CLHEP::HepRandomEngine::theSeed.
CLHEP::RanshiEngine::~RanshiEngine () virtual
Definition at line 114 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 114 of file RanshiEngine.cc
Member Function Documentation
std::string CLHEP::RanshiEngine::beginTag () static
Definition at line 286 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 286 of file RanshiEngine.cc
static std::string CLHEP::RanshiEngine::engineName () inline static
Definition at line 95 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 95 of file RanshiEngine.h
Referenced by restoreStatus().
double CLHEP::RanshiEngine::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 116 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 116 of file RanshiEngine.cc
References halfBuff, CLHEP::HepRandomEngine::nearlyTwoToMinus_54(), numBuff, numFlats, redSpin, CLHEP::HepRandomEngine::twoToMinus_32(), and CLHEP::HepRandomEngine::twoToMinus_53().
Referenced by flatArray(), and RanshiEngine().
void CLHEP::RanshiEngine::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 131 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 131 of file RanshiEngine.cc
References flat().
std::istream & CLHEP::RanshiEngine::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 269 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 269 of file RanshiEngine.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::RanshiEngine::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 328 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 328 of file RanshiEngine.cc
References getState().
std::istream & CLHEP::RanshiEngine::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 290 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 290 of file RanshiEngine.cc
References halfBuff, CLHEP::MarkerLen, numBuff, numFlats, CLHEP::possibleKeywordInput(), redSpin, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
Referenced by get(), and restoreStatus().
bool CLHEP::RanshiEngine::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 337 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 337 of file RanshiEngine.cc
References halfBuff, numBuff, numFlats, redSpin, and VECTOR_STATE_SIZE.
std::string CLHEP::RanshiEngine::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 60 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 60 of file RanshiEngine.cc
CLHEP::RanshiEngine::operator double () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 219 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 219 of file RanshiEngine.cc
References G4AblaRandom::flat().
CLHEP::RanshiEngine::operator float () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 223 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 223 of file RanshiEngine.cc
CLHEP::RanshiEngine::operator unsigned int () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 235 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 235 of file RanshiEngine.cc
std::ostream & CLHEP::RanshiEngine::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 247 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 247 of file RanshiEngine.cc
References put(), and v.
std::vector< unsigned long > CLHEP::RanshiEngine::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 257 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 257 of file RanshiEngine.cc
References halfBuff, numBuff, numFlats, redSpin, and v.
Referenced by put(), and saveStatus().
void CLHEP::RanshiEngine::restoreStatus (const char filename[] = "RanshiEngine.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 169 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 169 of file RanshiEngine.cc
References CLHEP::HepRandomEngine::checkFile(), engineName(), getState(), halfBuff, in, numBuff, numFlats, CLHEP::possibleKeywordInput(), redSpin, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
void CLHEP::RanshiEngine::saveStatus (const char filename[] = "RanshiEngine.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 158 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 158 of file RanshiEngine.cc
References put(), and v.
void CLHEP::RanshiEngine::setSeed (long seed, int) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 137 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 137 of file RanshiEngine.cc
References RanshiEngine().
void CLHEP::RanshiEngine::setSeeds (const long * seeds, int) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 141 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 141 of file RanshiEngine.cc
References int(), numBuff, redSpin, CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
void CLHEP::RanshiEngine::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 202 of file RanshiEngine.cc.
View newest version in sPHENIX GitHub at line 202 of file RanshiEngine.cc
References halfBuff, numBuff, numFlats, redSpin, right, and CLHEP::HepRandomEngine::theSeed.
Member Data Documentation
unsigned int CLHEP::RanshiEngine::buffer[numBuff] private
Definition at line 105 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 105 of file RanshiEngine.h
unsigned int CLHEP::RanshiEngine::halfBuff private
Definition at line 104 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 104 of file RanshiEngine.h
Referenced by flat(), getState(), put(), restoreStatus(), and showStatus().
unsigned int CLHEP::RanshiEngine::numFlats private
Definition at line 104 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 104 of file RanshiEngine.h
Referenced by flat(), getState(), put(), restoreStatus(), and showStatus().
unsigned int CLHEP::RanshiEngine::redSpin private
Definition at line 106 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 106 of file RanshiEngine.h
Referenced by flat(), getState(), put(), RanshiEngine(), restoreStatus(), setSeeds(), and showStatus().
const unsigned int CLHEP::RanshiEngine::VECTOR_STATE_SIZE = numBuff + 4 static private
Definition at line 108 of file RanshiEngine.h.
View newest version in sPHENIX GitHub at line 108 of file RanshiEngine.h
Referenced by getState(), and restoreStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RanshiEngine.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RanshiEngine.cc