ECCE @ EIC Software: G4DNAMolecularReactionData Class Reference
G4DNAMolecularReactionData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAMolecularReactionTable.hh>
Public Types
using Reactant = const G4MolecularConfiguration
using ReactantPair = std::pair< Reactant *, Reactant * >
using ReactionProducts = std::vector< Reactant * >
typedef std::function< double(double)> RateParam
Public Member Functions
G4DNAMolecularReactionData (G4double reactionRate, const G4MolecularConfiguration *reactive1, const G4MolecularConfiguration *reactive2)
G4DNAMolecularReactionData (G4double reactionRate, const G4String &reactive1, const G4String &reactive2)
~G4DNAMolecularReactionData ()
int GetReactionID () const
void SetReactionID (int ID)
ReactantPair GetReactants ()
Reactant * GetReactant1 () const
Reactant * GetReactant2 () const
void SetObservedReactionRateConstant (G4double rate)
G4double GetObservedReactionRateConstant () const
G4double GetEffectiveReactionRadius () const
void SetEffectiveReactionRadius (G4double radius)
void SetReactant1 (Reactant *reactive)
void SetReactant2 (Reactant *reactive)
void SetReactants (Reactant *reactive1, Reactant *reactive2)
void AddProduct (Reactant *molecule)
void SetReactant1 (const G4String &reactive)
void SetReactant2 (const G4String &reactive)
void SetReactants (const G4String &reactive1, const G4String &reactive2)
void AddProduct (const G4String &molecule)
G4int GetNbProducts () const
Reactant * GetProduct (G4int i) const
const ReactionProducts * GetProducts () const
void RemoveProducts ()
void SetPolynomialParameterization (const std::vector< double > &P)
void SetArrehniusParameterization (double A0, double E_R)
void SetScaledParameterization (double temperature_K, double rateCste)
void ScaleForNewTemperature (double temp_K)
Static Public Member Functions
static double PolynomialParam (double temp_K, std::vector< double > P)
static double ArrehniusParam (double temp_K, std::vector< double > P)
static double ScaledParameterization (double temp_K, double temp_init, double rateCste_init)
Protected Member Functions
G4DNAMolecularReactionData ()
Protected Attributes
Reactant * fpReactant1
Reactant * fpReactant2
G4double fObservedReactionRate
G4double fEffectiveReactionRadius
ReactionProducts fProducts
RateParam fRateParam
int fReactionID
Private Member Functions
void ComputeEffectiveRadius ()
Detailed Description
G4DNAMolecularReactionData contains the information relative to a given reaction (eg : °OH + °OH -> H2O2)
Definition at line 64 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 64 of file G4DNAMolecularReactionTable.hh
Member Typedef Documentation
typedef std::function<double(double)> G4DNAMolecularReactionData::RateParam
Definition at line 117 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 117 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionData::Reactant = const G4MolecularConfiguration
Definition at line 78 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 78 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionData::ReactantPair = std::pair<Reactant*, Reactant*>
Definition at line 79 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 79 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionData::ReactionProducts = std::vector<Reactant*>
Definition at line 80 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 80 of file G4DNAMolecularReactionTable.hh
Constructor & Destructor Documentation
G4DNAMolecularReactionData::G4DNAMolecularReactionData (G4double reactionRate, const G4MolecularConfiguration * reactive1, const G4MolecularConfiguration * reactive2)
G4DNAMolecularReactionData::G4DNAMolecularReactionData (G4double reactionRate, const G4String & reactive1, const G4String & reactive2)
Definition at line 77 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 77 of file G4DNAMolecularReactionTable.cc
References ComputeEffectiveRadius(), SetReactant1(), and SetReactant2().
G4DNAMolecularReactionData::~G4DNAMolecularReactionData ()
Definition at line 91 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 91 of file G4DNAMolecularReactionTable.cc
References fProducts.
G4DNAMolecularReactionData::G4DNAMolecularReactionData () protected
Definition at line 56 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 56 of file G4DNAMolecularReactionTable.cc
Member Function Documentation
void G4DNAMolecularReactionData::AddProduct (Reactant * molecule)
Definition at line 140 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 140 of file G4DNAMolecularReactionTable.cc
References fProducts.
Referenced by G4EmDNAChemistry::ConstructReactionTable(), G4EmDNAChemistry_option1::ConstructReactionTable(), G4EmDNAChemistry_option2::ConstructReactionTable(), and G4ReactionTableMessenger::SetNewValue().
void G4DNAMolecularReactionData::AddProduct (const G4String & molecule)
Definition at line 215 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 215 of file G4DNAMolecularReactionTable.cc
References fProducts, and G4MoleculeTable::Instance().
double G4DNAMolecularReactionData::ArrehniusParam (double temp_K, std::vector< double > P) static
Definition at line 230 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 230 of file G4DNAMolecularReactionTable.cc
References e, G4Exp(), CLHEP::m3, CLHEP::mole, and CLHEP::s.
Referenced by SetArrehniusParameterization().
void G4DNAMolecularReactionData::ComputeEffectiveRadius () private
Definition at line 96 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 96 of file G4DNAMolecularReactionTable.cc
References CLHEP::Avogadro, fEffectiveReactionRadius, fObservedReactionRate, fpReactant1, fpReactant2, G4MolecularConfiguration::GetDiffusionCoefficient(), and CLHEP::pi.
Referenced by G4DNAMolecularReactionData().
G4double G4DNAMolecularReactionData::GetEffectiveReactionRadius () const
Definition at line 205 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 205 of file G4DNAMolecularReactionTable.cc
References fEffectiveReactionRadius.
Referenced by G4DNASmoluchowskiReactionModel::GetReactionRadius().
G4int G4DNAMolecularReactionData::GetNbProducts () const
Definition at line 145 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 145 of file G4DNAMolecularReactionTable.cc
References fProducts.
Referenced by G4DNAMolecularReaction::MakeReaction(), and G4DNAMolecularReactionTable::PrintTable().
G4double G4DNAMolecularReactionData::GetObservedReactionRateConstant () const
Definition at line 200 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 200 of file G4DNAMolecularReactionTable.cc
References fObservedReactionRate.
Referenced by G4DNAMolecularReactionTable::PrintTable().
G4DNAMolecularReactionData::Reactant * G4DNAMolecularReactionData::GetProduct (G4int i) const
Definition at line 150 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 150 of file G4DNAMolecularReactionTable.cc
References fProducts.
Referenced by G4DNAMolecularReactionTable::PrintTable().
const G4DNAMolecularReactionData::ReactionProducts * G4DNAMolecularReactionData::GetProducts () const
Definition at line 155 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 155 of file G4DNAMolecularReactionTable.cc
References fProducts.
G4DNAMolecularReactionData::Reactant * G4DNAMolecularReactionData::GetReactant1 () const
Definition at line 185 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 185 of file G4DNAMolecularReactionTable.cc
References fpReactant1.
Referenced by G4DNAMolecularReactionTable::SetReaction().
G4DNAMolecularReactionData::Reactant * G4DNAMolecularReactionData::GetReactant2 () const
Definition at line 190 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 190 of file G4DNAMolecularReactionTable.cc
References fpReactant2.
Referenced by G4DNAMolecularReactionTable::SetReaction().
G4DNAMolecularReactionData::ReactantPair G4DNAMolecularReactionData::GetReactants ()
Definition at line 180 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 180 of file G4DNAMolecularReactionTable.cc
References fpReactant1, and fpReactant2.
int G4DNAMolecularReactionData::GetReactionID () const
Definition at line 113 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 113 of file G4DNAMolecularReactionTable.cc
References fReactionID.
double G4DNAMolecularReactionData::PolynomialParam (double temp_K, std::vector< double > P) static
Definition at line 220 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 220 of file G4DNAMolecularReactionTable.cc
References e, CLHEP::m3, CLHEP::mole, and CLHEP::s.
Referenced by SetPolynomialParameterization().
void G4DNAMolecularReactionData::RemoveProducts ()
Definition at line 160 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 160 of file G4DNAMolecularReactionTable.cc
References fProducts.
double G4DNAMolecularReactionData::ScaledParameterization (double temp_K, double temp_init, double rateCste_init) static
Definition at line 236 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 236 of file G4DNAMolecularReactionTable.cc
References G4MolecularConfiguration::DiffCoeffWater().
Referenced by SetScaledParameterization().
void G4DNAMolecularReactionData::ScaleForNewTemperature (double temp_K)
Definition at line 701 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 701 of file G4DNAMolecularReactionTable.cc
References fRateParam, and SetObservedReactionRateConstant().
void G4DNAMolecularReactionData::SetArrehniusParameterization (double A0, double E_R)
Definition at line 671 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 671 of file G4DNAMolecularReactionTable.cc
References ArrehniusParam(), fRateParam, and P.
Referenced by G4ReactionTableMessenger::SetNewValue().
void G4DNAMolecularReactionData::SetEffectiveReactionRadius (G4double radius)
Definition at line 210 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 210 of file G4DNAMolecularReactionTable.cc
References fEffectiveReactionRadius, and radius.
Referenced by G4EmDNAChemistry_option2::ConstructReactionTable().
void G4DNAMolecularReactionData::SetObservedReactionRateConstant (G4double rate)
Definition at line 195 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 195 of file G4DNAMolecularReactionTable.cc
References fObservedReactionRate.
Referenced by ScaleForNewTemperature(), and G4ReactionTableMessenger::SetNewValue().
void G4DNAMolecularReactionData::SetPolynomialParameterization (const std::vector< double > & P)
Definition at line 664 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 664 of file G4DNAMolecularReactionTable.cc
References fRateParam, and PolynomialParam().
Referenced by G4ReactionTableMessenger::SetNewValue().
void G4DNAMolecularReactionData::SetReactant1 (Reactant * reactive)
Definition at line 123 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 123 of file G4DNAMolecularReactionTable.cc
References fpReactant1.
Referenced by G4DNAMolecularReactionData().
void G4DNAMolecularReactionData::SetReactant1 (const G4String & reactive)
Definition at line 165 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 165 of file G4DNAMolecularReactionTable.cc
References fpReactant1, G4MoleculeTable::GetConfiguration(), and G4MoleculeTable::Instance().
void G4DNAMolecularReactionData::SetReactant2 (Reactant * reactive)
Definition at line 128 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 128 of file G4DNAMolecularReactionTable.cc
References fpReactant2.
Referenced by G4DNAMolecularReactionData().
void G4DNAMolecularReactionData::SetReactant2 (const G4String & reactive)
Definition at line 169 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 169 of file G4DNAMolecularReactionTable.cc
References fpReactant2, G4MoleculeTable::GetConfiguration(), and G4MoleculeTable::Instance().
void G4DNAMolecularReactionData::SetReactants (Reactant * reactive1, Reactant * reactive2)
Definition at line 133 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 133 of file G4DNAMolecularReactionTable.cc
References fpReactant1, and fpReactant2.
void G4DNAMolecularReactionData::SetReactants (const G4String & reactive1, const G4String & reactive2)
Definition at line 173 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 173 of file G4DNAMolecularReactionTable.cc
References fpReactant1, fpReactant2, G4MoleculeTable::GetConfiguration(), and G4MoleculeTable::Instance().
void G4DNAMolecularReactionData::SetReactionID (int ID)
Definition at line 118 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 118 of file G4DNAMolecularReactionTable.cc
References fReactionID.
Referenced by G4DNAMolecularReactionTable::SetReaction().
void G4DNAMolecularReactionData::SetScaledParameterization (double temperature_K, double rateCste)
Definition at line 680 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 680 of file G4DNAMolecularReactionTable.cc
References fRateParam, and ScaledParameterization().
Referenced by G4ReactionTableMessenger::SetNewValue().
Member Data Documentation
G4double G4DNAMolecularReactionData::fEffectiveReactionRadius protected
Definition at line 141 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 141 of file G4DNAMolecularReactionTable.hh
Referenced by ComputeEffectiveRadius(), GetEffectiveReactionRadius(), and SetEffectiveReactionRadius().
G4double G4DNAMolecularReactionData::fObservedReactionRate protected
Definition at line 140 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 140 of file G4DNAMolecularReactionTable.hh
Referenced by ComputeEffectiveRadius(), GetObservedReactionRateConstant(), and SetObservedReactionRateConstant().
Reactant* G4DNAMolecularReactionData::fpReactant1 protected
Definition at line 138 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 138 of file G4DNAMolecularReactionTable.hh
Referenced by ComputeEffectiveRadius(), GetReactant1(), GetReactants(), SetReactant1(), and SetReactants().
Reactant* G4DNAMolecularReactionData::fpReactant2 protected
Definition at line 139 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 139 of file G4DNAMolecularReactionTable.hh
Referenced by ComputeEffectiveRadius(), GetReactant2(), GetReactants(), SetReactant2(), and SetReactants().
ReactionProducts G4DNAMolecularReactionData::fProducts protected
Definition at line 143 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 143 of file G4DNAMolecularReactionTable.hh
Referenced by AddProduct(), GetNbProducts(), GetProduct(), GetProducts(), RemoveProducts(), and ~G4DNAMolecularReactionData().
RateParam G4DNAMolecularReactionData::fRateParam protected
Definition at line 144 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 144 of file G4DNAMolecularReactionTable.hh
Referenced by ScaleForNewTemperature(), SetArrehniusParameterization(), SetPolynomialParameterization(), and SetScaledParameterization().
int G4DNAMolecularReactionData::fReactionID protected
Definition at line 145 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 145 of file G4DNAMolecularReactionTable.hh
Referenced by GetReactionID(), and SetReactionID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAMolecularReactionTable.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4DNAMolecularReactionTable.cc