ECCE @ EIC Software: G4INCL::HFB Namespace Reference
G4INCL::HFB Namespace Reference
Functions
void initialize ()
G4double getRadiusParameterHFB (const ParticleType t, const G4int A, const G4int Z)
Get the radius and diffuseness parameters from HFB calculations.
G4double getSurfaceDiffusenessHFB (const ParticleType t, const G4int A, const G4int Z)
Function Documentation
G4double G4INCL::HFB::getRadiusParameterHFB (const ParticleType t, const G4int A, const G4int Z)
Get the radius and diffuseness parameters from HFB calculations.
Definition at line 123 of file G4INCLHFB.cc.
View newest version in sPHENIX GitHub at line 123 of file G4INCLHFB.cc
References A(), G4INCL::Neutron, G4INCL::Proton, and Z.
Referenced by G4INCL::ParticleTable::getRadiusParameter(), and G4INCL::ParticleTable::getSurfaceDiffuseness().
G4double G4INCL::HFB::getSurfaceDiffusenessHFB (const ParticleType t, const G4int A, const G4int Z)
Definition at line 133 of file G4INCLHFB.cc.
View newest version in sPHENIX GitHub at line 133 of file G4INCLHFB.cc
References a, A(), G4INCL::Neutron, G4INCL::Proton, and Z.
Referenced by G4INCL::ParticleTable::getRadiusParameter(), and G4INCL::ParticleTable::getSurfaceDiffuseness().
void G4INCL::HFB::initialize ()
Definition at line 74 of file G4INCLHFB.cc.
View newest version in sPHENIX GitHub at line 74 of file G4INCLHFB.cc
References a, FatalException, G4endl, G4Exception(), INCL_DEBUG, and z.
Referenced by G4INCL::ParticleTable::initialize().