ECCE @ EIC Software: CLHEP::RandLandau Class Reference
CLHEP::RandLandau Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandLandau.h>
Public Member Functions
RandLandau (HepRandomEngine &anEngine)
RandLandau (HepRandomEngine *anEngine)
virtual ~RandLandau ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
double fire ()
void fireArray (const int size, double *vect)
double operator() ()
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static void shootArray (const int size, double *vect)
static double shoot (HepRandomEngine *anotherEngine)
static void shootArray (HepRandomEngine *anotherEngine, const int size, double *vect)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Protected Member Functions
static double transform (double r)
static double transformSmall (double r)
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 41 of file RandLandau.h.
View newest version in sPHENIX GitHub at line 41 of file RandLandau.h
Constructor & Destructor Documentation
CLHEP::RandLandau::RandLandau (HepRandomEngine & anEngine) inline
CLHEP::RandLandau::RandLandau (HepRandomEngine * anEngine) inline
CLHEP::RandLandau::~RandLandau () virtual
Definition at line 29 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 29 of file RandLandau.cc
Member Function Documentation
static std::string CLHEP::RandLandau::distributionName () inline static
Definition at line 98 of file RandLandau.h.
View newest version in sPHENIX GitHub at line 98 of file RandLandau.h
HepRandomEngine & CLHEP::RandLandau::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 27 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 27 of file RandLandau.cc
References localEngine.
double CLHEP::RandLandau::fire () inline
Referenced by fireArray().
void CLHEP::RandLandau::fireArray (const int size, double * vect)
Definition at line 46 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 46 of file RandLandau.cc
References fire(), and v.
std::istream & CLHEP::RandLandau::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 370 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 370 of file RandLandau.cc
References name().
std::string CLHEP::RandLandau::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 26 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 26 of file RandLandau.cc
Referenced by get(), and put().
double CLHEP::RandLandau::operator() () inline virtual
Reimplemented from CLHEP::HepRandom.
std::ostream & CLHEP::RandLandau::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 363 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 363 of file RandLandau.cc
References name(), and gammaraytel::pr.
static double CLHEP::RandLandau::shoot () inline static
Referenced by shootArray().
static double CLHEP::RandLandau::shoot (HepRandomEngine * anotherEngine) inline static
void CLHEP::RandLandau::shootArray (const int size, double * vect) static
Definition at line 32 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 32 of file RandLandau.cc
References shoot(), and v.
void CLHEP::RandLandau::shootArray (HepRandomEngine * anotherEngine, const int size, double * vect) static
Definition at line 39 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 39 of file RandLandau.cc
References shoot(), and v.
double CLHEP::RandLandau::transform (double r) static protected
Definition at line 285 of file RandLandau.cc.
View newest version in sPHENIX GitHub at line 285 of file RandLandau.cc
References d1, d2, f0(), f1, f2, int(), CLHEP::inverseLandau, n1, r, CLHEP::TABLE_MULTIPLIER, Acts::UnitConstants::u, x, and x2.
static double CLHEP::RandLandau::transformSmall (double r) static protected
Member Data Documentation
std::shared_ptr<HepRandomEngine> CLHEP::RandLandau::localEngine private
Definition at line 109 of file RandLandau.h.
View newest version in sPHENIX GitHub at line 109 of file RandLandau.h
Referenced by engine().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandLandau.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandLandau.cc