ECCE @ EIC Software: G4eeToPGammaModel Class Reference
G4eeToPGammaModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeToPGammaModel.hh>
Public Member Functions
G4eeToPGammaModel (G4eeCrossSections *, const G4String &, G4double, G4double)
virtual ~G4eeToPGammaModel ()
virtual G4double PeakEnergy () const override
virtual G4double ComputeCrossSection (G4double) const override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, G4double, const G4ThreeVector &) override
Public Member Functions inherited from G4Vee2hadrons
G4Vee2hadrons (G4eeCrossSections *cr, G4double vlowEnergy, G4double vhighEnergy, G4double vdelta)
virtual ~G4Vee2hadrons ()
G4PhysicsVector * PhysicsVector () const
G4double LowEnergy () const
G4double HighEnergy () const
Private Member Functions
G4eeToPGammaModel & operator= (const G4eeToPGammaModel &right)=delete
G4eeToPGammaModel (const G4eeToPGammaModel &)=delete
Private Attributes
G4ParticleDefinition * particle
G4ParticleDefinition * pi0
G4double massP
G4double massR
Additional Inherited Members
Protected Attributes inherited from G4Vee2hadrons
G4eeCrossSections * cross
Detailed Description
Definition at line 59 of file G4eeToPGammaModel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4eeToPGammaModel.hh
Constructor & Destructor Documentation
G4eeToPGammaModel::G4eeToPGammaModel (G4eeCrossSections * cr, const G4String & npart, G4double maxkinEnergy, G4double binWidth) explicit
Definition at line 64 of file G4eeToPGammaModel.cc.
View newest version in sPHENIX GitHub at line 64 of file G4eeToPGammaModel.cc
References G4Eta::Eta(), G4cout, G4endl, G4ParticleDefinition::GetPDGMass(), massP, massR, MeV, particle, pi0, and G4PionZero::PionZero().
G4eeToPGammaModel::~G4eeToPGammaModel () virtual
Definition at line 90 of file G4eeToPGammaModel.cc.
View newest version in sPHENIX GitHub at line 90 of file G4eeToPGammaModel.cc
G4eeToPGammaModel::G4eeToPGammaModel (const G4eeToPGammaModel &) private delete
Member Function Documentation
G4double G4eeToPGammaModel::ComputeCrossSection (G4double e) const override virtual
Implements G4Vee2hadrons.
Definition at line 102 of file G4eeToPGammaModel.cc.
View newest version in sPHENIX GitHub at line 102 of file G4eeToPGammaModel.cc
References G4Vee2hadrons::cross, G4eeCrossSections::CrossSectionEtaG(), G4eeCrossSections::CrossSectionPi0G(), particle, and pi0.
G4eeToPGammaModel& G4eeToPGammaModel::operator= (const G4eeToPGammaModel & right) private delete
G4double G4eeToPGammaModel::PeakEnergy () const override virtual
Implements G4Vee2hadrons.
Definition at line 95 of file G4eeToPGammaModel.cc.
View newest version in sPHENIX GitHub at line 95 of file G4eeToPGammaModel.cc
References massR.
void G4eeToPGammaModel::SampleSecondaries (std::vector< G4DynamicParticle * > * newp, G4double e, const G4ThreeVector & direction) override virtual
Implements G4Vee2hadrons.
Definition at line 112 of file G4eeToPGammaModel.cc.
View newest version in sPHENIX GitHub at line 112 of file G4eeToPGammaModel.cc
References dir, G4UniformRand, G4Gamma::Gamma(), massP, massR, particle, phi, CLHEP::Hep3Vector::rotateUz(), and twopi.
Member Data Documentation
G4double G4eeToPGammaModel::massP private
Definition at line 85 of file G4eeToPGammaModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4eeToPGammaModel.hh
Referenced by G4eeToPGammaModel(), and SampleSecondaries().
G4double G4eeToPGammaModel::massR private
Definition at line 86 of file G4eeToPGammaModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4eeToPGammaModel.hh
Referenced by G4eeToPGammaModel(), PeakEnergy(), and SampleSecondaries().
G4ParticleDefinition* G4eeToPGammaModel::particle private
Definition at line 82 of file G4eeToPGammaModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4eeToPGammaModel.hh
Referenced by ComputeCrossSection(), G4eeToPGammaModel(), and SampleSecondaries().
G4ParticleDefinition* G4eeToPGammaModel::pi0 private
Definition at line 83 of file G4eeToPGammaModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4eeToPGammaModel.hh
Referenced by ComputeCrossSection(), and G4eeToPGammaModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeToPGammaModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4eeToPGammaModel.cc