ECCE @ EIC Software: G4VPDigitsCollectionIO Class Reference
G4VPDigitsCollectionIO Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPDigitsCollectionIO.hh>
Public Member Functions
G4VPDigitsCollectionIO (std::string detName, std::string colName)
virtual ~G4VPDigitsCollectionIO ()
virtual G4bool Store (const G4VDigiCollection *)=0
virtual G4bool Retrieve (G4VDigiCollection *&)=0
G4bool operator== (const G4VPDigitsCollectionIO &right) const
std::string DMname ()
std::string CollectionName ()
void SetVerboseLevel (int v)
Protected Attributes
G4int m_verbose
std::string f_detName
std::string f_colName
Detailed Description
Definition at line 39 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VPDigitsCollectionIO.hh
Constructor & Destructor Documentation
G4VPDigitsCollectionIO::G4VPDigitsCollectionIO (std::string detName, std::string colName)
Definition at line 34 of file G4VPDigitsCollectionIO.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VPDigitsCollectionIO.cc
virtual G4VPDigitsCollectionIO::~G4VPDigitsCollectionIO () inline virtual
Definition at line 45 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VPDigitsCollectionIO.hh
Member Function Documentation
std::string G4VPDigitsCollectionIO::CollectionName () inline
Definition at line 65 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VPDigitsCollectionIO.hh
References f_colName.
std::string G4VPDigitsCollectionIO::DMname () inline
Definition at line 62 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VPDigitsCollectionIO.hh
References f_detName.
Referenced by G4DCIOcatalog::RegisterDCIOmanager().
G4bool G4VPDigitsCollectionIO::operator== (const G4VPDigitsCollectionIO & right) const
Definition at line 40 of file G4VPDigitsCollectionIO.cc.
View newest version in sPHENIX GitHub at line 40 of file G4VPDigitsCollectionIO.cc
References f_colName, and f_detName.
virtual G4bool G4VPDigitsCollectionIO::Retrieve (G4VDigiCollection *&) pure virtual
void G4VPDigitsCollectionIO::SetVerboseLevel (int v) inline
Definition at line 68 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPDigitsCollectionIO.hh
References m_verbose, and v.
Referenced by G4VPDigitIO::SetVerboseLevel(), and G4PersistencyManager::SetVerboseLevel().
virtual G4bool G4VPDigitsCollectionIO::Store (const G4VDigiCollection *) pure virtual
Member Data Documentation
std::string G4VPDigitsCollectionIO::f_colName protected
Definition at line 74 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VPDigitsCollectionIO.hh
Referenced by CollectionName(), and operator==().
std::string G4VPDigitsCollectionIO::f_detName protected
Definition at line 73 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VPDigitsCollectionIO.hh
Referenced by DMname(), and operator==().
G4int G4VPDigitsCollectionIO::m_verbose protected
Definition at line 68 of file G4VPDigitsCollectionIO.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPDigitsCollectionIO.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPDigitsCollectionIO.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4VPDigitsCollectionIO.cc