ECCE @ EIC Software: G4tgbMaterialMixtureByNoAtoms Class Reference
G4tgbMaterialMixtureByNoAtoms Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixtureByNoAtoms.hh>
Public Member Functions
G4tgbMaterialMixtureByNoAtoms (G4tgrMaterial *tgr)
G4tgbMaterialMixtureByNoAtoms ()
~G4tgbMaterialMixtureByNoAtoms ()
G4Material * BuildG4Material ()
void TransformToFractionsByWeight ()
Public Member Functions inherited from G4tgbMaterialMixture
G4tgbMaterialMixture ()
virtual ~G4tgbMaterialMixture ()
virtual const G4String & GetComponent (G4int i) const
virtual G4double GetFraction (G4int i) const
G4tgbMaterialMixture & operator= (const G4tgbMaterialMixture &)
Public Member Functions inherited from G4tgbMaterial
G4tgbMaterial ()
virtual ~G4tgbMaterial ()
G4tgbMaterial (G4tgrMaterial *tgr)
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfMaterials () const
G4double GetA () const
G4double GetZ () const
const G4String & GetType () const
G4tgrMaterial * GetTgrMate () const
Additional Inherited Members
Protected Attributes inherited from G4tgbMaterial
G4tgrMaterial * theTgrMate
G4Material * theG4Mate
Detailed Description
Definition at line 49 of file G4tgbMaterialMixtureByNoAtoms.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialMixtureByNoAtoms.hh
Constructor & Destructor Documentation
G4tgbMaterialMixtureByNoAtoms::G4tgbMaterialMixtureByNoAtoms (G4tgrMaterial * tgr)
Definition at line 57 of file G4tgbMaterialMixtureByNoAtoms.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgbMaterialMixtureByNoAtoms.cc
References G4tgbMaterial::theTgrMate.
G4tgbMaterialMixtureByNoAtoms::G4tgbMaterialMixtureByNoAtoms ()
Definition at line 44 of file G4tgbMaterialMixtureByNoAtoms.cc.
View newest version in sPHENIX GitHub at line 44 of file G4tgbMaterialMixtureByNoAtoms.cc
G4tgbMaterialMixtureByNoAtoms::~G4tgbMaterialMixtureByNoAtoms ()
Definition at line 50 of file G4tgbMaterialMixtureByNoAtoms.cc.
View newest version in sPHENIX GitHub at line 50 of file G4tgbMaterialMixtureByNoAtoms.cc
Member Function Documentation
G4Material * G4tgbMaterialMixtureByNoAtoms::BuildG4Material () virtual
Implements G4tgbMaterial.
Definition at line 64 of file G4tgbMaterialMixtureByNoAtoms.cc.
View newest version in sPHENIX GitHub at line 64 of file G4tgbMaterialMixtureByNoAtoms.cc
References G4Material::AddElement(), cm3, FatalException, G4tgbMaterialMgr::FindOrBuildG4Element(), Acts::UnitConstants::g, G4cout, G4endl, G4Exception(), G4tgbMaterialMixture::GetComponent(), G4tgrMaterial::GetDensity(), G4tgbMaterialMixture::GetFraction(), G4tgbMaterialMgr::GetInstance(), G4tgrMaterial::GetName(), G4Element::GetName(), G4tgrMaterial::GetNumberOfComponents(), G4tgrMaterial::GetPressure(), G4tgrMaterial::GetState(), G4tgrMaterial::GetTemperature(), G4tgrMessenger::GetVerboseLevel(), and G4tgbMaterial::theTgrMate.
void G4tgbMaterialMixtureByNoAtoms::TransformToFractionsByWeight () virtual
Reimplemented from G4tgbMaterialMixture.
Definition at line 134 of file G4tgbMaterialMixtureByNoAtoms.cc.
View newest version in sPHENIX GitHub at line 134 of file G4tgbMaterialMixtureByNoAtoms.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixtureByNoAtoms.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterialMixtureByNoAtoms.cc