ECCE @ EIC Software: G4ParameterisationPolyhedraPhi Class Reference
G4ParameterisationPolyhedraPhi Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPolyhedra.hh>
Public Member Functions
G4ParameterisationPolyhedraPhi (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *motherSolid, DivisionType divType)
~G4ParameterisationPolyhedraPhi ()
void CheckParametersValidity ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Polyhedra &phedra, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VParameterisationPolyhedra
G4VParameterisationPolyhedra (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationPolyhedra ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VDivisionParameterisation
G4String ftype
EAxis faxis
G4int fnDiv = 0
G4double fwidth = 0.0
G4double foffset = 0.0
DivisionType fDivisionType
G4VSolid * fmotherSolid = nullptr
G4bool fReflectedSolid = false
G4bool fDeleteSolid = false
G4int theVoluFirstCopyNo = 1
G4double kCarTolerance
G4double fhgap = 0.0
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 130 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ParameterisationPolyhedra.hh
Constructor & Destructor Documentation
G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid * motherSolid, DivisionType divType)
Definition at line 284 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 284 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::CalculateWidth(), CheckParametersValidity(), DivWIDTH, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Polyhedra::GetEndPhi(), G4Polyhedra::GetNumSide(), G4Polyhedra::GetStartPhi(), G4VDivisionParameterisation::SetType(), and G4VDivisionParameterisation::verbose.
G4ParameterisationPolyhedraPhi::~G4ParameterisationPolyhedraPhi ()
Definition at line 314 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 314 of file G4ParameterisationPolyhedra.cc
Member Function Documentation
void G4ParameterisationPolyhedraPhi::CheckParametersValidity () virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 326 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 326 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::CheckParametersValidity(), DivNDIVandWIDTH, DivWIDTH, FatalException, G4VDivisionParameterisation::fDivisionType, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4endl, G4Exception(), G4VSolid::GetName(), G4Polyhedra::GetOriginalParameters(), JustWarning, message(), and G4PolyhedraHistorical::numSide.
Referenced by G4ParameterisationPolyhedraPhi().
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Polyhedra & phedra, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 407 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 407 of file G4ParameterisationPolyhedra.cc
References G4VSolid::DumpInfo(), G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Polyhedra::GetOriginalParameters(), G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, G4Polyhedra::Reset(), G4Polyhedra::SetOriginalParameters(), G4PolyhedraHistorical::Start_angle, and G4VDivisionParameterisation::verbose.
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 151 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 153 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 155 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 157 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 159 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 161 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 163 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 165 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 167 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 169 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 171 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 173 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraPhi::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 371 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 371 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::ChangeRotMatrix(), deg, G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fwidth, G4cout, G4endl, Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), and G4VDivisionParameterisation::verbose.
G4double G4ParameterisationPolyhedraPhi::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 319 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 319 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::fmotherSolid, G4Polyhedra::GetEndPhi(), and G4Polyhedra::GetStartPhi().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPolyhedra.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationPolyhedra.cc