ECCE @ EIC Software: G4PseudoScene Class Reference
G4PseudoScene Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PseudoScene.hh>
Public Member Functions
G4PseudoScene ()
virtual ~G4PseudoScene ()
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
void PostAddSolid ()
void AddSolid (const G4Box &solid)
void AddSolid (const G4Cons &solid)
void AddSolid (const G4Orb &solid)
void AddSolid (const G4Para &solid)
void AddSolid (const G4Sphere &solid)
void AddSolid (const G4Torus &solid)
void AddSolid (const G4Trap &solid)
void AddSolid (const G4Trd &solid)
void AddSolid (const G4Tubs &solid)
void AddSolid (const G4Ellipsoid &solid)
void AddSolid (const G4Polycone &solid)
void AddSolid (const G4Polyhedra &solid)
void AddSolid (const G4TessellatedSolid &solid)
void AddSolid (const G4VSolid &solid)
void AddCompound (const G4VTrajectory &)
void AddCompound (const G4VHit &)
void AddCompound (const G4VDigi &)
void AddCompound (const G4THitsMap< G4double > &)
void AddCompound (const G4THitsMap< G4StatDouble > &)
void BeginPrimitives (const G4Transform3D &)
void EndPrimitives ()
void BeginPrimitives2D (const G4Transform3D &)
void EndPrimitives2D ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Scale &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polymarker &)
void AddPrimitive (const G4Polyhedron &)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
virtual const G4VisExtent & GetExtent () const
Protected Member Functions
virtual void ProcessVolume (const G4VSolid &)=0
Protected Attributes
const G4Transform3D * fpCurrentObjectTransformation
Detailed Description
Definition at line 50 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 50 of file G4PseudoScene.hh
Constructor & Destructor Documentation
G4PseudoScene::G4PseudoScene () inline
Definition at line 54 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 54 of file G4PseudoScene.hh
virtual G4PseudoScene::~G4PseudoScene () inline virtual
Definition at line 55 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 55 of file G4PseudoScene.hh
Member Function Documentation
void G4PseudoScene::AddCompound (const G4VTrajectory &) inline virtual
Implements G4VGraphicsScene.
Definition at line 78 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PseudoScene.hh
void G4PseudoScene::AddCompound (const G4VHit &) inline virtual
Implements G4VGraphicsScene.
Definition at line 79 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 79 of file G4PseudoScene.hh
void G4PseudoScene::AddCompound (const G4VDigi &) inline virtual
Implements G4VGraphicsScene.
Definition at line 80 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 80 of file G4PseudoScene.hh
void G4PseudoScene::AddCompound (const G4THitsMap< G4double > &) inline virtual
Implements G4VGraphicsScene.
Definition at line 81 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 81 of file G4PseudoScene.hh
void G4PseudoScene::AddCompound (const G4THitsMap< G4StatDouble > &) inline virtual
Implements G4VGraphicsScene.
Definition at line 82 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 82 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Polyline &) inline virtual
Implements G4VGraphicsScene.
Definition at line 88 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Scale &) inline virtual
Implements G4VGraphicsScene.
Definition at line 89 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Text &) inline virtual
Implements G4VGraphicsScene.
Definition at line 90 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Circle &) inline virtual
Implements G4VGraphicsScene.
Definition at line 91 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Square &) inline virtual
Implements G4VGraphicsScene.
Definition at line 92 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Polymarker &) inline virtual
Implements G4VGraphicsScene.
Definition at line 93 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PseudoScene.hh
void G4PseudoScene::AddPrimitive (const G4Polyhedron &) inline virtual
Implements G4VGraphicsScene.
Definition at line 94 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PseudoScene.hh
void G4PseudoScene::AddSolid (const G4Box & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 61 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 61 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Cons & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 62 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Orb & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 63 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Para & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 64 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 64 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Sphere & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 65 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Torus & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 66 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 66 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Trap & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 67 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Trd & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 68 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Tubs & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 69 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Ellipsoid & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 71 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Polycone & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 72 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4Polyhedra & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 73 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4TessellatedSolid & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 74 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::AddSolid (const G4VSolid & solid) inline virtual
Implements G4VGraphicsScene.
Definition at line 76 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PseudoScene.hh
References ProcessVolume().
void G4PseudoScene::BeginPrimitives (const G4Transform3D &) inline virtual
Implements G4VGraphicsScene.
Definition at line 84 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 84 of file G4PseudoScene.hh
void G4PseudoScene::BeginPrimitives2D (const G4Transform3D &) inline virtual
Implements G4VGraphicsScene.
Definition at line 86 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PseudoScene.hh
void G4PseudoScene::EndPrimitives () inline virtual
Implements G4VGraphicsScene.
Definition at line 85 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 85 of file G4PseudoScene.hh
void G4PseudoScene::EndPrimitives2D () inline virtual
Implements G4VGraphicsScene.
Definition at line 87 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 87 of file G4PseudoScene.hh
void G4PseudoScene::PostAddSolid () inline virtual
Implements G4VGraphicsScene.
Definition at line 59 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PseudoScene.hh
void G4PseudoScene::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes &) inline virtual
Implements G4VGraphicsScene.
Definition at line 56 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 56 of file G4PseudoScene.hh
References fpCurrentObjectTransformation.
virtual void G4PseudoScene::ProcessVolume (const G4VSolid &) protected pure virtual
Implemented in G4PhysicalVolumesSearchScene, G4PhysicalVolumeMassScene, G4BoundingSphereScene, G4PhysicalVolumeSearchScene, G4BoundingExtentScene, and G4TouchablePropertiesScene.
Referenced by AddSolid().
Member Data Documentation
const G4Transform3D* G4PseudoScene::fpCurrentObjectTransformation protected
Definition at line 99 of file G4PseudoScene.hh.
View newest version in sPHENIX GitHub at line 99 of file G4PseudoScene.hh
Referenced by PreAddSolid(), G4BoundingExtentScene::ProcessVolume(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4BoundingSphereScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), G4BoundingExtentScene::ResetBoundingExtent(), and G4BoundingSphereScene::ResetBoundingSphere().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PseudoScene.hh