ECCE @ EIC Software: G4UIterminal Class Reference
G4UIterminal Class Reference
#include <geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4UIterminal.hh>
Public Member Functions
G4UIterminal (G4VUIshell *aShell=0, G4bool qsig=true)
~G4UIterminal ()
void SetPrompt (const G4String &prompt)
virtual G4UIsession * SessionStart ()
virtual void PauseSessionStart (const G4String &msg)
virtual G4int ReceiveG4cout (const G4String &coutString)
virtual G4int ReceiveG4cerr (const G4String &cerrString)
Public Member Functions inherited from G4VBasicShell
G4VBasicShell ()
virtual ~G4VBasicShell ()
Public Member Functions inherited from G4UIsession
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
G4int GetLastReturnCode () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Private Member Functions
virtual void ExecuteCommand (const G4String &aCommand)
virtual G4bool GetHelpChoice (G4int &aInt)
virtual void ExitHelp () const
G4String GetCommand (const char *msg=0)
Private Attributes
G4UImanager * UI
G4VUIshell * shell
G4bool iExit
G4bool iCont
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Public Member Functions inherited from G4UIsession
static G4int InSession ()
Protected Member Functions inherited from G4VBasicShell
G4String ModifyToFullPathCommand (const char *aCommandLine) const
G4String GetCurrentWorkingDirectory () const
G4bool ChangeDirectory (const char *newDir)
G4UIcommandTree * FindDirectory (const char *dirName) const
G4UIcommand * FindCommand (const char *commandName) const
G4String Complete (const G4String &)
G4String FindMatchingPath (G4UIcommandTree *, const G4String &)
void ApplyShellCommand (const G4String &, G4bool &, G4bool &)
void ShowCurrent (const G4String &) const
void ChangeDirectoryCommand (const G4String &)
void ListDirectory (const G4String &) const
void TerminalHelp (const G4String &)
Protected Attributes inherited from G4UIsession
G4int ifBatch
G4int lastRC
Static Protected Attributes inherited from G4UIsession
static G4ICOMS_DLL G4int inSession = 0
Detailed Description
Definition at line 70 of file G4UIterminal.hh.
View newest version in sPHENIX GitHub at line 70 of file G4UIterminal.hh
Constructor & Destructor Documentation
G4UIterminal::G4UIterminal (G4VUIshell * aShell = 0, G4bool qsig = true)
Definition at line 90 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 90 of file G4UIterminal.cc
References FALSE, G4UImanager::GetUIpointer(), iCont, iExit, shell, SignalHandler(), theshell, and UI.
G4UIterminal::~G4UIterminal ()
Definition at line 113 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 113 of file G4UIterminal.cc
References G4UImanager::GetUIpointer(), shell, and UI.
Member Function Documentation
void G4UIterminal::ExecuteCommand (const G4String & aCommand) private virtual
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Reimplemented from G4VBasicShell.
Definition at line 160 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 160 of file G4UIterminal.cc
References fAliasNotFound, fCommandNotFound, fCommandSucceeded, fIllegalApplicationState, G4VBasicShell::FindCommand(), fParameterOutOfCandidates, fParameterOutOfRange, fParameterUnreadable, G4cerr, G4cout, G4endl, G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4String::index(), G4UImanager::SolveAlias(), and UI.
Referenced by PauseSessionStart(), and SessionStart().
void G4UIterminal::ExitHelp () const private virtual
Implements G4VBasicShell.
Definition at line 335 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 335 of file G4UIterminal.cc
References G4cin.
G4String G4UIterminal::GetCommand (const char * msg = 0) private
Definition at line 211 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 211 of file G4UIterminal.cc
References G4VBasicShell::ChangeDirectoryCommand(), FALSE, G4cerr, G4cout, G4endl, G4VBasicShell::GetCurrentWorkingDirectory(), G4UImanager::GetPreviousCommand(), iCont, iExit, G4String::leading, G4VBasicShell::ListDirectory(), G4VBasicShell::ModifyToFullPathCommand(), G4String::remove(), shell, G4VBasicShell::ShowCurrent(), G4String::strip(), G4VBasicShell::TerminalHelp(), and UI.
Referenced by PauseSessionStart(), and SessionStart().
G4bool G4UIterminal::GetHelpChoice (G4int & aInt) private virtual
Implements G4VBasicShell.
Definition at line 322 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 322 of file G4UIterminal.cc
References FALSE, G4cin, and TRUE.
void G4UIterminal::PauseSessionStart (const G4String & msg) virtual
Implements G4VBasicShell.
Definition at line 147 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 147 of file G4UIterminal.cc
References ExecuteCommand(), GetCommand(), iCont, and TRUE.
G4int G4UIterminal::ReceiveG4cerr (const G4String & cerrString) virtual
Reimplemented from G4UIsession.
Definition at line 314 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 314 of file G4UIterminal.cc
G4int G4UIterminal::ReceiveG4cout (const G4String & coutString) virtual
Reimplemented from G4UIsession.
Definition at line 306 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 306 of file G4UIterminal.cc
G4UIsession * G4UIterminal::SessionStart () virtual
Implements G4VBasicShell.
Definition at line 133 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 133 of file G4UIterminal.cc
References ExecuteCommand(), GetCommand(), iExit, and TRUE.
void G4UIterminal::SetPrompt (const G4String & prompt)
Definition at line 126 of file G4UIterminal.cc.
View newest version in sPHENIX GitHub at line 126 of file G4UIterminal.cc
References shell.
Member Data Documentation
G4bool G4UIterminal::iCont private
Definition at line 78 of file G4UIterminal.hh.
View newest version in sPHENIX GitHub at line 78 of file G4UIterminal.hh
Referenced by G4UIterminal(), GetCommand(), and PauseSessionStart().
G4bool G4UIterminal::iExit private
Definition at line 77 of file G4UIterminal.hh.
View newest version in sPHENIX GitHub at line 77 of file G4UIterminal.hh
Referenced by G4UIterminal(), GetCommand(), and SessionStart().
G4VUIshell* G4UIterminal::shell private
Definition at line 74 of file G4UIterminal.hh.
View newest version in sPHENIX GitHub at line 74 of file G4UIterminal.hh
Referenced by G4UIterminal(), GetCommand(), SetPrompt(), and ~G4UIterminal().
G4UImanager* G4UIterminal::UI private
Definition at line 72 of file G4UIterminal.hh.
View newest version in sPHENIX GitHub at line 72 of file G4UIterminal.hh
Referenced by ExecuteCommand(), G4UIterminal(), GetCommand(), and ~G4UIterminal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4UIterminal.hh
geant4/tree/geant4-10.6-release/source/interfaces/basic/src/G4UIterminal.cc