ECCE @ EIC Software: G4UnboundPN Class Reference
G4UnboundPN Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4UnboundPN.hh>
Static Public Member Functions
static G4UnboundPN * Definition ()
static G4UnboundPN * UnboundPNDefinition ()
static G4UnboundPN * UnboundPN ()
Private Member Functions
G4UnboundPN ()
~G4UnboundPN ()
Static Private Attributes
static G4UnboundPN * theInstance = 0
Additional Inherited Members
Public Member Functions inherited from G4VShortLivedParticle
G4VShortLivedParticle (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable)
virtual ~G4VShortLivedParticle ()
G4bool operator== (const G4VShortLivedParticle &right) const
G4bool operator!= (const G4VShortLivedParticle &right) const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 46 of file G4UnboundPN.hh.
View newest version in sPHENIX GitHub at line 46 of file G4UnboundPN.hh
Constructor & Destructor Documentation
G4UnboundPN::G4UnboundPN () private
Definition at line 58 of file G4UnboundPN.cc.
View newest version in sPHENIX GitHub at line 58 of file G4UnboundPN.cc
Referenced by Definition().
G4UnboundPN::~G4UnboundPN () inline private
Definition at line 50 of file G4UnboundPN.hh.
View newest version in sPHENIX GitHub at line 50 of file G4UnboundPN.hh
References theInstance.
Member Function Documentation
G4UnboundPN * G4UnboundPN::Definition () static
Definition at line 66 of file G4UnboundPN.cc.
View newest version in sPHENIX GitHub at line 66 of file G4UnboundPN.cc
References G4UnboundPN(), G4ParticleTable::GetParticleTable(), G4ParticleTable::GetReadiness(), G4ParticleTable::Remove(), G4ParticleTable::SetReadiness(), and theInstance.
Referenced by G4CascadeInterface::Initialize(), G4InuclElementaryParticle::makeDefinition(), G4InuclElementaryParticle::type(), UnboundPN(), and UnboundPNDefinition().
G4UnboundPN * G4UnboundPN::UnboundPN () static
Definition at line 82 of file G4UnboundPN.cc.
View newest version in sPHENIX GitHub at line 82 of file G4UnboundPN.cc
References Definition().
G4UnboundPN * G4UnboundPN::UnboundPNDefinition () static
Definition at line 81 of file G4UnboundPN.cc.
View newest version in sPHENIX GitHub at line 81 of file G4UnboundPN.cc
References Definition().
Member Data Documentation
G4UnboundPN * G4UnboundPN::theInstance = 0 static private
Definition at line 48 of file G4UnboundPN.hh.
View newest version in sPHENIX GitHub at line 48 of file G4UnboundPN.hh
Referenced by Definition(), and ~G4UnboundPN().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4UnboundPN.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4UnboundPN.cc