ECCE @ EIC Software: GammaRayTelRunAction Class Reference
GammaRayTelRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelRunAction.hh>
Public Member Functions
GammaRayTelRunAction ()
~GammaRayTelRunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
std::ofstream * GetOutputFile ()
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Member Functions
void OpenFile ()
Private Attributes
std::ofstream * outFile
G4String fileName
G4int fRunID
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 50 of file GammaRayTelRunAction.hh.
View newest version in sPHENIX GitHub at line 50 of file GammaRayTelRunAction.hh
Constructor & Destructor Documentation
GammaRayTelRunAction::GammaRayTelRunAction ()
Definition at line 54 of file GammaRayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 54 of file GammaRayTelRunAction.cc
GammaRayTelRunAction::~GammaRayTelRunAction ()
Definition at line 61 of file GammaRayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 61 of file GammaRayTelRunAction.cc
Member Function Documentation
void GammaRayTelRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 66 of file GammaRayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 66 of file GammaRayTelRunAction.cc
References static_analysis_results::analysis(), G4UImanager::ApplyCommand(), GammaRayTelAnalysis::BeginOfRun(), fRunID, G4cout, G4endl, G4VVisManager::GetConcreteInstance(), GammaRayTelAnalysis::getInstance(), G4Run::GetRunID(), G4UImanager::GetUIpointer(), and G4UserRunAction::IsMaster().
void GammaRayTelRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 91 of file GammaRayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 91 of file GammaRayTelRunAction.cc
References static_analysis_results::analysis(), GammaRayTelAnalysis::EndOfRun(), fileName, G4cout, G4endl, GammaRayTelAnalysis::getInstance(), G4Run::GetRunID(), and outFile.
std::ofstream * GammaRayTelRunAction::GetOutputFile ()
Definition at line 114 of file GammaRayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 114 of file GammaRayTelRunAction.cc
References OpenFile(), and outFile.
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelRunAction::OpenFile () private
Definition at line 122 of file GammaRayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 122 of file GammaRayTelRunAction.cc
References fileName, fRunID, G4cout, G4endl, G4Threading::G4GetThreadId(), and outFile.
Referenced by GetOutputFile().
Member Data Documentation
G4String GammaRayTelRunAction::fileName private
Definition at line 64 of file GammaRayTelRunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file GammaRayTelRunAction.hh
Referenced by EndOfRunAction(), and OpenFile().
G4int GammaRayTelRunAction::fRunID private
Definition at line 67 of file GammaRayTelRunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file GammaRayTelRunAction.hh
Referenced by BeginOfRunAction(), and OpenFile().
std::ofstream* GammaRayTelRunAction::outFile private
Definition at line 63 of file GammaRayTelRunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file GammaRayTelRunAction.hh
Referenced by EndOfRunAction(), GetOutputFile(), and OpenFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelRunAction.cc