ECCE @ EIC Software: G4RKFieldIntegrator Class Reference
G4RKFieldIntegrator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4RKFieldIntegrator.hh>
Public Member Functions
G4RKFieldIntegrator ()
G4RKFieldIntegrator (const G4RKFieldIntegrator &)
~G4RKFieldIntegrator ()
const G4RKFieldIntegrator & operator= (const G4RKFieldIntegrator &)
G4bool operator== (const G4RKFieldIntegrator &) const
G4bool operator!= (const G4RKFieldIntegrator &) const
void Transport (G4KineticTrackVector &theActive, const G4KineticTrackVector &theSpectators, G4double theTimeStep)
G4double GetExcitationEnergy (G4int nHitNucleons, const G4KineticTrackVector &theParticles)
void Init (G4int z, G4int a)
G4double GetNeutronPotential (G4double radius)
G4double GetNeutronPotential (G4ThreeVector &aPosition)
G4double GetProtonPotential (G4double radius)
G4double GetProtonPotential (G4ThreeVector &aPosition)
G4double GetAntiprotonPotential (G4double radius)
G4double GetAntiprotonPotential (G4ThreeVector &aPosition)
G4double GetKaonPotential (G4double radius)
G4double GetKaonPotential (G4ThreeVector &aPosition)
G4double GetPionPotential (G4double radius)
G4double GetPionPotential (G4ThreeVector &aPosition)
Public Member Functions inherited from G4FieldPropagation
G4FieldPropagation ()
G4FieldPropagation (const G4FieldPropagation &)
virtual ~G4FieldPropagation ()
Private Member Functions
void Integrate (const G4KineticTrackVector &theActive, G4double theTimeStep)
G4double CalculateTotalEnergy (const G4KineticTrackVector &Barions)
G4double Erf (G4double X)
Private Attributes
G4int theA
G4int theZ
Static Private Attributes
static const G4double coulomb = 1.44 / 1.14 * MeV
static const G4double a_kaon = 0.35
static const G4double a_pion = 0.35
! for pions it has todiffer from kaons
static const G4double a_antiproton = 1.53
Detailed Description
Definition at line 31 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 31 of file G4RKFieldIntegrator.hh
Constructor & Destructor Documentation
G4RKFieldIntegrator::G4RKFieldIntegrator () inline
Definition at line 34 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 34 of file G4RKFieldIntegrator.hh
G4RKFieldIntegrator::G4RKFieldIntegrator (const G4RKFieldIntegrator &) inline
Definition at line 35 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 35 of file G4RKFieldIntegrator.hh
G4RKFieldIntegrator::~G4RKFieldIntegrator () inline
Definition at line 37 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 37 of file G4RKFieldIntegrator.hh
Member Function Documentation
G4double G4RKFieldIntegrator::CalculateTotalEnergy (const G4KineticTrackVector & Barions) private
Definition at line 53 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 53 of file G4RKFieldIntegrator.cc
References G4Pow::A23(), Alpha, c1, c2, CLHEP::HepLorentzVector::e(), Erf(), fermi, G4Exp(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4Pow::GetInstance(), G4ParticleDefinition::GetPDGCharge(), G4KineticTrack::GetPosition(), pi, G4Pow::powA(), and t1.
G4double G4RKFieldIntegrator::Erf (G4double X) private
Definition at line 103 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 103 of file G4RKFieldIntegrator.cc
References kdfinder::abs(), c1, C1, G4Exp(), H, P10, P11, P2, Y, and Z1.
Referenced by CalculateTotalEnergy().
G4double G4RKFieldIntegrator::GetAntiprotonPotential (G4double radius) virtual
Implements G4FieldPropagation.
Definition at line 296 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 296 of file G4RKFieldIntegrator.cc
G4double G4RKFieldIntegrator::GetAntiprotonPotential (G4ThreeVector & aPosition) inline virtual
Implements G4FieldPropagation.
Definition at line 61 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RKFieldIntegrator.hh
References GetAntiprotonPotential(), and CLHEP::Hep3Vector::mag().
Referenced by GetAntiprotonPotential().
G4double G4RKFieldIntegrator::GetExcitationEnergy (G4int nHitNucleons, const G4KineticTrackVector & theParticles) virtual
Implements G4FieldPropagation.
Definition at line 185 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 185 of file G4RKFieldIntegrator.cc
References c1, G4Log(), and G4UniformRand.
G4double G4RKFieldIntegrator::GetKaonPotential (G4double radius) virtual
Implements G4FieldPropagation.
Definition at line 326 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 326 of file G4RKFieldIntegrator.cc
G4double G4RKFieldIntegrator::GetKaonPotential (G4ThreeVector & aPosition) inline virtual
Implements G4FieldPropagation.
Definition at line 64 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RKFieldIntegrator.hh
References GetKaonPotential(), and CLHEP::Hep3Vector::mag().
Referenced by GetKaonPotential().
G4double G4RKFieldIntegrator::GetNeutronPotential (G4double radius) virtual
Implements G4FieldPropagation.
Definition at line 239 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 239 of file G4RKFieldIntegrator.cc
G4double G4RKFieldIntegrator::GetNeutronPotential (G4ThreeVector & aPosition) inline virtual
Implements G4FieldPropagation.
Definition at line 55 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 55 of file G4RKFieldIntegrator.hh
References GetNeutronPotential(), and CLHEP::Hep3Vector::mag().
Referenced by GetNeutronPotential().
G4double G4RKFieldIntegrator::GetPionPotential (G4double radius) virtual
Implements G4FieldPropagation.
Definition at line 356 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 356 of file G4RKFieldIntegrator.cc
G4double G4RKFieldIntegrator::GetPionPotential (G4ThreeVector & aPosition) inline virtual
Implements G4FieldPropagation.
Definition at line 67 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RKFieldIntegrator.hh
References GetPionPotential(), and CLHEP::Hep3Vector::mag().
Referenced by GetPionPotential().
G4double G4RKFieldIntegrator::GetProtonPotential (G4double radius) virtual
Implements G4FieldPropagation.
Definition at line 266 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 266 of file G4RKFieldIntegrator.cc
G4double G4RKFieldIntegrator::GetProtonPotential (G4ThreeVector & aPosition) inline virtual
Implements G4FieldPropagation.
Definition at line 58 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 58 of file G4RKFieldIntegrator.hh
References GetProtonPotential(), and CLHEP::Hep3Vector::mag().
Referenced by GetProtonPotential().
void G4RKFieldIntegrator::Init (G4int z, G4int a) inline virtual
Implements G4FieldPropagation.
Definition at line 51 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RKFieldIntegrator.hh
References a, theA, theZ, and z.
void G4RKFieldIntegrator::Integrate (const G4KineticTrackVector & theActive, G4double theTimeStep) private
Definition at line 210 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 210 of file G4RKFieldIntegrator.cc
References CLHEP::HepLorentzVector::boostVector(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetPosition(), and G4KineticTrack::SetPosition().
G4bool G4RKFieldIntegrator::operator!= (const G4RKFieldIntegrator &) const inline
Definition at line 43 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 43 of file G4RKFieldIntegrator.hh
const G4RKFieldIntegrator& G4RKFieldIntegrator::operator= (const G4RKFieldIntegrator &) inline
Definition at line 40 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 40 of file G4RKFieldIntegrator.hh
G4bool G4RKFieldIntegrator::operator== (const G4RKFieldIntegrator &) const inline
Definition at line 42 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 42 of file G4RKFieldIntegrator.hh
void G4RKFieldIntegrator::Transport (G4KineticTrackVector & theActive, const G4KineticTrackVector & theSpectators, G4double theTimeStep) virtual
Implements G4FieldPropagation.
Definition at line 45 of file G4RKFieldIntegrator.cc.
View newest version in sPHENIX GitHub at line 45 of file G4RKFieldIntegrator.cc
References void().
Member Data Documentation
const G4double G4RKFieldIntegrator::a_antiproton = 1.53 static private
Definition at line 83 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RKFieldIntegrator.hh
const G4double G4RKFieldIntegrator::a_kaon = 0.35 static private
Definition at line 81 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RKFieldIntegrator.hh
const G4double G4RKFieldIntegrator::a_pion = 0.35 static private
! for pions it has todiffer from kaons
Definition at line 82 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RKFieldIntegrator.hh
const G4double G4RKFieldIntegrator::coulomb = 1.44 / 1.14 * MeV static private
Definition at line 80 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RKFieldIntegrator.hh
G4int G4RKFieldIntegrator::theA private
Definition at line 75 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RKFieldIntegrator.hh
Referenced by Init().
G4int G4RKFieldIntegrator::theZ private
Definition at line 76 of file G4RKFieldIntegrator.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RKFieldIntegrator.hh
Referenced by Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4RKFieldIntegrator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4RKFieldIntegrator.cc