ECCE @ EIC Software: G4PolarizedMollerBhabhaModel Class Reference
G4PolarizedMollerBhabhaModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedMollerBhabhaModel.hh>
Public Member Functions
G4PolarizedMollerBhabhaModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="PolarizedMollerBhabha")
virtual ~G4PolarizedMollerBhabhaModel ()
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kinEnergy, G4double cut, G4double emax) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
void SetTargetPolarization (const G4ThreeVector &pTarget)
void SetBeamPolarization (const G4ThreeVector &pBeam)
const G4StokesVector & GetTargetPolarization ()
const G4StokesVector & GetBeamPolarization ()
const G4StokesVector & GetFinalElectronPolarization ()
const G4StokesVector & GetFinalPositronPolarization ()
Public Member Functions inherited from G4MollerBhabhaModel
G4MollerBhabhaModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="MollerBhabha")
virtual ~G4MollerBhabhaModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
G4PolarizedMollerBhabhaModel (G4PolarizedMollerBhabhaModel &)=delete
G4PolarizedMollerBhabhaModel & operator= (const G4PolarizedMollerBhabhaModel &right)=delete
Private Attributes
G4StokesVector theBeamPolarization
G4StokesVector theTargetPolarization
G4VPolarizedCrossSection * crossSectionCalculator
G4StokesVector fPositronPolarization
G4StokesVector fElectronPolarization
Additional Inherited Members
Protected Member Functions inherited from G4MollerBhabhaModel
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) final
void SetParticle (const G4ParticleDefinition *p)
Protected Attributes inherited from G4MollerBhabhaModel
const G4ParticleDefinition * particle
G4ParticleDefinition * theElectron
G4ParticleChangeForLoss * fParticleChange
G4bool isElectron
G4double twoln10
G4double lowLimit
Detailed Description
Definition at line 58 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PolarizedMollerBhabhaModel.hh
Constructor & Destructor Documentation
G4PolarizedMollerBhabhaModel::G4PolarizedMollerBhabhaModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "PolarizedMollerBhabha") explicit
Definition at line 64 of file G4PolarizedMollerBhabhaModel.cc.
View newest version in sPHENIX GitHub at line 64 of file G4PolarizedMollerBhabhaModel.cc
References crossSectionCalculator, G4cout, G4endl, G4MollerBhabhaModel::isElectron, and G4MollerBhabhaModel::theElectron.
G4PolarizedMollerBhabhaModel::~G4PolarizedMollerBhabhaModel () virtual
Definition at line 86 of file G4PolarizedMollerBhabhaModel.cc.
View newest version in sPHENIX GitHub at line 86 of file G4PolarizedMollerBhabhaModel.cc
References crossSectionCalculator.
G4PolarizedMollerBhabhaModel::G4PolarizedMollerBhabhaModel (G4PolarizedMollerBhabhaModel &) private delete
Member Function Documentation
G4double G4PolarizedMollerBhabhaModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * pd, G4double kinEnergy, G4double cut, G4double emax) override virtual
Reimplemented from G4MollerBhabhaModel.
Definition at line 96 of file G4PolarizedMollerBhabhaModel.cc.
View newest version in sPHENIX GitHub at line 96 of file G4PolarizedMollerBhabhaModel.cc
References G4MollerBhabhaModel::ComputeCrossSectionPerElectron(), crossSectionCalculator, e, source.hepunit::electron_mass_c2, G4InuclParticleNames::gam, G4MollerBhabhaModel::MaxSecondaryEnergy(), min, theBeamPolarization, theTargetPolarization, xmax, xmin, and G4StokesVector::ZERO.
const G4StokesVector& G4PolarizedMollerBhabhaModel::GetBeamPolarization () inline
Definition at line 95 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PolarizedMollerBhabhaModel.hh
References theBeamPolarization.
const G4StokesVector& G4PolarizedMollerBhabhaModel::GetFinalElectronPolarization () inline
Definition at line 99 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4PolarizedMollerBhabhaModel.hh
References fElectronPolarization.
const G4StokesVector& G4PolarizedMollerBhabhaModel::GetFinalPositronPolarization () inline
Definition at line 103 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PolarizedMollerBhabhaModel.hh
References fPositronPolarization.
const G4StokesVector& G4PolarizedMollerBhabhaModel::GetTargetPolarization () inline
Definition at line 91 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PolarizedMollerBhabhaModel.hh
References theTargetPolarization.
G4PolarizedMollerBhabhaModel& G4PolarizedMollerBhabhaModel::operator= (const G4PolarizedMollerBhabhaModel & right) private delete
void G4PolarizedMollerBhabhaModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * , const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Reimplemented from G4MollerBhabhaModel.
Definition at line 139 of file G4PolarizedMollerBhabhaModel.cc.
View newest version in sPHENIX GitHub at line 139 of file G4PolarizedMollerBhabhaModel.cc
References source.hepunit::classic_electr_radius, crossSectionCalculator, DBL_MIN, Acts::Test::delta, dir, source.hepunit::electron_mass_c2, energy, fElectronPolarization, G4MollerBhabhaModel::fParticleChange, fPositronPolarization, G, G4cout, G4endl, G4UniformRand, G4InuclParticleNames::gam, G4ParticleChangeForLoss::GetCurrentTrack(), G4PolarizationHelper::GetFrame(), G4PolarizationManager::GetInstance(), G4DynamicParticle::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4DynamicParticle::GetMomentumDirection(), G4VPolarizedCrossSection::GetPol2(), G4VPolarizedCrossSection::GetPol3(), G4DynamicParticle::GetPolarization(), G4Track::GetVolume(), G4PolarizationManager::GetVolumePolarization(), H, G4VPolarizedCrossSection::Initialize(), G4StokesVector::InvRotateAz(), G4MollerBhabhaModel::isElectron, G4PolarizationManager::IsPolarized(), G4VEmModel::MaxSecondaryKinEnergy(), min, phi, G4ParticleChangeForLoss::ProposePolarization(), G4StokesVector::RotateAz(), CLHEP::Hep3Vector::rotateUz(), G4DynamicParticle::SetPolarization(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), sqr(), theBeamPolarization, G4MollerBhabhaModel::theElectron, theTargetPolarization, twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), x, xmax, xmin, G4VPolarizedCrossSection::XSection(), CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), z, and G4StokesVector::ZERO.
void G4PolarizedMollerBhabhaModel::SetBeamPolarization (const G4ThreeVector & pBeam) inline
Definition at line 87 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4PolarizedMollerBhabhaModel.hh
References theBeamPolarization.
Referenced by G4ePolarizedIonisation::ComputeAsymmetry().
void G4PolarizedMollerBhabhaModel::SetTargetPolarization (const G4ThreeVector & pTarget) inline
Definition at line 83 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PolarizedMollerBhabhaModel.hh
References theTargetPolarization.
Referenced by G4ePolarizedIonisation::ComputeAsymmetry().
Member Data Documentation
G4VPolarizedCrossSection* G4PolarizedMollerBhabhaModel::crossSectionCalculator private
Definition at line 117 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PolarizedMollerBhabhaModel.hh
Referenced by ComputeCrossSectionPerElectron(), G4PolarizedMollerBhabhaModel(), SampleSecondaries(), and ~G4PolarizedMollerBhabhaModel().
G4StokesVector G4PolarizedMollerBhabhaModel::fElectronPolarization private
Definition at line 120 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4PolarizedMollerBhabhaModel.hh
Referenced by GetFinalElectronPolarization(), and SampleSecondaries().
G4StokesVector G4PolarizedMollerBhabhaModel::fPositronPolarization private
Definition at line 119 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PolarizedMollerBhabhaModel.hh
Referenced by GetFinalPositronPolarization(), and SampleSecondaries().
G4StokesVector G4PolarizedMollerBhabhaModel::theBeamPolarization private
Definition at line 114 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PolarizedMollerBhabhaModel.hh
Referenced by ComputeCrossSectionPerElectron(), GetBeamPolarization(), SampleSecondaries(), and SetBeamPolarization().
G4StokesVector G4PolarizedMollerBhabhaModel::theTargetPolarization private
Definition at line 115 of file G4PolarizedMollerBhabhaModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PolarizedMollerBhabhaModel.hh
Referenced by ComputeCrossSectionPerElectron(), GetTargetPolarization(), SampleSecondaries(), and SetTargetPolarization().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedMollerBhabhaModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedMollerBhabhaModel.cc