ECCE @ EIC Software: XrayFluoRunAction Class Reference
XrayFluoRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoRunAction.hh>
Public Member Functions
XrayFluoRunAction ()
~XrayFluoRunAction ()
const XrayFluoDataSet * GetSet () const
const XrayFluoDataSet * GetGammaSet () const
const XrayFluoDataSet * GetAlphaSet () const
G4DataVector * GetEnergies () const
G4DataVector * GetData () const
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
G4double GetDataSum () const
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Member Functions
void Initialise ()
void ReadData (G4double, G4String)
Private Attributes
G4bool isInitialized
const XrayFluoDataSet * dataSet
const XrayFluoDataSet * dataGammaSet
const XrayFluoDataSet * dataAlphaSet
G4DataVector * energies
G4DataVector * data
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 50 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 50 of file XrayFluoRunAction.hh
Constructor & Destructor Documentation
XrayFluoRunAction::XrayFluoRunAction ()
Definition at line 52 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 52 of file XrayFluoRunAction.cc
XrayFluoRunAction::~XrayFluoRunAction ()
Definition at line 59 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 59 of file XrayFluoRunAction.cc
Member Function Documentation
void XrayFluoRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 93 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 93 of file XrayFluoRunAction.cc
References static_analysis_results::analysis(), G4UImanager::ApplyCommand(), XrayFluoAnalysisManager::book(), G4cout, G4endl, G4VVisManager::GetConcreteInstance(), XrayFluoAnalysisManager::getInstance(), G4Run::GetRunID(), G4UImanager::GetUIpointer(), Initialise(), isInitialized, and G4UserRunAction::IsMaster().
void XrayFluoRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 119 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 119 of file XrayFluoRunAction.cc
References static_analysis_results::analysis(), G4UImanager::ApplyCommand(), XrayFluoAnalysisManager::finish(), G4VVisManager::GetConcreteInstance(), XrayFluoAnalysisManager::getInstance(), and G4UImanager::GetUIpointer().
const XrayFluoDataSet * XrayFluoRunAction::GetAlphaSet () const
Definition at line 146 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 146 of file XrayFluoRunAction.cc
References dataAlphaSet.
G4DataVector * XrayFluoRunAction::GetData () const
Definition at line 160 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 160 of file XrayFluoRunAction.cc
References data.
Referenced by XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction::GeneratePrimaries().
G4double XrayFluoRunAction::GetDataSum () const
Definition at line 167 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 167 of file XrayFluoRunAction.cc
References sum.
Referenced by XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction::GeneratePrimaries().
G4DataVector * XrayFluoRunAction::GetEnergies () const
Definition at line 153 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 153 of file XrayFluoRunAction.cc
References energies.
Referenced by XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction::GeneratePrimaries().
const XrayFluoDataSet * XrayFluoRunAction::GetGammaSet () const
Definition at line 139 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 139 of file XrayFluoRunAction.cc
References dataGammaSet.
Referenced by XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction::GeneratePrimaries().
const XrayFluoDataSet * XrayFluoRunAction::GetSet () const
Definition at line 132 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 132 of file XrayFluoRunAction.cc
References dataSet.
void XrayFluoRunAction::Initialise () private
Definition at line 64 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 64 of file XrayFluoRunAction.cc
References dataGammaSet, energies, G4cout, G4endl, isInitialized, G4UserRunAction::IsMaster(), keV, XrayFluoNormalization::Normalize(), and ReadData().
Referenced by BeginOfRunAction().
void XrayFluoRunAction::ReadData (G4double unitE, G4String fileName) private
Definition at line 180 of file XrayFluoRunAction.cc.
View newest version in sPHENIX GitHub at line 180 of file XrayFluoRunAction.cc
References a, e, energies, FatalException, file, G4cout, G4endl, G4Exception(), and k.
Referenced by Initialise().
Member Data Documentation
G4DataVector* XrayFluoRunAction::data private
Definition at line 102 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 102 of file XrayFluoRunAction.hh
Referenced by GetData().
const XrayFluoDataSet* XrayFluoRunAction::dataAlphaSet private
Definition at line 96 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 96 of file XrayFluoRunAction.hh
Referenced by GetAlphaSet().
const XrayFluoDataSet* XrayFluoRunAction::dataGammaSet private
Definition at line 93 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 93 of file XrayFluoRunAction.hh
Referenced by GetGammaSet(), and Initialise().
const XrayFluoDataSet* XrayFluoRunAction::dataSet private
Definition at line 90 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file XrayFluoRunAction.hh
Referenced by GetSet().
G4DataVector* XrayFluoRunAction::energies private
Definition at line 99 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 99 of file XrayFluoRunAction.hh
Referenced by GetEnergies(), Initialise(), and ReadData().
G4bool XrayFluoRunAction::isInitialized private
Definition at line 88 of file XrayFluoRunAction.hh.
View newest version in sPHENIX GitHub at line 88 of file XrayFluoRunAction.hh
Referenced by BeginOfRunAction(), and Initialise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoRunAction.cc