ECCE @ EIC Software: DicomFilePlan Class Reference
DicomFilePlan Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomFilePlan.hh>
Public Member Functions
DicomFilePlan (DcmDataset *dset)
~DicomFilePlan ()
virtual void ReadData ()
void CheckData0 (OFString title, Sint32 val)
void DumpToFile ()
void SetControlPointMetersets ()
Public Member Functions inherited from DicomVFile
DicomVFile ()
DicomVFile (DcmDataset *dset)
~DicomVFile ()
void SetFileName (G4String fName)
Private Attributes
std::vector< DicomBeam * > theBeams
Sint32 theNumberOfBeams
Additional Inherited Members
Protected Member Functions inherited from DicomVFile
virtual std::vector< G4double > Read1Data (DcmDataset *dset, DcmTagKey tagKey, G4int nData)
virtual OFString Read1DataStr (DcmDataset *dset, DcmTagKey tagKey)
Protected Attributes inherited from DicomVFile
DcmDataset * theDataset
G4String fFileName
Detailed Description
Definition at line 36 of file DicomFilePlan.hh.
View newest version in sPHENIX GitHub at line 36 of file DicomFilePlan.hh
Constructor & Destructor Documentation
DicomFilePlan::DicomFilePlan (DcmDataset * dset)
Definition at line 51 of file DicomFilePlan.cc.
View newest version in sPHENIX GitHub at line 51 of file DicomFilePlan.cc
DicomFilePlan::~DicomFilePlan () inline
Definition at line 40 of file DicomFilePlan.hh.
View newest version in sPHENIX GitHub at line 40 of file DicomFilePlan.hh
Member Function Documentation
void DicomFilePlan::CheckData0 (OFString title, Sint32 val)
Definition at line 268 of file DicomFilePlan.cc.
View newest version in sPHENIX GitHub at line 268 of file DicomFilePlan.cc
References FatalException, and G4Exception().
Referenced by ReadData().
void DicomFilePlan::DumpToFile ()
Definition at line 287 of file DicomFilePlan.cc.
View newest version in sPHENIX GitHub at line 287 of file DicomFilePlan.cc
References theBeams.
void DicomFilePlan::ReadData () virtual
Implements DicomVFile.
Definition at line 56 of file DicomFilePlan.cc.
View newest version in sPHENIX GitHub at line 56 of file DicomFilePlan.cc
References DicomBeam::AddBlock(), DicomBeam::AddCompensator(), DicomBeam::AddControlPoint(), DicomBeam::AddDevice(), DicomBeam::AddWedge(), CheckData0(), Acts::Test::db, FatalException, G4cout, G4endl, G4Exception(), DicomBeam::GetControlPoint(), DicomBeam::GetNControlPoints(), JustWarning, DicomBeam::SetDoseSpecificationPoint(), DicomBeam::SetMeterset(), DicomBeam::SetNumber(), DicomBeam::SetRadiationType(), DicomBeam::SetSourceAxisDistance(), theBeams, DicomVFile::theDataset, and theNumberOfBeams.
Referenced by DicomFileMgr::AddFile().
void DicomFilePlan::SetControlPointMetersets ()
Definition at line 279 of file DicomFilePlan.cc.
View newest version in sPHENIX GitHub at line 279 of file DicomFilePlan.cc
References theBeams.
Member Data Documentation
std::vector<DicomBeam*> DicomFilePlan::theBeams private
Definition at line 51 of file DicomFilePlan.hh.
View newest version in sPHENIX GitHub at line 51 of file DicomFilePlan.hh
Referenced by DumpToFile(), ReadData(), and SetControlPointMetersets().
Sint32 DicomFilePlan::theNumberOfBeams private
Definition at line 52 of file DicomFilePlan.hh.
View newest version in sPHENIX GitHub at line 52 of file DicomFilePlan.hh
Referenced by ReadData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomFilePlan.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomFilePlan.cc