ECCE @ EIC Software: eRositaPrimaryGeneratorAction Class Reference
eRositaPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/eRositaPrimaryGeneratorAction.hh>
Public Member Functions
eRositaPrimaryGeneratorAction ()
~eRositaPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * particleGun
G4double xposition
G4double yposition
G4double zposition
G4double xdirection
G4double ydirection
G4double zdirection
Detailed Description
Definition at line 42 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 42 of file eRositaPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction ()
Definition at line 43 of file eRositaPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 43 of file eRositaPrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), MeV, particle, particleGun, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), xdirection, ydirection, and zdirection.
eRositaPrimaryGeneratorAction::~eRositaPrimaryGeneratorAction ()
Definition at line 66 of file eRositaPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 66 of file eRositaPrimaryGeneratorAction.cc
References particleGun.
Member Function Documentation
void eRositaPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 73 of file eRositaPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 73 of file eRositaPrimaryGeneratorAction.cc
References cm, G4ParticleGun::GeneratePrimaryVertex(), particleGun, G4VPrimaryGenerator::SetParticlePosition(), xposition, yposition, and zposition.
Member Data Documentation
G4ParticleGun* eRositaPrimaryGeneratorAction::particleGun private
Definition at line 52 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file eRositaPrimaryGeneratorAction.hh
Referenced by eRositaPrimaryGeneratorAction(), GeneratePrimaries(), and ~eRositaPrimaryGeneratorAction().
G4double eRositaPrimaryGeneratorAction::xdirection private
Definition at line 58 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file eRositaPrimaryGeneratorAction.hh
Referenced by eRositaPrimaryGeneratorAction().
G4double eRositaPrimaryGeneratorAction::xposition private
Definition at line 54 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file eRositaPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4double eRositaPrimaryGeneratorAction::ydirection private
Definition at line 59 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file eRositaPrimaryGeneratorAction.hh
Referenced by eRositaPrimaryGeneratorAction().
G4double eRositaPrimaryGeneratorAction::yposition private
Definition at line 55 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file eRositaPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4double eRositaPrimaryGeneratorAction::zdirection private
Definition at line 60 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file eRositaPrimaryGeneratorAction.hh
Referenced by eRositaPrimaryGeneratorAction().
G4double eRositaPrimaryGeneratorAction::zposition private
Definition at line 56 of file eRositaPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file eRositaPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/eRositaPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/src/eRositaPrimaryGeneratorAction.cc