ECCE @ EIC Software: G4PreCompoundFragment Class Reference
G4PreCompoundFragment Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundFragment.hh>
Public Member Functions
G4PreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4PreCompoundFragment ()
G4double CalcEmissionProbability (const G4Fragment &aFragment)
G4double SampleKineticEnergy (const G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundFragment
G4VPreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4VPreCompoundFragment ()
void Initialize (const G4Fragment &aFragment)
G4bool IsItPossible (const G4Fragment &aFragment) const
G4ReactionProduct * GetReactionProduct () const
G4int GetA () const
G4int GetZ () const
G4int GetRestA () const
G4int GetRestZ () const
G4double GetBindingEnergy () const
G4double GetEnergyThreshold () const
G4double GetEmissionProbability () const
G4double GetNuclearMass () const
G4double GetRestNuclearMass () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Protected Member Functions
virtual G4double GetAlpha () const =0
virtual G4double GetBeta () const =0
G4double CrossSection (G4double ekin) const
virtual G4double ProbabilityDistributionFunction (G4double K, const G4Fragment &aFragment)=0
Private Member Functions
G4double IntegrateEmissionProbability (G4double Low, G4double Up, const G4Fragment &aFragment)
G4double GetOpt0 (G4double ekin) const
G4PreCompoundFragment (const G4PreCompoundFragment &right)=delete
const G4PreCompoundFragment & operator= (const G4PreCompoundFragment &right)=delete
G4bool operator== (const G4PreCompoundFragment &right) const =delete
G4bool operator!= (const G4PreCompoundFragment &right) const =delete
Private Attributes
G4int index
G4double muu
G4double probmax
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundFragment
G4NuclearLevelData * fNucData
G4DeexPrecoParameters * theParameters
G4Pow * g4calc
G4int theA
G4int theZ
G4int theResA
G4int theResZ
G4int theFragA
G4int theFragZ
G4double theResA13
G4double theBindingEnergy
G4double theMinKinEnergy
G4double theMaxKinEnergy
G4double theResMass
G4double theReducedMass
G4double theMass
G4double theEmissionProbability
G4double theCoulombBarrier
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 43 of file G4PreCompoundFragment.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PreCompoundFragment.hh
Constructor & Destructor Documentation
G4PreCompoundFragment::G4PreCompoundFragment (const G4ParticleDefinition * p, G4VCoulombBarrier * aCoulombBarrier)
Definition at line 42 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 42 of file G4PreCompoundFragment.cc
References index, muu, probmax, G4VPreCompoundFragment::theA, and G4VPreCompoundFragment::theZ.
G4PreCompoundFragment::~G4PreCompoundFragment () virtual
Definition at line 52 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PreCompoundFragment.cc
G4PreCompoundFragment::G4PreCompoundFragment (const G4PreCompoundFragment & right) private delete
Member Function Documentation
G4double G4PreCompoundFragment::CalcEmissionProbability (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundFragment.
Definition at line 56 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PreCompoundFragment.cc
References G4KalbachCrossSection::ComputePowerParameter(), index, IntegrateEmissionProbability(), muu, G4VPreCompoundFragment::theEmissionProbability, G4VPreCompoundFragment::theMaxKinEnergy, G4VPreCompoundFragment::theMinKinEnergy, and G4VPreCompoundFragment::theResA.
G4double G4PreCompoundFragment::CrossSection (G4double ekin) const protected
Definition at line 112 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 112 of file G4PreCompoundFragment.cc
References G4ChatterjeeCrossSection::ComputeCrossSection(), G4KalbachCrossSection::ComputeCrossSection(), GetOpt0(), index, muu, G4VPreCompoundFragment::OPTxs, G4VPreCompoundFragment::theA, G4VPreCompoundFragment::theCoulombBarrier, G4VPreCompoundFragment::theMaxKinEnergy, G4VPreCompoundFragment::theResA, G4VPreCompoundFragment::theResA13, and G4VPreCompoundFragment::theZ.
Referenced by G4PreCompoundNucleon::ProbabilityDistributionFunction(), and G4PreCompoundIon::ProbabilityDistributionFunction().
virtual G4double G4PreCompoundFragment::GetAlpha () const protected pure virtual
Implements G4VPreCompoundFragment.
Implemented in G4PreCompoundAlpha, G4PreCompoundDeuteron, G4PreCompoundHe3, G4PreCompoundTriton, G4PreCompoundNeutron, and G4PreCompoundProton.
Referenced by GetOpt0().
virtual G4double G4PreCompoundFragment::GetBeta () const protected pure virtual
Implements G4VPreCompoundFragment.
Implemented in G4PreCompoundIon, G4PreCompoundNeutron, and G4PreCompoundProton.
Referenced by GetOpt0().
G4double G4PreCompoundFragment::GetOpt0 (G4double ekin) const private
Definition at line 132 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 132 of file G4PreCompoundFragment.cc
References GetAlpha(), GetBeta(), G4DeexPrecoParameters::GetR0(), CLHEP::pi, G4VPreCompoundFragment::theParameters, and G4VPreCompoundFragment::theResA13.
Referenced by CrossSection().
G4double G4PreCompoundFragment::IntegrateEmissionProbability (G4double Low, G4double Up, const G4Fragment & aFragment) private
Definition at line 86 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 86 of file G4PreCompoundFragment.cc
References den, e, max, CLHEP::MeV, ProbabilityDistributionFunction(), probmax, sum, and y.
Referenced by CalcEmissionProbability().
G4bool G4PreCompoundFragment::operator!= (const G4PreCompoundFragment & right) const private delete
const G4PreCompoundFragment& G4PreCompoundFragment::operator= (const G4PreCompoundFragment & right) private delete
G4bool G4PreCompoundFragment::operator== (const G4PreCompoundFragment & right) const private delete
virtual G4double G4PreCompoundFragment::ProbabilityDistributionFunction (G4double K, const G4Fragment & aFragment) protected pure virtual
Implemented in G4PreCompoundIon, and G4PreCompoundNucleon.
Referenced by IntegrateEmissionProbability(), and SampleKineticEnergy().
G4double G4PreCompoundFragment::SampleKineticEnergy (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundFragment.
Definition at line 140 of file G4PreCompoundFragment.cc.
View newest version in sPHENIX GitHub at line 140 of file G4PreCompoundFragment.cc
References Acts::Test::delta, CLHEP::HepRandomEngine::flat(), ProbabilityDistributionFunction(), probmax, T, G4VPreCompoundFragment::theMaxKinEnergy, and G4VPreCompoundFragment::theMinKinEnergy.
Member Data Documentation
G4int G4PreCompoundFragment::index private
Definition at line 89 of file G4PreCompoundFragment.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PreCompoundFragment.hh
Referenced by CalcEmissionProbability(), CrossSection(), and G4PreCompoundFragment().
G4double G4PreCompoundFragment::muu private
Definition at line 91 of file G4PreCompoundFragment.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PreCompoundFragment.hh
Referenced by CalcEmissionProbability(), CrossSection(), and G4PreCompoundFragment().
G4double G4PreCompoundFragment::probmax private
Definition at line 92 of file G4PreCompoundFragment.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PreCompoundFragment.hh
Referenced by G4PreCompoundFragment(), IntegrateEmissionProbability(), and SampleKineticEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundFragment.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4PreCompoundFragment.cc