ECCE @ EIC Software: G4MatScanMessenger Class Reference
G4MatScanMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4MatScanMessenger.hh>
Public Member Functions
G4MatScanMessenger (G4MaterialScanner *p1)
virtual ~G4MatScanMessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4MaterialScanner * theScanner
G4UIdirectory * msDirectory
G4UIcmdWithoutParameter * scanCmd
G4UIcommand * thetaCmd
G4UIcommand * phiCmd
G4UIcommand * singleCmd
G4UIcmdWith3Vector * single2Cmd
G4UIcmdWithABool * regSenseCmd
G4UIcmdWithAString * regionCmd
G4UIcmdWith3VectorAndUnit * eyePosCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 47 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 47 of file G4MatScanMessenger.hh
Constructor & Destructor Documentation
G4MatScanMessenger::G4MatScanMessenger (G4MaterialScanner * p1)
Definition at line 46 of file G4MatScanMessenger.cc.
View newest version in sPHENIX GitHub at line 46 of file G4MatScanMessenger.cc
References G4UIcommand::AvailableForStates(), G4UIcommand::CategoryOf(), eyePosCmd, G4State_Idle, msDirectory, phiCmd, regionCmd, regSenseCmd, scanCmd, G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4UIparameter::SetParameterRange(), single2Cmd, singleCmd, theScanner, thetaCmd, and G4UIcommand::UnitsList().
G4MatScanMessenger::~G4MatScanMessenger () virtual
Definition at line 137 of file G4MatScanMessenger.cc.
View newest version in sPHENIX GitHub at line 137 of file G4MatScanMessenger.cc
References eyePosCmd, msDirectory, phiCmd, regionCmd, regSenseCmd, scanCmd, single2Cmd, singleCmd, and thetaCmd.
Member Function Documentation
G4String G4MatScanMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 150 of file G4MatScanMessenger.cc.
View newest version in sPHENIX GitHub at line 150 of file G4MatScanMessenger.cc
References G4UIcommand::ConvertToString(), deg, eyePosCmd, G4MaterialScanner::GetEyePosition(), G4MaterialScanner::GetNPhi(), G4MaterialScanner::GetNTheta(), G4MaterialScanner::GetPhiMin(), G4MaterialScanner::GetPhiSpan(), G4MaterialScanner::GetRegionName(), G4MaterialScanner::GetRegionSensitive(), G4MaterialScanner::GetThetaMin(), G4MaterialScanner::GetThetaSpan(), phiCmd, regionCmd, regSenseCmd, theScanner, and thetaCmd.
void G4MatScanMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 178 of file G4MatScanMessenger.cc.
View newest version in sPHENIX GitHub at line 178 of file G4MatScanMessenger.cc
References deg, eyePosCmd, G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4MaterialScanner::GetNPhi(), G4MaterialScanner::GetNTheta(), G4MaterialScanner::GetPhiMin(), G4MaterialScanner::GetPhiSpan(), G4MaterialScanner::GetThetaMin(), G4MaterialScanner::GetThetaSpan(), CLHEP::Hep3Vector::phi(), phi, phiCmd, Acts::Test::phiMin, regionCmd, regSenseCmd, G4MaterialScanner::Scan(), scanCmd, G4MaterialScanner::SetEyePosition(), G4MaterialScanner::SetNPhi(), G4MaterialScanner::SetNTheta(), G4MaterialScanner::SetPhiMin(), G4MaterialScanner::SetPhiSpan(), G4MaterialScanner::SetRegionName(), G4MaterialScanner::SetRegionSensitive(), G4MaterialScanner::SetThetaMin(), G4MaterialScanner::SetThetaSpan(), single2Cmd, singleCmd, G4UImessenger::StoD(), G4UImessenger::StoI(), theScanner, CLHEP::Hep3Vector::theta(), theta(), thetaCmd, v, and G4UIcommand::ValueOf().
Member Data Documentation
G4UIcmdWith3VectorAndUnit* G4MatScanMessenger::eyePosCmd private
Definition at line 67 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), GetCurrentValue(), SetNewValue(), and ~G4MatScanMessenger().
G4UIdirectory* G4MatScanMessenger::msDirectory private
Definition at line 59 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), and ~G4MatScanMessenger().
G4UIcommand* G4MatScanMessenger::phiCmd private
Definition at line 62 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), GetCurrentValue(), SetNewValue(), and ~G4MatScanMessenger().
G4UIcmdWithAString* G4MatScanMessenger::regionCmd private
Definition at line 66 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), GetCurrentValue(), SetNewValue(), and ~G4MatScanMessenger().
G4UIcmdWithABool* G4MatScanMessenger::regSenseCmd private
Definition at line 65 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), GetCurrentValue(), SetNewValue(), and ~G4MatScanMessenger().
G4UIcmdWithoutParameter* G4MatScanMessenger::scanCmd private
Definition at line 60 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), SetNewValue(), and ~G4MatScanMessenger().
G4UIcmdWith3Vector* G4MatScanMessenger::single2Cmd private
Definition at line 64 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), SetNewValue(), and ~G4MatScanMessenger().
G4UIcommand* G4MatScanMessenger::singleCmd private
Definition at line 63 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), SetNewValue(), and ~G4MatScanMessenger().
G4MaterialScanner* G4MatScanMessenger::theScanner private
Definition at line 57 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), GetCurrentValue(), and SetNewValue().
G4UIcommand* G4MatScanMessenger::thetaCmd private
Definition at line 61 of file G4MatScanMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file G4MatScanMessenger.hh
Referenced by G4MatScanMessenger(), GetCurrentValue(), SetNewValue(), and ~G4MatScanMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4MatScanMessenger.hh
geant4/tree/geant4-10.6-release/source/run/src/G4MatScanMessenger.cc