ECCE @ EIC Software: HadrontherapyDetectorConstruction Class Reference
HadrontherapyDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyDetectorConstruction.hh>
Public Member Functions
HadrontherapyDetectorConstruction (G4VPhysicalVolume *)
~HadrontherapyDetectorConstruction ()
void InitializeDetectorROGeometry (HadrontherapyDetectorROGeometry *, G4ThreeVector detectorToWorldPosition)
void VirtualLayer (G4bool Varbool)
void SetVirtualLayerPosition (G4ThreeVector)
G4ThreeVector GetDetectorToWorldPosition ()
G4ThreeVector GetDetectorToPhantomPosition ()
void SetDetectorPosition ()
bool IsInside (G4double detectorX, G4double detectorY, G4double detectorZ, G4double phantomX, G4double phantomY, G4double phantomZ, G4ThreeVector pos)
G4bool SetPhantomMaterial (G4String material)
void SetVoxelSize (G4double sizeX, G4double sizeY, G4double sizeZ)
void SetDetectorSize (G4double sizeX, G4double sizeY, G4double sizeZ)
void SetPhantomSize (G4double sizeX, G4double sizeY, G4double sizeZ)
void SetPhantomPosition (G4ThreeVector)
void SetDetectorToPhantomPosition (G4ThreeVector DetectorToPhantomPosition)
void UpdateGeometry ()
void PrintParameters ()
G4LogicalVolume * GetDetectorLogicalVolume ()
Static Public Member Functions
static
HadrontherapyDetectorConstruction * GetInstance ()
Public Attributes
G4VPhysicalVolume * motherPhys
HadrontherapyDetectorSD * detectorSD
G4bool NewSource
G4ThreeVector VirtualLayerPosition
Private Member Functions
void ConstructPhantom ()
void ConstructDetector ()
void ParametersCheck ()
void CheckOverlaps ()
Private Attributes
HadrontherapyDetectorMessenger * detectorMessenger
G4VisAttributes * skyBlue
G4VisAttributes * red
HadrontherapyDetectorROGeometry * detectorROGeometry
HadrontherapyMatrix * matrix
HadrontherapyLet * let
G4Box * phantom
G4Box * detector
G4LogicalVolume * phantomLogicalVolume
G4LogicalVolume * detectorLogicalVolume
G4VPhysicalVolume * phantomPhysicalVolume
G4VPhysicalVolume * detectorPhysicalVolume
G4Box * solidVirtualLayer
G4LogicalVolume * logicVirtualLayer
G4VPhysicalVolume * physVirtualLayer
G4double phantomSizeX
G4double phantomSizeY
G4double phantomSizeZ
G4double detectorSizeX
G4double detectorSizeY
G4double detectorSizeZ
G4ThreeVector phantomPosition
G4ThreeVector detectorPosition
G4ThreeVector detectorToPhantomPosition
G4double sizeOfVoxelAlongX
G4double sizeOfVoxelAlongY
G4double sizeOfVoxelAlongZ
G4int numberOfVoxelsAlongX
G4int numberOfVoxelsAlongY
G4int numberOfVoxelsAlongZ
G4double volumeOfVoxel
G4double massOfVoxel
G4Material * phantomMaterial
G4Material * detectorMaterial
G4Region * aRegion
Static Private Attributes
static
HadrontherapyDetectorConstruction * instance = 0
Detailed Description
Definition at line 48 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 48 of file HadrontherapyDetectorConstruction.hh
Constructor & Destructor Documentation
HadrontherapyDetectorConstruction::HadrontherapyDetectorConstruction (G4VPhysicalVolume * physicalTreatmentRoom)
Definition at line 67 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 67 of file HadrontherapyDetectorConstruction.cc
References cm, detectorMessenger, SetDetectorPosition(), SetDetectorSize(), SetDetectorToPhantomPosition(), SetPhantomMaterial(), SetPhantomPosition(), SetPhantomSize(), sizeOfVoxelAlongX, sizeOfVoxelAlongY, sizeOfVoxelAlongZ, um, and UpdateGeometry().
HadrontherapyDetectorConstruction::~HadrontherapyDetectorConstruction ()
Definition at line 112 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 112 of file HadrontherapyDetectorConstruction.cc
References detectorMessenger, detectorROGeometry, and matrix.
Member Function Documentation
void HadrontherapyDetectorConstruction::CheckOverlaps () private
Definition at line 486 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 486 of file HadrontherapyDetectorConstruction.cc
References G4cout, G4endl, and G4PhysicalVolumeStore::GetInstance().
void HadrontherapyDetectorConstruction::ConstructDetector () private
Definition at line 180 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 180 of file HadrontherapyDetectorConstruction.cc
References G4Region::AddRootLogicalVolume(), aRegion, detector, detectorLogicalVolume, detectorMaterial, detectorPhysicalVolume, detectorPosition, phantomPhysicalVolume, phantomSizeX, phantomSizeY, phantomSizeZ, and skyBlue.
Referenced by UpdateGeometry().
void HadrontherapyDetectorConstruction::ConstructPhantom () private
Definition at line 129 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 129 of file HadrontherapyDetectorConstruction.cc
References motherPhys, phantom, phantomLogicalVolume, phantomMaterial, phantomPhysicalVolume, phantomPosition, phantomSizeX, phantomSizeY, phantomSizeZ, and red.
Referenced by UpdateGeometry().
G4LogicalVolume* HadrontherapyDetectorConstruction::GetDetectorLogicalVolume () inline
Definition at line 167 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 167 of file HadrontherapyDetectorConstruction.hh
References detectorLogicalVolume.
G4ThreeVector HadrontherapyDetectorConstruction::GetDetectorToPhantomPosition () inline
Definition at line 85 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file HadrontherapyDetectorConstruction.hh
References detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), phantomSizeX, phantomSizeY, and phantomSizeZ.
G4ThreeVector HadrontherapyDetectorConstruction::GetDetectorToWorldPosition () inline
Definition at line 79 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 79 of file HadrontherapyDetectorConstruction.hh
References detectorPosition, and phantomPosition.
Referenced by PassiveCarbonBeamLine::Construct(), PassiveProtonBeamLine::Construct(), LaserDrivenBeamLine::Construct(), and UpdateGeometry().
HadrontherapyDetectorConstruction * HadrontherapyDetectorConstruction::GetInstance () static
Definition at line 120 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 120 of file HadrontherapyDetectorConstruction.cc
References instance.
void HadrontherapyDetectorConstruction::InitializeDetectorROGeometry (HadrontherapyDetectorROGeometry * RO, G4ThreeVector detectorToWorldPosition)
Definition at line 228 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 228 of file HadrontherapyDetectorConstruction.cc
References detectorSizeX, detectorSizeY, detectorSizeZ, HadrontherapyDetectorROGeometry::Initialize(), numberOfVoxelsAlongX, numberOfVoxelsAlongY, and numberOfVoxelsAlongZ.
Referenced by PassiveCarbonBeamLine::Construct(), PassiveProtonBeamLine::Construct(), and LaserDrivenBeamLine::Construct().
bool HadrontherapyDetectorConstruction::IsInside (G4double detectorX, G4double detectorY, G4double detectorZ, G4double phantomX, G4double phantomY, G4double phantomZ, G4ThreeVector pos) inline
Definition at line 106 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file HadrontherapyDetectorConstruction.hh
References G4cout, G4endl, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), and CLHEP::Hep3Vector::getZ().
Referenced by ParametersCheck().
void HadrontherapyDetectorConstruction::ParametersCheck () private
Definition at line 279 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 279 of file HadrontherapyDetectorConstruction.cc
References detectorSizeX, detectorSizeY, detectorSizeZ, detectorToPhantomPosition, FatalException, G4Exception(), IsInside(), phantomSizeX, phantomSizeY, phantomSizeZ, sizeOfVoxelAlongX, sizeOfVoxelAlongY, and sizeOfVoxelAlongZ.
Referenced by UpdateGeometry().
void HadrontherapyDetectorConstruction::PrintParameters ()
Definition at line 502 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 502 of file HadrontherapyDetectorConstruction.cc
References detector, G4BestUnit, G4cout, G4endl, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), numberOfVoxelsAlongX, numberOfVoxelsAlongY, numberOfVoxelsAlongZ, phantom, phantomPosition, sizeOfVoxelAlongX, sizeOfVoxelAlongY, and sizeOfVoxelAlongZ.
Referenced by UpdateGeometry().
void HadrontherapyDetectorConstruction::SetDetectorPosition () inline
Definition at line 95 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file HadrontherapyDetectorConstruction.hh
References detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, detectorToPhantomPosition, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), phantomSizeX, phantomSizeY, phantomSizeZ, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by HadrontherapyDetectorConstruction(), and UpdateGeometry().
void HadrontherapyDetectorConstruction::SetDetectorSize (G4double sizeX, G4double sizeY, G4double sizeZ)
Definition at line 342 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 342 of file HadrontherapyDetectorConstruction.cc
References detectorSizeX, detectorSizeY, detectorSizeZ, SetVoxelSize(), sizeOfVoxelAlongX, sizeOfVoxelAlongY, and sizeOfVoxelAlongZ.
Referenced by HadrontherapyDetectorConstruction().
void HadrontherapyDetectorConstruction::SetDetectorToPhantomPosition (G4ThreeVector DetectorToPhantomPosition)
Definition at line 365 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 365 of file HadrontherapyDetectorConstruction.cc
References detectorToPhantomPosition.
Referenced by HadrontherapyDetectorConstruction().
G4bool HadrontherapyDetectorConstruction::SetPhantomMaterial (G4String material)
Definition at line 306 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 306 of file HadrontherapyDetectorConstruction.cc
References detectorLogicalVolume, detectorMaterial, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), G4NistManager::Instance(), phantomLogicalVolume, phantomMaterial, and EmPlot::SetMaterial().
Referenced by HadrontherapyDetectorConstruction().
void HadrontherapyDetectorConstruction::SetPhantomPosition (G4ThreeVector pos)
Definition at line 359 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 359 of file HadrontherapyDetectorConstruction.cc
References phantomPosition, and pos().
Referenced by HadrontherapyDetectorConstruction().
void HadrontherapyDetectorConstruction::SetPhantomSize (G4double sizeX, G4double sizeY, G4double sizeZ)
Definition at line 334 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 334 of file HadrontherapyDetectorConstruction.cc
References phantomSizeX, phantomSizeY, and phantomSizeZ.
Referenced by HadrontherapyDetectorConstruction().
void HadrontherapyDetectorConstruction::SetVirtualLayerPosition (G4ThreeVector position)
Definition at line 370 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 370 of file HadrontherapyDetectorConstruction.cc
References physVirtualLayer, position, G4VPhysicalVolume::SetTranslation(), and VirtualLayerPosition.
void HadrontherapyDetectorConstruction::SetVoxelSize (G4double sizeX, G4double sizeY, G4double sizeZ)
Definition at line 351 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 351 of file HadrontherapyDetectorConstruction.cc
References sizeOfVoxelAlongX, sizeOfVoxelAlongY, and sizeOfVoxelAlongZ.
Referenced by SetDetectorSize().
void HadrontherapyDetectorConstruction::UpdateGeometry ()
Definition at line 378 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 378 of file HadrontherapyDetectorConstruction.cc
References ConstructDetector(), ConstructPhantom(), HadrontherapyRBE::CreateInstance(), detector, detectorMaterial, detectorPhysicalVolume, detectorPosition, detectorSizeX, detectorSizeY, detectorSizeZ, G4lrint(), pyG4RunManager::GeometryHasBeenModified, GetDetectorToWorldPosition(), HadrontherapyLet::GetInstance(), G4GeometryManager::GetInstance(), HadrontherapyMatrix::GetInstance(), G4VUserDetectorConstruction::GetParallelWorld(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), HadrontherapyDetectorROGeometry::Initialize(), Initialize(), let, massOfVoxel, matrix, numberOfVoxelsAlongX, numberOfVoxelsAlongY, numberOfVoxelsAlongZ, ParametersCheck(), phantom, phantomPhysicalVolume, phantomPosition, phantomSizeX, phantomSizeY, phantomSizeZ, PrintParameters(), SetDetectorPosition(), sizeOfVoxelAlongX, sizeOfVoxelAlongY, sizeOfVoxelAlongZ, HadrontherapyDetectorROGeometry::UpdateROGeometry(), and volumeOfVoxel.
Referenced by HadrontherapyDetectorConstruction().
void HadrontherapyDetectorConstruction::VirtualLayer (G4bool Varbool)
Definition at line 241 of file HadrontherapyDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 241 of file HadrontherapyDetectorConstruction.cc
References cm, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), logicVirtualLayer, motherPhys, NewSource, physVirtualLayer, skyBlue, solidVirtualLayer, um, and VirtualLayerPosition.
Referenced by HadrontherapyDetectorMessenger::SetNewValue().
Member Data Documentation
G4Region* HadrontherapyDetectorConstruction::aRegion private
Definition at line 209 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 209 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector().
G4Box * HadrontherapyDetectorConstruction::detector private
Definition at line 180 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 180 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), PrintParameters(), and UpdateGeometry().
G4LogicalVolume * HadrontherapyDetectorConstruction::detectorLogicalVolume private
Definition at line 181 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 181 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorLogicalVolume(), and SetPhantomMaterial().
G4Material * HadrontherapyDetectorConstruction::detectorMaterial private
Definition at line 208 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 208 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), SetPhantomMaterial(), and UpdateGeometry().
HadrontherapyDetectorMessenger* HadrontherapyDetectorConstruction::detectorMessenger private
Definition at line 171 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 171 of file HadrontherapyDetectorConstruction.hh
Referenced by HadrontherapyDetectorConstruction(), and ~HadrontherapyDetectorConstruction().
G4VPhysicalVolume * HadrontherapyDetectorConstruction::detectorPhysicalVolume private
Definition at line 182 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 182 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), and UpdateGeometry().
G4ThreeVector HadrontherapyDetectorConstruction::detectorPosition private
Definition at line 196 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 196 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), GetDetectorToPhantomPosition(), GetDetectorToWorldPosition(), SetDetectorPosition(), and UpdateGeometry().
HadrontherapyDetectorROGeometry* HadrontherapyDetectorConstruction::detectorROGeometry private
Definition at line 176 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 176 of file HadrontherapyDetectorConstruction.hh
Referenced by ~HadrontherapyDetectorConstruction().
HadrontherapyDetectorSD* HadrontherapyDetectorConstruction::detectorSD
Definition at line 61 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 61 of file HadrontherapyDetectorConstruction.hh
G4double HadrontherapyDetectorConstruction::detectorSizeX private
Definition at line 192 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 192 of file HadrontherapyDetectorConstruction.hh
Referenced by GetDetectorToPhantomPosition(), InitializeDetectorROGeometry(), ParametersCheck(), SetDetectorPosition(), SetDetectorSize(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::detectorSizeY private
Definition at line 193 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 193 of file HadrontherapyDetectorConstruction.hh
Referenced by GetDetectorToPhantomPosition(), InitializeDetectorROGeometry(), ParametersCheck(), SetDetectorPosition(), SetDetectorSize(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::detectorSizeZ private
Definition at line 194 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 194 of file HadrontherapyDetectorConstruction.hh
Referenced by GetDetectorToPhantomPosition(), InitializeDetectorROGeometry(), ParametersCheck(), SetDetectorPosition(), SetDetectorSize(), and UpdateGeometry().
G4ThreeVector HadrontherapyDetectorConstruction::detectorToPhantomPosition private
Definition at line 196 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 196 of file HadrontherapyDetectorConstruction.hh
Referenced by ParametersCheck(), SetDetectorPosition(), and SetDetectorToPhantomPosition().
HadrontherapyDetectorConstruction * HadrontherapyDetectorConstruction::instance = 0 static private
Definition at line 170 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 170 of file HadrontherapyDetectorConstruction.hh
Referenced by GetInstance().
HadrontherapyLet* HadrontherapyDetectorConstruction::let private
Definition at line 178 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 178 of file HadrontherapyDetectorConstruction.hh
Referenced by UpdateGeometry().
G4LogicalVolume* HadrontherapyDetectorConstruction::logicVirtualLayer private
Definition at line 185 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 185 of file HadrontherapyDetectorConstruction.hh
Referenced by VirtualLayer().
G4double HadrontherapyDetectorConstruction::massOfVoxel private
Definition at line 206 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 206 of file HadrontherapyDetectorConstruction.hh
Referenced by UpdateGeometry().
HadrontherapyMatrix* HadrontherapyDetectorConstruction::matrix private
Definition at line 177 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 177 of file HadrontherapyDetectorConstruction.hh
Referenced by UpdateGeometry(), and ~HadrontherapyDetectorConstruction().
G4VPhysicalVolume* HadrontherapyDetectorConstruction::motherPhys
Definition at line 60 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructPhantom(), and VirtualLayer().
G4bool HadrontherapyDetectorConstruction::NewSource
Definition at line 65 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file HadrontherapyDetectorConstruction.hh
Referenced by VirtualLayer().
G4int HadrontherapyDetectorConstruction::numberOfVoxelsAlongX private
Definition at line 202 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 202 of file HadrontherapyDetectorConstruction.hh
Referenced by InitializeDetectorROGeometry(), PrintParameters(), and UpdateGeometry().
G4int HadrontherapyDetectorConstruction::numberOfVoxelsAlongY private
Definition at line 203 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 203 of file HadrontherapyDetectorConstruction.hh
Referenced by InitializeDetectorROGeometry(), PrintParameters(), and UpdateGeometry().
G4int HadrontherapyDetectorConstruction::numberOfVoxelsAlongZ private
Definition at line 204 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 204 of file HadrontherapyDetectorConstruction.hh
Referenced by InitializeDetectorROGeometry(), PrintParameters(), and UpdateGeometry().
G4Box* HadrontherapyDetectorConstruction::phantom private
Definition at line 180 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 180 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructPhantom(), PrintParameters(), and UpdateGeometry().
G4LogicalVolume* HadrontherapyDetectorConstruction::phantomLogicalVolume private
Definition at line 181 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 181 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructPhantom(), and SetPhantomMaterial().
G4Material* HadrontherapyDetectorConstruction::phantomMaterial private
Definition at line 208 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 208 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructPhantom(), and SetPhantomMaterial().
G4VPhysicalVolume* HadrontherapyDetectorConstruction::phantomPhysicalVolume private
Definition at line 182 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 182 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructPhantom(), and UpdateGeometry().
G4ThreeVector HadrontherapyDetectorConstruction::phantomPosition private
Definition at line 196 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 196 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructPhantom(), GetDetectorToWorldPosition(), PrintParameters(), SetPhantomPosition(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::phantomSizeX private
Definition at line 188 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 188 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructPhantom(), GetDetectorToPhantomPosition(), ParametersCheck(), SetDetectorPosition(), SetPhantomSize(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::phantomSizeY private
Definition at line 189 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 189 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructPhantom(), GetDetectorToPhantomPosition(), ParametersCheck(), SetDetectorPosition(), SetPhantomSize(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::phantomSizeZ private
Definition at line 190 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 190 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), ConstructPhantom(), GetDetectorToPhantomPosition(), ParametersCheck(), SetDetectorPosition(), SetPhantomSize(), and UpdateGeometry().
G4VPhysicalVolume* HadrontherapyDetectorConstruction::physVirtualLayer private
Definition at line 186 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 186 of file HadrontherapyDetectorConstruction.hh
Referenced by SetVirtualLayerPosition(), and VirtualLayer().
G4VisAttributes* HadrontherapyDetectorConstruction::red private
Definition at line 174 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 174 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructPhantom().
G4double HadrontherapyDetectorConstruction::sizeOfVoxelAlongX private
Definition at line 198 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 198 of file HadrontherapyDetectorConstruction.hh
Referenced by HadrontherapyDetectorConstruction(), ParametersCheck(), PrintParameters(), SetDetectorSize(), SetVoxelSize(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::sizeOfVoxelAlongY private
Definition at line 199 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 199 of file HadrontherapyDetectorConstruction.hh
Referenced by HadrontherapyDetectorConstruction(), ParametersCheck(), PrintParameters(), SetDetectorSize(), SetVoxelSize(), and UpdateGeometry().
G4double HadrontherapyDetectorConstruction::sizeOfVoxelAlongZ private
Definition at line 200 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 200 of file HadrontherapyDetectorConstruction.hh
Referenced by HadrontherapyDetectorConstruction(), ParametersCheck(), PrintParameters(), SetDetectorSize(), SetVoxelSize(), and UpdateGeometry().
G4VisAttributes* HadrontherapyDetectorConstruction::skyBlue private
Definition at line 173 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 173 of file HadrontherapyDetectorConstruction.hh
Referenced by ConstructDetector(), and VirtualLayer().
G4Box* HadrontherapyDetectorConstruction::solidVirtualLayer private
Definition at line 184 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 184 of file HadrontherapyDetectorConstruction.hh
Referenced by VirtualLayer().
G4ThreeVector HadrontherapyDetectorConstruction::VirtualLayerPosition
Definition at line 67 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file HadrontherapyDetectorConstruction.hh
Referenced by SetVirtualLayerPosition(), and VirtualLayer().
G4double HadrontherapyDetectorConstruction::volumeOfVoxel private
Definition at line 206 of file HadrontherapyDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 206 of file HadrontherapyDetectorConstruction.hh
Referenced by UpdateGeometry().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyDetectorConstruction.cc