ECCE @ EIC Software: G4TrajectoryGenericDrawer Class Reference
G4TrajectoryGenericDrawer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryGenericDrawer.hh>
Public Member Functions
G4TrajectoryGenericDrawer (const G4String &name="Unspecified", G4VisTrajContext *context=0)
virtual ~G4TrajectoryGenericDrawer ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const
virtual void Print (std::ostream &ostr) const
Public Member Functions inherited from G4VTrajectoryModel
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Detailed Description
Definition at line 40 of file G4TrajectoryGenericDrawer.hh.
View newest version in sPHENIX GitHub at line 40 of file G4TrajectoryGenericDrawer.hh
Constructor & Destructor Documentation
G4TrajectoryGenericDrawer::G4TrajectoryGenericDrawer (const G4String & name = "Unspecified", G4VisTrajContext * context = 0)
Definition at line 35 of file G4TrajectoryGenericDrawer.cc.
View newest version in sPHENIX GitHub at line 35 of file G4TrajectoryGenericDrawer.cc
G4TrajectoryGenericDrawer::~G4TrajectoryGenericDrawer () virtual
Definition at line 39 of file G4TrajectoryGenericDrawer.cc.
View newest version in sPHENIX GitHub at line 39 of file G4TrajectoryGenericDrawer.cc
Member Function Documentation
void G4TrajectoryGenericDrawer::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const virtual
Implements G4VTrajectoryModel.
Definition at line 42 of file G4TrajectoryGenericDrawer.cc.
View newest version in sPHENIX GitHub at line 42 of file G4TrajectoryGenericDrawer.cc
References G4TrajectoryDrawerUtils::DrawLineAndPoints(), G4cout, G4endl, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::GetVerbose(), G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and G4VisTrajContext::SetVisible().
void G4TrajectoryGenericDrawer::Print (std::ostream & ostr) const virtual
Implements G4VTrajectoryModel.
Definition at line 57 of file G4TrajectoryGenericDrawer.cc.
View newest version in sPHENIX GitHub at line 57 of file G4TrajectoryGenericDrawer.cc
References G4cout, G4endl, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::Name(), and G4VisTrajContext::Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryGenericDrawer.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryGenericDrawer.cc