ECCE @ EIC Software: G4GEMChannelVI Class Reference
G4GEMChannelVI Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMChannelVI.hh>
Public Member Functions
G4GEMChannelVI (G4int theA, G4int theZ)
~G4GEMChannelVI () final
G4double GetEmissionProbability (G4Fragment *theNucleus) final
G4Fragment * EmittedFragment (G4Fragment *theNucleus) final
void Dump () const final
Public Member Functions inherited from G4VEvaporationChannel
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual void Initialise ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Private Member Functions
G4GEMChannelVI (const G4GEMChannelVI &right)
const G4GEMChannelVI & operator= (const G4GEMChannelVI &right)
G4bool operator== (const G4GEMChannelVI &right) const
G4bool operator!= (const G4GEMChannelVI &right) const
Private Attributes
const G4VCoulombBarrier * cBarrier
const G4PairingCorrection * pairingCorrection
G4GEMProbabilityVI * fProbability
G4int A
G4int Z
G4int resA
G4int resZ
G4int fragA
G4int fragZ
G4double mass
G4double resMass
G4double evapMass
G4double evapMass2
Additional Inherited Members
Protected Attributes inherited from G4VEvaporationChannel
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 40 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 40 of file G4GEMChannelVI.hh
Constructor & Destructor Documentation
G4GEMChannelVI::G4GEMChannelVI (G4int theA, G4int theZ) explicit
Definition at line 41 of file G4GEMChannelVI.cc.
View newest version in sPHENIX GitHub at line 41 of file G4GEMChannelVI.cc
References A, cBarrier, evapMass, evapMass2, fProbability, fragA, fragZ, G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetLevelManager(), G4NucleiProperties::GetNuclearMass(), G4NuclearLevelData::GetPairingCorrection(), mass, pairingCorrection, resA, resMass, resZ, and Z.
G4GEMChannelVI::~G4GEMChannelVI () final
Definition at line 58 of file G4GEMChannelVI.cc.
View newest version in sPHENIX GitHub at line 58 of file G4GEMChannelVI.cc
References cBarrier, and fProbability.
G4GEMChannelVI::G4GEMChannelVI (const G4GEMChannelVI & right) private
Member Function Documentation
void G4GEMChannelVI::Dump () const final virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 122 of file G4GEMChannelVI.cc.
View newest version in sPHENIX GitHub at line 122 of file G4GEMChannelVI.cc
G4Fragment * G4GEMChannelVI::EmittedFragment (G4Fragment * theNucleus) final virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 94 of file G4GEMChannelVI.cc.
View newest version in sPHENIX GitHub at line 94 of file G4GEMChannelVI.cc
References A, CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), evapMass, evapMass2, fProbability, G4RandomDirection(), G4Fragment::GetMomentum(), mass, max, resA, resMass, resZ, G4GEMProbabilityVI::SampleEvaporationFragment(), G4Fragment::SetMomentum(), G4Fragment::SetZandA_asInt(), and Z.
G4double G4GEMChannelVI::GetEmissionProbability (G4Fragment * theNucleus) final virtual
Implements G4VEvaporationChannel.
Definition at line 64 of file G4GEMChannelVI.cc.
View newest version in sPHENIX GitHub at line 64 of file G4GEMChannelVI.cc
References A, cBarrier, G4GEMProbabilityVI::ComputeTotalProbability(), fProbability, fragA, fragZ, G4Fragment::GetA_asInt(), G4VCoulombBarrier::GetCoulombBarrier(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4NucleiProperties::GetNuclearMass(), G4PairingCorrection::GetPairingCorrection(), G4Fragment::GetZ_asInt(), max, pairingCorrection, resA, G4VEmissionProbability::ResetProbability(), resMass, resZ, G4VEmissionProbability::SetDecayKinematics(), and Z.
G4bool G4GEMChannelVI::operator!= (const G4GEMChannelVI & right) const private
const G4GEMChannelVI& G4GEMChannelVI::operator= (const G4GEMChannelVI & right) private
G4bool G4GEMChannelVI::operator== (const G4GEMChannelVI & right) const private
Member Data Documentation
G4int G4GEMChannelVI::A private
Definition at line 65 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 65 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), G4GEMChannelVI(), and GetEmissionProbability().
const G4VCoulombBarrier* G4GEMChannelVI::cBarrier private
Definition at line 61 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 61 of file G4GEMChannelVI.hh
Referenced by G4GEMChannelVI(), GetEmissionProbability(), and ~G4GEMChannelVI().
G4double G4GEMChannelVI::evapMass private
Definition at line 74 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), and G4GEMChannelVI().
G4double G4GEMChannelVI::evapMass2 private
Definition at line 75 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 75 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), and G4GEMChannelVI().
G4GEMProbabilityVI* G4GEMChannelVI::fProbability private
Definition at line 63 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), G4GEMChannelVI(), GetEmissionProbability(), and ~G4GEMChannelVI().
G4int G4GEMChannelVI::fragA private
Definition at line 69 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GEMChannelVI.hh
Referenced by G4GEMChannelVI(), and GetEmissionProbability().
G4int G4GEMChannelVI::fragZ private
Definition at line 70 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 70 of file G4GEMChannelVI.hh
Referenced by G4GEMChannelVI(), and GetEmissionProbability().
G4double G4GEMChannelVI::mass private
Definition at line 72 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), and G4GEMChannelVI().
const G4PairingCorrection* G4GEMChannelVI::pairingCorrection private
Definition at line 62 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 62 of file G4GEMChannelVI.hh
Referenced by G4GEMChannelVI(), and GetEmissionProbability().
G4int G4GEMChannelVI::resA private
Definition at line 67 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 67 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), G4GEMChannelVI(), and GetEmissionProbability().
G4double G4GEMChannelVI::resMass private
Definition at line 73 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), G4GEMChannelVI(), and GetEmissionProbability().
G4int G4GEMChannelVI::resZ private
Definition at line 68 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 68 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), G4GEMChannelVI(), and GetEmissionProbability().
G4int G4GEMChannelVI::Z private
Definition at line 66 of file G4GEMChannelVI.hh.
View newest version in sPHENIX GitHub at line 66 of file G4GEMChannelVI.hh
Referenced by EmittedFragment(), G4GEMChannelVI(), and GetEmissionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMChannelVI.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/src/G4GEMChannelVI.cc