ECCE @ EIC Software: ScoreSpecies Class Reference
ScoreSpecies Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/ScoreSpecies.hh>
Classes
struct SpeciesInfo
Public Member Functions
ScoreSpecies (G4String name, G4int depth=0)
virtual ~ScoreSpecies ()
void AddTimeToRecord (double time)
void ClearTimeToRecord ()
int GetNumberOfRecordedEvents () const
void ASCII ()
void WriteWithAnalysisManager (G4VAnalysisManager *)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void AbsorbResultsFromWorkerScorer (G4VPrimitiveScorer *)
virtual void OutputAndClear ()
SpeciesMap GetSpeciesInfo ()
ScoreSpecies (G4String name, G4int depth=0)
virtual ~ScoreSpecies ()
void AddTimeToRecord (double time)
void ClearTimeToRecord ()
int GetNumberOfRecordedEvents () const
void ASCII ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void AbsorbResultsFromWorkerScorer (G4VPrimitiveScorer *)
virtual void OutputAndClear ()
SpeciesMap GetSpeciesInfo ()
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Types
typedef const
G4MolecularConfiguration Species
typedef std::map< Species
*, SpeciesInfo > InnerSpeciesMap
typedef std::map< double,
InnerSpeciesMap > SpeciesMap
typedef const
G4MolecularConfiguration Species
typedef std::map< Species
*, SpeciesInfo > InnerSpeciesMap
typedef std::map< double,
InnerSpeciesMap > SpeciesMap
Private Attributes
SpeciesMap fSpeciesInfoPerTime
std::set< G4double > fTimeToRecord
int fNEvent
double fEdep
G4bool fOutputToRoot
G4bool fOutputToXml
G4bool fOutputToCsv
G4int fHCID
G4THitsMap< G4double > * fEvtMap
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
This is a primitive scorer class for molecular species. The number of species is recorded for all times (predetermined or user chosen). It also scores the energy deposition in order to compute the radiochemical yields.
This is a primitive scorer class for molecular species. The number of species is recorded for all times (log spaced). It also scores the energy deposition in order to compute the radiochemical yields.
Definition at line 55 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 55 of file ScoreSpecies.hh
Member Typedef Documentation
typedef std::map<Species*, SpeciesInfo> ScoreSpecies::InnerSpeciesMap private
Definition at line 111 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 111 of file ScoreSpecies.hh
typedef std::map<Species*, SpeciesInfo> ScoreSpecies::InnerSpeciesMap private
Definition at line 148 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 148 of file ScoreSpecies.hh
typedef const G4MolecularConfiguration ScoreSpecies::Species private
Definition at line 110 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 110 of file ScoreSpecies.hh
typedef const G4MolecularConfiguration ScoreSpecies::Species private
Definition at line 147 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 147 of file ScoreSpecies.hh
typedef std::map<double, InnerSpeciesMap> ScoreSpecies::SpeciesMap private
Definition at line 112 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 112 of file ScoreSpecies.hh
typedef std::map<double, InnerSpeciesMap> ScoreSpecies::SpeciesMap private
Definition at line 149 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 149 of file ScoreSpecies.hh
Constructor & Destructor Documentation
ScoreSpecies::ScoreSpecies (G4String name, G4int depth = 0)
Definition at line 57 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 57 of file ScoreSpecies.cc
References AddTimeToRecord(), fEdep, fNEvent, and CLHEP::picosecond.
ScoreSpecies::~ScoreSpecies () virtual
Definition at line 79 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 79 of file ScoreSpecies.cc
ScoreSpecies::ScoreSpecies (G4String name, G4int depth = 0)
virtual ScoreSpecies::~ScoreSpecies () virtual
Member Function Documentation
virtual void ScoreSpecies::AbsorbResultsFromWorkerScorer (G4VPrimitiveScorer *) virtual
Method used in multithreading mode in order to merge the results
void ScoreSpecies::AbsorbResultsFromWorkerScorer (G4VPrimitiveScorer * workerScorer) virtual
Method used in multithreading mode in order to merge the results
Definition at line 192 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 192 of file ScoreSpecies.cc
References clear(), fEdep, ScoreSpecies::SpeciesInfo::fG, SpeciesInfoSOA::fG, ScoreSpecies::SpeciesInfo::fG2, fNEvent, ScoreSpecies::SpeciesInfo::fNumber, fSpeciesInfoPerTime, and right.
void ScoreSpecies::AddTimeToRecord (double time) inline
Add a time at which the number of species should be recorded. Default times are set up to 1 microsecond.
Definition at line 62 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 62 of file ScoreSpecies.hh
References fTimeToRecord.
void ScoreSpecies::AddTimeToRecord (double time) inline
Add a time at which the number of species should be recorded. Default times are set up to 1 microsecond.
Definition at line 64 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 64 of file ScoreSpecies.hh
References fTimeToRecord.
Referenced by ScoreSpecies().
void ScoreSpecies::ASCII ()
Write results to an text file
void ScoreSpecies::ASCII ()
Write results to an text file
Definition at line 313 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 313 of file ScoreSpecies.cc
References fSpeciesInfoPerTime, and G4endl.
virtual void ScoreSpecies::clear () virtual
Reimplemented from G4VPrimitiveScorer.
void ScoreSpecies::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 279 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 279 of file ScoreSpecies.cc
References G4VTHitsMap< T, Map_t >::clear(), fEdep, fEvtMap, fNEvent, and fSpeciesInfoPerTime.
Referenced by AbsorbResultsFromWorkerScorer().
void ScoreSpecies::ClearTimeToRecord () inline
Remove all times to record, must be reset by user.
Definition at line 68 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 68 of file ScoreSpecies.hh
References fTimeToRecord.
void ScoreSpecies::ClearTimeToRecord () inline
Remove all times to record, must be reset by user.
Definition at line 70 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 70 of file ScoreSpecies.hh
References fTimeToRecord.
virtual void ScoreSpecies::DrawAll () virtual
Reimplemented from G4VPrimitiveScorer.
void ScoreSpecies::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 289 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 289 of file ScoreSpecies.cc
virtual void ScoreSpecies::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
void ScoreSpecies::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 115 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 115 of file ScoreSpecies.cc
References eV, FatalException, fEdep, ScoreSpecies::SpeciesInfo::fG, SpeciesInfoSOA::fG, ScoreSpecies::SpeciesInfo::fG2, fNEvent, ScoreSpecies::SpeciesInfo::fNumber, fSpeciesInfoPerTime, fTimeToRecord, G4BestUnit, G4cerr, G4cout, G4endl, G4Exception(), G4EventManager::GetConstCurrentEvent(), G4Event::GetEventID(), G4EventManager::GetEventManager(), G4MoleculeCounter::GetNMoleculesAtTime(), G4MoleculeCounter::GetRecordedMolecules(), G4MoleculeCounter::Instance(), molecule(), and G4MoleculeCounter::ResetCounter().
int ScoreSpecies::GetNumberOfRecordedEvents () const inline
Get number of recorded events
Definition at line 74 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 74 of file ScoreSpecies.hh
References fNEvent.
int ScoreSpecies::GetNumberOfRecordedEvents () const inline
Get number of recorded events
Definition at line 76 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 76 of file ScoreSpecies.hh
References fNEvent.
SpeciesMap ScoreSpecies::GetSpeciesInfo () inline
Definition at line 134 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 134 of file ScoreSpecies.hh
References fSpeciesInfoPerTime.
SpeciesMap ScoreSpecies::GetSpeciesInfo () inline
Definition at line 180 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 180 of file ScoreSpecies.hh
References fSpeciesInfoPerTime.
virtual void ScoreSpecies::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
void ScoreSpecies::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 100 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 100 of file ScoreSpecies.cc
References G4HCofThisEvent::AddHitsCollection(), fEvtMap, fHCID, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetMultiFunctionalDetector(), G4VPrimitiveScorer::GetName(), and G4VSensitiveDetector::GetName().
virtual void ScoreSpecies::OutputAndClear () virtual
void ScoreSpecies::OutputAndClear () virtual
Definition at line 338 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 338 of file ScoreSpecies.cc
References fNEvent, fOutputToCsv, fOutputToRoot, fOutputToXml, fSpeciesInfoPerTime, G4Threading::IsWorkerThread(), G4Analysis::ManagerInstance(), and WriteWithAnalysisManager().
virtual void ScoreSpecies::PrintAll () virtual
Reimplemented from G4VPrimitiveScorer.
void ScoreSpecies::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 294 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 294 of file ScoreSpecies.cc
References G4VPrimitiveScorer::detector, G4VTHitsMap< T, Map_t >::entries(), fEvtMap, fNEvent, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), G4VPrimitiveScorer::GetUnit(), and G4VPrimitiveScorer::GetUnitValue().
virtual G4bool ScoreSpecies::ProcessHits (G4Step * , G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
G4bool ScoreSpecies::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 84 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 84 of file ScoreSpecies.cc
References G4VTHitsMap< T, Map_t >::add(), edep, FALSE, fEdep, fEvtMap, G4VPrimitiveScorer::GetIndex(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetWeight(), and TRUE.
void ScoreSpecies::WriteWithAnalysisManager (G4VAnalysisManager * analysisManager)
Write results to whatever chosen file format
Definition at line 373 of file ScoreSpecies.cc.
View newest version in sPHENIX GitHub at line 373 of file ScoreSpecies.cc
References G4VAnalysisManager::AddNtupleRow(), G4VAnalysisManager::CloseFile(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4VAnalysisManager::CreateNtupleSColumn(), G4VAnalysisManager::FillNtupleDColumn(), G4VAnalysisManager::FillNtupleIColumn(), G4VAnalysisManager::FillNtupleSColumn(), G4VAnalysisManager::FinishNtuple(), G4String::first(), fNEvent, fSpeciesInfoPerTime, G, G4MolecularConfiguration::GetName(), G4VAnalysisManager::OpenFile(), Acts::VectorHelpers::time(), and G4VAnalysisManager::Write().
Referenced by OutputAndClear().
Member Data Documentation
double ScoreSpecies::fEdep private
Definition at line 161 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 161 of file ScoreSpecies.hh
Referenced by AbsorbResultsFromWorkerScorer(), clear(), EndOfEvent(), ProcessHits(), and ScoreSpecies().
G4THitsMap< G4double > * ScoreSpecies::fEvtMap private
Definition at line 184 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 184 of file ScoreSpecies.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int ScoreSpecies::fHCID private
Definition at line 183 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 183 of file ScoreSpecies.hh
Referenced by Initialize().
int ScoreSpecies::fNEvent private
Definition at line 160 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 160 of file ScoreSpecies.hh
Referenced by AbsorbResultsFromWorkerScorer(), clear(), EndOfEvent(), GetNumberOfRecordedEvents(), OutputAndClear(), PrintAll(), ScoreSpecies(), and WriteWithAnalysisManager().
G4bool ScoreSpecies::fOutputToCsv private
Definition at line 164 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 164 of file ScoreSpecies.hh
Referenced by OutputAndClear().
G4bool ScoreSpecies::fOutputToRoot private
Definition at line 162 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 162 of file ScoreSpecies.hh
Referenced by OutputAndClear().
G4bool ScoreSpecies::fOutputToXml private
Definition at line 163 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 163 of file ScoreSpecies.hh
Referenced by OutputAndClear().
SpeciesMap ScoreSpecies::fSpeciesInfoPerTime private
Definition at line 150 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 150 of file ScoreSpecies.hh
Referenced by AbsorbResultsFromWorkerScorer(), ASCII(), clear(), EndOfEvent(), GetSpeciesInfo(), OutputAndClear(), and WriteWithAnalysisManager().
std::set< G4double > ScoreSpecies::fTimeToRecord private
Definition at line 158 of file ScoreSpecies.hh.
View newest version in sPHENIX GitHub at line 158 of file ScoreSpecies.hh
Referenced by AddTimeToRecord(), ClearTimeToRecord(), and EndOfEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/ScoreSpecies.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/ScoreSpecies.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/ScoreSpecies.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/ScoreSpecies.cc