ECCE @ EIC Software: G4NonEquilibriumEvaporator Class Reference
G4NonEquilibriumEvaporator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4NonEquilibriumEvaporator.hh>
Public Member Functions
G4NonEquilibriumEvaporator ()
virtual ~G4NonEquilibriumEvaporator ()
virtual void deExcite (const G4Fragment &target, G4CollisionOutput &output)
Public Member Functions inherited from G4CascadeDeexciteBase
G4CascadeDeexciteBase (const char *name)
virtual ~G4CascadeDeexciteBase ()
virtual void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4VCascadeDeexcitation
G4VCascadeDeexcitation (const G4String &name)
virtual ~G4VCascadeDeexcitation ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Private Member Functions
G4double getMatrixElement (G4int A) const
G4double getE0 (G4int A) const
G4double getParLev (G4int A, G4int Z) const
G4NonEquilibriumEvaporator (const G4NonEquilibriumEvaporator &)
G4NonEquilibriumEvaporator & operator= (const G4NonEquilibriumEvaporator &)
Private Attributes
G4InuclSpecialFunctions::paraMaker theParaMaker
G4Pow * theG4Pow
Additional Inherited Members
Protected Member Functions inherited from G4CascadeDeexciteBase
virtual G4bool explosion (const G4Fragment &target) const
virtual G4bool explosion (G4int A, G4int Z, G4double excitation) const
virtual G4bool validateOutput (const G4Fragment &target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
void getTargetData (const G4Fragment &target)
const G4Fragment & makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX=0.)
const G4Fragment & makeFragment (G4int A, G4int Z, G4double EX=0.)
Protected Attributes inherited from G4CascadeDeexciteBase
G4CascadeCheckBalance * balance
G4int A
G4int Z
G4LorentzVector PEX
G4double EEXS
G4Fragment aFragment
Detailed Description
Definition at line 46 of file G4NonEquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 46 of file G4NonEquilibriumEvaporator.hh
Constructor & Destructor Documentation
G4NonEquilibriumEvaporator::G4NonEquilibriumEvaporator ()
Definition at line 68 of file G4NonEquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 68 of file G4NonEquilibriumEvaporator.cc
virtual G4NonEquilibriumEvaporator::~G4NonEquilibriumEvaporator () inline virtual
Definition at line 49 of file G4NonEquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 49 of file G4NonEquilibriumEvaporator.hh
G4NonEquilibriumEvaporator::G4NonEquilibriumEvaporator (const G4NonEquilibriumEvaporator &) private
Member Function Documentation
void G4NonEquilibriumEvaporator::deExcite (const G4Fragment & target, G4CollisionOutput & output) virtual
Implements G4VCascadeDeexcitation.
Definition at line 73 of file G4NonEquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 73 of file G4NonEquilibriumEvaporator.cc
References G4CascadeDeexciteBase::A, G4CollisionOutput::addOutgoingParticle(), G4CollisionOutput::addRecoilFragment(), B(), G4LorentzConvertor::backToTheLab(), G4InuclSpecialFunctions::bindingEnergy(), G4InuclSpecialFunctions::csNN(), G4InuclSpecialFunctions::csPN(), D(), E, CLHEP::HepLorentzVector::e(), G4CascadeDeexciteBase::EEXS, F, F1, F2, G4InuclSpecialFunctions::FermiEnergy(), G4InuclSpecialFunctions::G4cbrt(), G4cout, G4endl, G4InuclSpecialFunctions::generateWithRandomAngles(), G4InuclSpecialFunctions::getAL(), getE0(), G4InuclParticle::getMass(), getMatrixElement(), G4InuclNuclei::getNucleiMass(), getParLev(), G4CollisionOutput::getRecoilFragment(), G4CascadeDeexciteBase::getTargetData(), G4InuclSpecialFunctions::paraMaker::getTruncated(), GeV, G4InuclSpecialFunctions::inuclRndm(), m, G4CascadeDeexciteBase::makeFragment(), mass, mom, G4ExitonConfiguration::neutronHoles, G4ExitonConfiguration::neutronQuasiParticles, G4InuclParticle::NonEquilib, G4CollisionOutput::numberOfOutgoingParticles(), particle, G4CascadeDeexciteBase::PEX, G4Pow::powA(), G4Pow::powN(), G4ExitonConfiguration::protonHoles, G4ExitonConfiguration::protonQuasiParticles, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), Acts::IntegrationTest::R, G4LorentzConvertor::setBullet(), G4InuclParticle::setModel(), G4InuclParticle::setMomentum(), G4LorentzConvertor::setTarget(), CLHEP::HepLorentzVector::setVectM(), SL, theG4Pow, theParaMaker, G4LorentzConvertor::toTheTargetRestFrame(), G4CascadeDeexciteBase::validateOutput(), CLHEP::HepLorentzVector::vect(), G4VCascadeCollider::verboseLevel, X, and G4CascadeDeexciteBase::Z.
Referenced by G4CascadeDeexcitation::deExcite().
G4double G4NonEquilibriumEvaporator::getE0 (G4int A) const private
Definition at line 494 of file G4NonEquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 494 of file G4NonEquilibriumEvaporator.cc
References G4cout, G4endl, and G4VCascadeCollider::verboseLevel.
Referenced by deExcite().
G4double G4NonEquilibriumEvaporator::getMatrixElement (G4int A) const private
Definition at line 480 of file G4NonEquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 480 of file G4NonEquilibriumEvaporator.cc
References G4cout, G4endl, and G4VCascadeCollider::verboseLevel.
Referenced by deExcite().
G4double G4NonEquilibriumEvaporator::getParLev (G4int A, G4int Z) const private
Definition at line 504 of file G4NonEquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 504 of file G4NonEquilibriumEvaporator.cc
References a, G4cout, G4endl, readPY::pl, and G4VCascadeCollider::verboseLevel.
Referenced by deExcite().
G4NonEquilibriumEvaporator& G4NonEquilibriumEvaporator::operator= (const G4NonEquilibriumEvaporator &) private
Member Data Documentation
G4Pow* G4NonEquilibriumEvaporator::theG4Pow private
Definition at line 55 of file G4NonEquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 55 of file G4NonEquilibriumEvaporator.hh
Referenced by deExcite().
G4InuclSpecialFunctions::paraMaker G4NonEquilibriumEvaporator::theParaMaker private
Definition at line 54 of file G4NonEquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 54 of file G4NonEquilibriumEvaporator.hh
Referenced by deExcite().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4NonEquilibriumEvaporator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4NonEquilibriumEvaporator.cc