ECCE @ EIC Software: G4VVisCommand Class Reference
G4VVisCommand Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VVisCommand.hh>
Inherits G4UImessenger.
Inherited by G4VisCommandAbortReviewKeptEvents, G4VisCommandDrawLogicalVolume, G4VisCommandDrawOnlyToBeKeptEvents, G4VisCommandDrawTree, G4VisCommandDrawView, G4VisCommandDrawVolume, G4VisCommandEnable, G4VisCommandInitialize, G4VisCommandList, G4VisCommandModelCreate< Factory >, G4VisCommandOpen, G4VisCommandReviewKeptEvents, G4VisCommandSceneHandlerAttach, G4VisCommandSceneHandlerCreate, G4VisCommandSceneHandlerList, G4VisCommandSceneHandlerSelect, G4VisCommandSetArrow3DLineSegmentsPerCircle, G4VisCommandSetColour, G4VisCommandSetExtentForField, G4VisCommandSetLineWidth, G4VisCommandSetTextColour, G4VisCommandSetTextLayout, G4VisCommandSetTextSize, G4VisCommandSetTouchable, G4VisCommandSetVolumeForField, G4VisCommandSpecify, G4VisCommandsTouchable, G4VisCommandsTouchableSet, G4VisCommandsViewerSet, G4VisCommandVerbose, G4VisCommandViewerAddCutawayPlane, G4VisCommandViewerCentreOn, G4VisCommandViewerChangeCutawayPlane, G4VisCommandViewerClear, G4VisCommandViewerClearCutawayPlanes, G4VisCommandViewerClearTransients, G4VisCommandViewerClearVisAttributesModifiers, G4VisCommandViewerClone, G4VisCommandViewerColourByDensity, G4VisCommandViewerCopyViewFrom, G4VisCommandViewerCreate, G4VisCommandViewerDefaultHiddenEdge, G4VisCommandViewerDefaultStyle, G4VisCommandViewerDolly, G4VisCommandViewerFlush, G4VisCommandViewerInterpolate, G4VisCommandViewerList, G4VisCommandViewerPan, G4VisCommandViewerRebuild, G4VisCommandViewerRefresh, G4VisCommandViewerReset, G4VisCommandViewerSave, G4VisCommandViewerScale, G4VisCommandViewerSelect, G4VisCommandViewerUpdate, G4VisCommandViewerZoom, G4VVisCommandGeometry, and G4VVisCommandScene.
Public Member Functions
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Static Public Member Functions
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions
void SetViewParameters (G4VViewer *viewer, const G4ViewParameters &viewParams)
void RefreshIfRequired (G4VViewer *viewer)
void InterpolateViews (G4VViewer *currentViewer, std::vector< G4ViewParameters > viewVector, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
void InterpolateToNewView (G4VViewer *currentViewer, const G4ViewParameters &oldVP, const G4ViewParameters &newVP, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
const G4String & ConvertToColourGuidance ()
void ConvertToColour (G4Colour &colour, const G4String &redOrString, G4double green, G4double blue, G4double opacity)
G4bool ProvideValueOfUnit (const G4String &where, const G4String &unit, const G4String &category, G4double &value)
void CheckSceneAndNotifyHandlers (G4Scene *=nullptr)
void G4VisCommandsSceneAddUnsuccessful (G4VisManager::Verbosity verbosity)
void CopyGuidanceFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd, G4int startLine=0)
void CopyParametersFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd)
void DrawExtent (const G4VisExtent &)
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Static Protected Member Functions
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Static Protected Attributes
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Additional Inherited Members
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 47 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VVisCommand.hh
Constructor & Destructor Documentation
G4VVisCommand::G4VVisCommand ()
Definition at line 54 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VVisCommand.cc
G4VVisCommand::~G4VVisCommand () virtual
Definition at line 56 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VVisCommand.cc
Member Function Documentation
void G4VVisCommand::CheckSceneAndNotifyHandlers (G4Scene * pScene = nullptr) protected
Definition at line 192 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 192 of file G4VVisCommand.cc
References fpVisManager, G4cout, G4endl, G4VSceneHandler::GetScene(), G4UImanager::GetUIpointer(), G4VisManager::GetVerbosity(), and G4VisManager::warnings.
Referenced by G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSceneActivateModel::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandSceneAddDigis::SetNewValue(), G4VisCommandSceneSelect::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddGPS::SetNewValue(), G4VisCommandSceneAddHits::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandViewerRefresh::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), G4VisCommandSceneAddMagneticField::SetNewValue(), G4VisCommandSceneAddPSHits::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), G4VisCommandSceneAddText2D::SetNewValue(), G4VisCommandSceneAddTrajectories::SetNewValue(), G4VisCommandSceneAddUserAction::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
void G4VVisCommand::ConvertToColour (G4Colour & colour, const G4String & redOrString, G4double green, G4double blue, G4double opacity) protected
Definition at line 105 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 105 of file G4VVisCommand.cc
References G4cout, G4endl, G4Colour::GetColour(), G4Colour::SetAlpha(), and G4VisManager::warnings.
Referenced by G4VisCommandSetColour::SetNewValue(), G4VisCommandSetTextColour::SetNewValue(), and G4VisCommandSceneAddGPS::SetNewValue().
const G4String & G4VVisCommand::ConvertToColourGuidance () protected
Definition at line 94 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 94 of file G4VVisCommand.cc
Referenced by G4VisCommandSceneAddGPS::G4VisCommandSceneAddGPS(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), and G4VisCommandsViewerSet::G4VisCommandsViewerSet().
G4bool G4VVisCommand::ConvertToDoublePair (const G4String & paramString, G4double & xval, G4double & yval) static protected
Definition at line 70 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 70 of file G4VVisCommand.cc
References G4VisManager::errors, fpVisManager, G4cout, G4endl, G4VisManager::GetVerbosity(), G4UnitDefinition::IsUnitDefined(), G4UIcommand::ValueOf(), x, and y.
Referenced by G4VisCommandViewerPan::SetNewValue().
G4String G4VVisCommand::ConvertToString (G4double x, G4double y, const char * unitName) static protected
Definition at line 61 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VVisCommand.cc
References G4UIcommand::ValueOf().
Referenced by G4VisCommandViewerPan::GetCurrentValue().
void G4VVisCommand::CopyGuidanceFrom (const G4UIcommand * fromCmd, G4UIcommand * toCmd, G4int startLine = 0) protected
Definition at line 307 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 307 of file G4VVisCommand.cc
References G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), and G4UIcommand::SetGuidance().
Referenced by G4VisCommandDrawLogicalVolume::G4VisCommandDrawLogicalVolume(), G4VisCommandDrawVolume::G4VisCommandDrawVolume(), G4VisCommandSceneAddMagneticField::G4VisCommandSceneAddMagneticField(), G4VisCommandsTouchable::G4VisCommandsTouchable(), and G4VisCommandViewerCentreOn::G4VisCommandViewerCentreOn().
void G4VVisCommand::CopyParametersFrom (const G4UIcommand * fromCmd, G4UIcommand * toCmd) protected
Definition at line 319 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 319 of file G4VVisCommand.cc
References G4UIcommand::GetParameter(), G4UIcommand::GetParameterEntries(), and G4UIcommand::SetParameter().
Referenced by G4VisCommandDrawLogicalVolume::G4VisCommandDrawLogicalVolume(), G4VisCommandDrawVolume::G4VisCommandDrawVolume(), G4VisCommandSceneAddMagneticField::G4VisCommandSceneAddMagneticField(), and G4VisCommandViewerCentreOn::G4VisCommandViewerCentreOn().
void G4VVisCommand::DrawExtent (const G4VisExtent & extent) protected
Definition at line 330 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 330 of file G4VVisCommand.cc
References G4VisManager::Draw(), fpVisManager, G4VisExtent::GetExtentCenter(), G4VisExtent::GetXmax(), G4VisExtent::GetXmin(), G4VisExtent::GetYmax(), G4VisExtent::GetYmin(), G4VisExtent::GetZmax(), G4VisExtent::GetZmin(), Acts::Test::halfX, Acts::Test::halfY, and G4Colour::Red().
Referenced by G4VisCommandSetVolumeForField::SetNewValue(), and G4VisCommandSceneShowExtents::SetNewValue().
void G4VVisCommand::G4VisCommandsSceneAddUnsuccessful (G4VisManager::Verbosity verbosity) protected
Definition at line 223 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 223 of file G4VVisCommand.cc
References G4cout, G4endl, and G4VisManager::warnings.
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandSceneAddDigis::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddGPS::SetNewValue(), G4VisCommandSceneAddHits::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), G4VisCommandSceneAddMagneticField::SetNewValue(), G4VisCommandSceneAddPSHits::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), G4VisCommandSceneAddText2D::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
static const G4Colour& G4VVisCommand::GetCurrentTextColour () inline static
Definition at line 58 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VVisCommand.hh
References fCurrentTextColour.
Referenced by G4VSceneHandler::AddPrimitive(), and G4VSceneHandler::GetTextColour().
void G4VVisCommand::InterpolateToNewView (G4VViewer * currentViewer, const G4ViewParameters & oldVP, const G4ViewParameters & newVP, const G4int nInterpolationPoints = 50, const G4int waitTimePerPointmilliseconds = 20, const G4String exportString = "") protected
Definition at line 285 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 285 of file G4VVisCommand.cc
Referenced by G4VisCommandViewerCentreOn::SetNewValue().
void G4VVisCommand::InterpolateViews (G4VViewer * currentViewer, std::vector< G4ViewParameters > viewVector, const G4int nInterpolationPoints = 50, const G4int waitTimePerPointmilliseconds = 20, const G4String exportString = "") protected
Definition at line 257 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 257 of file G4VVisCommand.cc
References G4UImanager::ApplyCommand(), G4ViewParameters::CatmullRomCubicSplineInterpolation(), G4String::contains(), G4VViewer::GetName(), G4UImanager::GetUIpointer(), G4VViewer::RefreshView(), G4VViewer::SetViewParameters(), and G4VViewer::ShowView().
Referenced by G4VisCommandViewerInterpolate::SetNewValue().
G4bool G4VVisCommand::ProvideValueOfUnit (const G4String & where, const G4String & unit, const G4String & category, G4double & value) protected
Definition at line 161 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 161 of file G4VVisCommand.cc
References G4cerr, G4endl, G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4UnitDefinition::IsUnitDefined(), and G4VisManager::warnings.
Referenced by G4VisCommandViewerColourByDensity::SetNewValue().
void G4VVisCommand::RefreshIfRequired (G4VViewer * viewer) protected
Definition at line 239 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 239 of file G4VVisCommand.cc
References G4UImanager::ApplyCommand(), fpVisManager, G4cout, G4endl, G4VSceneHandler::GetScene(), G4VViewer::GetSceneHandler(), G4UImanager::GetUIpointer(), G4VisManager::GetVerbosity(), G4VViewer::GetViewParameters(), G4ViewParameters::IsAutoRefresh(), and G4VisManager::warnings.
Referenced by G4VisCommandViewerReset::SetNewValue(), G4VisCommandViewerRebuild::SetNewValue(), and G4VisCommandViewerSelect::SetNewValue().
void G4VVisCommand::SetViewParameters (G4VViewer * viewer, const G4ViewParameters & viewParams) protected
Definition at line 234 of file G4VVisCommand.cc.
View newest version in sPHENIX GitHub at line 234 of file G4VVisCommand.cc
References G4VViewer::SetViewParameters().
Referenced by G4VisCommandViewerAddCutawayPlane::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandViewerChangeCutawayPlane::SetNewValue(), G4VisCommandViewerClearCutawayPlanes::SetNewValue(), G4VisCommandViewerClearVisAttributesModifiers::SetNewValue(), G4VisCommandViewerColourByDensity::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandViewerDolly::SetNewValue(), G4VisCommandViewerPan::SetNewValue(), G4VisCommandViewerScale::SetNewValue(), and G4VisCommandViewerZoom::SetNewValue().
static void G4VVisCommand::SetVisManager (G4VisManager * pVisManager) inline static
Definition at line 55 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VVisCommand.hh
References fpVisManager.
Referenced by G4VisManager::G4VisManager().
Member Data Documentation
G4int G4VVisCommand::fCurrentArrow3DLineSegmentsPerCircle = 6 static protected
Definition at line 138 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 138 of file G4VVisCommand.hh
Referenced by G4VisCommandSetArrow3DLineSegmentsPerCircle::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), and G4VisCommandSceneAddMagneticField::SetNewValue().
G4Colour G4VVisCommand::fCurrentColour = G4Colour::White() static protected
Definition at line 139 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 139 of file G4VVisCommand.hh
Referenced by G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSetColour::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), and G4VisCommandSceneAddLine2D::SetNewValue().
G4VisExtent G4VVisCommand::fCurrentExtentForField static protected
Definition at line 148 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 148 of file G4VVisCommand.hh
Referenced by G4VisCommandSetExtentForField::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), and G4VisCommandSceneAddMagneticField::SetNewValue().
G4double G4VVisCommand::fCurrentLineWidth = 1. static protected
Definition at line 140 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VVisCommand.hh
Referenced by G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSetLineWidth::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), and G4VisCommandSceneAddLine2D::SetNewValue().
G4Colour G4VVisCommand::fCurrentTextColour = G4Colour::Blue() static protected
Definition at line 144 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 144 of file G4VVisCommand.hh
Referenced by GetCurrentTextColour(), G4VisCommandSetTextColour::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
G4Text::Layout G4VVisCommand::fCurrentTextLayout = G4Text::left static protected
Definition at line 145 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 145 of file G4VVisCommand.hh
Referenced by G4VisCommandSetTextLayout::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
G4double G4VVisCommand::fCurrentTextSize = 12. static protected
Definition at line 146 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 146 of file G4VVisCommand.hh
Referenced by G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSetTextSize::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4PhysicalVolumeModel::TouchableProperties G4VVisCommand::fCurrentTouchableProperties static protected
Definition at line 147 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VVisCommand.hh
Referenced by G4VisCommandSetTouchable::SetNewValue().
std::vector< G4PhysicalVolumesSearchScene::Findings > G4VVisCommand::fCurrrentPVFindingsForField static protected
Definition at line 149 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VVisCommand.hh
Referenced by G4VisCommandSetExtentForField::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), and G4VisCommandSceneAddMagneticField::SetNewValue().
G4int G4VVisCommand::fErrorCode = 0 static protected
Definition at line 135 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 135 of file G4VVisCommand.hh
Referenced by G4VisCommandDrawTree::SetNewValue(), and G4VisCommandOpen::SetNewValue().
G4VisManager * G4VVisCommand::fpVisManager = 0 static protected
Definition at line 133 of file G4VVisCommand.hh.
View newest version in sPHENIX GitHub at line 133 of file G4VVisCommand.hh
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), CheckSceneAndNotifyHandlers(), ConvertToDoublePair(), G4VVisCommandScene::CurrentSceneName(), DrawExtent(), G4VisCommandSceneHandlerCreate::G4VisCommandSceneHandlerCreate(), G4VisCommandSceneHandlerAttach::GetCurrentValue(), G4VisCommandSceneHandlerCreate::GetCurrentValue(), G4VisCommandViewerClear::GetCurrentValue(), G4VisCommandViewerClearTransients::GetCurrentValue(), G4VisCommandViewerClone::GetCurrentValue(), G4VisCommandViewerCreate::GetCurrentValue(), G4VisCommandViewerReset::GetCurrentValue(), G4VisCommandViewerRefresh::GetCurrentValue(), G4VisCommandViewerRebuild::GetCurrentValue(), G4VisCommandViewerUpdate::GetCurrentValue(), G4VisCommandViewerCreate::NextName(), RefreshIfRequired(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), G4VisCommandAbortReviewKeptEvents::SetNewValue(), G4VisCommandSceneHandlerAttach::SetNewValue(), G4VisCommandSetArrow3DLineSegmentsPerCircle::SetNewValue(), G4VisCommandViewerAddCutawayPlane::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSceneActivateModel::SetNewValue(), G4VisCommandViewerDefaultStyle::SetNewValue(), G4VisCommandSceneHandlerCreate::SetNewValue(), G4VisCommandDrawOnlyToBeKeptEvents::SetNewValue(), G4VisCommandGeometryList::SetNewValue(), G4VisCommandSetColour::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandEnable::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4VisCommandSceneCreate::SetNewValue(), G4VisCommandSceneHandlerList::SetNewValue(), G4VisCommandSetExtentForField::SetNewValue(), G4VisCommandDrawVolume::SetNewValue(), G4VisCommandViewerChangeCutawayPlane::SetNewValue(), G4VisCommandSceneHandlerSelect::SetNewValue(), G4VisCommandInitialize::SetNewValue(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandSetLineWidth::SetNewValue(), G4VisCommandOpen::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandViewerClear::SetNewValue(), G4VisCommandList::SetNewValue(), G4VisCommandSpecify::SetNewValue(), G4VisCommandSetTextColour::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandViewerClearCutawayPlanes::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandSetTextLayout::SetNewValue(), G4VisCommandSceneList::SetNewValue(), G4VisCommandViewerClearTransients::SetNewValue(), G4VisCommandVerbose::SetNewValue(), G4VisCommandSetTextSize::SetNewValue(), G4VisCommandSceneNotifyHandlers::SetNewValue(), G4VisCommandViewerClearVisAttributesModifiers::SetNewValue(), G4VisCommandSceneAddDigis::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSceneSelect::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneShowExtents::SetNewValue(), G4VisCommandViewerColourByDensity::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), G4VisCommandViewerDolly::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandViewerFlush::SetNewValue(), G4VisCommandSceneAddGPS::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), G4VisCommandViewerList::SetNewValue(), G4VisCommandSceneAddHits::SetNewValue(), G4VisCommandViewerPan::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandViewerReset::SetNewValue(), G4VisCommandViewerRefresh::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandViewerRebuild::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandViewerScale::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandViewerSelect::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), G4VisCommandViewerUpdate::SetNewValue(), G4VisCommandViewerZoom::SetNewValue(), G4VisCommandSceneAddMagneticField::SetNewValue(), G4VisCommandSceneAddPSHits::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), G4VisCommandSceneAddText2D::SetNewValue(), G4VisCommandSceneAddTrajectories::SetNewValue(), G4VisCommandSceneAddUserAction::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), and SetVisManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VVisCommand.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VVisCommand.cc