ECCE @ EIC Software: G4VDigitizerModule Class Reference
G4VDigitizerModule Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/readout/include/G4VDigitizerModule.hh>
Public Member Functions
G4VDigitizerModule (const G4String &modName)
virtual ~G4VDigitizerModule ()
G4bool operator== (const G4VDigitizerModule &right) const
G4bool operator!= (const G4VDigitizerModule &right) const
virtual void Digitize ()=0
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int i) const
G4String GetName () const
void SetVerboseLevel (G4int val)
Protected Member Functions
void StoreDigiCollection (G4VDigiCollection *aDC)
void StoreDigiCollection (G4int DCID, G4VDigiCollection *aDC)
Protected Attributes
G4DigiManager * DigiManager
G4String moduleName
std::vector< G4String > collectionName
G4int verboseLevel
Detailed Description
Definition at line 48 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VDigitizerModule.hh
Constructor & Destructor Documentation
G4VDigitizerModule::G4VDigitizerModule (const G4String & modName)
Definition at line 35 of file G4VDigitizerModule.cc.
View newest version in sPHENIX GitHub at line 35 of file G4VDigitizerModule.cc
References DigiManager, G4DigiManager::GetDMpointer(), and moduleName.
G4VDigitizerModule::~G4VDigitizerModule () virtual
Definition at line 42 of file G4VDigitizerModule.cc.
View newest version in sPHENIX GitHub at line 42 of file G4VDigitizerModule.cc
Member Function Documentation
virtual void G4VDigitizerModule::Digitize () pure virtual
Implemented in CexmcEnergyDepositDigitizer, CexmcTrackPointsDigitizer, and GammaRayTelDigitizer.
Referenced by G4DigiManager::Digitize().
G4String G4VDigitizerModule::GetCollectionName (G4int i) const inline
Definition at line 71 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VDigitizerModule.hh
References collectionName.
Referenced by G4DigiManager::AddNewModule(), and G4DCtable::GetCollectionID().
G4String G4VDigitizerModule::GetName (void) const inline
Definition at line 73 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VDigitizerModule.hh
References moduleName.
Referenced by G4DigiManager::AddNewModule(), and G4DCtable::GetCollectionID().
G4int G4VDigitizerModule::GetNumberOfCollections () const inline
Definition at line 69 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VDigitizerModule.hh
References collectionName.
Referenced by G4DigiManager::AddNewModule(), and G4DCtable::GetCollectionID().
G4bool G4VDigitizerModule::operator!= (const G4VDigitizerModule & right) const
Definition at line 50 of file G4VDigitizerModule.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VDigitizerModule.cc
References moduleName.
G4bool G4VDigitizerModule::operator== (const G4VDigitizerModule & right) const
Definition at line 45 of file G4VDigitizerModule.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VDigitizerModule.cc
References moduleName.
void G4VDigitizerModule::SetVerboseLevel (G4int val) inline
Definition at line 75 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VDigitizerModule.hh
References verboseLevel.
void G4VDigitizerModule::StoreDigiCollection (G4VDigiCollection * aDC) protected
Definition at line 55 of file G4VDigitizerModule.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VDigitizerModule.cc
References DigiManager, G4DigiManager::GetDigiCollectionID(), G4VDigiCollection::GetName(), and moduleName.
Referenced by GammaRayTelDigitizer::Digitize().
void G4VDigitizerModule::StoreDigiCollection (G4int DCID, G4VDigiCollection * aDC) protected
Definition at line 64 of file G4VDigitizerModule.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VDigitizerModule.cc
References DigiManager, and G4DigiManager::SetDigiCollection().
Member Data Documentation
std::vector<G4String> G4VDigitizerModule::collectionName protected
Definition at line 87 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VDigitizerModule.hh
Referenced by GammaRayTelDigitizer::GammaRayTelDigitizer(), GetCollectionName(), and GetNumberOfCollections().
G4DigiManager* G4VDigitizerModule::DigiManager protected
Definition at line 85 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VDigitizerModule.hh
Referenced by G4VDigitizerModule(), and StoreDigiCollection().
G4String G4VDigitizerModule::moduleName protected
Definition at line 86 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VDigitizerModule.hh
Referenced by G4VDigitizerModule(), GetName(), operator!=(), operator==(), and StoreDigiCollection().
G4int G4VDigitizerModule::verboseLevel protected
Definition at line 88 of file G4VDigitizerModule.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VDigitizerModule.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/readout/include/G4VDigitizerModule.hh
geant4/tree/geant4-10.6-release/source/readout/src/G4VDigitizerModule.cc