ECCE @ EIC Software: G4IonDEDXHandler Class Reference
G4IonDEDXHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonDEDXHandler.hh>
Classes
struct CacheEntry
Public Member Functions
G4IonDEDXHandler (G4VIonDEDXTable *tables, G4VIonDEDXScalingAlgorithm *algorithm, const G4String &name, G4int maxCacheSize=5, G4bool splines=true)
~G4IonDEDXHandler ()
G4bool IsApplicable (const G4ParticleDefinition *, const G4Material *)
G4double GetDEDX (const G4ParticleDefinition *, const G4Material *, G4double)
G4bool BuildDEDXTable (const G4ParticleDefinition *, const G4Material *)
G4bool BuildDEDXTable (G4int atomicNumberIon, const G4Material *)
void PrintDEDXTable (const G4ParticleDefinition *, const G4Material *, G4double, G4double, G4int, G4bool logScaleEnergy=true)
G4double GetLowerEnergyEdge (const G4ParticleDefinition *, const G4Material *)
G4double GetUpperEnergyEdge (const G4ParticleDefinition *, const G4Material *)
void ClearCache ()
G4String GetName ()
Private Types
typedef std::pair< G4int,
const G4Material * > G4IonKey
typedef std::map< G4IonKey,
G4PhysicsVector * > DEDXTable
typedef std::map< G4IonKey,
G4PhysicsVector * > DEDXTableBraggRule
typedef std::pair< const
G4ParticleDefinition *, const
G4Material * > G4CacheKey
typedef struct
G4IonDEDXHandler::CacheEntry G4CacheEntry
typedef std::list< G4CacheEntry > CacheEntryList
typedef std::map< G4CacheKey,
void * > CacheIterPointerMap
Private Member Functions
G4IonDEDXHandler & operator= (const G4IonDEDXHandler &r)
G4IonDEDXHandler (const G4IonDEDXHandler &)
G4CacheValue UpdateCacheValue (const G4ParticleDefinition *, const G4Material *)
G4CacheValue GetCacheValue (const G4ParticleDefinition *, const G4Material *)
Private Attributes
G4VIonDEDXTable * table
G4VIonDEDXScalingAlgorithm * algorithm
G4String tableName
DEDXTable stoppingPowerTable
DEDXTableBraggRule stoppingPowerTableBragg
G4bool useSplines
CacheEntryList cacheEntries
CacheIterPointerMap cacheKeyPointers
G4int maxCacheEntries
Detailed Description
Definition at line 82 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 82 of file G4IonDEDXHandler.hh
Member Typedef Documentation
typedef std::list<G4CacheEntry> G4IonDEDXHandler::CacheEntryList private
Definition at line 190 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 190 of file G4IonDEDXHandler.hh
typedef std::map<G4CacheKey, void*> G4IonDEDXHandler::CacheIterPointerMap private
Definition at line 193 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 193 of file G4IonDEDXHandler.hh
typedef std::map<G4IonKey, G4PhysicsVector*> G4IonDEDXHandler::DEDXTable private
Definition at line 165 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 165 of file G4IonDEDXHandler.hh
typedef std::map<G4IonKey, G4PhysicsVector*> G4IonDEDXHandler::DEDXTableBraggRule private
Definition at line 169 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 169 of file G4IonDEDXHandler.hh
typedef struct G4IonDEDXHandler::CacheEntry G4IonDEDXHandler::G4CacheEntry private
typedef std::pair<const G4ParticleDefinition*, const G4Material*> G4IonDEDXHandler::G4CacheKey private
Definition at line 182 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 182 of file G4IonDEDXHandler.hh
typedef std::pair<G4int, const G4Material*> G4IonDEDXHandler::G4IonKey private
Definition at line 164 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 164 of file G4IonDEDXHandler.hh
Constructor & Destructor Documentation
G4IonDEDXHandler::G4IonDEDXHandler (G4VIonDEDXTable * tables, G4VIonDEDXScalingAlgorithm * algorithm, const G4String & name, G4int maxCacheSize = 5, G4bool splines = true)
Definition at line 68 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 68 of file G4IonDEDXHandler.cc
References algorithm, G4cerr, G4endl, maxCacheEntries, and table.
G4IonDEDXHandler::~G4IonDEDXHandler ()
Definition at line 102 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 102 of file G4IonDEDXHandler.cc
References algorithm, ClearCache(), stoppingPowerTable, stoppingPowerTableBragg, and table.
G4IonDEDXHandler::G4IonDEDXHandler (const G4IonDEDXHandler &) private
Member Function Documentation
G4bool G4IonDEDXHandler::BuildDEDXTable (const G4ParticleDefinition * particle, const G4Material * material)
Definition at line 196 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 196 of file G4IonDEDXHandler.cc
G4bool G4IonDEDXHandler::BuildDEDXTable (G4int atomicNumberIon, const G4Material * material)
Definition at line 210 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 210 of file G4IonDEDXHandler.cc
References algorithm, b, ClearCache(), G4cout, G4endl, GetName(), stoppingPowerTable, stoppingPowerTableBragg, table, and useSplines.
void G4IonDEDXHandler::ClearCache ()
Definition at line 425 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 425 of file G4IonDEDXHandler.cc
References cacheEntries, cacheKeyPointers, and second.
Referenced by BuildDEDXTable(), and ~G4IonDEDXHandler().
G4CacheValue G4IonDEDXHandler::GetCacheValue (const G4ParticleDefinition * particle, const G4Material * material) private
Definition at line 377 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 377 of file G4IonDEDXHandler.cc
References cacheEntries, cacheKeyPointers, G4IonDEDXHandler::CacheEntry::key, maxCacheEntries, UpdateCacheValue(), and G4IonDEDXHandler::CacheEntry::value.
Referenced by GetDEDX(), GetLowerEnergyEdge(), and GetUpperEnergyEdge().
G4double G4IonDEDXHandler::GetDEDX (const G4ParticleDefinition * particle, const G4Material * material, G4double kineticEnergy)
Definition at line 149 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 149 of file G4IonDEDXHandler.cc
References algorithm, b, cm, CacheValue::dedxVector, CacheValue::density, CacheValue::energyScaling, G4cout, G4endl, GetCacheValue(), GetName(), CacheValue::lowerEnergyEdge, and MeV.
Referenced by PrintDEDXTable().
G4double G4IonDEDXHandler::GetLowerEnergyEdge (const G4ParticleDefinition * particle, const G4Material * material)
Definition at line 517 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 517 of file G4IonDEDXHandler.cc
References CacheValue::energyScaling, GetCacheValue(), and CacheValue::lowerEnergyEdge.
Referenced by PrintDEDXTable().
G4String G4IonDEDXHandler::GetName (void)
Definition at line 549 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 549 of file G4IonDEDXHandler.cc
References tableName.
Referenced by BuildDEDXTable(), GetDEDX(), PrintDEDXTable(), and UpdateCacheValue().
G4double G4IonDEDXHandler::GetUpperEnergyEdge (const G4ParticleDefinition * particle, const G4Material * material)
Definition at line 533 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 533 of file G4IonDEDXHandler.cc
References CacheValue::energyScaling, GetCacheValue(), and CacheValue::upperEnergyEdge.
Referenced by PrintDEDXTable().
G4bool G4IonDEDXHandler::IsApplicable (const G4ParticleDefinition * particle, const G4Material * material)
Definition at line 123 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 123 of file G4IonDEDXHandler.cc
References algorithm, stoppingPowerTable, and table.
G4IonDEDXHandler& G4IonDEDXHandler::operator= (const G4IonDEDXHandler & r) private
void G4IonDEDXHandler::PrintDEDXTable (const G4ParticleDefinition * particle, const G4Material * material, G4double lowerBoundary, G4double upperBoundary, G4int nmbBins, G4bool logScaleEnergy = true)
Definition at line 444 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 444 of file G4IonDEDXHandler.cc
References cm, cm2, cm3, energy, Acts::UnitConstants::g, G4cout, G4endl, G4Exp(), GetDEDX(), GetLowerEnergyEdge(), GetName(), GetUpperEnergyEdge(), MeV, and right.
G4CacheValue G4IonDEDXHandler::UpdateCacheValue (const G4ParticleDefinition * particle, const G4Material * material) private
Definition at line 329 of file G4IonDEDXHandler.cc.
View newest version in sPHENIX GitHub at line 329 of file G4IonDEDXHandler.cc
References algorithm, CacheValue::dedxVector, CacheValue::density, CacheValue::energyScaling, G4cout, G4endl, GetName(), CacheValue::lowerEnergyEdge, second, stoppingPowerTable, and CacheValue::upperEnergyEdge.
Referenced by GetCacheValue().
Member Data Documentation
G4VIonDEDXScalingAlgorithm* G4IonDEDXHandler::algorithm private
Definition at line 158 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 158 of file G4IonDEDXHandler.hh
Referenced by BuildDEDXTable(), G4IonDEDXHandler(), GetDEDX(), IsApplicable(), UpdateCacheValue(), and ~G4IonDEDXHandler().
CacheEntryList G4IonDEDXHandler::cacheEntries private
Definition at line 191 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 191 of file G4IonDEDXHandler.hh
Referenced by ClearCache(), and GetCacheValue().
CacheIterPointerMap G4IonDEDXHandler::cacheKeyPointers private
Definition at line 194 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 194 of file G4IonDEDXHandler.hh
Referenced by ClearCache(), and GetCacheValue().
G4int G4IonDEDXHandler::maxCacheEntries private
Definition at line 197 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 197 of file G4IonDEDXHandler.hh
Referenced by G4IonDEDXHandler(), and GetCacheValue().
DEDXTable G4IonDEDXHandler::stoppingPowerTable private
Definition at line 166 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 166 of file G4IonDEDXHandler.hh
Referenced by BuildDEDXTable(), IsApplicable(), UpdateCacheValue(), and ~G4IonDEDXHandler().
DEDXTableBraggRule G4IonDEDXHandler::stoppingPowerTableBragg private
Definition at line 170 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 170 of file G4IonDEDXHandler.hh
Referenced by BuildDEDXTable(), and ~G4IonDEDXHandler().
G4VIonDEDXTable* G4IonDEDXHandler::table private
Definition at line 155 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 155 of file G4IonDEDXHandler.hh
Referenced by BuildDEDXTable(), G4IonDEDXHandler(), IsApplicable(), and ~G4IonDEDXHandler().
G4String G4IonDEDXHandler::tableName private
Definition at line 161 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 161 of file G4IonDEDXHandler.hh
Referenced by GetName().
G4bool G4IonDEDXHandler::useSplines private
Definition at line 174 of file G4IonDEDXHandler.hh.
View newest version in sPHENIX GitHub at line 174 of file G4IonDEDXHandler.hh
Referenced by BuildDEDXTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonDEDXHandler.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4IonDEDXHandler.cc