ECCE @ EIC Software: G4ParticleHPGamma Class Reference
G4ParticleHPGamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPGamma.hh>
Public Member Functions
G4ParticleHPGamma ()
~G4ParticleHPGamma ()
G4bool Init (std::istream &aDataFile)
void SetNext (G4ParticleHPLevel *aLevel)
G4DynamicParticleVector * GetDecayGammas ()
G4double GetLevelEnergy ()
G4double GetGammaEnergy ()
G4double GetWeight ()
Private Attributes
G4double levelEnergy
G4double gammaEnergy
G4double probability
G4ParticleHPLevel * next
Static Private Attributes
static G4ThreadLocal int instancecount = 0
Detailed Description
Definition at line 40 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPGamma.hh
Constructor & Destructor Documentation
G4ParticleHPGamma::G4ParticleHPGamma ()
Definition at line 37 of file G4ParticleHPGamma.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleHPGamma.cc
References gammaEnergy, instancecount, levelEnergy, next, and probability.
G4ParticleHPGamma::~G4ParticleHPGamma ()
Definition at line 46 of file G4ParticleHPGamma.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPGamma.cc
References instancecount.
Member Function Documentation
G4DynamicParticleVector* G4ParticleHPGamma::GetDecayGammas () inline
Definition at line 54 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPGamma.hh
References G4Gamma::Gamma(), gammaEnergy, G4ParticleHPLevel::GetDecayGammas(), next, G4DynamicParticle::SetDefinition(), and G4DynamicParticle::SetKineticEnergy().
Referenced by G4ParticleHPLevel::GetDecayGammas().
G4double G4ParticleHPGamma::GetGammaEnergy () inline
Definition at line 77 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPGamma.hh
References gammaEnergy.
Referenced by G4ParticleHPLevel::GetGammaEnergy(), and G4ParticleHPDeExGammas::Init().
G4double G4ParticleHPGamma::GetLevelEnergy () inline
Definition at line 72 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPGamma.hh
References levelEnergy.
Referenced by G4ParticleHPDeExGammas::Init(), and G4ParticleHPLevel::SetGamma().
G4double G4ParticleHPGamma::GetWeight () inline
Definition at line 82 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPGamma.hh
References probability.
Referenced by G4ParticleHPLevel::GetDecayGammas().
G4bool G4ParticleHPGamma::Init (std::istream & aDataFile)
Definition at line 48 of file G4ParticleHPGamma.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPGamma.cc
References gammaEnergy, keV, levelEnergy, and probability.
Referenced by G4ParticleHPDeExGammas::Init().
void G4ParticleHPGamma::SetNext (G4ParticleHPLevel * aLevel) inline
Definition at line 49 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPGamma.hh
References next.
Referenced by G4ParticleHPDeExGammas::Init().
Member Data Documentation
G4double G4ParticleHPGamma::gammaEnergy private
Definition at line 90 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleHPGamma.hh
Referenced by G4ParticleHPGamma(), GetDecayGammas(), GetGammaEnergy(), and Init().
G4ThreadLocal int G4ParticleHPGamma::instancecount = 0 static private
Definition at line 94 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPGamma.hh
Referenced by G4ParticleHPGamma(), and ~G4ParticleHPGamma().
G4double G4ParticleHPGamma::levelEnergy private
Definition at line 89 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPGamma.hh
Referenced by G4ParticleHPGamma(), GetLevelEnergy(), and Init().
G4ParticleHPLevel* G4ParticleHPGamma::next private
Definition at line 93 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPGamma.hh
Referenced by G4ParticleHPGamma(), GetDecayGammas(), and SetNext().
G4double G4ParticleHPGamma::probability private
Definition at line 91 of file G4ParticleHPGamma.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPGamma.hh
Referenced by G4ParticleHPGamma(), GetWeight(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPGamma.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPGamma.cc