ECCE @ EIC Software: G4PolarizedPEEffectCrossSection Class Reference
G4PolarizedPEEffectCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedPEEffectCrossSection.hh>
Public Member Functions
G4PolarizedPEEffectCrossSection ()
virtual ~G4PolarizedPEEffectCrossSection ()
virtual void Initialize (G4double aGammaE, G4double aLept0E, G4double sintheta, const G4StokesVector &beamPol, const G4StokesVector &, G4int flag=0) override
G4double XSection (const G4StokesVector &pol2, const G4StokesVector &pol3) override
G4StokesVector GetPol2 () override
G4StokesVector GetPol3 () override
Public Member Functions inherited from G4VPolarizedCrossSection
G4VPolarizedCrossSection ()
virtual ~G4VPolarizedCrossSection ()
virtual G4double TotalXSection (G4double xmin, G4double xmax, G4double y, const G4StokesVector &pol0, const G4StokesVector &pol1)
G4double GetYmin ()
virtual G4double GetXmin (G4double y)
virtual G4double GetXmax (G4double y)
void SetMaterial (G4double A, G4double Z, G4double coul)
Private Attributes
G4StokesVector theFinalElectronPolarization
Additional Inherited Members
Protected Member Functions inherited from G4VPolarizedCrossSection
void SetXmin (G4double xmin)
void SetXmax (G4double xmax)
void SetYmin (G4double ymin)
Protected Attributes inherited from G4VPolarizedCrossSection
G4double fXmin
G4double fXmax
G4double fYmin
G4double theA
G4double theZ
G4double fCoul
Detailed Description
Definition at line 49 of file G4PolarizedPEEffectCrossSection.hh.
View newest version in sPHENIX GitHub at line 49 of file G4PolarizedPEEffectCrossSection.hh
Constructor & Destructor Documentation
G4PolarizedPEEffectCrossSection::G4PolarizedPEEffectCrossSection ()
Definition at line 47 of file G4PolarizedPEEffectCrossSection.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PolarizedPEEffectCrossSection.cc
G4PolarizedPEEffectCrossSection::~G4PolarizedPEEffectCrossSection () virtual
Definition at line 54 of file G4PolarizedPEEffectCrossSection.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PolarizedPEEffectCrossSection.cc
Member Function Documentation
G4StokesVector G4PolarizedPEEffectCrossSection::GetPol2 () override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 149 of file G4PolarizedPEEffectCrossSection.cc.
View newest version in sPHENIX GitHub at line 149 of file G4PolarizedPEEffectCrossSection.cc
Referenced by G4PolarizedPEEffectModel::SampleSecondaries().
G4StokesVector G4PolarizedPEEffectCrossSection::GetPol3 () override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 156 of file G4PolarizedPEEffectCrossSection.cc.
View newest version in sPHENIX GitHub at line 156 of file G4PolarizedPEEffectCrossSection.cc
void G4PolarizedPEEffectCrossSection::Initialize (G4double aGammaE, G4double aLept0E, G4double sintheta, const G4StokesVector & beamPol, const G4StokesVector & , G4int flag = 0) override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 58 of file G4PolarizedPEEffectCrossSection.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PolarizedPEEffectCrossSection.cc
References source.hepunit::electron_mass_c2, and CLHEP::Hep3Vector::z().
Referenced by G4PolarizedPEEffectModel::SampleSecondaries().
G4double G4PolarizedPEEffectCrossSection::XSection (const G4StokesVector & pol2, const G4StokesVector & pol3) override virtual
Implements G4VPolarizedCrossSection.
Definition at line 140 of file G4PolarizedPEEffectCrossSection.cc.
View newest version in sPHENIX GitHub at line 140 of file G4PolarizedPEEffectCrossSection.cc
Member Data Documentation
G4StokesVector G4PolarizedPEEffectCrossSection::theFinalElectronPolarization private
Definition at line 68 of file G4PolarizedPEEffectCrossSection.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PolarizedPEEffectCrossSection.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedPEEffectCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedPEEffectCrossSection.cc