ECCE @ EIC Software: G4WentzelVIRelXSection Class Reference
G4WentzelVIRelXSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WentzelVIRelXSection.hh>
Public Member Functions
G4WentzelVIRelXSection ()
virtual ~G4WentzelVIRelXSection ()
virtual G4double SetupKinematic (G4double kinEnergy, const G4Material *mat)
Public Member Functions inherited from G4WentzelOKandVIxSection
G4WentzelOKandVIxSection (G4bool comb=true)
virtual ~G4WentzelOKandVIxSection ()
void Initialise (const G4ParticleDefinition *, G4double CosThetaLim)
void SetupParticle (const G4ParticleDefinition *)
G4double SetupKinematic (G4double kinEnergy, const G4Material *mat)
G4double SetupTarget (G4int Z, G4double cut)
G4double ComputeTransportCrossSectionPerAtom (G4double CosThetaMax)
G4ThreeVector & SampleSingleScattering (G4double CosThetaMin, G4double CosThetaMax, G4double elecRatio)
G4double ComputeSecondTransportMoment (G4double CosThetaMax)
G4double ComputeNuclearCrossSection (G4double CosThetaMin, G4double CosThetaMax)
G4double ComputeElectronCrossSection (G4double CosThetaMin, G4double CosThetaMax)
void SetTargetMass (G4double value)
G4double GetMomentumSquare () const
G4double GetCosThetaNuc () const
G4double GetCosThetaElec () const
Private Member Functions
G4WentzelVIRelXSection & operator= (const G4WentzelVIRelXSection &right)=delete
G4WentzelVIRelXSection (const G4WentzelVIRelXSection &)=delete
Additional Inherited Members
Protected Member Functions inherited from G4WentzelOKandVIxSection
void ComputeMaxElectronScattering (G4double cut)
void InitialiseA ()
G4double FlatFormfactor (G4double x)
Protected Attributes inherited from G4WentzelOKandVIxSection
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theElectron
const G4ParticleDefinition * thePositron
const G4Material * currentMaterial
G4NistManager * fNistManager
G4Pow * fG4pow
G4ScreeningMottCrossSection * fMottXSection
G4ThreeVector temp
G4double numlimit
G4int nwarnings
G4int nwarnlimit
G4NuclearFormfactorType fNucFormfactor
G4bool isCombined
G4double coeff
G4double cosTetMaxElec
G4double cosTetMaxNuc
G4double cosThetaMax
G4double alpha2
const G4ParticleDefinition * particle
G4double chargeSquare
G4double charge3
G4double spin
G4double mass
G4double tkin
G4double mom2
G4double momCM2
G4double invbeta2
G4double kinFactor
G4double etag
G4double ecut
G4double lowEnergyLimit
G4int targetZ
G4double targetMass
G4double screenZ
G4double formfactA
G4double factorA2
G4double factB
G4double factB1
G4double factD
G4double fMottFactor
G4double gam0pcmp
G4double pcmp2
Static Protected Attributes inherited from G4WentzelOKandVIxSection
static G4double ScreenRSquareElec [100] = {0.0}
static G4double ScreenRSquare [100] = {0.0}
static G4double FormFactor [100] = {0.0}
Detailed Description
Definition at line 63 of file G4WentzelVIRelXSection.hh.
View newest version in sPHENIX GitHub at line 63 of file G4WentzelVIRelXSection.hh
Constructor & Destructor Documentation
G4WentzelVIRelXSection::G4WentzelVIRelXSection () explicit
Definition at line 52 of file G4WentzelVIRelXSection.cc.
View newest version in sPHENIX GitHub at line 52 of file G4WentzelVIRelXSection.cc
G4WentzelVIRelXSection::~G4WentzelVIRelXSection () virtual
Definition at line 57 of file G4WentzelVIRelXSection.cc.
View newest version in sPHENIX GitHub at line 57 of file G4WentzelVIRelXSection.cc
G4WentzelVIRelXSection::G4WentzelVIRelXSection (const G4WentzelVIRelXSection &) private delete
Member Function Documentation
G4WentzelVIRelXSection& G4WentzelVIRelXSection::operator= (const G4WentzelVIRelXSection & right) private delete
G4double G4WentzelVIRelXSection::SetupKinematic (G4double kinEnergy, const G4Material * mat) virtual
Definition at line 62 of file G4WentzelVIRelXSection.cc.
View newest version in sPHENIX GitHub at line 62 of file G4WentzelVIRelXSection.cc
References G4WentzelOKandVIxSection::cosTetMaxNuc, G4WentzelOKandVIxSection::cosThetaMax, G4WentzelOKandVIxSection::currentMaterial, G4WentzelOKandVIxSection::factB, G4WentzelOKandVIxSection::factD, G4WentzelOKandVIxSection::factorA2, G4IonisParamMat::GetInvA23(), G4Material::GetIonisation(), G4WentzelOKandVIxSection::invbeta2, G4WentzelOKandVIxSection::isCombined, G4WentzelOKandVIxSection::mass, mat, max, G4WentzelOKandVIxSection::mom2, G4WentzelOKandVIxSection::spin, G4WentzelOKandVIxSection::targetMass, and G4WentzelOKandVIxSection::tkin.
Referenced by G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), and G4hCoulombScatteringModel::SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WentzelVIRelXSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4WentzelVIRelXSection.cc