ECCE @ EIC Software: G4EmProcessOptions Class Reference
G4EmProcessOptions Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmProcessOptions.hh>
Public Member Functions
G4EmProcessOptions ()
~G4EmProcessOptions ()
void SetLossFluctuations (G4bool val)
void SetBuildCSDARange (G4bool val)
void SetLPMFlag (G4bool val)
void SetSplineFlag (G4bool val)
void SetUseCutAsFinalRange (G4bool val)
void SetApplyCuts (G4bool val)
void SetFluo (G4bool val)
void SetAuger (G4bool val)
void SetPIXE (G4bool val)
void SetDeexcitationIgnoreCuts (G4bool val)
void SetMscLateralDisplacement (G4bool val)
void SetMscMuHadLateralDisplacement (G4bool val)
void SetDisplacementBeyondSafety (G4bool val)
void SetMinSubRange (G4double val)
void SetMinEnergy (G4double val)
void SetMaxEnergy (G4double val)
void SetMaxEnergyForMuons (G4double val)
void SetMaxEnergyForCSDARange (G4double val)
void SetLinearLossLimit (G4double val)
void SetBremsstrahlungTh (G4double val)
void SetLambdaFactor (G4double val)
void SetFactorForAngleLimit (G4double val)
void SetPolarAngleLimit (G4double val)
void SetMscRangeFactor (G4double val)
void SetMscGeomFactor (G4double val)
void SetSkin (G4double val)
void SetDEDXBinning (G4int val)
void SetDEDXBinningForCSDARange (G4int val)
void SetLambdaBinning (G4int val)
void SetVerbose (G4int val)
void SetWorkerVerbose (G4int val)
void SetMscStepLimitation (G4MscStepLimitType val)
void SetSubCutoff (G4bool val, const G4String &r="")
void SetIntegral (G4bool val)
void SetStepFunction (G4double v1, G4double v2)
void SetDeexcitationActiveRegion (const G4String &rname="", G4bool valDeexcitation=true, G4bool valAuger=true, G4bool valPIXE=true)
void SetPIXECrossSectionModel (const G4String &val)
void SetPIXEElectronCrossSectionModel (const G4String &val)
void SetProcessBiasingFactor (const G4String &name, G4double val, G4bool flag=true)
void ActivateForcedInteraction (const G4String &name, G4double length=0.0, const G4String &region="", G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &name, const G4String &region, G4double factor, G4double energyLimit)
void ActivateSecondaryBiasingForGamma (const G4String &name, const G4String &region, G4double factor, G4double energyLimit)
Private Member Functions
G4EmProcessOptions & operator= (const G4EmProcessOptions &right)=delete
G4EmProcessOptions (const G4EmProcessOptions &)=delete
Private Attributes
G4EmParameters * theParameters
Detailed Description
Definition at line 62 of file G4EmProcessOptions.hh.
View newest version in sPHENIX GitHub at line 62 of file G4EmProcessOptions.hh
Constructor & Destructor Documentation
G4EmProcessOptions::G4EmProcessOptions ()
Definition at line 66 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 66 of file G4EmProcessOptions.cc
References G4cout, G4endl, G4EmParameters::Instance(), and theParameters.
G4EmProcessOptions::~G4EmProcessOptions ()
Definition at line 78 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 78 of file G4EmProcessOptions.cc
G4EmProcessOptions::G4EmProcessOptions (const G4EmProcessOptions &) private delete
Member Function Documentation
void G4EmProcessOptions::ActivateForcedInteraction (const G4String & name, G4double length = 0.0, const G4String & region = "", G4bool flag = true)
Definition at line 362 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 362 of file G4EmProcessOptions.cc
References G4EmParameters::ActivateForcedInteraction(), and theParameters.
void G4EmProcessOptions::ActivateSecondaryBiasing (const G4String & name, const G4String & region, G4double factor, G4double energyLimit)
Definition at line 373 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 373 of file G4EmProcessOptions.cc
References G4EmParameters::ActivateSecondaryBiasing(), and theParameters.
void G4EmProcessOptions::ActivateSecondaryBiasingForGamma (const G4String & name, const G4String & region, G4double factor, G4double energyLimit)
Definition at line 384 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 384 of file G4EmProcessOptions.cc
References G4EmParameters::ActivateSecondaryBiasing(), and theParameters.
G4EmProcessOptions& G4EmProcessOptions::operator= (const G4EmProcessOptions & right) private delete
void G4EmProcessOptions::SetApplyCuts (G4bool val)
Definition at line 118 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 118 of file G4EmProcessOptions.cc
References G4EmParameters::SetApplyCuts(), and theParameters.
void G4EmProcessOptions::SetAuger (G4bool val)
Definition at line 132 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 132 of file G4EmProcessOptions.cc
References G4EmParameters::SetAuger(), and theParameters.
Referenced by XrayFluoPhysicsList::ConstructProcess().
void G4EmProcessOptions::SetBremsstrahlungTh (G4double val)
Definition at line 216 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 216 of file G4EmProcessOptions.cc
References G4EmParameters::SetBremsstrahlungTh(), and theParameters.
void G4EmProcessOptions::SetBuildCSDARange (G4bool val)
Definition at line 90 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 90 of file G4EmProcessOptions.cc
References G4EmParameters::SetBuildCSDARange(), and theParameters.
Referenced by PhysicsList::ConstructProcess(), and XrayFluoPhysicsList::ConstructProcess().
void G4EmProcessOptions::SetDEDXBinning (G4int val)
Definition at line 265 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 265 of file G4EmProcessOptions.cc
References G4EmParameters::SetNumberOfBins(), and theParameters.
Referenced by PhysListEmStandardNR::ConstructProcess().
void G4EmProcessOptions::SetDEDXBinningForCSDARange (G4int val)
Definition at line 272 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 272 of file G4EmProcessOptions.cc
Referenced by PhysicsList::ConstructProcess(), and XrayFluoPhysicsList::ConstructProcess().
void G4EmProcessOptions::SetDeexcitationActiveRegion (const G4String & rname = "", G4bool valDeexcitation = true, G4bool valAuger = true, G4bool valPIXE = true)
Definition at line 327 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 327 of file G4EmProcessOptions.cc
References G4EmParameters::SetDeexActiveRegion(), and theParameters.
void G4EmProcessOptions::SetDeexcitationIgnoreCuts (G4bool val)
Definition at line 146 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 146 of file G4EmProcessOptions.cc
References G4EmParameters::SetDeexcitationIgnoreCut(), and theParameters.
void G4EmProcessOptions::SetDisplacementBeyondSafety (G4bool val)
Definition at line 167 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 167 of file G4EmProcessOptions.cc
References G4EmParameters::SetLatDisplacementBeyondSafety(), and theParameters.
void G4EmProcessOptions::SetFactorForAngleLimit (G4double val)
Definition at line 230 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 230 of file G4EmProcessOptions.cc
References G4EmParameters::SetFactorForAngleLimit(), and theParameters.
void G4EmProcessOptions::SetFluo (G4bool val)
Definition at line 125 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 125 of file G4EmProcessOptions.cc
References G4EmParameters::SetFluo(), and theParameters.
Referenced by XrayFluoPhysicsList::ConstructProcess().
void G4EmProcessOptions::SetIntegral (G4bool val)
Definition at line 312 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 312 of file G4EmProcessOptions.cc
References G4EmParameters::SetIntegral(), and theParameters.
void G4EmProcessOptions::SetLambdaBinning (G4int val)
Definition at line 277 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 277 of file G4EmProcessOptions.cc
References G4EmParameters::SetNumberOfBins(), and theParameters.
Referenced by PhysListEmStandardNR::ConstructProcess().
void G4EmProcessOptions::SetLambdaFactor (G4double val)
Definition at line 223 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 223 of file G4EmProcessOptions.cc
References G4EmParameters::SetLambdaFactor(), and theParameters.
void G4EmProcessOptions::SetLinearLossLimit (G4double val)
Definition at line 209 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 209 of file G4EmProcessOptions.cc
References G4EmParameters::SetLinearLossLimit(), and theParameters.
void G4EmProcessOptions::SetLossFluctuations (G4bool val)
Definition at line 83 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 83 of file G4EmProcessOptions.cc
References G4EmParameters::SetLossFluctuations(), and theParameters.
void G4EmProcessOptions::SetLPMFlag (G4bool val)
Definition at line 97 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 97 of file G4EmProcessOptions.cc
References G4EmParameters::SetLPM(), and theParameters.
void G4EmProcessOptions::SetMaxEnergy (G4double val)
Definition at line 188 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 188 of file G4EmProcessOptions.cc
References G4EmParameters::SetMaxEnergy(), and theParameters.
Referenced by PhysListEmStandardNR::ConstructProcess().
void G4EmProcessOptions::SetMaxEnergyForCSDARange (G4double val)
Definition at line 202 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 202 of file G4EmProcessOptions.cc
References G4EmParameters::SetMaxEnergyForCSDARange(), and theParameters.
Referenced by PhysicsList::ConstructProcess().
void G4EmProcessOptions::SetMaxEnergyForMuons (G4double val)
Definition at line 195 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 195 of file G4EmProcessOptions.cc
References G4EmParameters::SetMaxEnergy(), and theParameters.
void G4EmProcessOptions::SetMinEnergy (G4double val)
Definition at line 181 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 181 of file G4EmProcessOptions.cc
References G4EmParameters::SetMinEnergy(), and theParameters.
Referenced by PhysListEmStandardNR::ConstructProcess().
void G4EmProcessOptions::SetMinSubRange (G4double val)
Definition at line 174 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 174 of file G4EmProcessOptions.cc
References G4EmParameters::SetMinSubRange(), and theParameters.
void G4EmProcessOptions::SetMscGeomFactor (G4double val)
Definition at line 251 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 251 of file G4EmProcessOptions.cc
References G4EmParameters::SetMscGeomFactor(), and theParameters.
void G4EmProcessOptions::SetMscLateralDisplacement (G4bool val)
Definition at line 153 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 153 of file G4EmProcessOptions.cc
References G4EmParameters::SetLateralDisplacement(), and theParameters.
void G4EmProcessOptions::SetMscMuHadLateralDisplacement (G4bool val)
Definition at line 160 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 160 of file G4EmProcessOptions.cc
References G4EmParameters::SetMuHadLateralDisplacement(), and theParameters.
void G4EmProcessOptions::SetMscRangeFactor (G4double val)
Definition at line 244 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 244 of file G4EmProcessOptions.cc
References G4EmParameters::SetMscRangeFactor(), and theParameters.
void G4EmProcessOptions::SetMscStepLimitation (G4MscStepLimitType val)
Definition at line 298 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 298 of file G4EmProcessOptions.cc
References G4EmParameters::SetMscStepLimitType(), and theParameters.
void G4EmProcessOptions::SetPIXE (G4bool val)
Definition at line 139 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 139 of file G4EmProcessOptions.cc
References G4EmParameters::SetPixe(), and theParameters.
Referenced by XrayFluoPhysicsList::ConstructProcess().
void G4EmProcessOptions::SetPIXECrossSectionModel (const G4String & val)
Definition at line 337 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 337 of file G4EmProcessOptions.cc
References G4EmParameters::SetPIXECrossSectionModel(), and theParameters.
void G4EmProcessOptions::SetPIXEElectronCrossSectionModel (const G4String & val)
Definition at line 345 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 345 of file G4EmProcessOptions.cc
References G4EmParameters::SetPIXEElectronCrossSectionModel(), and theParameters.
void G4EmProcessOptions::SetPolarAngleLimit (G4double val)
Definition at line 237 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 237 of file G4EmProcessOptions.cc
References G4EmParameters::SetMscThetaLimit(), and theParameters.
Referenced by PhysListEmStandardNR::ConstructProcess().
void G4EmProcessOptions::SetProcessBiasingFactor (const G4String & name, G4double val, G4bool flag = true)
Definition at line 353 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 353 of file G4EmProcessOptions.cc
References G4EmParameters::SetProcessBiasingFactor(), and theParameters.
void G4EmProcessOptions::SetSkin (G4double val)
Definition at line 258 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 258 of file G4EmProcessOptions.cc
References G4EmParameters::SetMscSkin(), and theParameters.
void G4EmProcessOptions::SetSplineFlag (G4bool val)
Definition at line 104 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 104 of file G4EmProcessOptions.cc
References G4EmParameters::SetSpline(), and theParameters.
void G4EmProcessOptions::SetStepFunction (G4double v1, G4double v2)
Definition at line 319 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 319 of file G4EmProcessOptions.cc
References G4EmParameters::SetStepFunction(), and theParameters.
void G4EmProcessOptions::SetSubCutoff (G4bool val, const G4String & r = "")
Definition at line 305 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 305 of file G4EmProcessOptions.cc
References G4EmParameters::SetSubCutoff(), and theParameters.
void G4EmProcessOptions::SetUseCutAsFinalRange (G4bool val)
Definition at line 111 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 111 of file G4EmProcessOptions.cc
References G4EmParameters::SetUseCutAsFinalRange(), and theParameters.
void G4EmProcessOptions::SetVerbose (G4int val)
Definition at line 284 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 284 of file G4EmProcessOptions.cc
References G4EmParameters::SetVerbose(), and theParameters.
Referenced by PhysicsList::ConstructProcess().
void G4EmProcessOptions::SetWorkerVerbose (G4int val)
Definition at line 291 of file G4EmProcessOptions.cc.
View newest version in sPHENIX GitHub at line 291 of file G4EmProcessOptions.cc
References G4EmParameters::SetWorkerVerbose(), and theParameters.
Member Data Documentation
G4EmParameters* G4EmProcessOptions::theParameters private
Definition at line 169 of file G4EmProcessOptions.hh.
View newest version in sPHENIX GitHub at line 169 of file G4EmProcessOptions.hh
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), ActivateSecondaryBiasingForGamma(), G4EmProcessOptions(), SetApplyCuts(), SetAuger(), SetBremsstrahlungTh(), SetBuildCSDARange(), SetDEDXBinning(), SetDeexcitationActiveRegion(), SetDeexcitationIgnoreCuts(), SetDisplacementBeyondSafety(), SetFactorForAngleLimit(), SetFluo(), SetIntegral(), SetLambdaBinning(), SetLambdaFactor(), SetLinearLossLimit(), SetLossFluctuations(), SetLPMFlag(), SetMaxEnergy(), SetMaxEnergyForCSDARange(), SetMaxEnergyForMuons(), SetMinEnergy(), SetMinSubRange(), SetMscGeomFactor(), SetMscLateralDisplacement(), SetMscMuHadLateralDisplacement(), SetMscRangeFactor(), SetMscStepLimitation(), SetPIXE(), SetPIXECrossSectionModel(), SetPIXEElectronCrossSectionModel(), SetPolarAngleLimit(), SetProcessBiasingFactor(), SetSkin(), SetSplineFlag(), SetStepFunction(), SetSubCutoff(), SetUseCutAsFinalRange(), SetVerbose(), and SetWorkerVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmProcessOptions.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmProcessOptions.cc