ECCE @ EIC Software: G4INCL::OmegaNToPiPiNChannel Class Reference
G4INCL::OmegaNToPiPiNChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLOmegaNToPiPiNChannel.hh>
Public Member Functions
OmegaNToPiPiNChannel (Particle *, Particle *)
virtual ~OmegaNToPiPiNChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (OmegaNToPiPiNChannel)
Private Attributes
G4int ind2
Particle * particle1
Particle * particle2
Static Private Attributes
static const G4double angularSlope = 15.
Detailed Description
Definition at line 47 of file G4INCLOmegaNToPiPiNChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLOmegaNToPiPiNChannel.hh
Constructor & Destructor Documentation
G4INCL::OmegaNToPiPiNChannel::OmegaNToPiPiNChannel (Particle * p1, Particle * p2)
Definition at line 51 of file G4INCLOmegaNToPiPiNChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLOmegaNToPiPiNChannel.cc
G4INCL::OmegaNToPiPiNChannel::~OmegaNToPiPiNChannel () virtual
Definition at line 57 of file G4INCLOmegaNToPiPiNChannel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLOmegaNToPiPiNChannel.cc
Member Function Documentation
void G4INCL::OmegaNToPiPiNChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 61 of file G4INCLOmegaNToPiPiNChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLOmegaNToPiPiNChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), angularSlope, G4INCL::PhaseSpaceGenerator::generateBiased(), G4INCL::ParticleTable::getIsospin(), G4INCL::ParticleTable::getNucleonType(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), ind2, G4INCL::Particle::isNucleon(), G4InuclParticleNames::nucleon(), particle1, particle2, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::KinematicsUtils::totalEnergyInCM(), and zero.
G4INCL::OmegaNToPiPiNChannel::INCL_DECLARE_ALLOCATION_POOL (OmegaNToPiPiNChannel) private
Member Data Documentation
const G4double G4INCL::OmegaNToPiPiNChannel::angularSlope = 15. static private
Definition at line 58 of file G4INCLOmegaNToPiPiNChannel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4INCLOmegaNToPiPiNChannel.hh
Referenced by fillFinalState().
G4int G4INCL::OmegaNToPiPiNChannel::ind2 private
Definition at line 55 of file G4INCLOmegaNToPiPiNChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLOmegaNToPiPiNChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::OmegaNToPiPiNChannel::particle1 private
Definition at line 56 of file G4INCLOmegaNToPiPiNChannel.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLOmegaNToPiPiNChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::OmegaNToPiPiNChannel::particle2 private
Definition at line 56 of file G4INCLOmegaNToPiPiNChannel.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLOmegaNToPiPiNChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLOmegaNToPiPiNChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLOmegaNToPiPiNChannel.cc