ECCE @ EIC Software: G4ParameterisationPolyconeZ Class Reference
G4ParameterisationPolyconeZ Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPolycone.hh>
Public Member Functions
G4ParameterisationPolyconeZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *motherSolid, DivisionType divType)
~G4ParameterisationPolyconeZ ()
void CheckParametersValidity ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Polycone &pcone, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VParameterisationPolycone
G4VParameterisationPolycone (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationPolycone ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
G4double GetR (G4double z, G4double z1, G4double r1, G4double z2, G4double r2) const
G4double GetRmin (G4double z, G4int nsegment) const
G4double GetRmax (G4double z, G4int nsegment) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNSegment = 0
G4PolyconeHistorical * fOrigParamMother = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VDivisionParameterisation
G4String ftype
EAxis faxis
G4int fnDiv = 0
G4double fwidth = 0.0
G4double foffset = 0.0
DivisionType fDivisionType
G4VSolid * fmotherSolid = nullptr
G4bool fReflectedSolid = false
G4bool fDeleteSolid = false
G4int theVoluFirstCopyNo = 1
G4double kCarTolerance
G4double fhgap = 0.0
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 173 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ParameterisationPolycone.hh
Constructor & Destructor Documentation
G4ParameterisationPolyconeZ::G4ParameterisationPolyconeZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid * motherSolid, DivisionType divType)
Definition at line 352 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 352 of file G4ParameterisationPolycone.cc
References G4VDivisionParameterisation::CalculateNDiv(), CheckParametersValidity(), DivNDIV, DivWIDTH, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4PolyconeHistorical::Num_z_planes, G4VDivisionParameterisation::SetType(), G4VDivisionParameterisation::verbose, and G4PolyconeHistorical::Z_values.
G4ParameterisationPolyconeZ::~G4ParameterisationPolyconeZ ()
Definition at line 387 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 387 of file G4ParameterisationPolycone.cc
Member Function Documentation
void G4ParameterisationPolyconeZ::CheckParametersValidity () virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 436 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 436 of file G4ParameterisationPolycone.cc
References G4VDivisionParameterisation::CheckParametersValidity(), DivNDIV, DivNDIVandWIDTH, DivWIDTH, error, FatalException, G4VDivisionParameterisation::fDivisionType, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, fNSegment, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fReflectedSolid, G4VDivisionParameterisation::fwidth, G4endl, G4Exception(), G4VSolid::GetName(), message(), G4PolyconeHistorical::Num_z_planes, and G4PolyconeHistorical::Z_values.
Referenced by G4ParameterisationPolyconeZ().
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Polycone & pcone, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 595 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 595 of file G4ParameterisationPolycone.cc
References DivNDIV, DivNDIVandWIDTH, DivWIDTH, G4VSolid::DumpInfo(), G4VDivisionParameterisation::fDivisionType, fNSegment, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fReflectedSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, GetRmax(), GetRmin(), G4PolyconeHistorical::Num_z_planes, G4PolyconeHistorical::Opening_angle, G4Polycone::Reset(), G4PolyconeHistorical::Rmax, G4PolyconeHistorical::Rmin, G4Polycone::SetOriginalParameters(), G4PolyconeHistorical::Start_angle, G4VDivisionParameterisation::verbose, and G4PolyconeHistorical::Z_values.
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 201 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 201 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 203 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 203 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 205 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 205 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 207 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 207 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 209 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 209 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 211 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 211 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 213 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 213 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 215 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 215 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 217 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 217 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 219 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 219 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 221 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 221 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 223 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 223 of file G4ParameterisationPolycone.hh
void G4ParameterisationPolyconeZ::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 543 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 543 of file G4ParameterisationPolycone.cc
References G4VDivisionParameterisation::ChangeRotMatrix(), deg, DivNDIV, DivNDIVandWIDTH, DivWIDTH, G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fDivisionType, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fReflectedSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), G4VDivisionParameterisation::verbose, and G4PolyconeHistorical::Z_values.
G4double G4ParameterisationPolyconeZ::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 429 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 429 of file G4ParameterisationPolycone.cc
References kdfinder::abs(), fOrigParamMother, G4PolyconeHistorical::Num_z_planes, and G4PolyconeHistorical::Z_values.
G4double G4ParameterisationPolyconeZ::GetR (G4double z, G4double z1, G4double r1, G4double z2, G4double r2) const private
Definition at line 392 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 392 of file G4ParameterisationPolycone.cc
References z2.
Referenced by GetRmax(), and GetRmin().
G4double G4ParameterisationPolyconeZ::GetRmax (G4double z, G4int nsegment) const private
Definition at line 417 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 417 of file G4ParameterisationPolycone.cc
References fOrigParamMother, GetR(), G4PolyconeHistorical::Rmax, and G4PolyconeHistorical::Z_values.
Referenced by ComputeDimensions().
G4double G4ParameterisationPolyconeZ::GetRmin (G4double z, G4int nsegment) const private
Definition at line 405 of file G4ParameterisationPolycone.cc.
View newest version in sPHENIX GitHub at line 405 of file G4ParameterisationPolycone.cc
References fOrigParamMother, GetR(), G4PolyconeHistorical::Rmin, and G4PolyconeHistorical::Z_values.
Referenced by ComputeDimensions().
Member Data Documentation
G4int G4ParameterisationPolyconeZ::fNSegment = 0 private
Definition at line 227 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 227 of file G4ParameterisationPolycone.hh
Referenced by CheckParametersValidity(), and ComputeDimensions().
G4PolyconeHistorical* G4ParameterisationPolyconeZ::fOrigParamMother = nullptr private
Definition at line 228 of file G4ParameterisationPolycone.hh.
View newest version in sPHENIX GitHub at line 228 of file G4ParameterisationPolycone.hh
Referenced by CheckParametersValidity(), ComputeDimensions(), ComputeTransformation(), G4ParameterisationPolyconeZ(), GetMaxParameter(), GetRmax(), and GetRmin().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPolycone.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationPolycone.cc