ECCE @ EIC Software: G4ErrorPropagatorData Class Reference
G4ErrorPropagatorData Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4ErrorPropagatorData.hh>
Public Member Functions
G4ErrorMode GetMode () const
void SetMode (G4ErrorMode mode)
G4ErrorState GetState () const
void SetState (G4ErrorState sta)
G4ErrorStage GetStage () const
void SetStage (G4ErrorStage sta)
const G4ErrorTarget * GetTarget (G4bool mustExist=0) const
void SetTarget (const G4ErrorTarget *target)
Static Public Member Functions
static G4ErrorPropagatorData * GetErrorPropagatorData ()
static G4int verbose ()
static void SetVerbose (G4int ver)
Private Member Functions
G4ErrorPropagatorData ()
~G4ErrorPropagatorData ()
Private Attributes
G4ErrorMode theMode
G4ErrorState theState
G4ErrorStage theStage
G4ErrorTarget * theTarget
Static Private Attributes
static G4ThreadLocal
G4ErrorPropagatorData * fpInstance = 0
static G4ThreadLocal G4int theVerbosity = 0
Detailed Description
Definition at line 61 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ErrorPropagatorData.hh
Constructor & Destructor Documentation
G4ErrorPropagatorData::G4ErrorPropagatorData () private
Definition at line 42 of file G4ErrorPropagatorData.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ErrorPropagatorData.cc
Referenced by GetErrorPropagatorData().
G4ErrorPropagatorData::~G4ErrorPropagatorData () private
Definition at line 48 of file G4ErrorPropagatorData.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ErrorPropagatorData.cc
References fpInstance.
Member Function Documentation
G4ErrorPropagatorData * G4ErrorPropagatorData::GetErrorPropagatorData () static
Definition at line 53 of file G4ErrorPropagatorData.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ErrorPropagatorData.cc
References fpInstance, and G4ErrorPropagatorData().
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorPropagator::CheckIfLastStep(), G4ErrorPropagationNavigator::ComputeStep(), G4ErrorMag_UsualEqRhs::EvaluateRhsGivenB(), G4ErrorPropagatorManager::EventTermination(), G4ErrorPropagatorManager::G4ErrorPropagatorManager(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4ErrorPropagator::GetFinalTrajState(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), G4ErrorPropagatorManager::InitGeant4e(), Initialize(), G4ErrorPropagatorManager::InitTrackPropagation(), G4ErrorPropagator::MakeOneStep(), G4ErrorPropagatorManager::PrintG4ErrorState(), G4ErrorPropagator::Propagate(), G4ErrorPropagatorManager::Propagate(), G4ErrorFreeTrajState::PropagateError(), G4ErrorPropagator::PropagateOneStep(), G4ErrorPropagatorManager::PropagateOneStep(), G4ErrorPropagatorManager::RunTermination(), and G4ErrorPropagationNavigator::TargetSafetyFromPoint().
G4ErrorMode G4ErrorPropagatorData::GetMode () const
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4ErrorPropagator::Propagate(), and G4ErrorPropagator::PropagateOneStep().
G4ErrorStage G4ErrorPropagatorData::GetStage () const
G4ErrorState G4ErrorPropagatorData::GetState () const
Referenced by G4ErrorPropagator::CheckIfLastStep(), G4ErrorPropagator::GetFinalTrajState(), G4ErrorPropagator::MakeOneStep(), G4ErrorPropagator::Propagate(), and G4ErrorPropagator::PropagateOneStep().
const G4ErrorTarget* G4ErrorPropagatorData::GetTarget (G4bool mustExist = 0) const
Referenced by G4ErrorPropagationNavigator::ComputeStep(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), G4ErrorPropagator::MakeOneStep(), G4ErrorPropagator::PropagateOneStep(), and G4ErrorPropagationNavigator::TargetSafetyFromPoint().
void G4ErrorPropagatorData::SetMode (G4ErrorMode mode)
Referenced by G4ErrorPropagator::Propagate(), G4ErrorPropagatorManager::Propagate(), and G4ErrorPropagatorManager::PropagateOneStep().
void G4ErrorPropagatorData::SetStage (G4ErrorStage sta)
void G4ErrorPropagatorData::SetState (G4ErrorState sta)
Referenced by G4ErrorPropagationNavigator::ComputeStep(), G4ErrorPropagatorManager::EventTermination(), G4ErrorPropagatorManager::G4ErrorPropagatorManager(), G4ErrorPropagatorManager::InitGeant4e(), G4ErrorPropagatorManager::InitTrackPropagation(), G4ErrorPropagator::MakeOneStep(), and G4ErrorPropagatorManager::RunTermination().
void G4ErrorPropagatorData::SetTarget (const G4ErrorTarget * target)
Referenced by Initialize(), and G4ErrorPropagator::Propagate().
void G4ErrorPropagatorData::SetVerbose (G4int ver) static
Definition at line 67 of file G4ErrorPropagatorData.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ErrorPropagatorData.cc
References theVerbosity.
Referenced by G4ErrorPropagatorManager::G4ErrorPropagatorManager().
G4int G4ErrorPropagatorData::verbose () static
Definition at line 62 of file G4ErrorPropagatorData.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ErrorPropagatorData.cc
References theVerbosity.
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4ErrorPropagationNavigator::ComputeStep(), G4ErrorCylSurfaceTarget::G4ErrorCylSurfaceTarget(), G4ErrorPlaneSurfaceTarget::G4ErrorPlaneSurfaceTarget(), G4ErrorPropagator::G4ErrorPropagator(), G4ErrorTrajState::G4ErrorTrajState(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4ErrorCylSurfaceTarget::GetDistanceFromPoint(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4ErrorTrackLengthTarget::GetMeanFreePath(), G4ErrorPropagatorManager::InitFieldForBackwards(), G4ErrorPropagatorManager::InitGeant4e(), G4ErrorPlaneSurfaceTarget::Intersect(), G4ErrorCylSurfaceTarget::IntersectLocal(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4ErrorStepLengthLimitProcess::PostStepGetPhysicalInteractionLength(), G4ErrorMessenger::SetNewValue(), G4ErrorPropagatorManager::StartG4ErrorRunManagerHelper(), G4ErrorPropagatorManager::StartNavigator(), and G4ErrorGeomVolumeTarget::TargetReached().
Member Data Documentation
G4ThreadLocal G4ErrorPropagatorData * G4ErrorPropagatorData::fpInstance = 0 static private
Definition at line 94 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ErrorPropagatorData.hh
Referenced by GetErrorPropagatorData(), and ~G4ErrorPropagatorData().
G4ErrorMode G4ErrorPropagatorData::theMode private
Definition at line 96 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ErrorPropagatorData.hh
G4ErrorStage G4ErrorPropagatorData::theStage private
Definition at line 100 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ErrorPropagatorData.hh
G4ErrorState G4ErrorPropagatorData::theState private
Definition at line 98 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ErrorPropagatorData.hh
G4ErrorTarget* G4ErrorPropagatorData::theTarget private
Definition at line 102 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ErrorPropagatorData.hh
G4ThreadLocal G4int G4ErrorPropagatorData::theVerbosity = 0 static private
Definition at line 104 of file G4ErrorPropagatorData.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ErrorPropagatorData.hh
Referenced by SetVerbose(), and verbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4ErrorPropagatorData.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4ErrorPropagatorData.cc