ECCE @ EIC Software: G4VScatteringCollision Class Reference
G4VScatteringCollision Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VScatteringCollision.hh>
Public Member Functions
G4VScatteringCollision ()
void establish_G4MT_TLS_G4VScatteringCollision ()
virtual ~G4VScatteringCollision ()
G4bool operator== (const G4VScatteringCollision &right) const
G4bool operator!= (const G4VScatteringCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual G4String GetName () const =0
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const std::vector
< const G4ParticleDefinition * > & GetOutgoingParticles () const =0
Protected Member Functions inherited from G4VCollision
G4int GetNumberOfPartons (const G4ParticleDefinition *aP) const
virtual const G4CollisionVector * GetComponents () const
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const =0
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const =0
Private Member Functions
G4VScatteringCollision (const G4VScatteringCollision &)
G4VScatteringCollision & operator= (const G4VScatteringCollision &)
double BrWigInt0 (const double x, const double gamma, const double m0) const
G4double BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const
double BrWigInv (const double x, const double gamma, const double m0) const
double SampleResonanceMass (const double poleMass, const double width, const double minMass, const double maxMass) const
Private Attributes
G4VAngularDistribution * theAngularDistribution
Detailed Description
Definition at line 55 of file G4VScatteringCollision.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VScatteringCollision.hh
Constructor & Destructor Documentation
G4VScatteringCollision::G4VScatteringCollision ()
Definition at line 47 of file G4VScatteringCollision.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VScatteringCollision.cc
References theAngularDistribution.
G4VScatteringCollision::~G4VScatteringCollision () virtual
Definition at line 53 of file G4VScatteringCollision.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VScatteringCollision.cc
References theAngularDistribution.
G4VScatteringCollision::G4VScatteringCollision (const G4VScatteringCollision &) private
Member Function Documentation
double G4VScatteringCollision::BrWigInt0 (const double x, const double gamma, const double m0) const inline private
Definition at line 84 of file G4VScatteringCollision.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VScatteringCollision.hh
Referenced by BrWigInt1(), and SampleResonanceMass().
G4double G4VScatteringCollision::BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 87 of file G4VScatteringCollision.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VScatteringCollision.hh
References BrWigInt0(), and G4Log().
double G4VScatteringCollision::BrWigInv (const double x, const double gamma, const double m0) const inline private
Definition at line 90 of file G4VScatteringCollision.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VScatteringCollision.hh
Referenced by SampleResonanceMass().
void G4VScatteringCollision::establish_G4MT_TLS_G4VScatteringCollision ()
Definition at line 180 of file G4VScatteringCollision.cc.
View newest version in sPHENIX GitHub at line 180 of file G4VScatteringCollision.cc
References G4VCollision::establish_G4MT_TLS_G4VCollision(), and theAngularDistribution.
Referenced by G4ConcreteNNTwoBodyResonance::establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance().
G4KineticTrackVector * G4VScatteringCollision::FinalState (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 60 of file G4VScatteringCollision.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VScatteringCollision.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), G4VAngularDistribution::CosTheta(), G4cerr, G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), GetAngularDistribution(), G4KineticTrack::GetDefinition(), GetOutgoingParticles(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4KineticTrack::GetPosition(), CLHEP::HepLorentzRotation::inverse(), CLHEP::HepLorentzVector::m(), CLHEP::Hep3Vector::mag2(), G4Neutron::NeutronDefinition(), G4VAngularDistribution::Phi(), phi, G4PionPlus::PionPlus(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), S(), and SampleResonanceMass().
virtual const G4VAngularDistribution* G4VScatteringCollision::GetAngularDistribution () const inline virtual
Implements G4VCollision.
Definition at line 69 of file G4VScatteringCollision.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VScatteringCollision.hh
References theAngularDistribution.
Referenced by FinalState().
virtual const std::vector<const G4ParticleDefinition*>& G4VScatteringCollision::GetOutgoingParticles () const protected pure virtual
Implemented in G4ConcreteNNTwoBodyResonance.
Referenced by FinalState().
G4bool G4VScatteringCollision::operator!= (const G4VScatteringCollision & right) const
G4VScatteringCollision& G4VScatteringCollision::operator= (const G4VScatteringCollision &) private
G4bool G4VScatteringCollision::operator== (const G4VScatteringCollision & right) const
double G4VScatteringCollision::SampleResonanceMass (const double poleMass, const double width, const double minMass, const double maxMass) const private
Definition at line 156 of file G4VScatteringCollision.cc.
View newest version in sPHENIX GitHub at line 156 of file G4VScatteringCollision.cc
References BrWigInt0(), BrWigInv(), E, f, G4cerr, G4endl, G4UniformRand, G4ParticleDefinition::GetPDGMass(), GeV, max, min, and G4PionPlus::PionPlus().
Referenced by FinalState().
Member Data Documentation
G4VAngularDistribution* G4VScatteringCollision::theAngularDistribution private
Definition at line 99 of file G4VScatteringCollision.hh.
View newest version in sPHENIX GitHub at line 99 of file G4VScatteringCollision.hh
Referenced by establish_G4MT_TLS_G4VScatteringCollision(), G4VScatteringCollision(), GetAngularDistribution(), and ~G4VScatteringCollision().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VScatteringCollision.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4VScatteringCollision.cc