ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITNavigator1.cc File Reference
G4ITNavigator1.cc File Reference
#include <iomanip>
#include "G4ITNavigator1.hh"
#include "G4ios.hh"
#include "G4SystemOfUnits.hh"
#include "G4GeometryTolerance.hh"
#include "G4VPhysicalVolume.hh"
#include "G4VoxelSafety.hh"
Macros
#define G4DEBUG_NAVIGATION 1
#define G4NEW_SAFETY 1
Functions
std::ostream & operator<< (std::ostream &os, const G4ITNavigator1 &n)
Macro Definition Documentation
#define G4DEBUG_NAVIGATION 1
Definition at line 52 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ITNavigator1.cc
#define G4NEW_SAFETY 1
Definition at line 1710 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1710 of file G4ITNavigator1.cc
Function Documentation
std::ostream& operator<< (std::ostream & os, const G4ITNavigator1 & n)
Definition at line 2041 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 2041 of file G4ITNavigator1.cc
References G4ITNavigator1::fBlockedPhysicalVolume, G4ITNavigator1::fBlockedReplicaNo, G4ITNavigator1::fEntering, G4ITNavigator1::fExiting, G4ITNavigator1::fExitNormal, G4ITNavigator1::fHistory, G4ITNavigator1::fLastLocatedPointLocal, G4ITNavigator1::fLastStepWasZero, G4ITNavigator1::fPreviousSafety, G4ITNavigator1::fPreviousSftOrigin, G4ITNavigator1::fValidExitNormal, G4ITNavigator1::fVerbose, G4endl, G4VPhysicalVolume::GetName(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().