ECCE @ EIC Software: G4ITTrackingManager Class Reference
G4ITTrackingManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTrackingManager.hh>
Public Member Functions
G4ITTrackingManager ()
~G4ITTrackingManager ()
void StartTracking (G4Track *)
void AppendStep (G4Track *track, G4Step *step)
void EndTracking (G4Track *)
void EndTrackingWOKill (G4Track *)
void SetInteractivity (G4ITTrackingInteractivity *)
G4ITTrackingInteractivity * GetInteractivity ()
Protected Attributes
G4ITTrackingInteractivity * fpTrackingInteractivity
Detailed Description
Definition at line 59 of file G4ITTrackingManager.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ITTrackingManager.hh
Constructor & Destructor Documentation
G4ITTrackingManager::G4ITTrackingManager ()
Definition at line 44 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ITTrackingManager.cc
References fpTrackingInteractivity.
G4ITTrackingManager::~G4ITTrackingManager ()
Definition at line 54 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ITTrackingManager.cc
References fpTrackingInteractivity.
Member Function Documentation
void G4ITTrackingManager::AppendStep (G4Track * track, G4Step * step)
Definition at line 73 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ITTrackingManager.cc
References G4ITTrackingInteractivity::AppendStep(), and fpTrackingInteractivity.
void G4ITTrackingManager::EndTracking (G4Track * track)
Definition at line 89 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ITTrackingManager.cc
References G4ITTrackingInteractivity::EndTracking(), fpTrackingInteractivity, G4ITTrackingInteractivity::GetSteppingVerbose(), G4ITTrackHolder::Instance(), G4ITTrackHolder::PushToKill(), and G4VITSteppingVerbose::TrackingEnded().
Referenced by G4ITStepProcessor::ExtractILData().
void G4ITTrackingManager::EndTrackingWOKill (G4Track * track)
Definition at line 102 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ITTrackingManager.cc
References G4ITTrackingInteractivity::EndTracking(), fpTrackingInteractivity, G4ITTrackingInteractivity::GetSteppingVerbose(), and G4VITSteppingVerbose::TrackingEnded().
Referenced by G4Scheduler::EndTracking().
G4ITTrackingInteractivity* G4ITTrackingManager::GetInteractivity () inline
Definition at line 76 of file G4ITTrackingManager.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ITTrackingManager.hh
References fpTrackingInteractivity.
Referenced by G4ITStepProcessor::Initialize().
void G4ITTrackingManager::SetInteractivity (G4ITTrackingInteractivity * iteractivity)
Definition at line 79 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ITTrackingManager.cc
References fpTrackingInteractivity.
Referenced by G4Scheduler::Initialize(), and G4Scheduler::SetInteractivity().
void G4ITTrackingManager::StartTracking (G4Track * track)
Definition at line 59 of file G4ITTrackingManager.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ITTrackingManager.cc
References fpTrackingInteractivity, G4Track::GetDefinition(), G4ParticleDefinition::GetProcessManager(), G4ITTrackingInteractivity::GetSteppingVerbose(), G4ITTrackingInteractivity::StartTracking(), G4ProcessManager::StartTracking(), and G4VITSteppingVerbose::TrackingStarted().
Referenced by G4ITStepProcessor::InitDefineStep().
Member Data Documentation
G4ITTrackingInteractivity* G4ITTrackingManager::fpTrackingInteractivity protected
Definition at line 62 of file G4ITTrackingManager.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ITTrackingManager.hh
Referenced by AppendStep(), EndTracking(), EndTrackingWOKill(), G4ITTrackingManager(), GetInteractivity(), SetInteractivity(), StartTracking(), and ~G4ITTrackingManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTrackingManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITTrackingManager.cc