ECCE @ EIC Software: GB01BOptrChangeCrossSection Class Reference
GB01BOptrChangeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB01/include/GB01BOptrChangeCrossSection.hh>
Public Member Functions
GB01BOptrChangeCrossSection (G4String particleToBias, G4String name="ChangeXS")
virtual ~GB01BOptrChangeCrossSection ()
virtual void StartRun ()
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartTracking (const G4Track *)
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
Private Attributes
std::map< const
G4BiasingProcessInterface
*, G4BOptnChangeCrossSection * > fChangeCrossSectionOperations
G4bool fSetup
const G4ParticleDefinition * fParticleToBias
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 54 of file GB01BOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 54 of file GB01BOptrChangeCrossSection.hh
Constructor & Destructor Documentation
GB01BOptrChangeCrossSection::GB01BOptrChangeCrossSection (G4String particleToBias, G4String name = "ChangeXS")
Definition at line 43 of file GB01BOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 43 of file GB01BOptrChangeCrossSection.cc
References G4ParticleTable::FindParticle(), fParticleToBias, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), and JustWarning.
GB01BOptrChangeCrossSection::~GB01BOptrChangeCrossSection () virtual
Definition at line 63 of file GB01BOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 63 of file GB01BOptrChangeCrossSection.cc
References fChangeCrossSectionOperations, and it.
Member Function Documentation
void GB01BOptrChangeCrossSection::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 193 of file GB01BOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 193 of file GB01BOptrChangeCrossSection.cc
References fChangeCrossSectionOperations, and G4BOptnChangeCrossSection::SetInteractionOccured().
virtual G4VBiasingOperation* GB01BOptrChangeCrossSection::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 75 of file GB01BOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 75 of file GB01BOptrChangeCrossSection.hh
virtual G4VBiasingOperation* GB01BOptrChangeCrossSection::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 78 of file GB01BOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 78 of file GB01BOptrChangeCrossSection.hh
G4VBiasingOperation * GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) private virtual
Implements G4VBiasingOperator.
Definition at line 105 of file GB01BOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 105 of file GB01BOptrChangeCrossSection.cc
References DBL_MAX, fChangeCrossSectionOperations, fParticleToBias, G4endl, G4Exception(), G4VProcess::GetCurrentInteractionLength(), G4Track::GetDefinition(), G4BOptnChangeCrossSection::GetInteractionOccured(), G4BiasingProcessInterface::GetPreviousOccurenceBiasingOperation(), G4BiasingProcessInterface::GetPreviousStepSize(), G4BiasingProcessInterface::GetWrappedProcess(), JustWarning, G4BOptnChangeCrossSection::Sample(), G4BOptnChangeCrossSection::SetBiasedCrossSection(), and G4BOptnChangeCrossSection::UpdateForStep().
void GB01BOptrChangeCrossSection::StartRun () virtual
Reimplemented from G4VBiasingOperator.
Definition at line 73 of file GB01BOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 73 of file GB01BOptrChangeCrossSection.cc
References fChangeCrossSectionOperations, fParticleToBias, fSetup, G4BiasingProcessSharedData::GetPhysicsBiasingProcessInterfaces(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4BiasingProcessInterface::GetSharedData(), and G4BiasingProcessInterface::GetWrappedProcess().
Member Data Documentation
std::map< const G4BiasingProcessInterface*, G4BOptnChangeCrossSection* > GB01BOptrChangeCrossSection::fChangeCrossSectionOperations private
Definition at line 99 of file GB01BOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 99 of file GB01BOptrChangeCrossSection.hh
Referenced by OperationApplied(), ProposeOccurenceBiasingOperation(), StartRun(), and ~GB01BOptrChangeCrossSection().
const G4ParticleDefinition* GB01BOptrChangeCrossSection::fParticleToBias private
Definition at line 101 of file GB01BOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 101 of file GB01BOptrChangeCrossSection.hh
Referenced by GB01BOptrChangeCrossSection(), ProposeOccurenceBiasingOperation(), and StartRun().
G4bool GB01BOptrChangeCrossSection::fSetup private
Definition at line 100 of file GB01BOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 100 of file GB01BOptrChangeCrossSection.hh
Referenced by StartRun().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB01/include/GB01BOptrChangeCrossSection.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB01/src/GB01BOptrChangeCrossSection.cc