ECCE @ EIC Software: G4INCL::INCL Class Reference
G4INCL::INCL Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCascade.hh>
Classes
class RecoilCMFunctor
Class to adjust remnant recoil in the reaction CM system.
class RecoilFunctor
Class to adjust remnant recoil.
Public Member Functions
INCL (Config const *const config)
~INCL ()
INCL (const INCL &rhs)
Dummy copy constructor to silence Coverity warning.
INCL & operator= (const INCL &rhs)
Dummy assignment operator to silence Coverity warning.
G4bool prepareReaction (const ParticleSpecies &projectileSpecies, const G4double kineticEnergy, const G4int A, const G4int Z, const G4int S)
G4bool initializeTarget (const G4int A, const G4int Z, const G4int S)
const EventInfo & processEvent ()
const EventInfo & processEvent (ParticleSpecies const &projectileSpecies, const G4double kineticEnergy, const G4int targetA, const G4int targetZ, const G4int targetS)
void finalizeGlobalInfo (Random::SeedVector const &initialSeeds)
const GlobalInfo & getGlobalInfo () const
Private Member Functions
void rescaleOutgoingForRecoil ()
Rescale the energies of the outgoing particles.
G4bool continueCascade ()
Stopping criterion for the cascade.
G4int makeProjectileRemnant ()
Make a projectile pre-fragment out of geometrical spectators.
void makeCompoundNucleus ()
Make a compound nucleus.
G4bool preCascade (ParticleSpecies const &projectileSpecies, const G4double kineticEnergy)
Initialise the cascade.
void cascade ()
The actual cascade loop.
void postCascade ()
Finalise the cascade and clean up.
void initMaxInteractionDistance (ParticleSpecies const &p, const G4double kineticEnergy)
Initialise the maximum interaction distance.
void initUniverseRadius (ParticleSpecies const &p, const G4double kineticEnergy, const G4int A, const G4int Z)
Initialize the universe radius.
void updateGlobalInfo ()
Update global counters and other members of theGlobalInfo object.
Private Attributes
IPropagationModel * propagationModel
G4int theA
G4int theZ
G4int theS
G4bool targetInitSuccess
G4double maxImpactParameter
G4double maxUniverseRadius
G4double maxInteractionDistance
G4double fixedImpactParameter
CascadeAction * cascadeAction
Config const *const theConfig
Nucleus * nucleus
G4bool forceTransparent
EventInfo theEventInfo
GlobalInfo theGlobalInfo
G4int minRemnantSize
Remnant size below which cascade stops.
Detailed Description
Definition at line 52 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 52 of file G4INCLCascade.hh
Constructor & Destructor Documentation
G4INCL::INCL::INCL (Config const *const config)
Definition at line 79 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 79 of file G4INCLCascade.cc
References G4INCL::GlobalInfo::Ap, G4INCL::GlobalInfo::At, G4INCL::AvatarDumpActionType, G4INCL::CascadeAction::beforeRunAction(), cascadeAction, G4INCL::GlobalInfo::cascadeModel, G4INCL::GlobalInfo::deexcitationModel, G4INCL::GlobalInfo::Ep, fixedImpactParameter, G4INCL::Config::getBias(), G4INCL::Config::getCascadeActionType(), G4INCL::Config::getCutNN(), G4INCL::Config::getDeExcitationString(), G4INCL::Config::getHadronizationTime(), G4INCL::Config::getImpactParameter(), G4INCL::Config::getLocalEnergyBBType(), G4INCL::Config::getLocalEnergyPiType(), G4INCL::Config::getProjectileKineticEnergy(), G4INCL::Config::getProjectileSpecies(), G4INCL::Config::getTargetA(), G4INCL::Config::getTargetZ(), G4INCL::Config::getVersionString(), G4INCL::Clustering::initialize(), G4INCL::PhaseSpaceGenerator::initialize(), G4INCL::ParticleTable::initialize(), G4INCL::Pauli::initialize(), G4INCL::CoulombDistortion::initialize(), G4INCL::Random::initialize(), G4INCL::CrossSections::initialize(), G4INCL::Logger::initVerbosityLevelFromEnvvar(), propagationModel, G4INCL::BinaryCollisionAvatar::setBias(), G4INCL::BinaryCollisionAvatar::setCutNN(), G4INCL::ParticleSpecies::theA, theConfig, theGlobalInfo, G4INCL::ParticleSpecies::theZ, G4INCL::GlobalInfo::Zp, and G4INCL::GlobalInfo::Zt.
G4INCL::INCL::~INCL ()
Definition at line 160 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 160 of file G4INCLCascade.cc
References G4INCL::CascadeAction::afterRunAction(), cascadeAction, G4INCL::NuclearDensityFactory::clearCache(), G4INCL::NuclearPotential::clearCache(), G4INCL::InteractionAvatar::deleteBackupParticles(), G4INCL::Pauli::deleteBlockers(), G4INCL::Clustering::deleteClusteringModel(), G4INCL::CoulombDistortion::deleteCoulomb(), G4INCL::CrossSections::deleteCrossSections(), G4INCL::Random::deleteGenerator(), G4INCL::PhaseSpaceGenerator::deletePhaseSpaceGenerator(), propagationModel, and theConfig.
G4INCL::INCL::INCL (const INCL & rhs)
Dummy copy constructor to silence Coverity warning.
Member Function Documentation
void G4INCL::INCL::cascade () private
The actual cascade loop.
Definition at line 328 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 328 of file G4INCLCascade.cc
References G4INCL::CascadeAction::afterAvatarAction(), G4INCL::CascadeAction::afterPropagationAction(), G4INCL::Nucleus::applyFinalState(), G4INCL::CascadeAction::beforeAvatarAction(), G4INCL::CascadeAction::beforePropagationAction(), cascadeAction, continueCascade(), G4INCL::IAvatar::fillFinalState(), nucleus, G4INCL::IPropagationModel::propagate(), propagationModel, and G4INCL::FinalState::reset().
Referenced by processEvent().
G4bool G4INCL::INCL::continueCascade () private
Stopping criterion for the cascade.
Returns true if the cascade should continue, and false if any of the stopping criteria is satisfied.
Definition at line 710 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 710 of file G4INCLCascade.cc
References G4INCL::Particle::getA(), G4INCL::Store::getBook(), G4INCL::Book::getCascading(), G4INCL::IPropagationModel::getCurrentTime(), G4INCL::Store::getIncomingParticles(), G4INCL::IPropagationModel::getStoppingTime(), G4INCL::Nucleus::getStore(), G4INCL::Nucleus::getTryCompoundNucleus(), INCL_DEBUG, minRemnantSize, nucleus, and propagationModel.
Referenced by cascade().
void G4INCL::INCL::finalizeGlobalInfo (Random::SeedVector const & initialSeeds)
Definition at line 741 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 741 of file G4INCLCascade.cc
References G4INCL::GlobalInfo::completeFusionCrossSection, G4INCL::GlobalInfo::energyViolationInteractionCrossSection, G4INCL::GlobalInfo::errorCompleteFusionCrossSection, G4INCL::GlobalInfo::errorForcedCNCrossSection, G4INCL::GlobalInfo::errorReactionCrossSection, G4INCL::GlobalInfo::finalRandomSeeds, G4INCL::GlobalInfo::forcedCNCrossSection, G4INCL::GlobalInfo::geometricCrossSection, G4INCL::Random::getSeeds(), G4INCL::GlobalInfo::initialRandomSeeds, G4INCL::GlobalInfo::nCompleteFusion, G4INCL::GlobalInfo::nEnergyViolationInteraction, G4INCL::GlobalInfo::nForcedCompoundNucleus, G4INCL::GlobalInfo::nNucleonAbsorptions, G4INCL::GlobalInfo::nPionAbsorptions, G4INCL::GlobalInfo::nShots, G4INCL::GlobalInfo::nTransparents, G4INCL::GlobalInfo::nucleonAbsorptionCrossSection, G4INCL::GlobalInfo::pionAbsorptionCrossSection, G4INCL::GlobalInfo::reactionCrossSection, and theGlobalInfo.
const GlobalInfo& G4INCL::INCL::getGlobalInfo () const inline
Definition at line 84 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 84 of file G4INCLCascade.hh
References theGlobalInfo.
G4bool G4INCL::INCL::initializeTarget (const G4int A, const G4int Z, const G4int S)
Definition at line 230 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 230 of file G4INCLCascade.cc
References G4INCL::Store::getBook(), G4INCL::Nucleus::getStore(), G4INCL::Nucleus::initializeParticles(), maxUniverseRadius, nucleus, propagationModel, G4INCL::Book::reset(), G4INCL::IPropagationModel::setNucleus(), and theConfig.
Referenced by prepareReaction().
void G4INCL::INCL::initMaxInteractionDistance (ParticleSpecies const & p, const G4double kineticEnergy) private
Initialise the maximum interaction distance.
Used in forced CN events.
Definition at line 805 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 805 of file G4INCLCascade.cc
References G4INCL::Composite, G4INCL::ParticleTable::getNuclearRadius(), INCL_DEBUG, G4INCL::CrossSections::interactionDistanceNN(), max, maxInteractionDistance, G4INCL::Neutron, G4INCL::Proton, theA, G4INCL::ParticleSpecies::theType, and theZ.
Referenced by prepareReaction().
void G4INCL::INCL::initUniverseRadius (ParticleSpecies const & p, const G4double kineticEnergy, const G4int A, const G4int Z) private
Initialize the universe radius.
Used for determining the energy-dependent size of the volume particles live in.
Definition at line 821 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 821 of file G4INCLCascade.cc
References G4INCL::Composite, e, G4INCL::IsotopicDistribution::getIsotopes(), G4INCL::ParticleTable::getMaximumNuclearRadius(), G4INCL::ParticleTable::getNaturalIsotopicDistribution(), INCL_DEBUG, G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::KMinus, G4INCL::KPlus, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, max, maxUniverseRadius, G4INCL::Neutron, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, and G4INCL::ParticleSpecies::theType.
Referenced by prepareReaction().
void G4INCL::INCL::makeCompoundNucleus () private
Make a compound nucleus.
Selects the projectile components that can actually enter their potential and puts them into the target nucleus. If the CN excitation energy turns out to be negative, the event is considered a transparent. This method modifies theEventInfo and theGlobalInfo.
Definition at line 500 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 500 of file G4INCLCascade.cc
References G4INCL::Store::addParticleEntryAvatar(), G4INCL::Nucleus::applyFinalState(), G4INCL::EventInfo::At, G4INCL::Store::clearIncoming(), G4INCL::Store::clearOutgoing(), G4INCL::EventInfo::clusterDecay, G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), e, G4INCL::Nucleus::emitInsideKaon(), G4INCL::EventInfo::emitKaon, G4INCL::Intersection::exists, G4INCL::Nucleus::fillEventInfo(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::EventInfo::forcedDeltasOutside, G4INCL::EventInfo::forcedPionResonancesOutside, forceTransparent, Acts::UnitConstants::fs, G4INCL::Random::getAdapter(), G4INCL::Cluster::getAngularMomentum(), G4INCL::IPropagationModel::getCurrentTime(), G4INCL::Config::getDecayTimeThreshold(), G4INCL::IntersectionFactory::getEarlierTrajectoryIntersection(), G4INCL::Particle::getEnergy(), G4INCL::IAvatar::getFinalState(), G4INCL::Nucleus::getIncomingAngularMomentum(), G4INCL::Nucleus::getIncomingMomentum(), G4INCL::Particle::getMomentum(), G4INCL::Cluster::getParticles(), G4INCL::Nucleus::getProjectileRemnant(), G4INCL::Nucleus::getStore(), G4INCL::ParticleTable::getTableMass, G4INCL::FinalState::getValidity(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), INCL_DEBUG, G4INCL::Nucleus::isNucleusNucleusCollision(), G4INCL::ThreeVector::mag2(), maxInteractionDistance, G4INCL::NoEnergyConservationFS, nucleus, G4INCL::ParticleBelowFermiFS, G4INCL::ParticleBelowZeroFS, G4INCL::PauliBlockedFS, propagationModel, G4INCL::ProjectileRemnant::reset(), G4INCL::Cluster::setA(), G4INCL::Particle::setEnergy(), G4INCL::Cluster::setExcitationEnergy(), G4INCL::Particle::setMass(), G4INCL::Particle::setMomentum(), G4INCL::Cluster::setS(), G4INCL::Cluster::setSpin(), G4INCL::Cluster::setZ(), G4INCL::EventInfo::St, theConfig, theEventInfo, G4INCL::ValidFS, and G4INCL::EventInfo::Zt.
Referenced by postCascade().
G4int G4INCL::INCL::makeProjectileRemnant () private
Make a projectile pre-fragment out of geometrical spectators.
The projectile pre-fragment is assigned an excitation energy given by , where is the sum of the energies of the spectator particles, and is the sum of the smallest particle energies initially present in the projectile, being the mass of the projectile pre-fragment. This is equivalent to assuming that the excitation energy is given by the sum of the transitions of all excited projectile components to the "holes" left by the participants.
This method can modify the outgoing list and adds a projectile pre-fragment.
Returns
the number of dynamical spectators that were merged back in the projectile
Definition at line 769 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 769 of file G4INCLCascade.cc
References G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::Store::addToOutgoing(), G4INCL::Store::extractDynamicalSpectators(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::IPropagationModel::getCurrentTime(), G4INCL::Cluster::getParticles(), G4INCL::Nucleus::getProjectileRemnant(), G4INCL::Nucleus::getStore(), nucleus, and propagationModel.
Referenced by postCascade().
INCL& G4INCL::INCL::operator= (const INCL & rhs)
Dummy assignment operator to silence Coverity warning.
void G4INCL::INCL::postCascade () private
Finalise the cascade and clean up.
Definition at line 374 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 374 of file G4INCLCascade.cc
References G4INCL::EventInfo::absorbedStrangeParticle, G4INCL::EventInfo::antikaonsInside, G4INCL::Store::clearIncoming(), G4INCL::EventInfo::clusterDecay, G4INCL::Nucleus::computeExcitationEnergy(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::containsAntiKaon(), G4INCL::Nucleus::containsDeltas(), G4INCL::Nucleus::containsKaon(), G4INCL::Nucleus::containsLambda(), G4INCL::Nucleus::containsSigma(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingNeutralKaon(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Store::deleteIncoming(), G4INCL::EventInfo::deltasInside, G4INCL::CoulombDistortion::distortOut(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::EventInfo::emitKaon, G4INCL::EventInfo::emitLambda, G4INCL::EventInfo::eventBias, G4INCL::Nucleus::fillEventInfo(), G4INCL::EventInfo::forcedDeltasInside, G4INCL::EventInfo::forcedDeltasOutside, G4INCL::EventInfo::forcedPionResonancesOutside, forceTransparent, G4INCL::Particle::getA(), G4INCL::IPropagationModel::getCurrentTime(), G4INCL::Config::getDecayTimeThreshold(), G4INCL::Nucleus::getExcitationEnergy(), G4INCL::Store::getOutgoingParticles(), G4INCL::Cluster::getParticles(), G4INCL::Nucleus::getProjectileRemnant(), G4INCL::Nucleus::getStore(), G4INCL::Particle::getTotalBias(), G4INCL::Nucleus::getTryCompoundNucleus(), G4INCL::Nucleus::hasRemnant(), INCL_DEBUG, INCL_ERROR, INCL_WARN, G4INCL::Nucleus::isEventTransparent(), G4INCL::EventInfo::kaonsInside, G4INCL::EventInfo::lambdasInside, makeCompoundNucleus(), makeProjectileRemnant(), minRemnantSize, nucleus, G4INCL::EventInfo::nUnmergedSpectators, propagationModel, rescaleOutgoingForRecoil(), G4INCL::Cluster::setExcitationEnergy(), G4INCL::EventInfo::sigmasInside, G4INCL::EventInfo::stoppingTime, theConfig, theEventInfo, G4INCL::EventInfo::transparent, and G4INCL::Nucleus::useFusionKinematics().
Referenced by processEvent().
G4bool G4INCL::INCL::preCascade (ParticleSpecies const & projectileSpecies, const G4double kineticEnergy) private
Initialise the cascade.
Definition at line 274 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 274 of file G4INCLCascade.cc
References G4INCL::EventInfo::Ap, G4INCL::EventInfo::At, G4INCL::EventInfo::effectiveImpactParameter, G4INCL::EventInfo::Ep, G4INCL::EventInfo::eventNumber, fixedImpactParameter, G4INCL::Particle::getA(), G4INCL::Particle::getS(), G4INCL::Particle::getZ(), G4INCL::EventInfo::impactParameter, INCL_DEBUG, maxImpactParameter, nucleus, phi, G4INCL::EventInfo::projectileType, propagationModel, G4INCL::EventInfo::reset(), G4INCL::Random::shoot(), G4INCL::IPropagationModel::shoot(), G4INCL::Random::shoot0(), G4INCL::EventInfo::Sp, G4INCL::EventInfo::St, G4INCL::ParticleSpecies::theA, theEventInfo, G4INCL::ParticleSpecies::theS, G4INCL::ParticleSpecies::theType, G4INCL::ParticleSpecies::theZ, G4INCL::EventInfo::transparent, G4INCL::Math::twoPi, G4INCL::EventInfo::Zp, and G4INCL::EventInfo::Zt.
Referenced by processEvent().
G4bool G4INCL::INCL::prepareReaction (const ParticleSpecies & projectileSpecies, const G4double kineticEnergy, const G4int A, const G4int Z, const G4int S)
Definition at line 182 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 182 of file G4INCLCascade.cc
References A(), G4INCL::Composite, G4INCL::ParticleTable::drawRandomNaturalIsotope(), forceTransparent, G4INCL::GlobalInfo::geometricCrossSection, INCL_DEBUG, INCL_ERROR, initializeTarget(), initMaxInteractionDistance(), initUniverseRadius(), G4INCL::Config::isNaturalTarget(), maxImpactParameter, G4INCL::CoulombDistortion::maxImpactParameter(), min, minRemnantSize, nucleus, S(), G4INCL::Math::tenPi, G4INCL::ParticleSpecies::theA, theA, theConfig, theGlobalInfo, G4INCL::ParticleSpecies::theS, theS, G4INCL::ParticleSpecies::theType, G4INCL::ParticleSpecies::theZ, theZ, and Z.
Referenced by processEvent().
const EventInfo& G4INCL::INCL::processEvent () inline
Definition at line 66 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLCascade.hh
References G4INCL::Config::getProjectileKineticEnergy(), G4INCL::Config::getProjectileSpecies(), G4INCL::Config::getTargetA(), G4INCL::Config::getTargetS(), G4INCL::Config::getTargetZ(), and theConfig.
Referenced by G4INCLXXInterface::ApplyYourself().
const EventInfo & G4INCL::INCL::processEvent (ParticleSpecies const & projectileSpecies, const G4double kineticEnergy, const G4int targetA, const G4int targetZ, const G4int targetS)
Definition at line 241 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 241 of file G4INCLCascade.cc
References G4INCL::CascadeAction::afterCascadeAction(), G4INCL::CascadeAction::beforeCascadeAction(), cascade(), cascadeAction, INCL_WARN, G4INCL::Particle::INCLBiasVector, G4INCL::Particle::nextBiasedCollisionID, nucleus, postCascade(), preCascade(), prepareReaction(), propagationModel, targetInitSuccess, theEventInfo, G4INCL::EventInfo::transparent, and updateGlobalInfo().
void G4INCL::INCL::rescaleOutgoingForRecoil () private
Rescale the energies of the outgoing particles.
Allow for the remnant recoil energy by rescaling the energy (and momenta) of the outgoing particles.
Definition at line 652 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 652 of file G4INCLCascade.cc
References INCL_WARN, nucleus, G4INCL::RootFinder::solve(), G4INCL::RootFinder::Solution::success, theEventInfo, and G4INCL::RootFinder::Solution::x.
Referenced by postCascade().
void G4INCL::INCL::updateGlobalInfo () private
Update global counters and other members of theGlobalInfo object.
Definition at line 865 of file G4INCLCascade.cc.
View newest version in sPHENIX GitHub at line 865 of file G4INCLCascade.cc
References forceTransparent, G4INCL::Nucleus::getTryCompoundNucleus(), G4INCL::EventInfo::nCascadeParticles, G4INCL::GlobalInfo::nCompleteFusion, G4INCL::GlobalInfo::nEnergyViolationInteraction, G4INCL::EventInfo::nEnergyViolationInteraction, G4INCL::GlobalInfo::nForcedCompoundNucleus, G4INCL::GlobalInfo::nForcedTransparents, G4INCL::GlobalInfo::nNucleonAbsorptions, G4INCL::GlobalInfo::nPionAbsorptions, G4INCL::GlobalInfo::nShots, G4INCL::GlobalInfo::nTransparents, G4INCL::EventInfo::nucleonAbsorption, nucleus, G4INCL::EventInfo::pionAbsorption, theEventInfo, theGlobalInfo, and G4INCL::EventInfo::transparent.
Referenced by processEvent().
Member Data Documentation
CascadeAction* G4INCL::INCL::cascadeAction private
Definition at line 95 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 95 of file G4INCLCascade.hh
Referenced by cascade(), INCL(), processEvent(), and ~INCL().
G4double G4INCL::INCL::fixedImpactParameter private
Definition at line 94 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 94 of file G4INCLCascade.hh
Referenced by INCL(), and preCascade().
G4bool G4INCL::INCL::forceTransparent private
Definition at line 98 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 98 of file G4INCLCascade.hh
Referenced by makeCompoundNucleus(), postCascade(), prepareReaction(), and updateGlobalInfo().
G4double G4INCL::INCL::maxImpactParameter private
Definition at line 91 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 91 of file G4INCLCascade.hh
Referenced by preCascade(), and prepareReaction().
G4double G4INCL::INCL::maxInteractionDistance private
Definition at line 93 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 93 of file G4INCLCascade.hh
Referenced by initMaxInteractionDistance(), and makeCompoundNucleus().
G4double G4INCL::INCL::maxUniverseRadius private
Definition at line 92 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 92 of file G4INCLCascade.hh
Referenced by initializeTarget(), and initUniverseRadius().
G4int G4INCL::INCL::minRemnantSize private
Remnant size below which cascade stops.
Definition at line 104 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 104 of file G4INCLCascade.hh
Referenced by continueCascade(), postCascade(), and prepareReaction().
Nucleus* G4INCL::INCL::nucleus private
Definition at line 97 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 97 of file G4INCLCascade.hh
Referenced by cascade(), continueCascade(), initializeTarget(), makeCompoundNucleus(), makeProjectileRemnant(), postCascade(), preCascade(), prepareReaction(), processEvent(), rescaleOutgoingForRecoil(), and updateGlobalInfo().
IPropagationModel* G4INCL::INCL::propagationModel private
Definition at line 88 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 88 of file G4INCLCascade.hh
Referenced by cascade(), continueCascade(), INCL(), initializeTarget(), makeCompoundNucleus(), makeProjectileRemnant(), postCascade(), preCascade(), processEvent(), and ~INCL().
G4bool G4INCL::INCL::targetInitSuccess private
Definition at line 90 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 90 of file G4INCLCascade.hh
Referenced by processEvent().
G4int G4INCL::INCL::theA private
Definition at line 89 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 89 of file G4INCLCascade.hh
Referenced by initMaxInteractionDistance(), and prepareReaction().
Config const* const G4INCL::INCL::theConfig private
Definition at line 96 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLCascade.hh
Referenced by INCL(), initializeTarget(), makeCompoundNucleus(), postCascade(), prepareReaction(), processEvent(), and ~INCL().
EventInfo G4INCL::INCL::theEventInfo private
Definition at line 100 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 100 of file G4INCLCascade.hh
Referenced by makeCompoundNucleus(), postCascade(), preCascade(), processEvent(), rescaleOutgoingForRecoil(), and updateGlobalInfo().
GlobalInfo G4INCL::INCL::theGlobalInfo private
Definition at line 101 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 101 of file G4INCLCascade.hh
Referenced by finalizeGlobalInfo(), getGlobalInfo(), INCL(), prepareReaction(), and updateGlobalInfo().
G4int G4INCL::INCL::theS private
Definition at line 89 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 89 of file G4INCLCascade.hh
Referenced by prepareReaction().
G4int G4INCL::INCL::theZ private
Definition at line 89 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 89 of file G4INCLCascade.hh
Referenced by initMaxInteractionDistance(), and prepareReaction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCascade.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCascade.cc