ECCE @ EIC Software: G4AdjointhIonisationModel Class Reference
G4AdjointhIonisationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointhIonisationModel.hh>
Public Member Functions
G4AdjointhIonisationModel (G4ParticleDefinition *projectileDefinition)
virtual ~G4AdjointhIonisationModel ()
virtual void SampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
void RapidSampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
virtual G4double DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A=0.)
virtual G4double AdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut=0)
virtual G4double GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy)
Public Member Functions inherited from G4VEmAdjointModel
G4VEmAdjointModel (const G4String &nam)
virtual ~G4VEmAdjointModel ()
virtual G4double GetAdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerVolumePrimToSecond (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
virtual G4double DiffCrossSectionPerVolumePrimToScatPrim (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj)
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
void SetCSMatrices (std::vector< G4AdjointCSMatrix * > *Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > *Vec2CSMatrix)
G4ParticleDefinition * GetAdjointEquivalentOfDirectPrimaryParticleDefinition ()
G4ParticleDefinition * GetAdjointEquivalentOfDirectSecondaryParticleDefinition ()
G4double GetHighEnergyLimit ()
G4double GetLowEnergyLimit ()
void SetHighEnergyLimit (G4double aVal)
void SetLowEnergyLimit (G4double aVal)
void DefineDirectEMModel (G4VEmModel *aModel)
void SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition *aPart)
void SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition *aPart)
void SetSecondPartOfSameType (G4bool aBool)
G4bool GetSecondPartOfSameType ()
void SetUseMatrix (G4bool aBool)
void SetUseMatrixPerElement (G4bool aBool)
void SetUseOnlyOneMatrixForAllElements (G4bool aBool)
void SetApplyCutInRange (G4bool aBool)
G4bool GetUseMatrix ()
G4bool GetUseMatrixPerElement ()
G4bool GetUseOnlyOneMatrixForAllElements ()
G4bool GetApplyCutInRange ()
G4String GetName ()
virtual void SetCSBiasingFactor (G4double aVal)
void SetCorrectWeightForPostStepInModel (G4bool aBool)
void SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor)
Private Member Functions
void DefineProjectileProperty ()
Private Attributes
G4double mass
G4double tlimit
G4double spin
G4double magMoment2
G4double chargeSquare
G4double ratio
G4double ratio2
G4double one_plus_ratio_2
G4double formfact
G4bool isIon
G4double one_minus_ratio_2
G4VEmModel * theBraggDirectEMModel
Additional Inherited Members
Protected Member Functions inherited from G4VEmAdjointModel
G4double DiffCrossSectionFunction1 (G4double kinEnergyProj)
G4double DiffCrossSectionFunction2 (G4double kinEnergyProj)
G4double DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd)
G4double SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase)
G4double SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase)
void SelectCSMatrix (G4bool IsScatProjToProjCase)
virtual G4double SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase)
virtual void CorrectPostStepWeight (G4ParticleChange *fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase)
Protected Attributes inherited from G4VEmAdjointModel
G4VEmModel * theDirectEMModel
G4VParticleChange * pParticleChange
const G4String name
G4int ASelectedNucleus
G4int ZSelectedNucleus
G4Material * SelectedMaterial
G4double kinEnergyProdForIntegration
G4double kinEnergyScatProjForIntegration
G4double kinEnergyProjForIntegration
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4double > CS_Vs_ElementForScatProjToProjCase
std::vector< G4double > CS_Vs_ElementForProdToProjCase
G4double lastCS
G4double lastAdjointCSForScatProjToProjCase
G4double lastAdjointCSForProdToProjCase
G4ParticleDefinition * theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition * theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition * theDirectPrimaryPartDef
G4bool second_part_of_same_type
G4double preStepEnergy
G4Material * currentMaterial
G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcutForDirectPrim
G4double currentTcutForDirectSecond
G4bool ApplyCutInRange
G4double mass_ratio_product
G4double mass_ratio_projectile
G4double HighEnergyLimit
G4double LowEnergyLimit
G4double CS_biasing_factor
G4bool UseMatrix
G4bool UseMatrixPerElement
G4bool UseOnlyOneMatrixForAllElements
size_t indexOfUsedCrossSectionMatrix
size_t model_index
G4bool correct_weight_for_post_step_in_model
G4double additional_weight_correction_factor_for_post_step_outside_model
Detailed Description
Definition at line 71 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AdjointhIonisationModel.hh
Constructor & Destructor Documentation
G4AdjointhIonisationModel::G4AdjointhIonisationModel (G4ParticleDefinition * projectileDefinition)
Definition at line 45 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4AdjointhIonisationModel.cc
References G4AdjointElectron::AdjointElectron(), G4AdjointProton::AdjointProton(), G4VEmAdjointModel::ApplyCutInRange, G4VEmAdjointModel::CS_biasing_factor, DefineProjectileProperty(), G4Proton::Proton(), G4VEmAdjointModel::second_part_of_same_type, G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, theBraggDirectEMModel, G4VEmAdjointModel::theDirectEMModel, G4VEmAdjointModel::theDirectPrimaryPartDef, G4VEmAdjointModel::UseMatrix, G4VEmAdjointModel::UseMatrixPerElement, and G4VEmAdjointModel::UseOnlyOneMatrixForAllElements.
G4AdjointhIonisationModel::~G4AdjointhIonisationModel () virtual
Definition at line 77 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointhIonisationModel.cc
Member Function Documentation
G4double G4AdjointhIonisationModel::AdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 437 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 437 of file G4AdjointhIonisationModel.cc
References G4VEmAdjointModel::AdjointCrossSection(), G4VEmAdjointModel::currentMaterial, G4VEmAdjointModel::currentTcutForDirectSecond, G4VEmAdjointModel::DefineCurrentMaterial(), G4Material::GetElectronDensity(), GetSecondAdjEnergyMaxForProdToProjCase(), GetSecondAdjEnergyMaxForScatProjToProjCase(), GetSecondAdjEnergyMinForProdToProjCase(), GetSecondAdjEnergyMinForScatProjToProjCase(), G4VEmAdjointModel::lastCS, mass, t1, t2, source.hepunit::twopi_mc2_rcl2, and G4VEmAdjointModel::UseMatrix.
void G4AdjointhIonisationModel::DefineProjectileProperty () private
Definition at line 400 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 400 of file G4AdjointhIonisationModel.cc
References source.hepunit::c_squared, chargeSquare, source.hepunit::electron_mass_c2, eplus, formfact, G4ParticleDefinition::GetLeptonNumber(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), G4NistManager::GetZ13(), GeV, source.hepunit::hbar_Planck, G4NistManager::Instance(), isIon, magMoment2, mass, G4VEmAdjointModel::mass_ratio_projectile, one_minus_ratio_2, one_plus_ratio_2, pname(), source.hepunit::proton_mass_c2, ratio, ratio2, spin, G4VEmAdjointModel::theDirectPrimaryPartDef, tlimit, and x.
Referenced by G4AdjointhIonisationModel().
G4double G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A = 0.) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 305 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 305 of file G4AdjointhIonisationModel.cc
References G4VEmModel::ComputeCrossSectionPerAtom(), dE, e, source.hepunit::electron_mass_c2, f, f1, formfact, Acts::UnitConstants::g, G4cout, G4endl, GetSecondAdjEnergyMaxForProdToProjCase(), GetSecondAdjEnergyMinForProdToProjCase(), magMoment2, mass, MeV, spin, theBraggDirectEMModel, G4VEmAdjointModel::theDirectEMModel, G4VEmAdjointModel::theDirectPrimaryPartDef, x, x1, and x2.
Referenced by RapidSampleSecondaries().
G4double G4AdjointhIonisationModel::GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 490 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 490 of file G4AdjointhIonisationModel.cc
References G4VEmAdjointModel::HighEnergyLimit.
Referenced by AdjointCrossSection(), DiffCrossSectionPerAtomPrimToSecond(), and RapidSampleSecondaries().
G4double G4AdjointhIonisationModel::GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 478 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 478 of file G4AdjointhIonisationModel.cc
References mass, one_minus_ratio_2, one_plus_ratio_2, and ratio.
Referenced by AdjointCrossSection(), and RapidSampleSecondaries().
G4double G4AdjointhIonisationModel::GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 495 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 495 of file G4AdjointhIonisationModel.cc
References mass, and ratio.
Referenced by AdjointCrossSection(), DiffCrossSectionPerAtomPrimToSecond(), and RapidSampleSecondaries().
G4double G4AdjointhIonisationModel::GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut = 0) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 485 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 485 of file G4AdjointhIonisationModel.cc
Referenced by AdjointCrossSection(), and RapidSampleSecondaries().
void G4AdjointhIonisationModel::RapidSampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange)
Definition at line 159 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 159 of file G4AdjointhIonisationModel.cc
References a, G4ParticleChange::AddSecondary(), b, G4VEmAdjointModel::currentMaterial, G4VEmAdjointModel::currentTcutForDirectSecond, G4VEmAdjointModel::DefineCurrentMaterial(), DiffCrossSectionPerAtomPrimToSecond(), Emax, Emin, fStopAndKill, G4UniformRand, G4AdjointCSManager::GetAdjointCSManager(), G4Track::GetDynamicParticle(), G4Material::GetElectronDensity(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4AdjointCSManager::GetPostStepWeightCorrection(), GetSecondAdjEnergyMaxForProdToProjCase(), GetSecondAdjEnergyMaxForScatProjToProjCase(), GetSecondAdjEnergyMinForProdToProjCase(), GetSecondAdjEnergyMinForScatProjToProjCase(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetWeight(), G4VEmAdjointModel::HighEnergyLimit, G4VEmAdjointModel::lastCS, mass, phi, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4VParticleChange::SetParentWeightByProcess(), G4VParticleChange::SetSecondaryWeightByProcess(), t, t1, t2, G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, source.hepunit::twopi_mc2_rcl2, and CLHEP::Hep3Vector::unit().
Referenced by SampleSecondaries().
void G4AdjointhIonisationModel::SampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange) virtual
Implements G4VEmAdjointModel.
Definition at line 83 of file G4AdjointhIonisationModel.cc.
View newest version in sPHENIX GitHub at line 83 of file G4AdjointhIonisationModel.cc
References G4ParticleChange::AddSecondary(), G4VEmAdjointModel::CorrectPostStepWeight(), fStopAndKill, G4UniformRand, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetWeight(), G4VEmAdjointModel::HighEnergyLimit, phi, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), RapidSampleSecondaries(), CLHEP::Hep3Vector::rotateUz(), G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, CLHEP::Hep3Vector::unit(), and G4VEmAdjointModel::UseMatrix.
Member Data Documentation
G4double G4AdjointhIonisationModel::chargeSquare private
Definition at line 115 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty().
G4double G4AdjointhIonisationModel::formfact private
Definition at line 118 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty(), and DiffCrossSectionPerAtomPrimToSecond().
G4bool G4AdjointhIonisationModel::isIon private
Definition at line 119 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty().
G4double G4AdjointhIonisationModel::magMoment2 private
Definition at line 114 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty(), and DiffCrossSectionPerAtomPrimToSecond().
G4double G4AdjointhIonisationModel::mass private
Definition at line 111 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AdjointhIonisationModel.hh
Referenced by AdjointCrossSection(), DefineProjectileProperty(), DiffCrossSectionPerAtomPrimToSecond(), GetSecondAdjEnergyMaxForScatProjToProjCase(), GetSecondAdjEnergyMinForProdToProjCase(), and RapidSampleSecondaries().
G4double G4AdjointhIonisationModel::one_minus_ratio_2 private
Definition at line 120 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty(), and GetSecondAdjEnergyMaxForScatProjToProjCase().
G4double G4AdjointhIonisationModel::one_plus_ratio_2 private
Definition at line 117 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty(), and GetSecondAdjEnergyMaxForScatProjToProjCase().
G4double G4AdjointhIonisationModel::ratio private
Definition at line 116 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty(), GetSecondAdjEnergyMaxForScatProjToProjCase(), and GetSecondAdjEnergyMinForProdToProjCase().
G4double G4AdjointhIonisationModel::ratio2 private
Definition at line 116 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty().
G4double G4AdjointhIonisationModel::spin private
Definition at line 113 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty(), and DiffCrossSectionPerAtomPrimToSecond().
G4VEmModel* G4AdjointhIonisationModel::theBraggDirectEMModel private
Definition at line 124 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 124 of file G4AdjointhIonisationModel.hh
Referenced by DiffCrossSectionPerAtomPrimToSecond(), and G4AdjointhIonisationModel().
G4double G4AdjointhIonisationModel::tlimit private
Definition at line 112 of file G4AdjointhIonisationModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AdjointhIonisationModel.hh
Referenced by DefineProjectileProperty().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointhIonisationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4AdjointhIonisationModel.cc