ECCE @ EIC Software: G4HadSignalHandler_local Namespace Reference
G4HadSignalHandler_local Namespace Reference
Functions
void HandleIt (int i)
Variables
static void(* G4HadSignalHandler_initial)(int)
Function Documentation
void G4HadSignalHandler_local::HandleIt (int i)
Definition at line 63 of file G4HadSignalHandler.cc.
View newest version in sPHENIX GitHub at line 63 of file G4HadSignalHandler.cc
References c, G4HadSignalHandler_initial, G4ThreadLocal, int(), and G4HadSignalHandler::theCache.
Referenced by G4HadSignalHandler::G4HadSignalHandler().
Variable Documentation
void(* G4HadSignalHandler_local::G4HadSignalHandler_initial)(int) static
Definition at line 35 of file G4HadSignalHandler.cc.
View newest version in sPHENIX GitHub at line 35 of file G4HadSignalHandler.cc
Referenced by G4HadSignalHandler::G4HadSignalHandler(), HandleIt(), and G4HadSignalHandler::~G4HadSignalHandler().