ECCE @ EIC Software: G4ExcitedSigmaConstructor Class Reference
G4ExcitedSigmaConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedSigmaConstructor.hh>
Public Types
enum { NStates = 8 }
enum { NumberOfDecayModes = 8 }
Public Member Functions
G4ExcitedSigmaConstructor ()
virtual ~G4ExcitedSigmaConstructor ()
Public Member Functions inherited from G4ExcitedBaryonConstructor
G4ExcitedBaryonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedBaryonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Member Functions
virtual G4bool Exist (G4int)
virtual G4int GetQuarkContents (G4int, G4int)
virtual G4String GetName (G4int iIso3, G4int iState)
virtual G4String GetMultipletName (G4int iState)
virtual G4double GetMass (G4int state, G4int iso)
virtual G4double GetWidth (G4int state, G4int iso)
virtual G4int GetiSpin (G4int iState)
virtual G4int GetiParity (G4int iState)
virtual G4int GetEncodingOffset (G4int iState)
virtual G4DecayTable * CreateDecayTable (const G4String &name, G4int iIso3, G4int iState, G4bool fAnti=false)
Protected Member Functions inherited from G4ExcitedBaryonConstructor
virtual void ConstructParticle (G4int indexOfState)
virtual void ConstructAntiParticle (G4int indexOfState)
virtual G4double GetCharge (G4int iIsoSpin3)
virtual G4int GetEncoding (G4int iIsoSpin3, G4int idxState)
Private Types
enum { SigmaIsoSpin = 2 }
enum {
NK =0, NKStar =1, SigmaPi =2, SigmaStarPi =3,
LambdaPi =4, SigmaEta =5, LambdaStarPi =6, DeltaK =7
}
Private Member Functions
G4DecayTable * AddNKMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNKStarMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddSigmaPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddSigmaStarPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddSigmaEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaStarPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddDeltaKMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
Static Private Attributes
static const char * name [NStates]
static const G4double mass [NStates]
static const G4double width [NStates]
static const G4int iSpin [NStates]
static const G4int iParity [NStates]
static const G4int encodingOffset [NStates]
static const G4double bRatio [NStates][NumberOfDecayModes]
Additional Inherited Members
Protected Attributes inherited from G4ExcitedBaryonConstructor
G4int NumberOfStates
G4int iIsoSpin
const G4String type
const G4int iConjugation
const G4int iGParity
const G4int leptonNumber
const G4int baryonNumber
Detailed Description
Definition at line 42 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ExcitedSigmaConstructor.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
NStates
Definition at line 85 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitedSigmaConstructor.hh
anonymous enum private
Enumerator:
SigmaIsoSpin
Definition at line 87 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ExcitedSigmaConstructor.hh
anonymous enum
Enumerator:
NumberOfDecayModes
Definition at line 98 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ExcitedSigmaConstructor.hh
anonymous enum private
Enumerator:
NK
NKStar
SigmaPi
SigmaStarPi
LambdaPi
SigmaEta
LambdaStarPi
DeltaK
Definition at line 100 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ExcitedSigmaConstructor.hh
Constructor & Destructor Documentation
G4ExcitedSigmaConstructor::G4ExcitedSigmaConstructor ()
Definition at line 46 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ExcitedSigmaConstructor.cc
G4ExcitedSigmaConstructor::~G4ExcitedSigmaConstructor () virtual
Definition at line 52 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ExcitedSigmaConstructor.cc
Member Function Documentation
G4DecayTable * G4ExcitedSigmaConstructor::AddDeltaKMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 193 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 193 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddLambdaPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 498 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 498 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddLambdaStarPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 533 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 533 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddNKMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 127 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 127 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddNKStarMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 261 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 261 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddSigmaEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 102 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddSigmaPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 326 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 326 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::AddSigmaStarPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 412 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 412 of file G4ExcitedSigmaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedSigmaConstructor::CreateDecayTable (const G4String & name, G4int iIso3, G4int iState, G4bool fAnti = false) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 56 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedSigmaConstructor.cc
References AddDeltaKMode(), AddLambdaPiMode(), AddLambdaStarPiMode(), AddNKMode(), AddNKStarMode(), AddSigmaEtaMode(), AddSigmaPiMode(), AddSigmaStarPiMode(), bRatio, DeltaK, LambdaPi, LambdaStarPi, NK, NKStar, SigmaEta, SigmaPi, and SigmaStarPi.
virtual G4bool G4ExcitedSigmaConstructor::Exist (G4int) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 52 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ExcitedSigmaConstructor.hh
G4int G4ExcitedSigmaConstructor::GetEncodingOffset (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 121 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ExcitedSigmaConstructor.hh
References encodingOffset.
G4int G4ExcitedSigmaConstructor::GetiParity (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 115 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ExcitedSigmaConstructor.hh
References iParity.
G4int G4ExcitedSigmaConstructor::GetiSpin (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 109 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ExcitedSigmaConstructor.hh
References iSpin.
G4double G4ExcitedSigmaConstructor::GetMass (G4int state, G4int iso) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 570 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 570 of file G4ExcitedSigmaConstructor.cc
References mass, and MeV.
G4String G4ExcitedSigmaConstructor::GetMultipletName (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 154 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ExcitedSigmaConstructor.hh
G4String G4ExcitedSigmaConstructor::GetName (G4int iIso3, G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 160 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ExcitedSigmaConstructor.hh
References particle.
G4int G4ExcitedSigmaConstructor::GetQuarkContents (G4int iQ, G4int iIso3) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 127 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ExcitedSigmaConstructor.hh
G4double G4ExcitedSigmaConstructor::GetWidth (G4int state, G4int iso) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 580 of file G4ExcitedSigmaConstructor.cc.
View newest version in sPHENIX GitHub at line 580 of file G4ExcitedSigmaConstructor.cc
References MeV, and width.
Member Data Documentation
const G4double G4ExcitedSigmaConstructor::bRatio static private
Initial value:
=
{
   {   0.0,  0.0, 0.12,  0.0, 0.88,   0.0,   0.0,   0.0},
   {  0.30,  0.0, 0.35,  0.0, 0.35,   0.0,   0.0,   0.0},
   {  0.15,  0.0, 0.70,  0.0, 0.15,   0.0,   0.0,   0.0},
   {  0.40,  0.0, 0.05,  0.0,  0.0,  0.55,   0.0,   0.0},
   {  0.40,  0.0, 0.04, 0.10, 0.23,   0.0,  0.23,   0.0},
   {  0.15,  0.0, 0.40, 0.05, 0.40,   0.0,   0.0,   0.0},
   {  0.10, 0.15, 0.15, 0.15, 0.15,   0.0,  0.15,  0.15},
   {  0.20, 0.04, 0.10, 0.10, 0.20,   0.0,  0.18,  0.18}
}
Definition at line 103 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ExcitedSigmaConstructor.hh
Referenced by CreateDecayTable().
const G4int G4ExcitedSigmaConstructor::encodingOffset static private
Initial value:
= {
      0, 10000, 10000, 20000,     0,
  10000, 20000,     0
}
Definition at line 95 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ExcitedSigmaConstructor.hh
Referenced by GetEncodingOffset().
const G4int G4ExcitedSigmaConstructor::iParity static private
Initial value:
= {
  +1,  +1,   -1,  -1,  -1,
  +1,  -1,   +1
}
Definition at line 94 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ExcitedSigmaConstructor.hh
Referenced by GetiParity().
const G4int G4ExcitedSigmaConstructor::iSpin static private
Initial value:
= {
    3,   1,   3,   1,   5,
    5,   3,   7
}
Definition at line 93 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ExcitedSigmaConstructor.hh
Referenced by GetiSpin().
const G4double G4ExcitedSigmaConstructor::mass static private
Initial value:
= {
 1.3837*GeV, 1.660*GeV, 1.670*GeV, 1.750*GeV,  1.775*GeV,
  1.915*GeV, 1.940*GeV, 2.030*GeV
}
Definition at line 91 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ExcitedSigmaConstructor.hh
Referenced by GetMass().
const char * G4ExcitedSigmaConstructor::name static private
Initial value:
= {
  "sigma(1385)","sigma(1660)","sigma(1670)","sigma(1750)","sigma(1775)",
  "sigma(1915)","sigma(1940)","sigma(2030)"
}
Definition at line 90 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ExcitedSigmaConstructor.hh
const G4double G4ExcitedSigmaConstructor::width static private
Initial value:
= {
   36.0*MeV, 100.0*MeV,  60.0*MeV,  90.0*MeV, 120.0*MeV,
  120.0*MeV, 220.0*MeV, 180.0*MeV
}
Definition at line 92 of file G4ExcitedSigmaConstructor.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ExcitedSigmaConstructor.hh
Referenced by GetWidth().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedSigmaConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ExcitedSigmaConstructor.cc