ECCE @ EIC Software: G4AllocatorList Class Reference
G4AllocatorList Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4AllocatorList.hh>
Public Member Functions
~G4AllocatorList ()
void Register (G4AllocatorBase *)
void Destroy (G4int nStat=0, G4int verboseLevel=0)
G4int Size () const
Static Public Member Functions
static G4AllocatorList * GetAllocatorList ()
static G4AllocatorList * GetAllocatorListIfExist ()
Private Member Functions
G4AllocatorList ()
Private Attributes
std::vector< G4AllocatorBase * > fList
Static Private Attributes
static G4ThreadLocal
G4AllocatorList * fAllocatorList =0
Detailed Description
Definition at line 47 of file G4AllocatorList.hh.
View newest version in sPHENIX GitHub at line 47 of file G4AllocatorList.hh
Constructor & Destructor Documentation
G4AllocatorList::~G4AllocatorList ()
Definition at line 56 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 56 of file G4AllocatorList.cc
References fAllocatorList.
G4AllocatorList::G4AllocatorList () private
Definition at line 52 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 52 of file G4AllocatorList.cc
Referenced by GetAllocatorList().
Member Function Documentation
void G4AllocatorList::Destroy (G4int nStat = 0, G4int verboseLevel = 0)
Definition at line 66 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 66 of file G4AllocatorList.cc
References fList, G4cout, G4endl, and Size().
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
G4AllocatorList * G4AllocatorList::GetAllocatorList () static
Definition at line 38 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 38 of file G4AllocatorList.cc
References fAllocatorList, and G4AllocatorList().
Referenced by G4AllocatorBase::G4AllocatorBase().
G4AllocatorList * G4AllocatorList::GetAllocatorListIfExist () static
Definition at line 47 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 47 of file G4AllocatorList.cc
References fAllocatorList.
Referenced by G4FastList< G4Track >::DeleteObject(), G4RunManagerKernel::G4RunManagerKernel(), and G4RunManagerKernel::~G4RunManagerKernel().
void G4AllocatorList::Register (G4AllocatorBase * alloc)
Definition at line 61 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 61 of file G4AllocatorList.cc
References fList.
Referenced by G4AllocatorBase::G4AllocatorBase().
G4int G4AllocatorList::Size () const
Definition at line 110 of file G4AllocatorList.cc.
View newest version in sPHENIX GitHub at line 110 of file G4AllocatorList.cc
References fList.
Referenced by Destroy(), and G4RunManagerKernel::G4RunManagerKernel().
Member Data Documentation
G4ThreadLocal G4AllocatorList * G4AllocatorList::fAllocatorList =0 static private
Definition at line 67 of file G4AllocatorList.hh.
View newest version in sPHENIX GitHub at line 67 of file G4AllocatorList.hh
Referenced by GetAllocatorList(), GetAllocatorListIfExist(), and ~G4AllocatorList().
std::vector<G4AllocatorBase*> G4AllocatorList::fList private
Definition at line 68 of file G4AllocatorList.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AllocatorList.hh
Referenced by Destroy(), Register(), and Size().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4AllocatorList.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4AllocatorList.cc