ECCE @ EIC Software: G4tgbVolumeMgr Class Reference
G4tgbVolumeMgr Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbVolumeMgr.hh>
Public Member Functions
G4tgbVolumeMgr ()
~G4tgbVolumeMgr ()
void AddTextFile (const G4String &fname)
G4VPhysicalVolume * ReadAndConstructDetector ()
void CopyVolumes ()
G4tgbVolume * FindVolume (const G4String &volname)
void RegisterMe (const G4tgbVolume *vol)
void RegisterMe (const G4VSolid *solid)
void RegisterMe (const G4LogicalVolume *lv)
void RegisterMe (const G4VPhysicalVolume *pv)
void RegisterChildParentLVs (const G4LogicalVolume *logvol, const G4LogicalVolume *parentLV)
G4VSolid * FindG4Solid (const G4String &name)
G4LogicalVolume * FindG4LogVol (const G4String &theName, const G4bool bExists=0)
G4VPhysicalVolume * FindG4PhysVol (const G4String &theName, const G4bool bExists=0)
G4VPhysicalVolume * GetTopPhysVol ()
G4LogicalVolume * GetTopLogVol ()
void BuildPhysVolTree ()
void DumpSummary ()
void DumpG4LogVolTree ()
void DumpG4LogVolLeaf (const G4LogicalVolume *lv, unsigned int leafDepth)
void DumpG4PhysVolTree ()
void DumpG4PhysVolLeaf (const G4VPhysicalVolume *pv, unsigned int leafDepth)
void DumpG4SolidList ()
const std::multimap< G4String,
G4VSolid * > & GetSolids () const
void SetDetectorBuilder (G4tgbDetectorBuilder *db)
G4tgbDetectorBuilder * GetDetectorBuilder () const
Static Public Member Functions
static G4tgbVolumeMgr * GetInstance ()
Private Attributes
G4mssvol theVolumeList
G4mmssol theSolids
G4mmslv theLVs
G4mmspv thePVs
G4mlvlv theLVTree
G4mlvlv theLVInvTree
G4mpvpv thePVTree
G4mpvpv thePVInvTree
G4tgbDetectorBuilder * theDetectorBuilder
Static Private Attributes
static G4ThreadLocal
G4tgbVolumeMgr * theInstance = 0
Detailed Description
Definition at line 65 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 65 of file G4tgbVolumeMgr.hh
Constructor & Destructor Documentation
G4tgbVolumeMgr::G4tgbVolumeMgr ()
Definition at line 55 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgbVolumeMgr.cc
References E, G4ReflectionFactory::Instance(), mm, G4ReflectionFactory::SetScalePrecision(), and theDetectorBuilder.
Referenced by GetInstance().
G4tgbVolumeMgr::~G4tgbVolumeMgr ()
Definition at line 65 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 65 of file G4tgbVolumeMgr.cc
References theDetectorBuilder, and theInstance.
Member Function Documentation
void G4tgbVolumeMgr::AddTextFile (const G4String & fname)
Definition at line 84 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 84 of file G4tgbVolumeMgr.cc
References G4tgrFileReader::AddTextFile(), and G4tgrFileReader::GetInstance().
Referenced by ExTGDetectorConstruction::Construct(), ExTGDetectorConstructionWithSD::Construct(), ExTGDetectorConstructionWithCuts::Construct(), ExTGDetectorConstructionWithCpp::Construct(), and EICG4dRICHDetector::ConstructMe().
void G4tgbVolumeMgr::BuildPhysVolTree ()
Definition at line 342 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 342 of file G4tgbVolumeMgr.cc
void G4tgbVolumeMgr::CopyVolumes ()
Definition at line 148 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 148 of file G4tgbVolumeMgr.cc
References G4tgrVolumeMgr::GetInstance(), G4tgrVolumeMgr::GetVolumeMap(), and RegisterMe().
Referenced by G4tgbDetectorConstruction::Construct(), and G4tgbDetectorBuilder::ConstructDetector().
void G4tgbVolumeMgr::DumpG4LogVolLeaf (const G4LogicalVolume * lv, unsigned int leafDepth)
Definition at line 410 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 410 of file G4tgbVolumeMgr.cc
References G4cout, G4endl, and G4LogicalVolume::GetName().
Referenced by DumpG4LogVolTree().
void G4tgbVolumeMgr::DumpG4LogVolTree ()
Definition at line 399 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 399 of file G4tgbVolumeMgr.cc
References DumpG4LogVolLeaf(), G4cout, G4endl, and GetTopLogVol().
Referenced by DumpSummary().
void G4tgbVolumeMgr::DumpG4PhysVolLeaf (const G4VPhysicalVolume * pv, unsigned int leafDepth)
Definition at line 447 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 447 of file G4tgbVolumeMgr.cc
References G4cout, G4endl, and G4VPhysicalVolume::GetName().
Referenced by DumpG4PhysVolTree().
void G4tgbVolumeMgr::DumpG4PhysVolTree ()
Definition at line 436 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 436 of file G4tgbVolumeMgr.cc
References DumpG4PhysVolLeaf(), G4cout, G4endl, and GetTopPhysVol().
Referenced by DumpSummary().
void G4tgbVolumeMgr::DumpG4SolidList ()
Definition at line 387 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 387 of file G4tgbVolumeMgr.cc
References G4cout, G4endl, and theSolids.
Referenced by EICG4dRICHDetector::ConstructMe(), and DumpSummary().
void G4tgbVolumeMgr::DumpSummary ()
Definition at line 357 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 357 of file G4tgbVolumeMgr.cc
References DumpG4LogVolTree(), DumpG4PhysVolTree(), DumpG4SolidList(), G4cout, G4endl, G4tgbMaterialMgr::GetG4ElementList(), G4tgbMaterialMgr::GetG4IsotopeList(), G4tgbMaterialMgr::GetG4MaterialList(), G4tgbRotationMatrixMgr::GetG4RotMatList(), G4tgbRotationMatrixMgr::GetInstance(), G4tgbMaterialMgr::GetInstance(), G4VPhysicalVolume::GetName(), GetTopPhysVol(), theLVs, thePVs, and theSolids.
Referenced by EICG4dRICHDetector::ConstructMe().
G4LogicalVolume * G4tgbVolumeMgr::FindG4LogVol (const G4String & theName, const G4bool bExists = 0)
Definition at line 238 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 238 of file G4tgbVolumeMgr.cc
References FatalException, G4Exception(), and theLVs.
Referenced by ExTGRCRegionCutsMgr::BuildRegions(), ExTGDetectorConstructionWithCpp::Construct(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), ExTGDetectorConstructionWithSD::ConstructSDandField(), and EICG4dRICHOptics::EICG4dRICHOptics().
G4VPhysicalVolume * G4tgbVolumeMgr::FindG4PhysVol (const G4String & theName, const G4bool bExists = 0)
Definition at line 259 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 259 of file G4tgbVolumeMgr.cc
References FatalException, G4Exception(), and thePVs.
G4VSolid * G4tgbVolumeMgr::FindG4Solid (const G4String & name)
Definition at line 177 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 177 of file G4tgbVolumeMgr.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theSolids.
Referenced by G4tgbVolume::FindOrConstructG4Solid().
G4tgbVolume * G4tgbVolumeMgr::FindVolume (const G4String & volname)
Definition at line 163 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 163 of file G4tgbVolumeMgr.cc
References FatalException, G4Exception(), and theVolumeList.
Referenced by G4tgbDetectorConstruction::Construct(), G4tgbDetectorBuilder::ConstructDetector(), G4tgbVolume::ConstructG4PhysVol(), and G4tgbVolume::ConstructG4Volumes().
G4tgbDetectorBuilder* G4tgbVolumeMgr::GetDetectorBuilder () const inline
Definition at line 134 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 134 of file G4tgbVolumeMgr.hh
References theDetectorBuilder.
G4tgbVolumeMgr * G4tgbVolumeMgr::GetInstance (void) static
Definition at line 73 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 73 of file G4tgbVolumeMgr.cc
References G4tgbVolumeMgr(), and theInstance.
Referenced by ExTGRCRegionCutsMgr::BuildRegions(), ExTGDetectorConstruction::Construct(), ExTGDetectorConstructionWithCpp::Construct(), ExTGDetectorConstructionWithCuts::Construct(), ExTGDetectorConstructionWithSD::Construct(), G4tgbDetectorConstruction::Construct(), G4tgbDetectorBuilder::ConstructDetector(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), EICG4dRICHDetector::ConstructMe(), ExTGDetectorConstructionWithSD::ConstructSDandField(), EICG4dRICHOptics::EICG4dRICHOptics(), and G4tgbVolume::FindOrConstructG4Solid().
const std::multimap< G4String, G4VSolid* >& G4tgbVolumeMgr::GetSolids () const inline
Definition at line 130 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 130 of file G4tgbVolumeMgr.hh
References theSolids.
G4LogicalVolume * G4tgbVolumeMgr::GetTopLogVol ()
Definition at line 298 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 298 of file G4tgbVolumeMgr.cc
References FatalException, G4cout, G4endl, G4Exception(), G4LogicalVolume::GetName(), G4tgrMessenger::GetVerboseLevel(), and theLVInvTree.
Referenced by DumpG4LogVolTree(), and GetTopPhysVol().
G4VPhysicalVolume * G4tgbVolumeMgr::GetTopPhysVol ()
Definition at line 280 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 280 of file G4tgbVolumeMgr.cc
References G4cout, G4endl, G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), GetTopLogVol(), G4tgrMessenger::GetVerboseLevel(), second, and thePVs.
Referenced by G4tgbDetectorBuilder::ConstructDetector(), DumpG4PhysVolTree(), and DumpSummary().
G4VPhysicalVolume * G4tgbVolumeMgr::ReadAndConstructDetector ()
Definition at line 91 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 91 of file G4tgbVolumeMgr.cc
References G4tgbDetectorBuilder::ConstructDetector(), G4tgbDetectorBuilder::ReadDetector(), and theDetectorBuilder.
Referenced by ExTGDetectorConstruction::Construct(), ExTGDetectorConstructionWithSD::Construct(), ExTGDetectorConstructionWithCpp::Construct(), and EICG4dRICHDetector::ConstructMe().
void G4tgbVolumeMgr::RegisterChildParentLVs (const G4LogicalVolume * logvol, const G4LogicalVolume * parentLV)
Definition at line 138 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 138 of file G4tgbVolumeMgr.cc
References theLVInvTree, and theLVTree.
Referenced by G4tgbVolume::ConstructG4Volumes().
void G4tgbVolumeMgr::RegisterMe (const G4tgbVolume * vol)
Definition at line 99 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 99 of file G4tgbVolumeMgr.cc
References G4tgbVolume::GetName(), and theVolumeList.
Referenced by G4tgbVolume::ConstructG4Volumes(), and CopyVolumes().
void G4tgbVolumeMgr::RegisterMe (const G4VSolid * solid)
Definition at line 107 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 107 of file G4tgbVolumeMgr.cc
References G4VSolid::GetName(), and theSolids.
void G4tgbVolumeMgr::RegisterMe (const G4LogicalVolume * lv)
Definition at line 115 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 115 of file G4tgbVolumeMgr.cc
References G4cout, G4endl, G4LogicalVolume::GetName(), G4tgrMessenger::GetVerboseLevel(), and theLVs.
void G4tgbVolumeMgr::RegisterMe (const G4VPhysicalVolume * pv)
Definition at line 130 of file G4tgbVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 130 of file G4tgbVolumeMgr.cc
References G4VPhysicalVolume::GetName(), and thePVs.
void G4tgbVolumeMgr::SetDetectorBuilder (G4tgbDetectorBuilder * db) inline
Definition at line 132 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 132 of file G4tgbVolumeMgr.hh
References Acts::Test::db, and theDetectorBuilder.
Referenced by ExTGDetectorConstructionWithCuts::Construct().
Member Data Documentation
G4tgbDetectorBuilder* G4tgbVolumeMgr::theDetectorBuilder private
Definition at line 167 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 167 of file G4tgbVolumeMgr.hh
Referenced by G4tgbVolumeMgr(), GetDetectorBuilder(), ReadAndConstructDetector(), SetDetectorBuilder(), and ~G4tgbVolumeMgr().
G4ThreadLocal G4tgbVolumeMgr * G4tgbVolumeMgr::theInstance = 0 static private
Definition at line 139 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 139 of file G4tgbVolumeMgr.hh
Referenced by GetInstance(), and ~G4tgbVolumeMgr().
G4mlvlv G4tgbVolumeMgr::theLVInvTree private
Definition at line 156 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 156 of file G4tgbVolumeMgr.hh
Referenced by GetTopLogVol(), and RegisterChildParentLVs().
G4mmslv G4tgbVolumeMgr::theLVs private
Definition at line 148 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 148 of file G4tgbVolumeMgr.hh
Referenced by DumpSummary(), FindG4LogVol(), and RegisterMe().
G4mlvlv G4tgbVolumeMgr::theLVTree private
Definition at line 153 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 153 of file G4tgbVolumeMgr.hh
Referenced by RegisterChildParentLVs().
G4mpvpv G4tgbVolumeMgr::thePVInvTree private
Definition at line 163 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 163 of file G4tgbVolumeMgr.hh
G4mmspv G4tgbVolumeMgr::thePVs private
Definition at line 150 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 150 of file G4tgbVolumeMgr.hh
Referenced by DumpSummary(), FindG4PhysVol(), GetTopPhysVol(), and RegisterMe().
G4mpvpv G4tgbVolumeMgr::thePVTree private
Definition at line 160 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 160 of file G4tgbVolumeMgr.hh
G4mmssol G4tgbVolumeMgr::theSolids private
Definition at line 145 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 145 of file G4tgbVolumeMgr.hh
Referenced by DumpG4SolidList(), DumpSummary(), FindG4Solid(), GetSolids(), and RegisterMe().
G4mssvol G4tgbVolumeMgr::theVolumeList private
Definition at line 141 of file G4tgbVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 141 of file G4tgbVolumeMgr.hh
Referenced by FindVolume(), and RegisterMe().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbVolumeMgr.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbVolumeMgr.cc