ECCE @ EIC Software: PHG4TTLSteppingAction Class Reference
PHG4TTLSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/PHG4TTLSteppingAction.h>
Public Member Functions
PHG4TTLSteppingAction (PHG4TTLDetector *)
constructor
~PHG4TTLSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetLGADResolution (double lgadReso)
void SetNPhiModules (double nPhimod)
void SetZPositionFwd (double zpos)
void SetIsForwardTTL (bool isfwd)
void CalculateSensorHitIndices (G4StepPoint *prePoint, int &module_ret, int &layer, int &sensor_0, int &sensor_1, int &j, int &k, TVector3 &sensorposition)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4TTLDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
PHG4Shower * saveshower
int layer_id
bool _isFwd_TTL
double _N_phi_modules
double _z_pos_TTL
double _sensor_resolution_x
double _sensor_resolution_y
Detailed Description
Definition at line 43 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4TTLSteppingAction.h
Constructor & Destructor Documentation
PHG4TTLSteppingAction::PHG4TTLSteppingAction (PHG4TTLDetector * detector)
constructor
Definition at line 8 of file PHG4TTLSteppingAction.cc.
View newest version in sPHENIX GitHub at line 8 of file PHG4TTLSteppingAction.cc
PHG4TTLSteppingAction::~PHG4TTLSteppingAction () override
destructor
Definition at line 23 of file PHG4TTLSteppingAction.cc.
View newest version in sPHENIX GitHub at line 23 of file PHG4TTLSteppingAction.cc
References hit.
Member Function Documentation
void PHG4TTLSteppingAction::CalculateSensorHitIndices (G4StepPoint * prePoint, int & module_ret, int & layer, int & sensor_0, int & sensor_1, int & j, int & k, TVector3 & sensorposition)
Definition at line 192 of file PHG4TTLSteppingAction.cc.
View newest version in sPHENIX GitHub at line 192 of file PHG4TTLSteppingAction.cc
References _isFwd_TTL, _N_phi_modules, _sensor_resolution_x, _sensor_resolution_y, _z_pos_TTL, cm, e, G4StepPoint::GetPosition(), int(), M_PI, mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by UserSteppingAction().
void PHG4TTLSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 263 of file PHG4TTLSteppingAction.cc.
View newest version in sPHENIX GitHub at line 263 of file PHG4TTLSteppingAction.cc
References detector_, PHG4Detector::GetName(), hits_, and PHG4TTLDetector::SuperDetector().
void PHG4TTLSteppingAction::SetIsForwardTTL (bool isfwd) inline
Definition at line 67 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4TTLSteppingAction.h
References _isFwd_TTL.
Referenced by PHG4TTLDetector::BuildBarrelTTL(), and PHG4TTLDetector::BuildForwardTTL().
void PHG4TTLSteppingAction::SetLGADResolution (double lgadReso) inline
Definition at line 57 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4TTLSteppingAction.h
References _sensor_resolution_x, and _sensor_resolution_y.
void PHG4TTLSteppingAction::SetNPhiModules (double nPhimod) inline
Definition at line 61 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4TTLSteppingAction.h
References _N_phi_modules.
Referenced by PHG4TTLDetector::BuildBarrelTTL(), and PHG4TTLDetector::BuildForwardTTL().
void PHG4TTLSteppingAction::SetZPositionFwd (double zpos) inline
Definition at line 64 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4TTLSteppingAction.h
References _z_pos_TTL, and BTOF::zpos.
Referenced by PHG4TTLDetector::BuildForwardTTL().
bool PHG4TTLSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 33 of file PHG4TTLSteppingAction.cc.
View newest version in sPHENIX GitHub at line 33 of file PHG4TTLSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), CalculateSensorHitIndices(), cm, detector_, edep, fAtRestDoItProc, fGeomBoundary, fStopAndKill, fUndefined, fWorldBoundary, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), G4StepPoint::GetGlobalTime(), PHG4HitContainer::GetID(), G4Step::GetNonIonizingEnergyDeposit(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetTrackLength(), G4Track::GetTrackStatus(), G4Track::GetUserInformation(), G4VTouchable::GetVolume(), GeV, hit, hits_, PHG4TTLDetector::IsInSectorActive(), G4TTL::layer, layer_id, nanosecond, G4InuclParticleNames::pp, PHG4Hit::Reset(), saveshower, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_i(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_index_l(), PHG4Hit::set_local_x(), PHG4Hit::set_local_y(), PHG4Hit::set_local_z(), PHG4Hit::set_path_length(), PHG4Hit::set_shower_id(), PHG4Hit::set_strip_y_index(), PHG4Hit::set_strip_z_index(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), Acts::Test::volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
bool PHG4TTLSteppingAction::_isFwd_TTL private
Definition at line 82 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 82 of file PHG4TTLSteppingAction.h
Referenced by CalculateSensorHitIndices(), and SetIsForwardTTL().
double PHG4TTLSteppingAction::_N_phi_modules private
Definition at line 83 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 83 of file PHG4TTLSteppingAction.h
Referenced by CalculateSensorHitIndices(), and SetNPhiModules().
double PHG4TTLSteppingAction::_sensor_resolution_x private
Definition at line 85 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 85 of file PHG4TTLSteppingAction.h
Referenced by CalculateSensorHitIndices(), and SetLGADResolution().
double PHG4TTLSteppingAction::_sensor_resolution_y private
Definition at line 86 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 86 of file PHG4TTLSteppingAction.h
Referenced by CalculateSensorHitIndices(), and SetLGADResolution().
double PHG4TTLSteppingAction::_z_pos_TTL private
Definition at line 84 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 84 of file PHG4TTLSteppingAction.h
Referenced by CalculateSensorHitIndices(), and SetZPositionFwd().
PHG4TTLDetector* PHG4TTLSteppingAction::detector_ private
pointer to the detector
Definition at line 74 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4TTLSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4TTLSteppingAction::hit private
Definition at line 78 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 78 of file PHG4TTLSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4TTLSteppingAction().
PHG4HitContainer* PHG4TTLSteppingAction::hits_ private
pointer to hit container
Definition at line 77 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4TTLSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4TTLSteppingAction::layer_id private
Definition at line 81 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 81 of file PHG4TTLSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4TTLSteppingAction::saveshower private
Definition at line 79 of file PHG4TTLSteppingAction.h.
View newest version in sPHENIX GitHub at line 79 of file PHG4TTLSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/PHG4TTLSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4ttl/PHG4TTLSteppingAction.cc