ECCE @ EIC Software: G4HadronicDeveloperParameters Class Reference
G4HadronicDeveloperParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadronicDeveloperParameters.hh>
Public Member Functions
G4bool Set (const std::string name, const G4bool)
G4bool Set (const std::string name, const G4int)
G4bool Set (const std::string name, const G4double)
G4bool GetDefault (const std::string name, G4bool &value)
G4bool GetDefault (const std::string name, G4int &value)
G4bool GetDefault (const std::string name, G4double &value)
G4bool Get (const std::string name, G4bool &value)
G4bool Get (const std::string name, G4int &value)
G4bool Get (const std::string name, G4double &value)
G4bool DeveloperGet (const std::string name, G4bool &value)
G4bool DeveloperGet (const std::string name, G4int &value)
G4bool DeveloperGet (const std::string name, G4double &value)
void Dump (const std::string name)
G4bool SetDefault (const std::string name, const G4bool value)
G4bool SetDefault (const std::string name, const G4int value, G4int lower_limit=-INT_MAX, G4int upper_limit=INT_MAX)
G4bool SetDefault (const std::string name, const G4double value, G4double lower_limit=-DBL_MAX, G4double upper_limit=DBL_MAX)
Static Public Member Functions
static
G4HadronicDeveloperParameters & GetInstance ()
Private Member Functions
G4HadronicDeveloperParameters ()
G4HadronicDeveloperParameters (const G4HadronicDeveloperParameters &)
G4HadronicDeveloperParameters & operator= (const G4HadronicDeveloperParameters &)
G4bool get (const std::string name, G4bool &value, G4bool check_change=false)
G4bool get (const std::string name, G4int &value, G4bool check_change=false)
G4bool get (const std::string name, G4double &value, G4bool check_change=false)
G4bool check_value_within_limits (std::pair< const G4double, const G4double > &, G4double)
G4bool check_value_within_limits (std::pair< const G4int, const G4int > &, G4int)
void issue_no_param (const std::string &name)
void issue_has_changed (const std::string &name)
void issue_non_eligible_value (const std::string &name)
void issue_is_already_defined (const std::string &name)
void issue_is_modified (const std::string &name)
Private Attributes
std::map< std::string, G4bool > b_values
std::map< std::string, const
G4bool > b_defaults
std::map< std::string, G4int > i_values
std::map< std::string, const
G4int > i_defaults
std::map< std::string,
std::pair< const G4int, const
G4int > > i_limits
std::map< std::string, G4double > values
std::map< std::string, const
G4double > defaults
std::map< std::string,
std::pair< const G4double,
const G4double > > limits
Detailed Description
Definition at line 36 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 36 of file G4HadronicDeveloperParameters.hh
Constructor & Destructor Documentation
G4HadronicDeveloperParameters::G4HadronicDeveloperParameters () private
Definition at line 33 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 33 of file G4HadronicDeveloperParameters.cc
G4HadronicDeveloperParameters::G4HadronicDeveloperParameters (const G4HadronicDeveloperParameters &) private
Definition at line 36 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 36 of file G4HadronicDeveloperParameters.cc
Member Function Documentation
G4bool G4HadronicDeveloperParameters::check_value_within_limits (std::pair< const G4double, const G4double > & alimits, G4double value) private
Definition at line 293 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 293 of file G4HadronicDeveloperParameters.cc
Referenced by Set().
G4bool G4HadronicDeveloperParameters::check_value_within_limits (std::pair< const G4int, const G4int > & alimits, G4int value) private
Definition at line 301 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 301 of file G4HadronicDeveloperParameters.cc
G4bool G4HadronicDeveloperParameters::DeveloperGet (const std::string name, G4bool & value)
Definition at line 242 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 242 of file G4HadronicDeveloperParameters.cc
References true.
Referenced by G4FTFParamCollBaryonProj::G4FTFParamCollBaryonProj(), G4FTFParamCollMesonProj::G4FTFParamCollMesonProj(), G4FTFParamCollPionProj::G4FTFParamCollPionProj(), and G4CascadeParameters::Initialize().
G4bool G4HadronicDeveloperParameters::DeveloperGet (const std::string name, G4int & value)
Definition at line 217 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 217 of file G4HadronicDeveloperParameters.cc
References true.
G4bool G4HadronicDeveloperParameters::DeveloperGet (const std::string name, G4double & value)
Definition at line 192 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 192 of file G4HadronicDeveloperParameters.cc
References true.
void G4HadronicDeveloperParameters::Dump (const std::string name)
Definition at line 263 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 263 of file G4HadronicDeveloperParameters.cc
References b_defaults, b_values, defaults, G4cout, G4endl, i_defaults, i_limits, i_values, issue_no_param(), limits, and values.
G4bool G4HadronicDeveloperParameters::Get (const std::string name, G4bool & value)
Definition at line 238 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 238 of file G4HadronicDeveloperParameters.cc
G4bool G4HadronicDeveloperParameters::Get (const std::string name, G4int & value)
Definition at line 213 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 213 of file G4HadronicDeveloperParameters.cc
G4bool G4HadronicDeveloperParameters::Get (const std::string name, G4double & value)
Definition at line 188 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 188 of file G4HadronicDeveloperParameters.cc
G4bool G4HadronicDeveloperParameters::get (const std::string name, G4bool & value, G4bool check_change = false) private
Definition at line 196 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 196 of file G4HadronicDeveloperParameters.cc
References b_defaults, b_values, issue_is_modified(), issue_no_param(), and it.
G4bool G4HadronicDeveloperParameters::get (const std::string name, G4int & value, G4bool check_change = false) private
Definition at line 221 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 221 of file G4HadronicDeveloperParameters.cc
References i_defaults, i_values, issue_is_modified(), issue_no_param(), and it.
G4bool G4HadronicDeveloperParameters::get (const std::string name, G4double & value, G4bool check_change = false) private
Definition at line 246 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 246 of file G4HadronicDeveloperParameters.cc
References defaults, issue_is_modified(), issue_no_param(), it, and values.
G4bool G4HadronicDeveloperParameters::GetDefault (const std::string name, G4bool & value)
Definition at line 149 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 149 of file G4HadronicDeveloperParameters.cc
References b_defaults, issue_no_param(), and it.
G4bool G4HadronicDeveloperParameters::GetDefault (const std::string name, G4int & value)
Definition at line 162 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 162 of file G4HadronicDeveloperParameters.cc
References i_defaults, issue_no_param(), and it.
G4bool G4HadronicDeveloperParameters::GetDefault (const std::string name, G4double & value)
Definition at line 175 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 175 of file G4HadronicDeveloperParameters.cc
References defaults, issue_no_param(), and it.
G4HadronicDeveloperParameters & G4HadronicDeveloperParameters::GetInstance (void) static
Definition at line 28 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 28 of file G4HadronicDeveloperParameters.cc
References instance.
void G4HadronicDeveloperParameters::issue_has_changed (const std::string & name) private
Definition at line 316 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 316 of file G4HadronicDeveloperParameters.cc
References FatalException, and G4Exception().
Referenced by Set().
void G4HadronicDeveloperParameters::issue_is_already_defined (const std::string & name) private
Definition at line 328 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 328 of file G4HadronicDeveloperParameters.cc
References FatalException, and G4Exception().
Referenced by SetDefault().
void G4HadronicDeveloperParameters::issue_is_modified (const std::string & name) private
Definition at line 334 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 334 of file G4HadronicDeveloperParameters.cc
References G4Exception(), and JustWarning.
Referenced by get().
void G4HadronicDeveloperParameters::issue_no_param (const std::string & name) private
Definition at line 309 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 309 of file G4HadronicDeveloperParameters.cc
References FatalException, and G4Exception().
Referenced by Dump(), get(), GetDefault(), and Set().
void G4HadronicDeveloperParameters::issue_non_eligible_value (const std::string & name) private
Definition at line 322 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 322 of file G4HadronicDeveloperParameters.cc
References FatalException, and G4Exception().
Referenced by Set().
G4HadronicDeveloperParameters& G4HadronicDeveloperParameters::operator= (const G4HadronicDeveloperParameters &) private
G4bool G4HadronicDeveloperParameters::Set (const std::string name, const G4bool value)
Definition at line 83 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 83 of file G4HadronicDeveloperParameters.cc
References b_defaults, b_values, issue_has_changed(), issue_no_param(), and it.
G4bool G4HadronicDeveloperParameters::Set (const std::string name, const G4int value)
Definition at line 101 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 101 of file G4HadronicDeveloperParameters.cc
References check_value_within_limits(), i_defaults, i_limits, i_values, issue_has_changed(), issue_no_param(), issue_non_eligible_value(), and it.
G4bool G4HadronicDeveloperParameters::Set (const std::string name, const G4double value)
Definition at line 125 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 125 of file G4HadronicDeveloperParameters.cc
References check_value_within_limits(), defaults, issue_has_changed(), issue_no_param(), issue_non_eligible_value(), it, limits, and values.
G4bool G4HadronicDeveloperParameters::SetDefault (const std::string name, const G4bool value)
Definition at line 39 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HadronicDeveloperParameters.cc
References b_defaults, b_values, issue_is_already_defined(), and it.
Referenced by G4FTFSettingDefaultHDP::G4FTFSettingDefaultHDP().
G4bool G4HadronicDeveloperParameters::SetDefault (const std::string name, const G4int value, G4int lower_limit = -INT_MAX, G4int upper_limit = INT_MAX)
Definition at line 53 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 53 of file G4HadronicDeveloperParameters.cc
References i_defaults, i_limits, i_values, issue_is_already_defined(), and it.
G4bool G4HadronicDeveloperParameters::SetDefault (const std::string name, const G4double value, G4double lower_limit = -DBL_MAX, G4double upper_limit = DBL_MAX)
Definition at line 68 of file G4HadronicDeveloperParameters.cc.
View newest version in sPHENIX GitHub at line 68 of file G4HadronicDeveloperParameters.cc
References defaults, issue_is_already_defined(), it, limits, and values.
Member Data Documentation
std::map<std::string,const G4bool> G4HadronicDeveloperParameters::b_defaults private
Definition at line 74 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), get(), GetDefault(), Set(), and SetDefault().
std::map<std::string,G4bool> G4HadronicDeveloperParameters::b_values private
Definition at line 73 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 73 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), get(), Set(), and SetDefault().
std::map<std::string,const G4double> G4HadronicDeveloperParameters::defaults private
Definition at line 81 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), get(), GetDefault(), Set(), and SetDefault().
std::map<std::string,const G4int> G4HadronicDeveloperParameters::i_defaults private
Definition at line 77 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), get(), GetDefault(), Set(), and SetDefault().
std::map<std::string,std::pair<const G4int,const G4int> > G4HadronicDeveloperParameters::i_limits private
Definition at line 78 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), Set(), and SetDefault().
std::map<std::string,G4int> G4HadronicDeveloperParameters::i_values private
Definition at line 76 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), get(), Set(), and SetDefault().
std::map<std::string,std::pair<const G4double,const G4double> > G4HadronicDeveloperParameters::limits private
Definition at line 82 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), Set(), and SetDefault().
std::map<std::string,G4double> G4HadronicDeveloperParameters::values private
Definition at line 80 of file G4HadronicDeveloperParameters.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HadronicDeveloperParameters.hh
Referenced by Dump(), get(), Set(), and SetDefault().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadronicDeveloperParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4HadronicDeveloperParameters.cc