ECCE @ EIC Software: G4NuclNuclDiffuseElastic Class Reference
G4NuclNuclDiffuseElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4NuclNuclDiffuseElastic.hh>
Public Member Functions
G4NuclNuclDiffuseElastic ()
virtual ~G4NuclNuclDiffuseElastic ()
void Initialise ()
void InitialiseOnFly (G4double Z, G4double A)
void BuildAngleTable ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void SetPlabLowLimit (G4double value)
void SetHEModelLowLimit (G4double value)
void SetQModelLowLimit (G4double value)
void SetLowestEnergyLimit (G4double value)
void SetRecoilKinEnergyLimit (G4double value)
G4double SampleT (const G4ParticleDefinition *aParticle, G4double p, G4double A)
G4double SampleTableT (const G4ParticleDefinition *aParticle, G4double p, G4double Z, G4double A)
G4double SampleThetaCMS (const G4ParticleDefinition *aParticle, G4double p, G4double A)
G4double SampleCoulombMuCMS (const G4ParticleDefinition *aParticle, G4double p)
G4double SampleTableThetaCMS (const G4ParticleDefinition *aParticle, G4double p, G4double Z, G4double A)
G4double GetScatteringAngle (G4int iMomentum, G4int iAngle, G4double position)
G4double SampleThetaLab (const G4HadProjectile *aParticle, G4double tmass, G4double A)
G4double GetDiffuseElasticXsc (const G4ParticleDefinition *particle, G4double theta, G4double momentum, G4double A)
G4double GetInvElasticXsc (const G4ParticleDefinition *particle, G4double theta, G4double momentum, G4double A, G4double Z)
G4double GetDiffuseElasticSumXsc (const G4ParticleDefinition *particle, G4double theta, G4double momentum, G4double A, G4double Z)
G4double GetInvElasticSumXsc (const G4ParticleDefinition *particle, G4double tMand, G4double momentum, G4double A, G4double Z)
G4double IntegralElasticProb (const G4ParticleDefinition *particle, G4double theta, G4double momentum, G4double A)
G4double GetCoulombElasticXsc (const G4ParticleDefinition *particle, G4double theta, G4double momentum, G4double Z)
G4double GetRutherfordXsc (G4double theta)
G4double GetInvCoulombElasticXsc (const G4ParticleDefinition *particle, G4double tMand, G4double momentum, G4double A, G4double Z)
G4double GetCoulombTotalXsc (const G4ParticleDefinition *particle, G4double momentum, G4double Z)
G4double GetCoulombIntegralXsc (const G4ParticleDefinition *particle, G4double momentum, G4double Z, G4double theta1, G4double theta2)
G4double CalculateParticleBeta (const G4ParticleDefinition *particle, G4double momentum)
G4double CalculateZommerfeld (G4double beta, G4double Z1, G4double Z2)
G4double CalculateAm (G4double momentum, G4double n, G4double Z)
G4double CalculateNuclearRad (G4double A)
G4double ThetaCMStoThetaLab (const G4DynamicParticle *aParticle, G4double tmass, G4double thetaCMS)
G4double ThetaLabToThetaCMS (const G4DynamicParticle *aParticle, G4double tmass, G4double thetaLab)
void TestAngleTable (const G4ParticleDefinition *theParticle, G4double partMom, G4double Z, G4double A)
G4double BesselJzero (G4double z)
G4double BesselJone (G4double z)
G4double DampFactor (G4double z)
G4double BesselOneByArg (G4double z)
G4double GetDiffElasticProb (G4double theta)
G4double GetDiffElasticSumProb (G4double theta)
G4double GetDiffElasticSumProbA (G4double alpha)
G4double GetIntegrandFunction (G4double theta)
G4double GetNuclearRadius ()
G4complex GammaLogarithm (G4complex xx)
G4complex GammaLogB2n (G4complex xx)
G4double GetErf (G4double x)
G4double GetCosHaPit2 (G4double t)
G4double GetSinHaPit2 (G4double t)
G4double GetCint (G4double x)
G4double GetSint (G4double x)
G4complex GetErfcComp (G4complex z, G4int nMax)
G4complex GetErfcSer (G4complex z, G4int nMax)
G4complex GetErfcInt (G4complex z)
G4complex GetErfComp (G4complex z, G4int nMax)
G4complex GetErfSer (G4complex z, G4int nMax)
G4double GetExpCos (G4double x)
G4double GetExpSin (G4double x)
G4complex GetErfInt (G4complex z)
G4double GetLegendrePol (G4int n, G4double x)
G4complex TestErfcComp (G4complex z, G4int nMax)
G4complex TestErfcSer (G4complex z, G4int nMax)
G4complex TestErfcInt (G4complex z)
G4complex CoulombAmplitude (G4double theta)
G4double CoulombAmplitudeMod2 (G4double theta)
void CalculateCoulombPhaseZero ()
G4double CalculateCoulombPhase (G4int n)
void CalculateRutherfordAnglePar ()
G4double ProfileNear (G4double theta)
G4double ProfileFar (G4double theta)
G4double Profile (G4double theta)
G4complex PhaseNear (G4double theta)
G4complex PhaseFar (G4double theta)
G4complex GammaLess (G4double theta)
G4complex GammaMore (G4double theta)
G4complex AmplitudeNear (G4double theta)
G4complex AmplitudeFar (G4double theta)
G4complex Amplitude (G4double theta)
G4double AmplitudeMod2 (G4double theta)
G4complex AmplitudeSim (G4double theta)
G4double AmplitudeSimMod2 (G4double theta)
G4double GetRatioSim (G4double theta)
G4double GetRatioGen (G4double theta)
G4double GetFresnelDiffuseXsc (G4double theta)
G4double GetFresnelIntegrandXsc (G4double alpha)
G4complex AmplitudeGla (G4double theta)
G4double AmplitudeGlaMod2 (G4double theta)
G4complex AmplitudeGG (G4double theta)
G4double AmplitudeGGMod2 (G4double theta)
void InitParameters (const G4ParticleDefinition *theParticle, G4double partMom, G4double Z, G4double A)
void InitDynParameters (const G4ParticleDefinition *theParticle, G4double partMom)
void InitParametersGla (const G4DynamicParticle *aParticle, G4double partMom, G4double Z, G4double A)
G4double GetHadronNucleonXscNS (G4ParticleDefinition *pParticle, G4double pTkin, G4ParticleDefinition *tParticle)
G4double CalcMandelstamS (const G4double mp, const G4double mt, const G4double Plab)
G4double GetProfileLambda ()
void SetProfileLambda (G4double pl)
void SetProfileDelta (G4double pd)
void SetProfileAlpha (G4double pa)
void SetCofLambda (G4double pa)
void SetCofAlpha (G4double pa)
void SetCofAlphaMax (G4double pa)
void SetCofAlphaCoulomb (G4double pa)
void SetCofDelta (G4double pa)
void SetCofPhase (G4double pa)
void SetCofFar (G4double pa)
void SetEtaRatio (G4double pa)
void SetMaxL (G4int l)
void SetNuclearRadiusCof (G4double r)
G4double GetCofAlphaMax ()
G4double GetCofAlphaCoulomb ()
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4ParticleDefinition * theDeuteron
G4ParticleDefinition * theAlpha
const G4ParticleDefinition * thePionPlus
const G4ParticleDefinition * thePionMinus
G4double lowEnergyRecoilLimit
G4double lowEnergyLimitHE
G4double lowEnergyLimitQ
G4double lowestEnergyLimit
G4double plabLowLimit
G4int fEnergyBin
G4int fAngleBin
G4PhysicsLogVector * fEnergyVector
G4PhysicsTable * fAngleTable
std::vector< G4PhysicsTable * > fAngleBank
std::vector< G4double > fElementNumberVector
std::vector< G4String > fElementNameVector
const G4ParticleDefinition * fParticle
G4double fWaveVector
G4double fAtomicWeight
G4double fAtomicNumber
G4double fNuclearRadius1
G4double fNuclearRadius2
G4double fNuclearRadius
G4double fNuclearRadiusSquare
G4double fNuclearRadiusCof
G4double fBeta
G4double fZommerfeld
G4double fRutherfordRatio
G4double fAm
G4bool fAddCoulomb
G4double fCoulombPhase0
G4double fHalfRutThetaTg
G4double fHalfRutThetaTg2
G4double fRutherfordTheta
G4double fProfileLambda
G4double fProfileDelta
G4double fProfileAlpha
G4double fCofLambda
G4double fCofAlpha
G4double fCofDelta
G4double fCofPhase
G4double fCofFar
G4double fCofAlphaMax
G4double fCofAlphaCoulomb
G4int fMaxL
G4double fSumSigma
G4double fEtaRatio
G4double fReZ
G4double fCoulombMuC
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 61 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 61 of file G4NuclNuclDiffuseElastic.hh
Constructor & Destructor Documentation
G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic ()
Definition at line 68 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 68 of file G4NuclNuclDiffuseElastic.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), fAddCoulomb, fAm, fAngleBin, fAngleTable, fAtomicNumber, fAtomicWeight, fBeta, fCofAlpha, fCofAlphaCoulomb, fCofAlphaMax, fCofDelta, fCofFar, fCofLambda, fCofPhase, fCoulombMuC, fCoulombPhase0, fEnergyBin, fEnergyVector, fEtaRatio, fHalfRutThetaTg, fHalfRutThetaTg2, fMaxL, fNuclearRadius, fNuclearRadius1, fNuclearRadius2, fNuclearRadiusCof, fNuclearRadiusSquare, fParticle, fProfileAlpha, fProfileDelta, fProfileLambda, fReZ, fRutherfordRatio, fRutherfordTheta, fSumSigma, fWaveVector, fZommerfeld, G4HadronicInteraction::GetMaxEnergy(), GeV, G4HadronicParameters::Instance(), keV, lowEnergyLimitHE, lowEnergyLimitQ, lowEnergyRecoilLimit, lowestEnergyLimit, MeV, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), plabLowLimit, G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAlpha, theDeuteron, G4HadronicInteraction::theMaxEnergy, G4HadronicInteraction::theMinEnergy, theNeutron, thePionMinus, thePionPlus, theProton, and G4HadronicInteraction::verboseLevel.
G4NuclNuclDiffuseElastic::~G4NuclNuclDiffuseElastic () virtual
Definition at line 130 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 130 of file G4NuclNuclDiffuseElastic.cc
References fAngleBank, fAngleTable, fEnergyVector, and it.
Member Function Documentation
G4complex G4NuclNuclDiffuseElastic::Amplitude (G4double theta) inline
Definition at line 978 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 978 of file G4NuclNuclDiffuseElastic.hh
References AmplitudeFar(), AmplitudeNear(), and fCofFar.
Referenced by AmplitudeMod2().
G4complex G4NuclNuclDiffuseElastic::AmplitudeFar (G4double theta) inline
Definition at line 964 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 964 of file G4NuclNuclDiffuseElastic.hh
References fProfileLambda, fWaveVector, PhaseFar(), CLHEP::pi, and ProfileFar().
Referenced by Amplitude().
G4complex G4NuclNuclDiffuseElastic::AmplitudeGG (G4double theta)
Definition at line 1691 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1691 of file G4NuclNuclDiffuseElastic.cc
References a, CoulombAmplitude(), fMaxL, fNuclearRadiusSquare, fSumSigma, fWaveVector, G4cout, G4endl, G4Exp(), n, CLHEP::pi, and CLHEP::twopi.
Referenced by AmplitudeGGMod2().
G4double G4NuclNuclDiffuseElastic::AmplitudeGGMod2 (G4double theta) inline
Definition at line 1069 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1069 of file G4NuclNuclDiffuseElastic.hh
References AmplitudeGG().
G4complex G4NuclNuclDiffuseElastic::AmplitudeGla (G4double theta)
Definition at line 1664 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1664 of file G4NuclNuclDiffuseElastic.cc
References b, CalculateCoulombPhase(), CoulombAmplitude(), fEtaRatio, fMaxL, fNuclearRadiusSquare, fSumSigma, fWaveVector, G4Exp(), GetLegendrePol(), n, and CLHEP::pi.
Referenced by AmplitudeGlaMod2().
G4double G4NuclNuclDiffuseElastic::AmplitudeGlaMod2 (G4double theta) inline
Definition at line 1058 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1058 of file G4NuclNuclDiffuseElastic.hh
References AmplitudeGla().
G4double G4NuclNuclDiffuseElastic::AmplitudeMod2 (G4double theta) inline
Definition at line 991 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 991 of file G4NuclNuclDiffuseElastic.hh
References Amplitude().
G4complex G4NuclNuclDiffuseElastic::AmplitudeNear (G4double theta)
Definition at line 1608 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1608 of file G4NuclNuclDiffuseElastic.cc
References CoulombAmplitude(), fProfileLambda, fRutherfordTheta, fWaveVector, GammaLess(), GammaMore(), PhaseNear(), CLHEP::pi, and ProfileNear().
Referenced by Amplitude().
G4complex G4NuclNuclDiffuseElastic::AmplitudeSim (G4double theta)
Definition at line 1633 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1633 of file G4NuclNuclDiffuseElastic.cc
References CoulombAmplitude(), fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, GetErfcInt(), and ProfileNear().
Referenced by AmplitudeSimMod2().
G4double G4NuclNuclDiffuseElastic::AmplitudeSimMod2 (G4double theta) inline
Definition at line 1046 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1046 of file G4NuclNuclDiffuseElastic.hh
References AmplitudeSim().
G4double G4NuclNuclDiffuseElastic::BesselJone (G4double z)
Definition at line 2085 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 2085 of file G4NuclNuclDiffuseElastic.cc
Referenced by BesselOneByArg(), GetDiffElasticProb(), GetDiffElasticSumProb(), and GetDiffElasticSumProbA().
G4double G4NuclNuclDiffuseElastic::BesselJzero (G4double z)
Definition at line 2033 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 2033 of file G4NuclNuclDiffuseElastic.cc
Referenced by GetDiffElasticProb(), GetDiffElasticSumProb(), and GetDiffElasticSumProbA().
G4double G4NuclNuclDiffuseElastic::BesselOneByArg (G4double z) inline
Definition at line 419 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 419 of file G4NuclNuclDiffuseElastic.hh
References BesselJone(), x, and x2.
Referenced by GetDiffElasticProb(), GetDiffElasticSumProb(), and GetDiffElasticSumProbA().
void G4NuclNuclDiffuseElastic::BuildAngleTable ()
Definition at line 1007 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1007 of file G4NuclNuclDiffuseElastic.cc
References Acts::Test::delta, fAddCoulomb, fAngleBin, fAngleTable, fCofAlphaCoulomb, fCofAlphaMax, fEnergyBin, fEnergyVector, fParticle, fRutherfordTheta, GetFresnelIntegrandXsc(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), InitDynParameters(), G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre10(), pi, G4PhysicsFreeVector::PutValue(), and sum.
Referenced by Initialise(), and InitialiseOnFly().
G4double G4NuclNuclDiffuseElastic::CalcMandelstamS (const G4double mp, const G4double mt, const G4double Plab) inline
Definition at line 1080 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1080 of file G4NuclNuclDiffuseElastic.hh
Referenced by GetHadronNucleonXscNS().
G4double G4NuclNuclDiffuseElastic::CalculateAm (G4double momentum, G4double n, G4double Z) inline
Definition at line 468 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 468 of file G4NuclNuclDiffuseElastic.hh
References G4Pow::A13(), CLHEP::Bohr_radius, fAm, G4Pow::GetInstance(), CLHEP::hbarc, k, and n.
Referenced by GetCoulombElasticXsc(), GetCoulombIntegralXsc(), GetCoulombTotalXsc(), GetDiffuseElasticSumXsc(), InitDynParameters(), InitParameters(), InitParametersGla(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::CalculateCoulombPhase (G4int n) inline
Definition at line 844 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 844 of file G4NuclNuclDiffuseElastic.hh
References fZommerfeld, GammaLogB2n(), and z.
Referenced by AmplitudeGla().
void G4NuclNuclDiffuseElastic::CalculateCoulombPhaseZero () inline
Definition at line 831 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 831 of file G4NuclNuclDiffuseElastic.hh
References fCoulombPhase0, fZommerfeld, GammaLogB2n(), and z.
Referenced by InitDynParameters(), InitParameters(), and InitParametersGla().
G4double G4NuclNuclDiffuseElastic::CalculateNuclearRad (G4double A) inline
Definition at line 483 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 483 of file G4NuclNuclDiffuseElastic.hh
References G4Pow::A13(), CLHEP::fermi, fNuclearRadiusCof, G4Pow::GetInstance(), and radius.
Referenced by GetDiffuseElasticSumXsc(), GetDiffuseElasticXsc(), Initialise(), InitialiseOnFly(), InitParameters(), InitParametersGla(), IntegralElasticProb(), SampleCoulombMuCMS(), SampleThetaCMS(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::CalculateParticleBeta (const G4ParticleDefinition * particle, G4double momentum) inline
Definition at line 441 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 441 of file G4NuclNuclDiffuseElastic.hh
References a, fBeta, G4ParticleDefinition::GetPDGMass(), and mass.
Referenced by GetCoulombElasticXsc(), GetCoulombIntegralXsc(), GetCoulombTotalXsc(), and GetDiffuseElasticSumXsc().
void G4NuclNuclDiffuseElastic::CalculateRutherfordAnglePar () inline
Definition at line 858 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 858 of file G4NuclNuclDiffuseElastic.hh
References fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, and fZommerfeld.
Referenced by InitDynParameters(), and InitParameters().
G4double G4NuclNuclDiffuseElastic::CalculateZommerfeld (G4double beta, G4double Z1, G4double Z2) inline
Definition at line 456 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 456 of file G4NuclNuclDiffuseElastic.hh
References CLHEP::fine_structure_const, and fZommerfeld.
Referenced by GetCoulombElasticXsc(), GetCoulombIntegralXsc(), GetCoulombTotalXsc(), GetDiffuseElasticSumXsc(), InitDynParameters(), InitParameters(), InitParametersGla(), and TestAngleTable().
G4complex G4NuclNuclDiffuseElastic::CoulombAmplitude (G4double theta) inline
Definition at line 797 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 797 of file G4NuclNuclDiffuseElastic.hh
References fAm, fCoulombPhase0, fWaveVector, fZommerfeld, G4Log(), and z.
Referenced by AmplitudeGG(), AmplitudeGla(), AmplitudeNear(), AmplitudeSim(), and CoulombAmplitudeMod2().
G4double G4NuclNuclDiffuseElastic::CoulombAmplitudeMod2 (G4double theta) inline
Definition at line 818 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 818 of file G4NuclNuclDiffuseElastic.hh
References CoulombAmplitude().
G4double G4NuclNuclDiffuseElastic::DampFactor (G4double z) inline
Definition at line 396 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 396 of file G4NuclNuclDiffuseElastic.hh
References f2, f3, and f4.
Referenced by GetDiffElasticProb(), GetDiffElasticSumProb(), and GetDiffElasticSumProbA().
G4complex G4NuclNuclDiffuseElastic::GammaLess (G4double theta)
Definition at line 1553 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1553 of file G4NuclNuclDiffuseElastic.cc
References a0, fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, GetErfcInt(), CLHEP::pi, and Acts::UnitConstants::u.
Referenced by AmplitudeNear().
G4complex G4NuclNuclDiffuseElastic::GammaLogarithm (G4complex xx)
Definition at line 2009 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 2009 of file G4NuclNuclDiffuseElastic.cc
References tmp, and z.
G4complex G4NuclNuclDiffuseElastic::GammaLogB2n (G4complex xx) inline
Definition at line 610 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 610 of file G4NuclNuclDiffuseElastic.hh
References G4Log(), CLHEP::twopi, z, z1, and z2.
Referenced by CalculateCoulombPhase(), and CalculateCoulombPhaseZero().
G4complex G4NuclNuclDiffuseElastic::GammaMore (G4double theta)
Definition at line 1581 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1581 of file G4NuclNuclDiffuseElastic.cc
References a0, fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, GetErfcInt(), CLHEP::pi, and Acts::UnitConstants::u.
Referenced by AmplitudeNear().
G4double G4NuclNuclDiffuseElastic::GetCint (G4double x) inline
Definition at line 767 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 767 of file G4NuclNuclDiffuseElastic.hh
References GetCosHaPit2(), and G4Integrator< T, F >::Legendre96().
Referenced by GetRatioGen(), and GetRatioSim().
G4double G4NuclNuclDiffuseElastic::GetCofAlphaCoulomb () inline
Definition at line 293 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 293 of file G4NuclNuclDiffuseElastic.hh
G4double G4NuclNuclDiffuseElastic::GetCofAlphaMax () inline
Definition at line 292 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 292 of file G4NuclNuclDiffuseElastic.hh
References fCofAlphaMax.
G4double G4NuclNuclDiffuseElastic::GetCosHaPit2 (G4double t) inline
Definition at line 195 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 195 of file G4NuclNuclDiffuseElastic.hh
References CLHEP::halfpi.
Referenced by GetCint().
G4double G4NuclNuclDiffuseElastic::GetCoulombElasticXsc (const G4ParticleDefinition * particle, G4double theta, G4double momentum, G4double Z) inline
Definition at line 514 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 514 of file G4NuclNuclDiffuseElastic.hh
References CalculateAm(), CalculateParticleBeta(), CalculateZommerfeld(), G4ParticleDefinition::GetPDGCharge(), CLHEP::hbarc, k, n, and z.
Referenced by GetInvCoulombElasticXsc().
G4double G4NuclNuclDiffuseElastic::GetCoulombIntegralXsc (const G4ParticleDefinition * particle, G4double momentum, G4double Z, G4double theta1, G4double theta2) inline
Definition at line 579 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 579 of file G4NuclNuclDiffuseElastic.hh
References c1, c2, CalculateAm(), CalculateParticleBeta(), CalculateZommerfeld(), G4ParticleDefinition::GetPDGCharge(), CLHEP::hbarc, k, n, CLHEP::twopi, and z.
G4double G4NuclNuclDiffuseElastic::GetCoulombTotalXsc (const G4ParticleDefinition * particle, G4double momentum, G4double Z) inline
Definition at line 553 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 553 of file G4NuclNuclDiffuseElastic.hh
References CLHEP::Bohr_radius, CalculateAm(), CalculateParticleBeta(), CalculateZommerfeld(), CLHEP::fermi, G4cout, G4endl, G4ParticleDefinition::GetPDGCharge(), CLHEP::hbarc, k, n, CLHEP::pi, and z.
G4double G4NuclNuclDiffuseElastic::GetDiffElasticProb (G4double theta)
Definition at line 397 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 397 of file G4NuclNuclDiffuseElastic.cc
References BesselJone(), BesselJzero(), BesselOneByArg(), DampFactor(), Acts::Test::delta, e1, e2, fermi, fNuclearRadius, fWaveVector, G4Exp(), G4InuclParticleNames::lambda, pi, and theta().
Referenced by GetDiffuseElasticXsc().
G4double G4NuclNuclDiffuseElastic::GetDiffElasticSumProb (G4double theta)
Definition at line 477 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 477 of file G4NuclNuclDiffuseElastic.cc
References BesselJone(), BesselJzero(), BesselOneByArg(), DampFactor(), Acts::Test::delta, e1, e2, fAddCoulomb, fAm, fermi, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, G4Exp(), G4InuclParticleNames::lambda, pi, theProton, and theta().
Referenced by GetDiffuseElasticSumXsc().
G4double G4NuclNuclDiffuseElastic::GetDiffElasticSumProbA (G4double alpha)
Definition at line 572 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 572 of file G4NuclNuclDiffuseElastic.cc
References BesselJone(), BesselJzero(), BesselOneByArg(), DampFactor(), Acts::Test::delta, e1, e2, fAddCoulomb, fAm, fermi, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, G4Exp(), G4InuclParticleNames::lambda, pi, theProton, and theta().
Referenced by GetIntegrandFunction().
G4double G4NuclNuclDiffuseElastic::GetDiffuseElasticSumXsc (const G4ParticleDefinition * particle, G4double theta, G4double momentum, G4double A, G4double Z)
Definition at line 261 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 261 of file G4NuclNuclDiffuseElastic.cc
References A(), CalculateAm(), CalculateNuclearRad(), CalculateParticleBeta(), CalculateZommerfeld(), fAddCoulomb, fAm, fAtomicNumber, fAtomicWeight, fBeta, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, GetDiffElasticSumProb(), G4ParticleDefinition::GetPDGCharge(), source.hepunit::hbarc, particle, theta(), Z, and z.
Referenced by GetInvElasticSumXsc().
G4double G4NuclNuclDiffuseElastic::GetDiffuseElasticXsc (const G4ParticleDefinition * particle, G4double theta, G4double momentum, G4double A)
Definition at line 190 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 190 of file G4NuclNuclDiffuseElastic.cc
References A(), CalculateNuclearRad(), fAddCoulomb, fAtomicWeight, fNuclearRadius, fParticle, fWaveVector, GetDiffElasticProb(), source.hepunit::hbarc, and particle.
Referenced by GetInvElasticXsc().
G4double G4NuclNuclDiffuseElastic::GetErf (G4double x) inline
Definition at line 631 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 631 of file G4NuclNuclDiffuseElastic.hh
References t, tmp, and z.
Referenced by GetErfComp(), and GetErfInt().
G4complex G4NuclNuclDiffuseElastic::GetErfcComp (G4complex z, G4int nMax) inline
Definition at line 652 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 652 of file G4NuclNuclDiffuseElastic.hh
References GetErfComp().
G4complex G4NuclNuclDiffuseElastic::GetErfcInt (G4complex z) inline
Definition at line 672 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 672 of file G4NuclNuclDiffuseElastic.hh
References GetErfInt().
Referenced by AmplitudeSim(), GammaLess(), and GammaMore().
G4complex G4NuclNuclDiffuseElastic::GetErfComp (G4complex z, G4int nMax)
Definition at line 1466 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1466 of file G4NuclNuclDiffuseElastic.cc
References kdfinder::abs(), G4Exp(), GetErf(), n, CLHEP::pi, x, and y.
Referenced by GetErfcComp(), and TestErfcComp().
G4complex G4NuclNuclDiffuseElastic::GetErfcSer (G4complex z, G4int nMax) inline
Definition at line 662 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 662 of file G4NuclNuclDiffuseElastic.hh
References GetErfSer().
G4complex G4NuclNuclDiffuseElastic::GetErfInt (G4complex z)
Definition at line 1527 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1527 of file G4NuclNuclDiffuseElastic.cc
References fReZ, GetErf(), GetExpCos(), GetExpSin(), G4Integrator< T, F >::Legendre96(), CLHEP::pi, x, and y.
Referenced by GetErfcInt(), and TestErfcInt().
G4complex G4NuclNuclDiffuseElastic::GetErfSer (G4complex z, G4int nMax) inline
Definition at line 719 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 719 of file G4NuclNuclDiffuseElastic.hh
References a, b, d, n, CLHEP::pi, sum, tmp, and z.
Referenced by GetErfcSer(), and TestErfcSer().
G4double G4NuclNuclDiffuseElastic::GetExpCos (G4double x) inline
Definition at line 742 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 742 of file G4NuclNuclDiffuseElastic.hh
References fReZ, and G4Exp().
Referenced by GetErfInt().
G4double G4NuclNuclDiffuseElastic::GetExpSin (G4double x) inline
Definition at line 753 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 753 of file G4NuclNuclDiffuseElastic.hh
References fReZ, and G4Exp().
Referenced by GetErfInt().
G4double G4NuclNuclDiffuseElastic::GetFresnelDiffuseXsc (G4double theta) inline
Definition at line 1023 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1023 of file G4NuclNuclDiffuseElastic.hh
References GetRatioGen(), GetRutherfordXsc(), and ratio.
Referenced by GetFresnelIntegrandXsc().
G4double G4NuclNuclDiffuseElastic::GetFresnelIntegrandXsc (G4double alpha) inline
Definition at line 1035 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1035 of file G4NuclNuclDiffuseElastic.hh
References GetFresnelDiffuseXsc(), and theta().
Referenced by BuildAngleTable().
G4double G4NuclNuclDiffuseElastic::GetHadronNucleonXscNS (G4ParticleDefinition * pParticle, G4double pTkin, G4ParticleDefinition * tParticle)
Definition at line 1862 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1862 of file G4NuclNuclDiffuseElastic.cc
References CalcMandelstamS(), fEtaRatio, G4cout, G4endl, G4Log(), G4Pow::GetInstance(), G4ParticleDefinition::GetPDGMass(), CLHEP::GeV, CLHEP::millibarn, and G4Pow::powA().
Referenced by InitParametersGla().
G4double G4NuclNuclDiffuseElastic::GetIntegrandFunction (G4double theta)
Definition at line 668 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 668 of file G4NuclNuclDiffuseElastic.cc
References GetDiffElasticSumProbA().
Referenced by IntegralElasticProb(), SampleThetaCMS(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc (const G4ParticleDefinition * particle, G4double tMand, G4double momentum, G4double A, G4double Z)
Definition at line 348 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 348 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), GetCoulombElasticXsc(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4He3::He3(), CLHEP::Hep3Vector::mag(), pi, theAlpha, theDeuteron, theProton, G4Triton::Triton(), and CLHEP::HepLorentzVector::vect().
G4double G4NuclNuclDiffuseElastic::GetInvElasticSumXsc (const G4ParticleDefinition * particle, G4double tMand, G4double momentum, G4double A, G4double Z)
Definition at line 296 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 296 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), GetDiffuseElasticSumXsc(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4He3::He3(), CLHEP::Hep3Vector::mag(), pi, theAlpha, theDeuteron, theProton, G4Triton::Triton(), and CLHEP::HepLorentzVector::vect().
G4double G4NuclNuclDiffuseElastic::GetInvElasticXsc (const G4ParticleDefinition * particle, G4double theta, G4double momentum, G4double A, G4double Z)
Definition at line 211 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 211 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), GetDiffuseElasticXsc(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4He3::He3(), CLHEP::Hep3Vector::mag(), pi, theAlpha, theDeuteron, theProton, G4Triton::Triton(), and CLHEP::HepLorentzVector::vect().
G4double G4NuclNuclDiffuseElastic::GetLegendrePol (G4int n, G4double x)
Definition at line 1440 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1440 of file G4NuclNuclDiffuseElastic.cc
References epsilon(), CLHEP::pi, and x.
Referenced by AmplitudeGla().
G4double G4NuclNuclDiffuseElastic::GetNuclearRadius () inline
Definition at line 185 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 185 of file G4NuclNuclDiffuseElastic.hh
References fNuclearRadius.
G4double G4NuclNuclDiffuseElastic::GetProfileLambda () inline
Definition at line 274 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 274 of file G4NuclNuclDiffuseElastic.hh
References fProfileLambda.
G4double G4NuclNuclDiffuseElastic::GetRatioGen (G4double theta)
Definition at line 1972 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1972 of file G4NuclNuclDiffuseElastic.cc
References kdfinder::abs(), fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, GetCint(), GetSint(), CLHEP::pi, and Profile().
Referenced by GetFresnelDiffuseXsc().
G4double G4NuclNuclDiffuseElastic::GetRatioSim (G4double theta) inline
Definition at line 1003 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 1003 of file G4NuclNuclDiffuseElastic.hh
References fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, GetCint(), GetSint(), and CLHEP::pi.
G4double G4NuclNuclDiffuseElastic::GetRutherfordXsc (G4double theta) inline
Definition at line 537 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 537 of file G4NuclNuclDiffuseElastic.hh
References fAm, and fRutherfordRatio.
Referenced by GetFresnelDiffuseXsc().
G4double G4NuclNuclDiffuseElastic::GetScatteringAngle (G4int iMomentum, G4int iAngle, G4double position)
Definition at line 1086 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1086 of file G4NuclNuclDiffuseElastic.cc
References fAngleTable, G4UniformRand, x1, x2, y1, and y2.
Referenced by SampleTableThetaCMS().
G4double G4NuclNuclDiffuseElastic::GetSinHaPit2 (G4double t) inline
Definition at line 196 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 196 of file G4NuclNuclDiffuseElastic.hh
References CLHEP::halfpi.
Referenced by GetSint().
G4double G4NuclNuclDiffuseElastic::GetSint (G4double x) inline
Definition at line 782 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 782 of file G4NuclNuclDiffuseElastic.hh
References GetSinHaPit2(), and G4Integrator< T, F >::Legendre96().
Referenced by GetRatioGen(), and GetRatioSim().
void G4NuclNuclDiffuseElastic::InitDynParameters (const G4ParticleDefinition * theParticle, G4double partMom)
Definition at line 1767 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1767 of file G4NuclNuclDiffuseElastic.cc
References a, CalculateAm(), CalculateCoulombPhaseZero(), CalculateRutherfordAnglePar(), CalculateZommerfeld(), fAm, fAtomicNumber, fBeta, fCofAlpha, fCofDelta, fCofLambda, fNuclearRadius, fProfileAlpha, fProfileDelta, fProfileLambda, fRutherfordRatio, fWaveVector, fZommerfeld, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), CLHEP::hbarc, G4InuclParticleNames::lambda, and z.
Referenced by BuildAngleTable(), and SampleCoulombMuCMS().
void G4NuclNuclDiffuseElastic::Initialise ()
Definition at line 150 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 150 of file G4NuclNuclDiffuseElastic.cc
References BuildAngleTable(), CalculateNuclearRad(), fAngleBank, fAngleTable, fAtomicNumber, fAtomicWeight, fElementNameVector, fElementNumberVector, fNuclearRadius, fParticle, G4cout, G4endl, G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetBaryonNumber(), G4Element::GetElementTable(), G4Element::GetNumberOfElements(), G4NistManager::Instance(), and G4HadronicInteraction::verboseLevel.
void G4NuclNuclDiffuseElastic::InitialiseOnFly (G4double Z, G4double A)
Definition at line 978 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 978 of file G4NuclNuclDiffuseElastic.cc
References BuildAngleTable(), CalculateNuclearRad(), fAngleBank, fAngleTable, fAtomicNumber, fAtomicWeight, fElementNumberVector, fNuclearRadius, fParticle, G4cout, G4endl, G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetBaryonNumber(), G4NistManager::Instance(), G4HadronicInteraction::verboseLevel, and Z.
Referenced by SampleTableThetaCMS().
void G4NuclNuclDiffuseElastic::InitParameters (const G4ParticleDefinition * theParticle, G4double partMom, G4double Z, G4double A)
Definition at line 1722 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1722 of file G4NuclNuclDiffuseElastic.cc
References a, A(), CalculateAm(), CalculateCoulombPhaseZero(), CalculateNuclearRad(), CalculateRutherfordAnglePar(), CalculateZommerfeld(), fAm, fAtomicNumber, fAtomicWeight, fBeta, fCofAlpha, fCofDelta, fCofLambda, fNuclearRadius, fNuclearRadius1, fNuclearRadius2, fProfileAlpha, fProfileDelta, fProfileLambda, fRutherfordRatio, fWaveVector, fZommerfeld, G4cout, G4endl, G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), CLHEP::hbarc, G4InuclParticleNames::lambda, Z, and z.
void G4NuclNuclDiffuseElastic::InitParametersGla (const G4DynamicParticle * aParticle, G4double partMom, G4double Z, G4double A)
Definition at line 1802 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1802 of file G4NuclNuclDiffuseElastic.cc
References a, A(), CalculateAm(), CalculateCoulombPhaseZero(), CalculateNuclearRad(), CalculateZommerfeld(), fAm, fAtomicNumber, fAtomicWeight, fBeta, fMaxL, fNuclearRadius1, fNuclearRadius2, fNuclearRadiusSquare, fSumSigma, fWaveVector, fZommerfeld, G4cout, G4endl, G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), GetHadronNucleonXscNS(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), CLHEP::hbarc, CLHEP::millibarn, CLHEP::pi, theNeutron, theProton, Z, and z.
G4double G4NuclNuclDiffuseElastic::IntegralElasticProb (const G4ParticleDefinition * particle, G4double theta, G4double momentum, G4double A)
Definition at line 684 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 684 of file G4NuclNuclDiffuseElastic.cc
References A(), CalculateNuclearRad(), fAtomicWeight, fNuclearRadius, fParticle, fWaveVector, GetIntegrandFunction(), source.hepunit::hbarc, G4Integrator< T, F >::Legendre96(), and particle.
G4complex G4NuclNuclDiffuseElastic::PhaseFar (G4double theta) inline
Definition at line 945 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 945 of file G4NuclNuclDiffuseElastic.hh
References fCofPhase, fCoulombPhase0, fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, fZommerfeld, G4Log(), CLHEP::halfpi, CLHEP::pi, and z.
Referenced by AmplitudeFar().
G4complex G4NuclNuclDiffuseElastic::PhaseNear (G4double theta) inline
Definition at line 927 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 927 of file G4NuclNuclDiffuseElastic.hh
References fCofPhase, fCoulombPhase0, fHalfRutThetaTg, fHalfRutThetaTg2, fProfileLambda, fRutherfordTheta, fZommerfeld, G4Log(), CLHEP::halfpi, CLHEP::pi, and z.
Referenced by AmplitudeNear().
G4double G4NuclNuclDiffuseElastic::Profile (G4double theta) inline
Definition at line 908 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 908 of file G4NuclNuclDiffuseElastic.hh
References kdfinder::abs(), fProfileDelta, fRutherfordTheta, CLHEP::pi, and theta().
Referenced by GetRatioGen().
G4double G4NuclNuclDiffuseElastic::ProfileFar (G4double theta) inline
Definition at line 892 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 892 of file G4NuclNuclDiffuseElastic.hh
References fProfileAlpha, fProfileDelta, fRutherfordTheta, G4Exp(), CLHEP::pi, and theta().
Referenced by AmplitudeFar().
G4double G4NuclNuclDiffuseElastic::ProfileNear (G4double theta) inline
Definition at line 871 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 871 of file G4NuclNuclDiffuseElastic.hh
References kdfinder::abs(), fProfileAlpha, fProfileDelta, fRutherfordTheta, G4Exp(), CLHEP::pi, and theta().
Referenced by AmplitudeNear(), and AmplitudeSim().
G4double G4NuclNuclDiffuseElastic::SampleCoulombMuCMS (const G4ParticleDefinition * aParticle, G4double p)
Definition at line 809 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 809 of file G4NuclNuclDiffuseElastic.cc
References CalculateNuclearRad(), fAm, fAtomicWeight, fCoulombMuC, fHalfRutThetaTg2, fNuclearRadius, fParticle, G4UniformRand, G4ParticleDefinition::GetBaryonNumber(), InitDynParameters(), and t.
Referenced by SampleInvariantT().
G4double G4NuclNuclDiffuseElastic::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) virtual
Reimplemented from G4HadronElastic.
Definition at line 777 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 777 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), fAtomicNumber, fAtomicWeight, fParticle, G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag(), SampleCoulombMuCMS(), t, and CLHEP::HepLorentzVector::vect().
G4double G4NuclNuclDiffuseElastic::SampleT (const G4ParticleDefinition * aParticle, G4double p, G4double A)
Definition at line 709 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 709 of file G4NuclNuclDiffuseElastic.cc
References SampleThetaCMS(), t, and theta().
Referenced by SampleThetaLab().
G4double G4NuclNuclDiffuseElastic::SampleTableT (const G4ParticleDefinition * aParticle, G4double p, G4double Z, G4double A)
Definition at line 840 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 840 of file G4NuclNuclDiffuseElastic.cc
References alpha, SampleTableThetaCMS(), and t.
G4double G4NuclNuclDiffuseElastic::SampleTableThetaCMS (const G4ParticleDefinition * aParticle, G4double p, G4double Z, G4double A)
Definition at line 855 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 855 of file G4NuclNuclDiffuseElastic.cc
References fAngleBank, fAngleBin, fAngleTable, fElementNumberVector, fEnergyBin, fEnergyVector, G4UniformRand, G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), GetScatteringAngle(), InitialiseOnFly(), and position.
Referenced by SampleTableT().
G4double G4NuclNuclDiffuseElastic::SampleThetaCMS (const G4ParticleDefinition * aParticle, G4double p, G4double A)
Definition at line 723 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 723 of file G4NuclNuclDiffuseElastic.cc
References A(), CalculateNuclearRad(), fAtomicWeight, fNuclearRadius, fParticle, fWaveVector, G4UniformRand, GetIntegrandFunction(), source.hepunit::hbarc, G4Integrator< T, F >::Legendre10(), G4Integrator< T, F >::Legendre96(), norm, particle, pi, G4INCL::DeJongSpin::shoot(), and sum.
Referenced by SampleT().
G4double G4NuclNuclDiffuseElastic::SampleThetaLab (const G4HadProjectile * aParticle, G4double tmass, G4double A)
Definition at line 1129 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1129 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalMomentum(), GeV, CLHEP::Hep3Vector::mag(), phi, SampleT(), t, CLHEP::Hep3Vector::theta(), theta(), twopi, v1, CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4NuclNuclDiffuseElastic::SetCofAlpha (G4double pa) inline
Definition at line 281 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 281 of file G4NuclNuclDiffuseElastic.hh
References fCofAlpha.
void G4NuclNuclDiffuseElastic::SetCofAlphaCoulomb (G4double pa) inline
Definition at line 283 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 283 of file G4NuclNuclDiffuseElastic.hh
References fCofAlphaCoulomb.
void G4NuclNuclDiffuseElastic::SetCofAlphaMax (G4double pa) inline
Definition at line 282 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 282 of file G4NuclNuclDiffuseElastic.hh
References fCofAlphaMax.
void G4NuclNuclDiffuseElastic::SetCofDelta (G4double pa) inline
Definition at line 285 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 285 of file G4NuclNuclDiffuseElastic.hh
References fCofDelta.
void G4NuclNuclDiffuseElastic::SetCofFar (G4double pa) inline
Definition at line 287 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 287 of file G4NuclNuclDiffuseElastic.hh
References fCofFar.
void G4NuclNuclDiffuseElastic::SetCofLambda (G4double pa) inline
Definition at line 279 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 279 of file G4NuclNuclDiffuseElastic.hh
References fCofLambda.
void G4NuclNuclDiffuseElastic::SetCofPhase (G4double pa) inline
Definition at line 286 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 286 of file G4NuclNuclDiffuseElastic.hh
References fCofPhase.
void G4NuclNuclDiffuseElastic::SetEtaRatio (G4double pa) inline
Definition at line 288 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 288 of file G4NuclNuclDiffuseElastic.hh
References fEtaRatio.
void G4NuclNuclDiffuseElastic::SetHEModelLowLimit (G4double value) inline
Definition at line 377 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 377 of file G4NuclNuclDiffuseElastic.hh
References lowEnergyLimitHE.
void G4NuclNuclDiffuseElastic::SetLowestEnergyLimit (G4double value) inline
Definition at line 387 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 387 of file G4NuclNuclDiffuseElastic.hh
References lowestEnergyLimit.
void G4NuclNuclDiffuseElastic::SetMaxL (G4int l) inline
Definition at line 289 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 289 of file G4NuclNuclDiffuseElastic.hh
References fMaxL.
void G4NuclNuclDiffuseElastic::SetNuclearRadiusCof (G4double r) inline
Definition at line 290 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 290 of file G4NuclNuclDiffuseElastic.hh
References fNuclearRadiusCof, and r.
void G4NuclNuclDiffuseElastic::SetPlabLowLimit (G4double value) inline
Definition at line 372 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 372 of file G4NuclNuclDiffuseElastic.hh
References plabLowLimit.
void G4NuclNuclDiffuseElastic::SetProfileAlpha (G4double pa) inline
Definition at line 278 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 278 of file G4NuclNuclDiffuseElastic.hh
References fProfileAlpha.
void G4NuclNuclDiffuseElastic::SetProfileDelta (G4double pd) inline
Definition at line 277 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 277 of file G4NuclNuclDiffuseElastic.hh
References fProfileDelta.
void G4NuclNuclDiffuseElastic::SetProfileLambda (G4double pl) inline
Definition at line 276 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 276 of file G4NuclNuclDiffuseElastic.hh
References fProfileLambda, and readPY::pl.
void G4NuclNuclDiffuseElastic::SetQModelLowLimit (G4double value) inline
Definition at line 382 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 382 of file G4NuclNuclDiffuseElastic.hh
References lowEnergyLimitQ.
void G4NuclNuclDiffuseElastic::SetRecoilKinEnergyLimit (G4double value) inline
Definition at line 367 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 367 of file G4NuclNuclDiffuseElastic.hh
References lowEnergyRecoilLimit.
void G4NuclNuclDiffuseElastic::TestAngleTable (const G4ParticleDefinition * theParticle, G4double partMom, G4double Z, G4double A)
Definition at line 1337 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1337 of file G4NuclNuclDiffuseElastic.cc
References a, A(), G4Integrator< T, F >::AdaptiveGauss(), CalculateAm(), CalculateNuclearRad(), CalculateZommerfeld(), degree, epsilon(), fAddCoulomb, fAm, fAngleBank, fAngleBin, fAngleTable, fAtomicNumber, fAtomicWeight, fBeta, fElementNumberVector, fEnergyBin, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, G4cout, G4endl, GetIntegrandFunction(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre10(), G4Integrator< T, F >::Legendre96(), G4PhysicsFreeVector::PutValue(), Z, and z.
G4complex G4NuclNuclDiffuseElastic::TestErfcComp (G4complex z, G4int nMax) inline
Definition at line 683 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 683 of file G4NuclNuclDiffuseElastic.hh
References GetErfComp(), and w.
G4complex G4NuclNuclDiffuseElastic::TestErfcInt (G4complex z) inline
Definition at line 707 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 707 of file G4NuclNuclDiffuseElastic.hh
References GetErfInt(), and w.
G4complex G4NuclNuclDiffuseElastic::TestErfcSer (G4complex z, G4int nMax) inline
Definition at line 695 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 695 of file G4NuclNuclDiffuseElastic.hh
References GetErfSer(), and w.
G4double G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab (const G4DynamicParticle * aParticle, G4double tmass, G4double thetaCMS)
Definition at line 1217 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1217 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, G4UniformRand, G4DynamicParticle::Get4Momentum(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag(), phi, CLHEP::Hep3Vector::theta(), twopi, v1, CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS (const G4DynamicParticle * aParticle, G4double tmass, G4double thetaLab)
Definition at line 1278 of file G4NuclNuclDiffuseElastic.cc.
View newest version in sPHENIX GitHub at line 1278 of file G4NuclNuclDiffuseElastic.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, G4UniformRand, G4DynamicParticle::Get4Momentum(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalMomentum(), phi, CLHEP::Hep3Vector::theta(), twopi, v1, G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4bool G4NuclNuclDiffuseElastic::fAddCoulomb private
Definition at line 337 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 337 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetDiffuseElasticSumXsc(), GetDiffuseElasticXsc(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fAm private
Definition at line 336 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 336 of file G4NuclNuclDiffuseElastic.hh
Referenced by CalculateAm(), CoulombAmplitude(), G4NuclNuclDiffuseElastic(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetDiffuseElasticSumXsc(), GetRutherfordXsc(), InitDynParameters(), InitParameters(), InitParametersGla(), SampleCoulombMuCMS(), and TestAngleTable().
std::vector<G4PhysicsTable*> G4NuclNuclDiffuseElastic::fAngleBank private
Definition at line 316 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 316 of file G4NuclNuclDiffuseElastic.hh
Referenced by Initialise(), InitialiseOnFly(), SampleTableThetaCMS(), TestAngleTable(), and ~G4NuclNuclDiffuseElastic().
G4int G4NuclNuclDiffuseElastic::fAngleBin private
Definition at line 312 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 312 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), SampleTableThetaCMS(), and TestAngleTable().
G4PhysicsTable* G4NuclNuclDiffuseElastic::fAngleTable private
Definition at line 315 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 315 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), GetScatteringAngle(), Initialise(), InitialiseOnFly(), SampleTableThetaCMS(), TestAngleTable(), and ~G4NuclNuclDiffuseElastic().
G4double G4NuclNuclDiffuseElastic::fAtomicNumber private
Definition at line 325 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 325 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetDiffuseElasticSumXsc(), InitDynParameters(), Initialise(), InitialiseOnFly(), InitParameters(), InitParametersGla(), SampleInvariantT(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fAtomicWeight private
Definition at line 324 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 324 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetDiffuseElasticSumXsc(), GetDiffuseElasticXsc(), Initialise(), InitialiseOnFly(), InitParameters(), InitParametersGla(), IntegralElasticProb(), SampleCoulombMuCMS(), SampleInvariantT(), SampleThetaCMS(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fBeta private
Definition at line 333 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 333 of file G4NuclNuclDiffuseElastic.hh
Referenced by CalculateParticleBeta(), G4NuclNuclDiffuseElastic(), GetDiffuseElasticSumXsc(), InitDynParameters(), InitParameters(), InitParametersGla(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fCofAlpha private
Definition at line 349 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 349 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitDynParameters(), InitParameters(), and SetCofAlpha().
G4double G4NuclNuclDiffuseElastic::fCofAlphaCoulomb private
Definition at line 355 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 355 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), and SetCofAlphaCoulomb().
G4double G4NuclNuclDiffuseElastic::fCofAlphaMax private
Definition at line 354 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 354 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), GetCofAlphaMax(), and SetCofAlphaMax().
G4double G4NuclNuclDiffuseElastic::fCofDelta private
Definition at line 350 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 350 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitDynParameters(), InitParameters(), and SetCofDelta().
G4double G4NuclNuclDiffuseElastic::fCofFar private
Definition at line 352 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 352 of file G4NuclNuclDiffuseElastic.hh
Referenced by Amplitude(), G4NuclNuclDiffuseElastic(), and SetCofFar().
G4double G4NuclNuclDiffuseElastic::fCofLambda private
Definition at line 348 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 348 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitDynParameters(), InitParameters(), and SetCofLambda().
G4double G4NuclNuclDiffuseElastic::fCofPhase private
Definition at line 351 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 351 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), PhaseFar(), PhaseNear(), and SetCofPhase().
G4double G4NuclNuclDiffuseElastic::fCoulombMuC private
Definition at line 362 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 362 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and SampleCoulombMuCMS().
G4double G4NuclNuclDiffuseElastic::fCoulombPhase0 private
Definition at line 339 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 339 of file G4NuclNuclDiffuseElastic.hh
Referenced by CalculateCoulombPhaseZero(), CoulombAmplitude(), G4NuclNuclDiffuseElastic(), PhaseFar(), and PhaseNear().
std::vector<G4String> G4NuclNuclDiffuseElastic::fElementNameVector private
Definition at line 319 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 319 of file G4NuclNuclDiffuseElastic.hh
Referenced by Initialise().
std::vector<G4double> G4NuclNuclDiffuseElastic::fElementNumberVector private
Definition at line 318 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 318 of file G4NuclNuclDiffuseElastic.hh
Referenced by Initialise(), InitialiseOnFly(), SampleTableThetaCMS(), and TestAngleTable().
G4int G4NuclNuclDiffuseElastic::fEnergyBin private
Definition at line 311 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 311 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), SampleTableThetaCMS(), and TestAngleTable().
G4PhysicsLogVector* G4NuclNuclDiffuseElastic::fEnergyVector private
Definition at line 314 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 314 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), SampleTableThetaCMS(), and ~G4NuclNuclDiffuseElastic().
G4double G4NuclNuclDiffuseElastic::fEtaRatio private
Definition at line 359 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 359 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeGla(), G4NuclNuclDiffuseElastic(), GetHadronNucleonXscNS(), and SetEtaRatio().
G4double G4NuclNuclDiffuseElastic::fHalfRutThetaTg private
Definition at line 340 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 340 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeSim(), CalculateRutherfordAnglePar(), G4NuclNuclDiffuseElastic(), GammaLess(), GammaMore(), GetRatioGen(), GetRatioSim(), PhaseFar(), and PhaseNear().
G4double G4NuclNuclDiffuseElastic::fHalfRutThetaTg2 private
Definition at line 341 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 341 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeSim(), CalculateRutherfordAnglePar(), G4NuclNuclDiffuseElastic(), GammaLess(), GammaMore(), GetRatioGen(), GetRatioSim(), PhaseFar(), PhaseNear(), and SampleCoulombMuCMS().
G4int G4NuclNuclDiffuseElastic::fMaxL private
Definition at line 357 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 357 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeGG(), AmplitudeGla(), G4NuclNuclDiffuseElastic(), InitParametersGla(), and SetMaxL().
G4double G4NuclNuclDiffuseElastic::fNuclearRadius private
Definition at line 329 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 329 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetDiffElasticProb(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetDiffuseElasticSumXsc(), GetDiffuseElasticXsc(), GetNuclearRadius(), InitDynParameters(), Initialise(), InitialiseOnFly(), InitParameters(), IntegralElasticProb(), SampleCoulombMuCMS(), SampleThetaCMS(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fNuclearRadius1 private
Definition at line 327 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 327 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitParameters(), and InitParametersGla().
G4double G4NuclNuclDiffuseElastic::fNuclearRadius2 private
Definition at line 328 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 328 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitParameters(), and InitParametersGla().
G4double G4NuclNuclDiffuseElastic::fNuclearRadiusCof private
Definition at line 331 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 331 of file G4NuclNuclDiffuseElastic.hh
Referenced by CalculateNuclearRad(), G4NuclNuclDiffuseElastic(), and SetNuclearRadiusCof().
G4double G4NuclNuclDiffuseElastic::fNuclearRadiusSquare private
Definition at line 330 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 330 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeGG(), AmplitudeGla(), G4NuclNuclDiffuseElastic(), and InitParametersGla().
const G4ParticleDefinition* G4NuclNuclDiffuseElastic::fParticle private
Definition at line 321 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 321 of file G4NuclNuclDiffuseElastic.hh
Referenced by BuildAngleTable(), G4NuclNuclDiffuseElastic(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetDiffuseElasticSumXsc(), GetDiffuseElasticXsc(), Initialise(), InitialiseOnFly(), IntegralElasticProb(), SampleCoulombMuCMS(), SampleInvariantT(), SampleThetaCMS(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fProfileAlpha private
Definition at line 346 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 346 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitDynParameters(), InitParameters(), ProfileFar(), ProfileNear(), and SetProfileAlpha().
G4double G4NuclNuclDiffuseElastic::fProfileDelta private
Definition at line 345 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 345 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), InitDynParameters(), InitParameters(), Profile(), ProfileFar(), ProfileNear(), and SetProfileDelta().
G4double G4NuclNuclDiffuseElastic::fProfileLambda private
Definition at line 344 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 344 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeFar(), AmplitudeNear(), AmplitudeSim(), CalculateRutherfordAnglePar(), G4NuclNuclDiffuseElastic(), GammaLess(), GammaMore(), GetProfileLambda(), GetRatioGen(), GetRatioSim(), InitDynParameters(), InitParameters(), PhaseFar(), PhaseNear(), and SetProfileLambda().
G4double G4NuclNuclDiffuseElastic::fReZ private
Definition at line 361 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 361 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetErfInt(), GetExpCos(), and GetExpSin().
G4double G4NuclNuclDiffuseElastic::fRutherfordRatio private
Definition at line 335 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 335 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetRutherfordXsc(), InitDynParameters(), and InitParameters().
G4double G4NuclNuclDiffuseElastic::fRutherfordTheta private
Definition at line 342 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 342 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeNear(), AmplitudeSim(), BuildAngleTable(), CalculateRutherfordAnglePar(), G4NuclNuclDiffuseElastic(), GammaLess(), GammaMore(), GetRatioGen(), GetRatioSim(), PhaseFar(), PhaseNear(), Profile(), ProfileFar(), and ProfileNear().
G4double G4NuclNuclDiffuseElastic::fSumSigma private
Definition at line 358 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 358 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeGG(), AmplitudeGla(), G4NuclNuclDiffuseElastic(), and InitParametersGla().
G4double G4NuclNuclDiffuseElastic::fWaveVector private
Definition at line 323 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 323 of file G4NuclNuclDiffuseElastic.hh
Referenced by AmplitudeFar(), AmplitudeGG(), AmplitudeGla(), AmplitudeNear(), CoulombAmplitude(), G4NuclNuclDiffuseElastic(), GetDiffElasticProb(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetDiffuseElasticSumXsc(), GetDiffuseElasticXsc(), InitDynParameters(), InitParameters(), InitParametersGla(), IntegralElasticProb(), SampleThetaCMS(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::fZommerfeld private
Definition at line 334 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 334 of file G4NuclNuclDiffuseElastic.hh
Referenced by CalculateCoulombPhase(), CalculateCoulombPhaseZero(), CalculateRutherfordAnglePar(), CalculateZommerfeld(), CoulombAmplitude(), G4NuclNuclDiffuseElastic(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetDiffuseElasticSumXsc(), InitDynParameters(), InitParameters(), InitParametersGla(), PhaseFar(), PhaseNear(), and TestAngleTable().
G4double G4NuclNuclDiffuseElastic::lowEnergyLimitHE private
Definition at line 306 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 306 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and SetHEModelLowLimit().
G4double G4NuclNuclDiffuseElastic::lowEnergyLimitQ private
Definition at line 307 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 307 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and SetQModelLowLimit().
G4double G4NuclNuclDiffuseElastic::lowEnergyRecoilLimit private
Definition at line 305 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 305 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and SetRecoilKinEnergyLimit().
G4double G4NuclNuclDiffuseElastic::lowestEnergyLimit private
Definition at line 308 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 308 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and SetLowestEnergyLimit().
G4double G4NuclNuclDiffuseElastic::plabLowLimit private
Definition at line 309 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 309 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and SetPlabLowLimit().
G4ParticleDefinition* G4NuclNuclDiffuseElastic::theAlpha private
Definition at line 300 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 300 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetInvCoulombElasticXsc(), GetInvElasticSumXsc(), and GetInvElasticXsc().
G4ParticleDefinition* G4NuclNuclDiffuseElastic::theDeuteron private
Definition at line 299 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 299 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetInvCoulombElasticXsc(), GetInvElasticSumXsc(), and GetInvElasticXsc().
G4ParticleDefinition* G4NuclNuclDiffuseElastic::theNeutron private
Definition at line 298 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 298 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), and InitParametersGla().
const G4ParticleDefinition* G4NuclNuclDiffuseElastic::thePionMinus private
Definition at line 303 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 303 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic().
const G4ParticleDefinition* G4NuclNuclDiffuseElastic::thePionPlus private
Definition at line 302 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 302 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic().
G4ParticleDefinition* G4NuclNuclDiffuseElastic::theProton private
Definition at line 293 of file G4NuclNuclDiffuseElastic.hh.
View newest version in sPHENIX GitHub at line 293 of file G4NuclNuclDiffuseElastic.hh
Referenced by G4NuclNuclDiffuseElastic(), GetDiffElasticSumProb(), GetDiffElasticSumProbA(), GetInvCoulombElasticXsc(), GetInvElasticSumXsc(), GetInvElasticXsc(), and InitParametersGla().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4NuclNuclDiffuseElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4NuclNuclDiffuseElastic.cc