ECCE @ EIC Software: G4ParticleChangeForOccurenceBiasing Class Reference
G4ParticleChangeForOccurenceBiasing Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ParticleChangeForOccurenceBiasing.hh>
Public Member Functions
G4ParticleChangeForOccurenceBiasing (G4String name)
~G4ParticleChangeForOccurenceBiasing ()
void SetOccurenceWeightForNonInteraction (G4double w)
G4double GetOccurenceWeightForNonInteraction () const
void SetOccurenceWeightForInteraction (G4double w)
G4double GetOccurenceWeightForInteraction () const
void SetWrappedParticleChange (G4VParticleChange *wpc)
G4VParticleChange * GetWrappedParticleChange () const
void StealSecondaries ()
virtual G4Step * UpdateStepForAtRest (G4Step *step)
virtual G4Step * UpdateStepForAlongStep (G4Step *step)
virtual G4Step * UpdateStepForPostStep (G4Step *step)
const G4String & GetName () const
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual void Initialize (const G4Track &)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
virtual G4bool CheckIt (const G4Track &)
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Private Attributes
G4String fName
G4VParticleChange * fWrappedParticleChange
G4double fOccurenceWeightForNonInteraction
G4double fOccurenceWeightForInteraction
Additional Inherited Members
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 47 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleChangeForOccurenceBiasing.hh
Constructor & Destructor Documentation
G4ParticleChangeForOccurenceBiasing::G4ParticleChangeForOccurenceBiasing (G4String name)
Definition at line 28 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 28 of file G4ParticleChangeForOccurenceBiasing.cc
G4ParticleChangeForOccurenceBiasing::~G4ParticleChangeForOccurenceBiasing ()
Definition at line 36 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleChangeForOccurenceBiasing.cc
Member Function Documentation
const G4String& G4ParticleChangeForOccurenceBiasing::GetName (void) const inline
Definition at line 73 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleChangeForOccurenceBiasing.hh
References fName.
G4double G4ParticleChangeForOccurenceBiasing::GetOccurenceWeightForInteraction () const inline
Definition at line 56 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleChangeForOccurenceBiasing.hh
References fOccurenceWeightForInteraction.
G4double G4ParticleChangeForOccurenceBiasing::GetOccurenceWeightForNonInteraction () const inline
Definition at line 54 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleChangeForOccurenceBiasing.hh
References fOccurenceWeightForNonInteraction.
G4VParticleChange* G4ParticleChangeForOccurenceBiasing::GetWrappedParticleChange () const inline
Definition at line 61 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleChangeForOccurenceBiasing.hh
References fWrappedParticleChange.
void G4ParticleChangeForOccurenceBiasing::SetOccurenceWeightForInteraction (G4double w) inline
Definition at line 55 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleChangeForOccurenceBiasing.hh
References fOccurenceWeightForInteraction, and w.
Referenced by G4BiasingProcessInterface::PostStepDoIt().
void G4ParticleChangeForOccurenceBiasing::SetOccurenceWeightForNonInteraction (G4double w) inline
Definition at line 53 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleChangeForOccurenceBiasing.hh
References fOccurenceWeightForNonInteraction, and w.
Referenced by G4BiasingProcessInterface::AlongStepDoIt().
void G4ParticleChangeForOccurenceBiasing::SetWrappedParticleChange (G4VParticleChange * wpc)
Definition at line 39 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleChangeForOccurenceBiasing.cc
References fWrappedParticleChange.
Referenced by G4BiasingProcessInterface::AlongStepDoIt(), and G4BiasingProcessInterface::PostStepDoIt().
void G4ParticleChangeForOccurenceBiasing::StealSecondaries ()
Definition at line 44 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleChangeForOccurenceBiasing.cc
References G4VParticleChange::AddSecondary(), G4VParticleChange::Clear(), fOccurenceWeightForInteraction, fWrappedParticleChange, G4VParticleChange::GetNumberOfSecondaries(), G4VParticleChange::GetSecondary(), G4Track::GetWeight(), G4VParticleChange::SetNumberOfSecondaries(), and G4Track::SetWeight().
Referenced by G4BiasingProcessInterface::PostStepDoIt().
G4Step * G4ParticleChangeForOccurenceBiasing::UpdateStepForAlongStep (G4Step * step) virtual
Reimplemented from G4VParticleChange.
Definition at line 62 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleChangeForOccurenceBiasing.cc
References fOccurenceWeightForNonInteraction, fWrappedParticleChange, G4Step::GetPostStepPoint(), G4StepPoint::GetWeight(), G4StepPoint::SetWeight(), Acts::Test::step(), and G4VParticleChange::UpdateStepForAlongStep().
G4Step * G4ParticleChangeForOccurenceBiasing::UpdateStepForAtRest (G4Step * step) virtual
Reimplemented from G4VParticleChange.
Definition at line 57 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleChangeForOccurenceBiasing.cc
References Acts::Test::step().
G4Step * G4ParticleChangeForOccurenceBiasing::UpdateStepForPostStep (G4Step * step) virtual
Reimplemented from G4VParticleChange.
Definition at line 74 of file G4ParticleChangeForOccurenceBiasing.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleChangeForOccurenceBiasing.cc
References fOccurenceWeightForInteraction, fWrappedParticleChange, G4Step::GetPostStepPoint(), G4StepPoint::GetWeight(), G4StepPoint::SetWeight(), Acts::Test::step(), and G4VParticleChange::UpdateStepForPostStep().
Member Data Documentation
G4String G4ParticleChangeForOccurenceBiasing::fName private
Definition at line 76 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleChangeForOccurenceBiasing.hh
Referenced by GetName().
G4double G4ParticleChangeForOccurenceBiasing::fOccurenceWeightForInteraction private
Definition at line 79 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleChangeForOccurenceBiasing.hh
Referenced by GetOccurenceWeightForInteraction(), SetOccurenceWeightForInteraction(), StealSecondaries(), and UpdateStepForPostStep().
G4double G4ParticleChangeForOccurenceBiasing::fOccurenceWeightForNonInteraction private
Definition at line 78 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleChangeForOccurenceBiasing.hh
Referenced by GetOccurenceWeightForNonInteraction(), SetOccurenceWeightForNonInteraction(), and UpdateStepForAlongStep().
G4VParticleChange* G4ParticleChangeForOccurenceBiasing::fWrappedParticleChange private
Definition at line 77 of file G4ParticleChangeForOccurenceBiasing.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleChangeForOccurenceBiasing.hh
Referenced by GetWrappedParticleChange(), SetWrappedParticleChange(), StealSecondaries(), UpdateStepForAlongStep(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ParticleChangeForOccurenceBiasing.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4ParticleChangeForOccurenceBiasing.cc