ECCE @ EIC Software: G4ITReactionSet Class Reference
G4ITReactionSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITReaction.hh>
Public Member Functions
virtual ~G4ITReactionSet ()
void AddReaction (double time, G4Track *trackA, G4Track *trackB)
void AddReactions (double time, G4Track *trackA, G4TrackVectorHandle reactants)
void RemoveReactionSet (G4Track *track)
void SelectThisReaction (G4ITReactionPtr reaction)
G4ITReactionPerTrackMap & GetReactionMap ()
void RemoveReactionPerTrack (G4ITReactionPerTrackPtr reactionPerTrack)
void CleanAllReaction ()
bool Empty ()
G4ITReactionPerTime & GetReactionsPerTime ()
Static Public Member Functions
static G4ITReactionSet * Instance ()
Protected Member Functions
void AddReaction (G4Track *track, G4ITReactionPtr reaction)
Protected Attributes
G4ITReactionPerTrackMap fReactionPerTrack
G4ITReactionPerTime fReactionPerTime
bool fSortByTime
Static Protected Attributes
static G4ThreadLocal
G4ITReactionSet * fpInstance
Private Member Functions
G4ITReactionSet ()
Detailed Description
Definition at line 178 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ITReaction.hh
Constructor & Destructor Documentation
G4ITReactionSet::G4ITReactionSet () inline private
Definition at line 180 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 180 of file G4ITReaction.hh
References fpInstance, and fSortByTime.
Referenced by Instance().
virtual G4ITReactionSet::~G4ITReactionSet () inline virtual
Definition at line 186 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 186 of file G4ITReaction.hh
References fReactionPerTime, and fReactionPerTrack.
Member Function Documentation
void G4ITReactionSet::AddReaction (double time, G4Track * trackA, G4Track * trackB) inline
Definition at line 201 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 201 of file G4ITReaction.hh
References fReactionPerTime, fSortByTime, it, and G4ITReaction::New().
Referenced by AddReactions().
void G4ITReactionSet::AddReaction (G4Track * track, G4ITReactionPtr reaction) inline protected
Definition at line 287 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 287 of file G4ITReaction.hh
References fReactionPerTrack, it, G4ITReactionPerTrack::New(), and pos().
void G4ITReactionSet::AddReactions (double time, G4Track * trackA, G4TrackVectorHandle reactants) inline
Definition at line 214 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 214 of file G4ITReaction.hh
References AddReaction(), and it.
void G4ITReactionSet::CleanAllReaction () inline
Definition at line 264 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 264 of file G4ITReaction.hh
References fReactionPerTime, fReactionPerTrack, and it.
Referenced by G4Scheduler::Reset(), and G4Scheduler::Stepping().
bool G4ITReactionSet::Empty () inline
Definition at line 276 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 276 of file G4ITReaction.hh
References fReactionPerTrack.
G4ITReactionPerTrackMap& G4ITReactionSet::GetReactionMap () inline
Definition at line 246 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 246 of file G4ITReaction.hh
References fReactionPerTrack.
Referenced by G4ITModelProcessor::FindReaction().
G4ITReactionPerTime& G4ITReactionSet::GetReactionsPerTime () inline
Definition at line 281 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 281 of file G4ITReaction.hh
References fReactionPerTime.
Referenced by G4ITReaction::RemoveMe().
static G4ITReactionSet* G4ITReactionSet::Instance (void) inline static
Definition at line 192 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ITReaction.hh
References fpInstance, and G4ITReactionSet().
Referenced by G4Scheduler::Create(), G4ITStepProcessor::ExtractDoItData(), G4ITModelProcessor::Initialize(), G4ITReaction::RemoveMe(), and G4ITReactionPerTrack::RemoveThisReaction().
void G4ITReactionSet::RemoveReactionPerTrack (G4ITReactionPerTrackPtr reactionPerTrack) inline
Definition at line 251 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 251 of file G4ITReaction.hh
References fReactionPerTrack, and it.
Referenced by G4ITReactionPerTrack::RemoveThisReaction().
void G4ITReactionSet::RemoveReactionSet (G4Track * track) inline
Definition at line 223 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 223 of file G4ITReaction.hh
References fReactionPerTrack, and it.
Referenced by G4ITStepProcessor::ExtractDoItData(), and SelectThisReaction().
void G4ITReactionSet::SelectThisReaction (G4ITReactionPtr reaction) inline
Definition at line 239 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 239 of file G4ITReaction.hh
References RemoveReactionSet().
Referenced by G4ITModelProcessor::FindReaction().
Member Data Documentation
G4ThreadLocal G4ITReactionSet * G4ITReactionSet::fpInstance static protected
Definition at line 311 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 311 of file G4ITReaction.hh
Referenced by G4ITReactionSet(), and Instance().
G4ITReactionPerTime G4ITReactionSet::fReactionPerTime protected
Definition at line 308 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 308 of file G4ITReaction.hh
Referenced by AddReaction(), CleanAllReaction(), GetReactionsPerTime(), and ~G4ITReactionSet().
G4ITReactionPerTrackMap G4ITReactionSet::fReactionPerTrack protected
Definition at line 307 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 307 of file G4ITReaction.hh
Referenced by AddReaction(), CleanAllReaction(), Empty(), GetReactionMap(), RemoveReactionPerTrack(), RemoveReactionSet(), and ~G4ITReactionSet().
bool G4ITReactionSet::fSortByTime protected
Definition at line 310 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 310 of file G4ITReaction.hh
Referenced by AddReaction(), and G4ITReactionSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITReaction.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITReaction.cc