ECCE @ EIC Software: G4FTFModel Class Reference
G4FTFModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFModel.hh>
Classes
struct CommonVariables
Public Member Functions
G4FTFModel (const G4String &modelName="FTF")
~G4FTFModel ()
void Init (const G4Nucleus &aNucleus, const G4DynamicParticle &aProjectile)
G4ExcitedStringVector * GetStrings ()
G4V3DNucleus * GetWoundedNucleus () const
G4V3DNucleus * GetTargetNucleus () const
G4V3DNucleus * GetProjectileNucleus () const
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4VPartonStringModel
G4VPartonStringModel (const G4String &modelName="Parton String Model")
virtual ~G4VPartonStringModel ()
void SetFragmentationModel (G4VStringFragmentation *aModel)
G4KineticTrackVector * Scatter (const G4Nucleus &theNucleus, const G4DynamicParticle &thePrimary)
Public Member Functions inherited from G4VHighEnergyGenerator
G4VHighEnergyGenerator (const G4String &modelName="High Energy Generator")
~G4VHighEnergyGenerator () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &, G4Nucleus &) final
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4FTFModel (const G4FTFModel &right)
const G4FTFModel & operator= (const G4FTFModel &right)
G4bool operator== (const G4FTFModel &right) const
G4bool operator!= (const G4FTFModel &right) const
void StoreInvolvedNucleon ()
void ReggeonCascade ()
G4bool PutOnMassShell ()
G4bool ExciteParticipants ()
void BuildStrings (G4ExcitedStringVector *strings)
void GetResiduals ()
G4bool AdjustNucleons (G4VSplitableHadron *SelectedAntiBaryon, G4Nucleon *ProjectileNucleon, G4VSplitableHadron *SelectedTargetNucleon, G4Nucleon *TargetNucleon, G4bool Annihilation)
G4int AdjustNucleonsAlgorithm_beforeSampling (G4int interactionCase, G4VSplitableHadron *SelectedAntiBaryon, G4Nucleon *ProjectileNucleon, G4VSplitableHadron *SelectedTargetNucleon, G4Nucleon *TargetNucleon, G4bool Annihilation, CommonVariables &common)
G4bool AdjustNucleonsAlgorithm_Sampling (G4int interactionCase, CommonVariables &common)
void AdjustNucleonsAlgorithm_afterSampling (G4int interactionCase, G4VSplitableHadron *SelectedAntiBaryon, G4VSplitableHadron *SelectedTargetNucleon, CommonVariables &common)
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
G4bool ComputeNucleusProperties (G4V3DNucleus *nucleus, G4LorentzVector &nucleusMomentum, G4LorentzVector &residualMomentum, G4double &sumMasses, G4double &residualExcitationEnergy, G4double &residualMass, G4int &residualMassNumber, G4int &residualCharge)
G4bool GenerateDeltaIsobar (const G4double sqrtS, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4double &sumMasses)
G4bool SamplingNucleonKinematics (G4double averagePt2, const G4double maxPt2, G4double dCor, G4V3DNucleus *nucleus, const G4LorentzVector &pResidual, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4double &mass2)
G4bool CheckKinematics (const G4double sValue, const G4double sqrtS, const G4double projectileMass2, const G4double targetMass2, const G4double nucleusY, const G4bool isProjectileNucleus, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4double &targetWminus, G4double &projectileWplus, G4bool &success)
G4bool FinalizeKinematics (const G4double w, const G4bool isProjectileNucleus, const G4LorentzRotation &boostFromCmsToLab, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4LorentzVector &residual4Momentum)
Private Attributes
G4ReactionProduct theProjectile
G4FTFParticipants theParticipants
G4Nucleon * TheInvolvedNucleonsOfTarget [250]
G4int NumberOfInvolvedNucleonsOfTarget
G4Nucleon * TheInvolvedNucleonsOfProjectile [250]
G4int NumberOfInvolvedNucleonsOfProjectile
G4FTFParameters * theParameters
G4DiffractiveExcitation * theExcitation
G4ElasticHNScattering * theElastic
G4FTFAnnihilation * theAnnihilation
std::vector< G4VSplitableHadron * > theAdditionalString
G4double LowEnergyLimit
G4bool HighEnergyInter
G4LorentzVector ProjectileResidual4Momentum
G4int ProjectileResidualMassNumber
G4int ProjectileResidualCharge
G4double ProjectileResidualExcitationEnergy
G4LorentzVector TargetResidual4Momentum
G4int TargetResidualMassNumber
G4int TargetResidualCharge
G4double TargetResidualExcitationEnergy
Additional Inherited Members
Protected Member Functions inherited from G4VPartonStringModel
void SetThisPointer (G4VPartonStringModel *aPointer)
G4bool EnergyAndMomentumCorrector (G4KineticTrackVector *Output, G4LorentzVector &TotalCollisionMomentum)
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 61 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4FTFModel.hh
Constructor & Destructor Documentation
G4FTFModel::G4FTFModel (const G4String & modelName = "FTF")
Definition at line 70 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4FTFModel.cc
References HighEnergyInter, LowEnergyLimit, MeV, NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, perCent, ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, G4HadronicInteraction::SetEnergyMomentumCheckLevels(), G4VPartonStringModel::SetThisPointer(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, theParameters, and tmp.
G4FTFModel::~G4FTFModel ()
Definition at line 114 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 114 of file G4FTFModel.cc
References G4Nucleon::GetSplitableHadron(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, theAdditionalString, theAnnihilation, theElastic, theExcitation, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, and theParameters.
G4FTFModel::G4FTFModel (const G4FTFModel & right) private
Member Function Documentation
G4bool G4FTFModel::AdjustNucleons (G4VSplitableHadron * SelectedAntiBaryon, G4Nucleon * ProjectileNucleon, G4VSplitableHadron * SelectedTargetNucleon, G4Nucleon * TargetNucleon, G4bool Annihilation) private
Definition at line 1038 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 1038 of file G4FTFModel.cc
References AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), AdjustNucleonsAlgorithm_Sampling(), common(), G4cout, G4endl, G4VSplitableHadron::Get4Momentum(), GetProjectileNucleus(), G4VSplitableHadron::GetSoftCollisionCount(), ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, CLHEP::HepLorentzVector::rapidity(), G4VSplitableHadron::Set4Momentum(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, and TargetResidualMassNumber.
Referenced by ExciteParticipants().
void G4FTFModel::AdjustNucleonsAlgorithm_afterSampling (G4int interactionCase, G4VSplitableHadron * SelectedAntiBaryon, G4VSplitableHadron * SelectedTargetNucleon, G4FTFModel::CommonVariables & common) private
Definition at line 1836 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 1836 of file G4FTFModel.cc
References E, G4FTFModel::CommonVariables::Eprojectile, G4FTFModel::CommonVariables::EprojectileNucleon, G4FTFModel::CommonVariables::Etarget, G4FTFModel::CommonVariables::EtargetNucleon, G4cout, G4endl, CLHEP::Hep3Vector::mag2(), G4FTFModel::CommonVariables::Pprojectile, G4FTFModel::CommonVariables::PResidualCharge, G4FTFModel::CommonVariables::PResidualExcitationEnergy, G4FTFModel::CommonVariables::PResidualMass, G4FTFModel::CommonVariables::PResidualMassNumber, ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, G4FTFModel::CommonVariables::Ptarget, G4FTFModel::CommonVariables::PtNucleon, G4FTFModel::CommonVariables::PtNucleonP, G4FTFModel::CommonVariables::PtNucleonT, G4FTFModel::CommonVariables::PtResidual, G4FTFModel::CommonVariables::PtResidualP, G4FTFModel::CommonVariables::PtResidualT, G4FTFModel::CommonVariables::Pzprojectile, G4FTFModel::CommonVariables::PzprojectileNucleon, G4FTFModel::CommonVariables::Pztarget, G4FTFModel::CommonVariables::PztargetNucleon, G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sqr(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, G4FTFModel::CommonVariables::toLab, CLHEP::HepLorentzVector::transform(), G4FTFModel::CommonVariables::TResidualCharge, G4FTFModel::CommonVariables::TResidualExcitationEnergy, G4FTFModel::CommonVariables::TResidualMass, G4FTFModel::CommonVariables::TResidualMassNumber, G4FTFModel::CommonVariables::WminusTarget, G4FTFModel::CommonVariables::WplusProjectile, CLHEP::Hep3Vector::x(), G4FTFModel::CommonVariables::XminusResidual, G4FTFModel::CommonVariables::XplusResidual, and CLHEP::Hep3Vector::y().
Referenced by AdjustNucleons().
G4int G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling (G4int interactionCase, G4VSplitableHadron * SelectedAntiBaryon, G4Nucleon * ProjectileNucleon, G4VSplitableHadron * SelectedTargetNucleon, G4Nucleon * TargetNucleon, G4bool Annihilation, G4FTFModel::CommonVariables & common) private
Definition at line 1153 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 1153 of file G4FTFModel.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, G4Log(), G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4Nucleon::GetDefinition(), G4FTFParameters::GetExcitationEnergyPerWoundedNucleon(), G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzRotation::inverse(), G4FTFModel::CommonVariables::M2projectile, G4FTFModel::CommonVariables::M2target, CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), G4FTFModel::CommonVariables::Mprojectile, G4FTFModel::CommonVariables::Mtarget, CLHEP::HepLorentzVector::phi(), G4FTFModel::CommonVariables::PNucleonMass, G4FTFModel::CommonVariables::Pprojectile, G4FTFModel::CommonVariables::PResidual4Momentum, G4FTFModel::CommonVariables::PResidualCharge, G4FTFModel::CommonVariables::PResidualExcitationEnergy, G4FTFModel::CommonVariables::PResidualMass, G4FTFModel::CommonVariables::PResidualMassNumber, ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, G4FTFModel::CommonVariables::Psum, G4FTFModel::CommonVariables::Ptarget, G4FTFModel::CommonVariables::Ptmp, CLHEP::HepLorentzVector::rapidity(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4FTFModel::CommonVariables::S, G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sqr(), G4FTFModel::CommonVariables::SqrtS, G4FTFModel::CommonVariables::SumMasses, TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, theParameters, CLHEP::HepLorentzVector::theta(), G4FTFModel::CommonVariables::TNucleonMass, G4FTFModel::CommonVariables::toCms, G4FTFModel::CommonVariables::toLab, CLHEP::HepLorentzVector::transform(), G4FTFModel::CommonVariables::TResidual4Momentum, G4FTFModel::CommonVariables::TResidualCharge, G4FTFModel::CommonVariables::TResidualExcitationEnergy, G4FTFModel::CommonVariables::TResidualMass, G4FTFModel::CommonVariables::TResidualMassNumber, CLHEP::HepLorentzVector::vect(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), G4FTFModel::CommonVariables::YprojectileNucleus, G4FTFModel::CommonVariables::YtargetNucleus, and CLHEP::HepLorentzVector::z().
Referenced by AdjustNucleons().
G4bool G4FTFModel::AdjustNucleonsAlgorithm_Sampling (G4int interactionCase, G4FTFModel::CommonVariables & common) private
Definition at line 1501 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 1501 of file G4FTFModel.cc
References kdfinder::abs(), condition(), G4FTFModel::CommonVariables::Eprojectile, G4FTFModel::CommonVariables::EprojectileNucleon, G4FTFModel::CommonVariables::Etarget, G4FTFModel::CommonVariables::EtargetNucleon, G4cout, G4endl, G4Log(), GaussianPt(), G4FTFParameters::GetDofNuclearDestruction(), G4FTFParameters::GetMaxPt2ofNuclearDestruction(), G4FTFParameters::GetPt2ofNuclearDestruction(), G4FTFModel::CommonVariables::M2projectile, G4FTFModel::CommonVariables::M2target, CLHEP::Hep3Vector::mag2(), G4FTFModel::CommonVariables::Mprojectile, G4FTFModel::CommonVariables::Mt2projectileNucleon, G4FTFModel::CommonVariables::Mt2targetNucleon, G4FTFModel::CommonVariables::Mtarget, G4FTFModel::CommonVariables::PNucleonMass, G4FTFModel::CommonVariables::PResidualMass, ProjectileResidualMassNumber, G4FTFModel::CommonVariables::PtNucleon, G4FTFModel::CommonVariables::PtNucleonP, G4FTFModel::CommonVariables::PtNucleonT, G4FTFModel::CommonVariables::PtResidual, G4FTFModel::CommonVariables::PtResidualP, G4FTFModel::CommonVariables::PtResidualT, G4FTFModel::CommonVariables::Pzprojectile, G4FTFModel::CommonVariables::PzprojectileNucleon, G4FTFModel::CommonVariables::Pztarget, G4FTFModel::CommonVariables::PztargetNucleon, G4FTFModel::CommonVariables::S, sqr(), G4FTFModel::CommonVariables::SqrtS, TargetResidualMassNumber, theParameters, G4FTFModel::CommonVariables::TNucleonMass, G4FTFModel::CommonVariables::TResidualMass, G4FTFModel::CommonVariables::WminusTarget, G4FTFModel::CommonVariables::WplusProjectile, CLHEP::Hep3Vector::x(), G4FTFModel::CommonVariables::XminusNucleon, G4FTFModel::CommonVariables::XminusResidual, G4FTFModel::CommonVariables::XplusNucleon, G4FTFModel::CommonVariables::XplusResidual, G4FTFModel::CommonVariables::YprojectileNucleus, and G4FTFModel::CommonVariables::YtargetNucleus.
Referenced by AdjustNucleons().
void G4FTFModel::BuildStrings (G4ExcitedStringVector * strings) private
Definition at line 1975 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 1975 of file G4FTFModel.cc
References G4DiffractiveExcitation::CreateStrings(), G4cout, G4endl, G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4FTFParticipants::GetInteraction(), G4ExcitedString::GetLeftParton(), G4Parton::GetPDGcode(), G4VSplitableHadron::GetPosition(), G4InteractionContent::GetProjectile(), GetProjectileNucleus(), G4ExcitedString::GetRightParton(), G4VSplitableHadron::GetSoftCollisionCount(), G4Nucleon::GetSplitableHadron(), G4InteractionContent::GetStatus(), G4VSplitableHadron::GetStatus(), G4VSplitableHadron::GetTimeOfCreation(), HighEnergyInter, G4ExcitedString::IsExcited(), G4FTFParticipants::Next(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, G4VSplitableHadron::SetStatus(), G4FTFParticipants::StartLoop(), theAdditionalString, theExcitation, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, theParameters, and theParticipants.
Referenced by GetStrings().
G4bool G4FTFModel::CheckKinematics (const G4double sValue, const G4double sqrtS, const G4double projectileMass2, const G4double targetMass2, const G4double nucleusY, const G4bool isProjectileNucleus, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4double & targetWminus, G4double & projectileWplus, G4bool & success) private
Definition at line 2929 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 2929 of file G4FTFModel.cc
References kdfinder::abs(), e, G4cout, G4endl, G4Log(), G4Nucleon::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), sqr(), tmp, CLHEP::HepLorentzVector::x(), x, CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by PutOnMassShell().
G4bool G4FTFModel::ComputeNucleusProperties (G4V3DNucleus * nucleus, G4LorentzVector & nucleusMomentum, G4LorentzVector & residualMomentum, G4double & sumMasses, G4double & residualExcitationEnergy, G4double & residualMass, G4int & residualMassNumber, G4int & residualCharge) private
Definition at line 2620 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 2620 of file G4FTFModel.cc
References kdfinder::abs(), G4Nucleon::AreYouHit(), G4cout, G4endl, G4Log(), G4UniformRand, G4Nucleon::Get4Momentum(), G4Nucleon::GetDefinition(), G4FTFParameters::GetExcitationEnergyPerWoundedNucleon(), G4ParticleTable::GetIonTable(), G4V3DNucleus::GetNextNucleon(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), MeV, CLHEP::HepLorentzVector::perp2(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), G4V3DNucleus::StartLoop(), and theParameters.
Referenced by PutOnMassShell().
G4bool G4FTFModel::ExciteParticipants () private
Definition at line 856 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 856 of file G4FTFModel.cc
References AdjustNucleons(), G4FTFAnnihilation::Annihilate(), G4ElasticHNScattering::ElasticScattering(), G4DiffractiveExcitation::ExciteParticipants(), G4cout, G4endl, G4UniformRand, G4FTFParticipants::GetInteraction(), G4FTFParameters::GetMaxNumberOfCollisions(), G4FTFParameters::GetProbabilityOfAnnihilation(), G4FTFParameters::GetProbabilityOfElasticScatt(), G4InteractionContent::GetProjectile(), G4InteractionContent::GetProjectileNucleon(), G4VSplitableHadron::GetSoftCollisionCount(), G4InteractionContent::GetStatus(), G4VSplitableHadron::GetStatus(), G4InteractionContent::GetTarget(), G4InteractionContent::GetTargetNucleon(), HighEnergyInter, I, G4FTFParticipants::Next(), G4InteractionContent::SetStatus(), G4FTFParticipants::StartLoop(), theAdditionalString, theAnnihilation, theElastic, theExcitation, theParameters, and theParticipants.
Referenced by GetStrings().
G4bool G4FTFModel::FinalizeKinematics (const G4double w, const G4bool isProjectileNucleus, const G4LorentzRotation & boostFromCmsToLab, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4LorentzVector & residual4Momentum) private
Definition at line 3003 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 3003 of file G4FTFModel.cc
References e, G4cout, G4endl, G4Nucleon::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), G4Nucleon::SetMomentum(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sqr(), tmp, CLHEP::HepLorentzVector::transform(), CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::HepLorentzVector::x(), x, CLHEP::Hep3Vector::y(), CLHEP::HepLorentzVector::y(), CLHEP::Hep3Vector::z(), and CLHEP::HepLorentzVector::z().
Referenced by PutOnMassShell().
G4ThreeVector G4FTFModel::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 2598 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 2598 of file G4FTFModel.cc
References e, G4Exp(), G4Log(), G4UniformRand, phi, and twopi.
Referenced by AdjustNucleonsAlgorithm_Sampling(), and SamplingNucleonKinematics().
G4bool G4FTFModel::GenerateDeltaIsobar (const G4double sqrtS, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4double & sumMasses) private
Definition at line 2703 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 2703 of file G4FTFModel.cc
References kdfinder::abs(), G4ParticleTable::FindParticle(), G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), MeV, CLHEP::HepLorentzVector::perp2(), G4VSplitableHadron::SetDefinition(), and sqr().
Referenced by PutOnMassShell().
G4V3DNucleus * G4FTFModel::GetProjectileNucleus () const inline virtual
Reimplemented from G4VPartonStringModel.
Definition at line 201 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 201 of file G4FTFModel.hh
References G4VParticipants::GetProjectileNucleus(), and theParticipants.
Referenced by AdjustNucleons(), BuildStrings(), GetResiduals(), GetStrings(), PutOnMassShell(), ReggeonCascade(), and StoreInvolvedNucleon().
void G4FTFModel::GetResiduals () private
Definition at line 2279 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 2279 of file G4FTFModel.cc
References G4Nucleon::AreYouHit(), CLHEP::HepLorentzVector::boost(), C(), E, CLHEP::HepLorentzVector::findBoostToCM(), G4cout, G4endl, G4Nucleon::Get4Momentum(), G4Nucleon::GetBindingEnergy(), G4Nucleon::GetDefinition(), G4V3DNucleus::GetNextNucleon(), G4ParticleDefinition::GetPDGMass(), GetProjectileNucleus(), G4VSplitableHadron::GetSoftCollisionCount(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::GetStatus(), GetTargetNucleus(), HighEnergyInter, G4Nucleon::Hit(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, G4Nucleon::SetBindingEnergy(), CLHEP::HepLorentzVector::setE(), G4Nucleon::SetMomentum(), sqr(), G4V3DNucleus::StartLoop(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, tmp, and CLHEP::HepLorentzVector::vect().
Referenced by GetStrings().
G4ExcitedStringVector * G4FTFModel::GetStrings () virtual
Implements G4VPartonStringModel.
Definition at line 291 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 291 of file G4FTFModel.cc
References BuildStrings(), G4FTFParticipants::Clean(), ExciteParticipants(), G4cout, G4endl, G4FTFParticipants::GetInteraction(), G4FTFParticipants::GetList(), G4InteractionContent::GetProjectile(), GetProjectileNucleus(), GetResiduals(), G4Nucleon::GetSplitableHadron(), HighEnergyInter, G4FTFParticipants::Next(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, PutOnMassShell(), ReggeonCascade(), G4FTFParticipants::StartLoop(), StoreInvolvedNucleon(), TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, theParameters, theParticipants, and theProjectile.
G4V3DNucleus * G4FTFModel::GetTargetNucleus () const inline
Definition at line 196 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 196 of file G4FTFModel.hh
References G4VParticipants::GetWoundedNucleus(), and theParticipants.
Referenced by GetResiduals(), PutOnMassShell(), ReggeonCascade(), and StoreInvolvedNucleon().
G4V3DNucleus * G4FTFModel::GetWoundedNucleus () const inline virtual
Implements G4VPartonStringModel.
Definition at line 191 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 191 of file G4FTFModel.hh
References G4VParticipants::GetWoundedNucleus(), and theParticipants.
void G4FTFModel::Init (const G4Nucleus & aNucleus, const G4DynamicParticle & aProjectile) virtual
Implements G4VPartonStringModel.
Definition at line 154 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 154 of file G4FTFModel.cc
References kdfinder::abs(), G4AntiNeutron::AntiNeutron(), G4AntiProton::AntiProton(), G4FTFParticipants::Clean(), G4V3DNucleus::DoLorentzBoost(), G4V3DNucleus::DoLorentzContraction(), G4cout, G4endl, G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetBaryonNumber(), G4Nucleon::GetDefinition(), G4ReactionProduct::GetDefinition(), G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ReactionProduct::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), HighEnergyInter, G4VParticipants::Init(), G4FTFParameters::InitForInteraction(), G4VParticipants::InitProjectileNucleus(), LowEnergyLimit, G4Neutron::Neutron(), ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, G4Proton::Proton(), CLHEP::HepLorentzVector::setE(), G4Nucleon::SetParticleType(), G4FTFParameters::SetProbabilityOfElasticScatt(), G4VParticipants::SetProjectileNucleus(), CLHEP::HepLorentzVector::setVect(), G4V3DNucleus::StartLoop(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, theAdditionalString, theParameters, theParticipants, theProjectile, G4VParticipants::theProjectileNucleus, tmp, and CLHEP::Hep3Vector::z().
void G4FTFModel::ModelDescription (std::ostream & desc) const virtual
Reimplemented from G4VPartonStringModel.
Definition at line 3075 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 3075 of file G4FTFModel.cc
G4bool G4FTFModel::operator!= (const G4FTFModel & right) const private
const G4FTFModel& G4FTFModel::operator= (const G4FTFModel & right) private
G4bool G4FTFModel::operator== (const G4FTFModel & right) const private
G4bool G4FTFModel::PutOnMassShell () private
Definition at line 549 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 549 of file G4FTFModel.cc
References CLHEP::HepLorentzVector::boostVector(), CheckKinematics(), ComputeNucleusProperties(), FinalizeKinematics(), G4cout, G4endl, GenerateDeltaIsobar(), G4VSplitableHadron::Get4Momentum(), G4FTFParameters::GetDofNuclearDestruction(), G4FTFParticipants::GetInteraction(), G4V3DNucleus::GetMassNumber(), G4FTFParameters::GetMaxPt2ofNuclearDestruction(), G4ReactionProduct::GetMomentum(), G4InteractionContent::GetProjectile(), GetProjectileNucleus(), G4FTFParameters::GetPt2ofNuclearDestruction(), GetTargetNucleus(), G4ReactionProduct::GetTotalEnergy(), GeV, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, G4FTFParticipants::Next(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, CLHEP::HepLorentzVector::perp2(), ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, CLHEP::HepLorentzVector::rapidity(), S(), SamplingNucleonKinematics(), G4VSplitableHadron::Set4Momentum(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), sqr(), G4FTFParticipants::StartLoop(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, theParameters, theParticipants, theProjectile, and CLHEP::HepLorentzVector::transform().
Referenced by GetStrings().
void G4FTFModel::ReggeonCascade () private
Definition at line 446 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 446 of file G4FTFModel.cc
References G4Nucleon::AreYouHit(), G4cout, G4endl, G4Exp(), G4UniformRand, G4FTFParameters::GetCofNuclearDestruction(), G4FTFParameters::GetCofNuclearDestructionPr(), G4FTFParameters::GetExcitationEnergyPerWoundedNucleon(), G4V3DNucleus::GetNextNucleon(), G4Nucleon::GetPosition(), GetProjectileNucleus(), G4FTFParameters::GetR2ofNuclearDestruction(), G4Nucleon::GetSplitableHadron(), GetTargetNucleus(), G4VSplitableHadron::GetTimeOfCreation(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4Nucleon::Hit(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, G4VSplitableHadron::SetStatus(), G4VSplitableHadron::SetTimeOfCreation(), sqr(), G4V3DNucleus::StartLoop(), TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, theParameters, theProjectile, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by GetStrings().
G4bool G4FTFModel::SamplingNucleonKinematics (G4double averagePt2, const G4double maxPt2, G4double dCor, G4V3DNucleus * nucleus, const G4LorentzVector & pResidual, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4double & mass2) private
Definition at line 2765 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 2765 of file G4FTFModel.cc
References Acts::Test::delta, CLHEP::HepLorentzVector::e(), G4cout, G4endl, GaussianPt(), G4Nucleon::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), GeV, CLHEP::HepLorentzVector::perp2(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), G4Nucleon::SetMomentum(), sqr(), tmp, CLHEP::Hep3Vector::x(), CLHEP::HepLorentzVector::x(), x, CLHEP::Hep3Vector::y(), and CLHEP::HepLorentzVector::y().
Referenced by PutOnMassShell().
void G4FTFModel::StoreInvolvedNucleon () private
Definition at line 396 of file G4FTFModel.cc.
View newest version in sPHENIX GitHub at line 396 of file G4FTFModel.cc
References G4Nucleon::AreYouHit(), G4cout, G4endl, G4V3DNucleus::GetNextNucleon(), GetProjectileNucleus(), GetTargetNucleus(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, G4V3DNucleus::StartLoop(), TheInvolvedNucleonsOfProjectile, and TheInvolvedNucleonsOfTarget.
Referenced by GetStrings().
Member Data Documentation
G4bool G4FTFModel::HighEnergyInter private
Definition at line 177 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4FTFModel.hh
Referenced by BuildStrings(), ExciteParticipants(), G4FTFModel(), GetResiduals(), GetStrings(), and Init().
G4double G4FTFModel::LowEnergyLimit private
Definition at line 176 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4FTFModel.hh
Referenced by G4FTFModel(), and Init().
G4int G4FTFModel::NumberOfInvolvedNucleonsOfProjectile private
Definition at line 167 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4FTFModel.hh
Referenced by BuildStrings(), G4FTFModel(), GetResiduals(), GetStrings(), PutOnMassShell(), ReggeonCascade(), StoreInvolvedNucleon(), and ~G4FTFModel().
G4int G4FTFModel::NumberOfInvolvedNucleonsOfTarget private
Definition at line 164 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4FTFModel.hh
Referenced by BuildStrings(), G4FTFModel(), GetResiduals(), GetStrings(), PutOnMassShell(), ReggeonCascade(), StoreInvolvedNucleon(), and ~G4FTFModel().
G4LorentzVector G4FTFModel::ProjectileResidual4Momentum private
Definition at line 179 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4int G4FTFModel::ProjectileResidualCharge private
Definition at line 181 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4double G4FTFModel::ProjectileResidualExcitationEnergy private
Definition at line 182 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4int G4FTFModel::ProjectileResidualMassNumber private
Definition at line 180 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), AdjustNucleonsAlgorithm_Sampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4LorentzVector G4FTFModel::TargetResidual4Momentum private
Definition at line 184 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4int G4FTFModel::TargetResidualCharge private
Definition at line 186 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 186 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4double G4FTFModel::TargetResidualExcitationEnergy private
Definition at line 187 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 187 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
G4int G4FTFModel::TargetResidualMassNumber private
Definition at line 185 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4FTFModel.hh
Referenced by AdjustNucleons(), AdjustNucleonsAlgorithm_afterSampling(), AdjustNucleonsAlgorithm_beforeSampling(), AdjustNucleonsAlgorithm_Sampling(), G4FTFModel(), GetResiduals(), Init(), and PutOnMassShell().
std::vector< G4VSplitableHadron* > G4FTFModel::theAdditionalString private
Definition at line 174 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4FTFModel.hh
Referenced by BuildStrings(), ExciteParticipants(), Init(), and ~G4FTFModel().
G4FTFAnnihilation* G4FTFModel::theAnnihilation private
Definition at line 172 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4FTFModel.hh
Referenced by ExciteParticipants(), and ~G4FTFModel().
G4ElasticHNScattering* G4FTFModel::theElastic private
Definition at line 171 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 171 of file G4FTFModel.hh
Referenced by ExciteParticipants(), and ~G4FTFModel().
G4DiffractiveExcitation* G4FTFModel::theExcitation private
Definition at line 170 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4FTFModel.hh
Referenced by BuildStrings(), ExciteParticipants(), and ~G4FTFModel().
G4Nucleon* G4FTFModel::TheInvolvedNucleonsOfProjectile[250] private
Definition at line 166 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4FTFModel.hh
Referenced by BuildStrings(), G4FTFModel(), GetResiduals(), GetStrings(), PutOnMassShell(), ReggeonCascade(), StoreInvolvedNucleon(), and ~G4FTFModel().
G4Nucleon* G4FTFModel::TheInvolvedNucleonsOfTarget[250] private
Definition at line 163 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4FTFModel.hh
Referenced by BuildStrings(), G4FTFModel(), GetResiduals(), GetStrings(), PutOnMassShell(), ReggeonCascade(), StoreInvolvedNucleon(), and ~G4FTFModel().
G4FTFParameters* G4FTFModel::theParameters private
Definition at line 169 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4FTFModel.hh
Referenced by AdjustNucleonsAlgorithm_beforeSampling(), AdjustNucleonsAlgorithm_Sampling(), BuildStrings(), ComputeNucleusProperties(), ExciteParticipants(), G4FTFModel(), GetStrings(), Init(), PutOnMassShell(), ReggeonCascade(), and ~G4FTFModel().
G4FTFParticipants G4FTFModel::theParticipants private
Definition at line 161 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4FTFModel.hh
Referenced by BuildStrings(), ExciteParticipants(), GetProjectileNucleus(), GetStrings(), GetTargetNucleus(), GetWoundedNucleus(), Init(), and PutOnMassShell().
G4ReactionProduct G4FTFModel::theProjectile private
Definition at line 160 of file G4FTFModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4FTFModel.hh
Referenced by GetStrings(), Init(), PutOnMassShell(), and ReggeonCascade().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4FTFModel.cc