ECCE @ EIC Software: G4LowEIonFragmentation Class Reference
G4LowEIonFragmentation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4LowEIonFragmentation.hh>
Public Member Functions
G4LowEIonFragmentation (G4ExcitationHandler *const value)
G4LowEIonFragmentation ()
virtual ~G4LowEIonFragmentation ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &thePrimary, G4Nucleus &theNucleus)
G4double GetCrossSection ()
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4LowEIonFragmentation (const G4LowEIonFragmentation &)
const G4LowEIonFragmentation & operator= (const G4LowEIonFragmentation &right)
G4bool operator== (const G4LowEIonFragmentation &right) const
G4bool operator!= (const G4LowEIonFragmentation &right) const
Private Attributes
G4HadFinalState theResult
const G4ParticleDefinition * proton
G4PreCompoundModel * theModel
G4ExcitationHandler * theHandler
G4int hits
G4int totalTries
G4double area
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 49 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LowEIonFragmentation.hh
Constructor & Destructor Documentation
G4LowEIonFragmentation::G4LowEIonFragmentation (G4ExcitationHandler *const value)
Definition at line 48 of file G4LowEIonFragmentation.cc.
View newest version in sPHENIX GitHub at line 48 of file G4LowEIonFragmentation.cc
References area, hits, G4Proton::Proton(), proton, theHandler, theModel, and totalTries.
G4LowEIonFragmentation::G4LowEIonFragmentation ()
Definition at line 58 of file G4LowEIonFragmentation.cc.
View newest version in sPHENIX GitHub at line 58 of file G4LowEIonFragmentation.cc
References area, hits, G4Proton::Proton(), proton, theHandler, theModel, and totalTries.
G4LowEIonFragmentation::~G4LowEIonFragmentation () virtual
Definition at line 68 of file G4LowEIonFragmentation.cc.
View newest version in sPHENIX GitHub at line 68 of file G4LowEIonFragmentation.cc
References theModel.
G4LowEIonFragmentation::G4LowEIonFragmentation (const G4LowEIonFragmentation &) private
Member Function Documentation
G4HadFinalState * G4LowEIonFragmentation::ApplyYourself (const G4HadProjectile & thePrimary, G4Nucleus & theNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 74 of file G4LowEIonFragmentation.cc.
View newest version in sPHENIX GitHub at line 74 of file G4LowEIonFragmentation.cc
References G4HadFinalState::AddSecondary(), area, G4ExcitationHandler::BreakItUp(), G4HadFinalState::Clear(), G4PreCompoundModel::DeExcite(), eplus, G4lrint(), G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetBaryonNumber(), G4HadProjectile::GetDefinition(), G4ReactionProduct::GetDefinition(), G4HadProjectile::GetGlobalTime(), G4ReactionProduct::GetMomentum(), G4Fancy3DNucleus::GetNextNucleon(), G4NucleiProperties::GetNuclearMass(), G4Fancy3DNucleus::GetOuterRadius(), G4Nucleon::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4Nucleon::GetPosition(), G4HadProjectile::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), hits, G4Fancy3DNucleus::Init(), k, momentum, pi, pinit(), proton, G4Fragment::SetCreationTime(), G4HadFinalState::SetEnergyChange(), G4Fragment::SetNumberOfExcitedParticle(), G4Fragment::SetNumberOfHoles(), G4HadFinalState::SetStatusChange(), G4Fancy3DNucleus::StartLoop(), stopAndKill, theHandler, theModel, theResult, Acts::VectorHelpers::time(), totalTries, CLHEP::HepLorentzVector::vect(), w, x, CLHEP::Hep3Vector::y(), and y.
G4double G4LowEIonFragmentation::GetCrossSection () inline
Definition at line 62 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 62 of file G4LowEIonFragmentation.hh
References area, hits, CLHEP::millibarn, and totalTries.
G4bool G4LowEIonFragmentation::operator!= (const G4LowEIonFragmentation & right) const private
const G4LowEIonFragmentation& G4LowEIonFragmentation::operator= (const G4LowEIonFragmentation & right) private
G4bool G4LowEIonFragmentation::operator== (const G4LowEIonFragmentation & right) const private
Member Data Documentation
G4double G4LowEIonFragmentation::area private
Definition at line 89 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 89 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself(), G4LowEIonFragmentation(), and GetCrossSection().
G4int G4LowEIonFragmentation::hits private
Definition at line 87 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 87 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself(), G4LowEIonFragmentation(), and GetCrossSection().
const G4ParticleDefinition* G4LowEIonFragmentation::proton private
Definition at line 80 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 80 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself(), and G4LowEIonFragmentation().
G4ExcitationHandler* G4LowEIonFragmentation::theHandler private
Definition at line 83 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself(), and G4LowEIonFragmentation().
G4PreCompoundModel* G4LowEIonFragmentation::theModel private
Definition at line 82 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 82 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself(), G4LowEIonFragmentation(), and ~G4LowEIonFragmentation().
G4HadFinalState G4LowEIonFragmentation::theResult private
Definition at line 79 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 79 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself().
G4int G4LowEIonFragmentation::totalTries private
Definition at line 88 of file G4LowEIonFragmentation.hh.
View newest version in sPHENIX GitHub at line 88 of file G4LowEIonFragmentation.hh
Referenced by ApplyYourself(), G4LowEIonFragmentation(), and GetCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4LowEIonFragmentation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4LowEIonFragmentation.cc