ECCE @ EIC Software: G4PropagatorInField Class Reference
G4PropagatorInField Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PropagatorInField.hh>
Public Member Functions
G4PropagatorInField (G4Navigator *theNavigator, G4FieldManager *detectorFieldMgr, G4VIntersectionLocator *vLocator=nullptr)
~G4PropagatorInField ()
G4double ComputeStep (G4FieldTrack &pFieldTrack, G4double pCurrentProposedStepLength, G4double &pNewSafety, G4VPhysicalVolume *pPhysVol=nullptr, G4bool canRelaxDeltaChord=false)
G4ThreeVector EndPosition () const
G4ThreeVector EndMomentumDir () const
G4bool IsParticleLooping () const
G4double GetEpsilonStep () const
void SetEpsilonStep (G4double newEps)
G4FieldManager * FindAndSetFieldManager (G4VPhysicalVolume *pCurrentPhysVol)
G4ChordFinder * GetChordFinder ()
G4int SetVerboseLevel (G4int verbose)
G4int GetVerboseLevel () const
G4int Verbose () const
void SetVerboseTrace (G4bool enable)
G4bool GetVerboseTrace ()
G4int GetMaxLoopCount () const
void SetMaxLoopCount (G4int new_max)
void printStatus (const G4FieldTrack &startFT, const G4FieldTrack &currentFT, G4double requestStep, G4double safety, G4int step, G4VPhysicalVolume *startVolume)
G4FieldTrack GetEndState () const
G4double GetMinimumEpsilonStep () const
void SetMinimumEpsilonStep (G4double newEpsMin)
G4double GetMaximumEpsilonStep () const
void SetMaximumEpsilonStep (G4double newEpsMax)
void SetLargestAcceptableStep (G4double newBigDist)
G4double GetLargestAcceptableStep ()
void SetTrajectoryFilter (G4VCurvedTrajectoryFilter *filter)
std::vector< G4ThreeVector > * GimmeTrajectoryVectorAndForgetIt () const
void ClearPropagatorState ()
void SetDetectorFieldManager (G4FieldManager *newGlobalFieldManager)
void SetUseSafetyForOptimization (G4bool)
G4bool GetUseSafetyForOptimization ()
G4bool IntersectChord (const G4ThreeVector &StartPointA, const G4ThreeVector &EndPointB, G4double &NewSafety, G4double &LinearStepLength, G4ThreeVector &IntersectionPoint)
G4bool IsFirstStepInVolume ()
G4bool IsLastStepInVolume ()
void PrepareNewTrack ()
G4VIntersectionLocator * GetIntersectionLocator ()
void SetIntersectionLocator (G4VIntersectionLocator *pLocator)
G4int GetIterationsToIncreaseChordDistance () const
void SetIterationsToIncreaseChordDistance (G4int numIters)
G4double GetDeltaIntersection () const
G4double GetDeltaOneStep () const
G4FieldManager * GetCurrentFieldManager ()
G4EquationOfMotion * GetCurrentEquationOfMotion ()
void SetNavigatorForPropagating (G4Navigator *SimpleOrMultiNavigator)
G4Navigator * GetNavigatorForPropagating ()
void SetThresholdNoZeroStep (G4int noAct, G4int noHarsh, G4int noAbandon)
G4int GetThresholdNoZeroSteps (G4int i)
G4double GetZeroStepThreshold ()
void SetZeroStepThreshold (G4double newLength)
void RefreshIntersectionLocator ()
Protected Member Functions
void PrintStepLengthDiagnostic (G4double currentProposedStepLength, G4double decreaseFactor, G4double stepTrial, const G4FieldTrack &aFieldTrack)
void ReportLoopingParticle (G4int count, G4double StepTaken, G4double stepRequest, const char *methodName, G4ThreeVector momentumVec, G4VPhysicalVolume *physVol)
void ReportStuckParticle (G4int noZeroSteps, G4double proposedStep, G4double lastTriedStep, G4VPhysicalVolume *physVol)
Private Attributes
G4int fMax_loop_count = 1000
G4int fIncreaseChordDistanceThreshold = 100
G4bool fUseSafetyForOptimisation = true
G4int fActionThreshold_NoZeroSteps = 2
G4int fSevereActionThreshold_NoZeroSteps = 10
G4int fAbandonThreshold_NoZeroSteps = 50
G4double fZeroStepThreshold = 0.0
G4double fLargestAcceptableStep
G4double kCarTolerance
G4bool fAllocatedLocator
G4FieldManager * fDetectorFieldMgr
G4VIntersectionLocator * fIntersectionLocator
G4VCurvedTrajectoryFilter * fpTrajectoryFilter = nullptr
G4Navigator * fNavigator
G4FieldManager * fCurrentFieldMgr
G4bool fSetFieldMgr = false
G4double fEpsilonStep
G4FieldTrack End_PointAndTangent
G4bool fParticleIsLooping = false
G4int fNoZeroStep = 0
G4double fFull_CurveLen_of_LastAttempt = -1
G4double fLast_ProposedStepLength = -1
G4ThreeVector fPreviousSftOrigin
G4double fPreviousSafety = 0.0
G4int fVerboseLevel = 0
G4bool fVerbTracePiF = false
G4bool fFirstStepInVolume = true
G4bool fLastStepInVolume = true
G4bool fNewTrack = true
Detailed Description
Definition at line 57 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 57 of file G4PropagatorInField.hh
Constructor & Destructor Documentation
G4PropagatorInField::G4PropagatorInField (G4Navigator * theNavigator, G4FieldManager * detectorFieldMgr, G4VIntersectionLocator * vLocator = nullptr)
Definition at line 55 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PropagatorInField.cc
References e, e5, fAllocatedLocator, fDetectorFieldMgr, fEpsilonStep, fIntersectionLocator, fLargestAcceptableStep, fPreviousSftOrigin, fVerboseLevel, fVerbTracePiF, fZeroStepThreshold, G4cout, G4endl, G4GeometryTolerance::GetInstance(), G4FieldManager::GetMaximumEpsilonStep(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, max, meter, micrometer, millimeter, and RefreshIntersectionLocator().
G4PropagatorInField::~G4PropagatorInField ()
Definition at line 99 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 99 of file G4PropagatorInField.cc
References fAllocatedLocator, and fIntersectionLocator.
Member Function Documentation
void G4PropagatorInField::ClearPropagatorState ()
Definition at line 674 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 674 of file G4PropagatorInField.cc
References End_PointAndTangent, fFull_CurveLen_of_LastAttempt, fLast_ProposedStepLength, fNoZeroStep, fParticleIsLooping, fPreviousSafety, and fPreviousSftOrigin.
Referenced by G4ITTransportation::StartTracking(), G4MonopoleTransportation::StartTracking(), G4Transportation::StartTracking(), and G4CoupledTransportation::StartTracking().
G4double G4PropagatorInField::ComputeStep (G4FieldTrack & pFieldTrack, G4double pCurrentProposedStepLength, G4double & pNewSafety, G4VPhysicalVolume * pPhysVol = nullptr, G4bool canRelaxDeltaChord = false)
Definition at line 118 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 118 of file G4PropagatorInField.cc
References G4ChordFinder::AdvanceChordLimited(), cm, G4VCurvedTrajectoryFilter::CreateNewTrajectorySegment(), e, End_PointAndTangent, epsilon(), fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, FatalException, fCurrentFieldMgr, fEpsilonStep, fFirstStepInVolume, fFull_CurveLen_of_LastAttempt, fIncreaseChordDistanceThreshold, FindAndSetFieldManager(), fIntersectionLocator, fLargestAcceptableStep, fLast_ProposedStepLength, fLastStepInVolume, fMax_loop_count, fNavigator, fNewTrack, fNoZeroStep, fParticleIsLooping, fPreviousSafety, fPreviousSftOrigin, fpTrajectoryFilter, fSetFieldMgr, fSevereActionThreshold_NoZeroSteps, fVerboseLevel, fZeroStepThreshold, G4cerr, G4cout, G4endl, G4Exception(), GetChordFinder(), G4FieldTrack::GetCurveLength(), G4ChordFinder::GetDeltaChord(), G4FieldManager::GetDeltaOneStep(), G4VPhysicalVolume::GetLogicalVolume(), G4FieldManager::GetMaximumEpsilonStep(), G4FieldManager::GetMinimumEpsilonStep(), G4FieldTrack::GetMomentum(), G4FieldTrack::GetMomentumDir(), G4VPhysicalVolume::GetName(), G4FieldTrack::GetPosition(), G4Navigator::GetWorldVolume(), IntersectChord(), JustWarning, kCarTolerance, kInfinity, G4Navigator::LocateGlobalPointWithinVolume(), max, message(), min, G4ChordFinder::OnComputeStep(), CLHEP::perMillion, printStatus(), PrintStepLengthDiagnostic(), RefreshIntersectionLocator(), ReportLoopingParticle(), ReportStuckParticle(), G4ChordFinder::SetDeltaChord(), SetEpsilonStep(), and G4VCurvedTrajectoryFilter::TakeIntermediatePoint().
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), and G4PathFinder::DoNextCurvedStep().
G4ThreeVector G4PropagatorInField::EndMomentumDir () const inline
G4ThreeVector G4PropagatorInField::EndPosition () const inline
G4FieldManager * G4PropagatorInField::FindAndSetFieldManager (G4VPhysicalVolume * pCurrentPhysVol)
Definition at line 694 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 694 of file G4PropagatorInField.cc
References fCurrentFieldMgr, fDetectorFieldMgr, fSetFieldMgr, G4Region::GetFieldManager(), G4LogicalVolume::GetFieldManager(), G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::GetRegion().
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), ComputeStep(), G4PathFinder::ComputeStep(), PHG4OuterHcalSteppingAction::FieldChecker(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4SynchrotronRadiation::PostStepDoIt(), and G4SynchrotronRadiationInMat::PostStepDoIt().
G4ChordFinder* G4PropagatorInField::GetChordFinder () inline
Referenced by ComputeStep(), RefreshIntersectionLocator(), SetVerboseLevel(), and G4CoupledTransportation::StartTracking().
G4EquationOfMotion* G4PropagatorInField::GetCurrentEquationOfMotion () inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4PathFinder::DoNextCurvedStep().
G4FieldManager* G4PropagatorInField::GetCurrentFieldManager () inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4DecayWithSpin::AtRestDoIt().
G4double G4PropagatorInField::GetDeltaIntersection () const inline
G4double G4PropagatorInField::GetDeltaOneStep () const inline
G4FieldTrack G4PropagatorInField::GetEndState () const inline
G4double G4PropagatorInField::GetEpsilonStep () const inline
G4VIntersectionLocator* G4PropagatorInField::GetIntersectionLocator () inline
Referenced by G4ErrorPropagatorManager::StartNavigator().
G4int G4PropagatorInField::GetIterationsToIncreaseChordDistance () const inline
G4double G4PropagatorInField::GetLargestAcceptableStep () inline
Referenced by G4BlineTracer::ComputeBlines().
G4double G4PropagatorInField::GetMaximumEpsilonStep () const inline
G4int G4PropagatorInField::GetMaxLoopCount () const inline
G4double G4PropagatorInField::GetMinimumEpsilonStep () const inline
G4Navigator* G4PropagatorInField::GetNavigatorForPropagating () inline
G4int G4PropagatorInField::GetThresholdNoZeroSteps (G4int i) inline
G4bool G4PropagatorInField::GetUseSafetyForOptimization () inline
G4int G4PropagatorInField::GetVerboseLevel () const inline
G4bool G4PropagatorInField::GetVerboseTrace () inline
G4double G4PropagatorInField::GetZeroStepThreshold () inline
std::vector< G4ThreeVector > * G4PropagatorInField::GimmeTrajectoryVectorAndForgetIt () const
Definition at line 649 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 649 of file G4PropagatorInField.cc
References fpTrajectoryFilter, and G4VCurvedTrajectoryFilter::GimmeThePointsAndForgetThem().
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), and G4ITTransportation::AlongStepDoIt().
G4bool G4PropagatorInField::IntersectChord (const G4ThreeVector & StartPointA, const G4ThreeVector & EndPointB, G4double & NewSafety, G4double & LinearStepLength, G4ThreeVector & IntersectionPoint) inline
Referenced by ComputeStep().
G4bool G4PropagatorInField::IsFirstStepInVolume () inline
G4bool G4PropagatorInField::IsLastStepInVolume () inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), and G4Transportation::PostStepDoIt().
G4bool G4PropagatorInField::IsParticleLooping () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), and G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
void G4PropagatorInField::PrepareNewTrack () inline
Referenced by G4PathFinder::PrepareNewTrack(), and G4Transportation::StartTracking().
void G4PropagatorInField::printStatus (const G4FieldTrack & startFT, const G4FieldTrack & currentFT, G4double requestStep, G4double safety, G4int step, G4VPhysicalVolume * startVolume)
Definition at line 524 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 524 of file G4PropagatorInField.cc
References fVerboseLevel, G4cout, G4endl, G4FieldTrack::GetCurveLength(), G4FieldTrack::GetMomentum(), G4FieldTrack::GetMomentumDir(), G4VPhysicalVolume::GetName(), G4FieldTrack::GetPosition(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ComputeStep().
void G4PropagatorInField::PrintStepLengthDiagnostic (G4double currentProposedStepLength, G4double decreaseFactor, G4double stepTrial, const G4FieldTrack & aFieldTrack) protected
Definition at line 614 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 614 of file G4PropagatorInField.cc
References fFull_CurveLen_of_LastAttempt, fLast_ProposedStepLength, fNoZeroStep, G4cout, and G4endl.
Referenced by ComputeStep().
void G4PropagatorInField::RefreshIntersectionLocator ()
Definition at line 107 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 107 of file G4PropagatorInField.cc
References fCurrentFieldMgr, fEpsilonStep, fIntersectionLocator, fUseSafetyForOptimisation, GetChordFinder(), G4FieldManager::GetDeltaIntersection(), G4VIntersectionLocator::SetChordFinderFor(), G4VIntersectionLocator::SetDeltaIntersectionFor(), G4VIntersectionLocator::SetEpsilonStepFor(), and G4VIntersectionLocator::SetSafetyParametersFor().
Referenced by ComputeStep(), and G4PropagatorInField().
void G4PropagatorInField::ReportLoopingParticle (G4int count, G4double StepTaken, G4double stepRequest, const char * methodName, G4ThreeVector momentumVec, G4VPhysicalVolume * physVol) protected
Definition at line 755 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 755 of file G4PropagatorInField.cc
References cm, Acts::UnitConstants::g, G4endl, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4VPhysicalVolume::GetName(), JustWarning, CLHEP::Hep3Vector::mag(), material(), message(), mm, and CLHEP::prec.
Referenced by ComputeStep().
void G4PropagatorInField::ReportStuckParticle (G4int noZeroSteps, G4double proposedStep, G4double lastTriedStep, G4VPhysicalVolume * physVol) protected
Definition at line 801 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 801 of file G4PropagatorInField.cc
References G4endl, G4Exception(), G4VPhysicalVolume::GetName(), JustWarning, and message().
Referenced by ComputeStep().
void G4PropagatorInField::SetDetectorFieldManager (G4FieldManager * newGlobalFieldManager) inline
void G4PropagatorInField::SetEpsilonStep (G4double newEps) inline
Referenced by ComputeStep().
void G4PropagatorInField::SetIntersectionLocator (G4VIntersectionLocator * pLocator) inline
void G4PropagatorInField::SetIterationsToIncreaseChordDistance (G4int numIters) inline
void G4PropagatorInField::SetLargestAcceptableStep (G4double newBigDist) inline
Referenced by G4BlineTracer::ComputeBlines(), and DetectorConstruction::SetMaxStepLength().
void G4PropagatorInField::SetMaximumEpsilonStep (G4double newEpsMax) inline
Referenced by CCalDetectorConstruction::Construct(), F04GlobalField::ConstructField(), ExUCNDetectorConstruction::ConstructSDandField(), and F05DetectorConstruction::ConstructSDandField().
void G4PropagatorInField::SetMaxLoopCount (G4int new_max) inline
void G4PropagatorInField::SetMinimumEpsilonStep (G4double newEpsMin) inline
Referenced by CCalDetectorConstruction::Construct(), F04GlobalField::ConstructField(), ExUCNDetectorConstruction::ConstructSDandField(), and F05DetectorConstruction::ConstructSDandField().
void G4PropagatorInField::SetNavigatorForPropagating (G4Navigator * SimpleOrMultiNavigator) inline
Referenced by G4PathFinder::EnableParallelNavigation(), and G4TransportationManager::SetNavigatorForTracking().
void G4PropagatorInField::SetThresholdNoZeroStep (G4int noAct, G4int noHarsh, G4int noAbandon) inline
void G4PropagatorInField::SetTrajectoryFilter (G4VCurvedTrajectoryFilter * filter)
Definition at line 667 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 667 of file G4PropagatorInField.cc
References filter, and fpTrajectoryFilter.
Referenced by G4TrackingMessenger::SetNewValue().
void G4PropagatorInField::SetUseSafetyForOptimization (G4bool) inline
G4int G4PropagatorInField::SetVerboseLevel (G4int verbose)
Definition at line 738 of file G4PropagatorInField.cc.
View newest version in sPHENIX GitHub at line 738 of file G4PropagatorInField.cc
References fVerboseLevel, G4cout, G4endl, GetChordFinder(), G4ChordFinder::GetIntegrationDriver(), and G4VIntegrationDriver::SetVerboseLevel().
void G4PropagatorInField::SetVerboseTrace (G4bool enable) inline
void G4PropagatorInField::SetZeroStepThreshold (G4double newLength) inline
G4int G4PropagatorInField::Verbose () const inline
Member Data Documentation
G4FieldTrack G4PropagatorInField::End_PointAndTangent private
Definition at line 282 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 282 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), and ComputeStep().
G4int G4PropagatorInField::fAbandonThreshold_NoZeroSteps = 50 private
Definition at line 237 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 237 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4int G4PropagatorInField::fActionThreshold_NoZeroSteps = 2 private
Definition at line 235 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 235 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4bool G4PropagatorInField::fAllocatedLocator private
Definition at line 248 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 248 of file G4PropagatorInField.hh
Referenced by G4PropagatorInField(), and ~G4PropagatorInField().
G4FieldManager* G4PropagatorInField::fCurrentFieldMgr private
Definition at line 276 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 276 of file G4PropagatorInField.hh
Referenced by ComputeStep(), FindAndSetFieldManager(), and RefreshIntersectionLocator().
G4FieldManager* G4PropagatorInField::fDetectorFieldMgr private
Definition at line 253 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 253 of file G4PropagatorInField.hh
Referenced by FindAndSetFieldManager(), and G4PropagatorInField().
G4double G4PropagatorInField::fEpsilonStep private
Definition at line 281 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 281 of file G4PropagatorInField.hh
Referenced by ComputeStep(), G4PropagatorInField(), and RefreshIntersectionLocator().
G4bool G4PropagatorInField::fFirstStepInVolume = true private
Definition at line 298 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 298 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4double G4PropagatorInField::fFull_CurveLen_of_LastAttempt = -1 private
Definition at line 287 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 287 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), ComputeStep(), and PrintStepLengthDiagnostic().
G4int G4PropagatorInField::fIncreaseChordDistanceThreshold = 100 private
Definition at line 229 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 229 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4VIntersectionLocator* G4PropagatorInField::fIntersectionLocator private
Definition at line 256 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 256 of file G4PropagatorInField.hh
Referenced by ComputeStep(), G4PropagatorInField(), RefreshIntersectionLocator(), and ~G4PropagatorInField().
G4double G4PropagatorInField::fLargestAcceptableStep private
Definition at line 241 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 241 of file G4PropagatorInField.hh
Referenced by ComputeStep(), and G4PropagatorInField().
G4double G4PropagatorInField::fLast_ProposedStepLength = -1 private
Definition at line 288 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 288 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), ComputeStep(), and PrintStepLengthDiagnostic().
G4bool G4PropagatorInField::fLastStepInVolume = true private
Definition at line 299 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 299 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4int G4PropagatorInField::fMax_loop_count = 1000 private
Definition at line 227 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 227 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4Navigator* G4PropagatorInField::fNavigator private
Definition at line 266 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 266 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4bool G4PropagatorInField::fNewTrack = true private
Definition at line 300 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 300 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4int G4PropagatorInField::fNoZeroStep = 0 private
Definition at line 284 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 284 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), ComputeStep(), and PrintStepLengthDiagnostic().
G4bool G4PropagatorInField::fParticleIsLooping = false private
Definition at line 283 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 283 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), and ComputeStep().
G4double G4PropagatorInField::fPreviousSafety = 0.0 private
Definition at line 291 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 291 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), and ComputeStep().
G4ThreeVector G4PropagatorInField::fPreviousSftOrigin private
Definition at line 290 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 290 of file G4PropagatorInField.hh
Referenced by ClearPropagatorState(), ComputeStep(), and G4PropagatorInField().
G4VCurvedTrajectoryFilter* G4PropagatorInField::fpTrajectoryFilter = nullptr private
Definition at line 259 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 259 of file G4PropagatorInField.hh
Referenced by ComputeStep(), GimmeTrajectoryVectorAndForgetIt(), and SetTrajectoryFilter().
G4bool G4PropagatorInField::fSetFieldMgr = false private
Definition at line 278 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 278 of file G4PropagatorInField.hh
Referenced by ComputeStep(), and FindAndSetFieldManager().
G4int G4PropagatorInField::fSevereActionThreshold_NoZeroSteps = 10 private
Definition at line 236 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 236 of file G4PropagatorInField.hh
Referenced by ComputeStep().
G4bool G4PropagatorInField::fUseSafetyForOptimisation = true private
Definition at line 230 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 230 of file G4PropagatorInField.hh
Referenced by RefreshIntersectionLocator().
G4int G4PropagatorInField::fVerboseLevel = 0 private
Definition at line 294 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 294 of file G4PropagatorInField.hh
Referenced by ComputeStep(), G4PropagatorInField(), printStatus(), and SetVerboseLevel().
G4bool G4PropagatorInField::fVerbTracePiF = false private
Definition at line 295 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 295 of file G4PropagatorInField.hh
Referenced by G4PropagatorInField().
G4double G4PropagatorInField::fZeroStepThreshold = 0.0 private
Definition at line 238 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 238 of file G4PropagatorInField.hh
Referenced by ComputeStep(), and G4PropagatorInField().
G4double G4PropagatorInField::kCarTolerance private
Definition at line 245 of file G4PropagatorInField.hh.
View newest version in sPHENIX GitHub at line 245 of file G4PropagatorInField.hh
Referenced by ComputeStep(), and G4PropagatorInField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PropagatorInField.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4PropagatorInField.cc