ECCE @ EIC Software: G4LowEnergyRayleigh Class Reference
G4LowEnergyRayleigh Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyRayleigh.hh>
Public Member Functions
G4LowEnergyRayleigh (const G4String &processName="LowEnRayleigh")
~G4LowEnergyRayleigh ()
G4bool IsApplicable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &photon)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep)
G4double DumpMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
Private Member Functions
G4LowEnergyRayleigh & operator= (const G4LowEnergyRayleigh &right)
G4LowEnergyRayleigh (const G4LowEnergyRayleigh &)
Private Attributes
G4double lowEnergyLimit
G4double highEnergyLimit
G4RDVEMDataSet * meanFreePathTable
G4RDVEMDataSet * formFactorData
G4RDVCrossSectionHandler * crossSectionHandler
const G4double intrinsicLowEnergyLimit
const G4double intrinsicHighEnergyLimit
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 58 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 58 of file G4LowEnergyRayleigh.hh
Constructor & Destructor Documentation
G4LowEnergyRayleigh::G4LowEnergyRayleigh (const G4String & processName = "LowEnRayleigh")
Definition at line 71 of file G4LowEnergyRayleigh.cc.
View newest version in sPHENIX GitHub at line 71 of file G4LowEnergyRayleigh.cc
References crossSectionHandler, FatalException, formFactorData, G4cout, G4endl, G4Exception(), G4VProcess::GetProcessName(), GeV, highEnergyLimit, intrinsicHighEnergyLimit, intrinsicLowEnergyLimit, keV, G4RDVEMDataSet::LoadData(), lowEnergyLimit, meanFreePathTable, and G4VProcess::verboseLevel.
G4LowEnergyRayleigh::~G4LowEnergyRayleigh ()
Definition at line 105 of file G4LowEnergyRayleigh.cc.
View newest version in sPHENIX GitHub at line 105 of file G4LowEnergyRayleigh.cc
References crossSectionHandler, formFactorData, and meanFreePathTable.
G4LowEnergyRayleigh::G4LowEnergyRayleigh (const G4LowEnergyRayleigh &) private
Member Function Documentation
void G4LowEnergyRayleigh::BuildPhysicsTable (const G4ParticleDefinition & photon) virtual
Reimplemented from G4VProcess.
Definition at line 112 of file G4LowEnergyRayleigh.cc.
View newest version in sPHENIX GitHub at line 112 of file G4LowEnergyRayleigh.cc
References G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4RDVCrossSectionHandler::Clear(), crossSectionHandler, G4RDVCrossSectionHandler::LoadData(), and meanFreePathTable.
G4double G4LowEnergyRayleigh::DumpMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) inline
Definition at line 73 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 73 of file G4LowEnergyRayleigh.hh
References GetMeanFreePath().
G4double G4LowEnergyRayleigh::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4VDiscreteProcess.
Definition at line 200 of file G4LowEnergyRayleigh.cc.
View newest version in sPHENIX GitHub at line 200 of file G4LowEnergyRayleigh.cc
References DBL_MAX, energy, G4RDVEMDataSet::FindValue(), G4Track::GetDynamicParticle(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), highEnergyLimit, lowEnergyLimit, meanFreePathTable, and G4InuclParticleNames::photon.
Referenced by DumpMeanFreePath().
G4bool G4LowEnergyRayleigh::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 195 of file G4LowEnergyRayleigh.cc.
View newest version in sPHENIX GitHub at line 195 of file G4LowEnergyRayleigh.cc
References G4Gamma::Gamma().
G4LowEnergyRayleigh& G4LowEnergyRayleigh::operator= (const G4LowEnergyRayleigh & right) private
G4VParticleChange * G4LowEnergyRayleigh::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 123 of file G4LowEnergyRayleigh.cc.
View newest version in sPHENIX GitHub at line 123 of file G4LowEnergyRayleigh.cc
References G4VProcess::aParticleChange, source.hepunit::c_light, cm, crossSectionHandler, e, G4RDVEMDataSet::FindValue(), formFactorData, fStopAndKill, G4UniformRand, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), source.hepunit::h_Planck, G4ParticleChange::Initialize(), lowEnergyLimit, phi, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VParticleChange::SetNumberOfSecondaries(), twopi, x, and Z.
Member Data Documentation
G4RDVCrossSectionHandler* G4LowEnergyRayleigh::crossSectionHandler private
Definition at line 96 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LowEnergyRayleigh.hh
Referenced by BuildPhysicsTable(), G4LowEnergyRayleigh(), PostStepDoIt(), and ~G4LowEnergyRayleigh().
G4RDVEMDataSet* G4LowEnergyRayleigh::formFactorData private
Definition at line 94 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 94 of file G4LowEnergyRayleigh.hh
Referenced by G4LowEnergyRayleigh(), PostStepDoIt(), and ~G4LowEnergyRayleigh().
G4double G4LowEnergyRayleigh::highEnergyLimit private
Definition at line 91 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 91 of file G4LowEnergyRayleigh.hh
Referenced by G4LowEnergyRayleigh(), and GetMeanFreePath().
const G4double G4LowEnergyRayleigh::intrinsicHighEnergyLimit private
Definition at line 99 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 99 of file G4LowEnergyRayleigh.hh
Referenced by G4LowEnergyRayleigh().
const G4double G4LowEnergyRayleigh::intrinsicLowEnergyLimit private
Definition at line 98 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 98 of file G4LowEnergyRayleigh.hh
Referenced by G4LowEnergyRayleigh().
G4double G4LowEnergyRayleigh::lowEnergyLimit private
Definition at line 90 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 90 of file G4LowEnergyRayleigh.hh
Referenced by G4LowEnergyRayleigh(), GetMeanFreePath(), and PostStepDoIt().
G4RDVEMDataSet* G4LowEnergyRayleigh::meanFreePathTable private
Definition at line 93 of file G4LowEnergyRayleigh.hh.
View newest version in sPHENIX GitHub at line 93 of file G4LowEnergyRayleigh.hh
Referenced by BuildPhysicsTable(), G4LowEnergyRayleigh(), GetMeanFreePath(), and ~G4LowEnergyRayleigh().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyRayleigh.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4LowEnergyRayleigh.cc