ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Sphere.cc File Reference
pyG4Sphere.cc File Reference
#include <boost/python.hpp>
#include "G4Sphere.hh"
Namespaces
namespace pyG4Sphere
Functions
G4Sphere * pyG4Sphere::CreateSphere (const G4String &name, G4double pRmin, G4double pRmax, G4double pSPhi, G4double pDPhi, G4double pSTheta, G4double pDTheta)
void export_G4Sphere ()
Function Documentation
void export_G4Sphere ()
Definition at line 56 of file pyG4Sphere.cc.
View newest version in sPHENIX GitHub at line 56 of file pyG4Sphere.cc
References pyG4Sphere::CreateSphere(), G4Sphere::GetDeltaPhiAngle(), G4Sphere::GetDeltaThetaAngle(), G4Sphere::GetInsideRadius(), G4Sphere::GetOuterRadius(), G4Sphere::GetStartPhiAngle(), G4Sphere::GetStartThetaAngle(), init(), G4Sphere::SetDeltaPhiAngle(), G4Sphere::SetDeltaThetaAngle(), G4Sphere::SetInsideRadius(), G4Sphere::SetOuterRadius(), G4Sphere::SetStartPhiAngle(), and G4Sphere::SetStartThetaAngle().
Referenced by BOOST_PYTHON_MODULE().