ECCE @ EIC Software: G4FastStep Class Reference
G4FastStep Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4FastStep.hh>
Public Member Functions
void KillPrimaryTrack ()
void ProposePrimaryTrackFinalPosition (const G4ThreeVector &, G4bool localCoordinates=true)
void SetPrimaryTrackFinalPosition (const G4ThreeVector &, G4bool localCoordinates=true)
void ProposePrimaryTrackFinalTime (G4double)
void SetPrimaryTrackFinalTime (G4double)
void ProposePrimaryTrackFinalProperTime (G4double)
void SetPrimaryTrackFinalProperTime (G4double)
void ProposePrimaryTrackFinalMomentumDirection (const G4ThreeVector &, G4bool localCoordinates=true)
void SetPrimaryTrackFinalMomentum (const G4ThreeVector &, G4bool localCoordinates=true)
void ProposePrimaryTrackFinalKineticEnergy (G4double)
void SetPrimaryTrackFinalKineticEnergy (G4double)
void ProposePrimaryTrackFinalKineticEnergyAndDirection (G4double, const G4ThreeVector &, G4bool localCoordinates=true)
void SetPrimaryTrackFinalKineticEnergyAndDirection (G4double, const G4ThreeVector &, G4bool localCoordinates=true)
void ProposePrimaryTrackFinalPolarization (const G4ThreeVector &, G4bool localCoordinates=true)
void SetPrimaryTrackFinalPolarization (const G4ThreeVector &, G4bool localCoordinates=true)
void ProposePrimaryTrackPathLength (G4double)
void SetPrimaryTrackPathLength (G4double)
void ProposePrimaryTrackFinalEventBiasingWeight (G4double)
void SetPrimaryTrackFinalEventBiasingWeight (G4double)
void SetNumberOfSecondaryTracks (G4int)
G4int GetNumberOfSecondaryTracks ()
G4Track * CreateSecondaryTrack (const G4DynamicParticle &, G4ThreeVector, G4ThreeVector, G4double, G4bool localCoordinates=true)
G4Track * CreateSecondaryTrack (const G4DynamicParticle &, G4ThreeVector, G4double, G4bool localCoordinates=true)
G4Track * GetSecondaryTrack (G4int)
void ProposeTotalEnergyDeposited (G4double anEnergyPart)
void SetTotalEnergyDeposited (G4double anEnergyPart)
G4double GetTotalEnergyDeposited () const
void ForceSteppingHitInvocation ()
G4FastStep ()
virtual ~G4FastStep ()
G4bool operator== (const G4FastStep &right) const
G4bool operator!= (const G4FastStep &right) const
G4Step * UpdateStepForAtRest (G4Step *Step)
G4Step * UpdateStepForPostStep (G4Step *Step)
void Initialize (const G4FastTrack &)
void DumpInfo () const
G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4FastStep (const G4FastStep &right)
G4FastStep & operator= (const G4FastStep &right)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Private Member Functions
void Initialize (const G4Track &)
void SetMomentumChange (G4double Px, G4double Py, G4double Pz)
void SetMomentumChange (const G4ThreeVector &Pfinal)
Private Attributes
G4ParticleMomentum theMomentumChange
G4ThreeVector thePolarizationChange
G4double theEnergyChange
G4ThreeVector thePositionChange
G4double theTimeChange
G4double theProperTimeChange
const G4FastTrack * fFastTrack
G4double theWeightChange
Additional Inherited Members
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 90 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FastStep.hh
Constructor & Destructor Documentation
G4FastStep::G4FastStep ()
Definition at line 297 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 297 of file G4FastStep.cc
References G4cerr, G4endl, and G4VParticleChange::verboseLevel.
G4FastStep::~G4FastStep () virtual
Definition at line 311 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 311 of file G4FastStep.cc
References G4cerr, G4endl, and G4VParticleChange::verboseLevel.
G4FastStep::G4FastStep (const G4FastStep & right) protected
Definition at line 320 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 320 of file G4FastStep.cc
References right.
Member Function Documentation
G4bool G4FastStep::CheckIt (const G4Track & aTrack) virtual
Reimplemented from G4VParticleChange.
Definition at line 465 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 465 of file G4FastStep.cc
References kdfinder::abs(), G4VParticleChange::CheckIt(), DumpInfo(), FatalException, G4cout, G4endl, G4Exception(), G4VParticleChange::GetAccuracyForException(), G4VParticleChange::GetAccuracyForWarning(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetProperTime(), JustWarning, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), MeV, ns, theEnergyChange, theMomentumChange, theProperTimeChange, and theTimeChange.
Referenced by UpdateStepForAtRest(), and UpdateStepForPostStep().
G4Track * G4FastStep::CreateSecondaryTrack (const G4DynamicParticle & dynamics, G4ThreeVector polarization, G4ThreeVector position, G4double time, G4bool localCoordinates = true)
Definition at line 202 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 202 of file G4FastStep.cc
References G4DynamicParticle::SetPolarization(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Par01PiModel::DoIt().
G4Track * G4FastStep::CreateSecondaryTrack (const G4DynamicParticle & dynamics, G4ThreeVector position, G4double time, G4bool localCoordinates = true)
Definition at line 224 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 224 of file G4FastStep.cc
References G4VParticleChange::AddSecondary(), fFastTrack, G4FastTrack::GetInverseAffineTransformation(), G4DynamicParticle::GetPolarization(), G4DynamicParticle::SetMomentumDirection(), G4DynamicParticle::SetPolarization(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4FastStep::DumpInfo () const virtual
Reimplemented from G4VParticleChange.
Definition at line 442 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 442 of file G4FastStep.cc
References G4VParticleChange::DumpInfo(), G4BestUnit, G4cout, G4endl, theEnergyChange, theMomentumChange, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CheckIt().
void G4FastStep::ForceSteppingHitInvocation ()
G4int G4FastStep::GetNumberOfSecondaryTracks ()
G4Track* G4FastStep::GetSecondaryTrack (G4int)
G4double G4FastStep::GetTotalEnergyDeposited () const
void G4FastStep::Initialize (const G4FastTrack & fastTrack)
Definition at line 53 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 53 of file G4FastStep.cc
References AvoidHitInvocation, fFastTrack, G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetPolarization(), G4Track::GetPosition(), G4FastTrack::GetPrimaryTrack(), G4DynamicParticle::GetProperTime(), G4Track::GetWeight(), G4VParticleChange::Initialize(), theEnergyChange, theMomentumChange, thePolarizationChange, thePositionChange, theProperTimeChange, G4VParticleChange::theSteppingControlFlag, theTimeChange, and theWeightChange.
Referenced by G4FastSimulationManager::AtRestGetFastSimulationManagerTrigger(), and G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger().
void G4FastStep::Initialize (const G4Track &) private virtual
Reimplemented from G4VParticleChange.
Definition at line 286 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 286 of file G4FastStep.cc
References FatalException, G4endl, and G4Exception().
void G4FastStep::KillPrimaryTrack ()
Definition at line 87 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 87 of file G4FastStep.cc
References fStopAndKill, G4VParticleChange::ProposeTrackStatus(), and SetPrimaryTrackFinalKineticEnergy().
Referenced by Par01PionShowerModel::DoIt(), Par01EMShowerModel::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelEMCal::DoIt(), and GFlashShowerModel::ElectronDoIt().
G4bool G4FastStep::operator!= (const G4FastStep & right) const
Definition at line 360 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 360 of file G4FastStep.cc
G4FastStep & G4FastStep::operator= (const G4FastStep & right) protected
Definition at line 327 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 327 of file G4FastStep.cc
References fFastTrack, G4VParticleChange::operator=(), theEnergyChange, G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, theMomentumChange, G4VParticleChange::theNumberOfSecondaries, thePolarizationChange, thePositionChange, theProperTimeChange, G4VParticleChange::theSizeOftheListOfSecondaries, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, theTimeChange, G4VParticleChange::theTrueStepLength, and theWeightChange.
G4bool G4FastStep::operator== (const G4FastStep & right) const
Definition at line 355 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 355 of file G4FastStep.cc
void G4FastStep::ProposePrimaryTrackFinalEventBiasingWeight (G4double)
void G4FastStep::ProposePrimaryTrackFinalKineticEnergy (G4double)
void G4FastStep::ProposePrimaryTrackFinalKineticEnergyAndDirection (G4double kineticEnergy, const G4ThreeVector & direction, G4bool localCoordinates = true)
Definition at line 150 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 150 of file G4FastStep.cc
References fFastTrack, G4FastTrack::GetInverseAffineTransformation(), SetMomentumChange(), SetPrimaryTrackFinalKineticEnergy(), and CLHEP::Hep3Vector::unit().
Referenced by SetPrimaryTrackFinalKineticEnergyAndDirection().
void G4FastStep::ProposePrimaryTrackFinalMomentumDirection (const G4ThreeVector & momentum, G4bool localCoordinates = true)
Definition at line 124 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 124 of file G4FastStep.cc
References fFastTrack, G4FastTrack::GetInverseAffineTransformation(), momentum, SetMomentumChange(), and CLHEP::Hep3Vector::unit().
Referenced by SetPrimaryTrackFinalMomentum().
void G4FastStep::ProposePrimaryTrackFinalPolarization (const G4ThreeVector & polarization, G4bool localCoordinates = true)
Definition at line 178 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 178 of file G4FastStep.cc
References fFastTrack, G4FastTrack::GetInverseAffineTransformation(), and thePolarizationChange.
Referenced by SetPrimaryTrackFinalPolarization().
void G4FastStep::ProposePrimaryTrackFinalPosition (const G4ThreeVector & position, G4bool localCoordinates = true)
Definition at line 98 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 98 of file G4FastStep.cc
References fFastTrack, G4FastTrack::GetInverseAffineTransformation(), position, and thePositionChange.
Referenced by Par01PiModel::DoIt(), Par02FastSimModelTracker::DoIt(), and SetPrimaryTrackFinalPosition().
void G4FastStep::ProposePrimaryTrackFinalProperTime (G4double)
void G4FastStep::ProposePrimaryTrackFinalTime (G4double)
void G4FastStep::ProposePrimaryTrackPathLength (G4double)
Referenced by Par01PionShowerModel::DoIt(), Par01EMShowerModel::DoIt(), Par02FastSimModelEMCal::DoIt(), and Par02FastSimModelHCal::DoIt().
void G4FastStep::ProposeTotalEnergyDeposited (G4double anEnergyPart)
Referenced by Par01PionShowerModel::DoIt(), Par01EMShowerModel::DoIt(), Par02FastSimModelEMCal::DoIt(), and Par02FastSimModelHCal::DoIt().
void G4FastStep::SetMomentumChange (G4double Px, G4double Py, G4double Pz) private
Referenced by ProposePrimaryTrackFinalKineticEnergyAndDirection(), and ProposePrimaryTrackFinalMomentumDirection().
void G4FastStep::SetMomentumChange (const G4ThreeVector & Pfinal) private
void G4FastStep::SetNumberOfSecondaryTracks (G4int)
Referenced by Par01PiModel::DoIt().
void G4FastStep::SetPrimaryTrackFinalEventBiasingWeight (G4double)
void G4FastStep::SetPrimaryTrackFinalKineticEnergy (G4double)
Referenced by KillPrimaryTrack(), and ProposePrimaryTrackFinalKineticEnergyAndDirection().
void G4FastStep::SetPrimaryTrackFinalKineticEnergyAndDirection (G4double kineticEnergy, const G4ThreeVector & direction, G4bool localCoordinates = true)
Definition at line 166 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 166 of file G4FastStep.cc
References ProposePrimaryTrackFinalKineticEnergyAndDirection().
void G4FastStep::SetPrimaryTrackFinalMomentum (const G4ThreeVector & momentum, G4bool localCoordinates = true)
Definition at line 139 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 139 of file G4FastStep.cc
References ProposePrimaryTrackFinalMomentumDirection().
void G4FastStep::SetPrimaryTrackFinalPolarization (const G4ThreeVector & polarization, G4bool localCoordinates = true)
Definition at line 192 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 192 of file G4FastStep.cc
References ProposePrimaryTrackFinalPolarization().
void G4FastStep::SetPrimaryTrackFinalPosition (const G4ThreeVector & position, G4bool localCoordinates = true)
Definition at line 113 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 113 of file G4FastStep.cc
References ProposePrimaryTrackFinalPosition().
void G4FastStep::SetPrimaryTrackFinalProperTime (G4double)
void G4FastStep::SetPrimaryTrackFinalTime (G4double)
void G4FastStep::SetPrimaryTrackPathLength (G4double)
Referenced by GFlashShowerModel::ElectronDoIt().
void G4FastStep::SetTotalEnergyDeposited (G4double anEnergyPart)
Referenced by GFlashShowerModel::ElectronDoIt().
G4Step * G4FastStep::UpdateStepForAtRest (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 406 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 406 of file G4FastStep.cc
References G4StepPoint::AddLocalTime(), CheckIt(), G4VParticleChange::debugFlag, G4Track::GetGlobalTime(), G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4StepPoint::SetGlobalTime(), G4StepPoint::SetKineticEnergy(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPolarization(), G4StepPoint::SetPosition(), G4StepPoint::SetProperTime(), G4StepPoint::SetWeight(), theEnergyChange, theMomentumChange, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theWeightChange, and G4VParticleChange::UpdateStepInfo().
G4Step * G4FastStep::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 369 of file G4FastStep.cc.
View newest version in sPHENIX GitHub at line 369 of file G4FastStep.cc
References G4StepPoint::AddLocalTime(), CheckIt(), G4VParticleChange::debugFlag, G4Track::GetGlobalTime(), G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4StepPoint::SetGlobalTime(), G4StepPoint::SetKineticEnergy(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPolarization(), G4StepPoint::SetPosition(), G4StepPoint::SetProperTime(), G4StepPoint::SetWeight(), theEnergyChange, theMomentumChange, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theWeightChange, and G4VParticleChange::UpdateStepInfo().
Member Data Documentation
const G4FastTrack* G4FastStep::fFastTrack private
Definition at line 365 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 365 of file G4FastStep.hh
Referenced by CreateSecondaryTrack(), Initialize(), operator=(), ProposePrimaryTrackFinalKineticEnergyAndDirection(), ProposePrimaryTrackFinalMomentumDirection(), ProposePrimaryTrackFinalPolarization(), and ProposePrimaryTrackFinalPosition().
G4double G4FastStep::theEnergyChange private
Definition at line 353 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 353 of file G4FastStep.hh
Referenced by CheckIt(), DumpInfo(), Initialize(), operator=(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4ParticleMomentum G4FastStep::theMomentumChange private
Definition at line 347 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 347 of file G4FastStep.hh
Referenced by CheckIt(), DumpInfo(), Initialize(), operator=(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4ThreeVector G4FastStep::thePolarizationChange private
Definition at line 350 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 350 of file G4FastStep.hh
Referenced by DumpInfo(), Initialize(), operator=(), ProposePrimaryTrackFinalPolarization(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4ThreeVector G4FastStep::thePositionChange private
Definition at line 356 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 356 of file G4FastStep.hh
Referenced by DumpInfo(), Initialize(), operator=(), ProposePrimaryTrackFinalPosition(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4FastStep::theProperTimeChange private
Definition at line 362 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 362 of file G4FastStep.hh
Referenced by CheckIt(), DumpInfo(), Initialize(), operator=(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4FastStep::theTimeChange private
Definition at line 359 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 359 of file G4FastStep.hh
Referenced by CheckIt(), DumpInfo(), Initialize(), operator=(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4FastStep::theWeightChange private
Definition at line 368 of file G4FastStep.hh.
View newest version in sPHENIX GitHub at line 368 of file G4FastStep.hh
Referenced by Initialize(), operator=(), UpdateStepForAtRest(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4FastStep.hh
geant4/tree/geant4-10.6-release/source/processes/parameterisation/src/G4FastStep.cc