ECCE @ EIC Software: G4EvaporationChannel Class Reference
G4EvaporationChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4EvaporationChannel.hh>
Public Member Functions
G4EvaporationChannel (G4int A, G4int Z, G4EvaporationProbability *)
~G4EvaporationChannel () override
void Initialise () override
G4double GetEmissionProbability (G4Fragment *fragment) override
G4Fragment * EmittedFragment (G4Fragment *theNucleus) override
Public Member Functions inherited from G4VEvaporationChannel
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void Dump () const
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Private Member Functions
G4EvaporationChannel (const G4EvaporationChannel &right)
const G4EvaporationChannel & operator= (const G4EvaporationChannel &right)
G4bool operator== (const G4EvaporationChannel &right) const
G4bool operator!= (const G4EvaporationChannel &right) const
Private Attributes
G4int theA
G4int theZ
G4int resA
G4int resZ
G4double mass
G4double resMass
G4double evapMass
G4double evapMass2
G4EvaporationProbability * theProbability
G4CoulombBarrier * theCoulombBarrier
G4NuclearLevelData * theLevelData
Additional Inherited Members
Protected Attributes inherited from G4VEvaporationChannel
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 45 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 45 of file G4EvaporationChannel.hh
Constructor & Destructor Documentation
G4EvaporationChannel::G4EvaporationChannel (G4int A, G4int Z, G4EvaporationProbability * aprob) explicit
Definition at line 53 of file G4EvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4EvaporationChannel.cc
References evapMass, evapMass2, G4NuclearLevelData::GetInstance(), G4NucleiProperties::GetNuclearMass(), mass, resA, resMass, resZ, theA, theLevelData, and theZ.
G4EvaporationChannel::~G4EvaporationChannel () override
Definition at line 70 of file G4EvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4EvaporationChannel.cc
References theCoulombBarrier.
G4EvaporationChannel::G4EvaporationChannel (const G4EvaporationChannel & right) private
Member Function Documentation
G4Fragment * G4EvaporationChannel::EmittedFragment (G4Fragment * theNucleus) override virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 153 of file G4EvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 153 of file G4EvaporationChannel.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), evapMass, evapMass2, G4RandomDirection(), G4Fragment::GetMomentum(), mass, max, resA, resMass, resZ, G4VEmissionProbability::SampleEnergy(), G4Fragment::SetMomentum(), G4Fragment::SetZandA_asInt(), theA, theProbability, and theZ.
G4double G4EvaporationChannel::GetEmissionProbability (G4Fragment * fragment) override virtual
Implements G4VEvaporationChannel.
Definition at line 81 of file G4EvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4EvaporationChannel.cc
References ekinmin, evapMass, evapMass2, G4Fragment::GetA_asInt(), G4CoulombBarrier::GetCoulombBarrier(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4NucleiProperties::GetNuclearMass(), G4NuclearLevelData::GetPairingCorrection(), G4Fragment::GetZ_asInt(), mass, max, CLHEP::MeV, G4VEvaporationChannel::OPTxs, resA, G4VEmissionProbability::ResetProbability(), resMass, resZ, G4VEmissionProbability::SetDecayKinematics(), theA, theCoulombBarrier, theLevelData, theProbability, theZ, and G4EvaporationProbability::TotalProbability().
void G4EvaporationChannel::Initialise () override virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 75 of file G4EvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 75 of file G4EvaporationChannel.cc
References G4VEmissionProbability::Initialise(), G4VEvaporationChannel::Initialise(), and theProbability.
G4bool G4EvaporationChannel::operator!= (const G4EvaporationChannel & right) const private
const G4EvaporationChannel& G4EvaporationChannel::operator= (const G4EvaporationChannel & right) private
G4bool G4EvaporationChannel::operator== (const G4EvaporationChannel & right) const private
Member Data Documentation
G4double G4EvaporationChannel::evapMass private
Definition at line 77 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4double G4EvaporationChannel::evapMass2 private
Definition at line 78 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4double G4EvaporationChannel::mass private
Definition at line 74 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4int G4EvaporationChannel::resA private
Definition at line 71 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4double G4EvaporationChannel::resMass private
Definition at line 75 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4int G4EvaporationChannel::resZ private
Definition at line 72 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 72 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4int G4EvaporationChannel::theA private
Definition at line 69 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 69 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
G4CoulombBarrier* G4EvaporationChannel::theCoulombBarrier private
Definition at line 84 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4EvaporationChannel.hh
Referenced by GetEmissionProbability(), and ~G4EvaporationChannel().
G4NuclearLevelData* G4EvaporationChannel::theLevelData private
Definition at line 86 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4EvaporationChannel.hh
Referenced by G4EvaporationChannel(), and GetEmissionProbability().
G4EvaporationProbability* G4EvaporationChannel::theProbability private
Definition at line 81 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), GetEmissionProbability(), and Initialise().
G4int G4EvaporationChannel::theZ private
Definition at line 70 of file G4EvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 70 of file G4EvaporationChannel.hh
Referenced by EmittedFragment(), G4EvaporationChannel(), and GetEmissionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4EvaporationChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4EvaporationChannel.cc