ECCE @ EIC Software: G4SBBremTable Class Reference
G4SBBremTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4SBBremTable.hh>
Classes
struct SamplingTablePerZ
struct STable
struct STPoint
Public Member Functions
G4SBBremTable ()
~G4SBBremTable ()
void Initialize (const G4double lowe, const G4double highe)
void ClearSamplingTables ()
double SampleEnergyTransfer (const G4double eekin, const G4double leekin, const G4double gcut, const G4double dielSupConst, const G4int izet, const G4int matCutIndx, const bool iselectron)
Private Member Functions
void BuildSamplingTables ()
void InitSamplingTables ()
void LoadSTGrid ()
void LoadSamplingTables (G4int iz)
void ReadCompressedFile (const G4String &fname, std::istringstream &iss)
G4int LinSearch (const std::vector< STPoint > &vect, const G4int size, const G4double val)
Private Attributes
G4int fMaxZet
G4int fNumElEnergy
G4int fNumKappa
G4double fUsedLowEenergy
G4double fUsedHighEenergy
G4double fLogMinElEnergy
G4double fILDeltaElEnergy
std::vector< G4double > fElEnergyVect
std::vector< G4double > fLElEnergyVect
std::vector< G4double > fKappaVect
std::vector< G4double > fLKappaVect
std::vector< SamplingTablePerZ * > fSBSamplingTables
Detailed Description
Definition at line 63 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 63 of file G4SBBremTable.hh
Constructor & Destructor Documentation
G4SBBremTable::G4SBBremTable ()
Definition at line 63 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 63 of file G4SBBremTable.cc
G4SBBremTable::~G4SBBremTable ()
Definition at line 68 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 68 of file G4SBBremTable.cc
References ClearSamplingTables().
Member Function Documentation
void G4SBBremTable::BuildSamplingTables () private
Definition at line 209 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 209 of file G4SBBremTable.cc
References ClearSamplingTables(), fMaxZet, fSBSamplingTables, G4Log(), G4Material::GetElementVector(), G4ProductionCutsTable::GetEnergyCutsVector(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4Element::GetZasInt(), G4MaterialCutsCouple::IsUsed(), LoadSTGrid(), mat, max, and min.
Referenced by Initialize().
void G4SBBremTable::ClearSamplingTables ()
Definition at line 460 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 460 of file G4SBBremTable.cc
References fElEnergyVect, fKappaVect, fLElEnergyVect, fLKappaVect, fMaxZet, fNumElEnergy, and fSBSamplingTables.
Referenced by BuildSamplingTables(), and ~G4SBBremTable().
void G4SBBremTable::Initialize (const G4double lowe, const G4double highe)
Definition at line 73 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 73 of file G4SBBremTable.cc
References BuildSamplingTables(), fUsedHighEenergy, fUsedLowEenergy, and InitSamplingTables().
Referenced by G4SeltzerBergerModel::Initialise().
void G4SBBremTable::InitSamplingTables () private
Definition at line 257 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 257 of file G4SBBremTable.cc
References e, G4SBBremTable::STPoint::fCum, fElEnergyVect, G4SBBremTable::SamplingTablePerZ::fGamCutIndxToMatCutIndx, G4SBBremTable::SamplingTablePerZ::fGammaECuts, fKappaVect, G4SBBremTable::SamplingTablePerZ::fLogGammaECuts, G4SBBremTable::SamplingTablePerZ::fMatCutIndxToGamCutIndx, fMaxZet, fNumElEnergy, G4SBBremTable::SamplingTablePerZ::fNumGammaCuts, G4SBBremTable::STPoint::fParA, G4SBBremTable::STPoint::fParB, fSBSamplingTables, G4SBBremTable::SamplingTablePerZ::fTablesPerEnergy, G4Log(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), LoadSamplingTables(), and max.
Referenced by Initialize().
G4int G4SBBremTable::LinSearch (const std::vector< STPoint > & vect, const G4int size, const G4double val) private
Definition at line 501 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 501 of file G4SBBremTable.cc
Referenced by SampleEnergyTransfer().
void G4SBBremTable::LoadSamplingTables (G4int iz) private
Definition at line 387 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 387 of file G4SBBremTable.cc
References FatalException, G4SBBremTable::STPoint::fCum, fElEnergyVect, G4SBBremTable::SamplingTablePerZ::fGammaECuts, G4SBBremTable::SamplingTablePerZ::fMaxElEnergyIndx, fMaxZet, G4SBBremTable::SamplingTablePerZ::fMinElEnergyIndx, test::fname, fNumElEnergy, fNumKappa, G4SBBremTable::STPoint::fParA, G4SBBremTable::STPoint::fParB, fSBSamplingTables, G4SBBremTable::SamplingTablePerZ::fTablesPerEnergy, fUsedHighEenergy, fUsedLowEenergy, G4Exception(), in, LoadSTGrid(), max, min, ReadCompressedFile(), and nlohmann::to_string().
Referenced by InitSamplingTables().
void G4SBBremTable::LoadSTGrid () private
Definition at line 335 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 335 of file G4SBBremTable.cc
References CLHEP::eV, FatalException, fElEnergyVect, fILDeltaElEnergy, fKappaVect, fLElEnergyVect, fLKappaVect, fLogMinElEnergy, fMaxZet, test::fname, fNumElEnergy, fNumKappa, fSBSamplingTables, fUsedHighEenergy, fUsedLowEenergy, G4Exception(), G4Log(), CLHEP::GeV, in, max, CLHEP::MeV, and min.
Referenced by BuildSamplingTables(), and LoadSamplingTables().
void G4SBBremTable::ReadCompressedFile (const G4String & fname, std::istringstream & iss) private
Definition at line 521 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 521 of file G4SBBremTable.cc
References FatalException, G4Exception(), in, uncompress(), and Z_OK.
Referenced by LoadSamplingTables().
double G4SBBremTable::SampleEnergyTransfer (const G4double eekin, const G4double leekin, const G4double gcut, const G4double dielSupConst, const G4int izet, const G4int matCutIndx, const bool iselectron)
Definition at line 83 of file G4SBBremTable.cc.
View newest version in sPHENIX GitHub at line 83 of file G4SBBremTable.cc
References e1, e2, Acts::eGamma, CLHEP::electron_mass_c2, FatalException, G4SBBremTable::STPoint::fCum, G4SBBremTable::STable::fCumCutValues, fElEnergyVect, G4SBBremTable::SamplingTablePerZ::fGammaECuts, fILDeltaElEnergy, CLHEP::fine_structure_const, CLHEP::HepRandomEngine::flat(), CLHEP::HepRandomEngine::flatArray(), fLElEnergyVect, fLKappaVect, G4SBBremTable::SamplingTablePerZ::fLogGammaECuts, fLogMinElEnergy, G4SBBremTable::SamplingTablePerZ::fMatCutIndxToGamCutIndx, G4SBBremTable::SamplingTablePerZ::fMaxElEnergyIndx, fMaxZet, G4SBBremTable::SamplingTablePerZ::fNumGammaCuts, fNumKappa, G4SBBremTable::STPoint::fParA, G4SBBremTable::STPoint::fParB, fSBSamplingTables, G4SBBremTable::STable::fSTable, G4SBBremTable::SamplingTablePerZ::fTablesPerEnergy, G4Exception(), G4Exp(), LinSearch(), max, min, nlohmann::to_string(), and CLHEP::twopi.
Referenced by G4SeltzerBergerModel::SampleSecondaries().
Member Data Documentation
std::vector<G4double> G4SBBremTable::fElEnergyVect private
Definition at line 152 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 152 of file G4SBBremTable.hh
Referenced by ClearSamplingTables(), InitSamplingTables(), LoadSamplingTables(), LoadSTGrid(), and SampleEnergyTransfer().
G4double G4SBBremTable::fILDeltaElEnergy private
Definition at line 149 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 149 of file G4SBBremTable.hh
Referenced by LoadSTGrid(), and SampleEnergyTransfer().
std::vector<G4double> G4SBBremTable::fKappaVect private
Definition at line 154 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 154 of file G4SBBremTable.hh
Referenced by ClearSamplingTables(), InitSamplingTables(), and LoadSTGrid().
std::vector<G4double> G4SBBremTable::fLElEnergyVect private
Definition at line 153 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 153 of file G4SBBremTable.hh
Referenced by ClearSamplingTables(), LoadSTGrid(), and SampleEnergyTransfer().
std::vector<G4double> G4SBBremTable::fLKappaVect private
Definition at line 155 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 155 of file G4SBBremTable.hh
Referenced by ClearSamplingTables(), LoadSTGrid(), and SampleEnergyTransfer().
G4double G4SBBremTable::fLogMinElEnergy private
Definition at line 148 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 148 of file G4SBBremTable.hh
Referenced by LoadSTGrid(), and SampleEnergyTransfer().
G4int G4SBBremTable::fMaxZet private
Definition at line 141 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 141 of file G4SBBremTable.hh
Referenced by BuildSamplingTables(), ClearSamplingTables(), InitSamplingTables(), LoadSamplingTables(), LoadSTGrid(), and SampleEnergyTransfer().
G4int G4SBBremTable::fNumElEnergy private
Definition at line 142 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 142 of file G4SBBremTable.hh
Referenced by ClearSamplingTables(), InitSamplingTables(), LoadSamplingTables(), and LoadSTGrid().
G4int G4SBBremTable::fNumKappa private
Definition at line 143 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 143 of file G4SBBremTable.hh
Referenced by LoadSamplingTables(), LoadSTGrid(), and SampleEnergyTransfer().
std::vector<SamplingTablePerZ*> G4SBBremTable::fSBSamplingTables private
Definition at line 158 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 158 of file G4SBBremTable.hh
Referenced by BuildSamplingTables(), ClearSamplingTables(), InitSamplingTables(), LoadSamplingTables(), LoadSTGrid(), and SampleEnergyTransfer().
G4double G4SBBremTable::fUsedHighEenergy private
Definition at line 147 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 147 of file G4SBBremTable.hh
Referenced by Initialize(), LoadSamplingTables(), and LoadSTGrid().
G4double G4SBBremTable::fUsedLowEenergy private
Definition at line 146 of file G4SBBremTable.hh.
View newest version in sPHENIX GitHub at line 146 of file G4SBBremTable.hh
Referenced by Initialize(), LoadSamplingTables(), and LoadSTGrid().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4SBBremTable.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4SBBremTable.cc