ECCE @ EIC Software: RMC01AnalysisManagerMessenger Class Reference
RMC01AnalysisManagerMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/RMC01AnalysisManagerMessenger.hh>
Public Member Functions
RMC01AnalysisManagerMessenger (RMC01AnalysisManager *)
virtual ~RMC01AnalysisManagerMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
RMC01AnalysisManager * fAnalysisManager
G4UIdirectory * fAnalysisDir
G4UIcmdWithADouble * fSetPrecisionForConvergenceTestCmd
G4UIcommand * fSetExpSpectrumToNormaliseAdjResCmd
G4UIcommand * fSetPowerLawSpectrumToNormaliseAdjResCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 59 of file RMC01AnalysisManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file RMC01AnalysisManagerMessenger.hh
Constructor & Destructor Documentation
RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger (RMC01AnalysisManager * analysisManager)
Definition at line 48 of file RMC01AnalysisManagerMessenger.cc.
View newest version in sPHENIX GitHub at line 48 of file RMC01AnalysisManagerMessenger.cc
References G4UIcommand::AvailableForStates(), fAnalysisDir, fSetExpSpectrumToNormaliseAdjResCmd, fSetPowerLawSpectrumToNormaliseAdjResCmd, fSetPrecisionForConvergenceTestCmd, G4State_Idle, G4State_PreInit, G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWithADouble::SetParameterName(), and G4UIparameter::SetParameterRange().
RMC01AnalysisManagerMessenger::~RMC01AnalysisManagerMessenger () virtual
Definition at line 137 of file RMC01AnalysisManagerMessenger.cc.
View newest version in sPHENIX GitHub at line 137 of file RMC01AnalysisManagerMessenger.cc
References fAnalysisDir.
Member Function Documentation
void RMC01AnalysisManagerMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 144 of file RMC01AnalysisManagerMessenger.cc.
View newest version in sPHENIX GitHub at line 144 of file RMC01AnalysisManagerMessenger.cc
References alpha, cm2, e1, e2, fAnalysisManager, fSetExpSpectrumToNormaliseAdjResCmd, fSetPowerLawSpectrumToNormaliseAdjResCmd, fSetPrecisionForConvergenceTestCmd, G4UIcmdWithADouble::GetNewDoubleValue(), G4UnitDefinition::GetValueOf(), m2, RMC01AnalysisManager::SetPrecision(), RMC01AnalysisManager::SetPrimaryExpSpectrumForAdjointSim(), and RMC01AnalysisManager::SetPrimaryPowerLawSpectrumForAdjointSim().
Member Data Documentation
G4UIdirectory* RMC01AnalysisManagerMessenger::fAnalysisDir private
Definition at line 71 of file RMC01AnalysisManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file RMC01AnalysisManagerMessenger.hh
Referenced by RMC01AnalysisManagerMessenger(), and ~RMC01AnalysisManagerMessenger().
RMC01AnalysisManager* RMC01AnalysisManagerMessenger::fAnalysisManager private
Definition at line 69 of file RMC01AnalysisManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file RMC01AnalysisManagerMessenger.hh
Referenced by SetNewValue().
G4UIcommand* RMC01AnalysisManagerMessenger::fSetExpSpectrumToNormaliseAdjResCmd private
Definition at line 74 of file RMC01AnalysisManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file RMC01AnalysisManagerMessenger.hh
Referenced by RMC01AnalysisManagerMessenger(), and SetNewValue().
G4UIcommand* RMC01AnalysisManagerMessenger::fSetPowerLawSpectrumToNormaliseAdjResCmd private
Definition at line 75 of file RMC01AnalysisManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file RMC01AnalysisManagerMessenger.hh
Referenced by RMC01AnalysisManagerMessenger(), and SetNewValue().
G4UIcmdWithADouble* RMC01AnalysisManagerMessenger::fSetPrecisionForConvergenceTestCmd private
Definition at line 73 of file RMC01AnalysisManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file RMC01AnalysisManagerMessenger.hh
Referenced by RMC01AnalysisManagerMessenger(), and SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/RMC01AnalysisManagerMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/src/RMC01AnalysisManagerMessenger.cc