ECCE @ EIC Software: GammaRayTelDigitizer Class Reference
GammaRayTelDigitizer Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelDigitizer.hh>
Public Member Functions
GammaRayTelDigitizer (G4String name)
~GammaRayTelDigitizer ()
void Digitize ()
void SetThreshold (G4double val)
Public Member Functions inherited from G4VDigitizerModule
G4VDigitizerModule (const G4String &modName)
virtual ~G4VDigitizerModule ()
G4bool operator== (const G4VDigitizerModule &right) const
G4bool operator!= (const G4VDigitizerModule &right) const
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int i) const
G4String GetName () const
void SetVerboseLevel (G4int val)
Private Attributes
GammaRayTelDigitsCollection * DigitsCollection
G4double Energy_Threshold
G4double TotalEnergy
G4double ACDThreshold
GammaRayTelDigitizerMessenger * digiMessenger
Additional Inherited Members
Protected Member Functions inherited from G4VDigitizerModule
void StoreDigiCollection (G4VDigiCollection *aDC)
void StoreDigiCollection (G4int DCID, G4VDigiCollection *aDC)
Protected Attributes inherited from G4VDigitizerModule
G4DigiManager * DigiManager
G4String moduleName
std::vector< G4String > collectionName
G4int verboseLevel
Detailed Description
Definition at line 50 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 50 of file GammaRayTelDigitizer.hh
Constructor & Destructor Documentation
GammaRayTelDigitizer::GammaRayTelDigitizer (G4String name)
Definition at line 56 of file GammaRayTelDigitizer.cc.
View newest version in sPHENIX GitHub at line 56 of file GammaRayTelDigitizer.cc
References ACDThreshold, G4VDigitizerModule::collectionName, digiMessenger, Energy_Threshold, keV, and TotalEnergy.
GammaRayTelDigitizer::~GammaRayTelDigitizer ()
Definition at line 74 of file GammaRayTelDigitizer.cc.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelDigitizer.cc
References digiMessenger.
Member Function Documentation
void GammaRayTelDigitizer::Digitize (void) virtual
Implements G4VDigitizerModule.
Definition at line 81 of file GammaRayTelDigitizer.cc.
View newest version in sPHENIX GitHub at line 81 of file GammaRayTelDigitizer.cc
References ACDThreshold, DigitsCollection, energy, Energy_Threshold, G4TDigiCollection< T >::entries(), G4THitsCollection< T >::entries(), G4cout, G4endl, G4DigiManager::GetDigiCollectionID(), G4DigiManager::GetDMpointer(), G4DigiManager::GetHitsCollection(), G4DigiManager::GetHitsCollectionID(), G4TDigiCollection< T >::insert(), GammaRayTelDigi::SetDigiType(), GammaRayTelDigi::SetEnergy(), GammaRayTelDigi::SetPlaneNumber(), GammaRayTelDigi::SetPlaneType(), GammaRayTelDigi::SetStripNumber(), G4VDigitizerModule::StoreDigiCollection(), and TotalEnergy.
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelDigitizer::SetThreshold (G4double val) inline
Definition at line 58 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 58 of file GammaRayTelDigitizer.hh
References Energy_Threshold.
Referenced by GammaRayTelDigitizerMessenger::SetNewValue().
Member Data Documentation
G4double GammaRayTelDigitizer::ACDThreshold private
Definition at line 65 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 65 of file GammaRayTelDigitizer.hh
Referenced by Digitize(), and GammaRayTelDigitizer().
GammaRayTelDigitizerMessenger* GammaRayTelDigitizer::digiMessenger private
Definition at line 66 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 66 of file GammaRayTelDigitizer.hh
Referenced by GammaRayTelDigitizer(), and ~GammaRayTelDigitizer().
GammaRayTelDigitsCollection* GammaRayTelDigitizer::DigitsCollection private
Definition at line 62 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 62 of file GammaRayTelDigitizer.hh
Referenced by Digitize().
G4double GammaRayTelDigitizer::Energy_Threshold private
Definition at line 63 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 63 of file GammaRayTelDigitizer.hh
Referenced by Digitize(), GammaRayTelDigitizer(), and SetThreshold().
G4double GammaRayTelDigitizer::TotalEnergy private
Definition at line 64 of file GammaRayTelDigitizer.hh.
View newest version in sPHENIX GitHub at line 64 of file GammaRayTelDigitizer.hh
Referenced by Digitize(), and GammaRayTelDigitizer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelDigitizer.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelDigitizer.cc