ECCE @ EIC Software: G4IonPhysicsPHP Class Reference
G4IonPhysicsPHP Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/ions/include/G4IonPhysicsPHP.hh>
Public Member Functions
G4IonPhysicsPHP (G4int ver=0)
G4IonPhysicsPHP (const G4String &nname)
virtual ~G4IonPhysicsPHP ()
void ConstructParticle ()
void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
void AddProcess (const G4String &, G4ParticleDefinition *, G4ParticleHPInelasticData *, G4HadronicInteraction *, G4HadronicInteraction *, G4HadronicInteraction *, G4VCrossSectionDataSet *)
Private Attributes
G4int verbose
Static Private Attributes
static G4ThreadLocal G4FTFBuilder * theBuilder = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 53 of file G4IonPhysicsPHP.hh.
View newest version in sPHENIX GitHub at line 53 of file G4IonPhysicsPHP.hh
Constructor & Destructor Documentation
G4IonPhysicsPHP::G4IonPhysicsPHP (G4int ver = 0)
Definition at line 77 of file G4IonPhysicsPHP.cc.
View newest version in sPHENIX GitHub at line 77 of file G4IonPhysicsPHP.cc
References verbose.
G4IonPhysicsPHP::G4IonPhysicsPHP (const G4String & nname)
Definition at line 83 of file G4IonPhysicsPHP.cc.
View newest version in sPHENIX GitHub at line 83 of file G4IonPhysicsPHP.cc
References bIons, fCombined, G4cout, G4endl, G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::SetDeexChannelsType(), G4VPhysicsConstructor::SetPhysicsType(), and verbose.
G4IonPhysicsPHP::~G4IonPhysicsPHP () virtual
Definition at line 93 of file G4IonPhysicsPHP.cc.
View newest version in sPHENIX GitHub at line 93 of file G4IonPhysicsPHP.cc
References theBuilder.
Member Function Documentation
void G4IonPhysicsPHP::AddProcess (const G4String & name, G4ParticleDefinition * part, G4ParticleHPInelasticData * xsecPHP, G4HadronicInteraction * aPHP, G4HadronicInteraction * aBIC, G4HadronicInteraction * aFTFP, G4VCrossSectionDataSet * theNuclNuclData) private
Definition at line 196 of file G4IonPhysicsPHP.cc.
View newest version in sPHENIX GitHub at line 196 of file G4IonPhysicsPHP.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), G4ParticleDefinition::GetProcessManager(), and G4HadronicProcess::RegisterMe().
Referenced by ConstructProcess().
void G4IonPhysicsPHP::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 100 of file G4IonPhysicsPHP.cc.
View newest version in sPHENIX GitHub at line 100 of file G4IonPhysicsPHP.cc
References G4IonConstructor::ConstructParticle().
void G4IonPhysicsPHP::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 107 of file G4IonPhysicsPHP.cc.
View newest version in sPHENIX GitHub at line 107 of file G4IonPhysicsPHP.cc
References AddProcess(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4HadronicInteractionRegistry::FindModel(), G4cout, G4endl, G4GenericIon::GenericIon(), G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4VHadronModelBuilder::GetModel(), G4He3::He3(), G4HadronicInteractionRegistry::Instance(), G4HadronicParameters::Instance(), MeV, G4HadronicInteraction::SetMaxEnergy(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4HadronicInteraction::SetMinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theBuilder, G4Triton::Triton(), and verbose.
Member Data Documentation
G4ThreadLocal G4FTFBuilder * G4IonPhysicsPHP::theBuilder = nullptr static private
Definition at line 73 of file G4IonPhysicsPHP.hh.
View newest version in sPHENIX GitHub at line 73 of file G4IonPhysicsPHP.hh
Referenced by ConstructProcess(), and ~G4IonPhysicsPHP().
G4int G4IonPhysicsPHP::verbose private
Definition at line 75 of file G4IonPhysicsPHP.hh.
View newest version in sPHENIX GitHub at line 75 of file G4IonPhysicsPHP.hh
Referenced by ConstructProcess(), and G4IonPhysicsPHP().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/ions/include/G4IonPhysicsPHP.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/ions/src/G4IonPhysicsPHP.cc