ECCE @ EIC Software: G4SmoothTrajectoryPoint Class Reference
G4SmoothTrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4SmoothTrajectoryPoint.hh>
Public Member Functions
G4SmoothTrajectoryPoint ()
G4SmoothTrajectoryPoint (G4ThreeVector pos, std::vector< G4ThreeVector > *auxiliaryPoints)
G4SmoothTrajectoryPoint (G4ThreeVector pos)
G4SmoothTrajectoryPoint (const G4SmoothTrajectoryPoint &right)
virtual ~G4SmoothTrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const G4SmoothTrajectoryPoint &right) const
const G4ThreeVector GetPosition () const
const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
Private Member Functions
G4SmoothTrajectoryPoint & operator= (const G4SmoothTrajectoryPoint &)
Private Attributes
G4ThreeVector fPosition
std::vector< G4ThreeVector > * fAuxiliaryPointVector
Detailed Description
Definition at line 47 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 47 of file G4SmoothTrajectoryPoint.hh
Constructor & Destructor Documentation
G4SmoothTrajectoryPoint::G4SmoothTrajectoryPoint ()
Definition at line 53 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 53 of file G4SmoothTrajectoryPoint.cc
References fPosition.
G4SmoothTrajectoryPoint::G4SmoothTrajectoryPoint (G4ThreeVector pos, std::vector< G4ThreeVector > * auxiliaryPoints)
Definition at line 65 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 65 of file G4SmoothTrajectoryPoint.cc
G4SmoothTrajectoryPoint::G4SmoothTrajectoryPoint (G4ThreeVector pos)
Definition at line 59 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 59 of file G4SmoothTrajectoryPoint.cc
References fPosition, and pos().
G4SmoothTrajectoryPoint::G4SmoothTrajectoryPoint (const G4SmoothTrajectoryPoint & right)
Definition at line 71 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 71 of file G4SmoothTrajectoryPoint.cc
G4SmoothTrajectoryPoint::~G4SmoothTrajectoryPoint () virtual
Definition at line 77 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 77 of file G4SmoothTrajectoryPoint.cc
References fAuxiliaryPointVector.
Member Function Documentation
std::vector< G4AttValue > * G4SmoothTrajectoryPoint::CreateAttValues () const virtual
Reimplemented from G4VTrajectoryPoint.
Definition at line 102 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 102 of file G4SmoothTrajectoryPoint.cc
References fAuxiliaryPointVector, fPosition, G4BestUnit, G4cout, GetAttDefs(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * G4SmoothTrajectoryPoint::GetAttDefs () const virtual
Reimplemented from G4VTrajectoryPoint.
Definition at line 86 of file G4SmoothTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 86 of file G4SmoothTrajectoryPoint.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
const std::vector<G4ThreeVector>* G4SmoothTrajectoryPoint::GetAuxiliaryPoints () const inline virtual
Reimplemented from G4VTrajectoryPoint.
Definition at line 78 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 78 of file G4SmoothTrajectoryPoint.hh
References fAuxiliaryPointVector.
const G4ThreeVector G4SmoothTrajectoryPoint::GetPosition (void) const inline virtual
Implements G4VTrajectoryPoint.
Definition at line 76 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 76 of file G4SmoothTrajectoryPoint.hh
References fPosition.
void G4SmoothTrajectoryPoint::operator delete (void * aTrajectoryPoint) inline
Definition at line 103 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 103 of file G4SmoothTrajectoryPoint.hh
References aSmoothTrajectoryPointAllocator().
void * G4SmoothTrajectoryPoint::operator new (size_t) inline
Definition at line 96 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 96 of file G4SmoothTrajectoryPoint.hh
References aSmoothTrajectoryPointAllocator().
G4SmoothTrajectoryPoint& G4SmoothTrajectoryPoint::operator= (const G4SmoothTrajectoryPoint &) private
G4bool G4SmoothTrajectoryPoint::operator== (const G4SmoothTrajectoryPoint & right) const inline
Definition at line 72 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 72 of file G4SmoothTrajectoryPoint.hh
Member Data Documentation
std::vector<G4ThreeVector>* G4SmoothTrajectoryPoint::fAuxiliaryPointVector private
Definition at line 91 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 91 of file G4SmoothTrajectoryPoint.hh
Referenced by CreateAttValues(), GetAuxiliaryPoints(), and ~G4SmoothTrajectoryPoint().
G4ThreeVector G4SmoothTrajectoryPoint::fPosition private
Definition at line 90 of file G4SmoothTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 90 of file G4SmoothTrajectoryPoint.hh
Referenced by CreateAttValues(), G4SmoothTrajectoryPoint(), and GetPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4SmoothTrajectoryPoint.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4SmoothTrajectoryPoint.cc