ECCE @ EIC Software: G4FTFParticipants Class Reference
G4FTFParticipants Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFParticipants.hh>
Public Member Functions
G4FTFParticipants ()
const G4FTFParticipants & operator= (const G4FTFParticipants &right)
~G4FTFParticipants ()
G4bool operator== (const G4FTFParticipants &right) const
G4bool operator!= (const G4FTFParticipants &right) const
void GetList (const G4ReactionProduct &thePrimary, G4FTFParameters *theParameters)
void StartLoop ()
G4bool Next ()
void SortInteractionsIncT ()
void ShiftInteractionTime ()
G4InteractionContent & GetInteraction ()
void Clean ()
Public Member Functions inherited from G4VParticipants
G4VParticipants ()
G4VParticipants (const G4VParticipants &right)
virtual ~G4VParticipants ()
const G4VParticipants & operator= (const G4VParticipants &right)
G4bool operator== (const G4VParticipants &right) const
G4bool operator!= (const G4VParticipants &right) const
virtual void Init (G4int theZ, G4int theA)
virtual void SetNucleus (G4V3DNucleus *aNucleus)
virtual G4V3DNucleus * GetWoundedNucleus () const
virtual void InitProjectileNucleus (G4int theZ, G4int theA)
virtual void SetProjectileNucleus (G4V3DNucleus *aNucleus)
virtual G4V3DNucleus * GetProjectileNucleus () const
Public Attributes
std::vector
< G4InteractionContent * > theInteractions
Public Attributes inherited from G4VParticipants
G4V3DNucleus * theNucleus
G4V3DNucleus * theProjectileNucleus
Private Member Functions
G4FTFParticipants (const G4FTFParticipants &right)
Private Attributes
G4int currentInteraction
Detailed Description
Definition at line 50 of file G4FTFParticipants.hh.
View newest version in sPHENIX GitHub at line 50 of file G4FTFParticipants.hh
Constructor & Destructor Documentation
G4FTFParticipants::G4FTFParticipants ()
Definition at line 61 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 61 of file G4FTFParticipants.cc
G4FTFParticipants::~G4FTFParticipants ()
Definition at line 76 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FTFParticipants.cc
G4FTFParticipants::G4FTFParticipants (const G4FTFParticipants & right) private
Definition at line 66 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 66 of file G4FTFParticipants.cc
References FatalException, and G4Exception().
Member Function Documentation
void G4FTFParticipants::Clean ()
Definition at line 371 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 371 of file G4FTFParticipants.cc
References currentInteraction, and theInteractions.
Referenced by G4FTFModel::GetStrings(), and G4FTFModel::Init().
G4InteractionContent & G4FTFParticipants::GetInteraction () inline
Definition at line 83 of file G4FTFParticipants.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FTFParticipants.hh
References currentInteraction, and theInteractions.
Referenced by G4FTFModel::BuildStrings(), G4FTFModel::ExciteParticipants(), G4FTFModel::GetStrings(), and G4FTFModel::PutOnMassShell().
void G4FTFParticipants::GetList (const G4ReactionProduct & thePrimary, G4FTFParameters * theParameters)
Definition at line 81 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 81 of file G4FTFParticipants.cc
References G4Nucleon::AreYouHit(), G4V3DNucleus::ChooseImpactXandY(), G4V3DNucleus::DoTranslation(), e, fermi, G4cout, G4endl, G4UniformRand, G4Nucleon::Get4Momentum(), G4InteractionContent::GetInteractionTime(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4V3DNucleus::GetOuterRadius(), G4Nucleon::GetPosition(), G4VSplitableHadron::GetPosition(), G4FTFParameters::GetProbabilityOfInteraction(), G4Nucleon::GetSplitableHadron(), G4ReactionProduct::GetTotalEnergy(), G4Nucleon::Hit(), G4InuclParticleNames::nucleon(), G4InteractionContent::SetInteractionTime(), G4VSplitableHadron::SetPosition(), G4InteractionContent::SetProjectileNucleon(), G4InteractionContent::SetStatus(), G4VSplitableHadron::SetStatus(), G4InteractionContent::SetTarget(), G4InteractionContent::SetTargetNucleon(), ShiftInteractionTime(), SortInteractionsIncT(), sqr(), G4V3DNucleus::StartLoop(), StartLoop(), theInteractions, G4VParticipants::theNucleus, G4VParticipants::theProjectileNucleus, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4FTFModel::GetStrings().
G4bool G4FTFParticipants::Next () inline
Definition at line 78 of file G4FTFParticipants.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFParticipants.hh
References theInteractions.
Referenced by G4FTFModel::BuildStrings(), G4FTFModel::ExciteParticipants(), G4FTFModel::GetStrings(), and G4FTFModel::PutOnMassShell().
G4bool G4FTFParticipants::operator!= (const G4FTFParticipants & right) const
const G4FTFParticipants& G4FTFParticipants::operator= (const G4FTFParticipants & right)
G4bool G4FTFParticipants::operator== (const G4FTFParticipants & right) const
void G4FTFParticipants::ShiftInteractionTime ()
Definition at line 351 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 351 of file G4FTFParticipants.cc
References G4VSplitableHadron::GetPosition(), G4InteractionContent::GetProjectile(), G4InteractionContent::GetTarget(), G4VSplitableHadron::SetPosition(), G4VSplitableHadron::SetTimeOfCreation(), CLHEP::Hep3Vector::setZ(), theInteractions, and CLHEP::Hep3Vector::z().
Referenced by GetList().
void G4FTFParticipants::SortInteractionsIncT ()
Definition at line 343 of file G4FTFParticipants.cc.
View newest version in sPHENIX GitHub at line 343 of file G4FTFParticipants.cc
References G4FTFPartHelperForSortInT(), and theInteractions.
Referenced by GetList().
void G4FTFParticipants::StartLoop () inline
Definition at line 73 of file G4FTFParticipants.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFParticipants.hh
References currentInteraction.
Referenced by G4FTFModel::BuildStrings(), G4FTFModel::ExciteParticipants(), GetList(), G4FTFModel::GetStrings(), and G4FTFModel::PutOnMassShell().
Member Data Documentation
G4int G4FTFParticipants::currentInteraction private
Definition at line 69 of file G4FTFParticipants.hh.
View newest version in sPHENIX GitHub at line 69 of file G4FTFParticipants.hh
Referenced by Clean(), GetInteraction(), and StartLoop().
std::vector< G4InteractionContent* > G4FTFParticipants::theInteractions
Definition at line 65 of file G4FTFParticipants.hh.
View newest version in sPHENIX GitHub at line 65 of file G4FTFParticipants.hh
Referenced by Clean(), GetInteraction(), GetList(), Next(), ShiftInteractionTime(), and SortInteractionsIncT().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFParticipants.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4FTFParticipants.cc