ECCE @ EIC Software: G4GenericBiasingPhysics Class Reference
G4GenericBiasingPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4GenericBiasingPhysics.hh>
Public Member Functions
G4GenericBiasingPhysics (const G4String &name="BiasingP")
virtual ~G4GenericBiasingPhysics ()
void PhysicsBias (const G4String &particleName)
void PhysicsBias (const G4String &particleName, const std::vector< G4String > &processToBiasNames)
void NonPhysicsBias (const G4String &particleName)
void Bias (const G4String &particleName)
void Bias (const G4String &particleName, const std::vector< G4String > &processToBiasNames)
void PhysicsBiasAddPDGRange (G4int PDGlow, G4int PDGhigh, G4bool includeAntiParticle=true)
void NonPhysicsBiasAddPDGRange (G4int PDGlow, G4int PDGhigh, G4bool includeAntiParticle=true)
void BiasAddPDGRange (G4int PDGlow, G4int PDGhigh, G4bool includeAntiParticle=true)
void PhysicsBiasAllCharged (G4bool includeShortLived=false)
void NonPhysicsBiasAllCharged (G4bool includeShortLived=false)
void BiasAllCharged (G4bool includeShortLived=false)
void PhysicsBiasAllNeutral (G4bool includeShortLived=false)
void NonPhysicsBiasAllNeutral (G4bool includeShortLived=false)
void BiasAllNeutral (G4bool includeShortLived=false)
void AddParallelGeometry (const G4String &particleName, const G4String &parallelGeometryName)
void AddParallelGeometry (const G4String &particleName, const std::vector< G4String > &parallelGeometryNames)
void AddParallelGeometry (G4int PDGlow, G4int PDGhigh, const G4String &parallelGeometryName, G4bool includeAntiParticle=true)
void AddParallelGeometry (G4int PDGlow, G4int PDGhigh, const std::vector< G4String > &parallelGeometryNames, G4bool includeAntiParticle=true)
void AddParallelGeometryAllCharged (const G4String &parallelGeometryName, G4bool includeShortLived=false)
void AddParallelGeometryAllCharged (const std::vector< G4String > &parallelGeometryNames, G4bool includeShortLived=false)
void AddParallelGeometryAllNeutral (const G4String &parallelGeometryName, G4bool includeShortLived=false)
void AddParallelGeometryAllNeutral (const std::vector< G4String > &parallelGeometryNames, G4bool includeShortLived=false)
void BeVerbose ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
G4GenericBiasingPhysics & operator= (const G4GenericBiasingPhysics &right)
G4GenericBiasingPhysics (const G4GenericBiasingPhysics &)
void AssociateParallelGeometries ()
Private Attributes
std::vector< G4String > fBiasedParticles
std::vector< G4bool > fBiasAllProcesses
std::vector< std::vector
< G4String > > fBiasedProcesses
std::vector< G4String > fNonPhysBiasedParticles
std::vector< G4int > fPhysBiasByPDGRangeLow
std::vector< G4int > fPhysBiasByPDGRangeHigh
std::vector< G4int > fNonPhysBiasByPDGRangeLow
std::vector< G4int > fNonPhysBiasByPDGRangeHigh
G4bool fPhysBiasAllCharged
G4bool fNonPhysBiasAllCharged
G4bool fPhysBiasAllChargedISL
G4bool fNonPhysBiasAllChargedISL
G4bool fPhysBiasAllNeutral
G4bool fNonPhysBiasAllNeutral
G4bool fPhysBiasAllNeutralISL
G4bool fNonPhysBiasAllNeutralISL
std::vector< G4String > fParticlesWithParallelGeometries
std::map< G4String,
std::vector< G4String > > fParallelGeometriesForParticle
std::vector< G4int > fPDGlowParallelGeometries
std::vector< G4int > fPDGhighParallelGeometries
std::map< G4int, std::vector
< G4String > > fPDGrangeParallelGeometries
std::vector< G4String > fParallelGeometriesForCharged
std::vector< G4String > fParallelGeometriesForNeutral
std::vector< G4bool > fAllChargedParallelGeometriesISL
std::vector< G4bool > fAllNeutralParallelGeometriesISL
G4bool fVerbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 41 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 41 of file G4GenericBiasingPhysics.hh
Constructor & Destructor Documentation
G4GenericBiasingPhysics::G4GenericBiasingPhysics (const G4String & name = "BiasingP")
Definition at line 59 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 59 of file G4GenericBiasingPhysics.cc
G4GenericBiasingPhysics::~G4GenericBiasingPhysics () virtual
Definition at line 70 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 70 of file G4GenericBiasingPhysics.cc
G4GenericBiasingPhysics::G4GenericBiasingPhysics (const G4GenericBiasingPhysics &) private
Member Function Documentation
void G4GenericBiasingPhysics::AddParallelGeometry (const G4String & particleName, const G4String & parallelGeometryName)
Definition at line 187 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 187 of file G4GenericBiasingPhysics.cc
References fParallelGeometriesForParticle, and fParticlesWithParallelGeometries.
Referenced by AddParallelGeometry(), and main().
void G4GenericBiasingPhysics::AddParallelGeometry (const G4String & particleName, const std::vector< G4String > & parallelGeometryNames)
Definition at line 217 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 217 of file G4GenericBiasingPhysics.cc
References AddParallelGeometry().
void G4GenericBiasingPhysics::AddParallelGeometry (G4int PDGlow, G4int PDGhigh, const G4String & parallelGeometryName, G4bool includeAntiParticle = true)
Definition at line 222 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 222 of file G4GenericBiasingPhysics.cc
References fPDGhighParallelGeometries, fPDGlowParallelGeometries, fPDGrangeParallelGeometries, G4cout, and G4endl.
void G4GenericBiasingPhysics::AddParallelGeometry (G4int PDGlow, G4int PDGhigh, const std::vector< G4String > & parallelGeometryNames, G4bool includeAntiParticle = true)
Definition at line 245 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 245 of file G4GenericBiasingPhysics.cc
References AddParallelGeometry(), G4cout, and G4endl.
void G4GenericBiasingPhysics::AddParallelGeometryAllCharged (const G4String & parallelGeometryName, G4bool includeShortLived = false)
Definition at line 256 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 256 of file G4GenericBiasingPhysics.cc
References fAllChargedParallelGeometriesISL, and fParallelGeometriesForCharged.
Referenced by AddParallelGeometryAllCharged().
void G4GenericBiasingPhysics::AddParallelGeometryAllCharged (const std::vector< G4String > & parallelGeometryNames, G4bool includeShortLived = false)
Definition at line 274 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 274 of file G4GenericBiasingPhysics.cc
References AddParallelGeometryAllCharged().
void G4GenericBiasingPhysics::AddParallelGeometryAllNeutral (const G4String & parallelGeometryName, G4bool includeShortLived = false)
Definition at line 279 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 279 of file G4GenericBiasingPhysics.cc
References fAllNeutralParallelGeometriesISL, and fParallelGeometriesForNeutral.
Referenced by AddParallelGeometryAllNeutral().
void G4GenericBiasingPhysics::AddParallelGeometryAllNeutral (const std::vector< G4String > & parallelGeometryNames, G4bool includeShortLived = false)
Definition at line 297 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 297 of file G4GenericBiasingPhysics.cc
References AddParallelGeometryAllNeutral().
void G4GenericBiasingPhysics::AssociateParallelGeometries () private
Definition at line 503 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 503 of file G4GenericBiasingPhysics.cc
References G4BiasingHelper::AddLimiterProcess(), G4ParallelGeometriesLimiterProcess::AddParallelWorld(), fAllChargedParallelGeometriesISL, fAllNeutralParallelGeometriesISL, fParallelGeometriesForCharged, fParallelGeometriesForParticle, fParticlesWithParallelGeometries, fPDGhighParallelGeometries, fPDGlowParallelGeometries, fPDGrangeParallelGeometries, G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsShortLived(), particle, and Acts::Test::world.
Referenced by ConstructProcess().
void G4GenericBiasingPhysics::BeVerbose () inline
Definition at line 106 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 106 of file G4GenericBiasingPhysics.hh
References fVerbose.
Referenced by main().
void G4GenericBiasingPhysics::Bias (const G4String & particleName)
Definition at line 102 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 102 of file G4GenericBiasingPhysics.cc
References NonPhysicsBias(), and PhysicsBias().
Referenced by main().
void G4GenericBiasingPhysics::Bias (const G4String & particleName, const std::vector< G4String > & processToBiasNames)
Definition at line 110 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 110 of file G4GenericBiasingPhysics.cc
References NonPhysicsBias(), and PhysicsBias().
void G4GenericBiasingPhysics::BiasAddPDGRange (G4int PDGlow, G4int PDGhigh, G4bool includeAntiParticle = true)
Definition at line 144 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 144 of file G4GenericBiasingPhysics.cc
References G4cout, G4endl, NonPhysicsBiasAddPDGRange(), and PhysicsBiasAddPDGRange().
void G4GenericBiasingPhysics::BiasAllCharged (G4bool includeShortLived = false)
Definition at line 161 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 161 of file G4GenericBiasingPhysics.cc
References fNonPhysBiasAllCharged, fNonPhysBiasAllChargedISL, fPhysBiasAllCharged, and fPhysBiasAllChargedISL.
void G4GenericBiasingPhysics::BiasAllNeutral (G4bool includeShortLived = false)
Definition at line 178 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 178 of file G4GenericBiasingPhysics.cc
References fNonPhysBiasAllNeutral, fNonPhysBiasAllNeutralISL, fPhysBiasAllNeutral, and fPhysBiasAllNeutralISL.
void G4GenericBiasingPhysics::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 306 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 306 of file G4GenericBiasingPhysics.cc
void G4GenericBiasingPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 311 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 311 of file G4GenericBiasingPhysics.cc
References kdfinder::abs(), G4BiasingHelper::ActivateNonPhysicsBiasing(), G4BiasingHelper::ActivatePhysicsBiasing(), AssociateParallelGeometries(), DBL_MIN, false, fBiasAllProcesses, fBiasedParticles, fBiasedProcesses, fNonPhysBiasAllCharged, fNonPhysBiasAllChargedISL, fNonPhysBiasAllNeutral, fNonPhysBiasAllNeutralISL, fNonPhysBiasByPDGRangeHigh, fNonPhysBiasByPDGRangeLow, fNonPhysBiasedParticles, fPhysBiasAllCharged, fPhysBiasAllChargedISL, fPhysBiasAllNeutral, fPhysBiasAllNeutralISL, fPhysBiasByPDGRangeHigh, fPhysBiasByPDGRangeLow, fVerbose, G4cout, G4endl, G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4ParticleDefinition::IsShortLived(), particle, and G4ProcessVector::size().
void G4GenericBiasingPhysics::NonPhysicsBias (const G4String & particleName)
Definition at line 95 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 95 of file G4GenericBiasingPhysics.cc
References fNonPhysBiasedParticles.
Referenced by Bias(), and main().
void G4GenericBiasingPhysics::NonPhysicsBiasAddPDGRange (G4int PDGlow, G4int PDGhigh, G4bool includeAntiParticle = true)
Definition at line 130 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 130 of file G4GenericBiasingPhysics.cc
References fNonPhysBiasByPDGRangeHigh, fNonPhysBiasByPDGRangeLow, G4cout, and G4endl.
Referenced by BiasAddPDGRange().
void G4GenericBiasingPhysics::NonPhysicsBiasAllCharged (G4bool includeShortLived = false)
Definition at line 156 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 156 of file G4GenericBiasingPhysics.cc
References fNonPhysBiasAllCharged, and fNonPhysBiasAllChargedISL.
void G4GenericBiasingPhysics::NonPhysicsBiasAllNeutral (G4bool includeShortLived = false)
Definition at line 173 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 173 of file G4GenericBiasingPhysics.cc
References fNonPhysBiasAllNeutral, and fNonPhysBiasAllNeutralISL.
G4GenericBiasingPhysics& G4GenericBiasingPhysics::operator= (const G4GenericBiasingPhysics & right) private
void G4GenericBiasingPhysics::PhysicsBias (const G4String & particleName)
Definition at line 76 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 76 of file G4GenericBiasingPhysics.cc
References fBiasAllProcesses, fBiasedParticles, and fBiasedProcesses.
Referenced by Bias(), and main().
void G4GenericBiasingPhysics::PhysicsBias (const G4String & particleName, const std::vector< G4String > & processToBiasNames)
Definition at line 86 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 86 of file G4GenericBiasingPhysics.cc
References fBiasAllProcesses, fBiasedParticles, and fBiasedProcesses.
void G4GenericBiasingPhysics::PhysicsBiasAddPDGRange (G4int PDGlow, G4int PDGhigh, G4bool includeAntiParticle = true)
Definition at line 117 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 117 of file G4GenericBiasingPhysics.cc
References fPhysBiasByPDGRangeHigh, fPhysBiasByPDGRangeLow, G4cout, and G4endl.
Referenced by BiasAddPDGRange().
void G4GenericBiasingPhysics::PhysicsBiasAllCharged (G4bool includeShortLived = false)
Definition at line 151 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 151 of file G4GenericBiasingPhysics.cc
References fPhysBiasAllCharged, and fPhysBiasAllChargedISL.
Referenced by main().
void G4GenericBiasingPhysics::PhysicsBiasAllNeutral (G4bool includeShortLived = false)
Definition at line 168 of file G4GenericBiasingPhysics.cc.
View newest version in sPHENIX GitHub at line 168 of file G4GenericBiasingPhysics.cc
References fPhysBiasAllNeutral, and fPhysBiasAllNeutralISL.
Member Data Documentation
std::vector< G4bool > G4GenericBiasingPhysics::fAllChargedParallelGeometriesISL private
Definition at line 147 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 147 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometryAllCharged(), and AssociateParallelGeometries().
std::vector< G4bool > G4GenericBiasingPhysics::fAllNeutralParallelGeometriesISL private
Definition at line 147 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 147 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometryAllNeutral(), and AssociateParallelGeometries().
std::vector< G4bool > G4GenericBiasingPhysics::fBiasAllProcesses private
Definition at line 126 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 126 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and PhysicsBias().
std::vector< G4String > G4GenericBiasingPhysics::fBiasedParticles private
Definition at line 125 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 125 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and PhysicsBias().
std::vector< std::vector< G4String > > G4GenericBiasingPhysics::fBiasedProcesses private
Definition at line 128 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 128 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and PhysicsBias().
G4bool G4GenericBiasingPhysics::fNonPhysBiasAllCharged private
Definition at line 135 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 135 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllCharged(), ConstructProcess(), and NonPhysicsBiasAllCharged().
G4bool G4GenericBiasingPhysics::fNonPhysBiasAllChargedISL private
Definition at line 136 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 136 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllCharged(), ConstructProcess(), and NonPhysicsBiasAllCharged().
G4bool G4GenericBiasingPhysics::fNonPhysBiasAllNeutral private
Definition at line 137 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 137 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllNeutral(), ConstructProcess(), and NonPhysicsBiasAllNeutral().
G4bool G4GenericBiasingPhysics::fNonPhysBiasAllNeutralISL private
Definition at line 138 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 138 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllNeutral(), ConstructProcess(), and NonPhysicsBiasAllNeutral().
std::vector< G4int > G4GenericBiasingPhysics::fNonPhysBiasByPDGRangeHigh private
Definition at line 134 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 134 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and NonPhysicsBiasAddPDGRange().
std::vector< G4int > G4GenericBiasingPhysics::fNonPhysBiasByPDGRangeLow private
Definition at line 134 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 134 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and NonPhysicsBiasAddPDGRange().
std::vector< G4String > G4GenericBiasingPhysics::fNonPhysBiasedParticles private
Definition at line 130 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 130 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and NonPhysicsBias().
std::vector< G4String > G4GenericBiasingPhysics::fParallelGeometriesForCharged private
Definition at line 146 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 146 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometryAllCharged(), and AssociateParallelGeometries().
std::vector< G4String > G4GenericBiasingPhysics::fParallelGeometriesForNeutral private
Definition at line 146 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 146 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometryAllNeutral().
std::map< G4String, std::vector< G4String > > G4GenericBiasingPhysics::fParallelGeometriesForParticle private
Definition at line 143 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 143 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometry(), and AssociateParallelGeometries().
std::vector< G4String > G4GenericBiasingPhysics::fParticlesWithParallelGeometries private
Definition at line 142 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 142 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometry(), and AssociateParallelGeometries().
std::vector< G4int > G4GenericBiasingPhysics::fPDGhighParallelGeometries private
Definition at line 144 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 144 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometry(), and AssociateParallelGeometries().
std::vector< G4int > G4GenericBiasingPhysics::fPDGlowParallelGeometries private
Definition at line 144 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 144 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometry(), and AssociateParallelGeometries().
std::map< G4int, std::vector< G4String > > G4GenericBiasingPhysics::fPDGrangeParallelGeometries private
Definition at line 145 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 145 of file G4GenericBiasingPhysics.hh
Referenced by AddParallelGeometry(), and AssociateParallelGeometries().
G4bool G4GenericBiasingPhysics::fPhysBiasAllCharged private
Definition at line 135 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 135 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllCharged(), ConstructProcess(), and PhysicsBiasAllCharged().
G4bool G4GenericBiasingPhysics::fPhysBiasAllChargedISL private
Definition at line 136 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 136 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllCharged(), ConstructProcess(), and PhysicsBiasAllCharged().
G4bool G4GenericBiasingPhysics::fPhysBiasAllNeutral private
Definition at line 137 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 137 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllNeutral(), ConstructProcess(), and PhysicsBiasAllNeutral().
G4bool G4GenericBiasingPhysics::fPhysBiasAllNeutralISL private
Definition at line 138 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 138 of file G4GenericBiasingPhysics.hh
Referenced by BiasAllNeutral(), ConstructProcess(), and PhysicsBiasAllNeutral().
std::vector< G4int > G4GenericBiasingPhysics::fPhysBiasByPDGRangeHigh private
Definition at line 133 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 133 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and PhysicsBiasAddPDGRange().
std::vector< G4int > G4GenericBiasingPhysics::fPhysBiasByPDGRangeLow private
Definition at line 133 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 133 of file G4GenericBiasingPhysics.hh
Referenced by ConstructProcess(), and PhysicsBiasAddPDGRange().
G4bool G4GenericBiasingPhysics::fVerbose private
Definition at line 154 of file G4GenericBiasingPhysics.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GenericBiasingPhysics.hh
Referenced by BeVerbose(), and ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4GenericBiasingPhysics.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/src/G4GenericBiasingPhysics.cc