ECCE @ EIC Software: G4RootFileManager Class Reference
G4RootFileManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootFileManager.hh>
Public Member Functions
G4RootFileManager (const G4AnalysisManagerState &state)
virtual ~G4RootFileManager ()
virtual G4bool OpenFile (const G4String &fileName) final
virtual G4bool WriteFile () final
virtual G4bool CloseFile () final
G4bool CreateHistoDirectory ()
G4bool CreateNtupleDirectory ()
void SetNofNtupleFiles (G4int nofFiles)
void SetBasketSize (unsigned int basketSize)
void SetBasketEntries (unsigned int basketEntries)
tools::wroot::directory * GetHistoDirectory () const
tools::wroot::directory * GetNtupleDirectory () const
std::shared_ptr
< tools::wroot::file > GetNtupleFile (G4int index) const
tools::wroot::directory * GetMainNtupleDirectory (G4int index) const
unsigned int GetBasketSize () const
unsigned int GetBasketEntries () const
Public Member Functions inherited from G4VFileManager
G4VFileManager (const G4AnalysisManagerState &state)
virtual ~G4VFileManager ()
virtual G4bool SetFileName (const G4String &fileName) final
void LockHistoDirectoryName ()
void LockNtupleDirectoryName ()
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
G4bool IsOpenFile () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
Public Member Functions inherited from G4BaseFileManager
G4BaseFileManager (const G4AnalysisManagerState &state)
virtual ~G4BaseFileManager ()
G4String GetFileName () const
G4String GetFullFileName (const G4String &baseFileName="", G4bool isPerThread=true) const
G4String GetHnFileName (const G4String &hnType, const G4String &hnName) const
G4String GetNtupleFileName (const G4String &ntupleName) const
G4String GetNtupleFileName (G4int ntupleFileNumber) const
G4String GetPlotFileName () const
G4String GetFileType () const
Private Member Functions
G4bool OpenNtupleFiles ()
G4bool WriteFile (std::shared_ptr< tools::wroot::file > rfile, const G4String &fileName)
G4bool CloseFile (std::shared_ptr< tools::wroot::file > rfile, const G4String &fileName)
Private Attributes
std::shared_ptr
< tools::wroot::file > fFile
tools::wroot::directory * fHistoDirectory
tools::wroot::directory * fNtupleDirectory
G4int fNofNtupleFiles
std::vector< std::shared_ptr
< tools::wroot::file > > fNtupleFiles
std::vector
< tools::wroot::directory * > fMainNtupleDirectories
unsigned int fBasketSize
unsigned int fBasketEntries
Additional Inherited Members
Protected Member Functions inherited from G4BaseFileManager
G4String TakeOffExtension (G4String &name) const
Protected Attributes inherited from G4VFileManager
G4bool fIsOpenFile
G4String fHistoDirectoryName
G4String fNtupleDirectoryName
G4bool fLockFileName
G4bool fLockHistoDirectoryName
G4bool fLockNtupleDirectoryName
Detailed Description
Definition at line 47 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 47 of file G4RootFileManager.hh
Constructor & Destructor Documentation
G4RootFileManager::G4RootFileManager (const G4AnalysisManagerState & state) explicit
Definition at line 42 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 42 of file G4RootFileManager.cc
G4RootFileManager::~G4RootFileManager () virtual
Definition at line 55 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 55 of file G4RootFileManager.cc
Member Function Documentation
G4bool G4RootFileManager::CloseFile () final virtual
Implements G4VFileManager.
Definition at line 233 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 233 of file G4RootFileManager.cc
References fFile, G4VFileManager::fIsOpenFile, G4VFileManager::fLockFileName, fNtupleFiles, G4BaseFileManager::GetFullFileName(), and G4BaseFileManager::GetNtupleFileName().
G4bool G4RootFileManager::CloseFile (std::shared_ptr< tools::wroot::file > rfile, const G4String & fileName) private
Definition at line 148 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 148 of file G4RootFileManager.cc
G4bool G4RootFileManager::CreateHistoDirectory ()
Definition at line 253 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 253 of file G4RootFileManager.cc
References fFile, fHistoDirectory, G4VFileManager::fHistoDirectoryName, G4BaseFileManager::fState, G4Exception(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
Referenced by OpenFile().
G4bool G4RootFileManager::CreateNtupleDirectory ()
Definition at line 287 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 287 of file G4RootFileManager.cc
References fFile, fNtupleDirectory, G4VFileManager::fNtupleDirectoryName, G4BaseFileManager::fState, G4Exception(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
Referenced by OpenFile().
unsigned int G4RootFileManager::GetBasketEntries () const inline
Definition at line 113 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4RootFileManager.hh
References fBasketEntries.
unsigned int G4RootFileManager::GetBasketSize () const inline
Definition at line 110 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RootFileManager.hh
References fBasketSize.
tools::wroot::directory * G4RootFileManager::GetHistoDirectory () const inline
Definition at line 104 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4RootFileManager.hh
References fHistoDirectory.
tools::wroot::directory * G4RootFileManager::GetMainNtupleDirectory (G4int index) const
Definition at line 339 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 339 of file G4RootFileManager.cc
References fMainNtupleDirectories, fNtupleDirectory, G4Exception(), and JustWarning.
tools::wroot::directory * G4RootFileManager::GetNtupleDirectory () const inline
Definition at line 107 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4RootFileManager.hh
References fNtupleDirectory.
std::shared_ptr< tools::wroot::file > G4RootFileManager::GetNtupleFile (G4int index) const
Definition at line 322 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4RootFileManager.cc
References fFile, fNtupleFiles, G4Exception(), and JustWarning.
G4bool G4RootFileManager::OpenFile (const G4String & fileName) final virtual
Implements G4VFileManager.
Definition at line 177 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 177 of file G4RootFileManager.cc
References CreateHistoDirectory(), CreateNtupleDirectory(), fFile, G4BaseFileManager::fFileName, G4VFileManager::fIsOpenFile, G4VFileManager::fLockFileName, G4VFileManager::fLockHistoDirectoryName, G4VFileManager::fLockNtupleDirectoryName, G4BaseFileManager::fState, G4cout, G4Exception(), G4AnalysisManagerState::GetCompressionLevel(), G4BaseFileManager::GetFullFileName(), JustWarning, and OpenNtupleFiles().
G4bool G4RootFileManager::OpenNtupleFiles () private
Definition at line 63 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 63 of file G4RootFileManager.cc
References fFile, fMainNtupleDirectories, fNofNtupleFiles, G4VFileManager::fNtupleDirectoryName, fNtupleFiles, G4BaseFileManager::fState, G4cout, G4Exception(), G4AnalysisManagerState::GetCompressionLevel(), G4BaseFileManager::GetNtupleFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and propagation_timing::rfile.
Referenced by OpenFile().
void G4RootFileManager::SetBasketEntries (unsigned int basketEntries) inline
Definition at line 101 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4RootFileManager.hh
References fBasketEntries.
void G4RootFileManager::SetBasketSize (unsigned int basketSize) inline
Definition at line 98 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RootFileManager.hh
References fBasketSize.
void G4RootFileManager::SetNofNtupleFiles (G4int nofFiles) inline
Definition at line 95 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RootFileManager.hh
References fNofNtupleFiles.
G4bool G4RootFileManager::WriteFile () final virtual
Implements G4VFileManager.
Definition at line 217 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 217 of file G4RootFileManager.cc
References fFile, fNtupleFiles, G4BaseFileManager::GetFullFileName(), and G4BaseFileManager::GetNtupleFileName().
G4bool G4RootFileManager::WriteFile (std::shared_ptr< tools::wroot::file > rfile, const G4String & fileName) private
Definition at line 121 of file G4RootFileManager.cc.
View newest version in sPHENIX GitHub at line 121 of file G4RootFileManager.cc
References n.
Member Data Documentation
unsigned int G4RootFileManager::fBasketEntries private
Definition at line 90 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RootFileManager.hh
Referenced by GetBasketEntries(), and SetBasketEntries().
unsigned int G4RootFileManager::fBasketSize private
Definition at line 89 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RootFileManager.hh
Referenced by GetBasketSize(), and SetBasketSize().
std::shared_ptr<tools::wroot::file> G4RootFileManager::fFile private
Definition at line 83 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RootFileManager.hh
Referenced by CloseFile(), CreateHistoDirectory(), CreateNtupleDirectory(), GetNtupleFile(), OpenFile(), OpenNtupleFiles(), and WriteFile().
tools::wroot::directory* G4RootFileManager::fHistoDirectory private
Definition at line 84 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RootFileManager.hh
Referenced by CreateHistoDirectory(), and GetHistoDirectory().
std::vector<tools::wroot::directory*> G4RootFileManager::fMainNtupleDirectories private
Definition at line 88 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RootFileManager.hh
Referenced by GetMainNtupleDirectory(), and OpenNtupleFiles().
G4int G4RootFileManager::fNofNtupleFiles private
Definition at line 86 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RootFileManager.hh
Referenced by OpenNtupleFiles(), and SetNofNtupleFiles().
tools::wroot::directory* G4RootFileManager::fNtupleDirectory private
Definition at line 85 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RootFileManager.hh
Referenced by CreateNtupleDirectory(), GetMainNtupleDirectory(), and GetNtupleDirectory().
std::vector<std::shared_ptr<tools::wroot::file> > G4RootFileManager::fNtupleFiles private
Definition at line 87 of file G4RootFileManager.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RootFileManager.hh
Referenced by CloseFile(), GetNtupleFile(), OpenNtupleFiles(), and WriteFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootFileManager.hh
geant4/tree/geant4-10.6-release/source/analysis/root/src/G4RootFileManager.cc