ECCE @ EIC Software: DetectorConstruction0 Class Reference
DetectorConstruction0 Class Reference
Simple detector construction with only a world volume.
#include <geant4/tree/geant4-10.6-release/examples/extended/common/include/DetectorConstruction0.hh>
Public Member Functions
DetectorConstruction0 (const G4String &materialName="G4_AIR", G4double hx=50 *CLHEP::cm, G4double hy=50 *CLHEP::cm, G4double hz=50 *CLHEP::cm)
~DetectorConstruction0 ()
virtual G4VPhysicalVolume * Construct ()
void SetMaterial (const G4String &materialName)
void SetDimensions (G4ThreeVector dimensions)
DetectorConstruction0 (const G4String &materialName="G4_AIR", G4double hx=50 *CLHEP::cm, G4double hy=50 *CLHEP::cm, G4double hz=50 *CLHEP::cm)
~DetectorConstruction0 ()
virtual G4VPhysicalVolume * Construct ()
void SetMaterial (const G4String &materialName)
void SetDimensions (G4ThreeVector dimensions)
DetectorConstruction0 (const G4String &materialName="G4_AIR", G4double hx=50 *CLHEP::cm, G4double hy=50 *CLHEP::cm, G4double hz=50 *CLHEP::cm)
~DetectorConstruction0 ()
virtual G4VPhysicalVolume * Construct ()
void SetMaterial (const G4String &materialName)
void SetDimensions (G4ThreeVector dimensions)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineCommands ()
void DefineCommands ()
void DefineCommands ()
Private Attributes
G4GenericMessenger * fMessenger
G4String fMaterialName
G4ThreeVector fDimensions
G4LogicalVolume * fWorldVolume
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Simple detector construction with only a world volume.
Definition at line 43 of file DetectorConstruction0.hh.
View newest version in sPHENIX GitHub at line 43 of file DetectorConstruction0.hh
Constructor & Destructor Documentation
DetectorConstruction0::DetectorConstruction0 (const G4String & materialName = "G4_AIR", G4double hx = 50*CLHEP::cm, G4double hy = 50*CLHEP::cm, G4double hz = 50*CLHEP::cm)
Definition at line 41 of file DetectorConstruction0.cc.
View newest version in sPHENIX GitHub at line 41 of file DetectorConstruction0.cc
References DefineCommands().
DetectorConstruction0::~DetectorConstruction0 ()
Definition at line 55 of file DetectorConstruction0.cc.
View newest version in sPHENIX GitHub at line 55 of file DetectorConstruction0.cc
References fMessenger.
DetectorConstruction0::DetectorConstruction0 (const G4String & materialName = "G4_AIR", G4double hx = 50 *CLHEP::cm, G4double hy = 50 *CLHEP::cm, G4double hz = 50 *CLHEP::cm)
DetectorConstruction0::~DetectorConstruction0 ()
DetectorConstruction0::DetectorConstruction0 (const G4String & materialName = "G4_AIR", G4double hx = 50 *CLHEP::cm, G4double hy = 50 *CLHEP::cm, G4double hz = 50 *CLHEP::cm)
DetectorConstruction0::~DetectorConstruction0 ()
Member Function Documentation
G4VPhysicalVolume * DetectorConstruction0::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 62 of file DetectorConstruction0.cc.
View newest version in sPHENIX GitHub at line 62 of file DetectorConstruction0.cc
References fDimensions, fMaterialName, fWorldVolume, G4NistManager::Instance(), material(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
virtual G4VPhysicalVolume* DetectorConstruction0::Construct () virtual
Implements G4VUserDetectorConstruction.
virtual G4VPhysicalVolume* DetectorConstruction0::Construct () virtual
Implements G4VUserDetectorConstruction.
void DetectorConstruction0::DefineCommands () private
void DetectorConstruction0::DefineCommands () private
Definition at line 126 of file DetectorConstruction0.cc.
View newest version in sPHENIX GitHub at line 126 of file DetectorConstruction0.cc
References G4GenericMessenger::DeclareMethod(), G4GenericMessenger::DeclareMethodWithUnit(), fMessenger, G4State_PreInit, G4GenericMessenger::Command::SetDefaultValue(), SetDimensions(), SetMaterial(), G4GenericMessenger::Command::SetParameterName(), and G4GenericMessenger::Command::SetStates().
Referenced by DetectorConstruction0().
void DetectorConstruction0::DefineCommands () private
void DetectorConstruction0::SetDimensions (G4ThreeVector dimensions)
void DetectorConstruction0::SetDimensions (G4ThreeVector dimensions)
void DetectorConstruction0::SetDimensions (G4ThreeVector dimensions)
Set world dimension (in half lengths). This setting has effect only if called in PreInit> phase
Definition at line 116 of file DetectorConstruction0.cc.
View newest version in sPHENIX GitHub at line 116 of file DetectorConstruction0.cc
References fDimensions.
Referenced by DefineCommands().
void DetectorConstruction0::SetMaterial (const G4String & materialName)
void DetectorConstruction0::SetMaterial (const G4String & materialName)
void DetectorConstruction0::SetMaterial (const G4String & materialName)
Definition at line 99 of file DetectorConstruction0.cc.
View newest version in sPHENIX GitHub at line 99 of file DetectorConstruction0.cc
References fWorldVolume, G4cerr, G4cout, G4endl, G4NistManager::Instance(), and G4LogicalVolume::SetMaterial().
Referenced by DefineCommands().
Member Data Documentation
G4ThreeVector DetectorConstruction0::fDimensions private
Definition at line 66 of file DetectorConstruction0.hh.
View newest version in sPHENIX GitHub at line 66 of file DetectorConstruction0.hh
Referenced by Construct(), and SetDimensions().
G4String DetectorConstruction0::fMaterialName private
Definition at line 65 of file DetectorConstruction0.hh.
View newest version in sPHENIX GitHub at line 65 of file DetectorConstruction0.hh
Referenced by Construct().
G4GenericMessenger * DetectorConstruction0::fMessenger private
Definition at line 64 of file DetectorConstruction0.hh.
View newest version in sPHENIX GitHub at line 64 of file DetectorConstruction0.hh
Referenced by DefineCommands(), and ~DetectorConstruction0().
G4LogicalVolume * DetectorConstruction0::fWorldVolume private
Definition at line 67 of file DetectorConstruction0.hh.
View newest version in sPHENIX GitHub at line 67 of file DetectorConstruction0.hh
Referenced by Construct(), and SetMaterial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/common/include/DetectorConstruction0.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/common/include/DetectorConstruction0.hh
geant4/tree/geant4-10.6-release/examples/extended/g3tog4/clGeometry/common/include/DetectorConstruction0.hh
geant4/tree/geant4-10.6-release/examples/extended/common/src/DetectorConstruction0.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/common/src/DetectorConstruction0.cc
geant4/tree/geant4-10.6-release/examples/extended/g3tog4/clGeometry/common/src/DetectorConstruction0.cc