ECCE @ EIC Software: G4VFacet Class Reference
G4VFacet Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VFacet.hh>
Public Member Functions
G4VFacet ()
virtual ~G4VFacet ()
G4bool operator== (const G4VFacet &right) const
virtual G4int GetNumberOfVertices () const =0
virtual G4ThreeVector GetVertex (G4int i) const =0
virtual void SetVertex (G4int i, const G4ThreeVector &val)=0
virtual G4GeometryType GetEntityType () const =0
virtual G4ThreeVector GetSurfaceNormal () const =0
virtual G4bool IsDefined () const =0
virtual G4ThreeVector GetCircumcentre () const =0
virtual G4double GetRadius () const =0
virtual G4VFacet * GetClone ()=0
virtual G4double Distance (const G4ThreeVector &, G4double)=0
virtual G4double Distance (const G4ThreeVector &, G4double, const G4bool)=0
virtual G4double Extent (const G4ThreeVector)=0
virtual G4bool Intersect (const G4ThreeVector &, const G4ThreeVector &, const G4bool, G4double &, G4double &, G4ThreeVector &)=0
virtual G4double GetArea () const =0
virtual G4ThreeVector GetPointOnFace () const =0
void ApplyTranslation (const G4ThreeVector v)
std::ostream & StreamInfo (std::ostream &os) const
G4bool IsInside (const G4ThreeVector &p) const
virtual G4int AllocatedMemory ()=0
virtual void SetVertexIndex (G4int i, G4int j)=0
virtual G4int GetVertexIndex (G4int i) const =0
virtual void SetVertices (std::vector< G4ThreeVector > *vertices)=0
Protected Attributes
G4double kCarTolerance
Static Protected Attributes
static const G4double dirTolerance = 1.0E-14
Detailed Description
Definition at line 50 of file G4VFacet.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VFacet.hh
Constructor & Destructor Documentation
G4VFacet::G4VFacet ()
Definition at line 44 of file G4VFacet.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VFacet.cc
References G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), and kCarTolerance.
G4VFacet::~G4VFacet () virtual
Definition at line 51 of file G4VFacet.cc.
View newest version in sPHENIX GitHub at line 51 of file G4VFacet.cc
Member Function Documentation
virtual G4int G4VFacet::AllocatedMemory () pure virtual
Implemented in G4QuadrangularFacet, and G4TriangularFacet.
Referenced by G4TessellatedSolid::AllocatedMemoryWithoutVoxels().
void G4VFacet::ApplyTranslation (const G4ThreeVector v)
Definition at line 85 of file G4VFacet.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VFacet.cc
References n.
virtual G4double G4VFacet::Distance (const G4ThreeVector & , G4double) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::DistanceToOutCandidates(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4TessellatedSolid::InsideNoVoxels(), G4TessellatedSolid::InsideVoxels(), G4TessellatedSolid::MinDistanceFacet(), G4TessellatedSolid::Normal(), G4TessellatedSolid::SafetyFromInside(), and G4TessellatedSolid::SafetyFromOutside().
virtual G4double G4VFacet::Distance (const G4ThreeVector & , G4double , const G4bool) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
virtual G4double G4VFacet::Extent (const G4ThreeVector) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4Voxelizer::BuildVoxelLimits().
virtual G4double G4VFacet::GetArea () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::GetCubicVolume(), and G4TessellatedSolid::GetSurfaceArea().
virtual G4ThreeVector G4VFacet::GetCircumcentre () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::AddFacet(), and operator==().
virtual G4VFacet* G4VFacet::GetClone () pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::operator+=().
virtual G4GeometryType G4VFacet::GetEntityType () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
virtual G4int G4VFacet::GetNumberOfVertices () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::CalculateExtent(), G4TessellatedSolid::CreatePolyhedron(), G4TessellatedSolid::CreateVertexList(), operator==(), PHG4GDMLWriteSolids::TessellatedWrite(), and G4GDMLWriteSolids::TessellatedWrite().
virtual G4ThreeVector G4VFacet::GetPointOnFace () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
virtual G4double G4VFacet::GetRadius () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
virtual G4ThreeVector G4VFacet::GetSurfaceNormal () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::CalculateExtent(), G4TessellatedSolid::GetCubicVolume(), G4TessellatedSolid::Normal(), and operator==().
virtual G4ThreeVector G4VFacet::GetVertex (G4int i) const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::CalculateExtent(), G4TessellatedSolid::CreateVertexList(), G4TessellatedSolid::GetCubicVolume(), operator==(), PHG4GDMLWriteSolids::TessellatedWrite(), and G4GDMLWriteSolids::TessellatedWrite().
virtual G4int G4VFacet::GetVertexIndex (G4int i) const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::CreatePolyhedron().
virtual G4bool G4VFacet::Intersect (const G4ThreeVector & , const G4ThreeVector & , const G4bool , G4double & , G4double & , G4ThreeVector &) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::DistanceToInCandidates(), G4TessellatedSolid::DistanceToInNoVoxels(), G4TessellatedSolid::DistanceToOutCandidates(), G4TessellatedSolid::DistanceToOutNoVoxels(), and G4TessellatedSolid::InsideVoxels().
virtual G4bool G4VFacet::IsDefined () const pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::AddFacet().
G4bool G4VFacet::IsInside (const G4ThreeVector & p) const
Definition at line 112 of file G4VFacet.cc.
View newest version in sPHENIX GitHub at line 112 of file G4VFacet.cc
References d, and CLHEP::Hep3Vector::dot().
Referenced by G4TessellatedSolid::SetExtremeFacets().
G4bool G4VFacet::operator== (const G4VFacet & right) const
Definition at line 57 of file G4VFacet.cc.
View newest version in sPHENIX GitHub at line 57 of file G4VFacet.cc
References GetCircumcentre(), GetNumberOfVertices(), GetSurfaceNormal(), GetVertex(), and kCarTolerance.
virtual void G4VFacet::SetVertex (G4int i, const G4ThreeVector & val) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
virtual void G4VFacet::SetVertexIndex (G4int i, G4int j) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::CreateVertexList().
virtual void G4VFacet::SetVertices (std::vector< G4ThreeVector > * vertices) pure virtual
Implemented in G4TriangularFacet, and G4QuadrangularFacet.
Referenced by G4TessellatedSolid::CreateVertexList().
std::ostream & G4VFacet::StreamInfo (std::ostream & os) const
Definition at line 96 of file G4VFacet.cc.
View newest version in sPHENIX GitHub at line 96 of file G4VFacet.cc
References G4endl, and n.
Referenced by G4TessellatedSolid::AddFacet(), and G4TessellatedSolid::StreamInfo().
Member Data Documentation
const G4double G4VFacet::dirTolerance = 1.0E-14 static protected
Definition at line 92 of file G4VFacet.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VFacet.hh
Referenced by G4QuadrangularFacet::Distance(), and G4TriangularFacet::Intersect().
G4double G4VFacet::kCarTolerance protected
Definition at line 93 of file G4VFacet.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VFacet.hh
Referenced by G4TriangularFacet::Distance(), G4QuadrangularFacet::G4QuadrangularFacet(), G4TriangularFacet::G4TriangularFacet(), and G4TriangularFacet::Intersect().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VFacet.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4VFacet.cc