ECCE @ EIC Software: G4TheoFSGenerator Class Reference
G4TheoFSGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/theo_high_energy/include/G4TheoFSGenerator.hh>
Public Member Functions
G4TheoFSGenerator (const G4String &name="TheoFSGenerator")
~G4TheoFSGenerator ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &thePrimary, G4Nucleus &theNucleus)
void SetTransport (G4VIntraNuclearTransportModel *const value)
void SetHighEnergyGenerator (G4VHighEnergyGenerator *const value)
void SetQuasiElasticChannel (G4QuasiElasticChannel *const value)
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4TheoFSGenerator (const G4TheoFSGenerator &right)
const G4TheoFSGenerator & operator= (const G4TheoFSGenerator &right)
G4bool operator== (const G4TheoFSGenerator &right) const
G4bool operator!= (const G4TheoFSGenerator &right) const
const
G4VIntraNuclearTransportModel * GetTransport () const
const G4VHighEnergyGenerator * GetHighEnergyGenerator () const
const G4HadFinalState * GetFinalState () const
Private Attributes
G4VIntraNuclearTransportModel * theTransport
G4VHighEnergyGenerator * theHighEnergyGenerator
G4DecayStrongResonances theDecay
G4HadFinalState * theParticleChange
G4QuasiElasticChannel * theQuasielastic
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 52 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 52 of file G4TheoFSGenerator.hh
Constructor & Destructor Documentation
G4TheoFSGenerator::G4TheoFSGenerator (const G4String & name = "TheoFSGenerator")
Definition at line 39 of file G4TheoFSGenerator.cc.
View newest version in sPHENIX GitHub at line 39 of file G4TheoFSGenerator.cc
References theParticleChange.
G4TheoFSGenerator::~G4TheoFSGenerator ()
Definition at line 47 of file G4TheoFSGenerator.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TheoFSGenerator.cc
References theParticleChange.
G4TheoFSGenerator::G4TheoFSGenerator (const G4TheoFSGenerator & right) private
Member Function Documentation
G4HadFinalState * G4TheoFSGenerator::ApplyYourself (const G4HadProjectile & thePrimary, G4Nucleus & theNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 68 of file G4TheoFSGenerator.cc.
View newest version in sPHENIX GitHub at line 68 of file G4TheoFSGenerator.cc
References G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4QuasiElasticChannel::GetFraction(), G4HadProjectile::GetGlobalTime(), G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNucleons(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4VHighEnergyGenerator::GetProjectileNucleus(), G4VHighEnergyGenerator::GetWoundedNucleus(), G4Nucleus::GetZ_asInt(), isAlive, G4Neutron::Neutron(), G4DecayStrongResonances::Propagate(), G4VIntraNuclearTransportModel::Propagate(), G4VIntraNuclearTransportModel::PropagateNuclNucl(), G4Proton::Proton(), G4QuasiElasticChannel::Scatter(), G4VHighEnergyGenerator::Scatter(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetMomentumChange(), G4VIntraNuclearTransportModel::SetPrimaryProjectile(), G4HadFinalState::SetStatusChange(), stopAndKill, theDecay, theHighEnergyGenerator, theParticleChange, theQuasielastic, theTransport, Acts::VectorHelpers::time(), CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by G4ElectroVDNuclearModel::CalculateHadronicVertex(), and G4MuonVDNuclearModel::CalculateHadronicVertex().
std::pair< G4double, G4double > G4TheoFSGenerator::GetEnergyMomentumCheckLevels () const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 224 of file G4TheoFSGenerator.cc.
View newest version in sPHENIX GitHub at line 224 of file G4TheoFSGenerator.cc
References DBL_MAX, G4HadronicInteraction::GetEnergyMomentumCheckLevels(), and theHighEnergyGenerator.
const G4HadFinalState * G4TheoFSGenerator::GetFinalState () const inline private
Definition at line 112 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 112 of file G4TheoFSGenerator.hh
References theParticleChange.
const G4VHighEnergyGenerator * G4TheoFSGenerator::GetHighEnergyGenerator () const inline private
Definition at line 97 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 97 of file G4TheoFSGenerator.hh
References theHighEnergyGenerator.
const G4VIntraNuclearTransportModel * G4TheoFSGenerator::GetTransport () const inline private
Definition at line 87 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 87 of file G4TheoFSGenerator.hh
References theTransport.
void G4TheoFSGenerator::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 52 of file G4TheoFSGenerator.cc.
View newest version in sPHENIX GitHub at line 52 of file G4TheoFSGenerator.cc
References G4HadronicInteraction::GetModelName(), G4VHighEnergyGenerator::ModelDescription(), G4VIntraNuclearTransportModel::PropagateModelDescription(), theHighEnergyGenerator, and theTransport.
G4bool G4TheoFSGenerator::operator!= (const G4TheoFSGenerator & right) const private
const G4TheoFSGenerator& G4TheoFSGenerator::operator= (const G4TheoFSGenerator & right) private
G4bool G4TheoFSGenerator::operator== (const G4TheoFSGenerator & right) const private
void G4TheoFSGenerator::SetHighEnergyGenerator (G4VHighEnergyGenerator *const value) inline
Definition at line 102 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 102 of file G4TheoFSGenerator.hh
References theHighEnergyGenerator.
Referenced by BiasingOperation::BiasingOperation(), G4BertiniElectroNuclearBuilder::Build(), G4FTFBuilder::BuildModel(), G4QGSBuilder::BuildModel(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder(), G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder(), G4QGSBinaryPiKBuilder::G4QGSBinaryPiKBuilder(), G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder(), G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder(), G4QGSPKaonBuilder::G4QGSPKaonBuilder(), G4QGSPLundStrFragmProtonBuilder::G4QGSPLundStrFragmProtonBuilder(), G4QGSPNeutronBuilder::G4QGSPNeutronBuilder(), G4QGSPPiKBuilder::G4QGSPPiKBuilder(), G4QGSPPionBuilder::G4QGSPPionBuilder(), and G4QGSPProtonBuilder::G4QGSPProtonBuilder().
void G4TheoFSGenerator::SetQuasiElasticChannel (G4QuasiElasticChannel *const value) inline
Definition at line 107 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 107 of file G4TheoFSGenerator.hh
References theQuasielastic.
Referenced by G4QGSBuilder::BuildModel(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder(), G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder(), G4QGSBinaryPiKBuilder::G4QGSBinaryPiKBuilder(), G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder(), G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder(), G4QGSPKaonBuilder::G4QGSPKaonBuilder(), G4QGSPLundStrFragmProtonBuilder::G4QGSPLundStrFragmProtonBuilder(), G4QGSPNeutronBuilder::G4QGSPNeutronBuilder(), G4QGSPPiKBuilder::G4QGSPPiKBuilder(), G4QGSPPionBuilder::G4QGSPPionBuilder(), and G4QGSPProtonBuilder::G4QGSPProtonBuilder().
void G4TheoFSGenerator::SetTransport (G4VIntraNuclearTransportModel *const value) inline
Definition at line 92 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 92 of file G4TheoFSGenerator.hh
References theTransport.
Referenced by BiasingOperation::BiasingOperation(), G4BertiniElectroNuclearBuilder::Build(), G4FTFBuilder::BuildModel(), G4QGSBuilder::BuildModel(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder(), G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder(), G4QGSBinaryPiKBuilder::G4QGSBinaryPiKBuilder(), G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder(), G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder(), G4QGSPKaonBuilder::G4QGSPKaonBuilder(), G4QGSPLundStrFragmProtonBuilder::G4QGSPLundStrFragmProtonBuilder(), G4QGSPNeutronBuilder::G4QGSPNeutronBuilder(), G4QGSPPiKBuilder::G4QGSPPiKBuilder(), G4QGSPPionBuilder::G4QGSPPionBuilder(), and G4QGSPProtonBuilder::G4QGSPProtonBuilder().
Member Data Documentation
G4DecayStrongResonances G4TheoFSGenerator::theDecay private
Definition at line 82 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 82 of file G4TheoFSGenerator.hh
Referenced by ApplyYourself().
G4VHighEnergyGenerator* G4TheoFSGenerator::theHighEnergyGenerator private
Definition at line 81 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 81 of file G4TheoFSGenerator.hh
Referenced by ApplyYourself(), GetEnergyMomentumCheckLevels(), GetHighEnergyGenerator(), ModelDescription(), and SetHighEnergyGenerator().
G4HadFinalState* G4TheoFSGenerator::theParticleChange private
Definition at line 83 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 83 of file G4TheoFSGenerator.hh
Referenced by ApplyYourself(), G4TheoFSGenerator(), GetFinalState(), and ~G4TheoFSGenerator().
G4QuasiElasticChannel* G4TheoFSGenerator::theQuasielastic private
Definition at line 84 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 84 of file G4TheoFSGenerator.hh
Referenced by ApplyYourself(), and SetQuasiElasticChannel().
G4VIntraNuclearTransportModel* G4TheoFSGenerator::theTransport private
Definition at line 80 of file G4TheoFSGenerator.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TheoFSGenerator.hh
Referenced by ApplyYourself(), GetTransport(), ModelDescription(), and SetTransport().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/theo_high_energy/include/G4TheoFSGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/theo_high_energy/src/G4TheoFSGenerator.cc