ECCE @ EIC Software: G4InterpolationManager Class Reference
G4InterpolationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4InterpolationManager.hh>
Public Member Functions
G4InterpolationManager ()
~G4InterpolationManager ()
G4InterpolationManager & operator= (const G4InterpolationManager &aManager)
void Init (G4int aScheme, G4int aRange)
void Init (G4InterpolationScheme aScheme, G4int aRange)
void Init (std::istream &aDataFile)
G4InterpolationScheme MakeScheme (G4int it)
G4InterpolationScheme GetScheme (G4int index) const
void CleanUp ()
G4InterpolationScheme GetInverseScheme (G4int index)
void AppendScheme (G4int aPoint, const G4InterpolationScheme &aScheme)
Private Attributes
G4int nRanges
G4InterpolationScheme * scheme
G4int * start
G4int * range
G4int nEntries
Friends
class G4InterpolationIterator
Detailed Description
Definition at line 37 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 37 of file G4InterpolationManager.hh
Constructor & Destructor Documentation
G4InterpolationManager::G4InterpolationManager () inline
Definition at line 43 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4InterpolationManager.hh
References LINLIN, nEntries, nRanges, range, scheme, and start.
G4InterpolationManager::~G4InterpolationManager () inline
Definition at line 55 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 55 of file G4InterpolationManager.hh
References range, scheme, and start.
Member Function Documentation
void G4InterpolationManager::AppendScheme (G4int aPoint, const G4InterpolationScheme & aScheme)
Definition at line 90 of file G4InterpolationManager.cc.
View newest version in sPHENIX GitHub at line 90 of file G4InterpolationManager.cc
References buffer, G4cout, G4endl, nEntries, nRanges, range, scheme, and start.
Referenced by G4ParticleHPVector::Merge(), and G4ParticleHPVector::SetScheme().
void G4InterpolationManager::CleanUp () inline
Definition at line 142 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 142 of file G4InterpolationManager.hh
References nEntries, and nRanges.
Referenced by G4ParticleHPVector::CleanUp().
G4InterpolationScheme G4InterpolationManager::GetInverseScheme (G4int index) inline
Definition at line 148 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 148 of file G4InterpolationManager.hh
References CHISTO, CLINLOG, CLOGLIN, CRANDOM, GetScheme(), HISTO, LINLOG, LOGLIN, RANDOM, UHISTO, ULINLOG, ULOGLIN, and URANDOM.
Referenced by G4ParticleHPContAngularPar::Sample().
G4InterpolationScheme G4InterpolationManager::GetScheme (G4int index) const inline
Definition at line 131 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 131 of file G4InterpolationManager.hh
References it, nRanges, scheme, and start.
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation(), G4ParticleHPAngularP::GetCosTh(), GetInverseScheme(), G4ParticleHPVector::GetMeanX(), G4ParticleHPVector::GetScheme(), G4ParticleHPVector::GetXsec(), G4ParticleHPPartial::GetY(), G4ParticleHPVector::Integrate(), G4ParticleHPVector::IntegrateAndNormalise(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContEnergyAngular::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPPartial::Sample(), G4ParticleHPLegendreStore::SampleDiscreteTwoBody(), G4ParticleHPLegendreStore::SampleElastic(), and G4ParticleHPLegendreStore::SampleMax().
void G4InterpolationManager::Init (G4int aScheme, G4int aRange) inline
Definition at line 84 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4InterpolationManager.hh
References MakeScheme(), nEntries, nRanges, range, scheme, and start.
Referenced by G4ParticleHPAngularP::Init(), G4ParticleHPArbitaryTab::Init(), G4ParticleHPDiscreteTwoBody::Init(), G4ParticleHPLabAngularEnergy::Init(), G4ParticleHPContEnergyAngular::Init(), G4ParticleHPVector::Init(), G4ParticleHPPhotonDist::InitAngular(), G4ParticleHPPartial::InitInterpolation(), G4ParticleHPLegendreStore::InitInterpolation(), G4ParticleHPVector::InitInterpolation(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), and G4ParticleHPContAngularPar::SetInterpolation().
void G4InterpolationManager::Init (G4InterpolationScheme aScheme, G4int aRange) inline
Definition at line 92 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 92 of file G4InterpolationManager.hh
References nEntries, nRanges, range, scheme, and start.
void G4InterpolationManager::Init (std::istream & aDataFile) inline
Definition at line 101 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4InterpolationManager.hh
References it, MakeScheme(), nEntries, nRanges, range, scheme, and start.
G4InterpolationScheme G4InterpolationManager::MakeScheme (G4int it)
Definition at line 33 of file G4InterpolationManager.cc.
View newest version in sPHENIX GitHub at line 33 of file G4InterpolationManager.cc
References CHISTO, CLINLIN, CLINLOG, CLOGLIN, CLOGLOG, HISTO, LINLIN, LINLOG, LOGLIN, LOGLOG, UHISTO, ULINLIN, ULINLOG, ULOGLIN, and ULOGLOG.
Referenced by Init().
G4InterpolationManager& G4InterpolationManager::operator= (const G4InterpolationManager & aManager) inline
Definition at line 62 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 62 of file G4InterpolationManager.hh
References nEntries, nRanges, range, scheme, and start.
Friends And Related Function Documentation
friend class G4InterpolationIterator friend
Definition at line 41 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 41 of file G4InterpolationManager.hh
Member Data Documentation
G4int G4InterpolationManager::nEntries private
Definition at line 198 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 198 of file G4InterpolationManager.hh
Referenced by AppendScheme(), CleanUp(), G4InterpolationManager(), Init(), and operator=().
G4int G4InterpolationManager::nRanges private
Definition at line 194 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 194 of file G4InterpolationManager.hh
Referenced by AppendScheme(), CleanUp(), G4InterpolationManager(), GetScheme(), Init(), and operator=().
G4int* G4InterpolationManager::range private
Definition at line 197 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 197 of file G4InterpolationManager.hh
Referenced by AppendScheme(), G4InterpolationManager(), Init(), operator=(), and ~G4InterpolationManager().
G4InterpolationScheme* G4InterpolationManager::scheme private
Definition at line 195 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 195 of file G4InterpolationManager.hh
Referenced by AppendScheme(), G4InterpolationManager(), GetScheme(), Init(), operator=(), and ~G4InterpolationManager().
G4int* G4InterpolationManager::start private
Definition at line 196 of file G4InterpolationManager.hh.
View newest version in sPHENIX GitHub at line 196 of file G4InterpolationManager.hh
Referenced by AppendScheme(), G4InterpolationIterator::Fetch(), G4InterpolationManager(), GetScheme(), Init(), operator=(), and ~G4InterpolationManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4InterpolationManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4InterpolationManager.cc