ECCE @ EIC Software: G4ProductionCuts Class Reference
G4ProductionCuts Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4ProductionCuts.hh>
Public Member Functions
G4ProductionCuts ()
G4ProductionCuts (const G4ProductionCuts &right)
G4ProductionCuts & operator= (const G4ProductionCuts &right)
virtual ~G4ProductionCuts ()
G4bool operator== (const G4ProductionCuts &right) const
G4bool operator!= (const G4ProductionCuts &right) const
void SetProductionCut (G4double cut, G4int index=-1)
void SetProductionCut (G4double cut, G4ParticleDefinition *ptcl)
void SetProductionCut (G4double cut, const G4String &pName)
G4double GetProductionCut (G4int index) const
G4double GetProductionCut (const G4String &name) const
void SetProductionCuts (std::vector< G4double > &)
const std::vector< G4double > & GetProductionCuts () const
G4bool IsModified () const
void PhysicsTableUpdated ()
Static Public Member Functions
static G4int GetIndex (const G4String &name)
static G4int GetIndex (const G4ParticleDefinition *ptcl)
Protected Attributes
std::vector< G4double > fRangeCuts
G4bool isModified
Static Private Attributes
static G4ThreadLocal
G4ParticleDefinition * gammaDef = nullptr
static G4ThreadLocal
G4ParticleDefinition * electDef = nullptr
static G4ThreadLocal
G4ParticleDefinition * positDef = nullptr
static G4ThreadLocal
G4ParticleDefinition * protonDef = nullptr
Detailed Description
Definition at line 60 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ProductionCuts.hh
Constructor & Destructor Documentation
G4ProductionCuts::G4ProductionCuts ()
Definition at line 43 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ProductionCuts.cc
References fRangeCuts, and NumberOfG4CutIndex.
G4ProductionCuts::G4ProductionCuts (const G4ProductionCuts & right)
Definition at line 51 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ProductionCuts.cc
References fRangeCuts, NumberOfG4CutIndex, and right.
G4ProductionCuts::~G4ProductionCuts () virtual
Definition at line 60 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 60 of file G4ProductionCuts.cc
References fRangeCuts.
Member Function Documentation
G4int G4ProductionCuts::GetIndex (const G4String & name) static
Definition at line 90 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ProductionCuts.cc
References G4InuclParticleNames::electron, G4InuclParticleNames::positron, and G4InuclParticleNames::proton.
Referenced by G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4ProductionCutsTable::ConvertRangeToEnergy(), GetProductionCut(), STCyclotronPhysicsList::SetCutFoil(), STCyclotronPhysicsList::SetCutTarget(), IORTPhysicsList::SetDetectorCut(), and SetProductionCut().
G4int G4ProductionCuts::GetIndex (const G4ParticleDefinition * ptcl) static
Definition at line 108 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 108 of file G4ProductionCuts.cc
References electDef, gammaDef, G4ParticleDefinition::GetParticleName(), positDef, and protonDef.
G4double G4ProductionCuts::GetProductionCut (G4int index) const inline
Definition at line 155 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ProductionCuts.hh
References fRangeCuts, and NumberOfG4CutIndex.
Referenced by G4VEnergyLossProcess::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4ContinuousGainOfEnergy::DefineMaterial(), G4ProductionCutsTable::DumpCouples(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), G4RDRangeTest::Escape(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), G4hImpactIonisation::GetConstraints(), G4VUserPhysicsList::GetCutValue(), GetProductionCut(), G4EmModelManager::Initialise(), G4ProductionCutsTable::StoreMaterialCutsCoupleInfo(), and G4ProductionCutsTable::UpdateCoupleTable().
G4double G4ProductionCuts::GetProductionCut (const G4String & name) const inline
Definition at line 165 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ProductionCuts.hh
References GetIndex(), and GetProductionCut().
const std::vector< G4double > & G4ProductionCuts::GetProductionCuts () const inline
Definition at line 172 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ProductionCuts.hh
References fRangeCuts.
Referenced by G4ProductionCutsTable::UpdateCoupleTable().
G4bool G4ProductionCuts::IsModified () const inline
Definition at line 178 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ProductionCuts.hh
References isModified.
Referenced by G4MaterialCutsCouple::IsRecalcNeeded().
G4bool G4ProductionCuts::operator!= (const G4ProductionCuts & right) const
Definition at line 84 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 84 of file G4ProductionCuts.cc
G4ProductionCuts & G4ProductionCuts::operator= (const G4ProductionCuts & right)
Definition at line 65 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 65 of file G4ProductionCuts.cc
References fRangeCuts, isModified, and NumberOfG4CutIndex.
G4bool G4ProductionCuts::operator== (const G4ProductionCuts & right) const
Definition at line 78 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ProductionCuts.cc
void G4ProductionCuts::PhysicsTableUpdated () inline
Definition at line 184 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ProductionCuts.hh
References isModified.
Referenced by G4MaterialCutsCouple::PhysicsTableUpdated().
void G4ProductionCuts::SetProductionCut (G4double cut, G4int index = -1) inline
Definition at line 125 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ProductionCuts.hh
References fRangeCuts, isModified, and NumberOfG4CutIndex.
Referenced by ExTGRCRegionCutsMgr::BuildProductionCuts(), CML2Ph_BoxInBox::Construct(), CML2Ph_FullWater::Construct(), DetectorConstruction::ConstructDetector(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4GDMLParser::ImportRegions(), CML2Acc1::ionizationChamber(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2AccSaturn::Jaw2X(), CML2Acc2::Jaw2Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), CML2AccSaturn::primaryCollimator(), STCyclotronPhysicsList::SetCutFoil(), STCyclotronPhysicsList::SetCutTarget(), G4VUserPhysicsList::SetParticleCuts(), SetProductionCut(), CexmcSetup::SetupSpecialVolumes(), CML2Acc1::target(), CML2Acc2::target(), CML2Acc1::vacuumWindow(), CML2Acc2::vacuumWindow(), and CML2AccSaturn::vacuumWindow().
void G4ProductionCuts::SetProductionCut (G4double cut, G4ParticleDefinition * ptcl) inline
Definition at line 140 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ProductionCuts.hh
References GetIndex(), incremental_prev_tag::idx, and SetProductionCut().
void G4ProductionCuts::SetProductionCut (G4double cut, const G4String & pName) inline
Definition at line 148 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ProductionCuts.hh
References GetIndex(), incremental_prev_tag::idx, and SetProductionCut().
void G4ProductionCuts::SetProductionCuts (std::vector< G4double > & cut)
Definition at line 128 of file G4ProductionCuts.cc.
View newest version in sPHENIX GitHub at line 128 of file G4ProductionCuts.cc
References fRangeCuts, G4cerr, G4endl, G4Exception(), G4ProductionCutsTable::GetProductionCutsTable(), isModified, JustWarning, and NumberOfG4CutIndex.
Referenced by Par01DetectorConstruction::Construct().
Member Data Documentation
G4ThreadLocal G4ParticleDefinition * G4ProductionCuts::electDef = nullptr static private
Definition at line 116 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ProductionCuts.hh
Referenced by GetIndex().
std::vector<G4double> G4ProductionCuts::fRangeCuts protected
Definition at line 111 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ProductionCuts.hh
Referenced by G4ProductionCuts(), GetProductionCut(), GetProductionCuts(), operator=(), SetProductionCut(), SetProductionCuts(), and ~G4ProductionCuts().
G4ThreadLocal G4ParticleDefinition * G4ProductionCuts::gammaDef = nullptr static private
Definition at line 115 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ProductionCuts.hh
Referenced by GetIndex().
G4bool G4ProductionCuts::isModified protected
Definition at line 112 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ProductionCuts.hh
Referenced by IsModified(), operator=(), PhysicsTableUpdated(), SetProductionCut(), and SetProductionCuts().
G4ThreadLocal G4ParticleDefinition * G4ProductionCuts::positDef = nullptr static private
Definition at line 117 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ProductionCuts.hh
Referenced by GetIndex().
G4ThreadLocal G4ParticleDefinition * G4ProductionCuts::protonDef = nullptr static private
Definition at line 119 of file G4ProductionCuts.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ProductionCuts.hh
Referenced by GetIndex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4ProductionCuts.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4ProductionCuts.cc