ECCE @ EIC Software: G4BetaDecayCorrections Class Reference
G4BetaDecayCorrections Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4BetaDecayCorrections.hh>
Public Member Functions
G4BetaDecayCorrections (const G4int Z, const G4int A)
~G4BetaDecayCorrections ()
G4double FermiFunction (const G4double &W)
G4double ShapeFactor (const G4BetaDecayType &, const G4double &p_e, const G4double &e_nu)
Private Member Functions
G4double ModSquared (const G4double &x, const G4double &y)
G4double Gamma (const G4double &arg)
Private Attributes
const G4int Z
const G4int A
G4double alphaZ
G4double Rnuc
G4double V0
G4double gamma0
G4double gc [6]
Detailed Description
Definition at line 36 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 36 of file G4BetaDecayCorrections.hh
Constructor & Destructor Documentation
G4BetaDecayCorrections::G4BetaDecayCorrections (const G4int Z, const G4int A)
Definition at line 32 of file G4BetaDecayCorrections.cc.
View newest version in sPHENIX GitHub at line 32 of file G4BetaDecayCorrections.cc
References A, kdfinder::abs(), alphaZ, source.hepunit::fine_structure_const, gamma0, gc, Rnuc, V0, and Z.
G4BetaDecayCorrections::~G4BetaDecayCorrections () inline
Definition at line 41 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 41 of file G4BetaDecayCorrections.hh
Member Function Documentation
G4double G4BetaDecayCorrections::FermiFunction (const G4double & W)
Definition at line 57 of file G4BetaDecayCorrections.cc.
View newest version in sPHENIX GitHub at line 57 of file G4BetaDecayCorrections.cc
References alphaZ, Acts::VectorHelpers::eta(), Gamma(), gamma0, ModSquared(), pi, Rnuc, V0, and Z.
Referenced by G4BetaMinusDecay::SetUpBetaSpectrumSampler(), and G4BetaPlusDecay::SetUpBetaSpectrumSampler().
G4double G4BetaDecayCorrections::Gamma (const G4double & arg) private
Definition at line 106 of file G4BetaDecayCorrections.cc.
View newest version in sPHENIX GitHub at line 106 of file G4BetaDecayCorrections.cc
References fac, G4endl, G4Exception(), gc, JustWarning, sum, and x.
Referenced by FermiFunction(), and ShapeFactor().
G4double G4BetaDecayCorrections::ModSquared (const G4double & x, const G4double & y) private
Definition at line 89 of file G4BetaDecayCorrections.cc.
View newest version in sPHENIX GitHub at line 89 of file G4BetaDecayCorrections.cc
References pi.
Referenced by FermiFunction(), and ShapeFactor().
G4double G4BetaDecayCorrections::ShapeFactor (const G4BetaDecayType & bdt, const G4double & p_e, const G4double & e_nu)
Definition at line 135 of file G4BetaDecayCorrections.cc.
View newest version in sPHENIX GitHub at line 135 of file G4BetaDecayCorrections.cc
References allowed, alphaZ, c1, c2, Acts::VectorHelpers::eta(), firstForbidden, G4Exception(), Gamma(), gamma0, JustWarning, ModSquared(), Rnuc, secondForbidden, thirdForbidden, uniqueFirstForbidden, uniqueSecondForbidden, uniqueThirdForbidden, and w.
Referenced by G4BetaMinusDecay::SetUpBetaSpectrumSampler(), and G4BetaPlusDecay::SetUpBetaSpectrumSampler().
Member Data Documentation
const G4int G4BetaDecayCorrections::A private
Definition at line 53 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 53 of file G4BetaDecayCorrections.hh
Referenced by G4BetaDecayCorrections().
G4double G4BetaDecayCorrections::alphaZ private
Definition at line 54 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BetaDecayCorrections.hh
Referenced by FermiFunction(), G4BetaDecayCorrections(), and ShapeFactor().
G4double G4BetaDecayCorrections::gamma0 private
Definition at line 57 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 57 of file G4BetaDecayCorrections.hh
Referenced by FermiFunction(), G4BetaDecayCorrections(), and ShapeFactor().
G4double G4BetaDecayCorrections::gc[6] private
Definition at line 59 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BetaDecayCorrections.hh
Referenced by G4BetaDecayCorrections(), and Gamma().
G4double G4BetaDecayCorrections::Rnuc private
Definition at line 55 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 55 of file G4BetaDecayCorrections.hh
Referenced by FermiFunction(), G4BetaDecayCorrections(), and ShapeFactor().
G4double G4BetaDecayCorrections::V0 private
Definition at line 56 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BetaDecayCorrections.hh
Referenced by FermiFunction(), and G4BetaDecayCorrections().
const G4int G4BetaDecayCorrections::Z private
Definition at line 52 of file G4BetaDecayCorrections.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BetaDecayCorrections.hh
Referenced by FermiFunction(), and G4BetaDecayCorrections().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4BetaDecayCorrections.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4BetaDecayCorrections.cc