ECCE @ EIC Software: TSRunAction Class Reference
TSRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/include/TSRunAction.hh>
Public Types
typedef std::tuple< G4double,
G4double, G4double > Compare_t
typedef std::map< G4int,
Compare_t > IDcompare_t
typedef std::map< G4String,
IDcompare_t > TypeCompare_t
Public Member Functions
TSRunAction ()
virtual ~TSRunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
TSDetectorConstruction * fDetector
G4String fName
TypeCompare_t fTypeCompare
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 51 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 51 of file TSRunAction.hh
Member Typedef Documentation
typedef std::tuple<G4double, G4double, G4double> TSRunAction::Compare_t
Definition at line 54 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file TSRunAction.hh
typedef std::map<G4int, Compare_t> TSRunAction::IDcompare_t
Definition at line 55 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TSRunAction.hh
typedef std::map<G4String, IDcompare_t> TSRunAction::TypeCompare_t
Definition at line 56 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file TSRunAction.hh
Constructor & Destructor Documentation
TSRunAction::TSRunAction ()
Definition at line 51 of file TSRunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file TSRunAction.cc
TSRunAction::~TSRunAction () virtual
Definition at line 58 of file TSRunAction.cc.
View newest version in sPHENIX GitHub at line 58 of file TSRunAction.cc
Member Function Documentation
void TSRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 70 of file TSRunAction.cc.
View newest version in sPHENIX GitHub at line 70 of file TSRunAction.cc
References G4PrintEnv(), G4Run::GetNumberOfEventToBeProcessed(), G4RunManager::GetRunManager(), G4UserRunAction::IsMaster(), and G4RunManager::SetPrintProgress().
void TSRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 82 of file TSRunAction.cc.
View newest version in sPHENIX GitHub at line 82 of file TSRunAction.cc
References Acts::units::_s, G4TAtomicHitsMap< T >::begin(), G4VTHitsVector< _Tp, std::deque< _Tp * > >::begin(), G4VTHitsMap< T, Map_t >::begin(), G4TAtomicHitsMap< T >::end(), G4VTHitsVector< _Tp, std::deque< _Tp * > >::end(), G4VTHitsMap< T, Map_t >::end(), CLHEP::eV, fName, test::fname, fTypeCompare, G4cout, G4endl, G4Exception(), TSRun::GetAtomicHitsMap(), TSRun::GetConvMap(), TSRun::GetHitsMap(), G4VTHitsVector< _Tp, std::deque< _Tp * > >::GetIndex(), TSRun::GetMutexHitsMap(), G4Run::GetNumberOfEvent(), G4VTHitsVector< _Tp, std::deque< _Tp * > >::GetObject(), G4VTHitsMap< T, Map_t >::GetObject(), TSRun::GetStatMap(), G4UserRunAction::IsMaster(), JustWarning, CLHEP::keV, print(), second, separator, G4VTHitsVector< _Tp, std::deque< _Tp * > >::size(), G4VTHitsMap< T, Map_t >::size(), G4TAtomicHitsMap< T >::size(), and Acts::IntegrationTest::valid().
G4Run * TSRunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 63 of file TSRunAction.cc.
View newest version in sPHENIX GitHub at line 63 of file TSRunAction.cc
References fName.
Member Data Documentation
TSDetectorConstruction* TSRunAction::fDetector private
Definition at line 68 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file TSRunAction.hh
G4String TSRunAction::fName private
Definition at line 69 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file TSRunAction.hh
Referenced by EndOfRunAction(), and GenerateRun().
TypeCompare_t TSRunAction::fTypeCompare private
Definition at line 70 of file TSRunAction.hh.
View newest version in sPHENIX GitHub at line 70 of file TSRunAction.hh
Referenced by EndOfRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/include/TSRunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/src/TSRunAction.cc