ECCE @ EIC Software: G4RDVEMDataSet Class Reference
G4RDVEMDataSet Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDVEMDataSet.hh>
Public Member Functions
G4RDVEMDataSet ()
virtual ~G4RDVEMDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const =0
virtual void PrintData (void) const =0
virtual const G4RDVEMDataSet * GetComponent (G4int componentId) const =0
virtual void AddComponent (G4RDVEMDataSet *dataSet)=0
virtual size_t NumberOfComponents (void) const =0
virtual const G4DataVector & GetEnergies (G4int componentId) const =0
virtual const G4DataVector & GetData (G4int componentId) const =0
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *data, G4int component=0)=0
virtual G4bool LoadData (const G4String &fileName)=0
virtual G4bool SaveData (const G4String &fileName) const =0
virtual G4double RandomSelect (G4int componentId=0) const =0
Private Member Functions
G4RDVEMDataSet (const G4RDVEMDataSet &copy)
G4RDVEMDataSet & operator= (const G4RDVEMDataSet &right)
Detailed Description
Definition at line 50 of file G4RDVEMDataSet.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RDVEMDataSet.hh
Constructor & Destructor Documentation
G4RDVEMDataSet::G4RDVEMDataSet () inline
Definition at line 53 of file G4RDVEMDataSet.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RDVEMDataSet.hh
virtual G4RDVEMDataSet::~G4RDVEMDataSet () inline virtual
Definition at line 54 of file G4RDVEMDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RDVEMDataSet.hh
G4RDVEMDataSet::G4RDVEMDataSet (const G4RDVEMDataSet & copy) private
Member Function Documentation
virtual void G4RDVEMDataSet::AddComponent (G4RDVEMDataSet * dataSet) pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4LowEnergyIonisation::BuildLossTable(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), and G4RDDopplerProfile::LoadProfile().
virtual G4double G4RDVEMDataSet::FindValue (G4double x, G4int componentId = 0) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDShellVacancy::AverageNOfIonisations(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4RDeIonisationParameters::Excitation(), G4RDCompositeEMDataSet::FindValue(), G4RDVCrossSectionHandler::FindValue(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4LowEnergyIonisation::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4LowEnergyBremsstrahlung::GetMeanFreePath(), G4RDBremsstrahlungParameters::Parameter(), G4RDeIonisationParameters::Parameter(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), and G4RDVCrossSectionHandler::SelectRandomShell().
virtual const G4RDVEMDataSet* G4RDVEMDataSet::GetComponent (G4int componentId) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4RDVCrossSectionHandler::FindValue(), G4LowEnergyIonisation::GetMeanFreePath(), G4LowEnergyBremsstrahlung::GetMeanFreePath(), G4RDeIonisationParameters::Parameter(), G4RDeIonisationParameters::PrintData(), G4RDDopplerProfile::Profile(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), and G4RDVCrossSectionHandler::SelectRandomShell().
virtual const G4DataVector& G4RDVEMDataSet::GetData (G4int componentId) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDCompositeEMDataSet::GetData(), G4RDShellEMDataSet::GetData(), and G4RDShellEMDataSet::SaveData().
virtual const G4DataVector& G4RDVEMDataSet::GetEnergies (G4int componentId) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDeIonisationParameters::Excitation(), G4RDCompositeEMDataSet::GetEnergies(), G4RDShellEMDataSet::GetEnergies(), G4RDeIonisationParameters::Parameter(), G4RDBremsstrahlungParameters::Parameter(), and G4RDShellEMDataSet::SaveData().
virtual G4bool G4RDVEMDataSet::LoadData (const G4String & fileName) pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4LowEnergyCompton::G4LowEnergyCompton(), G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton(), G4LowEnergyRayleigh::G4LowEnergyRayleigh(), G4RDCompositeEMDataSet::LoadData(), and G4RDVCrossSectionHandler::LoadShellData().
virtual size_t G4RDVEMDataSet::NumberOfComponents (void) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4RDVCrossSectionHandler::FindValue(), G4RDVCrossSectionHandler::NumberOfComponents(), G4RDeIonisationParameters::Parameter(), G4RDeIonisationParameters::PrintData(), and G4RDVCrossSectionHandler::SelectRandomShell().
G4RDVEMDataSet& G4RDVEMDataSet::operator= (const G4RDVEMDataSet & right) private
virtual void G4RDVEMDataSet::PrintData (void) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4LowEnergyIonisation::BuildLossTable(), G4LowEnergyIonisation::BuildPhysicsTable(), G4RDDopplerProfile::PrintData(), G4RDCompositeEMDataSet::PrintData(), G4RDShellEMDataSet::PrintData(), G4RDBremsstrahlungParameters::PrintData(), G4RDeIonisationParameters::PrintData(), and G4RDVCrossSectionHandler::PrintData().
virtual G4double G4RDVEMDataSet::RandomSelect (G4int componentId = 0) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDCompositeEMDataSet::RandomSelect(), and G4RDDopplerProfile::RandomSelectMomentum().
virtual G4bool G4RDVEMDataSet::SaveData (const G4String & fileName) const pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDCompositeEMDataSet::SaveData().
virtual void G4RDVEMDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * data, G4int component = 0) pure virtual
Implemented in G4RDEMDataSet, G4RDShellEMDataSet, and G4RDCompositeEMDataSet.
Referenced by G4RDCompositeEMDataSet::SetEnergiesData(), and G4RDShellEMDataSet::SetEnergiesData().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDVEMDataSet.hh