ECCE @ EIC Software: RE01PrimaryGeneratorAction Class Reference
RE01PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01PrimaryGeneratorAction.hh>
Public Member Functions
RE01PrimaryGeneratorAction ()
virtual ~RE01PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
void SetHEPEvtGenerator (G4bool f)
G4bool GetHEPEvtGenerator ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4VPrimaryGenerator * fHEPEvt
G4VPrimaryGenerator * fParticleGun
RE01PrimaryGeneratorMessenger * fMessenger
G4bool fUseHEPEvt
Detailed Description
Definition at line 41 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 41 of file RE01PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction ()
Definition at line 42 of file RE01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 42 of file RE01PrimaryGeneratorAction.cc
References cm, fHEPEvt, INPUTHEPMC::filename, G4ParticleTable::FindParticle(), fMessenger, fParticleGun, fUseHEPEvt, G4ParticleTable::GetParticleTable(), GeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
RE01PrimaryGeneratorAction::~RE01PrimaryGeneratorAction () virtual
Definition at line 73 of file RE01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 73 of file RE01PrimaryGeneratorAction.cc
References fHEPEvt, fMessenger, and fParticleGun.
Member Function Documentation
void RE01PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 82 of file RE01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 82 of file RE01PrimaryGeneratorAction.cc
References fHEPEvt, fParticleGun, fUseHEPEvt, G4Exception(), G4VPrimaryGenerator::GeneratePrimaryVertex(), G4Event::GetNumberOfPrimaryVertex(), and RunMustBeAborted.
G4bool RE01PrimaryGeneratorAction::GetHEPEvtGenerator () inline
Definition at line 51 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 51 of file RE01PrimaryGeneratorAction.hh
References fUseHEPEvt.
Referenced by RE01PrimaryGeneratorMessenger::GetCurrentValue().
void RE01PrimaryGeneratorAction::SetHEPEvtGenerator (G4bool f) inline
Definition at line 49 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 49 of file RE01PrimaryGeneratorAction.hh
References f, and fUseHEPEvt.
Member Data Documentation
G4VPrimaryGenerator* RE01PrimaryGeneratorAction::fHEPEvt private
Definition at line 55 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file RE01PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), RE01PrimaryGeneratorAction(), and ~RE01PrimaryGeneratorAction().
RE01PrimaryGeneratorMessenger* RE01PrimaryGeneratorAction::fMessenger private
Definition at line 57 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file RE01PrimaryGeneratorAction.hh
Referenced by RE01PrimaryGeneratorAction(), and ~RE01PrimaryGeneratorAction().
G4VPrimaryGenerator* RE01PrimaryGeneratorAction::fParticleGun private
Definition at line 56 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file RE01PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), RE01PrimaryGeneratorAction(), and ~RE01PrimaryGeneratorAction().
G4bool RE01PrimaryGeneratorAction::fUseHEPEvt private
Definition at line 58 of file RE01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file RE01PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetHEPEvtGenerator(), RE01PrimaryGeneratorAction(), and SetHEPEvtGenerator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01PrimaryGeneratorAction.cc