ECCE @ EIC Software: G4Trap Class Reference
G4Trap Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Trap.hh>
Public Member Functions
G4Trap (const G4String &pName, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
G4Trap (const G4String &pName, const G4ThreeVector pt[8])
G4Trap (const G4String &pName, G4double pZ, G4double pY, G4double pX, G4double pLTX)
G4Trap (const G4String &pName, G4double pDx1, G4double pDx2, G4double pDy1, G4double pDy2, G4double pDz)
G4Trap (const G4String &pName, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
G4Trap (const G4String &pName)
virtual ~G4Trap ()
G4double GetZHalfLength () const
G4double GetYHalfLength1 () const
G4double GetXHalfLength1 () const
G4double GetXHalfLength2 () const
G4double GetTanAlpha1 () const
G4double GetYHalfLength2 () const
G4double GetXHalfLength3 () const
G4double GetXHalfLength4 () const
G4double GetTanAlpha2 () const
TrapSidePlane GetSidePlane (G4int n) const
G4ThreeVector GetSymAxis () const
void SetAllParameters (G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Trap (__void__ &)
G4Trap (const G4Trap &rhs)
G4Trap & operator= (const G4Trap &rhs)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Member Functions
void MakePlanes ()
void MakePlanes (const G4ThreeVector pt[8])
G4bool MakePlane (const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3, const G4ThreeVector &p4, TrapSidePlane &plane)
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Private Member Functions
void CheckParameters ()
void GetVertices (G4ThreeVector pt[8]) const
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double halfCarTolerance
G4double fDz
G4double fTthetaCphi
G4double fTthetaSphi
G4double fDy1
G4double fDx1
G4double fDx2
G4double fTalpha1
G4double fDy2
G4double fDx3
G4double fDx4
G4double fTalpha2
TrapSidePlane fPlanes [4]
G4int fTrapType
Additional Inherited Members
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 109 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 109 of file G4Trap.hh
Constructor & Destructor Documentation
G4Trap::G4Trap (const G4String & pName, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
Definition at line 60 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 60 of file G4Trap.cc
References CheckParameters(), fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, and MakePlanes().
Referenced by Clone().
G4Trap::G4Trap (const G4String & pName, const G4ThreeVector pt[8])
Definition at line 86 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 86 of file G4Trap.cc
References CheckParameters(), FatalException, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, MakePlanes(), message(), x, y, and z.
G4Trap::G4Trap (const G4String & pName, G4double pZ, G4double pY, G4double pX, G4double pLTX)
Definition at line 145 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 145 of file G4Trap.cc
References CheckParameters(), fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, and MakePlanes().
G4Trap::G4Trap (const G4String & pName, G4double pDx1, G4double pDx2, G4double pDy1, G4double pDy2, G4double pDz)
Definition at line 163 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 163 of file G4Trap.cc
References CheckParameters(), fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, and MakePlanes().
G4Trap::G4Trap (const G4String & pName, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Definition at line 181 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 181 of file G4Trap.cc
References CheckParameters(), fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, and MakePlanes().
G4Trap::G4Trap (const G4String & pName)
Definition at line 205 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 205 of file G4Trap.cc
References MakePlanes().
G4Trap::~G4Trap () virtual
Definition at line 232 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 232 of file G4Trap.cc
G4Trap::G4Trap (__void__ & a)
Definition at line 219 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 219 of file G4Trap.cc
References MakePlanes().
G4Trap::G4Trap (const G4Trap & rhs)
Definition at line 240 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 240 of file G4Trap.cc
References fPlanes, and fTrapType.
Member Function Documentation
G4ThreeVector G4Trap::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 785 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 785 of file G4Trap.cc
References a, TrapSidePlane::a, kdfinder::abs(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, d, DBL_MAX, fDz, fPlanes, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4Trap::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 519 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 519 of file G4Trap.cc
References G4VSolid::DumpInfo(), dz, G4Exception(), G4VSolid::GetName(), GetVertices(), GetZHalfLength(), JustWarning, kInfinity, message(), pMax, pt, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), x, xmax, xmin, CLHEP::Hep3Vector::y(), y, ymax, ymin, and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Trap::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 559 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 559 of file G4Trap.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), GetVertices(), pMax, and pt.
void G4Trap::CheckParameters () private
Definition at line 313 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 313 of file G4Trap.cc
References FatalException, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, G4Exception(), G4VSolid::GetName(), and message().
Referenced by G4Trap(), and SetAllParameters().
G4VSolid * G4Trap::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 1098 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1098 of file G4Trap.cc
References G4Trap().
void G4Trap::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 508 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 508 of file G4Trap.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Trap::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1217 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1217 of file G4Trap.cc
References fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, phi, and theta().
void G4Trap::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 1212 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1212 of file G4Trap.cc
References G4VGraphicsScene::AddSolid().
G4double G4Trap::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 809 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 809 of file G4Trap.cc
References TrapSidePlane::a, kdfinder::abs(), TrapSidePlane::b, TrapSidePlane::c, TrapSidePlane::d, DBL_MAX, dz, fDz, fPlanes, halfCarTolerance, kInfinity, max, min, tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Trap::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 878 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 878 of file G4Trap.cc
References TrapSidePlane::a, kdfinder::abs(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, d, dx, dy, dz, fDz, fPlanes, fTrapType, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Trap::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 935 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 935 of file G4Trap.cc
References a, TrapSidePlane::a, kdfinder::abs(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, DBL_MAX, fDz, fPlanes, halfCarTolerance, CLHEP::Hep3Vector::set(), tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Trap::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1018 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1018 of file G4Trap.cc
References TrapSidePlane::a, kdfinder::abs(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, d, G4VSolid::DumpInfo(), dx, dy, dz, fDz, fPlanes, fTrapType, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), Inside(), JustWarning, kOutside, max, message(), mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Trap::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 458 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 458 of file G4Trap.cc
References dz, G4CSGSolid::fCubicVolume, GetVertices(), pt, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4GeometryType G4Trap::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 1089 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1089 of file G4Trap.cc
G4ThreeVector G4Trap::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1161 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1161 of file G4Trap.cc
References G4UniformRand, GetVertices(), k, CLHEP::Hep3Vector::mag(), pt, G4GeomTools::QuadAreaNormal(), s1, G4GeomTools::TriangleAreaNormal(), Acts::UnitConstants::u, and v.
TrapSidePlane G4Trap::GetSidePlane (G4int n) const inline
Referenced by export_G4Trap().
G4double G4Trap::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 483 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 483 of file G4Trap.cc
References G4CSGSolid::fSurfaceArea, GetVertices(), CLHEP::Hep3Vector::mag(), pt, and G4GeomTools::QuadAreaNormal().
G4ThreeVector G4Trap::GetSymAxis () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetTanAlpha1 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetTanAlpha2 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
void G4Trap::GetVertices (G4ThreeVector pt[8]) const private
Definition at line 1143 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1143 of file G4Trap.cc
References a, b, TrapSidePlane::b, TrapSidePlane::c, TrapSidePlane::d, fDz, fPlanes, CLHEP::Hep3Vector::set(), x, y, and z.
Referenced by BoundingLimits(), CalculateExtent(), GetCubicVolume(), GetPointOnSurface(), and GetSurfaceArea().
G4double G4Trap::GetXHalfLength1 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetXHalfLength2 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetXHalfLength3 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetXHalfLength4 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetYHalfLength1 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetYHalfLength2 () const inline
Referenced by export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
G4double G4Trap::GetZHalfLength () const inline
Referenced by BoundingLimits(), export_G4Trap(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteSolids::TrapWrite(), and G4GDMLWriteSolids::TrapWrite().
EInside G4Trap::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 608 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 608 of file G4Trap.cc
References TrapSidePlane::a, kdfinder::abs(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, d, dx, dy, dz, fDz, fPlanes, fTrapType, halfCarTolerance, kInside, kOutside, kSurface, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToOut().
G4bool G4Trap::MakePlane (const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3, const G4ThreeVector & p4, TrapSidePlane & plane) protected
Definition at line 426 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 426 of file G4Trap.cc
References TrapSidePlane::a, kdfinder::abs(), TrapSidePlane::b, TrapSidePlane::c, Acts::VectorHelpers::cross(), TrapSidePlane::d, d1, d2, DBL_EPSILON, CLHEP::Hep3Vector::dot(), G4VSolid::kCarTolerance, max, CLHEP::normal(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by MakePlanes().
void G4Trap::MakePlanes () protected
Definition at line 333 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 333 of file G4Trap.cc
References fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, and pt.
Referenced by G4Trap(), and SetAllParameters().
void G4Trap::MakePlanes (const G4ThreeVector pt[8]) protected
Definition at line 359 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 359 of file G4Trap.cc
References a, TrapSidePlane::a, kdfinder::abs(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, DBL_EPSILON, CLHEP::Hep3Vector::dot(), FatalException, fPlanes, fTrapType, G4Exception(), G4VSolid::GetName(), k, MakePlane(), message(), mm, CLHEP::normal(), and StreamInfo().
G4Trap & G4Trap::operator= (const G4Trap & rhs)
Definition at line 254 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 254 of file G4Trap.cc
References fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fPlanes, fTalpha1, fTalpha2, fTrapType, fTthetaCphi, fTthetaSphi, halfCarTolerance, and G4CSGSolid::operator=().
void G4Trap::SetAllParameters (G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
Definition at line 280 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 280 of file G4Trap.cc
References CheckParameters(), G4CSGSolid::fCubicVolume, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, G4CSGSolid::fRebuildPolyhedron, G4CSGSolid::fSurfaceArea, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, and MakePlanes().
Referenced by G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationTrdX::ComputeDimensions(), and export_G4Trap().
std::ostream & G4Trap::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 1107 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 1107 of file G4Trap.cc
References degree, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fTalpha1, fTalpha2, fTthetaCphi, fTthetaSphi, G4VSolid::GetName(), mm, phi, and theta().
Referenced by MakePlanes().
G4ThreeVector G4Trap::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 670 of file G4Trap.cc.
View newest version in sPHENIX GitHub at line 670 of file G4Trap.cc
References a, TrapSidePlane::a, kdfinder::abs(), ApproxSurfaceNormal(), b, TrapSidePlane::b, TrapSidePlane::c, c, TrapSidePlane::d, d, G4VSolid::DumpInfo(), dx, dy, dz, fDz, fPlanes, fTrapType, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), halfCarTolerance, JustWarning, message(), mm, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Trap::fDx1 private
Definition at line 272 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 272 of file G4Trap.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fDx2 private
Definition at line 272 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 272 of file G4Trap.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fDx3 private
Definition at line 273 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 273 of file G4Trap.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fDx4 private
Definition at line 273 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 273 of file G4Trap.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fDy1 private
Definition at line 272 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 272 of file G4Trap.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fDy2 private
Definition at line 273 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 273 of file G4Trap.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fDz private
Definition at line 271 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 271 of file G4Trap.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Trap(), GetVertices(), Inside(), MakePlanes(), operator=(), SetAllParameters(), StreamInfo(), and SurfaceNormal().
TrapSidePlane G4Trap::fPlanes[4] private
Definition at line 274 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 274 of file G4Trap.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4Trap(), GetVertices(), Inside(), MakePlanes(), operator=(), and SurfaceNormal().
G4double G4Trap::fTalpha1 private
Definition at line 272 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 272 of file G4Trap.hh
Referenced by CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fTalpha2 private
Definition at line 273 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 273 of file G4Trap.hh
Referenced by CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4int G4Trap::fTrapType private
Definition at line 275 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 275 of file G4Trap.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Trap(), Inside(), MakePlanes(), operator=(), and SurfaceNormal().
G4double G4Trap::fTthetaCphi private
Definition at line 271 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 271 of file G4Trap.hh
Referenced by CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::fTthetaSphi private
Definition at line 271 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 271 of file G4Trap.hh
Referenced by CreatePolyhedron(), G4Trap(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Trap::halfCarTolerance private
Definition at line 270 of file G4Trap.hh.
View newest version in sPHENIX GitHub at line 270 of file G4Trap.hh
Referenced by DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Trap.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4Trap.cc