ECCE @ EIC Software: G4INCL::INCL::RecoilFunctor Class Reference
G4INCL::INCL::RecoilFunctor Class Reference
Class to adjust remnant recoil.
Public Member Functions
RecoilFunctor (Nucleus *const n, const EventInfo &ei)
Prepare for calling the () operator and scaleParticleEnergies.
virtual ~RecoilFunctor ()
G4double operator() (const G4double x) const
Compute the energy-conservation violation.
void cleanUp (const G4bool success) const
Clean up after root finding.
Public Member Functions inherited from G4INCL::RootFunctor
virtual ~RootFunctor ()
Public Member Functions inherited from G4INCL::IFunction1D
IFunction1D ()
IFunction1D (const G4double x0, const G4double x1)
virtual ~IFunction1D ()
virtual G4double getXMinimum () const
Return the minimum allowed value of the independent variable.
virtual G4double getXMaximum () const
Return the maximum allowed value of the independent variable.
virtual G4double integrate (const G4double x0, const G4double x1, const G4double step=-1.) const
Integrate the function between two values.
IFunction1D * primitive () const
Return a pointer to the (numerical) primitive to this function.
InterpolationTable * inverseCDFTable (ManipulatorFunc fWrap=0, const G4int nNodes=60) const
Return a pointer to the inverse of the CDF of this function.
Private Member Functions
void scaleParticleEnergies (const G4double rescale) const
Scale the kinetic energies of the outgoing particles.
Private Attributes
Nucleus * nucleus
Pointer to the nucleus.
ParticleList outgoingParticles
List of final-state particles.
EventInfo const & theEventInfo
std::list< ThreeVector > particleMomenta
Initial momenta of the outgoing particles.
std::list< G4double > particleKineticEnergies
Initial kinetic energies of the outgoing particles.
Additional Inherited Members
Public Types inherited from G4INCL::IFunction1D
typedef G4double(*const ManipulatorFunc)(const G4double)
Typedef to simplify the syntax of inverseCDFTable.
Protected Member Functions inherited from G4INCL::RootFunctor
RootFunctor (const G4double x0, const G4double x1)
Protected Attributes inherited from G4INCL::IFunction1D
G4double xMin
Minimum value of the independent variable.
G4double xMax
Maximum value of the independent variable.
Detailed Description
Class to adjust remnant recoil.
Definition at line 107 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 107 of file G4INCLCascade.hh
Constructor & Destructor Documentation
G4INCL::INCL::RecoilFunctor::RecoilFunctor (Nucleus *const n, const EventInfo & ei) inline
Prepare for calling the () operator and scaleParticleEnergies.
The constructor sets the private class members.
Definition at line 113 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 113 of file G4INCLCascade.hh
References e, G4INCL::Particle::getA(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMomentum(), G4INCL::Nucleus::getProjectileRemnant(), outgoingParticles, particleKineticEnergies, and particleMomenta.
virtual G4INCL::INCL::RecoilFunctor::~RecoilFunctor () inline virtual
Definition at line 129 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 129 of file G4INCLCascade.hh
Member Function Documentation
void G4INCL::INCL::RecoilFunctor::cleanUp (const G4bool success) const inline virtual
Clean up after root finding.
Implements G4INCL::RootFunctor.
Definition at line 142 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 142 of file G4INCLCascade.hh
References scaleParticleEnergies().
G4double G4INCL::INCL::RecoilFunctor::operator() (const G4double x) const inline virtual
Compute the energy-conservation violation.
Parameters
x scale factor for the particle energies
Returns
the energy-conservation violation
Implements G4INCL::IFunction1D.
Definition at line 136 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 136 of file G4INCLCascade.hh
References G4INCL::Nucleus::ConservationBalance::energy, G4INCL::Nucleus::getConservationBalance(), nucleus, scaleParticleEnergies(), and theEventInfo.
void G4INCL::INCL::RecoilFunctor::scaleParticleEnergies (const G4double rescale) const inline private
Scale the kinetic energies of the outgoing particles.
Parameters
rescale scale factor
Definition at line 163 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 163 of file G4INCLCascade.hh
References e, G4INCL::Particle::getA(), G4INCL::Nucleus::getExcitationEnergy(), G4INCL::Nucleus::getIncomingMomentum(), G4INCL::Particle::getS(), G4INCL::ParticleTable::getTableMass, G4INCL::Particle::getZ(), G4INCL::ThreeVector::mag2(), mass, nucleus, outgoingParticles, particleKineticEnergies, particleMomenta, G4INCL::Particle::setEnergy(), and G4INCL::Particle::setMomentum().
Referenced by cleanUp(), and operator()().
Member Data Documentation
Nucleus* G4INCL::INCL::RecoilFunctor::nucleus private
Pointer to the nucleus.
Definition at line 149 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 149 of file G4INCLCascade.hh
Referenced by operator()(), and scaleParticleEnergies().
ParticleList G4INCL::INCL::RecoilFunctor::outgoingParticles private
List of final-state particles.
Definition at line 151 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 151 of file G4INCLCascade.hh
Referenced by RecoilFunctor(), and scaleParticleEnergies().
std::list<G4double> G4INCL::INCL::RecoilFunctor::particleKineticEnergies private
Initial kinetic energies of the outgoing particles.
Definition at line 157 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 157 of file G4INCLCascade.hh
Referenced by RecoilFunctor(), and scaleParticleEnergies().
std::list<ThreeVector> G4INCL::INCL::RecoilFunctor::particleMomenta private
Initial momenta of the outgoing particles.
Definition at line 155 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 155 of file G4INCLCascade.hh
Referenced by RecoilFunctor(), and scaleParticleEnergies().
EventInfo const& G4INCL::INCL::RecoilFunctor::theEventInfo private
Definition at line 153 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 153 of file G4INCLCascade.hh
Referenced by operator()().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCascade.hh