ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/processes/pymodG4processes.cc File Reference
pymodG4processes.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4ProcessManager ()
void export_G4ProcessTable ()
void export_G4VProcess ()
void export_G4ProcVector ()
void export_G4ProcessType ()
void export_G4EmCalculator ()
void export_G4ProductionCutsTable ()
void export_G4VCrossSectionHandler ()
void export_G4CrossSectionHandler ()
BOOST_PYTHON_MODULE (G4processes)
Function Documentation
BOOST_PYTHON_MODULE (G4processes)
Definition at line 48 of file pymodG4processes.cc.
View newest version in sPHENIX GitHub at line 48 of file pymodG4processes.cc
References export_G4CrossSectionHandler(), export_G4EmCalculator(), export_G4ProcessManager(), export_G4ProcessTable(), export_G4ProcessType(), export_G4ProcVector(), export_G4ProductionCutsTable(), export_G4VCrossSectionHandler(), and export_G4VProcess().
void export_G4CrossSectionHandler ()
Definition at line 39 of file pyG4CrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4CrossSectionHandler.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4EmCalculator ()
Definition at line 213 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 213 of file pyG4EmCalculator.cc
References pyG4EmCalculator::f1_ComputeElectronicDEDX, pyG4EmCalculator::f1_ComputeEnergyCutFromRangeCut, pyG4EmCalculator::f1_ComputeMeanFreePath, pyG4EmCalculator::f1_ComputeNuclearDEDX, pyG4EmCalculator::f1_GetCrossSectionPerVolume, pyG4EmCalculator::f1_GetDEDX, pyG4EmCalculator::f1_GetKinEnergy, pyG4EmCalculator::f1_GetRange, pyG4EmCalculator::f2_ComputeCrossSectionPerAtom, pyG4EmCalculator::f2_ComputeCrossSectionPerVolume, pyG4EmCalculator::f2_ComputeDEDX, pyG4EmCalculator::f2_ComputeElectronicDEDX, pyG4EmCalculator::f2_ComputeEnergyCutFromRangeCut, pyG4EmCalculator::f2_ComputeMeanFreePath, pyG4EmCalculator::f2_ComputeNuclearDEDX, pyG4EmCalculator::f2_ComputeTotalDEDX, pyG4EmCalculator::f2_GetCrossSectionPerVolume, pyG4EmCalculator::f2_GetDEDX, pyG4EmCalculator::f2_GetKinEnergy, pyG4EmCalculator::f2_GetMeanFreePath, G4EmCalculator::FindCouple(), G4EmCalculator::FindMaterial(), G4EmCalculator::FindParticle(), G4EmCalculator::FindRegion(), G4EmCalculator::PrintDEDXTable(), G4EmCalculator::PrintInverseRangeTable(), G4EmCalculator::PrintRangeTable(), and G4EmCalculator::SetVerbose().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ProcessManager ()
Definition at line 170 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 170 of file pyG4ProcessManager.cc
References G4ProcessManager::AddContinuousProcess(), G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4ProcessManager::AddRestProcess(), G4ProcessManager::DumpInfo(), pyG4ProcessManager::f1_GetProcessActivation, pyG4ProcessManager::f1_SetProcessActivation, pyG4ProcessManager::f2_GetProcessActivation, pyG4ProcessManager::f2_RemoveProcess, pyG4ProcessManager::f2_SetProcessActivation, pyG4ProcessManager::f_GetProcessList(), pyG4ProcessManager::f_GetProcessVector(), G4ProcessManager::GetAlongStepIndex(), G4ProcessManager::GetAtRestIndex(), G4ProcessManager::GetParticleType(), G4ProcessManager::GetPostStepIndex(), G4ProcessManager::GetProcessIndex(), G4ProcessManager::GetProcessListLength(), G4ProcessManager::GetProcessOrdering(), G4ProcessManager::GetProcessVectorIndex(), G4ProcessManager::GetVerboseLevel(), idxAll, idxAlongStep, idxAtRest, idxPostStep, ordDefault, ordInActive, ordLast, G4ProcessManager::SetParticleType(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToFirst(), G4ProcessManager::SetProcessOrderingToLast(), G4ProcessManager::SetVerboseLevel(), and typeDoIt.
Referenced by BOOST_PYTHON_MODULE().
void export_G4ProcessTable ()
Definition at line 144 of file pyG4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 144 of file pyG4ProcessTable.cc
References G4ProcessTable::DumpInfo(), pyG4ProcessTable::f1_FindProcess, pyG4ProcessTable::f1_FindProcesses(), pyG4ProcessManager::f1_SetProcessActivation, pyG4ProcessTable::f2_FindProcess, pyG4ProcessTable::f2_FindProcesses(), pyG4ProcessManager::f2_SetProcessActivation, pyG4ProcessTable::f3_FindProcess, pyG4ProcessTable::f3_FindProcesses(), pyG4ProcessTable::f3_SetProcessActivation, pyG4ProcessTable::f4_FindProcesses(), pyG4ProcessTable::f4_SetProcessActivation, pyG4ProcessTable::f5_SetProcessActivation, pyG4ProcessTable::f6_SetProcessActivation, pyG4ProcessTable::f7_SetProcessActivation, pyG4ProcessTable::f8_SetProcessActivation, G4ProcessTable::GetNameList(), G4ProcessTable::GetProcessTable(), G4ProcessTable::GetVerboseLevel(), G4ProcessTable::Length(), and G4ProcessTable::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ProcessType ()
Definition at line 39 of file pyG4ProcessType.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4ProcessType.cc
References fDecay, fElectromagnetic, fGeneral, fHadronic, fNotDefined, fOptical, fParameterisation, fPhotolepton_hadron, fTransportation, and fUserDefined.
Referenced by BOOST_PYTHON_MODULE().
void export_G4ProcVector ()
Definition at line 48 of file pyG4ProcVector.cc.
View newest version in sPHENIX GitHub at line 48 of file pyG4ProcVector.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4ProductionCutsTable ()
Definition at line 41 of file pyG4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4ProductionCutsTable.cc
References G4ProductionCutsTable::ConvertRangeToEnergy(), G4ProductionCutsTable::DumpCouples(), G4ProductionCutsTable::GetHighEdgeEnergy(), G4ProductionCutsTable::GetLowEdgeEnergy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetVerboseLevel(), G4ProductionCutsTable::IsModified(), G4ProductionCutsTable::SetEnergyRange(), and G4ProductionCutsTable::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VCrossSectionHandler ()
Definition at line 60 of file pyG4VCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 60 of file pyG4VCrossSectionHandler.cc
References G4VCrossSectionHandler::Clear(), pyG4VCrossSectionHandler::f1_FindValue, pyG4VCrossSectionHandler::f2_FindValue, G4VCrossSectionHandler::Initialise(), G4VCrossSectionHandler::LoadData(), G4VCrossSectionHandler::LoadShellData(), G4VCrossSectionHandler::PrintData(), G4VCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomShell(), and G4VCrossSectionHandler::ValueForMaterial().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VProcess ()
Definition at line 50 of file pyG4VProcess.cc.
View newest version in sPHENIX GitHub at line 50 of file pyG4VProcess.cc
References G4VProcess::BuildPhysicsTable(), G4VProcess::DumpInfo(), G4VProcess::GetPhysicsTableFileName(), G4VProcess::GetPILfactor(), G4VProcess::GetProcessName(), G4VProcess::GetProcessType(), G4VProcess::GetVerboseLevel(), G4VProcess::IsApplicable(), G4VProcess::PreparePhysicsTable(), G4VProcess::RetrievePhysicsTable(), G4VProcess::SetPILfactor(), G4VProcess::SetVerboseLevel(), and G4VProcess::StorePhysicsTable().
Referenced by BOOST_PYTHON_MODULE().