ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/management/include/templates.hh File Reference
templates.hh File Reference
#include <limits>
#include <climits>
Macros
#define HIGH_PRECISION 1
#define DBL_MIN std::numeric_limits<double>::min()
#define DBL_DIG std::numeric_limits<double>::digits10
#define DBL_MAX std::numeric_limits<double>::max()
#define DBL_EPSILON std::numeric_limits<double>::epsilon()
#define FLT_MIN std::numeric_limits<float>::min()
#define FLT_DIG std::numeric_limits<float>::digits10
#define FLT_MAX std::numeric_limits<float>::max()
#define FLT_EPSILON std::numeric_limits<float>::epsilon()
#define MAXFLOAT std::numeric_limits<float>::max()
#define INT_MAX std::numeric_limits<int>::max()
#define INT_MIN std::numeric_limits<int>::min()
#define LOG_EKIN_MIN -30
#define G4_SQR_DEFINED
Typedefs
typedef double Float
Functions
template<class T >
void G4SwapPtr (T *&a, T *&b)
template<class T >
void G4SwapObj (T *a, T *b)
template<class T >
T sqr (const T &x)
int G4lrint (double ad)
int G4lint (double ad)
int G4rint (double ad)
template<typename... _Args>
void G4ConsumeParameters (_Args &&...)
Macro Definition Documentation
#define DBL_DIG std::numeric_limits<double>::digits10
Definition at line 78 of file templates.hh.
View newest version in sPHENIX GitHub at line 78 of file templates.hh
#define DBL_EPSILON std::numeric_limits<double>::epsilon()
Definition at line 86 of file templates.hh.
View newest version in sPHENIX GitHub at line 86 of file templates.hh
Referenced by G4EllipticalTube::CheckParameters(), G4Polyhedra::Create(), G4ErrorMatrix::dfact_matrix(), G4Hype::DistanceToIn(), G4Ellipsoid::DistanceToOut(), G4ITStepProcessor::ExtractILData(), G4Polyhedra::G4Polyhedra(), G4TriangularFacet::Intersect(), G4TessellatedGeometryAlgorithms::IntersectLineAndLineSegment2D(), G4ErrorSymMatrix::invertBunchKaufman(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4Trap::MakePlane(), G4Trap::MakePlanes(), nf_GnG_adaptiveQuadrature(), nf_incompleteGammaFunction(), nf_incompleteGammaFunctionComplementary(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), ptwX_close(), ptwXY_applyFunction2(), ptwXY_createFromFunction(), ptwXY_createFromFunctionBisect(), ptwXY_div_s_ptwXY(), ptwXY_fromUnitbase(), ptwXY_mergeClosePoints(), ptwXY_mul2_s_ptwXY(), ptwXY_tweakDomainsToMutualify(), ptwXY_union(), and G4SampleResonance::SampleMass().
#define DBL_MAX std::numeric_limits<double>::max()
Definition at line 82 of file templates.hh.
View newest version in sPHENIX GitHub at line 82 of file templates.hh
Referenced by G4CollisionManager::AddCollision(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4CoupledTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepDoIt(), G4NuclearStopping::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4ScoreSplittingProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::AlongStepGetPhysicalInteractionLength(), G4ExtrudedSolid::ApproxSurfaceNormal(), G4Tet::ApproxSurfaceNormal(), G4Trd::ApproxSurfaceNormal(), G4Para::ApproxSurfaceNormal(), G4Trap::ApproxSurfaceNormal(), G4ScoreSplittingProcess::AtRestGetPhysicalInteractionLength(), G4ParallelWorldProcess::AtRestGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AtRestGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::AtRestGetPhysicalInteractionLength(), RunAction::BeginOfRunAction(), G4hImpactIonisation::BuildLambdaTable(), G4BinaryCascade::BuildLateParticleCollisions(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VLEPTSModel::BuildMeanFreePathTable(), StepMax::BuildPhysicsTable(), G4VLEPTSModel::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4IonParametrisedLossModel::BuildRangeVector(), G4QGSMSplitableHadron::BuildSeaQuark(), DicomFileCT::BuildStructureIDs(), G4ITModelProcessor::CalculateMinTimeStep(), G4DNAMoleculeEncounterStepper::CalculateStep(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ITStepProcessor::CleanProcessor(), G4ParticleHPVector::CleanUp(), PDBlib::ComputeBoundingVolumeParams(), G4BetheBlochNoDeltaModel::ComputeDEDXPerVolume(), G4BraggNoDeltaModel::ComputeDEDXPerVolume(), G4ICRU73NoDeltaModel::ComputeDEDXPerVolume(), G4DNABrownianTransportation::ComputeGeomLimit(), G4WentzelVIModel::ComputeGeomPathLength(), G4ITStepProcessor::ComputeInteractionLength(), G4SandiaTable::ComputeMatSandiaMatrix(), G4GammaConversionToMuons::ComputeMeanFreePath(), G4EmCalculator::ComputeMeanFreePath(), G4VEmModel::ComputeMeanFreePath(), G4Material::ComputeNuclearInterLength(), G4Material::ComputeRadiationLength(), G4PathFinder::ComputeSafety(), G4ErrorPropagationNavigator::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4DNABrownianTransportation::ComputeStep(), G4DummyModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTrueStepLength(), ExUCNDetectorConstruction::Construct(), F06DetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), WLSDetectorConstruction::ConstructFiber(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4IonParametrisedLossModel::CorrectionsAlongStep(), G4DNASecondOrderReaction::Create(), G4Scheduler::Create(), G4LEPTSElasticModel::CrossSectionPerVolume(), G4DNAIonElasticModel::CrossSectionPerVolume(), G4MicroElecElasticModel::CrossSectionPerVolume(), G4DNATransformElectronModel::CrossSectionPerVolume(), G4DNAPTBElasticModel::CrossSectionPerVolume(), G4TDNAOneStepThermalizationModel< MODEL >::CrossSectionPerVolume(), G4BFieldIntegrationDriver::CurvatureRadius(), G4DNAMolecularDissociation::DecayIt(), G4VEmProcess::DefineMaterial(), G4VEnergyLossProcess::DefineMaterial(), G4SteppingManager::DefinePhysicalStepLength(), DetectorConstruction::DefineVolumes(), BiasingOperation::DistanceToApplyOperation(), G4BOptnChangeCrossSection::DistanceToApplyOperation(), GB03BOptnSplitOrKillOnBoundary::DistanceToApplyOperation(), GB06BOptnSplitAndKillByImportance::DistanceToApplyOperation(), G4BOptnForceFreeFlight::DistanceToApplyOperation(), GB04BOptnBremSplitting::DistanceToApplyOperation(), G4BOptnForceCommonTruncatedExp::DistanceToApplyOperation(), G4EllipticalTube::DistanceToIn(), G4Box::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Tet::DistanceToIn(), G4ExtrudedSolid::DistanceToIn(), G4Trd::DistanceToIn(), G4Para::DistanceToIn(), G4Trap::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Tet::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Trd::DistanceToOut(), G4Para::DistanceToOut(), G4Trap::DistanceToOut(), DMXDetectorConstruction::DMXDetectorConstruction(), G4ITStepProcessor::DoDefinePhysicalStepLength(), G4PathFinder::DoNextCurvedStep(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), Run::EndOfRun(), HistoManager::EndOfRun(), G4GMocrenFileSceneHandler::EndSavingGdd(), F04ElementField::F04ElementField(), F04PhysicsList::F04PhysicsList(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4ScoreQuantityMessenger::FilterCommands(), G4Absorber::FindAbsorbers(), G4MesonAbsorption::FindAndFillCluster(), G4VEmProcess::FindLambdaMax(), RE06Run::FindMinimum(), G4ITStepProcessor::FindTransportationStep(), G4eeToHadronsMultiModel::G4eeToHadronsMultiModel(), G4EmCalculator::G4EmCalculator(), G4GammaConversionToMuons::G4GammaConversionToMuons(), G4ITModelProcessor::G4ITModelProcessor(), G4ITStepProcessor::G4ITStepProcessor(), G4LFission::G4LFission(), G4NeutronKiller::G4NeutronKiller(), G4ParticleHPContAngularPar::G4ParticleHPContAngularPar(), G4ParticleHPVector::G4ParticleHPVector(), G4PreCompoundModel::G4PreCompoundModel(), G4SteppingManager::G4SteppingManager(), G4UniversalFluctuation::G4UniversalFluctuation(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMscModel::G4VMscModel(), G4VXTRenergyLoss::G4VXTRenergyLoss(), G4WentzelOKandVIxSection::G4WentzelOKandVIxSection(), G4XAnnihilationChannel::G4XAnnihilationChannel(), G4XMesonBaryonElastic::G4XMesonBaryonElastic(), G4VAtomDeexcitation::GenerateParticles(), GFlashHomoShowerParameterisation::GenerateRadius(), GFlashSamplingShowerParameterisation::GenerateRadius(), G4PrimaryTransformer::GenerateSingleTrack(), G4ParticleHPVector::Get15percentBorder(), G4ParticleHPVector::Get50percentBorder(), G4DensityEffectData::GetAdensity(), G4DensityEffectData::GetAdjustmentFactor(), G4ParticleHPFFFissionFS::GetAFissionFragment(), G4ITStepProcessor::GetAtRestIL(), G4DensityEffectData::GetCdensity(), PHActsTrackProjection::getClusterProperties(), G4MesonAbsorption::GetCollisions(), G4Scatterer::GetCollisions(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4AdjointAlongStepWeightCorrection::GetContinuousStepLimit(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4AdjointForcedInteractionForGamma::GetContinuousStepLimit(), G4VEnergyLossProcess::GetContinuousStepLimit(), G4EmCalculator::GetCrossSectionPerVolume(), G4LossTableManager::GetCSDARange(), G4VEnergyLossProcess::GetCSDARange(), G4DensityEffectData::GetDelta0density(), G4ErrorTarget::GetDistanceFromPoint(), G4ErrorTrackLengthTarget::GetDistanceFromPoint(), G4tgrUtils::GetDouble(), G4HadronicProcess::GetEnergyMomentumCheckEnvvars(), G4TheoFSGenerator::GetEnergyMomentumCheckLevels(), GFlashParticleBounds::GetEneToKill(), G4DensityEffectData::GetErrorDensity(), G4ParticleHPElastic::GetFatalEnergyCheckLevels(), G4ParticleHPCapture::GetFatalEnergyCheckLevels(), G4LENDFission::GetFatalEnergyCheckLevels(), G4ParticleHPFission::GetFatalEnergyCheckLevels(), G4ParticleHPThermalScattering::GetFatalEnergyCheckLevels(), G4ParticleHPInelastic::GetFatalEnergyCheckLevels(), G4NuclideTable::GetIsotope(), G4DensityEffectData::GetMdensity(), G4PhononReflection::GetMeanFreePath(), G4Channeling::GetMeanFreePath(), StepLimiter::GetMeanFreePath(), G4OpMieHG::GetMeanFreePath(), StepMax::GetMeanFreePath(), G4VTransitionRadiation::GetMeanFreePath(), G4TransitionRadiation::GetMeanFreePath(), G4VLEPTSModel::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4DNAElectronHoleRecombination::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4eplusPolarizedAnnihilation::GetMeanFreePath(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4OpAbsorption::GetMeanFreePath(), G4ElectronCapture::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4ForwardXrayTR::GetMeanFreePath(), G4LowECapture::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4OpRayleigh::GetMeanFreePath(), G4OpWLS::GetMeanFreePath(), G4NeutronKiller::GetMeanFreePath(), G4GammaConversionToMuons::GetMeanFreePath(), G4AnnihiToMuPair::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4ePolarizedIonisation::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4UCNLoss::GetMeanFreePath(), G4UCNMultiScattering::GetMeanFreePath(), G4UCNAbsorption::GetMeanFreePath(), G4PolarizedCompton::GetMeanFreePath(), G4UCNBoundaryProcess::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4Scintillation::GetMeanFreePath(), G4OpBoundaryProcess::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4EmCalculator::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4VMultipleScattering::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4DensityEffectData::GetMeanIonisationPotential(), G4DNAElectronHoleRecombination::GetMeanLifeTime(), G4Scintillation::GetMeanLifeTime(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), G4HadronicInteraction::GetMinEnergy(), GFlashParticleBounds::GetMinEneToParametrise(), G4SampleResonance::GetMinimumMass(), G4CollisionManager::GetNextCollision(), G4ITTrackHolder::GetNextTime(), G4Scheduler::GetNextWatchedTime(), G4PAIxSection::GetPhotonRange(), G4ParticleHPPhotonDist::GetPhotons(), G4DensityEffectData::GetPlasmaEnergy(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4NuclearShellModelDensity::GetRadius(), G4NuclearFermiDensity::GetRadius(), G4LossTableManager::GetRange(), G4EnergyLossTables::GetRange(), G4LossTableManager::GetRangeFromRestricteDEDX(), G4EmBiasingManager::GetStepLimit(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4VMscModel::GetTransportMeanFreePath(), G4DensityEffectData::GetX0density(), G4DensityEffectData::GetX1density(), DicomROIContour::GetZ(), G4VCrossSectionSource::HighLimit(), G4GDMLParser::ImportRegions(), G4TablesForExtrapolator::Initialisation(), G4DNAModelInterface::Initialise(), G4IonCoulombCrossSection::Initialise(), G4WentzelOKandVIxSection::Initialise(), G4ScreeningMottCrossSection::Initialise(), G4EmModelManager::Initialise(), G4VEmModel::InitialiseElementSelectors(), G4ITStepProcessor::Initialize(), G4DNAMoleculeEncounterStepper::InitializeForNewTrack(), G4SteppingManager::InvokeAtRestDoItProcs(), G4VTwistedFaceted::LastValue::LastValue(), G4TwistedTubs::LastValue::LastValue(), G4VTwistedFaceted::LastValueWithDoubleVector::LastValueWithDoubleVector(), G4TwistedTubs::LastValueWithDoubleVector::LastValueWithDoubleVector(), lgam(), PDBlib::Load(), G4VEmProcess::MeanFreePath(), G4VEnergyLossProcess::MeanFreePath(), G4KDTree::Nearest(), nf_gammaFunction(), operator<<(), G4DNASecondOrderReaction::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), HadrontherapyStepMax::PostStepGetPhysicalInteractionLength(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4StepLimiter::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), F04StepMax::PostStepGetPhysicalInteractionLength(), G4SpecialCuts::PostStepGetPhysicalInteractionLength(), DMXSpecialCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), IORTStepMax::PostStepGetPhysicalInteractionLength(), ML2StepMax::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4MuonicAtomDecay::PostStepGetPhysicalInteractionLength(), G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), G4HadronStoppingProcess::PostStepGetPhysicalInteractionLength(), G4NeutronKiller::PostStepGetPhysicalInteractionLength(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::PostStepGetPhysicalInteractionLength(), G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength(), G4Transportation::PostStepGetPhysicalInteractionLength(), G4ImportanceProcess::PostStepGetPhysicalInteractionLength(), G4MonopoleTransportation::PostStepGetPhysicalInteractionLength(), G4WeightWindowProcess::PostStepGetPhysicalInteractionLength(), G4CoupledTransportation::PostStepGetPhysicalInteractionLength(), G4PolarizedCompton::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::PostStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4ITTransportation::PostStepGetPhysicalInteractionLength(), G4ScoreSplittingProcess::PostStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4VMultipleScattering::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), PrimaryKiller::PrimaryKiller(), G4IonParametrisedLossModel::PrintDEDXTable(), PHGenFitTrackProjection::process_event(), getVectors::process_event(), G4BOptnForceCommonTruncatedExp::ProposeAlongStepLimit(), G4VBiasingOperation::ProposeAlongStepLimit(), GB05BOptrSplitAndKillByCrossSection::ProposeNonPhysicsBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), HepGeom::BasicVector3D< T >::pseudoRapidity(), G4AnalyticalPolSolver::QuarticRoots(), RE01Trajectory::RE01Trajectory(), G4ChannelingECHARM::ReadFromECHARM(), DicomDetectorConstruction::ReadVoxelDensities(), DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4VIntersectionLocator::ReportImmediateHit(), G4Scheduler::Reset(), G4VoxelSafety::SafetyForVoxelHeader(), G4VoxelSafety::SafetyForVoxelNode(), G4ParticleHPLegendreStore::Sample(), G4ILawForceFreeFlight::SampleInteractionLength(), G4InteractionLawPhysical::SampleInteractionLength(), G4WentzelVIModel::SampleScattering(), G4DNAModelInterface::SampleSecondaries(), G4TDNAOneStepThermalizationModel< MODEL >::SampleSecondaries(), G4QMDGroundStateNucleus::samplingMomentum(), G4ChannelingMaterialData::SetBR(), G4ChargeState::SetChargeSpinMoments(), G4PrimaryTransformer::SetDecayProducts(), F04ElementField::SetGlobalPoint(), G4VEnergyLossProcess::SetLambdaTable(), G4UniversalFluctuation::SetParticleAndCharge(), XDetectorConstruction::SetupGeometry(), G4AtimaEnergyLossModel::SetupParameters(), G4BetheBlochModel::SetupParameters(), CLHEP::RandStudentT::shoot(), G4VEmProcess::StartTracking(), G4VEnergyLossProcess::StartTracking(), StepMax::StepMax(), StepMaxProcess::StepMaxProcess(), G4BinaryCascade::StepParticlesOut(), G4Scheduler::Stepping(), G4CoulombScattering::StreamProcessInfo(), G4eBremsstrahlung::StreamProcessInfo(), G4ErrorPropagationNavigator::TargetSafetyFromPoint(), G4VisExtent::Transform(), G4RKPropagation::Transport(), G4ILawForceFreeFlight::UpdateInteractionLengthForStep(), G4VBiasingInteractionLaw::UpdateInteractionLengthForStep(), G4Channeling::UpdateParameters(), and G4VEmModel::Value().
#define DBL_MIN std::numeric_limits<double>::min()
Definition at line 74 of file templates.hh.
View newest version in sPHENIX GitHub at line 74 of file templates.hh
Referenced by HistoManager::AddTargetStep(), G4PreCompoundEmission::AngularDistribution(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4Hype::ApproxDistInside(), G4Hype::ApproxDistOutside(), G4Decay::AtRestGetPhysicalInteractionLength(), G4DecayProducts::Boost(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4VLEPTSModel::BuildMeanFreePathTable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4PolyconeSide::CalculateExtent(), G4Track::CalculateVelocity(), RunAction::ComputeMscHighland(), Run::ComputeMscHighland(), G4GenericBiasingPhysics::ConstructProcess(), G4ITStepProcessor::DealWithSecondaries(), G4Hype::DistanceToIn(), G4Hype::DistanceToOut(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4PolyconeSide::Extent(), G4PolyhedraSide::Extent(), G4PolyPhiFace::G4PolyPhiFace(), G4TwistedTubs::G4TwistedTubs(), G4tgrUtils::GetDouble(), G4TripathiCrossSection::GetElementCrossSection(), G4AnnihiToMuPair::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4PAIxSection::GetPhotonRange(), G4BOptnForceCommonTruncatedExp::Initialize(), G4TwistTubsHypeSide::Inside(), G4PolyconeSide::Intersect(), G4Hype::IntersectHype(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4ITStepProcessor::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4DecayProducts::IsChecked(), G4VXResonance::IsospinCorrection(), operator<<(), G4PolyconeSide::PointOnCone(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4UnknownDecay::PostStepGetPhysicalInteractionLength(), GB05BOptrSplitAndKillByCrossSection::ProposeNonPhysicsBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), MyKleinNishinaCompton::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), DetectorConstruction::SetAbsorSizeYZ(), DetectorConstruction::SetAbsorThickness(), G4ReactionProduct::SetDefinitionAndUpdateE(), DetectorConstruction::SetMaxStepLength(), DetectorConstruction::SetMaxStepSize(), and G4RPGInelastic::SetUpChange().
#define FLT_DIG std::numeric_limits<float>::digits10
Definition at line 94 of file templates.hh.
View newest version in sPHENIX GitHub at line 94 of file templates.hh
#define FLT_EPSILON std::numeric_limits<float>::epsilon()
Definition at line 102 of file templates.hh.
View newest version in sPHENIX GitHub at line 102 of file templates.hh
Referenced by NeuronLoadDataFile::ComputeTransformation(), and PHSartre::process_event().
#define FLT_MAX std::numeric_limits<float>::max()
Definition at line 98 of file templates.hh.
View newest version in sPHENIX GitHub at line 98 of file templates.hh
Referenced by CaloRawClusterEval::best_cluster_from(), JetRecoEval::best_jet_from(), CaloRawTowerEval::best_tower_from(), SvtxTrackEval::best_track_from(), SvtxTruthEval::get_innermost_truth_hit(), SvtxTruthEval::get_outermost_truth_hit(), G4tgrUtils::GetDouble(), SvtxHitEval::max_truth_hit_by_energy(), SvtxClusterEval::max_truth_hit_by_energy(), JetRecoEval::max_truth_jet_by_energy(), SvtxClusterEval::max_truth_particle_by_cluster_energy(), SvtxHitEval::max_truth_particle_by_energy(), SvtxClusterEval::max_truth_particle_by_energy(), CaloRawClusterEval::max_truth_primary_shower_by_energy(), CaloRawTowerEval::max_truth_primary_shower_by_energy(), GlobalVertexReco::process_event(), HepGeom::BasicVector3D< T >::pseudoRapidity(), and PHG4InttDigitizer::set_adc_scale().
#define FLT_MIN std::numeric_limits<float>::min()
Definition at line 90 of file templates.hh.
View newest version in sPHENIX GitHub at line 90 of file templates.hh
Referenced by G4tgrUtils::GetDouble().
#define G4_SQR_DEFINED
Definition at line 142 of file templates.hh.
View newest version in sPHENIX GitHub at line 142 of file templates.hh
#define HIGH_PRECISION 1
Definition at line 61 of file templates.hh.
View newest version in sPHENIX GitHub at line 61 of file templates.hh
#define INT_MAX std::numeric_limits<int>::max()
Definition at line 110 of file templates.hh.
View newest version in sPHENIX GitHub at line 110 of file templates.hh
Referenced by DicomFileCT::BuildStructureIDs(), G4ITStepProcessor::CleanProcessor(), PDBlib::ComputeMatchEdepDNA(), G4StatDouble::fill(), G4ProcessManager::FindInsertPosition(), G4SolidExtentList::G4SolidExtentList(), G4tgrUtils::GetDouble(), G4MolecularConfiguration::GetFakeParticleID(), gzputs(), G4ParticleHPInelasticBaseFS::Init(), PDBlib::Load(), G4INCL::Random::Adapter::operator()(), G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), G4LivermorePhotoElectricModel::ReadData(), G4OpticalSurface::ReadDichroicFile(), G4Physics2DVector::Retrieve(), and G4ProcessManager::SetProcessOrderingToSecond().
#define INT_MIN std::numeric_limits<int>::min()
Definition at line 114 of file templates.hh.
View newest version in sPHENIX GitHub at line 114 of file templates.hh
Referenced by Fun4AllDstPileupMerger::copy_background_event(), PHG4Hit::get_detid(), PHG4Hit::get_hit_type(), PHG4VtxPoint::get_id(), PHG4Hit::get_index_i(), PHG4Hit::get_index_j(), PHG4Hit::get_index_k(), PHG4Hit::get_index_l(), PHG4Hit::get_ladder_phi_index(), PHG4Hit::get_ladder_z_index(), EicEventHeaderv1::get_property_int(), EICPIDParticlev1::get_property_int(), PHG4Hitv1::get_property_int(), EICPIDParticle::get_property_int(), EicEventHeader::get_property_int(), PHG4Cellv1::get_property_int(), RawClusterv1::get_property_int(), PHG4Cell::get_property_int(), PHG4Hit::get_property_int(), RawCluster::get_property_int(), PHG4Hit::get_row(), PHG4Hit::get_scint_id(), PHG4Hit::get_shower_id(), PHG4Hit::get_strip_y_index(), PHG4Hit::get_strip_z_index(), PHG4Hit::get_trkid(), G4tgrUtils::GetDouble(), PHG4Hitv1::Reset(), and EICG4dRICHHit::Reset().
#define LOG_EKIN_MIN -30
Definition at line 118 of file templates.hh.
View newest version in sPHENIX GitHub at line 118 of file templates.hh
Referenced by G4UrbanMscModel::G4UrbanMscModel(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), and G4VEnergyLossProcess::PreparePhysicsTable().
#define MAXFLOAT std::numeric_limits<float>::max()
Definition at line 106 of file templates.hh.
View newest version in sPHENIX GitHub at line 106 of file templates.hh
Typedef Documentation
typedef double Float
Definition at line 65 of file templates.hh.
View newest version in sPHENIX GitHub at line 65 of file templates.hh
Function Documentation
template<typename... _Args> void G4ConsumeParameters (_Args && ...) inline
Definition at line 207 of file templates.hh.
View newest version in sPHENIX GitHub at line 207 of file templates.hh
Referenced by DicomEventAction::BeginOfEventAction(), and DicomHandler::GetDicomDataPath().
int G4lint (double ad) inline
Definition at line 159 of file templates.hh.
View newest version in sPHENIX GitHub at line 159 of file templates.hh
int G4lrint (double ad) inline
Definition at line 154 of file templates.hh.
View newest version in sPHENIX GitHub at line 154 of file templates.hh
Referenced by G4EmBiasingManager::ActivateSecondaryBiasing(), G4Material::AddElement(), G4Material::AddMaterial(), G4Element::AddNaturalIsotopes(), G4BinaryCascade::ApplyCollision(), G4BinaryLightIonReaction::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4AtimaEnergyLossModel::Bethek_dedx_e(), G4AdjointCSManager::BuildCrossSectionMatrices(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4BinaryCascade::BuildLateParticleCollisions(), G4NistMaterialBuilder::BuildMaterial(), G4CrossSectionPairGG::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4BinaryCascade::CheckChargeAndBaryonNumber(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4StatMFMacroCanonical::ChooseZ(), G4LivermorePolarizedPhotoElectricGDModel::ComputeCrossSectionPerAtom(), G4BoldyshevTripletModel::ComputeCrossSectionPerAtom(), G4LivermoreRayleighModel::ComputeCrossSectionPerAtom(), G4LivermoreGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermoreComptonModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedPhotoElectricModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedRayleighModel::ComputeCrossSectionPerAtom(), G4LivermorePhotoElectricModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedComptonModel::ComputeCrossSectionPerAtom(), G4JAEAElasticScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4PairProductionRelModel::ComputeCrossSectionPerAtom(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4LowEPComptonModel::ComputeCrossSectionPerAtom(), G4LowEPPolarizedComptonModel::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerAtom(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4Element::ComputeDerivedQuantities(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4MuBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4PairProductionRelModel::ComputeDXSectionPerAtom(), G4Element::ComputeLradTsaiFactor(), G4SandiaTable::ComputeMatSandiaMatrix(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4eBremParametrizedModel::ComputeParametrizedDXSectionPerAtom(), G4PairProductionRelModel::ComputeRelDXSectionPerAtom(), G4PairProductionRelModel::ComputeXSectionPerAtom(), G4MonopolePhysics::ConstructProcess(), G4BinaryCascade::CorrectBarionsOnBoundary(), G4KineticTrack::Decay(), G4BraggIonModel::DEDX(), G4Fissioner::deExcite(), G4PreCompoundModel::DeExcite(), G4AtimaFluctuations::Dispersion(), G4BraggModel::ElectronicStoppingPower(), G4BraggIonModel::ElectronicStoppingPower(), G4IonFluctuations::Factor(), G4ElasticHadrNucleusHE::FillData(), G4MesonAbsorption::FindAndFillCluster(), G4BinaryCascade::FindFragments(), G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionCharge(), G4Element::G4Element(), G4IonisParamElm::G4IonisParamElm(), G4Material::G4Material(), G4mplIonisationWithDeltaModel::G4mplIonisationWithDeltaModel(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4ComponentGGNuclNuclXsc::GetCoulombBarier(), G4ComponentGGNuclNuclXsc::GetElasticElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticElementCrossSection(), G4ComponentSAIDTotalXS::GetElasticElementCrossSection(), G4TripathiCrossSection::GetElementCrossSection(), G4HadronInelasticDataSet::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsSihverCrossSection::GetElementCrossSection(), G4HadronElasticDataSet::GetElementCrossSection(), G4IonsShenCrossSection::GetElementCrossSection(), G4CrossSectionPairGG::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4GeneralSpaceNNCrossSection::GetElementCrossSection(), G4PionMinusField::GetField(), G4MesonAbsorption::GetFinalState(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXsc(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscPDG(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4ComponentGGNuclNuclXsc::GetInelasticElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticElementCrossSection(), G4ComponentSAIDTotalXS::GetInelasticElementCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4MuonMinusBoundDecay::GetMuonDecayRate(), G4ComponentGGHadronNucleusXsc::GetProductionElementCrossSection(), G4ProtonInelasticCrossSection::GetProtonCrossSection(), G4ComponentGGNuclNuclXsc::GetRatioQE(), G4ComponentGGNuclNuclXsc::GetRatioSD(), G4CollisionInitialState::GetTargetBaryonNumber(), G4CollisionInitialState::GetTargetCharge(), G4BinaryCascade::GetTotalBaryonCharge(), G4BinaryCascade::GetTotalCharge(), G4ComponentGGNuclNuclXsc::GetTotalElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetTotalElementCrossSection(), G4ComponentSAIDTotalXS::GetTotalElementCrossSection(), G4GSPWACorrections::InitDataMaterial(), G4GSPWACorrections::InitDataPerElement(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4WentzelVIModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4eBremsstrahlungRelModel::InitialiseElementData(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4GSMottCorrection::InitMCDataMaterial(), G4GSMottCorrection::InitMCDataPerElement(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4EmCorrections::IonHighOrderCorrections(), G4TripathiLightCrossSection::IsElementApplicable(), G4VXResonance::IsospinCorrection(), G4MuPairProductionModel::MaxSecondaryEnergyForElement(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), operator<<(), G4VEnergyLossProcess::PreparePhysicsTable(), G4ParticleHPChannel::Register(), G4ElectronIonPair::SampleNumberOfIonsAlongStep(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4Scatterer::Scatter(), G4QuasiElasticChannel::Scatter(), HistoManager::ScoreNewTrack(), G4ElementSelector::SelectZandA(), G4Fragment::SetA(), G4KM_OpticalEqRhs::SetFactor(), G4EmParameters::SetMaxEnergy(), G4VEmProcess::SetMaxKinEnergy(), G4EmParameters::SetMinEnergy(), G4VEmProcess::SetMinKinEnergy(), G4EmParameters::SetNumberOfBins(), G4EmParameters::SetNumberOfBinsPerDecade(), G4Nucleus::SetParameters(), G4IonCoulombCrossSection::SetScreenRSquare(), G4ScreeningMottCrossSection::SetupKinematic(), G4AtimaEnergyLossModel::SetupParameters(), G4LindhardSorensenIonModel::SetupParameters(), G4BetheBlochModel::SetupParameters(), G4IonCoulombCrossSection::SetupTarget(), G4Fragment::SetZ(), G4BinaryLightIonReaction::SortResult(), G4VEmProcess::StreamInfo(), and HadrontherapyDetectorConstruction::UpdateGeometry().
int G4rint (double ad) inline
Definition at line 164 of file templates.hh.
View newest version in sPHENIX GitHub at line 164 of file templates.hh
template<class T > void G4SwapObj (T * a, T * b) inline
Definition at line 132 of file templates.hh.
View newest version in sPHENIX GitHub at line 132 of file templates.hh
References a, b, T, and tmp.
Referenced by G4OpBoundaryProcess::DielectricDielectric(), G4KineticTrack::G4KineticTrack(), and G4MesonSplitter::SplitMeson().
template<class T > void G4SwapPtr (T *& a, T *& b) inline
Definition at line 124 of file templates.hh.
View newest version in sPHENIX GitHub at line 124 of file templates.hh
References a, b, T, and tmp.
Referenced by G4OpBoundaryProcess::DielectricDielectric().
template<class T > T sqr (const T & x) inline
Definition at line 148 of file templates.hh.
View newest version in sPHENIX GitHub at line 148 of file templates.hh
References x.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4FTFAnnihilation::Annihilate(), G4Hype::asinh(), G4KineticTrackVector::BoostBeam(), G4BinaryCascade::BuildTargetList(), G4Reggeons::CalculateXs(), G4RPGKPlusInelastic::Cascade(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4BinaryCascade::CheckPauliPrinciple(), G4Reggeons::Chi_pomeron(), G4Reggeons::Chi_reggeon(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4Fancy3DNucleus::ChoosePositions(), G4KDTree::HyperRect::CompareDistSqr(), G4PolarizedComptonModel::ComputeAsymmetryPerAtom(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4Navigator::ComputeSafety(), G4PathFinder::ComputeStep(), G4ITNavigator1::ComputeStepLog(), G4Navigator::ComputeStepLog(), G4ITNavigator2::ComputeStepLog(), G4AngularDistributionNP::CosTheta(), G4AngularDistributionPP::CosTheta(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::CreateStrings(), G4BinaryCascade::DecayVoidNucleus(), G4Parton::DefineMomentumInZ(), G4GHEKinematicsVector::Defs1(), G4QGSParticipants::DeterminePartonMomenta(), G4AngularDistribution::DifferentialCrossSection(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4PolyconeSide::DistanceAway(), G4Paraboloid::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4Paraboloid::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4ElasticHNScattering::ElasticScattering(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4ErrorMag_UsualEqRhs::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), ExN04Field::ExN04Field(), G4RKPropagation::FieldTransport(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4ExcitedStringDecay::FragmentStrings(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4Navigator::G4Navigator(), G4NuclearFermiDensity::G4NuclearFermiDensity(), G4PolarizedComptonCrossSection::G4PolarizedComptonCrossSection(), G4QGSParticipants::G4QGSParticipants(), G4Reggeons::G4Reggeons(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), MedicalBeam::GeneratePrimaries(), G4NuclearFermiDensity::GetDeriv(), H02Field::GetFieldValue(), ExN04Field::GetFieldValue(), RE01Field::GetFieldValue(), RE05Field::GetFieldValue(), G4MesonAbsorption::GetFinalState(), G4LundStringFragmentation::GetLightConeZ(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4PolarizationHelper::GetParticleFrameX(), G4PolarizationHelper::GetParticleFrameY(), G4Polycone::GetPointOnCone(), G4Polycone::GetPointOnSurface(), G4Polyhedra::GetPointOnSurface(), G4Paraboloid::GetPointOnSurface(), G4Hype::GetPointOnSurface(), G4Sphere::GetPointOnSurface(), G4TwistedTubs::GetPointOnSurface(), G4Reggeons::GetProbabilities(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4DiffractiveExcitation::GetQuarkFractionOfKink(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4BinaryCascade::GetSpherePoint(), G4PolarizationHelper::GetSpinInPRF(), G4ChipsKaonPlusElasticXS::GetTabValues(), G4ChipsKaonMinusElasticXS::GetTabValues(), G4GHEKinematicsVector::Impu(), G4FTFParameters::InitForInteraction(), G4PolarizedAnnihilationCrossSection::Initialize(), G4PolarizedComptonCrossSection::Initialize(), G4QGSMSplitableHadron::InitParameters(), G4Paraboloid::Inside(), G4BinaryLightIonReaction::Interact(), G4QGSMFragmentation::IsItFragmentable(), G4LundStringFragmentation::lambda(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4PathFinder::Locate(), G4GHEKinematicsVector::Lor(), G4KDTree::NearestInRange(), G4MagInt_Driver::OneGoodStep(), ExN04MuonSD::ProcessHits(), RE05MuonSD::ProcessHits(), G4VLongitudinalStringDecay::ProduceOneHadron(), G4GeneratorPrecompoundInterface::Propagate(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), pypole(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4MagInt_Driver::QuickAdvance(), RE01Field::RE01Field(), RE05Field::RE05Field(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4PathFinder::ReLocate(), G4SafetyHelper::ReLocateWithinVolume(), G4ITSafetyHelper::ReLocateWithinVolume(), G4GeomTools::RemoveRedundantVertices(), G4QGSMFragmentation::Sample4Momentum(), G4LundStringFragmentation::Sample4Momentum(), G4AntiNuclElastic::SampleInvariantT(), G4VLongitudinalStringDecay::SampleQuarkPt(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), G4QuasiElasticChannel::Scatter(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), G4RepleteEofM::SetChargeMomentumMass(), G4EqEMFieldWithSpin::SetChargeMomentumMass(), G4EqEMFieldWithEDM::SetChargeMomentumMass(), G4Mag_SpinEqRhs::SetChargeMomentumMass(), G4DecayWithSpin::Spin_Precession(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4LundStringFragmentation::Splitup(), G4QGSDiffractiveExcitation::String(), G4PolyconeSide::SurfaceArea(), G4Paraboloid::SurfaceNormal(), G4PolarizedAnnihilationCrossSection::TotalXSection(), G4PolarizedComptonCrossSection::TotalXSection(), G4RKPropagation::Transport(), G4KineticTrack::Update4Momentum(), and G4KineticTrack::UpdateTrackingMomentum().