ECCE @ EIC Software: CCalSensitiveDetectors Class Reference
CCalSensitiveDetectors Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSensitiveDetectors.hh>
Public Member Functions
~CCalSensitiveDetectors ()
std::vector< G4LogicalVolume * > getVolumes (const G4String &name, G4bool exists=false)
void registerVolume (const G4String &name, G4LogicalVolume *)
G4bool setSensitive (const G4String &string, G4VSensitiveDetector *sens)
Static Public Member Functions
static CCalSensitiveDetectors * getInstance ()
Private Member Functions
CCalSensitiveDetectors ()
Private Attributes
mmslv theLVs
Static Private Attributes
static CCalSensitiveDetectors * theInstance = 0
Detailed Description
Definition at line 41 of file CCalSensitiveDetectors.hh.
View newest version in sPHENIX GitHub at line 41 of file CCalSensitiveDetectors.hh
Constructor & Destructor Documentation
CCalSensitiveDetectors::~CCalSensitiveDetectors () inline
Definition at line 44 of file CCalSensitiveDetectors.hh.
View newest version in sPHENIX GitHub at line 44 of file CCalSensitiveDetectors.hh
CCalSensitiveDetectors::CCalSensitiveDetectors () inline private
Definition at line 51 of file CCalSensitiveDetectors.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalSensitiveDetectors.hh
Referenced by getInstance().
Member Function Documentation
CCalSensitiveDetectors * CCalSensitiveDetectors::getInstance () static
Definition at line 38 of file CCalSensitiveDetectors.cc.
View newest version in sPHENIX GitHub at line 38 of file CCalSensitiveDetectors.cc
References CCalSensitiveDetectors(), and theInstance.
Referenced by CCalSensAssign::assign(), CCalG4Hcal::constructSensitive(), and CCalG4Ecal::constructSensitive().
std::vector< G4LogicalVolume * > CCalSensitiveDetectors::getVolumes (const G4String & name, G4bool exists = false)
Definition at line 56 of file CCalSensitiveDetectors.cc.
View newest version in sPHENIX GitHub at line 56 of file CCalSensitiveDetectors.cc
References G4cout, G4endl, and theLVs.
void CCalSensitiveDetectors::registerVolume (const G4String & name, G4LogicalVolume * logv)
Definition at line 45 of file CCalSensitiveDetectors.cc.
View newest version in sPHENIX GitHub at line 45 of file CCalSensitiveDetectors.cc
References G4cout, G4endl, G4LogicalVolume::GetName(), and theLVs.
Referenced by CCalG4Hcal::constructSensitive(), and CCalG4Ecal::constructSensitive().
G4bool CCalSensitiveDetectors::setSensitive (const G4String & string, G4VSensitiveDetector * sens)
Definition at line 73 of file CCalSensitiveDetectors.cc.
View newest version in sPHENIX GitHub at line 73 of file CCalSensitiveDetectors.cc
References G4cout, G4endl, G4VSensitiveDetector::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::SetSensitiveDetector(), and theLVs.
Referenced by CCalSensAssign::assign().
Member Data Documentation
CCalSensitiveDetectors * CCalSensitiveDetectors::theInstance = 0 static private
Definition at line 51 of file CCalSensitiveDetectors.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalSensitiveDetectors.hh
Referenced by getInstance().
mmslv CCalSensitiveDetectors::theLVs private
Definition at line 54 of file CCalSensitiveDetectors.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalSensitiveDetectors.hh
Referenced by getVolumes(), registerVolume(), and setSensitive().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSensitiveDetectors.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalSensitiveDetectors.cc