ECCE @ EIC Software: Par02FastSimModelEMCal Class Reference
Par02FastSimModelEMCal Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02FastSimModelEMCal.hh>
Public Member Functions
Par02FastSimModelEMCal (G4String aModelName, G4Region *aEnvelope, Par02DetectorParametrisation::Parametrisation aParamType)
Par02FastSimModelEMCal (G4String aModelName, G4Region *aEnvelope)
Par02FastSimModelEMCal (G4String aModelName)
~Par02FastSimModelEMCal ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticle)
virtual G4bool ModelTrigger (const G4FastTrack &aFastTrack)
virtual void DoIt (const G4FastTrack &aFastTrack, G4FastStep &aFastStep)
Public Member Functions inherited from G4VFastSimulationModel
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Private Attributes
Par02DetectorParametrisation * fCalculateParametrisation
Par02DetectorParametrisation::Parametrisation fParametrisation
A parametrisation type.
Detailed Description
Shortcut to the ordinary tracking for electromagnetic calorimeters.
The fast simulation model describes what should be done instead of a normal tracking. Instead of the ordinary tracking, a particle deposits its energy at the entrance to the electromagnetic calorimeter and its value is smeared (by Par02Smearer::SmearMomentum()). Based on G4 examples/extended/parametrisations/Par01/include/Par01EMShowerModel.hh .
Author
Anna Zaborowska
Definition at line 46 of file Par02FastSimModelEMCal.hh.
View newest version in sPHENIX GitHub at line 46 of file Par02FastSimModelEMCal.hh
Constructor & Destructor Documentation
Par02FastSimModelEMCal::Par02FastSimModelEMCal (G4String aModelName, G4Region * aEnvelope, Par02DetectorParametrisation::Parametrisation aParamType)
A constructor.
Parameters
aModelName A name of the fast simulation model.
aEnvelope A region where the model can take over the ordinary tracking.
aParamType A parametrisation type.
Definition at line 50 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 50 of file Par02FastSimModelEMCal.cc
Par02FastSimModelEMCal::Par02FastSimModelEMCal (G4String aModelName, G4Region * aEnvelope)
A constructor.
Parameters
aModelName A name of the fast simulation model.
aEnvelope A region where the model can take over the ordinary tracking.
Definition at line 57 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 57 of file Par02FastSimModelEMCal.cc
Par02FastSimModelEMCal::Par02FastSimModelEMCal (G4String aModelName)
A constructor.
Parameters
aModelName A name of the fast simulation model.
Definition at line 64 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 64 of file Par02FastSimModelEMCal.cc
Par02FastSimModelEMCal::~Par02FastSimModelEMCal ()
Definition at line 70 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 70 of file Par02FastSimModelEMCal.cc
Member Function Documentation
void Par02FastSimModelEMCal::DoIt (const G4FastTrack & aFastTrack, G4FastStep & aFastStep) virtual
Smears the energy deposit and saves it, together with the position of the deposit, the electromagnetic calorimeter resolution and efficiency to the Par02PrimaryParticleInformation.
Parameters
aFastTrack A track.
aFastStep A step.
Implements G4VFastSimulationModel.
Definition at line 90 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 90 of file Par02FastSimModelEMCal.cc
References kdfinder::abs(), Par02DetectorParametrisation::eEMCAL, fCalculateParametrisation, Par02Output::FillHistogram(), fParametrisation, Par02EventInformation::GetDoSmearing(), G4Track::GetDynamicParticle(), Par02DetectorParametrisation::GetEfficiency(), G4EventManager::GetEventManager(), G4Track::GetKineticEnergy(), G4Track::GetMomentum(), G4Track::GetParentID(), G4Track::GetPosition(), G4DynamicParticle::GetPrimaryParticle(), G4FastTrack::GetPrimaryTrack(), Par02DetectorParametrisation::GetResolution(), G4EventManager::GetUserInformation(), Par02Output::Instance(), Par02Smearer::Instance(), G4FastStep::KillPrimaryTrack(), CLHEP::Hep3Vector::mag(), MeV, G4FastStep::ProposePrimaryTrackPathLength(), and G4FastStep::ProposeTotalEnergyDeposited().
G4bool Par02FastSimModelEMCal::IsApplicable (const G4ParticleDefinition & aParticle) virtual
Checks if this model should be applied to this particle type.
Parameters
aParticle A particle definition (type).
Implements G4VFastSimulationModel.
Definition at line 74 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 74 of file Par02FastSimModelEMCal.cc
References G4Electron::Definition(), G4Positron::Definition(), and G4Gamma::Definition().
G4bool Par02FastSimModelEMCal::ModelTrigger (const G4FastTrack & aFastTrack) virtual
Checks if the model should be applied, taking into account the kinematics of a track.
Parameters
aFastTrack A track.
Implements G4VFastSimulationModel.
Definition at line 84 of file Par02FastSimModelEMCal.cc.
View newest version in sPHENIX GitHub at line 84 of file Par02FastSimModelEMCal.cc
Member Data Documentation
Par02DetectorParametrisation* Par02FastSimModelEMCal::fCalculateParametrisation private
A pointer to Par02DetectorParametrisation used to get the efficiency and resolution of the detector for a given particle and parametrisation type.
Definition at line 87 of file Par02FastSimModelEMCal.hh.
View newest version in sPHENIX GitHub at line 87 of file Par02FastSimModelEMCal.hh
Referenced by DoIt().
Par02DetectorParametrisation::Parametrisation Par02FastSimModelEMCal::fParametrisation private
A parametrisation type.
Definition at line 90 of file Par02FastSimModelEMCal.hh.
View newest version in sPHENIX GitHub at line 90 of file Par02FastSimModelEMCal.hh
Referenced by DoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02FastSimModelEMCal.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/src/Par02FastSimModelEMCal.cc