ECCE @ EIC Software: G4VUIshell Class Reference
G4VUIshell Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4VUIshell.hh>
Public Member Functions
G4VUIshell (const G4String &prompt="> ")
virtual ~G4VUIshell ()
void SetNColumn (G4int ncol)
void SetPrompt (const G4String &prompt)
void SetCurrentDirectory (const G4String &ccd)
virtual void SetLsColor (TermColorIndex, TermColorIndex)
virtual void ShowCurrentDirectory () const
virtual void ListCommand (const G4String &input, const G4String &candidate="") const
virtual G4String GetCommandLineString (const char *msg=0)=0
virtual void ResetTerminal ()
Protected Member Functions
virtual void MakePrompt (const char *msg=0)
G4UIcommandTree * GetCommandTree (const G4String &dir) const
G4String GetAbsCommandDirPath (const G4String &apath) const
G4String GetCommandPathTail (const G4String &apath) const
Protected Attributes
G4String promptSetting
G4String promptString
G4int nColumn
G4bool lsColorFlag
TermColorIndex directoryColor
TermColorIndex commandColor
G4String currentCommandDir
Detailed Description
Definition at line 58 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VUIshell.hh
Constructor & Destructor Documentation
G4VUIshell::G4VUIshell (const G4String & prompt = "> ")
Definition at line 45 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VUIshell.cc
G4VUIshell::~G4VUIshell () virtual
Definition at line 54 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VUIshell.cc
Member Function Documentation
G4String G4VUIshell::GetAbsCommandDirPath (const G4String & apath) const protected
Definition at line 146 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 146 of file G4VUIshell.cc
References G4String::index(), G4String::last(), and G4String::remove().
Referenced by G4UItcsh::CompleteCommand(), and G4UItcsh::ListMatchedCommand().
virtual G4String G4VUIshell::GetCommandLineString (const char * msg = 0) pure virtual
Implemented in G4UItcsh, G4UIcsh, and G4UImpish.
G4String G4VUIshell::GetCommandPathTail (const G4String & apath) const protected
Definition at line 192 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 192 of file G4VUIshell.cc
References FALSE, and TRUE.
Referenced by G4UItcsh::CompleteCommand().
G4UIcommandTree * G4VUIshell::GetCommandTree (const G4String & dir) const protected
Definition at line 117 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 117 of file G4VUIshell.cc
References G4String::both, G4UImanager::GetUIpointer(), G4String::index(), and G4String::strip().
Referenced by G4UItcsh::CompleteCommand().
void G4VUIshell::ListCommand (const G4String & input, const G4String & candidate = "") const virtual
Definition at line 230 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 230 of file G4VUIshell.cc
References G4String::both, dir, FALSE, G4cout, G4endl, G4String::index(), G4UIArrayString::Show(), G4String::strip(), and TRUE.
Referenced by G4UItcsh::ListMatchedCommand().
void G4VUIshell::MakePrompt (const char * msg = 0) protected virtual
Reimplemented in G4UItcsh.
Definition at line 60 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VUIshell.cc
References G4String::append(), currentCommandDir, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), promptSetting, and promptString.
Referenced by G4UIcsh::GetCommandLineString().
void G4VUIshell::ResetTerminal () virtual
Reimplemented in G4UItcsh.
Definition at line 107 of file G4VUIshell.cc.
View newest version in sPHENIX GitHub at line 107 of file G4VUIshell.cc
void G4VUIshell::SetCurrentDirectory (const G4String & ccd) inline
Definition at line 114 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VUIshell.hh
References currentCommandDir, and dir.
void G4VUIshell::SetLsColor (TermColorIndex , TermColorIndex) inline virtual
Reimplemented in G4UItcsh.
Definition at line 119 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VUIshell.hh
void G4VUIshell::SetNColumn (G4int ncol) inline
Definition at line 104 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 104 of file G4VUIshell.hh
References nColumn.
void G4VUIshell::SetPrompt (const G4String & prompt) inline
Definition at line 109 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VUIshell.hh
References promptSetting.
void G4VUIshell::ShowCurrentDirectory () const inline virtual
Definition at line 123 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 123 of file G4VUIshell.hh
References currentCommandDir, G4cout, and G4endl.
Member Data Documentation
TermColorIndex G4VUIshell::commandColor protected
Definition at line 69 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VUIshell.hh
Referenced by G4UItcsh::SetLsColor().
G4String G4VUIshell::currentCommandDir protected
Definition at line 72 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VUIshell.hh
Referenced by G4UItcsh::CompleteCommand(), G4UItcsh::ListMatchedCommand(), MakePrompt(), G4UItcsh::MakePrompt(), SetCurrentDirectory(), and ShowCurrentDirectory().
TermColorIndex G4VUIshell::directoryColor protected
Definition at line 68 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VUIshell.hh
Referenced by G4UItcsh::SetLsColor().
G4bool G4VUIshell::lsColorFlag protected
Definition at line 67 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VUIshell.hh
Referenced by G4UItcsh::SetLsColor().
G4int G4VUIshell::nColumn protected
Definition at line 63 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VUIshell.hh
Referenced by SetNColumn().
G4String G4VUIshell::promptSetting protected
Definition at line 60 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VUIshell.hh
Referenced by MakePrompt(), G4UItcsh::MakePrompt(), and SetPrompt().
G4String G4VUIshell::promptString protected
Definition at line 61 of file G4VUIshell.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VUIshell.hh
Referenced by G4UItcsh::ClearScreen(), G4UIcsh::GetCommandLineString(), G4UItcsh::GetCommandLineString(), G4UItcsh::ListMatchedCommand(), MakePrompt(), and G4UItcsh::MakePrompt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4VUIshell.hh
geant4/tree/geant4-10.6-release/source/interfaces/basic/src/G4VUIshell.cc