ECCE @ EIC Software: G4UImanager Class Reference
G4UImanager Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UImanager.hh>
Public Member Functions
~G4UImanager ()
G4String GetCurrentValues (const char *aCommand)
void AddNewCommand (G4UIcommand *newCommand)
void RemoveCommand (G4UIcommand *aCommand)
void ExecuteMacroFile (const char *fileName)
void Loop (const char *macroFile, const char *variableName, G4double initialValue, G4double finalValue, G4double stepSize=1.0)
void Foreach (const char *macroFile, const char *variableName, const char *candidates)
G4int ApplyCommand (const char *aCommand)
G4int ApplyCommand (const G4String &aCommand)
void StoreHistory (const char *fileName="G4history.macro")
void StoreHistory (G4bool historySwitch, const char *fileName="G4history.macro")
void ListCommands (const char *direc)
void SetAlias (const char *aliasLine)
void RemoveAlias (const char *aliasName)
void ListAlias ()
G4String SolveAlias (const char *aCmd)
void CreateHTML (const char *dir="/")
void LoopS (const char *valueList)
void ForeachS (const char *valueList)
virtual G4bool Notify (G4ApplicationState requestedState)
G4String GetCurrentStringValue (const char *aCommand, G4int parameterNumber=1, G4bool reGet=true)
G4int GetCurrentIntValue (const char *aCommand, G4int parameterNumber=1, G4bool reGet=true)
G4double GetCurrentDoubleValue (const char *aCommand, G4int parameterNumber=1, G4bool reGet=true)
G4String GetCurrentStringValue (const char *aCommand, const char *aParameterName, G4bool reGet=true)
G4int GetCurrentIntValue (const char *aCommand, const char *aParameterName, G4bool reGet=true)
G4double GetCurrentDoubleValue (const char *aCommand, const char *aParameterName, G4bool reGet=true)
void SetPauseAtBeginOfEvent (G4bool vl)
G4bool GetPauseAtBeginOfEvent () const
void SetPauseAtEndOfEvent (G4bool vl)
G4bool GetPauseAtEndOfEvent () const
G4UIcommandTree * GetTree () const
G4UIsession * GetSession () const
G4UIsession * GetG4UIWindow () const
void SetSession (G4UIsession *const value)
void SetG4UIWindow (G4UIsession *const value)
void SetCoutDestination (G4UIsession *const value)
void SetVerboseLevel (G4int val)
G4int GetVerboseLevel () const
G4int GetNumberOfHistory () const
G4String GetPreviousCommand (G4int i) const
void SetMaxHistSize (G4int mx)
G4int GetMaxHistSize () const
void SetMacroSearchPath (const G4String &path)
const G4String & GetMacroSearchPath () const
void ParseMacroSearchPath ()
G4String FindMacroPath (const G4String &fname) const
void SetMasterUIManager (G4bool val)
void SetIgnoreCmdNotFound (G4bool val)
std::vector< G4String > * GetCommandStack ()
void RegisterBridge (G4UIbridge *brg)
void SetUpForAThread (G4int tId)
void SetUpForSpecialThread (G4String aPrefix)
G4int GetThreadID () const
void SetCoutFileName (const G4String &fileN="G4cout.txt", G4bool ifAppend=true)
void SetCerrFileName (const G4String &fileN="G4cerr.txt", G4bool ifAppend=true)
void SetThreadPrefixString (const G4String &s="W")
void SetThreadUseBuffer (G4bool flg=true)
void SetThreadIgnore (G4int tid=0)
void SetThreadIgnoreInit (G4bool flg=true)
G4MTcoutDestination * GetThreadCout ()
G4int GetLastReturnCode () const
Public Member Functions inherited from G4VStateDependent
G4VStateDependent (G4bool bottom=false)
virtual ~G4VStateDependent ()
G4bool operator== (const G4VStateDependent &right) const
G4bool operator!= (const G4VStateDependent &right) const
Static Public Member Functions
static G4UImanager * GetUIpointer ()
static G4UImanager * GetMasterUIpointer ()
static void UseDoublePrecisionStr (G4bool val)
static G4bool DoublePrecisionStr ()
Protected Member Functions
G4UImanager ()
Private Member Functions
G4UImanager (const G4UImanager &right)
const G4UImanager & operator= (const G4UImanager &right)
G4bool operator== (const G4UImanager &right) const
G4bool operator!= (const G4UImanager &right) const
void AddWorkerCommand (G4UIcommand *newCommand)
void RemoveWorkerCommand (G4UIcommand *aCommand)
void PauseSession (const char *msg)
void CreateMessenger ()
G4UIcommandTree * FindDirectory (const char *dirName)
Static Private Member Functions
static G4ICOMS_DLL G4UImanager *& fUImanager ()
static G4ICOMS_DLL G4bool & fUImanagerHasBeenKilled ()
static G4ICOMS_DLL G4UImanager *& fMasterUImanager ()
Private Attributes
G4UIcommandTree * treeTop
G4UIsession * session
G4UIsession * g4UIWindow
G4UIcontrolMessenger * UImessenger
G4UnitsMessenger * UnitsMessenger
G4LocalThreadCoutMessenger * CoutMessenger
G4String savedParameters
G4UIcommand * savedCommand
G4int verboseLevel
std::ofstream historyFile
G4bool saveHistory
std::vector< G4String > histVec
G4UIaliasList * aliasList
G4int maxHistSize
G4bool pauseAtBeginOfEvent
G4bool pauseAtEndOfEvent
G4String searchPath
std::vector< G4String > searchDirs
G4bool isMaster
std::vector< G4UIbridge * > * bridges
G4bool ignoreCmdNotFound
G4bool stackCommandsForBroadcast
std::vector< G4String > * commandStack
G4int threadID
G4MTcoutDestination * threadCout
G4int lastRC
Static Private Attributes
static G4ICOMS_DLL G4int igThreadID = -1
static G4ICOMS_DLL G4bool doublePrecisionStr = false
Detailed Description
Definition at line 57 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 57 of file G4UImanager.hh
Constructor & Destructor Documentation
G4UImanager::G4UImanager () protected
Definition at line 88 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 88 of file G4UImanager.cc
References aliasList, commandStack, g4UIWindow, maxHistSize, pauseAtBeginOfEvent, pauseAtEndOfEvent, savedCommand, savedParameters, saveHistory, searchPath, session, SetCoutDestination(), treeTop, and verboseLevel.
Referenced by GetUIpointer().
G4UImanager::~G4UImanager ()
Definition at line 119 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4UImanager.cc
References aliasList, bridges, commandStack, CoutMessenger, fUImanager(), fUImanagerHasBeenKilled(), G4iosFinalization(), historyFile, histVec, saveHistory, SetCoutDestination(), threadCout, threadID, treeTop, UImessenger, and UnitsMessenger.
G4UImanager::G4UImanager (const G4UImanager & right) private
Definition at line 151 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 151 of file G4UImanager.cc
References aliasList, bridges, commandStack, CoutMessenger, CreateMessenger(), g4UIWindow, ignoreCmdNotFound, isMaster, maxHistSize, pauseAtBeginOfEvent, pauseAtEndOfEvent, savedCommand, saveHistory, session, stackCommandsForBroadcast, threadCout, threadID, treeTop, UImessenger, UnitsMessenger, and verboseLevel.
Member Function Documentation
void G4UImanager::AddNewCommand (G4UIcommand * newCommand)
Definition at line 287 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 287 of file G4UImanager.cc
References G4UIcommandTree::AddNewCommand(), AddWorkerCommand(), fMasterUImanager(), G4Threading::G4GetThreadId(), and treeTop.
Referenced by G4UIcommand::G4UIcommandCommonConstructorCode().
void G4UImanager::AddWorkerCommand (G4UIcommand * newCommand) private
Definition at line 294 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 294 of file G4UImanager.cc
References G4UIcommandTree::AddNewCommand(), and treeTop.
Referenced by AddNewCommand().
G4int G4UImanager::ApplyCommand (const char * aCommand)
Definition at line 475 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 475 of file G4UImanager.cc
References bridges, commandStack, G4UIcommand::DoIt(), fAliasNotFound, fCommandNotFound, fCommandSucceeded, fIllegalApplicationState, G4UIcommandTree::FindPath(), G4cout, G4endl, G4Exception(), G4UIcommand::GetFailureDescription(), historyFile, histVec, G4UIcommand::IfCommandFailed(), ignoreCmdNotFound, G4String::index(), G4UIcommand::IsAvailable(), isMaster, G4String::isNull(), JustWarning, maxHistSize, G4String::remove(), G4UIcommand::ResetFailure(), saveHistory, SolveAlias(), stackCommandsForBroadcast, G4UIcommand::ToBeBroadcasted(), treeTop, and verboseLevel.
Referenced by G4UIbridge::ApplyCommand(), PHG4Reco::ApplyCommand(), ApplyCommand(), GammaRayTelRunAction::BeginOfRunAction(), XrayFluoRunAction::BeginOfRunAction(), XrayTelRunAction::BeginOfRunAction(), G4RunManagerKernel::BuildPhysicsTables(), G4TheMTRayTracer::CreateBitMap(), CML2AcceleratorConstruction::design(), CexmcRunManager::DoCommonEventLoop(), G4WorkerRunManager::DoWork(), DMXEventAction::drawTracks(), XrayFluoRunAction::EndOfRunAction(), XrayTelRunAction::EndOfRunAction(), tbbTask::execute(), G4UIGAG::ExecuteCommand(), G4VBasicShell::ExecuteCommand(), G4UIGainServer::ExecuteCommand(), G4RunManager::GeometryHasBeenModified(), Initialize(), PHG4ScoringManager::InitRun(), G4VVisCommand::InterpolateViews(), G4VisManager::IsValidView(), main(), G4WorkerRunManager::ProcessOneEvent(), G4RunManager::ProcessOneEvent(), G4VVisCommand::RefreshIfRequired(), G4RunManager::ReinitializeGeometry(), G4WorkerRunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), G4RunManager::rndmSaveThisRun(), XrayFluoSimulation::RunSimulation(), WLSSteppingAction::SaveRandomStatus(), G4VVisCommandGeometrySet::Set(), LXeDetectorConstruction::SetDefaults(), GammaRayTelDetectorConstruction::SetMagField(), G4VisCommandDrawTree::SetNewValue(), PerspectiveVisActionMessenger::SetNewValue(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4TrackingMessenger::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4EmLowEParametersMessenger::SetNewValue(), G4EmExtraParametersMessenger::SetNewValue(), G4ProcessTableMessenger::SetNewValue(), G4EmParametersMessenger::SetNewValue(), G4VisCommandDrawVolume::SetNewValue(), G4ProcessManagerMessenger::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), G4VisCommandOpen::SetNewValue(), G4VisCommandList::SetNewValue(), G4VisCommandSpecify::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), G4VisCommandViewerFlush::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), G4VisCommandSceneAddTrajectories::SetNewValue(), G4VisCommandGeometrySetVisibility::SetNewValueOnLV(), G4VViewer::SetTouchable(), SignalHandler(), PHG4Reco::StartGui(), G4TheRayTracer::Trace(), and G4TheMTRayTracer::Trace().
G4int G4UImanager::ApplyCommand (const G4String & aCommand)
Definition at line 468 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 468 of file G4UImanager.cc
References ApplyCommand(), and G4String::data().
void G4UImanager::CreateHTML (const char * dir = "/")
Definition at line 699 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 699 of file G4UImanager.cc
References G4UIcommandTree::CreateHTML(), FindDirectory(), G4cerr, and G4endl.
Referenced by export_G4UImanager(), and G4UIcontrolMessenger::SetNewValue().
void G4UImanager::CreateMessenger () private
Definition at line 112 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 112 of file G4UImanager.cc
References CoutMessenger, UImessenger, and UnitsMessenger.
Referenced by G4UImanager(), and GetUIpointer().
G4bool G4UImanager::DoublePrecisionStr () static
Definition at line 186 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 186 of file G4UImanager.cc
References doublePrecisionStr.
Referenced by G4UIcommand::ConvertToString(), and G4UIcontrolMessenger::GetCurrentValue().
void G4UImanager::ExecuteMacroFile (const char * fileName)
Definition at line 311 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 311 of file G4UImanager.cc
References G4UIsession::GetLastReturnCode(), lastRC, session, and G4UIsession::SessionStart().
Referenced by export_G4UImanager(), Foreach(), and G4UIcontrolMessenger::SetNewValue().
G4UIcommandTree * G4UImanager::FindDirectory (const char * dirName) private
Definition at line 604 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 604 of file G4UImanager.cc
References G4String::both, G4UIcommandTree::GetTree(), incremental_prev_tag::idx, G4String::index(), G4String::strip(), and treeTop.
Referenced by CreateHTML(), and ListCommands().
G4String G4UImanager::FindMacroPath (const G4String & fname) const
Definition at line 738 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 738 of file G4UImanager.cc
References FileFound(), test::fname, and searchDirs.
Referenced by Foreach(), and G4UIcontrolMessenger::SetNewValue().
G4UImanager *& G4UImanager::fMasterUImanager () static private
Definition at line 63 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 63 of file G4UImanager.cc
Referenced by AddNewCommand(), GetMasterUIpointer(), RemoveCommand(), and SetMasterUIManager().
void G4UImanager::Foreach (const char * macroFile, const char * variableName, const char * candidates)
Definition at line 395 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 395 of file G4UImanager.cc
References cd, ExecuteMacroFile(), FindMacroPath(), G4Exception(), JustWarning, lastRC, and SetAlias().
Referenced by ForeachS(), and Loop().
void G4UImanager::ForeachS (const char * valueList)
Definition at line 366 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 366 of file G4UImanager.cc
References c1, and Foreach().
Referenced by G4UIcontrolMessenger::SetNewValue().
G4UImanager *& G4UImanager::fUImanager () static private
Definition at line 51 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 51 of file G4UImanager.cc
References G4ThreadLocalStatic.
Referenced by GetUIpointer(), and ~G4UImanager().
G4bool & G4UImanager::fUImanagerHasBeenKilled () static private
Definition at line 57 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UImanager.cc
References G4ThreadLocalStatic.
Referenced by GetUIpointer(), and ~G4UImanager().
std::vector< G4String > * G4UImanager::GetCommandStack ()
Definition at line 753 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 753 of file G4UImanager.cc
References commandStack.
Referenced by G4MTRunManager::PrepareCommandsStack().
G4double G4UImanager::GetCurrentDoubleValue (const char * aCommand, G4int parameterNumber = 1, G4bool reGet = true)
Definition at line 275 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 275 of file G4UImanager.cc
References GetCurrentStringValue(), and t.
G4double G4UImanager::GetCurrentDoubleValue (const char * aCommand, const char * aParameterName, G4bool reGet = true)
Definition at line 263 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 263 of file G4UImanager.cc
References GetCurrentStringValue(), and t.
G4int G4UImanager::GetCurrentIntValue (const char * aCommand, G4int parameterNumber = 1, G4bool reGet = true)
Definition at line 251 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 251 of file G4UImanager.cc
References GetCurrentStringValue(), and t.
Referenced by G4TheRayTracer::Trace(), and G4TheMTRayTracer::Trace().
G4int G4UImanager::GetCurrentIntValue (const char * aCommand, const char * aParameterName, G4bool reGet = true)
Definition at line 239 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 239 of file G4UImanager.cc
References GetCurrentStringValue(), and t.
G4String G4UImanager::GetCurrentStringValue (const char * aCommand, G4int parameterNumber = 1, G4bool reGet = true)
Definition at line 201 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 201 of file G4UImanager.cc
References G4String::append(), GetCurrentValues(), G4String::isNull(), savedCommand, and savedParameters.
Referenced by GetCurrentDoubleValue(), GetCurrentIntValue(), GetCurrentStringValue(), G4DecayTableMessenger::SetCurrentParticle(), G4ParticlePropertyMessenger::SetCurrentParticle(), and G4ProcessManagerMessenger::SetCurrentParticle().
G4String G4UImanager::GetCurrentStringValue (const char * aCommand, const char * aParameterName, G4bool reGet = true)
Definition at line 223 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 223 of file G4UImanager.cc
References GetCurrentStringValue(), GetCurrentValues(), G4UIcommand::GetParameter(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterName(), and savedCommand.
G4String G4UImanager::GetCurrentValues (const char * aCommand)
Definition at line 189 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 189 of file G4UImanager.cc
References G4UIcommandTree::FindPath(), G4cerr, G4endl, G4UIcommand::GetCurrentValue(), savedCommand, and treeTop.
Referenced by export_G4UImanager(), GetCurrentStringValue(), G4UIcontrolMessenger::SetNewValue(), G4VBasicShell::ShowCurrent(), G4UIGAG::ShowCurrent(), and G4UIGainServer::ShowCurrent().
G4UIsession* G4UImanager::GetG4UIWindow () const inline
Definition at line 211 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 211 of file G4UImanager.hh
References g4UIWindow.
Referenced by main().
G4int G4UImanager::GetLastReturnCode () const inline
Definition at line 307 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 307 of file G4UImanager.hh
References lastRC.
Referenced by G4UIcontrolMessenger::SetNewValue().
const G4String& G4UImanager::GetMacroSearchPath () const inline
Definition at line 246 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 246 of file G4UImanager.hh
References searchPath.
Referenced by export_G4UImanager().
G4UImanager * G4UImanager::GetMasterUIpointer () static
Definition at line 85 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 85 of file G4UImanager.cc
References fMasterUImanager().
Referenced by G4UIbridge::G4UIbridge(), and G4UIcommand::G4UIcommandCommonConstructorCode().
G4int G4UImanager::GetMaxHistSize () const inline
Definition at line 241 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 241 of file G4UImanager.hh
References maxHistSize.
Referenced by G4UIcontrolMessenger::GetCurrentValue().
G4int G4UImanager::GetNumberOfHistory () const inline
Definition at line 230 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 230 of file G4UImanager.hh
References histVec.
Referenced by G4VBasicShell::ApplyShellCommand(), G4UIGAG::GetCommand(), and G4UIGainServer::GetCommand().
G4bool G4UImanager::GetPauseAtBeginOfEvent () const inline
Definition at line 195 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 195 of file G4UImanager.hh
References pauseAtBeginOfEvent.
Referenced by export_G4UImanager().
G4bool G4UImanager::GetPauseAtEndOfEvent () const inline
Definition at line 199 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 199 of file G4UImanager.hh
References pauseAtEndOfEvent.
Referenced by export_G4UImanager().
G4String G4UImanager::GetPreviousCommand (G4int i) const inline
Definition at line 232 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 232 of file G4UImanager.hh
References histVec.
Referenced by G4VBasicShell::ApplyShellCommand(), G4UIGAG::GetCommand(), G4UIterminal::GetCommand(), and G4UIGainServer::GetCommand().
G4UIsession* G4UImanager::GetSession () const inline
Definition at line 209 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 209 of file G4UImanager.hh
References session.
Referenced by G4VisCommandReviewKeptEvents::SetNewValue().
G4MTcoutDestination* G4UImanager::GetThreadCout () inline
Definition at line 295 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 295 of file G4UImanager.hh
References threadCout.
G4int G4UImanager::GetThreadID () const inline
Definition at line 280 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 280 of file G4UImanager.hh
References threadID.
G4UIcommandTree* G4UImanager::GetTree () const inline
Definition at line 207 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 207 of file G4UImanager.hh
References treeTop.
Referenced by G4VBasicShell::Complete(), G4CascadeParamMessenger::CreateDirectory(), G4UIGAG::ExecuteCommand(), G4UIGainServer::ExecuteCommand(), export_G4UImanager(), G4VBasicShell::FindCommand(), G4VBasicShell::FindDirectory(), G4UIGAG::FindDirPath(), G4UIGainServer::FindDirPath(), G4UIGAG::G4UIGAG(), G4UIGainServer::G4UIGainServer(), G4VisCommandDrawLogicalVolume::G4VisCommandDrawLogicalVolume(), G4VisCommandDrawVolume::G4VisCommandDrawVolume(), G4VisCommandSceneAddMagneticField::G4VisCommandSceneAddMagneticField(), G4UIGAG::GetCommand(), G4UIGainServer::GetCommand(), G4UIGAG::NotifyCommandUpdate(), G4UIGainServer::NotifyCommandUpdate(), G4UIGAG::NotifyStateChange(), G4UIGainServer::NotifyStateChange(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
G4UImanager * G4UImanager::GetUIpointer () static
Definition at line 72 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4UImanager.cc
References CreateMessenger(), fUImanager(), fUImanagerHasBeenKilled(), and G4UImanager().
Referenced by G4VBasicShell::ApplyShellCommand(), pyG4UImanager::ApplyUICommand_1(), G4MPImanager::BeamOn(), GammaRayTelRunAction::BeginOfRunAction(), XrayFluoRunAction::BeginOfRunAction(), XrayTelRunAction::BeginOfRunAction(), G4RunManagerKernel::BuildPhysicsTables(), CexmcSensitiveDetectorMessenger::CexmcSensitiveDetectorMessenger(), G4VVisCommand::CheckSceneAndNotifyHandlers(), G4VBasicShell::Complete(), G4TheMTRayTracer::CreateBitMap(), G4CascadeParamMessenger::CreateDirectory(), G4UImessenger::CreateDirectory(), CML2AcceleratorConstruction::design(), CexmcRunManager::DoCommonEventLoop(), G4WorkerRunManager::DoWork(), G4BlineEventAction::DrawFieldLines(), DMXEventAction::drawTracks(), XrayFluoRunAction::EndOfRunAction(), XrayTelRunAction::EndOfRunAction(), G4VMPIsession::ExecCommand(), G4UIbatch::ExecCommand(), tbbTask::execute(), G4VBasicShell::ExecuteCommand(), G4MPImanager::ExecuteThreadCommand(), export_G4UImanager(), G4VBasicShell::FindCommand(), G4VBasicShell::FindDirectory(), G4MTRunManager::G4MTRunManager(), G4UIbatch::G4UIbatch(), G4UIcommand::G4UIcommandCommonConstructorCode(), G4UIGAG::G4UIGAG(), G4UIGainServer::G4UIGainServer(), G4UIterminal::G4UIterminal(), G4VisCommandDrawLogicalVolume::G4VisCommandDrawLogicalVolume(), G4VisCommandDrawVolume::G4VisCommandDrawVolume(), G4VisCommandSceneAddMagneticField::G4VisCommandSceneAddMagneticField(), G4WorkerRunManager::G4WorkerRunManager(), G4ZMQServer::G4ZMQServer(), G4RunManager::GeometryHasBeenModified(), G4VisManager::GeometryHasChanged(), G4VUIshell::GetCommandTree(), G4UIcontrolMessenger::GetCurrentValue(), PHG4Reco::Init(), Initialize(), PHG4ScoringManager::InitRun(), PHG4Reco::InitUImanager(), G4VVisCommand::InterpolateViews(), G4VisManager::IsValidView(), main(), G4VisManager::NotifyHandlers(), G4MTRunManager::PrepareCommandsStack(), G4WorkerRunManager::ProcessOneEvent(), G4RunManager::ProcessOneEvent(), G4VVisCommand::RefreshIfRequired(), G4RunManager::ReinitializeGeometry(), LaserDrivenBeamLine::RemoveESS(), LaserDrivenBeamLine::RemoveQuads(), pyglobals::ResetG4PyCoutDestination(), G4WorkerRunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), G4RunManager::rndmSaveThisRun(), XrayFluoSimulation::RunSimulation(), WLSSteppingAction::SaveRandomStatus(), G4MPIbatch::SessionStart(), G4UIbatch::SessionStart(), G4VVisCommandGeometrySet::Set(), G4DecayTableMessenger::SetCurrentParticle(), G4ParticlePropertyMessenger::SetCurrentParticle(), G4ProcessManagerMessenger::SetCurrentParticle(), LXeDetectorConstruction::SetDefaults(), LaserDrivenBeamLine::SetFirstCollimatorPositionZ(), LaserDrivenBeamLine::SetFirstCollimatorRadius(), LaserDrivenBeamLine::SetFirstCollimatorThickness(), pyglobals::SetG4PyCoutDestination(), GammaRayTelDetectorConstruction::SetMagField(), G4VisCommandDrawTree::SetNewValue(), PerspectiveVisActionMessenger::SetNewValue(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandsTouchableSet::SetNewValue(), G4MPImessenger::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4LocalThreadCoutMessenger::SetNewValue(), G4VisCommandSceneHandlerCreate::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4TrackingMessenger::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4EmExtraParametersMessenger::SetNewValue(), G4ProcessTableMessenger::SetNewValue(), G4EmLowEParametersMessenger::SetNewValue(), G4EmParametersMessenger::SetNewValue(), G4VisCommandDrawVolume::SetNewValue(), G4RunMessenger::SetNewValue(), G4ProcessManagerMessenger::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), G4VisCommandOpen::SetNewValue(), G4VisCommandList::SetNewValue(), G4VisCommandSpecify::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), G4VisCommandViewerFlush::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), G4VisCommandSceneAddTrajectories::SetNewValue(), G4VisCommandGeometrySetVisibility::SetNewValueOnLV(), LaserDrivenBeamLine::SetSecondCollimatorPositionZ(), LaserDrivenBeamLine::SetSecondCollimatorRadius(), LaserDrivenBeamLine::SetSecondCollimatorThickness(), LaserDrivenBeamLine::SetSlitHoleDimensionY(), LaserDrivenBeamLine::SetSlitHoleDimensionZ(), LaserDrivenBeamLine::SetSlitHolePositionZ(), LaserDrivenBeamLine::SetThicknessSlit(), G4VViewer::SetTouchable(), G4VBasicShell::ShowCurrent(), SignalHandler(), G4MTRunManagerKernel::StartThread(), G4VBasicShell::TerminalHelp(), G4VViewer::TouchableSetColour(), G4VViewer::TouchableSetVisibility(), G4TheRayTracer::Trace(), G4TheMTRayTracer::Trace(), visio(), G4MPIsession::~G4MPIsession(), G4RunManagerKernel::~G4RunManagerKernel(), G4UIcommand::~G4UIcommand(), G4UIGAG::~G4UIGAG(), G4UIGainServer::~G4UIGainServer(), and G4UIterminal::~G4UIterminal().
G4int G4UImanager::GetVerboseLevel () const inline
Definition at line 228 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 228 of file G4UImanager.hh
References verboseLevel.
Referenced by export_G4UImanager(), G4UIcontrolMessenger::GetCurrentValue(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandDrawVolume::SetNewValue(), G4VisCommandOpen::SetNewValue(), G4VisCommandSpecify::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerFlush::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
void G4UImanager::ListAlias ()
Definition at line 694 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 694 of file G4UImanager.cc
References aliasList, and G4UIaliasList::List().
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4UImanager::ListCommands (const char * direc)
Definition at line 595 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 595 of file G4UImanager.cc
References FindDirectory(), G4cout, G4endl, and G4UIcommandTree::List().
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4UImanager::Loop (const char * macroFile, const char * variableName, G4double initialValue, G4double finalValue, G4double stepSize = 1.0)
Definition at line 342 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 342 of file G4UImanager.cc
References cd, d, and Foreach().
Referenced by LoopS().
void G4UImanager::LoopS (const char * valueList)
Definition at line 322 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4UImanager.cc
References c1, d1, d2, Loop(), and t1.
Referenced by G4UIcontrolMessenger::SetNewValue().
G4bool G4UImanager::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
Definition at line 626 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 626 of file G4UImanager.cc
References G4State_EventProc, G4State_GeomClosed, G4StateManager::GetStateManager(), pauseAtBeginOfEvent, pauseAtEndOfEvent, and PauseSession().
G4bool G4UImanager::operator!= (const G4UImanager & right) const private
Definition at line 181 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 181 of file G4UImanager.cc
const G4UImanager & G4UImanager::operator= (const G4UImanager & right) private
Definition at line 177 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 177 of file G4UImanager.cc
References right.
G4bool G4UImanager::operator== (const G4UImanager & right) const private
Definition at line 179 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 179 of file G4UImanager.cc
void G4UImanager::ParseMacroSearchPath ()
Definition at line 708 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 708 of file G4UImanager.cc
References G4String::index(), searchDirs, and searchPath.
void G4UImanager::PauseSession (const char * msg) private
Definition at line 590 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 590 of file G4UImanager.cc
References G4UIsession::PauseSessionStart(), and session.
Referenced by Notify().
void G4UImanager::RegisterBridge (G4UIbridge * brg)
Definition at line 760 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 760 of file G4UImanager.cc
References bridges, FatalException, G4Exception(), and G4UIbridge::LocalUI().
Referenced by G4UIbridge::G4UIbridge().
void G4UImanager::RemoveAlias (const char * aliasName)
Definition at line 687 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 687 of file G4UImanager.cc
References aliasList, G4String::both, G4UIaliasList::RemoveAlias(), and G4String::strip().
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4UImanager::RemoveCommand (G4UIcommand * aCommand)
Definition at line 299 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 299 of file G4UImanager.cc
References fMasterUImanager(), G4Threading::G4GetThreadId(), G4UIcommandTree::RemoveCommand(), RemoveWorkerCommand(), and treeTop.
Referenced by G4UIcommand::~G4UIcommand().
void G4UImanager::RemoveWorkerCommand (G4UIcommand * aCommand) private
Definition at line 306 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 306 of file G4UImanager.cc
References G4UIcommandTree::RemoveCommand(), and treeTop.
Referenced by RemoveCommand().
void G4UImanager::SetAlias (const char * aliasLine)
Definition at line 668 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 668 of file G4UImanager.cc
References aliasList, G4UIaliasList::ChangeAlias(), and G4String::index().
Referenced by Foreach(), and G4UIcontrolMessenger::SetNewValue().
void G4UImanager::SetCerrFileName (const G4String & fileN = "G4cerr.txt", G4bool ifAppend = true)
Definition at line 804 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 804 of file G4UImanager.cc
References G4MTcoutDestination::SetCerrFileName(), threadCout, and threadID.
Referenced by G4LocalThreadCoutMessenger::SetNewValue().
void G4UImanager::SetCoutDestination (G4UIsession *const value)
Definition at line 662 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 662 of file G4UImanager.cc
References G4cerrbuf, G4coutbuf, and G4strstreambuf::SetDestination().
Referenced by G4UIGAG::G4UIGAG(), G4UImanager(), PHG4Reco::Init(), G4UIGAG::~G4UIGAG(), G4UIGainServer::~G4UIGainServer(), and ~G4UImanager().
void G4UImanager::SetCoutFileName (const G4String & fileN = "G4cout.txt", G4bool ifAppend = true)
Definition at line 789 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 789 of file G4UImanager.cc
References G4MTcoutDestination::SetCoutFileName(), threadCout, and threadID.
Referenced by G4LocalThreadCoutMessenger::SetNewValue().
void G4UImanager::SetG4UIWindow (G4UIsession *const value) inline
Definition at line 216 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 216 of file G4UImanager.hh
References g4UIWindow.
void G4UImanager::SetIgnoreCmdNotFound (G4bool val) inline
Definition at line 270 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 270 of file G4UImanager.hh
References ignoreCmdNotFound.
Referenced by G4WorkerRunManager::G4WorkerRunManager().
void G4UImanager::SetMacroSearchPath (const G4String & path) inline
Definition at line 244 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 244 of file G4UImanager.hh
References searchPath.
Referenced by export_G4UImanager().
void G4UImanager::SetMasterUIManager (G4bool val) inline
Definition at line 259 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 259 of file G4UImanager.hh
References bridges, fMasterUImanager(), isMaster, and stackCommandsForBroadcast.
Referenced by G4MTRunManager::G4MTRunManager().
void G4UImanager::SetMaxHistSize (G4int mx) inline
Definition at line 239 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 239 of file G4UImanager.hh
References maxHistSize, and mx.
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4UImanager::SetPauseAtBeginOfEvent (G4bool vl) inline
Definition at line 193 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 193 of file G4UImanager.hh
References pauseAtBeginOfEvent.
Referenced by export_G4UImanager(), and G4RunMessenger::SetNewValue().
void G4UImanager::SetPauseAtEndOfEvent (G4bool vl) inline
Definition at line 197 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 197 of file G4UImanager.hh
References pauseAtEndOfEvent.
Referenced by export_G4UImanager(), and G4RunMessenger::SetNewValue().
void G4UImanager::SetSession (G4UIsession *const value) inline
Definition at line 214 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 214 of file G4UImanager.hh
References session.
Referenced by G4UIGAG::G4UIGAG(), PHG4Reco::Init(), G4UIGAG::~G4UIGAG(), and G4UIGainServer::~G4UIGainServer().
void G4UImanager::SetThreadIgnore (G4int tid = 0)
Definition at line 833 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 833 of file G4UImanager.cc
References igThreadID, G4MTcoutDestination::SetIgnoreCout(), threadCout, and threadID.
Referenced by G4LocalThreadCoutMessenger::SetNewValue().
void G4UImanager::SetThreadIgnoreInit (G4bool flg = true)
Definition at line 844 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 844 of file G4UImanager.cc
References G4MTcoutDestination::SetIgnoreInit(), threadCout, and threadID.
Referenced by G4LocalThreadCoutMessenger::SetNewValue().
void G4UImanager::SetThreadPrefixString (const G4String & s = "W")
Definition at line 819 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 819 of file G4UImanager.cc
References G4MTcoutDestination::SetPrefixString(), threadCout, and threadID.
Referenced by G4LocalThreadCoutMessenger::SetNewValue().
void G4UImanager::SetThreadUseBuffer (G4bool flg = true)
Definition at line 826 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 826 of file G4UImanager.cc
References G4MTcoutDestination::EnableBuffering(), threadCout, and threadID.
Referenced by G4LocalThreadCoutMessenger::SetNewValue().
void G4UImanager::SetUpForAThread (G4int tId)
Definition at line 771 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 771 of file G4UImanager.cc
References G4iosInitialization(), igThreadID, G4MTcoutDestination::SetIgnoreCout(), threadCout, and threadID.
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
void G4UImanager::SetUpForSpecialThread (G4String aPrefix)
Definition at line 779 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 779 of file G4UImanager.cc
References G4iosInitialization(), G4Threading::G4SetThreadId(), G4Threading::GENERICTHREAD_ID, igThreadID, G4MTcoutDestination::SetIgnoreCout(), G4MTcoutDestination::SetPrefixString(), threadCout, and threadID.
void G4UImanager::SetVerboseLevel (G4int val) inline
Definition at line 226 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 226 of file G4UImanager.hh
References verboseLevel.
Referenced by export_G4UImanager(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandDrawVolume::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), G4VisCommandOpen::SetNewValue(), G4VisCommandSpecify::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerFlush::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
G4String G4UImanager::SolveAlias (const char * aCmd)
Definition at line 420 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 420 of file G4UImanager.cc
References aliasList, G4UIaliasList::FindAlias(), G4cerr, G4endl, G4String::index(), and ps.
Referenced by ApplyCommand(), G4UIterminal::ExecuteCommand(), G4UIGAG::ExecuteCommand(), G4UIGainServer::ExecuteCommand(), and G4UIcontrolMessenger::SetNewValue().
void G4UImanager::StoreHistory (const char * fileName = "G4history.macro")
Definition at line 570 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 570 of file G4UImanager.cc
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4UImanager::StoreHistory (G4bool historySwitch, const char * fileName = "G4history.macro")
Definition at line 573 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 573 of file G4UImanager.cc
References historyFile, and saveHistory.
void G4UImanager::UseDoublePrecisionStr (G4bool val) static
Definition at line 184 of file G4UImanager.cc.
View newest version in sPHENIX GitHub at line 184 of file G4UImanager.cc
References doublePrecisionStr.
Referenced by G4UIcontrolMessenger::SetNewValue().
Member Data Documentation
G4UIaliasList* G4UImanager::aliasList private
Definition at line 164 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 164 of file G4UImanager.hh
Referenced by G4UImanager(), ListAlias(), RemoveAlias(), SetAlias(), SolveAlias(), and ~G4UImanager().
std::vector<G4UIbridge*>* G4UImanager::bridges private
Definition at line 253 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 253 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), RegisterBridge(), SetMasterUIManager(), and ~G4UImanager().
std::vector<G4String>* G4UImanager::commandStack private
Definition at line 256 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 256 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), GetCommandStack(), and ~G4UImanager().
G4LocalThreadCoutMessenger* G4UImanager::CoutMessenger private
Definition at line 157 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 157 of file G4UImanager.hh
Referenced by CreateMessenger(), G4UImanager(), and ~G4UImanager().
G4bool G4UImanager::doublePrecisionStr = false static private
Definition at line 295 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 295 of file G4UImanager.hh
Referenced by DoublePrecisionStr(), and UseDoublePrecisionStr().
G4UIsession* G4UImanager::g4UIWindow private
Definition at line 154 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 154 of file G4UImanager.hh
Referenced by G4UImanager(), GetG4UIWindow(), and SetG4UIWindow().
std::ofstream G4UImanager::historyFile private
Definition at line 161 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 161 of file G4UImanager.hh
Referenced by ApplyCommand(), StoreHistory(), and ~G4UImanager().
std::vector<G4String> G4UImanager::histVec private
Definition at line 163 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 163 of file G4UImanager.hh
Referenced by ApplyCommand(), GetNumberOfHistory(), GetPreviousCommand(), and ~G4UImanager().
G4bool G4UImanager::ignoreCmdNotFound private
Definition at line 254 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 254 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), and SetIgnoreCmdNotFound().
G4int G4UImanager::igThreadID = -1 static private
Definition at line 286 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 286 of file G4UImanager.hh
Referenced by SetThreadIgnore(), SetUpForAThread(), and SetUpForSpecialThread().
G4bool G4UImanager::isMaster private
Definition at line 252 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 252 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), and SetMasterUIManager().
G4int G4UImanager::lastRC private
Definition at line 305 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 305 of file G4UImanager.hh
Referenced by ExecuteMacroFile(), Foreach(), and GetLastReturnCode().
G4int G4UImanager::maxHistSize private
Definition at line 165 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 165 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), GetMaxHistSize(), and SetMaxHistSize().
G4bool G4UImanager::pauseAtBeginOfEvent private
Definition at line 166 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 166 of file G4UImanager.hh
Referenced by G4UImanager(), GetPauseAtBeginOfEvent(), Notify(), and SetPauseAtBeginOfEvent().
G4bool G4UImanager::pauseAtEndOfEvent private
Definition at line 167 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 167 of file G4UImanager.hh
Referenced by G4UImanager(), GetPauseAtEndOfEvent(), Notify(), and SetPauseAtEndOfEvent().
G4UIcommand* G4UImanager::savedCommand private
Definition at line 159 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 159 of file G4UImanager.hh
Referenced by G4UImanager(), GetCurrentStringValue(), and GetCurrentValues().
G4String G4UImanager::savedParameters private
Definition at line 158 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 158 of file G4UImanager.hh
Referenced by G4UImanager(), and GetCurrentStringValue().
G4bool G4UImanager::saveHistory private
Definition at line 162 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 162 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), StoreHistory(), and ~G4UImanager().
std::vector<G4String> G4UImanager::searchDirs private
Definition at line 169 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4UImanager.hh
Referenced by FindMacroPath(), and ParseMacroSearchPath().
G4String G4UImanager::searchPath private
Definition at line 168 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 168 of file G4UImanager.hh
Referenced by G4UImanager(), GetMacroSearchPath(), ParseMacroSearchPath(), and SetMacroSearchPath().
G4UIsession* G4UImanager::session private
Definition at line 153 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4UImanager.hh
Referenced by ExecuteMacroFile(), G4UImanager(), GetSession(), PauseSession(), and SetSession().
G4bool G4UImanager::stackCommandsForBroadcast private
Definition at line 255 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 255 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), and SetMasterUIManager().
G4MTcoutDestination* G4UImanager::threadCout private
Definition at line 285 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 285 of file G4UImanager.hh
Referenced by G4UImanager(), GetThreadCout(), SetCerrFileName(), SetCoutFileName(), SetThreadIgnore(), SetThreadIgnoreInit(), SetThreadPrefixString(), SetThreadUseBuffer(), SetUpForAThread(), SetUpForSpecialThread(), and ~G4UImanager().
G4int G4UImanager::threadID private
Definition at line 284 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 284 of file G4UImanager.hh
Referenced by G4UImanager(), GetThreadID(), SetCerrFileName(), SetCoutFileName(), SetThreadIgnore(), SetThreadIgnoreInit(), SetThreadPrefixString(), SetThreadUseBuffer(), SetUpForAThread(), SetUpForSpecialThread(), and ~G4UImanager().
G4UIcommandTree* G4UImanager::treeTop private
Definition at line 152 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 152 of file G4UImanager.hh
Referenced by AddNewCommand(), AddWorkerCommand(), ApplyCommand(), FindDirectory(), G4UImanager(), GetCurrentValues(), GetTree(), RemoveCommand(), RemoveWorkerCommand(), and ~G4UImanager().
G4UIcontrolMessenger* G4UImanager::UImessenger private
Definition at line 155 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 155 of file G4UImanager.hh
Referenced by CreateMessenger(), G4UImanager(), and ~G4UImanager().
G4UnitsMessenger* G4UImanager::UnitsMessenger private
Definition at line 156 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 156 of file G4UImanager.hh
Referenced by CreateMessenger(), G4UImanager(), and ~G4UImanager().
G4int G4UImanager::verboseLevel private
Definition at line 160 of file G4UImanager.hh.
View newest version in sPHENIX GitHub at line 160 of file G4UImanager.hh
Referenced by ApplyCommand(), G4UImanager(), GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UImanager.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UImanager.cc