ECCE @ EIC Software: G4RunManagerKernel Class Reference
G4RunManagerKernel Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4RunManagerKernel.hh>
Public Types
enum RMKType { sequentialRMK, masterRMK, workerRMK }
Public Member Functions
G4RunManagerKernel ()
virtual ~G4RunManagerKernel ()
void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void WorkerDefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void SetPhysics (G4VUserPhysicsList *uPhys)
void InitializePhysics ()
G4bool RunInitialization (G4bool fakeRun=false)
void RunTermination ()
void WorkerUpdateWorldVolume ()
void UpdateRegion ()
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
void GeometryHasBeenModified ()
void PhysicsHasBeenModified ()
G4EventManager * GetEventManager () const
G4StackManager * GetStackManager () const
G4TrackingManager * GetTrackingManager () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
G4PrimaryTransformer * GetPrimaryTransformer () const
const G4String & GetVersionString () const
void SetVerboseLevel (G4int vl)
void SetGeometryToBeOptimized (G4bool vl)
G4int GetNumberOfParallelWorld () const
void SetNumberOfParallelWorld (G4int i)
G4VUserPhysicsList * GetPhysicsList () const
G4VPhysicalVolume * GetCurrentWorld () const
G4int GetNumberOfStaticAllocators () const
Static Public Member Functions
static G4RunManagerKernel * GetRunManagerKernel ()
Protected Member Functions
G4RunManagerKernel (RMKType rmkType)
void SetupDefaultRegion ()
void SetupPhysics ()
void ResetNavigator ()
void BuildPhysicsTables (G4bool fakeRun)
void CheckRegions ()
virtual void SetupShadowProcess () const
void PropagateGenericIonID ()
Protected Attributes
RMKType runManagerKernelType
G4Region * defaultRegion
G4Region * defaultRegionForParallelWorld
G4bool geometryNeedsToBeClosed
Private Member Functions
void CheckRegularGeometry ()
G4bool ConfirmCoupledTransportation ()
void SetScoreSplitter ()
Private Attributes
G4VUserPhysicsList * physicsList
G4VPhysicalVolume * currentWorld
G4bool geometryInitialized
G4bool physicsInitialized
G4bool geometryToBeOptimized
G4bool physicsNeedsToBeReBuilt
G4int verboseLevel
G4int numberOfParallelWorld
G4EventManager * eventManager
G4ExceptionHandler * defaultExceptionHandler
G4String versionString
G4int numberOfStaticAllocators
Static Private Attributes
static G4ThreadLocal
G4RunManagerKernel * fRunManagerKernel = 0
Detailed Description
Definition at line 67 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RunManagerKernel.hh
Member Enumeration Documentation
enum G4RunManagerKernel::RMKType
Enumerator:
sequentialRMK
masterRMK
workerRMK
Definition at line 85 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RunManagerKernel.hh
Constructor & Destructor Documentation
G4RunManagerKernel::G4RunManagerKernel ()
Definition at line 81 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4RunManagerKernel.cc
References defaultExceptionHandler, defaultRegion, defaultRegionForParallelWorld, G4ParticleTable::entries(), eventManager, FatalException, fRunManagerKernel, G4cout, G4Date, G4endl, G4Exception(), G4State_PreInit, G4Version, G4AllocatorList::GetAllocatorListIfExist(), G4ParticleTable::GetParticle(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ProductionCutsTable::GetProductionCutsTable(), G4StateManager::GetStateManager(), InvalidOperationDetection(), numberOfStaticAllocators, runManagerKernelType, sequentialRMK, G4StateManager::SetNewState(), G4Region::SetProductionCuts(), G4AllocatorList::Size(), and versionString.
G4RunManagerKernel::~G4RunManagerKernel () virtual
Definition at line 274 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 274 of file G4RunManagerKernel.cc
References G4UnitDefinition::ClearUnitsTable(), defaultExceptionHandler, G4AllocatorList::Destroy(), eventManager, fRunManagerKernel, G4cout, G4endl, G4State_Quit, G4AllocatorList::GetAllocatorListIfExist(), G4StateManager::GetCurrentState(), G4NavigationHistoryPool::GetInstance(), G4GeometryManager::GetInstance(), G4TemplateRNGHelper< T >::GetInstanceIfExist(), G4TransportationManager::GetInstanceIfExist(), G4FieldManagerStore::GetInstanceIfExist(), G4ParallelWorldProcessStore::GetInstanceIfExist(), G4PathFinder::GetInstanceIfExist(), G4GeometryManager::GetInstanceIfExist(), G4SDManager::GetSDMpointerIfExist(), G4StateManager::GetStateManager(), G4UImanager::GetUIpointer(), numberOfStaticAllocators, G4GeometryManager::OpenGeometry(), G4NavigationHistoryPool::Print(), runManagerKernelType, G4StateManager::SetNewState(), verboseLevel, and workerRMK.
G4RunManagerKernel::G4RunManagerKernel (RMKType rmkType) protected
Definition at line 151 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 151 of file G4RunManagerKernel.cc
References defaultExceptionHandler, defaultRegion, defaultRegionForParallelWorld, eventManager, FatalException, fRunManagerKernel, G4cout, G4Date, G4endl, G4Exception(), G4State_PreInit, G4Version, G4RegionStore::GetInstance(), G4ProductionCutsTable::GetProductionCutsTable(), G4RegionStore::GetRegion(), G4StateManager::GetStateManager(), G4UnitDefinition::GetUnitsTable(), InvalidOperationDetection(), G4Threading::IsMasterThread(), masterRMK, runManagerKernelType, G4StateManager::SetNewState(), G4Region::SetProductionCuts(), verboseLevel, versionString, and workerRMK.
Member Function Documentation
void G4RunManagerKernel::BuildPhysicsTables (G4bool fakeRun) protected
Definition at line 786 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 786 of file G4RunManagerKernel.cc
References G4UImanager::ApplyCommand(), G4VUserPhysicsList::BuildPhysicsTable(), G4VUserPhysicsList::DumpCutValuesTable(), G4VUserPhysicsList::DumpCutValuesTableIfRequested(), DumpRegion(), G4ProductionCutsTable::GetProductionCutsTable(), G4UImanager::GetUIpointer(), masterRMK, physicsList, physicsNeedsToBeReBuilt, runManagerKernelType, TIMEMORY_AUTO_TIMER, and verboseLevel.
Referenced by RunInitialization().
void G4RunManagerKernel::CheckRegions () protected
Definition at line 810 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 810 of file G4RunManagerKernel.cc
References G4Region::AddRootLogicalVolume(), G4Region::BelongsTo(), currentWorld, defaultRegionForParallelWorld, G4cout, G4endl, G4RegionStore::GetInstance(), G4Region::GetName(), G4TransportationManager::GetNoWorlds(), G4Region::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetRegion(), G4TransportationManager::GetTransportationManager(), G4TransportationManager::GetWorldsIterator(), G4Region::IsInMassGeometry(), G4Region::IsInParallelGeometry(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4Region::SetWorld(), G4Region::UsedInMassGeometry(), and G4Region::UsedInParallelGeometry().
Referenced by InitializePhysics(), and UpdateRegion().
void G4RunManagerKernel::CheckRegularGeometry () private
Definition at line 961 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 961 of file G4RunManagerKernel.cc
References G4LogicalVolumeStore::GetInstance(), pos(), and SetScoreSplitter().
Referenced by RunInitialization().
G4bool G4RunManagerKernel::ConfirmCoupledTransportation () private
Definition at line 982 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 982 of file G4RunManagerKernel.cc
References G4ProcessManager::GetAlongStepProcessVector(), G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), Acts::UnitConstants::pm, G4ParticleTableIterator< K, V >::reset(), theParticleIterator, typeDoIt, and G4ParticleTableIterator< K, V >::value().
void G4RunManagerKernel::DefineWorldVolume (G4VPhysicalVolume * worldVol, G4bool topologyIsChanged = true)
Definition at line 439 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 439 of file G4RunManagerKernel.cc
References G4Region::AddRootLogicalVolume(), currentWorld, defaultRegion, FatalException, G4cout, G4endl, G4Exception(), G4State_Idle, G4State_Init, G4State_PreInit, G4VVisManager::GeometryHasChanged(), geometryInitialized, geometryNeedsToBeClosed, G4VVisManager::GetConcreteInstance(), G4StateManager::GetCurrentState(), G4VPhysicalVolume::GetLogicalVolume(), G4Region::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetRegion(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4TransportationManager::GetTransportationManager(), G4Threading::IsMasterThread(), physicsInitialized, G4StateManager::SetNewState(), G4LogicalVolume::SetRegion(), SetupDefaultRegion(), G4TransportationManager::SetWorldForTracking(), and verboseLevel.
Referenced by G4RunManager::DefineWorldVolume(), G4ErrorRunManagerHelper::InitializeGeometry(), and G4RunManager::InitializeGeometry().
void G4RunManagerKernel::DumpRegion (const G4String & rname) const
Definition at line 883 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 883 of file G4RunManagerKernel.cc
References G4RegionStore::GetInstance(), and G4RegionStore::GetRegion().
Referenced by BuildPhysicsTables(), DumpRegion(), and G4RunManager::DumpRegion().
void G4RunManagerKernel::DumpRegion (G4Region * region = 0) const
Definition at line 889 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 889 of file G4RunManagerKernel.cc
References DumpRegion(), G4BestUnit, G4cerr, G4cout, G4endl, G4Region::GetFastSimulationManager(), G4RegionStore::GetInstance(), G4Region::GetMaterialIterator(), G4Region::GetName(), G4VPhysicalVolume::GetName(), G4Region::GetNumberOfMaterials(), G4Region::GetNumberOfRootVolumes(), G4ProductionCuts::GetProductionCut(), G4Region::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4Region::GetRegionalSteppingAction(), G4Region::GetRootLogicalVolumeIterator(), G4Region::GetUserInformation(), G4Region::GetUserLimits(), G4Region::GetWorldPhysical(), G4Region::IsInMassGeometry(), G4Region::IsInParallelGeometry(), G4Threading::IsWorkerThread(), and G4Region::SetProductionCuts().
void G4RunManagerKernel::GeometryHasBeenModified () inline
Definition at line 163 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4RunManagerKernel.hh
References geometryNeedsToBeClosed.
Referenced by G4RunManager::GeometryHasBeenModified(), G4RunManager::ReinitializeGeometry(), and G4RunManager::SetGeometryToBeOptimized().
G4VPhysicalVolume* G4RunManagerKernel::GetCurrentWorld () const inline
Definition at line 211 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 211 of file G4RunManagerKernel.hh
References currentWorld.
Referenced by G4WorkerRunManager::InitializeGeometry().
G4EventManager* G4RunManagerKernel::GetEventManager () const inline
Definition at line 177 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4RunManagerKernel.hh
References eventManager.
Referenced by G4RunManager::G4RunManager().
G4int G4RunManagerKernel::GetNumberOfParallelWorld () const inline
Definition at line 203 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 203 of file G4RunManagerKernel.hh
References numberOfParallelWorld.
Referenced by G4PhysicsListHelper::AddTransportation(), and G4WorkerRunManager::InitializeGeometry().
G4int G4RunManagerKernel::GetNumberOfStaticAllocators () const inline
Definition at line 221 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 221 of file G4RunManagerKernel.hh
References numberOfStaticAllocators.
Referenced by G4MTRunManager::G4MTRunManager().
G4VUserPhysicsList* G4RunManagerKernel::GetPhysicsList () const inline
Definition at line 208 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 208 of file G4RunManagerKernel.hh
References physicsList.
G4PrimaryTransformer* G4RunManagerKernel::GetPrimaryTransformer () const inline
Definition at line 185 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4RunManagerKernel.hh
References eventManager, and G4EventManager::GetPrimaryTransformer().
Referenced by RunInitialization().
G4RunManagerKernel * G4RunManagerKernel::GetRunManagerKernel () static
Definition at line 78 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 78 of file G4RunManagerKernel.cc
References fRunManagerKernel.
Referenced by G4PhysicsListHelper::AddTransportation(), G4VisManager::Disable(), G4MaterialScanner::DoScan(), G4ExceptionHandler::DumpTrackInfo(), export_G4RunManagerKernel(), G4ErrorRunManagerHelper::G4ErrorRunManagerHelper(), and RE06SteppingVerbose::InitializeTimers().
G4StackManager* G4RunManagerKernel::GetStackManager () const inline
Definition at line 179 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4RunManagerKernel.hh
References eventManager, and G4EventManager::GetStackManager().
G4TrackingManager* G4RunManagerKernel::GetTrackingManager () const inline
Definition at line 181 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4RunManagerKernel.hh
References eventManager, and G4EventManager::GetTrackingManager().
Referenced by G4VisManager::Disable(), G4ExceptionHandler::DumpTrackInfo(), and RE06SteppingVerbose::InitializeTimers().
const G4String& G4RunManagerKernel::GetVersionString () const inline
Definition at line 188 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4RunManagerKernel.hh
References versionString.
Referenced by G4RunManager::GetVersionString().
void G4RunManagerKernel::InitializePhysics ()
Definition at line 581 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 581 of file G4RunManagerKernel.cc
References G4VUserPhysicsList::CheckParticleList(), CheckRegions(), G4VUserPhysicsList::Construct(), FatalException, G4cout, G4endl, G4Exception(), G4State_Idle, G4State_Init, G4State_PreInit, geometryInitialized, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4UnitDefinition::GetUnitsTable(), G4Threading::IsMasterThread(), numberOfParallelWorld, physicsInitialized, physicsList, G4VUserPhysicsList::SetCuts(), G4StateManager::SetNewState(), G4TemplateAutoLock< _Mutex_t >::unlock(), G4VUserPhysicsList::UseCoupledTransportation(), and verboseLevel.
Referenced by G4ErrorRunManagerHelper::InitializePhysics(), and G4RunManager::InitializePhysics().
void G4RunManagerKernel::PhysicsHasBeenModified () inline
Definition at line 169 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4RunManagerKernel.hh
References physicsNeedsToBeReBuilt.
Referenced by G4RunManager::PhysicsHasBeenModified().
void G4RunManagerKernel::PropagateGenericIonID () protected
Definition at line 721 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 721 of file G4RunManagerKernel.cc
References G4ParticleTable::GetGenericIon(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleDefinitionID(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::IsGeneralIon(), particle, G4ParticleTableIterator< K, V >::reset(), G4ParticleDefinition::SetParticleDefinitionID(), and G4ParticleTableIterator< K, V >::value().
Referenced by RunInitialization().
void G4RunManagerKernel::ResetNavigator () protected
Definition at line 745 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 745 of file G4RunManagerKernel.cc
References G4GeometryManager::CloseGeometry(), G4cout, G4endl, geometryNeedsToBeClosed, geometryToBeOptimized, G4GeometryManager::GetInstance(), G4GeometryManager::OpenGeometry(), runManagerKernelType, verboseLevel, and workerRMK.
Referenced by RunInitialization().
G4bool G4RunManagerKernel::RunInitialization (G4bool fakeRun = false)
Definition at line 658 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 658 of file G4RunManagerKernel.cc
References BuildPhysicsTables(), CheckRegularGeometry(), G4PrimaryTransformer::CheckUnknown(), G4Exception(), G4State_GeomClosed, G4State_Idle, G4State_Init, G4VVisManager::GeometryHasChanged(), geometryInitialized, geometryNeedsToBeClosed, G4VVisManager::GetConcreteInstance(), G4StateManager::GetCurrentState(), GetPrimaryTransformer(), G4StateManager::GetStateManager(), G4UnitDefinition::GetUnitsTable(), G4Threading::IsMasterThread(), JustWarning, physicsInitialized, PropagateGenericIonID(), ResetNavigator(), G4StateManager::SetNewState(), SetupShadowProcess(), TIMEMORY_AUTO_TIMER, and UpdateRegion().
Referenced by export_G4RunManagerKernel(), G4WorkerRunManager::RunInitialization(), G4ErrorRunManagerHelper::RunInitialization(), and G4RunManager::RunInitialization().
void G4RunManagerKernel::RunTermination ()
Definition at line 738 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 738 of file G4RunManagerKernel.cc
References G4State_Idle, G4ProductionCutsTable::GetProductionCutsTable(), G4StateManager::GetStateManager(), G4ProductionCutsTable::PhysicsTableUpdated(), runManagerKernelType, G4StateManager::SetNewState(), and workerRMK.
Referenced by G4ErrorRunManagerHelper::RunTermination(), and G4RunManager::RunTermination().
void G4RunManagerKernel::SetGeometryToBeOptimized (G4bool vl) inline
Definition at line 194 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 194 of file G4RunManagerKernel.hh
References geometryNeedsToBeClosed, and geometryToBeOptimized.
Referenced by G4RunManager::SetGeometryToBeOptimized().
void G4RunManagerKernel::SetNumberOfParallelWorld (G4int i) inline
Definition at line 205 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 205 of file G4RunManagerKernel.hh
References numberOfParallelWorld.
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::InitializeGeometry().
void G4RunManagerKernel::SetPhysics (G4VUserPhysicsList * uPhys)
Definition at line 514 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 514 of file G4RunManagerKernel.cc
References G4ParticleTable::DumpTable(), G4ParticleTable::entries(), G4cout, G4endl, G4ParticleTable::GetParticle(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), physicsList, runManagerKernelType, SetupPhysics(), verboseLevel, and workerRMK.
Referenced by G4ErrorRunManagerHelper::InitializePhysics(), and G4RunManager::SetUserInitialization().
void G4RunManagerKernel::SetPrimaryTransformer (G4PrimaryTransformer * pt) inline
Definition at line 183 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 183 of file G4RunManagerKernel.hh
References eventManager, and G4EventManager::SetPrimaryTransformer().
Referenced by G4RunManager::SetPrimaryTransformer().
void G4RunManagerKernel::SetScoreSplitter () private
Definition at line 1002 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 1002 of file G4RunManagerKernel.cc
References G4ProcessManager::AddDiscreteProcess(), G4cout, G4endl, G4ThreadLocal, G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), particle, G4ParticleTableIterator< K, V >::reset(), theParticleIterator, G4ParticleTableIterator< K, V >::value(), and verboseLevel.
Referenced by CheckRegularGeometry().
void G4RunManagerKernel::SetupDefaultRegion () protected
Definition at line 251 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 251 of file G4RunManagerKernel.cc
References defaultRegion, FatalException, G4cout, G4endl, G4Exception(), G4Region::GetNumberOfRootVolumes(), G4Region::GetRootLogicalVolumeIterator(), G4Region::RemoveRootLogicalVolume(), runManagerKernelType, verboseLevel, and workerRMK.
Referenced by DefineWorldVolume().
void G4RunManagerKernel::SetupPhysics () protected
Definition at line 541 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 541 of file G4RunManagerKernel.cc
References G4IonConstructor::ConstructParticle(), G4VUserPhysicsList::ConstructParticle(), G4Geantino::GeantinoDefinition(), G4ParticleTable::GetGenericIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleDefinitionID(), G4ParticleTable::GetParticleTable(), G4UnitDefinition::GetUnitsTable(), G4IonTable::InitializeLightIons(), G4ParticleDefinition::IsGeneralIon(), particle, physicsList, G4ParticleTableIterator< K, V >::reset(), G4ParticleDefinition::SetParticleDefinitionID(), G4ParticleTable::SetReadiness(), and G4ParticleTableIterator< K, V >::value().
Referenced by SetPhysics().
void G4RunManagerKernel::SetupShadowProcess () const protected virtual
Reimplemented in G4MTRunManagerKernel, and G4WorkerRunManagerKernel.
Definition at line 1029 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 1029 of file G4RunManagerKernel.cc
References G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), incremental_prev_tag::idx, Acts::UnitConstants::pm, G4ParticleTableIterator< K, V >::reset(), G4ProcessVector::size(), theParticleIterator, and G4ParticleTableIterator< K, V >::value().
Referenced by RunInitialization(), and G4MTRunManagerKernel::SetupShadowProcess().
void G4RunManagerKernel::SetVerboseLevel (G4int vl) inline
Definition at line 191 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 191 of file G4RunManagerKernel.hh
References verboseLevel.
Referenced by G4ErrorRunManagerHelper::G4ErrorRunManagerHelper(), and G4RunManager::SetVerboseLevel().
void G4RunManagerKernel::UpdateRegion ()
Definition at line 764 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 764 of file G4RunManagerKernel.cc
References CheckRegions(), currentWorld, G4Exception(), G4State_Init, G4StateManager::GetCurrentState(), G4RegionStore::GetInstance(), G4ProductionCutsTable::GetProductionCutsTable(), G4StateManager::GetStateManager(), JustWarning, runManagerKernelType, G4ProductionCutsTable::UpdateCoupleTable(), G4RegionStore::UpdateMaterialList(), and workerRMK.
Referenced by G4MaterialScanner::DoScan(), and RunInitialization().
void G4RunManagerKernel::WorkerDefineWorldVolume (G4VPhysicalVolume * worldVol, G4bool topologyIsChanged = true)
Definition at line 375 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 375 of file G4RunManagerKernel.cc
References currentWorld, FatalException, G4cout, G4endl, G4Exception(), G4State_Idle, G4State_Init, G4State_PreInit, G4VVisManager::GeometryHasChanged(), geometryInitialized, geometryNeedsToBeClosed, G4VVisManager::GetConcreteInstance(), G4StateManager::GetCurrentState(), G4MTRunManager::GetMasterRunManager(), G4MTRunManager::GetMasterWorlds(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4TransportationManager::GetTransportationManager(), G4Threading::IsMasterThread(), physicsInitialized, G4TransportationManager::RegisterWorld(), G4StateManager::SetNewState(), and G4TransportationManager::SetWorldForTracking().
Referenced by G4WorkerRunManager::InitializeGeometry().
void G4RunManagerKernel::WorkerUpdateWorldVolume ()
Definition at line 358 of file G4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 358 of file G4RunManagerKernel.cc
References G4MTRunManager::GetMasterRunManager(), G4MTRunManager::GetMasterWorlds(), G4VPhysicalVolume::GetName(), G4TransportationManager::GetTransportationManager(), G4TransportationManager::IsWorldExisting(), and G4TransportationManager::RegisterWorld().
Referenced by G4WorkerRunManager::ConstructScoringWorlds().
Member Data Documentation
G4VPhysicalVolume* G4RunManagerKernel::currentWorld private
Definition at line 147 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4RunManagerKernel.hh
Referenced by CheckRegions(), DefineWorldVolume(), GetCurrentWorld(), UpdateRegion(), and WorkerDefineWorldVolume().
G4ExceptionHandler* G4RunManagerKernel::defaultExceptionHandler private
Definition at line 156 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4RunManagerKernel.hh
Referenced by G4RunManagerKernel(), and ~G4RunManagerKernel().
G4Region* G4RunManagerKernel::defaultRegion protected
Definition at line 159 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4RunManagerKernel.hh
Referenced by DefineWorldVolume(), G4RunManagerKernel(), and SetupDefaultRegion().
G4Region* G4RunManagerKernel::defaultRegionForParallelWorld protected
Definition at line 160 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4RunManagerKernel.hh
Referenced by CheckRegions(), and G4RunManagerKernel().
G4EventManager* G4RunManagerKernel::eventManager private
Definition at line 155 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4RunManagerKernel.hh
Referenced by G4RunManagerKernel(), GetEventManager(), GetPrimaryTransformer(), GetStackManager(), GetTrackingManager(), SetPrimaryTransformer(), and ~G4RunManagerKernel().
G4ThreadLocal G4RunManagerKernel * G4RunManagerKernel::fRunManagerKernel = 0 static private
Definition at line 75 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RunManagerKernel.hh
Referenced by G4RunManagerKernel(), GetRunManagerKernel(), and ~G4RunManagerKernel().
G4bool G4RunManagerKernel::geometryInitialized private
Definition at line 148 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4RunManagerKernel.hh
Referenced by DefineWorldVolume(), InitializePhysics(), RunInitialization(), and WorkerDefineWorldVolume().
G4bool G4RunManagerKernel::geometryNeedsToBeClosed protected
Definition at line 161 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4RunManagerKernel.hh
Referenced by DefineWorldVolume(), GeometryHasBeenModified(), ResetNavigator(), RunInitialization(), SetGeometryToBeOptimized(), and WorkerDefineWorldVolume().
G4bool G4RunManagerKernel::geometryToBeOptimized private
Definition at line 150 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4RunManagerKernel.hh
Referenced by ResetNavigator(), and SetGeometryToBeOptimized().
G4int G4RunManagerKernel::numberOfParallelWorld private
Definition at line 153 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4RunManagerKernel.hh
Referenced by GetNumberOfParallelWorld(), InitializePhysics(), and SetNumberOfParallelWorld().
G4int G4RunManagerKernel::numberOfStaticAllocators private
Definition at line 218 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 218 of file G4RunManagerKernel.hh
Referenced by G4RunManagerKernel(), GetNumberOfStaticAllocators(), and ~G4RunManagerKernel().
G4bool G4RunManagerKernel::physicsInitialized private
Definition at line 149 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 149 of file G4RunManagerKernel.hh
Referenced by DefineWorldVolume(), InitializePhysics(), RunInitialization(), and WorkerDefineWorldVolume().
G4VUserPhysicsList* G4RunManagerKernel::physicsList private
Definition at line 146 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4RunManagerKernel.hh
Referenced by BuildPhysicsTables(), GetPhysicsList(), InitializePhysics(), SetPhysics(), and SetupPhysics().
G4bool G4RunManagerKernel::physicsNeedsToBeReBuilt private
Definition at line 151 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4RunManagerKernel.hh
Referenced by BuildPhysicsTables(), and PhysicsHasBeenModified().
RMKType G4RunManagerKernel::runManagerKernelType protected
Definition at line 89 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RunManagerKernel.hh
Referenced by BuildPhysicsTables(), G4RunManagerKernel(), ResetNavigator(), RunTermination(), SetPhysics(), SetupDefaultRegion(), UpdateRegion(), and ~G4RunManagerKernel().
G4int G4RunManagerKernel::verboseLevel private
Definition at line 152 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4RunManagerKernel.hh
Referenced by BuildPhysicsTables(), DefineWorldVolume(), G4RunManagerKernel(), InitializePhysics(), ResetNavigator(), SetPhysics(), SetScoreSplitter(), SetupDefaultRegion(), SetVerboseLevel(), and ~G4RunManagerKernel().
G4String G4RunManagerKernel::versionString private
Definition at line 157 of file G4RunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4RunManagerKernel.hh
Referenced by G4RunManagerKernel(), and GetVersionString().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4RunManagerKernel.hh
geant4/tree/geant4-10.6-release/source/run/src/G4RunManagerKernel.cc