ECCE @ EIC Software: G4INCL::Particle Class Reference
G4INCL::Particle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLParticle.hh>
Public Member Functions
Particle ()
Particle (ParticleType t, G4double energy, ThreeVector const &momentum, ThreeVector const &position)
Particle (ParticleType t, ThreeVector const &momentum, ThreeVector const &position)
virtual ~Particle ()
Particle (const Particle &rhs)
Copy constructor.
Particle & operator= (const Particle &rhs)
Assignment operator.
G4INCL::ParticleType getType () const
virtual G4INCL::ParticleSpecies getSpecies () const
Get the particle species.
void setType (ParticleType t)
G4bool isNucleon () const
ParticipantType getParticipantType () const
void setParticipantType (ParticipantType const p)
G4bool isParticipant () const
G4bool isTargetSpectator () const
G4bool isProjectileSpectator () const
virtual void makeParticipant ()
virtual void makeTargetSpectator ()
virtual void makeProjectileSpectator ()
G4bool isPion () const
Is this a pion?
G4bool isEta () const
Is this an eta?
G4bool isOmega () const
Is this an omega?
G4bool isEtaPrime () const
Is this an etaprime?
G4bool isPhoton () const
Is this a photon?
G4bool isResonance () const
Is it a resonance?
G4bool isDelta () const
Is it a Delta?
G4bool isSigma () const
Is this a Sigma?
G4bool isKaon () const
Is this a Kaon?
G4bool isAntiKaon () const
Is this an antiKaon?
G4bool isLambda () const
Is this a Lambda?
G4bool isNucleonorLambda () const
Is this a Nucleon or a Lambda?
G4bool isHyperon () const
Is this an Hyperon?
G4bool isMeson () const
Is this a Meson?
G4bool isBaryon () const
Is this a Baryon?
G4bool isStrange () const
Is this an Strange?
G4int getA () const
Returns the baryon number.
G4int getZ () const
Returns the charge number.
G4int getS () const
Returns the strangeness number.
G4double getBeta () const
ThreeVector boostVector () const
void boost (const ThreeVector &aBoostVector)
void lorentzContract (const ThreeVector &aBoostVector, const ThreeVector &refPos)
Lorentz-contract the particle position around some center.
G4double getMass () const
Get the cached particle mass.
G4double getINCLMass () const
Get the INCL particle mass.
virtual G4double getTableMass () const
Get the tabulated particle mass.
G4double getRealMass () const
Get the real particle mass.
void setRealMass ()
Set the mass of the Particle to its real mass.
void setTableMass ()
Set the mass of the Particle to its table mass.
void setINCLMass ()
Set the mass of the Particle to its table mass.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const
Computes correction on the emission Q-value.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const
Computes correction on the transfer Q-value.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const
Computes correction on the emission Q-value for hypernuclei.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const
Computes correction on the transfer Q-value for hypernuclei.
G4double getInvariantMass () const
Get the the particle invariant mass.
G4double getKineticEnergy () const
Get the particle kinetic energy.
G4double getPotentialEnergy () const
Get the particle potential energy.
void setPotentialEnergy (G4double v)
Set the particle potential energy.
G4double getEnergy () const
void setMass (G4double mass)
void setEnergy (G4double energy)
const G4INCL::ThreeVector & getMomentum () const
virtual G4INCL::ThreeVector getAngularMomentum () const
virtual void setMomentum (const G4INCL::ThreeVector &momentum)
const G4INCL::ThreeVector & getPosition () const
virtual void setPosition (const G4INCL::ThreeVector &position)
G4double getHelicity ()
void setHelicity (G4double h)
void propagate (G4double step)
G4int getNumberOfCollisions () const
Return the number of collisions undergone by the particle.
void setNumberOfCollisions (G4int n)
Set the number of collisions undergone by the particle.
void incrementNumberOfCollisions ()
Increment the number of collisions undergone by the particle.
G4int getNumberOfDecays () const
Return the number of decays undergone by the particle.
void setNumberOfDecays (G4int n)
Set the number of decays undergone by the particle.
void incrementNumberOfDecays ()
Increment the number of decays undergone by the particle.
void setOutOfWell ()
Mark the particle as out of its potential well.
G4bool isOutOfWell () const
Check if the particle is out of its potential well.
void setEmissionTime (G4double t)
G4double getEmissionTime ()
ThreeVector getTransversePosition () const
Transverse component of the position w.r.t. the momentum.
ThreeVector getLongitudinalPosition () const
Longitudinal component of the position w.r.t. the momentum.
const ThreeVector & adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
G4double adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
G4bool isCluster () const
void setFrozenMomentum (const ThreeVector &momentum)
Set the frozen particle momentum.
void setFrozenEnergy (const G4double energy)
Set the frozen particle momentum.
ThreeVector getFrozenMomentum () const
Get the frozen particle momentum.
G4double getFrozenEnergy () const
Get the frozen particle momentum.
ThreeVector getPropagationVelocity () const
Get the propagation velocity of the particle.
void freezePropagation ()
Freeze particle propagation.
void thawPropagation ()
Unfreeze particle propagation.
virtual void rotatePositionAndMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle position and momentum.
virtual void rotatePosition (const G4double angle, const ThreeVector &axis)
Rotate the particle position.
virtual void rotateMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle momentum.
std::string print () const
std::string dump () const
long getID () const
ParticleList const * getParticles () const
G4double getReflectionMomentum () const
Return the reflection momentum.
void setUncorrelatedMomentum (const G4double p)
Set the uncorrelated momentum.
void rpCorrelate ()
Make the particle follow a strict r-p correlation.
void rpDecorrelate ()
Make the particle not follow a strict r-p correlation.
G4double getCosRPAngle () const
Get the cosine of the angle between position and momentum.
G4double getParticleBias () const
Get the particle bias.
void setParticleBias (G4double ParticleBias)
Set the particle bias.
std::vector< G4int > getBiasCollisionVector () const
Get the vector list of biased vertices on the particle path.
void setBiasCollisionVector (std::vector< G4int > BiasCollisionVector)
Set the vector list of biased vertices on the particle path.
G4int getNumberOfKaon () const
Number of Kaon inside de nucleus.
void setNumberOfKaon (const G4int NK)
Static Public Member Functions
static G4double getTotalBias ()
General bias vector function.
static void setINCLBiasVector (std::vector< G4double > NewVector)
static void FillINCLBiasVector (G4double newBias)
static G4double getBiasFromVector (std::vector< G4int > VectorBias)
static std::vector< G4int > MergeVectorBias (Particle const *const p1, Particle const *const p2)
static std::vector< G4int > MergeVectorBias (std::vector< G4int > p1, Particle const *const p2)
Static Public Attributes
static std::vector< G4double > INCLBiasVector
Time ordered vector of all bias applied.
static G4ThreadLocal G4int nextBiasedCollisionID = 0
Protected Member Functions
void swap (Particle &rhs)
Helper method for the assignment operator.
Protected Attributes
G4int theZ
G4int theA
G4int theS
ParticipantType theParticipantType
G4INCL::ParticleType theType
G4double theEnergy
G4double * thePropagationEnergy
G4double theFrozenEnergy
G4INCL::ThreeVector theMomentum
G4INCL::ThreeVector * thePropagationMomentum
G4INCL::ThreeVector theFrozenMomentum
G4INCL::ThreeVector thePosition
G4int nCollisions
G4int nDecays
G4double thePotentialEnergy
long ID
G4bool rpCorrelated
G4double uncorrelatedMomentum
G4double theParticleBias
G4int theNKaon
The number of Kaons inside the nucleus (update during the cascade)
Private Attributes
G4double theHelicity
G4double emissionTime
G4bool outOfWell
std::vector< G4int > theBiasCollisionVector
Time ordered vector of all biased vertices on the particle path.
G4double theMass
Static Private Attributes
static G4ThreadLocal long nextID = 1
Detailed Description
Definition at line 75 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLParticle.hh
Constructor & Destructor Documentation
G4INCL::Particle::Particle ()
Definition at line 59 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 59 of file G4INCLParticle.cc
References ID, and nextID.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::ProjectileRemnant::reset(), and G4INCL::ProjectileRemnant::storeComponents().
G4INCL::Particle::Particle (ParticleType t, G4double energy, ThreeVector const & momentum, ThreeVector const & position)
Definition at line 86 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 86 of file G4INCLParticle.cc
References getInvariantMass(), ID, INCL_WARN, nextID, setMass(), setType(), G4INCL::TargetSpectator, theEnergy, and theParticipantType.
G4INCL::Particle::Particle (ParticleType t, ThreeVector const & momentum, ThreeVector const & position)
Definition at line 114 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 114 of file G4INCLParticle.cc
References energy, ID, INCL_ERROR, isResonance(), G4INCL::ThreeVector::mag2(), nextID, setType(), G4INCL::TargetSpectator, theEnergy, theFrozenEnergy, theMass, theMomentum, and theParticipantType.
virtual G4INCL::Particle::~Particle () inline virtual
Definition at line 80 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 80 of file G4INCLParticle.hh
G4INCL::Particle::Particle (const Particle & rhs) inline
Copy constructor.
Does not copy the particle ID.
Definition at line 86 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 86 of file G4INCLParticle.hh
References ID, nextID, theBiasCollisionVector, theEnergy, theFrozenEnergy, theFrozenMomentum, theMomentum, thePropagationEnergy, and thePropagationMomentum.
Member Function Documentation
G4double G4INCL::Particle::adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
Definition at line 155 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 155 of file G4INCLParticle.cc
References G4INCL::ThreeVector::mag2(), theEnergy, theMass, and theMomentum.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PhaseSpaceKopylov::generate(), and G4INCL::PhaseSpaceRauboldLynch::generateEvent().
const ThreeVector & G4INCL::Particle::adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
Definition at line 142 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 142 of file G4INCLParticle.cc
References INCL_ERROR, G4INCL::ThreeVector::mag2(), print(), theEnergy, theMass, and theMomentum.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::StandardPropagationModel::shootParticle(), and G4INCL::KinematicsUtils::transformToLocalEnergyFrame().
void G4INCL::Particle::boost (const ThreeVector & aBoostVector) inline
Boost the particle using a boost vector.
Example (go to the particle rest frame): particle->boost(particle->boostVector());
Definition at line 422 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 422 of file G4INCLParticle.hh
References alpha, bp, G4INCL::ThreeVector::dot(), G4INCL::ThreeVector::mag2(), theEnergy, and theMomentum.
Referenced by G4INCL::Cluster::boost(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::PhaseSpaceKopylov::generate(), and G4INCL::InteractionAvatar::preInteraction().
ThreeVector G4INCL::Particle::boostVector () const inline
Returns a three vector we can give to the boost() -method.
In order to go to the particle rest frame you need to multiply the boost vector by -1.0.
Definition at line 412 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 412 of file G4INCLParticle.hh
References theEnergy, and theMomentum.
Referenced by G4INCL::PhaseSpaceKopylov::generate(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
std::string G4INCL::Particle::dump () const inline
Definition at line 968 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 968 of file G4INCLParticle.hh
References G4INCL::ThreeVector::dump(), G4INCL::ParticleTable::getName(), ID, theEnergy, theMomentum, thePosition, and theType.
Referenced by G4INCL::ParticleEntryAvatar::dump(), G4INCL::BinaryCollisionAvatar::dump(), G4INCL::DecayAvatar::dump(), and G4INCL::SurfaceAvatar::dump().
void G4INCL::Particle::FillINCLBiasVector (G4double newBias) static
Definition at line 202 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 202 of file G4INCLParticle.cc
References INCLBiasVector, and nextBiasedCollisionID.
Referenced by G4INCL::InteractionAvatar::postInteraction().
void G4INCL::Particle::freezePropagation () inline
Freeze particle propagation.
Make the particle use theFrozenMomentum and theFrozenEnergy for propagation. The normal state can be restored by calling the thawPropagation() method.
Definition at line 908 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 908 of file G4INCLParticle.hh
References theFrozenEnergy, theFrozenMomentum, thePropagationEnergy, and thePropagationMomentum.
G4int G4INCL::Particle::getA () const inline
Returns the baryon number.
Definition at line 393 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 393 of file G4INCLParticle.hh
References theA.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::INCL::continueCascade(), G4INCL::ClusterDecay::decay(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::Nucleus::getConservationBalance(), G4INCL::CoulombNonRelativistic::getCoulombRadius(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::Nucleus::insertParticle(), G4INCL::ClusterDecay::isStable(), G4INCL::INCL::postCascade(), G4INCL::INCL::preCascade(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), G4INCL::INCL::RecoilFunctor::RecoilFunctor(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
virtual G4INCL::ThreeVector G4INCL::Particle::getAngularMomentum () const inline virtual
Get the angular momentum w.r.t. the origin
Reimplemented in G4INCL::Cluster.
Definition at line 800 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 800 of file G4INCLParticle.hh
References theMomentum, thePosition, and G4INCL::ThreeVector::vector().
Referenced by G4INCL::Cluster::getAngularMomentum(), and G4INCL::StandardPropagationModel::shootParticle().
G4double G4INCL::Particle::getBeta () const inline
Definition at line 401 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 401 of file G4INCLParticle.hh
References G4INCL::ThreeVector::mag(), P, theEnergy, and theMomentum.
std::vector<G4int> G4INCL::Particle::getBiasCollisionVector () const inline
Get the vector list of biased vertices on the particle path.
Definition at line 1038 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1038 of file G4INCLParticle.hh
References theBiasCollisionVector.
Referenced by G4INCL::ClusterDecay::decay(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), and MergeVectorBias().
G4double G4INCL::Particle::getBiasFromVector (std::vector< G4int > VectorBias) static
Definition at line 211 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 211 of file G4INCLParticle.cc
References INCLBiasVector.
Referenced by G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::ParticleList::getParticleListBias(), and setBiasCollisionVector().
G4double G4INCL::Particle::getCosRPAngle () const inline
Get the cosine of the angle between position and momentum.
Definition at line 1014 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1014 of file G4INCLParticle.hh
References G4INCL::ThreeVector::dot(), G4INCL::ThreeVector::mag2(), norm, thePosition, and thePropagationMomentum.
Referenced by G4INCL::SurfaceAvatar::initializeRefractionVariables(), and G4INCL::ParticleEntryChannel::particleEnters().
G4double G4INCL::Particle::getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const inline
Computes correction on the emission Q-value.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle emission from a given nucleus. For absorption, the correction is obviously equal to minus the value returned by this function.
Parameters
AParent the mass number of the emitting nucleus
ZParent the charge number of the emitting nucleus
Returns
the correction
Definition at line 602 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 602 of file G4INCLParticle.hh
References G4INCL::ParticleTable::getINCLMass(), getINCLMass(), G4INCL::ParticleTable::getTableMass, getTableMass(), G4INCL::ParticleTable::getTableQValue(), isCluster(), theA, theS, and theZ.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::SurfaceAvatar::getTransmissionProbability(), and G4INCL::TransmissionChannel::initializeKineticEnergyOutside().
G4double G4INCL::Particle::getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const inline
Computes correction on the emission Q-value for hypernuclei.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle emission from a given nucleus. For absorption, the correction is obviously equal to minus the value returned by this function.
Parameters
AParent the mass number of the emitting nucleus
ZParent the charge number of the emitting nucleus
SParent the strangess number of the emitting nucleus
Returns
the correction
Definition at line 678 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 678 of file G4INCLParticle.hh
References G4INCL::ParticleTable::getINCLMass(), getINCLMass(), G4INCL::ParticleTable::getTableMass, getTableMass(), G4INCL::ParticleTable::getTableQValue(), isCluster(), theA, theS, and theZ.
G4double G4INCL::Particle::getEmissionTime () inline
Definition at line 865 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 865 of file G4INCLParticle.hh
References emissionTime.
Referenced by G4INCL::Nucleus::decayOutgoingDeltas().
G4double G4INCL::Particle::getEnergy () const inline
Get the energy of the particle in MeV.
Definition at line 770 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 770 of file G4INCLParticle.hh
References theEnergy.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::DeltaDecayChannel::computeDecayTime(), G4INCL::PionResonanceDecayChannel::computeDecayTime(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::KinematicsUtils::makeBoostVector(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::InteractionAvatar::preInteraction(), G4INCL::InteractionAvatar::preInteractionBlocking(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::StandardPropagationModel::shootComposite(), G4INCL::StandardPropagationModel::shootParticle(), G4INCL::KinematicsUtils::squareTotalEnergyInCM(), and G4INCL::KinematicsUtils::transformToLocalEnergyFrame().
G4double G4INCL::Particle::getFrozenEnergy () const inline
Get the frozen particle momentum.
Definition at line 897 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 897 of file G4INCLParticle.hh
References theFrozenEnergy.
ThreeVector G4INCL::Particle::getFrozenMomentum () const inline
Get the frozen particle momentum.
Definition at line 894 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 894 of file G4INCLParticle.hh
References theFrozenMomentum.
G4double G4INCL::Particle::getHelicity () inline
Definition at line 826 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 826 of file G4INCLParticle.hh
References theHelicity.
Referenced by G4INCL::DeltaDecayChannel::sampleAngles().
long G4INCL::Particle::getID () const inline
Definition at line 981 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 981 of file G4INCLParticle.hh
References ID.
Referenced by G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::ProjectileRemnant::getStoredMomentum(), G4INCL::ParticleEntryChannel::particleEnters(), and G4INCL::ProjectileRemnant::reset().
G4double G4INCL::Particle::getINCLMass () const inline
Get the INCL particle mass.
Definition at line 454 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 454 of file G4INCLParticle.hh
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::ParticleTable::getINCLMass(), INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, theA, theMass, theS, theType, and theZ.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), getEmissionQValueCorrection(), and setINCLMass().
G4double G4INCL::Particle::getInvariantMass () const inline
Get the the particle invariant mass.
Uses the relativistic invariant
Definition at line 748 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 748 of file G4INCLParticle.hh
References G4INCL::ThreeVector::dot(), INCL_ERROR, mass, theEnergy, and theMomentum.
Referenced by G4INCL::Nucleus::finalizeProjectileRemnant(), and Particle().
G4double G4INCL::Particle::getKineticEnergy () const inline
Get the particle kinetic energy.
Definition at line 759 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 759 of file G4INCLParticle.hh
References theEnergy, and theMass.
Referenced by G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth::computePotentialEnergy(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::getConservationBalance(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::CoulombDistortion::maxImpactParameter(), G4INCL::CoulombNonRelativistic::minimumDistance(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::CDPP::processOneParticle(), G4INCL::INCL::RecoilFunctor::RecoilFunctor(), and G4INCL::StandardPropagationModel::shootParticle().
ThreeVector G4INCL::Particle::getLongitudinalPosition () const inline
Longitudinal component of the position w.r.t. the momentum.
Definition at line 873 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 873 of file G4INCLParticle.hh
References G4INCL::ThreeVector::dot(), G4INCL::ThreeVector::mag2(), thePosition, and thePropagationMomentum.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), and getTransversePosition().
G4double G4INCL::Particle::getMass () const inline
Get the cached particle mass.
Definition at line 451 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 451 of file G4INCLParticle.hh
References theMass.
Referenced by G4INCL::DeltaDecayChannel::computeDecayTime(), G4INCL::PionResonanceDecayChannel::computeDecayTime(), G4INCL::SigmaZeroDecayChannel::computeDecayTime(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::InteractionAvatar::enforceEnergyConservation(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::Cluster::freezeInternalMotion(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::PhaseSpaceRauboldLynch::initialize(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::Cluster::internalBoostToCM(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN(), G4INCL::Cluster::print(), G4INCL::ProjectileRemnant::ProjectileRemnant(), and G4INCL::StandardPropagationModel::shootParticle().
const G4INCL::ThreeVector& G4INCL::Particle::getMomentum () const inline
Get the momentum vector.
Definition at line 794 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 794 of file G4INCLParticle.hh
References theMomentum.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::SigmaZeroDecayChannel::computeDecayTime(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::fillEventInfo(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::Nucleus::getConservationBalance(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::ProjectileRemnant::getStoredMomentum(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::KinematicsUtils::makeBoostVector(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::BinaryCollisionAvatar::postInteraction(), G4INCL::InteractionAvatar::preInteraction(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), G4INCL::INCL::RecoilFunctor::RecoilFunctor(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ParticleSampler::sampleParticlesIntoList(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
G4int G4INCL::Particle::getNumberOfCollisions () const inline
Return the number of collisions undergone by the particle.
Definition at line 834 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 834 of file G4INCLParticle.hh
References nCollisions.
Referenced by G4INCL::Cluster::addParticle().
G4int G4INCL::Particle::getNumberOfDecays () const inline
Return the number of decays undergone by the particle.
Definition at line 843 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 843 of file G4INCLParticle.hh
References nDecays.
G4int G4INCL::Particle::getNumberOfKaon () const inline
Number of Kaon inside de nucleus.
Put in the Particle class in order to calculate the "correct" mass of composit particle.
Definition at line 1053 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1053 of file G4INCLParticle.hh
References theNKaon.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), and G4INCL::BinaryCollisionAvatar::postInteraction().
ParticipantType G4INCL::Particle::getParticipantType () const inline
Definition at line 310 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 310 of file G4INCLParticle.hh
References theParticipantType.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar().
G4double G4INCL::Particle::getParticleBias () const inline
Get the particle bias.
Definition at line 1032 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1032 of file G4INCLParticle.hh
References theParticleBias.
ParticleList const* G4INCL::Particle::getParticles () const inline
Return a NULL pointer
Definition at line 986 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 986 of file G4INCLParticle.hh
References INCL_WARN.
const G4INCL::ThreeVector& G4INCL::Particle::getPosition () const inline
Set the position vector.
Definition at line 816 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 816 of file G4INCLParticle.hh
References thePosition.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::CoulombNone::bringToSurface(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::StandardPropagationModel::getReflectionTime(), G4INCL::StandardPropagationModel::getTime(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::BinaryCollisionAvatar::postInteraction(), and G4INCL::ParticleSampler::sampleParticlesIntoList().
G4double G4INCL::Particle::getPotentialEnergy () const inline
Get the particle potential energy.
Definition at line 762 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 762 of file G4INCLParticle.hh
References thePotentialEnergy.
Referenced by G4INCL::Cluster::addParticle(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::InteractionAvatar::preInteractionBlocking(), and G4INCL::CDPP::processOneParticle().
ThreeVector G4INCL::Particle::getPropagationVelocity () const inline
Get the propagation velocity of the particle.
Definition at line 900 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 900 of file G4INCLParticle.hh
References thePropagationMomentum.
Referenced by G4INCL::CoulombNone::bringToSurface(), G4INCL::StandardPropagationModel::getReflectionTime(), and G4INCL::StandardPropagationModel::getTime().
G4double G4INCL::Particle::getRealMass () const inline
Get the real particle mass.
Definition at line 540 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 540 of file G4INCLParticle.hh
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::ParticleTable::getRealMass(), INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, theA, theMass, theS, theType, and theZ.
Referenced by G4INCL::Cluster::getTableMass(), and setRealMass().
G4double G4INCL::Particle::getReflectionMomentum () const inline
Return the reflection momentum.
The reflection momentum is used by calls to getSurfaceRadius to compute the radius of the sphere where the nucleon moves. It is necessary to introduce fuzzy r-p correlations.
Definition at line 997 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 997 of file G4INCLParticle.hh
References G4INCL::ThreeVector::mag(), rpCorrelated, theMomentum, and uncorrelatedMomentum.
Referenced by G4INCL::KinematicsUtils::getLocalEnergy(), and G4INCL::Nucleus::getSurfaceRadius().
G4int G4INCL::Particle::getS () const inline
Returns the strangeness number.
Definition at line 399 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 399 of file G4INCLParticle.hh
References theS.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::ClusterDecay::decay(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::Nucleus::getConservationBalance(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::Nucleus::insertParticle(), G4INCL::ClusterDecay::isStable(), G4INCL::INCL::preCascade(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
virtual G4INCL::ParticleSpecies G4INCL::Particle::getSpecies () const inline virtual
Get the particle species.
Reimplemented in G4INCL::Cluster.
Definition at line 183 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 183 of file G4INCLParticle.hh
References theType.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::CoulombDistortion::maxImpactParameter(), G4INCL::CoulombNonRelativistic::minimumDistance(), and G4INCL::StandardPropagationModel::shootParticle().
virtual G4double G4INCL::Particle::getTableMass () const inline virtual
Get the tabulated particle mass.
Reimplemented in G4INCL::Cluster.
Definition at line 497 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 497 of file G4INCLParticle.hh
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::ParticleTable::getTableMass, G4INCL::ParticleTable::getTableParticleMass, INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, theA, theMass, theS, theType, and theZ.
Referenced by G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), getEmissionQValueCorrection(), getTransferQValueCorrection(), and setTableMass().
G4double G4INCL::Particle::getTotalBias () static
General bias vector function.
Definition at line 300 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 300 of file G4INCLParticle.cc
References INCLBiasVector.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::INCL::postCascade(), and G4INCL::EventInfo::remnantToParticle().
G4double G4INCL::Particle::getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const inline
Computes correction on the transfer Q-value.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle transfer from a given nucleus to another.
Assumes that the receving nucleus is INCL's target nucleus, with the INCL separation energy.
Parameters
AFrom the mass number of the donating nucleus
ZFrom the charge number of the donating nucleus
ATo the mass number of the receiving nucleus
ZTo the charge number of the receiving nucleus
Returns
the correction
Definition at line 642 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 642 of file G4INCLParticle.hh
References G4INCL::ParticleTable::getINCLMass(), getTableMass(), G4INCL::ParticleTable::getTableQValue(), theA, and theZ.
G4double G4INCL::Particle::getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const inline
Computes correction on the transfer Q-value for hypernuclei.
Computes the correction that must be applied to INCL particles in order to obtain the correct Q-value for particle transfer from a given nucleus to another.
Assumes that the receving nucleus is INCL's target nucleus, with the INCL separation energy.
Parameters
AFrom the mass number of the donating nucleus
ZFrom the charge number of the donating nucleus
SFrom the strangess number of the donating nucleus
ATo the mass number of the receiving nucleus
ZTo the charge number of the receiving nucleus
STo the strangess number of the receiving nucleus
Returns
the correction
Definition at line 719 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 719 of file G4INCLParticle.hh
References G4INCL::ParticleTable::getINCLMass(), getTableMass(), G4INCL::ParticleTable::getTableQValue(), theA, theS, and theZ.
ThreeVector G4INCL::Particle::getTransversePosition () const inline
Transverse component of the position w.r.t. the momentum.
Definition at line 868 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 868 of file G4INCLParticle.hh
References getLongitudinalPosition(), and thePosition.
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
G4INCL::ParticleType G4INCL::Particle::getType () const inline
Get the particle type.
See Also
G4INCL::ParticleType
Definition at line 178 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 178 of file G4INCLParticle.hh
References theType.
Referenced by G4INCL::PionResonanceDecayChannel::computeDecayTime(), G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialConstant::computePotentialEnergy(), G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::DecayAvatar::getChannel(), G4INCL::NuclearPotential::INuclearPotential::getFermiEnergy(), G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::NuclearPotential::INuclearPotential::getSeparationEnergy(), G4INCL::Nucleus::getSurfaceRadius(), G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::Nucleus::insertParticle(), G4INCL::ParticleConfig::isPair(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK(), G4INCL::CrossSectionsStrangeness::NDeltaToNLK(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NDeltaToNNKKb(), G4INCL::CrossSectionsStrangeness::NDeltaToNSK(), G4INCL::CrossSectionsStrangeness::NKbToL2pi(), G4INCL::CrossSectionsStrangeness::NKbToLpi(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), G4INCL::CrossSectionsStrangeness::NKToNK(), G4INCL::CrossSectionsStrangeness::NKToNK2pi(), G4INCL::CrossSectionsStrangeness::NKToNKpi(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNOnePi(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsStrangeness::NNToMissingStrangeness(), G4INCL::CrossSectionsINCL46::NNToNDelta(), G4INCL::CrossSectionsMultiPions::NNToNDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaOmega(), G4INCL::CrossSectionsStrangeness::NNToNLK(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaxPi(), G4INCL::CrossSectionsStrangeness::NNToNNKKb(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmega(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaxPi(), G4INCL::CrossSectionsStrangeness::NNToNSK(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness(), G4INCL::CrossSectionsStrangeness::NpiToNKKb(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsStrangeness::NSToNL(), G4INCL::CrossSectionsStrangeness::NSToNS(), G4INCL::CrossSectionsStrangeness::p_pimToSzKz(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToOmegaN(), G4INCL::CrossSectionsMultiPions::piNTot(), and G4INCL::CrossSectionsMultiPions::piNTwoPi().
G4int G4INCL::Particle::getZ () const inline
Returns the charge number.
Definition at line 396 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 396 of file G4INCLParticle.hh
References theZ.
Referenced by G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::Cluster::addParticle(), G4INCL::CoulombNonRelativistic::bringToSurface(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::ClusterDecay::decay(), G4INCL::CoulombNonRelativistic::distortOut(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Nucleus::fillEventInfo(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::Nucleus::getConservationBalance(), G4INCL::CoulombNonRelativistic::getCoulombRadius(), G4INCL::Nucleus::getTransmissionBarrier(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::TransmissionChannel::initializeKineticEnergyOutside(), G4INCL::Nucleus::insertParticle(), G4INCL::ClusterDecay::isStable(), G4INCL::CoulombNonRelativistic::minimumDistance(), G4INCL::INCL::preCascade(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Particle::incrementNumberOfCollisions () inline
Increment the number of collisions undergone by the particle.
Definition at line 840 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 840 of file G4INCLParticle.hh
References nCollisions.
void G4INCL::Particle::incrementNumberOfDecays () inline
Increment the number of decays undergone by the particle.
Definition at line 849 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 849 of file G4INCLParticle.hh
References nDecays.
G4bool G4INCL::Particle::isAntiKaon () const inline
Is this an antiKaon?
Definition at line 372 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 372 of file G4INCLParticle.hh
References G4INCL::KMinus, G4INCL::KZeroBar, and theType.
Referenced by G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), G4INCL::Nucleus::insertParticle(), isMeson(), isStrange(), G4INCL::CrossSectionsStrangeness::NKbelastic(), G4INCL::CrossSectionsStrangeness::NKbToL2pi(), G4INCL::CrossSectionsStrangeness::NKbToLpi(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), and G4INCL::CrossSectionsStrangeness::total().
G4bool G4INCL::Particle::isBaryon () const inline
Is this a Baryon?
Definition at line 387 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 387 of file G4INCLParticle.hh
References isHyperon(), isNucleon(), and isResonance().
Referenced by G4INCL::CDPP::processOneParticle().
G4bool G4INCL::Particle::isCluster () const inline
Definition at line 883 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 883 of file G4INCLParticle.hh
References G4INCL::Composite, and theType.
Referenced by getEmissionQValueCorrection(), and G4INCL::SurfaceAvatar::postInteraction().
G4bool G4INCL::Particle::isDelta () const inline
Is it a Delta?
Definition at line 361 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 361 of file G4INCLParticle.hh
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, and theType.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::CrossSectionsINCL46::elastic(), G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), isResonance(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::RecombinationChannel::RecombinationChannel(), G4INCL::CrossSectionsINCL46::total(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPionsAndResonances::total(), and G4INCL::CrossSectionsMultiPions::total().
G4bool G4INCL::Particle::isEta () const inline
Is this an eta?
Definition at line 346 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 346 of file G4INCLParticle.hh
References G4INCL::Eta, and theType.
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), isMeson(), G4INCL::CrossSectionsStrangeness::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
G4bool G4INCL::Particle::isEtaPrime () const inline
Is this an etaprime?
Definition at line 352 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 352 of file G4INCLParticle.hh
References G4INCL::EtaPrime, and theType.
Referenced by isMeson(), G4INCL::CrossSectionsStrangeness::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
G4bool G4INCL::Particle::isHyperon () const inline
Is this an Hyperon?
Definition at line 381 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 381 of file G4INCLParticle.hh
References isLambda(), and isSigma().
Referenced by G4INCL::CrossSectionsStrangeness::elastic(), isBaryon(), isStrange(), and G4INCL::CrossSectionsStrangeness::NYelastic().
G4bool G4INCL::Particle::isKaon () const inline
Is this a Kaon?
Definition at line 369 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 369 of file G4INCLParticle.hh
References G4INCL::KPlus, G4INCL::KZero, and theType.
Referenced by G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::insertParticle(), isMeson(), isStrange(), G4INCL::CrossSectionsStrangeness::NKelastic(), G4INCL::CrossSectionsStrangeness::NKToNK(), G4INCL::CrossSectionsStrangeness::NKToNK2pi(), G4INCL::CrossSectionsStrangeness::NKToNKpi(), and G4INCL::CrossSectionsStrangeness::total().
G4bool G4INCL::Particle::isLambda () const inline
Is this a Lambda?
Definition at line 375 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 375 of file G4INCLParticle.hh
References G4INCL::Lambda, and theType.
Referenced by G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::Nucleus::getSurfaceRadius(), isHyperon(), isNucleonorLambda(), G4INCL::CrossSectionsStrangeness::NLToNS(), and G4INCL::CrossSectionsStrangeness::total().
G4bool G4INCL::Particle::isMeson () const inline
Is this a Meson?
Definition at line 384 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 384 of file G4INCLParticle.hh
References isAntiKaon(), isEta(), isEtaPrime(), isKaon(), isOmega(), and isPion().
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::InteractionAvatar::preInteractionLocalEnergy(), G4INCL::CDPP::processOneParticle(), and G4INCL::StandardPropagationModel::shootParticle().
G4bool G4INCL::Particle::isNucleon () const inline
Is this a nucleon?
Definition at line 303 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 303 of file G4INCLParticle.hh
References G4INCL::Neutron, G4INCL::Proton, and theType.
Referenced by G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin::computePotentialEnergy(), G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth::computePotentialEnergy(), G4INCL::CrossSectionsINCL46::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), G4INCL::Nucleus::getSurfaceRadius(), G4INCL::Nucleus::insertParticle(), isBaryon(), isNucleonorLambda(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::CrossSectionsMultiPions::piMinuspIne(), G4INCL::CrossSectionsMultiPions::piMinuspOnePi(), G4INCL::CrossSectionsMultiPions::piMinuspTwoPi(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToxPiN(), G4INCL::CrossSectionsMultiPions::piNTwoPi(), G4INCL::CrossSectionsMultiPions::piPluspIne(), G4INCL::CrossSectionsMultiPions::piPluspOnePi(), G4INCL::CrossSectionsMultiPions::piPluspTwoPi(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsINCL46::total(), G4INCL::CrossSectionsMultiPions::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
G4bool G4INCL::Particle::isNucleonorLambda () const inline
Is this a Nucleon or a Lambda?
Definition at line 378 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 378 of file G4INCLParticle.hh
References isLambda(), and isNucleon().
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), and G4INCL::SurfaceAvatar::getChannel().
G4bool G4INCL::Particle::isOmega () const inline
Is this an omega?
Definition at line 349 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 349 of file G4INCLParticle.hh
References G4INCL::Omega, and theType.
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), isMeson(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNInelastic(), G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN(), G4INCL::CrossSectionsStrangeness::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
G4bool G4INCL::Particle::isOutOfWell () const inline
Check if the particle is out of its potential well.
Definition at line 862 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 862 of file G4INCLParticle.hh
References outOfWell.
Referenced by G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy(), and G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy().
G4bool G4INCL::Particle::isParticipant () const inline
Definition at line 318 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 318 of file G4INCLParticle.hh
References G4INCL::Participant, and theParticipantType.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar().
G4bool G4INCL::Particle::isPhoton () const inline
Is this a photon?
Definition at line 355 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 355 of file G4INCLParticle.hh
References G4INCL::Photon, and theType.
G4bool G4INCL::Particle::isPion () const inline
Is this a pion?
Definition at line 343 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 343 of file G4INCLParticle.hh
References G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, and theType.
Referenced by G4INCL::CrossSectionsMultiPions::elastic(), G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::Nucleus::insertParticle(), isMeson(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToMissingStrangeness(), G4INCL::CrossSectionsStrangeness::NpiToNKKb(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNTot(), G4INCL::CrossSectionsINCL46::total(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPions::total(), and G4INCL::CrossSectionsMultiPionsAndResonances::total().
G4bool G4INCL::Particle::isProjectileSpectator () const inline
Definition at line 326 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 326 of file G4INCLParticle.hh
References G4INCL::ProjectileSpectator, and theParticipantType.
Referenced by G4INCL::SurfaceAvatar::getChannel().
G4bool G4INCL::Particle::isResonance () const inline
Is it a resonance?
Definition at line 358 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 358 of file G4INCLParticle.hh
References isDelta().
Referenced by G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::getSurfaceRadius(), isBaryon(), Particle(), G4INCL::CDPP::processOneParticle(), and setType().
G4bool G4INCL::Particle::isSigma () const inline
Is this a Sigma?
Definition at line 366 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 366 of file G4INCLParticle.hh
References G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, and theType.
Referenced by G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::DecayAvatar::getChannel(), isHyperon(), G4INCL::CrossSectionsStrangeness::NSToNL(), G4INCL::CrossSectionsStrangeness::NSToNS(), and G4INCL::CrossSectionsStrangeness::total().
G4bool G4INCL::Particle::isStrange () const inline
Is this an Strange?
Definition at line 390 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 390 of file G4INCLParticle.hh
References isAntiKaon(), isHyperon(), and isKaon().
G4bool G4INCL::Particle::isTargetSpectator () const inline
Definition at line 322 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 322 of file G4INCLParticle.hh
References G4INCL::TargetSpectator, and theParticipantType.
Referenced by G4INCL::SurfaceAvatar::getChannel(), G4INCL::Nucleus::insertParticle(), G4INCL::SurfaceAvatar::postInteraction(), and G4INCL::BinaryCollisionAvatar::preInteraction().
void G4INCL::Particle::lorentzContract (const ThreeVector & aBoostVector, const ThreeVector & refPos) inline
Lorentz-contract the particle position around some center.
Apply Lorentz contraction to the position component along the direction of the boost vector.
Parameters
aBoostVector the boost vector (velocity) [c]
refPos the reference position
Definition at line 440 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 440 of file G4INCLParticle.hh
References G4INCL::ThreeVector::dot(), G4INCL::ThreeVector::mag2(), and thePosition.
virtual void G4INCL::Particle::makeParticipant () inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 330 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 330 of file G4INCLParticle.hh
References G4INCL::Participant, and theParticipantType.
Referenced by G4INCL::Store::loadParticles(), and G4INCL::Cluster::makeParticipant().
virtual void G4INCL::Particle::makeProjectileSpectator () inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 338 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 338 of file G4INCLParticle.hh
References G4INCL::ProjectileSpectator, and theParticipantType.
Referenced by G4INCL::Cluster::makeProjectileSpectator(), and G4INCL::StandardPropagationModel::shootParticle().
virtual void G4INCL::Particle::makeTargetSpectator () inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 334 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 334 of file G4INCLParticle.hh
References G4INCL::TargetSpectator, and theParticipantType.
Referenced by G4INCL::Cluster::makeTargetSpectator().
std::vector< G4int > G4INCL::Particle::MergeVectorBias (Particle const *const p1, Particle const *const p2) static
Definition at line 223 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 223 of file G4INCLParticle.cc
References getBiasCollisionVector().
Referenced by G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::ParticleList::getParticleListBias(), and G4INCL::ParticleList::getParticleListBiasVector().
std::vector< G4int > G4INCL::Particle::MergeVectorBias (std::vector< G4int > p1, Particle const *const p2) static
Definition at line 262 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 262 of file G4INCLParticle.cc
References getBiasCollisionVector().
Particle& G4INCL::Particle::operator= (const Particle & rhs) inline
Assignment operator.
Does not copy the particle ID.
Definition at line 168 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 168 of file G4INCLParticle.hh
References swap().
Referenced by G4INCL::Cluster::operator=().
std::string G4INCL::Particle::print () const inline
Definition at line 953 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 953 of file G4INCLParticle.hh
References G4INCL::ParticleTable::getName(), ID, G4INCL::ThreeVector::print(), theEnergy, theMomentum, thePosition, and theType.
Referenced by adjustMomentumFromEnergy(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::StandardPropagationModel::getReflectionTime(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::CrossSectionsMultiPions::piNTot(), and G4INCL::ProjectileRemnant::removeParticle().
void G4INCL::Particle::propagate (G4double step) inline
Definition at line 829 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 829 of file G4INCLParticle.hh
References thePosition.
Referenced by G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar().
virtual void G4INCL::Particle::rotateMomentum (const G4double angle, const ThreeVector & axis) inline virtual
Rotate the particle momentum.
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Reimplemented in G4INCL::Cluster.
Definition at line 948 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 948 of file G4INCLParticle.hh
References G4INCL::ThreeVector::rotate(), theFrozenMomentum, and theMomentum.
Referenced by G4INCL::Cluster::rotateMomentum(), and rotatePositionAndMomentum().
virtual void G4INCL::Particle::rotatePosition (const G4double angle, const ThreeVector & axis) inline virtual
Rotate the particle position.
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Reimplemented in G4INCL::Cluster.
Definition at line 939 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 939 of file G4INCLParticle.hh
References G4INCL::ThreeVector::rotate(), and thePosition.
Referenced by G4INCL::Cluster::rotatePosition(), and rotatePositionAndMomentum().
virtual void G4INCL::Particle::rotatePositionAndMomentum (const G4double angle, const ThreeVector & axis) inline virtual
Rotate the particle position and momentum.
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Definition at line 929 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 929 of file G4INCLParticle.hh
References rotateMomentum(), and rotatePosition().
Referenced by G4INCL::CoulombNonRelativistic::coulombDeviation().
void G4INCL::Particle::rpCorrelate () inline
Make the particle follow a strict r-p correlation.
Definition at line 1008 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1008 of file G4INCLParticle.hh
References rpCorrelated.
Referenced by G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::ParticleEntryAvatar::postInteraction(), and G4INCL::SurfaceAvatar::postInteraction().
void G4INCL::Particle::rpDecorrelate () inline
Make the particle not follow a strict r-p correlation.
Definition at line 1011 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1011 of file G4INCLParticle.hh
References rpCorrelated.
void G4INCL::Particle::setBiasCollisionVector (std::vector< G4int > BiasCollisionVector) inline
Set the vector list of biased vertices on the particle path.
Definition at line 1041 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1041 of file G4INCLParticle.hh
References getBiasFromVector(), setParticleBias(), and theBiasCollisionVector.
Referenced by G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), and G4INCL::SurfaceAvatar::postInteraction().
void G4INCL::Particle::setEmissionTime (G4double t) inline
Definition at line 864 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 864 of file G4INCLParticle.hh
References emissionTime, and t.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), and G4INCL::Nucleus::finalizeProjectileRemnant().
void G4INCL::Particle::setEnergy (G4double energy) inline
Set the energy of the particle in MeV.
Definition at line 786 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 786 of file G4INCLParticle.hh
References energy, and theEnergy.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::CrossSections::interactionDistanceKbarN(), G4INCL::CrossSections::interactionDistanceKN(), G4INCL::CrossSections::interactionDistanceNN(), G4INCL::CrossSections::interactionDistancePiN(), G4INCL::CrossSections::interactionDistanceYN(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootParticle(), G4INCL::KinematicsUtils::transformToLocalEnergyFrame(), and G4INCL::Nucleus::useFusionKinematics().
void G4INCL::Particle::setFrozenEnergy (const G4double energy) inline
Set the frozen particle momentum.
Definition at line 891 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 891 of file G4INCLParticle.hh
References energy, and theFrozenEnergy.
void G4INCL::Particle::setFrozenMomentum (const ThreeVector & momentum) inline
Set the frozen particle momentum.
Definition at line 888 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 888 of file G4INCLParticle.hh
References momentum, and theFrozenMomentum.
void G4INCL::Particle::setHelicity (G4double h) inline
Definition at line 827 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 827 of file G4INCLParticle.hh
References Acts::UnitConstants::h, and theHelicity.
Referenced by G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), and G4INCL::DeltaDecayChannel::fillFinalState().
void G4INCL::Particle::setINCLBiasVector (std::vector< G4double > NewVector) static
Definition at line 306 of file G4INCLParticle.cc.
View newest version in sPHENIX GitHub at line 306 of file G4INCLParticle.cc
References INCLBiasVector.
void G4INCL::Particle::setINCLMass () inline
Set the mass of the Particle to its table mass.
Definition at line 589 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 589 of file G4INCLParticle.hh
References getINCLMass(), and setMass().
Referenced by G4INCL::Cluster::Cluster(), G4INCL::ParticleEntryChannel::particleEnters(), setType(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Particle::setMass (G4double mass) inline
Set the mass of the particle in MeV/c^2.
Definition at line 778 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 778 of file G4INCLParticle.hh
References mass, and theMass.
Referenced by G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::INCL::makeCompoundNucleus(), Particle(), setINCLMass(), setRealMass(), setTableMass(), and G4INCL::Nucleus::useFusionKinematics().
virtual void G4INCL::Particle::setMomentum (const G4INCL::ThreeVector & momentum) inline virtual
Set the momentum vector.
Definition at line 808 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 808 of file G4INCLParticle.hh
References momentum, and theMomentum.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), G4INCL::PhaseSpaceKopylov::generate(), G4INCL::PhaseSpaceRauboldLynch::generateEvent(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), and G4INCL::Nucleus::useFusionKinematics().
void G4INCL::Particle::setNumberOfCollisions (G4int n) inline
Set the number of collisions undergone by the particle.
Definition at line 837 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 837 of file G4INCLParticle.hh
References n, and nCollisions.
void G4INCL::Particle::setNumberOfDecays (G4int n) inline
Set the number of decays undergone by the particle.
Definition at line 846 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 846 of file G4INCLParticle.hh
References n, and nDecays.
void G4INCL::Particle::setNumberOfKaon (const G4int NK) inline
Definition at line 1054 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1054 of file G4INCLParticle.hh
References theNKaon.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), and G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Particle::setOutOfWell () inline
Mark the particle as out of its potential well.
This flag is used to control pions created outside their potential well in delta decay. The pion potential checks it and returns zero if it is true (necessary in order to correctly enforce energy conservation). The Nucleus::applyFinalState() method uses it to determine whether new avatars should be generated for the particle.
Definition at line 859 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 859 of file G4INCLParticle.hh
References outOfWell.
void G4INCL::Particle::setParticipantType (ParticipantType const p) inline
Definition at line 314 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 314 of file G4INCLParticle.hh
References theParticipantType.
void G4INCL::Particle::setParticleBias (G4double ParticleBias) inline
Set the particle bias.
Definition at line 1035 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1035 of file G4INCLParticle.hh
References theParticleBias.
Referenced by setBiasCollisionVector().
virtual void G4INCL::Particle::setPosition (const G4INCL::ThreeVector & position) inline virtual
Reimplemented in G4INCL::Cluster.
Definition at line 821 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 821 of file G4INCLParticle.hh
References position, and thePosition.
Referenced by G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::CoulombNone::bringToSurface(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::ParticleSampler::sampleParticlesIntoList(), G4INCL::Cluster::setPosition(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Particle::setPotentialEnergy (G4double v) inline
Set the particle potential energy.
Definition at line 765 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 765 of file G4INCLParticle.hh
References thePotentialEnergy, and v.
Referenced by G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::Store::loadParticles(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::TransmissionChannel::particleLeaves(), and G4INCL::Nucleus::updatePotentialEnergy().
void G4INCL::Particle::setRealMass () inline
Set the mass of the Particle to its real mass.
Definition at line 583 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 583 of file G4INCLParticle.hh
References getRealMass(), and setMass().
Referenced by G4INCL::ClusterDecay::decay().
void G4INCL::Particle::setTableMass () inline
Set the mass of the Particle to its table mass.
Definition at line 586 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 586 of file G4INCLParticle.hh
References getTableMass(), and setMass().
Referenced by G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::TransmissionChannel::particleLeaves(), G4INCL::ProjectileRemnant::ProjectileRemnant(), and G4INCL::ProjectileRemnant::reset().
void G4INCL::Particle::setType (ParticleType t) inline
Definition at line 187 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 187 of file G4INCLParticle.hh
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, INCL_ERROR, isResonance(), G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, setINCLMass(), G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, t, theA, theS, theType, theZ, and G4INCL::UnknownParticle.
Referenced by G4INCL::Cluster::Cluster(), G4INCL::ClusterDecay::decay(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NeutralKaonDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), and Particle().
void G4INCL::Particle::setUncorrelatedMomentum (const G4double p) inline
Set the uncorrelated momentum.
Definition at line 1005 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1005 of file G4INCLParticle.hh
References uncorrelatedMomentum.
Referenced by G4INCL::ParticleSampler::sampleOneParticleWithFuzzyRPCorrelation(), and G4INCL::ParticleSampler::sampleOneParticleWithRPCorrelation().
void G4INCL::Particle::swap (Particle & rhs) inline protected
Helper method for the assignment operator.
Definition at line 125 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 125 of file G4INCLParticle.hh
References emissionTime, nCollisions, nDecays, outOfWell, rpCorrelated, boost::swap(), theA, theBiasCollisionVector, theEnergy, theFrozenEnergy, theFrozenMomentum, theHelicity, theMass, theMomentum, theParticipantType, theParticleBias, thePosition, thePotentialEnergy, thePropagationEnergy, thePropagationMomentum, theS, theType, theZ, and uncorrelatedMomentum.
Referenced by operator=(), and G4INCL::Cluster::swap().
void G4INCL::Particle::thawPropagation () inline
Unfreeze particle propagation.
Make the particle use theMomentum and theEnergy for propagation. Call this method to restore the normal propagation if the freezePropagation() method has been called.
Definition at line 919 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 919 of file G4INCLParticle.hh
References theEnergy, theMomentum, thePropagationEnergy, and thePropagationMomentum.
Referenced by G4INCL::ReflectionChannel::fillFinalState().
Member Data Documentation
G4double G4INCL::Particle::emissionTime private
Definition at line 1104 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1104 of file G4INCLParticle.hh
Referenced by getEmissionTime(), setEmissionTime(), and swap().
long G4INCL::Particle::ID protected
Definition at line 1093 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1093 of file G4INCLParticle.hh
Referenced by dump(), getID(), Particle(), G4INCL::Cluster::print(), and print().
std::vector< G4double > G4INCL::Particle::INCLBiasVector static
Time ordered vector of all bias applied.
/!\ Caution /!\ methods Assotiated to G4VectorCache<T> are: Push_back(), operator[], Begin(), End(), Clear(), Size() and Pop_back()
Definition at line 1071 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1071 of file G4INCLParticle.hh
Referenced by FillINCLBiasVector(), getBiasFromVector(), getTotalBias(), G4INCL::INCL::processEvent(), and setINCLBiasVector().
G4int G4INCL::Particle::nCollisions protected
Definition at line 1090 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1090 of file G4INCLParticle.hh
Referenced by G4INCL::Cluster::addParticle(), getNumberOfCollisions(), incrementNumberOfCollisions(), G4INCL::ProjectileRemnant::reset(), setNumberOfCollisions(), swap(), and G4INCL::Cluster::updateClusterParameters().
G4int G4INCL::Particle::nDecays protected
Definition at line 1091 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1091 of file G4INCLParticle.hh
Referenced by getNumberOfDecays(), incrementNumberOfDecays(), setNumberOfDecays(), and swap().
G4ThreadLocal G4int G4INCL::Particle::nextBiasedCollisionID = 0 static
Definition at line 1077 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1077 of file G4INCLParticle.hh
Referenced by FillINCLBiasVector(), G4INCL::InteractionAvatar::postInteraction(), and G4INCL::INCL::processEvent().
G4ThreadLocal long G4INCL::Particle::nextID = 1 static private
Definition at line 1111 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1111 of file G4INCLParticle.hh
Referenced by Particle().
G4bool G4INCL::Particle::outOfWell private
Definition at line 1105 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1105 of file G4INCLParticle.hh
Referenced by isOutOfWell(), setOutOfWell(), and swap().
G4bool G4INCL::Particle::rpCorrelated protected
Definition at line 1095 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1095 of file G4INCLParticle.hh
Referenced by getReflectionMomentum(), rpCorrelate(), rpDecorrelate(), and swap().
G4int G4INCL::Particle::theA protected
Definition at line 1080 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1080 of file G4INCLParticle.hh
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), G4INCL::Nucleus::applyFinalState(), G4INCL::Cluster::Cluster(), G4INCL::Cluster::computeDynamicalPotential(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), getA(), getEmissionQValueCorrection(), getINCLMass(), getRealMass(), G4INCL::Cluster::getSpecies(), getTableMass(), getTransferQValueCorrection(), G4INCL::Cluster::initializeParticles(), G4INCL::Nucleus::insertParticle(), G4INCL::Cluster::internalBoostToCM(), G4INCL::Nucleus::Nucleus(), G4INCL::Cluster::print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), G4INCL::Cluster::setA(), setType(), swap(), and G4INCL::Cluster::updateClusterParameters().
std::vector<G4int> G4INCL::Particle::theBiasCollisionVector private
Time ordered vector of all biased vertices on the particle path.
Definition at line 1108 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1108 of file G4INCLParticle.hh
Referenced by getBiasCollisionVector(), Particle(), setBiasCollisionVector(), and swap().
G4double G4INCL::Particle::theEnergy protected
Definition at line 1083 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1083 of file G4INCLParticle.hh
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), adjustEnergyFromMomentum(), adjustMomentumFromEnergy(), boost(), boostVector(), dump(), getBeta(), getEnergy(), getInvariantMass(), getKineticEnergy(), G4INCL::Cluster::internalBoostToCM(), Particle(), G4INCL::Cluster::print(), print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), setEnergy(), swap(), thawPropagation(), G4INCL::Cluster::updateClusterParameters(), and G4INCL::Nucleus::useFusionKinematics().
G4double G4INCL::Particle::theFrozenEnergy protected
Definition at line 1085 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1085 of file G4INCLParticle.hh
Referenced by freezePropagation(), getFrozenEnergy(), Particle(), setFrozenEnergy(), and swap().
G4INCL::ThreeVector G4INCL::Particle::theFrozenMomentum protected
Definition at line 1088 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1088 of file G4INCLParticle.hh
Referenced by freezePropagation(), getFrozenMomentum(), Particle(), rotateMomentum(), setFrozenMomentum(), and swap().
G4double G4INCL::Particle::theHelicity private
Definition at line 1103 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1103 of file G4INCLParticle.hh
Referenced by getHelicity(), setHelicity(), and swap().
G4double G4INCL::Particle::theMass private
Definition at line 1110 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1110 of file G4INCLParticle.hh
Referenced by adjustEnergyFromMomentum(), adjustMomentumFromEnergy(), getINCLMass(), getKineticEnergy(), getMass(), getRealMass(), getTableMass(), Particle(), setMass(), and swap().
G4INCL::ThreeVector G4INCL::Particle::theMomentum protected
Definition at line 1086 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1086 of file G4INCLParticle.hh
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), adjustEnergyFromMomentum(), adjustMomentumFromEnergy(), boost(), boostVector(), G4INCL::Nucleus::computeRecoilKinematics(), dump(), G4INCL::Cluster::freezeInternalMotion(), getAngularMomentum(), getBeta(), getInvariantMass(), getMomentum(), getReflectionMomentum(), G4INCL::Cluster::internalBoostToCM(), Particle(), G4INCL::Cluster::print(), print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), rotateMomentum(), setMomentum(), swap(), thawPropagation(), G4INCL::Cluster::updateClusterParameters(), and G4INCL::Nucleus::useFusionKinematics().
G4int G4INCL::Particle::theNKaon protected
The number of Kaons inside the nucleus (update during the cascade)
Definition at line 1100 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1100 of file G4INCLParticle.hh
Referenced by G4INCL::Nucleus::emitInsideKaon(), getNumberOfKaon(), and setNumberOfKaon().
ParticipantType G4INCL::Particle::theParticipantType protected
Definition at line 1081 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1081 of file G4INCLParticle.hh
Referenced by getParticipantType(), isParticipant(), isProjectileSpectator(), isTargetSpectator(), makeParticipant(), makeProjectileSpectator(), makeTargetSpectator(), Particle(), setParticipantType(), and swap().
G4double G4INCL::Particle::theParticleBias protected
Definition at line 1098 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1098 of file G4INCLParticle.hh
Referenced by getParticleBias(), setParticleBias(), and swap().
G4INCL::ThreeVector G4INCL::Particle::thePosition protected
Definition at line 1089 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1089 of file G4INCLParticle.hh
Referenced by G4INCL::Cluster::addParticle(), G4INCL::Cluster::boost(), G4INCL::Cluster::Cluster(), G4INCL::Nucleus::computeRecoilKinematics(), dump(), getAngularMomentum(), getCosRPAngle(), getLongitudinalPosition(), getPosition(), getTransversePosition(), G4INCL::Nucleus::initializeParticles(), G4INCL::Cluster::initializeParticles(), G4INCL::Cluster::internalBoostToCM(), lorentzContract(), G4INCL::Cluster::print(), print(), propagate(), G4INCL::ProjectileRemnant::reset(), rotatePosition(), G4INCL::Cluster::setPosition(), setPosition(), swap(), and G4INCL::Cluster::updateClusterParameters().
G4double G4INCL::Particle::thePotentialEnergy protected
Definition at line 1092 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1092 of file G4INCLParticle.hh
Referenced by G4INCL::Cluster::addParticle(), getPotentialEnergy(), G4INCL::ProjectileRemnant::reset(), setPotentialEnergy(), swap(), and G4INCL::Cluster::updateClusterParameters().
G4double* G4INCL::Particle::thePropagationEnergy protected
Definition at line 1084 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1084 of file G4INCLParticle.hh
Referenced by freezePropagation(), Particle(), swap(), and thawPropagation().
G4INCL::ThreeVector* G4INCL::Particle::thePropagationMomentum protected
Definition at line 1087 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1087 of file G4INCLParticle.hh
Referenced by freezePropagation(), getCosRPAngle(), getLongitudinalPosition(), getPropagationVelocity(), Particle(), swap(), and thawPropagation().
G4int G4INCL::Particle::theS protected
Definition at line 1080 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1080 of file G4INCLParticle.hh
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), G4INCL::Nucleus::applyFinalState(), G4INCL::Cluster::Cluster(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), getEmissionQValueCorrection(), getINCLMass(), getRealMass(), getS(), G4INCL::Cluster::getSpecies(), getTableMass(), getTransferQValueCorrection(), G4INCL::Nucleus::insertParticle(), G4INCL::Nucleus::Nucleus(), G4INCL::Cluster::print(), G4INCL::Cluster::setS(), setType(), swap(), and G4INCL::Cluster::updateClusterParameters().
G4INCL::ParticleType G4INCL::Particle::theType protected
Definition at line 1082 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1082 of file G4INCLParticle.hh
Referenced by dump(), getINCLMass(), getRealMass(), getSpecies(), getTableMass(), getType(), isAntiKaon(), isCluster(), isDelta(), isEta(), isEtaPrime(), isKaon(), isLambda(), isNucleon(), isOmega(), isPhoton(), isPion(), isSigma(), G4INCL::Cluster::print(), print(), setType(), and swap().
G4int G4INCL::Particle::theZ protected
Definition at line 1080 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1080 of file G4INCLParticle.hh
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Cluster::addParticle(), G4INCL::Nucleus::applyFinalState(), G4INCL::Cluster::Cluster(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), getEmissionQValueCorrection(), getINCLMass(), getRealMass(), G4INCL::Cluster::getSpecies(), getTableMass(), getTransferQValueCorrection(), G4INCL::Nucleus::getTransmissionBarrier(), getZ(), G4INCL::Cluster::initializeParticles(), G4INCL::Nucleus::insertParticle(), G4INCL::Nucleus::Nucleus(), G4INCL::Cluster::print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::ProjectileRemnant::reset(), setType(), G4INCL::Cluster::setZ(), swap(), and G4INCL::Cluster::updateClusterParameters().
G4double G4INCL::Particle::uncorrelatedMomentum protected
Definition at line 1096 of file G4INCLParticle.hh.
View newest version in sPHENIX GitHub at line 1096 of file G4INCLParticle.hh
Referenced by getReflectionMomentum(), setUncorrelatedMomentum(), and swap().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLParticle.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLParticle.cc