ECCE @ EIC Software: G4XXXSceneHandler Class Reference
G4XXXSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXSceneHandler.hh>
Public Member Functions
G4XXXSceneHandler (G4VGraphicsSystem &system, const G4String &name)
virtual ~G4XXXSceneHandler ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Polymarker &polymarker)
void AddPrimitive (const G4Scale &scale)
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void AddSolid (const G4Box &)
virtual void AddSolid (const G4Cons &)
virtual void AddSolid (const G4Orb &)
virtual void AddSolid (const G4Para &)
virtual void AddSolid (const G4Sphere &)
virtual void AddSolid (const G4Torus &)
virtual void AddSolid (const G4Trap &)
virtual void AddSolid (const G4Trd &)
virtual void AddSolid (const G4Tubs &)
virtual void AddSolid (const G4Ellipsoid &)
virtual void AddSolid (const G4Polycone &)
virtual void AddSolid (const G4Polyhedra &)
virtual void AddSolid (const G4TessellatedSolid &)
virtual void AddSolid (const G4VSolid &)
virtual void AddCompound (const G4VTrajectory &)
virtual void AddCompound (const G4VHit &)
virtual void AddCompound (const G4VDigi &)
virtual void AddCompound (const G4THitsMap< G4double > &)
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
virtual void ClearTransientStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Static Protected Attributes
static G4int fSceneIdCount = 0
Friends
class G4XXXViewer
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Definition at line 40 of file G4XXXSceneHandler.hh.
View newest version in sPHENIX GitHub at line 40 of file G4XXXSceneHandler.hh
Constructor & Destructor Documentation
G4XXXSceneHandler::G4XXXSceneHandler (G4VGraphicsSystem & system, const G4String & name)
Definition at line 49 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 49 of file G4XXXSceneHandler.cc
G4XXXSceneHandler::~G4XXXSceneHandler () virtual
Definition at line 54 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 54 of file G4XXXSceneHandler.cc
Member Function Documentation
void G4XXXSceneHandler::AddPrimitive (const G4Polyline &) virtual
Implements G4VSceneHandler.
Definition at line 84 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 84 of file G4XXXSceneHandler.cc
References G4cout, and G4endl.
void G4XXXSceneHandler::AddPrimitive (const G4Text &) virtual
Implements G4VSceneHandler.
Definition at line 102 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 102 of file G4XXXSceneHandler.cc
References G4cout, and G4endl.
void G4XXXSceneHandler::AddPrimitive (const G4Circle &) virtual
Implements G4VSceneHandler.
Definition at line 122 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 122 of file G4XXXSceneHandler.cc
References G4cout, G4endl, G4VSceneHandler::GetMarkerSize(), G4VSceneHandler::screen, and G4VSceneHandler::world.
void G4XXXSceneHandler::AddPrimitive (const G4Square &) virtual
Implements G4VSceneHandler.
Definition at line 154 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 154 of file G4XXXSceneHandler.cc
References G4cout, G4endl, G4VSceneHandler::GetMarkerSize(), G4VSceneHandler::screen, square(), and G4VSceneHandler::world.
void G4XXXSceneHandler::AddPrimitive (const G4Polyhedron & polyhedron) virtual
Implements G4VSceneHandler.
Definition at line 186 of file G4XXXSceneHandler.cc.
View newest version in sPHENIX GitHub at line 186 of file G4XXXSceneHandler.cc
References G4VSceneHandler::fpViewer, G4cout, G4endl, G4VSceneHandler::GetDrawingStyle(), HepPolyhedron::GetNoFacets(), G4Visible::GetVisAttributes(), G4ViewParameters::hlr, G4ViewParameters::hsr, and G4ViewParameters::wireframe.
void G4XXXSceneHandler::AddPrimitive (const G4Polymarker & polymarker) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 60 of file G4XXXSceneHandler.hh.
View newest version in sPHENIX GitHub at line 60 of file G4XXXSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4XXXSceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 62 of file G4XXXSceneHandler.hh.
View newest version in sPHENIX GitHub at line 62 of file G4XXXSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
Friends And Related Function Documentation
friend class G4XXXViewer friend
Definition at line 42 of file G4XXXSceneHandler.hh.
View newest version in sPHENIX GitHub at line 42 of file G4XXXSceneHandler.hh
Member Data Documentation
G4int G4XXXSceneHandler::fSceneIdCount = 0 static protected
Definition at line 67 of file G4XXXSceneHandler.hh.
View newest version in sPHENIX GitHub at line 67 of file G4XXXSceneHandler.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/XXX/src/G4XXXSceneHandler.cc