ECCE @ EIC Software: G4ErrorTarget Class Reference
G4ErrorTarget Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4ErrorTarget.hh>
Public Member Functions
G4ErrorTarget ()
virtual ~G4ErrorTarget ()
virtual G4double GetDistanceFromPoint (const G4ThreeVector &, const G4ThreeVector &) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &) const
virtual G4bool TargetReached (const G4Step *)
virtual void Dump (const G4String &msg) const =0
G4ErrorTargetType GetType () const
Protected Attributes
G4ErrorTargetType theType
Detailed Description
Definition at line 46 of file G4ErrorTarget.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ErrorTarget.hh
Constructor & Destructor Documentation
G4ErrorTarget::G4ErrorTarget ()
Definition at line 33 of file G4ErrorTarget.cc.
View newest version in sPHENIX GitHub at line 33 of file G4ErrorTarget.cc
G4ErrorTarget::~G4ErrorTarget () virtual
Definition at line 35 of file G4ErrorTarget.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ErrorTarget.cc
Member Function Documentation
virtual void G4ErrorTarget::Dump (const G4String & msg) const pure virtual
Implemented in G4ErrorTrackLengthTarget, G4ErrorCylSurfaceTarget, G4ErrorPlaneSurfaceTarget, G4ErrorSurfaceTarget, G4ErrorGeomVolumeTarget, and G4ErrorTanPlaneTarget.
Referenced by G4ErrorPropagationNavigator::ComputeStep(), and G4ErrorPropagator::Propagate().
G4double G4ErrorTarget::GetDistanceFromPoint (const G4ThreeVector & , const G4ThreeVector &) const virtual
Reimplemented in G4ErrorTrackLengthTarget, G4ErrorPlaneSurfaceTarget, G4ErrorCylSurfaceTarget, and G4ErrorSurfaceTarget.
Definition at line 37 of file G4ErrorTarget.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ErrorTarget.cc
References DBL_MAX.
Referenced by G4ErrorPropagationNavigator::ComputeStep(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), and G4ErrorPropagationNavigator::TargetSafetyFromPoint().
G4double G4ErrorTarget::GetDistanceFromPoint (const G4ThreeVector &) const virtual
Reimplemented in G4ErrorTrackLengthTarget, G4ErrorPlaneSurfaceTarget, G4ErrorCylSurfaceTarget, and G4ErrorSurfaceTarget.
Definition at line 43 of file G4ErrorTarget.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ErrorTarget.cc
References DBL_MAX.
G4ErrorTargetType G4ErrorTarget::GetType () const inline
Definition at line 74 of file G4ErrorTarget.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ErrorTarget.hh
References theType.
Referenced by G4ErrorPropagator::GetFinalTrajState(), G4ErrorPropagationNavigator::GetGlobalExitNormal(), and G4ErrorPropagator::MakeOneStep().
G4bool G4ErrorTarget::TargetReached (const G4Step *) virtual
Reimplemented in G4ErrorGeomVolumeTarget.
Definition at line 48 of file G4ErrorTarget.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ErrorTarget.cc
Member Data Documentation
G4ErrorTargetType G4ErrorTarget::theType protected
Definition at line 69 of file G4ErrorTarget.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ErrorTarget.hh
Referenced by G4ErrorCylSurfaceTarget::G4ErrorCylSurfaceTarget(), G4ErrorGeomVolumeTarget::G4ErrorGeomVolumeTarget(), G4ErrorPlaneSurfaceTarget::G4ErrorPlaneSurfaceTarget(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), and GetType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4ErrorTarget.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4ErrorTarget.cc