ECCE @ EIC Software: G4LogicalSkinSurface Class Reference
G4LogicalSkinSurface Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4LogicalSkinSurface.hh>
Public Member Functions
G4LogicalSkinSurface (const G4String &name, G4LogicalVolume *vol, G4SurfaceProperty *surfaceProperty)
~G4LogicalSkinSurface ()
G4LogicalSkinSurface (const G4LogicalSkinSurface &)=delete
G4LogicalSkinSurface & operator= (const G4LogicalSkinSurface &)=delete
G4bool operator== (const G4LogicalSkinSurface &right) const
G4bool operator!= (const G4LogicalSkinSurface &right) const
const G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *vol)
Public Member Functions inherited from G4LogicalSurface
G4SurfaceProperty * GetSurfaceProperty () const
void SetSurfaceProperty (G4SurfaceProperty *ptrSurfaceProperty)
const G4String & GetName () const
void SetName (const G4String &name)
G4TransitionRadiationSurface * GetTransitionRadiationSurface () const
void SetTransitionRadiationSurface (G4TransitionRadiationSurface *trs)
virtual ~G4LogicalSurface ()
G4LogicalSurface (const G4LogicalSurface &)=delete
G4LogicalSurface & operator= (const G4LogicalSurface &)=delete
G4bool operator== (const G4LogicalSurface &right) const
G4bool operator!= (const G4LogicalSurface &right) const
Static Public Member Functions
static G4LogicalSkinSurface * GetSurface (const G4LogicalVolume *vol)
static void CleanSurfaceTable ()
static const
G4LogicalSkinSurfaceTable * GetSurfaceTable ()
static size_t GetNumberOfSkinSurfaces ()
static void DumpInfo ()
Private Attributes
G4LogicalVolume * LogVolume
Static Private Attributes
static G4LogicalSkinSurfaceTable * theSkinSurfaceTable = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4LogicalSurface
G4LogicalSurface (const G4String &name, G4SurfaceProperty *prop)
Detailed Description
Definition at line 48 of file G4LogicalSkinSurface.hh.
View newest version in sPHENIX GitHub at line 48 of file G4LogicalSkinSurface.hh
Constructor & Destructor Documentation
G4LogicalSkinSurface::G4LogicalSkinSurface (const G4String & name, G4LogicalVolume * vol, G4SurfaceProperty * surfaceProperty)
Definition at line 43 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 43 of file G4LogicalSkinSurface.cc
References theSkinSurfaceTable.
G4LogicalSkinSurface::~G4LogicalSkinSurface ()
Definition at line 58 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 58 of file G4LogicalSkinSurface.cc
G4LogicalSkinSurface::G4LogicalSkinSurface (const G4LogicalSkinSurface &) delete
Member Function Documentation
void G4LogicalSkinSurface::CleanSurfaceTable () static
Definition at line 135 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 135 of file G4LogicalSkinSurface.cc
References pos(), and theSkinSurfaceTable.
Referenced by WLSDetectorConstruction::Construct().
void G4LogicalSkinSurface::DumpInfo () static
Definition at line 116 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 116 of file G4LogicalSkinSurface.cc
References G4cout, G4endl, GetNumberOfSkinSurfaces(), pos(), and theSkinSurfaceTable.
const G4LogicalVolume* G4LogicalSkinSurface::GetLogicalVolume () const inline
Referenced by PHG4GDMLWriteStructure::SkinSurfaceCache(), and G4GDMLWriteStructure::SkinSurfaceCache().
size_t G4LogicalSkinSurface::GetNumberOfSkinSurfaces () static
Definition at line 91 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 91 of file G4LogicalSkinSurface.cc
References theSkinSurfaceTable.
Referenced by DumpInfo(), PHG4GDMLWriteStructure::GetSkinSurface(), and G4GDMLWriteStructure::GetSkinSurface().
G4LogicalSkinSurface * G4LogicalSkinSurface::GetSurface (const G4LogicalVolume * vol) static
Definition at line 101 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 101 of file G4LogicalSkinSurface.cc
References pos(), and theSkinSurfaceTable.
Referenced by OpNoviceDetectorConstruction::Construct(), and G4OpBoundaryProcess::PostStepDoIt().
const G4LogicalSkinSurfaceTable * G4LogicalSkinSurface::GetSurfaceTable () static
Definition at line 82 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 82 of file G4LogicalSkinSurface.cc
References theSkinSurfaceTable.
Referenced by PHG4GDMLWriteStructure::GetSkinSurface(), and G4GDMLWriteStructure::GetSkinSurface().
G4bool G4LogicalSkinSurface::operator!= (const G4LogicalSkinSurface & right) const
Definition at line 73 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 73 of file G4LogicalSkinSurface.cc
G4LogicalSkinSurface& G4LogicalSkinSurface::operator= (const G4LogicalSkinSurface &) delete
G4bool G4LogicalSkinSurface::operator== (const G4LogicalSkinSurface & right) const
Definition at line 67 of file G4LogicalSkinSurface.cc.
View newest version in sPHENIX GitHub at line 67 of file G4LogicalSkinSurface.cc
void G4LogicalSkinSurface::SetLogicalVolume (G4LogicalVolume * vol) inline
Member Data Documentation
G4LogicalVolume* G4LogicalSkinSurface::LogVolume private
Definition at line 80 of file G4LogicalSkinSurface.hh.
View newest version in sPHENIX GitHub at line 80 of file G4LogicalSkinSurface.hh
G4LogicalSkinSurfaceTable * G4LogicalSkinSurface::theSkinSurfaceTable = nullptr static private
Definition at line 83 of file G4LogicalSkinSurface.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LogicalSkinSurface.hh
Referenced by CleanSurfaceTable(), DumpInfo(), G4LogicalSkinSurface(), GetNumberOfSkinSurfaces(), GetSurface(), and GetSurfaceTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4LogicalSkinSurface.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4LogicalSkinSurface.cc