ECCE @ EIC Software: G4EMDissociationCrossSection Class Reference
G4EMDissociationCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4EMDissociationCrossSection.hh>
Public Member Functions
G4EMDissociationCrossSection ()
~G4EMDissociationCrossSection ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *)
G4PhysicsFreeVector * GetCrossSectionForProjectile (G4double, G4double, G4double, G4double, G4double, G4double)
G4PhysicsFreeVector * GetCrossSectionForTarget (G4double, G4double, G4double, G4double, G4double, G4double)
G4double GetWilsonProbabilityForProtonDissociation (G4double, G4double)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4EMDissociationSpectrum * thePhotonSpectrum
G4double r0
G4double J
G4double Qprime
G4double epsilon
G4double xd
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 79 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 79 of file G4EMDissociationCrossSection.hh
Constructor & Destructor Documentation
G4EMDissociationCrossSection::G4EMDissociationCrossSection ()
Definition at line 79 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 79 of file G4EMDissociationCrossSection.cc
References epsilon, fermi, J, MeV, Qprime, r0, thePhotonSpectrum, and xd.
G4EMDissociationCrossSection::~G4EMDissociationCrossSection ()
Definition at line 98 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 98 of file G4EMDissociationCrossSection.cc
References thePhotonSpectrum.
Member Function Documentation
G4PhysicsFreeVector * G4EMDissociationCrossSection::GetCrossSectionForProjectile (G4double AP, G4double ZP, G4double , G4double ZT, G4double b, G4double bmin)
Definition at line 165 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 165 of file G4EMDissociationCrossSection.cc
References source.hepunit::amu_c2, epsilon, G4EMDissociationSpectrum::GetGeneralE1Spectrum(), G4EMDissociationSpectrum::GetGeneralE2Spectrum(), G4Pow::GetInstance(), source.hepunit::hbarc, J, MeV, microbarn, millibarn, G4Pow::powA(), G4PhysicsFreeVector::PutValue(), Qprime, r0, thePhotonSpectrum, and Acts::UnitConstants::u.
Referenced by GetCrossSectionForTarget().
G4PhysicsFreeVector * G4EMDissociationCrossSection::GetCrossSectionForTarget (G4double AP, G4double ZP, G4double AT, G4double ZT, G4double b, G4double bmin)
Definition at line 218 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 218 of file G4EMDissociationCrossSection.cc
References GetCrossSectionForProjectile().
G4double G4EMDissociationCrossSection::GetElementCrossSection (const G4DynamicParticle * theDynamicParticle, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 125 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 125 of file G4EMDissociationCrossSection.cc
References b, CLHEP::HepLorentzVector::beta(), G4DynamicParticle::Get4Momentum(), G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), and G4NistManager::Instance().
G4double G4EMDissociationCrossSection::GetWilsonProbabilityForProtonDissociation (G4double A, G4double Z)
Definition at line 232 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 232 of file G4EMDissociationCrossSection.cc
References A(), and G4Exp().
G4bool G4EMDissociationCrossSection::IsElementApplicable (const G4DynamicParticle * part, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 105 of file G4EMDissociationCrossSection.cc.
View newest version in sPHENIX GitHub at line 105 of file G4EMDissociationCrossSection.cc
References G4DynamicParticle::GetDefinition(), and G4ParticleTable::GetParticleTable().
Member Data Documentation
G4double G4EMDissociationCrossSection::epsilon private
Definition at line 103 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 103 of file G4EMDissociationCrossSection.hh
Referenced by G4EMDissociationCrossSection(), and GetCrossSectionForProjectile().
G4double G4EMDissociationCrossSection::J private
Definition at line 101 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 101 of file G4EMDissociationCrossSection.hh
Referenced by G4EMDissociationCrossSection(), and GetCrossSectionForProjectile().
G4double G4EMDissociationCrossSection::Qprime private
Definition at line 102 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 102 of file G4EMDissociationCrossSection.hh
Referenced by G4EMDissociationCrossSection(), and GetCrossSectionForProjectile().
G4double G4EMDissociationCrossSection::r0 private
Definition at line 100 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 100 of file G4EMDissociationCrossSection.hh
Referenced by G4EMDissociationCrossSection(), and GetCrossSectionForProjectile().
G4EMDissociationSpectrum* G4EMDissociationCrossSection::thePhotonSpectrum private
Definition at line 99 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 99 of file G4EMDissociationCrossSection.hh
Referenced by G4EMDissociationCrossSection(), GetCrossSectionForProjectile(), and ~G4EMDissociationCrossSection().
G4double G4EMDissociationCrossSection::xd private
Definition at line 104 of file G4EMDissociationCrossSection.hh.
View newest version in sPHENIX GitHub at line 104 of file G4EMDissociationCrossSection.hh
Referenced by G4EMDissociationCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4EMDissociationCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4EMDissociationCrossSection.cc