ECCE @ EIC Software: CLHEP::RandGamma Class Reference
CLHEP::RandGamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGamma.h>
Public Member Functions
RandGamma (HepRandomEngine &anEngine, double k=1.0, double lambda=1.0)
RandGamma (HepRandomEngine *anEngine, double k=1.0, double lambda=1.0)
virtual ~RandGamma ()
double fire ()
double fire (double k, double lambda)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double k, double lambda)
double operator() ()
double operator() (double k, double lambda)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double k, double lambda)
static void shootArray (const int size, double *vect, double k=1.0, double lambda=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double k, double lambda)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double k=1.0, double lambda=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Private Member Functions
static double genGamma (HepRandomEngine *anEngine, double k, double lambda)
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double defaultK
double defaultLambda
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 36 of file RandGamma.h.
View newest version in sPHENIX GitHub at line 36 of file RandGamma.h
Constructor & Destructor Documentation
CLHEP::RandGamma::RandGamma (HepRandomEngine & anEngine, double k = 1.0, double lambda = 1.0) inline
CLHEP::RandGamma::RandGamma (HepRandomEngine * anEngine, double k = 1.0, double lambda = 1.0) inline
CLHEP::RandGamma::~RandGamma () virtual
Definition at line 27 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 27 of file RandGamma.cc
Member Function Documentation
static std::string CLHEP::RandGamma::distributionName () inline static
Definition at line 98 of file RandGamma.h.
View newest version in sPHENIX GitHub at line 98 of file RandGamma.h
HepRandomEngine & CLHEP::RandGamma::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 25 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 25 of file RandGamma.cc
References localEngine.
double CLHEP::RandGamma::fire () inline
Referenced by fireArray().
double CLHEP::RandGamma::fire (double k, double lambda)
Definition at line 40 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 40 of file RandGamma.cc
References genGamma(), k, G4InuclParticleNames::lambda, and localEngine.
void CLHEP::RandGamma::fireArray (const int size, double * vect)
Definition at line 59 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 59 of file RandGamma.cc
References defaultK, defaultLambda, fire(), and v.
void CLHEP::RandGamma::fireArray (const int size, double * vect, double k, double lambda)
Definition at line 65 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 65 of file RandGamma.cc
References fire(), and v.
double CLHEP::RandGamma::genGamma (HepRandomEngine * anEngine, double k, double lambda) static private
Definition at line 72 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 72 of file RandGamma.cc
References a, b, c, CLHEP_THREAD_LOCAL, d, e, e1, e2, e3, e4, e5, e6, CLHEP::HepRandomEngine::flat(), r, CLHEP::s, t, Acts::UnitConstants::u, v, v1, v2, w, and x.
Referenced by fire(), and shoot().
std::istream & CLHEP::RandGamma::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 235 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 235 of file RandGamma.cc
References defaultK, defaultLambda, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandGamma::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 24 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 24 of file RandGamma.cc
Referenced by get(), and put().
double CLHEP::RandGamma::operator() () inline virtual
Reimplemented from CLHEP::HepRandom.
double CLHEP::RandGamma::operator() (double k, double lambda) inline
std::ostream & CLHEP::RandGamma::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 222 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 222 of file RandGamma.cc
References defaultK, defaultLambda, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
static double CLHEP::RandGamma::shoot () inline static
Referenced by shootArray().
double CLHEP::RandGamma::shoot (double k, double lambda) static
Definition at line 35 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 35 of file RandGamma.cc
References genGamma(), and CLHEP::HepRandom::getTheEngine().
static double CLHEP::RandGamma::shoot (HepRandomEngine * anEngine) inline static
double CLHEP::RandGamma::shoot (HepRandomEngine * anEngine, double k, double lambda) static
Definition at line 30 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 30 of file RandGamma.cc
References genGamma().
void CLHEP::RandGamma::shootArray (const int size, double * vect, double k = 1.0, double lambda = 1.0) static
Definition at line 44 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 44 of file RandGamma.cc
References shoot(), and v.
void CLHEP::RandGamma::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double k = 1.0, double lambda = 1.0) static
Definition at line 51 of file RandGamma.cc.
View newest version in sPHENIX GitHub at line 51 of file RandGamma.cc
References shoot(), and v.
Member Data Documentation
double CLHEP::RandGamma::defaultK private
Definition at line 108 of file RandGamma.h.
View newest version in sPHENIX GitHub at line 108 of file RandGamma.h
Referenced by fireArray(), get(), and put().
double CLHEP::RandGamma::defaultLambda private
Definition at line 109 of file RandGamma.h.
View newest version in sPHENIX GitHub at line 109 of file RandGamma.h
Referenced by fireArray(), get(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandGamma::localEngine private
Definition at line 107 of file RandGamma.h.
View newest version in sPHENIX GitHub at line 107 of file RandGamma.h
Referenced by engine(), and fire().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGamma.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandGamma.cc