ECCE @ EIC Software: G4FastTrack Class Reference
G4FastTrack Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4FastTrack.hh>
Public Member Functions
G4FastTrack (G4Envelope *anEnvelope, G4bool IsUnique)
~G4FastTrack ()
void SetCurrentTrack (const G4Track &, const G4Navigator *a=0)
G4bool OnTheBoundaryButExiting () const
const G4Track * GetPrimaryTrack () const
G4Envelope * GetEnvelope () const
G4LogicalVolume * GetEnvelopeLogicalVolume () const
G4VPhysicalVolume * GetEnvelopePhysicalVolume () const
G4VSolid * GetEnvelopeSolid () const
G4ThreeVector GetPrimaryTrackLocalPosition () const
G4ThreeVector GetPrimaryTrackLocalMomentum () const
G4ThreeVector GetPrimaryTrackLocalDirection () const
G4ThreeVector GetPrimaryTrackLocalPolarization () const
const G4AffineTransform * GetAffineTransformation () const
const G4AffineTransform * GetInverseAffineTransformation () const
Private Member Functions
void FRecordsAffineTransformation (const G4Navigator *)
Private Attributes
const G4Track * fTrack
G4bool fAffineTransformationDefined
G4Envelope * fEnvelope
G4bool fIsUnique
G4LogicalVolume * fEnvelopeLogicalVolume
G4VPhysicalVolume * fEnvelopePhysicalVolume
G4VSolid * fEnvelopeSolid
G4ThreeVector fLocalTrackPosition
G4ThreeVector fLocalTrackMomentum
G4ThreeVector fLocalTrackDirection
G4ThreeVector fLocalTrackPolarization
G4AffineTransform fAffineTransformation
G4AffineTransform fInverseAffineTransformation
Detailed Description
Definition at line 76 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FastTrack.hh
Constructor & Destructor Documentation
G4FastTrack::G4FastTrack (G4Envelope * anEnvelope, G4bool IsUnique)
Definition at line 50 of file G4FastTrack.cc.
View newest version in sPHENIX GitHub at line 50 of file G4FastTrack.cc
G4FastTrack::~G4FastTrack ()
Definition at line 63 of file G4FastTrack.cc.
View newest version in sPHENIX GitHub at line 63 of file G4FastTrack.cc
Member Function Documentation
void G4FastTrack::FRecordsAffineTransformation (const G4Navigator * theNavigator) private
Definition at line 111 of file G4FastTrack.cc.
View newest version in sPHENIX GitHub at line 111 of file G4FastTrack.cc
References G4Navigator::CreateTouchableHistoryHandle(), fAffineTransformation, fAffineTransformationDefined, fEnvelope, fEnvelopeLogicalVolume, fEnvelopePhysicalVolume, fEnvelopeSolid, fInverseAffineTransformation, G4endl, G4Exception(), G4NavigationHistory::GetDepth(), G4TouchableHistory::GetHistory(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4TransportationManager::GetNavigatorForTracking(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTransform(), G4TransportationManager::GetTransportationManager(), G4NavigationHistory::GetVolume(), g4zmq::history(), G4AffineTransform::Inverse(), G4LogicalVolume::IsRootRegion(), and JustWarning.
Referenced by SetCurrentTrack().
const G4AffineTransform * G4FastTrack::GetAffineTransformation () const inline
Definition at line 231 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 231 of file G4FastTrack.hh
References fAffineTransformation.
G4Envelope * G4FastTrack::GetEnvelope () const inline
Definition at line 186 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 186 of file G4FastTrack.hh
References fEnvelope.
Referenced by G4FastSimulationManager::GetEnvelope(), G4FastSimulationManager::ListTitle(), and G4FastSimulationManager::~G4FastSimulationManager().
G4LogicalVolume * G4FastTrack::GetEnvelopeLogicalVolume () const inline
Definition at line 191 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 191 of file G4FastTrack.hh
References fEnvelopeLogicalVolume.
G4VPhysicalVolume * G4FastTrack::GetEnvelopePhysicalVolume () const inline
Definition at line 196 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 196 of file G4FastTrack.hh
References fEnvelopePhysicalVolume.
G4VSolid * G4FastTrack::GetEnvelopeSolid () const inline
Definition at line 201 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 201 of file G4FastTrack.hh
References fEnvelopeSolid.
Referenced by GFlashShowerModel::CheckContainment(), Par01PiModel::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), and OnTheBoundaryButExiting().
const G4AffineTransform * G4FastTrack::GetInverseAffineTransformation () const inline
Definition at line 236 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 236 of file G4FastTrack.hh
References fInverseAffineTransformation.
Referenced by G4FastStep::CreateSecondaryTrack(), Par01PionShowerModel::Explode(), G4FastStep::ProposePrimaryTrackFinalKineticEnergyAndDirection(), G4FastStep::ProposePrimaryTrackFinalMomentumDirection(), G4FastStep::ProposePrimaryTrackFinalPolarization(), and G4FastStep::ProposePrimaryTrackFinalPosition().
const G4Track * G4FastTrack::GetPrimaryTrack () const inline
Definition at line 206 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 206 of file G4FastTrack.hh
References fTrack.
Referenced by GFlashShowerModel::CheckParticleDefAndContainment(), Par01PiModel::DoIt(), Par01PionShowerModel::DoIt(), Par01EMShowerModel::DoIt(), GFlashShowerModel::DoIt(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), G4GFlashSpot::GetPosition(), G4VGFlashSensitiveDetector::Hit(), G4FastStep::Initialize(), Par01PiModel::ModelTrigger(), Par01EMShowerModel::ModelTrigger(), and GFlashShowerModel::ModelTrigger().
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalDirection () const inline
Definition at line 221 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 221 of file G4FastTrack.hh
References fLocalTrackDirection.
Referenced by GFlashShowerModel::CheckContainment(), Par01PiModel::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01PiModel::ModelTrigger(), and OnTheBoundaryButExiting().
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalMomentum () const inline
Definition at line 216 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 216 of file G4FastTrack.hh
References fLocalTrackMomentum.
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalPolarization () const inline
Definition at line 226 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 226 of file G4FastTrack.hh
References fLocalTrackPolarization.
G4ThreeVector G4FastTrack::GetPrimaryTrackLocalPosition () const inline
Definition at line 211 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 211 of file G4FastTrack.hh
References fLocalTrackPosition.
Referenced by GFlashShowerModel::CheckContainment(), Par01PiModel::DoIt(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01PiModel::ModelTrigger(), and OnTheBoundaryButExiting().
G4bool G4FastTrack::OnTheBoundaryButExiting () const inline
Definition at line 241 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 241 of file G4FastTrack.hh
References GetEnvelopeSolid(), GetPrimaryTrackLocalDirection(), and GetPrimaryTrackLocalPosition().
Referenced by G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger().
void G4FastTrack::SetCurrentTrack (const G4Track & track, const G4Navigator * a = 0)
Definition at line 70 of file G4FastTrack.cc.
View newest version in sPHENIX GitHub at line 70 of file G4FastTrack.cc
References fAffineTransformation, fAffineTransformationDefined, fIsUnique, fLocalTrackDirection, fLocalTrackMomentum, fLocalTrackPolarization, fLocalTrackPosition, FRecordsAffineTransformation(), fTrack, G4Track::GetMomentum(), G4Track::GetPolarization(), G4Track::GetPosition(), track, G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), and CLHEP::Hep3Vector::unit().
Referenced by G4FastSimulationManager::AtRestGetFastSimulationManagerTrigger(), and G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger().
Member Data Documentation
G4AffineTransform G4FastTrack::fAffineTransformation private
Definition at line 177 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 177 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), GetAffineTransformation(), and SetCurrentTrack().
G4bool G4FastTrack::fAffineTransformationDefined private
Definition at line 167 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 167 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), and SetCurrentTrack().
G4Envelope* G4FastTrack::fEnvelope private
Definition at line 168 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 168 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), and GetEnvelope().
G4LogicalVolume* G4FastTrack::fEnvelopeLogicalVolume private
Definition at line 170 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 170 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), and GetEnvelopeLogicalVolume().
G4VPhysicalVolume* G4FastTrack::fEnvelopePhysicalVolume private
Definition at line 171 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 171 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), and GetEnvelopePhysicalVolume().
G4VSolid* G4FastTrack::fEnvelopeSolid private
Definition at line 172 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 172 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), and GetEnvelopeSolid().
G4AffineTransform G4FastTrack::fInverseAffineTransformation private
Definition at line 177 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 177 of file G4FastTrack.hh
Referenced by FRecordsAffineTransformation(), and GetInverseAffineTransformation().
G4bool G4FastTrack::fIsUnique private
Definition at line 169 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 169 of file G4FastTrack.hh
Referenced by SetCurrentTrack().
G4ThreeVector G4FastTrack::fLocalTrackDirection private
Definition at line 173 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 173 of file G4FastTrack.hh
Referenced by GetPrimaryTrackLocalDirection(), and SetCurrentTrack().
G4ThreeVector G4FastTrack::fLocalTrackMomentum private
Definition at line 173 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 173 of file G4FastTrack.hh
Referenced by GetPrimaryTrackLocalMomentum(), and SetCurrentTrack().
G4ThreeVector G4FastTrack::fLocalTrackPolarization private
Definition at line 173 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 173 of file G4FastTrack.hh
Referenced by GetPrimaryTrackLocalPolarization(), and SetCurrentTrack().
G4ThreeVector G4FastTrack::fLocalTrackPosition private
Definition at line 173 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 173 of file G4FastTrack.hh
Referenced by GetPrimaryTrackLocalPosition(), and SetCurrentTrack().
const G4Track* G4FastTrack::fTrack private
Definition at line 160 of file G4FastTrack.hh.
View newest version in sPHENIX GitHub at line 160 of file G4FastTrack.hh
Referenced by GetPrimaryTrack(), and SetCurrentTrack().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4FastTrack.hh
geant4/tree/geant4-10.6-release/source/processes/parameterisation/src/G4FastTrack.cc