ECCE @ EIC Software: G4ChargeState Class Reference
G4ChargeState Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4ChargeState.hh>
Public Member Functions
G4ChargeState (G4double charge, G4double magnetic_dipole_moment, G4double pdgSpin, G4double electric_dipole_moment=0.0, G4double magnetic_charge=0.0)
G4ChargeState (const G4ChargeState &right)
G4ChargeState & operator= (const G4ChargeState &right)
void SetChargeSpinMoments (G4double charge, G4double pdgSpin, G4double magnetic_dipole_moment=DBL_MAX, G4double electric_dipole_moment=DBL_MAX, G4double magnetic_charge=DBL_MAX)
void SetCharge (G4double charge)
G4double GetCharge () const
void SetPDGSpin (G4double spin)
G4double GetPDGSpin () const
void SetMagneticDipoleMoment (G4double moment)
G4double GetMagneticDipoleMoment () const
void SetElectricDipoleMoment (G4double moment)
G4double ElectricDipoleMoment () const
void SetMagneticCharge (G4double charge)
G4double MagneticCharge () const
void SetChargeMdm (G4double charge, G4double mag_dipole_moment)
void SetChargeMdmSpin (G4double charge, G4double magnetic_dipole_moment, G4double pdgSpin)
void SetChargeSpin (G4double charge, G4double pdgSpin)
void SetChargeDipoleMoments (G4double charge, G4double magnetic_dipole_moment, G4double electric_dipole_moment)
void SetChargesAndMoments (G4double charge, G4double magnetic_dipole_moment, G4double electric_dipole_moment, G4double magnetic_charge)
void SetSpin (G4double spin)
G4double GetSpin () const
Private Attributes
G4double fCharge
G4double fSpin
G4double fMagn_dipole
G4double fElec_dipole
G4double fMagneticCharge
Detailed Description
Definition at line 39 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ChargeState.hh
Constructor & Destructor Documentation
G4ChargeState::G4ChargeState (G4double charge, G4double magnetic_dipole_moment, G4double pdgSpin, G4double electric_dipole_moment = 0.0, G4double magnetic_charge = 0.0) inline
Definition at line 118 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ChargeState.hh
References charge, fCharge, fElec_dipole, fMagn_dipole, fMagneticCharge, and fSpin.
G4ChargeState::G4ChargeState (const G4ChargeState & right) inline
Definition at line 131 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ChargeState.hh
References fCharge, fElec_dipole, fMagn_dipole, fMagneticCharge, and fSpin.
Member Function Documentation
G4double G4ChargeState::ElectricDipoleMoment () const inline
Definition at line 74 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ChargeState.hh
References fElec_dipole.
G4double G4ChargeState::GetCharge () const inline
Definition at line 61 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ChargeState.hh
References fCharge.
Referenced by G4EqMagElectricField::SetChargeMomentumMass(), G4EqEMFieldWithSpin::SetChargeMomentumMass(), G4RepleteEofM::SetChargeMomentumMass(), G4MonopoleEq::SetChargeMomentumMass(), G4EqEMFieldWithEDM::SetChargeMomentumMass(), G4Mag_SpinEqRhs::SetChargeMomentumMass(), G4MonopoleEquation::SetChargeMomentumMass(), and G4Mag_EqRhs::SetChargeMomentumMass().
G4double G4ChargeState::GetMagneticDipoleMoment () const inline
Definition at line 71 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ChargeState.hh
References fMagn_dipole.
Referenced by G4EqEMFieldWithSpin::SetChargeMomentumMass(), G4RepleteEofM::SetChargeMomentumMass(), G4EqEMFieldWithEDM::SetChargeMomentumMass(), and G4Mag_SpinEqRhs::SetChargeMomentumMass().
G4double G4ChargeState::GetPDGSpin () const inline
Definition at line 68 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ChargeState.hh
References fSpin.
Referenced by GetSpin().
G4double G4ChargeState::GetSpin () const inline
Definition at line 105 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ChargeState.hh
References GetPDGSpin().
Referenced by G4EqEMFieldWithSpin::SetChargeMomentumMass(), G4RepleteEofM::SetChargeMomentumMass(), G4EqEMFieldWithEDM::SetChargeMomentumMass(), and G4Mag_SpinEqRhs::SetChargeMomentumMass().
G4double G4ChargeState::MagneticCharge () const inline
Definition at line 77 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChargeState.hh
References fMagneticCharge.
Referenced by G4MonopoleEquation::SetChargeMomentumMass().
G4ChargeState & G4ChargeState::operator= (const G4ChargeState & right) inline
Definition at line 140 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ChargeState.hh
References fCharge, fElec_dipole, fMagn_dipole, fMagneticCharge, and fSpin.
void G4ChargeState::SetCharge (G4double charge) inline
Definition at line 60 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ChargeState.hh
References charge, and fCharge.
Referenced by SetChargeMdm(), and SetChargeSpin().
void G4ChargeState::SetChargeDipoleMoments (G4double charge, G4double magnetic_dipole_moment, G4double electric_dipole_moment) inline
Definition at line 175 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ChargeState.hh
References SetChargeMdm(), and SetElectricDipoleMoment().
Referenced by SetChargesAndMoments().
void G4ChargeState::SetChargeMdm (G4double charge, G4double mag_dipole_moment) inline
Definition at line 153 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ChargeState.hh
References SetCharge(), and SetMagneticDipoleMoment().
Referenced by SetChargeDipoleMoments(), and SetChargeMdmSpin().
void G4ChargeState::SetChargeMdmSpin (G4double charge, G4double magnetic_dipole_moment, G4double pdgSpin) inline
Definition at line 159 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ChargeState.hh
References SetChargeMdm(), and SetPDGSpin().
void G4ChargeState::SetChargesAndMoments (G4double charge, G4double magnetic_dipole_moment, G4double electric_dipole_moment, G4double magnetic_charge) inline
Definition at line 184 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ChargeState.hh
References SetChargeDipoleMoments(), and SetMagneticCharge().
Referenced by G4FieldTrack::SetChargeAndMoments().
void G4ChargeState::SetChargeSpin (G4double charge, G4double pdgSpin) inline
Definition at line 167 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ChargeState.hh
References SetCharge(), and SetPDGSpin().
void G4ChargeState::SetChargeSpinMoments (G4double charge, G4double pdgSpin, G4double magnetic_dipole_moment = DBL_MAX, G4double electric_dipole_moment = DBL_MAX, G4double magnetic_charge = DBL_MAX)
Definition at line 33 of file G4ChargeState.cc.
View newest version in sPHENIX GitHub at line 33 of file G4ChargeState.cc
References charge, DBL_MAX, fCharge, fElec_dipole, fMagn_dipole, fMagneticCharge, and fSpin.
void G4ChargeState::SetElectricDipoleMoment (G4double moment) inline
Definition at line 73 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ChargeState.hh
References fElec_dipole.
Referenced by SetChargeDipoleMoments().
void G4ChargeState::SetMagneticCharge (G4double charge) inline
Definition at line 76 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ChargeState.hh
References charge, and fMagneticCharge.
Referenced by SetChargesAndMoments().
void G4ChargeState::SetMagneticDipoleMoment (G4double moment) inline
Definition at line 70 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ChargeState.hh
References fMagn_dipole.
Referenced by SetChargeMdm().
void G4ChargeState::SetPDGSpin (G4double spin) inline
Definition at line 67 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ChargeState.hh
References fSpin.
Referenced by G4FieldTrack::G4FieldTrack(), SetChargeMdmSpin(), SetChargeSpin(), and SetSpin().
void G4ChargeState::SetSpin (G4double spin) inline
Definition at line 104 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ChargeState.hh
References SetPDGSpin().
Member Data Documentation
G4double G4ChargeState::fCharge private
Definition at line 109 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ChargeState.hh
Referenced by G4ChargeState(), GetCharge(), operator=(), SetCharge(), and SetChargeSpinMoments().
G4double G4ChargeState::fElec_dipole private
Definition at line 112 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ChargeState.hh
Referenced by ElectricDipoleMoment(), G4ChargeState(), operator=(), SetChargeSpinMoments(), and SetElectricDipoleMoment().
G4double G4ChargeState::fMagn_dipole private
Definition at line 111 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ChargeState.hh
Referenced by G4ChargeState(), GetMagneticDipoleMoment(), operator=(), SetChargeSpinMoments(), and SetMagneticDipoleMoment().
G4double G4ChargeState::fMagneticCharge private
Definition at line 113 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ChargeState.hh
Referenced by G4ChargeState(), MagneticCharge(), operator=(), SetChargeSpinMoments(), and SetMagneticCharge().
G4double G4ChargeState::fSpin private
Definition at line 110 of file G4ChargeState.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ChargeState.hh
Referenced by G4ChargeState(), GetPDGSpin(), operator=(), SetChargeSpinMoments(), and SetPDGSpin().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4ChargeState.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4ChargeState.cc