ECCE @ EIC Software: G4EnergyLossTables Class Reference
G4EnergyLossTables Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EnergyLossTables.hh>
Public Types
typedef const
G4ParticleDefinition * K
Static Public Member Functions
static const G4PhysicsTable * GetDEDXTable (const G4ParticleDefinition *p)
static const G4PhysicsTable * GetRangeTable (const G4ParticleDefinition *p)
static const G4PhysicsTable * GetInverseRangeTable (const G4ParticleDefinition *p)
static const G4PhysicsTable * GetLabTimeTable (const G4ParticleDefinition *p)
static const G4PhysicsTable * GetProperTimeTable (const G4ParticleDefinition *p)
static G4double GetDEDX (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4Material *aMaterial)
static G4double GetRange (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4Material *aMaterial)
static G4double GetLabTime (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4Material *aMaterial)
static G4double GetDeltaLabTime (const G4ParticleDefinition *aParticle, G4double KineticEnergyStart, G4double KineticEnergyEnd, const G4Material *aMaterial)
static G4double GetProperTime (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4Material *aMaterial)
static G4double GetDeltaProperTime (const G4ParticleDefinition *aParticle, G4double KineticEnergyStart, G4double KineticEnergyEnd, const G4Material *aMaterial)
static G4double GetPreciseDEDX (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4Material *aMaterial)
static G4double GetPreciseRangeFromEnergy (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4Material *aMaterial)
static G4double GetPreciseEnergyFromRange (const G4ParticleDefinition *aParticle, G4double range, const G4Material *aMaterial)
static G4double GetDEDX (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4MaterialCutsCouple *couple, G4bool check=true)
static G4double GetRange (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4MaterialCutsCouple *couple, G4bool check=true)
static G4double GetPreciseDEDX (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4MaterialCutsCouple *couple)
static G4double GetPreciseRangeFromEnergy (const G4ParticleDefinition *aParticle, G4double KineticEnergy, const G4MaterialCutsCouple *couple)
static G4double GetPreciseEnergyFromRange (const G4ParticleDefinition *aParticle, G4double range, const G4MaterialCutsCouple *couple, G4bool check=true)
static void Register (const G4ParticleDefinition *p, const G4PhysicsTable *tDEDX, const G4PhysicsTable *tRange, const G4PhysicsTable *tInverseRange, const G4PhysicsTable *tLabTime, const G4PhysicsTable *tProperTime, G4double lowestKineticEnergy, G4double highestKineticEnergy, G4double massRatio, G4int NumberOfBins)
Private Types
typedef std::map< K,
G4EnergyLossTablesHelper,
std::less< K > > helper_map
Static Private Member Functions
static void CPRWarning ()
static void ParticleHaveNoLoss (const G4ParticleDefinition *aParticle, const G4String &)
static G4EnergyLossTablesHelper GetTables (const G4ParticleDefinition *p)
Static Private Attributes
static helper_map * dict = 0
static G4EnergyLossTablesHelper * t = 0
static G4EnergyLossTablesHelper * null_loss = 0
static G4ParticleDefinition * lastParticle = 0
static G4double QQPositron = 1.0
static G4double Chargesquare
static G4int oldIndex = -1
static G4double rmin = 0.
static G4double rmax = 0.
static G4double Thigh = 0.
static G4int let_counter = 0
static G4int let_max_num_warnings = 100
static G4bool first_loss = true
Detailed Description
Definition at line 103 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 103 of file G4EnergyLossTables.hh
Member Typedef Documentation
typedef std::map<K,G4EnergyLossTablesHelper,std::less<K> > G4EnergyLossTables::helper_map private
Definition at line 226 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 226 of file G4EnergyLossTables.hh
typedef const G4ParticleDefinition* G4EnergyLossTables::K
Definition at line 201 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 201 of file G4EnergyLossTables.hh
Member Function Documentation
void G4EnergyLossTables::CPRWarning () static private
Definition at line 1044 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 1044 of file G4EnergyLossTables.cc
References G4cout, G4endl, let_counter, and let_max_num_warnings.
Referenced by GetDEDX(), GetDeltaLabTime(), GetDeltaProperTime(), GetLabTime(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetProperTime(), and GetRange().
G4double G4EnergyLossTables::GetDEDX (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4Material * aMaterial) static
Definition at line 206 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 206 of file G4EnergyLossTables.cc
References Chargesquare, CPRWarning(), G4Material::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, and G4EnergyLossTablesHelper::theMassRatio.
Referenced by G4hImpactIonisation::ComputeDEDX(), and G4hImpactIonisation::GetConstraints().
G4double G4EnergyLossTables::GetDEDX (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4MaterialCutsCouple * couple, G4bool check = true) static
Definition at line 759 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 759 of file G4EnergyLossTables.cc
References Chargesquare, G4LossTableManager::GetDEDX(), G4MaterialCutsCouple::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), G4LossTableManager::Instance(), lastParticle, oldIndex, ParticleHaveNoLoss(), QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, and G4EnergyLossTablesHelper::theMassRatio.
const G4PhysicsTable * G4EnergyLossTables::GetDEDXTable (const G4ParticleDefinition * p) static
Definition at line 136 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 136 of file G4EnergyLossTables.cc
References dict, and it.
G4double G4EnergyLossTables::GetDeltaLabTime (const G4ParticleDefinition * aParticle, G4double KineticEnergyStart, G4double KineticEnergyEnd, const G4Material * aMaterial) static
Definition at line 307 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 307 of file G4EnergyLossTables.cc
References CPRWarning(), G4Material::GetIndex(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), t, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLabTimeTable, G4EnergyLossTablesHelper::theLowestKineticEnergy, and G4EnergyLossTablesHelper::theMassRatio.
G4double G4EnergyLossTables::GetDeltaProperTime (const G4ParticleDefinition * aParticle, G4double KineticEnergyStart, G4double KineticEnergyEnd, const G4Material * aMaterial) static
Definition at line 441 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 441 of file G4EnergyLossTables.cc
References CPRWarning(), G4Material::GetIndex(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), t, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, and G4EnergyLossTablesHelper::theProperTimeTable.
const G4PhysicsTable * G4EnergyLossTables::GetInverseRangeTable (const G4ParticleDefinition * p) static
Definition at line 158 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 158 of file G4EnergyLossTables.cc
References dict, and it.
G4double G4EnergyLossTables::GetLabTime (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4Material * aMaterial) static
Definition at line 257 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 257 of file G4EnergyLossTables.cc
References CPRWarning(), G4Material::GetIndex(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), t, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLabTimeTable, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, and Acts::VectorHelpers::time().
const G4PhysicsTable * G4EnergyLossTables::GetLabTimeTable (const G4ParticleDefinition * p) static
Definition at line 169 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 169 of file G4EnergyLossTables.cc
References dict, and it.
G4double G4EnergyLossTables::GetPreciseDEDX (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4Material * aMaterial) static
Definition at line 649 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 649 of file G4EnergyLossTables.cc
References Chargesquare, CPRWarning(), G4Material::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, and G4EnergyLossTablesHelper::theMassRatio.
G4double G4EnergyLossTables::GetPreciseDEDX (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4MaterialCutsCouple * couple) static
Definition at line 939 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 939 of file G4EnergyLossTables.cc
References Chargesquare, G4LossTableManager::GetDEDX(), G4MaterialCutsCouple::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), G4LossTableManager::Instance(), lastParticle, oldIndex, QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, and G4EnergyLossTablesHelper::theMassRatio.
G4double G4EnergyLossTables::GetPreciseEnergyFromRange (const G4ParticleDefinition * aParticle, G4double range, const G4Material * aMaterial) static
Definition at line 580 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 580 of file G4EnergyLossTables.cc
References Chargesquare, CPRWarning(), G4Material::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), QQPositron, rmax, rmin, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theInverseRangeTable, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, G4EnergyLossTablesHelper::theNumberOfBins, and Thigh.
Referenced by G4eLowEnergyLoss::AlongStepDoIt(), and G4hImpactIonisation::AlongStepDoIt().
G4double G4EnergyLossTables::GetPreciseEnergyFromRange (const G4ParticleDefinition * aParticle, G4double range, const G4MaterialCutsCouple * couple, G4bool check = true) static
Definition at line 868 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 868 of file G4EnergyLossTables.cc
References Chargesquare, DBL_MAX, G4LossTableManager::GetEnergy(), G4MaterialCutsCouple::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), G4LossTableManager::Instance(), lastParticle, oldIndex, QQPositron, rmax, rmin, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theInverseRangeTable, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, G4EnergyLossTablesHelper::theNumberOfBins, and Thigh.
G4double G4EnergyLossTables::GetPreciseRangeFromEnergy (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4Material * aMaterial) static
Definition at line 700 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 700 of file G4EnergyLossTables.cc
References Chargesquare, CPRWarning(), G4Material::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, and G4EnergyLossTablesHelper::theRangeTable.
G4double G4EnergyLossTables::GetPreciseRangeFromEnergy (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4MaterialCutsCouple * couple) static
Definition at line 987 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 987 of file G4EnergyLossTables.cc
References Chargesquare, G4LossTableManager::GetDEDX(), G4MaterialCutsCouple::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), G4LossTableManager::Instance(), lastParticle, oldIndex, QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, and G4EnergyLossTablesHelper::theRangeTable.
G4double G4EnergyLossTables::GetProperTime (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4Material * aMaterial) static
Definition at line 391 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 391 of file G4EnergyLossTables.cc
References CPRWarning(), G4Material::GetIndex(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), t, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, G4EnergyLossTablesHelper::theProperTimeTable, and Acts::VectorHelpers::time().
const G4PhysicsTable * G4EnergyLossTables::GetProperTimeTable (const G4ParticleDefinition * p) static
Definition at line 180 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 180 of file G4EnergyLossTables.cc
References dict, and it.
G4double G4EnergyLossTables::GetRange (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4Material * aMaterial) static
Definition at line 525 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 525 of file G4EnergyLossTables.cc
References Chargesquare, CPRWarning(), G4Material::GetIndex(), G4ParticleDefinition::GetPDGCharge(), GetTables(), lastParticle, oldIndex, ParticleHaveNoLoss(), QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, and G4EnergyLossTablesHelper::theRangeTable.
Referenced by G4RDRangeTest::Escape(), G4hImpactIonisation::GetConstraints(), and G4MinEkineCuts::PostStepGetPhysicalInteractionLength().
G4double G4EnergyLossTables::GetRange (const G4ParticleDefinition * aParticle, G4double KineticEnergy, const G4MaterialCutsCouple * couple, G4bool check = true) static
Definition at line 812 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 812 of file G4EnergyLossTables.cc
References Chargesquare, DBL_MAX, G4MaterialCutsCouple::GetIndex(), G4ParticleDefinition::GetPDGCharge(), G4LossTableManager::GetRange(), GetTables(), G4LossTableManager::Instance(), lastParticle, oldIndex, QQPositron, t, G4EnergyLossTablesHelper::theDEDXTable, G4EnergyLossTablesHelper::theHighestKineticEnergy, G4EnergyLossTablesHelper::theLowestKineticEnergy, G4EnergyLossTablesHelper::theMassRatio, and G4EnergyLossTablesHelper::theRangeTable.
const G4PhysicsTable * G4EnergyLossTables::GetRangeTable (const G4ParticleDefinition * p) static
Definition at line 147 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 147 of file G4EnergyLossTables.cc
References dict, and it.
G4EnergyLossTablesHelper G4EnergyLossTables::GetTables (const G4ParticleDefinition * p) static private
Definition at line 191 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 191 of file G4EnergyLossTables.cc
References dict, it, and null_loss.
Referenced by GetDEDX(), GetDeltaLabTime(), GetDeltaProperTime(), GetLabTime(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetProperTime(), GetRange(), and Register().
void G4EnergyLossTables::ParticleHaveNoLoss (const G4ParticleDefinition * aParticle, const G4String &) static private
Definition at line 1066 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 1066 of file G4EnergyLossTables.cc
Referenced by GetDEDX(), GetDeltaLabTime(), GetDeltaProperTime(), GetLabTime(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetProperTime(), and GetRange().
void G4EnergyLossTables::Register (const G4ParticleDefinition * p, const G4PhysicsTable * tDEDX, const G4PhysicsTable * tRange, const G4PhysicsTable * tInverseRange, const G4PhysicsTable * tLabTime, const G4PhysicsTable * tProperTime, G4double lowestKineticEnergy, G4double highestKineticEnergy, G4double massRatio, G4int NumberOfBins) static
Definition at line 104 of file G4EnergyLossTables.cc.
View newest version in sPHENIX GitHub at line 104 of file G4EnergyLossTables.cc
References Chargesquare, dict, first_loss, G4ParticleDefinition::GetPDGCharge(), GetTables(), lastParticle, null_loss, QQPositron, and t.
Referenced by G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), and G4hImpactIonisation::BuildPhysicsTable().
Member Data Documentation
G4double G4EnergyLossTables::Chargesquare static private
Definition at line 235 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 235 of file G4EnergyLossTables.hh
Referenced by GetDEDX(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetRange(), and Register().
G4EnergyLossTables::helper_map * G4EnergyLossTables::dict = 0 static private
Definition at line 227 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 227 of file G4EnergyLossTables.hh
Referenced by GetDEDXTable(), GetInverseRangeTable(), GetLabTimeTable(), GetProperTimeTable(), GetRangeTable(), GetTables(), and Register().
G4bool G4EnergyLossTables::first_loss = true static private
Definition at line 240 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 240 of file G4EnergyLossTables.hh
Referenced by Register().
G4ParticleDefinition * G4EnergyLossTables::lastParticle = 0 static private
Definition at line 233 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 233 of file G4EnergyLossTables.hh
Referenced by GetDEDX(), GetDeltaLabTime(), GetDeltaProperTime(), GetLabTime(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetProperTime(), GetRange(), and Register().
G4int G4EnergyLossTables::let_counter = 0 static private
Definition at line 238 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 238 of file G4EnergyLossTables.hh
Referenced by CPRWarning().
G4int G4EnergyLossTables::let_max_num_warnings = 100 static private
Definition at line 239 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 239 of file G4EnergyLossTables.hh
Referenced by CPRWarning().
G4EnergyLossTablesHelper * G4EnergyLossTables::null_loss = 0 static private
Definition at line 232 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 232 of file G4EnergyLossTables.hh
Referenced by GetTables(), and Register().
G4int G4EnergyLossTables::oldIndex = -1 static private
Definition at line 236 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 236 of file G4EnergyLossTables.hh
Referenced by GetDEDX(), GetDeltaLabTime(), GetDeltaProperTime(), GetLabTime(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetProperTime(), and GetRange().
G4double G4EnergyLossTables::QQPositron = 1.0 static private
Definition at line 234 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 234 of file G4EnergyLossTables.hh
Referenced by GetDEDX(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetRange(), and Register().
G4double G4EnergyLossTables::rmax = 0. static private
Definition at line 237 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 237 of file G4EnergyLossTables.hh
Referenced by GetPreciseEnergyFromRange().
G4double G4EnergyLossTables::rmin = 0. static private
Definition at line 237 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 237 of file G4EnergyLossTables.hh
Referenced by GetPreciseEnergyFromRange().
G4EnergyLossTablesHelper * G4EnergyLossTables::t = 0 static private
Definition at line 231 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 231 of file G4EnergyLossTables.hh
Referenced by GetDEDX(), GetDeltaLabTime(), GetDeltaProperTime(), GetLabTime(), GetPreciseDEDX(), GetPreciseEnergyFromRange(), GetPreciseRangeFromEnergy(), GetProperTime(), GetRange(), and Register().
G4double G4EnergyLossTables::Thigh = 0. static private
Definition at line 237 of file G4EnergyLossTables.hh.
View newest version in sPHENIX GitHub at line 237 of file G4EnergyLossTables.hh
Referenced by GetPreciseEnergyFromRange().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EnergyLossTables.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EnergyLossTables.cc