ECCE @ EIC Software: G4VIntersectionLocator Class Reference
G4VIntersectionLocator Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4VIntersectionLocator.hh>
Public Member Functions
G4VIntersectionLocator (G4Navigator *theNavigator)
virtual ~G4VIntersectionLocator ()
virtual G4bool EstimateIntersectionPoint (const G4FieldTrack &curveStartPointTangent, const G4FieldTrack &curveEndPointTangent, const G4ThreeVector &trialPoint, G4FieldTrack &intersectPointTangent, G4bool &recalculatedEndPoint, G4double &fPreviousSafety, G4ThreeVector &fPreviousSftOrigin)=0
void printStatus (const G4FieldTrack &startFT, const G4FieldTrack &currentFT, G4double requestStep, G4double safety, G4int stepNum)
G4bool IntersectChord (const G4ThreeVector &StartPointA, const G4ThreeVector &EndPointB, G4double &NewSafety, G4double &PreviousSafety, G4ThreeVector &PreviousSftOrigin, G4double &LinearStepLength, G4ThreeVector &IntersectionPoint, G4bool *calledNavigator=nullptr)
void SetEpsilonStepFor (G4double EpsilonStep)
void SetDeltaIntersectionFor (G4double deltaIntersection)
void SetNavigatorFor (G4Navigator *fNavigator)
void SetChordFinderFor (G4ChordFinder *fCFinder)
void SetVerboseFor (G4int fVerbose)
G4int GetVerboseFor ()
G4double GetDeltaIntersectionFor ()
G4double GetEpsilonStepFor ()
G4Navigator * GetNavigatorFor ()
G4ChordFinder * GetChordFinderFor ()
void SetSafetyParametersFor (G4bool UseSafety)
void AddAdjustementOfFoundIntersection (G4bool UseCorrection)
G4bool GetAdjustementOfFoundIntersection ()
void AdjustIntersections (G4bool UseCorrection)
G4bool AreIntersectionsAdjusted ()
Static Public Member Functions
static void printStatus (const G4FieldTrack &startFT, const G4FieldTrack &currentFT, G4double requestStep, G4double safety, G4int stepNum, std::ostream &oss, G4int verboseLevel)
Protected Member Functions
G4FieldTrack ReEstimateEndpoint (const G4FieldTrack &CurrentStateA, const G4FieldTrack &EstimtdEndStateB, G4double linearDistSq, G4double curveDist)
G4bool CheckAndReEstimateEndpoint (const G4FieldTrack &CurrentStartA, const G4FieldTrack &EstimatedEndB, G4FieldTrack &RevisedEndPoint, G4int &errorCode)
G4ThreeVector GetSurfaceNormal (const G4ThreeVector &CurrentInt_Point, G4bool &validNormal)
G4ThreeVector GetGlobalSurfaceNormal (const G4ThreeVector &CurrentE_Point, G4bool &validNormal)
G4bool AdjustmentOfFoundIntersection (const G4ThreeVector &A, const G4ThreeVector &CurrentE_Point, const G4ThreeVector &CurrentF_Point, const G4ThreeVector &MomentumDir, const G4bool IntersectAF, G4ThreeVector &IntersectionPoint, G4double &NewSafety, G4double &fPrevSafety, G4ThreeVector &fPrevSftOrigin)
void ReportTrialStep (G4int step_no, const G4ThreeVector &ChordAB_v, const G4ThreeVector &ChordEF_v, const G4ThreeVector &NewMomentumDir, const G4ThreeVector &NormalAtEntry, G4bool validNormal)
G4bool LocateGlobalPointWithinVolumeAndCheck (const G4ThreeVector &pos)
void LocateGlobalPointWithinVolumeCheckAndReport (const G4ThreeVector &pos, const G4String &CodeLocationInfo, G4int CheckMode)
void SetCheckMode (G4bool value)
G4bool GetCheckMode ()
void ReportReversedPoints (std::ostringstream &ossMsg, const G4FieldTrack &StartPointVel, const G4FieldTrack &EndPointVel, G4double NewSafety, G4double epsStep, const G4FieldTrack &CurrentA_PointVelocity, const G4FieldTrack &CurrentB_PointVelocity, const G4FieldTrack &SubStart_PointVelocity, const G4ThreeVector &CurrentE_Point, const G4FieldTrack &ApproxIntersecPointV, G4int sbstp_no, G4int sbstp_no_p, G4int depth)
void ReportProgress (std::ostream &oss, const G4FieldTrack &StartPointVel, const G4FieldTrack &EndPointVel, G4int substep_no, const G4FieldTrack &A_PtVel, const G4FieldTrack &B_PtVel, G4double safetyLast, G4int depth=-1)
void ReportImmediateHit (const char *MethodName, const G4ThreeVector &StartPosition, const G4ThreeVector &TrialPoint, G4double tolerance, unsigned long int numCalls)
Protected Attributes
G4double kCarTolerance
G4int fVerboseLevel = 0
G4bool fUseNormalCorrection = false
G4bool fCheckMode = false
G4Navigator * fiNavigator
G4ChordFinder * fiChordFinder = nullptr
G4double fiEpsilonStep = -1.0
G4double fiDeltaIntersection = -1.0
G4bool fiUseSafety = false
G4Navigator * fHelpingNavigator
G4TouchableHistory * fpTouchable = nullptr
Private Member Functions
G4ThreeVector GetLocalSurfaceNormal (const G4ThreeVector &CurrentE_Point, G4bool &validNormal)
G4ThreeVector GetLastSurfaceNormal (const G4ThreeVector &intersectPoint, G4bool &validNormal) const
Detailed Description
Definition at line 49 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VIntersectionLocator.hh
Constructor & Destructor Documentation
G4VIntersectionLocator::G4VIntersectionLocator (G4Navigator * theNavigator)
Definition at line 45 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VIntersectionLocator.cc
References G4Navigator::Clone(), fHelpingNavigator, fiNavigator, G4Navigator::GetExternalNavigation(), G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), and kCarTolerance.
G4VIntersectionLocator::~G4VIntersectionLocator () virtual
Definition at line 64 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VIntersectionLocator.cc
References fHelpingNavigator, and fpTouchable.
Member Function Documentation
void G4VIntersectionLocator::AddAdjustementOfFoundIntersection (G4bool UseCorrection) inline
void G4VIntersectionLocator::AdjustIntersections (G4bool UseCorrection) inline
G4bool G4VIntersectionLocator::AdjustmentOfFoundIntersection (const G4ThreeVector & A, const G4ThreeVector & CurrentE_Point, const G4ThreeVector & CurrentF_Point, const G4ThreeVector & MomentumDir, const G4bool IntersectAF, G4ThreeVector & IntersectionPoint, G4double & NewSafety, G4double & fPrevSafety, G4ThreeVector & fPrevSftOrigin) protected
Definition at line 438 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 438 of file G4VIntersectionLocator.cc
References kdfinder::abs(), CLHEP::Hep3Vector::dot(), fVerboseLevel, G4Exception(), GetGlobalSurfaceNormal(), GetNavigatorFor(), IntersectChord(), JustWarning, kCarTolerance, G4InuclParticleNames::lambda, and G4Navigator::LocateGlobalPointWithinVolume().
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4bool G4VIntersectionLocator::AreIntersectionsAdjusted () inline
Definition at line 118 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VIntersectionLocator.hh
References fUseNormalCorrection.
G4bool G4VIntersectionLocator::CheckAndReEstimateEndpoint (const G4FieldTrack & CurrentStartA, const G4FieldTrack & EstimatedEndB, G4FieldTrack & RevisedEndPoint, G4int & errorCode) protected
Definition at line 328 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 328 of file G4VIntersectionLocator.cc
References fiEpsilonStep, G4Exception(), G4FieldTrack::GetCurveLength(), G4FieldTrack::GetPosition(), JustWarning, and ReEstimateEndpoint().
Referenced by G4MultiLevelLocator::EstimateIntersectionPoint().
virtual G4bool G4VIntersectionLocator::EstimateIntersectionPoint (const G4FieldTrack & curveStartPointTangent, const G4FieldTrack & curveEndPointTangent, const G4ThreeVector & trialPoint, G4FieldTrack & intersectPointTangent, G4bool & recalculatedEndPoint, G4double & fPreviousSafety, G4ThreeVector & fPreviousSftOrigin) pure virtual
Implemented in G4BrentLocator, G4MultiLevelLocator, and G4SimpleLocator.
G4bool G4VIntersectionLocator::GetAdjustementOfFoundIntersection () inline
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4bool G4VIntersectionLocator::GetCheckMode () inline protected
Definition at line 202 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 202 of file G4VIntersectionLocator.hh
References fCheckMode.
Referenced by LocateGlobalPointWithinVolumeCheckAndReport().
G4ChordFinder* G4VIntersectionLocator::GetChordFinderFor () inline
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and ReEstimateEndpoint().
G4double G4VIntersectionLocator::GetDeltaIntersectionFor () inline
Referenced by G4BrentLocator::EstimateIntersectionPoint().
G4double G4VIntersectionLocator::GetEpsilonStepFor () inline
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and ReEstimateEndpoint().
G4ThreeVector G4VIntersectionLocator::GetGlobalSurfaceNormal (const G4ThreeVector & CurrentE_Point, G4bool & validNormal) protected
Definition at line 562 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 562 of file G4VIntersectionLocator.cc
References fHelpingNavigator, G4endl, G4Exception(), GetLocalSurfaceNormal(), G4Navigator::GetLocalToGlobalTransform(), JustWarning, CLHEP::Hep3Vector::mag2(), message(), G4AffineTransform::NetRotation(), G4AffineTransform::NetTranslation(), perThousand, and G4AffineTransform::TransformAxis().
Referenced by AdjustmentOfFoundIntersection().
G4ThreeVector G4VIntersectionLocator::GetLastSurfaceNormal (const G4ThreeVector & intersectPoint, G4bool & validNormal) const private
Definition at line 601 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 601 of file G4VIntersectionLocator.cc
References fiNavigator, and G4Navigator::GetGlobalExitNormal().
Referenced by GetSurfaceNormal().
G4ThreeVector G4VIntersectionLocator::GetLocalSurfaceNormal (const G4ThreeVector & CurrentE_Point, G4bool & validNormal) private
Definition at line 383 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 383 of file G4VIntersectionLocator.cc
References G4Navigator::CreateTouchableHistory(), G4VSolid::DistanceToOut(), fHelpingNavigator, fpTouchable, G4cerr, G4endl, G4TouchableHistory::GetHistory(), G4VPhysicalVolume::GetLogicalVolume(), GetNavigatorFor(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopTransform(), G4VSolid::Inside(), kCarTolerance, kSurface, G4Navigator::LocateGlobalPointAndSetup(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::perThousand, G4Navigator::SetWorldVolume(), G4VSolid::SurfaceNormal(), and G4AffineTransform::TransformPoint().
Referenced by GetGlobalSurfaceNormal().
G4Navigator* G4VIntersectionLocator::GetNavigatorFor () inline
Referenced by AdjustmentOfFoundIntersection(), G4SimpleLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), GetLocalSurfaceNormal(), and LocateGlobalPointWithinVolumeAndCheck().
G4ThreeVector G4VIntersectionLocator::GetSurfaceNormal (const G4ThreeVector & CurrentInt_Point, G4bool & validNormal) protected
Definition at line 517 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 517 of file G4VIntersectionLocator.cc
References G4endl, G4Exception(), GetLastSurfaceNormal(), JustWarning, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), message(), and perThousand.
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4int G4VIntersectionLocator::GetVerboseFor () inline
G4bool G4VIntersectionLocator::IntersectChord (const G4ThreeVector & StartPointA, const G4ThreeVector & EndPointB, G4double & NewSafety, G4double & PreviousSafety, G4ThreeVector & PreviousSftOrigin, G4double & LinearStepLength, G4ThreeVector & IntersectionPoint, G4bool * calledNavigator = nullptr) inline
Referenced by AdjustmentOfFoundIntersection(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4bool G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck (const G4ThreeVector & pos) protected
Definition at line 673 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 673 of file G4VIntersectionLocator.cc
References G4Navigator::CheckMode(), G4Navigator::CreateTouchableHistoryHandle(), G4VSolid::DistanceToIn(), fCheckMode, G4endl, G4Exception(), G4VPhysicalVolume::GetCopyNo(), G4Navigator::GetGlobalToLocalTransform(), GetNavigatorFor(), G4TouchableHistory::GetSolid(), G4TouchableHistory::GetVolume(), G4VSolid::Inside(), G4Navigator::IsCheckModeActive(), JustWarning, kInside, kSurface, G4Navigator::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), message(), Acts::Test::transform, and G4AffineTransform::TransformPoint().
Referenced by LocateGlobalPointWithinVolumeCheckAndReport().
void G4VIntersectionLocator::LocateGlobalPointWithinVolumeCheckAndReport (const G4ThreeVector & pos, const G4String & CodeLocationInfo, G4int CheckMode) protected
Definition at line 735 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 735 of file G4VIntersectionLocator.cc
References G4endl, G4Exception(), GetCheckMode(), JustWarning, LocateGlobalPointWithinVolumeAndCheck(), message(), and SetCheckMode().
void G4VIntersectionLocator::printStatus (const G4FieldTrack & startFT, const G4FieldTrack & currentFT, G4double requestStep, G4double safety, G4int stepNum)
Definition at line 75 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 75 of file G4VIntersectionLocator.cc
References fVerboseLevel, and G4cout.
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), printStatus(), ReportProgress(), and ReportReversedPoints().
void G4VIntersectionLocator::printStatus (const G4FieldTrack & startFT, const G4FieldTrack & currentFT, G4double requestStep, G4double safety, G4int stepNum, std::ostream & oss, G4int verboseLevel) static
Definition at line 91 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 91 of file G4VIntersectionLocator.cc
References G4endl, G4FieldTrack::GetCurveLength(), G4FieldTrack::GetMomentum(), G4FieldTrack::GetMomentumDir(), G4FieldTrack::GetPosition(), CLHEP::Hep3Vector::mag(), printStatus(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4FieldTrack G4VIntersectionLocator::ReEstimateEndpoint (const G4FieldTrack & CurrentStateA, const G4FieldTrack & EstimtdEndStateB, G4double linearDistSq, G4double curveDist) protected
Definition at line 189 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 189 of file G4VIntersectionLocator.cc
References kdfinder::abs(), fVerboseLevel, G4cout, G4endl, G4Exception(), G4ThreadLocal, GetChordFinderFor(), G4FieldTrack::GetCurveLength(), GetEpsilonStepFor(), G4ChordFinder::GetIntegrationDriver(), G4FieldTrack::GetPosition(), JustWarning, kCarTolerance, CLHEP::Hep3Vector::mag(), and message().
Referenced by CheckAndReEstimateEndpoint(), G4SimpleLocator::EstimateIntersectionPoint(), and G4BrentLocator::EstimateIntersectionPoint().
void G4VIntersectionLocator::ReportImmediateHit (const char * MethodName, const G4ThreeVector & StartPosition, const G4ThreeVector & TrialPoint, G4double tolerance, unsigned long int numCalls) protected
Definition at line 839 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 839 of file G4VIntersectionLocator.cc
References DBL_MAX, G4cout, G4endl, G4ThreadLocal, and G4AutoDelete::Register().
Referenced by G4MultiLevelLocator::EstimateIntersectionPoint().
void G4VIntersectionLocator::ReportProgress (std::ostream & oss, const G4FieldTrack & StartPointVel, const G4FieldTrack & EndPointVel, G4int substep_no, const G4FieldTrack & A_PtVel, const G4FieldTrack & B_PtVel, G4double safetyLast, G4int depth = -1) protected
Definition at line 807 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 807 of file G4VIntersectionLocator.cc
References G4endl, and printStatus().
Referenced by G4MultiLevelLocator::EstimateIntersectionPoint().
void G4VIntersectionLocator::ReportReversedPoints (std::ostringstream & ossMsg, const G4FieldTrack & StartPointVel, const G4FieldTrack & EndPointVel, G4double NewSafety, G4double epsStep, const G4FieldTrack & CurrentA_PointVelocity, const G4FieldTrack & CurrentB_PointVelocity, const G4FieldTrack & SubStart_PointVelocity, const G4ThreeVector & CurrentE_Point, const G4FieldTrack & ApproxIntersecPointV, G4int sbstp_no, G4int sbstp_no_p, G4int depth) protected
Definition at line 760 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 760 of file G4VIntersectionLocator.cc
References G4endl, G4FieldTrack::GetCurveLength(), and printStatus().
Referenced by G4MultiLevelLocator::EstimateIntersectionPoint().
void G4VIntersectionLocator::ReportTrialStep (G4int step_no, const G4ThreeVector & ChordAB_v, const G4ThreeVector & ChordEF_v, const G4ThreeVector & NewMomentumDir, const G4ThreeVector & NormalAtEntry, G4bool validNormal) protected
Definition at line 616 of file G4VIntersectionLocator.cc.
View newest version in sPHENIX GitHub at line 616 of file G4VIntersectionLocator.cc
References CLHEP::Hep3Vector::dot(), G4cout, G4endl, G4Exception(), JustWarning, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), message(), and perThousand.
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
void G4VIntersectionLocator::SetCheckMode (G4bool value) inline protected
Definition at line 201 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 201 of file G4VIntersectionLocator.hh
References fCheckMode.
Referenced by LocateGlobalPointWithinVolumeCheckAndReport().
void G4VIntersectionLocator::SetChordFinderFor (G4ChordFinder * fCFinder) inline
Referenced by G4PropagatorInField::RefreshIntersectionLocator().
void G4VIntersectionLocator::SetDeltaIntersectionFor (G4double deltaIntersection) inline
Referenced by G4PropagatorInField::RefreshIntersectionLocator().
void G4VIntersectionLocator::SetEpsilonStepFor (G4double EpsilonStep) inline
Referenced by G4PropagatorInField::RefreshIntersectionLocator().
void G4VIntersectionLocator::SetNavigatorFor (G4Navigator * fNavigator) inline
Referenced by G4ErrorPropagatorManager::StartNavigator().
void G4VIntersectionLocator::SetSafetyParametersFor (G4bool UseSafety) inline
Referenced by G4PropagatorInField::RefreshIntersectionLocator().
void G4VIntersectionLocator::SetVerboseFor (G4int fVerbose) inline
Member Data Documentation
G4bool G4VIntersectionLocator::fCheckMode = false protected
Definition at line 256 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 256 of file G4VIntersectionLocator.hh
Referenced by GetCheckMode(), LocateGlobalPointWithinVolumeAndCheck(), and SetCheckMode().
G4Navigator* G4VIntersectionLocator::fHelpingNavigator protected
Definition at line 267 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 267 of file G4VIntersectionLocator.hh
Referenced by G4VIntersectionLocator(), GetGlobalSurfaceNormal(), GetLocalSurfaceNormal(), and ~G4VIntersectionLocator().
G4ChordFinder* G4VIntersectionLocator::fiChordFinder = nullptr protected
Definition at line 260 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 260 of file G4VIntersectionLocator.hh
G4double G4VIntersectionLocator::fiDeltaIntersection = -1.0 protected
Definition at line 262 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 262 of file G4VIntersectionLocator.hh
Referenced by G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4double G4VIntersectionLocator::fiEpsilonStep = -1.0 protected
Definition at line 261 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 261 of file G4VIntersectionLocator.hh
Referenced by CheckAndReEstimateEndpoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4Navigator* G4VIntersectionLocator::fiNavigator protected
Definition at line 258 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 258 of file G4VIntersectionLocator.hh
Referenced by G4VIntersectionLocator(), and GetLastSurfaceNormal().
G4bool G4VIntersectionLocator::fiUseSafety = false protected
Definition at line 263 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 263 of file G4VIntersectionLocator.hh
G4TouchableHistory* G4VIntersectionLocator::fpTouchable = nullptr protected
Definition at line 270 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 270 of file G4VIntersectionLocator.hh
Referenced by GetLocalSurfaceNormal(), and ~G4VIntersectionLocator().
G4bool G4VIntersectionLocator::fUseNormalCorrection = false protected
Definition at line 255 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 255 of file G4VIntersectionLocator.hh
Referenced by AreIntersectionsAdjusted().
G4int G4VIntersectionLocator::fVerboseLevel = 0 protected
Definition at line 254 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 254 of file G4VIntersectionLocator.hh
Referenced by AdjustmentOfFoundIntersection(), G4SimpleLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), printStatus(), and ReEstimateEndpoint().
G4double G4VIntersectionLocator::kCarTolerance protected
Definition at line 252 of file G4VIntersectionLocator.hh.
View newest version in sPHENIX GitHub at line 252 of file G4VIntersectionLocator.hh
Referenced by AdjustmentOfFoundIntersection(), G4SimpleLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4VIntersectionLocator(), GetLocalSurfaceNormal(), and ReEstimateEndpoint().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4VIntersectionLocator.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4VIntersectionLocator.cc