ECCE @ EIC Software: cheprep::DefaultHepRepAttValue Class Reference
cheprep::DefaultHepRepAttValue Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepAttValue.h>
Public Member Functions
DefaultHepRepAttValue (std::string name, std::string value, int showLabel)
DefaultHepRepAttValue (std::string name, int64 value, int showLabel)
DefaultHepRepAttValue (std::string name, int value, int showLabel)
DefaultHepRepAttValue (std::string name, double value, int showLabel)
DefaultHepRepAttValue (std::string name, bool value, int showLabel)
DefaultHepRepAttValue (std::string name, std::vector< double > value, int showLabel)
~DefaultHepRepAttValue ()
HEPREP::HepRepAttValue * copy ()
std::string getName ()
std::string getLowerCaseName ()
int getType ()
std::string getTypeName ()
int showLabel ()
std::string getString ()
std::string getLowerCaseString ()
int64 getLong ()
int getInteger ()
double getDouble ()
bool getBoolean ()
std::vector< double > getColor ()
std::string getAsString ()
std::string toShowLabel ()
Public Member Functions inherited from HEPREP::HepRepAttValue
virtual ~HepRepAttValue ()
Destructor.
Static Public Member Functions
static std::string getAsString (std::vector< double > c)
static std::string getAsString (int i)
static std::string getAsString (int64 i)
static std::string getAsString (double d)
static std::string getAsString (bool b)
static std::string toShowLabel (int showLabel)
Private Types
enum { LABELSTRINGS_LEN = 4 }
Private Member Functions
void init ()
Private Attributes
std::string name
int type
std::string stringValue
int64 longValue
double doubleValue
bool booleanValue
std::vector< double > colorValue
int showLabelValue
Static Private Attributes
static std::string labelStrings [LABELSTRINGS_LEN]
Detailed Description
Definition at line 16 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 16 of file DefaultHepRepAttValue.h
Member Enumeration Documentation
anonymous enum private
Enumerator:
LABELSTRINGS_LEN
Definition at line 19 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 19 of file DefaultHepRepAttValue.h
Constructor & Destructor Documentation
cheprep::DefaultHepRepAttValue::DefaultHepRepAttValue (std::string name, std::string value, int showLabel)
Definition at line 26 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 26 of file DefaultHepRepAttValue.cc
References init().
Referenced by copy().
cheprep::DefaultHepRepAttValue::DefaultHepRepAttValue (std::string name, int64 value, int showLabel)
Definition at line 38 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 38 of file DefaultHepRepAttValue.cc
References init().
cheprep::DefaultHepRepAttValue::DefaultHepRepAttValue (std::string name, int value, int showLabel)
Definition at line 49 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 49 of file DefaultHepRepAttValue.cc
References init().
cheprep::DefaultHepRepAttValue::DefaultHepRepAttValue (std::string name, double value, int showLabel)
Definition at line 60 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 60 of file DefaultHepRepAttValue.cc
References init().
cheprep::DefaultHepRepAttValue::DefaultHepRepAttValue (std::string name, bool value, int showLabel)
Definition at line 71 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 71 of file DefaultHepRepAttValue.cc
References init().
cheprep::DefaultHepRepAttValue::DefaultHepRepAttValue (std::string name, std::vector< double > value, int showLabel)
Definition at line 82 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 82 of file DefaultHepRepAttValue.cc
References init().
cheprep::DefaultHepRepAttValue::~DefaultHepRepAttValue ()
Definition at line 94 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 94 of file DefaultHepRepAttValue.cc
Member Function Documentation
HepRepAttValue * cheprep::DefaultHepRepAttValue::copy () virtual
Returns a deep copy of this attvalue.
Returns
copy of this attvalue.
Implements HEPREP::HepRepAttValue.
Definition at line 104 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 104 of file DefaultHepRepAttValue.cc
References booleanValue, colorValue, DefaultHepRepAttValue(), doubleValue, longValue, showLabelValue, stringValue, and type.
string cheprep::DefaultHepRepAttValue::getAsString () virtual
Returns value as string.
Returns
value (of any type) in string format.
Implements HEPREP::HepRepAttValue.
Definition at line 192 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 192 of file DefaultHepRepAttValue.cc
References getBoolean(), getColor(), getDouble(), getInteger(), getLong(), getString(), and type.
Referenced by cheprep::XMLWriter::setAttribute().
string cheprep::DefaultHepRepAttValue::getAsString (std::vector< double > c) static
Definition at line 204 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 204 of file DefaultHepRepAttValue.cc
References buffer.
string cheprep::DefaultHepRepAttValue::getAsString (int i) static
Definition at line 214 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 214 of file DefaultHepRepAttValue.cc
References buffer.
string cheprep::DefaultHepRepAttValue::getAsString (int64 i) static
Definition at line 220 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 220 of file DefaultHepRepAttValue.cc
References buffer, and CHEPREP_INT64_FORMAT.
string cheprep::DefaultHepRepAttValue::getAsString (double d) static
Definition at line 227 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 227 of file DefaultHepRepAttValue.cc
References buffer.
string cheprep::DefaultHepRepAttValue::getAsString (bool b) static
Definition at line 233 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 233 of file DefaultHepRepAttValue.cc
bool cheprep::DefaultHepRepAttValue::getBoolean () virtual
Returns value as boolean.
Returns
value as boolean.
Implements HEPREP::HepRepAttValue.
Definition at line 181 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 181 of file DefaultHepRepAttValue.cc
References booleanValue, getName(), and type.
Referenced by getAsString().
vector< double > cheprep::DefaultHepRepAttValue::getColor () virtual
Returns value as Color.
Returns
value as Color.
Implements HEPREP::HepRepAttValue.
Definition at line 186 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 186 of file DefaultHepRepAttValue.cc
References colorValue, getName(), and type.
Referenced by getAsString().
double cheprep::DefaultHepRepAttValue::getDouble () virtual
Returns value as double.
Returns
value as double.
Implements HEPREP::HepRepAttValue.
Definition at line 176 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 176 of file DefaultHepRepAttValue.cc
References doubleValue, getName(), and type.
Referenced by getAsString().
int cheprep::DefaultHepRepAttValue::getInteger () virtual
Returns value as int.
Returns
value as integer.
Implements HEPREP::HepRepAttValue.
Definition at line 171 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 171 of file DefaultHepRepAttValue.cc
References getName(), longValue, and type.
Referenced by getAsString().
int64 cheprep::DefaultHepRepAttValue::getLong () virtual
Returns value as long.
Returns
value as long.
Implements HEPREP::HepRepAttValue.
Definition at line 166 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 166 of file DefaultHepRepAttValue.cc
References getName(), longValue, and type.
Referenced by getAsString().
string cheprep::DefaultHepRepAttValue::getLowerCaseName () virtual
Returns lowercased name of the attvalue.
Returns
Lowercased Name.
Implements HEPREP::HepRepAttValue.
Definition at line 128 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 128 of file DefaultHepRepAttValue.cc
References int(), name, and Acts::Test::transform.
string cheprep::DefaultHepRepAttValue::getLowerCaseString () virtual
Returns value as lowercase string.
Returns
value as string (if type is string).
Implements HEPREP::HepRepAttValue.
Definition at line 159 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 159 of file DefaultHepRepAttValue.cc
References getName(), int(), stringValue, Acts::Test::transform, and type.
string cheprep::DefaultHepRepAttValue::getName () virtual
Returns name of the attvalue.
Returns
Capitalized Name.
Implements HEPREP::HepRepAttValue.
Definition at line 124 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 124 of file DefaultHepRepAttValue.cc
References name.
Referenced by getBoolean(), getColor(), getDouble(), getInteger(), getLong(), getLowerCaseString(), and getString().
string cheprep::DefaultHepRepAttValue::getString () virtual
Returns value as string.
Returns
value as string (if type is string).
Implements HEPREP::HepRepAttValue.
Definition at line 154 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 154 of file DefaultHepRepAttValue.cc
References getName(), stringValue, and type.
Referenced by getAsString().
int cheprep::DefaultHepRepAttValue::getType () virtual
Returns type of the attvalue, defined in HepRepConstants with names TYPE_xxx.
Returns
type.
Implements HEPREP::HepRepAttValue.
Definition at line 134 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 134 of file DefaultHepRepAttValue.cc
References type.
string cheprep::DefaultHepRepAttValue::getTypeName () virtual
Returns the Java-like name for the type of this attvalue.
Returns
type name.
Implements HEPREP::HepRepAttValue.
Definition at line 138 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 138 of file DefaultHepRepAttValue.cc
References type.
void cheprep::DefaultHepRepAttValue::init (void) private
Definition at line 97 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 97 of file DefaultHepRepAttValue.cc
References labelStrings.
Referenced by DefaultHepRepAttValue().
int cheprep::DefaultHepRepAttValue::showLabel () virtual
Returns the flag bits for showing this attvalue as a label, defined in HepRepConstants with names SHOW_xxx.
Returns
flag bits if should be shown as label.
Implements HEPREP::HepRepAttValue.
Definition at line 150 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 150 of file DefaultHepRepAttValue.cc
References showLabelValue.
Referenced by toShowLabel().
string cheprep::DefaultHepRepAttValue::toShowLabel ()
Definition at line 240 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 240 of file DefaultHepRepAttValue.cc
References showLabel().
Referenced by cheprep::XMLWriter::setAttribute().
string cheprep::DefaultHepRepAttValue::toShowLabel (int showLabel) static
Definition at line 245 of file DefaultHepRepAttValue.cc.
View newest version in sPHENIX GitHub at line 245 of file DefaultHepRepAttValue.cc
References labelStrings, and LABELSTRINGS_LEN.
Member Data Documentation
bool cheprep::DefaultHepRepAttValue::booleanValue private
Definition at line 28 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 28 of file DefaultHepRepAttValue.h
Referenced by copy(), and getBoolean().
std::vector<double> cheprep::DefaultHepRepAttValue::colorValue private
Definition at line 29 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 29 of file DefaultHepRepAttValue.h
Referenced by copy(), and getColor().
double cheprep::DefaultHepRepAttValue::doubleValue private
Definition at line 27 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 27 of file DefaultHepRepAttValue.h
Referenced by copy(), and getDouble().
std::string cheprep::DefaultHepRepAttValue::labelStrings static private
Definition at line 32 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 32 of file DefaultHepRepAttValue.h
Referenced by init(), and toShowLabel().
int64 cheprep::DefaultHepRepAttValue::longValue private
Definition at line 26 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 26 of file DefaultHepRepAttValue.h
Referenced by copy(), getInteger(), and getLong().
std::string cheprep::DefaultHepRepAttValue::name private
Definition at line 20 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 20 of file DefaultHepRepAttValue.h
Referenced by getLowerCaseName(), and getName().
int cheprep::DefaultHepRepAttValue::showLabelValue private
Definition at line 31 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 31 of file DefaultHepRepAttValue.h
Referenced by copy(), and showLabel().
std::string cheprep::DefaultHepRepAttValue::stringValue private
Definition at line 25 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 25 of file DefaultHepRepAttValue.h
Referenced by copy(), getLowerCaseString(), and getString().
int cheprep::DefaultHepRepAttValue::type private
Definition at line 21 of file DefaultHepRepAttValue.h.
View newest version in sPHENIX GitHub at line 21 of file DefaultHepRepAttValue.h
Referenced by copy(), getAsString(), getBoolean(), getColor(), getDouble(), getInteger(), getLong(), getLowerCaseString(), getString(), getType(), and getTypeName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepAttValue.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/DefaultHepRepAttValue.cc