ECCE @ EIC Software: G4PVReplica Class Reference
G4PVReplica Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4PVReplica.hh>
Public Member Functions
G4PVReplica (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset=0.)
G4PVReplica (const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset=0.)
G4PVReplica (__void__ &)
G4PVReplica (const G4PVReplica &)=delete
G4PVReplica & operator= (const G4PVReplica &)=delete
virtual ~G4PVReplica ()
virtual EVolume VolumeType () const
G4bool IsMany () const
G4bool IsReplicated () const
virtual G4int GetCopyNo () const
virtual void SetCopyNo (G4int CopyNo)
virtual G4bool IsParameterised () const
virtual G4VPVParameterisation * GetParameterisation () const
virtual G4int GetMultiplicity () const
virtual void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const
virtual void SetRegularStructureId (G4int code)
G4bool IsRegularStructure () const
G4int GetRegularStructureId () const
G4int GetInstanceID () const
void InitialiseWorker (G4PVReplica *pMasterObject)
void TerminateWorker (G4PVReplica *pMasterObject)
Public Member Functions inherited from G4VPhysicalVolume
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4VPhysicalVolume (const G4VPhysicalVolume &)=delete
G4VPhysicalVolume & operator= (const G4VPhysicalVolume &)=delete
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
virtual G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int errMax=1)
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
EVolume DeduceVolumeType () const
Static Public Member Functions
static const G4PVRManager & GetSubInstanceManager ()
Static Public Member Functions inherited from G4VPhysicalVolume
static const G4PVManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions
G4PVReplica (const G4String &pName, G4int nReplicas, EAxis pAxis, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical)
Protected Member Functions inherited from G4VPhysicalVolume
void InitialiseWorker (G4VPhysicalVolume *pMasterObject, G4RotationMatrix *pRot, const G4ThreeVector &tlate)
void TerminateWorker (G4VPhysicalVolume *pMasterObject)
Protected Attributes
EAxis faxis
G4int fnReplicas
G4double fwidth
G4double foffset
Protected Attributes inherited from G4VPhysicalVolume
G4int instanceID
Private Member Functions
void CheckAndSetParameters (const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset)
void CheckOnlyDaughter (G4LogicalVolume *pMotherLogical)
Private Attributes
G4int fRegularVolsId = 0
G4int instanceID
Static Private Attributes
static G4GEOM_DLL G4PVRManager subInstanceManager
Additional Inherited Members
Static Protected Attributes inherited from G4VPhysicalVolume
static G4GEOM_DLL G4PVManager subInstanceManager
Detailed Description
Definition at line 113 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PVReplica.hh
Constructor & Destructor Documentation
G4PVReplica::G4PVReplica (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset = 0.)
Definition at line 83 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 83 of file G4PVReplica.cc
References G4LogicalVolume::AddDaughter(), CheckAndSetParameters(), G4GeomSplitter< T >::CreateSubInstance(), FatalException, G4endl, G4Exception(), G4MT_copyNo, G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), instanceID, message(), G4VPhysicalVolume::SetMotherLogical(), and subInstanceManager.
G4PVReplica::G4PVReplica (const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset = 0.)
Definition at line 37 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 37 of file G4PVReplica.cc
References G4LogicalVolume::AddDaughter(), CheckAndSetParameters(), G4GeomSplitter< T >::CreateSubInstance(), FatalException, G4endl, G4Exception(), G4MT_copyNo, G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), instanceID, message(), G4VPhysicalVolume::SetMotherLogical(), and subInstanceManager.
G4PVReplica::G4PVReplica (__void__ & a)
Definition at line 242 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 242 of file G4PVReplica.cc
References G4GeomSplitter< T >::CreateSubInstance(), G4MT_copyNo, instanceID, and subInstanceManager.
G4PVReplica::G4PVReplica (const G4PVReplica &) delete
G4PVReplica::~G4PVReplica () virtual
Definition at line 249 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 249 of file G4PVReplica.cc
References faxis, G4VPhysicalVolume::GetRotation(), and kPhi.
G4PVReplica::G4PVReplica (const G4String & pName, G4int nReplicas, EAxis pAxis, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical) protected
Definition at line 129 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 129 of file G4PVReplica.cc
References CheckAndSetParameters(), CheckOnlyDaughter(), G4GeomSplitter< T >::CreateSubInstance(), FatalException, G4Exception(), G4MT_copyNo, instanceID, message(), and subInstanceManager.
Member Function Documentation
void G4PVReplica::CheckAndSetParameters (const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset) private
Definition at line 195 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 195 of file G4PVReplica.cc
References FatalException, faxis, fnReplicas, foffset, fwidth, G4Exception(), kPhi, kRho, kUndefined, kXAxis, kYAxis, kZAxis, offset, and G4VPhysicalVolume::SetRotation().
Referenced by G4PVReplica().
void G4PVReplica::CheckOnlyDaughter (G4LogicalVolume * pMotherLogical) private
Definition at line 177 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 177 of file G4PVReplica.cc
References FatalException, G4endl, G4Exception(), G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), and message().
Referenced by G4PVReplica().
G4int G4PVReplica::GetCopyNo () const virtual
Implements G4VPhysicalVolume.
Definition at line 262 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 262 of file G4PVReplica.cc
References G4MT_copyNo.
G4int G4PVReplica::GetInstanceID () const inline
Definition at line 172 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 172 of file G4PVReplica.hh
References instanceID.
G4int G4PVReplica::GetMultiplicity () const virtual
Reimplemented from G4VPhysicalVolume.
Definition at line 287 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 287 of file G4PVReplica.cc
References fnReplicas.
Referenced by G4PVParameterised::CheckOverlaps(), GB06ParallelWorldForSlices::ConstructSD(), G4LogicalVolumeModel::DescribeYourselfTo(), and export_G4PVReplica().
G4VPVParameterisation * G4PVReplica::GetParameterisation () const virtual
Implements G4VPhysicalVolume.
Reimplemented in G4PVParameterised.
Definition at line 282 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 282 of file G4PVReplica.cc
G4int G4PVReplica::GetRegularStructureId () const virtual
Implements G4VPhysicalVolume.
Definition at line 315 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 315 of file G4PVReplica.cc
References fRegularVolsId.
void G4PVReplica::GetReplicationData (EAxis & axis, G4int & nReplicas, G4double & width, G4double & offset, G4bool & consuming) const virtual
Implements G4VPhysicalVolume.
Reimplemented in G4PVParameterised.
Definition at line 297 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 297 of file G4PVReplica.cc
References faxis, fnReplicas, foffset, and fwidth.
Referenced by G4tgbGeometryDumper::DumpPVReplica().
const G4PVRManager & G4PVReplica::GetSubInstanceManager () static
Definition at line 327 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 327 of file G4PVReplica.cc
References subInstanceManager.
Referenced by G4GeometryWorkspace::G4GeometryWorkspace().
void G4PVReplica::InitialiseWorker (G4PVReplica * pMasterObject)
Definition at line 338 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 338 of file G4PVReplica.cc
References FatalException, faxis, G4Exception(), G4MT_copyNo, G4VPhysicalVolume::InitialiseWorker(), kPhi, kRho, kUndefined, kXAxis, kYAxis, kZAxis, G4VPhysicalVolume::SetRotation(), G4GeomSplitter< T >::SlaveCopySubInstanceArray(), and subInstanceManager.
Referenced by G4GeometryWorkspace::InitialisePhysicalVolumes().
G4bool G4PVReplica::IsMany () const virtual
Implements G4VPhysicalVolume.
Definition at line 257 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 257 of file G4PVReplica.cc
G4bool G4PVReplica::IsParameterised () const virtual
Implements G4VPhysicalVolume.
Reimplemented in G4PVParameterised.
Definition at line 277 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 277 of file G4PVReplica.cc
Referenced by G4GeometryWorkspace::InitialisePhysicalVolumes().
G4bool G4PVReplica::IsRegularStructure () const virtual
Implements G4VPhysicalVolume.
Definition at line 310 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 310 of file G4PVReplica.cc
References fRegularVolsId.
G4bool G4PVReplica::IsReplicated () const virtual
Implements G4VPhysicalVolume.
Definition at line 272 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 272 of file G4PVReplica.cc
G4PVReplica& G4PVReplica::operator= (const G4PVReplica &) delete
void G4PVReplica::SetCopyNo (G4int CopyNo) virtual
Implements G4VPhysicalVolume.
Definition at line 267 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 267 of file G4PVReplica.cc
References G4MT_copyNo.
void G4PVReplica::SetRegularStructureId (G4int code) virtual
Reimplemented in G4PVParameterised.
Definition at line 320 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 320 of file G4PVReplica.cc
References fRegularVolsId.
Referenced by G4PVParameterised::SetRegularStructureId().
void G4PVReplica::TerminateWorker (G4PVReplica * pMasterObject)
Definition at line 383 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 383 of file G4PVReplica.cc
References faxis, G4VPhysicalVolume::GetRotation(), and kPhi.
Referenced by G4GeometryWorkspace::DestroyWorkspace().
EVolume G4PVReplica::VolumeType () const virtual
Implements G4VPhysicalVolume.
Reimplemented in G4PVParameterised.
Definition at line 292 of file G4PVReplica.cc.
View newest version in sPHENIX GitHub at line 292 of file G4PVReplica.cc
References kReplica.
Member Data Documentation
EAxis G4PVReplica::faxis protected
Definition at line 206 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 206 of file G4PVReplica.hh
Referenced by CheckAndSetParameters(), G4PVParameterised::GetReplicationData(), GetReplicationData(), InitialiseWorker(), TerminateWorker(), and ~G4PVReplica().
G4int G4PVReplica::fnReplicas protected
Definition at line 207 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 207 of file G4PVReplica.hh
Referenced by CheckAndSetParameters(), GetMultiplicity(), G4PVParameterised::GetReplicationData(), and GetReplicationData().
G4double G4PVReplica::foffset protected
Definition at line 208 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 208 of file G4PVReplica.hh
Referenced by CheckAndSetParameters(), G4PVParameterised::GetReplicationData(), and GetReplicationData().
G4int G4PVReplica::fRegularVolsId = 0 private
Definition at line 212 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 212 of file G4PVReplica.hh
Referenced by GetRegularStructureId(), IsRegularStructure(), and SetRegularStructureId().
G4double G4PVReplica::fwidth protected
Definition at line 208 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 208 of file G4PVReplica.hh
Referenced by CheckAndSetParameters(), G4PVParameterised::GetReplicationData(), and GetReplicationData().
G4int G4PVReplica::instanceID private
Definition at line 214 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 214 of file G4PVReplica.hh
Referenced by G4PVReplica(), and GetInstanceID().
G4PVRManager G4PVReplica::subInstanceManager static private
Definition at line 216 of file G4PVReplica.hh.
View newest version in sPHENIX GitHub at line 216 of file G4PVReplica.hh
Referenced by G4PVReplica(), GetSubInstanceManager(), and InitialiseWorker().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4PVReplica.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4PVReplica.cc