ECCE @ EIC Software: G4GammaParticipants Class Reference
G4GammaParticipants Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4GammaParticipants.hh>
Public Member Functions
virtual ~G4GammaParticipants ()
Public Member Functions inherited from G4QGSParticipants
G4QGSParticipants ()
G4QGSParticipants (const G4QGSParticipants &right)
const G4QGSParticipants & operator= (const G4QGSParticipants &right)
virtual ~G4QGSParticipants ()
G4bool operator== (const G4QGSParticipants &right) const
G4bool operator!= (const G4QGSParticipants &right) const
virtual void DoLorentzBoost (G4ThreeVector aBoost)
G4PartonPair * GetNextPartonPair ()
void BuildInteractions (const G4ReactionProduct &thePrimary)
void StartPartonPairLoop ()
Public Member Functions inherited from G4VParticipants
G4VParticipants ()
G4VParticipants (const G4VParticipants &right)
virtual ~G4VParticipants ()
const G4VParticipants & operator= (const G4VParticipants &right)
G4bool operator== (const G4VParticipants &right) const
G4bool operator!= (const G4VParticipants &right) const
virtual void Init (G4int theZ, G4int theA)
virtual void SetNucleus (G4V3DNucleus *aNucleus)
virtual G4V3DNucleus * GetWoundedNucleus () const
virtual void InitProjectileNucleus (G4int theZ, G4int theA)
virtual void SetProjectileNucleus (G4V3DNucleus *aNucleus)
Private Member Functions
virtual G4VSplitableHadron * SelectInteractions (const G4ReactionProduct &thePrimary)
Additional Inherited Members
Public Attributes inherited from G4VParticipants
G4V3DNucleus * theNucleus
G4V3DNucleus * theProjectileNucleus
Protected Types inherited from G4QGSParticipants
enum { SOFT, DIFFRACTIVE }
enum { ALL, WITHOUT_R, NON_DIFF }
enum {
PrD, TrD, DD, NonD,
Qexc
}
Protected Member Functions inherited from G4QGSParticipants
void SplitHadrons ()
void PerformSoftCollisions ()
void PerformDiffractiveCollisions ()
G4bool DeterminePartonMomenta ()
G4double SampleX (G4double anXmin, G4int nSea, G4int theTotalSea, G4double aBeta)
Protected Attributes inherited from G4QGSParticipants
std::vector
< G4InteractionContent * > theInteractions
std::vector< G4VSplitableHadron * > theTargets
std::vector< G4PartonPair * > thePartonPairs
G4QuarkExchange theQuarkExchange
G4SingleDiffractiveExcitation theSingleDiffExcitation
G4QGSDiffractiveExcitation theDiffExcitaton
G4int ModelMode
G4ThreeVector theBoost
const G4int nCutMax
const G4double ThresholdParameter
const G4double QGSMThreshold
const G4double theNucleonRadius
G4ThreeVector theCurrentVelocity
G4QGSMSplitableHadron * theProjectileSplitable
Detailed Description
Definition at line 37 of file G4GammaParticipants.hh.
View newest version in sPHENIX GitHub at line 37 of file G4GammaParticipants.hh
Constructor & Destructor Documentation
virtual G4GammaParticipants::~G4GammaParticipants () inline virtual
Definition at line 40 of file G4GammaParticipants.hh.
View newest version in sPHENIX GitHub at line 40 of file G4GammaParticipants.hh
Member Function Documentation
G4VSplitableHadron * G4GammaParticipants::SelectInteractions (const G4ReactionProduct & thePrimary) private virtual
Reimplemented from G4QGSParticipants.
Definition at line 36 of file G4GammaParticipants.cc.
View newest version in sPHENIX GitHub at line 36 of file G4GammaParticipants.cc
References G4QGSParticipants::DIFFRACTIVE, G4cout, G4endl, G4UniformRand, G4ReactionProduct::GetMass(), G4V3DNucleus::GetMassNumber(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4VSplitableHadron::GetStatus(), G4ReactionProduct::GetTotalEnergy(), G4Nucleon::Hit(), G4VSplitableHadron::IncrementCollisionCount(), G4QGSParticipants::ModelMode, G4QGSParticipants::QGSMThreshold, S(), G4VSplitableHadron::SetCollisionCount(), G4InteractionContent::SetNumberOfDiffractiveCollisions(), G4InteractionContent::SetNumberOfSoftCollisions(), G4InteractionContent::SetStatus(), G4VSplitableHadron::SetStatus(), G4InteractionContent::SetTarget(), G4InteractionContent::SetTargetNucleon(), G4QGSParticipants::SOFT, sqr(), G4V3DNucleus::StartLoop(), G4QGSParticipants::theInteractions, G4VParticipants::theNucleus, G4QGSParticipants::theProjectileSplitable, G4QGSParticipants::theTargets, G4QGSParticipants::ThresholdParameter, and TRUE.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4GammaParticipants.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4GammaParticipants.cc