ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/externals/zlib/src/compress.c File Reference
compress.c File Reference
#include "zlib.h"
Macros
#define ZLIB_INTERNAL
Functions
int ZEXPORT compress2 (Bytef *dest, uLongf *destLen, const Bytef *source, uLong sourceLen, int level)
int ZEXPORT compress (Bytef *dest, uLongf *destLen, const Bytef *source, uLong sourceLen)
uLong ZEXPORT compressBound (uLong sourceLen)
Macro Definition Documentation
#define ZLIB_INTERNAL
Definition at line 7 of file compress.c.
View newest version in sPHENIX GitHub at line 7 of file compress.c
Function Documentation
int ZEXPORT compress (Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen)
Definition at line 67 of file compress.c.
View newest version in sPHENIX GitHub at line 67 of file compress.c
References compress2(), and Z_DEFAULT_COMPRESSION.
Referenced by alphas(), converttohepmc(), deriv(), dofistatescat(), doinstatescat(), dokinematics(), Fun4AllHistoManager::dumpHistos(), generatez(), genevent(), getdeltat(), getinspliti(), getinsudafast(), getinsudakov(), getinsudared(), getmass(), getnewmass(), getpdf(), getpdfxintexact(), getpnorad1(), getqvec(), getspliti(), getsscat(), getsudakov(), gett(), getxsecint(), init(), initpythia(), insudaint(), intpgghigh(), intpgglow(), intpqghigh(), intpqglow(), intpqq(), makebranch(), makecascade(), makeinsplit(), makesplitting(), makestrings_minl(), makestrings_vac(), pdfint(), scatprimfunc(), ShowerCompress(), splitfncint(), and xsecint().
int ZEXPORT compress2 (Bytef * dest, uLongf * destLen, const Bytef * source, uLong sourceLen, int level)
Definition at line 21 of file compress.c.
View newest version in sPHENIX GitHub at line 21 of file compress.c
References z_stream_s::avail_in, z_stream_s::avail_out, deflate(), deflateEnd(), deflateInit, check_license::err(), left, max, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, z_stream_s::total_out, Z_FINISH, Z_NO_FLUSH, Z_OK, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by compress(), and ogzBuffer::writeout().
uLong ZEXPORT compressBound (uLong sourceLen)
Definition at line 80 of file compress.c.
View newest version in sPHENIX GitHub at line 80 of file compress.c