ECCE @ EIC Software: acts/blob/master/Core/src/Material/MaterialProperties.cpp File Reference
MaterialProperties.cpp File Reference
#include "Acts/Material/MaterialProperties.hpp"
#include <climits>
#include <limits>
#include <ostream>
Variables
static constexpr auto eps = 2 * std::numeric_limits<float>::epsilon()
Variable Documentation
constexpr auto eps = 2 * std::numeric_limits<float>::epsilon() static
Definition at line 15 of file MaterialProperties.cpp.
View newest version in sPHENIX GitHub at line 15 of file MaterialProperties.cpp
Referenced by G4MagInt_Driver::AccurateAdvance(), G4ParticleHPCaptureFS::ApplyYourself(), CLHEP::HepRotation::axis(), G4ParticleHPInelasticBaseFS::BaseApply(), BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFMicroPartition::CalcPartitionTemperature(), calcta(), G4GeomTools::comp_ellint_2(), G4ParticleHPInelasticCompFS::CompositeApply(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4PairProductionRelModel::ComputeDXSectionPerAtom(), Acts::computeEnergyLossBethe(), Acts::computeEnergyLossLandau(), G4PairProductionRelModel::ComputeRelDXSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeScreeningFunctions(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), Acts::deriveEnergyLossBetheQOverP(), Acts::deriveEnergyLossLandauQOverP(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4ScreenedCoulombClassicalKinematics::DoScreeningComputation(), G4VSolid::EstimateSurfaceArea(), expai(), expaid(), G4ecpssrBaseKxsModel::ExpIntFunction(), G4ecpssrBaseLixsModel::ExpIntFunction(), fg(), fgp(), G4RKPropagation::FieldTransport(), G4DNAElectronHoleRecombination::FindReactant(), G4StatMF::FindTemperatureOfBreakingChannel(), G4MuonRadiativeDecayChannelWithSpin::fron(), MyGamma::GamCf(), MyGamma::GamSer(), gauss1(), gauss2(), gauss3(), gauss4(), G4Abla::gcf(), generatez(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), getmass(), G4PenelopeBremsstrahlungFS::GetMomentumIntegral(), G4HyperNucleiProperties::GetNuclearMass(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4Abla::gser(), G4ParticleHPInelasticBaseFS::InitGammas(), G4PolarizedAnnihilationCrossSection::Initialize(), G4PolarizedComptonCrossSection::Initialize(), G4LEPTSDiffXS::InterpolateCDXS(), G4NativeScreenedCoulombCrossSection::LoadData(), makesplitting(), G4DensityEffectCalculator::Newton(), odeint(), G4LindhardRobinsonPartition::PartitionNIEL(), ptwXY_createFromFunction(), ptwXY_flatInterpolationToLinear_eps(), pygaga(), pygau2(), pygaus(), pyhii3au(), pyhisigh(), pyhiw1au(), pyhiw2au(), pyhiwidt(), pyi3au(), pykmap(), pymirm(), pypole(), pyrand(), pyrvgw(), pysigh(), pystat(), pytbdy(), pyw1au(), pyw2au(), pywaux(), pywidt(), pyxtot(), G4MagInt_Driver::QuickAdvance(), G4InuclSpecialFunctions::randomGauss(), G4VEmissionProbability::ResetIntegrator(), rkstepper(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), serai(), seraid(), G4DNATransformElectronModel::SetEpsilonEnergy(), F04GlobalField::SetEpsMax(), F04GlobalField::SetEpsMin(), CLHEP::transformSmall(), CLHEP::RandGaussQ::transformSmall(), and G4MagInt_Driver::WarnEndPointTooFar().