ECCE @ EIC Software: RMC01AnalysisManager Class Reference
RMC01AnalysisManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/RMC01AnalysisManager.hh>
Public Member Functions
~RMC01AnalysisManager ()
void BeginOfRun (const G4Run *)
void EndOfRun (const G4Run *)
void BeginOfEvent (const G4Event *)
void EndOfEvent (const G4Event *)
void SetPrimaryExpSpectrumForAdjointSim (const G4String &particle_name, G4double fluence, G4double E0, G4double Emin, G4double Emax)
void SetPrimaryPowerLawSpectrumForAdjointSim (const G4String &particle_name, G4double fluence, G4double alpha, G4double Emin, G4double Emax)
void SetPrecision (G4double precision)
void Book ()
void Save (G4double scaling_factor)
Static Public Member Functions
static RMC01AnalysisManager * GetInstance ()
Private Member Functions
RMC01AnalysisManager ()
void EndOfEventForForwardSimulation (const G4Event *anEvent)
void EndOfEventForAdjointSimulation (const G4Event *anEvent)
G4double PrimDiffAndDirFluxForAdjointSim (G4double prim_energy)
void ComputeMeanEdepAndError (const G4Event *anEvent, G4double &mean, G4double &error)
Private Attributes
RMC01AnalysisManagerMessenger * fMsg
G4H1 * fEdep_vs_prim_ekin
G4H1 * fElectron_current
G4H1 * fProton_current
G4H1 * fGamma_current
G4double fAccumulated_edep
G4double fAccumulated_edep2
G4double fNentry
G4double fMean_edep
G4double fError_mean_edep
G4double fRelative_error
G4double fElapsed_time
G4double fPrecision_to_reach
G4bool fStop_run_if_precision_reached
G4int fNb_evt_modulo_for_convergence_test
G4H1 * fEdep_rmatrix_vs_electron_prim_energy
G4H2 * fElectron_current_rmatrix_vs_electron_prim_energy
G4H2 * fGamma_current_rmatrix_vs_electron_prim_energy
G4H1 * fEdep_rmatrix_vs_gamma_prim_energy
G4H2 * fElectron_current_rmatrix_vs_gamma_prim_energy
G4H2 * fGamma_current_rmatrix_vs_gamma_prim_energy
G4H1 * fEdep_rmatrix_vs_proton_prim_energy
G4H2 * fElectron_current_rmatrix_vs_proton_prim_energy
G4H2 * fProton_current_rmatrix_vs_proton_prim_energy
G4H2 * fGamma_current_rmatrix_vs_proton_prim_energy
G4String fFileName [2]
G4bool fFactoryOn
PRIM_SPECTRUM_TYPE fPrimSpectrumType
G4int fPrimPDG_ID
G4double fAlpha_or_E0
G4double fAmplitude_prim_spectrum
G4double fEmin_prim_spectrum
G4double fEmax_prim_spectrum
G4bool fAdjoint_sim_mode
G4int fNb_evt_per_adj_evt
G4Timer * fTimer
std::fstream fConvergenceFileOutput
Static Private Attributes
static RMC01AnalysisManager * fInstance = 0
Detailed Description
Definition at line 76 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 76 of file RMC01AnalysisManager.hh
Constructor & Destructor Documentation
RMC01AnalysisManager::~RMC01AnalysisManager ()
Definition at line 101 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 101 of file RMC01AnalysisManager.cc
RMC01AnalysisManager::RMC01AnalysisManager () private
Definition at line 59 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 59 of file RMC01AnalysisManager.cc
References G4Electron::Electron(), fFileName, fMsg, fPrimPDG_ID, fTimer, and G4ParticleDefinition::GetPDGEncoding().
Referenced by GetInstance().
Member Function Documentation
void RMC01AnalysisManager::BeginOfEvent (const G4Event *)
Definition at line 175 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 175 of file RMC01AnalysisManager.cc
Referenced by RMC01EventAction::BeginOfEventAction().
void RMC01AnalysisManager::BeginOfRun (const G4Run * aRun)
Definition at line 115 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 115 of file RMC01AnalysisManager.cc
References Book(), fAccumulated_edep, fAccumulated_edep2, fAdjoint_sim_mode, fConvergenceFileOutput, fElapsed_time, fError_mean_edep, fMean_edep, fNb_evt_per_adj_evt, fNentry, fRelative_error, fTimer, G4AdjointSimManager::GetAdjointSimMode(), G4AdjointSimManager::GetInstance(), G4AdjointSimManager::GetNbEvtOfLastRun(), G4Run::GetNumberOfEventToBeProcessed(), and G4Timer::Start().
Referenced by RMC01RunAction::BeginOfRunAction().
void RMC01AnalysisManager::Book ()
Definition at line 604 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 604 of file RMC01AnalysisManager.cc
References G4VAnalysisManager::CreateH1(), emax, CEMC_TOWER::emin, fAdjoint_sim_mode, fEdep_rmatrix_vs_electron_prim_energy, fEdep_rmatrix_vs_gamma_prim_energy, fEdep_rmatrix_vs_proton_prim_energy, fEdep_vs_prim_ekin, fElectron_current, fElectron_current_rmatrix_vs_electron_prim_energy, fElectron_current_rmatrix_vs_gamma_prim_energy, fElectron_current_rmatrix_vs_proton_prim_energy, fFactoryOn, fFileName, fGamma_current, fGamma_current_rmatrix_vs_electron_prim_energy, fGamma_current_rmatrix_vs_gamma_prim_energy, fGamma_current_rmatrix_vs_proton_prim_energy, fProton_current, fProton_current_rmatrix_vs_proton_prim_energy, G4cout, G4endl, G4VAnalysisManager::GetFileType(), G4ToolsAnalysisManager::GetH1(), G4ToolsAnalysisManager::GetH2(), GeV, G4ToolsAnalysisManager::Instance(), keV, G4VAnalysisManager::OpenFile(), G4VAnalysisManager::SetFirstHistoId(), and G4VAnalysisManager::SetHistoDirectoryName().
Referenced by BeginOfRun().
void RMC01AnalysisManager::ComputeMeanEdepAndError (const G4Event * anEvent, G4double & mean, G4double & error) private
Definition at line 508 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 508 of file RMC01AnalysisManager.cc
References fAccumulated_edep, fAccumulated_edep2, fAdjoint_sim_mode, fNb_evt_per_adj_evt, G4Event::GetEventID(), G4AdjointSimManager::GetInstance(), G4AdjointSimManager::GetNbEvtOfLastRun(), max, norm, and zz.
Referenced by EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
void RMC01AnalysisManager::EndOfEvent (const G4Event * anEvent)
Definition at line 181 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 181 of file RMC01AnalysisManager.cc
References G4RunManager::AbortRun(), EndOfEventForAdjointSimulation(), EndOfEventForForwardSimulation(), fAdjoint_sim_mode, fConvergenceFileOutput, fElapsed_time, fError_mean_edep, fMean_edep, fNb_evt_modulo_for_convergence_test, fNb_evt_per_adj_evt, fPrecision_to_reach, fRelative_error, fStop_run_if_precision_reached, fTimer, G4cout, G4Event::GetEventID(), G4Timer::GetRealElapsed(), G4RunManager::GetRunManager(), G4Timer::Start(), and G4Timer::Stop().
Referenced by RMC01EventAction::EndOfEventAction().
void RMC01AnalysisManager::EndOfEventForAdjointSimulation (const G4Event * anEvent) private
Definition at line 289 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 289 of file RMC01AnalysisManager.cc
References cm2, ComputeMeanEdepAndError(), edep, G4Electron::Electron(), G4THitsCollection< T >::entries(), fAccumulated_edep, fAccumulated_edep2, fEdep_rmatrix_vs_electron_prim_energy, fEdep_rmatrix_vs_gamma_prim_energy, fEdep_rmatrix_vs_proton_prim_energy, fEdep_vs_prim_ekin, fElectron_current, fElectron_current_rmatrix_vs_electron_prim_energy, fElectron_current_rmatrix_vs_gamma_prim_energy, fElectron_current_rmatrix_vs_proton_prim_energy, fEmax_prim_spectrum, fEmin_prim_spectrum, fError_mean_edep, fGamma_current, fGamma_current_rmatrix_vs_electron_prim_energy, fGamma_current_rmatrix_vs_gamma_prim_energy, fGamma_current_rmatrix_vs_proton_prim_energy, fMean_edep, fNentry, fPrimPDG_ID, fProton_current, fProton_current_rmatrix_vs_proton_prim_energy, fRelative_error, G4cout, G4Gamma::Gamma(), G4SDManager::GetCollectionID(), G4AdjointSimManager::GetEkinAtEndOfLastAdjointTrack(), G4AdjointSimManager::GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4AdjointSimManager::GetInstance(), G4AdjointSimManager::GetNbOfAdointTracksReachingTheExternalSurface(), G4SDManager::GetSDMpointer(), G4AdjointSimManager::GetWeightAtEndOfLastAdjointTrack(), PrimDiffAndDirFluxForAdjointSim(), G4Proton::Proton(), and weight.
Referenced by EndOfEvent().
void RMC01AnalysisManager::EndOfEventForForwardSimulation (const G4Event * anEvent) private
Definition at line 220 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 220 of file RMC01AnalysisManager.cc
References ComputeMeanEdepAndError(), G4THitsCollection< T >::entries(), fAccumulated_edep, fAccumulated_edep2, fEdep_vs_prim_ekin, fElectron_current, fError_mean_edep, fGamma_current, fMean_edep, fNentry, fProton_current, fRelative_error, G4SDManager::GetCollectionID(), G4PrimaryParticle::GetG4code(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4PrimaryParticle::GetMomentum(), G4ParticleDefinition::GetPDGMass(), G4PrimaryVertex::GetPrimary(), G4Event::GetPrimaryVertex(), G4SDManager::GetSDMpointer(), CLHEP::Hep3Vector::mag(), P, and weight.
Referenced by EndOfEvent().
void RMC01AnalysisManager::EndOfRun (const G4Run * aRun)
Definition at line 152 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 152 of file RMC01AnalysisManager.cc
References fAdjoint_sim_mode, fConvergenceFileOutput, fError_mean_edep, fMean_edep, fNb_evt_per_adj_evt, fTimer, G4cout, G4AdjointSimManager::GetInstance(), G4AdjointSimManager::GetNbEvtOfLastRun(), G4Run::GetNumberOfEvent(), Save(), and G4Timer::Stop().
Referenced by RMC01RunAction::EndOfRunAction().
RMC01AnalysisManager * RMC01AnalysisManager::GetInstance (void) static
Definition at line 107 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 107 of file RMC01AnalysisManager.cc
References fInstance, and RMC01AnalysisManager().
Referenced by RMC01EventAction::BeginOfEventAction(), RMC01EventAction::EndOfEventAction(), and RMC01RunAction::RMC01RunAction().
G4double RMC01AnalysisManager::PrimDiffAndDirFluxForAdjointSim (G4double prim_energy) private
Definition at line 457 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 457 of file RMC01AnalysisManager.cc
References EXPO, fAlpha_or_E0, fAmplitude_prim_spectrum, and fPrimSpectrumType.
Referenced by EndOfEventForAdjointSimulation().
void RMC01AnalysisManager::Save (G4double scaling_factor)
Definition at line 766 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 766 of file RMC01AnalysisManager.cc
References G4VAnalysisManager::CloseFile(), fFactoryOn, fFileName, G4cout, G4endl, G4VAnalysisManager::GetNofH1s(), G4VAnalysisManager::GetNofH2s(), G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::ScaleH1(), G4VAnalysisManager::ScaleH2(), G4VAnalysisManager::SetH1Ascii(), and G4VAnalysisManager::Write().
Referenced by EndOfRun().
void RMC01AnalysisManager::SetPrecision (G4double precision) inline
Definition at line 96 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 96 of file RMC01AnalysisManager.hh
References fPrecision_to_reach.
Referenced by RMC01AnalysisManagerMessenger::SetNewValue().
void RMC01AnalysisManager::SetPrimaryExpSpectrumForAdjointSim (const G4String & particle_name, G4double fluence, G4double E0, G4double Emin, G4double Emax)
Definition at line 545 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 545 of file RMC01AnalysisManager.cc
References G4Electron::Electron(), Emax, Emin, EXPO, fAlpha_or_E0, fAmplitude_prim_spectrum, fEmax_prim_spectrum, fEmin_prim_spectrum, fPrimPDG_ID, fPrimSpectrumType, G4cout, G4endl, G4Gamma::Gamma(), G4ParticleDefinition::GetPDGEncoding(), pi, and G4Proton::Proton().
Referenced by RMC01AnalysisManagerMessenger::SetNewValue().
void RMC01AnalysisManager::SetPrimaryPowerLawSpectrumForAdjointSim (const G4String & particle_name, G4double fluence, G4double alpha, G4double Emin, G4double Emax)
Definition at line 570 of file RMC01AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 570 of file RMC01AnalysisManager.cc
References alpha, G4Electron::Electron(), Emax, Emin, fAlpha_or_E0, fAmplitude_prim_spectrum, fEmax_prim_spectrum, fEmin_prim_spectrum, fPrimPDG_ID, fPrimSpectrumType, G4cout, G4endl, G4Gamma::Gamma(), G4ParticleDefinition::GetPDGEncoding(), pi, POWER, and G4Proton::Proton().
Referenced by RMC01AnalysisManagerMessenger::SetNewValue().
Member Data Documentation
G4double RMC01AnalysisManager::fAccumulated_edep private
Definition at line 137 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 137 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), ComputeMeanEdepAndError(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4double RMC01AnalysisManager::fAccumulated_edep2 private
Definition at line 138 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 138 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), ComputeMeanEdepAndError(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4bool RMC01AnalysisManager::fAdjoint_sim_mode private
Definition at line 178 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 178 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), Book(), ComputeMeanEdepAndError(), EndOfEvent(), and EndOfRun().
G4double RMC01AnalysisManager::fAlpha_or_E0 private
Definition at line 174 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 174 of file RMC01AnalysisManager.hh
Referenced by PrimDiffAndDirFluxForAdjointSim(), SetPrimaryExpSpectrumForAdjointSim(), and SetPrimaryPowerLawSpectrumForAdjointSim().
G4double RMC01AnalysisManager::fAmplitude_prim_spectrum private
Definition at line 175 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 175 of file RMC01AnalysisManager.hh
Referenced by PrimDiffAndDirFluxForAdjointSim(), SetPrimaryExpSpectrumForAdjointSim(), and SetPrimaryPowerLawSpectrumForAdjointSim().
std::fstream RMC01AnalysisManager::fConvergenceFileOutput private
Definition at line 184 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 184 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4H1* RMC01AnalysisManager::fEdep_rmatrix_vs_electron_prim_energy private
Definition at line 151 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 151 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H1* RMC01AnalysisManager::fEdep_rmatrix_vs_gamma_prim_energy private
Definition at line 155 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 155 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H1* RMC01AnalysisManager::fEdep_rmatrix_vs_proton_prim_energy private
Definition at line 159 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 159 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H1* RMC01AnalysisManager::fEdep_vs_prim_ekin private
Definition at line 125 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 125 of file RMC01AnalysisManager.hh
Referenced by Book(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4double RMC01AnalysisManager::fElapsed_time private
Definition at line 143 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 143 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), and EndOfEvent().
G4H1* RMC01AnalysisManager::fElectron_current private
Definition at line 126 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 126 of file RMC01AnalysisManager.hh
Referenced by Book(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4H2* RMC01AnalysisManager::fElectron_current_rmatrix_vs_electron_prim_energy private
Definition at line 152 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 152 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H2* RMC01AnalysisManager::fElectron_current_rmatrix_vs_gamma_prim_energy private
Definition at line 156 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 156 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H2* RMC01AnalysisManager::fElectron_current_rmatrix_vs_proton_prim_energy private
Definition at line 160 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 160 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4double RMC01AnalysisManager::fEmax_prim_spectrum private
Definition at line 177 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 177 of file RMC01AnalysisManager.hh
Referenced by EndOfEventForAdjointSimulation(), SetPrimaryExpSpectrumForAdjointSim(), and SetPrimaryPowerLawSpectrumForAdjointSim().
G4double RMC01AnalysisManager::fEmin_prim_spectrum private
Definition at line 176 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 176 of file RMC01AnalysisManager.hh
Referenced by EndOfEventForAdjointSimulation(), SetPrimaryExpSpectrumForAdjointSim(), and SetPrimaryPowerLawSpectrumForAdjointSim().
G4double RMC01AnalysisManager::fError_mean_edep private
Definition at line 141 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 141 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfEventForAdjointSimulation(), EndOfEventForForwardSimulation(), and EndOfRun().
G4bool RMC01AnalysisManager::fFactoryOn private
Definition at line 165 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 165 of file RMC01AnalysisManager.hh
Referenced by Book(), and Save().
G4String RMC01AnalysisManager::fFileName[2] private
Definition at line 164 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 164 of file RMC01AnalysisManager.hh
Referenced by Book(), RMC01AnalysisManager(), and Save().
G4H1* RMC01AnalysisManager::fGamma_current private
Definition at line 128 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 128 of file RMC01AnalysisManager.hh
Referenced by Book(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4H2* RMC01AnalysisManager::fGamma_current_rmatrix_vs_electron_prim_energy private
Definition at line 153 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 153 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H2* RMC01AnalysisManager::fGamma_current_rmatrix_vs_gamma_prim_energy private
Definition at line 157 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 157 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4H2* RMC01AnalysisManager::fGamma_current_rmatrix_vs_proton_prim_energy private
Definition at line 162 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 162 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
RMC01AnalysisManager * RMC01AnalysisManager::fInstance = 0 static private
Definition at line 105 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 105 of file RMC01AnalysisManager.hh
Referenced by GetInstance().
G4double RMC01AnalysisManager::fMean_edep private
Definition at line 140 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 140 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfEventForAdjointSimulation(), EndOfEventForForwardSimulation(), and EndOfRun().
RMC01AnalysisManagerMessenger* RMC01AnalysisManager::fMsg private
Definition at line 121 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 121 of file RMC01AnalysisManager.hh
Referenced by RMC01AnalysisManager().
G4int RMC01AnalysisManager::fNb_evt_modulo_for_convergence_test private
Definition at line 146 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 146 of file RMC01AnalysisManager.hh
Referenced by EndOfEvent().
G4int RMC01AnalysisManager::fNb_evt_per_adj_evt private
Definition at line 179 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 179 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), ComputeMeanEdepAndError(), EndOfEvent(), and EndOfRun().
G4double RMC01AnalysisManager::fNentry private
Definition at line 139 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 139 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4double RMC01AnalysisManager::fPrecision_to_reach private
Definition at line 144 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 144 of file RMC01AnalysisManager.hh
Referenced by EndOfEvent(), and SetPrecision().
G4int RMC01AnalysisManager::fPrimPDG_ID private
Definition at line 173 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 173 of file RMC01AnalysisManager.hh
Referenced by EndOfEventForAdjointSimulation(), RMC01AnalysisManager(), SetPrimaryExpSpectrumForAdjointSim(), and SetPrimaryPowerLawSpectrumForAdjointSim().
PRIM_SPECTRUM_TYPE RMC01AnalysisManager::fPrimSpectrumType private
Definition at line 172 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 172 of file RMC01AnalysisManager.hh
Referenced by PrimDiffAndDirFluxForAdjointSim(), SetPrimaryExpSpectrumForAdjointSim(), and SetPrimaryPowerLawSpectrumForAdjointSim().
G4H1* RMC01AnalysisManager::fProton_current private
Definition at line 127 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 127 of file RMC01AnalysisManager.hh
Referenced by Book(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4H2* RMC01AnalysisManager::fProton_current_rmatrix_vs_proton_prim_energy private
Definition at line 161 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 161 of file RMC01AnalysisManager.hh
Referenced by Book(), and EndOfEventForAdjointSimulation().
G4double RMC01AnalysisManager::fRelative_error private
Definition at line 142 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 142 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfEventForAdjointSimulation(), and EndOfEventForForwardSimulation().
G4bool RMC01AnalysisManager::fStop_run_if_precision_reached private
Definition at line 145 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 145 of file RMC01AnalysisManager.hh
Referenced by EndOfEvent().
G4Timer* RMC01AnalysisManager::fTimer private
Definition at line 183 of file RMC01AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 183 of file RMC01AnalysisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfRun(), and RMC01AnalysisManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/RMC01AnalysisManager.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/src/RMC01AnalysisManager.cc