ECCE @ EIC Software: G4VRML2FileViewer Class Reference
G4VRML2FileViewer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/VRML/include/G4VRML2FileViewer.hh>
Public Member Functions
G4VRML2FileViewer (G4VRML2FileSceneHandler &scene, const G4String &name="")
virtual ~G4VRML2FileViewer ()
void ClearView ()
void DrawView ()
void ShowView ()
void FinishView ()
Public Member Functions inherited from G4VViewer
G4VViewer (G4VSceneHandler &, G4int id, const G4String &name="")
virtual ~G4VViewer ()
virtual void Initialise ()
virtual void ResetView ()
void RefreshView ()
std::vector< G4ThreeVector > ComputeFlyThrough (G4Vector3D *)
const G4String & GetName () const
const G4String & GetShortName () const
void SetName (const G4String &)
G4int GetViewId () const
G4VSceneHandler * GetSceneHandler () const
const G4ViewParameters & GetViewParameters () const
const G4ViewParameters & GetDefaultViewParameters () const
virtual const std::vector
< G4ModelingParameters::VisAttributesModifier > * GetPrivateVisAttributesModifiers () const
void SetViewParameters (const G4ViewParameters &vp)
void SetDefaultViewParameters (const G4ViewParameters &vp)
const G4VisAttributes * GetApplicableVisAttributes (const G4VisAttributes *) const
void SetNeedKernelVisit (G4bool need)
void NeedKernelVisit ()
void ProcessView ()
Private Member Functions
void SetView ()
void SendViewParameters ()
Private Attributes
G4VRML2FileSceneHandler & fSceneHandler
std::ofstream & fDest
G4double fViewHalfAngle
G4double fsin_VHA
Additional Inherited Members
Protected Member Functions inherited from G4VViewer
void SetTouchable (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath)
void TouchableSetVisibility (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, G4bool visibility)
void TouchableSetColour (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, const G4Colour &)
Protected Attributes inherited from G4VViewer
G4VSceneHandler & fSceneHandler
G4int fViewId
G4String fName
G4String fShortName
G4ViewParameters fVP
G4ViewParameters fDefaultVP
G4bool fNeedKernelVisit
Detailed Description
Definition at line 40 of file G4VRML2FileViewer.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VRML2FileViewer.hh
Constructor & Destructor Documentation
G4VRML2FileViewer::G4VRML2FileViewer (G4VRML2FileSceneHandler & scene, const G4String & name = "")
Definition at line 44 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VRML2FileViewer.cc
References deg, fsin_VHA, and fViewHalfAngle.
G4VRML2FileViewer::~G4VRML2FileViewer () virtual
Definition at line 56 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VRML2FileViewer.cc
Member Function Documentation
void G4VRML2FileViewer::ClearView (void) virtual
Implements G4VViewer.
Definition at line 89 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VRML2FileViewer.cc
References G4VisManager::errors, G4VRML2FileSceneHandler::fDest, G4VRML2FileSceneHandler::fFlagDestOpen, fSceneHandler, G4VRML2FileSceneHandler::fVRMLFileName, G4cout, G4endl, and G4VisManager::GetVerbosity().
void G4VRML2FileViewer::DrawView () virtual
Implements G4VViewer.
Definition at line 71 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 71 of file G4VRML2FileViewer.cc
References G4VisManager::errors, FinishView(), fSceneHandler, G4cout, G4endl, G4VisManager::GetVerbosity(), G4VViewer::NeedKernelVisit(), G4VViewer::ProcessView(), SendViewParameters(), and G4VRML2FileSceneHandler::VRMLBeginModeling().
void G4VRML2FileViewer::FinishView (void) virtual
Reimplemented from G4VViewer.
Definition at line 113 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 113 of file G4VRML2FileViewer.cc
References G4VisManager::errors, G4cout, G4endl, and G4VisManager::GetVerbosity().
Referenced by DrawView().
void G4VRML2FileViewer::SendViewParameters () private
Definition at line 121 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 121 of file G4VRML2FileViewer.cc
References E, e, G4VisManager::errors, fDest, fSceneHandler, fsin_VHA, G4VViewer::fVP, G4cout, G4endl, G4ViewParameters::GetCurrentTargetPoint(), G4Scene::GetExtent(), G4VisExtent::GetExtentRadius(), G4VSceneHandler::GetScene(), G4Scene::GetStandardTargetPoint(), G4VisManager::GetVerbosity(), return(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
Referenced by DrawView().
void G4VRML2FileViewer::SetView () private virtual
Implements G4VViewer.
Definition at line 59 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VRML2FileViewer.cc
References G4VisManager::errors, G4cout, G4endl, and G4VisManager::GetVerbosity().
void G4VRML2FileViewer::ShowView (void) virtual
Reimplemented from G4VViewer.
Definition at line 104 of file G4VRML2FileViewer.cc.
View newest version in sPHENIX GitHub at line 104 of file G4VRML2FileViewer.cc
References G4VisManager::errors, fSceneHandler, G4cout, G4endl, G4VisManager::GetVerbosity(), and G4VRML2FileSceneHandler::VRMLEndModeling().
Member Data Documentation
std::ofstream& G4VRML2FileViewer::fDest private
Definition at line 54 of file G4VRML2FileViewer.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VRML2FileViewer.hh
Referenced by SendViewParameters().
G4VRML2FileSceneHandler& G4VRML2FileViewer::fSceneHandler private
Definition at line 53 of file G4VRML2FileViewer.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VRML2FileViewer.hh
Referenced by ClearView(), DrawView(), SendViewParameters(), and ShowView().
G4double G4VRML2FileViewer::fsin_VHA private
Definition at line 57 of file G4VRML2FileViewer.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VRML2FileViewer.hh
Referenced by G4VRML2FileViewer(), and SendViewParameters().
G4double G4VRML2FileViewer::fViewHalfAngle private
Definition at line 56 of file G4VRML2FileViewer.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VRML2FileViewer.hh
Referenced by G4VRML2FileViewer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/VRML/include/G4VRML2FileViewer.hh
geant4/tree/geant4-10.6-release/source/visualization/VRML/src/G4VRML2FileViewer.cc