ECCE @ EIC Software: G4Field Class Reference
G4Field Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4Field.hh>
Public Member Functions
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
virtual void GetFieldValue (const G4double Point[4], G4double *fieldArr) const =0
virtual G4bool DoesFieldChangeEnergy () const =0
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
virtual G4Field * Clone () const
Static Public Attributes
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Private Attributes
G4bool fGravityActive = false
Detailed Description
Definition at line 55 of file G4Field.hh.
View newest version in sPHENIX GitHub at line 55 of file G4Field.hh
Constructor & Destructor Documentation
G4Field::G4Field (G4bool gravityOn = false)
Definition at line 33 of file G4Field.cc.
View newest version in sPHENIX GitHub at line 33 of file G4Field.cc
G4Field::G4Field (const G4Field & p)
Definition at line 49 of file G4Field.cc.
View newest version in sPHENIX GitHub at line 49 of file G4Field.cc
G4Field::~G4Field () virtual
Definition at line 38 of file G4Field.cc.
View newest version in sPHENIX GitHub at line 38 of file G4Field.cc
Member Function Documentation
G4Field * G4Field::Clone () const virtual
Reimplemented in G4UniformMagField, G4UniformGravityField, G4CachedMagneticField, G4QuadrupoleMagField, G4UniformElectricField, G4SextupoleMagField, G4KM_DummyField, G4DELPHIMagField, G4HarmonicPolMagField, and G4LineCurrentMagField.
Definition at line 54 of file G4Field.cc.
View newest version in sPHENIX GitHub at line 54 of file G4Field.cc
References FatalException, and G4Exception().
Referenced by G4CachedMagneticField::Clone(), and G4FieldManager::Clone().
virtual G4bool G4Field::DoesFieldChangeEnergy () const pure virtual
Implemented in F04GlobalField, G4ElectroMagneticField, G4UniformGravityField, EMField, G4ElectricField, G4MagneticField, and F05Field.
Referenced by G4FieldManager::G4FieldManager(), and G4FieldManager::InitialiseFieldChangesEnergy().
virtual void G4Field::GetFieldValue (const G4double Point[4], G4double * fieldArr) const pure virtual
Implemented in PurgMagTabulatedField3D, G4ElectroMagneticField, G4UniformGravityField, HadrontherapyElectricTabulatedField3D, HadrontherapyMagneticField3D, G4UniformMagField, G4UniformElectricField, F05Field, G4ElectricField, G4MagneticField, G4CachedMagneticField, EMField, PyG4MagneticField, TabulatedField3D, B5MagneticField, PHG4OuterHcalField, and PHG4MagneticField.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), PHG4OuterHcalSteppingAction::FieldChecker(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ElectricFieldModel::GetFieldAtLocation(), G4MagneticFieldModel::GetFieldAtLocation(), PHG4OuterHcalField::GetFieldValue(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4SynchrotronRadiation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), and G4ErrorFreeTrajState::PropagateError().
G4bool G4Field::IsGravityActive () const inline
Definition at line 101 of file G4Field.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Field.hh
References fGravityActive.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4RepleteEofM::G4RepleteEofM().
G4Field & G4Field::operator= (const G4Field & p)
Definition at line 42 of file G4Field.cc.
View newest version in sPHENIX GitHub at line 42 of file G4Field.cc
References fGravityActive.
Referenced by G4MagneticField::operator=(), G4UniformGravityField::operator=(), and G4ElectroMagneticField::operator=().
void G4Field::SetGravityActive (G4bool OnOffFlag) inline
Definition at line 106 of file G4Field.hh.
View newest version in sPHENIX GitHub at line 106 of file G4Field.hh
References fGravityActive.
Member Data Documentation
G4bool G4Field::fGravityActive = false private
Definition at line 96 of file G4Field.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Field.hh
Referenced by IsGravityActive(), operator=(), and SetGravityActive().
constexpr G4int G4Field::MAX_NUMBER_OF_COMPONENTS = 24 static
Definition at line 92 of file G4Field.hh.
View newest version in sPHENIX GitHub at line 92 of file G4Field.hh
Referenced by G4BFieldIntegrationDriver::CurvatureRadius().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4Field.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4Field.cc