ECCE @ EIC Software: CexmcReconstructorMessenger Class Reference
CexmcReconstructorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcReconstructorMessenger.hh>
Public Member Functions
CexmcReconstructorMessenger (CexmcReconstructor *reconstructor)
~CexmcReconstructorMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CexmcReconstructor * reconstructor
G4UIcmdWithAString * setCalorimeterEntryPointDefinitionAlgorithm
G4UIcmdWithAString * setCalorimeterEntryPointDepthDefinitionAlgorithm
G4UIcmdWithAString * setCrystalSelectionAlgorithm
G4UIcmdWithABool * useInnerRefCrystal
G4UIcmdWithADoubleAndUnit * setCalorimeterEntryPointDepth
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 56 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcReconstructorMessenger.hh
Constructor & Destructor Documentation
CexmcReconstructorMessenger::CexmcReconstructorMessenger (CexmcReconstructor * reconstructor) explicit
Definition at line 53 of file CexmcReconstructorMessenger.cc.
View newest version in sPHENIX GitHub at line 53 of file CexmcReconstructorMessenger.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, CexmcMessenger::reconstructorDirName, setCalorimeterEntryPointDefinitionAlgorithm, setCalorimeterEntryPointDepth, setCalorimeterEntryPointDepthDefinitionAlgorithm, G4UIcmdWithAString::SetCandidates(), setCrystalSelectionAlgorithm, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), and useInnerRefCrystal.
CexmcReconstructorMessenger::~CexmcReconstructorMessenger ()
Definition at line 150 of file CexmcReconstructorMessenger.cc.
View newest version in sPHENIX GitHub at line 150 of file CexmcReconstructorMessenger.cc
References setCalorimeterEntryPointDefinitionAlgorithm, setCalorimeterEntryPointDepth, setCalorimeterEntryPointDepthDefinitionAlgorithm, setCrystalSelectionAlgorithm, and useInnerRefCrystal.
Member Function Documentation
void CexmcReconstructorMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 160 of file CexmcReconstructorMessenger.cc.
View newest version in sPHENIX GitHub at line 160 of file CexmcReconstructorMessenger.cc
References CexmcEntryPointByLinearEDWeights, CexmcEntryPointBySqrtEDWeights, CexmcEntryPointDepthPlain, CexmcEntryPointDepthSphere, CexmcEntryPointInTheCenter, CexmcEntryPointInTheCenterOfCrystalWithMaxED, CexmcSelectAdjacentCrystals, CexmcSelectAllCrystals, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), reconstructor, CexmcReconstructor::SetCalorimeterEntryPointDefinitionAlgorithm(), setCalorimeterEntryPointDefinitionAlgorithm, CexmcReconstructor::SetCalorimeterEntryPointDepth(), setCalorimeterEntryPointDepth, CexmcReconstructor::SetCalorimeterEntryPointDepthDefinitionAlgorithm(), setCalorimeterEntryPointDepthDefinitionAlgorithm, CexmcReconstructor::SetCrystalSelectionAlgorithm(), setCrystalSelectionAlgorithm, useInnerRefCrystal, and CexmcReconstructor::UseInnerRefCrystal().
Member Data Documentation
CexmcReconstructor* CexmcReconstructorMessenger::reconstructor private
Definition at line 68 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcReconstructorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* CexmcReconstructorMessenger::setCalorimeterEntryPointDefinitionAlgorithm private
Definition at line 70 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file CexmcReconstructorMessenger.hh
Referenced by CexmcReconstructorMessenger(), SetNewValue(), and ~CexmcReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcReconstructorMessenger::setCalorimeterEntryPointDepth private
Definition at line 78 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file CexmcReconstructorMessenger.hh
Referenced by CexmcReconstructorMessenger(), SetNewValue(), and ~CexmcReconstructorMessenger().
G4UIcmdWithAString* CexmcReconstructorMessenger::setCalorimeterEntryPointDepthDefinitionAlgorithm private
Definition at line 72 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcReconstructorMessenger.hh
Referenced by CexmcReconstructorMessenger(), SetNewValue(), and ~CexmcReconstructorMessenger().
G4UIcmdWithAString* CexmcReconstructorMessenger::setCrystalSelectionAlgorithm private
Definition at line 74 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file CexmcReconstructorMessenger.hh
Referenced by CexmcReconstructorMessenger(), SetNewValue(), and ~CexmcReconstructorMessenger().
G4UIcmdWithABool* CexmcReconstructorMessenger::useInnerRefCrystal private
Definition at line 76 of file CexmcReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcReconstructorMessenger.hh
Referenced by CexmcReconstructorMessenger(), SetNewValue(), and ~CexmcReconstructorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcReconstructorMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcReconstructorMessenger.cc