ECCE @ EIC Software: G4CrossSectionDataStore Class Reference
G4CrossSectionDataStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionDataStore.hh>
Public Member Functions
G4CrossSectionDataStore ()
~G4CrossSectionDataStore ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Material *)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *, const G4Element *, const G4Material *)
const G4Element * SampleZandA (const G4DynamicParticle *, const G4Material *, G4Nucleus &target)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
void DumpHtml (const G4ParticleDefinition &, std::ofstream &) const
void PrintCrossSectionHtml (const G4VCrossSectionDataSet *cs) const
void AddDataSet (G4VCrossSectionDataSet *)
void AddDataSet (G4VCrossSectionDataSet *, size_t)
void SetVerboseLevel (G4int value)
const
G4FastPathHadronicCrossSection::fastPathParameters & GetFastPathParameters () const
const
G4FastPathHadronicCrossSection::controlFlag & GetFastPathControlFlags () const
void DumpFastPath (const G4ParticleDefinition *, const G4Material *, std::ostream &os)
void ActivateFastPath (const G4ParticleDefinition *, const G4Material *, G4double)
Private Member Functions
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *, const G4Element *, const G4Material *aMaterial, G4int index)
G4CrossSectionDataStore & operator= (const G4CrossSectionDataStore &right)
G4CrossSectionDataStore (const G4CrossSectionDataStore &)
G4String HtmlFileName (const G4String &in) const
G4double GetCrossSection (const G4DynamicParticle *, const G4Material *, G4bool requiresSlowPath)
Private Attributes
G4NistManager * nist
std::vector
< G4VCrossSectionDataSet * > dataSetList
std::vector< G4double > xsecelm
std::vector< G4double > xseciso
const G4Material * currentMaterial
const G4ParticleDefinition * matParticle
G4double matKinEnergy
G4double matCrossSection
const G4Material * elmMaterial
const G4Element * currentElement
const G4ParticleDefinition * elmParticle
G4double elmKinEnergy
G4double elmCrossSection
G4int nDataSetList
G4int verboseLevel
G4FastPathHadronicCrossSection::controlFlag fastPathFlags
G4FastPathHadronicCrossSection::fastPathParameters fastPathParams
G4FastPathHadronicCrossSection::getCrossSectionCount counters
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Cache fastPathCache
G4FastPathHadronicCrossSection::timing timing
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Requests requests
Friends
struct G4FastPathHadronicCrossSection::fastPathEntry
Detailed Description
Definition at line 62 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 62 of file G4CrossSectionDataStore.hh
Constructor & Destructor Documentation
G4CrossSectionDataStore::G4CrossSectionDataStore ()
Definition at line 60 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 60 of file G4CrossSectionDataStore.cc
References currentElement, currentMaterial, elmCrossSection, elmKinEnergy, elmMaterial, elmParticle, G4NistManager::Instance(), matCrossSection, matKinEnergy, matParticle, and nist.
G4CrossSectionDataStore::~G4CrossSectionDataStore ()
Definition at line 73 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 73 of file G4CrossSectionDataStore.cc
G4CrossSectionDataStore::G4CrossSectionDataStore (const G4CrossSectionDataStore &) private
Member Function Documentation
void G4CrossSectionDataStore::ActivateFastPath (const G4ParticleDefinition * pdef, const G4Material * mat, G4double min_cutoff)
Definition at line 531 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 531 of file G4CrossSectionDataStore.cc
References requests.
void G4CrossSectionDataStore::AddDataSet (G4VCrossSectionDataSet * p)
Definition at line 644 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 644 of file G4CrossSectionDataStore.cc
References dataSetList, G4VCrossSectionDataSet::ForAllAtomsAndEnergies(), and nDataSetList.
Referenced by G4HadronicProcess::AddDataSet(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4ElectronNuclearProcess::G4ElectronNuclearProcess(), G4PhotoNuclearProcess::G4PhotoNuclearProcess(), and G4PositronNuclearProcess::G4PositronNuclearProcess().
void G4CrossSectionDataStore::AddDataSet (G4VCrossSectionDataSet * p, size_t i)
Definition at line 658 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 658 of file G4CrossSectionDataStore.cc
References dataSetList, G4VCrossSectionDataSet::ForAllAtomsAndEnergies(), it, and nDataSetList.
void G4CrossSectionDataStore::BuildPhysicsTable (const G4ParticleDefinition & aParticleType)
Definition at line 494 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 494 of file G4CrossSectionDataStore.cc
References dataSetList, G4FastPathHadronicCrossSection::cycleCountEntry::fastPath, fastPathCache, fastPathFlags, FatalException, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4FastPathHadronicCrossSection::controlFlag::initializationPhase, G4FastPathHadronicCrossSection::fastPathEntry::Initialize(), nDataSetList, requests, and G4FastPathHadronicCrossSection::controlFlag::useFastPathIfAvailable.
Referenced by G4HadronicProcess::BuildPhysicsTable().
G4double G4CrossSectionDataStore::ComputeCrossSection (const G4DynamicParticle * part, const G4Material * mat)
Definition at line 268 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 268 of file G4CrossSectionDataStore.cc
References currentMaterial, GetCrossSection(), G4DynamicParticle::GetDefinition(), G4Material::GetElement(), G4DynamicParticle::GetKineticEnergy(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), mat, matCrossSection, matKinEnergy, matParticle, and xsecelm.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4HadronXSDataTable::Initialise(), G4HadronicProcess::PostStepDoIt(), and G4GammaGeneralProcess::SampleSecondaries().
void G4CrossSectionDataStore::DumpFastPath (const G4ParticleDefinition * pd, const G4Material * mat, std::ostream & os)
Definition at line 249 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 249 of file G4CrossSectionDataStore.cc
References G4FastPathHadronicCrossSection::cycleCountEntry::fastPath, fastPathCache, G4Material::GetName(), and G4ParticleDefinition::GetParticleName().
void G4CrossSectionDataStore::DumpHtml (const G4ParticleDefinition & , std::ofstream & outFile) const
Definition at line 576 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 576 of file G4CrossSectionDataStore.cc
References dataSetList, GeV, nDataSetList, and PrintCrossSectionHtml().
Referenced by G4HadronicProcessStore::PrintHtml().
void G4CrossSectionDataStore::DumpPhysicsTable (const G4ParticleDefinition & aParticleType)
Definition at line 549 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 549 of file G4CrossSectionDataStore.cc
References dataSetList, e1, e2, G4BestUnit, G4cout, G4endl, and nDataSetList.
Referenced by G4ChargeExchangeProcess::DumpPhysicsTable(), G4HadronicProcess::DumpPhysicsTable(), and G4HadronicProcessStore::Print().
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * particle, const G4Material * material) inline
Definition at line 156 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 156 of file G4CrossSectionDataStore.hh
Referenced by ComputeCrossSection(), G4HadElementSelector::G4HadElementSelector(), GetCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4HadronicProcess::GetElementCrossSection(), and G4FastPathHadronicCrossSection::fastPathEntry::Initialize().
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * part, const G4Element * elm, const G4Material * mat)
Definition at line 296 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 296 of file G4CrossSectionDataStore.cc
References currentElement, dataSetList, elmCrossSection, elmKinEnergy, elmMaterial, elmParticle, G4DynamicParticle::GetDefinition(), GetIsoCrossSection(), G4Element::GetIsotope(), G4DynamicParticle::GetKineticEnergy(), G4Isotope::GetN(), G4Element::GetNaturalAbundanceFlag(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZasInt(), mat, nDataSetList, and Z.
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * part, G4int Z, G4int A, const G4Isotope * iso, const G4Element * elm, const G4Material * mat)
Definition at line 390 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 390 of file G4CrossSectionDataStore.cc
References dataSetList, FatalException, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4Element::GetName(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), MeV, and nDataSetList.
G4double G4CrossSectionDataStore::GetCrossSection (const G4DynamicParticle * part, const G4Material * mat, G4bool requiresSlowPath) private
Definition at line 79 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 79 of file G4CrossSectionDataStore.cc
References counters, G4FastPathHadronicCrossSection::cycleCountEntry::crossSection, currentMaterial, G4FastPathHadronicCrossSection::cycleCountEntry::energy, G4FastPathHadronicCrossSection::cycleCountEntry::fastPath, G4FastPathHadronicCrossSection::getCrossSectionCount::FastPath(), fastPathCache, fastPathFlags, G4FastPathHadronicCrossSection::fastPathEntry::GetCrossSection(), GetCrossSection(), G4DynamicParticle::GetDefinition(), G4Material::GetElementVector(), G4DynamicParticle::GetKineticEnergy(), G4Material::GetNumberOfElements(), G4DynamicParticle::GetParticleDefinition(), G4Material::GetVecNbOfAtomsPerVolume(), G4FastPathHadronicCrossSection::getCrossSectionCount::HitOneLine(), G4FastPathHadronicCrossSection::controlFlag::initializationPhase, G4FastPathHadronicCrossSection::logHit(), G4FastPathHadronicCrossSection::logInvocationOneLine(), G4FastPathHadronicCrossSection::logInvocationTriedOneLine(), G4FastPathHadronicCrossSection::logStartCountCycles(), G4FastPathHadronicCrossSection::logStopCountCycles(), G4FastPathHadronicCrossSection::logTiming(), mat, matCrossSection, matKinEnergy, matParticle, G4FastPathHadronicCrossSection::getCrossSectionCount::MethodCalled(), G4FastPathHadronicCrossSection::fastPathEntry::min_cutoff, G4FastPathHadronicCrossSection::controlFlag::prevCalcUsedFastPath, G4FastPathHadronicCrossSection::getCrossSectionCount::SlowPath(), timing, G4FastPathHadronicCrossSection::controlFlag::useFastPathIfAvailable, and xsecelm.
const G4FastPathHadronicCrossSection::controlFlag& G4CrossSectionDataStore::GetFastPathControlFlags () const inline
Definition at line 138 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 138 of file G4CrossSectionDataStore.hh
References fastPathFlags.
Referenced by G4FastPathHadronicCrossSection::fastPathEntry::Initialize().
const G4FastPathHadronicCrossSection::fastPathParameters& G4CrossSectionDataStore::GetFastPathParameters () const inline
Definition at line 136 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 136 of file G4CrossSectionDataStore.hh
References fastPathParams.
Referenced by G4FastPathHadronicCrossSection::fastPathEntry::Initialize().
G4double G4CrossSectionDataStore::GetIsoCrossSection (const G4DynamicParticle * part, G4int Z, G4int A, const G4Isotope * iso, const G4Element * elm, const G4Material * aMaterial, G4int index) private
Definition at line 352 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 352 of file G4CrossSectionDataStore.cc
References dataSetList, FatalException, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4Element::GetName(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), incremental_prev_tag::idx, MeV, and nDataSetList.
Referenced by GetCrossSection(), and SampleZandA().
G4String G4CrossSectionDataStore::HtmlFileName (const G4String & in) const private
Definition at line 631 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 631 of file G4CrossSectionDataStore.cc
References Acts::Test::transform.
Referenced by PrintCrossSectionHtml().
G4CrossSectionDataStore& G4CrossSectionDataStore::operator= (const G4CrossSectionDataStore & right) private
void G4CrossSectionDataStore::PrintCrossSectionHtml (const G4VCrossSectionDataSet * cs) const
Definition at line 608 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 608 of file G4CrossSectionDataStore.cc
References G4VCrossSectionDataSet::CrossSectionDescription(), G4VCrossSectionDataSet::GetName(), and HtmlFileName().
Referenced by DumpHtml().
const G4Element * G4CrossSectionDataStore::SampleZandA (const G4DynamicParticle * part, const G4Material * mat, G4Nucleus & target)
Definition at line 415 of file G4CrossSectionDataStore.cc.
View newest version in sPHENIX GitHub at line 415 of file G4CrossSectionDataStore.cc
References Acts::VectorHelpers::cross(), dataSetList, G4UniformRand, G4Material::GetElement(), GetIsoCrossSection(), G4Element::GetIsotope(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4Isotope::GetN(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZasInt(), mat, matCrossSection, nDataSetList, G4Nucleus::SetIsotope(), xsecelm, xseciso, and Z.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
void G4CrossSectionDataStore::SetVerboseLevel (G4int value) inline
Definition at line 161 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 161 of file G4CrossSectionDataStore.hh
References verboseLevel.
Friends And Related Function Documentation
friend struct G4FastPathHadronicCrossSection::fastPathEntry friend
Definition at line 142 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 142 of file G4CrossSectionDataStore.hh
Member Data Documentation
G4FastPathHadronicCrossSection::getCrossSectionCount G4CrossSectionDataStore::counters private
Definition at line 149 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 149 of file G4CrossSectionDataStore.hh
Referenced by GetCrossSection().
const G4Element* G4CrossSectionDataStore::currentElement private
Definition at line 126 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CrossSectionDataStore.hh
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
const G4Material* G4CrossSectionDataStore::currentMaterial private
Definition at line 120 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 120 of file G4CrossSectionDataStore.hh
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), and GetCrossSection().
std::vector<G4VCrossSectionDataSet*> G4CrossSectionDataStore::dataSetList private
Definition at line 116 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 116 of file G4CrossSectionDataStore.hh
Referenced by AddDataSet(), BuildPhysicsTable(), DumpHtml(), DumpPhysicsTable(), GetCrossSection(), GetIsoCrossSection(), and SampleZandA().
G4double G4CrossSectionDataStore::elmCrossSection private
Definition at line 129 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 129 of file G4CrossSectionDataStore.hh
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
G4double G4CrossSectionDataStore::elmKinEnergy private
Definition at line 128 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 128 of file G4CrossSectionDataStore.hh
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
const G4Material* G4CrossSectionDataStore::elmMaterial private
Definition at line 125 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 125 of file G4CrossSectionDataStore.hh
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
const G4ParticleDefinition* G4CrossSectionDataStore::elmParticle private
Definition at line 127 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 127 of file G4CrossSectionDataStore.hh
Referenced by G4CrossSectionDataStore(), and GetCrossSection().
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Cache G4CrossSectionDataStore::fastPathCache private
Definition at line 151 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 151 of file G4CrossSectionDataStore.hh
Referenced by BuildPhysicsTable(), DumpFastPath(), and GetCrossSection().
G4FastPathHadronicCrossSection::controlFlag G4CrossSectionDataStore::fastPathFlags private
Definition at line 146 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 146 of file G4CrossSectionDataStore.hh
Referenced by BuildPhysicsTable(), GetCrossSection(), and GetFastPathControlFlags().
G4FastPathHadronicCrossSection::fastPathParameters G4CrossSectionDataStore::fastPathParams private
Definition at line 147 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 147 of file G4CrossSectionDataStore.hh
Referenced by GetFastPathParameters().
G4double G4CrossSectionDataStore::matCrossSection private
Definition at line 123 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 123 of file G4CrossSectionDataStore.hh
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), GetCrossSection(), and SampleZandA().
G4double G4CrossSectionDataStore::matKinEnergy private
Definition at line 122 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 122 of file G4CrossSectionDataStore.hh
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), and GetCrossSection().
const G4ParticleDefinition* G4CrossSectionDataStore::matParticle private
Definition at line 121 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 121 of file G4CrossSectionDataStore.hh
Referenced by ComputeCrossSection(), G4CrossSectionDataStore(), and GetCrossSection().
G4int G4CrossSectionDataStore::nDataSetList private
Definition at line 131 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 131 of file G4CrossSectionDataStore.hh
Referenced by AddDataSet(), BuildPhysicsTable(), DumpHtml(), DumpPhysicsTable(), GetCrossSection(), GetIsoCrossSection(), and SampleZandA().
G4NistManager* G4CrossSectionDataStore::nist private
Definition at line 114 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 114 of file G4CrossSectionDataStore.hh
Referenced by G4CrossSectionDataStore().
G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Requests G4CrossSectionDataStore::requests private
Definition at line 153 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 153 of file G4CrossSectionDataStore.hh
Referenced by ActivateFastPath(), and BuildPhysicsTable().
G4FastPathHadronicCrossSection::timing G4CrossSectionDataStore::timing private
Definition at line 152 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 152 of file G4CrossSectionDataStore.hh
Referenced by GetCrossSection().
G4int G4CrossSectionDataStore::verboseLevel private
Definition at line 132 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 132 of file G4CrossSectionDataStore.hh
Referenced by SetVerboseLevel().
std::vector<G4double> G4CrossSectionDataStore::xsecelm private
Definition at line 117 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 117 of file G4CrossSectionDataStore.hh
Referenced by ComputeCrossSection(), GetCrossSection(), and SampleZandA().
std::vector<G4double> G4CrossSectionDataStore::xseciso private
Definition at line 118 of file G4CrossSectionDataStore.hh.
View newest version in sPHENIX GitHub at line 118 of file G4CrossSectionDataStore.hh
Referenced by SampleZandA().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionDataStore.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4CrossSectionDataStore.cc