ECCE @ EIC Software: G4MuNeutrinoNucleusTotXsc Class Reference
G4MuNeutrinoNucleusTotXsc Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4MuNeutrinoNucleusTotXsc.hh>
Public Member Functions
G4MuNeutrinoNucleusTotXsc ()
~G4MuNeutrinoNucleusTotXsc ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *, const G4Material *)
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *dynPart, G4int Z, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *aPart, G4int Z, G4int A, const G4Isotope *, const G4Element *, const G4Material *)
G4int GetEnergyIndex (G4double energy)
G4double GetNuMuTotCsXsc (G4int index, G4double energy)
G4double GetANuMuTotCsXsc (G4int index, G4double energy)
G4double GetNuMuTotCsArray (G4int index)
G4double GetANuMuTotCsArray (G4int index)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
void SetBiasingFactor (G4double bf)
G4double GetBiasingFactor ()
G4double GetTotXsc ()
G4double GetCcTotRatio ()
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Protected Attributes
G4double fCofXsc
G4double fSin2tW
G4double fCofS
G4double fCofL
G4double fCutEnergy
G4double fBiasingFactor
G4double fTotXsc
G4double fCcTotRatio
G4double fCcFactor
G4double fNcFactor
G4int fIndex
G4ParticleDefinition * theMuonMinus
G4ParticleDefinition * theMuonPlus
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Static Protected Attributes
static const G4double fNuMuEnergy [50]
static const G4double fNuMuTotXsc [50]
static const G4double fANuMuTotXsc [50]
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Detailed Description
Definition at line 42 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 42 of file G4MuNeutrinoNucleusTotXsc.hh
Constructor & Destructor Documentation
G4MuNeutrinoNucleusTotXsc::G4MuNeutrinoNucleusTotXsc ()
Definition at line 47 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 47 of file G4MuNeutrinoNucleusTotXsc.cc
References cm2, fBiasingFactor, fCcFactor, fCcTotRatio, fCofL, fCofS, fCofXsc, fCutEnergy, fIndex, fNcFactor, fSin2tW, fTotXsc, GeV, G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), theMuonMinus, and theMuonPlus.
G4MuNeutrinoNucleusTotXsc::~G4MuNeutrinoNucleusTotXsc ()
Definition at line 79 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 79 of file G4MuNeutrinoNucleusTotXsc.cc
Member Function Documentation
G4double G4MuNeutrinoNucleusTotXsc::GetANuMuTotCsArray (G4int index)
Definition at line 288 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 288 of file G4MuNeutrinoNucleusTotXsc.cc
References fANuMuTotXsc, fIndex, G4cout, and G4endl.
G4double G4MuNeutrinoNucleusTotXsc::GetANuMuTotCsXsc (G4int index, G4double energy)
Definition at line 247 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 247 of file G4MuNeutrinoNucleusTotXsc.cc
References angle, fANuMuTotXsc, fIndex, fNuMuEnergy, GeV, x1, x2, y1, and y2.
Referenced by GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::GetBiasingFactor () inline
Definition at line 77 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 77 of file G4MuNeutrinoNucleusTotXsc.hh
References fBiasingFactor.
G4double G4MuNeutrinoNucleusTotXsc::GetCcTotRatio () inline
Definition at line 80 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 80 of file G4MuNeutrinoNucleusTotXsc.hh
References fCcTotRatio.
Referenced by G4MuNeutrinoNucleusProcess::PostStepDoIt().
G4double G4MuNeutrinoNucleusTotXsc::GetCutEnergy () inline
Definition at line 74 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 74 of file G4MuNeutrinoNucleusTotXsc.hh
References fCutEnergy.
G4double G4MuNeutrinoNucleusTotXsc::GetElementCrossSection (const G4DynamicParticle * dynPart, G4int Z, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 99 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 99 of file G4MuNeutrinoNucleusTotXsc.cc
References A(), G4Material::GetElementVector(), GetIsoCrossSection(), G4Element::GetIsotopeVector(), G4Isotope::GetN(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), and IsIsoApplicable().
Referenced by G4MuNeutrinoNucleusProcess::PostStepDoIt().
G4int G4MuNeutrinoNucleusTotXsc::GetEnergyIndex (G4double energy)
Definition at line 199 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 199 of file G4MuNeutrinoNucleusTotXsc.cc
References fIndex, fNuMuEnergy, and GeV.
Referenced by GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::GetIsoCrossSection (const G4DynamicParticle * aPart, G4int Z, G4int A, const G4Isotope * , const G4Element * , const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 138 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 138 of file G4MuNeutrinoNucleusTotXsc.cc
References A(), bb, energy, fBiasingFactor, fCcFactor, fCcTotRatio, fCofL, fCofS, fCofXsc, fIndex, fNcFactor, fTotXsc, GetANuMuTotCsXsc(), G4DynamicParticle::GetDefinition(), GetEnergyIndex(), GetNuMuTotCsXsc(), G4ParticleDefinition::GetParticleName(), G4DynamicParticle::GetTotalEnergy(), GeV, Acts::UnitConstants::pm, and source.hepunit::proton_mass_c2.
Referenced by GetElementCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::GetNuMuTotCsArray (G4int index)
Definition at line 274 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 274 of file G4MuNeutrinoNucleusTotXsc.cc
References fIndex, fNuMuTotXsc, G4cout, and G4endl.
G4double G4MuNeutrinoNucleusTotXsc::GetNuMuTotCsXsc (G4int index, G4double energy)
Definition at line 220 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 220 of file G4MuNeutrinoNucleusTotXsc.cc
References angle, fIndex, fNuMuEnergy, fNuMuTotXsc, GeV, x1, x2, y1, and y2.
Referenced by GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::GetTotXsc () inline
Definition at line 79 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 79 of file G4MuNeutrinoNucleusTotXsc.hh
References fTotXsc.
virtual G4bool G4MuNeutrinoNucleusTotXsc::IsElementApplicable (const G4DynamicParticle * , G4int , const G4Material *) inline virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 53 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 53 of file G4MuNeutrinoNucleusTotXsc.hh
G4bool G4MuNeutrinoNucleusTotXsc::IsIsoApplicable (const G4DynamicParticle * aPart, G4int Z, G4int A, const G4Element * , const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 85 of file G4MuNeutrinoNucleusTotXsc.cc.
View newest version in sPHENIX GitHub at line 85 of file G4MuNeutrinoNucleusTotXsc.cc
References G4DynamicParticle::GetDefinition(), and G4ParticleDefinition::GetParticleName().
Referenced by GetElementCrossSection().
void G4MuNeutrinoNucleusTotXsc::SetBiasingFactor (G4double bf) inline
Definition at line 76 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MuNeutrinoNucleusTotXsc.hh
References fBiasingFactor.
Referenced by G4MuNeutrinoNucleusProcess::SetBiasingFactor().
void G4MuNeutrinoNucleusTotXsc::SetCutEnergy (G4double ec) inline
Definition at line 73 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 73 of file G4MuNeutrinoNucleusTotXsc.hh
References fCutEnergy.
Member Data Documentation
const G4double G4MuNeutrinoNucleusTotXsc::fANuMuTotXsc static protected
Initial value:
=
{
  0.0291812, 0.0979725, 0.136884, 0.16794, 0.194698,
  0.218468, 0.23992, 0.259241, 0.27665, 0.292251,
  0.30612, 0.318314, 0.328886, 0.337885, 0.345464,
  0.351495, 0.356131, 0.359448, 0.361531, 0.362474,
  0.362382, 0.361365, 0.359538, 0.357024, 0.353943,
  0.350422, 0.346685, 0.342662, 0.338567, 0.334514,
  0.330612, 0.326966, 0.323668, 0.320805, 0.318451,
  0.316671, 0.315514, 0.315013, 0.315187, 0.316036,
  0.317541, 0.319667, 0.322362, 0.325556, 0.329159,
  0.332577, 0.337133, 0.341214, 0.345128, 0.347657 }
Definition at line 95 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 95 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by GetANuMuTotCsArray(), and GetANuMuTotCsXsc().
G4double G4MuNeutrinoNucleusTotXsc::fBiasingFactor protected
Definition at line 88 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 88 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), GetBiasingFactor(), GetIsoCrossSection(), and SetBiasingFactor().
G4double G4MuNeutrinoNucleusTotXsc::fCcFactor protected
Definition at line 89 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), and GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::fCcTotRatio protected
Definition at line 89 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), GetCcTotRatio(), and GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::fCofL protected
Definition at line 86 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), and GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::fCofS protected
Definition at line 86 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), and GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::fCofXsc protected
Definition at line 80 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 80 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), and GetIsoCrossSection().
G4double G4MuNeutrinoNucleusTotXsc::fCutEnergy protected
Definition at line 87 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), GetCutEnergy(), and SetCutEnergy().
G4int G4MuNeutrinoNucleusTotXsc::fIndex protected
Definition at line 91 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 91 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), GetANuMuTotCsArray(), GetANuMuTotCsXsc(), GetEnergyIndex(), GetIsoCrossSection(), GetNuMuTotCsArray(), and GetNuMuTotCsXsc().
G4double G4MuNeutrinoNucleusTotXsc::fNcFactor protected
Definition at line 89 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), and GetIsoCrossSection().
const G4double G4MuNeutrinoNucleusTotXsc::fNuMuEnergy static protected
Initial value:
=
{
  0.112103, 0.117359, 0.123119, 0.129443, 0.136404,
  0.144084, 0.152576, 0.161991, 0.172458, 0.184126,
  0.197171, 0.211801, 0.228261, 0.24684, 0.267887,
  0.291816, 0.319125, 0.350417, 0.386422, 0.428032,
  0.47634, 0.532692, 0.598756, 0.676612, 0.768868,
  0.878812, 1.01062, 1.16963, 1.36271, 1.59876,
  1.88943, 2.25002, 2.70086, 3.26916, 3.99166,
  4.91843, 6.11836, 7.6872, 9.75942, 12.5259,
  16.2605, 21.3615, 28.4141, 38.2903, 52.3062,
  72.4763, 101.93, 145.6, 211.39, 312.172}
Definition at line 93 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by GetANuMuTotCsXsc(), GetEnergyIndex(), and GetNuMuTotCsXsc().
const G4double G4MuNeutrinoNucleusTotXsc::fNuMuTotXsc static protected
Initial value:
=
{
  0.0716001, 0.241013, 0.337793, 0.416033, 0.484616,
  0.546945, 0.604661, 0.658623, 0.709277, 0.756815,
  0.801263, 0.842519, 0.880396, 0.914642, 0.944968,
  0.971069, 0.992655, 1.00947, 1.02133, 1.02812,
  1.02987, 1.02671, 1.01892, 1.00689, 0.991167,
  0.972618, 0.951518, 0.928806, 0.90521, 0.881404,
  0.857978, 0.835424, 0.814112, 0.794314, 0.776204,
  0.759884, 0.745394, 0.732719, 0.721809, 0.712164,
  0.704299, 0.697804, 0.692491, 0.688137, 0.68448,
  0.681232, 0.676128, 0.674154, 0.670553, 0.666034 }
Definition at line 94 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 94 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by GetNuMuTotCsArray(), and GetNuMuTotCsXsc().
G4double G4MuNeutrinoNucleusTotXsc::fSin2tW protected
Definition at line 85 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc().
G4double G4MuNeutrinoNucleusTotXsc::fTotXsc protected
Definition at line 89 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc(), GetIsoCrossSection(), and GetTotXsc().
G4ParticleDefinition* G4MuNeutrinoNucleusTotXsc::theMuonMinus protected
Definition at line 97 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 97 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc().
G4ParticleDefinition* G4MuNeutrinoNucleusTotXsc::theMuonPlus protected
Definition at line 98 of file G4MuNeutrinoNucleusTotXsc.hh.
View newest version in sPHENIX GitHub at line 98 of file G4MuNeutrinoNucleusTotXsc.hh
Referenced by G4MuNeutrinoNucleusTotXsc().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4MuNeutrinoNucleusTotXsc.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4MuNeutrinoNucleusTotXsc.cc