ECCE @ EIC Software: G4PSPassageTrackLength Class Reference
G4PSPassageTrackLength Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSPassageTrackLength.hh>
Public Member Functions
G4PSPassageTrackLength (G4String name, G4int depth=0)
G4PSPassageTrackLength (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSPassageTrackLength ()
void Weighted (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
G4bool IsPassed (G4Step *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4int fCurrentTrkID
G4double fTrackLength
G4THitsMap< G4double > * EvtMap
G4bool weighted
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 46 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 46 of file G4PSPassageTrackLength.hh
Constructor & Destructor Documentation
G4PSPassageTrackLength::G4PSPassageTrackLength (G4String name, G4int depth = 0)
Definition at line 45 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 45 of file G4PSPassageTrackLength.cc
References SetUnit().
G4PSPassageTrackLength::G4PSPassageTrackLength (G4String name, const G4String & unit, G4int depth = 0)
Definition at line 52 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PSPassageTrackLength.cc
References SetUnit().
G4PSPassageTrackLength::~G4PSPassageTrackLength () virtual
Definition at line 62 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PSPassageTrackLength.cc
Member Function Documentation
void G4PSPassageTrackLength::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 118 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 118 of file G4PSPassageTrackLength.cc
References G4VTHitsMap< T, Map_t >::clear(), and EvtMap.
void G4PSPassageTrackLength::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 122 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 122 of file G4PSPassageTrackLength.cc
void G4PSPassageTrackLength::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 115 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 115 of file G4PSPassageTrackLength.cc
void G4PSPassageTrackLength::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 106 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 106 of file G4PSPassageTrackLength.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, EvtMap, fCurrentTrkID, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
G4bool G4PSPassageTrackLength::IsPassed (G4Step * aStep) protected
Definition at line 76 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 76 of file G4PSPassageTrackLength.cc
References FALSE, fCurrentTrkID, fGeomBoundary, fTrackLength, G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4Step::GetTrack(), G4Track::GetTrackID(), G4StepPoint::GetWeight(), TRUE, and weighted.
Referenced by ProcessHits().
void G4PSPassageTrackLength::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 125 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 125 of file G4PSPassageTrackLength.cc
References G4VPrimitiveScorer::detector, G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), G4VPrimitiveScorer::GetUnit(), and G4VPrimitiveScorer::GetUnitValue().
G4bool G4PSPassageTrackLength::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 65 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 65 of file G4PSPassageTrackLength.cc
References G4VTHitsMap< T, Map_t >::add(), EvtMap, fTrackLength, G4VPrimitiveScorer::GetIndex(), IsPassed(), and TRUE.
void G4PSPassageTrackLength::SetUnit (const G4String & unit) virtual
Definition at line 140 of file G4PSPassageTrackLength.cc.
View newest version in sPHENIX GitHub at line 140 of file G4PSPassageTrackLength.cc
References G4VPrimitiveScorer::CheckAndSetUnit().
Referenced by G4PSPassageTrackLength(), G4PSPassageTrackLength3D::G4PSPassageTrackLength3D(), and G4ScoreQuantityMessenger::SetNewValue().
void G4PSPassageTrackLength::Weighted (G4bool flg = true) inline
Definition at line 55 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 55 of file G4PSPassageTrackLength.hh
References weighted.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
Member Data Documentation
G4THitsMap<G4double>* G4PSPassageTrackLength::EvtMap private
Definition at line 75 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 75 of file G4PSPassageTrackLength.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int G4PSPassageTrackLength::fCurrentTrkID private
Definition at line 73 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PSPassageTrackLength.hh
Referenced by Initialize(), and IsPassed().
G4double G4PSPassageTrackLength::fTrackLength private
Definition at line 74 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PSPassageTrackLength.hh
Referenced by IsPassed(), and ProcessHits().
G4int G4PSPassageTrackLength::HCID private
Definition at line 72 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PSPassageTrackLength.hh
Referenced by Initialize().
G4bool G4PSPassageTrackLength::weighted private
Definition at line 76 of file G4PSPassageTrackLength.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PSPassageTrackLength.hh
Referenced by IsPassed(), and Weighted().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSPassageTrackLength.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSPassageTrackLength.cc