ECCE @ EIC Software: G4RegularNavigationHelper Class Reference
G4RegularNavigationHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4RegularNavigationHelper.hh>
Public Member Functions
~G4RegularNavigationHelper ()
void ClearStepLengths ()
void AddStepLength (G4int copyNo, G4double slen)
const std::vector< std::pair
< G4int, G4double > > & GetStepLengths ()
Static Public Member Functions
static G4RegularNavigationHelper * Instance ()
Public Attributes
std::vector< std::pair< G4int,
G4double > > theStepLengths
Private Member Functions
G4RegularNavigationHelper ()
Friends
class G4ThreadLocalSingleton< G4RegularNavigationHelper >
Detailed Description
Definition at line 45 of file G4RegularNavigationHelper.hh.
View newest version in sPHENIX GitHub at line 45 of file G4RegularNavigationHelper.hh
Constructor & Destructor Documentation
G4RegularNavigationHelper::~G4RegularNavigationHelper ()
Definition at line 47 of file G4RegularNavigationHelper.cc.
View newest version in sPHENIX GitHub at line 47 of file G4RegularNavigationHelper.cc
G4RegularNavigationHelper::G4RegularNavigationHelper () private
Definition at line 41 of file G4RegularNavigationHelper.cc.
View newest version in sPHENIX GitHub at line 41 of file G4RegularNavigationHelper.cc
Member Function Documentation
void G4RegularNavigationHelper::AddStepLength (G4int copyNo, G4double slen)
Definition at line 60 of file G4RegularNavigationHelper.cc.
View newest version in sPHENIX GitHub at line 60 of file G4RegularNavigationHelper.cc
References theStepLengths.
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials().
void G4RegularNavigationHelper::ClearStepLengths ()
Definition at line 53 of file G4RegularNavigationHelper.cc.
View newest version in sPHENIX GitHub at line 53 of file G4RegularNavigationHelper.cc
References theStepLengths.
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials().
const std::vector< std::pair< G4int, G4double > > & G4RegularNavigationHelper::GetStepLengths ()
Definition at line 68 of file G4RegularNavigationHelper.cc.
View newest version in sPHENIX GitHub at line 68 of file G4RegularNavigationHelper.cc
References theStepLengths.
Referenced by G4EnergySplitter::GetFirstVoxelID(), G4EnergySplitter::GetLastVoxelID(), G4EnergySplitter::GetStepLength(), G4EnergySplitter::GetVoxelID(), G4ScoreSplittingProcess::PostStepDoIt(), and G4EnergySplitter::SplitEnergyInVolumes().
G4RegularNavigationHelper * G4RegularNavigationHelper::Instance (void) static
Definition at line 33 of file G4RegularNavigationHelper.cc.
View newest version in sPHENIX GitHub at line 33 of file G4RegularNavigationHelper.cc
References G4ThreadLocalSingleton< T >::Instance().
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4EnergySplitter::GetFirstVoxelID(), G4EnergySplitter::GetLastVoxelID(), G4EnergySplitter::GetStepLength(), G4EnergySplitter::GetVoxelID(), G4ScoreSplittingProcess::PostStepDoIt(), and G4EnergySplitter::SplitEnergyInVolumes().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4RegularNavigationHelper > friend
Definition at line 47 of file G4RegularNavigationHelper.hh.
View newest version in sPHENIX GitHub at line 47 of file G4RegularNavigationHelper.hh
Member Data Documentation
std::vector< std::pair<G4int,G4double> > G4RegularNavigationHelper::theStepLengths
Definition at line 58 of file G4RegularNavigationHelper.hh.
View newest version in sPHENIX GitHub at line 58 of file G4RegularNavigationHelper.hh
Referenced by AddStepLength(), ClearStepLengths(), and GetStepLengths().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4RegularNavigationHelper.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4RegularNavigationHelper.cc