ECCE @ EIC Software: G4VEnergyLossProcess Class Reference
G4VEnergyLossProcess Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEnergyLossProcess.hh>
Public Member Functions
G4VEnergyLossProcess (const G4String &name="EnergyLoss", G4ProcessType type=fElectromagnetic)
virtual ~G4VEnergyLossProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override=0
virtual void PrintInfo ()
virtual void ProcessDescription (std::ostream &outFile) const override
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
G4PhysicsTable * BuildDEDXTable (G4EmTableType tType=fRestricted)
G4PhysicsTable * BuildLambdaTable (G4EmTableType tType=fRestricted)
virtual void StartTracking (G4Track *) override
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4double SampleSubCutSecondaries (std::vector< G4Track * > &, const G4Step &, G4VEmModel *model, G4int matIdx)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
G4double GetDEDXDispersion (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double length)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double MeanFreePath (const G4Track &track)
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t &idx) const
void AddEmModel (G4int, G4VEmModel *, G4VEmFluctuationModel *fluc=0, const G4Region *region=nullptr)
void UpdateEmModel (const G4String &, G4double, G4double)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
G4int NumberOfModels () const
void SetFluctModel (G4VEmFluctuationModel *)
G4VEmFluctuationModel * FluctModel ()
void SetBaseParticle (const G4ParticleDefinition *p)
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * BaseParticle () const
const G4ParticleDefinition * SecondaryParticle () const
void ActivateSubCutoff (G4bool val, const G4Region *region=nullptr)
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
void ActivateForcedInteraction (G4double length, const G4String &region, G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void AddCollaborativeProcess (G4VEnergyLossProcess *)
void SetLossFluctuations (G4bool val)
void SetIntegral (G4bool val)
G4bool IsIntegral () const
void SetIonisation (G4bool val)
G4bool IsIonisationProcess () const
void SetLinearLossLimit (G4double val)
void SetStepFunction (G4double v1, G4double v2, G4bool lock=true)
void SetLowestEnergyLimit (G4double)
G4int NumberOfSubCutoffRegions () const
void SetDEDXTable (G4PhysicsTable *p, G4EmTableType tType)
void SetCSDARangeTable (G4PhysicsTable *pRange)
void SetRangeTableForLoss (G4PhysicsTable *p)
void SetSecondaryRangeTable (G4PhysicsTable *p)
void SetInverseRangeTable (G4PhysicsTable *p)
void SetLambdaTable (G4PhysicsTable *p)
void SetSubLambdaTable (G4PhysicsTable *p)
void SetDEDXBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
G4double MinKinEnergy () const
void SetMaxKinEnergy (G4double e)
G4double MaxKinEnergy () const
G4double CrossSectionBiasingFactor () const
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetKineticEnergy (G4double range, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4bool TablesAreBuilt () const
G4PhysicsTable * DEDXTable () const
G4PhysicsTable * DEDXTableForSubsec () const
G4PhysicsTable * DEDXunRestrictedTable () const
G4PhysicsTable * IonisationTable () const
G4PhysicsTable * IonisationTableForSubsec () const
G4PhysicsTable * CSDARangeTable () const
G4PhysicsTable * SecondaryRangeTable () const
G4PhysicsTable * RangeTableForLoss () const
G4PhysicsTable * InverseRangeTable () const
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * SubLambdaTable () const
const G4Element * GetCurrentElement () const
void SetDynamicMassCharge (G4double massratio, G4double charge2ratio)
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void StreamProcessInfo (std::ostream &) const
virtual void InitialiseEnergyLossProcess (const G4ParticleDefinition *, const G4ParticleDefinition *)=0
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *, G4double cut)
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety) override
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *, G4double cut)
size_t CurrentMaterialCutsCoupleIndex () const
void SelectModel (G4double kinEnergy)
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4ParticleChangeForLoss fParticleChange
const G4Material * currentMaterial
const G4MaterialCutsCouple * currentCouple
size_t currentCoupleIndex
G4double preStepLambda
G4double fRange
G4double computedRange
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepScaledEnergy
G4double preStepLogScaledEnergy
G4double preStepRangeEnergy
G4double mfpKinEnergy
Private Member Functions
void Clean ()
void StreamInfo (std::ostream &out, const G4ParticleDefinition &part, G4bool rst=false) const
G4bool StoreTable (const G4ParticleDefinition *p, G4PhysicsTable *, G4bool ascii, const G4String &directory, const G4String &tname)
G4bool RetrieveTable (const G4ParticleDefinition *p, G4PhysicsTable *, G4bool ascii, const G4String &directory, const G4String &tname, G4bool mandatory)
void FillSecondariesAlongStep (G4double &eloss, G4double &weight)
void PrintWarning (G4String, G4double val)
void DefineMaterial (const G4MaterialCutsCouple *couple)
G4double GetDEDXForScaledEnergy (G4double scaledKinEnergy)
G4double GetDEDXForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy)
G4double GetSubDEDXForScaledEnergy (G4double scaledKinEnergy)
G4double GetIonisationForScaledEnergy (G4double scaledKinEnergy)
G4double GetSubIonisationForScaledEnergy (G4double scaledKinEnergy)
G4double GetScaledRangeForScaledEnergy (G4double scaledKinEnergy)
G4double GetScaledRangeForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy)
G4double GetLimitScaledRangeForScaledEnergy (G4double scaledKinEnergy)
G4double GetLimitScaledRangeForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy)
G4double ScaledKinEnergyForLoss (G4double range)
G4double GetLambdaForScaledEnergy (G4double scaledKinEnergy)
G4double GetLambdaForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy)
void ComputeLambdaForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy)
G4VEnergyLossProcess (G4VEnergyLossProcess &)=delete
G4VEnergyLossProcess & operator= (const G4VEnergyLossProcess &right)=delete
Private Attributes
G4LossTableManager * lManager
G4EmModelManager * modelManager
G4EmBiasingManager * biasManager
G4SafetyHelper * safetyHelper
G4EmParameters * theParameters
const G4ParticleDefinition * secondaryParticle
const G4ParticleDefinition * theElectron
const G4ParticleDefinition * thePositron
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theGenericIon
std::vector< G4VEmModel * > emModels
G4VEmFluctuationModel * fluctModel
G4VAtomDeexcitation * atomDeexcitation
G4VSubCutProducer * subcutProducer
std::vector< const G4Region * > scoffRegions
G4int nSCoffRegions
G4bool * idxSCoffRegions
std::vector
< G4VEnergyLossProcess * > scProcesses
G4int nProcesses
G4PhysicsTable * theDEDXTable
G4PhysicsTable * theDEDXSubTable
G4PhysicsTable * theDEDXunRestrictedTable
G4PhysicsTable * theIonisationTable
G4PhysicsTable * theIonisationSubTable
G4PhysicsTable * theRangeTableForLoss
G4PhysicsTable * theCSDARangeTable
G4PhysicsTable * theSecondaryRangeTable
G4PhysicsTable * theInverseRangeTable
G4PhysicsTable * theLambdaTable
G4PhysicsTable * theSubLambdaTable
size_t idxDEDX
size_t idxDEDXSub
size_t idxDEDXunRestricted
size_t idxIonisation
size_t idxIonisationSub
size_t idxRange
size_t idxCSDA
size_t idxSecRange
size_t idxInverseRange
size_t idxLambda
size_t idxSubLambda
std::vector< G4double > theDEDXAtMaxEnergy
std::vector< G4double > theRangeAtMaxEnergy
std::vector< G4double > theEnergyOfCrossSectionMax
std::vector< G4double > theCrossSectionMax
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
const G4DataVector * theCuts
const G4DataVector * theSubCuts
const G4ParticleDefinition * baseParticle
G4int nBins
G4int nBinsCSDA
G4double lowestKinEnergy
G4double minKinEnergy
G4double maxKinEnergy
G4double maxKinEnergyCSDA
G4double linLossLimit
G4double dRoverRange
G4double finalRange
G4double lambdaFactor
G4double logLambdafactor
G4double biasFactor
G4bool lossFluctuationFlag
G4bool rndmStepFlag
G4bool tablesAreBuilt
G4bool integral
G4bool isIon
G4bool isIonisation
G4bool useSubCutoff
G4bool useDeexcitation
G4bool biasFlag
G4bool weightFlag
G4bool isMaster
G4bool actIntegral
G4bool actStepFunc
G4bool actLinLossLimit
G4bool actLossFluc
G4bool actBinning
G4bool actMinKinEnergy
G4bool actMaxKinEnergy
std::vector< G4DynamicParticle * > secParticles
std::vector< G4Track * > scTracks
const G4ParticleDefinition * particle
G4VEmModel * currentModel
size_t basedCoupleIndex
size_t lastIdx
G4double massRatio
G4double logMassRatio
G4double fFactor
G4double reduceFactor
G4double chargeSqRatio
G4GPILSelection aGPILSelection
G4int secID
G4int subsecID
G4int biasID
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 81 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VEnergyLossProcess.hh
Constructor & Destructor Documentation
G4VEnergyLossProcess::G4VEnergyLossProcess (const G4String & name = "EnergyLoss", G4ProcessType type = fElectromagnetic)
Definition at line 86 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 86 of file G4VEnergyLossProcess.cc
References actBinning, actIntegral, actLinLossLimit, actLossFluc, actMaxKinEnergy, actMinKinEnergy, actStepFunc, aGPILSelection, atomDeexcitation, basedCoupleIndex, biasFactor, biasFlag, biasID, biasManager, CandidateForSelection, chargeSqRatio, computedRange, currentCoupleIndex, currentMaterial, currentModel, DBL_MAX, dRoverRange, G4Electron::Electron(), fFactor, finalRange, fluctModel, fParticleChange, fRange, G4Log(), G4Gamma::Gamma(), G4LossTableBuilder::GetCoupleIndexes(), G4LossTableBuilder::GetDensityFactors(), G4TransportationManager::GetSafetyHelper(), G4LossTableManager::GetTableBuilder(), G4TransportationManager::GetTransportationManager(), GeV, idxCSDA, idxDEDX, idxDEDXSub, idxDEDXunRestricted, idxInverseRange, idxIonisation, idxIonisationSub, idxLambda, idxRange, idxSecRange, idxSubLambda, G4EmParameters::Instance(), G4LossTableManager::Instance(), isMaster, keV, lambdaFactor, lastIdx, linLossLimit, lManager, LOG_EKIN_MIN, logLambdafactor, logMassRatio, G4EmParameters::LowestElectronEnergy(), lowestKinEnergy, massRatio, maxKinEnergy, maxKinEnergyCSDA, minKinEnergy, CLHEP::mm, modelManager, nBins, nBinsCSDA, G4Positron::Positron(), G4VProcess::pParticleChange, preStepKinEnergy, preStepLambda, preStepLogKinEnergy, preStepLogScaledEnergy, preStepRangeEnergy, preStepScaledEnergy, reduceFactor, G4LossTableManager::Register(), safetyHelper, scTracks, secID, secParticles, G4VParticleChange::SetSecondaryWeightByProcess(), G4VProcess::SetVerboseLevel(), subcutProducer, subsecID, TeV, theCuts, theDensityFactor, theDensityIdx, theElectron, theGamma, theGenericIon, theParameters, thePositron, theSubCuts, and weightFlag.
G4VEnergyLossProcess::~G4VEnergyLossProcess () virtual
Definition at line 199 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 199 of file G4VEnergyLossProcess.cc
References baseParticle, biasManager, Clean(), G4PhysicsTable::clearAndDestroy(), G4LossTableManager::DeRegister(), isIonisation, isMaster, lManager, modelManager, theCSDARangeTable, theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theInverseRangeTable, theIonisationSubTable, theIonisationTable, theLambdaTable, theRangeTableForLoss, and theSubLambdaTable.
G4VEnergyLossProcess::G4VEnergyLossProcess (G4VEnergyLossProcess &) private delete
Member Function Documentation
void G4VEnergyLossProcess::ActivateForcedInteraction (G4double length, const G4String & region, G4bool flag = true)
Definition at line 2239 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2239 of file G4VEnergyLossProcess.cc
References G4EmBiasingManager::ActivateForcedInteraction(), biasManager, G4cout, G4endl, G4VProcess::GetProcessName(), mm, G4VProcess::verboseLevel, and weightFlag.
Referenced by G4EmExtraParameters::DefineRegParamForLoss().
void G4VEnergyLossProcess::ActivateSecondaryBiasing (const G4String & region, G4double factor, G4double energyLimit)
Definition at line 2259 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2259 of file G4VEnergyLossProcess.cc
References G4EmBiasingManager::ActivateSecondaryBiasing(), biasManager, G4Electron::Electron(), G4cout, G4endl, G4VProcess::GetProcessName(), MeV, secondaryParticle, and G4VProcess::verboseLevel.
Referenced by G4EmExtraParameters::DefineRegParamForLoss().
void G4VEnergyLossProcess::ActivateSubCutoff (G4bool val, const G4Region * region = nullptr)
Definition at line 959 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 959 of file G4VEnergyLossProcess.cc
References G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), nSCoffRegions, r, reg, and scoffRegions.
Referenced by G4EmExtraParameters::DefineRegParamForLoss().
void G4VEnergyLossProcess::AddCollaborativeProcess (G4VEnergyLossProcess * p)
Definition at line 1988 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1988 of file G4VEnergyLossProcess.cc
References G4cout, G4endl, G4VProcess::GetProcessName(), nProcesses, scProcesses, and G4VProcess::verboseLevel.
Referenced by G4LossTableManager::BuildTables().
void G4VEnergyLossProcess::AddEmModel (G4int order, G4VEmModel * p, G4VEmFluctuationModel * fluc = 0, const G4Region * region = nullptr)
Definition at line 315 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 315 of file G4VEnergyLossProcess.cc
References G4EmModelManager::AddEmModel(), modelManager, G4VProcess::pParticleChange, and G4VEmModel::SetParticleChange().
Referenced by DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), G4EmPenelopePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4EmConfigurator::PrepareModels(), and G4EmConfigurator::SetModelForRegion().
G4VParticleChange * G4VEnergyLossProcess::AlongStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 1189 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1189 of file G4VEnergyLossProcess.cc
References G4VAtomDeexcitation::AlongStepDeexcitation(), atomDeexcitation, biasFactor, G4SafetyHelper::ComputeSafety(), G4VEmModel::CorrectionsAlongStep(), currentCouple, currentCoupleIndex, currentMaterial, currentModel, fGeomBoundary, FillSecondariesAlongStep(), fParticleChange, fRange, GetDEDXForScaledEnergy(), G4Track::GetDynamicParticle(), G4VEmModel::GetModelOfFluctuations(), G4VParticleChange::GetParentWeight(), G4VEmModel::GetParticleCharge(), G4Track::GetParticleDefinition(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), G4StepPoint::GetSafety(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), GetSubDEDXForScaledEnergy(), idxSCoffRegions, G4ParticleChangeForLoss::InitializeForAlongStep(), G4VEmModel::IsActive(), isIon, isIonisation, BTOF::length, linLossLimit, lossFluctuationFlag, lowestKinEnergy, massRatio, max, G4VEmModel::MaxSecondaryKinEnergy(), min, preStepKinEnergy, preStepLogScaledEnergy, preStepScaledEnergy, G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeWeight(), reduceFactor, safetyHelper, G4VEmFluctuationModel::SampleFluctuations(), G4VSubCutProducer::SampleSecondaries(), SampleSubCutSecondaries(), ScaledKinEnergyForLoss(), scTracks, G4ParticleChangeForLoss::SetProposedCharge(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), subcutProducer, useDeexcitation, useSubCutoff, weight, weightFlag, and x.
G4double G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 1026 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1026 of file G4VEnergyLossProcess.cc
References aGPILSelection, currentCouple, currentModel, DBL_MAX, dRoverRange, finalRange, fRange, G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), GetScaledRangeForScaledEnergy(), G4VEmModel::IsActive(), isIonisation, min, preStepLogScaledEnergy, preStepScaledEnergy, reduceFactor, rndmStepFlag, and x.
Referenced by ContinuousStepLimit().
const G4ParticleDefinition * G4VEnergyLossProcess::BaseParticle () const inline
Definition at line 979 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 979 of file G4VEnergyLossProcess.hh
References baseParticle.
Referenced by G4LossTableManager::BuildPhysicsTable(), G4LossTableManager::LocalPhysicsTables(), G4LossTableManager::RegisterExtraParticle(), and G4EmCalculator::UpdateParticle().
G4PhysicsTable * G4VEnergyLossProcess::BuildDEDXTable (G4EmTableType tType = fRestricted)
Definition at line 716 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 716 of file G4VEnergyLossProcess.cc
References bin, emax, G4EmModelManager::FillDEDXVector(), G4PhysicsVector::FillSecondDerivatives(), fRestricted, fSubRestricted, fTotal, G4cout, G4endl, G4LossTableBuilder::GetFlag(), G4PhysicsTable::GetFlag(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4ProductionCutsTable::GetTableSize(), lManager, maxKinEnergy, maxKinEnergyCSDA, minKinEnergy, modelManager, nBins, nBinsCSDA, particle, G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), G4EmParameters::Spline(), theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theParameters, and G4VProcess::verboseLevel.
Referenced by G4LossTableManager::BuildTables().
G4PhysicsTable * G4VEnergyLossProcess::BuildLambdaTable (G4EmTableType tType = fRestricted)
Definition at line 804 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 804 of file G4VEnergyLossProcess.cc
References bin, emax, CEMC_TOWER::emin, G4EmModelManager::FillLambdaVector(), G4PhysicsVector::FillSecondDerivatives(), fRestricted, fSubRestricted, G4cout, G4endl, G4Log(), G4lrint(), G4LossTableBuilder::GetCoupleIndexes(), G4LossTableBuilder::GetDensityFactors(), G4LossTableBuilder::GetFlag(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4ProductionCutsTable::GetTableSize(), lManager, max, maxKinEnergy, minKinEnergy, MinPrimaryEnergy(), modelManager, nBins, particle, scale, G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), G4EmParameters::Spline(), theDensityFactor, theDensityIdx, theLambdaTable, theParameters, theSubLambdaTable, and G4VProcess::verboseLevel.
Referenced by G4LossTableManager::BuildTables().
void G4VEnergyLossProcess::BuildPhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4ePolarizedIonisation.
Definition at line 616 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 616 of file G4VEnergyLossProcess.cc
References G4LossTableManager::AtomDeexcitation(), atomDeexcitation, baseParticle, G4LossTableManager::BuildPhysicsTable(), CSDARangeTable(), DEDXTable(), DEDXTableForSubsec(), DEDXunRestrictedTable(), fIsIonisation, fIsSubIonisation, fRestricted, fSubRestricted, fTotal, G4cout, G4endl, G4VProcess::GetMasterProcess(), GetModelByIndex(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4SafetyHelper::InitialiseHelper(), G4VEmModel::InitialiseLocal(), InverseRangeTable(), IonisationTable(), IonisationTableForSubsec(), isIon, isIonisation, IsIonisationProcess(), isMaster, G4VAtomDeexcitation::IsPIXEActive(), LambdaTable(), lManager, G4LossTableManager::LocalPhysicsTables(), modelManager, nSCoffRegions, num, G4EmModelManager::NumberOfModels(), particle, RangeTableForLoss(), safetyHelper, SecondaryRangeTable(), SetCSDARangeTable(), SetDEDXTable(), SetInverseRangeTable(), SetLambdaTable(), SetRangeTableForLoss(), SetSecondaryRangeTable(), SetSubLambdaTable(), StreamInfo(), G4LossTableManager::SubCutProducer(), subcutProducer, SubLambdaTable(), tablesAreBuilt, useDeexcitation, and G4VProcess::verboseLevel.
Referenced by G4ePolarizedIonisation::BuildPhysicsTable().
void G4VEnergyLossProcess::Clean () private
Definition at line 284 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 284 of file G4VEnergyLossProcess.cc
References idxCSDA, idxDEDX, idxDEDXSub, idxDEDXunRestricted, idxInverseRange, idxIonisation, idxIonisationSub, idxLambda, idxRange, idxSCoffRegions, idxSecRange, idxSubLambda, nProcesses, scProcesses, and tablesAreBuilt.
Referenced by PreparePhysicsTable(), and ~G4VEnergyLossProcess().
void G4VEnergyLossProcess::ComputeLambdaForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy) private
Definition at line 1159 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1159 of file G4VEnergyLossProcess.cc
References currentCoupleIndex, e, e1, fFactor, GetLambdaForScaledEnergy(), lambdaFactor, logLambdafactor, mfpKinEnergy, preStepLambda, theCrossSectionMax, and theEnergyOfCrossSectionMax.
Referenced by PostStepGetPhysicalInteractionLength().
G4double G4VEnergyLossProcess::ContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety)
Definition at line 1945 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1945 of file G4VEnergyLossProcess.cc
References AlongStepGetPhysicalInteractionLength().
G4double G4VEnergyLossProcess::CrossSectionBiasingFactor () const inline
Definition at line 1045 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1045 of file G4VEnergyLossProcess.hh
References biasFactor.
G4double G4VEnergyLossProcess::CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple * couple)
G4double G4VEnergyLossProcess::CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple * couple, G4double logKineticEnergy)
Definition at line 1911 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1911 of file G4VEnergyLossProcess.cc
References biasFactor, Acts::VectorHelpers::cross(), G4VEmModel::CrossSectionPerVolume(), currentCoupleIndex, currentMaterial, currentModel, DefineMaterial(), GetLambdaForScaledEnergy(), logMassRatio, massRatio, max, particle, SelectModel(), theCuts, and theLambdaTable.
G4PhysicsTable * G4VEnergyLossProcess::CSDARangeTable () const inline
Definition at line 1094 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1094 of file G4VEnergyLossProcess.hh
References theCSDARangeTable.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
size_t G4VEnergyLossProcess::CurrentMaterialCutsCoupleIndex () const inline protected
Definition at line 596 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 596 of file G4VEnergyLossProcess.hh
References currentCoupleIndex.
Referenced by G4ePolarizedIonisation::ComputeSaturationFactor().
G4PhysicsTable * G4VEnergyLossProcess::DEDXTable () const inline
Definition at line 1059 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1059 of file G4VEnergyLossProcess.hh
References theDEDXTable.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::LocalPhysicsTables(), and G4EmCalculator::PrintDEDXTable().
G4PhysicsTable * G4VEnergyLossProcess::DEDXTableForSubsec () const inline
Definition at line 1066 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1066 of file G4VEnergyLossProcess.hh
References theDEDXSubTable.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
G4PhysicsTable * G4VEnergyLossProcess::DEDXunRestrictedTable () const inline
Definition at line 1073 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1073 of file G4VEnergyLossProcess.hh
References theDEDXunRestrictedTable.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::DefineMaterial (const G4MaterialCutsCouple * couple) inline private
Definition at line 620 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 620 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, biasFactor, chargeSqRatio, currentCouple, currentCoupleIndex, currentMaterial, DBL_MAX, fFactor, G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), idxLambda, idxSubLambda, massRatio, mfpKinEnergy, and reduceFactor.
Referenced by CrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetDEDXForSubsec(), GetKineticEnergy(), GetLambda(), GetRange(), GetRangeForLoss(), MeanFreePath(), and PostStepGetPhysicalInteractionLength().
G4VEmModel * G4VEnergyLossProcess::EmModel (size_t index = 0) const
Definition at line 341 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 341 of file G4VEnergyLossProcess.cc
References emModels.
Referenced by G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::StreamProcessInfo(), G4MuPairProduction::StreamProcessInfo(), and G4eBremsstrahlung::StreamProcessInfo().
void G4VEnergyLossProcess::FillSecondariesAlongStep (G4double & eloss, G4double & weight) private
Definition at line 1450 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1450 of file G4VEnergyLossProcess.cc
References G4VParticleChange::AddSecondary(), G4EmBiasingManager::ApplySecondaryBiasing(), biasID, biasManager, currentCoupleIndex, fParticleChange, n, G4VProcess::pParticleChange, scTracks, G4EmBiasingManager::SecondaryBiasingRegion(), G4Track::SetCreatorModelIndex(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetWeight(), and t.
Referenced by AlongStepDoIt().
G4VEmFluctuationModel * G4VEnergyLossProcess::FluctModel () inline
Definition at line 942 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 942 of file G4VEnergyLossProcess.hh
References fluctModel.
Referenced by G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
G4double G4VEnergyLossProcess::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) override protected virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 1967 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1967 of file G4VEnergyLossProcess.cc
References DBL_MAX.
G4double G4VEnergyLossProcess::GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 871 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 871 of file G4VEnergyLossProcess.hh
References DBL_MAX, DefineMaterial(), GetLimitScaledRangeForScaledEnergy(), massRatio, reduceFactor, and theCSDARangeTable.
Referenced by G4LossTableManager::GetCSDARange().
const G4Element * G4VEnergyLossProcess::GetCurrentElement () const
Definition at line 2212 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2212 of file G4VEnergyLossProcess.cc
References currentModel, and G4VEmModel::GetCurrentElement().
G4double G4VEnergyLossProcess::GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 809 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 809 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetDEDXForScaledEnergy(), and massRatio.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4LossTableManager::GetDEDX(), and G4VMscModel::GetDEDX().
G4double G4VEnergyLossProcess::GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple * couple, G4double logKineticEnergy) inline
Definition at line 817 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 817 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetDEDXForScaledEnergy(), logMassRatio, and massRatio.
G4double G4VEnergyLossProcess::GetDEDXDispersion (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double length)
Definition at line 1892 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1892 of file G4VEnergyLossProcess.cc
References currentCoupleIndex, currentMaterial, currentModel, d, DefineMaterial(), G4VEmFluctuationModel::Dispersion(), Acts::UnitConstants::fm, G4DynamicParticle::GetKineticEnergy(), G4VEmModel::GetModelOfFluctuations(), massRatio, G4VEmModel::MaxSecondaryKinEnergy(), min, SelectModel(), and theCuts.
Referenced by G4LossTableManager::GetDEDXDispersion().
G4double G4VEnergyLossProcess::GetDEDXForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 648 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 648 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, fFactor, idxDEDX, minKinEnergy, and x.
Referenced by AlongStepDoIt(), and GetDEDX().
G4double G4VEnergyLossProcess::GetDEDXForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy) inline private
Definition at line 661 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 661 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, fFactor, minKinEnergy, and x.
G4double G4VEnergyLossProcess::GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 828 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 828 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetSubDEDXForScaledEnergy(), and massRatio.
Referenced by G4LossTableManager::GetSubDEDX().
G4double G4VEnergyLossProcess::GetIonisationForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 685 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 685 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, fFactor, idxIonisation, minKinEnergy, and x.
G4double G4VEnergyLossProcess::GetKineticEnergy (G4double range, const G4MaterialCutsCouple * couple) inline
Definition at line 905 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 905 of file G4VEnergyLossProcess.hh
References DefineMaterial(), massRatio, reduceFactor, and ScaledKinEnergyForLoss().
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4LossTableManager::GetEnergy(), and G4VMscModel::GetEnergy().
G4double G4VEnergyLossProcess::GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 915 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 915 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetLambdaForScaledEnergy(), massRatio, and theLambdaTable.
G4double G4VEnergyLossProcess::GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple * couple, G4double logKineticEnergy) inline
Definition at line 923 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 923 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetLambdaForScaledEnergy(), logMassRatio, massRatio, and theLambdaTable.
G4double G4VEnergyLossProcess::GetLambdaForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 795 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 795 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, fFactor, and idxLambda.
Referenced by ComputeLambdaForScaledEnergy(), CrossSectionPerVolume(), GetLambda(), MeanFreePath(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4double G4VEnergyLossProcess::GetLambdaForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy) inline private
Definition at line 801 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 801 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, and fFactor.
G4double G4VEnergyLossProcess::GetLimitScaledRangeForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 747 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 747 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, idxCSDA, maxKinEnergyCSDA, minKinEnergy, theDEDXAtMaxEnergy, theRangeAtMaxEnergy, and x.
Referenced by GetCSDARange(), and GetRange().
G4double G4VEnergyLossProcess::GetLimitScaledRangeForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy) inline private
Definition at line 761 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 761 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, maxKinEnergyCSDA, minKinEnergy, theDEDXAtMaxEnergy, theRangeAtMaxEnergy, and x.
G4double G4VEnergyLossProcess::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Implements G4VContinuousDiscreteProcess.
Reimplemented in G4ePolarizedIonisation.
Definition at line 1955 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1955 of file G4VEnergyLossProcess.cc
References MeanFreePath(), and NotForced.
Referenced by G4ePolarizedIonisation::GetMeanFreePath().
G4VEmModel * G4VEnergyLossProcess::GetModelByIndex (G4int idx = 0, G4bool ver = false) const
Definition at line 348 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 348 of file G4VEnergyLossProcess.cc
References G4EmModelManager::GetModel(), and modelManager.
Referenced by BuildPhysicsTable().
G4double G4VEnergyLossProcess::GetRange (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 838 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 838 of file G4VEnergyLossProcess.hh
References DefineMaterial(), fRange, GetLimitScaledRangeForScaledEnergy(), GetScaledRangeForScaledEnergy(), massRatio, reduceFactor, theCSDARangeTable, theRangeTableForLoss, and x.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), and G4LossTableManager::GetRange().
G4double G4VEnergyLossProcess::GetRange (G4double kineticEnergy, const G4MaterialCutsCouple * couple, G4double logKineticEnergy) inline
Definition at line 852 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 852 of file G4VEnergyLossProcess.hh
References DefineMaterial(), fRange, GetLimitScaledRangeForScaledEnergy(), GetScaledRangeForScaledEnergy(), logMassRatio, massRatio, reduceFactor, theCSDARangeTable, theRangeTableForLoss, and x.
G4double G4VEnergyLossProcess::GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 883 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 883 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetScaledRangeForScaledEnergy(), massRatio, and reduceFactor.
Referenced by G4EmBiasingManager::ApplyRangeCut(), G4VMscModel::GetRange(), and G4LossTableManager::GetRangeFromRestricteDEDX().
G4double G4VEnergyLossProcess::GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple * couple, G4double logKineticEnergy) inline
Definition at line 892 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 892 of file G4VEnergyLossProcess.hh
References DefineMaterial(), GetScaledRangeForScaledEnergy(), logMassRatio, massRatio, and reduceFactor.
G4double G4VEnergyLossProcess::GetScaledRangeForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 706 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 706 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, computedRange, e, idxRange, lastIdx, minKinEnergy, and preStepRangeEnergy.
Referenced by AlongStepGetPhysicalInteractionLength(), GetRange(), and GetRangeForLoss().
G4double G4VEnergyLossProcess::GetScaledRangeForScaledEnergy (G4double scaledKinEnergy, G4double logScaledKinEnergy) inline private
Definition at line 726 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 726 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, computedRange, e, lastIdx, minKinEnergy, and preStepRangeEnergy.
G4double G4VEnergyLossProcess::GetSubDEDXForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 675 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 675 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, fFactor, idxDEDXSub, minKinEnergy, and x.
Referenced by AlongStepDoIt(), and GetDEDXForSubsec().
G4double G4VEnergyLossProcess::GetSubIonisationForScaledEnergy (G4double scaledKinEnergy) inline private
Definition at line 696 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 696 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, fFactor, idxIonisationSub, minKinEnergy, and x.
virtual void G4VEnergyLossProcess::InitialiseEnergyLossProcess (const G4ParticleDefinition * , const G4ParticleDefinition *) protected pure virtual
Implemented in G4hIonisation, G4MuIonisation, G4MuBremsstrahlung, G4ionIonisation, G4eBremsstrahlung, G4eIonisation, G4MuPairProduction, G4mplIonisation, G4hhIonisation, G4ePolarizedIonisation, G4ePairProduction, G4alphaIonisation, G4hBremsstrahlung, G4hPairProduction, G4LDMBremsstrahlung, and G4ePolarizedBremsstrahlung.
Referenced by PreparePhysicsTable().
G4PhysicsTable * G4VEnergyLossProcess::InverseRangeTable () const inline
Definition at line 1115 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1115 of file G4VEnergyLossProcess.hh
References theInverseRangeTable.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), G4LossTableManager::LocalPhysicsTables(), and G4EmCalculator::PrintInverseRangeTable().
G4PhysicsTable * G4VEnergyLossProcess::IonisationTable () const inline
Definition at line 1080 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1080 of file G4VEnergyLossProcess.hh
References theIonisationTable.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
G4PhysicsTable * G4VEnergyLossProcess::IonisationTableForSubsec () const inline
Definition at line 1087 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1087 of file G4VEnergyLossProcess.hh
References theIonisationSubTable.
Referenced by BuildPhysicsTable(), and G4LossTableManager::BuildTables().
virtual G4bool G4VEnergyLossProcess::IsApplicable (const G4ParticleDefinition & p) override pure virtual
Reimplemented from G4VProcess.
Implemented in G4MuIonisation, G4hIonisation, G4eBremsstrahlung, G4eIonisation, G4MuBremsstrahlung, G4ionIonisation, G4MuPairProduction, G4ePolarizedIonisation, G4mplIonisation, G4hBremsstrahlung, G4hhIonisation, G4hPairProduction, G4alphaIonisation, G4ePairProduction, and G4LDMBremsstrahlung.
G4bool G4VEnergyLossProcess::IsIntegral () const inline
Definition at line 1010 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1010 of file G4VEnergyLossProcess.hh
References integral.
G4bool G4VEnergyLossProcess::IsIonisationProcess () const inline
Definition at line 1017 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1017 of file G4VEnergyLossProcess.hh
References isIonisation.
Referenced by G4LossTableManager::BuildPhysicsTable(), BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), and G4LossTableManager::LocalPhysicsTables().
G4PhysicsVector * G4VEnergyLossProcess::LambdaPhysicsVector (const G4MaterialCutsCouple * , G4double cut) protected
Definition at line 1977 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1977 of file G4VEnergyLossProcess.cc
References maxKinEnergy, minKinEnergy, nBins, G4PhysicsVector::SetSpline(), G4EmParameters::Spline(), theParameters, and v.
Referenced by G4ePolarizedIonisation::BuildAsymmetryTables().
G4PhysicsTable * G4VEnergyLossProcess::LambdaTable () const inline
Definition at line 1122 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1122 of file G4VEnergyLossProcess.hh
References theLambdaTable.
Referenced by BuildPhysicsTable(), G4LossTableManager::CopyTables(), and G4EmCalculator::FindLambdaTable().
G4double G4VEnergyLossProcess::MaxKinEnergy () const inline
Definition at line 1038 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1038 of file G4VEnergyLossProcess.hh
References maxKinEnergy.
G4double G4VEnergyLossProcess::MeanFreePath (const G4Track & track)
Definition at line 1933 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1933 of file G4VEnergyLossProcess.cc
References DBL_MAX, DefineMaterial(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), GetLambdaForScaledEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4Track::GetMaterialCutsCouple(), logMassRatio, and massRatio.
Referenced by GetMeanFreePath().
G4double G4VEnergyLossProcess::MinKinEnergy () const inline
Definition at line 1031 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1031 of file G4VEnergyLossProcess.hh
References minKinEnergy.
Referenced by G4LDMBremsstrahlung::MinPrimaryEnergy().
G4double G4VEnergyLossProcess::MinPrimaryEnergy (const G4ParticleDefinition * , const G4Material * , G4double cut) protected virtual
Reimplemented in G4ionIonisation, G4eIonisation, G4MuIonisation, G4hIonisation, G4MuBremsstrahlung, G4ePolarizedIonisation, G4MuPairProduction, G4alphaIonisation, G4mplIonisation, G4hhIonisation, G4ePairProduction, and G4LDMBremsstrahlung.
Definition at line 306 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 306 of file G4VEnergyLossProcess.cc
Referenced by BuildLambdaTable().
G4int G4VEnergyLossProcess::NumberOfModels () const
Definition at line 355 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 355 of file G4VEnergyLossProcess.cc
References modelManager, and G4EmModelManager::NumberOfModels().
G4int G4VEnergyLossProcess::NumberOfSubCutoffRegions () const inline
Definition at line 1024 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1024 of file G4VEnergyLossProcess.hh
References nSCoffRegions.
Referenced by G4LossTableManager::BuildTables().
G4VEnergyLossProcess& G4VEnergyLossProcess::operator= (const G4VEnergyLossProcess & right) private delete
const G4ParticleDefinition * G4VEnergyLossProcess::Particle () const inline
Definition at line 972 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 972 of file G4VEnergyLossProcess.hh
References particle.
Referenced by G4LossTableManager::BuildPhysicsTable(), and G4LossTableManager::LocalPhysicsTables().
G4VParticleChange * G4VEnergyLossProcess::PostStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 1560 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1560 of file G4VEnergyLossProcess.cc
References G4VParticleChange::AddSecondary(), G4EmBiasingManager::ApplySecondaryBiasing(), biasFactor, biasFlag, biasID, biasManager, currentCouple, currentCoupleIndex, G4VProcess::currentInteractionLength, currentModel, DBL_MAX, fAlive, G4EmBiasingManager::ForcedInteractionRegion(), fParticleChange, fStopAndKill, fStopButAlive, G4UniformRand, G4ProcessManager::GetAtRestProcessVector(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), GetLambdaForScaledEnergy(), G4VParticleChange::GetLocalEnergyDeposit(), G4DynamicParticle::GetLogKineticEnergy(), G4VParticleChange::GetParentWeight(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4ParticleDefinition::GetProcessManager(), G4ParticleChangeForLoss::GetProposedKineticEnergy(), G4StepPoint::GetSafety(), G4Track::GetTouchableHandle(), G4VParticleChange::GetTrackStatus(), G4EmBiasingManager::GetWeight(), G4ParticleChangeForLoss::InitializeForPostStep(), integral, G4VEmModel::IsActive(), logMassRatio, lowestKinEnergy, massRatio, mfpKinEnergy, num, particle, G4VProcess::pParticleChange, preStepLambda, G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4VEmModel::SampleSecondaries(), secID, G4EmBiasingManager::SecondaryBiasingRegion(), secParticles, SelectModel(), G4Track::SetCreatorModelIndex(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), G4ProcessVector::size(), t, G4VProcess::theNumberOfInteractionLengthLeft, Acts::VectorHelpers::time(), weight, and weightFlag.
G4double G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Reimplemented in G4ePolarizedIonisation.
Definition at line 1057 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1057 of file G4VEnergyLossProcess.cc
References biasFactor, biasFlag, biasManager, chargeSqRatio, G4VEmModel::ChargeSquareRatio(), cm, ComputeLambdaForScaledEnergy(), currentCoupleIndex, G4VProcess::currentInteractionLength, currentMaterial, currentModel, DBL_MAX, DefineMaterial(), fFactor, G4EmBiasingManager::ForcedInteractionRegion(), G4cout, G4endl, G4Log(), G4UniformRand, G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), GetLambdaForScaledEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4Track::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4Material::GetName(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4EmBiasingManager::GetStepLimit(), integral, G4VEmModel::IsActive(), isIon, logMassRatio, massRatio, max, MeV, mfpKinEnergy, NotForced, preStepKinEnergy, preStepLambda, preStepLogKinEnergy, preStepLogScaledEnergy, preStepScaledEnergy, reduceFactor, SelectModel(), G4VProcess::theInitialNumberOfInteractionLength, G4VProcess::theNumberOfInteractionLengthLeft, G4VProcess::verboseLevel, and x.
Referenced by G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength().
void G4VEnergyLossProcess::PreparePhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Definition at line 363 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 363 of file G4VEnergyLossProcess.cc
References actBinning, actIntegral, actLinLossLimit, actLossFluc, actMaxKinEnergy, actMinKinEnergy, baseParticle, biasFlag, biasID, biasManager, G4EmParameters::BuildCSDARange(), chargeSqRatio, Clean(), G4PhysicsTable::clearAndDestroy(), currentCouple, DBL_MAX, G4EmParameters::DefineRegParamForLoss(), fFactor, G4ParticleTable::FindParticle(), fRange, G4cout, G4endl, G4Log(), G4lrint(), G4ProcessManager::GetAlongStepProcessVector(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4EmModelManager::GetModel(), G4Region::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4ProductionCutsTable::GetTableSize(), G4VEmModel::HighEnergyLimit(), idxSCoffRegions, G4EmBiasingManager::Initialise(), G4EmModelManager::Initialise(), G4LossTableBuilder::InitialiseBaseMaterials(), InitialiseEnergyLossProcess(), G4EmParameters::Integral(), integral, isIon, isIonisation, G4LossTableManager::IsMaster(), isMaster, G4EmParameters::LambdaFactor(), lambdaFactor, lastIdx, G4EmParameters::LinearLossLimit(), linLossLimit, lManager, LOG_EKIN_MIN, logLambdafactor, logMassRatio, G4EmParameters::LossFluctuation(), lossFluctuationFlag, G4EmParameters::LowestElectronEnergy(), lowestKinEnergy, G4EmParameters::LowestMuHadEnergy(), massRatio, G4EmParameters::MaxEnergyForCSDARange(), G4EmParameters::MaxKinEnergy(), maxKinEnergy, maxKinEnergyCSDA, CLHEP::MeV, MeV, mfpKinEnergy, G4EmParameters::MinKinEnergy(), minKinEnergy, G4EmParameters::MinSubRange(), modelManager, n, nBins, nBinsCSDA, nSCoffRegions, G4EmParameters::NumberOfBinsPerDecade(), G4EmModelManager::NumberOfModels(), part, particle, Acts::UnitConstants::pm, pname(), G4PhysicsTableHelper::PreparePhysicsTable(), G4LossTableManager::PreparePhysicsTable(), preStepKinEnergy, preStepLambda, preStepLogKinEnergy, preStepRangeEnergy, r, reduceFactor, reg, G4PhysicsModelCatalog::Register(), G4LossTableManager::RegisterExtraParticle(), rndmStepFlag, scoffRegions, secID, secondaryParticle, G4VEmModel::SetAngularGeneratorFlag(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetMasterThread(), G4VProcess::SetVerboseLevel(), G4ProcessVector::size(), G4EmModelManager::SubCutoff(), G4LossTableManager::SubCutProducer(), subsecID, theCrossSectionMax, theCSDARangeTable, theCuts, theDEDXAtMaxEnergy, theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theEnergyOfCrossSectionMax, theGenericIon, theInverseRangeTable, theIonisationSubTable, theIonisationTable, theLambdaTable, theParameters, theRangeAtMaxEnergy, theRangeTableForLoss, theSubCuts, theSubLambdaTable, G4EmParameters::UseAngularGeneratorForIonisation(), G4EmParameters::UseCutAsFinalRange(), useSubCutoff, v, G4EmParameters::Verbose(), G4VProcess::verboseLevel, and G4EmParameters::WorkerVerbose().
virtual void G4VEnergyLossProcess::PrintInfo () inline virtual
Reimplemented in G4MuIonisation, G4hIonisation, G4MuBremsstrahlung, G4eIonisation, G4mplIonisation, G4ePolarizedIonisation, G4hhIonisation, and G4alphaIonisation.
Definition at line 102 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VEnergyLossProcess.hh
void G4VEnergyLossProcess::PrintWarning (G4String tit, G4double val) private
Definition at line 2361 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2361 of file G4VEnergyLossProcess.cc
References G4Exception(), G4VProcess::GetProcessName(), GeV, JustWarning, keV, maxKinEnergy, minKinEnergy, and nBins.
Referenced by SetDEDXBinning(), SetLinearLossLimit(), SetLowestEnergyLimit(), SetMaxKinEnergy(), SetMinKinEnergy(), and SetStepFunction().
void G4VEnergyLossProcess::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Reimplemented in G4MuIonisation, G4hIonisation, G4MuBremsstrahlung, G4eIonisation, G4ionIonisation, G4eBremsstrahlung, G4MuPairProduction, G4mplIonisation, G4hhIonisation, G4ePairProduction, G4hBremsstrahlung, G4alphaIonisation, and G4hPairProduction.
Definition at line 2375 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2375 of file G4VEnergyLossProcess.cc
References particle, and StreamInfo().
Referenced by G4hPairProduction::ProcessDescription(), G4alphaIonisation::ProcessDescription(), G4hBremsstrahlung::ProcessDescription(), G4ePairProduction::ProcessDescription(), G4hhIonisation::ProcessDescription(), G4mplIonisation::ProcessDescription(), G4MuPairProduction::ProcessDescription(), G4eBremsstrahlung::ProcessDescription(), G4ionIonisation::ProcessDescription(), G4eIonisation::ProcessDescription(), G4MuBremsstrahlung::ProcessDescription(), G4hIonisation::ProcessDescription(), and G4MuIonisation::ProcessDescription().
G4PhysicsTable * G4VEnergyLossProcess::RangeTableForLoss () const inline
Definition at line 1108 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1108 of file G4VEnergyLossProcess.hh
References theRangeTableForLoss.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), G4LossTableManager::LocalPhysicsTables(), and G4EmCalculator::PrintRangeTable().
G4bool G4VEnergyLossProcess::RetrievePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii) override virtual
Reimplemented from G4VProcess.
Definition at line 1765 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1765 of file G4VEnergyLossProcess.cc
References baseParticle, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), isMaster, nSCoffRegions, particle, RetrieveTable(), tablesAreBuilt, theCSDARangeTable, theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theInverseRangeTable, theIonisationSubTable, theLambdaTable, theRangeTableForLoss, theSubLambdaTable, and G4VProcess::verboseLevel.
G4bool G4VEnergyLossProcess::RetrieveTable (const G4ParticleDefinition * p, G4PhysicsTable * aTable, G4bool ascii, const G4String & directory, const G4String & tname, G4bool mandatory) private
Definition at line 1851 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1851 of file G4VEnergyLossProcess.cc
References G4PhysicsTable::ExistPhysicsTable(), INPUTHEPMC::filename, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetPhysicsTableFileName(), G4PhysicsTable::length(), n, G4PhysicsTableHelper::RetrievePhysicsTable(), G4EmParameters::Spline(), theParameters, and G4VProcess::verboseLevel.
Referenced by RetrievePhysicsTable().
G4double G4VEnergyLossProcess::SampleSubCutSecondaries (std::vector< G4Track * > & tracks, const G4Step & step, G4VEmModel * model, G4int matIdx)
Definition at line 1482 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1482 of file G4VEnergyLossProcess.cc
References chargeSqRatio, Acts::VectorHelpers::cross(), e, source.hepunit::electron_mass_c2, G4Log(), G4UniformRand, G4Track::GetDynamicParticle(), G4StepPoint::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4Track::GetParticleDefinition(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4Track::GetTouchableHandle(), G4Step::GetTrack(), incremental_prev_tag::idx, idxSubLambda, it, BTOF::length, massRatio, perMillion, r, G4VEmModel::SampleSecondaries(), secParticles, G4Track::SetCreatorModelIndex(), G4Track::SetTouchableHandle(), subsecID, t, thePositron, and track.
Referenced by AlongStepDoIt().
G4double G4VEnergyLossProcess::ScaledKinEnergyForLoss (G4double range) inline private
Definition at line 777 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 777 of file G4VEnergyLossProcess.hh
References basedCoupleIndex, e, G4PhysicsVector::Energy(), idxInverseRange, minKinEnergy, v, G4PhysicsVector::Value(), and x.
Referenced by AlongStepDoIt(), and GetKineticEnergy().
const G4ParticleDefinition * G4VEnergyLossProcess::SecondaryParticle () const inline
Definition at line 987 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 987 of file G4VEnergyLossProcess.hh
References secondaryParticle.
Referenced by G4LossTableManager::CopyTables().
G4PhysicsTable * G4VEnergyLossProcess::SecondaryRangeTable () const inline
Definition at line 1101 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1101 of file G4VEnergyLossProcess.hh
References theSecondaryRangeTable.
Referenced by BuildPhysicsTable().
void G4VEnergyLossProcess::SelectModel (G4double kinEnergy) inline protected
Definition at line 603 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 603 of file G4VEnergyLossProcess.hh
References currentCouple, currentCoupleIndex, currentModel, modelManager, G4EmModelManager::SelectModel(), and G4VEmModel::SetCurrentCouple().
Referenced by CrossSectionPerVolume(), GetDEDXDispersion(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4VEmModel * G4VEnergyLossProcess::SelectModelForMaterial (G4double kinEnergy, size_t & idx) const inline
Definition at line 611 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 611 of file G4VEnergyLossProcess.hh
References modelManager, and G4EmModelManager::SelectModel().
Referenced by G4EmCalculator::FindEmModel(), and G4ContinuousGainOfEnergy::GetContinuousStepLimit().
void G4VEnergyLossProcess::SetBaseParticle (const G4ParticleDefinition * p) inline
Definition at line 965 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 965 of file G4VEnergyLossProcess.hh
References baseParticle.
Referenced by G4alphaIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetCrossSectionBiasingFactor (G4double f, G4bool flag = true)
Definition at line 2221 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2221 of file G4VEnergyLossProcess.cc
References biasFactor, f, G4cout, G4endl, G4VProcess::GetProcessName(), G4VProcess::verboseLevel, and weightFlag.
Referenced by G4EmExtraParameters::DefineRegParamForLoss().
void G4VEnergyLossProcess::SetCSDARangeTable (G4PhysicsTable * pRange)
Definition at line 2076 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2076 of file G4VEnergyLossProcess.cc
References emax, idxCSDA, G4PhysicsTable::length(), maxKinEnergyCSDA, n, rmax(), theCSDARangeTable, theRangeAtMaxEnergy, and G4PhysicsVector::Value().
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::SetDEDXBinning (G4int nbins)
Definition at line 2327 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2327 of file G4VEnergyLossProcess.cc
References actBinning, e, n, nBins, and PrintWarning().
Referenced by G4MonopolePhysics::ConstructProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetDEDXTable (G4PhysicsTable * p, G4EmTableType tType)
Definition at line 2015 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2015 of file G4VEnergyLossProcess.cc
References emax, fIsIonisation, fIsSubIonisation, fRestricted, fSubRestricted, fTotal, G4LossTableBuilder::GetCoupleIndexes(), G4LossTableBuilder::GetDensityFactors(), G4LossTableManager::GetTableBuilder(), idxDEDXunRestricted, G4PhysicsTable::length(), lManager, maxKinEnergyCSDA, n, theDEDXAtMaxEnergy, theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theDensityFactor, theDensityIdx, theIonisationSubTable, theIonisationTable, and G4PhysicsVector::Value().
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::SetDynamicMassCharge (G4double massratio, G4double charge2ratio) inline
Definition at line 636 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 636 of file G4VEnergyLossProcess.hh
References biasFactor, chargeSqRatio, currentCoupleIndex, fFactor, G4Log(), logMassRatio, massRatio, and reduceFactor.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4ContinuousGainOfEnergy::SetDynamicMassCharge(), and G4EmCalculator::UpdateParticle().
void G4VEnergyLossProcess::SetEmModel (G4VEmModel * ptr, G4int index = 0)
Definition at line 333 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 333 of file G4VEnergyLossProcess.cc
References emModels.
Referenced by DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetFluctModel (G4VEmFluctuationModel * p) inline
Definition at line 935 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 935 of file G4VEnergyLossProcess.hh
References fluctModel.
Referenced by PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), and G4EmConfigurator::PrepareModels().
void G4VEnergyLossProcess::SetIntegral (G4bool val) inline
Definition at line 1002 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1002 of file G4VEnergyLossProcess.hh
References actIntegral, and integral.
void G4VEnergyLossProcess::SetInverseRangeTable (G4PhysicsTable * p)
Definition at line 2126 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2126 of file G4VEnergyLossProcess.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), particle, theInverseRangeTable, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::SetIonisation (G4bool val)
Definition at line 2284 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2284 of file G4VEnergyLossProcess.cc
References aGPILSelection, CandidateForSelection, isIonisation, and NotCandidateForSelection.
Referenced by G4LossTableManager::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4LossTableManager::CopyTables(), G4eBremsstrahlung::G4eBremsstrahlung(), G4ePairProduction::G4ePairProduction(), G4MuBremsstrahlung::G4MuBremsstrahlung(), G4MuPairProduction::G4MuPairProduction(), and G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetLambdaTable (G4PhysicsTable * p)
Definition at line 2138 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2138 of file G4VEnergyLossProcess.cc
References DBL_MAX, e, emax, G4PhysicsVector::Energy(), G4cout, G4endl, G4LossTableBuilder::GetCoupleIndexes(), G4LossTableBuilder::GetDensityFactors(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4LossTableManager::GetTableBuilder(), G4PhysicsVector::GetVectorLength(), G4PhysicsTable::length(), lManager, MeV, n, particle, smax, tablesAreBuilt, theCrossSectionMax, theDensityFactor, theDensityIdx, theEnergyOfCrossSectionMax, theLambdaTable, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::SetLinearLossLimit (G4double val)
Definition at line 2292 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2292 of file G4VEnergyLossProcess.cc
References actLinLossLimit, linLossLimit, and PrintWarning().
Referenced by G4alphaIonisation::G4alphaIonisation(), and G4ionIonisation::G4ionIonisation().
void G4VEnergyLossProcess::SetLossFluctuations (G4bool val) inline
Definition at line 994 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 994 of file G4VEnergyLossProcess.hh
References actLossFluc, and lossFluctuationFlag.
Referenced by G4AdjointPhysicsList::ConstructEM(), and G4AdjointPhysicsList::SetLossFluctuationFlag().
void G4VEnergyLossProcess::SetLowestEnergyLimit (G4double val)
Definition at line 2319 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2319 of file G4VEnergyLossProcess.cc
References e, lowestKinEnergy, and PrintWarning().
void G4VEnergyLossProcess::SetMaxKinEnergy (G4double e)
Definition at line 2350 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2350 of file G4VEnergyLossProcess.cc
References actMaxKinEnergy, e, maxKinEnergy, maxKinEnergyCSDA, minKinEnergy, and PrintWarning().
Referenced by G4MonopolePhysics::ConstructProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetMinKinEnergy (G4double e)
Definition at line 2340 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2340 of file G4VEnergyLossProcess.cc
References actMinKinEnergy, e, maxKinEnergy, minKinEnergy, and PrintWarning().
Referenced by G4MonopolePhysics::ConstructProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), and G4hIonisation::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetParticle (const G4ParticleDefinition * p) inline protected
Definition at line 949 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 949 of file G4VEnergyLossProcess.hh
References particle.
void G4VEnergyLossProcess::SetRangeTableForLoss (G4PhysicsTable * p)
Definition at line 2102 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2102 of file G4VEnergyLossProcess.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), particle, theRangeTableForLoss, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::SetSecondaryParticle (const G4ParticleDefinition * p) inline protected
Definition at line 957 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 957 of file G4VEnergyLossProcess.hh
References secondaryParticle.
Referenced by G4eBremsstrahlung::G4eBremsstrahlung(), G4eIonisation::G4eIonisation(), G4ePairProduction::G4ePairProduction(), G4ePolarizedIonisation::G4ePolarizedIonisation(), G4hhIonisation::G4hhIonisation(), G4hIonisation::G4hIonisation(), G4ionIonisation::G4ionIonisation(), G4mplIonisation::G4mplIonisation(), G4MuBremsstrahlung::G4MuBremsstrahlung(), G4MuIonisation::G4MuIonisation(), G4MuPairProduction::G4MuPairProduction(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), and G4alphaIonisation::InitialiseEnergyLossProcess().
void G4VEnergyLossProcess::SetSecondaryRangeTable (G4PhysicsTable * p)
Definition at line 2114 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2114 of file G4VEnergyLossProcess.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), particle, theSecondaryRangeTable, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::SetStepFunction (G4double v1, G4double v2, G4bool lock = true)
Definition at line 2303 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2303 of file G4VEnergyLossProcess.cc
References actStepFunc, dRoverRange, e, finalRange, min, PrintWarning(), and v2.
Referenced by DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4EmExtraParameters::DefineRegParamForLoss(), G4hhIonisation::G4hhIonisation(), and G4mplIonisation::G4mplIonisation().
void G4VEnergyLossProcess::SetSubLambdaTable (G4PhysicsTable * p)
Definition at line 2200 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 2200 of file G4VEnergyLossProcess.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), particle, theSubLambdaTable, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), G4LossTableManager::BuildTables(), and G4LossTableManager::CopyTables().
void G4VEnergyLossProcess::StartTracking (G4Track * track) override virtual
Reimplemented from G4VProcess.
Definition at line 984 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 984 of file G4VEnergyLossProcess.cc
References baseParticle, biasFlag, biasManager, chargeSqRatio, G4VProcess::currentInteractionLength, DBL_MAX, G4Log(), G4Track::GetDefinition(), G4Track::GetParentID(), G4ParticleDefinition::GetPDGMass(), isIon, logMassRatio, massRatio, mfpKinEnergy, preStepRangeEnergy, source.hepunit::proton_mass_c2, G4EmBiasingManager::ResetForcedInteraction(), theGenericIon, and G4VProcess::theNumberOfInteractionLengthLeft.
G4bool G4VEnergyLossProcess::StorePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii = false) override virtual
Reimplemented from G4VProcess.
Definition at line 1702 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1702 of file G4VEnergyLossProcess.cc
References baseParticle, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), isIonisation, isMaster, particle, StoreTable(), theCSDARangeTable, theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theInverseRangeTable, theIonisationSubTable, theIonisationTable, theLambdaTable, theRangeTableForLoss, theSubLambdaTable, and G4VProcess::verboseLevel.
G4bool G4VEnergyLossProcess::StoreTable (const G4ParticleDefinition * p, G4PhysicsTable * aTable, G4bool ascii, const G4String & directory, const G4String & tname) private
Definition at line 1831 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 1831 of file G4VEnergyLossProcess.cc
References G4cout, G4endl, G4VProcess::GetPhysicsTableFileName(), and G4PhysicsTable::StorePhysicsTable().
Referenced by StorePhysicsTable().
void G4VEnergyLossProcess::StreamInfo (std::ostream & out, const G4ParticleDefinition & part, G4bool rst = false) const private
Definition at line 884 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 884 of file G4VEnergyLossProcess.cc
References dRoverRange, G4EmModelManager::DumpModelList(), finalRange, G4BestUnit, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), integral, isIonisation, linLossLimit, lossFluctuationFlag, maxKinEnergy, maxKinEnergyCSDA, minKinEnergy, mm, modelManager, nBins, nBinsCSDA, nSCoffRegions, G4EmParameters::NumberOfBinsPerDecade(), G4EmParameters::Spline(), StreamProcessInfo(), theCSDARangeTable, theDEDXSubTable, theDEDXTable, theDEDXunRestrictedTable, theInverseRangeTable, theLambdaTable, theParameters, theRangeTableForLoss, theSubLambdaTable, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), and ProcessDescription().
virtual void G4VEnergyLossProcess::StreamProcessInfo (std::ostream &) const inline protected virtual
Reimplemented in G4ionIonisation, G4eBremsstrahlung, G4MuPairProduction, and G4ePairProduction.
Definition at line 108 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VEnergyLossProcess.hh
Referenced by StreamInfo().
G4PhysicsTable * G4VEnergyLossProcess::SubLambdaTable () const inline
Definition at line 1129 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1129 of file G4VEnergyLossProcess.hh
References theSubLambdaTable.
Referenced by BuildPhysicsTable(), and G4LossTableManager::CopyTables().
G4bool G4VEnergyLossProcess::TablesAreBuilt () const inline
Definition at line 1052 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 1052 of file G4VEnergyLossProcess.hh
References tablesAreBuilt.
void G4VEnergyLossProcess::UpdateEmModel (const G4String & nam, G4double emin, G4double emax)
Definition at line 325 of file G4VEnergyLossProcess.cc.
View newest version in sPHENIX GitHub at line 325 of file G4VEnergyLossProcess.cc
References modelManager, and G4EmModelManager::UpdateEmModel().
Member Data Documentation
G4bool G4VEnergyLossProcess::actBinning private
Definition at line 547 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 547 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetDEDXBinning().
G4bool G4VEnergyLossProcess::actIntegral private
Definition at line 543 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 543 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetIntegral().
G4bool G4VEnergyLossProcess::actLinLossLimit private
Definition at line 545 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 545 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetLinearLossLimit().
G4bool G4VEnergyLossProcess::actLossFluc private
Definition at line 546 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 546 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetLossFluctuations().
G4bool G4VEnergyLossProcess::actMaxKinEnergy private
Definition at line 549 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 549 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetMaxKinEnergy().
G4bool G4VEnergyLossProcess::actMinKinEnergy private
Definition at line 548 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 548 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SetMinKinEnergy().
G4bool G4VEnergyLossProcess::actStepFunc private
Definition at line 544 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 544 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), and SetStepFunction().
G4GPILSelection G4VEnergyLossProcess::aGPILSelection private
Definition at line 587 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 587 of file G4VEnergyLossProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), and SetIonisation().
G4VAtomDeexcitation* G4VEnergyLossProcess::atomDeexcitation private
Definition at line 470 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 470 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), BuildPhysicsTable(), and G4VEnergyLossProcess().
size_t G4VEnergyLossProcess::basedCoupleIndex private
Definition at line 578 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 578 of file G4VEnergyLossProcess.hh
Referenced by DefineMaterial(), G4VEnergyLossProcess(), GetDEDXForScaledEnergy(), GetIonisationForScaledEnergy(), GetLambdaForScaledEnergy(), GetLimitScaledRangeForScaledEnergy(), GetScaledRangeForScaledEnergy(), GetSubDEDXForScaledEnergy(), GetSubIonisationForScaledEnergy(), and ScaledKinEnergyForLoss().
const G4ParticleDefinition* G4VEnergyLossProcess::baseParticle private
Definition at line 515 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 515 of file G4VEnergyLossProcess.hh
Referenced by BaseParticle(), BuildPhysicsTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetBaseParticle(), StartTracking(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
G4double G4VEnergyLossProcess::biasFactor private
Definition at line 530 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 530 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), CrossSectionBiasingFactor(), CrossSectionPerVolume(), DefineMaterial(), G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), SetCrossSectionBiasingFactor(), and SetDynamicMassCharge().
G4bool G4VEnergyLossProcess::biasFlag private
Definition at line 540 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 540 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
G4int G4VEnergyLossProcess::biasID private
Definition at line 591 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 591 of file G4VEnergyLossProcess.hh
Referenced by FillSecondariesAlongStep(), G4VEnergyLossProcess(), PostStepDoIt(), and PreparePhysicsTable().
G4EmBiasingManager* G4VEnergyLossProcess::biasManager private
Definition at line 456 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 456 of file G4VEnergyLossProcess.hh
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), FillSecondariesAlongStep(), G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), StartTracking(), and ~G4VEnergyLossProcess().
G4double G4VEnergyLossProcess::chargeSqRatio private
Definition at line 585 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 585 of file G4VEnergyLossProcess.hh
Referenced by DefineMaterial(), G4VEnergyLossProcess(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SampleSubCutSecondaries(), SetDynamicMassCharge(), and StartTracking().
G4double G4VEnergyLossProcess::computedRange protected
Definition at line 560 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 560 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), and GetScaledRangeForScaledEnergy().
const G4MaterialCutsCouple* G4VEnergyLossProcess::currentCouple protected
Definition at line 555 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 555 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), DefineMaterial(), PostStepDoIt(), PreparePhysicsTable(), and SelectModel().
size_t G4VEnergyLossProcess::currentCoupleIndex protected
Definition at line 556 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 556 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), ComputeLambdaForScaledEnergy(), CrossSectionPerVolume(), CurrentMaterialCutsCoupleIndex(), DefineMaterial(), FillSecondariesAlongStep(), G4VEnergyLossProcess(), GetDEDXDispersion(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), SelectModel(), and SetDynamicMassCharge().
const G4Material* G4VEnergyLossProcess::currentMaterial protected
Definition at line 554 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 554 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), CrossSectionPerVolume(), DefineMaterial(), G4VEnergyLossProcess(), GetDEDXDispersion(), and PostStepGetPhysicalInteractionLength().
G4VEmModel* G4VEnergyLossProcess::currentModel private
Definition at line 577 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 577 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), CrossSectionPerVolume(), G4VEnergyLossProcess(), GetCurrentElement(), GetDEDXDispersion(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and SelectModel().
G4double G4VEnergyLossProcess::dRoverRange private
Definition at line 526 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 526 of file G4VEnergyLossProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), SetStepFunction(), and StreamInfo().
std::vector<G4VEmModel*> G4VEnergyLossProcess::emModels private
Definition at line 468 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 468 of file G4VEnergyLossProcess.hh
Referenced by EmModel(), and SetEmModel().
G4double G4VEnergyLossProcess::fFactor private
Definition at line 583 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 583 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), DefineMaterial(), G4VEnergyLossProcess(), GetDEDXForScaledEnergy(), GetIonisationForScaledEnergy(), GetLambdaForScaledEnergy(), GetSubDEDXForScaledEnergy(), GetSubIonisationForScaledEnergy(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and SetDynamicMassCharge().
G4double G4VEnergyLossProcess::finalRange private
Definition at line 527 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 527 of file G4VEnergyLossProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), SetStepFunction(), and StreamInfo().
G4VEmFluctuationModel* G4VEnergyLossProcess::fluctModel private
Definition at line 469 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 469 of file G4VEnergyLossProcess.hh
Referenced by FluctModel(), G4VEnergyLossProcess(), and SetFluctModel().
G4ParticleChangeForLoss G4VEnergyLossProcess::fParticleChange protected
Definition at line 553 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 553 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), FillSecondariesAlongStep(), G4VEnergyLossProcess(), and PostStepDoIt().
G4double G4VEnergyLossProcess::fRange protected
Definition at line 559 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 559 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), GetRange(), and PreparePhysicsTable().
size_t G4VEnergyLossProcess::idxCSDA private
Definition at line 498 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 498 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), GetLimitScaledRangeForScaledEnergy(), and SetCSDARangeTable().
size_t G4VEnergyLossProcess::idxDEDX private
Definition at line 492 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 492 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and GetDEDXForScaledEnergy().
size_t G4VEnergyLossProcess::idxDEDXSub private
Definition at line 493 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 493 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and GetSubDEDXForScaledEnergy().
size_t G4VEnergyLossProcess::idxDEDXunRestricted private
Definition at line 494 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 494 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and SetDEDXTable().
size_t G4VEnergyLossProcess::idxInverseRange private
Definition at line 500 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 500 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and ScaledKinEnergyForLoss().
size_t G4VEnergyLossProcess::idxIonisation private
Definition at line 495 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 495 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and GetIonisationForScaledEnergy().
size_t G4VEnergyLossProcess::idxIonisationSub private
Definition at line 496 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 496 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and GetSubIonisationForScaledEnergy().
size_t G4VEnergyLossProcess::idxLambda private
Definition at line 501 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 501 of file G4VEnergyLossProcess.hh
Referenced by Clean(), DefineMaterial(), G4VEnergyLossProcess(), and GetLambdaForScaledEnergy().
size_t G4VEnergyLossProcess::idxRange private
Definition at line 497 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 497 of file G4VEnergyLossProcess.hh
Referenced by Clean(), G4VEnergyLossProcess(), and GetScaledRangeForScaledEnergy().
G4bool* G4VEnergyLossProcess::idxSCoffRegions private
Definition at line 474 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 474 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), Clean(), and PreparePhysicsTable().
size_t G4VEnergyLossProcess::idxSecRange private
Definition at line 499 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 499 of file G4VEnergyLossProcess.hh
Referenced by Clean(), and G4VEnergyLossProcess().
size_t G4VEnergyLossProcess::idxSubLambda private
Definition at line 502 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 502 of file G4VEnergyLossProcess.hh
Referenced by Clean(), DefineMaterial(), G4VEnergyLossProcess(), and SampleSubCutSecondaries().
G4bool G4VEnergyLossProcess::integral private
Definition at line 535 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 535 of file G4VEnergyLossProcess.hh
Referenced by IsIntegral(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SetIntegral(), and StreamInfo().
G4bool G4VEnergyLossProcess::isIon private
Definition at line 536 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 536 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), BuildPhysicsTable(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
G4bool G4VEnergyLossProcess::isIonisation private
Definition at line 537 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 537 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), BuildPhysicsTable(), IsIonisationProcess(), PreparePhysicsTable(), SetIonisation(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
G4bool G4VEnergyLossProcess::isMaster private
Definition at line 542 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 542 of file G4VEnergyLossProcess.hh
Referenced by BuildPhysicsTable(), G4VEnergyLossProcess(), PreparePhysicsTable(), RetrievePhysicsTable(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
G4double G4VEnergyLossProcess::lambdaFactor private
Definition at line 528 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 528 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), G4VEnergyLossProcess(), and PreparePhysicsTable().
size_t G4VEnergyLossProcess::lastIdx private
Definition at line 579 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 579 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), GetScaledRangeForScaledEnergy(), and PreparePhysicsTable().
G4double G4VEnergyLossProcess::linLossLimit private
Definition at line 525 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 525 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), G4VEnergyLossProcess(), PreparePhysicsTable(), SetLinearLossLimit(), and StreamInfo().
G4LossTableManager* G4VEnergyLossProcess::lManager private
Definition at line 454 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 454 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), BuildLambdaTable(), BuildPhysicsTable(), G4VEnergyLossProcess(), PreparePhysicsTable(), SetDEDXTable(), SetLambdaTable(), and ~G4VEnergyLossProcess().
G4double G4VEnergyLossProcess::logLambdafactor private
Definition at line 529 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 529 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), G4VEnergyLossProcess(), and PreparePhysicsTable().
G4double G4VEnergyLossProcess::logMassRatio private
Definition at line 582 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 582 of file G4VEnergyLossProcess.hh
Referenced by CrossSectionPerVolume(), G4VEnergyLossProcess(), GetDEDX(), GetLambda(), GetRange(), GetRangeForLoss(), MeanFreePath(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SetDynamicMassCharge(), and StartTracking().
G4bool G4VEnergyLossProcess::lossFluctuationFlag private
Definition at line 532 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 532 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), PreparePhysicsTable(), SetLossFluctuations(), and StreamInfo().
G4double G4VEnergyLossProcess::lowestKinEnergy private
Definition at line 520 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 520 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), G4VEnergyLossProcess(), PostStepDoIt(), PreparePhysicsTable(), and SetLowestEnergyLimit().
G4double G4VEnergyLossProcess::massRatio private
Definition at line 581 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 581 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), CrossSectionPerVolume(), DefineMaterial(), G4VEnergyLossProcess(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetDEDXForSubsec(), GetKineticEnergy(), GetLambda(), GetRange(), GetRangeForLoss(), MeanFreePath(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), SampleSubCutSecondaries(), SetDynamicMassCharge(), and StartTracking().
G4double G4VEnergyLossProcess::maxKinEnergy private
Definition at line 522 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 522 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), LambdaPhysicsVector(), MaxKinEnergy(), PreparePhysicsTable(), PrintWarning(), SetMaxKinEnergy(), SetMinKinEnergy(), and StreamInfo().
G4double G4VEnergyLossProcess::maxKinEnergyCSDA private
Definition at line 523 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 523 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), G4VEnergyLossProcess(), GetLimitScaledRangeForScaledEnergy(), PreparePhysicsTable(), SetCSDARangeTable(), SetDEDXTable(), SetMaxKinEnergy(), and StreamInfo().
G4double G4VEnergyLossProcess::mfpKinEnergy protected
Definition at line 566 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 566 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), DefineMaterial(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
G4double G4VEnergyLossProcess::minKinEnergy private
Definition at line 521 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 521 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), GetDEDXForScaledEnergy(), GetIonisationForScaledEnergy(), GetLimitScaledRangeForScaledEnergy(), GetScaledRangeForScaledEnergy(), GetSubDEDXForScaledEnergy(), GetSubIonisationForScaledEnergy(), LambdaPhysicsVector(), MinKinEnergy(), PreparePhysicsTable(), PrintWarning(), ScaledKinEnergyForLoss(), SetMaxKinEnergy(), SetMinKinEnergy(), and StreamInfo().
G4EmModelManager* G4VEnergyLossProcess::modelManager private
Definition at line 455 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 455 of file G4VEnergyLossProcess.hh
Referenced by AddEmModel(), BuildDEDXTable(), BuildLambdaTable(), BuildPhysicsTable(), G4VEnergyLossProcess(), GetModelByIndex(), NumberOfModels(), PreparePhysicsTable(), SelectModel(), SelectModelForMaterial(), StreamInfo(), UpdateEmModel(), and ~G4VEnergyLossProcess().
G4int G4VEnergyLossProcess::nBins private
Definition at line 517 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 517 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), LambdaPhysicsVector(), PreparePhysicsTable(), PrintWarning(), SetDEDXBinning(), and StreamInfo().
G4int G4VEnergyLossProcess::nBinsCSDA private
Definition at line 518 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 518 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), G4VEnergyLossProcess(), PreparePhysicsTable(), and StreamInfo().
G4int G4VEnergyLossProcess::nProcesses private
Definition at line 477 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 477 of file G4VEnergyLossProcess.hh
Referenced by AddCollaborativeProcess(), and Clean().
G4int G4VEnergyLossProcess::nSCoffRegions private
Definition at line 473 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 473 of file G4VEnergyLossProcess.hh
Referenced by ActivateSubCutoff(), BuildPhysicsTable(), NumberOfSubCutoffRegions(), PreparePhysicsTable(), RetrievePhysicsTable(), and StreamInfo().
const G4ParticleDefinition* G4VEnergyLossProcess::particle private
Definition at line 575 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 575 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), BuildLambdaTable(), BuildPhysicsTable(), CrossSectionPerVolume(), Particle(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), SetInverseRangeTable(), SetLambdaTable(), SetParticle(), SetRangeTableForLoss(), SetSecondaryRangeTable(), SetSubLambdaTable(), and StorePhysicsTable().
G4double G4VEnergyLossProcess::preStepKinEnergy protected
Definition at line 561 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 561 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), G4VEnergyLossProcess(), PostStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
G4double G4VEnergyLossProcess::preStepLambda protected
Definition at line 558 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 558 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), G4VEnergyLossProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
G4double G4VEnergyLossProcess::preStepLogKinEnergy protected
Definition at line 562 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 562 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PostStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
G4double G4VEnergyLossProcess::preStepLogScaledEnergy protected
Definition at line 564 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 564 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), and PostStepGetPhysicalInteractionLength().
G4double G4VEnergyLossProcess::preStepRangeEnergy protected
Definition at line 565 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 565 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), GetScaledRangeForScaledEnergy(), PreparePhysicsTable(), and StartTracking().
G4double G4VEnergyLossProcess::preStepScaledEnergy protected
Definition at line 563 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 563 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4VEnergyLossProcess(), and PostStepGetPhysicalInteractionLength().
G4double G4VEnergyLossProcess::reduceFactor private
Definition at line 584 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 584 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), DefineMaterial(), G4VEnergyLossProcess(), GetCSDARange(), GetKineticEnergy(), GetRange(), GetRangeForLoss(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and SetDynamicMassCharge().
G4bool G4VEnergyLossProcess::rndmStepFlag private
Definition at line 533 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 533 of file G4VEnergyLossProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and PreparePhysicsTable().
G4SafetyHelper* G4VEnergyLossProcess::safetyHelper private
Definition at line 457 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 457 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), BuildPhysicsTable(), and G4VEnergyLossProcess().
std::vector<const G4Region*> G4VEnergyLossProcess::scoffRegions private
Definition at line 472 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 472 of file G4VEnergyLossProcess.hh
Referenced by ActivateSubCutoff(), and PreparePhysicsTable().
std::vector<G4VEnergyLossProcess*> G4VEnergyLossProcess::scProcesses private
Definition at line 476 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 476 of file G4VEnergyLossProcess.hh
Referenced by AddCollaborativeProcess(), and Clean().
std::vector<G4Track*> G4VEnergyLossProcess::scTracks private
Definition at line 573 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 573 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), FillSecondariesAlongStep(), and G4VEnergyLossProcess().
G4int G4VEnergyLossProcess::secID private
Definition at line 589 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 589 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PostStepDoIt(), and PreparePhysicsTable().
const G4ParticleDefinition* G4VEnergyLossProcess::secondaryParticle private
Definition at line 460 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 460 of file G4VEnergyLossProcess.hh
Referenced by ActivateSecondaryBiasing(), PreparePhysicsTable(), SecondaryParticle(), and SetSecondaryParticle().
std::vector<G4DynamicParticle*> G4VEnergyLossProcess::secParticles private
Definition at line 572 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 572 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PostStepDoIt(), and SampleSubCutSecondaries().
G4VSubCutProducer* G4VEnergyLossProcess::subcutProducer private
Definition at line 471 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 471 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), BuildPhysicsTable(), and G4VEnergyLossProcess().
G4int G4VEnergyLossProcess::subsecID private
Definition at line 590 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 590 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and SampleSubCutSecondaries().
G4bool G4VEnergyLossProcess::tablesAreBuilt private
Definition at line 534 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 534 of file G4VEnergyLossProcess.hh
Referenced by BuildPhysicsTable(), Clean(), RetrievePhysicsTable(), SetLambdaTable(), and TablesAreBuilt().
std::vector<G4double> G4VEnergyLossProcess::theCrossSectionMax private
Definition at line 507 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 507 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), PreparePhysicsTable(), and SetLambdaTable().
G4PhysicsTable* G4VEnergyLossProcess::theCSDARangeTable private
Definition at line 486 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 486 of file G4VEnergyLossProcess.hh
Referenced by CSDARangeTable(), GetCSDARange(), GetRange(), PreparePhysicsTable(), RetrievePhysicsTable(), SetCSDARangeTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
const G4DataVector* G4VEnergyLossProcess::theCuts private
Definition at line 512 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 512 of file G4VEnergyLossProcess.hh
Referenced by CrossSectionPerVolume(), G4VEnergyLossProcess(), GetDEDXDispersion(), and PreparePhysicsTable().
std::vector<G4double> G4VEnergyLossProcess::theDEDXAtMaxEnergy private
Definition at line 504 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 504 of file G4VEnergyLossProcess.hh
Referenced by GetLimitScaledRangeForScaledEnergy(), PreparePhysicsTable(), and SetDEDXTable().
G4PhysicsTable* G4VEnergyLossProcess::theDEDXSubTable private
Definition at line 481 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 481 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), DEDXTableForSubsec(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
G4PhysicsTable* G4VEnergyLossProcess::theDEDXTable private
Definition at line 480 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 480 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), DEDXTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
G4PhysicsTable* G4VEnergyLossProcess::theDEDXunRestrictedTable private
Definition at line 482 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 482 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), DEDXunRestrictedTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
const std::vector<G4double>* G4VEnergyLossProcess::theDensityFactor private
Definition at line 509 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 509 of file G4VEnergyLossProcess.hh
Referenced by BuildLambdaTable(), G4VEnergyLossProcess(), SetDEDXTable(), and SetLambdaTable().
const std::vector<G4int>* G4VEnergyLossProcess::theDensityIdx private
Definition at line 510 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 510 of file G4VEnergyLossProcess.hh
Referenced by BuildLambdaTable(), G4VEnergyLossProcess(), SetDEDXTable(), and SetLambdaTable().
const G4ParticleDefinition* G4VEnergyLossProcess::theElectron private
Definition at line 461 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 461 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess().
std::vector<G4double> G4VEnergyLossProcess::theEnergyOfCrossSectionMax private
Definition at line 506 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 506 of file G4VEnergyLossProcess.hh
Referenced by ComputeLambdaForScaledEnergy(), PreparePhysicsTable(), and SetLambdaTable().
const G4ParticleDefinition* G4VEnergyLossProcess::theGamma private
Definition at line 463 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 463 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess().
const G4ParticleDefinition* G4VEnergyLossProcess::theGenericIon private
Definition at line 464 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 464 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), PreparePhysicsTable(), and StartTracking().
G4PhysicsTable* G4VEnergyLossProcess::theInverseRangeTable private
Definition at line 488 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 488 of file G4VEnergyLossProcess.hh
Referenced by InverseRangeTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetInverseRangeTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
G4PhysicsTable* G4VEnergyLossProcess::theIonisationSubTable private
Definition at line 484 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 484 of file G4VEnergyLossProcess.hh
Referenced by IonisationTableForSubsec(), PreparePhysicsTable(), RetrievePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
G4PhysicsTable* G4VEnergyLossProcess::theIonisationTable private
Definition at line 483 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 483 of file G4VEnergyLossProcess.hh
Referenced by IonisationTable(), PreparePhysicsTable(), SetDEDXTable(), StorePhysicsTable(), and ~G4VEnergyLossProcess().
G4PhysicsTable* G4VEnergyLossProcess::theLambdaTable private
Definition at line 489 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 489 of file G4VEnergyLossProcess.hh
Referenced by BuildLambdaTable(), CrossSectionPerVolume(), GetLambda(), LambdaTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetLambdaTable(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
G4EmParameters* G4VEnergyLossProcess::theParameters private
Definition at line 458 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 458 of file G4VEnergyLossProcess.hh
Referenced by BuildDEDXTable(), BuildLambdaTable(), G4VEnergyLossProcess(), LambdaPhysicsVector(), PreparePhysicsTable(), RetrieveTable(), and StreamInfo().
const G4ParticleDefinition* G4VEnergyLossProcess::thePositron private
Definition at line 462 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 462 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), and SampleSubCutSecondaries().
std::vector<G4double> G4VEnergyLossProcess::theRangeAtMaxEnergy private
Definition at line 505 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 505 of file G4VEnergyLossProcess.hh
Referenced by GetLimitScaledRangeForScaledEnergy(), PreparePhysicsTable(), and SetCSDARangeTable().
G4PhysicsTable* G4VEnergyLossProcess::theRangeTableForLoss private
Definition at line 485 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 485 of file G4VEnergyLossProcess.hh
Referenced by GetRange(), PreparePhysicsTable(), RangeTableForLoss(), RetrievePhysicsTable(), SetRangeTableForLoss(), StorePhysicsTable(), StreamInfo(), and ~G4VEnergyLossProcess().
G4PhysicsTable* G4VEnergyLossProcess::theSecondaryRangeTable private
Definition at line 487 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 487 of file G4VEnergyLossProcess.hh
Referenced by SecondaryRangeTable(), and SetSecondaryRangeTable().
const G4DataVector* G4VEnergyLossProcess::theSubCuts private
Definition at line 513 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 513 of file G4VEnergyLossProcess.hh
Referenced by G4VEnergyLossProcess(), and PreparePhysicsTable().
G4PhysicsTable* G4VEnergyLossProcess::theSubLambdaTable private
Definition at line 490 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 490 of file G4VEnergyLossProcess.hh
Referenced by BuildLambdaTable(), PreparePhysicsTable(), RetrievePhysicsTable(), SetSubLambdaTable(), StorePhysicsTable(), StreamInfo(), SubLambdaTable(), and ~G4VEnergyLossProcess().
G4bool G4VEnergyLossProcess::useDeexcitation private
Definition at line 539 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 539 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), and BuildPhysicsTable().
G4bool G4VEnergyLossProcess::useSubCutoff private
Definition at line 538 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 538 of file G4VEnergyLossProcess.hh
Referenced by AlongStepDoIt(), and PreparePhysicsTable().
G4bool G4VEnergyLossProcess::weightFlag private
Definition at line 541 of file G4VEnergyLossProcess.hh.
View newest version in sPHENIX GitHub at line 541 of file G4VEnergyLossProcess.hh
Referenced by ActivateForcedInteraction(), AlongStepDoIt(), G4VEnergyLossProcess(), PostStepDoIt(), and SetCrossSectionBiasingFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEnergyLossProcess.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4VEnergyLossProcess.cc