ECCE @ EIC Software: G4StatMFMacroCanonical Class Reference
G4StatMFMacroCanonical Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroCanonical.hh>
Classes
struct DeleteFragment
Public Member Functions
G4StatMFMacroCanonical (G4Fragment const &theFragment)
~G4StatMFMacroCanonical ()
G4StatMFChannel * ChooseAandZ (const G4Fragment &theFragment)
Public Member Functions inherited from G4VStatMFEnsemble
G4VStatMFEnsemble ()
virtual ~G4VStatMFEnsemble ()
G4double GetMeanMultiplicity (void) const
G4double GetMeanTemperature (void) const
Private Member Functions
G4StatMFMacroCanonical ()
G4StatMFMacroCanonical (const G4StatMFMacroCanonical &)
G4StatMFMacroCanonical & operator= (const G4StatMFMacroCanonical &right)
G4bool operator== (const G4StatMFMacroCanonical &right) const
G4bool operator!= (const G4StatMFMacroCanonical &right) const
void Initialize (const G4Fragment &theFragment)
void CalculateTemperature (const G4Fragment &theFragment)
G4double ChooseA (G4int A, std::vector< G4int > &ANumbers)
G4StatMFChannel * ChooseZ (G4int &Z, std::vector< G4int > &FragmentsA)
Private Attributes
G4double _ChemPotentialMu
G4double _ChemPotentialNu
G4double _Kappa
std::vector
< G4VStatMFMacroCluster * > _theClusters
Additional Inherited Members
Protected Attributes inherited from G4VStatMFEnsemble
G4double __FreeInternalE0
G4double __MeanTemperature
G4double __MeanEntropy
G4double __MeanMultiplicity
Detailed Description
Definition at line 49 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 49 of file G4StatMFMacroCanonical.hh
Constructor & Destructor Documentation
G4StatMFMacroCanonical::G4StatMFMacroCanonical (G4Fragment const & theFragment)
Definition at line 43 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 43 of file G4StatMFMacroCanonical.cc
References _theClusters, G4Fragment::GetA_asInt(), and Initialize().
G4StatMFMacroCanonical::~G4StatMFMacroCanonical ()
Definition at line 60 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 60 of file G4StatMFMacroCanonical.cc
References _theClusters.
G4StatMFMacroCanonical::G4StatMFMacroCanonical () inline private
Definition at line 61 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 61 of file G4StatMFMacroCanonical.hh
G4StatMFMacroCanonical::G4StatMFMacroCanonical (const G4StatMFMacroCanonical &) inline private
Definition at line 65 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 65 of file G4StatMFMacroCanonical.hh
Member Function Documentation
void G4StatMFMacroCanonical::CalculateTemperature (const G4Fragment & theFragment) private
Definition at line 89 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 89 of file G4StatMFMacroCanonical.cc
References G4VStatMFEnsemble::__FreeInternalE0, G4VStatMFEnsemble::__MeanEntropy, G4VStatMFEnsemble::__MeanMultiplicity, G4VStatMFEnsemble::__MeanTemperature, _ChemPotentialMu, _ChemPotentialNu, _Kappa, _theClusters, A(), G4Pow::A13(), G4StatMFMacroTemperature::CalcTemperature(), source.hepunit::elm_coupling, G4Fragment::GetA_asInt(), G4StatMFMacroTemperature::GetChemicalPotentialMu(), G4StatMFMacroTemperature::GetChemicalPotentialNu(), G4StatMFMacroTemperature::GetEntropy(), G4Fragment::GetExcitationEnergy(), G4Pow::GetInstance(), G4StatMFMacroTemperature::GetMeanMultiplicity(), G4StatMFParameters::Getr0(), G4Fragment::GetZ_asInt(), max, MeV, Z, and G4Pow::Z13().
Referenced by Initialize().
G4double G4StatMFMacroCanonical::ChooseA (G4int A, std::vector< G4int > & ANumbers) private
Definition at line 164 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 164 of file G4StatMFMacroCanonical.cc
References G4VStatMFEnsemble::__MeanMultiplicity, _theClusters, A(), kdfinder::abs(), G4UniformRand, and it.
Referenced by ChooseAandZ().
G4StatMFChannel * G4StatMFMacroCanonical::ChooseAandZ (const G4Fragment & theFragment) virtual
Implements G4VStatMFEnsemble.
Definition at line 122 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 122 of file G4StatMFMacroCanonical.cc
References A(), ChooseA(), ChooseZ(), G4Fragment::GetA_asInt(), G4Fragment::GetZ_asInt(), and Z.
Referenced by G4StatMF::BreakItUp().
G4StatMFChannel * G4StatMFMacroCanonical::ChooseZ (G4int & Z, std::vector< G4int > & FragmentsA) private
Definition at line 209 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 209 of file G4StatMFMacroCanonical.cc
References G4VStatMFEnsemble::__MeanTemperature, _ChemPotentialNu, _theClusters, A(), kdfinder::abs(), G4StatMFChannel::CreateFragment(), G4lrint(), G4UniformRand, G4StatMFParameters::GetCoulomb(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), incremental_prev_tag::idx, G4INCL::DeJongSpin::shoot(), z, and G4Pow::Z23().
Referenced by ChooseAandZ().
void G4StatMFMacroCanonical::Initialize (const G4Fragment & theFragment) private
Definition at line 70 of file G4StatMFMacroCanonical.cc.
View newest version in sPHENIX GitHub at line 70 of file G4StatMFMacroCanonical.cc
References G4VStatMFEnsemble::__FreeInternalE0, A(), CalculateTemperature(), source.hepunit::elm_coupling, G4Fragment::GetA_asInt(), G4StatMFParameters::GetBeta0(), G4StatMFParameters::GetE0(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), G4StatMFParameters::Getr0(), G4Fragment::GetZ_asInt(), x, Z, G4Pow::Z13(), and G4Pow::Z23().
Referenced by G4StatMFMacroCanonical().
G4bool G4StatMFMacroCanonical::operator!= (const G4StatMFMacroCanonical & right) const private
G4StatMFMacroCanonical& G4StatMFMacroCanonical::operator= (const G4StatMFMacroCanonical & right) private
G4bool G4StatMFMacroCanonical::operator== (const G4StatMFMacroCanonical & right) const private
Member Data Documentation
G4double G4StatMFMacroCanonical::_ChemPotentialMu private
Definition at line 98 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 98 of file G4StatMFMacroCanonical.hh
Referenced by CalculateTemperature().
G4double G4StatMFMacroCanonical::_ChemPotentialNu private
Definition at line 101 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 101 of file G4StatMFMacroCanonical.hh
Referenced by CalculateTemperature(), and ChooseZ().
G4double G4StatMFMacroCanonical::_Kappa private
Definition at line 105 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 105 of file G4StatMFMacroCanonical.hh
Referenced by CalculateTemperature().
std::vector<G4VStatMFMacroCluster*> G4StatMFMacroCanonical::_theClusters private
Definition at line 108 of file G4StatMFMacroCanonical.hh.
View newest version in sPHENIX GitHub at line 108 of file G4StatMFMacroCanonical.hh
Referenced by CalculateTemperature(), ChooseA(), ChooseZ(), G4StatMFMacroCanonical(), and ~G4StatMFMacroCanonical().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroCanonical.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMacroCanonical.cc