ECCE @ EIC Software: G4EmConfigurator Class Reference
G4EmConfigurator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmConfigurator.hh>
Public Member Functions
G4EmConfigurator (G4int verboseLevel=1)
~G4EmConfigurator ()
void SetExtraEmModel (const G4String &particleName, const G4String &processName, G4VEmModel *, const G4String &regionName="", G4double emin=0.0, G4double emax=DBL_MAX, G4VEmFluctuationModel *fm=nullptr)
void AddModels ()
void PrepareModels (const G4ParticleDefinition *aParticle, G4VEnergyLossProcess *p)
void PrepareModels (const G4ParticleDefinition *aParticle, G4VEmProcess *p)
void PrepareModels (const G4ParticleDefinition *aParticle, G4VMultipleScattering *p)
void Clear ()
void SetVerbose (G4int value)
Private Member Functions
G4Region * FindRegion (const G4String &)
void SetModelForRegion (G4VEmModel *model, G4VEmFluctuationModel *fm, G4Region *reg, const G4String &particleName, const G4String &processName, G4double emin, G4double emax)
G4bool UpdateModelEnergyRange (G4VEmModel *mod, G4double emin, G4double emax)
G4EmConfigurator & operator= (const G4EmConfigurator &right)=delete
G4EmConfigurator (const G4EmConfigurator &)=delete
Private Attributes
std::vector< G4VEmModel * > models
std::vector
< G4VEmFluctuationModel * > flucModels
std::vector< G4String > particles
std::vector< G4String > processes
std::vector< G4String > regions
std::vector< G4double > lowEnergy
std::vector< G4double > highEnergy
G4int index
G4int verbose
Detailed Description
Definition at line 62 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 62 of file G4EmConfigurator.hh
Constructor & Destructor Documentation
G4EmConfigurator::G4EmConfigurator (G4int verboseLevel = 1) explicit
Definition at line 64 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 64 of file G4EmConfigurator.cc
References index.
G4EmConfigurator::~G4EmConfigurator ()
Definition at line 71 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 71 of file G4EmConfigurator.cc
G4EmConfigurator::G4EmConfigurator (const G4EmConfigurator &) private delete
Member Function Documentation
void G4EmConfigurator::AddModels ()
Definition at line 110 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 110 of file G4EmConfigurator.cc
References Clear(), FindRegion(), flucModels, G4cout, G4endl, highEnergy, index, lowEnergy, models, n, particles, processes, reg, regions, SetModelForRegion(), and verbose.
Referenced by G4EmDNAPhysicsActivator::ConstructProcess(), GammaRayTelPhysicsList::ConstructProcess(), and IORTPhysicsList::ConstructProcess().
void G4EmConfigurator::Clear ()
Definition at line 343 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 343 of file G4EmConfigurator.cc
References flucModels, highEnergy, lowEnergy, models, particles, processes, and regions.
Referenced by AddModels(), G4LossTableManager::BuildPhysicsTable(), and G4LossTableManager::LocalPhysicsTables().
G4Region * G4EmConfigurator::FindRegion (const G4String & regionName) private
Definition at line 356 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 356 of file G4EmConfigurator.cc
References G4cout, G4endl, G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), r, reg, and verbose.
Referenced by AddModels(), and PrepareModels().
G4EmConfigurator& G4EmConfigurator::operator= (const G4EmConfigurator & right) private delete
void G4EmConfigurator::PrepareModels (const G4ParticleDefinition * aParticle, G4VEnergyLossProcess * p)
Definition at line 220 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 220 of file G4EmConfigurator.cc
References G4VEnergyLossProcess::AddEmModel(), FindRegion(), flucModels, Acts::UnitConstants::fm, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4VProcess::GetProcessName(), highEnergy, index, lowEnergy, models, n, particles, processes, reg, regions, G4VEnergyLossProcess::SetFluctModel(), UpdateModelEnergyRange(), and verbose.
Referenced by G4LossTableManager::PreparePhysicsTable().
void G4EmConfigurator::PrepareModels (const G4ParticleDefinition * aParticle, G4VEmProcess * p)
Definition at line 265 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 265 of file G4EmConfigurator.cc
References G4VEmProcess::AddEmModel(), FindRegion(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4VProcess::GetProcessName(), highEnergy, index, lowEnergy, models, n, particles, processes, reg, regions, UpdateModelEnergyRange(), and verbose.
void G4EmConfigurator::PrepareModels (const G4ParticleDefinition * aParticle, G4VMultipleScattering * p)
Definition at line 306 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 306 of file G4EmConfigurator.cc
References G4VMultipleScattering::AddEmModel(), FindRegion(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4VProcess::GetProcessName(), highEnergy, index, lowEnergy, models, n, particles, processes, reg, regions, UpdateModelEnergyRange(), and verbose.
void G4EmConfigurator::SetExtraEmModel (const G4String & particleName, const G4String & processName, G4VEmModel * mod, const G4String & regionName = "", G4double emin = 0.0, G4double emax = DBL_MAX, G4VEmFluctuationModel * fm = nullptr)
Definition at line 76 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 76 of file G4EmConfigurator.cc
References flucModels, G4cout, G4endl, G4VEmModel::GetName(), highEnergy, G4VEmModel::HighEnergyLimit(), lowEnergy, G4VEmModel::LowEnergyLimit(), max, MeV, min, models, particles, processes, regions, G4VEmModel::SetActivationHighEnergyLimit(), and verbose.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), PhysicsList::AddIonGasModels(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4EmModelActivator::AddStandardScattering(), and PhysicsList::ConstructEM().
void G4EmConfigurator::SetModelForRegion (G4VEmModel * model, G4VEmFluctuationModel * fm, G4Region * reg, const G4String & particleName, const G4String & processName, G4double emin, G4double emax) private
Definition at line 134 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 134 of file G4EmConfigurator.cc
References G4VMultipleScattering::AddEmModel(), G4VEmProcess::AddEmModel(), G4VEnergyLossProcess::AddEmModel(), G4cout, G4endl, G4ParticleTable::GetIterator(), G4VEmFluctuationModel::GetName(), G4Region::GetName(), G4VEmModel::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ProcessManager::GetProcessList(), G4ProcessManager::GetProcessListLength(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessSubType(), index, MeV, part, G4ParticleTableIterator< K, V >::reset(), UpdateModelEnergyRange(), and verbose.
Referenced by AddModels().
void G4EmConfigurator::SetVerbose (G4int value) inline
Definition at line 135 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 135 of file G4EmConfigurator.hh
References verbose.
Referenced by G4LossTableManager::ResetParameters().
G4bool G4EmConfigurator::UpdateModelEnergyRange (G4VEmModel * mod, G4double emin, G4double emax) private
Definition at line 378 of file G4EmConfigurator.cc.
View newest version in sPHENIX GitHub at line 378 of file G4EmConfigurator.cc
References e1, e2, G4cout, G4endl, G4VEmModel::GetName(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), max, CLHEP::MeV, MeV, min, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), and verbose.
Referenced by PrepareModels(), and SetModelForRegion().
Member Data Documentation
std::vector<G4VEmFluctuationModel*> G4EmConfigurator::flucModels private
Definition at line 122 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 122 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
std::vector<G4double> G4EmConfigurator::highEnergy private
Definition at line 127 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 127 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
G4int G4EmConfigurator::index private
Definition at line 129 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 129 of file G4EmConfigurator.hh
Referenced by AddModels(), G4EmConfigurator(), PrepareModels(), and SetModelForRegion().
std::vector<G4double> G4EmConfigurator::lowEnergy private
Definition at line 126 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 126 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
std::vector<G4VEmModel*> G4EmConfigurator::models private
Definition at line 121 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 121 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
std::vector<G4String> G4EmConfigurator::particles private
Definition at line 123 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 123 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
std::vector<G4String> G4EmConfigurator::processes private
Definition at line 124 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 124 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
std::vector<G4String> G4EmConfigurator::regions private
Definition at line 125 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 125 of file G4EmConfigurator.hh
Referenced by AddModels(), Clear(), PrepareModels(), and SetExtraEmModel().
G4int G4EmConfigurator::verbose private
Definition at line 130 of file G4EmConfigurator.hh.
View newest version in sPHENIX GitHub at line 130 of file G4EmConfigurator.hh
Referenced by AddModels(), FindRegion(), PrepareModels(), SetExtraEmModel(), SetModelForRegion(), SetVerbose(), and UpdateModelEnergyRange().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmConfigurator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmConfigurator.cc