ECCE @ EIC Software: G4FissionParameters Class Reference
G4FissionParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionParameters.hh>
Public Member Functions
G4FissionParameters ()
~G4FissionParameters ()
void DefineParameters (G4int A, G4int Z, G4double ExEnergy, G4double FissionBarrier)
G4int GetA1 (void) const
G4int GetA2 (void) const
G4double GetAs (void) const
G4double GetSigma1 (void) const
G4double GetSigma2 (void) const
G4double GetSigmaS (void) const
G4double GetW (void) const
Private Member Functions
G4double LocalExp (G4double x) const
G4FissionParameters (const G4FissionParameters &right)
const G4FissionParameters & operator= (const G4FissionParameters &right)
G4bool operator== (const G4FissionParameters &right) const
G4bool operator!= (const G4FissionParameters &right) const
Private Attributes
G4int A1
G4int A2
G4double A3
G4double As
G4double Sigma1
G4double Sigma2
G4double SigmaS
G4double w
Detailed Description
Definition at line 38 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 38 of file G4FissionParameters.hh
Constructor & Destructor Documentation
G4FissionParameters::G4FissionParameters ()
Definition at line 37 of file G4FissionParameters.cc.
View newest version in sPHENIX GitHub at line 37 of file G4FissionParameters.cc
G4FissionParameters::~G4FissionParameters ()
Definition at line 42 of file G4FissionParameters.cc.
View newest version in sPHENIX GitHub at line 42 of file G4FissionParameters.cc
G4FissionParameters::G4FissionParameters (const G4FissionParameters & right) private
Member Function Documentation
void G4FissionParameters::DefineParameters (G4int A, G4int Z, G4double ExEnergy, G4double FissionBarrier)
Definition at line 45 of file G4FissionParameters.cc.
View newest version in sPHENIX GitHub at line 45 of file G4FissionParameters.cc
References A1, A2, A3, As, G4Exp(), LocalExp(), max, CLHEP::MeV, min, Sigma1, Sigma2, SigmaS, w, X, x1, x2, and x3.
Referenced by G4CompetitiveFission::EmittedFragment().
G4int G4FissionParameters::GetA1 (void) const inline
Definition at line 51 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 51 of file G4FissionParameters.hh
References A1.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4int G4FissionParameters::GetA2 (void) const inline
Definition at line 52 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 52 of file G4FissionParameters.hh
References A2.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4double G4FissionParameters::GetAs (void) const inline
Definition at line 54 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 54 of file G4FissionParameters.hh
References As.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4double G4FissionParameters::GetSigma1 (void) const inline
Definition at line 55 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 55 of file G4FissionParameters.hh
References Sigma1.
Referenced by G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4double G4FissionParameters::GetSigma2 (void) const inline
Definition at line 56 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 56 of file G4FissionParameters.hh
References Sigma2.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4double G4FissionParameters::GetSigmaS (void) const inline
Definition at line 57 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 57 of file G4FissionParameters.hh
References SigmaS.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4double G4FissionParameters::GetW (void) const inline
Definition at line 58 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 58 of file G4FissionParameters.hh
References w.
Referenced by G4CompetitiveFission::FissionAtomicNumber(), G4CompetitiveFission::FissionKineticEnergy(), and G4CompetitiveFission::MassDistribution().
G4double G4FissionParameters::LocalExp (G4double x) const inline private
Definition at line 62 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 62 of file G4FissionParameters.hh
References kdfinder::abs(), and G4Exp().
Referenced by DefineParameters().
G4bool G4FissionParameters::operator!= (const G4FissionParameters & right) const private
const G4FissionParameters& G4FissionParameters::operator= (const G4FissionParameters & right) private
G4bool G4FissionParameters::operator== (const G4FissionParameters & right) const private
Member Data Documentation
G4int G4FissionParameters::A1 private
Definition at line 74 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetA1().
G4int G4FissionParameters::A2 private
Definition at line 75 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetA2().
G4double G4FissionParameters::A3 private
Definition at line 76 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FissionParameters.hh
Referenced by DefineParameters().
G4double G4FissionParameters::As private
Definition at line 79 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetAs().
G4double G4FissionParameters::Sigma1 private
Definition at line 83 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetSigma1().
G4double G4FissionParameters::Sigma2 private
Definition at line 84 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 84 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetSigma2().
G4double G4FissionParameters::SigmaS private
Definition at line 87 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 87 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetSigmaS().
G4double G4FissionParameters::w private
Definition at line 91 of file G4FissionParameters.hh.
View newest version in sPHENIX GitHub at line 91 of file G4FissionParameters.hh
Referenced by DefineParameters(), and GetW().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/src/G4FissionParameters.cc