ECCE @ EIC Software: CCalMagneticField Class Reference
CCalMagneticField Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalMagneticField.hh>
Public Member Functions
CCalMagneticField (const G4String &name)
~CCalMagneticField ()
void MagneticField (const G4double Point[3], G4double Bfield[3]) const
CLHEP::Hep3Vector MagneticField (const CLHEP::Hep3Vector Point) const
virtual void GetFieldValue (const G4double Point[3], G4double *Bfield) const
G4double GetConstantFieldvalue () const
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
virtual void GetFieldValue (const G4double Point[4], G4double *Bfield) const =0
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
virtual G4Field * Clone () const
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
Private Attributes
G4double fval
G4int npts
G4double xoff
G4double * pos
G4double * slope
G4double * intercept
G4int fVerbosity
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 38 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 38 of file CCalMagneticField.hh
Constructor & Destructor Documentation
CCalMagneticField::CCalMagneticField (const G4String & name)
Definition at line 42 of file CCalMagneticField.cc.
View newest version in sPHENIX GitHub at line 42 of file CCalMagneticField.cc
References findDO(), fval, fVerbosity, G4cout, G4endl, intercept, mm, npts, openGeomFile(), pos, slope, tab(), and xoff.
CCalMagneticField::~CCalMagneticField ()
Definition at line 88 of file CCalMagneticField.cc.
View newest version in sPHENIX GitHub at line 88 of file CCalMagneticField.cc
References intercept, pos, and slope.
Member Function Documentation
G4double CCalMagneticField::GetConstantFieldvalue () const inline
Definition at line 48 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 48 of file CCalMagneticField.hh
References fval.
Referenced by CCalDetectorConstruction::Construct().
void CCalMagneticField::GetFieldValue (const G4double Point[3], G4double * Bfield) const virtual
Definition at line 152 of file CCalMagneticField.cc.
View newest version in sPHENIX GitHub at line 152 of file CCalMagneticField.cc
References MagneticField().
G4FieldManager* CCalMagneticField::GetGlobalFieldManager () protected
void CCalMagneticField::MagneticField (const G4double Point[3], G4double Bfield[3]) const
Definition at line 100 of file CCalMagneticField.cc.
View newest version in sPHENIX GitHub at line 100 of file CCalMagneticField.cc
References c1, fval, fVerbosity, G4cout, G4endl, intercept, kilogauss, m, mm, npts, pos, slope, tesla, and xoff.
Referenced by GetFieldValue(), and MagneticField().
CLHEP::Hep3Vector CCalMagneticField::MagneticField (const CLHEP::Hep3Vector Point) const
Definition at line 136 of file CCalMagneticField.cc.
View newest version in sPHENIX GitHub at line 136 of file CCalMagneticField.cc
References B(), MagneticField(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), v, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double CCalMagneticField::fval private
Definition at line 55 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 55 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), GetConstantFieldvalue(), and MagneticField().
G4int CCalMagneticField::fVerbosity private
Definition at line 62 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), and MagneticField().
G4double* CCalMagneticField::intercept private
Definition at line 60 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 60 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), MagneticField(), and ~CCalMagneticField().
G4int CCalMagneticField::npts private
Definition at line 56 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 56 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), and MagneticField().
G4double* CCalMagneticField::pos private
Definition at line 58 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 58 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), MagneticField(), and ~CCalMagneticField().
G4double* CCalMagneticField::slope private
Definition at line 59 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 59 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), MagneticField(), and ~CCalMagneticField().
G4double CCalMagneticField::xoff private
Definition at line 57 of file CCalMagneticField.hh.
View newest version in sPHENIX GitHub at line 57 of file CCalMagneticField.hh
Referenced by CCalMagneticField(), and MagneticField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalMagneticField.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalMagneticField.cc