ECCE @ EIC Software: G4OpRayleigh Class Reference
G4OpRayleigh Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/optical/include/G4OpRayleigh.hh>
Public Member Functions
G4OpRayleigh (const G4String &processName="OpRayleigh", G4ProcessType type=fOptical)
virtual ~G4OpRayleigh ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &aParticleType) override
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4PhysicsTable * GetPhysicsTable () const
virtual void DumpPhysicsTable () const
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Attributes
G4PhysicsTable * thePhysicsTable
Private Member Functions
G4OpRayleigh (const G4OpRayleigh &right)=delete
G4OpRayleigh & operator= (const G4OpRayleigh &right)=delete
G4PhysicsOrderedFreeVector * CalculateRayleighMeanFreePaths (const G4Material *material) const
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Detailed Description
Definition at line 68 of file G4OpRayleigh.hh.
View newest version in sPHENIX GitHub at line 68 of file G4OpRayleigh.hh
Constructor & Destructor Documentation
G4OpRayleigh::G4OpRayleigh (const G4String & processName = "OpRayleigh", G4ProcessType type = fOptical) explicit
Definition at line 73 of file G4OpRayleigh.cc.
View newest version in sPHENIX GitHub at line 73 of file G4OpRayleigh.cc
References fOpRayleigh, G4cout, G4endl, G4VProcess::GetProcessName(), G4VProcess::SetProcessSubType(), thePhysicsTable, and G4VProcess::verboseLevel.
G4OpRayleigh::~G4OpRayleigh () virtual
Definition at line 87 of file G4OpRayleigh.cc.
View newest version in sPHENIX GitHub at line 87 of file G4OpRayleigh.cc
References G4PhysicsTable::clearAndDestroy(), and thePhysicsTable.
G4OpRayleigh::G4OpRayleigh (const G4OpRayleigh & right) private delete
Member Function Documentation
void G4OpRayleigh::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 191 of file G4OpRayleigh.cc.
View newest version in sPHENIX GitHub at line 191 of file G4OpRayleigh.cc
References CalculateRayleighMeanFreePaths(), G4PhysicsTable::clearAndDestroy(), G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), G4MaterialPropertiesTable::GetProperty(), G4PhysicsTable::insertAt(), kRAYLEIGH, material(), and thePhysicsTable.
G4PhysicsOrderedFreeVector * G4OpRayleigh::CalculateRayleighMeanFreePaths (const G4Material * material) const private
Calculates the mean free paths for a material as a function of photon energy
Definition at line 239 of file G4OpRayleigh.cc.
View newest version in sPHENIX GitHub at line 239 of file G4OpRayleigh.cc
References c1, c2, source.hepunit::c_light, G4MaterialPropertiesTable::ConstPropertyExists(), energy, G4PhysicsVector::Energy(), G4cout, G4endl, G4MaterialPropertiesTable::GetConstProperty(), G4Material::GetMaterialPropertiesTable(), G4Material::GetName(), G4MaterialPropertiesTable::GetProperty(), G4Material::GetTemperature(), G4PhysicsVector::GetVectorLength(), source.hepunit::h_Planck, G4PhysicsOrderedFreeVector::InsertValues(), source.hepunit::k_Boltzmann, kelvin, kISOTHERMAL_COMPRESSIBILITY, kRINDEX, kRS_SCALE_FACTOR, m3, MeV, pi, twopi, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable().
void G4OpRayleigh::DumpPhysicsTable () const inline virtual
Definition at line 129 of file G4OpRayleigh.hh.
View newest version in sPHENIX GitHub at line 129 of file G4OpRayleigh.hh
References G4PhysicsVector::DumpValues(), G4PhysicsTable::entries(), thePhysicsTable, and v.
G4double G4OpRayleigh::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition *) override virtual
Implements G4VDiscreteProcess.
Definition at line 220 of file G4OpRayleigh.cc.
View newest version in sPHENIX GitHub at line 220 of file G4OpRayleigh.cc
References DBL_MAX, G4Track::GetDynamicParticle(), G4Material::GetIndex(), G4Track::GetMaterial(), G4DynamicParticle::GetTotalMomentum(), material(), particle, and G4PhysicsVector::Value().
G4PhysicsTable * G4OpRayleigh::GetPhysicsTable () const inline virtual
Definition at line 141 of file G4OpRayleigh.hh.
View newest version in sPHENIX GitHub at line 141 of file G4OpRayleigh.hh
References thePhysicsTable.
G4bool G4OpRayleigh::IsApplicable (const G4ParticleDefinition & aParticleType) inline override virtual
Reimplemented from G4VProcess.
Definition at line 123 of file G4OpRayleigh.hh.
View newest version in sPHENIX GitHub at line 123 of file G4OpRayleigh.hh
References G4OpticalPhoton::OpticalPhoton().
G4OpRayleigh& G4OpRayleigh::operator= (const G4OpRayleigh & right) private delete
G4VParticleChange * G4OpRayleigh::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 98 of file G4OpRayleigh.cc.
View newest version in sPHENIX GitHub at line 98 of file G4OpRayleigh.cc
References G4VProcess::aParticleChange, CLHEP::Hep3Vector::dot(), G4cout, G4endl, G4UniformRand, G4Track::GetDynamicParticle(), G4DynamicParticle::GetMomentumDirection(), G4ParticleChange::GetMomentumDirection(), G4ParticleChange::GetPolarization(), G4DynamicParticle::GetPolarization(), G4ParticleChange::Initialize(), CLHEP::Hep3Vector::mag(), G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), twopi, CLHEP::Hep3Vector::unit(), and G4VProcess::verboseLevel.
Member Data Documentation
G4PhysicsTable* G4OpRayleigh::thePhysicsTable protected
Definition at line 102 of file G4OpRayleigh.hh.
View newest version in sPHENIX GitHub at line 102 of file G4OpRayleigh.hh
Referenced by BuildPhysicsTable(), DumpPhysicsTable(), G4OpRayleigh(), GetPhysicsTable(), and ~G4OpRayleigh().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/optical/include/G4OpRayleigh.hh
geant4/tree/geant4-10.6-release/source/processes/optical/src/G4OpRayleigh.cc