ECCE @ EIC Software: G4UIparameter Class Reference
G4UIparameter Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIparameter.hh>
Public Member Functions
G4UIparameter ()
G4UIparameter (char theType)
G4UIparameter (const char *theName, char theType, G4bool theOmittable)
~G4UIparameter ()
G4bool operator== (const G4UIparameter &right) const
G4bool operator!= (const G4UIparameter &right) const
G4int CheckNewValue (const char *newValue)
void List ()
void SetDefaultValue (const char *theDefaultValue)
void SetDefaultValue (G4int theDefaultValue)
void SetDefaultValue (G4double theDefaultValue)
void SetDefaultUnit (const char *theDefaultUnit)
G4String GetDefaultValue () const
char GetParameterType () const
void SetParameterRange (const char *theRange)
G4String GetParameterRange () const
void SetParameterName (const char *theName)
G4String GetParameterName () const
void SetParameterCandidates (const char *theString)
G4String GetParameterCandidates () const
void SetOmittable (G4bool om)
G4bool IsOmittable () const
void SetCurrentAsDefault (G4bool val)
G4bool GetCurrentAsDefault () const
void SetWidget (G4int theWidget)
const G4String GetParameterGuidance () const
void SetGuidance (const char *theGuidance)
Protected Types
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Private Member Functions
G4int TypeCheck (const char *newValue)
G4int RangeCheck (const char *newValue)
G4int CandidateCheck (const char *newValue)
G4int IsInt (const char *str, short maxDigit)
G4int IsDouble (const char *str)
G4int ExpectExponent (const char *str)
yystype Expression (void)
yystype LogicalORExpression (void)
yystype LogicalANDExpression (void)
yystype EqualityExpression (void)
yystype RelationalExpression (void)
yystype AdditiveExpression (void)
yystype MultiplicativeExpression (void)
yystype UnaryExpression (void)
yystype PrimaryExpression (void)
G4int Eval2 (yystype arg1, G4int op, yystype arg2)
G4int CompareInt (G4int arg1, G4int op, G4int arg2)
G4int CompareDouble (double arg1, G4int op, double arg2)
tokenNum Yylex (void)
G4int G4UIpGetc (void)
G4int G4UIpUngetc (G4int c)
G4int Backslash (G4int c)
G4int Follow (G4int expect, G4int ifyes, G4int ifno)
G4String TokenToStr (G4int token)
Private Attributes
G4String parameterName
G4String parameterGuidance
G4String defaultValue
G4String parameterRange
G4String parameterCandidate
char parameterType
G4bool omittable
G4bool currentAsDefaultFlag
G4int widget
G4String rangeBuf
G4int bp
tokenNum token
yystype yylval
yystype newVal
G4int paramERR
Detailed Description
Definition at line 46 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 46 of file G4UIparameter.hh
Member Typedef Documentation
using G4UIparameter::tokenNum = G4UItokenNum::tokenNum protected
Definition at line 148 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 148 of file G4UIparameter.hh
using G4UIparameter::yystype = G4UItokenNum::yystype protected
Definition at line 147 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 147 of file G4UIparameter.hh
Constructor & Destructor Documentation
G4UIparameter::G4UIparameter ()
Definition at line 38 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 38 of file G4UIparameter.cc
References bp, currentAsDefaultFlag, defaultValue, RawTowerDefs::NONE, omittable, parameterCandidate, parameterGuidance, parameterName, parameterRange, parameterType, token, and widget.
G4UIparameter::G4UIparameter (char theType)
Definition at line 54 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UIparameter.cc
References bp, currentAsDefaultFlag, defaultValue, RawTowerDefs::NONE, omittable, parameterCandidate, parameterGuidance, parameterName, parameterRange, parameterType, token, and widget.
G4UIparameter::G4UIparameter (const char * theName, char theType, G4bool theOmittable)
Definition at line 70 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 70 of file G4UIparameter.cc
References bp, currentAsDefaultFlag, defaultValue, RawTowerDefs::NONE, omittable, parameterCandidate, parameterGuidance, parameterName, parameterRange, parameterType, token, and widget.
G4UIparameter::~G4UIparameter ()
Definition at line 86 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 86 of file G4UIparameter.cc
Member Function Documentation
yystype G4UIparameter::AdditiveExpression (void) private
Definition at line 482 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 482 of file G4UIparameter.cc
References G4cerr, G4endl, MultiplicativeExpression(), paramERR, and token.
Referenced by RelationalExpression().
G4int G4UIparameter::Backslash (G4int c) private
G4int G4UIparameter::CandidateCheck (const char * newValue) private
Definition at line 172 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 172 of file G4UIparameter.cc
References G4cerr, G4endl, and parameterCandidate.
Referenced by CheckNewValue().
G4int G4UIparameter::CheckNewValue (const char * newValue)
Definition at line 162 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 162 of file G4UIparameter.cc
References CandidateCheck(), fParameterOutOfCandidates, fParameterOutOfRange, fParameterUnreadable, G4String::isNull(), parameterCandidate, parameterRange, RangeCheck(), and TypeCheck().
G4int G4UIparameter::CompareDouble (double arg1, G4int op, double arg2) private
Definition at line 661 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 661 of file G4UIparameter.cc
References EQ, G4cerr, G4endl, GE, GT, LE, LT, NE, and paramERR.
Referenced by Eval2().
G4int G4UIparameter::CompareInt (G4int arg1, G4int op, G4int arg2) private
Definition at line 636 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 636 of file G4UIparameter.cc
References EQ, G4cerr, G4endl, GE, GT, LE, LT, NE, and paramERR.
Referenced by Eval2().
yystype G4UIparameter::EqualityExpression (void) private
Definition at line 422 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 422 of file G4UIparameter.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, EQ, Eval2(), G4cerr, G4endl, G4UItokenNum::yystype::I, NE, paramERR, RelationalExpression(), token, G4UItokenNum::yystype::type, and Yylex().
Referenced by LogicalANDExpression().
G4int G4UIparameter::Eval2 (yystype arg1, G4int op, yystype arg2) private
Definition at line 580 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 580 of file G4UIparameter.cc
References CompareDouble(), CompareInt(), G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, newVal, paramERR, parameterName, parameterRange, parameterType, and G4UItokenNum::yystype::type.
Referenced by EqualityExpression(), and RelationalExpression().
G4int G4UIparameter::ExpectExponent (const char * str) private
Definition at line 273 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 273 of file G4UIparameter.cc
References IsInt().
Referenced by IsDouble().
yystype G4UIparameter::Expression (void) private
Definition at line 340 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 340 of file G4UIparameter.cc
References G4cerr, G4endl, and LogicalORExpression().
Referenced by PrimaryExpression(), and RangeCheck().
G4int G4UIparameter::Follow (G4int expect, G4int ifyes, G4int ifno) private
Definition at line 746 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 746 of file G4UIparameter.cc
References c, G4UIpGetc(), and G4UIpUngetc().
Referenced by Yylex().
G4int G4UIparameter::G4UIpGetc (void) private
Definition at line 757 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 757 of file G4UIparameter.cc
References bp, BTOF::length, and parameterRange.
Referenced by Follow(), and Yylex().
G4int G4UIparameter::G4UIpUngetc (G4int c) private
Definition at line 765 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 765 of file G4UIparameter.cc
References bp, G4cerr, G4endl, paramERR, and parameterRange.
Referenced by Follow(), and Yylex().
G4bool G4UIparameter::GetCurrentAsDefault () const inline
Definition at line 135 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 135 of file G4UIparameter.hh
References currentAsDefaultFlag.
Referenced by G4UIcommandTree::CreateHTML(), and export_G4UIparameter().
G4String G4UIparameter::GetDefaultValue () const inline
Definition at line 94 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 94 of file G4UIparameter.hh
References defaultValue.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit(), G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
G4String G4UIparameter::GetParameterCandidates () const inline
Definition at line 123 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 123 of file G4UIparameter.hh
References parameterCandidate.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithBestUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithBestUnit(), G4UIcommandTree::CreateHTML(), G4UIterminal::ExecuteCommand(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
const G4String G4UIparameter::GetParameterGuidance () const inline
Definition at line 141 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 141 of file G4UIparameter.hh
References parameterGuidance.
Referenced by export_G4UIparameter(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
G4String G4UIparameter::GetParameterName () const inline
Definition at line 114 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 114 of file G4UIparameter.hh
References parameterName.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UImanager::GetCurrentStringValue(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), and G4GenericMessenger::Command::SetUnit().
G4String G4UIparameter::GetParameterRange () const inline
Definition at line 108 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 108 of file G4UIparameter.hh
References parameterRange.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
char G4UIparameter::GetParameterType () const inline
Definition at line 96 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 96 of file G4UIparameter.hh
References parameterType.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4UIGAG::SendATclParamProperty().
G4int G4UIparameter::IsDouble (const char * str) private
Definition at line 281 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 281 of file G4UIparameter.cc
References ExpectExponent().
Referenced by TypeCheck(), and Yylex().
G4int G4UIparameter::IsInt (const char * str, short maxDigit) private
Definition at line 249 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 249 of file G4UIparameter.cc
References G4cerr, G4endl, and BTOF::length.
Referenced by ExpectExponent(), TypeCheck(), and Yylex().
G4bool G4UIparameter::IsOmittable () const inline
Definition at line 129 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 129 of file G4UIparameter.hh
References omittable.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit(), G4UIcommandTree::CreateHTML(), export_G4UIparameter(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), and G4GenericMessenger::Command::SetUnit().
void G4UIparameter::List ()
Definition at line 99 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 99 of file G4UIparameter.cc
References currentAsDefaultFlag, defaultValue, G4cout, G4endl, G4String::isNull(), omittable, parameterCandidate, parameterGuidance, parameterName, parameterRange, and parameterType.
Referenced by export_G4UIparameter().
yystype G4UIparameter::LogicalANDExpression (void) private
Definition at line 386 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 386 of file G4UIparameter.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::CONSTSTRING, G4UItokenNum::yystype::D, EqualityExpression(), G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, G4UItokenNum::LOGICALAND, paramERR, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by LogicalORExpression().
yystype G4UIparameter::LogicalORExpression (void) private
Definition at line 351 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 351 of file G4UIparameter.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::CONSTSTRING, G4UItokenNum::yystype::D, G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, LogicalANDExpression(), G4UItokenNum::LOGICALOR, paramERR, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by Expression().
yystype G4UIparameter::MultiplicativeExpression (void) private
Definition at line 494 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 494 of file G4UIparameter.cc
References G4cerr, G4endl, paramERR, token, and UnaryExpression().
Referenced by AdditiveExpression().
G4bool G4UIparameter::operator!= (const G4UIparameter & right) const
Definition at line 94 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 94 of file G4UIparameter.cc
G4bool G4UIparameter::operator== (const G4UIparameter & right) const
Definition at line 89 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 89 of file G4UIparameter.cc
yystype G4UIparameter::PrimaryExpression (void) private
Definition at line 543 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 543 of file G4UIparameter.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, Expression(), G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, paramERR, G4UItokenNum::yystype::S, token, G4UItokenNum::yystype::type, Yylex(), and yylval.
Referenced by UnaryExpression().
G4int G4UIparameter::RangeCheck (const char * newValue) private
Definition at line 187 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 187 of file G4UIparameter.cc
References bp, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, Expression(), G4cerr, G4endl, G4UItokenNum::yystype::I, newVal, paramERR, parameterRange, parameterType, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by CheckNewValue().
yystype G4UIparameter::RelationalExpression (void) private
Definition at line 453 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 453 of file G4UIparameter.cc
References AdditiveExpression(), G4UItokenNum::CONSTINT, Eval2(), G4cerr, G4endl, GE, GT, G4UItokenNum::yystype::I, LE, LT, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by EqualityExpression().
void G4UIparameter::SetCurrentAsDefault (G4bool val) inline
Definition at line 133 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 133 of file G4UIparameter.hh
References currentAsDefaultFlag.
Referenced by G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4GenericMessenger::Command::SetParameterName(), and G4UIcmdWithNucleusLimits::SetParameterName().
void G4UIparameter::SetDefaultUnit (const char * theDefaultUnit)
Definition at line 134 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 134 of file G4UIparameter.cc
References G4UIcommand::CategoryOf(), FatalException, G4Exception(), parameterName, parameterType, SetDefaultValue(), SetParameterCandidates(), and G4UIcommand::UnitsList().
Referenced by G4ScoreQuantityMessenger::FilterCommands(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), and G4ScoreQuantityMessenger::QuantityCommands().
void G4UIparameter::SetDefaultValue (const char * theDefaultValue) inline
Definition at line 82 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UIparameter.hh
References defaultValue.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), DMXParticleSourceMessenger::DMXParticleSourceMessenger(), G4ScoreQuantityMessenger::FilterCommands(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4GeneralParticleSourceMessenger::G4GeneralParticleSourceMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4InteractorMessenger::G4InteractorMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour(), G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible(), G4VisCommandGeometrySetForceAuxEdgeVisible::G4VisCommandGeometrySetForceAuxEdgeVisible(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle(), G4VisCommandGeometrySetForceSolid::G4VisCommandGeometrySetForceSolid(), G4VisCommandGeometrySetForceWireframe::G4VisCommandGeometrySetForceWireframe(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandGeometrySetLineWidth::G4VisCommandGeometrySetLineWidth(), G4VisCommandGeometrySetVisibility::G4VisCommandGeometrySetVisibility(), G4VisCommandOpen::G4VisCommandOpen(), G4VisCommandSceneAddArrow::G4VisCommandSceneAddArrow(), G4VisCommandSceneAddAxes::G4VisCommandSceneAddAxes(), G4VisCommandSceneAddLine::G4VisCommandSceneAddLine(), G4VisCommandSceneAddLogicalVolume::G4VisCommandSceneAddLogicalVolume(), G4VisCommandSceneAddLogo::G4VisCommandSceneAddLogo(), G4VisCommandSceneAddScale::G4VisCommandSceneAddScale(), G4VisCommandSceneAddText::G4VisCommandSceneAddText(), G4VisCommandSceneAddText2D::G4VisCommandSceneAddText2D(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetExtentForField::G4VisCommandSetExtentForField(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandSpecify::G4VisCommandSpecify(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerCentreOn::G4VisCommandViewerCentreOn(), G4VisCommandViewerCreate::G4VisCommandViewerCreate(), HistoMessenger::HistoMessenger(), G4ScoreQuantityMessenger::QuantityCommands(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4GenericMessenger::Command::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
void G4UIparameter::SetDefaultValue (G4int theDefaultValue)
Definition at line 119 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 119 of file G4UIparameter.cc
References defaultValue.
void G4UIparameter::SetDefaultValue (G4double theDefaultValue)
Definition at line 126 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 126 of file G4UIparameter.cc
References defaultValue.
void G4UIparameter::SetGuidance (const char * theGuidance) inline
Definition at line 143 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 143 of file G4UIparameter.hh
References parameterGuidance.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4RadioactiveDecayBaseMessenger::G4RadioactiveDecayBaseMessenger(), G4RadioactiveDecaymessenger::G4RadioactiveDecaymessenger(), G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour(), G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible(), G4VisCommandGeometrySetForceAuxEdgeVisible::G4VisCommandGeometrySetForceAuxEdgeVisible(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle(), G4VisCommandGeometrySetForceSolid::G4VisCommandGeometrySetForceSolid(), G4VisCommandGeometrySetForceWireframe::G4VisCommandGeometrySetForceWireframe(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandGeometrySetLineWidth::G4VisCommandGeometrySetLineWidth(), G4VisCommandGeometrySetVisibility::G4VisCommandGeometrySetVisibility(), G4VisCommandOpen::G4VisCommandOpen(), G4VisCommandSceneAddLogo::G4VisCommandSceneAddLogo(), G4VisCommandSceneAddScale::G4VisCommandSceneAddScale(), G4VisCommandSceneAddText::G4VisCommandSceneAddText(), G4VisCommandSceneAddText2D::G4VisCommandSceneAddText2D(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandSetTouchable::G4VisCommandSetTouchable(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerCentreOn::G4VisCommandViewerCentreOn(), G4VisCommandViewerCreate::G4VisCommandViewerCreate(), HistoMessenger::HistoMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), and TrackingMessenger::TrackingMessenger().
void G4UIparameter::SetOmittable (G4bool om) inline
Definition at line 127 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 127 of file G4UIparameter.hh
References G4InuclParticleNames::om, and omittable.
Referenced by G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4GenericMessenger::Command::SetParameterName(), and G4UIcmdWithNucleusLimits::SetParameterName().
void G4UIparameter::SetParameterCandidates (const char * theString) inline
Definition at line 118 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 118 of file G4UIparameter.hh
References parameterCandidate.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4InteractorMessenger::G4InteractorMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), G4UIcmdWithAString::SetCandidates(), G4GenericMessenger::Command::SetCandidates(), SetDefaultUnit(), G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), G4UIcmdWith3VectorAndUnit::SetUnitCandidates(), and TrackingMessenger::TrackingMessenger().
void G4UIparameter::SetParameterName (const char * theName) inline
Definition at line 112 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 112 of file G4UIparameter.hh
References parameterName.
Referenced by G4UIcmdWith3VectorAndUnit::G4UIcmdWith3VectorAndUnit(), G4UIcmdWithADoubleAndUnit::G4UIcmdWithADoubleAndUnit(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4GenericMessenger::Command::SetParameterName(), and G4UIcmdWithNucleusLimits::SetParameterName().
void G4UIparameter::SetParameterRange (const char * theRange) inline
Definition at line 100 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 100 of file G4UIparameter.hh
References parameterRange.
Referenced by G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4RadioactiveDecayBaseMessenger::G4RadioactiveDecayBaseMessenger(), G4RadioactiveDecaymessenger::G4RadioactiveDecaymessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), HistoMessenger::HistoMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), and TrackingMessenger::TrackingMessenger().
void G4UIparameter::SetWidget (G4int theWidget) inline
Definition at line 139 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 139 of file G4UIparameter.hh
References widget.
G4String G4UIparameter::TokenToStr (G4int token) private
G4int G4UIparameter::TypeCheck (const char * newValue) private
Definition at line 212 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 212 of file G4UIparameter.cc
References G4String::data(), G4cerr, G4endl, IsDouble(), IsInt(), parameterType, and G4String::toUpper().
Referenced by CheckNewValue().
yystype G4UIparameter::UnaryExpression (void) private
Definition at line 506 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 506 of file G4UIparameter.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, G4cerr, G4endl, G4UItokenNum::yystype::I, paramERR, PrimaryExpression(), token, G4UItokenNum::yystype::type, and Yylex().
Referenced by MultiplicativeExpression().
tokenNum G4UIparameter::Yylex (void) private
Definition at line 688 of file G4UIparameter.cc.
View newest version in sPHENIX GitHub at line 688 of file G4UIparameter.cc
References c, G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, G4String::data(), EQ, Follow(), G4cerr, G4endl, G4UIpGetc(), G4UIpUngetc(), GE, GT, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, IsDouble(), IsInt(), LE, G4UItokenNum::LOGICALAND, G4UItokenNum::LOGICALOR, LT, NE, paramERR, parameterName, G4UItokenNum::yystype::S, t, and yylval.
Referenced by EqualityExpression(), LogicalANDExpression(), LogicalORExpression(), PrimaryExpression(), RangeCheck(), RelationalExpression(), and UnaryExpression().
Member Data Documentation
G4int G4UIparameter::bp private
Definition at line 181 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 181 of file G4UIparameter.hh
Referenced by G4UIparameter(), G4UIpGetc(), G4UIpUngetc(), and RangeCheck().
G4bool G4UIparameter::currentAsDefaultFlag private
Definition at line 78 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 78 of file G4UIparameter.hh
Referenced by G4UIparameter(), GetCurrentAsDefault(), List(), and SetCurrentAsDefault().
G4String G4UIparameter::defaultValue private
Definition at line 73 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 73 of file G4UIparameter.hh
Referenced by G4UIparameter(), GetDefaultValue(), List(), and SetDefaultValue().
yystype G4UIparameter::newVal private
Definition at line 184 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 184 of file G4UIparameter.hh
Referenced by Eval2(), and RangeCheck().
G4bool G4UIparameter::omittable private
Definition at line 77 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 77 of file G4UIparameter.hh
Referenced by G4UIparameter(), IsOmittable(), List(), and SetOmittable().
G4int G4UIparameter::paramERR private
Definition at line 185 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 185 of file G4UIparameter.hh
Referenced by AdditiveExpression(), CompareDouble(), CompareInt(), EqualityExpression(), Eval2(), G4UIpUngetc(), LogicalANDExpression(), LogicalORExpression(), MultiplicativeExpression(), PrimaryExpression(), RangeCheck(), UnaryExpression(), and Yylex().
G4String G4UIparameter::parameterCandidate private
Definition at line 75 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 75 of file G4UIparameter.hh
Referenced by CandidateCheck(), CheckNewValue(), G4UIparameter(), GetParameterCandidates(), List(), and SetParameterCandidates().
G4String G4UIparameter::parameterGuidance private
Definition at line 72 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 72 of file G4UIparameter.hh
Referenced by G4UIparameter(), GetParameterGuidance(), List(), and SetGuidance().
G4String G4UIparameter::parameterName private
Definition at line 71 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 71 of file G4UIparameter.hh
Referenced by Eval2(), G4UIparameter(), GetParameterName(), List(), SetDefaultUnit(), SetParameterName(), and Yylex().
G4String G4UIparameter::parameterRange private
Definition at line 74 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 74 of file G4UIparameter.hh
Referenced by CheckNewValue(), Eval2(), G4UIparameter(), G4UIpGetc(), G4UIpUngetc(), GetParameterRange(), List(), RangeCheck(), and SetParameterRange().
char G4UIparameter::parameterType private
Definition at line 76 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 76 of file G4UIparameter.hh
Referenced by Eval2(), G4UIparameter(), GetParameterType(), List(), RangeCheck(), SetDefaultUnit(), and TypeCheck().
G4String G4UIparameter::rangeBuf private
Definition at line 180 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 180 of file G4UIparameter.hh
tokenNum G4UIparameter::token private
Definition at line 182 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 182 of file G4UIparameter.hh
Referenced by AdditiveExpression(), EqualityExpression(), G4UIparameter(), LogicalANDExpression(), LogicalORExpression(), MultiplicativeExpression(), PrimaryExpression(), RangeCheck(), RelationalExpression(), and UnaryExpression().
G4int G4UIparameter::widget private
Definition at line 79 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 79 of file G4UIparameter.hh
Referenced by G4UIparameter(), and SetWidget().
yystype G4UIparameter::yylval private
Definition at line 183 of file G4UIparameter.hh.
View newest version in sPHENIX GitHub at line 183 of file G4UIparameter.hh
Referenced by PrimaryExpression(), and Yylex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIparameter.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIparameter.cc