ECCE @ EIC Software: G4LossTableManager Class Reference
G4LossTableManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4LossTableManager.hh>
Public Member Functions
~G4LossTableManager ()
void PreparePhysicsTable (const G4ParticleDefinition *aParticle, G4VEnergyLossProcess *p, G4bool theMaster)
void PreparePhysicsTable (const G4ParticleDefinition *aParticle, G4VEmProcess *p, G4bool theMaster)
void PreparePhysicsTable (const G4ParticleDefinition *aParticle, G4VMultipleScattering *p, G4bool theMaster)
void BuildPhysicsTable (const G4ParticleDefinition *aParticle)
void BuildPhysicsTable (const G4ParticleDefinition *aParticle, G4VEnergyLossProcess *p)
void LocalPhysicsTables (const G4ParticleDefinition *aParticle, G4VEnergyLossProcess *p)
void DumpHtml ()
G4double GetDEDX (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetSubDEDX (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetRange (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetCSDARange (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetRangeFromRestricteDEDX (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetEnergy (const G4ParticleDefinition *aParticle, G4double range, const G4MaterialCutsCouple *couple)
G4double GetDEDXDispersion (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double &length)
void Register (G4VEnergyLossProcess *p)
void DeRegister (G4VEnergyLossProcess *p)
void Register (G4VMultipleScattering *p)
void DeRegister (G4VMultipleScattering *p)
void Register (G4VEmProcess *p)
void DeRegister (G4VEmProcess *p)
void Register (G4VProcess *p)
void DeRegister (G4VProcess *p)
void Register (G4VEmModel *p)
void DeRegister (G4VEmModel *p)
void Register (G4VEmFluctuationModel *p)
void DeRegister (G4VEmFluctuationModel *p)
void RegisterExtraParticle (const G4ParticleDefinition *aParticle, G4VEnergyLossProcess *p)
void SetVerbose (G4int val)
void SetAtomDeexcitation (G4VAtomDeexcitation *)
void SetSubCutProducer (G4VSubCutProducer *)
void SetNIELCalculator (G4NIELCalculator *)
G4bool IsMaster () const
G4VEnergyLossProcess * GetEnergyLossProcess (const G4ParticleDefinition *)
const std::vector
< G4VEnergyLossProcess * > & GetEnergyLossProcessVector ()
const std::vector
< G4VEmProcess * > & GetEmProcessVector ()
const std::vector
< G4VMultipleScattering * > & GetMultipleScatteringVector ()
G4EmSaturation * EmSaturation ()
G4EmConfigurator * EmConfigurator ()
G4ElectronIonPair * ElectronIonPair ()
G4NIELCalculator * NIELCalculator ()
G4EmCorrections * EmCorrections ()
G4VAtomDeexcitation * AtomDeexcitation ()
G4VSubCutProducer * SubCutProducer ()
G4LossTableBuilder * GetTableBuilder ()
void SetGammaGeneralProcess (G4VEmProcess *)
G4VEmProcess * GetGammaGeneralProcess ()
void SetElectronGeneralProcess (G4VEnergyLossProcess *)
G4VEnergyLossProcess * GetElectronGeneralProcess ()
Static Public Member Functions
static G4LossTableManager * Instance ()
Private Types
typedef const
G4ParticleDefinition * PD
Private Member Functions
G4LossTableManager ()
void Clear ()
void ResetParameters ()
G4VEnergyLossProcess * BuildTables (const G4ParticleDefinition *aParticle)
void CopyTables (const G4ParticleDefinition *aParticle, G4VEnergyLossProcess *)
void ParticleHaveNoLoss (const G4ParticleDefinition *aParticle)
void CopyDEDXTables ()
void PrintEWarning (G4String, G4double)
G4LossTableManager (G4LossTableManager &)=delete
G4LossTableManager & operator= (const G4LossTableManager &right)=delete
Private Attributes
std::map< PD,
G4VEnergyLossProcess
*, std::less< PD > > loss_map
std::vector
< G4VEnergyLossProcess * > loss_vector
std::vector< PD > part_vector
std::vector< PD > base_part_vector
std::vector< G4bool > tables_are_built
std::vector< G4bool > isActive
std::vector< G4PhysicsTable * > dedx_vector
std::vector< G4PhysicsTable * > range_vector
std::vector< G4PhysicsTable * > inv_range_vector
std::vector
< G4VMultipleScattering * > msc_vector
std::vector< G4VEmProcess * > emp_vector
std::vector< G4VEmModel * > mod_vector
std::vector
< G4VEmFluctuationModel * > fmod_vector
std::vector< G4VProcess * > p_vector
G4VEnergyLossProcess * currentLoss
PD currentParticle
PD theElectron
PD theGenericIon
PD firstParticle
G4int n_loss
G4int run
G4bool all_tables_are_built
G4bool startInitialisation
G4bool isMaster
G4LossTableBuilder * tableBuilder
G4EmCorrections * emCorrections
G4EmConfigurator * emConfigurator
G4ElectronIonPair * emElectronIonPair
G4NIELCalculator * nielCalculator
G4VAtomDeexcitation * atomDeexcitation
G4VSubCutProducer * subcutProducer
G4EmParameters * theParameters
G4VEmProcess * gGeneral
G4VEnergyLossProcess * eGeneral
G4int verbose
Static Private Attributes
static G4ThreadLocal
G4LossTableManager * instance = nullptr
Friends
class G4ThreadLocalSingleton< G4LossTableManager >
Detailed Description
Definition at line 76 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 76 of file G4LossTableManager.hh
Member Typedef Documentation
typedef const G4ParticleDefinition* G4LossTableManager::PD private
Definition at line 256 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 256 of file G4LossTableManager.hh
Constructor & Destructor Documentation
G4LossTableManager::~G4LossTableManager ()
Definition at line 98 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 98 of file G4LossTableManager.cc
References a, atomDeexcitation, b, Clear(), emConfigurator, emCorrections, emElectronIonPair, emp_vector, fmod_vector, k, loss_vector, mod_vector, msc_vector, n_loss, nielCalculator, p_vector, subcutProducer, and tableBuilder.
G4LossTableManager::G4LossTableManager () private
Definition at line 145 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 145 of file G4LossTableManager.cc
References all_tables_are_built, atomDeexcitation, currentLoss, currentParticle, eGeneral, G4Electron::Electron(), emConfigurator, emCorrections, emElectronIonPair, firstParticle, gGeneral, G4EmParameters::Instance(), isMaster, G4Threading::IsWorkerThread(), n_loss, nielCalculator, run, startInitialisation, subcutProducer, tableBuilder, theElectron, theGenericIon, theParameters, G4EmParameters::Verbose(), verbose, and G4EmParameters::WorkerVerbose().
G4LossTableManager::G4LossTableManager (G4LossTableManager &) private delete
Member Function Documentation
G4VAtomDeexcitation * G4LossTableManager::AtomDeexcitation () inline
Definition at line 399 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 399 of file G4LossTableManager.hh
References atomDeexcitation.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4VEnergyLossProcess::BuildPhysicsTable(), G4EmCalculator::ComputeShellIonisationCrossSectionPerAtom(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), BiasedRDPhysics::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4EmCalculator::GetShellIonisationCrossSectionPerAtom(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4PEEffectFluoModel::Initialise(), G4KleinNishinaModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), and G4VEmProcess::PreparePhysicsTable().
void G4LossTableManager::BuildPhysicsTable (const G4ParticleDefinition * aParticle)
Definition at line 537 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 537 of file G4LossTableManager.cc
References G4EmConfigurator::Clear(), emConfigurator, run, and startInitialisation.
Referenced by G4VMultipleScattering::BuildPhysicsTable(), and G4VEnergyLossProcess::BuildPhysicsTable().
void G4LossTableManager::BuildPhysicsTable (const G4ParticleDefinition * aParticle, G4VEnergyLossProcess * p)
Definition at line 626 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 626 of file G4LossTableManager.cc
References all_tables_are_built, atomDeexcitation, base_part_vector, G4VEnergyLossProcess::BaseParticle(), BuildTables(), G4EmConfigurator::Clear(), CopyTables(), currentParticle, emConfigurator, firstParticle, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4NIELCalculator::Initialise(), isActive, G4VEnergyLossProcess::IsIonisationProcess(), loss_map, loss_vector, n_loss, nielCalculator, part_vector, G4VEnergyLossProcess::Particle(), run, G4VEnergyLossProcess::SetIonisation(), startInitialisation, tables_are_built, and verbose.
G4VEnergyLossProcess * G4LossTableManager::BuildTables (const G4ParticleDefinition * aParticle) private
Definition at line 782 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 782 of file G4LossTableManager.cc
References G4VEnergyLossProcess::AddCollaborativeProcess(), G4EmParameters::BuildCSDARange(), G4LossTableBuilder::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4LossTableBuilder::BuildInverseRangeTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4LossTableBuilder::BuildRangeTable(), G4VEnergyLossProcess::CSDARangeTable(), dedx_vector, G4VEnergyLossProcess::DEDXTable(), G4VEnergyLossProcess::DEDXunRestrictedTable(), fIsIonisation, fIsSubIonisation, fRestricted, fSubRestricted, fTotal, G4cout, G4endl, G4VSubCutProducer::GetName(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), inv_range_vector, G4VEnergyLossProcess::InverseRangeTable(), G4VEnergyLossProcess::IonisationTableForSubsec(), isActive, G4VEnergyLossProcess::IsIonisationProcess(), loss_vector, n_loss, G4VEnergyLossProcess::NumberOfSubCutoffRegions(), part_vector, G4PhysicsTableHelper::PreparePhysicsTable(), range_vector, G4VEnergyLossProcess::RangeTableForLoss(), G4VEnergyLossProcess::SetCSDARangeTable(), G4VEnergyLossProcess::SetDEDXTable(), G4VEnergyLossProcess::SetInverseRangeTable(), G4VEnergyLossProcess::SetIonisation(), G4VEnergyLossProcess::SetLambdaTable(), G4VEnergyLossProcess::SetRangeTableForLoss(), G4VEnergyLossProcess::SetSubLambdaTable(), G4ProcessVector::size(), subcutProducer, tableBuilder, tables_are_built, theParameters, and verbose.
Referenced by BuildPhysicsTable().
void G4LossTableManager::Clear () private
Definition at line 176 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 176 of file G4LossTableManager.cc
References all_tables_are_built, base_part_vector, currentLoss, currentParticle, dedx_vector, inv_range_vector, isActive, loss_map, loss_vector, n_loss, part_vector, range_vector, and tables_are_built.
Referenced by ~G4LossTableManager().
void G4LossTableManager::CopyDEDXTables () private
void G4LossTableManager::CopyTables (const G4ParticleDefinition * aParticle, G4VEnergyLossProcess * base_proc) private
Definition at line 739 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 739 of file G4LossTableManager.cc
References base_part_vector, G4VEnergyLossProcess::CSDARangeTable(), G4VEnergyLossProcess::DEDXTableForSubsec(), G4VEnergyLossProcess::DEDXunRestrictedTable(), fRestricted, fSubRestricted, fTotal, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), inv_range_vector, G4VEnergyLossProcess::InverseRangeTable(), G4VEnergyLossProcess::IonisationTable(), G4VEnergyLossProcess::IsIonisationProcess(), G4VEnergyLossProcess::LambdaTable(), loss_map, loss_vector, n_loss, part_vector, range_vector, G4VEnergyLossProcess::RangeTableForLoss(), G4VEnergyLossProcess::SecondaryParticle(), G4VEnergyLossProcess::SetCSDARangeTable(), G4VEnergyLossProcess::SetDEDXTable(), G4VEnergyLossProcess::SetInverseRangeTable(), G4VEnergyLossProcess::SetIonisation(), G4VEnergyLossProcess::SetLambdaTable(), G4VEnergyLossProcess::SetRangeTableForLoss(), G4VEnergyLossProcess::SetSecondaryRangeTable(), G4VEnergyLossProcess::SetSubLambdaTable(), G4VEnergyLossProcess::SubLambdaTable(), tables_are_built, theElectron, and verbose.
Referenced by BuildPhysicsTable().
void G4LossTableManager::DeRegister (G4VEnergyLossProcess * p)
Definition at line 240 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 240 of file G4LossTableManager.cc
References loss_vector, and n_loss.
Referenced by G4AnnihiToMuPair::~G4AnnihiToMuPair(), G4GammaConversionToMuons::~G4GammaConversionToMuons(), G4SynchrotronRadiation::~G4SynchrotronRadiation(), G4VEmFluctuationModel::~G4VEmFluctuationModel(), G4VEmModel::~G4VEmModel(), G4VEmProcess::~G4VEmProcess(), G4VEnergyLossProcess::~G4VEnergyLossProcess(), G4VMultipleScattering::~G4VMultipleScattering(), and G4VTransitionRadiation::~G4VTransitionRadiation().
void G4LossTableManager::DeRegister (G4VMultipleScattering * p)
Definition at line 269 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 269 of file G4LossTableManager.cc
References msc_vector.
void G4LossTableManager::DeRegister (G4VEmProcess * p)
Definition at line 299 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 299 of file G4LossTableManager.cc
References emp_vector.
void G4LossTableManager::DeRegister (G4VProcess * p)
Definition at line 329 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 329 of file G4LossTableManager.cc
References p_vector.
void G4LossTableManager::DeRegister (G4VEmModel * p)
Definition at line 354 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 354 of file G4LossTableManager.cc
References mod_vector, and n.
void G4LossTableManager::DeRegister (G4VEmFluctuationModel * p)
Definition at line 379 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 379 of file G4LossTableManager.cc
References fmod_vector, and n.
void G4LossTableManager::DumpHtml ()
Definition at line 1093 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1093 of file G4LossTableManager.cc
References G4Electron::Electron(), G4endl, G4Gamma::Gamma(), GetEmProcessVector(), GetEnergyLossProcessVector(), GetMultipleScatteringVector(), G4ProcessManager::GetProcessList(), G4ProcessManager::GetProcessListLength(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), Acts::UnitConstants::pm, G4Positron::Positron(), G4VProcess::ProcessDescription(), and G4Proton::ProtonDefinition().
G4ElectronIonPair * G4LossTableManager::ElectronIonPair ()
Definition at line 1026 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1026 of file G4LossTableManager.cc
References emElectronIonPair, and verbose.
G4EmConfigurator * G4LossTableManager::EmConfigurator ()
Definition at line 1016 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1016 of file G4LossTableManager.cc
References emConfigurator, and verbose.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), PhysicsList::AddIonGasModels(), G4EmDNAPhysicsActivator::AddProtonModels0(), PhysicsList::ConstructEM(), and G4EmDNAPhysicsActivator::ConstructProcess().
G4EmCorrections * G4LossTableManager::EmCorrections () inline
Definition at line 392 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 392 of file G4LossTableManager.hh
References emCorrections.
Referenced by G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4BetheBlochModel::G4BetheBlochModel(), G4BraggModel::G4BraggModel(), G4EmCalculator::G4EmCalculator(), G4ionIonisation::G4ionIonisation(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4LindhardSorensenIonModel::G4LindhardSorensenIonModel(), G4MuBetheBlochModel::G4MuBetheBlochModel(), G4UAtomicDeexcitation::G4UAtomicDeexcitation(), G4BraggIonModel::Initialise(), and G4ContinuousGainOfEnergy::SetDynamicMassCharge().
G4EmSaturation * G4LossTableManager::EmSaturation ()
Definition at line 1009 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1009 of file G4LossTableManager.cc
References G4EmParameters::GetEmSaturation(), and theParameters.
Referenced by G4OpticalPhysics::ConstructProcess(), PHG4SteppingAction::GetVisibleEnergyDeposition(), and PHG4Reco::Init().
G4double G4LossTableManager::GetCSDARange (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 328 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 328 of file G4LossTableManager.hh
References currentLoss, currentParticle, DBL_MAX, G4VEnergyLossProcess::GetCSDARange(), and GetEnergyLossProcess().
Referenced by G4EmCalculator::GetCSDARange().
G4double G4LossTableManager::GetDEDX (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 306 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 306 of file G4LossTableManager.hh
References currentLoss, currentParticle, G4VEnergyLossProcess::GetDEDX(), and GetEnergyLossProcess().
Referenced by G4EmCalculator::GetDEDX(), G4EnergyLossTables::GetDEDX(), G4EnergyLossTables::GetPreciseDEDX(), G4EnergyLossTables::GetPreciseRangeFromEnergy(), and G4Cerenkov::PostStepGetPhysicalInteractionLength().
G4double G4LossTableManager::GetDEDXDispersion (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double & length) inline
Definition at line 373 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 373 of file G4LossTableManager.hh
References currentLoss, currentParticle, G4VEnergyLossProcess::GetDEDXDispersion(), GetEnergyLossProcess(), and G4DynamicParticle::GetParticleDefinition().
G4VEnergyLossProcess * G4LossTableManager::GetElectronGeneralProcess () inline
Definition at line 442 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 442 of file G4LossTableManager.hh
References eGeneral.
const std::vector< G4VEmProcess * > & G4LossTableManager::GetEmProcessVector ()
Definition at line 994 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 994 of file G4LossTableManager.cc
References emp_vector.
Referenced by DumpHtml(), and G4EmCalculator::FindDiscreteProcess().
G4double G4LossTableManager::GetEnergy (const G4ParticleDefinition * aParticle, G4double range, const G4MaterialCutsCouple * couple) inline
Definition at line 362 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 362 of file G4LossTableManager.hh
References currentLoss, currentParticle, GetEnergyLossProcess(), and G4VEnergyLossProcess::GetKineticEnergy().
Referenced by G4EmCalculator::GetKinEnergy(), and G4EnergyLossTables::GetPreciseEnergyFromRange().
G4VEnergyLossProcess * G4LossTableManager::GetEnergyLossProcess (const G4ParticleDefinition * aParticle)
Definition at line 416 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 416 of file G4LossTableManager.cc
References currentLoss, currentParticle, loss_map, pos(), and theGenericIon.
Referenced by G4EmBiasingManager::ApplyRangeCut(), G4EmCalculator::FindEnergyLossProcess(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetEnergy(), GetRange(), GetRangeFromRestricteDEDX(), GetSubDEDX(), and G4VMultipleScattering::StartTracking().
const std::vector< G4VEnergyLossProcess * > & G4LossTableManager::GetEnergyLossProcessVector ()
Definition at line 987 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 987 of file G4LossTableManager.cc
References loss_vector.
Referenced by G4EmModelActivator::ActivatePAI(), G4EmCalculator::ComputeDEDXForCutInRange(), G4EmCalculator::ComputeElectronicDEDX(), DumpHtml(), and G4EmCalculator::FindEnLossProcess().
G4VEmProcess * G4LossTableManager::GetGammaGeneralProcess () inline
Definition at line 427 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 427 of file G4LossTableManager.hh
References gGeneral.
Referenced by G4BertiniElectroNuclearBuilder::Build(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), and G4EmExtraPhysics::ConstructProcess().
const std::vector< G4VMultipleScattering * > & G4LossTableManager::GetMultipleScatteringVector ()
Definition at line 1002 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1002 of file G4LossTableManager.cc
References msc_vector.
Referenced by DumpHtml(), and G4EmCalculator::FindMscProcess().
G4double G4LossTableManager::GetRange (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 351 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 351 of file G4LossTableManager.hh
References currentLoss, currentParticle, DBL_MAX, GetEnergyLossProcess(), and G4VEnergyLossProcess::GetRange().
Referenced by G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), PhysicsList::GetRange(), G4EnergyLossTables::GetRange(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), and G4EmSaturation::VisibleEnergyDeposition().
G4double G4LossTableManager::GetRangeFromRestricteDEDX (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 339 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 339 of file G4LossTableManager.hh
References currentLoss, currentParticle, DBL_MAX, GetEnergyLossProcess(), and G4VEnergyLossProcess::GetRangeForLoss().
Referenced by G4EmCalculator::GetRangeFromRestricteDEDX().
G4double G4LossTableManager::GetSubDEDX (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 317 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 317 of file G4LossTableManager.hh
References currentLoss, currentParticle, G4VEnergyLossProcess::GetDEDXForSubsec(), and GetEnergyLossProcess().
G4LossTableBuilder * G4LossTableManager::GetTableBuilder () inline
Definition at line 413 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 413 of file G4LossTableManager.hh
References tableBuilder.
Referenced by G4VEnergyLossProcess::BuildDEDXTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4VEmModel::G4VEmModel(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMscModel::GetParticleChangeForMSC(), G4GammaGeneralProcess::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VEnergyLossProcess::SetDEDXTable(), and G4VEnergyLossProcess::SetLambdaTable().
G4LossTableManager * G4LossTableManager::Instance (void) static
Definition at line 87 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 87 of file G4LossTableManager.cc
References G4ThreadLocalSingleton< T >::Instance(), and instance.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4EmModelActivator::ActivatePAI(), G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), PhysicsList::AddIonGasModels(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4EmBiasingManager::ApplyRangeCut(), G4BertiniElectroNuclearBuilder::Build(), G4EmCalculator::ComputeDEDXForCutInRange(), G4EmCalculator::ComputeElectronicDEDX(), PhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), BiasedRDPhysics::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), F04PhysicsList::F04PhysicsList(), G4AnnihiToMuPair::G4AnnihiToMuPair(), G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4BetheBlochModel::G4BetheBlochModel(), G4BraggModel::G4BraggModel(), G4EmCalculator::G4EmCalculator(), G4GammaConversionToMuons::G4GammaConversionToMuons(), G4GoudsmitSaundersonMscModel::G4GoudsmitSaundersonMscModel(), G4ionIonisation::G4ionIonisation(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4LindhardSorensenIonModel::G4LindhardSorensenIonModel(), G4MuBetheBlochModel::G4MuBetheBlochModel(), G4NIELCalculator::G4NIELCalculator(), G4SynchrotronRadiation::G4SynchrotronRadiation(), G4UAtomicDeexcitation::G4UAtomicDeexcitation(), G4UrbanAdjointMscModel::G4UrbanAdjointMscModel(), G4UrbanMscModel::G4UrbanMscModel(), G4UserSpecialCuts::G4UserSpecialCuts(), G4VEmFluctuationModel::G4VEmFluctuationModel(), G4VEmModel::G4VEmModel(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMultipleScattering::G4VMultipleScattering(), G4VTransitionRadiation::G4VTransitionRadiation(), GammaKnifePhysicsList::GammaKnifePhysicsList(), GammaRayTelPhysicsList::GammaRayTelPhysicsList(), G4EnergyLossTables::GetDEDX(), G4VMscModel::GetParticleChangeForMSC(), G4EnergyLossTables::GetPreciseDEDX(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4EnergyLossTables::GetPreciseRangeFromEnergy(), PhysicsList::GetRange(), G4EnergyLossTables::GetRange(), PHG4SteppingAction::GetVisibleEnergyDeposition(), HadrontherapyPhysicsList::HadrontherapyPhysicsList(), PHG4Reco::Init(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4PEEffectFluoModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4KleinNishinaModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4BraggIonModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), PHG4Reco::InitRun(), PhysicsList::PhysicsList(), PhysListEmStandardNR::PhysListEmStandardNR(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4ContinuousGainOfEnergy::SetDynamicMassCharge(), STCyclotronPhysicsList::STCyclotronPhysicsList(), UltraPhysicsList::UltraPhysicsList(), G4EmSaturation::VisibleEnergyDeposition(), XrayFluoPhysicsList::XrayFluoPhysicsList(), and G4AnnihiToMuPair::~G4AnnihiToMuPair().
G4bool G4LossTableManager::IsMaster () const inline
Definition at line 385 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 385 of file G4LossTableManager.hh
References isMaster.
Referenced by G4VMultipleScattering::BuildPhysicsTable(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
void G4LossTableManager::LocalPhysicsTables (const G4ParticleDefinition * aParticle, G4VEnergyLossProcess * p)
Definition at line 546 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 546 of file G4LossTableManager.cc
References all_tables_are_built, base_part_vector, G4VEnergyLossProcess::BaseParticle(), G4EmConfigurator::Clear(), currentParticle, dedx_vector, G4VEnergyLossProcess::DEDXTable(), emConfigurator, firstParticle, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), inv_range_vector, G4VEnergyLossProcess::InverseRangeTable(), isActive, G4VEnergyLossProcess::IsIonisationProcess(), loss_map, loss_vector, n_loss, part_vector, G4VEnergyLossProcess::Particle(), range_vector, G4VEnergyLossProcess::RangeTableForLoss(), run, startInitialisation, tables_are_built, and verbose.
Referenced by G4VEnergyLossProcess::BuildPhysicsTable().
G4NIELCalculator * G4LossTableManager::NIELCalculator ()
Definition at line 1046 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1046 of file G4LossTableManager.cc
References nielCalculator, and verbose.
G4LossTableManager& G4LossTableManager::operator= (const G4LossTableManager & right) private delete
void G4LossTableManager::ParticleHaveNoLoss (const G4ParticleDefinition * aParticle) private
Definition at line 967 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 967 of file G4LossTableManager.cc
References FatalException, G4Exception(), and G4ParticleDefinition::GetParticleName().
void G4LossTableManager::PreparePhysicsTable (const G4ParticleDefinition * aParticle, G4VEnergyLossProcess * p, G4bool theMaster)
Definition at line 438 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 438 of file G4LossTableManager.cc
References emConfigurator, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), isMaster, loss_vector, n_loss, part_vector, particle, G4EmConfigurator::PrepareModels(), ResetParameters(), run, startInitialisation, theGenericIon, and verbose.
Referenced by G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
void G4LossTableManager::PreparePhysicsTable (const G4ParticleDefinition * aParticle, G4VEmProcess * p, G4bool theMaster)
Definition at line 479 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 479 of file G4LossTableManager.cc
References emConfigurator, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), isMaster, G4EmConfigurator::PrepareModels(), ResetParameters(), run, startInitialisation, and verbose.
void G4LossTableManager::PreparePhysicsTable (const G4ParticleDefinition * aParticle, G4VMultipleScattering * p, G4bool theMaster)
Definition at line 507 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 507 of file G4LossTableManager.cc
References emConfigurator, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), isMaster, G4EmConfigurator::PrepareModels(), ResetParameters(), run, startInitialisation, and verbose.
void G4LossTableManager::PrintEWarning (G4String tit, G4double) private
Definition at line 1076 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1076 of file G4LossTableManager.cc
References G4Exception(), and JustWarning.
void G4LossTableManager::Register (G4VEnergyLossProcess * p)
Definition at line 197 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 197 of file G4LossTableManager.cc
References all_tables_are_built, base_part_vector, dedx_vector, G4cout, G4endl, G4VProcess::GetProcessName(), inv_range_vector, isActive, loss_vector, n_loss, part_vector, range_vector, tables_are_built, and verbose.
Referenced by G4AnnihiToMuPair::G4AnnihiToMuPair(), G4GammaConversionToMuons::G4GammaConversionToMuons(), G4SynchrotronRadiation::G4SynchrotronRadiation(), G4VEmFluctuationModel::G4VEmFluctuationModel(), G4VEmModel::G4VEmModel(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMultipleScattering::G4VMultipleScattering(), and G4VTransitionRadiation::G4VTransitionRadiation().
void G4LossTableManager::Register (G4VMultipleScattering * p)
Definition at line 253 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 253 of file G4LossTableManager.cc
References G4cout, G4endl, G4VProcess::GetProcessName(), msc_vector, n, and verbose.
void G4LossTableManager::Register (G4VEmProcess * p)
Definition at line 283 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 283 of file G4LossTableManager.cc
References emp_vector, G4cout, G4endl, G4VProcess::GetProcessName(), n, and verbose.
void G4LossTableManager::Register (G4VProcess * p)
Definition at line 313 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 313 of file G4LossTableManager.cc
References G4cout, G4endl, G4VProcess::GetProcessName(), n, p_vector, and verbose.
void G4LossTableManager::Register (G4VEmModel * p)
Definition at line 343 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 343 of file G4LossTableManager.cc
References G4cout, G4endl, G4VEmModel::GetName(), mod_vector, and verbose.
void G4LossTableManager::Register (G4VEmFluctuationModel * p)
Definition at line 368 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 368 of file G4LossTableManager.cc
References fmod_vector, G4cout, G4endl, G4VEmFluctuationModel::GetName(), and verbose.
void G4LossTableManager::RegisterExtraParticle (const G4ParticleDefinition * aParticle, G4VEnergyLossProcess * p)
Definition at line 389 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 389 of file G4LossTableManager.cc
References all_tables_are_built, base_part_vector, G4VEnergyLossProcess::BaseParticle(), dedx_vector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), inv_range_vector, loss_vector, n_loss, part_vector, range_vector, tables_are_built, and verbose.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
void G4LossTableManager::ResetParameters () private
Definition at line 221 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 221 of file G4LossTableManager.cc
References atomDeexcitation, emConfigurator, emCorrections, emElectronIonPair, G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), isMaster, G4LossTableBuilder::SetInitialisationFlag(), G4LossTableBuilder::SetSplineFlag(), G4EmConfigurator::SetVerbose(), G4ElectronIonPair::SetVerbose(), G4EmCorrections::SetVerbose(), G4VAtomDeexcitation::SetVerboseLevel(), G4EmParameters::Spline(), tableBuilder, theParameters, G4EmParameters::Verbose(), verbose, and G4EmParameters::WorkerVerbose().
Referenced by PreparePhysicsTable().
void G4LossTableManager::SetAtomDeexcitation (G4VAtomDeexcitation * p)
Definition at line 1056 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1056 of file G4LossTableManager.cc
References atomDeexcitation.
Referenced by PhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), BiasedRDPhysics::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), and G4EmStandardPhysics_option2::ConstructProcess().
void G4LossTableManager::SetElectronGeneralProcess (G4VEnergyLossProcess * ptr) inline
Definition at line 435 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 435 of file G4LossTableManager.hh
References eGeneral.
void G4LossTableManager::SetGammaGeneralProcess (G4VEmProcess * ptr) inline
Definition at line 420 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 420 of file G4LossTableManager.hh
References gGeneral.
Referenced by G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), and G4EmStandardPhysics_option2::ConstructProcess().
void G4LossTableManager::SetNIELCalculator (G4NIELCalculator * ptr)
Definition at line 1036 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1036 of file G4LossTableManager.cc
References nielCalculator.
Referenced by G4NIELCalculator::G4NIELCalculator().
void G4LossTableManager::SetSubCutProducer (G4VSubCutProducer * p)
Definition at line 1066 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 1066 of file G4LossTableManager.cc
References subcutProducer.
void G4LossTableManager::SetVerbose (G4int val)
Definition at line 979 of file G4LossTableManager.cc.
View newest version in sPHENIX GitHub at line 979 of file G4LossTableManager.cc
References verbose.
Referenced by PHG4Reco::InitRun(), and XrayFluoPhysicsList::XrayFluoPhysicsList().
G4VSubCutProducer * G4LossTableManager::SubCutProducer () inline
Definition at line 406 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 406 of file G4LossTableManager.hh
References subcutProducer.
Referenced by G4VEnergyLossProcess::BuildPhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4LossTableManager > friend
Definition at line 79 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 79 of file G4LossTableManager.hh
Member Data Documentation
G4bool G4LossTableManager::all_tables_are_built private
Definition at line 284 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 284 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), Clear(), G4LossTableManager(), LocalPhysicsTables(), Register(), and RegisterExtraParticle().
G4VAtomDeexcitation* G4LossTableManager::atomDeexcitation private
Definition at line 292 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 292 of file G4LossTableManager.hh
Referenced by AtomDeexcitation(), BuildPhysicsTable(), G4LossTableManager(), ResetParameters(), SetAtomDeexcitation(), and ~G4LossTableManager().
std::vector<PD> G4LossTableManager::base_part_vector private
Definition at line 262 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 262 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), Clear(), CopyTables(), LocalPhysicsTables(), Register(), and RegisterExtraParticle().
G4VEnergyLossProcess* G4LossTableManager::currentLoss private
Definition at line 275 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 275 of file G4LossTableManager.hh
Referenced by Clear(), G4LossTableManager(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetEnergy(), GetEnergyLossProcess(), GetRange(), GetRangeFromRestricteDEDX(), and GetSubDEDX().
PD G4LossTableManager::currentParticle private
Definition at line 276 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 276 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), Clear(), G4LossTableManager(), GetCSDARange(), GetDEDX(), GetDEDXDispersion(), GetEnergy(), GetEnergyLossProcess(), GetRange(), GetRangeFromRestricteDEDX(), GetSubDEDX(), and LocalPhysicsTables().
std::vector<G4PhysicsTable*> G4LossTableManager::dedx_vector private
Definition at line 265 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 265 of file G4LossTableManager.hh
Referenced by BuildTables(), Clear(), LocalPhysicsTables(), Register(), and RegisterExtraParticle().
G4VEnergyLossProcess* G4LossTableManager::eGeneral private
Definition at line 297 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 297 of file G4LossTableManager.hh
Referenced by G4LossTableManager(), GetElectronGeneralProcess(), and SetElectronGeneralProcess().
G4EmConfigurator* G4LossTableManager::emConfigurator private
Definition at line 289 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 289 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), EmConfigurator(), G4LossTableManager(), LocalPhysicsTables(), PreparePhysicsTable(), ResetParameters(), and ~G4LossTableManager().
G4EmCorrections* G4LossTableManager::emCorrections private
Definition at line 288 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 288 of file G4LossTableManager.hh
Referenced by EmCorrections(), G4LossTableManager(), ResetParameters(), and ~G4LossTableManager().
G4ElectronIonPair* G4LossTableManager::emElectronIonPair private
Definition at line 290 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 290 of file G4LossTableManager.hh
Referenced by ElectronIonPair(), G4LossTableManager(), ResetParameters(), and ~G4LossTableManager().
std::vector<G4VEmProcess*> G4LossTableManager::emp_vector private
Definition at line 269 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 269 of file G4LossTableManager.hh
Referenced by DeRegister(), GetEmProcessVector(), Register(), and ~G4LossTableManager().
PD G4LossTableManager::firstParticle private
Definition at line 279 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 279 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), G4LossTableManager(), and LocalPhysicsTables().
std::vector<G4VEmFluctuationModel*> G4LossTableManager::fmod_vector private
Definition at line 271 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 271 of file G4LossTableManager.hh
Referenced by DeRegister(), Register(), and ~G4LossTableManager().
G4VEmProcess* G4LossTableManager::gGeneral private
Definition at line 296 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 296 of file G4LossTableManager.hh
Referenced by G4LossTableManager(), GetGammaGeneralProcess(), and SetGammaGeneralProcess().
G4ThreadLocal G4LossTableManager * G4LossTableManager::instance = nullptr static private
Definition at line 254 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 254 of file G4LossTableManager.hh
Referenced by Instance().
std::vector<G4PhysicsTable*> G4LossTableManager::inv_range_vector private
Definition at line 267 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 267 of file G4LossTableManager.hh
Referenced by BuildTables(), Clear(), CopyTables(), LocalPhysicsTables(), Register(), and RegisterExtraParticle().
std::vector<G4bool> G4LossTableManager::isActive private
Definition at line 264 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 264 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), BuildTables(), Clear(), LocalPhysicsTables(), and Register().
G4bool G4LossTableManager::isMaster private
Definition at line 286 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 286 of file G4LossTableManager.hh
Referenced by G4LossTableManager(), IsMaster(), PreparePhysicsTable(), and ResetParameters().
std::map<PD,G4VEnergyLossProcess*,std::less<PD> > G4LossTableManager::loss_map private
Definition at line 258 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 258 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), Clear(), CopyTables(), GetEnergyLossProcess(), and LocalPhysicsTables().
std::vector<G4VEnergyLossProcess*> G4LossTableManager::loss_vector private
Definition at line 260 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 260 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), BuildTables(), Clear(), CopyTables(), DeRegister(), GetEnergyLossProcessVector(), LocalPhysicsTables(), PreparePhysicsTable(), Register(), RegisterExtraParticle(), and ~G4LossTableManager().
std::vector<G4VEmModel*> G4LossTableManager::mod_vector private
Definition at line 270 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 270 of file G4LossTableManager.hh
Referenced by DeRegister(), Register(), and ~G4LossTableManager().
std::vector<G4VMultipleScattering*> G4LossTableManager::msc_vector private
Definition at line 268 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 268 of file G4LossTableManager.hh
Referenced by DeRegister(), GetMultipleScatteringVector(), Register(), and ~G4LossTableManager().
G4int G4LossTableManager::n_loss private
Definition at line 281 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 281 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), BuildTables(), Clear(), CopyTables(), DeRegister(), G4LossTableManager(), LocalPhysicsTables(), PreparePhysicsTable(), Register(), RegisterExtraParticle(), and ~G4LossTableManager().
G4NIELCalculator* G4LossTableManager::nielCalculator private
Definition at line 291 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 291 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), G4LossTableManager(), NIELCalculator(), SetNIELCalculator(), and ~G4LossTableManager().
std::vector<G4VProcess*> G4LossTableManager::p_vector private
Definition at line 272 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 272 of file G4LossTableManager.hh
Referenced by DeRegister(), Register(), and ~G4LossTableManager().
std::vector<PD> G4LossTableManager::part_vector private
Definition at line 261 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 261 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), BuildTables(), Clear(), CopyTables(), LocalPhysicsTables(), PreparePhysicsTable(), Register(), and RegisterExtraParticle().
std::vector<G4PhysicsTable*> G4LossTableManager::range_vector private
Definition at line 266 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 266 of file G4LossTableManager.hh
Referenced by BuildTables(), Clear(), CopyTables(), LocalPhysicsTables(), Register(), and RegisterExtraParticle().
G4int G4LossTableManager::run private
Definition at line 282 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 282 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), G4LossTableManager(), LocalPhysicsTables(), and PreparePhysicsTable().
G4bool G4LossTableManager::startInitialisation private
Definition at line 285 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 285 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), G4LossTableManager(), LocalPhysicsTables(), and PreparePhysicsTable().
G4VSubCutProducer* G4LossTableManager::subcutProducer private
Definition at line 293 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 293 of file G4LossTableManager.hh
Referenced by BuildTables(), G4LossTableManager(), SetSubCutProducer(), SubCutProducer(), and ~G4LossTableManager().
G4LossTableBuilder* G4LossTableManager::tableBuilder private
Definition at line 287 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 287 of file G4LossTableManager.hh
Referenced by BuildTables(), G4LossTableManager(), GetTableBuilder(), ResetParameters(), and ~G4LossTableManager().
std::vector<G4bool> G4LossTableManager::tables_are_built private
Definition at line 263 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 263 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), BuildTables(), Clear(), CopyTables(), LocalPhysicsTables(), Register(), and RegisterExtraParticle().
PD G4LossTableManager::theElectron private
Definition at line 277 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 277 of file G4LossTableManager.hh
Referenced by CopyTables(), and G4LossTableManager().
PD G4LossTableManager::theGenericIon private
Definition at line 278 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 278 of file G4LossTableManager.hh
Referenced by G4LossTableManager(), GetEnergyLossProcess(), and PreparePhysicsTable().
G4EmParameters* G4LossTableManager::theParameters private
Definition at line 295 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 295 of file G4LossTableManager.hh
Referenced by BuildTables(), EmSaturation(), G4LossTableManager(), and ResetParameters().
G4int G4LossTableManager::verbose private
Definition at line 299 of file G4LossTableManager.hh.
View newest version in sPHENIX GitHub at line 299 of file G4LossTableManager.hh
Referenced by BuildPhysicsTable(), BuildTables(), CopyTables(), ElectronIonPair(), EmConfigurator(), G4LossTableManager(), LocalPhysicsTables(), NIELCalculator(), PreparePhysicsTable(), Register(), RegisterExtraParticle(), ResetParameters(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4LossTableManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4LossTableManager.cc