ECCE @ EIC Software: G4ChipsKaonPlusInelasticXS Class Reference
G4ChipsKaonPlusInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonPlusInelasticXS.hh>
Public Member Functions
G4ChipsKaonPlusInelasticXS ()
~G4ChipsKaonPlusInelasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
virtual G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
G4double CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum)
G4int GetFunctions (G4int tZ, G4int tN, G4double *y, G4double *z)
G4double CrossSectionLin (G4int targZ, G4int targN, G4double P)
G4double CrossSectionLog (G4int targZ, G4int targN, G4double lP)
G4double CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP)
G4double ThresholdMomentum (G4int targZ, G4int targN)
G4double EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double *Y)
Private Attributes
G4double lastSig
G4double * lastLEN
G4double * lastHEN
G4double lastE
G4int lastPDG
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
std::vector< G4double * > * LEN
std::vector< G4double * > * HEN
G4int j
std::vector< G4int > colN
std::vector< G4int > colZ
std::vector< G4double > colP
std::vector< G4double > colTH
std::vector< G4double > colCS
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 47 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ChipsKaonPlusInelasticXS.hh
Constructor & Destructor Documentation
G4ChipsKaonPlusInelasticXS::G4ChipsKaonPlusInelasticXS ()
Definition at line 75 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ChipsKaonPlusInelasticXS.cc
References G4ParticleDefinition::GetPDGMass(), HEN, G4KaonPlus::KaonPlus(), lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, LEN, G4PionPlus::PionPlus(), G4Proton::Proton(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4ChipsKaonPlusInelasticXS::~G4ChipsKaonPlusInelasticXS ()
Definition at line 96 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ChipsKaonPlusInelasticXS.cc
References HEN, and LEN.
Member Function Documentation
G4double G4ChipsKaonPlusInelasticXS::CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum) private
Definition at line 212 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 212 of file G4ChipsKaonPlusInelasticXS.cc
References A(), CrossSectionFormula(), CrossSectionLin(), CrossSectionLog(), EquLinearFit(), G4cerr, G4endl, HEN, k, lastHEN, lastLEN, lastTH, LEN, n, nH, nL, and P.
Referenced by GetChipsCrossSection().
void G4ChipsKaonPlusInelasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 108 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 108 of file G4ChipsKaonPlusInelasticXS.cc
G4double G4ChipsKaonPlusInelasticXS::CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP) private
Definition at line 308 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 308 of file G4ChipsKaonPlusInelasticXS.cc
References a, c, d, f, G4cerr, G4endl, Acts::UnitConstants::h, P, r, G4InuclParticleNames::sp, t, Acts::UnitConstants::u, v, w, and y.
Referenced by CalculateCrossSection(), CrossSectionLin(), and CrossSectionLog().
G4double G4ChipsKaonPlusInelasticXS::CrossSectionLin (G4int targZ, G4int targN, G4double P) private
Definition at line 295 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 295 of file G4ChipsKaonPlusInelasticXS.cc
References CrossSectionFormula().
Referenced by CalculateCrossSection().
G4double G4ChipsKaonPlusInelasticXS::CrossSectionLog (G4int targZ, G4int targN, G4double lP) private
Definition at line 302 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 302 of file G4ChipsKaonPlusInelasticXS.cc
References CrossSectionFormula(), and P.
Referenced by CalculateCrossSection().
static const char* G4ChipsKaonPlusInelasticXS::Default_Name () inline static
Definition at line 56 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by LBE::ConstructHad(), GammaRayTelHadronPhysics::ConstructProcess(), G4ChipsComponentXS::G4ChipsComponentXS(), and G4ChipsKaonZeroInelasticXS::G4ChipsKaonZeroInelasticXS().
G4double G4ChipsKaonPlusInelasticXS::EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double * Y) private
Definition at line 374 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 374 of file G4ChipsKaonPlusInelasticXS.cc
References d, G4cerr, and G4endl.
Referenced by CalculateCrossSection().
G4double G4ChipsKaonPlusInelasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg) virtual
!The slave functions must provide cross-sections in millibarns (mb) !! (not in IU)
Definition at line 137 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 137 of file G4ChipsKaonPlusInelasticXS.cc
References CalculateCrossSection(), colCS, colN, colP, colTH, colZ, in, j, lastCS, lastI, lastN, lastP, lastTH, lastZ, and millibarn.
Referenced by G4ChipsKaonZeroInelasticXS::GetChipsCrossSection(), and GetIsoCrossSection().
G4int G4ChipsKaonPlusInelasticXS::GetFunctions (G4int tZ, G4int tN, G4double * y, G4double * z) private
G4double G4ChipsKaonPlusInelasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 126 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ChipsKaonPlusInelasticXS.cc
References GetChipsCrossSection(), and G4DynamicParticle::GetTotalMomentum().
G4bool G4ChipsKaonPlusInelasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 116 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 116 of file G4ChipsKaonPlusInelasticXS.cc
G4double G4ChipsKaonPlusInelasticXS::ThresholdMomentum (G4int targZ, G4int targN) private
Definition at line 281 of file G4ChipsKaonPlusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 281 of file G4ChipsKaonPlusInelasticXS.cc
References dE, and T.
Member Data Documentation
std::vector<G4double> G4ChipsKaonPlusInelasticXS::colCS private
Definition at line 103 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsKaonPlusInelasticXS::colN private
Definition at line 99 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsKaonPlusInelasticXS::colP private
Definition at line 101 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsKaonPlusInelasticXS::colTH private
Definition at line 102 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsKaonPlusInelasticXS::colZ private
Definition at line 100 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double*>* G4ChipsKaonPlusInelasticXS::HEN private
Definition at line 96 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsKaonPlusInelasticXS(), and ~G4ChipsKaonPlusInelasticXS().
G4int G4ChipsKaonPlusInelasticXS::j private
Definition at line 98 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by GetChipsCrossSection().
G4double G4ChipsKaonPlusInelasticXS::lastCS private
Definition at line 93 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by G4ChipsKaonPlusInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsKaonPlusInelasticXS::lastE private
Definition at line 87 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsKaonPlusInelasticXS.hh
G4double* G4ChipsKaonPlusInelasticXS::lastHEN private
Definition at line 86 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsKaonPlusInelasticXS().
G4int G4ChipsKaonPlusInelasticXS::lastI private
Definition at line 94 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by G4ChipsKaonPlusInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsKaonPlusInelasticXS::lastLEN private
Definition at line 85 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsKaonPlusInelasticXS().
G4int G4ChipsKaonPlusInelasticXS::lastN private
Definition at line 89 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by G4ChipsKaonPlusInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsKaonPlusInelasticXS::lastP private
Definition at line 91 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by G4ChipsKaonPlusInelasticXS(), and GetChipsCrossSection().
G4int G4ChipsKaonPlusInelasticXS::lastPDG private
Definition at line 88 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsKaonPlusInelasticXS.hh
G4double G4ChipsKaonPlusInelasticXS::lastSig private
Definition at line 84 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsKaonPlusInelasticXS.hh
G4double G4ChipsKaonPlusInelasticXS::lastTH private
Definition at line 92 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsKaonPlusInelasticXS(), and GetChipsCrossSection().
G4int G4ChipsKaonPlusInelasticXS::lastZ private
Definition at line 90 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by G4ChipsKaonPlusInelasticXS(), and GetChipsCrossSection().
std::vector<G4double*>* G4ChipsKaonPlusInelasticXS::LEN private
Definition at line 95 of file G4ChipsKaonPlusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChipsKaonPlusInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsKaonPlusInelasticXS(), and ~G4ChipsKaonPlusInelasticXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonPlusInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsKaonPlusInelasticXS.cc