ECCE @ EIC Software: G4BohrFluctuations Class Reference
G4BohrFluctuations Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4BohrFluctuations.hh>
Public Member Functions
G4BohrFluctuations (const G4String &nam="BohrFluc")
virtual ~G4BohrFluctuations ()
virtual G4double SampleFluctuations (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double, G4double, G4double) override
virtual G4double Dispersion (const G4Material *, const G4DynamicParticle *, G4double, G4double) override
virtual void InitialiseMe (const G4ParticleDefinition *) override
Public Member Functions inherited from G4VEmFluctuationModel
G4VEmFluctuationModel (const G4String &nam)
virtual ~G4VEmFluctuationModel ()
virtual void SetParticleAndCharge (const G4ParticleDefinition *, G4double q2)
const G4String & GetName () const
Private Member Functions
G4BohrFluctuations & operator= (const G4BohrFluctuations &right)=delete
G4BohrFluctuations (const G4BohrFluctuations &)=delete
Private Attributes
const G4ParticleDefinition * particle
G4double particleMass
G4double chargeSquare
G4double minNumberInteractionsBohr
G4double minFraction
G4double xmin
G4double minLoss
G4double kineticEnergy
G4double beta2
Detailed Description
Definition at line 57 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 57 of file G4BohrFluctuations.hh
Constructor & Destructor Documentation
G4BohrFluctuations::G4BohrFluctuations (const G4String & nam = "BohrFluc") explicit
Definition at line 63 of file G4BohrFluctuations.cc.
View newest version in sPHENIX GitHub at line 63 of file G4BohrFluctuations.cc
References beta2, chargeSquare, kineticEnergy, particleMass, and source.hepunit::proton_mass_c2.
G4BohrFluctuations::~G4BohrFluctuations () virtual
Definition at line 79 of file G4BohrFluctuations.cc.
View newest version in sPHENIX GitHub at line 79 of file G4BohrFluctuations.cc
G4BohrFluctuations::G4BohrFluctuations (const G4BohrFluctuations &) private delete
Member Function Documentation
G4double G4BohrFluctuations::Dispersion (const G4Material * material, const G4DynamicParticle * dp, G4double tmax, G4double length) override virtual
Implements G4VEmFluctuationModel.
Definition at line 149 of file G4BohrFluctuations.cc.
View newest version in sPHENIX GitHub at line 149 of file G4BohrFluctuations.cc
References beta2, chargeSquare, G4DynamicParticle::GetDefinition(), G4Material::GetElectronDensity(), G4DynamicParticle::GetKineticEnergy(), InitialiseMe(), kineticEnergy, particle, particleMass, and source.hepunit::twopi_mc2_rcl2.
Referenced by SampleFluctuations().
void G4BohrFluctuations::InitialiseMe (const G4ParticleDefinition * part) override virtual
Reimplemented from G4VEmFluctuationModel.
Definition at line 84 of file G4BohrFluctuations.cc.
View newest version in sPHENIX GitHub at line 84 of file G4BohrFluctuations.cc
References chargeSquare, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), part, particle, and particleMass.
Referenced by Dispersion().
G4BohrFluctuations& G4BohrFluctuations::operator= (const G4BohrFluctuations & right) private delete
G4double G4BohrFluctuations::SampleFluctuations (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmax, G4double length, G4double meanLoss) override virtual
Implements G4VEmFluctuationModel.
Definition at line 95 of file G4BohrFluctuations.cc.
View newest version in sPHENIX GitHub at line 95 of file G4BohrFluctuations.cc
References beta2, Dispersion(), G4Poisson(), G4UniformRand, G4InuclParticleNames::gam, G4MaterialCutsCouple::GetMaterial(), kineticEnergy, material(), minFraction, minLoss, minNumberInteractionsBohr, n, particleMass, G4INCL::DeJongSpin::shoot(), x, x3, and xmin.
Member Data Documentation
G4double G4BohrFluctuations::beta2 private
Definition at line 93 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BohrFluctuations.hh
Referenced by Dispersion(), G4BohrFluctuations(), and SampleFluctuations().
G4double G4BohrFluctuations::chargeSquare private
Definition at line 85 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BohrFluctuations.hh
Referenced by Dispersion(), G4BohrFluctuations(), and InitialiseMe().
G4double G4BohrFluctuations::kineticEnergy private
Definition at line 92 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BohrFluctuations.hh
Referenced by Dispersion(), G4BohrFluctuations(), and SampleFluctuations().
G4double G4BohrFluctuations::minFraction private
Definition at line 88 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 88 of file G4BohrFluctuations.hh
Referenced by SampleFluctuations().
G4double G4BohrFluctuations::minLoss private
Definition at line 90 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BohrFluctuations.hh
Referenced by SampleFluctuations().
G4double G4BohrFluctuations::minNumberInteractionsBohr private
Definition at line 87 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 87 of file G4BohrFluctuations.hh
Referenced by SampleFluctuations().
const G4ParticleDefinition* G4BohrFluctuations::particle private
Definition at line 82 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 82 of file G4BohrFluctuations.hh
Referenced by Dispersion(), and InitialiseMe().
G4double G4BohrFluctuations::particleMass private
Definition at line 84 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 84 of file G4BohrFluctuations.hh
Referenced by Dispersion(), G4BohrFluctuations(), InitialiseMe(), and SampleFluctuations().
G4double G4BohrFluctuations::xmin private
Definition at line 89 of file G4BohrFluctuations.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BohrFluctuations.hh
Referenced by SampleFluctuations().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4BohrFluctuations.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4BohrFluctuations.cc