ECCE @ EIC Software: G4ErrorFreeTrajParam Class Reference
G4ErrorFreeTrajParam Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorFreeTrajParam.hh>
Public Member Functions
G4ErrorFreeTrajParam ()
G4ErrorFreeTrajParam (const G4Point3D &pos, const G4Vector3D &mom)
virtual ~G4ErrorFreeTrajParam ()
void Update (const G4Track *aTrack)
void SetParameters (const G4Point3D &pos, const G4Vector3D &mom)
G4Vector3D GetDirection () const
G4double GetInvP () const
G4double GetLambda () const
G4double GetPhi () const
G4double GetYPerp () const
G4double GetZPerp () const
Private Attributes
G4Vector3D fDir
G4double fInvP
G4double fLambda
G4double fPhi
G4double fYPerp
G4double fZPerp
Friends
std::ostream & operator<< (std::ostream &, const G4ErrorFreeTrajParam &ts)
Detailed Description
Definition at line 48 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ErrorFreeTrajParam.hh
Constructor & Destructor Documentation
G4ErrorFreeTrajParam::G4ErrorFreeTrajParam () inline
Definition at line 52 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ErrorFreeTrajParam.hh
G4ErrorFreeTrajParam::G4ErrorFreeTrajParam (const G4Point3D & pos, const G4Vector3D & mom)
Definition at line 39 of file G4ErrorFreeTrajParam.cc.
View newest version in sPHENIX GitHub at line 39 of file G4ErrorFreeTrajParam.cc
References SetParameters().
virtual G4ErrorFreeTrajParam::~G4ErrorFreeTrajParam () inline virtual
Definition at line 57 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ErrorFreeTrajParam.hh
Member Function Documentation
G4Vector3D G4ErrorFreeTrajParam::GetDirection () const inline
Definition at line 69 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ErrorFreeTrajParam.hh
References fDir.
Referenced by G4ErrorFreeTrajState::G4ErrorFreeTrajState().
G4double G4ErrorFreeTrajParam::GetInvP () const inline
Definition at line 71 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ErrorFreeTrajParam.hh
References fInvP.
G4double G4ErrorFreeTrajParam::GetLambda () const inline
Definition at line 72 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ErrorFreeTrajParam.hh
References fLambda.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), and G4ErrorFreeTrajState::G4ErrorFreeTrajState().
G4double G4ErrorFreeTrajParam::GetPhi () const inline
Definition at line 73 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ErrorFreeTrajParam.hh
References fPhi.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), and G4ErrorFreeTrajState::G4ErrorFreeTrajState().
G4double G4ErrorFreeTrajParam::GetYPerp () const inline
Definition at line 74 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ErrorFreeTrajParam.hh
References fYPerp.
G4double G4ErrorFreeTrajParam::GetZPerp () const inline
Definition at line 75 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ErrorFreeTrajParam.hh
References fZPerp.
void G4ErrorFreeTrajParam::SetParameters (const G4Point3D & pos, const G4Vector3D & mom)
Definition at line 47 of file G4ErrorFreeTrajParam.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ErrorFreeTrajParam.cc
References HepGeom::BasicVector3D< T >::cross(), deg, CLHEP::Hep3Vector::dot(), fDir, fInvP, fLambda, fPhi, fYPerp, fZPerp, HepGeom::BasicVector3D< T >::mag(), HepGeom::BasicVector3D< T >::phi(), HepGeom::BasicVector3D< T >::theta(), HepGeom::BasicVector3D< T >::x(), and HepGeom::BasicVector3D< T >::y().
Referenced by G4ErrorFreeTrajParam(), G4ErrorFreeTrajState::SetParameters(), and Update().
void G4ErrorFreeTrajParam::Update (const G4Track * aTrack)
Definition at line 78 of file G4ErrorFreeTrajParam.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ErrorFreeTrajParam.cc
References G4Track::GetMomentum(), G4Track::GetPosition(), and SetParameters().
Referenced by G4ErrorFreeTrajState::Update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4ErrorFreeTrajParam & ts) friend
Definition at line 86 of file G4ErrorFreeTrajParam.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ErrorFreeTrajParam.cc
Member Data Documentation
G4Vector3D G4ErrorFreeTrajParam::fDir private
Definition at line 79 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ErrorFreeTrajParam.hh
Referenced by GetDirection(), operator<<(), and SetParameters().
G4double G4ErrorFreeTrajParam::fInvP private
Definition at line 80 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ErrorFreeTrajParam.hh
Referenced by GetInvP(), operator<<(), and SetParameters().
G4double G4ErrorFreeTrajParam::fLambda private
Definition at line 81 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ErrorFreeTrajParam.hh
Referenced by GetLambda(), operator<<(), and SetParameters().
G4double G4ErrorFreeTrajParam::fPhi private
Definition at line 82 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ErrorFreeTrajParam.hh
Referenced by GetPhi(), operator<<(), and SetParameters().
G4double G4ErrorFreeTrajParam::fYPerp private
Definition at line 83 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ErrorFreeTrajParam.hh
Referenced by GetYPerp(), operator<<(), and SetParameters().
G4double G4ErrorFreeTrajParam::fZPerp private
Definition at line 84 of file G4ErrorFreeTrajParam.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ErrorFreeTrajParam.hh
Referenced by GetZPerp(), operator<<(), and SetParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorFreeTrajParam.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorFreeTrajParam.cc