ECCE @ EIC Software: GB06ParallelWorldForSlices Class Reference
GB06ParallelWorldForSlices Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB06/include/GB06ParallelWorldForSlices.hh>
Public Member Functions
GB06ParallelWorldForSlices (G4String worldName)
~GB06ParallelWorldForSlices ()
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Member Functions
virtual void Construct ()
virtual void ConstructSD ()
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 36 of file GB06ParallelWorldForSlices.hh.
View newest version in sPHENIX GitHub at line 36 of file GB06ParallelWorldForSlices.hh
Constructor & Destructor Documentation
GB06ParallelWorldForSlices::GB06ParallelWorldForSlices (G4String worldName)
Definition at line 45 of file GB06ParallelWorldForSlices.cc.
View newest version in sPHENIX GitHub at line 45 of file GB06ParallelWorldForSlices.cc
GB06ParallelWorldForSlices::~GB06ParallelWorldForSlices ()
Definition at line 51 of file GB06ParallelWorldForSlices.cc.
View newest version in sPHENIX GitHub at line 51 of file GB06ParallelWorldForSlices.cc
Member Function Documentation
void GB06ParallelWorldForSlices::Construct (void) private virtual
Implements G4VUserParallelWorld.
Definition at line 56 of file GB06ParallelWorldForSlices.cc.
View newest version in sPHENIX GitHub at line 56 of file GB06ParallelWorldForSlices.cc
References G4VUserParallelWorld::fWorldName, G4cout, G4endl, G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetObjectTranslation(), G4LogicalVolume::GetSolid(), G4LogicalVolumeStore::GetVolume(), G4PhysicalVolumeStore::GetVolume(), G4VUserParallelWorld::GetWorld(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), and kZAxis.
void GB06ParallelWorldForSlices::ConstructSD () private virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 158 of file GB06ParallelWorldForSlices.cc.
View newest version in sPHENIX GitHub at line 158 of file GB06ParallelWorldForSlices.cc
References G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4PVReplica::GetMultiplicity(), G4LogicalVolumeStore::GetVolume(), G4PhysicalVolumeStore::GetVolume(), and G4VUserParallelWorld::GetWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB06/include/GB06ParallelWorldForSlices.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB06/src/GB06ParallelWorldForSlices.cc