ECCE @ EIC Software: G4PVPlacement Class Reference
G4PVPlacement Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4PVPlacement.hh>
Public Member Functions
G4PVPlacement (G4RotationMatrix *pRot, const G4ThreeVector &tlate, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (const G4Transform3D &Transform3D, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (const G4Transform3D &Transform3D, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
virtual ~G4PVPlacement ()
G4int GetCopyNo () const
void SetCopyNo (G4int CopyNo)
G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int maxErr=1)
G4PVPlacement (__void__ &)
G4PVPlacement (const G4PVPlacement &)=delete
G4PVPlacement & operator= (const G4PVPlacement &)=delete
G4bool IsMany () const
G4bool IsReplicated () const
G4bool IsParameterised () const
G4VPVParameterisation * GetParameterisation () const
void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const
G4bool IsRegularStructure () const
G4int GetRegularStructureId () const
EVolume VolumeType () const
Public Member Functions inherited from G4VPhysicalVolume
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4VPhysicalVolume (const G4VPhysicalVolume &)=delete
G4VPhysicalVolume & operator= (const G4VPhysicalVolume &)=delete
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
virtual G4int GetMultiplicity () const
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
EVolume DeduceVolumeType () const
Static Private Member Functions
static G4RotationMatrix * NewPtrRotMatrix (const G4RotationMatrix &RotMat)
Private Attributes
G4bool fmany = false
G4bool fallocatedRotM = false
G4int fcopyNo = 0
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicalVolume
static const G4PVManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions inherited from G4VPhysicalVolume
void InitialiseWorker (G4VPhysicalVolume *pMasterObject, G4RotationMatrix *pRot, const G4ThreeVector &tlate)
void TerminateWorker (G4VPhysicalVolume *pMasterObject)
Protected Attributes inherited from G4VPhysicalVolume
G4int instanceID
Static Protected Attributes inherited from G4VPhysicalVolume
static G4GEOM_DLL G4PVManager subInstanceManager
Detailed Description
Definition at line 43 of file G4PVPlacement.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PVPlacement.hh
Constructor & Destructor Documentation
G4PVPlacement::G4PVPlacement (G4RotationMatrix * pRot, const G4ThreeVector & tlate, G4LogicalVolume * pCurrentLogical, const G4String & pName, G4LogicalVolume * pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 96 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 96 of file G4PVPlacement.cc
References G4LogicalVolume::AddDaughter(), CheckOverlaps(), FatalException, G4Exception(), and G4VPhysicalVolume::SetMotherLogical().
Referenced by LXeMainVolume::LXeMainVolume(), LXeWLSFiber::LXeWLSFiber(), and LXeMainVolume::PlacePMTs().
G4PVPlacement::G4PVPlacement (const G4Transform3D & Transform3D, G4LogicalVolume * pCurrentLogical, const G4String & pName, G4LogicalVolume * pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 121 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 121 of file G4PVPlacement.cc
References G4LogicalVolume::AddDaughter(), CheckOverlaps(), fallocatedRotM, FatalException, G4Exception(), G4VPhysicalVolume::GetRotation(), HepGeom::Transform3D::getRotation(), CLHEP::HepRotation::inverse(), NewPtrRotMatrix(), G4VPhysicalVolume::SetMotherLogical(), and G4VPhysicalVolume::SetRotation().
G4PVPlacement::G4PVPlacement (G4RotationMatrix * pRot, const G4ThreeVector & tlate, const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 39 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 39 of file G4PVPlacement.cc
References G4LogicalVolume::AddDaughter(), CheckOverlaps(), FatalException, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), and G4VPhysicalVolume::SetMotherLogical().
G4PVPlacement::G4PVPlacement (const G4Transform3D & Transform3D, const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk = false)
Definition at line 67 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PVPlacement.cc
References G4LogicalVolume::AddDaughter(), CheckOverlaps(), fallocatedRotM, FatalException, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetRotation(), and G4VPhysicalVolume::SetMotherLogical().
G4PVPlacement::~G4PVPlacement () virtual
Definition at line 156 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 156 of file G4PVPlacement.cc
References fallocatedRotM, and G4VPhysicalVolume::GetRotation().
G4PVPlacement::G4PVPlacement (__void__ & a)
Definition at line 148 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 148 of file G4PVPlacement.cc
G4PVPlacement::G4PVPlacement (const G4PVPlacement &) delete
Member Function Documentation
G4bool G4PVPlacement::CheckOverlaps (G4int res = 1000, G4double tol = 0., G4bool verbose = true, G4int maxErr = 1) virtual
Reimplemented from G4VPhysicalVolume.
Definition at line 243 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 243 of file G4PVPlacement.cc
References G4VSolid::BoundingLimits(), G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), G4BestUnit, G4cout, G4endl, G4Exception(), GetCopyNo(), G4VPhysicalVolume::GetCopyNo(), G4LogicalVolume::GetDaughter(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4VSolid::GetPointOnSurface(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4VPhysicalVolume::GetTranslation(), G4VSolid::Inside(), G4AffineTransform::InverseTransformPoint(), JustWarning, k, kInfinity, kInside, kOutside, kSurface, max, message(), min, offset, G4AffineTransform::TransformPoint(), CLHEP::Hep3Vector::x(), x, xmax, xmin, CLHEP::Hep3Vector::y(), y, ymax, ymin, CLHEP::Hep3Vector::z(), and z.
Referenced by export_G4PVPlacement(), and G4PVPlacement().
G4int G4PVPlacement::GetCopyNo () const inline virtual
Implements G4VPhysicalVolume.
Definition at line 117 of file G4PVPlacement.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PVPlacement.hh
References fcopyNo.
Referenced by CheckOverlaps(), PHG4TTLDetector::RegisterPhysicalVolume(), PHG4Sector::PHG4SectorConstructor::RegisterPhysicalVolume(), and ePHENIXRICH::ePHENIXRICHConstruction::RegisterPhysicalVolume().
G4VPVParameterisation * G4PVPlacement::GetParameterisation () const virtual
Implements G4VPhysicalVolume.
Definition at line 196 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 196 of file G4PVPlacement.cc
G4int G4PVPlacement::GetRegularStructureId () const virtual
Implements G4VPhysicalVolume.
Definition at line 225 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 225 of file G4PVPlacement.cc
void G4PVPlacement::GetReplicationData (EAxis & axis, G4int & nReplicas, G4double & width, G4double & offset, G4bool & consuming) const virtual
Implements G4VPhysicalVolume.
Definition at line 205 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 205 of file G4PVPlacement.cc
G4bool G4PVPlacement::IsMany () const virtual
Implements G4VPhysicalVolume.
Definition at line 164 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 164 of file G4PVPlacement.cc
References fmany.
G4bool G4PVPlacement::IsParameterised () const virtual
Implements G4VPhysicalVolume.
Definition at line 188 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 188 of file G4PVPlacement.cc
G4bool G4PVPlacement::IsRegularStructure () const virtual
Implements G4VPhysicalVolume.
Definition at line 215 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 215 of file G4PVPlacement.cc
G4bool G4PVPlacement::IsReplicated () const virtual
Implements G4VPhysicalVolume.
Definition at line 180 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 180 of file G4PVPlacement.cc
G4RotationMatrix * G4PVPlacement::NewPtrRotMatrix (const G4RotationMatrix & RotMat) static private
Definition at line 509 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 509 of file G4PVPlacement.cc
References CLHEP::HepRotation::isIdentity().
Referenced by G4PVPlacement().
G4PVPlacement& G4PVPlacement::operator= (const G4PVPlacement &) delete
void G4PVPlacement::SetCopyNo (G4int CopyNo) virtual
Implements G4VPhysicalVolume.
Definition at line 172 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 172 of file G4PVPlacement.cc
References fcopyNo.
EVolume G4PVPlacement::VolumeType () const virtual
Implements G4VPhysicalVolume.
Definition at line 235 of file G4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 235 of file G4PVPlacement.cc
References kNormal.
Member Data Documentation
G4bool G4PVPlacement::fallocatedRotM = false private
Definition at line 167 of file G4PVPlacement.hh.
View newest version in sPHENIX GitHub at line 167 of file G4PVPlacement.hh
Referenced by G4PVPlacement(), and ~G4PVPlacement().
G4int G4PVPlacement::fcopyNo = 0 private
Definition at line 168 of file G4PVPlacement.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PVPlacement.hh
Referenced by GetCopyNo(), and SetCopyNo().
G4bool G4PVPlacement::fmany = false private
Definition at line 166 of file G4PVPlacement.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PVPlacement.hh
Referenced by IsMany().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4PVPlacement.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4PVPlacement.cc