ECCE @ EIC Software: G4STRead Class Reference
G4STRead Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4STRead.hh>
Public Member Functions
G4LogicalVolume * Read (const G4String &, G4Material *mediumMaterial, G4Material *solidMaterial)
Private Member Functions
void TessellatedRead (const std::string &)
void FacetRead (const std::string &)
void PhysvolRead (const std::string &)
void ReadGeom (const G4String &)
void ReadTree (const G4String &)
Private Attributes
G4Box * world_box
G4ThreeVector world_extent
G4Material * solid_material
G4LogicalVolume * world_volume
std::vector< G4TessellatedSolid * > tessellatedList
std::map< G4TessellatedSolid
*, G4LogicalVolume * > volumeMap
Detailed Description
Definition at line 54 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 54 of file G4STRead.hh
Member Function Documentation
void G4STRead::FacetRead (const std::string & line) private
Definition at line 70 of file G4STRead.cc.
View newest version in sPHENIX GitHub at line 70 of file G4STRead.cc
References ABSOLUTE, FatalException, G4Exception(), tessellatedList, x1, x2, x3, x4, y1, y2, y3, y4, z1, and z2.
Referenced by ReadGeom().
void G4STRead::PhysvolRead (const std::string & line) private
Definition at line 114 of file G4STRead.cc.
View newest version in sPHENIX GitHub at line 114 of file G4STRead.cc
References FatalException, G4cout, G4endl, G4Exception(), incremental_prev_tag::idx, CLHEP::HepRotation::inverse(), kXAxis, kYAxis, kZAxis, G4B0ECAL::maxz, G4B0ECAL::minz, n1, pos(), r1, r2, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), tessellatedList, volumeMap, world_extent, world_volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ReadTree().
G4LogicalVolume * G4STRead::Read (const G4String & name, G4Material * mediumMaterial, G4Material * solidMaterial)
Definition at line 256 of file G4STRead.cc.
View newest version in sPHENIX GitHub at line 256 of file G4STRead.cc
References FatalException, G4Exception(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), kInfinity, ReadGeom(), ReadTree(), G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), G4Box::SetZHalfLength(), solid_material, world_box, world_extent, world_volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4STRead::ReadGeom (const G4String & name) private
Definition at line 199 of file G4STRead.cc.
View newest version in sPHENIX GitHub at line 199 of file G4STRead.cc
References FacetRead(), FatalException, G4cout, G4endl, G4Exception(), tessellatedList, TessellatedRead(), and volumeMap.
Referenced by Read().
void G4STRead::ReadTree (const G4String & name) private
Definition at line 231 of file G4STRead.cc.
View newest version in sPHENIX GitHub at line 231 of file G4STRead.cc
References FatalException, G4cout, G4endl, G4Exception(), and PhysvolRead().
Referenced by Read().
void G4STRead::TessellatedRead (const std::string & line) private
Definition at line 47 of file G4STRead.cc.
View newest version in sPHENIX GitHub at line 47 of file G4STRead.cc
References G4cout, G4endl, solid_material, tessellatedList, and volumeMap.
Referenced by ReadGeom().
Member Data Documentation
G4Material* G4STRead::solid_material private
Definition at line 72 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 72 of file G4STRead.hh
Referenced by Read(), and TessellatedRead().
std::vector<G4TessellatedSolid*> G4STRead::tessellatedList private
Definition at line 74 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 74 of file G4STRead.hh
Referenced by FacetRead(), PhysvolRead(), ReadGeom(), and TessellatedRead().
std::map<G4TessellatedSolid*,G4LogicalVolume*> G4STRead::volumeMap private
Definition at line 75 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 75 of file G4STRead.hh
Referenced by PhysvolRead(), ReadGeom(), and TessellatedRead().
G4Box* G4STRead::world_box private
Definition at line 70 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 70 of file G4STRead.hh
Referenced by Read().
G4ThreeVector G4STRead::world_extent private
Definition at line 71 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 71 of file G4STRead.hh
Referenced by PhysvolRead(), and Read().
G4LogicalVolume* G4STRead::world_volume private
Definition at line 73 of file G4STRead.hh.
View newest version in sPHENIX GitHub at line 73 of file G4STRead.hh
Referenced by PhysvolRead(), and Read().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4STRead.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4STRead.cc