ECCE @ EIC Software: G4FermiMomentum Class Reference
G4FermiMomentum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4FermiMomentum.hh>
Public Member Functions
G4FermiMomentum ()
~G4FermiMomentum ()
void Init (G4int anA, G4int aZ)
G4double GetFermiMomentum (G4double density)
G4ThreeVector GetMomentum (G4double density, G4double maxMomentum=-1.)
Private Member Functions
G4double cbrt (G4double x)
Private Attributes
G4int theA
G4int theZ
G4double constofpmax
Detailed Description
Definition at line 36 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 36 of file G4FermiMomentum.hh
Constructor & Destructor Documentation
G4FermiMomentum::G4FermiMomentum ()
Definition at line 31 of file G4FermiMomentum.cc.
View newest version in sPHENIX GitHub at line 31 of file G4FermiMomentum.cc
G4FermiMomentum::~G4FermiMomentum ()
Definition at line 36 of file G4FermiMomentum.cc.
View newest version in sPHENIX GitHub at line 36 of file G4FermiMomentum.cc
Member Function Documentation
G4double G4FermiMomentum::cbrt (G4double x) inline private
Definition at line 66 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 66 of file G4FermiMomentum.hh
References G4Pow::A13(), and G4Pow::GetInstance().
Referenced by GetFermiMomentum().
G4double G4FermiMomentum::GetFermiMomentum (G4double density) inline
Definition at line 45 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 45 of file G4FermiMomentum.hh
References cbrt(), constofpmax, and theA.
Referenced by G4BinaryCascade::CheckPauliPrinciple(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4Fancy3DNucleus::ChoosePositions(), G4ProtonField::GetFermiMomentum(), G4NeutronField::GetFermiMomentum(), GetMomentum(), G4BinaryLightIonReaction::GetProjectileExcitation(), and G4BinaryLightIonReaction::Interact().
G4ThreeVector G4FermiMomentum::GetMomentum (G4double density, G4double maxMomentum = -1.) inline
Definition at line 50 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 50 of file G4FermiMomentum.hh
References G4UniformRand, GetFermiMomentum(), and CLHEP::Hep3Vector::mag().
Referenced by G4Fancy3DNucleus::ChooseFermiMomenta().
void G4FermiMomentum::Init (G4int anA, G4int aZ) inline
Definition at line 43 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 43 of file G4FermiMomentum.hh
References theA, and theZ.
Referenced by G4BinaryCascade::CheckPauliPrinciple(), G4NeutronField::G4NeutronField(), G4ProtonField::G4ProtonField(), G4Fancy3DNucleus::Init(), and G4BinaryLightIonReaction::Interact().
Member Data Documentation
G4double G4FermiMomentum::constofpmax private
Definition at line 75 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FermiMomentum.hh
Referenced by GetFermiMomentum().
G4int G4FermiMomentum::theA private
Definition at line 70 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 70 of file G4FermiMomentum.hh
Referenced by GetFermiMomentum(), and Init().
G4int G4FermiMomentum::theZ private
Definition at line 71 of file G4FermiMomentum.hh.
View newest version in sPHENIX GitHub at line 71 of file G4FermiMomentum.hh
Referenced by Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4FermiMomentum.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4FermiMomentum.cc