ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/track/pyG4Track.cc File Reference
pyG4Track.cc File Reference
#include <boost/python.hpp>
#include "G4Track.hh"
#include "G4VProcess.hh"
Functions
void export_G4Track ()
Function Documentation
void export_G4Track ()
Definition at line 40 of file pyG4Track.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4Track.cc
References G4Track::GetCreatorProcess(), G4Track::GetCurrentStepNumber(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetLocalTime(), G4Track::GetLogicalVolumeAtVertex(), G4Track::GetMaterial(), G4Track::GetMomentum(), G4Track::GetMomentumDirection(), G4Track::GetParentID(), G4Track::GetPolarization(), G4Track::GetPosition(), G4Track::GetProperTime(), G4Track::GetStep(), G4Track::GetStepLength(), G4Track::GetTotalEnergy(), G4Track::GetTouchable(), G4Track::GetTrackID(), G4Track::GetTrackLength(), G4Track::GetTrackStatus(), G4Track::GetVelocity(), G4Track::GetVertexKineticEnergy(), G4Track::GetVertexMomentumDirection(), G4Track::GetVertexPosition(), G4Track::GetVolume(), G4Track::GetWeight(), and G4Track::SetWeight().
Referenced by BOOST_PYTHON_MODULE().