ECCE @ EIC Software: G4VNuclearDensity Class Reference
G4VNuclearDensity Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VNuclearDensity.hh>
Public Member Functions
G4VNuclearDensity ()
virtual ~G4VNuclearDensity ()
G4double GetDensity (const G4ThreeVector &aPosition) const
virtual G4double GetRelativeDensity (const G4ThreeVector &aPosition) const =0
virtual G4double GetRadius (const G4double maxRelativeDenisty) const =0
virtual G4double GetDeriv (const G4ThreeVector &point) const =0
Protected Member Functions
void Setrho0 (G4double arho0)
G4double Getrho0 () const
Private Attributes
G4double rho0
Detailed Description
Definition at line 35 of file G4VNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 35 of file G4VNuclearDensity.hh
Constructor & Destructor Documentation
G4VNuclearDensity::G4VNuclearDensity ()
Definition at line 31 of file G4VNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 31 of file G4VNuclearDensity.cc
G4VNuclearDensity::~G4VNuclearDensity () virtual
Definition at line 35 of file G4VNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 35 of file G4VNuclearDensity.cc
Member Function Documentation
G4double G4VNuclearDensity::GetDensity (const G4ThreeVector & aPosition) const inline
Definition at line 42 of file G4VNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 42 of file G4VNuclearDensity.hh
References GetRelativeDensity(), and rho0.
Referenced by G4BinaryCascade::CheckPauliPrinciple(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4Fancy3DNucleus::ChoosePositions(), G4KM_NucleonEqRhs::EvaluateRhsGivenB(), G4NeutronField::GetDensity(), G4ProtonField::GetDensity(), G4NuclearShellModelDensity::GetDeriv(), G4NuclearFermiDensity::GetDeriv(), G4SigmaPlusField::GetField(), G4KaonZeroField::GetField(), G4SigmaZeroField::GetField(), G4SigmaMinusField::GetField(), G4KaonPlusField::GetField(), G4PionZeroField::GetField(), G4KaonMinusField::GetField(), G4PionPlusField::GetField(), G4AntiProtonField::GetField(), G4PionMinusField::GetField(), and G4BinaryLightIonReaction::GetProjectileExcitation().
virtual G4double G4VNuclearDensity::GetDeriv (const G4ThreeVector & point) const pure virtual
Implemented in G4NuclearFermiDensity, and G4NuclearShellModelDensity.
Referenced by G4KM_NucleonEqRhs::EvaluateRhsGivenB(), and G4KM_OpticalEqRhs::EvaluateRhsGivenB().
virtual G4double G4VNuclearDensity::GetRadius (const G4double maxRelativeDenisty) const pure virtual
Implemented in G4NuclearFermiDensity, and G4NuclearShellModelDensity.
Referenced by G4Fancy3DNucleus::GetNuclearRadius().
virtual G4double G4VNuclearDensity::GetRelativeDensity (const G4ThreeVector & aPosition) const pure virtual
Implemented in G4NuclearFermiDensity, and G4NuclearShellModelDensity.
Referenced by G4Fancy3DNucleus::ChoosePositions(), and GetDensity().
G4double G4VNuclearDensity::Getrho0 () const inline protected
Definition at line 53 of file G4VNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VNuclearDensity.hh
Referenced by G4NuclearFermiDensity::GetDeriv().
void G4VNuclearDensity::Setrho0 (G4double arho0) inline protected
Definition at line 52 of file G4VNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VNuclearDensity.hh
References rho0.
Referenced by G4NuclearFermiDensity::G4NuclearFermiDensity(), and G4NuclearShellModelDensity::G4NuclearShellModelDensity().
Member Data Documentation
G4double G4VNuclearDensity::rho0 private
Definition at line 53 of file G4VNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VNuclearDensity.hh
Referenced by GetDensity(), and Setrho0().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VNuclearDensity.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4VNuclearDensity.cc