ECCE @ EIC Software: G4ChannelingOptrChangeCrossSection Class Reference
G4ChannelingOptrChangeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingOptrChangeCrossSection.hh>
Public Member Functions
G4ChannelingOptrChangeCrossSection (G4String particleToBias, G4String name="ChannelingChangeXS")
virtual ~G4ChannelingOptrChangeCrossSection ()
virtual void StartRun ()
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartTracking (const G4Track *)
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
Private Attributes
G4int fChannelingID
std::map< const
G4BiasingProcessInterface
*, G4BOptnChangeCrossSection * > fChangeCrossSectionOperations
G4bool fSetup
const G4ParticleDefinition * fParticleToBias
std::unordered_map
< std::string,
G4ChannelingDensityRatio > fProcessToDensity
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 60 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ChannelingOptrChangeCrossSection.hh
Constructor & Destructor Documentation
G4ChannelingOptrChangeCrossSection::G4ChannelingOptrChangeCrossSection (G4String particleToBias, G4String name = "ChannelingChangeXS")
Definition at line 43 of file G4ChannelingOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ChannelingOptrChangeCrossSection.cc
References fDensityRatioNone, G4ParticleTable::FindParticle(), fParticleToBias, fProcessToDensity, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), and JustWarning.
G4ChannelingOptrChangeCrossSection::~G4ChannelingOptrChangeCrossSection () virtual
Definition at line 65 of file G4ChannelingOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 65 of file G4ChannelingOptrChangeCrossSection.cc
References fChangeCrossSectionOperations, and it.
Member Function Documentation
void G4ChannelingOptrChangeCrossSection::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 254 of file G4ChannelingOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 254 of file G4ChannelingOptrChangeCrossSection.cc
References fChangeCrossSectionOperations, and G4BOptnChangeCrossSection::SetInteractionOccured().
virtual G4VBiasingOperation* G4ChannelingOptrChangeCrossSection::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 77 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChannelingOptrChangeCrossSection.hh
virtual G4VBiasingOperation* G4ChannelingOptrChangeCrossSection::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 80 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChannelingOptrChangeCrossSection.hh
G4VBiasingOperation * G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) private virtual
Implements G4VBiasingOperator.
Definition at line 172 of file G4ChannelingOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 172 of file G4ChannelingOptrChangeCrossSection.cc
References DBL_MAX, fChangeCrossSectionOperations, fChannelingID, fDensityRatioElD, fDensityRatioNone, fDensityRatioNotDefined, fDensityRatioNuD, fDensityRatioNuDElD, fParticleToBias, fProcessToDensity, G4endl, G4Exception(), G4Track::GetAuxiliaryTrackInformation(), G4VProcess::GetCurrentInteractionLength(), G4Track::GetDefinition(), G4ChannelingTrackData::GetDensity(), G4ChannelingTrackData::GetElD(), G4PhysicsModelCatalog::GetIndex(), G4BOptnChangeCrossSection::GetInteractionOccured(), G4ChannelingTrackData::GetNuD(), G4BiasingProcessInterface::GetPreviousOccurenceBiasingOperation(), G4BiasingProcessInterface::GetPreviousStepSize(), G4VProcess::GetProcessName(), G4BiasingProcessInterface::GetWrappedProcess(), JustWarning, G4BOptnChangeCrossSection::Sample(), G4BOptnChangeCrossSection::SetBiasedCrossSection(), and G4BOptnChangeCrossSection::UpdateForStep().
void G4ChannelingOptrChangeCrossSection::StartRun () virtual
Reimplemented from G4VBiasingOperator.
Definition at line 74 of file G4ChannelingOptrChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ChannelingOptrChangeCrossSection.cc
References fAnnihilation, fAnnihilationToHadrons, fAnnihilationToMuMu, fBremsstrahlung, fCerenkov, fChangeCrossSectionOperations, fComptonScattering, fCoulombScattering, fDecay, fDensityRatioElD, fDensityRatioNone, fDensityRatioNotDefined, fDensityRatioNuD, fDensityRatioNuDElD, fElectromagnetic, fGammaConversion, fGammaConversionToMuMu, fGeneral, fHadronic, fIonisation, fMultipleScattering, fNotDefined, fNuclearStopping, fOptical, fPairProdByCharged, fParallel, fParameterisation, fParticleToBias, fPhonon, fPhotoElectricEffect, fPhotolepton_hadron, fProcessToDensity, fRayleigh, fScintillation, fSetup, fSynchrotronRadiation, fTransitionRadiation, fTransportation, fUCN, fUserDefined, G4BiasingProcessSharedData::GetPhysicsBiasingProcessInterfaces(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), G4VProcess::GetProcessType(), G4BiasingProcessInterface::GetSharedData(), and G4BiasingProcessInterface::GetWrappedProcess().
Member Data Documentation
std::map< const G4BiasingProcessInterface*, G4BOptnChangeCrossSection* > G4ChannelingOptrChangeCrossSection::fChangeCrossSectionOperations private
Definition at line 94 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChannelingOptrChangeCrossSection.hh
Referenced by OperationApplied(), ProposeOccurenceBiasingOperation(), StartRun(), and ~G4ChannelingOptrChangeCrossSection().
G4int G4ChannelingOptrChangeCrossSection::fChannelingID private
Definition at line 70 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ChannelingOptrChangeCrossSection.hh
Referenced by ProposeOccurenceBiasingOperation().
const G4ParticleDefinition* G4ChannelingOptrChangeCrossSection::fParticleToBias private
Definition at line 96 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChannelingOptrChangeCrossSection.hh
Referenced by G4ChannelingOptrChangeCrossSection(), ProposeOccurenceBiasingOperation(), and StartRun().
std::unordered_map<std::string,G4ChannelingDensityRatio> G4ChannelingOptrChangeCrossSection::fProcessToDensity private
Definition at line 99 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ChannelingOptrChangeCrossSection.hh
Referenced by G4ChannelingOptrChangeCrossSection(), ProposeOccurenceBiasingOperation(), and StartRun().
G4bool G4ChannelingOptrChangeCrossSection::fSetup private
Definition at line 95 of file G4ChannelingOptrChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChannelingOptrChangeCrossSection.hh
Referenced by StartRun().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingOptrChangeCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/src/G4ChannelingOptrChangeCrossSection.cc