ECCE @ EIC Software: G4NavigationLogger Class Reference
G4NavigationLogger Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4NavigationLogger.hh>
Public Member Functions
G4NavigationLogger (const G4String &id)
~G4NavigationLogger ()
void PreComputeStepLog (const G4VPhysicalVolume *motherPhysical, G4double motherSafety, const G4ThreeVector &localPoint) const
void AlongComputeStepLog (const G4VSolid *sampleSolid, const G4ThreeVector &samplePoint, const G4ThreeVector &sampleDirection, const G4ThreeVector &localDirection, G4double sampleSafety, G4double sampleStep) const
void CheckDaughterEntryPoint (const G4VSolid *sampleSolid, const G4ThreeVector &samplePoint, const G4ThreeVector &sampleDirection, const G4VSolid *motherSolid, const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, G4double motherStep, G4double sampleStep) const
void PostComputeStepLog (const G4VSolid *motherSolid, const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, G4double motherStep, G4double motherSafety) const
void ComputeSafetyLog (const G4VSolid *solid, const G4ThreeVector &point, G4double safety, G4bool isMotherVolume, G4int banner=-1) const
void PrintDaughterLog (const G4VSolid *sampleSolid, const G4ThreeVector &samplePoint, G4double sampleSafety, G4bool onlySafety, const G4ThreeVector &sampleDirection, G4double sampleStep) const
G4bool CheckAndReportBadNormal (const G4ThreeVector &unitNormal, const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, G4double step, const G4VSolid *solid, const char *msg) const
G4bool CheckAndReportBadNormal (const G4ThreeVector &unitNormal, const G4ThreeVector &originalNormal, const G4RotationMatrix &rotationM, const char *msg) const
void ReportOutsideMother (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4VPhysicalVolume *motherPV, G4double tDist=30.0 *CLHEP::cm) const
void ReportVolumeAndIntersection (std::ostream &ostrm, const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4VPhysicalVolume *physical) const
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
G4double GetMinTriggerDistance () const
void SetMinTriggerDistance (G4double d)
G4bool GetReportSoftWarnings () const
void SetReportSoftWarnings (G4bool b)
Private Attributes
G4String fId
G4int fVerbose = 0
G4double fMinTriggerDistance = DBL_MAX
G4bool fReportSoftWarnings = false
Detailed Description
Definition at line 45 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 45 of file G4NavigationLogger.hh
Constructor & Destructor Documentation
G4NavigationLogger::G4NavigationLogger (const G4String & id)
Definition at line 39 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 39 of file G4NavigationLogger.cc
G4NavigationLogger::~G4NavigationLogger ()
Definition at line 44 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 44 of file G4NavigationLogger.cc
Member Function Documentation
void G4NavigationLogger::AlongComputeStepLog (const G4VSolid * sampleSolid, const G4ThreeVector & samplePoint, const G4ThreeVector & sampleDirection, const G4ThreeVector & localDirection, G4double sampleSafety, G4double sampleStep) const
Definition at line 134 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 134 of file G4NavigationLogger.cc
References G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), FatalException, fId, fVerbose, G4cout, G4endl, G4Exception(), G4GeometryTolerance::GetInstance(), G4VSolid::GetName(), G4VSolid::Inside(), JustWarning, kInfinity, kInside, kOutside, kSurface, max, and message().
Referenced by G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
G4bool G4NavigationLogger::CheckAndReportBadNormal (const G4ThreeVector & unitNormal, const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, G4double step, const G4VSolid * solid, const char * msg) const
Definition at line 556 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 556 of file G4NavigationLogger.cc
References fId, G4endl, G4Exception(), JustWarning, CLHEP::Hep3Vector::mag2(), message(), and CLHEP::perMillion.
Referenced by G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
G4bool G4NavigationLogger::CheckAndReportBadNormal (const G4ThreeVector & unitNormal, const G4ThreeVector & originalNormal, const G4RotationMatrix & rotationM, const char * msg) const
Definition at line 608 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 608 of file G4NavigationLogger.cc
References fId, G4endl, G4Exception(), CLHEP::HepRotation::inverse(), JustWarning, CLHEP::Hep3Vector::mag2(), message(), CLHEP::perMillion, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4NavigationLogger::CheckDaughterEntryPoint (const G4VSolid * sampleSolid, const G4ThreeVector & samplePoint, const G4ThreeVector & sampleDirection, const G4VSolid * motherSolid, const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, G4double motherStep, G4double sampleStep) const
Definition at line 258 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 258 of file G4NavigationLogger.cc
References G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), fId, fVerbose, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), G4VSolid::GetTolerance(), G4VSolid::Inside(), JustWarning, kCarTolerance, kInfinity, kOutside, kSurface, and millimeter.
Referenced by G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
void G4NavigationLogger::ComputeSafetyLog (const G4VSolid * solid, const G4ThreeVector & point, G4double safety, G4bool isMotherVolume, G4int banner = -1) const
Definition at line 487 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 487 of file G4NavigationLogger.cc
References fId, fVerbose, G4cout, G4endl, G4VSolid::GetEntityType(), and G4VSolid::GetName().
Referenced by G4NormalNavigation::ComputeSafety(), and G4VoxelNavigation::ComputeSafety().
G4double G4NavigationLogger::GetMinTriggerDistance () const inline
Definition at line 129 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 129 of file G4NavigationLogger.hh
References fMinTriggerDistance.
G4bool G4NavigationLogger::GetReportSoftWarnings () const inline
Definition at line 131 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 131 of file G4NavigationLogger.hh
References fReportSoftWarnings.
G4int G4NavigationLogger::GetVerboseLevel () const inline
Definition at line 126 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 126 of file G4NavigationLogger.hh
References fVerbose.
Referenced by G4NormalNavigation::GetVerboseLevel().
void G4NavigationLogger::PostComputeStepLog (const G4VSolid * motherSolid, const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, G4double motherStep, G4double motherSafety) const
Definition at line 436 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 436 of file G4NavigationLogger.cc
References G4VSolid::DumpInfo(), FatalException, fId, fVerbose, G4cerr, G4cout, G4endl, G4Exception(), G4VSolid::GetEntityType(), G4VSolid::GetName(), kInfinity, and message().
Referenced by G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
void G4NavigationLogger::PreComputeStepLog (const G4VPhysicalVolume * motherPhysical, G4double motherSafety, const G4ThreeVector & localPoint) const
Definition at line 53 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 53 of file G4NavigationLogger.cc
References G4VSolid::DistanceToIn(), FatalException, fId, fVerbose, G4cout, G4endl, G4Exception(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetSolid(), G4VSolid::GetTolerance(), G4VSolid::Inside(), JustWarning, kOutside, message(), and millimeter.
Referenced by G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
void G4NavigationLogger::PrintDaughterLog (const G4VSolid * sampleSolid, const G4ThreeVector & samplePoint, G4double sampleSafety, G4bool onlySafety, const G4ThreeVector & sampleDirection, G4double sampleStep) const
Definition at line 520 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 520 of file G4NavigationLogger.cc
References fVerbose, G4cout, G4endl, G4VSolid::GetEntityType(), and G4VSolid::GetName().
Referenced by G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
void G4NavigationLogger::ReportOutsideMother (const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4VPhysicalVolume * motherPV, G4double tDist = 30.0*CLHEP::cm) const
Definition at line 660 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 660 of file G4NavigationLogger.cc
References G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), e, FatalException, fId, fMinTriggerDistance, fReportSoftWarnings, G4endl, G4Exception(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), G4VSolid::GetName(), G4LogicalVolume::GetSolid(), G4VSolid::GetTolerance(), G4VSolid::Inside(), JustWarning, kCarTolerance, kInfinity, kOutside, max, and ReportVolumeAndIntersection().
Referenced by G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
void G4NavigationLogger::ReportVolumeAndIntersection (std::ostream & ostrm, const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4VPhysicalVolume * physical) const
Definition at line 780 of file G4NavigationLogger.cc.
View newest version in sPHENIX GitHub at line 780 of file G4NavigationLogger.cc
References G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), G4NavigationLogger_Namespace::EInsideNames, fId, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetSolid(), G4VSolid::GetTolerance(), G4VSolid::Inside(), kCarTolerance, kOutside, kSurface, and G4VSolid::SurfaceNormal().
Referenced by ReportOutsideMother().
void G4NavigationLogger::SetMinTriggerDistance (G4double d) inline
Definition at line 130 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 130 of file G4NavigationLogger.hh
References d, and fMinTriggerDistance.
void G4NavigationLogger::SetReportSoftWarnings (G4bool b) inline
Definition at line 132 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 132 of file G4NavigationLogger.hh
References b, and fReportSoftWarnings.
void G4NavigationLogger::SetVerboseLevel (G4int level) inline
Definition at line 127 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 127 of file G4NavigationLogger.hh
References fVerbose.
Referenced by G4NormalNavigation::SetVerboseLevel(), and G4VoxelNavigation::SetVerboseLevel().
Member Data Documentation
G4String G4NavigationLogger::fId private
Definition at line 136 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 136 of file G4NavigationLogger.hh
Referenced by AlongComputeStepLog(), CheckAndReportBadNormal(), CheckDaughterEntryPoint(), ComputeSafetyLog(), PostComputeStepLog(), PreComputeStepLog(), ReportOutsideMother(), and ReportVolumeAndIntersection().
G4double G4NavigationLogger::fMinTriggerDistance = DBL_MAX private
Definition at line 138 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 138 of file G4NavigationLogger.hh
Referenced by GetMinTriggerDistance(), ReportOutsideMother(), and SetMinTriggerDistance().
G4bool G4NavigationLogger::fReportSoftWarnings = false private
Definition at line 139 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 139 of file G4NavigationLogger.hh
Referenced by GetReportSoftWarnings(), ReportOutsideMother(), and SetReportSoftWarnings().
G4int G4NavigationLogger::fVerbose = 0 private
Definition at line 137 of file G4NavigationLogger.hh.
View newest version in sPHENIX GitHub at line 137 of file G4NavigationLogger.hh
Referenced by AlongComputeStepLog(), CheckDaughterEntryPoint(), ComputeSafetyLog(), GetVerboseLevel(), PostComputeStepLog(), PreComputeStepLog(), PrintDaughterLog(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4NavigationLogger.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4NavigationLogger.cc