ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/ptwXY_functions.cc File Reference
ptwXY_functions.cc File Reference
#include <cmath>
#include "ptwXY.h"
Functions
static nfu_status ptwXY_pow_callback (ptwXYPoint *point, void *argList)
static nfu_status ptwXY_exp_s (ptwXYPoints *ptwXY, double x1, double y1, double z1, double x2, double y2, double z2, int level)
static nfu_status ptwXY_convolution2 (ptwXYPoints *f1, ptwXYPoints *f2, double y, double yMin, double *c)
static nfu_status ptwXY_convolution3 (ptwXYPoints *convolute, ptwXYPoints *f1, ptwXYPoints *f2, double y1, double c1, double y2, double c2, double yMin)
nfu_status ptwXY_pow (ptwXYPoints *ptwXY, double v)
nfu_status ptwXY_exp (ptwXYPoints *ptwXY, double a)
ptwXYPoints * ptwXY_convolution (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int mode)
Function Documentation
ptwXYPoints* ptwXY_convolution (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int mode)
Definition at line 96 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 96 of file ptwXY_functions.cc
References ptwXYPoints_s::accuracy, c, dy, f1, f2, ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n, n1, nfu_Okay, nfu_tooFewPoints, nfu_unsupportedInterpolation, ptwXYPoints_s::points, ptwXY_convolution2(), ptwXY_convolution3(), ptwXY_free(), ptwXY_interpolationLinLin, ptwXY_new(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXYPoint_s::x, and y.
static nfu_status ptwXY_convolution2 (ptwXYPoints * f1, ptwXYPoints * f2, double y, double yMin, double * c) static
Definition at line 174 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 174 of file ptwXY_functions.cc
References ptwXYOverflowPoint_s::index, ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, n1, nfu_Okay, ptwXYPoints_s::points, ptwXY_getPointsAroundX(), ptwXY_interpolatePoint(), ptwXY_lessEqualGreaterX_between, ptwXY_lessEqualGreaterX_empty, ptwXY_lessEqualGreaterX_equal, ptwXY_lessEqualGreaterX_greater, ptwXY_lessEqualGreaterX_lessThan, ptwXYPoint_s::x, x, and ptwXYPoint_s::y.
Referenced by ptwXY_convolution(), and ptwXY_convolution3().
static nfu_status ptwXY_convolution3 (ptwXYPoints * convolute, ptwXYPoints * f1, ptwXYPoints * f2, double y1, double c1, double y2, double c2, double yMin) static
Definition at line 294 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 294 of file ptwXY_functions.cc
References ptwXYPoints_s::accuracy, c, e, nfu_Okay, ptwXY_convolution2(), ptwXY_getXMax(), ptwXY_getXMin(), ptwXY_setValueAtX(), and y2.
Referenced by ptwXY_convolution().
nfu_status ptwXY_exp (ptwXYPoints * ptwXY, double a)
Definition at line 43 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 43 of file ptwXY_functions.cc
References G4Exp(), ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_exp_s(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y1, y2, z1, and z2.
static nfu_status ptwXY_exp_s (ptwXYPoints * ptwXY, double x1, double y1, double z1, double x2, double y2, double z2, int level) static
Definition at line 71 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 71 of file ptwXY_functions.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, dx, dy, G4Exp(), nfu_Okay, ptwXY_setValueAtX(), x, x1, y, y1, z, and z1.
Referenced by ptwXY_exp().
nfu_status ptwXY_pow (ptwXYPoints * ptwXY, double v)
Definition at line 24 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 24 of file ptwXY_functions.cc
References ptwXY_applyFunction(), and ptwXY_pow_callback().
static nfu_status ptwXY_pow_callback (ptwXYPoint * point, void * argList) static
Definition at line 31 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 31 of file ptwXY_functions.cc
References G4Pow::GetInstance(), nfu_Okay, G4Pow::powA(), v, and ptwXYPoint_s::y.
Referenced by ptwXY_pow().