ECCE @ EIC Software: DicomDetectorConstruction Class Reference
DicomDetectorConstruction Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomDetectorConstruction.hh>
Public Member Functions
DicomDetectorConstruction ()
~DicomDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
G4int GetTotalVoxels () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Protected Member Functions
void InitialisationOfMaterials ()
void ReadPhantomData ()
void ReadPhantomDataNew ()
void ReadVoxelDensities (std::ifstream &fin)
void ReadPhantomDataFile (const G4String &fname)
void MergeZSliceHeaders ()
G4Material * BuildMaterialWithChangingDensity (const G4Material *origMate, G4float density, G4String newMateName)
void ConstructPhantomContainer ()
void ConstructPhantomContainerNew ()
virtual void ConstructPhantom ()=0
void SetScorer (G4LogicalVolume *voxel_logic)
virtual void ConstructSDandField ()
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes
G4Material * fAir
G4Box * fWorld_solid
G4LogicalVolume * fWorld_logic
G4VPhysicalVolume * fWorld_phys
G4Box * fContainer_solid
G4LogicalVolume * fContainer_logic
G4VPhysicalVolume * fContainer_phys
G4int fNoFiles
std::vector< G4Material * > fOriginalMaterials
std::vector< G4Material * > fMaterials
size_t * fMateIDs
std::map< G4int, G4double > fDensityDiffs
std::vector
< DicomPhantomZSliceHeader * > fZSliceHeaders
DicomPhantomZSliceHeader * fZSliceHeaderMerged
G4int fNVoxelX
G4int fNVoxelY
G4int fNVoxelZ
G4double fVoxelHalfDimX
G4double fVoxelHalfDimY
G4double fVoxelHalfDimZ
G4double fMinX
G4double fMinY
G4double fMinZ
G4double fMaxX
G4double fMaxY
G4double fMaxZ
std::map< G4int, G4Material * > thePhantomMaterialsOriginal
DicomPhantomZSliceMerged * fMergedSlices
std::set< G4LogicalVolume * > fScorers
G4bool fConstructed
Detailed Description
Definition at line 66 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file DicomDetectorConstruction.hh
Constructor & Destructor Documentation
DicomDetectorConstruction::DicomDetectorConstruction ()
Definition at line 61 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 61 of file DicomDetectorConstruction.cc
DicomDetectorConstruction::~DicomDetectorConstruction ()
Definition at line 90 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 90 of file DicomDetectorConstruction.cc
Member Function Documentation
G4Material * DicomDetectorConstruction::BuildMaterialWithChangingDensity (const G4Material * origMate, G4float density, G4String newMateName) protected
Definition at line 823 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 823 of file DicomDetectorConstruction.cc
References cm3, Acts::UnitConstants::g, G4Material::GetElement(), G4Material::GetFractionVector(), G4Material::GetNumberOfElements(), kStateUndefined, and source.hepunit::STP_Temperature.
Referenced by ReadPhantomDataFile(), ReadVoxelDensities(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
G4VPhysicalVolume * DicomDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Reimplemented in DicomPartialDetectorConstruction.
Definition at line 95 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 95 of file DicomDetectorConstruction.cc
References ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), fAir, fConstructed, fWorld_logic, fWorld_phys, fWorld_solid, InitialisationOfMaterials(), m, ReadPhantomData(), and ReadPhantomDataNew().
virtual void DicomDetectorConstruction::ConstructPhantom () protected pure virtual
Implemented in DicomPartialDetectorConstruction, DicomRegularDetectorConstruction, and DicomNestedParamDetectorConstruction.
Referenced by Construct().
void DicomDetectorConstruction::ConstructPhantomContainer () protected
Definition at line 842 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 842 of file DicomDetectorConstruction.cc
References fContainer_logic, fContainer_phys, fContainer_solid, fMaterials, fNVoxelX, fNVoxelY, fNVoxelZ, fVoxelHalfDimX, fVoxelHalfDimY, fVoxelHalfDimZ, fWorld_logic, fZSliceHeaderMerged, G4cout, G4endl, DicomPhantomZSliceHeader::GetMaxX(), DicomPhantomZSliceHeader::GetMaxY(), DicomPhantomZSliceHeader::GetMaxZ(), DicomPhantomZSliceHeader::GetMinX(), DicomPhantomZSliceHeader::GetMinY(), DicomPhantomZSliceHeader::GetMinZ(), DicomPhantomZSliceHeader::GetNoVoxelX(), DicomPhantomZSliceHeader::GetNoVoxelY(), DicomPhantomZSliceHeader::GetNoVoxelZ(), DicomPhantomZSliceHeader::GetVoxelHalfX(), DicomPhantomZSliceHeader::GetVoxelHalfY(), and DicomPhantomZSliceHeader::GetVoxelHalfZ().
Referenced by Construct().
void DicomDetectorConstruction::ConstructPhantomContainerNew () protected
Definition at line 894 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 894 of file DicomDetectorConstruction.cc
References fContainer_logic, fContainer_phys, fContainer_solid, fMaterials, fMaxX, fMaxY, fMaxZ, fMinX, fMinY, fMinZ, fNVoxelX, fNVoxelY, fNVoxelZ, fVoxelHalfDimX, fVoxelHalfDimY, fVoxelHalfDimZ, fWorld_logic, G4cout, and G4endl.
Referenced by Construct().
void DicomDetectorConstruction::ConstructSDandField () protected virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 954 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 954 of file DicomDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fNVoxelX, fNVoxelY, fNVoxelZ, fScorers, G4cout, G4endl, G4SDManager::GetSDMpointer(), G4MultiFunctionalDetector::RegisterPrimitive(), and G4VUserDetectorConstruction::SetSensitiveDetector().
G4int DicomDetectorConstruction::GetTotalVoxels () const inline
Definition at line 158 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 158 of file DicomDetectorConstruction.hh
References fNVoxelX, fNVoxelY, and fNVoxelZ.
void DicomDetectorConstruction::InitialisationOfMaterials () protected
Definition at line 138 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 138 of file DicomDetectorConstruction.cc
References a, G4Material::AddElement(), cm3, fAir, fOriginalMaterials, Acts::UnitConstants::g, G4cout, G4endl, mg, mole, perCent, and z.
Referenced by DicomPartialDetectorConstruction::Construct(), and Construct().
void DicomDetectorConstruction::MergeZSliceHeaders () protected
Definition at line 812 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 812 of file DicomDetectorConstruction.cc
References fZSliceHeaderMerged, and fZSliceHeaders.
Referenced by ReadPhantomData().
void DicomDetectorConstruction::ReadPhantomData () protected
Definition at line 659 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 659 of file DicomDetectorConstruction.cc
References FatalException, test::fname, fNoFiles, G4Exception(), DicomHandler::GetDicomDataFile(), MergeZSliceHeaders(), and ReadPhantomDataFile().
Referenced by Construct().
void DicomDetectorConstruction::ReadPhantomDataFile (const G4String & fname) protected
Definition at line 693 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 693 of file DicomDetectorConstruction.cc
References BuildMaterialWithChangingDensity(), G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToString(), FatalErrorInArgument, fDensityDiffs, fin, fMateIDs, fMaterials, fNoFiles, fOriginalMaterials, fZSliceHeaders, G4cerr, G4cout, G4endl, G4Exception(), G4Material::GetName(), DicomPhantomZSliceHeader::GetNoVoxels(), in, and part.
Referenced by ReadPhantomData().
void DicomDetectorConstruction::ReadPhantomDataNew () protected
Definition at line 456 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 456 of file DicomDetectorConstruction.cc
References G4UIcommand::ConvertToString(), FatalErrorInArgument, FatalException, fin, G4NistManager::FindOrBuildMaterial(), fMateIDs, fMaxX, fMaxY, fMaxZ, fMinX, fMinY, fMinZ, fNVoxelX, fNVoxelY, fNVoxelZ, fVoxelHalfDimX, fVoxelHalfDimY, fVoxelHalfDimZ, G4cout, G4endl, G4Exception(), DicomFileMgr::GetFileOutName(), DicomFileMgr::GetInstance(), G4Material::GetMaterialTable(), G4NistManager::Instance(), G4TrackingService::nMaterials, ReadVoxelDensities(), and thePhantomMaterialsOriginal.
Referenced by Construct().
void DicomDetectorConstruction::ReadVoxelDensities (std::ifstream & fin) protected
Definition at line 545 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 545 of file DicomDetectorConstruction.cc
References BuildMaterialWithChangingDensity(), CLHEP::cm3, G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToString(), DBL_MAX, e, matInfo::fId, fMateIDs, fMaterials, matInfo::fNvoxels, fNVoxelX, fNVoxelY, fNVoxelZ, matInfo::fSumdens, CLHEP::g, G4cout, G4endl, part, and thePhantomMaterialsOriginal.
Referenced by ReadPhantomDataNew().
void DicomDetectorConstruction::SetScorer (G4LogicalVolume * voxel_logic) protected
Definition at line 942 of file DicomDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 942 of file DicomDetectorConstruction.cc
References fScorers, G4cout, G4endl, and G4LogicalVolume::GetName().
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), and DicomRegularDetectorConstruction::ConstructPhantom().
Member Data Documentation
G4Material* DicomDetectorConstruction::fAir protected
Definition at line 112 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 112 of file DicomDetectorConstruction.hh
Referenced by DicomPartialDetectorConstruction::Construct(), Construct(), DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantomContainer(), and InitialisationOfMaterials().
G4bool DicomDetectorConstruction::fConstructed protected
Definition at line 153 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 153 of file DicomDetectorConstruction.hh
Referenced by Construct().
G4LogicalVolume* DicomDetectorConstruction::fContainer_logic protected
Definition at line 120 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 120 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantomContainer(), ConstructPhantomContainer(), and ConstructPhantomContainerNew().
G4VPhysicalVolume* DicomDetectorConstruction::fContainer_phys protected
Definition at line 121 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file DicomDetectorConstruction.hh
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantomContainer(), ConstructPhantomContainer(), and ConstructPhantomContainerNew().
G4Box* DicomDetectorConstruction::fContainer_solid protected
Definition at line 119 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file DicomDetectorConstruction.hh
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), and ConstructPhantomContainerNew().
std::map<G4int,G4double> DicomDetectorConstruction::fDensityDiffs protected
Definition at line 131 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 131 of file DicomDetectorConstruction.hh
Referenced by ReadPhantomDataFile().
size_t* DicomDetectorConstruction::fMateIDs protected
Definition at line 128 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 128 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ReadPhantomDataFile(), ReadPhantomDataFile(), ReadPhantomDataNew(), ReadVoxelDensities(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
std::vector<G4Material*> DicomDetectorConstruction::fMaterials protected
Definition at line 125 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), ReadPhantomDataFile(), ReadVoxelDensities(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
G4double DicomDetectorConstruction::fMaxX protected
Definition at line 143 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 143 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4double DicomDetectorConstruction::fMaxY protected
Definition at line 143 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 143 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4double DicomDetectorConstruction::fMaxZ protected
Definition at line 143 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 143 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainerNew(), and ReadPhantomDataNew().
DicomPhantomZSliceMerged* DicomDetectorConstruction::fMergedSlices protected
Definition at line 149 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 149 of file DicomDetectorConstruction.hh
G4double DicomDetectorConstruction::fMinX protected
Definition at line 142 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4double DicomDetectorConstruction::fMinY protected
Definition at line 142 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4double DicomDetectorConstruction::fMinZ protected
Definition at line 142 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4int DicomDetectorConstruction::fNoFiles protected
Definition at line 123 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 123 of file DicomDetectorConstruction.hh
Referenced by ReadPhantomData(), and ReadPhantomDataFile().
G4int DicomDetectorConstruction::fNVoxelX protected
Definition at line 140 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 140 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), ConstructSDandField(), GetTotalVoxels(), DicomPartialDetectorConstruction::ReadPhantomDataFile(), ReadPhantomDataNew(), ReadVoxelDensities(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
G4int DicomDetectorConstruction::fNVoxelY protected
Definition at line 140 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 140 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), ConstructSDandField(), GetTotalVoxels(), DicomPartialDetectorConstruction::ReadPhantomDataFile(), ReadPhantomDataNew(), ReadVoxelDensities(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
G4int DicomDetectorConstruction::fNVoxelZ protected
Definition at line 140 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 140 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), ConstructSDandField(), GetTotalVoxels(), DicomPartialDetectorConstruction::ReadPhantomDataFile(), ReadPhantomDataNew(), ReadVoxelDensities(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
std::vector<G4Material*> DicomDetectorConstruction::fOriginalMaterials protected
Definition at line 124 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 124 of file DicomDetectorConstruction.hh
Referenced by InitialisationOfMaterials(), ReadPhantomDataFile(), and DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial().
std::set<G4LogicalVolume*> DicomDetectorConstruction::fScorers protected
Definition at line 151 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 151 of file DicomDetectorConstruction.hh
Referenced by ConstructSDandField(), and SetScorer().
G4double DicomDetectorConstruction::fVoxelHalfDimX protected
Definition at line 141 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 141 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4double DicomDetectorConstruction::fVoxelHalfDimY protected
Definition at line 141 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 141 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4double DicomDetectorConstruction::fVoxelHalfDimZ protected
Definition at line 141 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 141 of file DicomDetectorConstruction.hh
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), ConstructPhantomContainer(), ConstructPhantomContainerNew(), and ReadPhantomDataNew().
G4LogicalVolume* DicomDetectorConstruction::fWorld_logic protected
Definition at line 116 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file DicomDetectorConstruction.hh
Referenced by DicomPartialDetectorConstruction::Construct(), Construct(), DicomPartialDetectorConstruction::ConstructPhantomContainer(), ConstructPhantomContainer(), and ConstructPhantomContainerNew().
G4VPhysicalVolume* DicomDetectorConstruction::fWorld_phys protected
Definition at line 117 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file DicomDetectorConstruction.hh
Referenced by Construct().
G4Box* DicomDetectorConstruction::fWorld_solid protected
Definition at line 115 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 115 of file DicomDetectorConstruction.hh
Referenced by Construct().
DicomPhantomZSliceHeader* DicomDetectorConstruction::fZSliceHeaderMerged protected
Definition at line 137 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 137 of file DicomDetectorConstruction.hh
Referenced by ConstructPhantomContainer(), and MergeZSliceHeaders().
std::vector<DicomPhantomZSliceHeader*> DicomDetectorConstruction::fZSliceHeaders protected
Definition at line 135 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 135 of file DicomDetectorConstruction.hh
Referenced by MergeZSliceHeaders(), and ReadPhantomDataFile().
std::map<G4int,G4Material*> DicomDetectorConstruction::thePhantomMaterialsOriginal protected
Definition at line 145 of file DicomDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 145 of file DicomDetectorConstruction.hh
Referenced by ReadPhantomDataNew(), and ReadVoxelDensities().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomDetectorConstruction.cc