ECCE @ EIC Software: G4PreCompoundFragmentVector Class Reference
G4PreCompoundFragmentVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundFragmentVector.hh>
Public Member Functions
G4PreCompoundFragmentVector (pcfvector *avector)
~G4PreCompoundFragmentVector ()=default
void SetVector (pcfvector *avector)
void SetOPTxs (G4int)
void UseSICB (G4bool)
G4double CalculateProbabilities (const G4Fragment &aFragment)
G4VPreCompoundFragment * ChooseFragment ()
Private Member Functions
G4PreCompoundFragmentVector (const G4PreCompoundFragmentVector &right)=delete
const G4PreCompoundFragmentVector & operator= (const G4PreCompoundFragmentVector &right)=delete
G4bool operator== (const G4PreCompoundFragmentVector &right) const =delete
G4bool operator!= (const G4PreCompoundFragmentVector &right) const =delete
Private Attributes
pcfvector * theChannels
G4DataVector probabilities
G4int nChannels
Detailed Description
Definition at line 51 of file G4PreCompoundFragmentVector.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PreCompoundFragmentVector.hh
Constructor & Destructor Documentation
G4PreCompoundFragmentVector::G4PreCompoundFragmentVector (pcfvector * avector) explicit
Definition at line 37 of file G4PreCompoundFragmentVector.cc.
View newest version in sPHENIX GitHub at line 37 of file G4PreCompoundFragmentVector.cc
References SetVector().
G4PreCompoundFragmentVector::~G4PreCompoundFragmentVector () default
G4PreCompoundFragmentVector::G4PreCompoundFragmentVector (const G4PreCompoundFragmentVector & right) private delete
Member Function Documentation
G4double G4PreCompoundFragmentVector::CalculateProbabilities (const G4Fragment & aFragment)
Definition at line 74 of file G4PreCompoundFragmentVector.cc.
View newest version in sPHENIX GitHub at line 74 of file G4PreCompoundFragmentVector.cc
References nChannels, probabilities, and theChannels.
Referenced by G4PreCompoundEmission::GetTotalProbability().
G4VPreCompoundFragment * G4PreCompoundFragmentVector::ChooseFragment ()
Definition at line 93 of file G4PreCompoundFragmentVector.cc.
View newest version in sPHENIX GitHub at line 93 of file G4PreCompoundFragmentVector.cc
References G4UniformRand, nChannels, probabilities, theChannels, and x.
Referenced by G4PreCompoundEmission::PerformEmission().
G4bool G4PreCompoundFragmentVector::operator!= (const G4PreCompoundFragmentVector & right) const private delete
const G4PreCompoundFragmentVector& G4PreCompoundFragmentVector::operator= (const G4PreCompoundFragmentVector & right) private delete
G4bool G4PreCompoundFragmentVector::operator== (const G4PreCompoundFragmentVector & right) const private delete
void G4PreCompoundFragmentVector::SetOPTxs (G4int opt)
Definition at line 59 of file G4PreCompoundFragmentVector.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PreCompoundFragmentVector.cc
References nChannels.
Referenced by G4PreCompoundEmission::SetOPTxs().
void G4PreCompoundFragmentVector::SetVector (pcfvector * avector)
Definition at line 43 of file G4PreCompoundFragmentVector.cc.
View newest version in sPHENIX GitHub at line 43 of file G4PreCompoundFragmentVector.cc
References nChannels, probabilities, and theChannels.
Referenced by G4PreCompoundFragmentVector(), G4PreCompoundEmission::SetDefaultModel(), and G4PreCompoundEmission::SetHETCModel().
void G4PreCompoundFragmentVector::UseSICB (G4bool use)
Definition at line 67 of file G4PreCompoundFragmentVector.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PreCompoundFragmentVector.cc
References nChannels.
Referenced by G4PreCompoundEmission::UseSICB().
Member Data Documentation
G4int G4PreCompoundFragmentVector::nChannels private
Definition at line 80 of file G4PreCompoundFragmentVector.hh.
View newest version in sPHENIX GitHub at line 80 of file G4PreCompoundFragmentVector.hh
Referenced by CalculateProbabilities(), ChooseFragment(), SetOPTxs(), SetVector(), and UseSICB().
G4DataVector G4PreCompoundFragmentVector::probabilities private
Definition at line 78 of file G4PreCompoundFragmentVector.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PreCompoundFragmentVector.hh
Referenced by CalculateProbabilities(), ChooseFragment(), and SetVector().
pcfvector* G4PreCompoundFragmentVector::theChannels private
Definition at line 77 of file G4PreCompoundFragmentVector.hh.
View newest version in sPHENIX GitHub at line 77 of file G4PreCompoundFragmentVector.hh
Referenced by CalculateProbabilities(), ChooseFragment(), and SetVector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundFragmentVector.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4PreCompoundFragmentVector.cc