ECCE @ EIC Software: G4SPSEneDistribution Class Reference
G4SPSEneDistribution Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4SPSEneDistribution.hh>
Classes
struct threadLocal_t
Public Member Functions
G4SPSEneDistribution ()
~G4SPSEneDistribution ()
void SetEnergyDisType (G4String)
G4String GetEnergyDisType ()
void SetEmin (G4double)
G4double GetEmin ()
G4double GetArbEmin ()
void SetEmax (G4double)
G4double GetEmax ()
G4double GetArbEmax ()
void SetMonoEnergy (G4double)
void SetAlpha (G4double)
void SetBiasAlpha (G4double)
void SetTemp (G4double)
void SetBeamSigmaInE (G4double)
void SetEzero (G4double)
void SetGradient (G4double)
void SetInterCept (G4double)
void UserEnergyHisto (G4ThreeVector)
void ArbEnergyHisto (G4ThreeVector)
void ArbEnergyHistoFile (G4String)
void EpnEnergyHisto (G4ThreeVector)
void InputEnergySpectra (G4bool)
void InputDifferentialSpectra (G4bool)
void ArbInterpolate (G4String)
G4String GetIntType ()
void Calculate ()
void SetBiasRndm (G4SPSRandomGenerator *a)
void ReSetHist (G4String)
void SetVerbosity (G4int a)
G4double GetWeight ()
G4double GetMonoEnergy ()
G4double GetSE ()
G4double Getalpha ()
G4double GetEzero ()
G4double GetTemp ()
G4double Getgrad ()
G4double Getcept ()
G4PhysicsOrderedFreeVector GetUserDefinedEnergyHisto ()
G4PhysicsOrderedFreeVector GetArbEnergyHisto ()
G4double GenerateOne (G4ParticleDefinition *)
G4double GetProbability (G4double)
Private Member Functions
void LinearInterpolation ()
void LogInterpolation ()
void ExpInterpolation ()
void SplineInterpolation ()
void CalculateCdgSpectrum ()
void CalculateBbodySpectrum ()
void CalculateCPowSpectrum ()
void GenerateMonoEnergetic ()
void GenerateBiasPowEnergies ()
void GenerateGaussEnergies ()
void GenerateBremEnergies ()
void GenerateBbodyEnergies ()
void GenerateCdgEnergies ()
void GenUserHistEnergies ()
void GenEpnHistEnergies ()
void GenArbPointEnergies ()
void GenerateExpEnergies (G4bool)
void GenerateLinearEnergies (G4bool)
void GeneratePowEnergies (G4bool)
void GenerateCPowEnergies ()
void ConvertEPNToEnergy ()
void BBInitHists ()
void CPInitHists ()
Private Attributes
G4String EnergyDisType
G4double weight
G4double MonoEnergy
G4double SE
G4double Emin
G4double Emax
G4double alpha
G4double Ezero
G4double Temp
G4double biasalpha
G4double grad
G4double cept
G4double prob_norm
G4bool Biased
G4bool EnergySpec
G4bool DiffSpec
G4PhysicsOrderedFreeVector UDefEnergyH
G4PhysicsOrderedFreeVector IPDFEnergyH
G4bool IPDFEnergyExist
G4bool IPDFArbExist
G4bool Epnflag
G4PhysicsOrderedFreeVector ArbEnergyH
G4PhysicsOrderedFreeVector IPDFArbEnergyH
G4PhysicsOrderedFreeVector EpnEnergyH
G4double CDGhist [3]
std::vector< G4double > * BBHist
std::vector< G4double > * Bbody_x
G4bool BBhistInit
G4bool BBhistCalcd
std::vector< G4double > * CPHist
std::vector< G4double > * CP_x
G4bool CPhistInit
G4bool CPhistCalcd
G4String IntType
G4double * Arb_grad
G4double * Arb_cept
G4bool Arb_grad_cept_flag
G4double * Arb_alpha
G4double * Arb_Const
G4bool Arb_alpha_Const_flag
G4double * Arb_ezero
G4bool Arb_ezero_flag
G4double ArbEmin
G4double ArbEmax
G4double particle_energy
G4SPSRandomGenerator * eneRndm
G4int verbosityLevel
G4PhysicsOrderedFreeVector ZeroPhysVector
std::vector
< G4DataInterpolation * > SplineInt
G4DataInterpolation * Splinetemp
G4Mutex mutex
G4Cache< threadLocal_t > threadLocalData
Detailed Description
Andrea Dotti Feb 2015 Important: This is a shared class between threads. Only one thread should use the set-methods here. Note that this is exactly what is achieved using UI commands. If you use the set methods to set defaults in your application take care that only one thread is executing them. In addition take care of calling these methods before the run is started Do not use these setters during the event loop
Definition at line 174 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 174 of file G4SPSEneDistribution.hh
Constructor & Destructor Documentation
G4SPSEneDistribution::G4SPSEneDistribution ()
Definition at line 66 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 66 of file G4SPSEneDistribution.cc
References alpha, G4SPSEneDistribution::threadLocal_t::alpha, Arb_alpha, Arb_alpha_Const_flag, Arb_cept, Arb_Const, Arb_ezero, Arb_ezero_flag, Arb_grad, Arb_grad_cept_flag, ArbEmax, ArbEmin, BBHist, BBhistCalcd, BBhistInit, Bbody_x, biasalpha, Biased, cept, G4SPSEneDistribution::threadLocal_t::cept, CP_x, CPHist, CPhistCalcd, CPhistInit, DiffSpec, Emax, G4SPSEneDistribution::threadLocal_t::Emax, Emin, G4SPSEneDistribution::threadLocal_t::Emin, EnergyDisType, EnergySpec, Ezero, G4SPSEneDistribution::threadLocal_t::Ezero, G4MUTEXINIT, G4Cache< VALTYPE >::Get(), grad, G4SPSEneDistribution::threadLocal_t::grad, IntType, IPDFArbExist, IPDFEnergyExist, MeV, MonoEnergy, G4SPSEneDistribution::threadLocal_t::particle_definition, particle_energy, G4SPSEneDistribution::threadLocal_t::particle_energy, prob_norm, SE, Temp, threadLocalData, verbosityLevel, weight, and G4SPSEneDistribution::threadLocal_t::weight.
G4SPSEneDistribution::~G4SPSEneDistribution ()
Definition at line 128 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 128 of file G4SPSEneDistribution.cc
References Arb_alpha, Arb_alpha_Const_flag, Arb_cept, Arb_Const, Arb_ezero, Arb_ezero_flag, Arb_grad, Arb_grad_cept_flag, BBHist, Bbody_x, CP_x, CPHist, G4MUTEXDESTROY, it, and SplineInt.
Member Function Documentation
void G4SPSEneDistribution::ArbEnergyHisto (G4ThreeVector input)
Definition at line 352 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 352 of file G4SPSEneDistribution.cc
References ArbEnergyH, G4cout, G4endl, G4PhysicsOrderedFreeVector::InsertValues(), verbosityLevel, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::ArbEnergyHistoFile (G4String filename)
Definition at line 366 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 366 of file G4SPSEneDistribution.cc
References ArbEnergyH, FatalException, G4Exception(), in, and G4PhysicsOrderedFreeVector::InsertValues().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::ArbInterpolate (G4String IType)
Definition at line 582 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 582 of file G4SPSEneDistribution.cc
References ArbEmax, ArbEmin, ArbEnergyH, EnergyDisType, ExpInterpolation(), FatalException, G4Exception(), G4PhysicsOrderedFreeVector::GetMaxLowEdgeEnergy(), G4PhysicsOrderedFreeVector::GetMinLowEdgeEnergy(), IntType, LinearInterpolation(), LogInterpolation(), and SplineInterpolation().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::BBInitHists () private
Definition at line 424 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 424 of file G4SPSEneDistribution.cc
References BBHist, BBhistInit, and Bbody_x.
Referenced by Calculate().
void G4SPSEneDistribution::Calculate ()
Definition at line 398 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 398 of file G4SPSEneDistribution.cc
References BBhistInit, BBInitHists(), CalculateBbodySpectrum(), CalculateCdgSpectrum(), CalculateCPowSpectrum(), CPhistInit, CPInitHists(), and EnergyDisType.
Referenced by GenerateBbodyEnergies(), GenerateCPowEnergies(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::CalculateBbodySpectrum () private
Definition at line 492 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 492 of file G4SPSEneDistribution.cc
References BBHist, Bbody_x, c, c2, G4Cache< VALTYPE >::Get(), Acts::UnitConstants::h, h2, k, propagation_timing::steps, sum, Temp, and threadLocalData.
Referenced by Calculate().
void G4SPSEneDistribution::CalculateCdgSpectrum () private
Definition at line 441 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 441 of file G4SPSEneDistribution.cc
References CDGhist, G4Cache< VALTYPE >::Get(), keV, and threadLocalData.
Referenced by Calculate().
void G4SPSEneDistribution::CalculateCPowSpectrum () private
Definition at line 531 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 531 of file G4SPSEneDistribution.cc
References alpha, CP_x, CPHist, Ezero, G4Cache< VALTYPE >::Get(), propagation_timing::steps, sum, and threadLocalData.
Referenced by Calculate().
void G4SPSEneDistribution::ConvertEPNToEnergy () private
Definition at line 1766 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1766 of file G4SPSEneDistribution.cc
References G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, EpnEnergyH, Epnflag, FatalException, G4cout, G4endl, G4Exception(), G4Cache< VALTYPE >::Get(), G4ParticleDefinition::GetBaryonNumber(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), JustWarning, G4SPSEneDistribution::threadLocal_t::particle_definition, threadLocalData, and UDefEnergyH.
Referenced by GenEpnHistEnergies().
void G4SPSEneDistribution::CPInitHists () private
Definition at line 432 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 432 of file G4SPSEneDistribution.cc
References CP_x, CPHist, and CPhistInit.
Referenced by Calculate().
void G4SPSEneDistribution::EpnEnergyHisto (G4ThreeVector input)
Definition at line 381 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 381 of file G4SPSEneDistribution.cc
References Emax, EpnEnergyH, Epnflag, G4cout, G4endl, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::InsertValues(), threadLocalData, verbosityLevel, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::ExpInterpolation () private
Definition at line 879 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 879 of file G4SPSEneDistribution.cc
References Arb_Const, Arb_ezero, Arb_ezero_flag, ArbEnergyH, DiffSpec, EnergySpec, FatalException, G4cout, G4endl, G4Exception(), G4Cache< VALTYPE >::Get(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFArbEnergyH, JustWarning, mass, maxi, G4PhysicsVector::ScaleVector(), sum, test(), threadLocalData, and verbosityLevel.
Referenced by ArbInterpolate().
void G4SPSEneDistribution::GenArbPointEnergies () private
Definition at line 1633 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1633 of file G4SPSEneDistribution.cc
References G4SPSEneDistribution::threadLocal_t::alpha, Arb_alpha, Arb_cept, Arb_ezero, Arb_grad, G4SPSEneDistribution::threadLocal_t::cept, G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, G4SPSEneDistribution::threadLocal_t::Ezero, FatalException, G4cout, G4endl, G4Exception(), GenerateExpEnergies(), GenerateLinearEnergies(), GeneratePowEnergies(), G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4SPSEneDistribution::threadLocal_t::grad, IntType, IPDFArbEnergyH, G4SPSEneDistribution::threadLocal_t::particle_energy, SplineInt, threadLocalData, and verbosityLevel.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenEpnHistEnergies () private
Definition at line 1714 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1714 of file G4SPSEneDistribution.cc
References ConvertEPNToEnergy(), eneRndm, Epnflag, G4cout, G4endl, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFEnergyExist, IPDFEnergyH, G4TemplateAutoLock< _Mutex_t >::lock(), sum, threadLocalData, UDefEnergyH, G4TemplateAutoLock< _Mutex_t >::unlock(), and verbosityLevel.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateBbodyEnergies () private
Definition at line 1422 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1422 of file G4SPSEneDistribution.cc
References Acts::Test::at, BBHist, BBhistCalcd, Bbody_x, Calculate(), eneRndm, G4cout, G4endl, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4TemplateAutoLock< _Mutex_t >::lock(), t, threadLocalData, G4TemplateAutoLock< _Mutex_t >::unlock(), verbosityLevel, x1, x2, y1, and y2.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateBiasPowEnergies () private
Definition at line 1282 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1282 of file G4SPSEneDistribution.cc
References biasalpha, emax, G4SPSEneDistribution::threadLocal_t::Emax, CEMC_TOWER::emin, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, G4cout, G4endl, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), GetProbability(), CLHEP::normal(), G4SPSEneDistribution::threadLocal_t::particle_energy, threadLocalData, verbosityLevel, and G4SPSEneDistribution::threadLocal_t::weight.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateBremEnergies () private
Definition at line 1349 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1349 of file G4SPSEneDistribution.cc
References G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, check_license::err(), FatalException, G4cout, G4endl, G4Exception(), G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), k, G4SPSEneDistribution::threadLocal_t::particle_energy, propagation_timing::steps, Temp, threadLocalData, and verbosityLevel.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateCdgEnergies () private
Definition at line 1492 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1492 of file G4SPSEneDistribution.cc
References CDGhist, G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, G4cout, G4endl, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), keV, G4SPSEneDistribution::threadLocal_t::particle_energy, threadLocalData, and verbosityLevel.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateCPowEnergies () private
Definition at line 1209 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1209 of file G4SPSEneDistribution.cc
References Acts::Test::at, Calculate(), CP_x, CPHist, CPhistCalcd, eneRndm, G4cout, G4endl, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4TemplateAutoLock< _Mutex_t >::lock(), t, threadLocalData, G4TemplateAutoLock< _Mutex_t >::unlock(), verbosityLevel, x1, x2, y1, and y2.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateExpEnergies (G4bool bArb = false) private
Definition at line 1326 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1326 of file G4SPSEneDistribution.cc
References G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, G4SPSEneDistribution::threadLocal_t::Ezero, G4cout, G4endl, G4UniformRand, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4SPSEneDistribution::threadLocal_t::particle_energy, threadLocalData, and verbosityLevel.
Referenced by GenArbPointEnergies(), and GenerateOne().
void G4SPSEneDistribution::GenerateGaussEnergies () private
Definition at line 1106 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1106 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), MonoEnergy, SE, G4INCL::DeJongSpin::shoot(), and threadLocalData.
Referenced by GenerateOne().
void G4SPSEneDistribution::GenerateLinearEnergies (G4bool bArb = false) private
Definition at line 1113 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1113 of file G4SPSEneDistribution.cc
References G4SPSEneDistribution::threadLocal_t::cept, G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, G4cout, G4endl, G4UniformRand, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4SPSEneDistribution::threadLocal_t::grad, G4SPSEneDistribution::threadLocal_t::particle_energy, threadLocalData, and verbosityLevel.
Referenced by GenArbPointEnergies(), and GenerateOne().
void G4SPSEneDistribution::GenerateMonoEnergetic () private
Definition at line 1101 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1101 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), MonoEnergy, and threadLocalData.
Referenced by GenerateOne().
G4double G4SPSEneDistribution::GenerateOne (G4ParticleDefinition * a)
Definition at line 1859 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1859 of file G4SPSEneDistribution.cc
References a, alpha, G4SPSEneDistribution::threadLocal_t::alpha, ArbEmax, ArbEmin, Biased, cept, G4SPSEneDistribution::threadLocal_t::cept, Emax, G4SPSEneDistribution::threadLocal_t::Emax, Emin, G4SPSEneDistribution::threadLocal_t::Emin, EnergyDisType, Ezero, G4SPSEneDistribution::threadLocal_t::Ezero, G4BestUnit, G4cout, G4endl, G4Exception(), GenArbPointEnergies(), GenEpnHistEnergies(), GenerateBbodyEnergies(), GenerateBiasPowEnergies(), GenerateBremEnergies(), GenerateCdgEnergies(), GenerateCPowEnergies(), GenerateExpEnergies(), GenerateGaussEnergies(), GenerateLinearEnergies(), GenerateMonoEnergetic(), GeneratePowEnergies(), GenUserHistEnergies(), G4Cache< VALTYPE >::Get(), grad, G4SPSEneDistribution::threadLocal_t::grad, JustWarning, MonoEnergy, G4SPSEneDistribution::threadLocal_t::particle_definition, G4SPSEneDistribution::threadLocal_t::particle_energy, threadLocalData, weight, and G4SPSEneDistribution::threadLocal_t::weight.
Referenced by G4SingleParticleSource::GeneratePrimaryVertex().
void G4SPSEneDistribution::GeneratePowEnergies (G4bool bArb = false) private
Definition at line 1170 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1170 of file G4SPSEneDistribution.cc
References G4SPSEneDistribution::threadLocal_t::alpha, G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, eneRndm, G4cout, G4endl, G4UniformRand, G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4SPSEneDistribution::threadLocal_t::particle_energy, threadLocalData, and verbosityLevel.
Referenced by GenArbPointEnergies(), and GenerateOne().
void G4SPSEneDistribution::GenUserHistEnergies () private
Definition at line 1541 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1541 of file G4SPSEneDistribution.cc
References DiffSpec, G4PhysicsVector::DumpValues(), EnergySpec, eneRndm, FatalException, G4cout, G4endl, G4Exception(), G4SPSRandomGenerator::GenRandEnergy(), G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFEnergyExist, IPDFEnergyH, JustWarning, mass, particle_energy, sum, threadLocalData, UDefEnergyH, G4TemplateAutoLock< _Mutex_t >::unlock(), and verbosityLevel.
Referenced by GenerateOne().
G4double G4SPSEneDistribution::Getalpha ()
Definition at line 300 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 300 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
G4double G4SPSEneDistribution::GetArbEmax ()
Definition at line 203 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 203 of file G4SPSEneDistribution.cc
References ArbEmax.
G4double G4SPSEneDistribution::GetArbEmin ()
Definition at line 197 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 197 of file G4SPSEneDistribution.cc
References ArbEmin.
G4PhysicsOrderedFreeVector G4SPSEneDistribution::GetArbEnergyHisto ()
Definition at line 332 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 332 of file G4SPSEneDistribution.cc
References ArbEnergyH.
G4double G4SPSEneDistribution::Getcept ()
Definition at line 321 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 321 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
G4double G4SPSEneDistribution::GetEmax ()
Definition at line 215 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 215 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
G4double G4SPSEneDistribution::GetEmin ()
Definition at line 192 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 192 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
G4String G4SPSEneDistribution::GetEnergyDisType ()
Definition at line 180 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 180 of file G4SPSEneDistribution.cc
References EnergyDisType.
Referenced by UltraPrimaryGeneratorAction::GeneratePrimaries(), and G4GeneralParticleSource::ListSource().
G4double G4SPSEneDistribution::GetEzero ()
Definition at line 305 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 305 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
G4double G4SPSEneDistribution::Getgrad ()
Definition at line 316 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 316 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
G4String G4SPSEneDistribution::GetIntType ()
Definition at line 265 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 265 of file G4SPSEneDistribution.cc
References IntType.
G4double G4SPSEneDistribution::GetMonoEnergy ()
Definition at line 288 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 288 of file G4SPSEneDistribution.cc
References MonoEnergy.
G4double G4SPSEneDistribution::GetProbability (G4double ene)
Definition at line 1947 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1947 of file G4SPSEneDistribution.cc
References alpha, G4SPSEneDistribution::threadLocal_t::alpha, ArbEnergyH, G4SPSEneDistribution::threadLocal_t::cept, e, G4SPSEneDistribution::threadLocal_t::Emax, G4SPSEneDistribution::threadLocal_t::Emin, EnergyDisType, G4SPSEneDistribution::threadLocal_t::Ezero, G4cout, G4endl, G4Cache< VALTYPE >::Get(), G4SPSEneDistribution::threadLocal_t::grad, prob_norm, threadLocalData, and G4PhysicsVector::Value().
Referenced by GenerateBiasPowEnergies().
G4double G4SPSEneDistribution::GetSE ()
Definition at line 294 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 294 of file G4SPSEneDistribution.cc
References SE.
G4double G4SPSEneDistribution::GetTemp ()
Definition at line 310 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 310 of file G4SPSEneDistribution.cc
References Temp.
G4PhysicsOrderedFreeVector G4SPSEneDistribution::GetUserDefinedEnergyHisto ()
Definition at line 326 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 326 of file G4SPSEneDistribution.cc
References UDefEnergyH.
G4double G4SPSEneDistribution::GetWeight ()
Definition at line 283 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 283 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), and threadLocalData.
Referenced by G4SingleParticleSource::GeneratePrimaryVertex().
void G4SPSEneDistribution::InputDifferentialSpectra (G4bool value)
Definition at line 574 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 574 of file G4SPSEneDistribution.cc
References DiffSpec, G4cout, G4endl, and verbosityLevel.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::InputEnergySpectra (G4bool value)
Definition at line 566 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 566 of file G4SPSEneDistribution.cc
References EnergySpec, G4cout, G4endl, and verbosityLevel.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::LinearInterpolation () private
Definition at line 604 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 604 of file G4SPSEneDistribution.cc
References Arb_cept, Arb_grad, Arb_grad_cept_flag, ArbEnergyH, DiffSpec, G4PhysicsVector::DumpValues(), EnergySpec, FatalException, G4cout, G4endl, G4Exception(), G4Cache< VALTYPE >::Get(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFArbEnergyH, mass, maxi, G4PhysicsVector::ScaleVector(), sum, threadLocalData, and verbosityLevel.
Referenced by ArbInterpolate().
void G4SPSEneDistribution::LogInterpolation () private
Definition at line 737 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 737 of file G4SPSEneDistribution.cc
References Arb_alpha, Arb_alpha_Const_flag, Arb_Const, Arb_ezero, ArbEnergyH, DiffSpec, e, EnergySpec, FatalException, G4cout, G4endl, G4Exception(), G4Cache< VALTYPE >::Get(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFArbEnergyH, mass, maxi, G4PhysicsVector::ScaleVector(), sum, threadLocalData, and verbosityLevel.
Referenced by ArbInterpolate().
void G4SPSEneDistribution::ReSetHist (G4String atype)
Definition at line 1832 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 1832 of file G4SPSEneDistribution.cc
References ArbEnergyH, Emax, Emin, EpnEnergyH, G4cout, G4endl, IPDFArbEnergyH, IPDFArbExist, IPDFEnergyExist, IPDFEnergyH, UDefEnergyH, and ZeroPhysVector.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetAlpha (G4double alp)
Definition at line 230 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 230 of file G4SPSEneDistribution.cc
References alpha, G4Cache< VALTYPE >::Get(), and threadLocalData.
Referenced by G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetBeamSigmaInE (G4double e)
Definition at line 226 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 226 of file G4SPSEneDistribution.cc
References e, and SE.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetBiasAlpha (G4double alp)
Definition at line 236 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 236 of file G4SPSEneDistribution.cc
References biasalpha, and Biased.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetBiasRndm (G4SPSRandomGenerator * a)
Definition at line 271 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 271 of file G4SPSEneDistribution.cc
References a, and eneRndm.
Referenced by G4SingleParticleSource::G4SingleParticleSource().
void G4SPSEneDistribution::SetEmax (G4double ema)
Definition at line 209 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 209 of file G4SPSEneDistribution.cc
References Emax, G4Cache< VALTYPE >::Get(), and threadLocalData.
Referenced by G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex(), G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetEmin (G4double emi)
Definition at line 186 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 186 of file G4SPSEneDistribution.cc
References Emin, G4Cache< VALTYPE >::Get(), and threadLocalData.
Referenced by G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex(), G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetEnergyDisType (G4String DisType)
Definition at line 159 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 159 of file G4SPSEneDistribution.cc
References ArbEnergyH, EnergyDisType, EpnEnergyH, IPDFArbEnergyH, IPDFArbExist, IPDFEnergyExist, IPDFEnergyH, UDefEnergyH, and ZeroPhysVector.
Referenced by G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetEzero (G4double eze)
Definition at line 247 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 247 of file G4SPSEneDistribution.cc
References Ezero, G4Cache< VALTYPE >::Get(), and threadLocalData.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetGradient (G4double gr)
Definition at line 253 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 253 of file G4SPSEneDistribution.cc
References G4Cache< VALTYPE >::Get(), grad, and threadLocalData.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetInterCept (G4double c)
Definition at line 259 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 259 of file G4SPSEneDistribution.cc
References c, cept, G4Cache< VALTYPE >::Get(), and threadLocalData.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetMonoEnergy (G4double menergy)
Definition at line 221 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 221 of file G4SPSEneDistribution.cc
References MonoEnergy.
Referenced by HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetTemp (G4double tem)
Definition at line 242 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 242 of file G4SPSEneDistribution.cc
References Temp.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSEneDistribution::SetVerbosity (G4int a)
Definition at line 277 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 277 of file G4SPSEneDistribution.cc
References a, and verbosityLevel.
Referenced by G4SingleParticleSource::SetVerbosity().
void G4SPSEneDistribution::SplineInterpolation () private
Definition at line 995 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 995 of file G4SPSEneDistribution.cc
References ArbEnergyH, G4DataInterpolation::CubicSplineInterpolation(), DiffSpec, ei(), EnergySpec, FatalException, G4cout, G4endl, G4Exception(), G4Cache< VALTYPE >::Get(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFArbEnergyH, it, mass, maxi, G4PhysicsVector::ScaleVector(), SplineInt, Splinetemp, sum, threadLocalData, and verbosityLevel.
Referenced by ArbInterpolate().
void G4SPSEneDistribution::UserEnergyHisto (G4ThreeVector input)
Definition at line 338 of file G4SPSEneDistribution.cc.
View newest version in sPHENIX GitHub at line 338 of file G4SPSEneDistribution.cc
References Emax, G4cout, G4endl, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::InsertValues(), threadLocalData, UDefEnergyH, verbosityLevel, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
Member Data Documentation
G4double G4SPSEneDistribution::alpha private
Definition at line 270 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 270 of file G4SPSEneDistribution.hh
Referenced by CalculateCPowSpectrum(), G4SPSEneDistribution(), GenerateOne(), GetProbability(), and SetAlpha().
G4double* G4SPSEneDistribution::Arb_alpha private
Definition at line 308 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 308 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenArbPointEnergies(), LogInterpolation(), and ~G4SPSEneDistribution().
G4bool G4SPSEneDistribution::Arb_alpha_Const_flag private
Definition at line 310 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 310 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), LogInterpolation(), and ~G4SPSEneDistribution().
G4double* G4SPSEneDistribution::Arb_cept private
Definition at line 305 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 305 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenArbPointEnergies(), LinearInterpolation(), and ~G4SPSEneDistribution().
G4double* G4SPSEneDistribution::Arb_Const private
Definition at line 309 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 309 of file G4SPSEneDistribution.hh
Referenced by ExpInterpolation(), G4SPSEneDistribution(), LogInterpolation(), and ~G4SPSEneDistribution().
G4double* G4SPSEneDistribution::Arb_ezero private
Definition at line 312 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 312 of file G4SPSEneDistribution.hh
Referenced by ExpInterpolation(), G4SPSEneDistribution(), GenArbPointEnergies(), LogInterpolation(), and ~G4SPSEneDistribution().
G4bool G4SPSEneDistribution::Arb_ezero_flag private
Definition at line 313 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 313 of file G4SPSEneDistribution.hh
Referenced by ExpInterpolation(), G4SPSEneDistribution(), and ~G4SPSEneDistribution().
G4double* G4SPSEneDistribution::Arb_grad private
Definition at line 304 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 304 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenArbPointEnergies(), LinearInterpolation(), and ~G4SPSEneDistribution().
G4bool G4SPSEneDistribution::Arb_grad_cept_flag private
Definition at line 306 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 306 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), LinearInterpolation(), and ~G4SPSEneDistribution().
G4double G4SPSEneDistribution::ArbEmax private
Definition at line 314 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 314 of file G4SPSEneDistribution.hh
Referenced by ArbInterpolate(), G4SPSEneDistribution(), GenerateOne(), and GetArbEmax().
G4double G4SPSEneDistribution::ArbEmin private
Definition at line 314 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 314 of file G4SPSEneDistribution.hh
Referenced by ArbInterpolate(), G4SPSEneDistribution(), GenerateOne(), and GetArbEmin().
G4PhysicsOrderedFreeVector G4SPSEneDistribution::ArbEnergyH private
Definition at line 283 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 283 of file G4SPSEneDistribution.hh
Referenced by ArbEnergyHisto(), ArbEnergyHistoFile(), ArbInterpolate(), ExpInterpolation(), GetArbEnergyHisto(), GetProbability(), LinearInterpolation(), LogInterpolation(), ReSetHist(), SetEnergyDisType(), and SplineInterpolation().
std::vector<G4double>* G4SPSEneDistribution::BBHist private
Definition at line 290 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 290 of file G4SPSEneDistribution.hh
Referenced by BBInitHists(), CalculateBbodySpectrum(), G4SPSEneDistribution(), GenerateBbodyEnergies(), and ~G4SPSEneDistribution().
G4bool G4SPSEneDistribution::BBhistCalcd private
Definition at line 293 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 293 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), and GenerateBbodyEnergies().
G4bool G4SPSEneDistribution::BBhistInit private
Definition at line 292 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 292 of file G4SPSEneDistribution.hh
Referenced by BBInitHists(), Calculate(), and G4SPSEneDistribution().
std::vector<G4double>* G4SPSEneDistribution::Bbody_x private
Definition at line 291 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 291 of file G4SPSEneDistribution.hh
Referenced by BBInitHists(), CalculateBbodySpectrum(), G4SPSEneDistribution(), GenerateBbodyEnergies(), and ~G4SPSEneDistribution().
G4double G4SPSEneDistribution::biasalpha private
Definition at line 272 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 272 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateBiasPowEnergies(), and SetBiasAlpha().
G4bool G4SPSEneDistribution::Biased private
Definition at line 275 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 275 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateOne(), and SetBiasAlpha().
G4double G4SPSEneDistribution::CDGhist[3] private
Definition at line 286 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 286 of file G4SPSEneDistribution.hh
Referenced by CalculateCdgSpectrum(), and GenerateCdgEnergies().
G4double G4SPSEneDistribution::cept private
Definition at line 273 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 273 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateOne(), and SetInterCept().
std::vector<G4double>* G4SPSEneDistribution::CP_x private
Definition at line 296 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 296 of file G4SPSEneDistribution.hh
Referenced by CalculateCPowSpectrum(), CPInitHists(), G4SPSEneDistribution(), GenerateCPowEnergies(), and ~G4SPSEneDistribution().
std::vector<G4double>* G4SPSEneDistribution::CPHist private
Definition at line 295 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 295 of file G4SPSEneDistribution.hh
Referenced by CalculateCPowSpectrum(), CPInitHists(), G4SPSEneDistribution(), GenerateCPowEnergies(), and ~G4SPSEneDistribution().
G4bool G4SPSEneDistribution::CPhistCalcd private
Definition at line 298 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 298 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), and GenerateCPowEnergies().
G4bool G4SPSEneDistribution::CPhistInit private
Definition at line 297 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 297 of file G4SPSEneDistribution.hh
Referenced by Calculate(), CPInitHists(), and G4SPSEneDistribution().
G4bool G4SPSEneDistribution::DiffSpec private
Definition at line 277 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 277 of file G4SPSEneDistribution.hh
Referenced by ExpInterpolation(), G4SPSEneDistribution(), GenUserHistEnergies(), InputDifferentialSpectra(), LinearInterpolation(), LogInterpolation(), and SplineInterpolation().
G4double G4SPSEneDistribution::Emax private
Definition at line 269 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 269 of file G4SPSEneDistribution.hh
Referenced by EpnEnergyHisto(), G4SPSEneDistribution(), GenerateOne(), ReSetHist(), SetEmax(), and UserEnergyHisto().
G4double G4SPSEneDistribution::Emin private
Definition at line 269 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 269 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateOne(), ReSetHist(), and SetEmin().
G4String G4SPSEneDistribution::EnergyDisType private
Definition at line 264 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 264 of file G4SPSEneDistribution.hh
Referenced by ArbInterpolate(), Calculate(), G4SPSEneDistribution(), GenerateOne(), GetEnergyDisType(), GetProbability(), and SetEnergyDisType().
G4bool G4SPSEneDistribution::EnergySpec private
Definition at line 276 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 276 of file G4SPSEneDistribution.hh
Referenced by ExpInterpolation(), G4SPSEneDistribution(), GenUserHistEnergies(), InputEnergySpectra(), LinearInterpolation(), LogInterpolation(), and SplineInterpolation().
G4SPSRandomGenerator* G4SPSEneDistribution::eneRndm private
Definition at line 318 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 318 of file G4SPSEneDistribution.hh
Referenced by GenArbPointEnergies(), GenEpnHistEnergies(), GenerateBbodyEnergies(), GenerateBiasPowEnergies(), GenerateBremEnergies(), GenerateCdgEnergies(), GenerateCPowEnergies(), GenerateExpEnergies(), GenerateLinearEnergies(), GeneratePowEnergies(), GenUserHistEnergies(), and SetBiasRndm().
G4PhysicsOrderedFreeVector G4SPSEneDistribution::EpnEnergyH private
Definition at line 285 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 285 of file G4SPSEneDistribution.hh
Referenced by ConvertEPNToEnergy(), EpnEnergyHisto(), ReSetHist(), and SetEnergyDisType().
G4bool G4SPSEneDistribution::Epnflag private
Definition at line 282 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 282 of file G4SPSEneDistribution.hh
Referenced by ConvertEPNToEnergy(), EpnEnergyHisto(), and GenEpnHistEnergies().
G4double G4SPSEneDistribution::Ezero private
Definition at line 270 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 270 of file G4SPSEneDistribution.hh
Referenced by CalculateCPowSpectrum(), G4SPSEneDistribution(), GenerateOne(), and SetEzero().
G4double G4SPSEneDistribution::grad private
Definition at line 273 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 273 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateOne(), and SetGradient().
G4String G4SPSEneDistribution::IntType private
Definition at line 302 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 302 of file G4SPSEneDistribution.hh
Referenced by ArbInterpolate(), G4SPSEneDistribution(), GenArbPointEnergies(), and GetIntType().
G4PhysicsOrderedFreeVector G4SPSEneDistribution::IPDFArbEnergyH private
Definition at line 284 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 284 of file G4SPSEneDistribution.hh
Referenced by ExpInterpolation(), GenArbPointEnergies(), LinearInterpolation(), LogInterpolation(), ReSetHist(), SetEnergyDisType(), and SplineInterpolation().
G4bool G4SPSEneDistribution::IPDFArbExist private
Definition at line 282 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 282 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), ReSetHist(), and SetEnergyDisType().
G4bool G4SPSEneDistribution::IPDFEnergyExist private
Definition at line 282 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 282 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenEpnHistEnergies(), GenUserHistEnergies(), ReSetHist(), and SetEnergyDisType().
G4PhysicsOrderedFreeVector G4SPSEneDistribution::IPDFEnergyH private
Definition at line 281 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 281 of file G4SPSEneDistribution.hh
Referenced by GenEpnHistEnergies(), GenUserHistEnergies(), ReSetHist(), and SetEnergyDisType().
G4double G4SPSEneDistribution::MonoEnergy private
Definition at line 266 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 266 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateGaussEnergies(), GenerateMonoEnergetic(), GenerateOne(), GetMonoEnergy(), and SetMonoEnergy().
G4Mutex G4SPSEneDistribution::mutex private
Definition at line 328 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 328 of file G4SPSEneDistribution.hh
G4double G4SPSEneDistribution::particle_energy private
Definition at line 316 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 316 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), and GenUserHistEnergies().
G4double G4SPSEneDistribution::prob_norm private
Definition at line 274 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 274 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), and GetProbability().
G4double G4SPSEneDistribution::SE private
Definition at line 267 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 267 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), GenerateGaussEnergies(), GetSE(), and SetBeamSigmaInE().
std::vector<G4DataInterpolation*> G4SPSEneDistribution::SplineInt private
Definition at line 325 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 325 of file G4SPSEneDistribution.hh
Referenced by GenArbPointEnergies(), SplineInterpolation(), and ~G4SPSEneDistribution().
G4DataInterpolation* G4SPSEneDistribution::Splinetemp private
Definition at line 326 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 326 of file G4SPSEneDistribution.hh
Referenced by SplineInterpolation().
G4double G4SPSEneDistribution::Temp private
Definition at line 271 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 271 of file G4SPSEneDistribution.hh
Referenced by CalculateBbodySpectrum(), G4SPSEneDistribution(), GenerateBremEnergies(), GetTemp(), and SetTemp().
G4Cache<threadLocal_t> G4SPSEneDistribution::threadLocalData private
Definition at line 343 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 343 of file G4SPSEneDistribution.hh
Referenced by CalculateBbodySpectrum(), CalculateCdgSpectrum(), CalculateCPowSpectrum(), ConvertEPNToEnergy(), EpnEnergyHisto(), ExpInterpolation(), G4SPSEneDistribution(), GenArbPointEnergies(), GenEpnHistEnergies(), GenerateBbodyEnergies(), GenerateBiasPowEnergies(), GenerateBremEnergies(), GenerateCdgEnergies(), GenerateCPowEnergies(), GenerateExpEnergies(), GenerateGaussEnergies(), GenerateLinearEnergies(), GenerateMonoEnergetic(), GenerateOne(), GeneratePowEnergies(), GenUserHistEnergies(), Getalpha(), Getcept(), GetEmax(), GetEmin(), GetEzero(), Getgrad(), GetProbability(), GetWeight(), LinearInterpolation(), LogInterpolation(), SetAlpha(), SetEmax(), SetEmin(), SetEzero(), SetGradient(), SetInterCept(), SplineInterpolation(), and UserEnergyHisto().
G4PhysicsOrderedFreeVector G4SPSEneDistribution::UDefEnergyH private
Definition at line 280 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 280 of file G4SPSEneDistribution.hh
Referenced by ConvertEPNToEnergy(), GenEpnHistEnergies(), GenUserHistEnergies(), GetUserDefinedEnergyHisto(), ReSetHist(), SetEnergyDisType(), and UserEnergyHisto().
G4int G4SPSEneDistribution::verbosityLevel private
Definition at line 321 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 321 of file G4SPSEneDistribution.hh
Referenced by ArbEnergyHisto(), EpnEnergyHisto(), ExpInterpolation(), G4SPSEneDistribution(), GenArbPointEnergies(), GenEpnHistEnergies(), GenerateBbodyEnergies(), GenerateBiasPowEnergies(), GenerateBremEnergies(), GenerateCdgEnergies(), GenerateCPowEnergies(), GenerateExpEnergies(), GenerateLinearEnergies(), GeneratePowEnergies(), GenUserHistEnergies(), InputDifferentialSpectra(), InputEnergySpectra(), LinearInterpolation(), LogInterpolation(), SetVerbosity(), SplineInterpolation(), and UserEnergyHisto().
G4double G4SPSEneDistribution::weight private
Definition at line 265 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 265 of file G4SPSEneDistribution.hh
Referenced by G4SPSEneDistribution(), and GenerateOne().
G4PhysicsOrderedFreeVector G4SPSEneDistribution::ZeroPhysVector private
Definition at line 323 of file G4SPSEneDistribution.hh.
View newest version in sPHENIX GitHub at line 323 of file G4SPSEneDistribution.hh
Referenced by ReSetHist(), and SetEnergyDisType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4SPSEneDistribution.hh
geant4/tree/geant4-10.6-release/source/event/src/G4SPSEneDistribution.cc