ECCE @ EIC Software: G4BGGNucleonInelasticXS Class Reference
G4BGGNucleonInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGNucleonInelasticXS.hh>
Public Member Functions
G4BGGNucleonInelasticXS (const G4ParticleDefinition *)
~G4BGGNucleonInelasticXS () override
G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat) override
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm, const G4Material *mat) override
G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat) override
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
void CrossSectionDescription (std::ostream &) const override
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4double CoulombFactor (G4double kinEnergy, G4int Z)
G4BGGNucleonInelasticXS & operator= (const G4BGGNucleonInelasticXS &right)
G4BGGNucleonInelasticXS (const G4BGGNucleonInelasticXS &)
Private Attributes
G4double fGlauberEnergy
G4double fLowEnergy
const G4ParticleDefinition * theProton
G4ComponentGGHadronNucleusXsc * fGlauber
G4NucleonNuclearCrossSection * fNucleon
G4HadronNucleonXsc * fHadron
G4bool isProton
G4bool isMaster
Static Private Attributes
static G4double theGlauberFacP [93] = {0.0}
static G4double theCoulombFacP [93] = {0.0}
static G4double theGlauberFacN [93] = {0.0}
static G4double theCoulombFacN [93] = {0.0}
static G4int theA [93] = {0}
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 63 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BGGNucleonInelasticXS.hh
Constructor & Destructor Documentation
G4BGGNucleonInelasticXS::G4BGGNucleonInelasticXS (const G4ParticleDefinition * p) explicit
Definition at line 74 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 74 of file G4BGGNucleonInelasticXS.cc
References fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fNucleon, GeV, isMaster, isProton, MeV, G4Proton::Proton(), G4VCrossSectionDataSet::SetForAllAtomsAndEnergies(), theProton, and G4VCrossSectionDataSet::verboseLevel.
G4BGGNucleonInelasticXS::~G4BGGNucleonInelasticXS () override
Definition at line 93 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 93 of file G4BGGNucleonInelasticXS.cc
References fHadron.
G4BGGNucleonInelasticXS::G4BGGNucleonInelasticXS (const G4BGGNucleonInelasticXS &) private
Member Function Documentation
void G4BGGNucleonInelasticXS::BuildPhysicsTable (const G4ParticleDefinition & p) override virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 177 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 177 of file G4BGGNucleonInelasticXS.cc
References A(), G4NucleonNuclearCrossSection::BuildPhysicsTable(), CoulombFactor(), FatalException, fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fNucleon, G4cout, G4endl, G4Exception(), G4lrint(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4NistManager::GetAtomicMassAmu(), G4NucleonNuclearCrossSection::GetElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4ParticleDefinition::GetParticleName(), G4NistManager::Instance(), isMaster, isProton, mom, G4Neutron::Neutron(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetKineticEnergy(), theA, theCoulombFacN, theCoulombFacP, theGlauberFacN, theGlauberFacP, theProton, and G4VCrossSectionDataSet::verboseLevel.
G4double G4BGGNucleonInelasticXS::CoulombFactor (G4double kinEnergy, G4int Z) private
Definition at line 269 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 269 of file G4BGGNucleonInelasticXS.cc
References G4NuclearRadii::CoulombFactor(), G4Exp(), G4Log(), GeV, isProton, llog10, theA, theProton, and Z.
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
void G4BGGNucleonInelasticXS::CrossSectionDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 310 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 310 of file G4BGGNucleonInelasticXS.cc
G4double G4BGGNucleonInelasticXS::GetElementCrossSection (const G4DynamicParticle * dp, G4int Z, const G4Material * mat) override virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 119 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 119 of file G4BGGNucleonInelasticXS.cc
References barn, CoulombFactor(), Acts::VectorHelpers::cross(), fGlauber, fGlauberEnergy, fLowEnergy, fNucleon, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4NucleonNuclearCrossSection::GetElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), GetIsoCrossSection(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), CLHEP::GeV, isProton, min, theA, theCoulombFacN, theCoulombFacP, theGlauberFacN, theGlauberFacP, G4VCrossSectionDataSet::verboseLevel, and Z.
G4double G4BGGNucleonInelasticXS::GetIsoCrossSection (const G4DynamicParticle * dp, G4int Z, G4int A, const G4Isotope * iso = nullptr, const G4Element * elm = nullptr, const G4Material * mat = nullptr) override virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 153 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 153 of file G4BGGNucleonInelasticXS.cc
References barn, Acts::VectorHelpers::cross(), fHadron, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4HadronNucleonXsc::GetInelasticHadronNucleonXsc(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), CLHEP::GeV, G4HadronNucleonXsc::HadronNucleonXscNS(), theA, theProton, G4VCrossSectionDataSet::verboseLevel, and Z.
Referenced by GetElementCrossSection().
G4bool G4BGGNucleonInelasticXS::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material * mat) override virtual
Reimplemented from G4VCrossSectionDataSet.
Reimplemented in G4ParticleHPBGGNucleonInelasticXS.
Definition at line 100 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 100 of file G4BGGNucleonInelasticXS.cc
G4bool G4BGGNucleonInelasticXS::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * elm, const G4Material * mat) override virtual
Reimplemented from G4VCrossSectionDataSet.
Reimplemented in G4ParticleHPBGGNucleonInelasticXS.
Definition at line 108 of file G4BGGNucleonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 108 of file G4BGGNucleonInelasticXS.cc
G4BGGNucleonInelasticXS& G4BGGNucleonInelasticXS::operator= (const G4BGGNucleonInelasticXS & right) private
Member Data Documentation
G4ComponentGGHadronNucleusXsc* G4BGGNucleonInelasticXS::fGlauber private
Definition at line 108 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonInelasticXS(), and GetElementCrossSection().
G4double G4BGGNucleonInelasticXS::fGlauberEnergy private
Definition at line 97 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonInelasticXS(), and GetElementCrossSection().
G4HadronNucleonXsc* G4BGGNucleonInelasticXS::fHadron private
Definition at line 110 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 110 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonInelasticXS(), GetIsoCrossSection(), and ~G4BGGNucleonInelasticXS().
G4double G4BGGNucleonInelasticXS::fLowEnergy private
Definition at line 98 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 98 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonInelasticXS(), and GetElementCrossSection().
G4NucleonNuclearCrossSection* G4BGGNucleonInelasticXS::fNucleon private
Definition at line 109 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 109 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonInelasticXS(), and GetElementCrossSection().
G4bool G4BGGNucleonInelasticXS::isMaster private
Definition at line 112 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 112 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), and G4BGGNucleonInelasticXS().
G4bool G4BGGNucleonInelasticXS::isProton private
Definition at line 111 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 111 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactor(), G4BGGNucleonInelasticXS(), and GetElementCrossSection().
G4int G4BGGNucleonInelasticXS::theA = {0} static private
Definition at line 104 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 104 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactor(), GetElementCrossSection(), and GetIsoCrossSection().
G4double G4BGGNucleonInelasticXS::theCoulombFacN = {0.0} static private
Definition at line 103 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 103 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGNucleonInelasticXS::theCoulombFacP = {0.0} static private
Definition at line 101 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGNucleonInelasticXS::theGlauberFacN = {0.0} static private
Definition at line 102 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 102 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGNucleonInelasticXS::theGlauberFacP = {0.0} static private
Definition at line 100 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 100 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
const G4ParticleDefinition* G4BGGNucleonInelasticXS::theProton private
Definition at line 106 of file G4BGGNucleonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 106 of file G4BGGNucleonInelasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactor(), G4BGGNucleonInelasticXS(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGNucleonInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4BGGNucleonInelasticXS.cc