ECCE @ EIC Software: G4LindhardSorensenData Class Reference
G4LindhardSorensenData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4LindhardSorensenData.hh>
Public Member Functions
G4LindhardSorensenData ()
~G4LindhardSorensenData ()
G4double GetDeltaL (G4int Z, G4double gamma) const
Private Member Functions
void InitialiseData ()
G4double ComputeDeltaL (G4int Z, G4double x) const
G4LindhardSorensenData & operator= (const G4LindhardSorensenData &right)=delete
G4LindhardSorensenData (const G4LindhardSorensenData &)=delete
Private Attributes
G4double xmin
G4double xmax
G4PhysicsVector * data [9]
G4Pow * g4calc
Detailed Description
Definition at line 52 of file G4LindhardSorensenData.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LindhardSorensenData.hh
Constructor & Destructor Documentation
G4LindhardSorensenData::G4LindhardSorensenData () explicit
Definition at line 56 of file G4LindhardSorensenData.cc.
View newest version in sPHENIX GitHub at line 56 of file G4LindhardSorensenData.cc
References g4calc, G4Pow::GetInstance(), and InitialiseData().
G4LindhardSorensenData::~G4LindhardSorensenData ()
Definition at line 64 of file G4LindhardSorensenData.cc.
View newest version in sPHENIX GitHub at line 64 of file G4LindhardSorensenData.cc
References LVECT.
G4LindhardSorensenData::G4LindhardSorensenData (const G4LindhardSorensenData &) private delete
Member Function Documentation
G4double G4LindhardSorensenData::ComputeDeltaL (G4int Z, G4double x) const private
Definition at line 94 of file G4LindhardSorensenData.cc.
View newest version in sPHENIX GitHub at line 94 of file G4LindhardSorensenData.cc
References incremental_prev_tag::idx, NPOINT, x1, xmax, xmin, y, y1, ymax, and ymin.
Referenced by GetDeltaL().
G4double G4LindhardSorensenData::GetDeltaL (G4int Z, G4double gamma) const
Definition at line 71 of file G4LindhardSorensenData.cc.
View newest version in sPHENIX GitHub at line 71 of file G4LindhardSorensenData.cc
References ComputeDeltaL(), g4calc, G4Log(), incremental_prev_tag::idx, LVECT, min, x, y, y1, G4Pow::Z23(), and zlist.
Referenced by G4LindhardSorensenIonModel::CorrectionsAlongStep().
void G4LindhardSorensenData::InitialiseData () private
Definition at line 115 of file G4LindhardSorensenData.cc.
View newest version in sPHENIX GitHub at line 115 of file G4LindhardSorensenData.cc
References g4calc, G4Log(), G4Pow::logZ(), LVECT, NPOINT, xmax, and xmin.
Referenced by G4LindhardSorensenData().
G4LindhardSorensenData& G4LindhardSorensenData::operator= (const G4LindhardSorensenData & right) private delete
Member Data Documentation
G4PhysicsVector* G4LindhardSorensenData::data[9] private
Definition at line 76 of file G4LindhardSorensenData.hh.
View newest version in sPHENIX GitHub at line 76 of file G4LindhardSorensenData.hh
G4Pow* G4LindhardSorensenData::g4calc private
Definition at line 77 of file G4LindhardSorensenData.hh.
View newest version in sPHENIX GitHub at line 77 of file G4LindhardSorensenData.hh
Referenced by G4LindhardSorensenData(), GetDeltaL(), and InitialiseData().
G4double G4LindhardSorensenData::xmax private
Definition at line 74 of file G4LindhardSorensenData.hh.
View newest version in sPHENIX GitHub at line 74 of file G4LindhardSorensenData.hh
Referenced by ComputeDeltaL(), and InitialiseData().
G4double G4LindhardSorensenData::xmin private
Definition at line 73 of file G4LindhardSorensenData.hh.
View newest version in sPHENIX GitHub at line 73 of file G4LindhardSorensenData.hh
Referenced by ComputeDeltaL(), and InitialiseData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4LindhardSorensenData.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4LindhardSorensenData.cc