ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/scripts/PlotSingle.C File Reference
PlotSingle.C File Reference
Functions
hh[ixs] GetYaxis () -> SetTitle(axtit[1])
gPad SetLogy ()
if (ixs==0||ixs==2)
cout<< "Loop is completed ixs= "
<< ixs<< endl;leg[ixs]-> Draw ("SAME")
cout<< "Legend is done "
<< endl;c1-> Update ()
c1 Print ("a"+filp[ipart]+fil0[ixs]+".gif")
Variables
gtit = hed[ixs] + " Cross Section for " + part[ipart]
hh [ixs] = gPad->DrawFrame(x1[ixs], y1[ixs], x2[ixs], y2[ixs], gtit)
Function Documentation
cout<< "Loop is completed ixs= " << ixs << endl;leg[ixs]-> Draw ("SAME")
hh [ixs] GetYaxis () -> SetTitle(axtit[1])
if (ixs = =0 || ixs==2)
Definition at line 9 of file PlotSingle.C.
View newest version in sPHENIX GitHub at line 9 of file PlotSingle.C
c1 Print ("a"+filp+fil0+".gif" [ipart][ixs])
gPad SetLogy ()
cout<< "Legend is done " << endl;c1-> Update ()
Variable Documentation
gtit = hed[ixs] + " Cross Section for " + part[ipart]
Definition at line 5 of file PlotSingle.C.
View newest version in sPHENIX GitHub at line 5 of file PlotSingle.C
hh[ixs] = gPad->DrawFrame(x1[ixs], y1[ixs], x2[ixs], y2[ixs], gtit)
Definition at line 6 of file PlotSingle.C.
View newest version in sPHENIX GitHub at line 6 of file PlotSingle.C
Referenced by BEmcProfile::BEmcProfile(), G4ClassicalRK4::DumbStepper(), G4ConstRK4::DumbStepper(), G4PenelopeRayleighModel::GetPMaxTable(), G4EllipticalCone::GetPointOnSurface(), ludecy(), prt_set_style(), ptwXY_groupThreeFunctions(), pydecy(), pytbbn(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), and PHHoughSeeding::shift_coordinate_system().