ECCE @ EIC Software: G4TrajectoryDrawByAttribute Class Reference
G4TrajectoryDrawByAttribute Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByAttribute.hh>
Public Member Functions
G4TrajectoryDrawByAttribute (const G4String &name="Unspecified", G4VisTrajContext *context=0)
virtual ~G4TrajectoryDrawByAttribute ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const
virtual void Print (std::ostream &ostr) const
void Set (const G4String &attribute)
void AddIntervalContext (const G4String &name, G4VisTrajContext *context)
void AddValueContext (const G4String &name, G4VisTrajContext *context)
Public Member Functions inherited from G4VTrajectoryModel
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Private Types
enum Config { Interval, SingleValue }
typedef std::pair< G4String,
Config > Pair
typedef std::map< Pair,
G4VisTrajContext * > ContextMap
Private Attributes
G4String fAttName
ContextMap fContextMap
G4bool fFirst
G4bool fWarnedMissingAttribute
G4VAttValueFilter * filter
Detailed Description
Definition at line 41 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 41 of file G4TrajectoryDrawByAttribute.hh
Member Typedef Documentation
typedef std::map<Pair, G4VisTrajContext*> G4TrajectoryDrawByAttribute::ContextMap private
Definition at line 68 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrajectoryDrawByAttribute.hh
typedef std::pair<G4String, Config> G4TrajectoryDrawByAttribute::Pair private
Definition at line 67 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 67 of file G4TrajectoryDrawByAttribute.hh
Member Enumeration Documentation
enum G4TrajectoryDrawByAttribute::Config private
Enumerator:
Interval
SingleValue
Definition at line 65 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 65 of file G4TrajectoryDrawByAttribute.hh
Constructor & Destructor Documentation
G4TrajectoryDrawByAttribute::G4TrajectoryDrawByAttribute (const G4String & name = "Unspecified", G4VisTrajContext * context = 0)
Definition at line 40 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 40 of file G4TrajectoryDrawByAttribute.cc
G4TrajectoryDrawByAttribute::~G4TrajectoryDrawByAttribute () virtual
Definition at line 48 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 48 of file G4TrajectoryDrawByAttribute.cc
References fContextMap, and filter.
Member Function Documentation
void G4TrajectoryDrawByAttribute::AddIntervalContext (const G4String & name, G4VisTrajContext * context)
Definition at line 204 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 204 of file G4TrajectoryDrawByAttribute.cc
References FatalErrorInArgument, fContextMap, G4Exception(), and Interval.
void G4TrajectoryDrawByAttribute::AddValueContext (const G4String & name, G4VisTrajContext * context)
Definition at line 223 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 223 of file G4TrajectoryDrawByAttribute.cc
References FatalErrorInArgument, fContextMap, G4Exception(), and SingleValue.
void G4TrajectoryDrawByAttribute::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const virtual
Implements G4VTrajectoryModel.
Definition at line 61 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 61 of file G4TrajectoryDrawByAttribute.cc
References G4TrajectoryDrawerUtils::DrawLineAndPoints(), G4AttUtils::ExtractAttDef(), G4AttUtils::ExtractAttValue(), fAttName, fContextMap, fFirst, filter, fWarnedMissingAttribute, G4cout, G4endl, G4Exception(), G4VTrajectoryModel::GetContext(), G4AttFilterUtils::GetNewFilter(), G4VAttValueFilter::GetValidElement(), G4AttValue::GetValue(), G4VTrajectoryModel::GetVerbose(), Interval, G4String::isNull(), JustWarning, G4VAttValueFilter::LoadIntervalElement(), G4VAttValueFilter::LoadSingleValueElement(), G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and SingleValue.
void G4TrajectoryDrawByAttribute::Print (std::ostream & ostr) const virtual
Implements G4VTrajectoryModel.
Definition at line 177 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 177 of file G4TrajectoryDrawByAttribute.cc
References fAttName, fContextMap, G4endl, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::Name(), and G4VisTrajContext::Print().
void G4TrajectoryDrawByAttribute::Set (const G4String & attribute)
Definition at line 198 of file G4TrajectoryDrawByAttribute.cc.
View newest version in sPHENIX GitHub at line 198 of file G4TrajectoryDrawByAttribute.cc
References fAttName.
Member Data Documentation
G4String G4TrajectoryDrawByAttribute::fAttName private
Definition at line 71 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 71 of file G4TrajectoryDrawByAttribute.hh
Referenced by Draw(), Print(), and Set().
ContextMap G4TrajectoryDrawByAttribute::fContextMap private
Definition at line 72 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TrajectoryDrawByAttribute.hh
Referenced by AddIntervalContext(), AddValueContext(), Draw(), Print(), and ~G4TrajectoryDrawByAttribute().
G4bool G4TrajectoryDrawByAttribute::fFirst mutable private
Definition at line 75 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 75 of file G4TrajectoryDrawByAttribute.hh
Referenced by Draw().
G4VAttValueFilter* G4TrajectoryDrawByAttribute::filter mutable private
Definition at line 77 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 77 of file G4TrajectoryDrawByAttribute.hh
Referenced by Draw(), and ~G4TrajectoryDrawByAttribute().
G4bool G4TrajectoryDrawByAttribute::fWarnedMissingAttribute mutable private
Definition at line 76 of file G4TrajectoryDrawByAttribute.hh.
View newest version in sPHENIX GitHub at line 76 of file G4TrajectoryDrawByAttribute.hh
Referenced by Draw().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByAttribute.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryDrawByAttribute.cc