ECCE @ EIC Software: G02DetectorConstruction Class Reference
G02DetectorConstruction Class Reference
Detector construction used in GDML read/write example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/include/G02DetectorConstruction.hh>
Public Member Functions
G02DetectorConstruction ()
~G02DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
G4LogicalVolume * ConstructSubDetector1 ()
G4LogicalVolume * ConstructSubDetector2 ()
G4VPhysicalVolume * ConstructDetector ()
G4LogicalVolume * ConstructAssembly ()
G4LogicalVolume * ConstructParametrisationChamber ()
void ListOfMaterials ()
void SetReadFile (const G4String &File)
void SetWriteFile (const G4String &File)
void SetStepFile (const G4String &File)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4Material * fAir
G4Material * fAluminum
G4Material * fPb
G4Material * fXenon
G4GDMLParser fParser
G4String fReadFile
G4String fWriteFile
G4String fStepFile
G4int fWritingChoice
G02DetectorMessenger * fDetectorMessenger
G4double fExpHall_x
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction used in GDML read/write example.
Definition at line 54 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file G02DetectorConstruction.hh
Constructor & Destructor Documentation
G02DetectorConstruction::G02DetectorConstruction ()
Definition at line 88 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 88 of file G02DetectorConstruction.cc
References fDetectorMessenger, fExpHall_x, fReadFile, fStepFile, fWriteFile, fWritingChoice, and m.
G02DetectorConstruction::~G02DetectorConstruction ()
Definition at line 107 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 107 of file G02DetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
G4VPhysicalVolume * G02DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 116 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 116 of file G02DetectorConstruction.cc
References ConstructDetector(), expHall_y, expHall_z, fAir, fAluminum, fExpHall_x, fParser, fReadFile, fStepFile, fWriteFile, fWritingChoice, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4Material::GetMaterialTable(), G4GDMLParser::GetWorldVolume(), ListOfMaterials(), G4GDMLParser::ParseST(), G4GDMLParser::Read(), G4LogicalVolume::SetVisAttributes(), and G4GDMLParser::Write().
G4LogicalVolume * G02DetectorConstruction::ConstructAssembly ()
Definition at line 446 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 446 of file G02DetectorConstruction.cc
References G4AssemblyVolume::AddPlacedVolume(), fAir, fAluminum, fExpHall_x, fXenon, G4AssemblyVolume::MakeImprint(), pi, position, and Acts::Test::transform.
Referenced by ConstructSubDetector1().
G4VPhysicalVolume * G02DetectorConstruction::ConstructDetector ()
Definition at line 307 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 307 of file G02DetectorConstruction.cc
References ConstructParametrisationChamber(), ConstructSubDetector1(), ConstructSubDetector2(), expHall_y, expHall_z, fAir, fExpHall_x, G4ReflectionFactory::Instance(), G4ReflectionFactory::Place(), and Acts::Test::transform.
Referenced by Construct().
G4LogicalVolume * G02DetectorConstruction::ConstructParametrisationChamber ()
Definition at line 549 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 549 of file G02DetectorConstruction.cc
References cm, fAir, fAluminum, fExpHall_x, and kZAxis.
Referenced by ConstructDetector().
G4LogicalVolume * G02DetectorConstruction::ConstructSubDetector1 ()
Definition at line 404 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 404 of file G02DetectorConstruction.cc
References ConstructAssembly(), deg, fExpHall_x, and fPb.
Referenced by ConstructDetector().
G4LogicalVolume * G02DetectorConstruction::ConstructSubDetector2 ()
Definition at line 426 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 426 of file G02DetectorConstruction.cc
References fAluminum, and fExpHall_x.
Referenced by ConstructDetector().
void G02DetectorConstruction::ListOfMaterials ()
Definition at line 247 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 247 of file G02DetectorConstruction.cc
References a, G4Material::AddElement(), atmosphere, cm3, fAir, fAluminum, fPb, fXenon, Acts::UnitConstants::g, G4cout, G4endl, G4Element::GetElementTable(), G4Material::GetMaterialTable(), kelvin, kStateGas, mg, mole, and z.
Referenced by Construct().
void G02DetectorConstruction::SetReadFile (const G4String & File)
Definition at line 603 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 603 of file G02DetectorConstruction.cc
References fReadFile, and fWritingChoice.
Referenced by G02DetectorMessenger::SetNewValue().
void G02DetectorConstruction::SetStepFile (const G4String & File)
Definition at line 623 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 623 of file G02DetectorConstruction.cc
References fStepFile, and fWritingChoice.
Referenced by G02DetectorMessenger::SetNewValue().
void G02DetectorConstruction::SetWriteFile (const G4String & File)
Definition at line 613 of file G02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 613 of file G02DetectorConstruction.cc
References fWriteFile, and fWritingChoice.
Referenced by G02DetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* G02DetectorConstruction::fAir private
Definition at line 87 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file G02DetectorConstruction.hh
Referenced by Construct(), ConstructAssembly(), ConstructDetector(), ConstructParametrisationChamber(), and ListOfMaterials().
G4Material* G02DetectorConstruction::fAluminum private
Definition at line 88 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file G02DetectorConstruction.hh
Referenced by Construct(), ConstructAssembly(), ConstructParametrisationChamber(), ConstructSubDetector2(), and ListOfMaterials().
G02DetectorMessenger* G02DetectorConstruction::fDetectorMessenger private
Definition at line 105 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file G02DetectorConstruction.hh
Referenced by G02DetectorConstruction(), and ~G02DetectorConstruction().
G4double G02DetectorConstruction::fExpHall_x private
Definition at line 109 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file G02DetectorConstruction.hh
Referenced by Construct(), ConstructAssembly(), ConstructDetector(), ConstructParametrisationChamber(), ConstructSubDetector1(), ConstructSubDetector2(), and G02DetectorConstruction().
G4GDMLParser G02DetectorConstruction::fParser private
Definition at line 94 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file G02DetectorConstruction.hh
Referenced by Construct().
G4Material* G02DetectorConstruction::fPb private
Definition at line 89 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file G02DetectorConstruction.hh
Referenced by ConstructSubDetector1(), and ListOfMaterials().
G4String G02DetectorConstruction::fReadFile private
Definition at line 98 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 98 of file G02DetectorConstruction.hh
Referenced by Construct(), G02DetectorConstruction(), and SetReadFile().
G4String G02DetectorConstruction::fStepFile private
Definition at line 100 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file G02DetectorConstruction.hh
Referenced by Construct(), G02DetectorConstruction(), and SetStepFile().
G4String G02DetectorConstruction::fWriteFile private
Definition at line 99 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file G02DetectorConstruction.hh
Referenced by Construct(), G02DetectorConstruction(), and SetWriteFile().
G4int G02DetectorConstruction::fWritingChoice private
Definition at line 101 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file G02DetectorConstruction.hh
Referenced by Construct(), G02DetectorConstruction(), SetReadFile(), SetStepFile(), and SetWriteFile().
G4Material* G02DetectorConstruction::fXenon private
Definition at line 90 of file G02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file G02DetectorConstruction.hh
Referenced by ConstructAssembly(), and ListOfMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/include/G02DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/src/G02DetectorConstruction.cc