ECCE @ EIC Software: G4VTreeSceneHandler Class Reference
G4VTreeSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/Tree/include/G4VTreeSceneHandler.hh>
Public Member Functions
G4VTreeSceneHandler (G4VGraphicsSystem &system, const G4String &name)
virtual ~G4VTreeSceneHandler ()
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
void PostAddSolid ()
virtual void AddPrimitive (const G4Polyline &)
virtual void AddPrimitive (const G4Text &)
virtual void AddPrimitive (const G4Circle &)
virtual void AddPrimitive (const G4Square &)
virtual void AddPrimitive (const G4Polyhedron &)
virtual void AddPrimitive (const G4Polymarker &)
virtual void AddPrimitive (const G4Scale &)
virtual void BeginModeling ()
virtual void EndModeling ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void AddSolid (const G4Box &)
virtual void AddSolid (const G4Cons &)
virtual void AddSolid (const G4Orb &)
virtual void AddSolid (const G4Para &)
virtual void AddSolid (const G4Sphere &)
virtual void AddSolid (const G4Torus &)
virtual void AddSolid (const G4Trap &)
virtual void AddSolid (const G4Trd &)
virtual void AddSolid (const G4Tubs &)
virtual void AddSolid (const G4Ellipsoid &)
virtual void AddSolid (const G4Polycone &)
virtual void AddSolid (const G4Polyhedra &)
virtual void AddSolid (const G4TessellatedSolid &)
virtual void AddSolid (const G4VSolid &)
virtual void AddCompound (const G4VTrajectory &)
virtual void AddCompound (const G4VHit &)
virtual void AddCompound (const G4VDigi &)
virtual void AddCompound (const G4THitsMap< G4double > &)
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)
virtual void BeginPrimitives (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
virtual void ClearTransientStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Protected Attributes
const G4Transform3D * fpCurrentObjectTransformation
std::set< G4LogicalVolume * > fDrawnLVStore
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Static Protected Attributes
static G4int fSceneIdCount = 0
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Detailed Description
Definition at line 47 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VTreeSceneHandler.hh
Constructor & Destructor Documentation
G4VTreeSceneHandler::G4VTreeSceneHandler (G4VGraphicsSystem & system, const G4String & name)
Definition at line 43 of file G4VTreeSceneHandler.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VTreeSceneHandler.cc
G4VTreeSceneHandler::~G4VTreeSceneHandler () virtual
Definition at line 49 of file G4VTreeSceneHandler.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VTreeSceneHandler.cc
Member Function Documentation
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Polyline &) inline virtual
Implements G4VSceneHandler.
Definition at line 60 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VTreeSceneHandler.hh
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Text &) inline virtual
Implements G4VSceneHandler.
Definition at line 61 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VTreeSceneHandler.hh
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Circle &) inline virtual
Implements G4VSceneHandler.
Definition at line 62 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VTreeSceneHandler.hh
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Square &) inline virtual
Implements G4VSceneHandler.
Definition at line 63 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VTreeSceneHandler.hh
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Polyhedron &) inline virtual
Implements G4VSceneHandler.
Definition at line 64 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VTreeSceneHandler.hh
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Polymarker &) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 65 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VTreeSceneHandler.hh
virtual void G4VTreeSceneHandler::AddPrimitive (const G4Scale &) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 66 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VTreeSceneHandler.hh
void G4VTreeSceneHandler::BeginModeling () virtual
Reimplemented from G4VSceneHandler.
Reimplemented in G4ASCIITreeSceneHandler.
Definition at line 51 of file G4VTreeSceneHandler.cc.
View newest version in sPHENIX GitHub at line 51 of file G4VTreeSceneHandler.cc
References G4VSceneHandler::BeginModeling().
Referenced by G4ASCIITreeSceneHandler::BeginModeling().
void G4VTreeSceneHandler::EndModeling () virtual
Reimplemented from G4VSceneHandler.
Reimplemented in G4ASCIITreeSceneHandler.
Definition at line 55 of file G4VTreeSceneHandler.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VTreeSceneHandler.cc
References G4VSceneHandler::EndModeling(), and fDrawnLVStore.
Referenced by G4ASCIITreeSceneHandler::EndModeling().
void G4VTreeSceneHandler::PostAddSolid () virtual
Reimplemented from G4VSceneHandler.
void G4VTreeSceneHandler::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes & visAttribs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 61 of file G4VTreeSceneHandler.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VTreeSceneHandler.cc
References G4cerr, G4endl, G4PhysicalVolumeModel::GetDrawnPVPath(), and G4VSceneHandler::PreAddSolid().
Member Data Documentation
std::set<G4LogicalVolume*> G4VTreeSceneHandler::fDrawnLVStore protected
Definition at line 77 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VTreeSceneHandler.hh
Referenced by EndModeling().
const G4Transform3D* G4VTreeSceneHandler::fpCurrentObjectTransformation protected
Definition at line 76 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VTreeSceneHandler.hh
G4int G4VTreeSceneHandler::fSceneIdCount = 0 static protected
Definition at line 75 of file G4VTreeSceneHandler.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VTreeSceneHandler.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/Tree/include/G4VTreeSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/Tree/src/G4VTreeSceneHandler.cc