ECCE @ EIC Software: G4VecpssrLiModel Class Reference
G4VecpssrLiModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VecpssrLiModel.hh>
Public Member Functions
G4VecpssrLiModel ()
virtual ~G4VecpssrLiModel ()
virtual G4double CalculateL1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
virtual G4double CalculateL2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
virtual G4double CalculateL3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)=0
Private Member Functions
G4VecpssrLiModel (const G4VecpssrLiModel &)
G4VecpssrLiModel & operator= (const G4VecpssrLiModel &right)
Detailed Description
Definition at line 50 of file G4VecpssrLiModel.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VecpssrLiModel.hh
Constructor & Destructor Documentation
G4VecpssrLiModel::G4VecpssrLiModel ()
Definition at line 45 of file G4VecpssrLiModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VecpssrLiModel.cc
G4VecpssrLiModel::~G4VecpssrLiModel () virtual
Definition at line 50 of file G4VecpssrLiModel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VecpssrLiModel.cc
G4VecpssrLiModel::G4VecpssrLiModel (const G4VecpssrLiModel &) private
Member Function Documentation
virtual G4double G4VecpssrLiModel::CalculateL1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrBaseLixsModel, and G4ecpssrFormFactorLixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
virtual G4double G4VecpssrLiModel::CalculateL2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrBaseLixsModel, and G4ecpssrFormFactorLixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
virtual G4double G4VecpssrLiModel::CalculateL3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) pure virtual
Implemented in G4ecpssrBaseLixsModel, and G4ecpssrFormFactorLixsModel.
Referenced by G4teoCrossSection::CrossSection(), and G4teoCrossSection::GetCrossSection().
G4VecpssrLiModel& G4VecpssrLiModel::operator= (const G4VecpssrLiModel & right) private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VecpssrLiModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VecpssrLiModel.cc