ECCE @ EIC Software: G4ParticleHPAngularP Class Reference
G4ParticleHPAngularP Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPAngularP.hh>
Public Member Functions
G4ParticleHPAngularP ()
~G4ParticleHPAngularP ()
void Init (std::istream &aDataFile)
void Init (G4double e, G4int n)
void SetEnergy (G4double energy)
void SetCosTh (G4int l, G4double coeff)
void SetProb (G4int l, G4double coeff)
G4double GetCosTh (G4int l)
G4double GetProb (G4int l)
G4double GetEnergy ()
G4int GetNumberOfPoints ()
G4double GetCosTh ()
Private Attributes
G4double theEnergy
G4ParticleHPInterpolator theInt
G4int nCoeff
G4InterpolationManager theManager
G4double * theCosTh
G4double * theProb
Detailed Description
Definition at line 39 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPAngularP.hh
Constructor & Destructor Documentation
G4ParticleHPAngularP::G4ParticleHPAngularP () inline
Definition at line 43 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPAngularP.hh
References nCoeff, theCosTh, theEnergy, and theProb.
G4ParticleHPAngularP::~G4ParticleHPAngularP () inline
Definition at line 50 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPAngularP.hh
References theCosTh, and theProb.
Member Function Documentation
G4double G4ParticleHPAngularP::GetCosTh (G4int l) inline
Definition at line 84 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPAngularP.hh
References theCosTh.
Referenced by G4ParticleHPPhotonDist::GetPhotons().
G4double G4ParticleHPAngularP::GetCosTh () inline
Definition at line 88 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPAngularP.hh
References G4UniformRand, GetNumberOfPoints(), GetProb(), G4InterpolationManager::GetScheme(), G4ParticleHPInterpolator::Interpolate(), theInt, and theManager.
G4double G4ParticleHPAngularP::GetEnergy () inline
Definition at line 86 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPAngularP.hh
References theEnergy.
G4int G4ParticleHPAngularP::GetNumberOfPoints () inline
Definition at line 87 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPAngularP.hh
References nCoeff.
Referenced by GetCosTh().
G4double G4ParticleHPAngularP::GetProb (G4int l) inline
Definition at line 85 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPAngularP.hh
References theProb.
Referenced by GetCosTh().
void G4ParticleHPAngularP::Init (std::istream & aDataFile) inline
Definition at line 56 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPAngularP.hh
References CLHEP::eV, G4InterpolationManager::Init(), SetCosTh(), SetProb(), and theManager.
Referenced by G4ParticleHPPhotonDist::InitAngular().
void G4ParticleHPAngularP::Init (G4double e, G4int n) inline
Definition at line 72 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPAngularP.hh
References e, n, nCoeff, theCosTh, theEnergy, and theProb.
void G4ParticleHPAngularP::SetCosTh (G4int l, G4double coeff) inline
Definition at line 81 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPAngularP.hh
References theCosTh.
Referenced by Init().
void G4ParticleHPAngularP::SetEnergy (G4double energy) inline
Definition at line 80 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPAngularP.hh
References energy, and theEnergy.
void G4ParticleHPAngularP::SetProb (G4int l, G4double coeff) inline
Definition at line 82 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPAngularP.hh
References theProb.
Referenced by Init().
Member Data Documentation
G4int G4ParticleHPAngularP::nCoeff private
Definition at line 109 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPAngularP.hh
Referenced by G4ParticleHPAngularP(), GetNumberOfPoints(), and Init().
G4double* G4ParticleHPAngularP::theCosTh private
Definition at line 111 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPAngularP.hh
Referenced by G4ParticleHPAngularP(), GetCosTh(), Init(), SetCosTh(), and ~G4ParticleHPAngularP().
G4double G4ParticleHPAngularP::theEnergy private
Definition at line 107 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPAngularP.hh
Referenced by G4ParticleHPAngularP(), GetEnergy(), Init(), and SetEnergy().
G4ParticleHPInterpolator G4ParticleHPAngularP::theInt private
Definition at line 108 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPAngularP.hh
Referenced by GetCosTh().
G4InterpolationManager G4ParticleHPAngularP::theManager private
Definition at line 110 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPAngularP.hh
Referenced by GetCosTh(), and Init().
G4double* G4ParticleHPAngularP::theProb private
Definition at line 112 of file G4ParticleHPAngularP.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPAngularP.hh
Referenced by G4ParticleHPAngularP(), GetProb(), Init(), SetProb(), and ~G4ParticleHPAngularP().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPAngularP.hh