ECCE @ EIC Software: G4VTouchable Class Reference
G4VTouchable Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VTouchable.hh>
Public Member Functions
G4VTouchable ()
virtual ~G4VTouchable ()
virtual const G4ThreeVector & GetTranslation (G4int depth=0) const =0
virtual const G4RotationMatrix * GetRotation (G4int depth=0) const =0
virtual G4VPhysicalVolume * GetVolume (G4int depth=0) const
virtual G4VSolid * GetSolid (G4int depth=0) const
virtual G4int GetReplicaNumber (G4int depth=0) const
G4int GetCopyNumber (G4int depth=0) const
virtual G4int GetHistoryDepth () const
virtual G4int MoveUpHistory (G4int num_levels=1)
virtual void UpdateYourself (G4VPhysicalVolume *pPhysVol, const G4NavigationHistory *history=nullptr)
virtual const G4NavigationHistory * GetHistory () const
Detailed Description
Definition at line 102 of file G4VTouchable.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VTouchable.hh
Constructor & Destructor Documentation
G4VTouchable::G4VTouchable ()
Definition at line 33 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VTouchable.cc
G4VTouchable::~G4VTouchable () virtual
Definition at line 37 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VTouchable.cc
Member Function Documentation
G4int G4VTouchable::GetCopyNumber (G4int depth = 0) const inline
Referenced by G4RayTrajectory::AppendStep(), PHG4RICHSteppingAction::MakeHit(), Path(), ExTGTrackerSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), ExN02TrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), and G4RTSteppingAction::UserSteppingAction().
const G4NavigationHistory * G4VTouchable::GetHistory () const virtual
Reimplemented in G4TouchableHistory.
Definition at line 83 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 83 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), RE05CalorimeterSD::ProcessHits(), ScreenSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CCaloSD::SetToLocal(), PHG4SteppingAction::StoreLocalCoordinate(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), and PHG4OuterHcalSteppingAction::UserSteppingAction().
G4int G4VTouchable::GetHistoryDepth () const virtual
Reimplemented in G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable, and G4TouchableHistory.
Definition at line 76 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by G4RayTrajectory::AppendStep(), export_G4VTouchable(), Path(), and G4RTSteppingAction::UserSteppingAction().
G4int G4VTouchable::GetReplicaNumber (G4int depth = 0) const virtual
Reimplemented in G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable, G4TouchableHistory, and G4GMocrenTouchable.
Definition at line 55 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by DicomNestedPhantomParameterisation::ComputeMaterial(), RE02NestedPhantomParameterisation::ComputeMaterial(), export_G4VTouchable(), RE02PSEnergyDeposit::GetIndex(), G4PSNofSecondary3D::GetIndex(), RE02PSNofStep::GetIndex(), G4PSNofStep3D::GetIndex(), G4PSTermination3D::GetIndex(), G4PSPopulation3D::GetIndex(), G4PSStepChecker3D::GetIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSNofCollision3D::GetIndex(), G4PSPassageCellCurrent3D::GetIndex(), RE02PSPassageCellFlux::GetIndex(), G4PSTrackCounter3D::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4PSCellCharge3D::GetIndex(), G4PSMinKinEAtGeneration3D::GetIndex(), G4PSTrackLength3D::GetIndex(), G4PSPassageTrackLength3D::GetIndex(), G4PSPassageCellFlux3D::GetIndex(), RE02PSCellFlux::GetIndex(), G4PSCellFlux3D::GetIndex(), RE02PSFlatSurfaceCurrent::GetIndex(), G4PSCylinderSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceCurrent3D::GetIndex(), RE02PSFlatSurfaceFlux::GetIndex(), G4PSSphereSurfaceCurrent3D::GetIndex(), G4PSFlatSurfaceFlux3D::GetIndex(), G4PSSphereSurfaceFlux3D::GetIndex(), G4ImportanceProcess::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), RE05CalorimeterSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), LXePMTSD::ProcessHits_constStep(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), and G4ParallelWorldScoringProcess::Verbose().
virtual const G4RotationMatrix* G4VTouchable::GetRotation (G4int depth = 0) const pure virtual
Implemented in G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable, G4TouchableHistory, G4GRSVolume, G4GRSSolid, and G4GMocrenTouchable.
Referenced by export_G4VTouchable(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4VXTRenergyLoss::PostStepDoIt().
G4VSolid * G4VTouchable::GetSolid (G4int depth = 0) const virtual
Reimplemented in G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable, G4TouchableHistory, G4GRSVolume, and G4GRSSolid.
Definition at line 48 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by G4DNAMolecularDissociation::DecayIt(), and export_G4VTouchable().
virtual const G4ThreeVector& G4VTouchable::GetTranslation (G4int depth = 0) const pure virtual
Implemented in G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable, G4TouchableHistory, G4GRSVolume, G4GRSSolid, and G4GMocrenTouchable.
Referenced by export_G4VTouchable(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4VXTRenergyLoss::PostStepDoIt().
G4VPhysicalVolume * G4VTouchable::GetVolume (G4int depth = 0) const virtual
Reimplemented in G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable, G4TouchableHistory, and G4GRSVolume.
Definition at line 41 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4RayTrajectory::AppendStep(), G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4Track::CalculateVelocityForOpticalPhoton(), G4RichTrajectory::CreateAttValues(), G4RichTrajectoryPoint::CreateAttValues(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4DNAMolecularDissociation::DecayIt(), export_G4VTouchable(), PHG4OuterHcalSteppingAction::FieldChecker(), PHG4ZDCSteppingAction::FindIndexSMD(), PHG4ZDCSteppingAction::FindIndexZDC(), PHG4ForwardDualReadoutSteppingAction::FindTowerIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSDoseDeposit3D::GetIndex(), CCaloSD::getStepInfo(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), GFlashHitMaker::make(), PHG4RICHSteppingAction::MakeHit(), Path(), SplitProcess::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), G4HumanPhantomSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), B5HodoscopeSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExGflash1SensitiveDetector::ProcessHits(), ExGflash2SensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), LXePMTSD::ProcessHits_constStep(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4ParallelWorldProcess::SwitchMaterial(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), and G4RTSteppingAction::UserSteppingAction().
G4int G4VTouchable::MoveUpHistory (G4int num_levels = 1) virtual
Reimplemented in G4TouchableHistory.
Definition at line 62 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 62 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by export_G4VTouchable().
void G4VTouchable::UpdateYourself (G4VPhysicalVolume * pPhysVol, const G4NavigationHistory * history = nullptr) virtual
Reimplemented in G4TouchableHistory.
Definition at line 69 of file G4VTouchable.cc.
View newest version in sPHENIX GitHub at line 69 of file G4VTouchable.cc
References FatalException, and G4Exception().
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VTouchable.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4VTouchable.cc