ECCE @ EIC Software: MedicalBeam Class Reference
MedicalBeam Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/MedicalBeam/MedicalBeam.hh>
Public Types
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
enum FieldShape {
SQUARE =0, CIRCLE, kSQUARE =0, kCIRCLE,
kSQUARE =0, kCIRCLE, kSQUARE =0, kCIRCLE
}
Public Member Functions
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
MedicalBeam ()
~MedicalBeam ()
void SetParticleDefinition (G4ParticleDefinition *pd)
const G4ParticleDefinition * GetParticleDefinition () const
void SetKineticE (G4double e)
G4double GetKineticE () const
void SetSourcePosition (const G4ThreeVector &pos)
G4ThreeVector GetSourcePosition () const
void SetFieldShape (FieldShape shape)
FieldShape GetFieldShape () const
void SetSSD (G4double ssd)
G4double GetSSD () const
void SetFieldXY (G4double fx, G4double fy)
G4double GetFieldX () const
G4double GetFieldY () const
void SetFieldR (G4double r)
G4double GetFieldR () const
virtual void GeneratePrimaries (G4Event *anEvent)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Protected Member Functions
G4ThreeVector GenerateBeamDirection () const
Protected Attributes
G4ParticleDefinition * particle
G4double kineticE
G4ThreeVector sourcePosition
G4double SSD
FieldShape fieldShape
G4double fieldXY [2]
G4double fieldR
Private Member Functions
G4ThreeVector GenerateBeamDirection () const
G4ThreeVector GenerateBeamDirection () const
G4ThreeVector GenerateBeamDirection () const
Private Attributes
G4ParticleDefinition * fparticle
G4double fkineticE
G4ThreeVector fsourcePosition
G4double fSSD
FieldShape ffieldShape
G4double ffieldXY [2]
G4double ffieldR
Detailed Description
Definition at line 45 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 45 of file MedicalBeam.hh
Member Enumeration Documentation
enum MedicalBeam::FieldShape
Enumerator:
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 41 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 41 of file MedicalBeam.hh
enum MedicalBeam::FieldShape
Enumerator:
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 41 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 41 of file MedicalBeam.hh
enum MedicalBeam::FieldShape
Enumerator:
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 41 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 41 of file MedicalBeam.hh
enum MedicalBeam::FieldShape
Enumerator:
SQUARE
CIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
kSQUARE
kCIRCLE
Definition at line 47 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 47 of file MedicalBeam.hh
Constructor & Destructor Documentation
MedicalBeam::MedicalBeam ()
MedicalBeam::~MedicalBeam ()
MedicalBeam::MedicalBeam ()
MedicalBeam::~MedicalBeam ()
MedicalBeam::MedicalBeam ()
MedicalBeam::~MedicalBeam ()
MedicalBeam::MedicalBeam ()
Definition at line 48 of file MedicalBeam.cc.
View newest version in sPHENIX GitHub at line 48 of file MedicalBeam.cc
References cm, and fieldXY.
MedicalBeam::~MedicalBeam ()
Definition at line 62 of file MedicalBeam.cc.
View newest version in sPHENIX GitHub at line 62 of file MedicalBeam.cc
Member Function Documentation
G4ThreeVector MedicalBeam::GenerateBeamDirection () const protected
G4ThreeVector MedicalBeam::GenerateBeamDirection () const private
G4ThreeVector MedicalBeam::GenerateBeamDirection () const private
G4ThreeVector MedicalBeam::GenerateBeamDirection () const private
virtual void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 114 of file MedicalBeam.cc.
View newest version in sPHENIX GitHub at line 114 of file MedicalBeam.cc
References mass, ns, particle, sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
virtual void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void MedicalBeam::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
G4double MedicalBeam::GetFieldR () const
G4double MedicalBeam::GetFieldR () const
G4double MedicalBeam::GetFieldR () const
G4double MedicalBeam::GetFieldR () const inline
Definition at line 139 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 139 of file MedicalBeam.hh
References fieldR.
Referenced by BOOST_PYTHON_MODULE().
FieldShape MedicalBeam::GetFieldShape () const
FieldShape MedicalBeam::GetFieldShape () const
FieldShape MedicalBeam::GetFieldShape () const
MedicalBeam::FieldShape MedicalBeam::GetFieldShape () const inline
Definition at line 118 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 118 of file MedicalBeam.hh
References fieldShape.
Referenced by BOOST_PYTHON_MODULE().
G4double MedicalBeam::GetFieldX () const
G4double MedicalBeam::GetFieldX () const
G4double MedicalBeam::GetFieldX () const
G4double MedicalBeam::GetFieldX () const inline
Definition at line 130 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 130 of file MedicalBeam.hh
References fieldXY.
Referenced by BOOST_PYTHON_MODULE().
G4double MedicalBeam::GetFieldY () const
G4double MedicalBeam::GetFieldY () const
G4double MedicalBeam::GetFieldY () const
G4double MedicalBeam::GetFieldY () const inline
Definition at line 133 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 133 of file MedicalBeam.hh
References fieldXY.
Referenced by BOOST_PYTHON_MODULE().
G4double MedicalBeam::GetKineticE () const
G4double MedicalBeam::GetKineticE () const
G4double MedicalBeam::GetKineticE () const
G4double MedicalBeam::GetKineticE () const inline
Definition at line 106 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 106 of file MedicalBeam.hh
References kineticE.
Referenced by BOOST_PYTHON_MODULE().
const G4ParticleDefinition* MedicalBeam::GetParticleDefinition () const
const G4ParticleDefinition* MedicalBeam::GetParticleDefinition () const
const G4ParticleDefinition* MedicalBeam::GetParticleDefinition () const
const G4ParticleDefinition * MedicalBeam::GetParticleDefinition () const inline
Definition at line 100 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 100 of file MedicalBeam.hh
References particle.
G4ThreeVector MedicalBeam::GetSourcePosition () const
G4ThreeVector MedicalBeam::GetSourcePosition () const
G4ThreeVector MedicalBeam::GetSourcePosition () const
G4ThreeVector MedicalBeam::GetSourcePosition () const inline
Definition at line 112 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 112 of file MedicalBeam.hh
References sourcePosition.
Referenced by BOOST_PYTHON_MODULE().
G4double MedicalBeam::GetSSD () const
G4double MedicalBeam::GetSSD () const
G4double MedicalBeam::GetSSD () const
G4double MedicalBeam::GetSSD () const inline
Definition at line 124 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 124 of file MedicalBeam.hh
References SSD.
Referenced by BOOST_PYTHON_MODULE().
void MedicalBeam::SetFieldR (G4double r)
void MedicalBeam::SetFieldR (G4double r)
void MedicalBeam::SetFieldR (G4double r)
void MedicalBeam::SetFieldR (G4double r) inline
Definition at line 136 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 136 of file MedicalBeam.hh
References fieldR, and r.
Referenced by BOOST_PYTHON_MODULE().
void MedicalBeam::SetFieldShape (FieldShape shape)
void MedicalBeam::SetFieldShape (FieldShape shape)
void MedicalBeam::SetFieldShape (FieldShape shape)
void MedicalBeam::SetFieldShape (MedicalBeam::FieldShape shape) inline
Definition at line 115 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 115 of file MedicalBeam.hh
References fieldShape.
Referenced by BOOST_PYTHON_MODULE().
void MedicalBeam::SetFieldXY (G4double fx, G4double fy)
void MedicalBeam::SetFieldXY (G4double fx, G4double fy)
void MedicalBeam::SetFieldXY (G4double fx, G4double fy)
void MedicalBeam::SetFieldXY (G4double fx, G4double fy) inline
Definition at line 127 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 127 of file MedicalBeam.hh
References fieldXY.
void MedicalBeam::SetKineticE (G4double e)
void MedicalBeam::SetKineticE (G4double e)
void MedicalBeam::SetKineticE (G4double e)
void MedicalBeam::SetKineticE (G4double e) inline
Definition at line 103 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 103 of file MedicalBeam.hh
References e, and kineticE.
Referenced by BOOST_PYTHON_MODULE().
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd)
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd)
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd)
void MedicalBeam::SetParticleDefinition (G4ParticleDefinition * pd) inline
Definition at line 97 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 97 of file MedicalBeam.hh
References particle.
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos)
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos)
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos)
void MedicalBeam::SetSourcePosition (const G4ThreeVector & pos) inline
Definition at line 109 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 109 of file MedicalBeam.hh
References pos(), and sourcePosition.
Referenced by BOOST_PYTHON_MODULE().
void MedicalBeam::SetSSD (G4double ssd)
void MedicalBeam::SetSSD (G4double ssd)
void MedicalBeam::SetSSD (G4double ssd)
void MedicalBeam::SetSSD (G4double ssd) inline
Definition at line 121 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 121 of file MedicalBeam.hh
References SSD.
Referenced by BOOST_PYTHON_MODULE().
Member Data Documentation
G4double MedicalBeam::ffieldR private
Definition at line 83 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 83 of file MedicalBeam.hh
FieldShape MedicalBeam::ffieldShape private
Definition at line 81 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 81 of file MedicalBeam.hh
G4double MedicalBeam::ffieldXY private
Definition at line 82 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 82 of file MedicalBeam.hh
G4double MedicalBeam::fieldR protected
Definition at line 57 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 57 of file MedicalBeam.hh
Referenced by GetFieldR(), and SetFieldR().
FieldShape MedicalBeam::fieldShape protected
Definition at line 55 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 55 of file MedicalBeam.hh
Referenced by GetFieldShape(), and SetFieldShape().
G4double MedicalBeam::fieldXY[2] protected
Definition at line 56 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 56 of file MedicalBeam.hh
Referenced by GetFieldX(), GetFieldY(), MedicalBeam(), and SetFieldXY().
G4double MedicalBeam::fkineticE private
Definition at line 77 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 77 of file MedicalBeam.hh
G4ParticleDefinition * MedicalBeam::fparticle private
Definition at line 76 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 76 of file MedicalBeam.hh
G4ThreeVector MedicalBeam::fsourcePosition private
Definition at line 78 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 78 of file MedicalBeam.hh
G4double MedicalBeam::fSSD private
Definition at line 80 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 80 of file MedicalBeam.hh
G4double MedicalBeam::kineticE protected
Definition at line 51 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 51 of file MedicalBeam.hh
Referenced by GetKineticE(), and SetKineticE().
G4ParticleDefinition* MedicalBeam::particle protected
Definition at line 50 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 50 of file MedicalBeam.hh
Referenced by GetParticleDefinition(), and SetParticleDefinition().
G4ThreeVector MedicalBeam::sourcePosition protected
Definition at line 52 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 52 of file MedicalBeam.hh
Referenced by GetSourcePosition(), and SetSourcePosition().
G4double MedicalBeam::SSD protected
Definition at line 54 of file MedicalBeam.hh.
View newest version in sPHENIX GitHub at line 54 of file MedicalBeam.hh
Referenced by GetSSD(), and SetSSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/MedicalBeam/MedicalBeam.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/include/MedicalBeam.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/include/MedicalBeam.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/include/MedicalBeam.hh
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/MedicalBeam/MedicalBeam.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/src/MedicalBeam.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/src/MedicalBeam.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/src/MedicalBeam.cc