ECCE @ EIC Software: G4PixeShellDataSet Class Reference
G4PixeShellDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4PixeShellDataSet.hh>
Public Member Functions
G4PixeShellDataSet (G4int Z, G4IInterpolator *algo, const G4String &modelK="ecpssr", const G4String &modelL="ecpssr", const G4String &modelM="ecpssr", G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4PixeShellDataSet ()
virtual G4double FindValue (G4double energy, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4IDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4IDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *energies, G4DataVector *data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4IDataSet
G4IDataSet ()
virtual ~G4IDataSet ()
Protected Member Functions
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4IInterpolator * GetAlgorithm () const
void CleanUpComponents (void)
Private Member Functions
G4String FullFileName (const G4String &particleType, const G4String &subShell) const
G4int TranslateShell (const G4String &subShell) const
G4PixeShellDataSet ()
G4PixeShellDataSet (const G4PixeShellDataSet &copy)
G4PixeShellDataSet & operator= (const G4PixeShellDataSet &right)
Private Attributes
std::vector< G4IDataSet * > components
G4int z
G4IInterpolator * algorithm
std::vector< G4String > crossModel
G4double unitEnergies
G4double unitData
std::vector< G4String > shellName
std::vector< G4String > subShellName
Detailed Description
Definition at line 56 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 56 of file G4PixeShellDataSet.hh
Constructor & Destructor Documentation
G4PixeShellDataSet::G4PixeShellDataSet (G4int Z, G4IInterpolator * algo, const G4String & modelK = "ecpssr", const G4String & modelL = "ecpssr", const G4String & modelM = "ecpssr", G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 47 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PixeShellDataSet.cc
References algorithm, crossModel, FatalException, G4Exception(), shellName, and subShellName.
G4PixeShellDataSet::~G4PixeShellDataSet () virtual
Definition at line 95 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 95 of file G4PixeShellDataSet.cc
References algorithm, and CleanUpComponents().
G4PixeShellDataSet::G4PixeShellDataSet () private
G4PixeShellDataSet::G4PixeShellDataSet (const G4PixeShellDataSet & copy) private
Member Function Documentation
virtual void G4PixeShellDataSet::AddComponent (G4IDataSet * dataSet) inline virtual
Implements G4IDataSet.
Definition at line 77 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4PixeShellDataSet.hh
References components.
Referenced by LoadData().
void G4PixeShellDataSet::CleanUpComponents (void) protected
Definition at line 191 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 191 of file G4PixeShellDataSet.cc
References components.
Referenced by LoadData(), and ~G4PixeShellDataSet().
G4double G4PixeShellDataSet::FindValue (G4double energy, G4int componentId = 0) const virtual
Implements G4IDataSet.
Definition at line 102 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 102 of file G4PixeShellDataSet.cc
References components.
G4String G4PixeShellDataSet::FullFileName (const G4String & particleType, const G4String & subShell) const private
Definition at line 201 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 201 of file G4PixeShellDataSet.cc
References crossModel, FatalException, G4Exception(), shellName, test(), and TranslateShell().
Referenced by LoadData().
const G4IInterpolator* G4PixeShellDataSet::GetAlgorithm () const inline protected
Definition at line 102 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PixeShellDataSet.hh
References algorithm.
virtual const G4IDataSet* G4PixeShellDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4IDataSet.
Definition at line 74 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PixeShellDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), and PrintData().
virtual const G4DataVector& G4PixeShellDataSet::GetData (G4int componentId) const inline virtual
Implements G4IDataSet.
Definition at line 86 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PixeShellDataSet.hh
References GetComponent(), and G4IDataSet::GetData().
virtual const G4DataVector& G4PixeShellDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4IDataSet.
Definition at line 83 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PixeShellDataSet.hh
References GetComponent(), and G4IDataSet::GetEnergies().
G4double G4PixeShellDataSet::GetUnitData () const inline protected
Definition at line 101 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PixeShellDataSet.hh
References unitData.
G4double G4PixeShellDataSet::GetUnitEnergies () const inline protected
Definition at line 100 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PixeShellDataSet.hh
References unitEnergies.
G4bool G4PixeShellDataSet::LoadData (const G4String & fileName) virtual
Implements G4IDataSet.
Definition at line 159 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 159 of file G4PixeShellDataSet.cc
References AddComponent(), algorithm, CleanUpComponents(), FullFileName(), G4IDataSet::LoadData(), subShellName, and z.
virtual size_t G4PixeShellDataSet::NumberOfComponents (void) const inline virtual
Implements G4IDataSet.
Definition at line 80 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4PixeShellDataSet.hh
References components.
Referenced by PrintData().
G4PixeShellDataSet& G4PixeShellDataSet::operator= (const G4PixeShellDataSet & right) private
void G4PixeShellDataSet::PrintData (void) const virtual
Implements G4IDataSet.
Definition at line 119 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 119 of file G4PixeShellDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4IDataSet::PrintData().
virtual G4double G4PixeShellDataSet::RandomSelect (G4int) const inline virtual
Implements G4IDataSet.
Definition at line 96 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 96 of file G4PixeShellDataSet.hh
G4bool G4PixeShellDataSet::SaveData (const G4String & fileName) const virtual
Implements G4IDataSet.
Definition at line 184 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 184 of file G4PixeShellDataSet.cc
void G4PixeShellDataSet::SetEnergiesData (G4DataVector * energies, G4DataVector * data, G4int componentId) virtual
Implements G4IDataSet.
Definition at line 137 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 137 of file G4PixeShellDataSet.cc
References components, FatalException, G4Exception(), message(), and G4IDataSet::SetEnergiesData().
G4int G4PixeShellDataSet::TranslateShell (const G4String & subShell) const private
Definition at line 238 of file G4PixeShellDataSet.cc.
View newest version in sPHENIX GitHub at line 238 of file G4PixeShellDataSet.cc
Referenced by FullFileName().
Member Data Documentation
G4IInterpolator* G4PixeShellDataSet::algorithm private
Definition at line 120 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 120 of file G4PixeShellDataSet.hh
Referenced by G4PixeShellDataSet(), GetAlgorithm(), LoadData(), and ~G4PixeShellDataSet().
std::vector<G4IDataSet*> G4PixeShellDataSet::components private
Definition at line 117 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PixeShellDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), and SetEnergiesData().
std::vector<G4String> G4PixeShellDataSet::crossModel private
Definition at line 125 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PixeShellDataSet.hh
Referenced by FullFileName(), and G4PixeShellDataSet().
std::vector<G4String> G4PixeShellDataSet::shellName private
Definition at line 128 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 128 of file G4PixeShellDataSet.hh
Referenced by FullFileName(), and G4PixeShellDataSet().
std::vector<G4String> G4PixeShellDataSet::subShellName private
Definition at line 129 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 129 of file G4PixeShellDataSet.hh
Referenced by G4PixeShellDataSet(), and LoadData().
G4double G4PixeShellDataSet::unitData private
Definition at line 127 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PixeShellDataSet.hh
Referenced by GetUnitData().
G4double G4PixeShellDataSet::unitEnergies private
Definition at line 126 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 126 of file G4PixeShellDataSet.hh
Referenced by GetUnitEnergies().
G4int G4PixeShellDataSet::z private
Definition at line 119 of file G4PixeShellDataSet.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PixeShellDataSet.hh
Referenced by LoadData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4PixeShellDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/src/G4PixeShellDataSet.cc