ECCE @ EIC Software: G4InuclParticle Class Reference
G4InuclParticle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclParticle.hh>
Public Types
enum Model {
DefaultModel, bullet, target, EPCollider,
INCascader, NonEquilib, Equilib, Fissioner,
BigBanger, PreCompound, Coalescence
}
Public Member Functions
G4InuclParticle ()
G4InuclParticle (const G4DynamicParticle &dynPart, Model model=DefaultModel)
G4InuclParticle (const G4LorentzVector &mom, Model model=DefaultModel)
virtual ~G4InuclParticle ()
G4InuclParticle (const G4InuclParticle &right)
G4InuclParticle & operator= (const G4InuclParticle &right)
G4bool operator== (const G4InuclParticle &right)
G4bool operator!= (const G4InuclParticle &right)
void setEnergy ()
void setMomentum (const G4LorentzVector &mom)
void setKineticEnergy (G4double ekin)
void setMass (G4double mass)
G4double getMass () const
G4double getCharge () const
G4double getKineticEnergy () const
G4double getEnergy () const
G4double getMomModule () const
G4LorentzVector getMomentum () const
virtual void print (std::ostream &os) const
const G4ParticleDefinition * getDefinition () const
const G4DynamicParticle & getDynamicParticle () const
void setModel (Model model)
Model getModel () const
Protected Member Functions
G4InuclParticle (const G4ParticleDefinition *pd, Model model=DefaultModel)
G4InuclParticle (const G4ParticleDefinition *pd, const G4LorentzVector &mom, Model model=DefaultModel)
G4InuclParticle (const G4ParticleDefinition *pd, G4double ekin, Model model=DefaultModel)
void setDefinition (const G4ParticleDefinition *pd)
Private Attributes
G4DynamicParticle pDP
Model modelId
Detailed Description
Definition at line 52 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 52 of file G4InuclParticle.hh
Member Enumeration Documentation
enum G4InuclParticle::Model
Enumerator:
DefaultModel
bullet
target
EPCollider
INCascader
NonEquilib
Equilib
Fissioner
BigBanger
PreCompound
Coalescence
Definition at line 66 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 66 of file G4InuclParticle.hh
Constructor & Destructor Documentation
G4InuclParticle::G4InuclParticle () inline
Definition at line 71 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 71 of file G4InuclParticle.hh
G4InuclParticle::G4InuclParticle (const G4DynamicParticle & dynPart, Model model = DefaultModel) inline
Definition at line 73 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 73 of file G4InuclParticle.hh
G4InuclParticle::G4InuclParticle (const G4LorentzVector & mom, Model model = DefaultModel) inline
Definition at line 76 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 76 of file G4InuclParticle.hh
References CLHEP::GeV, CLHEP::MeV, pDP, and G4DynamicParticle::Set4Momentum().
virtual G4InuclParticle::~G4InuclParticle () inline virtual
Definition at line 79 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 79 of file G4InuclParticle.hh
G4InuclParticle::G4InuclParticle (const G4InuclParticle & right) inline
Definition at line 82 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 82 of file G4InuclParticle.hh
G4InuclParticle::G4InuclParticle (const G4ParticleDefinition * pd, Model model = DefaultModel) inline explicit protected
Definition at line 146 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 146 of file G4InuclParticle.hh
References setDefinition().
G4InuclParticle::G4InuclParticle (const G4ParticleDefinition * pd, const G4LorentzVector & mom, G4InuclParticle::Model model = DefaultModel) protected
Definition at line 43 of file G4InuclParticle.cc.
View newest version in sPHENIX GitHub at line 43 of file G4InuclParticle.cc
References setDefinition(), and setMomentum().
G4InuclParticle::G4InuclParticle (const G4ParticleDefinition * pd, G4double ekin, Model model = DefaultModel) inline protected
Definition at line 156 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 156 of file G4InuclParticle.hh
Member Function Documentation
G4double G4InuclParticle::getCharge () const inline
Definition at line 110 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 110 of file G4InuclParticle.hh
References G4DynamicParticle::GetCharge(), and pDP.
Referenced by G4ElementaryParticleCollider::collide(), G4CascadeCheckBalance::collide(), G4IntraNucleiCascader::generateCascade(), G4NucleiModel::generateParticleFate(), G4CascadeHistory::GuessTarget(), G4CascadeColliderBase::inelasticInteractionPossible(), and G4IntraNucleiCascader::setupCascade().
const G4ParticleDefinition* G4InuclParticle::getDefinition () const inline
Definition at line 132 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 132 of file G4InuclParticle.hh
References G4DynamicParticle::GetDefinition(), and pDP.
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4InuclElementaryParticle::baryon(), G4LightTargetCollider::collide(), G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4IntraNucleiCascader::decayTrappedParticle(), G4CascadParticle::G4CascadParticle(), G4ElementaryParticleCollider::generateSCMmuonAbsorption(), G4ElementaryParticleCollider::generateSCMpionAbsorption(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4InuclNuclei::getA(), G4InuclNuclei::getNucleiMass(), G4InuclNuclei::getZ(), G4InuclNuclei::print(), G4CascadeHistory::PrintEntry(), G4CascadeInterface::retryInelasticNucleus(), G4CascadeInterface::retryInelasticProton(), G4LightTargetCollider::SingleNucleonScattering(), and G4InuclElementaryParticle::type().
const G4DynamicParticle& G4InuclParticle::getDynamicParticle () const inline
Definition at line 136 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 136 of file G4InuclParticle.hh
References pDP.
Referenced by G4CascadeInterface::makeDynamicParticle().
G4double G4InuclParticle::getEnergy () const inline
Definition at line 118 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 118 of file G4InuclParticle.hh
References G4DynamicParticle::GetTotalEnergy(), CLHEP::GeV, CLHEP::MeV, and pDP.
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4CascadeInterface::checkFinalResult(), G4IntraNucleiCascader::decayTrappedParticle(), G4NucleiModel::initializeCascad(), and G4ParticleLargerBeta::operator()().
G4double G4InuclParticle::getKineticEnergy () const inline
Definition at line 114 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 114 of file G4InuclParticle.hh
References G4DynamicParticle::GetKineticEnergy(), CLHEP::GeV, CLHEP::MeV, and pDP.
Referenced by G4LightTargetCollider::collide(), G4CascadeRecoilMaker::collide(), G4IntraNucleiCascader::generateCascade(), G4NucleiModel::initializeCascad(), G4CascadeInterface::makeDynamicParticle(), G4ParticleLargerEkin::operator()(), G4InuclCollider::photonuclearOkay(), G4InuclNuclei::setExitationEnergy(), G4LightTargetCollider::SingleNucleonScattering(), and G4NucleiModel::worthToPropagate().
G4double G4InuclParticle::getMass () const inline
Definition at line 106 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 106 of file G4InuclParticle.hh
References G4DynamicParticle::GetMass(), CLHEP::GeV, CLHEP::MeV, and pDP.
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4NonEquilibriumEvaporator::deExcite(), G4IntraNucleiCascader::generateCascade(), G4InuclNuclei::getExitationEnergy(), G4NucleiModel::initializeCascad(), G4InuclCollider::photonuclearOkay(), G4InuclNuclei::print(), G4InuclNuclei::setExitationEnergy(), and setMomentum().
Model G4InuclParticle::getModel () const inline
Definition at line 142 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 142 of file G4InuclParticle.hh
References modelId.
G4LorentzVector G4InuclParticle::getMomentum () const inline
Definition at line 126 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 126 of file G4InuclParticle.hh
References G4DynamicParticle::Get4Momentum(), CLHEP::GeV, CLHEP::MeV, and pDP.
Referenced by G4LightTargetCollider::collide(), G4CascadeCheckBalance::collide(), G4IntraNucleiCascader::decayTrappedParticle(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4CascadeCoalescence::getClusterMomentum(), G4CascadParticle::getMomentum(), G4IntraNucleiCascader::initialize(), G4CascadeInterface::makeDynamicParticle(), G4InuclNuclei::makeG4Fragment(), G4CascadeCoalescence::maxDeltaP(), print(), G4LorentzConvertor::setBullet(), G4CollisionOutput::setOnShell(), G4LorentzConvertor::setTarget(), and G4LightTargetCollider::SingleNucleonScattering().
G4double G4InuclParticle::getMomModule () const inline
Definition at line 122 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 122 of file G4InuclParticle.hh
References G4DynamicParticle::GetTotalMomentum(), CLHEP::GeV, CLHEP::MeV, and pDP.
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4ElementaryParticleCollider::collide(), and G4ParticleLargerBeta::operator()().
G4bool G4InuclParticle::operator!= (const G4InuclParticle & right) inline
Definition at line 92 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 92 of file G4InuclParticle.hh
References operator==().
G4InuclParticle & G4InuclParticle::operator= (const G4InuclParticle & right)
Definition at line 53 of file G4InuclParticle.cc.
View newest version in sPHENIX GitHub at line 53 of file G4InuclParticle.cc
References modelId, and pDP.
Referenced by G4InuclElementaryParticle::operator=(), and G4InuclNuclei::operator=().
G4bool G4InuclParticle::operator== (const G4InuclParticle & right) inline
Definition at line 88 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 88 of file G4InuclParticle.hh
References pDP.
Referenced by operator!=().
void G4InuclParticle::print (std::ostream & os) const virtual
Reimplemented in G4InuclNuclei, and G4InuclElementaryParticle.
Definition at line 92 of file G4InuclParticle.cc.
View newest version in sPHENIX GitHub at line 92 of file G4InuclParticle.cc
References CLHEP::HepLorentzVector::e(), getMomentum(), modelId, mom, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), and CLHEP::HepLorentzVector::rho().
Referenced by operator<<(), G4InuclElementaryParticle::print(), and G4InuclNuclei::print().
void G4InuclParticle::setDefinition (const G4ParticleDefinition * pd) protected
Definition at line 69 of file G4InuclParticle.cc.
View newest version in sPHENIX GitHub at line 69 of file G4InuclParticle.cc
References pDP, and G4DynamicParticle::SetDefinition().
Referenced by G4InuclNuclei::clear(), G4InuclNuclei::fill(), and G4InuclParticle().
void G4InuclParticle::setEnergy () inline
Definition at line 97 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 97 of file G4InuclParticle.hh
void G4InuclParticle::setKineticEnergy (G4double ekin) inline
Definition at line 102 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 102 of file G4InuclParticle.hh
References CLHEP::GeV, CLHEP::MeV, pDP, and G4DynamicParticle::SetKineticEnergy().
Referenced by G4InuclNuclei::fill(), and G4InuclNuclei::setExitationEnergy().
void G4InuclParticle::setMass (G4double mass) inline
Definition at line 104 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 104 of file G4InuclParticle.hh
References CLHEP::GeV, CLHEP::MeV, pDP, and G4DynamicParticle::SetMass().
Referenced by G4InuclNuclei::setExitationEnergy().
void G4InuclParticle::setModel (Model model) inline
Definition at line 141 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 141 of file G4InuclParticle.hh
References modelId.
Referenced by G4InuclNuclei::clear(), G4NonEquilibriumEvaporator::deExcite(), and G4InuclNuclei::fill().
void G4InuclParticle::setMomentum (const G4LorentzVector & mom)
Definition at line 76 of file G4InuclParticle.cc.
View newest version in sPHENIX GitHub at line 76 of file G4InuclParticle.cc
References e, getMass(), GeV, CLHEP::HepLorentzVector::m(), mass, MeV, pDP, G4DynamicParticle::Set4Momentum(), G4DynamicParticle::SetMomentum(), and CLHEP::HepLorentzVector::vect().
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4InuclNuclei::fill(), G4InuclParticle(), and G4CascadParticle::updateParticleMomentum().
Member Data Documentation
Model G4InuclParticle::modelId private
Definition at line 164 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 164 of file G4InuclParticle.hh
Referenced by getModel(), operator=(), print(), and setModel().
G4DynamicParticle G4InuclParticle::pDP private
Definition at line 163 of file G4InuclParticle.hh.
View newest version in sPHENIX GitHub at line 163 of file G4InuclParticle.hh
Referenced by G4InuclParticle(), getCharge(), getDefinition(), getDynamicParticle(), getEnergy(), getKineticEnergy(), getMass(), getMomentum(), getMomModule(), operator=(), operator==(), setDefinition(), setKineticEnergy(), setMass(), and setMomentum().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclParticle.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InuclParticle.cc