ECCE @ EIC Software: G4VUserPhysicsList Class Reference
G4VUserPhysicsList Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUserPhysicsList.hh>
Public Member Functions
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
virtual void ConstructParticle ()=0
void Construct ()
virtual void ConstructProcess ()=0
void UseCoupledTransportation (G4bool vl=true)
virtual void SetCuts ()
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Static Public Member Functions
static const G4VUPLManager & GetSubInstanceManager ()
Protected Member Functions
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Protected Attributes
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes
static G4RUN_DLL G4VUPLManager subInstanceManager
Private Types
enum { FixedStringLengthForStore = 32 }
Detailed Description
Definition at line 155 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 155 of file G4VUserPhysicsList.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
FixedStringLengthForStore
Definition at line 388 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 388 of file G4VUserPhysicsList.hh
Constructor & Destructor Documentation
G4VUserPhysicsList::G4VUserPhysicsList ()
Definition at line 103 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 103 of file G4VUserPhysicsList.cc
References G4VUPLSplitter< T >::CreateSubInstance(), defaultCutValue, fCutsTable, fDisplayThreshold, fIsPhysicsTableBuilt, G4MT_theMessenger, G4MT_thePLHelper, g4vuplInstanceID, G4ParticleTable::GetParticleTable(), G4ProductionCutsTable::GetProductionCutsTable(), keV, mm, G4ProductionCutsTable::SetEnergyRange(), subInstanceManager, TeV, theParticleTable, and verboseLevel.
G4VUserPhysicsList::~G4VUserPhysicsList () virtual
Definition at line 159 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 159 of file G4VUserPhysicsList.cc
References G4ParticleTable::DeleteAllParticles(), G4MT_theMessenger, RemoveProcessManager(), and theParticleTable.
G4VUserPhysicsList::G4VUserPhysicsList (const G4VUserPhysicsList & right)
Definition at line 173 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 173 of file G4VUserPhysicsList.cc
References G4VUPLSplitter< T >::CreateSubInstance(), fCutsTable, fDisplayThreshold, fIsPhysicsTableBuilt, G4MT_theMessenger, G4MT_thePLHelper, g4vuplInstanceID, GetInstanceID(), G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), G4PhysicsListHelper::GetPhysicsListHelper(), G4ProductionCutsTable::GetProductionCutsTable(), GetSubInstanceManager(), G4VUPLSplitter< T >::offset, subInstanceManager, theParticleIterator, theParticleTable, and verboseLevel.
Member Function Documentation
void G4VUserPhysicsList::AddProcessManager (G4ParticleDefinition * newParticle, G4ProcessManager * newManager = 0)
Definition at line 230 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 230 of file G4VUserPhysicsList.cc
References G4Exception(), and JustWarning.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::AddTransportation () protected
Definition at line 956 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 956 of file G4VUserPhysicsList.cc
References G4MT_thePLHelper.
Referenced by DMXPhysicsList::AddTransportation(), Par02PhysicsList::AddTransportation(), LBE::AddTransportation(), eRositaPhysicsList::ConstructProcess(), XPhysicsList::ConstructProcess(), GeantinoPhysicsList::ConstructProcess(), G4HumanPhantomPhysicsList::ConstructProcess(), STCyclotronPhysicsList::ConstructProcess(), GammaKnifePhysicsList::ConstructProcess(), BrachyPhysicsList::ConstructProcess(), ExN02PhysicsList::ConstructProcess(), PhysicsListEMstd::ConstructProcess(), ExN01PhysicsList::ConstructProcess(), XrayFluoPhysicsList::ConstructProcess(), HadrontherapyPhysicsList::ConstructProcess(), PhysicsList::ConstructProcess(), UltraPhysicsList::ConstructProcess(), GammaRayTelPhysicsList::ConstructProcess(), doiPETPhysicsList::ConstructProcess(), B03PhysicsList::ConstructProcess(), ML2PhysicsList::ConstructProcess(), PurgMagPhysicsList::ConstructProcess(), TSPhysicsList::ConstructProcess(), XrayTelPhysicsList::ConstructProcess(), IORTPhysicsList::ConstructProcess(), G4AdjointPhysicsList::ConstructProcess(), and G4VModularPhysicsList::ConstructProcess().
void G4VUserPhysicsList::BuildIntegralPhysicsTable (G4VProcess * process, G4ParticleDefinition * particle) protected
Definition at line 769 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 769 of file G4VUserPhysicsList.cc
References G4VProcess::BuildPhysicsTable(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), and verboseLevel.
Referenced by RetrievePhysicsTable().
void G4VUserPhysicsList::BuildPhysicsTable ()
Definition at line 526 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 526 of file G4VUserPhysicsList.cc
References directoryPhysicsTable, fCutsTable, G4ParticleTable::FindParticle(), fIsPhysicsTableBuilt, fIsRestoredCutValues, fRetrievePhysicsTable, fStoredInAscii, G4cout, G4endl, G4Exception(), particle, PreparePhysicsTable(), G4ProductionCutsTable::RetrieveCutsTable(), RunMustBeAborted, theParticleIterator, theParticleTable, and verboseLevel.
Referenced by G4RunManagerKernel::BuildPhysicsTables(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::BuildPhysicsTable (G4ParticleDefinition * particle)
Definition at line 595 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 595 of file G4VUserPhysicsList.cc
References directoryPhysicsTable, FatalException, fIsRestoredCutValues, fRetrievePhysicsTable, fStoredInAscii, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetMasterProcessManager(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsShortLived(), RetrievePhysicsTable(), G4ProcessVector::size(), and verboseLevel.
void G4VUserPhysicsList::CheckParticleList ()
Definition at line 948 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 948 of file G4VUserPhysicsList.cc
References fDisableCheckParticleList, and G4MT_thePLHelper.
Referenced by G4RunManagerKernel::InitializePhysics().
void G4VUserPhysicsList::Construct (void) inline
Definition at line 407 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 407 of file G4VUserPhysicsList.hh
References ConstructProcess(), G4cout, G4endl, InitializeProcessManager(), and verboseLevel.
Referenced by G4RunManagerKernel::InitializePhysics().
virtual void G4VUserPhysicsList::ConstructParticle () pure virtual
Implemented in G4VModularPhysicsList, PhysicsList, G4AdjointPhysicsList, PhysicsList, LBE, DMXPhysicsList, XrayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PurgMagPhysicsList, TSPhysicsList, PhysicsList, PhysicsList, PhysicsList, ML2PhysicsList, PhysicsList, PhysicsList, F04PhysicsList, IORTPhysicsList, PhysicsList, G4ErrorPhysicsList, B03PhysicsList, PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, doiPETPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, Par02PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsListEMstd, ExN01PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, ExN02PhysicsList, BrachyPhysicsList, PhysicsList, XrayFluoPhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, PhysicsListEMstd, GammaRayTelPhysicsList, STCyclotronPhysicsList, PhysicsList, HadrontherapyPhysicsList, PhysicsList, G4HumanPhantomPhysicsList, ExUCNPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, pyG4VUserPhysicsList::CB_G4VUserPhysicsList, XPhysicsList, eRositaPhysicsList, GammaKnifePhysicsList, and EICPhysicsList.
Referenced by export_G4VUserPhysicsList(), and G4RunManagerKernel::SetupPhysics().
virtual void G4VUserPhysicsList::ConstructProcess () pure virtual
Implemented in G4VModularPhysicsList, PhysicsList, G4AdjointPhysicsList, PhysicsList, LBE, DMXPhysicsList, PhysicsList, IORTPhysicsList, XrayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PurgMagPhysicsList, PhysicsList, PhysicsList, TSPhysicsList, ML2PhysicsList, PhysicsList, PhysicsList, F04PhysicsList, G4ErrorPhysicsList, PhysicsList, PhysicsList, Par02PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, B03PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, doiPETPhysicsList, GammaRayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, HadrontherapyPhysicsList, XrayFluoPhysicsList, PhysicsList, PhysicsListEMstd, ExN01PhysicsList, BrachyPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, ExN02PhysicsList, GammaKnifePhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, PhysicsListEMstd, STCyclotronPhysicsList, PhysicsList, PhysicsList, PhysicsList, pyG4VUserPhysicsList::CB_G4VUserPhysicsList, PhysicsList, PhysicsList, G4HumanPhantomPhysicsList, ExUCNPhysicsList, PhysicsList, PhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, GeantinoPhysicsList, PhysicsList, XPhysicsList, and eRositaPhysicsList.
Referenced by Construct(), and export_G4VUserPhysicsList().
void G4VUserPhysicsList::DisableCheckParticleList () inline
Definition at line 474 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 474 of file G4VUserPhysicsList.hh
References fDisableCheckParticleList.
void G4VUserPhysicsList::DumpCutValuesTable (G4int flag = 1)
Definition at line 816 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 816 of file G4VUserPhysicsList.cc
References fDisplayThreshold.
Referenced by G4RunManagerKernel::BuildPhysicsTables(), export_G4VUserPhysicsList(), GammaKnifePhysicsList::SetCuts(), eRositaPhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), STCyclotronPhysicsList::SetCuts(), ExN02PhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), PhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), IORTPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), XrayTelPhysicsList::SetCuts(), LBE::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCuts(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::DumpCutValuesTableIfRequested ()
Definition at line 822 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 822 of file G4VUserPhysicsList.cc
References G4ProductionCutsTable::DumpCouples(), fDisplayThreshold, and G4ProductionCutsTable::GetProductionCutsTable().
Referenced by G4RunManagerKernel::BuildPhysicsTables(), and export_G4VUserPhysicsList().
void G4VUserPhysicsList::DumpList () const
Definition at line 798 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 798 of file G4VUserPhysicsList.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), incremental_prev_tag::idx, particle, and theParticleIterator.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
G4bool G4VUserPhysicsList::GetApplyCuts (const G4String & name) const
Definition at line 941 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 941 of file G4VUserPhysicsList.cc
References G4ParticleTable::FindParticle(), G4ParticleDefinition::GetApplyCutsFlag(), and theParticleTable.
Referenced by export_G4VUserPhysicsList().
G4double G4VUserPhysicsList::GetCutValue (const G4String & pname) const
Definition at line 401 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 401 of file G4VUserPhysicsList.cc
References FatalException, G4cout, G4endl, G4Exception(), G4RegionStore::GetInstance(), G4ProductionCuts::GetProductionCut(), G4Region::GetProductionCuts(), G4RegionStore::GetRegion(), mm, and verboseLevel.
Referenced by SetCuts(), and G4UserPhysicsListMessenger::SetNewValue().
G4double G4VUserPhysicsList::GetDefaultCutValue () const inline
Definition at line 422 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 422 of file G4VUserPhysicsList.hh
References defaultCutValue.
Referenced by export_G4VUserPhysicsList(), G4UserPhysicsListMessenger::GetCurrentValue(), and CexmcSetup::SetupSpecialVolumes().
G4int G4VUserPhysicsList::GetInstanceID () const inline
Definition at line 480 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 480 of file G4VUserPhysicsList.hh
References g4vuplInstanceID.
Referenced by G4VUserPhysicsList(), and operator=().
G4ParticleTable::G4PTblDicIterator * G4VUserPhysicsList::GetParticleIterator () const protected
Definition at line 975 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 975 of file G4VUserPhysicsList.cc
References g4vuplInstanceID, G4VUPLSplitter< T >::offset, and subInstanceManager.
Referenced by XrayFluoPhysicsList::AddDecay(), PhysicsList::AddDecay(), PhysicsList::AddIonGasModels(), PhysicsList::AddMaxStepSize(), Par02PhysicsList::AddParameterisation(), B03PhysicsList::AddScoringProcess(), F04PhysicsList::AddStepMax(), HadrontherapyPhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), PhysicsList::AddStepMax(), ML2PhysicsList::AddStepMax(), ExN02PhysicsList::AddStepMax(), IORTPhysicsList::AddStepMax(), PhysicsList::AddTrackingCut(), DMXPhysicsList::AddTransportation(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), DMXPhysicsList::ConstructOp(), XPhysicsList::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), and TSPhysicsList::ConstructProcess().
const G4String & G4VUserPhysicsList::GetPhysicsTableDirectory () const inline
Definition at line 446 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 446 of file G4VUserPhysicsList.hh
References directoryPhysicsTable.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::GetCurrentValue().
const G4VUPLManager & G4VUserPhysicsList::GetSubInstanceManager () inline static
Definition at line 486 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 486 of file G4VUserPhysicsList.hh
References subInstanceManager.
Referenced by G4PhysicsListWorkspace::G4PhysicsListWorkspace(), G4VUserPhysicsList(), and operator=().
G4int G4VUserPhysicsList::GetVerboseLevel () const inline
Definition at line 428 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 428 of file G4VUserPhysicsList.hh
References verboseLevel.
Referenced by export_G4VUserPhysicsList(), G4UserPhysicsListMessenger::GetCurrentValue(), and ExN01PhysicsList::SetCuts().
void G4VUserPhysicsList::InitializeProcessManager () protected
Definition at line 241 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 241 of file G4VUserPhysicsList.cc
References G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4ParticleTable::GetGenericIon(), G4ParticleDefinition::GetMasterProcessManager(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsGeneralIon(), particle, G4ParticleDefinition::SetMasterProcessManager(), G4ParticleDefinition::SetProcessManager(), theParticleIterator, and verboseLevel.
Referenced by Construct().
void G4VUserPhysicsList::InitializeWorker () virtual
Definition at line 145 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 145 of file G4VUserPhysicsList.cc
References G4MT_theMessenger.
Referenced by G4WorkerRunManager::SetUserInitialization().
G4bool G4VUserPhysicsList::IsPhysicsTableRetrieved () const inline
Definition at line 434 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 434 of file G4VUserPhysicsList.hh
References fRetrievePhysicsTable.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::GetCurrentValue().
G4bool G4VUserPhysicsList::IsStoredInAscii () const inline
Definition at line 440 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 440 of file G4VUserPhysicsList.hh
References fStoredInAscii.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::GetCurrentValue().
G4VUserPhysicsList & G4VUserPhysicsList::operator= (const G4VUserPhysicsList & right)
Definition at line 209 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 209 of file G4VUserPhysicsList.cc
References defaultCutValue, directoryPhysicsTable, fDisableCheckParticleList, fDisplayThreshold, fIsCheckedForRetrievePhysicsTable, fIsPhysicsTableBuilt, fIsRestoredCutValues, fRetrievePhysicsTable, fStoredInAscii, GetInstanceID(), GetSubInstanceManager(), isSetDefaultCutValue, G4VUPLSplitter< T >::offset, and verboseLevel.
void G4VUserPhysicsList::PreparePhysicsTable (G4ParticleDefinition * particle)
Definition at line 703 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 703 of file G4VUserPhysicsList.cc
References FatalException, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetMasterProcessManager(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsShortLived(), G4ProcessVector::size(), and verboseLevel.
Referenced by BuildPhysicsTable(), and G4UserPhysicsListMessenger::SetNewValue().
G4bool G4VUserPhysicsList::RegisterProcess (G4VProcess * process, G4ParticleDefinition * particle) protected
Definition at line 968 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 968 of file G4VUserPhysicsList.cc
References G4MT_thePLHelper.
Referenced by DMXPhysicsList::ConstructGeneral().
void G4VUserPhysicsList::RemoveProcessManager ()
Definition at line 300 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 300 of file G4VUserPhysicsList.cc
References G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4ParticleDefinition::GetInstanceID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetProcessManager(), particle, G4ParticleDefinition::SetProcessManager(), G4PDefManager::slavetotalspace(), theParticleIterator, and verboseLevel.
Referenced by TerminateWorker(), and ~G4VUserPhysicsList().
void G4VUserPhysicsList::ResetCuts ()
obsolete methods
Definition at line 1002 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 1002 of file G4VUserPhysicsList.cc
References G4cout, G4endl, and verboseLevel.
Referenced by XrayTelPhysicsList::SetCutForElectron(), XrayTelPhysicsList::SetCutForGamma(), and PurgMagPhysicsList::SetGammaCut().
void G4VUserPhysicsList::ResetPhysicsTableRetrieved () inline
Definition at line 459 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 459 of file G4VUserPhysicsList.hh
References fIsCheckedForRetrievePhysicsTable, fIsRestoredCutValues, and fRetrievePhysicsTable.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::ResetStoredInAscii () inline
Definition at line 468 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 468 of file G4VUserPhysicsList.hh
References fStoredInAscii.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::RetrievePhysicsTable (G4ParticleDefinition * particle, const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 891 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 891 of file G4VUserPhysicsList.cc
References BuildIntegralPhysicsTable(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), G4ProcessVector::size(), and verboseLevel.
Referenced by BuildPhysicsTable().
void G4VUserPhysicsList::SetApplyCuts (G4bool value, const G4String & name)
Definition at line 923 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 923 of file G4VUserPhysicsList.cc
References G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleDefinition::SetApplyCutsFlag(), theParticleTable, and verboseLevel.
Referenced by G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::SetCuts () virtual
Reimplemented in PhysicsList, G4AdjointPhysicsList, PhysicsList, LBE, PhysicsList, PhysicsList, XrayTelPhysicsList, PurgMagPhysicsList, TSPhysicsList, DMXPhysicsList, G4ErrorPhysicsList, PhysicsList, PhysicsList, Par02PhysicsList, PhysicsList, doiPETPhysicsList, IORTPhysicsList, B03PhysicsList, PhysicsList, PhysicsList, PhysicsList, FTFP_BERT_HP, UltraPhysicsList, XrayFluoPhysicsList, PhysicsList, PhysicsList, BrachyPhysicsList, QGSP_BERT_HP, ExN02PhysicsList, pyG4VUserPhysicsList::CB_G4VUserPhysicsList, PhysicsListEMstd, ExN01PhysicsList, PhysicsList, PhysicsList, PhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, STCyclotronPhysicsList, PhysicsList, GammaRayTelPhysicsList, ExUCNPhysicsList, QPhysicsList, G4HumanPhantomPhysicsList, B3PhysicsList, B3PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, eRositaPhysicsList, XPhysicsList, PhysicsList, PhysicsList, PhysicsList, pyG4VModularPhysicsList::CB_G4VModularPhysicsList, GammaKnifePhysicsList, and EICPhysicsList.
Definition at line 341 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 341 of file G4VUserPhysicsList.cc
References defaultCutValue, DumpCutValuesTable(), G4cout, G4endl, GetCutValue(), isSetDefaultCutValue, mm, SetDefaultCutValue(), and verboseLevel.
Referenced by export_G4VModularPhysicsList(), export_G4VUserPhysicsList(), G4RunManagerKernel::InitializePhysics(), main(), B3PhysicsList::SetCuts(), SetCutsWithDefault(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::SetCutsForRegion (G4double aCut, const G4String & rname)
Definition at line 453 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 453 of file G4VUserPhysicsList.cc
References SetCutValue().
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::SetCutsWithDefault ()
Definition at line 446 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 446 of file G4VUserPhysicsList.cc
References defaultCutValue, SetCuts(), and SetDefaultCutValue().
Referenced by export_G4VUserPhysicsList(), PHG4Reco::Init(), XPhysicsList::SetCuts(), eRositaPhysicsList::SetCuts(), QPhysicsList::SetCuts(), ExUCNPhysicsList::SetCuts(), ExN01PhysicsList::SetCuts(), F05PhysicsList::SetCuts(), F06PhysicsList::SetCuts(), PhysicsListEMstd::SetCuts(), ExN02PhysicsList::SetCuts(), QGSP_BERT_HP::SetCuts(), UltraPhysicsList::SetCuts(), FTFP_BERT_HP::SetCuts(), B03PhysicsList::SetCuts(), Par02PhysicsList::SetCuts(), and G4ErrorPhysicsList::SetCuts().
void G4VUserPhysicsList::SetCutValue (G4double aCut, const G4String & pname)
Definition at line 421 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 421 of file G4VUserPhysicsList.cc
References SetParticleCuts().
Referenced by QGSP_BIC_AllHP::QGSP_BIC_AllHP(), QGSP_BIC_HP::QGSP_BIC_HP(), EICPhysicsList::SetCuts(), GammaKnifePhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), STCyclotronPhysicsList::SetCuts(), QGSP_BERT_HP::SetCuts(), BrachyPhysicsList::SetCuts(), PhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), FTFP_BERT_HP::SetCuts(), IORTPhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), TSPhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), XrayTelPhysicsList::SetCuts(), LBE::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCutsForRegion(), SetDefaultCutValue(), G4UserPhysicsListMessenger::SetNewValue(), and Shielding::Shielding().
void G4VUserPhysicsList::SetCutValue (G4double aCut, const G4String & pname, const G4String & rname)
Definition at line 428 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 428 of file G4VUserPhysicsList.cc
References G4cout, G4endl, G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), and pyG4VUserPhysicsList::SetParticleCuts.
void G4VUserPhysicsList::SetDefaultCutValue (G4double newCutValue)
Definition at line 369 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 369 of file G4VUserPhysicsList.cc
References defaultCutValue, G4cout, G4endl, isSetDefaultCutValue, mm, SetCutValue(), and verboseLevel.
Referenced by export_G4VUserPhysicsList(), main(), PhysicsList::PhysicsList(), SetCuts(), SetCutsWithDefault(), G4UserPhysicsListMessenger::SetNewValue(), SetParticleCuts(), UltraPhysicsList::UltraPhysicsList(), and XPhysicsList::XPhysicsList().
void G4VUserPhysicsList::SetParticleCuts (G4double cut, G4ParticleDefinition * particle, G4Region * region = 0)
Definition at line 465 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 465 of file G4VUserPhysicsList.cc
References G4ParticleDefinition::GetParticleName().
Referenced by GammaKnifePhysicsList::SetCutForElectron(), GammaRayTelPhysicsList::SetCutForElectron(), STCyclotronPhysicsList::SetCutForElectron(), PhysicsList::SetCutForElectron(), XrayFluoPhysicsList::SetCutForElectron(), IORTPhysicsList::SetCutForElectron(), GammaKnifePhysicsList::SetCutForGamma(), GammaRayTelPhysicsList::SetCutForGamma(), STCyclotronPhysicsList::SetCutForGamma(), PhysicsList::SetCutForGamma(), XrayFluoPhysicsList::SetCutForGamma(), IORTPhysicsList::SetCutForGamma(), GammaKnifePhysicsList::SetCutForPositron(), GammaRayTelPhysicsList::SetCutForPositron(), STCyclotronPhysicsList::SetCutForPositron(), PhysicsList::SetCutForPositron(), XrayFluoPhysicsList::SetCutForPositron(), IORTPhysicsList::SetCutForPositron(), XrayFluoPhysicsList::SetCutForProton(), and SetCutValue().
void G4VUserPhysicsList::SetParticleCuts (G4double cut, const G4String & particleName, G4Region * region = 0)
Definition at line 471 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 471 of file G4VUserPhysicsList.cc
References defaultCutValue, FatalException, G4cout, G4endl, G4Exception(), G4RegionStore::GetInstance(), G4Region::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4RegionStore::GetRegion(), isSetDefaultCutValue, mm, SetDefaultCutValue(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), and verboseLevel.
void G4VUserPhysicsList::SetPhysicsTableRetrieved (const G4String & directory = "")
Definition at line 880 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 880 of file G4VUserPhysicsList.cc
References directoryPhysicsTable, fIsCheckedForRetrievePhysicsTable, fIsRestoredCutValues, fRetrievePhysicsTable, and G4String::isNull().
Referenced by G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::SetStoredInAscii () inline
Definition at line 452 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 452 of file G4VUserPhysicsList.hh
References fStoredInAscii.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::SetVerboseLevel (G4int value)
Definition at line 981 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 981 of file G4VUserPhysicsList.cc
References fCutsTable, G4cout, G4endl, G4MT_thePLHelper, G4ProductionCutsTable::SetVerboseLevel(), and verboseLevel.
Referenced by B03PhysicsList::B03PhysicsList(), DMXPhysicsList::DMXPhysicsList(), eRositaPhysicsList::eRositaPhysicsList(), ExN02PhysicsList::ExN02PhysicsList(), export_G4VUserPhysicsList(), G4AdjointPhysicsList::G4AdjointPhysicsList(), Par02PhysicsList::Par02PhysicsList(), PurgMagPhysicsList::PurgMagPhysicsList(), ExN01PhysicsList::SetCuts(), G4UserPhysicsListMessenger::SetNewValue(), XPhysicsList::XPhysicsList(), and XrayTelPhysicsList::XrayTelPhysicsList().
G4bool G4VUserPhysicsList::StorePhysicsTable (const G4String & directory = ".")
Definition at line 831 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 831 of file G4VUserPhysicsList.cc
References dir, directoryPhysicsTable, fCutsTable, fStoredInAscii, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), G4String::isNull(), JustWarning, particle, G4ProcessVector::size(), G4ProductionCutsTable::StoreCutsTable(), theParticleIterator, and verboseLevel.
Referenced by export_G4VUserPhysicsList(), and G4UserPhysicsListMessenger::SetNewValue().
void G4VUserPhysicsList::TerminateWorker () virtual
Reimplemented in G4VModularPhysicsList.
Definition at line 152 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 152 of file G4VUserPhysicsList.cc
References G4MT_theMessenger, and RemoveProcessManager().
Referenced by G4VModularPhysicsList::TerminateWorker(), and G4WorkerRunManager::~G4WorkerRunManager().
void G4VUserPhysicsList::UseCoupledTransportation (G4bool vl = true)
Definition at line 962 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 962 of file G4VUserPhysicsList.cc
References G4MT_thePLHelper.
Referenced by G4RunManagerKernel::InitializePhysics().
Member Data Documentation
G4double G4VUserPhysicsList::defaultCutValue protected
Definition at line 358 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 358 of file G4VUserPhysicsList.hh
Referenced by DMXPhysicsList::DMXPhysicsList(), eRositaPhysicsList::eRositaPhysicsList(), ExN02PhysicsList::ExN02PhysicsList(), F04PhysicsList::F04PhysicsList(), FTF_BIC::FTF_BIC(), FTFP_BERT::FTFP_BERT(), FTFP_BERT_ATL::FTFP_BERT_ATL(), FTFP_BERT_HP::FTFP_BERT_HP(), FTFP_BERT_TRV::FTFP_BERT_TRV(), FTFQGSP_BERT::FTFQGSP_BERT(), G4AdjointPhysicsList::G4AdjointPhysicsList(), G4ErrorPhysicsList::G4ErrorPhysicsList(), G4VUserPhysicsList(), GammaKnifePhysicsList::GammaKnifePhysicsList(), GammaRayTelPhysicsList::GammaRayTelPhysicsList(), GetDefaultCutValue(), HadrontherapyPhysicsList::HadrontherapyPhysicsList(), IORTPhysicsList::IORTPhysicsList(), LBE::LBE(), ML2PhysicsList::ML2PhysicsList(), NuBeam::NuBeam(), G4VModularPhysicsList::operator=(), operator=(), Par02PhysicsList::Par02PhysicsList(), PhysicsListEMstd::PhysicsListEMstd(), PurgMagPhysicsList::PurgMagPhysicsList(), QBBC::QBBC(), QGS_BIC::QGS_BIC(), QGSP_BERT::QGSP_BERT(), QGSP_BERT_HP::QGSP_BERT_HP(), QGSP_BIC::QGSP_BIC(), QGSP_BIC_AllHP::QGSP_BIC_AllHP(), QGSP_BIC_HP::QGSP_BIC_HP(), QGSP_FTFP_BERT::QGSP_FTFP_BERT(), QPhysicsList::QPhysicsList(), GammaKnifePhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), STCyclotronPhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), B03PhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), IORTPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), LBE::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCuts(), SetCutsWithDefault(), SetDefaultCutValue(), SetParticleCuts(), Shielding::Shielding(), STCyclotronPhysicsList::STCyclotronPhysicsList(), XrayFluoPhysicsList::XrayFluoPhysicsList(), and XrayTelPhysicsList::XrayTelPhysicsList().
G4String G4VUserPhysicsList::directoryPhysicsTable protected
Definition at line 373 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 373 of file G4VUserPhysicsList.hh
Referenced by BuildPhysicsTable(), GetPhysicsTableDirectory(), G4VModularPhysicsList::operator=(), operator=(), SetPhysicsTableRetrieved(), and StorePhysicsTable().
G4ProductionCutsTable* G4VUserPhysicsList::fCutsTable protected
Definition at line 363 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 363 of file G4VUserPhysicsList.hh
Referenced by BuildPhysicsTable(), G4VUserPhysicsList(), SetVerboseLevel(), and StorePhysicsTable().
G4bool G4VUserPhysicsList::fDisableCheckParticleList protected
Definition at line 382 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 382 of file G4VUserPhysicsList.hh
Referenced by CheckParticleList(), DisableCheckParticleList(), G4VModularPhysicsList::operator=(), and operator=().
G4bool G4VUserPhysicsList::fIsCheckedForRetrievePhysicsTable protected
Definition at line 369 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 369 of file G4VUserPhysicsList.hh
Referenced by G4VModularPhysicsList::operator=(), operator=(), ResetPhysicsTableRetrieved(), and SetPhysicsTableRetrieved().
G4bool G4VUserPhysicsList::fIsRestoredCutValues protected
Definition at line 370 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 370 of file G4VUserPhysicsList.hh
Referenced by BuildPhysicsTable(), G4VModularPhysicsList::operator=(), operator=(), ResetPhysicsTableRetrieved(), and SetPhysicsTableRetrieved().
G4bool G4VUserPhysicsList::fRetrievePhysicsTable protected
Definition at line 366 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 366 of file G4VUserPhysicsList.hh
Referenced by BuildPhysicsTable(), IsPhysicsTableRetrieved(), G4VModularPhysicsList::operator=(), operator=(), ResetPhysicsTableRetrieved(), and SetPhysicsTableRetrieved().
G4bool G4VUserPhysicsList::fStoredInAscii protected
Definition at line 367 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 367 of file G4VUserPhysicsList.hh
Referenced by BuildPhysicsTable(), IsStoredInAscii(), G4VModularPhysicsList::operator=(), operator=(), ResetStoredInAscii(), SetStoredInAscii(), and StorePhysicsTable().
G4int G4VUserPhysicsList::g4vuplInstanceID protected
Definition at line 392 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 392 of file G4VUserPhysicsList.hh
Referenced by G4VUserPhysicsList(), GetInstanceID(), GetParticleIterator(), and G4VModularPhysicsList::operator=().
G4bool G4VUserPhysicsList::isSetDefaultCutValue protected
Definition at line 359 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 359 of file G4VUserPhysicsList.hh
Referenced by G4VModularPhysicsList::operator=(), operator=(), SetCuts(), SetDefaultCutValue(), and SetParticleCuts().
G4VUPLManager G4VUserPhysicsList::subInstanceManager static protected
Definition at line 393 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 393 of file G4VUserPhysicsList.hh
Referenced by G4VUserPhysicsList(), GetParticleIterator(), GetSubInstanceManager(), and G4VModularPhysicsList::operator=().
G4ParticleTable* G4VUserPhysicsList::theParticleTable protected
Definition at line 346 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 346 of file G4VUserPhysicsList.hh
Referenced by BuildPhysicsTable(), G4VUserPhysicsList(), GetApplyCuts(), SetApplyCuts(), and ~G4VUserPhysicsList().
G4int G4VUserPhysicsList::verboseLevel protected
Definition at line 354 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 354 of file G4VUserPhysicsList.hh
Referenced by BuildIntegralPhysicsTable(), BuildPhysicsTable(), Construct(), XPhysicsList::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), G4VUserPhysicsList(), GetCutValue(), GetVerboseLevel(), InitializeProcessManager(), operator=(), PreparePhysicsTable(), RemoveProcessManager(), ResetCuts(), RetrievePhysicsTable(), SetApplyCuts(), eRositaPhysicsList::SetCuts(), ExN02PhysicsList::SetCuts(), B03PhysicsList::SetCuts(), Par02PhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), PurgMagPhysicsList::SetCuts(), XrayTelPhysicsList::SetCuts(), G4AdjointPhysicsList::SetCuts(), SetCuts(), SetDefaultCutValue(), PurgMagPhysicsList::SetElectronLowLimit(), PurgMagPhysicsList::SetGammaLowLimit(), PurgMagPhysicsList::SetGELowLimit(), PurgMagPhysicsList::SetGEPLowLimit(), SetParticleCuts(), PurgMagPhysicsList::SetPositronLowLimit(), PurgMagPhysicsList::SetProtonLowLimit(), SetVerboseLevel(), and StorePhysicsTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VUserPhysicsList.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VUserPhysicsList.cc