ECCE @ EIC Software: G4LivermoreIonisationCrossSection Class Reference
G4LivermoreIonisationCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreIonisationCrossSection.hh>
Public Member Functions
G4LivermoreIonisationCrossSection (const G4String &nam="LivermorePIXE")
virtual ~G4LivermoreIonisationCrossSection ()
void Initialise ()
G4double CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass=0.0, const G4Material *mat=0)
std::vector< G4double > GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass=0.0, G4double deltaEnergy=0.0, const G4Material *mat=0)
std::vector< G4double > Probabilities (G4int Z, G4double incidentEnergy, G4double mass=0.0, G4double deltaEnergy=0, const G4Material *mat=0)
Public Member Functions inherited from G4VhShellCrossSection
G4VhShellCrossSection (const G4String &xname="")
virtual ~G4VhShellCrossSection ()
G4int SelectRandomShell (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)
virtual void SetTotalCS (G4double)
const G4String & GetName () const
Private Member Functions
G4LivermoreIonisationCrossSection & operator= (const G4LivermoreIonisationCrossSection &right)
G4LivermoreIonisationCrossSection (const G4LivermoreIonisationCrossSection &)
Private Attributes
G4double fLowEnergyLimit
G4double fHighEnergyLimit
G4int verboseLevel
G4VCrossSectionHandler * crossSectionHandler
const G4AtomicTransitionManager * transitionManager
Detailed Description
Definition at line 54 of file G4LivermoreIonisationCrossSection.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LivermoreIonisationCrossSection.hh
Constructor & Destructor Documentation
G4LivermoreIonisationCrossSection::G4LivermoreIonisationCrossSection (const G4String & nam = "LivermorePIXE")
Definition at line 46 of file G4LivermoreIonisationCrossSection.cc.
View newest version in sPHENIX GitHub at line 46 of file G4LivermoreIonisationCrossSection.cc
References eV, fHighEnergyLimit, fLowEnergyLimit, GeV, Initialise(), G4AtomicTransitionManager::Instance(), transitionManager, and verboseLevel.
G4LivermoreIonisationCrossSection::~G4LivermoreIonisationCrossSection () virtual
Definition at line 61 of file G4LivermoreIonisationCrossSection.cc.
View newest version in sPHENIX GitHub at line 61 of file G4LivermoreIonisationCrossSection.cc
References crossSectionHandler.
G4LivermoreIonisationCrossSection::G4LivermoreIonisationCrossSection (const G4LivermoreIonisationCrossSection &) private
Member Function Documentation
G4double G4LivermoreIonisationCrossSection::CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass = 0.0, const G4Material * mat = 0) virtual
Implements G4VhShellCrossSection.
Definition at line 89 of file G4LivermoreIonisationCrossSection.cc.
View newest version in sPHENIX GitHub at line 89 of file G4LivermoreIonisationCrossSection.cc
References Acts::VectorHelpers::cross(), crossSectionHandler, fHighEnergyLimit, G4VCrossSectionHandler::FindValue(), fLowEnergyLimit, min, n, nmax, G4AtomicTransitionManager::NumberOfShells(), and transitionManager.
Referenced by GetCrossSection().
std::vector< G4double > G4LivermoreIonisationCrossSection::GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass = 0.0, G4double deltaEnergy = 0.0, const G4Material * mat = 0) virtual
Implements G4VhShellCrossSection.
Definition at line 107 of file G4LivermoreIonisationCrossSection.cc.
View newest version in sPHENIX GitHub at line 107 of file G4LivermoreIonisationCrossSection.cc
References CrossSection(), min, nmax, G4AtomicTransitionManager::NumberOfShells(), and transitionManager.
Referenced by Probabilities().
void G4LivermoreIonisationCrossSection::Initialise ()
Definition at line 68 of file G4LivermoreIonisationCrossSection.cc.
View newest version in sPHENIX GitHub at line 68 of file G4LivermoreIonisationCrossSection.cc
References G4VCrossSectionHandler::Clear(), crossSectionHandler, fHighEnergyLimit, fLowEnergyLimit, and G4VCrossSectionHandler::LoadShellData().
Referenced by G4LivermoreIonisationCrossSection().
G4LivermoreIonisationCrossSection& G4LivermoreIonisationCrossSection::operator= (const G4LivermoreIonisationCrossSection & right) private
std::vector< G4double > G4LivermoreIonisationCrossSection::Probabilities (G4int Z, G4double incidentEnergy, G4double mass = 0.0, G4double deltaEnergy = 0, const G4Material * mat = 0) virtual
Implements G4VhShellCrossSection.
Definition at line 123 of file G4LivermoreIonisationCrossSection.cc.
View newest version in sPHENIX GitHub at line 123 of file G4LivermoreIonisationCrossSection.cc
References GetCrossSection(), n, and sum.
Member Data Documentation
G4VCrossSectionHandler* G4LivermoreIonisationCrossSection::crossSectionHandler private
Definition at line 96 of file G4LivermoreIonisationCrossSection.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LivermoreIonisationCrossSection.hh
Referenced by CrossSection(), Initialise(), and ~G4LivermoreIonisationCrossSection().
G4double G4LivermoreIonisationCrossSection::fHighEnergyLimit private
Definition at line 90 of file G4LivermoreIonisationCrossSection.hh.
View newest version in sPHENIX GitHub at line 90 of file G4LivermoreIonisationCrossSection.hh
Referenced by CrossSection(), G4LivermoreIonisationCrossSection(), and Initialise().
G4double G4LivermoreIonisationCrossSection::fLowEnergyLimit private
Definition at line 89 of file G4LivermoreIonisationCrossSection.hh.
View newest version in sPHENIX GitHub at line 89 of file G4LivermoreIonisationCrossSection.hh
Referenced by CrossSection(), G4LivermoreIonisationCrossSection(), and Initialise().
const G4AtomicTransitionManager* G4LivermoreIonisationCrossSection::transitionManager private
Definition at line 98 of file G4LivermoreIonisationCrossSection.hh.
View newest version in sPHENIX GitHub at line 98 of file G4LivermoreIonisationCrossSection.hh
Referenced by CrossSection(), G4LivermoreIonisationCrossSection(), and GetCrossSection().
G4int G4LivermoreIonisationCrossSection::verboseLevel private
Definition at line 94 of file G4LivermoreIonisationCrossSection.hh.
View newest version in sPHENIX GitHub at line 94 of file G4LivermoreIonisationCrossSection.hh
Referenced by G4LivermoreIonisationCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreIonisationCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4LivermoreIonisationCrossSection.cc