ECCE @ EIC Software: ExGflash1DetectorConstruction Class Reference
ExGflash1DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflash1DetectorConstruction.hh>
Public Member Functions
ExGflash1DetectorConstruction ()
~ExGflash1DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
const G4VPhysicalVolume * GetCristal (int aNumCrystal)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4LogicalVolume * fCrystalLog
G4VPhysicalVolume * fCrystalPhys [100]
G4Region * fRegion
Static Private Attributes
static G4ThreadLocal
GFlashShowerModel * fFastShowerModel = 0
static G4ThreadLocal
GFlashHomoShowerParameterisation * fParameterisation = 0
static G4ThreadLocal
GFlashParticleBounds * fParticleBounds = 0
static G4ThreadLocal
GFlashHitMaker * fHitMaker = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 45 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 45 of file ExGflash1DetectorConstruction.hh
Constructor & Destructor Documentation
ExGflash1DetectorConstruction::ExGflash1DetectorConstruction ()
Definition at line 71 of file ExGflash1DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 71 of file ExGflash1DetectorConstruction.cc
ExGflash1DetectorConstruction::~ExGflash1DetectorConstruction ()
Definition at line 79 of file ExGflash1DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 79 of file ExGflash1DetectorConstruction.cc
References fFastShowerModel, fHitMaker, fParameterisation, and fParticleBounds.
Member Function Documentation
G4VPhysicalVolume * ExGflash1DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 89 of file ExGflash1DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 89 of file ExGflash1DetectorConstruction.cc
References G4Region::AddRootLogicalVolume(), cm, fCrystalLog, fCrystalPhys, G4NistManager::FindOrBuildMaterial(), fRegion, G4cout, G4endl, G4VisAttributes::GetInvisible(), G4NistManager::Instance(), n, G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and BTOF::zpos.
void ExGflash1DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 229 of file ExGflash1DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 229 of file ExGflash1DetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCrystalLog, fFastShowerModel, fHitMaker, G4NistManager::FindOrBuildMaterial(), fParameterisation, fParticleBounds, fRegion, G4cout, G4endl, G4SDManager::GetSDMpointer(), G4NistManager::Instance(), GFlashShowerModel::SetHitMaker(), GFlashShowerModel::SetParameterisation(), GFlashShowerModel::SetParticleBounds(), and G4LogicalVolume::SetSensitiveDetector().
const G4VPhysicalVolume* ExGflash1DetectorConstruction::GetCristal (int aNumCrystal) inline
Definition at line 55 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file ExGflash1DetectorConstruction.hh
Referenced by ExGflash1SensitiveDetector::ProcessHits().
Member Data Documentation
G4LogicalVolume* ExGflash1DetectorConstruction::fCrystalLog private
Definition at line 56 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 56 of file ExGflash1DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4VPhysicalVolume* ExGflash1DetectorConstruction::fCrystalPhys[100] private
Definition at line 61 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 61 of file ExGflash1DetectorConstruction.hh
Referenced by Construct().
G4ThreadLocal GFlashShowerModel * ExGflash1DetectorConstruction::fFastShowerModel = 0 static private
Definition at line 64 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file ExGflash1DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash1DetectorConstruction().
G4ThreadLocal GFlashHitMaker * ExGflash1DetectorConstruction::fHitMaker = 0 static private
Definition at line 67 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file ExGflash1DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash1DetectorConstruction().
G4ThreadLocal GFlashHomoShowerParameterisation * ExGflash1DetectorConstruction::fParameterisation = 0 static private
Definition at line 65 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file ExGflash1DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash1DetectorConstruction().
G4ThreadLocal GFlashParticleBounds * ExGflash1DetectorConstruction::fParticleBounds = 0 static private
Definition at line 66 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file ExGflash1DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash1DetectorConstruction().
G4Region* ExGflash1DetectorConstruction::fRegion private
Definition at line 62 of file ExGflash1DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 62 of file ExGflash1DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflash1DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/src/ExGflash1DetectorConstruction.cc