ECCE @ EIC Software: G4MuonMinusAtomicCapture Class Reference
G4MuonMinusAtomicCapture Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuonMinusAtomicCapture.hh>
Public Member Functions
G4MuonMinusAtomicCapture (const G4String &name="muMinusAtomicCaptureAtRest")
~G4MuonMinusAtomicCapture ()
G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
void ProcessDescription (std::ostream &outFile) const
void SetElementSelector (G4ElementSelector *ptr)
void SetEmCascade (G4HadronicInteraction *ptr)
Public Member Functions inherited from G4VRestProcess
G4VRestProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestProcess (G4VRestProcess &)
virtual ~G4VRestProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double GetMeanLifeTime (const G4Track &, G4ForceCondition *)
Private Member Functions
G4MuonMinusAtomicCapture & operator= (const G4MuonMinusAtomicCapture &right)
G4MuonMinusAtomicCapture (const G4MuonMinusAtomicCapture &)
Private Attributes
G4ElementSelector * fElementSelector
G4HadronicInteraction * fEmCascade
G4ParticleChange * theTotalResult
G4HadFinalState * result
G4HadProjectile thePro
G4Nucleus targetNucleus
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 60 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 60 of file G4MuonMinusAtomicCapture.hh
Constructor & Destructor Documentation
G4MuonMinusAtomicCapture::G4MuonMinusAtomicCapture (const G4String & name = "muMinusAtomicCaptureAtRest") explicit
Definition at line 63 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 63 of file G4MuonMinusAtomicCapture.cc
References fMuAtomicCapture, G4HadronicProcessStore::Instance(), G4HadronicProcessStore::RegisterExtraProcess(), and G4VProcess::SetProcessSubType().
G4MuonMinusAtomicCapture::~G4MuonMinusAtomicCapture ()
Definition at line 76 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 76 of file G4MuonMinusAtomicCapture.cc
References G4HadronicProcessStore::DeRegisterExtraProcess(), G4HadronicProcessStore::Instance(), and theTotalResult.
G4MuonMinusAtomicCapture::G4MuonMinusAtomicCapture (const G4MuonMinusAtomicCapture &) private
Member Function Documentation
G4VParticleChange * G4MuonMinusAtomicCapture::AtRestDoIt (const G4Track & track, const G4Step &) virtual
Reimplemented from G4VRestProcess.
Definition at line 114 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 114 of file G4MuonMinusAtomicCapture.cc
References G4HadFinalState::AddSecondary(), G4ParticleChange::AddSecondary(), G4HadronicInteraction::ApplyYourself(), G4HadFinalState::Clear(), edep, fElementSelector, fEmCascade, fStopAndKill, G4cout, G4endl, G4RandomDirection(), G4Nucleus::GetA_asInt(), G4DynamicParticle::GetDefinition(), G4Track::GetGlobalTime(), G4IonTable::GetIonTable(), G4HadFinalState::GetLocalEnergyDeposit(), G4IonTable::GetMuonicAtom(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4ParticleDefinition::GetParticleName(), G4DynamicParticle::GetPDGcode(), G4Track::GetPosition(), G4HadFinalState::GetSecondary(), G4HadSecondary::GetTime(), G4Track::GetTouchableHandle(), G4VProcess::GetVerboseLevel(), G4HadSecondary::GetWeight(), G4Track::GetWeight(), G4Nucleus::GetZ_asInt(), G4HadProjectile::Initialise(), G4ParticleChange::Initialize(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), result, G4ElementSelector::SelectZandA(), G4HadProjectile::SetBoundEnergy(), G4HadProjectile::SetGlobalTime(), G4VParticleChange::SetNumberOfSecondaries(), G4HadSecondary::SetTime(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), t, targetNucleus, thePro, theTotalResult, Acts::VectorHelpers::time(), and w.
G4double G4MuonMinusAtomicCapture::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) virtual
Reimplemented from G4VRestProcess.
Definition at line 105 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 105 of file G4MuonMinusAtomicCapture.cc
References NotForced.
void G4MuonMinusAtomicCapture::BuildPhysicsTable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VProcess.
Definition at line 98 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 98 of file G4MuonMinusAtomicCapture.cc
References G4HadronicProcessStore::Instance(), and G4HadronicProcessStore::PrintInfo().
G4double G4MuonMinusAtomicCapture::GetMeanLifeTime (const G4Track & , G4ForceCondition *) inline protected virtual
Implements G4VRestProcess.
Definition at line 91 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 91 of file G4MuonMinusAtomicCapture.hh
G4bool G4MuonMinusAtomicCapture::IsApplicable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VProcess.
Definition at line 84 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 84 of file G4MuonMinusAtomicCapture.cc
References G4MuonMinus::MuonMinus().
G4MuonMinusAtomicCapture& G4MuonMinusAtomicCapture::operator= (const G4MuonMinusAtomicCapture & right) private
void G4MuonMinusAtomicCapture::PreparePhysicsTable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VProcess.
Definition at line 91 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 91 of file G4MuonMinusAtomicCapture.cc
References G4HadronicProcessStore::Instance(), and G4HadronicProcessStore::RegisterParticleForExtraProcess().
void G4MuonMinusAtomicCapture::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4VProcess.
Definition at line 212 of file G4MuonMinusAtomicCapture.cc.
View newest version in sPHENIX GitHub at line 212 of file G4MuonMinusAtomicCapture.cc
void G4MuonMinusAtomicCapture::SetElementSelector (G4ElementSelector * ptr) inline
void G4MuonMinusAtomicCapture::SetEmCascade (G4HadronicInteraction * ptr) inline
Member Data Documentation
G4ElementSelector* G4MuonMinusAtomicCapture::fElementSelector private
Definition at line 100 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 100 of file G4MuonMinusAtomicCapture.hh
Referenced by AtRestDoIt().
G4HadronicInteraction* G4MuonMinusAtomicCapture::fEmCascade private
Definition at line 102 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 102 of file G4MuonMinusAtomicCapture.hh
Referenced by AtRestDoIt().
G4HadFinalState* G4MuonMinusAtomicCapture::result private
Definition at line 106 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MuonMinusAtomicCapture.hh
Referenced by AtRestDoIt().
G4Nucleus G4MuonMinusAtomicCapture::targetNucleus private
Definition at line 110 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 110 of file G4MuonMinusAtomicCapture.hh
Referenced by AtRestDoIt().
G4HadProjectile G4MuonMinusAtomicCapture::thePro private
Definition at line 108 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 108 of file G4MuonMinusAtomicCapture.hh
Referenced by AtRestDoIt().
G4ParticleChange* G4MuonMinusAtomicCapture::theTotalResult private
Definition at line 104 of file G4MuonMinusAtomicCapture.hh.
View newest version in sPHENIX GitHub at line 104 of file G4MuonMinusAtomicCapture.hh
Referenced by AtRestDoIt(), and ~G4MuonMinusAtomicCapture().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuonMinusAtomicCapture.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4MuonMinusAtomicCapture.cc