ECCE @ EIC Software: G4PhononTrackMap Class Reference
G4PhononTrackMap Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4PhononTrackMap.hh>
Public Types
typedef std::map< const
G4Track *, G4ThreeVector > TrkIDKmap
Public Member Functions
void SetK (const G4Track *track, const G4ThreeVector &K)
void SetK (const G4Track &track, const G4ThreeVector &K)
const G4ThreeVector & GetK (const G4Track *track) const
const G4ThreeVector & GetK (const G4Track &track) const
G4bool Find (const G4Track *track) const
G4bool Find (const G4Track &track) const
void RemoveTrack (const G4Track *track)
void Clear ()
Static Public Member Functions
static G4PhononTrackMap * GetPhononTrackMap ()
static G4PhononTrackMap * GetInstance ()
Static Public Attributes
static G4ThreadLocal
G4PhononTrackMap * theTrackMap = 0
Private Member Functions
G4PhononTrackMap ()
~G4PhononTrackMap ()
Private Attributes
TrkIDKmap theMap
Detailed Description
Definition at line 40 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 40 of file G4PhononTrackMap.hh
Member Typedef Documentation
typedef std::map<const G4Track*, G4ThreeVector> G4PhononTrackMap::TrkIDKmap
Definition at line 42 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 42 of file G4PhononTrackMap.hh
Constructor & Destructor Documentation
G4PhononTrackMap::G4PhononTrackMap () inline private
Definition at line 70 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PhononTrackMap.hh
References Clear().
Referenced by GetPhononTrackMap().
G4PhononTrackMap::~G4PhononTrackMap () inline private
Definition at line 71 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PhononTrackMap.hh
Member Function Documentation
void G4PhononTrackMap::Clear ()
Definition at line 51 of file G4PhononTrackMap.cc.
View newest version in sPHENIX GitHub at line 51 of file G4PhononTrackMap.cc
References theMap.
Referenced by G4PhononTrackMap().
G4bool G4PhononTrackMap::Find (const G4Track * track) const
Definition at line 59 of file G4PhononTrackMap.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PhononTrackMap.cc
References theMap.
Referenced by G4VPhononProcess::StartTracking().
G4bool G4PhononTrackMap::Find (const G4Track & track) const inline
Definition at line 59 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PhononTrackMap.hh
References Find().
Referenced by Find().
static G4PhononTrackMap* G4PhononTrackMap::GetInstance (void) inline static
Definition at line 47 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PhononTrackMap.hh
References GetPhononTrackMap().
const G4ThreeVector & G4PhononTrackMap::GetK (const G4Track * track) const
Definition at line 81 of file G4PhononTrackMap.cc.
View newest version in sPHENIX GitHub at line 81 of file G4PhononTrackMap.cc
References theMap.
Referenced by G4VPhononProcess::CreateSecondary(), G4PhononDownconversion::MakeLTSecondaries(), and G4PhononDownconversion::MakeTTSecondaries().
const G4ThreeVector& G4PhononTrackMap::GetK (const G4Track & track) const inline
Definition at line 55 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 55 of file G4PhononTrackMap.hh
References GetK().
Referenced by GetK().
G4PhononTrackMap * G4PhononTrackMap::GetPhononTrackMap () static
Definition at line 46 of file G4PhononTrackMap.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PhononTrackMap.cc
References G4PhononTrackMap(), and theTrackMap.
Referenced by XPhononStackingAction::ClassifyNewTrack(), and GetInstance().
void G4PhononTrackMap::RemoveTrack (const G4Track * track)
Definition at line 66 of file G4PhononTrackMap.cc.
View newest version in sPHENIX GitHub at line 66 of file G4PhononTrackMap.cc
References theMap.
Referenced by G4VPhononProcess::EndTracking().
void G4PhononTrackMap::SetK (const G4Track * track, const G4ThreeVector & K)
Definition at line 74 of file G4PhononTrackMap.cc.
View newest version in sPHENIX GitHub at line 74 of file G4PhononTrackMap.cc
References theMap, and track.
Referenced by XPhononStackingAction::ClassifyNewTrack(), G4VPhononProcess::CreateSecondary(), and G4VPhononProcess::StartTracking().
void G4PhononTrackMap::SetK (const G4Track & track, const G4ThreeVector & K) inline
Definition at line 51 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PhononTrackMap.hh
References SetK().
Referenced by SetK().
Member Data Documentation
TrkIDKmap G4PhononTrackMap::theMap private
Definition at line 67 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PhononTrackMap.hh
Referenced by Clear(), Find(), GetK(), RemoveTrack(), and SetK().
G4ThreadLocal G4PhononTrackMap * G4PhononTrackMap::theTrackMap = 0 static
Definition at line 43 of file G4PhononTrackMap.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PhononTrackMap.hh
Referenced by GetPhononTrackMap().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4PhononTrackMap.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/src/G4PhononTrackMap.cc