ECCE @ EIC Software: G4ProtonBuilder Class Reference
G4ProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4ProtonBuilder.hh>
Public Member Functions
G4ProtonBuilder ()
virtual ~G4ProtonBuilder ()
virtual void Build () finaloverride
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4ProtonInelasticProcess * theProtonInelastic
std::vector< G4VProtonBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 51 of file G4ProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ProtonBuilder.hh
Constructor & Destructor Documentation
G4ProtonBuilder::G4ProtonBuilder ()
Definition at line 59 of file G4ProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ProtonBuilder.cc
References theProtonInelastic.
virtual G4ProtonBuilder::~G4ProtonBuilder () inline virtual
Definition at line 55 of file G4ProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ProtonBuilder.hh
Member Function Documentation
void G4ProtonBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 46 of file G4ProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ProtonBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4ParticleDefinition::GetProcessManager(), G4Proton::Proton(), theModelCollections, theProtonInelastic, and wasActivated.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), and G4HadronPhysicsQGSP_BIC_HP::ConstructProcess().
void G4ProtonBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 64 of file G4ProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ProtonBuilder.cc
References G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
Member Data Documentation
std::vector<G4VProtonBuilder *> G4ProtonBuilder::theModelCollections private
Definition at line 63 of file G4ProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ProtonBuilder.hh
Referenced by Build(), and RegisterMe().
G4ProtonInelasticProcess* G4ProtonBuilder::theProtonInelastic private
Definition at line 61 of file G4ProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ProtonBuilder.hh
Referenced by Build(), and G4ProtonBuilder().
G4bool G4ProtonBuilder::wasActivated private
Definition at line 65 of file G4ProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ProtonBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4ProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4ProtonBuilder.cc