ECCE @ EIC Software: G4BuffercoutDestination Class Reference
G4BuffercoutDestination Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4BuffercoutDestination.hh>
Public Member Functions
G4BuffercoutDestination (size_t maxSize=0)
virtual ~G4BuffercoutDestination ()
virtual G4int ReceiveG4cout (const G4String &msg) override
virtual G4int ReceiveG4cerr (const G4String &msg) override
virtual G4int FlushG4cout ()
virtual G4int FlushG4cerr ()
virtual void Finalize ()
void SetMaxSize (size_t max)
size_t GetMaxSize () const
size_t GetCurrentSizeOut () const
size_t GetCurrentSizeErr () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Protected Member Functions
void ResetCout ()
void ResetCerr ()
Protected Attributes
std::ostringstream m_buffer_out
std::ostringstream m_buffer_err
size_t m_currentSize_out
size_t m_currentSize_err
size_t m_maxSize
Protected Attributes inherited from G4coutDestination
std::vector< Transformer > transformersCout
std::vector< Transformer > transformersCerr
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Protected Attributes inherited from G4coutDestination
static G4MTGLOB_DLL
G4coutDestination * masterG4coutDestination = nullptr
Detailed Description
Definition at line 49 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 49 of file G4BuffercoutDestination.hh
Constructor & Destructor Documentation
G4BuffercoutDestination::G4BuffercoutDestination (size_t maxSize = 0) explicit
Definition at line 38 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 38 of file G4BuffercoutDestination.cc
G4BuffercoutDestination::~G4BuffercoutDestination () virtual
Definition at line 42 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 42 of file G4BuffercoutDestination.cc
References Finalize().
Member Function Documentation
void G4BuffercoutDestination::Finalize () virtual
Definition at line 46 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 46 of file G4BuffercoutDestination.cc
References FlushG4cerr(), and FlushG4cout().
Referenced by ~G4BuffercoutDestination().
G4int G4BuffercoutDestination::FlushG4cerr () virtual
Definition at line 83 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 83 of file G4BuffercoutDestination.cc
References m_buffer_err, and ResetCerr().
Referenced by G4MTcoutDestination::DumpBuffer(), Finalize(), and ReceiveG4cerr().
G4int G4BuffercoutDestination::FlushG4cout () virtual
Definition at line 71 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 71 of file G4BuffercoutDestination.cc
References m_buffer_out, and ResetCout().
Referenced by G4MTcoutDestination::DumpBuffer(), Finalize(), and ReceiveG4cout().
size_t G4BuffercoutDestination::GetCurrentSizeErr () const inline
Definition at line 71 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BuffercoutDestination.hh
References m_currentSize_err.
size_t G4BuffercoutDestination::GetCurrentSizeOut () const inline
Definition at line 70 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BuffercoutDestination.hh
References m_currentSize_out.
size_t G4BuffercoutDestination::GetMaxSize () const inline
Definition at line 69 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BuffercoutDestination.hh
References m_maxSize.
G4int G4BuffercoutDestination::ReceiveG4cerr (const G4String & msg) override virtual
Reimplemented from G4coutDestination.
Definition at line 61 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 61 of file G4BuffercoutDestination.cc
References FlushG4cerr(), m_buffer_err, m_currentSize_err, and m_maxSize.
G4int G4BuffercoutDestination::ReceiveG4cout (const G4String & msg) override virtual
Reimplemented from G4coutDestination.
Definition at line 51 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 51 of file G4BuffercoutDestination.cc
References FlushG4cout(), m_buffer_out, m_currentSize_out, and m_maxSize.
void G4BuffercoutDestination::ResetCerr () protected
Definition at line 89 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 89 of file G4BuffercoutDestination.cc
References m_buffer_err, and m_currentSize_err.
Referenced by FlushG4cerr().
void G4BuffercoutDestination::ResetCout () protected
Definition at line 77 of file G4BuffercoutDestination.cc.
View newest version in sPHENIX GitHub at line 77 of file G4BuffercoutDestination.cc
References m_buffer_out, and m_currentSize_out.
Referenced by FlushG4cout().
void G4BuffercoutDestination::SetMaxSize (size_t max) inline
Definition at line 68 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BuffercoutDestination.hh
References m_maxSize, and max.
Member Data Documentation
std::ostringstream G4BuffercoutDestination::m_buffer_err protected
Definition at line 79 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 79 of file G4BuffercoutDestination.hh
Referenced by FlushG4cerr(), ReceiveG4cerr(), and ResetCerr().
std::ostringstream G4BuffercoutDestination::m_buffer_out protected
Definition at line 78 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BuffercoutDestination.hh
Referenced by FlushG4cout(), ReceiveG4cout(), and ResetCout().
size_t G4BuffercoutDestination::m_currentSize_err protected
Definition at line 81 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 81 of file G4BuffercoutDestination.hh
Referenced by GetCurrentSizeErr(), ReceiveG4cerr(), and ResetCerr().
size_t G4BuffercoutDestination::m_currentSize_out protected
Definition at line 80 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 80 of file G4BuffercoutDestination.hh
Referenced by GetCurrentSizeOut(), ReceiveG4cout(), and ResetCout().
size_t G4BuffercoutDestination::m_maxSize protected
Definition at line 82 of file G4BuffercoutDestination.hh.
View newest version in sPHENIX GitHub at line 82 of file G4BuffercoutDestination.hh
Referenced by GetMaxSize(), ReceiveG4cerr(), ReceiveG4cout(), and SetMaxSize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4BuffercoutDestination.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4BuffercoutDestination.cc