ECCE @ EIC Software: G4LPhysicsFreeVector Class Reference
G4LPhysicsFreeVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4LPhysicsFreeVector.hh>
Public Member Functions
G4LPhysicsFreeVector ()
G4LPhysicsFreeVector (size_t length, G4double emin=0.0, G4double emax=0.0)
virtual ~G4LPhysicsFreeVector ()
void PutValues (size_t index, G4double e, G4double dataValue)
Public Member Functions inherited from G4PhysicsFreeVector
G4PhysicsFreeVector ()
G4PhysicsFreeVector (size_t length)
G4PhysicsFreeVector (const G4DataVector &eVector, const G4DataVector &dataVector)
virtual ~G4PhysicsFreeVector ()
void PutValue (size_t index, G4double energy, G4double dataValue)
Public Member Functions inherited from G4PhysicsVector
G4PhysicsVector (G4bool spline=false)
G4PhysicsVector (const G4PhysicsVector &)
G4PhysicsVector & operator= (const G4PhysicsVector &)
virtual ~G4PhysicsVector ()
G4double Value (G4double theEnergy, size_t &lastidx) const
G4double LogVectorValue (const G4double theEnergy, const G4double theLogEnergy) const
G4double Value (G4double theEnergy) const
G4double GetValue (G4double theEnergy, G4bool &isOutRange) const
G4bool operator== (const G4PhysicsVector &right) const
G4bool operator!= (const G4PhysicsVector &right) const
G4double operator[] (const size_t index) const
G4double operator() (const size_t index) const
void PutValue (size_t index, G4double theValue)
virtual void ScaleVector (G4double factorE, G4double factorV)
G4double Energy (size_t index) const
G4double GetMaxEnergy () const
G4double GetLowEdgeEnergy (size_t binNumber) const
size_t GetVectorLength () const
size_t FindBin (G4double energy, size_t idx) const
size_t ComputeLogVectorBin (const G4double logenergy) const
void FillSecondDerivatives ()
void ComputeSecDerivatives ()
void ComputeSecondDerivatives (G4double firstPointDerivative, G4double endPointDerivative)
G4double FindLinearEnergy (G4double rand) const
G4bool IsFilledVectorExist () const
G4PhysicsVectorType GetType () const
void SetSpline (G4bool)
G4bool Store (std::ofstream &fOut, G4bool ascii=false) const
virtual G4bool Retrieve (std::ifstream &fIn, G4bool ascii=false)
void DumpValues (G4double unitE=1.0, G4double unitV=1.0) const
void SetVerboseLevel (G4int value)
G4double Interpolation (size_t idx, G4double energy) const
Additional Inherited Members
Protected Member Functions inherited from G4PhysicsVector
void DeleteData ()
void CopyData (const G4PhysicsVector &vec)
void PrintPutValueError (size_t index)
Protected Attributes inherited from G4PhysicsVector
G4PhysicsVectorType type
G4double edgeMin
G4double edgeMax
size_t numberOfNodes
G4PVDataVector dataVector
G4PVDataVector binVector
G4PVDataVector secDerivative
G4double invdBin
G4double baseBin
G4int verboseLevel
Detailed Description
Definition at line 53 of file G4LPhysicsFreeVector.hh.
View newest version in sPHENIX GitHub at line 53 of file G4LPhysicsFreeVector.hh
Constructor & Destructor Documentation
G4LPhysicsFreeVector::G4LPhysicsFreeVector ()
Definition at line 46 of file G4LPhysicsFreeVector.cc.
View newest version in sPHENIX GitHub at line 46 of file G4LPhysicsFreeVector.cc
G4LPhysicsFreeVector::G4LPhysicsFreeVector (size_t length, G4double emin = 0.0, G4double emax = 0.0)
Definition at line 52 of file G4LPhysicsFreeVector.cc.
View newest version in sPHENIX GitHub at line 52 of file G4LPhysicsFreeVector.cc
G4LPhysicsFreeVector::~G4LPhysicsFreeVector () virtual
Definition at line 58 of file G4LPhysicsFreeVector.cc.
View newest version in sPHENIX GitHub at line 58 of file G4LPhysicsFreeVector.cc
Member Function Documentation
void G4LPhysicsFreeVector::PutValues (size_t index, G4double e, G4double dataValue) inline
Definition at line 72 of file G4LPhysicsFreeVector.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LPhysicsFreeVector.hh
References G4PhysicsFreeVector::PutValue().
Referenced by G4WaterStopping::AddData(), G4ASTARStopping::AddData(), G4PSTARStopping::AddData(), G4ICRU90StoppingData::AddData(), G4UPiNuclearCrossSection::AddDataSet(), G4LossTableBuilder::BuildInverseRangeTable(), G4ParticleHPData::DoPhysicsVector(), G4EmCorrections::Initialise(), G4ParticleHPJENDLHEData::readAFile(), G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), and G4LivermorePhotoElectricModel::ReadData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4LPhysicsFreeVector.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4LPhysicsFreeVector.cc