ECCE @ EIC Software: G4hIonEffChargeSquare Class Reference
G4hIonEffChargeSquare Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hIonEffChargeSquare.hh>
Public Member Functions
G4hIonEffChargeSquare (const G4String &name)
~G4hIonEffChargeSquare ()
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const
G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const
G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4double IonEffChargeSquare (const G4Material *material, G4double kineticEnergy, G4double particleMass, G4double ionCharge) const
Private Attributes
const G4double theHeMassAMU
Detailed Description
Definition at line 61 of file G4hIonEffChargeSquare.hh.
View newest version in sPHENIX GitHub at line 61 of file G4hIonEffChargeSquare.hh
Constructor & Destructor Documentation
G4hIonEffChargeSquare::G4hIonEffChargeSquare (const G4String & name)
Definition at line 67 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 67 of file G4hIonEffChargeSquare.cc
G4hIonEffChargeSquare::~G4hIonEffChargeSquare ()
Definition at line 74 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 74 of file G4hIonEffChargeSquare.cc
Member Function Documentation
G4double G4hIonEffChargeSquare::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 108 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 108 of file G4hIonEffChargeSquare.cc
References TeV.
G4double G4hIonEffChargeSquare::HighEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 126 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 126 of file G4hIonEffChargeSquare.cc
References TeV.
G4double G4hIonEffChargeSquare::IonEffChargeSquare (const G4Material * material, G4double kineticEnergy, G4double particleMass, G4double ionCharge) const private
Definition at line 158 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 158 of file G4hIonEffChargeSquare.cc
References c, e, G4Exp(), G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Element::GetZ(), G4Material::GetZ(), keV, G4InuclParticleNames::lambda, max, MeV, norm, source.hepunit::proton_mass_c2, theHeMassAMU, v1, weight, x, y, y3, z, and z2.
Referenced by TheValue().
G4bool G4hIonEffChargeSquare::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 142 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 142 of file G4hIonEffChargeSquare.cc
References true.
G4bool G4hIonEffChargeSquare::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 150 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 150 of file G4hIonEffChargeSquare.cc
References true.
G4double G4hIonEffChargeSquare::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 117 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 117 of file G4hIonEffChargeSquare.cc
G4double G4hIonEffChargeSquare::LowEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 134 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 134 of file G4hIonEffChargeSquare.cc
G4double G4hIonEffChargeSquare::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 79 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 79 of file G4hIonEffChargeSquare.cc
References charge, energy, eplus, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetPDGCharge(), and IonEffChargeSquare().
G4double G4hIonEffChargeSquare::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 93 of file G4hIonEffChargeSquare.cc.
View newest version in sPHENIX GitHub at line 93 of file G4hIonEffChargeSquare.cc
References charge, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), and IonEffChargeSquare().
Member Data Documentation
const G4double G4hIonEffChargeSquare::theHeMassAMU private
Definition at line 103 of file G4hIonEffChargeSquare.hh.
View newest version in sPHENIX GitHub at line 103 of file G4hIonEffChargeSquare.hh
Referenced by IonEffChargeSquare().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hIonEffChargeSquare.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4hIonEffChargeSquare.cc