ECCE @ EIC Software: LXeTrajectory Class Reference
LXeTrajectory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeTrajectory.hh>
Public Member Functions
LXeTrajectory ()
LXeTrajectory (const G4Track *aTrack)
LXeTrajectory (LXeTrajectory &)
virtual ~LXeTrajectory ()
virtual void DrawTrajectory () const
void * operator new (size_t)
void operator delete (void *)
void SetDrawTrajectory (G4bool b)
void WLS ()
void SetForceDrawTrajectory (G4bool b)
void SetForceNoDrawTrajectory (G4bool b)
Public Member Functions inherited from G4Trajectory
G4Trajectory ()
G4Trajectory (const G4Track *aTrack)
G4Trajectory (G4Trajectory &)
virtual ~G4Trajectory ()
void * operator new (size_t)
void operator delete (void *)
G4int operator== (const G4Trajectory &r) const
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4double GetInitialKineticEnergy () const
G4ThreeVector GetInitialMomentum () const
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void AppendStep (const G4Step *aStep)
virtual G4int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ParticleDefinition * GetParticleDefinition ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
Private Attributes
G4bool fWls
G4bool fDrawit
G4bool fForceNoDraw
G4bool fForceDraw
G4ParticleDefinition * fParticleDefinition
Detailed Description
Definition at line 44 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 44 of file LXeTrajectory.hh
Constructor & Destructor Documentation
LXeTrajectory::LXeTrajectory ()
Definition at line 48 of file LXeTrajectory.cc.
View newest version in sPHENIX GitHub at line 48 of file LXeTrajectory.cc
References fParticleDefinition.
LXeTrajectory::LXeTrajectory (const G4Track * aTrack)
Definition at line 57 of file LXeTrajectory.cc.
View newest version in sPHENIX GitHub at line 57 of file LXeTrajectory.cc
References fParticleDefinition, and G4Track::GetDefinition().
LXeTrajectory::LXeTrajectory (LXeTrajectory & right)
Definition at line 65 of file LXeTrajectory.cc.
View newest version in sPHENIX GitHub at line 65 of file LXeTrajectory.cc
References fParticleDefinition.
LXeTrajectory::~LXeTrajectory () virtual
Definition at line 73 of file LXeTrajectory.cc.
View newest version in sPHENIX GitHub at line 73 of file LXeTrajectory.cc
Member Function Documentation
void LXeTrajectory::DrawTrajectory () const virtual
Reimplemented from G4Trajectory.
Definition at line 77 of file LXeTrajectory.cc.
View newest version in sPHENIX GitHub at line 77 of file LXeTrajectory.cc
References kdfinder::abs(), G4Polymarker::circles, G4VVisManager::Draw(), fDrawit, fForceDraw, fForceNoDraw, G4VMarker::filled, fParticleDefinition, fWls, G4VTrajectoryPoint::GetAuxiliaryPoints(), G4VVisManager::GetConcreteInstance(), G4Trajectory::GetPoint(), G4Trajectory::GetPointEntries(), G4VTrajectoryPoint::GetPosition(), G4OpticalPhoton::OpticalPhotonDefinition(), pos(), G4VMarker::SetFillStyle(), G4Polymarker::SetMarkerType(), G4VMarker::SetScreenSize(), G4Visible::SetVisAttributes(), and G4Polymarker::squares.
Referenced by LXeEventAction::EndOfEventAction().
void LXeTrajectory::operator delete (void * aTrajectory) inline
Definition at line 81 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 81 of file LXeTrajectory.hh
References LXeTrajectoryAllocator.
void * LXeTrajectory::operator new (size_t) inline
Definition at line 74 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 74 of file LXeTrajectory.hh
References LXeTrajectoryAllocator.
void LXeTrajectory::SetDrawTrajectory (G4bool b) inline
Definition at line 58 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 58 of file LXeTrajectory.hh
References b, and fDrawit.
Referenced by LXeTrackingAction::PostUserTrackingAction().
void LXeTrajectory::SetForceDrawTrajectory (G4bool b) inline
Definition at line 60 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 60 of file LXeTrajectory.hh
References b, and fForceDraw.
Referenced by LXeEventAction::EndOfEventAction().
void LXeTrajectory::SetForceNoDrawTrajectory (G4bool b) inline
Definition at line 61 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 61 of file LXeTrajectory.hh
References b, and fForceNoDraw.
Referenced by LXeEventAction::EndOfEventAction().
void LXeTrajectory::WLS () inline
Definition at line 59 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 59 of file LXeTrajectory.hh
References fWls.
Referenced by LXeTrackingAction::PostUserTrackingAction().
Member Data Documentation
G4bool LXeTrajectory::fDrawit private
Definition at line 66 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 66 of file LXeTrajectory.hh
Referenced by DrawTrajectory(), and SetDrawTrajectory().
G4bool LXeTrajectory::fForceDraw private
Definition at line 68 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 68 of file LXeTrajectory.hh
Referenced by DrawTrajectory(), and SetForceDrawTrajectory().
G4bool LXeTrajectory::fForceNoDraw private
Definition at line 67 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 67 of file LXeTrajectory.hh
Referenced by DrawTrajectory(), and SetForceNoDrawTrajectory().
G4ParticleDefinition* LXeTrajectory::fParticleDefinition private
Definition at line 69 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 69 of file LXeTrajectory.hh
Referenced by DrawTrajectory(), and LXeTrajectory().
G4bool LXeTrajectory::fWls private
Definition at line 65 of file LXeTrajectory.hh.
View newest version in sPHENIX GitHub at line 65 of file LXeTrajectory.hh
Referenced by DrawTrajectory(), and WLS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeTrajectory.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeTrajectory.cc