ECCE @ EIC Software: G4DNASancheExcitationModel Class Reference
G4DNASancheExcitationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNASancheExcitationModel.hh>
Public Member Functions
G4DNASancheExcitationModel (const G4ParticleDefinition *p=0, const G4String &nam="DNASancheExcitationModel")
virtual ~G4DNASancheExcitationModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
G4double PartialCrossSection (G4double energy, G4int level)
G4double TotalCrossSection (G4double t)
void ExtendLowEnergyLimit (G4double)
void SetVerboseLevel (G4int verbose)
void SelectStationary (G4bool input)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4int RandomSelect (G4double energy)
G4double VibrationEnergy (G4int level)
G4double Sum (G4double k)
G4double LinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4DNASancheExcitationModel & operator= (const G4DNASancheExcitationModel &right)
G4DNASancheExcitationModel (const G4DNASancheExcitationModel &)
Private Attributes
G4bool statCode
const std::vector< G4double > * fpWaterDensity
G4bool isInitialised
G4int verboseLevel
G4int nLevels
std::vector< G4double > tdummyVec
std::vector< std::vector
< G4double > > fEnergyLevelXS
std::vector< G4double > fEnergyTotalXS
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 43 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 43 of file G4DNASancheExcitationModel.hh
Constructor & Destructor Documentation
G4DNASancheExcitationModel::G4DNASancheExcitationModel (const G4ParticleDefinition * p = 0, const G4String & nam = "DNASancheExcitationModel")
Definition at line 42 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 42 of file G4DNASancheExcitationModel.cc
References eV, fParticleChangeForGamma, fpWaterDensity, G4cout, G4endl, G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), nLevels, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), statCode, and verboseLevel.
G4DNASancheExcitationModel::~G4DNASancheExcitationModel () virtual
Definition at line 82 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 82 of file G4DNASancheExcitationModel.cc
G4DNASancheExcitationModel::G4DNASancheExcitationModel (const G4DNASancheExcitationModel &) private
Member Function Documentation
G4double G4DNASancheExcitationModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 184 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 184 of file G4DNASancheExcitationModel.cc
References cm, eV, G4cout, G4endl, G4Material::GetIndex(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), TotalCrossSection(), and verboseLevel.
void G4DNASancheExcitationModel::ExtendLowEnergyLimit (G4double threshold) inline
Definition at line 121 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4DNASancheExcitationModel.hh
References CLHEP::eV, G4Exception(), JustWarning, and G4VEmModel::SetLowEnergyLimit().
Referenced by G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), and G4EmDNAChemistry_option2::ConstructProcess().
void G4DNASancheExcitationModel::Initialise (const G4ParticleDefinition * , const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 90 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 90 of file G4DNASancheExcitationModel.cc
References eV, FatalException, fEnergyLevelXS, fEnergyTotalXS, fParticleChangeForGamma, fpWaterDensity, G4cout, G4endl, G4Exception(), G4Material::GetMaterial(), G4VEmModel::GetParticleChangeForGamma(), G4VEmModel::HighEnergyLimit(), G4DNAMolecularMaterial::Instance(), isInitialised, JustWarning, G4VEmModel::LowEnergyLimit(), G4VEmModel::SetHighEnergyLimit(), t, tdummyVec, and verboseLevel.
G4double G4DNASancheExcitationModel::LinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 408 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 408 of file G4DNASancheExcitationModel.cc
References a, b, and e2.
Referenced by PartialCrossSection(), and TotalCrossSection().
G4DNASancheExcitationModel& G4DNASancheExcitationModel::operator= (const G4DNASancheExcitationModel & right) private
G4double G4DNASancheExcitationModel::PartialCrossSection (G4double energy, G4int level)
Definition at line 291 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 291 of file G4DNASancheExcitationModel.cc
References cm, e, eV, fEnergyLevelXS, LinInterpolate(), t1, t2, and tdummyVec.
Referenced by RandomSelect(), and Sum().
G4int G4DNASancheExcitationModel::RandomSelect (G4double energy) private
Definition at line 355 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 355 of file G4DNASancheExcitationModel.cc
References G4UniformRand, nLevels, PartialCrossSection(), and Acts::Test::values.
Referenced by SampleSecondaries().
void G4DNASancheExcitationModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * aDynamicElectron, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 229 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 229 of file G4DNASancheExcitationModel.cc
References fParticleChangeForGamma, G4cout, G4endl, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4VEmModel::HighEnergyLimit(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), RandomSelect(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), statCode, verboseLevel, and VibrationEnergy().
void G4DNASancheExcitationModel::SelectStationary (G4bool input) inline
Definition at line 133 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4DNASancheExcitationModel.hh
References statCode.
Referenced by G4EmDNAPhysics_stationary::ConstructProcess().
void G4DNASancheExcitationModel::SetVerboseLevel (G4int verbose) inline
Definition at line 73 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DNASancheExcitationModel.hh
References verboseLevel.
G4double G4DNASancheExcitationModel::Sum (G4double k) private
Definition at line 394 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 394 of file G4DNASancheExcitationModel.cc
References nLevels, and PartialCrossSection().
G4double G4DNASancheExcitationModel::TotalCrossSection (G4double t)
Definition at line 319 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 319 of file G4DNASancheExcitationModel.cc
References cm, e, eV, fEnergyTotalXS, LinInterpolate(), t1, t2, and tdummyVec.
Referenced by CrossSectionPerVolume().
G4double G4DNASancheExcitationModel::VibrationEnergy (G4int level) private
Definition at line 346 of file G4DNASancheExcitationModel.cc.
View newest version in sPHENIX GitHub at line 346 of file G4DNASancheExcitationModel.cc
References eV.
Referenced by SampleSecondaries().
Member Data Documentation
std::vector<std::vector<G4double> > G4DNASancheExcitationModel::fEnergyLevelXS private
Definition at line 110 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DNASancheExcitationModel.hh
Referenced by Initialise(), and PartialCrossSection().
std::vector<G4double> G4DNASancheExcitationModel::fEnergyTotalXS private
Definition at line 111 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4DNASancheExcitationModel.hh
Referenced by Initialise(), and TotalCrossSection().
G4ParticleChangeForGamma* G4DNASancheExcitationModel::fParticleChangeForGamma protected
Definition at line 82 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DNASancheExcitationModel.hh
Referenced by G4DNASancheExcitationModel(), Initialise(), and SampleSecondaries().
const std::vector<G4double>* G4DNASancheExcitationModel::fpWaterDensity private
Definition at line 89 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DNASancheExcitationModel.hh
Referenced by G4DNASancheExcitationModel(), and Initialise().
G4bool G4DNASancheExcitationModel::isInitialised private
Definition at line 91 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4DNASancheExcitationModel.hh
Referenced by Initialise().
G4int G4DNASancheExcitationModel::nLevels private
Definition at line 97 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4DNASancheExcitationModel.hh
Referenced by G4DNASancheExcitationModel(), RandomSelect(), and Sum().
G4bool G4DNASancheExcitationModel::statCode private
Definition at line 86 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4DNASancheExcitationModel.hh
Referenced by G4DNASancheExcitationModel(), SampleSecondaries(), and SelectStationary().
std::vector<G4double> G4DNASancheExcitationModel::tdummyVec private
Definition at line 109 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4DNASancheExcitationModel.hh
Referenced by Initialise(), PartialCrossSection(), and TotalCrossSection().
G4int G4DNASancheExcitationModel::verboseLevel private
Definition at line 92 of file G4DNASancheExcitationModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4DNASancheExcitationModel.hh
Referenced by CrossSectionPerVolume(), G4DNASancheExcitationModel(), Initialise(), SampleSecondaries(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNASancheExcitationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNASancheExcitationModel.cc