ECCE @ EIC Software: G4ParticleHPDataUsed Class Reference
G4ParticleHPDataUsed Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDataUsed.hh>
Public Member Functions
G4ParticleHPDataUsed ()
void SetA (G4double anA)
void SetZ (G4int aZ)
void SetM (G4int aM)
void SetName (G4String aName)
G4int GetZ ()
G4double GetA ()
G4int GetM ()
G4String GetName ()
G4bool IsThisNaturalAbundance ()
void SetNaturalAbundanceFlag ()
Private Attributes
G4String theName
G4double theA
G4int theZ
G4int theM
G4bool nat
Detailed Description
Definition at line 35 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPDataUsed.hh
Constructor & Destructor Documentation
G4ParticleHPDataUsed::G4ParticleHPDataUsed () inline
Definition at line 39 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPDataUsed.hh
References nat, theA, theM, theName, and theZ.
Member Function Documentation
G4double G4ParticleHPDataUsed::GetA (void) inline
Definition at line 54 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPDataUsed.hh
References theA.
Referenced by G4ParticleHPNames::GetName(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPIsoData::Init(), G4WendtFissionFragmentGenerator::InitializeANucleus(), and G4ParticleHPFinalState::SetAZMs().
G4int G4ParticleHPDataUsed::GetM () inline
Definition at line 55 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPDataUsed.hh
References theM.
Referenced by G4ParticleHPFinalState::SetAZMs().
G4String G4ParticleHPDataUsed::GetName (void) inline
Definition at line 56 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPDataUsed.hh
References theName.
Referenced by G4ParticleHPNames::GetName(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4FissionLibrary::Init(), and G4WendtFissionFragmentGenerator::InitializeANucleus().
G4int G4ParticleHPDataUsed::GetZ (void) inline
Definition at line 53 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPDataUsed.hh
References theZ.
Referenced by G4ParticleHPNames::GetName(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPIsoData::Init(), G4WendtFissionFragmentGenerator::InitializeANucleus(), and G4ParticleHPFinalState::SetAZMs().
G4bool G4ParticleHPDataUsed::IsThisNaturalAbundance () inline
Definition at line 65 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPDataUsed.hh
References nat.
Referenced by G4ParticleHPNames::GetName().
void G4ParticleHPDataUsed::SetA (G4double anA) inline
Definition at line 48 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPDataUsed.hh
References theA.
Referenced by G4ParticleHPNames::GetName().
void G4ParticleHPDataUsed::SetM (G4int aM) inline
Definition at line 50 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPDataUsed.hh
References theM.
Referenced by G4ParticleHPNames::GetName().
void G4ParticleHPDataUsed::SetName (G4String aName) inline
Definition at line 51 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPDataUsed.hh
References theName.
Referenced by G4ParticleHPNames::GetName().
void G4ParticleHPDataUsed::SetNaturalAbundanceFlag () inline
Definition at line 66 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPDataUsed.hh
References nat, and TRUE.
Referenced by G4ParticleHPNames::GetName().
void G4ParticleHPDataUsed::SetZ (G4int aZ) inline
Definition at line 49 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPDataUsed.hh
References theZ.
Referenced by G4ParticleHPNames::GetName().
Member Data Documentation
G4bool G4ParticleHPDataUsed::nat private
Definition at line 66 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPDataUsed.hh
Referenced by G4ParticleHPDataUsed(), IsThisNaturalAbundance(), and SetNaturalAbundanceFlag().
G4double G4ParticleHPDataUsed::theA private
Definition at line 61 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPDataUsed.hh
Referenced by G4ParticleHPDataUsed(), GetA(), and SetA().
G4int G4ParticleHPDataUsed::theM private
Definition at line 63 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPDataUsed.hh
Referenced by G4ParticleHPDataUsed(), GetM(), and SetM().
G4String G4ParticleHPDataUsed::theName private
Definition at line 60 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPDataUsed.hh
Referenced by G4ParticleHPDataUsed(), GetName(), and SetName().
G4int G4ParticleHPDataUsed::theZ private
Definition at line 62 of file G4ParticleHPDataUsed.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPDataUsed.hh
Referenced by G4ParticleHPDataUsed(), GetZ(), and SetZ().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDataUsed.hh