ECCE @ EIC Software: G4TritonDecay Class Reference
G4TritonDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4TritonDecay.hh>
Public Member Functions
G4TritonDecay (const G4ParticleDefinition *theParentNucleus, const G4double &theBR, const G4double &Qvalue, const G4double &excitation, const G4Ions::G4FloatLevelBase &flb)
virtual ~G4TritonDecay ()
virtual G4DecayProducts * DecayIt (G4double)
virtual void DumpNuclearInfo ()
Public Member Functions inherited from G4NuclearDecay
G4NuclearDecay (const G4String &channelName, const G4RadioactiveDecayMode &mode, const G4double &excitation, const G4Ions::G4FloatLevelBase &floatingLevel)
virtual ~G4NuclearDecay ()
G4RadioactiveDecayMode GetDecayMode ()
G4double GetDaughterExcitation ()
G4Ions::G4FloatLevelBase GetFloatingLevel ()
G4ParticleDefinition * GetDaughterNucleus ()
void SetHLThreshold (G4double HLT)
G4double GetHLThreshold ()
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Private Attributes
const G4double transitionQ
Additional Inherited Members
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Protected Attributes inherited from G4NuclearDecay
const G4RadioactiveDecayMode theMode
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 42 of file G4TritonDecay.hh.
View newest version in sPHENIX GitHub at line 42 of file G4TritonDecay.hh
Constructor & Destructor Documentation
G4TritonDecay::G4TritonDecay (const G4ParticleDefinition * theParentNucleus, const G4double & theBR, const G4double & Qvalue, const G4double & excitation, const G4Ions::G4FloatLevelBase & flb)
Definition at line 47 of file G4TritonDecay.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TritonDecay.cc
References G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4VDecayChannel::SetBR(), G4VDecayChannel::SetDaughter(), G4VDecayChannel::SetNumberOfDaughters(), and G4VDecayChannel::SetParent().
G4TritonDecay::~G4TritonDecay () virtual
Definition at line 66 of file G4TritonDecay.cc.
View newest version in sPHENIX GitHub at line 66 of file G4TritonDecay.cc
Member Function Documentation
G4DecayProducts * G4TritonDecay::DecayIt (G4double) virtual
Implements G4VDecayChannel.
Definition at line 70 of file G4TritonDecay.cc.
View newest version in sPHENIX GitHub at line 70 of file G4TritonDecay.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4ParticleDefinition::GetPDGMass(), phi, G4DecayProducts::PushProducts(), rad, transitionQ, and twopi.
void G4TritonDecay::DumpNuclearInfo () virtual
Implements G4NuclearDecay.
Definition at line 132 of file G4TritonDecay.cc.
View newest version in sPHENIX GitHub at line 132 of file G4TritonDecay.cc
References G4cout, G4endl, G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughterName(), G4VDecayChannel::GetParentName(), and transitionQ.
Member Data Documentation
const G4double G4TritonDecay::transitionQ private
Definition at line 56 of file G4TritonDecay.hh.
View newest version in sPHENIX GitHub at line 56 of file G4TritonDecay.hh
Referenced by DecayIt(), and DumpNuclearInfo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4TritonDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4TritonDecay.cc