ECCE @ EIC Software: G4GSPWACorrections Class Reference
G4GSPWACorrections Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4GSPWACorrections.hh>
Classes
struct DataPerMaterial
Public Member Functions
G4GSPWACorrections (G4bool iselectron=true)
~G4GSPWACorrections ()
void Initialise ()
void GetPWACorrectionFactors (G4double logekin, G4double beta2, G4int matindx, G4double &corToScr, G4double &corToQ1, G4double &corToG2PerG1)
Private Member Functions
void InitDataPerElement ()
void InitDataPerMaterials ()
void LoadDataElement (const G4Element *)
void InitDataMaterial (const G4Material *)
void ClearDataPerElement ()
void ClearDataPerMaterial ()
Private Attributes
G4bool fIsElectron
G4double fMaxEkin
G4double fLogMinEkin
G4double fInvLogDelEkin
G4double fMinBeta2
G4double fInvDelBeta2
std::vector< DataPerMaterial * > fDataPerElement
std::vector< DataPerMaterial * > fDataPerMaterial
Static Private Attributes
static constexpr G4int gMaxZet = 98
static constexpr G4int gNumEkin = 31
static constexpr G4int gNumBeta2 = 16
static constexpr G4double gMinEkin = 1.*CLHEP::keV
static constexpr G4double gMidEkin = 100.*CLHEP::keV
static constexpr G4double gMaxBeta2 = 0.9999
static const std::string gElemSymbols []
Detailed Description
Definition at line 61 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 61 of file G4GSPWACorrections.hh
Constructor & Destructor Documentation
G4GSPWACorrections::G4GSPWACorrections (G4bool iselectron = true)
Definition at line 64 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 64 of file G4GSPWACorrections.cc
References CLHEP::electron_mass_c2, fInvDelBeta2, fInvLogDelEkin, fLogMinEkin, fMaxEkin, fMinBeta2, G4Log(), gMaxBeta2, gMidEkin, gMinEkin, gNumBeta2, gNumEkin, and pt2.
G4GSPWACorrections::~G4GSPWACorrections ()
Definition at line 75 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 75 of file G4GSPWACorrections.cc
References ClearDataPerElement(), and ClearDataPerMaterial().
Member Function Documentation
void G4GSPWACorrections::ClearDataPerElement () private
Definition at line 345 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 345 of file G4GSPWACorrections.cc
References fDataPerElement.
Referenced by ~G4GSPWACorrections().
void G4GSPWACorrections::ClearDataPerMaterial () private
Definition at line 358 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 358 of file G4GSPWACorrections.cc
References fDataPerMaterial.
Referenced by Initialise(), and ~G4GSPWACorrections().
void G4GSPWACorrections::GetPWACorrectionFactors (G4double logekin, G4double beta2, G4int matindx, G4double & corToScr, G4double & corToQ1, G4double & corToG2PerG1)
Definition at line 81 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 81 of file G4GSPWACorrections.cc
References G4GSPWACorrections::DataPerMaterial::fCorFirstMoment, G4GSPWACorrections::DataPerMaterial::fCorScreening, G4GSPWACorrections::DataPerMaterial::fCorSecondMoment, fDataPerMaterial, fInvDelBeta2, fInvLogDelEkin, fLogMinEkin, fMinBeta2, gMaxBeta2, gNumBeta2, and gNumEkin.
Referenced by G4GoudsmitSaundersonMscModel::CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePath(), and G4GoudsmitSaundersonMscModel::GetTransportMeanFreePathOnly().
void G4GSPWACorrections::InitDataMaterial (const G4Material * mat) private
Definition at line 220 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 220 of file G4GSPWACorrections.cc
References CLHEP::cm, CLHEP::cm3, CLHEP::electron_mass_c2, G4GSPWACorrections::DataPerMaterial::fCorFirstMoment, G4GSPWACorrections::DataPerMaterial::fCorScreening, G4GSPWACorrections::DataPerMaterial::fCorSecondMoment, fDataPerElement, fDataPerMaterial, CLHEP::fine_structure_const, fInvDelBeta2, fInvLogDelEkin, fLogMinEkin, fMinBeta2, CLHEP::g, G4Exp(), G4Log(), G4lrint(), G4Material::GetDensity(), G4Material::GetElementVector(), G4Material::GetIndex(), G4Material::GetNumberOfElements(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZ(), gMaxZet, gMidEkin, gNumBeta2, gNumEkin, CLHEP::MeV, and pt2.
Referenced by InitDataPerMaterials().
void G4GSPWACorrections::InitDataPerElement () private
Definition at line 121 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 121 of file G4GSPWACorrections.cc
References fDataPerElement, G4lrint(), G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4Element::GetZ(), gMaxZet, G4MaterialCutsCouple::IsUsed(), LoadDataElement(), and mat.
Referenced by Initialise().
void G4GSPWACorrections::InitDataPerMaterials () private
Definition at line 153 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 153 of file G4GSPWACorrections.cc
References fDataPerMaterial, G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfMaterials(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), InitDataMaterial(), G4MaterialCutsCouple::IsUsed(), and mat.
Referenced by Initialise().
void G4GSPWACorrections::Initialise ()
Definition at line 111 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 111 of file G4GSPWACorrections.cc
References ClearDataPerMaterial(), InitDataPerElement(), and InitDataPerMaterials().
Referenced by G4GoudsmitSaundersonMscModel::Initialise().
void G4GSPWACorrections::LoadDataElement (const G4Element * elem) private
Definition at line 176 of file G4GSPWACorrections.cc.
View newest version in sPHENIX GitHub at line 176 of file G4GSPWACorrections.cc
References FatalException, G4GSPWACorrections::DataPerMaterial::fCorFirstMoment, G4GSPWACorrections::DataPerMaterial::fCorScreening, G4GSPWACorrections::DataPerMaterial::fCorSecondMoment, fDataPerElement, fIsElectron, test::fname, G4Exception(), gElemSymbols, G4Element::GetZasInt(), gMaxZet, gNumEkin, and in.
Referenced by InitDataPerElement().
Member Data Documentation
std::vector<DataPerMaterial*> G4GSPWACorrections::fDataPerElement private
Definition at line 110 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 110 of file G4GSPWACorrections.hh
Referenced by ClearDataPerElement(), InitDataMaterial(), InitDataPerElement(), and LoadDataElement().
std::vector<DataPerMaterial*> G4GSPWACorrections::fDataPerMaterial private
Definition at line 111 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4GSPWACorrections.hh
Referenced by ClearDataPerMaterial(), GetPWACorrectionFactors(), InitDataMaterial(), and InitDataPerMaterials().
G4double G4GSPWACorrections::fInvDelBeta2 private
Definition at line 106 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 106 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), GetPWACorrectionFactors(), and InitDataMaterial().
G4double G4GSPWACorrections::fInvLogDelEkin private
Definition at line 104 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 104 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), GetPWACorrectionFactors(), and InitDataMaterial().
G4bool G4GSPWACorrections::fIsElectron private
Definition at line 94 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GSPWACorrections.hh
Referenced by LoadDataElement().
G4double G4GSPWACorrections::fLogMinEkin private
Definition at line 103 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 103 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), GetPWACorrectionFactors(), and InitDataMaterial().
G4double G4GSPWACorrections::fMaxEkin private
Definition at line 102 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 102 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections().
G4double G4GSPWACorrections::fMinBeta2 private
Definition at line 105 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 105 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), GetPWACorrectionFactors(), and InitDataMaterial().
const std::string G4GSPWACorrections::gElemSymbols static private
Initial value:
= {"H","He","Li","Be","B" ,
 "C" ,"N" ,"O" ,"F" ,"Ne","Na","Mg","Al","Si","P" , "S","Cl","Ar","K" ,"Ca","Sc",
 "Ti","V" ,"Cr","Mn","Fe","Co","Ni","Cu","Zn","Ga","Ge","As","Se","Br","Kr","Rb",
 "Sr","Y" ,"Zr","Nb","Mo","Tc","Ru","Rh","Pd","Ag","Cd","In","Sn","Sb","Te","I" ,
 "Xe","Cs","Ba","La","Ce","Pr","Nd","Pm","Sm","Eu","Gd","Tb","Dy","Ho","Er","Tm",
 "Yb","Lu","Hf","Ta","W" ,"Re","Os","Ir","Pt","Au","Hg","Tl","Pb","Bi","Po","At",
 "Rn","Fr","Ra","Ac","Th","Pa","U" ,"Np","Pu","Am","Cm","Bk","Cf"}
Definition at line 108 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 108 of file G4GSPWACorrections.hh
Referenced by LoadDataElement().
constexpr G4double G4GSPWACorrections::gMaxBeta2 = 0.9999 static private
Definition at line 100 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 100 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), and GetPWACorrectionFactors().
constexpr G4int G4GSPWACorrections::gMaxZet = 98 static private
Definition at line 95 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 95 of file G4GSPWACorrections.hh
Referenced by InitDataMaterial(), InitDataPerElement(), and LoadDataElement().
constexpr G4double G4GSPWACorrections::gMidEkin = 100.*CLHEP::keV static private
Definition at line 99 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 99 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), and InitDataMaterial().
constexpr G4double G4GSPWACorrections::gMinEkin = 1.*CLHEP::keV static private
Definition at line 98 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 98 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections().
constexpr G4int G4GSPWACorrections::gNumBeta2 = 16 static private
Definition at line 97 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 97 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), GetPWACorrectionFactors(), and InitDataMaterial().
constexpr G4int G4GSPWACorrections::gNumEkin = 31 static private
Definition at line 96 of file G4GSPWACorrections.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GSPWACorrections.hh
Referenced by G4GSPWACorrections(), GetPWACorrectionFactors(), InitDataMaterial(), and LoadDataElement().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4GSPWACorrections.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4GSPWACorrections.cc