ECCE @ EIC Software: doiPETSteppingAction Class Reference
doiPETSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETSteppingAction.hh>
Public Member Functions
doiPETSteppingAction ()
virtual ~doiPETSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 48 of file doiPETSteppingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file doiPETSteppingAction.hh
Constructor & Destructor Documentation
doiPETSteppingAction::doiPETSteppingAction ()
Definition at line 57 of file doiPETSteppingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file doiPETSteppingAction.cc
doiPETSteppingAction::~doiPETSteppingAction () virtual
Definition at line 62 of file doiPETSteppingAction.cc.
View newest version in sPHENIX GitHub at line 62 of file doiPETSteppingAction.cc
Member Function Documentation
void doiPETSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 66 of file doiPETSteppingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file doiPETSteppingAction.cc
References edep, fStopAndKill, G4VTouchable::GetCopyNumber(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), doiPETAnalysis::GetInstance(), doiPETRun::GetIntractionInfomation(), G4VPhysicalVolume::GetName(), G4RunManager::GetNonConstCurrentRun(), G4ParticleDefinition::GetParticleName(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4RunManager::GetRunManager(), doiPETAnalysis::GetScatterIndexInPhantom(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), pos(), doiPETRun::SetAnnihilationTime(), InteractionInformation::SetBlockNo(), InteractionInformation::SetCrystalNo(), InteractionInformation::SetEdep(), InteractionInformation::SetGlobalTime(), InteractionInformation::SetInteractionPositionInCrystal(), doiPETAnalysis::SetSourcePosition(), G4Track::SetTrackStatus(), track, and G4AffineTransform::TransformPoint().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/src/doiPETSteppingAction.cc