ECCE @ EIC Software: G4GDMLEvaluator Class Reference
G4GDMLEvaluator Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLEvaluator.hh>
Public Member Functions
G4GDMLEvaluator ()
void Clear ()
void DefineConstant (const G4String &, G4double)
void DefineVariable (const G4String &, G4double)
void DefineMatrix (const G4String &, G4int, std::vector< G4double >)
void SetVariable (const G4String &, G4double)
G4bool IsVariable (const G4String &) const
G4String SolveBrackets (const G4String &)
G4double Evaluate (const G4String &)
G4int EvaluateInteger (const G4String &)
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4String ConvertToString (G4int ival)
G4String ConvertToString (G4double dval)
Private Attributes
G4Evaluator eval
std::vector< G4String > variableList
Detailed Description
Definition at line 46 of file G4GDMLEvaluator.hh.
View newest version in sPHENIX GitHub at line 46 of file G4GDMLEvaluator.hh
Constructor & Destructor Documentation
G4GDMLEvaluator::G4GDMLEvaluator ()
Definition at line 40 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 40 of file G4GDMLEvaluator.cc
References ampere, candela, HepTool::Evaluator::clear(), eval, kelvin, kilogram, meter, mole, second, HepTool::Evaluator::setStdMath(), and HepTool::Evaluator::setSystemOfUnits().
Member Function Documentation
void G4GDMLEvaluator::Clear ()
Definition at line 47 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 47 of file G4GDMLEvaluator.cc
References ampere, candela, HepTool::Evaluator::clear(), eval, kelvin, kilogram, meter, mole, second, HepTool::Evaluator::setStdMath(), HepTool::Evaluator::setSystemOfUnits(), and variableList.
Referenced by G4GDMLReadStructure::Clear().
G4String G4GDMLEvaluator::ConvertToString (G4int ival)
Definition at line 284 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 284 of file G4GDMLEvaluator.cc
Referenced by G4GDMLWriteStructure::ExportEnergyCuts(), and G4GDMLParser::ExportRegions().
G4String G4GDMLEvaluator::ConvertToString (G4double dval)
Definition at line 292 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 292 of file G4GDMLEvaluator.cc
void G4GDMLEvaluator::DefineConstant (const G4String & name, G4double value)
Definition at line 56 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 56 of file G4GDMLEvaluator.cc
References eval, FatalException, HepTool::Evaluator::findVariable(), G4Exception(), and HepTool::Evaluator::setVariable().
Referenced by G4GDMLReadDefine::ConstantRead(), DefineMatrix(), G4GDMLReadDefine::ExpressionRead(), and G4GDMLReadDefine::QuantityRead().
void G4GDMLEvaluator::DefineMatrix (const G4String & name, G4int coldim, std::vector< G4double > valueList)
Definition at line 79 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 79 of file G4GDMLEvaluator.cc
References DefineConstant(), FatalException, and G4Exception().
Referenced by G4GDMLReadDefine::MatrixRead().
void G4GDMLEvaluator::DefineVariable (const G4String & name, G4double value)
Definition at line 67 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 67 of file G4GDMLEvaluator.cc
References eval, FatalException, HepTool::Evaluator::findVariable(), G4Exception(), HepTool::Evaluator::setVariable(), and variableList.
Referenced by G4GDMLReadDefine::VariableRead().
G4double G4GDMLEvaluator::Evaluate (const G4String & in)
Definition at line 212 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 212 of file G4GDMLEvaluator.cc
References eval, HepTool::Evaluator::evaluate(), FatalException, G4Exception(), HepTool::Evaluator::OK, HepTool::Evaluator::print_error(), SolveBrackets(), and HepTool::Evaluator::status().
Referenced by G4GDMLReadMaterials::AtomRead(), G4GDMLReadStructure::AxisRead(), G4GDMLReadParamvol::Box_dimensionsRead(), G4GDMLReadSolids::BoxRead(), G03ColorReader::ColorRead(), G4GDMLReadParamvol::Cone_dimensionsRead(), G4GDMLReadSolids::ConeRead(), G4GDMLReadDefine::ConstantRead(), G4GDMLReadSolids::CutTubeRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadMaterials::DRead(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadMaterials::ElementRead(), G4GDMLReadParamvol::Ellipsoid_dimensionsRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), EvaluateInteger(), G4GDMLReadDefine::ExpressionRead(), G4GDMLReadMaterials::FractionRead(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), GetConstant(), GetVariable(), G4GDMLReadParamvol::Hype_dimensionsRead(), G4GDMLReadSolids::HypeRead(), G4GDMLParser::ImportRegions(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadDefine::MatrixRead(), G4GDMLReadMaterials::MEERead(), G4GDMLReadSolids::OpticalSurfaceRead(), G4GDMLReadParamvol::Orb_dimensionsRead(), G4GDMLReadSolids::OrbRead(), G4GDMLReadParamvol::Para_dimensionsRead(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLReadParamvol::ParameterisedRead(), G4GDMLReadSolids::ParaRead(), G4GDMLReadParamvol::Polycone_dimensionsRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLReadDefine::PositionRead(), G4GDMLReadMaterials::PRead(), G4GDMLReadStructure::QuantityRead(), G4GDMLReadDefine::QuantityRead(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadDefine::RotationRead(), G4GDMLReadSolids::RZPointRead(), G4GDMLReadDefine::ScaleRead(), G4GDMLReadSolids::SectionRead(), G4GDMLReadParamvol::Sphere_dimensionsRead(), G4GDMLReadSolids::SphereRead(), G4GDMLReadParamvol::Torus_dimensionsRead(), G4GDMLReadSolids::TorusRead(), G4GDMLReadParamvol::Trap_dimensionsRead(), G4GDMLReadSolids::TrapRead(), G4GDMLReadParamvol::Trd_dimensionsRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadMaterials::TRead(), G4GDMLReadParamvol::Tube_dimensionsRead(), G4GDMLReadSolids::TubeRead(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), G4GDMLReadSolids::TwoDimVertexRead(), G4GDMLReadDefine::VariableRead(), G4GDMLReadDefine::VectorRead(), and G4GDMLReadSolids::ZplaneRead().
G4int G4GDMLEvaluator::EvaluateInteger (const G4String & expression)
Definition at line 233 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 233 of file G4GDMLEvaluator.cc
References Evaluate(), FatalException, and G4Exception().
Referenced by G4GDMLReadMaterials::CompositeRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadMaterials::IsotopeRead(), G4GDMLRead::LoopRead(), G4GDMLReadDefine::MatrixRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadSolids::PolyhedraRead(), SolveBrackets(), and G4GDMLReadStructure::Volume_contentRead().
G4double G4GDMLEvaluator::GetConstant (const G4String & name)
Definition at line 255 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 255 of file G4GDMLEvaluator.cc
References eval, Evaluate(), FatalException, HepTool::Evaluator::findVariable(), G4Exception(), and IsVariable().
Referenced by G4GDMLReadDefine::GetConstant().
G4double G4GDMLEvaluator::GetVariable (const G4String & name)
Definition at line 273 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 273 of file G4GDMLEvaluator.cc
References Evaluate(), FatalException, G4Exception(), and IsVariable().
Referenced by G4GDMLReadDefine::GetVariable().
G4bool G4GDMLEvaluator::IsVariable (const G4String & name) const
Definition at line 145 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 145 of file G4GDMLEvaluator.cc
References variableList.
Referenced by GetConstant(), GetVariable(), G4GDMLReadDefine::IsValidID(), G4GDMLRead::LoopRead(), and SetVariable().
void G4GDMLEvaluator::SetVariable (const G4String & name, G4double value)
Definition at line 134 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 134 of file G4GDMLEvaluator.cc
References eval, FatalException, G4Exception(), IsVariable(), and HepTool::Evaluator::setVariable().
Referenced by G4GDMLRead::LoopRead().
G4String G4GDMLEvaluator::SolveBrackets (const G4String & in)
Definition at line 157 of file G4GDMLEvaluator.cc.
View newest version in sPHENIX GitHub at line 157 of file G4GDMLEvaluator.cc
References G4String::append(), close(), EvaluateInteger(), FatalException, G4Exception(), in, and Acts::open.
Referenced by Evaluate(), G4GDMLRead::GenerateName(), and G4GDMLRead::GeneratePhysvolName().
Member Data Documentation
G4Evaluator G4GDMLEvaluator::eval private
Definition at line 69 of file G4GDMLEvaluator.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GDMLEvaluator.hh
Referenced by Clear(), DefineConstant(), DefineVariable(), Evaluate(), G4GDMLEvaluator(), GetConstant(), and SetVariable().
std::vector<G4String> G4GDMLEvaluator::variableList private
Definition at line 70 of file G4GDMLEvaluator.hh.
View newest version in sPHENIX GitHub at line 70 of file G4GDMLEvaluator.hh
Referenced by Clear(), DefineVariable(), and IsVariable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLEvaluator.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLEvaluator.cc