ECCE @ EIC Software: G4VDecayChannel Class Reference
G4VDecayChannel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4VDecayChannel.hh>
Public Member Functions
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
virtual G4DecayProducts * DecayIt (G4double parentMass=-1.0)=0
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Protected Member Functions
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Protected Attributes
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Static Protected Attributes
static const G4String noName = " "
Private Member Functions
void FillDaughters ()
void FillParent ()
const G4String & GetNoName () const
Detailed Description
Definition at line 52 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VDecayChannel.hh
Constructor & Destructor Documentation
G4VDecayChannel::G4VDecayChannel (const G4String & aName, G4int Verbose = 1)
Definition at line 69 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4VDecayChannel.cc
References G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, G4MT_parent, G4MT_parent_mass, G4ParticleTable::GetParticleTable(), and particletable.
G4VDecayChannel::G4VDecayChannel (const G4String & aName, const G4String & theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String & theDaughterName1, const G4String & theDaughterName2 = "", const G4String & theDaughterName3 = "", const G4String & theDaughterName4 = "")
Definition at line 90 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 90 of file G4VDecayChannel.cc
References daughters_name, G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, G4MT_parent, G4MT_parent_mass, G4ParticleTable::GetParticleTable(), numberOfDaughters, parent_name, particletable, and rbranch.
G4VDecayChannel::~G4VDecayChannel () virtual
Definition at line 214 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 214 of file G4VDecayChannel.cc
References ClearDaughtersName(), daughtersMutex, G4MT_daughters_mass, G4MT_daughters_width, G4MUTEXDESTROY, parent_name, and parentMutex.
G4VDecayChannel::G4VDecayChannel () protected
Definition at line 48 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VDecayChannel.cc
References G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, G4MT_parent, G4MT_parent_mass, G4ParticleTable::GetParticleTable(), and particletable.
G4VDecayChannel::G4VDecayChannel (const G4VDecayChannel & right) protected
Definition at line 134 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 134 of file G4VDecayChannel.cc
References daughters_name, daughtersMutex, G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, G4MT_parent, G4MT_parent_mass, G4MUTEXINIT, G4ParticleTable::GetParticleTable(), kinematics_name, numberOfDaughters, parent_name, parent_polarization, parentMutex, particletable, rangeMass, rbranch, and verboseLevel.
Member Function Documentation
void G4VDecayChannel::CheckAndFillDaughters () inline protected
Definition at line 320 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 320 of file G4VDecayChannel.hh
References daughtersMutex, FillDaughters(), G4MT_daughters, and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by G4AlphaDecay::DecayIt(), G4TritonDecay::DecayIt(), G4ECDecay::DecayIt(), G4NeutronDecay::DecayIt(), G4ProtonDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4PhaseSpaceDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4GeneralPhaseSpaceDecay::DecayIt(), GetAngularMomentum(), GetDaughter(), G4PhaseSpaceDecayChannel::IsOKWithParentMass(), and IsOKWithParentMass().
void G4VDecayChannel::CheckAndFillParent () inline protected
Definition at line 328 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 328 of file G4VDecayChannel.hh
References FillParent(), G4MT_parent, parentMutex, and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by G4AlphaDecay::DecayIt(), G4TritonDecay::DecayIt(), G4ECDecay::DecayIt(), G4NeutronDecay::DecayIt(), G4SFDecay::DecayIt(), G4ProtonDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4ITDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4PhaseSpaceDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4GeneralPhaseSpaceDecay::DecayIt(), FillDaughters(), GetParent(), G4PhaseSpaceDecayChannel::IsOKWithParentMass(), and IsOKWithParentMass().
void G4VDecayChannel::ClearDaughtersName () protected
Definition at line 227 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 227 of file G4VDecayChannel.cc
References daughters_name, daughtersMutex, G4cout, G4endl, G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, numberOfDaughters, parent_name, and verboseLevel.
Referenced by G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), SetNumberOfDaughters(), and ~G4VDecayChannel().
virtual G4DecayProducts* G4VDecayChannel::DecayIt (G4double parentMass = -1.0) pure virtual
Implemented in G4GeneralPhaseSpaceDecay, G4MuonRadiativeDecayChannelWithSpin, G4PionRadiativeDecayChannel, G4MuonDecayChannelWithSpin, G4PhaseSpaceDecayChannel, G4TauLeptonicDecayChannel, G4DalitzDecayChannel, G4MuonDecayChannel, G4NeutronBetaDecayChannel, G4KL3DecayChannel, G4ITDecay, G4BetaMinusDecay, G4BetaPlusDecay, G4NeutronDecay, G4ProtonDecay, G4SFDecay, G4ECDecay, G4AlphaDecay, and G4TritonDecay.
Referenced by G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4IntraNucleiCascader::decayTrappedParticle(), G4RadioactiveDecayBase::DoDecay(), and G4RadioactiveDecay::DoDecay().
void G4VDecayChannel::DumpInfo ()
Definition at line 547 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 547 of file G4VDecayChannel.cc
References daughters_name, G4cout, G4endl, kinematics_name, numberOfDaughters, and rbranch.
Referenced by G4PhaseSpaceDecayChannel::DecayIt(), G4GeneralPhaseSpaceDecay::DecayIt(), and G4KL3DecayChannel::G4KL3DecayChannel().
G4double G4VDecayChannel::DynamicalMass (G4double massPDG, G4double width, G4double maxDev = +1.) const protected
Definition at line 567 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 567 of file G4VDecayChannel.cc
References G4UniformRand, mass, rangeMass, x, and y.
Referenced by G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), and G4PhaseSpaceDecayChannel::TwoBodyDecayIt().
void G4VDecayChannel::FillDaughters () private
Definition at line 329 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 329 of file G4VDecayChannel.cc
References CheckAndFillParent(), daughters_name, daughtersMutex, FatalException, G4ParticleTable::FindParticle(), G4cout, G4endl, G4Exception(), G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, G4MT_parent, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), GetVerboseLevel(), GeV, numberOfDaughters, parent_name, particletable, rangeMass, SetBR(), and verboseLevel.
Referenced by CheckAndFillDaughters().
void G4VDecayChannel::FillParent () private
Definition at line 445 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 445 of file G4VDecayChannel.cc
References FatalException, G4ParticleTable::FindParticle(), G4cout, G4endl, G4Exception(), G4MT_parent, G4MT_parent_mass, G4ParticleDefinition::GetPDGMass(), parent_name, parentMutex, particletable, and verboseLevel.
Referenced by CheckAndFillParent().
G4int G4VDecayChannel::GetAngularMomentum ()
Definition at line 489 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 489 of file G4VDecayChannel.cc
References kdfinder::abs(), CheckAndFillDaughters(), G4cout, G4endl, G4Exception(), G4MT_daughters, G4MT_parent, G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGiSpin(), JustWarning, numberOfDaughters, and verboseLevel.
G4double G4VDecayChannel::GetBR () const inline
Definition at line 293 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 293 of file G4VDecayChannel.hh
References rbranch.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4TritonDecay::DumpNuclearInfo(), G4AlphaDecay::DumpNuclearInfo(), G4ECDecay::DumpNuclearInfo(), G4SFDecay::DumpNuclearInfo(), G4NeutronDecay::DumpNuclearInfo(), G4ProtonDecay::DumpNuclearInfo(), G4BetaPlusDecay::DumpNuclearInfo(), G4BetaMinusDecay::DumpNuclearInfo(), G4ITDecay::DumpNuclearInfo(), G4KineticTrack::G4KineticTrack(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4DecayTableMessenger::GetCurrentValue(), G4DecayTable::Insert(), G4RadioactiveDecayBase::LoadDecayTable(), and G4RadioactiveDecay::LoadDecayTable().
G4ParticleDefinition * G4VDecayChannel::GetDaughter (G4int anIndex) inline
Definition at line 211 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 211 of file G4VDecayChannel.hh
References CheckAndFillDaughters(), G4cout, G4endl, G4MT_daughters, numberOfDaughters, and verboseLevel.
Referenced by G4IonTable::CreateIon(), G4KineticTrack::Decay(), G4KineticTrack::G4KineticTrack(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4NuclearDecay::GetDaughterNucleus(), and G4MTRunManagerKernel::SetUpDecayChannels().
G4double G4VDecayChannel::GetDaughterMass (G4int anIndex) const inline
Definition at line 241 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 241 of file G4VDecayChannel.hh
References G4cout, G4endl, G4MT_daughters_mass, numberOfDaughters, and verboseLevel.
const G4String & G4VDecayChannel::GetDaughterName (G4int anIndex) const inline
Definition at line 227 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 227 of file G4VDecayChannel.hh
References daughters_name, G4cout, G4endl, GetNoName(), numberOfDaughters, and verboseLevel.
Referenced by G4KineticTrack::Decay(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4TritonDecay::DumpNuclearInfo(), G4AlphaDecay::DumpNuclearInfo(), G4ECDecay::DumpNuclearInfo(), G4ProtonDecay::DumpNuclearInfo(), G4NeutronDecay::DumpNuclearInfo(), G4BetaPlusDecay::DumpNuclearInfo(), G4BetaMinusDecay::DumpNuclearInfo(), and G4ITDecay::DumpNuclearInfo().
const G4String & G4VDecayChannel::GetKinematicsName () const inline
Definition at line 290 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 290 of file G4VDecayChannel.hh
References kinematics_name.
Referenced by G4TextPPReporter::GeneratePropertyTable(), and G4HtmlPPReporter::GeneratePropertyTable().
const G4String & G4VDecayChannel::GetNoName () const private
Definition at line 561 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 561 of file G4VDecayChannel.cc
References noName.
Referenced by GetDaughterName().
G4int G4VDecayChannel::GetNumberOfDaughters () const inline
Definition at line 284 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 284 of file G4VDecayChannel.hh
References numberOfDaughters.
Referenced by G4KineticTrack::Decay(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4KineticTrack::G4KineticTrack(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4SampleResonance::GetMinimumMass(), and G4TextPPRetriever::ModifyPropertyTable().
G4ParticleDefinition * G4VDecayChannel::GetParent () inline
Definition at line 255 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 255 of file G4VDecayChannel.hh
References CheckAndFillParent(), and G4MT_parent.
Referenced by G4DecayTable::Insert().
G4double G4VDecayChannel::GetParentMass () const inline
Definition at line 270 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 270 of file G4VDecayChannel.hh
References G4MT_parent_mass.
const G4String & G4VDecayChannel::GetParentName () const inline
Definition at line 264 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 264 of file G4VDecayChannel.hh
References parent_name.
Referenced by G4KineticTrack::Decay(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4TritonDecay::DumpNuclearInfo(), G4AlphaDecay::DumpNuclearInfo(), G4ECDecay::DumpNuclearInfo(), G4ProtonDecay::DumpNuclearInfo(), G4SFDecay::DumpNuclearInfo(), G4NeutronDecay::DumpNuclearInfo(), G4BetaPlusDecay::DumpNuclearInfo(), G4BetaMinusDecay::DumpNuclearInfo(), and G4ITDecay::DumpNuclearInfo().
const G4ThreeVector & G4VDecayChannel::GetPolarization () const inline
Definition at line 314 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 314 of file G4VDecayChannel.hh
References parent_polarization.
G4double G4VDecayChannel::GetRangeMass () const inline
Definition at line 302 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 302 of file G4VDecayChannel.hh
References rangeMass.
G4int G4VDecayChannel::GetVerboseLevel () const inline
Definition at line 299 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 299 of file G4VDecayChannel.hh
References verboseLevel.
Referenced by G4KL3DecayChannel::DalitzDensity(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4PhaseSpaceDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4GeneralPhaseSpaceDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), FillDaughters(), G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay(), G4KL3DecayChannel::G4KL3DecayChannel(), G4MuonDecayChannel::G4MuonDecayChannel(), G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin(), G4NeutronBetaDecayChannel::G4NeutronBetaDecayChannel(), G4PionRadiativeDecayChannel::G4PionRadiativeDecayChannel(), G4TauLeptonicDecayChannel::G4TauLeptonicDecayChannel(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4GeneralPhaseSpaceDecay::OneBodyDecayIt(), G4KL3DecayChannel::PhaseSpace(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and G4GeneralPhaseSpaceDecay::TwoBodyDecayIt().
G4bool G4VDecayChannel::IsOKWithParentMass (G4double parentMass) virtual
Reimplemented in G4PhaseSpaceDecayChannel.
Definition at line 585 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 585 of file G4VDecayChannel.cc
References CheckAndFillDaughters(), CheckAndFillParent(), G4MT_daughters_mass, G4MT_daughters_width, numberOfDaughters, and rangeMass.
Referenced by G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), and G4PhaseSpaceDecayChannel::IsOKWithParentMass().
G4bool G4VDecayChannel::operator!= (const G4VDecayChannel & right) const inline
Definition at line 76 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VDecayChannel.hh
G4bool G4VDecayChannel::operator< (const G4VDecayChannel & right) const inline
Definition at line 205 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 205 of file G4VDecayChannel.hh
References rbranch.
G4VDecayChannel & G4VDecayChannel::operator= (const G4VDecayChannel & right) protected
Definition at line 172 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 172 of file G4VDecayChannel.cc
References ClearDaughtersName(), daughters_name, daughtersMutex, G4MT_daughters, G4MT_daughters_mass, G4MT_daughters_width, G4MT_parent, G4MT_parent_mass, G4MUTEXINIT, G4ParticleTable::GetParticleTable(), kinematics_name, numberOfDaughters, parent_name, parent_polarization, parentMutex, particletable, rangeMass, rbranch, and verboseLevel.
G4bool G4VDecayChannel::operator== (const G4VDecayChannel & right) const inline
Definition at line 75 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VDecayChannel.hh
void G4VDecayChannel::SetBR (G4double value)
Definition at line 600 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 600 of file G4VDecayChannel.cc
References rbranch.
Referenced by G4TauMinus::Definition(), G4TauPlus::Definition(), FillDaughters(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4DalitzDecayChannel::G4DalitzDecayChannel(), G4ECDecay::G4ECDecay(), G4ITDecay::G4ITDecay(), G4MuonDecayChannel::G4MuonDecayChannel(), G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin(), G4NeutronBetaDecayChannel::G4NeutronBetaDecayChannel(), G4NeutronDecay::G4NeutronDecay(), G4PionRadiativeDecayChannel::G4PionRadiativeDecayChannel(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TauLeptonicDecayChannel::G4TauLeptonicDecayChannel(), G4TritonDecay::G4TritonDecay(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4TextPPRetriever::ModifyPropertyTable(), and G4DecayTableMessenger::SetNewValue().
void G4VDecayChannel::SetDaughter (G4int anIndex, const G4ParticleDefinition * particle_type)
Definition at line 324 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 324 of file G4VDecayChannel.cc
References G4ParticleDefinition::GetParticleName().
Referenced by G4TauMinus::Definition(), G4TauPlus::Definition(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4DalitzDecayChannel::G4DalitzDecayChannel(), G4ECDecay::G4ECDecay(), G4ITDecay::G4ITDecay(), G4MuonDecayChannel::G4MuonDecayChannel(), G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin(), G4NeutronBetaDecayChannel::G4NeutronBetaDecayChannel(), G4NeutronDecay::G4NeutronDecay(), G4PionRadiativeDecayChannel::G4PionRadiativeDecayChannel(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TauLeptonicDecayChannel::G4TauLeptonicDecayChannel(), and G4TritonDecay::G4TritonDecay().
void G4VDecayChannel::SetDaughter (G4int anIndex, const G4String & particle_name)
Definition at line 268 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 268 of file G4VDecayChannel.cc
References daughters_name, FatalException, G4cout, G4endl, G4Exception(), G4MT_daughters, numberOfDaughters, and verboseLevel.
void G4VDecayChannel::SetNumberOfDaughters (G4int value)
Definition at line 256 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 256 of file G4VDecayChannel.cc
References ClearDaughtersName(), daughters_name, and numberOfDaughters.
Referenced by G4TauMinus::Definition(), G4TauPlus::Definition(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4DalitzDecayChannel::G4DalitzDecayChannel(), G4ECDecay::G4ECDecay(), G4ITDecay::G4ITDecay(), G4MuonDecayChannel::G4MuonDecayChannel(), G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin(), G4NeutronBetaDecayChannel::G4NeutronBetaDecayChannel(), G4NeutronDecay::G4NeutronDecay(), G4PionRadiativeDecayChannel::G4PionRadiativeDecayChannel(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TauLeptonicDecayChannel::G4TauLeptonicDecayChannel(), and G4TritonDecay::G4TritonDecay().
void G4VDecayChannel::SetParent (const G4ParticleDefinition * particle_type)
Definition at line 484 of file G4VDecayChannel.cc.
View newest version in sPHENIX GitHub at line 484 of file G4VDecayChannel.cc
References G4ParticleDefinition::GetParticleName().
Referenced by G4TauMinus::Definition(), G4TauPlus::Definition(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4DalitzDecayChannel::G4DalitzDecayChannel(), G4ECDecay::G4ECDecay(), G4ITDecay::G4ITDecay(), G4MuonDecayChannel::G4MuonDecayChannel(), G4MuonRadiativeDecayChannelWithSpin::G4MuonRadiativeDecayChannelWithSpin(), G4NeutronBetaDecayChannel::G4NeutronBetaDecayChannel(), G4NeutronDecay::G4NeutronDecay(), G4PionRadiativeDecayChannel::G4PionRadiativeDecayChannel(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TauLeptonicDecayChannel::G4TauLeptonicDecayChannel(), and G4TritonDecay::G4TritonDecay().
void G4VDecayChannel::SetParent (const G4String & particle_name) inline
Definition at line 276 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 276 of file G4VDecayChannel.hh
References G4MT_parent, and parent_name.
void G4VDecayChannel::SetPolarization (const G4ThreeVector & polar) inline
Definition at line 308 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 308 of file G4VDecayChannel.hh
References parent_polarization.
Referenced by G4DecayWithSpin::AtRestDoIt(), and G4DecayWithSpin::PostStepDoIt().
void G4VDecayChannel::SetRangeMass (G4double val) inline
Definition at line 305 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 305 of file G4VDecayChannel.hh
References rangeMass.
void G4VDecayChannel::SetVerboseLevel (G4int value) inline
Definition at line 296 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 296 of file G4VDecayChannel.hh
References verboseLevel.
Referenced by G4Decay::DecayIt(), and G4MuonicAtomDecay::DecayIt().
Member Data Documentation
G4String** G4VDecayChannel::daughters_name protected
Definition at line 172 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4VDecayChannel.hh
Referenced by ClearDaughtersName(), G4KL3DecayChannel::DecayIt(), DumpInfo(), FillDaughters(), G4VDecayChannel(), GetDaughterName(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), SetDaughter(), and SetNumberOfDaughters().
G4Mutex G4VDecayChannel::daughtersMutex protected
Definition at line 196 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 196 of file G4VDecayChannel.hh
Referenced by CheckAndFillDaughters(), ClearDaughtersName(), FillDaughters(), G4VDecayChannel(), operator=(), and ~G4VDecayChannel().
G4ParticleDefinition** G4VDecayChannel::G4MT_daughters protected
Definition at line 192 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 192 of file G4VDecayChannel.hh
Referenced by CheckAndFillDaughters(), ClearDaughtersName(), G4AlphaDecay::DecayIt(), G4TritonDecay::DecayIt(), G4ECDecay::DecayIt(), G4NeutronDecay::DecayIt(), G4ProtonDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), FillDaughters(), G4VDecayChannel(), GetAngularMomentum(), GetDaughter(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4GeneralPhaseSpaceDecay::OneBodyDecayIt(), operator=(), SetDaughter(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and G4GeneralPhaseSpaceDecay::TwoBodyDecayIt().
G4double* G4VDecayChannel::G4MT_daughters_mass protected
Definition at line 194 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 194 of file G4VDecayChannel.hh
Referenced by ClearDaughtersName(), FillDaughters(), G4VDecayChannel(), GetDaughterMass(), IsOKWithParentMass(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), operator=(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and ~G4VDecayChannel().
G4double* G4VDecayChannel::G4MT_daughters_width protected
Definition at line 195 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 195 of file G4VDecayChannel.hh
Referenced by ClearDaughtersName(), FillDaughters(), G4VDecayChannel(), IsOKWithParentMass(), operator=(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and ~G4VDecayChannel().
G4ParticleDefinition* G4VDecayChannel::G4MT_parent protected
Definition at line 191 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 191 of file G4VDecayChannel.hh
Referenced by CheckAndFillParent(), G4AlphaDecay::DecayIt(), G4TritonDecay::DecayIt(), G4ECDecay::DecayIt(), G4NeutronDecay::DecayIt(), G4ProtonDecay::DecayIt(), G4SFDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4ITDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), FillDaughters(), FillParent(), G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay(), G4VDecayChannel(), GetAngularMomentum(), GetParent(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4GeneralPhaseSpaceDecay::OneBodyDecayIt(), operator=(), SetParent(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and G4GeneralPhaseSpaceDecay::TwoBodyDecayIt().
G4double G4VDecayChannel::G4MT_parent_mass protected
Definition at line 193 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 193 of file G4VDecayChannel.hh
Referenced by G4PhaseSpaceDecayChannel::DecayIt(), FillParent(), G4VDecayChannel(), GetParentMass(), and operator=().
G4String G4VDecayChannel::kinematics_name protected
Definition at line 164 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4VDecayChannel.hh
Referenced by DumpInfo(), G4VDecayChannel(), GetKinematicsName(), G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), and operator=().
const G4String G4VDecayChannel::noName = " " static protected
Definition at line 189 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 189 of file G4VDecayChannel.hh
Referenced by GetNoName().
G4int G4VDecayChannel::numberOfDaughters protected
Definition at line 168 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VDecayChannel.hh
Referenced by ClearDaughtersName(), G4PhaseSpaceDecayChannel::DecayIt(), G4GeneralPhaseSpaceDecay::DecayIt(), DumpInfo(), FillDaughters(), G4VDecayChannel(), GetAngularMomentum(), GetDaughter(), GetDaughterMass(), GetDaughterName(), GetNumberOfDaughters(), G4PhaseSpaceDecayChannel::IsOKWithParentMass(), IsOKWithParentMass(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), SetDaughter(), G4PhaseSpaceDecayChannel::SetDaughterMasses(), and SetNumberOfDaughters().
G4String* G4VDecayChannel::parent_name protected
Definition at line 170 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VDecayChannel.hh
Referenced by ClearDaughtersName(), G4PhaseSpaceDecayChannel::DecayIt(), G4GeneralPhaseSpaceDecay::DecayIt(), FillDaughters(), FillParent(), G4VDecayChannel(), GetParentName(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), SetParent(), and ~G4VDecayChannel().
G4ThreeVector G4VDecayChannel::parent_polarization protected
Definition at line 178 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 178 of file G4VDecayChannel.hh
Referenced by G4MuonDecayChannelWithSpin::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4VDecayChannel(), GetPolarization(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), and SetPolarization().
G4Mutex G4VDecayChannel::parentMutex protected
Definition at line 197 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 197 of file G4VDecayChannel.hh
Referenced by CheckAndFillParent(), FillParent(), G4VDecayChannel(), operator=(), and ~G4VDecayChannel().
G4ParticleTable* G4VDecayChannel::particletable protected
Definition at line 181 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4VDecayChannel.hh
Referenced by FillDaughters(), FillParent(), G4VDecayChannel(), and operator=().
G4double G4VDecayChannel::rangeMass protected
Definition at line 175 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 175 of file G4VDecayChannel.hh
Referenced by DynamicalMass(), FillDaughters(), G4VDecayChannel(), GetRangeMass(), IsOKWithParentMass(), operator=(), SetRangeMass(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), and G4PhaseSpaceDecayChannel::TwoBodyDecayIt().
G4double G4VDecayChannel::rbranch protected
Definition at line 166 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4VDecayChannel.hh
Referenced by DumpInfo(), G4VDecayChannel(), GetBR(), operator<(), G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), and SetBR().
G4int G4VDecayChannel::verboseLevel protected
Definition at line 184 of file G4VDecayChannel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4VDecayChannel.hh
Referenced by ClearDaughtersName(), FillDaughters(), FillParent(), G4VDecayChannel(), GetAngularMomentum(), GetDaughter(), GetDaughterMass(), GetDaughterName(), GetVerboseLevel(), G4KL3DecayChannel::operator=(), G4NeutronBetaDecayChannel::operator=(), G4MuonDecayChannel::operator=(), G4TauLeptonicDecayChannel::operator=(), G4DalitzDecayChannel::operator=(), G4MuonDecayChannelWithSpin::operator=(), G4PionRadiativeDecayChannel::operator=(), G4MuonRadiativeDecayChannelWithSpin::operator=(), operator=(), SetDaughter(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4VDecayChannel.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4VDecayChannel.cc