ECCE @ EIC Software: G4VDataSetAlgorithm Class Reference
G4VDataSetAlgorithm Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VDataSetAlgorithm.hh>
Public Member Functions
G4VDataSetAlgorithm ()
virtual ~G4VDataSetAlgorithm ()
virtual G4double Calculate (G4double point, G4int bin, const G4DataVector &energies, const G4DataVector &data) const =0
virtual G4double Calculate (G4double point, G4int bin, const G4DataVector &energies, const G4DataVector &data, const G4DataVector &log_energies, const G4DataVector &log_data) const =0
virtual G4VDataSetAlgorithm * Clone () const =0
Private Member Functions
G4VDataSetAlgorithm (const G4VDataSetAlgorithm &)
G4VDataSetAlgorithm & operator= (const G4VDataSetAlgorithm &right)
Detailed Description
Definition at line 50 of file G4VDataSetAlgorithm.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VDataSetAlgorithm.hh
Constructor & Destructor Documentation
G4VDataSetAlgorithm::G4VDataSetAlgorithm () inline
Definition at line 54 of file G4VDataSetAlgorithm.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VDataSetAlgorithm.hh
virtual G4VDataSetAlgorithm::~G4VDataSetAlgorithm () inline virtual
Definition at line 56 of file G4VDataSetAlgorithm.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VDataSetAlgorithm.hh
G4VDataSetAlgorithm::G4VDataSetAlgorithm (const G4VDataSetAlgorithm &) private
Member Function Documentation
virtual G4double G4VDataSetAlgorithm::Calculate (G4double point, G4int bin, const G4DataVector & energies, const G4DataVector & data) const pure virtual
Implemented in G4LogLogInterpolation, G4SemiLogInterpolation, G4LinInterpolation, G4LinLogInterpolation, G4LinLogLogInterpolation, and G4DNACPA100LogLogInterpolation.
Referenced by XrayFluoDataSet::FindValue(), G4EMDataSet::FindValue(), G4EMDataSet::IntegrationFunction(), and G4EMDataSet::RandomSelect().
virtual G4double G4VDataSetAlgorithm::Calculate (G4double point, G4int bin, const G4DataVector & energies, const G4DataVector & data, const G4DataVector & log_energies, const G4DataVector & log_data) const pure virtual
Implemented in G4LogLogInterpolation, G4SemiLogInterpolation, G4LinInterpolation, G4LinLogInterpolation, G4LinLogLogInterpolation, and G4DNACPA100LogLogInterpolation.
virtual G4VDataSetAlgorithm* G4VDataSetAlgorithm::Clone () const pure virtual
Implemented in G4LogLogInterpolation, G4SemiLogInterpolation, G4LinInterpolation, G4LinLogInterpolation, G4LinLogLogInterpolation, and G4DNACPA100LogLogInterpolation.
Referenced by G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4CompositeEMDataSet::LoadData(), G4ShellEMDataSet::LoadData(), G4VCrossSectionHandler::LoadData(), G4ShellEMDataSet::LoadNonLogData(), G4CompositeEMDataSet::LoadNonLogData(), G4VCrossSectionHandler::LoadNonLogData(), G4DopplerProfile::LoadProfile(), and G4VCrossSectionHandler::LoadShellData().
G4VDataSetAlgorithm& G4VDataSetAlgorithm::operator= (const G4VDataSetAlgorithm & right) private
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VDataSetAlgorithm.hh