ECCE @ EIC Software: G4INCL::NuclearDensityFactory Namespace Reference
G4INCL::NuclearDensityFactory Namespace Reference
Functions
InterpolationTable * createRPCorrelationTable (const ParticleType t, const G4int A, const G4int Z)
InterpolationTable * createRCDFTable (const ParticleType t, const G4int A, const G4int Z)
InterpolationTable * createPCDFTable (const ParticleType t, const G4int A, const G4int Z)
NuclearDensity const * createDensity (const G4int A, const G4int Z, const G4int S)
void addRPCorrelationToCache (const G4int A, const G4int Z, const ParticleType t, InterpolationTable *const table)
void addDensityToCache (const G4int A, const G4int Z, NuclearDensity *const density)
void clearCache ()
Function Documentation
void G4INCL::NuclearDensityFactory::addDensityToCache (const G4int A, const G4int Z, NuclearDensity *const density)
Definition at line 221 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 221 of file G4INCLNuclearDensityFactory.cc
References A().
void G4INCL::NuclearDensityFactory::addRPCorrelationToCache (const G4int A, const G4int Z, const ParticleType t, InterpolationTable *const table)
Definition at line 207 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 207 of file G4INCLNuclearDensityFactory.cc
References A(), and G4INCL::Proton.
void G4INCL::NuclearDensityFactory::clearCache ()
Definition at line 233 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 233 of file G4INCLNuclearDensityFactory.cc
Referenced by G4INCL::INCL::~INCL().
NuclearDensity const * G4INCL::NuclearDensityFactory::createDensity (const G4int A, const G4int Z, const G4int S)
Definition at line 59 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 59 of file G4INCLNuclearDensityFactory.cc
References A(), createRPCorrelationTable(), G4INCL::Lambda, G4INCL::Neutron, and G4INCL::Proton.
Referenced by G4INCL::Nucleus::Nucleus().
InterpolationTable * G4INCL::NuclearDensityFactory::createPCDFTable (const ParticleType t, const G4int A, const G4int Z)
Definition at line 171 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 171 of file G4INCLNuclearDensityFactory.cc
References A(), G4INCL::ParticleTable::getFermiMomentum, G4INCL::ParticleTable::getMomentumRMS(), INCL_DEBUG, INCL_ERROR, G4INCL::IFunction1D::inverseCDFTable(), G4INCL::Math::oneOverSqrtThree, G4INCL::InterpolationTable::print(), and G4INCL::Proton.
Referenced by G4INCL::ParticleSampler::sampleParticlesIntoList().
InterpolationTable * G4INCL::NuclearDensityFactory::createRCDFTable (const ParticleType t, const G4int A, const G4int Z)
Definition at line 126 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 126 of file G4INCLNuclearDensityFactory.cc
References A(), G4INCL::ParticleTable::getMaximumNuclearRadius(), G4INCL::ParticleTable::getRadiusParameter(), G4INCL::ParticleTable::getSurfaceDiffuseness(), INCL_DEBUG, INCL_ERROR, G4INCL::IFunction1D::inverseCDFTable(), G4INCL::Math::oneOverSqrtThree, G4INCL::InterpolationTable::print(), G4INCL::Proton, and radius.
Referenced by G4INCL::ParticleSampler::sampleParticlesIntoList().
InterpolationTable * G4INCL::NuclearDensityFactory::createRPCorrelationTable (const ParticleType t, const G4int A, const G4int Z)
Definition at line 79 of file G4INCLNuclearDensityFactory.cc.
View newest version in sPHENIX GitHub at line 79 of file G4INCLNuclearDensityFactory.cc
References A(), G4INCL::ParticleTable::getMaximumNuclearRadius(), G4INCL::ParticleTable::getRadiusParameter(), G4INCL::ParticleTable::getSurfaceDiffuseness(), INCL_DEBUG, INCL_ERROR, G4INCL::IFunction1D::inverseCDFTable(), G4INCL::Math::oneOverSqrtThree, G4INCL::Math::pow13(), G4INCL::InterpolationTable::print(), G4INCL::Proton, and radius.
Referenced by createDensity().