ECCE @ EIC Software: G4VectorCache< VALTYPE > Class Template Reference
G4VectorCache< VALTYPE > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4Cache.hh>
Public Types
typedef VALTYPE value_type
typedef std::vector< value_type > vector_type
typedef vector_type::size_type size_type
typedef vector_type::iterator iterator
typedef vector_type::const_iterator const_iterator
Public Types inherited from G4Cache< std::vector< VALTYPE > >
typedef std::vector< VALTYPE > value_type
Public Member Functions
G4VectorCache ()
G4VectorCache (G4int nElems)
G4VectorCache (G4int nElems, value_type *vals)
virtual ~G4VectorCache ()
void Push_back (const value_type &val)
value_type Pop_back ()
value_type & operator[] (const G4int &idx)
iterator Begin ()
iterator End ()
void Clear ()
size_type Size ()
Public Member Functions inherited from G4Cache< std::vector< VALTYPE > >
G4Cache ()
G4Cache (const value_type &v)
G4Cache (const G4Cache &rhs)
virtual ~G4Cache ()
value_type & Get () const
void Put (const value_type &val) const
value_type Pop ()
G4Cache & operator= (const G4Cache &rhs)
Additional Inherited Members
Protected Member Functions inherited from G4Cache< std::vector< VALTYPE > >
const G4int & GetId () const
Detailed Description
template<class VALTYPE>
class G4VectorCache< VALTYPE >
Definition at line 142 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 142 of file G4Cache.hh
Member Typedef Documentation
template<class VALTYPE> typedef vector_type::const_iterator G4VectorCache< VALTYPE >::const_iterator
Definition at line 152 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 152 of file G4Cache.hh
template<class VALTYPE> typedef vector_type::iterator G4VectorCache< VALTYPE >::iterator
Definition at line 151 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 151 of file G4Cache.hh
template<class VALTYPE> typedef vector_type::size_type G4VectorCache< VALTYPE >::size_type
Definition at line 150 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Cache.hh
template<class VALTYPE> typedef VALTYPE G4VectorCache< VALTYPE >::value_type
Definition at line 148 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 148 of file G4Cache.hh
template<class VALTYPE> typedef std::vector<value_type> G4VectorCache< VALTYPE >::vector_type
Definition at line 149 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 149 of file G4Cache.hh
Constructor & Destructor Documentation
template<class V > G4VectorCache< V >::G4VectorCache ()
Definition at line 347 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 347 of file G4Cache.hh
template<class V > G4VectorCache< V >::G4VectorCache (G4int nElems)
Definition at line 364 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 364 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class VALTYPE> G4VectorCache< VALTYPE >::G4VectorCache (G4int nElems, value_type * vals)
template<class V > G4VectorCache< V >::~G4VectorCache () virtual
Definition at line 351 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 351 of file G4Cache.hh
Member Function Documentation
template<class V > G4VectorCache< V >::iterator G4VectorCache< V >::Begin () inline
Definition at line 402 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 402 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class V > void G4VectorCache< V >::Clear () inline
Definition at line 414 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 414 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class V > G4VectorCache< V >::iterator G4VectorCache< V >::End () inline
Definition at line 408 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 408 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class V > V & G4VectorCache< V >::operator[] (const G4int & idx) inline
Definition at line 395 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 395 of file G4Cache.hh
References G4Cache< VALTYPE >::Get(), and incremental_prev_tag::idx.
template<class V > V G4VectorCache< V >::Pop_back () inline
Definition at line 386 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 386 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class VALTYPE> void G4VectorCache< V >::Push_back (const value_type & val) inline
Definition at line 380 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 380 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
Referenced by G4VBiasingOperator::G4VBiasingOperator(), and G4BiasingOperationManager::Register().
template<class VALTYPE> size_type G4VectorCache< VALTYPE >::Size () inline
Definition at line 174 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 174 of file G4Cache.hh
Referenced by G4BiasingOperationManager::GetBiasingOperation(), G4BiasingOperatorStateNotifier::Notify(), and G4BiasingOperationManager::Register().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4Cache.hh