ECCE @ EIC Software: LXeHistoManager Class Reference
LXeHistoManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeHistoManager.hh>
Public Member Functions
LXeHistoManager ()
~LXeHistoManager ()
Private Member Functions
void Book ()
Private Attributes
G4String fFileName
Detailed Description
Definition at line 44 of file LXeHistoManager.hh.
View newest version in sPHENIX GitHub at line 44 of file LXeHistoManager.hh
Constructor & Destructor Documentation
LXeHistoManager::LXeHistoManager ()
Definition at line 41 of file LXeHistoManager.cc.
View newest version in sPHENIX GitHub at line 41 of file LXeHistoManager.cc
References Book().
LXeHistoManager::~LXeHistoManager ()
Definition at line 49 of file LXeHistoManager.cc.
View newest version in sPHENIX GitHub at line 49 of file LXeHistoManager.cc
References G4ToolsAnalysisManager::Instance().
Member Function Documentation
void LXeHistoManager::Book () private
Definition at line 56 of file LXeHistoManager.cc.
View newest version in sPHENIX GitHub at line 56 of file LXeHistoManager.cc
References fFileName, G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::SetActivation(), G4VAnalysisManager::SetFileName(), G4VAnalysisManager::SetH1Activation(), and G4VAnalysisManager::SetVerboseLevel().
Referenced by LXeHistoManager().
Member Data Documentation
G4String LXeHistoManager::fFileName private
Definition at line 52 of file LXeHistoManager.hh.
View newest version in sPHENIX GitHub at line 52 of file LXeHistoManager.hh
Referenced by Book().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeHistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeHistoManager.cc