ECCE @ EIC Software: G4ecpssrFormFactorMixsModel Class Reference
G4ecpssrFormFactorMixsModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ecpssrFormFactorMixsModel.hh>
Public Member Functions
G4ecpssrFormFactorMixsModel ()
virtual ~G4ecpssrFormFactorMixsModel ()
G4double CalculateM1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateM2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateM3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateM4CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateM5CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
Public Member Functions inherited from G4VecpssrMiModel
G4VecpssrMiModel ()
virtual ~G4VecpssrMiModel ()
Private Member Functions
G4double CalculateMiCrossSection (G4int zTarget, G4double massIncident, G4double energyIncident, G4int mShellId)
G4ecpssrFormFactorMixsModel (const G4ecpssrFormFactorMixsModel &)
G4ecpssrFormFactorMixsModel & operator= (const G4ecpssrFormFactorMixsModel &right)
Private Attributes
G4VDataSetAlgorithm * interpolation
std::vector< std::map< G4int,
G4VEMDataSet * > > protonMiXsVector
std::vector< std::map< G4int,
G4VEMDataSet * > > alphaMiXsVector
std::map< G4int, G4VEMDataSet * > protonM1DataSetMap
std::map< G4int, G4VEMDataSet * > protonM2DataSetMap
std::map< G4int, G4VEMDataSet * > protonM3DataSetMap
std::map< G4int, G4VEMDataSet * > protonM4DataSetMap
std::map< G4int, G4VEMDataSet * > protonM5DataSetMap
std::map< G4int, G4VEMDataSet * > alphaM1DataSetMap
std::map< G4int, G4VEMDataSet * > alphaM2DataSetMap
std::map< G4int, G4VEMDataSet * > alphaM3DataSetMap
std::map< G4int, G4VEMDataSet * > alphaM4DataSetMap
std::map< G4int, G4VEMDataSet * > alphaM5DataSetMap
Detailed Description
Definition at line 49 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ecpssrFormFactorMixsModel.hh
Constructor & Destructor Documentation
G4ecpssrFormFactorMixsModel::G4ecpssrFormFactorMixsModel ()
Definition at line 53 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ecpssrFormFactorMixsModel.cc
References alphaM1DataSetMap, alphaM2DataSetMap, alphaM3DataSetMap, alphaM4DataSetMap, alphaM5DataSetMap, alphaMiXsVector, interpolation, protonM1DataSetMap, protonM2DataSetMap, protonM3DataSetMap, protonM4DataSetMap, protonM5DataSetMap, and protonMiXsVector.
G4ecpssrFormFactorMixsModel::~G4ecpssrFormFactorMixsModel () virtual
Definition at line 113 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 113 of file G4ecpssrFormFactorMixsModel.cc
References alphaM1DataSetMap, alphaM2DataSetMap, alphaM3DataSetMap, alphaM4DataSetMap, alphaM5DataSetMap, interpolation, protonM1DataSetMap, protonM2DataSetMap, protonM3DataSetMap, protonM4DataSetMap, and protonM5DataSetMap.
G4ecpssrFormFactorMixsModel::G4ecpssrFormFactorMixsModel (const G4ecpssrFormFactorMixsModel &) private
Member Function Documentation
G4double G4ecpssrFormFactorMixsModel::CalculateM1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrMiModel.
Definition at line 167 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 167 of file G4ecpssrFormFactorMixsModel.cc
References CalculateMiCrossSection().
G4double G4ecpssrFormFactorMixsModel::CalculateM2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrMiModel.
Definition at line 177 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 177 of file G4ecpssrFormFactorMixsModel.cc
References CalculateMiCrossSection().
G4double G4ecpssrFormFactorMixsModel::CalculateM3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrMiModel.
Definition at line 215 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 215 of file G4ecpssrFormFactorMixsModel.cc
References CalculateMiCrossSection().
G4double G4ecpssrFormFactorMixsModel::CalculateM4CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrMiModel.
Definition at line 252 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 252 of file G4ecpssrFormFactorMixsModel.cc
References CalculateMiCrossSection().
G4double G4ecpssrFormFactorMixsModel::CalculateM5CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrMiModel.
Definition at line 287 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 287 of file G4ecpssrFormFactorMixsModel.cc
References CalculateMiCrossSection().
G4double G4ecpssrFormFactorMixsModel::CalculateMiCrossSection (G4int zTarget, G4double massIncident, G4double energyIncident, G4int mShellId) private
Definition at line 135 of file G4ecpssrFormFactorMixsModel.cc.
View newest version in sPHENIX GitHub at line 135 of file G4ecpssrFormFactorMixsModel.cc
References G4Alpha::Alpha(), alphaMiXsVector, G4ParticleDefinition::GetPDGMass(), MeV, G4Proton::Proton(), and protonMiXsVector.
Referenced by CalculateM1CrossSection(), CalculateM2CrossSection(), CalculateM3CrossSection(), CalculateM4CrossSection(), and CalculateM5CrossSection().
G4ecpssrFormFactorMixsModel& G4ecpssrFormFactorMixsModel::operator= (const G4ecpssrFormFactorMixsModel & right) private
Member Data Documentation
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::alphaM1DataSetMap private
Definition at line 81 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::alphaM2DataSetMap private
Definition at line 82 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::alphaM3DataSetMap private
Definition at line 83 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::alphaM4DataSetMap private
Definition at line 84 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::alphaM5DataSetMap private
Definition at line 85 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::vector< std::map<G4int,G4VEMDataSet*> > G4ecpssrFormFactorMixsModel::alphaMiXsVector private
Definition at line 73 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ecpssrFormFactorMixsModel.hh
Referenced by CalculateMiCrossSection(), and G4ecpssrFormFactorMixsModel().
G4VDataSetAlgorithm* G4ecpssrFormFactorMixsModel::interpolation private
Definition at line 70 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::protonM1DataSetMap private
Definition at line 75 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::protonM2DataSetMap private
Definition at line 76 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::protonM3DataSetMap private
Definition at line 77 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::protonM4DataSetMap private
Definition at line 78 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::map< G4int , G4VEMDataSet* > G4ecpssrFormFactorMixsModel::protonM5DataSetMap private
Definition at line 79 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ecpssrFormFactorMixsModel.hh
Referenced by G4ecpssrFormFactorMixsModel(), and ~G4ecpssrFormFactorMixsModel().
std::vector< std::map<G4int,G4VEMDataSet*> > G4ecpssrFormFactorMixsModel::protonMiXsVector private
Definition at line 72 of file G4ecpssrFormFactorMixsModel.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ecpssrFormFactorMixsModel.hh
Referenced by CalculateMiCrossSection(), and G4ecpssrFormFactorMixsModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ecpssrFormFactorMixsModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4ecpssrFormFactorMixsModel.cc