ECCE @ EIC Software: G4VLongitudinalStringDecay Class Reference
G4VLongitudinalStringDecay Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4VLongitudinalStringDecay.hh>
Public Member Functions
G4VLongitudinalStringDecay ()
virtual ~G4VLongitudinalStringDecay ()
virtual G4KineticTrackVector * FragmentString (const G4ExcitedString &theString)=0
void AddNewParticles ()
void EraseNewParticles ()
void SetMinMasses ()
void SetMinimalStringMass (const G4FragmentingString *const string)
void SetMinimalStringMass2 (const G4double aValue)
G4int SampleQuarkFlavor (void)
G4ThreeVector SampleQuarkPt (G4double ptMax=-1.)
void SetSigmaTransverseMomentum (G4double aQT)
void SetStrangenessSuppression (G4double aValue)
void SetDiquarkSuppression (G4double aValue)
void SetDiquarkBreakProbability (G4double aValue)
void SetVectorMesonProbability (G4double aValue)
void SetSpinThreeHalfBarionProbability (G4double aValue)
void SetScalarMesonMixings (std::vector< G4double > aVector)
void SetVectorMesonMixings (std::vector< G4double > aVector)
void SetStringTensionParameter (G4double aValue)
void SetProbCCbar (G4double aValue)
void SetProbEta_c (G4double aValue)
void SetProbBBbar (G4double aValue)
void SetProbEta_b (G4double aValue)
Public Attributes
G4double Mass_of_light_quark
G4double Mass_of_s_quark
G4double Mass_of_c_quark
G4double Mass_of_b_quark
G4double Mass_of_string_junction
G4double minMassQQbarStr [5][5]
G4double minMassQDiQStr [5][5][5]
G4double MinimalStringMass
G4double MinimalStringMass2
G4int Qcharge [5]
G4int Meson [5][5][7]
G4double MesonWeight [5][5][7]
G4int Baryon [5][5][5][4]
G4double BaryonWeight [5][5][5][4]
G4double Prob_QQbar [5]
G4int DecayQuark
G4int NewQuark
G4ParticleDefinition * FS_LeftHadron [350]
G4ParticleDefinition * FS_RightHadron [350]
G4double FS_Weight [350]
G4int NumberOf_FS
Protected Types
typedef std::pair
< G4ParticleDefinition
*, G4ParticleDefinition * > pDefPair
typedef G4ParticleDefinition
*(G4HadronBuilder::* Pcreate)(G4ParticleDefinition *, G4ParticleDefinition *)
Protected Member Functions
virtual void SetMassCut (G4double aValue)
G4double GetMassCut ()
G4KineticTrackVector * ProduceOneHadron (const G4ExcitedString *const theString)
G4double PossibleHadronMass (const G4FragmentingString *const string, Pcreate build=0, pDefPair *pdefs=0)
G4ParticleDefinition * FindParticle (G4int Encoding)
virtual G4bool StopFragmenting (const G4FragmentingString *const string)=0
virtual G4bool IsItFragmentable (const G4FragmentingString *const string)=0
virtual G4bool SplitLast (G4FragmentingString *string, G4KineticTrackVector *LeftVector, G4KineticTrackVector *RightVector)=0
virtual void Sample4Momentum (G4LorentzVector *Mom, G4double Mass, G4LorentzVector *AntiMom, G4double AntiMass, G4double InitialMass)=0
G4ExcitedString * CopyExcited (const G4ExcitedString &string)
virtual G4KineticTrack * Splitup (G4FragmentingString *string, G4FragmentingString *&newString)=0
virtual G4ParticleDefinition * QuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
virtual G4ParticleDefinition * DiQuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)=0
pDefPair CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks=true)
virtual G4LorentzVector * SplitEandP (G4ParticleDefinition *pHadron, G4FragmentingString *string, G4FragmentingString *newString)=0
virtual G4double GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition *pHadron, G4double Px, G4double Py)=0
void CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector *)
void ConstructParticle ()
G4ParticleDefinition * CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin)
G4double GetDiquarkSuppress ()
G4double GetDiquarkBreakProb ()
G4double GetStrangeSuppress ()
G4int GetClusterLoopInterrupt ()
G4double GetProbCCbar ()
G4double GetProbEta_c ()
G4double GetProbBBbar ()
G4double GetProbEta_b ()
G4double GetStringTensionParameter ()
Protected Attributes
G4double MassCut
G4double SigmaQT
G4double DiquarkSuppress
G4double DiquarkBreakProb
G4double StrangeSuppress
G4int StringLoopInterrupt
G4int ClusterLoopInterrupt
G4HadronBuilder * hadronizer
G4double pspin_meson
G4double pspin_barion
std::vector< G4double > vectorMesonMix
std::vector< G4double > scalarMesonMix
G4double ProbCCbar
G4double ProbEta_c
G4double ProbBBbar
G4double ProbEta_b
G4double ProbCB
G4double MaxMass
G4bool PastInitPhase
G4double Kappa
std::vector
< G4ParticleDefinition * > NewParticles
Private Member Functions
G4VLongitudinalStringDecay (const G4VLongitudinalStringDecay &right)
const G4VLongitudinalStringDecay & operator= (const G4VLongitudinalStringDecay &right)
G4bool operator== (const G4VLongitudinalStringDecay &right) const
G4bool operator!= (const G4VLongitudinalStringDecay &right) const
Detailed Description
Definition at line 44 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VLongitudinalStringDecay.hh
Member Typedef Documentation
typedef G4ParticleDefinition*(G4HadronBuilder::* G4VLongitudinalStringDecay::Pcreate)(G4ParticleDefinition *, G4ParticleDefinition *) protected
Definition at line 82 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VLongitudinalStringDecay.hh
typedef std::pair<G4ParticleDefinition*, G4ParticleDefinition*> G4VLongitudinalStringDecay::pDefPair protected
Definition at line 78 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VLongitudinalStringDecay.hh
Constructor & Destructor Documentation
G4VLongitudinalStringDecay::G4VLongitudinalStringDecay ()
Definition at line 64 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VLongitudinalStringDecay.cc
References ClusterLoopInterrupt, DiquarkBreakProb, DiquarkSuppress, fermi, GeV, hadronizer, Kappa, MassCut, MaxMass, MeV, PastInitPhase, ProbEta_b, ProbEta_c, pspin_barion, pspin_meson, scalarMesonMix, SetMinMasses(), SetProbBBbar(), SetProbCCbar(), SetProbEta_b(), SetProbEta_c(), SigmaQT, StrangeSuppress, StringLoopInterrupt, and vectorMesonMix.
G4VLongitudinalStringDecay::~G4VLongitudinalStringDecay () virtual
Definition at line 123 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 123 of file G4VLongitudinalStringDecay.cc
References hadronizer.
G4VLongitudinalStringDecay::G4VLongitudinalStringDecay (const G4VLongitudinalStringDecay & right) private
Member Function Documentation
void G4VLongitudinalStringDecay::AddNewParticles ()
void G4VLongitudinalStringDecay::CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector * Hadrons) protected
Definition at line 421 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 421 of file G4VLongitudinalStringDecay.cc
References c1, c2, source.hepunit::c_light, and GetStringTensionParameter().
Referenced by G4QGSMFragmentation::FragmentString().
void G4VLongitudinalStringDecay::ConstructParticle () protected
G4ExcitedString * G4VLongitudinalStringDecay::CopyExcited (const G4ExcitedString & string) protected
Definition at line 319 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 319 of file G4VLongitudinalStringDecay.cc
References G4ExcitedString::GetDirection(), G4ExcitedString::GetLeftParton(), and G4ExcitedString::GetRightParton().
Referenced by G4QGSMFragmentation::FragmentString().
G4ParticleDefinition* G4VLongitudinalStringDecay::CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin) protected
G4VLongitudinalStringDecay::pDefPair G4VLongitudinalStringDecay::CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks = true) protected
Definition at line 353 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 353 of file G4VLongitudinalStringDecay.cc
References DiquarkSuppress, FindParticle(), G4cout, G4endl, G4UniformRand, max, min, and SampleQuarkFlavor().
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), QuarkSplitup(), and G4QGSMFragmentation::SplitLast().
virtual G4ParticleDefinition* G4VLongitudinalStringDecay::DiQuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
void G4VLongitudinalStringDecay::EraseNewParticles ()
G4ParticleDefinition * G4VLongitudinalStringDecay::FindParticle (G4int Encoding) protected
Definition at line 273 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 273 of file G4VLongitudinalStringDecay.cc
References G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), and NewParticles.
Referenced by CreatePartonPair(), G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), PossibleHadronMass(), and SetMinMasses().
virtual G4KineticTrackVector* G4VLongitudinalStringDecay::FragmentString (const G4ExcitedString & theString) pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Referenced by G4ExcitedStringDecay::FragmentString().
G4int G4VLongitudinalStringDecay::GetClusterLoopInterrupt () inline protected
Definition at line 171 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 171 of file G4VLongitudinalStringDecay.hh
References ClusterLoopInterrupt.
G4double G4VLongitudinalStringDecay::GetDiquarkBreakProb () inline protected
Definition at line 169 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 169 of file G4VLongitudinalStringDecay.hh
References DiquarkBreakProb.
G4double G4VLongitudinalStringDecay::GetDiquarkSuppress () inline protected
Definition at line 168 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VLongitudinalStringDecay.hh
References DiquarkSuppress.
Referenced by G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
virtual G4double G4VLongitudinalStringDecay::GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition * pHadron, G4double Px, G4double Py) protected pure virtual
Implemented in G4QGSMFragmentation, and G4LundStringFragmentation.
G4double G4VLongitudinalStringDecay::GetMassCut () protected
Definition at line 152 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 152 of file G4VLongitudinalStringDecay.cc
References MassCut.
Referenced by G4LundStringFragmentation::FragmentString().
G4double G4VLongitudinalStringDecay::GetProbBBbar () inline protected
Definition at line 175 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 175 of file G4VLongitudinalStringDecay.hh
References ProbBBbar.
G4double G4VLongitudinalStringDecay::GetProbCCbar () inline protected
Definition at line 173 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 173 of file G4VLongitudinalStringDecay.hh
References ProbCCbar.
G4double G4VLongitudinalStringDecay::GetProbEta_b () inline protected
Definition at line 176 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 176 of file G4VLongitudinalStringDecay.hh
References ProbEta_b.
G4double G4VLongitudinalStringDecay::GetProbEta_c () inline protected
Definition at line 174 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 174 of file G4VLongitudinalStringDecay.hh
References ProbEta_c.
G4double G4VLongitudinalStringDecay::GetStrangeSuppress () inline protected
Definition at line 170 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VLongitudinalStringDecay.hh
References StrangeSuppress.
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), and G4LundStringFragmentation::Splitup().
G4double G4VLongitudinalStringDecay::GetStringTensionParameter () inline protected
Definition at line 178 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 178 of file G4VLongitudinalStringDecay.hh
Referenced by CalculateHadronTimePosition().
virtual G4bool G4VLongitudinalStringDecay::IsItFragmentable (const G4FragmentingString *const string) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
G4bool G4VLongitudinalStringDecay::operator!= (const G4VLongitudinalStringDecay & right) const private
Definition at line 142 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 142 of file G4VLongitudinalStringDecay.cc
const G4VLongitudinalStringDecay& G4VLongitudinalStringDecay::operator= (const G4VLongitudinalStringDecay & right) private
G4bool G4VLongitudinalStringDecay::operator== (const G4VLongitudinalStringDecay & right) const private
Definition at line 134 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 134 of file G4VLongitudinalStringDecay.cc
G4double G4VLongitudinalStringDecay::PossibleHadronMass (const G4FragmentingString *const string, Pcreate build = 0, pDefPair * pdefs = 0) protected
Definition at line 214 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 214 of file G4VLongitudinalStringDecay.cc
References FW::Geometry::build(), G4HadronBuilder::BuildLowSpin(), FindParticle(), G4cout, G4endl, G4UniformRand, G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4FragmentingString::GetRightParton(), hadronizer, G4FragmentingString::IsAFourQuarkString(), mass, and MaxMass.
Referenced by G4QGSMFragmentation::IsItFragmentable(), and ProduceOneHadron().
G4KineticTrackVector * G4VLongitudinalStringDecay::ProduceOneHadron (const G4ExcitedString *const theString) protected
Definition at line 158 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 158 of file G4VLongitudinalStringDecay.cc
References G4KineticTrackVector::Boost(), G4cout, G4endl, G4ExcitedString::GetPosition(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), G4FragmentingString::Mass(), MassCut, PossibleHadronMass(), Sample4Momentum(), SetMinimalStringMass(), and sqr().
Referenced by G4QGSMFragmentation::FragmentString(), and G4LundStringFragmentation::FragmentString().
G4ParticleDefinition * G4VLongitudinalStringDecay::QuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) protected virtual
Definition at line 328 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 328 of file G4VLongitudinalStringDecay.cc
References G4HadronBuilder::Build(), CreatePartonPair(), DecayQuark, G4cout, G4endl, G4ParticleDefinition::GetPDGEncoding(), hadronizer, and NewQuark.
Referenced by G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
virtual void G4VLongitudinalStringDecay::Sample4Momentum (G4LorentzVector * Mom, G4double Mass, G4LorentzVector * AntiMom, G4double AntiMass, G4double InitialMass) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Referenced by ProduceOneHadron().
G4int G4VLongitudinalStringDecay::SampleQuarkFlavor (void)
Definition at line 385 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 385 of file G4VLongitudinalStringDecay.cc
References G4cout, G4endl, G4UniformRand, int(), ProbBBbar, ProbCB, ProbCCbar, and StrangeSuppress.
Referenced by CreatePartonPair().
G4ThreeVector G4VLongitudinalStringDecay::SampleQuarkPt (G4double ptMax = -1.)
Definition at line 404 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 404 of file G4VLongitudinalStringDecay.cc
References G4Exp(), G4Log(), G4UniformRand, phi, pi, G4INCL::DeJongSpin::shoot(), SigmaQT, and sqr().
Referenced by G4LundStringFragmentation::Sample4Momentum(), and G4QGSMFragmentation::SplitEandP().
void G4VLongitudinalStringDecay::SetDiquarkBreakProbability (G4double aValue)
Definition at line 474 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 474 of file G4VLongitudinalStringDecay.cc
References DiquarkBreakProb, and PastInitPhase.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), and G4QGSMFragmentation::G4QGSMFragmentation().
void G4VLongitudinalStringDecay::SetDiquarkSuppression (G4double aValue)
Definition at line 467 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 467 of file G4VLongitudinalStringDecay.cc
References DiquarkSuppress.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), G4QGSMFragmentation::Splitup(), and G4LundStringFragmentation::Splitup().
void G4VLongitudinalStringDecay::SetMassCut (G4double aValue) protected virtual
Definition at line 151 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 151 of file G4VLongitudinalStringDecay.cc
References MassCut.
Referenced by G4LundStringFragmentation::FragmentString(), and G4LundStringFragmentation::G4LundStringFragmentation().
void G4VLongitudinalStringDecay::SetMinimalStringMass (const G4FragmentingString *const string)
Definition at line 938 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 938 of file G4VLongitudinalStringDecay.cc
References kdfinder::abs(), G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetPDGEncoding(), G4FragmentingString::GetRightParton(), MaxMass, min, MinimalStringMass, minMassQDiQStr, minMassQQbarStr, and SetMinimalStringMass2().
Referenced by G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4LundStringFragmentation::IsItFragmentable(), ProduceOneHadron(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::StopFragmenting(), and G4LundStringFragmentation::StopFragmenting().
void G4VLongitudinalStringDecay::SetMinimalStringMass2 (const G4double aValue)
Definition at line 1030 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 1030 of file G4VLongitudinalStringDecay.cc
References MinimalStringMass2.
Referenced by SetMinimalStringMass().
void G4VLongitudinalStringDecay::SetMinMasses ()
Definition at line 595 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 595 of file G4VLongitudinalStringDecay.cc
References Baryon, BaryonWeight, FindParticle(), G4ParticleTable::FindParticle(), FS_LeftHadron, FS_RightHadron, FS_Weight, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), k, Mass_of_b_quark, Mass_of_c_quark, Mass_of_light_quark, Mass_of_s_quark, Mass_of_string_junction, max, MaxMass, Meson, MesonWeight, MeV, min, MinimalStringMass, MinimalStringMass2, minMassQDiQStr, minMassQQbarStr, NumberOf_FS, Prob_QQbar, ProbEta_b, ProbEta_c, pspin_barion, pspin_meson, Qcharge, scalarMesonMix, and vectorMesonMix.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), and G4VLongitudinalStringDecay().
void G4VLongitudinalStringDecay::SetProbBBbar (G4double aValue)
Definition at line 573 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 573 of file G4VLongitudinalStringDecay.cc
References ProbBBbar, ProbCB, and ProbCCbar.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), and G4VLongitudinalStringDecay().
void G4VLongitudinalStringDecay::SetProbCCbar (G4double aValue)
Definition at line 558 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 558 of file G4VLongitudinalStringDecay.cc
References ProbBBbar, ProbCB, and ProbCCbar.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), and G4VLongitudinalStringDecay().
void G4VLongitudinalStringDecay::SetProbEta_b (G4double aValue)
Definition at line 581 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 581 of file G4VLongitudinalStringDecay.cc
References ProbEta_b.
Referenced by G4VLongitudinalStringDecay().
void G4VLongitudinalStringDecay::SetProbEta_c (G4double aValue)
Definition at line 566 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 566 of file G4VLongitudinalStringDecay.cc
References ProbEta_c.
Referenced by G4VLongitudinalStringDecay().
void G4VLongitudinalStringDecay::SetScalarMesonMixings (std::vector< G4double > aVector)
Definition at line 514 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 514 of file G4VLongitudinalStringDecay.cc
References hadronizer, PastInitPhase, ProbEta_b, ProbEta_c, pspin_barion, pspin_meson, scalarMesonMix, and vectorMesonMix.
void G4VLongitudinalStringDecay::SetSigmaTransverseMomentum (G4double aQT)
Definition at line 448 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 448 of file G4VLongitudinalStringDecay.cc
References PastInitPhase, and SigmaQT.
void G4VLongitudinalStringDecay::SetSpinThreeHalfBarionProbability (G4double aValue)
Definition at line 500 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 500 of file G4VLongitudinalStringDecay.cc
References hadronizer, PastInitPhase, ProbEta_b, ProbEta_c, pspin_barion, pspin_meson, scalarMesonMix, and vectorMesonMix.
void G4VLongitudinalStringDecay::SetStrangenessSuppression (G4double aValue)
Definition at line 460 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 460 of file G4VLongitudinalStringDecay.cc
References StrangeSuppress.
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::G4LundStringFragmentation(), G4QGSMFragmentation::G4QGSMFragmentation(), and G4LundStringFragmentation::Splitup().
void G4VLongitudinalStringDecay::SetStringTensionParameter (G4double aValue)
Definition at line 588 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 588 of file G4VLongitudinalStringDecay.cc
References fermi, GeV, and Kappa.
Referenced by G4LundStringFragmentation::G4LundStringFragmentation().
void G4VLongitudinalStringDecay::SetVectorMesonMixings (std::vector< G4double > aVector)
Definition at line 536 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 536 of file G4VLongitudinalStringDecay.cc
References hadronizer, PastInitPhase, ProbEta_b, ProbEta_c, pspin_barion, pspin_meson, scalarMesonMix, and vectorMesonMix.
void G4VLongitudinalStringDecay::SetVectorMesonProbability (G4double aValue)
Definition at line 486 of file G4VLongitudinalStringDecay.cc.
View newest version in sPHENIX GitHub at line 486 of file G4VLongitudinalStringDecay.cc
References hadronizer, PastInitPhase, ProbEta_b, ProbEta_c, pspin_barion, pspin_meson, scalarMesonMix, and vectorMesonMix.
virtual G4LorentzVector* G4VLongitudinalStringDecay::SplitEandP (G4ParticleDefinition * pHadron, G4FragmentingString * string, G4FragmentingString * newString) protected pure virtual
Implemented in G4QGSMFragmentation, and G4LundStringFragmentation.
virtual G4bool G4VLongitudinalStringDecay::SplitLast (G4FragmentingString * string, G4KineticTrackVector * LeftVector, G4KineticTrackVector * RightVector) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
virtual G4KineticTrack* G4VLongitudinalStringDecay::Splitup (G4FragmentingString * string, G4FragmentingString *& newString) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
virtual G4bool G4VLongitudinalStringDecay::StopFragmenting (const G4FragmentingString *const string) protected pure virtual
Implemented in G4LundStringFragmentation, and G4QGSMFragmentation.
Member Data Documentation
G4int G4VLongitudinalStringDecay::Baryon[5][5][5][4]
Definition at line 231 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 231 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), and SetMinMasses().
G4double G4VLongitudinalStringDecay::BaryonWeight[5][5][5][4]
Definition at line 232 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 232 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), and SetMinMasses().
G4int G4VLongitudinalStringDecay::ClusterLoopInterrupt protected
Definition at line 187 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 187 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4VLongitudinalStringDecay(), and GetClusterLoopInterrupt().
G4int G4VLongitudinalStringDecay::DecayQuark
Definition at line 236 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 236 of file G4VLongitudinalStringDecay.hh
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4QGSMFragmentation::GetLightConeZ(), and QuarkSplitup().
G4double G4VLongitudinalStringDecay::DiquarkBreakProb protected
Definition at line 184 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 184 of file G4VLongitudinalStringDecay.hh
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4VLongitudinalStringDecay(), GetDiquarkBreakProb(), and SetDiquarkBreakProbability().
G4double G4VLongitudinalStringDecay::DiquarkSuppress protected
Definition at line 183 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 183 of file G4VLongitudinalStringDecay.hh
Referenced by CreatePartonPair(), G4VLongitudinalStringDecay(), GetDiquarkSuppress(), and SetDiquarkSuppression().
G4ParticleDefinition* G4VLongitudinalStringDecay::FS_LeftHadron[350]
Definition at line 246 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 246 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), SetMinMasses(), and G4LundStringFragmentation::SplitLast().
G4ParticleDefinition * G4VLongitudinalStringDecay::FS_RightHadron[350]
Definition at line 246 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 246 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), SetMinMasses(), and G4LundStringFragmentation::SplitLast().
G4double G4VLongitudinalStringDecay::FS_Weight[350]
Definition at line 247 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 247 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4LundStringFragmentation::SampleState(), SetMinMasses(), and G4LundStringFragmentation::SplitLast().
G4HadronBuilder* G4VLongitudinalStringDecay::hadronizer protected
Definition at line 189 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 189 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4VLongitudinalStringDecay(), PossibleHadronMass(), QuarkSplitup(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), SetVectorMesonProbability(), G4QGSMFragmentation::SplitLast(), and ~G4VLongitudinalStringDecay().
G4double G4VLongitudinalStringDecay::Kappa protected
Definition at line 208 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 208 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), and SetStringTensionParameter().
G4double G4VLongitudinalStringDecay::Mass_of_b_quark
Definition at line 217 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 217 of file G4VLongitudinalStringDecay.hh
Referenced by SetMinMasses().
G4double G4VLongitudinalStringDecay::Mass_of_c_quark
Definition at line 216 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 216 of file G4VLongitudinalStringDecay.hh
Referenced by SetMinMasses().
G4double G4VLongitudinalStringDecay::Mass_of_light_quark
Definition at line 214 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 214 of file G4VLongitudinalStringDecay.hh
Referenced by SetMinMasses().
G4double G4VLongitudinalStringDecay::Mass_of_s_quark
Definition at line 215 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 215 of file G4VLongitudinalStringDecay.hh
Referenced by SetMinMasses().
G4double G4VLongitudinalStringDecay::Mass_of_string_junction
Definition at line 218 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 218 of file G4VLongitudinalStringDecay.hh
Referenced by SetMinMasses().
G4double G4VLongitudinalStringDecay::MassCut protected
Definition at line 178 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 178 of file G4VLongitudinalStringDecay.hh
Referenced by G4QGSMFragmentation::G4QGSMFragmentation(), G4VLongitudinalStringDecay(), GetMassCut(), G4QGSMFragmentation::IsItFragmentable(), ProduceOneHadron(), and SetMassCut().
G4double G4VLongitudinalStringDecay::MaxMass protected
Definition at line 204 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 204 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), PossibleHadronMass(), SetMinimalStringMass(), SetMinMasses(), and G4QGSMFragmentation::SplitLast().
G4int G4VLongitudinalStringDecay::Meson[5][5][7]
Definition at line 228 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 228 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), and SetMinMasses().
G4double G4VLongitudinalStringDecay::MesonWeight[5][5][7]
Definition at line 229 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 229 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), and SetMinMasses().
G4double G4VLongitudinalStringDecay::MinimalStringMass
Definition at line 224 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 224 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::IsItFragmentable(), SetMinimalStringMass(), SetMinMasses(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::StopFragmenting(), and G4LundStringFragmentation::StopFragmenting().
G4double G4VLongitudinalStringDecay::MinimalStringMass2
Definition at line 225 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 225 of file G4VLongitudinalStringDecay.hh
Referenced by SetMinimalStringMass2(), and SetMinMasses().
G4double G4VLongitudinalStringDecay::minMassQDiQStr[5][5][5]
Definition at line 221 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 221 of file G4VLongitudinalStringDecay.hh
Referenced by G4FTFParameters::GetMinMass(), SetMinimalStringMass(), and SetMinMasses().
G4double G4VLongitudinalStringDecay::minMassQQbarStr[5][5]
Definition at line 220 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 220 of file G4VLongitudinalStringDecay.hh
Referenced by G4FTFParameters::GetMinMass(), SetMinimalStringMass(), and SetMinMasses().
std::vector<G4ParticleDefinition *> G4VLongitudinalStringDecay::NewParticles protected
Definition at line 210 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 210 of file G4VLongitudinalStringDecay.hh
Referenced by FindParticle().
G4int G4VLongitudinalStringDecay::NewQuark
Definition at line 237 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 237 of file G4VLongitudinalStringDecay.hh
Referenced by G4QGSMFragmentation::DiQuarkSplitup(), G4QGSMFragmentation::GetLightConeZ(), and QuarkSplitup().
G4int G4VLongitudinalStringDecay::NumberOf_FS
Definition at line 248 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 248 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4LundStringFragmentation::SampleState(), SetMinMasses(), and G4LundStringFragmentation::SplitLast().
G4bool G4VLongitudinalStringDecay::PastInitPhase protected
Definition at line 206 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 206 of file G4VLongitudinalStringDecay.hh
Referenced by G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4VLongitudinalStringDecay(), SetDiquarkBreakProbability(), SetScalarMesonMixings(), SetSigmaTransverseMomentum(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
G4double G4VLongitudinalStringDecay::Prob_QQbar[5]
Definition at line 234 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 234 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), and SetMinMasses().
G4double G4VLongitudinalStringDecay::ProbBBbar protected
Definition at line 199 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 199 of file G4VLongitudinalStringDecay.hh
Referenced by GetProbBBbar(), SampleQuarkFlavor(), SetProbBBbar(), and SetProbCCbar().
G4double G4VLongitudinalStringDecay::ProbCB protected
Definition at line 202 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 202 of file G4VLongitudinalStringDecay.hh
Referenced by SampleQuarkFlavor(), SetProbBBbar(), and SetProbCCbar().
G4double G4VLongitudinalStringDecay::ProbCCbar protected
Definition at line 196 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 196 of file G4VLongitudinalStringDecay.hh
Referenced by GetProbCCbar(), SampleQuarkFlavor(), SetProbBBbar(), and SetProbCCbar().
G4double G4VLongitudinalStringDecay::ProbEta_b protected
Definition at line 200 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 200 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), GetProbEta_b(), SetMinMasses(), SetProbEta_b(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
G4double G4VLongitudinalStringDecay::ProbEta_c protected
Definition at line 197 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 197 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), GetProbEta_c(), SetMinMasses(), SetProbEta_c(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
G4double G4VLongitudinalStringDecay::pspin_barion protected
Definition at line 192 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 192 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
G4double G4VLongitudinalStringDecay::pspin_meson protected
Definition at line 191 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 191 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
G4int G4VLongitudinalStringDecay::Qcharge[5]
Definition at line 227 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 227 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), and SetMinMasses().
std::vector<G4double> G4VLongitudinalStringDecay::scalarMesonMix protected
Definition at line 194 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 194 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
G4double G4VLongitudinalStringDecay::SigmaQT protected
Definition at line 182 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 182 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::G4LundStringFragmentation(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::Sample4Momentum(), SampleQuarkPt(), and SetSigmaTransverseMomentum().
G4double G4VLongitudinalStringDecay::StrangeSuppress protected
Definition at line 185 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 185 of file G4VLongitudinalStringDecay.hh
Referenced by G4LundStringFragmentation::DiQuarkSplitup(), G4VLongitudinalStringDecay(), GetStrangeSuppress(), SampleQuarkFlavor(), and SetStrangenessSuppression().
G4int G4VLongitudinalStringDecay::StringLoopInterrupt protected
Definition at line 186 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 186 of file G4VLongitudinalStringDecay.hh
Referenced by G4QGSMFragmentation::FragmentString(), G4VLongitudinalStringDecay(), G4LundStringFragmentation::Loop_toFragmentString(), G4LundStringFragmentation::SplitEandP(), and G4QGSMFragmentation::SplitEandP().
std::vector<G4double> G4VLongitudinalStringDecay::vectorMesonMix protected
Definition at line 193 of file G4VLongitudinalStringDecay.hh.
View newest version in sPHENIX GitHub at line 193 of file G4VLongitudinalStringDecay.hh
Referenced by G4VLongitudinalStringDecay(), SetMinMasses(), SetScalarMesonMixings(), SetSpinThreeHalfBarionProbability(), SetVectorMesonMixings(), and SetVectorMesonProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4VLongitudinalStringDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/src/G4VLongitudinalStringDecay.cc