ECCE @ EIC Software: G4VisTrajContext Class Reference
G4VisTrajContext Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VisTrajContext.hh>
Public Member Functions
G4VisTrajContext (const G4String &name="Unspecified")
virtual ~G4VisTrajContext ()
G4String Name () const
void SetVisible (const G4bool &visible)
void Print (std::ostream &ostr) const
void SetLineColour (const G4Colour &colour)
G4Colour GetLineColour () const
void SetLineWidth (const G4double &width)
G4double GetLineWidth () const
void SetDrawLine (const G4bool &draw)
G4bool GetDrawLine () const
void SetLineVisible (const G4bool &visible)
G4bool GetLineVisible () const
void SetDrawAuxPts (const G4bool &draw)
G4bool GetDrawAuxPts () const
void SetAuxPtsType (const G4Polymarker::MarkerType &marker)
G4Polymarker::MarkerType GetAuxPtsType () const
void SetAuxPtsSize (const G4double &size)
G4double GetAuxPtsSize () const
void SetAuxPtsSizeType (const G4VMarker::SizeType &sizeType)
G4VMarker::SizeType GetAuxPtsSizeType () const
void SetAuxPtsFillStyle (const G4VMarker::FillStyle &style)
G4VMarker::FillStyle GetAuxPtsFillStyle () const
void SetAuxPtsColour (const G4Colour &colour)
G4Colour GetAuxPtsColour () const
void SetAuxPtsVisible (const G4bool &visible)
G4bool GetAuxPtsVisible () const
void SetDrawStepPts (const G4bool &draw)
G4bool GetDrawStepPts () const
void SetStepPtsType (const G4Polymarker::MarkerType &marker)
G4Polymarker::MarkerType GetStepPtsType () const
void SetStepPtsSize (const G4double &size)
G4double GetStepPtsSize () const
void SetStepPtsSizeType (const G4VMarker::SizeType &sizeType)
G4VMarker::SizeType GetStepPtsSizeType () const
void SetStepPtsFillStyle (const G4VMarker::FillStyle &style)
G4VMarker::FillStyle GetStepPtsFillStyle () const
void SetStepPtsColour (const G4Colour &colour)
G4Colour GetStepPtsColour () const
void SetStepPtsVisible (const G4bool &visible)
G4bool GetStepPtsVisible () const
void SetTimeSliceInterval (const G4double &interval)
G4double GetTimeSliceInterval () const
Private Attributes
G4String fName
G4double fLineWidth
G4Colour fLineColour
G4bool fLineVisible
G4bool fDrawLine
G4bool fDrawAuxPts
G4Polymarker::MarkerType fAuxPtsType
G4double fAuxPtsSize
G4VMarker::SizeType fAuxPtsSizeType
G4VMarker::FillStyle fAuxPtsFillStyle
G4Colour fAuxPtsColour
G4bool fAuxPtsVisible
G4bool fDrawStepPts
G4Polymarker::MarkerType fStepPtsType
G4double fStepPtsSize
G4VMarker::SizeType fStepPtsSizeType
G4VMarker::FillStyle fStepPtsFillStyle
G4Colour fStepPtsColour
G4bool fStepPtsVisible
G4double fTimeSliceInterval
Detailed Description
Definition at line 35 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 35 of file G4VisTrajContext.hh
Constructor & Destructor Documentation
G4VisTrajContext::G4VisTrajContext (const G4String & name = "Unspecified")
Definition at line 29 of file G4VisTrajContext.cc.
View newest version in sPHENIX GitHub at line 29 of file G4VisTrajContext.cc
G4VisTrajContext::~G4VisTrajContext () virtual
Definition at line 53 of file G4VisTrajContext.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VisTrajContext.cc
Member Function Documentation
G4Colour G4VisTrajContext::GetAuxPtsColour () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4VMarker::FillStyle G4VisTrajContext::GetAuxPtsFillStyle () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4double G4VisTrajContext::GetAuxPtsSize () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4VMarker::SizeType G4VisTrajContext::GetAuxPtsSizeType () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4Polymarker::MarkerType G4VisTrajContext::GetAuxPtsType () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4bool G4VisTrajContext::GetAuxPtsVisible () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4bool G4VisTrajContext::GetDrawAuxPts () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawLineAndPoints(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4bool G4VisTrajContext::GetDrawLine () const
Referenced by G4TrajectoryDrawerUtils::DrawLineAndPoints(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4bool G4VisTrajContext::GetDrawStepPts () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawLineAndPoints(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4Colour G4VisTrajContext::GetLineColour () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4bool G4VisTrajContext::GetLineVisible () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4double G4VisTrajContext::GetLineWidth () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4Colour G4VisTrajContext::GetStepPtsColour () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4VMarker::FillStyle G4VisTrajContext::GetStepPtsFillStyle () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4double G4VisTrajContext::GetStepPtsSize () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4VMarker::SizeType G4VisTrajContext::GetStepPtsSizeType () const
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4Polymarker::MarkerType G4VisTrajContext::GetStepPtsType () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4bool G4VisTrajContext::GetStepPtsVisible () const
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawerUtils::DrawWithoutTime(), and G4TrajectoryDrawerUtils::DrawWithTime().
G4double G4VisTrajContext::GetTimeSliceInterval () const
Referenced by G4TrajectoryDrawerUtils::DrawLineAndPoints(), and G4TrajectoryDrawerUtils::GetPointsAndTimes().
G4String G4VisTrajContext::Name () const
void G4VisTrajContext::Print (std::ostream & ostr) const
Referenced by G4TrajectoryGenericDrawer::Draw(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), G4TrajectoryDrawByAttribute::Draw(), G4TrajectoryDrawByCharge::Draw(), G4TrajectoryGenericDrawer::Print(), G4TrajectoryDrawByOriginVolume::Print(), G4TrajectoryDrawByParticleID::Print(), G4TrajectoryDrawByEncounteredVolume::Print(), G4TrajectoryDrawByAttribute::Print(), and G4TrajectoryDrawByCharge::Print().
void G4VisTrajContext::SetAuxPtsColour (const G4Colour & colour)
void G4VisTrajContext::SetAuxPtsFillStyle (const G4VMarker::FillStyle & style)
void G4VisTrajContext::SetAuxPtsSize (const G4double & size)
void G4VisTrajContext::SetAuxPtsSizeType (const G4VMarker::SizeType & sizeType)
void G4VisTrajContext::SetAuxPtsType (const G4Polymarker::MarkerType & marker)
void G4VisTrajContext::SetAuxPtsVisible (const G4bool & visible)
void G4VisTrajContext::SetDrawAuxPts (const G4bool & draw)
void G4VisTrajContext::SetDrawLine (const G4bool & draw)
void G4VisTrajContext::SetDrawStepPts (const G4bool & draw)
void G4VisTrajContext::SetLineColour (const G4Colour & colour)
Referenced by G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), and G4TrajectoryDrawByCharge::Draw().
void G4VisTrajContext::SetLineVisible (const G4bool & visible)
void G4VisTrajContext::SetLineWidth (const G4double & width)
void G4VisTrajContext::SetStepPtsColour (const G4Colour & colour)
void G4VisTrajContext::SetStepPtsFillStyle (const G4VMarker::FillStyle & style)
void G4VisTrajContext::SetStepPtsSize (const G4double & size)
void G4VisTrajContext::SetStepPtsSizeType (const G4VMarker::SizeType & sizeType)
void G4VisTrajContext::SetStepPtsType (const G4Polymarker::MarkerType & marker)
void G4VisTrajContext::SetStepPtsVisible (const G4bool & visible)
void G4VisTrajContext::SetTimeSliceInterval (const G4double & interval)
void G4VisTrajContext::SetVisible (const G4bool & visible)
Referenced by G4TrajectoryGenericDrawer::Draw().
Member Data Documentation
G4Colour G4VisTrajContext::fAuxPtsColour private
Definition at line 129 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 129 of file G4VisTrajContext.hh
G4VMarker::FillStyle G4VisTrajContext::fAuxPtsFillStyle private
Definition at line 128 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 128 of file G4VisTrajContext.hh
G4double G4VisTrajContext::fAuxPtsSize private
Definition at line 126 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 126 of file G4VisTrajContext.hh
G4VMarker::SizeType G4VisTrajContext::fAuxPtsSizeType private
Definition at line 127 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VisTrajContext.hh
G4Polymarker::MarkerType G4VisTrajContext::fAuxPtsType private
Definition at line 125 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 125 of file G4VisTrajContext.hh
G4bool G4VisTrajContext::fAuxPtsVisible private
Definition at line 130 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 130 of file G4VisTrajContext.hh
G4bool G4VisTrajContext::fDrawAuxPts private
Definition at line 124 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 124 of file G4VisTrajContext.hh
G4bool G4VisTrajContext::fDrawLine private
Definition at line 121 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 121 of file G4VisTrajContext.hh
G4bool G4VisTrajContext::fDrawStepPts private
Definition at line 133 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 133 of file G4VisTrajContext.hh
G4Colour G4VisTrajContext::fLineColour private
Definition at line 119 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VisTrajContext.hh
G4bool G4VisTrajContext::fLineVisible private
Definition at line 120 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VisTrajContext.hh
G4double G4VisTrajContext::fLineWidth private
Definition at line 118 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VisTrajContext.hh
G4String G4VisTrajContext::fName private
Definition at line 115 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VisTrajContext.hh
G4Colour G4VisTrajContext::fStepPtsColour private
Definition at line 138 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 138 of file G4VisTrajContext.hh
G4VMarker::FillStyle G4VisTrajContext::fStepPtsFillStyle private
Definition at line 137 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 137 of file G4VisTrajContext.hh
G4double G4VisTrajContext::fStepPtsSize private
Definition at line 135 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 135 of file G4VisTrajContext.hh
G4VMarker::SizeType G4VisTrajContext::fStepPtsSizeType private
Definition at line 136 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 136 of file G4VisTrajContext.hh
G4Polymarker::MarkerType G4VisTrajContext::fStepPtsType private
Definition at line 134 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 134 of file G4VisTrajContext.hh
G4bool G4VisTrajContext::fStepPtsVisible private
Definition at line 139 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 139 of file G4VisTrajContext.hh
G4double G4VisTrajContext::fTimeSliceInterval private
Definition at line 142 of file G4VisTrajContext.hh.
View newest version in sPHENIX GitHub at line 142 of file G4VisTrajContext.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VisTrajContext.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4VisTrajContext.cc