ECCE @ EIC Software: G4InuclSpecialFunctions Namespace Reference
G4InuclSpecialFunctions Namespace Reference
Classes
class paraMaker
Functions
G4double bindingEnergy (G4int A, G4int Z)
G4double bindingEnergyAsymptotic (G4int A, G4int Z)
G4double FermiEnergy (G4int A, G4int Z, G4int ntype)
G4double getAL (G4int A)
G4double csNN (G4double e)
G4double csPN (G4double e)
G4double G4cbrt (G4double x)
G4double G4cbrt (G4int n)
G4double inuclRndm ()
G4double randomInuclPowers (G4double ekin, const G4double(&coeff)[4][4])
G4double randomGauss (G4double sigma)
G4double randomPHI ()
std::pair< G4double, G4double > randomCOS_SIN ()
G4double nucleiLevelDensity (G4int A)
G4LorentzVector generateWithFixedTheta (G4double ct, G4double p, G4double mass=0.)
G4LorentzVector generateWithRandomAngles (G4double p, G4double mass=0.)
Function Documentation
G4double G4InuclSpecialFunctions::bindingEnergy (G4int A, G4int Z)
Definition at line 36 of file bindingEnergy.cc.
View newest version in sPHENIX GitHub at line 36 of file bindingEnergy.cc
References G4NucleiProperties::GetBindingEnergy().
Referenced by G4VAtomDeexcitation::AlongStepDeexcitation(), G4RDeIonisationSpectrum::AverageEnergy(), G4eIonisationSpectrum::AverageEnergy(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), G4CascadeDeexciteBase::explosion(), G4EquilibriumEvaporator::explosion(), G4NucleiModel::fillBindingEnergies(), G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), G4ProtonField::GetBarrier(), G4SigmaPlusField::GetField(), G4KaonZeroField::GetField(), G4SigmaMinusField::GetField(), G4SigmaZeroField::GetField(), G4AntiProtonField::GetField(), G4KaonPlusField::GetField(), G4KaonMinusField::GetField(), G4PionPlusField::GetField(), G4PionZeroField::GetField(), G4PionMinusField::GetField(), G4CascadeRecoilMaker::goodNucleus(), G4AtomicTransitionManager::Initialise(), G4NucleiModel::initializeCascad(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4eIonisationSpectrum::Probability(), G4RDeIonisationSpectrum::Probability(), G4DNAPTBIonisationModel::RandomizeEjectedElectronEnergyFromCumulated(), G4PenelopeOscillatorManager::ReadElementData(), G4DeltaAngle::SampleDirection(), G4eIonisationSpectrum::SampleEnergy(), G4RDeIonisationSpectrum::SampleEnergy(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4KM_OpticalEqRhs::SetFactor(), and G4MicroElecInelasticModel::TransferedEnergy().
G4double G4InuclSpecialFunctions::bindingEnergyAsymptotic (G4int A, G4int Z)
Definition at line 33 of file bindingEnergyAsymptotic.cc.
View newest version in sPHENIX GitHub at line 33 of file bindingEnergyAsymptotic.cc
References A(), G4cbrt(), X, X1, and X2.
Referenced by G4Fissioner::deExcite().
G4double G4InuclSpecialFunctions::csNN (G4double e)
Definition at line 82 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 82 of file G4InuclSpecialFunctions.cc
References e.
Referenced by G4NonEquilibriumEvaporator::deExcite().
G4double G4InuclSpecialFunctions::csPN (G4double e)
Definition at line 94 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 94 of file G4InuclSpecialFunctions.cc
References e.
Referenced by G4NonEquilibriumEvaporator::deExcite().
G4double G4InuclSpecialFunctions::FermiEnergy (G4int A, G4int Z, G4int ntype)
Definition at line 108 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 108 of file G4InuclSpecialFunctions.cc
References C(), G4Pow::GetInstance(), and G4Pow::Z23().
Referenced by G4NonEquilibriumEvaporator::deExcite().
G4double G4InuclSpecialFunctions::G4cbrt (G4double x)
Definition at line 116 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 116 of file G4InuclSpecialFunctions.cc
References G4Exp(), and G4Log().
Referenced by bindingEnergyAsymptotic(), G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), G4NucleiModel::fillPotentials(), G4NucleiModel::generateModel(), G4NucleiModel::generateNucleonMomentum(), getAL(), G4EquilibriumEvaporator::getQF(), G4CascadeColliderBase::inelasticInteractionPossible(), G4IntraNucleiCascader::initialize(), and G4Fissioner::potentialMinimization().
G4double G4InuclSpecialFunctions::G4cbrt (G4int n)
Definition at line 120 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 120 of file G4InuclSpecialFunctions.cc
References kdfinder::abs(), G4Pow::GetInstance(), and G4Pow::Z13().
G4LorentzVector G4InuclSpecialFunctions::generateWithFixedTheta (G4double ct, G4double p, G4double mass = 0.)
Definition at line 150 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 150 of file G4InuclSpecialFunctions.cc
References G4ThreadLocal, phi, pt, randomPHI(), G4AutoDelete::Register(), CLHEP::Hep3Vector::set(), and CLHEP::HepLorentzVector::setVectM().
Referenced by G4CascadeFinalStateAlgorithm::FillDirManyBody(), G4CascadeFinalStateAlgorithm::FillDirThreeBody(), G4BigBanger::generateBangInSCM(), and G4NucleiModel::initializeCascad().
G4LorentzVector G4InuclSpecialFunctions::generateWithRandomAngles (G4double p, G4double mass = 0.)
Definition at line 177 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 177 of file G4InuclSpecialFunctions.cc
References G4ThreadLocal, phi, pt, randomCOS_SIN(), randomPHI(), G4AutoDelete::Register(), CLHEP::Hep3Vector::set(), and CLHEP::HepLorentzVector::setVectM().
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), G4BigBanger::generateBangInSCM(), G4NucleiModel::generateNucleonMomentum(), G4ElementaryParticleCollider::generateSCMpionAbsorption(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), and G4NucleiModel::initializeCascad().
G4double G4InuclSpecialFunctions::getAL (G4int A)
Definition at line 78 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 78 of file G4InuclSpecialFunctions.cc
References G4cbrt().
Referenced by G4NonEquilibriumEvaporator::deExcite(), and G4EquilibriumEvaporator::deExcite().
G4double G4InuclSpecialFunctions::inuclRndm ()
Definition at line 124 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 124 of file G4InuclSpecialFunctions.cc
References G4UniformRand.
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), G4CascadeFinalStateAlgorithm::GenerateCosTheta(), G4NucleiModel::generateInteractionLength(), G4NucleiModel::generateInteractionPartners(), G4NucleiModel::generateNucleonMomentum(), G4BigBanger::generateX(), G4InuclParamAngDst::GetCosTheta(), G4NucleiModel::initializeCascad(), randomCOS_SIN(), randomGauss(), randomPHI(), and G4IntraNucleiCascader::setupCascade().
G4double G4InuclSpecialFunctions::nucleiLevelDensity (G4int A)
Definition at line 32 of file nucleiLevelDensity.cc.
View newest version in sPHENIX GitHub at line 32 of file nucleiLevelDensity.cc
References a.
Referenced by G4Fissioner::deExcite().
std::pair< G4double, G4double > G4InuclSpecialFunctions::randomCOS_SIN ()
Definition at line 143 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 143 of file G4InuclSpecialFunctions.cc
References inuclRndm().
Referenced by generateWithRandomAngles().
G4double G4InuclSpecialFunctions::randomGauss (G4double sigma)
Definition at line 128 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 128 of file G4InuclSpecialFunctions.cc
References eps, G4Log(), inuclRndm(), r1, r2, and twopi.
Referenced by G4Fissioner::deExcite().
G4double G4InuclSpecialFunctions::randomInuclPowers (G4double ekin, const G4double(&) coeff[4][4])
Definition at line 54 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 54 of file G4InuclSpecialFunctions.cc
References C(), G4UniformRand, G4Pow::GetInstance(), k, G4Pow::powN(), and S().
Referenced by G4InuclParamAngDst::GetCosTheta(), and G4InuclParamMomDst::GetMomentum().
G4double G4InuclSpecialFunctions::randomPHI ()
Definition at line 139 of file G4InuclSpecialFunctions.cc.
View newest version in sPHENIX GitHub at line 139 of file G4InuclSpecialFunctions.cc
References inuclRndm(), and twopi.
Referenced by generateWithFixedTheta(), generateWithRandomAngles(), and G4NucleiModel::initializeCascad().