ECCE @ EIC Software: CLibSymbolInfo Class Reference
CLibSymbolInfo Class Reference
Public Member Functions
CLibSymbolInfo ()
virtual ~CLibSymbolInfo ()
BOOL DumpSymbols (LPTSTR lpszLibPathName, std::ostream &pFile)
std::string GetLastError () const
Protected Member Functions
BOOL Dump (LPTSTR lpszLibPathName, std::ostream &pFile)
BOOL IsRegularLibSymbol (PSTR pszSymbolName)
BOOL IsFiltedSymbol (std::string &pszSymbolName)
DWORD ConvertBigEndian (DWORD bigEndian)
Protected Attributes
std::string m_strResultsString
std::string m_strErrorMsg
Detailed Description
Definition at line 58 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 58 of file genwindef.cc
Constructor & Destructor Documentation
CLibSymbolInfo::CLibSymbolInfo ()
Definition at line 110 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 110 of file genwindef.cc
CLibSymbolInfo::~CLibSymbolInfo () virtual
Definition at line 114 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 114 of file genwindef.cc
Member Function Documentation
DWORD CLibSymbolInfo::ConvertBigEndian (DWORD bigEndian) protected
Definition at line 270 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 270 of file genwindef.cc
BOOL CLibSymbolInfo::Dump (LPTSTR lpszLibPathName, std::ostream & pFile) protected
Definition at line 154 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 154 of file genwindef.cc
References FALSE, MEMORY_MAPPED_FILE::GetBase(), MEMORY_MAPPED_FILE::IsValid(), MakePtr, offset, and TRUE.
BOOL CLibSymbolInfo::DumpSymbols (LPTSTR lpszLibPathName, std::ostream & pFile)
Definition at line 130 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 130 of file genwindef.cc
References FALSE, and TRUE.
Referenced by main().
string CLibSymbolInfo::GetLastError () const
Definition at line 282 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 282 of file genwindef.cc
BOOL CLibSymbolInfo::IsFiltedSymbol (std::string & pszSymbolName) protected
Definition at line 246 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 246 of file genwindef.cc
References FALSE, and TRUE.
BOOL CLibSymbolInfo::IsRegularLibSymbol (PSTR pszSymbolName) protected
Definition at line 230 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 230 of file genwindef.cc
References FALSE, and TRUE.
Member Data Documentation
std::string CLibSymbolInfo::m_strErrorMsg protected
Definition at line 68 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 68 of file genwindef.cc
std::string CLibSymbolInfo::m_strResultsString protected
Definition at line 67 of file genwindef.cc.
View newest version in sPHENIX GitHub at line 67 of file genwindef.cc
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/config/genwindef.cc