ECCE @ EIC Software: G4ScreenedCoulombClassicalKinematics Class Reference
G4ScreenedCoulombClassicalKinematics Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh>
Public Member Functions
G4ScreenedCoulombClassicalKinematics ()
virtual void DoCollisionStep (class G4ScreenedNuclearRecoil *master, const class G4Track &aTrack, const class G4Step &aStep)
G4bool DoScreeningComputation (class G4ScreenedNuclearRecoil *master, const G4ScreeningTables *screen, G4double eps, G4double beta)
virtual ~G4ScreenedCoulombClassicalKinematics ()
Public Member Functions inherited from G4ScreenedCoulombCrossSectionInfo
G4ScreenedCoulombCrossSectionInfo ()
~G4ScreenedCoulombCrossSectionInfo ()
Public Member Functions inherited from G4ScreenedCollisionStage
virtual ~G4ScreenedCollisionStage ()
Protected Attributes
c2_const_plugin_function_p
< G4double > & phifunc
c2_linear_p< G4double > & xovereps
G4_c2_ptr diff
Additional Inherited Members
Static Public Member Functions inherited from G4ScreenedCoulombCrossSectionInfo
static const char * CVSHeaderVers ()
static const char * CVSFileVers ()
Detailed Description
Definition at line 172 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ScreenedNuclearRecoil.hh
Constructor & Destructor Documentation
G4ScreenedCoulombClassicalKinematics::G4ScreenedCoulombClassicalKinematics ()
Definition at line 578 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 578 of file G4ScreenedNuclearRecoil.cc
virtual G4ScreenedCoulombClassicalKinematics::~G4ScreenedCoulombClassicalKinematics () inline virtual
Definition at line 183 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 183 of file G4ScreenedNuclearRecoil.hh
Member Function Documentation
void G4ScreenedCoulombClassicalKinematics::DoCollisionStep (class G4ScreenedNuclearRecoil * master, const class G4Track & aTrack, const class G4Step & aStep) virtual
Implements G4ScreenedCollisionStage.
Definition at line 691 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 691 of file G4ScreenedNuclearRecoil.cc
References A(), G4CoulombKinematicsInfo::a1, G4CoulombKinematicsInfo::a2, source.hepunit::amu_c2, G4ScreeningTables::au, G4CoulombKinematicsInfo::cosZeta, G4CoulombKinematicsInfo::crossSection, G4ScreenedNuclearRecoil::DepositEnergy(), DoScreeningComputation(), source.hepunit::elm_coupling, eplus, eps, G4CoulombKinematicsInfo::eRecoil, G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4ScreenedNuclearRecoil::GetEnableRecoils(), G4ScreenedNuclearRecoil::GetKinematics(), G4DynamicParticle::GetKineticEnergy(), G4ScreenedNuclearRecoil::GetParticleChange(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ScreenedNuclearRecoil::GetRecoilCutoff(), G4ScreenedCoulombCrossSection::GetScreening(), G4ScreenedNuclearRecoil::GetValidCollision(), G4CoulombKinematicsInfo::impactParameter, G4ParticleChange::ProposeEnergy(), G4CoulombKinematicsInfo::recoilIon, G4ScreenedNuclearRecoil::SetValidCollision(), G4CoulombKinematicsInfo::targetMaterial, Z, and G4ScreeningTables::z1.
G4bool G4ScreenedCoulombClassicalKinematics::DoScreeningComputation (class G4ScreenedNuclearRecoil * master, const G4ScreeningTables * screen, G4double eps, G4double beta)
Definition at line 591 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 591 of file G4ScreenedNuclearRecoil.cc
References A(), G4CoulombKinematicsInfo::a1, G4CoulombKinematicsInfo::a2, alpha, G4ScreeningTables::au, G4ScreenedNuclearRecoil::CheckNuclearCollision(), G4CoulombKinematicsInfo::cosTheta, G4CoulombKinematicsInfo::cosZeta, diff, e, G4ScreeningTables::EMphiData, eps, ff, c2_function< float_type >::find_root(), G4cout, G4endl, c2_const_ptr< float_type >::get(), G4ScreenedNuclearRecoil::GetKinematics(), k, min, phifunc, pi, c2_linear_p< float_type >::reset(), c2_const_plugin_function_p< float_type >::set_function(), G4CoulombKinematicsInfo::sinTheta, G4CoulombKinematicsInfo::sinZeta, c2_plugin_function_p< float_type >::unset_function(), x, c2_function< float_type >::xmax(), c2_function< float_type >::xmin(), xovereps, xvals, and y.
Referenced by DoCollisionStep().
Member Data Documentation
G4_c2_ptr G4ScreenedCoulombClassicalKinematics::diff protected
Definition at line 189 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 189 of file G4ScreenedNuclearRecoil.hh
Referenced by DoScreeningComputation().
c2_const_plugin_function_p<G4double>& G4ScreenedCoulombClassicalKinematics::phifunc protected
Definition at line 187 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 187 of file G4ScreenedNuclearRecoil.hh
Referenced by DoScreeningComputation().
c2_linear_p<G4double>& G4ScreenedCoulombClassicalKinematics::xovereps protected
Definition at line 188 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 188 of file G4ScreenedNuclearRecoil.hh
Referenced by DoScreeningComputation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/G4ScreenedNuclearRecoil.cc