ECCE @ EIC Software: CCalStackingAction Class Reference
CCalStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalStackingAction.hh>
Public Types
enum stageLevel { firstStage, end }
enum { maxNumberOfSD = 30 }
Public Member Functions
CCalStackingAction ()
~CCalStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Member Functions
void initialize ()
G4bool trackStartsInCalo (const G4Track *atrack)
void setPrimaryID (G4int id)
Private Attributes
G4double fTimeLimit
stageLevel stage
G4int numberOfSD
G4String SDName [maxNumberOfSD]
G4int nurgent
G4int acceptSecondaries
CCaloSD * theCaloSD [maxNumberOfSD]
G4bool isInitialized
Friends
class CCalSensAssign
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 40 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalStackingAction.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
maxNumberOfSD
Definition at line 54 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalStackingAction.hh
enum CCalStackingAction::stageLevel
Enumerator:
firstStage
end
Definition at line 53 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalStackingAction.hh
Constructor & Destructor Documentation
CCalStackingAction::CCalStackingAction ()
Definition at line 43 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalStackingAction.cc
CCalStackingAction::~CCalStackingAction ()
Definition at line 47 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file CCalStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack CCalStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
PRIMARIES ///
SECONDARIES ///
Reimplemented from G4UserStackingAction.
Definition at line 99 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 99 of file CCalStackingAction.cc
References acceptSecondaries, G4UserStackingAction::ClassifyNewTrack(), end, fKill, fTimeLimit, fUrgent, fWaiting, G4cout, G4endl, G4Track::GetDefinition(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), MeV, nurgent, setPrimaryID(), stage, and trackStartsInCalo().
void CCalStackingAction::initialize () private
Definition at line 57 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file CCalStackingAction.cc
References G4SDManager::FindSensitiveDetector(), G4cout, G4endl, CCalSDList::getInstance(), CCalSDList::getNumberOfCaloSD(), G4SDManager::GetSDMpointerIfExist(), isInitialized, numberOfSD, SDName, CCaloSD::SetPrimaryID(), and theCaloSD.
Referenced by PrepareNewEvent().
void CCalStackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 164 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 164 of file CCalStackingAction.cc
References acceptSecondaries, end, G4cout, G4endl, G4StackManager::GetNUrgentTrack(), nurgent, G4StackManager::ReClassify(), setPrimaryID(), G4UserStackingAction::stackManager, and stage.
void CCalStackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 49 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file CCalStackingAction.cc
References acceptSecondaries, firstStage, initialize(), isInitialized, nurgent, and stage.
void CCalStackingAction::setPrimaryID (G4int id) private
Definition at line 194 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 194 of file CCalStackingAction.cc
References numberOfSD, CCaloSD::SetPrimaryID(), and theCaloSD.
Referenced by ClassifyNewTrack(), and NewStage().
G4bool CCalStackingAction::trackStartsInCalo (const G4Track * atrack) private
This method should check that the secondary particle was produced inside the detector calorimeter and really is part of the shower. If it has been produced before the calorimeter for ex. Bremsstrahlung, it should be treated as a new particle producing a new shower.
Definition at line 182 of file CCalStackingAction.cc.
View newest version in sPHENIX GitHub at line 182 of file CCalStackingAction.cc
Referenced by ClassifyNewTrack().
Friends And Related Function Documentation
friend class CCalSensAssign friend
Definition at line 42 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 42 of file CCalStackingAction.hh
Member Data Documentation
G4int CCalStackingAction::acceptSecondaries private
Definition at line 66 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file CCalStackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
G4double CCalStackingAction::fTimeLimit private
Definition at line 61 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalStackingAction.hh
Referenced by ClassifyNewTrack().
G4bool CCalStackingAction::isInitialized private
Definition at line 68 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file CCalStackingAction.hh
Referenced by initialize(), and PrepareNewEvent().
G4int CCalStackingAction::numberOfSD private
Definition at line 63 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalStackingAction.hh
Referenced by initialize(), and setPrimaryID().
G4int CCalStackingAction::nurgent private
Definition at line 65 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file CCalStackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
G4String CCalStackingAction::SDName[maxNumberOfSD] private
Definition at line 64 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file CCalStackingAction.hh
Referenced by initialize().
stageLevel CCalStackingAction::stage private
Definition at line 62 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalStackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
CCaloSD* CCalStackingAction::theCaloSD[maxNumberOfSD] private
Definition at line 67 of file CCalStackingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file CCalStackingAction.hh
Referenced by initialize(), and setPrimaryID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalStackingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalStackingAction.cc