ECCE @ EIC Software: TrentoPassiveProtonBeamLine Class Reference
TrentoPassiveProtonBeamLine Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyTIFPAPassiveProtonBeamLine.hh>
Public Member Functions
TrentoPassiveProtonBeamLine ()
~TrentoPassiveProtonBeamLine ()
G4VPhysicalVolume * Construct ()
void HadrontherapyBeamLineSupport ()
void HadrontherapyBeamMonitoring ()
void HadrontherapyBeamScatteringFoils ()
void HadrontherapyBeamCollimators ()
void HadrontherapyRidgeFilter ()
void SetScatteringFoilXSize (G4double)
void SetPreCollimatorXSize (G4double)
void SetPreCollimatorXPosition (G4double)
void SetAirTubeYSize (G4double)
void SetAirTubeZSize (G4double)
void SetScattererMaterial (G4String)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Static Public Member Functions
static
TrentoPassiveProtonBeamLine * GetInstance ()
Private Member Functions
void SetDefaultDimensions ()
void ConstructTrentoPassiveProtonBeamLine ()
Private Attributes
TrentoPassiveProtonBeamLineMessenger * TrentoPassiveMessenger
G4LogicalVolume * logicTreatmentRoom
G4VPhysicalVolume * physicalTreatmentRoom
HadrontherapyDetectorConstruction * hadrontherapyDetectorConstruction
G4Material * kapton
G4double ScatteringFoilXSize
G4double ScatteringFoilYSize
G4double ScatteringFoilZSize
G4double ScatteringFoilXPosition
G4double ScatteringFoilYPosition
G4double ScatteringFoilZPosition
G4double preCollimatorXHalfSide
G4double preCollimatorXPosition
G4double preCollimatorYPosition
G4double preCollimatorZPosition
G4double YHalfSideAirTube
G4double ZHalfSideAirTube
G4VPhysicalVolume * physiBeamLineSupport
G4VPhysicalVolume * physiBeamLineCover
G4VPhysicalVolume * physiBeamLineCover2
G4VPhysicalVolume * physiMonitorLayer1
G4VPhysicalVolume * physiMonitorLayer2
G4VPhysicalVolume * internalMonitorStructurePV
G4VPhysicalVolume * firstFoilPV
G4VPhysicalVolume * secondFoilPV
G4VPhysicalVolume * airgapPV
G4Box * ScatteringFoil
G4LogicalVolume * logicScatteringFoil
G4VPhysicalVolume * physiScatteringFoil
G4VPhysicalVolume * ridgeFilterPhys
G4Box * preCollimator
G4VPhysicalVolume * physiPreCollimator
G4Box * Collimator
G4VPhysicalVolume * physiCollimator
G4Box * solidAirTube
G4Box * solidAirPreTube
G4VPhysicalVolume * mother
G4VPhysicalVolume * physiAirTube
G4VPhysicalVolume * physiAirPreTube
G4VisAttributes * blue
G4VisAttributes * gray
G4VisAttributes * white
G4VisAttributes * red
G4VisAttributes * yellow
G4VisAttributes * green
G4VisAttributes * darkGreen
G4VisAttributes * darkOrange3
G4VisAttributes * skyBlue
G4Material * beamLineSupportMaterial
G4Material * vacuumZoneMaterial
G4Material * layerMonitorChamberMaterial
G4Material * layerDefaultMaterial
G4Material * FoilMaterial
G4Material * internalStructureMaterial
G4Material * airgapMaterial
G4Material * ScatteringFoilMaterial
G4Material * singleTrapMaterial
G4Material * CollimatorMaterial
G4Material * preCollimatorMaterial
G4Material * airTubeMaterial
G4Material * airTube2Material
G4Material * airTube3Material
G4Material * ridgeFilterMaterial
HadrontherapyDetectorROGeometry * RO
Static Private Attributes
static
TrentoPassiveProtonBeamLine * instance
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 45 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 45 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
Constructor & Destructor Documentation
TrentoPassiveProtonBeamLine::TrentoPassiveProtonBeamLine ()
Definition at line 50 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 50 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, G4VUserDetectorConstruction::RegisterParallelWorld(), RO, and TrentoPassiveMessenger.
TrentoPassiveProtonBeamLine::~TrentoPassiveProtonBeamLine ()
Definition at line 72 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 72 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References hadrontherapyDetectorConstruction, and TrentoPassiveMessenger.
Member Function Documentation
G4VPhysicalVolume * TrentoPassiveProtonBeamLine::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 81 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 81 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
void TrentoPassiveProtonBeamLine::ConstructTrentoPassiveProtonBeamLine () private
Definition at line 272 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 272 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References cm, G4NistManager::FindOrBuildMaterial(), G4VisAttributes::GetInvisible(), and G4NistManager::Instance().
static TrentoPassiveProtonBeamLine* TrentoPassiveProtonBeamLine::GetInstance () static
void TrentoPassiveProtonBeamLine::HadrontherapyBeamCollimators ()
Definition at line 745 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 745 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References cm.
void TrentoPassiveProtonBeamLine::HadrontherapyBeamLineSupport ()
Definition at line 317 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 317 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References gray, m, and mm.
void TrentoPassiveProtonBeamLine::HadrontherapyBeamMonitoring ()
External Structure of the Monitor Chamber
Definition at line 397 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 397 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4AssemblyVolume::AddPlacedVolume(), cm, gray, mm, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and um.
void TrentoPassiveProtonBeamLine::HadrontherapyBeamScatteringFoils ()
Definition at line 555 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 555 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
void TrentoPassiveProtonBeamLine::HadrontherapyRidgeFilter ()
Definition at line 588 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 588 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References cm, deg, minY, mm, CLHEP::HepRotation::rotateY(), G4LogicalVolume::SetVisAttributes(), x1, x2, x3, x4, x5, and x6.
void TrentoPassiveProtonBeamLine::SetAirTubeYSize (G4double value)
Definition at line 916 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 916 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void TrentoPassiveProtonBeamLine::SetAirTubeZSize (G4double value)
Definition at line 925 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 925 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void TrentoPassiveProtonBeamLine::SetDefaultDimensions () private
Definition at line 113 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 113 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4Material::AddElement(), G4Material::AddMaterial(), cm, cm3, G4NistManager::FindOrBuildElement(), G4NistManager::FindOrBuildMaterial(), Acts::UnitConstants::g, gray, G4NistManager::Instance(), mm, mole, and perCent.
void TrentoPassiveProtonBeamLine::SetPreCollimatorXPosition (G4double value)
Definition at line 908 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 908 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and mm.
void TrentoPassiveProtonBeamLine::SetPreCollimatorXSize (G4double value)
Definition at line 899 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 899 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and mm.
void TrentoPassiveProtonBeamLine::SetScattererMaterial (G4String materialChoice)
Definition at line 936 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 936 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, G4NistManager::Instance(), and EmPlot::SetMaterial().
void TrentoPassiveProtonBeamLine::SetScatteringFoilXSize (G4double value)
Definition at line 889 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc.
View newest version in sPHENIX GitHub at line 889 of file HadrontherapyTIFPAPassiveProtonBeamLine.cc
References G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and mm.
Member Data Documentation
G4Material* TrentoPassiveProtonBeamLine::airgapMaterial private
Definition at line 177 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 177 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::airgapPV private
Definition at line 140 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 140 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::airTube2Material private
Definition at line 183 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 183 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::airTube3Material private
Definition at line 184 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 184 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::airTubeMaterial private
Definition at line 182 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 182 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::beamLineSupportMaterial private
Definition at line 171 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 171 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::blue private
Definition at line 161 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 161 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Box* TrentoPassiveProtonBeamLine::Collimator private
Definition at line 151 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 151 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::CollimatorMaterial private
Definition at line 180 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 180 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::darkGreen private
Definition at line 167 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 167 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::darkOrange3 private
Definition at line 168 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 168 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::firstFoilPV private
Definition at line 138 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 138 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::FoilMaterial private
Definition at line 175 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 175 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::gray private
Definition at line 162 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 162 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::green private
Definition at line 166 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 166 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
HadrontherapyDetectorConstruction* TrentoPassiveProtonBeamLine::hadrontherapyDetectorConstruction private
Definition at line 110 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 110 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
Referenced by ~TrentoPassiveProtonBeamLine().
TrentoPassiveProtonBeamLine* TrentoPassiveProtonBeamLine::instance static private
Definition at line 101 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 101 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::internalMonitorStructurePV private
Definition at line 137 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 137 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::internalStructureMaterial private
Definition at line 176 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 176 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::kapton private
Definition at line 113 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 113 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::layerDefaultMaterial private
Definition at line 174 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 174 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::layerMonitorChamberMaterial private
Definition at line 173 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 173 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4LogicalVolume* TrentoPassiveProtonBeamLine::logicScatteringFoil private
Definition at line 143 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 143 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4LogicalVolume* TrentoPassiveProtonBeamLine::logicTreatmentRoom private
Definition at line 108 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 108 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::mother private
Definition at line 157 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 157 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiAirPreTube private
Definition at line 159 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 159 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiAirTube private
Definition at line 158 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 158 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiBeamLineCover private
Definition at line 131 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 131 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiBeamLineCover2 private
Definition at line 132 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 132 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiBeamLineSupport private
Definition at line 130 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 130 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physicalTreatmentRoom private
Definition at line 109 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 109 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiCollimator private
Definition at line 152 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 152 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiMonitorLayer1 private
Definition at line 134 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 134 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiMonitorLayer2 private
Definition at line 135 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 135 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiPreCollimator private
Definition at line 149 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 149 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::physiScatteringFoil private
Definition at line 144 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 144 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Box* TrentoPassiveProtonBeamLine::preCollimator private
Definition at line 148 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 148 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::preCollimatorMaterial private
Definition at line 181 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 181 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::preCollimatorXHalfSide private
Definition at line 122 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 122 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::preCollimatorXPosition private
Definition at line 123 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 123 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::preCollimatorYPosition private
Definition at line 124 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 124 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::preCollimatorZPosition private
Definition at line 125 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 125 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::red private
Definition at line 164 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 164 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::ridgeFilterMaterial private
Definition at line 185 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 185 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::ridgeFilterPhys private
Definition at line 146 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 146 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
HadrontherapyDetectorROGeometry* TrentoPassiveProtonBeamLine::RO private
Definition at line 187 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 187 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
Referenced by TrentoPassiveProtonBeamLine().
G4Box* TrentoPassiveProtonBeamLine::ScatteringFoil private
Definition at line 142 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 142 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::ScatteringFoilMaterial private
Definition at line 178 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 178 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ScatteringFoilXPosition private
Definition at line 118 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 118 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ScatteringFoilXSize private
Definition at line 115 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 115 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ScatteringFoilYPosition private
Definition at line 119 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 119 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ScatteringFoilYSize private
Definition at line 116 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 116 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ScatteringFoilZPosition private
Definition at line 120 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 120 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ScatteringFoilZSize private
Definition at line 117 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 117 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VPhysicalVolume* TrentoPassiveProtonBeamLine::secondFoilPV private
Definition at line 139 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 139 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Material* TrentoPassiveProtonBeamLine::singleTrapMaterial private
Definition at line 179 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 179 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::skyBlue private
Definition at line 169 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 169 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Box* TrentoPassiveProtonBeamLine::solidAirPreTube private
Definition at line 155 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 155 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4Box* TrentoPassiveProtonBeamLine::solidAirTube private
Definition at line 154 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 154 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
TrentoPassiveProtonBeamLineMessenger* TrentoPassiveProtonBeamLine::TrentoPassiveMessenger private
Definition at line 107 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 107 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
Referenced by TrentoPassiveProtonBeamLine(), and ~TrentoPassiveProtonBeamLine().
G4Material* TrentoPassiveProtonBeamLine::vacuumZoneMaterial private
Definition at line 172 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 172 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::white private
Definition at line 163 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 163 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4VisAttributes* TrentoPassiveProtonBeamLine::yellow private
Definition at line 165 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 165 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::YHalfSideAirTube private
Definition at line 127 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 127 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
G4double TrentoPassiveProtonBeamLine::ZHalfSideAirTube private
Definition at line 128 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh.
View newest version in sPHENIX GitHub at line 128 of file HadrontherapyTIFPAPassiveProtonBeamLine.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyTIFPAPassiveProtonBeamLine.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyTIFPAPassiveProtonBeamLine.cc