ECCE @ EIC Software: ECCEFastPIDReco Class Reference
ECCEFastPIDReco Class Reference
#include <ecce-detectors/blob/master/FastPID/ECCEFastPIDReco.h>
Public Member Functions
ECCEFastPIDReco (ECCEFastPIDMap *map, EICPIDDefs::PIDDetector det, const std::string &name="ECCEFastPIDReco")
virtual ~ECCEFastPIDReco ()
int Init (PHCompositeNode *topNode) override
int InitRun (PHCompositeNode *topNode) override
int process_event (PHCompositeNode *topNode) override
int End (PHCompositeNode *topNode) override
Called at the end of all processing.
void setTrackmapNodeName (const std::string &name)
void setEICPIDParticleMapNodeName (const std::string &name)
void setMatchG4Hit (const std::string &g4hit_node_name)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
bool m_matchG4Hit = false
std::string m_G4HitNodeName = "Uninitialized"
ECCEFastPIDMap * m_pidmap
EICPIDDefs::PIDDetector m_PIDDetector
std::string m_TrackmapNodeName = "TrackMap"
std::string m_EICPIDParticleMapNodeName = "EICPIDParticleMap"
SvtxTrackMap * m_SvtxTrackMap = nullptr
EICPIDParticleContainer * m_EICPIDParticleContainer = nullptr
PHG4TruthInfoContainer * m_truthInfo = nullptr
PHG4HitContainer * m_g4hits = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 19 of file ECCEFastPIDReco.h
Constructor & Destructor Documentation
ECCEFastPIDReco::ECCEFastPIDReco (ECCEFastPIDMap * map, EICPIDDefs::PIDDetector det, const std::string & name = "ECCEFastPIDReco")
Definition at line 37 of file ECCEFastPIDReco.cc.
View newest version in sPHENIX GitHub at line 37 of file ECCEFastPIDReco.cc
References g4zmq::exit().
ECCEFastPIDReco::~ECCEFastPIDReco () virtual
Definition at line 50 of file ECCEFastPIDReco.cc.
View newest version in sPHENIX GitHub at line 50 of file ECCEFastPIDReco.cc
References m_pidmap.
Member Function Documentation
int ECCEFastPIDReco::End (PHCompositeNode * topNode) override virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 253 of file ECCEFastPIDReco.cc.
View newest version in sPHENIX GitHub at line 253 of file ECCEFastPIDReco.cc
References Fun4AllReturnCodes::EVENT_OK.
int ECCEFastPIDReco::Init (PHCompositeNode * topNode) override virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 56 of file ECCEFastPIDReco.cc.
View newest version in sPHENIX GitHub at line 56 of file ECCEFastPIDReco.cc
References Fun4AllReturnCodes::EVENT_OK.
int ECCEFastPIDReco::InitRun (PHCompositeNode * topNode) override virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number. A place to book histograms which have to know the run number.
G4 truth particle node
Reimplemented from SubsysReco.
Definition at line 66 of file ECCEFastPIDReco.cc.
View newest version in sPHENIX GitHub at line 66 of file ECCEFastPIDReco.cc
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, m_EICPIDParticleContainer, m_EICPIDParticleMapNodeName, m_G4HitNodeName, m_g4hits, m_matchG4Hit, m_SvtxTrackMap, m_TrackmapNodeName, m_truthInfo, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
int ECCEFastPIDReco::process_event (PHCompositeNode * topNode) override virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 118 of file ECCEFastPIDReco.cc.
View newest version in sPHENIX GitHub at line 118 of file ECCEFastPIDReco.cc
References Fun4AllReturnCodes::EVENT_OK, EICPIDParticleContainer::findOrAddPIDParticle(), SvtxTrack_v1::get_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), SvtxTrack_FastSim::get_truth_track_id(), ECCEFastPIDMap::getFastSmearLogLikelihood(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetParticle(), PHG4Particle::identify(), SvtxTrackMap::identify(), EICPIDParticle::identify(), PHG4Hit::identify(), EICPIDParticleContainer::identify(), SvtxTrack_FastSim::identify(), SvtxTrack::identify(), m_EICPIDParticleContainer, m_G4HitNodeName, m_g4hits, m_matchG4Hit, m_PIDDetector, m_pidmap, m_SvtxTrackMap, m_truthInfo, momentum, Fun4AllBase::Name(), EICPIDParticle::set_LogLikelyhood(), EICPIDParticle::set_property(), track, EICPIDParticle::Truth_eta, EICPIDParticle::Truth_momentum, EICPIDParticle::Truth_PID, and Fun4AllBase::Verbosity().
void ECCEFastPIDReco::setEICPIDParticleMapNodeName (const std::string & name) inline
Definition at line 52 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 52 of file ECCEFastPIDReco.h
References m_EICPIDParticleMapNodeName.
void ECCEFastPIDReco::setMatchG4Hit (const std::string & g4hit_node_name) inline
Definition at line 56 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 56 of file ECCEFastPIDReco.h
References m_G4HitNodeName, and m_matchG4Hit.
Referenced by DIRCReco().
void ECCEFastPIDReco::setTrackmapNodeName (const std::string & name) inline
Definition at line 48 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 48 of file ECCEFastPIDReco.h
References m_TrackmapNodeName.
Member Data Documentation
EICPIDParticleContainer* ECCEFastPIDReco::m_EICPIDParticleContainer = nullptr private
Definition at line 73 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 73 of file ECCEFastPIDReco.h
Referenced by InitRun(), and process_event().
std::string ECCEFastPIDReco::m_EICPIDParticleMapNodeName = "EICPIDParticleMap" private
Definition at line 70 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 70 of file ECCEFastPIDReco.h
Referenced by InitRun(), and setEICPIDParticleMapNodeName().
std::string ECCEFastPIDReco::m_G4HitNodeName = "Uninitialized" private
Definition at line 64 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 64 of file ECCEFastPIDReco.h
Referenced by InitRun(), process_event(), and setMatchG4Hit().
PHG4HitContainer* ECCEFastPIDReco::m_g4hits = nullptr private
Definition at line 75 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 75 of file ECCEFastPIDReco.h
Referenced by InitRun(), and process_event().
bool ECCEFastPIDReco::m_matchG4Hit = false private
Definition at line 62 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 62 of file ECCEFastPIDReco.h
Referenced by InitRun(), process_event(), and setMatchG4Hit().
EICPIDDefs::PIDDetector ECCEFastPIDReco::m_PIDDetector private
Definition at line 67 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 67 of file ECCEFastPIDReco.h
Referenced by process_event().
ECCEFastPIDMap* ECCEFastPIDReco::m_pidmap private
Definition at line 66 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 66 of file ECCEFastPIDReco.h
Referenced by process_event(), and ~ECCEFastPIDReco().
SvtxTrackMap* ECCEFastPIDReco::m_SvtxTrackMap = nullptr private
Definition at line 72 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 72 of file ECCEFastPIDReco.h
Referenced by InitRun(), and process_event().
std::string ECCEFastPIDReco::m_TrackmapNodeName = "TrackMap" private
Definition at line 69 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 69 of file ECCEFastPIDReco.h
Referenced by InitRun(), and setTrackmapNodeName().
PHG4TruthInfoContainer* ECCEFastPIDReco::m_truthInfo = nullptr private
Definition at line 74 of file ECCEFastPIDReco.h.
View newest version in sPHENIX GitHub at line 74 of file ECCEFastPIDReco.h
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
ecce-detectors/blob/master/FastPID/ECCEFastPIDReco.h
ecce-detectors/blob/master/FastPID/ECCEFastPIDReco.cc