ECCE @ EIC Software: G4BlineTracer Class Reference
G4BlineTracer Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlineTracer.hh>
Public Member Functions
G4BlineTracer ()
virtual ~G4BlineTracer ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void EndOfRunAction (const G4Run *aRun)
void ComputeBlines (G4int nlines)
void SetMaxTrackingStep (G4double max_step)
G4BlineEventAction * GetEventAction ()
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Member Functions
void ResetChordFinders ()
Private Attributes
G4BlineTracerMessenger * fMessenger
G4BlineSteppingAction * fSteppingAction
G4BlineEventAction * fEventAction
G4BlinePrimaryGeneratorAction * fPrimaryGeneratorAction
G4double fMaxTrackingStep
G4bool fWas_ResetChordFinders_already_called
std::vector< G4ChordFinder * > fVecChordFinders
std::vector< G4FieldManager * > fVecFieldManagers
std::vector< G4MagneticField * > fVecMagneticFields
std::vector< G4BlineEquation * > fVecEquationOfMotion
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 66 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BlineTracer.hh
Constructor & Destructor Documentation
G4BlineTracer::G4BlineTracer ()
Definition at line 60 of file G4BlineTracer.cc.
View newest version in sPHENIX GitHub at line 60 of file G4BlineTracer.cc
References fEventAction, fMaxTrackingStep, fMessenger, fPrimaryGeneratorAction, fSteppingAction, fWas_ResetChordFinders_already_called, and m.
G4BlineTracer::~G4BlineTracer () virtual
Definition at line 72 of file G4BlineTracer.cc.
View newest version in sPHENIX GitHub at line 72 of file G4BlineTracer.cc
References fEventAction, fMessenger, fPrimaryGeneratorAction, fSteppingAction, fVecChordFinders, and fVecEquationOfMotion.
Member Function Documentation
void G4BlineTracer::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 87 of file G4BlineTracer.cc.
View newest version in sPHENIX GitHub at line 87 of file G4BlineTracer.cc
void G4BlineTracer::ComputeBlines (G4int nlines)
Definition at line 99 of file G4BlineTracer.cc.
View newest version in sPHENIX GitHub at line 99 of file G4BlineTracer.cc
References G4RunManager::BeamOn(), fEventAction, fMaxTrackingStep, fPrimaryGeneratorAction, fSteppingAction, fVecChordFinders, fVecEquationOfMotion, fVecFieldManagers, fWas_ResetChordFinders_already_called, G4PropagatorInField::GetLargestAcceptableStep(), G4TransportationManager::GetPropagatorInField(), G4RunManager::GetRunManager(), G4TransportationManager::GetTransportationManager(), G4RunManager::GetUserEventAction(), G4RunManager::GetUserPrimaryGeneratorAction(), G4RunManager::GetUserRunAction(), G4RunManager::GetUserStackingAction(), G4RunManager::GetUserSteppingAction(), G4RunManager::GetUserTrackingAction(), ResetChordFinders(), G4PropagatorInField::SetLargestAcceptableStep(), G4RunManager::SetUserAction(), and G4BlinePrimaryGeneratorAction::SetUserPrimaryAction().
Referenced by G4BlineTracerMessenger::SetNewValue().
void G4BlineTracer::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 93 of file G4BlineTracer.cc.
View newest version in sPHENIX GitHub at line 93 of file G4BlineTracer.cc
G4BlineEventAction* G4BlineTracer::GetEventAction (void) inline
Definition at line 80 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 80 of file G4BlineTracer.hh
References fEventAction.
Referenced by G4BlineTracerMessenger::SetNewValue().
void G4BlineTracer::ResetChordFinders () private
Definition at line 271 of file G4BlineTracer.cc.
View newest version in sPHENIX GitHub at line 271 of file G4BlineTracer.cc
References fVecChordFinders, fVecEquationOfMotion, fVecFieldManagers, fVecMagneticFields, G4LogicalVolumeStore::GetInstance(), G4MagIntegratorStepper::GetNumberOfVariables(), G4TransportationManager::GetTransportationManager(), and mm.
Referenced by ComputeBlines().
void G4BlineTracer::SetMaxTrackingStep (G4double max_step) inline
Definition at line 78 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BlineTracer.hh
References fMaxTrackingStep.
Referenced by G4BlineTracerMessenger::SetNewValue().
Member Data Documentation
G4BlineEventAction* G4BlineTracer::fEventAction private
Definition at line 91 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BlineTracer.hh
Referenced by ComputeBlines(), G4BlineTracer(), GetEventAction(), and ~G4BlineTracer().
G4double G4BlineTracer::fMaxTrackingStep private
Definition at line 93 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BlineTracer.hh
Referenced by ComputeBlines(), G4BlineTracer(), and SetMaxTrackingStep().
G4BlineTracerMessenger* G4BlineTracer::fMessenger private
Definition at line 89 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BlineTracer.hh
Referenced by G4BlineTracer(), and ~G4BlineTracer().
G4BlinePrimaryGeneratorAction* G4BlineTracer::fPrimaryGeneratorAction private
Definition at line 92 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BlineTracer.hh
Referenced by ComputeBlines(), G4BlineTracer(), and ~G4BlineTracer().
G4BlineSteppingAction* G4BlineTracer::fSteppingAction private
Definition at line 90 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BlineTracer.hh
Referenced by ComputeBlines(), G4BlineTracer(), and ~G4BlineTracer().
std::vector<G4ChordFinder* > G4BlineTracer::fVecChordFinders private
Definition at line 99 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 99 of file G4BlineTracer.hh
Referenced by ComputeBlines(), ResetChordFinders(), and ~G4BlineTracer().
std::vector<G4BlineEquation* > G4BlineTracer::fVecEquationOfMotion private
Definition at line 102 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 102 of file G4BlineTracer.hh
Referenced by ComputeBlines(), ResetChordFinders(), and ~G4BlineTracer().
std::vector<G4FieldManager* > G4BlineTracer::fVecFieldManagers private
Definition at line 100 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 100 of file G4BlineTracer.hh
Referenced by ComputeBlines(), and ResetChordFinders().
std::vector<G4MagneticField* > G4BlineTracer::fVecMagneticFields private
Definition at line 101 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 101 of file G4BlineTracer.hh
Referenced by ResetChordFinders().
G4bool G4BlineTracer::fWas_ResetChordFinders_already_called private
Definition at line 94 of file G4BlineTracer.hh.
View newest version in sPHENIX GitHub at line 94 of file G4BlineTracer.hh
Referenced by ComputeBlines(), and G4BlineTracer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlineTracer.hh
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/src/G4BlineTracer.cc