ECCE @ EIC Software: G4PhysChemIO::FormattedText Class Reference
G4PhysChemIO::FormattedText Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4PhysChemIO.hh>
Public Member Functions
FormattedText ()
virtual ~FormattedText ()
virtual void InitializeMaster ()
virtual void InitializeThread ()
virtual void InitializeFile ()
virtual void NewRun ()
virtual void NewEvent ()
virtual void CreateWaterMolecule (G4int electronicModif, G4int, G4double energy, const G4Track *)
virtual void CreateSolvatedElectron (const G4Track *, G4ThreeVector *finalPosition=0)
virtual void WriteInto (const G4String &, std::ios_base::openmode mode=std::ios_base::out)
virtual void AddEmptyLineInOutputFile ()
virtual void CloseFile ()
Public Member Functions inherited from G4VPhysChemIO
G4VPhysChemIO ()
virtual ~G4VPhysChemIO ()
Protected Attributes
G4int fRunID
G4int fEventID
G4bool fFileInitialized
std::ofstream fOfstream
Detailed Description
Definition at line 40 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 40 of file G4PhysChemIO.hh
Constructor & Destructor Documentation
G4PhysChemIO::FormattedText::FormattedText ()
Definition at line 44 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 44 of file G4PhysChemIO.cc
G4PhysChemIO::FormattedText::~FormattedText () virtual
Definition at line 52 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PhysChemIO.cc
Member Function Documentation
void G4PhysChemIO::FormattedText::AddEmptyLineInOutputFile () virtual
Reimplemented from G4VPhysChemIO.
Definition at line 89 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 89 of file G4PhysChemIO.cc
References G4endl.
void G4PhysChemIO::FormattedText::CloseFile () virtual
Close the file specified with WriteInto
Implements G4VPhysChemIO.
Definition at line 96 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 96 of file G4PhysChemIO.cc
void G4PhysChemIO::FormattedText::CreateSolvatedElectron (const G4Track * theIncomingTrack, G4ThreeVector * finalPosition = 0) virtual
Same idea as the previous method but for solvated electron. This method should be used by the physics model of the ElectronSolvatation process.
Implements G4VPhysChemIO.
Definition at line 131 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 131 of file G4PhysChemIO.cc
References eV, G4endl, G4Track::GetKineticEnergy(), G4Track::GetPosition(), G4Track::GetTrackID(), nanometer, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4PhysChemIO::FormattedText::CreateWaterMolecule (G4int electronicModif, G4int electronicLevel, G4double energy, const G4Track * theIncomingTrack) virtual
When DNA physics model create a water molecule, you'll get a notification through this method. The ElectronicModification is a flag telling whether the molecule is ionized or excited, the electronic level is calculated by the model and the IncomingTrack is the track responsible for the creation of this molecule (electron, proton...)
Implements G4VPhysChemIO.
Definition at line 108 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 108 of file G4PhysChemIO.cc
References eV, G4endl, G4Track::GetPosition(), G4Track::GetTrackID(), left, nanometer, right, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4PhysChemIO::FormattedText::InitializeFile () virtual
Implements G4VPhysChemIO.
Definition at line 58 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PhysChemIO.cc
References G4endl, and left.
virtual void G4PhysChemIO::FormattedText::InitializeMaster () inline virtual
Reimplemented from G4VPhysChemIO.
Definition at line 46 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 46 of file G4PhysChemIO.hh
virtual void G4PhysChemIO::FormattedText::InitializeThread () inline virtual
Reimplemented from G4VPhysChemIO.
Definition at line 47 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PhysChemIO.hh
virtual void G4PhysChemIO::FormattedText::NewEvent () inline virtual
Implements G4VPhysChemIO.
Definition at line 51 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PhysChemIO.hh
virtual void G4PhysChemIO::FormattedText::NewRun () inline virtual
Implements G4VPhysChemIO.
Definition at line 50 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 50 of file G4PhysChemIO.hh
void G4PhysChemIO::FormattedText::WriteInto (const G4String & , std::ios_base::openmode mode = std::ios_base::out) virtual
Tells the chemistry manager to write into a file the position and electronic state of the water molecule and the position thermalized or not of the solvated electron
Implements G4VPhysChemIO.
Definition at line 80 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 80 of file G4PhysChemIO.cc
References G4String::data().
Member Data Documentation
G4int G4PhysChemIO::FormattedText::fEventID protected
Definition at line 94 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PhysChemIO.hh
G4bool G4PhysChemIO::FormattedText::fFileInitialized protected
Definition at line 95 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PhysChemIO.hh
std::ofstream G4PhysChemIO::FormattedText::fOfstream protected
Definition at line 96 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 96 of file G4PhysChemIO.hh
G4int G4PhysChemIO::FormattedText::fRunID protected
Definition at line 93 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PhysChemIO.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4PhysChemIO.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4PhysChemIO.cc