ECCE @ EIC Software: G4GEMProbabilityVI Class Reference
G4GEMProbabilityVI Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMProbabilityVI.hh>
Public Member Functions
G4GEMProbabilityVI (G4int anA, G4int aZ, const G4LevelManager *)
~G4GEMProbabilityVI () final
G4double ComputeTotalProbability (const G4Fragment &, G4double CB)
G4double ComputeProbability (G4double ekin, G4double CB) override
G4Fragment * SampleEvaporationFragment ()
Public Member Functions inherited from G4VEmissionProbability
G4VEmissionProbability (G4int Z, G4int A)
virtual ~G4VEmissionProbability ()
void Initialise ()
virtual G4double EmissionProbability (const G4Fragment &fragment, G4double anEnergy)
G4int GetZ (void) const
G4int GetA (void) const
void SetDecayKinematics (G4int Z, G4int A, G4double rmass, G4double fmass)
G4double GetRecoilExcitation () const
void SetEvapExcitation (G4double exc)
G4double GetProbability () const
void ResetProbability ()
G4double SampleEnergy ()
Private Member Functions
G4double Integrated2DProbability ()
G4double ProbabilityDistributionFunction (G4double exc, G4double resExc)
G4Fragment * Sample2DDistribution ()
G4double I0 (G4double t)
G4double I1 (G4double t, G4double tx)
G4double I2 (G4double s0, G4double sx)
G4double I3 (G4double s0, G4double sx)
G4GEMProbabilityVI (const G4GEMProbabilityVI &right)
const G4GEMProbabilityVI & operator= (const G4GEMProbabilityVI &right)
G4bool operator== (const G4GEMProbabilityVI &right) const
G4bool operator!= (const G4GEMProbabilityVI &right) const
Private Attributes
const G4LevelManager * lManager
G4int fragA
G4int fragZ
G4double bCoulomb
G4double resA13
G4double U
G4double delta0
G4double delta1
G4double a0
G4double a1
G4double alphaP
G4double betaP
G4double Umax
G4double A13
G4double Gamma
G4double coeff
G4double pcoeff
G4double probmax
G4bool isExcited
Additional Inherited Members
Protected Member Functions inherited from G4VEmissionProbability
void ResetIntegrator (size_t nbin, G4double de, G4double eps)
G4double IntegrateProbability (G4double elow, G4double ehigh, G4double CB)
Protected Attributes inherited from G4VEmissionProbability
G4int OPTxs
G4int pVerbose
G4int theZ
G4int theA
G4int resZ
G4int resA
G4double pMass
G4double pEvapMass
G4double pResMass
G4double pProbability
G4NuclearLevelData * pNuclearLevelData
G4Pow * pG4pow
Detailed Description
Definition at line 38 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 38 of file G4GEMProbabilityVI.hh
Constructor & Destructor Documentation
G4GEMProbabilityVI::G4GEMProbabilityVI (G4int anA, G4int aZ, const G4LevelManager * p) explicit
Definition at line 69 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 69 of file G4GEMProbabilityVI.cc
References a0, a1, A13, alphaP, bCoulomb, betaP, coeff, delta0, delta1, CLHEP::fermi, fragA, fragZ, Gamma, CLHEP::hbarc, isExcited, lManager, G4LevelManager::MaxLevelEnergy(), CLHEP::MeV, CLHEP::millibarn, pcoeff, G4VEmissionProbability::pEvapMass, G4VEmissionProbability::pG4pow, CLHEP::pi, probmax, resA13, G4VEmissionProbability::ResetIntegrator(), G4VEmissionProbability::theA, U, Umax, and G4Pow::Z13().
G4GEMProbabilityVI::~G4GEMProbabilityVI () final
Definition at line 90 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 90 of file G4GEMProbabilityVI.cc
G4GEMProbabilityVI::G4GEMProbabilityVI (const G4GEMProbabilityVI & right) private
Member Function Documentation
G4double G4GEMProbabilityVI::ComputeProbability (G4double ekin, G4double CB) override virtual
Reimplemented from G4VEmissionProbability.
Definition at line 151 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 151 of file G4GEMProbabilityVI.cc
References a1, G4NuclearLevelData::GetLevelDensity(), max, G4VEmissionProbability::pEvapMass, G4VEmissionProbability::pMass, G4VEmissionProbability::pNuclearLevelData, G4VEmissionProbability::pResMass, ProbabilityDistributionFunction(), G4VEmissionProbability::resA, and G4VEmissionProbability::resZ.
G4double G4GEMProbabilityVI::ComputeTotalProbability (const G4Fragment & fragment, G4double CB)
Definition at line 93 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 93 of file G4GEMProbabilityVI.cc
References a0, alphaP, bCoulomb, betaP, C(), delta0, delta1, e, ekinmin, fragA, fragZ, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4NuclearLevelData::GetPairingCorrection(), G4Fragment::GetZ_asInt(), Integrated2DProbability(), G4VEmissionProbability::IntegrateProbability(), isExcited, max, CLHEP::MeV, G4VEmissionProbability::pEvapMass, G4VEmissionProbability::pG4pow, G4VEmissionProbability::pMass, G4VEmissionProbability::pNuclearLevelData, G4VEmissionProbability::pProbability, G4VEmissionProbability::pResMass, G4VEmissionProbability::resA, resA13, G4VEmissionProbability::resZ, G4VEmissionProbability::theA, G4VEmissionProbability::theZ, U, Umax, G4Pow::Z13(), and Z2.
Referenced by G4GEMChannelVI::GetEmissionProbability().
G4double G4GEMProbabilityVI::I0 (G4double t) private
Definition at line 262 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 262 of file G4GEMProbabilityVI.cc
References G4Exp().
Referenced by ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::I1 (G4double t, G4double tx) private
Definition at line 267 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 267 of file G4GEMProbabilityVI.cc
References G4Exp().
Referenced by ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::I2 (G4double s0, G4double sx) private
Definition at line 272 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 272 of file G4GEMProbabilityVI.cc
References G4Exp(), and S().
Referenced by ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::I3 (G4double s0, G4double sx) private
Definition at line 283 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 283 of file G4GEMProbabilityVI.cc
References G4Exp(), S(), and G4InuclParticleNames::s0.
Referenced by ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::Integrated2DProbability () private
Definition at line 179 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 179 of file G4GEMProbabilityVI.cc
Referenced by ComputeTotalProbability().
G4bool G4GEMProbabilityVI::operator!= (const G4GEMProbabilityVI & right) const private
const G4GEMProbabilityVI& G4GEMProbabilityVI::operator= (const G4GEMProbabilityVI & right) private
G4bool G4GEMProbabilityVI::operator== (const G4GEMProbabilityVI & right) const private
G4double G4GEMProbabilityVI::ProbabilityDistributionFunction (G4double exc, G4double resExc) private
Definition at line 184 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 184 of file G4GEMProbabilityVI.cc
References a0, A13, alphaP, bCoulomb, betaP, delta0, delta1, G4Exp(), G4Log(), I0(), I1(), I2(), I3(), max, CLHEP::MeV, min, G4VEmissionProbability::pEvapMass, G4VEmissionProbability::pMass, G4VEmissionProbability::pResMass, G4VEmissionProbability::resA, resA13, G4InuclParticleNames::s0, T, t, G4VEmissionProbability::theA, G4VEmissionProbability::theZ, x, and x1.
Referenced by ComputeProbability().
G4Fragment * G4GEMProbabilityVI::Sample2DDistribution () private
Definition at line 256 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 256 of file G4GEMProbabilityVI.cc
Referenced by SampleEvaporationFragment().
G4Fragment * G4GEMProbabilityVI::SampleEvaporationFragment ()
Definition at line 169 of file G4GEMProbabilityVI.cc.
View newest version in sPHENIX GitHub at line 169 of file G4GEMProbabilityVI.cc
References G4RandomDirection(), isExcited, G4VEmissionProbability::pEvapMass, Sample2DDistribution(), G4VEmissionProbability::SampleEnergy(), G4VEmissionProbability::theA, and G4VEmissionProbability::theZ.
Referenced by G4GEMChannelVI::EmittedFragment().
Member Data Documentation
G4double G4GEMProbabilityVI::a0 private
Definition at line 81 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::a1 private
Definition at line 81 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GEMProbabilityVI.hh
Referenced by ComputeProbability(), and G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::A13 private
Definition at line 83 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 83 of file G4GEMProbabilityVI.hh
Referenced by G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::alphaP private
Definition at line 82 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 82 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::bCoulomb private
Definition at line 79 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::betaP private
Definition at line 82 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 82 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::coeff private
Definition at line 89 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GEMProbabilityVI.hh
Referenced by G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::delta0 private
Definition at line 81 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::delta1 private
Definition at line 81 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4int G4GEMProbabilityVI::fragA private
Definition at line 76 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), and G4GEMProbabilityVI().
G4int G4GEMProbabilityVI::fragZ private
Definition at line 77 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), and G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::Gamma private
Definition at line 88 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 88 of file G4GEMProbabilityVI.hh
Referenced by G4GEMProbabilityVI().
G4bool G4GEMProbabilityVI::isExcited private
Definition at line 94 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and SampleEvaporationFragment().
const G4LevelManager* G4GEMProbabilityVI::lManager private
Definition at line 74 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GEMProbabilityVI.hh
Referenced by G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::pcoeff private
Definition at line 90 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GEMProbabilityVI.hh
Referenced by G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::probmax private
Definition at line 92 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GEMProbabilityVI.hh
Referenced by G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::resA13 private
Definition at line 80 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 80 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), G4GEMProbabilityVI(), and ProbabilityDistributionFunction().
G4double G4GEMProbabilityVI::U private
Definition at line 81 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), and G4GEMProbabilityVI().
G4double G4GEMProbabilityVI::Umax private
Definition at line 83 of file G4GEMProbabilityVI.hh.
View newest version in sPHENIX GitHub at line 83 of file G4GEMProbabilityVI.hh
Referenced by ComputeTotalProbability(), and G4GEMProbabilityVI().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMProbabilityVI.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/src/G4GEMProbabilityVI.cc