ECCE @ EIC Software: G4FTFPKaonBuilder Class Reference
G4FTFPKaonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPKaonBuilder.hh>
Public Member Functions
G4FTFPKaonBuilder (G4bool quasiElastic=false)
virtual ~G4FTFPKaonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VKaonBuilder
G4VKaonBuilder ()=default
virtual ~G4VKaonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4LundStringFragmentation * theLund
G4double theMin
G4double theMax
Detailed Description
Definition at line 57 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4FTFPKaonBuilder.hh
Constructor & Destructor Documentation
G4FTFPKaonBuilder::G4FTFPKaonBuilder (G4bool quasiElastic = false)
Definition at line 43 of file G4FTFPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 43 of file G4FTFPKaonBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theLund, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFPKaonBuilder::~G4FTFPKaonBuilder () virtual
Definition at line 68 of file G4FTFPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 68 of file G4FTFPKaonBuilder.cc
References theLund, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4FTFPKaonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VKaonBuilder.
Definition at line 63 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4FTFPKaonBuilder.hh
void G4FTFPKaonBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 79 of file G4FTFPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 79 of file G4FTFPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPKaonBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 87 of file G4FTFPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 87 of file G4FTFPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPKaonBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 95 of file G4FTFPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 95 of file G4FTFPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPKaonBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 103 of file G4FTFPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 103 of file G4FTFPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4FTFPKaonBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 70 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4FTFPKaonBuilder.hh
References theMax.
virtual void G4FTFPKaonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 69 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4FTFPKaonBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4FTFPKaonBuilder::theCascade private
Definition at line 76 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FTFPKaonBuilder.hh
Referenced by G4FTFPKaonBuilder().
G4LundStringFragmentation* G4FTFPKaonBuilder::theLund private
Definition at line 80 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FTFPKaonBuilder.hh
Referenced by G4FTFPKaonBuilder(), and ~G4FTFPKaonBuilder().
G4double G4FTFPKaonBuilder::theMax private
Definition at line 83 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FTFPKaonBuilder.hh
Referenced by Build(), G4FTFPKaonBuilder(), and SetMaxEnergy().
G4double G4FTFPKaonBuilder::theMin private
Definition at line 82 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4FTFPKaonBuilder.hh
Referenced by Build(), G4FTFPKaonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFPKaonBuilder::theModel private
Definition at line 75 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FTFPKaonBuilder.hh
Referenced by Build(), and G4FTFPKaonBuilder().
G4QuasiElasticChannel* G4FTFPKaonBuilder::theQuasiElastic private
Definition at line 79 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFPKaonBuilder.hh
Referenced by G4FTFPKaonBuilder(), and ~G4FTFPKaonBuilder().
G4ExcitedStringDecay* G4FTFPKaonBuilder::theStringDecay private
Definition at line 78 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFPKaonBuilder.hh
Referenced by G4FTFPKaonBuilder(), and ~G4FTFPKaonBuilder().
G4FTFModel* G4FTFPKaonBuilder::theStringModel private
Definition at line 77 of file G4FTFPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FTFPKaonBuilder.hh
Referenced by G4FTFPKaonBuilder(), and ~G4FTFPKaonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPKaonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFPKaonBuilder.cc