ECCE @ EIC Software: G4GeometrySampler Class Reference
G4GeometrySampler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4GeometrySampler.hh>
Public Member Functions
G4GeometrySampler (G4VPhysicalVolume *worldvolume, const G4String &particlename)
G4GeometrySampler (G4String worldvolumeName, const G4String &particlename)
virtual ~G4GeometrySampler ()
virtual void PrepareImportanceSampling (G4VIStore *istore, const G4VImportanceAlgorithm *ialg)
virtual void PrepareWeightRoulett (G4double wsurvive, G4double wlimit, G4double isource)
virtual void PrepareWeightWindow (G4VWeightWindowStore *wwstore, G4VWeightWindowAlgorithm *wwAlg, G4PlaceOfAction placeOfAction)
virtual void Configure ()
virtual void AddProcess ()
virtual void ClearSampling ()
virtual G4bool IsConfigured () const
void SetParallel (G4bool paraflag)
void SetWorld (const G4VPhysicalVolume *world)
void SetParticle (const G4String &particlename)
G4String GetParticleName ()
Public Member Functions inherited from G4VSampler
G4VSampler ()
virtual ~G4VSampler ()
Private Member Functions
G4GeometrySampler (const G4GeometrySampler &)
G4GeometrySampler & operator= (const G4GeometrySampler &)
Private Attributes
G4String fParticleName
const G4VPhysicalVolume * fWorld
G4String fWorldName
G4ImportanceConfigurator * fImportanceConfigurator
G4WeightCutOffConfigurator * fWeightCutOffConfigurator
G4VIStore * fIStore
G4WeightWindowConfigurator * fWeightWindowConfigurator
G4VWeightWindowStore * fWWStore
G4bool fIsConfigured
G4Configurators fConfigurators
G4bool paraflag
Detailed Description
Definition at line 52 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 52 of file G4GeometrySampler.hh
Constructor & Destructor Documentation
G4GeometrySampler::G4GeometrySampler (G4VPhysicalVolume * worldvolume, const G4String & particlename) explicit
Definition at line 50 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 50 of file G4GeometrySampler.cc
References paraflag.
G4GeometrySampler::G4GeometrySampler (G4String worldvolumeName, const G4String & particlename) explicit
Definition at line 69 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 69 of file G4GeometrySampler.cc
References fWorld, G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetTransportationManager(), G4Navigator::GetWorldVolume(), and paraflag.
G4GeometrySampler::~G4GeometrySampler () virtual
Definition at line 88 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 88 of file G4GeometrySampler.cc
G4GeometrySampler::G4GeometrySampler (const G4GeometrySampler &) private
Member Function Documentation
void G4GeometrySampler::AddProcess () virtual
Definition at line 286 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 286 of file G4GeometrySampler.cc
References G4VSamplerConfigurator::Configure(), G4WeightCutOffConfigurator::Configure(), fConfigurators, fWeightCutOffConfigurator, and it.
Referenced by B03PhysicsList::AddBiasingProcess(), Configure(), G4ImportanceBiasing::ConstructProcess(), and G4WeightWindowBiasing::ConstructProcess().
void G4GeometrySampler::ClearSampling () virtual
Implements G4VSampler.
Definition at line 93 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 93 of file G4GeometrySampler.cc
References fConfigurators, fImportanceConfigurator, fIsConfigured, fIStore, fWeightCutOffConfigurator, and fWeightWindowConfigurator.
void G4GeometrySampler::Configure () virtual
Implements G4VSampler.
Definition at line 234 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 234 of file G4GeometrySampler.cc
References AddProcess(), fConfigurators, fImportanceConfigurator, fIsConfigured, fWeightWindowConfigurator, G4cout, G4endl, and IsConfigured().
Referenced by B03PhysicsList::AddBiasingProcess(), G4ImportanceBiasing::ConstructProcess(), and G4WeightWindowBiasing::ConstructProcess().
G4String G4GeometrySampler::GetParticleName () inline
Definition at line 83 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 83 of file G4GeometrySampler.hh
References fParticleName.
G4bool G4GeometrySampler::IsConfigured () const virtual
Implements G4VSampler.
Definition at line 125 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 125 of file G4GeometrySampler.cc
References fIsConfigured, G4cout, and G4endl.
Referenced by Configure().
G4GeometrySampler& G4GeometrySampler::operator= (const G4GeometrySampler &) private
void G4GeometrySampler::PrepareImportanceSampling (G4VIStore * istore, const G4VImportanceAlgorithm * ialg) virtual
Implements G4VSampler.
Definition at line 159 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 159 of file G4GeometrySampler.cc
References FatalException, fImportanceConfigurator, fIStore, fParticleName, fWorldName, G4cout, G4endl, G4Exception(), G4VIStore::GetWorldVolume(), paraflag, and G4ImportanceConfigurator::SetWorldName().
Referenced by B03PhysicsList::AddBiasingProcess(), and G4ImportanceBiasing::ConstructProcess().
void G4GeometrySampler::PrepareWeightRoulett (G4double wsurvive, G4double wlimit, G4double isource) virtual
Implements G4VSampler.
Definition at line 180 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 180 of file G4GeometrySampler.cc
References FatalException, fIStore, fParticleName, fWeightCutOffConfigurator, fWorld, G4cout, G4endl, G4Exception(), and paraflag.
void G4GeometrySampler::PrepareWeightWindow (G4VWeightWindowStore * wwstore, G4VWeightWindowAlgorithm * wwAlg, G4PlaceOfAction placeOfAction) virtual
Implements G4VSampler.
Definition at line 211 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 211 of file G4GeometrySampler.cc
References fParticleName, fWeightWindowConfigurator, fWWStore, G4cout, G4endl, G4VWeightWindowStore::GetWorldVolume(), and paraflag.
Referenced by G4WeightWindowBiasing::ConstructProcess().
void G4GeometrySampler::SetParallel (G4bool paraflag) virtual
Implements G4VSampler.
Definition at line 307 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 307 of file G4GeometrySampler.cc
References paraflag.
Referenced by B03PhysicsList::AddBiasingProcess(), G4ImportanceBiasing::ConstructProcess(), G4WeightWindowBiasing::ConstructProcess(), and main().
void G4GeometrySampler::SetParticle (const G4String & particlename)
Definition at line 317 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 317 of file G4GeometrySampler.cc
References fParticleName.
void G4GeometrySampler::SetWorld (const G4VPhysicalVolume * world)
Definition at line 312 of file G4GeometrySampler.cc.
View newest version in sPHENIX GitHub at line 312 of file G4GeometrySampler.cc
References fWorld.
Member Data Documentation
G4Configurators G4GeometrySampler::fConfigurators private
Definition at line 104 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 104 of file G4GeometrySampler.hh
Referenced by AddProcess(), ClearSampling(), and Configure().
G4ImportanceConfigurator* G4GeometrySampler::fImportanceConfigurator private
Definition at line 96 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GeometrySampler.hh
Referenced by ClearSampling(), Configure(), and PrepareImportanceSampling().
G4bool G4GeometrySampler::fIsConfigured private
Definition at line 103 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 103 of file G4GeometrySampler.hh
Referenced by ClearSampling(), Configure(), and IsConfigured().
G4VIStore* G4GeometrySampler::fIStore private
Definition at line 100 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 100 of file G4GeometrySampler.hh
Referenced by ClearSampling(), PrepareImportanceSampling(), and PrepareWeightRoulett().
G4String G4GeometrySampler::fParticleName private
Definition at line 93 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GeometrySampler.hh
Referenced by GetParticleName(), PrepareImportanceSampling(), PrepareWeightRoulett(), PrepareWeightWindow(), and SetParticle().
G4WeightCutOffConfigurator* G4GeometrySampler::fWeightCutOffConfigurator private
Definition at line 99 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 99 of file G4GeometrySampler.hh
Referenced by AddProcess(), ClearSampling(), and PrepareWeightRoulett().
G4WeightWindowConfigurator* G4GeometrySampler::fWeightWindowConfigurator private
Definition at line 101 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GeometrySampler.hh
Referenced by ClearSampling(), Configure(), and PrepareWeightWindow().
const G4VPhysicalVolume* G4GeometrySampler::fWorld private
Definition at line 94 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GeometrySampler.hh
Referenced by G4GeometrySampler(), PrepareWeightRoulett(), and SetWorld().
G4String G4GeometrySampler::fWorldName private
Definition at line 95 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 95 of file G4GeometrySampler.hh
Referenced by PrepareImportanceSampling().
G4VWeightWindowStore* G4GeometrySampler::fWWStore private
Definition at line 102 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 102 of file G4GeometrySampler.hh
Referenced by PrepareWeightWindow().
G4bool G4GeometrySampler::paraflag private
Definition at line 106 of file G4GeometrySampler.hh.
View newest version in sPHENIX GitHub at line 106 of file G4GeometrySampler.hh
Referenced by G4GeometrySampler(), PrepareImportanceSampling(), PrepareWeightRoulett(), PrepareWeightWindow(), and SetParallel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4GeometrySampler.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4GeometrySampler.cc