ECCE @ EIC Software: HepGeom::Vector3D< float > Class Template Reference
HepGeom::Vector3D< float > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Geometry/Vector3D.h>
Public Member Functions
Vector3D ()=default
Vector3D (float x1, float y1, float z1)
Vector3D (const float *a)
Vector3D (const Vector3D< float > &)=default
Vector3D (Vector3D< float > &&)=default
Vector3D (const BasicVector3D< float > &v)
~Vector3D ()=default
Vector3D< float > & operator= (const Vector3D< float > &)=default
Vector3D< float > & operator= (const BasicVector3D< float > &v)
Vector3D< float > & operator= (Vector3D< float > &&)=default
Vector3D< float > & transform (const Transform3D &m)
Public Member Functions inherited from HepGeom::BasicVector3D< float >
BasicVector3D (floatx1, floaty1, floatz1)
BasicVector3D (const BasicVector3D< float > &)=default
BasicVector3D (const BasicVector3D< float > &v)
BasicVector3D (BasicVector3D< float > &&)=default
virtual ~BasicVector3D ()=default
operator float * ()
operator const float * () const
operator CLHEP::Hep3Vector () const
BasicVector3D< float > & operator= (const BasicVector3D< float > &)=default
BasicVector3D< float > & operator= (BasicVector3D< float > &&)=default
BasicVector3D< float > & operator+= (const BasicVector3D< float > &v)
BasicVector3D< float > & operator-= (const BasicVector3D< float > &v)
BasicVector3D< float > & operator*= (double a)
BasicVector3D< float > & operator/= (double a)
float operator() (int i) const
float & operator() (int i)
float operator[] (int i) const
float & operator[] (int i)
float x () const
float y () const
float z () const
void setX (floata)
void setY (floata)
void setZ (floata)
void set (floatx1, floaty1, floatz1)
float perp2 () const
float perp2 (const BasicVector3D< float > &v) const
float perp () const
float perp (const BasicVector3D< float > &v) const
float rho () const
void setPerp (floatrh)
float mag2 () const
float mag () const
float r () const
float phi () const
float theta () const
float cosTheta () const
float getR () const
float getPhi () const
float getTheta () const
void setMag (floatma)
void setR (floatma)
void setPhi (floatph)
void setTheta (floatth)
float pseudoRapidity () const
float eta () const
float getEta () const
void setEta (floata)
float dot (const BasicVector3D< float > &v) const
BasicVector3D< float > cross (const BasicVector3D< float > &v) const
float angle (const BasicVector3D< float > &v) const
BasicVector3D< float > unit () const
BasicVector3D< float > orthogonal () const
BasicVector3D< float > & rotateX (floata)
BasicVector3D< float > & rotateY (floata)
BasicVector3D< float > & rotateZ (floata)
BasicVector3D< float > & rotate (floata, const BasicVector3D< float > &v)
Additional Inherited Members
Public Types inherited from HepGeom::BasicVector3D< float >
enum
Protected Member Functions inherited from HepGeom::BasicVector3D< float >
BasicVector3D ()
Protected Attributes inherited from HepGeom::BasicVector3D< float >
float v_ [3]
Detailed Description
template<>
class HepGeom::Vector3D< float >
Geometrical 3D Vector with components of float type.
Author
Evgeni Chernyaev Evgue.nosp@m.ni.T.nosp@m.chern.nosp@m.iaev.nosp@m.@cern.nosp@m..ch
Definition at line 42 of file Vector3D.h.
View newest version in sPHENIX GitHub at line 42 of file Vector3D.h
Constructor & Destructor Documentation
HepGeom::Vector3D< float >::Vector3D () default
Default constructor.
HepGeom::Vector3D< float >::Vector3D (float x1, float y1, float z1) inline
Constructor from three numbers.
Definition at line 50 of file Vector3D.h.
View newest version in sPHENIX GitHub at line 50 of file Vector3D.h
HepGeom::Vector3D< float >::Vector3D (const float * a) inline explicit
Constructor from array of floats.
Definition at line 54 of file Vector3D.h.
View newest version in sPHENIX GitHub at line 54 of file Vector3D.h
HepGeom::Vector3D< float >::Vector3D (const Vector3D< float > &) default
Copy constructor.
HepGeom::Vector3D< float >::Vector3D (Vector3D< float > &&) default
Move constructor.
HepGeom::Vector3D< float >::Vector3D (const BasicVector3D< float > & v) inline
Constructor from BasicVector3D<float>.
Definition at line 67 of file Vector3D.h.
View newest version in sPHENIX GitHub at line 67 of file Vector3D.h
HepGeom::Vector3D< float >::~Vector3D () default
Destructor.
Member Function Documentation
Vector3D<float>& HepGeom::Vector3D< float >::operator= (const Vector3D< float > &) default
Assignment.
Vector3D<float>& HepGeom::Vector3D< float >::operator= (const BasicVector3D< float > & v) inline
Assignment from BasicVector3D<float>.
Definition at line 79 of file Vector3D.h.
View newest version in sPHENIX GitHub at line 79 of file Vector3D.h
References HepGeom::BasicVector3D< T >::operator=().
Vector3D<float>& HepGeom::Vector3D< float >::operator= (Vector3D< float > &&) default
Move assignment.
Vector3D< float > & HepGeom::Vector3D< float >::transform (const Transform3D & m)
Transformation by Transform3D.
Definition at line 10 of file Vector3D.cc.
View newest version in sPHENIX GitHub at line 10 of file Vector3D.cc
References HepGeom::BasicVector3D< T >::x(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), and HepGeom::Transform3D::zz().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Geometry/Vector3D.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/Vector3D.cc