ECCE @ EIC Software: Materials Class Reference
Materials Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/Materials.hh>
Public Member Functions
Materials ()
~Materials ()
G4Material * GetMaterial (const G4String &)
Materials ()
~Materials ()
void Construct ()
Static Public Member Functions
static Materials * GetInstance ()
Private Member Functions
void Initialise ()
Static Private Attributes
static Materials * fgInstance = 0
Detailed Description
Definition at line 48 of file Materials.hh.
View newest version in sPHENIX GitHub at line 48 of file Materials.hh
Constructor & Destructor Documentation
Materials::Materials ()
Definition at line 60 of file Materials.cc.
View newest version in sPHENIX GitHub at line 60 of file Materials.cc
References fgInstance, and Initialise().
Referenced by GetInstance().
Materials::~Materials ()
Definition at line 66 of file Materials.cc.
View newest version in sPHENIX GitHub at line 66 of file Materials.cc
Materials::Materials ()
Materials::~Materials ()
Member Function Documentation
void Materials::Construct (void)
Definition at line 46 of file Materials.cc.
View newest version in sPHENIX GitHub at line 46 of file Materials.cc
References A(), cm3, Acts::UnitConstants::g, kelvin, kStateGas, mole, G4DRCALO::SETTING::Quartz, source.hepunit::STP_Temperature, source.hepunit::universe_mean_density, and Z.
Materials * Materials::GetInstance (void) static
Definition at line 51 of file Materials.cc.
View newest version in sPHENIX GitHub at line 51 of file Materials.cc
References fgInstance, and Materials().
Referenced by DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), and DetectorBari05::Construct().
G4Material * Materials::GetMaterial (const G4String & name)
Definition at line 459 of file Materials.cc.
View newest version in sPHENIX GitHub at line 459 of file Materials.cc
References G4cout, G4endl, G4Material::GetMaterial(), and G4Material::GetName().
Referenced by DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), and DetectorBari05::Construct().
void Materials::Initialise () private
Definition at line 69 of file Materials.cc.
View newest version in sPHENIX GitHub at line 69 of file Materials.cc
References a, G4Material::AddElement(), G4Material::AddMaterial(), atmosphere, cm3, Acts::UnitConstants::g, kelvin, kStateGas, mg, mole, and z.
Referenced by Materials().
Member Data Documentation
Materials * Materials::fgInstance = 0 static private
Definition at line 62 of file Materials.hh.
View newest version in sPHENIX GitHub at line 62 of file Materials.hh
Referenced by GetInstance(), and Materials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/Materials.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI01/include/Materials.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/Materials.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI01/src/Materials.cc