ECCE @ EIC Software: G4ProductionCutsTable Class Reference
G4ProductionCutsTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4ProductionCutsTable.hh>
Public Member Functions
virtual ~G4ProductionCutsTable ()
void UpdateCoupleTable (G4VPhysicalVolume *currentWorld)
void SetEnergyRange (G4double lowedge, G4double highedge)
G4double GetLowEdgeEnergy () const
G4double GetHighEdgeEnergy () const
G4double GetMaxEnergyCut ()
void SetMaxEnergyCut (G4double value)
void DumpCouples () const
const G4MCCIndexConversionTable * GetMCCIndexConversionTable () const
const std::vector< G4double > * GetRangeCutsVector (size_t pcIdx) const
const std::vector< G4double > * GetEnergyCutsVector (size_t pcIdx) const
G4double * GetRangeCutsDoubleVector (size_t pcIdx) const
G4double * GetEnergyCutsDoubleVector (size_t pcIdx) const
size_t GetTableSize () const
const G4MaterialCutsCouple * GetMaterialCutsCouple (G4int i) const
const G4MaterialCutsCouple * GetMaterialCutsCouple (const G4Material *aMat, const G4ProductionCuts *aCut) const
G4int GetCoupleIndex (const G4MaterialCutsCouple *aCouple) const
G4int GetCoupleIndex (const G4Material *aMat, const G4ProductionCuts *aCut) const
G4bool IsModified () const
void PhysicsTableUpdated ()
G4ProductionCuts * GetDefaultProductionCuts () const
G4double ConvertRangeToEnergy (const G4ParticleDefinition *particle, const G4Material *material, G4double range)
void ResetConverters ()
G4bool StoreCutsTable (const G4String &directory, G4bool ascii=false)
G4bool RetrieveCutsTable (const G4String &directory, G4bool ascii=false)
G4bool CheckForRetrieveCutsTable (const G4String &directory, G4bool ascii=false)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Static Public Member Functions
static G4ProductionCutsTable * GetProductionCutsTable ()
Protected Member Functions
G4ProductionCutsTable ()
virtual G4bool StoreMaterialInfo (const G4String &directory, G4bool ascii=false)
virtual G4bool CheckMaterialInfo (const G4String &directory, G4bool ascii=false)
virtual G4bool StoreMaterialCutsCoupleInfo (const G4String &directory, G4bool ascii=false)
virtual G4bool CheckMaterialCutsCoupleInfo (const G4String &directory, G4bool ascii=false)
virtual G4bool StoreCutsInfo (const G4String &directory, G4bool ascii=false)
virtual G4bool RetrieveCutsInfo (const G4String &directory, G4bool ascii=false)
Private Types
enum { FixedStringLengthForStore = 32 }
typedef std::vector
< G4MaterialCutsCouple * > G4CoupleTable
typedef std::vector
< G4MaterialCutsCouple * >
::const_iterator CoupleTableIterator
typedef std::vector< G4double > G4CutVectorForAParticle
typedef std::vector
< G4CutVectorForAParticle * > G4CutTable
Private Member Functions
G4ProductionCutsTable (const G4ProductionCutsTable &right)
void ScanAndSetCouple (G4LogicalVolume *aLV, G4MaterialCutsCouple *aCouple, G4Region *aRegion)
bool IsCoupleUsedInTheRegion (const G4MaterialCutsCouple *aCouple, const G4Region *aRegion) const
Private Attributes
G4CoupleTable coupleTable
G4CutTable rangeCutTable
G4CutTable energyCutTable
G4RegionStore * fG4RegionStore
G4VRangeToEnergyConverter * converters [NumberOfG4CutIndex]
G4ProductionCuts * defaultProductionCuts
G4MCCIndexConversionTable mccConversionTable
G4double * rangeDoubleVector [NumberOfG4CutIndex]
G4double * energyDoubleVector [NumberOfG4CutIndex]
G4bool firstUse
G4int verboseLevel
G4ProductionCutsTableMessenger * fMessenger
Static Private Attributes
static G4ProductionCutsTable * fG4ProductionCutsTable = 0
Detailed Description
Definition at line 70 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ProductionCutsTable.hh
Member Typedef Documentation
typedef std::vector<G4MaterialCutsCouple*>::const_iterator G4ProductionCutsTable::CoupleTableIterator private
Definition at line 112 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ProductionCutsTable.hh
typedef std::vector<G4MaterialCutsCouple*> G4ProductionCutsTable::G4CoupleTable private
Definition at line 111 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ProductionCutsTable.hh
typedef std::vector<G4CutVectorForAParticle*> G4ProductionCutsTable::G4CutTable private
Definition at line 114 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ProductionCutsTable.hh
typedef std::vector<G4double> G4ProductionCutsTable::G4CutVectorForAParticle private
Definition at line 113 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ProductionCutsTable.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
FixedStringLengthForStore
Definition at line 226 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ProductionCutsTable.hh
Constructor & Destructor Documentation
G4ProductionCutsTable::G4ProductionCutsTable () protected
Definition at line 72 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ProductionCutsTable.cc
References converters, defaultProductionCuts, energyCutTable, energyDoubleVector, fG4RegionStore, fMessenger, G4RegionStore::GetInstance(), NumberOfG4CutIndex, rangeCutTable, and rangeDoubleVector.
G4ProductionCutsTable::G4ProductionCutsTable (const G4ProductionCutsTable & right) private
Definition at line 91 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ProductionCutsTable.cc
References defaultProductionCuts, fG4RegionStore, and fMessenger.
G4ProductionCutsTable::~G4ProductionCutsTable () virtual
Definition at line 99 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ProductionCutsTable.cc
References converters, coupleTable, defaultProductionCuts, energyCutTable, energyDoubleVector, fG4ProductionCutsTable, fMessenger, NumberOfG4CutIndex, rangeCutTable, and rangeDoubleVector.
Member Function Documentation
G4bool G4ProductionCutsTable::CheckForRetrieveCutsTable (const G4String & directory, G4bool ascii = false)
Definition at line 502 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 502 of file G4ProductionCutsTable.cc
References CheckMaterialCutsCoupleInfo(), CheckMaterialInfo(), G4cerr, G4endl, and verboseLevel.
Referenced by RetrieveCutsTable().
G4bool G4ProductionCutsTable::CheckMaterialCutsCoupleInfo (const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 880 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 880 of file G4ProductionCutsTable.cc
References coupleTable, fG4RegionStore, FixedStringLengthForStore, fRegion(), G4cerr, G4cout, G4endl, G4Exception(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetName(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), G4RegionStore::GetRegion(), incremental_prev_tag::idx, in, IsCoupleUsedInTheRegion(), G4MaterialCutsCouple::IsUsed(), JustWarning, mccConversionTable, mm, NumberOfG4CutIndex, ratio, G4MCCIndexConversionTable::Reset(), G4MCCIndexConversionTable::SetNewIndex(), and verboseLevel.
Referenced by CheckForRetrieveCutsTable().
G4bool G4ProductionCutsTable::CheckMaterialInfo (const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 608 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 608 of file G4ProductionCutsTable.cc
References cm3, FixedStringLengthForStore, Acts::UnitConstants::g, G4cerr, G4cout, G4endl, G4Exception(), G4Material::GetDensity(), G4Material::GetMaterial(), incremental_prev_tag::idx, in, JustWarning, ratio, and verboseLevel.
Referenced by CheckForRetrieveCutsTable().
G4double G4ProductionCutsTable::ConvertRangeToEnergy (const G4ParticleDefinition * particle, const G4Material * material, G4double range)
Definition at line 292 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 292 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::Convert(), converters, firstUse, G4Exception(), G4ProductionCuts::GetIndex(), G4ParticleDefinition::GetParticleName(), JustWarning, and verboseLevel.
Referenced by export_G4ProductionCutsTable(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), and G4EmModelManager::Initialise().
void G4ProductionCutsTable::DumpCouples () const
Definition at line 399 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 399 of file G4ProductionCutsTable.cc
References coupleTable, energyCutTable, fG4RegionStore, G4BestUnit, G4cout, G4endl, G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetName(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), IsCoupleUsedInTheRegion(), and G4MaterialCutsCouple::IsUsed().
Referenced by G4VUserPhysicsList::DumpCutValuesTableIfRequested(), export_G4ProductionCutsTable(), and G4RunMessenger::SetNewValue().
G4int G4ProductionCutsTable::GetCoupleIndex (const G4MaterialCutsCouple * aCouple) const inline
Definition at line 331 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 331 of file G4ProductionCutsTable.hh
References coupleTable, and incremental_prev_tag::idx.
Referenced by G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), and GetCoupleIndex().
G4int G4ProductionCutsTable::GetCoupleIndex (const G4Material * aMat, const G4ProductionCuts * aCut) const inline
Definition at line 343 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 343 of file G4ProductionCutsTable.hh
References GetCoupleIndex(), and GetMaterialCutsCouple().
G4ProductionCuts * G4ProductionCutsTable::GetDefaultProductionCuts () const inline
Definition at line 297 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 297 of file G4ProductionCutsTable.hh
References defaultProductionCuts.
G4double * G4ProductionCutsTable::GetEnergyCutsDoubleVector (size_t pcIdx) const inline
Definition at line 293 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 293 of file G4ProductionCutsTable.hh
References energyDoubleVector.
const std::vector< G4double > * G4ProductionCutsTable::GetEnergyCutsVector (size_t pcIdx) const inline
Definition at line 249 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 249 of file G4ProductionCutsTable.hh
References energyCutTable.
Referenced by G4VAtomDeexcitation::AlongStepDeexcitation(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildPhysicsTable(), G4SBBremTable::BuildSamplingTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4AdjointCSManager::ComputeTotalAdjointCS(), G4VEmAdjointModel::DefineCurrentMaterial(), G4ContinuousGainOfEnergy::DefineMaterial(), G4VAtomDeexcitation::GenerateParticles(), RunAction::GetCuts(), RunAction::GetEnergyCut(), G4PAIPhotData::Initialise(), G4EmModelManager::Initialise(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4VEmProcess::PreparePhysicsTable(), and StoreCutsInfo().
G4double G4ProductionCutsTable::GetHighEdgeEnergy () const
Definition at line 369 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 369 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::GetHighEdgeEnergy().
Referenced by export_G4ProductionCutsTable(), G4ProductionCutsTableMessenger::GetCurrentValue(), and G4ProductionCutsTableMessenger::SetNewValue().
G4double G4ProductionCutsTable::GetLowEdgeEnergy () const
Definition at line 363 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 363 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::GetLowEdgeEnergy().
Referenced by export_G4ProductionCutsTable(), G4ProductionCutsTableMessenger::GetCurrentValue(), and G4ProductionCutsTableMessenger::SetNewValue().
const G4MaterialCutsCouple * G4ProductionCutsTable::GetMaterialCutsCouple (G4int i) const inline
Definition at line 261 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 261 of file G4ProductionCutsTable.hh
References coupleTable.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4VEnergyLossProcess::BuildDEDXTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4hImpactIonisation::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4hImpactIonisation::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4SBBremTable::BuildSamplingTables(), G4LossTableBuilder::BuildTableForModel(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4hRDEnergyLoss::CutsWhereModified(), G4EmCalculator::FindCouple(), G4ForwardXrayTR::G4ForwardXrayTR(), GetCoupleIndex(), RunAction::GetCuts(), RunAction::GetEnergyCut(), G4ForwardXrayTR::GetEnergyTR(), G4GSPWACorrections::InitDataPerElement(), G4GSPWACorrections::InitDataPerMaterials(), G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotData::Initialise(), G4EmBiasingManager::Initialise(), G4PenelopeIonisationModel::Initialise(), G4WentzelVIModel::Initialise(), G4LowEPComptonModel::Initialise(), G4IonParametrisedLossModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4LossTableBuilder::InitialiseBaseMaterials(), G4VEmModel::InitialiseElementSelectors(), G4EmCorrections::InitialiseForNewRun(), G4PenelopeBremsstrahlungModel::InitialiseLocal(), G4ElasticHadrNucleusHE::InitialiseModel(), G4GSMottCorrection::InitMCDataPerElement(), G4GSMottCorrection::InitMCDataPerMaterials(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4PhysicsTableHelper::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4hImpactIonisation::PrintInfoDefinition(), and G4ParallelWorldProcess::SwitchMaterial().
const G4MaterialCutsCouple * G4ProductionCutsTable::GetMaterialCutsCouple (const G4Material * aMat, const G4ProductionCuts * aCut) const inline
Definition at line 319 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 319 of file G4ProductionCutsTable.hh
References coupleTable.
G4double G4ProductionCutsTable::GetMaxEnergyCut ()
Definition at line 1259 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 1259 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::GetMaxEnergyCut().
Referenced by G4ProductionCutsTableMessenger::GetCurrentValue().
const G4MCCIndexConversionTable * G4ProductionCutsTable::GetMCCIndexConversionTable () const inline
Definition at line 358 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 358 of file G4ProductionCutsTable.hh
References mccConversionTable.
Referenced by G4PhysicsTableHelper::RetrievePhysicsTable().
G4ProductionCutsTable * G4ProductionCutsTable::GetProductionCutsTable () static
Definition at line 62 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ProductionCutsTable.cc
References fG4ProductionCutsTable.
Referenced by G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eLowEnergyLoss::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4hImpactIonisation::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4GammaConversionToMuons::BuildPhysicsTable(), G4NeutronElasticXS::BuildPhysicsTable(), G4NeutronInelasticXS::BuildPhysicsTable(), G4ParticleInelasticXS::BuildPhysicsTable(), G4NeutronCaptureXS::BuildPhysicsTable(), G4hImpactIonisation::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4RunManagerKernel::BuildPhysicsTables(), G4RDVeLowEnergyLoss::BuildProperTimeTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeTable(), G4SBBremTable::BuildSamplingTables(), G4LossTableBuilder::BuildTableForModel(), G4hRDEnergyLoss::BuildTimeTables(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4RunManagerKernel::CheckRegions(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4EmCalculator::ComputeEnergyCutFromRangeCut(), G4AdjointCSManager::ComputeTotalAdjointCS(), G4TheRayTracer::CreateBitMap(), G4hRDEnergyLoss::CutsWhereModified(), G4VEmAdjointModel::DefineCurrentMaterial(), G4ContinuousGainOfEnergy::DefineMaterial(), G4VUserPhysicsList::DumpCutValuesTableIfRequested(), G4RunManagerKernel::DumpRegion(), export_G4ProductionCutsTable(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), G4EmCalculator::FindCouple(), G4ForwardXrayTR::G4ForwardXrayTR(), G4RunManagerKernel::G4RunManagerKernel(), G4VUserPhysicsList::G4VUserPhysicsList(), RunAction::GetCuts(), RunAction::GetEnergyCut(), G4ForwardXrayTR::GetEnergyTR(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4GSPWACorrections::InitDataPerElement(), G4GSPWACorrections::InitDataPerMaterials(), G4LivermoreRayleighModel::Initialise(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotData::Initialise(), G4PenelopeIonisationModel::Initialise(), G4WentzelVIModel::Initialise(), G4EmBiasingManager::Initialise(), G4WentzelVIRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4LowEPComptonModel::Initialise(), G4IonParametrisedLossModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4LossTableBuilder::InitialiseBaseMaterials(), G4VEmModel::InitialiseElementSelectors(), G4EmCorrections::InitialiseForNewRun(), G4PenelopeBremsstrahlungModel::InitialiseLocal(), G4ElasticHadrNucleusHE::InitialiseModel(), G4GammaGeneralProcess::InitialiseProcess(), G4GSMottCorrection::InitMCDataPerElement(), G4GSMottCorrection::InitMCDataPerMaterials(), G4SBBremTable::InitSamplingTables(), G4GoudsmitSaundersonTable::InitSCPCorrection(), PhysicsList::PhysicsList(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4PhysicsTableHelper::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4hImpactIonisation::PrintInfoDefinition(), G4PhysicsTableHelper::RetrievePhysicsTable(), G4RunManagerKernel::RunTermination(), eRositaPhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), LBE::SetCuts(), PurgMagPhysicsList::SetGELowLimit(), G4RunMessenger::SetNewValue(), G4VUserPhysicsList::SetParticleCuts(), G4ProductionCuts::SetProductionCuts(), G4ParallelWorldProcess::SwitchMaterial(), and G4RunManagerKernel::UpdateRegion().
G4double * G4ProductionCutsTable::GetRangeCutsDoubleVector (size_t pcIdx) const inline
Definition at line 289 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 289 of file G4ProductionCutsTable.hh
References rangeDoubleVector.
const std::vector< G4double > * G4ProductionCutsTable::GetRangeCutsVector (size_t pcIdx) const inline
Definition at line 243 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 243 of file G4ProductionCutsTable.hh
References rangeCutTable.
Referenced by RunAction::GetCuts(), and StoreCutsInfo().
size_t G4ProductionCutsTable::GetTableSize () const inline
Definition at line 255 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 255 of file G4ProductionCutsTable.hh
References coupleTable.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eLowEnergyLoss::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4hImpactIonisation::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4GammaConversionToMuons::BuildPhysicsTable(), G4hImpactIonisation::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4RDVeLowEnergyLoss::BuildProperTimeTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeTable(), G4SBBremTable::BuildSamplingTables(), G4LossTableBuilder::BuildTableForModel(), G4hRDEnergyLoss::BuildTimeTables(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4hRDEnergyLoss::CutsWhereModified(), G4ForwardXrayTR::G4ForwardXrayTR(), RunAction::GetCuts(), G4ForwardXrayTR::GetEnergyTR(), G4GSPWACorrections::InitDataPerElement(), G4GSPWACorrections::InitDataPerMaterials(), G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4mplIonisationModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotData::Initialise(), G4PenelopeIonisationModel::Initialise(), G4WentzelVIModel::Initialise(), G4EmBiasingManager::Initialise(), G4WentzelVIRelModel::Initialise(), G4LowEPComptonModel::Initialise(), G4IonParametrisedLossModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4LossTableBuilder::InitialiseBaseMaterials(), G4VEmModel::InitialiseElementSelectors(), G4EmCorrections::InitialiseForNewRun(), G4PenelopeBremsstrahlungModel::InitialiseLocal(), G4ElasticHadrNucleusHE::InitialiseModel(), G4GammaGeneralProcess::InitialiseProcess(), G4GSMottCorrection::InitMCDataPerElement(), G4GSMottCorrection::InitMCDataPerMaterials(), G4SBBremTable::InitSamplingTables(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4PhysicsTableHelper::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4hImpactIonisation::PrintInfoDefinition().
G4int G4ProductionCutsTable::GetVerboseLevel () const inline
Definition at line 351 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 351 of file G4ProductionCutsTable.hh
References verboseLevel.
Referenced by export_G4ProductionCutsTable(), G4ProductionCutsTableMessenger::GetCurrentValue(), and UpdateCoupleTable().
bool G4ProductionCutsTable::IsCoupleUsedInTheRegion (const G4MaterialCutsCouple * aCouple, const G4Region * aRegion) const inline private
Definition at line 301 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 301 of file G4ProductionCutsTable.hh
References G4MaterialCutsCouple::GetMaterial(), G4Region::GetMaterialIterator(), G4Region::GetNumberOfMaterials(), G4MaterialCutsCouple::GetProductionCuts(), and G4Region::GetProductionCuts().
Referenced by CheckMaterialCutsCoupleInfo(), DumpCouples(), and StoreMaterialCutsCoupleInfo().
G4bool G4ProductionCutsTable::IsModified () const inline
Definition at line 267 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 267 of file G4ProductionCutsTable.hh
References coupleTable, and firstUse.
Referenced by export_G4ProductionCutsTable().
void G4ProductionCutsTable::PhysicsTableUpdated () inline
Definition at line 281 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 281 of file G4ProductionCutsTable.hh
References coupleTable.
Referenced by G4RunManagerKernel::RunTermination().
void G4ProductionCutsTable::ResetConverters ()
Definition at line 348 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 348 of file G4ProductionCutsTable.cc
References converters, NumberOfG4CutIndex, and G4VRangeToEnergyConverter::Reset().
G4bool G4ProductionCutsTable::RetrieveCutsInfo (const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 1145 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 1145 of file G4ProductionCutsTable.cc
References energyCutTable, FixedStringLengthForStore, G4cerr, G4endl, G4Exception(), G4MCCIndexConversionTable::GetIndex(), incremental_prev_tag::idx, in, G4MCCIndexConversionTable::IsUsed(), JustWarning, keV, mccConversionTable, mm, NumberOfG4CutIndex, rangeCutTable, G4MCCIndexConversionTable::size(), and verboseLevel.
Referenced by RetrieveCutsTable().
G4bool G4ProductionCutsTable::RetrieveCutsTable (const G4String & directory, G4bool ascii = false)
Definition at line 477 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 477 of file G4ProductionCutsTable.cc
References CheckForRetrieveCutsTable(), G4cout, G4endl, RetrieveCutsInfo(), and verboseLevel.
Referenced by G4VUserPhysicsList::BuildPhysicsTable().
void G4ProductionCutsTable::ScanAndSetCouple (G4LogicalVolume * aLV, G4MaterialCutsCouple * aCouple, G4Region * aRegion) private
Definition at line 376 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 376 of file G4ProductionCutsTable.cc
References G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4MaterialCutsCouple::GetMaterial(), G4LogicalVolume::GetMaterial(), G4LogicalVolume::GetNoDaughters(), G4LogicalVolume::GetRegion(), and G4LogicalVolume::SetMaterialCutsCouple().
Referenced by UpdateCoupleTable().
void G4ProductionCutsTable::SetEnergyRange (G4double lowedge, G4double highedge)
Definition at line 357 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 357 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::SetEnergyRange().
Referenced by export_G4ProductionCutsTable(), G4VUserPhysicsList::G4VUserPhysicsList(), PhysicsList::PhysicsList(), eRositaPhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), BrachyPhysicsList::SetCuts(), DMXPhysicsList::SetCuts(), LBE::SetCuts(), PurgMagPhysicsList::SetGELowLimit(), and G4ProductionCutsTableMessenger::SetNewValue().
void G4ProductionCutsTable::SetMaxEnergyCut (G4double value)
Definition at line 1266 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 1266 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::SetMaxEnergyCut().
Referenced by G4ProductionCutsTableMessenger::SetNewValue().
void G4ProductionCutsTable::SetVerboseLevel (G4int value)
Definition at line 1248 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 1248 of file G4ProductionCutsTable.cc
References converters, NumberOfG4CutIndex, G4VRangeToEnergyConverter::SetVerboseLevel(), and verboseLevel.
Referenced by export_G4ProductionCutsTable(), G4ProductionCutsTableMessenger::SetNewValue(), and G4VUserPhysicsList::SetVerboseLevel().
G4bool G4ProductionCutsTable::StoreCutsInfo (const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 1067 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 1067 of file G4ProductionCutsTable.cc
References coupleTable, FixedStringLengthForStore, G4cerr, G4endl, G4Exception(), GetEnergyCutsVector(), GetRangeCutsVector(), incremental_prev_tag::idx, JustWarning, keV, mm, NumberOfG4CutIndex, and verboseLevel.
Referenced by StoreCutsTable().
G4bool G4ProductionCutsTable::StoreCutsTable (const G4String & directory, G4bool ascii = false)
Definition at line 454 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 454 of file G4ProductionCutsTable.cc
References G4cout, G4endl, StoreCutsInfo(), StoreMaterialCutsCoupleInfo(), StoreMaterialInfo(), and verboseLevel.
Referenced by G4VUserPhysicsList::StorePhysicsTable().
G4bool G4ProductionCutsTable::StoreMaterialCutsCoupleInfo (const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 749 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 749 of file G4ProductionCutsTable.cc
References coupleTable, fG4RegionStore, FixedStringLengthForStore, G4cerr, G4endl, G4Exception(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetName(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), incremental_prev_tag::idx, IsCoupleUsedInTheRegion(), G4MaterialCutsCouple::IsUsed(), JustWarning, mm, NumberOfG4CutIndex, and verboseLevel.
Referenced by StoreCutsTable().
G4bool G4ProductionCutsTable::StoreMaterialInfo (const G4String & directory, G4bool ascii = false) protected virtual
Definition at line 521 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 521 of file G4ProductionCutsTable.cc
References cm3, FixedStringLengthForStore, Acts::UnitConstants::g, G4cerr, G4endl, G4Exception(), G4Material::GetMaterialTable(), incremental_prev_tag::idx, JustWarning, and verboseLevel.
Referenced by StoreCutsTable().
void G4ProductionCutsTable::UpdateCoupleTable (G4VPhysicalVolume * currentWorld)
Definition at line 129 of file G4ProductionCutsTable.cc.
View newest version in sPHENIX GitHub at line 129 of file G4ProductionCutsTable.cc
References G4VRangeToEnergyConverter::Convert(), converters, coupleTable, energyCutTable, energyDoubleVector, fG4RegionStore, firstUse, G4cout, G4endl, G4Material::GetMaterial(), G4ParticleTable::GetParticleTable(), G4ProductionCuts::GetProductionCut(), G4ProductionCuts::GetProductionCuts(), GetVerboseLevel(), incremental_prev_tag::idx, n, G4InuclParticleNames::nn, NumberOfG4CutIndex, rangeCutTable, rangeDoubleVector, ScanAndSetCouple(), G4MaterialCutsCouple::SetIndex(), G4MaterialCutsCouple::SetUseFlag(), G4VRangeToEnergyConverter::SetVerboseLevel(), G4Timer::Start(), G4Timer::Stop(), and verboseLevel.
Referenced by G4TheRayTracer::CreateBitMap(), and G4RunManagerKernel::UpdateRegion().
Member Data Documentation
G4VRangeToEnergyConverter* G4ProductionCutsTable::converters[NumberOfG4CutIndex] private
Definition at line 120 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ProductionCutsTable.hh
Referenced by ConvertRangeToEnergy(), G4ProductionCutsTable(), ResetConverters(), SetVerboseLevel(), UpdateCoupleTable(), and ~G4ProductionCutsTable().
G4CoupleTable G4ProductionCutsTable::coupleTable private
Definition at line 115 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ProductionCutsTable.hh
Referenced by CheckMaterialCutsCoupleInfo(), DumpCouples(), GetCoupleIndex(), GetMaterialCutsCouple(), GetTableSize(), IsModified(), PhysicsTableUpdated(), StoreCutsInfo(), StoreMaterialCutsCoupleInfo(), UpdateCoupleTable(), and ~G4ProductionCutsTable().
G4ProductionCuts* G4ProductionCutsTable::defaultProductionCuts private
Definition at line 122 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ProductionCutsTable.hh
Referenced by G4ProductionCutsTable(), GetDefaultProductionCuts(), and ~G4ProductionCutsTable().
G4CutTable G4ProductionCutsTable::energyCutTable private
Definition at line 117 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ProductionCutsTable.hh
Referenced by DumpCouples(), G4ProductionCutsTable(), GetEnergyCutsVector(), RetrieveCutsInfo(), UpdateCoupleTable(), and ~G4ProductionCutsTable().
G4double* G4ProductionCutsTable::energyDoubleVector[NumberOfG4CutIndex] private
Definition at line 128 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ProductionCutsTable.hh
Referenced by G4ProductionCutsTable(), GetEnergyCutsDoubleVector(), UpdateCoupleTable(), and ~G4ProductionCutsTable().
G4ProductionCutsTable * G4ProductionCutsTable::fG4ProductionCutsTable = 0 static private
Definition at line 109 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ProductionCutsTable.hh
Referenced by GetProductionCutsTable(), and ~G4ProductionCutsTable().
G4RegionStore* G4ProductionCutsTable::fG4RegionStore private
Definition at line 119 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ProductionCutsTable.hh
Referenced by CheckMaterialCutsCoupleInfo(), DumpCouples(), G4ProductionCutsTable(), StoreMaterialCutsCoupleInfo(), and UpdateCoupleTable().
G4bool G4ProductionCutsTable::firstUse private
Definition at line 225 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 225 of file G4ProductionCutsTable.hh
Referenced by ConvertRangeToEnergy(), IsModified(), and UpdateCoupleTable().
G4ProductionCutsTableMessenger* G4ProductionCutsTable::fMessenger private
Definition at line 238 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 238 of file G4ProductionCutsTable.hh
Referenced by G4ProductionCutsTable(), and ~G4ProductionCutsTable().
G4MCCIndexConversionTable G4ProductionCutsTable::mccConversionTable private
Definition at line 124 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ProductionCutsTable.hh
Referenced by CheckMaterialCutsCoupleInfo(), GetMCCIndexConversionTable(), and RetrieveCutsInfo().
G4CutTable G4ProductionCutsTable::rangeCutTable private
Definition at line 116 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ProductionCutsTable.hh
Referenced by G4ProductionCutsTable(), GetRangeCutsVector(), RetrieveCutsInfo(), UpdateCoupleTable(), and ~G4ProductionCutsTable().
G4double* G4ProductionCutsTable::rangeDoubleVector[NumberOfG4CutIndex] private
Definition at line 127 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ProductionCutsTable.hh
Referenced by G4ProductionCutsTable(), GetRangeCutsDoubleVector(), UpdateCoupleTable(), and ~G4ProductionCutsTable().
G4int G4ProductionCutsTable::verboseLevel private
Definition at line 237 of file G4ProductionCutsTable.hh.
View newest version in sPHENIX GitHub at line 237 of file G4ProductionCutsTable.hh
Referenced by CheckForRetrieveCutsTable(), CheckMaterialCutsCoupleInfo(), CheckMaterialInfo(), ConvertRangeToEnergy(), GetVerboseLevel(), RetrieveCutsInfo(), RetrieveCutsTable(), SetVerboseLevel(), StoreCutsInfo(), StoreCutsTable(), StoreMaterialCutsCoupleInfo(), StoreMaterialInfo(), and UpdateCoupleTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4ProductionCutsTable.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4ProductionCutsTable.cc