ECCE @ EIC Software: G4CoupledTransportation Class Reference
G4CoupledTransportation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4CoupledTransportation.hh>
Public Member Functions
G4CoupledTransportation (G4int verbosityLevel=0)
~G4CoupledTransportation ()
G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &stepData)
G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4ForceCondition *pForceCond)
G4PropagatorInField * GetPropagatorInField ()
void SetPropagatorInField (G4PropagatorInField *pFieldPropagator)
G4double GetThresholdWarningEnergy () const
G4double GetThresholdImportantEnergy () const
G4int GetThresholdTrials () const
void SetThresholdWarningEnergy (G4double newEnWarn)
void SetThresholdImportantEnergy (G4double newEnImp)
void SetThresholdTrials (G4int newMaxTrials)
void SetHighLooperThresholds ()
void SetLowLooperThresholds ()
void PushThresholdsToLogger ()
void ReportLooperThresholds ()
G4double GetMaxEnergyKilled () const
G4double GetSumEnergyKilled () const
void ResetKilledStatistics (G4int report=1)
G4bool IsFirstStepInAnyVolume () const
G4bool IsLastStepInAnyVolume () const
G4bool IsFirstStepInMassVolume () const
G4bool IsLastStepInMassVolume () const
void StartTracking (G4Track *aTrack)
void EndTracking ()
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
void PrintStatistics (std::ostream &outStr) const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static G4bool EnableMagneticMoment (G4bool useMoment=true)
static G4bool EnableGravity (G4bool useGravity)
static void SetSilenceLooperWarnings (G4bool val)
static G4bool GetSilenceLooperWarnings ()
static void SetSignifyStepsInAnyVolume (G4bool anyVol)
static G4bool GetSignifyStepsInAnyVolume ()
static G4bool EnableUseMagneticMoment (G4bool useMoment=true)
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions
G4bool DoesAnyFieldExist ()
void ReportInexactEnergy (G4double startEnergy, G4double endEnergy)
void ReportMove (G4ThreeVector OldVector, G4ThreeVector NewVector, const G4String &Quantity)
void ReportMissingLogger (const char *methodName)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Attributes
G4Navigator * fMassNavigator
G4PathFinder * fPathFinder
G4int fNavigatorId
G4PropagatorInField * fFieldPropagator
G4bool fAnyFieldExists
G4ThreeVector fTransportEndPosition
G4ThreeVector fTransportEndMomentumDir
G4double fTransportEndKineticEnergy
G4ThreeVector fTransportEndSpin
G4bool fMomentumChanged
G4bool fEndGlobalTimeComputed
G4double fCandidateEndGlobalTime
G4bool fParticleIsLooping
G4bool fNewTrack
G4ThreeVector fPreviousSftOrigin
G4double fPreviousMassSafety
G4double fPreviousFullSafety
G4TouchableHandle fCurrentTouchableHandle
G4bool fMassGeometryLimitedStep
G4bool fAnyGeometryLimitedStep
G4ParticleChangeForTransport fParticleChange
G4double fEndpointDistance
G4double fThreshold_Warning_Energy = 1.0 * CLHEP::keV
G4double fThreshold_Important_Energy = 1.0 * CLHEP::MeV
G4int fThresholdTrials = 10
G4int fNoLooperTrials =0
G4double fSumEnergyKilled = 0.0
G4double fSumEnerSqKilled = 0.0
G4double fMaxEnergyKilled = -1.0
G4int fMaxEnergyKilledPDG = 0
unsigned long fNumLoopersKilled = 0
G4double fSumEnergyKilled_NonElectron = 0.0
G4double fSumEnerSqKilled_NonElectron = 0.0
G4double fMaxEnergyKilled_NonElectron = -1.0
G4int fMaxEnergyKilled_NonElecPDG = 0
unsigned long fNumLoopersKilled_NonElectron = 0
G4double fSumEnergySaved = 0.0
G4double fMaxEnergySaved = -1.0
G4double fSumEnergyUnstableSaved = 0.0
G4SafetyHelper * fpSafetyHelper
G4TransportationLogger * fpLogger
G4bool fFirstStepInMassVolume
G4bool fFirstStepInAnyVolume
Static Private Attributes
static G4bool fUseMagneticMoment =false
static G4bool fUseGravity = false
static G4bool fSilenceLooperWarnings = false
static G4bool fSignifyStepInAnyVolume = false
Friends
class G4Transportation
Additional Inherited Members
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 65 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4CoupledTransportation.hh
Constructor & Destructor Documentation
G4CoupledTransportation::G4CoupledTransportation (G4int verbosityLevel = 0)
Definition at line 62 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 62 of file G4CoupledTransportation.cc
References G4TransportationManager::ActivateNavigator(), COUPLED_TRANSPORTATION, DoesAnyFieldExist(), fAnyFieldExists, fCurrentTouchableHandle, fFieldPropagator, fMassNavigator, fNavigatorId, fPathFinder, fpLogger, fpSafetyHelper, fSignifyStepInAnyVolume, G4cout, G4endl, G4ThreadLocal, G4PathFinder::GetInstance(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), PushThresholdsToLogger(), SetHighLooperThresholds(), G4VProcess::SetProcessSubType(), G4VProcess::SetVerboseLevel(), and G4VProcess::verboseLevel.
G4CoupledTransportation::~G4CoupledTransportation ()
Definition at line 125 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 125 of file G4CoupledTransportation.cc
References fpLogger, fSumEnergyKilled, G4cout, and PrintStatistics().
Member Function Documentation
G4VParticleChange * G4CoupledTransportation::AlongStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 563 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 563 of file G4CoupledTransportation.cc
References DBL_MAX, fCandidateEndGlobalTime, fEndGlobalTimeComputed, fMaxEnergyKilled, fMaxEnergyKilled_NonElecPDG, fMaxEnergyKilled_NonElectron, fMaxEnergyKilledPDG, fMaxEnergySaved, fMomentumChanged, fNoLooperTrials, fNumLoopersKilled, fNumLoopersKilled_NonElectron, fParticleChange, fParticleIsLooping, fpLogger, fSilenceLooperWarnings, fStopAndKill, fSumEnergyKilled, fSumEnergyKilled_NonElectron, fSumEnergySaved, fSumEnergyUnstableSaved, fSumEnerSqKilled, fSumEnerSqKilled_NonElectron, fThreshold_Important_Energy, fThreshold_Warning_Energy, fThresholdTrials, fTransportEndKineticEnergy, fTransportEndMomentumDir, fTransportEndPosition, fTransportEndSpin, G4cout, G4endl, G4ThreadLocal, G4Track::GetCurrentStepNumber(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetLocalTime(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGStable(), G4Step::GetPreStepPoint(), G4Track::GetProperTime(), G4Track::GetStepLength(), G4Track::GetTotalEnergy(), G4StepPoint::GetVelocity(), G4Track::GetVelocity(), G4ParticleChangeForTransport::Initialize(), max, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeGlobalTime(), G4ParticleChange::ProposeLocalTime(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4ParticleChange::ProposePosition(), G4ParticleChange::ProposeProperTime(), G4VParticleChange::ProposeTrackStatus(), G4TransportationLogger::ReportLoopingTrack(), G4ParticleChangeForTransport::SetMomentumChanged(), and G4VProcess::verboseLevel.
G4double G4CoupledTransportation::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 165 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 165 of file G4CoupledTransportation.cc
References CandidateForSelection, G4PathFinder::ComputeSafety(), G4PathFinder::ComputeStep(), G4FieldManager::ConfigureForTrack(), G4FieldManager::DoesFieldChangeEnergy(), false, fAnyGeometryLimitedStep, FatalException, fCandidateEndGlobalTime, fEndGlobalTimeComputed, fEndpointDistance, fFieldPropagator, fFirstStepInAnyVolume, fFirstStepInMassVolume, G4PropagatorInField::FindAndSetFieldManager(), fMassGeometryLimitedStep, fMomentumChanged, fNavigatorId, fNewTrack, fParticleChange, fParticleIsLooping, fPathFinder, fPreviousFullSafety, fPreviousMassSafety, fPreviousSftOrigin, fpSafetyHelper, fTransportEndKineticEnergy, fTransportEndMomentumDir, fTransportEndPosition, fTransportEndSpin, fUseGravity, fUseMagneticMoment, G4cerr, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4DynamicParticle::GetCharge(), G4PropagatorInField::GetCurrentEquationOfMotion(), G4PropagatorInField::GetCurrentFieldManager(), G4PathFinder::GetCurrentSafety(), G4Track::GetCurrentStepNumber(), G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4FieldTrack::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4FieldTrack::GetLabTimeOfFlight(), G4DynamicParticle::GetMagneticMoment(), G4DynamicParticle::GetMass(), G4FieldTrack::GetMomentumDir(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4PathFinder::GetNumberGeometriesLimitingStep(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGSpin(), G4Track::GetPolarization(), G4FieldTrack::GetPosition(), G4Track::GetPosition(), G4FieldTrack::GetSpin(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetVolume(), G4Field::IsGravityActive(), G4PropagatorInField::IsParticleLooping(), kSharedTransport, kUnique, CLHEP::Hep3Vector::mag2(), max, message(), min, G4PathFinder::ObtainSafety(), perMillion, perThousand, CLHEP::prec, G4VParticleChange::ProposeTrueStepLength(), ReportInexactEnergy(), G4SafetyHelper::SetCurrentSafety(), sqr(), true, and G4VProcess::verboseLevel.
G4VParticleChange* G4CoupledTransportation::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 167 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 167 of file G4CoupledTransportation.hh
G4double G4CoupledTransportation::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 163 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 163 of file G4CoupledTransportation.hh
G4bool G4CoupledTransportation::DoesAnyFieldExist () protected
Referenced by G4CoupledTransportation(), and StartTracking().
G4bool G4CoupledTransportation::EnableGravity (G4bool useGravity) static
Definition at line 1076 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1076 of file G4CoupledTransportation.cc
References G4Transportation::fUseGravity, and fUseGravity.
G4bool G4CoupledTransportation::EnableMagneticMoment (G4bool useMoment = true) static
Definition at line 1065 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1065 of file G4CoupledTransportation.cc
References G4Transportation::fUseMagneticMoment, and fUseMagneticMoment.
Referenced by EnableUseMagneticMoment().
static G4bool G4CoupledTransportation::EnableUseMagneticMoment (G4bool useMoment = true) inline static
Definition at line 159 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 159 of file G4CoupledTransportation.hh
References EnableMagneticMoment().
void G4CoupledTransportation::EndTracking () virtual
Reimplemented from G4VProcess.
Definition at line 1006 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1006 of file G4CoupledTransportation.cc
References G4PathFinder::EndTrack(), fPathFinder, G4TransportationManager::GetTransportationManager(), and G4TransportationManager::InactivateAll().
G4double G4CoupledTransportation::GetMaxEnergyKilled () const inline
G4PropagatorInField* G4CoupledTransportation::GetPropagatorInField ()
static G4bool G4CoupledTransportation::GetSignifyStepsInAnyVolume () inline static
Definition at line 140 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4CoupledTransportation.hh
References fSignifyStepInAnyVolume.
G4bool G4CoupledTransportation::GetSilenceLooperWarnings () static
Definition at line 1096 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1096 of file G4CoupledTransportation.cc
References fSilenceLooperWarnings.
G4double G4CoupledTransportation::GetSumEnergyKilled () const inline
G4double G4CoupledTransportation::GetThresholdImportantEnergy () const inline
G4int G4CoupledTransportation::GetThresholdTrials () const inline
G4double G4CoupledTransportation::GetThresholdWarningEnergy () const inline
G4bool G4CoupledTransportation::IsFirstStepInAnyVolume () const inline
Definition at line 149 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 149 of file G4CoupledTransportation.hh
References fFirstStepInAnyVolume.
G4bool G4CoupledTransportation::IsFirstStepInMassVolume () const inline
Definition at line 151 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 151 of file G4CoupledTransportation.hh
References fFirstStepInMassVolume.
G4bool G4CoupledTransportation::IsLastStepInAnyVolume () const inline
Definition at line 150 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 150 of file G4CoupledTransportation.hh
References fAnyGeometryLimitedStep.
G4bool G4CoupledTransportation::IsLastStepInMassVolume () const inline
Definition at line 152 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 152 of file G4CoupledTransportation.hh
References fMassGeometryLimitedStep.
G4VParticleChange * G4CoupledTransportation::PostStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 764 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 764 of file G4CoupledTransportation.cc
References G4PathFinder::CreateTouchableHandle(), fAnyGeometryLimitedStep, fCurrentTouchableHandle, fFirstStepInAnyVolume, fFirstStepInMassVolume, fMassGeometryLimitedStep, fNavigatorId, fParticleChange, fPathFinder, fSignifyStepInAnyVolume, fStopAndKill, fTransportEndPosition, G4cerr, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4MaterialCutsCouple::GetMaterial(), G4LogicalVolume::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4LogicalVolume::GetMaterialCutsCouple(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetSensitiveDetector(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4VTouchable::GetVolume(), G4PathFinder::Locate(), G4VParticleChange::ProposeFirstStepInVolume(), G4VParticleChange::ProposeLastStepInVolume(), G4VParticleChange::ProposeTrackStatus(), G4PathFinder::ReLocate(), ReportMove(), G4ParticleChangeForTransport::SetMaterialCutsCoupleInTouchable(), G4ParticleChangeForTransport::SetMaterialInTouchable(), G4ParticleChangeForTransport::SetSensitiveDetectorInTouchable(), G4ParticleChangeForTransport::SetTouchableHandle(), and G4VProcess::verboseLevel.
G4double G4CoupledTransportation::PostStepGetPhysicalInteractionLength (const G4Track & , G4double previousStepSize, G4ForceCondition * pForceCond) virtual
Implements G4VProcess.
Definition at line 733 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 733 of file G4CoupledTransportation.cc
References DBL_MAX, and Forced.
void G4CoupledTransportation::PrintStatistics (std::ostream & outStr) const
Definition at line 137 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 137 of file G4CoupledTransportation.cc
References fMaxEnergyKilled, fMaxEnergySaved, fSumEnergyKilled, fSumEnergySaved, fSumEnergyUnstableSaved, G4endl, and MeV.
Referenced by ~G4CoupledTransportation().
void G4CoupledTransportation::PushThresholdsToLogger ()
Referenced by G4CoupledTransportation(), and ReportLooperThresholds().
void G4CoupledTransportation::ReportInexactEnergy (G4double startEnergy, G4double endEnergy) protected
Definition at line 1017 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1017 of file G4CoupledTransportation.cc
References G4endl, G4Exception(), G4ThreadLocal, JustWarning, message(), MeV, perThousand, and G4VProcess::verboseLevel.
Referenced by AlongStepGetPhysicalInteractionLength().
void G4CoupledTransportation::ReportLooperThresholds ()
Definition at line 1144 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1144 of file G4CoupledTransportation.cc
References fpLogger, PushThresholdsToLogger(), and G4TransportationLogger::ReportLooperThresholds().
Referenced by ReportMissingLogger(), SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4CoupledTransportation::ReportMissingLogger (const char * methodName) protected
Definition at line 1132 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1132 of file G4CoupledTransportation.cc
References G4Exception(), JustWarning, message(), ReportLooperThresholds(), and G4VProcess::verboseLevel.
void G4CoupledTransportation::ReportMove (G4ThreeVector OldVector, G4ThreeVector NewVector, const G4String & Quantity) protected
Definition at line 745 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 745 of file G4CoupledTransportation.cc
References G4cerr, G4endl, CLHEP::Hep3Vector::mag(), and mm.
Referenced by PostStepDoIt().
void G4CoupledTransportation::ResetKilledStatistics (G4int report = 1) inline
void G4CoupledTransportation::SetHighLooperThresholds ()
Definition at line 1103 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4CoupledTransportation.cc
References CLHEP::MeV, ReportLooperThresholds(), SetThresholdImportantEnergy(), SetThresholdTrials(), SetThresholdWarningEnergy(), and G4VProcess::verboseLevel.
Referenced by G4CoupledTransportation().
void G4CoupledTransportation::SetLowLooperThresholds ()
Definition at line 1117 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1117 of file G4CoupledTransportation.cc
References CLHEP::keV, CLHEP::MeV, ReportLooperThresholds(), SetThresholdImportantEnergy(), SetThresholdTrials(), SetThresholdWarningEnergy(), and G4VProcess::verboseLevel.
void G4CoupledTransportation::SetPropagatorInField (G4PropagatorInField * pFieldPropagator)
static void G4CoupledTransportation::SetSignifyStepsInAnyVolume (G4bool anyVol) inline static
Definition at line 138 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 138 of file G4CoupledTransportation.hh
References fSignifyStepInAnyVolume.
void G4CoupledTransportation::SetSilenceLooperWarnings (G4bool val) static
Definition at line 1088 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 1088 of file G4CoupledTransportation.cc
References fSilenceLooperWarnings.
void G4CoupledTransportation::SetThresholdImportantEnergy (G4double newEnImp) inline
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4CoupledTransportation::SetThresholdTrials (G4int newMaxTrials) inline
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4CoupledTransportation::SetThresholdWarningEnergy (G4double newEnWarn) inline
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4CoupledTransportation::StartTracking (G4Track * aTrack) virtual
Reimplemented from G4VProcess.
Definition at line 935 of file G4CoupledTransportation.cc.
View newest version in sPHENIX GitHub at line 935 of file G4CoupledTransportation.cc
References G4TransportationManager::ActivateNavigator(), G4FieldManagerStore::ClearAllChordFindersState(), G4PropagatorInField::ClearPropagatorState(), DoesAnyFieldExist(), fAnyFieldExists, fCurrentTouchableHandle, fFieldPropagator, fMassNavigator, fNavigatorId, fNewTrack, fNoLooperTrials, fPathFinder, fPreviousFullSafety, fPreviousMassSafety, fPreviousSftOrigin, G4cout, G4endl, G4PropagatorInField::GetChordFinder(), G4FieldManagerStore::GetInstance(), G4Track::GetMomentumDirection(), G4TransportationManager::GetNavigatorForTracking(), G4Track::GetPosition(), G4Track::GetTouchableHandle(), G4TransportationManager::GetTransportationManager(), G4PathFinder::PrepareNewTrack(), G4ChordFinder::ResetStepEstimate(), and G4VProcess::verboseLevel.
Friends And Related Function Documentation
friend class G4Transportation friend
Definition at line 270 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 270 of file G4CoupledTransportation.hh
Member Data Documentation
G4bool G4CoupledTransportation::fAnyFieldExists private
Definition at line 198 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 198 of file G4CoupledTransportation.hh
Referenced by G4CoupledTransportation(), and StartTracking().
G4bool G4CoupledTransportation::fAnyGeometryLimitedStep private
Definition at line 227 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 227 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), IsLastStepInAnyVolume(), and PostStepDoIt().
G4double G4CoupledTransportation::fCandidateEndGlobalTime private
Definition at line 210 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 210 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4TouchableHandle G4CoupledTransportation::fCurrentTouchableHandle private
Definition at line 218 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 218 of file G4CoupledTransportation.hh
Referenced by G4CoupledTransportation(), PostStepDoIt(), and StartTracking().
G4bool G4CoupledTransportation::fEndGlobalTimeComputed private
Definition at line 209 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 209 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4double G4CoupledTransportation::fEndpointDistance private
Definition at line 233 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 233 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4PropagatorInField* G4CoupledTransportation::fFieldPropagator private
Definition at line 195 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 195 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation(), and StartTracking().
G4bool G4CoupledTransportation::fFirstStepInAnyVolume private
Definition at line 278 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 278 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), IsFirstStepInAnyVolume(), and PostStepDoIt().
G4bool G4CoupledTransportation::fFirstStepInMassVolume private
Definition at line 277 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 277 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), IsFirstStepInMassVolume(), and PostStepDoIt().
G4bool G4CoupledTransportation::fMassGeometryLimitedStep private
Definition at line 225 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 225 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), IsLastStepInMassVolume(), and PostStepDoIt().
G4Navigator* G4CoupledTransportation::fMassNavigator private
Definition at line 188 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 188 of file G4CoupledTransportation.hh
Referenced by G4CoupledTransportation(), and StartTracking().
G4double G4CoupledTransportation::fMaxEnergyKilled = -1.0 private
Definition at line 253 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 253 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4int G4CoupledTransportation::fMaxEnergyKilled_NonElecPDG = 0 private
Definition at line 259 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 259 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fMaxEnergyKilled_NonElectron = -1.0 private
Definition at line 258 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 258 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4int G4CoupledTransportation::fMaxEnergyKilledPDG = 0 private
Definition at line 254 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 254 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fMaxEnergySaved = -1.0 private
Definition at line 262 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 262 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4bool G4CoupledTransportation::fMomentumChanged private
Definition at line 206 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 206 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4int G4CoupledTransportation::fNavigatorId private
Definition at line 192 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 192 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation(), PostStepDoIt(), and StartTracking().
G4bool G4CoupledTransportation::fNewTrack private
Definition at line 213 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 213 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4int G4CoupledTransportation::fNoLooperTrials =0 private
Definition at line 247 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 247 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and StartTracking().
unsigned long G4CoupledTransportation::fNumLoopersKilled = 0 private
Definition at line 255 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 255 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
unsigned long G4CoupledTransportation::fNumLoopersKilled_NonElectron = 0 private
Definition at line 260 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 260 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4ParticleChangeForTransport G4CoupledTransportation::fParticleChange private
Definition at line 230 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 230 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and PostStepDoIt().
G4bool G4CoupledTransportation::fParticleIsLooping private
Definition at line 212 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 212 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4PathFinder* G4CoupledTransportation::fPathFinder private
Definition at line 191 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 191 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), EndTracking(), G4CoupledTransportation(), PostStepDoIt(), and StartTracking().
G4TransportationLogger* G4CoupledTransportation::fpLogger private
Definition at line 266 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 266 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), G4CoupledTransportation(), ReportLooperThresholds(), and ~G4CoupledTransportation().
G4double G4CoupledTransportation::fPreviousFullSafety private
Definition at line 216 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 216 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4double G4CoupledTransportation::fPreviousMassSafety private
Definition at line 215 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 215 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4ThreeVector G4CoupledTransportation::fPreviousSftOrigin private
Definition at line 214 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 214 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4SafetyHelper* G4CoupledTransportation::fpSafetyHelper private
Definition at line 265 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 265 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and G4CoupledTransportation().
G4bool G4CoupledTransportation::fSignifyStepInAnyVolume = false static private
Definition at line 282 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 282 of file G4CoupledTransportation.hh
Referenced by G4CoupledTransportation(), GetSignifyStepsInAnyVolume(), PostStepDoIt(), and SetSignifyStepsInAnyVolume().
G4bool G4CoupledTransportation::fSilenceLooperWarnings = false static private
Definition at line 273 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 273 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), GetSilenceLooperWarnings(), and SetSilenceLooperWarnings().
G4double G4CoupledTransportation::fSumEnergyKilled = 0.0 private
Definition at line 251 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 251 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), PrintStatistics(), and ~G4CoupledTransportation().
G4double G4CoupledTransportation::fSumEnergyKilled_NonElectron = 0.0 private
Definition at line 256 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 256 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fSumEnergySaved = 0.0 private
Definition at line 261 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 261 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4CoupledTransportation::fSumEnergyUnstableSaved = 0.0 private
Definition at line 263 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 263 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4CoupledTransportation::fSumEnerSqKilled = 0.0 private
Definition at line 252 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 252 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fSumEnerSqKilled_NonElectron = 0.0 private
Definition at line 257 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 257 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fThreshold_Important_Energy = 1.0 * CLHEP::MeV private
Definition at line 239 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 239 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fThreshold_Warning_Energy = 1.0 * CLHEP::keV private
Definition at line 238 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 238 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4int G4CoupledTransportation::fThresholdTrials = 10 private
Definition at line 240 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 240 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt().
G4double G4CoupledTransportation::fTransportEndKineticEnergy private
Definition at line 204 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 204 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4CoupledTransportation::fTransportEndMomentumDir private
Definition at line 203 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 203 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4CoupledTransportation::fTransportEndPosition private
Definition at line 202 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 202 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and PostStepDoIt().
G4ThreeVector G4CoupledTransportation::fTransportEndSpin private
Definition at line 205 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 205 of file G4CoupledTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4bool G4CoupledTransportation::fUseGravity = false static private
Definition at line 272 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 272 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4Transportation::EnableGravity(), and EnableGravity().
G4bool G4CoupledTransportation::fUseMagneticMoment =false static private
Definition at line 271 of file G4CoupledTransportation.hh.
View newest version in sPHENIX GitHub at line 271 of file G4CoupledTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4Transportation::EnableMagneticMoment(), and EnableMagneticMoment().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4CoupledTransportation.hh
geant4/tree/geant4-10.6-release/source/processes/transportation/src/G4CoupledTransportation.cc