ECCE @ EIC Software: G4DataSet Class Reference
G4DataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4DataSet.hh>
Public Member Functions
G4DataSet (G4int argZ, G4IInterpolator *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
G4DataSet (G4int argZ, G4DataVector *xData, G4DataVector *data, G4IInterpolator *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
virtual ~G4DataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4IDataSet * GetComponent (G4int) const
virtual void AddComponent (G4IDataSet *)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int) const
virtual const G4DataVector & GetData (G4int) const
virtual void SetEnergiesData (G4DataVector *xData, G4DataVector *data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int componentId=0) const
Public Member Functions inherited from G4IDataSet
G4IDataSet ()
virtual ~G4IDataSet ()
Private Member Functions
size_t FindLowerBound (G4double energy) const
size_t FindLowerBound (G4double x, G4DataVector *values) const
G4double IntegrationFunction (G4double x)
virtual void BuildPdf ()
G4String FullFileName (const G4String &fileName) const
G4DataSet ()
G4DataSet (const G4DataSet &copy)
G4DataSet & operator= (const G4DataSet &right)
Private Attributes
G4int z
G4DataVector * energies
G4DataVector * data
G4IInterpolator * algorithm
G4double unitEnergies
G4double unitData
G4DataVector * pdf
G4bool randomSet
Detailed Description
Definition at line 53 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DataSet.hh
Constructor & Destructor Documentation
G4DataSet::G4DataSet (G4int argZ, G4IInterpolator * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 46 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 46 of file G4DataSet.cc
References algorithm, BuildPdf(), FatalException, G4Exception(), and randomSet.
G4DataSet::G4DataSet (G4int argZ, G4DataVector * xData, G4DataVector * data, G4IInterpolator * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 67 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 67 of file G4DataSet.cc
References algorithm, BuildPdf(), energies, FatalException, G4Exception(), and randomSet.
G4DataSet::~G4DataSet () virtual
Definition at line 105 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 105 of file G4DataSet.cc
References algorithm, data, energies, and pdf.
G4DataSet::G4DataSet () private
G4DataSet::G4DataSet (const G4DataSet & copy) private
Member Function Documentation
virtual void G4DataSet::AddComponent (G4IDataSet *) inline virtual
Implements G4IDataSet.
Definition at line 78 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 78 of file G4DataSet.hh
void G4DataSet::BuildPdf () private virtual
Definition at line 352 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 352 of file G4DataSet.cc
References IntegrationFunction(), G4Integrator< T, F >::Legendre96(), pdf, and sum.
Referenced by G4DataSet(), and LoadData().
size_t G4DataSet::FindLowerBound (G4double energy) const private
Definition at line 302 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 302 of file G4DataSet.cc
References energies.
Referenced by FindValue(), IntegrationFunction(), and RandomSelect().
size_t G4DataSet::FindLowerBound (G4double x, G4DataVector * values) const private
Definition at line 319 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 319 of file G4DataSet.cc
G4double G4DataSet::FindValue (G4double x, G4int componentId = 0) const virtual
Implements G4IDataSet.
Definition at line 113 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 113 of file G4DataSet.cc
References algorithm, G4IInterpolator::Calculate(), energies, FatalException, FindLowerBound(), and G4Exception().
G4String G4DataSet::FullFileName (const G4String & fileName) const private
Definition at line 336 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 336 of file G4DataSet.cc
References FatalException, G4Exception(), and z.
Referenced by LoadData(), and SaveData().
virtual const G4IDataSet* G4DataSet::GetComponent (G4int) const inline virtual
Implements G4IDataSet.
Definition at line 76 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 76 of file G4DataSet.hh
virtual const G4DataVector& G4DataSet::GetData (G4int) const inline virtual
Implements G4IDataSet.
Definition at line 83 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DataSet.hh
References data.
virtual const G4DataVector& G4DataSet::GetEnergies (G4int) const inline virtual
Implements G4IDataSet.
Definition at line 82 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DataSet.hh
References energies.
G4double G4DataSet::IntegrationFunction (G4double x) private
Definition at line 410 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 410 of file G4DataSet.cc
References algorithm, bin, G4IInterpolator::Calculate(), G4LinInterpolation::Calculate(), energies, FindLowerBound(), and y.
Referenced by BuildPdf().
G4bool G4DataSet::LoadData (const G4String & fileName) virtual
Implements G4IDataSet.
Definition at line 175 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 175 of file G4DataSet.cc
References a, BuildPdf(), FatalException, FullFileName(), G4Exception(), in, message(), randomSet, SetEnergiesData(), unitData, and unitEnergies.
virtual size_t G4DataSet::NumberOfComponents (void) const inline virtual
Implements G4IDataSet.
Definition at line 80 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4DataSet.hh
G4DataSet& G4DataSet::operator= (const G4DataSet & right) private
void G4DataSet::PrintData (void) const virtual
Implements G4IDataSet.
Definition at line 130 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 130 of file G4DataSet.cc
References energies, G4cout, G4endl, pdf, unitData, and unitEnergies.
G4double G4DataSet::RandomSelect (G4int componentId = 0) const virtual
Implements G4IDataSet.
Definition at line 382 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 382 of file G4DataSet.cc
References algorithm, bin, G4IInterpolator::Calculate(), G4LinInterpolation::Calculate(), energies, FatalException, FindLowerBound(), G4Exception(), G4UniformRand, pdf, and x.
G4bool G4DataSet::SaveData (const G4String & fileName) const virtual
Implements G4IDataSet.
Definition at line 228 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 228 of file G4DataSet.cc
References energies, FatalException, FullFileName(), G4Exception(), left, message(), unitData, and unitEnergies.
void G4DataSet::SetEnergiesData (G4DataVector * xData, G4DataVector * data, G4int componentId) virtual
Implements G4IDataSet.
Definition at line 150 of file G4DataSet.cc.
View newest version in sPHENIX GitHub at line 150 of file G4DataSet.cc
References data, energies, FatalException, and G4Exception().
Referenced by LoadData().
Member Data Documentation
G4IInterpolator* G4DataSet::algorithm private
Definition at line 113 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 113 of file G4DataSet.hh
Referenced by FindValue(), G4DataSet(), IntegrationFunction(), RandomSelect(), and ~G4DataSet().
G4DataVector* G4DataSet::data private
Definition at line 111 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 111 of file G4DataSet.hh
Referenced by GetData(), SetEnergiesData(), and ~G4DataSet().
G4DataVector* G4DataSet::energies private
Definition at line 110 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DataSet.hh
Referenced by FindLowerBound(), FindValue(), G4DataSet(), GetEnergies(), IntegrationFunction(), PrintData(), RandomSelect(), SaveData(), SetEnergiesData(), and ~G4DataSet().
G4DataVector* G4DataSet::pdf private
Definition at line 118 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 118 of file G4DataSet.hh
Referenced by BuildPdf(), PrintData(), RandomSelect(), and ~G4DataSet().
G4bool G4DataSet::randomSet private
Definition at line 119 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 119 of file G4DataSet.hh
Referenced by G4DataSet(), and LoadData().
G4double G4DataSet::unitData private
Definition at line 116 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 116 of file G4DataSet.hh
Referenced by LoadData(), PrintData(), and SaveData().
G4double G4DataSet::unitEnergies private
Definition at line 115 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 115 of file G4DataSet.hh
Referenced by LoadData(), PrintData(), and SaveData().
G4int G4DataSet::z private
Definition at line 108 of file G4DataSet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4DataSet.hh
Referenced by FullFileName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4DataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/src/G4DataSet.cc