ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_importXML_V_W_XYs.cc File Reference
xDataTOM_importXML_V_W_XYs.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <ctype.h>
#include "xDataTOM_importXML_private.h"
Functions
static int xDataXML_V_W_XYs_W_XYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_W_XYs *W_XYs, xDataTOM_axes *axes)
int xDataXML_V_W_XYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
Function Documentation
static int xDataXML_V_W_XYs_W_XYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_W_XYs * W_XYs, xDataTOM_axes * axes) static
Definition at line 58 of file xDataTOM_importXML_V_W_XYs.cc.
View newest version in sPHENIX GitHub at line 58 of file xDataTOM_importXML_V_W_XYs.cc
References xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), and xDataXML_W_XYsDataToTOM().
Referenced by xDataXML_V_W_XYsToTOM().
int xDataXML_V_W_XYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 21 of file xDataTOM_importXML_V_W_XYs.cc.
View newest version in sPHENIX GitHub at line 21 of file xDataTOM_importXML_V_W_XYs.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), BTOF::length, xDataXML_element_s::name, smr_freeMemory(), smr_setReportError3, xDataTOM_V_W_XYs_s::W_XYs, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getLabel(), xDataTOM_smrLibraryID, xDataTOM_V_W_XYs_ID, xDataTOM_V_W_XYs_initialize(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_numberOfElementsByTagName(), and xDataXML_V_W_XYs_W_XYsToTOM().
Referenced by xDataXML_constructTOM().