ECCE @ EIC Software: G4RDeIonisationCrossSectionHandler Class Reference
G4RDeIonisationCrossSectionHandler Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeIonisationCrossSectionHandler.hh>
Public Member Functions
G4RDeIonisationCrossSectionHandler (const G4RDVEnergySpectrum *spec, G4RDVDataSetAlgorithm *alg, G4double emin, G4double emax, G4int nbin)
~G4RDeIonisationCrossSectionHandler ()
Public Member Functions inherited from G4RDVCrossSectionHandler
G4RDVCrossSectionHandler ()
G4RDVCrossSectionHandler (G4RDVDataSetAlgorithm *interpolation, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int nBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
virtual ~G4RDVCrossSectionHandler ()
void Initialise (G4RDVDataSetAlgorithm *interpolation=0, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int numberOfBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
G4int SelectRandomAtom (const G4MaterialCutsCouple *couple, G4double e) const
const G4Element * SelectRandomElement (const G4MaterialCutsCouple *material, G4double e) const
G4int SelectRandomShell (G4int Z, G4double e) const
G4RDVEMDataSet * BuildMeanFreePathForMaterials (const G4DataVector *energyCuts=0)
G4double FindValue (G4int Z, G4double e) const
G4double FindValue (G4int Z, G4double e, G4int shellIndex) const
G4double ValueForMaterial (const G4Material *material, G4double e) const
void LoadData (const G4String &dataFile)
void LoadShellData (const G4String &dataFile)
void PrintData () const
void Clear ()
Protected Member Functions
std::vector< G4RDVEMDataSet * > * BuildCrossSectionsForMaterials (const G4DataVector &energyVector, const G4DataVector *energyCuts)
Protected Member Functions inherited from G4RDVCrossSectionHandler
G4int NumberOfComponents (G4int Z) const
void ActiveElements ()
virtual G4RDVDataSetAlgorithm * CreateInterpolation ()
const G4RDVDataSetAlgorithm * GetInterpolation () const
Private Member Functions
G4RDeIonisationCrossSectionHandler & operator= (const G4RDeIonisationCrossSectionHandler &right)
G4RDeIonisationCrossSectionHandler (const G4RDeIonisationCrossSectionHandler &)
Private Attributes
const G4RDVEnergySpectrum * theParam
G4RDVDataSetAlgorithm * interp
Detailed Description
Definition at line 61 of file G4RDeIonisationCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RDeIonisationCrossSectionHandler.hh
Constructor & Destructor Documentation
G4RDeIonisationCrossSectionHandler::G4RDeIonisationCrossSectionHandler (const G4RDVEnergySpectrum * spec, G4RDVDataSetAlgorithm * alg, G4double emin, G4double emax, G4int nbin)
Definition at line 60 of file G4RDeIonisationCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 60 of file G4RDeIonisationCrossSectionHandler.cc
References G4RDVCrossSectionHandler::Initialise(), and interp.
G4RDeIonisationCrossSectionHandler::~G4RDeIonisationCrossSectionHandler ()
Definition at line 71 of file G4RDeIonisationCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 71 of file G4RDeIonisationCrossSectionHandler.cc
References interp.
G4RDeIonisationCrossSectionHandler::G4RDeIonisationCrossSectionHandler (const G4RDeIonisationCrossSectionHandler &) private
Member Function Documentation
std::vector< G4RDVEMDataSet * > * G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials (const G4DataVector & energyVector, const G4DataVector * energyCuts) protected virtual
Implements G4RDVCrossSectionHandler.
Definition at line 77 of file G4RDeIonisationCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 77 of file G4RDeIonisationCrossSectionHandler.cc
References G4RDVEMDataSet::AddComponent(), bin, G4RDVDataSetAlgorithm::Clone(), Acts::VectorHelpers::cross(), e, G4RDVCrossSectionHandler::FindValue(), G4cout, G4endl, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetName(), G4Material::GetNumberOfElements(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), interp, m, material(), MeV, n, G4RDVCrossSectionHandler::NumberOfComponents(), G4RDVEnergySpectrum::Probability(), theParam, and Z.
G4RDeIonisationCrossSectionHandler& G4RDeIonisationCrossSectionHandler::operator= (const G4RDeIonisationCrossSectionHandler & right) private
Member Data Documentation
G4RDVDataSetAlgorithm* G4RDeIonisationCrossSectionHandler::interp private
Definition at line 88 of file G4RDeIonisationCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RDeIonisationCrossSectionHandler.hh
Referenced by BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler(), and ~G4RDeIonisationCrossSectionHandler().
const G4RDVEnergySpectrum* G4RDeIonisationCrossSectionHandler::theParam private
Definition at line 86 of file G4RDeIonisationCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RDeIonisationCrossSectionHandler.hh
Referenced by BuildCrossSectionsForMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeIonisationCrossSectionHandler.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDeIonisationCrossSectionHandler.cc