ECCE @ EIC Software: GB05DetectorConstruction Class Reference
GB05DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/include/GB05DetectorConstruction.hh>
Public Member Functions
GB05DetectorConstruction ()
~GB05DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 40 of file GB05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 40 of file GB05DetectorConstruction.hh
Constructor & Destructor Documentation
GB05DetectorConstruction::GB05DetectorConstruction ()
Definition at line 51 of file GB05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 51 of file GB05DetectorConstruction.cc
GB05DetectorConstruction::~GB05DetectorConstruction ()
Definition at line 57 of file GB05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 57 of file GB05DetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * GB05DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 62 of file GB05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 62 of file GB05DetectorConstruction.cc
References cm, G4NistManager::Instance(), and m.
void GB05DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 126 of file GB05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 126 of file GB05DetectorConstruction.cc
References G4SDManager::AddNewDetector(), GB05BOptrSplitAndKillByCrossSection::AddProcessToEquipoise(), G4VBiasingOperator::AttachTo(), G4cout, G4endl, G4LogicalVolumeStore::GetInstance(), G4VBiasingOperator::GetName(), G4SDManager::GetSDMpointer(), G4LogicalVolumeStore::GetVolume(), and G4LogicalVolume::SetSensitiveDetector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/include/GB05DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/src/GB05DetectorConstruction.cc