ECCE @ EIC Software: G4SDParticleFilter Class Reference
G4SDParticleFilter Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4SDParticleFilter.hh>
Public Member Functions
G4SDParticleFilter (G4String name)
G4SDParticleFilter (G4String name, const G4String &particleName)
G4SDParticleFilter (G4String name, const std::vector< G4String > &particleNames)
G4SDParticleFilter (G4String name, const std::vector< G4ParticleDefinition * > &particleDef)
virtual ~G4SDParticleFilter ()
virtual G4bool Accept (const G4Step *) const
void add (const G4String &particleName)
void addIon (G4int Z, G4int A)
void show ()
Public Member Functions inherited from G4VSDFilter
G4VSDFilter (G4String name)
virtual ~G4VSDFilter ()
G4String GetName () const
Private Attributes
std::vector
< G4ParticleDefinition * > thePdef
std::vector< G4int > theIonZ
std::vector< G4int > theIonA
Additional Inherited Members
Protected Attributes inherited from G4VSDFilter
G4String filterName
Detailed Description
Definition at line 52 of file G4SDParticleFilter.hh.
View newest version in sPHENIX GitHub at line 52 of file G4SDParticleFilter.hh
Constructor & Destructor Documentation
G4SDParticleFilter::G4SDParticleFilter (G4String name)
Definition at line 45 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 45 of file G4SDParticleFilter.cc
References theIonA, theIonZ, and thePdef.
G4SDParticleFilter::G4SDParticleFilter (G4String name, const G4String & particleName)
Definition at line 53 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 53 of file G4SDParticleFilter.cc
References FatalException, G4ParticleTable::FindParticle(), G4Exception(), G4ParticleTable::GetParticleTable(), theIonA, theIonZ, and thePdef.
G4SDParticleFilter::G4SDParticleFilter (G4String name, const std::vector< G4String > & particleNames)
Definition at line 72 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 72 of file G4SDParticleFilter.cc
References FatalException, G4ParticleTable::FindParticle(), G4Exception(), G4ParticleTable::GetParticleTable(), theIonA, theIonZ, and thePdef.
G4SDParticleFilter::G4SDParticleFilter (G4String name, const std::vector< G4ParticleDefinition * > & particleDef)
Definition at line 93 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 93 of file G4SDParticleFilter.cc
References FatalException, G4Exception(), theIonA, and theIonZ.
G4SDParticleFilter::~G4SDParticleFilter () virtual
Definition at line 106 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 106 of file G4SDParticleFilter.cc
References theIonA, theIonZ, and thePdef.
Member Function Documentation
G4bool G4SDParticleFilter::Accept (const G4Step * aStep) const virtual
Implements G4VSDFilter.
Definition at line 113 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 113 of file G4SDParticleFilter.cc
References FALSE, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4Track::GetDefinition(), G4Step::GetTrack(), theIonA, theIonZ, thePdef, and TRUE.
Referenced by G4SDParticleWithEnergyFilter::Accept().
void G4SDParticleFilter::add (const G4String & particleName)
Definition at line 131 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 131 of file G4SDParticleFilter.cc
References FatalException, G4ParticleTable::FindParticle(), G4Exception(), G4ParticleTable::GetParticleTable(), and thePdef.
Referenced by G4SDParticleWithEnergyFilter::add(), RE02DetectorConstruction::ConstructSDandField(), RE06ParallelWorld::SetupDetectors(), and RE06DetectorConstruction::SetupDetectors().
void G4SDParticleFilter::addIon (G4int Z, G4int A)
Definition at line 149 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 149 of file G4SDParticleFilter.cc
References G4cout, G4endl, theIonA, and theIonZ.
void G4SDParticleFilter::show ()
Definition at line 160 of file G4SDParticleFilter.cc.
View newest version in sPHENIX GitHub at line 160 of file G4SDParticleFilter.cc
References G4cout, G4endl, theIonA, theIonZ, and thePdef.
Referenced by G4SDParticleWithEnergyFilter::show().
Member Data Documentation
std::vector<G4int> G4SDParticleFilter::theIonA private
Definition at line 79 of file G4SDParticleFilter.hh.
View newest version in sPHENIX GitHub at line 79 of file G4SDParticleFilter.hh
Referenced by Accept(), addIon(), G4SDParticleFilter(), show(), and ~G4SDParticleFilter().
std::vector<G4int> G4SDParticleFilter::theIonZ private
Definition at line 78 of file G4SDParticleFilter.hh.
View newest version in sPHENIX GitHub at line 78 of file G4SDParticleFilter.hh
Referenced by Accept(), addIon(), G4SDParticleFilter(), show(), and ~G4SDParticleFilter().
std::vector<G4ParticleDefinition*> G4SDParticleFilter::thePdef private
Definition at line 77 of file G4SDParticleFilter.hh.
View newest version in sPHENIX GitHub at line 77 of file G4SDParticleFilter.hh
Referenced by Accept(), add(), G4SDParticleFilter(), show(), and ~G4SDParticleFilter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4SDParticleFilter.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4SDParticleFilter.cc