ECCE @ EIC Software: G4BinaryLightIonReaction Class Reference
G4BinaryLightIonReaction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4BinaryLightIonReaction.hh>
Public Member Functions
G4BinaryLightIonReaction (G4VPreCompoundModel *ptr=0)
virtual ~G4BinaryLightIonReaction ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &theNucleus)
void SetPrecompound (G4VPreCompoundModel *ptr)
void SetDeExcitation (G4ExcitationHandler *ptr)
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4bool EnergyAndMomentumCorrector (G4ReactionProductVector *products, G4LorentzVector &TotalCollisionMom)
G4bool SetLighterAsProjectile (G4LorentzVector &mom, const G4LorentzRotation &toBreit)
G4ReactionProductVector * FuseNucleiAndPrompound (const G4LorentzVector &mom)
G4ReactionProductVector * Interact (G4LorentzVector &mom, const G4LorentzRotation &)
G4double GetProjectileExcitation ()
void DeExciteSpectatorNucleus (G4ReactionProductVector *spectators, G4ReactionProductVector *cascaders, G4double theStatisticalExEnergy, G4LorentzVector &momentum)
G4LorentzVector SortResult (G4ReactionProductVector *result, G4ReactionProductVector *spectators, G4ReactionProductVector *cascaders)
Private Attributes
G4BinaryCascade * theModel
G4ExcitationHandler * theHandler
G4VPreCompoundModel * theProjectileFragmentation
G4HadFinalState theResult
G4int pA
G4int pZ
G4int tA
G4int tZ
G4int spectatorA
G4int spectatorZ
G4Fancy3DNucleus * projectile3dNucleus
G4Fancy3DNucleus * target3dNucleus
G4FermiMomentum theFermi
G4LorentzVector pInitialState
G4LorentzVector pFinalState
G4bool debug_G4BinaryLightIonReactionResults
Static Private Attributes
static G4int theBLIR_ID = -1
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 34 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 34 of file G4BinaryLightIonReaction.hh
Constructor & Destructor Documentation
G4BinaryLightIonReaction::G4BinaryLightIonReaction (G4VPreCompoundModel * ptr = 0)
Definition at line 57 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4BinaryLightIonReaction.cc
References debug_G4BinaryLightIonReactionResults, G4HadronicInteractionRegistry::FindModel(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4VPreCompoundModel::GetExcitationHandler(), G4HadronicInteractionRegistry::Instance(), G4PhysicsModelCatalog::Register(), theBLIR_ID, theHandler, theModel, and theProjectileFragmentation.
G4BinaryLightIonReaction::~G4BinaryLightIonReaction () virtual
Definition at line 88 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 88 of file G4BinaryLightIonReaction.cc
Member Function Documentation
G4HadFinalState * G4BinaryLightIonReaction::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & theNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 107 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 107 of file G4BinaryLightIonReaction.cc
References kdfinder::abs(), G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), Acts::IntegrationTest::debug, debug_G4BinaryLightIonReactionResults, DeExciteSpectatorNucleus(), CLHEP::HepLorentzVector::e(), EnergyAndMomentumCorrector(), eplus, FatalException, FuseNucleiAndPrompound(), G4cerr, G4cout, G4endl, G4Exception(), G4lrint(), G4HadProjectile::Get4Momentum(), G4DynamicParticle::Get4Momentum(), G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetBaryonNumber(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetGlobalTime(), G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), GetProjectileExcitation(), CLHEP::HepLorentzVector::getT(), G4Nucleus::GetZ_asInt(), Interact(), CLHEP::HepLorentzRotation::inverse(), isAlive, keV, CLHEP::Hep3Vector::mag(), CLHEP::HepLorentzVector::mag(), MeV, mom, momentum, pA, pFinalState, pInitialState, projectile3dNucleus, pZ, CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4DynamicParticle::Set4Momentum(), G4HadSecondary::SetCreatorModelType(), G4HadFinalState::SetEnergyChange(), SetLighterAsProjectile(), G4HadFinalState::SetMomentumChange(), G4HadFinalState::SetStatusChange(), CLHEP::HepLorentzVector::setT(), G4HadSecondary::SetTime(), SortResult(), spectatorA, spectatorZ, stopAndKill, tA, target3dNucleus, theResult, Acts::VectorHelpers::time(), tmp, tZ, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
void G4BinaryLightIonReaction::DeExciteSpectatorNucleus (G4ReactionProductVector * spectators, G4ReactionProductVector * cascaders, G4double theStatisticalExEnergy, G4LorentzVector & momentum) private
Definition at line 661 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 661 of file G4BinaryLightIonReaction.cc
References CLHEP::HepLorentzVector::boostVector(), G4ExcitationHandler::BreakItUp(), debug_G4BinaryLightIonReactionResults, EnergyAndMomentumCorrector(), G4cout, G4endl, G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), max, pA, pFinalState, pInitialState, G4Fragment::SetMomentum(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), G4Fragment::SetNumberOfParticles(), G4Fragment::SetZandA_asInt(), spectatorA, spectatorZ, theHandler, and tmp.
Referenced by ApplyYourself().
G4bool G4BinaryLightIonReaction::EnergyAndMomentumCorrector (G4ReactionProductVector * products, G4LorentzVector & TotalCollisionMom) private
Definition at line 369 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 369 of file G4BinaryLightIonReaction.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), debug_G4BinaryLightIonReactionResults, E, CLHEP::HepLorentzVector::e(), FALSE, G4cout, G4endl, G4Log(), CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::m2(), CLHEP::Hep3Vector::mag2(), max, mom, Scale(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setVect(), sqr(), TRUE, and CLHEP::HepLorentzVector::vect().
Referenced by ApplyYourself(), and DeExciteSpectatorNucleus().
G4ReactionProductVector * G4BinaryLightIonReaction::FuseNucleiAndPrompound (const G4LorentzVector & mom) private
Definition at line 478 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 478 of file G4BinaryLightIonReaction.cc
References G4VPreCompoundModel::DeExcite(), CLHEP::HepLorentzVector::e(), G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), CLHEP::HepLorentzVector::m2(), pA, pZ, G4Fragment::SetMomentum(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), G4Fragment::SetNumberOfParticles(), G4Fragment::SetZandA_asInt(), sqr(), CLHEP::HepLorentzVector::t(), tA, theProjectileFragmentation, tZ, and CLHEP::HepLorentzVector::vect().
Referenced by ApplyYourself().
G4double G4BinaryLightIonReaction::GetProjectileExcitation () private
Definition at line 606 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 606 of file G4BinaryLightIonReaction.cc
References G4Nucleon::AreYouHit(), G4Nucleon::GetDefinition(), G4VNuclearDensity::GetDensity(), G4FermiMomentum::GetFermiMomentum(), G4Nucleon::GetMomentum(), G4Fancy3DNucleus::GetNextNucleon(), G4Fancy3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetPosition(), CLHEP::HepLorentzVector::mag(), projectile3dNucleus, G4Fancy3DNucleus::StartLoop(), CLHEP::HepLorentzVector::t(), and theFermi.
Referenced by ApplyYourself().
G4ReactionProductVector * G4BinaryLightIonReaction::Interact (G4LorentzVector & mom, const G4LorentzRotation & toBreit) private
Definition at line 515 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 515 of file G4BinaryLightIonReaction.cc
References G4Fancy3DNucleus::CenterNucleons(), fermi, G4cout, G4endl, G4UniformRand, G4KineticTrack::Get4Momentum(), G4Fancy3DNucleus::GetCharge(), G4Nucleon::GetDefinition(), G4FermiMomentum::GetFermiMomentum(), G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4Fancy3DNucleus::GetMass(), G4Fancy3DNucleus::GetMassNumber(), G4Nucleon::GetMomentum(), G4Fancy3DNucleus::GetNextNucleon(), G4Fancy3DNucleus::GetNuclearDensity(), G4Fancy3DNucleus::GetOuterRadius(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetPosition(), G4FermiMomentum::Init(), G4Fancy3DNucleus::Init(), it, CLHEP::Hep3Vector::mag(), mass, G4KineticTrack::outside, pA, pos(), projectile3dNucleus, G4BinaryCascade::Propagate(), pZ, G4KineticTrack::SetProjectilePotential(), G4KineticTrack::SetState(), CLHEP::HepLorentzVector::setX(), CLHEP::HepLorentzVector::setY(), CLHEP::HepLorentzVector::setZ(), sqr(), G4Fancy3DNucleus::StartLoop(), tA, target3dNucleus, theFermi, theModel, tZ, and CLHEP::HepLorentzVector::vect().
Referenced by ApplyYourself().
void G4BinaryLightIonReaction::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 91 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 91 of file G4BinaryLightIonReaction.cc
void G4BinaryLightIonReaction::SetDeExcitation (G4ExcitationHandler * ptr) inline
Definition at line 78 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BinaryLightIonReaction.hh
References G4VPreCompoundModel::SetExcitationHandler(), theHandler, and theProjectileFragmentation.
G4bool G4BinaryLightIonReaction::SetLighterAsProjectile (G4LorentzVector & mom, const G4LorentzRotation & toBreit) private
Definition at line 463 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 463 of file G4BinaryLightIonReaction.cc
References G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), it, pA, pZ, tA, tmp, and tZ.
Referenced by ApplyYourself().
void G4BinaryLightIonReaction::SetPrecompound (G4VPreCompoundModel * ptr) inline
Definition at line 73 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 73 of file G4BinaryLightIonReaction.hh
References G4VPreCompoundModel::GetExcitationHandler(), theHandler, and theProjectileFragmentation.
G4LorentzVector G4BinaryLightIonReaction::SortResult (G4ReactionProductVector * result, G4ReactionProductVector * spectators, G4ReactionProductVector * cascaders) private
Definition at line 629 of file G4BinaryLightIonReaction.cc.
View newest version in sPHENIX GitHub at line 629 of file G4BinaryLightIonReaction.cc
References eplus, G4lrint(), pFinalState, spectatorA, and spectatorZ.
Referenced by ApplyYourself().
Member Data Documentation
G4bool G4BinaryLightIonReaction::debug_G4BinaryLightIonReactionResults private
Definition at line 66 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), DeExciteSpectatorNucleus(), EnergyAndMomentumCorrector(), and G4BinaryLightIonReaction().
G4int G4BinaryLightIonReaction::pA private
Definition at line 61 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), DeExciteSpectatorNucleus(), FuseNucleiAndPrompound(), Interact(), and SetLighterAsProjectile().
G4LorentzVector G4BinaryLightIonReaction::pFinalState private
Definition at line 64 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), DeExciteSpectatorNucleus(), and SortResult().
G4LorentzVector G4BinaryLightIonReaction::pInitialState private
Definition at line 64 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), and DeExciteSpectatorNucleus().
G4Fancy3DNucleus* G4BinaryLightIonReaction::projectile3dNucleus private
Definition at line 62 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), GetProjectileExcitation(), and Interact().
G4int G4BinaryLightIonReaction::pZ private
Definition at line 61 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), FuseNucleiAndPrompound(), Interact(), and SetLighterAsProjectile().
G4int G4BinaryLightIonReaction::spectatorA private
Definition at line 61 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), DeExciteSpectatorNucleus(), and SortResult().
G4int G4BinaryLightIonReaction::spectatorZ private
Definition at line 61 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), DeExciteSpectatorNucleus(), and SortResult().
G4int G4BinaryLightIonReaction::tA private
Definition at line 61 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), FuseNucleiAndPrompound(), Interact(), and SetLighterAsProjectile().
G4Fancy3DNucleus * G4BinaryLightIonReaction::target3dNucleus private
Definition at line 62 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), and Interact().
G4int G4BinaryLightIonReaction::theBLIR_ID = -1 static private
Definition at line 67 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 67 of file G4BinaryLightIonReaction.hh
Referenced by G4BinaryLightIonReaction().
G4FermiMomentum G4BinaryLightIonReaction::theFermi private
Definition at line 63 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BinaryLightIonReaction.hh
Referenced by GetProjectileExcitation(), and Interact().
G4ExcitationHandler* G4BinaryLightIonReaction::theHandler private
Definition at line 58 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BinaryLightIonReaction.hh
Referenced by DeExciteSpectatorNucleus(), G4BinaryLightIonReaction(), SetDeExcitation(), and SetPrecompound().
G4BinaryCascade* G4BinaryLightIonReaction::theModel private
Definition at line 57 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 57 of file G4BinaryLightIonReaction.hh
Referenced by G4BinaryLightIonReaction(), and Interact().
G4VPreCompoundModel* G4BinaryLightIonReaction::theProjectileFragmentation private
Definition at line 59 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BinaryLightIonReaction.hh
Referenced by FuseNucleiAndPrompound(), G4BinaryLightIonReaction(), SetDeExcitation(), and SetPrecompound().
G4HadFinalState G4BinaryLightIonReaction::theResult private
Definition at line 60 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself().
G4int G4BinaryLightIonReaction::tZ private
Definition at line 61 of file G4BinaryLightIonReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryLightIonReaction.hh
Referenced by ApplyYourself(), FuseNucleiAndPrompound(), Interact(), and SetLighterAsProjectile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4BinaryLightIonReaction.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4BinaryLightIonReaction.cc