ECCE @ EIC Software: G4CrossSectionPatch Class Reference
G4CrossSectionPatch Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CrossSectionPatch.hh>
Public Member Functions
G4CrossSectionPatch ()
virtual ~G4CrossSectionPatch ()
G4bool operator== (const G4CrossSectionPatch &right) const
G4bool operator!= (const G4CrossSectionPatch &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const =0
virtual G4bool IsValid (G4double e) const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual G4String Name () const =0
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Protected Member Functions
G4double Transition (const G4KineticTrack &trk1, const G4KineticTrack &trk2, const G4VCrossSectionSource *comp1, const G4VCrossSectionSource *comp2) const
G4double Transition (G4double ecm, G4double sigma1, G4double sigma2, G4double e1, G4double e2) const
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Member Functions
G4CrossSectionPatch (const G4CrossSectionPatch &right)
G4CrossSectionPatch & operator= (const G4CrossSectionPatch &right)
Detailed Description
Definition at line 50 of file G4CrossSectionPatch.hh.
View newest version in sPHENIX GitHub at line 50 of file G4CrossSectionPatch.hh
Constructor & Destructor Documentation
G4CrossSectionPatch::G4CrossSectionPatch ()
Definition at line 48 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 48 of file G4CrossSectionPatch.cc
G4CrossSectionPatch::~G4CrossSectionPatch () virtual
Definition at line 52 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 52 of file G4CrossSectionPatch.cc
G4CrossSectionPatch::G4CrossSectionPatch (const G4CrossSectionPatch & right) private
Member Function Documentation
G4double G4CrossSectionPatch::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 68 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 68 of file G4CrossSectionPatch.cc
References components, G4VCrossSectionSource::CrossSection(), G4KineticTrack::Get4Momentum(), GetComponents(), G4VCrossSectionSource::HighLimit(), G4VCrossSectionSource::IsValid(), G4VCrossSectionSource::LowLimit(), and Transition().
virtual const G4CrossSectionVector* G4CrossSectionPatch::GetComponents () const pure virtual
Implements G4VCrossSectionSource.
Implemented in G4XNNElastic, G4XnpElastic, G4XnpTotal, and G4XNNTotal.
Referenced by CrossSection(), and IsValid().
G4bool G4CrossSectionPatch::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 109 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 109 of file G4CrossSectionPatch.cc
References components, GetComponents(), G4VCrossSectionSource::IsValid(), and n.
G4bool G4CrossSectionPatch::operator!= (const G4CrossSectionPatch & right) const
Definition at line 62 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 62 of file G4CrossSectionPatch.cc
G4CrossSectionPatch& G4CrossSectionPatch::operator= (const G4CrossSectionPatch & right) private
G4bool G4CrossSectionPatch::operator== (const G4CrossSectionPatch & right) const
Definition at line 56 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 56 of file G4CrossSectionPatch.cc
G4double G4CrossSectionPatch::Transition (const G4KineticTrack & trk1, const G4KineticTrack & trk2, const G4VCrossSectionSource * comp1, const G4VCrossSectionSource * comp2) const protected
Definition at line 133 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 133 of file G4CrossSectionPatch.cc
References G4VCrossSectionSource::CrossSection(), denom, G4KineticTrack::Get4Momentum(), G4VCrossSectionSource::HighLimit(), G4VCrossSectionSource::LowLimit(), and ratio.
Referenced by CrossSection().
G4double G4CrossSectionPatch::Transition (G4double ecm, G4double sigma1, G4double sigma2, G4double e1, G4double e2) const protected
Definition at line 156 of file G4CrossSectionPatch.cc.
View newest version in sPHENIX GitHub at line 156 of file G4CrossSectionPatch.cc
References denom, e1, and ratio.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CrossSectionPatch.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CrossSectionPatch.cc