ECCE @ EIC Software: G4VScheduler Class Reference
G4VScheduler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4VScheduler.hh>
Public Member Functions
virtual void Initialize ()
virtual void Reset ()
virtual void SetVerbose (int)
virtual void SetGun (G4ITGun *)
virtual void Process ()
virtual G4bool IsRunning ()
virtual G4ITModelHandler * GetModelHandler ()
virtual void RegisterModel (G4VITStepModel *, double)
virtual void SetEndTime (const double)
virtual void SetTimeTolerance (double)
virtual double GetTimeTolerance () const
virtual void SetMaxZeroTimeAllowed (int)
virtual int GetMaxZeroTimeAllowed () const
virtual void SetTimeSteps (std::map< double, double > *)
virtual void AddTimeStep (double, double)
virtual void SetDefaultTimeStep (double)
virtual double GetLimitingTimeStep () const
virtual G4int GetNbSteps () const
virtual void SetMaxNbSteps (G4int)
virtual G4int GetMaxNbSteps () const
virtual G4double GetStartTime () const
virtual G4double GetEndTime () const
virtual G4double GetTimeStep () const
virtual G4double GetPreviousTimeStep () const
virtual G4double GetGlobalTime () const
virtual void SetUserAction (G4UserTimeStepAction *)
virtual G4UserTimeStepAction * GetUserTimeStepAction () const
virtual void SetInteractivity (G4ITTrackingInteractivity *)
virtual G4ITTrackingInteractivity * GetInteractivity ()
Static Public Member Functions
static G4VScheduler * Instance ()
Protected Member Functions
G4VScheduler ()
virtual ~G4VScheduler ()
Static Private Attributes
static G4ThreadLocal G4VScheduler * fpInstance
Detailed Description
Definition at line 46 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VScheduler.hh
Constructor & Destructor Documentation
G4VScheduler::G4VScheduler () protected
Definition at line 38 of file G4VScheduler.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VScheduler.cc
References fpInstance.
G4VScheduler::~G4VScheduler () protected virtual
Definition at line 43 of file G4VScheduler.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VScheduler.cc
References fpInstance.
Member Function Documentation
virtual void G4VScheduler::AddTimeStep (double , double) inline virtual
Reimplemented in G4Scheduler.
Definition at line 82 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VScheduler.hh
virtual G4double G4VScheduler::GetEndTime () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 89 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VScheduler.hh
virtual G4double G4VScheduler::GetGlobalTime () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 92 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VScheduler.hh
virtual G4ITTrackingInteractivity* G4VScheduler::GetInteractivity () inline virtual
Reimplemented in G4Scheduler.
Definition at line 98 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 98 of file G4VScheduler.hh
virtual double G4VScheduler::GetLimitingTimeStep () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 84 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VScheduler.hh
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength().
virtual G4int G4VScheduler::GetMaxNbSteps () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 87 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VScheduler.hh
virtual int G4VScheduler::GetMaxZeroTimeAllowed () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 79 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VScheduler.hh
virtual G4ITModelHandler* G4VScheduler::GetModelHandler () inline virtual
Reimplemented in G4Scheduler.
Definition at line 67 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VScheduler.hh
virtual G4int G4VScheduler::GetNbSteps () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 85 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VScheduler.hh
Referenced by G4ITTrackHolder::KillTracks().
virtual G4double G4VScheduler::GetPreviousTimeStep () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 91 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VScheduler.hh
virtual G4double G4VScheduler::GetStartTime () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 88 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VScheduler.hh
virtual G4double G4VScheduler::GetTimeStep () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 90 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VScheduler.hh
virtual double G4VScheduler::GetTimeTolerance () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 76 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VScheduler.hh
virtual G4UserTimeStepAction* G4VScheduler::GetUserTimeStepAction () const inline virtual
Reimplemented in G4Scheduler.
Definition at line 95 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 95 of file G4VScheduler.hh
virtual void G4VScheduler::Initialize () inline virtual
Reimplemented in G4Scheduler.
Definition at line 56 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VScheduler.hh
G4VScheduler * G4VScheduler::Instance (void) static
Definition at line 48 of file G4VScheduler.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VScheduler.cc
References G4Scheduler::Instance().
Referenced by G4UserTimeStepAction::AddTimeStep(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTrackHolder::KillTracks(), G4DNASecondOrderReaction::PostStepDoIt(), G4VUserChemistryList::RegisterTimeStepModel(), and G4UserTimeStepAction::SetMinimumTimeSteps().
virtual G4bool G4VScheduler::IsRunning () inline virtual
Reimplemented in G4Scheduler.
Definition at line 65 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VScheduler.hh
void G4VScheduler::Process () virtual
Reimplemented in G4Scheduler.
Definition at line 56 of file G4VScheduler.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VScheduler.cc
References FatalException, and G4Exception().
virtual void G4VScheduler::RegisterModel (G4VITStepModel * , double) inline virtual
Reimplemented in G4Scheduler.
Definition at line 69 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VScheduler.hh
Referenced by G4VUserChemistryList::RegisterTimeStepModel().
virtual void G4VScheduler::Reset () inline virtual
Reimplemented in G4Scheduler.
Definition at line 57 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VScheduler.hh
virtual void G4VScheduler::SetDefaultTimeStep (double) inline virtual
Reimplemented in G4Scheduler.
Definition at line 83 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 83 of file G4VScheduler.hh
virtual void G4VScheduler::SetEndTime (const double) inline virtual
Reimplemented in G4Scheduler.
Definition at line 71 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VScheduler.hh
virtual void G4VScheduler::SetGun (G4ITGun *) inline virtual
Reimplemented in G4Scheduler.
Definition at line 61 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VScheduler.hh
virtual void G4VScheduler::SetInteractivity (G4ITTrackingInteractivity *) inline virtual
Reimplemented in G4Scheduler.
Definition at line 97 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 97 of file G4VScheduler.hh
virtual void G4VScheduler::SetMaxNbSteps (G4int) inline virtual
Reimplemented in G4Scheduler.
Definition at line 86 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VScheduler.hh
virtual void G4VScheduler::SetMaxZeroTimeAllowed (int) inline virtual
Reimplemented in G4Scheduler.
Definition at line 78 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VScheduler.hh
virtual void G4VScheduler::SetTimeSteps (std::map< double, double > *) inline virtual
Reimplemented in G4Scheduler.
Definition at line 81 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VScheduler.hh
virtual void G4VScheduler::SetTimeTolerance (double) inline virtual
Reimplemented in G4Scheduler.
Definition at line 73 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VScheduler.hh
virtual void G4VScheduler::SetUserAction (G4UserTimeStepAction *) inline virtual
Reimplemented in G4Scheduler.
Definition at line 94 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VScheduler.hh
virtual void G4VScheduler::SetVerbose (int) inline virtual
Reimplemented in G4Scheduler.
Definition at line 59 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VScheduler.hh
Member Data Documentation
G4ThreadLocal G4VScheduler * G4VScheduler::fpInstance static private
Definition at line 52 of file G4VScheduler.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VScheduler.hh
Referenced by G4VScheduler(), and ~G4VScheduler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4VScheduler.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4VScheduler.cc