ECCE @ EIC Software: GFlashHitMaker Class Reference
GFlashHitMaker Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashHitMaker.hh>
Public Member Functions
GFlashHitMaker ()
~GFlashHitMaker ()
void make (GFlashEnergySpot *aSpot, const G4FastTrack *aT)
void SetNameOfWorldWithSD (const G4String &aName)
Private Member Functions
GFlashHitMaker (const GFlashHitMaker &)
GFlashHitMaker & operator= (const GFlashHitMaker &)
Private Attributes
G4TouchableHandle fTouchableHandle
G4Navigator * fpNavigator
G4bool fNaviSetup
G4String fWorldWithSdName
Name of the world containing the sensitive detector. If empty, default mass world is used.
Detailed Description
Definition at line 51 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 51 of file GFlashHitMaker.hh
Constructor & Destructor Documentation
GFlashHitMaker::GFlashHitMaker ()
Definition at line 45 of file GFlashHitMaker.cc.
View newest version in sPHENIX GitHub at line 45 of file GFlashHitMaker.cc
References fNaviSetup, fpNavigator, fTouchableHandle, and fWorldWithSdName.
GFlashHitMaker::~GFlashHitMaker ()
Definition at line 53 of file GFlashHitMaker.cc.
View newest version in sPHENIX GitHub at line 53 of file GFlashHitMaker.cc
References fpNavigator.
GFlashHitMaker::GFlashHitMaker (const GFlashHitMaker &) inline private
Definition at line 71 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 71 of file GFlashHitMaker.hh
Member Function Documentation
void GFlashHitMaker::make (GFlashEnergySpot * aSpot, const G4FastTrack * aT)
Navigator
Definition at line 58 of file GFlashHitMaker.cc.
View newest version in sPHENIX GitHub at line 58 of file GFlashHitMaker.cc
References FatalException, fNaviSetup, fpNavigator, fTouchableHandle, fWorldWithSdName, G4cerr, G4cout, G4endl, G4Exception(), G4LogicalVolume::GetFastSimulationManager(), G4VPhysicalVolume::GetLogicalVolume(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetParallelWorld(), GFlashEnergySpot::GetPosition(), G4LogicalVolume::GetSensitiveDetector(), G4TransportationManager::GetTransportationManager(), G4VTouchable::GetVolume(), G4Navigator::GetWorldVolume(), G4VGFlashSensitiveDetector::Hit(), and G4Navigator::SetWorldVolume().
Referenced by GFlashShowerModel::ElectronDoIt().
GFlashHitMaker& GFlashHitMaker::operator= (const GFlashHitMaker &) inline private
Definition at line 72 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 72 of file GFlashHitMaker.hh
void GFlashHitMaker::SetNameOfWorldWithSD (const G4String & aName) inline
Definition at line 59 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 59 of file GFlashHitMaker.hh
References fWorldWithSdName.
Referenced by ExGflash3DetectorConstruction::ConstructSDandField().
Member Data Documentation
G4bool GFlashHitMaker::fNaviSetup private
Definition at line 65 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 65 of file GFlashHitMaker.hh
Referenced by GFlashHitMaker(), and make().
G4Navigator* GFlashHitMaker::fpNavigator private
Definition at line 64 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 64 of file GFlashHitMaker.hh
Referenced by GFlashHitMaker(), make(), and ~GFlashHitMaker().
G4TouchableHandle GFlashHitMaker::fTouchableHandle private
Definition at line 59 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 59 of file GFlashHitMaker.hh
Referenced by GFlashHitMaker(), and make().
G4String GFlashHitMaker::fWorldWithSdName private
Name of the world containing the sensitive detector. If empty, default mass world is used.
Definition at line 67 of file GFlashHitMaker.hh.
View newest version in sPHENIX GitHub at line 67 of file GFlashHitMaker.hh
Referenced by GFlashHitMaker(), make(), and SetNameOfWorldWithSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashHitMaker.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/GFlashHitMaker.cc