ECCE @ EIC Software: F02PrimaryGeneratorAction Class Reference
F02PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02PrimaryGeneratorAction.hh>
Public Member Functions
F02PrimaryGeneratorAction (F02DetectorConstruction *)
virtual ~F02PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
void SetRndmFlag (G4String val)
void SetXVertex (G4double x)
void SetYVertex (G4double y)
void SetZVertex (G4double z)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Static Public Member Functions
static G4String GetPrimaryName ()
Private Attributes
G4ParticleGun * fParticleGun
F02DetectorConstruction * fDetector
F02PrimaryGeneratorMessenger * fGunMessenger
G4String fRndmFlag
G4double fXVertex
G4double fYVertex
G4double fZVertex
G4bool fVertexDefined
Static Private Attributes
static G4ParticleDefinition * fgPrimaryParticle = 0
Detailed Description
Definition at line 49 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 49 of file F02PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
F02PrimaryGeneratorAction::F02PrimaryGeneratorAction (F02DetectorConstruction * det)
Definition at line 55 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 55 of file F02PrimaryGeneratorAction.cc
References fgPrimaryParticle, fGunMessenger, G4ParticleTable::FindParticle(), fParticleGun, fXVertex, fYVertex, fZVertex, G4ParticleTable::GetParticleTable(), GeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
F02PrimaryGeneratorAction::~F02PrimaryGeneratorAction () virtual
Definition at line 93 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 93 of file F02PrimaryGeneratorAction.cc
References fGunMessenger, and fParticleGun.
Member Function Documentation
void F02PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 101 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 101 of file F02PrimaryGeneratorAction.cc
References fDetector, fgPrimaryParticle, fParticleGun, fRndmFlag, fVertexDefined, fXVertex, fYVertex, fZVertex, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), F02DetectorConstruction::GetAbsorberRadius(), G4ParticleGun::GetParticleDefinition(), G4VPrimaryGenerator::SetParticlePosition(), twopi, and G4InuclParticleNames::z0.
G4String F02PrimaryGeneratorAction::GetPrimaryName () static
Definition at line 136 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 136 of file F02PrimaryGeneratorAction.cc
References fgPrimaryParticle, and G4ParticleDefinition::GetParticleName().
void F02PrimaryGeneratorAction::SetRndmFlag (G4String val) inline
Definition at line 57 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file F02PrimaryGeneratorAction.hh
References fRndmFlag.
Referenced by F02PrimaryGeneratorMessenger::SetNewValue().
void F02PrimaryGeneratorAction::SetXVertex (G4double x)
Definition at line 143 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 143 of file F02PrimaryGeneratorAction.cc
References fVertexDefined, fXVertex, G4cout, G4endl, mm, and x.
Referenced by F02PrimaryGeneratorMessenger::SetNewValue().
void F02PrimaryGeneratorAction::SetYVertex (G4double y)
Definition at line 153 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 153 of file F02PrimaryGeneratorAction.cc
References fVertexDefined, fYVertex, G4cout, G4endl, mm, and y.
Referenced by F02PrimaryGeneratorMessenger::SetNewValue().
void F02PrimaryGeneratorAction::SetZVertex (G4double z)
Definition at line 163 of file F02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 163 of file F02PrimaryGeneratorAction.cc
References fVertexDefined, fZVertex, G4cout, G4endl, mm, and z.
Referenced by F02PrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
F02DetectorConstruction* F02PrimaryGeneratorAction::fDetector private
Definition at line 66 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file F02PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4ParticleDefinition * F02PrimaryGeneratorAction::fgPrimaryParticle = 0 static private
Definition at line 71 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file F02PrimaryGeneratorAction.hh
Referenced by F02PrimaryGeneratorAction(), GeneratePrimaries(), and GetPrimaryName().
F02PrimaryGeneratorMessenger* F02PrimaryGeneratorAction::fGunMessenger private
Definition at line 68 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file F02PrimaryGeneratorAction.hh
Referenced by F02PrimaryGeneratorAction(), and ~F02PrimaryGeneratorAction().
G4ParticleGun* F02PrimaryGeneratorAction::fParticleGun private
Definition at line 65 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file F02PrimaryGeneratorAction.hh
Referenced by F02PrimaryGeneratorAction(), GeneratePrimaries(), and ~F02PrimaryGeneratorAction().
G4String F02PrimaryGeneratorAction::fRndmFlag private
Definition at line 69 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file F02PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmFlag().
G4bool F02PrimaryGeneratorAction::fVertexDefined private
Definition at line 73 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file F02PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), SetXVertex(), SetYVertex(), and SetZVertex().
G4double F02PrimaryGeneratorAction::fXVertex private
Definition at line 72 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file F02PrimaryGeneratorAction.hh
Referenced by F02PrimaryGeneratorAction(), GeneratePrimaries(), and SetXVertex().
G4double F02PrimaryGeneratorAction::fYVertex private
Definition at line 72 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file F02PrimaryGeneratorAction.hh
Referenced by F02PrimaryGeneratorAction(), GeneratePrimaries(), and SetYVertex().
G4double F02PrimaryGeneratorAction::fZVertex private
Definition at line 72 of file F02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file F02PrimaryGeneratorAction.hh
Referenced by F02PrimaryGeneratorAction(), GeneratePrimaries(), and SetZVertex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field02/src/F02PrimaryGeneratorAction.cc