ECCE @ EIC Software: PHG4GDMLWriteSolids Class Reference
PHG4GDMLWriteSolids Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteSolids.hh>
Classes
class G4ThreeVectorCompare
Public Member Functions
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (PHG4GDMLAuxStructType myaux)
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
PHG4GDMLWriteSolids ()
virtual ~PHG4GDMLWriteSolids ()
void MultiUnionWrite (xercesc::DOMElement *solElement, const G4MultiUnion *const)
void BooleanWrite (xercesc::DOMElement *, const G4BooleanSolid *const)
void BoxWrite (xercesc::DOMElement *, const G4Box *const)
void ConeWrite (xercesc::DOMElement *, const G4Cons *const)
void ElconeWrite (xercesc::DOMElement *, const G4EllipticalCone *const)
void EllipsoidWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void EltubeWrite (xercesc::DOMElement *, const G4EllipticalTube *const)
void XtruWrite (xercesc::DOMElement *, const G4ExtrudedSolid *const)
void HypeWrite (xercesc::DOMElement *, const G4Hype *const)
void OrbWrite (xercesc::DOMElement *, const G4Orb *const)
void ParaWrite (xercesc::DOMElement *, const G4Para *const)
void ParaboloidWrite (xercesc::DOMElement *, const G4Paraboloid *const)
void PolyconeWrite (xercesc::DOMElement *, const G4Polycone *const)
void GenericPolyconeWrite (xercesc::DOMElement *, const G4GenericPolycone *const)
void PolyhedraWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void SphereWrite (xercesc::DOMElement *, const G4Sphere *const)
void TessellatedWrite (xercesc::DOMElement *, const G4TessellatedSolid *const)
void TetWrite (xercesc::DOMElement *, const G4Tet *const)
void TorusWrite (xercesc::DOMElement *, const G4Torus *const)
void GenTrapWrite (xercesc::DOMElement *, const G4GenericTrap *const)
void TrapWrite (xercesc::DOMElement *, const G4Trap *const)
void TrdWrite (xercesc::DOMElement *, const G4Trd *const)
void TubeWrite (xercesc::DOMElement *, const G4Tubs *const)
void CutTubeWrite (xercesc::DOMElement *, const G4CutTubs *const)
void TwistedboxWrite (xercesc::DOMElement *, const G4TwistedBox *const)
void TwistedtrapWrite (xercesc::DOMElement *, const G4TwistedTrap *const)
void TwistedtrdWrite (xercesc::DOMElement *, const G4TwistedTrd *const)
void TwistedtubsWrite (xercesc::DOMElement *, const G4TwistedTubs *const)
void ZplaneWrite (xercesc::DOMElement *, const G4double &, const G4double &, const G4double &)
void RZPointWrite (xercesc::DOMElement *, const G4double &, const G4double &)
void OpticalSurfaceWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
Protected Member Functions inherited from PHG4GDMLWriteMaterials
PHG4GDMLWriteMaterials ()
virtual ~PHG4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from PHG4GDMLWriteDefine
PHG4GDMLWriteDefine ()
virtual ~PHG4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from PHG4GDMLWrite
PHG4GDMLWrite ()
virtual ~PHG4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (PHG4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
std::vector< const G4VSolid * > solidList
xercesc::DOMElement * solidsElement
Protected Attributes inherited from PHG4GDMLWriteMaterials
std::vector< const G4Isotope * > isotopeList
std::vector< const G4Element * > elementList
std::vector< const G4Material * > materialList
xercesc::DOMElement * materialsElement
Protected Attributes inherited from PHG4GDMLWriteDefine
xercesc::DOMElement * defineElement
Protected Attributes inherited from PHG4GDMLWrite
G4String SchemaLocation
xercesc::DOMDocument * doc
xercesc::DOMElement * extElement
xercesc::DOMElement * userinfoElement
XMLCh tempStr [10000]
PHG4GDMLAuxListType auxList
Static Protected Attributes
static const G4int maxTransforms = 8
Additional Inherited Members
Static Public Member Functions inherited from PHG4GDMLWrite
static void SetAddPointerToName (G4bool)
Detailed Description
Definition at line 78 of file PHG4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 78 of file PHG4GDMLWriteSolids.hh
Constructor & Destructor Documentation
PHG4GDMLWriteSolids::PHG4GDMLWriteSolids () protected
Definition at line 72 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 72 of file PHG4GDMLWriteSolids.cc
PHG4GDMLWriteSolids::~PHG4GDMLWriteSolids () protected virtual
Definition at line 77 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 77 of file PHG4GDMLWriteSolids.cc
Member Function Documentation
void PHG4GDMLWriteSolids::AddSolid (const G4VSolid * const solidPtr) virtual
Definition at line 1029 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1029 of file PHG4GDMLWriteSolids.cc
References BooleanWrite(), BoxWrite(), ConeWrite(), CutTubeWrite(), ElconeWrite(), EllipsoidWrite(), EltubeWrite(), FatalException, G4Exception(), GenericPolyconeWrite(), GenTrapWrite(), G4VSolid::GetEntityType(), G4VSolid::GetName(), HypeWrite(), MultiUnionWrite(), OrbWrite(), ParaboloidWrite(), ParaWrite(), PolyconeWrite(), PolyhedraWrite(), solidList, solidsElement, SphereWrite(), TessellatedWrite(), TetWrite(), TorusWrite(), TrapWrite(), TrdWrite(), TubeWrite(), TwistedboxWrite(), TwistedtrapWrite(), TwistedtrdWrite(), TwistedtubsWrite(), and XtruWrite().
Referenced by BooleanWrite(), and PHG4GDMLWriteStructure::TraverseVolumeTree().
void PHG4GDMLWriteSolids::BooleanWrite (xercesc::DOMElement * solElement, const G4BooleanSolid * const boolean) protected
Definition at line 150 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 150 of file PHG4GDMLWriteSolids.cc
References AddSolid(), FatalException, PHG4GDMLWriteDefine::FirstpositionWrite(), PHG4GDMLWriteDefine::FirstrotationWrite(), G4Exception(), PHG4GDMLWrite::GenerateName(), PHG4GDMLWriteDefine::GetAngles(), G4VSolid::GetName(), PHG4GDMLWriteDefine::kAngularPrecision, PHG4GDMLWriteDefine::kLinearPrecision, maxTransforms, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), pos(), PHG4GDMLWriteDefine::PositionWrite(), PHG4GDMLWriteDefine::RotationWrite(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::BoxWrite (xercesc::DOMElement * solElement, const G4Box * const box) protected
Definition at line 266 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 266 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::ConeWrite (xercesc::DOMElement * solElement, const G4Cons * const cone) protected
Definition at line 280 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 280 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4Cons::GetDeltaPhiAngle(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4VSolid::GetName(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Cons::GetStartPhiAngle(), G4Cons::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::CutTubeWrite (xercesc::DOMElement * solElement, const G4CutTubs * const cuttube) protected
Definition at line 843 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 843 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4CutTubs::GetDeltaPhiAngle(), G4CutTubs::GetHighNorm(), G4CutTubs::GetInnerRadius(), G4CutTubs::GetLowNorm(), G4VSolid::GetName(), G4CutTubs::GetOuterRadius(), G4CutTubs::GetStartPhiAngle(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4CutTubs::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::ElconeWrite (xercesc::DOMElement * solElement, const G4EllipticalCone * const elcone) protected
Definition at line 306 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 306 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4EllipticalCone::GetSemiAxisX(), G4EllipticalCone::GetSemiAxisY(), G4EllipticalCone::GetZMax(), G4EllipticalCone::GetZTopCut(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::EllipsoidWrite (xercesc::DOMElement * solElement, const G4Ellipsoid * const ellipsoid) protected
Definition at line 322 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 322 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Ellipsoid::GetSemiAxisMax(), G4Ellipsoid::GetZBottomCut(), G4Ellipsoid::GetZTopCut(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::EltubeWrite (xercesc::DOMElement * solElement, const G4EllipticalTube * const eltube) protected
Definition at line 345 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 345 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4EllipticalTube::GetDx(), G4EllipticalTube::GetDy(), G4EllipticalTube::GetDz(), G4VSolid::GetName(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::GenericPolyconeWrite (xercesc::DOMElement * solElement, const G4GenericPolycone * const polycone) protected
Definition at line 510 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 510 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4GenericPolycone::GetCorner(), G4GenericPolycone::GetEndPhi(), G4VSolid::GetName(), G4GenericPolycone::GetNumRZCorner(), G4GenericPolycone::GetStartPhi(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), G4PolyconeSideRZ::r, RZPointWrite(), and G4PolyconeSideRZ::z.
Referenced by AddSolid().
void PHG4GDMLWriteSolids::GenTrapWrite (xercesc::DOMElement * solElement, const G4GenericTrap * const gtrap) protected
Definition at line 732 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 732 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4GenericTrap::GetVertices(), G4GenericTrap::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), x, and y.
Referenced by AddSolid().
void PHG4GDMLWriteSolids::HypeWrite (xercesc::DOMElement * solElement, const G4Hype * const hype) protected
Definition at line 404 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 404 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4Hype::GetInnerRadius(), G4Hype::GetInnerStereo(), G4VSolid::GetName(), G4Hype::GetOuterRadius(), G4Hype::GetOuterStereo(), G4Hype::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::MultiUnionWrite (xercesc::DOMElement * solElement, const G4MultiUnion * const) protected
Definition at line 83 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 83 of file PHG4GDMLWriteSolids.cc
References FatalException, and G4Exception().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::OpticalSurfaceWrite (xercesc::DOMElement * solElement, const G4OpticalSurface * const surf) protected
Definition at line 1003 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1003 of file PHG4GDMLWriteSolids.cc
References G4OpticalSurface::GetFinish(), G4OpticalSurface::GetModel(), G4SurfaceProperty::GetName(), G4OpticalSurface::GetPolish(), G4OpticalSurface::GetSigmaAlpha(), G4SurfaceProperty::GetType(), glisur, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by PHG4GDMLWriteStructure::BorderSurfaceCache(), and PHG4GDMLWriteStructure::SkinSurfaceCache().
void PHG4GDMLWriteSolids::OrbWrite (xercesc::DOMElement * solElement, const G4Orb * const orb) protected
Definition at line 426 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 426 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Orb::GetRadius(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::ParaboloidWrite (xercesc::DOMElement * solElement, const G4Paraboloid * const paraboloid) protected
Definition at line 464 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 464 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Paraboloid::GetRadiusMinusZ(), G4Paraboloid::GetRadiusPlusZ(), G4Paraboloid::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::ParaWrite (xercesc::DOMElement * solElement, const G4Para * const para) protected
Definition at line 438 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 438 of file PHG4GDMLWriteSolids.cc
References alpha, degree, PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetXHalfLength(), G4Para::GetYHalfLength(), G4Para::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), phi, and theta().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::PolyconeWrite (xercesc::DOMElement * solElement, const G4Polycone * const polycone) protected
Definition at line 481 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 481 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Polycone::GetOriginalParameters(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), G4PolyconeHistorical::Num_z_planes, G4PolyconeHistorical::Opening_angle, G4PolyconeHistorical::Rmax, G4PolyconeHistorical::Rmin, G4PolyconeHistorical::Start_angle, G4PolyconeHistorical::Z_values, and ZplaneWrite().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::PolyhedraWrite (xercesc::DOMElement * solElement, const G4Polyhedra * const polyhedra) protected
Definition at line 536 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 536 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4Polyhedra::GetCorner(), G4VSolid::GetName(), G4Polyhedra::GetNumRZCorner(), G4Polyhedra::GetOriginalParameters(), G4Polyhedra::IsGeneric(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, G4PolyhedraSideRZ::r, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, RZPointWrite(), G4PolyhedraHistorical::Start_angle, G4PolyhedraSideRZ::z, G4PolyhedraHistorical::Z_values, and ZplaneWrite().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::RZPointWrite (xercesc::DOMElement * element, const G4double & r, const G4double & z) protected
Definition at line 993 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 993 of file PHG4GDMLWriteSolids.cc
References mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by GenericPolyconeWrite(), and PolyhedraWrite().
void PHG4GDMLWriteSolids::SolidsWrite (xercesc::DOMElement * gdmlElement) virtual
Implements PHG4GDMLWrite.
Definition at line 1019 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1019 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::NewElement(), solidList, and solidsElement.
void PHG4GDMLWriteSolids::SphereWrite (xercesc::DOMElement * solElement, const G4Sphere * const sphere) protected
Definition at line 593 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 593 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4Sphere::GetDeltaPhiAngle(), G4Sphere::GetDeltaThetaAngle(), G4Sphere::GetInnerRadius(), G4VSolid::GetName(), G4Sphere::GetOuterRadius(), G4Sphere::GetStartPhiAngle(), G4Sphere::GetStartThetaAngle(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TessellatedWrite (xercesc::DOMElement * solElement, const G4TessellatedSolid * const tessellated) protected
Definition at line 617 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 617 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWriteDefine::AddPosition(), FatalException, test::fname, G4Exception(), PHG4GDMLWrite::GenerateName(), G4TessellatedSolid::GetFacet(), G4VSolid::GetName(), G4TessellatedSolid::GetNumberOfFacets(), G4VFacet::GetNumberOfVertices(), G4VFacet::GetVertex(), PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TetWrite (xercesc::DOMElement * solElement, const G4Tet * const tet) protected
Definition at line 690 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 690 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWriteDefine::AddPosition(), PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Tet::GetVertices(), PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TorusWrite (xercesc::DOMElement * solElement, const G4Torus * const torus) protected
Definition at line 713 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 713 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4Torus::GetDPhi(), G4VSolid::GetName(), G4Torus::GetRmax(), G4Torus::GetRmin(), G4Torus::GetRtor(), G4Torus::GetSPhi(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TrapWrite (xercesc::DOMElement * solElement, const G4Trap * const trap) protected
Definition at line 764 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 764 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Trap::GetSymAxis(), G4Trap::GetTanAlpha1(), G4Trap::GetTanAlpha2(), G4Trap::GetXHalfLength1(), G4Trap::GetXHalfLength2(), G4Trap::GetXHalfLength3(), G4Trap::GetXHalfLength4(), G4Trap::GetYHalfLength1(), G4Trap::GetYHalfLength2(), G4Trap::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), phi, and theta().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TrdWrite (xercesc::DOMElement * solElement, const G4Trd * const trd) protected
Definition at line 800 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 800 of file PHG4GDMLWriteSolids.cc
References PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TubeWrite (xercesc::DOMElement * solElement, const G4Tubs * const tube) protected
Definition at line 821 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 821 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4Tubs::GetDeltaPhiAngle(), G4Tubs::GetInnerRadius(), G4VSolid::GetName(), G4Tubs::GetOuterRadius(), G4Tubs::GetStartPhiAngle(), G4Tubs::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TwistedboxWrite (xercesc::DOMElement * solElement, const G4TwistedBox * const twistedbox) protected
Definition at line 877 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 877 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4TwistedBox::GetPhiTwist(), G4TwistedBox::GetXHalfLength(), G4TwistedBox::GetYHalfLength(), G4TwistedBox::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TwistedtrapWrite (xercesc::DOMElement * solElement, const G4TwistedTrap * const twistedtrap) protected
Definition at line 898 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 898 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4TwistedTrap::GetAzimuthalAnglePhi(), G4VSolid::GetName(), G4TwistedTrap::GetPhiTwist(), G4TwistedTrap::GetPolarAngleTheta(), G4TwistedTrap::GetTiltAngleAlpha(), G4TwistedTrap::GetX1HalfLength(), G4TwistedTrap::GetX2HalfLength(), G4TwistedTrap::GetX3HalfLength(), G4TwistedTrap::GetX4HalfLength(), G4TwistedTrap::GetY1HalfLength(), G4TwistedTrap::GetY2HalfLength(), G4TwistedTrap::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TwistedtrdWrite (xercesc::DOMElement * solElement, const G4TwistedTrd * const twistedtrd) protected
Definition at line 934 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 934 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4TwistedTrd::GetPhiTwist(), G4TwistedTrd::GetX1HalfLength(), G4TwistedTrd::GetX2HalfLength(), G4TwistedTrd::GetY1HalfLength(), G4TwistedTrd::GetY2HalfLength(), G4TwistedTrd::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::TwistedtubsWrite (xercesc::DOMElement * solElement, const G4TwistedTubs * const twistedtubs) protected
Definition at line 959 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 959 of file PHG4GDMLWriteSolids.cc
References degree, PHG4GDMLWrite::GenerateName(), G4TwistedTubs::GetDPhi(), G4TwistedTubs::GetInnerRadius(), G4VSolid::GetName(), G4TwistedTubs::GetOuterRadius(), G4TwistedTubs::GetPhiTwist(), G4TwistedTubs::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::XtruWrite (xercesc::DOMElement * solElement, const G4ExtrudedSolid * const xtru) protected
Definition at line 360 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 360 of file PHG4GDMLWriteSolids.cc
References G4ExtrudedSolid::ZSection::fOffset, G4ExtrudedSolid::ZSection::fScale, G4ExtrudedSolid::ZSection::fZ, PHG4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4ExtrudedSolid::GetNofVertices(), G4ExtrudedSolid::GetNofZSections(), G4ExtrudedSolid::GetVertex(), G4ExtrudedSolid::GetZSection(), mm, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by AddSolid().
void PHG4GDMLWriteSolids::ZplaneWrite (xercesc::DOMElement * element, const G4double & z, const G4double & rmin, const G4double & rmax) protected
Definition at line 982 of file PHG4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 982 of file PHG4GDMLWriteSolids.cc
References mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by PHG4GDMLWriteParamvol::Polycone_dimensionsWrite(), PolyconeWrite(), PHG4GDMLWriteParamvol::Polyhedra_dimensionsWrite(), and PolyhedraWrite().
Member Data Documentation
const G4int PHG4GDMLWriteSolids::maxTransforms = 8 static protected
Definition at line 147 of file PHG4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 147 of file PHG4GDMLWriteSolids.hh
Referenced by BooleanWrite(), and PHG4GDMLWriteStructure::TraverseVolumeTree().
std::vector<const G4VSolid*> PHG4GDMLWriteSolids::solidList protected
Definition at line 145 of file PHG4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 145 of file PHG4GDMLWriteSolids.hh
Referenced by AddSolid(), and SolidsWrite().
xercesc::DOMElement* PHG4GDMLWriteSolids::solidsElement protected
Definition at line 146 of file PHG4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 146 of file PHG4GDMLWriteSolids.hh
Referenced by AddSolid(), PHG4GDMLWriteStructure::BorderSurfaceCache(), PHG4GDMLWriteStructure::SkinSurfaceCache(), and SolidsWrite().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteSolids.hh
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteSolids.cc