ECCE @ EIC Software: G4ParticleChangeForLoss Class Reference
G4ParticleChangeForLoss Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForLoss.hh>
Public Member Functions
G4ParticleChangeForLoss ()
virtual ~G4ParticleChangeForLoss ()
G4Step * UpdateStepForAlongStep (G4Step *Step)
G4Step * UpdateStepForPostStep (G4Step *Step)
void InitializeForAlongStep (const G4Track &)
void InitializeForPostStep (const G4Track &)
G4double GetProposedCharge () const
void SetProposedCharge (G4double theCharge)
G4double GetCharge () const
void ProposeCharge (G4double finalCharge)
G4double GetProposedKineticEnergy () const
void SetProposedKineticEnergy (G4double proposedKinEnergy)
const G4ThreeVector & GetProposedMomentumDirection () const
void SetProposedMomentumDirection (const G4ThreeVector &dir)
const G4ThreeVector & GetMomentumDirection () const
void ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
void ProposeMomentumDirection (const G4ThreeVector &Pfinal)
const G4ThreeVector & GetProposedPolarization () const
void ProposePolarization (const G4ThreeVector &dir)
void ProposePolarization (G4double Px, G4double Py, G4double Pz)
const G4Track * GetCurrentTrack () const
void SetLowEnergyLimit (G4double elimit)
virtual void DumpInfo () const
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
virtual void Initialize (const G4Track &)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChangeForLoss (const G4ParticleChangeForLoss &right)
G4ParticleChangeForLoss & operator= (const G4ParticleChangeForLoss &right)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Private Attributes
const G4Track * currentTrack
G4double proposedKinEnergy
G4double lowEnergyLimit
G4double currentCharge
G4ThreeVector proposedMomentumDirection
G4ThreeVector proposedPolarization
Additional Inherited Members
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 59 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleChangeForLoss.hh
Constructor & Destructor Documentation
G4ParticleChangeForLoss::G4ParticleChangeForLoss ()
Definition at line 51 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleChangeForLoss.cc
References G4VParticleChange::debugFlag, G4cout, G4endl, NormalCondition, G4VParticleChange::theSteppingControlFlag, and G4VParticleChange::verboseLevel.
G4ParticleChangeForLoss::~G4ParticleChangeForLoss () virtual
Definition at line 64 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleChangeForLoss.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForLoss::G4ParticleChangeForLoss (const G4ParticleChangeForLoss & right) protected
Definition at line 74 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleChangeForLoss.cc
References currentCharge, currentTrack, G4cout, G4endl, lowEnergyLimit, proposedKinEnergy, proposedMomentumDirection, and G4VParticleChange::verboseLevel.
Member Function Documentation
G4bool G4ParticleChangeForLoss::CheckIt (const G4Track & aTrack) virtual
Reimplemented from G4VParticleChange.
Definition at line 159 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 159 of file G4ParticleChangeForLoss.cc
References G4VParticleChange::accuracyForException, G4VParticleChange::accuracyForWarning, G4VParticleChange::CheckIt(), DumpInfo(), EventMustBeAborted, G4cout, G4endl, G4Exception(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), m, MeV, proposedKinEnergy, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4ParticleChangeForLoss::DumpInfo () const virtual
Reimplemented from G4VParticleChange.
Definition at line 135 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 135 of file G4ParticleChangeForLoss.cc
References currentCharge, G4VParticleChange::DumpInfo(), eplus, G4cout, G4endl, MeV, proposedKinEnergy, proposedMomentumDirection, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CheckIt().
G4double G4ParticleChangeForLoss::GetCharge () const inline
Definition at line 159 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ParticleChangeForLoss.hh
References currentCharge.
const G4Track * G4ParticleChangeForLoss::GetCurrentTrack () const inline
Definition at line 206 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 206 of file G4ParticleChangeForLoss.hh
References currentTrack.
Referenced by G4PolarizedMollerBhabhaModel::SampleSecondaries().
const G4ThreeVector & G4ParticleChangeForLoss::GetMomentumDirection () const inline
Definition at line 181 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 181 of file G4ParticleChangeForLoss.hh
References proposedMomentumDirection.
G4double G4ParticleChangeForLoss::GetProposedCharge () const inline
Definition at line 154 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleChangeForLoss.hh
References currentCharge.
G4double G4ParticleChangeForLoss::GetProposedKineticEnergy () const inline
Definition at line 144 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParticleChangeForLoss.hh
References proposedKinEnergy.
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4EmBiasingManager::ApplySecondaryBiasing(), and G4VEnergyLossProcess::PostStepDoIt().
const G4ThreeVector & G4ParticleChangeForLoss::GetProposedMomentumDirection () const inline
Definition at line 175 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ParticleChangeForLoss.hh
References proposedMomentumDirection.
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4EmBiasingManager::ApplySecondaryBiasing(), and G4ePolarizedBremsstrahlungModel::SampleSecondaries().
const G4ThreeVector & G4ParticleChangeForLoss::GetProposedPolarization () const inline
Definition at line 212 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 212 of file G4ParticleChangeForLoss.hh
References proposedPolarization.
void G4ParticleChangeForLoss::InitializeForAlongStep (const G4Track & track) inline
Definition at line 231 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 231 of file G4ParticleChangeForLoss.hh
References currentCharge, G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), G4Track::GetTrackStatus(), G4Track::GetWeight(), G4VParticleChange::InitializeSecondaries(), proposedKinEnergy, G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNonIonizingEnergyDeposit, G4VParticleChange::theParentWeight, and G4VParticleChange::theStatusChange.
Referenced by G4NuclearStopping::AlongStepDoIt(), and G4VEnergyLossProcess::AlongStepDoIt().
void G4ParticleChangeForLoss::InitializeForPostStep (const G4Track & track) inline
Definition at line 243 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 243 of file G4ParticleChangeForLoss.hh
References currentCharge, currentTrack, G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), G4Track::GetPolarization(), G4Track::GetTrackStatus(), G4Track::GetWeight(), G4VParticleChange::InitializeSecondaries(), proposedKinEnergy, proposedMomentumDirection, proposedPolarization, G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNonIonizingEnergyDeposit, G4VParticleChange::theParentWeight, G4VParticleChange::theStatusChange, and track.
Referenced by G4VEnergyLossProcess::PostStepDoIt().
G4ParticleChangeForLoss & G4ParticleChangeForLoss::operator= (const G4ParticleChangeForLoss & right) protected
Definition at line 88 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleChangeForLoss.cc
References currentCharge, currentTrack, G4VParticleChange::fSetSecondaryWeightByProcess, G4cout, G4endl, G4VParticleChange::isParentWeightProposed, proposedKinEnergy, proposedMomentumDirection, G4FastVector< Type, N >::SetElement(), G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNumberOfSecondaries, G4VParticleChange::theParentWeight, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, and G4VParticleChange::verboseLevel.
void G4ParticleChangeForLoss::ProposeCharge (G4double finalCharge) inline
Definition at line 169 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ParticleChangeForLoss.hh
References currentCharge.
void G4ParticleChangeForLoss::ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz) inline
Definition at line 199 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 199 of file G4ParticleChangeForLoss.hh
References proposedMomentumDirection, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by G4EmBiasingManager::ApplySecondaryBiasing(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), and G4PenelopeIonisationModel::SampleSecondaries().
void G4ParticleChangeForLoss::ProposeMomentumDirection (const G4ThreeVector & Pfinal) inline
Definition at line 187 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 187 of file G4ParticleChangeForLoss.hh
References dir, and proposedMomentumDirection.
void G4ParticleChangeForLoss::ProposePolarization (const G4ThreeVector & dir) inline
Definition at line 218 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 218 of file G4ParticleChangeForLoss.hh
References dir, and proposedPolarization.
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), and G4PolarizedMollerBhabhaModel::SampleSecondaries().
void G4ParticleChangeForLoss::ProposePolarization (G4double Px, G4double Py, G4double Pz) inline
Definition at line 224 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 224 of file G4ParticleChangeForLoss.hh
References proposedPolarization, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
void G4ParticleChangeForLoss::SetLowEnergyLimit (G4double elimit) inline
Definition at line 272 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 272 of file G4ParticleChangeForLoss.hh
References lowEnergyLimit.
void G4ParticleChangeForLoss::SetProposedCharge (G4double theCharge) inline
Definition at line 164 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 164 of file G4ParticleChangeForLoss.hh
References currentCharge.
Referenced by G4NuclearStopping::AlongStepDoIt(), and G4VEnergyLossProcess::AlongStepDoIt().
void G4ParticleChangeForLoss::SetProposedKineticEnergy (G4double proposedKinEnergy) inline
Definition at line 149 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ParticleChangeForLoss.hh
References energy, and proposedKinEnergy.
Referenced by G4NuclearStopping::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4EmBiasingManager::ApplySecondaryBiasing(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
void G4ParticleChangeForLoss::SetProposedMomentumDirection (const G4ThreeVector & dir) inline
Definition at line 193 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 193 of file G4ParticleChangeForLoss.hh
References dir, and proposedMomentumDirection.
Referenced by G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
G4Step * G4ParticleChangeForLoss::UpdateStepForAlongStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 209 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 209 of file G4ParticleChangeForLoss.cc
References G4Step::AddNonIonizingEnergyDeposit(), G4Step::AddTotalEnergyDeposit(), G4Track::CalculateVelocity(), currentCharge, G4StepPoint::GetKineticEnergy(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, lowEnergyLimit, proposedKinEnergy, G4StepPoint::SetCharge(), G4StepPoint::SetKineticEnergy(), G4Track::SetKineticEnergy(), G4StepPoint::SetVelocity(), G4StepPoint::SetWeight(), G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNonIonizingEnergyDeposit, and G4VParticleChange::theParentWeight.
G4Step * G4ParticleChangeForLoss::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 243 of file G4ParticleChangeForLoss.cc.
View newest version in sPHENIX GitHub at line 243 of file G4ParticleChangeForLoss.cc
References G4Step::AddNonIonizingEnergyDeposit(), G4Step::AddTotalEnergyDeposit(), G4Track::CalculateVelocity(), currentCharge, G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, proposedKinEnergy, proposedMomentumDirection, proposedPolarization, G4StepPoint::SetCharge(), G4StepPoint::SetKineticEnergy(), G4Track::SetKineticEnergy(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPolarization(), G4StepPoint::SetVelocity(), G4StepPoint::SetWeight(), G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNonIonizingEnergyDeposit, and G4VParticleChange::theParentWeight.
Member Data Documentation
G4double G4ParticleChangeForLoss::currentCharge private
Definition at line 132 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleChangeForLoss.hh
Referenced by DumpInfo(), G4ParticleChangeForLoss(), GetCharge(), GetProposedCharge(), InitializeForAlongStep(), InitializeForPostStep(), operator=(), ProposeCharge(), SetProposedCharge(), UpdateStepForAlongStep(), and UpdateStepForPostStep().
const G4Track* G4ParticleChangeForLoss::currentTrack private
Definition at line 123 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ParticleChangeForLoss.hh
Referenced by G4ParticleChangeForLoss(), GetCurrentTrack(), InitializeForPostStep(), and operator=().
G4double G4ParticleChangeForLoss::lowEnergyLimit private
Definition at line 129 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ParticleChangeForLoss.hh
Referenced by G4ParticleChangeForLoss(), SetLowEnergyLimit(), and UpdateStepForAlongStep().
G4double G4ParticleChangeForLoss::proposedKinEnergy private
Definition at line 126 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleChangeForLoss.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForLoss(), GetProposedKineticEnergy(), InitializeForAlongStep(), InitializeForPostStep(), operator=(), SetProposedKineticEnergy(), UpdateStepForAlongStep(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChangeForLoss::proposedMomentumDirection private
Definition at line 135 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ParticleChangeForLoss.hh
Referenced by DumpInfo(), G4ParticleChangeForLoss(), GetMomentumDirection(), GetProposedMomentumDirection(), InitializeForPostStep(), operator=(), ProposeMomentumDirection(), SetProposedMomentumDirection(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChangeForLoss::proposedPolarization private
Definition at line 138 of file G4ParticleChangeForLoss.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ParticleChangeForLoss.hh
Referenced by GetProposedPolarization(), InitializeForPostStep(), ProposePolarization(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForLoss.hh
geant4/tree/geant4-10.6-release/source/track/src/G4ParticleChangeForLoss.cc