ECCE @ EIC Software: G4AdjointBremsstrahlungModel Class Reference
G4AdjointBremsstrahlungModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointBremsstrahlungModel.hh>
Public Member Functions
G4AdjointBremsstrahlungModel (G4VEmModel *aModel)
G4AdjointBremsstrahlungModel ()
~G4AdjointBremsstrahlungModel ()
virtual void SampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
void RapidSampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
virtual G4double DiffCrossSectionPerVolumePrimToSecond (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
G4double DiffCrossSectionPerVolumePrimToSecondApproximated1 (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
G4double DiffCrossSectionPerVolumePrimToSecondApproximated2 (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
virtual G4double AdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double GetAdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
Public Member Functions inherited from G4VEmAdjointModel
G4VEmAdjointModel (const G4String &nam)
virtual ~G4VEmAdjointModel ()
virtual G4double DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerVolumePrimToScatPrim (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj)
virtual G4double GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut=0)
virtual G4double GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy)
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
void SetCSMatrices (std::vector< G4AdjointCSMatrix * > *Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > *Vec2CSMatrix)
G4ParticleDefinition * GetAdjointEquivalentOfDirectPrimaryParticleDefinition ()
G4ParticleDefinition * GetAdjointEquivalentOfDirectSecondaryParticleDefinition ()
G4double GetHighEnergyLimit ()
G4double GetLowEnergyLimit ()
void SetHighEnergyLimit (G4double aVal)
void SetLowEnergyLimit (G4double aVal)
void DefineDirectEMModel (G4VEmModel *aModel)
void SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition *aPart)
void SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition *aPart)
void SetSecondPartOfSameType (G4bool aBool)
G4bool GetSecondPartOfSameType ()
void SetUseMatrix (G4bool aBool)
void SetUseMatrixPerElement (G4bool aBool)
void SetUseOnlyOneMatrixForAllElements (G4bool aBool)
void SetApplyCutInRange (G4bool aBool)
G4bool GetUseMatrix ()
G4bool GetUseMatrixPerElement ()
G4bool GetUseOnlyOneMatrixForAllElements ()
G4bool GetApplyCutInRange ()
G4String GetName ()
virtual void SetCSBiasingFactor (G4double aVal)
void SetCorrectWeightForPostStepInModel (G4bool aBool)
void SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor)
Private Attributes
G4VEmModel * theDirectStdBremModel
G4EmModelManager * theEmModelManagerForFwdModels
G4bool isDirectModelInitialised
G4double highKinEnergy
G4double lowKinEnergy
G4double lastCZ
std::vector< G4DataVector * > partialSumSigma
std::vector< float > SigmaPerAtom
Additional Inherited Members
Protected Member Functions inherited from G4VEmAdjointModel
G4double DiffCrossSectionFunction1 (G4double kinEnergyProj)
G4double DiffCrossSectionFunction2 (G4double kinEnergyProj)
G4double DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd)
G4double SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase)
G4double SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase)
void SelectCSMatrix (G4bool IsScatProjToProjCase)
virtual G4double SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase)
virtual void CorrectPostStepWeight (G4ParticleChange *fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase)
Protected Attributes inherited from G4VEmAdjointModel
G4VEmModel * theDirectEMModel
G4VParticleChange * pParticleChange
const G4String name
G4int ASelectedNucleus
G4int ZSelectedNucleus
G4Material * SelectedMaterial
G4double kinEnergyProdForIntegration
G4double kinEnergyScatProjForIntegration
G4double kinEnergyProjForIntegration
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4double > CS_Vs_ElementForScatProjToProjCase
std::vector< G4double > CS_Vs_ElementForProdToProjCase
G4double lastCS
G4double lastAdjointCSForScatProjToProjCase
G4double lastAdjointCSForProdToProjCase
G4ParticleDefinition * theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition * theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition * theDirectPrimaryPartDef
G4bool second_part_of_same_type
G4double preStepEnergy
G4Material * currentMaterial
G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcutForDirectPrim
G4double currentTcutForDirectSecond
G4bool ApplyCutInRange
G4double mass_ratio_product
G4double mass_ratio_projectile
G4double HighEnergyLimit
G4double LowEnergyLimit
G4double CS_biasing_factor
G4bool UseMatrix
G4bool UseMatrixPerElement
G4bool UseOnlyOneMatrixForAllElements
size_t indexOfUsedCrossSectionMatrix
size_t model_index
G4bool correct_weight_for_post_step_in_model
G4double additional_weight_correction_factor_for_post_step_outside_model
Detailed Description
Definition at line 61 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AdjointBremsstrahlungModel.hh
Constructor & Destructor Documentation
G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel (G4VEmModel * aModel)
Definition at line 45 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4AdjointBremsstrahlungModel.cc
References G4EmModelManager::AddEmModel(), G4AdjointElectron::AdjointElectron(), G4AdjointGamma::AdjointGamma(), G4VEmAdjointModel::CS_biasing_factor, G4Electron::Electron(), f, GeV, highKinEnergy, isDirectModelInitialised, keV, lastCZ, lowKinEnergy, r, G4VEmAdjointModel::second_part_of_same_type, G4VEmAdjointModel::SetApplyCutInRange(), G4VEmAdjointModel::SetUseMatrix(), G4VEmAdjointModel::SetUseMatrixPerElement(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, G4VEmAdjointModel::theDirectEMModel, G4VEmAdjointModel::theDirectPrimaryPartDef, theDirectStdBremModel, and theEmModelManagerForFwdModels.
G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel ()
Definition at line 78 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 78 of file G4AdjointBremsstrahlungModel.cc
References G4EmModelManager::AddEmModel(), G4AdjointElectron::AdjointElectron(), G4AdjointGamma::AdjointGamma(), G4Electron::Electron(), f, GeV, highKinEnergy, isDirectModelInitialised, keV, lastCZ, lowKinEnergy, r, G4VEmAdjointModel::second_part_of_same_type, G4VEmAdjointModel::SetApplyCutInRange(), G4VEmAdjointModel::SetUseMatrix(), G4VEmAdjointModel::SetUseMatrixPerElement(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, G4VEmAdjointModel::theDirectEMModel, G4VEmAdjointModel::theDirectPrimaryPartDef, theDirectStdBremModel, and theEmModelManagerForFwdModels.
G4AdjointBremsstrahlungModel::~G4AdjointBremsstrahlungModel ()
Definition at line 103 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 103 of file G4AdjointBremsstrahlungModel.cc
References theDirectStdBremModel, and theEmModelManagerForFwdModels.
Member Function Documentation
G4double G4AdjointBremsstrahlungModel::AdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 399 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 399 of file G4AdjointBremsstrahlungModel.cc
References G4VEmAdjointModel::AdjointCrossSection(), G4VEmModel::CrossSectionPerVolume(), G4VEmAdjointModel::CS_biasing_factor, G4VEmAdjointModel::currentTcutForDirectSecond, G4VEmAdjointModel::DefineCurrentMaterial(), G4Electron::Electron(), G4Gamma::Gamma(), G4MaterialCutsCouple::GetMaterial(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForScatProjToProjCase(), G4EmModelManager::Initialise(), isDirectModelInitialised, lastCZ, MeV, G4VEmAdjointModel::theDirectEMModel, G4VEmAdjointModel::theDirectPrimaryPartDef, theEmModelManagerForFwdModels, and G4VEmAdjointModel::UseMatrix.
Referenced by GetAdjointCrossSection().
G4double G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecond (const G4Material * aMaterial, G4double kinEnergyProj, G4double kinEnergyProd) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 323 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 323 of file G4AdjointBremsstrahlungModel.cc
References G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToSecond(), G4Electron::Electron(), G4Gamma::Gamma(), G4EmModelManager::Initialise(), isDirectModelInitialised, and theEmModelManagerForFwdModels.
Referenced by RapidSampleSecondaries().
G4double G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1 (const G4Material * aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
Definition at line 343 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 343 of file G4AdjointBremsstrahlungModel.cc
References G4VEmModel::CrossSectionPerVolume(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase(), keV, G4VEmAdjointModel::theDirectEMModel, and G4VEmAdjointModel::theDirectPrimaryPartDef.
G4double G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2 (const G4Material * aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
Definition at line 372 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 372 of file G4AdjointBremsstrahlungModel.cc
References C1, C2, G4VEmModel::ComputeCrossSectionPerAtom(), dE, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4VEmAdjointModel::theDirectEMModel, and G4VEmAdjointModel::theDirectPrimaryPartDef.
G4double G4AdjointBremsstrahlungModel::GetAdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 425 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 425 of file G4AdjointBremsstrahlungModel.cc
References AdjointCrossSection(), G4VEmModel::CrossSectionPerVolume(), G4VEmAdjointModel::GetAdjointCrossSection(), G4MaterialCutsCouple::GetMaterial(), lastCZ, MeV, G4VEmAdjointModel::theDirectEMModel, and G4VEmAdjointModel::theDirectPrimaryPartDef.
void G4AdjointBremsstrahlungModel::RapidSampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange)
Definition at line 188 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 188 of file G4AdjointBremsstrahlungModel.cc
References G4VEmAdjointModel::additional_weight_correction_factor_for_post_step_outside_model, G4ParticleChange::AddSecondary(), CLHEP::Hep3Vector::angle(), G4VEmAdjointModel::correct_weight_for_post_step_in_model, G4VEmAdjointModel::CS_biasing_factor, G4VEmAdjointModel::currentCouple, G4VEmAdjointModel::currentMaterial, G4VEmAdjointModel::currentTcutForDirectSecond, G4VEmAdjointModel::DefineCurrentMaterial(), DiffCrossSectionPerVolumePrimToSecond(), G4Electron::Electron(), Emax, Emin, energy, f1, f2, fStopAndKill, G4UniformRand, G4AdjointCSManager::GetAdjointCSManager(), G4VEmModel::GetAngularDistribution(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::getPhi(), G4AdjointCSManager::GetPostStepWeightCorrection(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForScatProjToProjCase(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetWeight(), G4Element::GetZasInt(), G4VEmAdjointModel::HighEnergyLimit, lastCZ, phi, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SelectRandomAtom(), G4VParticleChange::SetParentWeightByProcess(), G4VParticleChange::SetSecondaryWeightByProcess(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theDirectEMModel, CLHEP::Hep3Vector::unit(), and Z.
Referenced by SampleSecondaries().
void G4AdjointBremsstrahlungModel::SampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange) virtual
Implements G4VEmAdjointModel.
Definition at line 110 of file G4AdjointBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 110 of file G4AdjointBremsstrahlungModel.cc
References G4ParticleChange::AddSecondary(), CLHEP::Hep3Vector::angle(), G4VEmAdjointModel::CorrectPostStepWeight(), d, G4VEmAdjointModel::DefineCurrentMaterial(), source.hepunit::electron_mass_c2, fStopAndKill, G4UniformRand, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetWeight(), G4VEmAdjointModel::HighEnergyLimit, phi, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), RapidSampleSecondaries(), CLHEP::Hep3Vector::rotateUz(), G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, theta(), twopi, Acts::UnitConstants::u, CLHEP::Hep3Vector::unit(), and G4VEmAdjointModel::UseMatrix.
Member Data Documentation
G4double G4AdjointBremsstrahlungModel::highKinEnergy private
Definition at line 106 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AdjointBremsstrahlungModel.hh
Referenced by G4AdjointBremsstrahlungModel().
G4bool G4AdjointBremsstrahlungModel::isDirectModelInitialised private
Definition at line 104 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointBremsstrahlungModel.hh
Referenced by AdjointCrossSection(), DiffCrossSectionPerVolumePrimToSecond(), and G4AdjointBremsstrahlungModel().
G4double G4AdjointBremsstrahlungModel::lastCZ private
Definition at line 107 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointBremsstrahlungModel.hh
Referenced by AdjointCrossSection(), G4AdjointBremsstrahlungModel(), GetAdjointCrossSection(), and RapidSampleSecondaries().
G4double G4AdjointBremsstrahlungModel::lowKinEnergy private
Definition at line 107 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointBremsstrahlungModel.hh
Referenced by G4AdjointBremsstrahlungModel().
std::vector<G4DataVector*> G4AdjointBremsstrahlungModel::partialSumSigma private
Definition at line 108 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointBremsstrahlungModel.hh
std::vector<float> G4AdjointBremsstrahlungModel::SigmaPerAtom private
Definition at line 109 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AdjointBremsstrahlungModel.hh
G4VEmModel* G4AdjointBremsstrahlungModel::theDirectStdBremModel private
Definition at line 102 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AdjointBremsstrahlungModel.hh
Referenced by G4AdjointBremsstrahlungModel(), and ~G4AdjointBremsstrahlungModel().
G4EmModelManager* G4AdjointBremsstrahlungModel::theEmModelManagerForFwdModels private
Definition at line 103 of file G4AdjointBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AdjointBremsstrahlungModel.hh
Referenced by AdjointCrossSection(), DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel(), and ~G4AdjointBremsstrahlungModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointBremsstrahlungModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4AdjointBremsstrahlungModel.cc