ECCE @ EIC Software: StepMax Class Reference
StepMax Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/StepMax.hh>
Public Member Functions
StepMax (PhysicsListMessenger *mess)
virtual ~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseProcess (const G4ParticleDefinition *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStep, G4ForceCondition *cond)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
StepMax (const G4String &processName="UserMaxStep")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserMaxStep")
~StepMax ()
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserMaxStep", G4ProcessType type=fUserDefined)
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep1 (G4double)
void SetMaxStep2 (G4double)
void ApplyMaxStep2 (G4bool)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserMaxStep", G4ProcessType type=fUserDefined)
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep1 (G4double)
void SetMaxStep2 (G4double)
void ApplyMaxStep2 (G4bool)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="stepMax")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserStepMax")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (PhysicsListMessenger *mess)
virtual ~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseProcess (const G4ParticleDefinition *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStep, G4ForceCondition *cond)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
StepMax (PhysicsListMessenger *mess)
virtual ~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseProcess (const G4ParticleDefinition *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStep, G4ForceCondition *cond)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
StepMax (PhysicsListMessenger *mess)
virtual ~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseProcess (const G4ParticleDefinition *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStep, G4ForceCondition *cond)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
StepMax (const G4String &processName="UserMaxStep")
~StepMax ()
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserMaxStep")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (DetectorConstruction *ptr, const G4String &processName="UserMaxStep")
virtual ~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseProcess (const G4ParticleDefinition *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStep, G4ForceCondition *cond)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
StepMax (const G4String &processName="UserMaxStep")
virtual ~StepMax ()
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserStepMax")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserStepMax")
virtual ~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserMaxStep")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="UserMaxStep")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
StepMax (const G4String &processName="stepMax")
~StepMax ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetMaxStep (G4double)
G4double GetMaxStep ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Attributes
PhysicsListMessenger * fMessenger
G4double fMaxChargedStep
G4bool isInitialised
StepMaxMessenger * fMess
G4double fProposedStep
StepMaxMessenger * fMessenger
G4double fMaxStep1
G4double fMaxStep2
G4bool fApplyMaxStep2
G4bool fInitialised
DetectorConstruction * fDetector
G4VPhysicalVolume * fWorld
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 42 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 42 of file StepMax.hh
Constructor & Destructor Documentation
StepMax::StepMax (PhysicsListMessenger * mess)
Definition at line 37 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 37 of file StepMax.cc
References G4VProcess::SetProcessSubType(), and STEP_LIMITER.
StepMax::~StepMax () virtual
Definition at line 46 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 46 of file StepMax.cc
StepMax::StepMax (const G4String & processName = "UserMaxStep")
Definition at line 38 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 38 of file StepMax.cc
References fMess.
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserMaxStep")
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserMaxStep", G4ProcessType type = fUserDefined)
Definition at line 38 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 38 of file StepMax.cc
References DBL_MAX, fApplyMaxStep2, fMaxStep1, fMaxStep2, and fMess.
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserMaxStep", G4ProcessType type = fUserDefined)
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "stepMax")
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserStepMax")
StepMax::~StepMax ()
StepMax::StepMax (PhysicsListMessenger * mess)
virtual StepMax::~StepMax () virtual
StepMax::StepMax (PhysicsListMessenger * mess)
virtual StepMax::~StepMax () virtual
StepMax::StepMax (PhysicsListMessenger * mess)
virtual StepMax::~StepMax () virtual
StepMax::StepMax (const G4String & processName = "UserMaxStep")
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserMaxStep")
StepMax::~StepMax ()
StepMax::StepMax (DetectorConstruction * ptr, const G4String & processName = "UserMaxStep")
Definition at line 37 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 37 of file StepMax.cc
References G4VProcess::SetProcessSubType(), and STEP_LIMITER.
virtual StepMax::~StepMax () virtual
StepMax::StepMax (const G4String & processName = "UserMaxStep")
virtual StepMax::~StepMax () virtual
StepMax::StepMax (const G4String & processName = "UserStepMax")
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserStepMax")
virtual StepMax::~StepMax () virtual
StepMax::StepMax (const G4String & processName = "UserMaxStep")
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "UserMaxStep")
StepMax::~StepMax ()
StepMax::StepMax (const G4String & processName = "stepMax")
StepMax::~StepMax ()
Member Function Documentation
void StepMax::ApplyMaxStep2 (G4bool value)
Definition at line 67 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 67 of file StepMax.cc
References fApplyMaxStep2.
void StepMax::ApplyMaxStep2 (G4bool)
void StepMax::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
Definition at line 67 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 67 of file StepMax.cc
References DBL_MAX, fMaxChargedStep, fMessenger, G4cout, G4endl, PhysicsListMessenger::GetMaxChargedStep(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), and isInitialised.
virtual void StepMax::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
virtual void StepMax::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
virtual void StepMax::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
virtual void StepMax::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
G4double StepMax::GetMaxStep () inline
Definition at line 50 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 50 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 54 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 54 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 54 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 54 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 54 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 54 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 54 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 56 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 56 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 56 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 56 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 56 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 56 of file StepMax.hh
References fMaxChargedStep.
G4double StepMax::GetMaxStep () inline
Definition at line 56 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 56 of file StepMax.hh
References fMaxChargedStep.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 58 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 58 of file StepMax.hh
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 61 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 61 of file StepMax.hh
References DBL_MAX.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 62 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 62 of file StepMax.hh
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 62 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 62 of file StepMax.hh
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 62 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 62 of file StepMax.hh
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 64 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 64 of file StepMax.hh
References DBL_MAX.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 64 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 64 of file StepMax.hh
References DBL_MAX.
G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 64 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 64 of file StepMax.hh
References DBL_MAX.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 65 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 65 of file StepMax.hh
References DBL_MAX.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 65 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 65 of file StepMax.hh
virtual G4double StepMax::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) inline virtual
Reimplemented from G4VEmProcess.
Definition at line 67 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 67 of file StepMax.hh
References DBL_MAX.
void StepMax::InitialiseProcess (const G4ParticleDefinition *) virtual
Implements G4VEmProcess.
Definition at line 81 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 81 of file StepMax.cc
virtual void StepMax::InitialiseProcess (const G4ParticleDefinition *) virtual
Implements G4VEmProcess.
virtual void StepMax::InitialiseProcess (const G4ParticleDefinition *) virtual
Implements G4VEmProcess.
virtual void StepMax::InitialiseProcess (const G4ParticleDefinition *) virtual
Implements G4VEmProcess.
virtual void StepMax::InitialiseProcess (const G4ParticleDefinition *) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
G4bool StepMax::IsApplicable (const G4ParticleDefinition & part) virtual
Implements G4VEmProcess.
Definition at line 51 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 51 of file StepMax.cc
References G4ParticleDefinition::GetPDGCharge(), and G4ParticleDefinition::IsShortLived().
Referenced by PhysicsList::AddStepMax().
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4bool StepMax::IsApplicable (const G4ParticleDefinition &) virtual
Implements G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
G4VParticleChange * StepMax::PostStepDoIt (const G4Track & aTrack, const G4Step &) virtual
Reimplemented from G4VEmProcess.
Definition at line 98 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 98 of file StepMax.cc
References G4VProcess::aParticleChange, and G4ParticleChange::Initialize().
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4VParticleChange* StepMax::PostStepDoIt (const G4Track & , const G4Step &) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStep, G4ForceCondition * cond) virtual
Reimplemented from G4VEmProcess.
G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStep, G4ForceCondition * cond) virtual
Reimplemented from G4VEmProcess.
Definition at line 87 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 87 of file StepMax.cc
References fMaxChargedStep, and NotForced.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStep, G4ForceCondition * cond) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStep, G4ForceCondition * cond) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStep, G4ForceCondition * cond) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual G4double StepMax::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VEmProcess.
virtual void StepMax::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
void StepMax::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
Definition at line 58 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 58 of file StepMax.cc
References isInitialised.
virtual void StepMax::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
virtual void StepMax::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
virtual void StepMax::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VEmProcess.
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep (G4double step)
Definition at line 57 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 57 of file StepMax.cc
References fMaxChargedStep, and Acts::Test::step().
Referenced by StepMaxMessenger::SetNewValue().
void StepMax::SetMaxStep (G4double)
void StepMax::SetMaxStep1 (G4double step)
Definition at line 59 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 59 of file StepMax.cc
References fMaxStep1, and Acts::Test::step().
void StepMax::SetMaxStep1 (G4double)
void StepMax::SetMaxStep2 (G4double)
void StepMax::SetMaxStep2 (G4double step)
Definition at line 63 of file StepMax.cc.
View newest version in sPHENIX GitHub at line 63 of file StepMax.cc
References fMaxStep2, and Acts::Test::step().
Member Data Documentation
G4bool StepMax::fApplyMaxStep2 private
Definition at line 72 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 72 of file StepMax.hh
Referenced by ApplyMaxStep2(), and StepMax().
DetectorConstruction* StepMax::fDetector private
Definition at line 69 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 69 of file StepMax.hh
G4bool StepMax::fInitialised private
Definition at line 68 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 68 of file StepMax.hh
G4double StepMax::fMaxChargedStep private
Definition at line 67 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 67 of file StepMax.hh
Referenced by BuildPhysicsTable(), GetMaxStep(), PostStepGetPhysicalInteractionLength(), and SetMaxStep().
G4double StepMax::fMaxStep1 private
Definition at line 66 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 66 of file StepMax.hh
Referenced by SetMaxStep1(), and StepMax().
G4double StepMax::fMaxStep2 private
Definition at line 71 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 71 of file StepMax.hh
Referenced by SetMaxStep2(), and StepMax().
StepMaxMessenger * StepMax::fMess private
Definition at line 71 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 71 of file StepMax.hh
Referenced by StepMax().
StepMaxMessenger * StepMax::fMessenger private
Definition at line 65 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 65 of file StepMax.hh
Referenced by BuildPhysicsTable().
StepMaxMessenger* StepMax::fMessenger private
Definition at line 73 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 73 of file StepMax.hh
G4double StepMax::fProposedStep private
Definition at line 71 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 71 of file StepMax.hh
G4VPhysicalVolume* StepMax::fWorld private
Definition at line 70 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 70 of file StepMax.hh
G4bool StepMax::isInitialised private
Definition at line 68 of file StepMax.hh.
View newest version in sPHENIX GitHub at line 68 of file StepMax.hh
Referenced by BuildPhysicsTable(), and PreparePhysicsTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/StepMax.hh
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/StepMax.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/StepMax.cc