ECCE @ EIC Software: G4TwistTubsSide Class Reference
G4TwistTubsSide Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistTubsSide.hh>
Public Member Functions
G4TwistTubsSide (const G4String &name, const G4RotationMatrix &rot, const G4ThreeVector &tlate, G4int handedness, const G4double kappa, const EAxis axis0=kXAxis, const EAxis axis1=kZAxis, G4double axis0min=-kInfinity, G4double axis1min=-kInfinity, G4double axis0max=kInfinity, G4double axis1max=kInfinity)
G4TwistTubsSide (const G4String &name, G4double EndInnerRadius[2], G4double EndOuterRadius[2], G4double DPhi, G4double EndPhi[2], G4double EndZ[2], G4double InnerRadius, G4double OuterRadius, G4double Kappa, G4int handedness)
virtual ~G4TwistTubsSide ()
virtual G4ThreeVector GetNormal (const G4ThreeVector &xx, G4bool isGlobal=false)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate=kValidateWithTol)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[])
G4ThreeVector ProjectAtPXPZ (const G4ThreeVector &p, G4bool isglobal=false) const
virtual G4ThreeVector SurfacePoint (G4double, G4double, G4bool isGlobal=false)
virtual G4double GetBoundaryMin (G4double phi)
virtual G4double GetBoundaryMax (G4double phi)
virtual G4double GetSurfaceArea ()
virtual void GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside)
G4TwistTubsSide (__void__ &)
Public Member Functions inherited from G4VTwistSurface
G4VTwistSurface (const G4String &name)
G4VTwistSurface (const G4String &name, const G4RotationMatrix &rot, const G4ThreeVector &tlate, G4int handedness, const EAxis axis1, const EAxis axis2, G4double axis0min=-kInfinity, G4double axis1min=-kInfinity, G4double axis0max=kInfinity, G4double axis1max=kInfinity)
virtual ~G4VTwistSurface ()
virtual G4int AmIOnLeftSide (const G4ThreeVector &me, const G4ThreeVector &vec, G4bool withTol=true)
virtual G4double DistanceToBoundary (G4int areacode, G4ThreeVector &xx, const G4ThreeVector &p)
virtual G4double DistanceToIn (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceToOut (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceTo (const G4ThreeVector &gp, G4ThreeVector &gxx)
void DebugPrint () const
virtual G4String GetName () const
virtual void GetBoundaryParameters (const G4int &areacode, G4ThreeVector &d, G4ThreeVector &x0, G4int &boundarytype) const
virtual G4ThreeVector GetBoundaryAtPZ (G4int areacode, const G4ThreeVector &p) const
G4double DistanceToPlaneWithV (const G4ThreeVector &p, const G4ThreeVector &v, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &t1, const G4ThreeVector &t2, G4ThreeVector &xx, G4ThreeVector &n)
G4double DistanceToLine (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &d, G4ThreeVector &xx)
G4bool IsAxis0 (G4int areacode) const
G4bool IsAxis1 (G4int areacode) const
G4bool IsOutside (G4int areacode) const
G4bool IsInside (G4int areacode, G4bool testbitmode=false) const
G4bool IsBoundary (G4int areacode, G4bool testbitmode=false) const
G4bool IsCorner (G4int areacode, G4bool testbitmode=false) const
G4bool IsValidNorm () const
G4bool IsSameBoundary (G4VTwistSurface *surface1, G4int areacode1, G4VTwistSurface *surface2, G4int areacode2) const
G4int GetAxisType (G4int areacode, G4int whichaxis) const
G4ThreeVector ComputeGlobalPoint (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &gp) const
G4ThreeVector ComputeGlobalDirection (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalDirection (const G4ThreeVector &gp) const
void SetAxis (G4int i, const EAxis axis)
void SetNeighbours (G4VTwistSurface *ax0min, G4VTwistSurface *ax1min, G4VTwistSurface *ax0max, G4VTwistSurface *ax1max)
G4int GetNode (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetFace (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetEdgeVisibility (G4int i, G4int j, G4int m, G4int n, G4int number, G4int orientation)
G4VTwistSurface (__void__ &)
Private Member Functions
virtual G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &A, const G4ThreeVector &B, const G4ThreeVector &C, const G4ThreeVector &D, const G4int parity, G4ThreeVector &xx, G4ThreeVector &n)
virtual G4int GetAreaCode (const G4ThreeVector &xx, G4bool withTol=true)
virtual void SetCorners ()
virtual void SetCorners (G4double endInnerRad[2], G4double endOuterRad[2], G4double endPhi[2], G4double endZ[2])
virtual void SetBoundaries ()
Private Attributes
G4double fKappa
Additional Inherited Members
Public Types inherited from G4VTwistSurface
enum EValidate { kDontValidate = 0, kValidateWithTol = 1, kValidateWithoutTol = 2, kUninitialized = 3 }
Static Public Attributes inherited from G4VTwistSurface
static const G4int sOutside = 0x00000000
static const G4int sInside = 0x10000000
static const G4int sBoundary = 0x20000000
static const G4int sCorner = 0x40000000
static const G4int sC0Min1Min = 0x40000101
static const G4int sC0Max1Min = 0x40000201
static const G4int sC0Max1Max = 0x40000202
static const G4int sC0Min1Max = 0x40000102
static const G4int sAxisMin = 0x00000101
static const G4int sAxisMax = 0x00000202
static const G4int sAxisX = 0x00000404
static const G4int sAxisY = 0x00000808
static const G4int sAxisZ = 0x00000C0C
static const G4int sAxisRho = 0x00001010
static const G4int sAxisPhi = 0x00001414
static const G4int sAxis0 = 0x0000FF00
static const G4int sAxis1 = 0x000000FF
static const G4int sSizeMask = 0x00000303
static const G4int sAxisMask = 0x0000FCFC
static const G4int sAreaMask = 0XF0000000
Protected Member Functions inherited from G4VTwistSurface
G4VTwistSurface ** GetNeighbours ()
G4int GetNeighbours (G4int areacode, G4VTwistSurface *surfaces[])
G4ThreeVector GetCorner (G4int areacode) const
void GetBoundaryAxis (G4int areacode, EAxis axis[]) const
void GetBoundaryLimit (G4int areacode, G4double limit[]) const
virtual void SetBoundary (const G4int &axiscode, const G4ThreeVector &direction, const G4ThreeVector &x0, const G4int &boundarytype)
void SetCorner (G4int areacode, G4double x, G4double y, G4double z)
Protected Attributes inherited from G4VTwistSurface
EAxis fAxis [2]
G4double fAxisMin [2]
G4double fAxisMax [2]
CurrentStatus fCurStatWithV
CurrentStatus fCurStat
G4RotationMatrix fRot
G4ThreeVector fTrans
G4int fHandedness
G4SurfCurNormal fCurrentNormal
G4bool fIsValidNorm
G4double kCarTolerance
Detailed Description
Definition at line 41 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 41 of file G4TwistTubsSide.hh
Constructor & Destructor Documentation
G4TwistTubsSide::G4TwistTubsSide (const G4String & name, const G4RotationMatrix & rot, const G4ThreeVector & tlate, G4int handedness, const G4double kappa, const EAxis axis0 = kXAxis, const EAxis axis1 = kZAxis, G4double axis0min = -kInfinity, G4double axis1min = -kInfinity, G4double axis0max = kInfinity, G4double axis1max = kInfinity)
Definition at line 38 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 38 of file G4TwistTubsSide.cc
References FatalErrorInArgument, G4VTwistSurface::fIsValidNorm, G4Exception(), kXAxis, kZAxis, SetBoundaries(), and SetCorners().
G4TwistTubsSide::G4TwistTubsSide (const G4String & name, G4double EndInnerRadius[2], G4double EndOuterRadius[2], G4double DPhi, G4double EndPhi[2], G4double EndZ[2], G4double InnerRadius, G4double OuterRadius, G4double Kappa, G4int handedness)
Definition at line 63 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 63 of file G4TwistTubsSide.cc
References G4VTwistSurface::fAxis, G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, G4VTwistSurface::fHandedness, G4VTwistSurface::fIsValidNorm, fKappa, G4VTwistSurface::fRot, G4VTwistSurface::fTrans, kXAxis, kZAxis, CLHEP::HepRotation::rotateZ(), CLHEP::Hep3Vector::set(), SetBoundaries(), and SetCorners().
G4TwistTubsSide::~G4TwistTubsSide () virtual
Definition at line 106 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 106 of file G4TwistTubsSide.cc
G4TwistTubsSide::G4TwistTubsSide (__void__ & a)
Definition at line 97 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 97 of file G4TwistTubsSide.cc
Member Function Documentation
G4double G4TwistTubsSide::DistanceToPlane (const G4ThreeVector & p, const G4ThreeVector & A, const G4ThreeVector & B, const G4ThreeVector & C, const G4ThreeVector & D, const G4int parity, G4ThreeVector & xx, G4ThreeVector & n) private virtual
Definition at line 747 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 747 of file G4TwistTubsSide.cc
References B(), D(), G4VTwistSurface::DistanceToPlane(), FatalException, G4Exception(), G4VTwistSurface::kCarTolerance, N, and parity().
Referenced by DistanceToSurface().
G4int G4TwistTubsSide::DistanceToSurface (const G4ThreeVector & gp, const G4ThreeVector & gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate = kValidateWithTol) virtual
Implements G4VTwistSurface.
Definition at line 156 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 156 of file G4TwistTubsSide.cc
References a, b, c, G4VTwistSurface::ComputeGlobalPoint(), G4VTwistSurface::ComputeLocalDirection(), G4VTwistSurface::ComputeLocalPoint(), D(), DBL_MIN, G4VTwistSurface::DistanceToPlaneWithV(), FatalException, G4VTwistSurface::fCurStat, G4VTwistSurface::fCurStatWithV, fKappa, G4endl, G4Exception(), GetAreaCode(), G4VTwistSurface::CurrentStatus::GetAreacode(), G4VTwistSurface::CurrentStatus::GetDistance(), GetNormal(), G4VTwistSurface::CurrentStatus::GetNXX(), G4VTwistSurface::CurrentStatus::GetXX(), G4VTwistSurface::CurrentStatus::IsDone(), G4VTwistSurface::IsInside(), G4VTwistSurface::IsOutside(), G4VTwistSurface::CurrentStatus::IsValid(), k, G4VTwistSurface::kCarTolerance, kInfinity, G4VTwistSurface::kValidateWithoutTol, G4VTwistSurface::kValidateWithTol, message(), G4VTwistSurface::CurrentStatus::ResetfDone(), CLHEP::Hep3Vector::set(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), G4VTwistSurface::sInside, G4VTwistSurface::sOutside, v, CLHEP::Hep3Vector::x(), x, xx, CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and z.
G4int G4TwistTubsSide::DistanceToSurface (const G4ThreeVector & gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[]) virtual
Implements G4VTwistSurface.
Definition at line 476 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 476 of file G4TwistTubsSide.cc
References A(), G4VTwistSurface::AmIOnLeftSide(), B(), C(), G4VTwistSurface::ComputeGlobalPoint(), G4VTwistSurface::ComputeLocalPoint(), D(), d, G4VTwistSurface::DistanceToBoundary(), G4VTwistSurface::DistanceToLine(), DistanceToPlane(), G4VTwistSurface::DistanceToPlane(), G4VTwistSurface::fAxis, G4VTwistSurface::fCurStat, G4VTwistSurface::fCurStatWithV, fKappa, G4VTwistSurface::CurrentStatus::GetAreacode(), G4VTwistSurface::GetBoundaryAtPZ(), G4VTwistSurface::GetBoundaryParameters(), G4VTwistSurface::CurrentStatus::GetDistance(), G4VTwistSurface::CurrentStatus::GetNXX(), CLHEP::Hep3Vector::getRho(), G4VTwistSurface::CurrentStatus::GetXX(), G4VTwistSurface::CurrentStatus::IsDone(), G4VTwistSurface::kCarTolerance, G4VTwistSurface::kDontValidate, kInfinity, kXAxis, kZAxis, CLHEP::normal(), parity(), pt, G4VTwistSurface::CurrentStatus::ResetfDone(), G4VTwistSurface::sAxis0, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, CLHEP::Hep3Vector::set(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), G4VTwistSurface::sInside, G4VTwistSurface::sOutside, test(), tmp, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and z.
G4int G4TwistTubsSide::GetAreaCode (const G4ThreeVector & xx, G4bool withTol = true) private virtual
Implements G4VTwistSurface.
Definition at line 827 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 827 of file G4TwistTubsSide.cc
References FatalException, G4VTwistSurface::fAxis, G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, G4Exception(), G4VTwistSurface::kCarTolerance, kXAxis, kZAxis, G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, G4VTwistSurface::sAxisX, G4VTwistSurface::sAxisZ, G4VTwistSurface::sBoundary, G4VTwistSurface::sCorner, G4VTwistSurface::sInside, CLHEP::Hep3Vector::x(), xaxis, and CLHEP::Hep3Vector::z().
Referenced by DistanceToSurface().
G4double G4TwistTubsSide::GetBoundaryMax (G4double phi) inline virtual
Implements G4VTwistSurface.
Definition at line 167 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 167 of file G4TwistTubsSide.hh
References G4VTwistSurface::fAxisMax.
Referenced by GetFacets().
G4double G4TwistTubsSide::GetBoundaryMin (G4double phi) inline virtual
Implements G4VTwistSurface.
Definition at line 161 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 161 of file G4TwistTubsSide.hh
References G4VTwistSurface::fAxisMin.
Referenced by GetFacets().
void G4TwistTubsSide::GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside) virtual
Implements G4VTwistSurface.
Definition at line 1050 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 1050 of file G4TwistTubsSide.cc
References G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, G4VTwistSurface::fHandedness, GetBoundaryMax(), GetBoundaryMin(), G4VTwistSurface::GetEdgeVisibility(), G4VTwistSurface::GetFace(), G4VTwistSurface::GetNode(), k, n, SurfacePoint(), CLHEP::Hep3Vector::x(), x, xmax, xmin, CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and z.
G4ThreeVector G4TwistTubsSide::GetNormal (const G4ThreeVector & xx, G4bool isGlobal = false) virtual
Implements G4VTwistSurface.
Definition at line 113 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 113 of file G4TwistTubsSide.cc
References G4VTwistSurface::ComputeGlobalDirection(), G4VTwistSurface::ComputeLocalPoint(), G4VTwistSurface::fCurrentNormal, G4VTwistSurface::fHandedness, fKappa, G4VTwistSurface::kCarTolerance, CLHEP::normal(), G4VTwistSurface::G4SurfCurNormal::normal, G4VTwistSurface::G4SurfCurNormal::p, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), xx, and CLHEP::Hep3Vector::z().
Referenced by DistanceToSurface().
G4double G4TwistTubsSide::GetSurfaceArea () inline virtual
Implements G4VTwistSurface.
Definition at line 173 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 173 of file G4TwistTubsSide.hh
References G4VTwistSurface::fAxisMax, and G4VTwistSurface::fAxisMin.
G4ThreeVector G4TwistTubsSide::ProjectAtPXPZ (const G4ThreeVector & p, G4bool isglobal = false) const inline
Definition at line 138 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 138 of file G4TwistTubsSide.hh
References fKappa, G4VTwistSurface::fRot, G4VTwistSurface::fTrans, CLHEP::HepRotation::inverse(), CLHEP::Hep3Vector::x(), xx, and CLHEP::Hep3Vector::z().
void G4TwistTubsSide::SetBoundaries () private virtual
Implements G4VTwistSurface.
Definition at line 1003 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 1003 of file G4TwistTubsSide.cc
References FatalException, G4VTwistSurface::fAxis, G4endl, G4Exception(), G4VTwistSurface::GetCorner(), kXAxis, kZAxis, message(), G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, G4VTwistSurface::sAxisX, G4VTwistSurface::sAxisZ, G4VTwistSurface::sC0Max1Max, G4VTwistSurface::sC0Max1Min, G4VTwistSurface::sC0Min1Max, G4VTwistSurface::sC0Min1Min, G4VTwistSurface::SetBoundary(), and CLHEP::Hep3Vector::unit().
Referenced by G4TwistTubsSide().
void G4TwistTubsSide::SetCorners () private virtual
Implements G4VTwistSurface.
Definition at line 993 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 993 of file G4TwistTubsSide.cc
References FatalException, and G4Exception().
Referenced by G4TwistTubsSide().
void G4TwistTubsSide::SetCorners (G4double endInnerRad[2], G4double endOuterRad[2], G4double endPhi[2], G4double endZ[2]) private virtual
Definition at line 940 of file G4TwistTubsSide.cc.
View newest version in sPHENIX GitHub at line 940 of file G4TwistTubsSide.cc
References FatalException, G4VTwistSurface::fAxis, G4endl, G4Exception(), kXAxis, kZAxis, message(), G4VTwistSurface::sC0Max1Max, G4VTwistSurface::sC0Max1Min, G4VTwistSurface::sC0Min1Max, G4VTwistSurface::sC0Min1Min, G4VTwistSurface::SetCorner(), x, y, and z.
G4ThreeVector G4TwistTubsSide::SurfacePoint (G4double x, G4double z, G4bool isGlobal = false) inline virtual
Implements G4VTwistSurface.
Definition at line 152 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 152 of file G4TwistTubsSide.hh
References fKappa, G4VTwistSurface::fRot, and G4VTwistSurface::fTrans.
Referenced by GetFacets().
Member Data Documentation
G4double G4TwistTubsSide::fKappa private
Definition at line 129 of file G4TwistTubsSide.hh.
View newest version in sPHENIX GitHub at line 129 of file G4TwistTubsSide.hh
Referenced by DistanceToSurface(), G4TwistTubsSide(), GetNormal(), ProjectAtPXPZ(), and SurfacePoint().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistTubsSide.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4TwistTubsSide.cc