ECCE @ EIC Software: boost::python::detail::container_element< Container, Index, Policies > Class Template Reference
boost::python::detail::container_element< Container, Index, Policies > Class Template Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/source/boost/detail/indexing_suite_detail.hpp>
Public Types
typedef Index index_type
typedef Container container_type
typedef Policies::data_type element_type
typedef Policies policies_type
typedef container_element
< Container, Index, Policies > self_t
typedef proxy_group< self_t > links_type
Public Member Functions
container_element (object container, Index index)
container_element (container_element const &ce)
~container_element ()
element_type & operator* () const
element_type * get () const
void detach ()
bool is_detached () const
Container & get_container () const
Index get_index () const
void set_index (Index i)
Static Public Member Functions
static proxy_links< self_t,
Container > & get_links ()
Private Member Functions
container_element & operator= (container_element const &ce)
Private Attributes
scoped_ptr< element_type > ptr
object container
Index index
Detailed Description
template<class Container, class Index, class Policies>
class boost::python::detail::container_element< Container, Index, Policies >
Definition at line 352 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 352 of file indexing_suite_detail.hpp
Member Typedef Documentation
template<class Container, class Index, class Policies> typedef Container boost::python::detail::container_element< Container, Index, Policies >::container_type
Definition at line 357 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 357 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> typedef Policies::data_type boost::python::detail::container_element< Container, Index, Policies >::element_type
Definition at line 358 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 358 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> typedef Index boost::python::detail::container_element< Container, Index, Policies >::index_type
Definition at line 356 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 356 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> typedef proxy_group<self_t> boost::python::detail::container_element< Container, Index, Policies >::links_type
Definition at line 361 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 361 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> typedef Policies boost::python::detail::container_element< Container, Index, Policies >::policies_type
Definition at line 359 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 359 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> typedef container_element<Container, Index, Policies> boost::python::detail::container_element< Container, Index, Policies >::self_t
Definition at line 360 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 360 of file indexing_suite_detail.hpp
Constructor & Destructor Documentation
template<class Container, class Index, class Policies> boost::python::detail::container_element< Container, Index, Policies >::container_element (object container, Index index) inline
Definition at line 363 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 363 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> boost::python::detail::container_element< Container, Index, Policies >::container_element (container_element< Container, Index, Policies > const & ce) inline
Definition at line 370 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 370 of file indexing_suite_detail.hpp
template<class Container, class Index, class Policies> boost::python::detail::container_element< Container, Index, Policies >::~container_element () inline
Definition at line 377 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 377 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::get_links(), and boost::python::detail::container_element< Container, Index, Policies >::is_detached().
Member Function Documentation
template<class Container, class Index, class Policies> void boost::python::detail::container_element< Container, Index, Policies >::detach () inline
Definition at line 398 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 398 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::container, boost::python::detail::container_element< Container, Index, Policies >::get_container(), boost::python::detail::container_element< Container, Index, Policies >::index, boost::python::detail::container_element< Container, Index, Policies >::is_detached(), and boost::python::detail::container_element< Container, Index, Policies >::ptr.
template<class Container, class Index, class Policies> element_type* boost::python::detail::container_element< Container, Index, Policies >::get (void) const inline
Definition at line 390 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 390 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::get_container(), boost::python::detail::get_pointer(), boost::python::detail::container_element< Container, Index, Policies >::index, boost::python::detail::container_element< Container, Index, Policies >::is_detached(), and boost::python::detail::container_element< Container, Index, Policies >::ptr.
Referenced by boost::python::detail::get_pointer().
template<class Container, class Index, class Policies> Container& boost::python::detail::container_element< Container, Index, Policies >::get_container () const inline
Definition at line 416 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 416 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::container.
Referenced by boost::python::detail::container_element< Container, Index, Policies >::detach(), boost::python::detail::container_element< Container, Index, Policies >::get(), and boost::python::detail::container_element< Container, Index, Policies >::operator*().
template<class Container, class Index, class Policies> Index boost::python::detail::container_element< Container, Index, Policies >::get_index () const inline
Definition at line 422 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 422 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::index.
template<class Container, class Index, class Policies> static proxy_links<self_t, Container>& boost::python::detail::container_element< Container, Index, Policies >::get_links () inline static
Definition at line 434 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 434 of file indexing_suite_detail.hpp
Referenced by boost::python::detail::container_element< Container, Index, Policies >::~container_element().
template<class Container, class Index, class Policies> bool boost::python::detail::container_element< Container, Index, Policies >::is_detached () const inline
Definition at line 410 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 410 of file indexing_suite_detail.hpp
References boost::python::detail::get_pointer(), and boost::python::detail::container_element< Container, Index, Policies >::ptr.
Referenced by boost::python::detail::container_element< Container, Index, Policies >::detach(), boost::python::detail::container_element< Container, Index, Policies >::get(), boost::python::detail::container_element< Container, Index, Policies >::operator*(), and boost::python::detail::container_element< Container, Index, Policies >::~container_element().
template<class Container, class Index, class Policies> element_type& boost::python::detail::container_element< Container, Index, Policies >::operator* () const inline
Definition at line 383 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 383 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::get_container(), boost::python::detail::get_pointer(), boost::python::detail::container_element< Container, Index, Policies >::index, boost::python::detail::container_element< Container, Index, Policies >::is_detached(), and boost::python::detail::container_element< Container, Index, Policies >::ptr.
template<class Container, class Index, class Policies> container_element& boost::python::detail::container_element< Container, Index, Policies >::operator= (container_element< Container, Index, Policies > const & ce) private
template<class Container, class Index, class Policies> void boost::python::detail::container_element< Container, Index, Policies >::set_index (Index i) inline
Definition at line 428 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 428 of file indexing_suite_detail.hpp
References boost::python::detail::container_element< Container, Index, Policies >::index.
Member Data Documentation
template<class Container, class Index, class Policies> object boost::python::detail::container_element< Container, Index, Policies >::container private
Definition at line 449 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 449 of file indexing_suite_detail.hpp
Referenced by boost::python::detail::container_element< Container, Index, Policies >::detach(), and boost::python::detail::container_element< Container, Index, Policies >::get_container().
template<class Container, class Index, class Policies> Index boost::python::detail::container_element< Container, Index, Policies >::index private
Definition at line 450 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 450 of file indexing_suite_detail.hpp
Referenced by boost::python::detail::container_element< Container, Index, Policies >::detach(), boost::python::detail::container_element< Container, Index, Policies >::get(), boost::python::detail::container_element< Container, Index, Policies >::get_index(), boost::python::detail::container_element< Container, Index, Policies >::operator*(), and boost::python::detail::container_element< Container, Index, Policies >::set_index().
template<class Container, class Index, class Policies> scoped_ptr<element_type> boost::python::detail::container_element< Container, Index, Policies >::ptr private
Definition at line 448 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 448 of file indexing_suite_detail.hpp
Referenced by boost::python::detail::container_element< Container, Index, Policies >::detach(), boost::python::detail::container_element< Container, Index, Policies >::get(), boost::python::detail::container_element< Container, Index, Policies >::is_detached(), and boost::python::detail::container_element< Container, Index, Policies >::operator*().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/environments/g4py/source/boost/detail/indexing_suite_detail.hpp