ECCE @ EIC Software: G4ITStepProcessor Class Reference
G4ITStepProcessor Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITStepProcessor.hh>
Public Member Functions
G4ITStepProcessor ()
virtual ~G4ITStepProcessor ()
void SetPreviousStepTime (G4double)
G4Track * GetTrack ()
G4Step * GetStep ()
const G4Step * GetStep () const
void SetStep (G4Step *val)
G4TrackVector * GetSecondaries () const
void SetTrackingManager (G4ITTrackingManager *trackMan)
G4ITTrackingManager * GetTrackingManager ()
virtual void Initialize ()
void ForceReInitialization ()
void ResetLeadingTracks ()
void PrepareLeadingTracks ()
G4double ComputeInteractionLength (double previousTimeStep)
void DefinePhysicalStepLength (G4Track *)
G4double GetILTimeStep ()
void DoIt (double timeStep)
void ExtractDoItData ()
void Stepping (G4Track *, const double &)
void FindTransportationStep ()
double GetInteractionTime ()
const G4Track * GetTrack () const
void CleanProcessor ()
size_t GetAtRestDoItProcTriggered () const
G4GPILSelection GetGPILSelection () const
G4int GetN2ndariesAlongStepDoIt () const
G4int GetN2ndariesAtRestDoIt () const
G4int GetN2ndariesPostStepDoIt () const
const G4VITProcess * GetCurrentProcess () const
G4double GetPhysIntLength () const
size_t GetPostStepAtTimeDoItProcTriggered () const
size_t GetPostStepDoItProcTriggered () const
const ProcessGeneralInfo * GetCurrentProcessInfo () const
const G4ITStepProcessorState * GetProcessorState () const
const G4VParticleChange * GetParticleChange () const
const G4VPhysicalVolume * GetCurrentVolume () const
G4ForceCondition GetCondition () const
Protected Member Functions
void ExtractILData ()
void SetupGeneralProcessInfo (G4ParticleDefinition *, G4ProcessManager *)
void ClearProcessInfo ()
void SetTrack (G4Track *)
void GetProcessInfo ()
void SetupMembers ()
void ResetSecondaries ()
void InitDefineStep ()
void SetInitialStep ()
void GetAtRestIL ()
void DoDefinePhysicalStepLength ()
void DoStepping ()
void PushSecondaries ()
void ActiveOnlyITProcess ()
void ActiveOnlyITProcess (G4ProcessManager *)
void DealWithSecondaries (G4int &)
void InvokeAtRestDoItProcs ()
void InvokeAlongStepDoItProcs ()
void InvokePostStepDoItProcs ()
void InvokePSDIP (size_t)
void InvokeTransportationProc ()
void SetNavigator (G4ITNavigator *value)
G4double CalculateSafety ()
void ApplyProductionCut (G4Track *)
G4ITStepProcessor (const G4ITStepProcessor &other)
G4ITStepProcessor & operator= (const G4ITStepProcessor &other)
Private Attributes
G4bool fInitialized
G4ITTrackingManager * fpTrackingManager
G4double kCarTolerance
G4ITNavigator * fpNavigator
G4int fStoreTrajectory
G4VITSteppingVerbose * fpVerbose
G4ITTrackHolder * fpTrackContainer
G4ITLeadingTracks fLeadingTracks
G4double fTimeStep
G4double fILTimeStep
G4double fPreviousTimeStep
G4TrackVector * fpSecondary
G4VParticleChange * fpParticleChange
G4VITProcess * fpCurrentProcess
G4int fN2ndariesAtRestDoIt
G4int fN2ndariesAlongStepDoIt
G4int fN2ndariesPostStepDoIt
size_t fAtRestDoItProcTriggered
size_t fPostStepDoItProcTriggered
size_t fPostStepAtTimeDoItProcTriggered
G4ForceCondition fCondition
G4GPILSelection fGPILSelection
G4double fPhysIntLength
G4VPhysicalVolume * fpCurrentVolume
std::map< const
G4ParticleDefinition
*, ProcessGeneralInfo * > fProcessGeneralInfoMap
ProcessGeneralInfo * fpProcessInfo
G4ITTransportation * fpTransportation
G4Track * fpTrack
G4IT * fpITrack
G4TrackingInformation * fpTrackingInfo
G4ITStepProcessorState * fpState
G4Step * fpStep
G4StepPoint * fpPreStepPoint
G4StepPoint * fpPostStepPoint
Friends
class G4Scheduler
Detailed Description
Its role is the same as G4StepManager :
Find the minimum physical length and corresponding time step
Step one track BUT on a given time step.
Definition at line 153 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ITStepProcessor.hh
Constructor & Destructor Documentation
G4ITStepProcessor::G4ITStepProcessor ()
Definition at line 76 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ITStepProcessor.cc
References DBL_MAX, and kCarTolerance.
G4ITStepProcessor::~G4ITStepProcessor () virtual
Definition at line 228 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ITStepProcessor.cc
References ClearProcessInfo(), G4Step::DeleteSecondaryVector(), fpSecondary, and fpStep.
G4ITStepProcessor::G4ITStepProcessor (const G4ITStepProcessor & other) protected
Definition at line 244 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 244 of file G4ITStepProcessor.cc
References CleanProcessor(), DBL_MAX, fILTimeStep, fInitialized, fpNavigator, fPreviousTimeStep, fpTrackContainer, fpTrackingManager, fpVerbose, fStoreTrajectory, kCarTolerance, and ResetSecondaries().
Member Function Documentation
void G4ITStepProcessor::ActiveOnlyITProcess () protected
Definition at line 289 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 289 of file G4ITStepProcessor.cc
References FatalException, G4cerr, G4cout, G4endl, G4Exception(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetProcessManager(), particle, Acts::UnitConstants::pm, G4ParticleTableIterator< K, V >::reset(), theParticleIterator, and G4ParticleTableIterator< K, V >::value().
void G4ITStepProcessor::ActiveOnlyITProcess (G4ProcessManager * processManager) protected
Definition at line 323 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 323 of file G4ITStepProcessor.cc
References G4ProcessManager::GetProcessList(), G4ProcessManager::SetProcessActivation(), and G4ProcessVector::size().
void G4ITStepProcessor::ApplyProductionCut (G4Track * aSecondary) protected
Definition at line 913 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 913 of file G4ITStepProcessor2.cc
References kdfinder::abs(), DBL_MIN, G4DynamicParticle::GetCharge(), G4ProductionCutsTable::GetCoupleIndex(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4ProductionCutsTable::GetEnergyCutsVector(), G4ProductionCuts::GetIndex(), G4Track::GetKineticEnergy(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetRange(), G4LossTableManager::Instance(), G4Track::IsGoodForTracking(), and G4Track::SetKineticEnergy().
G4double G4ITStepProcessor::CalculateSafety () inline protected
Definition at line 441 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 441 of file G4ITStepProcessor.hh
References G4ITStepProcessorState::fEndpointSafety, G4ITStepProcessorState::fEndpointSafOrigin, fpPostStepPoint, fpState, G4StepPoint::GetPosition(), kCarTolerance, and max.
void G4ITStepProcessor::CleanProcessor () inline
Definition at line 457 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 457 of file G4ITStepProcessor.hh
References DBL_MAX, fAtRestDoItProcTriggered, fCondition, fGPILSelection, fpCurrentProcess, fpCurrentVolume, fPhysIntLength, fpITrack, fPostStepAtTimeDoItProcTriggered, fPostStepDoItProcTriggered, fpParticleChange, fpPostStepPoint, fpPreStepPoint, fpProcessInfo, fpSecondary, fpState, fpStep, fpTrack, fpTrackingInfo, fpTransportation, fTimeStep, INT_MAX, NotCandidateForSelection, and NotForced.
Referenced by ExtractILData(), G4ITStepProcessor(), and Initialize().
void G4ITStepProcessor::ClearProcessInfo () protected
Definition at line 170 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 170 of file G4ITStepProcessor.cc
References fProcessGeneralInfoMap, and it.
Referenced by ForceReInitialization(), and ~G4ITStepProcessor().
G4double G4ITStepProcessor::ComputeInteractionLength (double previousTimeStep)
Definition at line 603 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 603 of file G4ITStepProcessor.cc
References G4ManyFastLists< OBJECT >::begin(), DBL_MAX, DefinePhysicalStepLength(), G4ManyFastLists< OBJECT >::end(), ExtractILData(), fILTimeStep, fpTrackContainer, G4cout, G4endl, G4Track::GetGlobalTime(), GetIT(), G4ITTrackHolder::GetMainList(), G4IT::GetName(), G4Track::GetTrackID(), it, SetPreviousStepTime(), and track.
Referenced by G4Scheduler::Stepping().
void G4ITStepProcessor::DealWithSecondaries (G4int & counter) protected
Definition at line 64 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ITStepProcessor2.cc
References DBL_MIN, G4ProcessVector::entries(), fStopButAlive, G4ParticleDefinition::GetApplyCutsFlag(), G4ProcessManager::GetAtRestProcessVector(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4ParticleDefinition::GetProcessManager(), Acts::UnitConstants::pm, G4Track::SetCreatorProcess(), G4Track::SetParentID(), and G4Track::SetTrackStatus().
void G4ITStepProcessor::DefinePhysicalStepLength (G4Track * track)
Definition at line 698 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 698 of file G4ITStepProcessor.cc
References DoDefinePhysicalStepLength(), and SetTrack().
Referenced by ComputeInteractionLength().
void G4ITStepProcessor::DoDefinePhysicalStepLength () protected
Definition at line 956 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 956 of file G4ITStepProcessor.cc
References G4VProcess::AlongStepGPIL(), CandidateForSelection, G4ITTransportation::ComputeStep(), Conditionally, DBL_MAX, G4VITSteppingVerbose::DPSLAlongStep(), G4VITSteppingVerbose::DPSLPostStep(), G4VITSteppingVerbose::DPSLStarted(), ExclusivelyForced, fAlongStepDoItProc, FatalErrorInArgument, FatalException, fCondition, fExclusivelyForcedProc, fGeomBoundary, fGPILSelection, Forced, ProcessGeneralInfo::fpAlongStepGetPhysIntVector, fpCurrentProcess, G4ITStepProcessorState::fPhysicalStep, fPhysIntLength, fpITrack, fpNavigator, fPostStepAtTimeDoItProcTriggered, fPostStepDoItProc, fPostStepDoItProcTriggered, ProcessGeneralInfo::fpPostStepGetPhysIntVector, fpProcessInfo, G4ITStepProcessorState::fPreviousStepSize, G4ITStepProcessorState::fProposedSafety, fpState, fpStep, fpTrack, fpTrackingInfo, fpTransportation, fpVerbose, G4ITStepProcessorState::fSelectedPostStepDoItVector, G4ITStepProcessorState::fStepStatus, fStopAndKill, fStopButAlive, fTimeStep, fWorldBoundary, G4Exception(), GetAtRestIL(), G4VITProcess::GetInteractionTimeLeft(), G4Track::GetNextVolume(), G4Step::GetPostStepPoint(), G4VITProcess::GetProcessID(), G4TrackingInformation::GetProcessState(), G4IT::GetTrackingInfo(), G4Track::GetTrackStatus(), InActivated, InitDefineStep(), ProcessGeneralInfo::MAXofAlongStepLoops, ProcessGeneralInfo::MAXofPostStepLoops, NotForced, G4VProcess::PostStepGPIL(), G4VITProcess::ProposesTimeStep(), G4VITProcess::ResetProcessState(), G4TrackingInformation::SetNavigatorState(), G4StepPoint::SetProcessDefinedStep(), G4VITProcess::SetProcessState(), and StronglyForced.
Referenced by DefinePhysicalStepLength().
void G4ITStepProcessor::DoIt (double timeStep)
Definition at line 111 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ITStepProcessor2.cc
References G4ManyFastLists< OBJECT >::end(), FatalException, fStopAndKill, G4cout, G4endl, G4Exception(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), it, G4MemStat::MemoryUsage(), G4ManyFastLists< OBJECT >::size(), and track.
Referenced by G4Scheduler::Stepping().
void G4ITStepProcessor::DoStepping () protected
Definition at line 293 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 293 of file G4ITStepProcessor2.cc
References FatalErrorInArgument, fAtRestDoItProc, fPostStepDoItProc, fStopAndKill, fStopButAlive, fUndefined, G4cout, G4endl, G4Exception(), GetIT(), JustWarning, kCarTolerance, max, and G4MemStat::MemoryUsage().
void G4ITStepProcessor::ExtractDoItData ()
Definition at line 192 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 192 of file G4ITStepProcessor2.cc
References fAlive, fKillTrackAndSecondaries, fPostponeToNextEvent, fStopAndKill, fStopButAlive, fSuspend, G4ITReactionSet::Instance(), and G4ITReactionSet::RemoveReactionSet().
void G4ITStepProcessor::ExtractILData () protected
Definition at line 635 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 635 of file G4ITStepProcessor.cc
References CleanProcessor(), DBL_EPSILON, G4ITTrackingManager::EndTracking(), fILTimeStep, fLeadingTracks, fpTrack, fpTrackingManager, fStopAndKill, fTimeStep, GetInteractionTime(), G4Track::GetTrackStatus(), IsInf(), G4ITLeadingTracks::Push(), and G4ITLeadingTracks::Reset().
Referenced by ComputeInteractionLength().
void G4ITStepProcessor::FindTransportationStep ()
Definition at line 802 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 802 of file G4ITStepProcessor2.cc
References DBL_MAX, FatalErrorInArgument, fStopAndKill, and G4Exception().
void G4ITStepProcessor::ForceReInitialization ()
Definition at line 189 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 189 of file G4ITStepProcessor.cc
References ClearProcessInfo(), fInitialized, and Initialize().
size_t G4ITStepProcessor::GetAtRestDoItProcTriggered () const inline
Definition at line 220 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ITStepProcessor.hh
References fAtRestDoItProcTriggered.
Referenced by G4VITSteppingVerbose::CopyState().
void G4ITStepProcessor::GetAtRestIL () protected
Definition at line 540 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 540 of file G4ITStepProcessor.cc
References G4VProcess::AtRestGPIL(), DBL_MAX, fAtRestDoItProcTriggered, fCondition, Forced, ProcessGeneralInfo::fpAtRestGetPhysIntVector, fpCurrentProcess, fpProcessInfo, fpState, fpTrack, fpTrackingInfo, G4ITStepProcessorState::fSelectedAtRestDoItVector, fTimeStep, G4cerr, G4endl, G4VITProcess::GetProcessID(), G4TrackingInformation::GetProcessState(), InActivated, ProcessGeneralInfo::MAXofAtRestLoops, NotForced, G4VITProcess::ResetProcessState(), and G4VITProcess::SetProcessState().
Referenced by DoDefinePhysicalStepLength().
G4ForceCondition G4ITStepProcessor::GetCondition () const inline
Definition at line 285 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 285 of file G4ITStepProcessor.hh
References fCondition.
Referenced by G4VITSteppingVerbose::CopyState().
const G4VITProcess* G4ITStepProcessor::GetCurrentProcess () const inline
Definition at line 245 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 245 of file G4ITStepProcessor.hh
References fpCurrentProcess.
Referenced by G4VITSteppingVerbose::CopyState().
const ProcessGeneralInfo* G4ITStepProcessor::GetCurrentProcessInfo () const inline
Definition at line 265 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 265 of file G4ITStepProcessor.hh
References fpProcessInfo.
Referenced by G4VITSteppingVerbose::CopyState().
const G4VPhysicalVolume* G4ITStepProcessor::GetCurrentVolume () const inline
Definition at line 280 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 280 of file G4ITStepProcessor.hh
References fpCurrentVolume.
Referenced by G4VITSteppingVerbose::CopyState().
G4GPILSelection G4ITStepProcessor::GetGPILSelection () const inline
Definition at line 225 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 225 of file G4ITStepProcessor.hh
References fGPILSelection.
Referenced by G4VITSteppingVerbose::CopyState().
G4double G4ITStepProcessor::GetILTimeStep () inline
Definition at line 203 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 203 of file G4ITStepProcessor.hh
References fILTimeStep.
double G4ITStepProcessor::GetInteractionTime () inline
Definition at line 491 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 491 of file G4ITStepProcessor.hh
References fTimeStep.
Referenced by ExtractILData().
G4int G4ITStepProcessor::GetN2ndariesAlongStepDoIt () const inline
Definition at line 230 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ITStepProcessor.hh
References fN2ndariesAlongStepDoIt.
Referenced by G4VITSteppingVerbose::CopyState().
G4int G4ITStepProcessor::GetN2ndariesAtRestDoIt () const inline
Definition at line 235 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 235 of file G4ITStepProcessor.hh
References fN2ndariesAtRestDoIt.
Referenced by G4VITSteppingVerbose::CopyState().
G4int G4ITStepProcessor::GetN2ndariesPostStepDoIt () const inline
Definition at line 240 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 240 of file G4ITStepProcessor.hh
References fN2ndariesPostStepDoIt.
Referenced by G4VITSteppingVerbose::CopyState().
const G4VParticleChange* G4ITStepProcessor::GetParticleChange () const inline
Definition at line 275 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 275 of file G4ITStepProcessor.hh
References fpParticleChange.
Referenced by G4VITSteppingVerbose::CopyState().
G4double G4ITStepProcessor::GetPhysIntLength () const inline
Definition at line 250 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 250 of file G4ITStepProcessor.hh
References fPhysIntLength.
Referenced by G4VITSteppingVerbose::CopyState().
size_t G4ITStepProcessor::GetPostStepAtTimeDoItProcTriggered () const inline
Definition at line 255 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 255 of file G4ITStepProcessor.hh
References fPostStepAtTimeDoItProcTriggered.
size_t G4ITStepProcessor::GetPostStepDoItProcTriggered () const inline
Definition at line 260 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 260 of file G4ITStepProcessor.hh
References fPostStepDoItProcTriggered.
Referenced by G4VITSteppingVerbose::CopyState().
void G4ITStepProcessor::GetProcessInfo () protected
Definition at line 487 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 487 of file G4ITStepProcessor.cc
References FatalErrorInArgument, fpProcessInfo, fProcessGeneralInfoMap, fpTrack, G4Exception(), G4Track::GetDefinition(), G4ParticleDefinition::GetProcessManager(), it, particle, and SetupGeneralProcessInfo().
Referenced by SetupMembers().
const G4ITStepProcessorState* G4ITStepProcessor::GetProcessorState () const inline
Definition at line 270 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 270 of file G4ITStepProcessor.hh
References fpState.
Referenced by G4VITSteppingVerbose::CopyState().
G4TrackVector* G4ITStepProcessor::GetSecondaries () const inline
Definition at line 179 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ITStepProcessor.hh
References fpSecondary.
Referenced by G4VITSteppingVerbose::CopyState().
G4Step* G4ITStepProcessor::GetStep () inline
Definition at line 166 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ITStepProcessor.hh
References fpStep.
Referenced by G4VITSteppingVerbose::CopyState().
const G4Step* G4ITStepProcessor::GetStep () const inline
Definition at line 170 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ITStepProcessor.hh
References fpStep.
G4Track* G4ITStepProcessor::GetTrack () inline
Definition at line 162 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ITStepProcessor.hh
References fpTrack.
Referenced by G4VITSteppingVerbose::CopyState().
const G4Track * G4ITStepProcessor::GetTrack () const inline
Definition at line 434 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 434 of file G4ITStepProcessor.hh
References fpTrack.
G4ITTrackingManager* G4ITStepProcessor::GetTrackingManager () inline
Definition at line 187 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 187 of file G4ITStepProcessor.hh
References fpTrackingManager.
void G4ITStepProcessor::InitDefineStep () protected
ADDED BACK
ADDED BACK
Definition at line 850 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 850 of file G4ITStepProcessor.cc
References G4Step::CopyPostToPreStepPoint(), fpCurrentVolume, fpITrack, fpNavigator, G4ITStepProcessorState::fPreviousStepSize, fpSecondary, fpState, fpStep, fpTrack, fpTrackingManager, G4ITStepProcessorState::fTouchableHandle, G4TrackingInformation::GetNavigatorState(), G4Track::GetNextTouchableHandle(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4Track::GetStepLength(), G4Track::GetTouchableHandle(), G4IT::GetTrackingInfo(), G4Step::NewSecondaryVector(), G4Step::ResetTotalEnergyDeposit(), SetInitialStep(), G4Track::SetNextTouchableHandle(), G4Step::SetPointerToVectorOfAuxiliaryPoints(), G4Track::SetStep(), G4TrackingInformation::SetStepProcessorState(), G4Track::SetTouchableHandle(), SetupMembers(), and G4ITTrackingManager::StartTracking().
Referenced by DoDefinePhysicalStepLength().
void G4ITStepProcessor::Initialize () virtual
Definition at line 198 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 198 of file G4ITStepProcessor.cc
References CleanProcessor(), DBL_MAX, fInitialized, fPhysIntLength, fpTrackContainer, fpTrackingManager, fpVerbose, G4GeometryTolerance::GetInstance(), G4ITTrackingManager::GetInteractivity(), G4ITTrackingInteractivity::GetSteppingVerbose(), G4GeometryTolerance::GetSurfaceTolerance(), G4ITTransportationManager::GetTransportationManager(), G4ITTrackHolder::Instance(), kCarTolerance, SetNavigator(), and G4VITSteppingVerbose::SetStepProcessor().
Referenced by ForceReInitialization(), and G4Scheduler::Process().
void G4ITStepProcessor::InvokeAlongStepDoItProcs () protected
Definition at line 628 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 628 of file G4ITStepProcessor2.cc
References DBL_MIN, fAlive, fExclusivelyForcedProc, fStopAndKill, fStopButAlive, G4cout, G4endl, and G4MemStat::MemoryUsage().
void G4ITStepProcessor::InvokeAtRestDoItProcs () protected
Definition at line 561 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 561 of file G4ITStepProcessor2.cc
References InActivated.
void G4ITStepProcessor::InvokePostStepDoItProcs () protected
Definition at line 712 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 712 of file G4ITStepProcessor2.cc
References ExclusivelyForced, fExclusivelyForcedProc, Forced, fPostStepDoItProc, fStopAndKill, InActivated, NotForced, and StronglyForced.
void G4ITStepProcessor::InvokePSDIP (size_t np) protected
Definition at line 762 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 762 of file G4ITStepProcessor2.cc
void G4ITStepProcessor::InvokeTransportationProc () protected
Definition at line 863 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 863 of file G4ITStepProcessor2.cc
References ExclusivelyForced, fExclusivelyForcedProc, Forced, fStopAndKill, InActivated, and StronglyForced.
G4ITStepProcessor & G4ITStepProcessor::operator= (const G4ITStepProcessor & other) protected
Definition at line 280 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 280 of file G4ITStepProcessor.cc
void G4ITStepProcessor::PrepareLeadingTracks ()
Definition at line 273 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 273 of file G4ITStepProcessor.cc
References fLeadingTracks, and G4ITLeadingTracks::PrepareLeadingTracks().
Referenced by G4Scheduler::Stepping().
void G4ITStepProcessor::PushSecondaries () protected
Definition at line 241 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 241 of file G4ITStepProcessor2.cc
void G4ITStepProcessor::ResetLeadingTracks ()
Definition at line 266 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 266 of file G4ITStepProcessor.cc
References fLeadingTracks, and G4ITLeadingTracks::Reset().
Referenced by G4Scheduler::Stepping().
void G4ITStepProcessor::ResetSecondaries () protected
Definition at line 530 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 530 of file G4ITStepProcessor.cc
References fN2ndariesAlongStepDoIt, fN2ndariesAtRestDoIt, and fN2ndariesPostStepDoIt.
Referenced by G4ITStepProcessor(), and SetupMembers().
void G4ITStepProcessor::SetInitialStep () protected
Definition at line 706 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 706 of file G4ITStepProcessor.cc
References fAlive, FatalException, fpCurrentVolume, fpITrack, fpNavigator, fPostponeToNextEvent, fpState, fpStep, fpTrack, G4ITStepProcessorState::fStepStatus, fStopAndKill, fStopButAlive, fSuspend, G4ITStepProcessorState::fTouchableHandle, fUndefined, G4cerr, G4cout, G4endl, G4Exception(), G4Track::GetCurrentStepNumber(), G4Track::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMomentumDirection(), G4TrackingInformation::GetNavigatorState(), G4Track::GetParentID(), G4Track::GetPosition(), G4VPhysicalVolume::GetRegularStructureId(), G4Track::GetTouchableHandle(), G4IT::GetTrackingInfo(), G4Track::GetTrackStatus(), G4VTouchable::GetVolume(), G4Track::GetVolume(), G4Step::InitializeStep(), G4Track::SetLogicalVolumeAtVertex(), G4TrackingInformation::SetNavigatorState(), G4Track::SetNextTouchableHandle(), G4Track::SetTouchableHandle(), G4Track::SetTrackStatus(), G4Track::SetVertexKineticEnergy(), G4Track::SetVertexMomentumDirection(), and G4Track::SetVertexPosition().
Referenced by InitDefineStep().
void G4ITStepProcessor::SetNavigator (G4ITNavigator * value) inline protected
Definition at line 450 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 450 of file G4ITStepProcessor.hh
References fpNavigator.
Referenced by Initialize().
void G4ITStepProcessor::SetPreviousStepTime (G4double previousTimeStep) inline
Definition at line 427 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 427 of file G4ITStepProcessor.hh
References fPreviousTimeStep.
Referenced by ComputeInteractionLength().
void G4ITStepProcessor::SetStep (G4Step * val) inline
Definition at line 174 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ITStepProcessor.hh
References fpStep.
void G4ITStepProcessor::SetTrack (G4Track * track) protected
Definition at line 454 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 454 of file G4ITStepProcessor.cc
References FatalErrorInArgument, fpITrack, fpStep, fpTrack, fpTrackingInfo, G4cerr, G4endl, G4Exception(), GetIT(), G4Track::GetStep(), G4Track::GetTrackID(), G4IT::GetTrackingInfo(), and track.
Referenced by DefinePhysicalStepLength().
void G4ITStepProcessor::SetTrackingManager (G4ITTrackingManager * trackMan) inline
Definition at line 183 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 183 of file G4ITStepProcessor.hh
References fpTrackingManager.
Referenced by G4Scheduler::Initialize().
void G4ITStepProcessor::SetupGeneralProcessInfo (G4ParticleDefinition * particle, G4ProcessManager * pm) protected
Definition at line 343 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 343 of file G4ITStepProcessor.cc
References G4ProcessVector::entries(), FatalErrorInArgument, FatalException, ProcessGeneralInfo::fpAlongStepDoItVector, ProcessGeneralInfo::fpAlongStepGetPhysIntVector, ProcessGeneralInfo::fpAtRestDoItVector, ProcessGeneralInfo::fpAtRestGetPhysIntVector, ProcessGeneralInfo::fpPostStepDoItVector, ProcessGeneralInfo::fpPostStepGetPhysIntVector, fpProcessInfo, fProcessGeneralInfoMap, ProcessGeneralInfo::fpTransportation, G4cerr, G4cout, G4endl, G4Exception(), G4ProcessManager::GetAlongStepProcessVector(), G4ProcessManager::GetAtRestProcessVector(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ProcessManager::GetPostStepProcessVector(), it, ProcessGeneralInfo::MAXofAlongStepLoops, ProcessGeneralInfo::MAXofAtRestLoops, ProcessGeneralInfo::MAXofPostStepLoops, particle, SizeOfSelectedDoItVector, typeDoIt, and typeGPIL.
Referenced by GetProcessInfo().
void G4ITStepProcessor::SetupMembers () protected
Definition at line 515 of file G4ITStepProcessor.cc.
View newest version in sPHENIX GitHub at line 515 of file G4ITStepProcessor.cc
References fpITrack, fpPostStepPoint, fpPreStepPoint, fpSecondary, fpState, fpStep, G4Step::GetfSecondary(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), GetProcessInfo(), G4TrackingInformation::GetStepProcessorState(), G4IT::GetTrackingInfo(), and ResetSecondaries().
Referenced by InitDefineStep().
void G4ITStepProcessor::Stepping (G4Track * track, const double & timeStep)
Definition at line 264 of file G4ITStepProcessor2.cc.
View newest version in sPHENIX GitHub at line 264 of file G4ITStepProcessor2.cc
References G4cout, G4endl, G4Track::GetTrackID(), and G4MemStat::MemoryUsage().
Friends And Related Function Documentation
friend class G4Scheduler friend
Definition at line 155 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ITStepProcessor.hh
Member Data Documentation
size_t G4ITStepProcessor::fAtRestDoItProcTriggered private
Definition at line 377 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 377 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), GetAtRestDoItProcTriggered(), and GetAtRestIL().
G4ForceCondition G4ITStepProcessor::fCondition private
Definition at line 382 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 382 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), GetAtRestIL(), and GetCondition().
G4GPILSelection G4ITStepProcessor::fGPILSelection private
Definition at line 383 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 383 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), and GetGPILSelection().
G4double G4ITStepProcessor::fILTimeStep private
Definition at line 359 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 359 of file G4ITStepProcessor.hh
Referenced by ComputeInteractionLength(), ExtractILData(), G4ITStepProcessor(), and GetILTimeStep().
G4bool G4ITStepProcessor::fInitialized private
Definition at line 339 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 339 of file G4ITStepProcessor.hh
Referenced by ForceReInitialization(), G4ITStepProcessor(), and Initialize().
G4ITLeadingTracks G4ITStepProcessor::fLeadingTracks private
Definition at line 351 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 351 of file G4ITStepProcessor.hh
Referenced by ExtractILData(), PrepareLeadingTracks(), and ResetLeadingTracks().
G4int G4ITStepProcessor::fN2ndariesAlongStepDoIt private
Definition at line 371 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 371 of file G4ITStepProcessor.hh
Referenced by GetN2ndariesAlongStepDoIt(), and ResetSecondaries().
G4int G4ITStepProcessor::fN2ndariesAtRestDoIt private
Definition at line 370 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 370 of file G4ITStepProcessor.hh
Referenced by GetN2ndariesAtRestDoIt(), and ResetSecondaries().
G4int G4ITStepProcessor::fN2ndariesPostStepDoIt private
Definition at line 372 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 372 of file G4ITStepProcessor.hh
Referenced by GetN2ndariesPostStepDoIt(), and ResetSecondaries().
G4VITProcess* G4ITStepProcessor::fpCurrentProcess private
Definition at line 365 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 365 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), GetAtRestIL(), and GetCurrentProcess().
G4VPhysicalVolume* G4ITStepProcessor::fpCurrentVolume private
Definition at line 396 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 396 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), GetCurrentVolume(), InitDefineStep(), and SetInitialStep().
G4double G4ITStepProcessor::fPhysIntLength private
Definition at line 389 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 389 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), GetPhysIntLength(), and Initialize().
G4IT* G4ITStepProcessor::fpITrack private
Definition at line 415 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 415 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), InitDefineStep(), SetInitialStep(), SetTrack(), and SetupMembers().
G4ITNavigator* G4ITStepProcessor::fpNavigator private
Definition at line 346 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 346 of file G4ITStepProcessor.hh
Referenced by DoDefinePhysicalStepLength(), G4ITStepProcessor(), InitDefineStep(), SetInitialStep(), and SetNavigator().
size_t G4ITStepProcessor::fPostStepAtTimeDoItProcTriggered private
Definition at line 379 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 379 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), and GetPostStepAtTimeDoItProcTriggered().
size_t G4ITStepProcessor::fPostStepDoItProcTriggered private
Definition at line 378 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 378 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), and GetPostStepDoItProcTriggered().
G4VParticleChange* G4ITStepProcessor::fpParticleChange private
Definition at line 363 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 363 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), and GetParticleChange().
G4StepPoint* G4ITStepProcessor::fpPostStepPoint private
Definition at line 422 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 422 of file G4ITStepProcessor.hh
Referenced by CalculateSafety(), CleanProcessor(), and SetupMembers().
G4StepPoint* G4ITStepProcessor::fpPreStepPoint private
Definition at line 421 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 421 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), and SetupMembers().
ProcessGeneralInfo* G4ITStepProcessor::fpProcessInfo private
Definition at line 406 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 406 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), GetAtRestIL(), GetCurrentProcessInfo(), GetProcessInfo(), and SetupGeneralProcessInfo().
G4double G4ITStepProcessor::fPreviousTimeStep private
Definition at line 361 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 361 of file G4ITStepProcessor.hh
Referenced by G4ITStepProcessor(), and SetPreviousStepTime().
std::map<const G4ParticleDefinition*, ProcessGeneralInfo*> G4ITStepProcessor::fProcessGeneralInfoMap private
Definition at line 405 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 405 of file G4ITStepProcessor.hh
Referenced by ClearProcessInfo(), GetProcessInfo(), and SetupGeneralProcessInfo().
G4TrackVector* G4ITStepProcessor::fpSecondary private
Definition at line 362 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 362 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), GetSecondaries(), InitDefineStep(), SetupMembers(), and ~G4ITStepProcessor().
G4ITStepProcessorState* G4ITStepProcessor::fpState private
Definition at line 418 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 418 of file G4ITStepProcessor.hh
Referenced by CalculateSafety(), CleanProcessor(), DoDefinePhysicalStepLength(), GetAtRestIL(), GetProcessorState(), InitDefineStep(), SetInitialStep(), and SetupMembers().
G4Step* G4ITStepProcessor::fpStep private
Definition at line 419 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 419 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), GetStep(), InitDefineStep(), SetInitialStep(), SetStep(), SetTrack(), SetupMembers(), and ~G4ITStepProcessor().
G4Track* G4ITStepProcessor::fpTrack private
Definition at line 414 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 414 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), ExtractILData(), GetAtRestIL(), GetProcessInfo(), GetTrack(), InitDefineStep(), SetInitialStep(), and SetTrack().
G4ITTrackHolder* G4ITStepProcessor::fpTrackContainer private
Definition at line 350 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 350 of file G4ITStepProcessor.hh
Referenced by ComputeInteractionLength(), G4ITStepProcessor(), and Initialize().
G4TrackingInformation* G4ITStepProcessor::fpTrackingInfo private
Definition at line 416 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 416 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), GetAtRestIL(), and SetTrack().
G4ITTrackingManager* G4ITStepProcessor::fpTrackingManager private
Definition at line 341 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 341 of file G4ITStepProcessor.hh
Referenced by ExtractILData(), G4ITStepProcessor(), GetTrackingManager(), InitDefineStep(), Initialize(), and SetTrackingManager().
G4ITTransportation* G4ITStepProcessor::fpTransportation private
Definition at line 407 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 407 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), and DoDefinePhysicalStepLength().
G4VITSteppingVerbose* G4ITStepProcessor::fpVerbose private
Definition at line 348 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 348 of file G4ITStepProcessor.hh
Referenced by DoDefinePhysicalStepLength(), G4ITStepProcessor(), and Initialize().
G4int G4ITStepProcessor::fStoreTrajectory private
Definition at line 347 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 347 of file G4ITStepProcessor.hh
Referenced by G4ITStepProcessor().
G4double G4ITStepProcessor::fTimeStep private
Definition at line 358 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 358 of file G4ITStepProcessor.hh
Referenced by CleanProcessor(), DoDefinePhysicalStepLength(), ExtractILData(), GetAtRestIL(), and GetInteractionTime().
G4double G4ITStepProcessor::kCarTolerance private
Definition at line 343 of file G4ITStepProcessor.hh.
View newest version in sPHENIX GitHub at line 343 of file G4ITStepProcessor.hh
Referenced by CalculateSafety(), G4ITStepProcessor(), and Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITStepProcessor.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITStepProcessor.cc
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITStepProcessor2.cc