ECCE @ EIC Software: G4tgbMaterialMixtureByVolume Class Reference
G4tgbMaterialMixtureByVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixtureByVolume.hh>
Public Member Functions
G4tgbMaterialMixtureByVolume ()
G4tgbMaterialMixtureByVolume (G4tgrMaterial *tgr)
~G4tgbMaterialMixtureByVolume ()
G4Material * BuildG4Material ()
void TransformToFractionsByWeight ()
Public Member Functions inherited from G4tgbMaterialMixture
G4tgbMaterialMixture ()
virtual ~G4tgbMaterialMixture ()
virtual const G4String & GetComponent (G4int i) const
virtual G4double GetFraction (G4int i) const
G4tgbMaterialMixture & operator= (const G4tgbMaterialMixture &)
Public Member Functions inherited from G4tgbMaterial
G4tgbMaterial ()
virtual ~G4tgbMaterial ()
G4tgbMaterial (G4tgrMaterial *tgr)
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfMaterials () const
G4double GetA () const
G4double GetZ () const
const G4String & GetType () const
G4tgrMaterial * GetTgrMate () const
Private Attributes
std::vector< G4double > theFractionsByWeight
Additional Inherited Members
Protected Attributes inherited from G4tgbMaterial
G4tgrMaterial * theTgrMate
G4Material * theG4Mate
Detailed Description
Definition at line 49 of file G4tgbMaterialMixtureByVolume.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialMixtureByVolume.hh
Constructor & Destructor Documentation
G4tgbMaterialMixtureByVolume::G4tgbMaterialMixtureByVolume ()
Definition at line 43 of file G4tgbMaterialMixtureByVolume.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgbMaterialMixtureByVolume.cc
G4tgbMaterialMixtureByVolume::G4tgbMaterialMixtureByVolume (G4tgrMaterial * tgr)
Definition at line 55 of file G4tgbMaterialMixtureByVolume.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgbMaterialMixtureByVolume.cc
References G4tgbMaterial::theTgrMate.
G4tgbMaterialMixtureByVolume::~G4tgbMaterialMixtureByVolume ()
Definition at line 49 of file G4tgbMaterialMixtureByVolume.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialMixtureByVolume.cc
Member Function Documentation
G4Material * G4tgbMaterialMixtureByVolume::BuildG4Material () virtual
Implements G4tgbMaterial.
Definition at line 62 of file G4tgbMaterialMixtureByVolume.cc.
View newest version in sPHENIX GitHub at line 62 of file G4tgbMaterialMixtureByVolume.cc
References G4Material::AddMaterial(), cm3, FatalException, G4tgbMaterialMgr::FindOrBuildG4Material(), Acts::UnitConstants::g, G4cout, G4endl, G4Exception(), G4tgbMaterialMixture::GetComponent(), G4tgrMaterial::GetDensity(), G4tgbMaterialMgr::GetInstance(), G4tgrMaterial::GetName(), G4tgrMaterial::GetNumberOfComponents(), G4tgrMaterial::GetPressure(), G4tgrMaterial::GetState(), G4tgrMaterial::GetTemperature(), G4tgrMessenger::GetVerboseLevel(), theFractionsByWeight, G4tgbMaterial::theTgrMate, and TransformToFractionsByWeight().
void G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight () virtual
Reimplemented from G4tgbMaterialMixture.
Definition at line 123 of file G4tgbMaterialMixtureByVolume.cc.
View newest version in sPHENIX GitHub at line 123 of file G4tgbMaterialMixtureByVolume.cc
References FatalException, G4tgbMaterialMgr::FindOrBuildG4Material(), G4cout, G4endl, G4Exception(), G4tgbMaterialMixture::GetComponent(), G4Material::GetDensity(), G4tgbMaterialMixture::GetFraction(), G4tgbMaterialMgr::GetInstance(), G4tgrMaterial::GetName(), G4Material::GetName(), G4tgrMaterial::GetNumberOfComponents(), G4tgrMessenger::GetVerboseLevel(), theFractionsByWeight, and G4tgbMaterial::theTgrMate.
Referenced by BuildG4Material().
Member Data Documentation
std::vector<G4double> G4tgbMaterialMixtureByVolume::theFractionsByWeight private
Definition at line 64 of file G4tgbMaterialMixtureByVolume.hh.
View newest version in sPHENIX GitHub at line 64 of file G4tgbMaterialMixtureByVolume.hh
Referenced by BuildG4Material(), and TransformToFractionsByWeight().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixtureByVolume.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterialMixtureByVolume.cc