ECCE @ EIC Software: G4DipBustGenerator Class Reference
G4DipBustGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4DipBustGenerator.hh>
Public Member Functions
G4DipBustGenerator (const G4String &name="")
virtual ~G4DipBustGenerator ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double out_energy, G4int Z, const G4Material *mat=nullptr) final
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr) final
G4double PolarAngle (G4double initial_energy, G4double final_energy, G4int Z)
virtual void PrintGeneratorInformation () const final
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
const G4String & GetName () const
Private Member Functions
G4double SampleCosTheta (G4double kinEnergy)
G4DipBustGenerator & operator= (const G4DipBustGenerator &right)=delete
G4DipBustGenerator (const G4DipBustGenerator &)=delete
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 54 of file G4DipBustGenerator.hh.
View newest version in sPHENIX GitHub at line 54 of file G4DipBustGenerator.hh
Constructor & Destructor Documentation
G4DipBustGenerator::G4DipBustGenerator (const G4String & name = "") explicit
Definition at line 62 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 62 of file G4DipBustGenerator.cc
G4DipBustGenerator::~G4DipBustGenerator () virtual
Definition at line 68 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 68 of file G4DipBustGenerator.cc
G4DipBustGenerator::G4DipBustGenerator (const G4DipBustGenerator &) private delete
Member Function Documentation
G4DipBustGenerator& G4DipBustGenerator::operator= (const G4DipBustGenerator & right) private delete
G4double G4DipBustGenerator::PolarAngle (G4double initial_energy, G4double final_energy, G4int Z)
Definition at line 106 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 106 of file G4DipBustGenerator.cc
References max, min, CLHEP::pi, SampleCosTheta(), and theta().
void G4DipBustGenerator::PrintGeneratorInformation () const final virtual
Definition at line 144 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 144 of file G4DipBustGenerator.cc
References G4cout, and G4endl.
G4double G4DipBustGenerator::SampleCosTheta (G4double kinEnergy) private
Definition at line 73 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 73 of file G4DipBustGenerator.cc
References G4Pow::A13(), kdfinder::abs(), c, Acts::Test::delta, CLHEP::electron_mass_c2, G4UniformRand, G4Pow::GetInstance(), max, and min.
Referenced by PolarAngle(), SampleDirection(), and SamplePairDirections().
G4ThreeVector & G4DipBustGenerator::SampleDirection (const G4DynamicParticle * dp, G4double out_energy, G4int Z, const G4Material * mat = nullptr) final virtual
Implements G4VEmAngularDistribution.
Definition at line 90 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 90 of file G4DipBustGenerator.cc
References G4VEmAngularDistribution::fLocalDirection, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), phi, CLHEP::Hep3Vector::rotateUz(), SampleCosTheta(), CLHEP::Hep3Vector::set(), and CLHEP::twopi.
void G4DipBustGenerator::SamplePairDirections (const G4DynamicParticle * dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector & dirElectron, G4ThreeVector & dirPositron, G4int Z = 0, const G4Material * mat = nullptr) final virtual
Reimplemented from G4VEmAngularDistribution.
Definition at line 118 of file G4DipBustGenerator.cc.
View newest version in sPHENIX GitHub at line 118 of file G4DipBustGenerator.cc
References G4UniformRand, G4DynamicParticle::GetMomentumDirection(), phi, CLHEP::Hep3Vector::rotateUz(), SampleCosTheta(), CLHEP::Hep3Vector::set(), and CLHEP::twopi.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4DipBustGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4DipBustGenerator.cc