ECCE @ EIC Software: G4ElectronIonPair Class Reference
G4ElectronIonPair Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4ElectronIonPair.hh>
Public Member Functions
G4ElectronIonPair (G4int verb)
virtual ~G4ElectronIonPair ()
G4double MeanNumberOfIonsAlongStep (const G4ParticleDefinition *, const G4Material *, G4double edepTotal, G4double edepNIEL=0.0)
G4double MeanNumberOfIonsAlongStep (const G4Step *)
G4int SampleNumberOfIonsAlongStep (const G4Step *)
std::vector< G4ThreeVector > * SampleIonsAlongStep (const G4Step *)
G4int ResidualeChargePostStep (const G4ParticleDefinition *, const G4TrackVector *secondary=nullptr, G4int processSubType=-1) const
G4int ResidualeChargePostStep (const G4Step *) const
G4double FindG4MeanEnergyPerIonPair (const G4Material *) const
void DumpMeanEnergyPerIonPair () const
void DumpG4MeanEnergyPerIonPair () const
void SetVerbose (G4int)
Private Member Functions
void Initialise ()
G4double FindMeanEnergyPerIonPair (const G4Material *) const
G4ElectronIonPair & operator= (const G4ElectronIonPair &right)=delete
G4ElectronIonPair (const G4ElectronIonPair &)=delete
Private Attributes
const G4Material * curMaterial
G4double curMeanEnergy
G4double invFanoFactor
G4int verbose
G4int nMaterials
std::vector< G4double > g4MatData
std::vector< G4String > g4MatNames
Detailed Description
Definition at line 73 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ElectronIonPair.hh
Constructor & Destructor Documentation
G4ElectronIonPair::G4ElectronIonPair (G4int verb) explicit
Definition at line 57 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ElectronIonPair.cc
References curMaterial, curMeanEnergy, Initialise(), invFanoFactor, nMaterials, and verbose.
G4ElectronIonPair::~G4ElectronIonPair () virtual
Definition at line 69 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ElectronIonPair.cc
G4ElectronIonPair::G4ElectronIonPair (const G4ElectronIonPair &) private delete
Member Function Documentation
void G4ElectronIonPair::DumpG4MeanEnergyPerIonPair () const
Definition at line 189 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 189 of file G4ElectronIonPair.cc
References eV, G4cout, G4endl, g4MatData, g4MatNames, and nMaterials.
void G4ElectronIonPair::DumpMeanEnergyPerIonPair () const
Definition at line 169 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 169 of file G4ElectronIonPair.cc
References eV, G4cout, G4endl, G4Material::GetIonisation(), G4Material::GetMaterialTable(), G4IonisParamMat::GetMeanEnergyPerIonPair(), G4Material::GetName(), G4Material::GetNumberOfMaterials(), mat, and x.
G4double G4ElectronIonPair::FindG4MeanEnergyPerIonPair (const G4Material * mat) const
Definition at line 146 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 146 of file G4ElectronIonPair.cc
References eV, G4cout, G4endl, g4MatData, g4MatNames, G4Material::GetIonisation(), G4Material::GetName(), nMaterials, G4IonisParamMat::SetMeanEnergyPerIonPair(), and verbose.
Referenced by MeanNumberOfIonsAlongStep().
G4double G4ElectronIonPair::FindMeanEnergyPerIonPair (const G4Material *) const private
void G4ElectronIonPair::Initialise () private
Definition at line 203 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 203 of file G4ElectronIonPair.cc
References eV, g4MatData, g4MatNames, and nMaterials.
Referenced by G4ElectronIonPair().
G4double G4ElectronIonPair::MeanNumberOfIonsAlongStep (const G4ParticleDefinition * part, const G4Material * material, G4double edepTotal, G4double edepNIEL = 0.0)
Definition at line 74 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ElectronIonPair.cc
References curMaterial, curMeanEnergy, FindG4MeanEnergyPerIonPair(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanEnergyPerIonPair(), G4ParticleDefinition::GetPDGCharge(), and material().
Referenced by Run::AddEnergy(), MeanNumberOfIonsAlongStep(), and SampleNumberOfIonsAlongStep().
G4double G4ElectronIonPair::MeanNumberOfIonsAlongStep (const G4Step * step) inline
Definition at line 138 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ElectronIonPair.hh
References G4StepPoint::GetMaterial(), G4Step::GetNonIonizingEnergyDeposit(), G4Track::GetParticleDefinition(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), and MeanNumberOfIonsAlongStep().
G4ElectronIonPair& G4ElectronIonPair::operator= (const G4ElectronIonPair & right) private delete
G4int G4ElectronIonPair::ResidualeChargePostStep (const G4ParticleDefinition * , const G4TrackVector * secondary = nullptr, G4int processSubType = -1) const
Definition at line 133 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 133 of file G4ElectronIonPair.cc
Referenced by ResidualeChargePostStep().
G4int G4ElectronIonPair::ResidualeChargePostStep (const G4Step * step) const inline
Definition at line 156 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ElectronIonPair.hh
References G4Track::GetParticleDefinition(), G4Step::GetPostStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessSubType(), G4Step::GetSecondary(), G4Step::GetTrack(), and ResidualeChargePostStep().
std::vector< G4ThreeVector > * G4ElectronIonPair::SampleIonsAlongStep (const G4Step * step)
Definition at line 107 of file G4ElectronIonPair.cc.
View newest version in sPHENIX GitHub at line 107 of file G4ElectronIonPair.cc
References G4cout, G4endl, G4UniformRand, G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), SampleNumberOfIonsAlongStep(), v, and verbose.
G4int G4ElectronIonPair::SampleNumberOfIonsAlongStep (const G4Step * step) inline
Definition at line 147 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ElectronIonPair.hh
References G4lrint(), invFanoFactor, MeanNumberOfIonsAlongStep(), and G4INCL::DeJongSpin::shoot().
Referenced by Run::AddEnergy(), and SampleIonsAlongStep().
void G4ElectronIonPair::SetVerbose (G4int val) inline
Definition at line 166 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ElectronIonPair.hh
References verbose.
Referenced by G4LossTableManager::ResetParameters().
Member Data Documentation
const G4Material* G4ElectronIonPair::curMaterial private
Definition at line 124 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ElectronIonPair.hh
Referenced by G4ElectronIonPair(), and MeanNumberOfIonsAlongStep().
G4double G4ElectronIonPair::curMeanEnergy private
Definition at line 125 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ElectronIonPair.hh
Referenced by G4ElectronIonPair(), and MeanNumberOfIonsAlongStep().
std::vector<G4double> G4ElectronIonPair::g4MatData private
Definition at line 133 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ElectronIonPair.hh
Referenced by DumpG4MeanEnergyPerIonPair(), FindG4MeanEnergyPerIonPair(), and Initialise().
std::vector<G4String> G4ElectronIonPair::g4MatNames private
Definition at line 134 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ElectronIonPair.hh
Referenced by DumpG4MeanEnergyPerIonPair(), FindG4MeanEnergyPerIonPair(), and Initialise().
G4double G4ElectronIonPair::invFanoFactor private
Definition at line 127 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ElectronIonPair.hh
Referenced by G4ElectronIonPair(), and SampleNumberOfIonsAlongStep().
G4int G4ElectronIonPair::nMaterials private
Definition at line 130 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ElectronIonPair.hh
Referenced by DumpG4MeanEnergyPerIonPair(), FindG4MeanEnergyPerIonPair(), G4ElectronIonPair(), and Initialise().
G4int G4ElectronIonPair::verbose private
Definition at line 129 of file G4ElectronIonPair.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ElectronIonPair.hh
Referenced by FindG4MeanEnergyPerIonPair(), G4ElectronIonPair(), SampleIonsAlongStep(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4ElectronIonPair.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4ElectronIonPair.cc