ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/intercoms/pymodG4intercoms.cc File Reference
pymodG4intercoms.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4UImanager ()
void export_G4UIcommandTree ()
void export_G4UIcommand ()
void export_G4UIparameter ()
BOOST_PYTHON_MODULE (G4intercoms)
Function Documentation
BOOST_PYTHON_MODULE (G4intercoms)
Definition at line 44 of file pymodG4intercoms.cc.
View newest version in sPHENIX GitHub at line 44 of file pymodG4intercoms.cc
References export_G4UIcommand(), export_G4UIcommandTree(), export_G4UImanager(), and export_G4UIparameter().
void export_G4UIcommand ()
Definition at line 62 of file pyG4UIcommand.cc.
View newest version in sPHENIX GitHub at line 62 of file pyG4UIcommand.cc
References pyG4UIcommand::f_GetStateList(), G4UIcommand::GetCommandName(), G4UIcommand::GetCommandPath(), G4UIcommand::GetCurrentValue(), G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), G4UIcommand::GetParameter(), G4UIcommand::GetParameterEntries(), G4UIcommand::GetRange(), G4UIcommand::GetTitle(), G4UIcommand::IsAvailable(), and G4UIcommand::List().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UIcommandTree ()
Definition at line 54 of file pyG4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4UIcommandTree.cc
References G4UIcommandTree::CreateHTML(), pyG4UIcommandTree::f1_GetTree, pyG4UIcommandTree::f2_GetTree, G4UIcommandTree::FindPath(), G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommandTree::GetGuidance(), G4UIcommandTree::GetPathName(), G4UIcommandTree::GetTitle(), G4UIcommandTree::GetTreeEntry(), G4UIcommandTree::List(), G4UIcommandTree::ListCurrent(), and G4UIcommandTree::ListCurrentWithNum().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UImanager ()
Definition at line 118 of file pyG4UImanager.cc.
View newest version in sPHENIX GitHub at line 118 of file pyG4UImanager.cc
References pyG4UImanager::ApplyUICommand_1(), pyG4UImanager::ApplyUICommand_2(), G4UImanager::CreateHTML(), G4UImanager::ExecuteMacroFile(), pyG4UImanager::f1_ApplyCommand, pyG4UImanager::f2_ApplyCommand, G4UImanager::GetCurrentValues(), G4UImanager::GetMacroSearchPath(), G4UImanager::GetPauseAtBeginOfEvent(), G4UImanager::GetPauseAtEndOfEvent(), G4UImanager::GetTree(), G4UImanager::GetUIpointer(), G4UImanager::GetVerboseLevel(), G4UImanager::SetMacroSearchPath(), G4UImanager::SetPauseAtBeginOfEvent(), G4UImanager::SetPauseAtEndOfEvent(), and G4UImanager::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UIparameter ()
Definition at line 39 of file pyG4UIparameter.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4UIparameter.cc
References G4UIparameter::GetCurrentAsDefault(), G4UIparameter::GetDefaultValue(), G4UIparameter::GetParameterCandidates(), G4UIparameter::GetParameterGuidance(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), G4UIparameter::IsOmittable(), and G4UIparameter::List().
Referenced by BOOST_PYTHON_MODULE().