ECCE @ EIC Software: G4PSPopulation Class Reference
G4PSPopulation Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSPopulation.hh>
Public Member Functions
G4PSPopulation (G4String name, G4int depth=0)
virtual ~G4PSPopulation ()
void Weighted (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
G4bool weighted
std::map< G4int, G4TrackLogger > fCellTrackLogger
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 48 of file G4PSPopulation.hh.
View newest version in sPHENIX GitHub at line 48 of file G4PSPopulation.hh
Constructor & Destructor Documentation
G4PSPopulation::G4PSPopulation (G4String name, G4int depth = 0)
Definition at line 41 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 41 of file G4PSPopulation.cc
References SetUnit().
G4PSPopulation::~G4PSPopulation () virtual
Definition at line 47 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PSPopulation.cc
Member Function Documentation
void G4PSPopulation::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 76 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 76 of file G4PSPopulation.cc
References G4VTHitsMap< T, Map_t >::clear(), EvtMap, and fCellTrackLogger.
void G4PSPopulation::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 81 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 81 of file G4PSPopulation.cc
void G4PSPopulation::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 71 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 71 of file G4PSPopulation.cc
References fCellTrackLogger.
void G4PSPopulation::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 64 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4PSPopulation.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, EvtMap, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
void G4PSPopulation::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 84 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 84 of file G4PSPopulation.cc
References G4VPrimitiveScorer::detector, G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and G4VPrimitiveScorer::GetUnitValue().
G4bool G4PSPopulation::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 50 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PSPopulation.cc
References G4VTHitsMap< T, Map_t >::add(), EvtMap, fCellTrackLogger, G4TrackLogger::FirstEnterance(), G4VPrimitiveScorer::GetIndex(), G4Step::GetPreStepPoint(), G4Step::GetTrack(), G4Track::GetTrackID(), G4StepPoint::GetWeight(), TRUE, and weighted.
void G4PSPopulation::SetUnit (const G4String & unit) virtual
Definition at line 98 of file G4PSPopulation.cc.
View newest version in sPHENIX GitHub at line 98 of file G4PSPopulation.cc
References G4Exception(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::GetUnit(), JustWarning, G4VPrimitiveScorer::unitName, and G4VPrimitiveScorer::unitValue.
Referenced by G4PSPopulation().
void G4PSPopulation::Weighted (G4bool flg = true) inline
Definition at line 60 of file G4PSPopulation.hh.
View newest version in sPHENIX GitHub at line 60 of file G4PSPopulation.hh
References weighted.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
Member Data Documentation
G4THitsMap<G4double>* G4PSPopulation::EvtMap private
Definition at line 76 of file G4PSPopulation.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PSPopulation.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
std::map<G4int,G4TrackLogger> G4PSPopulation::fCellTrackLogger private
Definition at line 78 of file G4PSPopulation.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PSPopulation.hh
Referenced by clear(), EndOfEvent(), and ProcessHits().
G4int G4PSPopulation::HCID private
Definition at line 75 of file G4PSPopulation.hh.
View newest version in sPHENIX GitHub at line 75 of file G4PSPopulation.hh
Referenced by Initialize().
G4bool G4PSPopulation::weighted private
Definition at line 77 of file G4PSPopulation.hh.
View newest version in sPHENIX GitHub at line 77 of file G4PSPopulation.hh
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSPopulation.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSPopulation.cc