ECCE @ EIC Software: G4Nucleus Class Reference
G4Nucleus Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4Nucleus.hh>
Public Member Functions
G4Nucleus ()
G4Nucleus (const G4double A, const G4double Z)
G4Nucleus (const G4int A, const G4int Z)
G4Nucleus (const G4Material *aMaterial)
~G4Nucleus ()
G4Nucleus (const G4Nucleus &right)
G4Nucleus & operator= (const G4Nucleus &right)
G4bool operator== (const G4Nucleus &right) const
G4bool operator!= (const G4Nucleus &right) const
void ChooseParameters (const G4Material *aMaterial)
void SetParameters (const G4double A, const G4double Z)
void SetParameters (const G4int A, const G4int Z)
G4int GetA_asInt () const
G4int GetN_asInt () const
G4int GetZ_asInt () const
const G4Isotope * GetIsotope ()
void SetIsotope (const G4Isotope *iso)
G4DynamicParticle * ReturnTargetParticle () const
G4double AtomicMass (const G4double A, const G4double Z) const
G4double AtomicMass (const G4int A, const G4int Z) const
G4double GetThermalPz (const G4double mass, const G4double temp) const
G4ReactionProduct GetThermalNucleus (G4double aMass, G4double temp=-1) const
G4ReactionProduct GetBiasedThermalNucleus (G4double aMass, G4ThreeVector aVelocity, G4double temp=-1) const
G4double Cinema (G4double kineticEnergy)
G4double EvaporationEffects (G4double kineticEnergy)
G4double AnnihilationEvaporationEffects (G4double kineticEnergy, G4double ekOrg)
G4double GetPNBlackTrackEnergy () const
G4double GetDTABlackTrackEnergy () const
G4double GetAnnihilationPNBlackTrackEnergy () const
G4double GetAnnihilationDTABlackTrackEnergy () const
G4ThreeVector GetFermiMomentum ()
G4ReactionProductVector * Fragmentate ()
void AddExcitationEnergy (G4double anEnergy)
void AddMomentum (const G4ThreeVector aMomentum)
G4double GetEnergyDeposit ()
Private Attributes
G4int theA
G4int theZ
G4double aEff
G4double zEff
const G4Isotope * fIsotope
G4double pnBlackTrackEnergy
G4double dtaBlackTrackEnergy
G4double pnBlackTrackEnergyfromAnnihilation
G4double dtaBlackTrackEnergyfromAnnihilation
G4double excitationEnergy
G4ThreeVector momentum
G4double fermiMomentum
G4double theTemp
Detailed Description
Definition at line 50 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 50 of file G4Nucleus.hh
Constructor & Destructor Documentation
G4Nucleus::G4Nucleus ()
Definition at line 54 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 54 of file G4Nucleus.cc
References dtaBlackTrackEnergy, dtaBlackTrackEnergyfromAnnihilation, excitationEnergy, fermi, fermiMomentum, fIsotope, source.hepunit::hbarc, kelvin, momentum, pnBlackTrackEnergy, pnBlackTrackEnergyfromAnnihilation, and theTemp.
G4Nucleus::G4Nucleus (const G4double A, const G4double Z)
Definition at line 68 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 68 of file G4Nucleus.cc
References dtaBlackTrackEnergy, dtaBlackTrackEnergyfromAnnihilation, excitationEnergy, fermi, fermiMomentum, fIsotope, source.hepunit::hbarc, kelvin, momentum, pnBlackTrackEnergy, pnBlackTrackEnergyfromAnnihilation, SetParameters(), and theTemp.
G4Nucleus::G4Nucleus (const G4int A, const G4int Z)
Definition at line 82 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 82 of file G4Nucleus.cc
References dtaBlackTrackEnergy, dtaBlackTrackEnergyfromAnnihilation, excitationEnergy, fermi, fermiMomentum, fIsotope, source.hepunit::hbarc, kelvin, momentum, pnBlackTrackEnergy, pnBlackTrackEnergyfromAnnihilation, SetParameters(), and theTemp.
G4Nucleus::G4Nucleus (const G4Material * aMaterial)
Definition at line 96 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 96 of file G4Nucleus.cc
References ChooseParameters(), dtaBlackTrackEnergy, dtaBlackTrackEnergyfromAnnihilation, excitationEnergy, fermi, fermiMomentum, fIsotope, G4Material::GetTemperature(), source.hepunit::hbarc, momentum, pnBlackTrackEnergy, pnBlackTrackEnergyfromAnnihilation, and theTemp.
G4Nucleus::~G4Nucleus ()
Definition at line 110 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 110 of file G4Nucleus.cc
G4Nucleus::G4Nucleus (const G4Nucleus & right) inline
Definition at line 61 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 61 of file G4Nucleus.hh
References right.
Member Function Documentation
void G4Nucleus::AddExcitationEnergy (G4double anEnergy)
Definition at line 449 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 449 of file G4Nucleus.cc
References excitationEnergy.
void G4Nucleus::AddMomentum (const G4ThreeVector aMomentum)
Definition at line 444 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 444 of file G4Nucleus.cc
References momentum.
G4double G4Nucleus::AnnihilationEvaporationEffects (G4double kineticEnergy, G4double ekOrg)
Definition at line 337 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 337 of file G4Nucleus.cc
References aEff, dtaBlackTrackEnergyfromAnnihilation, G4Exp(), G4Log(), G4UniformRand, GeV, max, min, and pnBlackTrackEnergyfromAnnihilation.
Referenced by G4RPGInelastic::CalculateMomenta().
G4double G4Nucleus::AtomicMass (const G4double A, const G4double Z) const
Definition at line 254 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 254 of file G4Nucleus.cc
References G4NucleiProperties::GetNuclearMass().
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4NeutrinoNucleusModel::CoherentPion(), G4NeutrinoNucleusModel::FinalBarion(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
G4double G4Nucleus::AtomicMass (const G4int A, const G4int Z) const
Definition at line 261 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 261 of file G4Nucleus.cc
References G4NucleiProperties::GetNuclearMass().
void G4Nucleus::ChooseParameters (const G4Material * aMaterial)
Definition at line 172 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 172 of file G4Nucleus.cc
References aEff, G4UniformRand, G4Material::GetElementVector(), G4Element::GetIsotope(), G4Isotope::GetN(), G4Element::GetN(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetVecNbOfAtomsPerVolume(), G4Isotope::GetZ(), G4Element::GetZ(), sum, theA, theZ, and zEff.
Referenced by G4Nucleus().
G4double G4Nucleus::Cinema (G4double kineticEnergy)
Definition at line 382 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 382 of file G4Nucleus.cc
References kdfinder::abs(), aEff, e, G4Exp(), G4Log(), GeV, max, min, temp1, and temp2.
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), and G4RPGInelastic::CalculateMomenta().
G4double G4Nucleus::EvaporationEffects (G4double kineticEnergy)
Definition at line 278 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 278 of file G4Nucleus.cc
References aEff, dtaBlackTrackEnergy, G4Exp(), G4Log(), G4UniformRand, GeV, max, min, pnBlackTrackEnergy, and zEff.
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), and G4RPGAntiKZeroInelastic::ApplyYourself().
G4ReactionProductVector * G4Nucleus::Fragmentate ()
Definition at line 438 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 438 of file G4Nucleus.cc
G4int G4Nucleus::GetA_asInt () const inline
Definition at line 109 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 109 of file G4Nucleus.hh
References theA.
Referenced by G4INCLXXInterface::AccurateProjectile(), G4RPGReaction::AddBlackTrackParticles(), G4BinaryLightIonReaction::ApplyYourself(), G4LEnp::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4LEpp::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4LENDGammaModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RPGInelastic::CalculateMomenta(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4HadronicProcess::CheckResult(), G4NeutrinoNucleusModel::CoherentPion(), G4CascadeInterface::createTarget(), G4MuonicAtomDecay::DecayIt(), G4NeutrinoNucleusModel::FermiMomentum(), G4HadronicProcess::FillResult(), G4NeutrinoNucleusModel::FinalBarion(), G4QuasiElasticChannel::GetFraction(), G4NeutrinoNucleusModel::GgSampleNM(), G4FTFModel::Init(), G4LMsdGenerator::IsApplicable(), G4RPGReaction::NuclearReaction(), G4NeutrinoNucleusModel::NucleonMomentum(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4RPGPionSuppression::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGReaction::Rotate(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4QuasiElasticChannel::Scatter(), G4VPartonStringModel::Scatter(), G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
G4double G4Nucleus::GetAnnihilationDTABlackTrackEnergy () const inline
Definition at line 159 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 159 of file G4Nucleus.hh
References dtaBlackTrackEnergyfromAnnihilation.
Referenced by G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
G4double G4Nucleus::GetAnnihilationPNBlackTrackEnergy () const inline
Definition at line 156 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 156 of file G4Nucleus.hh
References pnBlackTrackEnergyfromAnnihilation.
Referenced by G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
G4ReactionProduct G4Nucleus::GetBiasedThermalNucleus (G4double aMass, G4ThreeVector aVelocity, G4double temp = -1) const
Definition at line 113 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 113 of file G4Nucleus.cc
References G4endl, G4Exception(), G4UniformRand, G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4ParticleDefinition::GetPDGMass(), GetThermalNucleus(), JustWarning, source.hepunit::k_Boltzmann, CLHEP::Hep3Vector::mag(), G4Neutron::Neutron(), and norm.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), and G4ParticleHPThermalBoost::GetThermalEnergy().
G4double G4Nucleus::GetDTABlackTrackEnergy () const inline
Definition at line 153 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 153 of file G4Nucleus.hh
References dtaBlackTrackEnergy.
Referenced by G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
G4double G4Nucleus::GetEnergyDeposit () inline
Definition at line 184 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Nucleus.hh
References excitationEnergy.
Referenced by G4WilsonAbrasionModel::ApplyYourself().
G4ThreeVector G4Nucleus::GetFermiMomentum ()
Definition at line 412 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 412 of file G4Nucleus.cc
References fermiMomentum, G4UniformRand, phi, pi, and G4INCL::DeJongSpin::shoot().
Referenced by CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself().
const G4Isotope* G4Nucleus::GetIsotope () inline
Definition at line 119 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 119 of file G4Nucleus.hh
References fIsotope.
Referenced by G4LENDorBERTModel::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4LENDGammaModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), and G4HadronicProcess::GetTargetIsotope().
G4int G4Nucleus::GetN_asInt () const inline
Definition at line 112 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 112 of file G4Nucleus.hh
References theA, and theZ.
Referenced by G4QuasiElasticChannel::GetFraction().
G4double G4Nucleus::GetPNBlackTrackEnergy () const inline
Definition at line 150 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Nucleus.hh
References pnBlackTrackEnergy.
Referenced by G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
G4ReactionProduct G4Nucleus::GetThermalNucleus (G4double aMass, G4double temp = -1) const
Definition at line 143 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 143 of file G4Nucleus.cc
References G4ReactionProduct::GetMass(), GetThermalPz(), G4Neutron::Neutron(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), theTarget, and theTemp.
Referenced by GetBiasedThermalNucleus(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), and G4ParticleHPElasticData::GetCrossSection().
G4double G4Nucleus::GetThermalPz (const G4double mass, const G4double temp) const
Definition at line 268 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 268 of file G4Nucleus.cc
References source.hepunit::k_Boltzmann, and G4INCL::DeJongSpin::shoot().
Referenced by GetThermalNucleus().
G4int G4Nucleus::GetZ_asInt () const inline
Definition at line 115 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 115 of file G4Nucleus.hh
References theZ.
Referenced by G4INCLXXInterface::AccurateProjectile(), G4RPGReaction::AddBlackTrackParticles(), G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4BinaryLightIonReaction::ApplyYourself(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4LENDGammaModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4HadronicProcess::CheckResult(), G4NeutrinoNucleusModel::CoherentPion(), G4CascadeInterface::createTarget(), G4MuonicAtomDecay::DecayIt(), G4NeutrinoNucleusModel::FermiMomentum(), G4HadronicProcess::FillResult(), G4NeutrinoNucleusModel::FinalBarion(), G4QuasiElasticChannel::GetFraction(), G4FTFModel::Init(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4NuMuNucleusCcModel::IsApplicable(), G4DiffuseElasticV2::IsApplicable(), G4NuMuNucleusNcModel::IsApplicable(), G4NeutrinoNucleusModel::IsApplicable(), G4DiffuseElastic::IsApplicable(), G4hhElastic::IsApplicable(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4LightMedia::NeutronExchange(), G4LightMedia::OmegaMinusExchange(), G4LightMedia::PionPlusExchange(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4LightMedia::ProtonExchange(), G4RPGPionSuppression::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4QuasiElasticChannel::Scatter(), G4VPartonStringModel::Scatter(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4RPGNeutronInelastic::SlowNeutron(), G4RPGProtonInelastic::SlowProton(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
G4bool G4Nucleus::operator!= (const G4Nucleus & right) const inline
Definition at line 89 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 89 of file G4Nucleus.hh
G4Nucleus& G4Nucleus::operator= (const G4Nucleus & right) inline
Definition at line 64 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 64 of file G4Nucleus.hh
References aEff, dtaBlackTrackEnergy, dtaBlackTrackEnergyfromAnnihilation, excitationEnergy, fermiMomentum, fIsotope, momentum, pnBlackTrackEnergy, pnBlackTrackEnergyfromAnnihilation, theA, theTemp, theZ, and zEff.
G4bool G4Nucleus::operator== (const G4Nucleus & right) const inline
Definition at line 86 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Nucleus.hh
G4DynamicParticle * G4Nucleus::ReturnTargetParticle () const
Definition at line 241 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 241 of file G4Nucleus.cc
References aEff, G4UniformRand, G4Neutron::Neutron(), G4Proton::Proton(), G4DynamicParticle::SetDefinition(), and zEff.
Referenced by G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4LightMedia::NeutronExchange(), G4LightMedia::OmegaMinusExchange(), G4LightMedia::PionPlusExchange(), G4LightMedia::ProtonExchange(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
void G4Nucleus::SetIsotope (const G4Isotope * iso) inline
Definition at line 122 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 122 of file G4Nucleus.hh
References aEff, fIsotope, G4Isotope::GetN(), G4Isotope::GetZ(), theA, theZ, and zEff.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), and G4CrossSectionDataStore::SampleZandA().
void G4Nucleus::SetParameters (const G4double A, const G4double Z)
Definition at line 212 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 212 of file G4Nucleus.cc
References A(), aEff, fIsotope, G4lrint(), theA, theZ, Z, and zEff.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), CexmcHadronicProcess::CalculateTargetNucleus(), G4MuonicAtomDecay::DecayIt(), G4Nucleus(), and G4ElementSelector::SelectZandA().
void G4Nucleus::SetParameters (const G4int A, const G4int Z)
Definition at line 226 of file G4Nucleus.cc.
View newest version in sPHENIX GitHub at line 226 of file G4Nucleus.cc
References A(), aEff, fIsotope, theA, theZ, Z, and zEff.
Member Data Documentation
G4double G4Nucleus::aEff private
Definition at line 195 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 195 of file G4Nucleus.hh
Referenced by AnnihilationEvaporationEffects(), ChooseParameters(), Cinema(), EvaporationEffects(), operator=(), ReturnTargetParticle(), SetIsotope(), and SetParameters().
G4double G4Nucleus::dtaBlackTrackEnergy private
Definition at line 202 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 202 of file G4Nucleus.hh
Referenced by EvaporationEffects(), G4Nucleus(), GetDTABlackTrackEnergy(), and operator=().
G4double G4Nucleus::dtaBlackTrackEnergyfromAnnihilation private
Definition at line 207 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 207 of file G4Nucleus.hh
Referenced by AnnihilationEvaporationEffects(), G4Nucleus(), GetAnnihilationDTABlackTrackEnergy(), and operator=().
G4double G4Nucleus::excitationEnergy private
Definition at line 214 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 214 of file G4Nucleus.hh
Referenced by AddExcitationEnergy(), G4Nucleus(), GetEnergyDeposit(), and operator=().
G4double G4Nucleus::fermiMomentum private
Definition at line 225 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 225 of file G4Nucleus.hh
Referenced by G4Nucleus(), GetFermiMomentum(), and operator=().
const G4Isotope* G4Nucleus::fIsotope private
Definition at line 198 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 198 of file G4Nucleus.hh
Referenced by G4Nucleus(), GetIsotope(), operator=(), SetIsotope(), and SetParameters().
G4ThreeVector G4Nucleus::momentum private
Definition at line 217 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Nucleus.hh
Referenced by AddMomentum(), G4Nucleus(), and operator=().
G4double G4Nucleus::pnBlackTrackEnergy private
Definition at line 200 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 200 of file G4Nucleus.hh
Referenced by EvaporationEffects(), G4Nucleus(), GetPNBlackTrackEnergy(), and operator=().
G4double G4Nucleus::pnBlackTrackEnergyfromAnnihilation private
Definition at line 204 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 204 of file G4Nucleus.hh
Referenced by AnnihilationEvaporationEffects(), G4Nucleus(), GetAnnihilationPNBlackTrackEnergy(), and operator=().
G4int G4Nucleus::theA private
Definition at line 193 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 193 of file G4Nucleus.hh
Referenced by ChooseParameters(), GetA_asInt(), GetN_asInt(), operator=(), SetIsotope(), and SetParameters().
G4double G4Nucleus::theTemp private
Definition at line 226 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 226 of file G4Nucleus.hh
Referenced by G4Nucleus(), GetThermalNucleus(), and operator=().
G4int G4Nucleus::theZ private
Definition at line 194 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 194 of file G4Nucleus.hh
Referenced by ChooseParameters(), GetN_asInt(), GetZ_asInt(), operator=(), SetIsotope(), and SetParameters().
G4double G4Nucleus::zEff private
Definition at line 196 of file G4Nucleus.hh.
View newest version in sPHENIX GitHub at line 196 of file G4Nucleus.hh
Referenced by ChooseParameters(), EvaporationEffects(), operator=(), ReturnTargetParticle(), SetIsotope(), and SetParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4Nucleus.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4Nucleus.cc