ECCE @ EIC Software: G4ITSafetyHelper Class Reference
G4ITSafetyHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITSafetyHelper.hh>
Classes
class State
Public Member Functions
G4ITSafetyHelper ()
~G4ITSafetyHelper ()
G4double CheckNextStep (const G4ThreeVector &position, const G4ThreeVector &direction, const G4double currentMaxStep, G4double &newSafety)
G4double ComputeSafety (const G4ThreeVector &pGlobalPoint, G4double maxRadius=DBL_MAX)
void Locate (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &direction)
void ReLocateWithinVolume (const G4ThreeVector &pGlobalPoint)
void EnableParallelNavigation (G4bool parallel)
void InitialiseNavigator ()
G4int SetVerboseLevel (G4int lev)
G4VPhysicalVolume * GetWorldVolume ()
void SetCurrentSafety (G4double val, const G4ThreeVector &pos)
void InitialiseHelper ()
Public Member Functions inherited from G4TrackStateDependent< G4ITSafetyHelper >
virtual ~G4TrackStateDependent ()
virtual void SetTrackState (G4shared_ptr< StateType > state)
virtual G4VTrackStateHandle PopTrackState ()
virtual G4VTrackStateHandle GetTrackState () const
virtual StateTypeHandle GetConcreteTrackState () const
virtual void LoadTrackState (G4TrackStateManager &manager)
virtual void SaveTrackState (G4TrackStateManager &manager)
virtual void NewTrackState ()
virtual StateTypeHandle CreateTrackState () const
virtual void ResetTrackState ()
Public Member Functions inherited from G4VTrackStateDependent
G4VTrackStateDependent ()
virtual ~G4VTrackStateDependent ()
Private Attributes
G4PathFinder * fpPathFinder
G4ITNavigator * fpMassNavigator
G4int fMassNavigatorId
G4bool fUseParallelGeometries
G4bool fFirstCall
G4int fVerbose
Additional Inherited Members
Public Types inherited from G4TrackStateDependent< G4ITSafetyHelper >
typedef G4ITSafetyHelper ClassType
typedef G4TrackState
< G4ITSafetyHelper > StateType
typedef G4shared_ptr< StateType > StateTypeHandle
Protected Member Functions inherited from G4TrackStateDependent< G4ITSafetyHelper >
G4TrackStateDependent ()
Protected Attributes inherited from G4TrackStateDependent< G4ITSafetyHelper >
StateTypeHandle fpTrackState
Detailed Description
Definition at line 54 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ITSafetyHelper.hh
Constructor & Destructor Documentation
G4ITSafetyHelper::G4ITSafetyHelper ()
Definition at line 41 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ITSafetyHelper.cc
References fMassNavigatorId, fpMassNavigator, and fpPathFinder.
G4ITSafetyHelper::~G4ITSafetyHelper ()
Definition at line 89 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ITSafetyHelper.cc
Member Function Documentation
G4double G4ITSafetyHelper::CheckNextStep (const G4ThreeVector & position, const G4ThreeVector & direction, const G4double currentMaxStep, G4double & newSafety)
Definition at line 93 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ITSafetyHelper.cc
References fpMassNavigator, G4TrackStateDependent< G4ITSafetyHelper >::fpTrackState, and position.
Referenced by G4DNABrownianTransportation::ComputeGeomLimit().
G4double G4ITSafetyHelper::ComputeSafety (const G4ThreeVector & pGlobalPoint, G4double maxRadius = DBL_MAX)
Definition at line 111 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ITSafetyHelper.cc
References G4PathFinder::ComputeSafety(), fpMassNavigator, fpPathFinder, G4TrackStateDependent< G4ITSafetyHelper >::fpTrackState, fUseParallelGeometries, and position.
void G4ITSafetyHelper::EnableParallelNavigation (G4bool parallel) inline
Referenced by G4ITPathFinder::EnableParallelNavigation().
G4VPhysicalVolume * G4ITSafetyHelper::GetWorldVolume () inline
Definition at line 154 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ITSafetyHelper.hh
References fpMassNavigator.
Referenced by G4DNABrownianTransportation::ComputeGeomLimit().
void G4ITSafetyHelper::InitialiseHelper ()
Definition at line 79 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ITSafetyHelper.cc
References fFirstCall, InitialiseNavigator(), and G4TrackStateDependent< G4ITSafetyHelper >::NewTrackState().
Referenced by G4ITTransportation::BuildPhysicsTable(), G4DNABrownianTransportation::BuildPhysicsTable(), and G4ITPathFinder::PrepareNewTrack().
void G4ITSafetyHelper::InitialiseNavigator ()
Definition at line 55 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ITSafetyHelper.cc
References FatalException, fpMassNavigator, fpPathFinder, G4Exception(), G4PathFinder::GetInstance(), G4ITTransportationManager::GetNavigatorForTracking(), and G4ITTransportationManager::GetTransportationManager().
Referenced by InitialiseHelper().
void G4ITSafetyHelper::Locate (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & direction)
Definition at line 183 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 183 of file G4ITSafetyHelper.cc
References fpMassNavigator, fpPathFinder, fUseParallelGeometries, and G4PathFinder::Locate().
void G4ITSafetyHelper::ReLocateWithinVolume (const G4ThreeVector & pGlobalPoint)
Definition at line 151 of file G4ITSafetyHelper.cc.
View newest version in sPHENIX GitHub at line 151 of file G4ITSafetyHelper.cc
References fpMassNavigator, fpPathFinder, G4TrackStateDependent< G4ITSafetyHelper >::fpTrackState, fUseParallelGeometries, fVerbose, G4endl, G4Exception(), JustWarning, CLHEP::Hep3Vector::mag2(), G4PathFinder::ReLocate(), and sqr().
void G4ITSafetyHelper::SetCurrentSafety (G4double val, const G4ThreeVector & pos) inline
Definition at line 160 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ITSafetyHelper.hh
References G4TrackStateDependent< G4ITSafetyHelper >::fpTrackState, and pos().
Referenced by G4ITTransportation::AlongStepGetPhysicalInteractionLength().
G4int G4ITSafetyHelper::SetVerboseLevel (G4int lev) inline
Definition at line 97 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ITSafetyHelper.hh
References fVerbose.
Member Data Documentation
G4bool G4ITSafetyHelper::fFirstCall private
Definition at line 115 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ITSafetyHelper.hh
Referenced by InitialiseHelper().
G4int G4ITSafetyHelper::fMassNavigatorId private
Definition at line 111 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ITSafetyHelper.hh
Referenced by G4ITSafetyHelper().
G4ITNavigator* G4ITSafetyHelper::fpMassNavigator private
Definition at line 110 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ITSafetyHelper.hh
Referenced by CheckNextStep(), ComputeSafety(), G4ITSafetyHelper(), GetWorldVolume(), InitialiseNavigator(), Locate(), and ReLocateWithinVolume().
G4PathFinder* G4ITSafetyHelper::fpPathFinder private
Definition at line 109 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ITSafetyHelper.hh
Referenced by ComputeSafety(), G4ITSafetyHelper(), InitialiseNavigator(), Locate(), and ReLocateWithinVolume().
G4bool G4ITSafetyHelper::fUseParallelGeometries private
Definition at line 113 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ITSafetyHelper.hh
Referenced by ComputeSafety(), Locate(), RegisterTrackState(), and ReLocateWithinVolume().
G4int G4ITSafetyHelper::fVerbose private
Definition at line 117 of file G4ITSafetyHelper.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ITSafetyHelper.hh
Referenced by ReLocateWithinVolume(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITSafetyHelper.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITSafetyHelper.cc