ECCE @ EIC Software: G4GDMLWriteMaterials Class Reference
G4GDMLWriteMaterials Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteMaterials.hh>
Public Member Functions
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void SolidsWrite (xercesc::DOMElement *)=0
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
G4GDMLWriteMaterials ()
virtual ~G4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from G4GDMLWriteDefine
G4GDMLWriteDefine ()
virtual ~G4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from G4GDMLWrite
G4GDMLWrite ()
virtual ~G4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (G4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
std::vector< const G4Isotope * > isotopeList
std::vector< const G4Element * > elementList
std::vector< const G4Material * > materialList
std::vector< const
G4PhysicsOrderedFreeVector * > propertyList
xercesc::DOMElement * materialsElement
Protected Attributes inherited from G4GDMLWriteDefine
xercesc::DOMElement * defineElement
Protected Attributes inherited from G4GDMLWrite
G4String SchemaLocation
xercesc::DOMDocument * doc
xercesc::DOMElement * extElement
xercesc::DOMElement * userinfoElement
XMLCh tempStr [10000]
G4GDMLAuxListType auxList
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Static Protected Attributes inherited from G4GDMLWriteDefine
static const G4double kRelativePrecision = DBL_EPSILON
static const G4double kAngularPrecision = DBL_EPSILON
static const G4double kLinearPrecision = DBL_EPSILON
Detailed Description
Definition at line 52 of file G4GDMLWriteMaterials.hh.
View newest version in sPHENIX GitHub at line 52 of file G4GDMLWriteMaterials.hh
Constructor & Destructor Documentation
G4GDMLWriteMaterials::G4GDMLWriteMaterials () protected
Definition at line 44 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 44 of file G4GDMLWriteMaterials.cc
G4GDMLWriteMaterials::~G4GDMLWriteMaterials () protected virtual
Definition at line 49 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 49 of file G4GDMLWriteMaterials.cc
Member Function Documentation
void G4GDMLWriteMaterials::AddElement (const G4Element * const elementPtr)
Definition at line 314 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 314 of file G4GDMLWriteMaterials.cc
References elementList, and ElementWrite().
Referenced by MaterialWrite().
void G4GDMLWriteMaterials::AddIsotope (const G4Isotope * const isotopePtr)
Definition at line 304 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 304 of file G4GDMLWriteMaterials.cc
References isotopeList, and IsotopeWrite().
Referenced by ElementWrite().
void G4GDMLWriteMaterials::AddMaterial (const G4Material * const materialPtr)
Definition at line 324 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 324 of file G4GDMLWriteMaterials.cc
References materialList, and MaterialWrite().
Referenced by G4GDMLWriteStructure::TraverseVolumeTree().
void G4GDMLWriteMaterials::AtomWrite (xercesc::DOMElement * element, const G4double & a) protected
Definition at line 54 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 54 of file G4GDMLWriteMaterials.cc
References Acts::UnitConstants::g, mole, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by ElementWrite(), IsotopeWrite(), and MaterialWrite().
void G4GDMLWriteMaterials::DWrite (xercesc::DOMElement * element, const G4double & d) protected
Definition at line 63 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GDMLWriteMaterials.cc
References cm3, Acts::UnitConstants::g, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by MaterialWrite().
void G4GDMLWriteMaterials::ElementWrite (const G4Element * const elementPtr) protected
Definition at line 111 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 111 of file G4GDMLWriteMaterials.cc
References AddIsotope(), AtomWrite(), G4GDMLWrite::GenerateName(), G4Element::GetA(), G4Element::GetIsotope(), G4Isotope::GetName(), G4Element::GetName(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZ(), materialsElement, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddElement().
void G4GDMLWriteMaterials::IsotopeWrite (const G4Isotope * const isotopePtr) protected
Definition at line 99 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 99 of file G4GDMLWriteMaterials.cc
References AtomWrite(), G4GDMLWrite::GenerateName(), G4Isotope::GetA(), G4Isotope::GetN(), G4Isotope::GetName(), G4Isotope::GetZ(), materialsElement, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddIsotope().
void G4GDMLWriteMaterials::MaterialsWrite (xercesc::DOMElement * element) virtual
Implements G4GDMLWrite.
Definition at line 290 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 290 of file G4GDMLWriteMaterials.cc
References elementList, G4cout, G4endl, isotopeList, materialList, materialsElement, G4GDMLWrite::NewElement(), and propertyList.
void G4GDMLWriteMaterials::MaterialWrite (const G4Material * const materialPtr) protected
Definition at line 146 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 146 of file G4GDMLWriteMaterials.cc
References AddElement(), AtomWrite(), DWrite(), G4GDMLWrite::GenerateName(), G4Material::GetA(), G4Material::GetDensity(), G4Material::GetElement(), G4Material::GetFractionVector(), G4Material::GetIonisation(), G4Material::GetMaterialPropertiesTable(), G4IonisParamMat::GetMeanExcitationEnergy(), G4Element::GetName(), G4Material::GetName(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4Material::GetPressure(), G4Material::GetState(), G4Material::GetTemperature(), G4Material::GetZ(), kStateGas, kStateLiquid, kStateSolid, materialsElement, MEEWrite(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), PropertyWrite(), PWrite(), source.hepunit::STP_Pressure, source.hepunit::STP_Temperature, and TWrite().
Referenced by AddMaterial().
void G4GDMLWriteMaterials::MEEWrite (xercesc::DOMElement * element, const G4double & MEE) protected
Definition at line 90 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 90 of file G4GDMLWriteMaterials.cc
References electronvolt, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by MaterialWrite().
void G4GDMLWriteMaterials::PropertyVectorWrite (const G4String & key, const G4PhysicsOrderedFreeVector * const pvec) protected
Definition at line 209 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 209 of file G4GDMLWriteMaterials.cc
References G4GDMLWriteDefine::defineElement, G4PhysicsVector::Energy(), G4GDMLWrite::GenerateName(), G4PhysicsVector::GetVectorLength(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), and propertyList.
Referenced by PropertyWrite(), and G4GDMLWriteSolids::PropertyWrite().
void G4GDMLWriteMaterials::PropertyWrite (xercesc::DOMElement * matElement, const G4Material * const mat) protected
Definition at line 233 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 233 of file G4GDMLWriteMaterials.cc
References G4GDMLWriteDefine::defineElement, G4Exception(), G4GDMLWrite::GenerateName(), G4MaterialPropertiesTable::GetConstPropertyMap(), G4MaterialPropertiesTable::GetMaterialConstPropertyNames(), G4Material::GetMaterialPropertiesTable(), G4MaterialPropertiesTable::GetMaterialPropertyNames(), G4Material::GetName(), G4MaterialPropertiesTable::GetPropertyMap(), JustWarning, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), and PropertyVectorWrite().
Referenced by MaterialWrite().
void G4GDMLWriteMaterials::PWrite (xercesc::DOMElement * element, const G4double & P) protected
Definition at line 72 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 72 of file G4GDMLWriteMaterials.cc
References hep_pascal, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by MaterialWrite().
void G4GDMLWriteMaterials::TWrite (xercesc::DOMElement * element, const G4double & T) protected
Definition at line 81 of file G4GDMLWriteMaterials.cc.
View newest version in sPHENIX GitHub at line 81 of file G4GDMLWriteMaterials.cc
References kelvin, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by MaterialWrite().
Member Data Documentation
std::vector<const G4Element*> G4GDMLWriteMaterials::elementList protected
Definition at line 82 of file G4GDMLWriteMaterials.hh.
View newest version in sPHENIX GitHub at line 82 of file G4GDMLWriteMaterials.hh
Referenced by AddElement(), and MaterialsWrite().
std::vector<const G4Isotope*> G4GDMLWriteMaterials::isotopeList protected
Definition at line 81 of file G4GDMLWriteMaterials.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GDMLWriteMaterials.hh
Referenced by AddIsotope(), and MaterialsWrite().
std::vector<const G4Material*> G4GDMLWriteMaterials::materialList protected
Definition at line 83 of file G4GDMLWriteMaterials.hh.
View newest version in sPHENIX GitHub at line 83 of file G4GDMLWriteMaterials.hh
Referenced by AddMaterial(), and MaterialsWrite().
xercesc::DOMElement* G4GDMLWriteMaterials::materialsElement protected
Definition at line 85 of file G4GDMLWriteMaterials.hh.
View newest version in sPHENIX GitHub at line 85 of file G4GDMLWriteMaterials.hh
Referenced by ElementWrite(), IsotopeWrite(), MaterialsWrite(), and MaterialWrite().
std::vector<const G4PhysicsOrderedFreeVector*> G4GDMLWriteMaterials::propertyList protected
Definition at line 84 of file G4GDMLWriteMaterials.hh.
View newest version in sPHENIX GitHub at line 84 of file G4GDMLWriteMaterials.hh
Referenced by MaterialsWrite(), and PropertyVectorWrite().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteMaterials.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLWriteMaterials.cc