ECCE @ EIC Software: G4FTFBuilder Class Reference
G4FTFBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBuilder.hh>
Public Member Functions
G4FTFBuilder (const G4String &name="FTF", G4PreCompoundModel *p=0)
virtual ~G4FTFBuilder ()
Public Member Functions inherited from G4VHadronModelBuilder
G4VHadronModelBuilder (const G4String &name="")
virtual ~G4VHadronModelBuilder ()
G4HadronicInteraction * GetModel ()
const G4String & GetName () const
Protected Member Functions
virtual G4HadronicInteraction * BuildModel ()
Private Member Functions
G4FTFBuilder (G4FTFBuilder &)
G4FTFBuilder & operator= (const G4FTFBuilder &right)
Private Attributes
G4FTFModel * fStringModel
G4ExcitedStringDecay * fStringDecay
G4PreCompoundModel * fPreCompound
G4GeneratorPrecompoundInterface * fPrecoInterface
G4LundStringFragmentation * fLund
Detailed Description
Definition at line 49 of file G4FTFBuilder.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FTFBuilder.hh
Constructor & Destructor Documentation
G4FTFBuilder::G4FTFBuilder (const G4String & name = "FTF", G4PreCompoundModel * p = 0)
Definition at line 48 of file G4FTFBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4FTFBuilder.cc
G4FTFBuilder::~G4FTFBuilder () virtual
Definition at line 54 of file G4FTFBuilder.cc.
View newest version in sPHENIX GitHub at line 54 of file G4FTFBuilder.cc
References fLund, fStringDecay, and fStringModel.
G4FTFBuilder::G4FTFBuilder (G4FTFBuilder &) private
Member Function Documentation
G4HadronicInteraction * G4FTFBuilder::BuildModel () protected virtual
Implements G4VHadronModelBuilder.
Definition at line 61 of file G4FTFBuilder.cc.
View newest version in sPHENIX GitHub at line 61 of file G4FTFBuilder.cc
References fLund, fPrecoInterface, fPreCompound, fStringDecay, fStringModel, G4VHadronModelBuilder::GetName(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), and G4TheoFSGenerator::SetTransport().
G4FTFBuilder& G4FTFBuilder::operator= (const G4FTFBuilder & right) private
Member Data Documentation
G4LundStringFragmentation* G4FTFBuilder::fLund private
Definition at line 73 of file G4FTFBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFBuilder.hh
Referenced by BuildModel(), and ~G4FTFBuilder().
G4GeneratorPrecompoundInterface* G4FTFBuilder::fPrecoInterface private
Definition at line 72 of file G4FTFBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4FTFBuilder.hh
Referenced by BuildModel().
G4PreCompoundModel* G4FTFBuilder::fPreCompound private
Definition at line 70 of file G4FTFBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4FTFBuilder.hh
Referenced by BuildModel().
G4ExcitedStringDecay* G4FTFBuilder::fStringDecay private
Definition at line 69 of file G4FTFBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4FTFBuilder.hh
Referenced by BuildModel(), and ~G4FTFBuilder().
G4FTFModel* G4FTFBuilder::fStringModel private
Definition at line 68 of file G4FTFBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4FTFBuilder.hh
Referenced by BuildModel(), and ~G4FTFBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFBuilder.cc