ECCE @ EIC Software: ML2Run Class Reference
ML2Run Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Run.hh>
Public Member Functions
ML2Run (const std::vector< G4String > mfdName)
virtual ~ML2Run ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4int GetNumberOfHitsMap () const
G4THitsMap< G4double > * GetHitsMap (G4int i)
G4THitsMap< G4double > * GetHitsMap (const G4String &detName, const G4String &colName)
G4THitsMap< G4double > * GetHitsMap (const G4String &fullName)
void DumpAllScorer ()
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
std::vector< G4String > fCollName
std::vector< G4int > fCollID
std::vector< G4THitsMap
< G4double > * > fRunMap
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Definition at line 41 of file ML2Run.hh.
View newest version in sPHENIX GitHub at line 41 of file ML2Run.hh
Constructor & Destructor Documentation
ML2Run::ML2Run (const std::vector< G4String > mfdName)
Definition at line 35 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 35 of file ML2Run.cc
References fCollID, fCollName, G4SDManager::FindSensitiveDetector(), fRunMap, G4cout, G4endl, G4SDManager::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4MultiFunctionalDetector::GetNumberOfPrimitives(), G4MultiFunctionalDetector::GetPrimitive(), and G4SDManager::GetSDMpointer().
ML2Run::~ML2Run () virtual
Definition at line 80 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 80 of file ML2Run.cc
References fCollID, fCollName, and fRunMap.
Member Function Documentation
void ML2Run::DumpAllScorer ()
Definition at line 166 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 166 of file ML2Run.cc
References G4VTHitsMap< T, Map_t >::entries(), G4cout, G4endl, GetHitsMap(), G4VHitsCollection::GetName(), GetNumberOfHitsMap(), G4VHitsCollection::GetSDname(), and n.
Referenced by CML2RunAction::EndOfRunAction().
G4THitsMap<G4double>* ML2Run::GetHitsMap (G4int i) inline
Definition at line 62 of file ML2Run.hh.
View newest version in sPHENIX GitHub at line 62 of file ML2Run.hh
References fRunMap.
Referenced by DumpAllScorer(), CML2RunAction::EndOfRunAction(), and GetHitsMap().
G4THitsMap< G4double > * ML2Run::GetHitsMap (const G4String & detName, const G4String & colName)
Definition at line 147 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 147 of file ML2Run.cc
References GetHitsMap().
G4THitsMap< G4double > * ML2Run::GetHitsMap (const G4String & fullName)
Definition at line 156 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 156 of file ML2Run.cc
References fCollName, and fRunMap.
G4int ML2Run::GetNumberOfHitsMap () const inline
Definition at line 58 of file ML2Run.hh.
View newest version in sPHENIX GitHub at line 58 of file ML2Run.hh
References fRunMap.
Referenced by DumpAllScorer().
void ML2Run::Merge (const G4Run * aRun) virtual
Reimplemented from G4Run.
Definition at line 125 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 125 of file ML2Run.cc
References fCollID, fRunMap, and G4Run::Merge().
void ML2Run::RecordEvent (const G4Event * aEvent) virtual
Reimplemented from G4Run.
Definition at line 96 of file ML2Run.cc.
View newest version in sPHENIX GitHub at line 96 of file ML2Run.cc
References fCollID, fRunMap, G4cout, G4endl, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), and G4Run::numberOfEvent.
Member Data Documentation
std::vector<G4int> ML2Run::fCollID private
Definition at line 72 of file ML2Run.hh.
View newest version in sPHENIX GitHub at line 72 of file ML2Run.hh
Referenced by Merge(), ML2Run(), RecordEvent(), and ~ML2Run().
std::vector<G4String> ML2Run::fCollName private
Definition at line 71 of file ML2Run.hh.
View newest version in sPHENIX GitHub at line 71 of file ML2Run.hh
Referenced by GetHitsMap(), ML2Run(), and ~ML2Run().
std::vector<G4THitsMap<G4double>*> ML2Run::fRunMap private
Definition at line 73 of file ML2Run.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2Run.hh
Referenced by GetHitsMap(), GetNumberOfHitsMap(), Merge(), ML2Run(), RecordEvent(), and ~ML2Run().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Run.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Run.cc