ECCE @ EIC Software: G4ParameterisedNavigation Class Reference
G4ParameterisedNavigation Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4ParameterisedNavigation.hh>
Public Member Functions
G4ParameterisedNavigation ()
~G4ParameterisedNavigation ()
G4SmartVoxelNode * ParamVoxelLocate (G4SmartVoxelHeader *pHead, const G4ThreeVector &localPoint)
G4bool LevelLocate (G4NavigationHistory &history, const G4VPhysicalVolume *blockedVol, const G4int blockedNum, const G4ThreeVector &globalPoint, const G4ThreeVector *globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector &localPoint)
G4double ComputeStep (const G4ThreeVector &globalPoint, const G4ThreeVector &globalDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo)
G4double ComputeSafety (const G4ThreeVector &localPoint, const G4NavigationHistory &history, const G4double pProposedMaxLength=DBL_MAX)
Public Member Functions inherited from G4VoxelNavigation
G4VoxelNavigation ()
virtual ~G4VoxelNavigation ()
G4SmartVoxelNode * VoxelLocate (G4SmartVoxelHeader *pHead, const G4ThreeVector &localPoint)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void CheckMode (G4bool mode)
void EnableBestSafety (G4bool flag=false)
Private Member Functions
G4double ComputeVoxelSafety (const G4ThreeVector &localPoint, const EAxis pAxis) const
G4bool LocateNextVoxel (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double currentStep, const EAxis pAxis)
G4VSolid * IdentifyAndPlaceSolid (G4int num, G4VPhysicalVolume *apparentPhys, G4VPVParameterisation *curParam)
G4VPhysicalVolume * CreateVolumeWithParent (G4VPhysicalVolume *curPhysical, const G4NavigationHistory &hist)
Private Attributes
EAxis fVoxelAxis = kUndefined
G4int fVoxelNoSlices = 0
G4double fVoxelSliceWidth = 0.0
size_t fVoxelNodeNo = 0
G4SmartVoxelHeader * fVoxelHeader = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4VoxelNavigation
G4double ComputeVoxelSafety (const G4ThreeVector &localPoint) const
G4bool LocateNextVoxel (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double currentStep)
G4SmartVoxelNode * VoxelLocateLight (G4SmartVoxelHeader *pHead, const G4ThreeVector &localPoint) const
Protected Attributes inherited from G4VoxelNavigation
G4BlockingList fBList
G4int fVoxelDepth = -1
std::vector< EAxis > fVoxelAxisStack
std::vector< G4int > fVoxelNoSlicesStack
std::vector< G4double > fVoxelSliceWidthStack
std::vector< G4int > fVoxelNodeNoStack
std::vector< G4SmartVoxelHeader * > fVoxelHeaderStack
G4SmartVoxelNode * fVoxelNode = nullptr
G4VoxelSafety * fpVoxelSafety = nullptr
G4double fHalfTolerance
G4bool fCheck = false
G4bool fBestSafety = false
G4NavigationLogger * fLogger
Detailed Description
Definition at line 54 of file G4ParameterisedNavigation.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParameterisedNavigation.hh
Constructor & Destructor Documentation
G4ParameterisedNavigation::G4ParameterisedNavigation ()
Definition at line 56 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParameterisedNavigation.cc
G4ParameterisedNavigation::~G4ParameterisedNavigation ()
Definition at line 64 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ParameterisedNavigation.cc
Member Function Documentation
G4double G4ParameterisedNavigation::ComputeSafety (const G4ThreeVector & localPoint, const G4NavigationHistory & history, const G4double pProposedMaxLength = DBL_MAX) virtual
Reimplemented from G4VoxelNavigation.
Definition at line 396 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 396 of file G4ParameterisedNavigation.cc
References ComputeVoxelSafety(), G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), fVoxelAxis, fVoxelHeader, G4VoxelNavigation::fVoxelNode, fVoxelNodeNo, fVoxelSliceWidth, G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4SmartVoxelHeader::GetMinExtent(), G4SmartVoxelNode::GetNoContained(), G4SmartVoxelProxy::GetNode(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetReplicationData(), G4VPhysicalVolume::GetRotation(), G4SmartVoxelHeader::GetSlice(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopVolume(), G4VPhysicalVolume::GetTranslation(), G4SmartVoxelNode::GetVolume(), IdentifyAndPlaceSolid(), G4AffineTransform::Invert(), kUndefined, offset, and width.
Referenced by G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), and G4ITNavigator2::ComputeSafety().
G4double G4ParameterisedNavigation::ComputeStep (const G4ThreeVector & globalPoint, const G4ThreeVector & globalDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo) virtual
Reimplemented from G4VoxelNavigation.
Definition at line 73 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ParameterisedNavigation.cc
References G4BlockingList::BlockVolume(), G4NavigationLogger::CheckAndReportBadNormal(), ComputeVoxelSafety(), DBL_MAX, G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), CLHEP::Hep3Vector::dot(), G4VSolid::DumpInfo(), G4BlockingList::Enlarge(), FatalException, G4VoxelNavigation::fBList, G4VoxelNavigation::fCheck, G4VoxelNavigation::fLogger, G4VoxelNavigation::fVoxelNode, G4cout, G4endl, G4Exception(), G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4SmartVoxelNode::GetNoContained(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetReplicationData(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4VSolid::GetTolerance(), G4NavigationHistory::GetTopVolume(), G4VPhysicalVolume::GetTranslation(), G4SmartVoxelNode::GetVolume(), IdentifyAndPlaceSolid(), G4VSolid::Inside(), CLHEP::HepRotation::inverse(), G4AffineTransform::Invert(), G4BlockingList::IsBlocked(), JustWarning, kInfinity, kInside, kMinExitingNormalCosine, kOutside, kSurface, LocateNextVoxel(), message(), offset, G4NavigationLogger::ReportOutsideMother(), G4BlockingList::Reset(), and width.
Referenced by G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), and G4ITNavigator2::ComputeStep().
G4double G4ParameterisedNavigation::ComputeVoxelSafety (const G4ThreeVector & localPoint, const EAxis pAxis) const private
Definition at line 493 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 493 of file G4ParameterisedNavigation.cc
References G4VoxelNavigation::ComputeVoxelSafety(), fVoxelAxis, fVoxelHeader, G4VoxelNavigation::fVoxelNode, fVoxelNodeNo, fVoxelSliceWidth, G4SmartVoxelNode::GetMaxEquivalentSliceNo(), G4SmartVoxelNode::GetMinEquivalentSliceNo(), G4SmartVoxelHeader::GetMinExtent(), kUndefined, and min.
Referenced by ComputeSafety(), and ComputeStep().
G4VPhysicalVolume* G4ParameterisedNavigation::CreateVolumeWithParent (G4VPhysicalVolume * curPhysical, const G4NavigationHistory & hist) private
G4VSolid* G4ParameterisedNavigation::IdentifyAndPlaceSolid (G4int num, G4VPhysicalVolume * apparentPhys, G4VPVParameterisation * curParam) inline private
Referenced by ComputeSafety(), ComputeStep(), and LevelLocate().
G4bool G4ParameterisedNavigation::LevelLocate (G4NavigationHistory & history, const G4VPhysicalVolume * blockedVol, const G4int blockedNum, const G4ThreeVector & globalPoint, const G4ThreeVector * globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector & localPoint) virtual
Reimplemented from G4VoxelNavigation.
Definition at line 602 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 602 of file G4ParameterisedNavigation.cc
References G4NavigationHistory::BackLevel(), G4AuxiliaryNavServices::CheckPointOnSurface(), G4VPVParameterisation::ComputeMaterial(), G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4SmartVoxelNode::GetNoContained(), G4VPhysicalVolume::GetParameterisation(), G4NavigationHistory::GetTopTransform(), G4NavigationHistory::GetTopVolume(), G4SmartVoxelNode::GetVolume(), G4LogicalVolume::GetVoxelHeader(), IdentifyAndPlaceSolid(), kParameterised, G4NavigationHistory::NewLevel(), ParamVoxelLocate(), G4VPhysicalVolume::SetCopyNo(), G4LogicalVolume::SetSolid(), G4AffineTransform::TransformPoint(), and G4LogicalVolume::UpdateMaterial().
Referenced by G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4ITNavigator2::LocateGlobalPointAndSetup().
G4bool G4ParameterisedNavigation::LocateNextVoxel (const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4double currentStep, const EAxis pAxis) private
Definition at line 541 of file G4ParameterisedNavigation.cc.
View newest version in sPHENIX GitHub at line 541 of file G4ParameterisedNavigation.cc
References fVoxelAxis, fVoxelHeader, G4VoxelNavigation::fVoxelNode, fVoxelNodeNo, fVoxelSliceWidth, G4SmartVoxelNode::GetMaxEquivalentSliceNo(), G4SmartVoxelNode::GetMinEquivalentSliceNo(), G4SmartVoxelHeader::GetMinExtent(), G4SmartVoxelProxy::GetNode(), G4SmartVoxelHeader::GetNoSlices(), G4SmartVoxelHeader::GetSlice(), kUndefined, and G4VoxelNavigation::LocateNextVoxel().
Referenced by ComputeStep().
G4SmartVoxelNode* G4ParameterisedNavigation::ParamVoxelLocate (G4SmartVoxelHeader * pHead, const G4ThreeVector & localPoint) inline
Referenced by LevelLocate(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), and G4ITNavigator2::LocateGlobalPointWithinVolume().
Member Data Documentation
EAxis G4ParameterisedNavigation::fVoxelAxis = kUndefined private
Definition at line 114 of file G4ParameterisedNavigation.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParameterisedNavigation.hh
Referenced by ComputeSafety(), ComputeVoxelSafety(), and LocateNextVoxel().
G4SmartVoxelHeader* G4ParameterisedNavigation::fVoxelHeader = nullptr private
Definition at line 118 of file G4ParameterisedNavigation.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParameterisedNavigation.hh
Referenced by ComputeSafety(), ComputeVoxelSafety(), and LocateNextVoxel().
size_t G4ParameterisedNavigation::fVoxelNodeNo = 0 private
Definition at line 117 of file G4ParameterisedNavigation.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParameterisedNavigation.hh
Referenced by ComputeSafety(), ComputeVoxelSafety(), and LocateNextVoxel().
G4int G4ParameterisedNavigation::fVoxelNoSlices = 0 private
Definition at line 115 of file G4ParameterisedNavigation.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParameterisedNavigation.hh
G4double G4ParameterisedNavigation::fVoxelSliceWidth = 0.0 private
Definition at line 116 of file G4ParameterisedNavigation.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParameterisedNavigation.hh
Referenced by ComputeSafety(), ComputeVoxelSafety(), and LocateNextVoxel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4ParameterisedNavigation.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4ParameterisedNavigation.cc