ECCE @ EIC Software: G4INCL::InterpolationTable Class Reference
G4INCL::InterpolationTable Class Reference
Class for interpolating the of a 1-dimensional function.
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLInterpolationTable.hh>
Public Member Functions
InterpolationTable (std::vector< G4double > const &x, std::vector< G4double > const &y)
virtual ~InterpolationTable ()
unsigned int getNumberOfNodes () const
std::vector< G4double > getNodeAbscissae () const
std::vector< G4double > getNodeValues () const
G4double operator() (const G4double x) const
Compute the value of the function.
std::string print () const
Public Member Functions inherited from G4INCL::IFunction1D
IFunction1D ()
IFunction1D (const G4double x0, const G4double x1)
virtual ~IFunction1D ()
virtual G4double getXMinimum () const
Return the minimum allowed value of the independent variable.
virtual G4double getXMaximum () const
Return the maximum allowed value of the independent variable.
virtual G4double integrate (const G4double x0, const G4double x1, const G4double step=-1.) const
Integrate the function between two values.
IFunction1D * primitive () const
Return a pointer to the (numerical) primitive to this function.
InterpolationTable * inverseCDFTable (ManipulatorFunc fWrap=0, const G4int nNodes=60) const
Return a pointer to the inverse of the CDF of this function.
Protected Member Functions
InterpolationTable ()
void initDerivatives ()
Initialise the values of the node derivatives.
Protected Attributes
std::vector< InterpolationNode > nodes
Interpolating nodes.
Protected Attributes inherited from G4INCL::IFunction1D
G4double xMin
Minimum value of the independent variable.
G4double xMax
Maximum value of the independent variable.
Additional Inherited Members
Public Types inherited from G4INCL::IFunction1D
typedef G4double(*const ManipulatorFunc)(const G4double)
Typedef to simplify the syntax of inverseCDFTable.
Detailed Description
Class for interpolating the of a 1-dimensional function.
Definition at line 106 of file G4INCLInterpolationTable.hh.
View newest version in sPHENIX GitHub at line 106 of file G4INCLInterpolationTable.hh
Constructor & Destructor Documentation
G4INCL::InterpolationTable::InterpolationTable (std::vector< G4double > const & x, std::vector< G4double > const & y)
Definition at line 54 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 54 of file G4INCLInterpolationTable.cc
References initDerivatives(), and nodes.
virtual G4INCL::InterpolationTable::~InterpolationTable () inline virtual
Definition at line 109 of file G4INCLInterpolationTable.hh.
View newest version in sPHENIX GitHub at line 109 of file G4INCLInterpolationTable.hh
G4INCL::InterpolationTable::InterpolationTable () protected
Definition at line 52 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 52 of file G4INCLInterpolationTable.cc
Member Function Documentation
std::vector< G4double > G4INCL::InterpolationTable::getNodeAbscissae () const
Definition at line 67 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 67 of file G4INCLInterpolationTable.cc
References G4INCL::InterpolationNode::getX(), nodes, Acts::Test::transform, and x.
std::vector< G4double > G4INCL::InterpolationTable::getNodeValues () const
Definition at line 74 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 74 of file G4INCLInterpolationTable.cc
References G4INCL::InterpolationNode::getY(), nodes, Acts::Test::transform, and y.
unsigned int G4INCL::InterpolationTable::getNumberOfNodes () const inline
Definition at line 111 of file G4INCLInterpolationTable.hh.
View newest version in sPHENIX GitHub at line 111 of file G4INCLInterpolationTable.hh
References nodes.
void G4INCL::InterpolationTable::initDerivatives () protected
Initialise the values of the node derivatives.
Definition at line 81 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 81 of file G4INCLInterpolationTable.cc
References nodes.
Referenced by InterpolationTable(), and G4INCL::InvFInterpolationTable::InvFInterpolationTable().
G4double G4INCL::InterpolationTable::operator() (const G4double x) const virtual
Compute the value of the function.
Implements G4INCL::IFunction1D.
Definition at line 91 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 91 of file G4INCLInterpolationTable.cc
References dx, and nodes.
std::string G4INCL::InterpolationTable::print () const
Definition at line 108 of file G4INCLInterpolationTable.cc.
View newest version in sPHENIX GitHub at line 108 of file G4INCLInterpolationTable.cc
References e, message(), n, and nodes.
Referenced by G4INCL::NuclearDensityFactory::createPCDFTable(), G4INCL::NuclearDensityFactory::createRCDFTable(), and G4INCL::NuclearDensityFactory::createRPCorrelationTable().
Member Data Documentation
std::vector<InterpolationNode> G4INCL::InterpolationTable::nodes protected
Interpolating nodes.
Definition at line 128 of file G4INCLInterpolationTable.hh.
View newest version in sPHENIX GitHub at line 128 of file G4INCLInterpolationTable.hh
Referenced by getNodeAbscissae(), getNodeValues(), getNumberOfNodes(), initDerivatives(), InterpolationTable(), G4INCL::InvFInterpolationTable::InvFInterpolationTable(), operator()(), and print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLInterpolationTable.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLInterpolationTable.cc