ECCE @ EIC Software: G4VTwistSurface::Boundary Class Reference
G4VTwistSurface::Boundary Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh>
Public Member Functions
Boundary ()
virtual ~Boundary ()
void SetFields (const G4int &areacode, const G4ThreeVector &d, const G4ThreeVector &x0, const G4int &boundarytype)
G4bool IsEmpty () const
G4bool GetBoundaryParameters (const G4int &areacode, G4ThreeVector &d, G4ThreeVector &x0, G4int &boundarytype) const
Private Attributes
G4int fBoundaryAcode
G4ThreeVector fBoundaryDirection
G4ThreeVector fBoundaryX0
G4int fBoundaryType
Detailed Description
Definition at line 283 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 283 of file G4VTwistSurface.hh
Constructor & Destructor Documentation
G4VTwistSurface::Boundary::Boundary ()
Definition at line 1281 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1281 of file G4VTwistSurface.cc
G4VTwistSurface::Boundary::~Boundary () virtual
Definition at line 1289 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1289 of file G4VTwistSurface.cc
Member Function Documentation
G4bool G4VTwistSurface::Boundary::GetBoundaryParameters (const G4int & areacode, G4ThreeVector & d, G4ThreeVector & x0, G4int & boundarytype) const
Definition at line 1321 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1321 of file G4VTwistSurface.cc
References FatalException, G4endl, G4Exception(), message(), G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, and G4VTwistSurface::sSizeMask.
G4bool G4VTwistSurface::Boundary::IsEmpty () const
Definition at line 1311 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1311 of file G4VTwistSurface.cc
void G4VTwistSurface::Boundary::SetFields (const G4int & areacode, const G4ThreeVector & d, const G4ThreeVector & x0, const G4int & boundarytype)
Definition at line 1297 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1297 of file G4VTwistSurface.cc
References d.
Referenced by G4VTwistSurface::SetBoundary().
Member Data Documentation
G4int G4VTwistSurface::Boundary::fBoundaryAcode private
Definition at line 302 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 302 of file G4VTwistSurface.hh
G4ThreeVector G4VTwistSurface::Boundary::fBoundaryDirection private
Definition at line 303 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 303 of file G4VTwistSurface.hh
G4int G4VTwistSurface::Boundary::fBoundaryType private
Definition at line 305 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 305 of file G4VTwistSurface.hh
G4ThreeVector G4VTwistSurface::Boundary::fBoundaryX0 private
Definition at line 304 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 304 of file G4VTwistSurface.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4VTwistSurface.cc