ECCE @ EIC Software: G4ChannelingECHARM Class Reference
G4ChannelingECHARM Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingECHARM.hh>
Public Member Functions
G4ChannelingECHARM (const G4String &, G4double)
~G4ChannelingECHARM ()
G4double GetEC (G4ThreeVector &)
virtual void ReadFromECHARM (const G4String &, G4double)
G4double GetMax ()
G4double GetMin ()
G4double GetMaxMin ()
G4double GetIntSp (G4int index)
Private Attributes
G4PhysicsVector * fVectorEC
G4Physics2DVector * fVectorEC2D
G4double fDistances [3]
G4int fPoints [3]
G4double fMaximum
G4double fMinimum
Detailed Description
Definition at line 34 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 34 of file G4ChannelingECHARM.hh
Constructor & Destructor Documentation
G4ChannelingECHARM::G4ChannelingECHARM (const G4String & fileName, G4double vConversion)
Definition at line 32 of file G4ChannelingECHARM.cc.
View newest version in sPHENIX GitHub at line 32 of file G4ChannelingECHARM.cc
G4ChannelingECHARM::~G4ChannelingECHARM ()
Definition at line 49 of file G4ChannelingECHARM.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ChannelingECHARM.cc
References fVectorEC, and fVectorEC2D.
Member Function Documentation
G4double G4ChannelingECHARM::GetEC (G4ThreeVector & vPosition)
Definition at line 56 of file G4ChannelingECHARM.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ChannelingECHARM.cc
References fDistances, fPoints, fVectorEC, fVectorEC2D, int(), G4Physics2DVector::Value(), G4PhysicsVector::Value(), CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4Channeling::UpdateParameters().
G4double G4ChannelingECHARM::GetIntSp (G4int index) inline
Definition at line 49 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ChannelingECHARM.hh
References fDistances.
Referenced by G4Channeling::UpdateParameters().
G4double G4ChannelingECHARM::GetMax () inline
Definition at line 45 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ChannelingECHARM.hh
References fMaximum.
G4double G4ChannelingECHARM::GetMaxMin () inline
Definition at line 47 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ChannelingECHARM.hh
References fMaximum, and fMinimum.
G4double G4ChannelingECHARM::GetMin () inline
Definition at line 46 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ChannelingECHARM.hh
References fMinimum.
void G4ChannelingECHARM::ReadFromECHARM (const G4String & filename, G4double vConversion) virtual
Definition at line 81 of file G4ChannelingECHARM.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ChannelingECHARM.cc
References DBL_MAX, FatalException, fDistances, fMaximum, fMinimum, fPoints, fVectorEC, fVectorEC2D, G4cout, G4endl, G4Exception(), CLHEP::meter, G4Physics2DVector::PutValue(), G4PhysicsVector::PutValue(), G4Physics2DVector::PutX(), and G4Physics2DVector::PutY().
Member Data Documentation
G4double G4ChannelingECHARM::fDistances[3] private
Definition at line 55 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ChannelingECHARM.hh
Referenced by GetEC(), GetIntSp(), and ReadFromECHARM().
G4double G4ChannelingECHARM::fMaximum private
Definition at line 58 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ChannelingECHARM.hh
Referenced by GetMax(), GetMaxMin(), and ReadFromECHARM().
G4double G4ChannelingECHARM::fMinimum private
Definition at line 59 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ChannelingECHARM.hh
Referenced by GetMaxMin(), GetMin(), and ReadFromECHARM().
G4int G4ChannelingECHARM::fPoints[3] private
Definition at line 56 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ChannelingECHARM.hh
Referenced by GetEC(), and ReadFromECHARM().
G4PhysicsVector* G4ChannelingECHARM::fVectorEC private
Definition at line 49 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ChannelingECHARM.hh
Referenced by GetEC(), ReadFromECHARM(), and ~G4ChannelingECHARM().
G4Physics2DVector* G4ChannelingECHARM::fVectorEC2D private
Definition at line 53 of file G4ChannelingECHARM.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ChannelingECHARM.hh
Referenced by GetEC(), ReadFromECHARM(), and ~G4ChannelingECHARM().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingECHARM.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/src/G4ChannelingECHARM.cc