ECCE @ EIC Software: G4PionBuilder Class Reference
G4PionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4PionBuilder.hh>
Public Member Functions
G4PionBuilder ()
virtual ~G4PionBuilder ()
virtual void Build () finaloverride
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4PionPlusInelasticProcess * thePionPlusInelastic
G4PionMinusInelasticProcess * thePionMinusInelastic
std::vector< G4VPionBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 48 of file G4PionBuilder.hh.
View newest version in sPHENIX GitHub at line 48 of file G4PionBuilder.hh
Constructor & Destructor Documentation
G4PionBuilder::G4PionBuilder ()
Definition at line 45 of file G4PionBuilder.cc.
View newest version in sPHENIX GitHub at line 45 of file G4PionBuilder.cc
References thePionMinusInelastic, and thePionPlusInelastic.
virtual G4PionBuilder::~G4PionBuilder () inline virtual
Definition at line 52 of file G4PionBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4PionBuilder.hh
Member Function Documentation
void G4PionBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 52 of file G4PionBuilder.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PionBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4ParticleDefinition::GetProcessManager(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), theModelCollections, thePionMinusInelastic, thePionPlusInelastic, and wasActivated.
void G4PionBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 71 of file G4PionBuilder.cc.
View newest version in sPHENIX GitHub at line 71 of file G4PionBuilder.cc
References G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Member Data Documentation
std::vector<G4VPionBuilder *> G4PionBuilder::theModelCollections private
Definition at line 60 of file G4PionBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4PionBuilder.hh
Referenced by Build(), and RegisterMe().
G4PionMinusInelasticProcess* G4PionBuilder::thePionMinusInelastic private
Definition at line 59 of file G4PionBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PionBuilder.hh
Referenced by Build(), and G4PionBuilder().
G4PionPlusInelasticProcess* G4PionBuilder::thePionPlusInelastic private
Definition at line 58 of file G4PionBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PionBuilder.hh
Referenced by Build(), and G4PionBuilder().
G4bool G4PionBuilder::wasActivated private
Definition at line 62 of file G4PionBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PionBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4PionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4PionBuilder.cc