ECCE @ EIC Software: G4Evaporation Class Reference
G4Evaporation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4Evaporation.hh>
Public Member Functions
G4Evaporation (G4VEvaporationChannel *photoEvaporation=nullptr)
virtual ~G4Evaporation ()
virtual void InitialiseChannels () final
virtual void BreakFragment (G4FragmentVector *, G4Fragment *theNucleus) final
void SetDefaultChannel ()
void SetGEMChannel ()
void SetGEMVIChannel ()
void SetCombinedChannel ()
Public Member Functions inherited from G4VEvaporation
G4VEvaporation ()
virtual ~G4VEvaporation ()
virtual void SetPhotonEvaporation (G4VEvaporationChannel *ptr)
void SetFermiBreakUp (G4VFermiBreakUp *ptr)
G4VFermiBreakUp * GetFermiBreakUp () const
G4VEvaporationChannel * GetPhotonEvaporation ()
G4VEvaporationChannel * GetFissionChannel ()
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
size_t GetNumberOfChannels () const
Private Member Functions
void InitialiseChannelFactory ()
G4Evaporation (const G4Evaporation &right)
const G4Evaporation & operator= (const G4Evaporation &right)
G4bool operator== (const G4Evaporation &right) const
G4bool operator!= (const G4Evaporation &right) const
Private Attributes
G4int fVerbose
size_t nChannels
G4double minExcitation
G4NistManager * nist
G4IonTable * theTableOfIons
G4NuclearLevelData * fLevelData
G4UnstableFragmentBreakUp * unstableBreakUp
G4bool isInitialised
G4DeexChannelType channelType
std::vector< G4double > probabilities
Additional Inherited Members
Protected Member Functions inherited from G4VEvaporation
void CleanChannels ()
Protected Attributes inherited from G4VEvaporation
G4VEvaporationChannel * thePhotonEvaporation
G4VFermiBreakUp * theFBU
G4int OPTxs
G4bool useSICB
std::vector
< G4VEvaporationChannel * > * theChannels
G4VEvaporationFactory * theChannelFactory
Detailed Description
Definition at line 61 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 61 of file G4Evaporation.hh
Constructor & Destructor Documentation
G4Evaporation::G4Evaporation (G4VEvaporationChannel * photoEvaporation = nullptr) explicit
Definition at line 66 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 66 of file G4Evaporation.cc
References fDummy, fLevelData, G4NuclearLevelData::GetInstance(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4NistManager::Instance(), nist, G4VEvaporation::SetPhotonEvaporation(), G4VEvaporation::theChannelFactory, theTableOfIons, and unstableBreakUp.
G4Evaporation::~G4Evaporation () virtual
Definition at line 87 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 87 of file G4Evaporation.cc
References unstableBreakUp.
G4Evaporation::G4Evaporation (const G4Evaporation & right) private
Member Function Documentation
void G4Evaporation::BreakFragment (G4FragmentVector * theResult, G4Fragment * theNucleus) final virtual
Reimplemented from G4VEvaporation.
Definition at line 179 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 179 of file G4Evaporation.cc
References A(), G4UnstableFragmentBreakUp::BreakUpChain(), e, fLevelData, fVerbose, G4cout, G4endl, G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NistManager::GetIsotopeAbundance(), G4NuclearLevelData::GetLevelManager(), G4Fragment::GetZ_asInt(), InitialiseChannels(), G4VFermiBreakUp::IsApplicable(), isInitialised, minExcitation, nChannels, nist, probabilities, G4VEvaporation::theFBU, unstableBreakUp, and Z.
void G4Evaporation::InitialiseChannelFactory () private
Definition at line 110 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 110 of file G4Evaporation.cc
References fVerbose, G4cout, G4endl, G4VEvaporationFactory::GetChannel(), nChannels, G4VEvaporation::OPTxs, probabilities, G4VEvaporation::theChannelFactory, and G4VEvaporation::theChannels.
Referenced by SetCombinedChannel(), SetDefaultChannel(), SetGEMChannel(), and SetGEMVIChannel().
void G4Evaporation::InitialiseChannels () final virtual
Reimplemented from G4VEvaporation.
Definition at line 92 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 92 of file G4Evaporation.cc
References fCombined, fEvaporation, fGEM, fGEMVI, fLevelData, fVerbose, G4DeexPrecoParameters::GetDeexChannelsType(), G4DeexPrecoParameters::GetMinExcitation(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::GetVerbose(), isInitialised, minExcitation, SetCombinedChannel(), SetDefaultChannel(), SetGEMChannel(), SetGEMVIChannel(), G4UnstableFragmentBreakUp::SetVerbose(), and unstableBreakUp.
Referenced by BreakFragment(), and G4ExcitationHandler::SetDeexChannelsType().
G4bool G4Evaporation::operator!= (const G4Evaporation & right) const private
const G4Evaporation& G4Evaporation::operator= (const G4Evaporation & right) private
G4bool G4Evaporation::operator== (const G4Evaporation & right) const private
void G4Evaporation::SetCombinedChannel ()
Definition at line 165 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 165 of file G4Evaporation.cc
References G4VEvaporation::CleanChannels(), fCombined, InitialiseChannelFactory(), G4VEvaporation::theChannelFactory, and G4VEvaporation::thePhotonEvaporation.
Referenced by InitialiseChannels(), and G4ExcitationHandler::SetDeexChannelsType().
void G4Evaporation::SetDefaultChannel ()
Definition at line 126 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 126 of file G4Evaporation.cc
References G4VEvaporation::CleanChannels(), fEvaporation, InitialiseChannelFactory(), G4VEvaporation::theChannelFactory, and G4VEvaporation::thePhotonEvaporation.
Referenced by InitialiseChannels(), G4ExcitationHandler::SetDeexChannelsType(), and G4QMDReaction::setEvaporationCh().
void G4Evaporation::SetGEMChannel ()
Definition at line 139 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 139 of file G4Evaporation.cc
References G4VEvaporation::CleanChannels(), fCombined, fGEM, InitialiseChannelFactory(), G4VEvaporation::theChannelFactory, and G4VEvaporation::thePhotonEvaporation.
Referenced by InitialiseChannels(), G4ExcitationHandler::SetDeexChannelsType(), and G4QMDReaction::setEvaporationCh().
void G4Evaporation::SetGEMVIChannel ()
Definition at line 152 of file G4Evaporation.cc.
View newest version in sPHENIX GitHub at line 152 of file G4Evaporation.cc
References G4VEvaporation::CleanChannels(), fGEMVI, InitialiseChannelFactory(), G4VEvaporation::theChannelFactory, and G4VEvaporation::thePhotonEvaporation.
Referenced by InitialiseChannels(), and G4ExcitationHandler::SetDeexChannelsType().
Member Data Documentation
G4DeexChannelType G4Evaporation::channelType private
Definition at line 99 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 99 of file G4Evaporation.hh
G4NuclearLevelData* G4Evaporation::fLevelData private
Definition at line 95 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Evaporation.hh
Referenced by BreakFragment(), G4Evaporation(), and InitialiseChannels().
G4int G4Evaporation::fVerbose private
Definition at line 90 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4Evaporation.hh
Referenced by BreakFragment(), InitialiseChannelFactory(), and InitialiseChannels().
G4bool G4Evaporation::isInitialised private
Definition at line 97 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 97 of file G4Evaporation.hh
Referenced by BreakFragment(), and InitialiseChannels().
G4double G4Evaporation::minExcitation private
Definition at line 92 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 92 of file G4Evaporation.hh
Referenced by BreakFragment(), and InitialiseChannels().
size_t G4Evaporation::nChannels private
Definition at line 91 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 91 of file G4Evaporation.hh
Referenced by BreakFragment(), and InitialiseChannelFactory().
G4NistManager* G4Evaporation::nist private
Definition at line 93 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 93 of file G4Evaporation.hh
Referenced by BreakFragment(), and G4Evaporation().
std::vector<G4double> G4Evaporation::probabilities private
Definition at line 101 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Evaporation.hh
Referenced by BreakFragment(), and InitialiseChannelFactory().
G4IonTable* G4Evaporation::theTableOfIons private
Definition at line 94 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4Evaporation.hh
Referenced by G4Evaporation().
G4UnstableFragmentBreakUp* G4Evaporation::unstableBreakUp private
Definition at line 96 of file G4Evaporation.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Evaporation.hh
Referenced by BreakFragment(), G4Evaporation(), InitialiseChannels(), and ~G4Evaporation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4Evaporation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4Evaporation.cc