ECCE @ EIC Software: GammaRayTelCalorimeterSD Class Reference
GammaRayTelCalorimeterSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelCalorimeterSD.hh>
Public Member Functions
GammaRayTelCalorimeterSD (G4String)
~GammaRayTelCalorimeterSD ()
void Initialize (G4HCofThisEvent *)
G4bool ProcessHits (G4Step *astep, G4TouchableHistory *ROHist)
void EndOfEvent (G4HCofThisEvent *)
void clear ()
void DrawAll ()
void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
GammaRayTelCalorimeterHitsCollection * CalorimeterCollection
GammaRayTelDetectorConstruction * Detector
G4int * ChitXID
G4int * ChitYID
G4int NbOfCALLayers
G4int NbOfCALBars
G4int NbOfCALChannels
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 50 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 50 of file GammaRayTelCalorimeterSD.hh
Constructor & Destructor Documentation
GammaRayTelCalorimeterSD::GammaRayTelCalorimeterSD (G4String name)
Definition at line 51 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 51 of file GammaRayTelCalorimeterSD.cc
References ChitXID, ChitYID, G4VSensitiveDetector::collectionName, Detector, GammaRayTelDetectorConstruction::GetNbOfCALBars(), GammaRayTelDetectorConstruction::GetNbOfCALLayers(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4CollectionNameVector::insert(), NbOfCALBars, NbOfCALChannels, and NbOfCALLayers.
GammaRayTelCalorimeterSD::~GammaRayTelCalorimeterSD ()
Definition at line 72 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 72 of file GammaRayTelCalorimeterSD.cc
References ChitXID, and ChitYID.
Member Function Documentation
void GammaRayTelCalorimeterSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 192 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 192 of file GammaRayTelCalorimeterSD.cc
void GammaRayTelCalorimeterSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 197 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 197 of file GammaRayTelCalorimeterSD.cc
void GammaRayTelCalorimeterSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 172 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 172 of file GammaRayTelCalorimeterSD.cc
References G4HCofThisEvent::AddHitsCollection(), CalorimeterCollection, ChitXID, ChitYID, G4VSensitiveDetector::collectionName, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), and NbOfCALChannels.
void GammaRayTelCalorimeterSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 80 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 80 of file GammaRayTelCalorimeterSD.cc
References CalorimeterCollection, ChitXID, ChitYID, G4VSensitiveDetector::collectionName, NbOfCALChannels, and G4VSensitiveDetector::SensitiveDetectorName.
void GammaRayTelCalorimeterSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 202 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 202 of file GammaRayTelCalorimeterSD.cc
G4bool GammaRayTelCalorimeterSD::ProcessHits (G4Step * astep, G4TouchableHistory * ROHist) virtual
Implements G4VSensitiveDetector.
Definition at line 93 of file GammaRayTelCalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 93 of file GammaRayTelCalorimeterSD.cc
References GammaRayTelCalorimeterHit::AddEnergy(), CalorimeterCollection, ChitXID, ChitYID, edep, G4VPhysicalVolume::GetCopyNo(), G4VPhysicalVolume::GetName(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4TouchableHistory::GetVolume(), G4THitsCollection< T >::insert(), NbOfCALBars, GammaRayTelCalorimeterHit::SetCALBarNumber(), GammaRayTelCalorimeterHit::SetCALPlaneNumber(), GammaRayTelCalorimeterHit::SetCALType(), and GammaRayTelCalorimeterHit::SetPos().
Member Data Documentation
GammaRayTelCalorimeterHitsCollection* GammaRayTelCalorimeterSD::CalorimeterCollection private
Definition at line 66 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 66 of file GammaRayTelCalorimeterSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
G4int* GammaRayTelCalorimeterSD::ChitXID private
Definition at line 69 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 69 of file GammaRayTelCalorimeterSD.hh
Referenced by EndOfEvent(), GammaRayTelCalorimeterSD(), Initialize(), ProcessHits(), and ~GammaRayTelCalorimeterSD().
G4int* GammaRayTelCalorimeterSD::ChitYID private
Definition at line 70 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 70 of file GammaRayTelCalorimeterSD.hh
Referenced by EndOfEvent(), GammaRayTelCalorimeterSD(), Initialize(), ProcessHits(), and ~GammaRayTelCalorimeterSD().
GammaRayTelDetectorConstruction* GammaRayTelCalorimeterSD::Detector private
Definition at line 67 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 67 of file GammaRayTelCalorimeterSD.hh
Referenced by GammaRayTelCalorimeterSD().
G4int GammaRayTelCalorimeterSD::NbOfCALBars private
Definition at line 73 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 73 of file GammaRayTelCalorimeterSD.hh
Referenced by GammaRayTelCalorimeterSD(), and ProcessHits().
G4int GammaRayTelCalorimeterSD::NbOfCALChannels private
Definition at line 74 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelCalorimeterSD.hh
Referenced by EndOfEvent(), GammaRayTelCalorimeterSD(), and Initialize().
G4int GammaRayTelCalorimeterSD::NbOfCALLayers private
Definition at line 72 of file GammaRayTelCalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 72 of file GammaRayTelCalorimeterSD.hh
Referenced by GammaRayTelCalorimeterSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelCalorimeterSD.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelCalorimeterSD.cc