ECCE @ EIC Software: G4INCL::ClusterDecay Namespace Reference
G4INCL::ClusterDecay Namespace Reference
Namespace for functions that handle decay of unstable clusters.
Enumerations
enum ClusterDecayType {
StableCluster, NeutronDecay, ProtonDecay, AlphaDecay,
TwoProtonDecay, TwoNeutronDecay, ProtonUnbound, NeutronUnbound,
LambdaUnbound, LambdaDecay
}
Functions
G4bool isStable (Cluster const *const c)
True if the cluster is stable.
ParticleList decay (Cluster *const c)
Carries out a cluster decay.
Variables
G4ThreadLocal ClusterDecayType clusterDecayMode [ParticleTable::clusterTableSSize][ParticleTable::clusterTableZSize][ParticleTable::clusterTableASize]
Table for cluster decays.
Detailed Description
Namespace for functions that handle decay of unstable clusters.
Enumeration Type Documentation
enum G4INCL::ClusterDecay::ClusterDecayType
Enumerator:
StableCluster
NeutronDecay
ProtonDecay
AlphaDecay
TwoProtonDecay
TwoNeutronDecay
ProtonUnbound
NeutronUnbound
LambdaUnbound
LambdaDecay
Definition at line 66 of file G4INCLClusterDecay.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLClusterDecay.hh
Function Documentation
ParticleList G4INCL::ClusterDecay::decay (Cluster *const c)
Carries out a cluster decay.
Parameters
c cluster that should decay
Returns
list of decay products
Definition at line 637 of file G4INCLClusterDecay.cc.
View newest version in sPHENIX GitHub at line 637 of file G4INCLClusterDecay.cc
References e, G4INCL::Particle::getA(), G4INCL::Particle::getBiasCollisionVector(), G4INCL::Particle::getS(), G4INCL::Particle::getZ(), G4INCL::Lambda, G4INCL::Neutron, G4INCL::Proton, G4INCL::Particle::setRealMass(), and G4INCL::Particle::setType().
Referenced by G4LMsdGenerator::ApplyYourself(), G4MolecularDissociationTable::CheckDataConsistency(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), F04PhysicsList::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), P6DExtDecayerPhysics::ConstructProcess(), DecayFinderContainer_v1::DecayFinderContainer_v1(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingNeutralKaon(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4BinaryCascade::DecayVoidNucleus(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMeson(), DecayFinderContainer_v1::operator=(), DecayFinder::printNode(), G4DecayStrongResonances::Propagate(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate(), G4CascadeInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
G4bool G4INCL::ClusterDecay::isStable (Cluster const *const c)
True if the cluster is stable.
Definition at line 570 of file G4INCLClusterDecay.cc.
View newest version in sPHENIX GitHub at line 570 of file G4INCLClusterDecay.cc
References A(), clusterDecayMode, G4INCL::Particle::getA(), G4INCL::Particle::getS(), G4INCL::Particle::getZ(), L, StableCluster, and Z.
Variable Documentation
G4ThreadLocal ClusterDecayType G4INCL::ClusterDecay::clusterDecayMode
Table for cluster decays.
Definition of "Stable": halflife > 1 ms
These table includes decay data for clusters that INCL presently does not produce. It can't hurt.
Unphysical nuclides (A<Z) are marked as stable, but should never be produced by INCL. If you find them in the output, something is fishy.
Definition at line 587 of file G4INCLClusterDecay.cc.
View newest version in sPHENIX GitHub at line 587 of file G4INCLClusterDecay.cc
Referenced by isStable().