ECCE @ EIC Software: G4MuonicAtomDecay Class Reference
G4MuonicAtomDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuonicAtomDecay.hh>
Public Member Functions
G4MuonicAtomDecay (G4HadronicInteraction *hiptr=nullptr, const G4String &processName="MuonicAtomDecay")
virtual ~G4MuonicAtomDecay ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void ProcessDescription (std::ostream &outFile) const
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &theTrack, const G4Step &theStep)
virtual G4VParticleChange * PostStepDoIt (const G4Track &theTrack, const G4Step &theStep)
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *condition)
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4MuonicAtomDecay (const G4MuonicAtomDecay &right)
G4MuonicAtomDecay & operator= (const G4MuonicAtomDecay &right)
G4VParticleChange * DecayIt (const G4Track &theTrack, const G4Step &theStep)
void FillResult (G4HadFinalState *aR, const G4Track &aT)
void DumpState (const G4Track &, const G4String &, G4ExceptionDescription &)
Private Attributes
G4ParticleChange theTotalResult
const G4double fMuMass
G4HadronicInteraction * cmptr
G4int verboseLevel
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 50 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 50 of file G4MuonicAtomDecay.hh
Constructor & Destructor Documentation
G4MuonicAtomDecay::G4MuonicAtomDecay (G4HadronicInteraction * hiptr = nullptr, const G4String & processName = "MuonicAtomDecay") explicit
Definition at line 67 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 67 of file G4MuonicAtomDecay.cc
References cmptr, G4VProcess::enableAtRestDoIt, G4VProcess::enablePostStepDoIt, and G4VProcess::theProcessSubType.
G4MuonicAtomDecay::~G4MuonicAtomDecay () virtual
Definition at line 86 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 86 of file G4MuonicAtomDecay.cc
G4MuonicAtomDecay::G4MuonicAtomDecay (const G4MuonicAtomDecay & right) private
Member Function Documentation
virtual G4VParticleChange* G4MuonicAtomDecay::AtRestDoIt (const G4Track & theTrack, const G4Step & theStep) inline virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 86 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MuonicAtomDecay.hh
References DecayIt().
G4double G4MuonicAtomDecay::AtRestGetPhysicalInteractionLength (const G4Track & aTrack, G4ForceCondition * condition) virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 114 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 114 of file G4MuonicAtomDecay.cc
References GetMeanLifeTime(), NotForced, G4VProcess::ResetNumberOfInteractionLengthLeft(), and G4VProcess::theNumberOfInteractionLengthLeft.
G4VParticleChange * G4MuonicAtomDecay::DecayIt (const G4Track & theTrack, const G4Step & theStep) private
Definition at line 152 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 152 of file G4MuonicAtomDecay.cc
References A(), G4ParticleChange::AddSecondary(), G4HadronicInteraction::ApplyYourself(), G4DecayProducts::Boost(), G4VParticleChange::Clear(), G4VProcess::ClearNumberOfInteractionLengthLeft(), cm, cmptr, condition(), G4VDecayChannel::DecayIt(), G4DecayProducts::DumpInfo(), DumpState(), G4DecayTable::entries(), G4DecayProducts::entries(), fAlive, FatalException, FillResult(), fStopAndKill, fStopButAlive, G4cout, G4endl, G4Exception(), G4UniformRand, G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4MuonicAtom::GetBaseIon(), G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughterName(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4DynamicParticle::GetDefinition(), G4MuonicAtom::GetDIOLifeTime(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4MuonicAtomHelper::GetKShellEnergy(), G4Track::GetLocalTime(), G4DynamicParticle::GetMass(), GetMeanLifeTime(), G4HadronicInteraction::GetModelName(), G4DynamicParticle::GetMomentumDirection(), G4MuonicAtom::GetNCLifeTime(), G4VDecayChannel::GetNumberOfDaughters(), G4HadFinalState::GetNumberOfSecondaries(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4Track::GetPosition(), G4HadFinalState::GetSecondary(), G4HadSecondary::GetTime(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), GetVerboseLevel(), G4VDecayChannel::GetVerboseLevel(), G4Track::GetWeight(), G4Nucleus::GetZ_asInt(), GeV, G4ParticleChange::Initialize(), G4DecayProducts::IsChecked(), G4VDecayChannel::IsOKWithParentMass(), JustWarning, G4InuclParticleNames::lambda, MeV, G4MuonMinus::MuonMinus(), ns, G4DecayProducts::PopProducts(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeLocalTime(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4DecayTable::SelectADecayChannel(), G4HadProjectile::SetBoundEnergy(), G4HadProjectile::SetGlobalTime(), G4Track::SetGoodForTrackingFlag(), G4VParticleChange::SetNumberOfSecondaries(), G4Nucleus::SetParameters(), G4HadSecondary::SetTime(), G4Track::SetTouchableHandle(), G4VDecayChannel::SetVerboseLevel(), G4VProcess::theNumberOfInteractionLengthLeft, theTotalResult, x, y, Z, and z.
Referenced by AtRestDoIt(), and PostStepDoIt().
void G4MuonicAtomDecay::DumpState (const G4Track & aTrack, const G4String & method, G4ExceptionDescription & ed) private
Definition at line 564 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 564 of file G4MuonicAtomDecay.cc
References G4endl, G4Track::GetKineticEnergy(), G4Track::GetMaterial(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4Track::GetParentID(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4VProcess::GetProcessName(), G4Track::GetTrackID(), G4Track::GetVolume(), CLHEP::GeV, and CLHEP::mm.
Referenced by DecayIt(), and FillResult().
void G4MuonicAtomDecay::FillResult (G4HadFinalState * aR, const G4Track & aT) private
Definition at line 456 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 456 of file G4MuonicAtomDecay.cc
References G4ParticleChange::AddSecondary(), G4HadFinalState::Clear(), DumpState(), e, CLHEP::HepLorentzVector::e(), fAlive, fStopAndKill, fStopButAlive, G4endl, G4Exception(), G4UniformRand, G4DynamicParticle::Get4Momentum(), G4ProcessManager::GetAtRestProcessVector(), G4HadSecondary::GetCreatorModelType(), G4Track::GetDefinition(), G4HadFinalState::GetEnergyChange(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4HadFinalState::GetLocalEnergyDeposit(), G4HadFinalState::GetMomentumChange(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4Track::GetPosition(), G4ParticleDefinition::GetProcessManager(), G4HadFinalState::GetSecondary(), G4HadFinalState::GetStatusChange(), G4HadSecondary::GetTime(), G4Track::GetTouchableHandle(), G4HadFinalState::GetTrafoToLab(), GetVerboseLevel(), G4HadSecondary::GetWeight(), G4Track::GetWeight(), it, JustWarning, mass, G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), CLHEP::HepLorentzVector::rotate(), G4DynamicParticle::Set4Momentum(), G4Track::SetCreatorModelIndex(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), G4ProcessVector::size(), stopAndKill, theTotalResult, Acts::VectorHelpers::time(), track, CLHEP::twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and weight.
Referenced by DecayIt().
G4double G4MuonicAtomDecay::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VRestDiscreteProcess.
Definition at line 591 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 591 of file G4MuonicAtomDecay.cc
References source.hepunit::c_light, DBL_MAX, DBL_MIN, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), G4DynamicParticle::GetTotalMomentum(), GetVerboseLevel(), and GeV.
G4double G4MuonicAtomDecay::GetMeanLifeTime (const G4Track & aTrack, G4ForceCondition * condition) virtual
Implements G4VRestDiscreteProcess.
Definition at line 136 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 136 of file G4MuonicAtomDecay.cc
References G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4ParticleDefinition::GetPDGLifeTime(), GetVerboseLevel(), and ns.
Referenced by AtRestGetPhysicalInteractionLength(), and DecayIt().
G4int G4MuonicAtomDecay::GetVerboseLevel () const inline
Definition at line 74 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 74 of file G4MuonicAtomDecay.hh
References verboseLevel.
Referenced by DecayIt(), FillResult(), GetMeanFreePath(), and GetMeanLifeTime().
G4bool G4MuonicAtomDecay::IsApplicable (const G4ParticleDefinition & a) virtual
Reimplemented from G4VProcess.
Definition at line 92 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 92 of file G4MuonicAtomDecay.cc
References G4ParticleDefinition::GetParticleType().
G4MuonicAtomDecay& G4MuonicAtomDecay::operator= (const G4MuonicAtomDecay & right) private
virtual G4VParticleChange* G4MuonicAtomDecay::PostStepDoIt (const G4Track & theTrack, const G4Step & theStep) inline virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 90 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 90 of file G4MuonicAtomDecay.hh
References DecayIt().
G4double G4MuonicAtomDecay::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 127 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 127 of file G4MuonicAtomDecay.cc
References DBL_MAX, and NotForced.
void G4MuonicAtomDecay::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4VProcess.
Definition at line 449 of file G4MuonicAtomDecay.cc.
View newest version in sPHENIX GitHub at line 449 of file G4MuonicAtomDecay.cc
References G4endl.
void G4MuonicAtomDecay::SetVerboseLevel (G4int value) inline
Definition at line 71 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 71 of file G4MuonicAtomDecay.hh
References verboseLevel.
Member Data Documentation
G4HadronicInteraction* G4MuonicAtomDecay::cmptr private
Definition at line 125 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 125 of file G4MuonicAtomDecay.hh
Referenced by DecayIt(), and G4MuonicAtomDecay().
const G4double G4MuonicAtomDecay::fMuMass private
Definition at line 123 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 123 of file G4MuonicAtomDecay.hh
G4ParticleChange G4MuonicAtomDecay::theTotalResult private
Definition at line 121 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 121 of file G4MuonicAtomDecay.hh
Referenced by DecayIt(), and FillResult().
G4int G4MuonicAtomDecay::verboseLevel private
Definition at line 128 of file G4MuonicAtomDecay.hh.
View newest version in sPHENIX GitHub at line 128 of file G4MuonicAtomDecay.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuonicAtomDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4MuonicAtomDecay.cc