ECCE @ EIC Software: B2TrackerSD Class Reference
B2TrackerSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/include/B2TrackerSD.hh>
Public Member Functions
B2TrackerSD (const G4String &name, const G4String &hitsCollectionName)
virtual ~B2TrackerSD ()
virtual void Initialize (G4HCofThisEvent *hitCollection)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hitCollection)
B2TrackerSD (const G4String &name, const G4String &hitsCollectionName)
virtual ~B2TrackerSD ()
virtual void Initialize (G4HCofThisEvent *hitCollection)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hitCollection)
B2TrackerSD (const G4String &name, const G4String &hitsCollectionName)
virtual ~B2TrackerSD ()
virtual void Initialize (G4HCofThisEvent *hitCollection)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hitCollection)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
B2TrackerHitsCollection * fHitsCollection
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
B2Tracker sensitive detector class
The hits are accounted in hits in ProcessHits() function which is called by Geant4 kernel at each step. A hit is created with each step with non zero energy deposit.
Definition at line 50 of file B2TrackerSD.hh.
View newest version in sPHENIX GitHub at line 50 of file B2TrackerSD.hh
Constructor & Destructor Documentation
B2TrackerSD::B2TrackerSD (const G4String & name, const G4String & hitsCollectionName)
Definition at line 39 of file B2TrackerSD.cc.
View newest version in sPHENIX GitHub at line 39 of file B2TrackerSD.cc
References G4VSensitiveDetector::collectionName, and G4CollectionNameVector::insert().
B2TrackerSD::~B2TrackerSD () virtual
Definition at line 49 of file B2TrackerSD.cc.
View newest version in sPHENIX GitHub at line 49 of file B2TrackerSD.cc
B2TrackerSD::B2TrackerSD (const G4String & name, const G4String & hitsCollectionName)
virtual B2TrackerSD::~B2TrackerSD () virtual
B2TrackerSD::B2TrackerSD (const G4String & name, const G4String & hitsCollectionName)
virtual B2TrackerSD::~B2TrackerSD () virtual
Member Function Documentation
void B2TrackerSD::EndOfEvent (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 95 of file B2TrackerSD.cc.
View newest version in sPHENIX GitHub at line 95 of file B2TrackerSD.cc
References G4THitsCollection< T >::entries(), fHitsCollection, G4cout, G4endl, and G4VSensitiveDetector::verboseLevel.
virtual void B2TrackerSD::EndOfEvent (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
virtual void B2TrackerSD::EndOfEvent (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
virtual void B2TrackerSD::Initialize (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
virtual void B2TrackerSD::Initialize (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
void B2TrackerSD::Initialize (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 54 of file B2TrackerSD.cc.
View newest version in sPHENIX GitHub at line 54 of file B2TrackerSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, fHitsCollection, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), and G4VSensitiveDetector::SensitiveDetectorName.
G4bool B2TrackerSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
Definition at line 70 of file B2TrackerSD.cc.
View newest version in sPHENIX GitHub at line 70 of file B2TrackerSD.cc
References edep, fHitsCollection, G4VTouchable::GetCopyNumber(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), G4Track::GetTrackID(), G4THitsCollection< T >::insert(), B2TrackerHit::SetChamberNb(), B2TrackerHit::SetEdep(), B2TrackerHit::SetPos(), and B2TrackerHit::SetTrackID().
virtual G4bool B2TrackerSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
virtual G4bool B2TrackerSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
Member Data Documentation
B2TrackerHitsCollection * B2TrackerSD::fHitsCollection private
Definition at line 63 of file B2TrackerSD.hh.
View newest version in sPHENIX GitHub at line 63 of file B2TrackerSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/include/B2TrackerSD.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2TrackerSD.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/B2TrackerSD.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/src/B2TrackerSD.cc
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/src/B2TrackerSD.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/src/B2TrackerSD.cc