ECCE @ EIC Software: G4FileUtilities Class Reference
G4FileUtilities Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4FileUtilities.hh>
Public Member Functions
G4FileUtilities ()
~G4FileUtilities ()
G4bool FileExists (const std::string file)
std::string StrErrNo () const
G4int Shell (std::string str)
G4int CopyFile (const std::string srcFile, const std::string dstFile)
G4int DeleteFile (const std::string file, const std::string option)
std::string GetEnv (const std::string env)
Detailed Description
Definition at line 49 of file G4FileUtilities.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FileUtilities.hh
Constructor & Destructor Documentation
G4FileUtilities::G4FileUtilities ()
Definition at line 36 of file G4FileUtilities.cc.
View newest version in sPHENIX GitHub at line 36 of file G4FileUtilities.cc
G4FileUtilities::~G4FileUtilities ()
Definition at line 41 of file G4FileUtilities.cc.
View newest version in sPHENIX GitHub at line 41 of file G4FileUtilities.cc
Member Function Documentation
G4int G4FileUtilities::CopyFile (const std::string srcFile, const std::string dstFile)
Definition at line 61 of file G4FileUtilities.cc.
View newest version in sPHENIX GitHub at line 61 of file G4FileUtilities.cc
References Shell().
G4int G4FileUtilities::DeleteFile (const std::string file, const std::string option)
Definition at line 68 of file G4FileUtilities.cc.
View newest version in sPHENIX GitHub at line 68 of file G4FileUtilities.cc
References file, and Shell().
G4bool G4FileUtilities::FileExists (const std::string file)
Definition at line 46 of file G4FileUtilities.cc.
View newest version in sPHENIX GitHub at line 46 of file G4FileUtilities.cc
References c, close(), fd, and Acts::open.
Referenced by G4PersistencyCenter::SetReadFile().
std::string G4FileUtilities::GetEnv (const std::string env) inline
Definition at line 74 of file G4FileUtilities.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FileUtilities.hh
G4int G4FileUtilities::Shell (std::string str) inline
Definition at line 65 of file G4FileUtilities.hh.
View newest version in sPHENIX GitHub at line 65 of file G4FileUtilities.hh
References system().
Referenced by CopyFile(), and DeleteFile().
std::string G4FileUtilities::StrErrNo () const inline
Definition at line 62 of file G4FileUtilities.hh.
View newest version in sPHENIX GitHub at line 62 of file G4FileUtilities.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4FileUtilities.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4FileUtilities.cc