ECCE @ EIC Software: F03DetectorConstruction Class Reference
F03DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field03/include/F03DetectorConstruction.hh>
Public Member Functions
F03DetectorConstruction ()
virtual ~F03DetectorConstruction ()
void SetAbsorberMaterial (G4String)
void SetAbsorberThickness (G4double)
void SetAbsorberRadius (G4double)
void SetAbsorberZpos (G4double)
void SetWorldMaterial (G4String)
void SetWorldSizeZ (G4double)
void SetWorldSizeR (G4double)
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void PrintCalorParameters ()
G4Material * GetWorldMaterial ()
G4double GetWorldSizeZ ()
G4double GetWorldSizeR ()
G4double GetAbsorberZpos ()
G4double GetZStartAbs ()
G4double GetZEndAbs ()
G4Material * GetAbsorberMaterial ()
G4double GetAbsorberThickness ()
G4double GetAbsorberRadius ()
const G4VPhysicalVolume * GetPhysiWorld ()
const G4VPhysicalVolume * GetAbsorber ()
G4LogicalVolume * GetLogicalAbsorber ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void ComputeCalorParameters ()
G4VPhysicalVolume * ConstructCalorimeter ()
Private Attributes
F03DetectorMessenger * fDetectorMessenger
G4Cache< F03CalorimeterSD * > fCalorimeterSD
G4Cache< F03FieldSetup * > fEmFieldSetup
G4Tubs * fSolidWorld
G4LogicalVolume * fLogicWorld
G4VPhysicalVolume * fPhysiWorld
G4Tubs * fSolidAbsorber
G4LogicalVolume * fLogicAbsorber
G4VPhysicalVolume * fPhysiAbsorber
G4Tubs * fSolidRadSlice
G4LogicalVolume * fLogicRadSlice
G4VPhysicalVolume * fPhysiRadSlice
G4Tubs * fSolidRadiator
G4LogicalVolume * fLogicRadiator
G4VPhysicalVolume * fPhysiRadiator
G4Material * fWorldMaterial
G4Material * fAbsorberMaterial
G4Material * fRadiatorMat
G4double fWorldSizeR
G4double fWorldSizeZ
G4double fAbsorberThickness
G4double fAbsorberRadius
G4double fZAbsorber
G4double fZStartAbs
G4double fZEndAbs
G4double fRadThickness
G4double fGasGap
G4double fDetGap
G4int fFoilNumber
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 54 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file F03DetectorConstruction.hh
Constructor & Destructor Documentation
F03DetectorConstruction::F03DetectorConstruction ()
Definition at line 59 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 59 of file F03DetectorConstruction.cc
References DefineMaterials(), and fDetectorMessenger.
F03DetectorConstruction::~F03DetectorConstruction () virtual
Definition at line 90 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 90 of file F03DetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
void F03DetectorConstruction::ComputeCalorParameters () inline private
Definition at line 145 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 145 of file F03DetectorConstruction.hh
References fAbsorberThickness, fZAbsorber, fZEndAbs, and fZStartAbs.
Referenced by ConstructCalorimeter(), SetAbsorberRadius(), SetAbsorberThickness(), SetAbsorberZpos(), SetWorldSizeR(), and SetWorldSizeZ().
G4VPhysicalVolume * F03DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 97 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 97 of file F03DetectorConstruction.cc
References ConstructCalorimeter().
G4VPhysicalVolume * F03DetectorConstruction::ConstructCalorimeter () private
Definition at line 222 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 222 of file F03DetectorConstruction.cc
References G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), ComputeCalorParameters(), fAbsorberMaterial, fAbsorberRadius, fAbsorberThickness, fDetGap, fFoilNumber, fGasGap, fLogicAbsorber, fLogicRadiator, fLogicRadSlice, fLogicWorld, fPhysiAbsorber, fPhysiRadiator, fPhysiRadSlice, fPhysiWorld, fRadiatorMat, fRadThickness, fSolidAbsorber, fSolidRadiator, fSolidRadSlice, fSolidWorld, fWorldMaterial, fWorldSizeR, fWorldSizeZ, fZAbsorber, G4cout, G4endl, G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), G4Material::GetName(), mm, G4GeometryManager::OpenGeometry(), PrintCalorParameters(), and twopi.
Referenced by Construct().
void F03DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 428 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 428 of file F03DetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCalorimeterSD, fEmFieldSetup, fLogicAbsorber, fLogicRadiator, G4Cache< VALTYPE >::Get(), F03FieldSetup::GetLocalFieldManager(), G4SDManager::GetSDMpointer(), G4Cache< VALTYPE >::Put(), G4AutoDelete::Register(), G4LogicalVolume::SetFieldManager(), and G4VUserDetectorConstruction::SetSensitiveDetector().
void F03DetectorConstruction::DefineMaterials () private
Definition at line 104 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 104 of file F03DetectorConstruction.cc
References a, G4Material::AddElement(), G4Material::AddMaterial(), cm3, fAbsorberMaterial, fRadiatorMat, fWorldMaterial, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetMaterialTable(), kStateGas, mg, mole, source.hepunit::STP_Pressure, source.hepunit::STP_Temperature, and z.
Referenced by F03DetectorConstruction().
const G4VPhysicalVolume* F03DetectorConstruction::GetAbsorber () inline
Definition at line 93 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 93 of file F03DetectorConstruction.hh
References fPhysiAbsorber.
Referenced by F03CalorimeterSD::ProcessHits().
G4Material* F03DetectorConstruction::GetAbsorberMaterial () inline
Definition at line 88 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file F03DetectorConstruction.hh
References fAbsorberMaterial.
G4double F03DetectorConstruction::GetAbsorberRadius () inline
Definition at line 90 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file F03DetectorConstruction.hh
References fAbsorberRadius.
Referenced by F03PrimaryGeneratorAction::GeneratePrimaries().
G4double F03DetectorConstruction::GetAbsorberThickness () inline
Definition at line 89 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file F03DetectorConstruction.hh
References fAbsorberThickness.
Referenced by F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), and F03PrimaryGeneratorAction::GeneratePrimaries().
G4double F03DetectorConstruction::GetAbsorberZpos () inline
Definition at line 84 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file F03DetectorConstruction.hh
References fZAbsorber.
Referenced by F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), and F03PrimaryGeneratorAction::GeneratePrimaries().
G4LogicalVolume* F03DetectorConstruction::GetLogicalAbsorber () inline
Definition at line 94 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file F03DetectorConstruction.hh
References fLogicAbsorber.
const G4VPhysicalVolume* F03DetectorConstruction::GetPhysiWorld () inline
Definition at line 92 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file F03DetectorConstruction.hh
References fPhysiWorld.
G4Material* F03DetectorConstruction::GetWorldMaterial () inline
Definition at line 80 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file F03DetectorConstruction.hh
References fWorldMaterial.
G4double F03DetectorConstruction::GetWorldSizeR () inline
Definition at line 82 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file F03DetectorConstruction.hh
References fWorldSizeR.
G4double F03DetectorConstruction::GetWorldSizeZ () inline
Definition at line 81 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file F03DetectorConstruction.hh
References fWorldSizeZ.
G4double F03DetectorConstruction::GetZEndAbs () inline
Definition at line 86 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file F03DetectorConstruction.hh
References fZEndAbs.
G4double F03DetectorConstruction::GetZStartAbs () inline
Definition at line 85 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file F03DetectorConstruction.hh
References fZStartAbs.
void F03DetectorConstruction::PrintCalorParameters ()
Definition at line 324 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 324 of file F03DetectorConstruction.cc
References fAbsorberMaterial, fAbsorberRadius, fAbsorberThickness, fWorldMaterial, fWorldSizeR, fWorldSizeZ, fZAbsorber, G4cout, G4endl, G4Material::GetName(), and mm.
Referenced by ConstructCalorimeter().
void F03DetectorConstruction::SetAbsorberMaterial (G4String materialChoice)
Definition at line 341 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 341 of file F03DetectorConstruction.cc
References fAbsorberMaterial, fLogicAbsorber, G4Material::GetMaterialTable(), G4Material::GetName(), G4RunManager::GetRunManager(), material(), G4RunManager::PhysicsHasBeenModified(), and G4LogicalVolume::SetMaterial().
Referenced by F03DetectorMessenger::SetNewValue().
void F03DetectorConstruction::SetAbsorberRadius (G4double val)
Definition at line 391 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 391 of file F03DetectorConstruction.cc
References ComputeCalorParameters(), fAbsorberRadius, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F03DetectorMessenger::SetNewValue().
void F03DetectorConstruction::SetAbsorberThickness (G4double val)
Definition at line 381 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 381 of file F03DetectorConstruction.cc
References ComputeCalorParameters(), fAbsorberThickness, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F03DetectorMessenger::SetNewValue().
void F03DetectorConstruction::SetAbsorberZpos (G4double val)
Definition at line 419 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 419 of file F03DetectorConstruction.cc
References ComputeCalorParameters(), fZAbsorber, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F03DetectorMessenger::SetNewValue().
void F03DetectorConstruction::SetWorldMaterial (G4String materialChoice)
Definition at line 361 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 361 of file F03DetectorConstruction.cc
References fLogicWorld, fWorldMaterial, G4Material::GetMaterialTable(), G4Material::GetName(), G4RunManager::GetRunManager(), material(), G4RunManager::PhysicsHasBeenModified(), and G4LogicalVolume::SetMaterial().
Referenced by F03DetectorMessenger::SetNewValue().
void F03DetectorConstruction::SetWorldSizeR (G4double val)
Definition at line 410 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 410 of file F03DetectorConstruction.cc
References ComputeCalorParameters(), fWorldSizeR, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F03DetectorMessenger::SetNewValue().
void F03DetectorConstruction::SetWorldSizeZ (G4double val)
Definition at line 401 of file F03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 401 of file F03DetectorConstruction.cc
References ComputeCalorParameters(), fWorldSizeZ, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F03DetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* F03DetectorConstruction::fAbsorberMaterial private
Definition at line 118 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 118 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), DefineMaterials(), GetAbsorberMaterial(), PrintCalorParameters(), and SetAbsorberMaterial().
G4double F03DetectorConstruction::fAbsorberRadius private
Definition at line 125 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), GetAbsorberRadius(), PrintCalorParameters(), and SetAbsorberRadius().
G4double F03DetectorConstruction::fAbsorberThickness private
Definition at line 124 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 124 of file F03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), GetAbsorberThickness(), PrintCalorParameters(), and SetAbsorberThickness().
G4Cache<F03CalorimeterSD*> F03DetectorConstruction::fCalorimeterSD private
Definition at line 98 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 98 of file F03DetectorConstruction.hh
Referenced by ConstructSDandField().
F03DetectorMessenger* F03DetectorConstruction::fDetectorMessenger private
Definition at line 97 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file F03DetectorConstruction.hh
Referenced by F03DetectorConstruction(), and ~F03DetectorConstruction().
G4double F03DetectorConstruction::fDetGap private
Definition at line 132 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 132 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Cache<F03FieldSetup*> F03DetectorConstruction::fEmFieldSetup private
Definition at line 99 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file F03DetectorConstruction.hh
Referenced by ConstructSDandField().
G4int F03DetectorConstruction::fFoilNumber private
Definition at line 134 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 134 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4double F03DetectorConstruction::fGasGap private
Definition at line 131 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 131 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4LogicalVolume* F03DetectorConstruction::fLogicAbsorber private
Definition at line 106 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), ConstructSDandField(), GetLogicalAbsorber(), and SetAbsorberMaterial().
G4LogicalVolume* F03DetectorConstruction::fLogicRadiator private
Definition at line 114 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and ConstructSDandField().
G4LogicalVolume* F03DetectorConstruction::fLogicRadSlice private
Definition at line 110 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4LogicalVolume* F03DetectorConstruction::fLogicWorld private
Definition at line 102 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and SetWorldMaterial().
G4VPhysicalVolume* F03DetectorConstruction::fPhysiAbsorber private
Definition at line 107 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetAbsorber().
G4VPhysicalVolume* F03DetectorConstruction::fPhysiRadiator private
Definition at line 115 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 115 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4VPhysicalVolume* F03DetectorConstruction::fPhysiRadSlice private
Definition at line 111 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 111 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4VPhysicalVolume* F03DetectorConstruction::fPhysiWorld private
Definition at line 103 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetPhysiWorld().
G4Material* F03DetectorConstruction::fRadiatorMat private
Definition at line 119 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and DefineMaterials().
G4double F03DetectorConstruction::fRadThickness private
Definition at line 130 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 130 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Tubs* F03DetectorConstruction::fSolidAbsorber private
Definition at line 105 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Tubs* F03DetectorConstruction::fSolidRadiator private
Definition at line 113 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 113 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Tubs* F03DetectorConstruction::fSolidRadSlice private
Definition at line 109 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Tubs* F03DetectorConstruction::fSolidWorld private
Definition at line 101 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Material* F03DetectorConstruction::fWorldMaterial private
Definition at line 117 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), DefineMaterials(), GetWorldMaterial(), PrintCalorParameters(), and SetWorldMaterial().
G4double F03DetectorConstruction::fWorldSizeR private
Definition at line 121 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), GetWorldSizeR(), PrintCalorParameters(), and SetWorldSizeR().
G4double F03DetectorConstruction::fWorldSizeZ private
Definition at line 122 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 122 of file F03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), GetWorldSizeZ(), PrintCalorParameters(), and SetWorldSizeZ().
G4double F03DetectorConstruction::fZAbsorber private
Definition at line 127 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 127 of file F03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), GetAbsorberZpos(), PrintCalorParameters(), and SetAbsorberZpos().
G4double F03DetectorConstruction::fZEndAbs private
Definition at line 128 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 128 of file F03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and GetZEndAbs().
G4double F03DetectorConstruction::fZStartAbs private
Definition at line 128 of file F03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 128 of file F03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and GetZStartAbs().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field03/include/F03DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field03/src/F03DetectorConstruction.cc