ECCE @ EIC Software: B4RunAction Class Reference
B4RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B4/B4a/include/B4RunAction.hh>
Public Member Functions
B4RunAction ()
virtual ~B4RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
B4RunAction ()
virtual ~B4RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
B4RunAction ()
virtual ~B4RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Run action class
It accumulates statistic and computes dispersion of the energy deposit and track lengths of charged particles with use of analysis tools: H1D histograms are created in BeginOfRunAction() for the following physics quantities:
Edep in absorber
Edep in gap
Track length in absorber
Track length in gap The same values are also saved in the ntuple. The histograms and ntuple are saved in the output file in a format accoring to a selected technology in B4Analysis.hh.
In EndOfRunAction(), the accumulated statistic and computed dispersion is printed.
Definition at line 56 of file B4RunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file B4RunAction.hh
Constructor & Destructor Documentation
B4RunAction::B4RunAction ()
Definition at line 40 of file B4RunAction.cc.
View newest version in sPHENIX GitHub at line 40 of file B4RunAction.cc
References cm, G4cout, G4endl, G4RunManager::GetRunManager(), G4ToolsAnalysisManager::Instance(), m, MeV, and G4RunManager::SetPrintProgress().
B4RunAction::~B4RunAction () virtual
Definition at line 80 of file B4RunAction.cc.
View newest version in sPHENIX GitHub at line 80 of file B4RunAction.cc
References G4ToolsAnalysisManager::Instance().
B4RunAction::B4RunAction ()
virtual B4RunAction::~B4RunAction () virtual
B4RunAction::B4RunAction ()
virtual B4RunAction::~B4RunAction () virtual
Member Function Documentation
void B4RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 87 of file B4RunAction.cc.
View newest version in sPHENIX GitHub at line 87 of file B4RunAction.cc
References G4ToolsAnalysisManager::Instance().
virtual void B4RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void B4RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
virtual void B4RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void B4RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 103 of file B4RunAction.cc.
View newest version in sPHENIX GitHub at line 103 of file B4RunAction.cc
References G4BestUnit, G4cout, G4endl, G4ToolsAnalysisManager::Instance(), and G4UserRunAction::isMaster.
virtual void B4RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B4/B4a/include/B4RunAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4c/include/B4RunAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/include/B4RunAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4a/src/B4RunAction.cc
geant4/tree/geant4-10.6-release/examples/basic/B4/B4c/src/B4RunAction.cc
geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/src/B4RunAction.cc