ECCE @ EIC Software: G4GammaConversionToMuons Class Reference
G4GammaConversionToMuons Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4GammaConversionToMuons.hh>
Public Member Functions
G4GammaConversionToMuons (const G4String &processName="GammaToMuPair", G4ProcessType type=fElectromagnetic)
~G4GammaConversionToMuons () override
G4bool IsApplicable (const G4ParticleDefinition &) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
void PrintInfoDefinition ()
void SetCrossSecFactor (G4double fac)
G4double GetCrossSecFactor () const
G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition) override
G4double GetCrossSectionPerAtom (const G4DynamicParticle *aDynamicGamma, const G4Element *anElement)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
G4double ComputeCrossSectionPerAtom (G4double GammaEnergy, G4int Z)
G4double ComputeMeanFreePath (G4double GammaEnergy, const G4Material *aMaterial)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
const G4Element * SelectRandomAtom (const G4DynamicParticle *aDynamicGamma, const G4Material *aMaterial)
G4GammaConversionToMuons & operator= (const G4GammaConversionToMuons &right)=delete
G4GammaConversionToMuons (const G4GammaConversionToMuons &)=delete
Private Attributes
G4double Mmuon
G4double Rc
G4double LimitEnergy
G4double LowestEnergyLimit
G4double HighestEnergyLimit
G4double Energy5DLimit
G4double MeanFreePath
G4double CrossSecFactor
G4LossTableManager * fManager
G4BetheHeitler5DModel * f5Dmodel
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theMuonPlus
const G4ParticleDefinition * theMuonMinus
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 60 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 60 of file G4GammaConversionToMuons.hh
Constructor & Destructor Documentation
G4GammaConversionToMuons::G4GammaConversionToMuons (const G4String & processName = "GammaToMuPair", G4ProcessType type = fElectromagnetic) explicit
Definition at line 60 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 60 of file G4GammaConversionToMuons.cc
References DBL_MAX, fGammaConversionToMuMu, fManager, G4LossTableManager::Instance(), MeanFreePath, G4LossTableManager::Register(), and G4VProcess::SetProcessSubType().
G4GammaConversionToMuons::~G4GammaConversionToMuons () override
Definition at line 83 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 83 of file G4GammaConversionToMuons.cc
References G4LossTableManager::DeRegister(), and fManager.
G4GammaConversionToMuons::G4GammaConversionToMuons (const G4GammaConversionToMuons &) private delete
Member Function Documentation
void G4GammaConversionToMuons::BuildPhysicsTable (const G4ParticleDefinition & p) override virtual
Reimplemented from G4VProcess.
Definition at line 97 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 97 of file G4GammaConversionToMuons.cc
References Energy5DLimit, f5Dmodel, G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4BetheHeitler5DModel::Initialise(), G4EmParameters::Instance(), G4EmParameters::MaxEnergyFor5DMuPair(), PrintInfoDefinition(), G4BetheHeitler5DModel::SetLeptonPair(), theMuonMinus, and theMuonPlus.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable().
G4double G4GammaConversionToMuons::ComputeCrossSectionPerAtom (G4double GammaEnergy, G4int Z)
Definition at line 174 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 174 of file G4GammaConversionToMuons.cc
References B(), CrossSecFactor, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, G4Exp(), G4Log(), G4NistManager::GetA27(), G4NistManager::GetZ13(), G4NistManager::Instance(), LowestEnergyLimit, Mmuon, PowSat, Rc, and sqrte.
Referenced by ComputeMeanFreePath(), and GetCrossSectionPerAtom().
G4double G4GammaConversionToMuons::ComputeMeanFreePath (G4double GammaEnergy, const G4Material * aMaterial)
Definition at line 133 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 133 of file G4GammaConversionToMuons.cc
References ComputeCrossSectionPerAtom(), DBL_MAX, e, G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), LimitEnergy, LowestEnergyLimit, and y.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable(), and GetMeanFreePath().
G4double G4GammaConversionToMuons::GetCrossSecFactor () const inline
Definition at line 85 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 85 of file G4GammaConversionToMuons.hh
References CrossSecFactor.
G4double G4GammaConversionToMuons::GetCrossSectionPerAtom (const G4DynamicParticle * aDynamicGamma, const G4Element * anElement)
Definition at line 162 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 162 of file G4GammaConversionToMuons.cc
References ComputeCrossSectionPerAtom(), G4DynamicParticle::GetKineticEnergy(), and G4Element::GetZasInt().
Referenced by SelectRandomAtom().
G4double G4GammaConversionToMuons::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) override virtual
Implements G4VDiscreteProcess.
Definition at line 113 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 113 of file G4GammaConversionToMuons.cc
References ComputeMeanFreePath(), DBL_MAX, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterial(), LowestEnergyLimit, and MeanFreePath.
G4bool G4GammaConversionToMuons::IsApplicable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Definition at line 90 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 90 of file G4GammaConversionToMuons.cc
References theGamma.
G4GammaConversionToMuons& G4GammaConversionToMuons::operator= (const G4GammaConversionToMuons & right) private delete
G4VParticleChange * G4GammaConversionToMuons::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 226 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 226 of file G4GammaConversionToMuons.cc
References kdfinder::abs(), G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, B(), C2, DBL_MAX, source.hepunit::electron_mass_c2, Energy5DLimit, f1, f2, f5Dmodel, fStopAndKill, G4cout, G4endl, G4Exp(), G4Log(), G4UniformRand, G4NistManager::GetA27(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4NistManager::GetZ13(), G4Element::GetZasInt(), G4ParticleChange::Initialize(), G4NistManager::Instance(), LimitEnergy, LowestEnergyLimit, Mmuon, nmax, G4InuclParticleNames::nn, pi, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4BetheHeitler5DModel::SampleSecondaries(), SelectRandomAtom(), G4VParticleChange::SetNumberOfSecondaries(), sqrte, t, theMuonMinus, theMuonPlus, twopi, Acts::UnitConstants::u, xmax, xmin, and Z.
Referenced by G4GammaGeneralProcess::PostStepDoIt().
void G4GammaConversionToMuons::PrintInfoDefinition ()
Definition at line 460 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 460 of file G4GammaConversionToMuons.cc
References G4BestUnit, G4cout, G4endl, G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), GeV, HighestEnergyLimit, and LowestEnergyLimit.
Referenced by BuildPhysicsTable().
const G4Element * G4GammaConversionToMuons::SelectRandomAtom (const G4DynamicParticle * aDynamicGamma, const G4Material * aMaterial) private
Definition at line 431 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 431 of file G4GammaConversionToMuons.cc
References G4UniformRand, GetCrossSectionPerAtom(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), and MeanFreePath.
Referenced by PostStepDoIt().
void G4GammaConversionToMuons::SetCrossSecFactor (G4double fac)
Definition at line 216 of file G4GammaConversionToMuons.cc.
View newest version in sPHENIX GitHub at line 216 of file G4GammaConversionToMuons.cc
References CrossSecFactor, fac, G4cout, and G4endl.
Referenced by G4EmExtraPhysics::ConstructProcess(), and PhysicsList::SetGammaToMuPairFac().
Member Data Documentation
G4double G4GammaConversionToMuons::CrossSecFactor private
Definition at line 132 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 132 of file G4GammaConversionToMuons.hh
Referenced by ComputeCrossSectionPerAtom(), GetCrossSecFactor(), and SetCrossSecFactor().
G4double G4GammaConversionToMuons::Energy5DLimit private
Definition at line 129 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 129 of file G4GammaConversionToMuons.hh
Referenced by BuildPhysicsTable(), and PostStepDoIt().
G4BetheHeitler5DModel* G4GammaConversionToMuons::f5Dmodel private
Definition at line 136 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 136 of file G4GammaConversionToMuons.hh
Referenced by BuildPhysicsTable(), and PostStepDoIt().
G4LossTableManager* G4GammaConversionToMuons::fManager private
Definition at line 135 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 135 of file G4GammaConversionToMuons.hh
Referenced by G4GammaConversionToMuons(), and ~G4GammaConversionToMuons().
G4double G4GammaConversionToMuons::HighestEnergyLimit private
Definition at line 128 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 128 of file G4GammaConversionToMuons.hh
Referenced by PrintInfoDefinition().
G4double G4GammaConversionToMuons::LimitEnergy private
Definition at line 126 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 126 of file G4GammaConversionToMuons.hh
Referenced by ComputeMeanFreePath(), and PostStepDoIt().
G4double G4GammaConversionToMuons::LowestEnergyLimit private
Definition at line 127 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 127 of file G4GammaConversionToMuons.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeMeanFreePath(), GetMeanFreePath(), PostStepDoIt(), and PrintInfoDefinition().
G4double G4GammaConversionToMuons::MeanFreePath private
Definition at line 131 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 131 of file G4GammaConversionToMuons.hh
Referenced by G4GammaConversionToMuons(), GetMeanFreePath(), and SelectRandomAtom().
G4double G4GammaConversionToMuons::Mmuon private
Definition at line 124 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 124 of file G4GammaConversionToMuons.hh
Referenced by ComputeCrossSectionPerAtom(), and PostStepDoIt().
G4double G4GammaConversionToMuons::Rc private
Definition at line 125 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 125 of file G4GammaConversionToMuons.hh
Referenced by ComputeCrossSectionPerAtom().
const G4ParticleDefinition* G4GammaConversionToMuons::theGamma private
Definition at line 137 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 137 of file G4GammaConversionToMuons.hh
Referenced by IsApplicable().
const G4ParticleDefinition* G4GammaConversionToMuons::theMuonMinus private
Definition at line 139 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 139 of file G4GammaConversionToMuons.hh
Referenced by BuildPhysicsTable(), and PostStepDoIt().
const G4ParticleDefinition* G4GammaConversionToMuons::theMuonPlus private
Definition at line 138 of file G4GammaConversionToMuons.hh.
View newest version in sPHENIX GitHub at line 138 of file G4GammaConversionToMuons.hh
Referenced by BuildPhysicsTable(), and PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4GammaConversionToMuons.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4GammaConversionToMuons.cc