ECCE @ EIC Software: G4DAWNFILEViewer Class Reference
G4DAWNFILEViewer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/include/G4DAWNFILEViewer.hh>
Public Member Functions
G4DAWNFILEViewer (G4DAWNFILESceneHandler &scene, const G4String &name="")
virtual ~G4DAWNFILEViewer ()
void SetView ()
void ClearView ()
void DrawView ()
void ShowView ()
void SendViewParameters ()
const char * GetG4PrimViewer ()
const char * GetG4PrimViewerInvocation ()
const char * GetPSViewer ()
void SendDrawingStyleToDAWNGUI (std::ostream &out)
Public Member Functions inherited from G4VViewer
G4VViewer (G4VSceneHandler &, G4int id, const G4String &name="")
virtual ~G4VViewer ()
virtual void Initialise ()
virtual void ResetView ()
void RefreshView ()
virtual void FinishView ()
std::vector< G4ThreeVector > ComputeFlyThrough (G4Vector3D *)
const G4String & GetName () const
const G4String & GetShortName () const
void SetName (const G4String &)
G4int GetViewId () const
G4VSceneHandler * GetSceneHandler () const
const G4ViewParameters & GetViewParameters () const
const G4ViewParameters & GetDefaultViewParameters () const
virtual const std::vector
< G4ModelingParameters::VisAttributesModifier > * GetPrivateVisAttributesModifiers () const
void SetViewParameters (const G4ViewParameters &vp)
void SetDefaultViewParameters (const G4ViewParameters &vp)
const G4VisAttributes * GetApplicableVisAttributes (const G4VisAttributes *) const
void SetNeedKernelVisit (G4bool need)
void NeedKernelVisit ()
void ProcessView ()
Private Types
enum FRDEV {
FRDEV_PS =1, FRDEV_XWIN =2, FRDEV_PS2 =3, FRDEV_XWIN2 =4,
FRDEV_OPEN_GL =5, FRDEV_DEVICE_END =6
}
Private Attributes
G4DAWNFILESceneHandler & fSceneHandler
char fG4PrimViewer [32]
char fG4PrimViewerInvocation [64]
char fPSViewer [32]
Additional Inherited Members
Protected Member Functions inherited from G4VViewer
void SetTouchable (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath)
void TouchableSetVisibility (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, G4bool visibility)
void TouchableSetColour (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, const G4Colour &)
Protected Attributes inherited from G4VViewer
G4VSceneHandler & fSceneHandler
G4int fViewId
G4String fName
G4String fShortName
G4ViewParameters fVP
G4ViewParameters fDefaultVP
G4bool fNeedKernelVisit
Detailed Description
Definition at line 39 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 39 of file G4DAWNFILEViewer.hh
Member Enumeration Documentation
enum G4DAWNFILEViewer::FRDEV private
Enumerator:
FRDEV_PS
FRDEV_XWIN
FRDEV_PS2
FRDEV_XWIN2
FRDEV_OPEN_GL
FRDEV_DEVICE_END
Definition at line 41 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 41 of file G4DAWNFILEViewer.hh
Constructor & Destructor Documentation
G4DAWNFILEViewer::G4DAWNFILEViewer (G4DAWNFILESceneHandler & scene, const G4String & name = "")
Definition at line 62 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 62 of file G4DAWNFILEViewer.cc
References fG4PrimViewer, fG4PrimViewerInvocation, fPSViewer, fSceneHandler, and G4DAWNFILESceneHandler::GetG4PrimFileName().
G4DAWNFILEViewer::~G4DAWNFILEViewer () virtual
Definition at line 96 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 96 of file G4DAWNFILEViewer.cc
Member Function Documentation
void G4DAWNFILEViewer::ClearView (void) virtual
Implements G4VViewer.
Definition at line 113 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 113 of file G4DAWNFILEViewer.cc
References G4FRofstream::Close(), G4VisManager::errors, G4DAWNFILESceneHandler::fG4PrimFileName, G4DAWNFILESceneHandler::fPrimDest, FR_G4_PRIM_HEADER, G4DAWNFILESceneHandler::FRBeginModeling(), G4DAWNFILESceneHandler::FRflag_in_modeling, fSceneHandler, G4cout, G4endl, G4VisManager::GetVerbosity(), G4FRofstream::IsOpen(), G4FRofstream::Open(), and G4DAWNFILESceneHandler::SendStr().
void G4DAWNFILEViewer::DrawView () virtual
Implements G4VViewer.
Definition at line 131 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 131 of file G4DAWNFILEViewer.cc
References G4VisManager::errors, G4DAWNFILESceneHandler::FRBeginModeling(), fSceneHandler, G4cout, G4endl, G4VisManager::GetVerbosity(), G4VViewer::NeedKernelVisit(), and G4VViewer::ProcessView().
const char* G4DAWNFILEViewer::GetG4PrimViewer () inline
Definition at line 56 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 56 of file G4DAWNFILEViewer.hh
References fG4PrimViewer.
const char* G4DAWNFILEViewer::GetG4PrimViewerInvocation () inline
Definition at line 57 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 57 of file G4DAWNFILEViewer.hh
References fG4PrimViewerInvocation.
Referenced by ShowView().
const char* G4DAWNFILEViewer::GetPSViewer () inline
Definition at line 58 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 58 of file G4DAWNFILEViewer.hh
References fPSViewer.
Referenced by SendViewParameters().
void G4DAWNFILEViewer::SendDrawingStyleToDAWNGUI (std::ostream & out)
Definition at line 206 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 206 of file G4DAWNFILEViewer.cc
References G4VViewer::fVP, G4endl, G4ViewParameters::GetDrawingStyle(), G4ViewParameters::hlhsr, G4ViewParameters::hlr, G4ViewParameters::hsr, and G4ViewParameters::wireframe.
Referenced by SendViewParameters().
void G4DAWNFILEViewer::SendViewParameters ()
Definition at line 242 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 242 of file G4DAWNFILEViewer.cc
References G4VisManager::errors, FR_ENV_MULTI_WINDOW, FR_ENV_MULTI_WINDOW2, fSceneHandler, G4VViewer::fVP, G4cout, G4endl, G4ViewParameters::GetCurrentTargetPoint(), G4ViewParameters::GetDolly(), G4Scene::GetExtent(), G4VisExtent::GetExtentRadius(), G4ViewParameters::GetFieldHalfAngle(), GetPSViewer(), G4VSceneHandler::GetScene(), G4Scene::GetStandardTargetPoint(), G4VisManager::GetVerbosity(), G4ViewParameters::GetViewpointDirection(), G4ViewParameters::GetZoomFactor(), pi, radius, SendDrawingStyleToDAWNGUI(), HepGeom::BasicVector3D< T >::theta(), HepGeom::BasicVector3D< T >::unit(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
Referenced by ShowView().
void G4DAWNFILEViewer::SetView () virtual
Implements G4VViewer.
Definition at line 100 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 100 of file G4DAWNFILEViewer.cc
References G4VisManager::errors, G4cout, G4endl, and G4VisManager::GetVerbosity().
void G4DAWNFILEViewer::ShowView (void) virtual
Reimplemented from G4VViewer.
Definition at line 151 of file G4DAWNFILEViewer.cc.
View newest version in sPHENIX GitHub at line 151 of file G4DAWNFILEViewer.cc
References G4FRofstream::DoesFileExist(), G4VisManager::errors, fG4PrimViewer, fG4PrimViewerInvocation, G4DAWNFILESceneHandler::FREndModeling(), G4DAWNFILESceneHandler::FRIsInModeling(), fSceneHandler, G4cout, G4endl, G4DAWNFILESceneHandler::GetG4PrimFileName(), GetG4PrimViewerInvocation(), G4VisManager::GetVerbosity(), SendViewParameters(), system(), and void().
Member Data Documentation
char G4DAWNFILEViewer::fG4PrimViewer[32] private
Definition at line 64 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 64 of file G4DAWNFILEViewer.hh
Referenced by G4DAWNFILEViewer(), GetG4PrimViewer(), and ShowView().
char G4DAWNFILEViewer::fG4PrimViewerInvocation[64] private
Definition at line 65 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 65 of file G4DAWNFILEViewer.hh
Referenced by G4DAWNFILEViewer(), GetG4PrimViewerInvocation(), and ShowView().
char G4DAWNFILEViewer::fPSViewer[32] private
Definition at line 66 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 66 of file G4DAWNFILEViewer.hh
Referenced by G4DAWNFILEViewer(), and GetPSViewer().
G4DAWNFILESceneHandler& G4DAWNFILEViewer::fSceneHandler private
Definition at line 62 of file G4DAWNFILEViewer.hh.
View newest version in sPHENIX GitHub at line 62 of file G4DAWNFILEViewer.hh
Referenced by ClearView(), DrawView(), G4DAWNFILEViewer(), SendViewParameters(), and ShowView().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/include/G4DAWNFILEViewer.hh
geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/src/G4DAWNFILEViewer.cc