ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/HEPRandom/include/G4QuickRand.hh File Reference
G4QuickRand.hh File Reference
#include <cstdint>
#include "G4Types.hh"
Functions
G4double G4QuickRand ()
Function Documentation
G4double G4QuickRand () inline
Definition at line 34 of file G4QuickRand.hh.
View newest version in sPHENIX GitHub at line 34 of file G4QuickRand.hh
References f, G4ThreadLocal, x, and y.
Referenced by G4VSolid::EstimateCubicVolume(), G4VSolid::EstimateSurfaceArea(), G4BooleanSolid::GetPointOnSurface(), G4Ellipsoid::GetPointOnSurface(), and G4Tet::GetPointOnSurface().