ECCE @ EIC Software: G4VKineticNucleon Class Reference
G4VKineticNucleon Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VKineticNucleon.hh>
Public Member Functions
G4VKineticNucleon ()
G4VKineticNucleon (const G4VKineticNucleon &right)
virtual ~G4VKineticNucleon ()
const G4VKineticNucleon & operator= (const G4VKineticNucleon &right)
G4bool operator== (const G4VKineticNucleon &right) const
G4bool operator!= (const G4VKineticNucleon &right) const
virtual G4KineticTrackVector * Decay ()
virtual const G4LorentzVector & Get4Momentum () const =0
virtual const
G4ParticleDefinition * GetDefinition () const =0
virtual const G4ThreeVector & GetPosition () const =0
Detailed Description
Definition at line 37 of file G4VKineticNucleon.hh.
View newest version in sPHENIX GitHub at line 37 of file G4VKineticNucleon.hh
Constructor & Destructor Documentation
G4VKineticNucleon::G4VKineticNucleon ()
Definition at line 30 of file G4VKineticNucleon.cc.
View newest version in sPHENIX GitHub at line 30 of file G4VKineticNucleon.cc
G4VKineticNucleon::G4VKineticNucleon (const G4VKineticNucleon & right)
Definition at line 34 of file G4VKineticNucleon.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VKineticNucleon.cc
G4VKineticNucleon::~G4VKineticNucleon () virtual
Definition at line 39 of file G4VKineticNucleon.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VKineticNucleon.cc
Member Function Documentation
G4KineticTrackVector * G4VKineticNucleon::Decay () inline virtual
Reimplemented in G4KineticTrack.
Definition at line 71 of file G4VKineticNucleon.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VKineticNucleon.hh
virtual const G4LorentzVector& G4VKineticNucleon::Get4Momentum () const pure virtual
Implemented in G4KineticTrack, and G4Nucleon.
Referenced by G4VSplitableHadron::G4VSplitableHadron().
virtual const G4ParticleDefinition* G4VKineticNucleon::GetDefinition () const pure virtual
Implemented in G4Nucleon, and G4KineticTrack.
Referenced by G4VSplitableHadron::G4VSplitableHadron().
virtual const G4ThreeVector& G4VKineticNucleon::GetPosition () const pure virtual
Implemented in G4KineticTrack, and G4Nucleon.
Referenced by G4VSplitableHadron::G4VSplitableHadron().
G4bool G4VKineticNucleon::operator!= (const G4VKineticNucleon & right) const
Definition at line 53 of file G4VKineticNucleon.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VKineticNucleon.cc
References right.
const G4VKineticNucleon & G4VKineticNucleon::operator= (const G4VKineticNucleon & right) inline
Definition at line 76 of file G4VKineticNucleon.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VKineticNucleon.hh
G4bool G4VKineticNucleon::operator== (const G4VKineticNucleon & right) const
Definition at line 48 of file G4VKineticNucleon.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VKineticNucleon.cc
References right.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VKineticNucleon.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4VKineticNucleon.cc