ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/HEPRandom/include/G4Poisson.hh File Reference
G4Poisson.hh File Reference
#include <CLHEP/Units/PhysicalConstants.h>
#include "G4Types.hh"
#include "G4Exp.hh"
#include "Randomize.hh"
Functions
G4long G4Poisson (G4double mean)
Function Documentation
G4long G4Poisson (G4double mean) inline
Definition at line 50 of file G4Poisson.hh.
View newest version in sPHENIX GitHub at line 50 of file G4Poisson.hh
References border, G4Exp(), G4UniformRand, CLHEP::pi, and t.
Referenced by G4UniversalFluctuation::AddExcitation(), G4WilsonAbrasionModel::ApplyYourself(), G4hImpactIonisation::ElectronicLossFluctuation(), G4RDShellVacancy::GenerateNumberOfIonisations(), G4ShellVacancy::GenerateNumberOfIonisations(), G4ForwardXrayTR::GetEnergyTR(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4ParticleHPProduct::GetMultiplicity(), G4ParticleHPPhotonDist::GetPhotons(), G4PAIySection::GetStepCerenkovLoss(), G4PAIxSection::GetStepCerenkovLoss(), G4PAIySection::GetStepEnergyLoss(), G4PAIxSection::GetStepEnergyLoss(), G4PAIxSection::GetStepMMLoss(), G4PAIySection::GetStepPlasmonLoss(), G4PAIxSection::GetStepPlasmonLoss(), G4PAIxSection::GetStepResonanceLoss(), G4ForwardXrayTR::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4PAIPhotData::SampleAlongStepPhotonTransfer(), G4PAIPhotData::SampleAlongStepPlasmonTransfer(), G4PAIPhotData::SampleAlongStepTransfer(), G4PAIModelData::SampleAlongStepTransfer(), G4BohrFluctuations::SampleFluctuations(), G4UniversalFluctuation::SampleFluctuations(), and G4ParticleHPFSFissionFS::SampleNeutronMult().