ECCE @ EIC Software: G4MolecularConfiguration::G4MolecularConfigurationManager Class Reference
G4MolecularConfiguration::G4MolecularConfigurationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularConfiguration.hh>
Public Member Functions
G4MolecularConfigurationManager ()
~G4MolecularConfigurationManager ()
int GetNumberOfCreatedSpecies ()
G4int Insert (const G4MoleculeDefinition *molDef, const G4ElectronOccupancy &eOcc, G4MolecularConfiguration *molConf)
G4int Insert (const G4MoleculeDefinition *molDef, int charge, G4MolecularConfiguration *molConf)
G4int Insert (const G4MoleculeDefinition *molDef, const G4String &label, G4MolecularConfiguration *molConf)
void AddUserID (const G4String &name, G4MolecularConfiguration *molecule)
void RecordNewlyLabeledConfiguration (G4MolecularConfiguration *molConf)
const G4ElectronOccupancy * FindCommonElectronOccupancy (const G4MoleculeDefinition *molDef, const G4ElectronOccupancy &eOcc)
G4MolecularConfiguration * GetMolecularConfiguration (const G4MoleculeDefinition *molDef, const G4ElectronOccupancy &eOcc)
G4MolecularConfiguration * GetMolecularConfiguration (const G4MoleculeDefinition *molDef, int charge)
G4MolecularConfiguration * GetMolecularConfiguration (const G4MoleculeDefinition *molDef, const G4String &label)
G4MolecularConfiguration * GetMolecularConfiguration (int moleculeID)
G4MolecularConfiguration * GetMolecularConfiguration (const G4String &userID)
G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *molDef, const G4ElectronOccupancy &eOcc)
G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *molDef, int charge)
void RemoveMolecularConfigurationFromTable (G4MolecularConfiguration *)
const std::vector
< G4MolecularConfiguration * > & GetAllSpecies ()
std::map< G4String,
G4MolecularConfiguration * > & GetUserIDTable ()
Static Public Attributes
static G4Mutex fManagerCreationMutex
Private Types
typedef std::map
< G4ElectronOccupancy,
G4MolecularConfiguration
*, comparator > ElectronOccupancyTable
typedef std::map< const
G4MoleculeDefinition
*, ElectronOccupancyTable > MolElectronConfTable
typedef std::map< int,
G4MolecularConfiguration * > ChargeTable
typedef std::map< const
G4MoleculeDefinition
*, ChargeTable > MolChargeConfTable
typedef std::map< const
G4String,
G4MolecularConfiguration * > LabelTable
typedef std::map< const
G4MoleculeDefinition
*, std::map< const G4String,
G4MolecularConfiguration * > > MolLabelConfTable
typedef std::map< G4String,
G4MolecularConfiguration * > UserIDTable
Private Attributes
MolElectronConfTable fElecOccTable
MolChargeConfTable fChargeTable
MolLabelConfTable fLabelTable
UserIDTable fUserIDTable
std::vector
< G4MolecularConfiguration * > fMolConfPerID
G4int fLastMoleculeID
G4Mutex fMoleculeCreationMutex
Detailed Description
Definition at line 340 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 340 of file G4MolecularConfiguration.hh
Member Typedef Documentation
typedef std::map<int, G4MolecularConfiguration*> G4MolecularConfiguration::G4MolecularConfigurationManager::ChargeTable private
Definition at line 430 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 430 of file G4MolecularConfiguration.hh
typedef std::map<G4ElectronOccupancy, G4MolecularConfiguration*, comparator> G4MolecularConfiguration::G4MolecularConfigurationManager::ElectronOccupancyTable private
Definition at line 423 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 423 of file G4MolecularConfiguration.hh
typedef std::map<const G4String, G4MolecularConfiguration*> G4MolecularConfiguration::G4MolecularConfigurationManager::LabelTable private
Definition at line 437 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 437 of file G4MolecularConfiguration.hh
typedef std::map<const G4MoleculeDefinition*, ChargeTable> G4MolecularConfiguration::G4MolecularConfigurationManager::MolChargeConfTable private
Definition at line 432 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 432 of file G4MolecularConfiguration.hh
typedef std::map<const G4MoleculeDefinition*, ElectronOccupancyTable > G4MolecularConfiguration::G4MolecularConfigurationManager::MolElectronConfTable private
Definition at line 425 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 425 of file G4MolecularConfiguration.hh
typedef std::map<const G4MoleculeDefinition*, std::map<const G4String, G4MolecularConfiguration*> > G4MolecularConfiguration::G4MolecularConfigurationManager::MolLabelConfTable private
Definition at line 439 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 439 of file G4MolecularConfiguration.hh
typedef std::map<G4String, G4MolecularConfiguration*> G4MolecularConfiguration::G4MolecularConfigurationManager::UserIDTable private
Definition at line 443 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 443 of file G4MolecularConfiguration.hh
Constructor & Destructor Documentation
G4MolecularConfiguration::G4MolecularConfigurationManager::G4MolecularConfigurationManager () inline
Definition at line 343 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 343 of file G4MolecularConfiguration.hh
References fLastMoleculeID.
G4MolecularConfiguration::G4MolecularConfigurationManager::~G4MolecularConfigurationManager ()
Definition at line 149 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 149 of file G4MolecularConfiguration.cc
Member Function Documentation
void G4MolecularConfiguration::G4MolecularConfigurationManager::AddUserID (const G4String & name, G4MolecularConfiguration * molecule)
Definition at line 868 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 868 of file G4MolecularConfiguration.cc
References FatalException, G4endl, G4Exception(), it, and molecule().
const G4ElectronOccupancy * G4MolecularConfiguration::G4MolecularConfigurationManager::FindCommonElectronOccupancy (const G4MoleculeDefinition * molDef, const G4ElectronOccupancy & eOcc)
Definition at line 216 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 216 of file G4MolecularConfiguration.cc
const std::vector<G4MolecularConfiguration*>& G4MolecularConfiguration::G4MolecularConfigurationManager::GetAllSpecies () inline
Definition at line 408 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 408 of file G4MolecularConfiguration.hh
References fMolConfPerID.
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4ElectronOccupancy & eOcc)
Definition at line 247 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 247 of file G4MolecularConfiguration.cc
References it.
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetMolecularConfiguration (const G4MoleculeDefinition * molDef, int charge)
Definition at line 307 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 307 of file G4MolecularConfiguration.cc
References it.
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4String & label)
Definition at line 919 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 919 of file G4MolecularConfiguration.cc
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetMolecularConfiguration (int moleculeID)
Definition at line 942 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 942 of file G4MolecularConfiguration.cc
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetMolecularConfiguration (const G4String & userID)
Definition at line 1542 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1542 of file G4MolecularConfiguration.cc
References it.
int G4MolecularConfiguration::G4MolecularConfigurationManager::GetNumberOfCreatedSpecies () inline
Definition at line 350 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 350 of file G4MolecularConfiguration.hh
References fLastMoleculeID.
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4ElectronOccupancy & eOcc)
Definition at line 1319 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1319 of file G4MolecularConfiguration.cc
References it.
G4MolecularConfiguration * G4MolecularConfiguration::G4MolecularConfigurationManager::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef, int charge)
Definition at line 1351 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1351 of file G4MolecularConfiguration.cc
References it.
std::map<G4String, G4MolecularConfiguration*>& G4MolecularConfiguration::G4MolecularConfigurationManager::GetUserIDTable () inline
Definition at line 413 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 413 of file G4MolecularConfiguration.hh
References fUserIDTable.
Referenced by G4MolecularConfiguration::GetUserIDTable().
G4int G4MolecularConfiguration::G4MolecularConfigurationManager::Insert (const G4MoleculeDefinition * molDef, const G4ElectronOccupancy & eOcc, G4MolecularConfiguration * molConf)
Definition at line 177 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 177 of file G4MolecularConfiguration.cc
References FatalException, G4Exception(), and it.
G4int G4MolecularConfiguration::G4MolecularConfigurationManager::Insert (const G4MoleculeDefinition * molDef, int charge, G4MolecularConfiguration * molConf)
Definition at line 272 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 272 of file G4MolecularConfiguration.cc
References charge, FatalException, G4Exception(), and it.
G4int G4MolecularConfiguration::G4MolecularConfigurationManager::Insert (const G4MoleculeDefinition * molDef, const G4String & label, G4MolecularConfiguration * molConf)
Definition at line 954 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 954 of file G4MolecularConfiguration.cc
References FatalException, G4Exception(), it, and G4TemplateAutoLock< _Mutex_t >::unlock().
void G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration (G4MolecularConfiguration * molConf)
Definition at line 842 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 842 of file G4MolecularConfiguration.cc
References FatalException, G4MolecularConfiguration::fLabel, G4MolecularConfiguration::fMoleculeDefinition, G4Exception(), and it.
Referenced by G4MolecularConfiguration::SetLabel().
void G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable (G4MolecularConfiguration * configuration)
Definition at line 895 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 895 of file G4MolecularConfiguration.cc
References G4MolecularConfiguration::fElectronOccupancy, G4MolecularConfiguration::GetDefinition(), and G4MolecularConfiguration::GetElectronOccupancy().
Member Data Documentation
MolChargeConfTable G4MolecularConfiguration::G4MolecularConfigurationManager::fChargeTable private
Definition at line 433 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 433 of file G4MolecularConfiguration.hh
MolElectronConfTable G4MolecularConfiguration::G4MolecularConfigurationManager::fElecOccTable private
Definition at line 426 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 426 of file G4MolecularConfiguration.hh
MolLabelConfTable G4MolecularConfiguration::G4MolecularConfigurationManager::fLabelTable private
Definition at line 440 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 440 of file G4MolecularConfiguration.hh
G4int G4MolecularConfiguration::G4MolecularConfigurationManager::fLastMoleculeID private
Definition at line 451 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 451 of file G4MolecularConfiguration.hh
Referenced by G4MolecularConfigurationManager(), and GetNumberOfCreatedSpecies().
G4Mutex MolecularConfigurationManager::fManagerCreationMutex static
Definition at line 404 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 404 of file G4MolecularConfiguration.hh
Referenced by G4MolecularConfiguration::DeleteManager(), and G4MolecularConfiguration::GetManager().
std::vector<G4MolecularConfiguration*> G4MolecularConfiguration::G4MolecularConfigurationManager::fMolConfPerID private
Definition at line 447 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 447 of file G4MolecularConfiguration.hh
Referenced by GetAllSpecies().
G4Mutex G4MolecularConfiguration::G4MolecularConfigurationManager::fMoleculeCreationMutex private
Definition at line 452 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 452 of file G4MolecularConfiguration.hh
UserIDTable G4MolecularConfiguration::G4MolecularConfigurationManager::fUserIDTable private
Definition at line 444 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 444 of file G4MolecularConfiguration.hh
Referenced by GetUserIDTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularConfiguration.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4MolecularConfiguration.cc