ECCE @ EIC Software: G4NeutrinoElectronCcModel Class Reference
G4NeutrinoElectronCcModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/include/G4NeutrinoElectronCcModel.hh>
Public Member Functions
G4NeutrinoElectronCcModel (const G4String &name="nu-e-elastic")
virtual ~G4NeutrinoElectronCcModel ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double SampleCosCMS (const G4HadProjectile *aParticle)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * theNeutrinoE
G4ParticleDefinition * theAntiNeutrinoE
G4ParticleDefinition * theNeutrinoMu
G4ParticleDefinition * theAntiNeutrinoMu
G4ParticleDefinition * theNeutrinoTau
G4ParticleDefinition * theAntiNeutrinoTau
G4ParticleDefinition * theMuonMinus
G4ParticleDefinition * theTauMinus
G4double fSin2tW
G4double fCutEnergy
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 49 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4NeutrinoElectronCcModel.hh
Constructor & Destructor Documentation
G4NeutrinoElectronCcModel::G4NeutrinoElectronCcModel (const G4String & name = "nu-e-elastic")
Definition at line 52 of file G4NeutrinoElectronCcModel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4NeutrinoElectronCcModel.cc
References G4AntiNeutrinoE::AntiNeutrinoE(), G4AntiNeutrinoMu::AntiNeutrinoMu(), G4AntiNeutrinoTau::AntiNeutrinoTau(), e, eV, fCutEnergy, fSin2tW, G4HadronicInteraction::GetMaxEnergy(), GeV, G4HadronicParameters::Instance(), G4MuonMinus::MuonMinus(), G4NeutrinoE::NeutrinoE(), G4NeutrinoMu::NeutrinoMu(), G4NeutrinoTau::NeutrinoTau(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TauMinus::TauMinus(), theAntiNeutrinoE, theAntiNeutrinoMu, theAntiNeutrinoTau, theMuonMinus, theNeutrinoE, theNeutrinoMu, theNeutrinoTau, and theTauMinus.
G4NeutrinoElectronCcModel::~G4NeutrinoElectronCcModel () virtual
Definition at line 80 of file G4NeutrinoElectronCcModel.cc.
View newest version in sPHENIX GitHub at line 80 of file G4NeutrinoElectronCcModel.cc
Member Function Documentation
G4HadFinalState * G4NeutrinoElectronCcModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 125 of file G4NeutrinoElectronCcModel.cc.
View newest version in sPHENIX GitHub at line 125 of file G4NeutrinoElectronCcModel.cc
References G4HadFinalState::AddSecondary(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4HadFinalState::Clear(), source.hepunit::electron_mass_c2, energy, G4UniformRand, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), phi, SampleCosCMS(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetMomentumChange(), theAntiNeutrinoMu, theMuonMinus, theNeutrinoE, G4HadronicInteraction::theParticleChange, theTauMinus, CLHEP::twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and Z.
G4double G4NeutrinoElectronCcModel::GetCutEnergy () inline
Definition at line 68 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4NeutrinoElectronCcModel.hh
References fCutEnergy.
G4bool G4NeutrinoElectronCcModel::IsApplicable (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 95 of file G4NeutrinoElectronCcModel.cc.
View newest version in sPHENIX GitHub at line 95 of file G4NeutrinoElectronCcModel.cc
References source.hepunit::electron_mass_c2, energy, G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), G4HadronicInteraction::SetMinEnergy(), theMuonMinus, theTauMinus, and Z.
void G4NeutrinoElectronCcModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 84 of file G4NeutrinoElectronCcModel.cc.
View newest version in sPHENIX GitHub at line 84 of file G4NeutrinoElectronCcModel.cc
G4double G4NeutrinoElectronCcModel::SampleCosCMS (const G4HadProjectile * aParticle)
Definition at line 208 of file G4NeutrinoElectronCcModel.cc.
View newest version in sPHENIX GitHub at line 208 of file G4NeutrinoElectronCcModel.cc
References a, A(), b, B(), c, D(), d, source.hepunit::electron_mass_c2, energy, G4UniformRand, G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalEnergy(), theMuonMinus, theTauMinus, x1, and y1.
Referenced by ApplyYourself().
void G4NeutrinoElectronCcModel::SetCutEnergy (G4double ec) inline
Definition at line 67 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NeutrinoElectronCcModel.hh
References fCutEnergy.
Member Data Documentation
G4double G4NeutrinoElectronCcModel::fCutEnergy private
Definition at line 87 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4NeutrinoElectronCcModel.hh
Referenced by G4NeutrinoElectronCcModel(), GetCutEnergy(), and SetCutEnergy().
G4double G4NeutrinoElectronCcModel::fSin2tW private
Definition at line 86 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4NeutrinoElectronCcModel.hh
Referenced by G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theAntiNeutrinoE private
Definition at line 77 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4NeutrinoElectronCcModel.hh
Referenced by G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theAntiNeutrinoMu private
Definition at line 79 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 79 of file G4NeutrinoElectronCcModel.hh
Referenced by ApplyYourself(), and G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theAntiNeutrinoTau private
Definition at line 81 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4NeutrinoElectronCcModel.hh
Referenced by G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theMuonMinus private
Definition at line 83 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4NeutrinoElectronCcModel.hh
Referenced by ApplyYourself(), G4NeutrinoElectronCcModel(), IsApplicable(), and SampleCosCMS().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theNeutrinoE private
Definition at line 76 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4NeutrinoElectronCcModel.hh
Referenced by ApplyYourself(), and G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theNeutrinoMu private
Definition at line 78 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4NeutrinoElectronCcModel.hh
Referenced by G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theNeutrinoTau private
Definition at line 80 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4NeutrinoElectronCcModel.hh
Referenced by G4NeutrinoElectronCcModel().
G4ParticleDefinition* G4NeutrinoElectronCcModel::theTauMinus private
Definition at line 84 of file G4NeutrinoElectronCcModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4NeutrinoElectronCcModel.hh
Referenced by ApplyYourself(), G4NeutrinoElectronCcModel(), IsApplicable(), and SampleCosCMS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/include/G4NeutrinoElectronCcModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/src/G4NeutrinoElectronCcModel.cc