ECCE @ EIC Software: G3VolTable Class Reference
G3VolTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3VolTable.hh>
Public Member Functions
G3VolTableEntry * PutVTE (G3VolTableEntry *aVTE)
G3VolTableEntry * GetVTE (const G4String &Vname)
void PrintAll ()
G3VolTable ()
virtual ~G3VolTable ()
G4LogicalVolume * GetG3toG4Mother ()
G3VolTableEntry * GetFirstVTE ()
void SetFirstVTE ()
void VTEStat ()
void CountG3Pos ()
void Clear ()
Private Attributes
G3VolTableEntry * G3toG4TopVTE
G4String _FirstKey
std::map< G4String,
G3VolTableEntry *, std::less
< G4String > > VTD
G4int _NG3Pos
Detailed Description
Definition at line 59 of file G3VolTable.hh.
View newest version in sPHENIX GitHub at line 59 of file G3VolTable.hh
Constructor & Destructor Documentation
G3VolTable::G3VolTable ()
Definition at line 38 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 38 of file G3VolTable.cc
G3VolTable::~G3VolTable () virtual
Definition at line 42 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 42 of file G3VolTable.cc
References VTD.
Member Function Documentation
void G3VolTable::Clear ()
Definition at line 118 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 118 of file G3VolTable.cc
References _FirstKey, _NG3Pos, G3toG4TopVTE, and VTD.
void G3VolTable::CountG3Pos ()
Definition at line 91 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 91 of file G3VolTable.cc
References _NG3Pos.
Referenced by G3VolTableEntry::AddG3Pos().
G3VolTableEntry * G3VolTable::GetFirstVTE ()
Definition at line 106 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 106 of file G3VolTable.cc
References G3toG4TopVTE.
Referenced by G4BuildGeom().
G4LogicalVolume* G3VolTable::GetG3toG4Mother ()
G3VolTableEntry * G3VolTable::GetVTE (const G4String & Vname)
Definition at line 53 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 53 of file G3VolTable.cc
References VTD.
Referenced by G4gsbool(), G4gsdvn(), G4gsdvn2(), G4gsdvt(), G4gsdvt2(), G4gspos(), G4gsposp(), G4gsvolu(), G3VolTableEntry::GetMasterClone(), and PutVTE().
void G3VolTable::PrintAll (void)
Definition at line 60 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 60 of file G3VolTable.cc
References G4cout, G4endl, G3VolTableEntry::GetName(), G3VolTableEntry::GetNoDaughters(), v, VTD, and VTEStat().
Referenced by G4BuildGeom().
G3VolTableEntry * G3VolTable::PutVTE (G3VolTableEntry * aVTE)
Definition at line 75 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 75 of file G3VolTable.cc
References _FirstKey, G3VolTableEntry::GetName(), GetVTE(), and VTD.
Referenced by G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), and G4CreateVTE().
void G3VolTable::SetFirstVTE ()
Definition at line 96 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 96 of file G3VolTable.cc
References _FirstKey, G3toG4TopVTE, G3VolTableEntry::GetMother(), G3VolTableEntry::GetName(), G3VolTableEntry::NPCopies(), and VTD.
Referenced by G4ggclos().
void G3VolTable::VTEStat ()
Definition at line 111 of file G3VolTable.cc.
View newest version in sPHENIX GitHub at line 111 of file G3VolTable.cc
References _NG3Pos, G4cout, G4endl, and VTD.
Referenced by PrintAll().
Member Data Documentation
G4String G3VolTable::_FirstKey private
Definition at line 79 of file G3VolTable.hh.
View newest version in sPHENIX GitHub at line 79 of file G3VolTable.hh
Referenced by Clear(), PutVTE(), and SetFirstVTE().
G4int G3VolTable::_NG3Pos private
Definition at line 81 of file G3VolTable.hh.
View newest version in sPHENIX GitHub at line 81 of file G3VolTable.hh
Referenced by Clear(), CountG3Pos(), and VTEStat().
G3VolTableEntry* G3VolTable::G3toG4TopVTE private
Definition at line 78 of file G3VolTable.hh.
View newest version in sPHENIX GitHub at line 78 of file G3VolTable.hh
Referenced by Clear(), GetFirstVTE(), and SetFirstVTE().
std::map<G4String, G3VolTableEntry*, std::less<G4String> > G3VolTable::VTD private
Definition at line 80 of file G3VolTable.hh.
View newest version in sPHENIX GitHub at line 80 of file G3VolTable.hh
Referenced by Clear(), GetVTE(), PrintAll(), PutVTE(), SetFirstVTE(), VTEStat(), and ~G3VolTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3VolTable.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3VolTable.cc