ECCE @ EIC Software: G4VScoreColorMap Class Reference
G4VScoreColorMap Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoreColorMap.hh>
Public Member Functions
G4VScoreColorMap (G4String mName)
virtual ~G4VScoreColorMap ()
virtual void GetMapColor (G4double val, G4double color[4])=0
G4String GetName () const
void SetFloatingMinMax (G4bool vl=true)
G4bool IfFloatMinMax () const
void SetMinMax (G4double minVal, G4double maxVal)
G4double GetMin () const
G4double GetMax () const
virtual void DrawColorChart (G4int nPoint=5)
virtual void DrawColorChartBar (G4int nPoint)
virtual void DrawColorChartText (G4int nPoint)
void SetPSUnit (G4String &unit)
void SetPSName (G4String &psName)
Protected Attributes
G4String fName
G4bool ifFloat
G4double fMinVal
G4double fMaxVal
G4VVisManager * fVisManager
G4String fPSUnit
G4String fPSName
Detailed Description
Definition at line 36 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 36 of file G4VScoreColorMap.hh
Constructor & Destructor Documentation
G4VScoreColorMap::G4VScoreColorMap (G4String mName)
Definition at line 42 of file G4VScoreColorMap.cc.
View newest version in sPHENIX GitHub at line 42 of file G4VScoreColorMap.cc
G4VScoreColorMap::~G4VScoreColorMap () virtual
Definition at line 46 of file G4VScoreColorMap.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VScoreColorMap.cc
Member Function Documentation
void G4VScoreColorMap::DrawColorChart (G4int nPoint = 5) virtual
Definition at line 49 of file G4VScoreColorMap.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VScoreColorMap.cc
References DrawColorChartBar(), DrawColorChartText(), fVisManager, G4cerr, G4endl, and G4VVisManager::GetConcreteInstance().
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
void G4VScoreColorMap::DrawColorChartBar (G4int nPoint) virtual
Reimplemented in G4ScoreLogColorMap.
Definition at line 61 of file G4VScoreColorMap.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VScoreColorMap.cc
References G4VVisManager::BeginDraw2D(), c, col, G4VVisManager::Draw2D(), G4VVisManager::EndDraw2D(), fVisManager, GetMapColor(), GetMax(), GetMin(), max, min, Acts::Test::rb, G4Visible::SetVisAttributes(), smax, Acts::Test::step(), and y.
Referenced by DrawColorChart().
void G4VScoreColorMap::DrawColorChartText (G4int nPoint) virtual
Reimplemented in G4ScoreLogColorMap.
Definition at line 85 of file G4VScoreColorMap.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VScoreColorMap.cc
References a, b, G4VVisManager::BeginDraw2D(), c, color(), G4VVisManager::Draw2D(), G4VVisManager::EndDraw2D(), fPSName, fPSUnit, fVisManager, GetMapColor(), GetMax(), GetMin(), max, min, n, G4VMarker::SetScreenSize(), G4Visible::SetVisAttributes(), and v.
Referenced by DrawColorChart().
virtual void G4VScoreColorMap::GetMapColor (G4double val, G4double color[4]) pure virtual
Implemented in G4DefaultLinearColorMap, and G4ScoreLogColorMap.
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), DrawColorChartBar(), DrawColorChartText(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
G4double G4VScoreColorMap::GetMax () const inline
Definition at line 65 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VScoreColorMap.hh
References fMaxVal.
Referenced by DrawColorChartBar(), and DrawColorChartText().
G4double G4VScoreColorMap::GetMin () const inline
Definition at line 63 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VScoreColorMap.hh
References fMinVal.
Referenced by DrawColorChartBar(), and DrawColorChartText().
G4String G4VScoreColorMap::GetName (void) const inline
Definition at line 46 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VScoreColorMap.hh
References fName.
Referenced by G4ScoringManager::G4ScoringManager(), and G4ScoringManager::RegisterScoreColorMap().
G4bool G4VScoreColorMap::IfFloatMinMax () const inline
Definition at line 50 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VScoreColorMap.hh
References ifFloat.
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
void G4VScoreColorMap::SetFloatingMinMax (G4bool vl = true) inline
Definition at line 48 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VScoreColorMap.hh
References ifFloat.
Referenced by G4ScoringMessenger::SetNewValue().
void G4VScoreColorMap::SetMinMax (G4double minVal, G4double maxVal) inline
Definition at line 52 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VScoreColorMap.hh
References fMaxVal, fMinVal, G4cerr, and G4endl.
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), and G4ScoringMessenger::SetNewValue().
void G4VScoreColorMap::SetPSName (G4String & psName) inline
Definition at line 77 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VScoreColorMap.hh
References fPSName.
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
void G4VScoreColorMap::SetPSUnit (G4String & unit) inline
Definition at line 76 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VScoreColorMap.hh
References fPSUnit.
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), and G4ScoringBox::DrawColumn().
Member Data Documentation
G4double G4VScoreColorMap::fMaxVal protected
Definition at line 83 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 83 of file G4VScoreColorMap.hh
Referenced by G4ScoreLogColorMap::DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), G4ScoreLogColorMap::GetMapColor(), G4DefaultLinearColorMap::GetMapColor(), GetMax(), and SetMinMax().
G4double G4VScoreColorMap::fMinVal protected
Definition at line 82 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VScoreColorMap.hh
Referenced by G4ScoreLogColorMap::DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), G4ScoreLogColorMap::GetMapColor(), G4DefaultLinearColorMap::GetMapColor(), GetMin(), and SetMinMax().
G4String G4VScoreColorMap::fName protected
Definition at line 80 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VScoreColorMap.hh
Referenced by GetName().
G4String G4VScoreColorMap::fPSName protected
Definition at line 86 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VScoreColorMap.hh
Referenced by G4ScoreLogColorMap::DrawColorChartText(), DrawColorChartText(), and SetPSName().
G4String G4VScoreColorMap::fPSUnit protected
Definition at line 85 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VScoreColorMap.hh
Referenced by G4ScoreLogColorMap::DrawColorChartText(), DrawColorChartText(), and SetPSUnit().
G4VVisManager* G4VScoreColorMap::fVisManager protected
Definition at line 84 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VScoreColorMap.hh
Referenced by DrawColorChart(), G4ScoreLogColorMap::DrawColorChartBar(), DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), and DrawColorChartText().
G4bool G4VScoreColorMap::ifFloat protected
Definition at line 81 of file G4VScoreColorMap.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VScoreColorMap.hh
Referenced by IfFloatMinMax(), and SetFloatingMinMax().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoreColorMap.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4VScoreColorMap.cc