ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/MedicalBeam/pyMedicalBeam.cc File Reference
pyMedicalBeam.cc File Reference
#include <boost/python.hpp>
#include "MedicalBeam.hh"
#include "G4ParticleTable.hh"
#include "G4RunManager.hh"
Namespaces
namespace pyMedicalBeam
Functions
MedicalBeam * pyMedicalBeam::Construct ()
void pyMedicalBeam::SetParticleByName (MedicalBeam *beam, const std::string &pname)
std::string pyMedicalBeam::GetParticleByName (MedicalBeam *beam)
void pyMedicalBeam::f_SetFieldXY (MedicalBeam *beam, const list &listXY)
list pyMedicalBeam::f_GetFieldXY (MedicalBeam *beam)
BOOST_PYTHON_MODULE (_MedicalBeam)
Function Documentation
BOOST_PYTHON_MODULE (_MedicalBeam)
Definition at line 113 of file pyMedicalBeam.cc.
View newest version in sPHENIX GitHub at line 113 of file pyMedicalBeam.cc
References MedicalBeam::CIRCLE, pyEMSTDpl::Construct(), pyMedicalBeam::f_GetFieldXY(), pyMedicalBeam::f_SetFieldXY(), MedicalBeam::GetFieldR(), MedicalBeam::GetFieldShape(), MedicalBeam::GetFieldX(), MedicalBeam::GetFieldY(), MedicalBeam::GetKineticE(), pyG4ParticleGun::GetParticleByName(), MedicalBeam::GetSourcePosition(), MedicalBeam::GetSSD(), MedicalBeam::SetFieldR(), MedicalBeam::SetFieldShape(), MedicalBeam::SetKineticE(), pyG4ParticleGun::SetParticleByName(), MedicalBeam::SetSourcePosition(), MedicalBeam::SetSSD(), and MedicalBeam::SQUARE.