ECCE @ EIC Software: G4XAnnihilationChannel Class Reference
G4XAnnihilationChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XAnnihilationChannel.hh>
Public Member Functions
G4XAnnihilationChannel ()
G4XAnnihilationChannel (const G4ParticleDefinition *resDefinition, const G4ResonanceWidth &resWidths, const G4ResonancePartialWidth &resPartWidths, const G4String &partWidthLabel)
virtual ~G4XAnnihilationChannel ()
G4bool operator== (const G4XAnnihilationChannel &right) const
G4bool operator!= (const G4XAnnihilationChannel &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual G4String Name () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Private Member Functions
G4XAnnihilationChannel (const G4XAnnihilationChannel &right)
const G4XAnnihilationChannel & operator= (const G4XAnnihilationChannel &right)
G4double Branch (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double VariableWidth (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double VariablePartialWidth (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double NormalizedClebsch (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Attributes
G4double lowLimit
G4double highLimit
G4Clebsch clebsch
G4ResonanceNames theNames
G4PhysicsVector * widthTable
G4PhysicsVector * partWidthTable
const G4ParticleDefinition * resonance
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 46 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 46 of file G4XAnnihilationChannel.hh
Constructor & Destructor Documentation
G4XAnnihilationChannel::G4XAnnihilationChannel ()
Definition at line 37 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 37 of file G4XAnnihilationChannel.cc
References DBL_MAX, highLimit, lowLimit, partWidthTable, and widthTable.
G4XAnnihilationChannel::G4XAnnihilationChannel (const G4ParticleDefinition * resDefinition, const G4ResonanceWidth & resWidths, const G4ResonancePartialWidth & resPartWidths, const G4String & partWidthLabel)
Definition at line 47 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4XAnnihilationChannel.cc
References DBL_MAX, G4ParticleDefinition::GetParticleName(), highLimit, lowLimit, G4ResonancePartialWidth::MassDependentWidth(), G4ResonanceWidth::MassDependentWidth(), partWidthTable, resonance, G4ResonanceNames::ShortName(), theNames, and widthTable.
G4XAnnihilationChannel::~G4XAnnihilationChannel () virtual
Definition at line 70 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4XAnnihilationChannel.cc
References partWidthTable, and widthTable.
G4XAnnihilationChannel::G4XAnnihilationChannel (const G4XAnnihilationChannel & right) private
Member Function Documentation
G4double G4XAnnihilationChannel::Branch (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const private
Definition at line 152 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 152 of file G4XAnnihilationChannel.cc
References VariablePartialWidth(), VariableWidth(), and w.
Referenced by CrossSection().
G4double G4XAnnihilationChannel::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 91 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 91 of file G4XAnnihilationChannel.cc
References Branch(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc_squared, NormalizedClebsch(), pi, resonance, S(), VariableWidth(), and width.
virtual const G4CrossSectionVector* G4XAnnihilationChannel::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 64 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4XAnnihilationChannel.hh
G4bool G4XAnnihilationChannel::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 144 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 144 of file G4XAnnihilationChannel.cc
References highLimit, G4VCrossSectionSource::InLimits(), and lowLimit.
G4String G4XAnnihilationChannel::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 136 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 136 of file G4XAnnihilationChannel.cc
G4double G4XAnnihilationChannel::NormalizedClebsch (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const private
Definition at line 199 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 199 of file G4XAnnihilationChannel.cc
References clebsch, G4ParticleDefinition::GetAntiQuarkContent(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetQuarkContent(), G4Clebsch::NormalizedClebschGordan(), and resonance.
Referenced by CrossSection().
G4bool G4XAnnihilationChannel::operator!= (const G4XAnnihilationChannel & right) const
Definition at line 85 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 85 of file G4XAnnihilationChannel.cc
const G4XAnnihilationChannel& G4XAnnihilationChannel::operator= (const G4XAnnihilationChannel & right) private
G4bool G4XAnnihilationChannel::operator== (const G4XAnnihilationChannel & right) const
Definition at line 79 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 79 of file G4XAnnihilationChannel.cc
G4double G4XAnnihilationChannel::VariablePartialWidth (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const private
Definition at line 176 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 176 of file G4XAnnihilationChannel.cc
References G4KineticTrack::Get4Momentum(), G4ParticleDefinition::GetPDGWidth(), G4PhysicsVector::GetValue(), partWidthTable, resonance, and width.
Referenced by Branch().
G4double G4XAnnihilationChannel::VariableWidth (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const private
Definition at line 160 of file G4XAnnihilationChannel.cc.
View newest version in sPHENIX GitHub at line 160 of file G4XAnnihilationChannel.cc
References G4KineticTrack::Get4Momentum(), G4ParticleDefinition::GetPDGWidth(), G4PhysicsVector::GetValue(), resonance, width, and widthTable.
Referenced by Branch(), and CrossSection().
Member Data Documentation
G4Clebsch G4XAnnihilationChannel::clebsch private
Definition at line 93 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 93 of file G4XAnnihilationChannel.hh
Referenced by NormalizedClebsch().
G4double G4XAnnihilationChannel::highLimit private
Definition at line 91 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4XAnnihilationChannel.hh
Referenced by G4XAnnihilationChannel(), and IsValid().
G4double G4XAnnihilationChannel::lowLimit private
Definition at line 90 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4XAnnihilationChannel.hh
Referenced by G4XAnnihilationChannel(), and IsValid().
G4PhysicsVector* G4XAnnihilationChannel::partWidthTable private
Definition at line 98 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4XAnnihilationChannel.hh
Referenced by G4XAnnihilationChannel(), VariablePartialWidth(), and ~G4XAnnihilationChannel().
const G4ParticleDefinition* G4XAnnihilationChannel::resonance private
Definition at line 101 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4XAnnihilationChannel.hh
Referenced by CrossSection(), G4XAnnihilationChannel(), NormalizedClebsch(), VariablePartialWidth(), and VariableWidth().
G4ResonanceNames G4XAnnihilationChannel::theNames private
Definition at line 94 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4XAnnihilationChannel.hh
Referenced by G4XAnnihilationChannel().
G4PhysicsVector* G4XAnnihilationChannel::widthTable private
Definition at line 97 of file G4XAnnihilationChannel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4XAnnihilationChannel.hh
Referenced by G4XAnnihilationChannel(), VariableWidth(), and ~G4XAnnihilationChannel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XAnnihilationChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XAnnihilationChannel.cc