ECCE @ EIC Software: HadrontherapyRBE Class Reference
HadrontherapyRBE Class Reference
Main class of the RBE calculation.
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyRBE.hh>
Public Types
using array_type = std::valarray< G4double >
Public Member Functions
virtual ~HadrontherapyRBE ()
G4bool IsCalculationEnabled () const
G4bool IsAccumulationEnabled () const
void LoadLEMTable (G4String path)
void SetCellLine (G4String name)
std::tuple< G4double, G4double > GetHitAlphaAndBeta (G4double E, G4int Z)
void SetDoseScale (G4double scale)
void SetCalculationEnabled (G4bool enabled)
void SetAccumulationEnabled (G4bool accumulate)
void SetVerboseLevel (G4int level)
G4int GetVerboseLevel () const
void ComputeAlphaAndBeta ()
void ComputeRBE ()
void SetAlphaNumerator (const array_type alpha)
void SetBetaNumerator (const array_type beta)
void SetEnergyDeposit (const array_type eDep)
void SetDenominator (const array_type denom)
void AddAlphaNumerator (const array_type alpha)
void AddBetaNumerator (const array_type beta)
void AddEnergyDeposit (const array_type eDep)
void AddDenominator (const array_type denom)
void Reset ()
void StoreAlphaAndBeta ()
void StoreRBE ()
size_t GetNumberOfVoxelsAlongX () const
size_t GetNumberOfVoxelsAlongY () const
size_t GetNumberOfVoxelsAlongZ () const
void PrintParameters ()
Static Public Member Functions
static HadrontherapyRBE * CreateInstance (G4int nX, G4int nY, G4int nZ, G4double massOfVoxel)
static HadrontherapyRBE * GetInstance ()
Protected Member Functions
G4int Index (G4int i, G4int j, G4int k)
void CreateMessenger ()
Private Types
using vector_type = std::map< G4int, std::vector< G4double >>
Private Member Functions
HadrontherapyRBE (G4int numberOfVoxelX, G4int numberOfVoxelY, G4int numberOfVoxelZ, G4double massOfVoxel)
Private Attributes
G4GenericMessenger * fMessenger
G4Pow * g4pow = G4Pow::GetInstance()
G4int fVerboseLevel { 1 }
G4double fAlphaX { 0.0 }
G4double fBetaX { 0.0 }
G4double fDoseCut { 0.0 }
G4double fDoseScale { 1.0 }
G4String fAlphaBetaPath { "AlphaAndBeta.out" }
G4String fRBEPath { "RBE.out" }
G4int fNumberOfVoxelsAlongX
G4int fNumberOfVoxelsAlongY
G4int fNumberOfVoxelsAlongZ
G4int fNumberOfVoxels
G4double fMassOfVoxel
G4double * x
G4bool fCalculationEnabled { false }
G4bool fAccumulate { false }
array_type fAlpha
array_type fBeta
array_type fDose
array_type fAlphaNumerator
array_type fBetaNumerator
array_type fDenominator
array_type fLnS
array_type fSurvival
array_type fDoseX
array_type fRBE
std::map< G4String, vector_type > fTablesEnergy
std::map< G4String, vector_type > fTablesAlpha
std::map< G4String, vector_type > fTablesBeta
std::map< G4String, G4double > fTablesAlphaX
std::map< G4String, G4double > fTablesBetaX
std::map< G4String, G4double > fTablesDoseCut
G4String fActiveCellLine = ""
vector_type * fActiveTableEnergy { nullptr }
vector_type * fActiveTableAlpha { nullptr }
vector_type * fActiveTableBeta { nullptr }
std::map< G4int, G4double > fMaxEnergies
std::map< G4int, G4double > fMinEnergies
G4int fMinZ
G4int fMaxZ
Static Private Attributes
static HadrontherapyRBE * instance = nullptr
Detailed Description
Main class of the RBE calculation.
The calculation has to be explicitly enabled (use macro command)
Available macro commands:
/rbe/calculation 0/1 : enable or disable RBE calculation
/rbe/verbose 0/1/2 : level of screen output detail
/rbe/loadLemTable [path] : read a CSV file with alphas, betas, ...
/rbe/cellLine [name] : select one of the cell lines from the data file
/rbe/doseScale [number] : factor to make the survival/RBE calculation correct
/rbe/accumulate 0/1 : enable or disable data summing over multiple runs
/rbe/reset : clear accumulated data back to 0.
Definition at line 56 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 56 of file HadrontherapyRBE.hh
Member Typedef Documentation
using HadrontherapyRBE::array_type = std::valarray<G4double>
Definition at line 90 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 90 of file HadrontherapyRBE.hh
using HadrontherapyRBE::vector_type = std::map<G4int, std::vector<G4double>> private
Definition at line 183 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 183 of file HadrontherapyRBE.hh
Constructor & Destructor Documentation
HadrontherapyRBE::~HadrontherapyRBE () virtual
Definition at line 96 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 96 of file HadrontherapyRBE.cc
References fMessenger, and x.
HadrontherapyRBE::HadrontherapyRBE (G4int numberOfVoxelX, G4int numberOfVoxelY, G4int numberOfVoxelZ, G4double massOfVoxel) private
Definition at line 75 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 75 of file HadrontherapyRBE.cc
References CreateMessenger(), fNumberOfVoxelsAlongX, and x.
Member Function Documentation
void HadrontherapyRBE::AddAlphaNumerator (const array_type alpha)
Definition at line 453 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 453 of file HadrontherapyRBE.cc
References alpha, fAlphaNumerator, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::AddBetaNumerator (const array_type beta)
Definition at line 474 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 474 of file HadrontherapyRBE.cc
References fBetaNumerator, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::AddDenominator (const array_type denom)
Definition at line 414 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 414 of file HadrontherapyRBE.cc
References denom, fDenominator, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::AddEnergyDeposit (const array_type eDep)
Definition at line 504 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 504 of file HadrontherapyRBE.cc
References fDose, fDoseScale, fMassOfVoxel, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::ComputeAlphaAndBeta ()
Definition at line 355 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 355 of file HadrontherapyRBE.cc
References fAlpha, fAlphaNumerator, fBeta, fBetaNumerator, fDenominator, fVerboseLevel, G4cout, G4endl, and gray.
Referenced by StoreAlphaAndBeta().
void HadrontherapyRBE::ComputeRBE ()
Definition at line 368 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 368 of file HadrontherapyRBE.cc
References fAlpha, fAlphaX, fBeta, fBetaX, fDose, fDoseCut, fDoseX, fLnS, fNumberOfVoxels, fRBE, fSurvival, fVerboseLevel, G4cout, G4endl, and smax.
Referenced by StoreRBE().
HadrontherapyRBE * HadrontherapyRBE::CreateInstance (G4int nX, G4int nY, G4int nZ, G4double massOfVoxel) static
Definition at line 68 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 68 of file HadrontherapyRBE.cc
References instance.
Referenced by HadrontherapyDetectorConstruction::UpdateGeometry().
void HadrontherapyRBE::CreateMessenger () protected
Definition at line 584 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 584 of file HadrontherapyRBE.cc
References G4GenericMessenger::DeclareMethod(), fMessenger, G4State_Idle, G4State_PreInit, LoadLEMTable(), Reset(), SetAccumulationEnabled(), SetCalculationEnabled(), SetCellLine(), SetDoseScale(), G4GenericMessenger::Command::SetGuidance(), G4GenericMessenger::SetGuidance(), G4GenericMessenger::Command::SetStates(), G4GenericMessenger::Command::SetToBeBroadcasted(), and SetVerboseLevel().
Referenced by HadrontherapyRBE().
std::tuple< G4double, G4double > HadrontherapyRBE::GetHitAlphaAndBeta (G4double E, G4int Z)
Definition at line 296 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 296 of file HadrontherapyRBE.cc
References alpha, fActiveTableEnergy, FatalException, fMaxEnergies, fMaxZ, fMinEnergies, fMinZ, fVerboseLevel, G4cout, G4endl, G4Exception(), JustWarning, and Z.
Referenced by HadrontherapyRBEAccumulable::Accumulate().
HadrontherapyRBE * HadrontherapyRBE::GetInstance () static
Definition at line 63 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 63 of file HadrontherapyRBE.cc
References instance.
Referenced by HadrontherapyRBEAccumulable::Accumulate(), HadrontherapyRunAction::BeginOfRunAction(), HadrontherapyRunAction::EndOfRunAction(), HadrontherapyRBEAccumulable::GetVerboseLevel(), and HadrontherapyRBEAccumulable::Initialize().
size_t HadrontherapyRBE::GetNumberOfVoxelsAlongX () const inline
Definition at line 117 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 117 of file HadrontherapyRBE.hh
References fNumberOfVoxelsAlongX.
size_t HadrontherapyRBE::GetNumberOfVoxelsAlongY () const inline
Definition at line 118 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 118 of file HadrontherapyRBE.hh
References fNumberOfVoxelsAlongY.
size_t HadrontherapyRBE::GetNumberOfVoxelsAlongZ () const inline
Definition at line 119 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 119 of file HadrontherapyRBE.hh
References fNumberOfVoxelsAlongZ.
G4int HadrontherapyRBE::GetVerboseLevel () const inline
Definition at line 87 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 87 of file HadrontherapyRBE.hh
References fVerboseLevel.
Referenced by HadrontherapyRunAction::BeginOfRunAction(), and HadrontherapyRBEAccumulable::GetVerboseLevel().
G4int HadrontherapyRBE::Index (G4int i, G4int j, G4int k) inline protected
Definition at line 125 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 125 of file HadrontherapyRBE.hh
References fNumberOfVoxelsAlongY, fNumberOfVoxelsAlongZ, and k.
G4bool HadrontherapyRBE::IsAccumulationEnabled () const inline
Definition at line 69 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 69 of file HadrontherapyRBE.hh
References fAccumulate.
Referenced by HadrontherapyRunAction::EndOfRunAction().
G4bool HadrontherapyRBE::IsCalculationEnabled () const inline
Definition at line 66 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 66 of file HadrontherapyRBE.hh
References fCalculationEnabled.
Referenced by HadrontherapyRunAction::BeginOfRunAction(), and HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::LoadLEMTable (G4String path)
Definition at line 139 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 139 of file HadrontherapyRBE.cc
References field_utils::copy(), elements, FatalException, fTablesAlpha, fTablesAlphaX, fTablesBeta, fTablesBetaX, fTablesDoseCut, fTablesEnergy, fVerboseLevel, G4cout, G4endl, G4Exception(), gray, incremental_prev_tag::idx, in, MeV, pos(), and split().
Referenced by CreateMessenger().
void HadrontherapyRBE::PrintParameters ()
Definition at line 102 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 102 of file HadrontherapyRBE.cc
References fActiveCellLine, fAlphaX, fBetaX, fDoseCut, G4cout, G4endl, and gray.
Referenced by HadrontherapyRunAction::BeginOfRunAction().
void HadrontherapyRBE::Reset ()
Definition at line 568 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 568 of file HadrontherapyRBE.cc
References fAlphaNumerator, fBetaNumerator, fDenominator, fDose, fVerboseLevel, G4cout, and G4endl.
Referenced by CreateMessenger(), and SetAccumulationEnabled().
void HadrontherapyRBE::SetAccumulationEnabled (G4bool accumulate)
Definition at line 750 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 750 of file HadrontherapyRBE.cc
References fAccumulate, and Reset().
Referenced by CreateMessenger().
void HadrontherapyRBE::SetAlphaNumerator (const array_type alpha)
Definition at line 435 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 435 of file HadrontherapyRBE.cc
References alpha, fAlphaNumerator, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::SetBetaNumerator (const array_type beta)
Definition at line 444 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 444 of file HadrontherapyRBE.cc
References fBetaNumerator, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::SetCalculationEnabled (G4bool enabled)
Definition at line 745 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 745 of file HadrontherapyRBE.cc
References fCalculationEnabled.
Referenced by CreateMessenger().
void HadrontherapyRBE::SetCellLine (G4String name)
Definition at line 251 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 251 of file HadrontherapyRBE.cc
References fActiveCellLine, fActiveTableAlpha, fActiveTableBeta, fActiveTableEnergy, fAlphaX, FatalException, fBetaX, fDoseCut, fMaxEnergies, fMaxZ, fMinEnergies, fMinZ, fTablesAlpha, fTablesAlphaX, fTablesBeta, fTablesBetaX, fTablesDoseCut, fTablesEnergy, fVerboseLevel, G4cout, G4endl, and G4Exception().
Referenced by CreateMessenger().
void HadrontherapyRBE::SetDenominator (const array_type denom)
Definition at line 405 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 405 of file HadrontherapyRBE.cc
References denom, fDenominator, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::SetDoseScale (G4double scale)
Definition at line 765 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 765 of file HadrontherapyRBE.cc
References fDoseScale, and scale.
Referenced by CreateMessenger().
void HadrontherapyRBE::SetEnergyDeposit (const array_type eDep)
Definition at line 495 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 495 of file HadrontherapyRBE.cc
References fDose, fDoseScale, fMassOfVoxel, fVerboseLevel, G4cout, and G4endl.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::SetVerboseLevel (G4int level) inline
Definition at line 86 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 86 of file HadrontherapyRBE.hh
References fVerboseLevel.
Referenced by CreateMessenger().
void HadrontherapyRBE::StoreAlphaAndBeta ()
Definition at line 524 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 524 of file HadrontherapyRBE.cc
References ComputeAlphaAndBeta(), fAlpha, fAlphaBetaPath, fBeta, fNumberOfVoxelsAlongX, fNumberOfVoxelsAlongY, fNumberOfVoxelsAlongZ, fVerboseLevel, G4cout, G4endl, gray, L, and width.
Referenced by HadrontherapyRunAction::EndOfRunAction().
void HadrontherapyRBE::StoreRBE ()
Definition at line 546 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 546 of file HadrontherapyRBE.cc
References ComputeRBE(), fDose, fDoseX, fLnS, fNumberOfVoxelsAlongX, fNumberOfVoxelsAlongY, fNumberOfVoxelsAlongZ, fRBE, fRBEPath, fSurvival, fVerboseLevel, G4cout, G4endl, gray, and width.
Referenced by HadrontherapyRunAction::EndOfRunAction().
Member Data Documentation
G4bool HadrontherapyRBE::fAccumulate { false } private
Definition at line 165 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 165 of file HadrontherapyRBE.hh
Referenced by IsAccumulationEnabled(), and SetAccumulationEnabled().
G4String HadrontherapyRBE::fActiveCellLine = "" private
Definition at line 194 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 194 of file HadrontherapyRBE.hh
Referenced by PrintParameters(), and SetCellLine().
vector_type* HadrontherapyRBE::fActiveTableAlpha { nullptr } private
Definition at line 197 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 197 of file HadrontherapyRBE.hh
Referenced by SetCellLine().
vector_type* HadrontherapyRBE::fActiveTableBeta { nullptr } private
Definition at line 198 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 198 of file HadrontherapyRBE.hh
Referenced by SetCellLine().
vector_type* HadrontherapyRBE::fActiveTableEnergy { nullptr } private
Definition at line 195 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 195 of file HadrontherapyRBE.hh
Referenced by GetHitAlphaAndBeta(), and SetCellLine().
array_type HadrontherapyRBE::fAlpha private
Definition at line 168 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 168 of file HadrontherapyRBE.hh
Referenced by ComputeAlphaAndBeta(), ComputeRBE(), and StoreAlphaAndBeta().
G4String HadrontherapyRBE::fAlphaBetaPath { "AlphaAndBeta.out" } private
Definition at line 154 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 154 of file HadrontherapyRBE.hh
Referenced by StoreAlphaAndBeta().
array_type HadrontherapyRBE::fAlphaNumerator private
Definition at line 172 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 172 of file HadrontherapyRBE.hh
Referenced by AddAlphaNumerator(), ComputeAlphaAndBeta(), Reset(), and SetAlphaNumerator().
G4double HadrontherapyRBE::fAlphaX { 0.0 } private
Definition at line 148 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 148 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), PrintParameters(), and SetCellLine().
array_type HadrontherapyRBE::fBeta private
Definition at line 169 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 169 of file HadrontherapyRBE.hh
Referenced by ComputeAlphaAndBeta(), ComputeRBE(), and StoreAlphaAndBeta().
array_type HadrontherapyRBE::fBetaNumerator private
Definition at line 173 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 173 of file HadrontherapyRBE.hh
Referenced by AddBetaNumerator(), ComputeAlphaAndBeta(), Reset(), and SetBetaNumerator().
G4double HadrontherapyRBE::fBetaX { 0.0 } private
Definition at line 149 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 149 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), PrintParameters(), and SetCellLine().
G4bool HadrontherapyRBE::fCalculationEnabled { false } private
Definition at line 164 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 164 of file HadrontherapyRBE.hh
Referenced by IsCalculationEnabled(), and SetCalculationEnabled().
array_type HadrontherapyRBE::fDenominator private
Definition at line 174 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 174 of file HadrontherapyRBE.hh
Referenced by AddDenominator(), ComputeAlphaAndBeta(), Reset(), and SetDenominator().
array_type HadrontherapyRBE::fDose private
Definition at line 170 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 170 of file HadrontherapyRBE.hh
Referenced by AddEnergyDeposit(), ComputeRBE(), Reset(), SetEnergyDeposit(), and StoreRBE().
G4double HadrontherapyRBE::fDoseCut { 0.0 } private
Definition at line 150 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 150 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), PrintParameters(), and SetCellLine().
G4double HadrontherapyRBE::fDoseScale { 1.0 } private
Definition at line 151 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 151 of file HadrontherapyRBE.hh
Referenced by AddEnergyDeposit(), SetDoseScale(), and SetEnergyDeposit().
array_type HadrontherapyRBE::fDoseX private
Definition at line 179 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 179 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), and StoreRBE().
array_type HadrontherapyRBE::fLnS private
Definition at line 177 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 177 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), and StoreRBE().
G4double HadrontherapyRBE::fMassOfVoxel private
Definition at line 160 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 160 of file HadrontherapyRBE.hh
Referenced by AddEnergyDeposit(), and SetEnergyDeposit().
std::map<G4int, G4double> HadrontherapyRBE::fMaxEnergies private
Definition at line 199 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 199 of file HadrontherapyRBE.hh
Referenced by GetHitAlphaAndBeta(), and SetCellLine().
G4int HadrontherapyRBE::fMaxZ private
Definition at line 202 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 202 of file HadrontherapyRBE.hh
Referenced by GetHitAlphaAndBeta(), and SetCellLine().
G4GenericMessenger* HadrontherapyRBE::fMessenger private
Definition at line 141 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 141 of file HadrontherapyRBE.hh
Referenced by CreateMessenger(), and ~HadrontherapyRBE().
std::map<G4int, G4double> HadrontherapyRBE::fMinEnergies private
Definition at line 200 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 200 of file HadrontherapyRBE.hh
Referenced by GetHitAlphaAndBeta(), and SetCellLine().
G4int HadrontherapyRBE::fMinZ private
Definition at line 201 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 201 of file HadrontherapyRBE.hh
Referenced by GetHitAlphaAndBeta(), and SetCellLine().
G4int HadrontherapyRBE::fNumberOfVoxels private
Definition at line 159 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 159 of file HadrontherapyRBE.hh
Referenced by ComputeRBE().
G4int HadrontherapyRBE::fNumberOfVoxelsAlongX private
Definition at line 158 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 158 of file HadrontherapyRBE.hh
Referenced by GetNumberOfVoxelsAlongX(), HadrontherapyRBE(), StoreAlphaAndBeta(), and StoreRBE().
G4int HadrontherapyRBE::fNumberOfVoxelsAlongY private
Definition at line 158 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 158 of file HadrontherapyRBE.hh
Referenced by GetNumberOfVoxelsAlongY(), Index(), StoreAlphaAndBeta(), and StoreRBE().
G4int HadrontherapyRBE::fNumberOfVoxelsAlongZ private
Definition at line 158 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 158 of file HadrontherapyRBE.hh
Referenced by GetNumberOfVoxelsAlongZ(), Index(), StoreAlphaAndBeta(), and StoreRBE().
array_type HadrontherapyRBE::fRBE private
Definition at line 180 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 180 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), and StoreRBE().
G4String HadrontherapyRBE::fRBEPath { "RBE.out" } private
Definition at line 155 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 155 of file HadrontherapyRBE.hh
Referenced by StoreRBE().
array_type HadrontherapyRBE::fSurvival private
Definition at line 178 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 178 of file HadrontherapyRBE.hh
Referenced by ComputeRBE(), and StoreRBE().
std::map<G4String, vector_type> HadrontherapyRBE::fTablesAlpha private
Definition at line 186 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 186 of file HadrontherapyRBE.hh
Referenced by LoadLEMTable(), and SetCellLine().
std::map<G4String, G4double> HadrontherapyRBE::fTablesAlphaX private
Definition at line 188 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 188 of file HadrontherapyRBE.hh
Referenced by LoadLEMTable(), and SetCellLine().
std::map<G4String, vector_type> HadrontherapyRBE::fTablesBeta private
Definition at line 187 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 187 of file HadrontherapyRBE.hh
Referenced by LoadLEMTable(), and SetCellLine().
std::map<G4String, G4double> HadrontherapyRBE::fTablesBetaX private
Definition at line 189 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 189 of file HadrontherapyRBE.hh
Referenced by LoadLEMTable(), and SetCellLine().
std::map<G4String, G4double> HadrontherapyRBE::fTablesDoseCut private
Definition at line 190 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 190 of file HadrontherapyRBE.hh
Referenced by LoadLEMTable(), and SetCellLine().
std::map<G4String, vector_type> HadrontherapyRBE::fTablesEnergy private
Definition at line 184 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 184 of file HadrontherapyRBE.hh
Referenced by LoadLEMTable(), and SetCellLine().
G4int HadrontherapyRBE::fVerboseLevel { 1 } private
Definition at line 145 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 145 of file HadrontherapyRBE.hh
Referenced by AddAlphaNumerator(), AddBetaNumerator(), AddDenominator(), AddEnergyDeposit(), ComputeAlphaAndBeta(), ComputeRBE(), GetHitAlphaAndBeta(), GetVerboseLevel(), LoadLEMTable(), Reset(), SetAlphaNumerator(), SetBetaNumerator(), SetCellLine(), SetDenominator(), SetEnergyDeposit(), SetVerboseLevel(), StoreAlphaAndBeta(), and StoreRBE().
G4Pow* HadrontherapyRBE::g4pow = G4Pow::GetInstance() private
Definition at line 142 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 142 of file HadrontherapyRBE.hh
HadrontherapyRBE * HadrontherapyRBE::instance = nullptr static private
Definition at line 144 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 144 of file HadrontherapyRBE.hh
G4double* HadrontherapyRBE::x private
Definition at line 162 of file HadrontherapyRBE.hh.
View newest version in sPHENIX GitHub at line 162 of file HadrontherapyRBE.hh
Referenced by HadrontherapyRBE(), and ~HadrontherapyRBE().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyRBE.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyRBE.cc