ECCE @ EIC Software: RE01Trajectory Class Reference
RE01Trajectory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01Trajectory.hh>
Public Member Functions
RE01Trajectory (const G4Track *aTrack)
virtual ~RE01Trajectory ()
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void DrawTrajectory () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
virtual void AppendStep (const G4Step *aStep)
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
void * operator new (size_t)
void operator delete (void *)
int operator== (const RE01Trajectory &right) const
virtual G4int GetTrackID () const
virtual G4int GetParentID () const
virtual G4String GetParticleName () const
virtual G4double GetCharge () const
virtual G4int GetPDGEncoding () const
virtual G4ThreeVector GetInitialMomentum () const
virtual int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
Private Attributes
RE01TrajectoryPointContainer * fPositionRecord
G4int fTrackID
G4int fParentID
G4int fTrackStatus
G4ParticleDefinition * fParticleDefinition
G4String fParticleName
G4double fPDGCharge
G4int fPDGEncoding
G4ThreeVector fMomentum
G4ThreeVector fVertexPosition
G4double fGlobalTime
Detailed Description
Definition at line 53 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 53 of file RE01Trajectory.hh
Constructor & Destructor Documentation
RE01Trajectory::RE01Trajectory (const G4Track * aTrack)
Definition at line 52 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 52 of file RE01Trajectory.cc
References DBL_MAX, fGlobalTime, fMomentum, fParentID, fParticleDefinition, fParticleName, fPDGCharge, fPDGEncoding, fPositionRecord, fTrackID, fTrackStatus, fVertexPosition, G4PrimaryParticle::GetCharge(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4PrimaryParticle::GetG4code(), G4Track::GetGlobalTime(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4PrimaryParticle::GetPDGcode(), G4ParticleDefinition::GetPDGEncoding(), G4Track::GetPosition(), G4DynamicParticle::GetPrimaryParticle(), RE01TrackInformation::GetSourceTrackID(), G4Track::GetTrackID(), RE01TrackInformation::GetTrackingStatus(), G4Track::GetUserInformation(), and G4InuclParticleNames::pp.
RE01Trajectory::~RE01Trajectory () virtual
Definition at line 92 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 92 of file RE01Trajectory.cc
References fPositionRecord.
Member Function Documentation
void RE01Trajectory::AppendStep (const G4Step * aStep) virtual
Implements G4VTrajectory.
Definition at line 253 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 253 of file RE01Trajectory.cc
References fPositionRecord, G4StepPoint::GetPosition(), and G4Step::GetPostStepPoint().
std::vector< G4AttValue > * RE01Trajectory::CreateAttValues () const virtual
Reimplemented from G4VTrajectory.
Definition at line 216 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 216 of file RE01Trajectory.cc
References G4UIcommand::ConvertToString(), fMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fTrackID, fTrackStatus, fVertexPosition, G4BestUnit, GetPointEntries(), CLHEP::Hep3Vector::mag(), and Acts::Test::values.
void RE01Trajectory::DrawTrajectory () const virtual
Reimplemented from G4VTrajectory.
Definition at line 126 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 126 of file RE01Trajectory.cc
References G4VVisManager::Draw(), G4Electron::ElectronDefinition(), fParticleDefinition, fPDGCharge, fPositionRecord, G4Gamma::GammaDefinition(), G4VVisManager::GetConcreteInstance(), G4ParticleDefinition::GetParticleType(), G4TrajectoryPoint::GetPosition(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), pos(), G4Positron::PositronDefinition(), and G4Visible::SetVisAttributes().
const std::map< G4String, G4AttDef > * RE01Trajectory::GetAttDefs () const virtual
Reimplemented from G4VTrajectory.
Definition at line 170 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 170 of file RE01Trajectory.cc
References G4AttDefStore::GetInstance(), pdg, pid, and G4InuclParticleNames::pn.
virtual G4double RE01Trajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 74 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 74 of file RE01Trajectory.hh
References fPDGCharge.
virtual G4ThreeVector RE01Trajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 76 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 76 of file RE01Trajectory.hh
References fMomentum.
virtual G4int RE01Trajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 72 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 72 of file RE01Trajectory.hh
References fParentID.
virtual G4String RE01Trajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 73 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 73 of file RE01Trajectory.hh
References fParticleName.
virtual G4int RE01Trajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 75 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 75 of file RE01Trajectory.hh
References fPDGEncoding.
virtual G4VTrajectoryPoint* RE01Trajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Definition at line 78 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 78 of file RE01Trajectory.hh
References fPositionRecord.
virtual int RE01Trajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Definition at line 77 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 77 of file RE01Trajectory.hh
References fPositionRecord.
Referenced by CreateAttValues(), and MergeTrajectory().
virtual G4int RE01Trajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 71 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 71 of file RE01Trajectory.hh
References fTrackID.
void RE01Trajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Definition at line 260 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 260 of file RE01Trajectory.cc
References fPositionRecord, and GetPointEntries().
void RE01Trajectory::operator delete (void * aTrajectory) inline
Definition at line 105 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 105 of file RE01Trajectory.hh
References myTrajectoryAllocator.
void * RE01Trajectory::operator new (size_t) inline
Definition at line 98 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 98 of file RE01Trajectory.hh
References myTrajectoryAllocator.
int RE01Trajectory::operator== (const RE01Trajectory & right) const inline
Definition at line 68 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 68 of file RE01Trajectory.hh
void RE01Trajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4VTrajectory.
Definition at line 104 of file RE01Trajectory.cc.
View newest version in sPHENIX GitHub at line 104 of file RE01Trajectory.cc
References fGlobalTime, fMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fPositionRecord, fTrackID, fTrackStatus, fVertexPosition, G4BestUnit, G4endl, and G4TrajectoryPoint::GetPosition().
Referenced by RE01EventAction::EndOfEventAction().
Member Data Documentation
G4double RE01Trajectory::fGlobalTime private
Definition at line 92 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 92 of file RE01Trajectory.hh
Referenced by RE01Trajectory(), and ShowTrajectory().
G4ThreeVector RE01Trajectory::fMomentum private
Definition at line 90 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 90 of file RE01Trajectory.hh
Referenced by CreateAttValues(), GetInitialMomentum(), RE01Trajectory(), and ShowTrajectory().
G4int RE01Trajectory::fParentID private
Definition at line 84 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 84 of file RE01Trajectory.hh
Referenced by CreateAttValues(), GetParentID(), RE01Trajectory(), and ShowTrajectory().
G4ParticleDefinition* RE01Trajectory::fParticleDefinition private
Definition at line 86 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 86 of file RE01Trajectory.hh
Referenced by DrawTrajectory(), and RE01Trajectory().
G4String RE01Trajectory::fParticleName private
Definition at line 87 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 87 of file RE01Trajectory.hh
Referenced by CreateAttValues(), GetParticleName(), RE01Trajectory(), and ShowTrajectory().
G4double RE01Trajectory::fPDGCharge private
Definition at line 88 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 88 of file RE01Trajectory.hh
Referenced by CreateAttValues(), DrawTrajectory(), GetCharge(), RE01Trajectory(), and ShowTrajectory().
G4int RE01Trajectory::fPDGEncoding private
Definition at line 89 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 89 of file RE01Trajectory.hh
Referenced by CreateAttValues(), GetPDGEncoding(), RE01Trajectory(), and ShowTrajectory().
RE01TrajectoryPointContainer* RE01Trajectory::fPositionRecord private
Definition at line 82 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 82 of file RE01Trajectory.hh
Referenced by AppendStep(), DrawTrajectory(), GetPoint(), GetPointEntries(), MergeTrajectory(), RE01Trajectory(), ShowTrajectory(), and ~RE01Trajectory().
G4int RE01Trajectory::fTrackID private
Definition at line 83 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 83 of file RE01Trajectory.hh
Referenced by CreateAttValues(), GetTrackID(), RE01Trajectory(), and ShowTrajectory().
G4int RE01Trajectory::fTrackStatus private
Definition at line 85 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 85 of file RE01Trajectory.hh
Referenced by CreateAttValues(), RE01Trajectory(), and ShowTrajectory().
G4ThreeVector RE01Trajectory::fVertexPosition private
Definition at line 91 of file RE01Trajectory.hh.
View newest version in sPHENIX GitHub at line 91 of file RE01Trajectory.hh
Referenced by CreateAttValues(), RE01Trajectory(), and ShowTrajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01Trajectory.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01Trajectory.cc