ECCE @ EIC Software: G4VEmModel Class Reference
G4VEmModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmModel.hh>
Inherited by G4AtimaEnergyLossModel, G4BetheBlochModel, G4BetheHeitlerModel, G4BoldyshevTripletModel, G4BraggIonModel, G4BraggModel, G4DNABornExcitationModel1, G4DNABornExcitationModel2, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNAChampionElasticModel, G4DNACPA100ElasticModel, G4DNACPA100ExcitationModel, G4DNACPA100IonisationModel, G4DNADingfelderChargeDecreaseModel, G4DNADingfelderChargeIncreaseModel, G4DNAELSEPAElasticModel, G4DNAEmfietzoglouExcitationModel, G4DNAEmfietzoglouIonisationModel, G4DNAIonElasticModel, G4DNAMeltonAttachmentModel, G4DNAMillerGreenExcitationModel, G4DNAModelInterface, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4DNASancheExcitationModel, G4DNAScreenedRutherfordElasticModel, G4DNATransformElectronModel, G4DNAUeharaScreenedRutherfordElasticModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, G4eCoulombScatteringModel, G4eeToHadronsModel, G4eeToHadronsMultiModel, G4eeToTwoGammaModel, G4EmMultiModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4eSingleCoulombScatteringModel, G4hCoulombScatteringModel, G4ICRU49NuclearStoppingModel, G4ICRU73QOModel, G4IonCoulombScatteringModel, G4IonParametrisedLossModel, G4JAEAElasticScatteringModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4LindhardSorensenIonModel, G4LivermoreComptonModel, G4LivermoreComptonModifiedModel, G4LivermoreGammaConversionModel, G4LivermoreGammaConversionModelRC, G4LivermoreIonisationModel, G4LivermoreNuclearGammaConversionModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedComptonModel, G4LivermorePolarizedGammaConversionModel, G4LivermorePolarizedPhotoElectricGDModel, G4LivermorePolarizedPhotoElectricModel, G4LivermorePolarizedRayleighModel, G4LivermoreRayleighModel, G4LowEPComptonModel, G4LowEPPolarizedComptonModel, G4MicroElecElasticModel, G4MicroElecInelasticModel, G4MollerBhabhaModel, G4mplIonisationModel, G4mplIonisationWithDeltaModel, G4MuBetheBlochModel, G4MuBremsstrahlungModel, G4MuElecElasticModel, G4MuElecInelasticModel, G4MuPairProductionModel, G4PAIModel, G4PAIPhotModel, G4PairProductionRelModel, G4PEEffectFluoModel, G4PenelopeAnnihilationModel, G4PenelopeBremsstrahlungModel, G4PenelopeComptonModel, G4PenelopeGammaConversionModel, G4PenelopeIonisationModel, G4PenelopePhotoElectricModel, G4PenelopeRayleighModel, G4TDNAOneStepThermalizationModel< MODEL >, G4VLEPTSModel, G4VMscModel, and G4XrayRayleighModel.
Public Member Functions
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)=0
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin=0.0, G4double tmax=DBL_MAX)=0
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4VEmModel & operator= (const G4VEmModel &right)
G4VEmModel (const G4VEmModel &)
Private Attributes
G4VEmFluctuationModel * flucModel
G4VEmAngularDistribution * anglModel
const G4String name
G4double lowLimit
G4double highLimit
G4double eMinActive
G4double eMaxActive
G4double polarAngleLimit
G4double secondaryThreshold
G4bool theLPMflag
G4bool flagDeexcitation
G4bool flagForceBuildTable
G4bool isMaster
G4bool localTable
G4bool localElmSelectors
G4bool useAngularGenerator
G4bool useBaseMaterials
G4bool isLocked
G4int nSelectors
std::vector
< G4EmElementSelector * > * elmSelectors
G4LossTableManager * fEmManager
const G4MaterialCutsCouple * fCurrentCouple
const G4Element * fCurrentElement
const G4Isotope * fCurrentIsotope
G4VEmModel * fTripletModel
G4int nsec
std::vector< G4double > xsec
Detailed Description
Definition at line 102 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VEmModel.hh
Constructor & Destructor Documentation
G4VEmModel::G4VEmModel (const G4String & nam) explicit
Definition at line 65 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VEmModel.cc
References elmSelectors, fEmManager, G4LossTableBuilder::GetCoupleIndexes(), G4LossTableBuilder::GetDensityFactors(), G4LossTableManager::GetTableBuilder(), G4LossTableManager::Instance(), isLocked, localElmSelectors, localTable, nsec, nSelectors, G4LossTableManager::Register(), theDensityFactor, theDensityIdx, useAngularGenerator, useBaseMaterials, and xsec.
G4VEmModel::~G4VEmModel () virtual
Definition at line 94 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 94 of file G4VEmModel.cc
References anglModel, G4PhysicsTable::clearAndDestroy(), G4LossTableManager::DeRegister(), elmSelectors, fElementData, fEmManager, isMaster, localElmSelectors, localTable, nSelectors, and xSectionTable.
G4VEmModel::G4VEmModel (const G4VEmModel &) private
Member Function Documentation
G4double G4VEmModel::ChargeSquareRatio (const G4Track & track) virtual
Reimplemented in G4BraggIonGasModel, and G4BetheBlochIonGasModel.
Definition at line 383 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 383 of file G4VEmModel.cc
References GetChargeSquareRatio(), G4Track::GetKineticEnergy(), G4Track::GetMaterial(), and G4Track::GetParticleDefinition().
Referenced by G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength().
G4double G4VEmModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0., G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Reimplemented in G4LowEPPolarizedComptonModel, G4IonParametrisedLossModel, G4LowEPComptonModel, G4eCoulombScatteringModel, G4MuBetheBlochModel, G4MuBremsstrahlungModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4UrbanAdjointMscModel, G4MuPairProductionModel, G4PenelopeComptonModel, G4UrbanMscModel, G4BetheBlochModel, G4IonCoulombScatteringModel, G4PairProductionRelModel, G4eeToHadronsMultiModel, G4PenelopeIonisationModel, G4eSingleCoulombScatteringModel, G4hCoulombScatteringModel, G4LindhardSorensenIonModel, G4WentzelVIModel, G4mplIonisationWithDeltaModel, G4eBremParametrizedModel, G4MollerBhabhaModel, G4AtimaEnergyLossModel, G4eBremsstrahlungRelModel, G4EmMultiModel, G4WentzelVIRelModel, G4eeToHadronsModel, G4PenelopeBremsstrahlungModel, G4BetheHeitlerModel, G4eeToTwoGammaModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4LDMBremModel, G4PenelopePhotoElectricModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4JAEAElasticScatteringModel, G4LivermoreIonisationModel, G4PenelopeRayleighModel, G4LivermorePolarizedComptonModel, G4PenelopeGammaConversionModel, G4PolarizedComptonModel, G4PEEffectFluoModel, G4LivermorePhotoElectricModel, G4PenelopeAnnihilationModel, G4LivermorePolarizedPhotoElectricModel, G4LivermorePolarizedRayleighModel, G4LivermoreComptonModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreComptonModifiedModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, G4LivermoreRayleighModel, G4BoldyshevTripletModel, G4LivermorePolarizedPhotoElectricGDModel, and G4XrayRayleighModel.
Definition at line 359 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 359 of file G4VEmModel.cc
Referenced by G4VEmProcess::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), CrossSectionPerVolume(), G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToScatPrim(), G4AdjointIonIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4VEmAdjointModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4LivermoreGammaConversionModel::InitialiseProbability(), and main().
G4double G4VEmModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * part, const G4Element * elm, G4double kinEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 556 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 556 of file G4VEmModel.hh
References ComputeCrossSectionPerAtom(), G4Element::GetN(), G4Element::GetZ(), and SetCurrentElement().
G4double G4VEmModel::ComputeCrossSectionPerShell (const G4ParticleDefinition * , G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Definition at line 369 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 369 of file G4VEmModel.cc
Referenced by G4EmCalculator::ComputeCrossSectionPerShell().
G4double G4VEmModel::ComputeDEDX (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double cutEnergy = DBL_MAX) inline virtual
Reimplemented in G4EmMultiModel.
Definition at line 518 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 518 of file G4VEmModel.hh
References ComputeDEDXPerVolume(), pBaseMaterial, pFactor, and SetCurrentCouple().
Referenced by G4EmModelManager::ComputeDEDX(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4TablesForExtrapolator::ComputeMuonDEDX(), and G4TablesForExtrapolator::ComputeProtonDEDX().
G4double G4VEmModel::ComputeDEDXPerVolume (const G4Material * , const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy = DBL_MAX) virtual
Reimplemented in G4IonParametrisedLossModel, G4MuBetheBlochModel, G4BraggIonModel, G4BraggModel, G4PenelopeIonisationModel, G4ICRU73QOModel, G4PenelopeBremsstrahlungModel, G4MuBremsstrahlungModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4MuPairProductionModel, G4MollerBhabhaModel, G4AtimaEnergyLossModel, G4PAIModel, G4LivermoreIonisationModel, G4PAIPhotModel, G4eBremParametrizedModel, G4ICRU49NuclearStoppingModel, G4eBremsstrahlungRelModel, G4mplIonisationModel, G4mplIonisationWithDeltaModel, G4BetheBlochNoDeltaModel, G4BraggNoDeltaModel, G4ICRU73NoDeltaModel, G4LDMBremModel, MyMollerBhabhaModel, and MyMollerBhabhaModel.
Definition at line 245 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 245 of file G4VEmModel.cc
Referenced by G4NuclearStopping::AlongStepDoIt(), G4EmCorrections::BuildCorrectionVector(), G4EmCalculator::ComputeDEDX(), ComputeDEDX(), G4NIELCalculator::ComputeNIEL(), G4EmCalculator::ComputeNuclearDEDX(), and main().
G4double G4VEmModel::ComputeMeanFreePath (const G4ParticleDefinition * part, G4double kineticEnergy, const G4Material * material, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 543 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 543 of file G4VEmModel.hh
References Acts::VectorHelpers::cross(), CrossSectionPerVolume(), and DBL_MAX.
Referenced by main().
void G4VEmModel::CorrectionsAlongStep (const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double & eloss, G4double & niel, G4double length) virtual
Reimplemented in G4IonParametrisedLossModel, G4BraggIonModel, G4ICRU73QOModel, G4BetheBlochModel, G4LindhardSorensenIonModel, and G4AtimaEnergyLossModel.
Definition at line 408 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 408 of file G4VEmModel.cc
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4EmCalculator::ComputeDEDX(), and G4EmCalculator::GetDEDX().
G4double G4VEmModel::CrossSection (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 529 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 529 of file G4VEmModel.hh
References CrossSectionPerVolume(), pBaseMaterial, pFactor, and SetCurrentCouple().
Referenced by G4eplusPolarizedAnnihilation::ComputeAsymmetry(), G4ePolarizedIonisation::ComputeAsymmetry(), G4PolarizedCompton::ComputeAsymmetry(), G4EmModelManager::FillLambdaVector(), and G4EmMultiModel::SampleSecondaries().
G4double G4VEmModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Reimplemented in G4GoudsmitSaundersonMscModel, G4TDNAOneStepThermalizationModel< MODEL >, G4IonParametrisedLossModel, G4MuBetheBlochModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4BetheBlochModel, G4PAIModel, G4PenelopeIonisationModel, G4LindhardSorensenIonModel, G4MollerBhabhaModel, G4AtimaEnergyLossModel, G4PAIPhotModel, G4PenelopeBremsstrahlungModel, G4DNAModelInterface, G4eeToTwoGammaModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4eeToHadronsMultiModel, G4MicroElecInelasticModel, G4MuElecInelasticModel, G4PenelopeComptonModel, G4PEEffectFluoModel, G4DNACPA100IonisationModel, G4eeToHadronsModel, G4DNACPA100ExcitationModel, G4DNATransformElectronModel, G4BetheBlochNoDeltaModel, G4BraggNoDeltaModel, G4ICRU73NoDeltaModel, G4DNACPA100ElasticModel, G4DNAEmfietzoglouIonisationModel, G4DNAEmfietzoglouExcitationModel, G4MicroElecElasticModel, G4MuElecElasticModel, G4LivermorePhotoElectricModel, G4DNAIonElasticModel, G4LivermorePolarizedPhotoElectricModel, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4DNABornExcitationModel2, G4DNAMillerGreenExcitationModel, MyKleinNishinaCompton, G4DNAELSEPAElasticModel, G4DNASancheExcitationModel, G4DNABornExcitationModel1, G4DNAChampionElasticModel, G4DNAMeltonAttachmentModel, G4DNADingfelderChargeIncreaseModel, G4DNADingfelderChargeDecreaseModel, G4LEPTSAttachmentModel, G4LEPTSExcitationModel, G4DNAScreenedRutherfordElasticModel, G4LEPTSDissociationModel, G4LEPTSElasticModel, G4LEPTSIonisationModel, G4LEPTSPositroniumModel, G4LEPTSRotExcitationModel, G4LEPTSVibExcitationModel, and G4DNAUeharaScreenedRutherfordElasticModel.
Definition at line 254 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 254 of file G4VEmModel.cc
References ComputeCrossSectionPerAtom(), Acts::VectorHelpers::cross(), emax, CEMC_TOWER::emin, G4Material::GetElement(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), nsec, SetupForMaterial(), and xsec.
Referenced by G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4VEmProcess::ComputeCurrentLambda(), ComputeMeanFreePath(), G4TablesForExtrapolator::ComputeTrasportXS(), CrossSection(), G4DNADummyModel::CrossSectionPerVolume(), MyKleinNishinaCompton::CrossSectionPerVolume(), G4LivermorePolarizedPhotoElectricModel::CrossSectionPerVolume(), G4LivermorePhotoElectricModel::CrossSectionPerVolume(), G4VEmProcess::CrossSectionPerVolume(), G4VEnergyLossProcess::CrossSectionPerVolume(), G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToSecond(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated1(), G4AdjointBremsstrahlungModel::GetAdjointCrossSection(), G4VMscModel::GetTransportMeanFreePath(), SelectRandomAtom(), and Value().
const G4MaterialCutsCouple * G4VEmModel::CurrentCouple () const inline protected
Definition at line 480 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 480 of file G4VEmModel.hh
References fCurrentCouple.
Referenced by G4PEEffectFluoModel::ComputeCrossSectionPerAtom(), G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4EmMultiModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eSingleCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4mplIonisationModel::ComputeDEDXPerVolume(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4PAIPhotModel::ComputeDEDXPerVolume(), G4PAIModel::ComputeDEDXPerVolume(), G4PAIPhotModel::CrossSectionPerVolume(), G4PAIModel::CrossSectionPerVolume(), G4VMscModel::GetTransportMeanFreePath(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4hCoulombScatteringModel::MinPrimaryEnergy(), and G4eCoulombScatteringModel::MinPrimaryEnergy().
G4bool G4VEmModel::DeexcitationFlag () const inline
Definition at line 694 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 694 of file G4VEmModel.hh
References flagDeexcitation.
Referenced by G4EmModelManager::DumpModelList().
void G4VEmModel::DefineForRegion (const G4Region *) virtual
Reimplemented in G4PAIModel, and G4PAIPhotModel.
Definition at line 378 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 378 of file G4VEmModel.cc
Referenced by G4EmModelManager::AddEmModel().
G4bool G4VEmModel::ForceBuildTableFlag () const inline
Definition at line 701 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 701 of file G4VEmModel.hh
References flagForceBuildTable.
Referenced by G4VMscModel::GetParticleChangeForMSC().
G4VEmAngularDistribution * G4VEmModel::GetAngularDistribution () inline
Definition at line 611 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 611 of file G4VEmModel.hh
References anglModel.
Referenced by G4EmModelManager::DumpModelList(), G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheBlochModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), G4BraggModel::Initialise(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
G4double G4VEmModel::GetChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * , G4double kineticEnergy) virtual
Reimplemented in G4IonParametrisedLossModel, G4BraggIonModel, G4BraggModel, G4BetheBlochModel, G4LindhardSorensenIonModel, and G4AtimaEnergyLossModel.
Definition at line 391 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 391 of file G4VEmModel.cc
References G4ParticleDefinition::GetPDGCharge(), and inveplus.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4AdjointCSManager::BuildTotalSigmaTables(), ChargeSquareRatio(), G4EmCalculator::ComputeDEDX(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), and G4EmCalculator::GetDEDX().
G4PhysicsTable * G4VEmModel::GetCrossSectionTable () inline
Definition at line 860 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 860 of file G4VEmModel.hh
References xSectionTable.
Referenced by G4VMultipleScattering::BuildPhysicsTable(), G4EmModelManager::DumpModelList(), G4EmCalculator::FindLambdaTable(), G4WentzelVIModel::Initialise(), and G4VMultipleScattering::StorePhysicsTable().
const G4Element * G4VEmModel::GetCurrentElement () const inline
Definition at line 495 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 495 of file G4VEmModel.hh
References fCurrentElement.
Referenced by G4VEmProcess::GetCurrentElement(), G4VEnergyLossProcess::GetCurrentElement(), G4VEmProcess::GetTargetElement(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SelectedAtom(), G4ePolarizedBremsstrahlungModel::SelectedAtom(), and G4eBremParametrizedModel::SetCurrentElement().
const G4Isotope * G4VEmModel::GetCurrentIsotope () const inline
Definition at line 502 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 502 of file G4VEmModel.hh
References fCurrentIsotope.
Referenced by G4VEmProcess::GetTargetIsotope().
G4ElementData * G4VEmModel::GetElementData () inline
Definition at line 853 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 853 of file G4VEmModel.hh
References fElementData.
Referenced by G4MuPairProductionModel::InitialiseLocal(), G4ePairProduction::StreamProcessInfo(), and G4MuPairProduction::StreamProcessInfo().
std::vector< G4EmElementSelector * > * G4VEmModel::GetElementSelectors () inline
Definition at line 834 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 834 of file G4VEmModel.hh
References elmSelectors.
Referenced by G4LivermoreRayleighModel::InitialiseLocal(), G4LivermoreGammaConversionModelRC::InitialiseLocal(), G4LivermoreNuclearGammaConversionModel::InitialiseLocal(), G4LivermorePolarizedGammaConversionModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseLocal(), G4LivermoreComptonModel::InitialiseLocal(), G4LivermorePolarizedRayleighModel::InitialiseLocal(), G4LivermorePolarizedComptonModel::InitialiseLocal(), G4JAEAElasticScatteringModel::InitialiseLocal(), G4PenelopePhotoElectricModel::InitialiseLocal(), G4KleinNishinaCompton::InitialiseLocal(), G4KleinNishinaModel::InitialiseLocal(), G4eBremParametrizedModel::InitialiseLocal(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4BetheHeitlerModel::InitialiseLocal(), G4PAIPhotModel::InitialiseLocal(), G4eSingleCoulombScatteringModel::InitialiseLocal(), G4hCoulombScatteringModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4PAIModel::InitialiseLocal(), G4MuPairProductionModel::InitialiseLocal(), G4MuBremsstrahlungModel::InitialiseLocal(), G4eCoulombScatteringModel::InitialiseLocal(), G4LowEPComptonModel::InitialiseLocal(), and G4LowEPPolarizedComptonModel::InitialiseLocal().
G4VEmFluctuationModel * G4VEmModel::GetModelOfFluctuations () inline
Definition at line 604 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 604 of file G4VEmModel.hh
References flucModel.
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4IonParametrisedLossModel::CorrectionsAlongStep(), G4BraggModel::GetChargeSquareRatio(), G4VEnergyLossProcess::GetDEDXDispersion(), and G4EmMultiModel::Initialise().
const G4String & G4VEmModel::GetName (void) const inline
Definition at line 827 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 827 of file G4VEmModel.hh
References name.
Referenced by G4NIELCalculator::AddEmModel(), G4VLEPTSModel::BuildMeanFreePathTable(), G4VLEPTSModel::BuildPhysicsTable(), G4EmCalculator::ComputeDEDX(), G4MuPairProductionModel::DataCorrupted(), G4EmModelManager::DumpModelList(), G4EmCalculator::FindEmModel(), G4NIELCalculator::G4NIELCalculator(), G4EmMultiModel::Initialise(), G4IonParametrisedLossModel::Initialise(), G4EmModelManager::Initialise(), G4IonParametrisedLossModel::PrintDEDXTable(), G4DNADissociation::PrintInfo(), G4DNAPositronium::PrintInfo(), G4DNARotExcitation::PrintInfo(), G4DNAChargeIncrease::PrintInfo(), G4DNAVibExcitation::PrintInfo(), G4DNAAttachment::PrintInfo(), G4DNAChargeDecrease::PrintInfo(), G4DNAElastic::PrintInfo(), G4DNAExcitation::PrintInfo(), G4DNAIonisation::PrintInfo(), G4PolarizedCompton::PrintInfo(), G4VLEPTSModel::ReadIXS(), G4LossTableManager::Register(), G4DNAModelInterface::RegisterModel(), G4IonParametrisedLossModel::RemoveDEDXTable(), G4VLEPTSModel::SampleEnergyLoss(), G4EmConfigurator::SetExtraEmModel(), G4EmConfigurator::SetModelForRegion(), and G4EmConfigurator::UpdateModelEnergyRange().
G4double G4VEmModel::GetPartialCrossSection (const G4Material * , G4int level, const G4ParticleDefinition * , G4double kineticEnergy) virtual
Reimplemented in G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNABornExcitationModel2, G4DNAMillerGreenExcitationModel, and G4DNABornExcitationModel1.
Definition at line 279 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 279 of file G4VEmModel.cc
G4ParticleChangeForGamma * G4VEmModel::GetParticleChangeForGamma () protected
Definition at line 133 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 133 of file G4VEmModel.cc
References fTripletModel, pParticleChange, and SetParticleChange().
Referenced by G4LEPTSDissociationModel::Initialise(), G4LEPTSElasticModel::Initialise(), G4LEPTSExcitationModel::Initialise(), G4LEPTSIonisationModel::Initialise(), G4LEPTSPositroniumModel::Initialise(), G4LEPTSRotExcitationModel::Initialise(), G4LEPTSVibExcitationModel::Initialise(), G4LEPTSAttachmentModel::Initialise(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4XrayRayleighModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNABornIonisationModel1::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4eplusTo3GammaOKVIModel::Initialise(), G4DNATransformElectronModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4PEEffectFluoModel::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4KleinNishinaModel::Initialise(), G4KleinNishinaCompton::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4DNAModelInterface::Initialise(), G4eeToTwoGammaModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4BetheHeitlerModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PolarizedAnnihilationModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4eeToHadronsMultiModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4hCoulombScatteringModel::Initialise(), G4PairProductionRelModel::Initialise(), G4IonCoulombScatteringModel::Initialise(), G4eCoulombScatteringModel::Initialise(), G4LowEPComptonModel::Initialise(), and G4LowEPPolarizedComptonModel::Initialise().
G4ParticleChangeForLoss * G4VEmModel::GetParticleChangeForLoss () protected
Definition at line 118 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 118 of file G4VEmModel.cc
References fTripletModel, pParticleChange, and SetParticleChange().
Referenced by G4LivermoreIonisationModel::Initialise(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4AtimaEnergyLossModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4PAIPhotModel::Initialise(), G4BetheBlochModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4PAIModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4BraggIonModel::Initialise(), G4MuBetheBlochModel::Initialise(), G4ICRU73QOModel::Initialise(), G4MuPairProductionModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4BraggModel::Initialise(), and G4IonParametrisedLossModel::Initialise().
G4double G4VEmModel::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * , G4double kineticEnergy) virtual
Reimplemented in G4IonParametrisedLossModel, G4BraggIonModel, G4BraggModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4BraggIonGasModel, and G4BetheBlochIonGasModel.
Definition at line 400 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 400 of file G4VEmModel.cc
References G4ParticleDefinition::GetPDGCharge().
Referenced by G4VEnergyLossProcess::AlongStepDoIt().
G4VEmModel * G4VEmModel::GetTripletModel () inline
Definition at line 628 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 628 of file G4VEmModel.hh
References fTripletModel.
Referenced by G4LivermoreGammaConversionModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4LivermoreGammaConversionModel::InitialiseForElement(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4LivermoreGammaConversionModel::SampleSecondaries(), and G4eBremsstrahlungRelModel::SampleSecondaries().
G4double G4VEmModel::HighEnergyActivationLimit () const inline
Definition at line 659 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 659 of file G4VEmModel.hh
References eMaxActive.
Referenced by G4EmModelManager::DumpModelList(), G4VMscModel::GetParticleChangeForMSC(), G4WentzelVIModel::Initialise(), and G4EmModelManager::Initialise().
G4double G4VEmModel::HighEnergyLimit () const inline
Definition at line 645 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 645 of file G4VEmModel.hh
References highLimit.
Referenced by G4DNAScreenedRutherfordElasticModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::CrossSectionPerVolume(), G4DNAMeltonAttachmentModel::CrossSectionPerVolume(), G4DNAELSEPAElasticModel::CrossSectionPerVolume(), G4DNASancheExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNATransformElectronModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNAELSEPAElasticModel::G4DNAELSEPAElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4eeToHadronsModel::G4eeToHadronsModel(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4LivermorePolarizedRayleighModel::G4LivermorePolarizedRayleighModel(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4VMscModel::GetParticleChangeForMSC(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADummyModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4LivermoreIonisationModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PAIPhotModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4WentzelVIModel::Initialise(), G4PairProductionRelModel::Initialise(), G4PAIModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4MuPairProductionModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4EmModelManager::Initialise(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4MuBremsstrahlungModel::InitialiseLocal(), G4MuPairProductionModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4CoulombScattering::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4DNASancheExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4EmConfigurator::SetExtraEmModel(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), G4eBremsstrahlung::StreamProcessInfo(), and G4EmConfigurator::UpdateModelEnergyRange().
virtual void G4VEmModel::Initialise (const G4ParticleDefinition * , const G4DataVector &) pure virtual
Implemented in G4TDNAOneStepThermalizationModel< MODEL >, G4GoudsmitSaundersonMscModel, G4LowEPPolarizedComptonModel, G4IonParametrisedLossModel, G4LowEPComptonModel, G4eCoulombScatteringModel, G4UrbanAdjointMscModel, G4MuBremsstrahlungModel, G4MuPairProductionModel, G4BraggModel, G4ICRU73QOModel, G4IonCoulombScatteringModel, G4UrbanMscModel, G4MuBetheBlochModel, G4BraggIonModel, G4SeltzerBergerModel, G4PAIModel, G4PairProductionRelModel, G4eSingleCoulombScatteringModel, G4hCoulombScatteringModel, G4WentzelVIRelModel, G4PenelopeIonisationModel, G4BetheHeitler5DModel, G4WentzelVIModel, G4eeToHadronsMultiModel, G4MicroElecInelasticModel, G4MuElecInelasticModel, G4PolarizedAnnihilationModel, G4BetheBlochModel, G4ICRU49NuclearStoppingModel, G4MollerBhabhaModel, G4PAIPhotModel, G4PenelopeBremsstrahlungModel, G4PenelopeComptonModel, G4PolarizedPEEffectModel, G4BetheHeitlerModel, G4LindhardSorensenIonModel, G4DNACPA100IonisationModel, G4LivermoreBremsstrahlungModel, G4eeToTwoGammaModel, G4EmMultiModel, G4DNAModelInterface, G4eeToHadronsModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, G4mplIonisationModel, G4mplIonisationWithDeltaModel, G4PenelopePhotoElectricModel, G4AtimaEnergyLossModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4LivermoreIonisationModel, G4ePolarizedBremsstrahlungModel, G4PolarizedGammaConversionModel, G4eplusTo2GammaOKVIModel, G4PEEffectFluoModel, G4DNACPA100ExcitationModel, G4DNATransformElectronModel, G4PenelopeGammaConversionModel, G4PenelopeRayleighModel, G4DNACPA100ElasticModel, G4DNAEmfietzoglouIonisationModel, G4PenelopeAnnihilationModel, G4eplusTo3GammaOKVIModel, G4DNAEmfietzoglouExcitationModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4DummyModel, G4MicroElecElasticModel, G4MuElecElasticModel, G4DNAIonElasticModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedRayleighModel, G4LivermorePolarizedPhotoElectricModel, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4LivermoreComptonModifiedModel, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4LivermoreComptonModel, G4DNABornExcitationModel2, G4DNAMillerGreenExcitationModel, G4LivermoreGammaConversionModel, G4DNAELSEPAElasticModel, G4DNASancheExcitationModel, G4LivermorePolarizedGammaConversionModel, G4LivermorePolarizedPhotoElectricGDModel, G4XrayRayleighModel, G4DNABornExcitationModel1, G4DNAChampionElasticModel, G4DNAMeltonAttachmentModel, G4DNADingfelderChargeIncreaseModel, G4BoldyshevTripletModel, G4DNADingfelderChargeDecreaseModel, G4LivermoreGammaConversionModelRC, G4LivermoreNuclearGammaConversionModel, G4LivermoreRayleighModel, G4DNAScreenedRutherfordElasticModel, G4DNAUeharaScreenedRutherfordElasticModel, G4LEPTSAttachmentModel, G4LEPTSDissociationModel, G4LEPTSElasticModel, G4LEPTSExcitationModel, G4LEPTSIonisationModel, G4LEPTSPositroniumModel, G4LEPTSRotExcitationModel, and G4LEPTSVibExcitationModel.
Referenced by G4DNADummyModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4EmModelManager::Initialise(), InitialiseElementSelectors(), and main().
void G4VEmModel::InitialiseElementSelectors (const G4ParticleDefinition * part, const G4DataVector & cuts)
Definition at line 148 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 148 of file G4VEmModel.cc
References DBL_MAX, elmSelectors, emax, CEMC_TOWER::emin, G4Log(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), highLimit, Initialise(), G4EmParameters::Instance(), lowLimit, material(), max, MinPrimaryEnergy(), nSelectors, G4EmParameters::NumberOfBinsPerDecade(), and SetCurrentCouple().
Referenced by G4LivermoreRayleighModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4XrayRayleighModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4KleinNishinaCompton::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4KleinNishinaModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4BetheHeitlerModel::Initialise(), G4PAIPhotModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4hCoulombScatteringModel::Initialise(), G4PAIModel::Initialise(), G4PairProductionRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4MuPairProductionModel::Initialise(), G4eCoulombScatteringModel::Initialise(), G4LowEPComptonModel::Initialise(), and G4LowEPPolarizedComptonModel::Initialise().
void G4VEmModel::InitialiseForElement (const G4ParticleDefinition * , G4int Z) virtual
Reimplemented in G4LowEPPolarizedComptonModel, G4LowEPComptonModel, G4LivermorePhotoElectricModel, G4LivermorePolarizedPhotoElectricModel, G4SeltzerBergerModel, G4LivermoreBremsstrahlungModel, G4LivermorePolarizedPhotoElectricGDModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4LivermorePolarizedRayleighModel, G4LivermoreComptonModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, G4LivermoreRayleighModel, and G4BoldyshevTripletModel.
Definition at line 240 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 240 of file G4VEmModel.cc
Referenced by G4EmCalculator::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4LivermoreGammaConversionModel::InitialiseForElement(), and InitialiseForMaterial().
void G4VEmModel::InitialiseForMaterial (const G4ParticleDefinition * part, const G4Material * material) virtual
Definition at line 226 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 226 of file G4VEmModel.cc
References G4Material::GetElement(), G4Material::GetNumberOfElements(), G4Element::GetZasInt(), InitialiseForElement(), n, and Z.
Referenced by G4EmCalculator::FindEmModel().
void G4VEmModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) virtual
Reimplemented in G4GoudsmitSaundersonMscModel, G4LowEPPolarizedComptonModel, G4LowEPComptonModel, G4eCoulombScatteringModel, G4MuBremsstrahlungModel, G4MuPairProductionModel, G4PAIModel, G4PairProductionRelModel, G4eSingleCoulombScatteringModel, G4hCoulombScatteringModel, G4WentzelVIModel, G4PenelopeIonisationModel, G4PAIPhotModel, G4PenelopeBremsstrahlungModel, G4PenelopeComptonModel, G4BetheHeitlerModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4PenelopePhotoElectricModel, G4PenelopeRayleighModel, G4PenelopeGammaConversionModel, G4PenelopeAnnihilationModel, G4JAEAElasticScatteringModel, G4LivermorePolarizedComptonModel, G4LivermorePolarizedRayleighModel, G4LivermoreComptonModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, and G4LivermoreRayleighModel.
Definition at line 220 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 220 of file G4VEmModel.cc
Referenced by G4VEmProcess::BuildPhysicsTable(), G4VMultipleScattering::BuildPhysicsTable(), and G4VEnergyLossProcess::BuildPhysicsTable().
G4bool G4VEmModel::IsActive (G4double kinEnergy) const inline
Definition at line 785 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 785 of file G4VEmModel.hh
References eMaxActive, and eMinActive.
Referenced by G4NuclearStopping::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepGetPhysicalInteractionLength(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), and G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength().
G4bool G4VEmModel::IsLocked () const inline
Definition at line 867 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 867 of file G4VEmModel.hh
References isLocked.
Referenced by G4VMscModel::InitialiseParameters(), G4VMscModel::SetGeomFactor(), G4VMscModel::SetLambdaLimit(), G4VMscModel::SetLateralDisplasmentFlag(), G4VMscModel::SetRangeFactor(), G4VMscModel::SetSafetyFactor(), G4VMscModel::SetSampleZ(), G4VMscModel::SetSkin(), and G4VMscModel::SetStepLimitType().
G4bool G4VEmModel::IsMaster () const inline
Definition at line 736 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 736 of file G4VEmModel.hh
References isMaster.
Referenced by G4PenelopeBremsstrahlungModel::BuildXSTable(), G4PenelopeBremsstrahlungModel::ClearTables(), G4MuPairProductionModel::DataCorrupted(), G4PenelopePhotoElectricModel::GetNumberOfShellXS(), G4VMscModel::GetParticleChangeForMSC(), G4LivermoreRayleighModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4KleinNishinaCompton::Initialise(), G4KleinNishinaModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4mplIonisationModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4LivermoreBremsstrahlungModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheHeitlerModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PAIPhotModel::Initialise(), G4BetheBlochModel::Initialise(), G4WentzelVIModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4hCoulombScatteringModel::Initialise(), G4PAIModel::Initialise(), G4PairProductionRelModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4BraggIonModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4MuPairProductionModel::Initialise(), G4BraggModel::Initialise(), G4eCoulombScatteringModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4PenelopeBremsstrahlungModel::InitialiseLocal(), G4PenelopeGammaConversionModel::ReadDataFile(), G4PenelopePhotoElectricModel::ReadDataFile(), G4BetheHeitlerModel::~G4BetheHeitlerModel(), G4BoldyshevTripletModel::~G4BoldyshevTripletModel(), G4BraggIonModel::~G4BraggIonModel(), G4BraggModel::~G4BraggModel(), G4eBremsstrahlungRelModel::~G4eBremsstrahlungRelModel(), G4GoudsmitSaundersonMscModel::~G4GoudsmitSaundersonMscModel(), G4JAEAElasticScatteringModel::~G4JAEAElasticScatteringModel(), G4LivermoreBremsstrahlungModel::~G4LivermoreBremsstrahlungModel(), G4LivermoreComptonModel::~G4LivermoreComptonModel(), G4LivermoreGammaConversionModel::~G4LivermoreGammaConversionModel(), G4LivermorePhotoElectricModel::~G4LivermorePhotoElectricModel(), G4LivermorePolarizedComptonModel::~G4LivermorePolarizedComptonModel(), G4LivermorePolarizedGammaConversionModel::~G4LivermorePolarizedGammaConversionModel(), G4LivermorePolarizedPhotoElectricGDModel::~G4LivermorePolarizedPhotoElectricGDModel(), G4LivermorePolarizedPhotoElectricModel::~G4LivermorePolarizedPhotoElectricModel(), G4LivermorePolarizedRayleighModel::~G4LivermorePolarizedRayleighModel(), G4LivermoreRayleighModel::~G4LivermoreRayleighModel(), G4LowEPComptonModel::~G4LowEPComptonModel(), G4LowEPPolarizedComptonModel::~G4LowEPPolarizedComptonModel(), G4mplIonisationModel::~G4mplIonisationModel(), G4mplIonisationWithDeltaModel::~G4mplIonisationWithDeltaModel(), G4PAIModel::~G4PAIModel(), G4PAIPhotModel::~G4PAIPhotModel(), G4PairProductionRelModel::~G4PairProductionRelModel(), G4PenelopeBremsstrahlungModel::~G4PenelopeBremsstrahlungModel(), G4PenelopeGammaConversionModel::~G4PenelopeGammaConversionModel(), G4PenelopeIonisationModel::~G4PenelopeIonisationModel(), G4PenelopePhotoElectricModel::~G4PenelopePhotoElectricModel(), G4PenelopeRayleighModel::~G4PenelopeRayleighModel(), G4SeltzerBergerModel::~G4SeltzerBergerModel(), and G4WentzelVIModel::~G4WentzelVIModel().
G4double G4VEmModel::LowEnergyActivationLimit () const inline
Definition at line 666 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 666 of file G4VEmModel.hh
References eMinActive.
Referenced by G4EmModelManager::DumpModelList(), G4VMscModel::GetParticleChangeForMSC(), G4WentzelVIModel::Initialise(), and G4EmModelManager::Initialise().
G4double G4VEmModel::LowEnergyLimit () const inline
Definition at line 652 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 652 of file G4VEmModel.hh
References lowLimit.
Referenced by G4LivermoreComptonModifiedModel::ComputeCrossSectionPerAtom(), G4LivermoreComptonModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedComptonModel::ComputeCrossSectionPerAtom(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeCrossSectionPerAtom(), G4LowEPComptonModel::ComputeCrossSectionPerAtom(), G4LowEPPolarizedComptonModel::ComputeCrossSectionPerAtom(), G4mplIonisationWithDeltaModel::ComputeCrossSectionPerElectron(), G4EmCalculator::ComputeDEDX(), G4mplIonisationWithDeltaModel::ComputeDEDXPerVolume(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4IonParametrisedLossModel::ComputeDEDXPerVolume(), G4IonParametrisedLossModel::CorrectionsAlongStep(), G4DNAScreenedRutherfordElasticModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::CrossSectionPerVolume(), G4DNAMeltonAttachmentModel::CrossSectionPerVolume(), G4DNAELSEPAElasticModel::CrossSectionPerVolume(), G4DNASancheExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4PenelopeComptonModel::CrossSectionPerVolume(), G4EmCalculator::FindEmModel(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNAELSEPAElasticModel::G4DNAELSEPAElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4eeToHadronsModel::G4eeToHadronsModel(), G4LivermorePolarizedRayleighModel::G4LivermorePolarizedRayleighModel(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4VMscModel::GetParticleChangeForMSC(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4LivermoreRayleighModel::Initialise(), G4DNADummyModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4PenelopeAnnihilationModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4LivermoreIonisationModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4eBremParametrizedModel::Initialise(), G4eBremsstrahlungRelModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4PenelopeBremsstrahlungModel::Initialise(), G4PenelopeComptonModel::Initialise(), G4PAIPhotModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4WentzelVIModel::Initialise(), G4PairProductionRelModel::Initialise(), G4PAIModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4MuPairProductionModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4EmModelManager::Initialise(), G4mplIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4CoulombScattering::InitialiseProcess(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4EmConfigurator::SetExtraEmModel(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), and G4EmConfigurator::UpdateModelEnergyRange().
G4bool G4VEmModel::LPMFlag () const inline
Definition at line 687 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 687 of file G4VEmModel.hh
References theLPMflag.
Referenced by G4eBremsstrahlungRelModel::Initialise(), G4SeltzerBergerModel::SetupForMaterial(), G4eBremsstrahlungRelModel::SetupForMaterial(), and G4eBremsstrahlungRelModel::~G4eBremsstrahlungRelModel().
G4double G4VEmModel::MaxSecondaryEnergy (const G4ParticleDefinition * , G4double kineticEnergy) protected virtual
Reimplemented in G4IonParametrisedLossModel, G4BraggIonModel, G4BraggModel, G4BetheBlochModel, G4ICRU73QOModel, G4LindhardSorensenIonModel, G4PAIModel, G4AtimaEnergyLossModel, G4PAIPhotModel, G4MuBetheBlochModel, G4mplIonisationWithDeltaModel, and G4MollerBhabhaModel.
Definition at line 441 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 441 of file G4VEmModel.cc
Referenced by MaxSecondaryKinEnergy().
G4double G4VEmModel::MaxSecondaryKinEnergy (const G4DynamicParticle * dynParticle) inline
Definition at line 510 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 510 of file G4VEmModel.hh
References G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetParticleDefinition(), and MaxSecondaryEnergy().
Referenced by G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VEnergyLossProcess::GetDEDXDispersion(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
G4double G4VEmModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple *) virtual
Reimplemented in G4PenelopeIonisationModel, G4mplIonisationWithDeltaModel, G4IonParametrisedLossModel, G4PenelopeBremsstrahlungModel, G4MuBremsstrahlungModel, G4PAIModel, G4MuBetheBlochModel, G4BraggIonModel, G4PAIPhotModel, G4BetheBlochModel, G4eBremParametrizedModel, G4LindhardSorensenIonModel, and G4AtimaEnergyLossModel.
Definition at line 433 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 433 of file G4VEmModel.cc
Referenced by G4EmModelManager::Initialise().
G4double G4VEmModel::MinPrimaryEnergy (const G4Material * , const G4ParticleDefinition * , G4double cut = 0.0) virtual
Reimplemented in G4MuBremsstrahlungModel, G4eCoulombScatteringModel, G4MuPairProductionModel, G4eBremsstrahlungRelModel, G4hCoulombScatteringModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4LivermoreNuclearGammaConversionModel, G4LivermoreGammaConversionModelRC, and G4BoldyshevTripletModel.
Definition at line 424 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 424 of file G4VEmModel.cc
Referenced by G4LossTableBuilder::BuildTableForModel(), InitialiseElementSelectors(), and G4LivermoreGammaConversionModel::InitialiseProbability().
void G4VEmModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented in G4eeToHadronsMultiModel.
Definition at line 478 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 478 of file G4VEmModel.cc
G4VEmModel& G4VEmModel::operator= (const G4VEmModel & right) private
G4double G4VEmModel::PolarAngleLimit () const inline
Definition at line 673 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 673 of file G4VEmModel.hh
References polarAngleLimit.
Referenced by G4WentzelVIModel::Initialise(), G4hCoulombScatteringModel::Initialise(), and G4eCoulombScatteringModel::Initialise().
virtual void G4VEmModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double tmin = 0.0, G4double tmax = DBL_MAX) pure virtual
Implemented in G4TDNAOneStepThermalizationModel< MODEL >, G4IonParametrisedLossModel, G4LowEPPolarizedComptonModel, G4BetheBlochModel, G4LindhardSorensenIonModel, G4AtimaEnergyLossModel, G4MuBetheBlochModel, G4BraggIonModel, G4BraggModel, G4ICRU73QOModel, G4LowEPComptonModel, G4MuBremsstrahlungModel, G4eCoulombScatteringModel, G4DNAModelInterface, G4MuPairProductionModel, G4MollerBhabhaModel, G4PAIModel, G4PenelopeIonisationModel, G4PenelopeBremsstrahlungModel, G4PenelopeComptonModel, G4PAIPhotModel, G4IonCoulombScatteringModel, G4PairProductionRelModel, G4eeToHadronsModel, G4eeToHadronsMultiModel, G4eSingleCoulombScatteringModel, G4hCoulombScatteringModel, G4mplIonisationWithDeltaModel, G4eBremParametrizedModel, G4eeToTwoGammaModel, G4VMscModel, G4eBremsstrahlungRelModel, G4EmMultiModel, G4eplusTo2GammaOKVIModel, G4eplusTo3GammaOKVIModel, G4PolarizedAnnihilationModel, G4BetheHeitlerModel, G4SeltzerBergerModel, G4MicroElecInelasticModel, G4MuElecInelasticModel, G4PEEffectFluoModel, G4KleinNishinaCompton, G4KleinNishinaModel, G4LDMBremModel, G4PenelopePhotoElectricModel, G4ICRU49NuclearStoppingModel, G4DNACPA100IonisationModel, G4PolarizedComptonModel, G4JAEAElasticScatteringModel, G4LivermoreIonisationModel, G4PenelopeRayleighModel, G4LivermorePolarizedComptonModel, G4PenelopeGammaConversionModel, G4BetheHeitler5DModel, G4mplIonisationModel, G4LivermorePhotoElectricModel, G4PenelopeAnnihilationModel, G4PolarizedPEEffectModel, G4DNACPA100ExcitationModel, G4DNATransformElectronModel, G4LivermoreBremsstrahlungModel, G4LivermorePolarizedPhotoElectricModel, G4LivermorePolarizedRayleighModel, G4PolarizedMollerBhabhaModel, G4DNACPA100ElasticModel, G4DNAEmfietzoglouIonisationModel, G4DNAEmfietzoglouExcitationModel, G4LivermoreComptonModel, G4MicroElecElasticModel, G4MuElecElasticModel, G4ePolarizedBremsstrahlungModel, G4PolarizedGammaConversionModel, G4LivermoreGammaConversionModel, G4LivermorePolarizedGammaConversionModel, G4DNABornExcitationModel2, G4DNAMillerGreenExcitationModel, G4LivermoreComptonModifiedModel, G4LivermoreNuclearGammaConversionModel, G4HeatedKleinNishinaCompton, G4DNABornIonisationModel1, G4DNABornIonisationModel2, G4DNAIonElasticModel, G4DNABornExcitationModel1, G4LivermoreGammaConversionModelRC, G4DummyModel, G4DNARuddIonisationExtendedModel, G4DNARuddIonisationModel, G4LivermoreRayleighModel, G4BoldyshevTripletModel, G4LivermorePolarizedPhotoElectricGDModel, G4XrayRayleighModel, MyKleinNishinaCompton, G4DNAELSEPAElasticModel, G4DNASancheExcitationModel, G4DNAChampionElasticModel, G4DNAMeltonAttachmentModel, G4DNADingfelderChargeIncreaseModel, G4DNADingfelderChargeDecreaseModel, G4DNAScreenedRutherfordElasticModel, G4DNAUeharaScreenedRutherfordElasticModel, G4LEPTSAttachmentModel, G4LEPTSExcitationModel, G4LEPTSDissociationModel, G4LEPTSElasticModel, G4LEPTSIonisationModel, G4LEPTSPositroniumModel, G4LEPTSRotExcitationModel, and G4LEPTSVibExcitationModel.
Referenced by G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplySplitting(), G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4DNADummyModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), and G4VEnergyLossProcess::SampleSubCutSecondaries().
G4double G4VEmModel::SecondaryThreshold () const inline
Definition at line 680 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 680 of file G4VEmModel.hh
References secondaryThreshold.
Referenced by G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), and G4eBremParametrizedModel::SampleSecondaries().
G4int G4VEmModel::SelectIsotopeNumber (const G4Element * elm)
Definition at line 337 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 337 of file G4VEmModel.cc
References ab, fCurrentIsotope, G4UniformRand, G4Element::GetIsotope(), G4Isotope::GetN(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), incremental_prev_tag::idx, SetCurrentElement(), and x.
Referenced by G4BetheHeitler5DModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
const G4Element * G4VEmModel::SelectRandomAtom (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 570 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 570 of file G4VEmModel.hh
References elmSelectors, fCurrentElement, fCurrentIsotope, G4MaterialCutsCouple::GetIndex(), nSelectors, pBaseMaterial, and SetCurrentCouple().
Referenced by G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), and SelectTargetAtom().
const G4Element * G4VEmModel::SelectRandomAtom (const G4Material * material, const G4ParticleDefinition * pd, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX)
Definition at line 293 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 293 of file G4VEmModel.cc
References CrossSectionPerVolume(), fCurrentElement, G4UniformRand, G4Material::GetElement(), G4Material::GetNumberOfElements(), n, x, and xsec.
G4int G4VEmModel::SelectRandomAtomNumber (const G4Material * mat)
Definition at line 315 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 315 of file G4VEmModel.cc
References Acts::Test::at, fCurrentElement, G4UniformRand, G4Material::GetElement(), G4Material::GetNumberOfElements(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZasInt(), and G4InuclParticleNames::nn.
Referenced by G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4IonParametrisedLossModel::SampleSecondaries().
const G4Element * G4VEmModel::SelectTargetAtom (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * part, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 587 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 587 of file G4VEmModel.hh
References elmSelectors, fCurrentElement, fCurrentIsotope, G4MaterialCutsCouple::GetIndex(), nSelectors, pBaseMaterial, SelectRandomAtom(), and SetCurrentCouple().
Referenced by G4XrayRayleighModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
void G4VEmModel::SetActivationHighEnergyLimit (G4double val) inline
Definition at line 771 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 771 of file G4VEmModel.hh
References eMaxActive.
Referenced by G4EmModelActivator::ActivateMicroElec(), PhysicsList::ConstructEM(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4NuclearStopping::InitialiseProcess(), and G4EmConfigurator::SetExtraEmModel().
void G4VEmModel::SetActivationLowEnergyLimit (G4double val) inline
Definition at line 778 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 778 of file G4VEmModel.hh
References eMinActive.
Referenced by G4EmModelActivator::ActivateMicroElec(), G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4EmModelActivator::AddStandardScattering(), PhysicsList::ConstructEM(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), and G4EmDNAPhysicsActivator::DeactivateNuclearStopping().
void G4VEmModel::SetAngularDistribution (G4VEmAngularDistribution * p) inline
Definition at line 618 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 618 of file G4VEmModel.hh
References anglModel.
Referenced by G4EmLivermorePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4BetheHeitlerModel::G4BetheHeitlerModel(), G4DNABornIonisationModel1::G4DNABornIonisationModel1(), G4DNABornIonisationModel2::G4DNABornIonisationModel2(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNARuddIonisationExtendedModel::G4DNARuddIonisationExtendedModel(), G4DNARuddIonisationModel::G4DNARuddIonisationModel(), G4eBremParametrizedModel::G4eBremParametrizedModel(), G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel(), G4LivermoreIonisationModel::G4LivermoreIonisationModel(), G4LivermorePhotoElectricModel::G4LivermorePhotoElectricModel(), G4LivermorePolarizedPhotoElectricModel::G4LivermorePolarizedPhotoElectricModel(), G4LivermoreRayleighModel::G4LivermoreRayleighModel(), G4MicroElecInelasticModel::G4MicroElecInelasticModel(), G4PAIModel::G4PAIModel(), G4PAIPhotModel::G4PAIPhotModel(), G4PairProductionRelModel::G4PairProductionRelModel(), G4PEEffectFluoModel::G4PEEffectFluoModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4BetheBlochModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), and G4BraggModel::Initialise().
void G4VEmModel::SetAngularGeneratorFlag (G4bool val) inline
Definition at line 715 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 715 of file G4VEmModel.hh
References useAngularGenerator.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
void G4VEmModel::SetCrossSectionTable (G4PhysicsTable * p, G4bool isLocal)
Definition at line 464 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 464 of file G4VEmModel.cc
References G4PhysicsTable::clearAndDestroy(), localTable, and xSectionTable.
Referenced by G4VMultipleScattering::BuildPhysicsTable().
void G4VEmModel::SetCurrentCouple (const G4MaterialCutsCouple * ptr) inline
Definition at line 465 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 465 of file G4VEmModel.hh
References fCurrentCouple, G4Material::GetBaseMaterial(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), pBaseMaterial, pFactor, and useBaseMaterials.
Referenced by G4EmMultiModel::ComputeCrossSectionPerAtom(), G4EmMultiModel::ComputeDEDX(), ComputeDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), CrossSection(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4WentzelVIRelModel::DefineMaterial(), G4WentzelVIModel::DefineMaterial(), G4EmCalculator::GetCrossSectionPerVolume(), G4LivermoreGammaConversionModel::Initialise(), InitialiseElementSelectors(), main(), G4PEEffectFluoModel::SampleSecondaries(), G4EmMultiModel::SampleSecondaries(), G4VEmProcess::SelectModel(), G4VEnergyLossProcess::SelectModel(), SelectRandomAtom(), SelectTargetAtom(), and Value().
void G4VEmModel::SetCurrentElement (const G4Element * elm) inline protected
Definition at line 487 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 487 of file G4VEmModel.hh
References fCurrentElement, and fCurrentIsotope.
Referenced by ComputeCrossSectionPerAtom(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4eBremParametrizedModel::ComputeDEDXPerVolume(), and SelectIsotopeNumber().
void G4VEmModel::SetDeexcitationFlag (G4bool val) inline
Definition at line 813 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 813 of file G4VEmModel.hh
References flagDeexcitation.
Referenced by G4DNABornIonisationModel1::G4DNABornIonisationModel1(), G4DNABornIonisationModel2::G4DNABornIonisationModel2(), G4DNACPA100IonisationModel::G4DNACPA100IonisationModel(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNARuddIonisationExtendedModel::G4DNARuddIonisationExtendedModel(), G4DNARuddIonisationModel::G4DNARuddIonisationModel(), G4KleinNishinaModel::G4KleinNishinaModel(), G4LEPTSIonisationModel::G4LEPTSIonisationModel(), G4LivermoreComptonModel::G4LivermoreComptonModel(), G4LivermoreComptonModifiedModel::G4LivermoreComptonModifiedModel(), G4LivermorePhotoElectricModel::G4LivermorePhotoElectricModel(), G4LivermorePolarizedComptonModel::G4LivermorePolarizedComptonModel(), G4LivermorePolarizedPhotoElectricGDModel::G4LivermorePolarizedPhotoElectricGDModel(), G4LivermorePolarizedPhotoElectricModel::G4LivermorePolarizedPhotoElectricModel(), G4LowEPComptonModel::G4LowEPComptonModel(), G4LowEPPolarizedComptonModel::G4LowEPPolarizedComptonModel(), G4MicroElecInelasticModel::G4MicroElecInelasticModel(), G4MuElecInelasticModel::G4MuElecInelasticModel(), G4PEEffectFluoModel::G4PEEffectFluoModel(), G4PenelopeBremsstrahlungModel::G4PenelopeBremsstrahlungModel(), G4PenelopeComptonModel::G4PenelopeComptonModel(), G4PenelopeIonisationModel::G4PenelopeIonisationModel(), G4PenelopePhotoElectricModel::G4PenelopePhotoElectricModel(), G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheBlochModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), and G4BraggModel::Initialise().
void G4VEmModel::SetElementSelectors (std::vector< G4EmElementSelector * > * p) inline
Definition at line 842 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 842 of file G4VEmModel.hh
References elmSelectors, localElmSelectors, and nSelectors.
Referenced by G4LivermoreRayleighModel::InitialiseLocal(), G4LivermorePolarizedGammaConversionModel::InitialiseLocal(), G4LivermoreGammaConversionModel::InitialiseLocal(), G4LivermoreComptonModel::InitialiseLocal(), G4LivermorePolarizedRayleighModel::InitialiseLocal(), G4LivermorePolarizedComptonModel::InitialiseLocal(), G4JAEAElasticScatteringModel::InitialiseLocal(), G4PenelopePhotoElectricModel::InitialiseLocal(), G4KleinNishinaCompton::InitialiseLocal(), G4KleinNishinaModel::InitialiseLocal(), G4eBremParametrizedModel::InitialiseLocal(), G4eBremsstrahlungRelModel::InitialiseLocal(), G4BetheHeitlerModel::InitialiseLocal(), G4PAIPhotModel::InitialiseLocal(), G4eSingleCoulombScatteringModel::InitialiseLocal(), G4hCoulombScatteringModel::InitialiseLocal(), G4PAIModel::InitialiseLocal(), G4PairProductionRelModel::InitialiseLocal(), G4MuBremsstrahlungModel::InitialiseLocal(), G4MuPairProductionModel::InitialiseLocal(), G4eCoulombScatteringModel::InitialiseLocal(), G4LowEPComptonModel::InitialiseLocal(), and G4LowEPPolarizedComptonModel::InitialiseLocal().
void G4VEmModel::SetFluctuationFlag (G4bool val) inline
Definition at line 722 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 722 of file G4VEmModel.hh
References lossFlucFlag.
Referenced by G4EmCalculator::ComputeNuclearDEDX().
void G4VEmModel::SetForceBuildTable (G4bool val) inline
Definition at line 820 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 820 of file G4VEmModel.hh
References flagForceBuildTable.
void G4VEmModel::SetHighEnergyLimit (G4double val) inline
Definition at line 757 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 757 of file G4VEmModel.hh
References highLimit.
Referenced by G4EmModelActivator::ActivateEmOptions(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4BraggIonModel::G4BraggIonModel(), G4BraggModel::G4BraggModel(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNACPA100ExcitationModel::G4DNACPA100ExcitationModel(), G4DNACPA100IonisationModel::G4DNACPA100IonisationModel(), G4DNAELSEPAElasticModel::G4DNAELSEPAElasticModel(), G4DNAEmfietzoglouExcitationModel::G4DNAEmfietzoglouExcitationModel(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNAIonElasticModel::G4DNAIonElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAScreenedRutherfordElasticModel::G4DNAScreenedRutherfordElasticModel(), G4DNATransformElectronModel::G4DNATransformElectronModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4ICRU73QOModel::G4ICRU73QOModel(), G4MicroElecElasticModel::G4MicroElecElasticModel(), G4MuElecElasticModel::G4MuElecElasticModel(), G4PenelopeAnnihilationModel::G4PenelopeAnnihilationModel(), G4PenelopeBremsstrahlungModel::G4PenelopeBremsstrahlungModel(), G4PenelopeComptonModel::G4PenelopeComptonModel(), G4PenelopeGammaConversionModel::G4PenelopeGammaConversionModel(), G4PenelopeIonisationModel::G4PenelopeIonisationModel(), G4PenelopePhotoElectricModel::G4PenelopePhotoElectricModel(), G4PenelopeRayleighModel::G4PenelopeRayleighModel(), G4TDNAOneStepThermalizationModel< MODEL >::G4TDNAOneStepThermalizationModel(), G4XrayRayleighModel::G4XrayRayleighModel(), G4VLEPTSModel::Init(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAModelInterface::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4DNAPositronium::InitialiseProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNADissociation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4DNAUeharaScreenedRutherfordElasticModel::SelectHighEnergyLimit(), G4VEmAdjointModel::SetHighEnergyLimit(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), and G4EmConfigurator::UpdateModelEnergyRange().
void G4VEmModel::SetLocked (G4bool val) inline
Definition at line 874 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 874 of file G4VEmModel.hh
References isLocked.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::AddStandardScattering(), and G4EmModelActivator::GetGSModel().
void G4VEmModel::SetLowEnergyLimit (G4double val) inline
Definition at line 764 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 764 of file G4VEmModel.hh
References lowLimit.
Referenced by G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4DNASancheExcitationModel::ExtendLowEnergyLimit(), G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4BetheBlochModel::G4BetheBlochModel(), G4BetheHeitler5DModel::G4BetheHeitler5DModel(), G4DNAChampionElasticModel::G4DNAChampionElasticModel(), G4DNACPA100ElasticModel::G4DNACPA100ElasticModel(), G4DNACPA100ExcitationModel::G4DNACPA100ExcitationModel(), G4DNACPA100IonisationModel::G4DNACPA100IonisationModel(), G4DNAELSEPAElasticModel::G4DNAELSEPAElasticModel(), G4DNAEmfietzoglouExcitationModel::G4DNAEmfietzoglouExcitationModel(), G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel(), G4DNAIonElasticModel::G4DNAIonElasticModel(), G4DNAMeltonAttachmentModel::G4DNAMeltonAttachmentModel(), G4DNASancheExcitationModel::G4DNASancheExcitationModel(), G4DNAScreenedRutherfordElasticModel::G4DNAScreenedRutherfordElasticModel(), G4DNATransformElectronModel::G4DNATransformElectronModel(), G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel(), G4DummyModel::G4DummyModel(), G4eBremParametrizedModel::G4eBremParametrizedModel(), G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4LindhardSorensenIonModel::G4LindhardSorensenIonModel(), G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel(), G4MicroElecElasticModel::G4MicroElecElasticModel(), G4MuElecElasticModel::G4MuElecElasticModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), G4TDNAOneStepThermalizationModel< MODEL >::G4TDNAOneStepThermalizationModel(), G4VLEPTSModel::Init(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNAIonElasticModel::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAModelInterface::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4BetheHeitler5DModel::Initialise(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4DNADissociation::InitialiseProcess(), G4DNAPositronium::InitialiseProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmAdjointModel::SetLowEnergyLimit(), G4mplIonisationModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), and G4EmConfigurator::UpdateModelEnergyRange().
void G4VEmModel::SetLPMFlag (G4bool val) inline
Definition at line 806 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 806 of file G4VEmModel.hh
References theLPMflag.
Referenced by G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), and G4eBremsstrahlung::InitialiseEnergyLossProcess().
void G4VEmModel::SetMasterThread (G4bool val) inline
Definition at line 729 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 729 of file G4VEmModel.hh
References isMaster.
Referenced by G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
void G4VEmModel::SetParticleChange (G4VParticleChange * p, G4VEmFluctuationModel * f = nullptr)
Definition at line 456 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 456 of file G4VEmModel.cc
References f, flucModel, and pParticleChange.
Referenced by G4VMultipleScattering::AddEmModel(), G4VEmProcess::AddEmModel(), G4VEnergyLossProcess::AddEmModel(), GetParticleChangeForGamma(), GetParticleChangeForLoss(), G4DNADummyModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4EmMultiModel::Initialise(), G4IonParametrisedLossModel::Initialise(), and G4NuclearStopping::InitialiseProcess().
void G4VEmModel::SetPolarAngleLimit (G4double val) inline
Definition at line 792 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 792 of file G4VEmModel.hh
References isLocked, and polarAngleLimit.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4TablesForExtrapolator::ComputeTrasportXS(), PhysListEmStandardSSM::ConstructProcess(), G4CoulombScattering::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), and G4VMultipleScattering::PreparePhysicsTable().
void G4VEmModel::SetSecondaryThreshold (G4double val) inline
Definition at line 799 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 799 of file G4VEmModel.hh
References secondaryThreshold.
Referenced by G4eBremsstrahlung::InitialiseEnergyLossProcess().
void G4VEmModel::SetTripletModel (G4VEmModel * p) inline
Definition at line 635 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 635 of file G4VEmModel.hh
References fTripletModel.
Referenced by G4eplusTo2GammaOKVIModel::G4eplusTo2GammaOKVIModel().
void G4VEmModel::SetupForMaterial (const G4ParticleDefinition * , const G4Material * , G4double kineticEnergy) virtual
Reimplemented in G4PairProductionRelModel, G4eBremParametrizedModel, G4eBremsstrahlungRelModel, and G4SeltzerBergerModel.
Definition at line 449 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 449 of file G4VEmModel.cc
Referenced by G4PenelopeComptonModel::CrossSectionPerVolume(), G4PenelopeBremsstrahlungModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), CrossSectionPerVolume(), G4EmCalculator::FindEmModel(), and G4LivermoreGammaConversionModel::InitialiseProbability().
void G4VEmModel::SetUseBaseMaterials (G4bool val) inline
Definition at line 743 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 743 of file G4VEmModel.hh
References useBaseMaterials.
Referenced by G4TablesForExtrapolator::ComputeElectronDEDX(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), and G4VMscModel::G4VMscModel().
void G4VEmModel::StartTracking (G4Track *) virtual
Reimplemented in G4GoudsmitSaundersonMscModel, G4UrbanAdjointMscModel, G4UrbanMscModel, and G4WentzelVIModel.
Definition at line 288 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 288 of file G4VEmModel.cc
Referenced by G4VMultipleScattering::StartTracking().
G4bool G4VEmModel::UseAngularGeneratorFlag () const inline
Definition at line 708 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 708 of file G4VEmModel.hh
References useAngularGenerator.
Referenced by G4AtimaEnergyLossModel::Initialise(), G4LindhardSorensenIonModel::Initialise(), G4BetheBlochModel::Initialise(), G4MollerBhabhaModel::Initialise(), G4BraggIonModel::Initialise(), G4ICRU73QOModel::Initialise(), G4BraggModel::Initialise(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), and G4BetheBlochModel::SampleSecondaries().
G4bool G4VEmModel::UseBaseMaterials () const inline
Definition at line 750 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 750 of file G4VEmModel.hh
References useBaseMaterials.
Referenced by G4LossTableBuilder::BuildTableForModel().
G4double G4VEmModel::Value (const G4MaterialCutsCouple * couple, const G4ParticleDefinition * p, G4double kineticEnergy) virtual
Definition at line 415 of file G4VEmModel.cc.
View newest version in sPHENIX GitHub at line 415 of file G4VEmModel.cc
References CrossSectionPerVolume(), DBL_MAX, pBaseMaterial, pFactor, and SetCurrentCouple().
Referenced by G4IonParametrisedLossModel::BuildRangeVector(), G4LossTableBuilder::BuildTableForModel(), G4LivermorePolarizedPhotoElectricGDModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedPhotoElectricModel::ComputeCrossSectionPerAtom(), G4LivermorePhotoElectricModel::ComputeCrossSectionPerAtom(), G4IonParametrisedLossModel::ComputeLossForStep(), G4DNABornExcitationModel2::GetPartialCrossSection(), G4DNABornExcitationModel2::Initialise(), G4DNABornExcitationModel2::RandomSelect(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), and G4LivermorePhotoElectricModel::SampleSecondaries().
Member Data Documentation
G4VEmAngularDistribution* G4VEmModel::anglModel private
Definition at line 411 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 411 of file G4VEmModel.hh
Referenced by GetAngularDistribution(), SetAngularDistribution(), and ~G4VEmModel().
std::vector<G4EmElementSelector*>* G4VEmModel::elmSelectors private
Definition at line 433 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 433 of file G4VEmModel.hh
Referenced by G4VEmModel(), GetElementSelectors(), InitialiseElementSelectors(), SelectRandomAtom(), SelectTargetAtom(), SetElementSelectors(), and ~G4VEmModel().
G4double G4VEmModel::eMaxActive private
Definition at line 419 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 419 of file G4VEmModel.hh
Referenced by HighEnergyActivationLimit(), IsActive(), and SetActivationHighEnergyLimit().
G4double G4VEmModel::eMinActive private
Definition at line 418 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 418 of file G4VEmModel.hh
Referenced by IsActive(), LowEnergyActivationLimit(), and SetActivationLowEnergyLimit().
const G4MaterialCutsCouple* G4VEmModel::fCurrentCouple private
Definition at line 453 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 453 of file G4VEmModel.hh
Referenced by CurrentCouple(), and SetCurrentCouple().
const G4Element* G4VEmModel::fCurrentElement private
Definition at line 454 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 454 of file G4VEmModel.hh
Referenced by GetCurrentElement(), SelectRandomAtom(), SelectRandomAtomNumber(), SelectTargetAtom(), and SetCurrentElement().
const G4Isotope* G4VEmModel::fCurrentIsotope private
Definition at line 455 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 455 of file G4VEmModel.hh
Referenced by GetCurrentIsotope(), SelectIsotopeNumber(), SelectRandomAtom(), SelectTargetAtom(), and SetCurrentElement().
G4ElementData* G4VEmModel::fElementData protected
Definition at line 438 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 438 of file G4VEmModel.hh
Referenced by G4MuPairProductionModel::FindScaledEnergy(), GetElementData(), G4MuPairProductionModel::Initialise(), G4MuPairProductionModel::InitialiseLocal(), G4MuPairProductionModel::MakeSamplingTables(), G4MuPairProductionModel::RetrieveTables(), G4MuPairProductionModel::StoreTables(), and ~G4VEmModel().
G4LossTableManager* G4VEmModel::fEmManager private
Definition at line 434 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 434 of file G4VEmModel.hh
Referenced by G4VEmModel(), and ~G4VEmModel().
G4bool G4VEmModel::flagDeexcitation private
Definition at line 423 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 423 of file G4VEmModel.hh
Referenced by DeexcitationFlag(), and SetDeexcitationFlag().
G4bool G4VEmModel::flagForceBuildTable private
Definition at line 424 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 424 of file G4VEmModel.hh
Referenced by ForceBuildTableFlag(), and SetForceBuildTable().
G4VEmFluctuationModel* G4VEmModel::flucModel private
Definition at line 410 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 410 of file G4VEmModel.hh
Referenced by GetModelOfFluctuations(), and SetParticleChange().
G4VEmModel* G4VEmModel::fTripletModel private
Definition at line 456 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 456 of file G4VEmModel.hh
Referenced by GetParticleChangeForGamma(), GetParticleChangeForLoss(), GetTripletModel(), and SetTripletModel().
G4double G4VEmModel::highLimit private
Definition at line 417 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 417 of file G4VEmModel.hh
Referenced by HighEnergyLimit(), InitialiseElementSelectors(), and SetHighEnergyLimit().
size_t G4VEmModel::idxTable protected
Definition at line 444 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 444 of file G4VEmModel.hh
Referenced by G4VMscModel::GetParticleChangeForMSC(), and G4VMscModel::GetTransportMeanFreePath().
G4double G4VEmModel::inveplus protected
Definition at line 446 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 446 of file G4VEmModel.hh
Referenced by GetChargeSquareRatio(), G4VMscModel::GetDEDX(), G4VMscModel::GetEnergy(), G4VMscModel::GetRange(), G4LindhardSorensenIonModel::SetupParameters(), and G4BetheBlochModel::SetupParameters().
G4bool G4VEmModel::isLocked private
Definition at line 431 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 431 of file G4VEmModel.hh
Referenced by G4VEmModel(), IsLocked(), SetLocked(), and SetPolarAngleLimit().
G4bool G4VEmModel::isMaster private
Definition at line 425 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 425 of file G4VEmModel.hh
Referenced by IsMaster(), SetMasterThread(), and ~G4VEmModel().
G4bool G4VEmModel::localElmSelectors private
Definition at line 428 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 428 of file G4VEmModel.hh
Referenced by G4VEmModel(), SetElementSelectors(), and ~G4VEmModel().
G4bool G4VEmModel::localTable private
Definition at line 427 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 427 of file G4VEmModel.hh
Referenced by G4VEmModel(), SetCrossSectionTable(), and ~G4VEmModel().
G4bool G4VEmModel::lossFlucFlag protected
Definition at line 445 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 445 of file G4VEmModel.hh
Referenced by G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), and SetFluctuationFlag().
G4double G4VEmModel::lowLimit private
Definition at line 416 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 416 of file G4VEmModel.hh
Referenced by InitialiseElementSelectors(), LowEnergyLimit(), and SetLowEnergyLimit().
const G4String G4VEmModel::name private
Definition at line 412 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 412 of file G4VEmModel.hh
Referenced by GetName().
G4int G4VEmModel::nsec private
Definition at line 458 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 458 of file G4VEmModel.hh
Referenced by CrossSectionPerVolume(), and G4VEmModel().
G4int G4VEmModel::nSelectors private
Definition at line 432 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 432 of file G4VEmModel.hh
Referenced by G4VEmModel(), InitialiseElementSelectors(), SelectRandomAtom(), SelectTargetAtom(), SetElementSelectors(), and ~G4VEmModel().
const G4Material* G4VEmModel::pBaseMaterial protected
Definition at line 441 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 441 of file G4VEmModel.hh
Referenced by ComputeDEDX(), CrossSection(), SelectRandomAtom(), SelectTargetAtom(), SetCurrentCouple(), and Value().
G4double G4VEmModel::pFactor protected
Definition at line 447 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 447 of file G4VEmModel.hh
Referenced by ComputeDEDX(), CrossSection(), SetCurrentCouple(), and Value().
G4double G4VEmModel::polarAngleLimit private
Definition at line 420 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 420 of file G4VEmModel.hh
Referenced by PolarAngleLimit(), and SetPolarAngleLimit().
G4VParticleChange* G4VEmModel::pParticleChange protected
Definition at line 439 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 439 of file G4VEmModel.hh
Referenced by GetParticleChangeForGamma(), GetParticleChangeForLoss(), G4VMscModel::GetParticleChangeForMSC(), G4EmMultiModel::Initialise(), and SetParticleChange().
G4double G4VEmModel::secondaryThreshold private
Definition at line 421 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 421 of file G4VEmModel.hh
Referenced by SecondaryThreshold(), and SetSecondaryThreshold().
const std::vector<G4double>* G4VEmModel::theDensityFactor protected
Definition at line 442 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 442 of file G4VEmModel.hh
Referenced by G4VEmModel().
const std::vector<G4int>* G4VEmModel::theDensityIdx protected
Definition at line 443 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 443 of file G4VEmModel.hh
Referenced by G4VEmModel().
G4bool G4VEmModel::theLPMflag private
Definition at line 422 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 422 of file G4VEmModel.hh
Referenced by LPMFlag(), and SetLPMFlag().
G4bool G4VEmModel::useAngularGenerator private
Definition at line 429 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 429 of file G4VEmModel.hh
Referenced by G4VEmModel(), SetAngularGeneratorFlag(), and UseAngularGeneratorFlag().
G4bool G4VEmModel::useBaseMaterials private
Definition at line 430 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 430 of file G4VEmModel.hh
Referenced by G4VEmModel(), SetCurrentCouple(), SetUseBaseMaterials(), and UseBaseMaterials().
std::vector<G4double> G4VEmModel::xsec private
Definition at line 459 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 459 of file G4VEmModel.hh
Referenced by CrossSectionPerVolume(), G4VEmModel(), and SelectRandomAtom().
G4PhysicsTable* G4VEmModel::xSectionTable protected
Definition at line 440 of file G4VEmModel.hh.
View newest version in sPHENIX GitHub at line 440 of file G4VEmModel.hh
Referenced by GetCrossSectionTable(), G4VMscModel::GetParticleChangeForMSC(), G4VMscModel::GetTransportMeanFreePath(), SetCrossSectionTable(), and ~G4VEmModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4VEmModel.cc