ECCE @ EIC Software: G4Timer Class Reference
G4Timer Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4Timer.hh>
Public Member Functions
G4Timer ()
void Start ()
void Stop ()
G4bool IsValid () const
const char * GetClockTime () const
G4double GetRealElapsed () const
G4double GetSystemElapsed () const
G4double GetUserElapsed () const
Private Types
typedef
std::chrono::high_resolution_clock clock_type
Private Attributes
G4bool fValidTimes
std::chrono::time_point
< clock_type > fStartRealTime
std::chrono::time_point
< clock_type > fEndRealTime
tms fStartTimes
tms fEndTimes
Detailed Description
Definition at line 111 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Timer.hh
Member Typedef Documentation
typedef std::chrono::high_resolution_clock G4Timer::clock_type private
Definition at line 113 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 113 of file G4Timer.hh
Constructor & Destructor Documentation
G4Timer::G4Timer ()
Definition at line 121 of file G4Timer.cc.
View newest version in sPHENIX GitHub at line 121 of file G4Timer.cc
Member Function Documentation
const char* G4Timer::GetClockTime () const inline
G4double G4Timer::GetRealElapsed () const
Definition at line 126 of file G4Timer.cc.
View newest version in sPHENIX GitHub at line 126 of file G4Timer.cc
References FatalException, fEndRealTime, fStartRealTime, fValidTimes, and G4Exception().
Referenced by RMC01AnalysisManager::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), export_G4Timer(), main(), and operator<<().
G4double G4Timer::GetSystemElapsed () const
Definition at line 138 of file G4Timer.cc.
View newest version in sPHENIX GitHub at line 138 of file G4Timer.cc
References FatalException, fEndTimes, fStartTimes, fValidTimes, and G4Exception().
Referenced by G4ConvergenceTester::AddScore(), G4GeometryManager::BuildOptimisations(), ExGflashEventAction::EndOfEventAction(), export_G4Timer(), main(), operator<<(), and G4RunManager::ReOptimize().
G4double G4Timer::GetUserElapsed () const
Definition at line 149 of file G4Timer.cc.
View newest version in sPHENIX GitHub at line 149 of file G4Timer.cc
References FatalException, fEndTimes, fStartTimes, fValidTimes, and G4Exception().
Referenced by G4ConvergenceTester::AddScore(), G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4VXTRenergyLoss::BuildAngleTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4GeometryManager::BuildOptimisations(), ExGflashEventAction::EndOfEventAction(), CML2RunAction::EndOfRunAction(), export_G4Timer(), main(), operator<<(), and G4RunManager::ReOptimize().
G4bool G4Timer::IsValid () const inline
Referenced by export_G4Timer(), and operator<<().
void G4Timer::Start () inline
Referenced by ExGflashEventAction::BeginOfEventAction(), RMC01AnalysisManager::BeginOfRun(), eRositaRunAction::BeginOfRunAction(), OpNoviceRunAction::BeginOfRunAction(), GammaKnifeRunAction::BeginOfRunAction(), CML2RunAction::BeginOfRunAction(), G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4VXTRenergyLoss::BuildAngleTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4GeometryManager::BuildOptimisations(), CCalDetectorConstruction::Construct(), CexmcRunManager::DoEventLoop(), RMC01AnalysisManager::EndOfEvent(), export_G4Timer(), G4ConvergenceTester::G4ConvergenceTester(), G4MTRunManager::InitializeEventLoop(), G4RunManager::InitializeEventLoop(), main(), CCalG4Able::PhysicalVolume(), G4Scheduler::Process(), G4RunManager::ReOptimize(), and G4ProductionCutsTable::UpdateCoupleTable().
void G4Timer::Stop () inline
Referenced by G4ConvergenceTester::AddScore(), G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4VXTRenergyLoss::BuildAngleTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4GeometryManager::BuildOptimisations(), CCalDetectorConstruction::Construct(), CexmcRunManager::DoEventLoop(), RMC01AnalysisManager::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfRun(), eRositaRunAction::EndOfRunAction(), OpNoviceRunAction::EndOfRunAction(), GammaKnifeRunAction::EndOfRunAction(), CML2RunAction::EndOfRunAction(), export_G4Timer(), main(), CCalG4Able::PhysicalVolume(), G4Scheduler::Process(), G4RunManager::ReOptimize(), G4WorkerRunManager::TerminateEventLoop(), G4RunManager::TerminateEventLoop(), and G4ProductionCutsTable::UpdateCoupleTable().
Member Data Documentation
std::chrono::time_point<clock_type> G4Timer::fEndRealTime private
Definition at line 130 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 130 of file G4Timer.hh
Referenced by GetRealElapsed().
tms G4Timer::fEndTimes private
Definition at line 131 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 131 of file G4Timer.hh
Referenced by GetSystemElapsed(), and GetUserElapsed().
std::chrono::time_point<clock_type> G4Timer::fStartRealTime private
Definition at line 130 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 130 of file G4Timer.hh
Referenced by GetRealElapsed().
tms G4Timer::fStartTimes private
Definition at line 131 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 131 of file G4Timer.hh
Referenced by GetSystemElapsed(), and GetUserElapsed().
G4bool G4Timer::fValidTimes private
Definition at line 129 of file G4Timer.hh.
View newest version in sPHENIX GitHub at line 129 of file G4Timer.hh
Referenced by GetRealElapsed(), GetSystemElapsed(), and GetUserElapsed().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4Timer.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4Timer.cc