ECCE @ EIC Software: G4NavigationLevelRep Class Reference
G4NavigationLevelRep Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationLevelRep.hh>
Public Member Functions
G4NavigationLevelRep (G4VPhysicalVolume *newPtrPhysVol, const G4AffineTransform &newT, EVolume newVolTp, G4int newRepNo=-1)
G4NavigationLevelRep (G4VPhysicalVolume *newPtrPhysVol, const G4AffineTransform &levelAbove, const G4AffineTransform &relativeCurrent, EVolume newVolTp, G4int newRepNo=-1)
G4NavigationLevelRep ()
G4NavigationLevelRep (G4NavigationLevelRep &)
~G4NavigationLevelRep ()
G4NavigationLevelRep & operator= (const G4NavigationLevelRep &right)
G4VPhysicalVolume * GetPhysicalVolume ()
const G4AffineTransform * GetTransformPtr () const
const G4AffineTransform & GetTransform () const
EVolume GetVolumeType () const
G4int GetReplicaNo () const
void AddAReference ()
G4bool RemoveAReference ()
void * operator new (size_t)
void operator delete (void *aTrack)
Private Attributes
G4AffineTransform sTransform
G4VPhysicalVolume * sPhysicalVolumePtr = nullptr
G4int sReplicaNo = -1
EVolume sVolumeType
G4int fCountRef = 1
Detailed Description
Definition at line 50 of file G4NavigationLevelRep.hh.
View newest version in sPHENIX GitHub at line 50 of file G4NavigationLevelRep.hh
Constructor & Destructor Documentation
G4NavigationLevelRep::G4NavigationLevelRep (G4VPhysicalVolume * newPtrPhysVol, const G4AffineTransform & newT, EVolume newVolTp, G4int newRepNo = -1) inline
G4NavigationLevelRep::G4NavigationLevelRep (G4VPhysicalVolume * newPtrPhysVol, const G4AffineTransform & levelAbove, const G4AffineTransform & relativeCurrent, EVolume newVolTp, G4int newRepNo = -1) inline
G4NavigationLevelRep::G4NavigationLevelRep () inline
G4NavigationLevelRep::G4NavigationLevelRep (G4NavigationLevelRep &) inline
G4NavigationLevelRep::~G4NavigationLevelRep () inline
Member Function Documentation
void G4NavigationLevelRep::AddAReference () inline
Referenced by G4NavigationLevel::G4NavigationLevel(), and G4NavigationLevel::operator=().
G4VPhysicalVolume* G4NavigationLevelRep::GetPhysicalVolume () inline
G4int G4NavigationLevelRep::GetReplicaNo () const inline
const G4AffineTransform& G4NavigationLevelRep::GetTransform () const inline
const G4AffineTransform* G4NavigationLevelRep::GetTransformPtr () const inline
EVolume G4NavigationLevelRep::GetVolumeType () const inline
void G4NavigationLevelRep::operator delete (void * aTrack) inline
void* G4NavigationLevelRep::operator new (size_t) inline
G4NavigationLevelRep& G4NavigationLevelRep::operator= (const G4NavigationLevelRep & right) inline
G4bool G4NavigationLevelRep::RemoveAReference () inline
Referenced by G4NavigationLevel::operator=(), and G4NavigationLevel::~G4NavigationLevel().
Member Data Documentation
G4int G4NavigationLevelRep::fCountRef = 1 private
Definition at line 106 of file G4NavigationLevelRep.hh.
View newest version in sPHENIX GitHub at line 106 of file G4NavigationLevelRep.hh
G4VPhysicalVolume* G4NavigationLevelRep::sPhysicalVolumePtr = nullptr private
Definition at line 99 of file G4NavigationLevelRep.hh.
View newest version in sPHENIX GitHub at line 99 of file G4NavigationLevelRep.hh
G4int G4NavigationLevelRep::sReplicaNo = -1 private
Definition at line 102 of file G4NavigationLevelRep.hh.
View newest version in sPHENIX GitHub at line 102 of file G4NavigationLevelRep.hh
G4AffineTransform G4NavigationLevelRep::sTransform private
Definition at line 95 of file G4NavigationLevelRep.hh.
View newest version in sPHENIX GitHub at line 95 of file G4NavigationLevelRep.hh
EVolume G4NavigationLevelRep::sVolumeType private
Definition at line 103 of file G4NavigationLevelRep.hh.
View newest version in sPHENIX GitHub at line 103 of file G4NavigationLevelRep.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationLevelRep.hh