ECCE @ EIC Software: G4INCL::Config Class Reference
G4INCL::Config Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLConfig.hh>
Public Member Functions
Config ()
Default constructor.
~Config ()
Default destructor.
void init ()
Initialise the members.
std::string summary ()
Return a summary of the run configuration.
G4int getVerbosity () const
Get the verbosity.
std::string const & getCalculationTitle () const
Get the run title.
std::string const & getOutputFileRoot () const
Get the output file root.
G4int getNumberOfShots () const
Get the number of shots.
G4bool isNaturalTarget () const
Natural targets.
G4int getTargetA () const
Get the target mass number.
G4int getTargetZ () const
Get the target charge number.
G4int getTargetS () const
Get the target strangess number.
void setTargetA (G4int A)
Set target mass number.
void setTargetZ (G4int Z)
Set target charge number.
void setTargetS (G4int S)
Set target strangess number.
ParticleType getProjectileType () const
Get the projectile type.
ParticleSpecies getProjectileSpecies () const
Get the projectile species.
void setProjectileSpecies (ParticleSpecies const &ps)
Set the projectile species.
G4double getProjectileKineticEnergy () const
Get the projectile kinetic energy.
void setProjectileKineticEnergy (G4double const kinE)
Set the projectile kinetic energy.
G4int getVerboseEvent () const
Get the number of the verbose event.
Random::SeedVector getRandomSeeds () const
Get the seeds for the random-number generator.
PauliType getPauliType () const
Get the Pauli-blocking algorithm.
G4bool getCDPP () const
Do we want CDPP?
CoulombType getCoulombType () const
Get the Coulomb-distortion algorithm.
void setCoulombType (CoulombType const c)
Set the Coulomb-distortion algorithm.
PotentialType getPotentialType () const
Get the type of the potential for nucleons.
void setPotentialType (PotentialType type)
Set the type of the potential for nucleons.
G4bool getPionPotential () const
Do we want the pion potential?
void setPionPotential (const G4bool pionPot)
Set the type of the potential for nucleons.
LocalEnergyType getLocalEnergyBBType () const
Get the type of local energy for N-N avatars.
void setLocalEnergyBBType (const LocalEnergyType t)
Set the type of local energy for N-N avatars.
LocalEnergyType getLocalEnergyPiType () const
Get the type of local energy for pi-N and decay avatars.
void setLocalEnergyPiType (const LocalEnergyType t)
Set the type of local energy for N-N avatars.
std::string const & getLogFileName () const
Get the log file name.
DeExcitationType getDeExcitationType () const
Get the de-excitation model.
std::string getDeExcitationString () const
Get the de-excitation string.
ClusterAlgorithmType getClusterAlgorithm () const
Get the clustering algorithm.
void setClusterAlgorithm (ClusterAlgorithmType const c)
Set the clustering algorithm.
G4int getClusterMaxMass () const
Get the maximum mass for production of clusters.
void setClusterMaxMass (const G4int m)
Set the maximum mass for production of clusters.
G4bool getBackToSpectator () const
Get back-to-spectator.
void setBackToSpectator (const G4bool b)
Set back-to-spectator.
G4bool getUseRealMasses () const
Whether to use real masses.
void setUseRealMasses (G4bool use)
Set whether to use real masses.
void setINCLXXDataFilePath (std::string const &s)
Set the INCLXX datafile path.
std::string const & getINCLXXDataFilePath () const
G4double getImpactParameter () const
SeparationEnergyType getSeparationEnergyType () const
Get the separation-energy type.
FermiMomentumType getFermiMomentumType () const
Get the Fermi-momentum type.
void setFermiMomentumType (FermiMomentumType const f)
Set the Fermi-momentum type.
G4double getFermiMomentum () const
Get the Fermi momentum.
void setFermiMomentum (const G4double p)
Set the Fermi momentum.
G4double getCutNN () const
G4double getRPCorrelationCoefficient (const ParticleType t) const
Get the r-p correlation coefficient.
void setRPCorrelationCoefficient (const ParticleType t, const G4double corrCoeff)
Set the r-p correlation coefficient.
void setRPCorrelationCoefficient (const G4double corrCoeff)
Set the r-p correlation coefficient.
G4double getNeutronSkin () const
Get the neutron-skin thickness.
void setNeutronSkin (const G4double d)
Set the neutron-skin thickness.
G4double getNeutronHalo () const
Get the neutron-halo size.
void setNeutronHalo (const G4double d)
Set the neutron-halo size.
G4bool getRefraction () const
True if we should use refraction.
void setRefraction (const G4bool r)
Set the refraction variable.
RNGType getRNGType () const
Get the RNG type.
void setRNGType (RNGType const r)
Set the RNG type.
PhaseSpaceGeneratorType getPhaseSpaceGeneratorType () const
Get the phase-space-generator type.
void setPhaseSpaceGeneratorType (PhaseSpaceGeneratorType const p)
Set the phase-space-generator type.
CascadeActionType getCascadeActionType () const
Get the cascade-action type.
void setCascadeActionType (CascadeActionType const c)
Set the cascade-action type.
unsigned int getAutosaveFrequency () const
Get the autosave frequency.
void setAutosaveFrequency (const unsigned int f)
Set the autosave frequency.
CrossSectionsType getCrossSectionsType () const
Get the Cross Section type.
G4int getMaxNumberMultipions () const
Get the maximum number of pions for multipion collisions.
void setMaxNumberMultipions (const G4int n)
Set the maximum number of pions for multipion collisions.
void setCrossSectionsType (CrossSectionsType const c)
Set the Cross Section type.
G4double getHadronizationTime () const
Get the hadronization time.
void setHadronizationTime (const G4double t)
Set the hadronization time.
G4bool getInverseKinematics () const
G4double getDecayTimeThreshold () const
Get the decay time threshold time.
void setDecayTimeThreshold (const G4double t)
Set decay time threshold time.
G4double getBias () const
Get the bias.
Static Public Member Functions
static std::string const getVersionID ()
Get the INCL version ID.
static std::string const getVersionHash ()
Get the INCL version hash.
static std::string const getVersionString ()
Get the INCL version string.
Private Attributes
G4int verbosity
std::string inputFileName
std::string title
std::string outputFileRoot
std::string fileSuffix
std::string logFileName
G4int nShots
std::string targetString
ParticleSpecies targetSpecies
G4bool naturalTarget
std::string projectileString
ParticleSpecies projectileSpecies
G4double projectileKineticEnergy
G4int verboseEvent
std::string randomSeeds
Random::SeedVector randomSeedVector
std::string pauliString
PauliType pauliType
G4bool CDPP
std::string coulombString
CoulombType coulombType
std::string potentialString
PotentialType potentialType
G4bool pionPotential
std::string localEnergyBBString
LocalEnergyType localEnergyBBType
std::string localEnergyPiString
LocalEnergyType localEnergyPiType
std::string deExcitationModelList
std::string deExcitationOptionDescription
std::string deExcitationString
DeExcitationType deExcitationType
std::string INCLXXDataFilePath
std::string clusterAlgorithmString
ClusterAlgorithmType clusterAlgorithmType
G4int clusterMaxMass
G4bool backToSpectator
G4bool useRealMasses
G4double impactParameter
std::string separationEnergyString
SeparationEnergyType separationEnergyType
std::string fermiMomentumString
FermiMomentumType fermiMomentumType
G4double fermiMomentum
G4double cutNN
G4double bias
G4double rpCorrelationCoefficient
G4double rpCorrelationCoefficientProton
G4double rpCorrelationCoefficientNeutron
G4double neutronSkin
G4double neutronHalo
G4bool refraction
std::string randomNumberGenerator
RNGType rngType
std::string phaseSpaceGenerator
PhaseSpaceGeneratorType phaseSpaceGeneratorType
unsigned int autosaveFrequency
std::string crossSectionsString
CrossSectionsType crossSectionsType
G4int maxNumberMultipions
std::string cascadeAction
CascadeActionType cascadeActionType
G4double hadronizationTime
G4bool inverseKinematics
G4double decayTimeThreshold
Friends
class ::ConfigParser
Detailed Description
The INCL configuration object
The Config object keeps track of various INCL physics options (e.g. which Pauli blocking scheme to use, whether to use local energy option or not, etc.
Definition at line 60 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLConfig.hh
Constructor & Destructor Documentation
G4INCL::Config::Config ()
Default constructor.
Definition at line 45 of file G4INCLConfig.cc.
View newest version in sPHENIX GitHub at line 45 of file G4INCLConfig.cc
References init().
G4INCL::Config::~Config ()
Default destructor.
Definition at line 49 of file G4INCLConfig.cc.
View newest version in sPHENIX GitHub at line 49 of file G4INCLConfig.cc
Member Function Documentation
unsigned int G4INCL::Config::getAutosaveFrequency () const inline
Get the autosave frequency.
Definition at line 339 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 339 of file G4INCLConfig.hh
References autosaveFrequency.
G4bool G4INCL::Config::getBackToSpectator () const inline
Get back-to-spectator.
Definition at line 205 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 205 of file G4INCLConfig.hh
References backToSpectator.
Referenced by G4INCL::InteractionAvatar::postInteraction().
G4double G4INCL::Config::getBias () const inline
Get the bias.
Definition at line 375 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 375 of file G4INCLConfig.hh
References bias.
Referenced by G4INCL::INCL::INCL().
std::string const& G4INCL::Config::getCalculationTitle () const inline
Get the run title.
Definition at line 78 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 78 of file G4INCLConfig.hh
References title.
CascadeActionType G4INCL::Config::getCascadeActionType () const inline
Get the cascade-action type.
Definition at line 333 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 333 of file G4INCLConfig.hh
References cascadeActionType.
Referenced by G4INCL::INCL::INCL().
G4bool G4INCL::Config::getCDPP () const inline
Do we want CDPP?
Definition at line 151 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 151 of file G4INCLConfig.hh
References CDPP.
Referenced by G4INCL::Pauli::initialize().
ClusterAlgorithmType G4INCL::Config::getClusterAlgorithm () const inline
Get the clustering algorithm.
Definition at line 193 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 193 of file G4INCLConfig.hh
References clusterAlgorithmType.
Referenced by G4INCL::Clustering::initialize().
G4int G4INCL::Config::getClusterMaxMass () const inline
Get the maximum mass for production of clusters.
Definition at line 199 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 199 of file G4INCLConfig.hh
References clusterMaxMass.
Referenced by G4INCL::ClusteringModelIntercomparison::getCluster(), and G4INCLXXInterfaceStore::SetMaxClusterMass().
CoulombType G4INCL::Config::getCoulombType () const inline
Get the Coulomb-distortion algorithm.
Definition at line 154 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 154 of file G4INCLConfig.hh
References coulombType.
Referenced by G4INCL::CoulombDistortion::initialize().
CrossSectionsType G4INCL::Config::getCrossSectionsType () const inline
Get the Cross Section type.
Definition at line 345 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 345 of file G4INCLConfig.hh
References crossSectionsType.
Referenced by G4INCL::CrossSections::initialize().
G4double G4INCL::Config::getCutNN () const inline
Definition at line 263 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 263 of file G4INCLConfig.hh
References cutNN.
Referenced by G4INCL::INCL::INCL().
G4double G4INCL::Config::getDecayTimeThreshold () const inline
Get the decay time threshold time.
Definition at line 369 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 369 of file G4INCLConfig.hh
References decayTimeThreshold.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
std::string G4INCL::Config::getDeExcitationString () const inline
Get the de-excitation string.
Definition at line 190 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 190 of file G4INCLConfig.hh
References deExcitationString.
Referenced by G4INCL::INCL::INCL().
DeExcitationType G4INCL::Config::getDeExcitationType () const inline
Get the de-excitation model.
Definition at line 187 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 187 of file G4INCLConfig.hh
References deExcitationType.
G4double G4INCL::Config::getFermiMomentum () const inline
Get the Fermi momentum.
Definition at line 258 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 258 of file G4INCLConfig.hh
References fermiMomentum.
Referenced by G4INCL::ParticleTable::initialize().
FermiMomentumType G4INCL::Config::getFermiMomentumType () const inline
Get the Fermi-momentum type.
Definition at line 252 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 252 of file G4INCLConfig.hh
References fermiMomentumType.
Referenced by G4INCL::ParticleTable::initialize().
G4double G4INCL::Config::getHadronizationTime () const inline
Get the hadronization time.
Definition at line 357 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 357 of file G4INCLConfig.hh
References hadronizationTime.
Referenced by G4INCL::INCL::INCL().
G4double G4INCL::Config::getImpactParameter () const inline
Definition at line 246 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 246 of file G4INCLConfig.hh
References impactParameter.
Referenced by G4INCL::INCL::INCL().
std::string const& G4INCL::Config::getINCLXXDataFilePath () const inline
Definition at line 219 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 219 of file G4INCLConfig.hh
References INCLXXDataFilePath.
Referenced by G4INCL::ParticleTable::initialize().
G4bool G4INCL::Config::getInverseKinematics () const inline
Definition at line 366 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 366 of file G4INCLConfig.hh
References inverseKinematics.
LocalEnergyType G4INCL::Config::getLocalEnergyBBType () const inline
Get the type of local energy for N-N avatars.
Definition at line 172 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 172 of file G4INCLConfig.hh
References localEnergyBBType.
Referenced by G4INCL::INCL::INCL(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
LocalEnergyType G4INCL::Config::getLocalEnergyPiType () const inline
Get the type of local energy for pi-N and decay avatars.
Definition at line 178 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 178 of file G4INCLConfig.hh
References localEnergyPiType.
Referenced by G4INCL::INCL::INCL(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
std::string const& G4INCL::Config::getLogFileName () const inline
Get the log file name.
Definition at line 184 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 184 of file G4INCLConfig.hh
References logFileName.
G4int G4INCL::Config::getMaxNumberMultipions () const inline
Get the maximum number of pions for multipion collisions.
Definition at line 348 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 348 of file G4INCLConfig.hh
References maxNumberMultipions.
Referenced by G4INCL::CrossSections::initialize().
G4double G4INCL::Config::getNeutronHalo () const inline
Get the neutron-halo size.
Definition at line 309 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 309 of file G4INCLConfig.hh
References neutronHalo.
Referenced by G4INCL::ParticleTable::initialize().
G4double G4INCL::Config::getNeutronSkin () const inline
Get the neutron-skin thickness.
Definition at line 303 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 303 of file G4INCLConfig.hh
References neutronSkin.
Referenced by G4INCL::ParticleTable::initialize().
G4int G4INCL::Config::getNumberOfShots () const inline
Get the number of shots.
Definition at line 84 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 84 of file G4INCLConfig.hh
References nShots.
std::string const& G4INCL::Config::getOutputFileRoot () const inline
Get the output file root.
Definition at line 81 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 81 of file G4INCLConfig.hh
References outputFileRoot.
PauliType G4INCL::Config::getPauliType () const inline
Get the Pauli-blocking algorithm.
Definition at line 148 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 148 of file G4INCLConfig.hh
References pauliType.
Referenced by G4INCL::Pauli::initialize().
PhaseSpaceGeneratorType G4INCL::Config::getPhaseSpaceGeneratorType () const inline
Get the phase-space-generator type.
Definition at line 327 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 327 of file G4INCLConfig.hh
References phaseSpaceGeneratorType.
Referenced by G4INCL::PhaseSpaceGenerator::initialize().
G4bool G4INCL::Config::getPionPotential () const inline
Do we want the pion potential?
Definition at line 166 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 166 of file G4INCLConfig.hh
References pionPotential.
Referenced by G4INCL::Nucleus::Nucleus().
PotentialType G4INCL::Config::getPotentialType () const inline
Get the type of the potential for nucleons.
Definition at line 160 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 160 of file G4INCLConfig.hh
References potentialType.
Referenced by G4INCL::Nucleus::Nucleus().
G4double G4INCL::Config::getProjectileKineticEnergy () const inline
Get the projectile kinetic energy.
Definition at line 121 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 121 of file G4INCLConfig.hh
References projectileKineticEnergy.
Referenced by G4INCL::INCL::INCL(), and G4INCL::INCL::processEvent().
ParticleSpecies G4INCL::Config::getProjectileSpecies () const inline
Get the projectile species.
Definition at line 115 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 115 of file G4INCLConfig.hh
References projectileSpecies.
Referenced by G4INCL::INCL::INCL(), and G4INCL::INCL::processEvent().
ParticleType G4INCL::Config::getProjectileType () const inline
Get the projectile type.
Definition at line 112 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 112 of file G4INCLConfig.hh
References projectileSpecies, and G4INCL::ParticleSpecies::theType.
Random::SeedVector G4INCL::Config::getRandomSeeds () const inline
Get the seeds for the random-number generator.
Definition at line 143 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 143 of file G4INCLConfig.hh
References randomSeedVector.
G4bool G4INCL::Config::getRefraction () const inline
True if we should use refraction.
Definition at line 315 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 315 of file G4INCLConfig.hh
References refraction.
Referenced by G4INCL::SurfaceAvatar::getChannel(), G4INCL::SurfaceAvatar::getTransmissionProbability(), and G4INCL::ParticleEntryChannel::particleEnters().
RNGType G4INCL::Config::getRNGType () const inline
Get the RNG type.
Definition at line 321 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 321 of file G4INCLConfig.hh
References rngType.
G4double G4INCL::Config::getRPCorrelationCoefficient (const ParticleType t) const inline
Get the r-p correlation coefficient.
Definition at line 282 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 282 of file G4INCLConfig.hh
References G4INCL::Proton, rpCorrelationCoefficientNeutron, and rpCorrelationCoefficientProton.
Referenced by G4INCL::ParticleTable::initialize().
SeparationEnergyType G4INCL::Config::getSeparationEnergyType () const inline
Get the separation-energy type.
Definition at line 249 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 249 of file G4INCLConfig.hh
References separationEnergyType.
Referenced by G4INCL::ParticleTable::initialize().
G4int G4INCL::Config::getTargetA () const inline
Get the target mass number.
Note that A==0 means natural target. You should first check the isNaturalTarget() method.
Definition at line 94 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 94 of file G4INCLConfig.hh
References targetSpecies, and G4INCL::ParticleSpecies::theA.
Referenced by G4INCL::INCL::INCL(), and G4INCL::INCL::processEvent().
G4int G4INCL::Config::getTargetS () const inline
Get the target strangess number.
Definition at line 100 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 100 of file G4INCLConfig.hh
References targetSpecies, and G4INCL::ParticleSpecies::theS.
Referenced by G4INCL::INCL::processEvent().
G4int G4INCL::Config::getTargetZ () const inline
Get the target charge number.
Definition at line 97 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 97 of file G4INCLConfig.hh
References targetSpecies, and G4INCL::ParticleSpecies::theZ.
Referenced by G4INCL::INCL::INCL(), and G4INCL::INCL::processEvent().
G4bool G4INCL::Config::getUseRealMasses () const inline
Whether to use real masses.
Definition at line 211 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 211 of file G4INCLConfig.hh
References useRealMasses.
Referenced by G4INCL::ParticleTable::initialize().
G4int G4INCL::Config::getVerboseEvent () const inline
Get the number of the verbose event.
Definition at line 127 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 127 of file G4INCLConfig.hh
References verboseEvent.
G4int G4INCL::Config::getVerbosity () const inline
Get the verbosity.
Definition at line 75 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLConfig.hh
References verbosity.
std::string const G4INCL::Config::getVersionHash () static
Get the INCL version hash.
Definition at line 56 of file G4INCLConfigVersion.cc.
View newest version in sPHENIX GitHub at line 56 of file G4INCLConfigVersion.cc
References G4INCL_GIT_HASH.
Referenced by getVersionString().
std::string const G4INCL::Config::getVersionID () static
Get the INCL version ID.
Definition at line 54 of file G4INCLConfigVersion.cc.
View newest version in sPHENIX GitHub at line 54 of file G4INCLConfigVersion.cc
References G4INCL_VERSION_ID.
Referenced by getVersionString().
static std::string const G4INCL::Config::getVersionString () inline static
Get the INCL version string.
Definition at line 136 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 136 of file G4INCLConfig.hh
References getVersionHash(), and getVersionID().
Referenced by G4INCL::INCL::INCL(), and summary().
void G4INCL::Config::init (void)
Initialise the members.
Definition at line 51 of file G4INCLConfig.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLConfig.cc
References autosaveFrequency, backToSpectator, bias, cascadeAction, cascadeActionType, clusterAlgorithmString, clusterAlgorithmType, clusterMaxMass, G4INCL::ConstantFermiMomentum, coulombString, coulombType, crossSectionsString, crossSectionsType, cutNN, decayTimeThreshold, G4INCL::DeExcitationNone, deExcitationString, deExcitationType, G4INCL::DefaultActionType, fermiMomentum, fermiMomentumString, fermiMomentumType, G4INCL::FirstCollisionLocalEnergy, hadronizationTime, impactParameter, G4INCL::INCLSeparationEnergy, inputFileName, G4INCL::IntercomparisonClusterAlgorithm, inverseKinematics, G4INCL::IsospinEnergyPotential, localEnergyBBString, localEnergyBBType, localEnergyPiString, localEnergyPiType, logFileName, maxNumberMultipions, naturalTarget, neutronHalo, neutronSkin, G4INCL::NonRelativisticCoulomb, nShots, pauliString, pauliType, phaseSpaceGenerator, phaseSpaceGeneratorType, pionPotential, potentialString, potentialType, projectileKineticEnergy, projectileSpecies, projectileString, G4INCL::Proton, randomNumberGenerator, randomSeeds, randomSeedVector, G4INCL::RanecuType, G4INCL::RauboldLynchType, refraction, rngType, rpCorrelationCoefficient, rpCorrelationCoefficientNeutron, rpCorrelationCoefficientProton, separationEnergyString, separationEnergyType, G4INCL::StrangenessCrossSections, G4INCL::StrictStatisticalPauli, title, useRealMasses, verboseEvent, and verbosity.
Referenced by Config(), and G4INCLXXInterfaceStore::SetINCLPhysics().
G4bool G4INCL::Config::isNaturalTarget () const inline
Natural targets.
Definition at line 87 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 87 of file G4INCLConfig.hh
References naturalTarget.
Referenced by G4INCL::INCL::prepareReaction().
void G4INCL::Config::setAutosaveFrequency (const unsigned int f) inline
Set the autosave frequency.
Definition at line 342 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 342 of file G4INCLConfig.hh
References autosaveFrequency, and f.
void G4INCL::Config::setBackToSpectator (const G4bool b) inline
Set back-to-spectator.
Definition at line 208 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 208 of file G4INCLConfig.hh
References b, and backToSpectator.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setCascadeActionType (CascadeActionType const c) inline
Set the cascade-action type.
Definition at line 336 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 336 of file G4INCLConfig.hh
References c, and cascadeActionType.
void G4INCL::Config::setClusterAlgorithm (ClusterAlgorithmType const c) inline
Set the clustering algorithm.
Definition at line 196 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 196 of file G4INCLConfig.hh
References c, and clusterAlgorithmType.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setClusterMaxMass (const G4int m) inline
Set the maximum mass for production of clusters.
Definition at line 202 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 202 of file G4INCLConfig.hh
References clusterMaxMass, and m.
Referenced by G4INCLXXInterfaceStore::SetMaxClusterMass().
void G4INCL::Config::setCoulombType (CoulombType const c) inline
Set the Coulomb-distortion algorithm.
Definition at line 157 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 157 of file G4INCLConfig.hh
References c, and coulombType.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setCrossSectionsType (CrossSectionsType const c) inline
Set the Cross Section type.
Definition at line 354 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 354 of file G4INCLConfig.hh
References c, and crossSectionsType.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setDecayTimeThreshold (const G4double t) inline
Set decay time threshold time.
Definition at line 372 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 372 of file G4INCLConfig.hh
References decayTimeThreshold, and t.
void G4INCL::Config::setFermiMomentum (const G4double p) inline
Set the Fermi momentum.
Definition at line 261 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 261 of file G4INCLConfig.hh
References fermiMomentum.
void G4INCL::Config::setFermiMomentumType (FermiMomentumType const f) inline
Set the Fermi-momentum type.
Definition at line 255 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 255 of file G4INCLConfig.hh
References f, and fermiMomentumType.
void G4INCL::Config::setHadronizationTime (const G4double t) inline
Set the hadronization time.
Definition at line 360 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 360 of file G4INCLConfig.hh
References hadronizationTime, and t.
void G4INCL::Config::setINCLXXDataFilePath (std::string const & s) inline
Set the INCLXX datafile path.
Definition at line 217 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 217 of file G4INCLConfig.hh
References INCLXXDataFilePath.
void G4INCL::Config::setLocalEnergyBBType (const LocalEnergyType t) inline
Set the type of local energy for N-N avatars.
Definition at line 175 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 175 of file G4INCLConfig.hh
References localEnergyBBType, and t.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setLocalEnergyPiType (const LocalEnergyType t) inline
Set the type of local energy for N-N avatars.
Definition at line 181 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 181 of file G4INCLConfig.hh
References localEnergyPiType, and t.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setMaxNumberMultipions (const G4int n) inline
Set the maximum number of pions for multipion collisions.
Definition at line 351 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 351 of file G4INCLConfig.hh
References maxNumberMultipions, and n.
void G4INCL::Config::setNeutronHalo (const G4double d) inline
Set the neutron-halo size.
Definition at line 312 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 312 of file G4INCLConfig.hh
References d, and neutronHalo.
void G4INCL::Config::setNeutronSkin (const G4double d) inline
Set the neutron-skin thickness.
Definition at line 306 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 306 of file G4INCLConfig.hh
References d, and neutronSkin.
void G4INCL::Config::setPhaseSpaceGeneratorType (PhaseSpaceGeneratorType const p) inline
Set the phase-space-generator type.
Definition at line 330 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 330 of file G4INCLConfig.hh
References phaseSpaceGeneratorType.
void G4INCL::Config::setPionPotential (const G4bool pionPot) inline
Set the type of the potential for nucleons.
Definition at line 169 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 169 of file G4INCLConfig.hh
References pionPotential.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setPotentialType (PotentialType type) inline
Set the type of the potential for nucleons.
Definition at line 163 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 163 of file G4INCLConfig.hh
References potentialType.
Referenced by G4INCLXXInterfaceStore::SetINCLPhysics().
void G4INCL::Config::setProjectileKineticEnergy (G4double const kinE) inline
Set the projectile kinetic energy.
Definition at line 124 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 124 of file G4INCLConfig.hh
References projectileKineticEnergy.
void G4INCL::Config::setProjectileSpecies (ParticleSpecies const & ps) inline
Set the projectile species.
Definition at line 118 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 118 of file G4INCLConfig.hh
References projectileSpecies, and ps.
void G4INCL::Config::setRefraction (const G4bool r) inline
Set the refraction variable.
Definition at line 318 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 318 of file G4INCLConfig.hh
References r, and refraction.
void G4INCL::Config::setRNGType (RNGType const r) inline
Set the RNG type.
Definition at line 324 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 324 of file G4INCLConfig.hh
References r, and rngType.
void G4INCL::Config::setRPCorrelationCoefficient (const ParticleType t, const G4double corrCoeff) inline
Set the r-p correlation coefficient.
Definition at line 288 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 288 of file G4INCLConfig.hh
References G4INCL::Proton, rpCorrelationCoefficientNeutron, and rpCorrelationCoefficientProton.
Referenced by setRPCorrelationCoefficient().
void G4INCL::Config::setRPCorrelationCoefficient (const G4double corrCoeff) inline
Set the r-p correlation coefficient.
Definition at line 297 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 297 of file G4INCLConfig.hh
References G4INCL::Neutron, G4INCL::Proton, and setRPCorrelationCoefficient().
void G4INCL::Config::setTargetA (G4int A) inline
Set target mass number.
Definition at line 103 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 103 of file G4INCLConfig.hh
References A(), targetSpecies, and G4INCL::ParticleSpecies::theA.
void G4INCL::Config::setTargetS (G4int S) inline
Set target strangess number.
Definition at line 109 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 109 of file G4INCLConfig.hh
References S(), targetSpecies, and G4INCL::ParticleSpecies::theS.
void G4INCL::Config::setTargetZ (G4int Z) inline
Set target charge number.
Definition at line 106 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 106 of file G4INCLConfig.hh
References targetSpecies, G4INCL::ParticleSpecies::theZ, and Z.
void G4INCL::Config::setUseRealMasses (G4bool use) inline
Set whether to use real masses.
Definition at line 214 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 214 of file G4INCLConfig.hh
References useRealMasses.
std::string G4INCL::Config::summary ()
Return a summary of the run configuration.
Definition at line 121 of file G4INCLConfig.cc.
View newest version in sPHENIX GitHub at line 121 of file G4INCLConfig.cc
References G4INCL::Composite, G4INCL::ParticleTable::getName(), getVersionString(), message(), nShots, projectileKineticEnergy, projectileSpecies, targetSpecies, G4INCL::ParticleSpecies::theA, G4INCL::ParticleSpecies::theS, G4INCL::ParticleSpecies::theType, and G4INCL::ParticleSpecies::theZ.
Friends And Related Function Documentation
friend class ::ConfigParser friend
Definition at line 502 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 502 of file G4INCLConfig.hh
Member Data Documentation
unsigned int G4INCL::Config::autosaveFrequency private
Definition at line 483 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 483 of file G4INCLConfig.hh
Referenced by getAutosaveFrequency(), init(), and setAutosaveFrequency().
G4bool G4INCL::Config::backToSpectator private
Definition at line 441 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 441 of file G4INCLConfig.hh
Referenced by getBackToSpectator(), init(), and setBackToSpectator().
G4double G4INCL::Config::bias private
Definition at line 457 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 457 of file G4INCLConfig.hh
Referenced by getBias(), and init().
std::string G4INCL::Config::cascadeAction private
Definition at line 489 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 489 of file G4INCLConfig.hh
Referenced by init().
CascadeActionType G4INCL::Config::cascadeActionType private
Definition at line 490 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 490 of file G4INCLConfig.hh
Referenced by getCascadeActionType(), init(), and setCascadeActionType().
G4bool G4INCL::Config::CDPP private
Definition at line 403 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 403 of file G4INCLConfig.hh
Referenced by getCDPP().
std::string G4INCL::Config::clusterAlgorithmString private
Definition at line 436 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 436 of file G4INCLConfig.hh
Referenced by init().
ClusterAlgorithmType G4INCL::Config::clusterAlgorithmType private
Definition at line 437 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 437 of file G4INCLConfig.hh
Referenced by getClusterAlgorithm(), init(), and setClusterAlgorithm().
G4int G4INCL::Config::clusterMaxMass private
Definition at line 439 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 439 of file G4INCLConfig.hh
Referenced by getClusterMaxMass(), init(), and setClusterMaxMass().
std::string G4INCL::Config::coulombString private
Definition at line 405 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 405 of file G4INCLConfig.hh
Referenced by init().
CoulombType G4INCL::Config::coulombType private
Definition at line 406 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 406 of file G4INCLConfig.hh
Referenced by getCoulombType(), init(), and setCoulombType().
std::string G4INCL::Config::crossSectionsString private
Definition at line 485 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 485 of file G4INCLConfig.hh
Referenced by init().
CrossSectionsType G4INCL::Config::crossSectionsType private
Definition at line 486 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 486 of file G4INCLConfig.hh
Referenced by getCrossSectionsType(), init(), and setCrossSectionsType().
G4double G4INCL::Config::cutNN private
Definition at line 455 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 455 of file G4INCLConfig.hh
Referenced by getCutNN(), and init().
G4double G4INCL::Config::decayTimeThreshold private
Definition at line 500 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 500 of file G4INCLConfig.hh
Referenced by getDecayTimeThreshold(), init(), and setDecayTimeThreshold().
std::string G4INCL::Config::deExcitationModelList private
Definition at line 418 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 418 of file G4INCLConfig.hh
std::string G4INCL::Config::deExcitationOptionDescription private
Definition at line 419 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 419 of file G4INCLConfig.hh
std::string G4INCL::Config::deExcitationString private
Definition at line 420 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 420 of file G4INCLConfig.hh
Referenced by getDeExcitationString(), and init().
DeExcitationType G4INCL::Config::deExcitationType private
Definition at line 421 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 421 of file G4INCLConfig.hh
Referenced by getDeExcitationType(), and init().
G4double G4INCL::Config::fermiMomentum private
Definition at line 453 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 453 of file G4INCLConfig.hh
Referenced by getFermiMomentum(), init(), and setFermiMomentum().
std::string G4INCL::Config::fermiMomentumString private
Definition at line 450 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 450 of file G4INCLConfig.hh
Referenced by init().
FermiMomentumType G4INCL::Config::fermiMomentumType private
Definition at line 451 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 451 of file G4INCLConfig.hh
Referenced by getFermiMomentumType(), init(), and setFermiMomentumType().
std::string G4INCL::Config::fileSuffix private
Definition at line 383 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 383 of file G4INCLConfig.hh
G4double G4INCL::Config::hadronizationTime private
Definition at line 492 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 492 of file G4INCLConfig.hh
Referenced by getHadronizationTime(), init(), and setHadronizationTime().
G4double G4INCL::Config::impactParameter private
Definition at line 445 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 445 of file G4INCLConfig.hh
Referenced by getImpactParameter(), and init().
std::string G4INCL::Config::INCLXXDataFilePath private
Definition at line 434 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 434 of file G4INCLConfig.hh
Referenced by getINCLXXDataFilePath(), and setINCLXXDataFilePath().
std::string G4INCL::Config::inputFileName private
Definition at line 380 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 380 of file G4INCLConfig.hh
Referenced by init().
G4bool G4INCL::Config::inverseKinematics private
Definition at line 498 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 498 of file G4INCLConfig.hh
Referenced by getInverseKinematics(), and init().
std::string G4INCL::Config::localEnergyBBString private
Definition at line 412 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 412 of file G4INCLConfig.hh
Referenced by init().
LocalEnergyType G4INCL::Config::localEnergyBBType private
Definition at line 413 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 413 of file G4INCLConfig.hh
Referenced by getLocalEnergyBBType(), init(), and setLocalEnergyBBType().
std::string G4INCL::Config::localEnergyPiString private
Definition at line 415 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 415 of file G4INCLConfig.hh
Referenced by init().
LocalEnergyType G4INCL::Config::localEnergyPiType private
Definition at line 416 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 416 of file G4INCLConfig.hh
Referenced by getLocalEnergyPiType(), init(), and setLocalEnergyPiType().
std::string G4INCL::Config::logFileName private
Definition at line 384 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 384 of file G4INCLConfig.hh
Referenced by getLogFileName(), and init().
G4int G4INCL::Config::maxNumberMultipions private
Definition at line 487 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 487 of file G4INCLConfig.hh
Referenced by getMaxNumberMultipions(), init(), and setMaxNumberMultipions().
G4bool G4INCL::Config::naturalTarget private
Definition at line 390 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 390 of file G4INCLConfig.hh
Referenced by init(), and isNaturalTarget().
G4double G4INCL::Config::neutronHalo private
Definition at line 473 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 473 of file G4INCLConfig.hh
Referenced by getNeutronHalo(), init(), and setNeutronHalo().
G4double G4INCL::Config::neutronSkin private
Definition at line 472 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 472 of file G4INCLConfig.hh
Referenced by getNeutronSkin(), init(), and setNeutronSkin().
G4int G4INCL::Config::nShots private
Definition at line 386 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 386 of file G4INCLConfig.hh
Referenced by getNumberOfShots(), init(), and summary().
std::string G4INCL::Config::outputFileRoot private
Definition at line 382 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 382 of file G4INCLConfig.hh
Referenced by getOutputFileRoot().
std::string G4INCL::Config::pauliString private
Definition at line 401 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 401 of file G4INCLConfig.hh
Referenced by init().
PauliType G4INCL::Config::pauliType private
Definition at line 402 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 402 of file G4INCLConfig.hh
Referenced by getPauliType(), and init().
std::string G4INCL::Config::phaseSpaceGenerator private
Definition at line 480 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 480 of file G4INCLConfig.hh
Referenced by init().
PhaseSpaceGeneratorType G4INCL::Config::phaseSpaceGeneratorType private
Definition at line 481 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 481 of file G4INCLConfig.hh
Referenced by getPhaseSpaceGeneratorType(), init(), and setPhaseSpaceGeneratorType().
G4bool G4INCL::Config::pionPotential private
Definition at line 410 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 410 of file G4INCLConfig.hh
Referenced by getPionPotential(), init(), and setPionPotential().
std::string G4INCL::Config::potentialString private
Definition at line 408 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 408 of file G4INCLConfig.hh
Referenced by init().
PotentialType G4INCL::Config::potentialType private
Definition at line 409 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 409 of file G4INCLConfig.hh
Referenced by getPotentialType(), init(), and setPotentialType().
G4double G4INCL::Config::projectileKineticEnergy private
Definition at line 394 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 394 of file G4INCLConfig.hh
Referenced by getProjectileKineticEnergy(), init(), setProjectileKineticEnergy(), and summary().
ParticleSpecies G4INCL::Config::projectileSpecies private
Definition at line 393 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 393 of file G4INCLConfig.hh
Referenced by getProjectileSpecies(), getProjectileType(), init(), setProjectileSpecies(), and summary().
std::string G4INCL::Config::projectileString private
Definition at line 392 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 392 of file G4INCLConfig.hh
Referenced by init().
std::string G4INCL::Config::randomNumberGenerator private
Definition at line 477 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 477 of file G4INCLConfig.hh
Referenced by init().
std::string G4INCL::Config::randomSeeds private
Definition at line 398 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 398 of file G4INCLConfig.hh
Referenced by init().
Random::SeedVector G4INCL::Config::randomSeedVector private
Definition at line 399 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 399 of file G4INCLConfig.hh
Referenced by getRandomSeeds(), and init().
G4bool G4INCL::Config::refraction private
Definition at line 475 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 475 of file G4INCLConfig.hh
Referenced by getRefraction(), init(), and setRefraction().
RNGType G4INCL::Config::rngType private
Definition at line 478 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 478 of file G4INCLConfig.hh
Referenced by getRNGType(), init(), and setRNGType().
G4double G4INCL::Config::rpCorrelationCoefficient private
Definition at line 468 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 468 of file G4INCLConfig.hh
Referenced by init().
G4double G4INCL::Config::rpCorrelationCoefficientNeutron private
Definition at line 470 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 470 of file G4INCLConfig.hh
Referenced by getRPCorrelationCoefficient(), init(), and setRPCorrelationCoefficient().
G4double G4INCL::Config::rpCorrelationCoefficientProton private
Definition at line 469 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 469 of file G4INCLConfig.hh
Referenced by getRPCorrelationCoefficient(), init(), and setRPCorrelationCoefficient().
std::string G4INCL::Config::separationEnergyString private
Definition at line 447 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 447 of file G4INCLConfig.hh
Referenced by init().
SeparationEnergyType G4INCL::Config::separationEnergyType private
Definition at line 448 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 448 of file G4INCLConfig.hh
Referenced by getSeparationEnergyType(), and init().
ParticleSpecies G4INCL::Config::targetSpecies private
Definition at line 389 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 389 of file G4INCLConfig.hh
Referenced by getTargetA(), getTargetS(), getTargetZ(), setTargetA(), setTargetS(), setTargetZ(), and summary().
std::string G4INCL::Config::targetString private
Definition at line 388 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 388 of file G4INCLConfig.hh
std::string G4INCL::Config::title private
Definition at line 381 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 381 of file G4INCLConfig.hh
Referenced by getCalculationTitle(), and init().
G4bool G4INCL::Config::useRealMasses private
Definition at line 443 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 443 of file G4INCLConfig.hh
Referenced by getUseRealMasses(), init(), and setUseRealMasses().
G4int G4INCL::Config::verboseEvent private
Definition at line 396 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 396 of file G4INCLConfig.hh
Referenced by getVerboseEvent(), and init().
G4int G4INCL::Config::verbosity private
Definition at line 379 of file G4INCLConfig.hh.
View newest version in sPHENIX GitHub at line 379 of file G4INCLConfig.hh
Referenced by getVerbosity(), and init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLConfig.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLConfig.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLConfigVersion.cc