ECCE @ EIC Software: G4INCLXXInterfaceMessenger Class Reference
G4INCLXXInterfaceMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/interface/include/G4INCLXXInterfaceMessenger.hh>
Public Member Functions
G4INCLXXInterfaceMessenger (G4INCLXXInterfaceStore *anInterfaceStore)
~G4INCLXXInterfaceMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4INCLXXInterfaceStore * theINCLXXInterfaceStore
G4UIdirectory * theINCLXXDirectory
G4UIcmdWithAString * accurateNucleusCmd
G4UIcmdWithAnInteger * maxClusterMassCmd
G4UIcmdWithADoubleAndUnit * cascadeMinEnergyPerNucleonCmd
G4UIcmdWithAString * inclPhysicsCmd
G4UIcommand * useAblaCmd
Static Private Attributes
static const G4String theUIDirectory = "/process/had/inclxx/"
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 59 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLXXInterfaceMessenger.hh
Constructor & Destructor Documentation
G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger (G4INCLXXInterfaceStore * anInterfaceStore)
Definition at line 51 of file G4INCLXXInterfaceMessenger.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLXXInterfaceMessenger.cc
References accurateNucleusCmd, G4UIcommand::AvailableForStates(), cascadeMinEnergyPerNucleonCmd, G4State_Idle, G4State_PreInit, inclPhysicsCmd, maxClusterMassCmd, MeV, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), theINCLXXDirectory, theUIDirectory, and useAblaCmd.
G4INCLXXInterfaceMessenger::~G4INCLXXInterfaceMessenger ()
Definition at line 105 of file G4INCLXXInterfaceMessenger.cc.
View newest version in sPHENIX GitHub at line 105 of file G4INCLXXInterfaceMessenger.cc
References accurateNucleusCmd, cascadeMinEnergyPerNucleonCmd, inclPhysicsCmd, maxClusterMassCmd, theINCLXXDirectory, and useAblaCmd.
Member Function Documentation
void G4INCLXXInterfaceMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 114 of file G4INCLXXInterfaceMessenger.cc.
View newest version in sPHENIX GitHub at line 114 of file G4INCLXXInterfaceMessenger.cc
References accurateNucleusCmd, cascadeMinEnergyPerNucleonCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), inclPhysicsCmd, maxClusterMassCmd, G4INCLXXInterfaceStore::SetAccurateProjectile(), G4INCLXXInterfaceStore::SetCascadeMinEnergyPerNucleon(), G4INCLXXInterfaceStore::SetINCLPhysics(), G4INCLXXInterfaceStore::SetMaxClusterMass(), theINCLXXInterfaceStore, G4String::toLower(), useAblaCmd, and G4INCLXXInterfaceStore::UseAblaDeExcitation().
Member Data Documentation
G4UIcmdWithAString* G4INCLXXInterfaceMessenger::accurateNucleusCmd private
Definition at line 74 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger(), SetNewValue(), and ~G4INCLXXInterfaceMessenger().
G4UIcmdWithADoubleAndUnit* G4INCLXXInterfaceMessenger::cascadeMinEnergyPerNucleonCmd private
Definition at line 76 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger(), SetNewValue(), and ~G4INCLXXInterfaceMessenger().
G4UIcmdWithAString* G4INCLXXInterfaceMessenger::inclPhysicsCmd private
Definition at line 77 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger(), SetNewValue(), and ~G4INCLXXInterfaceMessenger().
G4UIcmdWithAnInteger* G4INCLXXInterfaceMessenger::maxClusterMassCmd private
Definition at line 75 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger(), SetNewValue(), and ~G4INCLXXInterfaceMessenger().
G4UIdirectory* G4INCLXXInterfaceMessenger::theINCLXXDirectory private
Definition at line 73 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger(), and ~G4INCLXXInterfaceMessenger().
G4INCLXXInterfaceStore* G4INCLXXInterfaceMessenger::theINCLXXInterfaceStore private
Definition at line 72 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLXXInterfaceMessenger.hh
Referenced by SetNewValue().
const G4String G4INCLXXInterfaceMessenger::theUIDirectory = "/process/had/inclxx/" static private
Definition at line 71 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger().
G4UIcommand* G4INCLXXInterfaceMessenger::useAblaCmd private
Definition at line 78 of file G4INCLXXInterfaceMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4INCLXXInterfaceMessenger.hh
Referenced by G4INCLXXInterfaceMessenger(), SetNewValue(), and ~G4INCLXXInterfaceMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/interface/include/G4INCLXXInterfaceMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/interface/src/G4INCLXXInterfaceMessenger.cc