ECCE @ EIC Software: G4WrapperProcess Class Reference
G4WrapperProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4WrapperProcess.hh>
Public Member Functions
G4WrapperProcess (const G4String &aName="Wrapped", G4ProcessType aType=fNotDefined)
G4WrapperProcess (const G4WrapperProcess &right)
virtual ~G4WrapperProcess ()
G4bool operator== (const G4WrapperProcess &right) const
G4bool operator!= (const G4WrapperProcess &right) const
virtual void RegisterProcess (G4VProcess *)
virtual const G4VProcess * GetRegisteredProcess () const
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &stepData)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)
virtual G4VParticleChange * AtRestDoIt (const G4Track &track, const G4Step &stepData)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
virtual void SetMasterProcess (G4VProcess *masterP)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Attributes
G4VProcess * pRegProcess
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
G4WrapperProcess & operator= (const G4WrapperProcess &right)
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Detailed Description
Definition at line 47 of file G4WrapperProcess.hh.
View newest version in sPHENIX GitHub at line 47 of file G4WrapperProcess.hh
Constructor & Destructor Documentation
G4WrapperProcess::G4WrapperProcess (const G4String & aName = "Wrapped", G4ProcessType aType = fNotDefined)
Definition at line 38 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 38 of file G4WrapperProcess.cc
G4WrapperProcess::G4WrapperProcess (const G4WrapperProcess & right)
Definition at line 45 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 45 of file G4WrapperProcess.cc
G4WrapperProcess::~G4WrapperProcess () virtual
Definition at line 50 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 50 of file G4WrapperProcess.cc
References pRegProcess.
Member Function Documentation
G4VParticleChange * G4WrapperProcess::AlongStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 108 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 108 of file G4WrapperProcess.cc
References G4VProcess::AlongStepDoIt(), and pRegProcess.
G4double G4WrapperProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 61 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 61 of file G4WrapperProcess.cc
References pRegProcess.
G4VParticleChange * G4WrapperProcess::AtRestDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 114 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 114 of file G4WrapperProcess.cc
References G4VProcess::AtRestDoIt(), and pRegProcess.
G4double G4WrapperProcess::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 76 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 76 of file G4WrapperProcess.cc
References G4VProcess::AtRestGetPhysicalInteractionLength(), and pRegProcess.
void G4WrapperProcess::BuildPhysicsTable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 125 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 125 of file G4WrapperProcess.cc
References G4VProcess::BuildPhysicsTable(), and pRegProcess.
void G4WrapperProcess::EndTracking () virtual
Reimplemented from G4VProcess.
Definition at line 156 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 156 of file G4WrapperProcess.cc
References G4VProcess::EndTracking(), and pRegProcess.
const G4ProcessManager * G4WrapperProcess::GetProcessManager () virtual
Reimplemented from G4VProcess.
Definition at line 97 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 97 of file G4WrapperProcess.cc
References G4VProcess::GetProcessManager(), and pRegProcess.
const G4VProcess * G4WrapperProcess::GetRegisteredProcess () const virtual
Definition at line 168 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 168 of file G4WrapperProcess.cc
References pRegProcess.
G4bool G4WrapperProcess::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 120 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 120 of file G4WrapperProcess.cc
References G4VProcess::IsApplicable(), and pRegProcess.
G4bool G4WrapperProcess::operator!= (const G4WrapperProcess & right) const inline
Definition at line 199 of file G4WrapperProcess.hh.
View newest version in sPHENIX GitHub at line 199 of file G4WrapperProcess.hh
G4WrapperProcess & G4WrapperProcess::operator= (const G4WrapperProcess & right) inline private
Definition at line 185 of file G4WrapperProcess.hh.
View newest version in sPHENIX GitHub at line 185 of file G4WrapperProcess.hh
References G4Exception(), and JustWarning.
G4bool G4WrapperProcess::operator== (const G4WrapperProcess & right) const inline
Definition at line 193 of file G4WrapperProcess.hh.
View newest version in sPHENIX GitHub at line 193 of file G4WrapperProcess.hh
G4VParticleChange * G4WrapperProcess::PostStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Reimplemented in CexmcStudiedProcess, and SplitProcess.
Definition at line 102 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 102 of file G4WrapperProcess.cc
References G4VProcess::PostStepDoIt(), and pRegProcess.
G4double G4WrapperProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Reimplemented in CexmcStudiedProcess.
Definition at line 83 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 83 of file G4WrapperProcess.cc
References G4VProcess::PostStepGetPhysicalInteractionLength(), and pRegProcess.
void G4WrapperProcess::PreparePhysicsTable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 130 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 130 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::PreparePhysicsTable().
void G4WrapperProcess::RegisterProcess (G4VProcess * process) virtual
Definition at line 161 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 161 of file G4WrapperProcess.cc
References G4VProcess::GetProcessName(), G4VProcess::GetProcessType(), pRegProcess, G4VProcess::theProcessName, and G4VProcess::theProcessType.
Referenced by CexmcStudiedPhysics< Process >::ConstructProcess().
void G4WrapperProcess::ResetNumberOfInteractionLengthLeft () virtual
Reimplemented from G4VProcess.
Definition at line 55 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 55 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::ResetNumberOfInteractionLengthLeft().
G4bool G4WrapperProcess::RetrievePhysicsTable (const G4ParticleDefinition * particle, const G4String & directory, G4bool ascii = false) virtual
Reimplemented from G4VProcess.
Definition at line 144 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 144 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::RetrievePhysicsTable().
void G4WrapperProcess::SetMasterProcess (G4VProcess * masterP) virtual
Reimplemented from G4VProcess.
Definition at line 173 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 173 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::SetMasterProcess().
void G4WrapperProcess::SetProcessManager (const G4ProcessManager * procMan) virtual
Reimplemented from G4VProcess.
Definition at line 92 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 92 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::SetProcessManager().
void G4WrapperProcess::StartTracking (G4Track * track) virtual
Reimplemented from G4VProcess.
Definition at line 151 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 151 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::StartTracking().
G4bool G4WrapperProcess::StorePhysicsTable (const G4ParticleDefinition * particle, const G4String & directory, G4bool ascii = false) virtual
Reimplemented from G4VProcess.
Definition at line 136 of file G4WrapperProcess.cc.
View newest version in sPHENIX GitHub at line 136 of file G4WrapperProcess.cc
References pRegProcess, and G4VProcess::StorePhysicsTable().
Member Data Documentation
G4VProcess* G4WrapperProcess::pRegProcess protected
Definition at line 78 of file G4WrapperProcess.hh.
View newest version in sPHENIX GitHub at line 78 of file G4WrapperProcess.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), AtRestDoIt(), AtRestGetPhysicalInteractionLength(), BuildPhysicsTable(), EndTracking(), GetProcessManager(), GetRegisteredProcess(), IsApplicable(), SplitProcess::PostStepDoIt(), CexmcStudiedProcess::PostStepDoIt(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), RegisterProcess(), ResetNumberOfInteractionLengthLeft(), RetrievePhysicsTable(), SetMasterProcess(), SetProcessManager(), StartTracking(), StorePhysicsTable(), and ~G4WrapperProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4WrapperProcess.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4WrapperProcess.cc