ECCE @ EIC Software: G4QMDCollision Class Reference
G4QMDCollision Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDCollision.hh>
Public Member Functions
G4QMDCollision ()
~G4QMDCollision ()
void CalKinematicsOfBinaryCollisions (G4double)
G4bool CalFinalStateOfTheBinaryCollision (G4int, G4int)
G4bool CalFinalStateOfTheBinaryCollisionJQMD (G4double, G4double, G4ThreeVector, G4double, G4double, G4ThreeVector, G4double, G4int, G4int)
void SetMeanField (G4QMDMeanField *meanfield)
void deltar (G4double x)
G4double deltar ()
void bcmax0 (G4double x)
G4double bcmax0 ()
void bcmax1 (G4double x)
G4double bcmax1 ()
void epse (G4double x)
G4double epse ()
Private Member Functions
G4QMDCollision (const G4QMDCollision &)
const G4QMDCollision & operator= (const G4QMDCollision &)
Private Attributes
G4QMDSystem * theSystem
G4QMDMeanField * theMeanField
G4double fdeltar
G4double fbcmax0
G4double fbcmax1
G4double fepse
G4Scatterer * theScatterer
Detailed Description
Definition at line 47 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 47 of file G4QMDCollision.hh
Constructor & Destructor Documentation
G4QMDCollision::G4QMDCollision ()
Definition at line 42 of file G4QMDCollision.cc.
View newest version in sPHENIX GitHub at line 42 of file G4QMDCollision.cc
References theMeanField, theScatterer, and theSystem.
G4QMDCollision::~G4QMDCollision ()
Definition at line 110 of file G4QMDCollision.cc.
View newest version in sPHENIX GitHub at line 110 of file G4QMDCollision.cc
References theScatterer.
G4QMDCollision::G4QMDCollision (const G4QMDCollision &) inline private
Definition at line 72 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QMDCollision.hh
Member Function Documentation
void G4QMDCollision::bcmax0 (G4double x) inline
Definition at line 63 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 63 of file G4QMDCollision.hh
References fbcmax0, and x.
G4double G4QMDCollision::bcmax0 () inline
Definition at line 64 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QMDCollision.hh
References fbcmax0.
void G4QMDCollision::bcmax1 (G4double x) inline
Definition at line 65 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QMDCollision.hh
References fbcmax1, and x.
G4double G4QMDCollision::bcmax1 () inline
Definition at line 66 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 66 of file G4QMDCollision.hh
References fbcmax1.
G4bool G4QMDCollision::CalFinalStateOfTheBinaryCollision (G4int i, G4int j)
Definition at line 559 of file G4QMDCollision.cc.
View newest version in sPHENIX GitHub at line 559 of file G4QMDCollision.cc
References kdfinder::abs(), absorbed, G4QMDMeanField::Cal2BodyQuantities(), CLHEP::HepLorentzVector::e(), G4QMDSystem::EraseParticipant(), false, fepse, fermi, G4cout, G4endl, G4QMDParticipant::Get4Momentum(), G4QMDParticipant::GetDefinition(), G4QMDSystem::GetParticipant(), G4QMDParticipant::GetPosition(), G4QMDMeanField::GetTotalPotential(), GeV, G4QMDSystem::InsertParticipant(), G4QMDMeanField::IsPauliBlocked(), it, G4Scatterer::Scatter(), G4QMDParticipant::SetDefinition(), G4QMDParticipant::SetMomentum(), theMeanField, theScatterer, theSystem, true, G4QMDMeanField::Update(), and CLHEP::HepLorentzVector::v().
Referenced by CalKinematicsOfBinaryCollisions().
G4bool G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD (G4double sig, G4double cutoff, G4ThreeVector pcm, G4double prcm, G4double srt, G4ThreeVector beta, G4double gamma, G4int i, G4int j)
Definition at line 769 of file G4QMDCollision.cc.
View newest version in sPHENIX GitHub at line 769 of file G4QMDCollision.cc
References a, kdfinder::abs(), c1, c2, G4QMDMeanField::Cal2BodyQuantities(), e, CLHEP::HepLorentzVector::e(), G4INCL::CrossSections::elastic(), fepse, G4Exp(), G4Log(), G4UniformRand, G4QMDParticipant::Get4Momentum(), G4QMDParticipant::GetChargeInUnitOfEplus(), G4Pow::GetInstance(), G4QMDParticipant::GetMass(), G4QMDSystem::GetParticipant(), G4QMDMeanField::GetTotalPotential(), pi, G4Pow::powN(), gammaraytel::pr, s1, G4QMDParticipant::SetMomentum(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), t1, t2, theMeanField, theSystem, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4QMDCollision::CalKinematicsOfBinaryCollisions (G4double dt)
Definition at line 118 of file G4QMDCollision.cc.
View newest version in sPHENIX GitHub at line 118 of file G4QMDCollision.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boost(), G4QMDMeanField::Cal2BodyQuantities(), CalFinalStateOfTheBinaryCollision(), G4KineticTrack::Decay(), G4QMDSystem::DeleteParticipant(), CLHEP::HepLorentzVector::e(), fbcmax0, fbcmax1, fdeltar, fepse, fermi, CLHEP::HepLorentzVector::findBoostToCM(), G4QMDParticipant::Get4Momentum(), G4QMDParticipant::GetDefinition(), G4QMDParticipant::GetMass(), G4QMDParticipant::GetMomentum(), G4QMDSystem::GetParticipant(), G4ParticleDefinition::GetPDGMass(), G4QMDParticipant::GetPosition(), G4QMDMeanField::GetRR2(), G4QMDSystem::GetTotalNumberOfParticipant(), G4QMDMeanField::GetTotalPotential(), GeV, G4QMDSystem::IncrementCollisionCounter(), G4QMDMeanField::IsPauliBlocked(), G4ParticleDefinition::IsShortLived(), G4QMDParticipant::IsThisHit(), G4QMDParticipant::IsThisProjectile(), G4QMDParticipant::IsThisTarget(), it, CLHEP::Hep3Vector::mag(), n, G4QMDParticipant::SetDefinition(), G4QMDParticipant::SetHitMark(), G4QMDParticipant::SetMomentum(), G4QMDSystem::SetParticipant(), G4QMDParticipant::SetPosition(), theMeanField, theSystem, true, G4QMDParticipant::UnsetHitMark(), G4QMDParticipant::UnsetInitialMark(), G4QMDMeanField::Update(), and CLHEP::HepLorentzVector::vect().
Referenced by G4QMDReaction::ApplyYourself().
void G4QMDCollision::deltar (G4double x) inline
Definition at line 61 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 61 of file G4QMDCollision.hh
References fdeltar, and x.
Referenced by expai(), and expaid().
G4double G4QMDCollision::deltar () inline
Definition at line 62 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 62 of file G4QMDCollision.hh
References fdeltar.
void G4QMDCollision::epse (G4double x) inline
Definition at line 67 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 67 of file G4QMDCollision.hh
References fepse, and x.
G4double G4QMDCollision::epse () inline
Definition at line 68 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 68 of file G4QMDCollision.hh
References fepse.
const G4QMDCollision& G4QMDCollision::operator= (const G4QMDCollision &) private
void G4QMDCollision::SetMeanField (G4QMDMeanField * meanfield) inline
Definition at line 58 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QMDCollision.hh
References G4QMDMeanField::GetSystem(), theMeanField, and theSystem.
Referenced by G4QMDReaction::ApplyYourself().
Member Data Documentation
G4double G4QMDCollision::fbcmax0 private
Definition at line 79 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QMDCollision.hh
Referenced by bcmax0(), and CalKinematicsOfBinaryCollisions().
G4double G4QMDCollision::fbcmax1 private
Definition at line 79 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QMDCollision.hh
Referenced by bcmax1(), and CalKinematicsOfBinaryCollisions().
G4double G4QMDCollision::fdeltar private
Definition at line 78 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QMDCollision.hh
Referenced by CalKinematicsOfBinaryCollisions(), and deltar().
G4double G4QMDCollision::fepse private
Definition at line 81 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 81 of file G4QMDCollision.hh
Referenced by CalFinalStateOfTheBinaryCollision(), CalFinalStateOfTheBinaryCollisionJQMD(), CalKinematicsOfBinaryCollisions(), and epse().
G4QMDMeanField* G4QMDCollision::theMeanField private
Definition at line 76 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QMDCollision.hh
Referenced by CalFinalStateOfTheBinaryCollision(), CalFinalStateOfTheBinaryCollisionJQMD(), CalKinematicsOfBinaryCollisions(), G4QMDCollision(), and SetMeanField().
G4Scatterer* G4QMDCollision::theScatterer private
Definition at line 83 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDCollision.hh
Referenced by CalFinalStateOfTheBinaryCollision(), G4QMDCollision(), and ~G4QMDCollision().
G4QMDSystem* G4QMDCollision::theSystem private
Definition at line 75 of file G4QMDCollision.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QMDCollision.hh
Referenced by CalFinalStateOfTheBinaryCollision(), CalFinalStateOfTheBinaryCollisionJQMD(), CalKinematicsOfBinaryCollisions(), G4QMDCollision(), and SetMeanField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDCollision.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDCollision.cc