ECCE @ EIC Software: G4DCofThisEvent Class Reference
G4DCofThisEvent Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4DCofThisEvent.hh>
Public Member Functions
G4DCofThisEvent ()
G4DCofThisEvent (G4int cap)
~G4DCofThisEvent ()
void * operator new (size_t)
void operator delete (void *anDCoTE)
void AddDigiCollection (G4int DCID, G4VDigiCollection *aDC)
G4DCofThisEvent (const G4DCofThisEvent &)
G4DCofThisEvent & operator= (const G4DCofThisEvent &)
G4VDigiCollection * GetDC (G4int i) const
G4int GetNumberOfCollections () const
size_t GetCapacity () const
Private Attributes
std::vector< G4VDigiCollection * > * DC
Detailed Description
Definition at line 49 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 49 of file G4DCofThisEvent.hh
Constructor & Destructor Documentation
G4DCofThisEvent::G4DCofThisEvent ()
Definition at line 38 of file G4DCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 38 of file G4DCofThisEvent.cc
References anDCoTHAllocator_G4MT_TLS_(), and DC.
G4DCofThisEvent::G4DCofThisEvent (G4int cap)
Definition at line 43 of file G4DCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 43 of file G4DCofThisEvent.cc
References anDCoTHAllocator_G4MT_TLS_(), and DC.
G4DCofThisEvent::~G4DCofThisEvent ()
Definition at line 52 of file G4DCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 52 of file G4DCofThisEvent.cc
References anDCoTHAllocator_G4MT_TLS_(), and DC.
G4DCofThisEvent::G4DCofThisEvent (const G4DCofThisEvent & rhs)
Definition at line 67 of file G4DCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 67 of file G4DCofThisEvent.cc
References anDCoTHAllocator_G4MT_TLS_(), and DC.
Member Function Documentation
void G4DCofThisEvent::AddDigiCollection (G4int DCID, G4VDigiCollection * aDC)
Definition at line 61 of file G4DCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 61 of file G4DCofThisEvent.cc
References anDCoTHAllocator_G4MT_TLS_(), and DC.
Referenced by G4DigiManager::SetDigiCollection().
size_t G4DCofThisEvent::GetCapacity () const inline
Definition at line 82 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DCofThisEvent.hh
References DC.
Referenced by G4Event::Draw().
G4VDigiCollection* G4DCofThisEvent::GetDC (G4int i) const inline
Definition at line 66 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 66 of file G4DCofThisEvent.hh
References DC.
Referenced by G4Event::Draw(), and G4DigiManager::GetDigiCollection().
G4int G4DCofThisEvent::GetNumberOfCollections () const inline
Definition at line 73 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DCofThisEvent.hh
References DC, and n.
void G4DCofThisEvent::operator delete (void * anDCoTE) inline
Definition at line 105 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 105 of file G4DCofThisEvent.hh
References anDCoTHAllocator_G4MT_TLS_(), and G4Allocator< Type >::FreeSingle().
void * G4DCofThisEvent::operator new (size_t) inline
Definition at line 94 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4DCofThisEvent.hh
References anDCoTHAllocator_G4MT_TLS_(), and G4Allocator< Type >::MallocSingle().
G4DCofThisEvent & G4DCofThisEvent::operator= (const G4DCofThisEvent & rhs)
Definition at line 75 of file G4DCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 75 of file G4DCofThisEvent.cc
References anDCoTHAllocator_G4MT_TLS_(), DC, and it.
Member Data Documentation
std::vector<G4VDigiCollection*>* G4DCofThisEvent::DC private
Definition at line 63 of file G4DCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 63 of file G4DCofThisEvent.hh
Referenced by AddDigiCollection(), G4DCofThisEvent(), GetCapacity(), GetDC(), GetNumberOfCollections(), operator=(), and ~G4DCofThisEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4DCofThisEvent.hh
geant4/tree/geant4-10.6-release/source/digits_hits/digits/src/G4DCofThisEvent.cc