ECCE @ EIC Software: G4Scale Class Reference
G4Scale Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Scale.hh>
Public Types
enum Direction { x, y, z }
Public Types inherited from G4VMarker
enum FillStyle { noFill, hashed, filled }
enum SizeType { none, world, screen }
Public Member Functions
G4Scale (G4double length, const G4String &annotation="", Direction direction=x, G4bool autoPlacing=true, G4double xmid=0., G4double ymid=0., G4double zmid=0., G4double annotationSize=12.)
~G4Scale ()
G4double GetLength () const
const G4String & GetAnnotation () const
G4double GetAnnotationSize () const
Direction GetDirection () const
G4bool GetAutoPlacing () const
G4double GetXmid () const
G4double GetYmid () const
G4double GetZmid () const
Public Member Functions inherited from G4VMarker
G4VMarker ()
G4VMarker (const G4VMarker &)
G4VMarker (const G4Point3D &position)
virtual ~G4VMarker ()
G4VMarker & operator= (const G4VMarker &)
G4bool operator!= (const G4VMarker &) const
G4Point3D GetPosition () const
SizeType GetSizeType () const
G4double GetWorldSize () const
G4double GetWorldDiameter () const
G4double GetWorldRadius () const
G4double GetScreenSize () const
G4double GetScreenDiameter () const
G4double GetScreenRadius () const
FillStyle GetFillStyle () const
void SetPosition (const G4Point3D &)
void SetSize (SizeType, G4double)
void SetDiameter (SizeType, G4double)
void SetRadius (SizeType, G4double)
void SetWorldSize (G4double)
void SetWorldDiameter (G4double)
void SetWorldRadius (G4double)
void SetScreenSize (G4double)
void SetScreenDiameter (G4double)
void SetScreenRadius (G4double)
void SetFillStyle (FillStyle)
virtual const G4String & GetInfo () const
virtual void SetInfo (const G4String &info)
Public Member Functions inherited from G4Visible
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Static Public Member Functions
static const G4String & GetGuidanceString ()
Private Attributes
G4double fLength
G4String fAnnotation
G4double fAnnotationSize
Direction fDirection
G4bool fAutoPlacing
G4double fXmid
G4double fYmid
G4double fZmid
Static Private Attributes
static const G4String GuidanceString
Additional Inherited Members
Protected Attributes inherited from G4Visible
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Detailed Description
Definition at line 37 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 37 of file G4Scale.hh
Member Enumeration Documentation
enum G4Scale::Direction
Enumerator:
x
y
z
Definition at line 41 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 41 of file G4Scale.hh
Constructor & Destructor Documentation
G4Scale::G4Scale (G4double length, const G4String & annotation = "", G4Scale::Direction direction = x, G4bool autoPlacing = true, G4double xmid = 0., G4double ymid = 0., G4double zmid = 0., G4double annotationSize = 12.)
Definition at line 33 of file G4Scale.cc.
View newest version in sPHENIX GitHub at line 33 of file G4Scale.cc
G4Scale::~G4Scale ()
Definition at line 45 of file G4Scale.cc.
View newest version in sPHENIX GitHub at line 45 of file G4Scale.cc
Member Function Documentation
const G4String& G4Scale::GetAnnotation () const
Referenced by G4VSceneHandler::AddPrimitive(), and G4ScaleModel::G4ScaleModel().
G4double G4Scale::GetAnnotationSize () const
Referenced by G4VSceneHandler::AddPrimitive().
G4bool G4Scale::GetAutoPlacing () const
Referenced by G4VSceneHandler::AddPrimitive().
Direction G4Scale::GetDirection () const
Referenced by G4VSceneHandler::AddPrimitive(), and G4ScaleModel::G4ScaleModel().
const G4String & G4Scale::GetGuidanceString () static
Definition at line 65 of file G4Scale.cc.
View newest version in sPHENIX GitHub at line 65 of file G4Scale.cc
References GuidanceString.
Referenced by G4VisCommandSceneAddScale::G4VisCommandSceneAddScale().
G4double G4Scale::GetLength () const
Referenced by G4VSceneHandler::AddPrimitive().
G4double G4Scale::GetXmid () const
G4double G4Scale::GetYmid () const
G4double G4Scale::GetZmid () const
Member Data Documentation
G4String G4Scale::fAnnotation private
Definition at line 82 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 82 of file G4Scale.hh
G4double G4Scale::fAnnotationSize private
Definition at line 83 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Scale.hh
G4bool G4Scale::fAutoPlacing private
Definition at line 85 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 85 of file G4Scale.hh
Direction G4Scale::fDirection private
Definition at line 84 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 84 of file G4Scale.hh
G4double G4Scale::fLength private
Definition at line 81 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 81 of file G4Scale.hh
G4double G4Scale::fXmid private
Definition at line 86 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Scale.hh
G4double G4Scale::fYmid private
Definition at line 86 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Scale.hh
G4double G4Scale::fZmid private
Definition at line 86 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Scale.hh
const G4String G4Scale::GuidanceString static private
Definition at line 87 of file G4Scale.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Scale.hh
Referenced by GetGuidanceString().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Scale.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4Scale.cc