ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_reaction.cc File Reference
MCGIDI_reaction.cc File Reference
#include <string.h>
#include <cmath>
#include <PoPs.h>
#include "MCGIDI.h"
#include "MCGIDI_misc.h"
#include "MCGIDI_private.h"
Macros
#define nParticleChanges 6
Functions
static int MCGIDI_reaction_initialize2 (statusMessageReporting *smr, MCGIDI_reaction *reaction)
static int MCGIDI_reaction_particleChanges (MCGIDI_POP *projectile, MCGIDI_POP *target, MCGIDI_productsInfo *productsInfo, int n1, int *particlesChanges)
static int MCGIDI_reaction_ParseReactionTypeAndDetermineProducts (statusMessageReporting *smr, MCGIDI_POPs *pops, MCGIDI_reaction *reaction)
static int MCGIDI_reaction_ParseDetermineReactionProducts (statusMessageReporting *smr, MCGIDI_POPs *pops, MCGIDI_outputChannel *outputChannel, MCGIDI_productsInfo *productsInfo, MCGIDI_reaction *reaction, double *finalQ, int level)
static int MCGIDI_reaction_addReturnProduct (statusMessageReporting *smr, MCGIDI_productsInfo *productsInfo, int ID, MCGIDI_product *product, MCGIDI_reaction *reaction, int transportable)
static int MCGIDI_reaction_setENDL_CSNumbers (statusMessageReporting *smr, MCGIDI_reaction *reaction)
MCGIDI_reaction * MCGIDI_reaction_new (statusMessageReporting *smr)
int MCGIDI_reaction_initialize (statusMessageReporting *smr, MCGIDI_reaction *reaction)
MCGIDI_reaction * MCGIDI_reaction_free (statusMessageReporting *smr, MCGIDI_reaction *reaction)
int MCGIDI_reaction_release (statusMessageReporting *smr, MCGIDI_reaction *reaction)
int MCGIDI_reaction_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_target_heated *target, MCGIDI_POPs *pops, MCGIDI_reaction *reaction)
enum MCGIDI_reactionType MCGIDI_reaction_getReactionType (statusMessageReporting *, MCGIDI_reaction *reaction)
MCGIDI_target_heated * MCGIDI_reaction_getTargetHeated (statusMessageReporting *, MCGIDI_reaction *reaction)
double MCGIDI_reaction_getProjectileMass_MeV (statusMessageReporting *smr, MCGIDI_reaction *reaction)
double MCGIDI_reaction_getTargetMass_MeV (statusMessageReporting *smr, MCGIDI_reaction *reaction)
int MCGIDI_reaction_getDomain (statusMessageReporting *, MCGIDI_reaction *reaction, double *EMin, double *EMax)
int MCGIDI_reaction_fixDomains (statusMessageReporting *, MCGIDI_reaction *reaction, double EMin, double EMax, nfu_status *status)
double MCGIDI_reaction_getCrossSectionAtE (statusMessageReporting *smr, MCGIDI_reaction *reaction, MCGIDI_quantitiesLookupModes &modes, bool sampling)
double MCGIDI_reaction_getFinalQ (statusMessageReporting *, MCGIDI_reaction *reaction, MCGIDI_quantitiesLookupModes &)
int MCGIDI_reaction_getENDF_MTNumber (MCGIDI_reaction *reaction)
int MCGIDI_reaction_getENDL_CSNumbers (MCGIDI_reaction *reaction, int *S)
MCGIDI_productsInfo * MCGIDI_reaction_getProductsInfo (MCGIDI_reaction *reaction)
int MCGIDI_reaction_recast (statusMessageReporting *smr, MCGIDI_reaction *reaction, GIDI_settings &, GIDI_settings_particle const *projectileSettings, double temperature_MeV, ptwXPoints *totalGroupedCrossSection)
int MCGIDI_productsInfo_getNumberOfUniqueProducts (MCGIDI_productsInfo *productsInfo)
int MCGIDI_productsInfo_getPoPsIndexAtIndex (MCGIDI_productsInfo *productsInfo, int index)
enum MCGIDI_productMultiplicityType MCGIDI_productsInfo_getMultiplicityTypeAtIndex (MCGIDI_productsInfo *productsInfo, int index)
int MCGIDI_productsInfo_getIntegerMultiplicityAtIndex (MCGIDI_productsInfo *productsInfo, int index)
int MCGIDI_productsInfo_getTransportableAtIndex (MCGIDI_productsInfo *productsInfo, int index)
Macro Definition Documentation
#define nParticleChanges 6
Definition at line 18 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 18 of file MCGIDI_reaction.cc
Referenced by MCGIDI_reaction_ParseReactionTypeAndDetermineProducts().
Function Documentation
int MCGIDI_productsInfo_getIntegerMultiplicityAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 550 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 550 of file MCGIDI_reaction.cc
References MCGIDI_productInfo_s::multiplicity, MCGIDI_productsInfo_s::numberOfProducts, and MCGIDI_productsInfo_s::productInfo.
enum MCGIDI_productMultiplicityType MCGIDI_productsInfo_getMultiplicityTypeAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 542 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 542 of file MCGIDI_reaction.cc
References MCGIDI_productMultiplicityType_invalid_e, MCGIDI_productsInfo_s::numberOfProducts, MCGIDI_productsInfo_s::productInfo, and MCGIDI_productInfo_s::productMultiplicityType.
int MCGIDI_productsInfo_getNumberOfUniqueProducts (MCGIDI_productsInfo * productsInfo)
Definition at line 527 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 527 of file MCGIDI_reaction.cc
References MCGIDI_productsInfo_s::numberOfProducts.
int MCGIDI_productsInfo_getPoPsIndexAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 534 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 534 of file MCGIDI_reaction.cc
References MCGIDI_productInfo_s::globalPoPsIndex, MCGIDI_productsInfo_s::numberOfProducts, and MCGIDI_productsInfo_s::productInfo.
int MCGIDI_productsInfo_getTransportableAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 558 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 558 of file MCGIDI_reaction.cc
References MCGIDI_productsInfo_s::numberOfProducts, MCGIDI_productsInfo_s::productInfo, and MCGIDI_productInfo_s::transportable.
static int MCGIDI_reaction_addReturnProduct (statusMessageReporting * smr, MCGIDI_productsInfo * productsInfo, int ID, MCGIDI_product * product, MCGIDI_reaction * reaction, int transportable) static
Definition at line 279 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 279 of file MCGIDI_reaction.cc
References MCGIDI_productInfo_s::globalPoPsIndex, MCGIDI_misc_updateTransportabilitiesMap2(), MCGIDI_productMultiplicityType_energyDependent_e, MCGIDI_productMultiplicityType_gammaBranching_e, MCGIDI_productMultiplicityType_integer_e, MCGIDI_productMultiplicityType_mixed_e, MCGIDI_productMultiplicityType_unknown_e, MCGIDI_productInfo_s::multiplicity, MCGIDI_product_s::multiplicity, MCGIDI_product_s::multiplicityVsEnergy, MCGIDI_productsInfo_s::numberOfAllocatedProducts, MCGIDI_productsInfo_s::numberOfProducts, MCGIDI_product_s::piecewiseMultiplicities, MCGIDI_productsInfo_s::productInfo, MCGIDI_productInfo_s::productMultiplicityType, smr_realloc2, MCGIDI_reaction_s::transportabilities, and MCGIDI_productInfo_s::transportable.
Referenced by MCGIDI_reaction_ParseDetermineReactionProducts().
int MCGIDI_reaction_fixDomains (statusMessageReporting * , MCGIDI_reaction * reaction, double EMin, double EMax, nfu_status * status)
Definition at line 366 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 366 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::crossSection, e, MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, nfu_Okay, and ptwXY_dullEdges().
Referenced by MCGIDI_target_heated_read().
MCGIDI_reaction* MCGIDI_reaction_free (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 60 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 60 of file MCGIDI_reaction.cc
References MCGIDI_reaction_release(), and smr_freeMemory().
Referenced by MCGIDI_reaction_new().
double MCGIDI_reaction_getCrossSectionAtE (statusMessageReporting * smr, MCGIDI_reaction * reaction, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 380 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 380 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::crossSectionGrouped, MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, MCGIDI_quantitiesLookupModes::getCrossSectionMode(), MCGIDI_quantitiesLookupModes::getGroupIndex(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_quantityLookupMode_grouped, MCGIDI_quantityLookupMode_pointwise, ptwX_getPointAtIndex(), ptwXY_getValueAtX(), smr_setReportError2, smr_unknownID, MCGIDI_reaction_s::thresholdGroupedDeltaCrossSection, and MCGIDI_reaction_s::thresholdGroupIndex.
Referenced by MCGIDI_target_heated_getIndexReactionCrossSectionAtE().
int MCGIDI_reaction_getDomain (statusMessageReporting * , MCGIDI_reaction * reaction, double * EMin, double * EMax)
Definition at line 350 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 350 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::domainValuesPresent, MCGIDI_reaction_s::EMax, and MCGIDI_reaction_s::EMin.
Referenced by MCGIDI_outputChannel_getDomain(), and MCGIDI_target_heated_read().
int MCGIDI_reaction_getENDF_MTNumber (MCGIDI_reaction * reaction)
Definition at line 415 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 415 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::ENDF_MT.
Referenced by G4GIDI_target::init(), MCGIDI_reaction_ParseReactionTypeAndDetermineProducts(), and MCGIDI_reaction_setENDL_CSNumbers().
int MCGIDI_reaction_getENDL_CSNumbers (MCGIDI_reaction * reaction, int * S)
Definition at line 422 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 422 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::ENDL_C, and MCGIDI_reaction_s::ENDL_S.
double MCGIDI_reaction_getFinalQ (statusMessageReporting * , MCGIDI_reaction * reaction, MCGIDI_quantitiesLookupModes &)
Definition at line 408 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 408 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::finalQ.
Referenced by MCGIDI_target_heated_getIndexReactionFinalQ().
MCGIDI_productsInfo* MCGIDI_reaction_getProductsInfo (MCGIDI_reaction * reaction)
Definition at line 489 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 489 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::productsInfo.
double MCGIDI_reaction_getProjectileMass_MeV (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 336 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 336 of file MCGIDI_reaction.cc
References MCGIDI_target_heated_getProjectileMass_MeV(), and MCGIDI_reaction_s::target.
Referenced by MCGIDI_outputChannel_getProjectileMass_MeV(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_sampleProductsAtE().
enum MCGIDI_reactionType MCGIDI_reaction_getReactionType (statusMessageReporting * , MCGIDI_reaction * reaction)
Definition at line 322 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 322 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::reactionType.
Referenced by MCGIDI_target_getReactionTypeAtIndex().
MCGIDI_target_heated* MCGIDI_reaction_getTargetHeated (statusMessageReporting * , MCGIDI_reaction * reaction)
Definition at line 329 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 329 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::target.
Referenced by MCGIDI_outputChannel_getTargetHeated().
double MCGIDI_reaction_getTargetMass_MeV (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 343 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 343 of file MCGIDI_reaction.cc
References MCGIDI_target_heated_getTargetMass_MeV(), and MCGIDI_reaction_s::target.
Referenced by MCGIDI_outputChannel_getTargetMass_MeV(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_reaction_initialize (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 42 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 42 of file MCGIDI_reaction.cc
References MCGIDI_reaction_initialize2(), and MCGIDI_reaction_s::transportabilities.
Referenced by MCGIDI_reaction_new(), and MCGIDI_reaction_parseFromTOM().
static int MCGIDI_reaction_initialize2 (statusMessageReporting * smr, MCGIDI_reaction * reaction) static
Definition at line 51 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::attributes, and xDataTOMAL_initial().
Referenced by MCGIDI_reaction_initialize(), and MCGIDI_reaction_release().
MCGIDI_reaction* MCGIDI_reaction_new (statusMessageReporting * smr)
Definition at line 31 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_reaction.cc
References MCGIDI_reaction_free(), MCGIDI_reaction_initialize(), and smr_malloc2.
static int MCGIDI_reaction_ParseDetermineReactionProducts (statusMessageReporting * smr, MCGIDI_POPs * pops, MCGIDI_outputChannel * outputChannel, MCGIDI_productsInfo * productsInfo, MCGIDI_reaction * reaction, double * finalQ, int level) static
Definition at line 202 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 202 of file MCGIDI_reaction.cc
References MCGIDI_distribution_s::angular, MCGIDI_product_s::decayChannel, MCGIDI_product_s::distribution, MCGIDI_outputChannel_s::genre, MCGIDI_POP_s::globalPoPsIndex, int(), MCGIDI_POP_s::level_MeV, MCGIDI_angularType_recoil, MCGIDI_channelGenre_twoBody_e, MCGIDI_channelGenre_undefined_e, MCGIDI_distributionType_angular_e, MCGIDI_distributionType_none_e, MCGIDI_distributionType_unknown_e, MCGIDI_outputChannel_getProductAtIndex(), MCGIDI_outputChannel_getQ_MeV(), MCGIDI_outputChannel_numberOfProducts(), MCGIDI_reaction_addReturnProduct(), MCGIDI_POP_s::name, MCGIDI_POP_s::numberOfGammaBranchs, MCGIDI_POP_s::parent, MCGIDI_product_s::pop, PoPs_particleIndex(), smr_setReportError2, smr_unknownID, MCGIDI_angular_s::type, and MCGIDI_distribution_s::type.
Referenced by MCGIDI_reaction_ParseReactionTypeAndDetermineProducts().
int MCGIDI_reaction_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_target_heated * target, MCGIDI_POPs * pops, MCGIDI_reaction * reaction)
Definition at line 84 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 84 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::attributes, MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::domainValuesPresent, MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, MCGIDI_reaction_s::ENDF_MT, check_license::err(), MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_reaction_initialize(), MCGIDI_reaction_ParseReactionTypeAndDetermineProducts(), MCGIDI_reaction_release(), MCGIDI_reactionType_unknown_e, MCGIDI_reaction_s::outputChannel, MCGIDI_reaction_s::outputChannelStr, ptwXY_getXMax(), ptwXY_getXMin(), MCGIDI_reaction_s::reactionType, smr_allocateCopyString2, smr_setReportError2, smr_unknownID, MCGIDI_reaction_s::target, xDataTOM_getAttributesValueInElement(), xDataTOM_interpolationFlag_linear, xDataTOME_convertAttributeToInteger(), xDataTOME_copyAttributionList(), xDataTOME_getInterpolation(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_target_heated_parseReaction().
static int MCGIDI_reaction_ParseReactionTypeAndDetermineProducts (statusMessageReporting * smr, MCGIDI_POPs * pops, MCGIDI_reaction * reaction) static
Definition at line 129 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 129 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::finalQ, MCGIDI_reaction_getENDF_MTNumber(), MCGIDI_reaction_ParseDetermineReactionProducts(), MCGIDI_reaction_particleChanges(), MCGIDI_reaction_setENDL_CSNumbers(), MCGIDI_reactionType_capture_e, MCGIDI_reactionType_elastic_e, MCGIDI_reactionType_fission_e, MCGIDI_reactionType_nuclearIsomerTransmutation_e, MCGIDI_reactionType_scattering_e, MCGIDI_reactionType_sumOfRemainingOutputChannels_e, MCGIDI_reactionType_unknown_e, nParticleChanges, MCGIDI_reaction_s::outputChannel, MCGIDI_reaction_s::productsInfo, MCGIDI_target_heated_s::projectilePOP, MCGIDI_reaction_s::reactionType, MCGIDI_reaction_s::target, and MCGIDI_target_heated_s::targetPOP.
Referenced by MCGIDI_reaction_parseFromTOM().
static int MCGIDI_reaction_particleChanges (MCGIDI_POP * projectile, MCGIDI_POP * target, MCGIDI_productsInfo * productsInfo, int n1, int * particlesChanges) static
Definition at line 177 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 177 of file MCGIDI_reaction.cc
References MCGIDI_POP_s::globalPoPsIndex, MCGIDI_productInfo_s::globalPoPsIndex, MCGIDI_productsInfo_s::numberOfProducts, PoPs_particleIndex(), and MCGIDI_productsInfo_s::productInfo.
Referenced by MCGIDI_reaction_ParseReactionTypeAndDetermineProducts().
int MCGIDI_reaction_recast (statusMessageReporting * smr, MCGIDI_reaction * reaction, GIDI_settings & , GIDI_settings_particle const * projectileSettings, double temperature_MeV, ptwXPoints * totalGroupedCrossSection)
Definition at line 496 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 496 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::crossSectionGrouped, MCGIDI_reaction_s::EMin, GIDI_settings_particle::getGroup(), GIDI_settings_particle::groupFunction(), nfu_Okay, ptwX_add_ptwX(), ptwX_free(), ptwX_getPointAtIndex(), MCGIDI_reaction_s::thresholdGroupDomain, MCGIDI_reaction_s::thresholdGroupedDeltaCrossSection, and MCGIDI_reaction_s::thresholdGroupIndex.
Referenced by MCGIDI_target_heated_recast().
int MCGIDI_reaction_release (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 69 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 69 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::attributes, MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::crossSectionGrouped, MCGIDI_outputChannel_release(), MCGIDI_reaction_initialize2(), MCGIDI_reaction_s::outputChannel, MCGIDI_reaction_s::outputChannelStr, MCGIDI_productsInfo_s::productInfo, MCGIDI_reaction_s::productsInfo, ptwX_free(), ptwXY_free(), smr_freeMemory(), MCGIDI_reaction_s::transportabilities, and xDataTOMAL_release().
Referenced by MCGIDI_reaction_free(), MCGIDI_reaction_parseFromTOM(), and MCGIDI_target_heated_release().
static int MCGIDI_reaction_setENDL_CSNumbers (statusMessageReporting * smr, MCGIDI_reaction * reaction) static
Definition at line 430 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 430 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::ENDL_C, MCGIDI_reaction_s::ENDL_S, and MCGIDI_reaction_getENDF_MTNumber().
Referenced by MCGIDI_reaction_ParseReactionTypeAndDetermineProducts().