ECCE @ EIC Software: G4VReadOutGeometry Class Reference
G4VReadOutGeometry Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4VReadOutGeometry.hh>
Public Member Functions
G4VReadOutGeometry ()
G4VReadOutGeometry (G4String)
virtual ~G4VReadOutGeometry ()
G4bool operator== (const G4VReadOutGeometry &right) const
G4bool operator!= (const G4VReadOutGeometry &right) const
void BuildROGeometry ()
virtual G4bool CheckROVolume (G4Step *, G4TouchableHistory *&)
const G4SensitiveVolumeList * GetIncludeList () const
void SetIncludeList (G4SensitiveVolumeList *value)
const G4SensitiveVolumeList * GetExcludeList () const
void SetExcludeList (G4SensitiveVolumeList *value)
G4String GetName () const
void SetName (G4String value)
G4VPhysicalVolume * GetROWorld () const
Protected Member Functions
virtual G4VPhysicalVolume * Build ()=0
G4VReadOutGeometry (const G4VReadOutGeometry &right)
G4VReadOutGeometry & operator= (const G4VReadOutGeometry &right)
virtual G4bool FindROTouchable (G4Step *)
Protected Attributes
G4VPhysicalVolume * ROworld
G4SensitiveVolumeList * fincludeList
G4SensitiveVolumeList * fexcludeList
G4String name
G4Navigator * ROnavigator
G4TouchableHistory * touchableHistory
Detailed Description
Definition at line 39 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VReadOutGeometry.hh
Constructor & Destructor Documentation
G4VReadOutGeometry::G4VReadOutGeometry ()
Definition at line 33 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VReadOutGeometry.cc
References G4Exception(), JustWarning, and ROnavigator.
G4VReadOutGeometry::G4VReadOutGeometry (G4String n)
Definition at line 61 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VReadOutGeometry.cc
References G4Exception(), JustWarning, and ROnavigator.
G4VReadOutGeometry::~G4VReadOutGeometry () virtual
Definition at line 76 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VReadOutGeometry.cc
References fexcludeList, fincludeList, ROnavigator, and touchableHistory.
G4VReadOutGeometry::G4VReadOutGeometry (const G4VReadOutGeometry & right) protected
Definition at line 49 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VReadOutGeometry.cc
References fexcludeList, fincludeList, name, ROnavigator, ROworld, and touchableHistory.
Member Function Documentation
virtual G4VPhysicalVolume* G4VReadOutGeometry::Build () protected pure virtual
Implemented in ExN04CalorimeterROGeometry, and ExN04CalorimeterROGeometry.
Referenced by BuildROGeometry().
void G4VReadOutGeometry::BuildROGeometry ()
Definition at line 103 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 103 of file G4VReadOutGeometry.cc
References Build(), ROnavigator, ROworld, and G4Navigator::SetWorldVolume().
Referenced by ExN04DetectorConstruction::Construct().
G4bool G4VReadOutGeometry::CheckROVolume (G4Step * currentStep, G4TouchableHistory *& ROhist) virtual
Definition at line 109 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 109 of file G4VReadOutGeometry.cc
References G4SensitiveVolumeList::CheckLV(), G4SensitiveVolumeList::CheckPV(), fexcludeList, fincludeList, FindROTouchable(), G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), ROworld, and touchableHistory.
Referenced by G4VGFlashSensitiveDetector::Hit(), and G4VSensitiveDetector::Hit().
G4bool G4VReadOutGeometry::FindROTouchable (G4Step * currentStep) protected virtual
Definition at line 131 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 131 of file G4VReadOutGeometry.cc
References G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetMomentumDirection(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4TouchableHistory::GetVolume(), G4Navigator::LocateGlobalPointAndUpdateTouchable(), ROnavigator, and touchableHistory.
Referenced by CheckROVolume().
const G4SensitiveVolumeList* G4VReadOutGeometry::GetExcludeList () const inline
Definition at line 78 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VReadOutGeometry.hh
References fexcludeList.
const G4SensitiveVolumeList* G4VReadOutGeometry::GetIncludeList () const inline
Definition at line 74 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VReadOutGeometry.hh
References fincludeList.
G4String G4VReadOutGeometry::GetName (void) const inline
Definition at line 82 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VReadOutGeometry.hh
References name.
Referenced by G4LogicalVolumeModel::DescribeYourselfTo(), and G4ASCIITreeSceneHandler::RequestPrimitives().
G4VPhysicalVolume* G4VReadOutGeometry::GetROWorld () const inline
Definition at line 87 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VReadOutGeometry.hh
References ROworld.
Referenced by G4LogicalVolumeModel::DescribeYourselfTo().
G4bool G4VReadOutGeometry::operator!= (const G4VReadOutGeometry & right) const
Definition at line 100 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 100 of file G4VReadOutGeometry.cc
G4VReadOutGeometry & G4VReadOutGeometry::operator= (const G4VReadOutGeometry & right) protected
Definition at line 85 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VReadOutGeometry.cc
References fexcludeList, fincludeList, name, ROnavigator, ROworld, and touchableHistory.
G4bool G4VReadOutGeometry::operator== (const G4VReadOutGeometry & right) const
Definition at line 97 of file G4VReadOutGeometry.cc.
View newest version in sPHENIX GitHub at line 97 of file G4VReadOutGeometry.cc
void G4VReadOutGeometry::SetExcludeList (G4SensitiveVolumeList * value) inline
Definition at line 80 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VReadOutGeometry.hh
References fexcludeList.
void G4VReadOutGeometry::SetIncludeList (G4SensitiveVolumeList * value) inline
Definition at line 76 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VReadOutGeometry.hh
References fincludeList.
void G4VReadOutGeometry::SetName (G4String value) inline
Definition at line 84 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VReadOutGeometry.hh
Member Data Documentation
G4SensitiveVolumeList* G4VReadOutGeometry::fexcludeList protected
Definition at line 67 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VReadOutGeometry.hh
Referenced by CheckROVolume(), G4VReadOutGeometry(), GetExcludeList(), operator=(), SetExcludeList(), and ~G4VReadOutGeometry().
G4SensitiveVolumeList* G4VReadOutGeometry::fincludeList protected
Definition at line 66 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VReadOutGeometry.hh
Referenced by CheckROVolume(), G4VReadOutGeometry(), GetIncludeList(), operator=(), SetIncludeList(), and ~G4VReadOutGeometry().
G4String G4VReadOutGeometry::name protected
Definition at line 68 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VReadOutGeometry.hh
Referenced by G4VReadOutGeometry(), GetName(), and operator=().
G4Navigator* G4VReadOutGeometry::ROnavigator protected
Definition at line 70 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VReadOutGeometry.hh
Referenced by BuildROGeometry(), FindROTouchable(), G4VReadOutGeometry(), operator=(), and ~G4VReadOutGeometry().
G4VPhysicalVolume* G4VReadOutGeometry::ROworld protected
Definition at line 65 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VReadOutGeometry.hh
Referenced by BuildROGeometry(), CheckROVolume(), G4VReadOutGeometry(), GetROWorld(), and operator=().
G4TouchableHistory* G4VReadOutGeometry::touchableHistory protected
Definition at line 71 of file G4VReadOutGeometry.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VReadOutGeometry.hh
Referenced by CheckROVolume(), FindROTouchable(), G4VReadOutGeometry(), operator=(), and ~G4VReadOutGeometry().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4VReadOutGeometry.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4VReadOutGeometry.cc