ECCE @ EIC Software: G4EnclosingCylinder Class Reference
G4EnclosingCylinder Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4EnclosingCylinder.hh>
Public Member Functions
G4EnclosingCylinder (const G4ReduciblePolygon *rz, G4bool phiIsOpen, G4double startPhi, G4double totalPhi)
~G4EnclosingCylinder ()
G4bool MustBeOutside (const G4ThreeVector &p) const
G4bool ShouldMiss (const G4ThreeVector &p, const G4ThreeVector &v) const
G4EnclosingCylinder (__void__ &)
Protected Attributes
G4double radius
G4double zLo
G4double zHi
G4bool phiIsOpen
G4double startPhi
G4double totalPhi
G4double rx1 =0.0
G4double ry1 =0.0
G4double dx1 =0.0
G4double dy1 =0.0
G4double rx2 =0.0
G4double ry2 =0.0
G4double dx2 =0.0
G4double dy2 =0.0
G4bool concave
Detailed Description
Definition at line 45 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 45 of file G4EnclosingCylinder.hh
Constructor & Destructor Documentation
G4EnclosingCylinder::G4EnclosingCylinder (const G4ReduciblePolygon * rz, G4bool phiIsOpen, G4double startPhi, G4double totalPhi)
Definition at line 39 of file G4EnclosingCylinder.cc.
View newest version in sPHENIX GitHub at line 39 of file G4EnclosingCylinder.cc
References G4ReduciblePolygon::Amax(), G4ReduciblePolygon::Bmax(), G4ReduciblePolygon::Bmin(), dx1, dx2, dy1, dy2, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, phiIsOpen, radius, rx1, rx2, ry1, ry2, startPhi, totalPhi, zHi, and zLo.
G4EnclosingCylinder::~G4EnclosingCylinder ()
Definition at line 91 of file G4EnclosingCylinder.cc.
View newest version in sPHENIX GitHub at line 91 of file G4EnclosingCylinder.cc
G4EnclosingCylinder::G4EnclosingCylinder (__void__ &)
Definition at line 83 of file G4EnclosingCylinder.cc.
View newest version in sPHENIX GitHub at line 83 of file G4EnclosingCylinder.cc
Member Function Documentation
G4bool G4EnclosingCylinder::MustBeOutside (const G4ThreeVector & p) const
Definition at line 101 of file G4EnclosingCylinder.cc.
View newest version in sPHENIX GitHub at line 101 of file G4EnclosingCylinder.cc
References concave, dx1, dx2, dy1, dy2, CLHEP::Hep3Vector::perp(), phiIsOpen, radius, rx1, rx2, ry1, ry2, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), zHi, and zLo.
Referenced by G4GenericPolycone::Inside(), G4Polyhedra::Inside(), G4Polycone::Inside(), and ShouldMiss().
G4bool G4EnclosingCylinder::ShouldMiss (const G4ThreeVector & p, const G4ThreeVector & v) const
Definition at line 130 of file G4EnclosingCylinder.cc.
View newest version in sPHENIX GitHub at line 130 of file G4EnclosingCylinder.cc
References Acts::VectorHelpers::cross(), MustBeOutside(), CLHEP::Hep3Vector::perp(), radius, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GenericPolycone::DistanceToIn(), G4Polycone::DistanceToIn(), and G4Polyhedra::DistanceToIn().
Member Data Documentation
G4bool G4EnclosingCylinder::concave protected
Definition at line 83 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4EnclosingCylinder.hh
Referenced by MustBeOutside().
G4double G4EnclosingCylinder::dx1 =0.0 protected
Definition at line 79 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::dx2 =0.0 protected
Definition at line 81 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::dy1 =0.0 protected
Definition at line 79 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::dy2 =0.0 protected
Definition at line 81 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4bool G4EnclosingCylinder::phiIsOpen protected
Definition at line 74 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::radius protected
Definition at line 71 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), MustBeOutside(), and ShouldMiss().
G4double G4EnclosingCylinder::rx1 =0.0 protected
Definition at line 78 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::rx2 =0.0 protected
Definition at line 80 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::ry1 =0.0 protected
Definition at line 78 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::ry2 =0.0 protected
Definition at line 80 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::startPhi protected
Definition at line 75 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder().
G4double G4EnclosingCylinder::totalPhi protected
Definition at line 75 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder().
G4double G4EnclosingCylinder::zHi protected
Definition at line 72 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
G4double G4EnclosingCylinder::zLo protected
Definition at line 72 of file G4EnclosingCylinder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4EnclosingCylinder.hh
Referenced by G4EnclosingCylinder(), and MustBeOutside().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4EnclosingCylinder.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4EnclosingCylinder.cc