ECCE @ EIC Software: G4ParticleHPThermalScatteringData Class Reference
G4ParticleHPThermalScatteringData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPThermalScatteringData.hh>
Public Member Functions
G4ParticleHPThermalScatteringData ()
~G4ParticleHPThermalScatteringData ()
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int, G4int, const G4Element *, const G4Material *)
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
G4bool IsApplicable (const G4DynamicParticle *, const G4Element *)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *)
G4double GetInelasticCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *)
G4double GetCoherentCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *)
G4double GetIncoherentCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
void AddUserThermalScatteringFile (G4String, G4String)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4double GetX (const G4DynamicParticle *, G4double aT, std::map< G4double, G4ParticleHPVector * > *)
void clearCurrentXSData ()
std::map< G4double,
G4ParticleHPVector * > * readData (G4String)
G4int getTS_ID (const G4Material *, const G4Element *)
Private Attributes
G4double emax
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * coherent
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * incoherent
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * inelastic
std::vector< G4int > indexOfThermalElement
G4ParticleHPThermalScatteringNames * names
G4double ke_cache
G4double xs_cache
const G4Element * element_cache
const G4Material * material_cache
std::map< std::pair< const
G4Material *, const G4Element * >
, G4int > dic
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 61 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPThermalScatteringData.hh
Constructor & Destructor Documentation
G4ParticleHPThermalScatteringData::G4ParticleHPThermalScatteringData ()
Definition at line 56 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPThermalScatteringData.cc
References element_cache, emax, eV, indexOfThermalElement, ke_cache, material_cache, MeV, names, G4VCrossSectionDataSet::SetMaxKinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), and xs_cache.
G4ParticleHPThermalScatteringData::~G4ParticleHPThermalScatteringData ()
Definition at line 77 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPThermalScatteringData.cc
References clearCurrentXSData(), and names.
Member Function Documentation
void G4ParticleHPThermalScatteringData::AddUserThermalScatteringFile (G4String nameG4Element, G4String filename)
Definition at line 568 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 568 of file G4ParticleHPThermalScatteringData.cc
References G4ParticleHPThermalScatteringNames::AddThermalElement(), and names.
Referenced by G4ParticleHPThermalScattering::AddUserThermalScatteringFile().
void G4ParticleHPThermalScatteringData::BuildPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 215 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 215 of file G4ParticleHPThermalScatteringData.cc
References clearCurrentXSData(), coherent, dic, G4cout, G4endl, G4ThreadLocal, G4Material::GetElement(), G4Element::GetElementTable(), G4ParticleHPManager::GetInstance(), G4Material::GetMaterialTable(), G4Element::GetName(), G4Material::GetName(), G4Element::GetNumberOfElements(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4ParticleHPManager::GetThermalScatteringCoherentCrossSections(), G4ParticleHPManager::GetThermalScatteringIncoherentCrossSections(), G4ParticleHPManager::GetThermalScatteringInelasticCrossSections(), G4ParticleHPThermalScatteringNames::GetTS_NDL_Name(), incoherent, inelastic, G4Threading::IsMasterThread(), G4ParticleHPThermalScatteringNames::IsThisThermalElement(), it, material(), names, G4Neutron::Neutron(), readData(), G4ParticleHPManager::RegisterThermalScatteringCoherentCrossSections(), G4ParticleHPManager::RegisterThermalScatteringIncoherentCrossSections(), G4ParticleHPManager::RegisterThermalScatteringInelasticCrossSections(), and second.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
void G4ParticleHPThermalScatteringData::clearCurrentXSData () private
Definition at line 128 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleHPThermalScatteringData.cc
References coherent, incoherent, inelastic, and it.
Referenced by BuildPhysicsTable(), and ~G4ParticleHPThermalScatteringData().
void G4ParticleHPThermalScatteringData::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 572 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 572 of file G4ParticleHPThermalScatteringData.cc
void G4ParticleHPThermalScatteringData::DumpPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 401 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 401 of file G4ParticleHPThermalScatteringData.cc
References G4Neutron::Neutron().
G4double G4ParticleHPThermalScatteringData::GetCoherentCrossSection (const G4DynamicParticle * aP, const G4Element * anE, const G4Material * aM)
Definition at line 481 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 481 of file G4ParticleHPThermalScatteringData.cc
References coherent, G4Material::GetTemperature(), getTS_ID(), and GetX().
Referenced by G4ParticleHPThermalScattering::ApplyYourself().
G4double G4ParticleHPThermalScatteringData::GetCrossSection (const G4DynamicParticle * aP, const G4Element * anE, const G4Material * aM)
Definition at line 450 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 450 of file G4ParticleHPThermalScatteringData.cc
References coherent, G4Material::GetTemperature(), getTS_ID(), GetX(), incoherent, and inelastic.
Referenced by G4ParticleHPThermalScattering::ApplyYourself(), and GetIsoCrossSection().
G4double G4ParticleHPThermalScatteringData::GetIncoherentCrossSection (const G4DynamicParticle * aP, const G4Element * anE, const G4Material * aM)
Definition at line 490 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 490 of file G4ParticleHPThermalScatteringData.cc
References G4Material::GetTemperature(), getTS_ID(), GetX(), and incoherent.
G4double G4ParticleHPThermalScatteringData::GetInelasticCrossSection (const G4DynamicParticle * aP, const G4Element * anE, const G4Material * aM)
Definition at line 472 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 472 of file G4ParticleHPThermalScatteringData.cc
References G4Material::GetTemperature(), getTS_ID(), GetX(), and inelastic.
Referenced by G4ParticleHPThermalScattering::ApplyYourself().
G4double G4ParticleHPThermalScatteringData::GetIsoCrossSection (const G4DynamicParticle * dp, G4int , G4int , const G4Isotope * , const G4Element * element, const G4Material * material) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 110 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPThermalScatteringData.cc
References element_cache, GetCrossSection(), G4DynamicParticle::GetKineticEnergy(), ke_cache, material(), material_cache, and xs_cache.
G4int G4ParticleHPThermalScatteringData::getTS_ID (const G4Material * material, const G4Element * element) private
Definition at line 501 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 501 of file G4ParticleHPThermalScatteringData.cc
References dic.
Referenced by GetCoherentCrossSection(), GetCrossSection(), GetIncoherentCrossSection(), and GetInelasticCrossSection().
G4double G4ParticleHPThermalScatteringData::GetX (const G4DynamicParticle * aP, G4double aT, std::map< G4double, G4ParticleHPVector * > * amapTemp_EnergyCross) private
Definition at line 514 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 514 of file G4ParticleHPThermalScatteringData.cc
References G4cout, G4endl, G4DynamicParticle::GetKineticEnergy(), it, kelvin, T, and X.
Referenced by GetCoherentCrossSection(), GetCrossSection(), GetIncoherentCrossSection(), and GetInelasticCrossSection().
G4bool G4ParticleHPThermalScatteringData::IsApplicable (const G4DynamicParticle * aP, const G4Element * anEle)
Definition at line 182 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 182 of file G4ParticleHPThermalScatteringData.cc
References emax, G4DynamicParticle::GetDefinition(), G4Element::GetIndex(), G4DynamicParticle::GetKineticEnergy(), indexOfThermalElement, it, and G4Neutron::Neutron().
G4bool G4ParticleHPThermalScatteringData::IsIsoApplicable (const G4DynamicParticle * dp, G4int , G4int , const G4Element * element, const G4Material * material) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 85 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPThermalScatteringData.cc
References dic, eV, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and G4Neutron::Neutron().
std::map< G4double, G4ParticleHPVector * > * G4ParticleHPThermalScatteringData::readData (G4String full_name) private
Definition at line 370 of file G4ParticleHPThermalScatteringData.cc.
View newest version in sPHENIX GitHub at line 370 of file G4ParticleHPThermalScatteringData.cc
References barn, eV, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), and G4ParticleHPVector::Init().
Referenced by BuildPhysicsTable().
Member Data Documentation
std::map< G4int , std::map< G4double , G4ParticleHPVector* >* >* G4ParticleHPThermalScatteringData::coherent private
Definition at line 110 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPThermalScatteringData.hh
Referenced by BuildPhysicsTable(), clearCurrentXSData(), GetCoherentCrossSection(), and GetCrossSection().
std::map< std::pair < const G4Material* , const G4Element* > , G4int > G4ParticleHPThermalScatteringData::dic private
Definition at line 126 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPThermalScatteringData.hh
Referenced by BuildPhysicsTable(), getTS_ID(), and IsIsoApplicable().
const G4Element* G4ParticleHPThermalScatteringData::element_cache private
Definition at line 123 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ParticleHPThermalScatteringData.hh
Referenced by G4ParticleHPThermalScatteringData(), and GetIsoCrossSection().
G4double G4ParticleHPThermalScatteringData::emax private
Definition at line 105 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPThermalScatteringData.hh
Referenced by G4ParticleHPThermalScatteringData(), and IsApplicable().
std::map< G4int , std::map< G4double , G4ParticleHPVector* >* >* G4ParticleHPThermalScatteringData::incoherent private
Definition at line 111 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPThermalScatteringData.hh
Referenced by BuildPhysicsTable(), clearCurrentXSData(), GetCrossSection(), and GetIncoherentCrossSection().
std::vector< G4int > G4ParticleHPThermalScatteringData::indexOfThermalElement private
Definition at line 116 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParticleHPThermalScatteringData.hh
Referenced by G4ParticleHPThermalScatteringData(), and IsApplicable().
std::map< G4int , std::map< G4double , G4ParticleHPVector* >* >* G4ParticleHPThermalScatteringData::inelastic private
Definition at line 112 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPThermalScatteringData.hh
Referenced by BuildPhysicsTable(), clearCurrentXSData(), GetCrossSection(), and GetInelasticCrossSection().
G4double G4ParticleHPThermalScatteringData::ke_cache private
Definition at line 121 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ParticleHPThermalScatteringData.hh
Referenced by G4ParticleHPThermalScatteringData(), and GetIsoCrossSection().
const G4Material* G4ParticleHPThermalScatteringData::material_cache private
Definition at line 124 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ParticleHPThermalScatteringData.hh
Referenced by G4ParticleHPThermalScatteringData(), and GetIsoCrossSection().
G4ParticleHPThermalScatteringNames* G4ParticleHPThermalScatteringData::names private
Definition at line 117 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleHPThermalScatteringData.hh
Referenced by AddUserThermalScatteringFile(), BuildPhysicsTable(), G4ParticleHPThermalScatteringData(), and ~G4ParticleHPThermalScatteringData().
G4double G4ParticleHPThermalScatteringData::xs_cache private
Definition at line 122 of file G4ParticleHPThermalScatteringData.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ParticleHPThermalScatteringData.hh
Referenced by G4ParticleHPThermalScatteringData(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPThermalScatteringData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPThermalScatteringData.cc