ECCE @ EIC Software: G4FastPathHadronicCrossSection Namespace Reference
G4FastPathHadronicCrossSection Namespace Reference
Classes
struct fastPathEntry
struct cycleCountEntry
struct timing
struct getCrossSectionCount
struct G4CrossSectionDataStore_Key_Hash
struct G4CrossSectionDataStore_Key_EqualTo
struct fastPathRequestConfig_t
struct fastPathRequestConfig_Less
struct controlFlag
struct fastPathParameters
Typedefs
using XSParam = G4PhysicsFreeVector
using G4CrossSectionDataStore_Key = std::pair< const G4ParticleDefinition *, const G4Material * >
using G4CrossSectionDataStore_Cache = std::unordered_map< G4CrossSectionDataStore_Key, cycleCountEntry *, G4CrossSectionDataStore_Key_Hash, G4CrossSectionDataStore_Key_EqualTo >
using G4CrossSectionDataStore_Requests = std::set< fastPathRequestConfig_t, fastPathRequestConfig_Less >
Functions
static void logInvocationTriedOneLine (cycleCountEntry *)
static void logInvocationOneLine (cycleCountEntry *)
static void logHit (cycleCountEntry *)
static void logInvocationCountFastPath (cycleCountEntry *)
static void logInvocationCountSlowPAth (cycleCountEntry *)
void logStartCountCycles (timing &)
void logStopCountCycles (timing &)
static void logInitCyclesFastPath (cycleCountEntry *, timing &)
static void logTotalCyclesFastPath (cycleCountEntry *, timing &)
static void logTotalCyclesSlowPath (cycleCountEntry *, timing &)
static void logTiming (cycleCountEntry *, fastPathEntry *, timing &)
Typedef Documentation
using G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Cache = typedef std::unordered_map<G4CrossSectionDataStore_Key,cycleCountEntry*, G4CrossSectionDataStore_Key_Hash,G4CrossSectionDataStore_Key_EqualTo>
Definition at line 139 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 139 of file G4FastPathHadronicCrossSection.hh
using G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Key = typedef std::pair<const G4ParticleDefinition*,const G4Material*>
Definition at line 52 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 52 of file G4FastPathHadronicCrossSection.hh
using G4FastPathHadronicCrossSection::G4CrossSectionDataStore_Requests = typedef std::set<fastPathRequestConfig_t,fastPathRequestConfig_Less>
Definition at line 152 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 152 of file G4FastPathHadronicCrossSection.hh
using G4FastPathHadronicCrossSection::XSParam = typedef G4PhysicsFreeVector
Definition at line 50 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 50 of file G4FastPathHadronicCrossSection.hh
Function Documentation
void G4FastPathHadronicCrossSection::logHit (cycleCountEntry *) inline static
Definition at line 257 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 257 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection().
void G4FastPathHadronicCrossSection::logInitCyclesFastPath (cycleCountEntry * , timing &) inline static
Definition at line 260 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 260 of file G4FastPathHadronicCrossSection.hh
void G4FastPathHadronicCrossSection::logInvocationCountFastPath (cycleCountEntry *) inline static
Definition at line 258 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 258 of file G4FastPathHadronicCrossSection.hh
void G4FastPathHadronicCrossSection::logInvocationCountSlowPAth (cycleCountEntry *) inline static
Definition at line 259 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 259 of file G4FastPathHadronicCrossSection.hh
void G4FastPathHadronicCrossSection::logInvocationOneLine (cycleCountEntry *) inline static
Definition at line 256 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 256 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection().
void G4FastPathHadronicCrossSection::logInvocationTriedOneLine (cycleCountEntry *) inline static
Definition at line 255 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 255 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection().
void G4FastPathHadronicCrossSection::logStartCountCycles (timing &) inline
Definition at line 190 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 190 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection().
void G4FastPathHadronicCrossSection::logStopCountCycles (timing &) inline
Definition at line 191 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 191 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection().
void G4FastPathHadronicCrossSection::logTiming (cycleCountEntry * , fastPathEntry * , timing &) inline static
Definition at line 263 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 263 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection().
void G4FastPathHadronicCrossSection::logTotalCyclesFastPath (cycleCountEntry * , timing &) inline static
Definition at line 261 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 261 of file G4FastPathHadronicCrossSection.hh
void G4FastPathHadronicCrossSection::logTotalCyclesSlowPath (cycleCountEntry * , timing &) inline static
Definition at line 262 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 262 of file G4FastPathHadronicCrossSection.hh