ECCE @ EIC Software: G4DeuteronBuilder Class Reference
G4DeuteronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4DeuteronBuilder.hh>
Public Member Functions
G4DeuteronBuilder ()
virtual ~G4DeuteronBuilder ()
virtual void Build () finaloverride
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4DeuteronInelasticProcess * theDeuteronInelastic
std::vector< G4VDeuteronBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 48 of file G4DeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 48 of file G4DeuteronBuilder.hh
Constructor & Destructor Documentation
G4DeuteronBuilder::G4DeuteronBuilder ()
Definition at line 56 of file G4DeuteronBuilder.cc.
View newest version in sPHENIX GitHub at line 56 of file G4DeuteronBuilder.cc
References theDeuteronInelastic.
virtual G4DeuteronBuilder::~G4DeuteronBuilder () inline virtual
Definition at line 52 of file G4DeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DeuteronBuilder.hh
Member Function Documentation
void G4DeuteronBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 43 of file G4DeuteronBuilder.cc.
View newest version in sPHENIX GitHub at line 43 of file G4DeuteronBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4Deuteron::Deuteron(), G4ParticleDefinition::GetProcessManager(), theDeuteronInelastic, theModelCollections, and wasActivated.
void G4DeuteronBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 61 of file G4DeuteronBuilder.cc.
View newest version in sPHENIX GitHub at line 61 of file G4DeuteronBuilder.cc
References G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Member Data Documentation
G4DeuteronInelasticProcess* G4DeuteronBuilder::theDeuteronInelastic private
Definition at line 58 of file G4DeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4DeuteronBuilder.hh
Referenced by Build(), and G4DeuteronBuilder().
std::vector<G4VDeuteronBuilder *> G4DeuteronBuilder::theModelCollections private
Definition at line 60 of file G4DeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4DeuteronBuilder.hh
Referenced by Build(), and RegisterMe().
G4bool G4DeuteronBuilder::wasActivated private
Definition at line 62 of file G4DeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4DeuteronBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4DeuteronBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4DeuteronBuilder.cc