ECCE @ EIC Software: G4IntersectingCone Class Reference
G4IntersectingCone Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4IntersectingCone.hh>
Public Member Functions
G4IntersectingCone (const G4double r[2], const G4double z[2])
virtual ~G4IntersectingCone ()
G4int LineHitsCone (const G4ThreeVector &p, const G4ThreeVector &v, G4double *s1, G4double *s2)
G4bool HitOn (const G4double r, const G4double z)
G4double RLo () const
G4double RHi () const
G4double ZLo () const
G4double ZHi () const
G4IntersectingCone (__void__ &)
Protected Member Functions
G4int LineHitsCone1 (const G4ThreeVector &p, const G4ThreeVector &v, G4double *s1, G4double *s2)
G4int LineHitsCone2 (const G4ThreeVector &p, const G4ThreeVector &v, G4double *s1, G4double *s2)
Protected Attributes
G4double zLo
G4double zHi
G4double rLo
G4double rHi
G4bool type1 = false
G4double A
G4double B
Detailed Description
Definition at line 42 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 42 of file G4IntersectingCone.hh
Constructor & Destructor Documentation
G4IntersectingCone::G4IntersectingCone (const G4double r[2], const G4double z[2])
Definition at line 37 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 37 of file G4IntersectingCone.cc
References A, kdfinder::abs(), B, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), max, min, rHi, rLo, type1, zHi, and zLo.
G4IntersectingCone::~G4IntersectingCone () virtual
Definition at line 76 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 76 of file G4IntersectingCone.cc
G4IntersectingCone::G4IntersectingCone (__void__ &)
Definition at line 69 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 69 of file G4IntersectingCone.cc
Member Function Documentation
G4bool G4IntersectingCone::HitOn (const G4double r, const G4double z)
Definition at line 85 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 85 of file G4IntersectingCone.cc
References rHi, type1, and zHi.
Referenced by G4PolyconeSide::PointOnCone().
G4int G4IntersectingCone::LineHitsCone (const G4ThreeVector & p, const G4ThreeVector & v, G4double * s1, G4double * s2)
Definition at line 109 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 109 of file G4IntersectingCone.cc
References LineHitsCone1(), LineHitsCone2(), and type1.
Referenced by G4PolyconeSide::Intersect(), and G4PolyhedraSide::LineHitsSegments().
G4int G4IntersectingCone::LineHitsCone1 (const G4ThreeVector & p, const G4ThreeVector & v, G4double * s1, G4double * s2) protected
Definition at line 181 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 181 of file G4IntersectingCone.cc
References a, A, b, B, c, DBL_EPSILON, EPS, kInfinity, max, min, sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and G4InuclParticleNames::z0.
Referenced by LineHitsCone().
G4int G4IntersectingCone::LineHitsCone2 (const G4ThreeVector & p, const G4ThreeVector & v, G4double * s1, G4double * s2) protected
Definition at line 291 of file G4IntersectingCone.cc.
View newest version in sPHENIX GitHub at line 291 of file G4IntersectingCone.cc
References a, A, b, B, c, DBL_EPSILON, EPS, kInfinity, max, min, sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and G4InuclParticleNames::z0.
Referenced by LineHitsCone().
G4double G4IntersectingCone::RHi () const inline
Definition at line 55 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 55 of file G4IntersectingCone.hh
References rHi.
G4double G4IntersectingCone::RLo () const inline
Definition at line 54 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 54 of file G4IntersectingCone.hh
References rLo.
G4double G4IntersectingCone::ZHi () const inline
Definition at line 57 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 57 of file G4IntersectingCone.hh
References zHi.
Referenced by G4PolyconeSide::Extent(), and G4PolyhedraSide::Extent().
G4double G4IntersectingCone::ZLo () const inline
Definition at line 56 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 56 of file G4IntersectingCone.hh
References zLo.
Referenced by G4PolyconeSide::Extent(), and G4PolyhedraSide::Extent().
Member Data Documentation
G4double G4IntersectingCone::A protected
Definition at line 74 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 74 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), LineHitsCone1(), and LineHitsCone2().
G4double G4IntersectingCone::B protected
Definition at line 74 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 74 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), LineHitsCone1(), and LineHitsCone2().
G4double G4IntersectingCone::rHi protected
Definition at line 69 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 69 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), HitOn(), and RHi().
G4double G4IntersectingCone::rLo protected
Definition at line 69 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 69 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), and RLo().
G4bool G4IntersectingCone::type1 = false protected
Definition at line 72 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 72 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), HitOn(), and LineHitsCone().
G4double G4IntersectingCone::zHi protected
Definition at line 69 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 69 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), HitOn(), and ZHi().
G4double G4IntersectingCone::zLo protected
Definition at line 69 of file G4IntersectingCone.hh.
View newest version in sPHENIX GitHub at line 69 of file G4IntersectingCone.hh
Referenced by G4IntersectingCone(), and ZLo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4IntersectingCone.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4IntersectingCone.cc