ECCE @ EIC Software: CCalEcal Class Reference
CCalEcal Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalEcal.hh>
Public Member Functions
CCalEcal (const G4String &name)
virtual ~CCalEcal ()
G4String getGenMat () const
G4double getWidBox () const
G4double getLengBox () const
G4double getXpos () const
G4double getYpos () const
G4double getZpos () const
G4double getThetaX () const
G4double getPhiX () const
G4double getThetaY () const
G4double getPhiY () const
G4double getThetaZ () const
G4double getPhiZ () const
G4String getLayMat () const
G4int getLayNum () const
G4double getLayRadius () const
G4double getLayAngle () const
G4double getLengFront () const
G4double getLayPar (unsigned int i) const
G4String getCrystMat () const
G4int getCrystNum () const
G4double getCrystLength () const
G4double getCrystTol () const
G4double getCrystPar (unsigned int i) const
G4String getSuppMat () const
G4double getDxSupp () const
G4double getDySupp () const
G4double getDzSupp () const
G4double getDistSupp () const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual G4int readFile ()
virtual void constructDaughters ()
Protected Member Functions inherited from CCalDetector
G4int buildFromFile ()
Private Attributes
G4String genMat
G4double widBox
G4double lengBox
G4double xpos
G4double ypos
G4double zpos
G4double thetaX
G4double phiX
G4double thetaY
G4double phiY
G4double thetaZ
G4double phiZ
G4String layMat
G4int layNum
G4double layRadius
G4double layAngle
G4double lengFront
G4double layPar [5]
G4String crystMat
G4int crystNum
G4double crystLength
G4double crystTol
G4double crystPar [5]
G4String suppMat
G4double dxSupp
G4double dySupp
G4double dzSupp
G4double distSupp
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Detailed Description
Definition at line 35 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 35 of file CCalEcal.hh
Constructor & Destructor Documentation
CCalEcal::CCalEcal (const G4String & name) inline
Definition at line 40 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalEcal.hh
CCalEcal::~CCalEcal () virtual
Definition at line 38 of file CCalEcal.cc.
View newest version in sPHENIX GitHub at line 38 of file CCalEcal.cc
Member Function Documentation
void CCalEcal::constructDaughters () protected virtual
Implements CCalDetector.
Definition at line 112 of file CCalEcal.cc.
View newest version in sPHENIX GitHub at line 112 of file CCalEcal.cc
G4double CCalEcal::getCrystLength () const inline
Definition at line 65 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 65 of file CCalEcal.hh
References crystLength.
Referenced by CCalG4Ecal::constructGlobal().
G4String CCalEcal::getCrystMat () const inline
Definition at line 63 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalEcal.hh
References crystMat.
Referenced by CCalG4Ecal::constructGlobal().
G4int CCalEcal::getCrystNum () const inline
Definition at line 64 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 64 of file CCalEcal.hh
References crystNum.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getCrystPar (unsigned int i) const inline
Definition at line 67 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 67 of file CCalEcal.hh
References crystPar.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getCrystTol () const inline
Definition at line 66 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 66 of file CCalEcal.hh
References crystTol.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getDistSupp () const inline
Definition at line 72 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 72 of file CCalEcal.hh
References distSupp.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getDxSupp () const inline
Definition at line 69 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 69 of file CCalEcal.hh
References dxSupp.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getDySupp () const inline
Definition at line 70 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 70 of file CCalEcal.hh
References dySupp.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getDzSupp () const inline
Definition at line 71 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 71 of file CCalEcal.hh
References dzSupp.
Referenced by CCalG4Ecal::constructGlobal().
G4String CCalEcal::getGenMat () const inline
Definition at line 45 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 45 of file CCalEcal.hh
References genMat.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getLayAngle () const inline
Definition at line 60 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 60 of file CCalEcal.hh
References layAngle.
Referenced by CCalG4Ecal::constructGlobal().
G4String CCalEcal::getLayMat () const inline
Definition at line 57 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 57 of file CCalEcal.hh
References layMat.
Referenced by CCalG4Ecal::constructGlobal().
G4int CCalEcal::getLayNum () const inline
Definition at line 58 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 58 of file CCalEcal.hh
References layNum.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getLayPar (unsigned int i) const inline
Definition at line 62 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalEcal.hh
References layPar.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getLayRadius () const inline
Definition at line 59 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 59 of file CCalEcal.hh
References layRadius.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getLengBox () const inline
Definition at line 47 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 47 of file CCalEcal.hh
References lengBox.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getLengFront () const inline
Definition at line 61 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalEcal.hh
References lengFront.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getPhiX () const inline
Definition at line 52 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalEcal.hh
References phiX.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getPhiY () const inline
Definition at line 54 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalEcal.hh
References phiY.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getPhiZ () const inline
Definition at line 56 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 56 of file CCalEcal.hh
References phiZ.
Referenced by CCalG4Ecal::constructIn().
G4String CCalEcal::getSuppMat () const inline
Definition at line 68 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 68 of file CCalEcal.hh
References suppMat.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getThetaX () const inline
Definition at line 51 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalEcal.hh
References thetaX.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getThetaY () const inline
Definition at line 53 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalEcal.hh
References thetaY.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getThetaZ () const inline
Definition at line 55 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 55 of file CCalEcal.hh
References thetaZ.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getWidBox () const inline
Definition at line 46 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 46 of file CCalEcal.hh
References widBox.
Referenced by CCalG4Ecal::constructGlobal().
G4double CCalEcal::getXpos () const inline
Definition at line 48 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 48 of file CCalEcal.hh
References xpos.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getYpos () const inline
Definition at line 49 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 49 of file CCalEcal.hh
References ypos.
Referenced by CCalG4Ecal::constructIn().
G4double CCalEcal::getZpos () const inline
Definition at line 50 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 50 of file CCalEcal.hh
References zpos.
Referenced by CCalG4Ecal::constructIn().
G4int CCalEcal::readFile () protected virtual
Implements CCalDetector.
Definition at line 40 of file CCalEcal.cc.
View newest version in sPHENIX GitHub at line 40 of file CCalEcal.cc
References crystLength, crystMat, crystNum, crystPar, crystTol, deg, distSupp, dxSupp, dySupp, dzSupp, CCalDetector::File(), findDO(), G4cout, G4endl, genMat, jump(), layAngle, layMat, layNum, layPar, layRadius, lengBox, lengFront, openGeomFile(), CCalDetector::pathName, phiX, phiY, phiZ, readName(), suppMat, tab(), thetaX, thetaY, thetaZ, widBox, xpos, ypos, and zpos.
Member Data Documentation
G4double CCalEcal::crystLength private
Definition at line 91 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 91 of file CCalEcal.hh
Referenced by getCrystLength(), and readFile().
G4String CCalEcal::crystMat private
Definition at line 89 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 89 of file CCalEcal.hh
Referenced by getCrystMat(), and readFile().
G4int CCalEcal::crystNum private
Definition at line 90 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 90 of file CCalEcal.hh
Referenced by getCrystNum(), and readFile().
G4double CCalEcal::crystPar[5] private
Definition at line 93 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 93 of file CCalEcal.hh
Referenced by getCrystPar(), and readFile().
G4double CCalEcal::crystTol private
Definition at line 92 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 92 of file CCalEcal.hh
Referenced by getCrystTol(), and readFile().
G4double CCalEcal::distSupp private
Definition at line 96 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 96 of file CCalEcal.hh
Referenced by getDistSupp(), and readFile().
G4double CCalEcal::dxSupp private
Definition at line 95 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalEcal.hh
Referenced by getDxSupp(), and readFile().
G4double CCalEcal::dySupp private
Definition at line 95 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalEcal.hh
Referenced by getDySupp(), and readFile().
G4double CCalEcal::dzSupp private
Definition at line 95 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalEcal.hh
Referenced by getDzSupp(), and readFile().
G4String CCalEcal::genMat private
Definition at line 80 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 80 of file CCalEcal.hh
Referenced by getGenMat(), and readFile().
G4double CCalEcal::layAngle private
Definition at line 86 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 86 of file CCalEcal.hh
Referenced by getLayAngle(), and readFile().
G4String CCalEcal::layMat private
Definition at line 84 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 84 of file CCalEcal.hh
Referenced by getLayMat(), and readFile().
G4int CCalEcal::layNum private
Definition at line 85 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 85 of file CCalEcal.hh
Referenced by getLayNum(), and readFile().
G4double CCalEcal::layPar[5] private
Definition at line 88 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 88 of file CCalEcal.hh
Referenced by getLayPar(), and readFile().
G4double CCalEcal::layRadius private
Definition at line 86 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 86 of file CCalEcal.hh
Referenced by getLayRadius(), and readFile().
G4double CCalEcal::lengBox private
Definition at line 81 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 81 of file CCalEcal.hh
Referenced by getLengBox(), and readFile().
G4double CCalEcal::lengFront private
Definition at line 87 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 87 of file CCalEcal.hh
Referenced by getLengFront(), and readFile().
G4double CCalEcal::phiX private
Definition at line 83 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalEcal.hh
Referenced by getPhiX(), and readFile().
G4double CCalEcal::phiY private
Definition at line 83 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalEcal.hh
Referenced by getPhiY(), and readFile().
G4double CCalEcal::phiZ private
Definition at line 83 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalEcal.hh
Referenced by getPhiZ(), and readFile().
G4String CCalEcal::suppMat private
Definition at line 94 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 94 of file CCalEcal.hh
Referenced by getSuppMat(), and readFile().
G4double CCalEcal::thetaX private
Definition at line 83 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalEcal.hh
Referenced by getThetaX(), and readFile().
G4double CCalEcal::thetaY private
Definition at line 83 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalEcal.hh
Referenced by getThetaY(), and readFile().
G4double CCalEcal::thetaZ private
Definition at line 83 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalEcal.hh
Referenced by getThetaZ(), and readFile().
G4double CCalEcal::widBox private
Definition at line 81 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 81 of file CCalEcal.hh
Referenced by getWidBox(), and readFile().
G4double CCalEcal::xpos private
Definition at line 82 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 82 of file CCalEcal.hh
Referenced by getXpos(), and readFile().
G4double CCalEcal::ypos private
Definition at line 82 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 82 of file CCalEcal.hh
Referenced by getYpos(), and readFile().
G4double CCalEcal::zpos private
Definition at line 82 of file CCalEcal.hh.
View newest version in sPHENIX GitHub at line 82 of file CCalEcal.hh
Referenced by getZpos(), and readFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalEcal.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalEcal.cc