ECCE @ EIC Software: CexmcParticleGunMessenger Class Reference
CexmcParticleGunMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcParticleGunMessenger.hh>
Public Member Functions
CexmcParticleGunMessenger (CexmcParticleGun *particleGun)
~CexmcParticleGunMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CexmcParticleGun * particleGun
G4UIcmdWithAString * setParticle
G4UIcmdWith3VectorAndUnit * setOrigPosition
G4UIcmdWith3Vector * setOrigDirection
G4UIcmdWithADoubleAndUnit * setOrigMomentumAmp
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 57 of file CexmcParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file CexmcParticleGunMessenger.hh
Constructor & Destructor Documentation
CexmcParticleGunMessenger::CexmcParticleGunMessenger (CexmcParticleGun * particleGun) explicit
Definition at line 57 of file CexmcParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 57 of file CexmcParticleGunMessenger.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, CexmcMessenger::gunDirName, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcommand::SetGuidance(), setOrigDirection, setOrigMomentumAmp, setOrigPosition, G4UIcmdWithAString::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), setParticle, G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), and G4UIcmdWith3VectorAndUnit::SetUnitCandidates().
CexmcParticleGunMessenger::~CexmcParticleGunMessenger ()
Definition at line 101 of file CexmcParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 101 of file CexmcParticleGunMessenger.cc
References setOrigDirection, setOrigMomentumAmp, setOrigPosition, and setParticle.
Member Function Documentation
void CexmcParticleGunMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 110 of file CexmcParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 110 of file CexmcParticleGunMessenger.cc
References CexmcRunManager::BeamParticleChangeHook(), CexmcWeirdException, G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4ParticleTable::GetParticleTable(), G4RunManager::GetRunManager(), particleGun, CexmcParticleGun::SetBeamParticle(), setOrigDirection, CexmcParticleGun::SetOrigDirection(), setOrigMomentumAmp, CexmcParticleGun::SetOrigMomentumAmp(), setOrigPosition, CexmcParticleGun::SetOrigPosition(), and setParticle.
Member Data Documentation
CexmcParticleGun* CexmcParticleGunMessenger::particleGun private
Definition at line 68 of file CexmcParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcParticleGunMessenger.hh
Referenced by SetNewValue().
G4UIcmdWith3Vector* CexmcParticleGunMessenger::setOrigDirection private
Definition at line 74 of file CexmcParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file CexmcParticleGunMessenger.hh
Referenced by CexmcParticleGunMessenger(), SetNewValue(), and ~CexmcParticleGunMessenger().
G4UIcmdWithADoubleAndUnit* CexmcParticleGunMessenger::setOrigMomentumAmp private
Definition at line 76 of file CexmcParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcParticleGunMessenger.hh
Referenced by CexmcParticleGunMessenger(), SetNewValue(), and ~CexmcParticleGunMessenger().
G4UIcmdWith3VectorAndUnit* CexmcParticleGunMessenger::setOrigPosition private
Definition at line 72 of file CexmcParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcParticleGunMessenger.hh
Referenced by CexmcParticleGunMessenger(), SetNewValue(), and ~CexmcParticleGunMessenger().
G4UIcmdWithAString* CexmcParticleGunMessenger::setParticle private
Definition at line 70 of file CexmcParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file CexmcParticleGunMessenger.hh
Referenced by CexmcParticleGunMessenger(), SetNewValue(), and ~CexmcParticleGunMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcParticleGunMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcParticleGunMessenger.cc