ECCE @ EIC Software: G4TrackingManager Class Reference
G4TrackingManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4TrackingManager.hh>
Public Member Functions
G4TrackingManager ()
~G4TrackingManager ()
G4Track * GetTrack () const
G4int GetStoreTrajectory () const
void SetStoreTrajectory (G4int value)
G4SteppingManager * GetSteppingManager () const
G4UserTrackingAction * GetUserTrackingAction () const
G4VTrajectory * GimmeTrajectory () const
void SetTrajectory (G4VTrajectory *aTrajectory)
G4TrackVector * GimmeSecondaries () const
void SetUserAction (G4UserTrackingAction *apAction)
void SetUserAction (G4UserSteppingAction *apAction)
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ProcessOneTrack (G4Track *apValueG4Track)
void EventAborted ()
void SetUserTrackInformation (G4VUserTrackInformation *aValue)
Private Member Functions
void TrackBanner ()
Private Attributes
G4Track * fpTrack
G4SteppingManager * fpSteppingManager
G4UserTrackingAction * fpUserTrackingAction
G4VTrajectory * fpTrajectory
G4int StoreTrajectory
G4int verboseLevel
G4TrackingMessenger * messenger
G4bool EventIsAborted
Detailed Description
Definition at line 68 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrackingManager.hh
Constructor & Destructor Documentation
G4TrackingManager::G4TrackingManager ()
Definition at line 47 of file G4TrackingManager.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TrackingManager.cc
References fpSteppingManager, and messenger.
G4TrackingManager::~G4TrackingManager ()
Definition at line 57 of file G4TrackingManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4TrackingManager.cc
References fpSteppingManager, fpUserTrackingAction, and messenger.
Member Function Documentation
void G4TrackingManager::EventAborted ()
Definition at line 163 of file G4TrackingManager.cc.
View newest version in sPHENIX GitHub at line 163 of file G4TrackingManager.cc
References EventIsAborted, fKillTrackAndSecondaries, fpTrack, and G4Track::SetTrackStatus().
Referenced by G4EventManager::AbortCurrentEvent().
G4SteppingManager * G4TrackingManager::GetSteppingManager () const inline
Definition at line 168 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 168 of file G4TrackingManager.hh
References fpSteppingManager.
Referenced by G4ExceptionHandler::DumpTrackInfo(), G4ErrorPropagator::G4ErrorPropagator(), G4TrackingMessenger::G4TrackingMessenger(), G4ErrorPropagatorManager::SetSteppingManagerVerboseLevel(), and G4ErrorPropagatorManager::StartNavigator().
G4int G4TrackingManager::GetStoreTrajectory () const inline
Definition at line 160 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 160 of file G4TrackingManager.hh
References StoreTrajectory.
Referenced by G4VisManager::Disable(), export_G4TrackingManager(), G4TrackingMessenger::GetCurrentValue(), and ITTrackingInteractivity::Initialize().
G4Track * G4TrackingManager::GetTrack () const inline
Definition at line 156 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 156 of file G4TrackingManager.hh
References fpTrack.
G4UserTrackingAction * G4TrackingManager::GetUserTrackingAction () const inline
Definition at line 172 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 172 of file G4TrackingManager.hh
References fpUserTrackingAction.
G4int G4TrackingManager::GetVerboseLevel () const inline
Definition at line 204 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 204 of file G4TrackingManager.hh
References verboseLevel.
Referenced by export_G4TrackingManager(), G4TrackingMessenger::GetCurrentValue(), ITTrackingInteractivity::Initialize(), and G4ErrorPropagatorManager::SetSteppingManagerVerboseLevel().
G4TrackVector * G4TrackingManager::GimmeSecondaries () const inline
Definition at line 180 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 180 of file G4TrackingManager.hh
References fpSteppingManager, and G4SteppingManager::GetfSecondary().
Referenced by G4EventManager::DoProcessing(), PHG4TruthTrackingAction::PostUserTrackingAction(), RE01TrackingAction::PostUserTrackingAction(), MCTruthTrackingAction::PostUserTrackingAction(), and ProcessOneTrack().
G4VTrajectory * G4TrackingManager::GimmeTrajectory () const inline
Definition at line 176 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 176 of file G4TrackingManager.hh
References fpTrajectory.
Referenced by G4EventManager::DoProcessing(), and LXeTrackingAction::PostUserTrackingAction().
void G4TrackingManager::ProcessOneTrack (G4Track * apValueG4Track)
Definition at line 66 of file G4TrackingManager.cc.
View newest version in sPHENIX GitHub at line 66 of file G4TrackingManager.cc
References G4ProcessManager::EndTracking(), EventIsAborted, fAlive, fKillTrackAndSecondaries, fpSteppingManager, fpTrack, fpTrajectory, fpUserTrackingAction, fStopButAlive, G4Track::GetDefinition(), G4ParticleDefinition::GetProcessManager(), G4SteppingManager::GetProcessNumber(), G4VSteppingVerbose::GetSilent(), G4SteppingManager::GetStep(), G4Track::GetTrackStatus(), GimmeSecondaries(), G4Track::IncrementCurrentStepNumber(), G4UserTrackingAction::PostUserTrackingAction(), G4UserTrackingAction::PreUserTrackingAction(), G4SteppingManager::SetInitialStep(), G4Track::SetStep(), G4Track::SetTrackStatus(), G4VTrajectory::ShowTrajectory(), G4ProcessManager::StartTracking(), G4SteppingManager::Stepping(), StoreTrajectory, TrackBanner(), and verboseLevel.
Referenced by G4EventManager::DoProcessing().
void G4TrackingManager::SetStoreTrajectory (G4int value) inline
Definition at line 164 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 164 of file G4TrackingManager.hh
References StoreTrajectory.
Referenced by export_G4TrackingManager(), ExN04TrackingAction::PreUserTrackingAction(), RE01TrackingAction::PreUserTrackingAction(), RE05TrackingAction::PreUserTrackingAction(), RE04TrackingAction::PreUserTrackingAction(), CML2TrackingAction::PreUserTrackingAction(), and G4TrackingMessenger::SetNewValue().
void G4TrackingManager::SetTrajectory (G4VTrajectory * aTrajectory)
Definition at line 152 of file G4TrackingManager.cc.
View newest version in sPHENIX GitHub at line 152 of file G4TrackingManager.cc
References FatalException, fpTrajectory, and G4Exception().
Referenced by RE01TrackingAction::PreUserTrackingAction(), LXeTrackingAction::PreUserTrackingAction(), WLSTrackingAction::PreUserTrackingAction(), RE04TrackingAction::PreUserTrackingAction(), and G4RTTrackingAction::PreUserTrackingAction().
void G4TrackingManager::SetUserAction (G4UserTrackingAction * apAction) inline
Definition at line 184 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 184 of file G4TrackingManager.hh
References fpUserTrackingAction, and G4UserTrackingAction::SetTrackingManagerPointer().
Referenced by G4EventManager::SetUserAction().
void G4TrackingManager::SetUserAction (G4UserSteppingAction * apAction) inline
Definition at line 191 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 191 of file G4TrackingManager.hh
References fpSteppingManager, G4UserSteppingAction::SetSteppingManagerPointer(), and G4SteppingManager::SetUserAction().
void G4TrackingManager::SetUserTrackInformation (G4VUserTrackInformation * aValue) inline
Definition at line 208 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 208 of file G4TrackingManager.hh
References fpTrack, and G4Track::SetUserInformation().
Referenced by export_G4TrackingManager(), F04TrackingAction::PreUserTrackingAction(), LXeTrackingAction::PreUserTrackingAction(), WLSTrackingAction::PreUserTrackingAction(), and MCTruthTrackingAction::PreUserTrackingAction().
void G4TrackingManager::SetVerboseLevel (G4int vLevel) inline
Definition at line 198 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 198 of file G4TrackingManager.hh
References fpSteppingManager, and verboseLevel.
Referenced by export_G4TrackingManager(), RE06SteppingVerbose::InitializeTimers(), and G4TrackingMessenger::SetNewValue().
void G4TrackingManager::TrackBanner () private
Definition at line 171 of file G4TrackingManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4TrackingManager.cc
References fpTrack, G4cout, G4endl, G4Track::GetDefinition(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), and G4Track::GetTrackID().
Referenced by ProcessOneTrack().
Member Data Documentation
G4bool G4TrackingManager::EventIsAborted private
Definition at line 143 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 143 of file G4TrackingManager.hh
Referenced by EventAborted(), and ProcessOneTrack().
G4SteppingManager* G4TrackingManager::fpSteppingManager private
Definition at line 137 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4TrackingManager.hh
Referenced by G4TrackingManager(), GetSteppingManager(), GimmeSecondaries(), ProcessOneTrack(), SetUserAction(), SetVerboseLevel(), and ~G4TrackingManager().
G4Track* G4TrackingManager::fpTrack private
Definition at line 136 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 136 of file G4TrackingManager.hh
Referenced by EventAborted(), GetTrack(), ProcessOneTrack(), SetUserTrackInformation(), and TrackBanner().
G4VTrajectory* G4TrackingManager::fpTrajectory private
Definition at line 139 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 139 of file G4TrackingManager.hh
Referenced by GimmeTrajectory(), ProcessOneTrack(), and SetTrajectory().
G4UserTrackingAction* G4TrackingManager::fpUserTrackingAction private
Definition at line 138 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 138 of file G4TrackingManager.hh
Referenced by GetUserTrackingAction(), ProcessOneTrack(), SetUserAction(), and ~G4TrackingManager().
G4TrackingMessenger* G4TrackingManager::messenger private
Definition at line 142 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 142 of file G4TrackingManager.hh
Referenced by G4TrackingManager(), and ~G4TrackingManager().
G4int G4TrackingManager::StoreTrajectory private
Definition at line 140 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 140 of file G4TrackingManager.hh
Referenced by GetStoreTrajectory(), ProcessOneTrack(), and SetStoreTrajectory().
G4int G4TrackingManager::verboseLevel private
Definition at line 141 of file G4TrackingManager.hh.
View newest version in sPHENIX GitHub at line 141 of file G4TrackingManager.hh
Referenced by GetVerboseLevel(), ProcessOneTrack(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4TrackingManager.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4TrackingManager.cc