ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/hijing1_383/hipyset1.35.f File Reference
hipyset1.35.f File Reference
Functions/Subroutines
subroutine lu1ent (IP, KF, PE, THE, PHI)
subroutine lu2ent (IP, KF1, KF2, PECM)
subroutine lu3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
subroutine lu4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
subroutine lujoin (NJOIN, IJOIN)
subroutine lugive (CHIN)
subroutine luexec
subroutine luprep (IP)
subroutine lustrf (IP)
subroutine luindf (IP)
subroutine ludecy (IP)
subroutine lukfdi (KFL1, KFL2, KFL3, KF)
subroutine luptdi (KFL, PX, PY)
subroutine luzdis (KFL1, KFL2, PR, Z)
subroutine lushow (IP1, IP2, QMAX)
subroutine luboei (NSAV)
function ulmass (KF)
subroutine luname (KF, CHAU)
function luchge (KF)
function lucomp (KF)
subroutine luerrm (MERR, CHMESS)
function ulalps (Q2)
function ulangl (X, Y)
function rlu (IDUM)
subroutine rluget (LFN, MOVE)
subroutine rluset (LFN, MOVE)
subroutine lurobo (THE, PHI, BEX, BEY, BEZ)
subroutine hirobo (THE, PHI, BEX, BEY, BEZ)
subroutine luedit (MEDIT)
subroutine lulist (MLIST)
subroutine luupda (MUPDA, LFN)
function klu (I, J)
function plu (I, J)
subroutine lusphe (SPH, APL)
subroutine luthru (THR, OBL)
subroutine luclus (NJET)
subroutine lucell (NJET)
subroutine lujmas (PMH, PML)
subroutine lufowo (H10, H20, H30, H40)
subroutine lutabu (MTABU)
subroutine lueevt (KFL, ECM)
subroutine luxtot (KFL, ECM, XTOT)
subroutine luradk (ECM, MK, PAK, THEK, PHIK, ALPK)
subroutine luxkfl (KFL, ECM, ECMC, KFLC)
subroutine luxjet (ECM, NJET, CUT)
subroutine lux3jt (NJET, CUT, KFL, ECM, X1, X2)
subroutine lux4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
subroutine luxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
subroutine luonia (KFL, ECM)
subroutine luhepc (MCONV)
subroutine lutest (MTEST)
subroutine pyinit (FRAME, BEAM, TARGET, WIN)
subroutine pythia
subroutine pystat (MSTAT)
subroutine pyinki (CHFRAM, CHBEAM, CHTARG, WIN)
subroutine pyinre
subroutine pyxtot
subroutine pymaxi
subroutine pyovly (MOVLY)
subroutine pyrand
subroutine pyscat
subroutine pysspa (IPU1, IPU2)
subroutine pymult (MMUL)
subroutine pyremn (IPU1, IPU2)
subroutine pyresd
subroutine pydiff
subroutine pyfram (IFRAME)
subroutine pywidt (KFLR, RMAS, WDTP, WDTE)
subroutine pyklim (ILIM)
subroutine pykmap (IVAR, MVAR, VVAR)
subroutine pysigh (NCHN, SIGS)
subroutine pystfu (KF, X, Q2, XPQ, JBT)
subroutine pyspli (KF, KFLIN, KFLCH, KFLSP)
function pygamm (X)
function pyw1au (EPS, IREIM)
function pyw2au (EPS, IREIM)
function pyi3au (BE, EPS, IREIM)
function pyspen (XREIN, XIMIN, IREIM)
subroutine pytest (MTEST)
subroutine pykcut (MCUT)
subroutine pystfe (KF, X, Q2, XPQ)
Function/Subroutine Documentation
subroutine hirobo (THE, PHI, BEX, BEY, BEZ)
Definition at line 5414 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5414 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), e, imax, k, luerrm(), n, phi, c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), and v.
function klu (I, J)
Definition at line 6195 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 6195 of file hipyset1.35.f
References common(), k, klu(), luchge(), lucomp(), max, G4Abla::mod(), n, and v.
subroutine lu1ent (IP, KF, PE, THE, PHI)
Definition at line 16 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 16 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), k, lucomp(), luerrm(), luexec(), lulist(), max, n, phi, c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulmass(), and v.
subroutine lu2ent (IP, KF1, KF2, PECM)
Definition at line 64 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 64 of file hipyset1.35.f
References common(), k, lucomp(), luerrm(), luexec(), lulist(), max, n, c2_factory< float_type >::sqrt(), ulmass(), and v.
subroutine lu3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
Definition at line 146 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 146 of file hipyset1.35.f
References common(), k, lucomp(), luerrm(), luexec(), lulist(), max, min, n, c2_factory< float_type >::sqrt(), ulmass(), v, x1, and x3.
subroutine lu4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
Definition at line 261 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 261 of file hipyset1.35.f
References common(), int(), k, lucomp(), luerrm(), luexec(), lulist(), max, min, n, rlu(), c2_factory< float_type >::sqrt(), ulmass(), v, x1, x2, and x4.
subroutine luboei (NSAV)
Definition at line 4537 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 4537 of file hipyset1.35.f
References common(), c2_factory< float_type >::exp(), fac, ha, k, le, luerrm(), max, min, n, G4Abla::nint(), c2_factory< float_type >::sqrt(), ulmass(), and v.
subroutine lucell (NJET)
Definition at line 6981 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 6981 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), e, int(), k, Acts::Logger::log(), luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), phi, pt, rlu(), sign(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulangl(), and v.
function luchge (KF)
Definition at line 4911 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 4911 of file hipyset1.35.f
References common(), luchge(), lucomp(), and G4Abla::mod().
subroutine luclus (NJET)
Definition at line 6666 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 6666 of file hipyset1.35.f
References common(), imax, k, luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), ps, r2, c2_factory< float_type >::sqrt(), and v.
function lucomp (KF)
Definition at line 4944 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 4944 of file hipyset1.35.f
References common(), lucomp(), and G4Abla::mod().
subroutine ludecy (IP)
Definition at line 2560 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 2560 of file hipyset1.35.f
References a, b, c, common(), c2_factory< float_type >::cos(), e, e4, e5, four, gauss, ha, hh, int(), Acts::FiniteStateMachine< Derived, States >::is(), k, Acts::Logger::log(), lucomp(), luerrm(), lukfdi(), max, min, G4Abla::mod(), n, nm, HiMain1::np(), phi, ps, rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), c2_factory< float_type >::tan(), ulmass(), and v.
subroutine luedit (MEDIT)
Definition at line 5489 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5489 of file hipyset1.35.f
References common(), FW::HepMC3Particle::id(), imax, Acts::FiniteStateMachine< Derived, States >::is(), k, luchge(), lucomp(), luerrm(), max, G4Abla::mod(), n, ns, sign(), c2_factory< float_type >::sqrt(), ulangl(), and v.
subroutine lueevt (KFL, ECM)
Definition at line 8084 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8084 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), k, lu1ent(), lu2ent(), lu3ent(), lu4ent(), luerrm(), luexec(), lulist(), luprep(), luradk(), lushow(), lux3jt(), lux4jt(), luxdif(), luxjet(), luxkfl(), luxtot(), max, min, n, phi, c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), v, x1, x2, x3, and x4.
subroutine luerrm (MERR, character, dimension(*) CHMESS)
Definition at line 5048 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5048 of file hipyset1.35.f
References a, common(), k, lulist(), n, PHTimer::stop(), v, and x.
subroutine luexec ()
Definition at line 726 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 726 of file hipyset1.35.f
References common(), k, luboei(), luchge(), lucomp(), ludecy(), luerrm(), luindf(), lulist(), luprep(), lushow(), lustrf(), max, min, G4Abla::mod(), n, ps, c2_factory< float_type >::sqrt(), and v.
subroutine lufowo (H10, H20, H30, H40)
Definition at line 7316 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 7316 of file hipyset1.35.f
References common(), h10, h20, k, luchge(), lucomp(), luerrm(), n, HiMain1::np(), c2_factory< float_type >::sqrt(), and v.
subroutine lugive (character, dimension(*) CHIN)
Definition at line 477 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 477 of file hipyset1.35.f
References common(), k, lucomp(), luerrm(), lulist(), n, v, and x.
subroutine luhepc (MCONV)
Definition at line 9336 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 9336 of file hipyset1.35.f
References common(), k, lucomp(), luerrm(), min, G4Abla::mod(), n, and v.
subroutine luindf (IP)
Definition at line 2147 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 2147 of file hipyset1.35.f
References common(), e, int(), k, lucomp(), luerrm(), lukfdi(), luptdi(), luzdis(), max, min, G4Abla::mod(), n, G4StokesVector::p2(), phi, CLHEP::HepEulerAngles::psi(), rlu(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), v, w, and z.
subroutine lujmas (PMH, PML)
Definition at line 7164 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 7164 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), Acts::FiniteStateMachine< Derived, States >::is(), k, luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), ps, smax, c2_factory< float_type >::sqrt(), sr, and v.
subroutine lujoin (NJOIN, dimension(*) IJOIN)
Definition at line 424 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 424 of file hipyset1.35.f
References common(), in, int(), k, lucomp(), luerrm(), n, rlu(), and v.
subroutine lukfdi (KFL1, KFL2, KFL3, KF)
Definition at line 3250 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 3250 of file hipyset1.35.f
References common(), int(), lucomp(), luerrm(), max, min, G4Abla::mod(), rlu(), and c2_factory< float_type >::sqrt().
subroutine lulist (MLIST)
Definition at line 5693 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5693 of file hipyset1.35.f
References common(), imax, k, lucomp(), luname(), max, min, G4Abla::mod(), n, plu(), ps, ulmass(), v, and x.
subroutine luname (KF, character CHAU)
Definition at line 4770 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 4770 of file hipyset1.35.f
References common(), luchge(), lucomp(), and G4Abla::mod().
subroutine luonia (KFL, ECM)
Definition at line 9183 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 9183 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), k, lu1ent(), lu2ent(), lu3ent(), luerrm(), luexec(), lulist(), luprep(), lushow(), max, n, phi, rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulalps(), v, x1, x2, and x3.
subroutine luprep (IP)
Definition at line 844 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 844 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), ha, int(), k, lucomp(), luerrm(), lukfdi(), max, G4Abla::mod(), n, HiMain1::np(), ns, phi, rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulmass(), and v.
subroutine luptdi (KFL, PX, PY)
Definition at line 3573 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 3573 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), e, Acts::Logger::log(), max, phi, pt, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), rlu(), c2_factory< float_type >::sin(), and c2_factory< float_type >::sqrt().
subroutine luradk (ECM, MK, PAK, THEK, PHIK, ALPK)
Definition at line 8388 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8388 of file hipyset1.35.f
References common(), e, Acts::Logger::log(), max, min, rlu(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), and xx.
subroutine lurobo (THE, PHI, BEX, BEY, BEZ)
Definition at line 5316 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5316 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), e, imax, k, luerrm(), n, phi, c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), and v.
subroutine lushow (IP1, IP2, QMAX)
Definition at line 3700 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 3700 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), e, c2_factory< float_type >::exp(), if(), int(), k, Acts::Logger::log(), luerrm(), max, min, G4Abla::mod(), n, ns, phi, ps, pt, rlu(), rmax(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), v, x1, x2, x3, and z.
subroutine lusphe (SPH, APL)
Definition at line 6376 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 6376 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), e, int(), k, luchge(), lucomp(), luerrm(), max, min, n, HiMain1::np(), ps, rlu(), smax, c2_factory< float_type >::sqrt(), sr, and v.
subroutine lustrf (IP)
Definition at line 1175 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 1175 of file hipyset1.35.f
References common(), e, c2_factory< float_type >::exp(), fa(), fb(), fd, four, in, int(), Acts::FiniteStateMachine< Derived, States >::is(), k, Acts::Logger::log(), lucomp(), luerrm(), lukfdi(), luptdi(), luzdis(), max, min, G4Abla::mod(), n, HiMain1::np(), ns, HijJet4::pdr(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), pyp(), rlu(), sign(), c2_factory< float_type >::sqrt(), ulmass(), v, and z.
subroutine lutabu (MTABU)
Definition at line 7394 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 7394 of file hipyset1.35.f
References common(), e, f4, fac, int(), k, Acts::Logger::log(), luchge(), lucomp(), luerrm(), luname(), max, min, G4Abla::mod(), n, HiMain1::np(), phi, sign(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), v, and x.
subroutine lutest (MTEST)
Definition at line 9468 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 9468 of file hipyset1.35.f
References common(), int(), k, lu1ent(), lu2ent(), lu3ent(), lu4ent(), lucomp(), lueevt(), luexec(), lulist(), luonia(), lutabu(), max, G4Abla::mod(), n, phi, plu(), rlu(), PHTimer::stop(), theta(), ulmass(), v, and x.
subroutine luthru (THR, OBL)
Definition at line 6504 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 6504 of file hipyset1.35.f
References common(), e, int(), k, luchge(), lucomp(), luerrm(), min, n, HiMain1::np(), phi, ps, rlu(), sign(), c2_factory< float_type >::sqrt(), ulangl(), and v.
subroutine luupda (MUPDA, LFN)
Definition at line 5949 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5949 of file hipyset1.35.f
References common(), Acts::HierarchicalGeometryContainer< value_t >::end(), luchge(), lucomp(), luerrm(), lulist(), max, min, ulmass(), and x.
subroutine lux3jt (NJET, CUT, KFL, ECM, X1, X2)
Definition at line 8696 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8696 of file hipyset1.35.f
References common(), c2_factory< float_type >::exp(), Acts::Logger::log(), max, min, G4Abla::mod(), rlu(), sign(), c2_factory< float_type >::sqrt(), ulmass(), x, x1, x2, x3, HepGeom::Transform3D::zx(), and HepGeom::Transform3D::zy().
subroutine lux4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
Definition at line 8849 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8849 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), cp, c2_factory< float_type >::exp(), FW::HepMC3Particle::id(), int(), it, Acts::Logger::log(), max, min, rlu(), c2_factory< float_type >::sqrt(), ulmass(), x1, x2, and x4.
subroutine luxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
Definition at line 9057 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 9057 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), k, n, phi, rlu(), sign(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulmass(), v, x1, and x2.
subroutine luxjet (ECM, NJET, CUT)
Definition at line 8524 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8524 of file hipyset1.35.f
References common(), c2_factory< float_type >::exp(), Acts::Logger::log(), luerrm(), max, min, rlu(), c2_factory< float_type >::sqrt(), and ulalps().
subroutine luxkfl (KFL, ECM, ECMC, KFLC)
Definition at line 8458 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8458 of file hipyset1.35.f
References common(), int(), luerrm(), max, G4Abla::mod(), rlu(), sign(), c2_factory< float_type >::sqrt(), and ulmass().
subroutine luxtot (KFL, ECM, XTOT)
Definition at line 8232 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 8232 of file hipyset1.35.f
References common(), c2_factory< float_type >::exp(), Acts::Logger::log(), max, min, G4Abla::mod(), sign(), c2_factory< float_type >::sqrt(), ulalps(), and ulmass().
subroutine luzdis (KFL1, KFL2, PR, Z)
Definition at line 3593 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 3593 of file hipyset1.35.f
References common(), c2_factory< float_type >::exp(), fa(), fb(), Acts::Logger::log(), max, min, G4Abla::mod(), rlu(), c2_factory< float_type >::sqrt(), and z.
function plu (I, J)
Definition at line 6305 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 6305 of file hipyset1.35.f
References common(), e, k, Acts::Logger::log(), luchge(), max, min, n, plu(), sign(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), and v.
subroutine pydiff ()
Definition at line 14947 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 14947 of file hipyset1.35.f
References common(), k, G4Abla::mod(), n, pyspli(), CLHEP::HepLorentzVector::pz(), rlu(), c2_factory< float_type >::sqrt(), ulmass(), and v.
subroutine pyfram (IFRAME)
Definition at line 15087 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 15087 of file hipyset1.35.f
References common(), lurobo(), and x.
function pygamm (X)
Definition at line 18811 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18811 of file hipyset1.35.f
References b, dx, int(), pygamm(), and x.
function pyi3au (BE, EPS, IREIM)
Definition at line 18898 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18898 of file hipyset1.35.f
References common(), eps, Acts::Logger::log(), phi, pyi3au(), pyspen(), r, and c2_factory< float_type >::sqrt().
subroutine pyinit (character*(*) FRAME, character*(*) BEAM, character*(*) TARGET, WIN)
Definition at line 10075 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 10075 of file hipyset1.35.f
References common(), lulist(), min, G4Abla::mod(), pyinki(), pyinre(), pymaxi(), pymult(), pyovly(), pyxtot(), PHTimer::stop(), and x.
subroutine pyinki (character CHFRAM, character CHBEAM, character CHTARG, WIN)
Definition at line 10823 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 10823 of file hipyset1.35.f
References a, common(), k, lurobo(), n, c2_factory< float_type >::sqrt(), PHTimer::stop(), ulangl(), ulmass(), v, and x.
subroutine pyinre ()
Definition at line 11007 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 11007 of file hipyset1.35.f
References common(), min, pywidt(), and ulalps().
subroutine pykcut (MCUT)
Definition at line 19485 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 19485 of file hipyset1.35.f
References common().
subroutine pyklim (ILIM)
Definition at line 15734 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 15734 of file hipyset1.35.f
References common(), e, c2_factory< float_type >::exp(), Acts::Logger::log(), max, min, rm3, sign(), c2_factory< float_type >::sqrt(), G4Abla::tau(), x1, x2, y3, and y4.
subroutine pykmap (IVAR, MVAR, VVAR)
Definition at line 16003 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 16003 of file hipyset1.35.f
References common(), c2_factory< float_type >::exp(), Acts::Logger::log(), max, min, c2_factory< float_type >::sqrt(), c2_factory< float_type >::tan(), and G4Abla::tau().
subroutine pymaxi ()
Definition at line 11279 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 11279 of file hipyset1.35.f
References common(), e, c2_factory< float_type >::exp(), imax, Acts::Logger::log(), max, min, G4Abla::mod(), nmax, pyklim(), pykmap(), pysigh(), c2_factory< float_type >::sqrt(), PHTimer::stop(), G4Abla::tau(), and x.
subroutine pymult (MMUL)
Definition at line 13656 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 13656 of file hipyset1.35.f
References b, common(), c2_factory< float_type >::cos(), e, c2_factory< float_type >::exp(), int(), k, Acts::Logger::log(), lucomp(), luerrm(), max, min, G4Abla::mod(), n, nmax, phi, pt, pyklim(), pykmap(), pysigh(), rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), c2_factory< float_type >::tan(), G4Abla::tau(), v, and x.
subroutine pyovly (MOVLY)
Definition at line 11763 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 11763 of file hipyset1.35.f
References common(), e, c2_factory< float_type >::exp(), imax, max, min, rlu(), and x.
Referenced by pyinit(), and pythia().
subroutine pyrand ()
Definition at line 11843 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 11843 of file hipyset1.35.f
References b, c, common(), e, c2_factory< float_type >::exp(), int(), Acts::FiniteStateMachine< Derived, States >::is(), Acts::Logger::log(), max, min, G4Abla::mod(), pykcut(), pyklim(), pykmap(), pymult(), pysigh(), pyspli(), rlu(), c2_factory< float_type >::sqrt(), PHTimer::stop(), ulmass(), and x.
subroutine pyremn (IPU1, IPU2)
Definition at line 14116 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 14116 of file hipyset1.35.f
References common(), c2_factory< float_type >::cos(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), Acts::FiniteStateMachine< Derived, States >::is(), k, Acts::Logger::log(), lucomp(), luptdi(), max, min, G4Abla::mod(), n, HiStrng::nfp(), HiStrng::nft(), nmax, ns, phi, pt, pt2, pyspli(), CLHEP::HepLorentzVector::pz(), rlu(), sign(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), and v.
subroutine pyresd ()
Definition at line 14451 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 14451 of file hipyset1.35.f
References common(), e, ei(), ha, FW::HepMC3Particle::id(), imax, int(), k, lu2ent(), luchge(), lushow(), G4Abla::mod(), n, HiMain1::np(), phi, pywidt(), rlu(), sign(), c2_factory< float_type >::sqrt(), v, and zz.
subroutine pyscat ()
Definition at line 12224 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 12224 of file hipyset1.35.f
References c1, c2, common(), c2_factory< float_type >::cos(), e, int(), k, luchge(), max, min, G4Abla::mod(), n, phi, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), pywidt(), CLHEP::HepLorentzVector::pz(), rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulangl(), ulmass(), v, z, z1, and z2.
subroutine pysigh (NCHN, SIGS)
Definition at line 16169 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 16169 of file hipyset1.35.f
References dfe::Variable::as(), common(), e, ei(), eps, c2_factory< float_type >::exp(), h1, h2, h3, Acts::Logger::log(), max, min, G4Abla::mod(), pyi3au(), pystfu(), pyw1au(), pyw2au(), pywidt(), rm3, sign(), c2_factory< float_type >::sqrt(), G4Abla::tau(), ulalps(), and x.
function pyspen (XREIN, XIMIN, IREIM)
Definition at line 18943 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18943 of file hipyset1.35.f
References b, common(), c2_factory< float_type >::cos(), e, Acts::Logger::log(), pyspen(), sign(), c2_factory< float_type >::sin(), and c2_factory< float_type >::sqrt().
subroutine pyspli (KF, KFLIN, KFLCH, KFLSP)
Definition at line 18727 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18727 of file hipyset1.35.f
References lukfdi(), G4Abla::mod(), and rlu().
subroutine pysspa (IPU1, IPU2)
Definition at line 13259 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 13259 of file hipyset1.35.f
References common(), d, e, c2_factory< float_type >::exp(), Acts::FiniteStateMachine< Derived, States >::is(), it, k, Acts::Logger::log(), luerrm(), lushow(), max, min, G4Abla::mod(), n, ns, pystfu(), rlu(), c2_factory< float_type >::sqrt(), ulalps(), ulangl(), ulmass(), v, x, Fun4AllFileOutStream::xb(), and z.
subroutine pystat (MSTAT)
Definition at line 10602 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 10602 of file hipyset1.35.f
References a, common(), luname(), max, and x.
subroutine pystfe (KF, X, Q2, dimension(-6:6) XPQ)
Definition at line 19503 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 19503 of file hipyset1.35.f
References common(), e, init(), max, min, c2_factory< float_type >::sqrt(), x, and xmin.
Referenced by pystfu().
subroutine pystfu (KF, X, Q2, dimension(-6:6) XPQ, JBT)
Definition at line 18117 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18117 of file hipyset1.35.f
References common(), e, c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), Acts::FiniteStateMachine< Derived, States >::is(), it, Acts::Logger::log(), max, min, pygamm(), pystfe(), c2_factory< float_type >::sqrt(), t, CLHEP::HepBoost::tt(), CLHEP::HepBoost::tx(), x, y, HijCrdn::yp(), and HijCrdn::yt().
Referenced by pysigh(), and pysspa().
subroutine pytest (MTEST)
Definition at line 19029 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 19029 of file hipyset1.35.f
References common(), e, e4, k, lucomp(), lulist(), max, n, plu(), pyinit(), pystat(), pythia(), sign(), c2_factory< float_type >::sqrt(), PHTimer::stop(), ulmass(), v, and x.
subroutine pythia ()
Definition at line 10306 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 10306 of file hipyset1.35.f
References common(), e, fac, Acts::FiniteStateMachine< Derived, States >::is(), k, Acts::Logger::log(), luedit(), luerrm(), luexec(), luprep(), lushow(), max, min, G4Abla::mod(), n, pt, pydiff(), pyfram(), pymult(), pyovly(), pyrand(), pyremn(), pyresd(), pyscat(), pysspa(), sign(), c2_factory< float_type >::sqrt(), ulangl(), and v.
Referenced by hijhrd(), and pytest().
function pyw1au (EPS, IREIM)
Definition at line 18838 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18838 of file hipyset1.35.f
References G4Hype::asinh(), common(), eps, Acts::Logger::log(), c2_factory< float_type >::sqrt(), and x.
Referenced by pysigh().
function pyw2au (EPS, IREIM)
Definition at line 18868 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 18868 of file hipyset1.35.f
References G4Hype::asinh(), common(), eps, Acts::Logger::log(), c2_factory< float_type >::sqrt(), and x.
Referenced by pysigh().
subroutine pywidt (KFLR, RMAS, dimension(0:40) WDTP, dimension(0:40,0:5) WDTE)
Definition at line 15128 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 15128 of file hipyset1.35.f
References dfe::Variable::as(), common(), e, ei(), eps, Acts::Logger::log(), max, G4Abla::mod(), sign(), c2_factory< float_type >::sqrt(), and ulalps().
subroutine pyxtot ()
Definition at line 11176 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 11176 of file hipyset1.35.f
References b, bp, c, common(), c2_factory< float_type >::cos(), e, Acts::Logger::log(), max, min, HepGeom::BasicVector3D< T >::rho(), c2_factory< float_type >::sin(), and c2_factory< float_type >::sqrt().
function rlu (IDUM)
Definition at line 5181 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5181 of file hipyset1.35.f
References common(), k, m, G4Abla::mod(), rlu(), and t.
subroutine rluget (LFN, MOVE)
Definition at line 5250 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5250 of file hipyset1.35.f
References common(), luerrm(), min, and Acts::Polyhedron::move().
subroutine rluset (LFN, MOVE)
Definition at line 5282 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5282 of file hipyset1.35.f
References common(), luerrm(), max, min, and Acts::Polyhedron::move().
function ulalps (Q2)
Definition at line 5098 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5098 of file hipyset1.35.f
References common(), Acts::Logger::log(), max, min, c2_factory< float_type >::sqrt(), and ulalps().
function ulangl (X, Y)
Definition at line 5156 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 5156 of file hipyset1.35.f
References common(), e, r, sign(), c2_factory< float_type >::sqrt(), ulangl(), x, and y.
function ulmass (KF)
Definition at line 4679 of file hipyset1.35.f.
View newest version in sPHENIX GitHub at line 4679 of file hipyset1.35.f
References common(), e, lucomp(), max, G4Abla::mod(), rlu(), c2_factory< float_type >::sqrt(), c2_factory< float_type >::tan(), and ulmass().