ECCE @ EIC Software: G4CascadeFinalStateGenerator Class Reference
G4CascadeFinalStateGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeFinalStateGenerator.hh>
Public Member Functions
G4CascadeFinalStateGenerator ()
virtual ~G4CascadeFinalStateGenerator ()
void Configure (G4InuclElementaryParticle *bullet, G4InuclElementaryParticle *target, const std::vector< G4int > &particle_kinds)
Public Member Functions inherited from G4HadDecayGenerator
G4HadDecayGenerator (Algorithm alg=Kopylov, G4int verbose=0)
G4HadDecayGenerator (G4VHadDecayAlgorithm *alg, G4int verbose=0)
virtual ~G4HadDecayGenerator ()
void SetVerboseLevel (G4int verbose)
const G4String & GetAlgorithmName () const
G4bool Generate (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
G4bool Generate (const G4ParticleDefinition *initialPD, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
G4bool Generate (const G4LorentzVector &initialState, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
Additional Inherited Members
Public Types inherited from G4HadDecayGenerator
enum Algorithm { NONE =0, Kopylov =1, GENBOD =2, NBody =3 }
Protected Member Functions inherited from G4HadDecayGenerator
G4bool GenerateOneBody (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState) const
void ReportInvalidAlgorithm (Algorithm alg) const
void ReportMissingAlgorithm () const
void UseAlgorithm (G4VHadDecayAlgorithm *alg)
Protected Attributes inherited from G4HadDecayGenerator
G4int verboseLevel
G4VHadDecayAlgorithm * theAlgorithm
Detailed Description
Definition at line 45 of file G4CascadeFinalStateGenerator.hh.
View newest version in sPHENIX GitHub at line 45 of file G4CascadeFinalStateGenerator.hh
Constructor & Destructor Documentation
G4CascadeFinalStateGenerator::G4CascadeFinalStateGenerator ()
Definition at line 41 of file G4CascadeFinalStateGenerator.cc.
View newest version in sPHENIX GitHub at line 41 of file G4CascadeFinalStateGenerator.cc
G4CascadeFinalStateGenerator::~G4CascadeFinalStateGenerator () virtual
Definition at line 44 of file G4CascadeFinalStateGenerator.cc.
View newest version in sPHENIX GitHub at line 44 of file G4CascadeFinalStateGenerator.cc
Member Function Documentation
void G4CascadeFinalStateGenerator::Configure (G4InuclElementaryParticle * bullet, G4InuclElementaryParticle * target, const std::vector< G4int > & particle_kinds)
Definition at line 49 of file G4CascadeFinalStateGenerator.cc.
View newest version in sPHENIX GitHub at line 49 of file G4CascadeFinalStateGenerator.cc
References G4CascadeFinalStateAlgorithm::Configure(), G4cout, G4endl, G4HadDecayGenerator::theAlgorithm, and G4HadDecayGenerator::verboseLevel.
Referenced by G4ElementaryParticleCollider::generateSCMfinalState(), and G4LightTargetCollider::SingleNucleonScattering().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeFinalStateGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeFinalStateGenerator.cc