ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/externals/clhep/src/setStdMath.cc File Reference
setStdMath.cc File Reference
#include "CLHEP/Evaluator/Evaluator.h"
#include <cmath>
Namespaces
namespace HepTool
Functions
static double eval_abs (double a)
static double eval_min (double a, double b)
static double eval_max (double a, double b)
static double eval_sqrt (double a)
static double eval_pow (double a, double b)
static double eval_sin (double a)
static double eval_cos (double a)
static double eval_tan (double a)
static double eval_asin (double a)
static double eval_acos (double a)
static double eval_atan (double a)
static double eval_atan2 (double a, double b)
static double eval_sinh (double a)
static double eval_cosh (double a)
static double eval_tanh (double a)
static double eval_exp (double a)
static double eval_log (double a)
static double eval_log10 (double a)
Function Documentation
static double eval_abs (double a) static
Definition at line 8 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 8 of file setStdMath.cc
References a.
Referenced by HepTool::Evaluator::setStdMath().
static double eval_acos (double a) static
Definition at line 17 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 17 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_asin (double a) static
Definition at line 16 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 16 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_atan (double a) static
Definition at line 18 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 18 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_atan2 (double a, double b) static
Definition at line 19 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 19 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_cos (double a) static
Definition at line 14 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 14 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_cosh (double a) static
Definition at line 21 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 21 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_exp (double a) static
Definition at line 23 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 23 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_log (double a) static
Definition at line 24 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 24 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_log10 (double a) static
Definition at line 25 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 25 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_max (double a, double b) static
Definition at line 10 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 10 of file setStdMath.cc
References b.
Referenced by HepTool::Evaluator::setStdMath().
static double eval_min (double a, double b) static
Definition at line 9 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 9 of file setStdMath.cc
References b.
Referenced by HepTool::Evaluator::setStdMath().
static double eval_pow (double a, double b) static
Definition at line 12 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 12 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_sin (double a) static
Definition at line 13 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 13 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_sinh (double a) static
Definition at line 20 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 20 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_sqrt (double a) static
Definition at line 11 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 11 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_tan (double a) static
Definition at line 15 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 15 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().
static double eval_tanh (double a) static
Definition at line 22 of file setStdMath.cc.
View newest version in sPHENIX GitHub at line 22 of file setStdMath.cc
Referenced by HepTool::Evaluator::setStdMath().