ECCE @ EIC Software: G4INCL::CrossSectionsMultiPions Class Reference
G4INCL::CrossSectionsMultiPions Class Reference
Cross sections used in INCL Multipions.
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsMultiPions.hh>
Public Member Functions
CrossSectionsMultiPions ()
virtual G4double elastic (Particle const *const p1, Particle const *const p2)
Elastic particle-particle cross section.
virtual G4double total (Particle const *const p1, Particle const *const p2)
Total (elastic+inelastic) particle-particle cross section.
virtual G4double NDeltaToNN (Particle const *const p1, Particle const *const p2)
Cross section for NDelta->NN.
virtual G4double NNToNDelta (Particle const *const p1, Particle const *const p2)
Cross section for Delta production - NN Channel.
virtual G4double piNToDelta (Particle const *const p1, Particle const *const p2)
Cross section for Delta production - piN Channel.
virtual G4double piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - piN Channel.
virtual G4double NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NN Channel.
virtual G4double calculateNNAngularSlope (G4double energyCM, G4int iso)
Calculate the slope of the NN DDXS.
virtual G4double piNToEtaN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance production - piN Channel.
virtual G4double piNToOmegaN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->OmegaN.
virtual G4double piNToEtaPrimeN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->EtaPrimeN.
virtual G4double etaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
virtual G4double omegaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross section for OmegaN->PiPiN.
virtual G4double etaNToPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - piN Channel.
virtual G4double omegaNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for OmegaN->PiN.
virtual G4double etaPrimeNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for EtaPrimeN->PiN.
virtual G4double NNToNNEta (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production - NN entrance channel.
virtual G4double NNToNNEtaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNEta Channel.
virtual G4double NNToNDeltaEta (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNEta Channel.
virtual G4double NNToNNOmega (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production - NN entrance channel.
virtual G4double NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNEta Channel.
virtual G4double NNToNDeltaOmega (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNEta Channel.
virtual G4double NYelastic (Particle const *const p1, Particle const *const p2)
elastic scattering for Nucleon-Strange Particles cross sections
virtual G4double NKbelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NKelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Nucleon to Stange particles cross sections.
virtual G4double NNToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NNToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Delta to Stange particles cross sections.
virtual G4double NDeltaToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK (Particle const *const p1, Particle const *const p2)
Nucleon-Pion to Stange particles cross sections.
virtual G4double NpiToSK (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSzKz (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSmKp (Particle const *const p1, Particle const *const p2)
virtual G4double p_pizToSzKp (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NLToNS (Particle const *const p1, Particle const *const p2)
Nucleon-Hyperon cross sections.
virtual G4double NSToNL (Particle const *const p1, Particle const *const p2)
virtual G4double NSToNS (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK (Particle const *const p1, Particle const *const p2)
Nucleon-Kaon quasi-elastic and inelastic cross sections.
virtual G4double NKToNKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb (Particle const *const p1, Particle const *const p2)
Nucleon-antiKaon quasi-elastic and inelastic cross sections.
virtual G4double NKbToSpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToLpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToS2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToL2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKbpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb2pi (Particle const *const p1, Particle const *const p2)
Public Member Functions inherited from G4INCL::ICrossSections
ICrossSections ()
virtual ~ICrossSections ()
Protected Member Functions
G4double NNElastic (Particle const *const part1, Particle const *const part2)
Internal implementation of the NN elastic cross section.
G4double NNElasticFixed (const G4double s, const G4int i)
Internal implementation of the NN elastic cross section with fixed isospin.
G4double NNTot (Particle const *const part1, Particle const *const part2)
Internal implementation of the NN total cross section.
G4double NNTotFixed (const G4double s, const G4int i)
Internal implementation of the NN total cross section with fixed isospin.
G4double NNInelasticIso (const G4double ener, const G4int iso)
Internal implementation of the isospin dependent NN reaction cross section.
virtual G4double NNOnePiOrDelta (const G4double ener, const G4int iso, const G4double xsiso)
Cross section for direct 1-pion production + delta production - NN entrance channel.
virtual G4double NNTwoPi (const G4double ener, const G4int iso, const G4double xsiso)
Cross section for direct 2-pion production - NN entrance channel.
virtual G4double NNThreePi (const G4double ener, const G4int iso, const G4double xsiso, const G4double xs1pi, const G4double xs2pi)
Cross section for direct 3-pion production - NN entrance channel.
virtual G4double NNOnePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NN entrance channel.
virtual G4double NNOnePiOrDelta (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NN entrance channel.
virtual G4double NNTwoPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 2-pion production - NN entrance channel.
virtual G4double NNThreePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 3-pion production - NN entrance channel.
virtual G4double NNFourPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 4-pion production - NN entrance channel.
G4double spnPiPlusPHE (const G4double x)
Internal function for pion cross sections.
G4double spnPiMinusPHE (const G4double x)
Internal function for pion cross sections.
G4double piNIne (Particle const *const p1, Particle const *const p2)
G4double piNTot (Particle const *const p1, Particle const *const p2)
G4double piNTopiN (Particle const *const p1, Particle const *const p2)
G4double piPluspIne (Particle const *const p1, Particle const *const p2)
G4double piMinuspIne (Particle const *const p1, Particle const *const p2)
G4double piPluspOnePi (Particle const *const p1, Particle const *const p2)
G4double piMinuspOnePi (Particle const *const p1, Particle const *const p2)
G4double piPluspTwoPi (Particle const *const p1, Particle const *const p2)
G4double piMinuspTwoPi (Particle const *const p1, Particle const *const p2)
virtual G4double piNOnePi (Particle const *const p1, Particle const *const p2)
Cross section for One (more) pion production - piN entrance channel.
virtual G4double piNTwoPi (Particle const *const p1, Particle const *const p2)
Cross section for Two (more) pion production - piN entrance channel.
Protected Attributes
const HornerC7 s11pzHC
Horner coefficients for s11pz.
const HornerC8 s01ppHC
Horner coefficients for s01pp.
const HornerC4 s01pzHC
Horner coefficients for s01pz.
const HornerC4 s11pmHC
Horner coefficients for s11pm.
const HornerC5 s12pmHC
Horner coefficients for s12pm.
const HornerC3 s12ppHC
Horner coefficients for s12pp.
const HornerC4 s12zzHC
Horner coefficients for s12zz.
const HornerC4 s02pzHC
Horner coefficients for s02pz.
const HornerC6 s02pmHC
Horner coefficients for s02pm.
const HornerC4 s12mzHC
Horner coefficients for s12mz.
Static Protected Attributes
static const G4int nMaxPiNN = 4
Maximum number of outgoing pions in NN collisions.
static const G4int nMaxPiPiN = 4
Maximum number of outgoing pions in piN collisions.
static const G4double s11pzOOT = 0.0035761542037692665889
One over threshold for s11pz.
static const G4double s01ppOOT = 0.003421025623481919853
One over threshold for s01pp.
static const G4double s01pzOOT = 0.0035739814152966403123
One over threshold for s01pz.
static const G4double s11pmOOT = 0.0034855350296270480281
One over threshold for s11pm.
static const G4double s12pmOOT = 0.0016672224074691565119
One over threshold for s12pm.
static const G4double s12ppOOT = 0.0016507643038726931312
One over threshold for s12pp.
static const G4double s12zzOOT = 0.0011111111111111111111
One over threshold for s12zz.
static const G4double s02pzOOT = 0.00125
One over threshold for s02pz.
static const G4double s02pmOOT = 0.0016661112962345883443
One over threshold for s02pm.
static const G4double s12mzOOT = 0.0017047391749062392793
One over threshold for s12mz.
Detailed Description
Cross sections used in INCL Multipions.
Definition at line 54 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 54 of file G4INCLCrossSectionsMultiPions.hh
Constructor & Destructor Documentation
G4INCL::CrossSectionsMultiPions::CrossSectionsMultiPions ()
Definition at line 71 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 71 of file G4INCLCrossSectionsMultiPions.cc
Member Function Documentation
G4double G4INCL::CrossSectionsMultiPions::calculateNNAngularSlope (G4double energyCM, G4int iso) virtual
Calculate the slope of the NN DDXS.
Parameters
energyCM energy in the CM frame, in MeV
iso total isospin of the system
Returns
the slope of the angular distribution
Implements G4INCL::ICrossSections.
Definition at line 826 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 826 of file G4INCLCrossSectionsMultiPions.cc
References b, e, readPY::pl, and x.
G4double G4INCL::CrossSectionsMultiPions::elastic (Particle const *const p1, Particle const *const p2) virtual
Elastic particle-particle cross section.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsTruncatedMultiPions, G4INCL::CrossSectionsStrangeness, and G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 807 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 807 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::Particle::isDelta(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isPion(), NNElastic(), piNIne(), piNToDelta(), and piNTot().
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::elastic(), G4INCL::CrossSectionsStrangeness::elastic(), NNTot(), piNOnePi(), piNTwoPi(), and total().
G4double G4INCL::CrossSectionsMultiPions::etaNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance absorption on nucleon - piN Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1248 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1248 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::etaNToPiPiN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1256 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1256 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::etaPrimeNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for EtaPrimeN->PiN.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1278 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1278 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1424 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1424 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1428 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1428 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NDeltaToNLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Delta to Stange particles cross sections.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1416 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1416 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NDeltaToNN (Particle const *const p1, Particle const *const p2) virtual
Cross section for NDelta->NN.
Implements G4INCL::ICrossSections.
Definition at line 749 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 749 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::ParticleTable::effectiveNucleonMass2, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::Particle::getType(), G4INCL::Particle::isDelta(), NNInelasticIso(), NNOnePiOrDelta(), G4INCL::KinematicsUtils::squareTotalEnergyInCM(), x, and y.
Referenced by NNTot(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPionsAndResonances::total(), and total().
G4double G4INCL::CrossSectionsMultiPions::NDeltaToNNKKb (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1433 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1433 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NDeltaToNSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1420 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1420 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbelastic (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1352 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1352 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToL2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1574 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1574 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToLpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1560 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1560 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToNKb (Particle const *const p1, Particle const *const p2) virtual
Nucleon-antiKaon quasi-elastic and inelastic cross sections.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1546 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1546 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToNKb2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1588 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1588 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToNKbpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1581 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1581 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToS2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1567 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1567 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKbToSpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1553 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1553 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKelastic (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1345 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1345 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKToNK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Kaon quasi-elastic and inelastic cross sections.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1525 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1525 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKToNK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1539 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1539 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NKToNKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1532 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1532 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NLToNS (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Hyperon cross sections.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1504 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1504 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNElastic (Particle const *const part1, Particle const *const part2) protected
Internal implementation of the NN elastic cross section.
Definition at line 85 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 85 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), NNElasticFixed(), and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), and NNFourPi().
G4double G4INCL::CrossSectionsMultiPions::NNElasticFixed (const G4double s, const G4int i) protected
Internal implementation of the NN elastic cross section with fixed isospin.
Definition at line 118 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 118 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::effectiveNucleonMass, and G4INCL::KinematicsUtils::momentumInLab().
Referenced by NNElastic(), and NNInelasticIso().
G4double G4INCL::CrossSectionsMultiPions::NNFourPi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 4-pion production - NN entrance channel.
Definition at line 524 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 524 of file G4INCLCrossSectionsMultiPions.cc
References e, NNElastic(), NNOnePiOrDelta(), NNThreePi(), NNTot(), NNTwoPi(), and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPions::NNInelasticIso (const G4double ener, const G4int iso) protected
Internal implementation of the isospin dependent NN reaction cross section.
Definition at line 224 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 224 of file G4INCLCrossSectionsMultiPions.cc
References NNElasticFixed(), and NNTotFixed().
Referenced by NDeltaToNN(), NNOnePi(), NNOnePiOrDelta(), NNThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaOmega(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaxPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaxPi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), and NNTwoPi().
G4double G4INCL::CrossSectionsMultiPions::NNOnePi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 1-pion production - NN entrance channel.
Definition at line 455 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 455 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNInelasticIso(), NNOnePiOrDelta(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta (const G4double ener, const G4int iso, const G4double xsiso) protected virtual
Cross section for direct 1-pion production + delta production - NN entrance channel.
Definition at line 248 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 248 of file G4INCLCrossSectionsMultiPions.cc
References b, e, G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::BystrickyEvaluator< N >::eval(), G4INCL::KinematicsUtils::momentumInLab(), NNTwoPi(), s01ppHC, s01ppOOT, s01pzHC, s01pzOOT, s11pmHC, s11pmOOT, s11pzHC, and s11pzOOT.
Referenced by NDeltaToNN(), NNFourPi(), NNOnePi(), NNOnePiOrDelta(), NNThreePi(), NNToNDelta(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), and NNTwoPi().
G4double G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 1-pion production - NN entrance channel.
Definition at line 469 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 469 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNInelasticIso(), NNOnePiOrDelta(), and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPions::NNThreePi (const G4double ener, const G4int iso, const G4double xsiso, const G4double xs1pi, const G4double xs2pi) protected virtual
Cross section for direct 3-pion production - NN entrance channel.
Definition at line 423 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 423 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::ParticleTable::effectiveNucleonMass, and G4INCL::KinematicsUtils::momentumInLab().
Referenced by NNFourPi(), NNThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), and NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPions::NNThreePi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 3-pion production - NN entrance channel.
Definition at line 502 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 502 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNInelasticIso(), NNOnePiOrDelta(), NNThreePi(), NNTwoPi(), and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPions::NNToMissingStrangeness (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1409 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1409 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNDelta (Particle const *const p1, Particle const *const p2) virtual
Cross section for Delta production - NN Channel.
Implements G4INCL::ICrossSections.
Definition at line 798 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 798 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), and NNOnePiOrDelta().
G4double G4INCL::CrossSectionsMultiPions::NNToNDeltaEta (Particle const *const p1, Particle const *const p2) virtual
Cross section for N-Delta-Eta production - NNEta Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1303 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1303 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNDeltaOmega (Particle const *const p1, Particle const *const p2) virtual
Cross section for N-Delta-Eta production - NNEta Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1328 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1328 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Nucleon to Stange particles cross sections.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1360 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1360 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNLK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1388 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1388 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNLKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1374 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1374 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNEta (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production - NN entrance channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1285 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1285 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNEtaExclu (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production (exclusive) - NN entrance channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1292 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1292 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NNEta Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1299 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1299 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNKKb (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1402 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1402 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNOmega (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production - NN entrance channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1310 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1310 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production (exclusive) - NN entrance channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1317 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1317 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NNEta Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1324 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1324 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1367 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1367 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNSK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1395 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1395 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNToNSKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1381 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1381 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NNTot (Particle const *const part1, Particle const *const part2) protected
Internal implementation of the NN total cross section.
Definition at line 164 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 164 of file G4INCLCrossSectionsMultiPions.cc
References elastic(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isDelta(), G4INCL::Particle::isNucleon(), NDeltaToNN(), NNTotFixed(), and G4INCL::KinematicsUtils::squareTotalEnergyInCM().
Referenced by NNFourPi(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPionsAndResonances::total(), and total().
G4double G4INCL::CrossSectionsMultiPions::NNTotFixed (const G4double s, const G4int i) protected
Internal implementation of the NN total cross section with fixed isospin.
Definition at line 181 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 181 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::effectiveNucleonMass, and G4INCL::KinematicsUtils::momentumInLab().
Referenced by NNInelasticIso(), and NNTot().
G4double G4INCL::CrossSectionsMultiPions::NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NN Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances, G4INCL::CrossSectionsTruncatedMultiPions, and G4INCL::CrossSectionsStrangeness.
Definition at line 532 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 532 of file G4INCLCrossSectionsMultiPions.cc
References NNFourPi(), NNOnePi(), NNThreePi(), and NNTwoPi().
Referenced by G4INCL::CrossSectionsStrangeness::NNToxPiNN(), G4INCL::CrossSectionsTruncatedMultiPions::NNToxPiNN(), and G4INCL::CrossSectionsMultiPionsAndResonances::NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPions::NNTwoPi (const G4double ener, const G4int iso, const G4double xsiso) protected virtual
Cross section for direct 2-pion production - NN entrance channel.
Definition at line 331 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 331 of file G4INCLCrossSectionsMultiPions.cc
References b, e, G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::BystrickyEvaluator< N >::eval(), G4INCL::KinematicsUtils::momentumInLab(), NNOnePiOrDelta(), s02pmHC, s02pmOOT, s02pzHC, s02pzOOT, s12mzHC, s12mzOOT, s12pmHC, s12pmOOT, s12ppHC, s12ppOOT, s12zzHC, and s12zzOOT.
Referenced by NNFourPi(), NNOnePiOrDelta(), NNThreePi(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), NNToxPiNN(), and NNTwoPi().
G4double G4INCL::CrossSectionsMultiPions::NNTwoPi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 2-pion production - NN entrance channel.
Definition at line 483 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 483 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNInelasticIso(), NNTwoPi(), and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPions::NpiToLK (Particle const *const p1, Particle const *const p2) virtual
Nucleon-Pion to Stange particles cross sections.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1439 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1439 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToLK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1476 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1476 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToLKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1462 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1462 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1497 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1497 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToNKKb (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1490 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1490 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToSK (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1446 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1446 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToSK2pi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1483 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1483 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NpiToSKpi (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1469 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1469 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NSToNL (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1511 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1511 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NSToNS (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1518 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1518 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::NYelastic (Particle const *const p1, Particle const *const p2) virtual
elastic scattering for Nucleon-Strange Particles cross sections
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1338 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1338 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::omegaNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for OmegaN->PiN.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1264 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1264 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::omegaNToPiPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for OmegaN->PiPiN.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1271 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1271 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::p_pimToSmKp (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1452 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1452 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::p_pimToSzKz (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1455 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1455 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::p_pizToSzKp (Particle const *const p1, Particle const *const p2) virtual
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 1458 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1458 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::piMinuspIne (Particle const *const p1, Particle const *const p2) protected
Definition at line 1026 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1026 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), and G4InuclParticleNames::pion().
Referenced by piMinuspOnePi(), piMinuspTwoPi(), and piNIne().
G4double G4INCL::CrossSectionsMultiPions::piMinuspOnePi (Particle const *const p1, Particle const *const p2) protected
Definition at line 1105 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1105 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), piMinuspIne(), and G4InuclParticleNames::pion().
Referenced by piMinuspTwoPi(), and piNOnePi().
G4double G4INCL::CrossSectionsMultiPions::piMinuspTwoPi (Particle const *const p1, Particle const *const p2) protected
Definition at line 1183 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1183 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), piMinuspIne(), piMinuspOnePi(), and G4InuclParticleNames::pion().
Referenced by piNTwoPi().
G4double G4INCL::CrossSectionsMultiPions::piNIne (Particle const *const p1, Particle const *const p2) protected
Definition at line 632 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 632 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), piMinuspIne(), G4InuclParticleNames::pion(), and piPluspIne().
Referenced by elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), piNOnePi(), and piNToxPiN().
G4double G4INCL::CrossSectionsMultiPions::piNOnePi (Particle const *const p1, Particle const *const p2) protected virtual
Cross section for One (more) pion production - piN entrance channel.
Definition at line 883 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 883 of file G4INCLCrossSectionsMultiPions.cc
References elastic(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), piMinuspOnePi(), piNIne(), G4InuclParticleNames::pion(), and piPluspOnePi().
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsMultiPions::piNToDelta (Particle const *const p1, Particle const *const p2) virtual
Cross section for Delta production - piN Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsTruncatedMultiPions.
Definition at line 679 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 679 of file G4INCLCrossSectionsMultiPions.cc
References f3, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::totalEnergyInCM(), x, and y.
Referenced by elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), and G4INCL::CrossSectionsTruncatedMultiPions::piNToDelta().
G4double G4INCL::CrossSectionsMultiPions::piNToEtaN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance production - piN Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1227 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1227 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::piNToEtaPrimeN (Particle const *const p1, Particle const *const p2) virtual
Cross section for PiN->EtaPrimeN.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1241 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1241 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::piNToOmegaN (Particle const *const p1, Particle const *const p2) virtual
Cross section for PiN->OmegaN.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 1234 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1234 of file G4INCLCrossSectionsMultiPions.cc
G4double G4INCL::CrossSectionsMultiPions::piNTopiN (Particle const *const p1, Particle const *const p2) protected
G4double G4INCL::CrossSectionsMultiPions::piNTot (Particle const *const p1, Particle const *const p2) protected
Definition at line 712 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 712 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), INCL_ERROR, G4INCL::Particle::isPion(), G4INCL::Particle::print(), spnPiMinusPHE(), spnPiPlusPHE(), G4INCL::KinematicsUtils::totalEnergyInCM(), and x.
Referenced by elastic(), G4INCL::CrossSectionsTruncatedMultiPions::elastic(), G4INCL::CrossSectionsStrangeness::total(), G4INCL::CrossSectionsMultiPionsAndResonances::total(), and total().
G4double G4INCL::CrossSectionsMultiPions::piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - piN Channel.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsTruncatedMultiPions, G4INCL::CrossSectionsStrangeness, and G4INCL::CrossSectionsMultiPionsAndResonances.
Definition at line 849 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 849 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), piNIne(), piNOnePi(), piNTwoPi(), and G4InuclParticleNames::pion().
Referenced by G4INCL::CrossSectionsTruncatedMultiPions::piNToDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToxPiN(), G4INCL::CrossSectionsStrangeness::piNToxPiN(), and G4INCL::CrossSectionsTruncatedMultiPions::piNToxPiN().
G4double G4INCL::CrossSectionsMultiPions::piNTwoPi (Particle const *const p1, Particle const *const p2) protected virtual
Cross section for Two (more) pion production - piN entrance channel.
Definition at line 936 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 936 of file G4INCLCrossSectionsMultiPions.cc
References elastic(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), piMinuspTwoPi(), G4InuclParticleNames::pion(), and piPluspTwoPi().
Referenced by piNToxPiN().
G4double G4INCL::CrossSectionsMultiPions::piPluspIne (Particle const *const p1, Particle const *const p2) protected
Definition at line 987 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 987 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), and G4InuclParticleNames::pion().
Referenced by piNIne(), piPluspOnePi(), and piPluspTwoPi().
G4double G4INCL::CrossSectionsMultiPions::piPluspOnePi (Particle const *const p1, Particle const *const p2) protected
Definition at line 1068 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1068 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), and piPluspIne().
Referenced by piNOnePi(), and piPluspTwoPi().
G4double G4INCL::CrossSectionsMultiPions::piPluspTwoPi (Particle const *const p1, Particle const *const p2) protected
Definition at line 1142 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 1142 of file G4INCLCrossSectionsMultiPions.cc
References e, G4INCL::Particle::isNucleon(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), piPluspIne(), and piPluspOnePi().
Referenced by piNTwoPi().
G4double G4INCL::CrossSectionsMultiPions::spnPiMinusPHE (const G4double x) protected
Internal function for pion cross sections.
Definition at line 582 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 582 of file G4INCLCrossSectionsMultiPions.cc
References f3, x, and y.
Referenced by piNTot().
G4double G4INCL::CrossSectionsMultiPions::spnPiPlusPHE (const G4double x) protected
Internal function for pion cross sections.
Definition at line 552 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 552 of file G4INCLCrossSectionsMultiPions.cc
References f3, x, and y.
Referenced by piNTot().
G4double G4INCL::CrossSectionsMultiPions::total (Particle const *const p1, Particle const *const p2) virtual
Total (elastic+inelastic) particle-particle cross section.
Implements G4INCL::ICrossSections.
Reimplemented in G4INCL::CrossSectionsMultiPionsAndResonances, and G4INCL::CrossSectionsStrangeness.
Definition at line 614 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 614 of file G4INCLCrossSectionsMultiPions.cc
References elastic(), G4INCL::Particle::isDelta(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isPion(), NDeltaToNN(), NNTot(), and piNTot().
Member Data Documentation
const G4int G4INCL::CrossSectionsMultiPions::nMaxPiNN = 4 static protected
Maximum number of outgoing pions in NN collisions.
Definition at line 187 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 187 of file G4INCLCrossSectionsMultiPions.hh
Referenced by G4INCL::CrossSectionsTruncatedMultiPions::NNToxPiNN().
const G4int G4INCL::CrossSectionsMultiPions::nMaxPiPiN = 4 static protected
Maximum number of outgoing pions in piN collisions.
Definition at line 190 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 190 of file G4INCLCrossSectionsMultiPions.hh
Referenced by G4INCL::CrossSectionsTruncatedMultiPions::piNToDelta(), and G4INCL::CrossSectionsTruncatedMultiPions::piNToxPiN().
const HornerC8 G4INCL::CrossSectionsMultiPions::s01ppHC protected
Horner coefficients for s01pp.
Definition at line 195 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 195 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const G4double G4INCL::CrossSectionsMultiPions::s01ppOOT = 0.003421025623481919853 static protected
One over threshold for s01pp.
Definition at line 216 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 216 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const HornerC4 G4INCL::CrossSectionsMultiPions::s01pzHC protected
Horner coefficients for s01pz.
Definition at line 197 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 197 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const G4double G4INCL::CrossSectionsMultiPions::s01pzOOT = 0.0035739814152966403123 static protected
One over threshold for s01pz.
Definition at line 218 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 218 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const HornerC6 G4INCL::CrossSectionsMultiPions::s02pmHC protected
Horner coefficients for s02pm.
Definition at line 209 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 209 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const G4double G4INCL::CrossSectionsMultiPions::s02pmOOT = 0.0016661112962345883443 static protected
One over threshold for s02pm.
Definition at line 230 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 230 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const HornerC4 G4INCL::CrossSectionsMultiPions::s02pzHC protected
Horner coefficients for s02pz.
Definition at line 207 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 207 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const G4double G4INCL::CrossSectionsMultiPions::s02pzOOT = 0.00125 static protected
One over threshold for s02pz.
Definition at line 228 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 228 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const HornerC4 G4INCL::CrossSectionsMultiPions::s11pmHC protected
Horner coefficients for s11pm.
Definition at line 199 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 199 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const G4double G4INCL::CrossSectionsMultiPions::s11pmOOT = 0.0034855350296270480281 static protected
One over threshold for s11pm.
Definition at line 220 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 220 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const HornerC7 G4INCL::CrossSectionsMultiPions::s11pzHC protected
Horner coefficients for s11pz.
Definition at line 193 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 193 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const G4double G4INCL::CrossSectionsMultiPions::s11pzOOT = 0.0035761542037692665889 static protected
One over threshold for s11pz.
Definition at line 214 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 214 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNOnePiOrDelta().
const HornerC4 G4INCL::CrossSectionsMultiPions::s12mzHC protected
Horner coefficients for s12mz.
Definition at line 211 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 211 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const G4double G4INCL::CrossSectionsMultiPions::s12mzOOT = 0.0017047391749062392793 static protected
One over threshold for s12mz.
Definition at line 232 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 232 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const HornerC5 G4INCL::CrossSectionsMultiPions::s12pmHC protected
Horner coefficients for s12pm.
Definition at line 201 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 201 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const G4double G4INCL::CrossSectionsMultiPions::s12pmOOT = 0.0016672224074691565119 static protected
One over threshold for s12pm.
Definition at line 222 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 222 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const HornerC3 G4INCL::CrossSectionsMultiPions::s12ppHC protected
Horner coefficients for s12pp.
Definition at line 203 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 203 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const G4double G4INCL::CrossSectionsMultiPions::s12ppOOT = 0.0016507643038726931312 static protected
One over threshold for s12pp.
Definition at line 224 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 224 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const HornerC4 G4INCL::CrossSectionsMultiPions::s12zzHC protected
Horner coefficients for s12zz.
Definition at line 205 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 205 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
const G4double G4INCL::CrossSectionsMultiPions::s12zzOOT = 0.0011111111111111111111 static protected
One over threshold for s12zz.
Definition at line 226 of file G4INCLCrossSectionsMultiPions.hh.
View newest version in sPHENIX GitHub at line 226 of file G4INCLCrossSectionsMultiPions.hh
Referenced by NNTwoPi().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsMultiPions.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsMultiPions.cc