ECCE @ EIC Software: G4ILawCommonTruncatedExp Class Reference
G4ILawCommonTruncatedExp Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ILawCommonTruncatedExp.hh>
Public Member Functions
G4ILawCommonTruncatedExp (G4String name="expSharedForceInteractionLaw")
virtual ~G4ILawCommonTruncatedExp ()
virtual G4bool IsSingular () const
virtual G4bool IsEffectiveCrossSectionInfinite () const
virtual G4double ComputeEffectiveCrossSectionAt (G4double length) const
virtual G4double ComputeNonInteractionProbabilityAt (G4double length) const
void SetForceCrossSection (G4double xs)
void SetSelectedProcessXSfraction (G4double fXS)
G4double SetSelectedProcessXSfraction () const
void SetMaximumDistance (G4double d)
G4double GetMaximumDistance () const
G4double GetInteractionDistance () const
Public Member Functions inherited from G4VBiasingInteractionLaw
G4VBiasingInteractionLaw (G4String name)
virtual ~G4VBiasingInteractionLaw ()
const G4String & GetName () const
G4double Sample ()
G4double UpdateForStep (G4double truePathLength)
G4double GetSampledInteractionLength () const
Private Member Functions
virtual G4double SampleInteractionLength ()
virtual G4double UpdateInteractionLengthForStep (G4double truePathLength)
Private Attributes
G4ILawTruncatedExp fExpInteractionLaw
G4double fSelectedProcessXSfraction
G4double fInteractionDistance
Detailed Description
Definition at line 50 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ILawCommonTruncatedExp.hh
Constructor & Destructor Documentation
G4ILawCommonTruncatedExp::G4ILawCommonTruncatedExp (G4String name = "expSharedForceInteractionLaw")
Definition at line 33 of file G4ILawCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 33 of file G4ILawCommonTruncatedExp.cc
G4ILawCommonTruncatedExp::~G4ILawCommonTruncatedExp () virtual
Definition at line 38 of file G4ILawCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 38 of file G4ILawCommonTruncatedExp.cc
Member Function Documentation
G4double G4ILawCommonTruncatedExp::ComputeEffectiveCrossSectionAt (G4double length) const virtual
Implements G4VBiasingInteractionLaw.
Definition at line 42 of file G4ILawCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ILawCommonTruncatedExp.cc
References G4ILawTruncatedExp::ComputeEffectiveCrossSectionAt(), fExpInteractionLaw, and fSelectedProcessXSfraction.
G4double G4ILawCommonTruncatedExp::ComputeNonInteractionProbabilityAt (G4double length) const virtual
Implements G4VBiasingInteractionLaw.
Definition at line 47 of file G4ILawCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ILawCommonTruncatedExp.cc
References G4ILawTruncatedExp::ComputeNonInteractionProbabilityAt(), fExpInteractionLaw, G4endl, G4Exception(), G4VBiasingInteractionLaw::GetName(), and JustWarning.
G4double G4ILawCommonTruncatedExp::GetInteractionDistance () const inline
Definition at line 78 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ILawCommonTruncatedExp.hh
References fExpInteractionLaw, and G4ILawTruncatedExp::GetInteractionDistance().
G4double G4ILawCommonTruncatedExp::GetMaximumDistance () const inline
Definition at line 77 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ILawCommonTruncatedExp.hh
References fExpInteractionLaw, and G4ILawTruncatedExp::GetMaximumDistance().
Referenced by G4BOptnForceCommonTruncatedExp::UpdateForStep().
virtual G4bool G4ILawCommonTruncatedExp::IsEffectiveCrossSectionInfinite () const inline virtual
Reimplemented from G4VBiasingInteractionLaw.
Definition at line 59 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ILawCommonTruncatedExp.hh
References fExpInteractionLaw, and G4VBiasingInteractionLaw::IsEffectiveCrossSectionInfinite().
virtual G4bool G4ILawCommonTruncatedExp::IsSingular () const inline virtual
Reimplemented from G4VBiasingInteractionLaw.
Definition at line 57 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ILawCommonTruncatedExp.hh
References fExpInteractionLaw, and G4ILawTruncatedExp::IsSingular().
G4double G4ILawCommonTruncatedExp::SampleInteractionLength () private virtual
Implements G4VBiasingInteractionLaw.
Definition at line 65 of file G4ILawCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 65 of file G4ILawCommonTruncatedExp.cc
References fExpInteractionLaw, fInteractionDistance, and G4ILawTruncatedExp::SampleInteractionLength().
void G4ILawCommonTruncatedExp::SetForceCrossSection (G4double xs) inline
Definition at line 73 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ILawCommonTruncatedExp.hh
References fExpInteractionLaw, and G4ILawTruncatedExp::SetForceCrossSection().
Referenced by G4BOptnForceCommonTruncatedExp::Sample().
void G4ILawCommonTruncatedExp::SetMaximumDistance (G4double d) inline
Definition at line 76 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ILawCommonTruncatedExp.hh
References fExpInteractionLaw, and G4ILawTruncatedExp::SetMaximumDistance().
Referenced by G4BOptnForceCommonTruncatedExp::Initialize().
void G4ILawCommonTruncatedExp::SetSelectedProcessXSfraction (G4double fXS) inline
Definition at line 74 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ILawCommonTruncatedExp.hh
References fSelectedProcessXSfraction.
Referenced by G4BOptnForceCommonTruncatedExp::Sample().
G4double G4ILawCommonTruncatedExp::SetSelectedProcessXSfraction () const inline
Definition at line 75 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ILawCommonTruncatedExp.hh
References fSelectedProcessXSfraction.
G4double G4ILawCommonTruncatedExp::UpdateInteractionLengthForStep (G4double truePathLength) private virtual
Reimplemented from G4VBiasingInteractionLaw.
Definition at line 71 of file G4ILawCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ILawCommonTruncatedExp.cc
References fExpInteractionLaw, fInteractionDistance, and G4ILawTruncatedExp::UpdateInteractionLengthForStep().
Member Data Documentation
G4ILawTruncatedExp G4ILawCommonTruncatedExp::fExpInteractionLaw private
Definition at line 81 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ILawCommonTruncatedExp.hh
Referenced by ComputeEffectiveCrossSectionAt(), ComputeNonInteractionProbabilityAt(), GetInteractionDistance(), GetMaximumDistance(), IsEffectiveCrossSectionInfinite(), IsSingular(), SampleInteractionLength(), SetForceCrossSection(), SetMaximumDistance(), and UpdateInteractionLengthForStep().
G4double G4ILawCommonTruncatedExp::fInteractionDistance private
Definition at line 83 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ILawCommonTruncatedExp.hh
Referenced by SampleInteractionLength(), and UpdateInteractionLengthForStep().
G4double G4ILawCommonTruncatedExp::fSelectedProcessXSfraction private
Definition at line 82 of file G4ILawCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ILawCommonTruncatedExp.hh
Referenced by ComputeEffectiveCrossSectionAt(), and SetSelectedProcessXSfraction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ILawCommonTruncatedExp.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4ILawCommonTruncatedExp.cc