ECCE @ EIC Software: LXeDetectorConstruction Class Reference
LXeDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeDetectorConstruction.hh>
Public Member Functions
LXeDetectorConstruction ()
virtual ~LXeDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void SetDimensions (G4ThreeVector)
void SetHousingThickness (G4double)
void SetNX (G4int)
void SetNY (G4int)
void SetNZ (G4int)
void SetPMTRadius (G4double)
void SetDefaults ()
void SetSaveThreshold (G4int)
G4int GetNX () const
G4int GetNY () const
G4int GetNZ () const
G4int GetSaveThreshold () const
G4double GetScintX () const
G4double GetScintY () const
G4double GetScintZ () const
G4double GetHousingThickness () const
G4double GetPMTRadius () const
G4double GetSlabZ () const
void SetSphereOn (G4bool)
void SetHousingReflectivity (G4double)
G4double GetHousingReflectivity () const
void SetWLSSlabOn (G4bool b)
G4bool GetWLSSlabOn () const
void SetMainVolumeOn (G4bool b)
G4bool GetMainVolumeOn () const
void SetNFibers (G4int n)
G4int GetNFibers () const
void SetMainScintYield (G4double)
void SetWLSScintYield (G4double)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Static Public Member Functions
static G4bool GetSphereOn ()
Private Member Functions
void DefineMaterials ()
Private Attributes
LXeDetectorMessenger * fDetectorMessenger
G4Box * fExperimentalHall_box
G4LogicalVolume * fExperimentalHall_log
G4VPhysicalVolume * fExperimentalHall_phys
G4Material * fLXe
G4Material * fAl
G4Element * fN
G4Element * fO
G4Material * fAir
G4Material * fVacuum
G4Element * fC
G4Element * fH
G4Material * fGlass
G4Material * fPstyrene
G4Material * fPMMA
G4Material * fPethylene1
G4Material * fPethylene2
G4double fScint_x
G4double fScint_y
G4double fScint_z
G4double fD_mtl
G4int fNx
G4int fNy
G4int fNz
G4int fSaveThreshold
G4double fOuterRadius_pmt
G4int fNfibers
G4double fRefl
G4bool fWLSslab
G4bool fMainVolumeOn
G4double fSlab_z
LXeMainVolume * fMainVolume
G4MaterialPropertiesTable * fLXe_mt
G4MaterialPropertiesTable * fMPTPStyrene
G4Cache< LXeScintSD * > fScint_SD
G4Cache< LXePMTSD * > fPmt_SD
Static Private Attributes
static G4bool fSphereOn = true
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 52 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 52 of file LXeDetectorConstruction.hh
Constructor & Destructor Documentation
LXeDetectorConstruction::LXeDetectorConstruction ()
Definition at line 67 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 67 of file LXeDetectorConstruction.cc
References DefineMaterials(), fAir, fAl, fC, fDetectorMessenger, fExperimentalHall_box, fExperimentalHall_log, fExperimentalHall_phys, fGlass, fH, fLXe, fN, fO, fPethylene1, fPethylene2, fPMMA, fPstyrene, fSaveThreshold, fVacuum, and SetDefaults().
LXeDetectorConstruction::~LXeDetectorConstruction () virtual
Definition at line 88 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 88 of file LXeDetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * LXeDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 243 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 243 of file LXeDetectorConstruction.cc
References G4MaterialPropertiesTable::AddProperty(), cm, dielectric_metal, eV, expHall_x, expHall_y, expHall_z, fD_mtl, fExperimentalHall_box, fExperimentalHall_log, fExperimentalHall_phys, fMainVolume, fMainVolumeOn, fScint_x, fScint_y, fScint_z, fSlab_z, fVacuum, fWLSslab, G4VisAttributes::GetInvisible(), glisur, m, num, polished, G4InuclParticleNames::pp, G4OpticalSurface::SetFinish(), G4OpticalSurface::SetMaterialPropertiesTable(), G4OpticalSurface::SetModel(), G4OpticalSurface::SetType(), and G4LogicalVolume::SetVisAttributes().
void LXeDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 304 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 304 of file LXeDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fMainVolume, fPmt_SD, fScint_SD, G4cout, G4endl, G4Cache< VALTYPE >::Get(), LXeMainVolume::GetLogPhotoCath(), LXeMainVolume::GetLogScint(), LXeMainVolume::GetPmtPositions(), G4SDManager::GetSDMpointer(), LXePMTSD::InitPMTs(), G4Cache< VALTYPE >::Put(), LXePMTSD::SetPmtPositions(), and G4VUserDetectorConstruction::SetSensitiveDetector().
void LXeDetectorConstruction::DefineMaterials (void) private
Definition at line 92 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 92 of file LXeDetectorConstruction.cc
References a, G4MaterialPropertiesTable::AddConstProperty(), G4Material::AddElement(), G4MaterialPropertiesTable::AddProperty(), cm, cm3, e, eV, fAir, fAl, fC, fGlass, fH, fLXe, fLXe_mt, fMPTPStyrene, fN, fO, fPethylene1, fPethylene2, fPMMA, fPstyrene, fVacuum, Acts::UnitConstants::g, G4Material::GetIonisation(), kelvin, keV, kg, kStateGas, m, m3, MeV, mg, mm, mole, ns, pascal, perCent, G4IonisParamMat::SetBirksConstant(), G4Material::SetMaterialPropertiesTable(), source.hepunit::universe_mean_density, and z.
Referenced by LXeDetectorConstruction().
G4double LXeDetectorConstruction::GetHousingReflectivity () const inline
Definition at line 88 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file LXeDetectorConstruction.hh
References fRefl.
Referenced by LXeMainVolume::CopyValues().
G4double LXeDetectorConstruction::GetHousingThickness () const inline
Definition at line 80 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file LXeDetectorConstruction.hh
References fD_mtl.
Referenced by LXeMainVolume::CopyValues().
G4bool LXeDetectorConstruction::GetMainVolumeOn () const inline
Definition at line 94 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file LXeDetectorConstruction.hh
References fMainVolumeOn.
G4int LXeDetectorConstruction::GetNFibers () const inline
Definition at line 97 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file LXeDetectorConstruction.hh
References fNfibers.
Referenced by LXeWLSSlab::CopyValues().
G4int LXeDetectorConstruction::GetNX () const inline
Definition at line 73 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file LXeDetectorConstruction.hh
References fNx.
Referenced by LXeMainVolume::CopyValues().
G4int LXeDetectorConstruction::GetNY () const inline
Definition at line 74 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file LXeDetectorConstruction.hh
References fNy.
Referenced by LXeMainVolume::CopyValues().
G4int LXeDetectorConstruction::GetNZ () const inline
Definition at line 75 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file LXeDetectorConstruction.hh
References fNz.
Referenced by LXeMainVolume::CopyValues().
G4double LXeDetectorConstruction::GetPMTRadius () const inline
Definition at line 81 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file LXeDetectorConstruction.hh
References fOuterRadius_pmt.
Referenced by LXeMainVolume::CopyValues().
G4int LXeDetectorConstruction::GetSaveThreshold () const inline
Definition at line 76 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file LXeDetectorConstruction.hh
References fSaveThreshold.
G4double LXeDetectorConstruction::GetScintX () const inline
Definition at line 77 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file LXeDetectorConstruction.hh
References fScint_x.
Referenced by LXeWLSFiber::CopyValues(), LXeWLSSlab::CopyValues(), and LXeMainVolume::CopyValues().
G4double LXeDetectorConstruction::GetScintY () const inline
Definition at line 78 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 78 of file LXeDetectorConstruction.hh
References fScint_y.
Referenced by LXeWLSSlab::CopyValues(), and LXeMainVolume::CopyValues().
G4double LXeDetectorConstruction::GetScintZ () const inline
Definition at line 79 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 79 of file LXeDetectorConstruction.hh
References fScint_z.
Referenced by LXeWLSSlab::CopyValues(), and LXeMainVolume::CopyValues().
G4double LXeDetectorConstruction::GetSlabZ () const inline
Definition at line 82 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file LXeDetectorConstruction.hh
References fSlab_z.
Referenced by LXeWLSSlab::CopyValues().
static G4bool LXeDetectorConstruction::GetSphereOn () inline static
Definition at line 85 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file LXeDetectorConstruction.hh
References fSphereOn.
Referenced by LXeMainVolume::CopyValues(), LXeTrackingAction::PostUserTrackingAction(), and LXePMTSD::ProcessHits_constStep().
G4bool LXeDetectorConstruction::GetWLSSlabOn () const inline
Definition at line 91 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file LXeDetectorConstruction.hh
References fWLSslab.
void LXeDetectorConstruction::SetDefaults ()
Definition at line 392 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 392 of file LXeDetectorConstruction.cc
References G4MaterialPropertiesTable::AddConstProperty(), G4UImanager::ApplyCommand(), cm, fD_mtl, fLXe_mt, fMainVolume, fMainVolumeOn, fMPTPStyrene, fNfibers, fNx, fNy, fNz, fOuterRadius_pmt, fRefl, fScint_x, fScint_y, fScint_z, fSlab_z, fSphereOn, fWLSslab, G4UImanager::GetUIpointer(), keV, MeV, and mm.
Referenced by LXeDetectorConstruction(), and LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetDimensions (G4ThreeVector dims)
Definition at line 348 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 348 of file LXeDetectorConstruction.cc
References fScint_x, fScint_y, fScint_z, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetHousingReflectivity (G4double r)
Definition at line 433 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 433 of file LXeDetectorConstruction.cc
References fRefl, G4RunManager::GetRunManager(), r, and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetHousingThickness (G4double d_mtl)
Definition at line 357 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 357 of file LXeDetectorConstruction.cc
References fD_mtl, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetMainScintYield (G4double y)
Definition at line 461 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 461 of file LXeDetectorConstruction.cc
References G4MaterialPropertiesTable::AddConstProperty(), fLXe_mt, and MeV.
void LXeDetectorConstruction::SetMainVolumeOn (G4bool b)
Definition at line 447 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 447 of file LXeDetectorConstruction.cc
References b, fMainVolumeOn, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetNFibers (G4int n)
Definition at line 454 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 454 of file LXeDetectorConstruction.cc
References fNfibers, G4RunManager::GetRunManager(), n, and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetNX (G4int nx)
Definition at line 364 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 364 of file LXeDetectorConstruction.cc
References fNx, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetNY (G4int ny)
Definition at line 371 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 371 of file LXeDetectorConstruction.cc
References fNy, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetNZ (G4int nz)
Definition at line 378 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 378 of file LXeDetectorConstruction.cc
References fNz, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetPMTRadius (G4double outerRadius_pmt)
Definition at line 385 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 385 of file LXeDetectorConstruction.cc
References fOuterRadius_pmt, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetSaveThreshold (G4int save)
Definition at line 473 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 473 of file LXeDetectorConstruction.cc
References fSaveThreshold, G4RunManager::GetRunManager(), and G4RunManager::SetRandomNumberStore().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetSphereOn (G4bool b)
Definition at line 426 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 426 of file LXeDetectorConstruction.cc
References b, fSphereOn, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetWLSScintYield (G4double y)
Definition at line 467 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 467 of file LXeDetectorConstruction.cc
References G4MaterialPropertiesTable::AddConstProperty(), fMPTPStyrene, and MeV.
Referenced by LXeDetectorMessenger::SetNewValue().
void LXeDetectorConstruction::SetWLSSlabOn (G4bool b)
Definition at line 440 of file LXeDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 440 of file LXeDetectorConstruction.cc
References b, fWLSslab, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by LXeDetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* LXeDetectorConstruction::fAir private
Definition at line 117 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Material* LXeDetectorConstruction::fAl private
Definition at line 114 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Element* LXeDetectorConstruction::fC private
Definition at line 119 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4double LXeDetectorConstruction::fD_mtl private
Definition at line 131 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 131 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetHousingThickness(), SetDefaults(), and SetHousingThickness().
LXeDetectorMessenger* LXeDetectorConstruction::fDetectorMessenger private
Definition at line 106 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file LXeDetectorConstruction.hh
Referenced by LXeDetectorConstruction().
G4Box* LXeDetectorConstruction::fExperimentalHall_box private
Definition at line 108 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 108 of file LXeDetectorConstruction.hh
Referenced by Construct(), and LXeDetectorConstruction().
G4LogicalVolume* LXeDetectorConstruction::fExperimentalHall_log private
Definition at line 109 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file LXeDetectorConstruction.hh
Referenced by Construct(), and LXeDetectorConstruction().
G4VPhysicalVolume* LXeDetectorConstruction::fExperimentalHall_phys private
Definition at line 110 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file LXeDetectorConstruction.hh
Referenced by Construct(), and LXeDetectorConstruction().
G4Material* LXeDetectorConstruction::fGlass private
Definition at line 121 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Element* LXeDetectorConstruction::fH private
Definition at line 120 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 120 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Material* LXeDetectorConstruction::fLXe private
Definition at line 113 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 113 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4MaterialPropertiesTable* LXeDetectorConstruction::fLXe_mt private
Definition at line 146 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 146 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), SetDefaults(), and SetMainScintYield().
LXeMainVolume* LXeDetectorConstruction::fMainVolume private
Definition at line 144 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 144 of file LXeDetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), and SetDefaults().
G4bool LXeDetectorConstruction::fMainVolumeOn private
Definition at line 141 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 141 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetMainVolumeOn(), SetDefaults(), and SetMainVolumeOn().
G4MaterialPropertiesTable* LXeDetectorConstruction::fMPTPStyrene private
Definition at line 147 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 147 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), SetDefaults(), and SetWLSScintYield().
G4Element* LXeDetectorConstruction::fN private
Definition at line 115 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 115 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4int LXeDetectorConstruction::fNfibers private
Definition at line 137 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 137 of file LXeDetectorConstruction.hh
Referenced by GetNFibers(), SetDefaults(), and SetNFibers().
G4int LXeDetectorConstruction::fNx private
Definition at line 132 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 132 of file LXeDetectorConstruction.hh
Referenced by GetNX(), SetDefaults(), and SetNX().
G4int LXeDetectorConstruction::fNy private
Definition at line 133 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 133 of file LXeDetectorConstruction.hh
Referenced by GetNY(), SetDefaults(), and SetNY().
G4int LXeDetectorConstruction::fNz private
Definition at line 134 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 134 of file LXeDetectorConstruction.hh
Referenced by GetNZ(), SetDefaults(), and SetNZ().
G4Element* LXeDetectorConstruction::fO private
Definition at line 116 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4double LXeDetectorConstruction::fOuterRadius_pmt private
Definition at line 136 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 136 of file LXeDetectorConstruction.hh
Referenced by GetPMTRadius(), SetDefaults(), and SetPMTRadius().
G4Material* LXeDetectorConstruction::fPethylene1 private
Definition at line 124 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 124 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Material* LXeDetectorConstruction::fPethylene2 private
Definition at line 125 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Material* LXeDetectorConstruction::fPMMA private
Definition at line 123 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 123 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4Cache<LXePMTSD*> LXeDetectorConstruction::fPmt_SD private
Definition at line 151 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 151 of file LXeDetectorConstruction.hh
Referenced by ConstructSDandField().
G4Material* LXeDetectorConstruction::fPstyrene private
Definition at line 122 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 122 of file LXeDetectorConstruction.hh
Referenced by DefineMaterials(), and LXeDetectorConstruction().
G4double LXeDetectorConstruction::fRefl private
Definition at line 139 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 139 of file LXeDetectorConstruction.hh
Referenced by GetHousingReflectivity(), SetDefaults(), and SetHousingReflectivity().
G4int LXeDetectorConstruction::fSaveThreshold private
Definition at line 135 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 135 of file LXeDetectorConstruction.hh
Referenced by GetSaveThreshold(), LXeDetectorConstruction(), and SetSaveThreshold().
G4Cache<LXeScintSD*> LXeDetectorConstruction::fScint_SD private
Definition at line 150 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 150 of file LXeDetectorConstruction.hh
Referenced by ConstructSDandField().
G4double LXeDetectorConstruction::fScint_x private
Definition at line 128 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 128 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetScintX(), SetDefaults(), and SetDimensions().
G4double LXeDetectorConstruction::fScint_y private
Definition at line 129 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 129 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetScintY(), SetDefaults(), and SetDimensions().
G4double LXeDetectorConstruction::fScint_z private
Definition at line 130 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 130 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetScintZ(), SetDefaults(), and SetDimensions().
G4double LXeDetectorConstruction::fSlab_z private
Definition at line 142 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 142 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetSlabZ(), and SetDefaults().
G4bool LXeDetectorConstruction::fSphereOn = true static private
Definition at line 138 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 138 of file LXeDetectorConstruction.hh
Referenced by GetSphereOn(), SetDefaults(), and SetSphereOn().
G4Material* LXeDetectorConstruction::fVacuum private
Definition at line 118 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 118 of file LXeDetectorConstruction.hh
Referenced by Construct(), DefineMaterials(), and LXeDetectorConstruction().
G4bool LXeDetectorConstruction::fWLSslab private
Definition at line 140 of file LXeDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 140 of file LXeDetectorConstruction.hh
Referenced by Construct(), GetWLSSlabOn(), SetDefaults(), and SetWLSSlabOn().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeDetectorConstruction.cc