ECCE @ EIC Software: G4tgrSolidBoolean Class Reference
G4tgrSolidBoolean Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrSolidBoolean.hh>
Public Member Functions
G4tgrSolidBoolean (const std::vector< G4String > &wl)
~G4tgrSolidBoolean ()
const G4tgrSolid * GetSolid (G4int ii) const
const G4String & GetRelativeRotMatName () const
G4ThreeVector GetRelativePlace () const
Public Member Functions inherited from G4tgrSolid
G4tgrSolid ()
G4tgrSolid (const std::vector< G4String > &wl)
virtual ~G4tgrSolid ()
const G4String & GetName () const
const G4String & GetType () const
const std::vector< std::vector
< G4double > * > GetSolidParams () const
Private Attributes
std::vector< std::vector
< G4double > * > theSolidParams
G4String theRelativeRotMatName
G4ThreeVector theRelativePlace
std::vector< const G4tgrSolid * > theSolids
Friends
std::ostream & operator<< (std::ostream &, const G4tgrSolidBoolean &)
Additional Inherited Members
Protected Attributes inherited from G4tgrSolid
G4String theName
G4String theType
std::vector< std::vector
< G4double > * > theSolidParams
Detailed Description
Definition at line 50 of file G4tgrSolidBoolean.hh.
View newest version in sPHENIX GitHub at line 50 of file G4tgrSolidBoolean.hh
Constructor & Destructor Documentation
G4tgrSolidBoolean::G4tgrSolidBoolean (const std::vector< G4String > & wl)
Definition at line 43 of file G4tgrSolidBoolean.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgrSolidBoolean.cc
References G4tgrUtils::DumpVS(), FatalException, G4tgrVolumeMgr::FindSolid(), G4tgrVolumeMgr::FindVolume(), G4cout, G4endl, G4Exception(), G4tgrUtils::GetDouble(), G4tgrVolumeMgr::GetInstance(), G4tgrVolume::GetSolid(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), G4tgrVolumeMgr::RegisterMe(), G4tgrSolid::theName, theRelativePlace, theRelativeRotMatName, theSolids, and G4tgrSolid::theType.
G4tgrSolidBoolean::~G4tgrSolidBoolean ()
Definition at line 96 of file G4tgrSolidBoolean.cc.
View newest version in sPHENIX GitHub at line 96 of file G4tgrSolidBoolean.cc
Member Function Documentation
G4ThreeVector G4tgrSolidBoolean::GetRelativePlace () const virtual
Reimplemented from G4tgrSolid.
Definition at line 109 of file G4tgrSolidBoolean.cc.
View newest version in sPHENIX GitHub at line 109 of file G4tgrSolidBoolean.cc
References theRelativePlace.
Referenced by G4tgbVolume::FindOrConstructG4Solid().
const G4String & G4tgrSolidBoolean::GetRelativeRotMatName () const virtual
Reimplemented from G4tgrSolid.
Definition at line 102 of file G4tgrSolidBoolean.cc.
View newest version in sPHENIX GitHub at line 102 of file G4tgrSolidBoolean.cc
References theRelativeRotMatName.
const G4tgrSolid * G4tgrSolidBoolean::GetSolid (G4int ii) const inline
Definition at line 81 of file G4tgrSolidBoolean.hh.
View newest version in sPHENIX GitHub at line 81 of file G4tgrSolidBoolean.hh
References FatalException, G4Exception(), message(), and theSolids.
Referenced by G4tgbVolume::FindOrConstructG4Solid().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrSolidBoolean & sol) friend
Definition at line 116 of file G4tgrSolidBoolean.cc.
View newest version in sPHENIX GitHub at line 116 of file G4tgrSolidBoolean.cc
Member Data Documentation
G4ThreeVector G4tgrSolidBoolean::theRelativePlace private
Definition at line 73 of file G4tgrSolidBoolean.hh.
View newest version in sPHENIX GitHub at line 73 of file G4tgrSolidBoolean.hh
Referenced by G4tgrSolidBoolean(), and GetRelativePlace().
G4String G4tgrSolidBoolean::theRelativeRotMatName private
Definition at line 72 of file G4tgrSolidBoolean.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgrSolidBoolean.hh
Referenced by G4tgrSolidBoolean(), and GetRelativeRotMatName().
std::vector< std::vector<G4double>* > G4tgrSolidBoolean::theSolidParams private
Definition at line 69 of file G4tgrSolidBoolean.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgrSolidBoolean.hh
Referenced by operator<<().
std::vector<const G4tgrSolid*> G4tgrSolidBoolean::theSolids private
Definition at line 76 of file G4tgrSolidBoolean.hh.
View newest version in sPHENIX GitHub at line 76 of file G4tgrSolidBoolean.hh
Referenced by G4tgrSolidBoolean(), and GetSolid().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrSolidBoolean.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrSolidBoolean.cc