ECCE @ EIC Software: G4FTFBinaryNeutronBuilder Class Reference
G4FTFBinaryNeutronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBinaryNeutronBuilder.hh>
Public Member Functions
G4FTFBinaryNeutronBuilder (G4bool quasiElastic=false)
virtual ~G4FTFBinaryNeutronBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4HadronFissionProcess *) finaloverride
virtual void Build (G4HadronCaptureProcess *) finaloverride
virtual void Build (G4NeutronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
G4double theMax
Detailed Description
Definition at line 57 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4FTFBinaryNeutronBuilder.hh
Constructor & Destructor Documentation
G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder (G4bool quasiElastic = false)
Definition at line 51 of file G4FTFBinaryNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 51 of file G4FTFBinaryNeutronBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFBinaryNeutronBuilder::~G4FTFBinaryNeutronBuilder () virtual
Definition at line 76 of file G4FTFBinaryNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FTFBinaryNeutronBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4FTFBinaryNeutronBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 63 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4FTFBinaryNeutronBuilder.hh
virtual void G4FTFBinaryNeutronBuilder::Build (G4HadronFissionProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 64 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4FTFBinaryNeutronBuilder.hh
virtual void G4FTFBinaryNeutronBuilder::Build (G4HadronCaptureProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 65 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4FTFBinaryNeutronBuilder.hh
void G4FTFBinaryNeutronBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 84 of file G4FTFBinaryNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 84 of file G4FTFBinaryNeutronBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4FTFBinaryNeutronBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 69 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4FTFBinaryNeutronBuilder.hh
References theMax.
virtual void G4FTFBinaryNeutronBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 68 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4FTFBinaryNeutronBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4FTFBinaryNeutronBuilder::theCascade private
Definition at line 75 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FTFBinaryNeutronBuilder.hh
Referenced by G4FTFBinaryNeutronBuilder().
G4double G4FTFBinaryNeutronBuilder::theMax private
Definition at line 81 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FTFBinaryNeutronBuilder.hh
Referenced by Build(), G4FTFBinaryNeutronBuilder(), and SetMaxEnergy().
G4double G4FTFBinaryNeutronBuilder::theMin private
Definition at line 80 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FTFBinaryNeutronBuilder.hh
Referenced by Build(), G4FTFBinaryNeutronBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFBinaryNeutronBuilder::theModel private
Definition at line 74 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FTFBinaryNeutronBuilder.hh
Referenced by Build(), and G4FTFBinaryNeutronBuilder().
G4QuasiElasticChannel* G4FTFBinaryNeutronBuilder::theQuasiElastic private
Definition at line 78 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFBinaryNeutronBuilder.hh
Referenced by G4FTFBinaryNeutronBuilder(), and ~G4FTFBinaryNeutronBuilder().
G4ExcitedStringDecay* G4FTFBinaryNeutronBuilder::theStringDecay private
Definition at line 77 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FTFBinaryNeutronBuilder.hh
Referenced by G4FTFBinaryNeutronBuilder(), and ~G4FTFBinaryNeutronBuilder().
G4FTFModel* G4FTFBinaryNeutronBuilder::theStringModel private
Definition at line 76 of file G4FTFBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FTFBinaryNeutronBuilder.hh
Referenced by G4FTFBinaryNeutronBuilder(), and ~G4FTFBinaryNeutronBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBinaryNeutronBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFBinaryNeutronBuilder.cc