ECCE @ EIC Software: G4NeutronLENDBuilder Class Reference
G4NeutronLENDBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4NeutronLENDBuilder.hh>
Public Member Functions
G4NeutronLENDBuilder (G4String eva="")
virtual ~G4NeutronLENDBuilder ()
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void Build (G4HadronFissionProcess *aP) finaloverride
virtual void Build (G4HadronCaptureProcess *aP) finaloverride
virtual void Build (G4NeutronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
void SetMinInelasticEnergy (G4double aM)
virtual void SetMaxEnergy (G4double aM) finaloverride
void SetMaxInelasticEnergy (G4double aM)
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theIMin
G4double theMax
G4double theIMax
G4LENDElastic * theLENDElastic
G4LENDElasticCrossSection * theLENDElasticCrossSection
G4LENDInelastic * theLENDInelastic
G4LENDInelasticCrossSection * theLENDInelasticCrossSection
G4LENDFission * theLENDFission
G4LENDFissionCrossSection * theLENDFissionCrossSection
G4LENDCapture * theLENDCapture
G4LENDCaptureCrossSection * theLENDCaptureCrossSection
G4String evaluation
Detailed Description
Definition at line 46 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 46 of file G4NeutronLENDBuilder.hh
Constructor & Destructor Documentation
G4NeutronLENDBuilder::G4NeutronLENDBuilder (G4String eva = "")
Definition at line 33 of file G4NeutronLENDBuilder.cc.
View newest version in sPHENIX GitHub at line 33 of file G4NeutronLENDBuilder.cc
References evaluation, MeV, theIMax, theIMin, theLENDCapture, theLENDCaptureCrossSection, theLENDElastic, theLENDElasticCrossSection, theLENDFission, theLENDFissionCrossSection, theLENDInelastic, theLENDInelasticCrossSection, theMax, and theMin.
virtual G4NeutronLENDBuilder::~G4NeutronLENDBuilder () inline virtual
Definition at line 50 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4NeutronLENDBuilder.hh
Member Function Documentation
void G4NeutronLENDBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 55 of file G4NeutronLENDBuilder.cc.
View newest version in sPHENIX GitHub at line 55 of file G4NeutronLENDBuilder.cc
References G4HadronicProcess::AddDataSet(), G4LENDModel::AllowNaturalAbundanceTarget(), G4LENDCrossSection::AllowNaturalAbundanceTarget(), G4LENDModel::ChangeDefaultEvaluation(), G4LENDCrossSection::ChangeDefaultEvaluation(), evaluation, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theLENDElastic, theLENDElasticCrossSection, theMax, and theMin.
void G4NeutronLENDBuilder::Build (G4HadronFissionProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 73 of file G4NeutronLENDBuilder.cc.
View newest version in sPHENIX GitHub at line 73 of file G4NeutronLENDBuilder.cc
References G4HadronicProcess::AddDataSet(), G4LENDModel::ChangeDefaultEvaluation(), G4LENDCrossSection::ChangeDefaultEvaluation(), evaluation, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theLENDFission, theLENDFissionCrossSection, theMax, and theMin.
void G4NeutronLENDBuilder::Build (G4HadronCaptureProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 90 of file G4NeutronLENDBuilder.cc.
View newest version in sPHENIX GitHub at line 90 of file G4NeutronLENDBuilder.cc
References G4HadronicProcess::AddDataSet(), G4LENDModel::AllowNaturalAbundanceTarget(), G4LENDCrossSection::AllowNaturalAbundanceTarget(), G4LENDModel::ChangeDefaultEvaluation(), G4LENDCrossSection::ChangeDefaultEvaluation(), evaluation, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theLENDCapture, theLENDCaptureCrossSection, theMax, and theMin.
void G4NeutronLENDBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 107 of file G4NeutronLENDBuilder.cc.
View newest version in sPHENIX GitHub at line 107 of file G4NeutronLENDBuilder.cc
References G4HadronicProcess::AddDataSet(), G4LENDModel::AllowNaturalAbundanceTarget(), G4LENDCrossSection::AllowNaturalAbundanceTarget(), G4LENDModel::ChangeDefaultEvaluation(), G4LENDCrossSection::ChangeDefaultEvaluation(), evaluation, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theIMax, theIMin, theLENDInelastic, and theLENDInelasticCrossSection.
virtual void G4NeutronLENDBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 66 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4NeutronLENDBuilder.hh
References theIMax, and theMax.
void G4NeutronLENDBuilder::SetMaxInelasticEnergy (G4double aM) inline
Definition at line 71 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NeutronLENDBuilder.hh
References theIMax.
virtual void G4NeutronLENDBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 57 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4NeutronLENDBuilder.hh
References theIMin, and theMin.
void G4NeutronLENDBuilder::SetMinInelasticEnergy (G4double aM) inline
Definition at line 62 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4NeutronLENDBuilder.hh
References theIMin.
Member Data Documentation
G4String G4NeutronLENDBuilder::evaluation private
Definition at line 94 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 94 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4double G4NeutronLENDBuilder::theIMax private
Definition at line 83 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4NeutronLENDBuilder.hh
Referenced by Build(), G4NeutronLENDBuilder(), SetMaxEnergy(), and SetMaxInelasticEnergy().
G4double G4NeutronLENDBuilder::theIMin private
Definition at line 81 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4NeutronLENDBuilder.hh
Referenced by Build(), G4NeutronLENDBuilder(), SetMinEnergy(), and SetMinInelasticEnergy().
G4LENDCapture* G4NeutronLENDBuilder::theLENDCapture private
Definition at line 91 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 91 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDCaptureCrossSection* G4NeutronLENDBuilder::theLENDCaptureCrossSection private
Definition at line 92 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDElastic* G4NeutronLENDBuilder::theLENDElastic private
Definition at line 85 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDElasticCrossSection* G4NeutronLENDBuilder::theLENDElasticCrossSection private
Definition at line 86 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDFission* G4NeutronLENDBuilder::theLENDFission private
Definition at line 89 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 89 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDFissionCrossSection* G4NeutronLENDBuilder::theLENDFissionCrossSection private
Definition at line 90 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 90 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDInelastic* G4NeutronLENDBuilder::theLENDInelastic private
Definition at line 87 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4LENDInelasticCrossSection* G4NeutronLENDBuilder::theLENDInelasticCrossSection private
Definition at line 88 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronLENDBuilder.hh
Referenced by Build(), and G4NeutronLENDBuilder().
G4double G4NeutronLENDBuilder::theMax private
Definition at line 82 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4NeutronLENDBuilder.hh
Referenced by Build(), G4NeutronLENDBuilder(), and SetMaxEnergy().
G4double G4NeutronLENDBuilder::theMin private
Definition at line 80 of file G4NeutronLENDBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4NeutronLENDBuilder.hh
Referenced by Build(), G4NeutronLENDBuilder(), and SetMinEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4NeutronLENDBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4NeutronLENDBuilder.cc