ECCE @ EIC Software: G4ITLeadingTracks Class Reference
G4ITLeadingTracks Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITLeadingTracks.hh>
Public Member Functions
G4ITLeadingTracks ()
virtual ~G4ITLeadingTracks ()
void Reset ()
void Push (G4Track *)
void PrepareLeadingTracks ()
Protected Attributes
std::vector< G4Track * > fLeadingTracks
Detailed Description
Definition at line 40 of file G4ITLeadingTracks.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ITLeadingTracks.hh
Constructor & Destructor Documentation
G4ITLeadingTracks::G4ITLeadingTracks ()
Definition at line 37 of file G4ITLeadingTracks.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ITLeadingTracks.cc
G4ITLeadingTracks::~G4ITLeadingTracks () virtual
Definition at line 43 of file G4ITLeadingTracks.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ITLeadingTracks.cc
Member Function Documentation
void G4ITLeadingTracks::PrepareLeadingTracks ()
Definition at line 80 of file G4ITLeadingTracks.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ITLeadingTracks.cc
References fLeadingTracks, GetIT(), G4IT::GetTrackingInfo(), G4TrackingInformation::SetLeadingStep(), and track.
Referenced by G4ITStepProcessor::PrepareLeadingTracks().
void G4ITLeadingTracks::Push (G4Track * track)
Definition at line 75 of file G4ITLeadingTracks.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ITLeadingTracks.cc
References fLeadingTracks.
Referenced by G4ITStepProcessor::ExtractILData().
void G4ITLeadingTracks::Reset ()
Definition at line 49 of file G4ITLeadingTracks.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ITLeadingTracks.cc
References fLeadingTracks, GetIT(), G4IT::GetTrackingInfo(), G4TrackingInformation::SetLeadingStep(), and track.
Referenced by G4ITStepProcessor::ExtractILData(), and G4ITStepProcessor::ResetLeadingTracks().
Member Data Documentation
std::vector<G4Track*> G4ITLeadingTracks::fLeadingTracks protected
Definition at line 52 of file G4ITLeadingTracks.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ITLeadingTracks.hh
Referenced by PrepareLeadingTracks(), Push(), and Reset().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITLeadingTracks.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITLeadingTracks.cc