ECCE @ EIC Software: G4DeuteronPHPBuilder Class Reference
G4DeuteronPHPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4DeuteronPHPBuilder.hh>
Public Member Functions
G4DeuteronPHPBuilder ()
virtual ~G4DeuteronPHPBuilder ()
virtual void Build (G4DeuteronInelasticProcess *aP) finaloverride
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VDeuteronBuilder
G4VDeuteronBuilder ()=default
virtual ~G4VDeuteronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theMax
G4ParticleHPInelastic * theParticlePHPModel
Detailed Description
Definition at line 49 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 49 of file G4DeuteronPHPBuilder.hh
Constructor & Destructor Documentation
G4DeuteronPHPBuilder::G4DeuteronPHPBuilder ()
Definition at line 34 of file G4DeuteronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 34 of file G4DeuteronPHPBuilder.cc
References MeV, theMax, theMin, and theParticlePHPModel.
virtual G4DeuteronPHPBuilder::~G4DeuteronPHPBuilder () inline virtual
Definition at line 53 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DeuteronPHPBuilder.hh
Member Function Documentation
void G4DeuteronPHPBuilder::Build (G4DeuteronInelasticProcess * aP) final override virtual
Implements G4VDeuteronBuilder.
Definition at line 48 of file G4DeuteronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4DeuteronPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Deuteron::Deuteron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4HadronicInteraction::SetMinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theMax, theMin, and theParticlePHPModel.
void G4DeuteronPHPBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VDeuteronBuilder.
Definition at line 42 of file G4DeuteronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 42 of file G4DeuteronPHPBuilder.cc
References G4cout, and G4endl.
virtual void G4DeuteronPHPBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 63 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4DeuteronPHPBuilder.hh
References theMax.
virtual void G4DeuteronPHPBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 59 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4DeuteronPHPBuilder.hh
References theMin.
Member Data Documentation
G4double G4DeuteronPHPBuilder::theMax private
Definition at line 72 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4DeuteronPHPBuilder.hh
Referenced by Build(), G4DeuteronPHPBuilder(), and SetMaxEnergy().
G4double G4DeuteronPHPBuilder::theMin private
Definition at line 71 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4DeuteronPHPBuilder.hh
Referenced by Build(), G4DeuteronPHPBuilder(), and SetMinEnergy().
G4ParticleHPInelastic* G4DeuteronPHPBuilder::theParticlePHPModel private
Definition at line 73 of file G4DeuteronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DeuteronPHPBuilder.hh
Referenced by Build(), and G4DeuteronPHPBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4DeuteronPHPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4DeuteronPHPBuilder.cc