ECCE @ EIC Software: G4V3DNucleus Class Reference
G4V3DNucleus Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4V3DNucleus.hh>
Public Member Functions
G4V3DNucleus ()
virtual ~G4V3DNucleus ()
virtual void Init (G4int theA, G4int theZ)=0
virtual G4bool StartLoop ()=0
virtual G4Nucleon * GetNextNucleon ()=0
virtual const std::vector
< G4Nucleon > & GetNucleons ()=0
virtual G4int GetMassNumber ()=0
virtual G4double GetMass ()=0
virtual G4int GetCharge ()=0
virtual G4double GetNuclearRadius ()=0
virtual G4double GetNuclearRadius (const G4double maxRelativeDensity)=0
virtual G4double GetOuterRadius ()=0
virtual G4double CoulombBarrier ()=0
virtual void DoLorentzBoost (const G4LorentzVector &theBoost)=0
virtual void DoLorentzBoost (const G4ThreeVector &theBeta)=0
virtual void DoLorentzContraction (const G4LorentzVector &theBoost)=0
virtual void DoLorentzContraction (const G4ThreeVector &theBeta)=0
virtual void DoTranslation (const G4ThreeVector &theShift)=0
virtual const G4VNuclearDensity * GetNuclearDensity () const =0
virtual void SortNucleonsIncZ ()=0
virtual void SortNucleonsDecZ ()=0
std::pair< G4double, G4double > ChooseImpactXandY (G4double maxImpact)
std::pair< G4double, G4double > RefetchImpactXandY ()
Private Member Functions
G4V3DNucleus (const G4V3DNucleus &right)
const G4V3DNucleus & operator= (const G4V3DNucleus &right)
G4bool operator== (const G4V3DNucleus &right) const
G4bool operator!= (const G4V3DNucleus &right) const
Private Attributes
std::pair< G4double, G4double > theImpactParameter
Detailed Description
Definition at line 40 of file G4V3DNucleus.hh.
View newest version in sPHENIX GitHub at line 40 of file G4V3DNucleus.hh
Constructor & Destructor Documentation
G4V3DNucleus::G4V3DNucleus ()
Definition at line 31 of file G4V3DNucleus.cc.
View newest version in sPHENIX GitHub at line 31 of file G4V3DNucleus.cc
G4V3DNucleus::~G4V3DNucleus () virtual
Definition at line 40 of file G4V3DNucleus.cc.
View newest version in sPHENIX GitHub at line 40 of file G4V3DNucleus.cc
G4V3DNucleus::G4V3DNucleus (const G4V3DNucleus & right) private
Definition at line 35 of file G4V3DNucleus.cc.
View newest version in sPHENIX GitHub at line 35 of file G4V3DNucleus.cc
Member Function Documentation
std::pair< G4double, G4double > G4V3DNucleus::ChooseImpactXandY (G4double maxImpact) inline
Definition at line 86 of file G4V3DNucleus.hh.
View newest version in sPHENIX GitHub at line 86 of file G4V3DNucleus.hh
References G4UniformRand, theImpactParameter, x, and y.
Referenced by G4FTFParticipants::GetList(), and G4QGSParticipants::GetList().
virtual G4double G4V3DNucleus::CoulombBarrier () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4BinaryCascade::CheckPauliPrinciple().
virtual void G4V3DNucleus::DoLorentzBoost (const G4LorentzVector & theBoost) pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4QGSParticipants::DoLorentzBoost(), and G4FTFModel::Init().
virtual void G4V3DNucleus::DoLorentzBoost (const G4ThreeVector & theBeta) pure virtual
Implemented in G4Fancy3DNucleus.
virtual void G4V3DNucleus::DoLorentzContraction (const G4LorentzVector & theBoost) pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4FTFModel::Init().
virtual void G4V3DNucleus::DoLorentzContraction (const G4ThreeVector & theBeta) pure virtual
Implemented in G4Fancy3DNucleus.
virtual void G4V3DNucleus::DoTranslation (const G4ThreeVector & theShift) pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4FTFParticipants::GetList().
virtual G4int G4V3DNucleus::GetCharge () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4QGSParticipants::BuildInteractions(), G4BinaryCascade::BuildTargetList(), G4BinaryCascade::CheckChargeAndBaryonNumber(), G4BinaryCascade::CheckPauliPrinciple(), G4InuclNuclei::copy(), G4IntraNucleiCascader::createTarget(), G4CascadeInterface::createTarget(), G4NeutronField::G4NeutronField(), G4ProtonField::G4ProtonField(), G4SigmaPlusField::GetBarrier(), G4SigmaMinusField::GetBarrier(), G4PionPlusField::GetBarrier(), G4AntiProtonField::GetBarrier(), G4KaonMinusField::GetBarrier(), G4KaonPlusField::GetBarrier(), G4PionMinusField::GetBarrier(), G4BinaryCascade::GetExcitationEnergy(), G4SigmaPlusField::GetField(), G4SigmaMinusField::GetField(), G4SigmaZeroField::GetField(), G4KaonZeroField::GetField(), G4AntiProtonField::GetField(), G4PionPlusField::GetField(), G4KaonMinusField::GetField(), G4KaonPlusField::GetField(), G4PionZeroField::GetField(), G4PionMinusField::GetField(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4CascadeInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), and G4KM_OpticalEqRhs::SetFactor().
virtual G4double G4V3DNucleus::GetMass () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4RKPropagation::FieldTransport(), G4BinaryCascade::Propagate(), G4QuasiElasticChannel::Scatter(), and G4RKPropagation::Transport().
virtual G4int G4V3DNucleus::GetMassNumber () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4TheoFSGenerator::ApplyYourself(), G4QGSParticipants::BuildInteractions(), G4BinaryCascade::BuildTargetList(), G4BinaryCascade::CheckChargeAndBaryonNumber(), G4BinaryCascade::CheckPauliPrinciple(), G4InuclNuclei::copy(), G4IntraNucleiCascader::createTarget(), G4CascadeInterface::createTarget(), G4BinaryCascade::FindFragments(), G4KM_NucleonEqRhs::G4KM_NucleonEqRhs(), G4NeutronField::G4NeutronField(), G4ProtonField::G4ProtonField(), G4SigmaPlusField::GetBarrier(), G4SigmaMinusField::GetBarrier(), G4PionPlusField::GetBarrier(), G4AntiProtonField::GetBarrier(), G4KaonMinusField::GetBarrier(), G4KaonPlusField::GetBarrier(), G4PionMinusField::GetBarrier(), G4BinaryCascade::GetExcitationEnergy(), G4SigmaPlusField::GetField(), G4SigmaMinusField::GetField(), G4KaonZeroField::GetField(), G4SigmaZeroField::GetField(), G4AntiProtonField::GetField(), G4PionPlusField::GetField(), G4KaonMinusField::GetField(), G4PionZeroField::GetField(), G4KaonPlusField::GetField(), G4PionMinusField::GetField(), G4QGSParticipants::GetList(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4CascadeInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), and G4KM_OpticalEqRhs::SetFactor().
virtual G4Nucleon* G4V3DNucleus::GetNextNucleon () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4QGSParticipants::BuildInteractions(), G4BinaryCascade::BuildTargetList(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4InuclNuclei::copy(), G4IntraNucleiCascader::copyWoundedNucleus(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::Init(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4VPartonStringModel::Scatter(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), G4QGSParticipants::StoreInvolvedNucleon(), and G4FTFModel::StoreInvolvedNucleon().
virtual const G4VNuclearDensity* G4V3DNucleus::GetNuclearDensity () const pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4BinaryCascade::CheckPauliPrinciple(), G4KM_NucleonEqRhs::EvaluateRhsGivenB(), G4KM_OpticalEqRhs::EvaluateRhsGivenB(), G4SigmaPlusField::GetField(), G4KaonZeroField::GetField(), G4SigmaMinusField::GetField(), G4SigmaZeroField::GetField(), G4AntiProtonField::GetField(), G4PionPlusField::GetField(), G4PionZeroField::GetField(), G4KaonPlusField::GetField(), G4KaonMinusField::GetField(), and G4PionMinusField::GetField().
virtual G4double G4V3DNucleus::GetNuclearRadius () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4GeneratorPrecompoundInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
virtual G4double G4V3DNucleus::GetNuclearRadius (const G4double maxRelativeDensity) pure virtual
Implemented in G4Fancy3DNucleus.
virtual const std::vector<G4Nucleon>& G4V3DNucleus::GetNucleons () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4TheoFSGenerator::ApplyYourself(), and G4QuasiElasticChannel::Scatter().
virtual G4double G4V3DNucleus::GetOuterRadius () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4BinaryCascade::ApplyYourself(), G4NeutronField::G4NeutronField(), G4ProtonField::G4ProtonField(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4RKPropagation::Init(), G4BinaryCascade::Propagate(), and G4VPartonStringModel::Scatter().
virtual void G4V3DNucleus::Init (G4int theA, G4int theZ) pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4BinaryCascade::ApplyYourself(), G4VParticipants::Init(), G4VParticipants::InitProjectileNucleus(), G4QGSParticipants::PrepareInitialState(), and G4QuasiElasticChannel::Scatter().
G4bool G4V3DNucleus::operator!= (const G4V3DNucleus & right) const private
Definition at line 58 of file G4V3DNucleus.cc.
View newest version in sPHENIX GitHub at line 58 of file G4V3DNucleus.cc
const G4V3DNucleus & G4V3DNucleus::operator= (const G4V3DNucleus & right) private
Definition at line 45 of file G4V3DNucleus.cc.
View newest version in sPHENIX GitHub at line 45 of file G4V3DNucleus.cc
G4bool G4V3DNucleus::operator== (const G4V3DNucleus & right) const private
Definition at line 53 of file G4V3DNucleus.cc.
View newest version in sPHENIX GitHub at line 53 of file G4V3DNucleus.cc
std::pair<G4double, G4double> G4V3DNucleus::RefetchImpactXandY () inline
Definition at line 76 of file G4V3DNucleus.hh.
View newest version in sPHENIX GitHub at line 76 of file G4V3DNucleus.hh
References theImpactParameter.
virtual void G4V3DNucleus::SortNucleonsDecZ () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4VParticipants::InitProjectileNucleus().
virtual void G4V3DNucleus::SortNucleonsIncZ () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4VParticipants::Init(), and G4QGSParticipants::PrepareInitialState().
virtual G4bool G4V3DNucleus::StartLoop () pure virtual
Implemented in G4Fancy3DNucleus.
Referenced by G4QGSParticipants::BuildInteractions(), G4BinaryCascade::BuildTargetList(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4InuclNuclei::copy(), G4IntraNucleiCascader::copyWoundedNucleus(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::Init(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4VPartonStringModel::Scatter(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), G4QGSParticipants::StoreInvolvedNucleon(), and G4FTFModel::StoreInvolvedNucleon().
Member Data Documentation
std::pair<G4double, G4double> G4V3DNucleus::theImpactParameter private
Definition at line 80 of file G4V3DNucleus.hh.
View newest version in sPHENIX GitHub at line 80 of file G4V3DNucleus.hh
Referenced by ChooseImpactXandY(), and RefetchImpactXandY().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4V3DNucleus.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4V3DNucleus.cc