ECCE @ EIC Software: G4VModel Class Reference
G4VModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VModel.hh>
Public Member Functions
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
virtual void DescribeYourselfTo (G4VGraphicsScene &)=0
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Protected Attributes
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Private Member Functions
G4VModel (const G4VModel &)
G4VModel & operator= (const G4VModel &)
Friends
std::ostream & operator<< (std::ostream &os, const G4VModel &)
Detailed Description
Definition at line 52 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VModel.hh
Constructor & Destructor Documentation
G4VModel::G4VModel (const G4Transform3D & modelTransformation = G4Transform3D(), const G4ModelingParameters * pMP = 0)
Definition at line 37 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VModel.cc
G4VModel::~G4VModel () virtual
Definition at line 46 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VModel.cc
G4VModel::G4VModel (const G4VModel &) private
Member Function Documentation
virtual void G4VModel::DescribeYourselfTo (G4VGraphicsScene &) pure virtual
Implemented in G4PhysicalVolumeModel, CexmcScenePrimitives, G4LogicalVolumeModel, G4VFieldModel, G4CallbackModel< F >, G4AxesModel, G4TrajectoriesModel, G4ArrowModel, G4DigiModel, G4GPSModel, G4HitsModel, G4ScaleModel, G4TextModel, G4PSHitsModel, and G4NullModel.
Referenced by G4AxesModel::DescribeYourselfTo().
G4String G4VModel::GetCurrentDescription () const virtual
Reimplemented in G4PhysicalVolumeModel, and G4GPSModel.
Definition at line 53 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VModel.cc
References fGlobalDescription.
G4String G4VModel::GetCurrentTag () const virtual
Reimplemented in G4PhysicalVolumeModel, and G4GPSModel.
Definition at line 48 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VModel.cc
References fGlobalTag.
const G4VisExtent& G4VModel::GetExtent () const
Referenced by G4PhysicalVolumeModel::CalculateExtent(), and G4VisCommandSceneAddLogicalVolume::SetNewValue().
const G4String& G4VModel::GetGlobalDescription () const
Referenced by G4VisCommandSceneAddScale::SetNewValue().
const G4String& G4VModel::GetGlobalTag () const
Referenced by G4Scene::AddRunDurationModel().
const G4ModelingParameters* G4VModel::GetModelingParameters () const
Referenced by G4ASCIITreeSceneHandler::EndModeling().
const G4Transform3D& G4VModel::GetTransformation () const
Referenced by G4VSceneHandler::AddPrimitive().
const G4VisExtent & G4VModel::GetTransformedExtent () const
Definition at line 58 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VModel.cc
References fExtent, fTransform, and G4VisExtent::Transform().
const G4String& G4VModel::GetType () const
G4VModel& G4VModel::operator= (const G4VModel &) private
void G4VModel::SetExtent (const G4VisExtent &)
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
void G4VModel::SetGlobalDescription (const G4String &)
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), CexmcScenePrimitives::CexmcScenePrimitives(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
void G4VModel::SetGlobalTag (const G4String &)
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
void G4VModel::SetModelingParameters (const G4ModelingParameters *)
Referenced by G4LogicalVolumeModel::DescribeYourselfTo(), G4ASCIITreeSceneHandler::EndModeling(), G4TouchableUtils::FindTouchableProperties(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), and G4PhysicalVolumeModel::Validate().
void G4VModel::SetTransformation (const G4Transform3D &)
Referenced by G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
void G4VModel::SetType (const G4String &)
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
G4bool G4VModel::Validate (G4bool warn = true) virtual
Reimplemented in G4PhysicalVolumeModel, and G4LogicalVolumeModel.
Definition at line 65 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VModel.cc
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4VModel & model) friend
Definition at line 69 of file G4VModel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4VModel.cc
Member Data Documentation
G4VisExtent G4VModel::fExtent protected
Definition at line 113 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VModel.hh
Referenced by G4PhysicalVolumeModel::CalculateExtent(), GetTransformedExtent(), and operator<<().
G4String G4VModel::fGlobalDescription protected
Definition at line 112 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VModel.hh
Referenced by G4DigiModel::G4DigiModel(), G4GPSModel::G4GPSModel(), G4HitsModel::G4HitsModel(), G4PSHitsModel::G4PSHitsModel(), G4ScaleModel::G4ScaleModel(), G4TextModel::G4TextModel(), G4TrajectoriesModel::G4TrajectoriesModel(), GetCurrentDescription(), and operator<<().
G4String G4VModel::fGlobalTag protected
Definition at line 111 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VModel.hh
Referenced by G4DigiModel::G4DigiModel(), G4GPSModel::G4GPSModel(), G4HitsModel::G4HitsModel(), G4PSHitsModel::G4PSHitsModel(), G4ScaleModel::G4ScaleModel(), G4TextModel::G4TextModel(), G4TrajectoriesModel::G4TrajectoriesModel(), GetCurrentTag(), and G4PhysicalVolumeModel::GetCurrentTag().
const G4ModelingParameters* G4VModel::fpMP protected
Definition at line 115 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VModel.hh
Referenced by G4PhysicalVolumeModel::CalculateExtent(), G4DigiModel::DescribeYourselfTo(), G4HitsModel::DescribeYourselfTo(), G4TrajectoriesModel::DescribeYourselfTo(), G4CallbackModel< F >::DescribeYourselfTo(), operator<<(), and G4PhysicalVolumeModel::Validate().
G4Transform3D G4VModel::fTransform protected
Definition at line 114 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VModel.hh
Referenced by G4PhysicalVolumeModel::CalculateExtent(), G4CallbackModel< F >::DescribeYourselfTo(), GetTransformedExtent(), and operator<<().
G4String G4VModel::fType protected
Definition at line 110 of file G4VModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VModel.hh
Referenced by G4DigiModel::G4DigiModel(), G4GPSModel::G4GPSModel(), G4HitsModel::G4HitsModel(), G4PSHitsModel::G4PSHitsModel(), G4ScaleModel::G4ScaleModel(), G4TextModel::G4TextModel(), and G4TrajectoriesModel::G4TrajectoriesModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4VModel.cc