ECCE @ EIC Software: G4PreCompoundTransitions Class Reference
G4PreCompoundTransitions Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundTransitions.hh>
Public Member Functions
G4PreCompoundTransitions ()
virtual ~G4PreCompoundTransitions ()
virtual G4double CalculateProbability (const G4Fragment &aFragment)
virtual void PerformTransition (G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundTransitions
G4VPreCompoundTransitions ()
virtual ~G4VPreCompoundTransitions ()
G4double GetTransitionProb1 () const
G4double GetTransitionProb2 () const
G4double GetTransitionProb3 () const
void UseNGB (G4bool use)
void UseCEMtr (G4bool use)
Private Member Functions
G4PreCompoundTransitions (const G4PreCompoundTransitions &)
const G4PreCompoundTransitions & operator= (const G4PreCompoundTransitions &right)
G4bool operator== (const G4PreCompoundTransitions &right) const
G4bool operator!= (const G4PreCompoundTransitions &right) const
Private Attributes
const G4ParticleDefinition * proton
G4NuclearLevelData * fNuclData
G4double FermiEnergy
G4double r0
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundTransitions
G4bool useNGB
G4bool useCEMtr
G4double TransitionProb1
G4double TransitionProb2
G4double TransitionProb3
Detailed Description
Definition at line 50 of file G4PreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 50 of file G4PreCompoundTransitions.hh
Constructor & Destructor Documentation
G4PreCompoundTransitions::G4PreCompoundTransitions ()
Definition at line 58 of file G4PreCompoundTransitions.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PreCompoundTransitions.cc
References FermiEnergy, fNuclData, G4DeexPrecoParameters::GetFermiEnergy(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::GetTransitionsR0(), G4Proton::Proton(), proton, and r0.
G4PreCompoundTransitions::~G4PreCompoundTransitions () virtual
Definition at line 67 of file G4PreCompoundTransitions.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PreCompoundTransitions.cc
G4PreCompoundTransitions::G4PreCompoundTransitions (const G4PreCompoundTransitions &) private
Member Function Documentation
G4double G4PreCompoundTransitions::CalculateProbability (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundTransitions.
Definition at line 73 of file G4PreCompoundTransitions.cc.
View newest version in sPHENIX GitHub at line 73 of file G4PreCompoundTransitions.cc
References A(), CLHEP::c_light, e, eV, FermiEnergy, fNuclData, G4Exp(), G4Log(), G4UniformRand, GE, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetZ_asInt(), H, CLHEP::hbarc, max, CLHEP::millibarn, N, CLHEP::neutron_mass_c2, P, CLHEP::pi, CLHEP::pi2, CLHEP::proton_mass_c2, r0, G4VPreCompoundTransitions::TransitionProb1, G4VPreCompoundTransitions::TransitionProb2, G4VPreCompoundTransitions::TransitionProb3, G4VPreCompoundTransitions::useCEMtr, G4VPreCompoundTransitions::useNGB, x, x1, xx, and Z.
G4bool G4PreCompoundTransitions::operator!= (const G4PreCompoundTransitions & right) const private
const G4PreCompoundTransitions& G4PreCompoundTransitions::operator= (const G4PreCompoundTransitions & right) private
G4bool G4PreCompoundTransitions::operator== (const G4PreCompoundTransitions & right) const private
void G4PreCompoundTransitions::PerformTransition (G4Fragment & aFragment) virtual
Implements G4VPreCompoundTransitions.
Definition at line 210 of file G4PreCompoundTransitions.cc.
View newest version in sPHENIX GitHub at line 210 of file G4PreCompoundTransitions.cc
References A(), G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetZ_asInt(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), G4Fragment::SetNumberOfParticles(), G4VPreCompoundTransitions::TransitionProb1, G4VPreCompoundTransitions::TransitionProb2, G4VPreCompoundTransitions::TransitionProb3, and Z.
Member Data Documentation
G4double G4PreCompoundTransitions::FermiEnergy private
Definition at line 72 of file G4PreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PreCompoundTransitions.hh
Referenced by CalculateProbability(), and G4PreCompoundTransitions().
G4NuclearLevelData* G4PreCompoundTransitions::fNuclData private
Definition at line 70 of file G4PreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PreCompoundTransitions.hh
Referenced by CalculateProbability(), and G4PreCompoundTransitions().
const G4ParticleDefinition* G4PreCompoundTransitions::proton private
Definition at line 69 of file G4PreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PreCompoundTransitions.hh
Referenced by G4PreCompoundTransitions().
G4double G4PreCompoundTransitions::r0 private
Definition at line 73 of file G4PreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PreCompoundTransitions.hh
Referenced by CalculateProbability(), and G4PreCompoundTransitions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundTransitions.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4PreCompoundTransitions.cc