ECCE @ EIC Software: MyGamma Class Reference
MyGamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/Gamma.hh>
Public Member Functions
MyGamma ()
~MyGamma ()
double Gamma (double z)
double Gamma (double a, double x)
Private Member Functions
double GamCf (double a, double x)
double GamSer (double a, double x)
Static Private Member Functions
static short Abs (short d)
static int Abs (int d)
static long Abs (long d)
static float Abs (float d)
static double Abs (double d)
static double LnGamma (double z)
static double Log (double x)
static double Exp (double x)
Detailed Description
Definition at line 45 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 45 of file Gamma.hh
Constructor & Destructor Documentation
MyGamma::MyGamma ()
Definition at line 36 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 36 of file Gamma.cc
MyGamma::~MyGamma ()
Definition at line 38 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 38 of file Gamma.cc
Member Function Documentation
static short MyGamma::Abs (short d) inline static private
Definition at line 61 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 61 of file Gamma.hh
References d.
Referenced by GamCf(), and GamSer().
static int MyGamma::Abs (int d) inline static private
Definition at line 62 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 62 of file Gamma.hh
References d.
static long MyGamma::Abs (long d) inline static private
Definition at line 63 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 63 of file Gamma.hh
References d.
static float MyGamma::Abs (float d) inline static private
Definition at line 64 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 64 of file Gamma.hh
References d.
static double MyGamma::Abs (double d) inline static private
Definition at line 65 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 65 of file Gamma.hh
References d.
static double MyGamma::Exp (double x) inline static private
Definition at line 68 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 68 of file Gamma.hh
Referenced by GamCf(), and GamSer().
double MyGamma::GamCf (double a, double x) private
Definition at line 75 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 75 of file Gamma.cc
References a, Abs(), G4InuclParticleNames::an, b, c, d, eps, Exp(), Acts::UnitConstants::h, LnGamma(), Log(), and v.
Referenced by Gamma().
double MyGamma::Gamma (double z)
Definition at line 41 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 41 of file Gamma.cc
References LnGamma(), and v.
Referenced by GVFlashShowerParameterisation::gam().
double MyGamma::Gamma (double a, double x)
Definition at line 59 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 59 of file Gamma.cc
References GamCf(), and GamSer().
double MyGamma::GamSer (double a, double x) private
Definition at line 115 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 115 of file Gamma.cc
References a, Abs(), G4InuclParticleNames::ap, eps, Exp(), LnGamma(), Log(), n, sum, and v.
Referenced by Gamma().
double MyGamma::LnGamma (double z) static private
Definition at line 146 of file Gamma.cc.
View newest version in sPHENIX GitHub at line 146 of file Gamma.cc
References c, Log(), tmp, v, x, y, and z.
Referenced by GamCf(), Gamma(), and GamSer().
static double MyGamma::Log (double x) inline static private
Definition at line 67 of file Gamma.hh.
View newest version in sPHENIX GitHub at line 67 of file Gamma.hh
Referenced by GamCf(), GamSer(), and LnGamma().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/Gamma.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/Gamma.cc