ECCE @ EIC Software: CexmcScenePrimitives Class Reference
CexmcScenePrimitives Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcScenePrimitives.hh>
Classes
struct CexmcRadialLine
Public Member Functions
CexmcScenePrimitives (CexmcSetup *setup)
~CexmcScenePrimitives ()
void DescribeYourselfTo (G4VGraphicsScene &scene)
void MarkTargetCenter (G4bool on=true)
void DrawRadialLine (const G4ThreeVector &line)
void HighlightInnerCrystals (G4bool=true)
void ClearRadialLines (void)
void SetColour (CexmcSPType primitive, const G4Colour &colour)
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Private Types
typedef std::vector
< CexmcRadialLine > CexmcRadialLines
typedef std::map< CexmcSPType,
G4Colour > CexmcSPColourMap
Private Member Functions
void DrawRadialLine (G4VGraphicsScene &scene, const CexmcRadialLine *rLine)
void MarkTargetCenter (G4VGraphicsScene &scene)
void HighlightInnerCrystals (G4VGraphicsScene &scene)
void UpdateScene (void)
Private Attributes
CexmcSetup * setup
G4bool markTargetCenter
G4bool highlightInnerCrystals
CexmcRadialLines radialLines
CexmcSPColourMap spColours
CexmcScenePrimitivesMessenger * messenger
Additional Inherited Members
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 67 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 67 of file CexmcScenePrimitives.hh
Member Typedef Documentation
typedef std::vector< CexmcRadialLine > CexmcScenePrimitives::CexmcRadialLines private
Definition at line 83 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 83 of file CexmcScenePrimitives.hh
typedef std::map< CexmcSPType, G4Colour > CexmcScenePrimitives::CexmcSPColourMap private
Definition at line 85 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcScenePrimitives.hh
Constructor & Destructor Documentation
CexmcScenePrimitives::CexmcScenePrimitives (CexmcSetup * setup) explicit
Definition at line 71 of file CexmcScenePrimitives.cc.
View newest version in sPHENIX GitHub at line 71 of file CexmcScenePrimitives.cc
References CexmcInnerCrystalsHl_SP, CexmcRadialLine_SP, CexmcScenePrimitivesDescription, CexmcTargetCenterMark_SP, messenger, G4VModel::SetGlobalDescription(), and spColours.
CexmcScenePrimitives::~CexmcScenePrimitives ()
Definition at line 83 of file CexmcScenePrimitives.cc.
View newest version in sPHENIX GitHub at line 83 of file CexmcScenePrimitives.cc
References messenger.
Member Function Documentation
void CexmcScenePrimitives::ClearRadialLines (void) inline
Definition at line 161 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 161 of file CexmcScenePrimitives.hh
References radialLines, and UpdateScene().
Referenced by CexmcScenePrimitivesMessenger::SetNewValue().
void CexmcScenePrimitives::DescribeYourselfTo (G4VGraphicsScene & scene) virtual
Implements G4VModel.
Definition at line 89 of file CexmcScenePrimitives.cc.
View newest version in sPHENIX GitHub at line 89 of file CexmcScenePrimitives.cc
References DrawRadialLine(), HighlightInnerCrystals(), highlightInnerCrystals, k, MarkTargetCenter(), markTargetCenter, and radialLines.
void CexmcScenePrimitives::DrawRadialLine (const G4ThreeVector & line) inline
Definition at line 140 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 140 of file CexmcScenePrimitives.hh
References radialLines, and UpdateScene().
Referenced by DescribeYourselfTo(), and CexmcScenePrimitivesMessenger::SetNewValue().
void CexmcScenePrimitives::DrawRadialLine (G4VGraphicsScene & scene, const CexmcRadialLine * rLine) private
Definition at line 120 of file CexmcScenePrimitives.cc.
View newest version in sPHENIX GitHub at line 120 of file CexmcScenePrimitives.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives(), CexmcRadialLine_SP, cm, deg, G4VGraphicsScene::EndPrimitives(), G4VMarker::filled, CexmcSetup::GetTargetTransform(), BTOF::length, CexmcScenePrimitives::CexmcRadialLine::length, CexmcScenePrimitives::CexmcRadialLine::phi, phi, G4VMarker::SetFillStyle(), G4VisAttributes::SetLineWidth(), G4VMarker::SetScreenSize(), setup, G4Visible::SetVisAttributes(), spColours, CexmcScenePrimitives::CexmcRadialLine::theta, theta(), and Acts::Test::transform.
void CexmcScenePrimitives::HighlightInnerCrystals (G4bool on = true) inline
Definition at line 154 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 154 of file CexmcScenePrimitives.hh
References highlightInnerCrystals, and UpdateScene().
Referenced by DescribeYourselfTo(), and CexmcScenePrimitivesMessenger::SetNewValue().
void CexmcScenePrimitives::HighlightInnerCrystals (G4VGraphicsScene & scene) private
Definition at line 154 of file CexmcScenePrimitives.cc.
View newest version in sPHENIX GitHub at line 154 of file CexmcScenePrimitives.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives(), CexmcInnerCrystalsHl_SP, G4VGraphicsScene::EndPrimitives(), CexmcSetup::GetCalorimeterGeometry(), CexmcSetup::GetCalorimeterLeftTransform(), CexmcSetup::GetCalorimeterRightTransform(), G4VisAttributes::SetLineWidth(), setup, G4Visible::SetVisAttributes(), and spColours.
void CexmcScenePrimitives::MarkTargetCenter (G4bool on = true) inline
Definition at line 147 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 147 of file CexmcScenePrimitives.hh
References markTargetCenter, and UpdateScene().
Referenced by DescribeYourselfTo(), and CexmcScenePrimitivesMessenger::SetNewValue().
void CexmcScenePrimitives::MarkTargetCenter (G4VGraphicsScene & scene) private
Definition at line 103 of file CexmcScenePrimitives.cc.
View newest version in sPHENIX GitHub at line 103 of file CexmcScenePrimitives.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives(), CexmcTargetCenterMark_SP, G4VGraphicsScene::EndPrimitives(), G4VMarker::filled, CexmcSetup::GetTargetTransform(), G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), setup, G4Visible::SetVisAttributes(), spColours, and Acts::Test::transform.
void CexmcScenePrimitives::SetColour (CexmcSPType primitive, const G4Colour & colour) inline
Definition at line 133 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 133 of file CexmcScenePrimitives.hh
References spColours.
Referenced by CexmcScenePrimitivesMessenger::SetNewValue().
void CexmcScenePrimitives::UpdateScene (void) inline private
Definition at line 168 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 168 of file CexmcScenePrimitives.hh
References G4VVisManager::GetConcreteInstance(), and G4VVisManager::NotifyHandlers().
Referenced by ClearRadialLines(), DrawRadialLine(), HighlightInnerCrystals(), and MarkTargetCenter().
Member Data Documentation
G4bool CexmcScenePrimitives::highlightInnerCrystals private
Definition at line 122 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 122 of file CexmcScenePrimitives.hh
Referenced by DescribeYourselfTo(), and HighlightInnerCrystals().
G4bool CexmcScenePrimitives::markTargetCenter private
Definition at line 120 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 120 of file CexmcScenePrimitives.hh
Referenced by DescribeYourselfTo(), and MarkTargetCenter().
CexmcScenePrimitivesMessenger* CexmcScenePrimitives::messenger private
Definition at line 129 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 129 of file CexmcScenePrimitives.hh
Referenced by CexmcScenePrimitives(), and ~CexmcScenePrimitives().
CexmcRadialLines CexmcScenePrimitives::radialLines private
Definition at line 124 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 124 of file CexmcScenePrimitives.hh
Referenced by ClearRadialLines(), DescribeYourselfTo(), and DrawRadialLine().
CexmcSetup* CexmcScenePrimitives::setup private
Definition at line 118 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 118 of file CexmcScenePrimitives.hh
Referenced by DrawRadialLine(), HighlightInnerCrystals(), and MarkTargetCenter().
CexmcSPColourMap CexmcScenePrimitives::spColours private
Definition at line 126 of file CexmcScenePrimitives.hh.
View newest version in sPHENIX GitHub at line 126 of file CexmcScenePrimitives.hh
Referenced by CexmcScenePrimitives(), DrawRadialLine(), HighlightInnerCrystals(), MarkTargetCenter(), and SetColour().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcScenePrimitives.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcScenePrimitives.cc