ECCE @ EIC Software: CexmcChargeExchangeProductionModel< OutputParticle > Class Template Reference
CexmcChargeExchangeProductionModel< OutputParticle > Class Template Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcChargeExchangeProductionModel.hh>
Public Member Functions
CexmcChargeExchangeProductionModel ()
~CexmcChargeExchangeProductionModel ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &projectile, G4Nucleus &targetNucleus)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Public Member Functions inherited from CexmcProductionModel
CexmcProductionModel (const G4String &name="unspecified", G4bool fermiMotionIsOn=false)
virtual ~CexmcProductionModel ()
void ApplyFermiMotion (G4bool on, G4bool fromMessenger=true)
void SetAngularRange (G4double top, G4double bottom, G4int nmbOfDivs)
void SetAngularRanges (const CexmcAngularRangeList &angularRanges_)
void AddAngularRange (G4double top, G4double bottom, G4int nmbOfDivs)
void SetProductionModelData (const CexmcProductionModelData &productionModelData_)
void PrintInitialData (void) const
const CexmcAngularRangeList & GetAngularRanges (void) const
const CexmcAngularRangeList & GetTriggeredAngularRanges (void) const
const CexmcProductionModelData & GetProductionModelData (void) const
G4bool IsFermiMotionOn (void) const
void SetTriggeredAngularRanges (G4double opCosThetaSCM)
const G4String & GetName (void) const
G4ParticleDefinition * GetIncidentParticle (void) const
G4ParticleDefinition * GetNucleusParticle (void) const
G4ParticleDefinition * GetOutputParticle (void) const
G4ParticleDefinition * GetNucleusOutputParticle (void) const
Private Attributes
G4double nucleusParticleMass
CexmcPhaseSpaceGenerator * phaseSpaceGenerator
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Member Functions inherited from CexmcProductionModel
virtual void FermiMotionStatusChangeHook (void)
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Protected Attributes inherited from CexmcProductionModel
G4String name
G4bool fermiMotionIsOn
CexmcAngularRangeList angularRanges
CexmcAngularRangeList angularRangesRef
CexmcAngularRangeList triggeredAngularRanges
CexmcProductionModelData productionModelData
G4ParticleDefinition * incidentParticle
G4ParticleDefinition * nucleusParticle
G4ParticleDefinition * outputParticle
G4ParticleDefinition * nucleusOutputParticle
Detailed Description
template<typename OutputParticle>
class CexmcChargeExchangeProductionModel< OutputParticle >
Definition at line 60 of file CexmcChargeExchangeProductionModel.hh.
View newest version in sPHENIX GitHub at line 60 of file CexmcChargeExchangeProductionModel.hh
Constructor & Destructor Documentation
template<typename OutputParticle > CexmcChargeExchangeProductionModel< OutputParticle >::CexmcChargeExchangeProductionModel ()
Definition at line 81 of file CexmcChargeExchangeProductionModel.hh.
View newest version in sPHENIX GitHub at line 81 of file CexmcChargeExchangeProductionModel.hh
References G4PionMinus::Definition(), G4Proton::Definition(), G4Neutron::Definition(), G4ParticleDefinition::GetPDGMass(), CexmcProductionModelData::incidentParticle, CexmcProductionModel::incidentParticle, CexmcProductionModelData::incidentParticleSCM, CexmcProductionModelData::nucleusOutputParticle, CexmcProductionModel::nucleusOutputParticle, CexmcProductionModelData::nucleusOutputParticleSCM, CexmcProductionModelData::nucleusParticle, CexmcProductionModel::nucleusParticle, CexmcChargeExchangeProductionModel< OutputParticle >::nucleusParticleMass, CexmcProductionModelData::nucleusParticleSCM, CexmcProductionModelData::outputParticle, CexmcProductionModel::outputParticle, CexmcProductionModelData::outputParticleSCM, CexmcChargeExchangeProductionModel< OutputParticle >::phaseSpaceGenerator, CexmcProductionModel::productionModelData, and CexmcPhaseSpaceGenerator::SetParticles().
template<typename OutputParticle > CexmcChargeExchangeProductionModel< OutputParticle >::~CexmcChargeExchangeProductionModel ()
Definition at line 124 of file CexmcChargeExchangeProductionModel.hh.
View newest version in sPHENIX GitHub at line 124 of file CexmcChargeExchangeProductionModel.hh
Member Function Documentation
template<typename OutputParticle > G4HadFinalState * CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself (const G4HadProjectile & projectile, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 132 of file CexmcChargeExchangeProductionModel.hh.
View newest version in sPHENIX GitHub at line 132 of file CexmcChargeExchangeProductionModel.hh
References CLHEP::HepLorentzVector::boostVector(), G4HadFinalState::Clear(), G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4Nucleus::GetFermiMomentum(), G4HadProjectile::GetKineticEnergy(), k, CLHEP::HepLorentzVector::setPx(), stopAndKill, CLHEP::HepLorentzVector::transform(), CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Member Data Documentation
template<typename OutputParticle > G4double CexmcChargeExchangeProductionModel< OutputParticle >::nucleusParticleMass private
Definition at line 73 of file CexmcChargeExchangeProductionModel.hh.
View newest version in sPHENIX GitHub at line 73 of file CexmcChargeExchangeProductionModel.hh
Referenced by CexmcChargeExchangeProductionModel< OutputParticle >::CexmcChargeExchangeProductionModel().
template<typename OutputParticle > CexmcPhaseSpaceGenerator* CexmcChargeExchangeProductionModel< OutputParticle >::phaseSpaceGenerator private
Definition at line 75 of file CexmcChargeExchangeProductionModel.hh.
View newest version in sPHENIX GitHub at line 75 of file CexmcChargeExchangeProductionModel.hh
Referenced by CexmcChargeExchangeProductionModel< OutputParticle >::CexmcChargeExchangeProductionModel().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcChargeExchangeProductionModel.hh