ECCE @ EIC Software: G4VFieldModel Class Reference
G4VFieldModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VFieldModel.hh>
Public Types
enum Representation { fullArrow, lightArrow }
Public Member Functions
G4VFieldModel (const G4String &typeOfField, const G4String &symbol="", const G4VisExtent &extentForField=G4VisExtent(), const std::vector< G4PhysicalVolumesSearchScene::Findings > &pvFindings=std::vector< G4PhysicalVolumesSearchScene::Findings >(), G4int nDataPointsPerHalfScene=10, Representation representation=Representation::fullArrow, G4int arrow3DLineSegmentsPerCircle=6)
virtual ~G4VFieldModel ()
virtual void DescribeYourselfTo (G4VGraphicsScene &sceneHandler)
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Protected Member Functions
virtual void GetFieldAtLocation (const G4Field *field, const G4Point3D &position, G4double time, G4Point3D &result) const =0
Private Member Functions
G4VFieldModel (const G4VFieldModel &)
G4VFieldModel & operator= (const G4VFieldModel &)
Private Attributes
G4VisExtent fExtentForField
std::vector
< G4PhysicalVolumesSearchScene::Findings > fPVFindings
G4int fNDataPointsPerMaxHalfScene
Representation fRepresentation
G4int fArrow3DLineSegmentsPerCircle
G4String fTypeOfField
G4String fArrowPrefix
Additional Inherited Members
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 46 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VFieldModel.hh
Member Enumeration Documentation
enum G4VFieldModel::Representation
Enumerator:
fullArrow
lightArrow
Definition at line 50 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VFieldModel.hh
Constructor & Destructor Documentation
G4VFieldModel::G4VFieldModel (const G4String & typeOfField, const G4String & symbol = "", const G4VisExtent & extentForField = G4VisExtent(), const std::vector< G4PhysicalVolumesSearchScene::Findings > & pvFindings = std::vector<G4PhysicalVolumesSearchScene::Findings>(), G4int nDataPointsPerHalfScene = 10, Representation representation = Representation::fullArrow, G4int arrow3DLineSegmentsPerCircle = 6)
Definition at line 61 of file G4VFieldModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VFieldModel.cc
References G4VisExtent::GetNullExtent().
G4VFieldModel::~G4VFieldModel () virtual
Definition at line 58 of file G4VFieldModel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VFieldModel.cc
G4VFieldModel::G4VFieldModel (const G4VFieldModel &) private
Member Function Documentation
void G4VFieldModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 109 of file G4VFieldModel.cc.
View newest version in sPHENIX GitHub at line 109 of file G4VFieldModel.cc
References G4VGraphicsScene::AddPrimitive(), alpha, G4VGraphicsScene::BeginPrimitives(), G4VSolid::ComputeDimensions(), G4ArrowModel::DescribeYourselfTo(), G4FieldManager::DoesFieldExist(), G4VGraphicsScene::EndPrimitives(), f, fArrow3DLineSegmentsPerCircle, fArrowPrefix, fExtentForField, fNDataPointsPerMaxHalfScene, fPVFindings, fRepresentation, fTypeOfField, G4cout, G4endl, G4FieldManager::GetDetectorField(), G4VGraphicsScene::GetExtent(), GetFieldAtLocation(), G4TransportationManager::GetFieldManager(), G4Region::GetFieldManager(), G4LogicalVolume::GetFieldManager(), G4VPhysicalVolume::GetLogicalVolume(), G4TransportationManager::GetNavigatorForTracking(), G4VisExtent::GetNullExtent(), G4PVParameterised::GetParameterisation(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSolid(), G4TransportationManager::GetTransportationManager(), G4VisExtent::GetXmax(), G4VisExtent::GetXmin(), G4VisExtent::GetYmax(), G4VisExtent::GetYmin(), G4VisExtent::GetZmax(), G4VisExtent::GetZmin(), G4VSolid::Inside(), k, kInside, G4Navigator::LocateGlobalPointAndSetup(), max, Acts::Test::navigator, pos(), G4VisAttributes::SetLineWidth(), G4Visible::SetVisAttributes(), Acts::VectorHelpers::time(), Acts::Test::transform, CLHEP::Hep3Vector::transform(), x, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), y, HepGeom::BasicVector3D< T >::z(), and z.
virtual void G4VFieldModel::GetFieldAtLocation (const G4Field * field, const G4Point3D & position, G4double time, G4Point3D & result) const protected pure virtual
Implemented in G4MagneticFieldModel, and G4ElectricFieldModel.
Referenced by DescribeYourselfTo().
G4VFieldModel& G4VFieldModel::operator= (const G4VFieldModel &) private
Member Data Documentation
G4int G4VFieldModel::fArrow3DLineSegmentsPerCircle private
Definition at line 102 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
G4String G4VFieldModel::fArrowPrefix private
Definition at line 104 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
G4VisExtent G4VFieldModel::fExtentForField private
Definition at line 86 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
G4int G4VFieldModel::fNDataPointsPerMaxHalfScene private
Definition at line 94 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
std::vector<G4PhysicalVolumesSearchScene::Findings> G4VFieldModel::fPVFindings private
Definition at line 89 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
Representation G4VFieldModel::fRepresentation private
Definition at line 101 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
G4String G4VFieldModel::fTypeOfField private
Definition at line 103 of file G4VFieldModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VFieldModel.hh
Referenced by DescribeYourselfTo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VFieldModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4VFieldModel.cc