ECCE @ EIC Software: G4INCL::CrossSectionsMultiPionsAndResonances Class Reference
G4INCL::CrossSectionsMultiPionsAndResonances Class Reference
Multipion and mesonic Resonances cross sections.
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsMultiPionsAndResonances.hh>
Public Member Functions
CrossSectionsMultiPionsAndResonances ()
virtual G4double elastic (Particle const *const p1, Particle const *const p2)
new elastic particle-particle cross section
virtual G4double total (Particle const *const p1, Particle const *const p2)
new total particle-particle cross section
virtual G4double piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - piN Channel (modified due to the mesonic resonances)
virtual G4double piNToEtaN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance production - piN Channel.
virtual G4double piNToOmegaN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->OmegaN.
virtual G4double piNToEtaPrimeN (Particle const *const p1, Particle const *const p2)
Cross section for PiN->EtaPrimeN.
virtual G4double etaNToPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - piN Channel.
virtual G4double omegaNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for OmegaN->PiN.
virtual G4double etaPrimeNToPiN (Particle const *const p1, Particle const *const p2)
Cross section for EtaPrimeN->PiN.
virtual G4double etaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
virtual G4double NNToNNEta (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (inclusive) - NN entrance channel.
virtual G4double NNToNNEtaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNOmega (Particle const *const particle1, Particle const *const particle2)
Cross section for Omega production (inclusive) - NN entrance channel.
virtual G4double NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2)
Cross section for Omega production (exclusive) - NN entrance channel.
virtual G4double NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NN Channel.
virtual G4double NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNEta Channel.
virtual G4double NNToNDeltaEta (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNEta Channel.
virtual G4double NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Cross section for X pion production - NNOmega Channel.
virtual G4double NNToNDeltaOmega (Particle const *const p1, Particle const *const p2)
Cross section for N-Delta-Eta production - NNOmega Channel.
Public Member Functions inherited from G4INCL::CrossSectionsMultiPions
CrossSectionsMultiPions ()
virtual G4double NDeltaToNN (Particle const *const p1, Particle const *const p2)
Cross section for NDelta->NN.
virtual G4double NNToNDelta (Particle const *const p1, Particle const *const p2)
Cross section for Delta production - NN Channel.
virtual G4double piNToDelta (Particle const *const p1, Particle const *const p2)
Cross section for Delta production - piN Channel.
virtual G4double calculateNNAngularSlope (G4double energyCM, G4int iso)
Calculate the slope of the NN DDXS.
virtual G4double NYelastic (Particle const *const p1, Particle const *const p2)
elastic scattering for Nucleon-Strange Particles cross sections
virtual G4double NKbelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NKelastic (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Nucleon to Stange particles cross sections.
virtual G4double NNToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NNToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NNToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNLK (Particle const *const p1, Particle const *const p2)
Nucleon-Delta to Stange particles cross sections.
virtual G4double NDeltaToNSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2)
virtual G4double NDeltaToNNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK (Particle const *const p1, Particle const *const p2)
Nucleon-Pion to Stange particles cross sections.
virtual G4double NpiToSK (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSzKz (Particle const *const p1, Particle const *const p2)
virtual G4double p_pimToSmKp (Particle const *const p1, Particle const *const p2)
virtual G4double p_pizToSzKp (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToLK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToSK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToNKKb (Particle const *const p1, Particle const *const p2)
virtual G4double NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2)
virtual G4double NLToNS (Particle const *const p1, Particle const *const p2)
Nucleon-Hyperon cross sections.
virtual G4double NSToNL (Particle const *const p1, Particle const *const p2)
virtual G4double NSToNS (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK (Particle const *const p1, Particle const *const p2)
Nucleon-Kaon quasi-elastic and inelastic cross sections.
virtual G4double NKToNKpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKToNK2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb (Particle const *const p1, Particle const *const p2)
Nucleon-antiKaon quasi-elastic and inelastic cross sections.
virtual G4double NKbToSpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToLpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToS2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToL2pi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKbpi (Particle const *const p1, Particle const *const p2)
virtual G4double NKbToNKb2pi (Particle const *const p1, Particle const *const p2)
Public Member Functions inherited from G4INCL::ICrossSections
ICrossSections ()
virtual ~ICrossSections ()
Protected Member Functions
G4double piMinuspToEtaN (Particle const *const p1, Particle const *const p2)
Internal function for pion cross sections.
G4double piMinuspToEtaN (const G4double ECM)
G4double piMinuspToOmegaN (Particle const *const p1, Particle const *const p2)
G4double piMinuspToOmegaN (const G4double ECM)
virtual G4double NNToNNEtaIso (const G4double ener, const G4int iso)
Cross section for One (more) pion production - piN entrance channel.
virtual G4double NNToNNEtaExcluIso (const G4double ener, const G4int iso)
Isotopic Cross section for Eta production (exclusive) - NN entrance channel.
virtual G4double NNToNNEtaOnePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNEta channel.
virtual G4double NNToNNEtaOnePiOrDelta (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNEta channel.
virtual G4double NNToNNEtaTwoPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 2-pion production - NNEta channel.
virtual G4double NNToNNEtaThreePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 3-pion production - NNEta channel.
virtual G4double NNToNNEtaFourPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 4-pion production - NNEta channel.
virtual G4double NNToNNOmegaIso (const G4double ener, const G4int iso)
Isotopic Cross section for Omega production (inclusive) - NN entrance channel.
virtual G4double NNToNNOmegaExcluIso (const G4double ener, const G4int iso)
Isotopic Cross section for Omega production (exclusive) - NN entrance channel.
virtual G4double NNToNNOmegaOnePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNOmega channel.
virtual G4double NNToNNOmegaOnePiOrDelta (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NNOmega channel.
virtual G4double NNToNNOmegaTwoPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 2-pion production - NNOmega channel.
virtual G4double NNToNNOmegaThreePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 3-pion production - NNOmega channel.
virtual G4double NNToNNOmegaFourPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 4-pion production - NNOmega channel.
virtual G4double etaNElastic (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - elastic Channel.
virtual G4double omegaNElastic (Particle const *const p1, Particle const *const p2)
virtual G4double omegaNInelastic (Particle const *const p1, Particle const *const p2)
Cross sections for mesonic resonance absorption on nucleon - inelastic Channel.
virtual G4double omegaNToPiPiN (Particle const *const p1, Particle const *const p2)
Cross sections for omega-induced 2Pi emission on nucleon.
Protected Member Functions inherited from G4INCL::CrossSectionsMultiPions
G4double NNElastic (Particle const *const part1, Particle const *const part2)
Internal implementation of the NN elastic cross section.
G4double NNElasticFixed (const G4double s, const G4int i)
Internal implementation of the NN elastic cross section with fixed isospin.
G4double NNTot (Particle const *const part1, Particle const *const part2)
Internal implementation of the NN total cross section.
G4double NNTotFixed (const G4double s, const G4int i)
Internal implementation of the NN total cross section with fixed isospin.
G4double NNInelasticIso (const G4double ener, const G4int iso)
Internal implementation of the isospin dependent NN reaction cross section.
virtual G4double NNOnePiOrDelta (const G4double ener, const G4int iso, const G4double xsiso)
Cross section for direct 1-pion production + delta production - NN entrance channel.
virtual G4double NNTwoPi (const G4double ener, const G4int iso, const G4double xsiso)
Cross section for direct 2-pion production - NN entrance channel.
virtual G4double NNThreePi (const G4double ener, const G4int iso, const G4double xsiso, const G4double xs1pi, const G4double xs2pi)
Cross section for direct 3-pion production - NN entrance channel.
virtual G4double NNOnePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NN entrance channel.
virtual G4double NNOnePiOrDelta (Particle const *const part1, Particle const *const part2)
Cross section for direct 1-pion production - NN entrance channel.
virtual G4double NNTwoPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 2-pion production - NN entrance channel.
virtual G4double NNThreePi (Particle const *const part1, Particle const *const part2)
Cross section for direct 3-pion production - NN entrance channel.
virtual G4double NNFourPi (Particle const *const part1, Particle const *const part2)
Cross section for direct 4-pion production - NN entrance channel.
G4double spnPiPlusPHE (const G4double x)
Internal function for pion cross sections.
G4double spnPiMinusPHE (const G4double x)
Internal function for pion cross sections.
G4double piNIne (Particle const *const p1, Particle const *const p2)
G4double piNTot (Particle const *const p1, Particle const *const p2)
G4double piNTopiN (Particle const *const p1, Particle const *const p2)
G4double piPluspIne (Particle const *const p1, Particle const *const p2)
G4double piMinuspIne (Particle const *const p1, Particle const *const p2)
G4double piPluspOnePi (Particle const *const p1, Particle const *const p2)
G4double piMinuspOnePi (Particle const *const p1, Particle const *const p2)
G4double piPluspTwoPi (Particle const *const p1, Particle const *const p2)
G4double piMinuspTwoPi (Particle const *const p1, Particle const *const p2)
virtual G4double piNOnePi (Particle const *const p1, Particle const *const p2)
Cross section for One (more) pion production - piN entrance channel.
virtual G4double piNTwoPi (Particle const *const p1, Particle const *const p2)
Cross section for Two (more) pion production - piN entrance channel.
Protected Attributes
const HornerC7 s11pzHC
Horner coefficients for s11pz.
const HornerC8 s01ppHC
Horner coefficients for s01pp.
const HornerC4 s01pzHC
Horner coefficients for s01pz.
const HornerC4 s11pmHC
Horner coefficients for s11pm.
const HornerC5 s12pmHC
Horner coefficients for s12pm.
const HornerC3 s12ppHC
Horner coefficients for s12pp.
const HornerC4 s12zzHC
Horner coefficients for s12zz.
const HornerC4 s02pzHC
Horner coefficients for s02pz.
const HornerC6 s02pmHC
Horner coefficients for s02pm.
const HornerC4 s12mzHC
Horner coefficients for s12mz.
Protected Attributes inherited from G4INCL::CrossSectionsMultiPions
const HornerC7 s11pzHC
Horner coefficients for s11pz.
const HornerC8 s01ppHC
Horner coefficients for s01pp.
const HornerC4 s01pzHC
Horner coefficients for s01pz.
const HornerC4 s11pmHC
Horner coefficients for s11pm.
const HornerC5 s12pmHC
Horner coefficients for s12pm.
const HornerC3 s12ppHC
Horner coefficients for s12pp.
const HornerC4 s12zzHC
Horner coefficients for s12zz.
const HornerC4 s02pzHC
Horner coefficients for s02pz.
const HornerC6 s02pmHC
Horner coefficients for s02pm.
const HornerC4 s12mzHC
Horner coefficients for s12mz.
Static Protected Attributes
static const G4int nMaxPiNN = 4
Maximum number of outgoing pions in NN collisions.
static const G4int nMaxPiPiN = 4
Maximum number of outgoing pions in piN collisions.
static const G4double s11pzOOT = 0.0035761542037692665889
One over threshold for s11pz.
static const G4double s01ppOOT = 0.003421025623481919853
One over threshold for s01pp.
static const G4double s01pzOOT = 0.0035739814152966403123
One over threshold for s01pz.
static const G4double s11pmOOT = 0.0034855350296270480281
One over threshold for s11pm.
static const G4double s12pmOOT = 0.0016672224074691565119
One over threshold for s12pm.
static const G4double s12ppOOT = 0.0016507643038726931312
One over threshold for s12pp.
static const G4double s12zzOOT = 0.0011111111111111111111
One over threshold for s12zz.
static const G4double s02pzOOT = 0.00125
One over threshold for s02pz.
static const G4double s02pmOOT = 0.0016661112962345883443
One over threshold for s02pm.
static const G4double s12mzOOT = 0.0017047391749062392793
One over threshold for s12mz.
Static Protected Attributes inherited from G4INCL::CrossSectionsMultiPions
static const G4int nMaxPiNN = 4
Maximum number of outgoing pions in NN collisions.
static const G4int nMaxPiPiN = 4
Maximum number of outgoing pions in piN collisions.
static const G4double s11pzOOT = 0.0035761542037692665889
One over threshold for s11pz.
static const G4double s01ppOOT = 0.003421025623481919853
One over threshold for s01pp.
static const G4double s01pzOOT = 0.0035739814152966403123
One over threshold for s01pz.
static const G4double s11pmOOT = 0.0034855350296270480281
One over threshold for s11pm.
static const G4double s12pmOOT = 0.0016672224074691565119
One over threshold for s12pm.
static const G4double s12ppOOT = 0.0016507643038726931312
One over threshold for s12pp.
static const G4double s12zzOOT = 0.0011111111111111111111
One over threshold for s12zz.
static const G4double s02pzOOT = 0.00125
One over threshold for s02pz.
static const G4double s02pmOOT = 0.0016661112962345883443
One over threshold for s02pm.
static const G4double s12mzOOT = 0.0017047391749062392793
One over threshold for s12mz.
Detailed Description
Multipion and mesonic Resonances cross sections.
Definition at line 54 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 54 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
Constructor & Destructor Documentation
G4INCL::CrossSectionsMultiPionsAndResonances::CrossSectionsMultiPionsAndResonances ()
Definition at line 77 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 77 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
Member Function Documentation
G4double G4INCL::CrossSectionsMultiPionsAndResonances::elastic (Particle const *const p1, Particle const *const p2) virtual
new elastic particle-particle cross section
Reimplemented from G4INCL::CrossSectionsMultiPions.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 118 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 118 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::CrossSectionsMultiPions::elastic(), etaNElastic(), G4INCL::Particle::isDelta(), G4INCL::Particle::isEta(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isOmega(), G4INCL::Particle::isPion(), and omegaNElastic().
Referenced by total().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic (Particle const *const p1, Particle const *const p2) protected virtual
Cross sections for mesonic resonance absorption on nucleon - elastic Channel.
Definition at line 340 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 340 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References Acts::VectorHelpers::eta(), G4INCL::Particle::isEta(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by elastic(), and G4INCL::CrossSectionsStrangeness::elastic().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance absorption on nucleon - piN Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 256 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 256 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References Acts::VectorHelpers::eta(), G4INCL::ParticleTable::getINCLMass(), G4INCL::Particle::getMass(), G4INCL::Particle::isEta(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::KinematicsUtils::momentumInLab(), G4InuclParticleNames::nucleon(), G4INCL::PiMinus, piMinuspToEtaN(), G4INCL::PiZero, G4INCL::Proton, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by etaNToPiPiN(), G4INCL::CrossSectionsStrangeness::total(), and total().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance absorption on nucleon - pipiN Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 303 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 303 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References Acts::VectorHelpers::eta(), etaNToPiN(), G4INCL::Particle::isEta(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by G4INCL::CrossSectionsStrangeness::total(), and total().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::etaPrimeNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for EtaPrimeN->PiN.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 493 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 493 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
Referenced by G4INCL::CrossSectionsStrangeness::total(), and total().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaEta (Particle const *const p1, Particle const *const p2) virtual
Cross section for N-Delta-Eta production - NNEta Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1092 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1092 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), NNToNNEta(), NNToNNEtaExclu(), NNToNNEtaOnePiOrDelta(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaOmega (Particle const *const p1, Particle const *const p2) virtual
Cross section for N-Delta-Eta production - NNOmega Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1241 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1241 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), NNToNNOmega(), NNToNNOmegaExclu(), NNToNNOmegaOnePiOrDelta(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEta (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production (inclusive) - NN entrance channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 691 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 691 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNToNNEtaIso(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNDeltaEta(), NNToNNEtaFourPi(), NNToNNEtaxPi(), G4INCL::CrossSectionsStrangeness::NNToxPiNN(), and NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExclu (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Eta production (exclusive) - NN entrance channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 767 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 767 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNToNNEtaExcluIso(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNDeltaEta(), NNToNNEtaFourPi(), and NNToNNEtaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExcluIso (const G4double ener, const G4int iso) protected virtual
Isotopic Cross section for Eta production (exclusive) - NN entrance channel.
Definition at line 704 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 704 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::Eta, G4INCL::ParticleTable::getRealMass(), G4INCL::Neutron, and G4INCL::Proton.
Referenced by NNToNNEtaExclu(), and NNToNNEtaIso().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaFourPi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 4-pion production - NNEta channel.
Definition at line 1039 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1039 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), NNToNNEta(), NNToNNEtaExclu(), NNToNNEtaOnePiOrDelta(), NNToNNEtaThreePi(), NNToNNEtaTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNEtaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaIso (const G4double ener, const G4int iso) protected virtual
Cross section for One (more) pion production - piN entrance channel.
Cross section for Two (more) pion production - piN entrance channel Cross section for Three (more) pion production - piN entrance channel virtual G4double piNThreePi(Particle const * const p1, Particle const * const p2); Isotopic Cross section for Eta production (inclusive) - NN entrance channel
Definition at line 638 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 638 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::Eta, G4INCL::ParticleTable::getRealMass(), G4INCL::Neutron, NNToNNEtaExcluIso(), G4INCL::Proton, and x.
Referenced by NNToNNEta().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 1-pion production - NNEta channel.
Definition at line 967 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 967 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNEtaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 1-pion production - NNEta channel.
Definition at line 983 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 983 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNDeltaEta(), and NNToNNEtaFourPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 3-pion production - NNEta channel.
Definition at line 1016 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1016 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNEtaFourPi(), and NNToNNEtaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 2-pion production - NNEta channel.
Definition at line 997 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 997 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNEtaFourPi(), and NNToNNEtaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NNEta Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1061 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1061 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), NNToNNEta(), NNToNNEtaExclu(), NNToNNEtaFourPi(), NNToNNEtaOnePi(), NNToNNEtaThreePi(), NNToNNEtaTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmega (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Omega production (inclusive) - NN entrance channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 815 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 815 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNToNNOmegaIso(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNDeltaOmega(), NNToNNOmegaFourPi(), NNToNNOmegaxPi(), G4INCL::CrossSectionsStrangeness::NNToxPiNN(), and NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExclu (Particle const *const particle1, Particle const *const particle2) virtual
Cross section for Omega production (exclusive) - NN entrance channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 875 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 875 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), NNToNNOmegaExcluIso(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNDeltaOmega(), NNToNNOmegaFourPi(), and NNToNNOmegaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExcluIso (const G4double ener, const G4int iso) protected virtual
Isotopic Cross section for Omega production (exclusive) - NN entrance channel.
Definition at line 830 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 830 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getRealMass(), G4INCL::Neutron, G4INCL::Omega, and G4INCL::Proton.
Referenced by NNToNNOmegaExclu(), and NNToNNOmegaIso().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaFourPi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 4-pion production - NNOmega channel.
Definition at line 1182 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1182 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), NNToNNOmega(), NNToNNOmegaExclu(), NNToNNOmegaOnePiOrDelta(), NNToNNOmegaThreePi(), NNToNNOmegaTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNOmegaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaIso (const G4double ener, const G4int iso) protected virtual
Isotopic Cross section for Omega production (inclusive) - NN entrance channel.
Definition at line 781 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 781 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, NNToNNOmegaExcluIso(), and x.
Referenced by NNToNNOmega().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 1-pion production - NNOmega channel.
Definition at line 1111 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1111 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNOmegaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 1-pion production - NNOmega channel.
Definition at line 1127 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1127 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNDeltaOmega(), and NNToNNOmegaFourPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 3-pion production - NNOmega channel.
Definition at line 1159 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1159 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNOmegaFourPi(), and NNToNNOmegaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi (Particle const *const part1, Particle const *const part2) protected virtual
Cross section for direct 2-pion production - NNOmega channel.
Definition at line 1141 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1141 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by NNToNNOmegaFourPi(), and NNToNNOmegaxPi().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NNOmega Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 1207 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 1207 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::CrossSectionsMultiPions::NNInelasticIso(), NNToNNOmega(), NNToNNOmegaExclu(), NNToNNOmegaFourPi(), NNToNNOmegaOnePi(), NNToNNOmegaThreePi(), NNToNNOmegaTwoPi(), ratio, and G4INCL::KinematicsUtils::totalEnergyInCM().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - NN Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 892 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 892 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References NNToNNEta(), NNToNNOmega(), and G4INCL::CrossSectionsMultiPions::NNToxPiNN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::omegaNElastic (Particle const *const p1, Particle const *const p2) protected virtual
Definition at line 405 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 405 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::Particle::isOmega(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by elastic().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::omegaNInelastic (Particle const *const p1, Particle const *const p2) protected virtual
Cross sections for mesonic resonance absorption on nucleon - inelastic Channel.
Definition at line 377 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 377 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::Particle::isOmega(), G4INCL::KinematicsUtils::momentumInLab(), and G4InuclParticleNames::nucleon().
Referenced by omegaNToPiN(), omegaNToPiPiN(), G4INCL::CrossSectionsStrangeness::total(), and total().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN (Particle const *const p1, Particle const *const p2) virtual
Cross section for OmegaN->PiN.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 433 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 433 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getINCLMass(), G4INCL::Particle::getMass(), G4INCL::Particle::isOmega(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::KinematicsUtils::momentumInLab(), omegaNInelastic(), G4INCL::PiMinus, piMinuspToOmegaN(), G4INCL::PiZero, G4INCL::Proton, and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by omegaNToPiPiN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiPiN (Particle const *const p1, Particle const *const p2) protected virtual
Cross sections for omega-induced 2Pi emission on nucleon.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 478 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 478 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References omegaNInelastic(), and omegaNToPiN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN (Particle const *const p1, Particle const *const p2) protected
Internal function for pion cross sections.
Definition at line 505 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 505 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::Particle::getMass(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by etaNToPiN(), and piNToEtaN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN (const G4double ECM) protected
Definition at line 550 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 550 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getRealMass(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::PiMinus, and G4INCL::Proton.
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN (Particle const *const p1, Particle const *const p2) protected
Definition at line 584 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 584 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::Particle::getMass(), G4INCL::Particle::isPion(), G4INCL::KinematicsUtils::momentumInLab(), and G4INCL::KinematicsUtils::totalEnergyInCM().
Referenced by omegaNToPiN(), and piNToOmegaN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN (const G4double ECM) protected
Definition at line 615 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 615 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getRealMass(), G4INCL::KinematicsUtils::momentumInLab(), G4INCL::PiMinus, and G4INCL::Proton.
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piNToEtaN (Particle const *const p1, Particle const *const p2) virtual
Cross sections for mesonic resonance production - piN Channel.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 195 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 195 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Neutron, piMinuspToEtaN(), and G4INCL::Proton.
Referenced by piNToxPiN(), and G4INCL::CrossSectionsStrangeness::piNToxPiN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piNToEtaPrimeN (Particle const *const p1, Particle const *const p2) virtual
Cross section for PiN->EtaPrimeN.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 244 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 244 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piNToOmegaN (Particle const *const p1, Particle const *const p2) virtual
Cross section for PiN->OmegaN.
Reimplemented from G4INCL::CrossSectionsMultiPions.
Definition at line 219 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 219 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getType(), G4INCL::Neutron, piMinuspToOmegaN(), and G4INCL::Proton.
Referenced by piNToxPiN(), and G4INCL::CrossSectionsStrangeness::piNToxPiN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2) virtual
Cross section for X pion production - piN Channel (modified due to the mesonic resonances)
Reimplemented from G4INCL::CrossSectionsMultiPions.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 137 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 137 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References e, piNToEtaN(), piNToOmegaN(), and G4INCL::CrossSectionsMultiPions::piNToxPiN().
G4double G4INCL::CrossSectionsMultiPionsAndResonances::total (Particle const *const p1, Particle const *const p2) virtual
new total particle-particle cross section
Reimplemented from G4INCL::CrossSectionsMultiPions.
Reimplemented in G4INCL::CrossSectionsStrangeness.
Definition at line 91 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 91 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References elastic(), etaNToPiN(), etaNToPiPiN(), etaPrimeNToPiN(), G4INCL::Particle::isDelta(), G4INCL::Particle::isEta(), G4INCL::Particle::isEtaPrime(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isOmega(), G4INCL::Particle::isPion(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NNTot(), omegaNInelastic(), and G4INCL::CrossSectionsMultiPions::piNTot().
Member Data Documentation
const G4int G4INCL::CrossSectionsMultiPionsAndResonances::nMaxPiNN = 4 static protected
Maximum number of outgoing pions in NN collisions.
Definition at line 110 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 110 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4int G4INCL::CrossSectionsMultiPionsAndResonances::nMaxPiPiN = 4 static protected
Maximum number of outgoing pions in piN collisions.
Definition at line 113 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 113 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC8 G4INCL::CrossSectionsMultiPionsAndResonances::s01ppHC protected
Horner coefficients for s01pp.
Definition at line 118 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 118 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s01ppOOT = 0.003421025623481919853 static protected
One over threshold for s01pp.
Definition at line 139 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 139 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC4 G4INCL::CrossSectionsMultiPionsAndResonances::s01pzHC protected
Horner coefficients for s01pz.
Definition at line 120 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 120 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s01pzOOT = 0.0035739814152966403123 static protected
One over threshold for s01pz.
Definition at line 141 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 141 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC6 G4INCL::CrossSectionsMultiPionsAndResonances::s02pmHC protected
Horner coefficients for s02pm.
Definition at line 132 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 132 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s02pmOOT = 0.0016661112962345883443 static protected
One over threshold for s02pm.
Definition at line 153 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 153 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC4 G4INCL::CrossSectionsMultiPionsAndResonances::s02pzHC protected
Horner coefficients for s02pz.
Definition at line 130 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 130 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s02pzOOT = 0.00125 static protected
One over threshold for s02pz.
Definition at line 151 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 151 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC4 G4INCL::CrossSectionsMultiPionsAndResonances::s11pmHC protected
Horner coefficients for s11pm.
Definition at line 122 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 122 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s11pmOOT = 0.0034855350296270480281 static protected
One over threshold for s11pm.
Definition at line 143 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 143 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC7 G4INCL::CrossSectionsMultiPionsAndResonances::s11pzHC protected
Horner coefficients for s11pz.
Definition at line 116 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 116 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s11pzOOT = 0.0035761542037692665889 static protected
One over threshold for s11pz.
Definition at line 137 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 137 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC4 G4INCL::CrossSectionsMultiPionsAndResonances::s12mzHC protected
Horner coefficients for s12mz.
Definition at line 134 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 134 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s12mzOOT = 0.0017047391749062392793 static protected
One over threshold for s12mz.
Definition at line 155 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 155 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC5 G4INCL::CrossSectionsMultiPionsAndResonances::s12pmHC protected
Horner coefficients for s12pm.
Definition at line 124 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 124 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s12pmOOT = 0.0016672224074691565119 static protected
One over threshold for s12pm.
Definition at line 145 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 145 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC3 G4INCL::CrossSectionsMultiPionsAndResonances::s12ppHC protected
Horner coefficients for s12pp.
Definition at line 126 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 126 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s12ppOOT = 0.0016507643038726931312 static protected
One over threshold for s12pp.
Definition at line 147 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 147 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const HornerC4 G4INCL::CrossSectionsMultiPionsAndResonances::s12zzHC protected
Horner coefficients for s12zz.
Definition at line 128 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 128 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
const G4double G4INCL::CrossSectionsMultiPionsAndResonances::s12zzOOT = 0.0011111111111111111111 static protected
One over threshold for s12zz.
Definition at line 149 of file G4INCLCrossSectionsMultiPionsAndResonances.hh.
View newest version in sPHENIX GitHub at line 149 of file G4INCLCrossSectionsMultiPionsAndResonances.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCrossSectionsMultiPionsAndResonances.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsMultiPionsAndResonances.cc