ECCE @ EIC Software: G4VSplitableHadron Class Reference
G4VSplitableHadron Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4VSplitableHadron.hh>
Public Member Functions
G4VSplitableHadron ()
G4VSplitableHadron (const G4ReactionProduct &aPrimary)
G4VSplitableHadron (const G4Nucleon &aNucleon)
G4VSplitableHadron (const G4VKineticNucleon *aNucleon)
virtual ~G4VSplitableHadron ()
G4bool operator== (const G4VSplitableHadron &right) const
G4bool operator!= (const G4VSplitableHadron &right) const
void Set4Momentum (const G4LorentzVector &a4Momentum)
const G4LorentzVector & Get4Momentum () const
void SetDefinition (const G4ParticleDefinition *aDefinition)
const G4ParticleDefinition * GetDefinition () const
void IncrementCollisionCount (G4int aCount)
void SetCollisionCount (G4int aCount)
void SetTimeOfCreation (G4double aTime)
G4double GetTimeOfCreation ()
void SetPosition (const G4ThreeVector &aPosition)
const G4ThreeVector & GetPosition () const
void SetStatus (const G4int aStatus)
G4int GetStatus ()
virtual void SplitUp ()=0
virtual void SetFirstParton (G4int PDGcode)=0
virtual void SetSecondParton (G4int PDGcode)=0
virtual G4Parton * GetNextParton ()=0
virtual G4Parton * GetNextAntiParton ()=0
G4bool IsSplit ()
G4int GetSoftCollisionCount ()
Protected Member Functions
void Splitting ()
Private Member Functions
G4VSplitableHadron (const G4VSplitableHadron &right)
const G4VSplitableHadron & operator= (const G4VSplitableHadron &right)
Private Attributes
const G4ParticleDefinition * theDefinition
G4LorentzVector the4Momentum
G4double TimeOfCreation
G4ThreeVector thePosition
G4int theCollisionCount
G4int curStatus
G4bool isSplit
Detailed Description
Definition at line 52 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VSplitableHadron.hh
Constructor & Destructor Documentation
G4VSplitableHadron::G4VSplitableHadron ()
Definition at line 41 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VSplitableHadron.cc
G4VSplitableHadron::G4VSplitableHadron (const G4ReactionProduct & aPrimary)
Definition at line 46 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VSplitableHadron.cc
References G4ReactionProduct::GetDefinition(), G4ReactionProduct::GetMomentum(), G4ReactionProduct::GetTotalEnergy(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setVect(), the4Momentum, and theDefinition.
G4VSplitableHadron::G4VSplitableHadron (const G4Nucleon & aNucleon)
Definition at line 54 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VSplitableHadron.cc
References curStatus, G4Nucleon::GetMomentum(), G4Nucleon::GetParticleType(), G4Nucleon::GetPosition(), isSplit, the4Momentum, theCollisionCount, theDefinition, thePosition, and TimeOfCreation.
G4VSplitableHadron::G4VSplitableHadron (const G4VKineticNucleon * aNucleon)
Definition at line 65 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VSplitableHadron.cc
References curStatus, G4VKineticNucleon::Get4Momentum(), G4VKineticNucleon::GetDefinition(), G4VKineticNucleon::GetPosition(), isSplit, the4Momentum, theCollisionCount, theDefinition, thePosition, and TimeOfCreation.
G4VSplitableHadron::~G4VSplitableHadron () virtual
Definition at line 88 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 88 of file G4VSplitableHadron.cc
G4VSplitableHadron::G4VSplitableHadron (const G4VSplitableHadron & right) private
Definition at line 76 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VSplitableHadron.cc
References curStatus, Get4Momentum(), GetDefinition(), GetPosition(), isSplit, the4Momentum, theCollisionCount, theDefinition, thePosition, and TimeOfCreation.
Member Function Documentation
const G4LorentzVector & G4VSplitableHadron::Get4Momentum () const inline
Definition at line 127 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VSplitableHadron.hh
References the4Momentum.
Referenced by G4FTFModel::AdjustNucleons(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4FTFModel::BuildStrings(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4VSplitableHadron(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4QGSParticipants::PerformDiffractiveCollisions(), G4FTFModel::PutOnMassShell(), and G4QGSDiffractiveExcitation::String().
const G4ParticleDefinition * G4VSplitableHadron::GetDefinition () const inline
Definition at line 137 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 137 of file G4VSplitableHadron.hh
References theDefinition.
Referenced by G4FTFAnnihilation::Annihilate(), G4FTFModel::BuildStrings(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4VSplitableHadron(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), G4QGSMSplitableHadron::SoftSplitUp(), and G4DiffractiveSplitableHadron::SplitUp().
virtual G4Parton* G4VSplitableHadron::GetNextAntiParton () pure virtual
Implemented in G4QGSMSplitableHadron, and G4DiffractiveSplitableHadron.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
virtual G4Parton* G4VSplitableHadron::GetNextParton () pure virtual
Implemented in G4QGSMSplitableHadron, and G4DiffractiveSplitableHadron.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::CreateStrings(), G4QuarkExchange::ExciteParticipants(), G4QGSParticipants::PerformSoftCollisions(), and G4QGSDiffractiveExcitation::String().
const G4ThreeVector & G4VSplitableHadron::GetPosition (void) const inline
Definition at line 162 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 162 of file G4VSplitableHadron.hh
References thePosition.
Referenced by G4QGSMSplitableHadron::BuildSeaQuark(), G4FTFModel::BuildStrings(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::CreateStrings(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4ElasticHNScattering::ElasticScattering(), G4VSplitableHadron(), G4FTFParticipants::GetList(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), G4FTFParticipants::ShiftInteractionTime(), and G4QGSDiffractiveExcitation::String().
G4int G4VSplitableHadron::GetSoftCollisionCount () inline
Definition at line 112 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VSplitableHadron.hh
References theCollisionCount.
Referenced by G4FTFModel::AdjustNucleons(), G4FTFModel::BuildStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4FTFModel::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4FTFModel::GetResiduals(), G4QGSMSplitableHadron::SoftSplitUp(), and G4QGSMSplitableHadron::SplitUp().
G4int G4VSplitableHadron::GetStatus () inline
Definition at line 172 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 172 of file G4VSplitableHadron.hh
References curStatus.
Referenced by G4QGSParticipants::BuildInteractions(), G4FTFModel::BuildStrings(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::CreateStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4FTFModel::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4QGSParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4QGSParticipants::PrepareInitialState(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
G4double G4VSplitableHadron::GetTimeOfCreation () inline
Definition at line 152 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 152 of file G4VSplitableHadron.hh
References TimeOfCreation.
Referenced by G4FTFModel::BuildStrings(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::CreateStrings(), G4ElasticHNScattering::ElasticScattering(), G4QGSParticipants::ReggeonCascade(), and G4FTFModel::ReggeonCascade().
void G4VSplitableHadron::IncrementCollisionCount (G4int aCount) inline
Definition at line 142 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 142 of file G4VSplitableHadron.hh
References theCollisionCount.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4ElasticHNScattering::ElasticScattering(), G4DiffractiveExcitation::ExciteParticipants(), G4QGSParticipants::GetList(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
G4bool G4VSplitableHadron::IsSplit () inline
Definition at line 88 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VSplitableHadron.hh
References isSplit.
Referenced by G4DiffractiveSplitableHadron::SplitUp(), and G4QGSMSplitableHadron::SplitUp().
G4bool G4VSplitableHadron::operator!= (const G4VSplitableHadron & right) const
Definition at line 106 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 106 of file G4VSplitableHadron.cc
References right.
const G4VSplitableHadron & G4VSplitableHadron::operator= (const G4VSplitableHadron & right) private
Definition at line 93 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 93 of file G4VSplitableHadron.cc
G4bool G4VSplitableHadron::operator== (const G4VSplitableHadron & right) const
Definition at line 101 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 101 of file G4VSplitableHadron.cc
References right.
void G4VSplitableHadron::Set4Momentum (const G4LorentzVector & a4Momentum) inline
Definition at line 122 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 122 of file G4VSplitableHadron.hh
References the4Momentum.
Referenced by G4FTFModel::AdjustNucleons(), G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4QGSParticipants::PutOnMassShell(), and G4FTFModel::PutOnMassShell().
void G4VSplitableHadron::SetCollisionCount (G4int aCount) inline
Definition at line 117 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 117 of file G4VSplitableHadron.hh
References theCollisionCount.
Referenced by G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4VSplitableHadron::SetDefinition (const G4ParticleDefinition * aDefinition) inline
Definition at line 132 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 132 of file G4VSplitableHadron.hh
References theDefinition.
Referenced by G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4QGSParticipants::GenerateDeltaIsobar(), and G4FTFModel::GenerateDeltaIsobar().
virtual void G4VSplitableHadron::SetFirstParton (G4int PDGcode) pure virtual
Implemented in G4DiffractiveSplitableHadron, and G4QGSMSplitableHadron.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), and G4FTFAnnihilation::Create3QuarkAntiQuarkStrings().
void G4VSplitableHadron::SetPosition (const G4ThreeVector & aPosition) inline
Definition at line 157 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 157 of file G4VSplitableHadron.hh
References thePosition.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4ElasticHNScattering::ElasticScattering(), G4FTFParticipants::GetList(), and G4FTFParticipants::ShiftInteractionTime().
virtual void G4VSplitableHadron::SetSecondParton (G4int PDGcode) pure virtual
Implemented in G4DiffractiveSplitableHadron, and G4QGSMSplitableHadron.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), and G4FTFAnnihilation::Create3QuarkAntiQuarkStrings().
void G4VSplitableHadron::SetStatus (const G4int aStatus) inline
Definition at line 167 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 167 of file G4VSplitableHadron.hh
References curStatus.
Referenced by G4FTFAnnihilation::Annihilate(), G4FTFModel::BuildStrings(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4VSplitableHadron::SetTimeOfCreation (G4double aTime) inline
Definition at line 147 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VSplitableHadron.hh
References TimeOfCreation.
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4ElasticHNScattering::ElasticScattering(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), and G4FTFParticipants::ShiftInteractionTime().
void G4VSplitableHadron::Splitting () inline protected
Definition at line 93 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VSplitableHadron.hh
References isSplit.
Referenced by G4DiffractiveSplitableHadron::SplitUp(), and G4QGSMSplitableHadron::SplitUp().
void G4VSplitableHadron::SplitUp () pure virtual
Implemented in G4QGSMSplitableHadron, and G4DiffractiveSplitableHadron.
Definition at line 112 of file G4VSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 112 of file G4VSplitableHadron.cc
Referenced by G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::CreateStrings(), G4QuarkExchange::ExciteParticipants(), G4InteractionContent::SplitHadrons(), and G4QGSDiffractiveExcitation::String().
Member Data Documentation
G4int G4VSplitableHadron::curStatus private
Definition at line 108 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), GetStatus(), and SetStatus().
G4bool G4VSplitableHadron::isSplit private
Definition at line 109 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), IsSplit(), and Splitting().
G4LorentzVector G4VSplitableHadron::the4Momentum private
Definition at line 102 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), Get4Momentum(), and Set4Momentum().
G4int G4VSplitableHadron::theCollisionCount private
Definition at line 106 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), GetSoftCollisionCount(), IncrementCollisionCount(), and SetCollisionCount().
const G4ParticleDefinition* G4VSplitableHadron::theDefinition private
Definition at line 100 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), GetDefinition(), and SetDefinition().
G4ThreeVector G4VSplitableHadron::thePosition private
Definition at line 105 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 105 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), GetPosition(), and SetPosition().
G4double G4VSplitableHadron::TimeOfCreation private
Definition at line 104 of file G4VSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 104 of file G4VSplitableHadron.hh
Referenced by G4VSplitableHadron(), GetTimeOfCreation(), and SetTimeOfCreation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4VSplitableHadron.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/src/G4VSplitableHadron.cc