ECCE @ EIC Software: ExUCNPrimaryGeneratorAction Class Reference
ExUCNPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/ucn/include/ExUCNPrimaryGeneratorAction.hh>
Public Member Functions
ExUCNPrimaryGeneratorAction (void)
virtual ~ExUCNPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
Detailed Description
Definition at line 45 of file ExUCNPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 45 of file ExUCNPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
ExUCNPrimaryGeneratorAction::ExUCNPrimaryGeneratorAction (void)
Definition at line 48 of file ExUCNPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 48 of file ExUCNPrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), particle, and G4ParticleGun::SetParticleDefinition().
ExUCNPrimaryGeneratorAction::~ExUCNPrimaryGeneratorAction () virtual
Definition at line 61 of file ExUCNPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 61 of file ExUCNPrimaryGeneratorAction.cc
References fParticleGun.
Member Function Documentation
void ExUCNPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 68 of file ExUCNPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 68 of file ExUCNPrimaryGeneratorAction.cc
References e, eV, fParticleGun, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), phi, pi, G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4ParticleGun::SetParticlePolarization(), G4VPrimaryGenerator::SetParticlePosition(), theta(), x, y, and z.
Member Data Documentation
G4ParticleGun* ExUCNPrimaryGeneratorAction::fParticleGun private
Definition at line 56 of file ExUCNPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file ExUCNPrimaryGeneratorAction.hh
Referenced by ExUCNPrimaryGeneratorAction(), GeneratePrimaries(), and ~ExUCNPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/ucn/include/ExUCNPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/ucn/src/ExUCNPrimaryGeneratorAction.cc