ECCE @ EIC Software: MarshaledG4THitsCollection< T > Class Template Reference
MarshaledG4THitsCollection< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/MarshaledG4THitsCollection.h>
Public Member Functions
MarshaledG4THitsCollection (G4THitsCollection< T > *objptr)
MarshaledG4THitsCollection (void *buf, char isUnmarshaling= 'u')
~MarshaledG4THitsCollection ()
G4THitsCollection< T > * unmarshal ()
void unmarshalTo (G4THitsCollection< T > *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4THitsCollection (G4THitsCollection< T > *objptr)
MarshaledG4THitsCollection (void *buf, char chIsUnmarshaling= 'u')
~MarshaledG4THitsCollection ()
G4THitsCollection< T > * unmarshal ()
void unmarshalTo (G4THitsCollection< T > *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4THitsCollection (G4THitsCollection< T > *objptr)
MarshaledG4THitsCollection (void *buf, char isUnmarshaling= 'u')
~MarshaledG4THitsCollection ()
G4THitsCollection< T > * unmarshal ()
void unmarshalTo (G4THitsCollection< T > *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4THitsCollection (G4THitsCollection< T > *objptr)
MarshaledG4THitsCollection (void *buf, char chIsUnmarshaling= 'u')
~MarshaledG4THitsCollection ()
G4THitsCollection< T > * unmarshal ()
void unmarshalTo (G4THitsCollection< T > *obj)
void marshal1 ()
void unmarshal1 ()
Public Member Functions inherited from MarshaledObj
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
Public Attributes
G4THitsCollection< T > * param
ShadowedMarshaledG4THitsCollection
< T > * Shadowed_param
Additional Inherited Members
Static Public Member Functions inherited from MarshaledObj
static int ROUND_UP (int x)
static int ROUND_UP (int x)
Protected Attributes inherited from MarshaledObj
int msh_typechoice
char * msh_buffer
char * msh_field_begin
size_t msh_size
char * msh_cursor
size_t msh_extent
bool msh_isUnmarshalDone
Detailed Description
template<class T>
class MarshaledG4THitsCollection< T >
Definition at line 24 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 24 of file MarshaledG4THitsCollection.h
Constructor & Destructor Documentation
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (G4THitsCollection< T > * objptr) inline
Definition at line 173 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 173 of file MarshaledG4THitsCollection.h
References MarshaledG4THitsCollection< T >::marshal1(), MarshaledObj::msh_isUnmarshalDone, MarshaledG4THitsCollection< T >::param, and MarshaledG4THitsCollection< T >::Shadowed_param.
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (void * buf, char isUnmarshaling = 'u') inline
Definition at line 183 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 183 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
template<class T> MarshaledG4THitsCollection< T >::~MarshaledG4THitsCollection () inline
Definition at line 188 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 188 of file MarshaledG4THitsCollection.h
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (G4THitsCollection< T > * objptr) inline
Definition at line 174 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 174 of file MarshaledG4THitsCollection.h
References MarshaledG4THitsCollection< T >::marshal1(), MarshaledObj::msh_isUnmarshalDone, MarshaledG4THitsCollection< T >::param, and MarshaledG4THitsCollection< T >::Shadowed_param.
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 184 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 184 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
template<class T> MarshaledG4THitsCollection< T >::~MarshaledG4THitsCollection () inline
Definition at line 189 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 189 of file MarshaledG4THitsCollection.h
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (G4THitsCollection< T > * objptr) inline
Definition at line 276 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 276 of file MarshaledG4THitsCollection.h
References MarshaledG4THitsCollection< T >::marshal1(), MarshaledObj::msh_isUnmarshalDone, MarshaledG4THitsCollection< T >::param, and MarshaledG4THitsCollection< T >::Shadowed_param.
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (void * buf, char isUnmarshaling = 'u') inline
Definition at line 286 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 286 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
template<class T> MarshaledG4THitsCollection< T >::~MarshaledG4THitsCollection () inline
Definition at line 291 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 291 of file MarshaledG4THitsCollection.h
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (G4THitsCollection< T > * objptr) inline
Definition at line 275 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 275 of file MarshaledG4THitsCollection.h
References MarshaledG4THitsCollection< T >::marshal1(), MarshaledObj::msh_isUnmarshalDone, MarshaledG4THitsCollection< T >::param, and MarshaledG4THitsCollection< T >::Shadowed_param.
template<class T> MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 285 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 285 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
template<class T> MarshaledG4THitsCollection< T >::~MarshaledG4THitsCollection () inline
Definition at line 290 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 290 of file MarshaledG4THitsCollection.h
Member Function Documentation
template<class T> void MarshaledG4THitsCollection< T >::marshal1 () inline
Definition at line 225 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 225 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, MarshaledG4THitsCollection< T >::param, and tmp.
Referenced by MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection().
template<class T> void MarshaledG4THitsCollection< T >::marshal1 () inline
Definition at line 226 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 226 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, MarshaledG4THitsCollection< T >::param, and tmp.
template<class T> void MarshaledG4THitsCollection< T >::marshal1 () inline
Definition at line 327 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 327 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, MarshaledG4THitsCollection< T >::param, and tmp.
template<class T> void MarshaledG4THitsCollection< T >::marshal1 () inline
Definition at line 328 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 328 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, MarshaledG4THitsCollection< T >::param, and tmp.
template<class T> G4THitsCollection<T>* MarshaledG4THitsCollection< T >::unmarshal () inline
Definition at line 194 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 194 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
template<class T> G4THitsCollection<T>* MarshaledG4THitsCollection< T >::unmarshal () inline
Definition at line 195 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 195 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
template<class T> G4THitsCollection<T>* MarshaledG4THitsCollection< T >::unmarshal () inline
Definition at line 296 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 296 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
template<class T> G4THitsCollection<T>* MarshaledG4THitsCollection< T >::unmarshal () inline
Definition at line 297 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 297 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
template<class T> void MarshaledG4THitsCollection< T >::unmarshal1 () inline
Definition at line 265 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 265 of file MarshaledG4THitsCollection.h
References int(), MarshaledObj::msh_cursor, MarshaledG4THitsCollection< T >::param, and MarshaledG4HitsCollection::unmarshalTo().
Referenced by MarshaledG4THitsCollection< T >::unmarshal(), and MarshaledG4THitsCollection< T >::unmarshalTo().
template<class T> void MarshaledG4THitsCollection< T >::unmarshal1 () inline
Definition at line 270 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 270 of file MarshaledG4THitsCollection.h
References int(), MarshaledObj::msh_cursor, MarshaledG4THitsCollection< T >::param, and MarshaledG4HitsCollection::unmarshalTo().
template<class T> void MarshaledG4THitsCollection< T >::unmarshal1 () inline
Definition at line 368 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 368 of file MarshaledG4THitsCollection.h
References int(), MarshaledObj::msh_cursor, MarshaledG4THitsCollection< T >::param, and MarshaledG4HitsCollection::unmarshalTo().
template<class T> void MarshaledG4THitsCollection< T >::unmarshal1 () inline
Definition at line 371 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 371 of file MarshaledG4THitsCollection.h
References int(), MarshaledObj::msh_cursor, MarshaledG4THitsCollection< T >::param, and MarshaledG4HitsCollection::unmarshalTo().
template<class T> void MarshaledG4THitsCollection< T >::unmarshalTo (G4THitsCollection< T > * obj) inline
Definition at line 211 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 211 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
Referenced by MarshaledG4VHitsCollection::unmarshal3().
template<class T> void MarshaledG4THitsCollection< T >::unmarshalTo (G4THitsCollection< T > * obj) inline
Definition at line 212 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 212 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
template<class T> void MarshaledG4THitsCollection< T >::unmarshalTo (G4THitsCollection< T > * obj) inline
Definition at line 313 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 313 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
template<class T> void MarshaledG4THitsCollection< T >::unmarshalTo (G4THitsCollection< T > * obj) inline
Definition at line 314 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 314 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, MarshaledG4THitsCollection< T >::param, MarshaledG4THitsCollection< T >::Shadowed_param, and MarshaledG4THitsCollection< T >::unmarshal1().
Member Data Documentation
template<class T> G4THitsCollection< T > * MarshaledG4THitsCollection< T >::param
Definition at line 166 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 166 of file MarshaledG4THitsCollection.h
Referenced by MarshaledG4THitsCollection< T >::marshal1(), MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection(), MarshaledG4THitsCollection< T >::unmarshal(), MarshaledG4THitsCollection< T >::unmarshal1(), and MarshaledG4THitsCollection< T >::unmarshalTo().
template<class T> ShadowedMarshaledG4THitsCollection< T > * MarshaledG4THitsCollection< T >::Shadowed_param
Definition at line 167 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 167 of file MarshaledG4THitsCollection.h
Referenced by MarshaledG4THitsCollection< T >::MarshaledG4THitsCollection(), MarshaledG4THitsCollection< T >::unmarshal(), and MarshaledG4THitsCollection< T >::unmarshalTo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/MarshaledG4THitsCollection.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/MarshaledG4THitsCollection.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/MarshaledG4THitsCollection.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledG4THitsCollection.h