ECCE @ EIC Software: G3MedTable Class Reference
G3MedTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MedTable.hh>
Public Member Functions
G3MedTable ()
virtual ~G3MedTable ()
G3MedTableEntry * get (G4int id) const
void put (G4int id, G4Material *material, G4MagneticField *field, G4UserLimits *limits, G4int isvol)
G4int GetSize () const
G3MedTableEntry * GetMTE (G4int i) const
void Clear ()
Private Attributes
G3MediumVector * fMedVector
Detailed Description
Definition at line 56 of file G3MedTable.hh.
View newest version in sPHENIX GitHub at line 56 of file G3MedTable.hh
Constructor & Destructor Documentation
G3MedTable::G3MedTable ()
Definition at line 32 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 32 of file G3MedTable.cc
References fMedVector.
G3MedTable::~G3MedTable () virtual
Definition at line 37 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 37 of file G3MedTable.cc
References Clear(), and fMedVector.
Member Function Documentation
void G3MedTable::Clear ()
Definition at line 73 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 73 of file G3MedTable.cc
References a, and fMedVector.
Referenced by ~G3MedTable().
G3MedTableEntry * G3MedTable::get (G4int id) const
Definition at line 43 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 43 of file G3MedTable.cc
References fMedVector, and G3MedTableEntry::GetID().
Referenced by G3toG4BuildLVTree().
G3MedTableEntry * G3MedTable::GetMTE (G4int i) const
Definition at line 60 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 60 of file G3MedTable.cc
References fMedVector.
G4int G3MedTable::GetSize () const
Definition at line 68 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 68 of file G3MedTable.cc
References fMedVector.
void G3MedTable::put (G4int id, G4Material * material, G4MagneticField * field, G4UserLimits * limits, G4int isvol)
Definition at line 52 of file G3MedTable.cc.
View newest version in sPHENIX GitHub at line 52 of file G3MedTable.cc
References fMedVector.
Referenced by G4gstmed().
Member Data Documentation
G3MediumVector* G3MedTable::fMedVector private
Definition at line 73 of file G3MedTable.hh.
View newest version in sPHENIX GitHub at line 73 of file G3MedTable.hh
Referenced by Clear(), G3MedTable(), get(), GetMTE(), GetSize(), put(), and ~G3MedTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MedTable.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3MedTable.cc