ECCE @ EIC Software: TrackerSD Class Reference
TrackerSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/include/TrackerSD.hh>
Public Member Functions
TrackerSD (const G4String &name, const G4String &hitsCollectionName)
virtual ~TrackerSD ()
virtual void Initialize (G4HCofThisEvent *hitCollection)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hitCollection)
TrackerSD (const G4String &name, const G4String &hitsCollectionName)
virtual ~TrackerSD ()
virtual void Initialize (G4HCofThisEvent *hitCollection)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hitCollection)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
TrackerHitsCollection * fHitsCollection
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Tracker sensitive detector class
The hits are accounted in hits in ProcessHits() function which is called by Geant4 kernel at each step. A hit is created with each step with non zero energy deposit.
Definition at line 54 of file TrackerSD.hh.
View newest version in sPHENIX GitHub at line 54 of file TrackerSD.hh
Constructor & Destructor Documentation
TrackerSD::TrackerSD (const G4String & name, const G4String & hitsCollectionName)
Definition at line 49 of file TrackerSD.cc.
View newest version in sPHENIX GitHub at line 49 of file TrackerSD.cc
References G4VSensitiveDetector::collectionName, and G4CollectionNameVector::insert().
TrackerSD::~TrackerSD () virtual
Definition at line 59 of file TrackerSD.cc.
View newest version in sPHENIX GitHub at line 59 of file TrackerSD.cc
TrackerSD::TrackerSD (const G4String & name, const G4String & hitsCollectionName)
virtual TrackerSD::~TrackerSD () virtual
Member Function Documentation
virtual void TrackerSD::EndOfEvent (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
void TrackerSD::EndOfEvent (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 105 of file TrackerSD.cc.
View newest version in sPHENIX GitHub at line 105 of file TrackerSD.cc
References G4THitsCollection< T >::entries(), eV, fHitsCollection, G4ToolsAnalysisManager::Instance(), k, Acts::Test::maxRadius, Acts::Test::minRadius, nm, radius, Acts::Test::step(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
virtual void TrackerSD::Initialize (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
void TrackerSD::Initialize (G4HCofThisEvent * hitCollection) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 64 of file TrackerSD.cc.
View newest version in sPHENIX GitHub at line 64 of file TrackerSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, fHitsCollection, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), and G4VSensitiveDetector::SensitiveDetectorName.
virtual G4bool TrackerSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
G4bool TrackerSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
Definition at line 80 of file TrackerSD.cc.
View newest version in sPHENIX GitHub at line 80 of file TrackerSD.cc
References edep, fHitsCollection, G4Track::GetParentID(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetVertexKineticEnergy(), G4THitsCollection< T >::insert(), TrackerHit::SetEdep(), TrackerHit::SetIncidentEnergy(), TrackerHit::SetPos(), and TrackerHit::SetTrackID().
Member Data Documentation
TrackerHitsCollection * TrackerSD::fHitsCollection private
Definition at line 67 of file TrackerSD.hh.
View newest version in sPHENIX GitHub at line 67 of file TrackerSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/include/TrackerSD.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/include/TrackerSD.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/src/TrackerSD.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/src/TrackerSD.cc