ECCE @ EIC Software: PhantomSD Class Reference
PhantomSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/PhantomSD.hh>
Public Member Functions
PhantomSD (const G4String &)
virtual ~PhantomSD ()
void Initialize (G4HCofThisEvent *)
G4bool ProcessHits (G4Step *, G4TouchableHistory *)
void EndOfEvent (G4HCofThisEvent *)
void clear ()
void PrintAll ()
void SetShiftZ (G4double val)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void DrawAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Member Functions
PhantomSD & operator= (const PhantomSD &right)
PhantomSD (const PhantomSD &)
Private Attributes
G4double fShiftZ
G4int fCounter
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 53 of file PhantomSD.hh.
View newest version in sPHENIX GitHub at line 53 of file PhantomSD.hh
Constructor & Destructor Documentation
PhantomSD::PhantomSD (const G4String & name)
Definition at line 52 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 52 of file PhantomSD.cc
PhantomSD::~PhantomSD () virtual
Definition at line 58 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 58 of file PhantomSD.cc
PhantomSD::PhantomSD (const PhantomSD &) private
Member Function Documentation
void PhantomSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 121 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 121 of file PhantomSD.cc
void PhantomSD::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 116 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 116 of file PhantomSD.cc
void PhantomSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 63 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 63 of file PhantomSD.cc
References fCounter, G4cout, G4endl, G4RunManager::GetNonConstCurrentRun(), G4RunManager::GetRunManager(), and Run::GetVerbose().
PhantomSD& PhantomSD::operator= (const PhantomSD & right) private
void PhantomSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 127 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 127 of file PhantomSD.cc
G4bool PhantomSD::ProcessHits (G4Step * aStep, G4TouchableHistory *) virtual
Implements G4VSensitiveDetector.
Definition at line 76 of file PhantomSD.cc.
View newest version in sPHENIX GitHub at line 76 of file PhantomSD.cc
References Run::AddPhantomStep(), edep, fShiftZ, G4cout, G4endl, G4RunManager::GetNonConstCurrentRun(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4RunManager::GetRunManager(), G4Step::GetTotalEnergyDeposit(), Run::GetVerbose(), MeV, r1, r2, CLHEP::Hep3Vector::x(), x1, x2, CLHEP::Hep3Vector::y(), y1, y2, CLHEP::Hep3Vector::z(), G4InuclParticleNames::z0, z1, and z2.
void PhantomSD::SetShiftZ (G4double val) inline
Definition at line 67 of file PhantomSD.hh.
View newest version in sPHENIX GitHub at line 67 of file PhantomSD.hh
References fShiftZ.
Member Data Documentation
G4int PhantomSD::fCounter private
Definition at line 75 of file PhantomSD.hh.
View newest version in sPHENIX GitHub at line 75 of file PhantomSD.hh
Referenced by Initialize().
G4double PhantomSD::fShiftZ private
Definition at line 74 of file PhantomSD.hh.
View newest version in sPHENIX GitHub at line 74 of file PhantomSD.hh
Referenced by ProcessHits(), and SetShiftZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/PhantomSD.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/PhantomSD.cc