ECCE @ EIC Software: G4tgrMaterialSimple Class Reference
G4tgrMaterialSimple Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterialSimple.hh>
Public Member Functions
G4tgrMaterialSimple (const G4String &matType, const std::vector< G4String > &wl)
G4tgrMaterialSimple & operator= (const G4tgrMaterialSimple &)
G4double GetA () const
G4double GetZ () const
const G4String & GetComponent (G4int i) const
G4double GetFraction (G4int i)
G4tgrMaterialSimple ()
~G4tgrMaterialSimple ()
Public Member Functions inherited from G4tgrMaterial
G4tgrMaterial ()
virtual ~G4tgrMaterial ()
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfComponents () const
const G4String & GetType () const
G4double GetIonisationMeanExcitationEnergy () const
void SetIonisationMeanExcitationEnergy (G4double mee)
G4State GetState () const
void SetState (G4String val)
G4double GetTemperature () const
void SetTemperature (G4double val)
G4double GetPressure () const
void SetPressure (G4double val)
Private Attributes
G4String name
G4double theA
G4double theZ
Friends
std::ostream & operator<< (std::ostream &, const G4tgrMaterialSimple &)
Additional Inherited Members
Protected Attributes inherited from G4tgrMaterial
G4String theName
G4double theDensity
G4int theNoComponents
G4String theMateType
G4double theIonisationMeanExcitationEnergy
G4State theState
G4double theTemperature
G4double thePressure
Detailed Description
Definition at line 49 of file G4tgrMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgrMaterialSimple.hh
Constructor & Destructor Documentation
G4tgrMaterialSimple::G4tgrMaterialSimple (const G4String & matType, const std::vector< G4String > & wl)
Definition at line 56 of file G4tgrMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 56 of file G4tgrMaterialSimple.cc
References G4tgrUtils::CheckWLsize(), cm3, Acts::UnitConstants::g, G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), mole, theA, G4tgrMaterial::theDensity, G4tgrMaterial::theMateType, G4tgrMaterial::theName, G4tgrMaterial::theNoComponents, theZ, and WLSIZE_EQ.
G4tgrMaterialSimple::G4tgrMaterialSimple ()
Definition at line 43 of file G4tgrMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgrMaterialSimple.cc
G4tgrMaterialSimple::~G4tgrMaterialSimple ()
Definition at line 50 of file G4tgrMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 50 of file G4tgrMaterialSimple.cc
Member Function Documentation
G4double G4tgrMaterialSimple::GetA () const inline virtual
Implements G4tgrMaterial.
Definition at line 61 of file G4tgrMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrMaterialSimple.hh
References theA.
Referenced by G4tgbMaterialSimple::G4tgbMaterialSimple().
const G4String & G4tgrMaterialSimple::GetComponent (G4int i) const virtual
Implements G4tgrMaterial.
Definition at line 82 of file G4tgrMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 82 of file G4tgrMaterialSimple.cc
References G4UIcommand::ConvertToString(), FatalException, G4Exception(), and name.
G4double G4tgrMaterialSimple::GetFraction (G4int i) virtual
Implements G4tgrMaterial.
Definition at line 94 of file G4tgrMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 94 of file G4tgrMaterialSimple.cc
References G4UIcommand::ConvertToString(), FatalException, and G4Exception().
G4double G4tgrMaterialSimple::GetZ () const inline virtual
Implements G4tgrMaterial.
Definition at line 62 of file G4tgrMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 62 of file G4tgrMaterialSimple.hh
References theZ.
Referenced by G4tgbMaterialSimple::G4tgbMaterialSimple().
G4tgrMaterialSimple& G4tgrMaterialSimple::operator= (const G4tgrMaterialSimple &)
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrMaterialSimple & mate) friend
Definition at line 106 of file G4tgrMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 106 of file G4tgrMaterialSimple.cc
Member Data Documentation
G4String G4tgrMaterialSimple::name private
Definition at line 74 of file G4tgrMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 74 of file G4tgrMaterialSimple.hh
Referenced by GetComponent().
G4double G4tgrMaterialSimple::theA private
Definition at line 75 of file G4tgrMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 75 of file G4tgrMaterialSimple.hh
Referenced by G4tgrMaterialSimple(), GetA(), and operator<<().
G4double G4tgrMaterialSimple::theZ private
Definition at line 76 of file G4tgrMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 76 of file G4tgrMaterialSimple.hh
Referenced by G4tgrMaterialSimple(), GetZ(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterialSimple.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrMaterialSimple.cc