ECCE @ EIC Software: G4VCoulombBarrier Class Reference
G4VCoulombBarrier Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4VCoulombBarrier.hh>
Public Member Functions
G4VCoulombBarrier (G4int anA, G4int aZ)
virtual ~G4VCoulombBarrier ()
virtual G4double GetCoulombBarrier (G4int ARes, G4int ZRes, G4double U) const =0
virtual G4double BarrierPenetrationFactor (G4int Eexc) const =0
void SetParameters (G4double rho, G4double r0)
G4int GetA (void) const
G4int GetZ (void) const
G4double GetRho (void) const
G4double GetR0 (void) const
Private Member Functions
G4VCoulombBarrier (const G4VCoulombBarrier &right)=delete
const G4VCoulombBarrier & operator= (const G4VCoulombBarrier &right)=delete
G4bool operator== (const G4VCoulombBarrier &right) const =delete
G4bool operator!= (const G4VCoulombBarrier &right) const =delete
Private Attributes
G4int theA
G4int theZ
G4double theRho
G4double theR0
Detailed Description
Definition at line 36 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 36 of file G4VCoulombBarrier.hh
Constructor & Destructor Documentation
G4VCoulombBarrier::G4VCoulombBarrier (G4int anA, G4int aZ) explicit
Definition at line 33 of file G4VCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VCoulombBarrier.cc
References CLHEP::fermi, theA, theR0, theRho, and theZ.
G4VCoulombBarrier::~G4VCoulombBarrier () virtual
Definition at line 41 of file G4VCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VCoulombBarrier.cc
G4VCoulombBarrier::G4VCoulombBarrier (const G4VCoulombBarrier & right) private delete
Member Function Documentation
virtual G4double G4VCoulombBarrier::BarrierPenetrationFactor (G4int Eexc) const pure virtual
Implemented in G4ProtonCoulombBarrier, G4CoulombBarrier, G4He3CoulombBarrier, G4AlphaCoulombBarrier, G4DeuteronCoulombBarrier, and G4TritonCoulombBarrier.
G4int G4VCoulombBarrier::GetA (void) const inline
Definition at line 50 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VCoulombBarrier.hh
References theA.
Referenced by G4CoulombBarrier::BarrierPenetrationFactor(), and G4GEMCoulombBarrier::CalcCompoundRadius().
virtual G4double G4VCoulombBarrier::GetCoulombBarrier (G4int ARes, G4int ZRes, G4double U) const pure virtual
Implemented in G4CoulombBarrier, and G4GEMCoulombBarrier.
Referenced by G4GEMProbability::GetCoulombBarrier(), G4GEMChannelVI::GetEmissionProbability(), and G4GEMChannel::GetEmissionProbability().
G4double G4VCoulombBarrier::GetR0 (void) const inline
Definition at line 53 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VCoulombBarrier.hh
References theR0.
G4double G4VCoulombBarrier::GetRho (void) const inline
Definition at line 52 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VCoulombBarrier.hh
References theRho.
Referenced by G4CoulombBarrier::GetCoulombBarrier().
G4int G4VCoulombBarrier::GetZ (void) const inline
Definition at line 51 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VCoulombBarrier.hh
References theZ.
Referenced by G4CoulombBarrier::BarrierPenetrationFactor().
G4bool G4VCoulombBarrier::operator!= (const G4VCoulombBarrier & right) const private delete
const G4VCoulombBarrier& G4VCoulombBarrier::operator= (const G4VCoulombBarrier & right) private delete
G4bool G4VCoulombBarrier::operator== (const G4VCoulombBarrier & right) const private delete
void G4VCoulombBarrier::SetParameters (G4double rho, G4double r0)
Definition at line 44 of file G4VCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VCoulombBarrier.cc
References theR0, and theRho.
Referenced by G4CoulombBarrier::G4CoulombBarrier().
Member Data Documentation
G4int G4VCoulombBarrier::theA private
Definition at line 62 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VCoulombBarrier.hh
Referenced by G4VCoulombBarrier(), and GetA().
G4double G4VCoulombBarrier::theR0 private
Definition at line 65 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VCoulombBarrier.hh
Referenced by G4VCoulombBarrier(), GetR0(), and SetParameters().
G4double G4VCoulombBarrier::theRho private
Definition at line 64 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VCoulombBarrier.hh
Referenced by G4VCoulombBarrier(), GetRho(), and SetParameters().
G4int G4VCoulombBarrier::theZ private
Definition at line 63 of file G4VCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VCoulombBarrier.hh
Referenced by G4VCoulombBarrier(), and GetZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4VCoulombBarrier.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/src/G4VCoulombBarrier.cc