ECCE @ EIC Software: G4GDMLMessenger Class Reference
G4GDMLMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLMessenger.hh>
Public Member Functions
G4GDMLMessenger (G4GDMLParser *)
~G4GDMLMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4GDMLParser * myParser
G4LogicalVolume * topvol
G4UIdirectory * persistencyDir
G4UIdirectory * gdmlDir
G4UIcmdWithAString * ReaderCmd
G4UIcmdWithAString * WriterCmd
G4UIcmdWithAString * TopVolCmd
G4UIcmdWithoutParameter * ClearCmd
G4UIcmdWithABool * RegionCmd
G4UIcmdWithABool * EcutsCmd
G4UIcmdWithABool * SDCmd
G4UIcmdWithABool * StripCmd
G4UIcmdWithABool * AppendCmd
G4bool pFlag
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 53 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file G4GDMLMessenger.hh
Constructor & Destructor Documentation
G4GDMLMessenger::G4GDMLMessenger (G4GDMLParser * myPars)
Definition at line 47 of file G4GDMLMessenger.cc.
View newest version in sPHENIX GitHub at line 47 of file G4GDMLMessenger.cc
References AppendCmd, G4UIcommand::AvailableForStates(), ClearCmd, EcutsCmd, G4State_Idle, G4State_PreInit, gdmlDir, persistencyDir, ReaderCmd, RegionCmd, SDCmd, G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcommand::SetToBeBroadcasted(), StripCmd, TopVolCmd, and WriterCmd.
G4GDMLMessenger::~G4GDMLMessenger ()
Definition at line 122 of file G4GDMLMessenger.cc.
View newest version in sPHENIX GitHub at line 122 of file G4GDMLMessenger.cc
References AppendCmd, ClearCmd, EcutsCmd, gdmlDir, persistencyDir, ReaderCmd, RegionCmd, SDCmd, StripCmd, TopVolCmd, and WriterCmd.
Member Function Documentation
void G4GDMLMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 137 of file G4GDMLMessenger.cc.
View newest version in sPHENIX GitHub at line 137 of file G4GDMLMessenger.cc
References AppendCmd, G4GDMLParser::Clear(), ClearCmd, G4RunManager::DefineWorldVolume(), EcutsCmd, G4RunManager::GeometryDirectlyUpdated(), G4LogicalVolumeStore::GetInstance(), G4GeometryManager::GetInstance(), G4UIcmdWithABool::GetNewBoolValue(), G4RunManager::GetRunManager(), G4LogicalVolumeStore::GetVolume(), G4GDMLParser::GetWorldVolume(), myParser, G4GeometryManager::OpenGeometry(), pFlag, G4GDMLParser::Read(), ReaderCmd, RegionCmd, G4RunManager::ReinitializeGeometry(), SDCmd, G4GDMLParser::SetAddPointerToName(), G4GDMLParser::SetEnergyCutsExport(), G4GDMLParser::SetRegionExport(), G4GDMLParser::SetSDExport(), G4GDMLParser::SetStripFlag(), StripCmd, topvol, TopVolCmd, G4GDMLParser::Write(), and WriterCmd.
Member Data Documentation
G4UIcmdWithABool* G4GDMLMessenger::AppendCmd private
Definition at line 77 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIcmdWithoutParameter* G4GDMLMessenger::ClearCmd private
Definition at line 72 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIcmdWithABool* G4GDMLMessenger::EcutsCmd private
Definition at line 74 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIdirectory* G4GDMLMessenger::gdmlDir private
Definition at line 68 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), and ~G4GDMLMessenger().
G4GDMLParser* G4GDMLMessenger::myParser private
Definition at line 64 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4GDMLMessenger.hh
Referenced by SetNewValue().
G4UIdirectory* G4GDMLMessenger::persistencyDir private
Definition at line 67 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), and ~G4GDMLMessenger().
G4bool G4GDMLMessenger::pFlag private
Definition at line 79 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GDMLMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* G4GDMLMessenger::ReaderCmd private
Definition at line 69 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIcmdWithABool* G4GDMLMessenger::RegionCmd private
Definition at line 73 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIcmdWithABool* G4GDMLMessenger::SDCmd private
Definition at line 75 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIcmdWithABool* G4GDMLMessenger::StripCmd private
Definition at line 76 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4LogicalVolume* G4GDMLMessenger::topvol private
Definition at line 65 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4GDMLMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* G4GDMLMessenger::TopVolCmd private
Definition at line 71 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
G4UIcmdWithAString* G4GDMLMessenger::WriterCmd private
Definition at line 70 of file G4GDMLMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4GDMLMessenger.hh
Referenced by G4GDMLMessenger(), SetNewValue(), and ~G4GDMLMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLMessenger.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLMessenger.cc