ECCE @ EIC Software: G4UIExecutive Class Reference
G4UIExecutive Class Reference
#include <geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4UIExecutive.hh>
Public Member Functions
G4UIExecutive (G4int argc, char **argv, const G4String &type="")
~G4UIExecutive ()
G4UIsession * GetSession () const
G4bool IsGUI () const
void SetPrompt (const G4String &prompt)
void SetLsColor (TermColorIndex dirColor, TermColorIndex cmdColor)
void SessionStart ()
Private Types
enum SessionType {
kNone, kQt, kXm, kWin32,
kWt, kGag, kTcsh, kCsh
}
Private Member Functions
void SelectSessionByArg (const G4String &stype)
void SelectSessionByEnv ()
void SelectSessionByFile (const G4String &appname)
void SelectSessionByBestGuess ()
Private Attributes
SessionType selected
G4UIsession * session
G4VUIshell * shell
G4bool isGUI
std::map< G4String, G4String > sessionMap
Detailed Description
Definition at line 59 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 59 of file G4UIExecutive.hh
Member Enumeration Documentation
enum G4UIExecutive::SessionType private
Enumerator:
kNone
kQt
kXm
kWin32
kWt
kGag
kTcsh
kCsh
Definition at line 74 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 74 of file G4UIExecutive.hh
Constructor & Destructor Documentation
G4UIExecutive::G4UIExecutive (G4int argc, char ** argv, const G4String & type = "")
Definition at line 90 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 90 of file G4UIExecutive.cc
References DISCARD_PARAMETER, G4cout, G4endl, G4Exception(), isGUI, JustWarning, kCsh, kGag, kNone, kQt, kTcsh, kWin32, kWt, kXm, qt_build, selected, SelectSessionByArg(), SelectSessionByBestGuess(), SelectSessionByEnv(), SelectSessionByFile(), session, shell, tcsh_build, TIMEMORY_INIT, G4String::toLower(), win32_build, wt_build, and xm_build.
G4UIExecutive::~G4UIExecutive ()
Definition at line 198 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 198 of file G4UIExecutive.cc
References kWt, selected, and session.
Member Function Documentation
G4UIsession * G4UIExecutive::GetSession () const inline
Definition at line 91 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 91 of file G4UIExecutive.hh
References session.
G4bool G4UIExecutive::IsGUI () const inline
Definition at line 96 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 96 of file G4UIExecutive.hh
References isGUI.
Referenced by main().
void G4UIExecutive::SelectSessionByArg (const G4String & stype) private
Definition at line 204 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 204 of file G4UIExecutive.cc
References kCsh, kGag, kQt, kTcsh, kWin32, kWt, kXm, qt_build, selected, tcsh_build, win32_build, wt_build, and xm_build.
Referenced by G4UIExecutive().
void G4UIExecutive::SelectSessionByBestGuess () private
Definition at line 286 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 286 of file G4UIExecutive.cc
References kQt, kTcsh, kXm, qt_build, selected, tcsh_build, and xm_build.
Referenced by G4UIExecutive().
void G4UIExecutive::SelectSessionByEnv () private
Definition at line 216 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 216 of file G4UIExecutive.cc
References kGag, kQt, kTcsh, kWin32, kWt, kXm, qt_build, selected, tcsh_build, win32_build, wt_build, and xm_build.
Referenced by G4UIExecutive().
void G4UIExecutive::SelectSessionByFile (const G4String & appname) private
Definition at line 227 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 227 of file G4UIExecutive.cc
References G4String::both, BUFSIZE, test::fname, incremental_prev_tag::idx, in, it, kCsh, kGag, kQt, kTcsh, kWin32, kXm, qt_build, selected, sessionMap, G4String::strip(), tcsh_build, G4String::toLower(), win32_build, and xm_build.
Referenced by G4UIExecutive().
void G4UIExecutive::SessionStart ()
Definition at line 307 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 307 of file G4UIExecutive.cc
References session.
Referenced by main(), XrayFluoSimulation::RunSimulation(), and PHG4Reco::StartGui().
void G4UIExecutive::SetLsColor (TermColorIndex dirColor, TermColorIndex cmdColor)
Definition at line 300 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 300 of file G4UIExecutive.cc
References shell.
void G4UIExecutive::SetPrompt (const G4String & prompt)
Definition at line 294 of file G4UIExecutive.cc.
View newest version in sPHENIX GitHub at line 294 of file G4UIExecutive.cc
References shell.
Member Data Documentation
G4bool G4UIExecutive::isGUI private
Definition at line 80 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UIExecutive.hh
Referenced by G4UIExecutive(), and IsGUI().
SessionType G4UIExecutive::selected private
Definition at line 75 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 75 of file G4UIExecutive.hh
Referenced by G4UIExecutive(), SelectSessionByArg(), SelectSessionByBestGuess(), SelectSessionByEnv(), SelectSessionByFile(), and ~G4UIExecutive().
G4UIsession* G4UIExecutive::session private
Definition at line 77 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 77 of file G4UIExecutive.hh
Referenced by G4UIExecutive(), GetSession(), SessionStart(), and ~G4UIExecutive().
std::map<G4String, G4String> G4UIExecutive::sessionMap private
Definition at line 82 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UIExecutive.hh
Referenced by SelectSessionByFile().
G4VUIshell* G4UIExecutive::shell private
Definition at line 78 of file G4UIExecutive.hh.
View newest version in sPHENIX GitHub at line 78 of file G4UIExecutive.hh
Referenced by G4UIExecutive(), SetLsColor(), and SetPrompt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/interfaces/basic/include/G4UIExecutive.hh
geant4/tree/geant4-10.6-release/source/interfaces/basic/src/G4UIExecutive.cc