ECCE @ EIC Software: G4ParticleChangeForRadDecay Class Reference
G4ParticleChangeForRadDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForRadDecay.hh>
Public Member Functions
G4ParticleChangeForRadDecay ()
virtual ~G4ParticleChangeForRadDecay ()
void AddSecondary (G4Track *aSecondary)
Public Member Functions inherited from G4ParticleChangeForDecay
G4ParticleChangeForDecay ()
virtual ~G4ParticleChangeForDecay ()
G4bool operator== (const G4ParticleChangeForDecay &right) const
G4bool operator!= (const G4ParticleChangeForDecay &right) const
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
virtual G4Step * UpdateStepForPostStep (G4Step *Step)
virtual void Initialize (const G4Track &)
void ProposeGlobalTime (G4double t)
void ProposeLocalTime (G4double t)
G4double GetGlobalTime (G4double timeDelay=0.0) const
G4double GetLocalTime (G4double timeDelay=0.0) const
const G4ThreeVector * GetPolarization () const
void ProposePolarization (G4double Px, G4double Py, G4double Pz)
void ProposePolarization (const G4ThreeVector &finalPoralization)
virtual void DumpInfo () const
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChangeForRadDecay (const G4ParticleChangeForRadDecay &)
G4ParticleChangeForRadDecay & operator= (const G4ParticleChangeForRadDecay &)
Protected Member Functions inherited from G4ParticleChangeForDecay
G4ParticleChangeForDecay (const G4ParticleChangeForDecay &right)
G4ParticleChangeForDecay & operator= (const G4ParticleChangeForDecay &right)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Additional Inherited Members
Protected Attributes inherited from G4ParticleChangeForDecay
G4double theGlobalTime0
G4double theLocalTime0
G4double theTimeChange
G4ThreeVector thePolarizationChange
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 47 of file G4ParticleChangeForRadDecay.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleChangeForRadDecay.hh
Constructor & Destructor Documentation
G4ParticleChangeForRadDecay::G4ParticleChangeForRadDecay () inline
Definition at line 51 of file G4ParticleChangeForRadDecay.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleChangeForRadDecay.hh
virtual G4ParticleChangeForRadDecay::~G4ParticleChangeForRadDecay () inline virtual
Definition at line 54 of file G4ParticleChangeForRadDecay.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleChangeForRadDecay.hh
G4ParticleChangeForRadDecay::G4ParticleChangeForRadDecay (const G4ParticleChangeForRadDecay &) inline protected
Definition at line 58 of file G4ParticleChangeForRadDecay.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleChangeForRadDecay.hh
Member Function Documentation
void G4ParticleChangeForRadDecay::AddSecondary (G4Track * aSecondary) inline
Definition at line 70 of file G4ParticleChangeForRadDecay.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleChangeForRadDecay.hh
References G4cout, G4endl, G4Exception(), JustWarning, G4FastVector< Type, N >::SetElement(), G4VParticleChange::theListOfSecondaries, G4VParticleChange::theNumberOfSecondaries, G4VParticleChange::theSizeOftheListOfSecondaries, and G4VParticleChange::verboseLevel.
Referenced by G4RadioactiveDecayBase::DecayAnalog(), G4Radioactivation::DecayIt(), and G4RadioactiveDecay::DecayIt().
G4ParticleChangeForRadDecay& G4ParticleChangeForRadDecay::operator= (const G4ParticleChangeForRadDecay &) inline protected
Definition at line 59 of file G4ParticleChangeForRadDecay.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleChangeForRadDecay.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForRadDecay.hh