ECCE @ EIC Software: F04StackingAction Class Reference
F04StackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04StackingAction.hh>
Public Member Functions
F04StackingAction ()
virtual ~F04StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 36 of file F04StackingAction.hh.
View newest version in sPHENIX GitHub at line 36 of file F04StackingAction.hh
Constructor & Destructor Documentation
F04StackingAction::F04StackingAction ()
Definition at line 41 of file F04StackingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file F04StackingAction.cc
F04StackingAction::~F04StackingAction () virtual
Definition at line 45 of file F04StackingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file F04StackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack F04StackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 50 of file F04StackingAction.cc.
View newest version in sPHENIX GitHub at line 50 of file F04StackingAction.cc
References fKill, fUrgent, G4Track::GetDefinition(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4KaonPlus::KaonPlusDefinition(), G4MuonPlus::MuonPlusDefinition(), G4Neutron::NeutronDefinition(), G4PionPlus::PionPlusDefinition(), G4Positron::PositronDefinition(), and G4Proton::ProtonDefinition().
void F04StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 74 of file F04StackingAction.cc.
View newest version in sPHENIX GitHub at line 74 of file F04StackingAction.cc
void F04StackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 78 of file F04StackingAction.cc.
View newest version in sPHENIX GitHub at line 78 of file F04StackingAction.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04StackingAction.cc