ECCE @ EIC Software: G4QGSParticipants Class Reference
G4QGSParticipants Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4QGSParticipants.hh>
Classes
struct DeleteInteractionContent
struct DeletePartonPair
struct DeleteSplitableHadron
Public Member Functions
G4QGSParticipants ()
G4QGSParticipants (const G4QGSParticipants &right)
const G4QGSParticipants & operator= (const G4QGSParticipants &right)
virtual ~G4QGSParticipants ()
G4bool operator== (const G4QGSParticipants &right) const
G4bool operator!= (const G4QGSParticipants &right) const
virtual void DoLorentzBoost (G4ThreeVector aBoost)
G4PartonPair * GetNextPartonPair ()
void BuildInteractions (const G4ReactionProduct &thePrimary)
void StartPartonPairLoop ()
Public Member Functions inherited from G4VParticipants
G4VParticipants ()
G4VParticipants (const G4VParticipants &right)
virtual ~G4VParticipants ()
const G4VParticipants & operator= (const G4VParticipants &right)
G4bool operator== (const G4VParticipants &right) const
G4bool operator!= (const G4VParticipants &right) const
virtual void Init (G4int theZ, G4int theA)
virtual void SetNucleus (G4V3DNucleus *aNucleus)
virtual G4V3DNucleus * GetWoundedNucleus () const
virtual void InitProjectileNucleus (G4int theZ, G4int theA)
virtual void SetProjectileNucleus (G4V3DNucleus *aNucleus)
Protected Types
enum { SOFT, DIFFRACTIVE }
enum { ALL, WITHOUT_R, NON_DIFF }
enum {
PrD, TrD, DD, NonD,
Qexc
}
Protected Member Functions
virtual G4VSplitableHadron * SelectInteractions (const G4ReactionProduct &thePrimary)
void SplitHadrons ()
void PerformSoftCollisions ()
void PerformDiffractiveCollisions ()
G4bool DeterminePartonMomenta ()
G4double SampleX (G4double anXmin, G4int nSea, G4int theTotalSea, G4double aBeta)
Protected Attributes
std::vector
< G4InteractionContent * > theInteractions
std::vector< G4VSplitableHadron * > theTargets
std::vector< G4PartonPair * > thePartonPairs
G4QuarkExchange theQuarkExchange
G4SingleDiffractiveExcitation theSingleDiffExcitation
G4QGSDiffractiveExcitation theDiffExcitaton
G4int ModelMode
G4ThreeVector theBoost
const G4int nCutMax
const G4double ThresholdParameter
const G4double QGSMThreshold
const G4double theNucleonRadius
G4ThreeVector theCurrentVelocity
G4QGSMSplitableHadron * theProjectileSplitable
Private Member Functions
G4V3DNucleus * GetTargetNucleus () const
G4V3DNucleus * GetProjectileNucleus () const
void PrepareInitialState (const G4ReactionProduct &thePrimary)
void GetList (const G4ReactionProduct &thePrimary)
void StoreInvolvedNucleon ()
void ReggeonCascade ()
G4bool PutOnMassShell ()
void GetResiduals ()
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
G4bool ComputeNucleusProperties (G4V3DNucleus *nucleus, G4LorentzVector &nucleusMomentum, G4LorentzVector &residualMomentum, G4double &sumMasses, G4double &residualExcitationEnergy, G4double &residualMass, G4int &residualMassNumber, G4int &residualCharge)
G4bool GenerateDeltaIsobar (const G4double sqrtS, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4double &sumMasses)
G4bool SamplingNucleonKinematics (G4double averagePt2, const G4double maxPt2, G4double dCor, G4V3DNucleus *nucleus, const G4LorentzVector &pResidual, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4double &mass2)
G4bool CheckKinematics (const G4double sValue, const G4double sqrtS, const G4double projectileMass2, const G4double targetMass2, const G4double nucleusY, const G4bool isProjectileNucleus, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4double &targetWminus, G4double &projectileWplus, G4bool &success)
G4bool FinalizeKinematics (const G4double w, const G4bool isProjectileNucleus, const G4LorentzRotation &boostFromCmsToLab, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon *involvedNucleons[], G4LorentzVector &residual4Momentum)
void CreateStrings ()
void SetCofNuclearDestruction (const G4double aValue)
void SetR2ofNuclearDestruction (const G4double aValue)
void SetExcitationEnergyPerWoundedNucleon (const G4double aValue)
void SetDofNuclearDestruction (const G4double aValue)
void SetPt2ofNuclearDestruction (const G4double aValue)
void SetMaxPt2ofNuclearDestruction (const G4double aValue)
G4double GetCofNuclearDestruction ()
G4double GetR2ofNuclearDestruction ()
G4double GetExcitationEnergyPerWoundedNucleon ()
G4double GetDofNuclearDestruction ()
G4double GetPt2ofNuclearDestruction ()
G4double GetMaxPt2ofNuclearDestruction ()
Private Attributes
G4ReactionProduct theProjectile
G4Reggeons * Regge
G4int InteractionMode
G4double alpha
G4double beta
G4double sigmaPt
G4Nucleon * TheInvolvedNucleonsOfTarget [250]
G4int NumberOfInvolvedNucleonsOfTarget
G4Nucleon * TheInvolvedNucleonsOfProjectile [250]
G4int NumberOfInvolvedNucleonsOfProjectile
G4LorentzVector ProjectileResidual4Momentum
G4int ProjectileResidualMassNumber
G4int ProjectileResidualCharge
G4double ProjectileResidualExcitationEnergy
G4LorentzVector TargetResidual4Momentum
G4int TargetResidualMassNumber
G4int TargetResidualCharge
G4double TargetResidualExcitationEnergy
G4double CofNuclearDestruction
G4double R2ofNuclearDestruction
G4double ExcitationEnergyPerWoundedNucleon
G4double DofNuclearDestruction
G4double Pt2ofNuclearDestruction
G4double MaxPt2ofNuclearDestruction
Additional Inherited Members
Public Attributes inherited from G4VParticipants
G4V3DNucleus * theNucleus
G4V3DNucleus * theProjectileNucleus
Detailed Description
Definition at line 44 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 44 of file G4QGSParticipants.hh
Member Enumeration Documentation
anonymous enum protected
Enumerator:
SOFT
DIFFRACTIVE
Definition at line 157 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 157 of file G4QGSParticipants.hh
anonymous enum protected
Enumerator:
ALL
WITHOUT_R
NON_DIFF
Definition at line 158 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 158 of file G4QGSParticipants.hh
anonymous enum protected
Enumerator:
PrD
TrD
DD
NonD
Qexc
Definition at line 159 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 159 of file G4QGSParticipants.hh
Constructor & Destructor Documentation
G4QGSParticipants::G4QGSParticipants ()
Definition at line 49 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 49 of file G4QGSParticipants.cc
References fermi, GeV, MeV, SetCofNuclearDestruction(), SetDofNuclearDestruction(), SetExcitationEnergyPerWoundedNucleon(), SetMaxPt2ofNuclearDestruction(), SetPt2ofNuclearDestruction(), SetR2ofNuclearDestruction(), sigmaPt, and sqr().
G4QGSParticipants::G4QGSParticipants (const G4QGSParticipants & right)
Definition at line 65 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 65 of file G4QGSParticipants.cc
G4QGSParticipants::~G4QGSParticipants () virtual
Definition at line 71 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 71 of file G4QGSParticipants.cc
Member Function Documentation
void G4QGSParticipants::BuildInteractions (const G4ReactionProduct & thePrimary)
Definition at line 73 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 73 of file G4QGSParticipants.cc
References kdfinder::abs(), CreateStrings(), DeterminePartonMomenta(), G4cout, G4endl, G4Nucleon::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4V3DNucleus::GetCharge(), G4ReactionProduct::GetDefinition(), GetList(), G4V3DNucleus::GetMassNumber(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), GetResiduals(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::GetStatus(), G4ReactionProduct::GetTotalEnergy(), NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, PerformDiffractiveCollisions(), PrepareInitialState(), ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, PutOnMassShell(), Regge, ReggeonCascade(), SelectInteractions(), CLHEP::HepLorentzVector::setE(), G4VParticipants::SetProjectileNucleus(), CLHEP::HepLorentzVector::setVect(), SplitHadrons(), G4V3DNucleus::StartLoop(), StoreInvolvedNucleon(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, theInteractions, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, G4VParticipants::theNucleus, theProjectile, theProjectileSplitable, theTargets, and tmp.
G4bool G4QGSParticipants::CheckKinematics (const G4double sValue, const G4double sqrtS, const G4double projectileMass2, const G4double targetMass2, const G4double nucleusY, const G4bool isProjectileNucleus, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4double & targetWminus, G4double & projectileWplus, G4bool & success) private
Definition at line 1268 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 1268 of file G4QGSParticipants.cc
References kdfinder::abs(), e, e5, G4cout, G4endl, G4Log(), G4Nucleon::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), sqr(), tmp, CLHEP::HepLorentzVector::x(), x, CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by PutOnMassShell().
G4bool G4QGSParticipants::ComputeNucleusProperties (G4V3DNucleus * nucleus, G4LorentzVector & nucleusMomentum, G4LorentzVector & residualMomentum, G4double & sumMasses, G4double & residualExcitationEnergy, G4double & residualMass, G4int & residualMassNumber, G4int & residualCharge) private
Definition at line 997 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 997 of file G4QGSParticipants.cc
References kdfinder::abs(), G4Nucleon::AreYouHit(), G4cout, G4endl, G4Log(), G4UniformRand, G4Nucleon::Get4Momentum(), G4Nucleon::GetDefinition(), GetExcitationEnergyPerWoundedNucleon(), G4ParticleTable::GetIonTable(), G4V3DNucleus::GetNextNucleon(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), GeV, MeV, CLHEP::HepLorentzVector::perp2(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), and G4V3DNucleus::StartLoop().
Referenced by PutOnMassShell().
void G4QGSParticipants::CreateStrings () private
Definition at line 2032 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 2032 of file G4QGSParticipants.cc
References G4PartonPair::DIFFRACTIVE, G4cout, G4endl, G4Parton::Get4Momentum(), G4QGSMSplitableHadron::GetNextAntiParton(), G4VSplitableHadron::GetNextAntiParton(), G4QGSMSplitableHadron::GetNextParton(), G4VSplitableHadron::GetNextParton(), G4InteractionContent::GetNumberOfSoftCollisions(), G4PartonPair::GetParton1(), G4PartonPair::GetParton2(), G4Parton::GetPDGcode(), G4VSplitableHadron::GetPosition(), G4InteractionContent::GetProjectile(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::GetStatus(), G4InteractionContent::GetTarget(), G4Parton::GetX(), CLHEP::HepLorentzVector::mag(), NumberOfInvolvedNucleonsOfTarget, G4PartonPair::PROJECTILE, G4PartonPair::SOFT, G4PartonPair::TARGET, theInteractions, TheInvolvedNucleonsOfTarget, thePartonPairs, and theProjectileSplitable.
Referenced by BuildInteractions().
G4bool G4QGSParticipants::DeterminePartonMomenta () protected
Definition at line 1496 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 1496 of file G4QGSParticipants.cc
References kdfinder::abs(), beta, CLHEP::HepLorentzVector::boostVector(), CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4Exception(), G4Gamma::GammaDefinition(), GaussianPt(), G4VSplitableHadron::Get4Momentum(), G4Parton::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4VSplitableHadron::GetDefinition(), G4Parton::GetDefinition(), G4ReactionProduct::GetDefinition(), G4QGSMSplitableHadron::GetNextAntiParton(), G4QGSMSplitableHadron::GetNextParton(), G4ParticleDefinition::GetParticleName(), G4VSplitableHadron::GetSoftCollisionCount(), G4VSplitableHadron::GetStatus(), JustWarning, G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), MeV, CLHEP::HepLorentzVector::minus(), G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), G4PionZero::PionZeroDefinition(), CLHEP::HepLorentzVector::pz(), CLHEP::HepLorentzVector::rotateY(), CLHEP::HepLorentzVector::rotateZ(), S(), SampleX(), G4Parton::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sigmaPt, sqr(), theProjectile, theProjectileSplitable, theTargets, tmp, CLHEP::HepLorentzRotation::transform(), CLHEP::HepLorentzVector::transform(), CLHEP::Hep3Vector::x(), Xmin, CLHEP::Hep3Vector::y(), CLHEP::HepLorentzVector::z(), and z.
Referenced by BuildInteractions().
virtual void G4QGSParticipants::DoLorentzBoost (G4ThreeVector aBoost) inline virtual
Definition at line 55 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 55 of file G4QGSParticipants.hh
References G4V3DNucleus::DoLorentzBoost(), theBoost, theCurrentVelocity, and G4VParticipants::theNucleus.
Referenced by PrepareInitialState().
G4bool G4QGSParticipants::FinalizeKinematics (const G4double w, const G4bool isProjectileNucleus, const G4LorentzRotation & boostFromCmsToLab, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4LorentzVector & residual4Momentum) private
Definition at line 1345 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 1345 of file G4QGSParticipants.cc
References e, G4cout, G4endl, G4Nucleon::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4Nucleon::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), G4Nucleon::SetMomentum(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sqr(), tmp, CLHEP::HepLorentzVector::transform(), CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::HepLorentzVector::x(), x, CLHEP::Hep3Vector::y(), CLHEP::HepLorentzVector::y(), CLHEP::Hep3Vector::z(), and CLHEP::HepLorentzVector::z().
Referenced by PutOnMassShell().
G4ThreeVector G4QGSParticipants::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 980 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 980 of file G4QGSParticipants.cc
References G4Exp(), G4Log(), G4UniformRand, phi, and twopi.
Referenced by DeterminePartonMomenta(), and SamplingNucleonKinematics().
G4bool G4QGSParticipants::GenerateDeltaIsobar (const G4double sqrtS, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4double & sumMasses) private
Definition at line 1079 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 1079 of file G4QGSParticipants.cc
References kdfinder::abs(), G4ParticleTable::FindParticle(), G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), MeV, CLHEP::HepLorentzVector::perp2(), G4VSplitableHadron::SetDefinition(), and sqr().
Referenced by PutOnMassShell().
G4double G4QGSParticipants::GetCofNuclearDestruction () inline private
Definition at line 265 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 265 of file G4QGSParticipants.hh
References CofNuclearDestruction.
Referenced by ReggeonCascade().
G4double G4QGSParticipants::GetDofNuclearDestruction () inline private
Definition at line 277 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 277 of file G4QGSParticipants.hh
References DofNuclearDestruction.
Referenced by PutOnMassShell().
G4double G4QGSParticipants::GetExcitationEnergyPerWoundedNucleon () inline private
Definition at line 273 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 273 of file G4QGSParticipants.hh
References ExcitationEnergyPerWoundedNucleon.
Referenced by ComputeNucleusProperties().
void G4QGSParticipants::GetList (const G4ReactionProduct & thePrimary) private
Definition at line 295 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 295 of file G4QGSParticipants.cc
References ALL, G4V3DNucleus::ChooseImpactXandY(), DD, fermi, G4cout, G4endl, G4QGSParticipants_NPart, G4UniformRand, G4Nucleon::Get4Momentum(), G4Nucleon::GetDefinition(), G4V3DNucleus::GetMassNumber(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4V3DNucleus::GetOuterRadius(), G4ParticleDefinition::GetParticleName(), G4Nucleon::GetPosition(), G4Reggeons::GetProbabilities(), G4InteractionContent::GetStatus(), G4VSplitableHadron::GetStatus(), G4InteractionContent::GetTarget(), G4InteractionContent::GetTargetNucleon(), G4ReactionProduct::GetTotalEnergy(), GeV, G4Nucleon::Hit(), G4VSplitableHadron::IncrementCollisionCount(), InteractionMode, CLHEP::Hep3Vector::mag(), MeV, G4Reggeons::ncPomerons(), NON_DIFF, NonD, PrD, Qexc, Regge, Scale(), G4VSplitableHadron::SetCollisionCount(), G4InteractionContent::SetNumberOfDiffractiveCollisions(), G4InteractionContent::SetNumberOfSoftCollisions(), G4Nucleon::SetPosition(), G4Reggeons::SetS(), G4InteractionContent::SetStatus(), G4VSplitableHadron::SetStatus(), G4InteractionContent::SetTarget(), G4InteractionContent::SetTargetNucleon(), sqr(), G4V3DNucleus::StartLoop(), theInteractions, theNucleonRadius, G4VParticipants::theNucleus, theProjectileSplitable, theTargets, TrD, TRUE, WITHOUT_R, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by BuildInteractions().
G4double G4QGSParticipants::GetMaxPt2ofNuclearDestruction () inline private
Definition at line 285 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 285 of file G4QGSParticipants.hh
References MaxPt2ofNuclearDestruction.
Referenced by PutOnMassShell().
G4PartonPair * G4QGSParticipants::GetNextPartonPair () inline
Definition at line 212 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 212 of file G4QGSParticipants.hh
References thePartonPairs.
G4V3DNucleus * G4QGSParticipants::GetProjectileNucleus () const inline private virtual
Reimplemented from G4VParticipants.
Definition at line 233 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 233 of file G4QGSParticipants.hh
Referenced by GetResiduals(), and PutOnMassShell().
G4double G4QGSParticipants::GetPt2ofNuclearDestruction () inline private
Definition at line 281 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 281 of file G4QGSParticipants.hh
References Pt2ofNuclearDestruction.
Referenced by PutOnMassShell().
G4double G4QGSParticipants::GetR2ofNuclearDestruction () inline private
Definition at line 269 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 269 of file G4QGSParticipants.hh
References R2ofNuclearDestruction.
Referenced by ReggeonCascade().
void G4QGSParticipants::GetResiduals () private
Definition at line 2179 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 2179 of file G4QGSParticipants.cc
References G4Nucleon::AreYouHit(), CLHEP::HepLorentzVector::boost(), C(), E, CLHEP::HepLorentzVector::findBoostToCM(), G4cout, G4endl, G4Nucleon::Get4Momentum(), G4Nucleon::GetBindingEnergy(), G4Nucleon::GetDefinition(), G4V3DNucleus::GetNextNucleon(), G4ParticleDefinition::GetPDGMass(), GetProjectileNucleus(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::GetStatus(), GetTargetNucleus(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), NumberOfInvolvedNucleonsOfTarget, G4Nucleon::SetBindingEnergy(), CLHEP::HepLorentzVector::setE(), G4Nucleon::SetMomentum(), sqr(), G4V3DNucleus::StartLoop(), TargetResidual4Momentum, TargetResidualExcitationEnergy, TargetResidualMassNumber, TheInvolvedNucleonsOfTarget, tmp, and CLHEP::HepLorentzVector::vect().
Referenced by BuildInteractions().
G4V3DNucleus * G4QGSParticipants::GetTargetNucleus () const inline private
Definition at line 229 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 229 of file G4QGSParticipants.hh
References G4VParticipants::theNucleus.
Referenced by GetResiduals(), and PutOnMassShell().
G4bool G4QGSParticipants::operator!= (const G4QGSParticipants & right) const
const G4QGSParticipants& G4QGSParticipants::operator= (const G4QGSParticipants & right)
G4bool G4QGSParticipants::operator== (const G4QGSParticipants & right) const
void G4QGSParticipants::PerformDiffractiveCollisions () protected
Definition at line 1419 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 1419 of file G4QGSParticipants.cc
References DD, G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), FALSE, G4cout, G4endl, G4VSplitableHadron::Get4Momentum(), G4InteractionContent::GetTarget(), CLHEP::HepLorentzVector::mag(), PrD, Qexc, theDiffExcitaton, theInteractions, theProjectileSplitable, theQuarkExchange, theSingleDiffExcitation, TrD, and TRUE.
Referenced by BuildInteractions().
void G4QGSParticipants::PerformSoftCollisions () protected
Definition at line 2296 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 2296 of file G4QGSParticipants.cc
References G4cout, G4endl, G4Parton::Get4Momentum(), G4VSplitableHadron::GetNextAntiParton(), G4VSplitableHadron::GetNextParton(), G4InteractionContent::GetNumberOfSoftCollisions(), G4PartonPair::GetParton1(), G4PartonPair::GetParton2(), G4Parton::GetPDGcode(), G4InteractionContent::GetProjectile(), G4InteractionContent::GetTarget(), G4Parton::GetX(), G4PartonPair::PROJECTILE, G4PartonPair::SOFT, G4PartonPair::TARGET, theInteractions, and thePartonPairs.
void G4QGSParticipants::PrepareInitialState (const G4ReactionProduct & thePrimary) private
Definition at line 238 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 238 of file G4QGSParticipants.cc
References G4Nucleon::AreYouHit(), DoLorentzBoost(), G4Nucleon::Get4Momentum(), G4V3DNucleus::GetCharge(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNextNucleon(), G4InteractionContent::GetProjectile(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::GetStatus(), G4Nucleon::Hit(), G4V3DNucleus::Init(), NumberOfInvolvedNucleonsOfTarget, G4Nucleon::SetPosition(), G4V3DNucleus::SortNucleonsIncZ(), G4V3DNucleus::StartLoop(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, theCurrentVelocity, theInteractions, G4VParticipants::theNucleus, theProjectile, and theTargets.
Referenced by BuildInteractions().
G4bool G4QGSParticipants::PutOnMassShell () private
Definition at line 652 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 652 of file G4QGSParticipants.cc
References CLHEP::HepLorentzVector::boostVector(), CheckKinematics(), ComputeNucleusProperties(), FinalizeKinematics(), G4cout, G4endl, G4Exception(), GenerateDeltaIsobar(), G4V3DNucleus::GetCharge(), G4ReactionProduct::GetDefinition(), GetDofNuclearDestruction(), G4V3DNucleus::GetMassNumber(), GetMaxPt2ofNuclearDestruction(), G4ReactionProduct::GetMomentum(), G4ParticleDefinition::GetParticleName(), GetProjectileNucleus(), GetPt2ofNuclearDestruction(), GetTargetNucleus(), G4ReactionProduct::GetTotalEnergy(), GeV, JustWarning, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, NumberOfInvolvedNucleonsOfProjectile, NumberOfInvolvedNucleonsOfTarget, CLHEP::HepLorentzVector::perp2(), ProjectileResidual4Momentum, ProjectileResidualCharge, ProjectileResidualExcitationEnergy, ProjectileResidualMassNumber, CLHEP::HepLorentzVector::rapidity(), S(), SamplingNucleonKinematics(), G4VSplitableHadron::Set4Momentum(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), sqr(), TargetResidual4Momentum, TargetResidualCharge, TargetResidualExcitationEnergy, TargetResidualMassNumber, TheInvolvedNucleonsOfProjectile, TheInvolvedNucleonsOfTarget, theProjectile, theProjectileSplitable, and CLHEP::HepLorentzVector::transform().
Referenced by BuildInteractions().
void G4QGSParticipants::ReggeonCascade () private
Definition at line 583 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 583 of file G4QGSParticipants.cc
References G4Nucleon::AreYouHit(), fermi, G4cout, G4endl, G4Exp(), G4UniformRand, GetCofNuclearDestruction(), G4Nucleon::GetDefinition(), G4V3DNucleus::GetNextNucleon(), G4ParticleDefinition::GetParticleName(), G4Nucleon::GetPosition(), GetR2ofNuclearDestruction(), G4Nucleon::GetSplitableHadron(), G4VSplitableHadron::GetTimeOfCreation(), G4Nucleon::Hit(), NumberOfInvolvedNucleonsOfTarget, G4VSplitableHadron::SetCollisionCount(), G4InteractionContent::SetNumberOfDiffractiveCollisions(), G4InteractionContent::SetNumberOfSoftCollisions(), G4InteractionContent::SetStatus(), G4VSplitableHadron::SetStatus(), G4InteractionContent::SetTarget(), G4InteractionContent::SetTargetNucleon(), G4VSplitableHadron::SetTimeOfCreation(), sqr(), G4V3DNucleus::StartLoop(), theInteractions, TheInvolvedNucleonsOfTarget, G4VParticipants::theNucleus, theProjectileSplitable, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by BuildInteractions().
G4double G4QGSParticipants::SampleX (G4double anXmin, G4int nSea, G4int theTotalSea, G4double aBeta) protected
Definition at line 2007 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 2007 of file G4QGSParticipants.cc
References alpha, G4UniformRand, G4Pow::GetInstance(), G4Pow::powA(), r1, r2, and Xmin.
Referenced by DeterminePartonMomenta().
G4bool G4QGSParticipants::SamplingNucleonKinematics (G4double averagePt2, const G4double maxPt2, G4double dCor, G4V3DNucleus * nucleus, const G4LorentzVector & pResidual, const G4double residualMass, const G4int residualMassNumber, const G4int numberOfInvolvedNucleons, G4Nucleon * involvedNucleons[], G4double & mass2) private
Definition at line 1145 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 1145 of file G4QGSParticipants.cc
References Acts::Test::delta, CLHEP::HepLorentzVector::e(), G4cout, G4endl, GaussianPt(), G4Nucleon::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetSplitableHadron(), GeV, CLHEP::HepLorentzVector::perp2(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), G4Nucleon::SetMomentum(), sqr(), tmp, CLHEP::Hep3Vector::x(), CLHEP::HepLorentzVector::x(), x, CLHEP::Hep3Vector::y(), and CLHEP::HepLorentzVector::y().
Referenced by PutOnMassShell().
G4VSplitableHadron * G4QGSParticipants::SelectInteractions (const G4ReactionProduct & thePrimary) protected virtual
Reimplemented in G4GammaParticipants.
Definition at line 2355 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 2355 of file G4QGSParticipants.cc
References DIFFRACTIVE, G4cout, G4endl, G4UniformRand, G4ReactionProduct::GetMass(), G4V3DNucleus::GetMassNumber(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4VSplitableHadron::GetStatus(), G4ReactionProduct::GetTotalEnergy(), G4Nucleon::Hit(), G4VSplitableHadron::IncrementCollisionCount(), ModelMode, QGSMThreshold, S(), G4VSplitableHadron::SetCollisionCount(), G4InteractionContent::SetNumberOfDiffractiveCollisions(), G4InteractionContent::SetNumberOfSoftCollisions(), G4InteractionContent::SetStatus(), G4VSplitableHadron::SetStatus(), G4InteractionContent::SetTarget(), G4InteractionContent::SetTargetNucleon(), SOFT, sqr(), G4V3DNucleus::StartLoop(), theInteractions, G4VParticipants::theNucleus, theProjectileSplitable, theTargets, ThresholdParameter, and TRUE.
Referenced by BuildInteractions().
void G4QGSParticipants::SetCofNuclearDestruction (const G4double aValue) inline private
Definition at line 240 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 240 of file G4QGSParticipants.hh
References CofNuclearDestruction.
Referenced by G4QGSParticipants().
void G4QGSParticipants::SetDofNuclearDestruction (const G4double aValue) inline private
Definition at line 252 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 252 of file G4QGSParticipants.hh
References DofNuclearDestruction.
Referenced by G4QGSParticipants().
void G4QGSParticipants::SetExcitationEnergyPerWoundedNucleon (const G4double aValue) inline private
Definition at line 248 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 248 of file G4QGSParticipants.hh
References ExcitationEnergyPerWoundedNucleon.
Referenced by G4QGSParticipants().
void G4QGSParticipants::SetMaxPt2ofNuclearDestruction (const G4double aValue) inline private
Definition at line 260 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 260 of file G4QGSParticipants.hh
References MaxPt2ofNuclearDestruction.
Referenced by G4QGSParticipants().
void G4QGSParticipants::SetPt2ofNuclearDestruction (const G4double aValue) inline private
Definition at line 256 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 256 of file G4QGSParticipants.hh
References Pt2ofNuclearDestruction.
Referenced by G4QGSParticipants().
void G4QGSParticipants::SetR2ofNuclearDestruction (const G4double aValue) inline private
Definition at line 244 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 244 of file G4QGSParticipants.hh
References R2ofNuclearDestruction.
Referenced by G4QGSParticipants().
void G4QGSParticipants::SplitHadrons () inline protected
Definition at line 220 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 220 of file G4QGSParticipants.hh
References theInteractions.
Referenced by BuildInteractions().
void G4QGSParticipants::StartPartonPairLoop () inline
Definition at line 208 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 208 of file G4QGSParticipants.hh
void G4QGSParticipants::StoreInvolvedNucleon () private
Definition at line 558 of file G4QGSParticipants.cc.
View newest version in sPHENIX GitHub at line 558 of file G4QGSParticipants.cc
References G4Nucleon::AreYouHit(), G4cout, G4endl, G4V3DNucleus::GetNextNucleon(), NumberOfInvolvedNucleonsOfTarget, G4V3DNucleus::StartLoop(), TheInvolvedNucleonsOfTarget, and G4VParticipants::theNucleus.
Referenced by BuildInteractions().
Member Data Documentation
G4double G4QGSParticipants::alpha private
Definition at line 175 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 175 of file G4QGSParticipants.hh
Referenced by SampleX().
G4double G4QGSParticipants::beta private
Definition at line 176 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 176 of file G4QGSParticipants.hh
Referenced by DeterminePartonMomenta().
G4double G4QGSParticipants::CofNuclearDestruction private
Definition at line 198 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 198 of file G4QGSParticipants.hh
Referenced by GetCofNuclearDestruction(), and SetCofNuclearDestruction().
G4double G4QGSParticipants::DofNuclearDestruction private
Definition at line 203 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 203 of file G4QGSParticipants.hh
Referenced by GetDofNuclearDestruction(), and SetDofNuclearDestruction().
G4double G4QGSParticipants::ExcitationEnergyPerWoundedNucleon private
Definition at line 201 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 201 of file G4QGSParticipants.hh
Referenced by GetExcitationEnergyPerWoundedNucleon(), and SetExcitationEnergyPerWoundedNucleon().
G4int G4QGSParticipants::InteractionMode private
Definition at line 173 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 173 of file G4QGSParticipants.hh
Referenced by GetList().
G4double G4QGSParticipants::MaxPt2ofNuclearDestruction private
Definition at line 205 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 205 of file G4QGSParticipants.hh
Referenced by GetMaxPt2ofNuclearDestruction(), and SetMaxPt2ofNuclearDestruction().
G4int G4QGSParticipants::ModelMode protected
Definition at line 150 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 150 of file G4QGSParticipants.hh
Referenced by G4GammaParticipants::SelectInteractions(), and SelectInteractions().
const G4int G4QGSParticipants::nCutMax protected
Definition at line 161 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 161 of file G4QGSParticipants.hh
G4int G4QGSParticipants::NumberOfInvolvedNucleonsOfProjectile private
Definition at line 184 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 184 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and PutOnMassShell().
G4int G4QGSParticipants::NumberOfInvolvedNucleonsOfTarget private
Definition at line 181 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 181 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), CreateStrings(), GetResiduals(), PrepareInitialState(), PutOnMassShell(), ReggeonCascade(), and StoreInvolvedNucleon().
G4LorentzVector G4QGSParticipants::ProjectileResidual4Momentum private
Definition at line 186 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 186 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and PutOnMassShell().
G4int G4QGSParticipants::ProjectileResidualCharge private
Definition at line 188 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 188 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and PutOnMassShell().
G4double G4QGSParticipants::ProjectileResidualExcitationEnergy private
Definition at line 189 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 189 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and PutOnMassShell().
G4int G4QGSParticipants::ProjectileResidualMassNumber private
Definition at line 187 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 187 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and PutOnMassShell().
G4double G4QGSParticipants::Pt2ofNuclearDestruction private
Definition at line 204 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 204 of file G4QGSParticipants.hh
Referenced by GetPt2ofNuclearDestruction(), and SetPt2ofNuclearDestruction().
const G4double G4QGSParticipants::QGSMThreshold protected
Definition at line 163 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 163 of file G4QGSParticipants.hh
Referenced by G4GammaParticipants::SelectInteractions(), and SelectInteractions().
G4double G4QGSParticipants::R2ofNuclearDestruction private
Definition at line 199 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 199 of file G4QGSParticipants.hh
Referenced by GetR2ofNuclearDestruction(), and SetR2ofNuclearDestruction().
G4Reggeons* G4QGSParticipants::Regge private
Definition at line 172 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 172 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and GetList().
G4double G4QGSParticipants::sigmaPt private
Definition at line 178 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 178 of file G4QGSParticipants.hh
Referenced by DeterminePartonMomenta(), and G4QGSParticipants().
G4LorentzVector G4QGSParticipants::TargetResidual4Momentum private
Definition at line 191 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 191 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), GetResiduals(), PrepareInitialState(), and PutOnMassShell().
G4int G4QGSParticipants::TargetResidualCharge private
Definition at line 193 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 193 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), PrepareInitialState(), and PutOnMassShell().
G4double G4QGSParticipants::TargetResidualExcitationEnergy private
Definition at line 194 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 194 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), GetResiduals(), PrepareInitialState(), and PutOnMassShell().
G4int G4QGSParticipants::TargetResidualMassNumber private
Definition at line 192 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 192 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), GetResiduals(), PrepareInitialState(), and PutOnMassShell().
G4ThreeVector G4QGSParticipants::theBoost protected
Definition at line 152 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 152 of file G4QGSParticipants.hh
Referenced by DoLorentzBoost().
G4ThreeVector G4QGSParticipants::theCurrentVelocity protected
Definition at line 166 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 166 of file G4QGSParticipants.hh
Referenced by DoLorentzBoost(), and PrepareInitialState().
G4QGSDiffractiveExcitation G4QGSParticipants::theDiffExcitaton protected
Definition at line 149 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 149 of file G4QGSParticipants.hh
Referenced by PerformDiffractiveCollisions().
std::vector<G4InteractionContent*> G4QGSParticipants::theInteractions protected
Definition at line 141 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 141 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), CreateStrings(), GetList(), PerformDiffractiveCollisions(), PerformSoftCollisions(), PrepareInitialState(), ReggeonCascade(), G4GammaParticipants::SelectInteractions(), SelectInteractions(), and SplitHadrons().
G4Nucleon* G4QGSParticipants::TheInvolvedNucleonsOfProjectile[250] private
Definition at line 183 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 183 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), and PutOnMassShell().
G4Nucleon* G4QGSParticipants::TheInvolvedNucleonsOfTarget[250] private
Definition at line 180 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 180 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), CreateStrings(), GetResiduals(), PutOnMassShell(), ReggeonCascade(), and StoreInvolvedNucleon().
const G4double G4QGSParticipants::theNucleonRadius protected
Definition at line 164 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 164 of file G4QGSParticipants.hh
Referenced by GetList().
std::vector<G4PartonPair*> G4QGSParticipants::thePartonPairs protected
Definition at line 145 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 145 of file G4QGSParticipants.hh
Referenced by CreateStrings(), GetNextPartonPair(), and PerformSoftCollisions().
G4ReactionProduct G4QGSParticipants::theProjectile private
Definition at line 170 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 170 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), DeterminePartonMomenta(), PrepareInitialState(), and PutOnMassShell().
G4QGSMSplitableHadron* G4QGSParticipants::theProjectileSplitable protected
Definition at line 167 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 167 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), CreateStrings(), DeterminePartonMomenta(), GetList(), PerformDiffractiveCollisions(), PutOnMassShell(), ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and SelectInteractions().
G4QuarkExchange G4QGSParticipants::theQuarkExchange protected
Definition at line 147 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 147 of file G4QGSParticipants.hh
Referenced by PerformDiffractiveCollisions().
G4SingleDiffractiveExcitation G4QGSParticipants::theSingleDiffExcitation protected
Definition at line 148 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 148 of file G4QGSParticipants.hh
Referenced by PerformDiffractiveCollisions().
std::vector<G4VSplitableHadron*> G4QGSParticipants::theTargets protected
Definition at line 143 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 143 of file G4QGSParticipants.hh
Referenced by BuildInteractions(), DeterminePartonMomenta(), GetList(), PrepareInitialState(), G4GammaParticipants::SelectInteractions(), and SelectInteractions().
const G4double G4QGSParticipants::ThresholdParameter protected
Definition at line 162 of file G4QGSParticipants.hh.
View newest version in sPHENIX GitHub at line 162 of file G4QGSParticipants.hh
Referenced by G4GammaParticipants::SelectInteractions(), and SelectInteractions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4QGSParticipants.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4QGSParticipants.cc