ECCE @ EIC Software: G4tgrVolumeDivision Class Reference
G4tgrVolumeDivision Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolumeDivision.hh>
Public Member Functions
G4tgrVolumeDivision (const std::vector< G4String > &wl)
~G4tgrVolumeDivision ()
G4tgrPlaceDivRep * GetPlaceDivision ()
Public Member Functions inherited from G4tgrVolume
G4tgrVolume ()
G4tgrVolume (const std::vector< G4String > &wl)
G4tgrVolume (const G4tgrVolume &vol)
virtual ~G4tgrVolume ()
virtual G4tgrPlace * AddPlace (const std::vector< G4String > &wl)
G4tgrPlaceDivRep * AddPlaceReplica (const std::vector< G4String > &wl)
G4tgrPlaceParameterisation * AddPlaceParam (const std::vector< G4String > &wl)
void AddVisibility (const std::vector< G4String > &wl)
void AddRGBColour (const std::vector< G4String > &wl)
void AddCheckOverlaps (const std::vector< G4String > &wl)
const G4String & GetName () const
void SetName (const G4String &name)
const G4String & GetType () const
G4tgrSolid * GetSolid () const
const G4String & GetMaterialName () const
const std::vector< G4tgrPlace * > GetPlacements () const
G4bool GetVisibility () const
G4double * GetColour () const
G4double * GetRGBColour () const
G4bool GetCheckOverlaps () const
virtual G4tgrVolume * GetVolume (G4int ii) const
Private Attributes
G4tgrPlaceDivRep * thePlaceDiv
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrVolumeDivision &obj)
Additional Inherited Members
Protected Attributes inherited from G4tgrVolume
G4String theName
G4String theType
G4String theMaterialName
G4tgrSolid * theSolid
std::vector< G4tgrPlace * > thePlacements
G4bool theVisibility
G4double * theRGBColour
G4bool theCheckOverlaps
Detailed Description
Definition at line 58 of file G4tgrVolumeDivision.hh.
View newest version in sPHENIX GitHub at line 58 of file G4tgrVolumeDivision.hh
Constructor & Destructor Documentation
G4tgrVolumeDivision::G4tgrVolumeDivision (const std::vector< G4String > & wl)
Definition at line 52 of file G4tgrVolumeDivision.cc.
View newest version in sPHENIX GitHub at line 52 of file G4tgrVolumeDivision.cc
References G4tgrPlaceDivRep::BuildAxis(), G4tgrUtils::CheckWLsize(), DivByNdiv, DivByNdivAndWidth, DivByWidth, FatalException, G4tgrVolumeMgr::FindVolume(), G4cout, G4endl, G4Exception(), G4tgrUtils::GetDouble(), G4tgrVolumeMgr::GetInstance(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), mm, G4tgrVolumeMgr::RegisterParentChild(), G4tgrPlaceDivRep::SetAxis(), G4tgrPlaceDivRep::SetDivType(), G4tgrPlaceDivRep::SetNDiv(), G4tgrPlaceDivRep::SetOffset(), G4tgrPlaceDivRep::SetParentName(), G4tgrPlace::SetType(), G4tgrPlace::SetVolume(), G4tgrPlaceDivRep::SetWidth(), G4tgrVolume::theMaterialName, G4tgrVolume::theName, thePlaceDiv, G4tgrVolume::theRGBColour, G4tgrVolume::theSolid, G4tgrVolume::theType, G4tgrVolume::theVisibility, WLSIZE_GE, and WLSIZE_LE.
G4tgrVolumeDivision::~G4tgrVolumeDivision ()
Definition at line 47 of file G4tgrVolumeDivision.cc.
View newest version in sPHENIX GitHub at line 47 of file G4tgrVolumeDivision.cc
Member Function Documentation
G4tgrPlaceDivRep* G4tgrVolumeDivision::GetPlaceDivision () inline
Definition at line 69 of file G4tgrVolumeDivision.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgrVolumeDivision.hh
References thePlaceDiv.
Referenced by G4tgbVolume::ConstructG4PhysVol().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrVolumeDivision & obj) friend
Definition at line 152 of file G4tgrVolumeDivision.cc.
View newest version in sPHENIX GitHub at line 152 of file G4tgrVolumeDivision.cc
Member Data Documentation
G4tgrPlaceDivRep* G4tgrVolumeDivision::thePlaceDiv private
Definition at line 75 of file G4tgrVolumeDivision.hh.
View newest version in sPHENIX GitHub at line 75 of file G4tgrVolumeDivision.hh
Referenced by G4tgrVolumeDivision(), GetPlaceDivision(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolumeDivision.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrVolumeDivision.cc