ECCE @ EIC Software: G4PhotonEvaporation Class Reference
G4PhotonEvaporation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4PhotonEvaporation.hh>
Public Member Functions
G4PhotonEvaporation (G4GammaTransition *ptr=nullptr)
virtual ~G4PhotonEvaporation ()
virtual void Initialise () final
virtual G4Fragment * EmittedFragment (G4Fragment *theNucleus) final
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus) final
G4FragmentVector * BreakItUp (const G4Fragment &theNucleus)
virtual G4double GetEmissionProbability (G4Fragment *theNucleus) final
virtual G4double GetFinalLevelEnergy (G4int Z, G4int A, G4double energy) final
virtual G4double GetUpperLevelEnergy (G4int Z, G4int A) final
void SetGammaTransition (G4GammaTransition *)
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetVerboseLevel (G4int verbose)
G4int GetVacantShellNumber () const
G4PhotonEvaporation (const G4PhotonEvaporation &right)=delete
const G4PhotonEvaporation & operator= (const G4PhotonEvaporation &right)=delete
Public Member Functions inherited from G4VEvaporationChannel
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void Dump () const
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Private Member Functions
void InitialiseGRData ()
G4Fragment * GenerateGamma (G4Fragment *nucleus)
void InitialiseLevelManager (G4int Z, G4int A)
Private Attributes
G4NuclearLevelData * fNuclearLevelData
const G4LevelManager * fLevelManager
G4GammaTransition * fTransition
G4NuclearPolarization * fPolarization
G4int fVerbose
G4int theZ
G4int theA
G4int fPoints
G4int fCode
G4int vShellNumber
size_t fIndex
G4double fCummProbability [MAXDEPOINT]
G4double fLevelEnergyMax
G4double fExcEnergy
G4double fProbability
G4double fStep
G4double fMaxLifeTime
G4double Tolerance
G4bool fICM
G4bool fRDM
G4bool fSampleTime
G4bool fCorrelatedGamma
G4bool isInitialised
Static Private Attributes
static G4float GREnergy [MAXGRDATA] = {0.0f}
static G4float GRWidth [MAXGRDATA] = {0.0f}
Additional Inherited Members
Protected Attributes inherited from G4VEvaporationChannel
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 63 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PhotonEvaporation.hh
Constructor & Destructor Documentation
G4PhotonEvaporation::G4PhotonEvaporation (G4GammaTransition * ptr = nullptr) explicit
Definition at line 63 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 63 of file G4PhotonEvaporation.cc
References CLHEP::eV, f, fCode, fCummProbability, fExcEnergy, fLevelEnergyMax, fNuclearLevelData, fProbability, fStep, fTransition, G4NuclearLevelData::GetInstance(), GREnergy, InitialiseGRData(), MAXDEPOINT, theA, theZ, and Tolerance.
G4PhotonEvaporation::~G4PhotonEvaporation () virtual
Definition at line 83 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 83 of file G4PhotonEvaporation.cc
References fTransition.
G4PhotonEvaporation::G4PhotonEvaporation (const G4PhotonEvaporation & right) delete
Member Function Documentation
G4FragmentVector * G4PhotonEvaporation::BreakItUp (const G4Fragment & theNucleus)
Definition at line 176 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 176 of file G4PhotonEvaporation.cc
References BreakUpChain(), fVerbose, G4cout, and G4endl.
Referenced by G4ParticleHPCaptureFS::ApplyYourself().
G4bool G4PhotonEvaporation::BreakUpChain (G4FragmentVector * theResult, G4Fragment * theNucleus) final virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 188 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 188 of file G4PhotonEvaporation.cc
References fCorrelatedGamma, fPolarization, fRDM, fSampleTime, fVerbose, G4cout, G4endl, GenerateGamma(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetZ_asInt(), Initialise(), isInitialised, and G4Fragment::SetNuclearPolarization().
Referenced by BreakItUp().
G4Fragment * G4PhotonEvaporation::EmittedFragment (G4Fragment * theNucleus) final virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 127 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 127 of file G4PhotonEvaporation.cc
References fCorrelatedGamma, fIndex, G4NuclearPolarizationStore::FindOrBuild(), fPolarization, fRDM, fSampleTime, fVerbose, G4cout, G4endl, GenerateGamma(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearPolarizationStore::GetInstance(), G4Fragment::GetNuclearPolarization(), G4Fragment::GetZ_asInt(), Initialise(), isInitialised, G4NuclearPolarizationStore::RemoveMe(), and G4Fragment::SetNuclearPolarization().
Referenced by G4ITDecay::DecayIt().
G4Fragment * G4PhotonEvaporation::GenerateGamma (G4Fragment * nucleus) private
Definition at line 335 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 335 of file G4PhotonEvaporation.cc
References kdfinder::abs(), fCode, fCummProbability, fExcEnergy, fICM, G4NucLevel::FinalExcitationIndex(), fIndex, fLevelEnergyMax, fLevelManager, G4LevelManager::FloatingLevel(), fMaxLifeTime, fPoints, fPolarization, fProbability, fRDM, fSampleTime, fStep, fTransition, fVerbose, G4cout, G4endl, G4Log(), G4UniformRand, G4NucLevel::GammaProbability(), G4Fragment::GetA_asInt(), G4Fragment::GetCreationTime(), GetEmissionProbability(), G4Fragment::GetExcitationEnergy(), G4LevelManager::GetLevel(), G4Fragment::GetZ_asInt(), incremental_prev_tag::idx, Initialise(), InitialiseLevelManager(), isInitialised, G4LevelManager::LevelEnergy(), G4LevelManager::LifeTime(), G4NucLevel::MultipolarityRatio(), G4LevelManager::NearestLevelIndex(), G4NucLevel::NumberOfTransitions(), G4LevelManager::NumberOfTransitions(), CLHEP::prec, ratio, G4NucLevel::SampleGammaTransition(), G4NucLevel::SampleShell(), G4GammaTransition::SampleTransition(), G4Fragment::SetCreationTime(), G4NuclearPolarization::SetExcitationEnergy(), G4Fragment::SetFloatingLevelNumber(), G4Fragment::SetSpin(), G4LevelManager::SpinTwo(), theA, theZ, Acts::VectorHelpers::time(), Tolerance, G4NucLevel::TransitionType(), vShellNumber, and y.
Referenced by BreakUpChain(), and EmittedFragment().
G4double G4PhotonEvaporation::GetEmissionProbability (G4Fragment * theNucleus) final virtual
Implements G4VEvaporationChannel.
Definition at line 232 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 232 of file G4PhotonEvaporation.cc
References A(), kdfinder::abs(), G4Fragment::ComputeGroundStateMass(), emax, fCode, fCummProbability, fExcEnergy, fNuclearLevelData, fPoints, fProbability, fStep, fVerbose, G4cout, G4endl, G4Exp(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetZ_asInt(), GREnergy, GRWidth, CLHEP::hbarc, Initialise(), isInitialised, max, MAXDEPOINT, MAXGRDATA, CLHEP::MeV, CLHEP::millibarn, min, CLHEP::neutron_mass_c2, CLHEP::pi2, Tolerance, and Z.
Referenced by GenerateGamma().
G4double G4PhotonEvaporation::GetFinalLevelEnergy (G4int Z, G4int A, G4double energy) final virtual
Definition at line 317 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 317 of file G4PhotonEvaporation.cc
References E, energy, fIndex, fLevelEnergyMax, fLevelManager, InitialiseLevelManager(), G4LevelManager::NearestLevelEnergy(), and Tolerance.
G4double G4PhotonEvaporation::GetUpperLevelEnergy (G4int Z, G4int A) final virtual
Definition at line 328 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 328 of file G4PhotonEvaporation.cc
References fLevelEnergyMax, and InitialiseLevelManager().
G4int G4PhotonEvaporation::GetVacantShellNumber () const inline
Definition at line 170 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PhotonEvaporation.hh
References vShellNumber.
Referenced by G4ITDecay::DecayIt().
void G4PhotonEvaporation::Initialise () final virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 88 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 88 of file G4PhotonEvaporation.cc
References G4DeexPrecoParameters::CorrelatedGamma(), fCorrelatedGamma, fICM, fMaxLifeTime, fNuclearLevelData, fTransition, fVerbose, G4cout, G4endl, G4DeexPrecoParameters::GetInternalConversionFlag(), G4DeexPrecoParameters::GetMaxLifeTime(), G4DeexPrecoParameters::GetMinExcitation(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::GetTwoJMAX(), G4DeexPrecoParameters::GetVerbose(), isInitialised, G4GammaTransition::SetPolarizationFlag(), G4GammaTransition::SetTwoJMAX(), G4GammaTransition::SetVerbose(), and Tolerance.
Referenced by BreakUpChain(), EmittedFragment(), GenerateGamma(), and GetEmissionProbability().
void G4PhotonEvaporation::InitialiseGRData () private
Definition at line 108 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 108 of file G4PhotonEvaporation.cc
References A(), f, G4MUTEXLOCK, G4MUTEXUNLOCK, G4Pow::GetInstance(), GREnergy, GRWidth, MAXGRDATA, CLHEP::MeV, and G4Pow::powZ().
Referenced by G4PhotonEvaporation().
void G4PhotonEvaporation::InitialiseLevelManager (G4int Z, G4int A) inline private
Definition at line 159 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 159 of file G4PhotonEvaporation.hh
References A(), fIndex, fLevelEnergyMax, fLevelManager, fNuclearLevelData, G4NuclearLevelData::GetLevelManager(), G4LevelManager::MaxLevelEnergy(), theA, theZ, and Z.
Referenced by GenerateGamma(), GetFinalLevelEnergy(), and GetUpperLevelEnergy().
const G4PhotonEvaporation& G4PhotonEvaporation::operator= (const G4PhotonEvaporation & right) delete
void G4PhotonEvaporation::RDMForced (G4bool val) virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 556 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 556 of file G4PhotonEvaporation.cc
References fRDM.
Referenced by G4RadioactiveDecay::G4RadioactiveDecay(), and G4RadioactiveDecayBase::G4RadioactiveDecayBase().
void G4PhotonEvaporation::SetGammaTransition (G4GammaTransition * p)
Definition at line 543 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 543 of file G4PhotonEvaporation.cc
References fTransition.
void G4PhotonEvaporation::SetICM (G4bool val) virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 551 of file G4PhotonEvaporation.cc.
View newest version in sPHENIX GitHub at line 551 of file G4PhotonEvaporation.cc
References fICM.
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4RadioactiveDecay::G4RadioactiveDecay(), and G4RadioactiveDecayBase::G4RadioactiveDecayBase().
void G4PhotonEvaporation::SetVerboseLevel (G4int verbose) inline
Definition at line 153 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 153 of file G4PhotonEvaporation.hh
References fVerbose.
Member Data Documentation
G4int G4PhotonEvaporation::fCode private
Definition at line 125 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and GetEmissionProbability().
G4bool G4PhotonEvaporation::fCorrelatedGamma private
Definition at line 145 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 145 of file G4PhotonEvaporation.hh
Referenced by BreakUpChain(), EmittedFragment(), and Initialise().
G4double G4PhotonEvaporation::fCummProbability[MAXDEPOINT] private
Definition at line 132 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 132 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and GetEmissionProbability().
G4double G4PhotonEvaporation::fExcEnergy private
Definition at line 135 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 135 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and GetEmissionProbability().
G4bool G4PhotonEvaporation::fICM private
Definition at line 142 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PhotonEvaporation.hh
Referenced by GenerateGamma(), Initialise(), and SetICM().
size_t G4PhotonEvaporation::fIndex private
Definition at line 127 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PhotonEvaporation.hh
Referenced by EmittedFragment(), GenerateGamma(), GetFinalLevelEnergy(), and InitialiseLevelManager().
G4double G4PhotonEvaporation::fLevelEnergyMax private
Definition at line 134 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 134 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), GetFinalLevelEnergy(), GetUpperLevelEnergy(), and InitialiseLevelManager().
const G4LevelManager* G4PhotonEvaporation::fLevelManager private
Definition at line 114 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PhotonEvaporation.hh
Referenced by GenerateGamma(), GetFinalLevelEnergy(), and InitialiseLevelManager().
G4double G4PhotonEvaporation::fMaxLifeTime private
Definition at line 138 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 138 of file G4PhotonEvaporation.hh
Referenced by GenerateGamma(), and Initialise().
G4NuclearLevelData* G4PhotonEvaporation::fNuclearLevelData private
Definition at line 113 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GetEmissionProbability(), Initialise(), and InitialiseLevelManager().
G4int G4PhotonEvaporation::fPoints private
Definition at line 124 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PhotonEvaporation.hh
Referenced by GenerateGamma(), and GetEmissionProbability().
G4NuclearPolarization* G4PhotonEvaporation::fPolarization private
Definition at line 119 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PhotonEvaporation.hh
Referenced by BreakUpChain(), EmittedFragment(), and GenerateGamma().
G4double G4PhotonEvaporation::fProbability private
Definition at line 136 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 136 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and GetEmissionProbability().
G4bool G4PhotonEvaporation::fRDM private
Definition at line 143 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 143 of file G4PhotonEvaporation.hh
Referenced by BreakUpChain(), EmittedFragment(), GenerateGamma(), and RDMForced().
G4bool G4PhotonEvaporation::fSampleTime private
Definition at line 144 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 144 of file G4PhotonEvaporation.hh
Referenced by BreakUpChain(), EmittedFragment(), and GenerateGamma().
G4double G4PhotonEvaporation::fStep private
Definition at line 137 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 137 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and GetEmissionProbability().
G4GammaTransition* G4PhotonEvaporation::fTransition private
Definition at line 115 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), Initialise(), SetGammaTransition(), and ~G4PhotonEvaporation().
G4int G4PhotonEvaporation::fVerbose private
Definition at line 121 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PhotonEvaporation.hh
Referenced by BreakItUp(), BreakUpChain(), EmittedFragment(), GenerateGamma(), GetEmissionProbability(), Initialise(), and SetVerboseLevel().
G4float G4PhotonEvaporation::GREnergy = {0.0f} static private
Definition at line 129 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 129 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GetEmissionProbability(), and InitialiseGRData().
G4float G4PhotonEvaporation::GRWidth = {0.0f} static private
Definition at line 130 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PhotonEvaporation.hh
Referenced by GetEmissionProbability(), and InitialiseGRData().
G4bool G4PhotonEvaporation::isInitialised private
Definition at line 146 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 146 of file G4PhotonEvaporation.hh
Referenced by BreakUpChain(), EmittedFragment(), GenerateGamma(), GetEmissionProbability(), and Initialise().
G4int G4PhotonEvaporation::theA private
Definition at line 123 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 123 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and InitialiseLevelManager().
G4int G4PhotonEvaporation::theZ private
Definition at line 122 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 122 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), and InitialiseLevelManager().
G4double G4PhotonEvaporation::Tolerance private
Definition at line 140 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4PhotonEvaporation.hh
Referenced by G4PhotonEvaporation(), GenerateGamma(), GetEmissionProbability(), GetFinalLevelEnergy(), and Initialise().
G4int G4PhotonEvaporation::vShellNumber private
Definition at line 126 of file G4PhotonEvaporation.hh.
View newest version in sPHENIX GitHub at line 126 of file G4PhotonEvaporation.hh
Referenced by GenerateGamma(), and GetVacantShellNumber().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4PhotonEvaporation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/src/G4PhotonEvaporation.cc