ECCE @ EIC Software: G4VisCommandsTouchableSet Class Reference
G4VisCommandsTouchableSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsTouchableSet.hh>
Public Member Functions
G4VisCommandsTouchableSet ()
virtual ~G4VisCommandsTouchableSet ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4VisCommandsTouchableSet (const G4VisCommandsTouchableSet &)
G4VisCommandsTouchableSet & operator= (const G4VisCommandsTouchableSet &)
Private Attributes
G4UIcommand * fpCommandSetColour
G4UIcmdWithABool * fpCommandSetDaughtersInvisible
G4UIcmdWithABool * fpCommandSetForceAuxEdgeVisible
G4UIcmdWithAnInteger * fpCommandSetLineSegmentsPerCircle
G4UIcmdWithABool * fpCommandSetForceCloud
G4UIcmdWithABool * fpCommandSetForceSolid
G4UIcmdWithABool * fpCommandSetForceWireframe
G4UIcmdWithAString * fpCommandSetLineStyle
G4UIcmdWithADouble * fpCommandSetLineWidth
G4UIcmdWithAnInteger * fpCommandSetNumberOfCloudPoints
G4UIcmdWithABool * fpCommandSetVisibility
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommand
void SetViewParameters (G4VViewer *viewer, const G4ViewParameters &viewParams)
void RefreshIfRequired (G4VViewer *viewer)
void InterpolateViews (G4VViewer *currentViewer, std::vector< G4ViewParameters > viewVector, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
void InterpolateToNewView (G4VViewer *currentViewer, const G4ViewParameters &oldVP, const G4ViewParameters &newVP, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
const G4String & ConvertToColourGuidance ()
void ConvertToColour (G4Colour &colour, const G4String &redOrString, G4double green, G4double blue, G4double opacity)
G4bool ProvideValueOfUnit (const G4String &where, const G4String &unit, const G4String &category, G4double &value)
void CheckSceneAndNotifyHandlers (G4Scene *=nullptr)
void G4VisCommandsSceneAddUnsuccessful (G4VisManager::Verbosity verbosity)
void CopyGuidanceFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd, G4int startLine=0)
void CopyParametersFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd)
void DrawExtent (const G4VisExtent &)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 41 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VisCommandsTouchableSet.hh
Constructor & Destructor Documentation
G4VisCommandsTouchableSet::G4VisCommandsTouchableSet ()
Definition at line 43 of file G4VisCommandsTouchableSet.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VisCommandsTouchableSet.cc
References G4VVisCommand::ConvertToColourGuidance(), fpCommandSetColour, fpCommandSetDaughtersInvisible, fpCommandSetForceAuxEdgeVisible, fpCommandSetForceCloud, fpCommandSetForceSolid, fpCommandSetForceWireframe, fpCommandSetLineSegmentsPerCircle, fpCommandSetLineStyle, fpCommandSetLineWidth, fpCommandSetNumberOfCloudPoints, fpCommandSetVisibility, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), and G4UIcmdWithABool::SetParameterName().
G4VisCommandsTouchableSet::~G4VisCommandsTouchableSet () virtual
Definition at line 163 of file G4VisCommandsTouchableSet.cc.
View newest version in sPHENIX GitHub at line 163 of file G4VisCommandsTouchableSet.cc
References fpCommandSetColour, fpCommandSetDaughtersInvisible, fpCommandSetForceAuxEdgeVisible, fpCommandSetForceCloud, fpCommandSetForceSolid, fpCommandSetForceWireframe, fpCommandSetLineSegmentsPerCircle, fpCommandSetLineStyle, fpCommandSetLineWidth, fpCommandSetNumberOfCloudPoints, and fpCommandSetVisibility.
G4VisCommandsTouchableSet::G4VisCommandsTouchableSet (const G4VisCommandsTouchableSet &) private
Member Function Documentation
G4String G4VisCommandsTouchableSet::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 177 of file G4VisCommandsTouchableSet.cc.
View newest version in sPHENIX GitHub at line 177 of file G4VisCommandsTouchableSet.cc
G4VisCommandsTouchableSet& G4VisCommandsTouchableSet::operator= (const G4VisCommandsTouchableSet &) private
void G4VisCommandsTouchableSet::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 182 of file G4VisCommandsTouchableSet.cc.
View newest version in sPHENIX GitHub at line 182 of file G4VisCommandsTouchableSet.cc
References G4ViewParameters::AddVisAttributesModifier(), G4UImanager::ApplyCommand(), G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToInt(), G4VisAttributes::dashed, G4VisAttributes::dotted, G4VisManager::errors, G4cerr, G4endl, G4UImanager::GetUIpointer(), G4VViewer::GetViewParameters(), G4VisAttributes::SetColour(), G4VisAttributes::SetDaughtersInvisible(), G4VisAttributes::SetForceAuxEdgeVisible(), G4VisAttributes::SetForceCloud(), G4VisAttributes::SetForceLineSegmentsPerCircle(), G4VisAttributes::SetForceNumberOfCloudPoints(), G4VisAttributes::SetForceSolid(), G4VisAttributes::SetForceWireframe(), G4VisAttributes::SetLineStyle(), G4VisAttributes::SetLineWidth(), G4VisAttributes::SetVisibility(), G4VisAttributes::unbroken, G4ModelingParameters::VASColour, G4ModelingParameters::VASDaughtersInvisible, G4ModelingParameters::VASForceAuxEdgeVisible, G4ModelingParameters::VASForceCloud, G4ModelingParameters::VASForceLineSegmentsPerCircle, G4ModelingParameters::VASForceNumberOfCloudPoints, G4ModelingParameters::VASForceSolid, G4ModelingParameters::VASForceWireframe, G4ModelingParameters::VASLineStyle, G4ModelingParameters::VASLineWidth, and G4ModelingParameters::VASVisibility.
Member Data Documentation
G4UIcommand* G4VisCommandsTouchableSet::fpCommandSetColour private
Definition at line 50 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithABool* G4VisCommandsTouchableSet::fpCommandSetDaughtersInvisible private
Definition at line 51 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithABool* G4VisCommandsTouchableSet::fpCommandSetForceAuxEdgeVisible private
Definition at line 52 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithABool* G4VisCommandsTouchableSet::fpCommandSetForceCloud private
Definition at line 54 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithABool* G4VisCommandsTouchableSet::fpCommandSetForceSolid private
Definition at line 55 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithABool* G4VisCommandsTouchableSet::fpCommandSetForceWireframe private
Definition at line 56 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithAnInteger* G4VisCommandsTouchableSet::fpCommandSetLineSegmentsPerCircle private
Definition at line 53 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithAString* G4VisCommandsTouchableSet::fpCommandSetLineStyle private
Definition at line 57 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithADouble* G4VisCommandsTouchableSet::fpCommandSetLineWidth private
Definition at line 58 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithAnInteger* G4VisCommandsTouchableSet::fpCommandSetNumberOfCloudPoints private
Definition at line 59 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
G4UIcmdWithABool* G4VisCommandsTouchableSet::fpCommandSetVisibility private
Definition at line 60 of file G4VisCommandsTouchableSet.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VisCommandsTouchableSet.hh
Referenced by G4VisCommandsTouchableSet(), and ~G4VisCommandsTouchableSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsTouchableSet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsTouchableSet.cc