ECCE @ EIC Software: F03FieldSetup Class Reference
F03FieldSetup Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field03/include/F03FieldSetup.hh>
Public Member Functions
F03FieldSetup ()
virtual ~F03FieldSetup ()
void SetStepperType (G4int i)
void CreateSteppers ()
void SetMinStep (G4double s)
void SetFieldValue (G4ThreeVector fieldVector)
void SetFieldZValue (G4double fieldValue)
void SetLocalFieldValue (G4ThreeVector fieldVector)
G4ThreeVector GetGlobalFieldValue () const
G4ThreeVector GetLocalFieldValue () const
void UpdateField ()
G4FieldManager * GetLocalFieldManager ()
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
G4ThreeVector GetConstantFieldValue (G4MagneticField *magneticField) const
Protected Attributes
G4FieldManager * fFieldManager
G4FieldManager * fLocalFieldManager
G4ChordFinder * fChordFinder
G4ChordFinder * fLocalChordFinder
G4Mag_UsualEqRhs * fEquation
G4Mag_UsualEqRhs * fLocalEquation
G4MagneticField * fMagneticField
G4MagneticField * fLocalMagneticField
G4MagIntegratorStepper * fStepper
G4MagIntegratorStepper * fLocalStepper
G4int fStepperType
G4double fMinStep
F03FieldMessenger * fFieldMessenger
Detailed Description
A class for setting up the Magnetic Field
It also creates the necessary classes to control accuracy of propagation. In this example
There is a global field for most of the setup;
A local field overides it for some volume(s) and it assumed to be uniform.
Definition at line 55 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 55 of file F03FieldSetup.hh
Constructor & Destructor Documentation
F03FieldSetup::F03FieldSetup ()
Definition at line 65 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 65 of file F03FieldSetup.cc
References fEquation, fFieldManager, fFieldMessenger, fLocalEquation, fLocalFieldManager, fLocalMagneticField, fMagneticField, fMinStep, fStepperType, GetGlobalFieldManager(), mm, tesla, and UpdateField().
F03FieldSetup::~F03FieldSetup () virtual
Definition at line 101 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 101 of file F03FieldSetup.cc
References fChordFinder, fFieldMessenger, fMagneticField, and fStepper.
Member Function Documentation
void F03FieldSetup::CreateSteppers ()
Definition at line 146 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 146 of file F03FieldSetup.cc
References fEquation, fLocalEquation, fLocalStepper, fStepper, fStepperType, G4cout, and G4endl.
Referenced by UpdateField().
G4ThreeVector F03FieldSetup::GetConstantFieldValue (G4MagneticField * magneticField) const protected
Definition at line 283 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 283 of file F03FieldSetup.cc
References G4MagneticField::GetFieldValue().
Referenced by GetGlobalFieldValue(), and GetLocalFieldValue().
G4FieldManager * F03FieldSetup::GetGlobalFieldManager () protected
Definition at line 275 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 275 of file F03FieldSetup.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by F03FieldSetup(), and SetFieldValue().
G4ThreeVector F03FieldSetup::GetGlobalFieldValue () const inline
Definition at line 70 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 70 of file F03FieldSetup.hh
References fMagneticField, and GetConstantFieldValue().
Referenced by F03FieldMessenger::SetNewValue().
G4FieldManager* F03FieldSetup::GetLocalFieldManager () inline
Definition at line 75 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 75 of file F03FieldSetup.hh
References fLocalFieldManager.
Referenced by F03DetectorConstruction::ConstructSDandField(), and SetLocalFieldValue().
G4ThreeVector F03FieldSetup::GetLocalFieldValue () const inline
Definition at line 71 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 71 of file F03FieldSetup.hh
References fLocalMagneticField, and GetConstantFieldValue().
Referenced by F03FieldMessenger::SetNewValue().
void F03FieldSetup::SetFieldValue (G4ThreeVector fieldVector)
Definition at line 220 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 220 of file F03FieldSetup.cc
References fEquation, fMagneticField, GetGlobalFieldManager(), G4FieldManager::SetDetectorField(), and G4EquationOfMotion::SetFieldObj().
Referenced by SetFieldZValue(), and F03FieldMessenger::SetNewValue().
void F03FieldSetup::SetFieldZValue (G4double fieldValue)
Definition at line 212 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 212 of file F03FieldSetup.cc
References SetFieldValue().
Referenced by F03FieldMessenger::SetNewValue().
void F03FieldSetup::SetLocalFieldValue (G4ThreeVector fieldVector)
Definition at line 248 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 248 of file F03FieldSetup.cc
References fEquation, fLocalMagneticField, GetLocalFieldManager(), G4FieldManager::SetDetectorField(), and G4EquationOfMotion::SetFieldObj().
Referenced by F03FieldMessenger::SetNewValue().
void F03FieldSetup::SetMinStep (G4double s) inline
Definition at line 65 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 65 of file F03FieldSetup.hh
References fMinStep.
Referenced by F03FieldMessenger::SetNewValue().
void F03FieldSetup::SetStepperType (G4int i) inline
Definition at line 61 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 61 of file F03FieldSetup.hh
References fStepperType.
Referenced by F03FieldMessenger::SetNewValue().
void F03FieldSetup::UpdateField ()
Definition at line 111 of file F03FieldSetup.cc.
View newest version in sPHENIX GitHub at line 111 of file F03FieldSetup.cc
References CreateSteppers(), fChordFinder, fFieldManager, fLocalChordFinder, fLocalFieldManager, fLocalMagneticField, fLocalStepper, fMagneticField, fMinStep, fStepper, fStepperType, G4cout, G4endl, mm, G4FieldManager::SetChordFinder(), and G4FieldManager::SetDetectorField().
Referenced by F03FieldSetup(), and F03FieldMessenger::SetNewValue().
Member Data Documentation
G4ChordFinder* F03FieldSetup::fChordFinder protected
Definition at line 85 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 85 of file F03FieldSetup.hh
Referenced by UpdateField(), and ~F03FieldSetup().
G4Mag_UsualEqRhs* F03FieldSetup::fEquation protected
Definition at line 87 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 87 of file F03FieldSetup.hh
Referenced by CreateSteppers(), F03FieldSetup(), SetFieldValue(), and SetLocalFieldValue().
G4FieldManager* F03FieldSetup::fFieldManager protected
Definition at line 83 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 83 of file F03FieldSetup.hh
Referenced by F03FieldSetup(), and UpdateField().
F03FieldMessenger* F03FieldSetup::fFieldMessenger protected
Definition at line 98 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 98 of file F03FieldSetup.hh
Referenced by F03FieldSetup(), and ~F03FieldSetup().
G4ChordFinder* F03FieldSetup::fLocalChordFinder protected
Definition at line 86 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 86 of file F03FieldSetup.hh
Referenced by UpdateField().
G4Mag_UsualEqRhs* F03FieldSetup::fLocalEquation protected
Definition at line 88 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 88 of file F03FieldSetup.hh
Referenced by CreateSteppers(), and F03FieldSetup().
G4FieldManager* F03FieldSetup::fLocalFieldManager protected
Definition at line 84 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 84 of file F03FieldSetup.hh
Referenced by F03FieldSetup(), GetLocalFieldManager(), and UpdateField().
G4MagneticField* F03FieldSetup::fLocalMagneticField protected
Definition at line 90 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 90 of file F03FieldSetup.hh
Referenced by F03FieldSetup(), GetLocalFieldValue(), SetLocalFieldValue(), and UpdateField().
G4MagIntegratorStepper* F03FieldSetup::fLocalStepper protected
Definition at line 93 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 93 of file F03FieldSetup.hh
Referenced by CreateSteppers(), and UpdateField().
G4MagneticField* F03FieldSetup::fMagneticField protected
Definition at line 89 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 89 of file F03FieldSetup.hh
Referenced by F03FieldSetup(), GetGlobalFieldValue(), SetFieldValue(), UpdateField(), and ~F03FieldSetup().
G4double F03FieldSetup::fMinStep protected
Definition at line 96 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 96 of file F03FieldSetup.hh
Referenced by F03FieldSetup(), SetMinStep(), and UpdateField().
G4MagIntegratorStepper* F03FieldSetup::fStepper protected
Definition at line 92 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 92 of file F03FieldSetup.hh
Referenced by CreateSteppers(), UpdateField(), and ~F03FieldSetup().
G4int F03FieldSetup::fStepperType protected
Definition at line 94 of file F03FieldSetup.hh.
View newest version in sPHENIX GitHub at line 94 of file F03FieldSetup.hh
Referenced by CreateSteppers(), F03FieldSetup(), SetStepperType(), and UpdateField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field03/include/F03FieldSetup.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field03/src/F03FieldSetup.cc