ECCE @ EIC Software: G4GDMLWriteSolids Class Reference
G4GDMLWriteSolids Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteSolids.hh>
Classes
class G4ThreeVectorCompare
Public Member Functions
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
G4GDMLWriteSolids ()
virtual ~G4GDMLWriteSolids ()
void MultiUnionWrite (xercesc::DOMElement *solElement, const G4MultiUnion *const)
void BooleanWrite (xercesc::DOMElement *, const G4BooleanSolid *const)
void ScaledWrite (xercesc::DOMElement *, const G4ScaledSolid *const)
void BoxWrite (xercesc::DOMElement *, const G4Box *const)
void ConeWrite (xercesc::DOMElement *, const G4Cons *const)
void ElconeWrite (xercesc::DOMElement *, const G4EllipticalCone *const)
void EllipsoidWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void EltubeWrite (xercesc::DOMElement *, const G4EllipticalTube *const)
void XtruWrite (xercesc::DOMElement *, const G4ExtrudedSolid *const)
void HypeWrite (xercesc::DOMElement *, const G4Hype *const)
void OrbWrite (xercesc::DOMElement *, const G4Orb *const)
void ParaWrite (xercesc::DOMElement *, const G4Para *const)
void ParaboloidWrite (xercesc::DOMElement *, const G4Paraboloid *const)
void PolyconeWrite (xercesc::DOMElement *, const G4Polycone *const)
void GenericPolyconeWrite (xercesc::DOMElement *, const G4GenericPolycone *const)
void PolyhedraWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void SphereWrite (xercesc::DOMElement *, const G4Sphere *const)
void TessellatedWrite (xercesc::DOMElement *, const G4TessellatedSolid *const)
void TetWrite (xercesc::DOMElement *, const G4Tet *const)
void TorusWrite (xercesc::DOMElement *, const G4Torus *const)
void GenTrapWrite (xercesc::DOMElement *, const G4GenericTrap *const)
void TrapWrite (xercesc::DOMElement *, const G4Trap *const)
void TrdWrite (xercesc::DOMElement *, const G4Trd *const)
void TubeWrite (xercesc::DOMElement *, const G4Tubs *const)
void CutTubeWrite (xercesc::DOMElement *, const G4CutTubs *const)
void TwistedboxWrite (xercesc::DOMElement *, const G4TwistedBox *const)
void TwistedtrapWrite (xercesc::DOMElement *, const G4TwistedTrap *const)
void TwistedtrdWrite (xercesc::DOMElement *, const G4TwistedTrd *const)
void TwistedtubsWrite (xercesc::DOMElement *, const G4TwistedTubs *const)
void ZplaneWrite (xercesc::DOMElement *, const G4double &, const G4double &, const G4double &)
void RZPointWrite (xercesc::DOMElement *, const G4double &, const G4double &)
void OpticalSurfaceWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
void PropertyWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
Protected Member Functions inherited from G4GDMLWriteMaterials
G4GDMLWriteMaterials ()
virtual ~G4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from G4GDMLWriteDefine
G4GDMLWriteDefine ()
virtual ~G4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from G4GDMLWrite
G4GDMLWrite ()
virtual ~G4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (G4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
std::vector< const G4VSolid * > solidList
xercesc::DOMElement * solidsElement
Protected Attributes inherited from G4GDMLWriteMaterials
std::vector< const G4Isotope * > isotopeList
std::vector< const G4Element * > elementList
std::vector< const G4Material * > materialList
std::vector< const
G4PhysicsOrderedFreeVector * > propertyList
xercesc::DOMElement * materialsElement
Protected Attributes inherited from G4GDMLWriteDefine
xercesc::DOMElement * defineElement
Protected Attributes inherited from G4GDMLWrite
G4String SchemaLocation
xercesc::DOMDocument * doc
xercesc::DOMElement * extElement
xercesc::DOMElement * userinfoElement
XMLCh tempStr [10000]
G4GDMLAuxListType auxList
Static Protected Attributes
static const G4int maxTransforms = 8
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Detailed Description
Definition at line 78 of file G4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 78 of file G4GDMLWriteSolids.hh
Constructor & Destructor Documentation
G4GDMLWriteSolids::G4GDMLWriteSolids () protected
Definition at line 73 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 73 of file G4GDMLWriteSolids.cc
G4GDMLWriteSolids::~G4GDMLWriteSolids () protected virtual
Definition at line 78 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 78 of file G4GDMLWriteSolids.cc
Member Function Documentation
void G4GDMLWriteSolids::AddSolid (const G4VSolid * const solidPtr) virtual
Definition at line 1121 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1121 of file G4GDMLWriteSolids.cc
References BooleanWrite(), BoxWrite(), ConeWrite(), CutTubeWrite(), ElconeWrite(), EllipsoidWrite(), EltubeWrite(), FatalException, G4Exception(), GenericPolyconeWrite(), GenTrapWrite(), G4VSolid::GetEntityType(), G4VSolid::GetName(), HypeWrite(), MultiUnionWrite(), OrbWrite(), ParaboloidWrite(), ParaWrite(), PolyconeWrite(), PolyhedraWrite(), ScaledWrite(), solidList, solidsElement, SphereWrite(), TessellatedWrite(), TetWrite(), TorusWrite(), TrapWrite(), TrdWrite(), TubeWrite(), TwistedboxWrite(), TwistedtrapWrite(), TwistedtrdWrite(), TwistedtubsWrite(), and XtruWrite().
Referenced by BooleanWrite(), MultiUnionWrite(), ScaledWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
void G4GDMLWriteSolids::BooleanWrite (xercesc::DOMElement * solElement, const G4BooleanSolid * const boolean) protected
Definition at line 142 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 142 of file G4GDMLWriteSolids.cc
References AddSolid(), FatalException, G4GDMLWriteDefine::FirstpositionWrite(), G4GDMLWriteDefine::FirstrotationWrite(), G4Exception(), G4GDMLWrite::GenerateName(), G4GDMLWriteDefine::GetAngles(), G4VSolid::GetName(), G4GDMLWriteDefine::kAngularPrecision, G4GDMLWriteDefine::kLinearPrecision, maxTransforms, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), pos(), G4GDMLWriteDefine::PositionWrite(), G4GDMLWriteDefine::RotationWrite(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by AddSolid().
void G4GDMLWriteSolids::BoxWrite (xercesc::DOMElement * solElement, const G4Box * const box) protected
Definition at line 291 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 291 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::ConeWrite (xercesc::DOMElement * solElement, const G4Cons * const cone) protected
Definition at line 305 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 305 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4Cons::GetDeltaPhiAngle(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4VSolid::GetName(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Cons::GetStartPhiAngle(), G4Cons::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::CutTubeWrite (xercesc::DOMElement * solElement, const G4CutTubs * const cuttube) protected
Definition at line 871 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 871 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4CutTubs::GetDeltaPhiAngle(), G4CutTubs::GetHighNorm(), G4CutTubs::GetInnerRadius(), G4CutTubs::GetLowNorm(), G4VSolid::GetName(), G4CutTubs::GetOuterRadius(), G4CutTubs::GetStartPhiAngle(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4CutTubs::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::ElconeWrite (xercesc::DOMElement * solElement, const G4EllipticalCone * const elcone) protected
Definition at line 331 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 331 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4EllipticalCone::GetSemiAxisX(), G4EllipticalCone::GetSemiAxisY(), G4EllipticalCone::GetZMax(), G4EllipticalCone::GetZTopCut(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::EllipsoidWrite (xercesc::DOMElement * solElement, const G4Ellipsoid * const ellipsoid) protected
Definition at line 347 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 347 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Ellipsoid::GetSemiAxisMax(), G4Ellipsoid::GetZBottomCut(), G4Ellipsoid::GetZTopCut(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::EltubeWrite (xercesc::DOMElement * solElement, const G4EllipticalTube * const eltube) protected
Definition at line 370 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 370 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4EllipticalTube::GetDx(), G4EllipticalTube::GetDy(), G4EllipticalTube::GetDz(), G4VSolid::GetName(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::GenericPolyconeWrite (xercesc::DOMElement * solElement, const G4GenericPolycone * const polycone) protected
Definition at line 535 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 535 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4GenericPolycone::GetCorner(), G4GenericPolycone::GetEndPhi(), G4VSolid::GetName(), G4GenericPolycone::GetNumRZCorner(), G4GenericPolycone::GetStartPhi(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), G4PolyconeSideRZ::r, RZPointWrite(), and G4PolyconeSideRZ::z.
Referenced by AddSolid().
void G4GDMLWriteSolids::GenTrapWrite (xercesc::DOMElement * solElement, const G4GenericTrap * const gtrap) protected
Definition at line 760 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 760 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4GenericTrap::GetVertices(), G4GenericTrap::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), x, and y.
Referenced by AddSolid().
void G4GDMLWriteSolids::HypeWrite (xercesc::DOMElement * solElement, const G4Hype * const hype) protected
Definition at line 429 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 429 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4Hype::GetInnerRadius(), G4Hype::GetInnerStereo(), G4VSolid::GetName(), G4Hype::GetOuterRadius(), G4Hype::GetOuterStereo(), G4Hype::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::MultiUnionWrite (xercesc::DOMElement * solElement, const G4MultiUnion * const munionSolid) protected
Definition at line 83 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 83 of file G4GDMLWriteSolids.cc
References AddSolid(), G4GDMLWrite::GenerateName(), G4GDMLWriteDefine::GetAngles(), HepGeom::Transform3D::getDecomposition(), G4VSolid::GetName(), G4MultiUnion::GetNumberOfSolids(), G4MultiUnion::GetSolid(), G4MultiUnion::GetTransformation(), HepGeom::Transform3D::getTranslation(), G4GDMLWriteDefine::kAngularPrecision, G4GDMLWriteDefine::kLinearPrecision, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), pos(), G4GDMLWriteDefine::PositionWrite(), G4GDMLWriteDefine::RotationWrite(), scale, Acts::Test::transform, CLHEP::Hep3Vector::x(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), CLHEP::Hep3Vector::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), CLHEP::Hep3Vector::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), and HepGeom::Transform3D::zz().
Referenced by AddSolid().
void G4GDMLWriteSolids::OpticalSurfaceWrite (xercesc::DOMElement * solElement, const G4OpticalSurface * const surf) protected
Definition at line 1033 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1033 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4OpticalSurface::GetFinish(), G4OpticalSurface::GetMaterialPropertiesTable(), G4OpticalSurface::GetModel(), G4SurfaceProperty::GetName(), G4OpticalSurface::GetPolish(), G4OpticalSurface::GetSigmaAlpha(), G4SurfaceProperty::GetType(), glisur, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), and PropertyWrite().
Referenced by G4GDMLWriteStructure::BorderSurfaceCache(), and G4GDMLWriteStructure::SkinSurfaceCache().
void G4GDMLWriteSolids::OrbWrite (xercesc::DOMElement * solElement, const G4Orb * const orb) protected
Definition at line 451 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 451 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Orb::GetRadius(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::ParaboloidWrite (xercesc::DOMElement * solElement, const G4Paraboloid * const paraboloid) protected
Definition at line 489 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 489 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Paraboloid::GetRadiusMinusZ(), G4Paraboloid::GetRadiusPlusZ(), G4Paraboloid::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::ParaWrite (xercesc::DOMElement * solElement, const G4Para * const para) protected
Definition at line 463 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 463 of file G4GDMLWriteSolids.cc
References alpha, degree, G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetXHalfLength(), G4Para::GetYHalfLength(), G4Para::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), phi, and theta().
Referenced by AddSolid().
void G4GDMLWriteSolids::PolyconeWrite (xercesc::DOMElement * solElement, const G4Polycone * const polycone) protected
Definition at line 506 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 506 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Polycone::GetOriginalParameters(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), G4PolyconeHistorical::Num_z_planes, G4PolyconeHistorical::Opening_angle, G4PolyconeHistorical::Rmax, G4PolyconeHistorical::Rmin, G4PolyconeHistorical::Start_angle, G4PolyconeHistorical::Z_values, and ZplaneWrite().
Referenced by AddSolid().
void G4GDMLWriteSolids::PolyhedraWrite (xercesc::DOMElement * solElement, const G4Polyhedra * const polyhedra) protected
Definition at line 560 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 560 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4Polyhedra::GetCorner(), G4VSolid::GetName(), G4Polyhedra::GetNumRZCorner(), G4Polyhedra::GetOriginalParameters(), G4Polyhedra::IsGeneric(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, G4PolyhedraSideRZ::r, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, RZPointWrite(), G4PolyhedraHistorical::Start_angle, G4PolyhedraSideRZ::z, G4PolyhedraHistorical::Z_values, and ZplaneWrite().
Referenced by AddSolid().
void G4GDMLWriteSolids::PropertyWrite (xercesc::DOMElement * optElement, const G4OpticalSurface * const surf) protected
Definition at line 1057 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1057 of file G4GDMLWriteSolids.cc
References G4GDMLWriteDefine::defineElement, G4Exception(), G4GDMLWrite::GenerateName(), G4MaterialPropertiesTable::GetConstPropertyMap(), G4MaterialPropertiesTable::GetMaterialConstPropertyNames(), G4OpticalSurface::GetMaterialPropertiesTable(), G4MaterialPropertiesTable::GetMaterialPropertyNames(), G4SurfaceProperty::GetName(), G4MaterialPropertiesTable::GetPropertyMap(), JustWarning, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), and G4GDMLWriteMaterials::PropertyVectorWrite().
Referenced by OpticalSurfaceWrite().
void G4GDMLWriteSolids::RZPointWrite (xercesc::DOMElement * element, const G4double & r, const G4double & z) protected
Definition at line 1023 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1023 of file G4GDMLWriteSolids.cc
References mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by GenericPolyconeWrite(), and PolyhedraWrite().
void G4GDMLWriteSolids::ScaledWrite (xercesc::DOMElement * solElement, const G4ScaledSolid * const scaled) protected
Definition at line 258 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 258 of file G4GDMLWriteSolids.cc
References AddSolid(), G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4ScaledSolid::GetScaleTransform(), G4ScaledSolid::GetUnscaledSolid(), G4GDMLWriteDefine::kLinearPrecision, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), scale, G4GDMLWriteDefine::ScaleWrite(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::yy(), and HepGeom::Transform3D::zz().
Referenced by AddSolid().
void G4GDMLWriteSolids::SolidsWrite (xercesc::DOMElement * gdmlElement) virtual
Implements G4GDMLWrite.
Definition at line 1110 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1110 of file G4GDMLWriteSolids.cc
References G4cout, G4endl, G4GDMLWrite::NewElement(), solidList, and solidsElement.
void G4GDMLWriteSolids::SphereWrite (xercesc::DOMElement * solElement, const G4Sphere * const sphere) protected
Definition at line 621 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 621 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4Sphere::GetDeltaPhiAngle(), G4Sphere::GetDeltaThetaAngle(), G4Sphere::GetInnerRadius(), G4VSolid::GetName(), G4Sphere::GetOuterRadius(), G4Sphere::GetStartPhiAngle(), G4Sphere::GetStartThetaAngle(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TessellatedWrite (xercesc::DOMElement * solElement, const G4TessellatedSolid * const tessellated) protected
Definition at line 645 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 645 of file G4GDMLWriteSolids.cc
References G4GDMLWriteDefine::AddPosition(), FatalException, test::fname, G4Exception(), G4GDMLWrite::GenerateName(), G4TessellatedSolid::GetFacet(), G4VSolid::GetName(), G4TessellatedSolid::GetNumberOfFacets(), G4VFacet::GetNumberOfVertices(), G4VFacet::GetVertex(), G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TetWrite (xercesc::DOMElement * solElement, const G4Tet * const tet) protected
Definition at line 718 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 718 of file G4GDMLWriteSolids.cc
References G4GDMLWriteDefine::AddPosition(), G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Tet::GetVertices(), G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TorusWrite (xercesc::DOMElement * solElement, const G4Torus * const torus) protected
Definition at line 741 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 741 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4Torus::GetDPhi(), G4VSolid::GetName(), G4Torus::GetRmax(), G4Torus::GetRmin(), G4Torus::GetRtor(), G4Torus::GetSPhi(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TrapWrite (xercesc::DOMElement * solElement, const G4Trap * const trap) protected
Definition at line 792 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 792 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Trap::GetSymAxis(), G4Trap::GetTanAlpha1(), G4Trap::GetTanAlpha2(), G4Trap::GetXHalfLength1(), G4Trap::GetXHalfLength2(), G4Trap::GetXHalfLength3(), G4Trap::GetXHalfLength4(), G4Trap::GetYHalfLength1(), G4Trap::GetYHalfLength2(), G4Trap::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), phi, and theta().
Referenced by AddSolid().
void G4GDMLWriteSolids::TrdWrite (xercesc::DOMElement * solElement, const G4Trd * const trd) protected
Definition at line 828 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 828 of file G4GDMLWriteSolids.cc
References G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TubeWrite (xercesc::DOMElement * solElement, const G4Tubs * const tube) protected
Definition at line 849 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 849 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4Tubs::GetDeltaPhiAngle(), G4Tubs::GetInnerRadius(), G4VSolid::GetName(), G4Tubs::GetOuterRadius(), G4Tubs::GetStartPhiAngle(), G4Tubs::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TwistedboxWrite (xercesc::DOMElement * solElement, const G4TwistedBox * const twistedbox) protected
Definition at line 905 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 905 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4TwistedBox::GetPhiTwist(), G4TwistedBox::GetXHalfLength(), G4TwistedBox::GetYHalfLength(), G4TwistedBox::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TwistedtrapWrite (xercesc::DOMElement * solElement, const G4TwistedTrap * const twistedtrap) protected
Definition at line 926 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 926 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4TwistedTrap::GetAzimuthalAnglePhi(), G4VSolid::GetName(), G4TwistedTrap::GetPhiTwist(), G4TwistedTrap::GetPolarAngleTheta(), G4TwistedTrap::GetTiltAngleAlpha(), G4TwistedTrap::GetX1HalfLength(), G4TwistedTrap::GetX2HalfLength(), G4TwistedTrap::GetX3HalfLength(), G4TwistedTrap::GetX4HalfLength(), G4TwistedTrap::GetY1HalfLength(), G4TwistedTrap::GetY2HalfLength(), G4TwistedTrap::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TwistedtrdWrite (xercesc::DOMElement * solElement, const G4TwistedTrd * const twistedtrd) protected
Definition at line 962 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 962 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4TwistedTrd::GetPhiTwist(), G4TwistedTrd::GetX1HalfLength(), G4TwistedTrd::GetX2HalfLength(), G4TwistedTrd::GetY1HalfLength(), G4TwistedTrd::GetY2HalfLength(), G4TwistedTrd::GetZHalfLength(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::TwistedtubsWrite (xercesc::DOMElement * solElement, const G4TwistedTubs * const twistedtubs) protected
Definition at line 987 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 987 of file G4GDMLWriteSolids.cc
References degree, G4GDMLWrite::GenerateName(), G4TwistedTubs::GetDPhi(), G4TwistedTubs::GetEndZ(), G4TwistedTubs::GetInnerRadius(), G4VSolid::GetName(), G4TwistedTubs::GetOuterRadius(), G4TwistedTubs::GetPhiTwist(), mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by AddSolid().
void G4GDMLWriteSolids::XtruWrite (xercesc::DOMElement * solElement, const G4ExtrudedSolid * const xtru) protected
Definition at line 385 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 385 of file G4GDMLWriteSolids.cc
References G4ExtrudedSolid::ZSection::fOffset, G4ExtrudedSolid::ZSection::fScale, G4ExtrudedSolid::ZSection::fZ, G4GDMLWrite::GenerateName(), G4VSolid::GetName(), G4ExtrudedSolid::GetNofVertices(), G4ExtrudedSolid::GetNofZSections(), G4ExtrudedSolid::GetVertex(), G4ExtrudedSolid::GetZSection(), mm, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by AddSolid().
void G4GDMLWriteSolids::ZplaneWrite (xercesc::DOMElement * element, const G4double & z, const G4double & rmin, const G4double & rmax) protected
Definition at line 1012 of file G4GDMLWriteSolids.cc.
View newest version in sPHENIX GitHub at line 1012 of file G4GDMLWriteSolids.cc
References mm, G4GDMLWrite::NewAttribute(), and G4GDMLWrite::NewElement().
Referenced by G4GDMLWriteParamvol::Polycone_dimensionsWrite(), PolyconeWrite(), G4GDMLWriteParamvol::Polyhedra_dimensionsWrite(), and PolyhedraWrite().
Member Data Documentation
const G4int G4GDMLWriteSolids::maxTransforms = 8 static protected
Definition at line 150 of file G4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 150 of file G4GDMLWriteSolids.hh
Referenced by BooleanWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
std::vector<const G4VSolid*> G4GDMLWriteSolids::solidList protected
Definition at line 148 of file G4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 148 of file G4GDMLWriteSolids.hh
Referenced by AddSolid(), and SolidsWrite().
xercesc::DOMElement* G4GDMLWriteSolids::solidsElement protected
Definition at line 149 of file G4GDMLWriteSolids.hh.
View newest version in sPHENIX GitHub at line 149 of file G4GDMLWriteSolids.hh
Referenced by AddSolid(), G4GDMLWriteStructure::BorderSurfaceCache(), G4GDMLWriteStructure::SkinSurfaceCache(), and SolidsWrite().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteSolids.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLWriteSolids.cc