ECCE @ EIC Software: HEPREP::HepRepPoint Class Reference
HEPREP::HepRepPoint Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepPoint.h>
Public Member Functions
virtual ~HepRepPoint ()
Destructor.
virtual double getX ()=0
virtual double getY ()=0
virtual double getZ ()=0
virtual double getRho ()=0
virtual double getPhi ()=0
virtual double getTheta ()=0
virtual double getR ()=0
virtual double getEta ()=0
virtual double getX (double xVertex, double yVertex, double zVertex)=0
virtual double getY (double xVertex, double yVertex, double zVertex)=0
virtual double getZ (double xVertex, double yVertex, double zVertex)=0
virtual double getRho (double xVertex, double yVertex, double zVertex)=0
virtual double getPhi (double xVertex, double yVertex, double zVertex)=0
virtual double getTheta (double xVertex, double yVertex, double zVertex)=0
virtual double getR (double xVertex, double yVertex, double zVertex)=0
virtual double getEta (double xVertex, double yVertex, double zVertex)=0
virtual std::vector< double > * getXYZ (std::vector< double > *xyz)=0
virtual HepRepInstance * getInstance ()=0
virtual HepRepPoint * copy (HepRepInstance *parent)=0
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
virtual void addAttValue (HepRepAttValue *attValue)=0
virtual void addAttValue (std::string key, char *value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::string value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int64 value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, bool value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::vector< double > value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double red, double green, double blue, double alpha=1.0, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual HepRepAttValue * removeAttValue (std::string key)=0
virtual HepRepAttValue * getAttValue (std::string name)=0
virtual std::set
< HepRepAttValue * > getAttValuesFromNode ()=0
virtual HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)=0
Detailed Description
HepRepPoint interface. The HepRepMath class can be used to deal with the conversions.
Author
Mark Donszelmann
Definition at line 25 of file HepRepPoint.h.
View newest version in sPHENIX GitHub at line 25 of file HepRepPoint.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepPoint::~HepRepPoint () inline virtual
Destructor.
Definition at line 29 of file HepRepPoint.h.
View newest version in sPHENIX GitHub at line 29 of file HepRepPoint.h
Member Function Documentation
virtual HepRepPoint* HEPREP::HepRepPoint::copy (HepRepInstance * parent) pure virtual
Returns a deep copy of this point.
Parameters
parent to add the copy to.
Returns
copy of this point.
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getEta () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
eta = -0.5*clog((1.-ct)/(1.+ct)), where ct = .cos(getTheta(dx, dy, dz));
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getEta (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
eta = -0.5*clog((1.-ct)/(1.+ct)), where ct = .cos(getTheta(dx, dy, dz));
Implemented in cheprep::DefaultHepRepPoint.
virtual HepRepInstance* HEPREP::HepRepPoint::getInstance () pure virtual
Returns associated instance (parent).
Returns
HepRepInstance.
Implemented in cheprep::DefaultHepRepPoint.
Referenced by G4HepRepSceneHandler::setAttribute().
virtual double HEPREP::HepRepPoint::getPhi () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
phi = std::atan2(dy, dx);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getPhi (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
phi = std::atan2(dy, dx);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getR () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
r = std::sqrt(dx2+dy2+dz2);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getR (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
r = std::sqrt(dx2+dy2+dz2);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getRho () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
rho = std::sqrt(dx2+dy2);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getRho (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
rho = std::sqrt(dx2+dy2);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getTheta () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
theta = std::atan2(rho, dx);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getTheta (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
theta = std::atan2(rho, dx);
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getX () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
dx-coordinate
Implemented in cheprep::DefaultHepRepPoint.
Referenced by G4HepRepSceneHandler::addAttVals(), and cheprep::XMLHepRepWriter::write().
virtual double HEPREP::HepRepPoint::getX (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
dx-coordinate
Implemented in cheprep::DefaultHepRepPoint.
virtual std::vector<double>* HEPREP::HepRepPoint::getXYZ (std::vector< double > * xyz) pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Parameters
xyz list of three coordinates which are filled and returned. If null, a new list of three coordinates is allocated.
Returns
list of 3 coordinates.
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getY () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
dy-coordinate
Implemented in cheprep::DefaultHepRepPoint.
Referenced by cheprep::XMLHepRepWriter::write().
virtual double HEPREP::HepRepPoint::getY (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
dy-coordinate
Implemented in cheprep::DefaultHepRepPoint.
virtual double HEPREP::HepRepPoint::getZ () pure virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
dz-coordinate
Implemented in cheprep::DefaultHepRepPoint.
Referenced by cheprep::XMLHepRepWriter::write().
virtual double HEPREP::HepRepPoint::getZ (double xVertex, double yVertex, double zVertex) pure virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
dz-coordinate
Implemented in cheprep::DefaultHepRepPoint.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepPoint.h