ECCE @ EIC Software: G4VIntegrationDriver Class Reference
G4VIntegrationDriver Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4VIntegrationDriver.hh>
Public Member Functions
virtual ~G4VIntegrationDriver ()=default
virtual G4double AdvanceChordLimited (G4FieldTrack &track, G4double hstep, G4double eps, G4double chordDistance)=0
virtual G4bool AccurateAdvance (G4FieldTrack &track, G4double hstep, G4double eps, G4double hinitial=0)=0
virtual void SetEquationOfMotion (G4EquationOfMotion *equation)=0
virtual G4EquationOfMotion * GetEquationOfMotion ()=0
virtual void RenewStepperAndAdjust (G4MagIntegratorStepper *pItsStepper)
virtual void SetVerboseLevel (G4int level)=0
virtual G4int GetVerboseLevel () const =0
virtual void OnComputeStep ()=0
virtual void OnStartTracking ()=0
virtual G4bool QuickAdvance (G4FieldTrack &, const G4double[], G4double, G4double &, G4double &)
virtual void GetDerivatives (const G4FieldTrack &track, G4double dydx[]) const =0
virtual void GetDerivatives (const G4FieldTrack &track, G4double dydx[], G4double field[]) const =0
virtual const
G4MagIntegratorStepper * GetStepper () const =0
virtual G4MagIntegratorStepper * GetStepper ()=0
virtual G4double ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent)=0
virtual G4bool DoesReIntegrate ()=0
Static Protected Attributes
static constexpr G4double max_stepping_increase = 5
static constexpr G4double max_stepping_decrease = 0.1
Detailed Description
Definition at line 51 of file G4VIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VIntegrationDriver.hh
Constructor & Destructor Documentation
virtual G4VIntegrationDriver::~G4VIntegrationDriver () virtual default
Member Function Documentation
virtual G4bool G4VIntegrationDriver::AccurateAdvance (G4FieldTrack & track, G4double hstep, G4double eps, G4double hinitial = 0) pure virtual
Implemented in G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4InterpolationDriver< T >, G4FSALIntegrationDriver< T >, G4MagInt_Driver, and G4BFieldIntegrationDriver.
Referenced by G4BFieldIntegrationDriver::AccurateAdvance(), G4ChordFinder::ApproxCurvePointS(), G4ChordFinder::ApproxCurvePointV(), and G4BrentLocator::EstimateIntersectionPoint().
virtual G4double G4VIntegrationDriver::AdvanceChordLimited (G4FieldTrack & track, G4double hstep, G4double eps, G4double chordDistance) pure virtual
Implemented in G4IntegrationDriver< T >, G4InterpolationDriver< T >, G4IntegrationDriver< G4BulirschStoer >, G4MagInt_Driver, G4FSALIntegrationDriver< T >, and G4BFieldIntegrationDriver.
Referenced by G4BFieldIntegrationDriver::AdvanceChordLimited().
virtual G4double G4VIntegrationDriver::ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) pure virtual
Implemented in G4MagInt_Driver, G4IntegrationDriver< G4BulirschStoer >, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
Referenced by G4BFieldIntegrationDriver::ComputeNewStepSize().
virtual G4bool G4VIntegrationDriver::DoesReIntegrate () pure virtual
Implemented in G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4FSALIntegrationDriver< T >, G4InterpolationDriver< T >, G4BFieldIntegrationDriver, and G4MagInt_Driver.
Referenced by G4BFieldIntegrationDriver::DoesReIntegrate(), and G4MultiLevelLocator::EstimateIntersectionPoint().
virtual void G4VIntegrationDriver::GetDerivatives (const G4FieldTrack & track, G4double dydx[]) const pure virtual
Implemented in G4MagInt_Driver, G4IntegrationDriver< G4BulirschStoer >, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
Referenced by G4BFieldIntegrationDriver::GetDerivatives().
virtual void G4VIntegrationDriver::GetDerivatives (const G4FieldTrack & track, G4double dydx[], G4double field[]) const pure virtual
Implemented in G4MagInt_Driver, G4IntegrationDriver< G4BulirschStoer >, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
virtual G4EquationOfMotion* G4VIntegrationDriver::GetEquationOfMotion () pure virtual
Implemented in G4IntegrationDriver< G4BulirschStoer >, G4MagInt_Driver, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
Referenced by G4BFieldIntegrationDriver::GetEquationOfMotion(), G4ErrorPropagatorManager::InitFieldForBackwards(), and G4FieldManager::SetDetectorField().
virtual const G4MagIntegratorStepper* G4VIntegrationDriver::GetStepper () const pure virtual
Implemented in G4MagInt_Driver, G4IntegrationDriver< G4BulirschStoer >, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
Referenced by F01FieldSetup::CreateFSALStepperAndDriver(), and G4BFieldIntegrationDriver::GetStepper().
virtual G4MagIntegratorStepper* G4VIntegrationDriver::GetStepper () pure virtual
Implemented in G4MagInt_Driver, G4IntegrationDriver< G4BulirschStoer >, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
virtual G4int G4VIntegrationDriver::GetVerboseLevel () const pure virtual
Implemented in G4MagInt_Driver, G4BFieldIntegrationDriver, G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4FSALIntegrationDriver< T >, and G4InterpolationDriver< T >.
Referenced by G4BFieldIntegrationDriver::GetVerboseLevel().
virtual void G4VIntegrationDriver::OnComputeStep () pure virtual
Implemented in G4BFieldIntegrationDriver, G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4FSALIntegrationDriver< T >, G4InterpolationDriver< T >, and G4MagInt_Driver.
Referenced by G4BFieldIntegrationDriver::AdvanceChordLimited().
virtual void G4VIntegrationDriver::OnStartTracking () pure virtual
Implemented in G4BFieldIntegrationDriver, G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4InterpolationDriver< T >, G4MagInt_Driver, and G4FSALIntegrationDriver< T >.
virtual G4bool G4VIntegrationDriver::QuickAdvance (G4FieldTrack & , const G4double [], G4double , G4double & , G4double &) inline virtual
Reimplemented in G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4FSALIntegrationDriver< T >, and G4MagInt_Driver.
Definition at line 83 of file G4VIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 83 of file G4VIntegrationDriver.hh
void G4VIntegrationDriver::RenewStepperAndAdjust (G4MagIntegratorStepper * pItsStepper) virtual
Reimplemented in G4MagInt_Driver, and G4RKIntegrationDriver< T >.
Definition at line 34 of file G4VIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VIntegrationDriver.cc
References FatalException, and G4Exception().
virtual void G4VIntegrationDriver::SetEquationOfMotion (G4EquationOfMotion * equation) pure virtual
Implemented in G4IntegrationDriver< G4BulirschStoer >, G4MagInt_Driver, G4BFieldIntegrationDriver, and G4RKIntegrationDriver< T >.
virtual void G4VIntegrationDriver::SetVerboseLevel (G4int level) pure virtual
Implemented in G4MagInt_Driver, G4BFieldIntegrationDriver, G4IntegrationDriver< G4BulirschStoer >, G4IntegrationDriver< T >, G4FSALIntegrationDriver< T >, and G4InterpolationDriver< T >.
Referenced by G4PropagatorInField::SetVerboseLevel().
Member Data Documentation
constexpr G4double G4VIntegrationDriver::max_stepping_decrease = 0.1 static protected
Definition at line 117 of file G4VIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 117 of file G4VIntegrationDriver.hh
Referenced by G4MagInt_Driver::ComputeNewStepSize_WithinLimits().
constexpr G4double G4VIntegrationDriver::max_stepping_increase = 5 static protected
Definition at line 116 of file G4VIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VIntegrationDriver.hh
Referenced by G4MagInt_Driver::ComputeNewStepSize(), G4MagInt_Driver::ComputeNewStepSize_WithinLimits(), and G4MagInt_Driver::OneGoodStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4VIntegrationDriver.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4VIntegrationDriver.cc