ECCE @ EIC Software: G4HadronPhysicsQGSP_BIC_HP Class Reference
G4HadronPhysicsQGSP_BIC_HP Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGSP_BIC_HP.hh>
Classes
struct ThreadPrivate
Public Member Functions
G4HadronPhysicsQGSP_BIC_HP (G4int verbose=1)
G4HadronPhysicsQGSP_BIC_HP (const G4String &name, G4bool quasiElastic=true)
virtual ~G4HadronPhysicsQGSP_BIC_HP ()
void ConstructParticle () override
void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
void CreateModels ()
Static Private Attributes
static G4ThreadLocal
ThreadPrivate * tpdata = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 74 of file G4HadronPhysicsQGSP_BIC_HP.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadronPhysicsQGSP_BIC_HP.hh
Constructor & Destructor Documentation
G4HadronPhysicsQGSP_BIC_HP::G4HadronPhysicsQGSP_BIC_HP (G4int verbose = 1)
Definition at line 75 of file G4HadronPhysicsQGSP_BIC_HP.cc.
View newest version in sPHENIX GitHub at line 75 of file G4HadronPhysicsQGSP_BIC_HP.cc
G4HadronPhysicsQGSP_BIC_HP::G4HadronPhysicsQGSP_BIC_HP (const G4String & name, G4bool quasiElastic = true)
Definition at line 79 of file G4HadronPhysicsQGSP_BIC_HP.cc.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsQGSP_BIC_HP.cc
G4HadronPhysicsQGSP_BIC_HP::~G4HadronPhysicsQGSP_BIC_HP () virtual
Definition at line 127 of file G4HadronPhysicsQGSP_BIC_HP.cc.
View newest version in sPHENIX GitHub at line 127 of file G4HadronPhysicsQGSP_BIC_HP.cc
References G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theAntiBaryon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theBertiniPiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theBinaryNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theBinaryPro, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPAntiBaryon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPPiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPPro, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theHPNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theHyperon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::thePiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::thePro, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theQGSPNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theQGSPPiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theQGSPPro, and tpdata.
Member Function Documentation
void G4HadronPhysicsQGSP_BIC_HP::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 150 of file G4HadronPhysicsQGSP_BIC_HP.cc.
View newest version in sPHENIX GitHub at line 150 of file G4HadronPhysicsQGSP_BIC_HP.cc
References G4MesonConstructor::ConstructParticle(), G4IonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsQGSP_BIC_HP::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 165 of file G4HadronPhysicsQGSP_BIC_HP.cc.
View newest version in sPHENIX GitHub at line 165 of file G4HadronPhysicsQGSP_BIC_HP.cc
References G4AntiBarionBuilder::Build(), G4PiKBuilder::Build(), G4ProtonBuilder::Build(), G4NeutronBuilder::Build(), G4HyperonFTFPBuilder::Build(), CreateModels(), G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindFissionProcess(), G4HadronicParameters::Instance(), MeV, G4InuclParticleNames::neutron, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theAntiBaryon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theHyperon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theNeutrons, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::thePiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::thePro, and tpdata.
void G4HadronPhysicsQGSP_BIC_HP::CreateModels () private
Definition at line 83 of file G4HadronPhysicsQGSP_BIC_HP.cc.
View newest version in sPHENIX GitHub at line 83 of file G4HadronPhysicsQGSP_BIC_HP.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMaxEnergyTransitionQGS_FTF(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), MeV, G4AntiBarionBuilder::RegisterMe(), G4PiKBuilder::RegisterMe(), G4ProtonBuilder::RegisterMe(), G4NeutronBuilder::RegisterMe(), G4BinaryProtonBuilder::SetMaxEnergy(), G4BinaryNeutronBuilder::SetMaxEnergy(), G4FTFPProtonBuilder::SetMaxEnergy(), G4BertiniPiKBuilder::SetMaxEnergy(), G4FTFPNeutronBuilder::SetMaxEnergy(), G4FTFPPiKBuilder::SetMaxEnergy(), G4BinaryNeutronBuilder::SetMinEnergy(), G4FTFPProtonBuilder::SetMinEnergy(), G4FTFPNeutronBuilder::SetMinEnergy(), G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theAntiBaryon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theBertiniPiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theBinaryNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theBinaryPro, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPAntiBaryon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPPiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theFTFPPro, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theHPNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theHyperon, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theNeutrons, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::thePiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::thePro, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theQGSPNeutron, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theQGSPPiK, G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate::theQGSPPro, and tpdata.
Referenced by ConstructProcess().
Member Data Documentation
G4ThreadLocal G4HadronPhysicsQGSP_BIC_HP::ThreadPrivate * G4HadronPhysicsQGSP_BIC_HP::tpdata = nullptr static private
Definition at line 109 of file G4HadronPhysicsQGSP_BIC_HP.hh.
View newest version in sPHENIX GitHub at line 109 of file G4HadronPhysicsQGSP_BIC_HP.hh
Referenced by ConstructProcess(), CreateModels(), and ~G4HadronPhysicsQGSP_BIC_HP().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGSP_BIC_HP.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsQGSP_BIC_HP.cc