ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/plotHisto.C File Reference
plotHisto.C File Reference
Functions
TFile f0 ("testem6_0.root")
c1 Divide (2, 3)
for (int i=1;i< 7;++i)
Variables
TCanvas * c1 = new TCanvas("c1", " ")
Function Documentation
c1 Divide (2 , 3)
TFile f0 ("testem6_0.root")
Referenced by c2_factory< float_type >::connector_function(), CLHEP::HepStat::flatToGaussian(), for(), pyofsh(), Acts::AtlasStepper< ConstantBField >::step(), and CLHEP::RandLandau::transform().
for ()
Definition at line 9 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 9 of file plotHisto.C
References f0(), and nlohmann::to_string().
Variable Documentation
TCanvas* c1 = new TCanvas("c1", " ")
Definition at line 7 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 7 of file plotHisto.C