ECCE @ EIC Software: G3VolTableEntry Class Reference
G3VolTableEntry Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3VolTableEntry.hh>
Public Member Functions
G3VolTableEntry (G4String &vname, G4String &shape, G4double *rpar, G4int npar, G4int nmed, G4VSolid *solid, G4bool hasNegPars)
virtual ~G3VolTableEntry ()
G4bool operator== (const G3VolTableEntry &vte) const
void AddG3Pos (G3Pos *aG3Pos)
void AddDaughter (G3VolTableEntry *aDaughter)
void AddMother (G3VolTableEntry *aDaughter)
void AddClone (G3VolTableEntry *aDaughter)
void AddOverlap (G3VolTableEntry *aOverlap)
void ReplaceDaughter (G3VolTableEntry *vteOld, G3VolTableEntry *vteNew)
void ReplaceMother (G3VolTableEntry *vteOld, G3VolTableEntry *vteNew)
G3VolTableEntry * FindDaughter (const G4String &vname)
G3VolTableEntry * FindMother (const G4String &vname)
G3VolTableEntry * FindClone (const G4String &vname)
void PrintSolidInfo ()
void SetName (G4String name)
void SetLV (G4LogicalVolume *lv)
void SetSolid (G4VSolid *solid)
void SetNmed (G4int nmed)
void SetNRpar (G4int npar, G4double *Rpar)
void SetDivision (G3Division *division)
void SetHasNegPars (G4bool hasNegPars)
void SetHasMANY (G4bool hasMANY)
void ClearG3PosCopy (G4int copy)
void ClearDivision ()
G4String GetName ()
G4String GetShape ()
G4int GetNmed ()
G4int GetNpar ()
G4double * GetRpar ()
G4int NPCopies ()
G3Pos * GetG3PosCopy (G4int copy=0)
G3Division * GetDivision ()
G4bool HasNegPars ()
G4bool HasMANY ()
G4VSolid * GetSolid ()
G4LogicalVolume * GetLV ()
G4int GetNoDaughters ()
G4int GetNoMothers ()
G4int GetNoClones ()
G4int GetNoOverlaps ()
G3VolTableEntry * GetDaughter (G4int i)
G3VolTableEntry * GetMother (G4int i)
G3VolTableEntry * GetMother ()
G3VolTableEntry * GetClone (G4int i)
G3VolTableEntry * GetMasterClone ()
std::vector< G3VolTableEntry * > * GetOverlaps ()
Private Attributes
G4String fVname
G4String fShape
G4double * fRpar
G4int fNpar
G4int fNmed
G4VSolid * fSolid
G4LogicalVolume * fLV
G4bool fHasNegPars
G4bool fHasMANY
std::vector< G3VolTableEntry * > fDaughters
std::vector< G3VolTableEntry * > fMothers
std::vector< G3VolTableEntry * > fClones
std::vector< G3VolTableEntry * > fOverlaps
std::vector< G3Pos * > fG3Pos
G3Division * fDivision
Detailed Description
Definition at line 79 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 79 of file G3VolTableEntry.hh
Constructor & Destructor Documentation
G3VolTableEntry::G3VolTableEntry (G4String & vname, G4String & shape, G4double * rpar, G4int npar, G4int nmed, G4VSolid * solid, G4bool hasNegPars)
Definition at line 39 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 39 of file G3VolTableEntry.cc
References fClones, and fRpar.
G3VolTableEntry::~G3VolTableEntry () virtual
Definition at line 53 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 53 of file G3VolTableEntry.cc
References fDivision, and fRpar.
Member Function Documentation
void G3VolTableEntry::AddClone (G3VolTableEntry * aDaughter)
Definition at line 90 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 90 of file G3VolTableEntry.cc
References fClones, FindClone(), and GetName().
Referenced by G4CloneDaughters(), G4CreateCloneVTE(), and G4CreateCloneVTEWithDivision().
void G3VolTableEntry::AddDaughter (G3VolTableEntry * aDaughter)
Definition at line 76 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 76 of file G3VolTableEntry.cc
References fDaughters, FindDaughter(), and GetName().
Referenced by G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4gspos(), and G3Division::UpdateVTE().
void G3VolTableEntry::AddG3Pos (G3Pos * aG3Pos)
Definition at line 64 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 64 of file G3VolTableEntry.cc
References G3VolTable::CountG3Pos(), fG3Pos, G3Vol, G3Pos::GetOnly(), and SetHasMANY().
Referenced by G3Division::CreateEnvelope(), G4CloneDaughters(), G4CreateCloneVTE(), and G4gspos().
void G3VolTableEntry::AddMother (G3VolTableEntry * aDaughter)
Definition at line 83 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 83 of file G3VolTableEntry.cc
References FindMother(), fMothers, and GetName().
Referenced by G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4gspos(), and G3Division::UpdateVTE().
void G3VolTableEntry::AddOverlap (G3VolTableEntry * aOverlap)
Definition at line 97 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 97 of file G3VolTableEntry.cc
References fOverlaps.
Referenced by G4gsbool().
void G3VolTableEntry::ClearDivision ()
Definition at line 222 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 222 of file G3VolTableEntry.cc
References fDivision.
Referenced by G3toG4BuildPVTree().
void G3VolTableEntry::ClearG3PosCopy (G4int copy)
Definition at line 212 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 212 of file G3VolTableEntry.cc
References field_utils::copy(), fG3Pos, and it.
Referenced by G3toG4BuildPVTree().
G3VolTableEntry * G3VolTableEntry::FindClone (const G4String & vname)
Definition at line 155 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 155 of file G3VolTableEntry.cc
References GetClone(), GetName(), and GetNoClones().
Referenced by AddClone().
G3VolTableEntry * G3VolTableEntry::FindDaughter (const G4String & vname)
Definition at line 138 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 138 of file G3VolTableEntry.cc
References GetDaughter(), GetName(), and GetNoDaughters().
Referenced by AddDaughter().
G3VolTableEntry * G3VolTableEntry::FindMother (const G4String & vname)
Definition at line 146 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 146 of file G3VolTableEntry.cc
References GetMother(), GetName(), and GetNoMothers().
Referenced by AddMother(), and G3toG4BuildPVTree().
G3VolTableEntry * G3VolTableEntry::GetClone (G4int i)
Definition at line 331 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 331 of file G3VolTableEntry.cc
References fClones.
Referenced by FindClone(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4gspos(), and MakeBooleanSolids().
G3VolTableEntry * G3VolTableEntry::GetDaughter (G4int i)
Definition at line 306 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 306 of file G3VolTableEntry.cc
References fDaughters.
Referenced by FindDaughter(), G3toG4BuildLVTree(), G3toG4BuildPVTree(), G3toG4MANY(), G4CloneDaughters(), G4ProcessDaughters(), and SubstractSolids().
G3Division * G3VolTableEntry::GetDivision () inline
Definition at line 164 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 164 of file G3VolTableEntry.hh
References fDivision.
Referenced by G3toG4BuildLVTree(), G3toG4BuildPVTree(), G4CloneDaughters(), and G4ProcessDaughters().
G3Pos * G3VolTableEntry::GetG3PosCopy (G4int copy = 0)
Definition at line 258 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 258 of file G3VolTableEntry.cc
References fG3Pos.
Referenced by G3toG4BuildPVTree(), G3toG4MANY(), G4CloneDaughters(), and SubstractSolids().
G4LogicalVolume * G3VolTableEntry::GetLV ()
Definition at line 281 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 281 of file G3VolTableEntry.cc
References fLV.
Referenced by G3Division::CreatePVReplica(), G3toG4BuildLVTree(), G3toG4BuildPVTree(), and G4BuildGeom().
G3VolTableEntry * G3VolTableEntry::GetMasterClone ()
Definition at line 339 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 339 of file G3VolTableEntry.cc
References G4String::contains(), G4String::first(), fVname, G3Vol, G3VolTable::GetVTE(), and gSeparator.
Referenced by G3Division::CreateEnvelope(), G3toG4BuildLVTree(), G3toG4BuildPVTree(), G4CloneDaughters(), and MakeBooleanSolids().
G3VolTableEntry * G3VolTableEntry::GetMother (G4int i)
Definition at line 314 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 314 of file G3VolTableEntry.cc
References fMothers.
Referenced by G3toG4BuildPVTree(), and G3VolTable::SetFirstVTE().
G3VolTableEntry * G3VolTableEntry::GetMother ()
Definition at line 323 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 323 of file G3VolTableEntry.cc
References fMothers.
Referenced by FindMother().
G4String G3VolTableEntry::GetName (void)
Definition at line 228 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 228 of file G3VolTableEntry.cc
References fVname.
Referenced by AddClone(), AddDaughter(), AddMother(), G3Division::CreateEnvelope(), G3Division::CreatePVReplica(), G3Division::CreateSolid(), FindClone(), FindDaughter(), FindMother(), G3toG4BuildLVTree(), G3toG4BuildPVTree(), G3toG4MANY(), G4BuildGeom(), G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4ProcessDaughters(), MakeBooleanSolids(), G3VolTable::PrintAll(), G3VolTable::PutVTE(), ReplaceDaughter(), ReplaceMother(), G3VolTable::SetFirstVTE(), and SubstractSolids().
G4int G3VolTableEntry::GetNmed ()
Definition at line 238 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 238 of file G3VolTableEntry.cc
References fNmed.
Referenced by G3toG4BuildLVTree(), G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), and G3Division::UpdateVTE().
G4int G3VolTableEntry::GetNoClones ()
Definition at line 296 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 296 of file G3VolTableEntry.cc
References fClones.
Referenced by FindClone(), G3toG4BuildLVTree(), G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4gspos(), and MakeBooleanSolids().
G4int G3VolTableEntry::GetNoDaughters ()
Definition at line 286 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 286 of file G3VolTableEntry.cc
References fDaughters.
Referenced by FindDaughter(), G3toG4BuildLVTree(), G3toG4BuildPVTree(), G3toG4MANY(), G4CloneDaughters(), G4ProcessDaughters(), G3VolTable::PrintAll(), ReplaceDaughter(), and SubstractSolids().
G4int G3VolTableEntry::GetNoMothers ()
Definition at line 291 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 291 of file G3VolTableEntry.cc
References fMothers.
Referenced by FindMother(), G3toG4BuildPVTree(), and ReplaceMother().
G4int G3VolTableEntry::GetNoOverlaps ()
Definition at line 301 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 301 of file G3VolTableEntry.cc
References fOverlaps.
Referenced by G3toG4MANY().
G4int G3VolTableEntry::GetNpar ()
Definition at line 243 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 243 of file G3VolTableEntry.cc
References fNpar.
Referenced by G3Division::Dvn(), G3Division::Dvn2(), G3Division::Dvt(), G3Division::Dvt2(), G3NegVolPars(), G4CloneDaughters(), G4CreateCloneVTE(), G4gspos(), and G4ProcessDaughters().
std::vector< G3VolTableEntry * > * G3VolTableEntry::GetOverlaps ()
Definition at line 353 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 353 of file G3VolTableEntry.cc
References fOverlaps.
Referenced by G3toG4MANY().
G4double * G3VolTableEntry::GetRpar ()
Definition at line 248 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 248 of file G3VolTableEntry.cc
References fRpar.
Referenced by G3Division::Dvn(), G3Division::Dvn2(), G3Division::Dvt(), G3Division::Dvt2(), G3NegVolPars(), G4CloneDaughters(), G4CreateCloneVTE(), G4gspos(), G4ProcessDaughters(), and G3Division::SetRangeAndAxis().
G4String G3VolTableEntry::GetShape ()
Definition at line 233 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 233 of file G3VolTableEntry.cc
References fShape.
Referenced by G3Division::CreatePVReplica(), G3Division::Dvn(), G3Division::Dvn2(), G3Division::Dvt(), G3Division::Dvt2(), G3NegVolPars(), G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4ProcessDaughters(), and G3Division::SetRangeAndAxis().
G4VSolid * G3VolTableEntry::GetSolid ()
Definition at line 276 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 276 of file G3VolTableEntry.cc
References fSolid.
Referenced by G3toG4BuildLVTree(), G3toG4BuildPVTree(), and SubstractSolids().
G4bool G3VolTableEntry::HasMANY ()
Definition at line 271 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 271 of file G3VolTableEntry.cc
References fHasMANY.
Referenced by G3toG4MANY().
G4bool G3VolTableEntry::HasNegPars ()
Definition at line 266 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 266 of file G3VolTableEntry.cc
References fHasNegPars.
Referenced by G4CloneDaughters(), G4gspos(), G4ProcessDaughters(), and G3Division::UpdateVTE().
G4int G3VolTableEntry::NPCopies ()
Definition at line 253 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 253 of file G3VolTableEntry.cc
References fG3Pos.
Referenced by G3toG4BuildPVTree(), G3toG4MANY(), G4CloneDaughters(), MakeBooleanSolids(), G3VolTable::SetFirstVTE(), and SubstractSolids().
G4bool G3VolTableEntry::operator== (const G3VolTableEntry & vte) const
Definition at line 59 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 59 of file G3VolTableEntry.cc
void G3VolTableEntry::PrintSolidInfo ()
Definition at line 163 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 163 of file G3VolTableEntry.cc
References fHasMANY, fHasNegPars, fNpar, fRpar, fSolid, fVname, G4cout, and G4endl.
void G3VolTableEntry::ReplaceDaughter (G3VolTableEntry * vteOld, G3VolTableEntry * vteNew)
Definition at line 102 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 102 of file G3VolTableEntry.cc
References FatalException, fDaughters, G4Exception(), GetName(), and GetNoDaughters().
Referenced by G3Division::UpdateVTE().
void G3VolTableEntry::ReplaceMother (G3VolTableEntry * vteOld, G3VolTableEntry * vteNew)
Definition at line 120 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 120 of file G3VolTableEntry.cc
References FatalException, fMothers, G4Exception(), GetName(), and GetNoMothers().
Referenced by G3Division::UpdateVTE().
void G3VolTableEntry::SetDivision (G3Division * division) inline
Definition at line 161 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 161 of file G3VolTableEntry.hh
References fDivision.
Referenced by G4CloneDaughters(), and G4CreateCloneVTEWithDivision().
void G3VolTableEntry::SetHasMANY (G4bool hasMANY)
Definition at line 208 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 208 of file G3VolTableEntry.cc
References fHasMANY.
Referenced by AddG3Pos().
void G3VolTableEntry::SetHasNegPars (G4bool hasNegPars)
Definition at line 204 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 204 of file G3VolTableEntry.cc
References fHasNegPars.
Referenced by G3Division::CreateSolid(), G3Division::G3Division(), G4CreateCloneVTE(), and G4ProcessDaughters().
void G3VolTableEntry::SetLV (G4LogicalVolume * lv)
Definition at line 182 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 182 of file G3VolTableEntry.cc
References fLV.
Referenced by G3toG4BuildLVTree().
void G3VolTableEntry::SetName (G4String name)
Definition at line 177 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 177 of file G3VolTableEntry.cc
References fVname.
Referenced by G4CreateCloneVTE().
void G3VolTableEntry::SetNmed (G4int nmed)
Definition at line 191 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 191 of file G3VolTableEntry.cc
References fNmed.
Referenced by G3Division::UpdateVTE().
void G3VolTableEntry::SetNRpar (G4int npar, G4double * Rpar)
Definition at line 195 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 195 of file G3VolTableEntry.cc
References fNpar, and fRpar.
Referenced by G3Division::CreateSolid(), and G4ProcessDaughters().
void G3VolTableEntry::SetSolid (G4VSolid * solid)
Definition at line 187 of file G3VolTableEntry.cc.
View newest version in sPHENIX GitHub at line 187 of file G3VolTableEntry.cc
References fSolid.
Referenced by G3Division::CreateSolid(), G4CreateCloneVTE(), G4ProcessDaughters(), and SubstractSolids().
Member Data Documentation
std::vector<G3VolTableEntry*> G3VolTableEntry::fClones private
Definition at line 153 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 153 of file G3VolTableEntry.hh
Referenced by AddClone(), G3VolTableEntry(), GetClone(), and GetNoClones().
std::vector<G3VolTableEntry*> G3VolTableEntry::fDaughters private
Definition at line 151 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 151 of file G3VolTableEntry.hh
Referenced by AddDaughter(), GetDaughter(), GetNoDaughters(), and ReplaceDaughter().
G3Division* G3VolTableEntry::fDivision private
Definition at line 156 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 156 of file G3VolTableEntry.hh
Referenced by ClearDivision(), GetDivision(), SetDivision(), and ~G3VolTableEntry().
std::vector<G3Pos*> G3VolTableEntry::fG3Pos private
Definition at line 155 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 155 of file G3VolTableEntry.hh
Referenced by AddG3Pos(), ClearG3PosCopy(), GetG3PosCopy(), and NPCopies().
G4bool G3VolTableEntry::fHasMANY private
Definition at line 150 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 150 of file G3VolTableEntry.hh
Referenced by HasMANY(), PrintSolidInfo(), and SetHasMANY().
G4bool G3VolTableEntry::fHasNegPars private
Definition at line 149 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 149 of file G3VolTableEntry.hh
Referenced by HasNegPars(), PrintSolidInfo(), and SetHasNegPars().
G4LogicalVolume* G3VolTableEntry::fLV private
Definition at line 148 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 148 of file G3VolTableEntry.hh
Referenced by GetLV(), and SetLV().
std::vector<G3VolTableEntry*> G3VolTableEntry::fMothers private
Definition at line 152 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 152 of file G3VolTableEntry.hh
Referenced by AddMother(), GetMother(), GetNoMothers(), and ReplaceMother().
G4int G3VolTableEntry::fNmed private
Definition at line 146 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 146 of file G3VolTableEntry.hh
Referenced by GetNmed(), and SetNmed().
G4int G3VolTableEntry::fNpar private
Definition at line 145 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 145 of file G3VolTableEntry.hh
Referenced by GetNpar(), PrintSolidInfo(), and SetNRpar().
std::vector<G3VolTableEntry*> G3VolTableEntry::fOverlaps private
Definition at line 154 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 154 of file G3VolTableEntry.hh
Referenced by AddOverlap(), GetNoOverlaps(), and GetOverlaps().
G4double* G3VolTableEntry::fRpar private
Definition at line 144 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 144 of file G3VolTableEntry.hh
Referenced by G3VolTableEntry(), GetRpar(), PrintSolidInfo(), SetNRpar(), and ~G3VolTableEntry().
G4String G3VolTableEntry::fShape private
Definition at line 143 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 143 of file G3VolTableEntry.hh
Referenced by GetShape().
G4VSolid* G3VolTableEntry::fSolid private
Definition at line 147 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 147 of file G3VolTableEntry.hh
Referenced by GetSolid(), PrintSolidInfo(), and SetSolid().
G4String G3VolTableEntry::fVname private
Definition at line 142 of file G3VolTableEntry.hh.
View newest version in sPHENIX GitHub at line 142 of file G3VolTableEntry.hh
Referenced by GetMasterClone(), GetName(), PrintSolidInfo(), and SetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3VolTableEntry.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3VolTableEntry.cc