ECCE @ EIC Software: G4ParallelWorldProcess Class Reference
G4ParallelWorldProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4ParallelWorldProcess.hh>
Public Member Functions
G4ParallelWorldProcess (const G4String &processName="ParaWorld", G4ProcessType theType=fParallel)
virtual ~G4ParallelWorldProcess ()
void SetParallelWorld (G4String parallelWorldName)
void SetParallelWorld (G4VPhysicalVolume *parallelWorld)
void StartTracking (G4Track *)
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *)
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
void SetLayeredMaterialFlag (G4bool flg=true)
G4bool GetLayeredMaterialFlag () const
G4bool IsAtRestRequired (G4ParticleDefinition *)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static const G4Step * GetHyperStep ()
static G4int GetHypNavigatorID ()
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Private Member Functions
void CopyStep (const G4Step &step)
void SwitchMaterial (G4StepPoint *)
Private Attributes
G4Step * fGhostStep
G4StepPoint * fGhostPreStepPoint
G4StepPoint * fGhostPostStepPoint
G4VParticleChange aDummyParticleChange
G4ParticleChange xParticleChange
G4TransportationManager * fTransportationManager
G4PathFinder * fPathFinder
G4String fGhostWorldName
G4VPhysicalVolume * fGhostWorld
G4Navigator * fGhostNavigator
G4int fNavigatorID
G4TouchableHandle fOldGhostTouchable
G4TouchableHandle fNewGhostTouchable
G4FieldTrack fFieldTrack
G4double fGhostSafety
G4bool fOnBoundary
G4bool layeredMaterialFlag
G4int iParallelWorld
Static Private Attributes
static G4ThreadLocal G4Step * fpHyperStep = 0
static G4ThreadLocal G4int nParallelWorlds = 0
static G4ThreadLocal G4int fNavIDHyp = 0
Additional Inherited Members
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 71 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParallelWorldProcess.hh
Constructor & Destructor Documentation
G4ParallelWorldProcess::G4ParallelWorldProcess (const G4String & processName = "ParaWorld", G4ProcessType theType = fParallel)
Definition at line 60 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 60 of file G4ParallelWorldProcess.cc
References aDummyParticleChange, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fGhostWorldName, fPathFinder, fpHyperStep, fTransportationManager, G4cout, G4endl, G4PathFinder::GetInstance(), G4ParallelWorldProcessStore::GetInstance(), G4TransportationManager::GetNavigatorForTracking(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VProcess::GetProcessName(), G4TransportationManager::GetTransportationManager(), iParallelWorld, nParallelWorlds, G4VProcess::pParticleChange, G4ParallelWorldProcessStore::SetParallelWorld(), G4VProcess::SetProcessSubType(), G4Navigator::SetPushVerbosity(), and G4VProcess::verboseLevel.
G4ParallelWorldProcess::~G4ParallelWorldProcess () virtual
Definition at line 88 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ParallelWorldProcess.cc
References fGhostStep, fpHyperStep, and nParallelWorlds.
Member Function Documentation
G4VParticleChange * G4ParallelWorldProcess::AlongStepDoIt (const G4Track & track, const G4Step &) virtual
Implements G4VProcess.
Definition at line 342 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 342 of file G4ParallelWorldProcess.cc
References G4VParticleChange::Initialize(), and G4VProcess::pParticleChange.
G4double G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 269 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 269 of file G4ParallelWorldProcess.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PathFinder::ComputeStep(), DBL_MAX, fFieldTrack, fGhostNavigator, fGhostSafety, fNavIDHyp, fNavigatorID, fOnBoundary, fPathFinder, G4cout, G4endl, G4ThreadLocal, G4Track::GetCurrentStepNumber(), G4VProcess::GetProcessName(), G4Track::GetVolume(), iParallelWorld, kDoNot, kSharedOther, kSharedTransport, kUndefLimited, kUnique, NotCandidateForSelection, nParallelWorlds, G4FieldTrackUpdator::Update(), and G4VProcess::verboseLevel.
G4VParticleChange * G4ParallelWorldProcess::AtRestDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 175 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ParallelWorldProcess.cc
References CopyStep(), fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetSensitiveDetector(), G4StepPoint::GetTouchableHandle(), G4VTouchable::GetVolume(), G4VSensitiveDetector::Hit(), G4VParticleChange::Initialize(), G4VProcess::pParticleChange, G4StepPoint::SetSensitiveDetector(), and G4StepPoint::SetTouchableHandle().
G4double G4ParallelWorldProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 163 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 163 of file G4ParallelWorldProcess.cc
References DBL_MAX, and Forced.
void G4ParallelWorldProcess::CopyStep (const G4Step & step) private
Definition at line 349 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 349 of file G4ParallelWorldProcess.cc
References fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fOnBoundary, fpHyperStep, fPostStepDoItProc, G4Step::GetControlFlag(), G4Step::GetNonIonizingEnergyDeposit(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), iParallelWorld, G4Step::SetControlFlag(), G4Step::SetNonIonizingEnergyDeposit(), G4Step::SetSecondary(), G4Step::SetStepLength(), G4StepPoint::SetStepStatus(), G4Step::SetTotalEnergyDeposit(), and G4Step::SetTrack().
Referenced by AtRestDoIt(), and PostStepDoIt().
const G4Step * G4ParallelWorldProcess::GetHyperStep () static
Definition at line 54 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ParallelWorldProcess.cc
References fpHyperStep.
Referenced by G4RayTrajectory::AppendStep(), G4UCNBoundaryProcess::PostStepDoIt(), and G4OpBoundaryProcess::PostStepDoIt().
G4int G4ParallelWorldProcess::GetHypNavigatorID () static
Definition at line 56 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParallelWorldProcess.cc
References fNavIDHyp.
Referenced by G4RayTrajectory::AppendStep(), G4UCNBoundaryProcess::PostStepDoIt(), and G4OpBoundaryProcess::PostStepDoIt().
G4bool G4ParallelWorldProcess::GetLayeredMaterialFlag () const inline
Definition at line 125 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ParallelWorldProcess.hh
References layeredMaterialFlag.
G4bool G4ParallelWorldProcess::IsAtRestRequired (G4ParticleDefinition * partDef)
Definition at line 429 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 429 of file G4ParallelWorldProcess.cc
References G4ParticleDefinition::GetParticleName(), and G4ParticleDefinition::GetPDGEncoding().
Referenced by B03PhysicsList::AddScoringProcess(), G4ParallelWorldPhysics::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
G4VParticleChange * G4ParallelWorldProcess::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 222 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 222 of file G4ParallelWorldProcess.cc
References CopyStep(), G4PathFinder::CreateTouchableHandle(), fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fPathFinder, G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetSensitiveDetector(), G4LogicalVolume::GetSensitiveDetector(), G4Track::GetStep(), G4StepPoint::GetTouchableHandle(), G4VTouchable::GetVolume(), G4VSensitiveDetector::Hit(), G4VParticleChange::Initialize(), layeredMaterialFlag, G4VProcess::pParticleChange, G4StepPoint::SetSensitiveDetector(), G4StepPoint::SetTouchableHandle(), and SwitchMaterial().
G4double G4ParallelWorldProcess::PostStepGetPhysicalInteractionLength (const G4Track & , G4double , G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 213 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 213 of file G4ParallelWorldProcess.cc
References DBL_MAX, and StronglyForced.
void G4ParallelWorldProcess::SetLayeredMaterialFlag (G4bool flg = true) inline
Definition at line 123 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ParallelWorldProcess.hh
References layeredMaterialFlag.
Referenced by G4ParallelWorldPhysics::ConstructProcess().
void G4ParallelWorldProcess::SetParallelWorld (G4String parallelWorldName)
Definition at line 100 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ParallelWorldProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4TransportationManager::GetNavigator(), G4TransportationManager::GetParallelWorld(), and G4Navigator::SetPushVerbosity().
Referenced by B03PhysicsList::AddScoringProcess(), G4ParallelWorldPhysics::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
void G4ParallelWorldProcess::SetParallelWorld (G4VPhysicalVolume * parallelWorld)
Definition at line 109 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 109 of file G4ParallelWorldProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4VPhysicalVolume::GetName(), G4TransportationManager::GetNavigator(), and G4Navigator::SetPushVerbosity().
void G4ParallelWorldProcess::StartTracking (G4Track * trk) virtual
Reimplemented from G4VProcess.
Definition at line 117 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 117 of file G4ParallelWorldProcess.cc
References G4TransportationManager::ActivateNavigator(), G4Track::CalculateVelocity(), G4PathFinder::CreateTouchableHandle(), FatalException, fGhostNavigator, fGhostPostStepPoint, fGhostPreStepPoint, fGhostSafety, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fPathFinder, fpHyperStep, fTransportationManager, fUndefined, G4Exception(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Track::GetStep(), layeredMaterialFlag, G4PathFinder::PrepareNewTrack(), G4StepPoint::SetStepStatus(), G4StepPoint::SetTouchableHandle(), G4StepPoint::SetVelocity(), G4Track::SetVelocity(), and SwitchMaterial().
void G4ParallelWorldProcess::SwitchMaterial (G4StepPoint * realWorldStepPoint) private
Definition at line 389 of file G4ParallelWorldProcess.cc.
View newest version in sPHENIX GitHub at line 389 of file G4ParallelWorldProcess.cc
References fGhostPostStepPoint, fNewGhostTouchable, fpHyperStep, fWorldBoundary, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetMaterial(), G4LogicalVolume::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4StepPoint::GetMaterialCutsCouple(), G4Material::GetName(), G4Step::GetPostStepPoint(), G4MaterialCutsCouple::GetProductionCuts(), G4Region::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetRegion(), G4StepPoint::GetStepStatus(), G4VTouchable::GetVolume(), G4StepPoint::SetMaterial(), and G4StepPoint::SetMaterialCutsCouple().
Referenced by PostStepDoIt(), and StartTracking().
Member Data Documentation
G4VParticleChange G4ParallelWorldProcess::aDummyParticleChange private
Definition at line 143 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 143 of file G4ParallelWorldProcess.hh
Referenced by G4ParallelWorldProcess().
G4FieldTrack G4ParallelWorldProcess::fFieldTrack private
Definition at line 158 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4Navigator* G4ParallelWorldProcess::fGhostNavigator private
Definition at line 154 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), SetParallelWorld(), and StartTracking().
G4StepPoint* G4ParallelWorldProcess::fGhostPostStepPoint private
Definition at line 141 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ParallelWorldProcess.hh
Referenced by AtRestDoIt(), CopyStep(), G4ParallelWorldProcess(), PostStepDoIt(), StartTracking(), and SwitchMaterial().
G4StepPoint* G4ParallelWorldProcess::fGhostPreStepPoint private
Definition at line 140 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ParallelWorldProcess.hh
Referenced by AtRestDoIt(), CopyStep(), G4ParallelWorldProcess(), PostStepDoIt(), and StartTracking().
G4double G4ParallelWorldProcess::fGhostSafety private
Definition at line 159 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4Step* G4ParallelWorldProcess::fGhostStep private
Definition at line 139 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ParallelWorldProcess.hh
Referenced by AtRestDoIt(), CopyStep(), G4ParallelWorldProcess(), PostStepDoIt(), and ~G4ParallelWorldProcess().
G4VPhysicalVolume* G4ParallelWorldProcess::fGhostWorld private
Definition at line 153 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParallelWorldProcess.hh
Referenced by SetParallelWorld().
G4String G4ParallelWorldProcess::fGhostWorldName private
Definition at line 152 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ParallelWorldProcess.hh
Referenced by G4ParallelWorldProcess(), and SetParallelWorld().
G4ThreadLocal G4int G4ParallelWorldProcess::fNavIDHyp = 0 static private
Definition at line 176 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and GetHypNavigatorID().
G4int G4ParallelWorldProcess::fNavigatorID private
Definition at line 155 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4TouchableHandle G4ParallelWorldProcess::fNewGhostTouchable private
Definition at line 157 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParallelWorldProcess.hh
Referenced by AtRestDoIt(), PostStepDoIt(), StartTracking(), and SwitchMaterial().
G4TouchableHandle G4ParallelWorldProcess::fOldGhostTouchable private
Definition at line 156 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParallelWorldProcess.hh
Referenced by AtRestDoIt(), PostStepDoIt(), and StartTracking().
G4bool G4ParallelWorldProcess::fOnBoundary private
Definition at line 160 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), AtRestDoIt(), CopyStep(), PostStepDoIt(), and StartTracking().
G4PathFinder* G4ParallelWorldProcess::fPathFinder private
Definition at line 147 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess(), PostStepDoIt(), and StartTracking().
G4ThreadLocal G4Step * G4ParallelWorldProcess::fpHyperStep = 0 static private
Definition at line 174 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ParallelWorldProcess.hh
Referenced by CopyStep(), G4ParallelWorldProcess(), GetHyperStep(), StartTracking(), SwitchMaterial(), and ~G4ParallelWorldProcess().
G4TransportationManager* G4ParallelWorldProcess::fTransportationManager private
Definition at line 146 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ParallelWorldProcess.hh
Referenced by G4ParallelWorldProcess(), SetParallelWorld(), and StartTracking().
G4int G4ParallelWorldProcess::iParallelWorld private
Definition at line 177 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), CopyStep(), and G4ParallelWorldProcess().
G4bool G4ParallelWorldProcess::layeredMaterialFlag private
Definition at line 165 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ParallelWorldProcess.hh
Referenced by GetLayeredMaterialFlag(), PostStepDoIt(), SetLayeredMaterialFlag(), and StartTracking().
G4ThreadLocal G4int G4ParallelWorldProcess::nParallelWorlds = 0 static private
Definition at line 175 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ParallelWorldProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess(), and ~G4ParallelWorldProcess().
G4ParticleChange G4ParallelWorldProcess::xParticleChange private
Definition at line 144 of file G4ParallelWorldProcess.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParallelWorldProcess.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4ParallelWorldProcess.hh
geant4/tree/geant4-10.6-release/source/processes/scoring/src/G4ParallelWorldProcess.cc