ECCE @ EIC Software: G4SolidStore Class Reference
G4SolidStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SolidStore.hh>
Public Member Functions
G4VSolid * GetSolid (const G4String &name, G4bool verbose=true) const
virtual ~G4SolidStore ()
Static Public Member Functions
static void Register (G4VSolid *pSolid)
static void DeRegister (G4VSolid *pSolid)
static G4SolidStore * GetInstance ()
static void SetNotifier (G4VStoreNotifier *pNotifier)
static void Clean ()
Protected Member Functions
G4SolidStore ()
Static Private Attributes
static G4SolidStore * fgInstance = nullptr
static G4ThreadLocal
G4VStoreNotifier * fgNotifier = nullptr
static G4ThreadLocal G4bool locked = false
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 59 of file G4SolidStore.hh.
View newest version in sPHENIX GitHub at line 59 of file G4SolidStore.hh
Constructor & Destructor Documentation
G4SolidStore::~G4SolidStore () virtual
Definition at line 59 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 59 of file G4SolidStore.cc
References Clean().
G4SolidStore::G4SolidStore () protected
Definition at line 49 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 49 of file G4SolidStore.cc
Member Function Documentation
void G4SolidStore::Clean () static
Definition at line 68 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 68 of file G4SolidStore.cc
References fgNotifier, G4cout, G4endl, GetInstance(), G4GeometryManager::IsGeometryClosed(), locked, G4VNotifier::NotifyDeRegistration(), and pos().
Referenced by PHG4PhenixDetector::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4RunManager::ReinitializeGeometry(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), and ~G4SolidStore().
void G4SolidStore::DeRegister (G4VSolid * pSolid) static
Definition at line 132 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 132 of file G4SolidStore.cc
References fgNotifier, GetInstance(), locked, and G4VNotifier::NotifyDeRegistration().
Referenced by G4Voxelizer::G4Voxelizer(), and G4VSolid::~G4VSolid().
G4SolidStore * G4SolidStore::GetInstance (void) static
Definition at line 173 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 173 of file G4SolidStore.cc
References fgInstance.
Referenced by Clean(), PHG4PhenixDetector::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), DeRegister(), G4Voxelizer::G4Voxelizer(), G4VSolid::G4VSolid(), G4GDMLReadSolids::GetSolid(), GetSolid(), Register(), G4RunManager::ReinitializeGeometry(), SetNotifier(), G4GeometryManager::SetWorldMaximumExtent(), G4GDMLRead::StripNames(), and G4VSolid::~G4VSolid().
G4VSolid * G4SolidStore::GetSolid (const G4String & name, G4bool verbose = true) const
Definition at line 152 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 152 of file G4SolidStore.cc
References G4endl, G4Exception(), GetInstance(), JustWarning, and message().
Referenced by G4GDMLReadSolids::GetSolid().
void G4SolidStore::Register (G4VSolid * pSolid) static
Definition at line 122 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 122 of file G4SolidStore.cc
References fgNotifier, GetInstance(), and G4VNotifier::NotifyRegistration().
Referenced by G4VSolid::G4VSolid().
void G4SolidStore::SetNotifier (G4VStoreNotifier * pNotifier) static
Definition at line 112 of file G4SolidStore.cc.
View newest version in sPHENIX GitHub at line 112 of file G4SolidStore.cc
References fgNotifier, and GetInstance().
Member Data Documentation
G4SolidStore * G4SolidStore::fgInstance = nullptr static private
Definition at line 87 of file G4SolidStore.hh.
View newest version in sPHENIX GitHub at line 87 of file G4SolidStore.hh
Referenced by GetInstance().
G4ThreadLocal G4VStoreNotifier * G4SolidStore::fgNotifier = nullptr static private
Definition at line 88 of file G4SolidStore.hh.
View newest version in sPHENIX GitHub at line 88 of file G4SolidStore.hh
Referenced by Clean(), DeRegister(), Register(), and SetNotifier().
G4ThreadLocal G4bool G4SolidStore::locked = false static private
Definition at line 89 of file G4SolidStore.hh.
View newest version in sPHENIX GitHub at line 89 of file G4SolidStore.hh
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SolidStore.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4SolidStore.cc