ECCE @ EIC Software: FFDetectorConstruction Class Reference
FFDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/hadronic/FissionFragment/include/FFDetectorConstruction.hh>
Public Member Functions
FFDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual ~FFDetectorConstruction ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials (void)
void PlaceFuelPlate (double x, double y, G4LogicalVolume *const myLogicalVolume, G4LogicalVolume *const parentLogicalVolume)
Private Attributes
G4Material * fAir
G4Material * fAluminum
G4Material * fBF3_96E
G4Material * fGraphite
G4Material * fStainlessSteel
G4Material * fPolyethylene
G4Material * fUO2_20E
G4Material * fWater
unsigned int fCopyNumber
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 51 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 51 of file FFDetectorConstruction.hh
Constructor & Destructor Documentation
FFDetectorConstruction::FFDetectorConstruction ()
Definition at line 71 of file FFDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 71 of file FFDetectorConstruction.cc
References DefineMaterials().
FFDetectorConstruction::~FFDetectorConstruction () virtual
Definition at line 568 of file FFDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 568 of file FFDetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * FFDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 79 of file FFDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 79 of file FFDetectorConstruction.cc
References deg, fAir, fAluminum, fBF3_96E, fCopyNumber, fGraphite, fPolyethylene, fStainlessSteel, fUO2_20E, G4cout, G4endl, G4VSolid::GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), inch, PlaceFuelPlate(), position, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::setZ(), x, and y.
void FFDetectorConstruction::DefineMaterials (void) private
Definition at line 417 of file FFDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 417 of file FFDetectorConstruction.cc
References G4Material::AddElement(), G4Element::AddIsotope(), cm3, fAir, fAluminum, fBF3_96E, fGraphite, G4NistManager::FindOrBuildElement(), G4NistManager::FindOrBuildMaterial(), fPolyethylene, fStainlessSteel, fUO2_20E, fWater, Acts::UnitConstants::g, G4Element::GetA(), G4NistManager::Instance(), kg, m3, and mole.
Referenced by FFDetectorConstruction().
void FFDetectorConstruction::PlaceFuelPlate (double x, double y, G4LogicalVolume *const myLogicalVolume, G4LogicalVolume *const parentLogicalVolume) private
Definition at line 543 of file FFDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 543 of file FFDetectorConstruction.cc
References fCopyNumber, inch, and position.
Referenced by Construct().
Member Data Documentation
G4Material* FFDetectorConstruction::fAir private
Definition at line 66 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* FFDetectorConstruction::fAluminum private
Definition at line 67 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* FFDetectorConstruction::fBF3_96E private
Definition at line 68 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 68 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
unsigned int FFDetectorConstruction::fCopyNumber private
Definition at line 74 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file FFDetectorConstruction.hh
Referenced by Construct(), and PlaceFuelPlate().
G4Material* FFDetectorConstruction::fGraphite private
Definition at line 69 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* FFDetectorConstruction::fPolyethylene private
Definition at line 71 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 71 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* FFDetectorConstruction::fStainlessSteel private
Definition at line 70 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 70 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* FFDetectorConstruction::fUO2_20E private
Definition at line 72 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 72 of file FFDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* FFDetectorConstruction::fWater private
Definition at line 73 of file FFDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file FFDetectorConstruction.hh
Referenced by DefineMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/hadronic/FissionFragment/include/FFDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/FissionFragment/src/FFDetectorConstruction.cc