ECCE @ EIC Software: G4EmExtraParameters Class Reference
G4EmExtraParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmExtraParameters.hh>
Public Member Functions
G4EmExtraParameters ()
~G4EmExtraParameters ()
void Initialise ()
G4bool GetDirectionalSplitting ()
void SetDirectionalSplitting (G4bool v)
G4bool QuantumEntanglement ()
void SetQuantumEntanglement (G4bool v)
void SetDirectionalSplittingRadius (G4double r)
G4double GetDirectionalSplittingRadius ()
void SetDirectionalSplittingTarget (const G4ThreeVector &v)
G4ThreeVector GetDirectionalSplittingTarget () const
void SetStepFunction (G4double v1, G4double v2)
G4double GetStepFunctionP1 () const
G4double GetStepFunctionP2 () const
void SetStepFunctionMuHad (G4double v1, G4double v2)
G4double GetStepFunctionMuHadP1 () const
G4double GetStepFunctionMuHadP2 () const
void AddPAIModel (const G4String &particle, const G4String &region, const G4String &type)
const std::vector< G4String > & ParticlesPAI () const
const std::vector< G4String > & RegionsPAI () const
const std::vector< G4String > & TypesPAI () const
void AddPhysics (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsPhysics () const
const std::vector< G4String > & TypesPhysics () const
void SetSubCutoff (G4bool val, const G4String &region="")
void SetProcessBiasingFactor (const G4String &procname, G4double val, G4bool wflag)
void ActivateForcedInteraction (const G4String &procname, const G4String &region, G4double length, G4bool wflag)
void ActivateSecondaryBiasing (const G4String &name, const G4String &region, G4double factor, G4double energyLimit)
void DefineRegParamForLoss (G4VEnergyLossProcess *, G4bool isElectron) const
void DefineRegParamForEM (G4VEmProcess *) const
G4EmExtraParameters (G4EmExtraParameters &)=delete
G4EmExtraParameters & operator= (const G4EmExtraParameters &right)=delete
Private Member Functions
G4String CheckRegion (const G4String &) const
void PrintWarning (G4ExceptionDescription &ed) const
Private Attributes
G4EmExtraParametersMessenger * theMessenger
G4bool directionalSplitting
G4bool quantumEntanglement
G4double dRoverRange
G4double finalRange
G4double dRoverRangeMuHad
G4double finalRangeMuHad
G4double directionalSplittingRadius
G4ThreeVector directionalSplittingTarget
std::vector< G4String > m_particlesPAI
std::vector< G4String > m_regnamesPAI
std::vector< G4String > m_typesPAI
std::vector< G4String > m_regnamesPhys
std::vector< G4String > m_typesPhys
std::vector< G4String > m_regnamesSubCut
std::vector< G4bool > m_subCuts
std::vector< G4String > m_procBiasedXS
std::vector< G4double > m_factBiasedXS
std::vector< G4bool > m_weightBiasedXS
std::vector< G4String > m_procForced
std::vector< G4String > m_regnamesForced
std::vector< G4double > m_lengthForced
std::vector< G4bool > m_weightForced
std::vector< G4String > m_procBiasedSec
std::vector< G4String > m_regnamesBiasedSec
std::vector< G4double > m_factBiasedSec
std::vector< G4double > m_elimBiasedSec
Detailed Description
Definition at line 61 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 61 of file G4EmExtraParameters.hh
Constructor & Destructor Documentation
G4EmExtraParameters::G4EmExtraParameters () explicit
Definition at line 54 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 54 of file G4EmExtraParameters.cc
References Initialise(), and theMessenger.
G4EmExtraParameters::~G4EmExtraParameters ()
Definition at line 62 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 62 of file G4EmExtraParameters.cc
References theMessenger.
G4EmExtraParameters::G4EmExtraParameters (G4EmExtraParameters &) delete
Member Function Documentation
void G4EmExtraParameters::ActivateForcedInteraction (const G4String & procname, const G4String & region, G4double length, G4bool wflag)
Definition at line 253 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 253 of file G4EmExtraParameters.cc
References CheckRegion(), BTOF::length, m_lengthForced, m_procForced, m_regnamesForced, m_weightForced, n, PrintWarning(), and r.
Referenced by G4EmParameters::ActivateForcedInteraction(), and G4EmExtraParametersMessenger::SetNewValue().
void G4EmExtraParameters::ActivateSecondaryBiasing (const G4String & name, const G4String & region, G4double factor, G4double energyLimit)
Definition at line 282 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 282 of file G4EmExtraParameters.cc
References CheckRegion(), m_elimBiasedSec, m_factBiasedSec, m_procBiasedSec, m_regnamesBiasedSec, n, PrintWarning(), and r.
Referenced by G4EmParameters::ActivateSecondaryBiasing(), and G4EmExtraParametersMessenger::SetNewValue().
void G4EmExtraParameters::AddPAIModel (const G4String & particle, const G4String & region, const G4String & type)
Definition at line 152 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 152 of file G4EmExtraParameters.cc
References CheckRegion(), m_particlesPAI, m_regnamesPAI, m_typesPAI, particle, and r.
Referenced by G4EmParameters::AddPAIModel(), and G4EmExtraParametersMessenger::SetNewValue().
void G4EmExtraParameters::AddPhysics (const G4String & region, const G4String & type)
Definition at line 192 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 192 of file G4EmExtraParameters.cc
References CheckRegion(), m_regnamesPhys, m_typesPhys, and r.
Referenced by G4EmParameters::AddPhysics(), and G4EmExtraParametersMessenger::SetNewValue().
G4String G4EmExtraParameters::CheckRegion (const G4String & reg) const private
Definition at line 97 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 97 of file G4EmExtraParameters.cc
References r, and reg.
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), AddPAIModel(), AddPhysics(), and SetSubCutoff().
void G4EmExtraParameters::DefineRegParamForEM (G4VEmProcess * ptr) const
Definition at line 350 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 350 of file G4EmExtraParameters.cc
References G4VEmProcess::ActivateForcedInteraction(), G4VEmProcess::ActivateSecondaryBiasing(), G4VProcess::GetProcessName(), m_elimBiasedSec, m_factBiasedSec, m_factBiasedXS, m_lengthForced, m_procBiasedSec, m_procBiasedXS, m_procForced, m_regnamesBiasedSec, m_regnamesForced, m_weightBiasedXS, m_weightForced, n, and G4VEmProcess::SetCrossSectionBiasingFactor().
Referenced by G4EmParameters::DefineRegParamForEM().
void G4EmExtraParameters::DefineRegParamForLoss (G4VEnergyLossProcess * ptr, G4bool isElectron) const
Definition at line 310 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 310 of file G4EmExtraParameters.cc
References G4VEnergyLossProcess::ActivateForcedInteraction(), G4VEnergyLossProcess::ActivateSecondaryBiasing(), G4VEnergyLossProcess::ActivateSubCutoff(), dRoverRange, dRoverRangeMuHad, finalRange, finalRangeMuHad, G4RegionStore::GetInstance(), G4VProcess::GetProcessName(), G4RegionStore::GetRegion(), m_elimBiasedSec, m_factBiasedSec, m_factBiasedXS, m_lengthForced, m_procBiasedSec, m_procBiasedXS, m_procForced, m_regnamesBiasedSec, m_regnamesForced, m_regnamesSubCut, m_subCuts, m_weightBiasedXS, m_weightForced, n, reg, G4VEnergyLossProcess::SetCrossSectionBiasingFactor(), and G4VEnergyLossProcess::SetStepFunction().
Referenced by G4EmParameters::DefineRegParamForLoss().
G4bool G4EmExtraParameters::GetDirectionalSplitting ()
Definition at line 390 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 390 of file G4EmExtraParameters.cc
References directionalSplitting.
Referenced by G4EmParameters::GetDirectionalSplitting().
G4double G4EmExtraParameters::GetDirectionalSplittingRadius ()
Definition at line 415 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 415 of file G4EmExtraParameters.cc
References directionalSplittingRadius.
Referenced by G4EmParameters::GetDirectionalSplittingRadius().
G4ThreeVector G4EmExtraParameters::GetDirectionalSplittingTarget () const
Definition at line 405 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 405 of file G4EmExtraParameters.cc
References directionalSplittingTarget.
Referenced by G4EmParameters::GetDirectionalSplittingTarget().
G4double G4EmExtraParameters::GetStepFunctionMuHadP1 () const
Definition at line 142 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 142 of file G4EmExtraParameters.cc
References dRoverRangeMuHad.
Referenced by G4EmParameters::StreamInfo().
G4double G4EmExtraParameters::GetStepFunctionMuHadP2 () const
Definition at line 147 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 147 of file G4EmExtraParameters.cc
References finalRangeMuHad.
Referenced by G4EmParameters::StreamInfo().
G4double G4EmExtraParameters::GetStepFunctionP1 () const
Definition at line 119 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 119 of file G4EmExtraParameters.cc
References dRoverRange.
Referenced by G4EmParameters::StreamInfo().
G4double G4EmExtraParameters::GetStepFunctionP2 () const
Definition at line 124 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 124 of file G4EmExtraParameters.cc
References finalRange.
Referenced by G4EmParameters::StreamInfo().
void G4EmExtraParameters::Initialise ()
Definition at line 69 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 69 of file G4EmExtraParameters.cc
References directionalSplitting, directionalSplittingRadius, directionalSplittingTarget, dRoverRange, dRoverRangeMuHad, finalRange, finalRangeMuHad, m_lengthForced, m_procForced, m_regnamesForced, m_regnamesSubCut, m_subCuts, m_weightForced, CLHEP::mm, quantumEntanglement, and CLHEP::Hep3Vector::set().
Referenced by G4EmExtraParameters(), G4EmParameters::SetDefaults(), and G4EmParameters::SetGeneralProcessActive().
G4EmExtraParameters& G4EmExtraParameters::operator= (const G4EmExtraParameters & right) delete
const std::vector< G4String > & G4EmExtraParameters::ParticlesPAI () const
Definition at line 177 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 177 of file G4EmExtraParameters.cc
References m_particlesPAI.
Referenced by G4EmParameters::ParticlesPAI().
void G4EmExtraParameters::PrintWarning (G4ExceptionDescription & ed) const private
Definition at line 92 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 92 of file G4EmExtraParameters.cc
References G4Exception(), and JustWarning.
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), SetProcessBiasingFactor(), SetStepFunction(), and SetStepFunctionMuHad().
G4bool G4EmExtraParameters::QuantumEntanglement ()
Definition at line 380 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 380 of file G4EmExtraParameters.cc
References quantumEntanglement.
Referenced by G4EmParameters::QuantumEntanglement(), and G4EmParameters::StreamInfo().
const std::vector< G4String > & G4EmExtraParameters::RegionsPAI () const
Definition at line 182 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 182 of file G4EmExtraParameters.cc
References m_regnamesPAI.
Referenced by G4EmParameters::RegionsPAI().
const std::vector< G4String > & G4EmExtraParameters::RegionsPhysics () const
Definition at line 204 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 204 of file G4EmExtraParameters.cc
References m_regnamesPhys.
Referenced by G4EmParameters::RegionsPhysics().
void G4EmExtraParameters::SetDirectionalSplitting (G4bool v)
Definition at line 394 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 394 of file G4EmExtraParameters.cc
References directionalSplitting, and v.
Referenced by G4EmParameters::SetDirectionalSplitting(), and G4EmExtraParametersMessenger::SetNewValue().
void G4EmExtraParameters::SetDirectionalSplittingRadius (G4double r)
Definition at line 410 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 410 of file G4EmExtraParameters.cc
References directionalSplittingRadius, and r.
Referenced by G4EmParameters::SetDirectionalSplittingRadius(), and G4EmExtraParametersMessenger::SetNewValue().
void G4EmExtraParameters::SetDirectionalSplittingTarget (const G4ThreeVector & v)
Definition at line 400 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 400 of file G4EmExtraParameters.cc
References directionalSplittingTarget, and v.
Referenced by G4EmParameters::SetDirectionalSplittingTarget(), and G4EmExtraParametersMessenger::SetNewValue().
void G4EmExtraParameters::SetProcessBiasingFactor (const G4String & procname, G4double val, G4bool wflag)
Definition at line 229 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 229 of file G4EmExtraParameters.cc
References m_factBiasedXS, m_procBiasedXS, m_weightBiasedXS, n, and PrintWarning().
Referenced by G4EmExtraParametersMessenger::SetNewValue(), and G4EmParameters::SetProcessBiasingFactor().
void G4EmExtraParameters::SetQuantumEntanglement (G4bool v)
Definition at line 385 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 385 of file G4EmExtraParameters.cc
References quantumEntanglement, and v.
Referenced by G4EmExtraParametersMessenger::SetNewValue(), and G4EmParameters::SetQuantumEntanglement().
void G4EmExtraParameters::SetStepFunction (G4double v1, G4double v2)
Definition at line 106 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 106 of file G4EmExtraParameters.cc
References dRoverRange, finalRange, CLHEP::mm, PrintWarning(), v1, and v2.
Referenced by G4EmExtraParametersMessenger::SetNewValue(), and G4EmParameters::SetStepFunction().
void G4EmExtraParameters::SetStepFunctionMuHad (G4double v1, G4double v2)
Definition at line 129 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 129 of file G4EmExtraParameters.cc
References dRoverRangeMuHad, finalRangeMuHad, CLHEP::mm, PrintWarning(), v1, and v2.
Referenced by G4EmExtraParametersMessenger::SetNewValue(), and G4EmParameters::SetStepFunctionMuHad().
void G4EmExtraParameters::SetSubCutoff (G4bool val, const G4String & region = "")
Definition at line 214 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 214 of file G4EmExtraParameters.cc
References CheckRegion(), m_regnamesSubCut, m_subCuts, and r.
Referenced by G4EmExtraParametersMessenger::SetNewValue(), and G4EmParameters::SetSubCutoff().
const std::vector< G4String > & G4EmExtraParameters::TypesPAI () const
Definition at line 187 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 187 of file G4EmExtraParameters.cc
References m_typesPAI.
Referenced by G4EmParameters::TypesPAI().
const std::vector< G4String > & G4EmExtraParameters::TypesPhysics () const
Definition at line 209 of file G4EmExtraParameters.cc.
View newest version in sPHENIX GitHub at line 209 of file G4EmExtraParameters.cc
References m_typesPhys.
Referenced by G4EmParameters::TypesPhysics().
Member Data Documentation
G4bool G4EmExtraParameters::directionalSplitting private
Definition at line 135 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 135 of file G4EmExtraParameters.hh
Referenced by GetDirectionalSplitting(), Initialise(), and SetDirectionalSplitting().
G4double G4EmExtraParameters::directionalSplittingRadius private
Definition at line 143 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 143 of file G4EmExtraParameters.hh
Referenced by GetDirectionalSplittingRadius(), Initialise(), and SetDirectionalSplittingRadius().
G4ThreeVector G4EmExtraParameters::directionalSplittingTarget private
Definition at line 144 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 144 of file G4EmExtraParameters.hh
Referenced by GetDirectionalSplittingTarget(), Initialise(), and SetDirectionalSplittingTarget().
G4double G4EmExtraParameters::dRoverRange private
Definition at line 138 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 138 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForLoss(), GetStepFunctionP1(), Initialise(), and SetStepFunction().
G4double G4EmExtraParameters::dRoverRangeMuHad private
Definition at line 140 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 140 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForLoss(), GetStepFunctionMuHadP1(), Initialise(), and SetStepFunctionMuHad().
G4double G4EmExtraParameters::finalRange private
Definition at line 139 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 139 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForLoss(), GetStepFunctionP2(), Initialise(), and SetStepFunction().
G4double G4EmExtraParameters::finalRangeMuHad private
Definition at line 141 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 141 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForLoss(), GetStepFunctionMuHadP2(), Initialise(), and SetStepFunctionMuHad().
std::vector<G4double> G4EmExtraParameters::m_elimBiasedSec private
Definition at line 168 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 168 of file G4EmExtraParameters.hh
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
std::vector<G4double> G4EmExtraParameters::m_factBiasedSec private
Definition at line 167 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 167 of file G4EmExtraParameters.hh
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
std::vector<G4double> G4EmExtraParameters::m_factBiasedXS private
Definition at line 157 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 157 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForEM(), DefineRegParamForLoss(), and SetProcessBiasingFactor().
std::vector<G4double> G4EmExtraParameters::m_lengthForced private
Definition at line 162 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 162 of file G4EmExtraParameters.hh
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and Initialise().
std::vector<G4String> G4EmExtraParameters::m_particlesPAI private
Definition at line 146 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 146 of file G4EmExtraParameters.hh
Referenced by AddPAIModel(), and ParticlesPAI().
std::vector<G4String> G4EmExtraParameters::m_procBiasedSec private
Definition at line 165 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 165 of file G4EmExtraParameters.hh
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
std::vector<G4String> G4EmExtraParameters::m_procBiasedXS private
Definition at line 156 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 156 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForEM(), DefineRegParamForLoss(), and SetProcessBiasingFactor().
std::vector<G4String> G4EmExtraParameters::m_procForced private
Definition at line 160 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 160 of file G4EmExtraParameters.hh
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and Initialise().
std::vector<G4String> G4EmExtraParameters::m_regnamesBiasedSec private
Definition at line 166 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 166 of file G4EmExtraParameters.hh
Referenced by ActivateSecondaryBiasing(), DefineRegParamForEM(), and DefineRegParamForLoss().
std::vector<G4String> G4EmExtraParameters::m_regnamesForced private
Definition at line 161 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 161 of file G4EmExtraParameters.hh
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and Initialise().
std::vector<G4String> G4EmExtraParameters::m_regnamesPAI private
Definition at line 147 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 147 of file G4EmExtraParameters.hh
Referenced by AddPAIModel(), and RegionsPAI().
std::vector<G4String> G4EmExtraParameters::m_regnamesPhys private
Definition at line 150 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 150 of file G4EmExtraParameters.hh
Referenced by AddPhysics(), and RegionsPhysics().
std::vector<G4String> G4EmExtraParameters::m_regnamesSubCut private
Definition at line 153 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 153 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForLoss(), Initialise(), and SetSubCutoff().
std::vector<G4bool> G4EmExtraParameters::m_subCuts private
Definition at line 154 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 154 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForLoss(), Initialise(), and SetSubCutoff().
std::vector<G4String> G4EmExtraParameters::m_typesPAI private
Definition at line 148 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 148 of file G4EmExtraParameters.hh
Referenced by AddPAIModel(), and TypesPAI().
std::vector<G4String> G4EmExtraParameters::m_typesPhys private
Definition at line 151 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 151 of file G4EmExtraParameters.hh
Referenced by AddPhysics(), and TypesPhysics().
std::vector<G4bool> G4EmExtraParameters::m_weightBiasedXS private
Definition at line 158 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 158 of file G4EmExtraParameters.hh
Referenced by DefineRegParamForEM(), DefineRegParamForLoss(), and SetProcessBiasingFactor().
std::vector<G4bool> G4EmExtraParameters::m_weightForced private
Definition at line 163 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 163 of file G4EmExtraParameters.hh
Referenced by ActivateForcedInteraction(), DefineRegParamForEM(), DefineRegParamForLoss(), and Initialise().
G4bool G4EmExtraParameters::quantumEntanglement private
Definition at line 136 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 136 of file G4EmExtraParameters.hh
Referenced by Initialise(), QuantumEntanglement(), and SetQuantumEntanglement().
G4EmExtraParametersMessenger* G4EmExtraParameters::theMessenger private
Definition at line 133 of file G4EmExtraParameters.hh.
View newest version in sPHENIX GitHub at line 133 of file G4EmExtraParameters.hh
Referenced by G4EmExtraParameters(), and ~G4EmExtraParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmExtraParameters.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmExtraParameters.cc