ECCE @ EIC Software: GIDI_settings_flux Class Reference
GIDI_settings_flux Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh>
Public Member Functions
GIDI_settings_flux (std::string const &label, double temperature_MeV)
GIDI_settings_flux (char const *label, double temperature_MeV)
GIDI_settings_flux (GIDI_settings_flux const &flux)
GIDI_settings_flux & operator= (const GIDI_settings_flux &flux)
~GIDI_settings_flux ()
GIDI_settings_flux_order const * operator[] (int order) const
int getMaxOrder (void) const
int size (void) const
std::string getLabel () const
bool isLabel (std::string const &label) const
bool isLabel (char const *label) const
double getTemperature () const
void addFluxOrder (GIDI_settings_flux_order const &fluxOrder)
void print (bool outline=true, int valuesPerLine=10) const
Private Attributes
std::string mLabel
double mTemperature
std::vector
< GIDI_settings_flux_order > mFluxOrders
Detailed Description
Definition at line 122 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 122 of file GIDI_settings.hh
Constructor & Destructor Documentation
GIDI_settings_flux::GIDI_settings_flux (std::string const & label, double temperature_MeV)
Definition at line 98 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 98 of file GIDI_settings_flux.cc
References mLabel, and mTemperature.
GIDI_settings_flux::GIDI_settings_flux (char const * label, double temperature_MeV)
Definition at line 106 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 106 of file GIDI_settings_flux.cc
References mLabel, and mTemperature.
GIDI_settings_flux::GIDI_settings_flux (GIDI_settings_flux const & flux)
Definition at line 114 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 114 of file GIDI_settings_flux.cc
References addFluxOrder(), getLabel(), mFluxOrders, mLabel, and mTemperature.
GIDI_settings_flux::~GIDI_settings_flux ()
Definition at line 134 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 134 of file GIDI_settings_flux.cc
Member Function Documentation
void GIDI_settings_flux::addFluxOrder (GIDI_settings_flux_order const & fluxOrder)
Definition at line 147 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 147 of file GIDI_settings_flux.cc
References GIDI_settings_flux_order::getOrder(), and mFluxOrders.
Referenced by GIDI_settings_flux(), and operator=().
std::string GIDI_settings_flux::getLabel () const inline
Definition at line 140 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 140 of file GIDI_settings.hh
References mLabel.
Referenced by GIDI_settings_flux(), and operator=().
int GIDI_settings_flux::getMaxOrder (void) const inline
Definition at line 137 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 137 of file GIDI_settings.hh
References mFluxOrders.
double GIDI_settings_flux::getTemperature () const inline
Definition at line 143 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 143 of file GIDI_settings.hh
References mTemperature.
Referenced by GIDI_settings_particle::addFlux(), and GIDI_settings_processedFlux::getTemperature().
bool GIDI_settings_flux::isLabel (std::string const & label) const inline
Definition at line 141 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 141 of file GIDI_settings.hh
References mLabel.
bool GIDI_settings_flux::isLabel (char const * label) const inline
Definition at line 142 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 142 of file GIDI_settings.hh
References mLabel.
GIDI_settings_flux & GIDI_settings_flux::operator= (const GIDI_settings_flux & flux)
Definition at line 123 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 123 of file GIDI_settings_flux.cc
References addFluxOrder(), getLabel(), mFluxOrders, mLabel, and mTemperature.
GIDI_settings_flux_order const * GIDI_settings_flux::operator[] (int order) const
Definition at line 140 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 140 of file GIDI_settings_flux.cc
References mFluxOrders.
void GIDI_settings_flux::print (bool outline = true, int valuesPerLine = 10) const
Definition at line 159 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 159 of file GIDI_settings_flux.cc
References mFluxOrders, mLabel, and size().
int GIDI_settings_flux::size (void) const inline
Definition at line 138 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 138 of file GIDI_settings.hh
References mFluxOrders.
Referenced by GIDI_settings_processedFlux::GIDI_settings_processedFlux(), GIDI_settings_processedFlux::operator=(), and print().
Member Data Documentation
std::vector<GIDI_settings_flux_order> GIDI_settings_flux::mFluxOrders private
List of fluxes for each Legendre order, l, sorted by Legendre order starting with l = 0.
Definition at line 127 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 127 of file GIDI_settings.hh
Referenced by addFluxOrder(), getMaxOrder(), GIDI_settings_flux(), operator=(), operator[](), print(), and size().
std::string GIDI_settings_flux::mLabel private
Label for the flux.
Definition at line 125 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 125 of file GIDI_settings.hh
Referenced by getLabel(), GIDI_settings_flux(), isLabel(), operator=(), and print().
double GIDI_settings_flux::mTemperature private
Definition at line 126 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 126 of file GIDI_settings.hh
Referenced by getTemperature(), GIDI_settings_flux(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/GIDI_settings_flux.cc