ECCE @ EIC Software: G4KDMap Class Reference
G4KDMap Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDMap.hh>
Public Member Functions
G4KDMap (size_t dimensions)
void Insert (G4KDNode_Base *pos)
void Sort ()
G4KDNode_Base * PopOutMiddle (size_t dimension)
size_t GetDimension ()
size_t GetSize ()
Private Attributes
bool fIsSorted
std::vector< __1DSortOut > fSortOut
std::map< G4KDNode_Base
*, std::vector< std::deque
< G4KDNode_Base * >::iterator > > fMap
Detailed Description
Definition at line 89 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 89 of file G4KDMap.hh
Constructor & Destructor Documentation
G4KDMap::G4KDMap (size_t dimensions) inline
Definition at line 92 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 92 of file G4KDMap.hh
References fIsSorted.
Member Function Documentation
size_t G4KDMap::GetDimension () inline
Definition at line 105 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 105 of file G4KDMap.hh
References fSortOut.
size_t G4KDMap::GetSize () inline
Definition at line 110 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 110 of file G4KDMap.hh
References fMap.
Referenced by G4KDTree::Build().
void G4KDMap::Insert (G4KDNode_Base * pos)
Definition at line 90 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 90 of file G4KDMap.cc
References fIsSorted, fMap, fSortOut, G4cout, G4endl, and pos().
Referenced by G4KDTree::__InsertMap().
G4KDNode_Base * G4KDMap::PopOutMiddle (size_t dimension)
Definition at line 137 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 137 of file G4KDMap.cc
References fIsSorted, fMap, fSortOut, G4cout, G4endl, G4KDNode_Base::GetAxis(), and Sort().
Referenced by G4KDTree::Build().
void G4KDMap::Sort ()
Definition at line 196 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 196 of file G4KDMap.cc
References fIsSorted, and fSortOut.
Referenced by PopOutMiddle().
Member Data Documentation
bool G4KDMap::fIsSorted private
Definition at line 116 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 116 of file G4KDMap.hh
Referenced by G4KDMap(), Insert(), PopOutMiddle(), and Sort().
std::map<G4KDNode_Base*, std::vector<std::deque<G4KDNode_Base*>::iterator> > G4KDMap::fMap private
Definition at line 118 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 118 of file G4KDMap.hh
Referenced by GetSize(), Insert(), and PopOutMiddle().
std::vector<__1DSortOut> G4KDMap::fSortOut private
Definition at line 117 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 117 of file G4KDMap.hh
Referenced by GetDimension(), Insert(), PopOutMiddle(), and Sort().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDMap.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4KDMap.cc