ECCE @ EIC Software: G4ChipsKaonMinusInelasticXS Class Reference
G4ChipsKaonMinusInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonMinusInelasticXS.hh>
Public Member Functions
G4ChipsKaonMinusInelasticXS ()
~G4ChipsKaonMinusInelasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
virtual G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
G4double CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum)
G4double CrossSectionLin (G4int targZ, G4int targN, G4double P)
G4double CrossSectionLog (G4int targZ, G4int targN, G4double lP)
G4double CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP)
G4double EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double *Y)
Private Attributes
G4double * lastLEN
G4double * lastHEN
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
std::vector< G4double * > * LEN
std::vector< G4double * > * HEN
G4int j
std::vector< G4int > colN
std::vector< G4int > colZ
std::vector< G4double > colP
std::vector< G4double > colTH
std::vector< G4double > colCS
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 45 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ChipsKaonMinusInelasticXS.hh
Constructor & Destructor Documentation
G4ChipsKaonMinusInelasticXS::G4ChipsKaonMinusInelasticXS ()
Definition at line 66 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ChipsKaonMinusInelasticXS.cc
References HEN, lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, and LEN.
G4ChipsKaonMinusInelasticXS::~G4ChipsKaonMinusInelasticXS ()
Definition at line 80 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ChipsKaonMinusInelasticXS.cc
References HEN, and LEN.
Member Function Documentation
G4double G4ChipsKaonMinusInelasticXS::CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum) private
Definition at line 193 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 193 of file G4ChipsKaonMinusInelasticXS.cc
References CrossSectionFormula(), CrossSectionLin(), CrossSectionLog(), EquLinearFit(), G4cerr, G4endl, HEN, k, lastHEN, lastLEN, lastTH, LEN, n, nH, nL, and P.
Referenced by GetChipsCrossSection().
void G4ChipsKaonMinusInelasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 92 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsKaonMinusInelasticXS.cc
G4double G4ChipsKaonMinusInelasticXS::CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP) private
Definition at line 272 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 272 of file G4ChipsKaonMinusInelasticXS.cc
References a, c, d, Acts::Test::dX, f, G4cerr, G4endl, Acts::UnitConstants::h, P, G4InuclParticleNames::sp, Acts::UnitConstants::u, and v.
Referenced by CalculateCrossSection(), CrossSectionLin(), and CrossSectionLog().
G4double G4ChipsKaonMinusInelasticXS::CrossSectionLin (G4int targZ, G4int targN, G4double P) private
Definition at line 259 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 259 of file G4ChipsKaonMinusInelasticXS.cc
References CrossSectionFormula().
Referenced by CalculateCrossSection().
G4double G4ChipsKaonMinusInelasticXS::CrossSectionLog (G4int targZ, G4int targN, G4double lP) private
Definition at line 266 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 266 of file G4ChipsKaonMinusInelasticXS.cc
References CrossSectionFormula(), and P.
Referenced by CalculateCrossSection().
static const char* G4ChipsKaonMinusInelasticXS::Default_Name () inline static
Definition at line 54 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by LBE::ConstructHad(), GammaRayTelHadronPhysics::ConstructProcess(), G4ChipsComponentXS::G4ChipsComponentXS(), and G4ChipsKaonZeroInelasticXS::G4ChipsKaonZeroInelasticXS().
G4double G4ChipsKaonMinusInelasticXS::EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double * Y) private
Definition at line 326 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 326 of file G4ChipsKaonMinusInelasticXS.cc
References d, G4cerr, and G4endl.
Referenced by CalculateCrossSection().
G4double G4ChipsKaonMinusInelasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg) virtual
!The slave functions must provide cross-sections in millibarns (mb) !! (not in IU)
Definition at line 121 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ChipsKaonMinusInelasticXS.cc
References CalculateCrossSection(), colCS, colN, colP, colTH, colZ, in, j, lastCS, lastI, lastN, lastP, lastTH, lastZ, and millibarn.
Referenced by G4ChipsKaonZeroInelasticXS::GetChipsCrossSection(), and GetIsoCrossSection().
G4double G4ChipsKaonMinusInelasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 110 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ChipsKaonMinusInelasticXS.cc
References GetChipsCrossSection(), and G4DynamicParticle::GetTotalMomentum().
G4bool G4ChipsKaonMinusInelasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 100 of file G4ChipsKaonMinusInelasticXS.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ChipsKaonMinusInelasticXS.cc
Member Data Documentation
std::vector<G4double> G4ChipsKaonMinusInelasticXS::colCS private
Definition at line 97 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsKaonMinusInelasticXS::colN private
Definition at line 93 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsKaonMinusInelasticXS::colP private
Definition at line 95 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsKaonMinusInelasticXS::colTH private
Definition at line 96 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsKaonMinusInelasticXS::colZ private
Definition at line 94 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double*>* G4ChipsKaonMinusInelasticXS::HEN private
Definition at line 90 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsKaonMinusInelasticXS(), and ~G4ChipsKaonMinusInelasticXS().
G4int G4ChipsKaonMinusInelasticXS::j private
Definition at line 92 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by GetChipsCrossSection().
G4double G4ChipsKaonMinusInelasticXS::lastCS private
Definition at line 87 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by G4ChipsKaonMinusInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsKaonMinusInelasticXS::lastHEN private
Definition at line 82 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsKaonMinusInelasticXS().
G4int G4ChipsKaonMinusInelasticXS::lastI private
Definition at line 88 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by G4ChipsKaonMinusInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsKaonMinusInelasticXS::lastLEN private
Definition at line 81 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsKaonMinusInelasticXS().
G4int G4ChipsKaonMinusInelasticXS::lastN private
Definition at line 83 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by G4ChipsKaonMinusInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsKaonMinusInelasticXS::lastP private
Definition at line 85 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by G4ChipsKaonMinusInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsKaonMinusInelasticXS::lastTH private
Definition at line 86 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsKaonMinusInelasticXS(), and GetChipsCrossSection().
G4int G4ChipsKaonMinusInelasticXS::lastZ private
Definition at line 84 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by G4ChipsKaonMinusInelasticXS(), and GetChipsCrossSection().
std::vector<G4double*>* G4ChipsKaonMinusInelasticXS::LEN private
Definition at line 89 of file G4ChipsKaonMinusInelasticXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChipsKaonMinusInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsKaonMinusInelasticXS(), and ~G4ChipsKaonMinusInelasticXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonMinusInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsKaonMinusInelasticXS.cc