ECCE @ EIC Software: WLSMaterials Class Reference
WLSMaterials Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSMaterials.hh>
Public Member Functions
virtual ~WLSMaterials ()
G4Material * GetMaterial (const G4String)
Static Public Member Functions
static WLSMaterials * GetInstance ()
Private Member Functions
WLSMaterials ()
void CreateMaterials ()
Private Attributes
G4NistManager * fNistMan
G4Material * fAir
G4Material * fPMMA
G4Material * fPethylene
G4Material * fFPethylene
G4Material * fPolystyrene
G4Material * fSilicone
G4Material * fCoating
Static Private Attributes
static WLSMaterials * fInstance = 0
Detailed Description
Definition at line 41 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 41 of file WLSMaterials.hh
Constructor & Destructor Documentation
WLSMaterials::~WLSMaterials () virtual
Definition at line 50 of file WLSMaterials.cc.
View newest version in sPHENIX GitHub at line 50 of file WLSMaterials.cc
References fFPethylene, fPethylene, fPMMA, fPolystyrene, and fSilicone.
WLSMaterials::WLSMaterials () private
Definition at line 39 of file WLSMaterials.cc.
View newest version in sPHENIX GitHub at line 39 of file WLSMaterials.cc
References CreateMaterials(), fNistMan, G4NistManager::Instance(), and G4NistManager::SetVerbose().
Referenced by GetInstance().
Member Function Documentation
void WLSMaterials::CreateMaterials () private
Definition at line 89 of file WLSMaterials.cc.
View newest version in sPHENIX GitHub at line 89 of file WLSMaterials.cc
References G4MaterialPropertiesTable::AddConstProperty(), G4Material::AddMaterial(), G4MaterialPropertiesTable::AddProperty(), cm, cm3, elements, eV, fAir, fCoating, fFPethylene, G4NistManager::FindOrBuildMaterial(), fNistMan, fPethylene, fPMMA, fPolystyrene, fSilicone, Acts::UnitConstants::g, G4Material::GetIonisation(), keV, m, MeV, mm, ns, perCent, G4IonisParamMat::SetBirksConstant(), and G4Material::SetMaterialPropertiesTable().
Referenced by WLSMaterials().
WLSMaterials * WLSMaterials::GetInstance (void) static
Definition at line 61 of file WLSMaterials.cc.
View newest version in sPHENIX GitHub at line 61 of file WLSMaterials.cc
References fInstance, and WLSMaterials().
Referenced by WLSDetectorConstruction::Construct().
G4Material * WLSMaterials::GetMaterial (const G4String material)
Definition at line 72 of file WLSMaterials.cc.
View newest version in sPHENIX GitHub at line 72 of file WLSMaterials.cc
References FatalException, G4NistManager::FindOrBuildMaterial(), fNistMan, G4Exception(), G4Material::GetMaterial(), and mat.
Member Data Documentation
G4Material* WLSMaterials::fAir private
Definition at line 63 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 63 of file WLSMaterials.hh
Referenced by CreateMaterials().
G4Material* WLSMaterials::fCoating private
Definition at line 70 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 70 of file WLSMaterials.hh
Referenced by CreateMaterials().
G4Material* WLSMaterials::fFPethylene private
Definition at line 67 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 67 of file WLSMaterials.hh
Referenced by CreateMaterials(), and ~WLSMaterials().
WLSMaterials * WLSMaterials::fInstance = 0 static private
Definition at line 59 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 59 of file WLSMaterials.hh
Referenced by GetInstance().
G4NistManager* WLSMaterials::fNistMan private
Definition at line 61 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 61 of file WLSMaterials.hh
Referenced by CreateMaterials(), GetMaterial(), and WLSMaterials().
G4Material* WLSMaterials::fPethylene private
Definition at line 66 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 66 of file WLSMaterials.hh
Referenced by CreateMaterials(), and ~WLSMaterials().
G4Material* WLSMaterials::fPMMA private
Definition at line 65 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 65 of file WLSMaterials.hh
Referenced by CreateMaterials(), and ~WLSMaterials().
G4Material* WLSMaterials::fPolystyrene private
Definition at line 68 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 68 of file WLSMaterials.hh
Referenced by CreateMaterials(), and ~WLSMaterials().
G4Material* WLSMaterials::fSilicone private
Definition at line 69 of file WLSMaterials.hh.
View newest version in sPHENIX GitHub at line 69 of file WLSMaterials.hh
Referenced by CreateMaterials(), and ~WLSMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSMaterials.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSMaterials.cc