ECCE @ EIC Software: G4TessellatedGeometryAlgorithms Class Reference
G4TessellatedGeometryAlgorithms Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TessellatedGeometryAlgorithms.hh>
Static Public Member Functions
static G4bool IntersectLineAndTriangle2D (const G4TwoVector &p, const G4TwoVector &v, const G4TwoVector &p0, const G4TwoVector &e0, const G4TwoVector &e1, G4TwoVector location[2])
static G4int IntersectLineAndLineSegment2D (const G4TwoVector &p0, const G4TwoVector &d0, const G4TwoVector &p1, const G4TwoVector &d1, G4TwoVector location[2])
static G4double cross (const G4TwoVector &v1, const G4TwoVector &v2)
Detailed Description
Definition at line 69 of file G4TessellatedGeometryAlgorithms.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TessellatedGeometryAlgorithms.hh
Member Function Documentation
G4double G4TessellatedGeometryAlgorithms::cross (const G4TwoVector & v1, const G4TwoVector & v2) static
Definition at line 236 of file G4TessellatedGeometryAlgorithms.cc.
View newest version in sPHENIX GitHub at line 236 of file G4TessellatedGeometryAlgorithms.cc
References CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by IntersectLineAndLineSegment2D().
G4int G4TessellatedGeometryAlgorithms::IntersectLineAndLineSegment2D (const G4TwoVector & p0, const G4TwoVector & d0, const G4TwoVector & p1, const G4TwoVector & d1, G4TwoVector location[2]) static
Definition at line 163 of file G4TessellatedGeometryAlgorithms.cc.
View newest version in sPHENIX GitHub at line 163 of file G4TessellatedGeometryAlgorithms.cc
References cross(), DBL_EPSILON, CLHEP::Hep2Vector::dot(), e, CLHEP::Hep2Vector::mag2(), G4InuclParticleNames::s0, s1, smax, and t.
Referenced by IntersectLineAndTriangle2D().
G4bool G4TessellatedGeometryAlgorithms::IntersectLineAndTriangle2D (const G4TwoVector & p, const G4TwoVector & v, const G4TwoVector & p0, const G4TwoVector & e0, const G4TwoVector & e1, G4TwoVector location[2]) static
Definition at line 55 of file G4TessellatedGeometryAlgorithms.cc.
View newest version in sPHENIX GitHub at line 55 of file G4TessellatedGeometryAlgorithms.cc
References IntersectLineAndLineSegment2D().
Referenced by G4TriangularFacet::Intersect().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TessellatedGeometryAlgorithms.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4TessellatedGeometryAlgorithms.cc