ECCE @ EIC Software: G4HadronicInteractionRegistry Class Reference
G4HadronicInteractionRegistry Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4HadronicInteractionRegistry.hh>
Public Member Functions
~G4HadronicInteractionRegistry ()
void RegisterMe (G4HadronicInteraction *aModel)
void RemoveMe (G4HadronicInteraction *aModel)
void Clean ()
void InitialiseModels ()
G4HadronicInteraction * FindModel (const G4String &name)
std::vector
< G4HadronicInteraction * > FindAllModels (const G4String &name)
Static Public Member Functions
static
G4HadronicInteractionRegistry * Instance ()
Private Member Functions
G4HadronicInteractionRegistry ()
Private Attributes
std::vector
< G4HadronicInteraction * > allModels
Static Private Attributes
static G4ThreadLocal
G4HadronicInteractionRegistry * instance = nullptr
Friends
class G4ThreadLocalSingleton< G4HadronicInteractionRegistry >
Detailed Description
Definition at line 43 of file G4HadronicInteractionRegistry.hh.
View newest version in sPHENIX GitHub at line 43 of file G4HadronicInteractionRegistry.hh
Constructor & Destructor Documentation
G4HadronicInteractionRegistry::~G4HadronicInteractionRegistry ()
Definition at line 48 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 48 of file G4HadronicInteractionRegistry.cc
References Clean().
G4HadronicInteractionRegistry::G4HadronicInteractionRegistry () private
Definition at line 45 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 45 of file G4HadronicInteractionRegistry.cc
Member Function Documentation
void G4HadronicInteractionRegistry::Clean ()
Definition at line 53 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 53 of file G4HadronicInteractionRegistry.cc
References allModels, BTOF::length, and min.
Referenced by ~G4HadronicInteractionRegistry().
std::vector< G4HadronicInteraction * > G4HadronicInteractionRegistry::FindAllModels (const G4String & name)
Definition at line 124 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 124 of file G4HadronicInteractionRegistry.cc
References allModels.
Referenced by G4INCLXXInterfaceStore::UseAblaDeExcitation().
G4HadronicInteraction * G4HadronicInteractionRegistry::FindModel (const G4String & name)
Definition at line 111 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 111 of file G4HadronicInteractionRegistry.cc
References allModels.
Referenced by IonPhysics::ConstructProcess(), G4IonPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4BinaryCascade::G4BinaryCascade(), G4BinaryLightIonReaction::G4BinaryLightIonReaction(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4INCLXXInterface::G4INCLXXInterface(), G4INCLXXNeutronBuilder::G4INCLXXNeutronBuilder(), G4INCLXXProtonBuilder::G4INCLXXProtonBuilder(), G4LENDInelastic::G4LENDInelastic(), G4LowEGammaNuclearModel::G4LowEGammaNuclearModel(), G4MuMinusCapturePrecompound::G4MuMinusCapturePrecompound(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4PreCompoundDeexcitation::G4PreCompoundDeexcitation(), and G4INCLXXInterfaceStore::UseAblaDeExcitation().
void G4HadronicInteractionRegistry::InitialiseModels ()
Definition at line 77 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 77 of file G4HadronicInteractionRegistry.cc
References allModels.
Referenced by G4HadronicProcessStore::PrintInfo().
G4HadronicInteractionRegistry * G4HadronicInteractionRegistry::Instance (void) static
Definition at line 36 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 36 of file G4HadronicInteractionRegistry.cc
References instance, and G4ThreadLocalSingleton< T >::Instance().
Referenced by IonPhysics::ConstructProcess(), G4IonPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4BinaryCascade::G4BinaryCascade(), G4BinaryLightIonReaction::G4BinaryLightIonReaction(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicInteraction::G4HadronicInteraction(), G4INCLXXInterface::G4INCLXXInterface(), G4INCLXXNeutronBuilder::G4INCLXXNeutronBuilder(), G4INCLXXProtonBuilder::G4INCLXXProtonBuilder(), G4LENDInelastic::G4LENDInelastic(), G4LowEGammaNuclearModel::G4LowEGammaNuclearModel(), G4MuMinusCapturePrecompound::G4MuMinusCapturePrecompound(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4PreCompoundDeexcitation::G4PreCompoundDeexcitation(), G4HadronicProcessStore::PrintInfo(), and G4INCLXXInterfaceStore::UseAblaDeExcitation().
void G4HadronicInteractionRegistry::RegisterMe (G4HadronicInteraction * aModel)
Definition at line 85 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 85 of file G4HadronicInteractionRegistry.cc
References allModels.
Referenced by G4HadronicInteraction::G4HadronicInteraction().
void G4HadronicInteractionRegistry::RemoveMe (G4HadronicInteraction * aModel)
Definition at line 97 of file G4HadronicInteractionRegistry.cc.
View newest version in sPHENIX GitHub at line 97 of file G4HadronicInteractionRegistry.cc
References allModels.
Referenced by G4HadronicInteraction::~G4HadronicInteraction().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4HadronicInteractionRegistry > friend
Definition at line 45 of file G4HadronicInteractionRegistry.hh.
View newest version in sPHENIX GitHub at line 45 of file G4HadronicInteractionRegistry.hh
Member Data Documentation
std::vector<G4HadronicInteraction*> G4HadronicInteractionRegistry::allModels private
Definition at line 78 of file G4HadronicInteractionRegistry.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronicInteractionRegistry.hh
Referenced by Clean(), FindAllModels(), FindModel(), InitialiseModels(), RegisterMe(), and RemoveMe().
G4ThreadLocal G4HadronicInteractionRegistry * G4HadronicInteractionRegistry::instance = nullptr static private
Definition at line 76 of file G4HadronicInteractionRegistry.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadronicInteractionRegistry.hh
Referenced by Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4HadronicInteractionRegistry.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4HadronicInteractionRegistry.cc