ECCE @ EIC Software: G4IonsSihverCrossSection Class Reference
G4IonsSihverCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4IonsSihverCrossSection.hh>
Public Member Functions
G4IonsSihverCrossSection ()
virtual ~G4IonsSihverCrossSection ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *aDP, G4int Z, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
const G4double square_r0
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 46 of file G4IonsSihverCrossSection.hh.
View newest version in sPHENIX GitHub at line 46 of file G4IonsSihverCrossSection.hh
Constructor & Destructor Documentation
G4IonsSihverCrossSection::G4IonsSihverCrossSection ()
Definition at line 40 of file G4IonsSihverCrossSection.cc.
View newest version in sPHENIX GitHub at line 40 of file G4IonsSihverCrossSection.cc
G4IonsSihverCrossSection::~G4IonsSihverCrossSection () virtual
Definition at line 44 of file G4IonsSihverCrossSection.cc.
View newest version in sPHENIX GitHub at line 44 of file G4IonsSihverCrossSection.cc
Member Function Documentation
void G4IonsSihverCrossSection::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 48 of file G4IonsSihverCrossSection.cc.
View newest version in sPHENIX GitHub at line 48 of file G4IonsSihverCrossSection.cc
G4double G4IonsSihverCrossSection::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 67 of file G4IonsSihverCrossSection.cc.
View newest version in sPHENIX GitHub at line 67 of file G4IonsSihverCrossSection.cc
References G4lrint(), G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), G4Pow::GetInstance(), G4NistManager::Instance(), pi, square_r0, and G4Pow::Z13().
G4bool G4IonsSihverCrossSection::IsElementApplicable (const G4DynamicParticle * aDP, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 57 of file G4IonsSihverCrossSection.cc.
View newest version in sPHENIX GitHub at line 57 of file G4IonsSihverCrossSection.cc
References G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and MeV.
Member Data Documentation
const G4double G4IonsSihverCrossSection::square_r0 private
Definition at line 65 of file G4IonsSihverCrossSection.hh.
View newest version in sPHENIX GitHub at line 65 of file G4IonsSihverCrossSection.hh
Referenced by GetElementCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4IonsSihverCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4IonsSihverCrossSection.cc