ECCE @ EIC Software: G4VisCommandGeometryList Class Reference
G4VisCommandGeometryList Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometry.hh>
Public Member Functions
G4VisCommandGeometryList ()
virtual ~G4VisCommandGeometryList ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommandGeometry
virtual ~G4VVisCommandGeometry ()
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4VisCommandGeometryList (const G4VisCommandGeometryList &)
G4VisCommandGeometryList & operator= (const G4VisCommandGeometryList &)
Private Attributes
G4UIcmdWithAString * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Types inherited from G4VVisCommandGeometry
typedef std::map
< G4LogicalVolume *, const
G4VisAttributes * >
::const_iterator VisAttsMapIterator
Protected Member Functions inherited from G4VVisCommand
void SetViewParameters (G4VViewer *viewer, const G4ViewParameters &viewParams)
void RefreshIfRequired (G4VViewer *viewer)
void InterpolateViews (G4VViewer *currentViewer, std::vector< G4ViewParameters > viewVector, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
void InterpolateToNewView (G4VViewer *currentViewer, const G4ViewParameters &oldVP, const G4ViewParameters &newVP, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
const G4String & ConvertToColourGuidance ()
void ConvertToColour (G4Colour &colour, const G4String &redOrString, G4double green, G4double blue, G4double opacity)
G4bool ProvideValueOfUnit (const G4String &where, const G4String &unit, const G4String &category, G4double &value)
void CheckSceneAndNotifyHandlers (G4Scene *=nullptr)
void G4VisCommandsSceneAddUnsuccessful (G4VisManager::Verbosity verbosity)
void CopyGuidanceFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd, G4int startLine=0)
void CopyParametersFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd)
void DrawExtent (const G4VisExtent &)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommandGeometry
static std::map
< G4LogicalVolume *, const
G4VisAttributes * > fVisAttsMap
Detailed Description
Definition at line 51 of file G4VisCommandsGeometry.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VisCommandsGeometry.hh
Constructor & Destructor Documentation
G4VisCommandGeometryList::G4VisCommandGeometryList ()
Definition at line 48 of file G4VisCommandsGeometry.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VisCommandsGeometry.cc
References fpCommand.
G4VisCommandGeometryList::~G4VisCommandGeometryList () virtual
Definition at line 58 of file G4VisCommandsGeometry.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VisCommandsGeometry.cc
References fpCommand.
G4VisCommandGeometryList::G4VisCommandGeometryList (const G4VisCommandGeometryList &) private
Member Function Documentation
G4String G4VisCommandGeometryList::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 63 of file G4VisCommandsGeometry.cc.
View newest version in sPHENIX GitHub at line 63 of file G4VisCommandsGeometry.cc
G4VisCommandGeometryList& G4VisCommandGeometryList::operator= (const G4VisCommandGeometryList &) private
void G4VisCommandGeometryList::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 68 of file G4VisCommandsGeometry.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VisCommandsGeometry.cc
References G4VisManager::errors, G4VVisCommand::fpVisManager, G4cerr, G4cout, G4endl, G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), G4VisManager::GetVerbosity(), and G4LogicalVolume::GetVisAttributes().
Member Data Documentation
G4UIcmdWithAString* G4VisCommandGeometryList::fpCommand private
Definition at line 60 of file G4VisCommandsGeometry.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VisCommandsGeometry.hh
Referenced by G4VisCommandGeometryList(), and ~G4VisCommandGeometryList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometry.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsGeometry.cc