ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/hijing1_383/Main_HIJING.f File Reference
Main_HIJING.f File Reference
Functions/Subroutines
program test
Function/Subroutine Documentation
program test ()
Definition at line 1 of file Main_HIJING.f.
View newest version in sPHENIX GitHub at line 1 of file Main_HIJING.f
References common(), HiMain1::eatt(), efrm, hijing(), hijset(), HiParnt::hint1(), HiParnt::hipr1(), iap, iat, HiParnt::ihnt2(), HiParnt::ihpr2(), izp, izt, HiMain1::jatt(), HiMain2::katt(), max, HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HiMain1::np(), RanSeed::nseed(), HiMain1::nt(), HiMain2::patt(), PHTimer::stop(), and ulmass().
Referenced by BOOST_DATA_TEST_CASE(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), Acts::BoundaryCheck::computeEuclideanClosestPointOnRectangle(), G4PolyPhiFace::Diagnose(), G4TwistTubsSide::DistanceToSurface(), G4SPSEneDistribution::ExpInterpolation(), G4PixeShellDataSet::FullFileName(), G4RPGInelastic::GetNormalizationConstant(), G4ITReactionChange::Initialize(), G4GenericTrap::InsidePolygone(), nlohmann::basic_json::patch(), G4DNAPTBElasticModel::ReadDiffCSFile(), G4DNAPTBIonisationModel::ReadDiffCSFile(), G4ReduciblePolygon::RemoveRedundantVertices(), G4ParticleHPVector::Sample(), G4PenelopeAnnihilationModel::SampleSecondaries(), PHMicromegasTpcTrackMatching::set_test_windows_printout(), PHSiliconTpcTrackMatching::set_test_windows_printout(), G4LBLVtxDetector::SetActiveVolumes(), and Acts::CylinderVolumeBuilder::trackingVolume().