ECCE @ EIC Software: G4RadioactiveDecay Class Reference
G4RadioactiveDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactiveDecay.hh>
Public Member Functions
G4RadioactiveDecay (const G4String &processName="RadioactiveDecay")
~G4RadioactiveDecay ()
virtual void ProcessDescription (std::ostream &outFile) const
G4bool IsApplicable (const G4ParticleDefinition &)
G4DecayTable * GetDecayTable (const G4ParticleDefinition *)
void SelectAVolume (const G4String aVolume)
void DeselectAVolume (const G4String aVolume)
void SelectAllVolumes ()
void DeselectAllVolumes ()
void SetDecayBias (G4String filename)
void SetHLThreshold (G4double hl)
void SetICM (G4bool icm)
void SetARM (G4bool arm)
void SetSourceTimeProfile (G4String filename)
G4bool IsRateTableReady (const G4ParticleDefinition &)
void CalculateChainsFromParent (const G4ParticleDefinition &)
void GetChainsFromParent (const G4ParticleDefinition &)
void SetDecayRate (G4int, G4int, G4double, G4int, std::vector< G4double >, std::vector< G4double >)
std::vector
< G4RadioactivityTable * > GetTheRadioactivityTables ()
G4DecayTable * LoadDecayTable (const G4ParticleDefinition &theParentNucleus)
void AddUserDecayDataFile (G4int Z, G4int A, G4String filename)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetNucleusLimits (G4NucleusLimits theNucleusLimits1)
G4NucleusLimits GetNucleusLimits () const
void SetAnalogueMonteCarlo (G4bool r)
void SetFBeta (G4bool r)
G4bool IsAnalogueMonteCarlo ()
void SetBRBias (G4bool r)
void SetSplitNuclei (G4int r)
G4int GetSplitNuclei ()
void SetDecayDirection (const G4ThreeVector &theDir)
const G4ThreeVector & GetDecayDirection () const
void SetDecayHalfAngle (G4double halfAngle=0.*CLHEP::deg)
G4double GetDecayHalfAngle () const
void SetDecayCollimation (const G4ThreeVector &theDir, G4double halfAngle=0.*CLHEP::deg)
void BuildPhysicsTable (const G4ParticleDefinition &)
G4VParticleChange * DecayIt (const G4Track &theTrack, const G4Step &theStep)
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4DecayProducts * DoDecay (const G4ParticleDefinition &theParticleDef)
void CollimateDecay (G4DecayProducts *products)
void CollimateDecayProduct (G4DynamicParticle *product)
G4ThreeVector ChooseCollimationDirection () const
G4double GetMeanFreePath (const G4Track &theTrack, G4double previousStepSize, G4ForceCondition *condition)
G4double GetMeanLifeTime (const G4Track &theTrack, G4ForceCondition *condition)
G4double ConvolveSourceTimeProfile (const G4double, const G4double)
G4double GetDecayTime ()
G4int GetDecayTimeBin (const G4double aDecayTime)
void AddDeexcitationSpectrumForBiasMode (G4ParticleDefinition *apartDef, G4double weight, G4double currenTime, std::vector< double > &weights_v, std::vector< double > &times_v, std::vector< G4DynamicParticle * > &secondaries_v)
Private Member Functions
void StreamInfo (std::ostream &os, const G4String &endline)
G4RadioactiveDecay (const G4RadioactiveDecay &right)
G4RadioactiveDecay & operator= (const G4RadioactiveDecay &right)
G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)
G4VParticleChange * AtRestDoIt (const G4Track &theTrack, const G4Step &theStep)
G4VParticleChange * PostStepDoIt (const G4Track &theTrack, const G4Step &theStep)
Private Attributes
G4RadioactiveDecaymessenger * theRadioactiveDecaymessenger
G4PhotonEvaporation * photonEvaporation
G4NucleusLimits theNucleusLimits
G4bool isInitialised
G4bool AnalogueMC
G4bool BRBias
G4bool FBeta
G4int NSplit
G4double halflifethreshold
G4bool applyICM
G4bool applyARM
G4ThreeVector forceDecayDirection
G4double forceDecayHalfAngle
G4int NSourceBin
G4double SBin [100]
G4double SProfile [100]
G4int NDecayBin
G4double DBin [100]
G4double DProfile [100]
std::vector< G4String > ValidVolumes
bool isAllVolumesMode
G4RadioactiveDecayRatesToDaughter ratesToDaughter
G4RadioactiveDecayRates theDecayRateVector
G4RadioactiveDecayChainsFromParent chainsFromParent
G4RadioactiveDecayParentChainTable theParentChainTable
std::vector
< G4RadioactivityTable * > theRadioactivityTables
G4int decayWindows [100]
G4String dirPath
std::map< G4int, G4String > theUserRadioactiveDataFiles
G4RadioactiveDecayMode theRadDecayMode
DecayTableMap * dkmap
G4double fRemainderLifeTime
G4int verboseLevel
G4ParticleChangeForRadDecay fParticleChangeForRadDecay
Static Private Attributes
static const G4ThreeVector origin
static const G4double levelTolerance = 10.0*eV
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 83 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RadioactiveDecay.hh
Constructor & Destructor Documentation
G4RadioactiveDecay::G4RadioactiveDecay (const G4String & processName = "RadioactiveDecay")
Definition at line 168 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 168 of file G4RadioactiveDecay.cc
References AnalogueMC, applyARM, applyICM, BRBias, DBin, decayWindows, dirPath, dkmap, DProfile, false, FatalException, FBeta, fParticleChangeForRadDecay, fRadioactiveDecay, G4cout, G4endl, G4Exception(), GetVerboseLevel(), halflifethreshold, G4HadronicProcessStore::Instance(), isAllVolumesMode, nanosecond, NDecayBin, NSourceBin, NSplit, photonEvaporation, G4VProcess::pParticleChange, G4PhotonEvaporation::RDMForced(), G4HadronicProcessStore::RegisterExtraProcess(), SBin, SelectAllVolumes(), G4PhotonEvaporation::SetICM(), G4VProcess::SetProcessSubType(), SProfile, theRadioactiveDecaymessenger, theRadioactivityTables, theUserRadioactiveDataFiles, and true.
G4RadioactiveDecay::~G4RadioactiveDecay ()
Definition at line 261 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 261 of file G4RadioactiveDecay.cc
References dkmap, photonEvaporation, and theRadioactiveDecaymessenger.
G4RadioactiveDecay::G4RadioactiveDecay (const G4RadioactiveDecay & right) private
Member Function Documentation
void G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode (G4ParticleDefinition * apartDef, G4double weight, G4double currenTime, std::vector< double > & weights_v, std::vector< double > & times_v, std::vector< G4DynamicParticle * > & secondaries_v) protected
Definition at line 2184 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 2184 of file G4RadioactiveDecay.cc
References G4ITDecay::DecayIt(), G4DecayProducts::entries(), G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), photonEvaporation, and G4DecayProducts::PopProducts().
Referenced by DecayIt().
void G4RadioactiveDecay::AddUserDecayDataFile (G4int Z, G4int A, G4String filename)
Definition at line 1190 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 1190 of file G4RadioactiveDecay.cc
References INPUTHEPMC::filename, G4cout, G4endl, theUserRadioactiveDataFiles, and Z.
Referenced by G4RadioactiveDecaymessenger::SetNewValue().
G4VParticleChange* G4RadioactiveDecay::AtRestDoIt (const G4Track & theTrack, const G4Step & theStep) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 354 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 354 of file G4RadioactiveDecay.hh
References DecayIt().
G4double G4RadioactiveDecay::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 345 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 345 of file G4RadioactiveDecay.hh
References G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), and fRemainderLifeTime.
void G4RadioactiveDecay::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Definition at line 739 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 739 of file G4RadioactiveDecay.cc
References G4cout, G4GenericIon::GenericIon(), G4HadronicProcessStore::Instance(), isInitialised, G4Threading::IsMasterThread(), G4HadronicProcessStore::RegisterParticleForExtraProcess(), and StreamInfo().
void G4RadioactiveDecay::CalculateChainsFromParent (const G4ParticleDefinition & theParentNucleus)
Definition at line 1221 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 1221 of file G4RadioactiveDecay.cc
References A(), kdfinder::abs(), allowed, chainsFromParent, E, e, G4DecayTable::entries(), G4cout, G4endl, G4Exception(), G4VDecayChannel::GetBR(), G4NuclearDecay::GetDaughterExcitation(), G4NuclearDecay::GetDaughterNucleus(), G4DecayTable::GetDecayChannel(), G4NuclearDecay::GetDecayMode(), GetDecayTable(), G4NuclearLevelData::GetInstance(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4NuclearLevelData::GetLevelManager(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGLifeTime(), GetVerboseLevel(), halflifethreshold, G4DecayTable::Insert(), IsApplicable(), IT, JustWarning, k, levelTolerance, G4LevelManager::LifeTime(), MeV, G4LevelManager::NearestLevelEnergy(), G4LevelManager::NearestLevelIndex(), noFloat, ns, G4LevelManager::NumberOfTransitions(), photonEvaporation, ratesToDaughter, SetDecayRate(), G4RadioactiveDecayChainsFromParent::SetIonName(), G4RadioactiveDecayChainsFromParent::SetItsRates(), theDecayRateVector, theParentChainTable, and Z.
Referenced by DecayIt().
G4ThreeVector G4RadioactiveDecay::ChooseCollimationDirection () const protected
Definition at line 2157 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 2157 of file G4RadioactiveDecay.cc
References deg, dir, forceDecayDirection, forceDecayHalfAngle, G4cout, G4endl, G4UniformRand, GetVerboseLevel(), origin, CLHEP::Hep3Vector::phi(), phi, pi, CLHEP::Hep3Vector::setPhi(), CLHEP::Hep3Vector::setTheta(), and CLHEP::Hep3Vector::theta().
Referenced by CollimateDecayProduct().
void G4RadioactiveDecay::CollimateDecay (G4DecayProducts * products) protected
Definition at line 2113 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 2113 of file G4RadioactiveDecay.cc
References alpha, CollimateDecayProduct(), G4Electron::Definition(), G4Alpha::Definition(), G4Triton::Definition(), G4Proton::Definition(), G4Positron::Definition(), G4Neutron::Definition(), G4Gamma::Definition(), deg, G4InuclParticleNames::electron, G4DecayProducts::entries(), forceDecayDirection, forceDecayHalfAngle, G4cout, G4endl, G4DynamicParticle::GetParticleDefinition(), GetVerboseLevel(), G4InuclParticleNames::neutron, origin, G4InuclParticleNames::positron, G4InuclParticleNames::proton, and G4InuclParticleNames::triton.
Referenced by DoDecay().
void G4RadioactiveDecay::CollimateDecayProduct (G4DynamicParticle * product) protected
Definition at line 2142 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 2142 of file G4RadioactiveDecay.cc
References ChooseCollimationDirection(), G4cout, G4endl, G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), origin, and G4DynamicParticle::SetMomentumDirection().
Referenced by CollimateDecay().
G4double G4RadioactiveDecay::ConvolveSourceTimeProfile (const G4double t, const G4double tau) protected
Definition at line 519 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 519 of file G4RadioactiveDecay.cc
References G4cout, G4endl, G4Exception(), GetVerboseLevel(), JustWarning, NSourceBin, SBin, and SProfile.
Referenced by DecayIt().
G4VParticleChange * G4RadioactiveDecay::DecayIt (const G4Track & theTrack, const G4Step & theStep)
Definition at line 1662 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 1662 of file G4RadioactiveDecay.cc
References AddDeexcitationSpectrumForBiasMode(), G4ParticleChangeForRadDecay::AddSecondary(), AnalogueMC, G4DecayProducts::Boost(), BRBias, CalculateChainsFromParent(), G4VProcess::ClearNumberOfInteractionLengthLeft(), cm, ConvolveSourceTimeProfile(), DBin, decayWindows, DoDecay(), DProfile, G4DecayTable::DumpInfo(), G4DecayProducts::DumpInfo(), G4DecayTable::entries(), G4DecayProducts::entries(), fParticleChangeForRadDecay, fStopAndKill, fStopButAlive, G4cout, G4endl, G4UniformRand, GetChainsFromParent(), G4DecayTable::GetDecayChannel(), GetDecayTable(), GetDecayTime(), GetDecayTimeBin(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetLocalTime(), G4VPhysicalVolume::GetLogicalVolume(), G4DynamicParticle::GetMomentumDirection(), G4LogicalVolume::GetName(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGStable(), G4Track::GetPosition(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), GetVerboseLevel(), G4Track::GetVolume(), G4Track::GetWeight(), G4ParticleChangeForDecay::Initialize(), isAllVolumesMode, IsApplicable(), G4DecayProducts::IsChecked(), IsRateTableReady(), IT, KshellEC, n, ns, NshellEC, NSplit, G4DecayProducts::PopProducts(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForDecay::ProposeLocalTime(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4Track::SetCreatorModelIndex(), G4Track::SetGoodForTrackingFlag(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), theDecayRateVector, theRadDecayMode, theRadioactivityTables, ValidVolumes, weight, x, y, and z.
Referenced by AtRestDoIt(), and PostStepDoIt().
void G4RadioactiveDecay::DeselectAllVolumes ()
Definition at line 413 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 413 of file G4RadioactiveDecay.cc
References G4cout, G4endl, GetVerboseLevel(), isAllVolumesMode, and ValidVolumes.
void G4RadioactiveDecay::DeselectAVolume (const G4String aVolume)
Definition at line 354 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 354 of file G4RadioactiveDecay.cc
References G4cout, G4endl, G4Exception(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), GetVerboseLevel(), isAllVolumesMode, JustWarning, ValidVolumes, and Acts::Test::volume.
G4DecayProducts * G4RadioactiveDecay::DoDecay (const G4ParticleDefinition & theParticleDef) protected
Definition at line 2075 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 2075 of file G4RadioactiveDecay.cc
References CollimateDecay(), G4VDecayChannel::DecayIt(), FatalException, G4cout, G4endl, G4Exception(), GetDecayTable(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), GetVerboseLevel(), MeV, G4DecayTable::SelectADecayChannel(), and theRadDecayMode.
Referenced by DecayIt().
void G4RadioactiveDecay::GetChainsFromParent (const G4ParticleDefinition & aParticle)
Definition at line 437 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 437 of file G4RadioactiveDecay.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), theDecayRateVector, and theParentChainTable.
Referenced by DecayIt().
const G4ThreeVector& G4RadioactiveDecay::GetDecayDirection () const inline
Definition at line 221 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 221 of file G4RadioactiveDecay.hh
References forceDecayDirection.
G4double G4RadioactiveDecay::GetDecayHalfAngle () const inline
Definition at line 229 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 229 of file G4RadioactiveDecay.hh
References forceDecayHalfAngle.
G4DecayTable * G4RadioactiveDecay::GetDecayTable (const G4ParticleDefinition * aNucleus)
Definition at line 311 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 311 of file G4RadioactiveDecay.cc
References dkmap, G4ParticleDefinition::GetParticleName(), and LoadDecayTable().
Referenced by CalculateChainsFromParent(), DecayIt(), and DoDecay().
G4double G4RadioactiveDecay::GetDecayTime () protected
Definition at line 581 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 581 of file G4RadioactiveDecay.cc
References DBin, DProfile, G4cout, G4endl, G4Exception(), G4UniformRand, GetVerboseLevel(), and JustWarning.
Referenced by DecayIt().
G4int G4RadioactiveDecay::GetDecayTimeBin (const G4double aDecayTime) protected
Definition at line 608 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 608 of file G4RadioactiveDecay.cc
References DBin, G4Exception(), and JustWarning.
Referenced by DecayIt().
G4double G4RadioactiveDecay::GetMeanFreePath (const G4Track & theTrack, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 674 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 674 of file G4RadioactiveDecay.cc
References source.hepunit::c_light, DBL_MAX, DBL_MIN, G4cout, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGLifeTime(), G4DynamicParticle::GetTotalMomentum(), GetVerboseLevel(), GeV, JustWarning, keV, and m.
G4double G4RadioactiveDecay::GetMeanLifeTime (const G4Track & theTrack, G4ForceCondition * condition) protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 632 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 632 of file G4RadioactiveDecay.cc
References AnalogueMC, DBL_MAX, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), GetVerboseLevel(), GeV, and ns.
G4NucleusLimits G4RadioactiveDecay::GetNucleusLimits () const inline
Definition at line 181 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 181 of file G4RadioactiveDecay.hh
References theNucleusLimits.
G4int G4RadioactiveDecay::GetSplitNuclei () inline
Definition at line 215 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 215 of file G4RadioactiveDecay.hh
References NSplit.
std::vector<G4RadioactivityTable*> G4RadioactiveDecay::GetTheRadioactivityTables () inline
Definition at line 159 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 159 of file G4RadioactiveDecay.hh
References theRadioactivityTables.
G4int G4RadioactiveDecay::GetVerboseLevel () const inline
Definition at line 173 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 173 of file G4RadioactiveDecay.hh
References verboseLevel.
Referenced by CalculateChainsFromParent(), ChooseCollimationDirection(), CollimateDecay(), CollimateDecayProduct(), ConvolveSourceTimeProfile(), DecayIt(), DeselectAllVolumes(), DeselectAVolume(), DoDecay(), G4RadioactiveDecay(), GetChainsFromParent(), GetDecayTime(), GetMeanFreePath(), GetMeanLifeTime(), LoadDecayTable(), SelectAllVolumes(), SelectAVolume(), SetDecayBias(), and SetSourceTimeProfile().
G4bool G4RadioactiveDecay::IsAnalogueMonteCarlo () inline
Definition at line 200 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 200 of file G4RadioactiveDecay.hh
References AnalogueMC.
G4bool G4RadioactiveDecay::IsApplicable (const G4ParticleDefinition & aParticle) virtual
Reimplemented from G4VProcess.
Definition at line 285 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 285 of file G4RadioactiveDecay.cc
References A(), G4NucleusLimits::GetAMax(), G4NucleusLimits::GetAMin(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGLifeTime(), G4NucleusLimits::GetZMax(), G4NucleusLimits::GetZMin(), theNucleusLimits, and Z.
Referenced by CalculateChainsFromParent(), and DecayIt().
G4bool G4RadioactiveDecay::IsRateTableReady (const G4ParticleDefinition & aParticle)
Definition at line 424 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 424 of file G4RadioactiveDecay.cc
References G4ParticleDefinition::GetParticleName(), and theParentChainTable.
Referenced by DecayIt().
G4DecayTable * G4RadioactiveDecay::LoadDecayTable (const G4ParticleDefinition & theParentNucleus)
Definition at line 803 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 803 of file G4RadioactiveDecay.cc
References a, A(), kdfinder::abs(), allowed, Alpha, applyARM, b, BDNeutron, BDProton, Beta2Minus, Beta2Plus, BetaMinus, BetaPlus, c, dirPath, G4DecayTable::DumpInfo(), G4DecayTable::entries(), FatalException, file, G4Ions::FloatLevelBase(), G4Exception(), G4VDecayChannel::GetBR(), G4DecayTable::GetDecayChannel(), G4NuclearDecay::GetDecayMode(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), halflifethreshold, G4DecayTable::Insert(), IT, JustWarning, keV, KshellEC, levelTolerance, LshellEC, MeV, MshellEC, Neutron, Neutron2, noFloat, NshellEC, photonEvaporation, Proton, Proton2, RDM_ERROR, G4ECDecay::SetARM(), G4ITDecay::SetARM(), G4VDecayChannel::SetBR(), G4NuclearDecay::SetHLThreshold(), SpFission, G4String::strip(), theUserRadioactiveDataFiles, Triton, and Z.
Referenced by GetDecayTable().
G4RadioactiveDecay& G4RadioactiveDecay::operator= (const G4RadioactiveDecay & right) private
G4VParticleChange* G4RadioactiveDecay::PostStepDoIt (const G4Track & theTrack, const G4Step & theStep) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 359 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 359 of file G4RadioactiveDecay.hh
References DecayIt().
void G4RadioactiveDecay::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4VProcess.
Definition at line 251 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 251 of file G4RadioactiveDecay.cc
void G4RadioactiveDecay::SelectAllVolumes ()
Definition at line 389 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 389 of file G4RadioactiveDecay.cc
References G4cout, G4endl, G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), GetVerboseLevel(), isAllVolumesMode, ValidVolumes, and Acts::Test::volume.
Referenced by G4RadioactiveDecay().
void G4RadioactiveDecay::SelectAVolume (const G4String aVolume)
Definition at line 328 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 328 of file G4RadioactiveDecay.cc
References G4cout, G4endl, G4Exception(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), GetVerboseLevel(), JustWarning, ValidVolumes, and Acts::Test::volume.
void G4RadioactiveDecay::SetAnalogueMonteCarlo (G4bool r) inline
Definition at line 189 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 189 of file G4RadioactiveDecay.hh
References AnalogueMC, e, halflifethreshold, r, and CLHEP::s.
Referenced by SetBRBias(), SetDecayBias(), SetSourceTimeProfile(), and SetSplitNuclei().
void G4RadioactiveDecay::SetARM (G4bool arm) inline
Definition at line 132 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 132 of file G4RadioactiveDecay.hh
References applyARM.
Referenced by PhysicsList::AddRadioactiveDecay().
void G4RadioactiveDecay::SetBRBias (G4bool r) inline
Definition at line 203 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 203 of file G4RadioactiveDecay.hh
References BRBias, r, and SetAnalogueMonteCarlo().
void G4RadioactiveDecay::SetDecayBias (G4String filename)
Definition at line 1603 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 1603 of file G4RadioactiveDecay.cc
References bin, DBin, decayWindows, DProfile, FatalException, G4cout, G4endl, G4Exception(), GetVerboseLevel(), in, JustWarning, NDecayBin, SetAnalogueMonteCarlo(), and theRadioactivityTables.
void G4RadioactiveDecay::SetDecayCollimation (const G4ThreeVector & theDir, G4double halfAngle = 0.*CLHEP::deg) inline
Definition at line 233 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 233 of file G4RadioactiveDecay.hh
References SetDecayDirection(), and SetDecayHalfAngle().
void G4RadioactiveDecay::SetDecayDirection (const G4ThreeVector & theDir) inline
Definition at line 217 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 217 of file G4RadioactiveDecay.hh
References forceDecayDirection, and CLHEP::Hep3Vector::unit().
Referenced by SetDecayCollimation().
void G4RadioactiveDecay::SetDecayHalfAngle (G4double halfAngle = 0.*CLHEP::deg) inline
Definition at line 225 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 225 of file G4RadioactiveDecay.hh
References CLHEP::deg, forceDecayHalfAngle, max, and min.
Referenced by SetDecayCollimation().
void G4RadioactiveDecay::SetDecayRate (G4int theZ, G4int theA, G4double theE, G4int theG, std::vector< G4double > theCoefficients, std::vector< G4double > theTaos)
Definition at line 1205 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 1205 of file G4RadioactiveDecay.cc
References ratesToDaughter, G4RadioactiveDecayRatesToDaughter::SetA(), G4RadioactiveDecayRatesToDaughter::SetDecayRateC(), G4RadioactiveDecayRatesToDaughter::SetE(), G4RadioactiveDecayRatesToDaughter::SetGeneration(), G4RadioactiveDecayRatesToDaughter::SetTaos(), and G4RadioactiveDecayRatesToDaughter::SetZ().
Referenced by CalculateChainsFromParent().
void G4RadioactiveDecay::SetFBeta (G4bool r) inline
Definition at line 196 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 196 of file G4RadioactiveDecay.hh
References FBeta, and r.
void G4RadioactiveDecay::SetHLThreshold (G4double hl) inline
Definition at line 126 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 126 of file G4RadioactiveDecay.hh
References halflifethreshold.
void G4RadioactiveDecay::SetICM (G4bool icm) inline
Definition at line 129 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 129 of file G4RadioactiveDecay.hh
References applyICM.
void G4RadioactiveDecay::SetNucleusLimits (G4NucleusLimits theNucleusLimits1) inline
Definition at line 176 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 176 of file G4RadioactiveDecay.hh
References theNucleusLimits.
void G4RadioactiveDecay::SetSourceTimeProfile (G4String filename)
Definition at line 1555 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 1555 of file G4RadioactiveDecay.cc
References bin, FatalException, G4cout, G4endl, G4Exception(), GetVerboseLevel(), in, JustWarning, NSourceBin, SBin, SetAnalogueMonteCarlo(), and SProfile.
void G4RadioactiveDecay::SetSplitNuclei (G4int r) inline
Definition at line 209 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 209 of file G4RadioactiveDecay.hh
References NSplit, r, and SetAnalogueMonteCarlo().
void G4RadioactiveDecay::SetVerboseLevel (G4int value) inline
Definition at line 170 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 170 of file G4RadioactiveDecay.hh
References verboseLevel.
void G4RadioactiveDecay::StreamInfo (std::ostream & os, const G4String & endline) private
Definition at line 757 of file G4RadioactiveDecay.cc.
View newest version in sPHENIX GitHub at line 757 of file G4RadioactiveDecay.cc
References G4EmParameters::Auger(), G4EmParameters::AugerCascade(), G4EmParameters::BeardenFluoDir(), G4DeexPrecoParameters::CorrelatedGamma(), G4EmParameters::DeexcitationIgnoreCut(), G4EmParameters::Fluo(), G4NuclearLevelData::GetInstance(), G4DeexPrecoParameters::GetInternalConversionFlag(), G4DeexPrecoParameters::GetMaxLifeTime(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::GetTwoJMAX(), G4EmParameters::Instance(), CLHEP::prec, CLHEP::ps, and G4DeexPrecoParameters::StoreICLevelData().
Referenced by BuildPhysicsTable().
Member Data Documentation
G4bool G4RadioactiveDecay::AnalogueMC private
Definition at line 286 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 286 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), GetMeanLifeTime(), IsAnalogueMonteCarlo(), and SetAnalogueMonteCarlo().
G4bool G4RadioactiveDecay::applyARM private
Definition at line 293 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 293 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), LoadDecayTable(), and SetARM().
G4bool G4RadioactiveDecay::applyICM private
Definition at line 292 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 292 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), and SetICM().
G4bool G4RadioactiveDecay::BRBias private
Definition at line 287 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 287 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), and SetBRBias().
G4RadioactiveDecayChainsFromParent G4RadioactiveDecay::chainsFromParent private
Definition at line 312 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 312 of file G4RadioactiveDecay.hh
Referenced by CalculateChainsFromParent().
G4double G4RadioactiveDecay::DBin[100] private
Definition at line 304 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 304 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), GetDecayTime(), GetDecayTimeBin(), and SetDecayBias().
G4int G4RadioactiveDecay::decayWindows[100] private
Definition at line 317 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 317 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), and SetDecayBias().
G4String G4RadioactiveDecay::dirPath private
Definition at line 321 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 321 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), and LoadDecayTable().
DecayTableMap* G4RadioactiveDecay::dkmap private
Definition at line 330 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 330 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), GetDecayTable(), and ~G4RadioactiveDecay().
G4double G4RadioactiveDecay::DProfile[100] private
Definition at line 305 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 305 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), GetDecayTime(), and SetDecayBias().
G4bool G4RadioactiveDecay::FBeta private
Definition at line 288 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 288 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), and SetFBeta().
G4ThreeVector G4RadioactiveDecay::forceDecayDirection private
Definition at line 296 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 296 of file G4RadioactiveDecay.hh
Referenced by ChooseCollimationDirection(), CollimateDecay(), GetDecayDirection(), and SetDecayDirection().
G4double G4RadioactiveDecay::forceDecayHalfAngle private
Definition at line 297 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 297 of file G4RadioactiveDecay.hh
Referenced by ChooseCollimationDirection(), CollimateDecay(), GetDecayHalfAngle(), and SetDecayHalfAngle().
G4ParticleChangeForRadDecay G4RadioactiveDecay::fParticleChangeForRadDecay private
Definition at line 341 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 341 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), and G4RadioactiveDecay().
G4double G4RadioactiveDecay::fRemainderLifeTime private
Definition at line 336 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 336 of file G4RadioactiveDecay.hh
Referenced by AtRestGetPhysicalInteractionLength().
G4double G4RadioactiveDecay::halflifethreshold private
Definition at line 291 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 291 of file G4RadioactiveDecay.hh
Referenced by CalculateChainsFromParent(), G4RadioactiveDecay(), LoadDecayTable(), SetAnalogueMonteCarlo(), and SetHLThreshold().
bool G4RadioactiveDecay::isAllVolumesMode private
Definition at line 308 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 308 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), DeselectAllVolumes(), DeselectAVolume(), G4RadioactiveDecay(), and SelectAllVolumes().
G4bool G4RadioactiveDecay::isInitialised private
Definition at line 285 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 285 of file G4RadioactiveDecay.hh
Referenced by BuildPhysicsTable().
const G4double G4RadioactiveDecay::levelTolerance = 10.0*eV static private
Definition at line 318 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 318 of file G4RadioactiveDecay.hh
Referenced by CalculateChainsFromParent(), and LoadDecayTable().
G4int G4RadioactiveDecay::NDecayBin private
Definition at line 303 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 303 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), and SetDecayBias().
G4int G4RadioactiveDecay::NSourceBin private
Definition at line 300 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 300 of file G4RadioactiveDecay.hh
Referenced by ConvolveSourceTimeProfile(), G4RadioactiveDecay(), and SetSourceTimeProfile().
G4int G4RadioactiveDecay::NSplit private
Definition at line 289 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 289 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), GetSplitNuclei(), and SetSplitNuclei().
const G4ThreeVector G4RadioactiveDecay::origin static private
Definition at line 298 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 298 of file G4RadioactiveDecay.hh
Referenced by ChooseCollimationDirection(), CollimateDecay(), and CollimateDecayProduct().
G4PhotonEvaporation* G4RadioactiveDecay::photonEvaporation private
Definition at line 281 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 281 of file G4RadioactiveDecay.hh
Referenced by AddDeexcitationSpectrumForBiasMode(), CalculateChainsFromParent(), G4RadioactiveDecay(), LoadDecayTable(), and ~G4RadioactiveDecay().
G4RadioactiveDecayRatesToDaughter G4RadioactiveDecay::ratesToDaughter private
Definition at line 310 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 310 of file G4RadioactiveDecay.hh
Referenced by CalculateChainsFromParent(), and SetDecayRate().
G4double G4RadioactiveDecay::SBin[100] private
Definition at line 301 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 301 of file G4RadioactiveDecay.hh
Referenced by ConvolveSourceTimeProfile(), G4RadioactiveDecay(), and SetSourceTimeProfile().
G4double G4RadioactiveDecay::SProfile[100] private
Definition at line 302 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 302 of file G4RadioactiveDecay.hh
Referenced by ConvolveSourceTimeProfile(), G4RadioactiveDecay(), and SetSourceTimeProfile().
G4RadioactiveDecayRates G4RadioactiveDecay::theDecayRateVector private
Definition at line 311 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 311 of file G4RadioactiveDecay.hh
Referenced by CalculateChainsFromParent(), DecayIt(), and GetChainsFromParent().
G4NucleusLimits G4RadioactiveDecay::theNucleusLimits private
Definition at line 283 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 283 of file G4RadioactiveDecay.hh
Referenced by GetNucleusLimits(), IsApplicable(), and SetNucleusLimits().
G4RadioactiveDecayParentChainTable G4RadioactiveDecay::theParentChainTable private
Definition at line 313 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 313 of file G4RadioactiveDecay.hh
Referenced by CalculateChainsFromParent(), GetChainsFromParent(), and IsRateTableReady().
G4RadioactiveDecayMode G4RadioactiveDecay::theRadDecayMode private
Definition at line 327 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 327 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), and DoDecay().
G4RadioactiveDecaymessenger* G4RadioactiveDecay::theRadioactiveDecaymessenger private
Definition at line 280 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 280 of file G4RadioactiveDecay.hh
Referenced by G4RadioactiveDecay(), and ~G4RadioactiveDecay().
std::vector<G4RadioactivityTable*> G4RadioactiveDecay::theRadioactivityTables private
Definition at line 316 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 316 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), G4RadioactiveDecay(), GetTheRadioactivityTables(), and SetDecayBias().
std::map<G4int, G4String> G4RadioactiveDecay::theUserRadioactiveDataFiles private
Definition at line 324 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 324 of file G4RadioactiveDecay.hh
Referenced by AddUserDecayDataFile(), G4RadioactiveDecay(), and LoadDecayTable().
std::vector<G4String> G4RadioactiveDecay::ValidVolumes private
Definition at line 307 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 307 of file G4RadioactiveDecay.hh
Referenced by DecayIt(), DeselectAllVolumes(), DeselectAVolume(), SelectAllVolumes(), and SelectAVolume().
G4int G4RadioactiveDecay::verboseLevel private
Definition at line 337 of file G4RadioactiveDecay.hh.
View newest version in sPHENIX GitHub at line 337 of file G4RadioactiveDecay.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactiveDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4RadioactiveDecay.cc