ECCE @ EIC Software: G4Visible Class Reference
G4Visible Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Visible.hh>
Public Member Functions
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Protected Attributes
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Friends
std::ostream & operator<< (std::ostream &os, const G4Visible &v)
Detailed Description
Definition at line 47 of file G4Visible.hh.
View newest version in sPHENIX GitHub at line 47 of file G4Visible.hh
Constructor & Destructor Documentation
G4Visible::G4Visible ()
Definition at line 36 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 36 of file G4Visible.cc
G4Visible::G4Visible (const G4Visible & visible)
Definition at line 41 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 41 of file G4Visible.cc
References fAllocatedVisAttributes, and fpVisAttributes.
G4Visible::G4Visible (const G4VisAttributes * pVA)
Definition at line 48 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 48 of file G4Visible.cc
G4Visible::~G4Visible () virtual
Definition at line 53 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 53 of file G4Visible.cc
References fAllocatedVisAttributes, and fpVisAttributes.
Member Function Documentation
const G4VisAttributes* G4Visible::GetVisAttributes () const
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4XXXSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddPrimitive(), G4VSceneHandler::AddPrimitive(), G4HepRepSceneHandler::getColorFor(), G4VSceneHandler::GetTextColour(), G4VSceneHandler::LoadAtts(), G4HepRepSceneHandler::setLine(), G4HepRepSceneHandler::setMarker(), and G4HepRepSceneHandler::setVisibility().
G4bool G4Visible::operator!= (const G4Visible & right) const
Definition at line 86 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 86 of file G4Visible.cc
References fpVisAttributes.
G4Visible & G4Visible::operator= (const G4Visible & rhs)
Definition at line 57 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 57 of file G4Visible.cc
References fAllocatedVisAttributes, and fpVisAttributes.
Referenced by G4VMarker::operator=().
void G4Visible::SetVisAttributes (const G4VisAttributes * pVA)
Definition at line 79 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 79 of file G4Visible.cc
References fAllocatedVisAttributes, and fpVisAttributes.
Referenced by G4VSceneHandler::AddPrimitive(), G4DrawVoxels::ComputeVoxelPolyhedra(), G4GPSModel::DescribeYourselfTo(), G4VFieldModel::DescribeYourselfTo(), StandaloneVisAction::Draw(), UVA_VisAction::Draw(), ExN04MuonHit::Draw(), ExN04TrackerHit::Draw(), G4ScoringCylinder::Draw(), ExTGTrackerHit::Draw(), RE01TrackerHit::Draw(), eRositaTrackerHit::Draw(), G4ScoringBox::Draw(), RE05MuonHit::Draw(), RE05TrackerHit::Draw(), Par01EnergySpot::Draw(), ExP01TrackerHit::Draw(), B2TrackerHit::Draw(), XAluminumElectrodeHit::Draw(), ExN02TrackerHit::Draw(), B5DriftChamberHit::Draw(), DMXPmtHit::Draw(), TrackerHit::Draw(), H02MuonHit::Draw(), G4ScoreLogColorMap::DrawColorChartBar(), G4VScoreColorMap::DrawColorChartBar(), G4ScoreLogColorMap::DrawColorChartText(), G4VScoreColorMap::DrawColorChartText(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), CexmcScenePrimitives::DrawRadialLine(), CexmcEventAction::DrawTrackPoints(), LXeTrajectory::DrawTrajectory(), RE01Trajectory::DrawTrajectory(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), G4BlineEventAction::EndOfEventAction(), PerspectiveVisAction::ExtendedDraw(), G4AxesModel::G4AxesModel(), G4VisCommandSceneAddLogo::G4Logo::G4Logo(), CexmcScenePrimitives::HighlightInnerCrystals(), CexmcScenePrimitives::MarkTargetCenter(), G4VisCommandSceneAddDate::Date::operator()(), G4VisCommandSceneAddFrame::Frame::operator()(), G4VisCommandSceneAddLogo2D::Logo2D::operator()(), G4VSceneHandler::RequestPrimitives(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), G4VisCommandSceneAddText2D::SetNewValue(), and DMXSteppingAction::UserSteppingAction().
void G4Visible::SetVisAttributes (const G4VisAttributes & VA)
Definition at line 68 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 68 of file G4Visible.cc
References fAllocatedVisAttributes, and fpVisAttributes.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4Visible & v) friend
Definition at line 93 of file G4Visible.cc.
View newest version in sPHENIX GitHub at line 93 of file G4Visible.cc
Member Data Documentation
G4bool G4Visible::fAllocatedVisAttributes protected
Definition at line 81 of file G4Visible.hh.
View newest version in sPHENIX GitHub at line 81 of file G4Visible.hh
Referenced by G4Visible(), operator=(), SetVisAttributes(), and ~G4Visible().
const G4VisAttributes* G4Visible::fpVisAttributes protected
Definition at line 80 of file G4Visible.hh.
View newest version in sPHENIX GitHub at line 80 of file G4Visible.hh
Referenced by G4Visible(), operator!=(), operator<<(), operator=(), SetVisAttributes(), and ~G4Visible().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Visible.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4Visible.cc