ECCE @ EIC Software: G4UIGainServer Class Reference
G4UIGainServer Class Reference
#include <geant4/tree/geant4-10.6-release/source/interfaces/GAG/include/G4UIGainServer.hh>
Public Member Functions
G4UIsession * SessionStart ()
virtual void PauseSessionStart (const G4String &msg)
virtual G4int ReceiveG4cout (const G4String &coutString)
virtual G4int ReceiveG4cerr (const G4String &cerrString)
G4UIGainServer ()
~G4UIGainServer ()
void SessionTerminate ()
void Prompt (G4String)
G4String GetCommand ()
Public Member Functions inherited from G4VBasicShell
G4VBasicShell ()
virtual ~G4VBasicShell ()
Public Member Functions inherited from G4UIsession
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
G4int GetLastReturnCode () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Private Member Functions
void GetNewTreeStructure (G4UIcommandTree *, int recursiveLevel)
void GetNewTreeValues (G4UIcommandTree *, int recursiveLevel)
virtual void ExecuteCommand (const G4String &aCommand)
virtual G4bool GetHelpChoice (G4int &aInt)
virtual void ExitHelp () const
bool SetUPServer ()
void WaitingConnection ()
void CloseConnection ()
void ChangeDirectory (G4String)
void ListDirectory (G4String)
void TerminalHelp (G4String)
G4String ModifyPrefix (G4String)
G4UIcommandTree * FindDirPath (G4String)
void ShowCurrent (G4String)
G4String GetFullPath (G4String)
void SendCommandProperties (G4UIcommandTree *)
void SendParameterProperties (G4UIcommandTree *)
void SendAParamProperty (G4UIcommand *)
void SendATclParamProperty (G4UIcommand *)
void CodeGenJavaTree (G4UIcommandTree *, int recursiveLevel)
void CodeGenJavaParams (G4UIcommandTree *, int recursiveLevel)
void CodeGenTclTree (G4UIcommandTree *, int recursiveLevel)
void CodeGenTclParams (G4UIcommandTree *, int recursiveLevel)
void SendDisableList (G4UIcommandTree *, int recursiveLevel)
void NotifyStateChange (void)
void NotifyCommandUpdate (void)
void NotifyParameterUpdate (G4UIcommand *)
int CommandUpdated (void)
void UpdateState (void)
void UpdateParamVal (void)
Private Attributes
G4String prefix
G4String promptCharacter
G4UImanager * UI
UImode uiMode
G4String JVersion
G4String TVersion
G4bool iExit
G4bool iCont
int socketD [3]
int port
struct sockaddr_in saddr
struct sockaddr_in caddr
int len
int ret
char buf [1024]
std::vector< G4String > previousTreeCommands
std::vector< G4String > newTreeCommands
std::vector< G4String > previousTreeParams
std::vector< G4String > newTreeParams
std::vector< G4UIcommand * > previousTreePCP
std::vector< G4UIcommand * > newTreePCP
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Public Member Functions inherited from G4UIsession
static G4int InSession ()
Protected Member Functions inherited from G4VBasicShell
G4String ModifyToFullPathCommand (const char *aCommandLine) const
G4String GetCurrentWorkingDirectory () const
G4bool ChangeDirectory (const char *newDir)
G4UIcommandTree * FindDirectory (const char *dirName) const
G4UIcommand * FindCommand (const char *commandName) const
G4String Complete (const G4String &)
G4String FindMatchingPath (G4UIcommandTree *, const G4String &)
void ApplyShellCommand (const G4String &, G4bool &, G4bool &)
void ShowCurrent (const G4String &) const
void ChangeDirectoryCommand (const G4String &)
void ListDirectory (const G4String &) const
void TerminalHelp (const G4String &)
Protected Attributes inherited from G4UIsession
G4int ifBatch
G4int lastRC
Static Protected Attributes inherited from G4UIsession
static G4ICOMS_DLL G4int inSession = 0
Detailed Description
Definition at line 63 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 63 of file G4UIGainServer.hh
Constructor & Destructor Documentation
G4UIGainServer::G4UIGainServer ()
Definition at line 42 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 42 of file G4UIGainServer.cc
References DEFAULT_PORT, FALSE, G4cout, G4endl, G4StateManager::GetCurrentState(), GetNewTreeStructure(), GetNewTreeValues(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4UImanager::GetTree(), G4UImanager::GetUIpointer(), iCont, iExit, JVersion, newTreeCommands, newTreeParams, newTreePCP, port, previousTreeCommands, previousTreeParams, previousTreePCP, promptCharacter, SetUPServer(), terminal_mode, gammaraytel::tree, TVersion, UI, and uiMode.
G4UIGainServer::~G4UIGainServer ()
Definition at line 76 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 76 of file G4UIGainServer.cc
References G4UImanager::GetUIpointer(), G4UImanager::SetCoutDestination(), G4UImanager::SetSession(), and UI.
Member Function Documentation
void G4UIGainServer::ChangeDirectory (G4String newCommand) private
Definition at line 479 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 479 of file G4UIGainServer.cc
References G4String::both, FindDirPath(), G4cout, G4endl, ModifyPrefix(), prefix, and G4String::strip().
Referenced by GetCommand().
void G4UIGainServer::CloseConnection () private
void G4UIGainServer::CodeGenJavaParams (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 693 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 693 of file G4UIGainServer.cc
References G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommandTree::GetPathName(), G4UIcommandTree::GetTitle(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), and SendAParamProperty().
Referenced by SendCommandProperties(), and SendParameterProperties().
void G4UIGainServer::CodeGenJavaTree (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 674 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 674 of file G4UIGainServer.cc
References G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommandTree::GetTree(), and G4UIcommandTree::GetTreeEntry().
Referenced by SendCommandProperties().
void G4UIGainServer::CodeGenTclParams (G4UIcommandTree * , int recursiveLevel) private
void G4UIGainServer::CodeGenTclTree (G4UIcommandTree * , int recursiveLevel) private
int G4UIGainServer::CommandUpdated (void) private
Definition at line 830 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 830 of file G4UIGainServer.cc
References added, addedAndDeleted, deleted, G4cout, G4endl, newTreeCommands, notChanged, and previousTreeCommands.
Referenced by ExecuteCommand().
void G4UIGainServer::ExecuteCommand (const G4String & aCommand) private virtual
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Reimplemented from G4VBasicShell.
Definition at line 131 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 131 of file G4UIGainServer.cc
References G4UImanager::ApplyCommand(), CommandUpdated(), fAliasNotFound, fCommandNotFound, fCommandSucceeded, fIllegalApplicationState, fParameterOutOfCandidates, fParameterOutOfRange, fParameterUnreadable, G4cerr, G4cout, G4endl, GetNewTreeStructure(), GetNewTreeValues(), G4UImanager::GetTree(), newTreeCommands, newTreeParams, newTreePCP, NotifyCommandUpdate(), previousTreeCommands, previousTreeParams, previousTreePCP, G4UImanager::SolveAlias(), terminal_mode, gammaraytel::tree, UI, uiMode, UpdateParamVal(), and UpdateState().
Referenced by PauseSessionStart(), and SessionStart().
void G4UIGainServer::ExitHelp () const private virtual
Implements G4VBasicShell.
Definition at line 356 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 356 of file G4UIGainServer.cc
References G4cin.
G4UIcommandTree * G4UIGainServer::FindDirPath (G4String newCommand) private
Definition at line 629 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 629 of file G4UIGainServer.cc
References G4UIcommandTree::GetTree(), G4UImanager::GetTree(), incremental_prev_tag::idx, G4String::index(), and UI.
Referenced by ChangeDirectory(), and ListDirectory().
G4String G4UIGainServer::GetCommand ()
Definition at line 183 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 183 of file G4UIGainServer.cc
References G4String::append(), buf, ChangeDirectory(), close(), G4cerr, G4cin, G4cout, G4endl, GetFullPath(), G4UImanager::GetNumberOfHistory(), G4UImanager::GetPreviousCommand(), G4UImanager::GetTree(), iCont, iExit, java_mode, JVersion, G4String::leading, ListDirectory(), NotifyStateChange(), promptCharacter, G4String::readLine(), G4String::remove(), SendCommandProperties(), ShowCurrent(), socketD, G4String::strip(), tcl_mode, terminal_mode, TerminalHelp(), gammaraytel::tree, TVersion, UI, and uiMode.
Referenced by PauseSessionStart(), and SessionStart().
G4String G4UIGainServer::GetFullPath (G4String aNewCommand) private
Definition at line 421 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 421 of file G4UIGainServer.cc
References G4String::append(), G4String::both, ModifyPrefix(), prefix, and G4String::strip().
Referenced by GetCommand(), and ShowCurrent().
G4bool G4UIGainServer::GetHelpChoice (G4int & aInt) private virtual
Implements G4VBasicShell.
Definition at line 343 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 343 of file G4UIGainServer.cc
References FALSE, G4cin, and TRUE.
void G4UIGainServer::GetNewTreeStructure (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 861 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 861 of file G4UIGainServer.cc
References G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommandTree::GetPathName(), G4UIcommandTree::GetTitle(), G4UIcommand::GetTitle(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), newTreeCommands, t, and title().
Referenced by ExecuteCommand(), and G4UIGainServer().
void G4UIGainServer::GetNewTreeValues (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 910 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 910 of file G4UIGainServer.cc
References G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), newTreeParams, newTreePCP, and t.
Referenced by ExecuteCommand(), and G4UIGainServer().
void G4UIGainServer::ListDirectory (G4String newCommand) private
Definition at line 506 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 506 of file G4UIGainServer.cc
References G4String::both, FindDirPath(), G4cout, G4endl, G4UIcommandTree::ListCurrent(), ModifyPrefix(), prefix, and G4String::strip().
Referenced by GetCommand().
G4String G4UIGainServer::ModifyPrefix (G4String newCommand) private
Definition at line 606 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 606 of file G4UIGainServer.cc
References G4String::last(), and prefix.
Referenced by ChangeDirectory(), GetFullPath(), and ListDirectory().
void G4UIGainServer::NotifyCommandUpdate (void) private
Definition at line 815 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 815 of file G4UIGainServer.cc
References G4UImanager::GetTree(), SendCommandProperties(), gammaraytel::tree, and UI.
Referenced by ExecuteCommand().
void G4UIGainServer::NotifyParameterUpdate (G4UIcommand * com) private
Definition at line 823 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 823 of file G4UIGainServer.cc
References SendAParamProperty().
Referenced by UpdateParamVal().
void G4UIGainServer::NotifyStateChange (void) private
Definition at line 799 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 799 of file G4UIGainServer.cc
References G4cout, G4endl, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4UImanager::GetTree(), SendDisableList(), terminal_mode, gammaraytel::tree, UI, and uiMode.
Referenced by GetCommand(), and UpdateState().
void G4UIGainServer::PauseSessionStart (const G4String & msg) virtual
Implements G4VBasicShell.
Definition at line 112 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 112 of file G4UIGainServer.cc
References buf, ExecuteCommand(), G4cout, G4endl, GetCommand(), iCont, promptCharacter, socketD, and TRUE.
void G4UIGainServer::Prompt (G4String)
G4int G4UIGainServer::ReceiveG4cerr (const G4String & cerrString) virtual
Reimplemented from G4UIsession.
Definition at line 329 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 329 of file G4UIGainServer.cc
References socketD.
G4int G4UIGainServer::ReceiveG4cout (const G4String & coutString) virtual
Reimplemented from G4UIsession.
Definition at line 315 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 315 of file G4UIGainServer.cc
References socketD.
void G4UIGainServer::SendAParamProperty (G4UIcommand * Comp) private
Definition at line 716 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 716 of file G4UIGainServer.cc
References G4String::append(), c, G4cout, G4endl, G4UIcommand::GetCommandPath(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterGuidance(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), G4UIcommand::GetRange(), int(), G4UIparameter::IsOmittable(), and title().
Referenced by CodeGenJavaParams(), and NotifyParameterUpdate().
void G4UIGainServer::SendATclParamProperty (G4UIcommand *) private
void G4UIGainServer::SendCommandProperties (G4UIcommandTree * tree) private
Definition at line 647 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 647 of file G4UIGainServer.cc
References CodeGenJavaParams(), CodeGenJavaTree(), G4cerr, G4cout, G4endl, java_mode, and uiMode.
Referenced by GetCommand(), and NotifyCommandUpdate().
void G4UIGainServer::SendDisableList (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 758 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 758 of file G4UIGainServer.cc
References false, G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), and G4UIcommand::IsAvailable().
Referenced by NotifyStateChange().
void G4UIGainServer::SendParameterProperties (G4UIcommandTree * tree) private
Definition at line 662 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 662 of file G4UIGainServer.cc
References CodeGenJavaParams(), G4cerr, G4endl, java_mode, and uiMode.
G4UIsession * G4UIGainServer::SessionStart () virtual
Implements G4VBasicShell.
Definition at line 93 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 93 of file G4UIGainServer.cc
References ExecuteCommand(), GetCommand(), G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), iExit, promptCharacter, TRUE, and WaitingConnection().
void G4UIGainServer::SessionTerminate ()
Definition at line 454 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 454 of file G4UIGainServer.cc
References G4cout, and G4endl.
bool G4UIGainServer::SetUPServer () private
Definition at line 364 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 364 of file G4UIGainServer.cc
References G4cout, G4endl, port, saddr, SOCK_NAME, g4zmq::socket, and socketD.
Referenced by G4UIGainServer().
void G4UIGainServer::ShowCurrent (G4String newCommand) private
Definition at line 461 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 461 of file G4UIGainServer.cc
References G4cout, G4endl, G4UImanager::GetCurrentValues(), GetFullPath(), G4String::isNull(), terminal_mode, UI, and uiMode.
Referenced by GetCommand().
void G4UIGainServer::TerminalHelp (G4String newCommand) private
Definition at line 535 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 535 of file G4UIGainServer.cc
References G4String::both, G4UIcommandTree::FindPath(), G4cin, G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetTree(), G4UImanager::GetTree(), G4UIcommandTree::GetTreeEntry(), G4String::index(), G4UIcommand::List(), G4UIcommandTree::ListCurrentWithNum(), prefix, G4String::prepend(), G4String::strip(), and UI.
Referenced by GetCommand().
void G4UIGainServer::UpdateParamVal (void) private
Definition at line 889 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 889 of file G4UIGainServer.cc
References G4cout, G4endl, G4UIcommand::GetCommandPath(), newTreeParams, newTreePCP, NotifyParameterUpdate(), and previousTreeParams.
Referenced by ExecuteCommand().
void G4UIGainServer::UpdateState (void) private
Definition at line 784 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 784 of file G4UIGainServer.cc
References G4State_PreInit, G4ThreadLocal, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), and NotifyStateChange().
Referenced by ExecuteCommand().
void G4UIGainServer::WaitingConnection () private
Definition at line 399 of file G4UIGainServer.cc.
View newest version in sPHENIX GitHub at line 399 of file G4UIGainServer.cc
References caddr, close(), FatalException, G4cerr, G4endl, G4Exception(), and socketD.
Referenced by SessionStart().
Member Data Documentation
char G4UIGainServer::buf[1024] private
Definition at line 86 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 86 of file G4UIGainServer.hh
Referenced by GetCommand(), and PauseSessionStart().
struct sockaddr_in G4UIGainServer::caddr private
Definition at line 83 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 83 of file G4UIGainServer.hh
Referenced by WaitingConnection().
G4bool G4UIGainServer::iCont private
Definition at line 77 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 77 of file G4UIGainServer.hh
Referenced by G4UIGainServer(), GetCommand(), and PauseSessionStart().
G4bool G4UIGainServer::iExit private
Definition at line 76 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 76 of file G4UIGainServer.hh
Referenced by G4UIGainServer(), GetCommand(), and SessionStart().
G4String G4UIGainServer::JVersion private
Definition at line 69 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 69 of file G4UIGainServer.hh
Referenced by G4UIGainServer(), and GetCommand().
int G4UIGainServer::len private
Definition at line 84 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 84 of file G4UIGainServer.hh
std::vector<G4String> G4UIGainServer::newTreeCommands private
Definition at line 93 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 93 of file G4UIGainServer.hh
Referenced by CommandUpdated(), ExecuteCommand(), G4UIGainServer(), and GetNewTreeStructure().
std::vector<G4String> G4UIGainServer::newTreeParams private
Definition at line 95 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 95 of file G4UIGainServer.hh
Referenced by ExecuteCommand(), G4UIGainServer(), GetNewTreeValues(), and UpdateParamVal().
std::vector<G4UIcommand*> G4UIGainServer::newTreePCP private
Definition at line 97 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 97 of file G4UIGainServer.hh
Referenced by ExecuteCommand(), G4UIGainServer(), GetNewTreeValues(), and UpdateParamVal().
int G4UIGainServer::port private
Definition at line 81 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 81 of file G4UIGainServer.hh
Referenced by G4UIGainServer(), and SetUPServer().
G4String G4UIGainServer::prefix private
Definition at line 65 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 65 of file G4UIGainServer.hh
Referenced by ChangeDirectory(), GetFullPath(), ListDirectory(), ModifyPrefix(), and TerminalHelp().
std::vector<G4String> G4UIGainServer::previousTreeCommands private
Definition at line 92 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 92 of file G4UIGainServer.hh
Referenced by CommandUpdated(), ExecuteCommand(), and G4UIGainServer().
std::vector<G4String> G4UIGainServer::previousTreeParams private
Definition at line 94 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 94 of file G4UIGainServer.hh
Referenced by ExecuteCommand(), G4UIGainServer(), and UpdateParamVal().
std::vector<G4UIcommand*> G4UIGainServer::previousTreePCP private
Definition at line 96 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 96 of file G4UIGainServer.hh
Referenced by ExecuteCommand(), and G4UIGainServer().
G4String G4UIGainServer::promptCharacter private
Definition at line 66 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 66 of file G4UIGainServer.hh
Referenced by G4UIGainServer(), GetCommand(), PauseSessionStart(), and SessionStart().
int G4UIGainServer::ret private
Definition at line 85 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 85 of file G4UIGainServer.hh
struct sockaddr_in G4UIGainServer::saddr private
Definition at line 82 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UIGainServer.hh
Referenced by SetUPServer().
int G4UIGainServer::socketD[3] private
Definition at line 80 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UIGainServer.hh
Referenced by GetCommand(), PauseSessionStart(), ReceiveG4cerr(), ReceiveG4cout(), SetUPServer(), and WaitingConnection().
G4String G4UIGainServer::TVersion private
Definition at line 70 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 70 of file G4UIGainServer.hh
Referenced by G4UIGainServer(), and GetCommand().
G4UImanager* G4UIGainServer::UI private
Definition at line 67 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 67 of file G4UIGainServer.hh
Referenced by ExecuteCommand(), FindDirPath(), G4UIGainServer(), GetCommand(), NotifyCommandUpdate(), NotifyStateChange(), ShowCurrent(), TerminalHelp(), and ~G4UIGainServer().
UImode G4UIGainServer::uiMode private
Definition at line 68 of file G4UIGainServer.hh.
View newest version in sPHENIX GitHub at line 68 of file G4UIGainServer.hh
Referenced by ExecuteCommand(), G4UIGainServer(), GetCommand(), NotifyStateChange(), SendCommandProperties(), SendParameterProperties(), and ShowCurrent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/interfaces/GAG/include/G4UIGainServer.hh
geant4/tree/geant4-10.6-release/source/interfaces/GAG/src/G4UIGainServer.cc