ECCE @ EIC Software: G4AtomicTransitionManager Class Reference
G4AtomicTransitionManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AtomicTransitionManager.hh>
Public Member Functions
void Initialise ()
G4AtomicShell * Shell (G4int Z, size_t shellIndex) const
const G4FluoTransition * ReachableShell (G4int Z, size_t shellIndex) const
const G4AugerTransition * ReachableAugerShell (G4int Z, G4int shellIndex) const
G4int NumberOfShells (G4int Z) const
G4int NumberOfReachableShells (G4int Z) const
G4int NumberOfReachableAugerShells (G4int Z) const
G4double TotalRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
G4double TotalNonRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel ()
Static Public Member Functions
static G4AtomicTransitionManager * Instance ()
Private Member Functions
G4AtomicTransitionManager ()
~G4AtomicTransitionManager ()
G4AtomicTransitionManager & operator= (const G4AtomicTransitionManager &right)
G4AtomicTransitionManager (const G4AtomicTransitionManager &)
Private Attributes
std::map< G4int, std::vector
< G4AtomicShell * >, std::less
< G4int > > shellTable
std::map< G4int, std::vector
< G4FluoTransition * >
, std::less< G4int > > transitionTable
G4AugerData * augerData
G4int zMin
G4int zMax
G4int infTableLimit
G4int supTableLimit
G4bool isInitialized
G4int verboseLevel
Static Private Attributes
static G4AtomicTransitionManager * instance = 0
Detailed Description
Definition at line 59 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 59 of file G4AtomicTransitionManager.hh
Constructor & Destructor Documentation
G4AtomicTransitionManager::G4AtomicTransitionManager () private
Definition at line 52 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 52 of file G4AtomicTransitionManager.cc
Referenced by Instance().
G4AtomicTransitionManager::~G4AtomicTransitionManager () private
Definition at line 62 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 62 of file G4AtomicTransitionManager.cc
References augerData, pos(), shellTable, and transitionTable.
G4AtomicTransitionManager::G4AtomicTransitionManager (const G4AtomicTransitionManager &) private
Member Function Documentation
G4int G4AtomicTransitionManager::GetVerboseLevel () inline
Definition at line 115 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AtomicTransitionManager.hh
References verboseLevel.
void G4AtomicTransitionManager::Initialise ()
Definition at line 285 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 285 of file G4AtomicTransitionManager.cc
References augerData, G4EmParameters::BeardenFluoDir(), G4InuclSpecialFunctions::bindingEnergy(), G4ShellData::BindingEnergy(), infTableLimit, G4EmParameters::Instance(), isInitialized, G4ShellData::LoadData(), G4FluoData::LoadData(), G4ShellData::NumberOfShells(), G4FluoData::NumberOfTransitions(), G4ShellData::ShellId(), shellTable, G4FluoData::StartShellEnergy(), G4FluoData::StartShellId(), G4FluoData::StartShellProb(), supTableLimit, transitionTable, G4FluoData::VacancyId(), Z, zMax, and zMin.
Referenced by G4LivermoreIonisationModel::Initialise(), G4UAtomicDeexcitation::InitialiseForNewRun(), and G4PenelopeOscillatorManager::ReadElementData().
G4AtomicTransitionManager * G4AtomicTransitionManager::Instance (void) static
Definition at line 44 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 44 of file G4AtomicTransitionManager.cc
References G4AtomicTransitionManager(), and instance.
Referenced by G4eIonisationSpectrum::AverageEnergy(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4LivermoreIonisationCrossSection::G4LivermoreIonisationCrossSection(), G4LivermoreIonisationModel::G4LivermoreIonisationModel(), G4OrlicLiXsModel::G4OrlicLiXsModel(), G4PenelopeComptonModel::G4PenelopeComptonModel(), G4PenelopeIonisationCrossSection::G4PenelopeIonisationCrossSection(), G4PenelopePhotoElectricModel::G4PenelopePhotoElectricModel(), G4UAtomicDeexcitation::G4UAtomicDeexcitation(), G4AtomicDeexcitation::GenerateAuger(), G4AtomicDeexcitation::GenerateFluorescence(), G4hImpactIonisation::PostStepDoIt(), G4eIonisationSpectrum::Probability(), G4PenelopeOscillatorManager::ReadElementData(), G4eIonisationSpectrum::SampleEnergy(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), and G4AtomicDeexcitation::SelectTypeOfTransition().
G4int G4AtomicTransitionManager::NumberOfReachableAugerShells (G4int Z) const
Definition at line 216 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 216 of file G4AtomicTransitionManager.cc
References augerData, and G4AugerData::NumberOfVacancies().
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
G4int G4AtomicTransitionManager::NumberOfReachableShells (G4int Z) const
Definition at line 192 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 192 of file G4AtomicTransitionManager.cc
References FatalException, G4Exception(), pos(), and transitionTable.
Referenced by G4AtomicDeexcitation::GenerateFluorescence(), G4UAtomicDeexcitation::GenerateFluorescence(), G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
G4int G4AtomicTransitionManager::NumberOfShells (G4int Z) const
Definition at line 170 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 170 of file G4AtomicTransitionManager.cc
References FatalException, G4Exception(), pos(), shellTable, and Z.
Referenced by G4LivermoreIonisationModel::ComputeDEDXPerVolume(), G4LivermoreIonisationCrossSection::CrossSection(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeIonisationCrossSection::GetCrossSection(), G4LivermoreIonisationCrossSection::GetCrossSection(), G4PenelopeOscillatorManager::ReadElementData(), and G4PenelopePhotoElectricModel::SampleSecondaries().
G4AtomicTransitionManager& G4AtomicTransitionManager::operator= (const G4AtomicTransitionManager & right) private
const G4AugerTransition * G4AtomicTransitionManager::ReachableAugerShell (G4int Z, G4int shellIndex) const
Definition at line 164 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 164 of file G4AtomicTransitionManager.cc
References augerData, and G4AugerData::GetAugerTransition().
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
const G4FluoTransition * G4AtomicTransitionManager::ReachableShell (G4int Z, size_t shellIndex) const
Definition at line 135 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 135 of file G4AtomicTransitionManager.cc
References FatalException, G4Exception(), pos(), transitionTable, and v.
Referenced by G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
void G4AtomicTransitionManager::SetVerboseLevel (G4int vl) inline
Definition at line 114 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AtomicTransitionManager.hh
References verboseLevel.
G4AtomicShell * G4AtomicTransitionManager::Shell (G4int Z, size_t shellIndex) const
Definition at line 94 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 94 of file G4AtomicTransitionManager.cc
References FatalException, G4Exception(), JustWarning, pos(), shellTable, v, and verboseLevel.
Referenced by G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4OrlicLiXsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4UAtomicDeexcitation::GetAtomicShell(), G4hImpactIonisation::PostStepDoIt(), G4PenelopeOscillatorManager::ReadElementData(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), and G4PenelopeIonisationModel::SampleSecondaries().
G4double G4AtomicTransitionManager::TotalNonRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
Definition at line 265 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 265 of file G4AtomicTransitionManager.cc
References FatalException, G4Exception(), and TotalRadiativeTransitionProbability().
G4double G4AtomicTransitionManager::TotalRadiativeTransitionProbability (G4int Z, size_t shellIndex) const
Definition at line 221 of file G4AtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 221 of file G4AtomicTransitionManager.cc
References FatalException, G4Exception(), pos(), G4FluoTransition::TransitionProbabilities(), transitionTable, and v.
Referenced by TotalNonRadiativeTransitionProbability().
Member Data Documentation
G4AugerData* G4AtomicTransitionManager::augerData private
Definition at line 139 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 139 of file G4AtomicTransitionManager.hh
Referenced by Initialise(), NumberOfReachableAugerShells(), ReachableAugerShell(), and ~G4AtomicTransitionManager().
G4int G4AtomicTransitionManager::infTableLimit private
Definition at line 148 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 148 of file G4AtomicTransitionManager.hh
Referenced by Initialise().
G4AtomicTransitionManager * G4AtomicTransitionManager::instance = 0 static private
Definition at line 127 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 127 of file G4AtomicTransitionManager.hh
Referenced by Instance().
G4bool G4AtomicTransitionManager::isInitialized private
Definition at line 151 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 151 of file G4AtomicTransitionManager.hh
Referenced by Initialise().
std::map<G4int,std::vector<G4AtomicShell*>,std::less<G4int> > G4AtomicTransitionManager::shellTable private
Definition at line 131 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 131 of file G4AtomicTransitionManager.hh
Referenced by Initialise(), NumberOfShells(), Shell(), and ~G4AtomicTransitionManager().
G4int G4AtomicTransitionManager::supTableLimit private
Definition at line 149 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4AtomicTransitionManager.hh
Referenced by Initialise().
std::map<G4int,std::vector<G4FluoTransition*>,std::less<G4int> > G4AtomicTransitionManager::transitionTable private
Definition at line 135 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 135 of file G4AtomicTransitionManager.hh
Referenced by Initialise(), NumberOfReachableShells(), ReachableShell(), TotalRadiativeTransitionProbability(), and ~G4AtomicTransitionManager().
G4int G4AtomicTransitionManager::verboseLevel private
Definition at line 153 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4AtomicTransitionManager.hh
Referenced by GetVerboseLevel(), SetVerboseLevel(), and Shell().
G4int G4AtomicTransitionManager::zMax private
Definition at line 144 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 144 of file G4AtomicTransitionManager.hh
Referenced by Initialise().
G4int G4AtomicTransitionManager::zMin private
Definition at line 143 of file G4AtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 143 of file G4AtomicTransitionManager.hh
Referenced by Initialise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AtomicTransitionManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4AtomicTransitionManager.cc