ECCE @ EIC Software: G4FastSimulationPhysics Class Reference
G4FastSimulationPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4FastSimulationPhysics.hh>
Public Member Functions
G4FastSimulationPhysics (const G4String &name="FastSimP")
virtual ~G4FastSimulationPhysics ()
void ActivateFastSimulation (const G4String &particleName)
void ActivateFastSimulation (const G4String &particleName, const G4String &parallelGeometryName)
void BeVerbose ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
G4FastSimulationPhysics & operator= (const G4FastSimulationPhysics &right)
G4FastSimulationPhysics (const G4FastSimulationPhysics &)
Private Attributes
std::vector< G4String > fParticlesUnderFastSimulation
std::vector< G4String > fGeometries
G4bool fVerbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 41 of file G4FastSimulationPhysics.hh.
View newest version in sPHENIX GitHub at line 41 of file G4FastSimulationPhysics.hh
Constructor & Destructor Documentation
G4FastSimulationPhysics::G4FastSimulationPhysics (const G4String & name = "FastSimP")
Definition at line 54 of file G4FastSimulationPhysics.cc.
View newest version in sPHENIX GitHub at line 54 of file G4FastSimulationPhysics.cc
G4FastSimulationPhysics::~G4FastSimulationPhysics () virtual
Definition at line 61 of file G4FastSimulationPhysics.cc.
View newest version in sPHENIX GitHub at line 61 of file G4FastSimulationPhysics.cc
G4FastSimulationPhysics::G4FastSimulationPhysics (const G4FastSimulationPhysics &) private
Member Function Documentation
void G4FastSimulationPhysics::ActivateFastSimulation (const G4String & particleName)
Definition at line 66 of file G4FastSimulationPhysics.cc.
View newest version in sPHENIX GitHub at line 66 of file G4FastSimulationPhysics.cc
References fGeometries, and fParticlesUnderFastSimulation.
Referenced by main().
void G4FastSimulationPhysics::ActivateFastSimulation (const G4String & particleName, const G4String & parallelGeometryName)
Definition at line 74 of file G4FastSimulationPhysics.cc.
View newest version in sPHENIX GitHub at line 74 of file G4FastSimulationPhysics.cc
References fGeometries, and fParticlesUnderFastSimulation.
void G4FastSimulationPhysics::BeVerbose () inline
Definition at line 59 of file G4FastSimulationPhysics.hh.
View newest version in sPHENIX GitHub at line 59 of file G4FastSimulationPhysics.hh
References fVerbose.
Referenced by main().
void G4FastSimulationPhysics::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 82 of file G4FastSimulationPhysics.cc.
View newest version in sPHENIX GitHub at line 82 of file G4FastSimulationPhysics.cc
void G4FastSimulationPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 87 of file G4FastSimulationPhysics.cc.
View newest version in sPHENIX GitHub at line 87 of file G4FastSimulationPhysics.cc
References G4FastSimulationHelper::ActivateFastSimulation(), fGeometries, fParticlesUnderFastSimulation, fVerbose, G4cout, G4endl, G4VPhysicalVolume::GetName(), G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4FastSimulationManagerProcess::GetWorldVolume(), particle, and G4ProcessVector::size().
G4FastSimulationPhysics& G4FastSimulationPhysics::operator= (const G4FastSimulationPhysics & right) private
Member Data Documentation
std::vector< G4String > G4FastSimulationPhysics::fGeometries private
Definition at line 80 of file G4FastSimulationPhysics.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FastSimulationPhysics.hh
Referenced by ActivateFastSimulation(), and ConstructProcess().
std::vector< G4String > G4FastSimulationPhysics::fParticlesUnderFastSimulation private
Definition at line 78 of file G4FastSimulationPhysics.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FastSimulationPhysics.hh
Referenced by ActivateFastSimulation(), and ConstructProcess().
G4bool G4FastSimulationPhysics::fVerbose private
Definition at line 83 of file G4FastSimulationPhysics.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FastSimulationPhysics.hh
Referenced by BeVerbose(), and ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4FastSimulationPhysics.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/src/G4FastSimulationPhysics.cc