ECCE @ EIC Software: G4AttDefStore Namespace Reference
G4AttDefStore Namespace Reference
Functions
std::map< G4String, G4AttDef > * GetInstance (const G4String &storeKey, G4bool &isNew)
G4bool GetStoreKey (const std::map< G4String, G4AttDef > *definitions, G4String &key)
Variables
std::map< G4String, std::map
< G4String, G4AttDef > * > * m_defsmaps = 0
G4Mutex mutex = G4MUTEX_INITIALIZER
Function Documentation
std::map< G4String, G4AttDef > * G4AttDefStore::GetInstance (const G4String & storeKey, G4bool & isNew)
Definition at line 40 of file G4AttDefStore.cc.
View newest version in sPHENIX GitHub at line 40 of file G4AttDefStore.cc
References m_defsmaps.
Referenced by RE01TrackerHit::GetAttDefs(), SensitiveDetectorHit::GetAttDefs(), RE01CalorimeterHit::GetAttDefs(), RE01Trajectory::GetAttDefs(), XAluminumElectrodeHit::GetAttDefs(), B5HodoscopeHit::GetAttDefs(), B5HadCalorimeterHit::GetAttDefs(), B5DriftChamberHit::GetAttDefs(), B5EmCalorimeterHit::GetAttDefs(), G4TrajectoriesModel::GetAttDefs(), F04TrajectoryPoint::GetAttDefs(), WLSTrajectoryPoint::GetAttDefs(), G4SmoothTrajectoryPoint::GetAttDefs(), G4TrajectoryPoint::GetAttDefs(), RE04TrajectoryPoint::GetAttDefs(), G4RichTrajectory::GetAttDefs(), F04Trajectory::GetAttDefs(), WLSTrajectory::GetAttDefs(), G4RichTrajectoryPoint::GetAttDefs(), G4SmoothTrajectory::GetAttDefs(), G4Trajectory::GetAttDefs(), RE04Trajectory::GetAttDefs(), and G4PhysicalVolumeModel::GetAttDefs().
G4bool G4AttDefStore::GetStoreKey (const std::map< G4String, G4AttDef > * definitions, G4String & key)
Definition at line 69 of file G4AttDefStore.cc.
View newest version in sPHENIX GitHub at line 69 of file G4AttDefStore.cc
References m_defsmaps.
Referenced by operator<<().
Variable Documentation
std::map< G4String, std::map< G4String, G4AttDef > * > * G4AttDefStore::m_defsmaps = 0
Definition at line 35 of file G4AttDefStore.cc.
View newest version in sPHENIX GitHub at line 35 of file G4AttDefStore.cc
Referenced by GetInstance(), and GetStoreKey().
G4Mutex G4AttDefStore::mutex = G4MUTEX_INITIALIZER
Definition at line 37 of file G4AttDefStore.cc.
View newest version in sPHENIX GitHub at line 37 of file G4AttDefStore.cc
Referenced by G4EnvSettings::insert().