ECCE @ EIC Software: Analysis Class Reference
Analysis Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/include/Analysis.hh>
Public Member Functions
~Analysis ()
void Update ()
void Clear ()
void Save (const G4String &fname)
void FillIncident (const G4ThreeVector &p)
void FillDose (const G4ThreeVector &p, G4double dedx)
void ClearIncidentFlag ()
~Analysis ()
void Book ()
void EndOfRun ()
void Update ()
void Clear ()
void Save (const G4String &fname)
void Close (G4bool reset=true)
void FillIncident (const G4ThreeVector &p)
void FillDose (const G4ThreeVector &p, G4double dedx)
void ClearIncidentFlag ()
~Analysis ()
void Book ()
void EndOfRun ()
void OpenFile (const G4String &fname)
void Save ()
void Close (G4bool reset=true)
void FillIncident (const G4ThreeVector &p)
void FillDose (const G4ThreeVector &p, G4double dedx)
void ClearIncidentFlag ()
void SetUseNtuple (G4bool useNtuple)
void SetMergeNtuple (G4bool mergeNtuple)
Static Public Member Functions
static Analysis * GetAnalysis ()
static Analysis * GetAnalysis ()
static Analysis * GetAnalysis ()
Private Member Functions
Analysis ()
DISALLOW_COPY_AND_ASSIGN (Analysis)
Analysis ()
DISALLOW_COPY_AND_ASSIGN (Analysis)
Analysis ()
DISALLOW_COPY_AND_ASSIGN (Analysis)
Private Attributes
TH2D * fincident_map
TH1D * fincident_x_hist
TH2D * fdose_map
TH1D * fdose_hist
G4int fincident_x_hist
G4int fincident_map
G4int fdose_hist
G4int fdose_map
G4int fdose_prof
G4int fdose_map_prof
G4int fdose_map3d
G4bool fUseNtuple
G4bool fMergeNtuple
Static Private Attributes
static G4ThreadLocal G4int fincidentFlag = false
Detailed Description
Definition at line 42 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 42 of file Analysis.hh
Constructor & Destructor Documentation
Analysis::~Analysis ()
Definition at line 81 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 81 of file Analysis.cc
References fdose_hist, fdose_map, fincident_map, and fincident_x_hist.
Analysis::Analysis () private
Definition at line 51 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 51 of file Analysis.cc
References fdose_hist, fdose_map, fincident_map, fincident_x_hist, GetXaxis(), GetYaxis(), rootm, SetFillColor(), SetStats(), and SetTitle().
Referenced by GetAnalysis().
Analysis::~Analysis ()
Analysis::Analysis () private
Analysis::~Analysis ()
Analysis::Analysis () private
Member Function Documentation
void Analysis::Book ()
Definition at line 64 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 64 of file Analysis.cc
References cm, G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateH3(), G4VAnalysisManager::CreateP1(), G4VAnalysisManager::CreateP2(), fdose_hist, fdose_map, fdose_map3d, fdose_map_prof, fdose_prof, fincident_map, fincident_x_hist, G4ToolsAnalysisManager::Instance(), and MeV.
Referenced by RunActionMaster::BeginOfRunAction(), RunAction::RunAction(), and RunActionMaster::RunActionMaster().
void Analysis::Book ()
void Analysis::Clear ()
Definition at line 96 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 96 of file Analysis.cc
References fdose_hist, fdose_map, fincident_map, fincident_x_hist, and Reset().
void Analysis::Clear ()
void Analysis::ClearIncidentFlag () inline
Definition at line 71 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 71 of file Analysis.hh
References fincidentFlag.
void Analysis::ClearIncidentFlag ()
void Analysis::ClearIncidentFlag ()
void Analysis::Close (G4bool reset = true)
void Analysis::Close (G4bool reset = true)
Definition at line 116 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 116 of file Analysis.cc
References G4VAnalysisManager::CloseFile(), and G4ToolsAnalysisManager::Instance().
Referenced by Save().
Analysis::DISALLOW_COPY_AND_ASSIGN (Analysis) private
Analysis::DISALLOW_COPY_AND_ASSIGN (Analysis) private
Analysis::DISALLOW_COPY_AND_ASSIGN (Analysis) private
void Analysis::EndOfRun ()
void Analysis::EndOfRun ()
void Analysis::FillDose (const G4ThreeVector & p, G4double dedx)
Definition at line 136 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 136 of file Analysis.cc
References kdfinder::abs(), cm, fdose_hist, fdose_map, Fill(), GeV, mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void Analysis::FillDose (const G4ThreeVector & p, G4double dedx)
void Analysis::FillDose (const G4ThreeVector & p, G4double dedx)
void Analysis::FillIncident (const G4ThreeVector & p)
Definition at line 125 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 125 of file Analysis.cc
References cm, Fill(), fincident_map, fincident_x_hist, fincidentFlag, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
void Analysis::FillIncident (const G4ThreeVector & p)
void Analysis::FillIncident (const G4ThreeVector & p)
static Analysis* Analysis::GetAnalysis () static
static Analysis* Analysis::GetAnalysis () static
Analysis * Analysis::GetAnalysis () static
Definition at line 44 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 44 of file Analysis.cc
References Analysis(), and the_analysis.
Referenced by RunActionMaster::BeginOfRunAction(), RunActionMaster::EndOfRunAction(), VoxelSD::ProcessHits(), RunAction::RunAction(), and RunActionMaster::RunActionMaster().
void Analysis::OpenFile (const G4String & fname)
Definition at line 110 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 110 of file Analysis.cc
References G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::OpenFile().
void Analysis::Save (const G4String & fname)
Definition at line 107 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 107 of file Analysis.cc
References Close(), fdose_hist, fdose_map, file, fincident_map, fincident_x_hist, and rootm.
void Analysis::Save ()
Definition at line 118 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 118 of file Analysis.cc
References G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
void Analysis::Save (const G4String & fname)
void Analysis::SetMergeNtuple (G4bool mergeNtuple) inline
Definition at line 65 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 65 of file Analysis.hh
References fMergeNtuple, G4cout, and G4endl.
Referenced by RunAction::RunAction(), and RunActionMaster::RunActionMaster().
void Analysis::SetUseNtuple (G4bool useNtuple) inline
Definition at line 60 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 60 of file Analysis.hh
References fUseNtuple, G4cout, and G4endl.
Referenced by RunAction::RunAction(), and RunActionMaster::RunActionMaster().
void Analysis::Update ()
Definition at line 90 of file Analysis.cc.
View newest version in sPHENIX GitHub at line 90 of file Analysis.cc
void Analysis::Update ()
Member Data Documentation
G4int Analysis::fdose_hist private
Definition at line 65 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 65 of file Analysis.hh
Referenced by Analysis(), Book(), Clear(), FillDose(), Save(), and ~Analysis().
G4int Analysis::fdose_hist private
Definition at line 67 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 67 of file Analysis.hh
G4int Analysis::fdose_map private
Definition at line 64 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 64 of file Analysis.hh
Referenced by Analysis(), Book(), Clear(), FillDose(), Save(), and ~Analysis().
G4int Analysis::fdose_map private
Definition at line 68 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 68 of file Analysis.hh
G4int Analysis::fdose_map3d private
Definition at line 71 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 71 of file Analysis.hh
Referenced by Book().
G4int Analysis::fdose_map_prof private
Definition at line 70 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 70 of file Analysis.hh
Referenced by Book().
G4int Analysis::fdose_prof private
Definition at line 69 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 69 of file Analysis.hh
Referenced by Book().
G4int Analysis::fincident_map private
Definition at line 61 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 61 of file Analysis.hh
Referenced by Analysis(), Book(), Clear(), FillIncident(), Save(), and ~Analysis().
G4int Analysis::fincident_map private
Definition at line 66 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 66 of file Analysis.hh
G4int Analysis::fincident_x_hist private
Definition at line 62 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 62 of file Analysis.hh
Referenced by Analysis(), Book(), Clear(), FillIncident(), Save(), and ~Analysis().
G4int Analysis::fincident_x_hist private
Definition at line 65 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 65 of file Analysis.hh
G4ThreadLocal G4int Analysis::fincidentFlag = false static private
Definition at line 67 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 67 of file Analysis.hh
Referenced by ClearIncidentFlag(), and FillIncident().
G4bool Analysis::fMergeNtuple private
Definition at line 75 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 75 of file Analysis.hh
Referenced by SetMergeNtuple().
G4bool Analysis::fUseNtuple private
Definition at line 74 of file Analysis.hh.
View newest version in sPHENIX GitHub at line 74 of file Analysis.hh
Referenced by SetUseNtuple().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/include/Analysis.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/include/Analysis.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/include/Analysis.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/src/Analysis.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/src/Analysis.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/src/Analysis.cc