ECCE @ EIC Software: G4NavigationHistory Class Reference
G4NavigationHistory Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationHistory.hh>
Public Member Functions
G4NavigationHistory ()
~G4NavigationHistory ()
G4NavigationHistory (const G4NavigationHistory &h)
G4NavigationHistory & operator= (const G4NavigationHistory &h)
void Reset ()
void Clear ()
void SetFirstEntry (G4VPhysicalVolume *pVol)
const G4AffineTransform & GetTopTransform () const
const G4AffineTransform * GetPtrTopTransform () const
G4int GetTopReplicaNo () const
EVolume GetTopVolumeType () const
G4VPhysicalVolume * GetTopVolume () const
size_t GetDepth () const
size_t GetMaxDepth () const
const G4AffineTransform & GetTransform (G4int n) const
G4int GetReplicaNo (G4int n) const
EVolume GetVolumeType (G4int n) const
G4VPhysicalVolume * GetVolume (G4int n) const
void NewLevel (G4VPhysicalVolume *pNewMother, EVolume vType=kNormal, G4int nReplica=-1)
void BackLevel ()
void BackLevel (G4int n)
void * operator new (size_t)
void operator delete (void *aHistory)
Private Member Functions
void EnlargeHistory ()
Private Attributes
std::vector< G4NavigationLevel > * fNavHistory
size_t fStackDepth
Friends
std::ostream & operator<< (std::ostream &os, const G4NavigationHistory &h)
Detailed Description
Definition at line 52 of file G4NavigationHistory.hh.
View newest version in sPHENIX GitHub at line 52 of file G4NavigationHistory.hh
Constructor & Destructor Documentation
G4NavigationHistory::G4NavigationHistory ()
Definition at line 41 of file G4NavigationHistory.cc.
View newest version in sPHENIX GitHub at line 41 of file G4NavigationHistory.cc
References Clear(), fNavHistory, G4NavigationHistoryPool::GetInstance(), and G4NavigationHistoryPool::GetLevels().
G4NavigationHistory::~G4NavigationHistory ()
Definition at line 63 of file G4NavigationHistory.cc.
View newest version in sPHENIX GitHub at line 63 of file G4NavigationHistory.cc
References G4NavigationHistoryPool::DeRegister(), fNavHistory, and G4NavigationHistoryPool::GetInstance().
G4NavigationHistory::G4NavigationHistory (const G4NavigationHistory & h)
Definition at line 48 of file G4NavigationHistory.cc.
View newest version in sPHENIX GitHub at line 48 of file G4NavigationHistory.cc
References fNavHistory, fStackDepth, G4NavigationHistoryPool::GetInstance(), G4NavigationHistoryPool::GetLevels(), and GetMaxDepth().
Member Function Documentation
void G4NavigationHistory::BackLevel () inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), and G4ITNavigator1::LocateGlobalPointAndSetup().
void G4NavigationHistory::BackLevel (G4int n) inline
void G4NavigationHistory::Clear () inline
Referenced by G4NavigationHistory().
void G4NavigationHistory::EnlargeHistory () inline private
size_t G4NavigationHistory::GetDepth () const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4FastTrack::FRecordsAffineTransformation(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), operator<<(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), PHG4EICMvtxSteppingAction::UserSteppingAction(), and PHG4MvtxSteppingAction::UserSteppingAction().
size_t G4NavigationHistory::GetMaxDepth () const inline
Referenced by G4NavigationHistory().
const G4AffineTransform* G4NavigationHistory::GetPtrTopTransform () const inline
G4int G4NavigationHistory::GetReplicaNo (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), operator<<(), G4ITNavigator1::SetupHierarchy(), and G4Navigator::SetupHierarchy().
G4int G4NavigationHistory::GetTopReplicaNo () const inline
Referenced by G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), G4Navigator::LocateGlobalPointAndSetup(), and G4ITNavigator1::LocateGlobalPointAndSetup().
const G4AffineTransform& G4NavigationHistory::GetTopTransform () const inline
Referenced by G4RegularNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStepLog(), G4Navigator::ComputeStepLog(), F04ElementField::Construct(), G4DrawVoxels::DrawVoxels(), G4TouchableHistory::G4TouchableHistory(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4Navigator::GetGlobalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), ExN04CalorimeterSD::ProcessHits(), ScreenSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), RE01CalorimeterSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CCaloSD::SetToLocal(), PHG4SteppingAction::StoreLocalCoordinate(), and PHG4OuterHcalSteppingAction::UserSteppingAction().
G4VPhysicalVolume* G4NavigationHistory::GetTopVolume () const inline
Referenced by G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4Navigator::GetGlobalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), and G4Navigator::RecheckDistanceToCurrentBoundary().
EVolume G4NavigationHistory::GetTopVolumeType () const inline
Referenced by G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointWithinVolume(), and G4Navigator::RecheckDistanceToCurrentBoundary().
const G4AffineTransform& G4NavigationHistory::GetTransform (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4FastTrack::FRecordsAffineTransformation(), G4TouchableHistory::GetRotation(), and G4TouchableHistory::GetTranslation().
G4VPhysicalVolume* G4NavigationHistory::GetVolume (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), G4FastTrack::FRecordsAffineTransformation(), operator<<(), G4ITNavigator1::SetupHierarchy(), and G4Navigator::SetupHierarchy().
EVolume G4NavigationHistory::GetVolumeType (G4int n) const inline
Referenced by G4ReplicaNavigation::BackLocate(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), operator<<(), G4ITNavigator1::SetupHierarchy(), and G4Navigator::SetupHierarchy().
void G4NavigationHistory::NewLevel (G4VPhysicalVolume * pNewMother, EVolume vType = kNormal, G4int nReplica = -1) inline
Referenced by G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), and G4ITNavigator1::LocateGlobalPointAndSetup().
void G4NavigationHistory::operator delete (void * aHistory) inline
void* G4NavigationHistory::operator new (size_t) inline
G4NavigationHistory& G4NavigationHistory::operator= (const G4NavigationHistory & h) inline
void G4NavigationHistory::Reset () inline
void G4NavigationHistory::SetFirstEntry (G4VPhysicalVolume * pVol) inline
Referenced by G4TouchableHistory::G4TouchableHistory().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4NavigationHistory & h) friend
Definition at line 69 of file G4NavigationHistory.cc.
View newest version in sPHENIX GitHub at line 69 of file G4NavigationHistory.cc
Member Data Documentation
std::vector<G4NavigationLevel>* G4NavigationHistory::fNavHistory private
Definition at line 144 of file G4NavigationHistory.hh.
View newest version in sPHENIX GitHub at line 144 of file G4NavigationHistory.hh
Referenced by G4NavigationHistory(), and ~G4NavigationHistory().
size_t G4NavigationHistory::fStackDepth private
Definition at line 147 of file G4NavigationHistory.hh.
View newest version in sPHENIX GitHub at line 147 of file G4NavigationHistory.hh
Referenced by G4NavigationHistory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationHistory.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4NavigationHistory.cc