ECCE @ EIC Software: G4ITTrackingInteractivity Class Reference
G4ITTrackingInteractivity Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTrackingInteractivity.hh>
Public Member Functions
G4ITTrackingInteractivity (G4VITSteppingVerbose *verbose=0)
virtual ~G4ITTrackingInteractivity ()
virtual void Initialize ()
virtual void StartTracking (G4Track *)
virtual void AppendStep (G4Track *, G4Step *)
virtual void EndTracking (G4Track *)
virtual void Finalize ()
virtual void TrackBanner (G4Track *, const G4String &message="")
void SetVerbose (int flag)
G4int GetVerboseLevel () const
void SetSteppingVerboseLevel (G4int level)
G4int GetSteppingVerboseLevel () const
G4VITSteppingVerbose * GetSteppingVerbose ()
void SetSteppingVerbose (G4VITSteppingVerbose *verbose)
Protected Attributes
int fVerboseLevel
Private Attributes
G4VITSteppingVerbose * fpVerbose
Detailed Description
Definition at line 57 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ITTrackingInteractivity.hh
Constructor & Destructor Documentation
G4ITTrackingInteractivity::G4ITTrackingInteractivity (G4VITSteppingVerbose * verbose = 0)
Definition at line 63 of file G4ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ITTrackingInteractivity.cc
References fpVerbose, and fVerboseLevel.
virtual G4ITTrackingInteractivity::~G4ITTrackingInteractivity () inline virtual
Definition at line 65 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ITTrackingInteractivity.hh
Member Function Documentation
virtual void G4ITTrackingInteractivity::AppendStep (G4Track * , G4Step *) inline virtual
Reimplemented in ITTrackingInteractivity, ITTrackingInteractivity, and ITTrackingInteractivity.
Definition at line 80 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ITTrackingInteractivity.hh
Referenced by G4ITTrackingManager::AppendStep().
virtual void G4ITTrackingInteractivity::EndTracking (G4Track *) inline virtual
Reimplemented in ITTrackingInteractivity, ITTrackingInteractivity, and ITTrackingInteractivity.
Definition at line 86 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ITTrackingInteractivity.hh
Referenced by G4ITTrackingManager::EndTracking(), and G4ITTrackingManager::EndTrackingWOKill().
virtual void G4ITTrackingInteractivity::Finalize () inline virtual
Reimplemented in ITTrackingInteractivity, ITTrackingInteractivity, and ITTrackingInteractivity.
Definition at line 91 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ITTrackingInteractivity.hh
Referenced by G4Scheduler::Process().
G4VITSteppingVerbose* G4ITTrackingInteractivity::GetSteppingVerbose () inline
Definition at line 112 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ITTrackingInteractivity.hh
References fpVerbose.
Referenced by G4ITTrackingManager::EndTracking(), G4ITTrackingManager::EndTrackingWOKill(), G4ITStepProcessor::Initialize(), and G4ITTrackingManager::StartTracking().
G4int G4ITTrackingInteractivity::GetSteppingVerboseLevel () const
Definition at line 91 of file G4ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ITTrackingInteractivity.cc
References fpVerbose, and G4VITSteppingVerbose::GetVerbose().
G4int G4ITTrackingInteractivity::GetVerboseLevel () const inline
Definition at line 104 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ITTrackingInteractivity.hh
References fVerboseLevel.
virtual void G4ITTrackingInteractivity::Initialize () inline virtual
Reimplemented in ITTrackingInteractivity, ITTrackingInteractivity, and ITTrackingInteractivity.
Definition at line 70 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ITTrackingInteractivity.hh
Referenced by G4Scheduler::Process().
void G4ITTrackingInteractivity::SetSteppingVerbose (G4VITSteppingVerbose * verbose) inline
Definition at line 117 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ITTrackingInteractivity.hh
References fpVerbose.
void G4ITTrackingInteractivity::SetSteppingVerboseLevel (G4int level)
Definition at line 76 of file G4ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ITTrackingInteractivity.cc
References fpVerbose, and G4VITSteppingVerbose::SetVerbose().
void G4ITTrackingInteractivity::SetVerbose (int flag) inline
Definition at line 99 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ITTrackingInteractivity.hh
References fVerboseLevel.
virtual void G4ITTrackingInteractivity::StartTracking (G4Track *) inline virtual
Reimplemented in ITTrackingInteractivity, ITTrackingInteractivity, and ITTrackingInteractivity.
Definition at line 75 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ITTrackingInteractivity.hh
Referenced by G4ITTrackingManager::StartTracking().
void G4ITTrackingInteractivity::TrackBanner (G4Track * track, const G4String & message = "") virtual
Definition at line 42 of file G4ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ITTrackingInteractivity.cc
References G4cout, G4endl, G4Track::GetDefinition(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4Track::GetTrackID(), and message().
Referenced by ITTrackingInteractivity::EndTracking(), and ITTrackingInteractivity::StartTracking().
Member Data Documentation
G4VITSteppingVerbose* G4ITTrackingInteractivity::fpVerbose private
Definition at line 123 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ITTrackingInteractivity.hh
Referenced by G4ITTrackingInteractivity(), GetSteppingVerbose(), GetSteppingVerboseLevel(), SetSteppingVerbose(), and SetSteppingVerboseLevel().
int G4ITTrackingInteractivity::fVerboseLevel protected
Definition at line 60 of file G4ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ITTrackingInteractivity.hh
Referenced by ITTrackingInteractivity::EndTracking(), G4ITTrackingInteractivity(), GetVerboseLevel(), ITTrackingInteractivity::Initialize(), ITTrackingInteractivity::ITTrackingInteractivity(), SetVerbose(), and ITTrackingInteractivity::StartTracking().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTrackingInteractivity.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITTrackingInteractivity.cc