ECCE @ EIC Software: GFlashParticleBounds Class Reference
GFlashParticleBounds Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashParticleBounds.hh>
Public Member Functions
GFlashParticleBounds ()
~GFlashParticleBounds ()
G4double GetMinEneToParametrise (G4ParticleDefinition &particleType)
G4double GetMaxEneToParametrise (G4ParticleDefinition &particleType)
G4double GetEneToKill (G4ParticleDefinition &particleType)
void SetMinEneToParametrise (G4ParticleDefinition &particleType, G4double enemin)
void SetMaxEneToParametrise (G4ParticleDefinition &particleType, G4double enemax)
void SetEneToKill (G4ParticleDefinition &particleType, G4double enekill)
Private Attributes
G4double EMinEneToParametrise
G4double EMaxEneToParametrise
G4double EEneToKill
Detailed Description
Definition at line 46 of file GFlashParticleBounds.hh.
View newest version in sPHENIX GitHub at line 46 of file GFlashParticleBounds.hh
Constructor & Destructor Documentation
GFlashParticleBounds::GFlashParticleBounds ()
Definition at line 43 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 43 of file GFlashParticleBounds.cc
References EEneToKill, EMaxEneToParametrise, EMinEneToParametrise, and GeV.
GFlashParticleBounds::~GFlashParticleBounds ()
Definition at line 51 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 51 of file GFlashParticleBounds.cc
Member Function Documentation
G4double GFlashParticleBounds::GetEneToKill (G4ParticleDefinition & particleType)
Definition at line 104 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 104 of file GFlashParticleBounds.cc
References DBL_MAX, EEneToKill, G4Electron::ElectronDefinition(), and G4Positron::PositronDefinition().
Referenced by GFlashShowerModelMessenger::GetCurrentValue(), and GFlashShowerModel::ModelTrigger().
G4double GFlashParticleBounds::GetMaxEneToParametrise (G4ParticleDefinition & particleType)
Definition at line 92 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 92 of file GFlashParticleBounds.cc
References G4Electron::ElectronDefinition(), EMaxEneToParametrise, and G4Positron::PositronDefinition().
Referenced by GFlashShowerModelMessenger::GetCurrentValue(), and GFlashShowerModel::ModelTrigger().
G4double GFlashParticleBounds::GetMinEneToParametrise (G4ParticleDefinition & particleType)
Definition at line 80 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 80 of file GFlashParticleBounds.cc
References DBL_MAX, G4Electron::ElectronDefinition(), EMinEneToParametrise, and G4Positron::PositronDefinition().
Referenced by GFlashShowerModelMessenger::GetCurrentValue(), and GFlashShowerModel::ModelTrigger().
void GFlashParticleBounds::SetEneToKill (G4ParticleDefinition & particleType, G4double enekill)
Definition at line 72 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 72 of file GFlashParticleBounds.cc
References EEneToKill, G4Electron::ElectronDefinition(), and G4Positron::PositronDefinition().
Referenced by GFlashShowerModelMessenger::SetNewValue().
void GFlashParticleBounds::SetMaxEneToParametrise (G4ParticleDefinition & particleType, G4double enemax)
Definition at line 64 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 64 of file GFlashParticleBounds.cc
References G4Electron::ElectronDefinition(), EMaxEneToParametrise, and G4Positron::PositronDefinition().
Referenced by GFlashShowerModelMessenger::SetNewValue().
void GFlashParticleBounds::SetMinEneToParametrise (G4ParticleDefinition & particleType, G4double enemin)
Definition at line 56 of file GFlashParticleBounds.cc.
View newest version in sPHENIX GitHub at line 56 of file GFlashParticleBounds.cc
References G4Electron::ElectronDefinition(), EMinEneToParametrise, and G4Positron::PositronDefinition().
Referenced by GFlashShowerModelMessenger::SetNewValue().
Member Data Documentation
G4double GFlashParticleBounds::EEneToKill private
Definition at line 71 of file GFlashParticleBounds.hh.
View newest version in sPHENIX GitHub at line 71 of file GFlashParticleBounds.hh
Referenced by GetEneToKill(), GFlashParticleBounds(), and SetEneToKill().
G4double GFlashParticleBounds::EMaxEneToParametrise private
Definition at line 70 of file GFlashParticleBounds.hh.
View newest version in sPHENIX GitHub at line 70 of file GFlashParticleBounds.hh
Referenced by GetMaxEneToParametrise(), GFlashParticleBounds(), and SetMaxEneToParametrise().
G4double GFlashParticleBounds::EMinEneToParametrise private
Definition at line 69 of file GFlashParticleBounds.hh.
View newest version in sPHENIX GitHub at line 69 of file GFlashParticleBounds.hh
Referenced by GetMinEneToParametrise(), GFlashParticleBounds(), and SetMinEneToParametrise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashParticleBounds.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/GFlashParticleBounds.cc