ECCE @ EIC Software: ExP01PrimaryGeneratorAction Class Reference
ExP01PrimaryGeneratorAction Class Reference
Primary generator action for the persistency example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/ExP01PrimaryGeneratorAction.hh>
Public Member Functions
ExP01PrimaryGeneratorAction (ExP01DetectorConstruction *)
~ExP01PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
ExP01DetectorConstruction * fMyDetector
Detailed Description
Primary generator action for the persistency example.
Definition at line 47 of file ExP01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 47 of file ExP01PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction (ExP01DetectorConstruction * myDC)
Definition at line 46 of file ExP01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 46 of file ExP01PrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), GeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), and G4ParticleGun::SetParticleMomentumDirection().
ExP01PrimaryGeneratorAction::~ExP01PrimaryGeneratorAction ()
Definition at line 66 of file ExP01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 66 of file ExP01PrimaryGeneratorAction.cc
References fParticleGun.
Member Function Documentation
void ExP01PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 73 of file ExP01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 73 of file ExP01PrimaryGeneratorAction.cc
References cm, fMyDetector, fParticleGun, G4ParticleGun::GeneratePrimaryVertex(), ExP01DetectorConstruction::GetWorldFullLength(), and G4VPrimaryGenerator::SetParticlePosition().
Member Data Documentation
ExP01DetectorConstruction* ExP01PrimaryGeneratorAction::fMyDetector private
Definition at line 58 of file ExP01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file ExP01PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4ParticleGun* ExP01PrimaryGeneratorAction::fParticleGun private
Definition at line 57 of file ExP01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file ExP01PrimaryGeneratorAction.hh
Referenced by ExP01PrimaryGeneratorAction(), GeneratePrimaries(), and ~ExP01PrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/ExP01PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/src/ExP01PrimaryGeneratorAction.cc