ECCE @ EIC Software: boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key > Class Template Reference
boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key > Class Template Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/source/boost/indexing_suite.hpp>
Public Member Functions
template<class Class >
void visit (Class &cl) const
Static Public Member Functions
template<class Class >
static void extension_def (Class &cl)
Private Types
typedef mpl::or_< mpl::bool_
< NoProxy >, mpl::not_
< is_class< Data > > > no_proxy
typedef
detail::container_element
< Container, Index,
DerivedPolicies > container_element_t
typedef return_internal_reference return_policy
typedef mpl::if_< no_proxy,
iterator< Container >
, iterator< Container,
return_policy > >::type def_iterator
typedef mpl::if_< no_proxy,
detail::no_proxy_helper
< Container, DerivedPolicies,
container_element_t, Index >
, detail::proxy_helper
< Container, DerivedPolicies,
container_element_t, Index >
>::type proxy_handler
typedef mpl::if_< mpl::bool_
< NoSlice >
, detail::no_slice_helper
< Container, DerivedPolicies,
proxy_handler, Data, Index >
, detail::slice_helper
< Container, DerivedPolicies,
proxy_handler, Data, Index >
>::type slice_handler
Static Private Member Functions
static object base_get_item (back_reference< Container & > container, PyObject *i)
static void base_set_item (Container &container, PyObject *i, PyObject *v)
static void base_delete_item (Container &container, PyObject *i)
static size_t base_size (Container &container)
static bool base_contains (Container &container, PyObject *key)
Detailed Description
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type>
class boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >
Definition at line 106 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 106 of file indexing_suite.hpp
Member Typedef Documentation
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> typedef detail::container_element<Container, Index, DerivedPolicies> boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::container_element_t private
Definition at line 126 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 126 of file indexing_suite.hpp
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> typedef mpl::if_< no_proxy , iterator<Container> , iterator<Container, return_policy> >::type boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::def_iterator private
Definition at line 138 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 138 of file indexing_suite.hpp
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> typedef mpl::or_< mpl::bool_<NoProxy> , mpl::not_<is_class<Data> > > boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::no_proxy private
Definition at line 123 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 123 of file indexing_suite.hpp
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> typedef mpl::if_< no_proxy , detail::no_proxy_helper< Container , DerivedPolicies , container_element_t , Index> , detail::proxy_helper< Container , DerivedPolicies , container_element_t , Index> >::type boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::proxy_handler private
Definition at line 152 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 152 of file indexing_suite.hpp
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> typedef return_internal_reference boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::return_policy private
Definition at line 131 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 131 of file indexing_suite.hpp
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> typedef mpl::if_< mpl::bool_<NoSlice> , detail::no_slice_helper< Container , DerivedPolicies , proxy_handler , Data , Index> , detail::slice_helper< Container , DerivedPolicies , proxy_handler , Data , Index> >::type boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::slice_handler private
Definition at line 168 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 168 of file indexing_suite.hpp
Member Function Documentation
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> static bool boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::base_contains (Container & container, PyObject * key) inline static private
Definition at line 271 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 271 of file indexing_suite.hpp
Referenced by boost::python::indexing_suite< Container, DerivedPolicies, NoProxy >::visit().
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> static void boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::base_delete_item (Container & container, PyObject * i) inline static private
Definition at line 250 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 250 of file indexing_suite.hpp
Referenced by boost::python::indexing_suite< Container, DerivedPolicies, NoProxy >::visit().
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> static object boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::base_get_item (back_reference< Container & > container, PyObject * i) inline static private
Definition at line 201 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 201 of file indexing_suite.hpp
Referenced by boost::python::indexing_suite< Container, DerivedPolicies, NoProxy >::visit().
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> static void boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::base_set_item (Container & container, PyObject * i, PyObject * v) inline static private
Definition at line 211 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 211 of file indexing_suite.hpp
Referenced by boost::python::indexing_suite< Container, DerivedPolicies, NoProxy >::visit().
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> static size_t boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::base_size (Container & container) inline static private
Definition at line 265 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 265 of file indexing_suite.hpp
Referenced by boost::python::indexing_suite< Container, DerivedPolicies, NoProxy >::visit().
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> template<class Class > static void boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::extension_def (Class & cl) inline static
Definition at line 192 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 192 of file indexing_suite.hpp
template<class Container, class DerivedPolicies, bool NoProxy = false, bool NoSlice = false, class Data = typename Container::value_type, class Index = typename Container::size_type, class Key = typename Container::value_type> template<class Class > void boost::python::indexing_suite< Container, DerivedPolicies, NoProxy, NoSlice, Data, Index, Key >::visit (Class & cl) const inline
Definition at line 173 of file indexing_suite.hpp.
View newest version in sPHENIX GitHub at line 173 of file indexing_suite.hpp
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/environments/g4py/source/boost/indexing_suite.hpp