ECCE @ EIC Software: G4StatAnalysis Class Reference
G4StatAnalysis Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4StatAnalysis.hh>
Public Member Functions
G4StatAnalysis ()
~G4StatAnalysis ()
G4double GetMean () const
const G4double & GetSum () const
const G4double & GetSumSquared () const
const G4double & GetSum1 () const
const G4double & GetSum2 () const
const G4int & GetHits () const
G4int GetNumNonZero () const
G4int GetNumZero () const
void SetSum (const G4double &val)
void SetSumSquared (const G4double &val)
void SetSum1 (const G4double &val)
void SetSum2 (const G4double &val)
void SetHits (const G4int &val)
void SetZero (const G4int &val)
G4double GetFOM () const
G4double GetRelativeError () const
G4double GetStdDev () const
G4double GetVariance () const
G4double GetCoeffVariation () const
G4double GetEfficiency () const
G4double GetR2Int () const
G4double GetR2Eff () const
operator G4double () const
void Reset ()
void Add (const G4double &_val, const G4double &_weight=1.0)
void Rescale (const G4double &factor)
void PrintInfo (std::ostream &os, const std::string &="") const
G4StatAnalysis & operator+= (const G4double &_val)
G4StatAnalysis & operator/= (const G4double &_val)
G4StatAnalysis & operator+= (const G4StatAnalysis &)
G4StatAnalysis & operator-= (const G4StatAnalysis &)
void * operator new (size_t)
void operator delete (void *)
G4double GetCpuTime () const
Static Public Member Functions
static tms *& GetCpuClock ()
static void ResetCpuClock ()
Private Attributes
G4double fSum1
G4double fSum2
G4int fHits
G4int fZero
Friends
std::ostream & operator<< (std::ostream &os, const G4StatAnalysis &obj)
const G4StatAnalysis operator+ (const G4StatAnalysis &lhs, const G4StatAnalysis &rhs)
const G4StatAnalysis operator- (const G4StatAnalysis &lhs, const G4StatAnalysis &rhs)
Detailed Description
Definition at line 69 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 69 of file G4StatAnalysis.hh
Constructor & Destructor Documentation
G4StatAnalysis::G4StatAnalysis () inline
G4StatAnalysis::~G4StatAnalysis () inline
Definition at line 73 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 73 of file G4StatAnalysis.hh
Member Function Documentation
void G4StatAnalysis::Add (const G4double & _val, const G4double & _weight = 1.0) inline
G4double G4StatAnalysis::GetCoeffVariation () const inline
static tms*& G4StatAnalysis::GetCpuClock () inline static
Definition at line 128 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 128 of file G4StatAnalysis.hh
References G4ThreadLocalStatic.
Referenced by ResetCpuClock().
G4double G4StatAnalysis::GetCpuTime () const inline
G4double G4StatAnalysis::GetEfficiency () const inline
G4double G4StatAnalysis::GetFOM () const inline
const G4int& G4StatAnalysis::GetHits () const inline
Referenced by Dicom2RunAction::EndOfRunAction().
G4double G4StatAnalysis::GetMean () const inline
G4int G4StatAnalysis::GetNumNonZero () const inline
G4int G4StatAnalysis::GetNumZero () const inline
G4double G4StatAnalysis::GetR2Eff () const inline
G4double G4StatAnalysis::GetR2Int () const inline
G4double G4StatAnalysis::GetRelativeError () const inline
G4double G4StatAnalysis::GetStdDev () const inline
const G4double& G4StatAnalysis::GetSum () const inline
const G4double& G4StatAnalysis::GetSum1 () const inline
const G4double& G4StatAnalysis::GetSum2 () const inline
const G4double& G4StatAnalysis::GetSumSquared () const inline
G4double G4StatAnalysis::GetVariance () const inline
void G4StatAnalysis::operator delete (void *) inline
G4StatAnalysis::operator G4double () const inline
void* G4StatAnalysis::operator new (size_t) inline
G4StatAnalysis& G4StatAnalysis::operator+= (const G4double & _val) inline
G4StatAnalysis& G4StatAnalysis::operator+= (const G4StatAnalysis &) inline
G4StatAnalysis& G4StatAnalysis::operator-= (const G4StatAnalysis &) inline
G4StatAnalysis& G4StatAnalysis::operator/= (const G4double & _val) inline
void G4StatAnalysis::PrintInfo (std::ostream & os, const std::string & = "") const inline
void G4StatAnalysis::Rescale (const G4double & factor) inline
void G4StatAnalysis::Reset () inline
static void G4StatAnalysis::ResetCpuClock () inline static
Definition at line 144 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 144 of file G4StatAnalysis.hh
References GetCpuClock().
Referenced by G4Run::G4Run().
void G4StatAnalysis::SetHits (const G4int & val) inline
void G4StatAnalysis::SetSum (const G4double & val) inline
void G4StatAnalysis::SetSum1 (const G4double & val) inline
void G4StatAnalysis::SetSum2 (const G4double & val) inline
void G4StatAnalysis::SetSumSquared (const G4double & val) inline
void G4StatAnalysis::SetZero (const G4int & val) inline
Friends And Related Function Documentation
const G4StatAnalysis operator+ (const G4StatAnalysis & lhs, const G4StatAnalysis & rhs) friend
Definition at line 168 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 168 of file G4StatAnalysis.hh
const G4StatAnalysis operator- (const G4StatAnalysis & lhs, const G4StatAnalysis & rhs) friend
Definition at line 174 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 174 of file G4StatAnalysis.hh
std::ostream& operator<< (std::ostream & os, const G4StatAnalysis & obj) friend
Definition at line 162 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 162 of file G4StatAnalysis.hh
Member Data Documentation
G4int G4StatAnalysis::fHits private
Definition at line 156 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 156 of file G4StatAnalysis.hh
G4double G4StatAnalysis::fSum1 private
Definition at line 152 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 152 of file G4StatAnalysis.hh
G4double G4StatAnalysis::fSum2 private
Definition at line 154 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 154 of file G4StatAnalysis.hh
G4int G4StatAnalysis::fZero private
Definition at line 158 of file G4StatAnalysis.hh.
View newest version in sPHENIX GitHub at line 158 of file G4StatAnalysis.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4StatAnalysis.hh