ECCE @ EIC Software: G4VFastSimulationModel Class Reference
G4VFastSimulationModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4VFastSimulationModel.hh>
Public Member Functions
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)=0
virtual G4bool ModelTrigger (const G4FastTrack &)=0
virtual void DoIt (const G4FastTrack &, G4FastStep &)=0
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Private Attributes
G4String theModelName
Detailed Description
Definition at line 65 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VFastSimulationModel.hh
Constructor & Destructor Documentation
G4VFastSimulationModel::G4VFastSimulationModel (const G4String & aName)
Definition at line 47 of file G4VFastSimulationModel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VFastSimulationModel.cc
G4VFastSimulationModel::G4VFastSimulationModel (const G4String & aName, G4Envelope * anEnvelope, G4bool IsUnique = FALSE)
Definition at line 53 of file G4VFastSimulationModel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VFastSimulationModel.cc
References G4FastSimulationManager::AddFastSimulationModel(), and G4Region::GetFastSimulationManager().
virtual G4VFastSimulationModel::~G4VFastSimulationModel () inline virtual
Definition at line 87 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VFastSimulationModel.hh
Member Function Documentation
virtual void G4VFastSimulationModel::AtRestDoIt (const G4FastTrack & , G4FastStep &) inline virtual
Definition at line 131 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4VFastSimulationModel.hh
Referenced by G4FastSimulationManager::InvokeAtRestDoIt().
virtual G4bool G4VFastSimulationModel::AtRestModelTrigger (const G4FastTrack &) inline virtual
Definition at line 120 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VFastSimulationModel.hh
virtual void G4VFastSimulationModel::DoIt (const G4FastTrack & , G4FastStep &) pure virtual
Implemented in Par02FastSimModelTracker, Par02FastSimModelEMCal, Par02FastSimModelHCal, GFlashShowerModel, Par01EMShowerModel, Par01PionShowerModel, and Par01PiModel.
Referenced by G4FastSimulationManager::InvokePostStepDoIt().
const G4String G4VFastSimulationModel::GetName (void) const inline
Definition at line 151 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4VFastSimulationModel.hh
References theModelName.
virtual G4bool G4VFastSimulationModel::IsApplicable (const G4ParticleDefinition &) pure virtual
Implemented in Par02FastSimModelTracker, Par02FastSimModelEMCal, Par02FastSimModelHCal, GFlashShowerModel, Par01EMShowerModel, Par01PionShowerModel, and Par01PiModel.
virtual G4bool G4VFastSimulationModel::ModelTrigger (const G4FastTrack &) pure virtual
Implemented in Par02FastSimModelTracker, Par02FastSimModelEMCal, Par02FastSimModelHCal, GFlashShowerModel, Par01EMShowerModel, Par01PionShowerModel, and Par01PiModel.
G4bool G4VFastSimulationModel::operator== (const G4VFastSimulationModel & fsm) const inline
Definition at line 157 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4VFastSimulationModel.hh
Member Data Documentation
G4String G4VFastSimulationModel::theModelName private
Definition at line 148 of file G4VFastSimulationModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4VFastSimulationModel.hh
Referenced by GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4VFastSimulationModel.hh
geant4/tree/geant4-10.6-release/source/processes/parameterisation/src/G4VFastSimulationModel.cc