ECCE @ EIC Software: CLHEP::HepRandom Class Reference
CLHEP::HepRandom Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/Random.h>
Public Member Functions
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
virtual double operator() ()
virtual std::string name () const
virtual HepRandomEngine & engine ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
Static Public Member Functions
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Protected Attributes
static const long seedTable [215][2]
Detailed Description
Author
Gabri.nosp@m.ele..nosp@m.Cosmo.nosp@m.@cer.nosp@m.n.ch
Definition at line 48 of file Random.h.
View newest version in sPHENIX GitHub at line 48 of file Random.h
Constructor & Destructor Documentation
CLHEP::HepRandom::HepRandom ()
Definition at line 174 of file Random.cc.
View newest version in sPHENIX GitHub at line 174 of file Random.cc
CLHEP::HepRandom::HepRandom (long seed)
Definition at line 177 of file Random.cc.
View newest version in sPHENIX GitHub at line 177 of file Random.cc
CLHEP::HepRandom::HepRandom (HepRandomEngine & algorithm)
Definition at line 182 of file Random.cc.
View newest version in sPHENIX GitHub at line 182 of file Random.cc
CLHEP::HepRandom::HepRandom (HepRandomEngine * algorithm)
Definition at line 187 of file Random.cc.
View newest version in sPHENIX GitHub at line 187 of file Random.cc
CLHEP::HepRandom::~HepRandom () virtual
Definition at line 192 of file Random.cc.
View newest version in sPHENIX GitHub at line 192 of file Random.cc
Member Function Documentation
int CLHEP::HepRandom::createInstance () static
Definition at line 307 of file Random.cc.
View newest version in sPHENIX GitHub at line 307 of file Random.cc
static std::string CLHEP::HepRandom::distributionName () inline static
Definition at line 151 of file Random.h.
View newest version in sPHENIX GitHub at line 151 of file Random.h
HepRandomEngine & CLHEP::HepRandom::engine () virtual
Reimplemented in CLHEP::RandFlat, CLHEP::RandBreitWigner, CLHEP::RandGeneral, CLHEP::RandExpZiggurat, CLHEP::RandGaussQ, CLHEP::RandPoissonQ, CLHEP::RandGauss, CLHEP::RandStudentT, CLHEP::RandBinomial, CLHEP::RandGamma, CLHEP::RandLandau, CLHEP::RandChiSquare, CLHEP::RandPoisson, CLHEP::RandExponential, and CLHEP::RandGaussZiggurat.
Definition at line 210 of file Random.cc.
View newest version in sPHENIX GitHub at line 210 of file Random.cc
References CLHEP::HepRandomEngine::get().
double CLHEP::HepRandom::flat ()
Definition at line 195 of file Random.cc.
View newest version in sPHENIX GitHub at line 195 of file Random.cc
Referenced by CLHEP::RandExponential::shoot().
double CLHEP::HepRandom::flat (HepRandomEngine * theNewEngine) inline
void CLHEP::HepRandom::flatArray (const int size, double * vect)
Definition at line 200 of file Random.cc.
View newest version in sPHENIX GitHub at line 200 of file Random.cc
void CLHEP::HepRandom::flatArray (HepRandomEngine * theNewEngine, const int size, double * vect) inline
std::istream & CLHEP::HepRandom::get (std::istream & is) virtual
Reimplemented in CLHEP::RandFlat, CLHEP::RandBreitWigner, CLHEP::RandGeneral, CLHEP::RandGauss, CLHEP::RandExpZiggurat, CLHEP::RandGaussQ, CLHEP::RandBinomial, CLHEP::RandGamma, CLHEP::RandChiSquare, CLHEP::RandExponential, CLHEP::RandGaussZiggurat, CLHEP::RandBit, CLHEP::RandLandau, CLHEP::RandPoisson, CLHEP::RandStudentT, and CLHEP::RandPoissonQ.
Definition at line 224 of file Random.cc.
View newest version in sPHENIX GitHub at line 224 of file Random.cc
Referenced by getTheGenerator(), and CLHEP::operator>>().
HepRandomEngine * CLHEP::HepRandom::getTheEngine () static
Definition at line 264 of file Random.cc.
View newest version in sPHENIX GitHub at line 264 of file Random.cc
References CLHEP::HepRandomEngine::get().
Referenced by FW::Geant4::MMPrimaryGeneratorAction::MMPrimaryGeneratorAction(), CLHEP::StaticRandomStates::restore(), CLHEP::RandGauss::restoreEngineStatus(), CLHEP::RandFlat::restoreEngineStatus(), CLHEP::RandGauss::saveEngineStatus(), CLHEP::RandFlat::saveEngineStatus(), CLHEP::RandGaussZiggurat::shoot(), CLHEP::RandExponential::shoot(), CLHEP::RandExpZiggurat::shoot(), CLHEP::RandBreitWigner::shoot(), CLHEP::RandChiSquare::shoot(), CLHEP::RandBinomial::shoot(), CLHEP::RandGamma::shoot(), CLHEP::RandGauss::shoot(), CLHEP::RandFlat::shoot(), CLHEP::RandPoisson::shoot(), CLHEP::RandStudentT::shoot(), CLHEP::RandPoissonQ::shoot(), and CLHEP::RandFlat::shootArray().
HepRandom * CLHEP::HepRandom::getTheGenerator () static
Definition at line 259 of file Random.cc.
View newest version in sPHENIX GitHub at line 259 of file Random.cc
References get().
long CLHEP::HepRandom::getTheSeed () static
Definition at line 235 of file Random.cc.
View newest version in sPHENIX GitHub at line 235 of file Random.cc
Referenced by main().
const long * CLHEP::HepRandom::getTheSeeds () static
Definition at line 245 of file Random.cc.
View newest version in sPHENIX GitHub at line 245 of file Random.cc
void CLHEP::HepRandom::getTheTableSeeds (long * seeds, int index) static
Definition at line 250 of file Random.cc.
View newest version in sPHENIX GitHub at line 250 of file Random.cc
Referenced by CLHEP::HepJamesRandom::HepJamesRandom(), CLHEP::MTwistEngine::MTwistEngine(), CLHEP::RanecuEngine::RanecuEngine(), CLHEP::Ranlux64Engine::Ranlux64Engine(), CLHEP::RanluxEngine::RanluxEngine(), and CLHEP::RanecuEngine::setSeed().
std::string CLHEP::HepRandom::name () const virtual
Reimplemented in CLHEP::RandFlat, CLHEP::RandBreitWigner, CLHEP::RandGeneral, CLHEP::RandExpZiggurat, CLHEP::RandGaussQ, CLHEP::RandPoissonQ, CLHEP::RandGauss, CLHEP::RandStudentT, CLHEP::RandBinomial, CLHEP::RandGamma, CLHEP::RandLandau, CLHEP::RandChiSquare, CLHEP::RandPoisson, CLHEP::RandExponential, CLHEP::RandGaussZiggurat, and CLHEP::RandBit.
Definition at line 209 of file Random.cc.
View newest version in sPHENIX GitHub at line 209 of file Random.cc
double CLHEP::HepRandom::operator() () virtual
Reimplemented in CLHEP::RandFlat, CLHEP::RandBreitWigner, CLHEP::RandGeneral, CLHEP::RandExpZiggurat, CLHEP::RandPoissonQ, CLHEP::RandGauss, CLHEP::RandLandau, CLHEP::RandStudentT, CLHEP::RandGaussQ, CLHEP::RandBinomial, CLHEP::RandGamma, CLHEP::RandPoisson, CLHEP::RandChiSquare, CLHEP::RandExponential, and CLHEP::RandGaussZiggurat.
Definition at line 205 of file Random.cc.
View newest version in sPHENIX GitHub at line 205 of file Random.cc
References G4AblaRandom::flat().
std::ostream & CLHEP::HepRandom::put (std::ostream & os) const virtual
Reimplemented in CLHEP::RandFlat, CLHEP::RandBreitWigner, CLHEP::RandGeneral, CLHEP::RandGauss, CLHEP::RandExpZiggurat, CLHEP::RandGaussQ, CLHEP::RandBinomial, CLHEP::RandGamma, CLHEP::RandChiSquare, CLHEP::RandExponential, CLHEP::RandGaussZiggurat, CLHEP::RandBit, CLHEP::RandLandau, CLHEP::RandPoisson, CLHEP::RandStudentT, and CLHEP::RandPoissonQ.
Definition at line 223 of file Random.cc.
View newest version in sPHENIX GitHub at line 223 of file Random.cc
Referenced by CLHEP::operator<<().
static std::istream& CLHEP::HepRandom::restoreDistState (std::istream & is) inline static
Definition at line 136 of file Random.h.
View newest version in sPHENIX GitHub at line 136 of file Random.h
void CLHEP::HepRandom::restoreEngineStatus (const char filename[] = "Config.conf") static
Definition at line 279 of file Random.cc.
View newest version in sPHENIX GitHub at line 279 of file Random.cc
Referenced by RunMessenger::SetNewValue().
std::istream & CLHEP::HepRandom::restoreFullState (std::istream & is) static
Definition at line 289 of file Random.cc.
View newest version in sPHENIX GitHub at line 289 of file Random.cc
Referenced by CLHEP::RandGauss::restoreFullState(), and CLHEP::RandFlat::restoreFullState().
std::istream & CLHEP::HepRandom::restoreStaticRandomStates (std::istream & is) static
Definition at line 298 of file Random.cc.
View newest version in sPHENIX GitHub at line 298 of file Random.cc
static std::ostream& CLHEP::HepRandom::saveDistState (std::ostream & os) inline static
Definition at line 133 of file Random.h.
View newest version in sPHENIX GitHub at line 133 of file Random.h
void CLHEP::HepRandom::saveEngineStatus (const char filename[] = "Config.conf") static
Definition at line 274 of file Random.cc.
View newest version in sPHENIX GitHub at line 274 of file Random.cc
Referenced by G4CascadeInterface::ApplyYourself(), G4HadronicProcess::PostStepDoIt(), and G4CascadeInterface::Propagate().
std::ostream & CLHEP::HepRandom::saveFullState (std::ostream & os) static
Definition at line 284 of file Random.cc.
View newest version in sPHENIX GitHub at line 284 of file Random.cc
Referenced by G4EventManager::DoProcessing(), G4EventManager::ProcessOneEvent(), CLHEP::RandGauss::saveFullState(), and CLHEP::RandFlat::saveFullState().
std::ostream & CLHEP::HepRandom::saveStaticRandomStates (std::ostream & os) static
Definition at line 294 of file Random.cc.
View newest version in sPHENIX GitHub at line 294 of file Random.cc
void CLHEP::HepRandom::setTheEngine (HepRandomEngine * theNewEngine) static
Definition at line 269 of file Random.cc.
View newest version in sPHENIX GitHub at line 269 of file Random.cc
Referenced by main(), and CLHEP::StaticRandomStates::restore().
void CLHEP::HepRandom::setTheSeed (long seed, int lux = 3) static
Definition at line 230 of file Random.cc.
View newest version in sPHENIX GitHub at line 230 of file Random.cc
Referenced by PHG4Reco::G4Seed(), main(), and G4MPImanager::SetSeed().
void CLHEP::HepRandom::setTheSeeds (const long * seeds, int aux = -1) static
Definition at line 240 of file Random.cc.
View newest version in sPHENIX GitHub at line 240 of file Random.cc
Referenced by main().
void CLHEP::HepRandom::showEngineStatus () static
Definition at line 302 of file Random.cc.
View newest version in sPHENIX GitHub at line 302 of file Random.cc
Referenced by RunMessenger::SetNewValue().
Member Data Documentation
const long CLHEP::HepRandom::seedTable static protected
Definition at line 156 of file Random.h.
View newest version in sPHENIX GitHub at line 156 of file Random.h
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/Random.h
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/SeedTable.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/Random.cc