ECCE @ EIC Software: G4DynamicParticle Class Reference
G4DynamicParticle Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4DynamicParticle.hh>
Public Member Functions
G4DynamicParticle ()
G4DynamicParticle (const G4ParticleDefinition *aParticleDefinition, const G4ThreeVector &aMomentumDirection, G4double aKineticEnergy)
G4DynamicParticle (const G4ParticleDefinition *aParticleDefinition, const G4ThreeVector &aParticleMomentum)
G4DynamicParticle (const G4ParticleDefinition *aParticleDefinition, const G4LorentzVector &aParticleMomentum)
G4DynamicParticle (const G4ParticleDefinition *aParticleDefinition, G4double aTotalEnergy, const G4ThreeVector &aParticleMomentum)
G4DynamicParticle (const G4ParticleDefinition *aParticleDefinition, const G4ThreeVector &aMomentumDirection, G4double aKineticEnergy, const G4double dynamicalMass)
G4DynamicParticle (const G4DynamicParticle &right)
~G4DynamicParticle ()
G4DynamicParticle & operator= (const G4DynamicParticle &right)
G4bool operator== (const G4DynamicParticle &right) const
G4bool operator!= (const G4DynamicParticle &right) const
void * operator new (size_t)
void operator delete (void *aDynamicParticle)
const G4ThreeVector & GetMomentumDirection () const
void SetMomentumDirection (const G4ThreeVector &aDirection)
void SetMomentumDirection (G4double px, G4double py, G4double pz)
G4ThreeVector GetMomentum () const
void SetMomentum (const G4ThreeVector &momentum)
G4LorentzVector Get4Momentum () const
void Set4Momentum (const G4LorentzVector &momentum)
G4double GetTotalMomentum () const
G4double GetTotalEnergy () const
G4double GetKineticEnergy () const
G4double GetLogKineticEnergy () const
void SetKineticEnergy (G4double aEnergy)
G4double GetProperTime () const
void SetProperTime (G4double)
const G4ThreeVector & GetPolarization () const
void SetPolarization (const G4ThreeVector &)
void SetPolarization (G4double polX, G4double polY, G4double polZ)
G4double GetMass () const
void SetMass (G4double mass)
G4double GetCharge () const
void SetCharge (G4double charge)
void SetCharge (G4int chargeInUnitOfEplus)
G4double GetSpin () const
void SetSpin (G4double spin)
void SetSpin (G4int spinInUnitOfHalfInteger)
G4double GetMagneticMoment () const
void SetMagneticMoment (G4double magneticMoment)
const G4ElectronOccupancy * GetElectronOccupancy () const
G4int GetTotalOccupancy () const
G4int GetOccupancy (G4int orbit) const
void AddElectron (G4int orbit, G4int number=1)
void RemoveElectron (G4int orbit, G4int number=1)
const G4ParticleDefinition * GetParticleDefinition () const
void SetDefinition (const G4ParticleDefinition *aParticleDefinition)
G4ParticleDefinition * GetDefinition () const
const G4DecayProducts * GetPreAssignedDecayProducts () const
void SetPreAssignedDecayProducts (G4DecayProducts *aDecayProducts)
G4double GetPreAssignedDecayProperTime () const
void SetPreAssignedDecayProperTime (G4double)
void DumpInfo (G4int mode=0) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetPrimaryParticle (G4PrimaryParticle *p)
void SetPDGcode (G4int c)
G4PrimaryParticle * GetPrimaryParticle () const
G4int GetPDGcode () const
Protected Member Functions
void AllocateElectronOccupancy ()
G4double GetElectronMass () const
Private Attributes
G4ThreeVector theMomentumDirection
G4ThreeVector thePolarization
const G4ParticleDefinition * theParticleDefinition
G4ElectronOccupancy * theElectronOccupancy
G4DecayProducts * thePreAssignedDecayProducts
G4PrimaryParticle * primaryParticle
G4double theKineticEnergy
G4double theLogKineticEnergy
G4double theProperTime
G4double theDynamicalMass
G4double theDynamicalCharge
G4double theDynamicalSpin
G4double theDynamicalMagneticMoment
G4double thePreAssignedDecayTime
G4int verboseLevel
G4int thePDGcode
Detailed Description
Definition at line 74 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 74 of file G4DynamicParticle.hh
Constructor & Destructor Documentation
G4DynamicParticle::G4DynamicParticle ()
Definition at line 81 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 81 of file G4DynamicParticle.cc
G4DynamicParticle::G4DynamicParticle (const G4ParticleDefinition * aParticleDefinition, const G4ThreeVector & aMomentumDirection, G4double aKineticEnergy)
Definition at line 104 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 104 of file G4DynamicParticle.cc
G4DynamicParticle::G4DynamicParticle (const G4ParticleDefinition * aParticleDefinition, const G4ThreeVector & aParticleMomentum)
Definition at line 155 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 155 of file G4DynamicParticle.cc
References SetMomentum().
G4DynamicParticle::G4DynamicParticle (const G4ParticleDefinition * aParticleDefinition, const G4LorentzVector & aParticleMomentum)
Definition at line 177 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 177 of file G4DynamicParticle.cc
References Set4Momentum().
G4DynamicParticle::G4DynamicParticle (const G4ParticleDefinition * aParticleDefinition, G4double aTotalEnergy, const G4ThreeVector & aParticleMomentum)
Definition at line 199 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 199 of file G4DynamicParticle.cc
References kdfinder::abs(), EnergyMRA2, G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag2(), SetKineticEnergy(), SetMomentumDirection(), theDynamicalMass, and CLHEP::Hep3Vector::unit().
G4DynamicParticle::G4DynamicParticle (const G4ParticleDefinition * aParticleDefinition, const G4ThreeVector & aMomentumDirection, G4double aKineticEnergy, const G4double dynamicalMass)
Definition at line 127 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 127 of file G4DynamicParticle.cc
References kdfinder::abs(), EnergyMomentumRelationAllowance, and theDynamicalMass.
G4DynamicParticle::G4DynamicParticle (const G4DynamicParticle & right)
Definition at line 242 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 242 of file G4DynamicParticle.cc
References theElectronOccupancy.
G4DynamicParticle::~G4DynamicParticle ()
Definition at line 269 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 269 of file G4DynamicParticle.cc
References theElectronOccupancy, and thePreAssignedDecayProducts.
Member Function Documentation
void G4DynamicParticle::AddElectron (G4int orbit, G4int number = 1) inline
Referenced by G4PrimaryTransformer::GenerateSingleTrack().
void G4DynamicParticle::AllocateElectronOccupancy () protected
Definition at line 366 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 366 of file G4DynamicParticle.cc
References G4IonTable::IsIon(), theElectronOccupancy, and theParticleDefinition.
void G4DynamicParticle::DumpInfo (G4int mode = 0) const
Definition at line 447 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 447 of file G4DynamicParticle.cc
Referenced by G4VContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4DecayProducts::DumpInfo(), export_G4DynamicParticle(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), and G4Decay::PostStepGetPhysicalInteractionLength().
G4LorentzVector G4DynamicParticle::Get4Momentum () const inline
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4KineticTrack::Decay(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4MuonicAtomDecay::FillResult(), G4TripathiCrossSection::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4InuclParticle::getMomentum(), G4HadProjectile::InitialiseLocal(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4QuasiElasticChannel::Scatter(), G4VPartonStringModel::Scatter(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), and G4DiffuseElastic::ThetaLabToThetaCMS().
G4double G4DynamicParticle::GetCharge () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4BetheBlochIonGasModel::ChargeSquareRatio(), G4BraggIonGasModel::ChargeSquareRatio(), G4FieldTrackUpdator::CreateFieldTrack(), G4PionDecayMakeSpin::DaughterPolarization(), G4PAIPhotModel::Dispersion(), G4PAIModel::Dispersion(), export_G4DynamicParticle(), G4InuclParticle::getCharge(), G4hImpactIonisation::GetMeanFreePath(), G4ParticleChange::Initialize(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4IonYangFluctuationModel::TheValue(), G4hNuclearStoppingModel::TheValue(), G4QAOLowEnergyLoss::TheValue(), and G4FieldTrackUpdator::Update().
G4ParticleDefinition* G4DynamicParticle::GetDefinition () const inline
Referenced by G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode(), G4ParticleHPFinalState::adjust_final_state(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4ErrorEnergyLoss::AlongStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4EmBiasingManager::ApplyRangeCut(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LFission::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4DecayWithSpin::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4ParticleHPInelasticBaseFS::BaseApply(), G4HadLeadBias::Bias(), G4HadronCrossSections::CalcScatteringCrossSections(), G4RPGInelastic::CalculateMomenta(), G4PrimaryTransformer::CheckDynamicParticle(), G4HadronicProcess::CheckResult(), G4CrossSectionDataStore::ComputeCrossSection(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4PionDecayMakeSpin::DaughterPolarization(), G4KineticTrack::Decay(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4LowEnergyIonisation::DeexciteAtom(), G4BohrFluctuations::Dispersion(), G4UniversalFluctuation::Dispersion(), G4AtimaFluctuations::Dispersion(), export_G4DynamicParticle(), G4HadronicProcess::FillResult(), G4Track::G4Track(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4ComponentGGNuclNuclXsc::GetCoulombBarier(), G4HadronNucleonXsc::GetCoulombBarrier(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4InuclParticle::getDefinition(), G4UPiNuclearCrossSection::GetElasticCrossSection(), G4NucleonNuclearCrossSection::GetElasticCrossSection(), G4HadronCrossSections::GetElasticCrossSection(), G4ComponentBarNucleonNucleusXsc::GetElasticCrossSection(), G4ComponentGGNuclNuclXsc::GetElasticGlauberGribov(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), G4NeutrinoElectronNcXsc::GetElementCrossSection(), G4PiNuclearCrossSection::GetElementCrossSection(), G4NeutrinoElectronCcXsc::GetElementCrossSection(), G4TripathiCrossSection::GetElementCrossSection(), G4NucleonNuclearCrossSection::GetElementCrossSection(), G4HadronInelasticDataSet::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsSihverCrossSection::GetElementCrossSection(), G4HadronElasticDataSet::GetElementCrossSection(), G4CrossSectionPairGG::GetElementCrossSection(), G4IonProtonCrossSection::GetElementCrossSection(), G4CrossSectionElastic::GetElementCrossSection(), G4CrossSectionInelastic::GetElementCrossSection(), G4BGGNucleonElasticXS::GetElementCrossSection(), G4BGGNucleonInelasticXS::GetElementCrossSection(), G4BGGPionElasticXS::GetElementCrossSection(), G4BGGPionInelasticXS::GetElementCrossSection(), G4ComponentBarNucleonNucleusXsc::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4GeneralSpaceNNCrossSection::GetElementCrossSection(), G4VCrossSectionDataSet::GetElementCrossSection(), G4RPGReaction::GetFinalStateNucleons(), G4QuasiElasticChannel::GetFraction(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXsc(), G4HadronNucleonXsc::GetHadronNucleonXscEL(), G4HadronNucleonXsc::GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscNS(), G4HadronNucleonXsc::GetHadronNucleonXscPDG(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscPDG(), G4HadronNucleonXsc::GetHadronNucleonXscVU(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXscVU(), G4HadronNucleonXsc::GetHyperonNucleonXscNS(), G4UPiNuclearCrossSection::GetInelasticCrossSection(), G4HadronCrossSections::GetInelasticCrossSection(), G4ComponentGGNuclNuclXsc::GetInelasticGlauberGribov(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4ChipsAntiBaryonInelasticXS::GetIsoCrossSection(), G4MuNeutrinoNucleusTotXsc::GetIsoCrossSection(), G4ChipsHyperonElasticXS::GetIsoCrossSection(), G4ChipsHyperonInelasticXS::GetIsoCrossSection(), G4ChipsAntiBaryonElasticXS::GetIsoCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), G4CrossSectionDataStore::GetIsoCrossSection(), G4ComponentGGHadronNucleusXsc::GetIsoCrossSection(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4HadronNucleonXsc::GetKaonNucleonXscGG(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanLifeTime(), G4Decay::GetMeanLifeTime(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4ComponentGGHadronNucleusXsc::GetRatioQE(), G4ComponentGGNuclNuclXsc::GetRatioQE(), G4ComponentGGHadronNucleusXsc::GetRatioSD(), G4ComponentGGNuclNuclXsc::GetRatioSD(), G4Scintillation::GetScintillationYieldByParticleType(), G4ComponentGGNuclNuclXsc::GetZandACrossSection(), G4Pythia6Decayer::ImportDecayProducts(), G4HadProjectile::InitialiseLocal(), G4NuclNuclDiffuseElastic::InitParametersGla(), G4ParticleHPThermalScatteringData::IsApplicable(), G4NeutrinoElectronNcXsc::IsElementApplicable(), G4NeutrinoElectronCcXsc::IsElementApplicable(), G4TripathiCrossSection::IsElementApplicable(), G4NeutronElectronElXsc::IsElementApplicable(), G4IonsKoxCrossSection::IsElementApplicable(), G4IonsSihverCrossSection::IsElementApplicable(), G4IonsShenCrossSection::IsElementApplicable(), G4ProtonInelasticCrossSection::IsElementApplicable(), G4EMDissociationCrossSection::IsElementApplicable(), G4TripathiLightCrossSection::IsElementApplicable(), G4GeneralSpaceNNCrossSection::IsElementApplicable(), G4QAOLowEnergyLoss::IsInCharge(), G4MuNeutrinoNucleusTotXsc::IsIsoApplicable(), G4ParticleHPFissionData::IsIsoApplicable(), G4ParticleHPCaptureData::IsIsoApplicable(), G4ParticleHPElasticData::IsIsoApplicable(), G4ParticleHPInelasticData::IsIsoApplicable(), G4ParticleHPThermalScatteringData::IsIsoApplicable(), G4LENDCrossSection::IsIsoApplicable(), G4ReactionProduct::operator=(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), G4HadronElasticProcess::PostStepDoIt(), G4DecayWithSpin::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4RPGStrangeProduction::ReactionStage(), G4DNABornAngle::SampleDirectionForShell(), G4DNARuddAngle::SampleDirectionForShell(), G4UniversalFluctuation::SampleFluctuations(), G4PAIPhotModel::SampleFluctuations(), G4PAIModel::SampleFluctuations(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4QuasiElasticChannel::Scatter(), G4VPartonStringModel::Scatter(), G4UrbanMscModel::StartTracking(), G4UrbanAdjointMscModel::StartTracking(), G4AdjointProcessEquivalentToDirectProcess::StartTracking(), G4GoudsmitSaundersonMscModel::StartTracking(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4hIonEffChargeSquare::TheValue(), doiPETSteppingAction::UserSteppingAction(), and PurgMagSteppingAction::UserSteppingAction().
G4double G4DynamicParticle::GetElectronMass () const protected
Definition at line 454 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 454 of file G4DynamicParticle.cc
References CLHEP::electron_mass_c2.
const G4ElectronOccupancy* G4DynamicParticle::GetElectronOccupancy () const inline
G4double G4DynamicParticle::GetKineticEnergy () const inline
Referenced by HistoManager::AddDeltaElectron(), Run::AddPhantomElectron(), HistoManager::AddPhoton(), Run::AddTargetElectron(), Run::AddTargetPhoton(), G4ParticleHPFinalState::adjust_final_state(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4EmBiasingManager::ApplyRangeCut(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4eplusAnnihilation::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4HadLeadBias::Bias(), G4HadronCrossSections::CalcScatteringCrossSections(), G4Track::CalculateVelocity(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CrossSectionDataStore::ComputeCrossSection(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4RadioactiveDecayBase::DecayAnalog(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4RadioactiveDecay::DecayIt(), G4LowEnergyIonisation::DeexciteAtom(), G4BohrFluctuations::Dispersion(), G4UniversalFluctuation::Dispersion(), G4AtimaFluctuations::Dispersion(), G4IonFluctuations::Dispersion(), G4mplIonisationModel::Dispersion(), G4PAIPhotModel::Dispersion(), G4mplIonisationWithDeltaModel::Dispersion(), G4PAIModel::Dispersion(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4SingleScatter::DoCollisionStep(), export_G4DynamicParticle(), G4HadronicProcess::FillResult(), G4HadSecondary::G4HadSecondary(), G4HadronCrossSections::GetCaptureCrossSection(), G4hImpactIonisation::GetConstraints(), G4ComponentGGNuclNuclXsc::GetCoulombBarier(), G4HadronNucleonXsc::GetCoulombBarrier(), G4ParticleHPJENDLHEData::GetCrossSection(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4GammaConversionToMuons::GetCrossSectionPerAtom(), G4VEnergyLossProcess::GetDEDXDispersion(), G4UPiNuclearCrossSection::GetElasticCrossSection(), G4NucleonNuclearCrossSection::GetElasticCrossSection(), G4HadronCrossSections::GetElasticCrossSection(), G4ComponentBarNucleonNucleusXsc::GetElasticCrossSection(), G4ComponentGGNuclNuclXsc::GetElasticGlauberGribov(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), G4PiNuclearCrossSection::GetElementCrossSection(), G4TripathiCrossSection::GetElementCrossSection(), G4NeutronInelasticCrossSection::GetElementCrossSection(), G4NucleonNuclearCrossSection::GetElementCrossSection(), G4HadronInelasticDataSet::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4NeutronElectronElXsc::GetElementCrossSection(), G4HadronElasticDataSet::GetElementCrossSection(), G4ProtonInelasticCrossSection::GetElementCrossSection(), G4CrossSectionPairGG::GetElementCrossSection(), G4KokoulinMuonNuclearXS::GetElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4PhotoNuclearCrossSection::GetElementCrossSection(), G4ElectroNuclearCrossSection::GetElementCrossSection(), G4IonProtonCrossSection::GetElementCrossSection(), G4NeutronElasticXS::GetElementCrossSection(), G4NeutronInelasticXS::GetElementCrossSection(), G4ParticleInelasticXS::GetElementCrossSection(), G4CrossSectionInelastic::GetElementCrossSection(), G4NeutronCaptureXS::GetElementCrossSection(), G4CrossSectionElastic::GetElementCrossSection(), G4BGGNucleonElasticXS::GetElementCrossSection(), G4BGGNucleonInelasticXS::GetElementCrossSection(), G4BGGPionElasticXS::GetElementCrossSection(), G4BGGPionInelasticXS::GetElementCrossSection(), G4ComponentBarNucleonNucleusXsc::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4GeneralSpaceNNCrossSection::GetElementCrossSection(), G4VCrossSectionDataSet::GetElementCrossSection(), G4NeutronElectronElXsc::GetElementNonRelXsc(), G4HadronCrossSections::GetFissionCrossSection(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXsc(), G4HadronNucleonXsc::GetHadronNucleonXscEL(), G4HadronNucleonXsc::GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscNS(), G4HadronNucleonXsc::GetHadronNucleonXscPDG(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscPDG(), G4HadronNucleonXsc::GetHadronNucleonXscVU(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXscVU(), G4HadronNucleonXsc::GetHyperonNucleonXscNS(), G4UPiNuclearCrossSection::GetInelasticCrossSection(), G4HadronCrossSections::GetInelasticCrossSection(), G4ComponentGGNuclNuclXsc::GetInelasticGlauberGribov(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4ParticleHPFissionData::GetIsoCrossSection(), G4PhotoNuclearCrossSection::GetIsoCrossSection(), G4ParticleHPCaptureData::GetIsoCrossSection(), G4ParticleHPElasticData::GetIsoCrossSection(), G4ParticleHPInelasticData::GetIsoCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4ParticleHPThermalScatteringData::GetIsoCrossSection(), G4NeutronElasticXS::GetIsoCrossSection(), G4NeutronInelasticXS::GetIsoCrossSection(), G4ParticleInelasticXS::GetIsoCrossSection(), G4NeutronCaptureXS::GetIsoCrossSection(), G4LENDCrossSection::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), G4CrossSectionDataStore::GetIsoCrossSection(), G4ComponentGGHadronNucleusXsc::GetIsoCrossSection(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4HadronNucleonXsc::GetKaonNucleonXscGG(), G4InuclParticle::getKineticEnergy(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4GammaConversionToMuons::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4AnnihiToMuPair::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), G4ComponentGGHadronNucleusXsc::GetRatioQE(), G4ComponentGGNuclNuclXsc::GetRatioQE(), G4ComponentGGHadronNucleusXsc::GetRatioSD(), G4ComponentGGNuclNuclXsc::GetRatioSD(), G4ParticleHPThermalScatteringData::GetX(), G4ComponentGGNuclNuclXsc::GetZandACrossSection(), G4HadProjectile::InitialiseLocal(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), G4NuclNuclDiffuseElastic::InitParametersGla(), G4ParticleHPJENDLHEData::IsApplicable(), G4ParticleHPThermalScatteringData::IsApplicable(), G4TripathiCrossSection::IsElementApplicable(), G4NeutronInelasticCrossSection::IsElementApplicable(), G4NeutronElectronElXsc::IsElementApplicable(), G4IonsSihverCrossSection::IsElementApplicable(), G4CrossSectionPairGG::IsElementApplicable(), G4CrossSectionInelastic::IsElementApplicable(), G4CrossSectionElastic::IsElementApplicable(), G4ParticleHPBGGNucleonInelasticXS::IsElementApplicable(), G4TripathiLightCrossSection::IsElementApplicable(), G4ParticleHPFissionData::IsIsoApplicable(), G4ParticleHPCaptureData::IsIsoApplicable(), G4ParticleHPElasticData::IsIsoApplicable(), G4ParticleHPInelasticData::IsIsoApplicable(), G4ParticleHPThermalScatteringData::IsIsoApplicable(), G4ParticleHPBGGNucleonInelasticXS::IsIsoApplicable(), G4LENDCrossSection::IsIsoApplicable(), G4VEmModel::MaxSecondaryKinEnergy(), G4ReactionProduct::operator=(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4PolarizedComptonModel::PrintWarning(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4DipBustGenerator::SampleDirection(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4ModifiedTsai::SampleDirection(), G4Generator2BN::SampleDirection(), G4DNARuddAngle::SampleDirectionForShell(), G4DNABornAngle::SampleDirectionForShell(), G4UniversalFluctuation::SampleFluctuations(), G4IonFluctuations::SampleFluctuations(), G4PAIPhotModel::SampleFluctuations(), G4PAIModel::SampleFluctuations(), G4LEPTSVibExcitationModel::SampleSecondaries(), G4LEPTSIonisationModel::SampleSecondaries(), G4LEPTSPositroniumModel::SampleSecondaries(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSRotExcitationModel::SampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSAttachmentModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4DNAMeltonAttachmentModel::SampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), G4DNASancheExcitationModel::SampleSecondaries(), MyKleinNishinaCompton::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4DNATransformElectronModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4EmMultiModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4eeToHadronsMultiModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4DNAModelInterface::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4TDNAOneStepThermalizationModel< MODEL >::SampleSecondaries(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4CrossSectionDataStore::SampleZandA(), HistoManager::ScoreNewTrack(), G4IonYangFluctuationModel::TheValue(), G4IonChuFluctuationModel::TheValue(), G4hBetheBlochModel::TheValue(), G4hNuclearStoppingModel::TheValue(), G4hParametrisedLossModel::TheValue(), G4hIonEffChargeSquare::TheValue(), G4QAOLowEnergyLoss::TheValue(), and FCALSteppingAction::UserSteppingAction().
G4double G4DynamicParticle::GetLogKineticEnergy () const inline
Referenced by G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4NeutronElasticXS::GetElementCrossSection(), G4NeutronInelasticXS::GetElementCrossSection(), G4ParticleInelasticXS::GetElementCrossSection(), G4NeutronCaptureXS::GetElementCrossSection(), G4NeutronElasticXS::GetIsoCrossSection(), G4ParticleInelasticXS::GetIsoCrossSection(), G4NeutronInelasticXS::GetIsoCrossSection(), G4NeutronCaptureXS::GetIsoCrossSection(), G4VEmProcess::MeanFreePath(), G4VEnergyLossProcess::MeanFreePath(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4XrayRayleighModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), and G4CrossSectionDataStore::SampleZandA().
G4double G4DynamicParticle::GetMagneticMoment () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ParticleChange::Initialize(), and G4FieldTrackUpdator::Update().
G4double G4DynamicParticle::GetMass () const inline
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4DecayProducts::Boost(), G4HadronCrossSections::CalcScatteringCrossSections(), G4Track::CalculateVelocity(), G4HadronicProcess::CheckResult(), G4FieldTrackUpdator::CreateFieldTrack(), G4PionDecayMakeSpin::DaughterPolarization(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4PAIPhotModel::Dispersion(), G4PAIModel::Dispersion(), export_G4DynamicParticle(), G4HadronicProcess::FillResult(), G4hImpactIonisation::GetConstraints(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4InuclParticle::getMass(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4ParticleChange::Initialize(), G4DecayProducts::IsChecked(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4Decay::PostStepGetPhysicalInteractionLength(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4VPartonStringModel::Scatter(), G4SteppingManager::SetInitialStep(), G4IonYangFluctuationModel::TheValue(), G4IonChuFluctuationModel::TheValue(), G4hBetheBlochModel::TheValue(), G4hParametrisedLossModel::TheValue(), G4hNuclearStoppingModel::TheValue(), G4hIonEffChargeSquare::TheValue(), G4FieldTrackUpdator::Update(), and G4ParticleChangeForTransport::UpdateStepForAlongStep().
G4ThreeVector G4DynamicParticle::GetMomentum () const inline
Referenced by G4ParticleHPFinalState::adjust_final_state(), XrayFluoAnalysisManager::analyseStepping(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4PionDecayMakeSpin::DaughterPolarization(), G4SingleScatter::DoCollisionStep(), export_G4DynamicParticle(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4SynchrotronRadiation::GetMeanFreePath(), G4ReactionProduct::operator=(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), and FCALSteppingAction::UserSteppingAction().
const G4ThreeVector& G4DynamicParticle::GetMomentumDirection () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4DecayProducts::Boost(), G4ElectroVDNuclearModel::CalculateHadronicVertex(), G4MuonVDNuclearModel::CalculateHadronicVertex(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4ITTransportation::ComputeStep(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4RadioactiveDecay::DecayIt(), G4SingleScatter::DoCollisionStep(), export_G4DynamicParticle(), G4HadronicProcess::FillResult(), G4PrimaryTransformer::GenerateSingleTrack(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4HadProjectile::InitialiseLocal(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), G4DecayProducts::IsChecked(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4PolarizedComptonModel::PrintWarning(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4PhotoElectricAngularGeneratorPolarized::SampleDirection(), G4DeltaAngleFreeScat::SampleDirection(), G4DipBustGenerator::SampleDirection(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4PhotoElectricAngularGeneratorSimple::SampleDirection(), G4DeltaAngle::SampleDirection(), G4AngleDirect::SampleDirection(), G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4Generator2BN::SampleDirection(), G4ModifiedTsai::SampleDirection(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4Generator2BS::SampleDirection(), G4DNARuddAngle::SampleDirectionForShell(), G4DNABornAngle::SampleDirectionForShell(), G4DipBustGenerator::SamplePairDirections(), G4ModifiedTsai::SamplePairDirections(), G4VEmAngularDistribution::SamplePairDirections(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSIonisationModel::SampleSecondaries(), G4LEPTSPositroniumModel::SampleSecondaries(), G4LEPTSRotExcitationModel::SampleSecondaries(), G4LEPTSVibExcitationModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4DNASancheExcitationModel::SampleSecondaries(), MyKleinNishinaCompton::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), HistoManager::ScoreNewTrack(), and PHG4ZDCSteppingAction::UserSteppingAction().
G4int G4DynamicParticle::GetOccupancy (G4int orbit) const inline
Referenced by export_G4DynamicParticle().
const G4ParticleDefinition* G4DynamicParticle::GetParticleDefinition () const inline
Referenced by G4Transportation::AlongStepDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4RadioactiveDecayBase::CollimateDecay(), G4RadioactiveDecay::CollimateDecay(), G4RadioactiveDecayBase::CollimateDecayProduct(), G4RadioactiveDecay::CollimateDecayProduct(), G4ParticleHPInelasticCompFS::CompositeApply(), G4RadioactiveDecayBase::DecayAnalog(), G4RadioactiveDecay::DecayIt(), G4CrossSectionDataStore::GetCrossSection(), G4LossTableManager::GetDEDXDispersion(), G4PiNuclearCrossSection::GetElementCrossSection(), G4VEmModel::MaxSecondaryKinEnergy(), G4HadronicProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4DeltaAngle::SampleDirection(), G4XrayRayleighModel::SampleSecondaries(), G4EmMultiModel::SampleSecondaries(), G4DNAModelInterface::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4VPartonStringModel::Scatter(), G4FieldTrackUpdator::Update(), and PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
G4int G4DynamicParticle::GetPDGcode () const inline
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), export_G4DynamicParticle(), G4HadronCrossSections::GetParticleCode(), and G4SmartTrackStack::PushToStack().
const G4ThreeVector& G4DynamicParticle::GetPolarization () const inline
Referenced by G4DecayWithSpin::AtRestDoIt(), G4FieldTrackUpdator::CreateFieldTrack(), G4FastStep::CreateSecondaryTrack(), export_G4DynamicParticle(), G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4ParticleChangeForDecay::Initialize(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), G4DecayWithSpin::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4PolarizedComptonModel::PrintWarning(), G4PhotoElectricAngularGeneratorPolarized::SampleDirection(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), and G4FieldTrackUpdator::Update().
const G4DecayProducts* G4DynamicParticle::GetPreAssignedDecayProducts () const inline
Referenced by G4AdjointProcessEquivalentToDirectProcess::AlongStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::AlongStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4PrimaryTransformer::CheckDynamicParticle(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4DecayProducts::G4DecayProducts(), G4DecayProducts::operator=(), G4AdjointProcessEquivalentToDirectProcess::PostStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4PrimaryTransformer::SetDecayProducts(), and G4AdjointProcessEquivalentToDirectProcess::StartTracking().
G4double G4DynamicParticle::GetPreAssignedDecayProperTime () const inline
Referenced by G4Decay::AtRestGetPhysicalInteractionLength(), G4UnknownDecay::DecayIt(), export_G4DynamicParticle(), G4DecayProducts::G4DecayProducts(), G4DecayProducts::operator=(), G4UnknownDecay::PostStepGetPhysicalInteractionLength(), and G4Decay::PostStepGetPhysicalInteractionLength().
G4PrimaryParticle* G4DynamicParticle::GetPrimaryParticle () const inline
Referenced by Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), export_G4DynamicParticle(), Par02TrackingAction::PostUserTrackingAction(), PHG4TruthTrackingAction::PreUserTrackingAction(), and RE01Trajectory::RE01Trajectory().
G4double G4DynamicParticle::GetProperTime () const inline
Referenced by export_G4DynamicParticle(), G4ParticleChange::Initialize(), and G4FastStep::Initialize().
G4double G4DynamicParticle::GetSpin () const inline
G4double G4DynamicParticle::GetTotalEnergy () const inline
Referenced by G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LFission::ApplyYourself(), G4DecayProducts::Boost(), G4ElectroVDNuclearModel::CalculateHadronicVertex(), G4MuonVDNuclearModel::CalculateHadronicVertex(), G4HadronicProcess::CheckResult(), G4PionDecayMakeSpin::DaughterPolarization(), G4MuonDecayChannelWithSpin::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), export_G4DynamicParticle(), G4NeutrinoElectronNcXsc::GetElementCrossSection(), G4NeutrinoElectronCcXsc::GetElementCrossSection(), G4InuclParticle::getEnergy(), G4MuNeutrinoNucleusTotXsc::GetIsoCrossSection(), G4OpMieHG::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4OpWLS::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4NeutronElectronElXsc::GetRosenbluthXsc(), G4Pythia6Decayer::ImportDecayProducts(), G4DecayProducts::IsChecked(), G4NeutrinoElectronNcXsc::IsElementApplicable(), G4NeutrinoElectronCcXsc::IsElementApplicable(), G4ReactionProduct::operator=(), G4SmartTrackStack::PopFromStack(), G4SynchrotronRadiation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4SmartTrackStack::PushToStack(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4DeltaAngleFreeScat::SampleDirection(), G4DeltaAngle::SampleDirection(), G4Generator2BN::SampleDirection(), G4Generator2BS::SampleDirection(), G4AdjointBremsstrahlungModel::SampleSecondaries(), PHG4ZDCSteppingAction::UserSteppingAction(), and FCALSteppingAction::UserSteppingAction().
G4double G4DynamicParticle::GetTotalMomentum () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LFission::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4DecayProducts::Boost(), G4HadronCrossSections::CalcScatteringCrossSections(), G4Track::CalculateVelocityForOpticalPhoton(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), export_G4DynamicParticle(), G4ChargeExchangeProcess::GetElementCrossSection(), G4QuasiElasticChannel::GetFraction(), G4ChipsAntiBaryonInelasticXS::GetIsoCrossSection(), G4ChipsProtonElasticXS::GetIsoCrossSection(), G4ChipsProtonInelasticXS::GetIsoCrossSection(), G4ChipsHyperonElasticXS::GetIsoCrossSection(), G4ChipsHyperonInelasticXS::GetIsoCrossSection(), G4ChipsKaonMinusInelasticXS::GetIsoCrossSection(), G4ChipsKaonPlusElasticXS::GetIsoCrossSection(), G4ChipsPionPlusElasticXS::GetIsoCrossSection(), G4ChipsKaonMinusElasticXS::GetIsoCrossSection(), G4ChipsNeutronElasticXS::GetIsoCrossSection(), G4ChipsPionMinusElasticXS::GetIsoCrossSection(), G4ChipsPionMinusInelasticXS::GetIsoCrossSection(), G4ChipsAntiBaryonElasticXS::GetIsoCrossSection(), G4ChipsKaonPlusInelasticXS::GetIsoCrossSection(), G4ChipsNeutronInelasticXS::GetIsoCrossSection(), G4ChipsPionPlusInelasticXS::GetIsoCrossSection(), G4ChipsKaonZeroElasticXS::GetIsoCrossSection(), G4ChipsKaonZeroInelasticXS::GetIsoCrossSection(), G4OpAbsorption::GetMeanFreePath(), G4OpRayleigh::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4InuclParticle::getMomModule(), G4DecayProducts::IsChecked(), G4OpAbsorption::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4DeltaAngleFreeScat::SampleDirection(), G4DeltaAngle::SampleDirection(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), PHG4ZDCSteppingAction::UserSteppingAction(), and FCALSteppingAction::UserSteppingAction().
G4int G4DynamicParticle::GetTotalOccupancy () const inline
Referenced by export_G4DynamicParticle().
G4int G4DynamicParticle::GetVerboseLevel () const inline
Referenced by export_G4DynamicParticle().
void G4DynamicParticle::operator delete (void * aDynamicParticle) inline
void* G4DynamicParticle::operator new (size_t) inline
G4bool G4DynamicParticle::operator!= (const G4DynamicParticle & right) const
Definition at line 358 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 358 of file G4DynamicParticle.cc
G4DynamicParticle & G4DynamicParticle::operator= (const G4DynamicParticle & right)
Definition at line 282 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 282 of file G4DynamicParticle.cc
References theDynamicalCharge, theDynamicalMagneticMoment, theDynamicalMass, theDynamicalSpin, theElectronOccupancy, theKineticEnergy, theMomentumDirection, theParticleDefinition, thePDGcode, thePolarization, thePreAssignedDecayProducts, thePreAssignedDecayTime, theProperTime, and verboseLevel.
G4bool G4DynamicParticle::operator== (const G4DynamicParticle & right) const
Definition at line 352 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 352 of file G4DynamicParticle.cc
void G4DynamicParticle::RemoveElectron (G4int orbit, G4int number = 1) inline
void G4DynamicParticle::Set4Momentum (const G4LorentzVector & momentum)
Definition at line 395 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 395 of file G4DynamicParticle.cc
References kdfinder::abs(), EnergyMRA2, G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag2(), SetKineticEnergy(), SetMomentumDirection(), CLHEP::HepLorentzVector::t(), theDynamicalMass, theParticleDefinition, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4DecayProducts::Boost(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4MuonicAtomDecay::FillResult(), G4DynamicParticle(), G4InuclParticle::G4InuclParticle(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4eeToHadronsModel::SampleSecondaries(), G4VPartonStringModel::Scatter(), and G4InuclParticle::setMomentum().
void G4DynamicParticle::SetCharge (G4double charge) inline
Referenced by G4PrimaryTransformer::GenerateSingleTrack(), G4ErrorPropagator::InitG4Track(), and G4PrimaryTransformer::SetDecayProducts().
void G4DynamicParticle::SetCharge (G4int chargeInUnitOfEplus) inline
void G4DynamicParticle::SetDefinition (const G4ParticleDefinition * aParticleDefinition)
Definition at line 319 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 319 of file G4DynamicParticle.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), theDynamicalCharge, theDynamicalMagneticMoment, theDynamicalMass, theDynamicalSpin, theElectronOccupancy, theParticleDefinition, thePreAssignedDecayProducts, and verboseLevel.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4AdjointProcessEquivalentToDirectProcess::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::AlongStepGetPhysicalInteractionLength(), G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4ParticleHPInelasticCompFS::CompositeApply(), G4HadronicProcessStore::FindProcess(), G4ParticleHPGamma::GetDecayGammas(), G4ParticleHPFSFissionFS::GetPhotons(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroLongExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4LightMedia::NeutronExchange(), G4LightMedia::OmegaMinusExchange(), G4LightMedia::PionPlusExchange(), G4AdjointProcessEquivalentToDirectProcess::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4LightMedia::ProtonExchange(), G4Nucleus::ReturnTargetParticle(), G4PAIPhotModel::SampleSecondaries(), G4InuclParticle::setDefinition(), G4RPGInelastic::SetUpChange(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4RPGNeutronInelastic::SlowNeutron(), G4RPGProtonInelastic::SlowProton(), G4AdjointProcessEquivalentToDirectProcess::StartTracking(), G4EmCalculator::UpdateParticle(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
void G4DynamicParticle::SetKineticEnergy (G4double aEnergy) inline
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4ChargeExchange::ApplyYourself(), G4LFission::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4EmCalculator::ComputeDEDX(), G4HadronicProcess::FillResult(), G4DynamicParticle(), G4HadElementSelector::G4HadElementSelector(), G4HadronicProcessStore::GetCaptureCrossSectionPerAtom(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerAtom(), G4ParticleHPGamma::GetDecayGammas(), G4EmCalculator::GetDEDX(), G4HadronicProcessStore::GetElasticCrossSectionPerAtom(), G4TripathiLightCrossSection::GetElementCrossSection(), G4HadronicProcessStore::GetFissionCrossSectionPerAtom(), G4HadronicProcessStore::GetInelasticCrossSectionPerAtom(), G4HadronXSDataTable::Initialise(), G4FastPathHadronicCrossSection::fastPathEntry::Initialize(), G4LowEnergyIonisation::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4PAIPhotModel::SampleSecondaries(), Set4Momentum(), G4InuclParticle::setKineticEnergy(), SetMomentum(), and G4EmCalculator::UpdateParticle().
void G4DynamicParticle::SetMagneticMoment (G4double magneticMoment) inline
void G4DynamicParticle::SetMass (G4double mass) inline
Referenced by G4HadronicProcess::FillResult(), G4PrimaryTransformer::GenerateSingleTrack(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4PrimaryTransformer::SetDecayProducts(), and G4InuclParticle::setMass().
void G4DynamicParticle::SetMomentum (const G4ThreeVector & momentum)
Definition at line 381 of file G4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 381 of file G4DynamicParticle.cc
References CLHEP::Hep3Vector::mag2(), mass, SetKineticEnergy(), SetMomentumDirection(), theDynamicalMass, and CLHEP::Hep3Vector::unit().
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), G4DynamicParticle(), G4ParticleHPFSFissionFS::GetPhotons(), G4InuclParticle::setMomentum(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
void G4DynamicParticle::SetMomentumDirection (const G4ThreeVector & aDirection) inline
Referenced by G4LFission::ApplyYourself(), G4RadioactiveDecayBase::CollimateDecayProduct(), G4RadioactiveDecay::CollimateDecayProduct(), G4FastStep::CreateSecondaryTrack(), G4HadronicProcess::FillResult(), G4DynamicParticle(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4PAIPhotModel::SampleSecondaries(), Set4Momentum(), and SetMomentum().
void G4DynamicParticle::SetMomentumDirection (G4double px, G4double py, G4double pz) inline
void G4DynamicParticle::SetPDGcode (G4int c) inline
Referenced by G4PrimaryTransformer::GenerateSingleTrack().
void G4DynamicParticle::SetPolarization (const G4ThreeVector &) inline
Referenced by G4FastStep::CreateSecondaryTrack(), G4PionDecayMakeSpin::DaughterPolarization(), G4PrimaryTransformer::GenerateSingleTrack(), G4ErrorPropagator::InitG4Track(), G4SynchrotronRadiation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), and G4PrimaryTransformer::SetDecayProducts().
void G4DynamicParticle::SetPolarization (G4double polX, G4double polY, G4double polZ) inline
void G4DynamicParticle::SetPreAssignedDecayProducts (G4DecayProducts * aDecayProducts) inline
Referenced by G4AdjointProcessEquivalentToDirectProcess::AlongStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::AlongStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4DecayProducts::G4DecayProducts(), G4DecayProducts::operator=(), G4AdjointProcessEquivalentToDirectProcess::PostStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4PrimaryTransformer::SetDecayProducts(), and G4AdjointProcessEquivalentToDirectProcess::StartTracking().
void G4DynamicParticle::SetPreAssignedDecayProperTime (G4double) inline
Referenced by G4DecayProducts::G4DecayProducts(), G4PrimaryTransformer::GenerateSingleTrack(), G4DecayProducts::operator=(), and G4PrimaryTransformer::SetDecayProducts().
void G4DynamicParticle::SetPrimaryParticle (G4PrimaryParticle * p) inline
Referenced by G4PrimaryTransformer::GenerateSingleTrack(), and G4PrimaryTransformer::SetDecayProducts().
void G4DynamicParticle::SetProperTime (G4double) inline
Referenced by G4ITDecay::DecayIt().
void G4DynamicParticle::SetSpin (G4double spin) inline
void G4DynamicParticle::SetSpin (G4int spinInUnitOfHalfInteger) inline
void G4DynamicParticle::SetVerboseLevel (G4int value) inline
Referenced by export_G4DynamicParticle().
Member Data Documentation
G4PrimaryParticle* G4DynamicParticle::primaryParticle private
Definition at line 251 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 251 of file G4DynamicParticle.hh
G4double G4DynamicParticle::theDynamicalCharge private
Definition at line 264 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 264 of file G4DynamicParticle.hh
Referenced by operator=(), and SetDefinition().
G4double G4DynamicParticle::theDynamicalMagneticMoment private
Definition at line 268 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 268 of file G4DynamicParticle.hh
Referenced by operator=(), and SetDefinition().
G4double G4DynamicParticle::theDynamicalMass private
Definition at line 262 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 262 of file G4DynamicParticle.hh
Referenced by G4DynamicParticle(), operator=(), Set4Momentum(), SetDefinition(), and SetMomentum().
G4double G4DynamicParticle::theDynamicalSpin private
Definition at line 266 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 266 of file G4DynamicParticle.hh
Referenced by operator=(), and SetDefinition().
G4ElectronOccupancy* G4DynamicParticle::theElectronOccupancy private
Definition at line 247 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 247 of file G4DynamicParticle.hh
Referenced by AllocateElectronOccupancy(), G4DynamicParticle(), operator=(), SetDefinition(), and ~G4DynamicParticle().
G4double G4DynamicParticle::theKineticEnergy private
Definition at line 256 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 256 of file G4DynamicParticle.hh
Referenced by operator=().
G4double G4DynamicParticle::theLogKineticEnergy mutable private
Definition at line 258 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 258 of file G4DynamicParticle.hh
G4ThreeVector G4DynamicParticle::theMomentumDirection private
Definition at line 239 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 239 of file G4DynamicParticle.hh
Referenced by operator=().
const G4ParticleDefinition* G4DynamicParticle::theParticleDefinition private
Definition at line 244 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 244 of file G4DynamicParticle.hh
Referenced by AllocateElectronOccupancy(), operator=(), Set4Momentum(), and SetDefinition().
G4int G4DynamicParticle::thePDGcode private
Definition at line 274 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 274 of file G4DynamicParticle.hh
Referenced by operator=().
G4ThreeVector G4DynamicParticle::thePolarization private
Definition at line 242 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 242 of file G4DynamicParticle.hh
Referenced by operator=().
G4DecayProducts* G4DynamicParticle::thePreAssignedDecayProducts private
Definition at line 249 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 249 of file G4DynamicParticle.hh
Referenced by operator=(), SetDefinition(), and ~G4DynamicParticle().
G4double G4DynamicParticle::thePreAssignedDecayTime private
Definition at line 270 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 270 of file G4DynamicParticle.hh
Referenced by operator=().
G4double G4DynamicParticle::theProperTime private
Definition at line 260 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 260 of file G4DynamicParticle.hh
Referenced by operator=().
G4int G4DynamicParticle::verboseLevel private
Definition at line 272 of file G4DynamicParticle.hh.
View newest version in sPHENIX GitHub at line 272 of file G4DynamicParticle.hh
Referenced by operator=(), and SetDefinition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4DynamicParticle.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4DynamicParticle.cc