ECCE @ EIC Software: G4VEmFluctuationModel Class Reference
G4VEmFluctuationModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmFluctuationModel.hh>
Public Member Functions
G4VEmFluctuationModel (const G4String &nam)
virtual ~G4VEmFluctuationModel ()
virtual G4double SampleFluctuations (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmax, G4double length, G4double meanLoss)=0
virtual G4double Dispersion (const G4Material *, const G4DynamicParticle *, G4double tmax, G4double length)=0
virtual void InitialiseMe (const G4ParticleDefinition *)
virtual void SetParticleAndCharge (const G4ParticleDefinition *, G4double q2)
const G4String & GetName () const
Private Member Functions
G4VEmFluctuationModel & operator= (const G4VEmFluctuationModel &right)=delete
G4VEmFluctuationModel (const G4VEmFluctuationModel &)=delete
Private Attributes
const G4String name
G4LossTableManager * fManager
Detailed Description
Definition at line 68 of file G4VEmFluctuationModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VEmFluctuationModel.hh
Constructor & Destructor Documentation
G4VEmFluctuationModel::G4VEmFluctuationModel (const G4String & nam) explicit
Definition at line 55 of file G4VEmFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VEmFluctuationModel.cc
References fManager, G4LossTableManager::Instance(), and G4LossTableManager::Register().
G4VEmFluctuationModel::~G4VEmFluctuationModel () virtual
Definition at line 62 of file G4VEmFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4VEmFluctuationModel.cc
References G4LossTableManager::DeRegister(), and fManager.
G4VEmFluctuationModel::G4VEmFluctuationModel (const G4VEmFluctuationModel &) private delete
Member Function Documentation
virtual G4double G4VEmFluctuationModel::Dispersion (const G4Material * , const G4DynamicParticle * , G4double tmax, G4double length) pure virtual
Implemented in G4PAIModel, G4mplIonisationWithDeltaModel, G4PAIPhotModel, G4mplIonisationModel, G4IonFluctuations, G4AtimaFluctuations, G4UniversalFluctuation, and G4BohrFluctuations.
Referenced by G4VEnergyLossProcess::GetDEDXDispersion().
const G4String & G4VEmFluctuationModel::GetName (void) const inline
Definition at line 120 of file G4VEmFluctuationModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VEmFluctuationModel.hh
References name.
Referenced by G4LossTableManager::Register(), and G4EmConfigurator::SetModelForRegion().
void G4VEmFluctuationModel::InitialiseMe (const G4ParticleDefinition *) virtual
Reimplemented in G4IonFluctuations, G4AtimaFluctuations, G4UniversalFluctuation, and G4BohrFluctuations.
Definition at line 67 of file G4VEmFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 67 of file G4VEmFluctuationModel.cc
G4VEmFluctuationModel& G4VEmFluctuationModel::operator= (const G4VEmFluctuationModel & right) private delete
virtual G4double G4VEmFluctuationModel::SampleFluctuations (const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double tmax, G4double length, G4double meanLoss) pure virtual
Implemented in G4PAIModel, G4PAIPhotModel, G4mplIonisationWithDeltaModel, G4mplIonisationModel, G4IonFluctuations, G4AtimaFluctuations, G4UniversalFluctuation, and G4BohrFluctuations.
Referenced by G4VEnergyLossProcess::AlongStepDoIt().
void G4VEmFluctuationModel::SetParticleAndCharge (const G4ParticleDefinition * , G4double q2) virtual
Reimplemented in G4IonFluctuations, G4AtimaFluctuations, and G4UniversalFluctuation.
Definition at line 70 of file G4VEmFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4VEmFluctuationModel.cc
Referenced by G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), and G4BraggModel::GetChargeSquareRatio().
Member Data Documentation
G4LossTableManager* G4VEmFluctuationModel::fManager private
Definition at line 114 of file G4VEmFluctuationModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VEmFluctuationModel.hh
Referenced by G4VEmFluctuationModel(), and ~G4VEmFluctuationModel().
const G4String G4VEmFluctuationModel::name private
Definition at line 113 of file G4VEmFluctuationModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VEmFluctuationModel.hh
Referenced by GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmFluctuationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4VEmFluctuationModel.cc