ECCE @ EIC Software: G4SmartFilter< T > Class Template Reference
G4SmartFilter< T > Class Template Reference abstract
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4SmartFilter.hh>
Public Member Functions
G4SmartFilter (const G4String &name)
virtual ~G4SmartFilter ()
virtual G4bool Evaluate (const T &) const =0
virtual void Print (std::ostream &ostr) const =0
virtual void Clear ()=0
G4bool Accept (const T &) const
virtual void PrintAll (std::ostream &ostr) const
virtual void Reset ()
void SetActive (const G4bool &)
G4bool GetActive () const
void SetInvert (const G4bool &)
G4bool GetInvert () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Public Member Functions inherited from G4VFilter< T >
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
G4String Name () const
G4String GetName () const
Private Attributes
G4bool fActive
G4bool fInvert
G4bool fVerbose
size_t fNPassed
size_t fNProcessed
Additional Inherited Members
Public Types inherited from G4VFilter< T >
typedef T Type
Detailed Description
template<typename T>
class G4SmartFilter< T >
Definition at line 38 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 38 of file G4SmartFilter.hh
Constructor & Destructor Documentation
template<typename T > G4SmartFilter< T >::G4SmartFilter (const G4String & name)
Definition at line 90 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 90 of file G4SmartFilter.hh
template<typename T > G4SmartFilter< T >::~G4SmartFilter () virtual
Definition at line 100 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 100 of file G4SmartFilter.hh
Member Function Documentation
template<typename T> G4bool G4SmartFilter< T >::Accept (const T & object) const virtual
Implements G4VFilter< T >.
Definition at line 104 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 104 of file G4SmartFilter.hh
References G4cout, G4endl, and G4VFilter< T >::Name().
template<typename T> virtual void G4SmartFilter< T >::Clear () pure virtual
Implemented in G4AttributeFilterT< T >, G4TrajectoryChargeFilter, G4TrajectoryEncounteredVolumeFilter, G4TrajectoryOriginVolumeFilter, and G4TrajectoryParticleFilter.
template<typename T> virtual G4bool G4SmartFilter< T >::Evaluate (const T &) const pure virtual
Implemented in G4AttributeFilterT< T >, G4TrajectoryChargeFilter, G4TrajectoryEncounteredVolumeFilter, G4TrajectoryOriginVolumeFilter, and G4TrajectoryParticleFilter.
template<typename T > G4bool G4SmartFilter< T >::GetActive () const
Definition at line 172 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 172 of file G4SmartFilter.hh
template<typename T > G4bool G4SmartFilter< T >::GetInvert () const
Definition at line 186 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 186 of file G4SmartFilter.hh
template<typename T > G4bool G4SmartFilter< T >::GetVerbose () const
Definition at line 200 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 200 of file G4SmartFilter.hh
template<typename T> virtual void G4SmartFilter< T >::Print (std::ostream & ostr) const pure virtual
Implemented in G4AttributeFilterT< T >, G4TrajectoryChargeFilter, G4TrajectoryEncounteredVolumeFilter, G4TrajectoryOriginVolumeFilter, and G4TrajectoryParticleFilter.
template<typename T > void G4SmartFilter< T >::PrintAll (std::ostream & ostr) const virtual
Implements G4VFilter< T >.
Definition at line 138 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 138 of file G4SmartFilter.hh
References G4endl, G4VFilter< T >::Name(), and pyG4Element::Print().
template<typename T > void G4SmartFilter< T >::Reset () virtual
Implements G4VFilter< T >.
Definition at line 152 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 152 of file G4SmartFilter.hh
References JA::Clear().
template<typename T > void G4SmartFilter< T >::SetActive (const G4bool & active)
Definition at line 165 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 165 of file G4SmartFilter.hh
References active.
template<typename T > void G4SmartFilter< T >::SetInvert (const G4bool & invert)
Definition at line 179 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 179 of file G4SmartFilter.hh
template<typename T > void G4SmartFilter< T >::SetVerbose (const G4bool & verbose)
Definition at line 193 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 193 of file G4SmartFilter.hh
Member Data Documentation
template<typename T> G4bool G4SmartFilter< T >::fActive private
Definition at line 81 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 81 of file G4SmartFilter.hh
template<typename T> G4bool G4SmartFilter< T >::fInvert private
Definition at line 82 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 82 of file G4SmartFilter.hh
template<typename T> size_t G4SmartFilter< T >::fNPassed mutable private
Definition at line 84 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 84 of file G4SmartFilter.hh
template<typename T> size_t G4SmartFilter< T >::fNProcessed mutable private
Definition at line 85 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 85 of file G4SmartFilter.hh
template<typename T> G4bool G4SmartFilter< T >::fVerbose private
Definition at line 83 of file G4SmartFilter.hh.
View newest version in sPHENIX GitHub at line 83 of file G4SmartFilter.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4SmartFilter.hh