ECCE @ EIC Software: G4hIonisation Class Reference
G4hIonisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4hIonisation.hh>
Public Member Functions
G4hIonisation (const G4String &name="hIoni")
virtual ~G4hIonisation ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *p, const G4Material *, G4double cut) final
virtual void PrintInfo () final
virtual void ProcessDescription (std::ostream &) const override
Public Member Functions inherited from G4VEnergyLossProcess
G4VEnergyLossProcess (const G4String &name="EnergyLoss", G4ProcessType type=fElectromagnetic)
virtual ~G4VEnergyLossProcess ()
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
G4PhysicsTable * BuildDEDXTable (G4EmTableType tType=fRestricted)
G4PhysicsTable * BuildLambdaTable (G4EmTableType tType=fRestricted)
virtual void StartTracking (G4Track *) override
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4double SampleSubCutSecondaries (std::vector< G4Track * > &, const G4Step &, G4VEmModel *model, G4int matIdx)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
G4double GetDEDXDispersion (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double length)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double MeanFreePath (const G4Track &track)
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t &idx) const
void AddEmModel (G4int, G4VEmModel *, G4VEmFluctuationModel *fluc=0, const G4Region *region=nullptr)
void UpdateEmModel (const G4String &, G4double, G4double)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
G4int NumberOfModels () const
void SetFluctModel (G4VEmFluctuationModel *)
G4VEmFluctuationModel * FluctModel ()
void SetBaseParticle (const G4ParticleDefinition *p)
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * BaseParticle () const
const G4ParticleDefinition * SecondaryParticle () const
void ActivateSubCutoff (G4bool val, const G4Region *region=nullptr)
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
void ActivateForcedInteraction (G4double length, const G4String &region, G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void AddCollaborativeProcess (G4VEnergyLossProcess *)
void SetLossFluctuations (G4bool val)
void SetIntegral (G4bool val)
G4bool IsIntegral () const
void SetIonisation (G4bool val)
G4bool IsIonisationProcess () const
void SetLinearLossLimit (G4double val)
void SetStepFunction (G4double v1, G4double v2, G4bool lock=true)
void SetLowestEnergyLimit (G4double)
G4int NumberOfSubCutoffRegions () const
void SetDEDXTable (G4PhysicsTable *p, G4EmTableType tType)
void SetCSDARangeTable (G4PhysicsTable *pRange)
void SetRangeTableForLoss (G4PhysicsTable *p)
void SetSecondaryRangeTable (G4PhysicsTable *p)
void SetInverseRangeTable (G4PhysicsTable *p)
void SetLambdaTable (G4PhysicsTable *p)
void SetSubLambdaTable (G4PhysicsTable *p)
void SetDEDXBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
G4double MinKinEnergy () const
void SetMaxKinEnergy (G4double e)
G4double MaxKinEnergy () const
G4double CrossSectionBiasingFactor () const
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetKineticEnergy (G4double range, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4bool TablesAreBuilt () const
G4PhysicsTable * DEDXTable () const
G4PhysicsTable * DEDXTableForSubsec () const
G4PhysicsTable * DEDXunRestrictedTable () const
G4PhysicsTable * IonisationTable () const
G4PhysicsTable * IonisationTableForSubsec () const
G4PhysicsTable * CSDARangeTable () const
G4PhysicsTable * SecondaryRangeTable () const
G4PhysicsTable * RangeTableForLoss () const
G4PhysicsTable * InverseRangeTable () const
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * SubLambdaTable () const
const G4Element * GetCurrentElement () const
void SetDynamicMassCharge (G4double massratio, G4double charge2ratio)
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void InitialiseEnergyLossProcess (const G4ParticleDefinition *, const G4ParticleDefinition *) override
Protected Member Functions inherited from G4VEnergyLossProcess
virtual void StreamProcessInfo (std::ostream &) const
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety) override
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *, G4double cut)
size_t CurrentMaterialCutsCoupleIndex () const
void SelectModel (G4double kinEnergy)
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Member Functions
G4hIonisation & operator= (const G4hIonisation &right)=delete
G4hIonisation (const G4hIonisation &)=delete
Private Attributes
G4bool isInitialised
G4double mass
G4double ratio
G4double eth
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VEnergyLossProcess
G4ParticleChangeForLoss fParticleChange
const G4Material * currentMaterial
const G4MaterialCutsCouple * currentCouple
size_t currentCoupleIndex
G4double preStepLambda
G4double fRange
G4double computedRange
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepScaledEnergy
G4double preStepLogScaledEnergy
G4double preStepRangeEnergy
G4double mfpKinEnergy
Detailed Description
Definition at line 84 of file G4hIonisation.hh.
View newest version in sPHENIX GitHub at line 84 of file G4hIonisation.hh
Constructor & Destructor Documentation
G4hIonisation::G4hIonisation (const G4String & name = "hIoni") explicit
Definition at line 69 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 69 of file G4hIonisation.cc
References G4Electron::Electron(), eth, fIonisation, mass, MeV, ratio, G4VProcess::SetProcessSubType(), and G4VEnergyLossProcess::SetSecondaryParticle().
G4hIonisation::~G4hIonisation () virtual
Definition at line 82 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 82 of file G4hIonisation.cc
G4hIonisation::G4hIonisation (const G4hIonisation &) private delete
Member Function Documentation
void G4hIonisation::InitialiseEnergyLossProcess (const G4ParticleDefinition * part, const G4ParticleDefinition * bpart) override protected virtual
Implements G4VEnergyLossProcess.
Definition at line 106 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 106 of file G4hIonisation.cc
References G4VEnergyLossProcess::AddEmModel(), G4AntiProton::AntiProton(), bin, source.hepunit::electron_mass_c2, emax, CEMC_TOWER::emin, G4VEnergyLossProcess::EmModel(), eth, G4VEnergyLossProcess::FluctModel(), G4lrint(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), G4EmParameters::Instance(), isInitialised, G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), mass, max, G4EmParameters::MaxKinEnergy(), MeV, min, G4EmParameters::MinKinEnergy(), G4EmParameters::NumberOfBinsPerDecade(), pname(), G4Proton::Proton(), source.hepunit::proton_mass_c2, ratio, G4VEnergyLossProcess::SetBaseParticle(), G4VEnergyLossProcess::SetDEDXBinning(), G4VEnergyLossProcess::SetEmModel(), G4VEnergyLossProcess::SetFluctModel(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), G4VEnergyLossProcess::SetMaxKinEnergy(), and G4VEnergyLossProcess::SetMinKinEnergy().
G4bool G4hIonisation::IsApplicable (const G4ParticleDefinition & p) override virtual
Implements G4VEnergyLossProcess.
Definition at line 87 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 87 of file G4hIonisation.cc
References G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::IsShortLived(), and MeV.
G4double G4hIonisation::MinPrimaryEnergy (const G4ParticleDefinition * p, const G4Material * , G4double cut) final virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 95 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 95 of file G4hIonisation.cc
References source.hepunit::electron_mass_c2, G4InuclParticleNames::gam, mass, ratio, and x.
G4hIonisation& G4hIonisation::operator= (const G4hIonisation & right) private delete
void G4hIonisation::PrintInfo () final virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 181 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 181 of file G4hIonisation.cc
void G4hIonisation::ProcessDescription (std::ostream & out) const override virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 186 of file G4hIonisation.cc.
View newest version in sPHENIX GitHub at line 186 of file G4hIonisation.cc
References G4VEnergyLossProcess::ProcessDescription().
Member Data Documentation
G4double G4hIonisation::eth private
Definition at line 120 of file G4hIonisation.hh.
View newest version in sPHENIX GitHub at line 120 of file G4hIonisation.hh
Referenced by G4hIonisation(), and InitialiseEnergyLossProcess().
G4bool G4hIonisation::isInitialised private
Definition at line 116 of file G4hIonisation.hh.
View newest version in sPHENIX GitHub at line 116 of file G4hIonisation.hh
Referenced by InitialiseEnergyLossProcess().
G4double G4hIonisation::mass private
Definition at line 118 of file G4hIonisation.hh.
View newest version in sPHENIX GitHub at line 118 of file G4hIonisation.hh
Referenced by G4hIonisation(), InitialiseEnergyLossProcess(), and MinPrimaryEnergy().
G4double G4hIonisation::ratio private
Definition at line 119 of file G4hIonisation.hh.
View newest version in sPHENIX GitHub at line 119 of file G4hIonisation.hh
Referenced by G4hIonisation(), InitialiseEnergyLossProcess(), and MinPrimaryEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4hIonisation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4hIonisation.cc