ECCE @ EIC Software: G4UIcmdWith3VectorAndUnit Class Reference
G4UIcmdWith3VectorAndUnit Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWith3VectorAndUnit.hh>
Public Member Functions
G4UIcmdWith3VectorAndUnit (const char *theCommandPath, G4UImessenger *theMessenger)
virtual G4int DoIt (G4String parameterList)
G4String ConvertToStringWithBestUnit (G4ThreeVector vec)
G4String ConvertToStringWithDefaultUnit (G4ThreeVector vec)
void SetParameterName (const char *theNameX, const char *theNameY, const char *theNameZ, G4bool omittable, G4bool currentAsDefault=false)
void SetDefaultValue (G4ThreeVector defVal)
void SetUnitCategory (const char *unitCategory)
void SetUnitCandidates (const char *candidateList)
void SetDefaultUnit (const char *defUnit)
Public Member Functions inherited from G4UIcommand
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
size_t GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
size_t GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Static Public Member Functions
static G4ThreeVector GetNew3VectorValue (const char *paramString)
static G4ThreeVector GetNew3VectorRawValue (const char *paramString)
static G4double GetNewUnitValue (const char *paramString)
Static Public Member Functions inherited from G4UIcommand
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Additional Inherited Members
Protected Types inherited from G4UIcommand
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Protected Member Functions inherited from G4UIcommand
G4int CheckNewValue (const char *newValue)
Protected Attributes inherited from G4UIcommand
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Detailed Description
Definition at line 41 of file G4UIcmdWith3VectorAndUnit.hh.
View newest version in sPHENIX GitHub at line 41 of file G4UIcmdWith3VectorAndUnit.hh
Constructor & Destructor Documentation
G4UIcmdWith3VectorAndUnit::G4UIcmdWith3VectorAndUnit (const char * theCommandPath, G4UImessenger * theMessenger)
Definition at line 37 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 37 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIparameter::SetParameterName().
Member Function Documentation
G4String G4UIcmdWith3VectorAndUnit::ConvertToStringWithBestUnit (G4ThreeVector vec)
Definition at line 119 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 119 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::CategoryOf(), G4BestUnit, G4UIcommand::GetParameter(), and G4UIparameter::GetParameterCandidates().
Referenced by ConvertToStringWithDefaultUnit(), and G4MoleculeShootMessenger::GetCurrentValue().
G4String G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit (G4ThreeVector vec)
Definition at line 133 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 133 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::ConvertToString(), ConvertToStringWithBestUnit(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetParameter(), and G4UIparameter::IsOmittable().
G4int G4UIcmdWith3VectorAndUnit::DoIt (G4String parameterList) virtual
Reimplemented from G4UIcommand.
Definition at line 51 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 51 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::CategoryOf(), G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToString(), G4UIcommand::DoIt(), fParameterOutOfCandidates, G4UIcommand::GetParameter(), G4UIcommand::ValueOf(), x, y, and z.
G4ThreeVector G4UIcmdWith3VectorAndUnit::GetNew3VectorRawValue (const char * paramString) static
Definition at line 96 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 96 of file G4UIcmdWith3VectorAndUnit.cc
Referenced by CML2PhantomConstructionMessenger::SetNewValue(), and CML2MainMessenger::SetNewValue().
G4ThreeVector G4UIcmdWith3VectorAndUnit::GetNew3VectorValue (const char * paramString) static
Definition at line 91 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 91 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::ConvertToDimensioned3Vector().
Referenced by G4HepRepMessenger::SetNewValue(), DetectorConstructionMessenger::SetNewValue(), LXeDetectorMessenger::SetNewValue(), G4MatScanMessenger::SetNewValue(), F02FieldMessenger::SetNewValue(), F03FieldMessenger::SetNewValue(), F01FieldMessenger::SetNewValue(), G4RTMessenger::SetNewValue(), G4ParticleGunMessenger::SetNewValue(), G4GlobalMagFieldMessenger::SetNewValue(), CexmcParticleGunMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4EmExtraParametersMessenger::SetNewValue(), G4MoleculeShootMessenger::SetNewValue(), and G4GeneralParticleSourceMessenger::SetNewValue().
G4double G4UIcmdWith3VectorAndUnit::GetNewUnitValue (const char * paramString) static
Definition at line 107 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 107 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::ValueOf().
void G4UIcmdWith3VectorAndUnit::SetDefaultUnit (const char * defUnit)
Definition at line 184 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 184 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::CategoryOf(), G4UIcommand::GetParameter(), G4UIparameter::SetDefaultValue(), G4UIparameter::SetOmittable(), and SetUnitCategory().
Referenced by CexmcParticleGunMessenger::CexmcParticleGunMessenger(), DetectorConstructionMessenger::DetectorConstructionMessenger(), F01FieldMessenger::F01FieldMessenger(), F02FieldMessenger::F02FieldMessenger(), F03FieldMessenger::F03FieldMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4RTMessenger::G4RTMessenger(), G4ScoringMessenger::G4ScoringMessenger(), LXeDetectorMessenger::LXeDetectorMessenger(), and G4GenericMessenger::Command::SetUnit().
void G4UIcmdWith3VectorAndUnit::SetDefaultValue (G4ThreeVector defVal)
Definition at line 162 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 162 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::GetParameter(), G4UIparameter::SetDefaultValue(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DetectorConstructionMessenger::DetectorConstructionMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4MatScanMessenger::G4MatScanMessenger(), and G4RTMessenger::G4RTMessenger().
void G4UIcmdWith3VectorAndUnit::SetParameterName (const char * theNameX, const char * theNameY, const char * theNameZ, G4bool omittable, G4bool currentAsDefault = false)
Definition at line 145 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 145 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIparameter::SetCurrentAsDefault(), G4UIparameter::SetOmittable(), and G4UIparameter::SetParameterName().
Referenced by CexmcParticleGunMessenger::CexmcParticleGunMessenger(), G4GenericMessenger::DeclarePropertyWithUnit(), DetectorConstructionMessenger::DetectorConstructionMessenger(), F01FieldMessenger::F01FieldMessenger(), F02FieldMessenger::F02FieldMessenger(), F03FieldMessenger::F03FieldMessenger(), G4GlobalMagFieldMessenger::G4GlobalMagFieldMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4RTMessenger::G4RTMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), and LXeDetectorMessenger::LXeDetectorMessenger().
void G4UIcmdWith3VectorAndUnit::SetUnitCandidates (const char * candidateList)
Definition at line 177 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 177 of file G4UIcmdWith3VectorAndUnit.cc
References G4UIcommand::GetParameter(), and G4UIparameter::SetParameterCandidates().
Referenced by CexmcParticleGunMessenger::CexmcParticleGunMessenger(), and SetUnitCategory().
void G4UIcmdWith3VectorAndUnit::SetUnitCategory (const char * unitCategory)
Definition at line 172 of file G4UIcmdWith3VectorAndUnit.cc.
View newest version in sPHENIX GitHub at line 172 of file G4UIcmdWith3VectorAndUnit.cc
References SetUnitCandidates(), and G4UIcommand::UnitsList().
Referenced by G4GlobalMagFieldMessenger::G4GlobalMagFieldMessenger(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), SetDefaultUnit(), and G4GenericMessenger::Command::SetUnit().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWith3VectorAndUnit.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIcmdWith3VectorAndUnit.cc