ECCE @ EIC Software: G4RayTrajectoryPoint Class Reference
G4RayTrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RayTrajectoryPoint.hh>
Public Member Functions
G4RayTrajectoryPoint ()
virtual ~G4RayTrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
void SetPreStepAtt (const G4VisAttributes *val)
const G4VisAttributes * GetPreStepAtt () const
void SetPostStepAtt (const G4VisAttributes *val)
const G4VisAttributes * GetPostStepAtt () const
void SetSurfaceNormal (const G4ThreeVector &val)
G4ThreeVector GetSurfaceNormal () const
void SetStepLength (G4double val)
G4double GetStepLength () const
const G4ThreeVector GetPosition () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
virtual const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
const G4VisAttributes * preStepAtt
const G4VisAttributes * postStepAtt
G4ThreeVector surfaceNormal
G4double stepLength
Detailed Description
Definition at line 50 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RayTrajectoryPoint.hh
Constructor & Destructor Documentation
G4RayTrajectoryPoint::G4RayTrajectoryPoint ()
Definition at line 43 of file G4RayTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 43 of file G4RayTrajectoryPoint.cc
G4RayTrajectoryPoint::~G4RayTrajectoryPoint () virtual
Definition at line 49 of file G4RayTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 49 of file G4RayTrajectoryPoint.cc
Member Function Documentation
const G4ThreeVector G4RayTrajectoryPoint::GetPosition (void) const inline virtual
Implements G4VTrajectoryPoint.
Definition at line 77 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RayTrajectoryPoint.hh
const G4VisAttributes* G4RayTrajectoryPoint::GetPostStepAtt () const inline
Definition at line 71 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RayTrajectoryPoint.hh
References postStepAtt.
Referenced by G4TheRayTracer::GenerateColour(), G4RTRun::GetSurfaceColour(), G4TheRayTracer::GetSurfaceColour(), and G4RTRun::RecordEvent().
const G4VisAttributes* G4RayTrajectoryPoint::GetPreStepAtt () const inline
Definition at line 69 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RayTrajectoryPoint.hh
References preStepAtt.
Referenced by G4RTRun::Attenuate(), G4TheRayTracer::Attenuate(), G4RTRun::GetSurfaceColour(), and G4TheRayTracer::GetSurfaceColour().
G4double G4RayTrajectoryPoint::GetStepLength () const inline
Definition at line 75 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RayTrajectoryPoint.hh
References stepLength.
Referenced by G4RTRun::Attenuate(), and G4TheRayTracer::Attenuate().
G4ThreeVector G4RayTrajectoryPoint::GetSurfaceNormal () const inline
Definition at line 73 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 73 of file G4RayTrajectoryPoint.hh
References surfaceNormal.
Referenced by G4RTRun::GetSurfaceColour(), and G4TheRayTracer::GetSurfaceColour().
void G4RayTrajectoryPoint::operator delete (void * aTrajectoryPoint) inline
Definition at line 94 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RayTrajectoryPoint.hh
References rayTrajectoryPointAllocator().
void * G4RayTrajectoryPoint::operator new (size_t) inline
Definition at line 87 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RayTrajectoryPoint.hh
References rayTrajectoryPointAllocator().
void G4RayTrajectoryPoint::SetPostStepAtt (const G4VisAttributes * val) inline
Definition at line 70 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RayTrajectoryPoint.hh
References postStepAtt.
Referenced by G4RayTrajectory::AppendStep().
void G4RayTrajectoryPoint::SetPreStepAtt (const G4VisAttributes * val) inline
Definition at line 68 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RayTrajectoryPoint.hh
References preStepAtt.
Referenced by G4RayTrajectory::AppendStep().
void G4RayTrajectoryPoint::SetStepLength (G4double val) inline
Definition at line 74 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 74 of file G4RayTrajectoryPoint.hh
References stepLength.
Referenced by G4RayTrajectory::AppendStep().
void G4RayTrajectoryPoint::SetSurfaceNormal (const G4ThreeVector & val) inline
Definition at line 72 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 72 of file G4RayTrajectoryPoint.hh
References surfaceNormal.
Referenced by G4RayTrajectory::AppendStep().
Member Data Documentation
const G4VisAttributes* G4RayTrajectoryPoint::postStepAtt private
Definition at line 63 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RayTrajectoryPoint.hh
Referenced by GetPostStepAtt(), and SetPostStepAtt().
const G4VisAttributes* G4RayTrajectoryPoint::preStepAtt private
Definition at line 62 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RayTrajectoryPoint.hh
Referenced by GetPreStepAtt(), and SetPreStepAtt().
G4double G4RayTrajectoryPoint::stepLength private
Definition at line 65 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RayTrajectoryPoint.hh
Referenced by GetStepLength(), and SetStepLength().
G4ThreeVector G4RayTrajectoryPoint::surfaceNormal private
Definition at line 64 of file G4RayTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RayTrajectoryPoint.hh
Referenced by GetSurfaceNormal(), and SetSurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RayTrajectoryPoint.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RayTrajectoryPoint.cc