ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/HEPRandom/include/G4RandomDirection.hh File Reference
G4RandomDirection.hh File Reference
#include <CLHEP/Units/PhysicalConstants.h>
#include "globals.hh"
#include "Randomize.hh"
#include "G4ThreeVector.hh"
Functions
G4ThreeVector G4RandomDirection ()
G4ThreeVector G4RandomDirection (G4double cosTheta)
Function Documentation
G4ThreeVector G4RandomDirection () inline
Definition at line 58 of file G4RandomDirection.hh.
View newest version in sPHENIX GitHub at line 58 of file G4RandomDirection.hh
References a, b, G4UniformRand, Acts::UnitConstants::u, and v.
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4EmCaptureCascade::AddNewParticle(), G4NeutronRadCapture::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4UnstableFragmentBreakUp::BreakUpChain(), XPhononStackingAction::ClassifyNewTrack(), G4NeutrinoNucleusModel::ClusterDecay(), G4LightTargetCollider::collide(), G4PionDecayMakeSpin::DaughterPolarization(), G4FermiPhaseSpaceDecay::Decay(), G4DNABrownianTransportation::Diffusion(), G4GEMChannelVI::EmittedFragment(), G4CompetitiveFission::EmittedFragment(), G4EvaporationChannel::EmittedFragment(), G4GEMChannel::EmittedFragment(), G4StatMFChannel::FragmentsMomenta(), G4LambertianRand(), G4RandomPointOnEllipsoid(), XPrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), MyPrimaryGeneratorActionFromFile::GeneratePrimaries(), DNA::Penetration::GetGaussianPenetrationFromRmean3D(), DNA::Penetration::Kreipl2009::GetPenetration(), G4Orb::GetPointOnSurface(), G4PhononDownconversion::MakeTTSecondaries(), G4NeutrinoNucleusModel::MesonDecay(), G4PreCompoundEmission::PerformEmission(), G4StatMFChannel::PlaceFragments(), G4PhononScattering::PostStepDoIt(), G4FermiBreakUpVI::SampleDecay(), G4GEMProbabilityVI::SampleEvaporationFragment(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), and XPrimaryGeneratorAction::XPrimaryGeneratorAction().
G4ThreeVector G4RandomDirection (G4double cosTheta) inline
Definition at line 70 of file G4RandomDirection.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RandomDirection.hh
References G4UniformRand, phi, CLHEP::twopi, and z.