ECCE @ EIC Software: G4CollisionOutput Class Reference
G4CollisionOutput Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CollisionOutput.hh>
Public Member Functions
G4CollisionOutput ()
G4CollisionOutput & operator= (const G4CollisionOutput &right)
void setVerboseLevel (G4int verbose)
void reset ()
void add (const G4CollisionOutput &right)
void addOutgoingParticle (const G4InuclElementaryParticle &particle)
void addOutgoingParticles (const std::vector< G4InuclElementaryParticle > &particles)
void addOutgoingNucleus (const G4InuclNuclei &nuclei)
void addOutgoingNuclei (const std::vector< G4InuclNuclei > &nuclea)
void addOutgoingParticle (const G4CascadParticle &cparticle)
void addOutgoingParticles (const std::vector< G4CascadParticle > &cparticles)
void addOutgoingParticles (const G4ReactionProductVector *rproducts)
void addRecoilFragment (const G4Fragment *aFragment)
void addRecoilFragment (const G4Fragment &aFragment)
void removeOutgoingParticle (G4int index)
void removeOutgoingParticle (const G4InuclElementaryParticle &particle)
void removeOutgoingParticle (const G4InuclElementaryParticle *particle)
void removeOutgoingNucleus (G4int index)
void removeOutgoingNucleus (const G4InuclNuclei &nuclei)
void removeOutgoingNucleus (const G4InuclNuclei *nuclei)
void removeRecoilFragment (G4int index=-1)
G4int numberOfOutgoingParticles () const
const std::vector
< G4InuclElementaryParticle > & getOutgoingParticles () const
std::vector
< G4InuclElementaryParticle > & getOutgoingParticles ()
G4int numberOfOutgoingNuclei () const
const std::vector
< G4InuclNuclei > & getOutgoingNuclei () const
std::vector< G4InuclNuclei > & getOutgoingNuclei ()
G4int numberOfFragments () const
const G4Fragment & getRecoilFragment (G4int index=0) const
const std::vector< G4Fragment > & getRecoilFragments () const
std::vector< G4Fragment > & getRecoilFragments ()
G4LorentzVector getTotalOutputMomentum () const
G4int getTotalCharge () const
G4int getTotalBaryonNumber () const
G4int getTotalStrangeness () const
void printCollisionOutput (std::ostream &os=G4cout) const
void boostToLabFrame (const G4LorentzConvertor &convertor)
G4LorentzVector boostToLabFrame (G4LorentzVector mom, const G4LorentzConvertor &convertor) const
void rotateEvent (const G4LorentzRotation &rotate)
void trivialise (G4InuclParticle *bullet, G4InuclParticle *target)
void setOnShell (G4InuclParticle *bullet, G4InuclParticle *target)
void setRemainingExitationEnergy ()
double getRemainingExitationEnergy () const
G4bool acceptable () const
Private Member Functions
std::pair< std::pair< G4int,
G4int >, G4int > selectPairToTune (G4double de) const
G4bool tuneSelectedPair (G4LorentzVector &mom1, G4LorentzVector &mom2, G4int mom_index) const
Private Attributes
G4int verboseLevel
std::vector
< G4InuclElementaryParticle > outgoingParticles
std::vector< G4InuclNuclei > outgoingNuclei
std::vector< G4Fragment > recoilFragments
G4double eex_rest
G4LorentzVector mom_non_cons
G4bool on_shell
Static Private Attributes
static const G4Fragment emptyFragment
Detailed Description
Definition at line 66 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 66 of file G4CollisionOutput.hh
Constructor & Destructor Documentation
G4CollisionOutput::G4CollisionOutput ()
Definition at line 84 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 84 of file G4CollisionOutput.cc
References G4cout, G4endl, and verboseLevel.
Member Function Documentation
G4bool G4CollisionOutput::acceptable () const inline
Definition at line 173 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 173 of file G4CollisionOutput.hh
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::finishCascade().
void G4CollisionOutput::add (const G4CollisionOutput & right)
Definition at line 123 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 123 of file G4CollisionOutput.cc
References addOutgoingNuclei(), addOutgoingParticles(), eex_rest, on_shell, outgoingNuclei, outgoingParticles, and recoilFragments.
Referenced by G4InuclCollider::collide(), G4CascadeCheckBalance::collide(), G4CascadeDeexcitation::deExcite(), G4InuclCollider::deexcite(), G4IntraNucleiCascader::finalize(), and G4InuclCollider::rescatter().
void G4CollisionOutput::addOutgoingNuclei (const std::vector< G4InuclNuclei > & nuclea)
Definition at line 139 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 139 of file G4CollisionOutput.cc
References outgoingNuclei.
Referenced by add(), and G4CascadeCheckBalance::collide().
void G4CollisionOutput::addOutgoingNucleus (const G4InuclNuclei & nuclei) inline
Definition at line 85 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 85 of file G4CollisionOutput.hh
References outgoingNuclei.
Referenced by G4CascadeCoalescence::createNuclei(), and G4EquilibriumEvaporator::deExcite().
void G4CollisionOutput::addOutgoingParticle (const G4InuclElementaryParticle & particle) inline
Definition at line 79 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CollisionOutput.hh
References outgoingParticles.
Referenced by addOutgoingParticle(), addOutgoingParticles(), G4LightTargetCollider::collide(), G4IntraNucleiCascader::decayTrappedParticle(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), and G4IntraNucleiCascader::processTrappedParticle().
void G4CollisionOutput::addOutgoingParticle (const G4CascadParticle & cparticle)
Definition at line 145 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 145 of file G4CollisionOutput.cc
References addOutgoingParticle(), and G4CascadParticle::getParticle().
void G4CollisionOutput::addOutgoingParticles (const std::vector< G4InuclElementaryParticle > & particles)
Definition at line 134 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 134 of file G4CollisionOutput.cc
References outgoingParticles.
Referenced by add(), G4ElementaryParticleCollider::collide(), G4CascadeCheckBalance::collide(), G4BigBanger::deExcite(), G4CascadeDeexcitation::deExcite(), G4PreCompoundDeexcitation::deExcite(), G4IntraNucleiCascader::finishCascade(), and G4IntraNucleiCascader::setupCascade().
void G4CollisionOutput::addOutgoingParticles (const std::vector< G4CascadParticle > & cparticles)
Definition at line 149 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 149 of file G4CollisionOutput.cc
References addOutgoingParticle().
void G4CollisionOutput::addOutgoingParticles (const G4ReactionProductVector * rproducts)
Definition at line 156 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 156 of file G4CollisionOutput.cc
References G4cout, G4endl, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetParticleName(), GeV, mom, numberOfOutgoingNuclei(), numberOfOutgoingParticles(), outgoingNuclei, outgoingParticles, G4InuclParticle::PreCompound, G4InuclElementaryParticle::type(), and verboseLevel.
void G4CollisionOutput::addRecoilFragment (const G4Fragment * aFragment) inline
Definition at line 98 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 98 of file G4CollisionOutput.hh
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), and G4IntraNucleiCascader::finishCascade().
void G4CollisionOutput::addRecoilFragment (const G4Fragment & aFragment) inline
Definition at line 102 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 102 of file G4CollisionOutput.hh
References recoilFragments.
void G4CollisionOutput::boostToLabFrame (const G4LorentzConvertor & convertor)
Definition at line 322 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 322 of file G4CollisionOutput.cc
References G4cout, G4endl, GeV, ipart, outgoingNuclei, outgoingParticles, recoilFragments, and verboseLevel.
Referenced by G4InuclCollider::collide(), and G4EquilibriumEvaporator::deExcite().
G4LorentzVector G4CollisionOutput::boostToLabFrame (G4LorentzVector mom, const G4LorentzConvertor & convertor) const
Definition at line 350 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 350 of file G4CollisionOutput.cc
References G4LorentzConvertor::backToTheLab(), mom, G4LorentzConvertor::reflectionNeeded(), G4LorentzConvertor::rotate(), CLHEP::HepLorentzVector::setZ(), and CLHEP::HepLorentzVector::z().
const std::vector<G4InuclNuclei>& G4CollisionOutput::getOutgoingNuclei () const inline
Definition at line 136 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 136 of file G4CollisionOutput.hh
References outgoingNuclei.
Referenced by G4Analyser::analyse(), G4InuclEvaporation::BreakItUp(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::copyOutputToReactionProducts(), G4EquilibriumEvaporator::deExcite(), G4InuclCollider::photonuclearOkay(), and G4IntraNucleiCascader::releaseSecondary().
std::vector<G4InuclNuclei>& G4CollisionOutput::getOutgoingNuclei () inline
Definition at line 140 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 140 of file G4CollisionOutput.hh
References outgoingNuclei.
const std::vector<G4InuclElementaryParticle>& G4CollisionOutput::getOutgoingParticles () const inline
Definition at line 126 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CollisionOutput.hh
References outgoingParticles.
Referenced by G4Analyser::analyse(), G4InuclEvaporation::BreakItUp(), G4CascadeCheckBalance::collide(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::copyOutputToReactionProducts(), G4CascadeInterface::coulombBarrierViolation(), G4CascadeDeexcitation::deExcite(), G4EquilibriumEvaporator::deExcite(), G4CascadeCoalescence::FindClusters(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4NucleiModel::generateParticleFate(), G4IntraNucleiCascader::releaseSecondary(), G4CascadeInterface::retryInelasticNucleus(), and G4CascadeInterface::retryInelasticProton().
std::vector<G4InuclElementaryParticle>& G4CollisionOutput::getOutgoingParticles () inline
Definition at line 130 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 130 of file G4CollisionOutput.hh
References outgoingParticles.
const G4Fragment & G4CollisionOutput::getRecoilFragment (G4int index = 0) const
Definition at line 115 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 115 of file G4CollisionOutput.cc
References emptyFragment, numberOfFragments(), and recoilFragments.
Referenced by G4InuclCollider::collide(), G4NonEquilibriumEvaporator::deExcite(), G4CascadeDeexcitation::deExcite(), G4EquilibriumEvaporator::deExcite(), and G4InuclCollider::rescatter().
const std::vector<G4Fragment>& G4CollisionOutput::getRecoilFragments () const inline
Definition at line 146 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 146 of file G4CollisionOutput.hh
References recoilFragments.
std::vector<G4Fragment>& G4CollisionOutput::getRecoilFragments () inline
Definition at line 150 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 150 of file G4CollisionOutput.hh
References recoilFragments.
double G4CollisionOutput::getRemainingExitationEnergy () const inline
Definition at line 172 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 172 of file G4CollisionOutput.hh
References eex_rest.
G4int G4CollisionOutput::getTotalBaryonNumber () const
Definition at line 271 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 271 of file G4CollisionOutput.cc
References G4InuclParticleNames::baryon(), G4cout, G4endl, numberOfFragments(), numberOfOutgoingNuclei(), numberOfOutgoingParticles(), outgoingNuclei, outgoingParticles, recoilFragments, and verboseLevel.
Referenced by G4CascadeCheckBalance::collide().
G4int G4CollisionOutput::getTotalCharge () const
Definition at line 251 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 251 of file G4CollisionOutput.cc
References charge, G4cout, G4endl, numberOfFragments(), numberOfOutgoingNuclei(), numberOfOutgoingParticles(), outgoingNuclei, outgoingParticles, recoilFragments, and verboseLevel.
Referenced by G4CascadeCheckBalance::collide().
G4LorentzVector G4CollisionOutput::getTotalOutputMomentum () const
Definition at line 232 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 232 of file G4CollisionOutput.cc
References G4cout, G4endl, GeV, numberOfFragments(), numberOfOutgoingNuclei(), numberOfOutgoingParticles(), outgoingNuclei, outgoingParticles, recoilFragments, and verboseLevel.
Referenced by G4CascadeCheckBalance::collide(), and setOnShell().
G4int G4CollisionOutput::getTotalStrangeness () const
Definition at line 290 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 290 of file G4CollisionOutput.cc
References G4cout, G4endl, numberOfOutgoingParticles(), outgoingParticles, and verboseLevel.
Referenced by G4CascadeCheckBalance::collide().
G4int G4CollisionOutput::numberOfFragments () const inline
Definition at line 142 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 142 of file G4CollisionOutput.hh
References recoilFragments.
Referenced by G4EquilibriumEvaporator::deExcite(), getRecoilFragment(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), printCollisionOutput(), removeRecoilFragment(), setOnShell(), and setRemainingExitationEnergy().
G4int G4CollisionOutput::numberOfOutgoingNuclei () const inline
Definition at line 134 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 134 of file G4CollisionOutput.hh
References outgoingNuclei.
Referenced by addOutgoingParticles(), G4IntraNucleiCascader::copySecondaries(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), G4InuclCollider::photonuclearOkay(), printCollisionOutput(), G4IntraNucleiCascader::releaseSecondary(), removeOutgoingNucleus(), G4CascadeInterface::retryInelasticNucleus(), setOnShell(), and setRemainingExitationEnergy().
G4int G4CollisionOutput::numberOfOutgoingParticles () const inline
Definition at line 124 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 124 of file G4CollisionOutput.hh
References outgoingParticles.
Referenced by addOutgoingParticles(), G4CascadeCheckBalance::collide(), G4IntraNucleiCascader::copySecondaries(), G4NonEquilibriumEvaporator::deExcite(), G4IntraNucleiCascader::finishCascade(), G4NucleiModel::generateParticleFate(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), getTotalStrangeness(), printCollisionOutput(), G4IntraNucleiCascader::releaseSecondary(), removeOutgoingParticle(), G4CascadeInterface::retryInelasticNucleus(), and setOnShell().
G4CollisionOutput & G4CollisionOutput::operator= (const G4CollisionOutput & right)
Definition at line 91 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 91 of file G4CollisionOutput.cc
References eex_rest, on_shell, outgoingNuclei, outgoingParticles, recoilFragments, and verboseLevel.
void G4CollisionOutput::printCollisionOutput (std::ostream & os = G4cout) const
Definition at line 304 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 304 of file G4CollisionOutput.cc
References G4endl, numberOfFragments(), numberOfOutgoingNuclei(), numberOfOutgoingParticles(), outgoingNuclei, outgoingParticles, and recoilFragments.
Referenced by G4CascadeInterface::ApplyYourself(), G4EvaporationInuclCollider::deExcite(), G4CascadeDeexcitation::deExcite(), G4CascadeCoalescence::FindClusters(), G4IntraNucleiCascader::finishCascade(), G4NucleiModel::generateParticleFate(), G4CascadeInterface::Propagate(), setOnShell(), G4CascadeInterface::throwNonConservationFailure(), and G4CascadeColliderBase::validateOutput().
void G4CollisionOutput::removeOutgoingNucleus (G4int index)
Definition at line 202 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 202 of file G4CollisionOutput.cc
References numberOfOutgoingNuclei(), and outgoingNuclei.
Referenced by removeOutgoingNucleus().
void G4CollisionOutput::removeOutgoingNucleus (const G4InuclNuclei & nuclei)
Definition at line 215 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 215 of file G4CollisionOutput.cc
References G4InuclParticleNames::nuclei, outgoingNuclei, and pos().
void G4CollisionOutput::removeOutgoingNucleus (const G4InuclNuclei * nuclei) inline
Definition at line 116 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 116 of file G4CollisionOutput.hh
References removeOutgoingNucleus().
void G4CollisionOutput::removeOutgoingParticle (G4int index)
Definition at line 197 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 197 of file G4CollisionOutput.cc
References numberOfOutgoingParticles(), and outgoingParticles.
Referenced by G4CascadeCoalescence::removeNucleons(), and removeOutgoingParticle().
void G4CollisionOutput::removeOutgoingParticle (const G4InuclElementaryParticle & particle)
Definition at line 209 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 209 of file G4CollisionOutput.cc
References outgoingParticles, particle, and pos().
void G4CollisionOutput::removeOutgoingParticle (const G4InuclElementaryParticle * particle) inline
Definition at line 110 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 110 of file G4CollisionOutput.hh
References removeOutgoingParticle().
void G4CollisionOutput::removeRecoilFragment (G4int index = -1)
Definition at line 223 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 223 of file G4CollisionOutput.cc
References numberOfFragments(), and recoilFragments.
Referenced by G4InuclCollider::collide(), and G4InuclCollider::rescatter().
void G4CollisionOutput::reset ()
Definition at line 104 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 104 of file G4CollisionOutput.cc
References eex_rest, on_shell, outgoingNuclei, outgoingParticles, and recoilFragments.
Referenced by G4CascadeInterface::ApplyYourself(), G4LightTargetCollider::collide(), G4InuclCollider::collide(), G4CascadeCheckBalance::collide(), G4CascadeDeexcitation::deExcite(), G4EquilibriumEvaporator::deExcite(), G4InuclCollider::deexcite(), G4NucleiModel::generateParticleFate(), G4IntraNucleiCascader::newCascade(), G4CascadeInterface::Propagate(), G4InuclCollider::rescatter(), and trivialise().
void G4CollisionOutput::rotateEvent (const G4LorentzRotation & rotate)
Definition at line 361 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 361 of file G4CollisionOutput.cc
References G4cout, G4endl, ipart, mom, outgoingNuclei, outgoingParticles, recoilFragments, and verboseLevel.
std::pair< std::pair< G4int, G4int >, G4int > G4CollisionOutput::selectPairToTune (G4double de) const private
Definition at line 630 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 630 of file G4CollisionOutput.cc
References G4cout, G4endl, outgoingParticles, verboseLevel, CLHEP::HepLorentzVector::X, and CLHEP::HepLorentzVector::Z.
Referenced by setOnShell().
void G4CollisionOutput::setOnShell (G4InuclParticle * bullet, G4InuclParticle * target)
Definition at line 406 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 406 of file G4CollisionOutput.cc
References CLHEP::HepLorentzVector::e(), eex_rest, G4Electron::Electron(), source.hepunit::electron_mass_c2, G4cout, G4endl, G4InuclParticle::getMomentum(), getTotalOutputMomentum(), GeV, in, CLHEP::HepLorentzVector::m(), mom_non_cons, npart, numberOfFragments(), numberOfOutgoingNuclei(), numberOfOutgoingParticles(), on_shell, outgoingNuclei, outgoingParticles, printCollisionOutput(), recoilFragments, CLHEP::HepLorentzVector::rho(), selectPairToTune(), setRemainingExitationEnergy(), CLHEP::HepLorentzVector::setVectM(), tuneSelectedPair(), CLHEP::HepLorentzVector::vect(), verboseLevel, CLHEP::HepLorentzVector::X, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by G4InuclCollider::collide(), and G4IntraNucleiCascader::finishCascade().
void G4CollisionOutput::setRemainingExitationEnergy ()
Definition at line 619 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 619 of file G4CollisionOutput.cc
References eex_rest, GeV, numberOfFragments(), numberOfOutgoingNuclei(), outgoingNuclei, and recoilFragments.
Referenced by setOnShell().
void G4CollisionOutput::setVerboseLevel (G4int verbose) inline
Definition at line 71 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 71 of file G4CollisionOutput.hh
References verboseLevel.
Referenced by G4PreCompoundDeexcitation::deExcite(), G4IntraNucleiCascader::finishCascade(), G4LightTargetCollider::setVerboseLevel(), G4InuclCollider::setVerboseLevel(), and G4CascadeInterface::SetVerboseLevel().
void G4CollisionOutput::trivialise (G4InuclParticle * bullet, G4InuclParticle * target)
Definition at line 381 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 381 of file G4CollisionOutput.cc
References G4cout, G4endl, outgoingNuclei, outgoingParticles, particle, reset(), and verboseLevel.
Referenced by G4LightTargetCollider::collide(), G4InuclCollider::collide(), and G4IntraNucleiCascader::finalize().
G4bool G4CollisionOutput::tuneSelectedPair (G4LorentzVector & mom1, G4LorentzVector & mom2, G4int mom_index) const private
Definition at line 687 of file G4CollisionOutput.cc.
View newest version in sPHENIX GitHub at line 687 of file G4CollisionOutput.cc
References CLHEP::HepLorentzVector::e(), G4cout, G4endl, mom_non_cons, Q, Acts::IntegrationTest::R, verboseLevel, x, x1, and x2.
Referenced by setOnShell().
Member Data Documentation
G4double G4CollisionOutput::eex_rest private
Definition at line 187 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 187 of file G4CollisionOutput.hh
Referenced by add(), getRemainingExitationEnergy(), operator=(), reset(), setOnShell(), and setRemainingExitationEnergy().
const G4Fragment G4CollisionOutput::emptyFragment static private
Definition at line 181 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 181 of file G4CollisionOutput.hh
Referenced by getRecoilFragment().
G4LorentzVector G4CollisionOutput::mom_non_cons private
Definition at line 188 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 188 of file G4CollisionOutput.hh
Referenced by setOnShell(), and tuneSelectedPair().
G4bool G4CollisionOutput::on_shell private
Definition at line 189 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 189 of file G4CollisionOutput.hh
Referenced by add(), operator=(), reset(), and setOnShell().
std::vector<G4InuclNuclei> G4CollisionOutput::outgoingNuclei private
Definition at line 179 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 179 of file G4CollisionOutput.hh
Referenced by add(), addOutgoingNuclei(), addOutgoingNucleus(), addOutgoingParticles(), boostToLabFrame(), getOutgoingNuclei(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), numberOfOutgoingNuclei(), operator=(), printCollisionOutput(), removeOutgoingNucleus(), reset(), rotateEvent(), setOnShell(), setRemainingExitationEnergy(), and trivialise().
std::vector<G4InuclElementaryParticle> G4CollisionOutput::outgoingParticles private
Definition at line 178 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 178 of file G4CollisionOutput.hh
Referenced by add(), addOutgoingParticle(), addOutgoingParticles(), boostToLabFrame(), getOutgoingParticles(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), getTotalStrangeness(), numberOfOutgoingParticles(), operator=(), printCollisionOutput(), removeOutgoingParticle(), reset(), rotateEvent(), selectPairToTune(), setOnShell(), and trivialise().
std::vector<G4Fragment> G4CollisionOutput::recoilFragments private
Definition at line 180 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 180 of file G4CollisionOutput.hh
Referenced by add(), addRecoilFragment(), boostToLabFrame(), getRecoilFragment(), getRecoilFragments(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), numberOfFragments(), operator=(), printCollisionOutput(), removeRecoilFragment(), reset(), rotateEvent(), setOnShell(), and setRemainingExitationEnergy().
G4int G4CollisionOutput::verboseLevel private
Definition at line 173 of file G4CollisionOutput.hh.
View newest version in sPHENIX GitHub at line 173 of file G4CollisionOutput.hh
Referenced by addOutgoingParticles(), boostToLabFrame(), G4CollisionOutput(), getTotalBaryonNumber(), getTotalCharge(), getTotalOutputMomentum(), getTotalStrangeness(), operator=(), rotateEvent(), selectPairToTune(), setOnShell(), setVerboseLevel(), trivialise(), and tuneSelectedPair().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CollisionOutput.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CollisionOutput.cc