ECCE @ EIC Software: G4MesonAbsorption Class Reference
G4MesonAbsorption Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4MesonAbsorption.hh>
Public Member Functions
G4MesonAbsorption ()
virtual ~G4MesonAbsorption ()
virtual const std::vector
< G4CollisionInitialState * > & GetCollisions (G4KineticTrack *aProjectile, std::vector< G4KineticTrack * > &someCandidates, G4double aCurrentTime)
virtual G4KineticTrackVector * GetFinalState (G4KineticTrack *aProjectile, std::vector< G4KineticTrack * > &theTargets)
G4CollisionInitialState * GetCollision (G4KineticTrack *projectile, std::vector< G4KineticTrack * > targets)
Public Member Functions inherited from G4BCAction
G4BCAction ()
virtual ~G4BCAction ()
Private Member Functions
G4MesonAbsorption (const G4MesonAbsorption &)
G4MesonAbsorption & operator= (const G4MesonAbsorption &)
G4double GetTimeToAbsorption (const G4KineticTrack &trk1, const G4KineticTrack &trk2)
void FindAndFillCluster (G4KineticTrackVector &result, G4KineticTrack *aProjectile, std::vector< G4KineticTrack * > &someCandidates)
G4double AbsorptionCrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2)
Private Attributes
std::vector
< G4CollisionInitialState * > theCollisions
Detailed Description
Definition at line 34 of file G4MesonAbsorption.hh.
View newest version in sPHENIX GitHub at line 34 of file G4MesonAbsorption.hh
Constructor & Destructor Documentation
G4MesonAbsorption::G4MesonAbsorption () inline
Definition at line 37 of file G4MesonAbsorption.hh.
View newest version in sPHENIX GitHub at line 37 of file G4MesonAbsorption.hh
virtual G4MesonAbsorption::~G4MesonAbsorption () inline virtual
Definition at line 38 of file G4MesonAbsorption.hh.
View newest version in sPHENIX GitHub at line 38 of file G4MesonAbsorption.hh
G4MesonAbsorption::G4MesonAbsorption (const G4MesonAbsorption &) private
Member Function Documentation
G4double G4MesonAbsorption::AbsorptionCrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) private
Definition at line 306 of file G4MesonAbsorption.cc.
View newest version in sPHENIX GitHub at line 306 of file G4MesonAbsorption.cc
References G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), it, CLHEP::HepLorentzVector::mag(), MeV, millibarn, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), t, CLHEP::HepLorentzVector::t(), x1, x2, y1, and y2.
Referenced by GetTimeToAbsorption().
void G4MesonAbsorption::FindAndFillCluster (G4KineticTrackVector & result, G4KineticTrack * aProjectile, std::vector< G4KineticTrack * > & someCandidates) private
Definition at line 74 of file G4MesonAbsorption.cc.
View newest version in sPHENIX GitHub at line 74 of file G4MesonAbsorption.cc
References DBL_MAX, G4lrint(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4KineticTrack::GetPosition(), and min.
Referenced by GetCollisions().
G4CollisionInitialState* G4MesonAbsorption::GetCollision (G4KineticTrack * projectile, std::vector< G4KineticTrack * > targets)
const std::vector< G4CollisionInitialState * > & G4MesonAbsorption::GetCollisions (G4KineticTrack * aProjectile, std::vector< G4KineticTrack * > & someCandidates, G4double aCurrentTime) virtual
Implements G4BCAction.
Definition at line 44 of file G4MesonAbsorption.cc.
View newest version in sPHENIX GitHub at line 44 of file G4MesonAbsorption.cc
References DBL_MAX, FindAndFillCluster(), GetTimeToAbsorption(), and theCollisions.
G4KineticTrackVector * G4MesonAbsorption::GetFinalState (G4KineticTrack * aProjectile, std::vector< G4KineticTrack * > & theTargets) virtual
Implements G4BCAction.
Definition at line 104 of file G4MesonAbsorption.cc.
View newest version in sPHENIX GitHub at line 104 of file G4MesonAbsorption.cc
References d1, d2, f1, f2, G4endl, G4lrint(), G4UniformRand, G4KineticTrack::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzRotation::inverse(), CLHEP::Hep3Vector::mag2(), G4Neutron::NeutronDefinition(), CLHEP::HepLorentzVector::phi(), phi, pi, G4Proton::ProtonDefinition(), CLHEP::HepLorentzVector::rotateY(), CLHEP::HepLorentzVector::rotateZ(), sqr(), CLHEP::HepLorentzVector::t(), and CLHEP::HepLorentzVector::theta().
G4double G4MesonAbsorption::GetTimeToAbsorption (const G4KineticTrack & trk1, const G4KineticTrack & trk2) private
Definition at line 238 of file G4MesonAbsorption.cc.
View newest version in sPHENIX GitHub at line 238 of file G4MesonAbsorption.cc
References kdfinder::abs(), AbsorptionCrossSection(), source.hepunit::c_light, DBL_MAX, CLHEP::HepLorentzVector::e(), eV, G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4KineticTrack::GetPosition(), G4KineticTrack::GetTrackingMomentum(), GeV, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), millibarn, mom, G4Neutron::Neutron(), pi, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), pos(), Acts::VectorHelpers::time(), and CLHEP::HepLorentzVector::vect().
Referenced by GetCollisions().
G4MesonAbsorption& G4MesonAbsorption::operator= (const G4MesonAbsorption &) private
Member Data Documentation
std::vector<G4CollisionInitialState *> G4MesonAbsorption::theCollisions private
Definition at line 65 of file G4MesonAbsorption.hh.
View newest version in sPHENIX GitHub at line 65 of file G4MesonAbsorption.hh
Referenced by GetCollisions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4MesonAbsorption.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4MesonAbsorption.cc