ECCE @ EIC Software: RE04ParallelWorldConstruction Class Reference
RE04ParallelWorldConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04ParallelWorldConstruction.hh>
Public Member Functions
RE04ParallelWorldConstruction (G4String &parallelWorldName)
virtual ~RE04ParallelWorldConstruction ()
virtual void Construct ()
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
virtual void ConstructSD ()
G4String GetName ()
Private Attributes
G4bool fConstructed
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
A parallel world construction class
void Construct() creates a parallel world in the mass world and parameterized volumes
Definition at line 45 of file RE04ParallelWorldConstruction.hh.
View newest version in sPHENIX GitHub at line 45 of file RE04ParallelWorldConstruction.hh
Constructor & Destructor Documentation
RE04ParallelWorldConstruction::RE04ParallelWorldConstruction (G4String & parallelWorldName)
Definition at line 42 of file RE04ParallelWorldConstruction.cc.
View newest version in sPHENIX GitHub at line 42 of file RE04ParallelWorldConstruction.cc
RE04ParallelWorldConstruction::~RE04ParallelWorldConstruction () virtual
Definition at line 47 of file RE04ParallelWorldConstruction.cc.
View newest version in sPHENIX GitHub at line 47 of file RE04ParallelWorldConstruction.cc
Member Function Documentation
void RE04ParallelWorldConstruction::Construct (void) virtual
Implements G4VUserParallelWorld.
Definition at line 51 of file RE04ParallelWorldConstruction.cc.
View newest version in sPHENIX GitHub at line 51 of file RE04ParallelWorldConstruction.cc
References cm, fConstructed, G4VPhysicalVolume::GetLogicalVolume(), G4Material::GetMaterial(), G4VUserParallelWorld::GetWorld(), and kXAxis.
Member Data Documentation
G4bool RE04ParallelWorldConstruction::fConstructed private
Definition at line 55 of file RE04ParallelWorldConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file RE04ParallelWorldConstruction.hh
Referenced by Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04ParallelWorldConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/src/RE04ParallelWorldConstruction.cc