ECCE @ EIC Software: G4IonFluctuations Class Reference
G4IonFluctuations Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4IonFluctuations.hh>
Public Member Functions
G4IonFluctuations (const G4String &nam="IonFluc")
virtual ~G4IonFluctuations ()
virtual G4double SampleFluctuations (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmax, G4double length, G4double meanLoss) override
virtual G4double Dispersion (const G4Material *, const G4DynamicParticle *, G4double tmax, G4double length) override
virtual void InitialiseMe (const G4ParticleDefinition *) override
virtual void SetParticleAndCharge (const G4ParticleDefinition *, G4double q2) override
Public Member Functions inherited from G4VEmFluctuationModel
G4VEmFluctuationModel (const G4String &nam)
virtual ~G4VEmFluctuationModel ()
const G4String & GetName () const
Private Member Functions
G4double Factor (const G4Material *, G4double Zeff)
G4double RelativisticFactor (const G4Material *, G4double Zeff)
G4IonFluctuations & operator= (const G4IonFluctuations &right)=delete
G4IonFluctuations (const G4IonFluctuations &)=delete
Private Attributes
G4UniversalFluctuation uniFluct
const G4ParticleDefinition * particle
G4Pow * g4calc
G4double particleMass
G4double charge
G4double chargeSquare
G4double effChargeSquare
G4double parameter
G4double theBohrBeta2
G4double minFraction
G4double xmin
G4double minLoss
G4double kineticEnergy
G4double beta2
Detailed Description
Definition at line 60 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 60 of file G4IonFluctuations.hh
Constructor & Destructor Documentation
G4IonFluctuations::G4IonFluctuations (const G4String & nam = "IonFluc") explicit
Definition at line 72 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 72 of file G4IonFluctuations.cc
References beta2, g4calc, G4Pow::GetInstance(), and kineticEnergy.
G4IonFluctuations::~G4IonFluctuations () virtual
Definition at line 92 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 92 of file G4IonFluctuations.cc
G4IonFluctuations::G4IonFluctuations (const G4IonFluctuations &) private delete
Member Function Documentation
G4double G4IonFluctuations::Dispersion (const G4Material * material, const G4DynamicParticle * dp, G4double tmax, G4double length) override virtual
Implements G4VEmFluctuationModel.
Definition at line 177 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 177 of file G4IonFluctuations.cc
References beta2, chargeSquare, source.hepunit::electron_mass_c2, fac, Factor(), G4Material::GetElectronDensity(), G4Material::GetIonisation(), G4DynamicParticle::GetKineticEnergy(), G4IonisParamMat::GetZeffective(), kineticEnergy, particleMass, source.hepunit::twopi_mc2_rcl2, and Z.
Referenced by SampleFluctuations().
G4double G4IonFluctuations::Factor (const G4Material * material, G4double Zeff) private
Definition at line 226 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 226 of file G4IonFluctuations.cc
References a, G4Pow::A13(), source.hepunit::amu_c2, b, beta2, charge, chargeSquare, effChargeSquare, energy, G4Pow::expA(), g4calc, G4lrint(), G4Material::GetNumberOfElements(), G4Material::GetState(), kineticEnergy, kStateGas, MeV, particleMass, G4Pow::powA(), RelativisticFactor(), s1, theBohrBeta2, x, and y.
Referenced by Dispersion().
void G4IonFluctuations::InitialiseMe (const G4ParticleDefinition * part) override virtual
Reimplemented from G4VEmFluctuationModel.
Definition at line 97 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 97 of file G4IonFluctuations.cc
References charge, chargeSquare, effChargeSquare, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4UniversalFluctuation::InitialiseMe(), part, particle, particleMass, and uniFluct.
G4IonFluctuations& G4IonFluctuations::operator= (const G4IonFluctuations & right) private delete
G4double G4IonFluctuations::RelativisticFactor (const G4Material * mat, G4double Zeff) private
Definition at line 421 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 421 of file G4IonFluctuations.cc
References beta2, source.hepunit::electron_mass_c2, f, G4Log(), G4IonisParamMat::GetFermiEnergy(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), I, and Z.
Referenced by Factor().
G4double G4IonFluctuations::SampleFluctuations (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmax, G4double length, G4double meanLoss) override virtual
Implements G4VEmFluctuationModel.
Definition at line 110 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 110 of file G4IonFluctuations.cc
References beta2, charge, Dispersion(), CLHEP::HepRandomEngine::flat(), G4InuclParticleNames::gam, G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), kineticEnergy, material(), minFraction, minLoss, parameter, particleMass, G4UniversalFluctuation::SampleFluctuations(), G4INCL::DeJongSpin::shoot(), sn, uniFluct, x, x3, and xmin.
void G4IonFluctuations::SetParticleAndCharge (const G4ParticleDefinition * part, G4double q2) override virtual
Reimplemented from G4VEmFluctuationModel.
Definition at line 441 of file G4IonFluctuations.cc.
View newest version in sPHENIX GitHub at line 441 of file G4IonFluctuations.cc
References charge, chargeSquare, effChargeSquare, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), part, particle, particleMass, G4UniversalFluctuation::SetParticleAndCharge(), and uniFluct.
Member Data Documentation
G4double G4IonFluctuations::beta2 private
Definition at line 116 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 116 of file G4IonFluctuations.hh
Referenced by Dispersion(), Factor(), G4IonFluctuations(), RelativisticFactor(), and SampleFluctuations().
G4double G4IonFluctuations::charge private
Definition at line 104 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 104 of file G4IonFluctuations.hh
Referenced by Factor(), InitialiseMe(), SampleFluctuations(), and SetParticleAndCharge().
G4double G4IonFluctuations::chargeSquare private
Definition at line 105 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 105 of file G4IonFluctuations.hh
Referenced by Dispersion(), Factor(), InitialiseMe(), and SetParticleAndCharge().
G4double G4IonFluctuations::effChargeSquare private
Definition at line 106 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 106 of file G4IonFluctuations.hh
Referenced by Factor(), InitialiseMe(), and SetParticleAndCharge().
G4Pow* G4IonFluctuations::g4calc private
Definition at line 101 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 101 of file G4IonFluctuations.hh
Referenced by Factor(), and G4IonFluctuations().
G4double G4IonFluctuations::kineticEnergy private
Definition at line 115 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 115 of file G4IonFluctuations.hh
Referenced by Dispersion(), Factor(), G4IonFluctuations(), and SampleFluctuations().
G4double G4IonFluctuations::minFraction private
Definition at line 111 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 111 of file G4IonFluctuations.hh
Referenced by SampleFluctuations().
G4double G4IonFluctuations::minLoss private
Definition at line 113 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 113 of file G4IonFluctuations.hh
Referenced by SampleFluctuations().
G4double G4IonFluctuations::parameter private
Definition at line 109 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 109 of file G4IonFluctuations.hh
Referenced by SampleFluctuations().
const G4ParticleDefinition* G4IonFluctuations::particle private
Definition at line 99 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 99 of file G4IonFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
G4double G4IonFluctuations::particleMass private
Definition at line 103 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 103 of file G4IonFluctuations.hh
Referenced by Dispersion(), Factor(), InitialiseMe(), SampleFluctuations(), and SetParticleAndCharge().
G4double G4IonFluctuations::theBohrBeta2 private
Definition at line 110 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 110 of file G4IonFluctuations.hh
Referenced by Factor().
G4UniversalFluctuation G4IonFluctuations::uniFluct private
Definition at line 98 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 98 of file G4IonFluctuations.hh
Referenced by InitialiseMe(), SampleFluctuations(), and SetParticleAndCharge().
G4double G4IonFluctuations::xmin private
Definition at line 112 of file G4IonFluctuations.hh.
View newest version in sPHENIX GitHub at line 112 of file G4IonFluctuations.hh
Referenced by SampleFluctuations().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4IonFluctuations.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4IonFluctuations.cc