ECCE @ EIC Software: G4EicDircStackingAction Class Reference
G4EicDircStackingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4EicDircStackingAction.h>
Public Member Functions
G4EicDircStackingAction (G4EicDircDetector *det)
~G4EicDircStackingAction () override
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack) override
stacking action. This gets called by the stacking action when a new track is generated
void PrepareNewEvent () override
Public Member Functions inherited from PHG4StackingAction
PHG4StackingAction (const std::string &name, const int i=0)
virtual ~PHG4StackingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual void SetInterfacePointers (PHCompositeNode *)
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
Private Attributes
gsl_rng * m_RandomGenerator = nullptr
G4EicDircDetector * m_Detector = nullptr
TGraph * fDetEff [2] = {nullptr}
int fCerenkovCounter = 0
int fScintillationCounter = 0
Detailed Description
Definition at line 14 of file G4EicDircStackingAction.h.
View newest version in sPHENIX GitHub at line 14 of file G4EicDircStackingAction.h
Constructor & Destructor Documentation
G4EicDircStackingAction::G4EicDircStackingAction (G4EicDircDetector * det)
Definition at line 21 of file G4EicDircStackingAction.cc.
View newest version in sPHENIX GitHub at line 21 of file G4EicDircStackingAction.cc
References fDetEff, G4InuclParticleNames::lambda, and m_RandomGenerator.
G4EicDircStackingAction::~G4EicDircStackingAction () override
Definition at line 58 of file G4EicDircStackingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file G4EicDircStackingAction.cc
References fDetEff, and m_RandomGenerator.
Member Function Documentation
G4ClassificationOfNewTrack G4EicDircStackingAction::ClassifyNewTrack (const G4Track *) override virtual
stacking action. This gets called by the stacking action when a new track is generated
Reimplemented from PHG4StackingAction.
Definition at line 65 of file G4EicDircStackingAction.cc.
View newest version in sPHENIX GitHub at line 65 of file G4EicDircStackingAction.cc
References fCerenkovCounter, fDetEff, fKill, fScintillationCounter, fUrgent, G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4Track::GetVolume(), G4EicDircDetector::IsInDetector(), G4InuclParticleNames::lambda, m_Detector, M_PI, m_RandomGenerator, CLHEP::Hep3Vector::mag(), G4OpticalPhoton::OpticalPhotonDefinition(), and Acts::Test::volume.
void G4EicDircStackingAction::PrepareNewEvent () override virtual
Reimplemented from PHG4StackingAction.
Definition at line 107 of file G4EicDircStackingAction.cc.
View newest version in sPHENIX GitHub at line 107 of file G4EicDircStackingAction.cc
References fCerenkovCounter, fScintillationCounter, G4cout, G4endl, and PHG4StackingAction::Verbosity().
Member Data Documentation
int G4EicDircStackingAction::fCerenkovCounter = 0 private
Definition at line 27 of file G4EicDircStackingAction.h.
View newest version in sPHENIX GitHub at line 27 of file G4EicDircStackingAction.h
Referenced by ClassifyNewTrack(), and PrepareNewEvent().
TGraph* G4EicDircStackingAction::fDetEff[2] = {nullptr} private
Definition at line 26 of file G4EicDircStackingAction.h.
View newest version in sPHENIX GitHub at line 26 of file G4EicDircStackingAction.h
Referenced by ClassifyNewTrack(), G4EicDircStackingAction(), and ~G4EicDircStackingAction().
int G4EicDircStackingAction::fScintillationCounter = 0 private
Definition at line 28 of file G4EicDircStackingAction.h.
View newest version in sPHENIX GitHub at line 28 of file G4EicDircStackingAction.h
Referenced by ClassifyNewTrack(), and PrepareNewEvent().
G4EicDircDetector* G4EicDircStackingAction::m_Detector = nullptr private
Definition at line 25 of file G4EicDircStackingAction.h.
View newest version in sPHENIX GitHub at line 25 of file G4EicDircStackingAction.h
Referenced by ClassifyNewTrack().
gsl_rng* G4EicDircStackingAction::m_RandomGenerator = nullptr private
Definition at line 24 of file G4EicDircStackingAction.h.
View newest version in sPHENIX GitHub at line 24 of file G4EicDircStackingAction.h
Referenced by ClassifyNewTrack(), G4EicDircStackingAction(), and ~G4EicDircStackingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4EicDircStackingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/G4EicDircStackingAction.cc