ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/event/pymodG4event.cc File Reference
pymodG4event.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4EventManager ()
void export_G4StackManager ()
void export_G4Event ()
void export_G4UserEventAction ()
void export_G4UserStackingAction ()
void export_G4ClassificationOfNewTrack ()
void export_G4ParticleGun ()
BOOST_PYTHON_MODULE (G4event)
Function Documentation
BOOST_PYTHON_MODULE (G4event)
Definition at line 46 of file pymodG4event.cc.
View newest version in sPHENIX GitHub at line 46 of file pymodG4event.cc
References export_G4ClassificationOfNewTrack(), export_G4Event(), export_G4EventManager(), export_G4ParticleGun(), export_G4StackManager(), export_G4UserEventAction(), and export_G4UserStackingAction().
void export_G4ClassificationOfNewTrack ()
Definition at line 39 of file pyG4ClassificationOfNewTrack.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4ClassificationOfNewTrack.cc
References fKill, fPostpone, fUrgent, fWaiting, fWaiting_1, fWaiting_10, fWaiting_2, fWaiting_3, fWaiting_4, fWaiting_5, fWaiting_6, fWaiting_7, fWaiting_8, and fWaiting_9.
Referenced by BOOST_PYTHON_MODULE().
void export_G4Event ()
Definition at line 50 of file pyG4Event.cc.
View newest version in sPHENIX GitHub at line 50 of file pyG4Event.cc
References G4Event::AddPrimaryVertex(), G4Event::Draw(), G4Event::GetEventID(), G4Event::GetNumberOfPrimaryVertex(), G4Event::GetPrimaryVertex(), G4Event::GetTrajectoryContainer(), G4Event::GetUserInformation(), G4Event::IsAborted(), G4Event::Print(), G4Event::SetEventAborted(), G4Event::SetEventID(), and G4Event::SetUserInformation().
Referenced by BOOST_PYTHON_MODULE().
void export_G4EventManager ()
Definition at line 40 of file pyG4EventManager.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4EventManager.cc
References G4EventManager::AbortCurrentEvent(), G4EventManager::GetConstCurrentEvent(), G4EventManager::GetEventManager(), G4EventManager::GetNonconstCurrentEvent(), G4EventManager::GetStackManager(), G4EventManager::GetTrackingManager(), G4EventManager::GetUserInformation(), G4EventManager::GetVerboseLevel(), G4EventManager::SetNumberOfAdditionalWaitingStacks(), G4EventManager::SetUserInformation(), and G4EventManager::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ParticleGun ()
Definition at line 126 of file pyG4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 126 of file pyG4ParticleGun.cc
References G4ParticleGun::GeneratePrimaryVertex(), G4ParticleGun::GetNumberOfParticles(), pyG4ParticleGun::GetParticleByName(), G4ParticleGun::GetParticleCharge(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleGun::GetParticlePolarization(), G4VPrimaryGenerator::GetParticlePosition(), G4VPrimaryGenerator::GetParticleTime(), G4ParticleGun::SetNumberOfParticles(), pyG4ParticleGun::SetParticleByName(), G4ParticleGun::SetParticleCharge(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentum(), G4ParticleGun::SetParticleMomentumDirection(), G4ParticleGun::SetParticlePolarization(), G4VPrimaryGenerator::SetParticlePosition(), and G4VPrimaryGenerator::SetParticleTime().
Referenced by BOOST_PYTHON_MODULE().
void export_G4StackManager ()
Definition at line 54 of file pyG4StackManager.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4StackManager.cc
References G4StackManager::clear(), G4StackManager::ClearPostponeStack(), G4StackManager::ClearUrgentStack(), G4StackManager::ClearWaitingStack(), G4StackManager::GetNTotalTrack(), G4StackManager::GetNUrgentTrack(), G4StackManager::GetNWaitingTrack(), G4StackManager::ReClassify(), and G4StackManager::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UserEventAction ()
Definition at line 64 of file pyG4UserEventAction.cc.
View newest version in sPHENIX GitHub at line 64 of file pyG4UserEventAction.cc
References CB_G4UserEventAction::BeginOfEventAction(), G4UserEventAction::BeginOfEventAction(), CB_G4UserEventAction::EndOfEventAction(), and G4UserEventAction::EndOfEventAction().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UserStackingAction ()
Definition at line 78 of file pyG4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 78 of file pyG4UserStackingAction.cc
References G4UserStackingAction::ClassifyNewTrack(), G4UserStackingAction::NewStage(), and G4UserStackingAction::PrepareNewEvent().
Referenced by BOOST_PYTHON_MODULE().