ECCE @ EIC Software: HEPREP::HepRepWriter Class Reference
HEPREP::HepRepWriter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepWriter.h>
Public Member Functions
virtual ~HepRepWriter ()
Destructor.
virtual bool addProperty (std::string key, std::string value)=0
virtual bool close ()=0
virtual bool write (HepRep *heprep, std::string name)=0
virtual bool write (std::vector< std::string > layerOrder)=0
virtual bool write (HepRepTypeTree *typeTree)=0
virtual bool write (HepRepType *type)=0
virtual bool write (HepRepTreeID *treeID)=0
virtual bool write (HepRepAction *action)=0
virtual bool write (HepRepInstanceTree *instanceTree)=0
virtual bool write (HepRepInstance *instance)=0
virtual bool write (HepRepPoint *point)=0
virtual bool write (HepRepAttribute *attribute)=0
virtual bool write (HepRepDefinition *definition)=0
virtual bool write (HepRepAttValue *attValue)=0
virtual bool write (HepRepAttDef *attDef)=0
Detailed Description
HepRepWriter interface.
Author
Mark Donszelmann
Definition at line 35 of file HepRepWriter.h.
View newest version in sPHENIX GitHub at line 35 of file HepRepWriter.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepWriter::~HepRepWriter () inline virtual
Destructor.
Definition at line 39 of file HepRepWriter.h.
View newest version in sPHENIX GitHub at line 39 of file HepRepWriter.h
Member Function Documentation
virtual bool HEPREP::HepRepWriter::addProperty (std::string key, std::string value) pure virtual
Adds a property, to be written to the HepRep file when closed.
Parameters
key
value
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
Referenced by G4HepRepSceneHandler::closeHepRep().
virtual bool HEPREP::HepRepWriter::close () pure virtual
Closes the writer and its underlying stream.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
Referenced by G4HepRepSceneHandler::closeFile().
virtual bool HEPREP::HepRepWriter::write (HepRep * heprep, std::string name) pure virtual
Writes a HepRep.
Parameters
heprep to be written.
name for the heprep to be written (for tagged access), may be ommited.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
Referenced by G4HepRepSceneHandler::closeHepRep().
virtual bool HEPREP::HepRepWriter::write (std::vector< std::string > layerOrder) pure virtual
Writes the layerOrder.
Parameters
layerOrder to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepTypeTree * typeTree) pure virtual
Writes a HepRepTypeTree.
Parameters
typeTree to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepType * type) pure virtual
Writes a HepRepType.
Parameters
type to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepTreeID * treeID) pure virtual
Writes a HepRepTreeID.
Parameters
treeID to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepAction * action) pure virtual
Writes a HepRepAction.
Parameters
action to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepInstanceTree * instanceTree) pure virtual
Writes a HepRepInstanceTree.
Parameters
instanceTree to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepInstance * instance) pure virtual
Writes a HepRepInstance.
Parameters
instance to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepPoint * point) pure virtual
Writes a HepRepPoint.
Parameters
point to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepAttribute * attribute) pure virtual
Writes a HepRepAttribute.
Parameters
attribute to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepDefinition * definition) pure virtual
Writes a HepRepDefinition.
Parameters
definition to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepAttValue * attValue) pure virtual
Writes a HepRepAttValue.
Parameters
attValue to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
virtual bool HEPREP::HepRepWriter::write (HepRepAttDef * attDef) pure virtual
Writes a HepRepAttDef.
Parameters
attDef to be written.
Returns
false in case of a stream problem.
Implemented in cheprep::XMLHepRepWriter.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepWriter.h