ECCE @ EIC Software: G4AnalysisMessengerHelper Class Reference
G4AnalysisMessengerHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4AnalysisMessengerHelper.hh>
Classes
struct BinData
struct ValueData
Public Member Functions
G4AnalysisMessengerHelper (const G4String &hnType)
~G4AnalysisMessengerHelper ()
std::unique_ptr< G4UIdirectory > CreateHnDirectory () const
std::unique_ptr< G4UIcommand > CreateSetTitleCommand (G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetBinsCommand (const G4String &axis, G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetValuesCommand (const G4String &axis, G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetAxisCommand (const G4String &axis, G4UImessenger *messenger) const
std::unique_ptr< G4UIcommand > CreateSetAxisLogCommand (const G4String &axis, G4UImessenger *messenger) const
void GetBinData (BinData &data, std::vector< G4String > &parameters, G4int &counter) const
void GetValueData (ValueData &data, std::vector< G4String > &parameters, G4int &counter) const
void WarnAboutParameters (G4UIcommand *command, G4int nofParameters) const
void WarnAboutSetCommands () const
Private Member Functions
G4String Update (const G4String &str, const G4String &axis="") const
Private Attributes
G4String fHnType
Friends
class G4HnMessenger
Detailed Description
Definition at line 44 of file G4AnalysisMessengerHelper.hh.
View newest version in sPHENIX GitHub at line 44 of file G4AnalysisMessengerHelper.hh
Constructor & Destructor Documentation
G4AnalysisMessengerHelper::G4AnalysisMessengerHelper (const G4String & hnType) explicit
Definition at line 78 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 78 of file G4AnalysisMessengerHelper.cc
G4AnalysisMessengerHelper::~G4AnalysisMessengerHelper ()
Definition at line 83 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 83 of file G4AnalysisMessengerHelper.cc
Member Function Documentation
std::unique_ptr< G4UIdirectory > G4AnalysisMessengerHelper::CreateHnDirectory () const
Definition at line 133 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 133 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::SetGuidance(), and Update().
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetAxisCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 264 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 264 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), and Update().
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetAxisLogCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 286 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 286 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), and Update().
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetBinsCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 165 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 165 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), and Update().
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetTitleCommand (G4UImessenger * messenger) const
Definition at line 142 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 142 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), and Update().
std::unique_ptr< G4UIcommand > G4AnalysisMessengerHelper::CreateSetValuesCommand (const G4String & axis, G4UImessenger * messenger) const
Definition at line 222 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 222 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), and Update().
void G4AnalysisMessengerHelper::GetBinData (BinData & data, std::vector< G4String > & parameters, G4int & counter) const
Definition at line 308 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 308 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToInt(), G4AnalysisMessengerHelper::BinData::fNbins, G4AnalysisMessengerHelper::BinData::fSbinScheme, G4AnalysisMessengerHelper::BinData::fSfcn, G4AnalysisMessengerHelper::BinData::fSunit, G4AnalysisMessengerHelper::BinData::fVmax, and G4AnalysisMessengerHelper::BinData::fVmin.
void G4AnalysisMessengerHelper::GetValueData (ValueData & data, std::vector< G4String > & parameters, G4int & counter) const
Definition at line 321 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 321 of file G4AnalysisMessengerHelper.cc
References G4UIcommand::ConvertToDouble(), G4AnalysisMessengerHelper::ValueData::fSfcn, G4AnalysisMessengerHelper::ValueData::fSunit, G4AnalysisMessengerHelper::ValueData::fVmax, and G4AnalysisMessengerHelper::ValueData::fVmin.
G4String G4AnalysisMessengerHelper::Update (const G4String & str, const G4String & axis = "") const private
Definition at line 91 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 91 of file G4AnalysisMessengerHelper.cc
References fHnType, second, G4String::toLower(), and G4String::toUpper().
Referenced by CreateHnDirectory(), CreateSetAxisCommand(), CreateSetAxisLogCommand(), CreateSetBinsCommand(), CreateSetTitleCommand(), CreateSetValuesCommand(), WarnAboutParameters(), and WarnAboutSetCommands().
void G4AnalysisMessengerHelper::WarnAboutParameters (G4UIcommand * command, G4int nofParameters) const
Definition at line 332 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 332 of file G4AnalysisMessengerHelper.cc
References G4endl, G4Exception(), G4UIcommand::GetCommandName(), G4UIcommand::GetParameterEntries(), JustWarning, and Update().
void G4AnalysisMessengerHelper::WarnAboutSetCommands () const
Definition at line 347 of file G4AnalysisMessengerHelper.cc.
View newest version in sPHENIX GitHub at line 347 of file G4AnalysisMessengerHelper.cc
References G4endl, G4Exception(), JustWarning, and Update().
Friends And Related Function Documentation
friend class G4HnMessenger friend
Definition at line 78 of file G4AnalysisMessengerHelper.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AnalysisMessengerHelper.hh
Member Data Documentation
G4String G4AnalysisMessengerHelper::fHnType private
Definition at line 113 of file G4AnalysisMessengerHelper.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AnalysisMessengerHelper.hh
Referenced by Update().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4AnalysisMessengerHelper.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4AnalysisMessengerHelper.cc