ECCE @ EIC Software: G4AdjointPosOnPhysVolGenerator Class Reference
G4AdjointPosOnPhysVolGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4AdjointPosOnPhysVolGenerator.hh>
Public Member Functions
G4VPhysicalVolume * DefinePhysicalVolume (const G4String &aName)
void DefinePhysicalVolume1 (const G4String &aName)
G4double ComputeAreaOfExtSurface ()
G4double ComputeAreaOfExtSurface (G4int NStat)
G4double ComputeAreaOfExtSurface (G4double epsilon)
G4double ComputeAreaOfExtSurface (G4VSolid *aSolid)
G4double ComputeAreaOfExtSurface (G4VSolid *aSolid, G4int NStat)
G4double ComputeAreaOfExtSurface (G4VSolid *aSolid, G4double epsilon)
void GenerateAPositionOnTheExtSurfaceOfASolid (G4VSolid *aSolid, G4ThreeVector &p, G4ThreeVector &direction)
void GenerateAPositionOnTheExtSurfaceOfTheSolid (G4ThreeVector &p, G4ThreeVector &direction)
void GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume (G4ThreeVector &p, G4ThreeVector &direction)
void GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume (G4ThreeVector &p, G4ThreeVector &direction, G4double &costh_to_normal)
void SetSolid (G4VSolid *aSolid)
G4double GetAreaOfExtSurfaceOfThePhysicalVolume ()
G4double GetCosThDirComparedToNormal ()
Static Public Member Functions
static
G4AdjointPosOnPhysVolGenerator * GetInstance ()
Private Member Functions
G4AdjointPosOnPhysVolGenerator ()
~G4AdjointPosOnPhysVolGenerator ()
G4double ComputeAreaOfExtSurfaceStartingFromSphere (G4VSolid *aSolid, G4int NStat)
G4double ComputeAreaOfExtSurfaceStartingFromBox (G4VSolid *aSolid, G4int NStat)
void GenerateAPositionOnASolidBoundary (G4VSolid *aSolid, G4ThreeVector &p, G4ThreeVector &direction)
G4double GenerateAPositionOnASphereBoundary (G4VSolid *aSolid, G4ThreeVector &p, G4ThreeVector &direction)
G4double GenerateAPositionOnABoxBoundary (G4VSolid *aSolid, G4ThreeVector &p, G4ThreeVector &direction)
void ComputeTransformationFromPhysVolToWorld ()
Private Attributes
G4VSolid * theSolid
G4VPhysicalVolume * thePhysicalVolume
G4bool UseSphere
G4String ModelOfSurfaceSource
G4AffineTransform theTransformationFromPhysVolToWorld
G4double AreaOfExtSurfaceOfThePhysicalVolume
G4double CosThDirComparedToNormal
Static Private Attributes
static G4ThreadLocal
G4AdjointPosOnPhysVolGenerator * theInstance = 0
Detailed Description
Definition at line 61 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AdjointPosOnPhysVolGenerator.hh
Constructor & Destructor Documentation
G4AdjointPosOnPhysVolGenerator::G4AdjointPosOnPhysVolGenerator () private
Definition at line 65 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 65 of file G4AdjointPosOnPhysVolGenerator.cc
Referenced by GetInstance().
G4AdjointPosOnPhysVolGenerator::~G4AdjointPosOnPhysVolGenerator () private
Definition at line 59 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 59 of file G4AdjointPosOnPhysVolGenerator.cc
Member Function Documentation
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface ()
Definition at line 108 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointPosOnPhysVolGenerator.cc
References theSolid.
Referenced by ComputeAreaOfExtSurface().
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface (G4int NStat)
Definition at line 114 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 114 of file G4AdjointPosOnPhysVolGenerator.cc
References ComputeAreaOfExtSurface(), and theSolid.
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface (G4double epsilon)
Definition at line 120 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 120 of file G4AdjointPosOnPhysVolGenerator.cc
References ComputeAreaOfExtSurface(), and theSolid.
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface (G4VSolid * aSolid)
Definition at line 126 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 126 of file G4AdjointPosOnPhysVolGenerator.cc
References ComputeAreaOfExtSurface(), and e.
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface (G4VSolid * aSolid, G4int NStat)
Definition at line 132 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 132 of file G4AdjointPosOnPhysVolGenerator.cc
References ComputeAreaOfExtSurfaceStartingFromBox(), ComputeAreaOfExtSurfaceStartingFromSphere(), dir, GenerateAPositionOnABoxBoundary(), GenerateAPositionOnASphereBoundary(), ModelOfSurfaceSource, and UseSphere.
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface (G4VSolid * aSolid, G4double epsilon)
Definition at line 150 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 150 of file G4AdjointPosOnPhysVolGenerator.cc
References ComputeAreaOfExtSurface().
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurfaceStartingFromBox (G4VSolid * aSolid, G4int NStat) private
Definition at line 176 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 176 of file G4AdjointPosOnPhysVolGenerator.cc
References G4VSolid::DistanceToIn(), GenerateAPositionOnABoxBoundary(), and kInfinity.
Referenced by ComputeAreaOfExtSurface().
G4double G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurfaceStartingFromSphere (G4VSolid * aSolid, G4int NStat) private
Definition at line 194 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 194 of file G4AdjointPosOnPhysVolGenerator.cc
References G4VSolid::DistanceToIn(), GenerateAPositionOnASphereBoundary(), and kInfinity.
Referenced by ComputeAreaOfExtSurface().
void G4AdjointPosOnPhysVolGenerator::ComputeTransformationFromPhysVolToWorld () private
Definition at line 389 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 389 of file G4AdjointPosOnPhysVolGenerator.cc
References G4VPhysicalVolume::GetFrameRotation(), G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetObjectTranslation(), thePhysicalVolume, and theTransformationFromPhysVolToWorld.
Referenced by DefinePhysicalVolume().
G4VPhysicalVolume * G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume (const G4String & aName)
Definition at line 74 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 74 of file G4AdjointPosOnPhysVolGenerator.cc
References ComputeTransformationFromPhysVolToWorld(), G4cout, G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetSolid(), thePhysicalVolume, and theSolid.
Referenced by DefinePhysicalVolume1().
void G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume1 (const G4String & aName)
Definition at line 102 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 102 of file G4AdjointPosOnPhysVolGenerator.cc
References DefinePhysicalVolume(), and thePhysicalVolume.
Referenced by G4AdjointPrimaryGenerator::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume().
G4double G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnABoxBoundary (G4VSolid * aSolid, G4ThreeVector & p, G4ThreeVector & direction) private
Definition at line 267 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 267 of file G4AdjointPosOnPhysVolGenerator.cc
References kdfinder::abs(), G4VSolid::CalculateExtent(), Acts::Test::dX, Acts::Test::dY, G4UniformRand, kXAxis, kYAxis, kZAxis, maxY, maxZ, minY, Acts::Test::origin(), phi, and scale.
Referenced by ComputeAreaOfExtSurface(), ComputeAreaOfExtSurfaceStartingFromBox(), GenerateAPositionOnASolidBoundary(), and GenerateAPositionOnTheExtSurfaceOfASolid().
void G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASolidBoundary (G4VSolid * aSolid, G4ThreeVector & p, G4ThreeVector & direction) private
Definition at line 212 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 212 of file G4AdjointPosOnPhysVolGenerator.cc
References G4VSolid::DistanceToIn(), GenerateAPositionOnABoxBoundary(), GenerateAPositionOnASphereBoundary(), kInfinity, and UseSphere.
Referenced by GenerateAPositionOnTheExtSurfaceOfASolid().
G4double G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary (G4VSolid * aSolid, G4ThreeVector & p, G4ThreeVector & direction) private
Definition at line 227 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 227 of file G4AdjointPosOnPhysVolGenerator.cc
References G4VSolid::CalculateExtent(), Acts::Test::dX, Acts::Test::dY, G4UniformRand, kXAxis, kYAxis, kZAxis, maxY, maxZ, minY, Acts::Test::origin(), phi, r, CLHEP::Hep3Vector::rotateY(), CLHEP::Hep3Vector::rotateZ(), scale, CLHEP::Hep3Vector::setRThetaPhi(), and theta().
Referenced by ComputeAreaOfExtSurface(), ComputeAreaOfExtSurfaceStartingFromSphere(), GenerateAPositionOnASolidBoundary(), and GenerateAPositionOnTheExtSurfaceOfASolid().
void G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfASolid (G4VSolid * aSolid, G4ThreeVector & p, G4ThreeVector & direction)
Definition at line 156 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 156 of file G4AdjointPosOnPhysVolGenerator.cc
References GenerateAPositionOnABoxBoundary(), GenerateAPositionOnASolidBoundary(), GenerateAPositionOnASphereBoundary(), and ModelOfSurfaceSource.
Referenced by GenerateAPositionOnTheExtSurfaceOfTheSolid().
void G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume (G4ThreeVector & p, G4ThreeVector & direction)
Definition at line 369 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 369 of file G4AdjointPosOnPhysVolGenerator.cc
References G4cout, GenerateAPositionOnTheExtSurfaceOfTheSolid(), thePhysicalVolume, theTransformationFromPhysVolToWorld, G4AffineTransform::TransformAxis(), and G4AffineTransform::TransformPoint().
Referenced by G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex(), GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume(), and G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex().
void G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume (G4ThreeVector & p, G4ThreeVector & direction, G4double & costh_to_normal)
Definition at line 381 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 381 of file G4AdjointPosOnPhysVolGenerator.cc
References CosThDirComparedToNormal, and GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume().
void G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfTheSolid (G4ThreeVector & p, G4ThreeVector & direction)
Definition at line 170 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 170 of file G4AdjointPosOnPhysVolGenerator.cc
References GenerateAPositionOnTheExtSurfaceOfASolid(), and theSolid.
Referenced by GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume().
G4double G4AdjointPosOnPhysVolGenerator::GetAreaOfExtSurfaceOfThePhysicalVolume () inline
Definition at line 92 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 92 of file G4AdjointPosOnPhysVolGenerator.hh
References AreaOfExtSurfaceOfThePhysicalVolume.
G4double G4AdjointPosOnPhysVolGenerator::GetCosThDirComparedToNormal () inline
Definition at line 93 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 93 of file G4AdjointPosOnPhysVolGenerator.hh
References CosThDirComparedToNormal.
G4AdjointPosOnPhysVolGenerator * G4AdjointPosOnPhysVolGenerator::GetInstance (void) static
Definition at line 48 of file G4AdjointPosOnPhysVolGenerator.cc.
View newest version in sPHENIX GitHub at line 48 of file G4AdjointPosOnPhysVolGenerator.cc
References G4AdjointPosOnPhysVolGenerator(), and theInstance.
Referenced by G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator().
void G4AdjointPosOnPhysVolGenerator::SetSolid (G4VSolid * aSolid) inline
Definition at line 91 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 91 of file G4AdjointPosOnPhysVolGenerator.hh
References theSolid.
Member Data Documentation
G4double G4AdjointPosOnPhysVolGenerator::AreaOfExtSurfaceOfThePhysicalVolume private
Definition at line 117 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by GetAreaOfExtSurfaceOfThePhysicalVolume().
G4double G4AdjointPosOnPhysVolGenerator::CosThDirComparedToNormal private
Definition at line 118 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 118 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume(), and GetCosThDirComparedToNormal().
G4String G4AdjointPosOnPhysVolGenerator::ModelOfSurfaceSource private
Definition at line 115 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by ComputeAreaOfExtSurface(), and GenerateAPositionOnTheExtSurfaceOfASolid().
G4ThreadLocal G4AdjointPosOnPhysVolGenerator * G4AdjointPosOnPhysVolGenerator::theInstance = 0 static private
Definition at line 110 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by GetInstance().
G4VPhysicalVolume* G4AdjointPosOnPhysVolGenerator::thePhysicalVolume private
Definition at line 112 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by ComputeTransformationFromPhysVolToWorld(), DefinePhysicalVolume(), DefinePhysicalVolume1(), and GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume().
G4VSolid* G4AdjointPosOnPhysVolGenerator::theSolid private
Definition at line 111 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by ComputeAreaOfExtSurface(), DefinePhysicalVolume(), GenerateAPositionOnTheExtSurfaceOfTheSolid(), and SetSolid().
G4AffineTransform G4AdjointPosOnPhysVolGenerator::theTransformationFromPhysVolToWorld private
Definition at line 116 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by ComputeTransformationFromPhysVolToWorld(), and GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume().
G4bool G4AdjointPosOnPhysVolGenerator::UseSphere private
Definition at line 114 of file G4AdjointPosOnPhysVolGenerator.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AdjointPosOnPhysVolGenerator.hh
Referenced by ComputeAreaOfExtSurface(), and GenerateAPositionOnASolidBoundary().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4AdjointPosOnPhysVolGenerator.hh
geant4/tree/geant4-10.6-release/source/event/src/G4AdjointPosOnPhysVolGenerator.cc