ECCE @ EIC Software: PhysicsListMessenger Class Reference
PhysicsListMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysicsListMessenger.hh>
Public Member Functions
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
G4double GetMaxChargedStep () const
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
G4double GetMaxChargedStep () const
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
G4double GetMaxChargedStep () const
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
G4double GetMaxChargedStep () const
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
virtual ~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
virtual ~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
virtual ~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *p=0)
virtual ~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
virtual ~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
virtual ~PhysicsListMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PhysicsListMessenger (PhysicsList *)
virtual ~PhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
PhysicsListMessenger & operator= (const PhysicsListMessenger &right)
PhysicsListMessenger (const PhysicsListMessenger &)
Private Attributes
PhysicsList * pPhysicsList
G4UIdirectory * physDir
G4UIcmdWithADoubleAndUnit * gammaCutCmd
G4UIcmdWithADoubleAndUnit * electCutCmd
G4UIcmdWithADoubleAndUnit * protoCutCmd
G4UIcmdWithADoubleAndUnit * allCutCmd
G4UIcmdWithAString * pListCmd
G4UIdirectory * amsDir
PhysicsList * fPhysicsList
G4UIdirectory * fPhysDir
G4UIcmdWithAString * fListCmd
G4UIcmdWithADoubleAndUnit * fStepMaxCmd
G4double fMaxChargedStep
G4UIcmdWithAString * packageListCmd
G4UIcmdWithADoubleAndUnit * fRCmd
PhysicsList * fList
G4UIcmdWithAString * fXTRModelCmd
PhysicsList * fPhysList
G4UIcmdWithABool * fSRTypeCmd
G4UIcmdWithADouble * fGammaToMuPairFacCmd
G4UIcmdWithADouble * fAnnihiToMuPairFacCmd
G4UIcmdWithADouble * fAnnihiToHadronFacCmd
G4UIcmdWithADoubleAndUnit * fECmd
G4UIcmdWithAnInteger * fEBCmd
G4UIcmdWithAnInteger * fCBCmd
G4UIcmdWithAnInteger * fCMCmd
G4UIcmdWithADoubleAndUnit * fADCCmd
G4UIcmdWithADouble * fNorCmd
G4UIcmdWithADoubleAndUnit * fSmCmd
G4UIcmdWithADoubleAndUnit * fPHCmd
G4UIcmdWithADoubleAndUnit * fHCmd
G4UIcmdWithAString * fPListCmd
G4UIcmdWithoutParameter * fListCmd
G4UIcmdWithAnInteger * fVerbCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 43 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 43 of file PhysicsListMessenger.hh
Constructor & Destructor Documentation
PhysicsListMessenger::PhysicsListMessenger (PhysicsList * pPhys)
Definition at line 39 of file PhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 39 of file PhysicsListMessenger.cc
References allCutCmd, G4UIcommand::AvailableForStates(), electCutCmd, G4State_Idle, G4State_PreInit, gammaCutCmd, physDir, pListCmd, protoCutCmd, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
PhysicsListMessenger::~PhysicsListMessenger ()
Definition at line 81 of file PhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 81 of file PhysicsListMessenger.cc
References allCutCmd, electCutCmd, gammaCutCmd, physDir, pListCmd, and protoCutCmd.
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
PhysicsListMessenger::PhysicsListMessenger (PhysicsList * p = 0)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
PhysicsListMessenger::~PhysicsListMessenger ()
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
PhysicsListMessenger::PhysicsListMessenger (const PhysicsListMessenger &) private
PhysicsListMessenger::PhysicsListMessenger (PhysicsList *)
virtual PhysicsListMessenger::~PhysicsListMessenger () virtual
Member Function Documentation
G4double PhysicsListMessenger::GetMaxChargedStep () const inline
Definition at line 55 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file PhysicsListMessenger.hh
References fMaxChargedStep.
Referenced by StepMax::BuildPhysicsTable().
G4double PhysicsListMessenger::GetMaxChargedStep () const inline
Definition at line 55 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file PhysicsListMessenger.hh
References fMaxChargedStep.
G4double PhysicsListMessenger::GetMaxChargedStep () const inline
Definition at line 55 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file PhysicsListMessenger.hh
References fMaxChargedStep.
G4double PhysicsListMessenger::GetMaxChargedStep () const inline
Definition at line 55 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file PhysicsListMessenger.hh
References fMaxChargedStep.
PhysicsListMessenger& PhysicsListMessenger::operator= (const PhysicsListMessenger & right) private
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PhysicsListMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 93 of file PhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 93 of file PhysicsListMessenger.cc
References PhysicsList::AddPhysicsList(), allCutCmd, electCutCmd, gammaCutCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), pListCmd, pPhysicsList, protoCutCmd, PhysicsList::SetCutForElectron(), PhysicsList::SetCutForGamma(), and PhysicsList::SetCutForPositron().
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PhysicsListMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
Member Data Documentation
G4UIcmdWithADoubleAndUnit * PhysicsListMessenger::allCutCmd private
Definition at line 60 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file PhysicsListMessenger.hh
Referenced by PhysicsListMessenger(), SetNewValue(), and ~PhysicsListMessenger().
G4UIdirectory* PhysicsListMessenger::amsDir private
Definition at line 55 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit * PhysicsListMessenger::electCutCmd private
Definition at line 58 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file PhysicsListMessenger.hh
Referenced by PhysicsListMessenger(), SetNewValue(), and ~PhysicsListMessenger().
G4UIcmdWithADoubleAndUnit* PhysicsListMessenger::fADCCmd private
Definition at line 79 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file PhysicsListMessenger.hh
G4UIcmdWithADouble* PhysicsListMessenger::fAnnihiToHadronFacCmd private
Definition at line 63 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsListMessenger.hh
G4UIcmdWithADouble* PhysicsListMessenger::fAnnihiToMuPairFacCmd private
Definition at line 62 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsListMessenger.hh
G4UIcmdWithAnInteger* PhysicsListMessenger::fCBCmd private
Definition at line 76 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file PhysicsListMessenger.hh
G4UIcmdWithAnInteger* PhysicsListMessenger::fCMCmd private
Definition at line 77 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file PhysicsListMessenger.hh
G4UIcmdWithAnInteger * PhysicsListMessenger::fEBCmd private
Definition at line 75 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit * PhysicsListMessenger::fECmd private
Definition at line 74 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file PhysicsListMessenger.hh
G4UIcmdWithADouble* PhysicsListMessenger::fGammaToMuPairFacCmd private
Definition at line 61 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit* PhysicsListMessenger::fHCmd private
Definition at line 78 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file PhysicsListMessenger.hh
PhysicsList* PhysicsListMessenger::fList private
Definition at line 57 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file PhysicsListMessenger.hh
G4UIcmdWithAString * PhysicsListMessenger::fListCmd private
Definition at line 62 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsListMessenger.hh
G4UIcmdWithoutParameter* PhysicsListMessenger::fListCmd private
Definition at line 71 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file PhysicsListMessenger.hh
G4double PhysicsListMessenger::fMaxChargedStep private
Definition at line 64 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file PhysicsListMessenger.hh
Referenced by GetMaxChargedStep().
G4UIcmdWithADouble* PhysicsListMessenger::fNorCmd private
Definition at line 80 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit* PhysicsListMessenger::fPHCmd private
Definition at line 77 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file PhysicsListMessenger.hh
G4UIdirectory * PhysicsListMessenger::fPhysDir private
Definition at line 61 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file PhysicsListMessenger.hh
PhysicsList * PhysicsListMessenger::fPhysicsList private
Definition at line 59 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PhysicsListMessenger.hh
PhysicsList * PhysicsListMessenger::fPhysList private
Definition at line 56 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file PhysicsListMessenger.hh
G4UIcmdWithAString * PhysicsListMessenger::fPListCmd private
Definition at line 70 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit* PhysicsListMessenger::fRCmd private
Definition at line 60 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit* PhysicsListMessenger::fSmCmd private
Definition at line 81 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file PhysicsListMessenger.hh
G4UIcmdWithABool* PhysicsListMessenger::fSRTypeCmd private
Definition at line 59 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit * PhysicsListMessenger::fStepMaxCmd private
Definition at line 63 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsListMessenger.hh
G4UIcmdWithAnInteger* PhysicsListMessenger::fVerbCmd private
Definition at line 63 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsListMessenger.hh
G4UIcmdWithAString* PhysicsListMessenger::fXTRModelCmd private
Definition at line 59 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PhysicsListMessenger.hh
G4UIcmdWithADoubleAndUnit * PhysicsListMessenger::gammaCutCmd private
Definition at line 57 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file PhysicsListMessenger.hh
Referenced by PhysicsListMessenger(), SetNewValue(), and ~PhysicsListMessenger().
G4UIcmdWithAString* PhysicsListMessenger::packageListCmd private
Definition at line 64 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file PhysicsListMessenger.hh
G4UIdirectory * PhysicsListMessenger::physDir private
Definition at line 56 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file PhysicsListMessenger.hh
Referenced by PhysicsListMessenger(), and ~PhysicsListMessenger().
G4UIcmdWithAString * PhysicsListMessenger::pListCmd private
Definition at line 61 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file PhysicsListMessenger.hh
Referenced by PhysicsListMessenger(), SetNewValue(), and ~PhysicsListMessenger().
PhysicsList * PhysicsListMessenger::pPhysicsList private
Definition at line 54 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file PhysicsListMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit * PhysicsListMessenger::protoCutCmd private
Definition at line 59 of file PhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PhysicsListMessenger.hh
Referenced by PhysicsListMessenger(), SetNewValue(), and ~PhysicsListMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/PhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/PhysicsListMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/PhysicsListMessenger.cc