ECCE @ EIC Software: G4PiData Class Reference
G4PiData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4PiData.hh>
Public Member Functions
G4PiData (const G4double *aTotal, const G4double *aInelastic, const G4double *anEnergy, G4int nPoints)
~G4PiData ()=default
G4bool AppliesTo (G4double kineticEnergy)
G4double ReactionXSection (G4double kineticEnergy)
G4double ElasticXSection (G4double kineticEnergy)
G4double TotalXSection (G4double kineticEnergy)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 35 of file G4PiData.hh.
View newest version in sPHENIX GitHub at line 35 of file G4PiData.hh
Constructor & Destructor Documentation
G4PiData::G4PiData (const G4double * aTotal, const G4double * aInelastic, const G4double * anEnergy, G4int nPoints) explicit
Definition at line 35 of file G4PiData.cc.
View newest version in sPHENIX GitHub at line 35 of file G4PiData.cc
References GeV, millibarn, and x.
G4PiData::~G4PiData () default
Member Function Documentation
G4bool G4PiData::AppliesTo (G4double kineticEnergy)
Definition at line 54 of file G4PiData.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PiData.cc
G4double G4PiData::ElasticXSection (G4double kineticEnergy)
Definition at line 85 of file G4PiData.cc.
View newest version in sPHENIX GitHub at line 85 of file G4PiData.cc
References e1, e2, FatalException, G4endl, G4Exception(), it, max, x1, and x2.
G4double G4PiData::ReactionXSection (G4double kineticEnergy)
Definition at line 61 of file G4PiData.cc.
View newest version in sPHENIX GitHub at line 61 of file G4PiData.cc
References e1, e2, FatalException, G4endl, G4Exception(), it, max, x1, and x2.
G4double G4PiData::TotalXSection (G4double kineticEnergy)
Definition at line 109 of file G4PiData.cc.
View newest version in sPHENIX GitHub at line 109 of file G4PiData.cc
References e1, e2, FatalException, G4endl, G4Exception(), it, max, x1, and x2.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4PiData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4PiData.cc