ECCE @ EIC Software: CCalG4Ecal Class Reference
CCalG4Ecal Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Ecal.hh>
Public Types
enum CMType { module1, module2 }
Public Member Functions
CCalG4Ecal (const G4String &name)
virtual ~CCalG4Ecal ()
void setType (CMType ty)
Public Member Functions inherited from CCalEcal
CCalEcal (const G4String &name)
virtual ~CCalEcal ()
G4String getGenMat () const
G4double getWidBox () const
G4double getLengBox () const
G4double getXpos () const
G4double getYpos () const
G4double getZpos () const
G4double getThetaX () const
G4double getPhiX () const
G4double getThetaY () const
G4double getPhiY () const
G4double getThetaZ () const
G4double getPhiZ () const
G4String getLayMat () const
G4int getLayNum () const
G4double getLayRadius () const
G4double getLayAngle () const
G4double getLengFront () const
G4double getLayPar (unsigned int i) const
G4String getCrystMat () const
G4int getCrystNum () const
G4double getCrystLength () const
G4double getCrystTol () const
G4double getCrystPar (unsigned int i) const
G4String getSuppMat () const
G4double getDxSupp () const
G4double getDySupp () const
G4double getDzSupp () const
G4double getDistSupp () const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Public Member Functions inherited from CCalG4Able
CCalG4Able (G4String name)
virtual ~CCalG4Able ()
G4VPhysicalVolume * PhysicalVolume (G4VPhysicalVolume *)
void setVisType (CCalVisualisable::visType, G4LogicalVolume *)
void setSensitivity (G4bool sens=true)
G4bool isSensitive () const
G4String G4Name () const
void setName (const G4String &name)
G4bool operator== (const CCalG4Able &right) const
Static Public Attributes
static G4String idName = "CrystalMatrix"
Protected Member Functions
virtual G4VPhysicalVolume * constructIn (G4VPhysicalVolume *)
virtual void constructSensitive ()
Protected Member Functions inherited from CCalEcal
virtual G4int readFile ()
virtual void constructDaughters ()
Protected Member Functions inherited from CCalDetector
G4int buildFromFile ()
Protected Member Functions inherited from CCalG4Able
void AddCCalG4Able (CCalG4Able *)
Private Member Functions
G4LogicalVolume * constructGlobal ()
Private Attributes
CMType type
std::vector< ptrG4Log > sensitiveLogs
Static Private Attributes
static G4LogicalVolume * crystalmatrixLog = 0
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Protected Attributes inherited from CCalG4Able
G4VPhysicalVolume * detPhysicalVolume
CCalG4AbleTable theG4DetectorsInside
G4String g4ableName
G4bool sensitivity
CCalVisualisable visProperties
G4VisAttributes * g4VisAtt [CCalVisualisable::TotalVisTypes]
Detailed Description
Definition at line 39 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 39 of file CCalG4Ecal.hh
Member Enumeration Documentation
enum CCalG4Ecal::CMType
Enumerator:
module1
module2
Definition at line 42 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 42 of file CCalG4Ecal.hh
Constructor & Destructor Documentation
CCalG4Ecal::CCalG4Ecal (const G4String & name)
Definition at line 65 of file CCalG4Ecal.cc.
View newest version in sPHENIX GitHub at line 65 of file CCalG4Ecal.cc
CCalG4Ecal::~CCalG4Ecal () virtual
Definition at line 68 of file CCalG4Ecal.cc.
View newest version in sPHENIX GitHub at line 68 of file CCalG4Ecal.cc
Member Function Documentation
G4LogicalVolume * CCalG4Ecal::constructGlobal () private
Definition at line 149 of file CCalG4Ecal.cc.
View newest version in sPHENIX GitHub at line 149 of file CCalG4Ecal.cc
References kdfinder::abs(), CCalRotationMatrixFactory::AddMatrix(), angle, deg, CCalMaterialFactory::findMaterial(), CCalRotationMatrixFactory::findMatrix(), G4cout, G4endl, CCalEcal::getCrystLength(), CCalEcal::getCrystMat(), CCalEcal::getCrystNum(), CCalEcal::getCrystPar(), CCalEcal::getCrystTol(), CCalEcal::getDistSupp(), CCalEcal::getDxSupp(), CCalEcal::getDySupp(), CCalEcal::getDzSupp(), CCalEcal::getGenMat(), CCalRotationMatrixFactory::getInstance(), CCalMaterialFactory::getInstance(), CCalEcal::getLayAngle(), CCalEcal::getLayMat(), CCalEcal::getLayNum(), CCalEcal::getLayPar(), CCalEcal::getLayRadius(), CCalEcal::getLengBox(), CCalEcal::getLengFront(), G4LogicalVolume::GetName(), CCalEcal::getSuppMat(), CCalEcal::getWidBox(), idName, mm, CCalVisualisable::OtherServices, CCalVisualisable::PseudoVolumes, CCalVisualisable::Sensitive, sensitiveLogs, CCalG4Able::setVisType(), CCalVisualisable::Support, and tab().
Referenced by constructIn().
G4VPhysicalVolume * CCalG4Ecal::constructIn (G4VPhysicalVolume * mother) protected virtual
Implements CCalG4Able.
Definition at line 74 of file CCalG4Ecal.cc.
View newest version in sPHENIX GitHub at line 74 of file CCalG4Ecal.cc
References CCalRotationMatrixFactory::AddMatrix(), constructGlobal(), crystalmatrixLog, deg, CCalRotationMatrixFactory::findMatrix(), G4cout, G4endl, CCalRotationMatrixFactory::getInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), CCalEcal::getPhiX(), CCalEcal::getPhiY(), CCalEcal::getPhiZ(), CCalEcal::getThetaX(), CCalEcal::getThetaY(), CCalEcal::getThetaZ(), CCalEcal::getXpos(), CCalEcal::getYpos(), CCalEcal::getZpos(), idName, mm, module2, num, tab(), type, x, y, and z.
void CCalG4Ecal::constructSensitive () protected virtual
Reimplemented from CCalG4Able.
Definition at line 276 of file CCalG4Ecal.cc.
View newest version in sPHENIX GitHub at line 276 of file CCalG4Ecal.cc
References G4cout, G4endl, CCalSensitiveDetectors::getInstance(), idName, CCalSensitiveDetectors::registerVolume(), and sensitiveLogs.
void CCalG4Ecal::setType (CMType ty) inline
Definition at line 48 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 48 of file CCalG4Ecal.hh
References type.
Referenced by CCalG4Hall::constructDaughters().
Member Data Documentation
G4LogicalVolume * CCalG4Ecal::crystalmatrixLog = 0 static private
Definition at line 70 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 70 of file CCalG4Ecal.hh
Referenced by constructIn().
G4String CCalG4Ecal::idName = "CrystalMatrix" static
Definition at line 51 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalG4Ecal.hh
Referenced by constructGlobal(), constructIn(), and constructSensitive().
std::vector<ptrG4Log> CCalG4Ecal::sensitiveLogs private
Definition at line 73 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 73 of file CCalG4Ecal.hh
Referenced by constructGlobal(), and constructSensitive().
CMType CCalG4Ecal::type private
Definition at line 67 of file CCalG4Ecal.hh.
View newest version in sPHENIX GitHub at line 67 of file CCalG4Ecal.hh
Referenced by constructIn(), and setType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Ecal.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalG4Ecal.cc