ECCE @ EIC Software: G4TrackingMessenger Class Reference
G4TrackingMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4TrackingMessenger.hh>
Public Member Functions
G4TrackingMessenger (G4TrackingManager *trMan)
~G4TrackingMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4TrackingManager * trackingManager
G4SteppingManager * steppingManager
G4UIdirectory * TrackingDirectory
G4UIcmdWithoutParameter * AbortCmd
G4UIcmdWithoutParameter * ResumeCmd
G4UIcmdWithAnInteger * StoreTrajectoryCmd
G4UIcmdWithAnInteger * VerboseCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 55 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file G4TrackingMessenger.hh
Constructor & Destructor Documentation
G4TrackingMessenger::G4TrackingMessenger (G4TrackingManager * trMan)
Definition at line 59 of file G4TrackingMessenger.cc.
View newest version in sPHENIX GitHub at line 59 of file G4TrackingMessenger.cc
References AbortCmd, G4TrackingManager::GetSteppingManager(), ResumeCmd, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcommand::SetRange(), steppingManager, StoreTrajectoryCmd, TrackingDirectory, trackingManager, and VerboseCmd.
G4TrackingMessenger::~G4TrackingMessenger ()
Definition at line 110 of file G4TrackingMessenger.cc.
View newest version in sPHENIX GitHub at line 110 of file G4TrackingMessenger.cc
References AbortCmd, ResumeCmd, StoreTrajectoryCmd, TrackingDirectory, and VerboseCmd.
Member Function Documentation
G4String G4TrackingMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 157 of file G4TrackingMessenger.cc.
View newest version in sPHENIX GitHub at line 157 of file G4TrackingMessenger.cc
References G4UIcommand::ConvertToString(), G4TrackingManager::GetStoreTrajectory(), G4TrackingManager::GetVerboseLevel(), StoreTrajectoryCmd, trackingManager, and VerboseCmd.
void G4TrackingMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 121 of file G4TrackingMessenger.cc.
View newest version in sPHENIX GitHub at line 121 of file G4TrackingMessenger.cc
References AbortCmd, G4UImanager::ApplyCommand(), G4UIcommand::ConvertToInt(), fStopAndKill, G4ThreadLocal, G4TransportationManager::GetPropagatorInField(), G4SteppingManager::GetTrack(), G4TransportationManager::GetTransportationManager(), G4UImanager::GetUIpointer(), ResumeCmd, G4TrackingManager::SetStoreTrajectory(), G4Track::SetTrackStatus(), G4PropagatorInField::SetTrajectoryFilter(), G4TrackingManager::SetVerboseLevel(), steppingManager, StoreTrajectoryCmd, trackingManager, and VerboseCmd.
Member Data Documentation
G4UIcmdWithoutParameter* G4TrackingMessenger::AbortCmd private
Definition at line 77 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), SetNewValue(), and ~G4TrackingMessenger().
G4UIcmdWithoutParameter* G4TrackingMessenger::ResumeCmd private
Definition at line 78 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), SetNewValue(), and ~G4TrackingMessenger().
G4SteppingManager* G4TrackingMessenger::steppingManager private
Definition at line 73 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), and SetNewValue().
G4UIcmdWithAnInteger* G4TrackingMessenger::StoreTrajectoryCmd private
Definition at line 79 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), GetCurrentValue(), SetNewValue(), and ~G4TrackingMessenger().
G4UIdirectory* G4TrackingMessenger::TrackingDirectory private
Definition at line 76 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), and ~G4TrackingMessenger().
G4TrackingManager* G4TrackingMessenger::trackingManager private
Definition at line 72 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), GetCurrentValue(), and SetNewValue().
G4UIcmdWithAnInteger* G4TrackingMessenger::VerboseCmd private
Definition at line 80 of file G4TrackingMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TrackingMessenger.hh
Referenced by G4TrackingMessenger(), GetCurrentValue(), SetNewValue(), and ~G4TrackingMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4TrackingMessenger.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4TrackingMessenger.cc