ECCE @ EIC Software: CCalVisualisable Class Reference
CCalVisualisable Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalVisualisable.hh>
Classes
class visParameters
Public Types
enum visType {
Sensitive =0, Electronics =1, Support =2, Cable =3,
Absorber =4, OtherServices =5, PseudoVolumes =6, TotalVisTypes =7,
Undefined =-1
}
Public Member Functions
CCalVisualisable (G4String file)
virtual ~CCalVisualisable ()
G4bool readFile (G4String file)
void setDefault ()
G4bool isVisible (visType v) const
void setVisible (visType v, G4bool flag=true)
G4double colorRed (visType v) const
G4double colorGreen (visType v) const
G4double colorBlue (visType v) const
void setColorRed (visType v, G4double r)
void setColorGreen (visType v, G4double g)
void setColorBlue (visType v, G4double b)
void setColor (visType v, G4double r, G4double g, G4double b)
G4bool isWireFrame (visType v) const
void setWireFrame (visType v, G4bool wf=true)
Protected Member Functions
G4bool readFile ()
Static Protected Member Functions
static void setPath ()
Private Member Functions
G4double checkColorRange (G4double color, char type) const
Private Attributes
G4String visFile
visParameters theParameters [TotalVisTypes]
Static Private Attributes
static const char * pathName =0
Detailed Description
Definition at line 35 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 35 of file CCalVisualisable.hh
Member Enumeration Documentation
enum CCalVisualisable::visType
Enumerator:
Sensitive
Electronics
Support
Cable
Absorber
OtherServices
PseudoVolumes
TotalVisTypes
Undefined
Definition at line 40 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalVisualisable.hh
Constructor & Destructor Documentation
CCalVisualisable::CCalVisualisable (G4String file)
Definition at line 41 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 41 of file CCalVisualisable.cc
References pathName, readFile(), setDefault(), and setPath().
virtual CCalVisualisable::~CCalVisualisable () inline virtual
Definition at line 70 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 70 of file CCalVisualisable.hh
Member Function Documentation
G4double CCalVisualisable::checkColorRange (G4double color, char type) const private
Definition at line 159 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 159 of file CCalVisualisable.cc
References G4cerr, G4endl, and visFile.
Referenced by readFile().
G4double CCalVisualisable::colorBlue (visType v) const inline
Definition at line 86 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 86 of file CCalVisualisable.hh
References CCalVisualisable::visParameters::bColor, theParameters, and v.
Referenced by CCalG4Able::setVisType().
G4double CCalVisualisable::colorGreen (visType v) const inline
Definition at line 85 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 85 of file CCalVisualisable.hh
References CCalVisualisable::visParameters::gColor, theParameters, and v.
Referenced by CCalG4Able::setVisType().
G4double CCalVisualisable::colorRed (visType v) const inline
Definition at line 84 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 84 of file CCalVisualisable.hh
References CCalVisualisable::visParameters::rColor, theParameters, and v.
Referenced by CCalG4Able::setVisType().
G4bool CCalVisualisable::isVisible (visType v) const inline
Definition at line 79 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 79 of file CCalVisualisable.hh
References theParameters, v, and CCalVisualisable::visParameters::visibility.
Referenced by CCalG4Able::setVisType().
G4bool CCalVisualisable::isWireFrame (visType v) const inline
Definition at line 92 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 92 of file CCalVisualisable.hh
References theParameters, v, and CCalVisualisable::visParameters::wireframe.
Referenced by CCalG4Able::setVisType().
G4bool CCalVisualisable::readFile (G4String file)
Definition at line 48 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 48 of file CCalVisualisable.cc
References file, readFile(), and visFile.
G4bool CCalVisualisable::readFile () protected
Definition at line 80 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 80 of file CCalVisualisable.cc
References Absorber, b, Cable, checkColorRange(), Electronics, Acts::UnitConstants::g, G4cerr, G4cout, G4endl, jump(), openGeomFile(), OtherServices, pathName, PseudoVolumes, r, readName(), Sensitive, Support, tab(), theParameters, Undefined, visFile, and wireframe().
Referenced by CCalVisualisable(), and readFile().
void CCalVisualisable::setColor (visType v, G4double r, G4double g, G4double b)
Definition at line 62 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 62 of file CCalVisualisable.cc
References b, CCalVisualisable::visParameters::bColor, Acts::UnitConstants::g, CCalVisualisable::visParameters::gColor, r, CCalVisualisable::visParameters::rColor, theParameters, and v.
void CCalVisualisable::setColorBlue (visType v, G4double b) inline
Definition at line 89 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 89 of file CCalVisualisable.hh
References b, CCalVisualisable::visParameters::bColor, theParameters, and v.
void CCalVisualisable::setColorGreen (visType v, G4double g) inline
Definition at line 88 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 88 of file CCalVisualisable.hh
References Acts::UnitConstants::g, CCalVisualisable::visParameters::gColor, theParameters, and v.
void CCalVisualisable::setColorRed (visType v, G4double r) inline
Definition at line 87 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 87 of file CCalVisualisable.hh
References r, CCalVisualisable::visParameters::rColor, theParameters, and v.
void CCalVisualisable::setDefault ()
Definition at line 53 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 53 of file CCalVisualisable.cc
References Cable, Electronics, OtherServices, PseudoVolumes, Sensitive, Support, and theParameters.
Referenced by CCalVisualisable().
void CCalVisualisable::setPath () static protected
Definition at line 68 of file CCalVisualisable.cc.
View newest version in sPHENIX GitHub at line 68 of file CCalVisualisable.cc
References FatalException, G4endl, G4Exception(), pathName, and visEnvName.
Referenced by CCalVisualisable().
void CCalVisualisable::setVisible (visType v, G4bool flag = true) inline
Definition at line 81 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 81 of file CCalVisualisable.hh
References theParameters, v, and CCalVisualisable::visParameters::visibility.
void CCalVisualisable::setWireFrame (visType v, G4bool wf = true) inline
Definition at line 93 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 93 of file CCalVisualisable.hh
References theParameters, v, and CCalVisualisable::visParameters::wireframe.
Member Data Documentation
const char * CCalVisualisable::pathName =0 static private
Definition at line 101 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 101 of file CCalVisualisable.hh
Referenced by CCalVisualisable(), readFile(), and setPath().
visParameters CCalVisualisable::theParameters[TotalVisTypes] private
Definition at line 103 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 103 of file CCalVisualisable.hh
Referenced by colorBlue(), colorGreen(), colorRed(), isVisible(), isWireFrame(), readFile(), setColor(), setColorBlue(), setColorGreen(), setColorRed(), setDefault(), setVisible(), and setWireFrame().
G4String CCalVisualisable::visFile private
Definition at line 102 of file CCalVisualisable.hh.
View newest version in sPHENIX GitHub at line 102 of file CCalVisualisable.hh
Referenced by checkColorRange(), and readFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalVisualisable.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalVisualisable.cc