ECCE @ EIC Software: DicomPhantomParameterisationColour Class Reference
DicomPhantomParameterisationColour Class Reference
Class inherited from G4PhantomParameterisation to provide different.
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomPhantomParameterisationColour.hh>
Public Types
typedef std::map< G4String,
G4VisAttributes * > ColourMap_t
Public Member Functions
DicomPhantomParameterisationColour (G4String colorFile=defaultColorFile)
~DicomPhantomParameterisationColour ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=0)
const ColourMap_t & GetColourMap () const
ColourMap_t & GetColourMap ()
Public Member Functions inherited from G4PhantomParameterisation
G4PhantomParameterisation ()
~G4PhantomParameterisation ()
virtual void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void BuildContainerSolid (G4VPhysicalVolume *pPhysicalVol)
void BuildContainerSolid (G4VSolid *pMotherSolid)
virtual G4int GetReplicaNo (const G4ThreeVector &localPoint, const G4ThreeVector &localDir)
void SetMaterials (std::vector< G4Material * > &mates)
void SetMaterialIndices (size_t *matInd)
void SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
void SetNoVoxel (size_t nx, size_t ny, size_t nz)
G4double GetVoxelHalfX () const
G4double GetVoxelHalfY () const
G4double GetVoxelHalfZ () const
size_t GetNoVoxelX () const
size_t GetNoVoxelY () const
size_t GetNoVoxelZ () const
size_t GetNoVoxel () const
std::vector< G4Material * > GetMaterials () const
size_t * GetMaterialIndices () const
G4VSolid * GetContainerSolid () const
G4ThreeVector GetTranslation (const G4int copyNo) const
G4bool SkipEqualMaterials () const
void SetSkipEqualMaterials (G4bool skip)
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Static Public Attributes
static G4String defaultColorFile
Private Member Functions
void ReadColourData (G4String colourFile)
Private Attributes
ColourMap_t fColours
std::map< G4int,
G4VisAttributes * > mColours
Additional Inherited Members
Protected Attributes inherited from G4PhantomParameterisation
G4double fVoxelHalfX = 0.0
G4double fVoxelHalfY = 0.0
G4double fVoxelHalfZ = 0.0
size_t fNoVoxelX = 0
size_t fNoVoxelY = 0
size_t fNoVoxelZ = 0
size_t fNoVoxelXY = 0
size_t fNoVoxel = 0
std::vector< G4Material * > fMaterials
size_t * fMaterialIndices = nullptr
G4VSolid * fContainerSolid = nullptr
G4double fContainerWallX =0.0
G4double fContainerWallY =0.0
G4double fContainerWallZ =0.0
G4double kCarTolerance
G4bool bSkipEqualMaterials = true
Detailed Description
Class inherited from G4PhantomParameterisation to provide different.
History:
Created. 5 December 2007
Author
P. Arce
Definition at line 48 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 48 of file DicomPhantomParameterisationColour.hh
Member Typedef Documentation
typedef std::map<G4String,G4VisAttributes*> DicomPhantomParameterisationColour::ColourMap_t
Definition at line 51 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 51 of file DicomPhantomParameterisationColour.hh
Constructor & Destructor Documentation
DicomPhantomParameterisationColour::DicomPhantomParameterisationColour (G4String colorFile = defaultColorFile)
Definition at line 48 of file DicomPhantomParameterisationColour.cc.
View newest version in sPHENIX GitHub at line 48 of file DicomPhantomParameterisationColour.cc
References ReadColourData(), and G4PhantomParameterisation::SetSkipEqualMaterials().
DicomPhantomParameterisationColour::~DicomPhantomParameterisationColour ()
Definition at line 57 of file DicomPhantomParameterisationColour.cc.
View newest version in sPHENIX GitHub at line 57 of file DicomPhantomParameterisationColour.cc
Member Function Documentation
G4Material * DicomPhantomParameterisationColour::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = 0) virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 92 of file DicomPhantomParameterisationColour.cc.
View newest version in sPHENIX GitHub at line 92 of file DicomPhantomParameterisationColour.cc
References G4PhantomParameterisation::ComputeMaterial(), fColours, G4String::first(), G4cout, G4endl, G4VVisManager::GetConcreteInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4PhantomParameterisation::GetMaterialIndex(), G4Material::GetName(), mColours, n, and G4LogicalVolume::SetVisAttributes().
const ColourMap_t& DicomPhantomParameterisationColour::GetColourMap () const inline
Definition at line 64 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 64 of file DicomPhantomParameterisationColour.hh
References fColours.
ColourMap_t& DicomPhantomParameterisationColour::GetColourMap () inline
Definition at line 65 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 65 of file DicomPhantomParameterisationColour.hh
References fColours.
void DicomPhantomParameterisationColour::ReadColourData (G4String colourFile) private
Definition at line 62 of file DicomPhantomParameterisationColour.cc.
View newest version in sPHENIX GitHub at line 62 of file DicomPhantomParameterisationColour.cc
References FALSE, fColours, fin, mColours, and G4VisAttributes::SetVisibility().
Referenced by DicomPhantomParameterisationColour().
Member Data Documentation
G4String DicomPhantomParameterisationColour::defaultColorFile static
Initial value:
=
        DicomHandler::GetDicomDataPath() + "/ColourMap.dat"
Definition at line 53 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 53 of file DicomPhantomParameterisationColour.hh
ColourMap_t DicomPhantomParameterisationColour::fColours private
Definition at line 71 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 71 of file DicomPhantomParameterisationColour.hh
Referenced by ComputeMaterial(), GetColourMap(), and ReadColourData().
std::map<G4int, G4VisAttributes*> DicomPhantomParameterisationColour::mColours private
Definition at line 72 of file DicomPhantomParameterisationColour.hh.
View newest version in sPHENIX GitHub at line 72 of file DicomPhantomParameterisationColour.hh
Referenced by ComputeMaterial(), and ReadColourData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomPhantomParameterisationColour.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomPhantomParameterisationColour.cc