ECCE @ EIC Software: G4ScoringMessenger Class Reference
G4ScoringMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringMessenger.hh>
Public Member Functions
G4ScoringMessenger (G4ScoringManager *SManager)
~G4ScoringMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Member Functions
void FillTokenVec (G4String newValues, G4TokenVec &token)
void MeshBinCommand (G4VScoringMesh *mesh, G4TokenVec &token)
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Private Attributes
G4ScoringManager * fSMan
G4UIdirectory * scoreDir
G4UIcmdWithoutParameter * listCmd
G4UIcmdWithoutParameter * dumpCmd
G4UIcmdWithAnInteger * verboseCmd
G4UIdirectory * meshCreateDir
G4UIcmdWithAString * meshBoxCreateCmd
G4UIcmdWithAString * meshCylinderCreateCmd
G4UIcommand * meshRWLogVolCreateCmd
G4UIdirectory * meshDir
G4UIcmdWithAString * meshOpnCmd
G4UIcmdWithoutParameter * meshClsCmd
G4UIcmdWith3VectorAndUnit * mBoxSizeCmd
G4UIcommand * mCylinderSizeCmd
G4UIcommand * mBinCmd
G4UIdirectory * mTransDir
G4UIcmdWithoutParameter * mTResetCmd
G4UIcmdWith3VectorAndUnit * mTXyzCmd
G4UIdirectory * mRotDir
G4UIcmdWithADoubleAndUnit * mRotXCmd
G4UIcmdWithADoubleAndUnit * mRotYCmd
G4UIcmdWithADoubleAndUnit * mRotZCmd
G4UIcommand * drawCmd
G4UIcommand * drawColumnCmd
G4UIdirectory * colorMapDir
G4UIcmdWithoutParameter * listColorMapCmd
G4UIcmdWithAString * floatMinMaxCmd
G4UIcommand * colorMapMinMaxCmd
G4UIcommand * dumpQtyToFileCmd
G4UIcommand * dumpAllQtsToFileCmd
G4UIcommand * dumpQtyWithFactorCmd
G4UIcommand * dumpAllQtsWithFactorCmd
Additional Inherited Members
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 62 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ScoringMessenger.hh
Constructor & Destructor Documentation
G4ScoringMessenger::G4ScoringMessenger (G4ScoringManager * SManager)
Definition at line 50 of file G4ScoringMessenger.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ScoringMessenger.cc
References colorMapDir, colorMapMinMaxCmd, drawCmd, drawColumnCmd, dumpAllQtsToFileCmd, dumpAllQtsWithFactorCmd, dumpCmd, dumpQtyToFileCmd, dumpQtyWithFactorCmd, floatMinMaxCmd, listCmd, listColorMapCmd, mBinCmd, mBoxSizeCmd, mCylinderSizeCmd, meshBoxCreateCmd, meshClsCmd, meshCreateDir, meshCylinderCreateCmd, meshDir, meshOpnCmd, meshRWLogVolCreateCmd, mRotDir, mRotXCmd, mRotYCmd, mRotZCmd, mTransDir, mTResetCmd, mTXyzCmd, scoreDir, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIparameter::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4UIparameter::SetParameterRange(), G4UIcommand::SetRange(), G4UIcommand::SetToBeBroadcasted(), and verboseCmd.
G4ScoringMessenger::~G4ScoringMessenger ()
Definition at line 333 of file G4ScoringMessenger.cc.
View newest version in sPHENIX GitHub at line 333 of file G4ScoringMessenger.cc
References colorMapDir, colorMapMinMaxCmd, drawCmd, drawColumnCmd, dumpAllQtsToFileCmd, dumpAllQtsWithFactorCmd, dumpCmd, dumpQtyWithFactorCmd, floatMinMaxCmd, listCmd, listColorMapCmd, mBinCmd, mBoxSizeCmd, mCylinderSizeCmd, meshBoxCreateCmd, meshClsCmd, meshCreateDir, meshCylinderCreateCmd, meshDir, meshOpnCmd, meshRWLogVolCreateCmd, mRotDir, mRotXCmd, mRotYCmd, mRotZCmd, mTransDir, mTResetCmd, mTXyzCmd, scoreDir, and verboseCmd.
Member Function Documentation
void G4ScoringMessenger::FillTokenVec (G4String newValues, G4TokenVec & token) protected
Definition at line 696 of file G4ScoringMessenger.cc.
View newest version in sPHENIX GitHub at line 696 of file G4ScoringMessenger.cc
Referenced by SetNewValue().
G4String G4ScoringMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 687 of file G4ScoringMessenger.cc.
View newest version in sPHENIX GitHub at line 687 of file G4ScoringMessenger.cc
References G4UIcommand::ConvertToString(), fSMan, G4ScoringManager::GetVerboseLevel(), and verboseCmd.
void G4ScoringMessenger::MeshBinCommand (G4VScoringMesh * mesh, G4TokenVec & token) protected
Definition at line 706 of file G4ScoringMessenger.cc.
View newest version in sPHENIX GitHub at line 706 of file G4ScoringMessenger.cc
References FatalException, G4cout, G4endl, G4Exception(), G4VScoringMesh::SetNumberOfSegments(), and G4UImessenger::StoI().
Referenced by SetNewValue().
void G4ScoringMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 381 of file G4ScoringMessenger.cc.
View newest version in sPHENIX GitHub at line 381 of file G4ScoringMessenger.cc
References G4ScoringManager::CloseCurrentMesh(), colorMapMinMaxCmd, G4UIcommand::CommandFailed(), drawCmd, drawColumnCmd, G4ScoringManager::DrawMesh(), G4ScoringManager::Dump(), dumpAllQtsToFileCmd, dumpAllQtsWithFactorCmd, G4ScoringManager::DumpAllQuantitiesToFile(), dumpCmd, dumpQtyToFileCmd, dumpQtyWithFactorCmd, G4ScoringManager::DumpQuantityToFile(), fac, FillTokenVec(), G4ScoringManager::FindMesh(), floatMinMaxCmd, fSMan, G4endl, G4UIcommand::GetCommandPath(), G4ScoringManager::GetCurrentMesh(), G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ScoringManager::GetScoreColorMap(), G4VScoringMesh::GetShape(), G4VScoringMesh::GetWorldName(), incremental_prev_tag::idx, G4ScoringManager::List(), listCmd, listColorMapCmd, G4ScoringManager::ListScoreColorMaps(), mBinCmd, mBoxSizeCmd, mCylinderSizeCmd, MeshBinCommand(), meshBoxCreateCmd, meshClsCmd, meshCylinderCreateCmd, meshOpnCmd, meshRWLogVolCreateCmd, mRotXCmd, mRotYCmd, mRotZCmd, mTResetCmd, mTXyzCmd, G4ScoringManager::RegisterScoringMesh(), G4VScoringMesh::RotateX(), G4VScoringMesh::RotateY(), G4VScoringMesh::RotateZ(), G4VScoringMesh::SetCenterPosition(), G4ScoringManager::SetCurrentMesh(), G4ScoringManager::SetFactor(), G4VScoreColorMap::SetFloatingMinMax(), G4VScoreColorMap::SetMinMax(), G4VScoringMesh::SetSize(), G4ScoringManager::SetVerboseLevel(), G4UImessenger::StoD(), G4UImessenger::StoI(), G4UIcommand::ValueOf(), verboseCmd, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4UIdirectory* G4ScoringMessenger::colorMapDir private
Definition at line 123 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::colorMapMinMaxCmd private
Definition at line 126 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::drawCmd private
Definition at line 121 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::drawColumnCmd private
Definition at line 122 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::dumpAllQtsToFileCmd private
Definition at line 131 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::dumpAllQtsWithFactorCmd private
Definition at line 133 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithoutParameter* G4ScoringMessenger::dumpCmd private
Definition at line 86 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::dumpQtyToFileCmd private
Definition at line 130 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and SetNewValue().
G4UIcommand* G4ScoringMessenger::dumpQtyWithFactorCmd private
Definition at line 132 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithAString* G4ScoringMessenger::floatMinMaxCmd private
Definition at line 125 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4ScoringManager* G4ScoringMessenger::fSMan private
Definition at line 83 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ScoringMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIcmdWithoutParameter* G4ScoringMessenger::listCmd private
Definition at line 85 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithoutParameter* G4ScoringMessenger::listColorMapCmd private
Definition at line 124 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::mBinCmd private
Definition at line 108 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWith3VectorAndUnit* G4ScoringMessenger::mBoxSizeCmd private
Definition at line 103 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::mCylinderSizeCmd private
Definition at line 104 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithAString* G4ScoringMessenger::meshBoxCreateCmd private
Definition at line 90 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithoutParameter* G4ScoringMessenger::meshClsCmd private
Definition at line 99 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIdirectory* G4ScoringMessenger::meshCreateDir private
Definition at line 89 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and ~G4ScoringMessenger().
G4UIcmdWithAString* G4ScoringMessenger::meshCylinderCreateCmd private
Definition at line 91 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIdirectory* G4ScoringMessenger::meshDir private
Definition at line 96 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and ~G4ScoringMessenger().
G4UIcmdWithAString* G4ScoringMessenger::meshOpnCmd private
Definition at line 97 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcommand* G4ScoringMessenger::meshRWLogVolCreateCmd private
Definition at line 93 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIdirectory* G4ScoringMessenger::mRotDir private
Definition at line 114 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and ~G4ScoringMessenger().
G4UIcmdWithADoubleAndUnit* G4ScoringMessenger::mRotXCmd private
Definition at line 116 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithADoubleAndUnit* G4ScoringMessenger::mRotYCmd private
Definition at line 117 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWithADoubleAndUnit* G4ScoringMessenger::mRotZCmd private
Definition at line 118 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIdirectory* G4ScoringMessenger::mTransDir private
Definition at line 111 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and ~G4ScoringMessenger().
G4UIcmdWithoutParameter* G4ScoringMessenger::mTResetCmd private
Definition at line 112 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIcmdWith3VectorAndUnit* G4ScoringMessenger::mTXyzCmd private
Definition at line 113 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), SetNewValue(), and ~G4ScoringMessenger().
G4UIdirectory* G4ScoringMessenger::scoreDir private
Definition at line 84 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), and ~G4ScoringMessenger().
G4UIcmdWithAnInteger* G4ScoringMessenger::verboseCmd private
Definition at line 87 of file G4ScoringMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ScoringMessenger.hh
Referenced by G4ScoringMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ScoringMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringMessenger.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoringMessenger.cc