ECCE @ EIC Software: macros/blob/master/common/G4_mRICH.C File Reference
G4_mRICH.C File Reference
Aerogel mRICH for EIC detector.
#include "GlobalVariables.C"
#include <g4main/PHG4Reco.h>
#include <g4mrich/PHG4mRICHSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <eccefastpidreco/ECCEFastPIDReco.h>
#include <eccefastpidreco/ECCEmRICHFastPIDMap.h>
Namespaces
namespace Enable
Functions
void mRICHInit ()
void mRICHSetup (PHG4Reco *g4Reco, const int detectorSetup=1, const int mRICHsystemSetup=6)
void mRICHReco (int verbosity=0)
void mRICH_Eval (std::string outputfile, int verbosity=0)
Variables
bool Enable::mRICH = false
bool Enable::mRICH_RECO = false
bool Enable::mRICH_OVERLAPCHECK = false
int Enable::mRICH_VERBOSITY = 0
Detailed Description
Aerogel mRICH for EIC detector.
Author
Murad Sarsour
Date
Date:
2020/7/2
Definition in file G4_mRICH.C.
Function Documentation
void mRICH_Eval (std::string outputfile, int verbosity = 0)
Definition at line 82 of file G4_mRICH.C.
View newest version in sPHENIX GitHub at line 82 of file G4_mRICH.C
References Fun4AllServer::instance().
void mRICHInit ()
Definition at line 28 of file G4_mRICH.C.
View newest version in sPHENIX GitHub at line 28 of file G4_mRICH.C
Referenced by G4Init().
void mRICHReco (int verbosity = 0)
Definition at line 66 of file G4_mRICH.C.
View newest version in sPHENIX GitHub at line 66 of file G4_mRICH.C
References Fun4AllServer::instance(), max, EICPIDDefs::mRICH, Enable::mRICH_VERBOSITY, Fun4AllServer::registerSubsystem(), ECCEFastPIDMap::Verbosity(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), and Fun4All_G4_EICDetector_AnaTutorial().
void mRICHSetup (PHG4Reco * g4Reco, const int detectorSetup = 1, const int mRICHsystemSetup = 6)
Definition at line 41 of file G4_mRICH.C.
View newest version in sPHENIX GitHub at line 41 of file G4_mRICH.C
References TRACKING::FastKalmanFilter(), Enable::mRICH_OVERLAPCHECK, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), TRACKING::ProjectionNames, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::SetCalibrationFileDir(), PHG4DetectorSubsystem::UseCalibFiles(), and PHG4DetectorSubsystem::xml.
Referenced by G4Setup().