ECCE @ EIC Software: G4ParticleMessenger Class Reference
G4ParticleMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticleMessenger.hh>
Public Member Functions
G4ParticleMessenger (G4ParticleTable *pTable=0)
virtual ~G4ParticleMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4ParticleMessenger (const G4ParticleMessenger &)
Private Attributes
G4UIdirectory * thisDirectory
G4UIcmdWithAString * listCmd
G4UIcmdWithAString * selectCmd
G4UIcmdWithAnInteger * findCmd
G4UIcmdWithoutParameter * createAllIonCmd
G4UIcmdWithoutParameter * createAllIsomerCmd
G4UIcmdWithAnInteger * verboseCmd
G4ParticleTable * theParticleTable
G4ParticleDefinition * currentParticle
G4ParticlePropertyMessenger * fParticlePropertyMessenger
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 92 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleMessenger.hh
Constructor & Destructor Documentation
G4ParticleMessenger::G4ParticleMessenger (G4ParticleTable * pTable = 0)
Definition at line 59 of file G4ParticleMessenger.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleMessenger.cc
References G4UIcommand::AvailableForStates(), createAllIonCmd, createAllIsomerCmd, currentParticle, findCmd, fParticlePropertyMessenger, G4State_Idle, G4State_PreInit, G4ParticleTable::GetParticleTable(), listCmd, selectCmd, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcommand::SetRange(), G4UIcommand::SetToBeBroadcasted(), theParticleTable, thisDirectory, and verboseCmd.
G4ParticleMessenger::~G4ParticleMessenger () virtual
Definition at line 124 of file G4ParticleMessenger.cc.
View newest version in sPHENIX GitHub at line 124 of file G4ParticleMessenger.cc
References createAllIonCmd, createAllIsomerCmd, findCmd, fParticlePropertyMessenger, listCmd, selectCmd, thisDirectory, and verboseCmd.
G4ParticleMessenger::G4ParticleMessenger (const G4ParticleMessenger &) inline private
Definition at line 104 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleMessenger.hh
Member Function Documentation
G4String G4ParticleMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 202 of file G4ParticleMessenger.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ParticleMessenger.cc
References G4UIcommand::ConvertToString(), currentParticle, G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetVerboseLevel(), particle, selectCmd, G4UIcmdWithAString::SetCandidates(), theParticleTable, G4ParticleTableIterator< K, V >::value(), and verboseCmd.
void G4ParticleMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 139 of file G4ParticleMessenger.cc.
View newest version in sPHENIX GitHub at line 139 of file G4ParticleMessenger.cc
References G4IonTable::CreateAllIon(), createAllIonCmd, G4IonTable::CreateAllIsomer(), createAllIsomerCmd, currentParticle, G4ParticleDefinition::DumpTable(), findCmd, G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleTable::GetIonTable(), G4ParticleTable::GetIterator(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), listCmd, particle, selectCmd, G4UIcmdWithAString::SetCandidates(), G4ParticleTable::SetVerboseLevel(), theParticleTable, tmp, G4ParticleTableIterator< K, V >::value(), and verboseCmd.
Member Data Documentation
G4UIcmdWithoutParameter* G4ParticleMessenger::createAllIonCmd private
Definition at line 111 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), SetNewValue(), and ~G4ParticleMessenger().
G4UIcmdWithoutParameter* G4ParticleMessenger::createAllIsomerCmd private
Definition at line 112 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), SetNewValue(), and ~G4ParticleMessenger().
G4ParticleDefinition* G4ParticleMessenger::currentParticle private
Definition at line 116 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), GetCurrentValue(), and SetNewValue().
G4UIcmdWithAnInteger* G4ParticleMessenger::findCmd private
Definition at line 110 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), SetNewValue(), and ~G4ParticleMessenger().
G4ParticlePropertyMessenger* G4ParticleMessenger::fParticlePropertyMessenger private
Definition at line 118 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), and ~G4ParticleMessenger().
G4UIcmdWithAString* G4ParticleMessenger::listCmd private
Definition at line 108 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), SetNewValue(), and ~G4ParticleMessenger().
G4UIcmdWithAString* G4ParticleMessenger::selectCmd private
Definition at line 109 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleMessenger().
G4ParticleTable* G4ParticleMessenger::theParticleTable private
Definition at line 115 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), GetCurrentValue(), and SetNewValue().
G4UIdirectory* G4ParticleMessenger::thisDirectory private
Definition at line 104 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), and ~G4ParticleMessenger().
G4UIcmdWithAnInteger* G4ParticleMessenger::verboseCmd private
Definition at line 113 of file G4ParticleMessenger.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleMessenger.hh
Referenced by G4ParticleMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticleMessenger.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4ParticleMessenger.cc