ECCE @ EIC Software: G4RunManager Class Reference
G4RunManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4RunManager.hh>
Public Types
enum RMType { sequentialRM, masterRM, workerRM }
Public Member Functions
G4RunManager ()
virtual ~G4RunManager ()
virtual void BeamOn (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void Initialize ()
virtual void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
virtual void AbortRun (G4bool softAbort=false)
virtual void AbortEvent ()
virtual void InitializeGeometry ()
virtual void InitializePhysics ()
virtual G4bool ConfirmBeamOnCondition ()
virtual void RunInitialization ()
virtual void DoEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void RunTermination ()
virtual void InitializeEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void ProcessOneEvent (G4int i_event)
virtual void TerminateOneEvent ()
virtual void TerminateEventLoop ()
virtual G4Event * GenerateEvent (G4int i_event)
virtual void AnalyzeEvent (G4Event *anEvent)
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
virtual void rndmSaveThisRun ()
virtual void rndmSaveThisEvent ()
virtual void RestoreRandomNumberStatus (const G4String &fileN)
virtual void SetUserInitialization (G4VUserDetectorConstruction *userInit)
virtual void SetUserInitialization (G4VUserPhysicsList *userInit)
virtual void SetUserInitialization (G4VUserActionInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerThreadInitialization *userInit)
virtual void SetUserAction (G4UserRunAction *userAction)
virtual void SetUserAction (G4VUserPrimaryGeneratorAction *userAction)
virtual void SetUserAction (G4UserEventAction *userAction)
virtual void SetUserAction (G4UserStackingAction *userAction)
virtual void SetUserAction (G4UserTrackingAction *userAction)
virtual void SetUserAction (G4UserSteppingAction *userAction)
const G4VUserDetectorConstruction * GetUserDetectorConstruction () const
const G4VUserPhysicsList * GetUserPhysicsList () const
const G4VUserActionInitialization * GetUserActionInitialization () const
G4VUserActionInitialization * GetNonConstUserActionInitialization () const
const G4UserWorkerInitialization * GetUserWorkerInitialization () const
const
G4UserWorkerThreadInitialization * GetUserWorkerThreadInitialization () const
const G4UserRunAction * GetUserRunAction () const
const
G4VUserPrimaryGeneratorAction * GetUserPrimaryGeneratorAction () const
const G4UserEventAction * GetUserEventAction () const
const G4UserStackingAction * GetUserStackingAction () const
const G4UserTrackingAction * GetUserTrackingAction () const
const G4UserSteppingAction * GetUserSteppingAction () const
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
const G4String & GetVersionString () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
void StoreRandomNumberStatusToG4Event (G4int vl)
G4int GetFlagRandomNumberStatusToG4Event () const
void SetRandomNumberStore (G4bool flag)
G4bool GetRandomNumberStore () const
void SetRandomNumberStoreDir (const G4String &dir)
const G4String & GetRandomNumberStoreDir () const
const G4String & GetRandomNumberStatusForThisRun () const
const G4String & GetRandomNumberStatusForThisEvent () const
void SetRandomNumberStorePerEvent (G4bool flag)
G4bool GetRandomNumberStorePerEvent () const
void GeometryHasBeenModified (G4bool prop=true)
void ReinitializeGeometry (G4bool destroyFirst=false, G4bool prop=true)
void PhysicsHasBeenModified ()
void CutOffHasBeenModified ()
void ReOptimizeMotherOf (G4VPhysicalVolume *)
void ReOptimize (G4LogicalVolume *)
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
G4int GetPrintProgress ()
void SetPrintProgress (G4int i)
void SetGeometryToBeOptimized (G4bool vl)
G4bool GetGeometryToBeOptimized ()
void SetNumberOfEventsToBeStored (G4int val)
const G4Run * GetCurrentRun () const
G4Run * GetNonConstCurrentRun () const
const G4Event * GetCurrentEvent () const
const G4Event * GetPreviousEvent (G4int i) const
void SetRunIDCounter (G4int i)
G4int GetNumberOfParallelWorld () const
void SetNumberOfEventsToBeProcessed (G4int val)
G4int GetNumberOfEventsToBeProcessed () const
G4int GetNumberOfSelectEvents () const
G4String GetSelectMacro () const
void SetDCtable (G4DCtable *DCtbl)
RMType GetRunManagerType () const
virtual void ConstructScoringWorlds ()
virtual void RestoreRndmEachEvent (G4bool)
void GeometryDirectlyUpdated (G4bool val=true)
Static Public Member Functions
static G4RunManager * GetRunManager ()
static G4bool IfGeometryHasBeenDestroyed ()
Protected Member Functions
void CleanUpPreviousEvents ()
void CleanUpUnnecessaryEvents (G4int keepNEvents)
void StackPreviousEvent (G4Event *anEvent)
G4RunManager (RMType rmType)
virtual void StoreRNGStatus (const G4String &filenamePrefix)
void UpdateScoring ()
virtual void DeleteUserInitializations ()
Protected Attributes
G4RunManagerKernel * kernel
G4EventManager * eventManager
G4VUserDetectorConstruction * userDetector
G4VUserPhysicsList * physicsList
G4VUserActionInitialization * userActionInitialization
G4UserWorkerInitialization * userWorkerInitialization
G4UserWorkerThreadInitialization * userWorkerThreadInitialization
G4UserRunAction * userRunAction
G4VUserPrimaryGeneratorAction * userPrimaryGeneratorAction
G4UserEventAction * userEventAction
G4UserStackingAction * userStackingAction
G4UserTrackingAction * userTrackingAction
G4UserSteppingAction * userSteppingAction
G4bool geometryInitialized
G4bool physicsInitialized
G4bool runAborted
G4bool initializedAtLeastOnce
G4bool geometryToBeOptimized
G4int runIDCounter
G4int verboseLevel
G4int printModulo
G4Timer * timer
G4DCtable * DCtable
G4Run * currentRun
G4Event * currentEvent
std::list< G4Event * > * previousEvents
G4int n_perviousEventsToBeStored
G4int numberOfEventToBeProcessed
G4bool storeRandomNumberStatus
G4int storeRandomNumberStatusToG4Event
G4String randomNumberStatusDir
G4String randomNumberStatusForThisRun
G4String randomNumberStatusForThisEvent
G4bool rngStatusEventsFlag
G4VPhysicalVolume * currentWorld
G4int nParallelWorlds
G4String msgText
G4int n_select_msg
G4int numberOfEventProcessed
G4String selectMacro
G4bool fakeRun
G4bool isScoreNtupleWriter
RMType runManagerType
G4bool geometryDirectlyUpdated
Static Protected Attributes
static G4bool fGeometryHasBeenDestroyed = false
Private Member Functions
G4RunManager (const G4RunManager &)
G4RunManager & operator= (const G4RunManager &)
Private Attributes
G4RunMessenger * runMessenger
Static Private Attributes
static G4ThreadLocal G4RunManager * fRunManager = 0
Detailed Description
Definition at line 137 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4RunManager.hh
Member Enumeration Documentation
enum G4RunManager::RMType
Enumerator:
sequentialRM
masterRM
workerRM
Definition at line 267 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 267 of file G4RunManager.hh
Constructor & Destructor Documentation
G4RunManager::G4RunManager ()
Definition at line 83 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 83 of file G4RunManager.cc
References G4ParticleTable::CreateMessenger(), eventManager, FatalException, fRunManager, G4Exception(), G4RunManagerKernel::GetEventManager(), G4ParticleTable::GetParticleTable(), G4ProcessTable::GetProcessTable(), kernel, previousEvents, randomNumberStatusDir, randomNumberStatusForThisEvent, randomNumberStatusForThisRun, runManagerType, runMessenger, sequentialRM, and timer.
G4RunManager::~G4RunManager () virtual
Definition at line 186 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 186 of file G4RunManager.cc
References CleanUpPreviousEvents(), currentRun, G4ParticleTable::DeleteMessenger(), DeleteUserInitializations(), fRunManager, G4cout, G4endl, G4State_Quit, G4StateManager::GetCurrentState(), G4ParticleTable::GetParticleTable(), G4StateManager::GetStateManager(), kernel, previousEvents, runMessenger, G4StateManager::SetNewState(), timer, userPrimaryGeneratorAction, userRunAction, and verboseLevel.
G4RunManager::G4RunManager (RMType rmType) protected
Definition at line 123 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 123 of file G4RunManager.cc
References G4ParticleTable::CreateMessenger(), eventManager, FatalException, fRunManager, G4Exception(), G4RunManagerKernel::GetEventManager(), G4ParticleTable::GetParticleTable(), G4ProcessTable::GetProcessTable(), kernel, masterRM, previousEvents, randomNumberStatusDir, randomNumberStatusForThisEvent, randomNumberStatusForThisRun, runManagerType, runMessenger, timer, and workerRM.
G4RunManager::G4RunManager (const G4RunManager &) inline private
Definition at line 585 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 585 of file G4RunManager.hh
Member Function Documentation
void G4RunManager::AbortEvent () virtual
Reimplemented in G4MTRunManager.
Definition at line 669 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 669 of file G4RunManager.cc
References G4EventManager::AbortCurrentEvent(), currentEvent, eventManager, G4cerr, G4endl, G4State_EventProc, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), and G4Event::SetEventAborted().
Referenced by export_G4RunManager(), G4ExceptionHandler::Notify(), PrimaryKiller::ProcessHits(), and G4RunMessenger::SetNewValue().
void G4RunManager::AbortRun (G4bool softAbort = false) virtual
Reimplemented in G4MTRunManager.
Definition at line 649 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 649 of file G4RunManager.cc
References G4EventManager::AbortCurrentEvent(), currentEvent, eventManager, G4cerr, G4endl, G4State_EventProc, G4State_GeomClosed, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), runAborted, and G4Event::SetEventAborted().
Referenced by RMC01AnalysisManager::EndOfEvent(), export_G4RunManager(), CML2PrimaryGenerationAction::fillParticlesContainer(), G4ExceptionHandler::Notify(), and G4RunMessenger::SetNewValue().
void G4RunManager::AnalyzeEvent (G4Event * anEvent) virtual
Definition at line 488 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 488 of file G4RunManager.cc
References currentRun, G4VPersistencyManager::GetPersistencyManager(), G4Run::RecordEvent(), and G4VPersistencyManager::Store().
Referenced by CexmcRunManager::DoCommonEventLoop(), G4WorkerRunManager::ProcessOneEvent(), and ProcessOneEvent().
void G4RunManager::BeamOn (G4int n_event, const char * macroFile = 0, G4int n_select = -1) virtual
Definition at line 264 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 264 of file G4RunManager.cc
References ConfirmBeamOnCondition(), ConstructScoringWorlds(), DoEventLoop(), fakeRun, numberOfEventProcessed, numberOfEventToBeProcessed, RunInitialization(), RunTermination(), and TIMEMORY_AUTO_TIMER.
Referenced by GammaKnifeController::BeamOn(), G4BlineTracer::ComputeBlines(), G4WorkerRunManager::DoWork(), export_G4RunManager(), G4MTRunManager::Initialize(), main(), PHG4Reco::process_event(), G4AdjointSimManager::RunAdjointSimulation(), and G4RunMessenger::SetNewValue().
void G4RunManager::CleanUpPreviousEvents () protected
Definition at line 512 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 512 of file G4RunManager.cc
References previousEvents, and G4Event::ToBeKept().
Referenced by G4WorkerRunManager::RunInitialization(), RunInitialization(), and ~G4RunManager().
void G4RunManager::CleanUpUnnecessaryEvents (G4int keepNEvents) protected
Definition at line 531 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 531 of file G4RunManager.cc
References G4Event::GetNumberOfGrips(), previousEvents, and G4Event::ToBeKept().
Referenced by RunTermination(), and StackPreviousEvent().
G4bool G4RunManager::ConfirmBeamOnCondition () virtual
Definition at line 282 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 282 of file G4RunManager.cc
References G4cerr, G4cout, G4endl, G4State_Idle, G4State_PreInit, geometryInitialized, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), Initialize(), initializedAtLeastOnce, physicsInitialized, and verboseLevel.
Referenced by BeamOn().
void G4RunManager::ConstructScoringWorlds () virtual
Reimplemented in G4WorkerRunManager, G4MTRunManager, and tbbWorkerRunManager.
Definition at line 793 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 793 of file G4RunManager.cc
References G4ProcessManager::AddProcess(), G4VScoringMesh::Construct(), fGeometryHasBeenDestroyed, G4VScoringMesh::GeometryHasBeenDestroyed(), GeometryHasBeenModified(), G4ParticleTable::GetIterator(), G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4TransportationManager::GetParallelWorld(), G4VScoringMesh::GetParallelWorldProcess(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), G4ScoringManager::GetScoringManagerIfExist(), G4VScoringMesh::GetShape(), G4TransportationManager::GetTransportationManager(), G4ScoringManager::GetWorldName(), idxAlongStep, idxAtRest, idxPostStep, G4ParallelWorldProcess::IsAtRestRequired(), G4TransportationManager::IsWorldExisting(), particle, G4ParticleTableIterator< K, V >::reset(), G4VPhysicalVolume::SetName(), G4ParallelWorldProcess::SetParallelWorld(), G4VScoringMesh::SetParallelWorldProcess(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToSecond(), theParticleIterator, TIMEMORY_AUTO_TIMER, and G4ParticleTableIterator< K, V >::value().
Referenced by BeamOn(), G4MTRunManager::ConstructScoringWorlds(), and G4RunMessenger::SetNewValue().
void G4RunManager::CutOffHasBeenModified () inline
Definition at line 479 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 479 of file G4RunManager.hh
References G4cerr, and G4endl.
void G4RunManager::DefineWorldVolume (G4VPhysicalVolume * worldVol, G4bool topologyIsChanged = true) virtual
Definition at line 685 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 685 of file G4RunManager.cc
References G4RunManagerKernel::DefineWorldVolume(), and kernel.
Referenced by DetectorConstruction::BuildBoundingVolume(), DetectorConstruction::DrawAtoms_(), DetectorConstruction::DrawAtomsWithBounding_(), DetectorConstruction::DrawNucleotides_(), DetectorConstruction::DrawNucleotidesWithBounding_(), DetectorConstruction::DrawResidues_(), DetectorConstruction::DrawResiduesWithBounding_(), export_G4RunManager(), DetectorConstruction::LoadPDBfile(), DetectorConstruction::SetMaterial(), DetectorConstruction::SetMethod(), G4GDMLMessenger::SetNewValue(), DetectorConstruction::UpdateGeometry(), ExN03DetectorConstruction::UpdateGeometry(), and GammaRayTelDetectorConstruction::UpdateGeometry().
void G4RunManager::DeleteUserInitializations () protected virtual
Definition at line 229 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 229 of file G4RunManager.cc
References G4cout, G4endl, physicsList, userActionInitialization, userDetector, userWorkerInitialization, userWorkerThreadInitialization, and verboseLevel.
Referenced by ~G4RunManager().
void G4RunManager::DoEventLoop (G4int n_event, const char * macroFile = 0, G4int n_select = -1) virtual
Reimplemented in CexmcRunManager, G4WorkerRunManager, ParRunManager, and ParRunManager.
Definition at line 373 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 373 of file G4RunManager.cc
References InitializeEventLoop(), ProcessOneEvent(), runAborted, runManagerType, sequentialRM, TerminateEventLoop(), TerminateOneEvent(), and TIMEMORY_AUTO_TIMER.
Referenced by BeamOn().
void G4RunManager::DumpRegion (const G4String & rname) const
Definition at line 770 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 770 of file G4RunManager.cc
References G4RunManagerKernel::DumpRegion(), and kernel.
Referenced by G4RunMessenger::SetNewValue().
void G4RunManager::DumpRegion (G4Region * region = 0) const
Definition at line 775 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 775 of file G4RunManager.cc
References G4RunManagerKernel::DumpRegion(), and kernel.
G4Event * G4RunManager::GenerateEvent (G4int i_event) virtual
Reimplemented in G4WorkerRunManager.
Definition at line 445 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 445 of file G4RunManager.cc
References currentRun, FatalException, G4cout, G4endl, G4Exception(), G4VUserPrimaryGeneratorAction::GeneratePrimaries(), G4Event::GetEventID(), G4Run::GetRunID(), printModulo, randomNumberStatusForThisEvent, rngStatusEventsFlag, G4Event::SetRandomNumberStatus(), storeRandomNumberStatus, storeRandomNumberStatusToG4Event, StoreRNGStatus(), TIMEMORY_AUTO_TIMER, and userPrimaryGeneratorAction.
Referenced by CexmcRunManager::DoCommonEventLoop(), and ProcessOneEvent().
void G4RunManager::GeometryDirectlyUpdated (G4bool val = true) inline
Definition at line 600 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 600 of file G4RunManager.hh
References geometryDirectlyUpdated.
Referenced by G4GDMLMessenger::SetNewValue().
void G4RunManager::GeometryHasBeenModified (G4bool prop = true)
Definition at line 971 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 971 of file G4RunManager.cc
References G4UImanager::ApplyCommand(), G4RunManagerKernel::GeometryHasBeenModified(), G4UImanager::GetUIpointer(), and kernel.
Referenced by CML2PhantomConstruction::applyNewCentre(), UltraDetectorConstruction::ConstructReflector(), ConstructScoringWorlds(), export_G4RunManager(), IORTGeometryController::registerGeometry(), CML2AcceleratorConstruction::rotateAccelerator(), DetectorConstruction::SetAbsLength(), GB03DetectorConstruction::SetAbsorberMaterial(), RE06DetectorConstruction::SetAbsorberMaterial(), B5DetectorConstruction::SetArmAngle(), DetectorConstruction::SetCytoMaterial(), DetectorConstruction::SetDiameter(), DetectorConstruction::SetEcalLength(), DetectorConstruction::SetEcalWidth(), GB03DetectorConstruction::SetGapMaterial(), RE06DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetLength(), XrayFluoDetectorMessenger::SetNewValue(), DMXDetectorMessenger::SetNewValue(), XrayFluoMercuryDetectorMessenger::SetNewValue(), XrayFluoPlaneDetectorMessenger::SetNewValue(), G4RunMessenger::SetNewValue(), DetectorConstruction::SetNuclMaterial(), GB03DetectorConstruction::SetNumberOfLayers(), RE06DetectorConstruction::SetNumberOfLayers(), DetectorConstruction::SetPadLength(), DetectorConstruction::SetPadWidth(), ElectronBenchmarkDetector::SetPrimFoilThickness(), G4EicDircDetector::SetQuantumEfficiency(), RE06DetectorConstruction::SetSerialGeometry(), DetectorConstruction::SetSurfaceFinish(), DetectorConstruction::SetSurfaceModel(), DetectorConstruction::SetSurfacePolish(), DetectorConstruction::SetSurfaceSigmaAlpha(), DetectorConstruction::SetSurfaceType(), DetectorConstruction::SetVertexLength(), DetectorConstruction::SetWorldMaterial(), and GammaKnifeDetectorConstruction::UpdateHelmet().
const G4Event* G4RunManager::GetCurrentEvent () const inline
Definition at line 532 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 532 of file G4RunManager.hh
References currentEvent.
Referenced by Par02Output::CreateNtuples(), export_G4RunManager(), RE01StackingAction::GetCalCollection(), RE05StackingAction::GetCollection(), ExN04StackingAction::GetCollection(), G4DigiManager::GetDigiCollection(), G4DigiManager::GetHitsCollection(), WLSSteppingAction::SaveRandomStatus(), and G4DigiManager::SetDigiCollection().
const G4Run* G4RunManager::GetCurrentRun () const inline
Definition at line 526 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 526 of file G4RunManager.hh
References currentRun.
Referenced by G4TheMTRayTracer::CreateBitMap(), G4TrajectoriesModel::DescribeYourselfTo(), G4VisManager::Draw(), G4VisManager::Enable(), G4VisManager::EndOfEvent(), G4VisManager::EndOfRun(), export_G4RunManager(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VSceneHandler::ProcessScene(), WLSSteppingAction::SaveRandomStatus(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), and CexmcEventAction::UpdateRunHits().
G4int G4RunManager::GetFlagRandomNumberStatusToG4Event () const inline
Definition at line 407 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 407 of file G4RunManager.hh
References storeRandomNumberStatusToG4Event.
Referenced by G4RunMessenger::GetCurrentValue().
G4bool G4RunManager::GetGeometryToBeOptimized () inline
Definition at line 516 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 516 of file G4RunManager.hh
References geometryToBeOptimized.
Referenced by export_G4RunManager().
G4Run* G4RunManager::GetNonConstCurrentRun () const inline
Definition at line 528 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 528 of file G4RunManager.hh
References currentRun.
Referenced by B4bEventAction::BeginOfEventAction(), B4bEventAction::EndOfEventAction(), EventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), doiPETEventAction::EndOfEventAction(), STCyclotronPrimaryGeneratorAction::GeneratePrimaries(), TargetSD::Initialize(), PhantomSD::Initialize(), TrackingAction::PostUserTrackingAction(), STCyclotronSensitiveTarget::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), PhantomSD::ProcessHits(), B4bSteppingAction::UserSteppingAction(), and doiPETSteppingAction::UserSteppingAction().
G4VUserActionInitialization* G4RunManager::GetNonConstUserActionInitialization () const inline
Definition at line 365 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 365 of file G4RunManager.hh
References userActionInitialization.
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
G4int G4RunManager::GetNumberOfEventsToBeProcessed () const inline
Definition at line 560 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 560 of file G4RunManager.hh
References numberOfEventToBeProcessed.
Referenced by G4VisManager::BeginOfRun(), G4WorkerRunManager::DoWork(), G4VisManager::EndOfEvent(), and G4VisManager::EndOfRun().
G4int G4RunManager::GetNumberOfParallelWorld () const inline
Definition at line 556 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 556 of file G4RunManager.hh
References nParallelWorlds.
G4int G4RunManager::GetNumberOfSelectEvents () const inline
Definition at line 562 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 562 of file G4RunManager.hh
References n_select_msg.
Referenced by G4WorkerRunManager::DoWork(), and tbbTask::execute().
const G4Event* G4RunManager::GetPreviousEvent (G4int i) const inline
Definition at line 536 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 536 of file G4RunManager.hh
References n_perviousEventsToBeStored, and previousEvents.
Referenced by G4DigiManager::GetDigiCollection(), and G4DigiManager::GetHitsCollection().
G4int G4RunManager::GetPrintProgress () inline
Definition at line 502 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 502 of file G4RunManager.hh
References printModulo.
Referenced by B4bEventAction::EndOfEventAction(), B4dEventAction::EndOfEventAction(), B4cEventAction::EndOfEventAction(), B4aEventAction::EndOfEventAction(), and G4RunMessenger::GetCurrentValue().
const G4String& G4RunManager::GetRandomNumberStatusForThisEvent () const inline
Definition at line 439 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 439 of file G4RunManager.hh
References G4Exception(), JustWarning, randomNumberStatusForThisEvent, and storeRandomNumberStatusToG4Event.
const G4String& G4RunManager::GetRandomNumberStatusForThisRun () const inline
Definition at line 437 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 437 of file G4RunManager.hh
References randomNumberStatusForThisRun.
G4bool G4RunManager::GetRandomNumberStore () const inline
Definition at line 413 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 413 of file G4RunManager.hh
References storeRandomNumberStatus.
Referenced by export_G4RunManager().
const G4String& G4RunManager::GetRandomNumberStoreDir () const inline
Definition at line 435 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 435 of file G4RunManager.hh
References randomNumberStatusDir.
Referenced by export_G4RunManager(), G4RunMessenger::GetCurrentValue(), and WLSSteppingAction::SaveRandomStatus().
G4bool G4RunManager::GetRandomNumberStorePerEvent () const inline
Definition at line 449 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 449 of file G4RunManager.hh
References rngStatusEventsFlag.
G4RunManager * G4RunManager::GetRunManager () static
Definition at line 80 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 80 of file G4RunManager.cc
Referenced by GammaKnifePhysicsList::AddPhysicsList(), HadrontherapyPhysicsList::AddPhysicsList(), IORTPhysicsList::AddPhysicsList(), CML2PhantomConstruction::applyNewCentre(), B2RunAction::B2RunAction(), B4bRunAction::B4bRunAction(), B4RunAction::B4RunAction(), GammaKnifeController::BeamOn(), HadrontherapyInteractionParameters::BeamOn(), G4MPImanager::BeamOn(), RunAction::BeginMaster(), B4bEventAction::BeginOfEventAction(), DMXEventAction::BeginOfEventAction(), CexmcEventAction::BeginOfEventAction(), G4VisManager::BeginOfRun(), B3aRunAction::BeginOfRunAction(), ExN04RunAction::BeginOfRunAction(), RE01RunAction::BeginOfRunAction(), B3bRunAction::BeginOfRunAction(), B2RunAction::BeginOfRunAction(), F04RunAction::BeginOfRunAction(), HadrontherapyRunAction::BeginOfRunAction(), STCyclotronRunAction::BeginOfRunAction(), DicomRunAction::BeginOfRunAction(), B1RunAction::BeginOfRunAction(), GammaKnifeRunAction::BeginOfRunAction(), B1ConRunAction::BeginOfRunAction(), FFRunAction::BeginOfRunAction(), WLSRunAction::BeginOfRunAction(), IORTRunAction::BeginOfRunAction(), doiPETRunAction::BeginOfRunAction(), TSRunAction::BeginOfRunAction(), PurgMagActionInitializer::Build(), XrayFluoActionInitializer::Build(), DetectorConstruction::BuildBoundingVolume(), HadrontherapyModulator::BuildSteps(), CexmcChargeExchangeReconstructor::CexmcChargeExchangeReconstructor(), CexmcEnergyDepositDigitizer::CexmcEnergyDepositDigitizer(), CexmcReconstructor::CexmcReconstructor(), CexmcSteppingAction::CexmcSteppingAction(), CexmcTrackingAction::CexmcTrackingAction(), CexmcTrackPointsDigitizer::CexmcTrackPointsDigitizer(), BrachyDetectorConstructionFlexi::CleanFlexi(), BrachyDetectorConstructionI::CleanIodium(), BrachyDetectorConstructionOncura6711::CleanOncura6711(), BrachyDetectorConstructionTG186::CleanTG186(), G4BlineTracer::ComputeBlines(), Construct(), pyExN01pl::Construct(), pyExN03geom::Construct(), pyQgeom::Construct(), pyMedicalBeam::Construct(), pyParticleGun::Construct(), pyEZgeom::Construct(), CexmcSetup::Construct(), UltraDetectorConstruction::ConstructReflector(), Par02Output::CreateNtuples(), G4AdjointSimManager::DefineUserActions(), IORTDetectorConstruction::DeleteDisc(), G4TrajectoriesModel::DescribeYourselfTo(), CexmcEnergyDepositDigitizer::Digitize(), G4VisManager::Draw(), DetectorConstruction::DrawAtoms_(), DetectorConstruction::DrawAtomsWithBounding_(), DetectorConstruction::DrawNucleotides_(), DetectorConstruction::DrawNucleotidesWithBounding_(), DetectorConstruction::DrawResidues_(), DetectorConstruction::DrawResiduesWithBounding_(), ElectronRunAction::ElectronRunAction(), G4VisManager::Enable(), RunAction::EndMaster(), RMC01AnalysisManager::EndOfEvent(), G4VisManager::EndOfEvent(), B4bEventAction::EndOfEventAction(), EventAction::EndOfEventAction(), B4dEventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), B4cEventAction::EndOfEventAction(), doiPETEventAction::EndOfEventAction(), B4aEventAction::EndOfEventAction(), G4VisManager::EndOfRun(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), B02RunAction::EndOfRunAction(), B03RunAction::EndOfRunAction(), B01RunAction::EndOfRunAction(), RE02RunAction::EndOfRunAction(), export_G4RunManager(), CML2PrimaryGenerationAction::fillParticlesContainer(), G4DigiManager::G4DigiManager(), G4MonopoleTransportation::G4MonopoleTransportation(), GammaRayTelAnalysis::GammaRayTelAnalysis(), GammaRayTelAnticoincidenceSD::GammaRayTelAnticoincidenceSD(), GammaRayTelCalorimeterSD::GammaRayTelCalorimeterSD(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GammaRayTelTrackerSD::GammaRayTelTrackerSD(), STCyclotronPrimaryGeneratorAction::GeneratePrimaries(), UltraPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), HepMCG4Interface::GeneratePrimaryVertex(), RE01StackingAction::GetCalCollection(), RE05StackingAction::GetCollection(), ExN04StackingAction::GetCollection(), G4WorkerRunManager::GetWorkerRunManager(), HadrontherapyLet::HadrontherapyLet(), TargetSD::Initialize(), PhantomSD::Initialize(), G4ErrorRunManagerHelper::InitializePhysics(), RunAction::InitializeWorker(), PHG4ScoringManager::InitRun(), CexmcProductionModel::IsGoodCandidateForAngularRange(), DetectorConstruction::LoadPDBfile(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), G4ExceptionHandler::Notify(), G4VisCommandSceneAddEventID::EventID::operator()(), TrackingAction::PostUserTrackingAction(), source::print_version(), RunAction::PrintRunInfo(), STCyclotronSensitiveTarget::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), PhantomSD::ProcessHits(), PrimaryKiller::ProcessHits(), G4VSceneHandler::ProcessScene(), HadrontherapyGeometryController::registerGeometry(), IORTGeometryController::registerGeometry(), LaserDrivenBeamLine::RemoveESS(), LaserDrivenBeamLine::RemoveQuads(), G4EzWorld::Reset(), G4AdjointSimManager::ResetRestOfUserActions(), G4AdjointSimManager::ResetUserActions(), G4AdjointSimManager::ResetUserPrimaryRunAndStackingActions(), G4EzWorld::Resize(), CML2AcceleratorConstruction::rotateAccelerator(), RunAction::RunAction(), G4AdjointSimManager::RunAdjointSimulation(), WLSSteppingAction::SaveRandomStatus(), DetectorConstruction::SetAbsLength(), DetectorConstruction::SetAbsMaterial(), GB03DetectorConstruction::SetAbsorberMaterial(), RE06DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorberMaterial(), F03DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), F03DetectorConstruction::SetAbsorberRadius(), F01DetectorConstruction::SetAbsorberRadius(), F02DetectorConstruction::SetAbsorberRadius(), DetectorConstruction::SetAbsorberThickness(), F03DetectorConstruction::SetAbsorberThickness(), F01DetectorConstruction::SetAbsorberThickness(), F02DetectorConstruction::SetAbsorberThickness(), F03DetectorConstruction::SetAbsorberZpos(), F01DetectorConstruction::SetAbsorberZpos(), F02DetectorConstruction::SetAbsorberZpos(), DetectorConstruction::SetAbsorLength(), DetectorConstruction::SetAbsorMaterial(), DetectorConstruction::SetAbsorRadius(), DetectorConstruction::SetAbsorSizeYZ(), DetectorConstruction::SetAbsorThickness(), G4AdjointSimManager::SetAdjointActions(), G4AdjointSimManager::SetAdjointPrimaryRunAndStackingActions(), TrentoPassiveProtonBeamLine::SetAirTubeYSize(), TrentoPassiveProtonBeamLine::SetAirTubeZSize(), B5DetectorConstruction::SetArmAngle(), WLSDetectorConstruction::SetBarBase(), WLSDetectorConstruction::SetBarLength(), DetectorConstruction::SetCalorSizeYZ(), F04DetectorConstruction::SetCaptureMgntB1(), F04DetectorConstruction::SetCaptureMgntB2(), F04DetectorConstruction::SetCaptureMgntLength(), F04DetectorConstruction::SetCaptureMgntRadius(), WLSDetectorConstruction::SetClad1Radius(), WLSDetectorConstruction::SetClad2Radius(), WLSDetectorConstruction::SetCoatingRadius(), WLSDetectorConstruction::SetCoatingThickness(), DetectorConstruction::SetCoef(), DetectorConstruction::SetContainerMaterial(), DetectorConstruction::SetContainMaterial(), DetectorConstruction::SetContainThickness(), DetectorConstruction::SetCytoMaterial(), DetectorConstruction::SetCytoThickness(), F04DetectorConstruction::SetDegraderMaterial(), F04DetectorConstruction::SetDegraderPos(), F04DetectorConstruction::SetDegraderRadius(), F04DetectorConstruction::SetDegraderThickness(), DetectorConstruction::SetDetectorLength(), DetectorConstruction::SetDetectorMaterial(), DetectorConstruction::SetDetectorThickness(), DetectorConstruction::SetDiameter(), LXeDetectorConstruction::SetDimensions(), IORTDetectorConstruction::SetDiscoMaterialIORT(), IORTDetectorConstruction::SetDiscoMaterialIORT1(), DetectorConstruction::SetEcalLength(), DetectorConstruction::SetEcalMaterial(), DetectorConstruction::SetEcalWidth(), LaserDrivenBeamLine::SetFirstCollimatorPositionZ(), LaserDrivenBeamLine::SetFirstCollimatorRadius(), LaserDrivenBeamLine::SetFirstCollimatorThickness(), PassiveProtonBeamLine::SetFirstScatteringFoilXSize(), STCyclotronDetectorConstruction::SetFoilElementAbundance(), STCyclotronDetectorConstruction::SetFoilElementName(), STCyclotronDetectorConstruction::SetFoilElementNComponents(), STCyclotronDetectorConstruction::SetFoilElementSymbole(), STCyclotronDetectorConstruction::SetFoilIsotopeA(), STCyclotronDetectorConstruction::SetFoilIsotopeN(), STCyclotronDetectorConstruction::SetFoilIsotopeName(), STCyclotronDetectorConstruction::SetFoilIsotopeZ(), STCyclotronDetectorConstruction::SetFoilMaterial(), STCyclotronDetectorConstruction::SetFoilMaterialDensity(), STCyclotronDetectorConstruction::SetFoilMaterialFractionMass(), STCyclotronDetectorConstruction::SetFoilMaterialNComponents(), STCyclotronDetectorConstruction::SetFoilNaturalElement(), STCyclotronDetectorConstruction::SetFoilNaturalMaterialFractionMass(), STCyclotronDetectorConstruction::SetFoilThickness(), DetectorConstruction::SetG1(), DetectorConstruction::SetG2(), DetectorConstruction::SetG3(), DetectorConstruction::SetG4(), WLSDetectorConstruction::SetGap(), GB03DetectorConstruction::SetGapMaterial(), RE06DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGapThickness(), DetectorConstruction::SetGasMaterial(), DetectorConstruction::SetGrid(), WLSDetectorConstruction::SetHoleRadius(), LXeDetectorConstruction::SetHousingReflectivity(), LXeDetectorConstruction::SetHousingThickness(), PassiveCarbonBeamLine::SetInnerRadiusFinalCollimator(), PassiveProtonBeamLine::SetInnerRadiusFinalCollimator(), Collimator70BeamLine::SetInnerRadiusFinalCollimatorIORT(), Collimator100BeamLine::SetInnerRadiusFinalCollimatorIORT(), Collimator40BeamLine::SetInnerRadiusFinalCollimatorIORT(), Collimator50BeamLine::SetInnerRadiusFinalCollimatorIORT(), Collimator60BeamLine::SetInnerRadiusFinalCollimatorIORT(), Collimator80BeamLine::SetInnerRadiusFinalCollimatorIORT(), HistoManager::SetIonPhysics(), DetectorConstruction::SetLength(), LXeDetectorConstruction::SetMainVolumeOn(), DetectorConstruction::SetMaterial(), ExGflashDetectorConstruction::SetMaterial(), DetectorConstruction::SetMethod(), WLSDetectorConstruction::SetMirror(), WLSDetectorConstruction::SetMirrorPolish(), WLSDetectorConstruction::SetMirrorReflectivity(), DetectorConstruction::SetModel(), HadrontherapyModulator::SetModulatorAngle(), HadrontherapyModulator::SetModulatorInnerRadius(), HadrontherapyModulator::SetModulatorMaterial(), HadrontherapyModulator::SetModulatorOuterRadius(), HadrontherapyModulator::SetModulatorPosition(), DetectorConstruction::SetNbOfAbsor(), DetectorConstruction::SetNbOfDivisions(), DetectorConstruction::SetNbOfLayers(), LXeDetectorMessenger::SetNewValue(), XrayFluoPhysicsListMessenger::SetNewValue(), XrayFluoDetectorMessenger::SetNewValue(), G4GDMLMessenger::SetNewValue(), DMXDetectorMessenger::SetNewValue(), XrayFluoMercuryDetectorMessenger::SetNewValue(), XrayFluoPlaneDetectorMessenger::SetNewValue(), CexmcParticleGunMessenger::SetNewValue(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4AdjointSimMessenger::SetNewValue(), LXeDetectorConstruction::SetNFibers(), DetectorConstruction::SetNuclMaterial(), DetectorConstruction::SetNuclRadius(), WLSDetectorConstruction::SetNumberOfCladding(), GB03DetectorConstruction::SetNumberOfLayers(), RE06DetectorConstruction::SetNumberOfLayers(), LXeDetectorConstruction::SetNX(), LXeDetectorConstruction::SetNY(), LXeDetectorConstruction::SetNZ(), Collimator40BeamLine::SetOuterRadiusFinalCollimatorIORT(), Collimator100BeamLine::SetOuterRadiusFinalCollimatorIORT(), Collimator80BeamLine::SetOuterRadiusFinalCollimatorIORT(), Collimator70BeamLine::SetOuterRadiusFinalCollimatorIORT(), Collimator60BeamLine::SetOuterRadiusFinalCollimatorIORT(), Collimator50BeamLine::SetOuterRadiusFinalCollimatorIORT(), PassiveProtonBeamLine::SetOuterRadiusStopper(), DetectorConstruction::SetPadLength(), DetectorConstruction::SetPadWidth(), IORTDetectorConstruction::SetPhantomMaterial(), HadrontherapyDetectorConstruction::SetPhantomMaterial(), WLSDetectorConstruction::SetPhotonDetAlignment(), WLSDetectorConstruction::SetPhotonDetGeometry(), WLSDetectorConstruction::SetPhotonDetHalfLength(), WLSDetectorConstruction::SetPhotonDetPolish(), WLSDetectorConstruction::SetPhotonDetReflectivity(), LXeDetectorConstruction::SetPMTRadius(), TrentoPassiveProtonBeamLine::SetPreCollimatorXPosition(), TrentoPassiveProtonBeamLine::SetPreCollimatorXSize(), ElectronBenchmarkDetector::SetPrimFoilMaterial(), ElectronBenchmarkDetector::SetPrimFoilThickness(), DetectorConstruction::SetProfile(), G4EicDircDetector::SetQuantumEfficiency(), PassiveProtonBeamLine::SetRangeShifterXPosition(), PassiveProtonBeamLine::SetRangeShifterXSize(), UltraDetectorConstruction::SetReflectionType(), G4AdjointSimManager::SetRestOfAdjointActions(), PassiveCarbonBeamLine::SetRippleFilterXPosition(), CCalPrimaryGeneratorAction::SetRunNo(), LXeDetectorConstruction::SetSaveThreshold(), TrentoPassiveProtonBeamLine::SetScatteringFoilXSize(), LaserDrivenBeamLine::SetSecondCollimatorPositionZ(), LaserDrivenBeamLine::SetSecondCollimatorRadius(), LaserDrivenBeamLine::SetSecondCollimatorThickness(), PassiveProtonBeamLine::SetSecondScatteringFoilXSize(), RE06DetectorConstruction::SetSerialGeometry(), LaserDrivenBeamLine::SetSlitHoleDimensionY(), LaserDrivenBeamLine::SetSlitHoleDimensionZ(), LaserDrivenBeamLine::SetSlitHolePositionZ(), LXeDetectorConstruction::SetSphereOn(), DetectorConstruction::SetSurfaceFinish(), DetectorConstruction::SetSurfaceModel(), DetectorConstruction::SetSurfacePolish(), WLSDetectorConstruction::SetSurfaceRoughness(), DetectorConstruction::SetSurfaceSigmaAlpha(), DetectorConstruction::SetSurfaceType(), DetectorConstruction::SetTankMaterial(), DetectorConstruction::SetTarget1Material(), DetectorConstruction::SetTarget2Material(), F04DetectorConstruction::SetTargetAngle(), STCyclotronDetectorConstruction::SetTargetDiameter(), STCyclotronDetectorConstruction::SetTargetElementAbundance(), STCyclotronDetectorConstruction::SetTargetElementName(), STCyclotronDetectorConstruction::SetTargetElementNComponents(), STCyclotronDetectorConstruction::SetTargetElementSymbole(), STCyclotronDetectorConstruction::SetTargetIsotopeA(), STCyclotronDetectorConstruction::SetTargetIsotopeN(), STCyclotronDetectorConstruction::SetTargetIsotopeName(), STCyclotronDetectorConstruction::SetTargetIsotopeZ(), DetectorConstruction::SetTargetMaterial(), STCyclotronDetectorConstruction::SetTargetMaterial(), F04DetectorConstruction::SetTargetMaterial(), STCyclotronDetectorConstruction::SetTargetMaterialDensity(), STCyclotronDetectorConstruction::SetTargetMaterialFractionMass(), STCyclotronDetectorConstruction::SetTargetMaterialNComponents(), STCyclotronDetectorConstruction::SetTargetNaturalElement(), STCyclotronDetectorConstruction::SetTargetNaturalMaterialFractionMass(), F04DetectorConstruction::SetTargetPos(), F04DetectorConstruction::SetTargetRadius(), STCyclotronDetectorConstruction::SetTargetThickness(), F04DetectorConstruction::SetTargetThickness(), LaserDrivenBeamLine::SetThicknessSlit(), F04DetectorConstruction::SetTransferMgntB(), F04DetectorConstruction::SetTransferMgntLength(), F04DetectorConstruction::SetTransferMgntPos(), F04DetectorConstruction::SetTransferMgntRadius(), CexmcSetup::SetupSpecialVolumes(), G4VUserActionInitialization::SetUserAction(), DetectorConstruction::SetVertexLength(), WLSDetectorConstruction::SetWLSLength(), WLSDetectorConstruction::SetWLSRadius(), LXeDetectorConstruction::SetWLSSlabOn(), DetectorConstruction::SetWorldMaterial(), F03DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), F04DetectorConstruction::SetWorldMaterial(), F03DetectorConstruction::SetWorldSizeR(), F02DetectorConstruction::SetWorldSizeR(), F01DetectorConstruction::SetWorldSizeR(), F04DetectorConstruction::SetWorldSizeR(), F03DetectorConstruction::SetWorldSizeZ(), F01DetectorConstruction::SetWorldSizeZ(), F02DetectorConstruction::SetWorldSizeZ(), F04DetectorConstruction::SetWorldSizeZ(), WLSDetectorConstruction::SetXYRatio(), CCalSensAssign::stackingAction(), BrachyDetectorConstruction::SwitchBrachytherapicSeed(), ThrowExceptionIfProjectIsRead(), G4HumanPhantomEventAction::totalEventEnergyDeposit(), G4MPIsession::TryForcedTerminate(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), DetectorConstruction::UpdateGeometry(), IORTGeometryController::UpdateGeometry(), ExN03DetectorConstruction::UpdateGeometry(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), GammaRayTelDetectorConstruction::UpdateGeometry(), IORTDetectorConstruction::UpdateGeometry(), HadrontherapyDetectorConstruction::UpdateGeometry(), GammaKnifeDetectorConstruction::UpdateHelmet(), STCyclotronDetectorConstruction::UpdateMaterial(), CexmcEventAction::UpdateRunHits(), G4MPImanager::UpdateStatus(), OpNoviceSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), and G4Run::~G4Run().
RMType G4RunManager::GetRunManagerType () const inline
Definition at line 570 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 570 of file G4RunManager.hh
References runManagerType.
Referenced by RunAction::BeginMaster(), RunAction::EndMaster(), G4RunMessenger::GetCurrentValue(), RunAction::PrintRunInfo(), G4RunMessenger::SetNewValue(), and G4Run::~G4Run().
G4String G4RunManager::GetSelectMacro () const inline
Definition at line 564 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 564 of file G4RunManager.hh
References selectMacro.
Referenced by G4WorkerRunManager::DoWork(), and tbbTask::execute().
const G4VUserActionInitialization* G4RunManager::GetUserActionInitialization () const inline
Definition at line 363 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 363 of file G4RunManager.hh
References userActionInitialization.
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
const G4VUserDetectorConstruction* G4RunManager::GetUserDetectorConstruction () const inline
Definition at line 359 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 359 of file G4RunManager.hh
References userDetector.
Referenced by PurgMagActionInitializer::Build(), XrayFluoActionInitializer::Build(), CexmcEnergyDepositDigitizer::CexmcEnergyDepositDigitizer(), CexmcReconstructor::CexmcReconstructor(), CexmcSteppingAction::CexmcSteppingAction(), CexmcTrackingAction::CexmcTrackingAction(), CexmcTrackPointsDigitizer::CexmcTrackPointsDigitizer(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), B01RunAction::EndOfRunAction(), B02RunAction::EndOfRunAction(), B03RunAction::EndOfRunAction(), RE02RunAction::EndOfRunAction(), tbbTask::execute(), export_G4RunManager(), G4MonopoleTransportation::G4MonopoleTransportation(), GammaRayTelAnalysis::GammaRayTelAnalysis(), GammaRayTelAnticoincidenceSD::GammaRayTelAnticoincidenceSD(), GammaRayTelCalorimeterSD::GammaRayTelCalorimeterSD(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GammaRayTelTrackerSD::GammaRayTelTrackerSD(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), RunAction::RunAction(), G4MTRunManagerKernel::StartThread(), HadrontherapyDetectorConstruction::UpdateGeometry(), and B1SteppingAction::UserSteppingAction().
const G4UserEventAction* G4RunManager::GetUserEventAction () const inline
Definition at line 375 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 375 of file G4RunManager.hh
References userEventAction.
Referenced by G4BlineTracer::ComputeBlines(), G4AdjointSimManager::DefineUserActions(), export_G4RunManager(), DMXSteppingAction::UserSteppingAction(), and G4RTWorkerInitialization::WorkerRunStart().
const G4VUserPhysicsList* G4RunManager::GetUserPhysicsList () const inline
Definition at line 361 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 361 of file G4RunManager.hh
References physicsList.
Referenced by CexmcSetup::Construct(), tbbTask::execute(), export_G4RunManager(), and G4MTRunManagerKernel::StartThread().
const G4VUserPrimaryGeneratorAction* G4RunManager::GetUserPrimaryGeneratorAction () const inline
Definition at line 373 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 373 of file G4RunManager.hh
References userPrimaryGeneratorAction.
Referenced by DMXEventAction::BeginOfEventAction(), CexmcChargeExchangeReconstructor::CexmcChargeExchangeReconstructor(), G4BlineTracer::ComputeBlines(), G4AdjointSimManager::DefineUserActions(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), export_G4RunManager(), RE06DetectorConstruction::SetSerialGeometry(), and G4RTWorkerInitialization::WorkerRunStart().
const G4UserRunAction* G4RunManager::GetUserRunAction () const inline
Definition at line 371 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 371 of file G4RunManager.hh
References userRunAction.
Referenced by DMXEventAction::BeginOfEventAction(), G4BlineTracer::ComputeBlines(), G4AdjointSimManager::DefineUserActions(), export_G4RunManager(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), main(), G4TheMTRayTracer::StoreUserActions(), G4HumanPhantomEventAction::totalEventEnergyDeposit(), and G4RTWorkerInitialization::WorkerRunStart().
const G4UserStackingAction* G4RunManager::GetUserStackingAction () const inline
Definition at line 377 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 377 of file G4RunManager.hh
References userStackingAction.
Referenced by G4BlineTracer::ComputeBlines(), G4AdjointSimManager::DefineUserActions(), export_G4RunManager(), and G4RTWorkerInitialization::WorkerRunStart().
const G4UserSteppingAction* G4RunManager::GetUserSteppingAction () const inline
Definition at line 381 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 381 of file G4RunManager.hh
References userSteppingAction.
Referenced by G4BlineTracer::ComputeBlines(), G4AdjointSimManager::DefineUserActions(), export_G4RunManager(), and G4RTWorkerInitialization::WorkerRunStart().
const G4UserTrackingAction* G4RunManager::GetUserTrackingAction () const inline
Definition at line 379 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 379 of file G4RunManager.hh
References userTrackingAction.
Referenced by CexmcEventAction::BeginOfEventAction(), G4BlineTracer::ComputeBlines(), G4AdjointSimManager::DefineUserActions(), export_G4RunManager(), RunAction::InitializeWorker(), and G4RTWorkerInitialization::WorkerRunStart().
const G4UserWorkerInitialization* G4RunManager::GetUserWorkerInitialization () const inline
Definition at line 367 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 367 of file G4RunManager.hh
References userWorkerInitialization.
Referenced by tbbTask::execute(), G4WorkerRunManager::RunInitialization(), G4WorkerRunManager::RunTermination(), G4MTRunManagerKernel::StartThread(), and G4TheMTRayTracer::StoreUserActions().
const G4UserWorkerThreadInitialization* G4RunManager::GetUserWorkerThreadInitialization () const inline
Definition at line 369 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 369 of file G4RunManager.hh
References userWorkerThreadInitialization.
Referenced by tbbTask::execute(), G4WorkerRunManager::SetupDefaultRNGEngine(), and G4MTRunManagerKernel::StartThread().
G4int G4RunManager::GetVerboseLevel () const inline
Definition at line 500 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 500 of file G4RunManager.hh
References verboseLevel.
Referenced by export_G4RunManager(), G4RunMessenger::GetCurrentValue(), and message().
const G4String& G4RunManager::GetVersionString () const inline
Definition at line 392 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 392 of file G4RunManager.hh
References G4RunManagerKernel::GetVersionString(), and kernel.
Referenced by export_G4RunManager().
G4bool G4RunManager::IfGeometryHasBeenDestroyed () static
Definition at line 72 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4RunManager.cc
void G4RunManager::Initialize (void) virtual
Reimplemented in G4MTRunManager.
Definition at line 575 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 575 of file G4RunManager.cc
References G4cerr, G4endl, G4State_Idle, G4State_Init, G4State_PreInit, geometryInitialized, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), initializedAtLeastOnce, InitializeGeometry(), InitializePhysics(), physicsInitialized, and G4StateManager::SetNewState().
Referenced by ConfirmBeamOnCondition(), export_G4RunManager(), G4MTRunManager::Initialize(), PHG4Reco::InitRun(), main(), G4RunMessenger::SetNewValue(), and G4MTRunManagerKernel::StartThread().
void G4RunManager::InitializeEventLoop (G4int n_event, const char * macroFile = 0, G4int n_select = -1) virtual
Reimplemented in G4MTRunManager.
Definition at line 390 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 390 of file G4RunManager.cc
References msgText, n_select_msg, selectMacro, G4Timer::Start(), timer, and verboseLevel.
Referenced by G4WorkerRunManager::DoEventLoop(), and DoEventLoop().
void G4RunManager::InitializeGeometry () virtual
Reimplemented in G4WorkerRunManager.
Definition at line 594 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 594 of file G4RunManager.cc
References G4VUserDetectorConstruction::Construct(), G4VUserDetectorConstruction::ConstructParallelGeometries(), G4VUserDetectorConstruction::ConstructParallelSD(), G4VUserDetectorConstruction::ConstructSDandField(), G4RunManagerKernel::DefineWorldVolume(), FatalException, G4cout, G4endl, G4Exception(), G4State_Idle, G4State_Init, G4State_PreInit, geometryDirectlyUpdated, G4VVisManager::GeometryHasChanged(), geometryInitialized, G4VVisManager::GetConcreteInstance(), G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4Threading::IsMasterThread(), kernel, nParallelWorlds, G4StateManager::SetNewState(), G4RunManagerKernel::SetNumberOfParallelWorld(), userDetector, and verboseLevel.
Referenced by Initialize().
void G4RunManager::InitializePhysics () virtual
Definition at line 629 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 629 of file G4RunManager.cc
References FatalException, G4Exception(), G4State_Idle, G4State_Init, G4State_PreInit, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4RunManagerKernel::InitializePhysics(), kernel, physicsInitialized, physicsList, and G4StateManager::SetNewState().
Referenced by Initialize().
G4RunManager& G4RunManager::operator= (const G4RunManager &) inline private
Definition at line 586 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 586 of file G4RunManager.hh
void G4RunManager::PhysicsHasBeenModified () inline
Definition at line 471 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 471 of file G4RunManager.hh
References kernel, and G4RunManagerKernel::PhysicsHasBeenModified().
Referenced by export_G4RunManager(), DetectorConstruction::SetAbsMaterial(), DetectorConstruction::SetAbsorberMaterial(), F03DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorMaterial(), DetectorConstruction::SetContainerMaterial(), DetectorConstruction::SetContainMaterial(), DetectorConstruction::SetCytoMaterial(), F04DetectorConstruction::SetDegraderMaterial(), DetectorConstruction::SetDetectorMaterial(), DetectorConstruction::SetEcalMaterial(), DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGasMaterial(), HistoManager::SetIonPhysics(), DetectorConstruction::SetMaterial(), ExGflashDetectorConstruction::SetMaterial(), XrayFluoPhysicsListMessenger::SetNewValue(), DMXDetectorMessenger::SetNewValue(), G4RunMessenger::SetNewValue(), DetectorConstruction::SetNuclMaterial(), ElectronBenchmarkDetector::SetPrimFoilMaterial(), DetectorConstruction::SetTankMaterial(), DetectorConstruction::SetTarget1Material(), DetectorConstruction::SetTarget2Material(), DetectorConstruction::SetTargetMaterial(), F04DetectorConstruction::SetTargetMaterial(), DetectorConstruction::SetWorldMaterial(), F03DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldMaterial(), F04DetectorConstruction::SetWorldMaterial(), and GammaRayTelDetectorConstruction::UpdateGeometry().
void G4RunManager::ProcessOneEvent (G4int i_event) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 410 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 410 of file G4RunManager.cc
References AnalyzeEvent(), G4UImanager::ApplyCommand(), currentEvent, eventManager, GenerateEvent(), G4UImanager::GetUIpointer(), msgText, n_select_msg, G4EventManager::ProcessOneEvent(), TIMEMORY_AUTO_TIMER, and UpdateScoring().
Referenced by DoEventLoop().
void G4RunManager::ReinitializeGeometry (G4bool destroyFirst = false, G4bool prop = true)
Definition at line 986 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 986 of file G4RunManager.cc
References G4UImanager::ApplyCommand(), G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4AssemblyStore::Clean(), G4SolidStore::Clean(), G4TransportationManager::ClearParallelWorlds(), fGeometryHasBeenDestroyed, G4cout, G4endl, G4RunManagerKernel::GeometryHasBeenModified(), G4VVisManager::GeometryHasChanged(), geometryInitialized, G4VVisManager::GetConcreteInstance(), G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4AssemblyStore::GetInstance(), G4SolidStore::GetInstance(), G4RegionStore::GetInstance(), G4GeometryManager::GetInstance(), G4TransportationManager::GetTransportationManager(), G4UImanager::GetUIpointer(), G4Threading::IsMasterThread(), kernel, G4GeometryManager::OpenGeometry(), and verboseLevel.
Referenced by DetectorConstruction::BuildBoundingVolume(), DetectorConstruction::DrawAtoms_(), DetectorConstruction::DrawAtomsWithBounding_(), DetectorConstruction::DrawNucleotides_(), DetectorConstruction::DrawNucleotidesWithBounding_(), DetectorConstruction::DrawResidues_(), DetectorConstruction::DrawResiduesWithBounding_(), DetectorConstruction::LoadPDBfile(), F03DetectorConstruction::SetAbsorberRadius(), F01DetectorConstruction::SetAbsorberRadius(), F02DetectorConstruction::SetAbsorberRadius(), DetectorConstruction::SetAbsorberThickness(), F03DetectorConstruction::SetAbsorberThickness(), F01DetectorConstruction::SetAbsorberThickness(), F02DetectorConstruction::SetAbsorberThickness(), F03DetectorConstruction::SetAbsorberZpos(), F01DetectorConstruction::SetAbsorberZpos(), F02DetectorConstruction::SetAbsorberZpos(), DetectorConstruction::SetAbsorLength(), DetectorConstruction::SetAbsorRadius(), DetectorConstruction::SetAbsorSizeYZ(), DetectorConstruction::SetAbsorThickness(), WLSDetectorConstruction::SetBarBase(), WLSDetectorConstruction::SetBarLength(), DetectorConstruction::SetCalorSizeYZ(), F04DetectorConstruction::SetCaptureMgntB1(), F04DetectorConstruction::SetCaptureMgntB2(), F04DetectorConstruction::SetCaptureMgntLength(), F04DetectorConstruction::SetCaptureMgntRadius(), WLSDetectorConstruction::SetClad1Radius(), WLSDetectorConstruction::SetClad2Radius(), WLSDetectorConstruction::SetCoatingRadius(), WLSDetectorConstruction::SetCoatingThickness(), DetectorConstruction::SetCoef(), DetectorConstruction::SetContainThickness(), DetectorConstruction::SetCytoThickness(), F04DetectorConstruction::SetDegraderPos(), F04DetectorConstruction::SetDegraderRadius(), F04DetectorConstruction::SetDegraderThickness(), DetectorConstruction::SetDetectorLength(), DetectorConstruction::SetDetectorThickness(), LXeDetectorConstruction::SetDimensions(), DetectorConstruction::SetG1(), DetectorConstruction::SetG2(), DetectorConstruction::SetG3(), DetectorConstruction::SetG4(), WLSDetectorConstruction::SetGap(), DetectorConstruction::SetGapThickness(), DetectorConstruction::SetGrid(), WLSDetectorConstruction::SetHoleRadius(), LXeDetectorConstruction::SetHousingReflectivity(), LXeDetectorConstruction::SetHousingThickness(), LXeDetectorConstruction::SetMainVolumeOn(), WLSDetectorConstruction::SetMirror(), WLSDetectorConstruction::SetMirrorPolish(), WLSDetectorConstruction::SetMirrorReflectivity(), DetectorConstruction::SetModel(), DetectorConstruction::SetNbOfAbsor(), DetectorConstruction::SetNbOfDivisions(), DetectorConstruction::SetNbOfLayers(), LXeDetectorMessenger::SetNewValue(), G4GDMLMessenger::SetNewValue(), G4RunMessenger::SetNewValue(), LXeDetectorConstruction::SetNFibers(), DetectorConstruction::SetNuclRadius(), WLSDetectorConstruction::SetNumberOfCladding(), LXeDetectorConstruction::SetNX(), LXeDetectorConstruction::SetNY(), LXeDetectorConstruction::SetNZ(), WLSDetectorConstruction::SetPhotonDetAlignment(), WLSDetectorConstruction::SetPhotonDetGeometry(), WLSDetectorConstruction::SetPhotonDetHalfLength(), WLSDetectorConstruction::SetPhotonDetPolish(), WLSDetectorConstruction::SetPhotonDetReflectivity(), LXeDetectorConstruction::SetPMTRadius(), DetectorConstruction::SetProfile(), UltraDetectorConstruction::SetReflectionType(), LXeDetectorConstruction::SetSphereOn(), WLSDetectorConstruction::SetSurfaceRoughness(), F04DetectorConstruction::SetTargetAngle(), F04DetectorConstruction::SetTargetPos(), F04DetectorConstruction::SetTargetRadius(), F04DetectorConstruction::SetTargetThickness(), F04DetectorConstruction::SetTransferMgntB(), F04DetectorConstruction::SetTransferMgntLength(), F04DetectorConstruction::SetTransferMgntPos(), F04DetectorConstruction::SetTransferMgntRadius(), WLSDetectorConstruction::SetWLSLength(), WLSDetectorConstruction::SetWLSRadius(), LXeDetectorConstruction::SetWLSSlabOn(), F03DetectorConstruction::SetWorldSizeR(), F01DetectorConstruction::SetWorldSizeR(), F02DetectorConstruction::SetWorldSizeR(), F04DetectorConstruction::SetWorldSizeR(), F03DetectorConstruction::SetWorldSizeZ(), F01DetectorConstruction::SetWorldSizeZ(), F02DetectorConstruction::SetWorldSizeZ(), F04DetectorConstruction::SetWorldSizeZ(), WLSDetectorConstruction::SetXYRatio(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), and GammaRayTelDetectorConstruction::UpdateGeometry().
void G4RunManager::ReOptimize (G4LogicalVolume * pLog)
Definition at line 885 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 885 of file G4RunManager.cc
References G4cout, G4endl, G4LogicalVolume::GetName(), G4Timer::GetSystemElapsed(), G4Timer::GetUserElapsed(), G4LogicalVolume::GetVoxelHeader(), G4LogicalVolume::SetVoxelHeader(), G4Timer::Start(), G4Timer::Stop(), and verboseLevel.
Referenced by ReOptimizeMotherOf().
void G4RunManager::ReOptimizeMotherOf (G4VPhysicalVolume * pPhys)
Definition at line 879 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 879 of file G4RunManager.cc
References G4VPhysicalVolume::GetMotherLogical(), and ReOptimize().
void G4RunManager::RestoreRandomNumberStatus (const G4String & fileN) virtual
Definition at line 756 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 756 of file G4RunManager.cc
References G4cout, G4endl, G4String::index(), randomNumberStatusDir, and verboseLevel.
Referenced by export_G4RunManager(), and G4RunMessenger::SetNewValue().
virtual void G4RunManager::RestoreRndmEachEvent (G4bool) inline virtual
Reimplemented in G4WorkerRunManager.
Definition at line 596 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 596 of file G4RunManager.hh
Referenced by G4RunMessenger::SetNewValue().
void G4RunManager::rndmSaveThisEvent () virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 718 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 718 of file G4RunManager.cc
References G4UImanager::ApplyCommand(), currentEvent, currentRun, G4cerr, G4cout, G4endl, G4Event::GetEventID(), G4Run::GetRunID(), G4UImanager::GetUIpointer(), randomNumberStatusDir, storeRandomNumberStatus, and verboseLevel.
Referenced by LXeEventAction::EndOfEventAction(), export_G4RunManager(), and G4RunMessenger::SetNewValue().
void G4RunManager::rndmSaveThisRun () virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 691 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 691 of file G4RunManager.cc
References G4UImanager::ApplyCommand(), currentRun, G4cerr, G4cout, G4endl, G4Run::GetRunID(), G4UImanager::GetUIpointer(), randomNumberStatusDir, storeRandomNumberStatus, and verboseLevel.
Referenced by export_G4RunManager(), and G4RunMessenger::SetNewValue().
void G4RunManager::RunInitialization () virtual
Reimplemented in G4WorkerRunManager.
Definition at line 314 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 314 of file G4RunManager.cc
References G4UserRunAction::BeginOfRunAction(), G4VScoreNtupleWriter::Book(), CleanUpPreviousEvents(), currentRun, DCtable, fakeRun, fGeometryHasBeenDestroyed, G4cout, G4endl, G4UserRunAction::GenerateRun(), G4SDManager::GetHCtable(), G4ParallelWorldProcessStore::GetInstance(), G4Run::GetRunID(), G4SDManager::GetSDMpointerIfExist(), G4VScoreNtupleWriter::Instance(), isScoreNtupleWriter, kernel, n_perviousEventsToBeStored, numberOfEventProcessed, numberOfEventToBeProcessed, G4VScoreNtupleWriter::OpenFile(), G4SDManager::PrepareNewEvent(), previousEvents, printModulo, randomNumberStatusForThisRun, rngStatusEventsFlag, runAborted, runIDCounter, G4RunManagerKernel::RunInitialization(), G4Run::SetDCtable(), G4Run::SetHCtable(), G4Run::SetNumberOfEventToBeProcessed(), G4Run::SetRandomNumberStatus(), G4Run::SetRunID(), storeRandomNumberStatus, StoreRNGStatus(), TIMEMORY_AUTO_TIMER, G4ParallelWorldProcessStore::UpdateWorlds(), userRunAction, and verboseLevel.
Referenced by BeamOn().
void G4RunManager::RunTermination () virtual
Reimplemented in G4MTRunManager, G4WorkerRunManager, and SimpleTbbMasterRunManager.
Definition at line 495 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 495 of file G4RunManager.cc
References CleanUpUnnecessaryEvents(), currentRun, G4UserRunAction::EndOfRunAction(), fakeRun, G4VPersistencyManager::GetPersistencyManager(), G4VScoreNtupleWriter::Instance(), isScoreNtupleWriter, kernel, runIDCounter, G4RunManagerKernel::RunTermination(), G4VPersistencyManager::Store(), userRunAction, and G4VScoreNtupleWriter::Write().
Referenced by BeamOn(), G4WorkerRunManager::RunTermination(), and G4MTRunManager::RunTermination().
void G4RunManager::SetDCtable (G4DCtable * DCtbl) inline
Definition at line 566 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 566 of file G4RunManager.hh
References DCtable.
Referenced by G4DigiManager::AddNewModule().
void G4RunManager::SetGeometryToBeOptimized (G4bool vl) inline
Definition at line 507 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 507 of file G4RunManager.hh
References G4RunManagerKernel::GeometryHasBeenModified(), geometryToBeOptimized, kernel, and G4RunManagerKernel::SetGeometryToBeOptimized().
Referenced by G4RunMessenger::SetNewValue().
void G4RunManager::SetNumberOfAdditionalWaitingStacks (G4int iAdd) inline
Definition at line 385 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 385 of file G4RunManager.hh
References eventManager, and G4EventManager::SetNumberOfAdditionalWaitingStacks().
void G4RunManager::SetNumberOfEventsToBeProcessed (G4int val) inline
Definition at line 558 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 558 of file G4RunManager.hh
References numberOfEventToBeProcessed.
void G4RunManager::SetNumberOfEventsToBeStored (G4int val) inline
Definition at line 520 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 520 of file G4RunManager.hh
References n_perviousEventsToBeStored.
void G4RunManager::SetPrimaryTransformer (G4PrimaryTransformer * pt) inline
Definition at line 395 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 395 of file G4RunManager.hh
References kernel, and G4RunManagerKernel::SetPrimaryTransformer().
void G4RunManager::SetPrintProgress (G4int i) inline
Definition at line 504 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 504 of file G4RunManager.hh
References printModulo.
Referenced by B2RunAction::B2RunAction(), B4bRunAction::B4bRunAction(), B4RunAction::B4RunAction(), DicomRunAction::BeginOfRunAction(), TSRunAction::BeginOfRunAction(), ElectronRunAction::ElectronRunAction(), and G4RunMessenger::SetNewValue().
void G4RunManager::SetRandomNumberStore (G4bool flag) inline
Definition at line 411 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 411 of file G4RunManager.hh
References storeRandomNumberStatus.
Referenced by B3aRunAction::BeginOfRunAction(), B3bRunAction::BeginOfRunAction(), RE01RunAction::BeginOfRunAction(), B2RunAction::BeginOfRunAction(), F04RunAction::BeginOfRunAction(), STCyclotronRunAction::BeginOfRunAction(), B1RunAction::BeginOfRunAction(), DicomRunAction::BeginOfRunAction(), B1ConRunAction::BeginOfRunAction(), GammaKnifeRunAction::BeginOfRunAction(), FFRunAction::BeginOfRunAction(), WLSRunAction::BeginOfRunAction(), doiPETRunAction::BeginOfRunAction(), export_G4RunManager(), G4RunMessenger::SetNewValue(), and LXeDetectorConstruction::SetSaveThreshold().
void G4RunManager::SetRandomNumberStoreDir (const G4String & dir) inline
Definition at line 415 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 415 of file G4RunManager.hh
References dir, G4cerr, G4endl, G4Exception(), JustWarning, randomNumberStatusDir, and system().
Referenced by F04RunAction::BeginOfRunAction(), DicomRunAction::BeginOfRunAction(), export_G4RunManager(), and G4RunMessenger::SetNewValue().
void G4RunManager::SetRandomNumberStorePerEvent (G4bool flag) inline
Definition at line 447 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 447 of file G4RunManager.hh
References rngStatusEventsFlag.
Referenced by DicomRunAction::BeginOfRunAction(), and G4RunMessenger::SetNewValue().
void G4RunManager::SetRunIDCounter (G4int i) inline
Definition at line 550 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 550 of file G4RunManager.hh
References runIDCounter.
Referenced by export_G4RunManager(), G4MTRunManager::Initialize(), and CCalPrimaryGeneratorAction::SetRunNo().
void G4RunManager::SetUserAction (G4UserRunAction * userAction) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 937 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 937 of file G4RunManager.cc
References userRunAction.
Referenced by G4BlineTracer::ComputeBlines(), PHG4Reco::InitRun(), main(), PHG4Reco::setupInputEventNodeReader(), G4VUserActionInitialization::SetUserAction(), G4WorkerRunManager::SetUserAction(), G4MTRunManager::SetUserAction(), and CCalSensAssign::stackingAction().
void G4RunManager::SetUserAction (G4VUserPrimaryGeneratorAction * userAction) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 942 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 942 of file G4RunManager.cc
References userPrimaryGeneratorAction.
void G4RunManager::SetUserAction (G4UserEventAction * userAction) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 947 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 947 of file G4RunManager.cc
References eventManager, G4EventManager::SetUserAction(), and userEventAction.
void G4RunManager::SetUserAction (G4UserStackingAction * userAction) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 953 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 953 of file G4RunManager.cc
References eventManager, G4EventManager::SetUserAction(), and userStackingAction.
void G4RunManager::SetUserAction (G4UserTrackingAction * userAction) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 959 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 959 of file G4RunManager.cc
References eventManager, G4EventManager::SetUserAction(), and userTrackingAction.
void G4RunManager::SetUserAction (G4UserSteppingAction * userAction) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 965 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 965 of file G4RunManager.cc
References eventManager, G4EventManager::SetUserAction(), and userSteppingAction.
void G4RunManager::SetUserInitialization (G4VUserDetectorConstruction * userInit) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 910 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 910 of file G4RunManager.cc
References userDetector.
Referenced by PHG4Reco::Init(), PHG4Reco::InitRun(), main(), IORTGeometryController::registerGeometry(), XrayFluoSimulation::RunSimulation(), G4WorkerRunManager::SetUserInitialization(), and G4MTRunManager::SetUserInitialization().
void G4RunManager::SetUserInitialization (G4VUserPhysicsList * userInit) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 913 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 913 of file G4RunManager.cc
References kernel, physicsList, and G4RunManagerKernel::SetPhysics().
void G4RunManager::SetUserInitialization (G4VUserActionInitialization * userInit) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 931 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 931 of file G4RunManager.cc
References G4VUserActionInitialization::Build(), and userActionInitialization.
void G4RunManager::SetUserInitialization (G4UserWorkerInitialization * userInit) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 919 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 919 of file G4RunManager.cc
References FatalException, and G4Exception().
void G4RunManager::SetUserInitialization (G4UserWorkerThreadInitialization * userInit) virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 925 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 925 of file G4RunManager.cc
References FatalException, and G4Exception().
void G4RunManager::SetVerboseLevel (G4int vl) inline
Definition at line 497 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 497 of file G4RunManager.hh
References kernel, G4RunManagerKernel::SetVerboseLevel(), and verboseLevel.
Referenced by export_G4RunManager(), PHG4Reco::G4Verbosity(), message(), and G4RunMessenger::SetNewValue().
void G4RunManager::StackPreviousEvent (G4Event * anEvent) protected
Definition at line 560 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 560 of file G4RunManager.cc
References CleanUpUnnecessaryEvents(), currentRun, G4Event::GetNumberOfGrips(), n_perviousEventsToBeStored, previousEvents, G4Run::StoreEvent(), and G4Event::ToBeKept().
Referenced by CexmcRunManager::DoCommonEventLoop(), and TerminateOneEvent().
void G4RunManager::StoreRandomNumberStatusToG4Event (G4int vl) inline
Definition at line 398 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 398 of file G4RunManager.hh
References eventManager, G4EventManager::StoreRandomNumberStatusToG4Event(), and storeRandomNumberStatusToG4Event.
Referenced by G4RunMessenger::SetNewValue().
void G4RunManager::StoreRNGStatus (const G4String & filenamePrefix) protected virtual
Reimplemented in G4MTRunManager, and G4WorkerRunManager.
Definition at line 481 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 481 of file G4RunManager.cc
References randomNumberStatusDir, and TIMEMORY_AUTO_TIMER.
Referenced by GenerateEvent(), and RunInitialization().
void G4RunManager::TerminateEventLoop () virtual
Reimplemented in G4WorkerRunManager.
Definition at line 428 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 428 of file G4RunManager.cc
References fakeRun, fGeometryHasBeenDestroyed, G4cout, G4endl, numberOfEventProcessed, runAborted, G4Timer::Stop(), timer, and verboseLevel.
Referenced by DoEventLoop(), and G4MTRunManager::RunTermination().
void G4RunManager::TerminateOneEvent () virtual
Reimplemented in G4MTRunManager.
Definition at line 420 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 420 of file G4RunManager.cc
References currentEvent, numberOfEventProcessed, StackPreviousEvent(), and TIMEMORY_AUTO_TIMER.
Referenced by G4WorkerRunManager::DoEventLoop(), and DoEventLoop().
void G4RunManager::UpdateScoring () protected
Definition at line 850 of file G4RunManager.cc.
View newest version in sPHENIX GitHub at line 850 of file G4RunManager.cc
References G4ScoringManager::Accumulate(), currentEvent, G4VScoreNtupleWriter::Fill(), G4HCofThisEvent::GetCapacity(), G4Event::GetEventID(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4ScoringManager::GetNumberOfMesh(), G4ScoringManager::GetScoringManagerIfExist(), G4VScoreNtupleWriter::Instance(), isScoreNtupleWriter, and TIMEMORY_AUTO_TIMER.
Referenced by CexmcRunManager::DoCommonEventLoop(), G4WorkerRunManager::ProcessOneEvent(), and ProcessOneEvent().
Member Data Documentation
G4Event* G4RunManager::currentEvent protected
Definition at line 305 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 305 of file G4RunManager.hh
Referenced by AbortEvent(), AbortRun(), CexmcRunManager::DoCommonEventLoop(), GetCurrentEvent(), G4WorkerRunManager::ProcessOneEvent(), ProcessOneEvent(), G4WorkerRunManager::rndmSaveThisEvent(), rndmSaveThisEvent(), TerminateOneEvent(), and UpdateScoring().
G4Run* G4RunManager::currentRun protected
Definition at line 304 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 304 of file G4RunManager.hh
Referenced by AnalyzeEvent(), G4WorkerRunManager::GenerateEvent(), GenerateEvent(), GetCurrentRun(), GetNonConstCurrentRun(), G4WorkerRunManager::MergePartialResults(), G4MTRunManager::MergeRun(), G4WorkerRunManager::rndmSaveThisEvent(), rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), rndmSaveThisRun(), G4WorkerRunManager::RunInitialization(), RunInitialization(), RunTermination(), StackPreviousEvent(), and ~G4RunManager().
G4VPhysicalVolume* G4RunManager::currentWorld protected
Definition at line 318 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 318 of file G4RunManager.hh
G4DCtable* G4RunManager::DCtable protected
Definition at line 302 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 302 of file G4RunManager.hh
Referenced by G4WorkerRunManager::RunInitialization(), RunInitialization(), and SetDCtable().
G4EventManager* G4RunManager::eventManager protected
Definition at line 274 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 274 of file G4RunManager.hh
Referenced by AbortEvent(), AbortRun(), CexmcRunManager::DoCommonEventLoop(), G4RunManager(), G4WorkerRunManager::ProcessOneEvent(), ProcessOneEvent(), SetNumberOfAdditionalWaitingStacks(), SetUserAction(), and StoreRandomNumberStatusToG4Event().
G4bool G4RunManager::fakeRun protected
Definition at line 326 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 326 of file G4RunManager.hh
Referenced by BeamOn(), G4MTRunManager::InitializeEventLoop(), G4WorkerRunManager::RunInitialization(), RunInitialization(), G4WorkerRunManager::RunTermination(), RunTermination(), G4WorkerRunManager::TerminateEventLoop(), and TerminateEventLoop().
G4bool G4RunManager::fGeometryHasBeenDestroyed = false static protected
Definition at line 590 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 590 of file G4RunManager.hh
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), ConstructScoringWorlds(), G4WorkerRunManager::InitializeGeometry(), ReinitializeGeometry(), G4WorkerRunManager::RunInitialization(), RunInitialization(), and TerminateEventLoop().
G4ThreadLocal G4RunManager * G4RunManager::fRunManager = 0 static private
Definition at line 147 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 147 of file G4RunManager.hh
Referenced by G4RunManager(), and ~G4RunManager().
G4bool G4RunManager::geometryDirectlyUpdated protected
Definition at line 598 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 598 of file G4RunManager.hh
Referenced by GeometryDirectlyUpdated(), and InitializeGeometry().
G4bool G4RunManager::geometryInitialized protected
Definition at line 292 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 292 of file G4RunManager.hh
Referenced by ConfirmBeamOnCondition(), Initialize(), G4WorkerRunManager::InitializeGeometry(), InitializeGeometry(), and ReinitializeGeometry().
G4bool G4RunManager::geometryToBeOptimized protected
Definition at line 296 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 296 of file G4RunManager.hh
Referenced by GetGeometryToBeOptimized(), and SetGeometryToBeOptimized().
G4bool G4RunManager::initializedAtLeastOnce protected
Definition at line 295 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 295 of file G4RunManager.hh
Referenced by ConfirmBeamOnCondition(), and Initialize().
G4bool G4RunManager::isScoreNtupleWriter protected
Definition at line 327 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 327 of file G4RunManager.hh
Referenced by G4WorkerRunManager::RunInitialization(), RunInitialization(), RunTermination(), and UpdateScoring().
G4RunManagerKernel* G4RunManager::kernel protected
Definition at line 273 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 273 of file G4RunManager.hh
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), DefineWorldVolume(), DumpRegion(), G4MTRunManager::G4MTRunManager(), G4RunManager(), GeometryHasBeenModified(), G4MTRunManager::GetMasterRunManagerKernel(), GetVersionString(), G4WorkerRunManager::GetWorkerRunManagerKernel(), G4WorkerRunManager::InitializeGeometry(), InitializeGeometry(), InitializePhysics(), PhysicsHasBeenModified(), ReinitializeGeometry(), G4WorkerRunManager::RunInitialization(), RunInitialization(), RunTermination(), SetGeometryToBeOptimized(), SetPrimaryTransformer(), SetUserInitialization(), SetVerboseLevel(), and ~G4RunManager().
G4String G4RunManager::msgText protected
Definition at line 322 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 322 of file G4RunManager.hh
Referenced by G4MTRunManager::InitializeEventLoop(), InitializeEventLoop(), G4WorkerRunManager::ProcessOneEvent(), and ProcessOneEvent().
G4int G4RunManager::n_perviousEventsToBeStored protected
Definition at line 307 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 307 of file G4RunManager.hh
Referenced by GetPreviousEvent(), G4WorkerRunManager::RunInitialization(), RunInitialization(), SetNumberOfEventsToBeStored(), and StackPreviousEvent().
G4int G4RunManager::n_select_msg protected
Definition at line 323 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 323 of file G4RunManager.hh
Referenced by GetNumberOfSelectEvents(), G4MTRunManager::InitializeEventLoop(), InitializeEventLoop(), G4WorkerRunManager::ProcessOneEvent(), and ProcessOneEvent().
G4int G4RunManager::nParallelWorlds protected
Definition at line 320 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 320 of file G4RunManager.hh
Referenced by GetNumberOfParallelWorld(), and InitializeGeometry().
G4int G4RunManager::numberOfEventProcessed protected
Definition at line 324 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 324 of file G4RunManager.hh
Referenced by BeamOn(), G4MTRunManager::InitializeEventLoop(), G4WorkerRunManager::RunInitialization(), RunInitialization(), G4MTRunManager::SetUpAnEvent(), G4MTRunManager::SetUpNEvents(), G4WorkerRunManager::TerminateEventLoop(), TerminateEventLoop(), and TerminateOneEvent().
G4int G4RunManager::numberOfEventToBeProcessed protected
Definition at line 308 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 308 of file G4RunManager.hh
Referenced by BeamOn(), GetNumberOfEventsToBeProcessed(), G4WorkerRunManager::RunInitialization(), RunInitialization(), and SetNumberOfEventsToBeProcessed().
G4bool G4RunManager::physicsInitialized protected
Definition at line 293 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 293 of file G4RunManager.hh
Referenced by ConfirmBeamOnCondition(), Initialize(), and InitializePhysics().
G4VUserPhysicsList* G4RunManager::physicsList protected
Definition at line 277 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 277 of file G4RunManager.hh
Referenced by DeleteUserInitializations(), GetUserPhysicsList(), InitializePhysics(), SetUserInitialization(), and G4WorkerRunManager::~G4WorkerRunManager().
std::list<G4Event*>* G4RunManager::previousEvents protected
Definition at line 306 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 306 of file G4RunManager.hh
Referenced by CleanUpPreviousEvents(), CleanUpUnnecessaryEvents(), G4RunManager(), GetPreviousEvent(), G4WorkerRunManager::RunInitialization(), RunInitialization(), StackPreviousEvent(), and ~G4RunManager().
G4int G4RunManager::printModulo protected
Definition at line 300 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 300 of file G4RunManager.hh
Referenced by G4WorkerRunManager::GenerateEvent(), GenerateEvent(), GetPrintProgress(), G4WorkerRunManager::RunInitialization(), RunInitialization(), and SetPrintProgress().
G4String G4RunManager::randomNumberStatusDir protected
Definition at line 312 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 312 of file G4RunManager.hh
Referenced by G4RunManager(), GetRandomNumberStoreDir(), RestoreRandomNumberStatus(), G4WorkerRunManager::rndmSaveThisEvent(), rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), rndmSaveThisRun(), SetRandomNumberStoreDir(), G4WorkerRunManager::StoreRNGStatus(), G4MTRunManager::StoreRNGStatus(), and StoreRNGStatus().
G4String G4RunManager::randomNumberStatusForThisEvent protected
Definition at line 314 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 314 of file G4RunManager.hh
Referenced by G4RunManager(), G4WorkerRunManager::GenerateEvent(), GenerateEvent(), and GetRandomNumberStatusForThisEvent().
G4String G4RunManager::randomNumberStatusForThisRun protected
Definition at line 313 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 313 of file G4RunManager.hh
Referenced by G4RunManager(), GetRandomNumberStatusForThisRun(), G4WorkerRunManager::RunInitialization(), and RunInitialization().
G4bool G4RunManager::rngStatusEventsFlag protected
Definition at line 315 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 315 of file G4RunManager.hh
Referenced by G4WorkerRunManager::GenerateEvent(), GenerateEvent(), GetRandomNumberStorePerEvent(), G4WorkerRunManager::RunInitialization(), RunInitialization(), and SetRandomNumberStorePerEvent().
G4bool G4RunManager::runAborted protected
Definition at line 294 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 294 of file G4RunManager.hh
Referenced by AbortRun(), G4MTRunManager::AbortRun(), CexmcRunManager::DoCommonEventLoop(), G4WorkerRunManager::DoEventLoop(), CexmcRunManager::DoEventLoop(), DoEventLoop(), G4WorkerRunManager::RunInitialization(), RunInitialization(), G4MTRunManager::SetUpNEvents(), G4WorkerRunManager::TerminateEventLoop(), and TerminateEventLoop().
G4int G4RunManager::runIDCounter protected
Definition at line 298 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 298 of file G4RunManager.hh
Referenced by G4WorkerRunManager::RunInitialization(), RunInitialization(), RunTermination(), and SetRunIDCounter().
RMType G4RunManager::runManagerType protected
Definition at line 574 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 574 of file G4RunManager.hh
Referenced by DoEventLoop(), G4RunManager(), and GetRunManagerType().
G4RunMessenger* G4RunManager::runMessenger private
Definition at line 289 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 289 of file G4RunManager.hh
Referenced by G4RunManager(), and ~G4RunManager().
G4String G4RunManager::selectMacro protected
Definition at line 325 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 325 of file G4RunManager.hh
Referenced by GetSelectMacro(), G4MTRunManager::InitializeEventLoop(), and InitializeEventLoop().
G4bool G4RunManager::storeRandomNumberStatus protected
Definition at line 310 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 310 of file G4RunManager.hh
Referenced by G4WorkerRunManager::GenerateEvent(), GenerateEvent(), GetRandomNumberStore(), G4WorkerRunManager::rndmSaveThisEvent(), rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), rndmSaveThisRun(), G4WorkerRunManager::RunInitialization(), RunInitialization(), and SetRandomNumberStore().
G4int G4RunManager::storeRandomNumberStatusToG4Event protected
Definition at line 311 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 311 of file G4RunManager.hh
Referenced by G4WorkerRunManager::GenerateEvent(), GenerateEvent(), GetFlagRandomNumberStatusToG4Event(), GetRandomNumberStatusForThisEvent(), and StoreRandomNumberStatusToG4Event().
G4Timer* G4RunManager::timer protected
Definition at line 301 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 301 of file G4RunManager.hh
Referenced by CexmcRunManager::DoEventLoop(), G4RunManager(), G4MTRunManager::InitializeEventLoop(), InitializeEventLoop(), G4WorkerRunManager::TerminateEventLoop(), TerminateEventLoop(), and ~G4RunManager().
G4VUserActionInitialization* G4RunManager::userActionInitialization protected
Definition at line 278 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 278 of file G4RunManager.hh
Referenced by DeleteUserInitializations(), GetNonConstUserActionInitialization(), GetUserActionInitialization(), G4MTRunManager::SetUserInitialization(), SetUserInitialization(), and G4WorkerRunManager::~G4WorkerRunManager().
G4VUserDetectorConstruction* G4RunManager::userDetector protected
Definition at line 276 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 276 of file G4RunManager.hh
Referenced by DeleteUserInitializations(), GetUserDetectorConstruction(), G4WorkerRunManager::InitializeGeometry(), InitializeGeometry(), CexmcRunManager::RegisterScenePrimitives(), SetUserInitialization(), and G4WorkerRunManager::~G4WorkerRunManager().
G4UserEventAction* G4RunManager::userEventAction protected
Definition at line 283 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 283 of file G4RunManager.hh
Referenced by CexmcRunManager::BeamParticleChangeHook(), GetUserEventAction(), and SetUserAction().
G4VUserPrimaryGeneratorAction* G4RunManager::userPrimaryGeneratorAction protected
Definition at line 282 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 282 of file G4RunManager.hh
Referenced by G4WorkerRunManager::DoEventLoop(), G4WorkerRunManager::GenerateEvent(), GenerateEvent(), GetUserPrimaryGeneratorAction(), SetUserAction(), and ~G4RunManager().
G4UserRunAction* G4RunManager::userRunAction protected
Definition at line 281 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 281 of file G4RunManager.hh
Referenced by GetUserRunAction(), G4WorkerRunManager::RunInitialization(), RunInitialization(), RunTermination(), SetUserAction(), and ~G4RunManager().
G4UserStackingAction* G4RunManager::userStackingAction protected
Definition at line 284 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 284 of file G4RunManager.hh
Referenced by GetUserStackingAction(), and SetUserAction().
G4UserSteppingAction* G4RunManager::userSteppingAction protected
Definition at line 286 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 286 of file G4RunManager.hh
Referenced by GetUserSteppingAction(), and SetUserAction().
G4UserTrackingAction* G4RunManager::userTrackingAction protected
Definition at line 285 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 285 of file G4RunManager.hh
Referenced by GetUserTrackingAction(), and SetUserAction().
G4UserWorkerInitialization* G4RunManager::userWorkerInitialization protected
Definition at line 279 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 279 of file G4RunManager.hh
Referenced by DeleteUserInitializations(), GetUserWorkerInitialization(), G4MTRunManager::SetUserInitialization(), and G4WorkerRunManager::~G4WorkerRunManager().
G4UserWorkerThreadInitialization* G4RunManager::userWorkerThreadInitialization protected
Definition at line 280 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 280 of file G4RunManager.hh
Referenced by G4MTRunManager::CreateAndStartWorkers(), DeleteUserInitializations(), GetUserWorkerThreadInitialization(), G4MTRunManager::InitializeEventLoop(), G4MTRunManager::SetUserInitialization(), G4MTRunManager::TerminateWorkers(), and G4WorkerRunManager::~G4WorkerRunManager().
G4int G4RunManager::verboseLevel protected
Definition at line 299 of file G4RunManager.hh.
View newest version in sPHENIX GitHub at line 299 of file G4RunManager.hh
Referenced by ConfirmBeamOnCondition(), DeleteUserInitializations(), CexmcRunManager::DoEventLoop(), GetVerboseLevel(), G4MTRunManager::InitializeEventLoop(), InitializeEventLoop(), InitializeGeometry(), ReinitializeGeometry(), ReOptimize(), RestoreRandomNumberStatus(), G4WorkerRunManager::rndmSaveThisEvent(), rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), rndmSaveThisRun(), G4WorkerRunManager::RunInitialization(), RunInitialization(), SetVerboseLevel(), G4WorkerRunManager::TerminateEventLoop(), TerminateEventLoop(), ~G4RunManager(), and G4WorkerRunManager::~G4WorkerRunManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4RunManager.hh
geant4/tree/geant4-10.6-release/source/run/src/G4RunManager.cc