ECCE @ EIC Software: CLHEP::RandStudentT Class Reference
CLHEP::RandStudentT Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandStudentT.h>
Public Member Functions
RandStudentT (HepRandomEngine &anEngine, double a=1.0)
RandStudentT (HepRandomEngine *anEngine, double a=1.0)
virtual ~RandStudentT ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
double fire ()
double fire (double a)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double a)
double operator() ()
double operator() (double a)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double a)
static void shootArray (const int size, double *vect, double a=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double a)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double a=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double defaultA
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 41 of file RandStudentT.h.
View newest version in sPHENIX GitHub at line 41 of file RandStudentT.h
Constructor & Destructor Documentation
CLHEP::RandStudentT::RandStudentT (HepRandomEngine & anEngine, double a = 1.0) inline
CLHEP::RandStudentT::RandStudentT (HepRandomEngine * anEngine, double a = 1.0) inline
CLHEP::RandStudentT::~RandStudentT () virtual
Definition at line 29 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 29 of file RandStudentT.cc
Member Function Documentation
static std::string CLHEP::RandStudentT::distributionName () inline static
Definition at line 99 of file RandStudentT.h.
View newest version in sPHENIX GitHub at line 99 of file RandStudentT.h
HepRandomEngine & CLHEP::RandStudentT::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 27 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 27 of file RandStudentT.cc
References localEngine.
double CLHEP::RandStudentT::fire () inline
Referenced by fireArray(), and operator()().
double CLHEP::RandStudentT::fire (double a)
Definition at line 97 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 97 of file RandStudentT.cc
References localEngine, Acts::UnitConstants::u, v, and w.
void CLHEP::RandStudentT::fireArray (const int size, double * vect)
Definition at line 111 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 111 of file RandStudentT.cc
References defaultA, fire(), and v.
void CLHEP::RandStudentT::fireArray (const int size, double * vect, double a)
Definition at line 117 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 117 of file RandStudentT.cc
References fire(), and v.
std::istream & CLHEP::RandStudentT::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 149 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 149 of file RandStudentT.cc
References defaultA, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandStudentT::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 26 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 26 of file RandStudentT.cc
Referenced by get(), and put().
double CLHEP::RandStudentT::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 33 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 33 of file RandStudentT.cc
References defaultA, and fire().
double CLHEP::RandStudentT::operator() (double a)
Definition at line 37 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 37 of file RandStudentT.cc
References fire().
std::ostream & CLHEP::RandStudentT::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 138 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 138 of file RandStudentT.cc
References defaultA, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
static double CLHEP::RandStudentT::shoot () inline static
Referenced by shootArray().
double CLHEP::RandStudentT::shoot (double a) static
Definition at line 41 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 41 of file RandStudentT.cc
References DBL_MAX, CLHEP::HepRandomEngine::flat(), CLHEP::HepRandom::getTheEngine(), Acts::UnitConstants::u, v, and w.
static double CLHEP::RandStudentT::shoot (HepRandomEngine * anEngine) inline static
double CLHEP::RandStudentT::shoot (HepRandomEngine * anEngine, double a) static
Definition at line 124 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 124 of file RandStudentT.cc
References CLHEP::HepRandomEngine::flat(), Acts::UnitConstants::u, v, and w.
void CLHEP::RandStudentT::shootArray (const int size, double * vect, double a = 1.0) static
Definition at line 82 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 82 of file RandStudentT.cc
References shoot(), and v.
void CLHEP::RandStudentT::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double a = 1.0) static
Definition at line 89 of file RandStudentT.cc.
View newest version in sPHENIX GitHub at line 89 of file RandStudentT.cc
References shoot(), and v.
Member Data Documentation
double CLHEP::RandStudentT::defaultA private
Definition at line 106 of file RandStudentT.h.
View newest version in sPHENIX GitHub at line 106 of file RandStudentT.h
Referenced by fireArray(), get(), operator()(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandStudentT::localEngine private
Definition at line 105 of file RandStudentT.h.
View newest version in sPHENIX GitHub at line 105 of file RandStudentT.h
Referenced by engine(), and fire().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandStudentT.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandStudentT.cc