ECCE @ EIC Software: G4GDMLRead Class Reference
G4GDMLRead Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLRead.hh>
Public Member Functions
virtual void DefineRead (const xercesc::DOMElement *const)=0
virtual void MaterialsRead (const xercesc::DOMElement *const)=0
virtual void SetupRead (const xercesc::DOMElement *const)=0
virtual void SolidsRead (const xercesc::DOMElement *const)=0
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)=0
virtual void Volume_contentRead (const xercesc::DOMElement *const)=0
virtual void StructureRead (const xercesc::DOMElement *const)=0
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
virtual G4LogicalVolume * GetVolume (const G4String &) const =0
virtual G4String GetSetup (const G4String &)=0
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Protected Attributes
G4GDMLEvaluator eval
G4bool validate
G4bool check
G4bool dostrip
Private Attributes
G4int inLoop
G4int loopCount
G4GDMLAuxListType auxGlobalList
Detailed Description
Definition at line 88 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 88 of file G4GDMLRead.hh
Constructor & Destructor Documentation
G4GDMLRead::G4GDMLRead () protected
Definition at line 44 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 44 of file G4GDMLRead.cc
References G4UnitDefinition::GetUnitsTable().
G4GDMLRead::~G4GDMLRead () protected virtual
Definition at line 51 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 51 of file G4GDMLRead.cc
Member Function Documentation
G4GDMLAuxStructType G4GDMLRead::AuxiliaryRead (const xercesc::DOMElement *const auxElem) protected
Definition at line 257 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 257 of file G4GDMLRead.cc
References G4GDMLAuxStructType::auxList, FatalException, G4Exception(), Transcode(), G4GDMLAuxStructType::type, G4GDMLAuxStructType::unit, and G4GDMLAuxStructType::value.
Referenced by UserinfoRead(), G03ColorReader::VolumeRead(), and G4GDMLReadStructure::VolumeRead().
virtual void G4GDMLRead::DefineRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadDefine.
Referenced by Read().
void G4GDMLRead::ExtensionRead (const xercesc::DOMElement * const) virtual
Reimplemented in G03ColorReader.
Definition at line 350 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 350 of file G4GDMLRead.cc
References G4Exception(), and JustWarning.
Referenced by Read().
G4String G4GDMLRead::GenerateName (const G4String & name, G4bool strip = false) protected
Definition at line 68 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 68 of file G4GDMLRead.cc
References eval, inLoop, G4GDMLEvaluator::SolveBrackets(), and StripName().
Referenced by G4GDMLReadStructure::AssemblyRead(), G4GDMLReadSolids::BooleanRead(), G4GDMLReadStructure::BorderSurfaceRead(), G4GDMLReadSolids::BoxRead(), G03ColorReader::ColorRead(), G4GDMLReadSolids::ConeRead(), G4GDMLReadSolids::CutTubeRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadMaterials::ElementRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), G4GDMLReadStructure::FileRead(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4GDMLReadStructure::GetWorldVolume(), G4GDMLReadSolids::HypeRead(), G4GDMLReadMaterials::IsotopeRead(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadDefine::MatrixRead(), G4GDMLReadMaterials::MixtureRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadSolids::MultiUnionRead(), G4GDMLReadSolids::OpticalSurfaceRead(), G4GDMLReadSolids::OrbRead(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLReadParamvol::ParametersRead(), G4GDMLReadParamvol::ParamvolRead(), G4GDMLReadSolids::ParaRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLReadDefine::PositionRead(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), G4GDMLReadSolids::QuadrangularRead(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadStructure::ReplicaRead(), G4GDMLReadStructure::ReplicavolRead(), G4GDMLReadDefine::RotationRead(), G4GDMLReadSolids::ScaledSolidRead(), G4GDMLReadDefine::ScaleRead(), G4GDMLReadSetup::SetupRead(), G4GDMLReadStructure::SkinSurfaceRead(), G4GDMLReadSolids::SphereRead(), G4GDMLReadSolids::TessellatedRead(), G4GDMLReadSolids::TetRead(), G4GDMLReadSolids::TorusRead(), G4GDMLReadSolids::TrapRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadSolids::TriangularRead(), G4GDMLReadSolids::TubeRead(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), G03ColorReader::VolumeRead(), G4GDMLReadStructure::VolumeRead(), and G4GDMLReadSolids::XtruRead().
void G4GDMLRead::GeneratePhysvolName (const G4String & nameIn, G4VPhysicalVolume * physvol) protected
Definition at line 81 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 81 of file G4GDMLRead.cc
References eval, G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetName(), G4VPhysicalVolume::SetName(), and G4GDMLEvaluator::SolveBrackets().
Referenced by G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadStructure::PhysvolRead(), and G4GDMLReadStructure::ReplicaRead().
const G4GDMLAuxListType * G4GDMLRead::GetAuxList () const
Definition at line 469 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 469 of file G4GDMLRead.cc
References auxGlobalList.
virtual G4String G4GDMLRead::GetSetup (const G4String &) pure virtual
Implemented in G4GDMLReadSetup.
virtual G4LogicalVolume* G4GDMLRead::GetVolume (const G4String &) const pure virtual
Implemented in G4GDMLReadStructure.
Referenced by G4GDMLReadParamvol::ParamvolRead().
void G4GDMLRead::LoopRead (const xercesc::DOMElement * const element, void(G4GDMLRead::*)(const xercesc::DOMElement *const) func) protected
Definition at line 176 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 176 of file G4GDMLRead.cc
References eval, G4GDMLEvaluator::EvaluateInteger(), FatalException, func, G4Exception(), inLoop, G4GDMLEvaluator::IsVariable(), loopCount, G4GDMLEvaluator::SetVariable(), Acts::Test::step(), and Transcode().
Referenced by G4GDMLReadParamvol::ParameterisedRead(), G4GDMLReadParamvol::Paramvol_contentRead(), G4GDMLReadSolids::SolidsRead(), G4GDMLReadStructure::StructureRead(), and G4GDMLReadStructure::Volume_contentRead().
virtual void G4GDMLRead::MaterialsRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadMaterials.
Referenced by Read().
void G4GDMLRead::OverlapCheck (G4bool flag)
Definition at line 63 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GDMLRead.cc
References check.
virtual void G4GDMLRead::Paramvol_contentRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadParamvol.
Referenced by G4GDMLReadParamvol::ParameterisedRead(), and G4GDMLReadParamvol::Paramvol_contentRead().
void G4GDMLRead::Read (const G4String & fileName, G4bool validation, G4bool isModule, G4bool strip = true)
Definition at line 357 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 357 of file G4GDMLRead.cc
References DefineRead(), dostrip, e, ExtensionRead(), FatalException, G4cout, G4endl, G4Exception(), inLoop, MaterialsRead(), message(), parser(), SetupRead(), SolidsRead(), StripNames(), StructureRead(), Transcode(), UserinfoRead(), and validate.
Referenced by G4GDMLReadStructure::FileRead().
virtual void G4GDMLRead::SetupRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadSetup.
Referenced by Read().
virtual void G4GDMLRead::SolidsRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadSolids.
Referenced by Read(), and G4GDMLReadSolids::SolidsRead().
G4String G4GDMLRead::Strip (const G4String & name) const protected
Definition at line 97 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 97 of file G4GDMLRead.cc
References G4String::remove().
Referenced by G4GDMLReadStructure::BorderSurfaceRead(), G4GDMLReadMaterials::ElementRead(), G4GDMLReadMaterials::IsotopeRead(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), and G4GDMLReadStructure::SkinSurfaceRead().
void G4GDMLRead::StripName (G4String & name) const
Definition at line 103 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 103 of file G4GDMLRead.cc
References G4String::remove().
Referenced by G4GDMLParser::ExportRegions(), GenerateName(), G4GDMLParser::ImportRegions(), and StripNames().
void G4GDMLRead::StripNames () const
Definition at line 108 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 108 of file G4GDMLRead.cc
References elements, G4cout, G4endl, G4Element::GetElementTable(), G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4Material::GetMaterialTable(), G4VSolid::GetName(), G4Element::GetName(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), G4TrackingService::materials, G4VSolid::SetName(), G4VPhysicalVolume::SetName(), G4LogicalVolume::SetName(), G4Element::SetName(), G4Material::SetName(), and StripName().
Referenced by Read().
virtual void G4GDMLRead::StructureRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadStructure.
Referenced by Read(), and G4GDMLReadStructure::StructureRead().
G4String G4GDMLRead::Transcode (const XMLCh * const toTranscode) protected
Definition at line 55 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 55 of file G4GDMLRead.cc
Referenced by G4GDMLReadStructure::AssemblyRead(), G4GDMLReadMaterials::AtomRead(), AuxiliaryRead(), G4GDMLReadStructure::AxisRead(), G4GDMLReadSolids::BooleanRead(), G4GDMLReadStructure::BorderSurfaceRead(), G4GDMLReadParamvol::Box_dimensionsRead(), G4GDMLReadSolids::BoxRead(), G03ColorReader::ColorRead(), G4GDMLReadMaterials::CompositeRead(), G4GDMLReadParamvol::Cone_dimensionsRead(), G4GDMLReadSolids::ConeRead(), G4GDMLReadDefine::ConstantRead(), G4GDMLReadSolids::CutTubeRead(), G4GDMLReadDefine::DefineRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadMaterials::DRead(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadMaterials::ElementRead(), G4GDMLReadParamvol::Ellipsoid_dimensionsRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), G4GDMLReadDefine::ExpressionRead(), G03ColorReader::ExtensionRead(), G4GDMLReadStructure::FileRead(), G4GDMLReadMaterials::FractionRead(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4GDMLReadParamvol::Hype_dimensionsRead(), G4GDMLReadSolids::HypeRead(), G4GDMLReadMaterials::IsotopeRead(), LoopRead(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadMaterials::MaterialsRead(), G4GDMLReadDefine::MatrixRead(), G4GDMLReadMaterials::MEERead(), G4GDMLReadMaterials::MixtureRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadSolids::MultiUnionRead(), G4GDMLReadSolids::OpticalSurfaceRead(), G4GDMLReadParamvol::Orb_dimensionsRead(), G4GDMLReadSolids::OrbRead(), G4GDMLReadParamvol::Para_dimensionsRead(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLReadParamvol::ParameterisedRead(), G4GDMLReadParamvol::ParametersRead(), G4GDMLReadParamvol::Paramvol_contentRead(), G4GDMLReadParamvol::ParamvolRead(), G4GDMLReadSolids::ParaRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadParamvol::Polycone_dimensionsRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLReadDefine::PositionRead(), G4GDMLReadMaterials::PRead(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), G4GDMLReadSolids::QuadrangularRead(), G4GDMLReadStructure::QuantityRead(), G4GDMLReadDefine::QuantityRead(), Read(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadDefine::RefRead(), G4GDMLReadStructure::ReplicaRead(), G4GDMLReadStructure::ReplicavolRead(), G4GDMLReadDefine::RotationRead(), G4GDMLReadSolids::RZPointRead(), G4GDMLReadSolids::ScaledSolidRead(), G4GDMLReadDefine::ScaleRead(), G4GDMLReadSolids::SectionRead(), G4GDMLReadSetup::SetupRead(), G4GDMLReadStructure::SkinSurfaceRead(), G4GDMLReadSolids::SolidsRead(), G4GDMLReadParamvol::Sphere_dimensionsRead(), G4GDMLReadSolids::SphereRead(), G4GDMLReadStructure::StructureRead(), G4GDMLReadSolids::TessellatedRead(), G4GDMLReadSolids::TetRead(), G4GDMLReadParamvol::Torus_dimensionsRead(), G4GDMLReadSolids::TorusRead(), G4GDMLReadParamvol::Trap_dimensionsRead(), G4GDMLReadSolids::TrapRead(), G4GDMLReadParamvol::Trd_dimensionsRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadMaterials::TRead(), G4GDMLReadSolids::TriangularRead(), G4GDMLReadParamvol::Tube_dimensionsRead(), G4GDMLReadSolids::TubeRead(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), G4GDMLReadSolids::TwoDimVertexRead(), UserinfoRead(), G4GDMLReadDefine::VariableRead(), G4GDMLReadDefine::VectorRead(), G4GDMLReadStructure::Volume_contentRead(), G03ColorReader::VolumeRead(), G4GDMLReadStructure::VolumeRead(), G4GDMLReadSolids::XtruRead(), and G4GDMLReadSolids::ZplaneRead().
void G4GDMLRead::UserinfoRead (const xercesc::DOMElement * const userinfoElement) virtual
Definition at line 317 of file G4GDMLRead.cc.
View newest version in sPHENIX GitHub at line 317 of file G4GDMLRead.cc
References auxGlobalList, AuxiliaryRead(), FatalException, G4cout, G4endl, G4Exception(), and Transcode().
Referenced by Read().
virtual void G4GDMLRead::Volume_contentRead (const xercesc::DOMElement * const) pure virtual
Implemented in G4GDMLReadStructure.
Referenced by G4GDMLReadStructure::Volume_contentRead().
Member Data Documentation
G4GDMLAuxListType G4GDMLRead::auxGlobalList private
Definition at line 162 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 162 of file G4GDMLRead.hh
Referenced by GetAuxList(), and UserinfoRead().
G4bool G4GDMLRead::check protected
Definition at line 156 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 156 of file G4GDMLRead.hh
Referenced by OverlapCheck(), G4GDMLReadParamvol::ParamvolRead(), and G4GDMLReadStructure::PhysvolRead().
G4bool G4GDMLRead::dostrip protected
Definition at line 157 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 157 of file G4GDMLRead.hh
Referenced by G4GDMLReadStructure::GetWorldVolume(), and Read().
G4GDMLEvaluator G4GDMLRead::eval protected
Definition at line 154 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GDMLRead.hh
Referenced by G4GDMLReadMaterials::AtomRead(), G4GDMLReadStructure::AxisRead(), G4GDMLReadParamvol::Box_dimensionsRead(), G4GDMLReadSolids::BoxRead(), G4GDMLReadStructure::Clear(), G03ColorReader::ColorRead(), G4GDMLReadMaterials::CompositeRead(), G4GDMLReadParamvol::Cone_dimensionsRead(), G4GDMLReadSolids::ConeRead(), G4GDMLReadDefine::ConstantRead(), G4GDMLReadSolids::CutTubeRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadMaterials::DRead(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadMaterials::ElementRead(), G4GDMLReadParamvol::Ellipsoid_dimensionsRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), G4GDMLReadDefine::ExpressionRead(), G4GDMLReadMaterials::FractionRead(), GenerateName(), GeneratePhysvolName(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4GDMLReadDefine::GetConstant(), G4GDMLReadDefine::GetVariable(), G4GDMLReadParamvol::Hype_dimensionsRead(), G4GDMLReadSolids::HypeRead(), G4GDMLReadMaterials::IsotopeRead(), G4GDMLReadDefine::IsValidID(), LoopRead(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadDefine::MatrixRead(), G4GDMLReadMaterials::MEERead(), G4GDMLReadSolids::OpticalSurfaceRead(), G4GDMLReadParamvol::Orb_dimensionsRead(), G4GDMLReadSolids::OrbRead(), G4GDMLReadParamvol::Para_dimensionsRead(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLReadParamvol::ParameterisedRead(), G4GDMLReadSolids::ParaRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadParamvol::Polycone_dimensionsRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLReadDefine::PositionRead(), G4GDMLReadMaterials::PRead(), G4GDMLReadStructure::QuantityRead(), G4GDMLReadDefine::QuantityRead(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadDefine::RotationRead(), G4GDMLReadSolids::RZPointRead(), G4GDMLReadDefine::ScaleRead(), G4GDMLReadSolids::SectionRead(), G4GDMLReadParamvol::Sphere_dimensionsRead(), G4GDMLReadSolids::SphereRead(), G4GDMLReadParamvol::Torus_dimensionsRead(), G4GDMLReadSolids::TorusRead(), G4GDMLReadParamvol::Trap_dimensionsRead(), G4GDMLReadSolids::TrapRead(), G4GDMLReadParamvol::Trd_dimensionsRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadMaterials::TRead(), G4GDMLReadParamvol::Tube_dimensionsRead(), G4GDMLReadSolids::TubeRead(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), G4GDMLReadSolids::TwoDimVertexRead(), G4GDMLReadDefine::VariableRead(), G4GDMLReadDefine::VectorRead(), G4GDMLReadStructure::Volume_contentRead(), and G4GDMLReadSolids::ZplaneRead().
G4int G4GDMLRead::inLoop private
Definition at line 161 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 161 of file G4GDMLRead.hh
Referenced by GenerateName(), LoopRead(), and Read().
G4int G4GDMLRead::loopCount private
Definition at line 161 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 161 of file G4GDMLRead.hh
Referenced by LoopRead().
G4bool G4GDMLRead::validate protected
Definition at line 155 of file G4GDMLRead.hh.
View newest version in sPHENIX GitHub at line 155 of file G4GDMLRead.hh
Referenced by G4GDMLReadStructure::FileRead(), and Read().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLRead.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLRead.cc