ECCE @ EIC Software: XrayFluoPhysicsList Class Reference
XrayFluoPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPhysicsList.hh>
Public Member Functions
XrayFluoPhysicsList ()
virtual ~XrayFluoPhysicsList ()
void ConstructParticle ()
void AddPhysicsList (const G4String &name)
void ConstructProcess ()
void AddDecay ()
void AddStepMax ()
void SetCuts ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
void SetCutForPositron (G4double)
void SetCutForProton (G4double)
void SetFluorescence (G4bool)
void SetPIXE (G4bool)
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Private Attributes
XrayFluoPhysicsListMessenger * pMessenger
G4String emName
G4VPhysicsConstructor * emPhysicsList
G4double cutForGamma
G4double cutForElectron
G4double cutForPositron
G4double cutForProton
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Detailed Description
Definition at line 43 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 43 of file XrayFluoPhysicsList.hh
Constructor & Destructor Documentation
XrayFluoPhysicsList::XrayFluoPhysicsList ()
Definition at line 86 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, cutForProton, G4VUserPhysicsList::defaultCutValue, emName, emPhysicsList, G4LossTableManager::Instance(), mm, pMessenger, G4LossTableManager::SetVerbose(), and G4VModularPhysicsList::SetVerboseLevel().
XrayFluoPhysicsList::~XrayFluoPhysicsList () virtual
Definition at line 110 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 110 of file XrayFluoPhysicsList.cc
References emPhysicsList, and pMessenger.
Member Function Documentation
void XrayFluoPhysicsList::AddDecay ()
Definition at line 174 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 174 of file XrayFluoPhysicsList.cc
References G4ProcessManager::AddProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), idxAtRest, idxPostStep, G4Decay::IsApplicable(), G4ParticleDefinition::IsShortLived(), particle, and G4ProcessManager::SetProcessOrdering().
Referenced by ConstructProcess().
void XrayFluoPhysicsList::AddPhysicsList (const G4String & name)
Definition at line 220 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 220 of file XrayFluoPhysicsList.cc
References emName, emPhysicsList, G4cout, G4endl, and G4VModularPhysicsList::verboseLevel.
Referenced by XrayFluoPhysicsListMessenger::SetNewValue().
void XrayFluoPhysicsList::AddStepMax ()
Definition at line 200 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 200 of file XrayFluoPhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), XrayFluoStepMax::IsApplicable(), G4ParticleDefinition::IsShortLived(), and particle.
Referenced by ConstructProcess().
void XrayFluoPhysicsList::ConstructParticle (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 118 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 118 of file XrayFluoPhysicsList.cc
References G4AntiNeutrinoE::AntiNeutrinoEDefinition(), G4AntiNeutrinoMu::AntiNeutrinoMuDefinition(), G4ChargedGeantino::ChargedGeantinoDefinition(), G4MesonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), G4IonConstructor::ConstructParticle(), G4Electron::ElectronDefinition(), G4Gamma::GammaDefinition(), G4Geantino::GeantinoDefinition(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), G4NeutrinoE::NeutrinoEDefinition(), G4NeutrinoMu::NeutrinoMuDefinition(), and G4Positron::PositronDefinition().
void XrayFluoPhysicsList::ConstructProcess (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 153 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 153 of file XrayFluoPhysicsList.cc
References AddDecay(), AddStepMax(), G4VUserPhysicsList::AddTransportation(), G4VPhysicsConstructor::ConstructProcess(), emPhysicsList, G4EmProcessOptions::SetAuger(), G4EmProcessOptions::SetBuildCSDARange(), G4EmProcessOptions::SetDEDXBinningForCSDARange(), G4EmProcessOptions::SetFluo(), and G4EmProcessOptions::SetPIXE().
void XrayFluoPhysicsList::SetCutForElectron (G4double cut)
Definition at line 298 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 298 of file XrayFluoPhysicsList.cc
References cutForElectron, G4Electron::Electron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by XrayFluoPhysicsListMessenger::SetNewValue().
void XrayFluoPhysicsList::SetCutForGamma (G4double cut)
Definition at line 290 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 290 of file XrayFluoPhysicsList.cc
References cutForGamma, G4Gamma::Gamma(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by XrayFluoPhysicsListMessenger::SetNewValue().
void XrayFluoPhysicsList::SetCutForPositron (G4double cut)
Definition at line 306 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 306 of file XrayFluoPhysicsList.cc
References cutForPositron, G4Positron::Positron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by XrayFluoPhysicsListMessenger::SetNewValue().
void XrayFluoPhysicsList::SetCutForProton (G4double cut)
Definition at line 314 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 314 of file XrayFluoPhysicsList.cc
References cutForProton, G4Proton::Proton(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by XrayFluoPhysicsListMessenger::SetNewValue().
void XrayFluoPhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 272 of file XrayFluoPhysicsList.cc.
View newest version in sPHENIX GitHub at line 272 of file XrayFluoPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), G4BestUnit, G4cout, G4endl, G4VUserPhysicsList::SetCutValue(), and G4VModularPhysicsList::verboseLevel.
void XrayFluoPhysicsList::SetFluorescence (G4bool)
void XrayFluoPhysicsList::SetPIXE (G4bool)
Member Data Documentation
G4double XrayFluoPhysicsList::cutForElectron private
Definition at line 73 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoPhysicsList.hh
Referenced by SetCutForElectron(), SetCuts(), and XrayFluoPhysicsList().
G4double XrayFluoPhysicsList::cutForGamma private
Definition at line 72 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 72 of file XrayFluoPhysicsList.hh
Referenced by SetCutForGamma(), SetCuts(), and XrayFluoPhysicsList().
G4double XrayFluoPhysicsList::cutForPositron private
Definition at line 74 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file XrayFluoPhysicsList.hh
Referenced by SetCutForPositron(), SetCuts(), and XrayFluoPhysicsList().
G4double XrayFluoPhysicsList::cutForProton private
Definition at line 75 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 75 of file XrayFluoPhysicsList.hh
Referenced by SetCutForProton(), and XrayFluoPhysicsList().
G4String XrayFluoPhysicsList::emName private
Definition at line 69 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file XrayFluoPhysicsList.hh
Referenced by AddPhysicsList(), and XrayFluoPhysicsList().
G4VPhysicsConstructor* XrayFluoPhysicsList::emPhysicsList private
Definition at line 70 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file XrayFluoPhysicsList.hh
Referenced by AddPhysicsList(), ConstructProcess(), XrayFluoPhysicsList(), and ~XrayFluoPhysicsList().
XrayFluoPhysicsListMessenger* XrayFluoPhysicsList::pMessenger private
Definition at line 67 of file XrayFluoPhysicsList.hh.
View newest version in sPHENIX GitHub at line 67 of file XrayFluoPhysicsList.hh
Referenced by XrayFluoPhysicsList(), and ~XrayFluoPhysicsList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoPhysicsList.cc