ECCE @ EIC Software: G4PhononDownconversion Class Reference
G4PhononDownconversion Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4PhononDownconversion.hh>
Public Member Functions
G4PhononDownconversion (const G4String &processName="phononDownconversion")
virtual ~G4PhononDownconversion ()
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
Public Member Functions inherited from G4VPhononProcess
G4VPhononProcess (const G4String &processName)
virtual ~G4VPhononProcess ()
virtual void StartTracking (G4Track *track)
virtual void EndTracking ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
Protected Member Functions inherited from G4VPhononProcess
virtual G4int GetPolarization (const G4Track &track) const
virtual G4int GetPolarization (const G4Track *track) const
virtual G4int ChoosePolarization (G4double Ldos, G4double STdos, G4double FTdos) const
virtual G4Track * CreateSecondary (G4int polarization, const G4ThreeVector &K, G4double energy) const
Private Member Functions
G4double GetLTDecayProb (G4double, G4double) const
G4double GetTTDecayProb (G4double, G4double) const
G4double MakeLDeviation (G4double, G4double) const
G4double MakeTTDeviation (G4double, G4double) const
G4double MakeTDeviation (G4double, G4double) const
void MakeTTSecondaries (const G4Track &)
void MakeLTSecondaries (const G4Track &)
G4PhononDownconversion (G4PhononDownconversion &)
G4PhononDownconversion & operator= (const G4PhononDownconversion &right)
Private Attributes
G4double fBeta
G4double fGamma
G4double fLambda
G4double fMu
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VPhononProcess
G4PhononTrackMap * trackKmap
const G4LatticePhysical * theLattice
Detailed Description
Definition at line 35 of file G4PhononDownconversion.hh.
View newest version in sPHENIX GitHub at line 35 of file G4PhononDownconversion.hh
Constructor & Destructor Documentation
G4PhononDownconversion::G4PhononDownconversion (const G4String & processName = "phononDownconversion")
Definition at line 50 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PhononDownconversion.cc
G4PhononDownconversion::~G4PhononDownconversion () virtual
Definition at line 53 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 53 of file G4PhononDownconversion.cc
G4PhononDownconversion::G4PhononDownconversion (G4PhononDownconversion &) private
Member Function Documentation
G4double G4PhononDownconversion::GetLTDecayProb (G4double d, G4double x) const private
Definition at line 110 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 110 of file G4PhononDownconversion.cc
References x.
Referenced by MakeLTSecondaries().
G4double G4PhononDownconversion::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition * condition) protected virtual
Implements G4VDiscreteProcess.
Definition at line 57 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PhononDownconversion.cc
References A(), G4cout, G4endl, G4LatticePhysical::GetAnhDecConstant(), G4Track::GetKineticEnergy(), G4Track::GetVelocity(), source.hepunit::h_Planck, mfp, NotForced, G4VPhononProcess::theLattice, and G4VProcess::verboseLevel.
G4double G4PhononDownconversion::GetTTDecayProb (G4double d, G4double x) const private
Definition at line 118 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 118 of file G4PhononDownconversion.cc
References A(), B(), C(), D(), d, fBeta, fGamma, fLambda, fMu, and x.
Referenced by MakeTTSecondaries().
G4bool G4PhononDownconversion::IsApplicable (const G4ParticleDefinition & aPD) virtual
Reimplemented from G4VPhononProcess.
Definition at line 101 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PhononDownconversion.cc
References G4PhononLong::PhononDefinition().
G4double G4PhononDownconversion::MakeLDeviation (G4double d, G4double x) const private
Definition at line 131 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 131 of file G4PhononDownconversion.cc
Referenced by MakeLTSecondaries().
void G4PhononDownconversion::MakeLTSecondaries (const G4Track & aTrack) private
Definition at line 216 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 216 of file G4PhononDownconversion.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, G4VPhononProcess::ChoosePolarization(), G4VPhononProcess::CreateSecondary(), d, E, G4UniformRand, G4LatticePhysical::GetFTDOS(), G4PhononTrackMap::GetK(), G4Track::GetKineticEnergy(), GetLTDecayProb(), G4LatticePhysical::GetSTDOS(), G4PhononPolarization::Long, MakeLDeviation(), MakeTDeviation(), CLHEP::Hep3Vector::orthogonal(), CLHEP::Hep3Vector::rotate(), G4VParticleChange::SetNumberOfSecondaries(), G4VPhononProcess::theLattice, G4VPhononProcess::trackKmap, twopi, and x.
Referenced by PostStepDoIt().
G4double G4PhononDownconversion::MakeTDeviation (G4double d, G4double x) const private
Definition at line 140 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 140 of file G4PhononDownconversion.cc
Referenced by MakeLTSecondaries().
G4double G4PhononDownconversion::MakeTTDeviation (G4double d, G4double x) const private
Definition at line 149 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 149 of file G4PhononDownconversion.cc
Referenced by MakeTTSecondaries().
void G4PhononDownconversion::MakeTTSecondaries (const G4Track & aTrack) private
Definition at line 160 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 160 of file G4PhononDownconversion.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, G4VPhononProcess::ChoosePolarization(), G4VPhononProcess::CreateSecondary(), d, E, G4RandomDirection(), G4UniformRand, G4LatticePhysical::GetFTDOS(), G4PhononTrackMap::GetK(), G4Track::GetKineticEnergy(), G4LatticePhysical::GetSTDOS(), GetTTDecayProb(), MakeTTDeviation(), CLHEP::Hep3Vector::orthogonal(), ran(), CLHEP::Hep3Vector::rotate(), G4VParticleChange::SetNumberOfSecondaries(), G4VPhononProcess::theLattice, G4VPhononProcess::trackKmap, twopi, and x.
Referenced by PostStepDoIt().
G4PhononDownconversion& G4PhononDownconversion::operator= (const G4PhononDownconversion & right) private
G4VParticleChange * G4PhononDownconversion::PostStepDoIt (const G4Track & aTrack, const G4Step &) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 77 of file G4PhononDownconversion.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PhononDownconversion.cc
References G4VProcess::aParticleChange, fBeta, fGamma, fLambda, fMu, fStopAndKill, G4UniformRand, G4LatticePhysical::GetBeta(), G4LatticePhysical::GetGamma(), G4LatticePhysical::GetLambda(), G4LatticePhysical::GetMu(), G4ParticleChange::Initialize(), MakeLTSecondaries(), MakeTTSecondaries(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeTrackStatus(), and G4VPhononProcess::theLattice.
Member Data Documentation
G4double G4PhononDownconversion::fBeta private
Definition at line 59 of file G4PhononDownconversion.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PhononDownconversion.hh
Referenced by GetTTDecayProb(), and PostStepDoIt().
G4double G4PhononDownconversion::fGamma private
Definition at line 59 of file G4PhononDownconversion.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PhononDownconversion.hh
Referenced by GetTTDecayProb(), and PostStepDoIt().
G4double G4PhononDownconversion::fLambda private
Definition at line 59 of file G4PhononDownconversion.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PhononDownconversion.hh
Referenced by GetTTDecayProb(), and PostStepDoIt().
G4double G4PhononDownconversion::fMu private
Definition at line 59 of file G4PhononDownconversion.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PhononDownconversion.hh
Referenced by GetTTDecayProb(), and PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4PhononDownconversion.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/src/G4PhononDownconversion.cc