ECCE @ EIC Software: Dicom2RunAction Class Reference
Dicom2RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/include/Dicom2RunAction.hh>
Public Types
typedef Dicom2Run::Dicom2RunVector Dicom2RunVector
Public Member Functions
Dicom2RunAction ()
Constructor.
virtual ~Dicom2RunAction ()
Destructor.
virtual G4Run * GenerateRun () override
virtual void EndOfRunAction (const G4Run *aRun) override
Public Member Functions inherited from DicomRunAction
DicomRunAction ()
Constructor.
~DicomRunAction ()
Destructor.
void BeginOfRunAction (const G4Run *)
DicomRun * GetDicomRun () const
void PrintHeader (std::ostream *out)
std::string FillString (const std::string &name, char c, G4int n, G4bool back=true)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Additional Inherited Members
Protected Attributes inherited from DicomRunAction
DicomRun * fDcmrun
std::vector< G4String > fSDName
Detailed Description
Definition at line 42 of file Dicom2RunAction.hh.
View newest version in sPHENIX GitHub at line 42 of file Dicom2RunAction.hh
Member Typedef Documentation
typedef Dicom2Run::Dicom2RunVector Dicom2RunAction::Dicom2RunVector
Definition at line 45 of file Dicom2RunAction.hh.
View newest version in sPHENIX GitHub at line 45 of file Dicom2RunAction.hh
Constructor & Destructor Documentation
Dicom2RunAction::Dicom2RunAction ()
Constructor.
Definition at line 47 of file Dicom2RunAction.cc.
View newest version in sPHENIX GitHub at line 47 of file Dicom2RunAction.cc
Dicom2RunAction::~Dicom2RunAction () virtual
Destructor.
Definition at line 53 of file Dicom2RunAction.cc.
View newest version in sPHENIX GitHub at line 53 of file Dicom2RunAction.cc
Member Function Documentation
void Dicom2RunAction::EndOfRunAction (const G4Run * aRun) override virtual
Reimplemented from DicomRunAction.
Definition at line 66 of file Dicom2RunAction.cc.
View newest version in sPHENIX GitHub at line 66 of file Dicom2RunAction.cc
References G4VTHitsVector< T, Vector_t >::begin(), G4VTHitsVector< T, Vector_t >::end(), DicomRunAction::EndOfRunAction(), test::fname, DicomRunAction::fSDName, G4cout, G4endl, G4Exception(), G4StatAnalysis::GetHits(), Dicom2Run::GetHitsVector(), G4VTHitsVector< T, Vector_t >::GetIndex(), G4Run::GetNumberOfEvent(), G4VTHitsVector< T, Vector_t >::GetObject(), G4Run::GetRunID(), CLHEP::gray, gray, G4UserRunAction::IsMaster(), JustWarning, DicomRunAction::PrintHeader(), and G4VTHitsVector< T, Vector_t >::size().
G4Run * Dicom2RunAction::GenerateRun (void) override virtual
Reimplemented from DicomRunAction.
Definition at line 57 of file Dicom2RunAction.cc.
View newest version in sPHENIX GitHub at line 57 of file Dicom2RunAction.cc
References DicomRunAction::fDcmrun, and DicomRunAction::fSDName.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/include/Dicom2RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/src/Dicom2RunAction.cc