ECCE @ EIC Software: G4VEmProcess Class Reference
G4VEmProcess Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmProcess.hh>
Public Member Functions
G4VEmProcess (const G4String &name, G4ProcessType type=fElectromagnetic)
virtual ~G4VEmProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override=0
virtual void PrintInfo ()
virtual void ProcessDescription (std::ostream &outFile) const override
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual void StartTracking (G4Track *) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
virtual G4VEmProcess * GetEmProcess (const G4String &name)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double ComputeCrossSectionPerAtom (G4double kineticEnergy, G4double Z, G4double A=0., G4double cut=0.0)
G4double MeanFreePath (const G4Track &track)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple, G4double logKinEnergy)
void SetLambdaBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
void SetMinKinEnergyPrim (G4double e)
void SetMaxKinEnergy (G4double e)
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * LambdaTablePrim () const
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * SecondaryParticle () const
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t idxRegion) const
void AddEmModel (G4int, G4VEmModel *, const G4Region *region=nullptr)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
void UpdateEmModel (const G4String &, G4double, G4double)
G4int GetNumberOfModels () const
G4int GetNumberOfRegionModels (size_t couple_index) const
G4VEmModel * GetRegionModel (G4int idx, size_t couple_index) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
const G4VEmModel * GetCurrentModel () const
const G4Element * GetCurrentElement () const
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
G4double CrossSectionBiasingFactor () const
void ActivateForcedInteraction (G4double length=0.0, const G4String &r="", G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void SetEmMasterProcess (const G4VEmProcess *)
void SetIntegral (G4bool val)
void SetBuildTableFlag (G4bool val)
void CurrentSetup (const G4MaterialCutsCouple *, G4double energy)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void StreamProcessInfo (std::ostream &) const
virtual void InitialiseProcess (const G4ParticleDefinition *)=0
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *)
G4VEmModel * SelectModel (G4double kinEnergy, size_t index)
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *)
G4int LambdaBinning () const
G4double MinKinEnergy () const
G4double MaxKinEnergy () const
G4double PolarAngleLimit () const
G4bool IsIntegral () const
G4double RecalculateLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4ParticleChangeForGamma * GetParticleChange ()
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
size_t CurrentMaterialCutsCoupleIndex () const
const G4MaterialCutsCouple * MaterialCutsCouple () const
G4bool ApplyCuts () const
G4double GetGammaEnergyCut ()
G4double GetElectronEnergyCut ()
void SetStartFromNullFlag (G4bool val)
void SetSplineFlag (G4bool val)
const G4Element * GetTargetElement () const
const G4Isotope * GetTargetIsotope () const
Protected Attributes
G4LossTableManager * lManager
G4EmParameters * theParameters
G4EmBiasingManager * biasManager
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theElectron
G4ParticleChangeForGamma fParticleChange
std::vector< G4DynamicParticle * > secParticles
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t currentCoupleIndex
size_t basedCoupleIndex
G4int mainSecondaries
G4int secID
G4int fluoID
G4int augerID
G4int biasID
G4bool isTheMaster
G4double mfpKinEnergy
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepLambda
Private Member Functions
void Clear ()
void BuildLambdaTable ()
void StreamInfo (std::ostream &outFile, const G4ParticleDefinition &, G4bool rst=false) const
void FindLambdaMax ()
void PrintWarning (G4String tit, G4double val)
void ComputeIntegralLambda (G4double kinEnergy, G4double logKinEnergy)
void DefineMaterial (const G4MaterialCutsCouple *couple)
G4double GetLambdaFromTable (G4double kinEnergy)
G4double GetLambdaFromTable (G4double kinEnergy, G4double logKinEnergy)
G4double GetLambdaFromTablePrim (G4double kinEnergy)
G4double GetLambdaFromTablePrim (G4double kinEnergy, G4double logKinEnergy)
G4double GetCurrentLambda (G4double kinEnergy)
G4double GetCurrentLambda (G4double kinEnergy, G4double logKinEnergy)
G4double ComputeCurrentLambda (G4double kinEnergy)
G4VEmProcess (G4VEmProcess &)=delete
G4VEmProcess & operator= (const G4VEmProcess &right)=delete
Private Attributes
G4EmModelManager * modelManager
const G4ParticleDefinition * thePositron
const G4ParticleDefinition * secondaryParticle
G4bool buildLambdaTable
std::vector< G4VEmModel * > emModels
G4int numberOfModels
G4PhysicsTable * theLambdaTable
G4PhysicsTable * theLambdaTablePrim
std::vector< G4double > theEnergyOfCrossSectionMax
std::vector< G4double > theCrossSectionMax
size_t idxLambda
size_t idxLambdaPrim
const std::vector< G4double > * theCuts
const std::vector< G4double > * theCutsGamma
const std::vector< G4double > * theCutsElectron
const std::vector< G4double > * theCutsPositron
G4int nLambdaBins
G4double minKinEnergy
G4double minKinEnergyPrim
G4double maxKinEnergy
G4double lambdaFactor
G4double logLambdaFactor
G4double biasFactor
G4double massRatio
G4bool integral
G4bool applyCuts
G4bool startFromNull
G4bool splineFlag
G4bool actMinKinEnergy
G4bool actMaxKinEnergy
G4bool actBinning
G4bool actSpline
G4bool isIon
const G4VEmProcess * masterProc
G4EmDataHandler * theData
G4VEmModel * currentModel
const G4ParticleDefinition * particle
const G4ParticleDefinition * currentParticle
const G4Material * baseMaterial
G4double fFactor
G4bool biasFlag
G4bool weightFlag
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 74 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VEmProcess.hh
Constructor & Destructor Documentation
G4VEmProcess::G4VEmProcess (const G4String & name, G4ProcessType type = fElectromagnetic)
Definition at line 74 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VEmProcess.cc
References actBinning, actMaxKinEnergy, actMinKinEnergy, actSpline, augerID, basedCoupleIndex, baseMaterial, biasFactor, biasFlag, biasID, biasManager, currentCoupleIndex, currentMaterial, DBL_MAX, G4Electron::Electron(), fFactor, fluoID, fParticleChange, G4Log(), G4Gamma::Gamma(), G4LossTableBuilder::GetCoupleIndexes(), G4LossTableBuilder::GetDensityFactors(), G4VProcess::GetProcessName(), G4LossTableManager::GetTableBuilder(), idxLambda, idxLambdaPrim, G4EmParameters::Instance(), G4LossTableManager::Instance(), keV, lambdaFactor, lManager, LOG_EKIN_MIN, logLambdaFactor, mainSecondaries, massRatio, maxKinEnergy, mfpKinEnergy, minKinEnergy, minKinEnergyPrim, modelManager, nLambdaBins, G4Positron::Positron(), G4VProcess::pParticleChange, preStepKinEnergy, preStepLambda, preStepLogKinEnergy, G4LossTableManager::Register(), secID, secParticles, G4VParticleChange::SetSecondaryWeightByProcess(), G4VProcess::SetVerboseLevel(), TeV, theCuts, theCutsElectron, theCutsGamma, theCutsPositron, theDensityFactor, theDensityIdx, theElectron, theGamma, theParameters, thePositron, and weightFlag.
G4VEmProcess::~G4VEmProcess () virtual
Definition at line 158 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 158 of file G4VEmProcess.cc
References biasManager, G4LossTableManager::DeRegister(), isTheMaster, lManager, modelManager, and theData.
G4VEmProcess::G4VEmProcess (G4VEmProcess &) private delete
Member Function Documentation
void G4VEmProcess::ActivateForcedInteraction (G4double length = 0.0, const G4String & r = "", G4bool flag = true)
Definition at line 1159 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1159 of file G4VEmProcess.cc
References G4EmBiasingManager::ActivateForcedInteraction(), biasManager, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), mm, particle, G4VProcess::verboseLevel, and weightFlag.
Referenced by G4EmExtraParameters::DefineRegParamForEM().
void G4VEmProcess::ActivateSecondaryBiasing (const G4String & region, G4double factor, G4double energyLimit)
Definition at line 1179 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1179 of file G4VEmProcess.cc
References G4EmBiasingManager::ActivateSecondaryBiasing(), biasManager, G4Electron::Electron(), G4cout, G4endl, G4VProcess::GetProcessName(), MeV, secondaryParticle, and G4VProcess::verboseLevel.
Referenced by G4EmExtraParameters::DefineRegParamForEM().
void G4VEmProcess::AddEmModel (G4int order, G4VEmModel * p, const G4Region * region = nullptr)
Definition at line 195 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 195 of file G4VEmProcess.cc
References G4EmModelManager::AddEmModel(), Acts::UnitConstants::fm, modelManager, G4VProcess::pParticleChange, and G4VEmModel::SetParticleChange().
Referenced by LBE::ConstructEM(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4DNADissociation::InitialiseProcess(), G4DNAPositronium::InitialiseProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MicroElecElastic::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4RayleighScattering::InitialiseProcess(), G4MicroElecInelastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4JAEAElasticScattering::InitialiseProcess(), G4DNAElectronSolvation::InitialiseProcess(), G4eeToHadrons::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4NuclearStopping::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4EmConfigurator::PrepareModels(), and G4EmConfigurator::SetModelForRegion().
G4bool G4VEmProcess::ApplyCuts () const inline protected
Definition at line 439 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 439 of file G4VEmProcess.hh
References applyCuts.
Referenced by G4eplusAnnihilation::AtRestDoIt().
void G4VEmProcess::BuildLambdaTable () private
Definition at line 436 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 436 of file G4VEmProcess.cc
References actBinning, bin, buildLambdaTable, e, emax, CEMC_TOWER::emin, G4EmModelManager::FillLambdaVector(), G4PhysicsVector::FillSecondDerivatives(), FindLambdaMax(), fIsCrossSectionPrim, G4cout, G4endl, G4Log(), G4lrint(), G4LossTableBuilder::GetFlag(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4ProductionCutsTable::GetTableSize(), lManager, max, G4EmParameters::MaxKinEnergy(), maxKinEnergy, min, G4EmParameters::MinKinEnergy(), minKinEnergy, minKinEnergyPrim, MinPrimaryEnergy(), modelManager, nLambdaBins, G4EmParameters::NumberOfBinsPerDecade(), particle, scale, G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), splineFlag, startFromNull, theLambdaTable, theLambdaTablePrim, theParameters, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable().
void G4VEmProcess::BuildPhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4GammaGeneralProcess, G4PolarizedCompton, G4eplusPolarizedAnnihilation, StepMax, StepMax, StepMax, StepMax, and StepMax.
Definition at line 366 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 366 of file G4VEmProcess.cc
References BuildLambdaTable(), buildLambdaTable, FindLambdaMax(), G4cout, G4endl, G4VProcess::GetMasterProcess(), GetModelByIndex(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4VEmModel::InitialiseLocal(), isTheMaster, LambdaTable(), LambdaTablePrim(), masterProc, maxKinEnergy, minKinEnergyPrim, modelManager, num, G4EmModelManager::NumberOfModels(), numberOfModels, particle, StreamInfo(), theLambdaTable, theLambdaTablePrim, and G4VProcess::verboseLevel.
Referenced by G4eplusPolarizedAnnihilation::BuildPhysicsTable(), G4PolarizedCompton::BuildPhysicsTable(), and G4GammaGeneralProcess::BuildPhysicsTable().
void G4VEmProcess::Clear () private
Definition at line 178 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 178 of file G4VEmProcess.cc
References currentCouple, idxLambda, idxLambdaPrim, and preStepLambda.
Referenced by PreparePhysicsTable().
G4double G4VEmProcess::ComputeCrossSectionPerAtom (G4double kineticEnergy, G4double Z, G4double A = 0., G4double cut = 0.0)
Definition at line 1058 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1058 of file G4VEmProcess.cc
References G4VEmModel::ComputeCrossSectionPerAtom(), currentCoupleIndex, currentModel, currentParticle, and SelectModel().
G4double G4VEmProcess::ComputeCurrentLambda (G4double kinEnergy) inline private
Definition at line 537 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 537 of file G4VEmProcess.hh
References baseMaterial, G4VEmModel::CrossSectionPerVolume(), currentCoupleIndex, currentModel, currentParticle, and theCuts.
Referenced by GetCurrentLambda(), and RecalculateLambda().
void G4VEmProcess::ComputeIntegralLambda (G4double kinEnergy, G4double logKinEnergy) private
Definition at line 695 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 695 of file G4VEmProcess.cc
References currentCoupleIndex, e, e1, fFactor, GetCurrentLambda(), lambdaFactor, logLambdaFactor, mfpKinEnergy, preStepLambda, theCrossSectionMax, and theEnergyOfCrossSectionMax.
Referenced by PostStepGetPhysicalInteractionLength().
G4double G4VEmProcess::CrossSectionBiasingFactor () const inline
Definition at line 630 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 630 of file G4VEmProcess.hh
References biasFactor.
G4double G4VEmProcess::CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple * couple)
Definition at line 1015 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1015 of file G4VEmProcess.cc
References buildLambdaTable, Acts::VectorHelpers::cross(), G4VEmModel::CrossSectionPerVolume(), currentCoupleIndex, currentMaterial, currentModel, currentParticle, DefineMaterial(), fFactor, GetCurrentLambda(), max, and SelectModel().
Referenced by G4EmCalculator::GetCrossSectionPerVolume().
size_t G4VEmProcess::CurrentMaterialCutsCoupleIndex () const inline protected
Definition at line 446 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 446 of file G4VEmProcess.hh
References currentCoupleIndex.
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), and G4PolarizedCompton::ComputeSaturationFactor().
void G4VEmProcess::CurrentSetup (const G4MaterialCutsCouple * couple, G4double energy) inline
Definition at line 566 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 566 of file G4VEmProcess.hh
References currentCoupleIndex, DefineMaterial(), and SelectModel().
Referenced by GetLambda(), MeanFreePath(), RecalculateLambda(), and G4GammaGeneralProcess::SampleSecondaries().
void G4VEmProcess::DefineMaterial (const G4MaterialCutsCouple * couple) inline private
Definition at line 474 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 474 of file G4VEmProcess.hh
References basedCoupleIndex, baseMaterial, biasFactor, currentCouple, currentCoupleIndex, currentMaterial, DBL_MAX, fFactor, G4Material::GetBaseMaterial(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), idxLambda, idxLambdaPrim, mfpKinEnergy, and preStepKinEnergy.
Referenced by CrossSectionPerVolume(), CurrentSetup(), and PostStepGetPhysicalInteractionLength().
G4VEmModel * G4VEmProcess::EmModel (size_t index = 0) const
Definition at line 213 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 213 of file G4VEmProcess.cc
References emModels.
Referenced by G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), G4DNAPositronium::InitialiseProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNADissociation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4MicroElecElastic::InitialiseProcess(), G4RayleighScattering::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4MicroElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4JAEAElasticScattering::InitialiseProcess(), G4DNAElectronSolvation::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4NuclearStopping::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4DNADissociation::PrintInfo(), G4DNARotExcitation::PrintInfo(), G4DNAPositronium::PrintInfo(), G4DNAVibExcitation::PrintInfo(), G4DNAChargeIncrease::PrintInfo(), G4DNAAttachment::PrintInfo(), G4DNAChargeDecrease::PrintInfo(), G4DNAElastic::PrintInfo(), G4DNAExcitation::PrintInfo(), G4DNAIonisation::PrintInfo(), and G4PolarizedCompton::PrintInfo().
void G4VEmProcess::FindLambdaMax () private
Definition at line 1069 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1069 of file G4VEmProcess.cc
References DBL_MAX, e, emax, G4PhysicsVector::Energy(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4PhysicsVector::GetVectorLength(), G4PhysicsTable::length(), MeV, n, particle, smax, theCrossSectionMax, theEnergyOfCrossSectionMax, theLambdaTable, and G4VProcess::verboseLevel.
Referenced by BuildLambdaTable(), and BuildPhysicsTable().
const G4Element * G4VEmProcess::GetCurrentElement () const
Definition at line 1132 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1132 of file G4VEmProcess.cc
References currentModel, and G4VEmModel::GetCurrentElement().
G4double G4VEmProcess::GetCurrentLambda (G4double kinEnergy) inline private
Definition at line 545 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 545 of file G4VEmProcess.hh
References ComputeCurrentLambda(), currentModel, fFactor, GetLambdaFromTable(), GetLambdaFromTablePrim(), minKinEnergyPrim, theLambdaTable, and x.
Referenced by ComputeIntegralLambda(), CrossSectionPerVolume(), GetLambda(), MeanFreePath(), and PostStepGetPhysicalInteractionLength().
G4double G4VEmProcess::GetCurrentLambda (G4double kinEnergy, G4double logKinEnergy) inline private
Definition at line 554 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 554 of file G4VEmProcess.hh
References ComputeCurrentLambda(), currentModel, fFactor, GetLambdaFromTable(), GetLambdaFromTablePrim(), minKinEnergyPrim, theLambdaTable, and x.
const G4VEmModel * G4VEmProcess::GetCurrentModel () const inline
Definition at line 737 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 737 of file G4VEmProcess.hh
References currentModel.
G4double G4VEmProcess::GetElectronEnergyCut () inline protected
Definition at line 467 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 467 of file G4VEmProcess.hh
References currentCoupleIndex, and theCutsElectron.
Referenced by G4eplusAnnihilation::AtRestDoIt().
G4VEmProcess * G4VEmProcess::GetEmProcess (const G4String & name) virtual
Reimplemented in G4GammaGeneralProcess.
Definition at line 1250 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1250 of file G4VEmProcess.cc
References G4VProcess::GetProcessName().
G4double G4VEmProcess::GetGammaEnergyCut () inline protected
Definition at line 460 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 460 of file G4VEmProcess.hh
References currentCoupleIndex, and theCutsGamma.
Referenced by G4eplusAnnihilation::AtRestDoIt().
G4double G4VEmProcess::GetLambda (G4double kinEnergy, const G4MaterialCutsCouple * couple) inline
Definition at line 575 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 575 of file G4VEmProcess.hh
References CurrentSetup(), and GetCurrentLambda().
Referenced by G4GammaGeneralProcess::BuildPhysicsTable(), PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), and G4GammaGeneralProcess::TotalCrossSectionPerVolume().
G4double G4VEmProcess::GetLambda (G4double kinEnergy, const G4MaterialCutsCouple * couple, G4double logKinEnergy) inline
Definition at line 582 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 582 of file G4VEmProcess.hh
References CurrentSetup(), and GetCurrentLambda().
G4double G4VEmProcess::GetLambdaFromTable (G4double kinEnergy) inline private
Definition at line 513 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 513 of file G4VEmProcess.hh
References basedCoupleIndex, idxLambda, and theLambdaTable.
Referenced by GetCurrentLambda().
G4double G4VEmProcess::GetLambdaFromTable (G4double kinEnergy, G4double logKinEnergy) inline private
Definition at line 518 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 518 of file G4VEmProcess.hh
References basedCoupleIndex, and theLambdaTable.
G4double G4VEmProcess::GetLambdaFromTablePrim (G4double kinEnergy) inline private
Definition at line 525 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 525 of file G4VEmProcess.hh
References basedCoupleIndex, e, idxLambdaPrim, and theLambdaTablePrim.
Referenced by GetCurrentLambda().
G4double G4VEmProcess::GetLambdaFromTablePrim (G4double kinEnergy, G4double logKinEnergy) inline private
Definition at line 530 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 530 of file G4VEmProcess.hh
References basedCoupleIndex, e, and theLambdaTablePrim.
G4double G4VEmProcess::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Implements G4VDiscreteProcess.
Reimplemented in G4GammaGeneralProcess, G4PolarizedCompton, G4eplusPolarizedAnnihilation, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, and StepMax.
Definition at line 1036 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1036 of file G4VEmProcess.cc
References MeanFreePath(), and NotForced.
Referenced by G4eplusPolarizedAnnihilation::GetMeanFreePath(), and G4PolarizedCompton::GetMeanFreePath().
G4VEmModel * G4VEmProcess::GetModelByIndex (G4int idx = 0, G4bool ver = false) const
Definition at line 249 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 249 of file G4VEmProcess.cc
References G4EmModelManager::GetModel(), and modelManager.
Referenced by BuildPhysicsTable(), and G4EmCalculator::ComputeNuclearDEDX().
G4int G4VEmProcess::GetNumberOfModels () const
Definition at line 228 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 228 of file G4VEmProcess.cc
References modelManager, and G4EmModelManager::NumberOfModels().
G4int G4VEmProcess::GetNumberOfRegionModels (size_t couple_index) const
Definition at line 235 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 235 of file G4VEmProcess.cc
References modelManager, and G4EmModelManager::NumberOfRegionModels().
G4ParticleChangeForGamma * G4VEmProcess::GetParticleChange () inline protected
Definition at line 686 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 686 of file G4VEmProcess.hh
References fParticleChange.
G4VEmModel * G4VEmProcess::GetRegionModel (G4int idx, size_t couple_index) const
Definition at line 242 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 242 of file G4VEmProcess.cc
References G4EmModelManager::GetRegionModel(), and modelManager.
const G4Element * G4VEmProcess::GetTargetElement () const inline protected
Definition at line 723 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 723 of file G4VEmProcess.hh
References currentModel, and G4VEmModel::GetCurrentElement().
const G4Isotope * G4VEmProcess::GetTargetIsotope () const inline protected
Definition at line 730 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 730 of file G4VEmProcess.hh
References currentModel, and G4VEmModel::GetCurrentIsotope().
virtual void G4VEmProcess::InitialiseProcess (const G4ParticleDefinition *) protected pure virtual
Implemented in G4PhotoElectricEffect, G4GammaConversion, G4NuclearStopping, G4PolarizedPhotoElectricEffect, G4PolarizedCompton, G4eplusAnnihilation, G4ComptonScattering, G4GammaGeneralProcess, G4PolarizedGammaConversion, G4DNAElectronSolvation, G4eeToHadrons, G4JAEAElasticScattering, G4CoulombScattering, G4MicroElecInelastic, G4MuElecInelastic, G4RayleighScattering, G4MicroElecElastic, G4MuElecElastic, G4DNAVibExcitation, G4DNAIonisation, G4DNAExcitation, G4DNAChargeDecrease, G4DNAElastic, StepMax, G4DNAAttachment, G4DNAChargeIncrease, StepMax, StepMax, StepMax, StepMax, G4DNADissociation, G4DNAPositronium, and G4DNARotExcitation.
Referenced by PreparePhysicsTable().
virtual G4bool G4VEmProcess::IsApplicable (const G4ParticleDefinition & p) override pure virtual
Reimplemented from G4VProcess.
Implemented in G4PhotoElectricEffect, G4PolarizedPhotoElectricEffect, G4GammaConversion, G4PolarizedCompton, G4ComptonScattering, G4GammaGeneralProcess, G4eplusAnnihilation, G4NuclearStopping, G4PolarizedGammaConversion, G4eeToHadrons, G4MicroElecInelastic, G4MuElecInelastic, G4DNAElectronSolvation, G4CoulombScattering, G4RayleighScattering, G4JAEAElasticScattering, G4MicroElecElastic, G4MuElecElastic, StepMax, StepMax, StepMax, G4DNAIonisation, StepMax, StepMax, G4DNAExcitation, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, G4DNAChargeDecrease, G4DNAElastic, StepMax, G4DNAAttachment, G4DNAChargeIncrease, G4DNAVibExcitation, StepMax, StepMax, StepMax, StepMax, StepMax, G4DNADissociation, G4DNAPositronium, and G4DNARotExcitation.
G4bool G4VEmProcess::IsIntegral () const inline protected
Definition at line 672 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 672 of file G4VEmProcess.hh
References integral.
G4int G4VEmProcess::LambdaBinning () const inline protected
Definition at line 602 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 602 of file G4VEmProcess.hh
References nLambdaBins.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), and G4eplusPolarizedAnnihilation::BuildAsymmetryTables().
G4PhysicsVector * G4VEmProcess::LambdaPhysicsVector (const G4MaterialCutsCouple *) protected
Definition at line 1122 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1122 of file G4VEmProcess.cc
References maxKinEnergy, minKinEnergy, nLambdaBins, G4PhysicsVector::SetSpline(), G4EmParameters::Spline(), theParameters, and v.
Referenced by G4eplusPolarizedAnnihilation::BuildAsymmetryTables().
G4PhysicsTable * G4VEmProcess::LambdaTable () const inline
Definition at line 637 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 637 of file G4VEmProcess.hh
References theLambdaTable.
Referenced by BuildPhysicsTable(), and G4EmCalculator::FindLambdaTable().
G4PhysicsTable * G4VEmProcess::LambdaTablePrim () const inline
Definition at line 644 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 644 of file G4VEmProcess.hh
References theLambdaTablePrim.
Referenced by BuildPhysicsTable().
const G4MaterialCutsCouple * G4VEmProcess::MaterialCutsCouple () const inline protected
Definition at line 453 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 453 of file G4VEmProcess.hh
References currentCouple.
Referenced by G4eplusAnnihilation::AtRestDoIt().
G4double G4VEmProcess::MaxKinEnergy () const inline protected
Definition at line 616 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 616 of file G4VEmProcess.hh
References maxKinEnergy.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), and G4eplusAnnihilation::InitialiseProcess().
G4double G4VEmProcess::MeanFreePath (const G4Track & track)
Definition at line 1046 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1046 of file G4VEmProcess.cc
References CurrentSetup(), DBL_MAX, GetCurrentLambda(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), and G4Track::GetMaterialCutsCouple().
Referenced by G4GammaGeneralProcess::GetMeanFreePath(), and GetMeanFreePath().
G4double G4VEmProcess::MinKinEnergy () const inline protected
Definition at line 609 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 609 of file G4VEmProcess.hh
References minKinEnergy.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), and G4eplusAnnihilation::InitialiseProcess().
G4double G4VEmProcess::MinPrimaryEnergy (const G4ParticleDefinition * , const G4Material *) protected virtual
Reimplemented in G4GammaConversion, and G4CoulombScattering.
Definition at line 187 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 187 of file G4VEmProcess.cc
Referenced by BuildLambdaTable().
G4VEmProcess& G4VEmProcess::operator= (const G4VEmProcess & right) private delete
const G4ParticleDefinition * G4VEmProcess::Particle () const inline
Definition at line 651 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 651 of file G4VEmProcess.hh
References particle.
G4double G4VEmProcess::PolarAngleLimit () const inline protected
Definition at line 623 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 623 of file G4VEmProcess.hh
References G4EmParameters::MscThetaLimit(), and theParameters.
G4VParticleChange * G4VEmProcess::PostStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VDiscreteProcess.
Reimplemented in G4GammaGeneralProcess, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, and StepMax.
Definition at line 724 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 724 of file G4VEmProcess.cc
References G4VParticleChange::AddSecondary(), applyCuts, G4EmBiasingManager::ApplySecondaryBiasing(), augerID, biasFactor, biasFlag, biasID, biasManager, G4VProcess::ClearNumberOfInteractionLengthLeft(), currentCouple, currentCoupleIndex, currentModel, currentParticle, DBL_MAX, e, edep, source.hepunit::electron_mass_c2, fAlive, fluoID, G4EmBiasingManager::ForcedInteractionRegion(), fParticleChange, fStopAndKill, fStopButAlive, G4cout, G4endl, G4UniformRand, G4ProcessManager::GetAtRestProcessVector(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetKineticEnergy(), GetLambda(), G4VParticleChange::GetLocalEnergyDeposit(), G4DynamicParticle::GetLogKineticEnergy(), G4VParticleChange::GetParentWeight(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4ParticleChangeForGamma::GetProposedKineticEnergy(), G4StepPoint::GetSafety(), G4Track::GetTouchableHandle(), G4VParticleChange::GetTrackStatus(), G4Track::GetTrackStatus(), G4EmBiasingManager::GetWeight(), G4ParticleChangeForGamma::InitializeForPostStep(), integral, G4VEmModel::IsActive(), mainSecondaries, massRatio, MeV, mfpKinEnergy, num, particle, G4VProcess::pParticleChange, preStepLambda, G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4VEmModel::SampleSecondaries(), secID, G4EmBiasingManager::SecondaryBiasingRegion(), secParticles, SelectModel(), G4Track::SetCreatorModelIndex(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), G4ProcessVector::size(), t, theCuts, theCutsElectron, theCutsGamma, theCutsPositron, theElectron, theGamma, G4VProcess::theNumberOfInteractionLengthLeft, thePositron, Acts::VectorHelpers::time(), G4VProcess::verboseLevel, weight, and weightFlag.
Referenced by G4GammaGeneralProcess::SampleSecondaries().
G4double G4VEmProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VDiscreteProcess.
Reimplemented in G4GammaGeneralProcess, G4PolarizedCompton, G4eplusPolarizedAnnihilation, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, and StepMax.
Definition at line 624 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 624 of file G4VEmProcess.cc
References biasFlag, biasManager, ComputeIntegralLambda(), currentCoupleIndex, G4VProcess::currentInteractionLength, currentModel, DBL_MAX, DefineMaterial(), G4EmBiasingManager::ForcedInteractionRegion(), G4Log(), G4UniformRand, GetCurrentLambda(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4Track::GetParentID(), G4EmBiasingManager::GetStepLimit(), integral, G4VEmModel::IsActive(), massRatio, max, mfpKinEnergy, NotForced, preStepKinEnergy, preStepLambda, preStepLogKinEnergy, SelectModel(), G4VProcess::theInitialNumberOfInteractionLength, G4VProcess::theNumberOfInteractionLengthLeft, and x.
Referenced by G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), and G4PolarizedCompton::PostStepGetPhysicalInteractionLength().
void G4VEmProcess::PreparePhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4GammaGeneralProcess, StepMax, StepMax, StepMax, StepMax, and StepMax.
Definition at line 256 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 256 of file G4VEmProcess.cc
References actMaxKinEnergy, actMinKinEnergy, actSpline, G4EmParameters::ApplyCuts(), applyCuts, G4LossTableManager::AtomDeexcitation(), augerID, biasFlag, biasID, biasManager, buildLambdaTable, Clear(), currentModel, DBL_MAX, G4EmParameters::DefineRegParamForEM(), fluoID, G4cout, G4endl, G4Log(), G4GenericIon::GenericIon(), G4ProductionCutsTable::GetEnergyCutsVector(), G4EmModelManager::GetModel(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetParticleType(), G4VProcess::GetProcessName(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4ProductionCutsTable::GetTableSize(), G4VEmModel::HighEnergyLimit(), idxG4ElectronCut, idxG4GammaCut, idxG4PositronCut, G4EmBiasingManager::Initialise(), G4EmModelManager::Initialise(), G4LossTableBuilder::InitialiseBaseMaterials(), InitialiseProcess(), isIon, G4LossTableManager::IsMaster(), isTheMaster, G4EmParameters::LambdaFactor(), lambdaFactor, lManager, logLambdaFactor, mainSecondaries, G4EmDataHandler::MakeTable(), G4EmParameters::MaxKinEnergy(), maxKinEnergy, G4EmParameters::MinKinEnergy(), minKinEnergy, minKinEnergyPrim, modelManager, G4EmParameters::MscThetaLimit(), n, G4EmModelManager::NumberOfModels(), numberOfModels, particle, pname(), G4LossTableManager::PreparePhysicsTable(), G4PhysicsModelCatalog::Register(), secID, secondaryParticle, G4EmModelManager::SetFluoFlag(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetMasterThread(), SetParticle(), G4VEmModel::SetPolarAngleLimit(), G4VProcess::SetVerboseLevel(), G4EmParameters::Spline(), splineFlag, theCrossSectionMax, theCuts, theCutsElectron, theCutsGamma, theCutsPositron, theData, theEnergyOfCrossSectionMax, theLambdaTable, theLambdaTablePrim, theParameters, G4EmParameters::Verbose(), G4VProcess::verboseLevel, and G4EmParameters::WorkerVerbose().
Referenced by G4GammaGeneralProcess::PreparePhysicsTable().
virtual void G4VEmProcess::PrintInfo () inline virtual
Reimplemented in G4PhotoElectricEffect, G4GammaConversion, G4PolarizedPhotoElectricEffect, G4NuclearStopping, G4PolarizedCompton, G4ComptonScattering, G4PolarizedGammaConversion, G4eplusPolarizedAnnihilation, G4JAEAElasticScattering, G4MicroElecInelastic, G4MuElecInelastic, G4DNAElectronSolvation, G4RayleighScattering, G4MicroElecElastic, G4MuElecElastic, G4DNAIonisation, G4DNAExcitation, G4DNAChargeDecrease, G4DNAElastic, G4DNAAttachment, G4DNAChargeIncrease, G4DNAVibExcitation, G4DNADissociation, G4DNAPositronium, and G4DNARotExcitation.
Definition at line 89 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VEmProcess.hh
void G4VEmProcess::PrintWarning (G4String tit, G4double val) private
Definition at line 1257 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1257 of file G4VEmProcess.cc
References G4Exception(), G4VProcess::GetProcessName(), GeV, JustWarning, keV, G4EmParameters::MaxKinEnergy(), G4EmParameters::MinKinEnergy(), G4EmParameters::NumberOfBins(), and theParameters.
Referenced by SetLambdaBinning(), SetMaxKinEnergy(), SetMinKinEnergy(), and SetMinKinEnergyPrim().
void G4VEmProcess::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Reimplemented in G4PhotoElectricEffect, G4GammaConversion, G4NuclearStopping, G4ComptonScattering, G4eplusAnnihilation, G4GammaGeneralProcess, G4eeToHadrons, G4RayleighScattering, and G4CoulombScattering.
Definition at line 1271 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1271 of file G4VEmProcess.cc
References particle, and StreamInfo().
Referenced by G4CoulombScattering::ProcessDescription(), G4RayleighScattering::ProcessDescription(), G4eeToHadrons::ProcessDescription(), G4GammaGeneralProcess::ProcessDescription(), G4eplusAnnihilation::ProcessDescription(), G4ComptonScattering::ProcessDescription(), G4NuclearStopping::ProcessDescription(), G4GammaConversion::ProcessDescription(), and G4PhotoElectricEffect::ProcessDescription().
G4double G4VEmProcess::RecalculateLambda (G4double kinEnergy, const G4MaterialCutsCouple * couple) inline protected
Definition at line 592 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 592 of file G4VEmProcess.hh
References ComputeCurrentLambda(), CurrentSetup(), and fFactor.
G4bool G4VEmProcess::RetrievePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4GammaGeneralProcess.
Definition at line 937 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 937 of file G4VEmProcess.cc
References buildLambdaTable, INPUTHEPMC::filename, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetPhysicsTableFileName(), G4VProcess::GetProcessName(), G4PhysicsTable::length(), maxKinEnergy, minKinEnergyPrim, n, particle, G4PhysicsTableHelper::RetrievePhysicsTable(), G4EmParameters::Spline(), theLambdaTable, theLambdaTablePrim, theParameters, and G4VProcess::verboseLevel.
Referenced by G4GammaGeneralProcess::RetrievePhysicsTable().
const G4ParticleDefinition * G4VEmProcess::SecondaryParticle () const inline
Definition at line 658 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 658 of file G4VEmProcess.hh
References secondaryParticle.
G4VEmModel * G4VEmProcess::SelectModel (G4double kinEnergy, size_t index) inline protected
Definition at line 493 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 493 of file G4VEmProcess.hh
References currentCouple, currentModel, modelManager, numberOfModels, G4EmModelManager::SelectModel(), and G4VEmModel::SetCurrentCouple().
Referenced by G4NuclearStopping::AlongStepDoIt(), G4eplusAnnihilation::AtRestDoIt(), ComputeCrossSectionPerAtom(), CrossSectionPerVolume(), CurrentSetup(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4VEmModel * G4VEmProcess::SelectModelForMaterial (G4double kinEnergy, size_t idxRegion) const inline
Definition at line 505 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 505 of file G4VEmProcess.hh
References modelManager, and G4EmModelManager::SelectModel().
Referenced by G4EmCalculator::FindEmModel().
void G4VEmProcess::SetBuildTableFlag (G4bool val) inline
Definition at line 679 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 679 of file G4VEmProcess.hh
References buildLambdaTable.
Referenced by PhysListEmStandardSSM::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), G4ComptonScattering::G4ComptonScattering(), G4CoulombScattering::G4CoulombScattering(), G4eeToHadrons::G4eeToHadrons(), G4eplusAnnihilation::G4eplusAnnihilation(), G4GammaConversion::G4GammaConversion(), G4JAEAElasticScattering::G4JAEAElasticScattering(), G4NuclearStopping::G4NuclearStopping(), G4PhotoElectricEffect::G4PhotoElectricEffect(), G4PolarizedCompton::G4PolarizedCompton(), G4PolarizedGammaConversion::G4PolarizedGammaConversion(), G4PolarizedPhotoElectricEffect::G4PolarizedPhotoElectricEffect(), G4RayleighScattering::G4RayleighScattering(), G4DNAPositronium::InitialiseProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNADissociation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MicroElecElastic::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4MicroElecInelastic::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), and G4DNAElectronSolvation::InitialiseProcess().
void G4VEmProcess::SetCrossSectionBiasingFactor (G4double f, G4bool flag = true)
Definition at line 1141 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1141 of file G4VEmProcess.cc
References biasFactor, f, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), particle, G4VProcess::verboseLevel, and weightFlag.
Referenced by G4EmExtraParameters::DefineRegParamForEM().
void G4VEmProcess::SetEmMasterProcess (const G4VEmProcess * ptr) inline
Definition at line 744 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 744 of file G4VEmProcess.hh
References masterProc.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable().
void G4VEmProcess::SetEmModel (G4VEmModel * ptr, G4int index = 0)
Definition at line 205 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 205 of file G4VEmProcess.cc
References emModels.
Referenced by PhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4EmDNAPhysicsActivator::DeactivateNuclearStopping(), G4EmModelActivator::FindOrAddProcess(), G4eplusPolarizedAnnihilation::G4eplusPolarizedAnnihilation(), G4DNADissociation::InitialiseProcess(), G4DNAPositronium::InitialiseProcess(), G4DNARotExcitation::InitialiseProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MicroElecElastic::InitialiseProcess(), G4MuElecElastic::InitialiseProcess(), G4RayleighScattering::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4MicroElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4JAEAElasticScattering::InitialiseProcess(), G4eeToHadrons::InitialiseProcess(), G4DNAElectronSolvation::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4eplusAnnihilation::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4NuclearStopping::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), and G4PhotoElectricEffect::InitialiseProcess().
void G4VEmProcess::SetIntegral (G4bool val) inline
Definition at line 665 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 665 of file G4VEmProcess.hh
References integral.
Referenced by G4CoulombScattering::G4CoulombScattering(), G4eeToHadrons::G4eeToHadrons(), and G4eplusAnnihilation::G4eplusAnnihilation().
void G4VEmProcess::SetLambdaBinning (G4int nbins)
Definition at line 1204 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1204 of file G4VEmProcess.cc
References actBinning, e, n, nLambdaBins, and PrintWarning().
Referenced by G4GammaConversion::G4GammaConversion(), and G4PolarizedGammaConversion::G4PolarizedGammaConversion().
void G4VEmProcess::SetMaxKinEnergy (G4double e)
Definition at line 1229 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1229 of file G4VEmProcess.cc
References actMaxKinEnergy, e, G4Log(), G4lrint(), maxKinEnergy, minKinEnergy, nLambdaBins, PrintWarning(), and TeV.
Referenced by G4EmLivermorePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), and G4EmStandardPhysicsWVI::ConstructProcess().
void G4VEmProcess::SetMinKinEnergy (G4double e)
Definition at line 1217 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1217 of file G4VEmProcess.cc
References actMinKinEnergy, e, eV, G4Log(), G4lrint(), maxKinEnergy, minKinEnergy, nLambdaBins, and PrintWarning().
Referenced by G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4GammaConversion::G4GammaConversion(), G4PolarizedGammaConversion::G4PolarizedGammaConversion(), and G4GammaConversion::InitialiseProcess().
void G4VEmProcess::SetMinKinEnergyPrim (G4double e)
Definition at line 1241 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 1241 of file G4VEmProcess.cc
References e, G4EmParameters::MaxKinEnergy(), G4EmParameters::MinKinEnergy(), minKinEnergyPrim, PrintWarning(), and theParameters.
Referenced by G4ComptonScattering::G4ComptonScattering(), G4JAEAElasticScattering::G4JAEAElasticScattering(), G4PhotoElectricEffect::G4PhotoElectricEffect(), G4PolarizedCompton::G4PolarizedCompton(), and G4RayleighScattering::G4RayleighScattering().
void G4VEmProcess::SetParticle (const G4ParticleDefinition * p) inline protected
Definition at line 693 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 693 of file G4VEmProcess.hh
References currentParticle, and particle.
Referenced by G4GammaGeneralProcess::G4GammaGeneralProcess(), G4eeToHadrons::InitialiseProcess(), G4GammaGeneralProcess::PreparePhysicsTable(), and PreparePhysicsTable().
void G4VEmProcess::SetSecondaryParticle (const G4ParticleDefinition * p) inline protected
Definition at line 701 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 701 of file G4VEmProcess.hh
References secondaryParticle.
Referenced by G4ComptonScattering::G4ComptonScattering(), G4CoulombScattering::G4CoulombScattering(), G4eeToHadrons::G4eeToHadrons(), G4eplusAnnihilation::G4eplusAnnihilation(), G4GammaConversion::G4GammaConversion(), G4PhotoElectricEffect::G4PhotoElectricEffect(), G4PolarizedCompton::G4PolarizedCompton(), G4PolarizedGammaConversion::G4PolarizedGammaConversion(), and G4PolarizedPhotoElectricEffect::G4PolarizedPhotoElectricEffect().
void G4VEmProcess::SetSplineFlag (G4bool val) inline protected
Definition at line 715 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 715 of file G4VEmProcess.hh
References actSpline, and splineFlag.
Referenced by G4ComptonScattering::G4ComptonScattering(), G4JAEAElasticScattering::G4JAEAElasticScattering(), G4PolarizedCompton::G4PolarizedCompton(), and G4RayleighScattering::G4RayleighScattering().
void G4VEmProcess::SetStartFromNullFlag (G4bool val) inline protected
Definition at line 708 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 708 of file G4VEmProcess.hh
References startFromNull.
Referenced by G4ComptonScattering::G4ComptonScattering(), G4CoulombScattering::G4CoulombScattering(), G4eplusAnnihilation::G4eplusAnnihilation(), G4GammaConversion::G4GammaConversion(), G4JAEAElasticScattering::G4JAEAElasticScattering(), G4PolarizedCompton::G4PolarizedCompton(), G4RayleighScattering::G4RayleighScattering(), and G4CoulombScattering::InitialiseProcess().
void G4VEmProcess::StartTracking (G4Track * track) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4GammaGeneralProcess.
Definition at line 604 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 604 of file G4VEmProcess.cc
References biasFlag, biasManager, currentParticle, DBL_MAX, G4Track::GetParentID(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetPDGMass(), isIon, massRatio, mfpKinEnergy, source.hepunit::proton_mass_c2, G4EmBiasingManager::ResetForcedInteraction(), and G4VProcess::theNumberOfInteractionLengthLeft.
G4bool G4VEmProcess::StorePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii = false) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4GammaGeneralProcess.
Definition at line 888 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 888 of file G4VEmProcess.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetPhysicsTableFileName(), G4VProcess::GetProcessName(), isTheMaster, particle, G4PhysicsTable::StorePhysicsTable(), theLambdaTable, and theLambdaTablePrim.
Referenced by G4GammaGeneralProcess::StorePhysicsTable().
void G4VEmProcess::StreamInfo (std::ostream & outFile, const G4ParticleDefinition & part, G4bool rst = false) const private
Definition at line 531 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 531 of file G4VEmProcess.cc
References applyCuts, biasFactor, buildLambdaTable, G4EmModelManager::DumpModelList(), emax, CEMC_TOWER::emin, G4PhysicsVector::Energy(), G4BestUnit, G4endl, G4lrint(), G4PhysicsVector::GetMaxEnergy(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), G4PhysicsVector::GetVectorLength(), integral, BTOF::length, G4PhysicsTable::length(), maxKinEnergy, minKinEnergy, minKinEnergyPrim, modelManager, particle, splineFlag, StreamProcessInfo(), theLambdaTable, theLambdaTablePrim, v, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), and ProcessDescription().
virtual void G4VEmProcess::StreamProcessInfo (std::ostream &) const inline protected virtual
Reimplemented in G4eplusAnnihilation, G4eeToHadrons, and G4CoulombScattering.
Definition at line 95 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 95 of file G4VEmProcess.hh
Referenced by StreamInfo().
void G4VEmProcess::UpdateEmModel (const G4String & nam, G4double emin, G4double emax)
Definition at line 220 of file G4VEmProcess.cc.
View newest version in sPHENIX GitHub at line 220 of file G4VEmProcess.cc
References modelManager, and G4EmModelManager::UpdateEmModel().
Member Data Documentation
G4bool G4VEmProcess::actBinning private
Definition at line 383 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 383 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), G4VEmProcess(), and SetLambdaBinning().
G4bool G4VEmProcess::actMaxKinEnergy private
Definition at line 382 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 382 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), PreparePhysicsTable(), and SetMaxKinEnergy().
G4bool G4VEmProcess::actMinKinEnergy private
Definition at line 381 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 381 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), PreparePhysicsTable(), and SetMinKinEnergy().
G4bool G4VEmProcess::actSpline private
Definition at line 384 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 384 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), PreparePhysicsTable(), and SetSplineFlag().
G4bool G4VEmProcess::applyCuts private
Definition at line 378 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 378 of file G4VEmProcess.hh
Referenced by ApplyCuts(), PostStepDoIt(), PreparePhysicsTable(), and StreamInfo().
G4int G4VEmProcess::augerID protected
Definition at line 410 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 410 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
size_t G4VEmProcess::basedCoupleIndex protected
Definition at line 405 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 405 of file G4VEmProcess.hh
Referenced by G4GammaGeneralProcess::ComputeGeneralLambda(), DefineMaterial(), G4VEmProcess(), GetLambdaFromTable(), GetLambdaFromTablePrim(), G4GammaGeneralProcess::GetProbability(), and G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength().
const G4Material* G4VEmProcess::baseMaterial private
Definition at line 430 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 430 of file G4VEmProcess.hh
Referenced by ComputeCurrentLambda(), DefineMaterial(), and G4VEmProcess().
G4double G4VEmProcess::biasFactor private
Definition at line 374 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 374 of file G4VEmProcess.hh
Referenced by CrossSectionBiasingFactor(), DefineMaterial(), G4VEmProcess(), PostStepDoIt(), SetCrossSectionBiasingFactor(), and StreamInfo().
G4bool G4VEmProcess::biasFlag private
Definition at line 433 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 433 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and StartTracking().
G4int G4VEmProcess::biasID protected
Definition at line 411 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 411 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
G4EmBiasingManager* G4VEmProcess::biasManager protected
Definition at line 394 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 394 of file G4VEmProcess.hh
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), StartTracking(), and ~G4VEmProcess().
G4bool G4VEmProcess::buildLambdaTable private
Definition at line 346 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 346 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), CrossSectionPerVolume(), PreparePhysicsTable(), RetrievePhysicsTable(), SetBuildTableFlag(), and StreamInfo().
const G4MaterialCutsCouple* G4VEmProcess::currentCouple protected
Definition at line 399 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 399 of file G4VEmProcess.hh
Referenced by Clear(), DefineMaterial(), MaterialCutsCouple(), PostStepDoIt(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PreparePhysicsTable(), G4GammaGeneralProcess::SampleSecondaries(), SelectModel(), and G4GammaGeneralProcess::TotalCrossSectionPerVolume().
size_t G4VEmProcess::currentCoupleIndex protected
Definition at line 404 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 404 of file G4VEmProcess.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCurrentLambda(), ComputeIntegralLambda(), CrossSectionPerVolume(), CurrentMaterialCutsCoupleIndex(), CurrentSetup(), DefineMaterial(), G4VEmProcess(), GetElectronEnergyCut(), GetGammaEnergyCut(), PostStepDoIt(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), and PostStepGetPhysicalInteractionLength().
const G4Material* G4VEmProcess::currentMaterial protected
Definition at line 400 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 400 of file G4VEmProcess.hh
Referenced by CrossSectionPerVolume(), DefineMaterial(), G4VEmProcess(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PreparePhysicsTable(), and G4GammaGeneralProcess::StartTracking().
G4VEmModel* G4VEmProcess::currentModel private
Definition at line 424 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 424 of file G4VEmProcess.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCurrentLambda(), CrossSectionPerVolume(), GetCurrentElement(), GetCurrentLambda(), GetCurrentModel(), GetTargetElement(), GetTargetIsotope(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), and SelectModel().
const G4ParticleDefinition* G4VEmProcess::currentParticle private
Definition at line 427 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 427 of file G4VEmProcess.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCurrentLambda(), CrossSectionPerVolume(), PostStepDoIt(), SetParticle(), and StartTracking().
std::vector<G4VEmModel*> G4VEmProcess::emModels private
Definition at line 350 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 350 of file G4VEmProcess.hh
Referenced by EmModel(), and SetEmModel().
G4double G4VEmProcess::fFactor private
Definition at line 432 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 432 of file G4VEmProcess.hh
Referenced by ComputeIntegralLambda(), CrossSectionPerVolume(), DefineMaterial(), G4VEmProcess(), GetCurrentLambda(), and RecalculateLambda().
G4int G4VEmProcess::fluoID protected
Definition at line 409 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 409 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
G4ParticleChangeForGamma G4VEmProcess::fParticleChange protected
Definition at line 397 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 397 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), GetParticleChange(), G4GammaGeneralProcess::PostStepDoIt(), and PostStepDoIt().
size_t G4VEmProcess::idxLambda private
Definition at line 359 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 359 of file G4VEmProcess.hh
Referenced by Clear(), DefineMaterial(), G4VEmProcess(), and GetLambdaFromTable().
size_t G4VEmProcess::idxLambdaPrim private
Definition at line 360 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 360 of file G4VEmProcess.hh
Referenced by Clear(), DefineMaterial(), G4VEmProcess(), and GetLambdaFromTablePrim().
G4bool G4VEmProcess::integral private
Definition at line 377 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 377 of file G4VEmProcess.hh
Referenced by IsIntegral(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), SetIntegral(), and StreamInfo().
G4bool G4VEmProcess::isIon private
Definition at line 385 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 385 of file G4VEmProcess.hh
Referenced by PreparePhysicsTable(), and StartTracking().
G4bool G4VEmProcess::isTheMaster protected
Definition at line 413 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 413 of file G4VEmProcess.hh
Referenced by G4GammaGeneralProcess::BuildPhysicsTable(), BuildPhysicsTable(), G4GammaGeneralProcess::InitialiseProcess(), G4GammaGeneralProcess::PreparePhysicsTable(), PreparePhysicsTable(), G4GammaGeneralProcess::StorePhysicsTable(), StorePhysicsTable(), G4GammaGeneralProcess::~G4GammaGeneralProcess(), and ~G4VEmProcess().
G4double G4VEmProcess::lambdaFactor private
Definition at line 372 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 372 of file G4VEmProcess.hh
Referenced by ComputeIntegralLambda(), G4VEmProcess(), and PreparePhysicsTable().
G4LossTableManager* G4VEmProcess::lManager protected
Definition at line 391 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 391 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4VEmProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4GammaGeneralProcess::PreparePhysicsTable(), PreparePhysicsTable(), and ~G4VEmProcess().
G4double G4VEmProcess::logLambdaFactor private
Definition at line 373 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 373 of file G4VEmProcess.hh
Referenced by ComputeIntegralLambda(), G4VEmProcess(), and PreparePhysicsTable().
G4int G4VEmProcess::mainSecondaries protected
Definition at line 407 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 407 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4eplusAnnihilation::G4eplusAnnihilation(), G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
G4double G4VEmProcess::massRatio private
Definition at line 375 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 375 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and StartTracking().
const G4VEmProcess* G4VEmProcess::masterProc private
Definition at line 422 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 422 of file G4VEmProcess.hh
Referenced by BuildPhysicsTable(), and SetEmMasterProcess().
G4double G4VEmProcess::maxKinEnergy private
Definition at line 371 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 371 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), G4VEmProcess(), LambdaPhysicsVector(), MaxKinEnergy(), PreparePhysicsTable(), RetrievePhysicsTable(), SetMaxKinEnergy(), SetMinKinEnergy(), and StreamInfo().
G4double G4VEmProcess::mfpKinEnergy protected
Definition at line 415 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 415 of file G4VEmProcess.hh
Referenced by ComputeIntegralLambda(), DefineMaterial(), G4VEmProcess(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4double G4VEmProcess::minKinEnergy private
Definition at line 369 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 369 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), G4VEmProcess(), LambdaPhysicsVector(), MinKinEnergy(), PreparePhysicsTable(), SetMaxKinEnergy(), SetMinKinEnergy(), and StreamInfo().
G4double G4VEmProcess::minKinEnergyPrim private
Definition at line 370 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 370 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), G4VEmProcess(), GetCurrentLambda(), PreparePhysicsTable(), RetrievePhysicsTable(), SetMinKinEnergyPrim(), and StreamInfo().
G4EmModelManager* G4VEmProcess::modelManager private
Definition at line 342 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 342 of file G4VEmProcess.hh
Referenced by AddEmModel(), BuildLambdaTable(), BuildPhysicsTable(), G4VEmProcess(), GetModelByIndex(), GetNumberOfModels(), GetNumberOfRegionModels(), GetRegionModel(), PreparePhysicsTable(), SelectModel(), SelectModelForMaterial(), StreamInfo(), UpdateEmModel(), and ~G4VEmProcess().
G4int G4VEmProcess::nLambdaBins private
Definition at line 367 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 367 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), G4VEmProcess(), LambdaBinning(), LambdaPhysicsVector(), SetLambdaBinning(), SetMaxKinEnergy(), and SetMinKinEnergy().
G4int G4VEmProcess::numberOfModels private
Definition at line 351 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 351 of file G4VEmProcess.hh
Referenced by BuildPhysicsTable(), PreparePhysicsTable(), and SelectModel().
const G4ParticleDefinition* G4VEmProcess::particle private
Definition at line 426 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 426 of file G4VEmProcess.hh
Referenced by ActivateForcedInteraction(), BuildLambdaTable(), BuildPhysicsTable(), FindLambdaMax(), Particle(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), SetCrossSectionBiasingFactor(), SetParticle(), StorePhysicsTable(), and StreamInfo().
G4double G4VEmProcess::preStepKinEnergy protected
Definition at line 416 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 416 of file G4VEmProcess.hh
Referenced by G4GammaGeneralProcess::ComputeGeneralLambda(), DefineMaterial(), G4VEmProcess(), G4GammaGeneralProcess::GetProbability(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::SampleSecondaries(), and G4GammaGeneralProcess::TotalCrossSectionPerVolume().
G4double G4VEmProcess::preStepLambda protected
Definition at line 418 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 418 of file G4VEmProcess.hh
Referenced by Clear(), ComputeIntegralLambda(), G4VEmProcess(), G4GammaGeneralProcess::PostStepDoIt(), PostStepDoIt(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), PostStepGetPhysicalInteractionLength(), and G4GammaGeneralProcess::PreparePhysicsTable().
G4double G4VEmProcess::preStepLogKinEnergy protected
Definition at line 417 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 417 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), and PostStepGetPhysicalInteractionLength().
G4int G4VEmProcess::secID protected
Definition at line 408 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 408 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
const G4ParticleDefinition* G4VEmProcess::secondaryParticle private
Definition at line 344 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 344 of file G4VEmProcess.hh
Referenced by ActivateSecondaryBiasing(), PreparePhysicsTable(), SecondaryParticle(), and SetSecondaryParticle().
std::vector<G4DynamicParticle*> G4VEmProcess::secParticles protected
Definition at line 398 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 398 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), and PostStepDoIt().
G4bool G4VEmProcess::splineFlag private
Definition at line 380 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 380 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), PreparePhysicsTable(), SetSplineFlag(), and StreamInfo().
G4bool G4VEmProcess::startFromNull private
Definition at line 379 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 379 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), and SetStartFromNullFlag().
std::vector<G4double> G4VEmProcess::theCrossSectionMax private
Definition at line 357 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 357 of file G4VEmProcess.hh
Referenced by ComputeIntegralLambda(), FindLambdaMax(), and PreparePhysicsTable().
const std::vector<G4double>* G4VEmProcess::theCuts private
Definition at line 362 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 362 of file G4VEmProcess.hh
Referenced by ComputeCurrentLambda(), G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
const std::vector<G4double>* G4VEmProcess::theCutsElectron private
Definition at line 364 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 364 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), GetElectronEnergyCut(), PostStepDoIt(), and PreparePhysicsTable().
const std::vector<G4double>* G4VEmProcess::theCutsGamma private
Definition at line 363 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 363 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), GetGammaEnergyCut(), PostStepDoIt(), and PreparePhysicsTable().
const std::vector<G4double>* G4VEmProcess::theCutsPositron private
Definition at line 365 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 365 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), PostStepDoIt(), and PreparePhysicsTable().
G4EmDataHandler* G4VEmProcess::theData private
Definition at line 423 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 423 of file G4VEmProcess.hh
Referenced by PreparePhysicsTable(), and ~G4VEmProcess().
const std::vector<G4double>* G4VEmProcess::theDensityFactor protected
Definition at line 401 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 401 of file G4VEmProcess.hh
Referenced by G4VEmProcess().
const std::vector<G4int>* G4VEmProcess::theDensityIdx protected
Definition at line 402 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 402 of file G4VEmProcess.hh
Referenced by G4VEmProcess().
const G4ParticleDefinition* G4VEmProcess::theElectron protected
Definition at line 396 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 396 of file G4VEmProcess.hh
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess(), and PostStepDoIt().
std::vector<G4double> G4VEmProcess::theEnergyOfCrossSectionMax private
Definition at line 356 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 356 of file G4VEmProcess.hh
Referenced by ComputeIntegralLambda(), FindLambdaMax(), and PreparePhysicsTable().
const G4ParticleDefinition* G4VEmProcess::theGamma protected
Definition at line 395 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 395 of file G4VEmProcess.hh
Referenced by G4GammaGeneralProcess::G4GammaGeneralProcess(), G4VEmProcess(), and PostStepDoIt().
G4PhysicsTable* G4VEmProcess::theLambdaTable private
Definition at line 354 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 354 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), FindLambdaMax(), GetCurrentLambda(), GetLambdaFromTable(), LambdaTable(), PreparePhysicsTable(), RetrievePhysicsTable(), StorePhysicsTable(), and StreamInfo().
G4PhysicsTable* G4VEmProcess::theLambdaTablePrim private
Definition at line 355 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 355 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), GetLambdaFromTablePrim(), LambdaTablePrim(), PreparePhysicsTable(), RetrievePhysicsTable(), StorePhysicsTable(), and StreamInfo().
G4EmParameters* G4VEmProcess::theParameters protected
Definition at line 392 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 392 of file G4VEmProcess.hh
Referenced by BuildLambdaTable(), G4VEmProcess(), G4GammaGeneralProcess::InitialiseProcess(), LambdaPhysicsVector(), PolarAngleLimit(), G4GammaGeneralProcess::PreparePhysicsTable(), PreparePhysicsTable(), PrintWarning(), RetrievePhysicsTable(), and SetMinKinEnergyPrim().
const G4ParticleDefinition* G4VEmProcess::thePositron private
Definition at line 343 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 343 of file G4VEmProcess.hh
Referenced by G4VEmProcess(), and PostStepDoIt().
G4bool G4VEmProcess::weightFlag private
Definition at line 434 of file G4VEmProcess.hh.
View newest version in sPHENIX GitHub at line 434 of file G4VEmProcess.hh
Referenced by ActivateForcedInteraction(), G4VEmProcess(), PostStepDoIt(), and SetCrossSectionBiasingFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmProcess.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4VEmProcess.cc