ECCE @ EIC Software: G4MolecularDissociationTable Class Reference
G4MolecularDissociationTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularDissociationTable.hh>
Public Member Functions
G4MolecularDissociationTable ()
~G4MolecularDissociationTable ()
G4MolecularDissociationTable (const G4MolecularDissociationTable &)
G4MolecularDissociationTable & operator= (const G4MolecularDissociationTable &right)
void AddChannel (const G4MolecularConfiguration *molConf, const G4MolecularDissociationChannel *channel)
void CheckDataConsistency () const
const std::vector< const
G4MolecularDissociationChannel * > * GetDecayChannels (const G4MolecularConfiguration *) const
const std::vector< const
G4MolecularDissociationChannel * > * GetDecayChannels (const G4String &excitedStateLabel) const
void Serialize (std::ostream &)
Private Attributes
G4DNA::ChannelMap fDissociationChannels
Detailed Description
Class Description G4MolecularDecayTable operates as a container of deexcitation modes for excited or ionized molecules
Definition at line 78 of file G4MolecularDissociationTable.hh.
View newest version in sPHENIX GitHub at line 78 of file G4MolecularDissociationTable.hh
Constructor & Destructor Documentation
G4MolecularDissociationTable::G4MolecularDissociationTable ()
Definition at line 46 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 46 of file G4MolecularDissociationTable.cc
G4MolecularDissociationTable::~G4MolecularDissociationTable ()
Definition at line 53 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 53 of file G4MolecularDissociationTable.cc
References int().
G4MolecularDissociationTable::G4MolecularDissociationTable (const G4MolecularDissociationTable & right)
Definition at line 80 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 80 of file G4MolecularDissociationTable.cc
References right.
Member Function Documentation
void G4MolecularDissociationTable::AddChannel (const G4MolecularConfiguration * molConf, const G4MolecularDissociationChannel * channel)
Definition at line 132 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 132 of file G4MolecularDissociationTable.cc
Referenced by G4MoleculeDefinition::AddDecayChannel().
void G4MolecularDissociationTable::CheckDataConsistency () const
Definition at line 140 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 140 of file G4MolecularDissociationTable.cc
References G4INCL::ClusterDecay::decay(), FatalErrorInArgument, G4Exception(), G4MolecularDissociationChannel::GetProbability(), max, and sum.
const vector< const G4MolecularDissociationChannel * > * G4MolecularDissociationTable::GetDecayChannels (const G4MolecularConfiguration * conf) const
Definition at line 99 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 99 of file G4MolecularDissociationTable.cc
Referenced by G4MoleculeDefinition::GetDecayChannels().
const vector< const G4MolecularDissociationChannel * > * G4MolecularDissociationTable::GetDecayChannels (const G4String & excitedStateLabel) const
Definition at line 109 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 109 of file G4MolecularDissociationTable.cc
References it.
G4MolecularDissociationTable & G4MolecularDissociationTable::operator= (const G4MolecularDissociationTable & right)
Definition at line 88 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 88 of file G4MolecularDissociationTable.cc
References fDissociationChannels.
void G4MolecularDissociationTable::Serialize (std::ostream &)
Definition at line 176 of file G4MolecularDissociationTable.cc.
View newest version in sPHENIX GitHub at line 176 of file G4MolecularDissociationTable.cc
Member Data Documentation
G4DNA::ChannelMap G4MolecularDissociationTable::fDissociationChannels private
Definition at line 111 of file G4MolecularDissociationTable.hh.
View newest version in sPHENIX GitHub at line 111 of file G4MolecularDissociationTable.hh
Referenced by operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularDissociationTable.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4MolecularDissociationTable.cc