ECCE @ EIC Software: G4IonisParamElm Class Reference
G4IonisParamElm Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4IonisParamElm.hh>
Public Member Functions
G4IonisParamElm (G4double Z)
~G4IonisParamElm ()
G4double GetZ () const
G4double GetZ3 () const
G4double GetZZ3 () const
G4double GetlogZ3 () const
G4double GetTau0 () const
G4double GetTaul () const
G4double GetAlow () const
G4double GetBlow () const
G4double GetClow () const
G4double GetMeanExcitationEnergy () const
G4double GetFermiVelocity () const
G4double GetLFactor () const
G4double * GetShellCorrectionVector () const
G4IonisParamElm (__void__ &)
Private Member Functions
G4IonisParamElm & operator= (const G4IonisParamElm &)=delete
G4bool operator== (const G4IonisParamElm &) const =delete
G4bool operator!= (const G4IonisParamElm &) const =delete
G4IonisParamElm (G4IonisParamElm &)=delete
Private Attributes
G4double fZ
G4double fZ3
G4double fZZ3
G4double flogZ3
G4double fTau0
G4double fTaul
G4double fBetheBlochLow
G4double fAlow
G4double fBlow
G4double fClow
G4double fMeanExcitationEnergy
G4double * fShellCorrectionVector
G4double fVFermi
G4double fLFactor
Detailed Description
Definition at line 50 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 50 of file G4IonisParamElm.hh
Constructor & Destructor Documentation
G4IonisParamElm::G4IonisParamElm (G4double Z)
Definition at line 51 of file G4IonisParamElm.cc.
View newest version in sPHENIX GitHub at line 51 of file G4IonisParamElm.cc
References source.hepunit::electron_mass_c2, eV, fAlow, FatalException, fBetheBlochLow, fBlow, fClow, fLFactor, flogZ3, fMeanExcitationEnergy, fShellCorrectionVector, fTau0, fTaul, fVFermi, fZ, fZ3, fZZ3, G4Exception(), G4lrint(), G4Pow::GetInstance(), G4NistManager::GetMeanIonisationEnergy(), G4NistManager::Instance(), G4Pow::logZ(), MeV, source.hepunit::proton_mass_c2, source.hepunit::twopi_mc2_rcl2, w, Z, and G4Pow::Z13().
G4IonisParamElm::~G4IonisParamElm ()
Definition at line 149 of file G4IonisParamElm.cc.
View newest version in sPHENIX GitHub at line 149 of file G4IonisParamElm.cc
References fShellCorrectionVector.
G4IonisParamElm::G4IonisParamElm (__void__ &)
Definition at line 140 of file G4IonisParamElm.cc.
View newest version in sPHENIX GitHub at line 140 of file G4IonisParamElm.cc
References fAlow, fBetheBlochLow, fBlow, fClow, fLFactor, flogZ3, fMeanExcitationEnergy, fTau0, fTaul, fVFermi, fZ, fZ3, and fZZ3.
G4IonisParamElm::G4IonisParamElm (G4IonisParamElm &) private delete
Member Function Documentation
G4double G4IonisParamElm::GetAlow () const inline
Definition at line 69 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 69 of file G4IonisParamElm.hh
References fAlow.
G4double G4IonisParamElm::GetBlow () const inline
Definition at line 70 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 70 of file G4IonisParamElm.hh
References fBlow.
G4double G4IonisParamElm::GetClow () const inline
Definition at line 71 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 71 of file G4IonisParamElm.hh
References fClow.
G4double G4IonisParamElm::GetFermiVelocity () const inline
Definition at line 77 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 77 of file G4IonisParamElm.hh
References fVFermi.
Referenced by G4IonisParamMat::ComputeIonParameters().
G4double G4IonisParamElm::GetLFactor () const inline
Definition at line 78 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 78 of file G4IonisParamElm.hh
References fLFactor.
Referenced by G4IonisParamMat::ComputeIonParameters().
G4double G4IonisParamElm::GetlogZ3 () const inline
Definition at line 62 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 62 of file G4IonisParamElm.hh
References flogZ3.
Referenced by G4BetheHeitlerModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), and G4BetheHeitlerModel::SampleSecondaries().
G4double G4IonisParamElm::GetMeanExcitationEnergy () const inline
Definition at line 74 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 74 of file G4IonisParamElm.hh
References fMeanExcitationEnergy.
Referenced by G4IonisParamMat::ComputeMeanParameters().
G4double* G4IonisParamElm::GetShellCorrectionVector () const inline
Definition at line 80 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 80 of file G4IonisParamElm.hh
References fShellCorrectionVector.
G4double G4IonisParamElm::GetTau0 () const inline
Definition at line 64 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 64 of file G4IonisParamElm.hh
References fTau0.
G4double G4IonisParamElm::GetTaul () const inline
Definition at line 67 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 67 of file G4IonisParamElm.hh
References fTaul.
G4double G4IonisParamElm::GetZ () const inline
Definition at line 59 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 59 of file G4IonisParamElm.hh
References fZ.
G4double G4IonisParamElm::GetZ3 () const inline
Definition at line 60 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 60 of file G4IonisParamElm.hh
References fZ3.
Referenced by G4PairProductionRelModel::InitialiseElementData(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), and G4BetheHeitlerModel::SampleSecondaries().
G4double G4IonisParamElm::GetZZ3 () const inline
Definition at line 61 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 61 of file G4IonisParamElm.hh
References fZZ3.
G4bool G4IonisParamElm::operator!= (const G4IonisParamElm &) const private delete
G4IonisParamElm& G4IonisParamElm::operator= (const G4IonisParamElm &) private delete
G4bool G4IonisParamElm::operator== (const G4IonisParamElm &) const private delete
Member Data Documentation
G4double G4IonisParamElm::fAlow private
Definition at line 108 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 108 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetAlow().
G4double G4IonisParamElm::fBetheBlochLow private
Definition at line 107 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 107 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm().
G4double G4IonisParamElm::fBlow private
Definition at line 108 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 108 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetBlow().
G4double G4IonisParamElm::fClow private
Definition at line 108 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 108 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetClow().
G4double G4IonisParamElm::fLFactor private
Definition at line 114 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 114 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetLFactor().
G4double G4IonisParamElm::flogZ3 private
Definition at line 101 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 101 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetlogZ3().
G4double G4IonisParamElm::fMeanExcitationEnergy private
Definition at line 109 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 109 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetMeanExcitationEnergy().
G4double* G4IonisParamElm::fShellCorrectionVector private
Definition at line 110 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 110 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), GetShellCorrectionVector(), and ~G4IonisParamElm().
G4double G4IonisParamElm::fTau0 private
Definition at line 105 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 105 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetTau0().
G4double G4IonisParamElm::fTaul private
Definition at line 106 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 106 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetTaul().
G4double G4IonisParamElm::fVFermi private
Definition at line 113 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 113 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetFermiVelocity().
G4double G4IonisParamElm::fZ private
Definition at line 98 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 98 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetZ().
G4double G4IonisParamElm::fZ3 private
Definition at line 99 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 99 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetZ3().
G4double G4IonisParamElm::fZZ3 private
Definition at line 100 of file G4IonisParamElm.hh.
View newest version in sPHENIX GitHub at line 100 of file G4IonisParamElm.hh
Referenced by G4IonisParamElm(), and GetZZ3().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4IonisParamElm.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4IonisParamElm.cc