ECCE @ EIC Software: DMXStackingAction Class Reference
DMXStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXStackingAction.hh>
Public Member Functions
DMXStackingAction ()
virtual ~DMXStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
void SetKillGammasFlag (G4bool val)
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Public Attributes
DMXStackingActionMessenger * theMessenger
Private Attributes
G4bool killGammasFlag
G4Navigator * gNavigator
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 53 of file DMXStackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file DMXStackingAction.hh
Constructor & Destructor Documentation
DMXStackingAction::DMXStackingAction ()
Definition at line 57 of file DMXStackingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file DMXStackingAction.cc
References G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetTransportationManager(), gNavigator, killGammasFlag, and theMessenger.
DMXStackingAction::~DMXStackingAction () virtual
Definition at line 71 of file DMXStackingAction.cc.
View newest version in sPHENIX GitHub at line 71 of file DMXStackingAction.cc
References theMessenger.
Member Function Documentation
G4ClassificationOfNewTrack DMXStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 78 of file DMXStackingAction.cc.
View newest version in sPHENIX GitHub at line 78 of file DMXStackingAction.cc
References fKill, fWaiting, G4cout, G4endl, G4Gamma::GammaDefinition(), G4Track::GetDefinition(), G4VPhysicalVolume::GetName(), G4Track::GetPosition(), and pos().
void DMXStackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 108 of file DMXStackingAction.cc.
View newest version in sPHENIX GitHub at line 108 of file DMXStackingAction.cc
void DMXStackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 111 of file DMXStackingAction.cc.
View newest version in sPHENIX GitHub at line 111 of file DMXStackingAction.cc
void DMXStackingAction::SetKillGammasFlag (G4bool val) inline
Definition at line 73 of file DMXStackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file DMXStackingAction.hh
References killGammasFlag.
Member Data Documentation
G4Navigator* DMXStackingAction::gNavigator private
Definition at line 70 of file DMXStackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file DMXStackingAction.hh
Referenced by DMXStackingAction().
G4bool DMXStackingAction::killGammasFlag private
Definition at line 68 of file DMXStackingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file DMXStackingAction.hh
Referenced by DMXStackingAction(), and SetKillGammasFlag().
DMXStackingActionMessenger* DMXStackingAction::theMessenger
Definition at line 64 of file DMXStackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file DMXStackingAction.hh
Referenced by DMXStackingAction(), and ~DMXStackingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXStackingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/src/DMXStackingAction.cc