ECCE @ EIC Software: GB06BOptrSplitAndKillByImportance Class Reference
GB06BOptrSplitAndKillByImportance Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB06/include/GB06BOptrSplitAndKillByImportance.hh>
Public Member Functions
GB06BOptrSplitAndKillByImportance (G4String particleToBias, G4String name="SplitAndKillByImportance")
virtual ~GB06BOptrSplitAndKillByImportance ()
virtual void StartRun ()
void SetParallelWorld (G4VPhysicalVolume *parallelWorld)
std::map< G4int, G4int > & GetImportanceMap ()
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartTracking (const G4Track *)
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
Private Attributes
GB06BOptnSplitAndKillByImportance * fSplitAndKillByImportance
const G4ParticleDefinition * fParticleToBias
G4VPhysicalVolume * fParallelWorld
G4int fParallelWorldIndex
const G4BiasingProcessSharedData * fBiasingSharedData
const
G4ParallelGeometriesLimiterProcess * fBiasingLimiterProcess
std::map< G4int, G4int > fImportanceMap
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 60 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 60 of file GB06BOptrSplitAndKillByImportance.hh
Constructor & Destructor Documentation
GB06BOptrSplitAndKillByImportance::GB06BOptrSplitAndKillByImportance (G4String particleToBias, G4String name = "SplitAndKillByImportance")
Definition at line 47 of file GB06BOptrSplitAndKillByImportance.cc.
View newest version in sPHENIX GitHub at line 47 of file GB06BOptrSplitAndKillByImportance.cc
References G4ParticleTable::FindParticle(), fParticleToBias, fSplitAndKillByImportance, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), and JustWarning.
GB06BOptrSplitAndKillByImportance::~GB06BOptrSplitAndKillByImportance () virtual
Definition at line 73 of file GB06BOptrSplitAndKillByImportance.cc.
View newest version in sPHENIX GitHub at line 73 of file GB06BOptrSplitAndKillByImportance.cc
References fSplitAndKillByImportance.
Member Function Documentation
std::map< G4int, G4int >& GB06BOptrSplitAndKillByImportance::GetImportanceMap () inline
Definition at line 103 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 103 of file GB06BOptrSplitAndKillByImportance.hh
References fImportanceMap.
virtual G4VBiasingOperation* GB06BOptrSplitAndKillByImportance::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline final private virtual
Implements G4VBiasingOperator.
Definition at line 84 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 84 of file GB06BOptrSplitAndKillByImportance.hh
G4VBiasingOperation * GB06BOptrSplitAndKillByImportance::ProposeNonPhysicsBiasingOperation (const G4Track * track, const G4BiasingProcessInterface *) final private virtual
Implements G4VBiasingOperator.
Definition at line 104 of file GB06BOptrSplitAndKillByImportance.cc.
View newest version in sPHENIX GitHub at line 104 of file GB06BOptrSplitAndKillByImportance.cc
References fParticleToBias, fSplitAndKillByImportance, and G4Track::GetDefinition().
virtual G4VBiasingOperation* GB06BOptrSplitAndKillByImportance::ProposeOccurenceBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline final private virtual
Implements G4VBiasingOperator.
Definition at line 78 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 78 of file GB06BOptrSplitAndKillByImportance.hh
void GB06BOptrSplitAndKillByImportance::SetParallelWorld (G4VPhysicalVolume * parallelWorld) inline
Definition at line 99 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 99 of file GB06BOptrSplitAndKillByImportance.hh
References fParallelWorld.
void GB06BOptrSplitAndKillByImportance::StartRun () virtual
Reimplemented from G4VBiasingOperator.
Definition at line 80 of file GB06BOptrSplitAndKillByImportance.cc.
View newest version in sPHENIX GitHub at line 80 of file GB06BOptrSplitAndKillByImportance.cc
References fBiasingLimiterProcess, fBiasingSharedData, fImportanceMap, fParallelWorld, fParallelWorldIndex, fParticleToBias, fSplitAndKillByImportance, G4BiasingProcessSharedData::GetParallelGeometriesLimiterProcess(), G4ParallelGeometriesLimiterProcess::GetParallelWorldIndex(), G4ParticleDefinition::GetProcessManager(), G4BiasingProcessInterface::GetSharedData(), and GB06BOptnSplitAndKillByImportance::SetParallelWorldIndex().
Member Data Documentation
const G4ParallelGeometriesLimiterProcess* GB06BOptrSplitAndKillByImportance::fBiasingLimiterProcess private
Definition at line 113 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 113 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by StartRun().
const G4BiasingProcessSharedData* GB06BOptrSplitAndKillByImportance::fBiasingSharedData private
Definition at line 112 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 112 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by StartRun().
std::map< G4int, G4int > GB06BOptrSplitAndKillByImportance::fImportanceMap private
Definition at line 114 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 114 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by GetImportanceMap(), and StartRun().
G4VPhysicalVolume* GB06BOptrSplitAndKillByImportance::fParallelWorld private
Definition at line 110 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 110 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by SetParallelWorld(), and StartRun().
G4int GB06BOptrSplitAndKillByImportance::fParallelWorldIndex private
Definition at line 111 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 111 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by StartRun().
const G4ParticleDefinition* GB06BOptrSplitAndKillByImportance::fParticleToBias private
Definition at line 109 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 109 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by GB06BOptrSplitAndKillByImportance(), ProposeNonPhysicsBiasingOperation(), and StartRun().
GB06BOptnSplitAndKillByImportance* GB06BOptrSplitAndKillByImportance::fSplitAndKillByImportance private
Definition at line 108 of file GB06BOptrSplitAndKillByImportance.hh.
View newest version in sPHENIX GitHub at line 108 of file GB06BOptrSplitAndKillByImportance.hh
Referenced by GB06BOptrSplitAndKillByImportance(), ProposeNonPhysicsBiasingOperation(), StartRun(), and ~GB06BOptrSplitAndKillByImportance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB06/include/GB06BOptrSplitAndKillByImportance.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB06/src/GB06BOptrSplitAndKillByImportance.cc