ECCE @ EIC Software: G4UIcmdWithABool Class Reference
G4UIcmdWithABool Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWithABool.hh>
Public Member Functions
G4UIcmdWithABool (const char *theCommandPath, G4UImessenger *theMessenger)
void SetParameterName (const char *theName, G4bool omittable, G4bool currentAsDefault=false)
void SetDefaultValue (G4bool defVal)
Public Member Functions inherited from G4UIcommand
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
virtual G4int DoIt (G4String parameterList)
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
size_t GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
size_t GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Static Public Member Functions
static G4bool GetNewBoolValue (const char *paramString)
Static Public Member Functions inherited from G4UIcommand
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Additional Inherited Members
Protected Types inherited from G4UIcommand
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Protected Member Functions inherited from G4UIcommand
G4int CheckNewValue (const char *newValue)
Protected Attributes inherited from G4UIcommand
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Detailed Description
Definition at line 44 of file G4UIcmdWithABool.hh.
View newest version in sPHENIX GitHub at line 44 of file G4UIcmdWithABool.hh
Constructor & Destructor Documentation
G4UIcmdWithABool::G4UIcmdWithABool (const char * theCommandPath, G4UImessenger * theMessenger)
Definition at line 33 of file G4UIcmdWithABool.cc.
View newest version in sPHENIX GitHub at line 33 of file G4UIcmdWithABool.cc
Member Function Documentation
G4bool G4UIcmdWithABool::GetNewBoolValue (const char * paramString) static
Definition at line 40 of file G4UIcmdWithABool.cc.
View newest version in sPHENIX GitHub at line 40 of file G4UIcmdWithABool.cc
References G4UIcommand::ConvertToBool().
Referenced by G4GeometryMessenger::SetCheckMode(), G4HepRepMessenger::SetNewValue(), HadrontherapyDetectorMessenger::SetNewValue(), RE06DetectorMessenger::SetNewValue(), StackingMessenger::SetNewValue(), NeutronHPMessenger::SetNewValue(), TrackingMessenger::SetNewValue(), F04RunActionMessenger::SetNewValue(), HadrontherapyPrimaryGeneratorMessenger::SetNewValue(), G4GMocrenMessenger::SetNewValue(), LXeDetectorMessenger::SetNewValue(), G4MatScanMessenger::SetNewValue(), XrayFluoPrimaryGeneratorMessenger::SetNewValue(), WLSRunActionMessenger::SetNewValue(), G4RTMessenger::SetNewValue(), WLSDetectorMessenger::SetNewValue(), G4RadioactivationMessenger::SetNewValue(), G4GeometryMessenger::SetNewValue(), XrayFluoDetectorMessenger::SetNewValue(), G4EmMessenger::SetNewValue(), G4GDMLMessenger::SetNewValue(), XrayFluoPlaneDetectorMessenger::SetNewValue(), GammaRayTelPrimaryGeneratorMessenger::SetNewValue(), XrayFluoAnalysisMessenger::SetNewValue(), G4RadioactiveDecayBaseMessenger::SetNewValue(), CexmcProductionModelMessenger::SetNewValue(), CexmcReconstructorMessenger::SetNewValue(), CexmcRunManagerMessenger::SetNewValue(), CexmcScenePrimitivesMessenger::SetNewValue(), CexmcChargeExchangeReconstructorMessenger::SetNewValue(), G4PolarizationMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4AdjointPhysicsMessenger::SetNewValue(), G4UCNBoundaryProcessMessenger::SetNewValue(), G4OpticalPhysicsMessenger::SetNewValue(), G4EmExtraParametersMessenger::SetNewValue(), G4EmLowEParametersMessenger::SetNewValue(), G4SchedulerMessenger::SetNewValue(), G4EmParametersMessenger::SetNewValue(), G4DeexParametersMessenger::SetNewValue(), CML2MainMessenger::SetNewValue(), G4RunMessenger::SetNewValue(), G4ParticlePropertyMessenger::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), G4RadioactiveDecaymessenger::SetNewValue(), G4DNAChemistryManager::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4GeometryMessenger::SetPushFlag().
void G4UIcmdWithABool::SetDefaultValue (G4bool defVal)
Definition at line 54 of file G4UIcmdWithABool.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UIcmdWithABool.cc
References G4UIcommand::GetParameter(), and G4UIparameter::SetDefaultValue().
Referenced by CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcProductionModelMessenger::CexmcProductionModelMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), DMXEventActionMessenger::DMXEventActionMessenger(), G4DeexParametersMessenger::G4DeexParametersMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4GDMLMessenger::G4GDMLMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4UCNBoundaryProcessMessenger::G4UCNBoundaryProcessMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4VisCommandsTouchable::G4VisCommandsTouchable(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerDefaultHiddenEdge::G4VisCommandViewerDefaultHiddenEdge(), StackingMessenger::StackingMessenger(), StepMaxMessenger::StepMaxMessenger(), TrackingMessenger::TrackingMessenger(), XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), and XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger().
void G4UIcmdWithABool::SetParameterName (const char * theName, G4bool omittable, G4bool currentAsDefault = false)
Definition at line 46 of file G4UIcmdWithABool.cc.
View newest version in sPHENIX GitHub at line 46 of file G4UIcmdWithABool.cc
References G4UIparameter::SetCurrentAsDefault(), G4UIparameter::SetOmittable(), and G4UIparameter::SetParameterName().
Referenced by CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcProductionModelMessenger::CexmcProductionModelMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), DMXEventActionMessenger::DMXEventActionMessenger(), F04RunActionMessenger::F04RunActionMessenger(), G4BlineTracerMessenger::G4BlineTracerMessenger(), G4DeexParametersMessenger::G4DeexParametersMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4GDMLMessenger::G4GDMLMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4ModelCmdApplyBool< M >::G4ModelCmdApplyBool(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4UCNBoundaryProcessMessenger::G4UCNBoundaryProcessMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4VisCommandsTouchable::G4VisCommandsTouchable(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerDefaultHiddenEdge::G4VisCommandViewerDefaultHiddenEdge(), NeutronHPMessenger::NeutronHPMessenger(), RE06DetectorMessenger::RE06DetectorMessenger(), StackingMessenger::StackingMessenger(), StepMaxMessenger::StepMaxMessenger(), TrackingMessenger::TrackingMessenger(), WLSRunActionMessenger::WLSRunActionMessenger(), XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), and XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWithABool.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIcmdWithABool.cc