ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_sampling.cc File Reference
MCGIDI_sampling.cc File Reference
#include <stdlib.h>
#include <cmath>
#include "MCGIDI.h"
Functions
int MCGIDI_sampling_pdfsOfXGivenW_initialize (statusMessageReporting *, MCGIDI_pdfsOfXGivenW *dists)
int MCGIDI_sampling_pdfsOfXGivenW_release (statusMessageReporting *smr, MCGIDI_pdfsOfXGivenW *dists)
int MCGIDI_sampling_pdfsOfX_release (statusMessageReporting *, MCGIDI_pdfOfX *dist)
int MCGIDI_sampling_sampleX_from_pdfsOfXGivenW (MCGIDI_pdfsOfXGivenW *dists, MCGIDI_pdfsOfXGivenW_sampled *sampled, double rngValue)
int MCGIDI_sampling_sampleX_from_pdfOfX (MCGIDI_pdfOfX *dist, MCGIDI_pdfsOfXGivenW_sampled *sampled, double rngValue)
int MCGIDI_sampling_doubleDistribution (statusMessageReporting *smr, MCGIDI_pdfsOfXGivenW *pdfOfWGivenV, MCGIDI_pdfsOfXGivenW *pdfOfXGivenVAndW, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
int MCGIDI_sampling_interpolationValues (statusMessageReporting *smr, ptwXY_interpolation interpolation, double *ws, double y1, double y2, double *y)
double MCGIDI_sampling_ptwXY_getValueAtX (ptwXYPoints *ptwXY, double x1)
Function Documentation
int MCGIDI_sampling_doubleDistribution (statusMessageReporting * smr, MCGIDI_pdfsOfXGivenW * pdfOfWGivenV, MCGIDI_pdfsOfXGivenW * pdfOfXGivenVAndW, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 141 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 141 of file MCGIDI_sampling.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_misc_binarySearch(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_pdfsOfXGivenW_s::numberOfWs, ptwXY_interpolationFlat, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_pdfsOfXGivenW_sampled_s::smr, w, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_pdfsOfXGivenW_s::Ws, x, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_angularEnergy_sampleDistribution(), and MCGIDI_energyAngular_sampleDistribution().
int MCGIDI_sampling_interpolationValues (statusMessageReporting * smr, ptwXY_interpolation interpolation, double * ws, double y1, double y2, double * y)
Definition at line 187 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 187 of file MCGIDI_sampling.cc
References G4Log(), G4Pow::GetInstance(), G4Pow::powA(), ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_sampling_doubleDistribution().
int MCGIDI_sampling_pdfsOfX_release (statusMessageReporting * , MCGIDI_pdfOfX * dist)
Definition at line 41 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 41 of file MCGIDI_sampling.cc
References smr_freeMemory(), and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_energy_release(), and MCGIDI_sampling_pdfsOfXGivenW_release().
int MCGIDI_sampling_pdfsOfXGivenW_initialize (statusMessageReporting * , MCGIDI_pdfsOfXGivenW * dists)
Definition at line 20 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_sampling.cc
Referenced by MCGIDI_sampling_pdfsOfXGivenW_release().
int MCGIDI_sampling_pdfsOfXGivenW_release (statusMessageReporting * smr, MCGIDI_pdfsOfXGivenW * dists)
Definition at line 28 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 28 of file MCGIDI_sampling.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_sampling_pdfsOfX_release(), MCGIDI_sampling_pdfsOfXGivenW_initialize(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, smr_freeMemory(), and MCGIDI_pdfsOfXGivenW_s::Ws.
Referenced by MCGIDI_angular_release(), MCGIDI_angularEnergy_release(), MCGIDI_energy_release(), MCGIDI_energyAngular_release(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
double MCGIDI_sampling_ptwXY_getValueAtX (ptwXYPoints * ptwXY, double x1)
Definition at line 212 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 212 of file MCGIDI_sampling.cc
References nfu_XOutsideDomain, ptwXY_getValueAtX(), ptwXY_getXMax(), ptwXY_getXMin(), and y1.
Referenced by MCGIDI_energy_sampleEnergy(), MCGIDI_energy_sampleWeightedFunctional(), and MCGIDI_product_sampleMultiplicity().
int MCGIDI_sampling_sampleX_from_pdfOfX (MCGIDI_pdfOfX * dist, MCGIDI_pdfsOfXGivenW_sampled * sampled, double rngValue)
Definition at line 98 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 98 of file MCGIDI_sampling.cc
References MCGIDI_pdfOfX_s::cdf, d1, d2, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, iX, MCGIDI_pdfsOfXGivenW_sampled_s::iX1, MCGIDI_misc_binarySearch(), MCGIDI_pdfOfX_s::numberOfXs, MCGIDI_pdfOfX_s::pdf, ptwXY_interpolationFlat, s1, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_setReportError2, smr_unknownID, MCGIDI_pdfsOfXGivenW_sampled_s::x, and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_energy_sampleEnergy(), MCGIDI_sampling_doubleDistribution(), and MCGIDI_sampling_sampleX_from_pdfsOfXGivenW().
int MCGIDI_sampling_sampleX_from_pdfsOfXGivenW (MCGIDI_pdfsOfXGivenW * dists, MCGIDI_pdfsOfXGivenW_sampled * sampled, double rngValue)
Definition at line 49 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 49 of file MCGIDI_sampling.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_pdfsOfXGivenW_sampled_s::frac, G4Log(), G4Pow::GetInstance(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::iW, MCGIDI_pdfsOfXGivenW_sampled_s::iX1, MCGIDI_pdfsOfXGivenW_sampled_s::iX2, MCGIDI_misc_binarySearch(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, G4Pow::powA(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_setReportError2, smr_unknownID, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_pdfsOfXGivenW_s::Ws, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_angular_sampleMu(), MCGIDI_energy_sampleEnergy(), MCGIDI_KalbachMann_sampleEp(), and MCGIDI_sampling_doubleDistribution().