ECCE @ EIC Software: G4Allocator< Type > Class Template Reference
G4Allocator< Type > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4Allocator.hh>
Classes
struct rebind
Public Types
typedef Type value_type
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef Type * pointer
typedef const Type * const_pointer
typedef Type & reference
typedef const Type & const_reference
Public Member Functions
G4Allocator () throw ()
~G4Allocator () throw ()
Type * MallocSingle ()
void FreeSingle (Type *anElement)
void ResetStorage ()
size_t GetAllocatedSize () const
int GetNoPages () const
size_t GetPageSize () const
void IncreasePageSize (unsigned int sz)
const char * GetPoolType () const
template<class U >
G4Allocator (const G4Allocator< U > &right) throw ()
pointer address (reference r) const
const_pointer address (const_reference r) const
pointer allocate (size_type n, void *=0)
void deallocate (pointer p, size_type n)
void construct (pointer p, const Type &val)
void destroy (pointer p)
size_type max_size () const throw ()
Public Member Functions inherited from G4AllocatorBase
G4AllocatorBase ()
virtual ~G4AllocatorBase ()
Public Attributes
G4AllocatorPool mem
Private Attributes
const char * tname
Detailed Description
template<class Type>
class G4Allocator< Type >
Definition at line 66 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 66 of file G4Allocator.hh
Member Typedef Documentation
template<class Type> typedef const Type* G4Allocator< Type >::const_pointer
Definition at line 109 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 109 of file G4Allocator.hh
template<class Type> typedef const Type& G4Allocator< Type >::const_reference
Definition at line 111 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Allocator.hh
template<class Type> typedef ptrdiff_t G4Allocator< Type >::difference_type
Definition at line 107 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 107 of file G4Allocator.hh
template<class Type> typedef Type* G4Allocator< Type >::pointer
Definition at line 108 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 108 of file G4Allocator.hh
template<class Type> typedef Type& G4Allocator< Type >::reference
Definition at line 110 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 110 of file G4Allocator.hh
template<class Type> typedef size_t G4Allocator< Type >::size_type
Definition at line 106 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 106 of file G4Allocator.hh
template<class Type> typedef Type G4Allocator< Type >::value_type
Definition at line 105 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 105 of file G4Allocator.hh
Constructor & Destructor Documentation
template<class Type > G4Allocator< Type >::G4Allocator () throw ()
Definition at line 181 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Allocator.hh
template<class Type > G4Allocator< Type >::~G4Allocator () throw ()
Definition at line 192 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 192 of file G4Allocator.hh
template<class Type> template<class U > G4Allocator< Type >::G4Allocator (const G4Allocator< U > & right) throw () inline
Definition at line 113 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 113 of file G4Allocator.hh
Member Function Documentation
template<class Type> pointer G4Allocator< Type >::address (reference r) const inline
Definition at line 117 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 117 of file G4Allocator.hh
template<class Type> const_pointer G4Allocator< Type >::address (const_reference r) const inline
Definition at line 118 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 118 of file G4Allocator.hh
template<class Type> pointer G4Allocator< Type >::allocate (size_type n, void * = 0) inline
Definition at line 121 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 121 of file G4Allocator.hh
template<class Type> void G4Allocator< Type >::construct (pointer p, const Type & val) inline
Definition at line 143 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 143 of file G4Allocator.hh
template<class Type> void G4Allocator< Type >::deallocate (pointer p, size_type n) inline
Definition at line 132 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 132 of file G4Allocator.hh
template<class Type> void G4Allocator< Type >::destroy (pointer p) inline
Definition at line 145 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 145 of file G4Allocator.hh
template<class Type> void G4Allocator< Type >::FreeSingle (Type * anElement) inline
Definition at line 211 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 211 of file G4Allocator.hh
Referenced by G4Allocator< G4KDNode< PointT > >::deallocate(), ExN04MuonHit::operator delete(), ExN04TrackerHit::operator delete(), H02MuonHit::operator delete(), eRositaTrackerHit::operator delete(), ExN04CalorimeterHit::operator delete(), G4DCofThisEvent::operator delete(), ExN02TrackerHit::operator delete(), RMC01DoubleWithWeightHit::operator delete(), G4TDigiCollection< T >::operator delete(), CexmcTrackPointsStore::operator delete(), CexmcEnergyDepositStore::operator delete(), CexmcTrackPointInfo::operator delete(), and G4KDNodeCopy< PointCopyT >::operator delete().
template<class Type > size_t G4Allocator< Type >::GetAllocatedSize () const inline virtual
Implements G4AllocatorBase.
Definition at line 235 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 235 of file G4Allocator.hh
template<class Type > int G4Allocator< Type >::GetNoPages () const inline virtual
Implements G4AllocatorBase.
Definition at line 245 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 245 of file G4Allocator.hh
template<class Type > size_t G4Allocator< Type >::GetPageSize () const inline virtual
Implements G4AllocatorBase.
Definition at line 255 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 255 of file G4Allocator.hh
template<class Type > const char * G4Allocator< Type >::GetPoolType () const inline virtual
Implements G4AllocatorBase.
Definition at line 276 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 276 of file G4Allocator.hh
template<class Type > void G4Allocator< Type >::IncreasePageSize (unsigned int sz) inline virtual
Implements G4AllocatorBase.
Definition at line 265 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 265 of file G4Allocator.hh
template<class Type > Type * G4Allocator< Type >::MallocSingle () inline
Definition at line 201 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 201 of file G4Allocator.hh
Referenced by G4Allocator< G4KDNode< PointT > >::allocate(), ExN04MuonHit::operator new(), ExN04TrackerHit::operator new(), H02MuonHit::operator new(), eRositaTrackerHit::operator new(), ExN04CalorimeterHit::operator new(), G4DCofThisEvent::operator new(), ExN02TrackerHit::operator new(), RMC01DoubleWithWeightHit::operator new(), CexmcTrackPointsStore::operator new(), G4TDigiCollection< T >::operator new(), CexmcEnergyDepositStore::operator new(), CexmcTrackPointInfo::operator new(), G4KDTree::operator new(), G4KDNode< PointT >::operator new(), and G4KDNodeCopy< PointCopyT >::operator new().
template<class Type> size_type G4Allocator< Type >::max_size () const throw () inline
Definition at line 148 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 148 of file G4Allocator.hh
template<class Type > void G4Allocator< Type >::ResetStorage () inline virtual
Implements G4AllocatorBase.
Definition at line 222 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 222 of file G4Allocator.hh
Member Data Documentation
template<class Type> G4AllocatorPool G4Allocator< Type >::mem
Definition at line 159 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 159 of file G4Allocator.hh
template<class Type> const char* G4Allocator< Type >::tname private
Definition at line 164 of file G4Allocator.hh.
View newest version in sPHENIX GitHub at line 164 of file G4Allocator.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4Allocator.hh