ECCE @ EIC Software: G4BaryonConstructor Class Reference
G4BaryonConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/hadrons/barions/include/G4BaryonConstructor.hh>
Public Member Functions
G4BaryonConstructor ()
~G4BaryonConstructor ()
Static Public Member Functions
static void ConstructParticle ()
Static Protected Member Functions
static void ConstructNucleons ()
static void ConstructStrangeBaryons ()
static void ConstructCharmBaryons ()
static void ConstructBottomBaryons ()
Detailed Description
Definition at line 38 of file G4BaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 38 of file G4BaryonConstructor.hh
Constructor & Destructor Documentation
G4BaryonConstructor::G4BaryonConstructor ()
Definition at line 92 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 92 of file G4BaryonConstructor.cc
G4BaryonConstructor::~G4BaryonConstructor ()
Definition at line 96 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 96 of file G4BaryonConstructor.cc
Member Function Documentation
void G4BaryonConstructor::ConstructBottomBaryons () static protected
Definition at line 151 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 151 of file G4BaryonConstructor.cc
References G4AntiLambdab::AntiLambdabDefinition(), G4AntiOmegabMinus::AntiOmegabMinusDefinition(), G4AntiSigmabMinus::AntiSigmabMinusDefinition(), G4AntiSigmabPlus::AntiSigmabPlusDefinition(), G4AntiSigmabZero::AntiSigmabZeroDefinition(), G4AntiXibMinus::AntiXibMinusDefinition(), G4AntiXibZero::AntiXibZeroDefinition(), G4Lambdab::LambdabDefinition(), G4OmegabMinus::OmegabMinusDefinition(), G4SigmabMinus::SigmabMinusDefinition(), G4SigmabPlus::SigmabPlusDefinition(), G4SigmabZero::SigmabZeroDefinition(), G4XibMinus::XibMinusDefinition(), and G4XibZero::XibZeroDefinition().
Referenced by ConstructParticle().
void G4BaryonConstructor::ConstructCharmBaryons () static protected
Definition at line 133 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 133 of file G4BaryonConstructor.cc
References G4AntiLambdacPlus::AntiLambdacPlusDefinition(), G4AntiOmegacZero::AntiOmegacZeroDefinition(), G4AntiSigmacPlus::AntiSigmacPlusDefinition(), G4AntiSigmacPlusPlus::AntiSigmacPlusPlusDefinition(), G4AntiSigmacZero::AntiSigmacZeroDefinition(), G4AntiXicPlus::AntiXicPlusDefinition(), G4AntiXicZero::AntiXicZeroDefinition(), G4LambdacPlus::LambdacPlusDefinition(), G4OmegacZero::OmegacZeroDefinition(), G4SigmacPlus::SigmacPlusDefinition(), G4SigmacPlusPlus::SigmacPlusPlusDefinition(), G4SigmacZero::SigmacZeroDefinition(), G4XicPlus::XicPlusDefinition(), and G4XicZero::XicZeroDefinition().
Referenced by ConstructParticle().
void G4BaryonConstructor::ConstructNucleons () static protected
Definition at line 109 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 109 of file G4BaryonConstructor.cc
References G4AntiNeutron::AntiNeutronDefinition(), G4AntiProton::AntiProtonDefinition(), G4Neutron::NeutronDefinition(), and G4Proton::ProtonDefinition().
Referenced by ConstructParticle().
void G4BaryonConstructor::ConstructParticle (void) static
Definition at line 101 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 101 of file G4BaryonConstructor.cc
References ConstructBottomBaryons(), ConstructCharmBaryons(), ConstructNucleons(), and ConstructStrangeBaryons().
Referenced by B03PhysicsList::ConstructAllBaryons(), Par02PhysicsList::ConstructBaryons(), XrayTelPhysicsList::ConstructBaryons(), LBE::ConstructMyBaryons(), DMXPhysicsList::ConstructMyHadrons(), EICPhysicsList::ConstructParticle(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), G4ChannelingPhysics::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), Particles::ConstructParticle(), XrayFluoPhysicsList::ConstructParticle(), G4ChargeExchangePhysics::ConstructParticle(), G4HadronDElasticPhysics::ConstructParticle(), G4HadronHElasticPhysics::ConstructParticle(), G4HadronPhysicsQGS_BIC::ConstructParticle(), G4HadronPhysicsFTF_BIC::ConstructParticle(), G4DecayPhysics::ConstructParticle(), G4HadronPhysicsShieldingLEND::ConstructParticle(), G4VHadronPhysics::ConstructParticle(), G4HadronPhysicsFTFP_BERT::ConstructParticle(), G4HadronPhysicsQGSP_BIC::ConstructParticle(), G4HadronPhysicsQGSP_BERT::ConstructParticle(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructParticle(), G4HadronPhysicsShielding::ConstructParticle(), G4HadronElasticPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructParticle(), G4HadronPhysicsINCLXX::ConstructParticle(), G4StoppingPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC_HP::ConstructParticle(), and G4HadronPhysicsFTFQGSP_BERT::ConstructParticle().
void G4BaryonConstructor::ConstructStrangeBaryons () static protected
Definition at line 116 of file G4BaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 116 of file G4BaryonConstructor.cc
References G4AntiLambda::AntiLambdaDefinition(), G4AntiOmegaMinus::AntiOmegaMinusDefinition(), G4AntiSigmaMinus::AntiSigmaMinusDefinition(), G4AntiSigmaPlus::AntiSigmaPlusDefinition(), G4AntiSigmaZero::AntiSigmaZeroDefinition(), G4AntiXiMinus::AntiXiMinusDefinition(), G4AntiXiZero::AntiXiZeroDefinition(), G4Lambda::LambdaDefinition(), G4OmegaMinus::OmegaMinusDefinition(), G4SigmaMinus::SigmaMinusDefinition(), G4SigmaPlus::SigmaPlusDefinition(), G4SigmaZero::SigmaZeroDefinition(), G4XiMinus::XiMinusDefinition(), and G4XiZero::XiZeroDefinition().
Referenced by ConstructParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/hadrons/barions/include/G4BaryonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/hadrons/barions/src/G4BaryonConstructor.cc