ECCE @ EIC Software: G4VCrossSectionSource Class Reference
G4VCrossSectionSource Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VCrossSectionSource.hh>
Public Member Functions
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual const
G4CrossSectionVector * GetComponents () const =0
virtual G4String Name () const =0
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsValid (G4double e) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Protected Member Functions
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Member Functions
G4VCrossSectionSource (const G4VCrossSectionSource &right)
G4VCrossSectionSource & operator= (const G4VCrossSectionSource &right)
Detailed Description
Definition at line 38 of file G4VCrossSectionSource.hh.
View newest version in sPHENIX GitHub at line 38 of file G4VCrossSectionSource.hh
Constructor & Destructor Documentation
G4VCrossSectionSource::G4VCrossSectionSource ()
Definition at line 41 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VCrossSectionSource.cc
G4VCrossSectionSource::~G4VCrossSectionSource () virtual
Definition at line 45 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VCrossSectionSource.cc
G4VCrossSectionSource::G4VCrossSectionSource (const G4VCrossSectionSource & right) private
Member Function Documentation
virtual G4double G4VCrossSectionSource::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const pure virtual
Implemented in G4XPDGTotal, G4XPDGElastic, G4CrossSectionComposite, G4XnpElasticLowE, G4XnpTotalLowE, G4CrossSectionPatch, G4XAnnihilationChannel, G4XAqmElastic, G4XMesonBaryonElastic, G4XResonance, G4XNNElasticLowE, G4XAqmTotal, G4XNNTotalLowE, G4XpimNTotal, and G4XpipNTotal.
Referenced by G4VCollision::CrossSection(), G4CollisionNN::CrossSection(), G4CrossSectionPatch::CrossSection(), G4CrossSectionComposite::CrossSection(), G4CollisionComposite::CrossSection(), PrintAll(), and G4CrossSectionPatch::Transition().
G4double G4VCrossSectionSource::FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const protected
Definition at line 174 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 174 of file G4VCrossSectionSource.cc
References denom, G4Pow::GetInstance(), max, and G4Pow::powA().
const G4ParticleDefinition * G4VCrossSectionSource::FindKeyParticle (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const protected
Definition at line 50 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VCrossSectionSource.cc
References G4KineticTrack::GetDefinition(), G4Neutron::Neutron(), and G4Proton::Proton().
Referenced by G4XNNTotalLowE::CrossSection(), and G4XNNElasticLowE::CrossSection().
const G4ParticleDefinition * G4VCrossSectionSource::FindLightParticle (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const protected
Definition at line 158 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 158 of file G4VCrossSectionSource.cc
References G4KineticTrack::GetDefinition(), and G4ParticleDefinition::GetPDGMass().
Referenced by G4XMesonBaryonElastic::CrossSection().
virtual const G4CrossSectionVector* G4VCrossSectionSource::GetComponents () const pure virtual
Implemented in G4XPDGTotal, G4XPDGElastic, G4CrossSectionComposite, G4XnpElasticLowE, G4XnpTotalLowE, G4CrossSectionPatch, G4XAnnihilationChannel, G4XAqmElastic, G4XMesonBaryonElastic, G4XNNElastic, G4XnpElastic, G4XnpTotal, G4XResonance, G4XNNElasticLowE, G4XAqmTotal, G4XNNTotalLowE, G4XNNTotal, G4XpimNTotal, and G4XpipNTotal.
Referenced by Print(), and PrintAll().
G4double G4VCrossSectionSource::HighLimit () const virtual
Reimplemented in G4XnpElasticLowE, G4XnpTotalLowE, G4XNNElasticLowE, and G4XNNTotalLowE.
Definition at line 146 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 146 of file G4VCrossSectionSource.cc
References DBL_MAX.
Referenced by G4CrossSectionPatch::CrossSection(), IsValid(), and G4CrossSectionPatch::Transition().
G4bool G4VCrossSectionSource::InLimits (G4double e, G4double eLow, G4double eHigh) const protected
Definition at line 133 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 133 of file G4VCrossSectionSource.cc
Referenced by G4XAqmTotal::IsValid(), G4XNNElasticLowE::IsValid(), G4XMesonBaryonElastic::IsValid(), G4XAqmElastic::IsValid(), G4XAnnihilationChannel::IsValid(), G4XnpTotalLowE::IsValid(), G4XnpElasticLowE::IsValid(), G4XPDGElastic::IsValid(), and G4XPDGTotal::IsValid().
G4bool G4VCrossSectionSource::IsValid (G4double e) const virtual
Reimplemented in G4XPDGTotal, G4XPDGElastic, G4CrossSectionComposite, G4XnpElasticLowE, G4XnpTotalLowE, G4CrossSectionPatch, G4XAnnihilationChannel, G4XAqmElastic, G4XMesonBaryonElastic, G4XNNElasticLowE, G4XAqmTotal, and G4XNNTotalLowE.
Definition at line 151 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 151 of file G4VCrossSectionSource.cc
References HighLimit(), and LowLimit().
Referenced by G4CrossSectionPatch::CrossSection(), G4CrossSectionComposite::CrossSection(), G4CrossSectionPatch::IsValid(), and G4CrossSectionComposite::IsValid().
G4double G4VCrossSectionSource::LowLimit () const virtual
Reimplemented in G4XPDGTotal, and G4XPDGElastic.
Definition at line 140 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 140 of file G4VCrossSectionSource.cc
Referenced by G4CrossSectionPatch::CrossSection(), IsValid(), and G4CrossSectionPatch::Transition().
virtual G4String G4VCrossSectionSource::Name () const pure virtual
Implemented in G4XnpElasticLowE, G4XnpTotalLowE, G4XPDGTotal, G4XPDGElastic, G4XAnnihilationChannel, G4XAqmElastic, G4XMesonBaryonElastic, G4XNNElastic, G4XnpElastic, G4XnpTotal, G4XResonance, G4XNNElasticLowE, G4XAqmTotal, G4XNNTotalLowE, G4XNNTotal, G4XpimNTotal, and G4XpipNTotal.
Referenced by Print(), and PrintAll().
G4bool G4VCrossSectionSource::operator!= (const G4VCrossSectionSource & right) const
Definition at line 80 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 80 of file G4VCrossSectionSource.cc
G4VCrossSectionSource& G4VCrossSectionSource::operator= (const G4VCrossSectionSource & right) private
G4bool G4VCrossSectionSource::operator== (const G4VCrossSectionSource & right) const
Definition at line 74 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VCrossSectionSource.cc
void G4VCrossSectionSource::Print (void) const virtual
Reimplemented in G4XnpElasticLowE, G4XnpTotalLowE, and G4XNNElasticLowE.
Definition at line 86 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 86 of file G4VCrossSectionSource.cc
References components, G4cout, G4endl, GetComponents(), Name(), and Print().
Referenced by Print(), G4XNNElasticLowE::Print(), G4VCollision::Print(), G4XnpTotalLowE::Print(), and G4XnpElasticLowE::Print().
void G4VCrossSectionSource::PrintAll (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Definition at line 107 of file G4VCrossSectionSource.cc.
View newest version in sPHENIX GitHub at line 107 of file G4VCrossSectionSource.cc
References components, CrossSection(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), GetComponents(), GeV, millibarn, Name(), and PrintAll().
Referenced by PrintAll().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VCrossSectionSource.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4VCrossSectionSource.cc