ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/materials/pyG4Material.cc File Reference
pyG4Material.cc File Reference
#include <boost/python.hpp>
#include "G4Material.hh"
Namespaces
namespace pyG4Material
Functions
list pyG4Material::f_GetFractionVector (const G4Material *material)
list pyG4Material::f_GetAtomsVector (const G4Material *material)
list pyG4Material::f_GetVecNbOfAtomsPerVolume (const G4Material *material)
list pyG4Material::f_GetAtomicNumDensityVector (const G4Material *material)
void pyG4Material::Print (G4Material &mat)
void export_G4Material ()
Variables
void(G4Material::* pyG4Material::f1_AddElement)(G4Element *, G4int) = &G4Material::AddElement
void(G4Material::* pyG4Material::f2_AddElement)(G4Element *, G4double) = &G4Material::AddElement
G4Material *(* pyG4Material::f1_GetMaterial)(const G4String &, G4bool) = &G4Material::GetMaterial
G4Material *(* pyG4Material::f2_GetMaterial)(G4double, G4double, G4double) = &G4Material::GetMaterial
G4Material *(* pyG4Material::f3_GetMaterial)(size_t, G4double) = &G4Material::GetMaterial
Function Documentation
void export_G4Material ()
Definition at line 115 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 115 of file pyG4Material.cc
References G4Material::AddMaterial(), pyG4Material::f1_AddElement, pyG4Material::f1_GetMaterial, pyG4Material::f2_AddElement, pyG4Material::f2_GetMaterial, pyG4Material::f3_GetMaterial, pyG4Material::f_GetAtomicNumDensityVector(), pyG4Material::f_GetAtomsVector(), pyG4Material::f_GetFractionVector(), pyG4Material::f_GetVecNbOfAtomsPerVolume(), G4Material::GetA(), G4Material::GetChemicalFormula(), G4Material::GetDensity(), G4Material::GetElectronDensity(), G4Material::GetElement(), G4Material::GetElementVector(), G4Material::GetIndex(), G4Material::GetIonisation(), G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4Material::GetName(), G4Material::GetNuclearInterLength(), G4Material::GetNumberOfMaterials(), G4Material::GetPressure(), G4Material::GetRadlen(), G4Material::GetSandiaTable(), G4Material::GetState(), G4Material::GetTemperature(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetTotNbOfElectPerVolume(), G4Material::GetZ(), kStateGas, kStateLiquid, kStateSolid, kStateUndefined, pyG4Element::Print(), G4Material::SetChemicalFormula(), G4Material::SetMaterialPropertiesTable(), and G4Material::SetName().
Referenced by BOOST_PYTHON_MODULE().