ECCE @ EIC Software: F01CalorimeterSD Class Reference
F01CalorimeterSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01CalorimeterSD.hh>
Public Member Functions
F01CalorimeterSD (G4String, F01DetectorConstruction *)
virtual ~F01CalorimeterSD ()
virtual void Initialize (G4HCofThisEvent *)
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual void EndOfEvent (G4HCofThisEvent *)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
F01CalorHitsCollection * fCalCollection
F01DetectorConstruction * fDetector
G4int * fHitID
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 47 of file F01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 47 of file F01CalorimeterSD.hh
Constructor & Destructor Documentation
F01CalorimeterSD::F01CalorimeterSD (G4String name, F01DetectorConstruction * det)
Definition at line 48 of file F01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 48 of file F01CalorimeterSD.cc
References G4VSensitiveDetector::collectionName, and G4CollectionNameVector::insert().
F01CalorimeterSD::~F01CalorimeterSD () virtual
Definition at line 60 of file F01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 60 of file F01CalorimeterSD.cc
References fHitID.
Member Function Documentation
void F01CalorimeterSD::EndOfEvent (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 111 of file F01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 111 of file F01CalorimeterSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, fCalCollection, G4SDManager::GetCollectionID(), and G4SDManager::GetSDMpointer().
void F01CalorimeterSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 67 of file F01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 67 of file F01CalorimeterSD.cc
References G4VSensitiveDetector::collectionName, fCalCollection, fHitID, and G4VSensitiveDetector::SensitiveDetectorName.
G4bool F01CalorimeterSD::ProcessHits (G4Step * step, G4TouchableHistory *) virtual
Implements G4VSensitiveDetector.
Definition at line 76 of file F01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 76 of file F01CalorimeterSD.cc
References F01CalorHit::AddAbs(), edep, fCalCollection, fDetector, fHitID, G4cout, G4endl, F01DetectorConstruction::GetAbsorber(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4TouchableHistory::GetVolume(), G4THitsCollection< T >::insert(), and G4VSensitiveDetector::verboseLevel.
Member Data Documentation
F01CalorHitsCollection* F01CalorimeterSD::fCalCollection private
Definition at line 60 of file F01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 60 of file F01CalorimeterSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
F01DetectorConstruction* F01CalorimeterSD::fDetector private
Definition at line 61 of file F01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 61 of file F01CalorimeterSD.hh
Referenced by ProcessHits().
G4int* F01CalorimeterSD::fHitID private
Definition at line 62 of file F01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 62 of file F01CalorimeterSD.hh
Referenced by Initialize(), ProcessHits(), and ~F01CalorimeterSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01CalorimeterSD.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field01/src/F01CalorimeterSD.cc