ECCE @ EIC Software: CexmcRunManager Class Reference
CexmcRunManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRunManager.hh>
Public Member Functions
CexmcRunManager (const G4String &projectId="", const G4String &rProject="", G4bool overrideExistingProject=false)
virtual ~CexmcRunManager ()
void SetPhysicsManager (CexmcPhysicsManager *physicsManager_)
void SetProductionModelType (CexmcProductionModelType productionModelType_)
void SetGdmlFileName (const G4String &gdmlFileName_)
void SetGdmlFileValidation (G4bool on=true)
void SetGuiMacroName (const G4String &guiMacroName_)
void SetEventCountPolicy (CexmcEventCountPolicy value)
void SetEventDataVerboseLevel (CexmcEventDataVerboseLevel value)
void RegisterScenePrimitives (void)
void BeamParticleChangeHook (void)
void SetupConstructionHook (void)
CexmcPhysicsManager * GetPhysicsManager (void)
CexmcProductionModelType GetProductionModelType (void) const
G4String GetGdmlFileName (void) const
G4bool ShouldGdmlFileBeValidated (void) const
G4String GetGuiMacroName (void) const
G4bool ProjectIsSaved (void) const
G4bool ProjectIsRead (void) const
G4String GetProjectsDir (void) const
G4String GetProjectId (void) const
CexmcEventDataVerboseLevel GetEventDataVerboseLevel (void) const
Public Member Functions inherited from G4RunManager
G4RunManager ()
virtual ~G4RunManager ()
virtual void BeamOn (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void Initialize ()
virtual void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
virtual void AbortRun (G4bool softAbort=false)
virtual void AbortEvent ()
virtual void InitializeGeometry ()
virtual void InitializePhysics ()
virtual G4bool ConfirmBeamOnCondition ()
virtual void RunInitialization ()
virtual void RunTermination ()
virtual void InitializeEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void ProcessOneEvent (G4int i_event)
virtual void TerminateOneEvent ()
virtual void TerminateEventLoop ()
virtual G4Event * GenerateEvent (G4int i_event)
virtual void AnalyzeEvent (G4Event *anEvent)
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
virtual void rndmSaveThisRun ()
virtual void rndmSaveThisEvent ()
virtual void RestoreRandomNumberStatus (const G4String &fileN)
virtual void SetUserInitialization (G4VUserDetectorConstruction *userInit)
virtual void SetUserInitialization (G4VUserPhysicsList *userInit)
virtual void SetUserInitialization (G4VUserActionInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerThreadInitialization *userInit)
virtual void SetUserAction (G4UserRunAction *userAction)
virtual void SetUserAction (G4VUserPrimaryGeneratorAction *userAction)
virtual void SetUserAction (G4UserEventAction *userAction)
virtual void SetUserAction (G4UserStackingAction *userAction)
virtual void SetUserAction (G4UserTrackingAction *userAction)
virtual void SetUserAction (G4UserSteppingAction *userAction)
const G4VUserDetectorConstruction * GetUserDetectorConstruction () const
const G4VUserPhysicsList * GetUserPhysicsList () const
const G4VUserActionInitialization * GetUserActionInitialization () const
G4VUserActionInitialization * GetNonConstUserActionInitialization () const
const G4UserWorkerInitialization * GetUserWorkerInitialization () const
const
G4UserWorkerThreadInitialization * GetUserWorkerThreadInitialization () const
const G4UserRunAction * GetUserRunAction () const
const
G4VUserPrimaryGeneratorAction * GetUserPrimaryGeneratorAction () const
const G4UserEventAction * GetUserEventAction () const
const G4UserStackingAction * GetUserStackingAction () const
const G4UserTrackingAction * GetUserTrackingAction () const
const G4UserSteppingAction * GetUserSteppingAction () const
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
const G4String & GetVersionString () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
void StoreRandomNumberStatusToG4Event (G4int vl)
G4int GetFlagRandomNumberStatusToG4Event () const
void SetRandomNumberStore (G4bool flag)
G4bool GetRandomNumberStore () const
void SetRandomNumberStoreDir (const G4String &dir)
const G4String & GetRandomNumberStoreDir () const
const G4String & GetRandomNumberStatusForThisRun () const
const G4String & GetRandomNumberStatusForThisEvent () const
void SetRandomNumberStorePerEvent (G4bool flag)
G4bool GetRandomNumberStorePerEvent () const
void GeometryHasBeenModified (G4bool prop=true)
void ReinitializeGeometry (G4bool destroyFirst=false, G4bool prop=true)
void PhysicsHasBeenModified ()
void CutOffHasBeenModified ()
void ReOptimizeMotherOf (G4VPhysicalVolume *)
void ReOptimize (G4LogicalVolume *)
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
G4int GetPrintProgress ()
void SetPrintProgress (G4int i)
void SetGeometryToBeOptimized (G4bool vl)
G4bool GetGeometryToBeOptimized ()
void SetNumberOfEventsToBeStored (G4int val)
const G4Run * GetCurrentRun () const
G4Run * GetNonConstCurrentRun () const
const G4Event * GetCurrentEvent () const
const G4Event * GetPreviousEvent (G4int i) const
void SetRunIDCounter (G4int i)
G4int GetNumberOfParallelWorld () const
void SetNumberOfEventsToBeProcessed (G4int val)
G4int GetNumberOfEventsToBeProcessed () const
G4int GetNumberOfSelectEvents () const
G4String GetSelectMacro () const
void SetDCtable (G4DCtable *DCtbl)
RMType GetRunManagerType () const
virtual void ConstructScoringWorlds ()
virtual void RestoreRndmEachEvent (G4bool)
void GeometryDirectlyUpdated (G4bool val=true)
Protected Member Functions
void DoEventLoop (G4int nEvent, const char *macroFile, G4int nSelect)
Protected Member Functions inherited from G4RunManager
void CleanUpPreviousEvents ()
void CleanUpUnnecessaryEvents (G4int keepNEvents)
void StackPreviousEvent (G4Event *anEvent)
G4RunManager (RMType rmType)
virtual void StoreRNGStatus (const G4String &filenamePrefix)
void UpdateScoring ()
virtual void DeleteUserInitializations ()
Private Member Functions
void DoCommonEventLoop (G4int nEvent, const G4String &cmd, G4int nSelect)
void ReadPreinitProjectData (void)
Private Attributes
CexmcBasePhysicsUsed basePhysicsUsed
CexmcProductionModelType productionModelType
G4String gdmlFileName
G4bool shouldGdmlFileBeValidated
G4bool zipGdmlFile
G4String projectsDir
G4String projectId
G4String rProject
G4String guiMacroName
G4String cfFileName
CexmcEventCountPolicy eventCountPolicy
G4bool skipInteractionsWithoutEDTonWrite
CexmcEventDataVerboseLevel evDataVerboseLevel
CexmcEventDataVerboseLevel rEvDataVerboseLevel
G4int numberOfEventsProcessed
G4int numberOfEventsProcessedEffective
G4int curEventRead
CexmcPhysicsManager * physicsManager
CexmcRunManagerMessenger * messenger
Additional Inherited Members
Public Types inherited from G4RunManager
enum RMType { sequentialRM, masterRM, workerRM }
Static Public Member Functions inherited from G4RunManager
static G4RunManager * GetRunManager ()
static G4bool IfGeometryHasBeenDestroyed ()
Protected Attributes inherited from G4RunManager
G4RunManagerKernel * kernel
G4EventManager * eventManager
G4VUserDetectorConstruction * userDetector
G4VUserPhysicsList * physicsList
G4VUserActionInitialization * userActionInitialization
G4UserWorkerInitialization * userWorkerInitialization
G4UserWorkerThreadInitialization * userWorkerThreadInitialization
G4UserRunAction * userRunAction
G4VUserPrimaryGeneratorAction * userPrimaryGeneratorAction
G4UserEventAction * userEventAction
G4UserStackingAction * userStackingAction
G4UserTrackingAction * userTrackingAction
G4UserSteppingAction * userSteppingAction
G4bool geometryInitialized
G4bool physicsInitialized
G4bool runAborted
G4bool initializedAtLeastOnce
G4bool geometryToBeOptimized
G4int runIDCounter
G4int verboseLevel
G4int printModulo
G4Timer * timer
G4DCtable * DCtable
G4Run * currentRun
G4Event * currentEvent
std::list< G4Event * > * previousEvents
G4int n_perviousEventsToBeStored
G4int numberOfEventToBeProcessed
G4bool storeRandomNumberStatus
G4int storeRandomNumberStatusToG4Event
G4String randomNumberStatusDir
G4String randomNumberStatusForThisRun
G4String randomNumberStatusForThisEvent
G4bool rngStatusEventsFlag
G4VPhysicalVolume * currentWorld
G4int nParallelWorlds
G4String msgText
G4int n_select_msg
G4int numberOfEventProcessed
G4String selectMacro
G4bool fakeRun
G4bool isScoreNtupleWriter
RMType runManagerType
G4bool geometryDirectlyUpdated
Static Protected Attributes inherited from G4RunManager
static G4bool fGeometryHasBeenDestroyed = false
Detailed Description
Definition at line 68 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcRunManager.hh
Constructor & Destructor Documentation
CexmcRunManager::CexmcRunManager (const G4String & projectId = "", const G4String & rProject = "", G4bool overrideExistingProject = false) explicit
Definition at line 105 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 105 of file CexmcRunManager.cc
References CexmcProjectExists, CexmcWeirdException, messenger, projectId, ProjectIsRead(), ProjectIsSaved(), projectsDir, ReadPreinitProjectData(), and rProject.
CexmcRunManager::~CexmcRunManager () virtual
Definition at line 150 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 150 of file CexmcRunManager.cc
References messenger.
Member Function Documentation
void CexmcRunManager::BeamParticleChangeHook (void)
Definition at line 1348 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 1348 of file CexmcRunManager.cc
References CexmcEventAction::BeamParticleChangeHook(), CexmcWeirdException, and G4RunManager::userEventAction.
Referenced by CexmcParticleGunMessenger::SetNewValue().
void CexmcRunManager::DoCommonEventLoop (G4int nEvent, const G4String & cmd, G4int nSelect) private
Definition at line 462 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 462 of file CexmcRunManager.cc
References G4RunManager::AnalyzeEvent(), G4UImanager::ApplyCommand(), CexmcCountAllEvents, CexmcCountEventsWithInteraction, CexmcCountEventsWithTrigger, G4RunManager::currentEvent, CexmcEventInfo::EdTriggerIsOk(), G4RunManager::eventManager, G4RunManager::GenerateEvent(), G4UImanager::GetUIpointer(), G4Event::GetUserInformation(), G4EventManager::ProcessOneEvent(), G4RunManager::runAborted, G4RunManager::StackPreviousEvent(), CexmcEventInfo::TpTriggerIsOk(), and G4RunManager::UpdateScoring().
Referenced by DoEventLoop().
void CexmcRunManager::DoEventLoop (G4int nEvent, const char * macroFile, G4int nSelect) protected virtual
Reimplemented from G4RunManager.
Definition at line 885 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 885 of file CexmcRunManager.cc
References DoCommonEventLoop(), G4cout, G4endl, projectId, ProjectIsRead(), ProjectIsSaved(), projectsDir, G4RunManager::runAborted, G4Timer::Start(), G4Timer::Stop(), G4RunManager::timer, and G4RunManager::verboseLevel.
CexmcEventDataVerboseLevel CexmcRunManager::GetEventDataVerboseLevel (void) const inline
Definition at line 382 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 382 of file CexmcRunManager.hh
References evDataVerboseLevel.
G4String CexmcRunManager::GetGdmlFileName (void) const inline
Definition at line 295 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 295 of file CexmcRunManager.hh
References gdmlFileName.
Referenced by main().
G4String CexmcRunManager::GetGuiMacroName (void) const inline
Definition at line 307 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 307 of file CexmcRunManager.hh
References guiMacroName.
Referenced by main().
CexmcPhysicsManager * CexmcRunManager::GetPhysicsManager (void) inline
Definition at line 282 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 282 of file CexmcRunManager.hh
References physicsManager.
CexmcProductionModelType CexmcRunManager::GetProductionModelType (void) const inline
Definition at line 289 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 289 of file CexmcRunManager.hh
References productionModelType.
Referenced by main().
G4String CexmcRunManager::GetProjectId (void) const inline
Definition at line 331 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 331 of file CexmcRunManager.hh
References projectId.
G4String CexmcRunManager::GetProjectsDir (void) const inline
Definition at line 325 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 325 of file CexmcRunManager.hh
References projectsDir.
G4bool CexmcRunManager::ProjectIsRead (void) const inline
Definition at line 319 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 319 of file CexmcRunManager.hh
References rProject.
Referenced by CexmcRunManager(), CexmcEnergyDepositDigitizer::Digitize(), DoEventLoop(), CexmcProductionModel::IsGoodCandidateForAngularRange(), main(), SetEventCountPolicy(), SetEventDataVerboseLevel(), SetGdmlFileName(), SetProductionModelType(), SetupConstructionHook(), and ThrowExceptionIfProjectIsRead().
G4bool CexmcRunManager::ProjectIsSaved (void) const inline
Definition at line 313 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 313 of file CexmcRunManager.hh
References projectId.
Referenced by CexmcRunManager(), DoEventLoop(), main(), and SetupConstructionHook().
void CexmcRunManager::ReadPreinitProjectData (void) private
Referenced by CexmcRunManager().
void CexmcRunManager::RegisterScenePrimitives (void)
Definition at line 1308 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 1308 of file CexmcRunManager.cc
References CexmcScenePrimitivesDescription, CexmcWeirdException, G4VVisManager::GetConcreteInstance(), G4VisManager::GetCurrentScene(), k, and G4RunManager::userDetector.
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetEventCountPolicy (CexmcEventCountPolicy value) inline
Definition at line 262 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 262 of file CexmcRunManager.hh
References CexmcCmdIsNotAllowed, eventCountPolicy, and ProjectIsRead().
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetEventDataVerboseLevel (CexmcEventDataVerboseLevel value) inline
Definition at line 272 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 272 of file CexmcRunManager.hh
References CexmcPoorEventData, evDataVerboseLevel, ProjectIsRead(), and rEvDataVerboseLevel.
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetGdmlFileName (const G4String & gdmlFileName_) inline
Definition at line 241 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 241 of file CexmcRunManager.hh
References CexmcCmdIsNotAllowed, gdmlFileName, and ProjectIsRead().
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetGdmlFileValidation (G4bool on = true) inline
Definition at line 250 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 250 of file CexmcRunManager.hh
References shouldGdmlFileBeValidated.
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetGuiMacroName (const G4String & guiMacroName_) inline
Definition at line 256 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 256 of file CexmcRunManager.hh
References guiMacroName.
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetPhysicsManager (CexmcPhysicsManager * physicsManager_) inline
Definition at line 224 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 224 of file CexmcRunManager.hh
References physicsManager.
Referenced by main().
void CexmcRunManager::SetProductionModelType (CexmcProductionModelType productionModelType_) inline
Definition at line 231 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 231 of file CexmcRunManager.hh
References CexmcCmdIsNotAllowed, productionModelType, and ProjectIsRead().
Referenced by CexmcRunManagerMessenger::SetNewValue().
void CexmcRunManager::SetupConstructionHook (void)
Definition at line 1361 of file CexmcRunManager.cc.
View newest version in sPHENIX GitHub at line 1361 of file CexmcRunManager.cc
References CexmcFileCompressException, CexmcSystemException, projectId, ProjectIsRead(), ProjectIsSaved(), projectsDir, system(), and zipGdmlFile.
Referenced by CexmcSetup::Construct().
G4bool CexmcRunManager::ShouldGdmlFileBeValidated (void) const inline
Definition at line 301 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 301 of file CexmcRunManager.hh
References shouldGdmlFileBeValidated.
Referenced by main().
Member Data Documentation
CexmcBasePhysicsUsed CexmcRunManager::basePhysicsUsed private
Definition at line 168 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 168 of file CexmcRunManager.hh
G4String CexmcRunManager::cfFileName private
Definition at line 186 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 186 of file CexmcRunManager.hh
G4int CexmcRunManager::curEventRead private
Definition at line 201 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 201 of file CexmcRunManager.hh
CexmcEventDataVerboseLevel CexmcRunManager::evDataVerboseLevel private
Definition at line 192 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 192 of file CexmcRunManager.hh
Referenced by GetEventDataVerboseLevel(), and SetEventDataVerboseLevel().
CexmcEventCountPolicy CexmcRunManager::eventCountPolicy private
Definition at line 188 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 188 of file CexmcRunManager.hh
Referenced by SetEventCountPolicy().
G4String CexmcRunManager::gdmlFileName private
Definition at line 172 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 172 of file CexmcRunManager.hh
Referenced by GetGdmlFileName(), and SetGdmlFileName().
G4String CexmcRunManager::guiMacroName private
Definition at line 184 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 184 of file CexmcRunManager.hh
Referenced by GetGuiMacroName(), and SetGuiMacroName().
CexmcRunManagerMessenger* CexmcRunManager::messenger private
Definition at line 220 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 220 of file CexmcRunManager.hh
Referenced by CexmcRunManager(), and ~CexmcRunManager().
G4int CexmcRunManager::numberOfEventsProcessed private
Definition at line 197 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 197 of file CexmcRunManager.hh
G4int CexmcRunManager::numberOfEventsProcessedEffective private
Definition at line 199 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 199 of file CexmcRunManager.hh
CexmcPhysicsManager* CexmcRunManager::physicsManager private
Definition at line 217 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 217 of file CexmcRunManager.hh
Referenced by GetPhysicsManager(), and SetPhysicsManager().
CexmcProductionModelType CexmcRunManager::productionModelType private
Definition at line 170 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 170 of file CexmcRunManager.hh
Referenced by GetProductionModelType(), and SetProductionModelType().
G4String CexmcRunManager::projectId private
Definition at line 180 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 180 of file CexmcRunManager.hh
Referenced by CexmcRunManager(), DoEventLoop(), GetProjectId(), ProjectIsSaved(), and SetupConstructionHook().
G4String CexmcRunManager::projectsDir private
Definition at line 178 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 178 of file CexmcRunManager.hh
Referenced by CexmcRunManager(), DoEventLoop(), GetProjectsDir(), and SetupConstructionHook().
CexmcEventDataVerboseLevel CexmcRunManager::rEvDataVerboseLevel private
Definition at line 194 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 194 of file CexmcRunManager.hh
Referenced by SetEventDataVerboseLevel().
G4String CexmcRunManager::rProject private
Definition at line 182 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 182 of file CexmcRunManager.hh
Referenced by CexmcRunManager(), and ProjectIsRead().
G4bool CexmcRunManager::shouldGdmlFileBeValidated private
Definition at line 174 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 174 of file CexmcRunManager.hh
Referenced by SetGdmlFileValidation(), and ShouldGdmlFileBeValidated().
G4bool CexmcRunManager::skipInteractionsWithoutEDTonWrite private
Definition at line 190 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 190 of file CexmcRunManager.hh
G4bool CexmcRunManager::zipGdmlFile private
Definition at line 176 of file CexmcRunManager.hh.
View newest version in sPHENIX GitHub at line 176 of file CexmcRunManager.hh
Referenced by SetupConstructionHook().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRunManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcRunManager.cc