ECCE @ EIC Software: G4AngularDistributionPP Class Reference
G4AngularDistributionPP Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4AngularDistributionPP.hh>
Public Member Functions
G4AngularDistributionPP ()
virtual ~G4AngularDistributionPP ()
virtual G4double CosTheta (G4double s, G4double m1, G4double m2) const
virtual G4double Phi () const
Public Member Functions inherited from G4VAngularDistribution
G4VAngularDistribution ()
virtual ~G4VAngularDistribution ()
Private Types
enum { NENERGY =40, NENERGYC =22, NANGLE =180 }
Static Private Attributes
static const G4float sig [NENERGY][NANGLE]
static const G4float pcm [NENERGY]
static const G4float elab [NENERGY]
static const G4float dsigmax [NENERGY]
static const G4float sigtot [NENERGY]
Detailed Description
Definition at line 40 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 40 of file G4AngularDistributionPP.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
NENERGY
NENERGYC
NANGLE
Definition at line 45 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 45 of file G4AngularDistributionPP.hh
Constructor & Destructor Documentation
G4AngularDistributionPP::G4AngularDistributionPP () inline
Definition at line 49 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 49 of file G4AngularDistributionPP.hh
virtual G4AngularDistributionPP::~G4AngularDistributionPP () inline virtual
Definition at line 51 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 51 of file G4AngularDistributionPP.hh
Member Function Documentation
G4double G4AngularDistributionPP::CosTheta (G4double s, G4double m1, G4double m2) const virtual
Implements G4VAngularDistribution.
Definition at line 37 of file G4AngularDistributionPP.cc.
View newest version in sPHENIX GitHub at line 37 of file G4AngularDistributionPP.cc
References b, degree, elab, FatalException, G4cout, G4endl, G4Exception(), G4UniformRand, GeV, NANGLE, NENERGY, pi, sig, sqr(), and theta().
G4double G4AngularDistributionPP::Phi () const virtual
Reimplemented from G4VAngularDistribution.
Definition at line 133 of file G4AngularDistributionPP.cc.
View newest version in sPHENIX GitHub at line 133 of file G4AngularDistributionPP.cc
References G4UniformRand, and twopi.
Member Data Documentation
const G4float G4AngularDistributionPP::dsigmax static private
Initial value:
= {
     63.9f, 29.9f, 14.5f, 8.97f, 7.23f, 6.66f, 6.30f,
     5.89f, 5.68f, 5.57f, 5.56f, 5.57f, 5.74f, 6.38f,
     7.66f, 9.65f, 12.4f, 15.6f, 18.0f, 20.1f, 22.0f, 23.8f,
     26.710f, 28.910f, 31.000f, 32.990f, 34.900f, 36.730f, 38.520f,
     40.270f, 43.680f, 46.950f, 50.100f, 53.160f, 55.880f, 58.820f,
     57.420f, 57.820f, 58.590f, 57.800f
 }
Definition at line 61 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AngularDistributionPP.hh
const G4float G4AngularDistributionPP::elab static private
Initial value:
= {
     0.100E-01f, 0.200E-01f, 0.400E-01f, 0.700E-01f, 0.100f, 0.120f, 0.140f,
     0.180f, 0.220f, 0.260f, 0.280f, 0.300f, 0.340f, 0.420f,
     0.520f, 0.620f, 0.700f, 0.800f, 0.900f, 1.00f, 1.10f, 1.20f,
     1.30f, 1.40f, 1.50f, 1.60f, 1.70f, 1.80f, 1.90f,
     2.00f, 2.20f, 2.40f, 2.60f, 2.80f, 3.00f, 3.40f,
     3.80f, 4.20f, 4.60f, 5.00f
 }
Definition at line 61 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AngularDistributionPP.hh
Referenced by CosTheta().
const G4float G4AngularDistributionPP::pcm static private
Initial value:
= {
     0.685E-01f, 0.969E-01f, 0.137f, 0.181f, 0.217f, 0.237f, 0.256f,
     0.291f, 0.321f, 0.349f, 0.363f, 0.375f, 0.400f, 0.444f,
     0.494f, 0.540f, 0.573f, 0.613f, 0.650f, 0.685f, 0.719f, 0.751f,
     0.781f, 0.810f, 0.839f, 0.866f, 0.893f, 0.919f, 0.944f,
     0.969f, 1.016f, 1.061f, 1.104f, 1.146f, 1.186f, 1.263f,
     1.335f, 1.404f, 1.469f, 1.532f
 }
Definition at line 61 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AngularDistributionPP.hh
const G4float G4AngularDistributionPP::sig static private
Definition at line 60 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 60 of file G4AngularDistributionPP.hh
Referenced by CosTheta().
const G4float G4AngularDistributionPP::sigtot static private
Initial value:
= {
     396.f, 179.f, 80.7f, 44.5f, 32.8f, 29.0f, 26.9f,
     24.9f, 24.4f, 24.3f, 24.4f, 24.4f, 24.7f, 25.5f,
     26.4f, 26.1f, 25.6f, 25.1f, 24.4f, 23.4f, 22.4f, 21.5f,
     22.765f, 23.275f, 23.744f, 24.188f, 24.620f, 25.058f, 25.509f,
     25.981f, 26.984f, 28.055f, 29.242f, 30.608f, 32.026f, 34.457f,
     34.394f, 33.885f, 34.122f, 33.603f
 }
Definition at line 61 of file G4AngularDistributionPP.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AngularDistributionPP.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4AngularDistributionPP.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4AngularDistributionPPData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4AngularDistributionPP.cc