ECCE @ EIC Software: G4PrecoProtonBuilder Class Reference
G4PrecoProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4PrecoProtonBuilder.hh>
Public Member Functions
G4PrecoProtonBuilder ()
virtual ~G4PrecoProtonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4PreCompoundModel * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 51 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PrecoProtonBuilder.hh
Constructor & Destructor Documentation
G4PrecoProtonBuilder::G4PrecoProtonBuilder ()
Definition at line 48 of file G4PrecoProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4PrecoProtonBuilder.cc
References MeV, theMax, theMin, and theModel.
virtual G4PrecoProtonBuilder::~G4PrecoProtonBuilder () inline virtual
Definition at line 55 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 55 of file G4PrecoProtonBuilder.hh
Member Function Documentation
virtual void G4PrecoProtonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VProtonBuilder.
Definition at line 58 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PrecoProtonBuilder.hh
void G4PrecoProtonBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 56 of file G4PrecoProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PrecoProtonBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4PrecoProtonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 61 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4PrecoProtonBuilder.hh
References theMin.
Member Data Documentation
G4double G4PrecoProtonBuilder::theMax private
Definition at line 69 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PrecoProtonBuilder.hh
Referenced by Build(), and G4PrecoProtonBuilder().
G4double G4PrecoProtonBuilder::theMin private
Definition at line 68 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PrecoProtonBuilder.hh
Referenced by Build(), G4PrecoProtonBuilder(), and SetMinEnergy().
G4PreCompoundModel* G4PrecoProtonBuilder::theModel private
Definition at line 67 of file G4PrecoProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PrecoProtonBuilder.hh
Referenced by Build(), and G4PrecoProtonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4PrecoProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4PrecoProtonBuilder.cc