ECCE @ EIC Software: UVA_VisAction Class Reference
UVA_VisAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/include/UVA_VisAction.hh>
Private Member Functions
virtual void Draw ()
Additional Inherited Members
Public Member Functions inherited from G4VUserVisAction
G4VUserVisAction ()
virtual ~G4VUserVisAction ()
void operator() (G4VGraphicsScene &scene, const G4Transform3D &trans, const G4ModelingParameters *pMP)
Protected Attributes inherited from G4VUserVisAction
G4VGraphicsScene * fpSceneHandler
const G4Transform3D * fpTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 36 of file UVA_VisAction.hh.
View newest version in sPHENIX GitHub at line 36 of file UVA_VisAction.hh
Member Function Documentation
void UVA_VisAction::Draw () private virtual
Implements G4VUserVisAction.
Definition at line 43 of file UVA_VisAction.cc.
View newest version in sPHENIX GitHub at line 43 of file UVA_VisAction.cc
References cm, G4VVisManager::Draw(), G4VVisManager::GetConcreteInstance(), G4Colour::Magenta(), G4Colour::Red(), G4VisAttributes::SetForceSolid(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/include/UVA_VisAction.hh
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/src/UVA_VisAction.cc