ECCE @ EIC Software: macros/blob/master/common/G4_Bbc.C File Reference
G4_Bbc.C File Reference
#include <g4detectors/PHG4BbcSubsystem.h>
#include <g4bbc/BbcVertexFastSimReco.h>
#include <g4main/PHG4Reco.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4BBC
Macros
#define MACRO_G4BBC_C
Functions
void BbcInit ()
void Bbc (PHG4Reco *g4Reco)
void Bbc_Reco ()
Variables
bool Enable::BBC = false
bool Enable::BBCFAKE = false
int Enable::BBC_VERBOSITY = 0
double G4BBC::z_smearing = 0.
double G4BBC::t_smearing = 0.02
Macro Definition Documentation
#define MACRO_G4BBC_C
Definition at line 2 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Bbc.C
Function Documentation
void Bbc (PHG4Reco * g4Reco)
Definition at line 44 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 44 of file G4_Bbc.C
References Enable::BBC, PHG4Reco::registerSubsystem(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().
void Bbc_Reco ()
Definition at line 55 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 55 of file G4_Bbc.C
References Enable::BBC_VERBOSITY, Enable::BBCFAKE, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), BbcVertexFastSimReco::set_t_smearing(), BbcVertexFastSimReco::set_z_smearing(), G4BBC::t_smearing, Enable::VERBOSITY, and G4BBC::z_smearing.
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_G4_sPHENIX().
void BbcInit ()
Definition at line 28 of file G4_Bbc.C.
View newest version in sPHENIX GitHub at line 28 of file G4_Bbc.C
References Enable::BBC, Enable::BBCFAKE, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, and BlackHoleGeometry::min_z.
Referenced by G4Init().