ECCE @ EIC Software: G4DNAMolecularStepByStepModel Class Reference
G4DNAMolecularStepByStepModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAMolecularStepByStepModel.hh>
Public Member Functions
G4DNAMolecularStepByStepModel (const G4String &name="DNAMolecularStepByStepModel")
G4DNAMolecularStepByStepModel (const G4String &name, std::unique_ptr< G4VITTimeStepComputer > pTimeStepper, std::unique_ptr< G4VITReactionProcess > pReactionProcess)
G4DNAMolecularStepByStepModel & operator= (const G4DNAMolecularStepByStepModel &)=delete
G4DNAMolecularStepByStepModel (const G4DNAMolecularStepByStepModel &)=delete
~G4DNAMolecularStepByStepModel () override
void PrintInfo () override
void Initialize () override
void SetReactionModel (G4VDNAReactionModel *)
G4VDNAReactionModel * GetReactionModel ()
Public Member Functions inherited from G4VITStepModel
G4VITStepModel (const G4String &aName="NoName")
G4VITStepModel (std::unique_ptr< G4VITTimeStepComputer > pTimeStepper, std::unique_ptr< G4VITReactionProcess > pReactionProcess, const G4String &aName="NoName")
G4VITStepModel (const G4VITStepModel &other)=delete
G4VITStepModel & operator= (const G4VITStepModel &other)=delete
virtual ~G4VITStepModel ()=default
void PrepareNewTimeStep ()
void GetApplicable (G4ITType &type1, G4ITType &type2)
G4VITTimeStepComputer * GetTimeStepper ()
const G4String & GetName ()
G4VITReactionProcess * GetReactionProcess ()
void SetReactionTable (G4ITReactionTable *)
const G4ITReactionTable * GetReactionTable ()
Protected Attributes
const
G4DNAMolecularReactionTable *& fMolecularReactionTable
std::unique_ptr
< G4VDNAReactionModel > fpReactionModel
Protected Attributes inherited from G4VITStepModel
G4String fName
std::unique_ptr
< G4VITTimeStepComputer > fpTimeStepper
std::unique_ptr
< G4VITReactionProcess > fpReactionProcess
const G4ITReactionTable * fpReactionTable
G4ITType fType1
G4ITType fType2
Detailed Description
G4DNAMolecularStepByStepModel :
TimeStepper : G4DNAMolecularEncounterStepper
ReactionProcess : G4DNAMolecularReaction Before each step, the next minimum encounter time is calculated for each pair of molecule. The minimum time step is selected. All the molecules are stepped within this time step. Then, only the relevant pair of molecules are checked for reaction.
Definition at line 63 of file G4DNAMolecularStepByStepModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4DNAMolecularStepByStepModel.hh
Constructor & Destructor Documentation
G4DNAMolecularStepByStepModel::G4DNAMolecularStepByStepModel (const G4String & name = "DNAMolecularStepByStepModel")
Definition at line 39 of file G4DNAMolecularStepByStepModel.cc.
View newest version in sPHENIX GitHub at line 39 of file G4DNAMolecularStepByStepModel.cc
G4DNAMolecularStepByStepModel::G4DNAMolecularStepByStepModel (const G4String & name, std::unique_ptr< G4VITTimeStepComputer > pTimeStepper, std::unique_ptr< G4VITReactionProcess > pReactionProcess)
Definition at line 46 of file G4DNAMolecularStepByStepModel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4DNAMolecularStepByStepModel.cc
References G4VITStepModel::fType1, and G4VITStepModel::fType2.
G4DNAMolecularStepByStepModel::G4DNAMolecularStepByStepModel (const G4DNAMolecularStepByStepModel &) delete
G4DNAMolecularStepByStepModel::~G4DNAMolecularStepByStepModel () override default
Member Function Documentation
G4VDNAReactionModel * G4DNAMolecularStepByStepModel::GetReactionModel ()
Definition at line 92 of file G4DNAMolecularStepByStepModel.cc.
View newest version in sPHENIX GitHub at line 92 of file G4DNAMolecularStepByStepModel.cc
References fpReactionModel.
void G4DNAMolecularStepByStepModel::Initialize () override virtual
Reimplemented from G4VITStepModel.
Definition at line 60 of file G4DNAMolecularStepByStepModel.cc.
View newest version in sPHENIX GitHub at line 60 of file G4DNAMolecularStepByStepModel.cc
References fpReactionModel, G4VITStepModel::fpReactionProcess, G4VITStepModel::fpReactionTable, G4VITStepModel::fpTimeStepper, G4DNAMolecularReactionTable::GetReactionTable(), G4VITStepModel::Initialize(), SetReactionModel(), and G4VITStepModel::SetReactionTable().
G4DNAMolecularStepByStepModel& G4DNAMolecularStepByStepModel::operator= (const G4DNAMolecularStepByStepModel &) delete
void G4DNAMolecularStepByStepModel::PrintInfo () override virtual
Reimplemented from G4VITStepModel.
Definition at line 80 of file G4DNAMolecularStepByStepModel.cc.
View newest version in sPHENIX GitHub at line 80 of file G4DNAMolecularStepByStepModel.cc
References G4VITStepModel::fName, G4cout, and G4endl.
void G4DNAMolecularStepByStepModel::SetReactionModel (G4VDNAReactionModel * pReactionModel)
Definition at line 87 of file G4DNAMolecularStepByStepModel.cc.
View newest version in sPHENIX GitHub at line 87 of file G4DNAMolecularStepByStepModel.cc
References fpReactionModel.
Referenced by G4EmDNAChemistry::ConstructTimeStepModel(), G4EmDNAChemistry_option1::ConstructTimeStepModel(), G4EmDNAChemistry_option2::ConstructTimeStepModel(), and Initialize().
Member Data Documentation
const G4DNAMolecularReactionTable*& G4DNAMolecularStepByStepModel::fMolecularReactionTable protected
Definition at line 81 of file G4DNAMolecularStepByStepModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4DNAMolecularStepByStepModel.hh
std::unique_ptr<G4VDNAReactionModel> G4DNAMolecularStepByStepModel::fpReactionModel protected
Definition at line 82 of file G4DNAMolecularStepByStepModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DNAMolecularStepByStepModel.hh
Referenced by GetReactionModel(), Initialize(), and SetReactionModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAMolecularStepByStepModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAMolecularStepByStepModel.cc