ECCE @ EIC Software: G4HelixExplicitEuler Class Reference
G4HelixExplicitEuler Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4HelixExplicitEuler.hh>
Public Member Functions
G4HelixExplicitEuler (G4Mag_EqRhs *EqRhs)
~G4HelixExplicitEuler ()
void Stepper (const G4double y[], const G4double *, G4double h, G4double yout[], G4double yerr[])
void DumbStepper (const G4double y[], G4ThreeVector Bfld, G4double h, G4double yout[])
G4double DistChord () const
G4int IntegratorOrder () const
Public Member Functions inherited from G4MagHelicalStepper
G4MagHelicalStepper (G4Mag_EqRhs *EqRhs)
virtual ~G4MagHelicalStepper ()
G4MagHelicalStepper (const G4MagHelicalStepper &)=delete
G4MagHelicalStepper & operator= (const G4MagHelicalStepper &)=delete
virtual void Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[])
G4double DistChord () const
Public Member Functions inherited from G4MagIntegratorStepper
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, G4bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
G4MagIntegratorStepper (const G4MagIntegratorStepper &)=delete
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)=delete
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
G4bool IsFSAL () const
Additional Inherited Members
Protected Member Functions inherited from G4MagHelicalStepper
void LinearStep (const G4double yIn[], G4double h, G4double yHelix[]) const
void AdvanceHelix (const G4double yIn[], G4ThreeVector Bfld, G4double h, G4double yHelix[], G4double yHelix2[]=0)
void MagFieldEvaluate (const G4double y[], G4ThreeVector &Bfield)
G4double GetInverseCurve (const G4double Momentum, const G4double Bmag)
void SetAngCurve (const G4double Ang)
G4double GetAngCurve () const
void SetCurve (const G4double Curve)
G4double GetCurve () const
void SetRadHelix (const G4double Rad)
G4double GetRadHelix () const
Detailed Description
Definition at line 42 of file G4HelixExplicitEuler.hh.
View newest version in sPHENIX GitHub at line 42 of file G4HelixExplicitEuler.hh
Constructor & Destructor Documentation
G4HelixExplicitEuler::G4HelixExplicitEuler (G4Mag_EqRhs * EqRhs)
Definition at line 40 of file G4HelixExplicitEuler.cc.
View newest version in sPHENIX GitHub at line 40 of file G4HelixExplicitEuler.cc
G4HelixExplicitEuler::~G4HelixExplicitEuler ()
Definition at line 45 of file G4HelixExplicitEuler.cc.
View newest version in sPHENIX GitHub at line 45 of file G4HelixExplicitEuler.cc
Member Function Documentation
G4double G4HelixExplicitEuler::DistChord () const virtual
Implements G4MagIntegratorStepper.
Definition at line 89 of file G4HelixExplicitEuler.cc.
View newest version in sPHENIX GitHub at line 89 of file G4HelixExplicitEuler.cc
References G4MagHelicalStepper::GetAngCurve(), G4MagHelicalStepper::GetRadHelix(), pi, and twopi.
void G4HelixExplicitEuler::DumbStepper (const G4double y[], G4ThreeVector Bfld, G4double h, G4double yout[]) virtual
Implements G4MagHelicalStepper.
Definition at line 115 of file G4HelixExplicitEuler.cc.
View newest version in sPHENIX GitHub at line 115 of file G4HelixExplicitEuler.cc
References G4MagHelicalStepper::AdvanceHelix().
G4int G4HelixExplicitEuler::IntegratorOrder () const inline virtual
Implements G4MagIntegratorStepper.
Definition at line 64 of file G4HelixExplicitEuler.hh.
View newest version in sPHENIX GitHub at line 64 of file G4HelixExplicitEuler.hh
void G4HelixExplicitEuler::Stepper (const G4double y[], const G4double * , G4double h, G4double yout[], G4double yerr[])
Definition at line 49 of file G4HelixExplicitEuler.cc.
View newest version in sPHENIX GitHub at line 49 of file G4HelixExplicitEuler.cc
References G4MagHelicalStepper::AdvanceHelix(), G4MagHelicalStepper::GetAngCurve(), Acts::UnitConstants::h, G4MagHelicalStepper::MagFieldEvaluate(), and G4MagHelicalStepper::SetAngCurve().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4HelixExplicitEuler.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4HelixExplicitEuler.cc