ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/g3tog4.F File Reference
g3tog4.F File Reference
#include "G3toG4.inc"
Macros
#define CALL_GEANT
Functions/Subroutines
subroutine g3tog4 (luni, lunc, chopt)
subroutine g4init
subroutine g3header
subroutine g3source
subroutine g3main
subroutine g3context (cntxt)
subroutine ctocp (string)
subroutine rtocp (string, x)
subroutine artocp (string, ax, n)
subroutine aitocp (string, ai, n)
subroutine astocp (string, ac, n)
subroutine g3ldpar (par, npar)
subroutine check_lines
Macro Definition Documentation
#define CALL_GEANT
Function/Subroutine Documentation
subroutine aitocp (character*(*) string, integer, dimension(*) ai, integer n)
Definition at line 259 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 259 of file g3tog4.F
References n, and nlohmann::json_sax< BasicJsonType >::string().
Referenced by ksdet(), ksdetd(), ksdeth(), and ksdk().
subroutine artocp (character*(*) string, real, dimension(*) ax, integer n)
Definition at line 245 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 245 of file g3tog4.F
References n, and nlohmann::json_sax< BasicJsonType >::string().
Referenced by ksdeth(), ksdk(), and ksmixt().
subroutine astocp (character*(*) string, character*(*), dimension(*) ac, integer n)
Definition at line 273 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 273 of file g3tog4.F
References n, and nlohmann::json_sax< BasicJsonType >::string().
Referenced by ksdet(), ksdetd(), and ksdeth().
subroutine check_lines ()
Definition at line 305 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 305 of file g3tog4.F
References g3source(), and nlines.
Referenced by kgclos(), ksatt(), ksdet(), ksdeta(), ksdetd(), ksdeth(), ksdetu(), ksdetv(), ksdk(), ksdvn(), ksdvn2(), ksdvt(), ksdvt2(), ksdvx(), ksmate(), ksmixt(), kspart(), kspos(), ksposp(), ksrotm(), kstmed(), kstpar(), and ksvolu().
subroutine ctocp (character*(*) string)
Definition at line 225 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 225 of file g3tog4.F
References nlohmann::json_sax< BasicJsonType >::string().
Referenced by g3main(), and g3source().
subroutine g3context (character*(*) cntxt)
Definition at line 208 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 208 of file g3tog4.F
subroutine g3header ()
Definition at line 138 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 138 of file g3tog4.F
References g4init().
Referenced by g3source().
subroutine g3ldpar (real, dimension(*) par, integer npar)
Definition at line 287 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 287 of file g3tog4.F
Referenced by ksdetu(), ksmate(), kspart(), ksposp(), kstmed(), and ksvolu().
subroutine g3main ()
Definition at line 187 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 187 of file g3tog4.F
References ctocp(), file, Acts::detail::VoidNavigator::status(), and kdfinder::TVector< T >::unit().
Referenced by kgclos().
subroutine g3source ()
Definition at line 146 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 146 of file g3tog4.F
References ctocp(), file, g3header(), Acts::detail::VoidNavigator::status(), and kdfinder::TVector< T >::unit().
Referenced by check_lines(), g3tog4(), and mztog4().
subroutine g3tog4 (integer luni, integer lunc, character, dimension(*) chopt)
Definition at line 60 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 60 of file g3tog4.F
References false, file, g3source(), print(), Acts::detail::VoidNavigator::status(), true, and kdfinder::TVector< T >::unit().
subroutine g4init ()
Definition at line 124 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 124 of file g3tog4.F
Referenced by g3header().
subroutine rtocp (character*(*) string, real x)
Definition at line 234 of file g3tog4.F.
View newest version in sPHENIX GitHub at line 234 of file g3tog4.F
References nlohmann::json_sax< BasicJsonType >::string(), and x.
Referenced by ksdvn2(), ksdvt(), ksdvt2(), ksdvx(), ksmate(), ksmixt(), kspart(), kspos(), ksposp(), ksrotm(), and kstmed().