ECCE @ EIC Software: G4NativeScreenedCoulombCrossSection Class Reference
G4NativeScreenedCoulombCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh>
Public Types
typedef G4_c2_function &(* ScreeningFunc)(G4int z1, G4int z2, size_t nPoints, G4double rMax, G4double *au)
Public Types inherited from G4ScreenedCoulombCrossSection
enum { nMassMapElements =116 }
typedef std::map< G4int,
G4ScreeningTables > ScreeningMap
typedef std::map< G4int, class
G4ParticleDefinition * > ParticleCache
Public Member Functions
G4NativeScreenedCoulombCrossSection ()
G4NativeScreenedCoulombCrossSection (const G4NativeScreenedCoulombCrossSection &src)
G4NativeScreenedCoulombCrossSection (const G4ScreenedCoulombCrossSection &src)
virtual ~G4NativeScreenedCoulombCrossSection ()
virtual void LoadData (G4String screeningKey, G4int z1, G4double m1, G4double recoilCutoff)
virtual
G4ScreenedCoulombCrossSection * create ()
std::vector< G4String > GetScreeningKeys () const
void AddScreeningFunction (G4String name, ScreeningFunc fn)
Public Member Functions inherited from G4ScreenedCoulombCrossSection
G4ScreenedCoulombCrossSection ()
G4ScreenedCoulombCrossSection (const G4ScreenedCoulombCrossSection &src)
virtual ~G4ScreenedCoulombCrossSection ()
void BuildMFPTables (void)
const G4ScreeningTables * GetScreening (G4int Z)
void SetVerbosity (G4int v)
G4ParticleDefinition * SelectRandomUnweightedTarget (const G4MaterialCutsCouple *couple)
G4double standardmass (G4int z1)
const G4_c2_function * operator[] (G4int materialIndex)
Public Member Functions inherited from G4ScreenedCoulombCrossSectionInfo
G4ScreenedCoulombCrossSectionInfo ()
~G4ScreenedCoulombCrossSectionInfo ()
Private Attributes
std::map< std::string,
ScreeningFunc > phiMap
Additional Inherited Members
Static Public Member Functions inherited from G4ScreenedCoulombCrossSectionInfo
static const char * CVSHeaderVers ()
static const char * CVSFileVers ()
Protected Attributes inherited from G4ScreenedCoulombCrossSection
ScreeningMap screeningData
ParticleCache targetMap
G4int verbosity
std::map< G4int, G4_c2_const_ptr > sigmaMap
std::map< G4int, G4_c2_const_ptr > MFPTables
Detailed Description
Definition at line 449 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 449 of file G4ScreenedNuclearRecoil.hh
Member Typedef Documentation
typedef G4_c2_function&(* G4NativeScreenedCoulombCrossSection::ScreeningFunc)(G4int z1, G4int z2, size_t nPoints, G4double rMax, G4double *au)
Definition at line 473 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 473 of file G4ScreenedNuclearRecoil.hh
Constructor & Destructor Documentation
G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection ()
Definition at line 961 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 961 of file G4ScreenedNuclearRecoil.cc
References AddScreeningFunction(), LJScreening(), LJZBLScreening(), MoliereScreening(), and ZBLScreening().
Referenced by create().
G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection (const G4NativeScreenedCoulombCrossSection & src) inline
Definition at line 454 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 454 of file G4ScreenedNuclearRecoil.hh
G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection (const G4ScreenedCoulombCrossSection & src) inline
Definition at line 458 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 458 of file G4ScreenedNuclearRecoil.hh
G4NativeScreenedCoulombCrossSection::~G4NativeScreenedCoulombCrossSection () virtual
Definition at line 958 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 958 of file G4ScreenedNuclearRecoil.cc
Member Function Documentation
void G4NativeScreenedCoulombCrossSection::AddScreeningFunction (G4String name, ScreeningFunc fn) inline
Definition at line 476 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 476 of file G4ScreenedNuclearRecoil.hh
References phiMap.
Referenced by G4NativeScreenedCoulombCrossSection().
virtual G4ScreenedCoulombCrossSection* G4NativeScreenedCoulombCrossSection::create () inline virtual
Implements G4ScreenedCoulombCrossSection.
Definition at line 467 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 467 of file G4ScreenedNuclearRecoil.hh
References G4NativeScreenedCoulombCrossSection().
std::vector< G4String > G4NativeScreenedCoulombCrossSection::GetScreeningKeys () const
Definition at line 969 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 969 of file G4ScreenedNuclearRecoil.cc
References phiMap.
void G4NativeScreenedCoulombCrossSection::LoadData (G4String screeningKey, G4int z1, G4double m1, G4double recoilCutoff) virtual
Implements G4ScreenedCoulombCrossSection.
Definition at line 996 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 996 of file G4ScreenedNuclearRecoil.cc
References source.hepunit::amu_c2, angstrom, G4ScreeningTables::au, cm_energy(), e, source.hepunit::elm_coupling, emax, G4ScreeningTables::emin, G4ScreeningTables::EMphiData, eps, FatalException, G4cout, G4endl, G4Exception(), G4Element::GetA(), G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Element::GetZ(), gram, incremental_prev_tag::idx, c2_factory< float_type >::inverse_function(), c2_factory< float_type >::linear(), c2_factory< float_type >::log_log_interpolating_function(), G4ScreeningTables::m1, G4ScreeningTables::m2, material(), mole, G4TrackingService::nMaterials, phiMap, pi, c2_linear_p< float_type >::reset(), G4ScreenedCoulombCrossSection::screeningData, G4ScreenedCoulombCrossSection::sigmaMap, G4ScreenedCoulombCrossSection::standardmass(), theta(), thetac(), G4ScreenedCoulombCrossSection::verbosity, c2_function< float_type >::xmax(), Z, G4ScreeningTables::z1, z1, and G4ScreeningTables::z2.
Member Data Documentation
std::map<std::string, ScreeningFunc> G4NativeScreenedCoulombCrossSection::phiMap private
Definition at line 482 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 482 of file G4ScreenedNuclearRecoil.hh
Referenced by AddScreeningFunction(), GetScreeningKeys(), and LoadData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/G4ScreenedNuclearRecoil.cc