ECCE @ EIC Software: G4ManyFastLists< OBJECT > Class Template Reference
G4ManyFastLists< OBJECT > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh>
Public Types
typedef
G4ManyFastLists_iterator
< OBJECT > iterator
Public Types inherited from G4FastList< OBJECT >::Watcher
enum Priority {
eExtreme, eHigh, eNormal, eLow,
eVeryLow
}
typedef G4FastList< OBJECT > list
Public Member Functions
G4ManyFastLists ()
virtual ~G4ManyFastLists ()=default
virtual void NotifyDeletingList (G4FastList< OBJECT > *__list)
void AddGlobalWatcher (typename G4FastList< OBJECT >::Watcher *watcher)
void Add (G4FastList< OBJECT > *__list)
void Remove (G4FastList< OBJECT > *__list)
bool Holds (OBJECT *__track) const
size_t size () const
void RemoveLists ()
void ClearLists ()
iterator begin ()
iterator end ()
void pop (OBJECT *)
Public Member Functions inherited from G4FastList< OBJECT >::Watcher
Watcher ()
virtual ~Watcher ()
virtual G4String GetWatcherName ()
Priority GetPriority () const
void NotifyDeletingList (G4FastList< OBJECT > *)
virtual void NotifyAddObject (OBJECT *, G4FastList< OBJECT > *)
virtual void NotifyRemoveObject (OBJECT *, G4FastList< OBJECT > *)
void Watch (G4FastList< OBJECT > *fastList)
void StopWatching (G4FastList< OBJECT > *fastList, bool removeWatcher=true)
Protected Types
typedef G4FastList< G4FastList
< OBJECT > > ManyLists
typedef std::set< typename
G4FastList< OBJECT >::Watcher
*, sortWatcher< OBJECT > > WatcherSet
Protected Attributes
ManyLists fAssociatedLists
WatcherSet * fMainListWatchers
Protected Attributes inherited from G4FastList< OBJECT >::Watcher
Priority fPriority
Detailed Description
template<typename OBJECT>
class G4ManyFastLists< OBJECT >
Definition at line 64 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 64 of file G4FastList.hh
Member Typedef Documentation
template<typename OBJECT> typedef G4ManyFastLists_iterator<OBJECT> G4ManyFastLists< OBJECT >::iterator
Definition at line 57 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ManyFastLists.hh
template<typename OBJECT> typedef G4FastList<G4FastList<OBJECT> > G4ManyFastLists< OBJECT >::ManyLists protected
Definition at line 48 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ManyFastLists.hh
template<typename OBJECT> typedef std::set<typename G4FastList<OBJECT>::Watcher*, sortWatcher<OBJECT> > G4ManyFastLists< OBJECT >::WatcherSet protected
Definition at line 53 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ManyFastLists.hh
Constructor & Destructor Documentation
template<typename OBJECT> G4ManyFastLists< OBJECT >::G4ManyFastLists () inline
Definition at line 59 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ManyFastLists.hh
template<typename OBJECT> virtual G4ManyFastLists< OBJECT >::~G4ManyFastLists () virtual default
Member Function Documentation
template<typename OBJECT> void G4ManyFastLists< OBJECT >::Add (G4FastList< OBJECT > * __list) inline
Definition at line 91 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ManyFastLists.hh
Referenced by PriorityList::NewMainList(), and PriorityList::PushToListOfSecondaries().
template<typename OBJECT> void G4ManyFastLists< OBJECT >::AddGlobalWatcher (typename G4FastList< OBJECT >::Watcher * watcher) inline
Definition at line 71 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ManyFastLists.hh
Referenced by G4ITTrackHolder::AddWatcherForMainList().
template<class OBJECT > G4ManyFastLists< OBJECT >::iterator G4ManyFastLists< OBJECT >::begin () inline
Definition at line 371 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 371 of file G4ManyFastLists.hh
References it.
Referenced by G4ITStepProcessor::ComputeInteractionLength(), and G4Scheduler::EndTracking().
template<typename OBJECT> void G4ManyFastLists< OBJECT >::ClearLists () inline
Definition at line 217 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 217 of file G4ManyFastLists.hh
Referenced by G4ITTrackHolder::Clear().
template<class OBJECT > G4ManyFastLists< OBJECT >::iterator G4ManyFastLists< OBJECT >::end () inline
Definition at line 409 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 409 of file G4ManyFastLists.hh
Referenced by G4ITStepProcessor::ComputeInteractionLength(), G4ITStepProcessor::DoIt(), and G4Scheduler::EndTracking().
template<typename OBJECT> bool G4ManyFastLists< OBJECT >::Holds (OBJECT * __track) const inline
Definition at line 172 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ManyFastLists.hh
template<typename OBJECT> virtual void G4ManyFastLists< OBJECT >::NotifyDeletingList (G4FastList< OBJECT > * __list) inline virtual
Definition at line 66 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ManyFastLists.hh
template<typename OBJECT> void G4ManyFastLists< OBJECT >::pop (OBJECT *)
template<typename OBJECT> void G4ManyFastLists< OBJECT >::Remove (G4FastList< OBJECT > * __list) inline
Definition at line 149 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ManyFastLists.hh
Referenced by G4ManyFastLists< G4Track >::RemoveLists().
template<typename OBJECT> void G4ManyFastLists< OBJECT >::RemoveLists () inline
Definition at line 191 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 191 of file G4ManyFastLists.hh
Referenced by G4ITTrackHolder::Clear(), G4ITTrackHolder::MoveMainToWaitingList(), and G4ITTrackHolder::~G4ITTrackHolder().
template<typename OBJECT> size_t G4ManyFastLists< OBJECT >::size (void) const inline
Definition at line 181 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 181 of file G4ManyFastLists.hh
Referenced by G4ITStepProcessor::DoIt(), and G4ITTrackHolder::GetNTracks().
Member Data Documentation
template<typename OBJECT> ManyLists G4ManyFastLists< OBJECT >::fAssociatedLists protected
Definition at line 49 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ManyFastLists.hh
Referenced by G4ManyFastLists< G4Track >::Add(), G4ManyFastLists< G4Track >::AddGlobalWatcher(), G4ManyFastLists< G4Track >::ClearLists(), G4ManyFastLists< G4Track >::Holds(), G4ManyFastLists< G4Track >::NotifyDeletingList(), G4ManyFastLists< G4Track >::Remove(), G4ManyFastLists< G4Track >::RemoveLists(), and G4ManyFastLists< G4Track >::size().
template<typename OBJECT> WatcherSet* G4ManyFastLists< OBJECT >::fMainListWatchers protected
Definition at line 54 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ManyFastLists.hh
Referenced by G4ManyFastLists< G4Track >::Add(), G4ManyFastLists< G4Track >::AddGlobalWatcher(), and G4ManyFastLists< G4Track >::Remove().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ManyFastLists.hh