ECCE @ EIC Software: G4INCL::CoulombNone Class Reference
G4INCL::CoulombNone Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCoulombNone.hh>
Public Member Functions
CoulombNone ()
virtual ~CoulombNone ()
ParticleEntryAvatar * bringToSurface (Particle *const p, Nucleus *const n) const
Position the particle on the surface of the nucleus.
IAvatarList bringToSurface (Cluster *const c, Nucleus *const n) const
Position the cluster on the surface of the nucleus.
void distortOut (ParticleList const &, Nucleus const *const) const
Modify the momenta of the outgoing particles.
G4double maxImpactParameter (ParticleSpecies const &p, const G4double, Nucleus const *const n) const
Return the maximum impact parameter for Coulomb-distorted trajectories.
Public Member Functions inherited from G4INCL::ICoulomb
ICoulomb ()
virtual ~ICoulomb ()
Detailed Description
Definition at line 55 of file G4INCLCoulombNone.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLCoulombNone.hh
Constructor & Destructor Documentation
G4INCL::CoulombNone::CoulombNone () inline
Definition at line 58 of file G4INCLCoulombNone.hh.
View newest version in sPHENIX GitHub at line 58 of file G4INCLCoulombNone.hh
virtual G4INCL::CoulombNone::~CoulombNone () inline virtual
Definition at line 59 of file G4INCLCoulombNone.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLCoulombNone.hh
Member Function Documentation
ParticleEntryAvatar * G4INCL::CoulombNone::bringToSurface (Particle *const p, Nucleus *const n) const virtual
Position the particle on the surface of the nucleus.
This method does not perform any distortion.
Parameters
p incoming particle
n distorting nucleus
Implements G4INCL::ICoulomb.
Definition at line 50 of file G4INCLCoulombNone.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLCoulombNone.cc
References G4INCL::Intersection::exists, G4INCL::IntersectionFactory::getEarlierTrajectoryIntersection(), G4INCL::Particle::getPosition(), G4INCL::Particle::getPropagationVelocity(), G4INCL::Nucleus::getUniverseRadius(), G4INCL::Intersection::position, and G4INCL::Particle::setPosition().
Referenced by G4INCL::CoulombNonRelativistic::bringToSurface().
IAvatarList G4INCL::CoulombNone::bringToSurface (Cluster *const c, Nucleus *const n) const virtual
Position the cluster on the surface of the nucleus.
This method does not perform any distortion.
Parameters
c incoming cluster
n distorting nucleus
Implements G4INCL::ICoulomb.
Definition at line 59 of file G4INCLCoulombNone.cc.
View newest version in sPHENIX GitHub at line 59 of file G4INCLCoulombNone.cc
References E, e, G4INCL::Intersection::exists, G4INCL::IntersectionFactory::getEarlierTrajectoryIntersection(), G4INCL::Cluster::getParticles(), G4INCL::Nucleus::getUniverseRadius(), G4INCL::Intersection::position, and G4INCL::Intersection::time.
void G4INCL::CoulombNone::distortOut (ParticleList const & , Nucleus const * const) const inline virtual
Modify the momenta of the outgoing particles.
This method does not perform any distortion.
Implements G4INCL::ICoulomb.
Definition at line 83 of file G4INCLCoulombNone.hh.
View newest version in sPHENIX GitHub at line 83 of file G4INCLCoulombNone.hh
G4double G4INCL::CoulombNone::maxImpactParameter (ParticleSpecies const & p, const G4double , Nucleus const *const n) const inline virtual
Return the maximum impact parameter for Coulomb-distorted trajectories.
Implements G4INCL::ICoulomb.
Definition at line 87 of file G4INCLCoulombNone.hh.
View newest version in sPHENIX GitHub at line 87 of file G4INCLCoulombNone.hh
References G4INCL::Composite, G4INCL::ParticleTable::getLargestNuclearRadius(), G4INCL::Nucleus::getUniverseRadius(), G4INCL::ParticleSpecies::theA, G4INCL::ParticleSpecies::theType, and G4INCL::ParticleSpecies::theZ.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCoulombNone.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCoulombNone.cc