ECCE @ EIC Software: G4Mag_EqRhs Class Reference
G4Mag_EqRhs Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4Mag_EqRhs.hh>
Public Member Functions
G4Mag_EqRhs (G4MagneticField *magField)
virtual ~G4Mag_EqRhs ()
virtual void EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const =0
G4double FCof () const
virtual void SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double mass)
Public Member Functions inherited from G4EquationOfMotion
G4EquationOfMotion (G4Field *Field)
virtual ~G4EquationOfMotion ()
void RightHandSide (const G4double y[], G4double dydx[]) const
void EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const
void GetFieldValue (const G4double Point[4], G4double Field[]) const
const G4Field * GetFieldObj () const
G4Field * GetFieldObj ()
void SetFieldObj (G4Field *pField)
Private Attributes
G4double fCof_val = 0.0
Static Private Attributes
static const G4double fUnitConstant = 0.299792458 * (GeV/(tesla*m))
Detailed Description
Definition at line 46 of file G4Mag_EqRhs.hh.
View newest version in sPHENIX GitHub at line 46 of file G4Mag_EqRhs.hh
Constructor & Destructor Documentation
G4Mag_EqRhs::G4Mag_EqRhs (G4MagneticField * magField)
Definition at line 39 of file G4Mag_EqRhs.cc.
View newest version in sPHENIX GitHub at line 39 of file G4Mag_EqRhs.cc
G4Mag_EqRhs::~G4Mag_EqRhs () virtual
Definition at line 44 of file G4Mag_EqRhs.cc.
View newest version in sPHENIX GitHub at line 44 of file G4Mag_EqRhs.cc
Member Function Documentation
virtual void G4Mag_EqRhs::EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const pure virtual
Implements G4EquationOfMotion.
Implemented in G4BlineEquation, G4Mag_SpinEqRhs, G4KM_NucleonEqRhs, G4KM_OpticalEqRhs, G4Mag_UsualEqRhs, and G4ErrorMag_UsualEqRhs.
G4double G4Mag_EqRhs::FCof () const inline
Definition at line 62 of file G4Mag_EqRhs.hh.
View newest version in sPHENIX GitHub at line 62 of file G4Mag_EqRhs.hh
References fCof_val.
Referenced by G4MagHelicalStepper::AdvanceHelix(), G4BFieldIntegrationDriver::CurvatureRadius(), G4ErrorMag_UsualEqRhs::EvaluateRhsGivenB(), G4Mag_UsualEqRhs::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), and G4ConstRK4::RightHandSideConst().
void G4Mag_EqRhs::SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double mass) virtual
Implements G4EquationOfMotion.
Reimplemented in G4Mag_UsualEqRhs, G4KM_NucleonEqRhs, G4KM_OpticalEqRhs, and G4Mag_SpinEqRhs.
Definition at line 49 of file G4Mag_EqRhs.cc.
View newest version in sPHENIX GitHub at line 49 of file G4Mag_EqRhs.cc
References source.hepunit::c_light, eplus, fCof_val, and G4ChargeState::GetCharge().
Referenced by G4Mag_SpinEqRhs::SetChargeMomentumMass(), and G4Mag_UsualEqRhs::SetChargeMomentumMass().
Member Data Documentation
G4double G4Mag_EqRhs::fCof_val = 0.0 private
Definition at line 69 of file G4Mag_EqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4Mag_EqRhs.hh
Referenced by FCof(), and SetChargeMomentumMass().
const G4double G4Mag_EqRhs::fUnitConstant = 0.299792458 * (GeV/(tesla*m)) static private
Definition at line 71 of file G4Mag_EqRhs.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Mag_EqRhs.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4Mag_EqRhs.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4Mag_EqRhs.cc