ECCE @ EIC Software: G4EmCalculator Class Reference
G4EmCalculator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmCalculator.hh>
Public Member Functions
G4EmCalculator ()
~G4EmCalculator ()
G4double GetDEDX (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *, const G4Region *r=nullptr)
G4double GetDEDX (G4double kinEnergy, const G4String &part, const G4String &mat, const G4String &s="world")
G4double GetRangeFromRestricteDEDX (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *, const G4Region *r=nullptr)
G4double GetRangeFromRestricteDEDX (G4double kinEnergy, const G4String &part, const G4String &mat, const G4String &s="world")
G4double GetCSDARange (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *, const G4Region *r=nullptr)
G4double GetCSDARange (G4double kinEnergy, const G4String &part, const G4String &mat, const G4String &s="world")
G4double GetRange (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *, const G4Region *r=nullptr)
G4double GetRange (G4double kinEnergy, const G4String &part, const G4String &mat, const G4String &s="world")
G4double GetKinEnergy (G4double range, const G4ParticleDefinition *, const G4Material *, const G4Region *r=nullptr)
G4double GetKinEnergy (G4double range, const G4String &part, const G4String &mat, const G4String &s="world")
G4double GetCrossSectionPerVolume (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, const G4Material *, const G4Region *r=nullptr)
G4double GetCrossSectionPerVolume (G4double kinEnergy, const G4String &part, const G4String &proc, const G4String &mat, const G4String &s="world")
G4double GetShellIonisationCrossSectionPerAtom (const G4String &part, G4int Z, G4AtomicShellEnumerator shell, G4double kinEnergy)
G4double GetMeanFreePath (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, const G4Material *, const G4Region *r=nullptr)
G4double GetMeanFreePath (G4double kinEnergy, const G4String &part, const G4String &proc, const G4String &mat, const G4String &s="world")
void PrintDEDXTable (const G4ParticleDefinition *)
void PrintRangeTable (const G4ParticleDefinition *)
void PrintInverseRangeTable (const G4ParticleDefinition *)
G4double ComputeDEDX (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, const G4Material *, G4double cut=DBL_MAX)
G4double ComputeDEDX (G4double kinEnergy, const G4String &part, const G4String &proc, const G4String &mat, G4double cut=DBL_MAX)
G4double ComputeElectronicDEDX (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *mat, G4double cut=DBL_MAX)
G4double ComputeElectronicDEDX (G4double kinEnergy, const G4String &part, const G4String &mat, G4double cut=DBL_MAX)
G4double ComputeDEDXForCutInRange (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *mat, G4double rangecut=DBL_MAX)
G4double ComputeDEDXForCutInRange (G4double kinEnergy, const G4String &part, const G4String &mat, G4double rangecut=DBL_MAX)
G4double ComputeNuclearDEDX (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *)
G4double ComputeNuclearDEDX (G4double kinEnergy, const G4String &part, const G4String &mat)
G4double ComputeTotalDEDX (G4double kinEnergy, const G4ParticleDefinition *, const G4Material *, G4double cut=DBL_MAX)
G4double ComputeTotalDEDX (G4double kinEnergy, const G4String &part, const G4String &mat, G4double cut=DBL_MAX)
G4double ComputeCrossSectionPerVolume (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, const G4Material *, G4double cut=0.0)
G4double ComputeCrossSectionPerVolume (G4double kinEnergy, const G4String &part, const G4String &proc, const G4String &mat, G4double cut=0.0)
G4double ComputeCrossSectionPerAtom (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, G4double Z, G4double A, G4double cut=0.0)
G4double ComputeCrossSectionPerAtom (G4double kinEnergy, const G4String &part, const G4String &processName, const G4Element *, G4double cut=0.0)
G4double ComputeCrossSectionPerShell (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, G4int Z, G4int shellIdx, G4double cut=0.0)
G4double ComputeCrossSectionPerShell (G4double kinEnergy, const G4String &part, const G4String &processName, const G4Element *, G4int shellIdx, G4double cut=0.0)
G4double ComputeGammaAttenuationLength (G4double kinEnergy, const G4Material *)
G4double ComputeShellIonisationCrossSectionPerAtom (const G4String &part, G4int Z, G4AtomicShellEnumerator shell, G4double kinEnergy, const G4Material *mat=nullptr)
G4double ComputeMeanFreePath (G4double kinEnergy, const G4ParticleDefinition *, const G4String &processName, const G4Material *, G4double cut=0.0)
G4double ComputeMeanFreePath (G4double kinEnergy, const G4String &, const G4String &, const G4String &processName, G4double cut=0.0)
G4double ComputeEnergyCutFromRangeCut (G4double range, const G4ParticleDefinition *, const G4Material *)
G4double ComputeEnergyCutFromRangeCut (G4double range, const G4String &, const G4String &)
const G4ParticleDefinition * FindParticle (const G4String &)
const G4ParticleDefinition * FindIon (G4int Z, G4int A)
const G4Material * FindMaterial (const G4String &)
const G4Region * FindRegion (const G4String &)
const G4MaterialCutsCouple * FindCouple (const G4Material *, const G4Region *r=nullptr)
G4VProcess * FindProcess (const G4ParticleDefinition *part, const G4String &processName)
void SetupMaterial (const G4Material *)
void SetupMaterial (const G4String &)
void SetVerbose (G4int val)
Private Member Functions
G4bool UpdateParticle (const G4ParticleDefinition *, G4double kinEnergy)
G4bool UpdateCouple (const G4Material *, G4double cut)
void FindLambdaTable (const G4ParticleDefinition *, const G4String &processName, G4double kinEnergy, G4int &proctype)
G4bool FindEmModel (const G4ParticleDefinition *, const G4String &processName, G4double kinEnergy)
G4VEnergyLossProcess * FindEnergyLossProcess (const G4ParticleDefinition *)
G4VEnergyLossProcess * FindEnLossProcess (const G4ParticleDefinition *, const G4String &processName)
G4VEmProcess * FindDiscreteProcess (const G4ParticleDefinition *, const G4String &processName)
G4VMultipleScattering * FindMscProcess (const G4ParticleDefinition *, const G4String &processName)
G4bool ActiveForParticle (const G4ParticleDefinition *part, G4VProcess *proc)
void CheckMaterial (G4int Z)
G4EmCalculator & operator= (const G4EmCalculator &right)=delete
G4EmCalculator (const G4EmCalculator &)=delete
Private Attributes
std::vector< const G4Material * > localMaterials
std::vector< const
G4MaterialCutsCouple * > localCouples
G4EmParameters * theParameters
G4LossTableManager * manager
G4NistManager * nist
G4IonTable * ionTable
G4EmCorrections * corr
G4DataVector localCuts
G4int nLocalMaterials
G4int verbose
G4int currentCoupleIndex
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const G4Material * cutMaterial
const G4ParticleDefinition * currentParticle
const G4ParticleDefinition * lambdaParticle
const G4ParticleDefinition * baseParticle
const G4PhysicsTable * currentLambda
G4VEmModel * currentModel
G4VEmModel * loweModel
G4VEnergyLossProcess * currentProcess
G4VProcess * curProcess
const G4ParticleDefinition * theGenericIon
G4ionEffectiveCharge * ionEffCharge
G4DynamicParticle dynParticle
G4String currentName
G4String lambdaName
G4double currentCut
G4double chargeSquare
G4double massRatio
G4double mass
G4double cutenergy [3]
G4bool isIon
G4bool isApplicable
G4String currentParticleName
G4String currentMaterialName
G4String currentProcessName
Detailed Description
Definition at line 82 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 82 of file G4EmCalculator.hh
Constructor & Destructor Documentation
G4EmCalculator::G4EmCalculator ()
Definition at line 74 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 74 of file G4EmCalculator.cc
References baseParticle, chargeSquare, corr, curProcess, currentCouple, currentCoupleIndex, currentCut, currentLambda, currentMaterial, currentMaterialName, currentModel, currentName, currentParticle, currentParticleName, currentProcess, cutenergy, cutMaterial, DBL_MAX, G4LossTableManager::EmCorrections(), G4GenericIon::GenericIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4EmParameters::Instance(), G4LossTableManager::Instance(), G4NistManager::Instance(), ionEffCharge, ionTable, isApplicable, isIon, lambdaName, lambdaParticle, loweModel, manager, mass, massRatio, nist, nLocalMaterials, theGenericIon, theParameters, and verbose.
G4EmCalculator::~G4EmCalculator ()
Definition at line 111 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 111 of file G4EmCalculator.cc
References ionEffCharge, localCouples, and nLocalMaterials.
G4EmCalculator::G4EmCalculator (const G4EmCalculator &) private delete
Member Function Documentation
G4bool G4EmCalculator::ActiveForParticle (const G4ParticleDefinition * part, G4VProcess * proc) private
Definition at line 1248 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1248 of file G4EmCalculator.cc
References G4ProcessManager::GetProcessActivation(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), n, Acts::UnitConstants::pm, and G4ProcessVector::size().
Referenced by ComputeDEDXForCutInRange(), ComputeElectronicDEDX(), FindDiscreteProcess(), FindEnLossProcess(), and FindMscProcess().
void G4EmCalculator::CheckMaterial (G4int Z) private
Definition at line 1286 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1286 of file G4EmCalculator.cc
References currentMaterial, G4NistManager::FindOrBuildSimpleMaterial(), G4Material::GetElement(), G4Material::GetNumberOfElements(), G4Element::GetZasInt(), nist, G4InuclParticleNames::nn, and SetupMaterial().
Referenced by ComputeCrossSectionPerAtom(), and ComputeCrossSectionPerShell().
G4double G4EmCalculator::ComputeCrossSectionPerAtom (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, G4double Z, G4double A, G4double cut = 0.0)
Definition at line 640 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 640 of file G4EmCalculator.cc
References barn, baseParticle, chargeSquare, CheckMaterial(), G4VEmModel::ComputeCrossSectionPerAtom(), currentModel, e, FindEmModel(), Acts::UnitConstants::g, G4cout, G4endl, G4lrint(), G4ParticleDefinition::GetParticleName(), G4VEmModel::InitialiseForElement(), keV, G4EmParameters::LowestElectronEnergy(), massRatio, max, MeV, mole, theParameters, UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), and ComputeCrossSectionPerAtom().
G4double G4EmCalculator::ComputeCrossSectionPerAtom (G4double kinEnergy, const G4String & part, const G4String & processName, const G4Element * elm, G4double cut = 0.0) inline
Definition at line 513 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 513 of file G4EmCalculator.hh
References ComputeCrossSectionPerAtom(), FindParticle(), G4Element::GetN(), and G4Element::GetZ().
G4double G4EmCalculator::ComputeCrossSectionPerShell (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, G4int Z, G4int shellIdx, G4double cut = 0.0)
Definition at line 678 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 678 of file G4EmCalculator.cc
References barn, baseParticle, chargeSquare, CheckMaterial(), G4VEmModel::ComputeCrossSectionPerAtom(), G4VEmModel::ComputeCrossSectionPerShell(), currentModel, e, FindEmModel(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VEmModel::InitialiseForElement(), keV, G4EmParameters::LowestElectronEnergy(), massRatio, max, MeV, theParameters, UpdateParticle(), and verbose.
Referenced by ComputeCrossSectionPerShell().
G4double G4EmCalculator::ComputeCrossSectionPerShell (G4double kinEnergy, const G4String & part, const G4String & processName, const G4Element * elm, G4int shellIdx, G4double cut = 0.0) inline
Definition at line 526 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 526 of file G4EmCalculator.hh
References ComputeCrossSectionPerShell(), FindParticle(), and G4Element::GetZasInt().
G4double G4EmCalculator::ComputeCrossSectionPerVolume (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, const G4Material * mat, G4double cut = 0.0)
Definition at line 605 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 605 of file G4EmCalculator.cc
References baseParticle, chargeSquare, cm, G4VEmModel::CrossSectionPerVolume(), currentModel, e, FindEmModel(), G4cout, G4endl, G4Material::GetName(), G4ParticleDefinition::GetParticleName(), keV, G4EmParameters::LowestElectronEnergy(), massRatio, max, MeV, SetupMaterial(), theParameters, UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), ComputeCrossSectionPerVolume(), ComputeGammaAttenuationLength(), ComputeMeanFreePath(), and GetCrossSectionPerVolume().
G4double G4EmCalculator::ComputeCrossSectionPerVolume (G4double kinEnergy, const G4String & part, const G4String & proc, const G4String & mat, G4double cut = 0.0) inline
Definition at line 498 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 498 of file G4EmCalculator.hh
References ComputeCrossSectionPerVolume(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeDEDX (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, const G4Material * mat, G4double cut = DBL_MAX)
Definition at line 372 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 372 of file G4EmCalculator.cc
References baseParticle, chargeSquare, cm2, G4VEmModel::ComputeDEDXPerVolume(), G4VEmModel::CorrectionsAlongStep(), currentMaterialName, currentModel, dynParticle, FindCouple(), FindEmModel(), G4cout, G4endl, G4VEmModel::GetChargeSquareRatio(), G4Material::GetDensity(), G4VEmModel::GetName(), G4ParticleDefinition::GetParticleName(), gram, isIon, BTOF::length, loweModel, G4VEmModel::LowEnergyLimit(), massRatio, MeV, mm, CLHEP::nm, r, G4DynamicParticle::SetKineticEnergy(), SetupMaterial(), UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), ComputeDEDX(), ComputeDEDXForCutInRange(), ComputeElectronicDEDX(), and RunAction::CriticalEnergy().
G4double G4EmCalculator::ComputeDEDX (G4double kinEnergy, const G4String & part, const G4String & proc, const G4String & mat, G4double cut = DBL_MAX) inline
Definition at line 474 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 474 of file G4EmCalculator.hh
References ComputeDEDX(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeDEDXForCutInRange (G4double kinEnergy, const G4ParticleDefinition * part, const G4Material * mat, G4double rangecut = DBL_MAX)
Definition at line 521 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 521 of file G4EmCalculator.cc
References ActiveForParticle(), ComputeDEDX(), ComputeEnergyCutFromRangeCut(), cutenergy, cutMaterial, G4Electron::Electron(), G4Gamma::Gamma(), G4LossTableManager::GetEnergyLossProcessVector(), incremental_prev_tag::idx, G4LossTableManager::Instance(), mat, n, G4Positron::Positron(), SetupMaterial(), and UpdateParticle().
Referenced by ComputeDEDXForCutInRange().
G4double G4EmCalculator::ComputeDEDXForCutInRange (G4double kinEnergy, const G4String & part, const G4String & mat, G4double rangecut = DBL_MAX) inline
Definition at line 451 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 451 of file G4EmCalculator.hh
References ComputeDEDXForCutInRange(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeElectronicDEDX (G4double kinEnergy, const G4ParticleDefinition * part, const G4Material * mat, G4double cut = DBL_MAX)
Definition at line 488 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 488 of file G4EmCalculator.cc
References ActiveForParticle(), ComputeDEDX(), G4LossTableManager::GetEnergyLossProcessVector(), G4LossTableManager::Instance(), n, SetupMaterial(), and UpdateParticle().
Referenced by ComputeElectronicDEDX(), ComputeTotalDEDX(), Run::EndOfRun(), and HadrontherapyLet::FillEnergySpectrum().
G4double G4EmCalculator::ComputeElectronicDEDX (G4double kinEnergy, const G4String & part, const G4String & mat, G4double cut = DBL_MAX) inline
Definition at line 441 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 441 of file G4EmCalculator.hh
References ComputeElectronicDEDX(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeEnergyCutFromRangeCut (G4double range, const G4ParticleDefinition * part, const G4Material * mat)
Definition at line 770 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 770 of file G4EmCalculator.cc
References G4ProductionCutsTable::GetProductionCutsTable().
Referenced by ComputeDEDXForCutInRange(), and ComputeEnergyCutFromRangeCut().
G4double G4EmCalculator::ComputeEnergyCutFromRangeCut (G4double range, const G4String & particle, const G4String & material) inline
Definition at line 539 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 539 of file G4EmCalculator.hh
References ComputeEnergyCutFromRangeCut(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeGammaAttenuationLength (G4double kinEnergy, const G4Material * mat)
Definition at line 715 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 715 of file G4EmCalculator.cc
References ComputeCrossSectionPerVolume(), and G4Gamma::Gamma().
G4double G4EmCalculator::ComputeMeanFreePath (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, const G4Material * mat, G4double cut = 0.0)
Definition at line 749 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 749 of file G4EmCalculator.cc
References ComputeCrossSectionPerVolume(), DBL_MAX, G4cout, G4endl, G4Material::GetName(), G4ParticleDefinition::GetParticleName(), MeV, mfp, mm, verbose, and x.
Referenced by ComputeMeanFreePath().
G4double G4EmCalculator::ComputeMeanFreePath (G4double kinEnergy, const G4String & particle, const G4String & processName, const G4String & processName, G4double cut = 0.0) inline
Definition at line 551 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 551 of file G4EmCalculator.hh
References ComputeMeanFreePath(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeNuclearDEDX (G4double kinEnergy, const G4ParticleDefinition * p, const G4Material * mat)
Definition at line 579 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 579 of file G4EmCalculator.cc
References cm2, G4VEmModel::ComputeDEDXPerVolume(), FindDiscreteProcess(), G4cout, G4endl, G4Material::GetDensity(), G4VEmProcess::GetModelByIndex(), G4ParticleDefinition::GetParticleName(), gram, MeV, mm, G4VEmModel::SetFluctuationFlag(), and verbose.
Referenced by ComputeNuclearDEDX(), and ComputeTotalDEDX().
G4double G4EmCalculator::ComputeNuclearDEDX (G4double kinEnergy, const G4String & part, const G4String & mat) inline
Definition at line 487 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 487 of file G4EmCalculator.hh
References ComputeNuclearDEDX(), FindMaterial(), and FindParticle().
G4double G4EmCalculator::ComputeShellIonisationCrossSectionPerAtom (const G4String & part, G4int Z, G4AtomicShellEnumerator shell, G4double kinEnergy, const G4Material * mat = nullptr)
Definition at line 730 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 730 of file G4EmCalculator.cc
References G4LossTableManager::AtomDeexcitation(), G4VAtomDeexcitation::ComputeShellIonisationCrossSectionPerAtom(), FindParticle(), and manager.
G4double G4EmCalculator::ComputeTotalDEDX (G4double kinEnergy, const G4ParticleDefinition * part, const G4Material * mat, G4double cut = DBL_MAX)
Definition at line 567 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 567 of file G4EmCalculator.cc
References ComputeElectronicDEDX(), ComputeNuclearDEDX(), mass, and MeV.
Referenced by ComputeTotalDEDX(), RunAction::GetEnergyFromCSDARange(), HadrontherapyInteractionParameters::GetStopping(), and HadrontherapyInteractionParameters::GetStoppingTable().
G4double G4EmCalculator::ComputeTotalDEDX (G4double kinEnergy, const G4String & part, const G4String & mat, G4double cut = DBL_MAX) inline
Definition at line 463 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 463 of file G4EmCalculator.hh
References ComputeTotalDEDX(), FindMaterial(), and FindParticle().
const G4MaterialCutsCouple * G4EmCalculator::FindCouple (const G4Material * material, const G4Region * r = nullptr)
Definition at line 901 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 901 of file G4EmCalculator.cc
References currentMaterial, currentMaterialName, FatalException, G4Exception(), G4RegionStore::GetInstance(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Region::GetName(), G4Region::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), r, and SetupMaterial().
Referenced by ComputeDEDX(), export_G4EmCalculator(), GetCrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetKinEnergy(), and GetRangeFromRestricteDEDX().
G4VEmProcess * G4EmCalculator::FindDiscreteProcess (const G4ParticleDefinition * part, const G4String & processName) private
Definition at line 1184 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1184 of file G4EmCalculator.cc
References ActiveForParticle(), G4LossTableManager::GetEmProcessVector(), manager, n, and v.
Referenced by ComputeNuclearDEDX(), FindEmModel(), FindLambdaTable(), and GetCrossSectionPerVolume().
G4bool G4EmCalculator::FindEmModel (const G4ParticleDefinition * p, const G4String & processName, G4double kinEnergy) private
Definition at line 1035 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1035 of file G4EmCalculator.cc
References currentMaterial, currentModel, currentName, CLHEP::eV, FindDiscreteProcess(), FindEnLossProcess(), FindMscProcess(), G4cout, G4endl, G4VEmModel::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4VProcess::GetProcessName(), incremental_prev_tag::idx, G4VEmModel::InitialiseForMaterial(), isApplicable, isIon, loweModel, G4VEmModel::LowEnergyLimit(), massRatio, MeV, part, G4VMultipleScattering::SelectModel(), G4VEmProcess::SelectModelForMaterial(), G4VEnergyLossProcess::SelectModelForMaterial(), G4VEmModel::SetupForMaterial(), theGenericIon, and verbose.
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), GetCrossSectionPerVolume(), and GetDEDX().
G4VEnergyLossProcess * G4EmCalculator::FindEnergyLossProcess (const G4ParticleDefinition * p) private
Definition at line 1133 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1133 of file G4EmCalculator.cc
References currentParticleName, G4LossTableManager::GetEnergyLossProcess(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), manager, part, and theGenericIon.
Referenced by PrintDEDXTable(), PrintInverseRangeTable(), PrintRangeTable(), and UpdateParticle().
G4VEnergyLossProcess * G4EmCalculator::FindEnLossProcess (const G4ParticleDefinition * part, const G4String & processName) private
Definition at line 1162 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1162 of file G4EmCalculator.cc
References ActiveForParticle(), G4LossTableManager::GetEnergyLossProcessVector(), manager, n, and v.
Referenced by FindEmModel(), and FindLambdaTable().
const G4ParticleDefinition * G4EmCalculator::FindIon (G4int Z, G4int A)
Definition at line 866 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 866 of file G4EmCalculator.cc
References G4IonTable::GetIon(), and ionTable.
void G4EmCalculator::FindLambdaTable (const G4ParticleDefinition * p, const G4String & processName, G4double kinEnergy, G4int & proctype) private
Definition at line 965 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 965 of file G4EmCalculator.cc
References curProcess, currentLambda, currentModel, currentName, FindDiscreteProcess(), FindEnLossProcess(), FindMscProcess(), G4cout, G4endl, G4VEmModel::GetCrossSectionTable(), isApplicable, isIon, lambdaName, lambdaParticle, G4VEmProcess::LambdaTable(), G4VEnergyLossProcess::LambdaTable(), loweModel, part, G4VMultipleScattering::SelectModel(), theGenericIon, and verbose.
Referenced by GetCrossSectionPerVolume().
const G4Material * G4EmCalculator::FindMaterial (const G4String & name)
Definition at line 874 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 874 of file G4EmCalculator.cc
References currentMaterial, currentMaterialName, G4cout, G4endl, G4Material::GetMaterial(), and SetupMaterial().
Referenced by ComputeCrossSectionPerVolume(), ComputeDEDX(), ComputeDEDXForCutInRange(), ComputeElectronicDEDX(), ComputeEnergyCutFromRangeCut(), ComputeMeanFreePath(), ComputeNuclearDEDX(), ComputeTotalDEDX(), export_G4EmCalculator(), GetCrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetKinEnergy(), GetMeanFreePath(), GetRange(), and GetRangeFromRestricteDEDX().
G4VMultipleScattering * G4EmCalculator::FindMscProcess (const G4ParticleDefinition * part, const G4String & processName) private
Definition at line 1209 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1209 of file G4EmCalculator.cc
References ActiveForParticle(), G4LossTableManager::GetMultipleScatteringVector(), manager, n, and v.
Referenced by FindEmModel(), and FindLambdaTable().
const G4ParticleDefinition * G4EmCalculator::FindParticle (const G4String & name)
Definition at line 849 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 849 of file G4EmCalculator.cc
References currentParticle, currentParticleName, G4ParticleTable::FindParticle(), G4cout, G4endl, and G4ParticleTable::GetParticleTable().
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), ComputeDEDXForCutInRange(), ComputeElectronicDEDX(), ComputeEnergyCutFromRangeCut(), ComputeMeanFreePath(), ComputeNuclearDEDX(), ComputeShellIonisationCrossSectionPerAtom(), ComputeTotalDEDX(), export_G4EmCalculator(), GetCrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetKinEnergy(), GetMeanFreePath(), GetRange(), GetRangeFromRestricteDEDX(), GetShellIonisationCrossSectionPerAtom(), and HadrontherapyInteractionParameters::ParseArg().
G4VProcess * G4EmCalculator::FindProcess (const G4ParticleDefinition * part, const G4String & processName)
Definition at line 1230 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1230 of file G4EmCalculator.cc
References G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), and G4ProcessVector::size().
const G4Region * G4EmCalculator::FindRegion (const G4String & reg)
Definition at line 888 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 888 of file G4EmCalculator.cc
References G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), and r.
Referenced by export_G4EmCalculator(), GetCrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetKinEnergy(), GetMeanFreePath(), GetRange(), and GetRangeFromRestricteDEDX().
G4double G4EmCalculator::GetCrossSectionPerVolume (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 254 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 254 of file G4EmCalculator.cc
References chargeSquare, cm, ComputeCrossSectionPerVolume(), G4VEmProcess::CrossSectionPerVolume(), currentLambda, currentModel, DBL_MAX, e, FindCouple(), FindDiscreteProcess(), FindEmModel(), FindLambdaTable(), G4cout, G4endl, G4MaterialCutsCouple::GetIndex(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4VMscModel::GetTransportMeanFreePath(), incremental_prev_tag::idx, massRatio, MeV, G4VEmModel::SetCurrentCouple(), UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), Run::EndOfRun(), GetCrossSectionPerVolume(), and GetMeanFreePath().
G4double G4EmCalculator::GetCrossSectionPerVolume (G4double kinEnergy, const G4String & part, const G4String & proc, const G4String & mat, const G4String & s = "world") inline
Definition at line 415 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 415 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetCrossSectionPerVolume().
G4double G4EmCalculator::GetCSDARange (G4double kinEnergy, const G4ParticleDefinition * p, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 185 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 185 of file G4EmCalculator.cc
References G4EmParameters::BuildCSDARange(), FindCouple(), G4cout, G4endl, G4Exception(), G4LossTableManager::GetCSDARange(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), JustWarning, manager, MeV, mm, theParameters, UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), GetCSDARange(), RunAction::GetEnergyFromCSDARange(), GetRange(), and Run::Run().
G4double G4EmCalculator::GetCSDARange (G4double kinEnergy, const G4String & part, const G4String & mat, const G4String & s = "world") inline
Definition at line 381 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 381 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetCSDARange().
G4double G4EmCalculator::GetDEDX (G4double kinEnergy, const G4ParticleDefinition * p, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 121 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 121 of file G4EmCalculator.cc
References cm2, G4VEmModel::CorrectionsAlongStep(), currentModel, currentProcessName, dynParticle, FindCouple(), FindEmModel(), G4cout, G4endl, G4VEmModel::GetChargeSquareRatio(), G4LossTableManager::GetDEDX(), G4Material::GetDensity(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), gram, isIon, BTOF::length, manager, MeV, mm, CLHEP::nm, G4DynamicParticle::SetKineticEnergy(), UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), Run::EndOfRun(), GetDEDX(), RunAction::GetEnergyFromRestrictedRange(), Run::Run(), and G4EnergySplitter::SplitEnergyInVolumes().
G4double G4EmCalculator::GetDEDX (G4double kinEnergy, const G4String & part, const G4String & mat, const G4String & s = "world") inline
Definition at line 359 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 359 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetDEDX().
G4double G4EmCalculator::GetKinEnergy (G4double range, const G4ParticleDefinition * p, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 232 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 232 of file G4EmCalculator.cc
References FindCouple(), G4cout, G4endl, G4LossTableManager::GetEnergy(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), GeV, manager, MeV, mm, UpdateParticle(), and verbose.
Referenced by GetKinEnergy().
G4double G4EmCalculator::GetKinEnergy (G4double range, const G4String & part, const G4String & mat, const G4String & s = "world") inline
Definition at line 405 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 405 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetKinEnergy().
G4double G4EmCalculator::GetMeanFreePath (G4double kinEnergy, const G4ParticleDefinition * p, const G4String & processName, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 323 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 323 of file G4EmCalculator.cc
References DBL_MAX, G4cout, G4endl, GetCrossSectionPerVolume(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), MeV, mm, verbose, and x.
Referenced by RunAction::BeginOfRunAction(), and GetMeanFreePath().
G4double G4EmCalculator::GetMeanFreePath (G4double kinEnergy, const G4String & part, const G4String & proc, const G4String & mat, const G4String & s = "world") inline
Definition at line 428 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 428 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetMeanFreePath().
G4double G4EmCalculator::GetRange (G4double kinEnergy, const G4ParticleDefinition * p, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 216 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 216 of file G4EmCalculator.cc
References G4EmParameters::BuildCSDARange(), GetCSDARange(), GetRangeFromRestricteDEDX(), and theParameters.
Referenced by Run::EndOfRun(), and GetRange().
G4double G4EmCalculator::GetRange (G4double kinEnergy, const G4String & part, const G4String & mat, const G4String & s = "world") inline
Definition at line 393 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 393 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetRange().
G4double G4EmCalculator::GetRangeFromRestricteDEDX (G4double kinEnergy, const G4ParticleDefinition * p, const G4Material * mat, const G4Region * r = nullptr)
Definition at line 162 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 162 of file G4EmCalculator.cc
References FindCouple(), G4cout, G4endl, G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4LossTableManager::GetRangeFromRestricteDEDX(), manager, MeV, mm, UpdateParticle(), and verbose.
Referenced by RunAction::BeginOfRunAction(), RunAction::GetEnergyFromRestrictedRange(), GetRange(), and GetRangeFromRestricteDEDX().
G4double G4EmCalculator::GetRangeFromRestricteDEDX (G4double kinEnergy, const G4String & part, const G4String & mat, const G4String & s = "world") inline
Definition at line 369 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 369 of file G4EmCalculator.hh
References FindMaterial(), FindParticle(), FindRegion(), and GetRangeFromRestricteDEDX().
G4double G4EmCalculator::GetShellIonisationCrossSectionPerAtom (const G4String & part, G4int Z, G4AtomicShellEnumerator shell, G4double kinEnergy)
Definition at line 306 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 306 of file G4EmCalculator.cc
References G4LossTableManager::AtomDeexcitation(), FindParticle(), G4VAtomDeexcitation::GetShellIonisationCrossSectionPerAtom(), and manager.
G4EmCalculator& G4EmCalculator::operator= (const G4EmCalculator & right) private delete
void G4EmCalculator::PrintDEDXTable (const G4ParticleDefinition * p)
Definition at line 344 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 344 of file G4EmCalculator.cc
References G4VEnergyLossProcess::DEDXTable(), FindEnergyLossProcess(), G4cout, G4endl, and G4ParticleDefinition::GetParticleName().
Referenced by export_G4EmCalculator().
void G4EmCalculator::PrintInverseRangeTable (const G4ParticleDefinition * p)
Definition at line 362 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 362 of file G4EmCalculator.cc
References FindEnergyLossProcess(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), and G4VEnergyLossProcess::InverseRangeTable().
Referenced by export_G4EmCalculator().
void G4EmCalculator::PrintRangeTable (const G4ParticleDefinition * p)
Definition at line 353 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 353 of file G4EmCalculator.cc
References FindEnergyLossProcess(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), and G4VEnergyLossProcess::RangeTableForLoss().
Referenced by export_G4EmCalculator().
void G4EmCalculator::SetupMaterial (const G4Material * mat)
Definition at line 1266 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1266 of file G4EmCalculator.cc
References currentMaterial, currentMaterialName, G4Material::GetName(), and mat.
Referenced by CheckMaterial(), ComputeCrossSectionPerVolume(), ComputeDEDX(), ComputeDEDXForCutInRange(), ComputeElectronicDEDX(), FindCouple(), FindMaterial(), SetupMaterial(), and UpdateCouple().
void G4EmCalculator::SetupMaterial (const G4String & mname)
Definition at line 1279 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1279 of file G4EmCalculator.cc
References G4NistManager::FindOrBuildMaterial(), nist, and SetupMaterial().
void G4EmCalculator::SetVerbose (G4int val)
Definition at line 1305 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 1305 of file G4EmCalculator.cc
References verbose.
Referenced by export_G4EmCalculator().
G4bool G4EmCalculator::UpdateCouple (const G4Material * material, G4double cut) private
Definition at line 940 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 940 of file G4EmCalculator.cc
References currentCouple, currentCoupleIndex, currentCut, currentMaterial, G4MaterialCutsCouple::GetIndex(), localCouples, localCuts, localMaterials, nLocalMaterials, and SetupMaterial().
G4bool G4EmCalculator::UpdateParticle (const G4ParticleDefinition * p, G4double kinEnergy) private
Definition at line 781 of file G4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 781 of file G4EmCalculator.cc
References G4VEnergyLossProcess::BaseParticle(), baseParticle, chargeSquare, corr, currentMaterial, currentParticle, currentParticleName, currentProcess, currentProcessName, dynParticle, G4EmCorrections::EffectiveChargeCorrection(), G4EmCorrections::EffectiveChargeSquareRatio(), FindEnergyLossProcess(), G4cout, G4endl, G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4VProcess::GetProcessName(), isIon, mass, massRatio, G4DynamicParticle::SetDefinition(), G4VEnergyLossProcess::SetDynamicMassCharge(), G4DynamicParticle::SetKineticEnergy(), theGenericIon, and verbose.
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), ComputeDEDXForCutInRange(), ComputeElectronicDEDX(), GetCrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetKinEnergy(), and GetRangeFromRestricteDEDX().
Member Data Documentation
const G4ParticleDefinition* G4EmCalculator::baseParticle private
Definition at line 328 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 328 of file G4EmCalculator.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), G4EmCalculator(), and UpdateParticle().
G4double G4EmCalculator::chargeSquare private
Definition at line 343 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 343 of file G4EmCalculator.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), G4EmCalculator(), GetCrossSectionPerVolume(), and UpdateParticle().
G4EmCorrections* G4EmCalculator::corr private
Definition at line 315 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 315 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), and UpdateParticle().
G4VProcess* G4EmCalculator::curProcess private
Definition at line 334 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 334 of file G4EmCalculator.hh
Referenced by FindLambdaTable(), and G4EmCalculator().
const G4MaterialCutsCouple* G4EmCalculator::currentCouple private
Definition at line 323 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 323 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), and UpdateCouple().
G4int G4EmCalculator::currentCoupleIndex private
Definition at line 322 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 322 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), and UpdateCouple().
G4double G4EmCalculator::currentCut private
Definition at line 342 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 342 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), and UpdateCouple().
const G4PhysicsTable* G4EmCalculator::currentLambda private
Definition at line 329 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 329 of file G4EmCalculator.hh
Referenced by FindLambdaTable(), G4EmCalculator(), and GetCrossSectionPerVolume().
const G4Material* G4EmCalculator::currentMaterial private
Definition at line 324 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 324 of file G4EmCalculator.hh
Referenced by CheckMaterial(), FindCouple(), FindEmModel(), FindMaterial(), G4EmCalculator(), SetupMaterial(), UpdateCouple(), and UpdateParticle().
G4String G4EmCalculator::currentMaterialName private
Definition at line 351 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 351 of file G4EmCalculator.hh
Referenced by ComputeDEDX(), FindCouple(), FindMaterial(), G4EmCalculator(), and SetupMaterial().
G4VEmModel* G4EmCalculator::currentModel private
Definition at line 331 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 331 of file G4EmCalculator.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), FindEmModel(), FindLambdaTable(), G4EmCalculator(), GetCrossSectionPerVolume(), and GetDEDX().
G4String G4EmCalculator::currentName private
Definition at line 340 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 340 of file G4EmCalculator.hh
Referenced by FindEmModel(), FindLambdaTable(), and G4EmCalculator().
const G4ParticleDefinition* G4EmCalculator::currentParticle private
Definition at line 326 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 326 of file G4EmCalculator.hh
Referenced by FindParticle(), G4EmCalculator(), and UpdateParticle().
G4String G4EmCalculator::currentParticleName private
Definition at line 350 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 350 of file G4EmCalculator.hh
Referenced by FindEnergyLossProcess(), FindParticle(), G4EmCalculator(), and UpdateParticle().
G4VEnergyLossProcess* G4EmCalculator::currentProcess private
Definition at line 333 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 333 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), and UpdateParticle().
G4String G4EmCalculator::currentProcessName private
Definition at line 352 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 352 of file G4EmCalculator.hh
Referenced by GetDEDX(), and UpdateParticle().
G4double G4EmCalculator::cutenergy[3] private
Definition at line 346 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 346 of file G4EmCalculator.hh
Referenced by ComputeDEDXForCutInRange(), and G4EmCalculator().
const G4Material* G4EmCalculator::cutMaterial private
Definition at line 325 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 325 of file G4EmCalculator.hh
Referenced by ComputeDEDXForCutInRange(), and G4EmCalculator().
G4DynamicParticle G4EmCalculator::dynParticle private
Definition at line 338 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 338 of file G4EmCalculator.hh
Referenced by ComputeDEDX(), GetDEDX(), and UpdateParticle().
G4ionEffectiveCharge* G4EmCalculator::ionEffCharge private
Definition at line 337 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 337 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), and ~G4EmCalculator().
G4IonTable* G4EmCalculator::ionTable private
Definition at line 314 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 314 of file G4EmCalculator.hh
Referenced by FindIon(), and G4EmCalculator().
G4bool G4EmCalculator::isApplicable private
Definition at line 348 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 348 of file G4EmCalculator.hh
Referenced by FindEmModel(), FindLambdaTable(), and G4EmCalculator().
G4bool G4EmCalculator::isIon private
Definition at line 347 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 347 of file G4EmCalculator.hh
Referenced by ComputeDEDX(), FindEmModel(), FindLambdaTable(), G4EmCalculator(), GetDEDX(), and UpdateParticle().
G4String G4EmCalculator::lambdaName private
Definition at line 341 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 341 of file G4EmCalculator.hh
Referenced by FindLambdaTable(), and G4EmCalculator().
const G4ParticleDefinition* G4EmCalculator::lambdaParticle private
Definition at line 327 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 327 of file G4EmCalculator.hh
Referenced by FindLambdaTable(), and G4EmCalculator().
std::vector<const G4MaterialCutsCouple*> G4EmCalculator::localCouples private
Definition at line 309 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 309 of file G4EmCalculator.hh
Referenced by UpdateCouple(), and ~G4EmCalculator().
G4DataVector G4EmCalculator::localCuts private
Definition at line 316 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 316 of file G4EmCalculator.hh
Referenced by UpdateCouple().
std::vector<const G4Material*> G4EmCalculator::localMaterials private
Definition at line 308 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 308 of file G4EmCalculator.hh
Referenced by UpdateCouple().
G4VEmModel* G4EmCalculator::loweModel private
Definition at line 332 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 332 of file G4EmCalculator.hh
Referenced by ComputeDEDX(), FindEmModel(), FindLambdaTable(), and G4EmCalculator().
G4LossTableManager* G4EmCalculator::manager private
Definition at line 312 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 312 of file G4EmCalculator.hh
Referenced by ComputeShellIonisationCrossSectionPerAtom(), FindDiscreteProcess(), FindEnergyLossProcess(), FindEnLossProcess(), FindMscProcess(), G4EmCalculator(), GetCSDARange(), GetDEDX(), GetKinEnergy(), GetRangeFromRestricteDEDX(), and GetShellIonisationCrossSectionPerAtom().
G4double G4EmCalculator::mass private
Definition at line 345 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 345 of file G4EmCalculator.hh
Referenced by ComputeTotalDEDX(), G4EmCalculator(), and UpdateParticle().
G4double G4EmCalculator::massRatio private
Definition at line 344 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 344 of file G4EmCalculator.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), FindEmModel(), G4EmCalculator(), GetCrossSectionPerVolume(), and UpdateParticle().
G4NistManager* G4EmCalculator::nist private
Definition at line 313 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 313 of file G4EmCalculator.hh
Referenced by CheckMaterial(), G4EmCalculator(), and SetupMaterial().
G4int G4EmCalculator::nLocalMaterials private
Definition at line 317 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 317 of file G4EmCalculator.hh
Referenced by G4EmCalculator(), UpdateCouple(), and ~G4EmCalculator().
const G4ParticleDefinition* G4EmCalculator::theGenericIon private
Definition at line 336 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 336 of file G4EmCalculator.hh
Referenced by FindEmModel(), FindEnergyLossProcess(), FindLambdaTable(), G4EmCalculator(), and UpdateParticle().
G4EmParameters* G4EmCalculator::theParameters private
Definition at line 311 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 311 of file G4EmCalculator.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), G4EmCalculator(), GetCSDARange(), and GetRange().
G4int G4EmCalculator::verbose private
Definition at line 319 of file G4EmCalculator.hh.
View newest version in sPHENIX GitHub at line 319 of file G4EmCalculator.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeCrossSectionPerShell(), ComputeCrossSectionPerVolume(), ComputeDEDX(), ComputeMeanFreePath(), ComputeNuclearDEDX(), FindEmModel(), FindLambdaTable(), G4EmCalculator(), GetCrossSectionPerVolume(), GetCSDARange(), GetDEDX(), GetKinEnergy(), GetMeanFreePath(), GetRangeFromRestricteDEDX(), SetVerbose(), and UpdateParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmCalculator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmCalculator.cc