ECCE @ EIC Software: G4XAqmTotal Class Reference
G4XAqmTotal Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XAqmTotal.hh>
Public Member Functions
G4XAqmTotal ()
virtual ~G4XAqmTotal ()
G4bool operator== (const G4XAqmTotal &right) const
G4bool operator!= (const G4XAqmTotal &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual G4String Name () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Private Member Functions
G4XAqmTotal (const G4XAqmTotal &right)
const G4XAqmTotal & operator= (const G4XAqmTotal &right)
Static Private Attributes
static const G4double _lowLimit = 0.
static const G4double _highLimit = DBL_MAX
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 37 of file G4XAqmTotal.hh.
View newest version in sPHENIX GitHub at line 37 of file G4XAqmTotal.hh
Constructor & Destructor Documentation
G4XAqmTotal::G4XAqmTotal ()
Definition at line 58 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 58 of file G4XAqmTotal.cc
G4XAqmTotal::~G4XAqmTotal () virtual
Definition at line 65 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 65 of file G4XAqmTotal.cc
G4XAqmTotal::G4XAqmTotal (const G4XAqmTotal & right) private
Member Function Documentation
G4double G4XAqmTotal::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 81 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 81 of file G4XAqmTotal.cc
References G4ParticleDefinition::GetAntiQuarkContent(), G4KineticTrack::GetDefinition(), G4Pow::GetInstance(), G4ParticleDefinition::GetQuarkContent(), millibarn, and G4Pow::powN().
Referenced by G4XAqmElastic::CrossSection().
virtual const G4CrossSectionVector* G4XAqmTotal::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 51 of file G4XAqmTotal.hh.
View newest version in sPHENIX GitHub at line 51 of file G4XAqmTotal.hh
G4bool G4XAqmTotal::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 133 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 133 of file G4XAqmTotal.cc
References _highLimit, _lowLimit, and G4VCrossSectionSource::InLimits().
G4String G4XAqmTotal::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 125 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 125 of file G4XAqmTotal.cc
G4bool G4XAqmTotal::operator!= (const G4XAqmTotal & right) const
Definition at line 75 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 75 of file G4XAqmTotal.cc
const G4XAqmTotal& G4XAqmTotal::operator= (const G4XAqmTotal & right) private
G4bool G4XAqmTotal::operator== (const G4XAqmTotal & right) const
Definition at line 69 of file G4XAqmTotal.cc.
View newest version in sPHENIX GitHub at line 69 of file G4XAqmTotal.cc
Member Data Documentation
const G4double G4XAqmTotal::_highLimit = DBL_MAX static private
Definition at line 67 of file G4XAqmTotal.hh.
View newest version in sPHENIX GitHub at line 67 of file G4XAqmTotal.hh
Referenced by IsValid().
const G4double G4XAqmTotal::_lowLimit = 0. static private
Definition at line 66 of file G4XAqmTotal.hh.
View newest version in sPHENIX GitHub at line 66 of file G4XAqmTotal.hh
Referenced by IsValid().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XAqmTotal.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XAqmTotal.cc