ECCE @ EIC Software: G4ITTransportationManager Class Reference
G4ITTransportationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTransportationManager.hh>
Public Member Functions
G4ITNavigator * GetNavigatorForTracking () const
void SetWorldForTracking (G4VPhysicalVolume *theWorld)
size_t GetNoActiveNavigators () const
std::vector< G4ITNavigator * >
::iterator GetActiveNavigatorsIterator ()
size_t GetNoWorlds () const
std::vector< G4VPhysicalVolume * >
::iterator GetWorldsIterator ()
G4ITSafetyHelper * GetSafetyHelper () const
G4VPhysicalVolume * GetParallelWorld (const G4String &worldName)
G4VPhysicalVolume * IsWorldExisting (const G4String &worldName)
G4ITNavigator * GetNavigator (const G4String &worldName)
G4ITNavigator * GetNavigator (G4VPhysicalVolume *aWorld)
G4bool RegisterWorld (G4VPhysicalVolume *aWorld)
void DeRegisterNavigator (G4ITNavigator *aNavigator)
G4int ActivateNavigator (G4ITNavigator *aNavigator)
void DeActivateNavigator (G4ITNavigator *aNavigator)
void InactivateAll ()
Static Public Member Functions
static void DeleteInstance ()
static G4ITTransportationManager * GetTransportationManager ()
Private Member Functions
void ClearNavigators ()
void DeRegisterWorld (G4VPhysicalVolume *aWorld)
G4ITTransportationManager ()
~G4ITTransportationManager ()
void Initialize ()
Private Attributes
G4ITSafetyHelper * fpSafetyHelper
std::vector< G4ITNavigator * > fNavigators
std::vector< G4ITNavigator * > fActiveNavigators
std::vector< G4VPhysicalVolume * > fWorlds
Static Private Attributes
static G4ThreadLocal
G4ITTransportationManager * fpInstance
{Duplicated version of G4TransportationManager. This class just contains the pointer to the navigator object of the simulation.}
Detailed Description
Definition at line 61 of file G4ITTransportationManager.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ITTransportationManager.hh
Constructor & Destructor Documentation
G4ITTransportationManager::G4ITTransportationManager () private
Definition at line 45 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ITTransportationManager.cc
References Initialize().
Referenced by GetTransportationManager().
G4ITTransportationManager::~G4ITTransportationManager () private
Definition at line 50 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ITTransportationManager.cc
References ClearNavigators(), and fpSafetyHelper.
Member Function Documentation
G4int G4ITTransportationManager::ActivateNavigator (G4ITNavigator * aNavigator)
Definition at line 267 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 267 of file G4ITTransportationManager.cc
References fActiveNavigators, fNavigators, G4Exception(), JustWarning, and message().
void G4ITTransportationManager::ClearNavigators () private
Definition at line 71 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ITTransportationManager.cc
References fActiveNavigators, fNavigators, and fWorlds.
Referenced by ~G4ITTransportationManager().
void G4ITTransportationManager::DeActivateNavigator (G4ITNavigator * aNavigator)
Definition at line 305 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 305 of file G4ITTransportationManager.cc
References fActiveNavigators, fNavigators, G4Exception(), JustWarning, and message().
void G4ITTransportationManager::DeleteInstance () static
Definition at line 56 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ITTransportationManager.cc
References fpInstance.
void G4ITTransportationManager::DeRegisterNavigator (G4ITNavigator * aNavigator)
Definition at line 228 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ITTransportationManager.cc
References DeRegisterWorld(), FatalException, fNavigators, G4Exception(), JustWarning, and message().
void G4ITTransportationManager::DeRegisterWorld (G4VPhysicalVolume * aWorld) private
Definition at line 406 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 406 of file G4ITTransportationManager.cc
References fWorlds, G4Exception(), G4VPhysicalVolume::GetName(), JustWarning, and message().
Referenced by DeRegisterNavigator().
std::vector<G4ITNavigator*>::iterator G4ITTransportationManager::GetActiveNavigatorsIterator () inline
Referenced by G4ITPathFinder::ComputeSafety(), G4ITMultiNavigator::GetGlobalExitNormal(), G4ITPathFinder::Locate(), G4ITMultiNavigator::LocateGlobalPointAndSetup(), G4ITMultiNavigator::LocateGlobalPointWithinVolume(), G4ITPathFinder::PrepareNewTrack(), G4ITPathFinder::ReLocate(), and G4ITMultiNavigator::ResetHierarchyAndLocate().
G4ITNavigator * G4ITTransportationManager::GetNavigator (const G4String & worldName)
Definition at line 145 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 145 of file G4ITTransportationManager.cc
References FatalException, fNavigators, G4Exception(), IsWorldExisting(), and message().
G4ITNavigator * G4ITTransportationManager::GetNavigator (G4VPhysicalVolume * aWorld)
Definition at line 188 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 188 of file G4ITTransportationManager.cc
References FatalException, fNavigators, fWorlds, G4Exception(), G4VPhysicalVolume::GetName(), and message().
G4ITNavigator* G4ITTransportationManager::GetNavigatorForTracking () const
Referenced by G4ITMultiNavigator::CheckMassWorld(), G4DNAMolecularDissociation::DecayIt(), G4ITMultiNavigator::G4ITMultiNavigator(), G4ITTransportation::G4ITTransportation(), GetParallelWorld(), and G4ITSafetyHelper::InitialiseNavigator().
size_t G4ITTransportationManager::GetNoActiveNavigators () const inline
size_t G4ITTransportationManager::GetNoWorlds () const inline
G4VPhysicalVolume * G4ITTransportationManager::GetParallelWorld (const G4String & worldName)
Definition at line 123 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ITTransportationManager.cc
References G4VPhysicalVolume::GetLogicalVolume(), GetNavigatorForTracking(), G4LogicalVolume::GetSolid(), IsWorldExisting(), and RegisterWorld().
G4ITSafetyHelper* G4ITTransportationManager::GetSafetyHelper () const inline
Referenced by G4ITPathFinder::EnableParallelNavigation(), G4ITTransportation::G4ITTransportation(), and G4ITPathFinder::PrepareNewTrack().
G4ITTransportationManager * G4ITTransportationManager::GetTransportationManager () static
Definition at line 110 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ITTransportationManager.cc
References fpInstance, and G4ITTransportationManager().
Referenced by G4DNAMolecularDissociation::DecayIt(), G4ITMultiNavigator::G4ITMultiNavigator(), G4ITPathFinder::G4ITPathFinder(), G4ITTransportation::G4ITTransportation(), G4ITSafetyHelper::InitialiseNavigator(), and G4ITStepProcessor::Initialize().
std::vector<G4VPhysicalVolume*>::iterator G4ITTransportationManager::GetWorldsIterator () inline
void G4ITTransportationManager::InactivateAll ()
Definition at line 336 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 336 of file G4ITTransportationManager.cc
References fActiveNavigators, and fNavigators.
void G4ITTransportationManager::Initialize () private
Definition at line 83 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ITTransportationManager.cc
References fActiveNavigators, fNavigators, fpSafetyHelper, fWorlds, G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetNoWorlds(), G4TransportationManager::GetTransportationManager(), G4TransportationManager::GetWorldsIterator(), G4Navigator::GetWorldVolume(), it, and Acts::Test::world.
Referenced by G4ITTransportationManager().
G4VPhysicalVolume * G4ITTransportationManager::IsWorldExisting (const G4String & worldName)
Definition at line 359 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 359 of file G4ITTransportationManager.cc
References fNavigators, and fWorlds.
Referenced by GetNavigator(), and GetParallelWorld().
G4bool G4ITTransportationManager::RegisterWorld (G4VPhysicalVolume * aWorld)
Definition at line 384 of file G4ITTransportationManager.cc.
View newest version in sPHENIX GitHub at line 384 of file G4ITTransportationManager.cc
References fWorlds.
Referenced by GetParallelWorld().
void G4ITTransportationManager::SetWorldForTracking (G4VPhysicalVolume * theWorld) inline
Member Data Documentation
std::vector<G4ITNavigator*> G4ITTransportationManager::fActiveNavigators private
Definition at line 122 of file G4ITTransportationManager.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ITTransportationManager.hh
Referenced by ActivateNavigator(), ClearNavigators(), DeActivateNavigator(), InactivateAll(), and Initialize().
std::vector<G4ITNavigator*> G4ITTransportationManager::fNavigators private
Definition at line 120 of file G4ITTransportationManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ITTransportationManager.hh
Referenced by ActivateNavigator(), ClearNavigators(), DeActivateNavigator(), DeRegisterNavigator(), GetNavigator(), InactivateAll(), Initialize(), and IsWorldExisting().
G4ThreadLocal G4ITTransportationManager * G4ITTransportationManager::fpInstance static private
{Duplicated version of G4TransportationManager. This class just contains the pointer to the navigator object of the simulation.}
Definition at line 116 of file G4ITTransportationManager.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ITTransportationManager.hh
Referenced by DeleteInstance(), and GetTransportationManager().
G4ITSafetyHelper* G4ITTransportationManager::fpSafetyHelper private
Definition at line 119 of file G4ITTransportationManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ITTransportationManager.hh
Referenced by Initialize(), and ~G4ITTransportationManager().
std::vector<G4VPhysicalVolume*> G4ITTransportationManager::fWorlds private
Definition at line 124 of file G4ITTransportationManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ITTransportationManager.hh
Referenced by ClearNavigators(), DeRegisterWorld(), GetNavigator(), Initialize(), IsWorldExisting(), and RegisterWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTransportationManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITTransportationManager.cc