ECCE @ EIC Software: G4IonPhysics Class Reference
G4IonPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/ions/include/G4IonPhysics.hh>
Public Member Functions
G4IonPhysics (G4int ver=0)
G4IonPhysics (const G4String &nname)
virtual ~G4IonPhysics ()
void ConstructParticle () override
void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Attributes
G4int verbose
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Private Member Functions
virtual void AddProcess (const G4String &, G4ParticleDefinition *, G4HadronicInteraction *, G4HadronicInteraction *, G4VCrossSectionDataSet *)
Static Private Attributes
static G4ThreadLocal G4FTFBuilder * theBuilder =nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 48 of file G4IonPhysics.hh.
View newest version in sPHENIX GitHub at line 48 of file G4IonPhysics.hh
Constructor & Destructor Documentation
G4IonPhysics::G4IonPhysics (G4int ver = 0)
Definition at line 74 of file G4IonPhysics.cc.
View newest version in sPHENIX GitHub at line 74 of file G4IonPhysics.cc
References verbose.
G4IonPhysics::G4IonPhysics (const G4String & nname)
Definition at line 82 of file G4IonPhysics.cc.
View newest version in sPHENIX GitHub at line 82 of file G4IonPhysics.cc
References bIons, G4cout, G4endl, G4VPhysicsConstructor::SetPhysicsType(), and verbose.
G4IonPhysics::~G4IonPhysics () virtual
Definition at line 91 of file G4IonPhysics.cc.
View newest version in sPHENIX GitHub at line 91 of file G4IonPhysics.cc
References theBuilder.
Member Function Documentation
void G4IonPhysics::AddProcess (const G4String & name, G4ParticleDefinition * part, G4HadronicInteraction * theIonBC, G4HadronicInteraction * theFTFP, G4VCrossSectionDataSet * xs) private virtual
Reimplemented in G4IonPhysicsXS.
Definition at line 157 of file G4IonPhysics.cc.
View newest version in sPHENIX GitHub at line 157 of file G4IonPhysics.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), G4ParticleDefinition::GetProcessManager(), and G4HadronicProcess::RegisterMe().
Referenced by ConstructProcess().
void G4IonPhysics::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 102 of file G4IonPhysics.cc.
View newest version in sPHENIX GitHub at line 102 of file G4IonPhysics.cc
References G4IonConstructor::ConstructParticle().
void G4IonPhysics::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 111 of file G4IonPhysics.cc.
View newest version in sPHENIX GitHub at line 111 of file G4IonPhysics.cc
References AddProcess(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), emax, G4HadronicInteractionRegistry::FindModel(), G4cout, G4endl, G4GenericIon::GenericIon(), G4HadronicParameters::GetMaxEnergy(), G4HadronicInteraction::GetMaxEnergy(), G4VHadronModelBuilder::GetModel(), G4He3::He3(), G4HadronicInteractionRegistry::Instance(), G4HadronicParameters::Instance(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theBuilder, G4Triton::Triton(), and verbose.
Member Data Documentation
G4ThreadLocal G4FTFBuilder * G4IonPhysics::theBuilder =nullptr static private
Definition at line 68 of file G4IonPhysics.hh.
View newest version in sPHENIX GitHub at line 68 of file G4IonPhysics.hh
Referenced by ConstructProcess(), and ~G4IonPhysics().
G4int G4IonPhysics::verbose protected
Definition at line 72 of file G4IonPhysics.hh.
View newest version in sPHENIX GitHub at line 72 of file G4IonPhysics.hh
Referenced by ConstructProcess(), G4IonPhysics(), and G4IonPhysicsXS::G4IonPhysicsXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/ions/include/G4IonPhysics.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/ions/src/G4IonPhysics.cc