ECCE @ EIC Software: G4VUPLData Class Reference
G4VUPLData Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUserPhysicsList.hh>
Public Member Functions
void initialize ()
Public Attributes
G4ParticleTable::G4PTblDicIterator * _theParticleIterator
G4UserPhysicsListMessenger * _theMessenger
G4PhysicsListHelper * _thePLHelper
G4bool _fIsPhysicsTableBuilt
G4int _fDisplayThreshold
Detailed Description
Definition at line 103 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VUserPhysicsList.hh
Member Function Documentation
void G4VUPLData::initialize ()
Definition at line 93 of file G4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 93 of file G4VUserPhysicsList.cc
References _fDisplayThreshold, _fIsPhysicsTableBuilt, _theMessenger, _theParticleIterator, _thePLHelper, G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), and G4PhysicsListHelper::GetPhysicsListHelper().
Member Data Documentation
G4int G4VUPLData::_fDisplayThreshold
Definition at line 113 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VUserPhysicsList.hh
Referenced by initialize().
G4bool G4VUPLData::_fIsPhysicsTableBuilt
Definition at line 112 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VUserPhysicsList.hh
Referenced by initialize().
G4UserPhysicsListMessenger* G4VUPLData::_theMessenger
Definition at line 110 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VUserPhysicsList.hh
Referenced by initialize().
G4ParticleTable::G4PTblDicIterator* G4VUPLData::_theParticleIterator
Definition at line 109 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VUserPhysicsList.hh
Referenced by initialize().
G4PhysicsListHelper* G4VUPLData::_thePLHelper
Definition at line 111 of file G4VUserPhysicsList.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VUserPhysicsList.hh
Referenced by initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VUserPhysicsList.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VUserPhysicsList.cc