ECCE @ EIC Software: G4ReduciblePolygonIterator Class Reference
G4ReduciblePolygonIterator Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4ReduciblePolygon.hh>
Public Member Functions
G4ReduciblePolygonIterator (const G4ReduciblePolygon *theSubject)
void Begin ()
G4bool Next ()
G4bool Valid () const
G4double GetA () const
G4double GetB () const
Protected Attributes
const G4ReduciblePolygon * subject = nullptr
G4ReduciblePolygon::ABVertex * current = nullptr
Detailed Description
Definition at line 152 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ReduciblePolygon.hh
Constructor & Destructor Documentation
G4ReduciblePolygonIterator::G4ReduciblePolygonIterator (const G4ReduciblePolygon * theSubject) inline
Definition at line 156 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ReduciblePolygon.hh
References current, and subject.
Member Function Documentation
void G4ReduciblePolygonIterator::Begin () inline
Definition at line 159 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ReduciblePolygon.hh
References current, subject, and G4ReduciblePolygon::vertexHead.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
G4double G4ReduciblePolygonIterator::GetA () const inline
Definition at line 168 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ReduciblePolygon.hh
References G4ReduciblePolygon::ABVertex::a, and current.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
G4double G4ReduciblePolygonIterator::GetB () const inline
Definition at line 169 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ReduciblePolygon.hh
References G4ReduciblePolygon::ABVertex::b, and current.
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
G4bool G4ReduciblePolygonIterator::Next () inline
Definition at line 160 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ReduciblePolygon.hh
References current, G4ReduciblePolygon::ABVertex::next, and Valid().
Referenced by G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), and G4PolyPhiFace::G4PolyPhiFace().
G4bool G4ReduciblePolygonIterator::Valid () const inline
Definition at line 166 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ReduciblePolygon.hh
References current.
Referenced by Next().
Member Data Documentation
G4ReduciblePolygon::ABVertex* G4ReduciblePolygonIterator::current = nullptr protected
Definition at line 174 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ReduciblePolygon.hh
Referenced by Begin(), G4ReduciblePolygonIterator(), GetA(), GetB(), Next(), and Valid().
const G4ReduciblePolygon* G4ReduciblePolygonIterator::subject = nullptr protected
Definition at line 173 of file G4ReduciblePolygon.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ReduciblePolygon.hh
Referenced by Begin(), and G4ReduciblePolygonIterator().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4ReduciblePolygon.hh