ECCE @ EIC Software: DMXSteppingAction Class Reference
DMXSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXSteppingAction.hh>
Public Member Functions
DMXSteppingAction ()
virtual ~DMXSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
void SetColourNeutronFlag (G4String val)
void SetColourGammaFlag (G4String val)
void SetColourOpticalFlag (G4String val)
void SetColourChargedPlusFlag (G4String val)
void SetColourChargedMinusFlag (G4String val)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
G4String colourNeutronFlag
G4String colourGammaFlag
G4String colourOpticalFlag
G4String colourChargedPlusFlag
G4String colourChargedMinusFlag
DMXSteppingActionMessenger * steppingMessenger
const DMXEventAction * evtAction
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 55 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file DMXSteppingAction.hh
Constructor & Destructor Documentation
DMXSteppingAction::DMXSteppingAction ()
Definition at line 68 of file DMXSteppingAction.cc.
View newest version in sPHENIX GitHub at line 68 of file DMXSteppingAction.cc
References colourChargedMinusFlag, colourChargedPlusFlag, colourGammaFlag, colourNeutronFlag, colourOpticalFlag, and steppingMessenger.
DMXSteppingAction::~DMXSteppingAction () virtual
Definition at line 84 of file DMXSteppingAction.cc.
View newest version in sPHENIX GitHub at line 84 of file DMXSteppingAction.cc
References steppingMessenger.
Member Function Documentation
void DMXSteppingAction::SetColourChargedMinusFlag (G4String val) inline
Definition at line 68 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file DMXSteppingAction.hh
References colourChargedMinusFlag.
Referenced by DMXSteppingActionMessenger::SetNewValue().
void DMXSteppingAction::SetColourChargedPlusFlag (G4String val) inline
Definition at line 67 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file DMXSteppingAction.hh
References colourChargedPlusFlag.
Referenced by DMXSteppingActionMessenger::SetNewValue().
void DMXSteppingAction::SetColourGammaFlag (G4String val) inline
Definition at line 65 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file DMXSteppingAction.hh
References colourGammaFlag.
Referenced by DMXSteppingActionMessenger::SetNewValue().
void DMXSteppingAction::SetColourNeutronFlag (G4String val) inline
Definition at line 64 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file DMXSteppingAction.hh
References colourNeutronFlag.
Referenced by DMXSteppingActionMessenger::SetNewValue().
void DMXSteppingAction::SetColourOpticalFlag (G4String val) inline
Definition at line 66 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file DMXSteppingAction.hh
References colourOpticalFlag.
Referenced by DMXSteppingActionMessenger::SetNewValue().
void DMXSteppingAction::UserSteppingAction (const G4Step * fStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 93 of file DMXSteppingAction.cc.
View newest version in sPHENIX GitHub at line 93 of file DMXSteppingAction.cc
References colourChargedMinusFlag, colourChargedPlusFlag, colourGammaFlag, colourNeutronFlag, colourOpticalFlag, G4Electron::Definition(), G4Neutron::Definition(), G4Positron::Definition(), G4Gamma::Definition(), G4VVisManager::Draw(), evtAction, G4VAnalysisManager::FillH1(), G4VVisManager::GetConcreteInstance(), G4Track::GetCurrentStepNumber(), G4Track::GetDefinition(), DMXEventAction::GetDrawColsFlag(), DMXEventAction::GetDrawTrksFlag(), G4StepPoint::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4RunManager::GetRunManager(), G4Step::GetTrack(), G4RunManager::GetUserEventAction(), G4ToolsAnalysisManager::Instance(), G4Visible::SetVisAttributes(), and start().
Member Data Documentation
G4String DMXSteppingAction::colourChargedMinusFlag private
Definition at line 75 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file DMXSteppingAction.hh
Referenced by DMXSteppingAction(), SetColourChargedMinusFlag(), and UserSteppingAction().
G4String DMXSteppingAction::colourChargedPlusFlag private
Definition at line 74 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 74 of file DMXSteppingAction.hh
Referenced by DMXSteppingAction(), SetColourChargedPlusFlag(), and UserSteppingAction().
G4String DMXSteppingAction::colourGammaFlag private
Definition at line 72 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 72 of file DMXSteppingAction.hh
Referenced by DMXSteppingAction(), SetColourGammaFlag(), and UserSteppingAction().
G4String DMXSteppingAction::colourNeutronFlag private
Definition at line 68 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file DMXSteppingAction.hh
Referenced by DMXSteppingAction(), SetColourNeutronFlag(), and UserSteppingAction().
G4String DMXSteppingAction::colourOpticalFlag private
Definition at line 73 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file DMXSteppingAction.hh
Referenced by DMXSteppingAction(), SetColourOpticalFlag(), and UserSteppingAction().
const DMXEventAction* DMXSteppingAction::evtAction private
Definition at line 79 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 79 of file DMXSteppingAction.hh
Referenced by UserSteppingAction().
DMXSteppingActionMessenger* DMXSteppingAction::steppingMessenger private
Definition at line 77 of file DMXSteppingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file DMXSteppingAction.hh
Referenced by DMXSteppingAction(), and ~DMXSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/src/DMXSteppingAction.cc