ECCE @ EIC Software: G4EmDNAPhysics_option1 Class Reference
G4EmDNAPhysics_option1 Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmDNAPhysics_option1.hh>
Public Member Functions
G4EmDNAPhysics_option1 (G4int ver=1, const G4String &name="")
virtual ~G4EmDNAPhysics_option1 ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Attributes
G4int verbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 36 of file G4EmDNAPhysics_option1.hh.
View newest version in sPHENIX GitHub at line 36 of file G4EmDNAPhysics_option1.hh
Constructor & Destructor Documentation
G4EmDNAPhysics_option1::G4EmDNAPhysics_option1 (G4int ver = 1, const G4String & name = "") explicit
Definition at line 89 of file G4EmDNAPhysics_option1.cc.
View newest version in sPHENIX GitHub at line 89 of file G4EmDNAPhysics_option1.cc
References G4EmParameters::ActivateDNA(), bElectromagnetic, G4EmParameters::Instance(), G4EmParameters::SetAuger(), G4EmParameters::SetAugerCascade(), G4EmParameters::SetDeexcitationIgnoreCut(), G4EmParameters::SetDefaults(), G4EmParameters::SetFluo(), and G4VPhysicsConstructor::SetPhysicsType().
G4EmDNAPhysics_option1::~G4EmDNAPhysics_option1 () virtual
Definition at line 105 of file G4EmDNAPhysics_option1.cc.
View newest version in sPHENIX GitHub at line 105 of file G4EmDNAPhysics_option1.cc
Member Function Documentation
void G4EmDNAPhysics_option1::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 110 of file G4EmDNAPhysics_option1.cc.
View newest version in sPHENIX GitHub at line 110 of file G4EmDNAPhysics_option1.cc
References G4Electron::Electron(), G4Gamma::Gamma(), G4GenericIon::GenericIonDefinition(), G4DNAGenericIonsManager::GetIon(), G4DNAGenericIonsManager::Instance(), G4Positron::Positron(), and G4Proton::Proton().
void G4EmDNAPhysics_option1::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 139 of file G4EmDNAPhysics_option1.cc.
View newest version in sPHENIX GitHub at line 139 of file G4EmDNAPhysics_option1.cc
References fUseDistanceToBoundary, G4cout, G4endl, G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4PhysicsListHelper::GetPhysicsListHelper(), G4VPhysicsConstructor::GetPhysicsName(), G4LossTableManager::Instance(), particle, G4PhysicsListHelper::RegisterProcess(), G4LossTableManager::SetAtomDeexcitation(), G4VMultipleScattering::SetEmModel(), G4VEmProcess::SetEmModel(), G4VEnergyLossProcess::SetStepFunction(), G4VMultipleScattering::SetStepLimitType(), um, and verbose.
Member Data Documentation
G4int G4EmDNAPhysics_option1::verbose private
Definition at line 48 of file G4EmDNAPhysics_option1.hh.
View newest version in sPHENIX GitHub at line 48 of file G4EmDNAPhysics_option1.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmDNAPhysics_option1.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/src/G4EmDNAPhysics_option1.cc