ECCE @ EIC Software: G4ITGun Class Reference
G4ITGun Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITGun.hh>
Public Member Functions
G4ITGun ()
virtual ~G4ITGun ()
virtual void DefineTracks ()
Protected Member Functions
void PushTrack (G4Track *)
Detailed Description
Definition at line 50 of file G4ITGun.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ITGun.hh
Constructor & Destructor Documentation
G4ITGun::G4ITGun ()
Definition at line 36 of file G4ITGun.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ITGun.cc
G4ITGun::~G4ITGun () virtual
Definition at line 41 of file G4ITGun.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ITGun.cc
Member Function Documentation
virtual void G4ITGun::DefineTracks () inline virtual
Reimplemented in G4MoleculeGun.
Definition at line 56 of file G4ITGun.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ITGun.hh
Referenced by G4Scheduler::Process().
void G4ITGun::PushTrack (G4Track * track) protected
Definition at line 45 of file G4ITGun.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ITGun.cc
References G4VITTrackHolder::Instance(), and G4VITTrackHolder::Push().
Referenced by G4MoleculeGun::BuildAndPushTrack().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITGun.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITGun.cc