ECCE @ EIC Software: DicomBeam Class Reference
DicomBeam Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeam.hh>
Public Member Functions
DicomBeam ()
~DicomBeam ()
void SetDoseSpecificationPoint (G4ThreeVector point)
void SetMeterset (Float64 dat)
void SetSourceAxisDistance (Float64 dat)
void SetNumber (Sint32 dat)
void SetRadiationType (OFString dat)
void AddDevice (DicomVBeamDevice *db)
void AddControlPoint (DicomBeamControlPoint *db)
void AddCompensator (DicomBeamCompensator *db)
void AddBlock (DicomBeamBlock *db)
void AddWedge (DicomBeamWedge *db)
size_t GetNControlPoints () const
DicomBeamControlPoint * GetControlPoint (size_t ii)
void SetControlPointMetersets ()
void Print (std::ostream &out)
void DumpToFile ()
Private Attributes
G4ThreeVector theDoseSpecificationPoint
Float64 theMeterset
Float64 theSourceAxisDistance
Sint32 theNumber
OFString theRadiationType
std::vector< DicomVBeamDevice * > theDevices
std::vector
< DicomBeamControlPoint * > theControlPoints
std::vector
< DicomBeamCompensator * > theCompensators
std::vector< DicomBeamBlock * > theBlocks
std::vector< DicomBeamWedge * > theWedges
Detailed Description
Definition at line 40 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 40 of file DicomBeam.hh
Constructor & Destructor Documentation
DicomBeam::DicomBeam ()
Definition at line 33 of file DicomBeam.cc.
View newest version in sPHENIX GitHub at line 33 of file DicomBeam.cc
DicomBeam::~DicomBeam () inline
Definition at line 44 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 44 of file DicomBeam.hh
Member Function Documentation
void DicomBeam::AddBlock (DicomBeamBlock * db) inline
Definition at line 71 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 71 of file DicomBeam.hh
References theBlocks.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::AddCompensator (DicomBeamCompensator * db) inline
Definition at line 68 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 68 of file DicomBeam.hh
References theCompensators.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::AddControlPoint (DicomBeamControlPoint * db) inline
Definition at line 65 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 65 of file DicomBeam.hh
References theControlPoints.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::AddDevice (DicomVBeamDevice * db) inline
Definition at line 62 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 62 of file DicomBeam.hh
References theDevices.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::AddWedge (DicomBeamWedge * db) inline
Definition at line 74 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 74 of file DicomBeam.hh
References theWedges.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::DumpToFile ()
Definition at line 55 of file DicomBeam.cc.
View newest version in sPHENIX GitHub at line 55 of file DicomBeam.cc
References G4endl, theCompensators, theControlPoints, theDevices, theMeterset, theNumber, and nlohmann::to_string().
DicomBeamControlPoint* DicomBeam::GetControlPoint (size_t ii) inline
Definition at line 80 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 80 of file DicomBeam.hh
References theControlPoints.
Referenced by DicomFilePlan::ReadData().
size_t DicomBeam::GetNControlPoints () const inline
Definition at line 77 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 77 of file DicomBeam.hh
References theControlPoints.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::Print (std::ostream & out)
Definition at line 38 of file DicomBeam.cc.
View newest version in sPHENIX GitHub at line 38 of file DicomBeam.cc
void DicomBeam::SetControlPointMetersets ()
Definition at line 44 of file DicomBeam.cc.
View newest version in sPHENIX GitHub at line 44 of file DicomBeam.cc
References theControlPoints, and theMeterset.
void DicomBeam::SetDoseSpecificationPoint (G4ThreeVector point) inline
Definition at line 47 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 47 of file DicomBeam.hh
References theDoseSpecificationPoint.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::SetMeterset (Float64 dat) inline
Definition at line 50 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 50 of file DicomBeam.hh
References theMeterset.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::SetNumber (Sint32 dat) inline
Definition at line 56 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 56 of file DicomBeam.hh
References theNumber.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::SetRadiationType (OFString dat) inline
Definition at line 59 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 59 of file DicomBeam.hh
References theRadiationType.
Referenced by DicomFilePlan::ReadData().
void DicomBeam::SetSourceAxisDistance (Float64 dat) inline
Definition at line 53 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 53 of file DicomBeam.hh
References theSourceAxisDistance.
Referenced by DicomFilePlan::ReadData().
Member Data Documentation
std::vector<DicomBeamBlock*> DicomBeam::theBlocks private
Definition at line 99 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 99 of file DicomBeam.hh
Referenced by AddBlock().
std::vector<DicomBeamCompensator*> DicomBeam::theCompensators private
Definition at line 98 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 98 of file DicomBeam.hh
Referenced by AddCompensator(), and DumpToFile().
std::vector<DicomBeamControlPoint*> DicomBeam::theControlPoints private
Definition at line 97 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 97 of file DicomBeam.hh
Referenced by AddControlPoint(), DumpToFile(), GetControlPoint(), GetNControlPoints(), and SetControlPointMetersets().
std::vector<DicomVBeamDevice*> DicomBeam::theDevices private
Definition at line 96 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 96 of file DicomBeam.hh
Referenced by AddDevice(), and DumpToFile().
G4ThreeVector DicomBeam::theDoseSpecificationPoint private
Definition at line 91 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 91 of file DicomBeam.hh
Referenced by SetDoseSpecificationPoint().
Float64 DicomBeam::theMeterset private
Definition at line 92 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 92 of file DicomBeam.hh
Referenced by DumpToFile(), SetControlPointMetersets(), and SetMeterset().
Sint32 DicomBeam::theNumber private
Definition at line 94 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 94 of file DicomBeam.hh
Referenced by DumpToFile(), and SetNumber().
OFString DicomBeam::theRadiationType private
Definition at line 95 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 95 of file DicomBeam.hh
Referenced by SetRadiationType().
Float64 DicomBeam::theSourceAxisDistance private
Definition at line 93 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 93 of file DicomBeam.hh
Referenced by SetSourceAxisDistance().
std::vector<DicomBeamWedge*> DicomBeam::theWedges private
Definition at line 100 of file DicomBeam.hh.
View newest version in sPHENIX GitHub at line 100 of file DicomBeam.hh
Referenced by AddWedge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeam.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomBeam.cc