ECCE @ EIC Software: macros/blob/master/detectors/Modular/Fun4All_runEvaluators.C File Reference
Fun4All_runEvaluators.C File Reference
#include <dirent.h>
#include <fstream>
#include <map>
#include <stdlib.h>
#include <GlobalVariables.C>
#include <G4Setup_EICDetector.C>
#include <G4_DSTReader_EICDetector.C>
#include <G4_EventEvaluator.C>
#include <G4_FwdJets.C>
#include <G4_Global.C>
#include <G4_Input.C>
#include <G4_Production.C>
#include <G4_User.C>
#include <fun4all/Fun4AllServer.h>
Macros
#define MACRO_FUN4ALLG4RUNEVALUATORS_C
Functions
bool checkForDir (string name)
bool checkForFile (string dir, string base, map< string, string > extension)
int Fun4All_runEvaluators (const int nEvents=1, const string &inputFile="myInputFile.root", const string &inputDir=".", const int skip=0, const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4RUNEVALUATORS_C
Definition at line 2 of file Fun4All_runEvaluators.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_runEvaluators.C
Function Documentation
bool checkForDir (string name)
Definition at line 26 of file Fun4All_runEvaluators.C.
View newest version in sPHENIX GitHub at line 26 of file Fun4All_runEvaluators.C
References dir.
Referenced by Fun4All_runEvaluators().
bool checkForFile (string dir, string base, map< string, string > extension)
Definition at line 33 of file Fun4All_runEvaluators.C.
View newest version in sPHENIX GitHub at line 33 of file Fun4All_runEvaluators.C
References file.
Referenced by Fun4All_runEvaluators().
int Fun4All_runEvaluators (const int nEvents = 1, const string & inputFile = "myInputFile.root", const string & inputDir = ".", const int skip = 0, const string & outdir = ".")
Definition at line 47 of file Fun4All_runEvaluators.C.
View newest version in sPHENIX GitHub at line 47 of file Fun4All_runEvaluators.C
References Enable::BECAL, Enable::BECAL_EVAL, BECAL_Eval(), checkForDir(), checkForFile(), Enable::DIRC_RECO, Enable::DSTREADER, Enable::EEMCH, Enable::EEMCH_EVAL, EEMCH_Eval(), Enable::EHCAL, Enable::EHCAL_EVAL, EHCAL_Eval(), Fun4AllServer::End(), Enable::EVENT_EVAL, Event_Eval(), Enable::FEMC, Enable::FEMC_EVAL, FEMC_Eval(), Enable::FFR_EVAL, FFR_Eval(), Enable::FHCAL_EVAL, FHCAL_Eval(), INPUTREADHITS::filename, Enable::FWDJETS_EVAL, G4DSTreader_EICDetector(), Enable::HCALIN, Enable::HCALIN_EVAL, HCALInner_Eval(), Enable::HCALOUT, Enable::HCALOUT_EVAL, HCALOuter_Eval(), InputInit(), InputManagers(), Fun4AllServer::instance(), Jet_FwdEval(), Enable::LFHCAL, Enable::LFHCAL_EVAL, Enable::mRICH_RECO, nEvents, pos(), TRACKING::ProjectionNames, Input::READHITS, Enable::RICH_RECO, Fun4AllServer::run(), Acts::IntegrationTest::skip, Fun4AllServer::skip(), system(), nlohmann::to_string(), Enable::TRACKING, Enable::TRACKING_EVAL, Tracking_Eval(), Enable::USER, UserAnalysisInit(), and Fun4AllBase::Verbosity().