ECCE @ EIC Software: G4MPIbatch Class Reference
G4MPIbatch Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPIbatch.hh>
Public Member Functions
G4MPIbatch (const G4String &fname="", G4bool qbatch=false)
~G4MPIbatch ()
virtual G4UIsession * SessionStart ()
Public Member Functions inherited from G4VMPIsession
G4VMPIsession ()
~G4VMPIsession ()
virtual void PauseSessionStart (const G4String &msg)
virtual G4int ReceiveG4cout (const G4String &coutString)
virtual G4int ReceiveG4cerr (const G4String &cerrString)
Public Member Functions inherited from G4VBasicShell
G4VBasicShell ()
virtual ~G4VBasicShell ()
Public Member Functions inherited from G4UIsession
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
G4int GetLastReturnCode () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Protected Member Functions
G4String ReadCommand ()
Protected Member Functions inherited from G4VMPIsession
G4int ExecCommand (const G4String &acommand)
G4String TruncateCommand (const G4String &command) const
G4String BypassCommand (const G4String &command) const
virtual G4bool GetHelpChoice (G4int &aval)
virtual void ExitHelp () const
Protected Member Functions inherited from G4VBasicShell
G4String ModifyToFullPathCommand (const char *aCommandLine) const
G4String GetCurrentWorkingDirectory () const
G4bool ChangeDirectory (const char *newDir)
G4UIcommandTree * FindDirectory (const char *dirName) const
G4UIcommand * FindCommand (const char *commandName) const
G4String Complete (const G4String &)
G4String FindMatchingPath (G4UIcommandTree *, const G4String &)
virtual void ExecuteCommand (const G4String &)
void ApplyShellCommand (const G4String &, G4bool &, G4bool &)
void ShowCurrent (const G4String &) const
void ChangeDirectoryCommand (const G4String &)
void ListDirectory (const G4String &) const
void TerminalHelp (const G4String &)
Protected Attributes
std::ifstream batch_stream_
G4bool is_opened_
G4bool is_batch_mode_
Protected Attributes inherited from G4VMPIsession
G4MPImanager * g4mpi_
G4bool is_master_
G4bool is_slave_
G4int rank_
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Public Member Functions inherited from G4UIsession
static G4int InSession ()
Static Protected Attributes inherited from G4UIsession
static G4ICOMS_DLL G4int inSession = 0
Detailed Description
Definition at line 34 of file G4MPIbatch.hh.
View newest version in sPHENIX GitHub at line 34 of file G4MPIbatch.hh
Constructor & Destructor Documentation
G4MPIbatch::G4MPIbatch (const G4String & fname = "", G4bool qbatch = false)
Definition at line 64 of file G4MPIbatch.cc.
View newest version in sPHENIX GitHub at line 64 of file G4MPIbatch.cc
References batch_stream_, G4cerr, G4endl, in, G4VMPIsession::is_master_, and is_opened_.
G4MPIbatch::~G4MPIbatch ()
Definition at line 79 of file G4MPIbatch.cc.
View newest version in sPHENIX GitHub at line 79 of file G4MPIbatch.cc
References batch_stream_, and is_opened_.
Member Function Documentation
G4String G4MPIbatch::ReadCommand () protected
Definition at line 85 of file G4MPIbatch.cc.
View newest version in sPHENIX GitHub at line 85 of file G4MPIbatch.cc
References batch_stream_, G4String::both, BUFSIZE, G4VMPIsession::BypassCommand(), G4Exception(), JustWarning, G4String::replace(), G4String::strip(), and Tokenize().
Referenced by SessionStart().
G4UIsession * G4MPIbatch::SessionStart () virtual
Implements G4VBasicShell.
Definition at line 154 of file G4MPIbatch.cc.
View newest version in sPHENIX GitHub at line 154 of file G4MPIbatch.cc
References G4VMPIsession::ExecCommand(), fCommandSucceeded, G4cerr, G4cout, G4endl, G4VMPIsession::g4mpi_, G4UImanager::GetUIpointer(), G4VMPIsession::is_master_, is_opened_, and ReadCommand().
Member Data Documentation
std::ifstream G4MPIbatch::batch_stream_ protected
Definition at line 42 of file G4MPIbatch.hh.
View newest version in sPHENIX GitHub at line 42 of file G4MPIbatch.hh
Referenced by G4MPIbatch(), ReadCommand(), and ~G4MPIbatch().
G4bool G4MPIbatch::is_batch_mode_ protected
Definition at line 44 of file G4MPIbatch.hh.
View newest version in sPHENIX GitHub at line 44 of file G4MPIbatch.hh
G4bool G4MPIbatch::is_opened_ protected
Definition at line 43 of file G4MPIbatch.hh.
View newest version in sPHENIX GitHub at line 43 of file G4MPIbatch.hh
Referenced by G4MPIbatch(), SessionStart(), and ~G4MPIbatch().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPIbatch.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/src/G4MPIbatch.cc