ECCE @ EIC Software: G4BraggIonModel Class Reference
G4BraggIonModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4BraggIonModel.hh>
Public Member Functions
G4BraggIonModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="BraggIon")
virtual ~G4BraggIonModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *couple) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy) override
virtual G4double GetParticleCharge (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) override
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual void StartTracking (G4Track *)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) final
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void SetParticle (const G4ParticleDefinition *p)
G4double HeEffChargeSquare (G4double z, G4double kinEnergyInMeV) const
G4BraggIonModel & operator= (const G4BraggIonModel &right)=delete
G4BraggIonModel (const G4BraggIonModel &)=delete
void HasMaterial (const G4Material *material)
G4double StoppingPower (const G4Material *material, G4double kineticEnergy)
G4double ElectronicStoppingPower (G4double z, G4double kineticEnergy) const
G4double DEDX (const G4Material *material, G4double kineticEnergy)
Private Attributes
G4EmCorrections * corr
const G4ParticleDefinition * particle
G4ParticleDefinition * theElectron
G4ParticleChangeForLoss * fParticleChange
G4ICRU90StoppingData * fICRU90
const G4Material * currentMaterial
const G4Material * baseMaterial
G4double mass
G4double spin
G4double chargeSquare
G4double massRate
G4double ratio
G4double lowestKinEnergy
G4double HeMass
G4double massFactor
G4double corrFactor
G4double rateMassHe2p
G4double theZieglerFactor
G4int iMolecula
G4int iASTAR
G4int iICRU90
G4bool isIon
Static Private Attributes
static G4ASTARStopping * fASTAR = nullptr
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 68 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BraggIonModel.hh
Constructor & Destructor Documentation
G4BraggIonModel::G4BraggIonModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "BraggIon") explicit
Definition at line 79 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 79 of file G4BraggIonModel.cc
References source.hepunit::amu_c2, cm2, corrFactor, G4Electron::Electron(), eV, GeV, HeMass, keV, lowestKinEnergy, massFactor, MeV, source.hepunit::proton_mass_c2, rateMassHe2p, G4VEmModel::SetHighEnergyLimit(), SetParticle(), theElectron, and theZieglerFactor.
G4BraggIonModel::~G4BraggIonModel () virtual
Definition at line 108 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 108 of file G4BraggIonModel.cc
References fASTAR, and G4VEmModel::IsMaster().
G4BraggIonModel::G4BraggIonModel (const G4BraggIonModel &) private delete
Member Function Documentation
G4double G4BraggIonModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 216 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 216 of file G4BraggIonModel.cc
References ComputeCrossSectionPerElectron().
G4double G4BraggIonModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) virtual
Definition at line 187 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 187 of file G4BraggIonModel.cc
References chargeSquare, Acts::VectorHelpers::cross(), energy, G4Log(), mass, MaxSecondaryEnergy(), min, spin, and source.hepunit::twopi_mc2_rcl2.
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4BraggIonModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Reimplemented in G4BraggNoDeltaModel.
Definition at line 242 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 242 of file G4BraggIonModel.cc
References chargeSquare, DEDX(), G4Log(), G4InuclParticleNames::gam, G4Material::GetElectronDensity(), lowestKinEnergy, mass, massRate, max, MaxSecondaryEnergy(), min, source.hepunit::twopi_mc2_rcl2, and x.
Referenced by G4BraggNoDeltaModel::ComputeDEDXPerVolume().
void G4BraggIonModel::CorrectionsAlongStep (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double & eloss, G4double & niel, G4double length) override virtual
Reimplemented from G4VEmModel.
Definition at line 284 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 284 of file G4BraggIonModel.cc
References corr, corrFactor, e, G4EmCorrections::EffectiveChargeCorrection(), G4EmCorrections::EffectiveChargeSquareRatio(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4VEmModel::GetModelOfFluctuations(), mat, and G4VEmFluctuationModel::SetParticleAndCharge().
G4double G4BraggIonModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Reimplemented in G4BraggNoDeltaModel.
Definition at line 229 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 229 of file G4BraggIonModel.cc
References ComputeCrossSectionPerElectron(), and G4Material::GetElectronDensity().
G4double G4BraggIonModel::DEDX (const G4Material * material, G4double kineticEnergy) private
Definition at line 654 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 654 of file G4BraggIonModel.cc
References source.hepunit::amu, baseMaterial, chargeSquare, currentMaterial, ElectronicStoppingPower(), fASTAR, fICRU90, G4lrint(), G4Material::GetAtomicNumDensityVector(), G4Material::GetBaseMaterial(), G4Material::GetDensity(), G4ASTARStopping::GetElectronicDEDX(), G4ICRU90StoppingData::GetElectronicDEDXforAlpha(), G4Material::GetElementVector(), G4ASTARStopping::GetIndex(), G4ICRU90StoppingData::GetIndex(), G4Material::GetNumberOfElements(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetTotNbOfElectPerVolume(), G4Element::GetZ(), G4Material::GetZ(), HasMaterial(), HeEffChargeSquare(), iASTAR, iICRU90, iMolecula, material(), MeV, rateMassHe2p, StoppingPower(), T, theZieglerFactor, and z.
Referenced by ComputeDEDXPerVolume().
G4double G4BraggIonModel::ElectronicStoppingPower (G4double z, G4double kineticEnergy) const private
Definition at line 499 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 499 of file G4BraggIonModel.cc
References a, G4Exp(), G4Log(), G4lrint(), HeEffChargeSquare(), max, MeV, min, rateMassHe2p, T, x1, x2, x3, and x4.
Referenced by DEDX(), and StoppingPower().
G4double G4BraggIonModel::GetChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 162 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 162 of file G4BraggIonModel.cc
References corr, corrFactor, G4EmCorrections::EffectiveChargeCorrection(), and G4EmCorrections::EffectiveChargeSquareRatio().
G4double G4BraggIonModel::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 175 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 175 of file G4BraggIonModel.cc
References corr, and G4EmCorrections::GetParticleCharge().
void G4BraggIonModel::HasMaterial (const G4Material * material) private
Definition at line 398 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 398 of file G4BraggIonModel.cc
References G4Material::GetChemicalFormula(), iMolecula, and numberOfMolecula.
Referenced by DEDX().
G4double G4BraggIonModel::HeEffChargeSquare (G4double z, G4double kinEnergyInMeV) const private
Definition at line 721 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 721 of file G4BraggIonModel.cc
References c, e, G4Exp(), G4Log(), massFactor, max, w, x, y, and z.
Referenced by DEDX(), ElectronicStoppingPower(), and StoppingPower().
void G4BraggIonModel::Initialise (const G4ParticleDefinition * p, const G4DataVector &) override virtual
Implements G4VEmModel.
Definition at line 115 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 115 of file G4BraggIonModel.cc
References chargeSquare, corr, corrFactor, G4LossTableManager::EmCorrections(), fASTAR, fICRU90, fParticleChange, G4VEmModel::GetAngularDistribution(), G4NistManager::GetICRU90StoppingData(), G4VEmModel::GetParticleChangeForLoss(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGMass(), GeV, G4ICRU90StoppingData::Initialise(), G4ASTARStopping::Initialise(), G4EmParameters::Instance(), G4LossTableManager::Instance(), G4NistManager::Instance(), isIon, G4VEmModel::IsMaster(), particle, pname(), G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), SetParticle(), and G4VEmModel::UseAngularGeneratorFlag().
G4double G4BraggIonModel::MaxSecondaryEnergy (const G4ParticleDefinition * pd, G4double kinEnergy) final protected virtual
Reimplemented from G4VEmModel.
Definition at line 386 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 386 of file G4BraggIonModel.cc
References source.hepunit::electron_mass_c2, mass, particle, ratio, and SetParticle().
Referenced by ComputeCrossSectionPerElectron(), and ComputeDEDXPerVolume().
G4double G4BraggIonModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple * couple) override virtual
Reimplemented from G4VEmModel.
Definition at line 154 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 154 of file G4BraggIonModel.cc
References G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), and G4IonisParamMat::GetMeanExcitationEnergy().
G4BraggIonModel& G4BraggIonModel::operator= (const G4BraggIonModel & right) private delete
void G4BraggIonModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 308 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 308 of file G4BraggIonModel.cc
References Acts::Test::delta, source.hepunit::electron_mass_c2, energy, f, CLHEP::HepRandomEngine::flat(), CLHEP::HepRandomEngine::flatArray(), fParticleChange, G4cout, G4endl, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetTotalMomentum(), mass, mat, G4VEmModel::MaxSecondaryKinEnergy(), min, phi, CLHEP::Hep3Vector::rotateUz(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SelectRandomAtomNumber(), CLHEP::Hep3Vector::set(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), theElectron, twopi, CLHEP::Hep3Vector::unit(), G4VEmModel::UseAngularGeneratorFlag(), xmax, and Z.
void G4BraggIonModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 187 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 187 of file G4BraggIonModel.hh
References chargeSquare, CLHEP::electron_mass_c2, CLHEP::eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), mass, massRate, particle, CLHEP::proton_mass_c2, ratio, and spin.
Referenced by G4BraggIonModel(), Initialise(), and MaxSecondaryEnergy().
G4double G4BraggIonModel::StoppingPower (const G4Material * material, G4double kineticEnergy) private
Definition at line 424 of file G4BraggIonModel.cc.
View newest version in sPHENIX GitHub at line 424 of file G4BraggIonModel.cc
References a, ElectronicStoppingPower(), G4Exp(), G4Log(), G4Material::GetNumberOfElements(), G4Material::GetZ(), HeEffChargeSquare(), iMolecula, max, MeV, rateMassHe2p, T, x1, x2, x3, x4, and z.
Referenced by DEDX().
Member Data Documentation
const G4Material* G4BraggIonModel::baseMaterial private
Definition at line 165 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4BraggIonModel.hh
Referenced by DEDX().
G4double G4BraggIonModel::chargeSquare private
Definition at line 169 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4BraggIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), DEDX(), Initialise(), and SetParticle().
G4EmCorrections* G4BraggIonModel::corr private
Definition at line 155 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4BraggIonModel.hh
Referenced by CorrectionsAlongStep(), GetChargeSquareRatio(), GetParticleCharge(), and Initialise().
G4double G4BraggIonModel::corrFactor private
Definition at line 175 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 175 of file G4BraggIonModel.hh
Referenced by CorrectionsAlongStep(), G4BraggIonModel(), GetChargeSquareRatio(), and Initialise().
const G4Material* G4BraggIonModel::currentMaterial private
Definition at line 164 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4BraggIonModel.hh
Referenced by DEDX().
G4ASTARStopping * G4BraggIonModel::fASTAR = nullptr static private
Definition at line 161 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4BraggIonModel.hh
Referenced by DEDX(), Initialise(), and ~G4BraggIonModel().
G4ICRU90StoppingData* G4BraggIonModel::fICRU90 private
Definition at line 162 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4BraggIonModel.hh
Referenced by DEDX(), and Initialise().
G4ParticleChangeForLoss* G4BraggIonModel::fParticleChange private
Definition at line 159 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4BraggIonModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4double G4BraggIonModel::HeMass private
Definition at line 173 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4BraggIonModel.hh
Referenced by G4BraggIonModel().
G4int G4BraggIonModel::iASTAR private
Definition at line 180 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4BraggIonModel.hh
Referenced by DEDX().
G4int G4BraggIonModel::iICRU90 private
Definition at line 181 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4BraggIonModel.hh
Referenced by DEDX().
G4int G4BraggIonModel::iMolecula private
Definition at line 179 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4BraggIonModel.hh
Referenced by DEDX(), HasMaterial(), and StoppingPower().
G4bool G4BraggIonModel::isIon private
Definition at line 182 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4BraggIonModel.hh
Referenced by Initialise().
G4double G4BraggIonModel::lowestKinEnergy private
Definition at line 172 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4BraggIonModel.hh
Referenced by ComputeDEDXPerVolume(), and G4BraggIonModel().
G4double G4BraggIonModel::mass private
Definition at line 167 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4BraggIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), MaxSecondaryEnergy(), SampleSecondaries(), and SetParticle().
G4double G4BraggIonModel::massFactor private
Definition at line 174 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4BraggIonModel.hh
Referenced by G4BraggIonModel(), and HeEffChargeSquare().
G4double G4BraggIonModel::massRate private
Definition at line 170 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4BraggIonModel.hh
Referenced by ComputeDEDXPerVolume(), and SetParticle().
const G4ParticleDefinition* G4BraggIonModel::particle private
Definition at line 157 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4BraggIonModel.hh
Referenced by Initialise(), MaxSecondaryEnergy(), and SetParticle().
G4double G4BraggIonModel::rateMassHe2p private
Definition at line 176 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4BraggIonModel.hh
Referenced by DEDX(), ElectronicStoppingPower(), G4BraggIonModel(), and StoppingPower().
G4double G4BraggIonModel::ratio private
Definition at line 171 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 171 of file G4BraggIonModel.hh
Referenced by MaxSecondaryEnergy(), and SetParticle().
G4double G4BraggIonModel::spin private
Definition at line 168 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 168 of file G4BraggIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), and SetParticle().
G4ParticleDefinition* G4BraggIonModel::theElectron private
Definition at line 158 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4BraggIonModel.hh
Referenced by G4BraggIonModel(), and SampleSecondaries().
G4double G4BraggIonModel::theZieglerFactor private
Definition at line 177 of file G4BraggIonModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4BraggIonModel.hh
Referenced by DEDX(), and G4BraggIonModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4BraggIonModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4BraggIonModel.cc