ECCE @ EIC Software: RE03UserScoreWriter Class Reference
RE03UserScoreWriter Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE03/include/RE03UserScoreWriter.hh>
Public Member Functions
RE03UserScoreWriter ()
virtual ~RE03UserScoreWriter ()
virtual void DumpQuantityToFile (const G4String &psName, const G4String &fileName, const G4String &option)
Public Member Functions inherited from G4VScoreWriter
G4VScoreWriter ()
virtual ~G4VScoreWriter ()
virtual void DumpAllQuantitiesToFile (const G4String &fileName, const G4String &option)
void SetScoringMesh (G4VScoringMesh *sm)
void SetVerboseLevel (G4int vl)
void SetFactor (G4double val=1.0)
G4double GetFactor () const
Additional Inherited Members
Protected Member Functions inherited from G4VScoreWriter
G4int GetIndex (G4int x, G4int y, G4int z) const
Protected Attributes inherited from G4VScoreWriter
G4int fNMeshSegments [3]
G4VScoringMesh * fScoringMesh
G4int verboseLevel
G4double fact
Detailed Description
Definition at line 42 of file RE03UserScoreWriter.hh.
View newest version in sPHENIX GitHub at line 42 of file RE03UserScoreWriter.hh
Constructor & Destructor Documentation
RE03UserScoreWriter::RE03UserScoreWriter ()
Definition at line 42 of file RE03UserScoreWriter.cc.
View newest version in sPHENIX GitHub at line 42 of file RE03UserScoreWriter.cc
RE03UserScoreWriter::~RE03UserScoreWriter () virtual
Definition at line 47 of file RE03UserScoreWriter.cc.
View newest version in sPHENIX GitHub at line 47 of file RE03UserScoreWriter.cc
Member Function Documentation
void RE03UserScoreWriter::DumpQuantityToFile (const G4String & psName, const G4String & fileName, const G4String & option) virtual
Reimplemented from G4VScoreWriter.
Definition at line 51 of file RE03UserScoreWriter.cc.
View newest version in sPHENIX GitHub at line 51 of file RE03UserScoreWriter.cc
References G4VScoreWriter::fNMeshSegments, G4VScoreWriter::fScoringMesh, G4cerr, G4cout, G4endl, G4VScoreWriter::GetIndex(), G4VScoringMesh::GetScoreMap(), G4VScoringMesh::GetWorldName(), incremental_prev_tag::idx, int(), ofile, Acts::Test::transform, G4VScoreWriter::verboseLevel, x, y, and z.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE03/include/RE03UserScoreWriter.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE03/src/RE03UserScoreWriter.cc