ECCE @ EIC Software: G3DetTable Class Reference
G3DetTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3DetTable.hh>
Public Member Functions
G3DetTable ()
virtual ~G3DetTable ()
G4int GetID (G4String &set, G4String &det)
void Put (G4String &set, G4String &det, G4int id, G4VSensitiveDetector *D)
G4VSensitiveDetector * GetSD (G4String &set, G4String &det)
void PrintAll ()
Private Member Functions
G4String MakeHash (G4String &set, G4String &det)
Private Attributes
std::map< G4String,
G3DetTableEntry *, std::less
< G4String > > DTD
Detailed Description
Definition at line 38 of file G3DetTable.hh.
View newest version in sPHENIX GitHub at line 38 of file G3DetTable.hh
Constructor & Destructor Documentation
G3DetTable::G3DetTable ()
Definition at line 39 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 39 of file G3DetTable.cc
G3DetTable::~G3DetTable () virtual
Definition at line 42 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 42 of file G3DetTable.cc
Member Function Documentation
G4int G3DetTable::GetID (G4String & set, G4String & det)
Definition at line 69 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 69 of file G3DetTable.cc
References G3DetTableEntry::GetID(), and MakeHash().
Referenced by G4gsdeta().
G4VSensitiveDetector * G3DetTable::GetSD (G4String & set, G4String & det)
Definition at line 53 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 53 of file G3DetTable.cc
References G3DetTableEntry::GetSD(), and MakeHash().
G4String G3DetTable::MakeHash (G4String & set, G4String & det) private
Definition at line 35 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 35 of file G3DetTable.cc
Referenced by GetID(), GetSD(), and Put().
void G3DetTable::PrintAll (void)
Definition at line 95 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 95 of file G3DetTable.cc
References G4cout, G4endl, G4VSensitiveDetector::GetName(), and G3DetTableEntry::GetSD().
Referenced by G4BuildGeom().
void G3DetTable::Put (G4String & set, G4String & det, G4int id, G4VSensitiveDetector * D)
Definition at line 85 of file G3DetTable.cc.
View newest version in sPHENIX GitHub at line 85 of file G3DetTable.cc
References G4cout, G4endl, and MakeHash().
Member Data Documentation
std::map<G4String, G3DetTableEntry*, std::less<G4String> > G3DetTable::DTD private
Definition at line 40 of file G3DetTable.hh.
View newest version in sPHENIX GitHub at line 40 of file G3DetTable.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3DetTable.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3DetTable.cc