ECCE @ EIC Software: DNA::Penetration::Terrisol1990 Struct Reference
DNA::Penetration::Terrisol1990 Struct Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAOneStepThermalizationModel.hh>
Static Public Member Functions
static void GetPenetration (G4double energy, G4ThreeVector &displacement)
static double GetRmean (double energy)
static double Get3DStdDeviation (double energy)
Static Public Attributes
static const double gEnergies_T1990 [11]
static const double gStdDev_T1990 [11]
Detailed Description
Definition at line 101 of file G4DNAOneStepThermalizationModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4DNAOneStepThermalizationModel.hh
Member Function Documentation
double DNA::Penetration::Terrisol1990::Get3DStdDeviation (double energy) static
Definition at line 185 of file G4DNAOneStepThermalizationModel.cc.
View newest version in sPHENIX GitHub at line 185 of file G4DNAOneStepThermalizationModel.cc
References e, eV, FatalErrorInArgument, G4Exception(), gEnergies_T1990, gStdDev_T1990, it, min, and CLHEP::nanometer.
Referenced by GetPenetration(), and GetRmean().
void DNA::Penetration::Terrisol1990::GetPenetration (G4double energy, G4ThreeVector & displacement) static
Definition at line 238 of file G4DNAOneStepThermalizationModel.cc.
View newest version in sPHENIX GitHub at line 238 of file G4DNAOneStepThermalizationModel.cc
References Get3DStdDeviation(), and G4INCL::DeJongSpin::shoot().
Referenced by G4DNAWaterDissociationDisplacer::radialDistributionOfElectron().
double DNA::Penetration::Terrisol1990::GetRmean (double energy) static
Definition at line 229 of file G4DNAOneStepThermalizationModel.cc.
View newest version in sPHENIX GitHub at line 229 of file G4DNAOneStepThermalizationModel.cc
References Get3DStdDeviation().
Member Data Documentation
const double DNA::Penetration::Terrisol1990::gEnergies_T1990 static
Initial value:
=
{ 0.2, 0.5, 1, 2, 3, 4, 5, 6, 7,
  8, 9}
Definition at line 108 of file G4DNAOneStepThermalizationModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4DNAOneStepThermalizationModel.hh
Referenced by Get3DStdDeviation().
const double DNA::Penetration::Terrisol1990::gStdDev_T1990 static
Initial value:
=
{ 17.68*CLHEP::angstrom,
  22.3*CLHEP::angstrom,
  28.49*CLHEP::angstrom,
  45.35*CLHEP::angstrom,
  70.03*CLHEP::angstrom,
  98.05*CLHEP::angstrom,
  120.56*CLHEP::angstrom,
  132.73*CLHEP::angstrom,
  142.60*CLHEP::angstrom,
  137.9*CLHEP::angstrom,
  120.7*CLHEP::angstrom
}
Definition at line 109 of file G4DNAOneStepThermalizationModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4DNAOneStepThermalizationModel.hh
Referenced by Get3DStdDeviation().
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAOneStepThermalizationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAOneStepThermalizationModel.cc