ECCE @ EIC Software: G4HCofThisEvent Class Reference
G4HCofThisEvent Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4HCofThisEvent.hh>
Public Member Functions
G4HCofThisEvent ()
G4HCofThisEvent (G4int cap)
~G4HCofThisEvent ()
void * operator new (size_t)
void operator delete (void *anHCoTE)
void AddHitsCollection (G4int HCID, G4VHitsCollection *aHC)
G4VHitsCollection * GetHC (G4int i)
G4int GetNumberOfCollections ()
G4int GetCapacity ()
G4HCofThisEvent ()
G4HCofThisEvent (G4int cap)
~G4HCofThisEvent ()
void * operator new (size_t)
void operator delete (void *anHCoTE)
void AddHitsCollection (G4int HCID, G4VHitsCollection *aHC)
G4VHitsCollection * GetHC (G4int i)
G4int GetNumberOfCollections ()
G4int GetCapacity ()
G4HCofThisEvent ()
G4HCofThisEvent (G4int cap)
~G4HCofThisEvent ()
void * operator new (size_t)
void operator delete (void *anHCoTE)
void AddHitsCollection (G4int HCID, G4VHitsCollection *aHC)
G4HCofThisEvent (const G4HCofThisEvent &)
G4HCofThisEvent & operator= (const G4HCofThisEvent &)
G4VHitsCollection * GetHC (G4int i)
G4int GetNumberOfCollections ()
size_t GetCapacity ()
Private Attributes
std::vector< G4VHitsCollection * > * HC
Detailed Description
Definition at line 63 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 63 of file G4HCofThisEvent.hh
Constructor & Destructor Documentation
G4HCofThisEvent::G4HCofThisEvent ()
Definition at line 37 of file G4HCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 37 of file G4HCofThisEvent.cc
References anHCoTHAllocator_G4MT_TLS_(), and HC.
G4HCofThisEvent::G4HCofThisEvent (G4int cap)
Definition at line 42 of file G4HCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 42 of file G4HCofThisEvent.cc
References anHCoTHAllocator_G4MT_TLS_(), and HC.
G4HCofThisEvent::~G4HCofThisEvent ()
Definition at line 51 of file G4HCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HCofThisEvent.cc
References anHCoTHAllocator_G4MT_TLS_(), and HC.
G4HCofThisEvent::G4HCofThisEvent ()
G4HCofThisEvent::G4HCofThisEvent (G4int cap)
G4HCofThisEvent::~G4HCofThisEvent ()
G4HCofThisEvent::G4HCofThisEvent ()
G4HCofThisEvent::G4HCofThisEvent (G4int cap)
G4HCofThisEvent::~G4HCofThisEvent ()
G4HCofThisEvent::G4HCofThisEvent (const G4HCofThisEvent & rhs)
Definition at line 70 of file G4HCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 70 of file G4HCofThisEvent.cc
References anHCoTHAllocator_G4MT_TLS_(), and HC.
Member Function Documentation
void G4HCofThisEvent::AddHitsCollection (G4int HCID, G4VHitsCollection * aHC)
void G4HCofThisEvent::AddHitsCollection (G4int HCID, G4VHitsCollection * aHC)
void G4HCofThisEvent::AddHitsCollection (G4int HCID, G4VHitsCollection * aHC)
Definition at line 60 of file G4HCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 60 of file G4HCofThisEvent.cc
References anHCoTHAllocator_G4MT_TLS_(), HC, and G4VHitsCollection::SetColID().
Referenced by RE05CalorimeterSD::EndOfEvent(), Par01CalorimeterSD::EndOfEvent(), F02CalorimeterSD::EndOfEvent(), F01CalorimeterSD::EndOfEvent(), F03CalorimeterSD::EndOfEvent(), XrayFluoHPGeSD::EndOfEvent(), GammaRayTelTrackerSD::EndOfEvent(), GammaRayTelCalorimeterSD::EndOfEvent(), GammaRayTelAnticoincidenceSD::EndOfEvent(), DMXScintSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), UltraPMTSD::EndOfEvent(), XrayFluoSD::EndOfEvent(), G4HumanPhantomSD::Initialize(), ExN04MuonSD::Initialize(), RE01TrackerSD::Initialize(), RE05TrackerSD::Initialize(), ExN04TrackerSD::Initialize(), RE05MuonSD::Initialize(), LXeScintSD::Initialize(), B5HodoscopeSD::Initialize(), ExTGTrackerSD::Initialize(), RE01CalorimeterSD::Initialize(), eRositaTrackerSD::Initialize(), B5DriftChamberSD::Initialize(), B5EmCalorimeterSD::Initialize(), B5HadCalorimeterSD::Initialize(), XAluminumElectrodeSensitivity::Initialize(), WLSPhotonDetSD::Initialize(), ExN02TrackerSD::Initialize(), ExGflash1SensitiveDetector::Initialize(), ExGflash2SensitiveDetector::Initialize(), ExGflash3SensitiveDetector::Initialize(), ExGflashSensitiveDetector::Initialize(), SensitiveDetector::Initialize(), LXePMTSD::Initialize(), ExP01TrackerSD::Initialize(), G4PSCellCharge::Initialize(), G4PSEnergyDeposit::Initialize(), G4PSDoseDeposit::Initialize(), B2TrackerSD::Initialize(), G4PSNofStep::Initialize(), B4cCalorimeterSD::Initialize(), G4PSTrackCounter::Initialize(), UltraPMTSD::Initialize(), G4PSMinKinEAtGeneration::Initialize(), G4PSNofCollision::Initialize(), G4PSTermination::Initialize(), TrackerSD::Initialize(), G4PSPassageTrackLength::Initialize(), G4PSPopulation::Initialize(), G4PSPassageCellCurrent::Initialize(), CexmcSimpleEnergyDeposit::Initialize(), CexmcTrackPoints::Initialize(), CCaloSD::Initialize(), G4PSPassageCellFlux::Initialize(), G4PSTrackLength::Initialize(), RMC01SD::Initialize(), G4PSNofSecondary::Initialize(), G4PSCellFlux::Initialize(), G4PSSphereSurfaceCurrent::Initialize(), G4PSCylinderSurfaceFlux::Initialize(), G4PSCylinderSurfaceCurrent::Initialize(), G4PSFlatSurfaceCurrent::Initialize(), G4PSSphereSurfaceFlux::Initialize(), G4PSFlatSurfaceFlux::Initialize(), ScoreSpecies::Initialize(), and MarshaledG4HCofThisEvent::unmarshal1().
size_t G4HCofThisEvent::GetCapacity () inline
Definition at line 84 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HCofThisEvent.hh
References HC.
G4int G4HCofThisEvent::GetCapacity () inline
Definition at line 101 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HCofThisEvent.hh
References HC.
G4int G4HCofThisEvent::GetCapacity () inline
Definition at line 101 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HCofThisEvent.hh
References HC.
Referenced by G4Event::Draw(), and G4RunManager::UpdateScoring().
G4VHitsCollection* G4HCofThisEvent::GetHC (G4int i) inline
Definition at line 65 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 65 of file G4HCofThisEvent.hh
References HC.
G4VHitsCollection* G4HCofThisEvent::GetHC (G4int i) inline
Definition at line 82 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HCofThisEvent.hh
References HC.
Referenced by G4Event::Draw(), ExN04EventAction::EndOfEventAction(), ExGflashEventAction::EndOfEventAction(), RE05EventAction::EndOfEventAction(), G4HumanPhantomEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), B3aEventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), WLSEventAction::EndOfEventAction(), GammaRayTelEventAction::EndOfEventAction(), XrayFluoEventAction::EndOfEventAction(), UltraEventAction::EndOfEventAction(), DMXEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), RE01StackingAction::GetCalCollection(), RE05StackingAction::GetCollection(), ExN04StackingAction::GetCollection(), G4DigiManager::GetHitsCollection(), MarshaledG4HCofThisEvent::marshal1(), RE06Run::RecordEvent(), ElectronRun::RecordEvent(), B3bRun::RecordEvent(), ML2Run::RecordEvent(), Run::RecordEvent(), B02Run::RecordEvent(), B01Run::RecordEvent(), B03Run::RecordEvent(), DicomRun::RecordEvent(), Dicom2Run::RecordEvent(), RE02Run::RecordEvent(), TSRun::RecordEvent(), and G4RunManager::UpdateScoring().
G4VHitsCollection* G4HCofThisEvent::GetHC (G4int i) inline
Definition at line 82 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HCofThisEvent.hh
References HC.
G4int G4HCofThisEvent::GetNumberOfCollections () inline
Definition at line 72 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HCofThisEvent.hh
References HC, and n.
G4int G4HCofThisEvent::GetNumberOfCollections () inline
Definition at line 89 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HCofThisEvent.hh
References HC, and n.
G4int G4HCofThisEvent::GetNumberOfCollections () inline
Definition at line 89 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HCofThisEvent.hh
References HC, and n.
Referenced by MarshaledG4HCofThisEvent::marshal1().
void G4HCofThisEvent::operator delete (void * anHCoTE) inline
void G4HCofThisEvent::operator delete (void * anHCoTE) inline
Definition at line 121 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 121 of file G4HCofThisEvent.hh
References anHCoTHAllocator.
void G4HCofThisEvent::operator delete (void * anHCoTE) inline
void* G4HCofThisEvent::operator new (size_t) inline
void * G4HCofThisEvent::operator new (size_t) inline
Definition at line 114 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 114 of file G4HCofThisEvent.hh
References anHCoTHAllocator.
void* G4HCofThisEvent::operator new (size_t) inline
G4HCofThisEvent & G4HCofThisEvent::operator= (const G4HCofThisEvent & rhs)
Definition at line 78 of file G4HCofThisEvent.cc.
View newest version in sPHENIX GitHub at line 78 of file G4HCofThisEvent.cc
References anHCoTHAllocator_G4MT_TLS_(), HC, and it.
Member Data Documentation
std::vector< G4VHitsCollection * > * G4HCofThisEvent::HC private
Definition at line 75 of file G4HCofThisEvent.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HCofThisEvent.hh
Referenced by AddHitsCollection(), G4HCofThisEvent(), GetCapacity(), GetHC(), GetNumberOfCollections(), operator=(), and ~G4HCofThisEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4HCofThisEvent.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/G4HCofThisEvent.hh
geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4HCofThisEvent.hh
geant4/tree/geant4-10.6-release/source/digits_hits/hits/src/G4HCofThisEvent.cc