ECCE @ EIC Software: G4WaterStopping Class Reference
G4WaterStopping Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WaterStopping.hh>
Public Member Functions
G4WaterStopping (G4EmCorrections *corr=0, G4bool splineFlag=true)
~G4WaterStopping ()
G4double GetElectronicDEDX (G4int Z, G4double energy)
Private Member Functions
void Initialise (G4EmCorrections *)
void AddData (const G4double *energy, const G4double *stoppower, G4double factor)
G4WaterStopping & operator= (const G4WaterStopping &right)=delete
G4WaterStopping (const G4WaterStopping &)=delete
Private Attributes
G4bool spline
G4double emin
std::vector
< G4LPhysicsFreeVector * > dedx
Static Private Attributes
static const G4int Z [17]
static const G4double A [17]
Detailed Description
Definition at line 56 of file G4WaterStopping.hh.
View newest version in sPHENIX GitHub at line 56 of file G4WaterStopping.hh
Constructor & Destructor Documentation
G4WaterStopping::G4WaterStopping (G4EmCorrections * corr = 0, G4bool splineFlag = true) explicit
Definition at line 57 of file G4WaterStopping.cc.
View newest version in sPHENIX GitHub at line 57 of file G4WaterStopping.cc
References dedx, Initialise(), and spline.
G4WaterStopping::~G4WaterStopping ()
Definition at line 66 of file G4WaterStopping.cc.
View newest version in sPHENIX GitHub at line 66 of file G4WaterStopping.cc
G4WaterStopping::G4WaterStopping (const G4WaterStopping &) private delete
Member Function Documentation
void G4WaterStopping::AddData (const G4double * energy, const G4double * stoppower, G4double factor) private
Definition at line 90 of file G4WaterStopping.cc.
View newest version in sPHENIX GitHub at line 90 of file G4WaterStopping.cc
References dedx, MeV, G4LPhysicsFreeVector::PutValues(), G4PhysicsVector::SetSpline(), and spline.
Referenced by Initialise().
G4double G4WaterStopping::GetElectronicDEDX (G4int Z, G4double energy)
Definition at line 71 of file G4WaterStopping.cc.
View newest version in sPHENIX GitHub at line 71 of file G4WaterStopping.cc
References A, dedx, emin, and incremental_prev_tag::idx.
void G4WaterStopping::Initialise (G4EmCorrections * corr) private
Definition at line 105 of file G4WaterStopping.cc.
View newest version in sPHENIX GitHub at line 105 of file G4WaterStopping.cc
References A, AddData(), G4EmCorrections::AddStoppingData(), cm, dedx, E, emin, MeV, and Z.
Referenced by G4WaterStopping().
G4WaterStopping& G4WaterStopping::operator= (const G4WaterStopping & right) private delete
Member Data Documentation
const G4double G4WaterStopping::A static private
Initial value:
= {
  7, 9, 11, 12, 14, 16, 19, 20, 23, 24, 27, 28, 31, 32, 35, 40, 56}
Definition at line 79 of file G4WaterStopping.hh.
View newest version in sPHENIX GitHub at line 79 of file G4WaterStopping.hh
Referenced by GetElectronicDEDX(), and Initialise().
std::vector<G4LPhysicsFreeVector*> G4WaterStopping::dedx private
Definition at line 81 of file G4WaterStopping.hh.
View newest version in sPHENIX GitHub at line 81 of file G4WaterStopping.hh
Referenced by AddData(), G4WaterStopping(), GetElectronicDEDX(), and Initialise().
G4double G4WaterStopping::emin private
Definition at line 80 of file G4WaterStopping.hh.
View newest version in sPHENIX GitHub at line 80 of file G4WaterStopping.hh
Referenced by GetElectronicDEDX(), and Initialise().
G4bool G4WaterStopping::spline private
Definition at line 77 of file G4WaterStopping.hh.
View newest version in sPHENIX GitHub at line 77 of file G4WaterStopping.hh
Referenced by AddData(), and G4WaterStopping().
const G4int G4WaterStopping::Z static private
Initial value:
= {
  3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 26}
Definition at line 78 of file G4WaterStopping.hh.
View newest version in sPHENIX GitHub at line 78 of file G4WaterStopping.hh
Referenced by Initialise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WaterStopping.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4WaterStopping.cc