ECCE @ EIC Software: G4NeutrinoElectronCcXsc Class Reference
G4NeutrinoElectronCcXsc Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutrinoElectronCcXsc.hh>
Public Member Functions
G4NeutrinoElectronCcXsc ()
~G4NeutrinoElectronCcXsc ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
void SetBiasingFactor (G4double bf)
G4double GetBiasingFactor ()
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Protected Attributes
G4double fCofXsc
G4double fSin2tW
G4double fCutEnergy
G4double fBiasingFactor
G4ParticleDefinition * theMuonMinus
G4ParticleDefinition * theTauMinus
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Detailed Description
Definition at line 41 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 41 of file G4NeutrinoElectronCcXsc.hh
Constructor & Destructor Documentation
G4NeutrinoElectronCcXsc::G4NeutrinoElectronCcXsc ()
Definition at line 43 of file G4NeutrinoElectronCcXsc.cc.
View newest version in sPHENIX GitHub at line 43 of file G4NeutrinoElectronCcXsc.cc
References source.hepunit::electron_mass_c2, fBiasingFactor, fCofXsc, fCutEnergy, fSin2tW, halfpi, source.hepunit::hbarc, G4MuonMinus::MuonMinus(), G4TauMinus::TauMinus(), theMuonMinus, and theTauMinus.
G4NeutrinoElectronCcXsc::~G4NeutrinoElectronCcXsc ()
Definition at line 69 of file G4NeutrinoElectronCcXsc.cc.
View newest version in sPHENIX GitHub at line 69 of file G4NeutrinoElectronCcXsc.cc
Member Function Documentation
G4double G4NeutrinoElectronCcXsc::GetBiasingFactor () inline
Definition at line 60 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 60 of file G4NeutrinoElectronCcXsc.hh
References fBiasingFactor.
G4double G4NeutrinoElectronCcXsc::GetCutEnergy () inline
Definition at line 57 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 57 of file G4NeutrinoElectronCcXsc.hh
References fCutEnergy.
G4double G4NeutrinoElectronCcXsc::GetElementCrossSection (const G4DynamicParticle * aPart, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 100 of file G4NeutrinoElectronCcXsc.cc.
View newest version in sPHENIX GitHub at line 100 of file G4NeutrinoElectronCcXsc.cc
References bb, source.hepunit::electron_mass_c2, energy, fBiasingFactor, fCofXsc, G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), GeV, theMuonMinus, and theTauMinus.
Referenced by G4NeutrinoElectronTotXsc::GetElementCrossSection().
G4bool G4NeutrinoElectronCcXsc::IsElementApplicable (const G4DynamicParticle * aPart, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 75 of file G4NeutrinoElectronCcXsc.cc.
View newest version in sPHENIX GitHub at line 75 of file G4NeutrinoElectronCcXsc.cc
References source.hepunit::electron_mass_c2, energy, G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), theMuonMinus, and theTauMinus.
Referenced by G4NeutrinoElectronTotXsc::IsElementApplicable().
void G4NeutrinoElectronCcXsc::SetBiasingFactor (G4double bf) inline
Definition at line 59 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 59 of file G4NeutrinoElectronCcXsc.hh
References fBiasingFactor.
Referenced by G4NeutrinoElectronTotXsc::SetBiasingFactor(), and G4NeutrinoElectronTotXsc::SetBiasingFactors().
void G4NeutrinoElectronCcXsc::SetCutEnergy (G4double ec) inline
Definition at line 56 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 56 of file G4NeutrinoElectronCcXsc.hh
References fCutEnergy.
Member Data Documentation
G4double G4NeutrinoElectronCcXsc::fBiasingFactor protected
Definition at line 67 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NeutrinoElectronCcXsc.hh
Referenced by G4NeutrinoElectronCcXsc(), GetBiasingFactor(), GetElementCrossSection(), and SetBiasingFactor().
G4double G4NeutrinoElectronCcXsc::fCofXsc protected
Definition at line 60 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 60 of file G4NeutrinoElectronCcXsc.hh
Referenced by G4NeutrinoElectronCcXsc(), and GetElementCrossSection().
G4double G4NeutrinoElectronCcXsc::fCutEnergy protected
Definition at line 66 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 66 of file G4NeutrinoElectronCcXsc.hh
Referenced by G4NeutrinoElectronCcXsc(), GetCutEnergy(), and SetCutEnergy().
G4double G4NeutrinoElectronCcXsc::fSin2tW protected
Definition at line 65 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 65 of file G4NeutrinoElectronCcXsc.hh
Referenced by G4NeutrinoElectronCcXsc().
G4ParticleDefinition* G4NeutrinoElectronCcXsc::theMuonMinus protected
Definition at line 69 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NeutrinoElectronCcXsc.hh
Referenced by G4NeutrinoElectronCcXsc(), GetElementCrossSection(), and IsElementApplicable().
G4ParticleDefinition* G4NeutrinoElectronCcXsc::theTauMinus protected
Definition at line 70 of file G4NeutrinoElectronCcXsc.hh.
View newest version in sPHENIX GitHub at line 70 of file G4NeutrinoElectronCcXsc.hh
Referenced by G4NeutrinoElectronCcXsc(), GetElementCrossSection(), and IsElementApplicable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutrinoElectronCcXsc.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4NeutrinoElectronCcXsc.cc