ECCE @ EIC Software: G4CollisionNNElastic Class Reference
G4CollisionNNElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionNNElastic.hh>
Public Member Functions
G4CollisionNNElastic ()
virtual ~G4CollisionNNElastic ()
G4bool operator== (const G4CollisionNNElastic &right) const
G4bool operator!= (const G4CollisionNNElastic &right) const
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4String GetName () const
Public Member Functions inherited from G4VElasticCollision
G4VElasticCollision ()
virtual ~G4VElasticCollision ()
G4bool operator== (const G4VElasticCollision &right) const
G4bool operator!= (const G4VElasticCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const
Private Member Functions
G4CollisionNNElastic (const G4CollisionNNElastic &)
G4CollisionNNElastic & operator= (const G4CollisionNNElastic &)
Private Attributes
G4VCrossSectionSource * crossSectionSource
G4VAngularDistribution * angularDistribution
std::vector< G4String > colliders1
std::vector< G4String > colliders2
Detailed Description
Definition at line 41 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 41 of file G4CollisionNNElastic.hh
Constructor & Destructor Documentation
G4CollisionNNElastic::G4CollisionNNElastic ()
Definition at line 42 of file G4CollisionNNElastic.cc.
View newest version in sPHENIX GitHub at line 42 of file G4CollisionNNElastic.cc
References angularDistribution, colliders1, colliders2, crossSectionSource, G4ParticleDefinition::GetParticleSubType(), G4Neutron::NeutronDefinition(), and G4Proton::ProtonDefinition().
G4CollisionNNElastic::~G4CollisionNNElastic () virtual
Definition at line 56 of file G4CollisionNNElastic.cc.
View newest version in sPHENIX GitHub at line 56 of file G4CollisionNNElastic.cc
References angularDistribution, and crossSectionSource.
G4CollisionNNElastic::G4CollisionNNElastic (const G4CollisionNNElastic &) private
Member Function Documentation
virtual const G4VAngularDistribution* G4CollisionNNElastic::GetAngularDistribution () const inline protected virtual
Implements G4VCollision.
Definition at line 65 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 65 of file G4CollisionNNElastic.hh
References angularDistribution.
virtual const G4VCrossSectionSource* G4CollisionNNElastic::GetCrossSectionSource () const inline protected virtual
Implements G4VCollision.
Definition at line 64 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CollisionNNElastic.hh
References crossSectionSource.
const std::vector< G4String > & G4CollisionNNElastic::GetListOfColliders (G4int whichOne) const protected virtual
Implements G4VCollision.
Definition at line 85 of file G4CollisionNNElastic.cc.
View newest version in sPHENIX GitHub at line 85 of file G4CollisionNNElastic.cc
References colliders1, and colliders2.
virtual G4String G4CollisionNNElastic::GetName (void) const inline virtual
Implements G4VCollision.
Definition at line 56 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 56 of file G4CollisionNNElastic.hh
G4bool G4CollisionNNElastic::IsInCharge (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 65 of file G4CollisionNNElastic.cc.
View newest version in sPHENIX GitHub at line 65 of file G4CollisionNNElastic.cc
References G4KineticTrack::GetDefinition(), G4Neutron::NeutronDefinition(), and G4Proton::ProtonDefinition().
G4bool G4CollisionNNElastic::operator!= (const G4CollisionNNElastic & right) const
G4CollisionNNElastic& G4CollisionNNElastic::operator= (const G4CollisionNNElastic &) private
G4bool G4CollisionNNElastic::operator== (const G4CollisionNNElastic & right) const
Member Data Documentation
G4VAngularDistribution* G4CollisionNNElastic::angularDistribution private
Definition at line 73 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CollisionNNElastic.hh
Referenced by G4CollisionNNElastic(), GetAngularDistribution(), and ~G4CollisionNNElastic().
std::vector<G4String> G4CollisionNNElastic::colliders1 private
Definition at line 75 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CollisionNNElastic.hh
Referenced by G4CollisionNNElastic(), and GetListOfColliders().
std::vector<G4String> G4CollisionNNElastic::colliders2 private
Definition at line 76 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CollisionNNElastic.hh
Referenced by G4CollisionNNElastic(), and GetListOfColliders().
G4VCrossSectionSource* G4CollisionNNElastic::crossSectionSource private
Definition at line 72 of file G4CollisionNNElastic.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CollisionNNElastic.hh
Referenced by G4CollisionNNElastic(), GetCrossSectionSource(), and ~G4CollisionNNElastic().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionNNElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CollisionNNElastic.cc