ECCE @ EIC Software: G4VExceptionHandler Class Reference
G4VExceptionHandler Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4VExceptionHandler.hh>
Public Member Functions
G4VExceptionHandler ()
virtual ~G4VExceptionHandler ()
G4bool operator== (const G4VExceptionHandler &right) const
G4bool operator!= (const G4VExceptionHandler &right) const
virtual G4bool Notify (const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, const char *description)=0
Private Member Functions
G4VExceptionHandler (const G4VExceptionHandler &right)
G4VExceptionHandler & operator= (const G4VExceptionHandler &right)
Detailed Description
Definition at line 54 of file G4VExceptionHandler.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VExceptionHandler.hh
Constructor & Destructor Documentation
G4VExceptionHandler::G4VExceptionHandler ()
Definition at line 39 of file G4VExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VExceptionHandler.cc
References G4StateManager::GetStateManager(), and G4StateManager::SetExceptionHandler().
G4VExceptionHandler::~G4VExceptionHandler () virtual
Definition at line 45 of file G4VExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VExceptionHandler.cc
G4VExceptionHandler::G4VExceptionHandler (const G4VExceptionHandler & right) private
Definition at line 49 of file G4VExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VExceptionHandler.cc
References right.
Member Function Documentation
virtual G4bool G4VExceptionHandler::Notify (const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, const char * description) pure virtual
Implemented in G4ExceptionHandler, and PyG4ExceptionHandler.
Referenced by G4Exception().
G4bool G4VExceptionHandler::operator!= (const G4VExceptionHandler & right) const
Definition at line 66 of file G4VExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 66 of file G4VExceptionHandler.cc
G4VExceptionHandler & G4VExceptionHandler::operator= (const G4VExceptionHandler & right) private
Definition at line 54 of file G4VExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VExceptionHandler.cc
References right.
G4bool G4VExceptionHandler::operator== (const G4VExceptionHandler & right) const
Definition at line 61 of file G4VExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VExceptionHandler.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4VExceptionHandler.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4VExceptionHandler.cc