ECCE @ EIC Software: G4He3PHPBuilder Class Reference
G4He3PHPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4He3PHPBuilder.hh>
Public Member Functions
G4He3PHPBuilder ()
virtual ~G4He3PHPBuilder ()
virtual void Build (G4He3InelasticProcess *aP) finaloverride
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VHe3Builder
G4VHe3Builder ()=default
virtual ~G4VHe3Builder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theMax
G4ParticleHPInelastic * theParticlePHPModel
Detailed Description
Definition at line 49 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 49 of file G4He3PHPBuilder.hh
Constructor & Destructor Documentation
G4He3PHPBuilder::G4He3PHPBuilder ()
Definition at line 34 of file G4He3PHPBuilder.cc.
View newest version in sPHENIX GitHub at line 34 of file G4He3PHPBuilder.cc
References MeV, theMax, theMin, and theParticlePHPModel.
virtual G4He3PHPBuilder::~G4He3PHPBuilder () inline virtual
Definition at line 53 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 53 of file G4He3PHPBuilder.hh
Member Function Documentation
void G4He3PHPBuilder::Build (G4He3InelasticProcess * aP) final override virtual
Implements G4VHe3Builder.
Definition at line 48 of file G4He3PHPBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4He3PHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4He3::He3(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4HadronicInteraction::SetMinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theMax, theMin, and theParticlePHPModel.
void G4He3PHPBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VHe3Builder.
Definition at line 42 of file G4He3PHPBuilder.cc.
View newest version in sPHENIX GitHub at line 42 of file G4He3PHPBuilder.cc
References G4cout, and G4endl.
virtual void G4He3PHPBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 62 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4He3PHPBuilder.hh
References theMax.
virtual void G4He3PHPBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 58 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4He3PHPBuilder.hh
References theMin.
Member Data Documentation
G4double G4He3PHPBuilder::theMax private
Definition at line 71 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4He3PHPBuilder.hh
Referenced by Build(), G4He3PHPBuilder(), and SetMaxEnergy().
G4double G4He3PHPBuilder::theMin private
Definition at line 70 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4He3PHPBuilder.hh
Referenced by Build(), G4He3PHPBuilder(), and SetMinEnergy().
G4ParticleHPInelastic* G4He3PHPBuilder::theParticlePHPModel private
Definition at line 72 of file G4He3PHPBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4He3PHPBuilder.hh
Referenced by Build(), and G4He3PHPBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4He3PHPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4He3PHPBuilder.cc