ECCE @ EIC Software: XrayTelPhysicsList Class Reference
XrayTelPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelPhysicsList.hh>
Public Member Functions
XrayTelPhysicsList ()
~XrayTelPhysicsList ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
G4double GetCutForGamma () const
G4double GetCutForElectron () const
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Protected Member Functions
void ConstructParticle ()
void ConstructProcess ()
void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructMesons ()
void ConstructBaryons ()
void ConstructIons ()
void ConstructAllShortLiveds ()
void ConstructGeneral ()
void ConstructEM ()
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Private Attributes
G4double cutForGamma
G4double cutForElectron
Additional Inherited Members
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 57 of file XrayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 57 of file XrayTelPhysicsList.hh
Constructor & Destructor Documentation
XrayTelPhysicsList::XrayTelPhysicsList ()
Definition at line 70 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 70 of file XrayTelPhysicsList.cc
References cutForElectron, cutForGamma, G4VUserPhysicsList::defaultCutValue, m, mm, and G4VUserPhysicsList::SetVerboseLevel().
XrayTelPhysicsList::~XrayTelPhysicsList ()
Definition at line 80 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 80 of file XrayTelPhysicsList.cc
Member Function Documentation
void XrayTelPhysicsList::ConstructAllShortLiveds () protected
Definition at line 143 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 143 of file XrayTelPhysicsList.cc
References G4ShortLivedConstructor::ConstructParticle().
Referenced by ConstructParticle().
void XrayTelPhysicsList::ConstructBaryons () protected
Definition at line 129 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 129 of file XrayTelPhysicsList.cc
References G4BaryonConstructor::ConstructParticle().
Referenced by ConstructParticle().
void XrayTelPhysicsList::ConstructBosons () protected
Definition at line 96 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 96 of file XrayTelPhysicsList.cc
References G4ChargedGeantino::ChargedGeantinoDefinition(), G4Gamma::GammaDefinition(), G4Geantino::GeantinoDefinition(), and G4OpticalPhoton::OpticalPhotonDefinition().
Referenced by ConstructParticle().
void XrayTelPhysicsList::ConstructEM () protected
Definition at line 182 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 182 of file XrayTelPhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsShortLived(), and particle.
Referenced by ConstructProcess().
void XrayTelPhysicsList::ConstructGeneral () protected
Definition at line 263 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 263 of file XrayTelPhysicsList.cc
References G4ProcessManager::AddProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), idxAtRest, idxPostStep, G4Decay::IsApplicable(), particle, and G4ProcessManager::SetProcessOrdering().
Referenced by ConstructProcess().
void XrayTelPhysicsList::ConstructIons () protected
Definition at line 136 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 136 of file XrayTelPhysicsList.cc
References G4IonConstructor::ConstructParticle().
Referenced by ConstructParticle().
void XrayTelPhysicsList::ConstructLeptons () protected
Definition at line 108 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 108 of file XrayTelPhysicsList.cc
References G4AntiNeutrinoE::AntiNeutrinoEDefinition(), G4AntiNeutrinoMu::AntiNeutrinoMuDefinition(), G4MuonMinus::Definition(), G4MuonPlus::Definition(), G4Electron::ElectronDefinition(), G4NeutrinoE::NeutrinoEDefinition(), G4NeutrinoMu::NeutrinoMuDefinition(), and G4Positron::PositronDefinition().
Referenced by ConstructParticle().
void XrayTelPhysicsList::ConstructMesons () protected
Definition at line 122 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 122 of file XrayTelPhysicsList.cc
References G4MesonConstructor::ConstructParticle().
Referenced by ConstructParticle().
void XrayTelPhysicsList::ConstructParticle (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 83 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 83 of file XrayTelPhysicsList.cc
References ConstructAllShortLiveds(), ConstructBaryons(), ConstructBosons(), ConstructIons(), ConstructLeptons(), and ConstructMesons().
void XrayTelPhysicsList::ConstructProcess (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 151 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 151 of file XrayTelPhysicsList.cc
References G4VUserPhysicsList::AddTransportation(), ConstructEM(), and ConstructGeneral().
G4double XrayTelPhysicsList::GetCutForElectron () const
Definition at line 316 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 316 of file XrayTelPhysicsList.cc
References cutForElectron.
G4double XrayTelPhysicsList::GetCutForGamma () const
Definition at line 311 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 311 of file XrayTelPhysicsList.cc
References cutForGamma.
void XrayTelPhysicsList::SetCutForElectron (G4double cut)
Definition at line 305 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 305 of file XrayTelPhysicsList.cc
References cutForElectron, and G4VUserPhysicsList::ResetCuts().
void XrayTelPhysicsList::SetCutForGamma (G4double cut)
Definition at line 299 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 299 of file XrayTelPhysicsList.cc
References cutForGamma, and G4VUserPhysicsList::ResetCuts().
void XrayTelPhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 279 of file XrayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 279 of file XrayTelPhysicsList.cc
References cutForElectron, cutForGamma, G4VUserPhysicsList::DumpCutValuesTable(), G4cout, G4endl, G4VUserPhysicsList::SetCutValue(), and G4VUserPhysicsList::verboseLevel.
Member Data Documentation
G4double XrayTelPhysicsList::cutForElectron private
Definition at line 92 of file XrayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 92 of file XrayTelPhysicsList.hh
Referenced by GetCutForElectron(), SetCutForElectron(), SetCuts(), and XrayTelPhysicsList().
G4double XrayTelPhysicsList::cutForGamma private
Definition at line 91 of file XrayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 91 of file XrayTelPhysicsList.hh
Referenced by GetCutForGamma(), SetCutForGamma(), SetCuts(), and XrayTelPhysicsList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/src/XrayTelPhysicsList.cc