ECCE @ EIC Software: CCalG4Hit Class Reference
CCalG4Hit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Hit.hh>
Public Member Functions
CCalG4Hit ()
~CCalG4Hit ()
CCalG4Hit (const CCalG4Hit &right)
const CCalG4Hit & operator= (const CCalG4Hit &right)
G4bool operator== (const CCalG4Hit &)
void Draw ()
void Print ()
G4double getEM () const
void setEM (double e)
G4double getHadr () const
void setHadr (G4double e)
void addEnergyDeposit (const CCalG4Hit &aHit)
void addEnergyDeposit (G4double em, G4double hd)
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from CCalHit
CCalHit ()
~CCalHit ()
CCalHit (const CCalHit &right)
const CCalHit & operator= (const CCalHit &right)
G4bool operator== (const CCalHit &)
void print ()
CLHEP::Hep3Vector getEntry () const
void setEntry (CLHEP::Hep3Vector xyz)
G4double getIncidentEnergy () const
void setIncidentEnergy (G4double e)
G4int getTrackID () const
void setTrackID (G4int i)
unsigned int getUnitID () const
void setUnitID (unsigned int i)
G4double getTimeSlice () const
void setTimeSlice (G4double d)
G4int getTimeSliceID () const
G4double getEnergyDeposit () const
void setEnergyDeposit (const G4double e)
void addEnergyDeposit (const CCalHit &aHit)
void addEnergyDeposit (const G4double e)
Private Attributes
G4double elem
G4double hadr
Friends
std::ostream & operator<< (std::ostream &os, const CCalG4Hit &hit)
Detailed Description
Definition at line 38 of file CCalG4Hit.hh.
View newest version in sPHENIX GitHub at line 38 of file CCalG4Hit.hh
Constructor & Destructor Documentation
CCalG4Hit::CCalG4Hit ()
Definition at line 35 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 35 of file CCalG4Hit.cc
CCalG4Hit::~CCalG4Hit ()
Definition at line 40 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 40 of file CCalG4Hit.cc
CCalG4Hit::CCalG4Hit (const CCalG4Hit & right)
Definition at line 43 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalG4Hit.cc
Member Function Documentation
void CCalG4Hit::addEnergyDeposit (const CCalG4Hit & aHit)
Definition at line 63 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 63 of file CCalG4Hit.cc
References getEM(), and getHadr().
Referenced by CCaloSD::updateHit().
void CCalG4Hit::addEnergyDeposit (G4double em, G4double hd)
Definition at line 67 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 67 of file CCalG4Hit.cc
References CCalHit::addEnergyDeposit(), elem, and hadr.
void CCalG4Hit::Draw () inline virtual
Reimplemented from G4VHit.
Definition at line 53 of file CCalG4Hit.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalG4Hit.hh
G4double CCalG4Hit::getEM () const
Definition at line 57 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 57 of file CCalG4Hit.cc
References elem.
Referenced by addEnergyDeposit(), and operator<<().
G4double CCalG4Hit::getHadr () const
Definition at line 60 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 60 of file CCalG4Hit.cc
References hadr.
Referenced by addEnergyDeposit(), and operator<<().
const CCalG4Hit & CCalG4Hit::operator= (const CCalG4Hit & right)
Definition at line 49 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 49 of file CCalG4Hit.cc
References elem, hadr, and CCalHit::operator=().
G4bool CCalG4Hit::operator== (const CCalG4Hit &) inline
Definition at line 49 of file CCalG4Hit.hh.
View newest version in sPHENIX GitHub at line 49 of file CCalG4Hit.hh
void CCalG4Hit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 74 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 74 of file CCalG4Hit.cc
References G4cout.
void CCalG4Hit::setEM (double e)
Definition at line 58 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 58 of file CCalG4Hit.cc
References e, and elem.
void CCalG4Hit::setHadr (G4double e)
Definition at line 61 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 61 of file CCalG4Hit.cc
References e, and hadr.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCalG4Hit & hit) friend
Definition at line 79 of file CCalG4Hit.cc.
View newest version in sPHENIX GitHub at line 79 of file CCalG4Hit.cc
Member Data Documentation
G4double CCalG4Hit::elem private
Definition at line 67 of file CCalG4Hit.hh.
View newest version in sPHENIX GitHub at line 67 of file CCalG4Hit.hh
Referenced by addEnergyDeposit(), getEM(), operator=(), and setEM().
G4double CCalG4Hit::hadr private
Definition at line 68 of file CCalG4Hit.hh.
View newest version in sPHENIX GitHub at line 68 of file CCalG4Hit.hh
Referenced by addEnergyDeposit(), getHadr(), operator=(), and setHadr().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Hit.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalG4Hit.cc