ECCE @ EIC Software: G4UIcommandTree Class Reference
G4UIcommandTree Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcommandTree.hh>
Public Member Functions
G4UIcommandTree ()
G4UIcommandTree (const char *thePathName)
~G4UIcommandTree ()
G4bool operator== (const G4UIcommandTree &right) const
G4bool operator!= (const G4UIcommandTree &right) const
void AddNewCommand (G4UIcommand *newCommand, G4bool workerThreadOnly=false)
void RemoveCommand (G4UIcommand *aCommand, G4bool workerThreadOnly=false)
G4UIcommand * FindPath (const char *commandPath) const
G4UIcommandTree * FindCommandTree (const char *commandPath)
G4String CompleteCommandPath (const G4String &commandPath)
G4String GetFirstMatchedString (const G4String &, const G4String &) const
void List () const
void ListCurrent () const
void ListCurrentWithNum () const
void CreateHTML ()
const G4UIcommand * GetGuidance () const
const G4String GetPathName () const
G4int GetTreeEntry () const
G4int GetCommandEntry () const
G4UIcommandTree * GetTree (G4int i)
G4UIcommandTree * GetTree (const char *comNameC)
G4UIcommand * GetCommand (G4int i)
const G4String GetTitle () const
Private Member Functions
G4String CreateFileName (const char *pName)
G4String ModStr (const char *strS)
Private Attributes
std::vector< G4UIcommand * > command
std::vector< G4UIcommandTree * > tree
G4UIcommand * guidance
G4String pathName
G4bool broadcastCommands
Detailed Description
Definition at line 43 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 43 of file G4UIcommandTree.hh
Constructor & Destructor Documentation
G4UIcommandTree::G4UIcommandTree ()
Definition at line 34 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 34 of file G4UIcommandTree.cc
Referenced by AddNewCommand().
G4UIcommandTree::G4UIcommandTree (const char * thePathName)
Definition at line 38 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 38 of file G4UIcommandTree.cc
References pathName.
G4UIcommandTree::~G4UIcommandTree ()
Definition at line 44 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 44 of file G4UIcommandTree.cc
References tree.
Member Function Documentation
void G4UIcommandTree::AddNewCommand (G4UIcommand * newCommand, G4bool workerThreadOnly = false)
Definition at line 62 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 62 of file G4UIcommandTree.cc
References AddNewCommand(), G4String::append(), broadcastCommands, command, G4String::first(), G4UIcommandTree(), G4UIcommand::GetCommandPath(), GetPathName(), guidance, G4String::isNull(), pathName, G4String::remove(), G4UIcommand::SetToBeBroadcasted(), G4UIcommand::SetWorkerThreadOnly(), G4UIcommand::ToBeBroadcasted(), and tree.
Referenced by AddNewCommand(), G4UImanager::AddNewCommand(), and G4UImanager::AddWorkerCommand().
G4String G4UIcommandTree::CompleteCommandPath (const G4String & commandPath)
Definition at line 236 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 236 of file G4UIcommandTree.cc
References FindCommandTree(), G4cout, G4endl, GetCommand(), GetCommandEntry(), GetFirstMatchedString(), GetPathName(), GetTree(), GetTreeEntry(), G4String::index(), G4String::last(), and G4String::remove().
G4String G4UIcommandTree::CreateFileName (const char * pName) private
Definition at line 404 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 404 of file G4UIcommandTree.cc
References G4String::index().
Referenced by CreateHTML().
void G4UIcommandTree::CreateHTML ()
Definition at line 436 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 436 of file G4UIcommandTree.cc
References command, CreateFileName(), G4endl, G4UIcommand::GetCommandName(), G4UIparameter::GetCurrentAsDefault(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), GetPathName(), G4UIcommand::GetRange(), G4UIcommand::GetStateList(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), GetTitle(), guidance, G4UIparameter::IsOmittable(), ModStr(), pathName, and tree.
Referenced by G4UImanager::CreateHTML(), and export_G4UIcommandTree().
G4UIcommandTree * G4UIcommandTree::FindCommandTree (const char * commandPath)
Try to match a command or a path with the one given. : command or path to match
Returns
the commandTree found or NULL if not
Definition at line 208 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 208 of file G4UIcommandTree.cc
References G4String::append(), G4String::first(), GetPathName(), G4String::index(), pathName, G4String::remove(), and tree.
Referenced by CompleteCommandPath().
G4UIcommand * G4UIcommandTree::FindPath (const char * commandPath) const
Definition at line 170 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 170 of file G4UIcommandTree.cc
References G4String::append(), command, G4String::first(), GetPathName(), G4String::index(), pathName, G4String::remove(), and tree.
Referenced by G4UImanager::ApplyCommand(), G4CascadeParamMessenger::CreateDirectory(), export_G4UIcommandTree(), G4VBasicShell::FindCommand(), G4VisCommandDrawLogicalVolume::G4VisCommandDrawLogicalVolume(), G4VisCommandDrawVolume::G4VisCommandDrawVolume(), G4VisCommandSceneAddMagneticField::G4VisCommandSceneAddMagneticField(), G4UImanager::GetCurrentValues(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
G4UIcommand* G4UIcommandTree::GetCommand (G4int i) inline
Definition at line 98 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 98 of file G4UIcommandTree.hh
References command.
Referenced by G4UIGAG::CodeGenJavaParams(), G4UIGainServer::CodeGenJavaParams(), G4UIGAG::CodeGenJavaTree(), G4UIGainServer::CodeGenJavaTree(), G4UIGAG::CodeGenTclParams(), G4UIGAG::CodeGenTclTree(), CompleteCommandPath(), export_G4UIcommandTree(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendDisableList(), G4UIGainServer::SendDisableList(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
G4int G4UIcommandTree::GetCommandEntry () const inline
Definition at line 84 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 84 of file G4UIcommandTree.hh
References command.
Referenced by G4UIGAG::CodeGenJavaParams(), G4UIGainServer::CodeGenJavaParams(), G4UIGAG::CodeGenJavaTree(), G4UIGainServer::CodeGenJavaTree(), G4UIGAG::CodeGenTclParams(), G4UIGAG::CodeGenTclTree(), CompleteCommandPath(), export_G4UIcommandTree(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendDisableList(), and G4UIGainServer::SendDisableList().
G4String G4UIcommandTree::GetFirstMatchedString (const G4String & str1, const G4String & str2) const
Definition at line 316 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 316 of file G4UIcommandTree.cc
Referenced by CompleteCommandPath().
const G4UIcommand* G4UIcommandTree::GetGuidance () const inline
Definition at line 78 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 78 of file G4UIcommandTree.hh
References guidance.
Referenced by export_G4UIcommandTree(), and ListCurrent().
const G4String G4UIcommandTree::GetPathName () const inline
Definition at line 80 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UIcommandTree.hh
References pathName.
Referenced by AddNewCommand(), G4UIGAG::CodeGenJavaParams(), G4UIGainServer::CodeGenJavaParams(), G4UIGAG::CodeGenTclTree(), CompleteCommandPath(), CreateHTML(), export_G4UIcommandTree(), FindCommandTree(), FindPath(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), GetTree(), operator!=(), operator==(), and RemoveCommand().
const G4String G4UIcommandTree::GetTitle () const inline
Definition at line 100 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 100 of file G4UIcommandTree.hh
References G4UIcommand::GetTitle(), and guidance.
Referenced by G4UIGAG::CodeGenJavaParams(), G4UIGainServer::CodeGenJavaParams(), G4UIGAG::CodeGenTclTree(), CreateHTML(), export_G4UIcommandTree(), G4UIGainServer::GetNewTreeStructure(), and G4UIGAG::GetNewTreeStructure().
G4UIcommandTree* G4UIcommandTree::GetTree (G4int i) inline
Definition at line 86 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 86 of file G4UIcommandTree.hh
References tree.
Referenced by G4UIGAG::CodeGenJavaParams(), G4UIGainServer::CodeGenJavaParams(), G4UIGAG::CodeGenJavaTree(), G4UIGainServer::CodeGenJavaTree(), G4UIGAG::CodeGenTclParams(), G4UIGAG::CodeGenTclTree(), CompleteCommandPath(), G4VBasicShell::FindDirectory(), G4UImanager::FindDirectory(), G4UIGAG::FindDirPath(), G4UIGainServer::FindDirPath(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendDisableList(), G4UIGainServer::SendDisableList(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
G4UIcommandTree* G4UIcommandTree::GetTree (const char * comNameC) inline
Definition at line 88 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 88 of file G4UIcommandTree.hh
References GetPathName(), and tree.
G4int G4UIcommandTree::GetTreeEntry () const inline
Definition at line 82 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UIcommandTree.hh
References tree.
Referenced by G4UIGAG::CodeGenJavaParams(), G4UIGainServer::CodeGenJavaParams(), G4UIGAG::CodeGenJavaTree(), G4UIGainServer::CodeGenJavaTree(), G4UIGAG::CodeGenTclParams(), G4UIGAG::CodeGenTclTree(), CompleteCommandPath(), export_G4UIcommandTree(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), RemoveCommand(), G4UIGAG::SendDisableList(), G4UIGainServer::SendDisableList(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
void G4UIcommandTree::List () const
Definition at line 389 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 389 of file G4UIcommandTree.cc
References command, ListCurrent(), and tree.
Referenced by export_G4UIcommandTree(), and G4UImanager::ListCommands().
void G4UIcommandTree::ListCurrent () const
Definition at line 337 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 337 of file G4UIcommandTree.cc
References command, G4cout, G4endl, GetGuidance(), guidance, G4UIcommand::List(), pathName, and tree.
Referenced by export_G4UIcommandTree(), List(), G4UIGAG::ListDirectory(), G4VBasicShell::ListDirectory(), and G4UIGainServer::ListDirectory().
void G4UIcommandTree::ListCurrentWithNum () const
Definition at line 366 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 366 of file G4UIcommandTree.cc
References command, G4cout, G4endl, guidance, G4UIcommand::List(), pathName, and tree.
Referenced by export_G4UIcommandTree(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
G4String G4UIcommandTree::ModStr (const char * strS) private
Definition at line 414 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 414 of file G4UIcommandTree.cc
References c.
Referenced by CreateHTML().
G4bool G4UIcommandTree::operator!= (const G4UIcommandTree & right) const
Definition at line 57 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UIcommandTree.cc
References GetPathName(), and pathName.
G4bool G4UIcommandTree::operator== (const G4UIcommandTree & right) const
Definition at line 52 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 52 of file G4UIcommandTree.cc
References GetPathName(), and pathName.
void G4UIcommandTree::RemoveCommand (G4UIcommand * aCommand, G4bool workerThreadOnly = false)
Definition at line 115 of file G4UIcommandTree.cc.
View newest version in sPHENIX GitHub at line 115 of file G4UIcommandTree.cc
References G4String::append(), command, G4String::first(), G4UIcommand::GetCommandPath(), GetPathName(), GetTreeEntry(), guidance, G4String::isNull(), G4UIcommand::IsWorkerThreadOnly(), pathName, G4String::remove(), and tree.
Referenced by G4UImanager::RemoveCommand(), and G4UImanager::RemoveWorkerCommand().
Member Data Documentation
G4bool G4UIcommandTree::broadcastCommands private
Definition at line 75 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 75 of file G4UIcommandTree.hh
Referenced by AddNewCommand().
std::vector<G4UIcommand*> G4UIcommandTree::command private
Definition at line 71 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 71 of file G4UIcommandTree.hh
Referenced by AddNewCommand(), CreateHTML(), FindPath(), GetCommand(), GetCommandEntry(), List(), ListCurrent(), ListCurrentWithNum(), and RemoveCommand().
G4UIcommand* G4UIcommandTree::guidance private
Definition at line 73 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 73 of file G4UIcommandTree.hh
Referenced by AddNewCommand(), CreateHTML(), GetGuidance(), GetTitle(), ListCurrent(), ListCurrentWithNum(), and RemoveCommand().
G4String G4UIcommandTree::pathName private
Definition at line 74 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 74 of file G4UIcommandTree.hh
Referenced by AddNewCommand(), CreateHTML(), FindCommandTree(), FindPath(), G4UIcommandTree(), GetPathName(), ListCurrent(), ListCurrentWithNum(), operator!=(), operator==(), and RemoveCommand().
std::vector<G4UIcommandTree*> G4UIcommandTree::tree private
Definition at line 72 of file G4UIcommandTree.hh.
View newest version in sPHENIX GitHub at line 72 of file G4UIcommandTree.hh
Referenced by AddNewCommand(), CreateHTML(), FindCommandTree(), FindPath(), GetTree(), GetTreeEntry(), List(), ListCurrent(), ListCurrentWithNum(), RemoveCommand(), and ~G4UIcommandTree().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcommandTree.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIcommandTree.cc