ECCE @ EIC Software: OpNovicePrimaryGeneratorAction Class Reference
OpNovicePrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNovicePrimaryGeneratorAction.hh>
Public Member Functions
OpNovicePrimaryGeneratorAction ()
virtual ~OpNovicePrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
void SetOptPhotonPolar ()
void SetOptPhotonPolar (G4double)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
OpNovicePrimaryGeneratorMessenger * fGunMessenger
Detailed Description
Definition at line 46 of file OpNovicePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 46 of file OpNovicePrimaryGeneratorAction.hh
Constructor & Destructor Documentation
OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction ()
Definition at line 47 of file OpNovicePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 47 of file OpNovicePrimaryGeneratorAction.cc
References cm, fGunMessenger, G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), keV, ns, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and G4VPrimaryGenerator::SetParticleTime().
OpNovicePrimaryGeneratorAction::~OpNovicePrimaryGeneratorAction () virtual
Definition at line 71 of file OpNovicePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 71 of file OpNovicePrimaryGeneratorAction.cc
References fGunMessenger, and fParticleGun.
Member Function Documentation
void OpNovicePrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 79 of file OpNovicePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 79 of file OpNovicePrimaryGeneratorAction.cc
References fParticleGun, and G4ParticleGun::GeneratePrimaryVertex().
void OpNovicePrimaryGeneratorAction::SetOptPhotonPolar ()
Definition at line 86 of file OpNovicePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 86 of file OpNovicePrimaryGeneratorAction.cc
References angle, deg, and G4UniformRand.
Referenced by OpNovicePrimaryGeneratorMessenger::SetNewValue().
void OpNovicePrimaryGeneratorAction::SetOptPhotonPolar (G4double angle)
Definition at line 94 of file OpNovicePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 94 of file OpNovicePrimaryGeneratorAction.cc
References CLHEP::Hep3Vector::cross(), fParticleGun, G4cout, G4endl, G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleDefinition::GetParticleName(), CLHEP::normal(), and G4ParticleGun::SetParticlePolarization().
Member Data Documentation
OpNovicePrimaryGeneratorMessenger* OpNovicePrimaryGeneratorAction::fGunMessenger private
Definition at line 60 of file OpNovicePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file OpNovicePrimaryGeneratorAction.hh
Referenced by OpNovicePrimaryGeneratorAction(), and ~OpNovicePrimaryGeneratorAction().
G4ParticleGun* OpNovicePrimaryGeneratorAction::fParticleGun private
Definition at line 59 of file OpNovicePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file OpNovicePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), OpNovicePrimaryGeneratorAction(), SetOptPhotonPolar(), and ~OpNovicePrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNovicePrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/src/OpNovicePrimaryGeneratorAction.cc