ECCE @ EIC Software: HepMCG4Interface Class Reference
HepMCG4Interface Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/HepMCG4Interface.hh>
Public Member Functions
HepMCG4Interface ()
virtual ~HepMCG4Interface ()
HepMC::GenEvent * GetHepMCGenEvent () const
virtual void GeneratePrimaryVertex (G4Event *anEvent)
HepMCG4Interface ()
virtual ~HepMCG4Interface ()
HepMC::GenEvent * GetHepMCGenEvent () const
virtual void GeneratePrimaryVertex (G4Event *anEvent)
Public Member Functions inherited from G4VPrimaryGenerator
G4VPrimaryGenerator ()
virtual ~G4VPrimaryGenerator ()
G4ThreeVector GetParticlePosition ()
G4double GetParticleTime ()
void SetParticlePosition (G4ThreeVector aPosition)
void SetParticleTime (G4double aTime)
Protected Member Functions
virtual G4bool CheckVertexInsideWorld (const G4ThreeVector &pos) const
void HepMC2G4 (const HepMC::GenEvent *hepmcevt, G4Event *g4event)
virtual HepMC::GenEvent * GenerateHepMCEvent ()
virtual G4bool CheckVertexInsideWorld (const G4ThreeVector &pos) const
void HepMC2G4 (const HepMC::GenEvent *hepmcevt, G4Event *g4event)
virtual HepMC::GenEvent * GenerateHepMCEvent ()
Protected Attributes
HepMC::GenEvent * hepmcEvent
Protected Attributes inherited from G4VPrimaryGenerator
G4ThreeVector particle_position
G4double particle_time
Additional Inherited Members
Static Public Member Functions inherited from G4VPrimaryGenerator
static G4bool CheckVertexInsideWorld (const G4ThreeVector &pos)
Detailed Description
A base class for primary generation via HepMC object. This class is derived from G4VPrimaryGenerator.
Definition at line 40 of file HepMCG4Interface.hh.
View newest version in sPHENIX GitHub at line 40 of file HepMCG4Interface.hh
Constructor & Destructor Documentation
HepMCG4Interface::HepMCG4Interface ()
Definition at line 43 of file HepMCG4Interface.cc.
View newest version in sPHENIX GitHub at line 43 of file HepMCG4Interface.cc
HepMCG4Interface::~HepMCG4Interface () virtual
Definition at line 49 of file HepMCG4Interface.cc.
View newest version in sPHENIX GitHub at line 49 of file HepMCG4Interface.cc
References hepmcEvent.
HepMCG4Interface::HepMCG4Interface ()
virtual HepMCG4Interface::~HepMCG4Interface () virtual
Member Function Documentation
G4bool HepMCG4Interface::CheckVertexInsideWorld (const G4ThreeVector & pos) const protected virtual
Definition at line 56 of file HepMCG4Interface.cc.
View newest version in sPHENIX GitHub at line 56 of file HepMCG4Interface.cc
References G4TransportationManager::GetTransportationManager(), kInside, Acts::Test::navigator, and Acts::Test::world.
Referenced by HepMC2G4().
virtual G4bool HepMCG4Interface::CheckVertexInsideWorld (const G4ThreeVector & pos) const protected virtual
virtual HepMC::GenEvent* HepMCG4Interface::GenerateHepMCEvent () protected virtual
Reimplemented in HepMCG4PythiaInterface, HepMCG4PythiaInterface, HepMCG4AsciiReader, and HepMCG4AsciiReader.
HepMC::GenEvent * HepMCG4Interface::GenerateHepMCEvent () protected virtual
Reimplemented in HepMCG4PythiaInterface, HepMCG4PythiaInterface, HepMCG4AsciiReader, and HepMCG4AsciiReader.
Definition at line 118 of file HepMCG4Interface.cc.
View newest version in sPHENIX GitHub at line 118 of file HepMCG4Interface.cc
Referenced by GeneratePrimaryVertex().
void HepMCG4Interface::GeneratePrimaryVertex (G4Event * anEvent) virtual
Implements G4VPrimaryGenerator.
Definition at line 125 of file HepMCG4Interface.cc.
View newest version in sPHENIX GitHub at line 125 of file HepMCG4Interface.cc
References G4cout, G4endl, GenerateHepMCEvent(), G4RunManager::GetRunManager(), HepMC2G4(), and hepmcEvent.
virtual void HepMCG4Interface::GeneratePrimaryVertex (G4Event * anEvent) virtual
Implements G4VPrimaryGenerator.
HepMC::GenEvent* HepMCG4Interface::GetHepMCGenEvent () const
HepMC::GenEvent * HepMCG4Interface::GetHepMCGenEvent () const inline
Definition at line 73 of file HepMCG4Interface.hh.
View newest version in sPHENIX GitHub at line 73 of file HepMCG4Interface.hh
References hepmcEvent.
void HepMCG4Interface::HepMC2G4 (const HepMC::GenEvent * hepmcevt, G4Event * g4event) protected
Definition at line 70 of file HepMCG4Interface.cc.
View newest version in sPHENIX GitHub at line 70 of file HepMCG4Interface.cc
References source.hepunit::c_light, CheckVertexInsideWorld(), GeV, mm, momentum, and position.
Referenced by GeneratePrimaryVertex().
void HepMCG4Interface::HepMC2G4 (const HepMC::GenEvent * hepmcevt, G4Event * g4event) protected
Member Data Documentation
HepMC::GenEvent * HepMCG4Interface::hepmcEvent protected
Definition at line 45 of file HepMCG4Interface.hh.
View newest version in sPHENIX GitHub at line 45 of file HepMCG4Interface.hh
Referenced by GeneratePrimaryVertex(), GetHepMCGenEvent(), and ~HepMCG4Interface().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/HepMCG4Interface.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx02/include/HepMCG4Interface.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/HepMCG4Interface.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx02/src/HepMCG4Interface.cc