ECCE @ EIC Software: G4ErrorTrajState Class Reference
G4ErrorTrajState Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorTrajState.hh>
Public Member Functions
G4ErrorTrajState ()
G4ErrorTrajState (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom, const G4ErrorTrajErr &errmat=G4ErrorTrajErr(5, 0))
virtual ~G4ErrorTrajState ()
void SetData (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom)
void BuildCharge ()
virtual G4int PropagateError (const G4Track *)
virtual G4int Update (const G4Track *)
void UpdatePosMom (const G4Point3D &pos, const G4Vector3D &mom)
void DumpPosMomError (std::ostream &out=G4cout) const
virtual void Dump (std::ostream &out=G4cout) const =0
const G4String & GetParticleType () const
void SetParticleType (const G4String &partType)
G4Point3D GetPosition () const
virtual void SetPosition (const G4Point3D pos)
G4Vector3D GetMomentum () const
virtual void SetMomentum (const G4Vector3D &mom)
G4ErrorTrajErr GetError () const
virtual void SetError (G4ErrorTrajErr em)
G4Track * GetG4Track () const
void SetG4Track (G4Track *trk)
G4double GetCharge () const
void SetCharge (G4double ch)
virtual G4eTSType GetTSType () const
Protected Attributes
G4String fParticleType
G4Point3D fPosition
G4Vector3D fMomentum
G4double fCharge
G4ErrorTrajErr fError
G4eTSType theTSType
G4Track * theG4Track
G4int iverbose
Friends
std::ostream & operator<< (std::ostream &, const G4ErrorTrajState &ts)
Detailed Description
Definition at line 48 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ErrorTrajState.hh
Constructor & Destructor Documentation
G4ErrorTrajState::G4ErrorTrajState () inline
Definition at line 52 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ErrorTrajState.hh
G4ErrorTrajState::G4ErrorTrajState (const G4String & partType, const G4Point3D & pos, const G4Vector3D & mom, const G4ErrorTrajErr & errmat = G4ErrorTrajErr(5,0))
Definition at line 40 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ErrorTrajState.cc
References iverbose, and G4ErrorPropagatorData::verbose().
virtual G4ErrorTrajState::~G4ErrorTrajState () inline virtual
Definition at line 59 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ErrorTrajState.hh
Member Function Documentation
void G4ErrorTrajState::BuildCharge ()
Definition at line 84 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 84 of file G4ErrorTrajState.cc
References FatalException, fCharge, G4ParticleTable::FindParticle(), fParticleType, G4Exception(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), message(), and particle.
Referenced by G4ErrorFreeTrajState::Init(), G4ErrorSurfaceTrajState::Init(), and SetData().
virtual void G4ErrorTrajState::Dump (std::ostream & out = G4cout) const pure virtual
Implemented in G4ErrorFreeTrajState, and G4ErrorSurfaceTrajState.
void G4ErrorTrajState::DumpPosMomError (std::ostream & out = G4cout) const
Definition at line 103 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 103 of file G4ErrorTrajState.cc
Referenced by operator<<().
G4double G4ErrorTrajState::GetCharge () const inline
Definition at line 113 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ErrorTrajState.hh
References fCharge.
G4ErrorTrajErr G4ErrorTrajState::GetError () const inline
Definition at line 103 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ErrorTrajState.hh
References fError.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), and ProcessEvent().
G4Track* G4ErrorTrajState::GetG4Track () const inline
Definition at line 108 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ErrorTrajState.hh
References theG4Track.
Referenced by ProcessEvent().
G4Vector3D G4ErrorTrajState::GetMomentum () const inline
Definition at line 98 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ErrorTrajState.hh
References fMomentum.
Referenced by G4ErrorPropagator::InitG4Track(), ProcessEvent(), G4ErrorPropagator::Propagate(), and G4ErrorPropagator::PropagateOneStep().
const G4String& G4ErrorTrajState::GetParticleType () const inline
Definition at line 88 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ErrorTrajState.hh
References fParticleType.
Referenced by G4ErrorPropagator::InitG4Track(), G4ErrorPropagator::Propagate(), and G4ErrorPropagator::PropagateOneStep().
G4Point3D G4ErrorTrajState::GetPosition () const inline
Definition at line 93 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ErrorTrajState.hh
References fPosition.
Referenced by G4ErrorPropagator::GetFinalTrajState(), G4ErrorPropagator::InitG4Track(), and ProcessEvent().
virtual G4eTSType G4ErrorTrajState::GetTSType () const inline virtual
Definition at line 118 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ErrorTrajState.hh
References theTSType.
Referenced by G4ErrorPropagator::GetFinalTrajState(), G4ErrorPropagator::InitFreeTrajState(), and PropagateError().
G4int G4ErrorTrajState::PropagateError (const G4Track *) virtual
Reimplemented in G4ErrorFreeTrajState.
Definition at line 52 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ErrorTrajState.cc
References FatalException, G4endl, G4Exception(), GetTSType(), and message().
void G4ErrorTrajState::SetCharge (G4double ch) inline
Definition at line 115 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ErrorTrajState.hh
References fCharge.
void G4ErrorTrajState::SetData (const G4String & partType, const G4Point3D & pos, const G4Vector3D & mom)
Definition at line 73 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ErrorTrajState.cc
References BuildCharge(), fMomentum, fParticleType, fPosition, mom, and pos().
virtual void G4ErrorTrajState::SetError (G4ErrorTrajErr em) inline virtual
Definition at line 105 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ErrorTrajState.hh
References fError.
void G4ErrorTrajState::SetG4Track (G4Track * trk) inline
Definition at line 110 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ErrorTrajState.hh
References theG4Track.
Referenced by G4ErrorPropagator::InitG4Track().
virtual void G4ErrorTrajState::SetMomentum (const G4Vector3D & mom) inline virtual
Reimplemented in G4ErrorSurfaceTrajState, and G4ErrorFreeTrajState.
Definition at line 100 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ErrorTrajState.hh
References fMomentum, and mom.
void G4ErrorTrajState::SetParticleType (const G4String & partType) inline
Definition at line 90 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ErrorTrajState.hh
References fParticleType.
virtual void G4ErrorTrajState::SetPosition (const G4Point3D pos) inline virtual
Reimplemented in G4ErrorSurfaceTrajState, and G4ErrorFreeTrajState.
Definition at line 95 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ErrorTrajState.hh
References fPosition, and pos().
virtual G4int G4ErrorTrajState::Update (const G4Track *) inline virtual
Reimplemented in G4ErrorFreeTrajState.
Definition at line 74 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ErrorTrajState.hh
void G4ErrorTrajState::UpdatePosMom (const G4Point3D & pos, const G4Vector3D & mom)
Definition at line 64 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ErrorTrajState.cc
References fMomentum, fPosition, mom, and pos().
Referenced by G4ErrorFreeTrajState::Update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4ErrorTrajState & ts) friend
Definition at line 110 of file G4ErrorTrajState.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ErrorTrajState.cc
Member Data Documentation
G4double G4ErrorTrajState::fCharge protected
Definition at line 126 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ErrorTrajState.hh
Referenced by BuildCharge(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), GetCharge(), and SetCharge().
G4ErrorTrajErr G4ErrorTrajState::fError protected
Definition at line 127 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ErrorTrajState.hh
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), GetError(), operator<<(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), and SetError().
G4Vector3D G4ErrorTrajState::fMomentum protected
Definition at line 125 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ErrorTrajState.hh
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorSurfaceTrajState::G4ErrorSurfaceTrajState(), GetMomentum(), operator<<(), SetData(), SetMomentum(), G4ErrorSurfaceTrajState::SetParameters(), G4ErrorFreeTrajState::SetParameters(), G4ErrorFreeTrajState::SetPosition(), G4ErrorSurfaceTrajState::SetPosition(), and UpdatePosMom().
G4String G4ErrorTrajState::fParticleType protected
Definition at line 123 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ErrorTrajState.hh
Referenced by BuildCharge(), GetParticleType(), operator<<(), SetData(), and SetParticleType().
G4Point3D G4ErrorTrajState::fPosition protected
Definition at line 124 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ErrorTrajState.hh
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorSurfaceTrajState::G4ErrorSurfaceTrajState(), GetPosition(), operator<<(), SetData(), G4ErrorFreeTrajState::SetMomentum(), G4ErrorSurfaceTrajState::SetMomentum(), G4ErrorSurfaceTrajState::SetParameters(), G4ErrorFreeTrajState::SetParameters(), SetPosition(), and UpdatePosMom().
G4int G4ErrorTrajState::iverbose protected
Definition at line 133 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ErrorTrajState.hh
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorTrajState(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), and G4ErrorFreeTrajState::PropagateErrorMSC().
G4Track* G4ErrorTrajState::theG4Track protected
Definition at line 131 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ErrorTrajState.hh
Referenced by GetG4Track(), and SetG4Track().
G4eTSType G4ErrorTrajState::theTSType protected
Definition at line 129 of file G4ErrorTrajState.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ErrorTrajState.hh
Referenced by GetTSType(), G4ErrorFreeTrajState::Init(), G4ErrorSurfaceTrajState::Init(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorTrajState.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorTrajState.cc