ECCE @ EIC Software: G4DensityEffectCalculator Class Reference
G4DensityEffectCalculator Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4DensityEffectCalculator.hh>
Public Member Functions
G4DensityEffectCalculator (const G4Material *, G4int)
~G4DensityEffectCalculator ()
G4double ComputeDensityCorrection (G4double x)
Private Member Functions
G4double FermiDeltaCalculation (G4double x)
G4double Newton (G4double x0, G4bool first)
G4double DFRho (G4double)
G4double FRho (G4double)
G4double DEll (G4double)
G4double Ell (G4double)
G4double DeltaOnceSolved (G4double)
Private Attributes
const G4Material * fMaterial
G4int fVerbose
G4int fWarnings
const G4int nlev
G4double fConductivity
G4double sternx
G4double plasmaE
G4double meanexcite
G4double * sternf
G4double * levE
G4double * sternl
G4double * sternEbar
Detailed Description
Definition at line 53 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DensityEffectCalculator.hh
Constructor & Destructor Documentation
G4DensityEffectCalculator::G4DensityEffectCalculator (const G4Material * mat, G4int n)
Definition at line 56 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 56 of file G4DensityEffectCalculator.cc
References CLHEP::eV, fConductivity, fMaterial, fVerbose, G4AtomicShells::GetBindingEnergy(), G4Material::GetElement(), G4Material::GetFreeElectronDensity(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), G4AtomicShells::GetNumberOfElectrons(), G4Material::GetNumberOfElements(), G4AtomicShells::GetNumberOfShells(), G4IonisParamMat::GetPlasmaEnergy(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZasInt(), G4NistManager::Instance(), levE, max, meanexcite, nlev, plasmaE, sternEbar, sternf, sternl, sternx, sum, xx, and Z.
G4DensityEffectCalculator::~G4DensityEffectCalculator ()
Definition at line 113 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 113 of file G4DensityEffectCalculator.cc
References levE, sternEbar, sternf, and sternl.
Member Function Documentation
G4double G4DensityEffectCalculator::ComputeDensityCorrection (G4double x)
Definition at line 121 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 121 of file G4DensityEffectCalculator.cc
References kdfinder::abs(), approx(), FermiDeltaCalculation(), fMaterial, fVerbose, fWarnings, G4cout, G4endl, G4Exception(), G4IonisParamMat::GetDensityCorrection(), G4Material::GetIonisation(), G4Material::GetName(), JustWarning, maxWarnings, and x.
Referenced by G4IonisParamMat::DensityCorrection().
G4double G4DensityEffectCalculator::DEll (G4double L) private
Definition at line 312 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 312 of file G4DensityEffectCalculator.cc
References L, nlev, G4Pow::powN(), sternEbar, sternf, and y.
Referenced by Newton().
G4double G4DensityEffectCalculator::DeltaOnceSolved (G4double sternL) private
Given the Sternheimer parameter l^2 (called 'sternL' here), and that the l_i and adjusted energies have been found with SetupFermiDeltaCalc(), return the value of delta. Helper function for DoFermiDeltaCalc().
Definition at line 344 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 344 of file G4DensityEffectCalculator.cc
References G4Log(), nlev, G4Pow::powN(), G4Pow::powZ(), sternf, sternl, and sternx.
Referenced by FermiDeltaCalculation().
G4double G4DensityEffectCalculator::DFRho (G4double rho) private
Definition at line 277 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 277 of file G4DensityEffectCalculator.cc
References levE, nlev, plasmaE, G4Pow::powN(), and sternf.
Referenced by Newton().
G4double G4DensityEffectCalculator::Ell (G4double L) private
Definition at line 327 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 327 of file G4DensityEffectCalculator.cc
References L, nlev, G4Pow::powN(), G4Pow::powZ(), sternEbar, sternf, and sternx.
Referenced by Newton().
G4double G4DensityEffectCalculator::FermiDeltaCalculation (G4double x) private
Definition at line 170 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 170 of file G4DensityEffectCalculator.cc
References DeltaOnceSolved(), fMaterial, fVerbose, fWarnings, G4Exception(), G4Material::GetName(), JustWarning, levE, maxWarnings, meanexcite, Newton(), nlev, plasmaE, G4Pow::powN(), sternEbar, sternf, sternl, sternx, and x.
Referenced by ComputeDensityCorrection().
G4double G4DensityEffectCalculator::FRho (G4double rho) private
Definition at line 292 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 292 of file G4DensityEffectCalculator.cc
References fConductivity, G4Log(), levE, meanexcite, nlev, plasmaE, G4Pow::powN(), and sternf.
Referenced by Newton().
G4double G4DensityEffectCalculator::Newton (G4double x0, G4bool first) private
Definition at line 231 of file G4DensityEffectCalculator.cc.
View newest version in sPHENIX GitHub at line 231 of file G4DensityEffectCalculator.cc
References kdfinder::abs(), DEll(), DFRho(), e, Ell(), eps, FRho(), fVerbose, G4cout, G4endl, and G4InuclParticleNames::lambda.
Referenced by FermiDeltaCalculation().
Member Data Documentation
G4double G4DensityEffectCalculator::fConductivity private
Definition at line 101 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 101 of file G4DensityEffectCalculator.hh
Referenced by FRho(), and G4DensityEffectCalculator().
const G4Material* G4DensityEffectCalculator::fMaterial private
Definition at line 88 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 88 of file G4DensityEffectCalculator.hh
Referenced by ComputeDensityCorrection(), FermiDeltaCalculation(), and G4DensityEffectCalculator().
G4int G4DensityEffectCalculator::fVerbose private
Definition at line 89 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DensityEffectCalculator.hh
Referenced by ComputeDensityCorrection(), FermiDeltaCalculation(), G4DensityEffectCalculator(), and Newton().
G4int G4DensityEffectCalculator::fWarnings private
Definition at line 90 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 90 of file G4DensityEffectCalculator.hh
Referenced by ComputeDensityCorrection(), and FermiDeltaCalculation().
G4double* G4DensityEffectCalculator::levE private
Definition at line 129 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 129 of file G4DensityEffectCalculator.hh
Referenced by DFRho(), FermiDeltaCalculation(), FRho(), G4DensityEffectCalculator(), and ~G4DensityEffectCalculator().
G4double G4DensityEffectCalculator::meanexcite private
Definition at line 112 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 112 of file G4DensityEffectCalculator.hh
Referenced by FermiDeltaCalculation(), FRho(), and G4DensityEffectCalculator().
const G4int G4DensityEffectCalculator::nlev private
Definition at line 99 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 99 of file G4DensityEffectCalculator.hh
Referenced by DEll(), DeltaOnceSolved(), DFRho(), Ell(), FermiDeltaCalculation(), FRho(), and G4DensityEffectCalculator().
G4double G4DensityEffectCalculator::plasmaE private
Definition at line 108 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 108 of file G4DensityEffectCalculator.hh
Referenced by DFRho(), FermiDeltaCalculation(), FRho(), and G4DensityEffectCalculator().
G4double* G4DensityEffectCalculator::sternEbar private
Definition at line 137 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 137 of file G4DensityEffectCalculator.hh
Referenced by DEll(), Ell(), FermiDeltaCalculation(), G4DensityEffectCalculator(), and ~G4DensityEffectCalculator().
G4double* G4DensityEffectCalculator::sternf private
Definition at line 120 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 120 of file G4DensityEffectCalculator.hh
Referenced by DEll(), DeltaOnceSolved(), DFRho(), Ell(), FermiDeltaCalculation(), FRho(), G4DensityEffectCalculator(), and ~G4DensityEffectCalculator().
G4double* G4DensityEffectCalculator::sternl private
Definition at line 134 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 134 of file G4DensityEffectCalculator.hh
Referenced by DeltaOnceSolved(), FermiDeltaCalculation(), G4DensityEffectCalculator(), and ~G4DensityEffectCalculator().
G4double G4DensityEffectCalculator::sternx private
Definition at line 104 of file G4DensityEffectCalculator.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DensityEffectCalculator.hh
Referenced by DeltaOnceSolved(), Ell(), FermiDeltaCalculation(), and G4DensityEffectCalculator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4DensityEffectCalculator.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4DensityEffectCalculator.cc