ECCE @ EIC Software: G4VITProcess Class Reference
G4VITProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4VITProcess.hh>
Classes
struct G4ProcessState
class G4ProcessStateBase
Public Member Functions
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4bool operator== (const G4VITProcess &right) const
G4bool operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
virtual void StartTracking (G4Track *)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &stepData)=0
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)=0
virtual G4VParticleChange * AtRestDoIt (const G4Track &track, const G4Step &stepData)=0
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)=0
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)=0
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)=0
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static const size_t & GetMaxProcessIndex ()
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions
void RetrieveProcessInfo ()
void CreateInfo ()
template<typename T >
T * GetState ()
virtual void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
virtual void ClearInteractionTimeLeft ()
virtual void ClearNumberOfInteractionLengthLeft ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Attributes
size_t fProcessID
static size_t * fNbProcess = 0
G4bool fInstantiateProcessState
G4double * theNumberOfInteractionLengthLeft
G4double * currentInteractionLength
G4double * theInteractionTimeLeft
Detailed Description
G4VITProcess inherits from G4VProcess. A G4VITProcess is able to save its current state for a given track into G4IT. This state may be retrieve latter on to be used by the G4VITProcess. Each G4VITProcess is tagged.
Definition at line 98 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 98 of file G4VITProcess.hh
Constructor & Destructor Documentation
G4VITProcess::G4VITProcess (const G4String & name, G4ProcessType type = fNotDefined)
Definition at line 34 of file G4VITProcess.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VITProcess.cc
References currentInteractionLength, fNbProcess, fProcessID, fProposesTimeStep, fpState, SetInstantiateProcessState(), theInteractionTimeLeft, and theNumberOfInteractionLengthLeft.
G4VITProcess::~G4VITProcess () virtual
Definition at line 60 of file G4VITProcess.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VITProcess.cc
G4VITProcess::G4VITProcess (const G4VITProcess & other)
Definition at line 66 of file G4VITProcess.cc.
View newest version in sPHENIX GitHub at line 66 of file G4VITProcess.cc
References currentInteractionLength, fInstantiateProcessState, fProposesTimeStep, theInteractionTimeLeft, and theNumberOfInteractionLengthLeft.
Member Function Documentation
virtual void G4VITProcess::BuildPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4VProcess.
Reimplemented in G4DNABrownianTransportation, G4ITTransportation, G4DNASecondOrderReaction, and G4DNAElectronHoleRecombination.
Definition at line 140 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VITProcess.hh
void G4VITProcess::ClearInteractionTimeLeft () inline protected virtual
Definition at line 258 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 258 of file G4VITProcess.hh
References fpState.
Referenced by G4DNAElectronHoleRecombination::AtRestDoIt(), G4VITRestProcess::AtRestDoIt(), and G4DNAMolecularDissociation::AtRestDoIt().
void G4VITProcess::ClearNumberOfInteractionLengthLeft () inline protected virtual
Definition at line 263 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 263 of file G4VITProcess.hh
References fpState.
Referenced by G4DNAElectronHoleRecombination::AtRestDoIt(), G4VITRestProcess::AtRestDoIt(), G4VITRestDiscreteProcess::AtRestDoIt(), G4DNAMolecularDissociation::AtRestDoIt(), G4VITDiscreteProcess::PostStepDoIt(), and G4VITRestDiscreteProcess::PostStepDoIt().
void G4VITProcess::CreateInfo () protected
G4double G4VITProcess::GetInteractionTimeLeft () inline
Definition at line 273 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 273 of file G4VITProcess.hh
References fpState.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength().
const size_t & G4VITProcess::GetMaxProcessIndex () inline static
Definition at line 285 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 285 of file G4VITProcess.hh
References fNbProcess.
Referenced by G4TrackingInformation::GetProcessState().
size_t G4VITProcess::GetProcessID () const inline
Definition at line 115 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VITProcess.hh
References fProcessID.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength(), and G4ITStepProcessor::GetAtRestIL().
G4shared_ptr<G4ProcessState_Lock> G4VITProcess::GetProcessState () inline
Definition at line 120 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VITProcess.hh
References UpcastProcessState.
template<typename T > T* G4VITProcess::GetState () inline protected
Definition at line 212 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 212 of file G4VITProcess.hh
References fpState, and T.
G4bool G4VITProcess::InstantiateProcessState () inline protected
Definition at line 234 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 234 of file G4VITProcess.hh
References fInstantiateProcessState.
Referenced by StartTracking().
G4bool G4VITProcess::operator!= (const G4VITProcess & right) const
G4VITProcess & G4VITProcess::operator= (const G4VITProcess & other)
Definition at line 78 of file G4VITProcess.cc.
View newest version in sPHENIX GitHub at line 78 of file G4VITProcess.cc
G4bool G4VITProcess::operator== (const G4VITProcess & right) const
G4bool G4VITProcess::ProposesTimeStep () const inline
Definition at line 280 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 280 of file G4VITProcess.hh
References fProposesTimeStep.
Referenced by G4DNABrownianTransportation::ComputeStep(), and G4ITStepProcessor::DoDefinePhysicalStepLength().
void G4VITProcess::ResetNumberOfInteractionLengthLeft () inline virtual
WARNING : Redefine the method of G4VProcess reset (determine the value of)NumberOfInteractionLengthLeft
Reimplemented from G4VProcess.
Definition at line 268 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 268 of file G4VITProcess.hh
References fpState, and G4UniformRand.
Referenced by G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), and G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength().
void G4VITProcess::ResetProcessState () inline
Definition at line 130 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 130 of file G4VITProcess.hh
References fpState.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength(), and G4ITStepProcessor::GetAtRestIL().
void G4VITProcess::RetrieveProcessInfo () protected
void G4VITProcess::SetInstantiateProcessState (G4bool flag) inline protected
Definition at line 229 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 229 of file G4VITProcess.hh
References fInstantiateProcessState.
Referenced by G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4ITTransportation::G4ITTransportation(), and G4VITProcess().
void G4VITProcess::SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo) inline
Definition at line 125 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 125 of file G4VITProcess.hh
References DowncastState, and fpState.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength(), and G4ITStepProcessor::GetAtRestIL().
void G4VITProcess::StartTracking (G4Track * track) virtual
Reimplemented from G4VProcess.
Reimplemented in G4DNABrownianTransportation, G4ITTransportation, G4DNASecondOrderReaction, and G4DNAElectronHoleRecombination.
Definition at line 85 of file G4VITProcess.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VITProcess.cc
References currentInteractionLength, fProcessID, fpState, GetIT(), G4IT::GetTrackingInfo(), InstantiateProcessState(), G4TrackingInformation::RecordProcessState(), theInteractionTimeLeft, and theNumberOfInteractionLengthLeft.
Referenced by G4DNAElectronHoleRecombination::StartTracking(), G4DNASecondOrderReaction::StartTracking(), and G4ITTransportation::StartTracking().
void G4VITProcess::SubtractNumberOfInteractionLengthLeft (G4double previousStepSize) inline protected virtual
Definition at line 292 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 292 of file G4VITProcess.hh
References EventMustBeAborted, fpState, G4cerr, G4endl, G4Exception(), CLHEP::perMillion, G4VProcess::theProcessName, and G4VProcess::verboseLevel.
Referenced by G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), and G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength().
Member Data Documentation
G4double* G4VITProcess::currentInteractionLength private
Definition at line 254 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 254 of file G4VITProcess.hh
Referenced by G4VITProcess(), and StartTracking().
G4bool G4VITProcess::fInstantiateProcessState private
Definition at line 250 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 250 of file G4VITProcess.hh
Referenced by G4VITProcess(), InstantiateProcessState(), and SetInstantiateProcessState().
size_t * G4VITProcess::fNbProcess = 0 private
Definition at line 248 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 248 of file G4VITProcess.hh
Referenced by G4VITProcess(), and GetMaxProcessIndex().
size_t G4VITProcess::fProcessID private
Definition at line 243 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 243 of file G4VITProcess.hh
Referenced by G4VITProcess(), GetProcessID(), and StartTracking().
G4bool G4VITProcess::fProposesTimeStep protected
Definition at line 239 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 239 of file G4VITProcess.hh
Referenced by G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4VITProcess(), and ProposesTimeStep().
G4shared_ptr<G4ProcessState> G4VITProcess::fpState protected
Definition at line 217 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 217 of file G4VITProcess.hh
Referenced by G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), ClearInteractionTimeLeft(), ClearNumberOfInteractionLengthLeft(), G4DNAElectronHoleRecombination::FindReactant(), G4DNABrownianTransportation::G4DNABrownianTransportation(), G4ITTransportation::G4ITTransportation(), G4VITProcess(), GetInteractionTimeLeft(), GetState(), G4DNAElectronHoleRecombination::MakeReaction(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), ResetNumberOfInteractionLengthLeft(), ResetProcessState(), SetProcessState(), G4DNAElectronHoleRecombination::StartTracking(), G4DNASecondOrderReaction::StartTracking(), G4ITTransportation::StartTracking(), G4DNABrownianTransportation::StartTracking(), StartTracking(), and SubtractNumberOfInteractionLengthLeft().
G4double* G4VITProcess::theInteractionTimeLeft private
Definition at line 255 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 255 of file G4VITProcess.hh
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4VITProcess(), and StartTracking().
G4double* G4VITProcess::theNumberOfInteractionLengthLeft private
Definition at line 253 of file G4VITProcess.hh.
View newest version in sPHENIX GitHub at line 253 of file G4VITProcess.hh
Referenced by G4VITProcess(), and StartTracking().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4VITProcess.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4VITProcess.cc