ECCE @ EIC Software: G4RTPrimaryGeneratorAction Class Reference
G4RTPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTPrimaryGeneratorAction.hh>
Public Member Functions
G4RTPrimaryGeneratorAction ()
virtual ~G4RTPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
void SetUp ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleDefinition * particle_definition
G4double particle_energy
G4double particle_time
G4ThreeVector particle_polarization
G4VPhysicalVolume * pWorld
EInside whereisit
G4int nColumn
G4int nRow
G4ThreeVector eyePosition
G4ThreeVector eyeDirection
G4ThreeVector up
G4double headAngle
G4double viewSpan
G4double stepAngle
G4double viewSpanX
G4double viewSpanY
G4bool distortionOn
Detailed Description
Definition at line 40 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 40 of file G4RTPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
G4RTPrimaryGeneratorAction::G4RTPrimaryGeneratorAction ()
Definition at line 41 of file G4RTPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 41 of file G4RTPrimaryGeneratorAction.cc
References distortionOn, eyeDirection, eyePosition, CLHEP::GeV, headAngle, kInside, nColumn, nRow, particle_definition, particle_energy, particle_polarization, particle_time, pWorld, stepAngle, up, viewSpan, viewSpanX, viewSpanY, whereisit, and zero.
G4RTPrimaryGeneratorAction::~G4RTPrimaryGeneratorAction () virtual
Definition at line 67 of file G4RTPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 67 of file G4RTPrimaryGeneratorAction.cc
Member Function Documentation
void G4RTPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 70 of file G4RTPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 70 of file G4RTPrimaryGeneratorAction.cc
References G4Event::AddPrimaryVertex(), cp, distortionOn, eyeDirection, eyePosition, G4InuclParticleNames::gam, G4Event::GetEventID(), G4VPhysicalVolume::GetLogicalVolume(), G4ParticleDefinition::GetPDGMass(), G4LogicalVolume::GetSolid(), headAngle, kInfinity, kInside, mass, nColumn, particle, particle_definition, particle_energy, particle_polarization, particle_time, CLHEP::Hep3Vector::phi(), pWorld, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::rotateZ(), G4PrimaryParticle::SetKineticEnergy(), G4PrimaryParticle::SetMass(), G4PrimaryParticle::SetMomentumDirection(), G4PrimaryParticle::SetPolarization(), G4PrimaryVertex::SetPrimary(), G4InuclParticleNames::sp, stepAngle, CLHEP::Hep3Vector::theta(), CLHEP::Hep3Vector::unit(), up, viewSpanX, viewSpanY, whereisit, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4RTPrimaryGeneratorAction::SetUp ()
Definition at line 128 of file G4RTPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 128 of file G4RTPrimaryGeneratorAction.cc
References distortionOn, G4TheRayTracer::distortionOn, eyeDirection, G4TheRayTracer::eyeDirection, eyePosition, G4TheRayTracer::eyePosition, FatalException, G4ParticleTable::FindParticle(), G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4ParticleTable::GetParticleTable(), G4LogicalVolume::GetSolid(), G4TransportationManager::GetTransportationManager(), G4VSolid::Inside(), nColumn, G4TheRayTracer::nColumn, nRow, G4TheRayTracer::nRow, particle_definition, pWorld, stepAngle, G4TheMTRayTracer::theInstance, viewSpan, G4TheRayTracer::viewSpan, viewSpanX, viewSpanY, and whereisit.
Referenced by G4RTWorkerInitialization::WorkerRunStart().
Member Data Documentation
G4bool G4RTPrimaryGeneratorAction::distortionOn private
Definition at line 71 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4ThreeVector G4RTPrimaryGeneratorAction::eyeDirection private
Definition at line 63 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4ThreeVector G4RTPrimaryGeneratorAction::eyePosition private
Definition at line 62 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4double G4RTPrimaryGeneratorAction::headAngle private
Definition at line 65 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and GeneratePrimaries().
G4int G4RTPrimaryGeneratorAction::nColumn private
Definition at line 59 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4int G4RTPrimaryGeneratorAction::nRow private
Definition at line 60 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and SetUp().
G4ParticleDefinition* G4RTPrimaryGeneratorAction::particle_definition private
Definition at line 51 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4double G4RTPrimaryGeneratorAction::particle_energy private
Definition at line 52 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and GeneratePrimaries().
G4ThreeVector G4RTPrimaryGeneratorAction::particle_polarization private
Definition at line 54 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and GeneratePrimaries().
G4double G4RTPrimaryGeneratorAction::particle_time private
Definition at line 53 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and GeneratePrimaries().
G4VPhysicalVolume* G4RTPrimaryGeneratorAction::pWorld private
Definition at line 56 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4double G4RTPrimaryGeneratorAction::stepAngle private
Definition at line 67 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4ThreeVector G4RTPrimaryGeneratorAction::up private
Definition at line 64 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and GeneratePrimaries().
G4double G4RTPrimaryGeneratorAction::viewSpan private
Definition at line 66 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), and SetUp().
G4double G4RTPrimaryGeneratorAction::viewSpanX private
Definition at line 68 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
G4double G4RTPrimaryGeneratorAction::viewSpanY private
Definition at line 69 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
EInside G4RTPrimaryGeneratorAction::whereisit private
Definition at line 57 of file G4RTPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file G4RTPrimaryGeneratorAction.hh
Referenced by G4RTPrimaryGeneratorAction(), GeneratePrimaries(), and SetUp().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RTPrimaryGeneratorAction.cc