ECCE @ EIC Software: G4ExcitedBaryonConstructor Class Reference
G4ExcitedBaryonConstructor Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedBaryonConstructor.hh>
Public Member Functions
G4ExcitedBaryonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedBaryonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Member Functions
virtual void ConstructParticle (G4int indexOfState)
virtual void ConstructAntiParticle (G4int indexOfState)
virtual G4double GetCharge (G4int iIsoSpin3)
virtual G4int GetEncoding (G4int iIsoSpin3, G4int idxState)
virtual G4bool Exist (G4int)=0
virtual G4int GetQuarkContents (G4int, G4int)=0
virtual G4String GetName (G4int, G4int)=0
virtual G4String GetMultipletName (G4int)=0
virtual G4double GetMass (G4int state, G4int iso)=0
virtual G4double GetWidth (G4int state, G4int iso)=0
virtual G4int GetiSpin (G4int)=0
virtual G4int GetiParity (G4int)=0
virtual G4int GetEncodingOffset (G4int)=0
virtual G4DecayTable * CreateDecayTable (const G4String &, G4int, G4int, G4bool)=0
Protected Attributes
G4int NumberOfStates
G4int iIsoSpin
const G4String type
const G4int iConjugation
const G4int iGParity
const G4int leptonNumber
const G4int baryonNumber
Detailed Description
Definition at line 42 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ExcitedBaryonConstructor.hh
Constructor & Destructor Documentation
G4ExcitedBaryonConstructor::G4ExcitedBaryonConstructor (G4int nStates = 0, G4int isoSpin = 0)
Definition at line 47 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ExcitedBaryonConstructor.cc
G4ExcitedBaryonConstructor::~G4ExcitedBaryonConstructor () virtual
Definition at line 54 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ExcitedBaryonConstructor.cc
Member Function Documentation
void G4ExcitedBaryonConstructor::Construct (G4int indexOfState = -1) virtual
Definition at line 58 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ExcitedBaryonConstructor.cc
References ConstructAntiParticle(), ConstructParticle(), G4cerr, G4endl, G4ParticleTable::GetParticleTable(), and NumberOfStates.
Referenced by G4ShortLivedConstructor::ConstructResonances().
void G4ExcitedBaryonConstructor::ConstructAntiParticle (G4int indexOfState) protected virtual
Definition at line 112 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 112 of file G4ExcitedBaryonConstructor.cc
References baryonNumber, CreateDecayTable(), Exist(), GetCharge(), GetEncoding(), GetiParity(), GetiSpin(), GetMass(), GetMultipletName(), GetName(), GetWidth(), iConjugation, iGParity, iIsoSpin, leptonNumber, particle, G4ParticleDefinition::SetDecayTable(), and type.
Referenced by Construct().
void G4ExcitedBaryonConstructor::ConstructParticle (G4int indexOfState) protected virtual
Definition at line 81 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ExcitedBaryonConstructor.cc
References baryonNumber, CreateDecayTable(), Exist(), GetCharge(), GetEncoding(), GetiParity(), GetiSpin(), GetMass(), GetMultipletName(), GetName(), GetWidth(), iConjugation, iGParity, iIsoSpin, leptonNumber, particle, G4ParticleDefinition::SetDecayTable(), and type.
Referenced by Construct().
virtual G4DecayTable* G4ExcitedBaryonConstructor::CreateDecayTable (const G4String & , G4int , G4int , G4bool) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
virtual G4bool G4ExcitedBaryonConstructor::Exist (G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
G4double G4ExcitedBaryonConstructor::GetCharge (G4int iIsoSpin3) protected virtual
Definition at line 148 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 148 of file G4ExcitedBaryonConstructor.cc
References charge, eplus, GetQuarkContents(), and incremental_prev_tag::idx.
Referenced by ConstructAntiParticle(), and ConstructParticle().
G4int G4ExcitedBaryonConstructor::GetEncoding (G4int iIsoSpin3, G4int idxState) protected virtual
Reimplemented in G4ExcitedDeltaConstructor, and G4ExcitedNucleonConstructor.
Definition at line 162 of file G4ExcitedBaryonConstructor.cc.
View newest version in sPHENIX GitHub at line 162 of file G4ExcitedBaryonConstructor.cc
References GetEncodingOffset(), GetiSpin(), and GetQuarkContents().
Referenced by ConstructAntiParticle(), ConstructParticle(), G4ExcitedDeltaConstructor::GetEncoding(), and G4ExcitedNucleonConstructor::GetEncoding().
virtual G4int G4ExcitedBaryonConstructor::GetEncodingOffset (G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by GetEncoding().
virtual G4int G4ExcitedBaryonConstructor::GetiParity (G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
virtual G4int G4ExcitedBaryonConstructor::GetiSpin (G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), ConstructParticle(), and GetEncoding().
virtual G4double G4ExcitedBaryonConstructor::GetMass (G4int state, G4int iso) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
virtual G4String G4ExcitedBaryonConstructor::GetMultipletName (G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
virtual G4String G4ExcitedBaryonConstructor::GetName (G4int , G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
virtual G4int G4ExcitedBaryonConstructor::GetQuarkContents (G4int , G4int) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by GetCharge(), and GetEncoding().
virtual G4double G4ExcitedBaryonConstructor::GetWidth (G4int state, G4int iso) protected pure virtual
Implemented in G4ExcitedDeltaConstructor, G4ExcitedNucleonConstructor, G4ExcitedLambdaConstructor, G4ExcitedSigmaConstructor, and G4ExcitedXiConstructor.
Referenced by ConstructAntiParticle(), and ConstructParticle().
Member Data Documentation
const G4int G4ExcitedBaryonConstructor::baryonNumber protected
Definition at line 70 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ExcitedBaryonConstructor.hh
Referenced by ConstructAntiParticle(), and ConstructParticle().
const G4int G4ExcitedBaryonConstructor::iConjugation protected
Definition at line 67 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ExcitedBaryonConstructor.hh
Referenced by ConstructAntiParticle(), and ConstructParticle().
const G4int G4ExcitedBaryonConstructor::iGParity protected
Definition at line 68 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ExcitedBaryonConstructor.hh
Referenced by ConstructAntiParticle(), and ConstructParticle().
G4int G4ExcitedBaryonConstructor::iIsoSpin protected
Definition at line 64 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ExcitedBaryonConstructor.hh
Referenced by ConstructAntiParticle(), and ConstructParticle().
const G4int G4ExcitedBaryonConstructor::leptonNumber protected
Definition at line 69 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ExcitedBaryonConstructor.hh
Referenced by ConstructAntiParticle(), and ConstructParticle().
G4int G4ExcitedBaryonConstructor::NumberOfStates protected
Definition at line 63 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ExcitedBaryonConstructor.hh
Referenced by Construct().
const G4String G4ExcitedBaryonConstructor::type protected
Definition at line 66 of file G4ExcitedBaryonConstructor.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ExcitedBaryonConstructor.hh
Referenced by ConstructAntiParticle(), and ConstructParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedBaryonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ExcitedBaryonConstructor.cc