ECCE @ EIC Software: G4ShellVacancy Class Reference
G4ShellVacancy Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ShellVacancy.hh>
Public Member Functions
G4ShellVacancy ()
~G4ShellVacancy ()
std::vector< G4int > GenerateNumberOfIonisations (const G4MaterialCutsCouple *couple, G4double incidentEnergy, G4double eLoss) const
void AddXsiTable (G4VEMDataSet *p)
Private Member Functions
G4double AverageNOfIonisations (const G4MaterialCutsCouple *couple, G4int index, G4double energy, G4double eLoss) const
Private Attributes
std::vector< G4VEMDataSet * > xsis
Detailed Description
Definition at line 54 of file G4ShellVacancy.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ShellVacancy.hh
Constructor & Destructor Documentation
G4ShellVacancy::G4ShellVacancy ()
Definition at line 43 of file G4ShellVacancy.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ShellVacancy.cc
G4ShellVacancy::~G4ShellVacancy ()
Definition at line 47 of file G4ShellVacancy.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ShellVacancy.cc
References k, and xsis.
Member Function Documentation
void G4ShellVacancy::AddXsiTable (G4VEMDataSet * p)
Definition at line 57 of file G4ShellVacancy.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ShellVacancy.cc
References xsis.
G4double G4ShellVacancy::AverageNOfIonisations (const G4MaterialCutsCouple * couple, G4int index, G4double energy, G4double eLoss) const private
Definition at line 91 of file G4ShellVacancy.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ShellVacancy.cc
References G4VEMDataSet::FindValue(), G4MaterialCutsCouple::GetIndex(), and xsis.
Referenced by GenerateNumberOfIonisations().
std::vector< G4int > G4ShellVacancy::GenerateNumberOfIonisations (const G4MaterialCutsCouple * couple, G4double incidentEnergy, G4double eLoss) const
Definition at line 62 of file G4ShellVacancy.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ShellVacancy.cc
References AverageNOfIonisations(), G4Poisson(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetNumberOfElements(), and material().
Member Data Documentation
std::vector<G4VEMDataSet*> G4ShellVacancy::xsis private
Definition at line 75 of file G4ShellVacancy.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ShellVacancy.hh
Referenced by AddXsiTable(), AverageNOfIonisations(), and ~G4ShellVacancy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ShellVacancy.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4ShellVacancy.cc