ECCE @ EIC Software: G4SolidsWorkspace Class Reference
G4SolidsWorkspace Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4SolidsWorkspace.hh>
Public Types
using pool_type = G4TWorkspacePool< G4SolidsWorkspace >
Public Member Functions
G4SolidsWorkspace (G4bool verbose=false)
~G4SolidsWorkspace ()
void UseWorkspace ()
void ReleaseWorkspace ()
void DestroyWorkspace ()
void InitialiseWorkspace ()
void SetVerbose (G4bool v)
G4bool GetVerbose ()
Static Public Member Functions
static pool_type * GetPool ()
Protected Member Functions
void InitialiseSolids ()
Private Attributes
G4PlSideManager * fpPolyconeSideSIM = nullptr
G4PhSideManager * fpPolyhedraSideSIM = nullptr
G4PlSideData * fPolyconeSideOffset = nullptr
G4PhSideData * fPolyhedraSideOffset = nullptr
G4bool fVerbose = false
Detailed Description
Definition at line 54 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 54 of file G4SolidsWorkspace.hh
Member Typedef Documentation
using G4SolidsWorkspace::pool_type = G4TWorkspacePool<G4SolidsWorkspace>
Definition at line 58 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 58 of file G4SolidsWorkspace.hh
Constructor & Destructor Documentation
G4SolidsWorkspace::G4SolidsWorkspace (G4bool verbose = false)
Definition at line 48 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 48 of file G4SolidsWorkspace.cc
References fPolyconeSideOffset, fPolyhedraSideOffset, fpPolyconeSideSIM, fpPolyhedraSideSIM, G4GeomSplitter< T >::GetOffset(), G4PolyconeSide::GetSubInstanceManager(), G4PolyhedraSide::GetSubInstanceManager(), and InitialiseWorkspace().
G4SolidsWorkspace::~G4SolidsWorkspace ()
Definition at line 64 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 64 of file G4SolidsWorkspace.cc
Member Function Documentation
void G4SolidsWorkspace::DestroyWorkspace ()
Definition at line 116 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 116 of file G4SolidsWorkspace.cc
References fpPolyconeSideSIM, fpPolyhedraSideSIM, and G4GeomSplitter< T >::FreeSlave().
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4SolidsWorkspace::pool_type * G4SolidsWorkspace::GetPool () static
Definition at line 46 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 46 of file G4SolidsWorkspace.cc
Referenced by G4WorkerThread::BuildGeometryAndPhysicsVector(), G4WorkerThread::DestroyGeometryAndPhysicsVector(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4bool G4SolidsWorkspace::GetVerbose () inline
Definition at line 71 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 71 of file G4SolidsWorkspace.hh
References fVerbose.
void G4SolidsWorkspace::InitialiseSolids () protected
Definition at line 90 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 90 of file G4SolidsWorkspace.cc
Referenced by InitialiseWorkspace().
void G4SolidsWorkspace::InitialiseWorkspace ()
Definition at line 95 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 95 of file G4SolidsWorkspace.cc
References fpPolyconeSideSIM, fpPolyhedraSideSIM, fVerbose, G4cout, G4endl, InitialiseSolids(), and G4GeomSplitter< T >::SlaveInitializeSubInstance().
Referenced by G4SolidsWorkspace(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
void G4SolidsWorkspace::ReleaseWorkspace ()
Definition at line 83 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 83 of file G4SolidsWorkspace.cc
References fpPolyconeSideSIM, fpPolyhedraSideSIM, and G4GeomSplitter< T >::UseWorkArea().
void G4SolidsWorkspace::SetVerbose (G4bool v) inline
Definition at line 70 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 70 of file G4SolidsWorkspace.hh
References fVerbose, and v.
void G4SolidsWorkspace::UseWorkspace ()
Definition at line 69 of file G4SolidsWorkspace.cc.
View newest version in sPHENIX GitHub at line 69 of file G4SolidsWorkspace.cc
References fPolyconeSideOffset, fPolyhedraSideOffset, fpPolyconeSideSIM, fpPolyhedraSideSIM, fVerbose, G4cout, G4endl, and G4GeomSplitter< T >::UseWorkArea().
Member Data Documentation
G4PlSideData* G4SolidsWorkspace::fPolyconeSideOffset = nullptr private
Definition at line 91 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 91 of file G4SolidsWorkspace.hh
Referenced by G4SolidsWorkspace(), and UseWorkspace().
G4PhSideData* G4SolidsWorkspace::fPolyhedraSideOffset = nullptr private
Definition at line 92 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 92 of file G4SolidsWorkspace.hh
Referenced by G4SolidsWorkspace(), and UseWorkspace().
G4PlSideManager* G4SolidsWorkspace::fpPolyconeSideSIM = nullptr private
Definition at line 83 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 83 of file G4SolidsWorkspace.hh
Referenced by DestroyWorkspace(), G4SolidsWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4PhSideManager* G4SolidsWorkspace::fpPolyhedraSideSIM = nullptr private
Definition at line 84 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 84 of file G4SolidsWorkspace.hh
Referenced by DestroyWorkspace(), G4SolidsWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4bool G4SolidsWorkspace::fVerbose = false private
Definition at line 94 of file G4SolidsWorkspace.hh.
View newest version in sPHENIX GitHub at line 94 of file G4SolidsWorkspace.hh
Referenced by GetVerbose(), InitialiseWorkspace(), SetVerbose(), and UseWorkspace().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4SolidsWorkspace.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4SolidsWorkspace.cc