ECCE @ EIC Software: G4EventManager Class Reference
G4EventManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4EventManager.hh>
Public Member Functions
G4EventManager ()
~G4EventManager ()
void ProcessOneEvent (G4Event *anEvent)
void ProcessOneEvent (G4TrackVector *trackVector, G4Event *anEvent=0)
const G4Event * GetConstCurrentEvent ()
G4Event * GetNonconstCurrentEvent ()
void AbortCurrentEvent ()
void SetUserAction (G4UserEventAction *userAction)
void SetUserAction (G4UserStackingAction *userAction)
void SetUserAction (G4UserTrackingAction *userAction)
void SetUserAction (G4UserSteppingAction *userAction)
G4UserEventAction * GetUserEventAction ()
G4UserStackingAction * GetUserStackingAction ()
G4UserTrackingAction * GetUserTrackingAction ()
G4UserSteppingAction * GetUserSteppingAction ()
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
void KeepTheCurrentEvent ()
G4StackManager * GetStackManager () const
G4TrackingManager * GetTrackingManager () const
G4int GetVerboseLevel ()
void SetVerboseLevel (G4int value)
void SetUserInformation (G4VUserEventInformation *anInfo)
G4VUserEventInformation * GetUserInformation ()
G4PrimaryTransformer * GetPrimaryTransformer () const
void SetPrimaryTransformer (G4PrimaryTransformer *tf)
void StoreRandomNumberStatusToG4Event (G4int vl)
Static Public Member Functions
static G4EventManager * GetEventManager ()
Private Member Functions
G4EventManager (const G4EventManager &right)=delete
G4EventManager & operator= (const G4EventManager &right)=delete
void DoProcessing (G4Event *anEvent)
void StackTracks (G4TrackVector *trackVector, G4bool IDhasAlreadySet=false)
Private Attributes
G4Event * currentEvent
G4StackManager * trackContainer
G4TrackingManager * trackManager
G4TrajectoryContainer * trajectoryContainer
G4int trackIDCounter
G4int verboseLevel
G4SDManager * sdManager
G4PrimaryTransformer * transformer
G4bool tracking
G4bool abortRequested
G4EvManMessenger * theMessenger
G4UserEventAction * userEventAction
G4UserStackingAction * userStackingAction
G4UserTrackingAction * userTrackingAction
G4UserSteppingAction * userSteppingAction
G4int storetRandomNumberStatusToG4Event
G4String randomNumberStatusToG4Event
G4StateManager * stateManager
Static Private Attributes
static G4ThreadLocal
G4EventManager * fpEventManager = nullptr
Detailed Description
Definition at line 59 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 59 of file G4EventManager.hh
Constructor & Destructor Documentation
G4EventManager::G4EventManager ()
Definition at line 48 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 48 of file G4EventManager.cc
References FatalException, fpEventManager, G4Exception(), G4SDManager::GetSDMpointerIfExist(), G4StateManager::GetStateManager(), sdManager, stateManager, theMessenger, trackContainer, trackManager, transformer, userEventAction, userStackingAction, userSteppingAction, and userTrackingAction.
G4EventManager::~G4EventManager ()
Definition at line 81 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 81 of file G4EventManager.cc
References fpEventManager, theMessenger, trackContainer, trackManager, transformer, and userEventAction.
G4EventManager::G4EventManager (const G4EventManager & right) private delete
Member Function Documentation
void G4EventManager::AbortCurrentEvent ()
Definition at line 389 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 389 of file G4EventManager.cc
References abortRequested, G4StackManager::clear(), G4TrackingManager::EventAborted(), trackContainer, tracking, and trackManager.
Referenced by G4RunManager::AbortEvent(), G4RunManager::AbortRun(), export_G4EventManager(), and G4EvManMessenger::SetNewValue().
void G4EventManager::DoProcessing (G4Event * anEvent) private
Definition at line 98 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 98 of file G4EventManager.cc
References abortRequested, G4UserEventAction::BeginOfEventAction(), currentEvent, G4UserEventAction::EndOfEventAction(), fAlive, fKillTrackAndSecondaries, fPostponeToNextEvent, fStopAndKill, fStopButAlive, fSuspend, G4cout, G4endl, G4Exception(), G4State_EventProc, G4State_GeomClosed, G4StateManager::GetCurrentState(), G4Event::GetHCofThisEvent(), G4TransportationManager::GetNavigatorForTracking(), G4StackManager::GetNTotalTrack(), G4Event::GetNumberOfPrimaryVertex(), G4Track::GetParentID(), G4SDManager::GetSDMpointerIfExist(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), G4TransportationManager::GetTransportationManager(), G4PrimaryTransformer::GimmePrimaries(), G4TrackingManager::GimmeSecondaries(), G4TrackingManager::GimmeTrajectory(), G4TrajectoryContainer::insert(), JustWarning, G4Navigator::LocateGlobalPointAndSetup(), G4VTrajectory::MergeTrajectory(), Acts::Test::navigator, G4StackManager::PopNextTrack(), G4StackManager::PrepareNewEvent(), G4SDManager::PrepareNewEvent(), G4TrackingManager::ProcessOneTrack(), G4StackManager::PushOneTrack(), randomNumberStatusToG4Event, CLHEP::HepRandom::saveFullState(), sdManager, G4Event::SetHCofThisEvent(), G4StateManager::SetNewState(), G4Event::SetRandomNumberStatusForProcessing(), G4Event::SetTrajectoryContainer(), StackTracks(), stateManager, storetRandomNumberStatusToG4Event, G4SDManager::TerminateCurrentEvent(), track, trackContainer, trackIDCounter, tracking, trackManager, trajectoryContainer, transformer, true, userEventAction, and verboseLevel.
Referenced by ProcessOneEvent().
const G4Event* G4EventManager::GetConstCurrentEvent () inline
Definition at line 124 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4EventManager.hh
References currentEvent.
Referenced by G4VisManager::Draw(), ScoreSpecies::EndOfEvent(), G4VisManager::EndOfEvent(), export_G4EventManager(), F04EventAction::GetEventNo(), WLSEventAction::GetEventNo(), and PrimaryKiller::ProcessHits().
G4EventManager * G4EventManager::GetEventManager () static
Definition at line 45 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4EventManager.cc
References fpEventManager.
Referenced by Par02EventAction::BeginOfEventAction(), G4StackChecker::ClassifyNewTrack(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), G4VisManager::Draw(), ScoreSpecies::EndOfEvent(), G4VisManager::EndOfEvent(), ITTrackingInteractivity::EndTracking(), export_G4EventManager(), G4ErrorPropagator::G4ErrorPropagator(), G4MaterialScanner::G4MaterialScanner(), G4TheRayTracer::G4TheRayTracer(), SteppingAction::Initialize(), ITTrackingInteractivity::Initialize(), PHG4Reco::InitRun(), G4ErrorPropagator::InvokePostUserTrackingAction(), G4ErrorPropagator::InvokePreUserTrackingAction(), PrimaryKiller::ProcessHits(), G4ErrorPropagatorManager::SetSteppingManagerVerboseLevel(), G4ErrorRunManagerHelper::SetUserAction(), G4ErrorPropagatorManager::SetUserAction(), G4ErrorPropagatorManager::StartNavigator(), and ITTrackingInteractivity::~ITTrackingInteractivity().
G4Event* G4EventManager::GetNonconstCurrentEvent () inline
Definition at line 126 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4EventManager.hh
References currentEvent.
Referenced by ITTrackingInteractivity::EndTracking(), and export_G4EventManager().
G4PrimaryTransformer* G4EventManager::GetPrimaryTransformer () const inline
Definition at line 183 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 183 of file G4EventManager.hh
References transformer.
Referenced by G4RunManagerKernel::GetPrimaryTransformer().
G4StackManager* G4EventManager::GetStackManager () const inline
Definition at line 161 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 161 of file G4EventManager.hh
References trackContainer.
Referenced by export_G4EventManager(), and G4RunManagerKernel::GetStackManager().
G4TrackingManager* G4EventManager::GetTrackingManager () const inline
Definition at line 163 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 163 of file G4EventManager.hh
References trackManager.
Referenced by export_G4EventManager(), G4ErrorPropagator::G4ErrorPropagator(), G4RunManagerKernel::GetTrackingManager(), ITTrackingInteractivity::Initialize(), PHG4Reco::InitRun(), G4ErrorPropagatorManager::SetSteppingManagerVerboseLevel(), and G4ErrorPropagatorManager::StartNavigator().
G4UserEventAction* G4EventManager::GetUserEventAction () inline
Definition at line 144 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 144 of file G4EventManager.hh
References userEventAction.
Referenced by G4MaterialScanner::StoreUserActions(), and G4TheRayTracer::StoreUserActions().
G4VUserEventInformation * G4EventManager::GetUserInformation ()
Definition at line 377 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 377 of file G4EventManager.cc
References currentEvent, G4State_EventProc, G4StateManager::GetCurrentState(), G4Event::GetUserInformation(), and stateManager.
Referenced by Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), and export_G4EventManager().
G4UserStackingAction* G4EventManager::GetUserStackingAction () inline
Definition at line 146 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 146 of file G4EventManager.hh
References userStackingAction.
Referenced by G4MaterialScanner::StoreUserActions(), and G4TheRayTracer::StoreUserActions().
G4UserSteppingAction* G4EventManager::GetUserSteppingAction () inline
Definition at line 150 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 150 of file G4EventManager.hh
References userSteppingAction.
Referenced by G4MaterialScanner::StoreUserActions(), G4TheRayTracer::StoreUserActions(), and ITTrackingInteractivity::~ITTrackingInteractivity().
G4UserTrackingAction* G4EventManager::GetUserTrackingAction () inline
Definition at line 148 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 148 of file G4EventManager.hh
References userTrackingAction.
Referenced by G4ErrorPropagator::InvokePostUserTrackingAction(), G4ErrorPropagator::InvokePreUserTrackingAction(), G4MaterialScanner::StoreUserActions(), G4TheRayTracer::StoreUserActions(), and ITTrackingInteractivity::~ITTrackingInteractivity().
G4int G4EventManager::GetVerboseLevel () inline
Definition at line 167 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 167 of file G4EventManager.hh
References verboseLevel.
Referenced by RE01EventAction::EndOfEventAction(), export_G4EventManager(), and G4EvManMessenger::GetCurrentValue().
void G4EventManager::KeepTheCurrentEvent ()
Definition at line 386 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 386 of file G4EventManager.cc
References currentEvent, and G4Event::KeepTheEvent().
Referenced by G4VisManager::EndOfEvent(), and G4EvManMessenger::SetNewValue().
G4EventManager& G4EventManager::operator= (const G4EventManager & right) private delete
void G4EventManager::ProcessOneEvent (G4Event * anEvent)
Definition at line 334 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 334 of file G4EventManager.cc
References DoProcessing(), and trackIDCounter.
Referenced by G4TheRayTracer::CreateBitMap(), CexmcRunManager::DoCommonEventLoop(), G4MaterialScanner::DoScan(), G4WorkerRunManager::ProcessOneEvent(), and G4RunManager::ProcessOneEvent().
void G4EventManager::ProcessOneEvent (G4TrackVector * trackVector, G4Event * anEvent = 0)
Definition at line 340 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 340 of file G4EventManager.cc
References DoProcessing(), G4ThreadLocal, CLHEP::HepRandom::saveFullState(), G4Event::SetRandomNumberStatus(), StackTracks(), storetRandomNumberStatusToG4Event, and trackIDCounter.
void G4EventManager::SetNumberOfAdditionalWaitingStacks (G4int iAdd) inline
Definition at line 155 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 155 of file G4EventManager.hh
References G4StackManager::SetNumberOfAdditionalWaitingStacks(), and trackContainer.
Referenced by export_G4EventManager(), and G4RunManager::SetNumberOfAdditionalWaitingStacks().
void G4EventManager::SetPrimaryTransformer (G4PrimaryTransformer * tf) inline
Definition at line 185 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 185 of file G4EventManager.hh
References transformer.
Referenced by G4RunManagerKernel::SetPrimaryTransformer().
void G4EventManager::SetUserAction (G4UserEventAction * userAction)
Definition at line 310 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 310 of file G4EventManager.cc
References G4UserEventAction::SetEventManager(), and userEventAction.
Referenced by G4MaterialScanner::RestoreUserActions(), G4TheRayTracer::RestoreUserActions(), G4ErrorRunManagerHelper::SetUserAction(), G4ErrorPropagatorManager::SetUserAction(), G4RunManager::SetUserAction(), G4MaterialScanner::StoreUserActions(), and G4TheRayTracer::StoreUserActions().
void G4EventManager::SetUserAction (G4UserStackingAction * userAction)
Definition at line 316 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 316 of file G4EventManager.cc
References G4StackManager::SetUserStackingAction(), trackContainer, and userStackingAction.
void G4EventManager::SetUserAction (G4UserTrackingAction * userAction)
Definition at line 322 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4EventManager.cc
References G4TrackingManager::SetUserAction(), trackManager, and userTrackingAction.
void G4EventManager::SetUserAction (G4UserSteppingAction * userAction)
Definition at line 328 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 328 of file G4EventManager.cc
References G4TrackingManager::SetUserAction(), trackManager, and userSteppingAction.
void G4EventManager::SetUserInformation (G4VUserEventInformation * anInfo)
Definition at line 363 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 363 of file G4EventManager.cc
References currentEvent, G4Exception(), G4State_EventProc, G4StateManager::GetCurrentState(), JustWarning, G4Event::SetUserInformation(), and stateManager.
Referenced by Par02EventAction::BeginOfEventAction(), and export_G4EventManager().
void G4EventManager::SetVerboseLevel (G4int value) inline
Definition at line 169 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4EventManager.hh
References G4PrimaryTransformer::SetVerboseLevel(), G4StackManager::SetVerboseLevel(), trackContainer, transformer, and verboseLevel.
Referenced by export_G4EventManager(), and G4EvManMessenger::SetNewValue().
void G4EventManager::StackTracks (G4TrackVector * trackVector, G4bool IDhasAlreadySet = false) private
Definition at line 271 of file G4EventManager.cc.
View newest version in sPHENIX GitHub at line 271 of file G4EventManager.cc
References G4cout, G4endl, G4InuclParticleNames::pp, G4StackManager::PushOneTrack(), G4PrimaryParticle::SetTrackID(), trackContainer, trackIDCounter, and verboseLevel.
Referenced by DoProcessing(), and ProcessOneEvent().
void G4EventManager::StoreRandomNumberStatusToG4Event (G4int vl) inline
Definition at line 187 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 187 of file G4EventManager.hh
References storetRandomNumberStatusToG4Event.
Referenced by G4RunManager::StoreRandomNumberStatusToG4Event().
Member Data Documentation
G4bool G4EventManager::abortRequested private
Definition at line 109 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 109 of file G4EventManager.hh
Referenced by AbortCurrentEvent(), and DoProcessing().
G4Event* G4EventManager::currentEvent private
Definition at line 99 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 99 of file G4EventManager.hh
Referenced by DoProcessing(), GetConstCurrentEvent(), GetNonconstCurrentEvent(), GetUserInformation(), KeepTheCurrentEvent(), and SetUserInformation().
G4ThreadLocal G4EventManager * G4EventManager::fpEventManager = nullptr static private
Definition at line 66 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 66 of file G4EventManager.hh
Referenced by G4EventManager(), GetEventManager(), and ~G4EventManager().
G4String G4EventManager::randomNumberStatusToG4Event private
Definition at line 119 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4EventManager.hh
Referenced by DoProcessing().
G4SDManager* G4EventManager::sdManager private
Definition at line 106 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4EventManager.hh
Referenced by DoProcessing(), and G4EventManager().
G4StateManager* G4EventManager::stateManager private
Definition at line 121 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4EventManager.hh
Referenced by DoProcessing(), G4EventManager(), GetUserInformation(), and SetUserInformation().
G4int G4EventManager::storetRandomNumberStatusToG4Event private
Definition at line 118 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 118 of file G4EventManager.hh
Referenced by DoProcessing(), ProcessOneEvent(), and StoreRandomNumberStatusToG4Event().
G4EvManMessenger* G4EventManager::theMessenger private
Definition at line 111 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 111 of file G4EventManager.hh
Referenced by G4EventManager(), and ~G4EventManager().
G4StackManager* G4EventManager::trackContainer private
Definition at line 101 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4EventManager.hh
Referenced by AbortCurrentEvent(), DoProcessing(), G4EventManager(), GetStackManager(), SetNumberOfAdditionalWaitingStacks(), SetUserAction(), SetVerboseLevel(), StackTracks(), and ~G4EventManager().
G4int G4EventManager::trackIDCounter private
Definition at line 104 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4EventManager.hh
Referenced by DoProcessing(), ProcessOneEvent(), and StackTracks().
G4bool G4EventManager::tracking private
Definition at line 108 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 108 of file G4EventManager.hh
Referenced by AbortCurrentEvent(), and DoProcessing().
G4TrackingManager* G4EventManager::trackManager private
Definition at line 102 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 102 of file G4EventManager.hh
Referenced by AbortCurrentEvent(), DoProcessing(), G4EventManager(), GetTrackingManager(), SetUserAction(), and ~G4EventManager().
G4TrajectoryContainer* G4EventManager::trajectoryContainer private
Definition at line 103 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 103 of file G4EventManager.hh
Referenced by DoProcessing().
G4PrimaryTransformer* G4EventManager::transformer private
Definition at line 107 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4EventManager.hh
Referenced by DoProcessing(), G4EventManager(), GetPrimaryTransformer(), SetPrimaryTransformer(), SetVerboseLevel(), and ~G4EventManager().
G4UserEventAction* G4EventManager::userEventAction private
Definition at line 113 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4EventManager.hh
Referenced by DoProcessing(), G4EventManager(), GetUserEventAction(), SetUserAction(), and ~G4EventManager().
G4UserStackingAction* G4EventManager::userStackingAction private
Definition at line 114 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4EventManager.hh
Referenced by G4EventManager(), GetUserStackingAction(), and SetUserAction().
G4UserSteppingAction* G4EventManager::userSteppingAction private
Definition at line 116 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 116 of file G4EventManager.hh
Referenced by G4EventManager(), GetUserSteppingAction(), and SetUserAction().
G4UserTrackingAction* G4EventManager::userTrackingAction private
Definition at line 115 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4EventManager.hh
Referenced by G4EventManager(), GetUserTrackingAction(), and SetUserAction().
G4int G4EventManager::verboseLevel private
Definition at line 105 of file G4EventManager.hh.
View newest version in sPHENIX GitHub at line 105 of file G4EventManager.hh
Referenced by DoProcessing(), GetVerboseLevel(), SetVerboseLevel(), and StackTracks().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4EventManager.hh
geant4/tree/geant4-10.6-release/source/event/src/G4EventManager.cc