ECCE @ EIC Software: G4tgrElement Class Reference
G4tgrElement Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrElement.hh>
Public Member Functions
G4tgrElement ()
virtual ~G4tgrElement ()
const G4String & GetName () const
const G4String & GetSymbol () const
const G4String & GetType () const
Protected Attributes
G4String theName
G4String theSymbol
G4String theType
Detailed Description
Definition at line 44 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 44 of file G4tgrElement.hh
Constructor & Destructor Documentation
G4tgrElement::G4tgrElement ()
Definition at line 37 of file G4tgrElement.cc.
View newest version in sPHENIX GitHub at line 37 of file G4tgrElement.cc
G4tgrElement::~G4tgrElement () virtual
Definition at line 41 of file G4tgrElement.cc.
View newest version in sPHENIX GitHub at line 41 of file G4tgrElement.cc
Member Function Documentation
const G4String& G4tgrElement::GetName (void) const inline
Definition at line 51 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 51 of file G4tgrElement.hh
References theName.
Referenced by G4tgrMaterialFactory::AddElementFromIsotopes(), G4tgrMaterialFactory::AddElementSimple(), G4tgbElement::BuildG4ElementFromIsotopes(), G4tgbElement::BuildG4ElementSimple(), and G4tgbElement::GetName().
const G4String& G4tgrElement::GetSymbol () const inline
Definition at line 52 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 52 of file G4tgrElement.hh
References theSymbol.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes(), and G4tgbElement::BuildG4ElementSimple().
const G4String& G4tgrElement::GetType () const inline
Definition at line 53 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 53 of file G4tgrElement.hh
References theType.
Referenced by G4tgbElement::GetType().
Member Data Documentation
G4String G4tgrElement::theName protected
Definition at line 57 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 57 of file G4tgrElement.hh
Referenced by G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), GetName(), and operator<<().
G4String G4tgrElement::theSymbol protected
Definition at line 58 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 58 of file G4tgrElement.hh
Referenced by G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), and GetSymbol().
G4String G4tgrElement::theType protected
Definition at line 59 of file G4tgrElement.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrElement.hh
Referenced by G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), and GetType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrElement.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrElement.cc