ECCE @ EIC Software: G4HETCTriton Class Reference
G4HETCTriton Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCTriton.hh>
Public Member Functions
G4HETCTriton ()
~G4HETCTriton ()
Public Member Functions inherited from G4HETCChargedFragment
G4HETCChargedFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4HETCChargedFragment ()
virtual G4double SampleKineticEnergy (const G4Fragment &aFragment)
Public Member Functions inherited from G4HETCFragment
G4HETCFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4HETCFragment ()
G4double CalcEmissionProbability (const G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundFragment
G4VPreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4VPreCompoundFragment ()
void Initialize (const G4Fragment &aFragment)
G4bool IsItPossible (const G4Fragment &aFragment) const
G4ReactionProduct * GetReactionProduct () const
G4int GetA () const
G4int GetZ () const
G4int GetRestA () const
G4int GetRestZ () const
G4double GetBindingEnergy () const
G4double GetEnergyThreshold () const
G4double GetEmissionProbability () const
G4double GetNuclearMass () const
G4double GetRestNuclearMass () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Protected Member Functions
virtual G4double GetAlpha () const
virtual G4double GetBeta () const
virtual G4double GetSpinFactor () const
virtual G4double K (const G4Fragment &aFragment)
Private Member Functions
G4HETCTriton (const G4HETCTriton &right)
const G4HETCTriton & operator= (const G4HETCTriton &right)
G4bool operator== (const G4HETCTriton &right) const
G4bool operator!= (const G4HETCTriton &right) const
Private Attributes
G4TritonCoulombBarrier theTritonCoulombBarrier
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundFragment
G4NuclearLevelData * fNucData
G4DeexPrecoParameters * theParameters
G4Pow * g4calc
G4int theA
G4int theZ
G4int theResA
G4int theResZ
G4int theFragA
G4int theFragZ
G4double theResA13
G4double theBindingEnergy
G4double theMinKinEnergy
G4double theMaxKinEnergy
G4double theResMass
G4double theReducedMass
G4double theMass
G4double theEmissionProbability
G4double theCoulombBarrier
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 40 of file G4HETCTriton.hh.
View newest version in sPHENIX GitHub at line 40 of file G4HETCTriton.hh
Constructor & Destructor Documentation
G4HETCTriton::G4HETCTriton ()
Definition at line 36 of file G4HETCTriton.cc.
View newest version in sPHENIX GitHub at line 36 of file G4HETCTriton.cc
G4HETCTriton::~G4HETCTriton ()
Definition at line 40 of file G4HETCTriton.cc.
View newest version in sPHENIX GitHub at line 40 of file G4HETCTriton.cc
G4HETCTriton::G4HETCTriton (const G4HETCTriton & right) private
Member Function Documentation
G4double G4HETCTriton::GetAlpha () const protected virtual
Implements G4HETCFragment.
Definition at line 43 of file G4HETCTriton.cc.
View newest version in sPHENIX GitHub at line 43 of file G4HETCTriton.cc
References C(), e, and G4VPreCompoundFragment::theFragZ.
G4double G4HETCTriton::GetBeta () const protected virtual
Implements G4HETCFragment.
Definition at line 59 of file G4HETCTriton.cc.
View newest version in sPHENIX GitHub at line 59 of file G4HETCTriton.cc
References G4VPreCompoundFragment::theCoulombBarrier.
G4double G4HETCTriton::GetSpinFactor () const protected virtual
Implements G4HETCFragment.
Definition at line 64 of file G4HETCTriton.cc.
View newest version in sPHENIX GitHub at line 64 of file G4HETCTriton.cc
G4double G4HETCTriton::K (const G4Fragment & aFragment) protected virtual
Implements G4HETCFragment.
Definition at line 70 of file G4HETCTriton.cc.
View newest version in sPHENIX GitHub at line 70 of file G4HETCTriton.cc
References G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), H, max, P, r, G4VPreCompoundFragment::theA, G4VPreCompoundFragment::theResA, G4VPreCompoundFragment::theResZ, and G4VPreCompoundFragment::theZ.
G4bool G4HETCTriton::operator!= (const G4HETCTriton & right) const private
const G4HETCTriton& G4HETCTriton::operator= (const G4HETCTriton & right) private
G4bool G4HETCTriton::operator== (const G4HETCTriton & right) const private
Member Data Documentation
G4TritonCoulombBarrier G4HETCTriton::theTritonCoulombBarrier private
Definition at line 66 of file G4HETCTriton.hh.
View newest version in sPHENIX GitHub at line 66 of file G4HETCTriton.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCTriton.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4HETCTriton.cc