ECCE @ EIC Software: G4BaseNtupleManager Class Reference
G4BaseNtupleManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4BaseNtupleManager.hh>
Public Member Functions
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Protected Member Functions
virtual G4int CreateNtuple (const G4String &name, const G4String &title)=0
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual void FinishNtuple () final
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector)=0
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector)=0
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector)=0
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)=0
virtual void FinishNtuple (G4int ntupleId)=0
virtual G4bool SetFirstNtupleColumnId (G4int firstId) final
G4int GetFirstNtupleColumnId () const final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool AddNtupleRow () final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)=0
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)=0
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)=0
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value)=0
virtual G4bool AddNtupleRow (G4int ntupleId)=0
Protected Member Functions inherited from G4VNtupleManager
virtual void SetActivation (G4bool activation)=0
virtual void SetActivation (G4int id, G4bool activation)=0
virtual G4bool GetActivation (G4int id) const =0
virtual G4int GetNofNtuples () const =0
virtual G4int GetNofNtupleBookings () const =0
Protected Attributes
G4int fFirstNtupleColumnId
G4bool fLockFirstNtupleColumnId
Private Member Functions
G4int GetCurrentNtupleId () const
Detailed Description
Definition at line 38 of file G4BaseNtupleManager.hh.
View newest version in sPHENIX GitHub at line 38 of file G4BaseNtupleManager.hh
Constructor & Destructor Documentation
G4BaseNtupleManager::G4BaseNtupleManager (const G4AnalysisManagerState & state) explicit
Definition at line 32 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 32 of file G4BaseNtupleManager.cc
G4BaseNtupleManager::~G4BaseNtupleManager () virtual
Definition at line 39 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 39 of file G4BaseNtupleManager.cc
G4BaseNtupleManager::G4BaseNtupleManager (const G4BaseNtupleManager & rhs) delete
Member Function Documentation
G4bool G4BaseNtupleManager::AddNtupleRow () final protected virtual
Implements G4VNtupleManager.
Definition at line 115 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 115 of file G4BaseNtupleManager.cc
References G4BaseAnalysisManager::fFirstId.
virtual G4bool G4BaseNtupleManager::AddNtupleRow (G4int ntupleId) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
virtual G4int G4BaseNtupleManager::CreateNtuple (const G4String & name, const G4String & title) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4int G4BaseNtupleManager::CreateNtupleDColumn (const G4String & name, std::vector< double > * vector) final protected virtual
Implements G4VNtupleManager.
Definition at line 72 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4BaseNtupleManager.cc
References GetCurrentNtupleId().
virtual G4int G4BaseNtupleManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > * vector) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4int G4BaseNtupleManager::CreateNtupleFColumn (const G4String & name, std::vector< float > * vector) final protected virtual
Implements G4VNtupleManager.
Definition at line 65 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 65 of file G4BaseNtupleManager.cc
References GetCurrentNtupleId().
virtual G4int G4BaseNtupleManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > * vector) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4int G4BaseNtupleManager::CreateNtupleIColumn (const G4String & name, std::vector< int > * vector) final protected virtual
Implements G4VNtupleManager.
Definition at line 58 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4BaseNtupleManager.cc
References GetCurrentNtupleId().
virtual G4int G4BaseNtupleManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > * vector) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4int G4BaseNtupleManager::CreateNtupleSColumn (const G4String & name) protected virtual
Implements G4VNtupleManager.
Definition at line 79 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4BaseNtupleManager.cc
References GetCurrentNtupleId().
virtual G4int G4BaseNtupleManager::CreateNtupleSColumn (G4int ntupleId, const G4String & name) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseNtupleManager::FillNtupleDColumn (G4int id, G4double value) final protected virtual
Implements G4VNtupleManager.
Definition at line 103 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 103 of file G4BaseNtupleManager.cc
References G4BaseAnalysisManager::fFirstId.
virtual G4bool G4BaseNtupleManager::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseNtupleManager::FillNtupleFColumn (G4int id, G4float value) final protected virtual
Implements G4VNtupleManager.
Definition at line 97 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 97 of file G4BaseNtupleManager.cc
References G4BaseAnalysisManager::fFirstId.
virtual G4bool G4BaseNtupleManager::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseNtupleManager::FillNtupleIColumn (G4int id, G4int value) final protected virtual
Implements G4VNtupleManager.
Definition at line 91 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 91 of file G4BaseNtupleManager.cc
References G4BaseAnalysisManager::fFirstId.
virtual G4bool G4BaseNtupleManager::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseNtupleManager::FillNtupleSColumn (G4int id, const G4String & value) final protected virtual
Implements G4VNtupleManager.
Definition at line 109 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 109 of file G4BaseNtupleManager.cc
References G4BaseAnalysisManager::fFirstId.
virtual G4bool G4BaseNtupleManager::FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String & value) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
void G4BaseNtupleManager::FinishNtuple () final protected virtual
Implements G4VNtupleManager.
Definition at line 85 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 85 of file G4BaseNtupleManager.cc
References GetCurrentNtupleId().
virtual void G4BaseNtupleManager::FinishNtuple (G4int ntupleId) protected pure virtual
Implements G4VNtupleManager.
Implemented in G4RootPNtupleManager, G4RootMpiPNtupleManager, G4TNtupleManager< TNTUPLE >, G4TNtupleManager< tools::wcsv::ntuple >, G4TNtupleManager< tools::waxml::ntuple >, G4TNtupleManager< tools::wroot::ntuple >, and G4TNtupleManager< tools::hdf5::ntuple >.
G4int G4BaseNtupleManager::GetCurrentNtupleId () const private
Definition at line 48 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 48 of file G4BaseNtupleManager.cc
References G4BaseAnalysisManager::fFirstId, and G4VNtupleManager::GetNofNtupleBookings().
Referenced by CreateNtupleDColumn(), CreateNtupleFColumn(), CreateNtupleIColumn(), CreateNtupleSColumn(), and FinishNtuple().
G4int G4BaseNtupleManager::GetFirstNtupleColumnId () const inline final protected virtual
Implements G4VNtupleManager.
Definition at line 104 of file G4BaseNtupleManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4BaseNtupleManager.hh
References fFirstNtupleColumnId.
G4BaseNtupleManager& G4BaseNtupleManager::operator= (const G4BaseNtupleManager & rhs) delete
G4bool G4BaseNtupleManager::SetFirstNtupleColumnId (G4int firstId) final protected virtual
Implements G4VNtupleManager.
Definition at line 121 of file G4BaseNtupleManager.cc.
View newest version in sPHENIX GitHub at line 121 of file G4BaseNtupleManager.cc
References fFirstNtupleColumnId, fLockFirstNtupleColumnId, G4Exception(), and JustWarning.
Member Data Documentation
G4int G4BaseNtupleManager::fFirstNtupleColumnId protected
Definition at line 95 of file G4BaseNtupleManager.hh.
View newest version in sPHENIX GitHub at line 95 of file G4BaseNtupleManager.hh
Referenced by G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), G4TNtupleManager< tools::hdf5::ntuple >::FillNtupleTColumn(), G4TNtupleManager< tools::wroot::ntuple >::FillNtupleTColumn(), G4RootMpiPNtupleManager::FillNtupleTColumn(), G4RootPNtupleManager::FillNtupleTColumn(), GetFirstNtupleColumnId(), and SetFirstNtupleColumnId().
G4bool G4BaseNtupleManager::fLockFirstNtupleColumnId protected
Definition at line 96 of file G4BaseNtupleManager.hh.
View newest version in sPHENIX GitHub at line 96 of file G4BaseNtupleManager.hh
Referenced by G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), and SetFirstNtupleColumnId().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4BaseNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4BaseNtupleManager.cc