ECCE @ EIC Software: G4DNAWaterIonisationStructure Class Reference
G4DNAWaterIonisationStructure Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAWaterIonisationStructure.hh>
Public Member Functions
G4DNAWaterIonisationStructure ()
virtual ~G4DNAWaterIonisationStructure ()
G4double IonisationEnergy (G4int level)
G4int NumberOfLevels ()
Private Attributes
G4int nLevels
std::vector< G4double > energyConstant
Detailed Description
Definition at line 33 of file G4DNAWaterIonisationStructure.hh.
View newest version in sPHENIX GitHub at line 33 of file G4DNAWaterIonisationStructure.hh
Constructor & Destructor Documentation
G4DNAWaterIonisationStructure::G4DNAWaterIonisationStructure ()
Definition at line 29 of file G4DNAWaterIonisationStructure.cc.
View newest version in sPHENIX GitHub at line 29 of file G4DNAWaterIonisationStructure.cc
References energyConstant, eV, and nLevels.
G4DNAWaterIonisationStructure::~G4DNAWaterIonisationStructure () virtual
Definition at line 41 of file G4DNAWaterIonisationStructure.cc.
View newest version in sPHENIX GitHub at line 41 of file G4DNAWaterIonisationStructure.cc
Member Function Documentation
G4double G4DNAWaterIonisationStructure::IonisationEnergy (G4int level)
Definition at line 45 of file G4DNAWaterIonisationStructure.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DNAWaterIonisationStructure.cc
References energyConstant, and nLevels.
Referenced by G4DNAChemistryManager::CreateWaterMolecule(), G4DNABornIonisationModel1::DifferentialCrossSection(), G4DNABornIonisationModel2::DifferentialCrossSection(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4DNARuddIonisationExtendedModel::ProposedSampledEnergy(), G4DNARuddIonisationModel::RandomizeEjectedElectronEnergy(), G4DNABornIonisationModel2::RandomizeEjectedElectronEnergy(), G4DNABornIonisationModel1::RandomizeEjectedElectronEnergy(), G4DNABornIonisationModel2::RandomizeEjectedElectronEnergyFromCumulatedDcs(), G4DNABornIonisationModel1::RandomizeEjectedElectronEnergyFromCumulatedDcs(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), and G4DNABornIonisationModel2::SampleSecondaries().
G4int G4DNAWaterIonisationStructure::NumberOfLevels () inline
Definition at line 43 of file G4DNAWaterIonisationStructure.hh.
View newest version in sPHENIX GitHub at line 43 of file G4DNAWaterIonisationStructure.hh
References nLevels.
Member Data Documentation
std::vector<G4double> G4DNAWaterIonisationStructure::energyConstant private
Definition at line 52 of file G4DNAWaterIonisationStructure.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DNAWaterIonisationStructure.hh
Referenced by G4DNAWaterIonisationStructure(), and IonisationEnergy().
G4int G4DNAWaterIonisationStructure::nLevels private
Definition at line 50 of file G4DNAWaterIonisationStructure.hh.
View newest version in sPHENIX GitHub at line 50 of file G4DNAWaterIonisationStructure.hh
Referenced by G4DNAWaterIonisationStructure(), IonisationEnergy(), and NumberOfLevels().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAWaterIonisationStructure.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4DNAWaterIonisationStructure.cc