ECCE @ EIC Software: G4CollisionInitialState Class Reference
G4CollisionInitialState Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionInitialState.hh>
Public Member Functions
G4CollisionInitialState ()
G4CollisionInitialState (G4double time, G4KineticTrack *aPrimary, G4KineticTrack *aTarget)
G4CollisionInitialState (G4double time, G4KineticTrack *aPrimary, const G4KineticTrackVector &aTarget, G4BCAction *aFSGenerator)
~G4CollisionInitialState ()
G4CollisionInitialState (const G4CollisionInitialState &right)
G4CollisionInitialState & operator= (const G4CollisionInitialState &right)
G4bool operator< (const G4CollisionInitialState &right) const
G4bool operator== (const G4CollisionInitialState &right) const
G4KineticTrack * GetPrimary (void)
void SetPrimary (G4KineticTrack *aPrimary)
G4KineticTrack * GetTarget (void)
void SetTarget (G4KineticTrack *aTarget)
void AddTarget (G4KineticTrack *aTarget)
G4KineticTrackVector & GetTargetCollection (void)
G4KineticTrackVector * GetFinalState ()
G4int GetTargetBaryonNumber ()
G4int GetTargetCharge ()
G4double GetCollisionTime (void)
void SetCollisionTime (G4double value)
const G4BCAction * GetGenerator ()
void Print () const
Private Attributes
G4double theCollisionTime
G4KineticTrack * thePrimary
G4KineticTrack * theTarget
G4KineticTrackVector theTs
G4BCAction * theFSGenerator
Detailed Description
Definition at line 44 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 44 of file G4CollisionInitialState.hh
Constructor & Destructor Documentation
G4CollisionInitialState::G4CollisionInitialState ()
Definition at line 38 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 38 of file G4CollisionInitialState.cc
G4CollisionInitialState::G4CollisionInitialState (G4double time, G4KineticTrack * aPrimary, G4KineticTrack * aTarget)
Definition at line 44 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 44 of file G4CollisionInitialState.cc
References theCollisionTime, theFSGenerator, thePrimary, theTarget, theTs, and Acts::VectorHelpers::time().
G4CollisionInitialState::G4CollisionInitialState (G4double time, G4KineticTrack * aPrimary, const G4KineticTrackVector & aTarget, G4BCAction * aFSGenerator)
Definition at line 55 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 55 of file G4CollisionInitialState.cc
References theCollisionTime, theFSGenerator, thePrimary, theTarget, theTs, and Acts::VectorHelpers::time().
G4CollisionInitialState::~G4CollisionInitialState () inline
Definition at line 55 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 55 of file G4CollisionInitialState.hh
G4CollisionInitialState::G4CollisionInitialState (const G4CollisionInitialState & right)
Definition at line 68 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 68 of file G4CollisionInitialState.cc
References theCollisionTime, theFSGenerator, thePrimary, theTarget, and theTs.
Member Function Documentation
void G4CollisionInitialState::AddTarget (G4KineticTrack * aTarget) inline
Definition at line 77 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CollisionInitialState.hh
References theTs.
G4double G4CollisionInitialState::GetCollisionTime (void) inline
Definition at line 103 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 103 of file G4CollisionInitialState.hh
References theCollisionTime.
Referenced by G4CollisionManager::Print(), G4BinaryCascade::Propagate(), and G4BinaryCascade::StepParticlesOut().
G4KineticTrackVector * G4CollisionInitialState::GetFinalState ()
Definition at line 95 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 95 of file G4CollisionInitialState.cc
References G4BCAction::GetFinalState(), theFSGenerator, thePrimary, and theTs.
Referenced by G4BinaryCascade::ApplyCollision(), and G4BinaryCascade::FillVoidNucleusProducts().
const G4BCAction* G4CollisionInitialState::GetGenerator () inline
Definition at line 109 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 109 of file G4CollisionInitialState.hh
References theFSGenerator.
Referenced by G4BinaryCascade::ApplyCollision(), G4BinaryCascade::DebugApplyCollisionFail(), and G4CollisionManager::Print().
G4KineticTrack* G4CollisionInitialState::GetPrimary (void) inline
Definition at line 67 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 67 of file G4CollisionInitialState.hh
References thePrimary.
Referenced by G4BinaryCascade::ApplyCollision(), G4BinaryCascade::DebugApplyCollision(), G4BinaryCascade::DebugApplyCollisionFail(), G4BinaryCascade::DoTimeStep(), G4CollisionManager::Print(), and G4CollisionManager::RemoveTracksCollisions().
G4KineticTrack* G4CollisionInitialState::GetTarget (void) inline
Definition at line 72 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CollisionInitialState.hh
References theTarget.
Referenced by G4CollisionManager::Print(), and G4CollisionManager::RemoveTracksCollisions().
G4int G4CollisionInitialState::GetTargetBaryonNumber () inline
Definition at line 82 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CollisionInitialState.hh
References G4lrint(), and theTs.
Referenced by G4BinaryCascade::ApplyCollision().
G4int G4CollisionInitialState::GetTargetCharge () inline
Definition at line 91 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 91 of file G4CollisionInitialState.hh
References G4lrint(), and theTs.
Referenced by G4BinaryCascade::ApplyCollision().
G4KineticTrackVector& G4CollisionInitialState::GetTargetCollection (void) inline
Definition at line 79 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CollisionInitialState.hh
References theTs.
Referenced by G4BinaryCascade::ApplyCollision(), G4BinaryCascade::DebugApplyCollision(), G4BinaryCascade::DebugApplyCollisionFail(), G4BinaryCascade::FillVoidNucleusProducts(), and G4CollisionManager::RemoveTracksCollisions().
G4bool G4CollisionInitialState::operator< (const G4CollisionInitialState & right) const inline
Definition at line 60 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CollisionInitialState.hh
References theCollisionTime.
G4CollisionInitialState & G4CollisionInitialState::operator= (const G4CollisionInitialState & right)
Definition at line 77 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 77 of file G4CollisionInitialState.cc
References theCollisionTime, theFSGenerator, thePrimary, theTarget, and theTs.
G4bool G4CollisionInitialState::operator== (const G4CollisionInitialState & right) const inline
Definition at line 63 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 63 of file G4CollisionInitialState.hh
References theCollisionTime.
void G4CollisionInitialState::Print (void) const
Definition at line 105 of file G4CollisionInitialState.cc.
View newest version in sPHENIX GitHub at line 105 of file G4CollisionInitialState.cc
References G4cout, G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGEncoding(), second, theCollisionTime, thePrimary, and theTarget.
Referenced by G4BinaryCascade::ApplyCollision().
void G4CollisionInitialState::SetCollisionTime (G4double value) inline
Definition at line 105 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 105 of file G4CollisionInitialState.hh
References theCollisionTime.
void G4CollisionInitialState::SetPrimary (G4KineticTrack * aPrimary) inline
Definition at line 69 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 69 of file G4CollisionInitialState.hh
References thePrimary.
void G4CollisionInitialState::SetTarget (G4KineticTrack * aTarget) inline
Definition at line 74 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CollisionInitialState.hh
References theTarget.
Member Data Documentation
G4double G4CollisionInitialState::theCollisionTime private
Definition at line 125 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 125 of file G4CollisionInitialState.hh
Referenced by G4CollisionInitialState(), GetCollisionTime(), operator<(), operator=(), operator==(), Print(), and SetCollisionTime().
G4BCAction* G4CollisionInitialState::theFSGenerator private
Definition at line 129 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 129 of file G4CollisionInitialState.hh
Referenced by G4CollisionInitialState(), GetFinalState(), GetGenerator(), and operator=().
G4KineticTrack* G4CollisionInitialState::thePrimary private
Definition at line 126 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CollisionInitialState.hh
Referenced by G4CollisionInitialState(), GetFinalState(), GetPrimary(), operator=(), Print(), and SetPrimary().
G4KineticTrack* G4CollisionInitialState::theTarget private
Definition at line 127 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 127 of file G4CollisionInitialState.hh
Referenced by G4CollisionInitialState(), GetTarget(), operator=(), Print(), and SetTarget().
G4KineticTrackVector G4CollisionInitialState::theTs private
Definition at line 128 of file G4CollisionInitialState.hh.
View newest version in sPHENIX GitHub at line 128 of file G4CollisionInitialState.hh
Referenced by AddTarget(), G4CollisionInitialState(), GetFinalState(), GetTargetBaryonNumber(), GetTargetCharge(), GetTargetCollection(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionInitialState.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CollisionInitialState.cc