ECCE @ EIC Software: G4PVParameterised Class Reference
G4PVParameterised Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4PVParameterised.hh>
Public Member Functions
G4PVParameterised (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const EAxis pAxis, const G4int nReplicas, G4VPVParameterisation *pParam, G4bool pSurfChk=false)
G4PVParameterised (const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, G4VPVParameterisation *pParam, G4bool pSurfChk=false)
G4PVParameterised (__void__ &)
virtual ~G4PVParameterised ()
G4bool IsParameterised () const
EVolume VolumeType () const final
G4VPVParameterisation * GetParameterisation () const
void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const
virtual void SetRegularStructureId (G4int code)
G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int maxErr=1)
Public Member Functions inherited from G4PVReplica
G4PVReplica (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset=0.)
G4PVReplica (const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset=0.)
G4PVReplica (__void__ &)
G4PVReplica (const G4PVReplica &)=delete
G4PVReplica & operator= (const G4PVReplica &)=delete
virtual ~G4PVReplica ()
G4bool IsMany () const
G4bool IsReplicated () const
virtual G4int GetCopyNo () const
virtual void SetCopyNo (G4int CopyNo)
virtual G4int GetMultiplicity () const
G4bool IsRegularStructure () const
G4int GetRegularStructureId () const
G4int GetInstanceID () const
void InitialiseWorker (G4PVReplica *pMasterObject)
void TerminateWorker (G4PVReplica *pMasterObject)
Public Member Functions inherited from G4VPhysicalVolume
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4VPhysicalVolume (const G4VPhysicalVolume &)=delete
G4VPhysicalVolume & operator= (const G4VPhysicalVolume &)=delete
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
EVolume DeduceVolumeType () const
Private Attributes
G4VPVParameterisation * fparam = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4PVReplica
static const G4PVRManager & GetSubInstanceManager ()
Protected Member Functions inherited from G4PVReplica
G4PVReplica (const G4String &pName, G4int nReplicas, EAxis pAxis, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical)
Protected Attributes inherited from G4PVReplica
EAxis faxis
G4int fnReplicas
G4double fwidth
G4double foffset
Static Protected Attributes inherited from G4VPhysicalVolume
static G4GEOM_DLL G4PVManager subInstanceManager
Detailed Description
Definition at line 42 of file G4PVParameterised.hh.
View newest version in sPHENIX GitHub at line 42 of file G4PVParameterised.hh
Constructor & Destructor Documentation
G4PVParameterised::G4PVParameterised (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const EAxis pAxis, const G4int nReplicas, G4VPVParameterisation * pParam, G4bool pSurfChk = false)
Definition at line 84 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 84 of file G4PVParameterised.cc
References G4LogicalVolume::AddDaughter(), CheckOverlaps(), and G4VPhysicalVolume::SetMotherLogical().
G4PVParameterised::G4PVParameterised (const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother, const EAxis pAxis, const G4int nReplicas, G4VPVParameterisation * pParam, G4bool pSurfChk = false)
Definition at line 41 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 41 of file G4PVParameterised.cc
References G4LogicalVolume::AddDaughter(), CheckOverlaps(), G4endl, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::IsParameterised(), JustWarning, message(), and G4VPhysicalVolume::SetMotherLogical().
G4PVParameterised::G4PVParameterised (__void__ & a)
Definition at line 107 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 107 of file G4PVParameterised.cc
G4PVParameterised::~G4PVParameterised () virtual
Definition at line 115 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 115 of file G4PVParameterised.cc
Member Function Documentation
G4bool G4PVParameterised::CheckOverlaps (G4int res = 1000, G4double tol = 0., G4bool verbose = true, G4int maxErr = 1) virtual
Reimplemented from G4VPhysicalVolume.
Definition at line 174 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 174 of file G4PVParameterised.cc
References G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), G4VSolid::DistanceToIn(), fparam, G4BestUnit, G4cout, G4endl, G4Exception(), G4VPhysicalVolume::GetMotherLogical(), G4PVReplica::GetMultiplicity(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4VSolid::GetPointOnSurface(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4VPhysicalVolume::GetTranslation(), G4VSolid::Inside(), G4AffineTransform::InverseTransformPoint(), JustWarning, kInside, kOutside, message(), n, pos(), and G4AffineTransform::TransformPoint().
Referenced by G4PVParameterised().
G4VPVParameterisation * G4PVParameterised::GetParameterisation () const virtual
Reimplemented from G4PVReplica.
Definition at line 122 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 122 of file G4PVParameterised.cc
References fparam.
Referenced by G4VFieldModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), G4tgbGeometryDumper::DumpPVParameterised(), DicomIntersectVolume::GetPhantomParam(), and G4EnergySplitter::GetPhantomParam().
void G4PVParameterised::GetReplicationData (EAxis & axis, G4int & nReplicas, G4double & width, G4double & offset, G4bool & consuming) const virtual
Reimplemented from G4PVReplica.
Definition at line 146 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 146 of file G4PVParameterised.cc
References G4PVReplica::faxis, G4PVReplica::fnReplicas, G4PVReplica::foffset, and G4PVReplica::fwidth.
Referenced by G4tgbGeometryDumper::DumpPVParameterised().
G4bool G4PVParameterised::IsParameterised () const virtual
Reimplemented from G4PVReplica.
Definition at line 130 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 130 of file G4PVParameterised.cc
void G4PVParameterised::SetRegularStructureId (G4int code) virtual
Reimplemented from G4PVReplica.
Definition at line 162 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 162 of file G4PVParameterised.cc
References G4PVReplica::SetRegularStructureId().
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
EVolume G4PVParameterised::VolumeType () const final virtual
Reimplemented from G4PVReplica.
Definition at line 138 of file G4PVParameterised.cc.
View newest version in sPHENIX GitHub at line 138 of file G4PVParameterised.cc
References kParameterised.
Member Data Documentation
G4VPVParameterisation* G4PVParameterised::fparam = nullptr private
Definition at line 110 of file G4PVParameterised.hh.
View newest version in sPHENIX GitHub at line 110 of file G4PVParameterised.hh
Referenced by CheckOverlaps(), and GetParameterisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4PVParameterised.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4PVParameterised.cc