ECCE @ EIC Software: CLHEP::RanecuEngine Class Reference
CLHEP::RanecuEngine Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RanecuEngine.h>
Public Member Functions
RanecuEngine (std::istream &is)
RanecuEngine ()
RanecuEngine (int index)
virtual ~RanecuEngine ()
double flat ()
void flatArray (const int size, double *vect)
void setIndex (long index)
void setSeed (long index, int dum=0)
void setSeeds (const long *seeds, int index=-1)
void saveStatus (const char filename[]="Ranecu.conf") const
void restoreStatus (const char filename[]="Ranecu.conf")
void showStatus () const
operator double ()
operator float ()
operator unsigned int ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Protected Attributes
static const int ecuyer_a = 40014
static const int ecuyer_b = 53668
static const int ecuyer_c = 12211
static const int ecuyer_d = 40692
static const int ecuyer_e = 52774
static const int ecuyer_f = 3791
static const int shift1 = 2147483563
static const int shift2 = 2147483399
static const unsigned int VECTOR_STATE_SIZE = 4
Private Member Functions
void further_randomize (int seq, int col, int index, int modulus)
Private Attributes
long table [215][2]
int seq
Static Private Attributes
static const int maxSeq = 215
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Gabri.nosp@m.ele..nosp@m.Cosmo.nosp@m.@cer.nosp@m.n.ch
Definition at line 46 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 46 of file RanecuEngine.h
Constructor & Destructor Documentation
CLHEP::RanecuEngine::RanecuEngine (std::istream & is)
Definition at line 101 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 101 of file RanecuEngine.cc
CLHEP::RanecuEngine::RanecuEngine ()
Definition at line 67 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 67 of file RanecuEngine.cc
References kdfinder::abs(), CLHEP::HepRandom::getTheTableSeeds(), mask, maxSeq, seq, table, CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
CLHEP::RanecuEngine::RanecuEngine (int index)
Definition at line 85 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 85 of file RanecuEngine.cc
References kdfinder::abs(), further_randomize(), CLHEP::HepRandom::getTheTableSeeds(), mask, maxSeq, seq, shift1, table, CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
CLHEP::RanecuEngine::~RanecuEngine () virtual
Definition at line 107 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 107 of file RanecuEngine.cc
Member Function Documentation
std::string CLHEP::RanecuEngine::beginTag () static
Definition at line 313 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 313 of file RanecuEngine.cc
static std::string CLHEP::RanecuEngine::engineName () inline static
Definition at line 99 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 99 of file RanecuEngine.h
Referenced by restoreStatus().
double CLHEP::RanecuEngine::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 195 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 195 of file RanecuEngine.cc
References ecuyer_a, ecuyer_b, ecuyer_c, ecuyer_d, ecuyer_e, ecuyer_f, int(), k1, k2, CLHEP::prec, seq, shift1, shift2, and table.
void CLHEP::RanecuEngine::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 218 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 218 of file RanecuEngine.cc
References ecuyer_a, ecuyer_b, ecuyer_c, ecuyer_d, ecuyer_e, ecuyer_f, int(), k1, k2, CLHEP::prec, seq, shift1, shift2, and table.
void CLHEP::RanecuEngine::further_randomize (int seq, int col, int index, int modulus) private
Definition at line 61 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 61 of file RanecuEngine.cc
References col, and table.
Referenced by RanecuEngine(), and setSeed().
std::istream & CLHEP::RanecuEngine::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 294 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 294 of file RanecuEngine.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::RanecuEngine::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 356 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 356 of file RanecuEngine.cc
References getState().
std::istream & CLHEP::RanecuEngine::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 317 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 317 of file RanecuEngine.cc
References int(), CLHEP::MarkerLen, CLHEP::possibleKeywordInput(), seq, table, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
Referenced by get(), and restoreStatus().
bool CLHEP::RanecuEngine::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 365 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 365 of file RanecuEngine.cc
References int(), seq, table, CLHEP::HepRandomEngine::theSeed, and VECTOR_STATE_SIZE.
std::string CLHEP::RanecuEngine::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 59 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 59 of file RanecuEngine.cc
CLHEP::RanecuEngine::operator double () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 245 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 245 of file RanecuEngine.cc
References G4AblaRandom::flat().
CLHEP::RanecuEngine::operator float () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 249 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 249 of file RanecuEngine.cc
References G4AblaRandom::flat().
CLHEP::RanecuEngine::operator unsigned int () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 253 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 253 of file RanecuEngine.cc
References int(), k1, and k2.
std::ostream & CLHEP::RanecuEngine::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 274 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 274 of file RanecuEngine.cc
References put(), and v.
std::vector< unsigned long > CLHEP::RanecuEngine::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 285 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 285 of file RanecuEngine.cc
References table, CLHEP::HepRandomEngine::theSeed, and v.
Referenced by put(), and saveStatus().
void CLHEP::RanecuEngine::restoreStatus (const char filename[] = "Ranecu.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 151 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 151 of file RanecuEngine.cc
References CLHEP::HepRandomEngine::checkFile(), engineName(), getState(), in, int(), CLHEP::possibleKeywordInput(), seq, table, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
void CLHEP::RanecuEngine::saveStatus (const char filename[] = "Ranecu.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 138 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 138 of file RanecuEngine.cc
References put(), and v.
void CLHEP::RanecuEngine::setIndex (long index)
Definition at line 131 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 131 of file RanecuEngine.cc
References kdfinder::abs(), maxSeq, seq, table, CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
void CLHEP::RanecuEngine::setSeed (long index, int dum = 0) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 109 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 109 of file RanecuEngine.cc
References kdfinder::abs(), further_randomize(), CLHEP::HepRandom::getTheTableSeeds(), maxSeq, seq, shift1, shift2, table, CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
void CLHEP::RanecuEngine::setSeeds (const long * seeds, int index = -1) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 119 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 119 of file RanecuEngine.cc
References kdfinder::abs(), maxSeq, seq, shift1, shift2, table, CLHEP::HepRandomEngine::theSeed, and CLHEP::HepRandomEngine::theSeeds.
void CLHEP::RanecuEngine::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 184 of file RanecuEngine.cc.
View newest version in sPHENIX GitHub at line 184 of file RanecuEngine.cc
References table, and CLHEP::HepRandomEngine::theSeed.
Member Data Documentation
const int CLHEP::RanecuEngine::ecuyer_a = 40014 static protected
Definition at line 109 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 109 of file RanecuEngine.h
Referenced by flat(), and flatArray().
const int CLHEP::RanecuEngine::ecuyer_b = 53668 static protected
Definition at line 110 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 110 of file RanecuEngine.h
Referenced by flat(), and flatArray().
const int CLHEP::RanecuEngine::ecuyer_c = 12211 static protected
Definition at line 111 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 111 of file RanecuEngine.h
Referenced by flat(), and flatArray().
const int CLHEP::RanecuEngine::ecuyer_d = 40692 static protected
Definition at line 112 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 112 of file RanecuEngine.h
Referenced by flat(), and flatArray().
const int CLHEP::RanecuEngine::ecuyer_e = 52774 static protected
Definition at line 113 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 113 of file RanecuEngine.h
Referenced by flat(), and flatArray().
const int CLHEP::RanecuEngine::ecuyer_f = 3791 static protected
Definition at line 114 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 114 of file RanecuEngine.h
Referenced by flat(), and flatArray().
const int CLHEP::RanecuEngine::maxSeq = 215 static private
Definition at line 127 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 127 of file RanecuEngine.h
Referenced by RanecuEngine(), setIndex(), setSeed(), and setSeeds().
int CLHEP::RanecuEngine::seq private
Definition at line 129 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 129 of file RanecuEngine.h
Referenced by flat(), flatArray(), getState(), RanecuEngine(), restoreStatus(), setIndex(), setSeed(), and setSeeds().
const int CLHEP::RanecuEngine::shift1 = 2147483563 static protected
Definition at line 115 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 115 of file RanecuEngine.h
Referenced by flat(), flatArray(), RanecuEngine(), setSeed(), and setSeeds().
const int CLHEP::RanecuEngine::shift2 = 2147483399 static protected
Definition at line 116 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 116 of file RanecuEngine.h
Referenced by flat(), flatArray(), setSeed(), and setSeeds().
long CLHEP::RanecuEngine::table[215][2] private
Definition at line 128 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 128 of file RanecuEngine.h
Referenced by flat(), flatArray(), further_randomize(), getState(), put(), RanecuEngine(), restoreStatus(), setIndex(), setSeed(), setSeeds(), and showStatus().
const unsigned int CLHEP::RanecuEngine::VECTOR_STATE_SIZE = 4 static protected
Definition at line 118 of file RanecuEngine.h.
View newest version in sPHENIX GitHub at line 118 of file RanecuEngine.h
Referenced by getState(), and restoreStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RanecuEngine.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RanecuEngine.cc