ECCE @ EIC Software: ExP01MagneticField Class Reference
ExP01MagneticField Class Reference
Magnetic field for the persistency example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/ExP01MagneticField.hh>
Public Member Functions
ExP01MagneticField (G4ThreeVector)
ExP01MagneticField ()
~ExP01MagneticField ()
void SetFieldValue (G4double fieldValue)
void SetFieldValue (G4ThreeVector fieldVector)
G4ThreeVector GetConstantFieldValue ()
Public Member Functions inherited from G4UniformMagField
G4UniformMagField (const G4ThreeVector &FieldVector)
G4UniformMagField (G4double vField, G4double vTheta, G4double vPhi)
virtual ~G4UniformMagField () override
G4UniformMagField (const G4UniformMagField &p)
G4UniformMagField & operator= (const G4UniformMagField &p)
virtual void GetFieldValue (const G4double yTrack[4], G4double *MagField) const overridefinal
void SetFieldValue (const G4ThreeVector &newFieldValue)
G4ThreeVector GetConstantFieldValue () const
virtual G4Field * Clone () const override
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Magnetic field for the persistency example.
Definition at line 49 of file ExP01MagneticField.hh.
View newest version in sPHENIX GitHub at line 49 of file ExP01MagneticField.hh
Constructor & Destructor Documentation
ExP01MagneticField::ExP01MagneticField (G4ThreeVector fieldVector)
Definition at line 50 of file ExP01MagneticField.cc.
View newest version in sPHENIX GitHub at line 50 of file ExP01MagneticField.cc
References G4FieldManager::CreateChordFinder(), GetGlobalFieldManager(), and G4FieldManager::SetDetectorField().
ExP01MagneticField::ExP01MagneticField ()
Definition at line 41 of file ExP01MagneticField.cc.
View newest version in sPHENIX GitHub at line 41 of file ExP01MagneticField.cc
References G4FieldManager::CreateChordFinder(), GetGlobalFieldManager(), and G4FieldManager::SetDetectorField().
ExP01MagneticField::~ExP01MagneticField ()
Definition at line 89 of file ExP01MagneticField.cc.
View newest version in sPHENIX GitHub at line 89 of file ExP01MagneticField.cc
Member Function Documentation
G4ThreeVector ExP01MagneticField::GetConstantFieldValue ()
G4FieldManager * ExP01MagneticField::GetGlobalFieldManager () protected
Definition at line 98 of file ExP01MagneticField.cc.
View newest version in sPHENIX GitHub at line 98 of file ExP01MagneticField.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by ExP01MagneticField(), and SetFieldValue().
void ExP01MagneticField::SetFieldValue (G4double fieldValue)
Definition at line 61 of file ExP01MagneticField.cc.
View newest version in sPHENIX GitHub at line 61 of file ExP01MagneticField.cc
References G4UniformMagField::SetFieldValue().
Referenced by ExP01DetectorConstruction::SetMagField().
void ExP01MagneticField::SetFieldValue (G4ThreeVector fieldVector)
Definition at line 70 of file ExP01MagneticField.cc.
View newest version in sPHENIX GitHub at line 70 of file ExP01MagneticField.cc
References GetGlobalFieldManager(), G4FieldManager::SetDetectorField(), and G4UniformMagField::SetFieldValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/ExP01MagneticField.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/src/ExP01MagneticField.cc