ECCE @ EIC Software: G4ParticleHPCaptureFS Class Reference
G4ParticleHPCaptureFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPCaptureFS.hh>
Public Member Functions
G4ParticleHPCaptureFS ()
~G4ParticleHPCaptureFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aFSType, G4ParticleDefinition *)
G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)
G4ParticleHPFinalState * New ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
virtual G4double GetXsec (G4double)
virtual G4ParticleHPVector * GetXsec ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Attributes
G4double targetMass
G4ParticleHPPhotonDist theFinalStatePhotons
G4ParticleHPEnAngCorrelation theMF6FinalState
G4bool hasExactMF6
G4ParticleHPNames theNames
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 42 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPCaptureFS.hh
Constructor & Destructor Documentation
G4ParticleHPCaptureFS::G4ParticleHPCaptureFS () inline
Definition at line 46 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPCaptureFS.hh
References hasExactMF6, G4ParticleHPFinalState::hasXsec, and targetMass.
Referenced by New().
G4ParticleHPCaptureFS::~G4ParticleHPCaptureFS () inline
Definition at line 53 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPCaptureFS.hh
Member Function Documentation
G4HadFinalState * G4ParticleHPCaptureFS::ApplyYourself (const G4HadProjectile & theTrack) virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 50 of file G4ParticleHPCaptureFS.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPCaptureFS.cc
References G4HadFinalState::AddSecondary(), G4PhotonEvaporation::BreakItUp(), G4HadFinalState::Clear(), G4ParticleHPFinalState::DoNotAdjustFinalState(), CLHEP::HepLorentzVector::e(), eps, eV, G4UniformRand, G4Gamma::Gamma(), G4Cache< VALTYPE >::Get(), G4HadProjectile::Get4Momentum(), G4DynamicParticle::Get4Momentum(), G4Nucleus::GetBiasedThermalNucleus(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4ParticleHPManager::GetInstance(), G4IonTable::GetIon(), G4IonTable::GetIonMass(), G4IonTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4ParticleDefinition::GetPDGMass(), G4ParticleHPPhotonDist::GetPhotons(), G4HadFinalState::GetSecondary(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalEnergy(), hasExactMF6, G4ParticleHPFinalState::HasFSData(), it, G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag(), MeV, G4Neutron::Neutron(), phi, G4Cache< VALTYPE >::Put(), Q, G4ParticleHPEnAngCorrelation::Sample(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ReactionProduct::SetDefinitionAndUpdateE(), G4PhotonEvaporation::SetICM(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4ParticleHPEnAngCorrelation::SetProjectileRP(), G4HadFinalState::SetStatusChange(), G4ParticleHPEnAngCorrelation::SetTarget(), stopAndKill, targetMass, G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theFinalStatePhotons, theMF6FinalState, G4ParticleHPFinalState::theResult, theta(), theTarget, TRUE, twopi, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
void G4ParticleHPCaptureFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aFSType, G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Definition at line 312 of file G4ParticleHPCaptureFS.cc.
View newest version in sPHENIX GitHub at line 312 of file G4ParticleHPCaptureFS.cc
References A(), kdfinder::abs(), INPUTHEPMC::filename, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPPhotonDist::GetTargetMass(), G4ParticleHPFinalState::hasAnyData, hasExactMF6, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPEnAngCorrelation::Init(), G4ParticleHPPhotonDist::InitAngular(), G4ParticleHPPhotonDist::InitEnergies(), G4ParticleHPPhotonDist::InitMean(), G4ParticleHPFinalState::SetAZMs(), targetMass, G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theFinalStatePhotons, theMF6FinalState, theNames, true, and Z.
G4ParticleHPFinalState* G4ParticleHPCaptureFS::New () inline virtual
Implements G4ParticleHPFinalState.
Definition at line 59 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleHPCaptureFS.hh
References G4ParticleHPCaptureFS().
Member Data Documentation
G4bool G4ParticleHPCaptureFS::hasExactMF6 private
Definition at line 72 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPCaptureFS.hh
Referenced by ApplyYourself(), G4ParticleHPCaptureFS(), and Init().
G4double G4ParticleHPCaptureFS::targetMass private
Definition at line 67 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ParticleHPCaptureFS.hh
Referenced by ApplyYourself(), G4ParticleHPCaptureFS(), and Init().
G4ParticleHPPhotonDist G4ParticleHPCaptureFS::theFinalStatePhotons private
Definition at line 69 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPCaptureFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPEnAngCorrelation G4ParticleHPCaptureFS::theMF6FinalState private
Definition at line 71 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPCaptureFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPNames G4ParticleHPCaptureFS::theNames private
Definition at line 74 of file G4ParticleHPCaptureFS.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleHPCaptureFS.hh
Referenced by Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPCaptureFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPCaptureFS.cc