ECCE @ EIC Software: G4MapCache< KEYTYPE, VALTYPE > Class Template Reference
G4MapCache< KEYTYPE, VALTYPE > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4Cache.hh>
Public Types
typedef KEYTYPE key_type
typedef VALTYPE value_type
typedef std::map< key_type,
value_type > map_type
typedef map_type::size_type size_type
typedef map_type::iterator iterator
typedef map_type::const_iterator const_iterator
Public Types inherited from G4Cache< std::map< KEYTYPE, VALTYPE > >
typedef std::map< KEYTYPE,
VALTYPE > value_type
Public Member Functions
virtual ~G4MapCache ()
G4bool Has (const key_type &k)
std::pair< iterator, G4bool > Insert (const key_type &k, const value_type &v)
iterator Begin ()
iterator End ()
iterator Find (const key_type &k)
value_type & Get (const key_type &k)
size_type Erase (const key_type &k)
value_type & operator[] (const key_type &k)
size_type Size ()
Public Member Functions inherited from G4Cache< std::map< KEYTYPE, VALTYPE > >
G4Cache ()
G4Cache (const value_type &v)
G4Cache (const G4Cache &rhs)
virtual ~G4Cache ()
value_type & Get () const
void Put (const value_type &val) const
value_type Pop ()
G4Cache & operator= (const G4Cache &rhs)
Additional Inherited Members
Protected Member Functions inherited from G4Cache< std::map< KEYTYPE, VALTYPE > >
const G4int & GetId () const
Detailed Description
template<class KEYTYPE, class VALTYPE>
class G4MapCache< KEYTYPE, VALTYPE >
Definition at line 184 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Cache.hh
Member Typedef Documentation
template<class KEYTYPE, class VALTYPE> typedef map_type::const_iterator G4MapCache< KEYTYPE, VALTYPE >::const_iterator
Definition at line 195 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 195 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> typedef map_type::iterator G4MapCache< KEYTYPE, VALTYPE >::iterator
Definition at line 194 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 194 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> typedef KEYTYPE G4MapCache< KEYTYPE, VALTYPE >::key_type
Definition at line 190 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 190 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> typedef std::map<key_type,value_type> G4MapCache< KEYTYPE, VALTYPE >::map_type
Definition at line 192 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 192 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> typedef map_type::size_type G4MapCache< KEYTYPE, VALTYPE >::size_type
Definition at line 193 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 193 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> typedef VALTYPE G4MapCache< KEYTYPE, VALTYPE >::value_type
Definition at line 191 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 191 of file G4Cache.hh
Constructor & Destructor Documentation
template<class K , class V > G4MapCache< K, V >::~G4MapCache () virtual
Definition at line 428 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 428 of file G4Cache.hh
References G4Cache< VALTYPE >::GetId(), and it.
Member Function Documentation
template<class K , class V > G4MapCache< K, V >::iterator G4MapCache< K, V >::Begin () inline
Definition at line 453 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 453 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class K , class V > G4MapCache< K, V >::iterator G4MapCache< K, V >::End () inline
Definition at line 458 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 458 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
Referenced by G4VBiasingOperator::AttachTo(), and G4VBiasingOperator::GetBiasingOperator().
template<class KEYTYPE, class VALTYPE> G4MapCache< K, V >::size_type G4MapCache< K, V >::Erase (const key_type & k) inline
Definition at line 482 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 482 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class KEYTYPE, class VALTYPE> G4MapCache< K, V >::iterator G4MapCache< K, V >::Find (const key_type & k) inline
Definition at line 464 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 464 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
Referenced by G4VBiasingOperator::AttachTo(), G4VBiasingOperator::GetBiasingOperator(), and G4BiasingProcessInterface::GetSharedData().
template<class KEYTYPE, class VALTYPE> V & G4MapCache< K, V >::Get (const key_type & k) inline
Definition at line 476 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 476 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> G4bool G4MapCache< K, V >::Has (const key_type & k) inline
Definition at line 470 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 470 of file G4Cache.hh
template<class KEYTYPE, class VALTYPE> std::pair< typename G4MapCache< K, V >::iterator, G4bool > G4MapCache< K, V >::Insert (const key_type & k, const value_type & v) inline
Definition at line 441 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 441 of file G4Cache.hh
References G4Cache< VALTYPE >::Get().
template<class KEYTYPE, class VALTYPE> V & G4MapCache< K, V >::operator[] (const key_type & k) inline
Definition at line 488 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 488 of file G4Cache.hh
References k.
template<class KEYTYPE, class VALTYPE> size_type G4MapCache< KEYTYPE, VALTYPE >::Size () inline
Definition at line 213 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Cache.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4Cache.hh