ECCE @ EIC Software: CLHEP::RandExponential Class Reference
CLHEP::RandExponential Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandExponential.h>
Public Member Functions
RandExponential (HepRandomEngine &anEngine, double mean=1.0)
RandExponential (HepRandomEngine *anEngine, double mean=1.0)
virtual ~RandExponential ()
double fire ()
double fire (double mean)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double mean)
double operator() ()
double operator() (double mean)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double mean)
static void shootArray (const int size, double *vect, double mean=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double mean)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double mean=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double defaultMean
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Gabri.nosp@m.ele..nosp@m.Cosmo.nosp@m.@cer.nosp@m.n.ch
Definition at line 34 of file RandExponential.h.
View newest version in sPHENIX GitHub at line 34 of file RandExponential.h
Constructor & Destructor Documentation
CLHEP::RandExponential::RandExponential (HepRandomEngine & anEngine, double mean = 1.0) inline
CLHEP::RandExponential::RandExponential (HepRandomEngine * anEngine, double mean = 1.0) inline
CLHEP::RandExponential::~RandExponential () virtual
Definition at line 29 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 29 of file RandExponential.cc
Member Function Documentation
static std::string CLHEP::RandExponential::distributionName () inline static
Definition at line 92 of file RandExponential.h.
View newest version in sPHENIX GitHub at line 92 of file RandExponential.h
HepRandomEngine & CLHEP::RandExponential::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 27 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 27 of file RandExponential.cc
References localEngine.
double CLHEP::RandExponential::fire () inline
Referenced by fireArray(), and operator()().
double CLHEP::RandExponential::fire (double mean) inline
void CLHEP::RandExponential::fireArray (const int size, double * vect)
Definition at line 62 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 62 of file RandExponential.cc
References defaultMean, fire(), and v.
void CLHEP::RandExponential::fireArray (const int size, double * vect, double mean)
Definition at line 68 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 68 of file RandExponential.cc
References fire(), and v.
std::istream & CLHEP::RandExponential::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 86 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 86 of file RandExponential.cc
References defaultMean, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandExponential::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 26 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 26 of file RandExponential.cc
Referenced by get(), and put().
double CLHEP::RandExponential::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 32 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 32 of file RandExponential.cc
References defaultMean, and fire().
double CLHEP::RandExponential::operator() (double mean)
Definition at line 36 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 36 of file RandExponential.cc
References fire().
std::ostream & CLHEP::RandExponential::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 75 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 75 of file RandExponential.cc
References defaultMean, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
double CLHEP::RandExponential::shoot () static
Definition at line 40 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 40 of file RandExponential.cc
References CLHEP::HepRandom::flat(), and CLHEP::HepRandom::getTheEngine().
Referenced by shootArray().
double CLHEP::RandExponential::shoot (double mean) static
Definition at line 44 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 44 of file RandExponential.cc
References CLHEP::HepRandom::flat(), and CLHEP::HepRandom::getTheEngine().
static double CLHEP::RandExponential::shoot (HepRandomEngine * anEngine) inline static
static double CLHEP::RandExponential::shoot (HepRandomEngine * anEngine, double mean) inline static
void CLHEP::RandExponential::shootArray (const int size, double * vect, double mean = 1.0) static
Definition at line 48 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 48 of file RandExponential.cc
References shoot(), and v.
void CLHEP::RandExponential::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double mean = 1.0) static
Definition at line 55 of file RandExponential.cc.
View newest version in sPHENIX GitHub at line 55 of file RandExponential.cc
References shoot(), and v.
Member Data Documentation
double CLHEP::RandExponential::defaultMean private
Definition at line 98 of file RandExponential.h.
View newest version in sPHENIX GitHub at line 98 of file RandExponential.h
Referenced by fireArray(), get(), operator()(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandExponential::localEngine private
Definition at line 97 of file RandExponential.h.
View newest version in sPHENIX GitHub at line 97 of file RandExponential.h
Referenced by engine().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandExponential.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandExponential.cc