ECCE @ EIC Software: G4ParticleHPThreadLocalManager Class Reference
G4ParticleHPThreadLocalManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPThreadLocalManager.hh>
Public Member Functions
G4ParticleHPReactionWhiteBoard * GetReactionWhiteBoard ()
void OpenReactionWhiteBoard ()
void CloseReactionWhiteBoard ()
Static Public Member Functions
static
G4ParticleHPThreadLocalManager * GetInstance ()
Private Member Functions
G4ParticleHPThreadLocalManager ()
G4ParticleHPThreadLocalManager (const G4ParticleHPThreadLocalManager &)
~G4ParticleHPThreadLocalManager ()
Private Attributes
G4ParticleHPReactionWhiteBoard * RWB
Friends
class G4ThreadLocalSingleton< G4ParticleHPThreadLocalManager >
Detailed Description
Definition at line 40 of file G4ParticleHPThreadLocalManager.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPThreadLocalManager.hh
Constructor & Destructor Documentation
G4ParticleHPThreadLocalManager::G4ParticleHPThreadLocalManager () private
Definition at line 35 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPThreadLocalManager.cc
G4ParticleHPThreadLocalManager::G4ParticleHPThreadLocalManager (const G4ParticleHPThreadLocalManager &) private
Definition at line 47 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPThreadLocalManager.cc
G4ParticleHPThreadLocalManager::~G4ParticleHPThreadLocalManager () private
Definition at line 41 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPThreadLocalManager.cc
Member Function Documentation
void G4ParticleHPThreadLocalManager::CloseReactionWhiteBoard ()
Definition at line 80 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPThreadLocalManager.cc
References RWB.
Referenced by G4ParticleHPManager::CloseReactionWhiteBoard().
G4ParticleHPThreadLocalManager * G4ParticleHPThreadLocalManager::GetInstance (void) static
Definition at line 52 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPThreadLocalManager.cc
References instance, and G4ThreadLocalSingleton< T >::Instance().
Referenced by G4ParticleHPManager::CloseReactionWhiteBoard(), G4ParticleHPManager::GetReactionWhiteBoard(), and G4ParticleHPManager::OpenReactionWhiteBoard().
G4ParticleHPReactionWhiteBoard * G4ParticleHPThreadLocalManager::GetReactionWhiteBoard ()
Definition at line 70 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPThreadLocalManager.cc
References G4cout, G4endl, and RWB.
Referenced by G4ParticleHPManager::GetReactionWhiteBoard().
void G4ParticleHPThreadLocalManager::OpenReactionWhiteBoard ()
Definition at line 58 of file G4ParticleHPThreadLocalManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPThreadLocalManager.cc
References G4cout, G4endl, and RWB.
Referenced by G4ParticleHPManager::OpenReactionWhiteBoard().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4ParticleHPThreadLocalManager > friend
Definition at line 42 of file G4ParticleHPThreadLocalManager.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPThreadLocalManager.hh
Member Data Documentation
G4ParticleHPReactionWhiteBoard* G4ParticleHPThreadLocalManager::RWB private
Definition at line 56 of file G4ParticleHPThreadLocalManager.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPThreadLocalManager.hh
Referenced by CloseReactionWhiteBoard(), GetReactionWhiteBoard(), and OpenReactionWhiteBoard().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPThreadLocalManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPThreadLocalManager.cc