ECCE @ EIC Software: G4PenelopeIonisationModel Class Reference
G4PenelopeIonisationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeIonisationModel.hh>
Public Member Functions
G4PenelopeIonisationModel (const G4ParticleDefinition *p=0, const G4String &processName="PenIoni")
virtual ~G4PenelopeIonisationModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double, G4double, G4double, G4double, G4double)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *theParticle, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
void SetVerbosityLevel (G4int lev)
G4int GetVerbosityLevel ()
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForLoss * fParticleChange
const G4ParticleDefinition * fParticle
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4PenelopeIonisationModel & operator= (const G4PenelopeIonisationModel &right)
G4PenelopeIonisationModel (const G4PenelopeIonisationModel &)
void SetParticle (const G4ParticleDefinition *)
void SampleFinalStateElectron (const G4Material *, G4double cutEnergy, G4double kineticEnergy)
void SampleFinalStatePositron (const G4Material *, G4double cutEnergy, G4double kineticEnergy)
Private Attributes
G4double fIntrinsicLowEnergyLimit
G4double fIntrinsicHighEnergyLimit
G4int verboseLevel
G4bool isInitialised
G4VAtomDeexcitation * fAtomDeexcitation
G4bool fPIXEflag
G4double kineticEnergy1
G4double cosThetaPrimary
G4double energySecondary
G4double cosThetaSecondary
G4int targetOscillator
G4PenelopeOscillatorManager * oscManager
G4PenelopeIonisationXSHandler * theCrossSectionHandler
size_t nBins
G4bool fLocalTable
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 65 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PenelopeIonisationModel.hh
Constructor & Destructor Documentation
G4PenelopeIonisationModel::G4PenelopeIonisationModel (const G4ParticleDefinition * p = 0, const G4String & processName = "PenIoni")
Definition at line 73 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 73 of file G4PenelopeIonisationModel.cc
References eV, fIntrinsicHighEnergyLimit, fIntrinsicLowEnergyLimit, G4PenelopeOscillatorManager::GetOscillatorManager(), GeV, nBins, oscManager, G4VEmModel::SetDeexcitationFlag(), G4VEmModel::SetHighEnergyLimit(), SetParticle(), and verboseLevel.
G4PenelopeIonisationModel::~G4PenelopeIonisationModel () virtual
Definition at line 108 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 108 of file G4PenelopeIonisationModel.cc
References fLocalTable, G4VEmModel::IsMaster(), and theCrossSectionHandler.
G4PenelopeIonisationModel::G4PenelopeIonisationModel (const G4PenelopeIonisationModel &) private
Member Function Documentation
G4double G4PenelopeIonisationModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double , G4double , G4double , G4double , G4double) virtual
Reimplemented from G4VEmModel.
Definition at line 356 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 356 of file G4PenelopeIonisationModel.cc
References G4cout, and G4endl.
G4double G4PenelopeIonisationModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * theParticle, G4double kineticEnergy, G4double cutEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 372 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 372 of file G4PenelopeIonisationModel.cc
References G4PenelopeIonisationXSHandler::BuildXSTable(), fLocalTable, G4cout, G4endl, G4Exception(), G4PenelopeOscillatorManager::GetAtomsPerMolecule(), G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4PenelopeCrossSection::GetSoftStoppingPower(), G4Material::GetTotNbOfAtomsPerVolume(), JustWarning, keV, mm, nBins, oscManager, theCrossSectionHandler, G4TemplateAutoLock< _Mutex_t >::unlock(), and verboseLevel.
G4double G4PenelopeIonisationModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * theParticle, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 251 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 251 of file G4PenelopeIonisationModel.cc
References G4PenelopeIonisationXSHandler::BuildXSTable(), fLocalTable, G4cout, G4endl, G4Exception(), G4PenelopeOscillatorManager::GetAtomsPerMolecule(), G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4PenelopeCrossSection::GetHardCrossSection(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4PenelopeCrossSection::GetTotalCrossSection(), G4Material::GetTotNbOfAtomsPerVolume(), JustWarning, keV, mm, nBins, oscManager, G4VEmModel::SetupForMaterial(), theCrossSectionHandler, G4TemplateAutoLock< _Mutex_t >::unlock(), and verboseLevel.
G4int G4PenelopeIonisationModel::GetVerbosityLevel () inline
Definition at line 112 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PenelopeIonisationModel.hh
References verboseLevel.
void G4PenelopeIonisationModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector & theCuts) virtual
Implements G4VEmModel.
Definition at line 119 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 119 of file G4PenelopeIonisationModel.cc
References G4LossTableManager::AtomDeexcitation(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4Electron::Electron(), fAtomDeexcitation, fParticle, fParticleChange, fPIXEflag, G4cout, G4endl, G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4VEmModel::GetParticleChangeForLoss(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), GeV, G4VEmModel::HighEnergyLimit(), G4EmParameters::Instance(), G4LossTableManager::Instance(), isInitialised, G4VEmModel::IsMaster(), G4VAtomDeexcitation::IsPIXEActive(), keV, G4VEmModel::LowEnergyLimit(), max, nBins, particle, G4EmParameters::PIXEElectronCrossSectionModel(), SetParticle(), G4PenelopeIonisationXSHandler::SetVerboseLevel(), theCrossSectionHandler, and verboseLevel.
void G4PenelopeIonisationModel::InitialiseLocal (const G4ParticleDefinition * part, G4VEmModel * masterModel) virtual
Reimplemented from G4VEmModel.
Definition at line 219 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 219 of file G4PenelopeIonisationModel.cc
References fParticle, G4cout, G4endl, nBins, theCrossSectionHandler, and verboseLevel.
G4double G4PenelopeIonisationModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple *) virtual
Reimplemented from G4VEmModel.
Definition at line 460 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 460 of file G4PenelopeIonisationModel.cc
References fIntrinsicLowEnergyLimit.
G4PenelopeIonisationModel& G4PenelopeIonisationModel::operator= (const G4PenelopeIonisationModel & right) private
void G4PenelopeIonisationModel::SampleFinalStateElectron (const G4Material * mat, G4double cutEnergy, G4double kineticEnergy) private
Definition at line 718 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 718 of file G4PenelopeIonisationModel.cc
References A(), barn, cosThetaPrimary, cosThetaSecondary, cp, Acts::Test::delta, e, G4Electron::Electron(), source.hepunit::electron_mass_c2, energySecondary, eV, fb(), G4cout, G4endl, G4UniformRand, G4InuclParticleNames::gam, G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4PenelopeIonisationXSHandler::GetDensityCorrection(), G4PenelopeCrossSection::GetNormalizedShellCrossSection(), G4PenelopeOscillatorManager::GetOscillatorTableIonisation(), kineticEnergy1, max, oscManager, phi, Q, Acts::Test::rb, targetOscillator, theCrossSectionHandler, and verboseLevel.
Referenced by SampleSecondaries().
void G4PenelopeIonisationModel::SampleFinalStatePositron (const G4Material * mat, G4double cutEnergy, G4double kineticEnergy) private
Definition at line 931 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 931 of file G4PenelopeIonisationModel.cc
References barn, cosThetaPrimary, cosThetaSecondary, cp, Acts::Test::delta, e, source.hepunit::electron_mass_c2, energySecondary, eV, G4cout, G4endl, G4UniformRand, G4InuclParticleNames::gam, G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4PenelopeIonisationXSHandler::GetDensityCorrection(), G4PenelopeCrossSection::GetNormalizedShellCrossSection(), G4PenelopeOscillatorManager::GetOscillatorTableIonisation(), kineticEnergy1, max, oscManager, phi, G4Positron::Positron(), Q, Acts::Test::rb, targetOscillator, theCrossSectionHandler, and verboseLevel.
Referenced by SampleSecondaries().
void G4PenelopeIonisationModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicParticle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 468 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 468 of file G4PenelopeIonisationModel.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4AtomicShell::BindingEnergy(), G4VAtomDeexcitation::CheckDeexcitationActiveRegion(), cosThetaPrimary, cosThetaSecondary, G4Electron::Definition(), G4Gamma::Definition(), G4InuclParticleNames::electron, G4Electron::Electron(), energySecondary, eV, FatalException, fAtomDeexcitation, fIntrinsicLowEnergyLimit, fParticleChange, fPIXEflag, G4cout, G4endl, G4Exception(), G4UniformRand, G4VAtomDeexcitation::GenerateParticles(), G4DynamicParticle::GetDefinition(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4PenelopeOscillatorManager::GetOscillatorTableIonisation(), G4ParticleDefinition::GetParticleName(), G4AtomicTransitionManager::Instance(), JustWarning, keV, kineticEnergy1, material(), oscManager, pi, G4Positron::Positron(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForLoss::ProposeMomentumDirection(), return(), CLHEP::Hep3Vector::rotateUz(), SampleFinalStateElectron(), SampleFinalStatePositron(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4AtomicTransitionManager::Shell(), targetOscillator, twopi, verboseLevel, and Z.
void G4PenelopeIonisationModel::SetParticle (const G4ParticleDefinition * p) private
Definition at line 1132 of file G4PenelopeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 1132 of file G4PenelopeIonisationModel.cc
References fParticle.
Referenced by G4PenelopeIonisationModel(), and Initialise().
void G4PenelopeIonisationModel::SetVerbosityLevel (G4int lev) inline
Definition at line 111 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4PenelopeIonisationModel.hh
References verboseLevel.
Member Data Documentation
G4double G4PenelopeIonisationModel::cosThetaPrimary private
Definition at line 144 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4PenelopeIonisationModel.hh
Referenced by SampleFinalStateElectron(), SampleFinalStatePositron(), and SampleSecondaries().
G4double G4PenelopeIonisationModel::cosThetaSecondary private
Definition at line 146 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4PenelopeIonisationModel.hh
Referenced by SampleFinalStateElectron(), SampleFinalStatePositron(), and SampleSecondaries().
G4double G4PenelopeIonisationModel::energySecondary private
Definition at line 145 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4PenelopeIonisationModel.hh
Referenced by SampleFinalStateElectron(), SampleFinalStatePositron(), and SampleSecondaries().
G4VAtomDeexcitation* G4PenelopeIonisationModel::fAtomDeexcitation private
Definition at line 139 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4PenelopeIonisationModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4double G4PenelopeIonisationModel::fIntrinsicHighEnergyLimit private
Definition at line 134 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 134 of file G4PenelopeIonisationModel.hh
Referenced by G4PenelopeIonisationModel().
G4double G4PenelopeIonisationModel::fIntrinsicLowEnergyLimit private
Definition at line 133 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4PenelopeIonisationModel.hh
Referenced by G4PenelopeIonisationModel(), MinEnergyCut(), and SampleSecondaries().
G4bool G4PenelopeIonisationModel::fLocalTable private
Definition at line 155 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4PenelopeIonisationModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), and ~G4PenelopeIonisationModel().
const G4ParticleDefinition* G4PenelopeIonisationModel::fParticle protected
Definition at line 116 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PenelopeIonisationModel.hh
Referenced by Initialise(), InitialiseLocal(), and SetParticle().
G4ParticleChangeForLoss* G4PenelopeIonisationModel::fParticleChange protected
Definition at line 112 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PenelopeIonisationModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4bool G4PenelopeIonisationModel::fPIXEflag private
Definition at line 140 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 140 of file G4PenelopeIonisationModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4bool G4PenelopeIonisationModel::isInitialised private
Definition at line 138 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4PenelopeIonisationModel.hh
Referenced by Initialise().
G4double G4PenelopeIonisationModel::kineticEnergy1 private
Definition at line 143 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 143 of file G4PenelopeIonisationModel.hh
Referenced by SampleFinalStateElectron(), SampleFinalStatePositron(), and SampleSecondaries().
size_t G4PenelopeIonisationModel::nBins private
Definition at line 152 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4PenelopeIonisationModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), G4PenelopeIonisationModel(), Initialise(), and InitialiseLocal().
G4PenelopeOscillatorManager* G4PenelopeIonisationModel::oscManager private
Definition at line 149 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 149 of file G4PenelopeIonisationModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), G4PenelopeIonisationModel(), SampleFinalStateElectron(), SampleFinalStatePositron(), and SampleSecondaries().
G4int G4PenelopeIonisationModel::targetOscillator private
Definition at line 147 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4PenelopeIonisationModel.hh
Referenced by SampleFinalStateElectron(), SampleFinalStatePositron(), and SampleSecondaries().
G4PenelopeIonisationXSHandler* G4PenelopeIonisationModel::theCrossSectionHandler private
Definition at line 150 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4PenelopeIonisationModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), Initialise(), InitialiseLocal(), SampleFinalStateElectron(), SampleFinalStatePositron(), and ~G4PenelopeIonisationModel().
G4int G4PenelopeIonisationModel::verboseLevel private
Definition at line 136 of file G4PenelopeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 136 of file G4PenelopeIonisationModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), G4PenelopeIonisationModel(), GetVerbosityLevel(), Initialise(), InitialiseLocal(), SampleFinalStateElectron(), SampleFinalStatePositron(), SampleSecondaries(), and SetVerbosityLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeIonisationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4PenelopeIonisationModel.cc