ECCE @ EIC Software: G4ExcitedDeltaConstructor Class Reference
G4ExcitedDeltaConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedDeltaConstructor.hh>
Public Types
enum { NStates = 9 }
enum { NumberOfDecayModes = 5 }
Public Member Functions
G4ExcitedDeltaConstructor ()
virtual ~G4ExcitedDeltaConstructor ()
Public Member Functions inherited from G4ExcitedBaryonConstructor
G4ExcitedBaryonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedBaryonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Member Functions
virtual G4int GetEncoding (G4int iIsoSpin3, G4int idxState)
virtual G4bool Exist (G4int)
virtual G4int GetQuarkContents (G4int, G4int)
virtual G4String GetName (G4int iIso3, G4int iState)
virtual G4String GetMultipletName (G4int iState)
virtual G4double GetMass (G4int state, G4int iso)
virtual G4double GetWidth (G4int state, G4int iso)
virtual G4int GetiSpin (G4int iState)
virtual G4int GetiParity (G4int iState)
virtual G4int GetEncodingOffset (G4int iState)
virtual G4DecayTable * CreateDecayTable (const G4String &name, G4int iIso3, G4int iState, G4bool fAnti=false)
Protected Member Functions inherited from G4ExcitedBaryonConstructor
virtual void ConstructParticle (G4int indexOfState)
virtual void ConstructAntiParticle (G4int indexOfState)
virtual G4double GetCharge (G4int iIsoSpin3)
Private Types
enum { DeltaIsoSpin = 3 }
enum {
NGamma =0, NPi =1, NRho =2, DeltaPi =3,
NStarPi =4
}
Private Member Functions
G4DecayTable * AddNGammaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNRhoMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddDeltaPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNStarPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
Static Private Attributes
static const char * name [NStates]
static const G4double mass [NStates]
static const G4double width [NStates]
static const G4int iSpin [NStates]
static const G4int iParity [NStates]
static const G4int encodingOffset [NStates]
static const G4double bRatio [NStates][NumberOfDecayModes]
Additional Inherited Members
Protected Attributes inherited from G4ExcitedBaryonConstructor
G4int NumberOfStates
G4int iIsoSpin
const G4String type
const G4int iConjugation
const G4int iGParity
const G4int leptonNumber
const G4int baryonNumber
Detailed Description
Definition at line 42 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ExcitedDeltaConstructor.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
NStates
Definition at line 83 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ExcitedDeltaConstructor.hh
anonymous enum private
Enumerator:
DeltaIsoSpin
Definition at line 85 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitedDeltaConstructor.hh
anonymous enum
Enumerator:
NumberOfDecayModes
Definition at line 96 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ExcitedDeltaConstructor.hh
anonymous enum private
Enumerator:
NGamma
NPi
NRho
DeltaPi
NStarPi
Definition at line 98 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ExcitedDeltaConstructor.hh
Constructor & Destructor Documentation
G4ExcitedDeltaConstructor::G4ExcitedDeltaConstructor ()
Definition at line 47 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ExcitedDeltaConstructor.cc
G4ExcitedDeltaConstructor::~G4ExcitedDeltaConstructor () virtual
Definition at line 53 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ExcitedDeltaConstructor.cc
Member Function Documentation
G4DecayTable * G4ExcitedDeltaConstructor::AddDeltaPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 375 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 375 of file G4ExcitedDeltaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedDeltaConstructor::AddNGammaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 118 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ExcitedDeltaConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedDeltaConstructor::AddNPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 146 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 146 of file G4ExcitedDeltaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedDeltaConstructor::AddNRhoMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 223 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 223 of file G4ExcitedDeltaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedDeltaConstructor::AddNStarPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 299 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 299 of file G4ExcitedDeltaConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedDeltaConstructor::CreateDecayTable (const G4String & name, G4int iIso3, G4int iState, G4bool fAnti = false) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 85 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitedDeltaConstructor.cc
References AddDeltaPiMode(), AddNGammaMode(), AddNPiMode(), AddNRhoMode(), AddNStarPiMode(), bRatio, DeltaPi, NGamma, NPi, NRho, and NStarPi.
virtual G4bool G4ExcitedDeltaConstructor::Exist (G4int) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 55 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ExcitedDeltaConstructor.hh
G4int G4ExcitedDeltaConstructor::GetEncoding (G4int iIsoSpin3, G4int idxState) protected virtual
Reimplemented from G4ExcitedBaryonConstructor.
Definition at line 57 of file G4ExcitedDeltaConstructor.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ExcitedDeltaConstructor.cc
References G4ExcitedBaryonConstructor::GetEncoding(), GetEncodingOffset(), GetiSpin(), and GetQuarkContents().
G4int G4ExcitedDeltaConstructor::GetEncodingOffset (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 128 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ExcitedDeltaConstructor.hh
References encodingOffset.
Referenced by GetEncoding().
G4int G4ExcitedDeltaConstructor::GetiParity (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 122 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ExcitedDeltaConstructor.hh
References iParity.
G4int G4ExcitedDeltaConstructor::GetiSpin (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 116 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ExcitedDeltaConstructor.hh
References iSpin.
Referenced by GetEncoding().
G4double G4ExcitedDeltaConstructor::GetMass (G4int state, G4int iso) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 104 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ExcitedDeltaConstructor.hh
References mass.
G4String G4ExcitedDeltaConstructor::GetMultipletName (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 171 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ExcitedDeltaConstructor.hh
G4String G4ExcitedDeltaConstructor::GetName (G4int iIso3, G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 177 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ExcitedDeltaConstructor.hh
References particle.
G4int G4ExcitedDeltaConstructor::GetQuarkContents (G4int iQ, G4int iIso3) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 134 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ExcitedDeltaConstructor.hh
Referenced by GetEncoding().
G4double G4ExcitedDeltaConstructor::GetWidth (G4int state, G4int iso) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 110 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ExcitedDeltaConstructor.hh
References width.
Member Data Documentation
const G4double G4ExcitedDeltaConstructor::bRatio static private
Initial value:
=
{
   {    0.0,   0.15,    0.0,   0.55,   0.30 },
   {    0.0,   0.25,    0.0,   0.60,   0.15 },
   {    0.0,   0.20,   0.10,   0.55,   0.15 },
   {    0.0,   0.30,   0.15,   0.30,   0.25 },
   {    0.0,   0.20,   0.60,   0.10,   0.10 },
   {    0.0,   0.35,   0.40,   0.15,   0.10 },
   {    0.0,   0.15,   0.30,   0.30,   0.25 },
   {    0.0,   0.20,   0.25,   0.25,   0.30 },
   {   0.01,   0.44,   0.15,   0.20,   0.20 }
}
Definition at line 100 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ExcitedDeltaConstructor.hh
Referenced by CreateDecayTable().
const G4int G4ExcitedDeltaConstructor::encodingOffset static private
Initial value:
= {
  30000,     0, 10000, 10000,     0,
  20000, 20000, 10000,     0
}
Definition at line 93 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ExcitedDeltaConstructor.hh
Referenced by GetEncodingOffset().
const G4int G4ExcitedDeltaConstructor::iParity static private
Initial value:
= {
  +1,  -1,   -1,  -1,  +1,
  +1,  +1,   -1,  +1
}
Definition at line 92 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ExcitedDeltaConstructor.hh
Referenced by GetiParity().
const G4int G4ExcitedDeltaConstructor::iSpin static private
Initial value:
=
{
    3,   1,   3,   1,   5,
    1,   3,   5,   7
}
Definition at line 91 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ExcitedDeltaConstructor.hh
Referenced by GetiSpin().
const G4double G4ExcitedDeltaConstructor::mass static private
Initial value:
=
{
  1.600*GeV, 1.630*GeV, 1.700*GeV, 1.900*GeV,  1.880*GeV,
  1.890*GeV, 1.920*GeV, 1.950*GeV, 1.930*GeV
}
Definition at line 89 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ExcitedDeltaConstructor.hh
Referenced by GetMass().
const char * G4ExcitedDeltaConstructor::name static private
Initial value:
=
{
  "delta(1600)", "delta(1620)", "delta(1700)", "delta(1900)", "delta(1905)",
  "delta(1910)", "delta(1920)", "delta(1930)", "delta(1950)"
}
Definition at line 88 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ExcitedDeltaConstructor.hh
const G4double G4ExcitedDeltaConstructor::width static private
Initial value:
= {
  320.0*MeV, 140.0*MeV, 300.0*MeV, 200.0*MeV, 330.0*MeV,
  280.0*MeV, 260.0*MeV, 360.0*MeV, 280.0*MeV
}
Definition at line 90 of file G4ExcitedDeltaConstructor.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ExcitedDeltaConstructor.hh
Referenced by GetWidth().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedDeltaConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ExcitedDeltaConstructor.cc