ECCE @ EIC Software: G4EquationOfMotion Class Reference
G4EquationOfMotion Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4EquationOfMotion.hh>
Public Member Functions
G4EquationOfMotion (G4Field *Field)
virtual ~G4EquationOfMotion ()
virtual void EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const =0
virtual void SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double MassXc2)=0
void RightHandSide (const G4double y[], G4double dydx[]) const
void EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const
void GetFieldValue (const G4double Point[4], G4double Field[]) const
const G4Field * GetFieldObj () const
G4Field * GetFieldObj ()
void SetFieldObj (G4Field *pField)
Private Attributes
G4Field * itsField = nullptr
Detailed Description
Definition at line 43 of file G4EquationOfMotion.hh.
View newest version in sPHENIX GitHub at line 43 of file G4EquationOfMotion.hh
Constructor & Destructor Documentation
G4EquationOfMotion::G4EquationOfMotion (G4Field * Field)
Definition at line 33 of file G4EquationOfMotion.cc.
View newest version in sPHENIX GitHub at line 33 of file G4EquationOfMotion.cc
G4EquationOfMotion::~G4EquationOfMotion () virtual
Definition at line 38 of file G4EquationOfMotion.cc.
View newest version in sPHENIX GitHub at line 38 of file G4EquationOfMotion.cc
Member Function Documentation
virtual void G4EquationOfMotion::EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const pure virtual
Implemented in G4BlineEquation, G4Mag_SpinEqRhs, G4KM_NucleonEqRhs, G4KM_OpticalEqRhs, G4Mag_EqRhs, G4Mag_UsualEqRhs, and G4ErrorMag_UsualEqRhs.
Referenced by G4RKG3_Stepper::StepNoErr(), and G4RKG3_Stepper::Stepper().
void G4EquationOfMotion::EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const inline
Referenced by G4RKG3_Stepper::StepNoErr().
const G4Field* G4EquationOfMotion::GetFieldObj () const inline
Referenced by G4NystromRK4::GetField().
G4Field* G4EquationOfMotion::GetFieldObj () inline
void G4EquationOfMotion::GetFieldValue (const G4double Point[4], G4double Field[]) const inline
Referenced by G4BFieldIntegrationDriver::GetFieldValue(), and G4MultiLevelLocator::ReportFieldValue().
void G4EquationOfMotion::RightHandSide (const G4double y[], G4double dydx[]) const inline
Referenced by G4ModifiedMidpoint::DoStep(), and G4VFSALIntegrationStepper::RightHandSide().
virtual void G4EquationOfMotion::SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double MassXc2) pure virtual
Implemented in G4Mag_EqRhs, G4MonopoleEquation, G4Mag_UsualEqRhs, G4KM_NucleonEqRhs, G4KM_OpticalEqRhs, G4Mag_SpinEqRhs, G4EqEMFieldWithEDM, G4EqEMFieldWithSpin, G4MonopoleEq, G4RepleteEofM, G4EqGravityField, and G4EqMagElectricField.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), and G4PathFinder::DoNextCurvedStep().
void G4EquationOfMotion::SetFieldObj (G4Field * pField) inline
Referenced by G4FieldManager::SetDetectorField(), G4NystromRK4::SetDistanceForConstantField(), F03FieldSetup::SetFieldValue(), F02ElectricFieldSetup::SetFieldValue(), G4TBMagneticFieldSetup::SetFieldValue(), F01FieldSetup::SetFieldValue(), and F03FieldSetup::SetLocalFieldValue().
Member Data Documentation
G4Field* G4EquationOfMotion::itsField = nullptr private
Definition at line 90 of file G4EquationOfMotion.hh.
View newest version in sPHENIX GitHub at line 90 of file G4EquationOfMotion.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4EquationOfMotion.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4EquationOfMotion.cc