ECCE @ EIC Software: G4VPersistencyManager Class Reference
G4VPersistencyManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VPersistencyManager.hh>
Public Member Functions
virtual ~G4VPersistencyManager ()
virtual G4bool Store (const G4Event *anEvent)=0
virtual G4bool Store (const G4Run *aRun)=0
virtual G4bool Store (const G4VPhysicalVolume *theWorld)=0
virtual G4bool Retrieve (G4Event *&anEvent)=0
virtual G4bool Retrieve (G4Run *&aRun)=0
virtual G4bool Retrieve (G4VPhysicalVolume *&theWorld)=0
Static Public Member Functions
static G4VPersistencyManager * GetPersistencyManager ()
Protected Member Functions
G4VPersistencyManager ()
Static Private Attributes
static G4ThreadLocal
G4VPersistencyManager * fPersistencyManager = 0
Detailed Description
Definition at line 51 of file G4VPersistencyManager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VPersistencyManager.hh
Constructor & Destructor Documentation
G4VPersistencyManager::G4VPersistencyManager () protected
Definition at line 38 of file G4VPersistencyManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VPersistencyManager.cc
References fPersistencyManager.
G4VPersistencyManager::~G4VPersistencyManager () virtual
Definition at line 43 of file G4VPersistencyManager.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VPersistencyManager.cc
References fPersistencyManager.
Member Function Documentation
G4VPersistencyManager * G4VPersistencyManager::GetPersistencyManager () static
Definition at line 33 of file G4VPersistencyManager.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VPersistencyManager.cc
References fPersistencyManager.
Referenced by G4RunManager::AnalyzeEvent(), and G4RunManager::RunTermination().
virtual G4bool G4VPersistencyManager::Retrieve (G4Event *& anEvent) pure virtual
Implemented in G4PersistencyManager.
virtual G4bool G4VPersistencyManager::Retrieve (G4Run *& aRun) pure virtual
Implemented in G4PersistencyManager.
virtual G4bool G4VPersistencyManager::Retrieve (G4VPhysicalVolume *& theWorld) pure virtual
Implemented in G4PersistencyManager.
virtual G4bool G4VPersistencyManager::Store (const G4Event * anEvent) pure virtual
Implemented in G4PersistencyManager.
Referenced by G4RunManager::AnalyzeEvent(), and G4RunManager::RunTermination().
virtual G4bool G4VPersistencyManager::Store (const G4Run * aRun) pure virtual
Implemented in G4PersistencyManager.
virtual G4bool G4VPersistencyManager::Store (const G4VPhysicalVolume * theWorld) pure virtual
Implemented in G4PersistencyManager.
Member Data Documentation
G4ThreadLocal G4VPersistencyManager * G4VPersistencyManager::fPersistencyManager = 0 static private
Definition at line 65 of file G4VPersistencyManager.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VPersistencyManager.hh
Referenced by G4VPersistencyManager(), GetPersistencyManager(), and ~G4VPersistencyManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VPersistencyManager.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VPersistencyManager.cc