ECCE @ EIC Software: G4PenelopeRayleighModel Class Reference
G4PenelopeRayleighModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeRayleighModel.hh>
Public Member Functions
G4PenelopeRayleighModel (const G4ParticleDefinition *p=0, const G4String &processName="PenRayleigh")
virtual ~G4PenelopeRayleighModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0, G4double cut=0, G4double emax=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
void SetVerbosityLevel (G4int lev)
G4int GetVerbosityLevel ()
void DumpFormFactorTable (const G4Material *)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChange
const G4ParticleDefinition * fParticle
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4PenelopeRayleighModel & operator= (const G4PenelopeRayleighModel &right)
G4PenelopeRayleighModel (const G4PenelopeRayleighModel &)
void SetParticle (const G4ParticleDefinition *)
void ReadDataFile (G4int)
void ClearTables ()
void BuildFormFactorTable (const G4Material *)
void GetPMaxTable (const G4Material *)
G4double GetFSquared (const G4Material *, const G4double)
void InitializeSamplingAlgorithm (const G4Material *)
Private Attributes
G4double fIntrinsicLowEnergyLimit
G4double fIntrinsicHighEnergyLimit
G4int verboseLevel
G4bool isInitialised
std::map< G4int,
G4PhysicsFreeVector * > * logAtomicCrossSection
std::map< G4int,
G4PhysicsFreeVector * > * atomicFormFactor
G4DataVector logQSquareGrid
std::map< const G4Material
*, G4PhysicsFreeVector * > * logFormFactorTable
G4DataVector logEnergyGridPMax
std::map< const G4Material
*, G4PhysicsFreeVector * > * pMaxTable
std::map< const G4Material
*, G4PenelopeSamplingData * > * samplingTable
G4bool fLocalTable
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 57 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4PenelopeRayleighModel.hh
Constructor & Destructor Documentation
G4PenelopeRayleighModel::G4PenelopeRayleighModel (const G4ParticleDefinition * p = 0, const G4String & processName = "PenRayleigh")
Definition at line 53 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4PenelopeRayleighModel.cc
References eV, fIntrinsicHighEnergyLimit, fIntrinsicLowEnergyLimit, GeV, keV, logEnergyGridPMax, G4VEmModel::SetHighEnergyLimit(), SetParticle(), and verboseLevel.
G4PenelopeRayleighModel::~G4PenelopeRayleighModel () virtual
Definition at line 95 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 95 of file G4PenelopeRayleighModel.cc
References atomicFormFactor, ClearTables(), fLocalTable, G4VEmModel::IsMaster(), and logAtomicCrossSection.
G4PenelopeRayleighModel::G4PenelopeRayleighModel (const G4PenelopeRayleighModel &) private
Member Function Documentation
void G4PenelopeRayleighModel::BuildFormFactorTable (const G4Material * material) private
Definition at line 344 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 344 of file G4PenelopeRayleighModel.cc
References atomicFormFactor, e, f, FatalException, Acts::UnitConstants::g, G4endl, G4Exception(), G4Material::GetElementVector(), G4Material::GetFractionVector(), G4Material::GetName(), G4Material::GetNumberOfElements(), k, logFormFactorTable, logQSquareGrid, mole, G4PhysicsFreeVector::PutValue(), and G4PhysicsVector::SetSpline().
Referenced by DumpFormFactorTable(), Initialise(), and SampleSecondaries().
void G4PenelopeRayleighModel::ClearTables () private
Definition at line 118 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 118 of file G4PenelopeRayleighModel.cc
References logFormFactorTable, pMaxTable, and samplingTable.
Referenced by Initialise(), and ~G4PenelopeRayleighModel().
G4double G4PenelopeRayleighModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0, G4double cut = 0, G4double emax = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 273 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 273 of file G4PenelopeRayleighModel.cc
References barn, Acts::VectorHelpers::cross(), FatalException, fLocalTable, G4cout, G4endl, G4Exception(), G4Exp(), JustWarning, keV, logAtomicCrossSection, ReadDataFile(), G4TemplateAutoLock< _Mutex_t >::unlock(), G4PhysicsVector::Value(), and verboseLevel.
void G4PenelopeRayleighModel::DumpFormFactorTable (const G4Material * mat)
Definition at line 1332 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 1332 of file G4PenelopeRayleighModel.cc
References BuildFormFactorTable(), F, G4cout, G4endl, G4Exp(), G4PhysicsVector::GetLowEdgeEnergy(), G4Material::GetName(), G4PhysicsVector::GetVectorLength(), logFormFactorTable, and Q.
G4double G4PenelopeRayleighModel::GetFSquared (const G4Material * mat, const G4double QSquared) private
Definition at line 723 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 723 of file G4PenelopeRayleighModel.cc
References e, f2, FatalException, G4cout, G4endl, G4Exception(), G4Exp(), G4Material::GetName(), logFormFactorTable, logQSquareGrid, G4PhysicsVector::Value(), and verboseLevel.
Referenced by InitializeSamplingAlgorithm().
void G4PenelopeRayleighModel::GetPMaxTable (const G4Material * mat) private
Definition at line 1197 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 1197 of file G4PenelopeRayleighModel.cc
References source.hepunit::electron_mass_c2, energy, FatalException, G4cout, G4endl, G4Exception(), G4Exp(), G4PenelopeSamplingData::GetA(), G4PenelopeSamplingData::GetB(), G4Material::GetName(), G4PenelopeSamplingData::GetNumberOfStoredPoints(), G4PenelopeSamplingData::GetPAC(), G4PenelopeSamplingData::GetX(), hh, k, logEnergyGridPMax, pMaxTable, G4PhysicsFreeVector::PutValue(), samplingTable, and sum.
Referenced by Initialise(), and SampleSecondaries().
G4int G4PenelopeRayleighModel::GetVerbosityLevel () inline
Definition at line 84 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4PenelopeRayleighModel.hh
References verboseLevel.
void G4PenelopeRayleighModel::Initialise (const G4ParticleDefinition * part, const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 156 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 156 of file G4PenelopeRayleighModel.cc
References atomicFormFactor, BuildFormFactorTable(), ClearTables(), fParticle, fParticleChange, G4cout, G4endl, G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4VEmModel::GetParticleChangeForGamma(), GetPMaxTable(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), GeV, G4VEmModel::HighEnergyLimit(), InitializeSamplingAlgorithm(), isInitialised, G4VEmModel::IsMaster(), keV, logAtomicCrossSection, logFormFactorTable, G4VEmModel::LowEnergyLimit(), material(), pMaxTable, ReadDataFile(), samplingTable, SetParticle(), and verboseLevel.
void G4PenelopeRayleighModel::InitialiseLocal (const G4ParticleDefinition * part, G4VEmModel * masterModel) virtual
Reimplemented from G4VEmModel.
Definition at line 237 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 237 of file G4PenelopeRayleighModel.cc
References atomicFormFactor, fParticle, G4cout, G4endl, logAtomicCrossSection, logFormFactorTable, logQSquareGrid, pMaxTable, samplingTable, and verboseLevel.
void G4PenelopeRayleighModel::InitializeSamplingAlgorithm (const G4Material * mat) private
Definition at line 769 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 769 of file G4PenelopeRayleighModel.cc
References a, G4PenelopeSamplingData::AddPoint(), demo::app, b, bin, c, G4PenelopeSamplingData::DumpTable(), dx, e, check_license::err(), FatalException, G4cout, G4endl, G4Exception(), G4Exp(), GetFSquared(), G4Material::GetName(), k, logQSquareGrid, max, min, samplingTable, verboseLevel, and x.
Referenced by Initialise(), and SampleSecondaries().
G4PenelopeRayleighModel& G4PenelopeRayleighModel::operator= (const G4PenelopeRayleighModel & right) private
void G4PenelopeRayleighModel::ReadDataFile (G4int Z) private
Definition at line 586 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 586 of file G4PenelopeRayleighModel.cc
References atomicFormFactor, cm2, eV, f1, f2, FatalException, ff, file, G4cout, G4endl, G4Exception(), logAtomicCrossSection, logQSquareGrid, G4PhysicsFreeVector::PutValue(), and verboseLevel.
Referenced by ComputeCrossSectionPerAtom(), Initialise(), and SampleSecondaries().
void G4PenelopeRayleighModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicGamma, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 415 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 415 of file G4PenelopeRayleighModel.cc
References atomicFormFactor, BuildFormFactorTable(), e, source.hepunit::electron_mass_c2, fIntrinsicLowEnergyLimit, fLocalTable, fParticleChange, fStopAndKill, G, G4cout, G4endl, G4Exception(), G4UniformRand, G4Material::GetElementVector(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4Material::GetName(), G4Material::GetNumberOfElements(), G4PenelopeSamplingData::GetNumberOfStoredPoints(), GetPMaxTable(), G4PenelopeSamplingData::GetX(), InitializeSamplingAlgorithm(), JustWarning, G4TemplateAutoLock< _Mutex_t >::lock(), logAtomicCrossSection, logFormFactorTable, min, phi, pMaxTable, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), ReadDataFile(), return(), CLHEP::Hep3Vector::rotateUz(), G4PenelopeSamplingData::SampleValue(), samplingTable, G4ParticleChangeForGamma::SetProposedKineticEnergy(), twopi, G4TemplateAutoLock< _Mutex_t >::unlock(), G4PhysicsVector::Value(), verboseLevel, and xx.
void G4PenelopeRayleighModel::SetParticle (const G4ParticleDefinition * p) private
Definition at line 1357 of file G4PenelopeRayleighModel.cc.
View newest version in sPHENIX GitHub at line 1357 of file G4PenelopeRayleighModel.cc
References fParticle.
Referenced by G4PenelopeRayleighModel(), and Initialise().
void G4PenelopeRayleighModel::SetVerbosityLevel (G4int lev) inline
Definition at line 83 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PenelopeRayleighModel.hh
References verboseLevel.
Member Data Documentation
std::map<G4int,G4PhysicsFreeVector*>* G4PenelopeRayleighModel::atomicFormFactor private
Definition at line 109 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4PenelopeRayleighModel.hh
Referenced by BuildFormFactorTable(), Initialise(), InitialiseLocal(), ReadDataFile(), SampleSecondaries(), and ~G4PenelopeRayleighModel().
G4double G4PenelopeRayleighModel::fIntrinsicHighEnergyLimit private
Definition at line 102 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PenelopeRayleighModel.hh
Referenced by G4PenelopeRayleighModel().
G4double G4PenelopeRayleighModel::fIntrinsicLowEnergyLimit private
Definition at line 101 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PenelopeRayleighModel.hh
Referenced by G4PenelopeRayleighModel(), and SampleSecondaries().
G4bool G4PenelopeRayleighModel::fLocalTable private
Definition at line 130 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PenelopeRayleighModel.hh
Referenced by ComputeCrossSectionPerAtom(), SampleSecondaries(), and ~G4PenelopeRayleighModel().
const G4ParticleDefinition* G4PenelopeRayleighModel::fParticle protected
Definition at line 91 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PenelopeRayleighModel.hh
Referenced by Initialise(), InitialiseLocal(), and SetParticle().
G4ParticleChangeForGamma* G4PenelopeRayleighModel::fParticleChange protected
Definition at line 90 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PenelopeRayleighModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4bool G4PenelopeRayleighModel::isInitialised private
Definition at line 105 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4PenelopeRayleighModel.hh
Referenced by Initialise().
std::map<G4int,G4PhysicsFreeVector*>* G4PenelopeRayleighModel::logAtomicCrossSection private
Definition at line 108 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PenelopeRayleighModel.hh
Referenced by ComputeCrossSectionPerAtom(), Initialise(), InitialiseLocal(), ReadDataFile(), SampleSecondaries(), and ~G4PenelopeRayleighModel().
G4DataVector G4PenelopeRayleighModel::logEnergyGridPMax private
Definition at line 115 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PenelopeRayleighModel.hh
Referenced by G4PenelopeRayleighModel(), and GetPMaxTable().
std::map<const G4Material*,G4PhysicsFreeVector*>* G4PenelopeRayleighModel::logFormFactorTable private
Definition at line 113 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PenelopeRayleighModel.hh
Referenced by BuildFormFactorTable(), ClearTables(), DumpFormFactorTable(), GetFSquared(), Initialise(), InitialiseLocal(), and SampleSecondaries().
G4DataVector G4PenelopeRayleighModel::logQSquareGrid private
Definition at line 112 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PenelopeRayleighModel.hh
Referenced by BuildFormFactorTable(), GetFSquared(), InitialiseLocal(), InitializeSamplingAlgorithm(), and ReadDataFile().
std::map<const G4Material*,G4PhysicsFreeVector*>* G4PenelopeRayleighModel::pMaxTable private
Definition at line 116 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PenelopeRayleighModel.hh
Referenced by ClearTables(), GetPMaxTable(), Initialise(), InitialiseLocal(), and SampleSecondaries().
std::map<const G4Material*,G4PenelopeSamplingData*>* G4PenelopeRayleighModel::samplingTable private
Definition at line 118 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4PenelopeRayleighModel.hh
Referenced by ClearTables(), GetPMaxTable(), Initialise(), InitialiseLocal(), InitializeSamplingAlgorithm(), and SampleSecondaries().
G4int G4PenelopeRayleighModel::verboseLevel private
Definition at line 104 of file G4PenelopeRayleighModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4PenelopeRayleighModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4PenelopeRayleighModel(), GetFSquared(), GetVerbosityLevel(), Initialise(), InitialiseLocal(), InitializeSamplingAlgorithm(), ReadDataFile(), SampleSecondaries(), and SetVerbosityLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeRayleighModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4PenelopeRayleighModel.cc