ECCE @ EIC Software: CexmcTrackPoints Class Reference
CexmcTrackPoints Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPoints.hh>
Public Member Functions
CexmcTrackPoints (const G4String &name)
void Initialize (G4HCofThisEvent *hcOfThisEvent)
void EndOfEvent (G4HCofThisEvent *hcOfThisEvent)
void DrawAll (void)
void PrintAll (void)
void clear (void)
Public Member Functions inherited from CexmcPrimitiveScorer
CexmcPrimitiveScorer (const G4String &name)
virtual ~CexmcPrimitiveScorer ()
void InitializeMessenger (void)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
G4int GetTrackId (G4Step *step)
G4int GetIndex (G4Step *step)
G4bool ProcessHits (G4Step *step, G4TouchableHistory *tHistory)
Protected Member Functions inherited from CexmcPrimitiveScorer
void PrintHeader (G4int nmbOfEntries) const
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Protected Attributes
CexmcTrackPointsCollection * eventMap
Private Attributes
G4int hcId
Detailed Description
Definition at line 61 of file CexmcTrackPoints.hh.
View newest version in sPHENIX GitHub at line 61 of file CexmcTrackPoints.hh
Constructor & Destructor Documentation
CexmcTrackPoints::CexmcTrackPoints (const G4String & name) explicit
Definition at line 51 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 51 of file CexmcTrackPoints.cc
Member Function Documentation
void CexmcTrackPoints::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 134 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 134 of file CexmcTrackPoints.cc
References G4VTHitsMap< T, Map_t >::clear(), and eventMap.
void CexmcTrackPoints::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 140 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 140 of file CexmcTrackPoints.cc
void CexmcTrackPoints::EndOfEvent (G4HCofThisEvent * hcOfThisEvent) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 127 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 127 of file CexmcTrackPoints.cc
References G4VPrimitiveScorer::GetVerboseLevel(), and PrintAll().
G4int CexmcTrackPoints::GetIndex (G4Step * step) protected virtual
Reimplemented from G4VPrimitiveScorer.
Reimplemented in CexmcTrackPointsInLeftRightSet, and CexmcTrackPointsInCalorimeter.
Definition at line 73 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 73 of file CexmcTrackPoints.cc
References GetTrackId().
Referenced by ProcessHits().
G4int CexmcTrackPoints::GetTrackId (G4Step * step) protected
Definition at line 57 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 57 of file CexmcTrackPoints.cc
References CexmcOutputParticleDecayProductTrack, CexmcTrackInfo::GetCopyNumber(), G4Step::GetTrack(), CexmcTrackInfo::GetTrackType(), and G4Track::GetUserInformation().
Referenced by CexmcTrackPointsInCalorimeter::GetIndex(), CexmcTrackPointsInLeftRightSet::GetIndex(), and GetIndex().
void CexmcTrackPoints::Initialize (G4HCofThisEvent * hcOfThisEvent) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 115 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 115 of file CexmcTrackPoints.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, eventMap, G4VPrimitiveScorer::GetCollectionID(), G4VSensitiveDetector::GetName(), hcId, and G4VPrimitiveScorer::primitiveName.
void CexmcTrackPoints::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Reimplemented in CexmcTrackPointsInLeftRightSet, and CexmcTrackPointsInCalorimeter.
Definition at line 145 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 145 of file CexmcTrackPoints.cc
References G4VTHitsMap< T, Map_t >::entries(), eventMap, G4BestUnit, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), and CexmcPrimitiveScorer::PrintHeader().
Referenced by EndOfEvent().
G4bool CexmcTrackPoints::ProcessHits (G4Step * step, G4TouchableHistory * tHistory) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 79 of file CexmcTrackPoints.cc.
View newest version in sPHENIX GitHub at line 79 of file CexmcTrackPoints.cc
References CexmcInsipidTrack, eventMap, GetIndex(), G4Step::GetPreStepPoint(), G4Step::GetTrack(), particle, position, G4VTHitsMap< T, Map_t >::set(), track, and Acts::Test::transform.
Member Data Documentation
CexmcTrackPointsCollection* CexmcTrackPoints::eventMap protected
Definition at line 85 of file CexmcTrackPoints.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcTrackPoints.hh
Referenced by clear(), Initialize(), CexmcTrackPointsInCalorimeter::PrintAll(), CexmcTrackPointsInLeftRightSet::PrintAll(), PrintAll(), and ProcessHits().
G4int CexmcTrackPoints::hcId private
Definition at line 88 of file CexmcTrackPoints.hh.
View newest version in sPHENIX GitHub at line 88 of file CexmcTrackPoints.hh
Referenced by Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPoints.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcTrackPoints.cc