ECCE @ EIC Software: G4BlineEventAction Class Reference
G4BlineEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlineEventAction.hh>
Public Member Functions
G4BlineEventAction (G4BlineTracer *aBlineTool)
virtual ~G4BlineEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
void DrawFieldLines (G4double zoom, G4double theta, G4double phi)
void ResetVectorObjectToBeDrawn ()
void SetDrawColour (G4Colour aColour)
void SetDrawBline (G4bool aBool)
void SetDrawPoints (G4bool aBool)
void SetPointSize (G4double aVal)
G4bool GetDrawBline ()
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4BlineTracer * fBlineTool
G4Colour fDrawColour
G4bool fDrawBline
G4bool fDrawPoints
G4double fPointSize
std::vector< G4VisAttributes * > fTrajectoryVisAttributes
std::vector< G4Polyline > fTrajectoryPolyline
std::vector< G4Polymarker > fTrajectoryPoints
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 60 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4BlineEventAction.hh
Constructor & Destructor Documentation
G4BlineEventAction::G4BlineEventAction (G4BlineTracer * aBlineTool)
Definition at line 54 of file G4BlineEventAction.cc.
View newest version in sPHENIX GitHub at line 54 of file G4BlineEventAction.cc
References fBlineTool.
G4BlineEventAction::~G4BlineEventAction () virtual
Definition at line 61 of file G4BlineEventAction.cc.
View newest version in sPHENIX GitHub at line 61 of file G4BlineEventAction.cc
References fTrajectoryVisAttributes.
Member Function Documentation
void G4BlineEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Definition at line 69 of file G4BlineEventAction.cc.
View newest version in sPHENIX GitHub at line 69 of file G4BlineEventAction.cc
void G4BlineEventAction::DrawFieldLines (G4double zoom, G4double theta, G4double phi)
Definition at line 114 of file G4BlineEventAction.cc.
View newest version in sPHENIX GitHub at line 114 of file G4BlineEventAction.cc
References G4VVisManager::Draw(), fTrajectoryPoints, fTrajectoryPolyline, G4cout, G4endl, G4Exception(), G4VVisManager::GetConcreteInstance(), G4UImanager::GetUIpointer(), and JustWarning.
Referenced by G4BlineTracerMessenger::SetNewValue().
void G4BlineEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 75 of file G4BlineEventAction.cc.
View newest version in sPHENIX GitHub at line 75 of file G4BlineEventAction.cc
References G4Polymarker::circles, fDrawBline, fDrawColour, fDrawPoints, G4VMarker::filled, fPointSize, fTrajectoryPoints, fTrajectoryPolyline, fTrajectoryVisAttributes, G4Event::GetTrajectoryContainer(), pos(), G4VMarker::SetFillStyle(), G4Polymarker::SetMarkerType(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
G4bool G4BlineEventAction::GetDrawBline () inline
Definition at line 79 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 79 of file G4BlineEventAction.hh
References fDrawBline.
void G4BlineEventAction::ResetVectorObjectToBeDrawn ()
Definition at line 148 of file G4BlineEventAction.cc.
View newest version in sPHENIX GitHub at line 148 of file G4BlineEventAction.cc
References fTrajectoryPoints, fTrajectoryPolyline, and fTrajectoryVisAttributes.
Referenced by G4BlineTracerMessenger::SetNewValue().
void G4BlineEventAction::SetDrawBline (G4bool aBool) inline
Definition at line 76 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 76 of file G4BlineEventAction.hh
References fDrawBline.
Referenced by G4BlineTracerMessenger::SetNewValue().
void G4BlineEventAction::SetDrawColour (G4Colour aColour) inline
Definition at line 75 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BlineEventAction.hh
References fDrawColour.
void G4BlineEventAction::SetDrawPoints (G4bool aBool) inline
Definition at line 77 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 77 of file G4BlineEventAction.hh
References fDrawPoints.
Referenced by G4BlineTracerMessenger::SetNewValue().
void G4BlineEventAction::SetPointSize (G4double aVal) inline
Definition at line 78 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BlineEventAction.hh
References fPointSize.
Referenced by G4BlineTracerMessenger::SetNewValue().
Member Data Documentation
G4BlineTracer* G4BlineEventAction::fBlineTool private
Definition at line 91 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BlineEventAction.hh
Referenced by G4BlineEventAction().
G4bool G4BlineEventAction::fDrawBline private
Definition at line 93 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BlineEventAction.hh
Referenced by EndOfEventAction(), GetDrawBline(), and SetDrawBline().
G4Colour G4BlineEventAction::fDrawColour private
Definition at line 92 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BlineEventAction.hh
Referenced by EndOfEventAction(), and SetDrawColour().
G4bool G4BlineEventAction::fDrawPoints private
Definition at line 94 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 94 of file G4BlineEventAction.hh
Referenced by EndOfEventAction(), and SetDrawPoints().
G4double G4BlineEventAction::fPointSize private
Definition at line 95 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 95 of file G4BlineEventAction.hh
Referenced by EndOfEventAction(), and SetPointSize().
std::vector<G4Polymarker> G4BlineEventAction::fTrajectoryPoints private
Definition at line 98 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 98 of file G4BlineEventAction.hh
Referenced by DrawFieldLines(), EndOfEventAction(), and ResetVectorObjectToBeDrawn().
std::vector<G4Polyline> G4BlineEventAction::fTrajectoryPolyline private
Definition at line 97 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 97 of file G4BlineEventAction.hh
Referenced by DrawFieldLines(), EndOfEventAction(), and ResetVectorObjectToBeDrawn().
std::vector<G4VisAttributes*> G4BlineEventAction::fTrajectoryVisAttributes private
Definition at line 96 of file G4BlineEventAction.hh.
View newest version in sPHENIX GitHub at line 96 of file G4BlineEventAction.hh
Referenced by EndOfEventAction(), ResetVectorObjectToBeDrawn(), and ~G4BlineEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlineEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/src/G4BlineEventAction.cc