ECCE @ EIC Software: G4RayTrajectory Class Reference
G4RayTrajectory Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RayTrajectory.hh>
Public Member Functions
G4RayTrajectory ()
G4RayTrajectory (G4RayTrajectory &right)
virtual ~G4RayTrajectory ()
void * operator new (size_t)
void operator delete (void *)
virtual void AppendStep (const G4Step *)
virtual void ShowTrajectory (std::ostream &) const
virtual void DrawTrajectory () const
virtual int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
G4RayTrajectoryPoint * GetPointC (G4int i) const
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4ThreeVector GetInitialMomentum () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Member Functions
G4RayTrajectory & operator= (const G4RayTrajectory &)
Private Attributes
std::vector
< G4RayTrajectoryPoint * > * positionRecord
Detailed Description
Definition at line 56 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 56 of file G4RayTrajectory.hh
Constructor & Destructor Documentation
G4RayTrajectory::G4RayTrajectory ()
Definition at line 53 of file G4RayTrajectory.cc.
View newest version in sPHENIX GitHub at line 53 of file G4RayTrajectory.cc
References positionRecord.
G4RayTrajectory::G4RayTrajectory (G4RayTrajectory & right)
Definition at line 58 of file G4RayTrajectory.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RayTrajectory.cc
References positionRecord.
G4RayTrajectory::~G4RayTrajectory () virtual
Definition at line 70 of file G4RayTrajectory.cc.
View newest version in sPHENIX GitHub at line 70 of file G4RayTrajectory.cc
References positionRecord.
Member Function Documentation
void G4RayTrajectory::AppendStep (const G4Step * theStep) virtual
Implements G4VTrajectory.
Definition at line 79 of file G4RayTrajectory.cc.
View newest version in sPHENIX GitHub at line 79 of file G4RayTrajectory.cc
References G4VTouchable::GetCopyNumber(), G4VisManager::GetCurrentSceneHandler(), G4VTouchable::GetHistoryDepth(), G4ParallelWorldProcess::GetHyperStep(), G4ParallelWorldProcess::GetHypNavigatorID(), G4VisManager::GetInstance(), G4Navigator::GetLocalExitNormal(), G4Navigator::GetLocalToGlobalTransform(), G4TransportationManager::GetNavigatorForTracking(), G4RayTracerSceneHandler::GetSceneVisAttsMap(), G4Step::GetStepLength(), G4StepPoint::GetTouchable(), G4TransportationManager::GetTransportationManager(), G4VTouchable::GetVolume(), positionRecord, G4RayTrajectoryPoint::SetPostStepAtt(), G4RayTrajectoryPoint::SetPreStepAtt(), G4RayTrajectoryPoint::SetStepLength(), G4RayTrajectoryPoint::SetSurfaceNormal(), G4AffineTransform::TransformAxis(), and Acts::IntegrationTest::valid().
virtual void G4RayTrajectory::DrawTrajectory () const inline virtual
Reimplemented from G4VTrajectory.
Definition at line 76 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RayTrajectory.hh
G4double G4RayTrajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 88 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RayTrajectory.hh
G4ThreeVector G4RayTrajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 90 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RayTrajectory.hh
G4int G4RayTrajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 86 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RayTrajectory.hh
G4String G4RayTrajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 87 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RayTrajectory.hh
G4int G4RayTrajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 89 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RayTrajectory.hh
virtual G4VTrajectoryPoint* G4RayTrajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Definition at line 78 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 78 of file G4RayTrajectory.hh
References positionRecord.
Referenced by MergeTrajectory().
G4RayTrajectoryPoint* G4RayTrajectory::GetPointC (G4int i) const inline
Definition at line 80 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RayTrajectory.hh
References positionRecord.
Referenced by G4TheRayTracer::GenerateColour(), and G4RTRun::RecordEvent().
virtual int G4RayTrajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Definition at line 77 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RayTrajectory.hh
References positionRecord.
Referenced by G4TheRayTracer::GenerateColour(), MergeTrajectory(), and G4RTRun::RecordEvent().
G4int G4RayTrajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 85 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RayTrajectory.hh
void G4RayTrajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Definition at line 161 of file G4RayTrajectory.cc.
View newest version in sPHENIX GitHub at line 161 of file G4RayTrajectory.cc
References GetPoint(), GetPointEntries(), and positionRecord.
void G4RayTrajectory::operator delete (void * aTrajectory) inline
Definition at line 110 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RayTrajectory.hh
References rayTrajectoryAllocator().
void * G4RayTrajectory::operator new (size_t) inline
Definition at line 103 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 103 of file G4RayTrajectory.hh
References rayTrajectoryAllocator().
G4RayTrajectory& G4RayTrajectory::operator= (const G4RayTrajectory &) private
void G4RayTrajectory::ShowTrajectory (std::ostream &) const virtual
Reimplemented from G4VTrajectory.
Definition at line 158 of file G4RayTrajectory.cc.
View newest version in sPHENIX GitHub at line 158 of file G4RayTrajectory.cc
Member Data Documentation
std::vector<G4RayTrajectoryPoint*>* G4RayTrajectory::positionRecord private
Definition at line 94 of file G4RayTrajectory.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RayTrajectory.hh
Referenced by AppendStep(), G4RayTrajectory(), GetPoint(), GetPointC(), GetPointEntries(), MergeTrajectory(), and ~G4RayTrajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RayTrajectory.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RayTrajectory.cc