ECCE @ EIC Software: G4CsvNtupleManager Class Reference
G4CsvNtupleManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/csv/include/G4CsvNtupleManager.hh>
Public Member Functions
G4CsvNtupleManager (const G4AnalysisManagerState &state)
~G4CsvNtupleManager ()
Public Member Functions inherited from G4TNtupleManager< tools::wcsv::ntuple >
G4TNtupleManager (const G4AnalysisManagerState &state)
~G4TNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Types
using NtupleType = tools::wcsv::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Private Member Functions
void SetFileManager (std::shared_ptr< G4CsvFileManager > fileManager)
const std::vector
< NtupleDescriptionType * > & GetNtupleDescriptionVector () const
void SetIsCommentedHeader (G4bool isCommentedHeader)
void SetIsHippoHeader (G4bool isHippoHeader)
virtual void CreateTNtuple (NtupleDescriptionType *ntupleDescription, const G4String &name, const G4String &title) final
virtual void CreateTNtupleFromBooking (NtupleDescriptionType *ntupleDescription) final
virtual void FinishTNtuple (NtupleDescriptionType *ntupleDescription, G4bool fromBooking) final
G4bool WriteHeader (NtupleType *ntuple) const
Private Attributes
std::shared_ptr< G4CsvFileManager > fFileManager
G4bool fIsCommentedHeader
G4bool fIsHippoHeader
Friends
class G4CsvAnalysisManager
Additional Inherited Members
Protected Member Functions inherited from G4TNtupleManager< tools::wcsv::ntuple >
virtual void CreateNtuplesFromBooking ()
G4bool IsEmpty () const
virtual G4bool Reset (G4bool deleteNtuple)
virtual G4int CreateNtuple (const G4String &name, const G4String &title) override
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual void FinishNtuple (G4int ntupleId) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool AddNtupleRow (G4int ntupleId) override
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
tools::wcsv::ntuple * GetNtuple () const
tools::wcsv::ntuple * GetNtuple (G4int ntupleId) const
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const override
std::vector
< tools::wcsv::ntuple * >
::iterator BeginNtuple ()
std::vector
< tools::wcsv::ntuple * >
::iterator EndNtuple ()
std::vector
< tools::wcsv::ntuple * >
::const_iterator BeginConstNtuple () const
std::vector
< tools::wcsv::ntuple * >
::const_iterator EndConstNtuple () const
Protected Attributes inherited from G4TNtupleManager< tools::wcsv::ntuple >
std::vector
< G4TNtupleDescription
< tools::wcsv::ntuple > * > fNtupleDescriptionVector
std::vector
< tools::wcsv::ntuple * > fNtupleVector
Detailed Description
Definition at line 43 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4CsvNtupleManager.hh
Member Typedef Documentation
using G4CsvNtupleManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType> private
Definition at line 54 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 54 of file G4CsvNtupleManager.hh
using G4CsvNtupleManager::NtupleType = tools::wcsv::ntuple private
Definition at line 53 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4CsvNtupleManager.hh
Constructor & Destructor Documentation
G4CsvNtupleManager::G4CsvNtupleManager (const G4AnalysisManagerState & state) explicit
Definition at line 45 of file G4CsvNtupleManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4CsvNtupleManager.cc
G4CsvNtupleManager::~G4CsvNtupleManager ()
Definition at line 53 of file G4CsvNtupleManager.cc.
View newest version in sPHENIX GitHub at line 53 of file G4CsvNtupleManager.cc
Member Function Documentation
void G4CsvNtupleManager::CreateTNtuple (NtupleDescriptionType * ntupleDescription, const G4String & name, const G4String & title) final private virtual
Definition at line 61 of file G4CsvNtupleManager.cc.
View newest version in sPHENIX GitHub at line 61 of file G4CsvNtupleManager.cc
References G4TNtupleDescription< TNTUPLE >::fFile, fFileManager, G4TNtupleDescription< TNTUPLE >::fNtuple, G4TNtupleManager< tools::wcsv::ntuple >::fNtupleVector, and ntuple.
void G4CsvNtupleManager::CreateTNtupleFromBooking (NtupleDescriptionType * ntupleDescription) final private virtual
Definition at line 79 of file G4CsvNtupleManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4CsvNtupleManager.cc
References G4TNtupleDescription< TNTUPLE >::fFile, fFileManager, G4TNtupleDescription< TNTUPLE >::fNtuple, G4TNtupleDescription< TNTUPLE >::fNtupleBooking, G4TNtupleManager< tools::wcsv::ntuple >::fNtupleVector, G4cerr, and ntuple.
Referenced by FinishTNtuple().
void G4CsvNtupleManager::FinishTNtuple (NtupleDescriptionType * ntupleDescription, G4bool fromBooking) final private virtual
Definition at line 93 of file G4CsvNtupleManager.cc.
View newest version in sPHENIX GitHub at line 93 of file G4CsvNtupleManager.cc
References CreateTNtupleFromBooking(), fFileManager, G4TNtupleDescription< TNTUPLE >::fNtuple, G4Exception(), JustWarning, and WriteHeader().
const std::vector< G4TNtupleDescription< tools::wcsv::ntuple > * > & G4CsvNtupleManager::GetNtupleDescriptionVector () const inline private
Definition at line 94 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CsvNtupleManager.hh
References G4TNtupleManager< tools::wcsv::ntuple >::fNtupleDescriptionVector.
Referenced by G4CsvAnalysisManager::CloseNtupleFiles().
void G4CsvNtupleManager::SetFileManager (std::shared_ptr< G4CsvFileManager > fileManager) inline private
Definition at line 90 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 90 of file G4CsvNtupleManager.hh
References fFileManager.
Referenced by G4CsvAnalysisManager::G4CsvAnalysisManager().
void G4CsvNtupleManager::SetIsCommentedHeader (G4bool isCommentedHeader) inline private
Definition at line 97 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 97 of file G4CsvNtupleManager.hh
References fIsCommentedHeader.
void G4CsvNtupleManager::SetIsHippoHeader (G4bool isHippoHeader) inline private
Definition at line 100 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4CsvNtupleManager.hh
References fIsHippoHeader.
G4bool G4CsvNtupleManager::WriteHeader (NtupleType * ntuple) const private
Definition at line 117 of file G4CsvNtupleManager.cc.
View newest version in sPHENIX GitHub at line 117 of file G4CsvNtupleManager.cc
References fIsCommentedHeader, fIsHippoHeader, and G4cout.
Referenced by FinishTNtuple().
Friends And Related Function Documentation
friend class G4CsvAnalysisManager friend
Definition at line 45 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 45 of file G4CsvNtupleManager.hh
Member Data Documentation
std::shared_ptr<G4CsvFileManager> G4CsvNtupleManager::fFileManager private
Definition at line 82 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CsvNtupleManager.hh
Referenced by CreateTNtuple(), CreateTNtupleFromBooking(), FinishTNtuple(), and SetFileManager().
G4bool G4CsvNtupleManager::fIsCommentedHeader private
Definition at line 83 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4CsvNtupleManager.hh
Referenced by SetIsCommentedHeader(), and WriteHeader().
G4bool G4CsvNtupleManager::fIsHippoHeader private
Definition at line 84 of file G4CsvNtupleManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4CsvNtupleManager.hh
Referenced by SetIsHippoHeader(), and WriteHeader().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/csv/include/G4CsvNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/csv/src/G4CsvNtupleManager.cc