ECCE @ EIC Software: G4RPGPionSuppression Class Reference
G4RPGPionSuppression Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGPionSuppression.hh>
Public Member Functions
G4RPGPionSuppression ()
G4bool ReactionStage (const G4HadProjectile *, G4ReactionProduct &, G4bool &, const G4DynamicParticle *, G4ReactionProduct &, G4bool &, const G4Nucleus &, G4ReactionProduct &, G4FastVector< G4ReactionProduct, 256 > &, G4int &, G4bool, G4ReactionProduct &)
Public Member Functions inherited from G4RPGReaction
G4RPGReaction ()
virtual ~G4RPGReaction ()
G4bool ReactionStage (const G4HadProjectile *, G4ReactionProduct &, G4bool &, const G4DynamicParticle *, G4ReactionProduct &, G4bool &, const G4Nucleus &, G4ReactionProduct &, G4FastVector< G4ReactionProduct, 256 > &, G4int &, G4bool, G4ReactionProduct &)
void AddBlackTrackParticles (const G4double, const G4int, const G4double, const G4int, const G4ReactionProduct &, G4int, G4int, const G4Nucleus &, G4FastVector< G4ReactionProduct, 256 > &, G4int &)
G4double GenerateNBodyEvent (const G4double totalEnergy, const G4bool constantCrossSection, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
G4double GenerateNBodyEventT (const G4double totalEnergy, const G4bool constantCrossSection, std::vector< G4ReactionProduct * > &list)
void NuclearReaction (G4FastVector< G4ReactionProduct, 4 > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, const G4Nucleus &aNucleus, const G4double theAtomicMass, const G4double *massVec)
Additional Inherited Members
Protected Member Functions inherited from G4RPGReaction
void Rotate (const G4double numberofFinalStateNucleons, const G4ThreeVector &temp, const G4ReactionProduct &modifiedOriginal, const G4HadProjectile *originalIncident, const G4Nucleus &targetNucleus, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
void Defs1 (const G4ReactionProduct &modifiedOriginal, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
std::pair< G4int, G4int > GetFinalStateNucleons (const G4DynamicParticle *originalTarget, const G4FastVector< G4ReactionProduct, 256 > &vec, const G4int &vecLen)
void MomentumCheck (const G4ReactionProduct &modifiedOriginal, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
G4double normal ()
G4ThreeVector Isotropic (const G4double &)
Detailed Description
Definition at line 47 of file G4RPGPionSuppression.hh.
View newest version in sPHENIX GitHub at line 47 of file G4RPGPionSuppression.hh
Constructor & Destructor Documentation
G4RPGPionSuppression::G4RPGPionSuppression ()
Definition at line 36 of file G4RPGPionSuppression.cc.
View newest version in sPHENIX GitHub at line 36 of file G4RPGPionSuppression.cc
Member Function Documentation
G4bool G4RPGPionSuppression::ReactionStage (const G4HadProjectile * , G4ReactionProduct & modifiedOriginal, G4bool & incidentHasChanged, const G4DynamicParticle * , G4ReactionProduct & targetParticle, G4bool & targetHasChanged, const G4Nucleus & targetNucleus, G4ReactionProduct & currentParticle, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen, G4bool , G4ReactionProduct &)
Definition at line 41 of file G4RPGPionSuppression.cc.
View newest version in sPHENIX GitHub at line 41 of file G4RPGPionSuppression.cc
References G4AntiLambda::AntiLambda(), G4AntiNeutron::AntiNeutron(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), G4UniformRand, G4Nucleus::GetA_asInt(), G4ReactionProduct::GetDefinition(), G4ReactionProduct::GetMass(), G4ParticleDefinition::GetPDGMass(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4Proton::Proton(), and G4ReactionProduct::SetDefinitionAndUpdateE().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGPionSuppression.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/src/G4RPGPionSuppression.cc