ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/run/pymodG4run.cc File Reference
pymodG4run.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4RunManager ()
void export_G4RunManagerKernel ()
void export_G4Run ()
void export_G4UserRunAction ()
void export_G4VUserPrimaryGeneratorAction ()
void export_G4VUserDetectorConstruction ()
void export_G4VUserPhysicsList ()
void export_G4VModularPhysicsList ()
void export_G4VPhysicsConstructor ()
BOOST_PYTHON_MODULE (G4run)
Function Documentation
BOOST_PYTHON_MODULE (G4run)
Definition at line 49 of file pymodG4run.cc.
View newest version in sPHENIX GitHub at line 49 of file pymodG4run.cc
References export_G4Run(), export_G4RunManager(), export_G4RunManagerKernel(), export_G4UserRunAction(), export_G4VModularPhysicsList(), export_G4VPhysicsConstructor(), export_G4VUserDetectorConstruction(), export_G4VUserPhysicsList(), and export_G4VUserPrimaryGeneratorAction().
void export_G4Run ()
Definition at line 41 of file pyG4Run.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4Run.cc
References G4Run::GetNumberOfEvent(), G4Run::GetNumberOfEventToBeProcessed(), G4Run::GetRunID(), G4Run::SetNumberOfEventToBeProcessed(), and G4Run::SetRunID().
Referenced by BOOST_PYTHON_MODULE().
void export_G4RunManager ()
Definition at line 102 of file pyG4RunManager.cc.
View newest version in sPHENIX GitHub at line 102 of file pyG4RunManager.cc
References G4RunManager::AbortEvent(), G4RunManager::AbortRun(), G4RunManager::BeamOn(), G4RunManager::DefineWorldVolume(), pyG4RunManager::f1_DumpRegion, pyG4RunManager::f1_SetUserAction, pyG4RunManager::f1_SetUserInitialization, pyG4RunManager::f2_DumpRegion, pyG4RunManager::f2_SetUserAction, pyG4RunManager::f2_SetUserInitialization, pyG4RunManager::f3_SetUserAction, pyG4RunManager::f4_SetUserAction, pyG4RunManager::f5_SetUserAction, pyG4RunManager::f6_SetUserAction, G4RunManager::GeometryHasBeenModified(), G4RunManager::GetCurrentEvent(), G4RunManager::GetCurrentRun(), G4RunManager::GetGeometryToBeOptimized(), G4RunManager::GetRandomNumberStore(), G4RunManager::GetRandomNumberStoreDir(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4RunManager::GetUserEventAction(), G4RunManager::GetUserPhysicsList(), G4RunManager::GetUserPrimaryGeneratorAction(), G4RunManager::GetUserRunAction(), G4RunManager::GetUserStackingAction(), G4RunManager::GetUserSteppingAction(), G4RunManager::GetUserTrackingAction(), G4RunManager::GetVerboseLevel(), G4RunManager::GetVersionString(), G4RunManager::Initialize(), G4RunManager::PhysicsHasBeenModified(), G4RunManager::RestoreRandomNumberStatus(), G4RunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisRun(), G4RunManager::SetRandomNumberStore(), G4RunManager::SetRandomNumberStoreDir(), G4RunManager::SetRunIDCounter(), and G4RunManager::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4RunManagerKernel ()
Definition at line 52 of file pyG4RunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 52 of file pyG4RunManagerKernel.cc
References G4RunManagerKernel::GetRunManagerKernel(), and G4RunManagerKernel::RunInitialization().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UserRunAction ()
Definition at line 63 of file pyG4UserRunAction.cc.
View newest version in sPHENIX GitHub at line 63 of file pyG4UserRunAction.cc
References CB_G4UserRunAction::BeginOfRunAction(), G4UserRunAction::BeginOfRunAction(), CB_G4UserRunAction::EndOfRunAction(), and G4UserRunAction::EndOfRunAction().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VModularPhysicsList ()
Definition at line 65 of file pyG4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 65 of file pyG4VModularPhysicsList.cc
References G4VModularPhysicsList::ConstructParticle(), G4VModularPhysicsList::ConstructProcess(), pyG4VModularPhysicsList::f1_GetPhysics, pyG4VModularPhysicsList::f2_GetPhysics, G4VModularPhysicsList::RegisterPhysics(), and G4VUserPhysicsList::SetCuts().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VPhysicsConstructor ()
Definition at line 71 of file pyG4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 71 of file pyG4VPhysicsConstructor.cc
References G4VPhysicsConstructor::ConstructParticle(), G4VPhysicsConstructor::ConstructProcess(), G4VPhysicsConstructor::GetPhysicsName(), G4VPhysicsConstructor::GetVerboseLevel(), G4VPhysicsConstructor::SetPhysicsName(), and G4VPhysicsConstructor::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VUserDetectorConstruction ()
Definition at line 58 of file pyG4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 58 of file pyG4VUserDetectorConstruction.cc
References G4VUserDetectorConstruction::Construct().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VUserPhysicsList ()
Definition at line 88 of file pyG4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 88 of file pyG4VUserPhysicsList.cc
References G4VUserPhysicsList::ConstructParticle(), G4VUserPhysicsList::ConstructProcess(), G4VUserPhysicsList::DumpCutValuesTable(), G4VUserPhysicsList::DumpCutValuesTableIfRequested(), G4VUserPhysicsList::DumpList(), pyG4VUserPhysicsList::f1_SetCutValue, pyG4VUserPhysicsList::f1_SetParticleCuts, pyG4VUserPhysicsList::f2_SetCutValue, pyG4VUserPhysicsList::f2_SetParticleCuts, G4VUserPhysicsList::GetApplyCuts(), G4VUserPhysicsList::GetDefaultCutValue(), G4VUserPhysicsList::GetPhysicsTableDirectory(), G4VUserPhysicsList::GetVerboseLevel(), G4VUserPhysicsList::IsPhysicsTableRetrieved(), G4VUserPhysicsList::IsStoredInAscii(), G4VUserPhysicsList::ResetStoredInAscii(), G4VUserPhysicsList::SetCuts(), G4VUserPhysicsList::SetCutsForRegion(), G4VUserPhysicsList::SetCutsWithDefault(), G4VUserPhysicsList::SetDefaultCutValue(), G4VUserPhysicsList::SetStoredInAscii(), G4VUserPhysicsList::SetVerboseLevel(), and G4VUserPhysicsList::StorePhysicsTable().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VUserPrimaryGeneratorAction ()
Definition at line 57 of file pyG4VUserPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 57 of file pyG4VUserPrimaryGeneratorAction.cc
References G4VUserPrimaryGeneratorAction::GeneratePrimaries().
Referenced by BOOST_PYTHON_MODULE().