ECCE @ EIC Software: G4CascadeColliderBase Class Reference
G4CascadeColliderBase Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeColliderBase.hh>
Public Member Functions
G4CascadeColliderBase (const G4String &name, G4int verbose=0)
virtual ~G4CascadeColliderBase ()
virtual void rescatter (G4InuclParticle *, G4KineticTrackVector *, G4V3DNucleus *, G4CollisionOutput &)
virtual void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)=0
Protected Member Functions
virtual G4bool useEPCollider (G4InuclParticle *bullet, G4InuclParticle *target) const
virtual G4bool inelasticInteractionPossible (G4InuclParticle *bullet, G4InuclParticle *target, G4double ekin) const
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &fragment, G4CollisionOutput &output)
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, const std::vector< G4InuclElementaryParticle > &particles)
Protected Member Functions inherited from G4VCascadeCollider
virtual void setName (const G4String &name)
Protected Attributes
G4InteractionCase interCase
G4CascadeCheckBalance * balance
Protected Attributes inherited from G4VCascadeCollider
G4String theName
G4int verboseLevel
Private Member Functions
G4CascadeColliderBase (const G4CascadeColliderBase &)
G4CascadeColliderBase & operator= (const G4CascadeColliderBase &)
Detailed Description
Definition at line 62 of file G4CascadeColliderBase.hh.
View newest version in sPHENIX GitHub at line 62 of file G4CascadeColliderBase.hh
Constructor & Destructor Documentation
G4CascadeColliderBase::G4CascadeColliderBase (const G4String & name, G4int verbose = 0)
Definition at line 57 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 57 of file G4CascadeColliderBase.cc
References balance, and G4CascadeParameters::checkConservation().
G4CascadeColliderBase::~G4CascadeColliderBase () virtual
Definition at line 63 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 63 of file G4CascadeColliderBase.cc
References balance.
G4CascadeColliderBase::G4CascadeColliderBase (const G4CascadeColliderBase &) private
Member Function Documentation
G4bool G4CascadeColliderBase::inelasticInteractionPossible (G4InuclParticle * bullet, G4InuclParticle * target, G4double ekin) const protected virtual
Definition at line 85 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 85 of file G4CascadeColliderBase.cc
References ab, Acts::Test::at, G4InuclSpecialFunctions::G4cbrt(), G4cout, G4endl, G4InuclNuclei::getA(), G4InuclParticle::getCharge(), G4InuclNuclei::getZ(), G4VCascadeCollider::theName, useEPCollider(), and G4VCascadeCollider::verboseLevel.
Referenced by G4InuclCollider::collide().
G4CascadeColliderBase& G4CascadeColliderBase::operator= (const G4CascadeColliderBase &) private
virtual void G4CascadeColliderBase::rescatter (G4InuclParticle * , G4KineticTrackVector * , G4V3DNucleus * , G4CollisionOutput &) inline virtual
Reimplemented in G4IntraNucleiCascader, and G4InuclCollider.
Definition at line 68 of file G4CascadeColliderBase.hh.
View newest version in sPHENIX GitHub at line 68 of file G4CascadeColliderBase.hh
void G4CascadeColliderBase::setVerboseLevel (G4int verbose = 0) virtual
Reimplemented from G4VCascadeCollider.
Reimplemented in G4IntraNucleiCascader, G4InuclCollider, and G4LightTargetCollider.
Definition at line 67 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 67 of file G4CascadeColliderBase.cc
References balance, and G4VCascadeCollider::setVerboseLevel().
Referenced by G4LightTargetCollider::setVerboseLevel(), G4InuclCollider::setVerboseLevel(), and G4IntraNucleiCascader::setVerboseLevel().
G4bool G4CascadeColliderBase::useEPCollider (G4InuclParticle * bullet, G4InuclParticle * target) const protected virtual
Definition at line 75 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 75 of file G4CascadeColliderBase.cc
Referenced by G4LightTargetCollider::collide(), G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), and inelasticInteractionPossible().
G4bool G4CascadeColliderBase::validateOutput (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & output) protected virtual
Definition at line 123 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 123 of file G4CascadeColliderBase.cc
References balance, G4CascadeCheckBalance::collide(), G4cout, G4endl, G4CascadeCheckBalance::okay(), G4CollisionOutput::printCollisionOutput(), G4VCascadeCollider::setVerboseLevel(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by G4ElementaryParticleCollider::collide(), and G4InuclCollider::deexcite().
G4bool G4CascadeColliderBase::validateOutput (const G4Fragment & fragment, G4CollisionOutput & output) protected virtual
Definition at line 139 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 139 of file G4CascadeColliderBase.cc
References balance, G4CascadeCheckBalance::collide(), G4cout, G4endl, G4CascadeCheckBalance::okay(), G4VCascadeCollider::setVerboseLevel(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
G4bool G4CascadeColliderBase::validateOutput (G4InuclParticle * bullet, G4InuclParticle * target, const std::vector< G4InuclElementaryParticle > & particles) protected virtual
Definition at line 151 of file G4CascadeColliderBase.cc.
View newest version in sPHENIX GitHub at line 151 of file G4CascadeColliderBase.cc
References balance, G4CascadeCheckBalance::collide(), G4cout, G4endl, G4CascadeCheckBalance::okay(), G4VCascadeCollider::setVerboseLevel(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Member Data Documentation
G4CascadeCheckBalance* G4CascadeColliderBase::balance protected
Definition at line 88 of file G4CascadeColliderBase.hh.
View newest version in sPHENIX GitHub at line 88 of file G4CascadeColliderBase.hh
Referenced by G4CascadeColliderBase(), setVerboseLevel(), validateOutput(), and ~G4CascadeColliderBase().
G4InteractionCase G4CascadeColliderBase::interCase protected
Definition at line 76 of file G4CascadeColliderBase.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CascadeColliderBase.hh
Referenced by G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4IntraNucleiCascader::finishCascade(), G4IntraNucleiCascader::generateCascade(), G4IntraNucleiCascader::initialize(), G4IntraNucleiCascader::newCascade(), G4InuclCollider::photonuclearOkay(), G4ElementaryParticleCollider::pionNucleonAbsorption(), and G4IntraNucleiCascader::setupCascade().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeColliderBase.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeColliderBase.cc