ECCE @ EIC Software: CLHEP::RandGaussQ Class Reference
CLHEP::RandGaussQ Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGaussQ.h>
Public Member Functions
RandGaussQ (HepRandomEngine &anEngine, double mean=0.0, double stdDev=1.0)
RandGaussQ (HepRandomEngine *anEngine, double mean=0.0, double stdDev=1.0)
virtual ~RandGaussQ ()
double fire ()
double fire (double mean, double stdDev)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double mean, double stdDev)
virtual double operator() ()
virtual double operator() (double mean, double stdDev)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::RandGauss
RandGauss (HepRandomEngine &anEngine, double mean=0.0, double stdDev=1.0)
RandGauss (HepRandomEngine *anEngine, double mean=0.0, double stdDev=1.0)
virtual ~RandGauss ()
double fire ()
double fire (double mean, double stdDev)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double mean, double stdDev)
bool getF () const
void setF (bool val)
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double mean, double stdDev)
static void shootArray (const int size, double *vect, double mean=0.0, double stdDev=1.0)
static double shoot (HepRandomEngine *anotherEngine)
static double shoot (HepRandomEngine *anotherEngine, double mean, double stdDev)
static void shootArray (HepRandomEngine *anotherEngine, const int size, double *vect, double mean=0.0, double stdDev=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::RandGauss
static double shoot ()
static double shoot (double mean, double stdDev)
static void shootArray (const int size, double *vect, double mean=0.0, double stdDev=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double mean, double stdDev)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double mean=0.0, double stdDev=1.0)
static std::string distributionName ()
static bool getFlag ()
static void setFlag (bool val)
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Protected Member Functions
static double transformQuick (double r)
static double transformSmall (double r)
Static Protected Member Functions inherited from CLHEP::RandGauss
static double getVal ()
static void setVal (double nextVal)
Additional Inherited Members
Protected Member Functions inherited from CLHEP::RandGauss
double normal ()
Protected Attributes inherited from CLHEP::RandGauss
double defaultMean
double defaultStdDev
std::shared_ptr< HepRandomEngine > localEngine
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 30 of file RandGaussQ.h.
View newest version in sPHENIX GitHub at line 30 of file RandGaussQ.h
Constructor & Destructor Documentation
CLHEP::RandGaussQ::RandGaussQ (HepRandomEngine & anEngine, double mean = 0.0, double stdDev = 1.0) inline
CLHEP::RandGaussQ::RandGaussQ (HepRandomEngine * anEngine, double mean = 0.0, double stdDev = 1.0) inline
CLHEP::RandGaussQ::~RandGaussQ () virtual
Definition at line 24 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 24 of file RandGaussQ.cc
Member Function Documentation
static std::string CLHEP::RandGaussQ::distributionName () inline static
Definition at line 102 of file RandGaussQ.h.
View newest version in sPHENIX GitHub at line 102 of file RandGaussQ.h
HepRandomEngine & CLHEP::RandGaussQ::engine () virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 22 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 22 of file RandGaussQ.cc
References CLHEP::RandGauss::engine().
double CLHEP::RandGaussQ::fire () inline
Referenced by fireArray().
double CLHEP::RandGaussQ::fire (double mean, double stdDev) inline
void CLHEP::RandGaussQ::fireArray (const int size, double * vect)
Definition at line 50 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 50 of file RandGaussQ.cc
References CLHEP::RandGauss::defaultMean, CLHEP::RandGauss::defaultStdDev, fire(), and v.
void CLHEP::RandGaussQ::fireArray (const int size, double * vect, double mean, double stdDev)
Definition at line 56 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 56 of file RandGaussQ.cc
References fire(), and v.
std::istream & CLHEP::RandGaussQ::get (std::istream & is) virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 173 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 173 of file RandGaussQ.cc
References CLHEP::RandGauss::get(), and name().
std::string CLHEP::RandGaussQ::name () const virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 21 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 21 of file RandGaussQ.cc
Referenced by get(), and put().
double CLHEP::RandGaussQ::operator() () virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 27 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 27 of file RandGaussQ.cc
References CLHEP::RandGauss::defaultMean, CLHEP::RandGauss::defaultStdDev, CLHEP::RandGauss::localEngine, and transformQuick().
double CLHEP::RandGaussQ::operator() (double mean, double stdDev) virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 31 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 31 of file RandGaussQ.cc
References CLHEP::RandGauss::localEngine, and transformQuick().
std::ostream & CLHEP::RandGaussQ::put (std::ostream & os) const virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 165 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 165 of file RandGaussQ.cc
References name(), gammaraytel::pr, and CLHEP::RandGauss::put().
static double CLHEP::RandGaussQ::shoot () inline static
Referenced by CLHEP::RandPoissonQ::poissonDeviateQuick(), and shootArray().
static double CLHEP::RandGaussQ::shoot (double mean, double stdDev) inline static
static double CLHEP::RandGaussQ::shoot (HepRandomEngine * anotherEngine) inline static
static double CLHEP::RandGaussQ::shoot (HepRandomEngine * anotherEngine, double mean, double stdDev) inline static
void CLHEP::RandGaussQ::shootArray (const int size, double * vect, double mean = 0.0, double stdDev = 1.0) static
Definition at line 35 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 35 of file RandGaussQ.cc
References shoot(), and v.
void CLHEP::RandGaussQ::shootArray (HepRandomEngine * anotherEngine, const int size, double * vect, double mean = 0.0, double stdDev = 1.0) static
Definition at line 42 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 42 of file RandGaussQ.cc
References shoot(), and v.
double CLHEP::RandGaussQ::transformQuick (double r) static protected
Definition at line 91 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 91 of file RandGaussQ.cc
References dx, CLHEP::gaussTables, int(), r, sign(), Table0offset, Table0scale, Table0size, Table0step, Table1offset, Table1size, Table1step, transformSmall(), and y1.
Referenced by operator()().
double CLHEP::RandGaussQ::transformSmall (double r) static protected
Definition at line 124 of file RandGaussQ.cc.
View newest version in sPHENIX GitHub at line 124 of file RandGaussQ.cc
References eps, s1, CLHEP::twopi, and v.
Referenced by transformQuick().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGaussQ.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandGaussQ.cc