ECCE @ EIC Software: G4FTFAnnihilation Class Reference
G4FTFAnnihilation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFAnnihilation.hh>
Classes
struct CommonVariables
Public Member Functions
G4FTFAnnihilation ()
virtual ~G4FTFAnnihilation ()
virtual G4bool Annihilate (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4VSplitableHadron *&AdditionalString, G4FTFParameters *theParameters) const
Private Member Functions
G4FTFAnnihilation (const G4FTFAnnihilation &right)
const G4FTFAnnihilation & operator= (const G4FTFAnnihilation &right)
G4bool operator== (const G4FTFAnnihilation &right) const
G4bool operator!= (const G4FTFAnnihilation &right) const
G4bool Create3QuarkAntiQuarkStrings (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4VSplitableHadron *&AdditionalString, G4FTFParameters *theParameters, CommonVariables &common) const
G4int Create1DiquarkAntiDiquarkString (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, CommonVariables &common) const
G4int Create2QuarkAntiQuarkStrings (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters, CommonVariables &common) const
G4bool Create1QuarkAntiQuarkString (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters, CommonVariables &common) const
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
G4double ChooseX (G4double Alpha, G4double Beta) const
void UnpackBaryon (G4int IdPDG, G4int &Q1, G4int &Q2, G4int &Q3) const
Detailed Description
Definition at line 49 of file G4FTFAnnihilation.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FTFAnnihilation.hh
Constructor & Destructor Documentation
G4FTFAnnihilation::G4FTFAnnihilation ()
Definition at line 76 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FTFAnnihilation.cc
G4FTFAnnihilation::~G4FTFAnnihilation () virtual
Definition at line 81 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 81 of file G4FTFAnnihilation.cc
G4FTFAnnihilation::G4FTFAnnihilation (const G4FTFAnnihilation & right) private
Definition at line 1067 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1067 of file G4FTFAnnihilation.cc
Member Function Documentation
G4bool G4FTFAnnihilation::Annihilate (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4VSplitableHadron *& AdditionalString, G4FTFParameters * theParameters) const virtual
Definition at line 86 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 86 of file G4FTFAnnihilation.cc
References G4FTFAnnihilation::CommonVariables::AQ, CLHEP::HepLorentzVector::boostVector(), common(), Create1DiquarkAntiDiquarkString(), Create1QuarkAntiQuarkString(), Create2QuarkAntiQuarkStrings(), Create3QuarkAntiQuarkStrings(), G4cout, G4endl, G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4Pow::GetInstance(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, CLHEP::HepLorentzRotation::inverse(), CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, pi, G4Pow::powA(), G4FTFAnnihilation::CommonVariables::Pprojectile, G4FTFAnnihilation::CommonVariables::Ptarget, G4FTFAnnihilation::CommonVariables::Q, G4FTFAnnihilation::CommonVariables::RandomRotation, G4FTFAnnihilation::CommonVariables::RotateStrings, CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4FTFAnnihilation::CommonVariables::S, G4VSplitableHadron::SetStatus(), sqr(), G4FTFAnnihilation::CommonVariables::SqrtS, G4FTFAnnihilation::CommonVariables::toLab, and UnpackBaryon().
Referenced by G4FTFModel::ExciteParticipants().
G4double G4FTFAnnihilation::ChooseX (G4double Alpha, G4double Beta) const private
Definition at line 1027 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1027 of file G4FTFAnnihilation.cc
G4int G4FTFAnnihilation::Create1DiquarkAntiDiquarkString (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 553 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 553 of file G4FTFAnnihilation.cc
References kdfinder::abs(), G4FTFAnnihilation::CommonVariables::AQ, G4cout, G4endl, G4VSplitableHadron::GetNextAntiParton(), G4VSplitableHadron::GetNextParton(), G4VSplitableHadron::GetPosition(), G4VSplitableHadron::GetTimeOfCreation(), G4VSplitableHadron::IncrementCollisionCount(), G4FTFAnnihilation::CommonVariables::Pprojectile, G4FTFAnnihilation::CommonVariables::Q, G4FTFAnnihilation::CommonVariables::RandomRotation, G4FTFAnnihilation::CommonVariables::RotateStrings, G4VSplitableHadron::Set4Momentum(), G4Parton::Set4Momentum(), CLHEP::HepLorentzVector::setE(), G4VSplitableHadron::SetFirstParton(), G4VSplitableHadron::SetPosition(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SetSecondParton(), G4VSplitableHadron::SetStatus(), G4VSplitableHadron::SetTimeOfCreation(), G4VSplitableHadron::SplitUp(), G4FTFAnnihilation::CommonVariables::SqrtS, G4FTFAnnihilation::CommonVariables::toLab, and CLHEP::HepLorentzVector::transform().
Referenced by Annihilate().
G4bool G4FTFAnnihilation::Create1QuarkAntiQuarkString (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 906 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 906 of file G4FTFAnnihilation.cc
References kdfinder::abs(), G4FTFAnnihilation::CommonVariables::AQ, G4ParticleTable::FindParticle(), G4cout, G4endl, G4UniformRand, G4VSplitableHadron::GetNextAntiParton(), G4VSplitableHadron::GetNextParton(), G4ParticleTable::GetParticleTable(), G4VSplitableHadron::GetPosition(), G4VSplitableHadron::GetTimeOfCreation(), G4VSplitableHadron::IncrementCollisionCount(), G4FTFAnnihilation::CommonVariables::Pprojectile, G4FTFAnnihilation::CommonVariables::Q, G4FTFAnnihilation::CommonVariables::RandomRotation, G4FTFAnnihilation::CommonVariables::RotateStrings, G4VSplitableHadron::Set4Momentum(), G4Parton::Set4Momentum(), G4VSplitableHadron::SetDefinition(), CLHEP::HepLorentzVector::setE(), G4VSplitableHadron::SetFirstParton(), G4VSplitableHadron::SetPosition(), G4FTFParameters::SetProjMinDiffMass(), G4FTFParameters::SetProjMinNonDiffMass(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SetSecondParton(), G4VSplitableHadron::SetStatus(), G4VSplitableHadron::SetTimeOfCreation(), G4VSplitableHadron::SplitUp(), G4FTFAnnihilation::CommonVariables::SqrtS, G4FTFAnnihilation::CommonVariables::toLab, and CLHEP::HepLorentzVector::transform().
Referenced by Annihilate().
G4int G4FTFAnnihilation::Create2QuarkAntiQuarkStrings (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 646 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 646 of file G4FTFAnnihilation.cc
References kdfinder::abs(), G4FTFAnnihilation::CommonVariables::AQ, CLHEP::HepLorentzVector::e(), G4ParticleTable::FindParticle(), G4cout, G4endl, G4UniformRand, GaussianPt(), G4ParticleTable::GetParticleTable(), G4VSplitableHadron::GetPosition(), G4VSplitableHadron::GetTimeOfCreation(), CLHEP::Hep3Vector::getZ(), G4VSplitableHadron::IncrementCollisionCount(), CLHEP::Hep3Vector::mag2(), pi, G4FTFAnnihilation::CommonVariables::Pprojectile, G4FTFAnnihilation::CommonVariables::Ptarget, CLHEP::HepLorentzVector::pz(), G4FTFAnnihilation::CommonVariables::Q, r, G4FTFAnnihilation::CommonVariables::RandomRotation, CLHEP::HepLorentzVector::rapidity(), G4FTFAnnihilation::CommonVariables::RotateStrings, G4FTFAnnihilation::CommonVariables::S, G4VSplitableHadron::Set4Momentum(), G4VSplitableHadron::SetDefinition(), G4VSplitableHadron::SetFirstParton(), G4VSplitableHadron::SetPosition(), G4FTFParameters::SetProjMinDiffMass(), G4FTFParameters::SetProjMinNonDiffMass(), G4VSplitableHadron::SetSecondParton(), G4VSplitableHadron::SetStatus(), G4FTFParameters::SetTarMinDiffMass(), G4FTFParameters::SetTarMinNonDiffMass(), G4VSplitableHadron::SetTimeOfCreation(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4VSplitableHadron::SplitUp(), sqr(), G4FTFAnnihilation::CommonVariables::SqrtS, tmp, G4FTFAnnihilation::CommonVariables::toLab, CLHEP::HepLorentzVector::transform(), w, and x.
Referenced by Annihilate().
G4bool G4FTFAnnihilation::Create3QuarkAntiQuarkStrings (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4VSplitableHadron *& AdditionalString, G4FTFParameters * theParameters, G4FTFAnnihilation::CommonVariables & common) const private
Definition at line 282 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 282 of file G4FTFAnnihilation.cc
References kdfinder::abs(), G4FTFAnnihilation::CommonVariables::AQ, CLHEP::HepLorentzVector::e(), G4ParticleTable::FindParticle(), G4cout, G4endl, G4UniformRand, GaussianPt(), G4ParticleTable::GetParticleTable(), G4VSplitableHadron::GetPosition(), G4VSplitableHadron::GetTimeOfCreation(), CLHEP::Hep3Vector::getZ(), G4VSplitableHadron::IncrementCollisionCount(), CLHEP::Hep3Vector::mag2(), pi, G4FTFAnnihilation::CommonVariables::Pprojectile, G4FTFAnnihilation::CommonVariables::Ptarget, CLHEP::HepLorentzVector::pz(), G4FTFAnnihilation::CommonVariables::Q, r1, r2, G4FTFAnnihilation::CommonVariables::RandomRotation, CLHEP::HepLorentzVector::rapidity(), G4FTFAnnihilation::CommonVariables::RotateStrings, G4FTFAnnihilation::CommonVariables::S, G4VSplitableHadron::Set4Momentum(), G4VSplitableHadron::SetDefinition(), G4VSplitableHadron::SetFirstParton(), G4VSplitableHadron::SetPosition(), G4FTFParameters::SetProjMinDiffMass(), G4FTFParameters::SetProjMinNonDiffMass(), G4VSplitableHadron::SetSecondParton(), G4VSplitableHadron::SetStatus(), G4FTFParameters::SetTarMinDiffMass(), G4FTFParameters::SetTarMinNonDiffMass(), G4VSplitableHadron::SetTimeOfCreation(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4VSplitableHadron::SplitUp(), sqr(), G4FTFAnnihilation::CommonVariables::SqrtS, tmp, G4FTFAnnihilation::CommonVariables::toLab, CLHEP::HepLorentzVector::transform(), w, x1, x2, and x3.
Referenced by Annihilate().
G4ThreeVector G4FTFAnnihilation::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 1038 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1038 of file G4FTFAnnihilation.cc
References G4Exp(), G4Log(), G4UniformRand, phi, and twopi.
Referenced by Create2QuarkAntiQuarkStrings(), and Create3QuarkAntiQuarkStrings().
G4bool G4FTFAnnihilation::operator!= (const G4FTFAnnihilation & right) const private
Definition at line 1091 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1091 of file G4FTFAnnihilation.cc
const G4FTFAnnihilation & G4FTFAnnihilation::operator= (const G4FTFAnnihilation & right) private
Definition at line 1075 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1075 of file G4FTFAnnihilation.cc
G4bool G4FTFAnnihilation::operator== (const G4FTFAnnihilation & right) const private
Definition at line 1083 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1083 of file G4FTFAnnihilation.cc
void G4FTFAnnihilation::UnpackBaryon (G4int IdPDG, G4int & Q1, G4int & Q2, G4int & Q3) const private
Definition at line 1055 of file G4FTFAnnihilation.cc.
View newest version in sPHENIX GitHub at line 1055 of file G4FTFAnnihilation.cc
References kdfinder::abs().
Referenced by Annihilate().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFAnnihilation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4FTFAnnihilation.cc