ECCE @ EIC Software: G4VEvaporationChannel Class Reference
G4VEvaporationChannel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4VEvaporationChannel.hh>
Public Member Functions
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual G4double GetEmissionProbability (G4Fragment *theNucleus)=0
virtual void Initialise ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4Fragment * EmittedFragment (G4Fragment *theNucleus)
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void Dump () const
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Protected Attributes
G4int OPTxs
G4bool useSICB
Private Member Functions
G4VEvaporationChannel (const G4VEvaporationChannel &right)
const G4VEvaporationChannel & operator= (const G4VEvaporationChannel &right)
G4bool operator== (const G4VEvaporationChannel &right) const
G4bool operator!= (const G4VEvaporationChannel &right) const
Detailed Description
Definition at line 49 of file G4VEvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VEvaporationChannel.hh
Constructor & Destructor Documentation
G4VEvaporationChannel::G4VEvaporationChannel (const G4String & aName = "") explicit
Definition at line 38 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VEvaporationChannel.cc
G4VEvaporationChannel::~G4VEvaporationChannel () virtual
Definition at line 44 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VEvaporationChannel.cc
G4VEvaporationChannel::G4VEvaporationChannel (const G4VEvaporationChannel & right) private
Member Function Documentation
G4bool G4VEvaporationChannel::BreakUpChain (G4FragmentVector * theResult, G4Fragment * theNucleus) virtual
Reimplemented in G4PhotonEvaporation, and G4UnstableFragmentBreakUp.
Definition at line 66 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4VEvaporationChannel.cc
Referenced by BreakUpFragment().
G4FragmentVector * G4VEvaporationChannel::BreakUpFragment (G4Fragment * theNucleus) inline
Definition at line 106 of file G4VEvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VEvaporationChannel.hh
References BreakUpChain().
Referenced by G4NeutronRadCapture::ApplyYourself().
void G4VEvaporationChannel::Dump () const virtual
Reimplemented in G4GEMChannel, and G4GEMChannelVI.
Definition at line 71 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 71 of file G4VEvaporationChannel.cc
G4Fragment * G4VEvaporationChannel::EmittedFragment (G4Fragment * theNucleus) virtual
Reimplemented in G4PhotonEvaporation, G4GEMChannel, G4EvaporationChannel, G4CompetitiveFission, and G4GEMChannelVI.
Definition at line 61 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VEvaporationChannel.cc
virtual G4double G4VEvaporationChannel::GetEmissionProbability (G4Fragment * theNucleus) pure virtual
Implemented in G4PhotonEvaporation, G4UnstableFragmentBreakUp, G4GEMChannel, G4EvaporationChannel, G4CompetitiveFission, and G4GEMChannelVI.
G4double G4VEvaporationChannel::GetLifeTime (G4Fragment * theNucleus) virtual
Definition at line 50 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VEvaporationChannel.cc
void G4VEvaporationChannel::Initialise () virtual
Reimplemented in G4PhotonEvaporation, and G4EvaporationChannel.
Definition at line 47 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VEvaporationChannel.cc
Referenced by G4EvaporationChannel::Initialise(), and G4NeutronRadCapture::InitialiseModel().
G4bool G4VEvaporationChannel::operator!= (const G4VEvaporationChannel & right) const private
const G4VEvaporationChannel& G4VEvaporationChannel::operator= (const G4VEvaporationChannel & right) private
G4bool G4VEvaporationChannel::operator== (const G4VEvaporationChannel & right) const private
void G4VEvaporationChannel::RDMForced (G4bool) virtual
Reimplemented in G4PhotonEvaporation.
Definition at line 58 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VEvaporationChannel.cc
void G4VEvaporationChannel::SetICM (G4bool) virtual
Reimplemented in G4PhotonEvaporation.
Definition at line 55 of file G4VEvaporationChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VEvaporationChannel.cc
Referenced by G4NeutronRadCapture::InitialiseModel().
void G4VEvaporationChannel::SetOPTxs (G4int opt) inline
Definition at line 113 of file G4VEvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VEvaporationChannel.hh
void G4VEvaporationChannel::UseSICB (G4bool use) inline
Definition at line 116 of file G4VEvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VEvaporationChannel.hh
Member Data Documentation
G4int G4VEvaporationChannel::OPTxs protected
Definition at line 93 of file G4VEvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VEvaporationChannel.hh
Referenced by G4EvaporationChannel::GetEmissionProbability().
G4bool G4VEvaporationChannel::useSICB protected
Definition at line 94 of file G4VEvaporationChannel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VEvaporationChannel.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4VEvaporationChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/src/G4VEvaporationChannel.cc