ECCE @ EIC Software: G4VhShellCrossSection Class Reference
G4VhShellCrossSection Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VhShellCrossSection.hh>
Public Member Functions
G4VhShellCrossSection (const G4String &xname="")
virtual ~G4VhShellCrossSection ()
G4int SelectRandomShell (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)
virtual std::vector< G4double > GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)=0
virtual G4double CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass, const G4Material *mat)=0
virtual std::vector< G4double > Probabilities (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)=0
virtual void SetTotalCS (G4double)
const G4String & GetName () const
Private Member Functions
G4VhShellCrossSection (const G4VhShellCrossSection &)
G4VhShellCrossSection & operator= (const G4VhShellCrossSection &right)
Private Attributes
G4String name
Detailed Description
Definition at line 62 of file G4VhShellCrossSection.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VhShellCrossSection.hh
Constructor & Destructor Documentation
G4VhShellCrossSection::G4VhShellCrossSection (const G4String & xname = "")
Definition at line 47 of file G4VhShellCrossSection.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VhShellCrossSection.cc
G4VhShellCrossSection::~G4VhShellCrossSection () virtual
Definition at line 50 of file G4VhShellCrossSection.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VhShellCrossSection.cc
G4VhShellCrossSection::G4VhShellCrossSection (const G4VhShellCrossSection &) private
Member Function Documentation
virtual G4double G4VhShellCrossSection::CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass, const G4Material * mat) pure virtual
Implemented in G4PenelopeIonisationCrossSection, G4teoCrossSection, G4empCrossSection, and G4LivermoreIonisationCrossSection.
Referenced by G4UAtomicDeexcitation::GetShellIonisationCrossSectionPerAtom().
virtual std::vector<G4double> G4VhShellCrossSection::GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material * mat) pure virtual
Implemented in G4LivermoreIonisationCrossSection, G4PenelopeIonisationCrossSection, G4teoCrossSection, and G4empCrossSection.
const G4String & G4VhShellCrossSection::GetName (void) const inline
Definition at line 113 of file G4VhShellCrossSection.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VhShellCrossSection.hh
References name.
Referenced by G4UAtomicDeexcitation::InitialiseForNewRun().
G4VhShellCrossSection& G4VhShellCrossSection::operator= (const G4VhShellCrossSection & right) private
virtual std::vector<G4double> G4VhShellCrossSection::Probabilities (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material * mat) pure virtual
Implemented in G4PenelopeIonisationCrossSection, G4LivermoreIonisationCrossSection, G4teoCrossSection, and G4empCrossSection.
Referenced by SelectRandomShell().
G4int G4VhShellCrossSection::SelectRandomShell (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material * mat)
Definition at line 56 of file G4VhShellCrossSection.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VhShellCrossSection.cc
References G4UniformRand, and Probabilities().
void G4VhShellCrossSection::SetTotalCS (G4double) virtual
Reimplemented in G4teoCrossSection, and G4empCrossSection.
Definition at line 53 of file G4VhShellCrossSection.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VhShellCrossSection.cc
Member Data Documentation
G4String G4VhShellCrossSection::name private
Definition at line 109 of file G4VhShellCrossSection.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VhShellCrossSection.hh
Referenced by GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VhShellCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VhShellCrossSection.cc