ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorMatrix.hh File Reference
G4ErrorMatrix.hh File Reference
#include <vector>
#include "G4Types.hh"
#include "G4ErrorMatrix.icc"
Classes
class G4ErrorMatrix
class G4ErrorMatrix::G4ErrorMatrix_row
class G4ErrorMatrix::G4ErrorMatrix_row_const
Typedefs
typedef std::vector< G4double >
::iterator G4ErrorMatrixIter
typedef std::vector< G4double >
::const_iterator G4ErrorMatrixConstIter
Functions
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (G4double t, const G4ErrorMatrix &m1)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, G4double t)
G4ErrorMatrix operator/ (const G4ErrorMatrix &m1, G4double t)
G4ErrorMatrix operator+ (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator- (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix dsum (const G4ErrorMatrix &, const G4ErrorMatrix &)
std::ostream & operator<< (std::ostream &s, const G4ErrorMatrix &q)
G4ErrorMatrix qr_solve (const G4ErrorMatrix &A, const G4ErrorMatrix &b)
G4ErrorMatrix qr_solve (G4ErrorMatrix *A, const G4ErrorMatrix &b)
G4ErrorMatrix qr_inverse (const G4ErrorMatrix &A)
G4ErrorMatrix qr_inverse (G4ErrorMatrix *A)
void qr_decomp (G4ErrorMatrix *A, G4ErrorMatrix *hsm)
G4ErrorMatrix qr_decomp (G4ErrorMatrix *A)
void back_solve (const G4ErrorMatrix &R, G4ErrorMatrix *b)
void col_house (G4ErrorMatrix *a, const G4ErrorMatrix &v, G4double vnormsq, G4int row, G4int col, G4int row_start, G4int col_start)
void col_house (G4ErrorMatrix *a, const G4ErrorMatrix &v, G4int row, G4int col, G4int row_start, G4int col_start)
void col_givens (G4ErrorMatrix *A, G4double c, G4double s, G4int k1, G4int k2, G4int row_min=1, G4int row_max=0)
void row_givens (G4ErrorMatrix *A, G4double c, G4double s, G4int k1, G4int k2, G4int col_min=1, G4int col_max=0)
void house_with_update (G4ErrorMatrix *a, G4int row=1, G4int col=1)
void house_with_update (G4ErrorMatrix *a, G4ErrorMatrix *v, G4int row=1, G4int col=1)
void row_house (G4ErrorMatrix *a, const G4ErrorMatrix &v, G4double vnormsq, G4int row, G4int col, G4int row_start, G4int col_start)
void row_house (G4ErrorMatrix *a, const G4ErrorMatrix &v, G4int row, G4int col, G4int row_start, G4int col_start)
Typedef Documentation
typedef std::vector<G4double >::const_iterator G4ErrorMatrixConstIter
Definition at line 44 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ErrorMatrix.hh
typedef std::vector<G4double >::iterator G4ErrorMatrixIter
Definition at line 41 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ErrorMatrix.hh
Function Documentation
void back_solve (const G4ErrorMatrix & R, G4ErrorMatrix * b)
void col_givens (G4ErrorMatrix * A, G4double c, G4double s, G4int k1, G4int k2, G4int row_min = 1, G4int row_max = 0)
void col_house (G4ErrorMatrix * a, const G4ErrorMatrix & v, G4double vnormsq, G4int row, G4int col, G4int row_start, G4int col_start)
void col_house (G4ErrorMatrix * a, const G4ErrorMatrix & v, G4int row, G4int col, G4int row_start, G4int col_start)
G4ErrorMatrix dsum (const G4ErrorMatrix & , const G4ErrorMatrix &)
Definition at line 200 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 200 of file G4ErrorMatrix.cc
References G4ErrorMatrix::num_col(), G4ErrorMatrix::num_row(), and G4ErrorMatrix::sub().
void house_with_update (G4ErrorMatrix * a, G4int row = 1, G4int col = 1)
void house_with_update (G4ErrorMatrix * a, G4ErrorMatrix * v, G4int row = 1, G4int col = 1)
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2)
Definition at line 271 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 271 of file G4ErrorMatrix.cc
References CHK_DIM_1, G4ErrorMatrix::m, G4ErrorMatrix::ncol, G4ErrorMatrix::nrow, and pt.
G4ErrorMatrix operator* (G4double t, const G4ErrorMatrix & m1)
Definition at line 264 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 264 of file G4ErrorMatrix.cc
References t.
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, G4double t)
Definition at line 257 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 257 of file G4ErrorMatrix.cc
References t.
G4ErrorMatrix operator+ (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2)
Definition at line 224 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 224 of file G4ErrorMatrix.cc
References CHK_DIM_2, G4ErrorMatrix::ncol, G4ErrorMatrix::nrow, G4ErrorMatrix::num_col(), G4ErrorMatrix::num_row(), and SIMPLE_TOP.
G4ErrorMatrix operator- (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2)
Definition at line 236 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 236 of file G4ErrorMatrix.cc
References CHK_DIM_2, G4ErrorMatrix::num_col(), G4ErrorMatrix::num_row(), and SIMPLE_TOP.
G4ErrorMatrix operator/ (const G4ErrorMatrix & m1, G4double t)
Definition at line 250 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 250 of file G4ErrorMatrix.cc
References t.
std::ostream& operator<< (std::ostream & s, const G4ErrorMatrix & q)
Definition at line 349 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 349 of file G4ErrorMatrix.cc
References G4endl, G4ErrorMatrix::num_col(), G4ErrorMatrix::num_row(), and width.
void qr_decomp (G4ErrorMatrix * A, G4ErrorMatrix * hsm)
G4ErrorMatrix qr_decomp (G4ErrorMatrix * A)
G4ErrorMatrix qr_inverse (const G4ErrorMatrix & A)
G4ErrorMatrix qr_inverse (G4ErrorMatrix * A)
G4ErrorMatrix qr_solve (const G4ErrorMatrix & A, const G4ErrorMatrix & b)
G4ErrorMatrix qr_solve (G4ErrorMatrix * A, const G4ErrorMatrix & b)
void row_givens (G4ErrorMatrix * A, G4double c, G4double s, G4int k1, G4int k2, G4int col_min = 1, G4int col_max = 0)
void row_house (G4ErrorMatrix * a, const G4ErrorMatrix & v, G4double vnormsq, G4int row, G4int col, G4int row_start, G4int col_start)
void row_house (G4ErrorMatrix * a, const G4ErrorMatrix & v, G4int row, G4int col, G4int row_start, G4int col_start)