ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/externals/expat/src/xmltok.cc File Reference
xmltok.cc File Reference
#include <stddef.h>
#include "expat_external.h"
#include "internal.h"
#include "xmltok.h"
#include "nametab.h"
#include "xmltok_impl.h"
#include "ascii.h"
#include "xmltok_impl.cc"
#include "asciitab.h"
#include "utf8tab.h"
#include "iasciitab.h"
#include "latin1tab.h"
#include "xmltok_ns.cc"
Classes
struct normal_encoding
struct unknown_encoding
Macros
#define IGNORE_SECTION_TOK_VTABLE /* as nothing */
#define VTABLE1
#define VTABLE VTABLE1, PREFIX(toUtf8), PREFIX(toUtf16)
#define UCS2_GET_NAMING(pages, hi, lo) (namingBitmap[(pages[hi] << 3) + ((lo) >> 5)] & (1 << ((lo) & 0x1F)))
#define UTF8_GET_NAMING2(pages, byte)
#define UTF8_GET_NAMING3(pages, byte)
#define UTF8_GET_NAMING(pages, p, n)
#define UTF8_INVALID2(p) ((*p) < 0xC2 || ((p)[1] & 0x80) == 0 || ((p)[1] & 0xC0) == 0xC0)
#define UTF8_INVALID3(p)
#define UTF8_INVALID4(p)
#define utf8_isName4 isNever
#define utf8_isNmstrt4 isNever
#define AS_NORMAL_ENCODING(enc) ((const struct normal_encoding *) (enc))
#define STANDARD_VTABLE(E) /* as nothing */
#define NORMAL_VTABLE(E)
#define MINBPC(enc) 1
#define SB_BYTE_TYPE(enc, p) (((struct normal_encoding *)(enc))->type[(unsigned char)*(p)])
#define BYTE_TYPE(enc, p) SB_BYTE_TYPE(enc, p)
#define BYTE_TO_ASCII(enc, p) (*(p))
#define IS_NAME_CHAR(enc, p, n) (AS_NORMAL_ENCODING(enc)->isName ## n(enc, p))
#define IS_NMSTRT_CHAR(enc, p, n) (AS_NORMAL_ENCODING(enc)->isNmstrt ## n(enc, p))
#define IS_INVALID_CHAR(enc, p, n) (AS_NORMAL_ENCODING(enc)->isInvalid ## n(enc, p))
#define IS_NAME_CHAR_MINBPC(enc, p) (0)
#define IS_NMSTRT_CHAR_MINBPC(enc, p) (0)
#define CHAR_MATCHES(enc, p, c) (*(p) == c)
#define PREFIX(ident) normal_ ## ident
#define XML_TOK_IMPL_C
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define DEFINE_UTF16_TO_UTF8(E)
#define DEFINE_UTF16_TO_UTF16(E)
#define SET2(ptr, ch) (((ptr)[0] = ((ch) & 0xff)), ((ptr)[1] = ((ch) >> 8)))
#define GET_LO(ptr) ((unsigned char)(ptr)[0])
#define GET_HI(ptr) ((unsigned char)(ptr)[1])
#define SET2(ptr, ch) (((ptr)[0] = ((ch) >> 8)), ((ptr)[1] = ((ch) & 0xFF)))
#define GET_LO(ptr) ((unsigned char)(ptr)[1])
#define GET_HI(ptr) ((unsigned char)(ptr)[0])
#define LITTLE2_BYTE_TYPE(enc, p)
#define LITTLE2_BYTE_TO_ASCII(enc, p) ((p)[1] == 0 ? (p)[0] : -1)
#define LITTLE2_CHAR_MATCHES(enc, p, c) ((p)[1] == 0 && (p)[0] == c)
#define LITTLE2_IS_NAME_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[1], (unsigned char)p[0])
#define LITTLE2_IS_NMSTRT_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[1], (unsigned char)p[0])
#define PREFIX(ident) little2_ ## ident
#define MINBPC(enc) 2
#define BYTE_TYPE(enc, p) LITTLE2_BYTE_TYPE(enc, p)
#define BYTE_TO_ASCII(enc, p) LITTLE2_BYTE_TO_ASCII(enc, p)
#define CHAR_MATCHES(enc, p, c) LITTLE2_CHAR_MATCHES(enc, p, c)
#define IS_NAME_CHAR(enc, p, n) 0
#define IS_NAME_CHAR_MINBPC(enc, p) LITTLE2_IS_NAME_CHAR_MINBPC(enc, p)
#define IS_NMSTRT_CHAR(enc, p, n) (0)
#define IS_NMSTRT_CHAR_MINBPC(enc, p) LITTLE2_IS_NMSTRT_CHAR_MINBPC(enc, p)
#define XML_TOK_IMPL_C
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BIG2_BYTE_TYPE(enc, p)
#define BIG2_BYTE_TO_ASCII(enc, p) ((p)[0] == 0 ? (p)[1] : -1)
#define BIG2_CHAR_MATCHES(enc, p, c) ((p)[0] == 0 && (p)[1] == c)
#define BIG2_IS_NAME_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[0], (unsigned char)p[1])
#define BIG2_IS_NMSTRT_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[0], (unsigned char)p[1])
#define PREFIX(ident) big2_ ## ident
#define MINBPC(enc) 2
#define BYTE_TYPE(enc, p) BIG2_BYTE_TYPE(enc, p)
#define BYTE_TO_ASCII(enc, p) BIG2_BYTE_TO_ASCII(enc, p)
#define CHAR_MATCHES(enc, p, c) BIG2_CHAR_MATCHES(enc, p, c)
#define IS_NAME_CHAR(enc, p, n) 0
#define IS_NAME_CHAR_MINBPC(enc, p) BIG2_IS_NAME_CHAR_MINBPC(enc, p)
#define IS_NMSTRT_CHAR(enc, p, n) (0)
#define IS_NMSTRT_CHAR_MINBPC(enc, p) BIG2_IS_NMSTRT_CHAR_MINBPC(enc, p)
#define XML_TOK_IMPL_C
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define AS_UNKNOWN_ENCODING(enc) ((const struct unknown_encoding *) (enc))
#define INIT_ENC_INDEX(enc) ((int)(enc)->initEnc.isUtf16)
#define SET_INIT_ENC_INDEX(enc, i) ((enc)->initEnc.isUtf16 = (char)i)
#define NS(x) x
#define ns(x) x
#define XML_TOK_NS_C
Enumerations
enum { UTF8_cval1 = 0x00, UTF8_cval2 = 0xc0, UTF8_cval3 = 0xe0, UTF8_cval4 = 0xf0 }
enum {
UNKNOWN_ENC = -1, ISO_8859_1_ENC = 0, US_ASCII_ENC, UTF_8_ENC,
UTF_16_ENC, UTF_16BE_ENC, UTF_16LE_ENC, NO_ENC
}
Functions
static int PTRFASTCALL isNever (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isName2 (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isName3 (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isNmstrt2 (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isNmstrt3 (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isInvalid2 (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isInvalid3 (const ENCODING *enc, const char *p)
static int PTRFASTCALL utf8_isInvalid4 (const ENCODING *enc, const char *p)
static int FASTCALL checkCharRefNumber (int)
static void PTRCALL utf8_toUtf8 (const ENCODING *enc, const char **fromP, const char *fromLim, char **toP, const char *toLim)
static void PTRCALL utf8_toUtf16 (const ENCODING *enc, const char **fromP, const char *fromLim, unsigned short **toP, const unsigned short *toLim)
static void PTRCALL latin1_toUtf8 (const ENCODING *enc, const char **fromP, const char *fromLim, char **toP, const char *toLim)
static void PTRCALL latin1_toUtf16 (const ENCODING *enc, const char **fromP, const char *fromLim, unsigned short **toP, const unsigned short *toLim)
static void PTRCALL ascii_toUtf8 (const ENCODING *enc, const char **fromP, const char *fromLim, char **toP, const char *toLim)
static int PTRFASTCALL unicode_byte_type (char hi, char lo)
static int FASTCALL streqci (const char *s1, const char *s2)
static void PTRCALL initUpdatePosition (const ENCODING *enc, const char *ptr, const char *end, POSITION *pos)
static int toAscii (const ENCODING *enc, const char *ptr, const char *end)
static int FASTCALL isSpace (int c)
static int parsePseudoAttribute (const ENCODING *enc, const char *ptr, const char *end, const char **namePtr, const char **nameEndPtr, const char **valPtr, const char **nextTokPtr)
static int doParseXmlDecl (const ENCODING *(*encodingFinder)(const ENCODING *, const char *, const char *), int isGeneralTextEntity, const ENCODING *enc, const char *ptr, const char *end, const char **badPtr, const char **versionPtr, const char **versionEndPtr, const char **encodingName, const ENCODING **encoding, int *standalone)
int FASTCALL XmlUtf8Encode (int c, char *buf)
int FASTCALL XmlUtf16Encode (int charNum, unsigned short *buf)
int XmlSizeOfUnknownEncoding (void)
static int PTRFASTCALL unknown_isName (const ENCODING *enc, const char *p)
static int PTRFASTCALL unknown_isNmstrt (const ENCODING *enc, const char *p)
static int PTRFASTCALL unknown_isInvalid (const ENCODING *enc, const char *p)
static void PTRCALL unknown_toUtf8 (const ENCODING *enc, const char **fromP, const char *fromLim, char **toP, const char *toLim)
static void PTRCALL unknown_toUtf16 (const ENCODING *enc, const char **fromP, const char *fromLim, unsigned short **toP, const unsigned short *toLim)
ENCODING * XmlInitUnknownEncoding (void *mem, int *table, CONVERTER convert, void *userData)
static int FASTCALL getEncodingIndex (const char *name)
static int initScan (const ENCODING *const *encodingTable, const INIT_ENCODING *enc, int state, const char *ptr, const char *end, const char **nextTokPtr)
Variables
static struct normal_encoding utf8_encoding
static struct normal_encoding internal_utf8_encoding
static struct normal_encoding latin1_encoding
static struct normal_encoding ascii_encoding
static struct normal_encoding little2_encoding
static struct normal_encoding internal_little2_encoding
static struct normal_encoding big2_encoding
static struct normal_encoding internal_big2_encoding
static const char KW_version []
static const char KW_encoding []
static const char KW_standalone []
static const char KW_yes []
static const char KW_no []
static const char KW_ISO_8859_1 []
static const char KW_US_ASCII []
static const char KW_UTF_8 []
static const char KW_UTF_16 []
static const char KW_UTF_16BE []
static const char KW_UTF_16LE []
Macro Definition Documentation
#define AS_NORMAL_ENCODING (enc) ((const struct normal_encoding *) (enc))
Definition at line 202 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 202 of file xmltok.cc
Referenced by unknown_toUtf16(), and unknown_toUtf8().
#define AS_UNKNOWN_ENCODING (enc) ((const struct unknown_encoding *) (enc))
Definition at line 1260 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1260 of file xmltok.cc
Referenced by unknown_isInvalid(), unknown_isName(), unknown_isNmstrt(), unknown_toUtf16(), and unknown_toUtf8().
#define BIG2_BYTE_TO_ASCII (enc, p) ((p)[0] == 0 ? (p)[1] : -1)
Definition at line 789 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 789 of file xmltok.cc
#define BIG2_BYTE_TYPE (enc, p)
Value:
((p)[0] == 0 \
  ? ((struct normal_encoding *)(enc))->type[(unsigned char)(p)[1]] \
  : unicode_byte_type((p)[0], (p)[1]))
Definition at line 785 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 785 of file xmltok.cc
#define BIG2_CHAR_MATCHES (enc, p, c) ((p)[0] == 0 && (p)[1] == c)
Definition at line 790 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 790 of file xmltok.cc
#define BIG2_IS_NAME_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[0], (unsigned char)p[1])
Definition at line 791 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 791 of file xmltok.cc
#define BIG2_IS_NMSTRT_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[0], (unsigned char)p[1])
Definition at line 793 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 793 of file xmltok.cc
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BYTE_TO_ASCII (enc, p) (*(p))
Definition at line 838 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 838 of file xmltok.cc
#define BYTE_TO_ASCII (enc, p) LITTLE2_BYTE_TO_ASCII(enc, p)
Definition at line 838 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 838 of file xmltok.cc
#define BYTE_TO_ASCII (enc, p) BIG2_BYTE_TO_ASCII(enc, p)
Definition at line 838 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 838 of file xmltok.cc
#define BYTE_TYPE (enc, p) SB_BYTE_TYPE(enc, p)
Definition at line 837 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 837 of file xmltok.cc
#define BYTE_TYPE (enc, p) LITTLE2_BYTE_TYPE(enc, p)
Definition at line 837 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 837 of file xmltok.cc
#define BYTE_TYPE (enc, p) BIG2_BYTE_TYPE(enc, p)
Definition at line 837 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 837 of file xmltok.cc
#define CHAR_MATCHES (enc, p, c) (*(p) == c)
Definition at line 839 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 839 of file xmltok.cc
#define CHAR_MATCHES (enc, p, c) LITTLE2_CHAR_MATCHES(enc, p, c)
Definition at line 839 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 839 of file xmltok.cc
#define CHAR_MATCHES (enc, p, c) BIG2_CHAR_MATCHES(enc, p, c)
Definition at line 839 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 839 of file xmltok.cc
#define DEFINE_UTF16_TO_UTF16 (E)
Value:
static void  PTRCALL \
E ## toUtf16(const ENCODING *enc, \
             const char **fromP, const char *fromLim, \
             unsigned short **toP, const unsigned short *toLim) \
{ \
  /* Avoid copying first half only of surrogate */ \
  if (fromLim - *fromP > ((toLim - *toP) << 1) \
      && (GET_HI(fromLim - 2) & 0xF8) == 0xD8) \
    fromLim -= 2; \
  for (; *fromP != fromLim && *toP != toLim; *fromP += 2) \
    *(*toP)++ = (GET_HI(*fromP) << 8) | GET_LO(*fromP); \
}
Definition at line 606 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 606 of file xmltok.cc
#define DEFINE_UTF16_TO_UTF8 (E)
Definition at line 543 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 543 of file xmltok.cc
#define GET_HI (ptr) ((unsigned char)(ptr)[1])
Definition at line 635 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 635 of file xmltok.cc
#define GET_HI (ptr) ((unsigned char)(ptr)[0])
Definition at line 635 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 635 of file xmltok.cc
#define GET_LO (ptr) ((unsigned char)(ptr)[0])
Definition at line 634 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 634 of file xmltok.cc
#define GET_LO (ptr) ((unsigned char)(ptr)[1])
Definition at line 634 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 634 of file xmltok.cc
#define IGNORE_SECTION_TOK_VTABLE /* as nothing */
Definition at line 34 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 34 of file xmltok.cc
#define INIT_ENC_INDEX (enc) ((int)(enc)->initEnc.isUtf16)
Definition at line 1490 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1490 of file xmltok.cc
Referenced by initScan().
#define IS_INVALID_CHAR (enc, p, n) (AS_NORMAL_ENCODING(enc)->isInvalid ## n(enc, p))
Definition at line 278 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 278 of file xmltok.cc
#define IS_NAME_CHAR (enc, p, n) (AS_NORMAL_ENCODING(enc)->isName ## n(enc, p))
Definition at line 840 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 840 of file xmltok.cc
#define IS_NAME_CHAR (enc, p, n) 0
Definition at line 840 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 840 of file xmltok.cc
#define IS_NAME_CHAR (enc, p, n) 0
Definition at line 840 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 840 of file xmltok.cc
#define IS_NAME_CHAR_MINBPC (enc, p) (0)
Definition at line 841 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 841 of file xmltok.cc
#define IS_NAME_CHAR_MINBPC (enc, p) LITTLE2_IS_NAME_CHAR_MINBPC(enc, p)
Definition at line 841 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 841 of file xmltok.cc
#define IS_NAME_CHAR_MINBPC (enc, p) BIG2_IS_NAME_CHAR_MINBPC(enc, p)
Definition at line 841 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 841 of file xmltok.cc
#define IS_NMSTRT_CHAR (enc, p, n) (AS_NORMAL_ENCODING(enc)->isNmstrt ## n(enc, p))
Definition at line 842 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 842 of file xmltok.cc
#define IS_NMSTRT_CHAR (enc, p, n) (0)
Definition at line 842 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 842 of file xmltok.cc
#define IS_NMSTRT_CHAR (enc, p, n) (0)
Definition at line 842 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 842 of file xmltok.cc
#define IS_NMSTRT_CHAR_MINBPC (enc, p) (0)
Definition at line 843 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 843 of file xmltok.cc
#define IS_NMSTRT_CHAR_MINBPC (enc, p) LITTLE2_IS_NMSTRT_CHAR_MINBPC(enc, p)
Definition at line 843 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 843 of file xmltok.cc
#define IS_NMSTRT_CHAR_MINBPC (enc, p) BIG2_IS_NMSTRT_CHAR_MINBPC(enc, p)
Definition at line 843 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 843 of file xmltok.cc
#define LITTLE2_BYTE_TO_ASCII (enc, p) ((p)[1] == 0 ? (p)[0] : -1)
Definition at line 648 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 648 of file xmltok.cc
#define LITTLE2_BYTE_TYPE (enc, p)
Value:
((p)[1] == 0 \
  ? ((struct normal_encoding *)(enc))->type[(unsigned char)*(p)] \
  : unicode_byte_type((p)[1], (p)[0]))
Definition at line 644 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 644 of file xmltok.cc
#define LITTLE2_CHAR_MATCHES (enc, p, c) ((p)[1] == 0 && (p)[0] == c)
Definition at line 649 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 649 of file xmltok.cc
#define LITTLE2_IS_NAME_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[1], (unsigned char)p[0])
Definition at line 650 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 650 of file xmltok.cc
#define LITTLE2_IS_NMSTRT_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[1], (unsigned char)p[0])
Definition at line 652 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 652 of file xmltok.cc
#define MINBPC (enc) 1
Definition at line 835 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 835 of file xmltok.cc
#define MINBPC (enc) 2
Definition at line 835 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 835 of file xmltok.cc
#define MINBPC (enc) 2
Definition at line 835 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 835 of file xmltok.cc
#define NORMAL_VTABLE (E)
Value:
E ## isName2, \
 E ## isName3, \
 E ## isName4, \
 E ## isNmstrt2, \
 E ## isNmstrt3, \
 E ## isNmstrt4, \
 E ## isInvalid2, \
 E ## isInvalid3, \
 E ## isInvalid4
Definition at line 219 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 219 of file xmltok.cc
#define NS (x) x
Definition at line 1624 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1624 of file xmltok.cc
Referenced by G4NistElementBuilder::Initialise().
#define ns (x) x
Definition at line 1625 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1625 of file xmltok.cc
#define PREFIX (ident) normal_ ## ident
Definition at line 834 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 834 of file xmltok.cc
#define PREFIX (ident) little2_ ## ident
Definition at line 834 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 834 of file xmltok.cc
#define PREFIX (ident) big2_ ## ident
Definition at line 834 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 834 of file xmltok.cc
#define SB_BYTE_TYPE (enc, p) (((struct normal_encoding *)(enc))->type[(unsigned char)*(p)])
Definition at line 247 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 247 of file xmltok.cc
#define SET2 (ptr, ch) (((ptr)[0] = ((ch) & 0xff)), ((ptr)[1] = ((ch) >> 8)))
Definition at line 632 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 632 of file xmltok.cc
#define SET2 (ptr, ch) (((ptr)[0] = ((ch) >> 8)), ((ptr)[1] = ((ch) & 0xFF)))
Definition at line 632 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 632 of file xmltok.cc
#define SET_INIT_ENC_INDEX (enc, i) ((enc)->initEnc.isUtf16 = (char)i)
Definition at line 1491 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1491 of file xmltok.cc
#define STANDARD_VTABLE (E) /* as nothing */
Definition at line 215 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 215 of file xmltok.cc
#define UCS2_GET_NAMING (pages, hi, lo) (namingBitmap[(pages[hi] << 3) + ((lo) >> 5)] & (1 << ((lo) & 0x1F)))
Definition at line 53 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 53 of file xmltok.cc
Referenced by unknown_isName(), unknown_isNmstrt(), and XmlInitUnknownEncoding().
#define UTF8_GET_NAMING (pages, p, n)
Value:
((n) == 2 \
  ? UTF8_GET_NAMING2(pages, (const unsigned char *)(p)) \
  : ((n) == 3 \
     ? UTF8_GET_NAMING3(pages, (const unsigned char *)(p)) \
     : 0))
Definition at line 79 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 79 of file xmltok.cc
#define UTF8_GET_NAMING2 (pages, byte)
Value:
(namingBitmap[((pages)[(((byte)[0]) >> 2) & 7] << 3) \
                      + ((((byte)[0]) & 3) << 1) \
                      + ((((byte)[1]) >> 5) & 1)] \
         & (1 << (((byte)[1]) & 0x1F)))
Definition at line 60 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 60 of file xmltok.cc
Referenced by utf8_isName2(), and utf8_isNmstrt2().
#define UTF8_GET_NAMING3 (pages, byte)
Value:
(namingBitmap[((pages)[((((byte)[0]) & 0xF) << 4) \
                             + ((((byte)[1]) >> 2) & 0xF)] \
                       << 3) \
                      + ((((byte)[1]) & 3) << 1) \
                      + ((((byte)[2]) >> 5) & 1)] \
         & (1 << (((byte)[2]) & 0x1F)))
Definition at line 71 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 71 of file xmltok.cc
Referenced by utf8_isName3(), and utf8_isNmstrt3().
#define UTF8_INVALID2 (p) ((*p) < 0xC2 || ((p)[1] & 0x80) == 0 || ((p)[1] & 0xC0) == 0xC0)
Definition at line 96 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 96 of file xmltok.cc
Referenced by utf8_isInvalid2().
#define UTF8_INVALID3 (p)
Value:
(((p)[2] & 0x80) == 0 \
  || \
  ((*p) == 0xEF && (p)[1] == 0xBF \
    ? \
    (p)[2] > 0xBD \
    : \
    ((p)[2] & 0xC0) == 0xC0) \
  || \
  ((*p) == 0xE0 \
    ? \
    (p)[1] < 0xA0 || ((p)[1] & 0xC0) == 0xC0 \
    : \
    ((p)[1] & 0x80) == 0 \
    || \
    ((*p) == 0xED ? (p)[1] > 0x9F : ((p)[1] & 0xC0) == 0xC0)))
Definition at line 99 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 99 of file xmltok.cc
Referenced by utf8_isInvalid3().
#define UTF8_INVALID4 (p)
Value:
(((p)[3] & 0x80) == 0 || ((p)[3] & 0xC0) == 0xC0 \
  || \
  ((p)[2] & 0x80) == 0 || ((p)[2] & 0xC0) == 0xC0 \
  || \
  ((*p) == 0xF0 \
    ? \
    (p)[1] < 0x90 || ((p)[1] & 0xC0) == 0xC0 \
    : \
    ((p)[1] & 0x80) == 0 \
    || \
    ((*p) == 0xF4 ? (p)[1] > 0x8F : ((p)[1] & 0xC0) == 0xC0)))
Definition at line 116 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 116 of file xmltok.cc
Referenced by utf8_isInvalid4().
#define utf8_isName4 isNever
Definition at line 147 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 147 of file xmltok.cc
#define utf8_isNmstrt4 isNever
Definition at line 161 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 161 of file xmltok.cc
#define VTABLE VTABLE1, PREFIX(toUtf8), PREFIX(toUtf16)
Definition at line 51 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 51 of file xmltok.cc
#define VTABLE1
Value:
{ PREFIX(prologTok), PREFIX(contentTok), \
    PREFIX(cdataSectionTok) IGNORE_SECTION_TOK_VTABLE }, \
  { PREFIX(attributeValueTok), PREFIX(entityValueTok) }, \
  PREFIX(sameName), \
  PREFIX(nameMatchesAscii), \
  PREFIX(nameLength), \
  PREFIX(skipS), \
  PREFIX(getAtts), \
  PREFIX(charRefNumber), \
  PREFIX(predefinedEntityName), \
  PREFIX(updatePosition), \
  PREFIX(isPublicId)
Definition at line 37 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 37 of file xmltok.cc
#define XML_TOK_IMPL_C
Definition at line 845 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 845 of file xmltok.cc
#define XML_TOK_IMPL_C
Definition at line 845 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 845 of file xmltok.cc
#define XML_TOK_IMPL_C
Definition at line 845 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 845 of file xmltok.cc
#define XML_TOK_NS_C
Definition at line 1626 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1626 of file xmltok.cc
Enumeration Type Documentation
anonymous enum
Enumerator:
UTF8_cval1
UTF8_cval2
UTF8_cval3
UTF8_cval4
Definition at line 319 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 319 of file xmltok.cc
anonymous enum
Enumerator:
UNKNOWN_ENC
ISO_8859_1_ENC
US_ASCII_ENC
UTF_8_ENC
UTF_16_ENC
UTF_16BE_ENC
UTF_16LE_ENC
NO_ENC
Definition at line 1431 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1431 of file xmltok.cc
Function Documentation
static void PTRCALL ascii_toUtf8 (const ENCODING * enc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
Definition at line 492 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 492 of file xmltok.cc
static int FASTCALL checkCharRefNumber (int result) static
Definition at line 1179 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1179 of file xmltok.cc
References BT_NONXML, and normal_encoding::type.
Referenced by unknown_isInvalid(), and XmlInitUnknownEncoding().
static int doParseXmlDecl (const ENCODING *(*)(const ENCODING *, const char *, const char *) encodingFinder, int isGeneralTextEntity, const ENCODING * enc, const char * ptr, const char * end, const char ** badPtr, const char ** versionPtr, const char ** versionEndPtr, const char ** encodingName, const ENCODING ** encoding, int * standalone) static
Definition at line 1087 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1087 of file xmltok.cc
References ASCII_A, ASCII_a, ASCII_Z, ASCII_z, c, isSpace(), encoding::minBytesPerChar, parsePseudoAttribute(), toAscii(), and XmlNameMatchesAscii.
static int FASTCALL getEncodingIndex (const char * name) static
Definition at line 1467 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1467 of file xmltok.cc
References int(), KW_ISO_8859_1, KW_US_ASCII, KW_UTF_16, KW_UTF_16BE, KW_UTF_16LE, KW_UTF_8, NO_ENC, streqci(), and UNKNOWN_ENC.
static int initScan (const ENCODING *const * encodingTable, const INIT_ENCODING * enc, int state, const char * ptr, const char * end, const char ** nextTokPtr) static
Definition at line 1502 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1502 of file xmltok.cc
References e, INIT_ENCODING::encPtr, INIT_ENC_INDEX, ISO_8859_1_ENC, UTF_16_ENC, UTF_16BE_ENC, UTF_16LE_ENC, UTF_8_ENC, XML_CONTENT_STATE, XML_TOK_BOM, XML_TOK_NONE, XML_TOK_PARTIAL, and XmlTok.
static void PTRCALL initUpdatePosition (const ENCODING * enc, const char * ptr, const char * end, POSITION * pos) static
Definition at line 946 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 946 of file xmltok.cc
References normal_encoding::enc.
static int PTRFASTCALL isNever (const ENCODING * enc, const char * p) static
Definition at line 130 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 130 of file xmltok.cc
static int FASTCALL isSpace (int c) static
Definition at line 965 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 965 of file xmltok.cc
Referenced by doParseXmlDecl(), and parsePseudoAttribute().
static void PTRCALL latin1_toUtf16 (const ENCODING * enc, const char ** fromP, const char * fromLim, unsigned short ** toP, const unsigned short * toLim) static
Definition at line 459 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 459 of file xmltok.cc
static void PTRCALL latin1_toUtf8 (const ENCODING * enc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
Definition at line 434 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 434 of file xmltok.cc
References c, and UTF8_cval2.
static int parsePseudoAttribute (const ENCODING * enc, const char * ptr, const char * end, const char ** namePtr, const char ** nameEndPtr, const char ** valPtr, const char ** nextTokPtr) static
Definition at line 981 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 981 of file xmltok.cc
References ASCII_0, ASCII_9, ASCII_A, ASCII_a, ASCII_APOS, ASCII_EQUALS, ASCII_MINUS, ASCII_PERIOD, ASCII_QUOT, ASCII_UNDERSCORE, ASCII_Z, ASCII_z, c, isSpace(), encoding::minBytesPerChar, Acts::open, and toAscii().
Referenced by doParseXmlDecl().
static int FASTCALL streqci (const char * s1, const char * s2) static
Definition at line 928 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 928 of file xmltok.cc
References ASCII_A, ASCII_a, ASCII_z, c1, and c2.
Referenced by getEncodingIndex().
static int toAscii (const ENCODING * enc, const char * ptr, const char * end) static
Definition at line 953 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 953 of file xmltok.cc
References XmlUtf8Convert.
Referenced by doParseXmlDecl(), and parsePseudoAttribute().
static int PTRFASTCALL unicode_byte_type (char hi, char lo) static
Definition at line 525 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 525 of file xmltok.cc
References BT_LEAD4, BT_NONASCII, BT_NONXML, and BT_TRAIL.
static int PTRFASTCALL unknown_isInvalid (const ENCODING * enc, const char * p) static
Definition at line 1289 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1289 of file xmltok.cc
References AS_UNKNOWN_ENCODING, c, checkCharRefNumber(), unknown_encoding::convert, and unknown_encoding::userData.
Referenced by XmlInitUnknownEncoding().
static int PTRFASTCALL unknown_isName (const ENCODING * enc, const char * p) static
Definition at line 1269 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1269 of file xmltok.cc
References AS_UNKNOWN_ENCODING, c, unknown_encoding::convert, namePages, UCS2_GET_NAMING, and unknown_encoding::userData.
Referenced by XmlInitUnknownEncoding().
static int PTRFASTCALL unknown_isNmstrt (const ENCODING * enc, const char * p) static
Definition at line 1279 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1279 of file xmltok.cc
References AS_UNKNOWN_ENCODING, c, unknown_encoding::convert, nmstrtPages, UCS2_GET_NAMING, and unknown_encoding::userData.
Referenced by XmlInitUnknownEncoding().
static void PTRCALL unknown_toUtf16 (const ENCODING * enc, const char ** fromP, const char * fromLim, unsigned short ** toP, const unsigned short * toLim) static
Definition at line 1331 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1331 of file xmltok.cc
References AS_NORMAL_ENCODING, AS_UNKNOWN_ENCODING, BT_LEAD2, c, unknown_encoding::convert, unknown_encoding::userData, and unknown_encoding::utf16.
Referenced by XmlInitUnknownEncoding().
static void PTRCALL unknown_toUtf8 (const ENCODING * enc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
Definition at line 1297 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1297 of file xmltok.cc
References AS_NORMAL_ENCODING, AS_UNKNOWN_ENCODING, BT_LEAD2, c, unknown_encoding::convert, n, unknown_encoding::userData, unknown_encoding::utf8, XML_UTF8_ENCODE_MAX, and XmlUtf8Encode().
Referenced by XmlInitUnknownEncoding().
static int PTRFASTCALL utf8_isInvalid2 (const ENCODING * enc, const char * p) static
Definition at line 164 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 164 of file xmltok.cc
References UTF8_INVALID2.
static int PTRFASTCALL utf8_isInvalid3 (const ENCODING * enc, const char * p) static
Definition at line 170 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 170 of file xmltok.cc
References UTF8_INVALID3.
static int PTRFASTCALL utf8_isInvalid4 (const ENCODING * enc, const char * p) static
Definition at line 176 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 176 of file xmltok.cc
References UTF8_INVALID4.
static int PTRFASTCALL utf8_isName2 (const ENCODING * enc, const char * p) static
Definition at line 136 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 136 of file xmltok.cc
References namePages, and UTF8_GET_NAMING2.
static int PTRFASTCALL utf8_isName3 (const ENCODING * enc, const char * p) static
Definition at line 142 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 142 of file xmltok.cc
References namePages, and UTF8_GET_NAMING3.
static int PTRFASTCALL utf8_isNmstrt2 (const ENCODING * enc, const char * p) static
Definition at line 150 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 150 of file xmltok.cc
References nmstrtPages, and UTF8_GET_NAMING2.
static int PTRFASTCALL utf8_isNmstrt3 (const ENCODING * enc, const char * p) static
Definition at line 156 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 156 of file xmltok.cc
References nmstrtPages, and UTF8_GET_NAMING3.
static void PTRCALL utf8_toUtf16 (const ENCODING * enc, const char ** fromP, const char * fromLim, unsigned short ** toP, const unsigned short * toLim) static
Definition at line 346 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 346 of file xmltok.cc
References BT_LEAD2, BT_LEAD3, BT_LEAD4, and n.
static void PTRCALL utf8_toUtf8 (const ENCODING * enc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
Definition at line 327 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 327 of file xmltok.cc
ENCODING* XmlInitUnknownEncoding (void * mem, int * table, CONVERTER convert, void * userData)
Definition at line 1351 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1351 of file xmltok.cc
References BT_LEAD2, BT_MALFORM, BT_NAME, BT_NMSTRT, BT_NONXML, BT_OTHER, c, checkCharRefNumber(), unknown_encoding::convert, e, normal_encoding::enc, if(), int(), latin1_encoding, namePages, nmstrtPages, unknown_encoding::normal, normal_encoding::type, UCS2_GET_NAMING, unknown_isInvalid(), unknown_isName(), unknown_isNmstrt(), unknown_toUtf16(), unknown_toUtf8(), userData, unknown_encoding::userData, unknown_encoding::utf16, unknown_encoding::utf8, and XmlUtf8Encode().
Referenced by handleUnknownEncoding().
int XmlSizeOfUnknownEncoding (void)
Definition at line 1263 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1263 of file xmltok.cc
Referenced by handleUnknownEncoding().
int FASTCALL XmlUtf16Encode (int charNum, unsigned short * buf)
Definition at line 1235 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1235 of file xmltok.cc
int FASTCALL XmlUtf8Encode (int c, char * buf)
Definition at line 1198 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1198 of file xmltok.cc
References min3(), UTF8_cval1, UTF8_cval2, UTF8_cval3, and UTF8_cval4.
Referenced by unknown_toUtf8(), and XmlInitUnknownEncoding().
Variable Documentation
struct normal_encoding ascii_encoding static
Definition at line 513 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 513 of file xmltok.cc
struct normal_encoding big2_encoding static
Definition at line 880 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 880 of file xmltok.cc
struct normal_encoding internal_big2_encoding static
Definition at line 912 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 912 of file xmltok.cc
struct normal_encoding internal_little2_encoding static
Definition at line 771 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 771 of file xmltok.cc
struct normal_encoding internal_utf8_encoding static
Definition at line 422 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 422 of file xmltok.cc
const char KW_encoding[] static
Initial value:
= {
  ASCII_e, ASCII_n, ASCII_c, ASCII_o, ASCII_d, ASCII_i, ASCII_n, ASCII_g, '\0'
}
Definition at line 1069 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1069 of file xmltok.cc
const char KW_ISO_8859_1[] static
Initial value:
= {
  ASCII_I, ASCII_S, ASCII_O, ASCII_MINUS, ASCII_8, ASCII_8, ASCII_5, ASCII_9,
  ASCII_MINUS, ASCII_1, '\0'
}
Definition at line 1443 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1443 of file xmltok.cc
Referenced by getEncodingIndex().
const char KW_no[] static
Initial value:
= {
  ASCII_n, ASCII_o,  '\0'
}
Definition at line 1082 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1082 of file xmltok.cc
const char KW_standalone[] static
Initial value:
= {
  ASCII_s, ASCII_t, ASCII_a, ASCII_n, ASCII_d, ASCII_a, ASCII_l, ASCII_o,
  ASCII_n, ASCII_e, '\0'
}
Definition at line 1073 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1073 of file xmltok.cc
const char KW_US_ASCII[] static
Initial value:
= {
  ASCII_U, ASCII_S, ASCII_MINUS, ASCII_A, ASCII_S, ASCII_C, ASCII_I, ASCII_I,
  '\0'
}
Definition at line 1447 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1447 of file xmltok.cc
Referenced by getEncodingIndex().
const char KW_UTF_16[] static
Initial value:
= {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_1, ASCII_6, '\0'
}
Definition at line 1454 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1454 of file xmltok.cc
Referenced by getEncodingIndex().
const char KW_UTF_16BE[] static
Initial value:
= {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_1, ASCII_6, ASCII_B, ASCII_E,
  '\0'
}
Definition at line 1457 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1457 of file xmltok.cc
Referenced by getEncodingIndex().
const char KW_UTF_16LE[] static
Initial value:
= {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_1, ASCII_6, ASCII_L, ASCII_E,
  '\0'
}
Definition at line 1461 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1461 of file xmltok.cc
Referenced by getEncodingIndex().
const char KW_UTF_8[] static
Initial value:
=  {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_8, '\0'
}
Definition at line 1451 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1451 of file xmltok.cc
Referenced by getEncodingIndex().
const char KW_version[] static
Initial value:
= {
  ASCII_v, ASCII_e, ASCII_r, ASCII_s, ASCII_i, ASCII_o, ASCII_n, '\0'
}
Definition at line 1065 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1065 of file xmltok.cc
const char KW_yes[] static
Initial value:
= {
  ASCII_y, ASCII_e, ASCII_s,  '\0'
}
Definition at line 1078 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 1078 of file xmltok.cc
struct normal_encoding latin1_encoding static
Definition at line 480 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 480 of file xmltok.cc
Referenced by XmlInitUnknownEncoding().
struct normal_encoding little2_encoding static
Definition at line 739 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 739 of file xmltok.cc
struct normal_encoding utf8_encoding static
Definition at line 398 of file xmltok.cc.
View newest version in sPHENIX GitHub at line 398 of file xmltok.cc