ECCE @ EIC Software: CLHEP::RandBit Class Reference
CLHEP::RandBit Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandBit.h>
Public Member Functions
RandBit (HepRandomEngine &anEngine)
RandBit (HepRandomEngine &anEngine, double width)
RandBit (HepRandomEngine &anEngine, double a, double b)
RandBit (HepRandomEngine *anEngine)
RandBit (HepRandomEngine *anEngine, double width)
RandBit (HepRandomEngine *anEngine, double a, double b)
virtual ~RandBit ()
int fireBit ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
Public Member Functions inherited from CLHEP::RandFlat
RandFlat (HepRandomEngine &anEngine)
RandFlat (HepRandomEngine &anEngine, double width)
RandFlat (HepRandomEngine &anEngine, double a, double b)
RandFlat (HepRandomEngine *anEngine)
RandFlat (HepRandomEngine *anEngine, double width)
RandFlat (HepRandomEngine *anEngine, double a, double b)
virtual ~RandFlat ()
double fire ()
double fire (double width)
double fire (double a, double b)
long fireInt (long n)
long fireInt (long a1, long n)
int fireBit ()
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double lx, double dx)
double operator() ()
double operator() (double width)
double operator() (double a, double b)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static int shootBit ()
static int shootBit (HepRandomEngine *)
static std::string distributionName ()
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
Static Public Member Functions inherited from CLHEP::RandFlat
static double shoot ()
static double shoot (double width)
static double shoot (double a, double b)
static long shootInt (long n)
static long shootInt (long a1, long n)
static int shootBit ()
static void shootArray (const int size, double *vect)
static void shootArray (const int size, double *vect, double lx, double dx)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double width)
static double shoot (HepRandomEngine *anEngine, double a, double b)
static long shootInt (HepRandomEngine *anEngine, long n)
static long shootInt (HepRandomEngine *anEngine, long a1, long n)
static int shootBit (HepRandomEngine *)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double lx, double dx)
static std::string distributionName ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 38 of file RandBit.h.
View newest version in sPHENIX GitHub at line 38 of file RandBit.h
Constructor & Destructor Documentation
CLHEP::RandBit::RandBit (HepRandomEngine & anEngine) inline
CLHEP::RandBit::RandBit (HepRandomEngine & anEngine, double width) inline
CLHEP::RandBit::RandBit (HepRandomEngine & anEngine, double a, double b) inline
CLHEP::RandBit::RandBit (HepRandomEngine * anEngine) inline
CLHEP::RandBit::RandBit (HepRandomEngine * anEngine, double width) inline
CLHEP::RandBit::RandBit (HepRandomEngine * anEngine, double a, double b) inline
CLHEP::RandBit::~RandBit () virtual
Definition at line 23 of file RandBit.cc.
View newest version in sPHENIX GitHub at line 23 of file RandBit.cc
Member Function Documentation
static std::string CLHEP::RandBit::distributionName () inline static
Definition at line 79 of file RandBit.h.
View newest version in sPHENIX GitHub at line 79 of file RandBit.h
int CLHEP::RandBit::fireBit () inline
std::istream & CLHEP::RandBit::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 32 of file RandBit.cc.
View newest version in sPHENIX GitHub at line 32 of file RandBit.cc
References CLHEP::RandFlat::get(), and name().
std::string CLHEP::RandBit::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 21 of file RandBit.cc.
View newest version in sPHENIX GitHub at line 21 of file RandBit.cc
Referenced by get(), and put().
std::ostream & CLHEP::RandBit::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 26 of file RandBit.cc.
View newest version in sPHENIX GitHub at line 26 of file RandBit.cc
References name(), and CLHEP::RandFlat::put().
static std::istream& CLHEP::RandBit::restoreDistState (std::istream & is) inline static
Definition at line 94 of file RandBit.h.
View newest version in sPHENIX GitHub at line 94 of file RandBit.h
References CLHEP::RandFlat::restoreDistState().
static std::istream& CLHEP::RandBit::restoreFullState (std::istream & is) inline static
Definition at line 86 of file RandBit.h.
View newest version in sPHENIX GitHub at line 86 of file RandBit.h
References CLHEP::RandFlat::restoreFullState().
static std::ostream& CLHEP::RandBit::saveDistState (std::ostream & os) inline static
Definition at line 90 of file RandBit.h.
View newest version in sPHENIX GitHub at line 90 of file RandBit.h
References CLHEP::RandFlat::saveDistState().
static std::ostream& CLHEP::RandBit::saveFullState (std::ostream & os) inline static
Definition at line 82 of file RandBit.h.
View newest version in sPHENIX GitHub at line 82 of file RandBit.h
References CLHEP::RandFlat::saveFullState().
static int CLHEP::RandBit::shootBit () inline static
Referenced by G4LowEnergyGammaConversion::PostStepDoIt().
static int CLHEP::RandBit::shootBit (HepRandomEngine *) inline static
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandBit.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandBit.cc