ECCE @ EIC Software: G4ElasticHNScattering Class Reference
G4ElasticHNScattering Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4ElasticHNScattering.hh>
Public Member Functions
G4ElasticHNScattering ()
virtual ~G4ElasticHNScattering ()
virtual G4bool ElasticScattering (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters) const
Private Member Functions
G4ElasticHNScattering (const G4ElasticHNScattering &right)
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
const G4ElasticHNScattering & operator= (const G4ElasticHNScattering &right)
G4bool operator== (const G4ElasticHNScattering &right) const
G4bool operator!= (const G4ElasticHNScattering &right) const
Detailed Description
Definition at line 50 of file G4ElasticHNScattering.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ElasticHNScattering.hh
Constructor & Destructor Documentation
G4ElasticHNScattering::G4ElasticHNScattering ()
Definition at line 59 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ElasticHNScattering.cc
G4ElasticHNScattering::~G4ElasticHNScattering () virtual
Definition at line 189 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 189 of file G4ElasticHNScattering.cc
G4ElasticHNScattering::G4ElasticHNScattering (const G4ElasticHNScattering & right) private
Definition at line 181 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 181 of file G4ElasticHNScattering.cc
Member Function Documentation
G4bool G4ElasticHNScattering::ElasticScattering (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters) const virtual
Definition at line 64 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ElasticHNScattering.cc
References CLHEP::HepLorentzVector::boostVector(), GaussianPt(), G4VSplitableHadron::Get4Momentum(), G4FTFParameters::GetAvaragePt2ofElasticScattering(), G4VSplitableHadron::GetPosition(), G4VSplitableHadron::GetTimeOfCreation(), G4VSplitableHadron::IncrementCollisionCount(), CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), CLHEP::HepLorentzVector::rotateY(), CLHEP::HepLorentzVector::rotateZ(), S(), G4VSplitableHadron::Set4Momentum(), G4VSplitableHadron::SetPosition(), G4VSplitableHadron::SetTimeOfCreation(), sqr(), CLHEP::HepLorentzRotation::transform(), CLHEP::HepLorentzVector::transform(), CLHEP::HepLorentzVector::vect(), and CLHEP::HepLorentzVector::z().
Referenced by G4FTFModel::ExciteParticipants(), and G4DiffractiveExcitation::ExciteParticipants_doChargeExchange().
G4ThreeVector G4ElasticHNScattering::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 164 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 164 of file G4ElasticHNScattering.cc
References G4Exp(), G4Log(), G4UniformRand, phi, and twopi.
Referenced by ElasticScattering().
G4bool G4ElasticHNScattering::operator!= (const G4ElasticHNScattering & right) const private
Definition at line 210 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 210 of file G4ElasticHNScattering.cc
const G4ElasticHNScattering & G4ElasticHNScattering::operator= (const G4ElasticHNScattering & right) private
Definition at line 194 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 194 of file G4ElasticHNScattering.cc
G4bool G4ElasticHNScattering::operator== (const G4ElasticHNScattering & right) const private
Definition at line 202 of file G4ElasticHNScattering.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ElasticHNScattering.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4ElasticHNScattering.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4ElasticHNScattering.cc