ECCE @ EIC Software: G4ParticleHPChannel Class Reference
G4ParticleHPChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPChannel.hh>
Public Member Functions
G4ParticleHPChannel (G4ParticleDefinition *projectile)
G4ParticleHPChannel ()
~G4ParticleHPChannel ()
G4double GetXsec (G4double energy)
G4double GetWeightedXsec (G4double energy, G4int isoNumber)
G4double GetFSCrossSection (G4double energy, G4int isoNumber)
G4bool IsActive (G4int isoNumber)
G4bool HasFSData (G4int isoNumber)
G4bool HasAnyData (G4int isoNumber)
G4bool Register (G4ParticleHPFinalState *theFS)
void Init (G4Element *theElement, const G4String dirName)
void Init (G4Element *theElement, const G4String dirName, const G4String fsType)
void UpdateData (G4int A, G4int Z, G4int index, G4double abundance, G4ParticleDefinition *projectile)
void UpdateData (G4int A, G4int Z, G4int M, G4int index, G4double abundance, G4ParticleDefinition *projectile)
void Harmonise (G4ParticleHPVector *&theStore, G4ParticleHPVector *theNew)
G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack, G4int isoNumber=-1)
G4int GetNiso ()
G4double GetN (G4int i)
G4double GetZ (G4int i)
G4double GetM (G4int i)
G4bool HasDataInAnyFinalState ()
void DumpInfo ()
G4String GetFSType () const
G4ParticleHPFinalState ** GetFinalStates () const
Private Attributes
G4ParticleDefinition * theProjectile
G4ParticleHPVector * theChannelData
G4ParticleHPVector * theBuffer
G4ParticleHPIsoData * theIsotopeWiseData
G4ParticleHPFinalState ** theFinalStates
G4bool * active
G4int niso
G4StableIsotopes theStableOnes
G4String theDir
G4String theFSType
G4Element * theElement
G4int registerCount
G4WendtFissionFragmentGenerator
*const wendtFissionGenerator
Detailed Description
Definition at line 57 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleHPChannel.hh
Constructor & Destructor Documentation
G4ParticleHPChannel::G4ParticleHPChannel (G4ParticleDefinition * projectile) inline
Definition at line 61 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPChannel.hh
References active, niso, registerCount, theBuffer, theChannelData, theElement, theFinalStates, theIsotopeWiseData, and theProjectile.
G4ParticleHPChannel::G4ParticleHPChannel () inline
Definition at line 75 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPChannel.hh
References active, G4Neutron::Neutron(), niso, registerCount, theBuffer, theChannelData, theElement, theFinalStates, theIsotopeWiseData, and theProjectile.
G4ParticleHPChannel::~G4ParticleHPChannel () inline
Definition at line 89 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPChannel.hh
References active, niso, theChannelData, theFinalStates, and theIsotopeWiseData.
Member Function Documentation
G4HadFinalState * G4ParticleHPChannel::ApplyYourself (const G4HadProjectile & theTrack, G4int isoNumber = -1)
Definition at line 228 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ParticleHPChannel.cc
References A(), G4WendtFissionFragmentGenerator::ApplyYourself(), G4ParticleHPFinalState::ApplyYourself(), G4cout, G4endl, G4UniformRand, G4ParticleHPManager::GetInstance(), GetM(), G4HadProjectile::GetMaterial(), G4ParticleHPFinalState::GetN(), GetN(), G4ParticleHPManager::GetReactionWhiteBoard(), G4Material::GetTemperature(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4ParticleHPIsoData::GetXsec(), G4ParticleHPFinalState::GetZ(), GetZ(), HasAnyData(), it, niso, G4ParticleHPReactionWhiteBoard::SetTargA(), G4ParticleHPReactionWhiteBoard::SetTargM(), G4ParticleHPReactionWhiteBoard::SetTargZ(), sum, theFinalStates, theIsotopeWiseData, wendtFissionGenerator, and Z.
Referenced by G4ParticleHPChannelList::ApplyYourself(), and G4FissLib::ApplyYourself().
void G4ParticleHPChannel::DumpInfo ()
Definition at line 326 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 326 of file G4ParticleHPChannel.cc
References eV, G4cout, G4endl, G4ParticleHPVector::GetEnergy(), G4Element::GetName(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetXsec(), G4ParticleHPFinalState::HasXsec(), niso, theChannelData, theDir, theElement, theFinalStates, and theFSType.
Referenced by G4ParticleHPChannelList::DumpInfo().
G4ParticleHPFinalState** G4ParticleHPChannel::GetFinalStates () const inline
Definition at line 171 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ParticleHPChannel.hh
References theFinalStates.
G4double G4ParticleHPChannel::GetFSCrossSection (G4double energy, G4int isoNumber)
Definition at line 60 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPChannel.cc
References G4ParticleHPFinalState::GetXsec(), and theFinalStates.
Referenced by G4ParticleHPChannelList::ApplyYourself().
G4String G4ParticleHPChannel::GetFSType () const inline
Definition at line 167 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ParticleHPChannel.hh
References theFSType.
G4double G4ParticleHPChannel::GetM (G4int i) inline
Definition at line 152 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ParticleHPChannel.hh
References G4ParticleHPFinalState::GetM(), and theFinalStates.
Referenced by ApplyYourself().
G4double G4ParticleHPChannel::GetN (G4int i) inline
Definition at line 150 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParticleHPChannel.hh
References G4ParticleHPFinalState::GetN(), and theFinalStates.
Referenced by G4ParticleHPChannelList::ApplyYourself(), and ApplyYourself().
G4int G4ParticleHPChannel::GetNiso () inline
Definition at line 148 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ParticleHPChannel.hh
References niso.
Referenced by G4ParticleHPChannelList::ApplyYourself().
G4double G4ParticleHPChannel::GetWeightedXsec (G4double energy, G4int isoNumber)
Definition at line 55 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPChannel.cc
References G4ParticleHPIsoData::GetXsec(), and theIsotopeWiseData.
Referenced by G4ParticleHPChannelList::ApplyYourself().
G4double G4ParticleHPChannel::GetXsec (G4double energy)
Definition at line 50 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPChannel.cc
References G4ParticleHPVector::GetXsec(), max, and theChannelData.
Referenced by G4FissLib::ApplyYourself().
G4double G4ParticleHPChannel::GetZ (G4int i) inline
Definition at line 151 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParticleHPChannel.hh
References G4ParticleHPFinalState::GetZ(), and theFinalStates.
Referenced by G4ParticleHPChannelList::ApplyYourself(), and ApplyYourself().
void G4ParticleHPChannel::Harmonise (G4ParticleHPVector *& theStore, G4ParticleHPVector * theNew)
Definition at line 183 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 183 of file G4ParticleHPChannel.cc
References a, kdfinder::abs(), G4ParticleHPVector::GetEnergy(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetXsec(), max, n, G4ParticleHPVector::SetData(), t, and tmp.
Referenced by UpdateData().
G4bool G4ParticleHPChannel::HasAnyData (G4int isoNumber) inline
Definition at line 132 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleHPChannel.hh
References G4ParticleHPFinalState::HasAnyData(), and theFinalStates.
Referenced by ApplyYourself(), HasDataInAnyFinalState(), and UpdateData().
G4bool G4ParticleHPChannel::HasDataInAnyFinalState () inline
Definition at line 154 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPChannel.hh
References HasAnyData(), niso, and theFinalStates.
Referenced by Register().
G4bool G4ParticleHPChannel::HasFSData (G4int isoNumber) inline
Definition at line 130 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ParticleHPChannel.hh
References G4ParticleHPFinalState::HasFSData(), and theFinalStates.
void G4ParticleHPChannel::Init (G4Element * theElement, const G4String dirName)
Definition at line 72 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPChannel.cc
References theDir, and theElement.
Referenced by G4FissLib::G4FissLib(), Init(), and G4ParticleHPChannelList::Register().
void G4ParticleHPChannel::Init (G4Element * theElement, const G4String dirName, const G4String fsType)
Definition at line 66 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPChannel.cc
References Init(), and theFSType.
G4bool G4ParticleHPChannel::IsActive (G4int isoNumber) inline
Definition at line 128 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleHPChannel.hh
References active.
G4bool G4ParticleHPChannel::Register (G4ParticleHPFinalState * theFS)
Definition at line 78 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPChannel.cc
References A(), active, G4lrint(), G4StableIsotopes::GetAbundance(), G4StableIsotopes::GetFirstIsotope(), G4Element::GetIsotope(), G4StableIsotopes::GetIsotopeNucleonCount(), G4Isotope::Getm(), G4Isotope::GetN(), G4StableIsotopes::GetNumberOfIsotopes(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZ(), HasDataInAnyFinalState(), G4ParticleHPVector::Hash(), G4ParticleHPFinalState::New(), niso, perCent, registerCount, G4ParticleHPFinalState::SetA_Z(), G4ParticleHPFinalState::SetProjectile(), theChannelData, theElement, theFinalStates, theIsotopeWiseData, theProjectile, theStableOnes, UpdateData(), and Z.
Referenced by G4FissLib::G4FissLib(), and G4ParticleHPChannelList::Register().
void G4ParticleHPChannel::UpdateData (G4int A, G4int Z, G4int index, G4double abundance, G4ParticleDefinition * projectile) inline
Definition at line 141 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ParticleHPChannel.hh
References UpdateData().
Referenced by Register(), and UpdateData().
void G4ParticleHPChannel::UpdateData (G4int A, G4int Z, G4int M, G4int index, G4double abundance, G4ParticleDefinition * projectile)
Definition at line 154 of file G4ParticleHPChannel.cc.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPChannel.cc
References active, G4ParticleHPIsoData::FillChannelData(), G4ParticleHPFinalState::GetXsec(), Harmonise(), HasAnyData(), G4ParticleHPIsoData::Init(), G4ParticleHPFinalState::Init(), G4WendtFissionFragmentGenerator::InitializeANucleus(), G4ParticleHPIsoData::MakeChannelData(), theBuffer, theChannelData, theDir, theFinalStates, theFSType, theIsotopeWiseData, G4ParticleHPVector::Times(), and wendtFissionGenerator.
Member Data Documentation
G4bool* G4ParticleHPChannel::active private
Definition at line 183 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 183 of file G4ParticleHPChannel.hh
Referenced by G4ParticleHPChannel(), IsActive(), Register(), UpdateData(), and ~G4ParticleHPChannel().
G4int G4ParticleHPChannel::niso private
Definition at line 184 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ParticleHPChannel.hh
Referenced by ApplyYourself(), DumpInfo(), G4ParticleHPChannel(), GetNiso(), HasDataInAnyFinalState(), Register(), and ~G4ParticleHPChannel().
G4int G4ParticleHPChannel::registerCount private
Definition at line 192 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ParticleHPChannel.hh
Referenced by G4ParticleHPChannel(), and Register().
G4ParticleHPVector* G4ParticleHPChannel::theBuffer private
Definition at line 179 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPChannel.hh
Referenced by G4ParticleHPChannel(), and UpdateData().
G4ParticleHPVector* G4ParticleHPChannel::theChannelData private
Definition at line 178 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ParticleHPChannel.hh
Referenced by DumpInfo(), G4ParticleHPChannel(), GetXsec(), Register(), UpdateData(), and ~G4ParticleHPChannel().
G4String G4ParticleHPChannel::theDir private
Definition at line 188 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4ParticleHPChannel.hh
Referenced by DumpInfo(), Init(), and UpdateData().
G4Element* G4ParticleHPChannel::theElement private
Definition at line 190 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 190 of file G4ParticleHPChannel.hh
Referenced by DumpInfo(), G4ParticleHPChannel(), Init(), and Register().
G4ParticleHPFinalState** G4ParticleHPChannel::theFinalStates private
Definition at line 182 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4ParticleHPChannel.hh
Referenced by ApplyYourself(), DumpInfo(), G4ParticleHPChannel(), GetFinalStates(), GetFSCrossSection(), GetM(), GetN(), GetZ(), HasAnyData(), HasDataInAnyFinalState(), HasFSData(), Register(), UpdateData(), and ~G4ParticleHPChannel().
G4String G4ParticleHPChannel::theFSType private
Definition at line 189 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 189 of file G4ParticleHPChannel.hh
Referenced by DumpInfo(), GetFSType(), Init(), and UpdateData().
G4ParticleHPIsoData* G4ParticleHPChannel::theIsotopeWiseData private
Definition at line 181 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4ParticleHPChannel.hh
Referenced by ApplyYourself(), G4ParticleHPChannel(), GetWeightedXsec(), Register(), UpdateData(), and ~G4ParticleHPChannel().
G4ParticleDefinition* G4ParticleHPChannel::theProjectile private
Definition at line 176 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ParticleHPChannel.hh
Referenced by G4ParticleHPChannel(), and Register().
G4StableIsotopes G4ParticleHPChannel::theStableOnes private
Definition at line 186 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 186 of file G4ParticleHPChannel.hh
Referenced by Register().
G4WendtFissionFragmentGenerator* const G4ParticleHPChannel::wendtFissionGenerator private
Definition at line 194 of file G4ParticleHPChannel.hh.
View newest version in sPHENIX GitHub at line 194 of file G4ParticleHPChannel.hh
Referenced by ApplyYourself(), and UpdateData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPChannel.cc