ECCE @ EIC Software: G3MedTableEntry Class Reference
G3MedTableEntry Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MedTableEntry.hh>
Public Member Functions
G3MedTableEntry (G4int id, G4Material *material, G4MagneticField *field, G4UserLimits *limits, G4int isvol)
G3MedTableEntry (const G3MedTableEntry &right)
virtual ~G3MedTableEntry ()
G3MedTableEntry & operator= (const G3MedTableEntry &right)
G4bool operator== (const G3MedTableEntry &right) const
G4bool operator!= (const G3MedTableEntry &right) const
void SetMaterial (G4Material *material)
void SetField (G4MagneticField *field)
void SetLimits (G4UserLimits *limits)
void SetISVOL (G4int isvol)
G4int GetID () const
G4Material * GetMaterial () const
G4MagneticField * GetField () const
G4UserLimits * GetLimits () const
G4int GetISVOL () const
Private Attributes
G4int fID
G4Material * fMaterial
G4MagneticField * fField
G4UserLimits * fLimits
G4int fISVOL
Detailed Description
Definition at line 48 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 48 of file G3MedTableEntry.hh
Constructor & Destructor Documentation
G3MedTableEntry::G3MedTableEntry (G4int id, G4Material * material, G4MagneticField * field, G4UserLimits * limits, G4int isvol)
Definition at line 36 of file G3MedTableEntry.cc.
View newest version in sPHENIX GitHub at line 36 of file G3MedTableEntry.cc
G3MedTableEntry::G3MedTableEntry (const G3MedTableEntry & right)
Definition at line 45 of file G3MedTableEntry.cc.
View newest version in sPHENIX GitHub at line 45 of file G3MedTableEntry.cc
G3MedTableEntry::~G3MedTableEntry () virtual
Definition at line 53 of file G3MedTableEntry.cc.
View newest version in sPHENIX GitHub at line 53 of file G3MedTableEntry.cc
Member Function Documentation
G4MagneticField * G3MedTableEntry::GetField () const inline
Definition at line 107 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 107 of file G3MedTableEntry.hh
References fField.
Referenced by operator=().
G4int G3MedTableEntry::GetID () const inline
Definition at line 101 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 101 of file G3MedTableEntry.hh
References fID.
Referenced by G3MedTable::get(), operator=(), and operator==().
G4int G3MedTableEntry::GetISVOL () const inline
Definition at line 113 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 113 of file G3MedTableEntry.hh
References fISVOL.
Referenced by G3toG4BuildLVTree(), and operator=().
G4UserLimits * G3MedTableEntry::GetLimits () const inline
Definition at line 110 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 110 of file G3MedTableEntry.hh
References fLimits.
Referenced by operator=().
G4Material * G3MedTableEntry::GetMaterial () const inline
Definition at line 104 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 104 of file G3MedTableEntry.hh
References fMaterial.
Referenced by G3toG4BuildLVTree(), and operator=().
G4bool G3MedTableEntry::operator!= (const G3MedTableEntry & right) const
Definition at line 75 of file G3MedTableEntry.cc.
View newest version in sPHENIX GitHub at line 75 of file G3MedTableEntry.cc
G3MedTableEntry & G3MedTableEntry::operator= (const G3MedTableEntry & right)
Definition at line 56 of file G3MedTableEntry.cc.
View newest version in sPHENIX GitHub at line 56 of file G3MedTableEntry.cc
References fField, fID, fISVOL, fLimits, fMaterial, GetField(), GetID(), GetISVOL(), GetLimits(), and GetMaterial().
G4bool G3MedTableEntry::operator== (const G3MedTableEntry & right) const
Definition at line 67 of file G3MedTableEntry.cc.
View newest version in sPHENIX GitHub at line 67 of file G3MedTableEntry.cc
References fID, and GetID().
void G3MedTableEntry::SetField (G4MagneticField * field) inline
Definition at line 92 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 92 of file G3MedTableEntry.hh
References fField.
void G3MedTableEntry::SetISVOL (G4int isvol) inline
Definition at line 98 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 98 of file G3MedTableEntry.hh
References fISVOL.
void G3MedTableEntry::SetLimits (G4UserLimits * limits) inline
Definition at line 95 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 95 of file G3MedTableEntry.hh
References fLimits.
void G3MedTableEntry::SetMaterial (G4Material * material) inline
Definition at line 89 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 89 of file G3MedTableEntry.hh
References fMaterial, and material().
Member Data Documentation
G4MagneticField* G3MedTableEntry::fField private
Definition at line 80 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 80 of file G3MedTableEntry.hh
Referenced by GetField(), operator=(), and SetField().
G4int G3MedTableEntry::fID private
Definition at line 78 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 78 of file G3MedTableEntry.hh
Referenced by GetID(), operator=(), and operator==().
G4int G3MedTableEntry::fISVOL private
Definition at line 82 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 82 of file G3MedTableEntry.hh
Referenced by GetISVOL(), operator=(), and SetISVOL().
G4UserLimits* G3MedTableEntry::fLimits private
Definition at line 81 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 81 of file G3MedTableEntry.hh
Referenced by GetLimits(), operator=(), and SetLimits().
G4Material* G3MedTableEntry::fMaterial private
Definition at line 79 of file G3MedTableEntry.hh.
View newest version in sPHENIX GitHub at line 79 of file G3MedTableEntry.hh
Referenced by GetMaterial(), operator=(), and SetMaterial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MedTableEntry.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3MedTableEntry.cc