ECCE @ EIC Software: GB04BOptnBremSplitting Class Reference
GB04BOptnBremSplitting Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB04/include/GB04BOptnBremSplitting.hh>
Public Member Functions
GB04BOptnBremSplitting (G4String name)
virtual ~GB04BOptnBremSplitting ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
void SetSplittingFactor (G4int splittingFactor)
G4int GetSplittingFactor () const
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4int fSplittingFactor
G4ParticleChange fParticleChange
Detailed Description
Definition at line 47 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 47 of file GB04BOptnBremSplitting.hh
Constructor & Destructor Documentation
GB04BOptnBremSplitting::GB04BOptnBremSplitting (G4String name)
Definition at line 37 of file GB04BOptnBremSplitting.cc.
View newest version in sPHENIX GitHub at line 37 of file GB04BOptnBremSplitting.cc
GB04BOptnBremSplitting::~GB04BOptnBremSplitting () virtual
Definition at line 46 of file GB04BOptnBremSplitting.cc.
View newest version in sPHENIX GitHub at line 46 of file GB04BOptnBremSplitting.cc
Member Function Documentation
G4VParticleChange * GB04BOptnBremSplitting::ApplyFinalStateBiasing (const G4BiasingProcessInterface * callingProcess, const G4Track * track, const G4Step * step, G4bool &) virtual
Implements G4VBiasingOperation.
Definition at line 52 of file GB04BOptnBremSplitting.cc.
View newest version in sPHENIX GitHub at line 52 of file GB04BOptnBremSplitting.cc
References G4ParticleChange::AddSecondary(), G4VParticleChange::Clear(), fParticleChange, fSplittingFactor, G4VParticleChange::GetNumberOfSecondaries(), G4ParticleChangeForLoss::GetProposedKineticEnergy(), G4ParticleChangeForLoss::GetProposedMomentumDirection(), G4VParticleChange::GetSecondary(), G4VParticleChange::GetTrackStatus(), G4Track::GetWeight(), G4BiasingProcessInterface::GetWrappedProcess(), G4ParticleChange::Initialize(), G4VProcess::PostStepDoIt(), G4VParticleChange::SetNumberOfSecondaries(), G4VParticleChange::SetSecondaryWeightByProcess(), and G4Track::SetWeight().
virtual G4double GB04BOptnBremSplitting::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) inline virtual
Implements G4VBiasingOperation.
Definition at line 71 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 71 of file GB04BOptnBremSplitting.hh
References DBL_MAX.
virtual G4VParticleChange* GB04BOptnBremSplitting::GenerateBiasingFinalState (const G4Track * , const G4Step *) inline virtual
Implements G4VBiasingOperation.
Definition at line 75 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 75 of file GB04BOptnBremSplitting.hh
G4int GB04BOptnBremSplitting::GetSplittingFactor () const inline
Definition at line 87 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 87 of file GB04BOptnBremSplitting.hh
References fSplittingFactor.
virtual const G4VBiasingInteractionLaw* GB04BOptnBremSplitting::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) inline virtual
Implements G4VBiasingOperation.
Definition at line 60 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 60 of file GB04BOptnBremSplitting.hh
void GB04BOptnBremSplitting::SetSplittingFactor (G4int splittingFactor) inline
Definition at line 85 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 85 of file GB04BOptnBremSplitting.hh
References fSplittingFactor.
Referenced by GB04BOptrBremSplitting::StartRun().
Member Data Documentation
G4ParticleChange GB04BOptnBremSplitting::fParticleChange private
Definition at line 91 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 91 of file GB04BOptnBremSplitting.hh
Referenced by ApplyFinalStateBiasing().
G4int GB04BOptnBremSplitting::fSplittingFactor private
Definition at line 90 of file GB04BOptnBremSplitting.hh.
View newest version in sPHENIX GitHub at line 90 of file GB04BOptnBremSplitting.hh
Referenced by ApplyFinalStateBiasing(), GetSplittingFactor(), and SetSplittingFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB04/include/GB04BOptnBremSplitting.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB04/src/GB04BOptnBremSplitting.cc