ECCE @ EIC Software: RE06DetectorMessenger Class Reference
RE06DetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06DetectorMessenger.hh>
Public Member Functions
RE06DetectorMessenger (RE06DetectorConstruction *)
virtual ~RE06DetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
virtual G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void UpdateMaterialList ()
Private Attributes
RE06DetectorConstruction * fDetector
G4UIdirectory * fDirectory
G4UIcmdWithAString * fAbsMaterialCmd
G4UIcmdWithAString * fGapMaterialCmd
G4UIcmdWithAnInteger * fNumLayerCmd
G4UIcmdWithABool * fSerialCmd
G4UIcmdWithAnInteger * fVerboseCmd
G4UIcmdWithABool * fAddMaterialCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 43 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 43 of file RE06DetectorMessenger.hh
Constructor & Destructor Documentation
RE06DetectorMessenger::RE06DetectorMessenger (RE06DetectorConstruction * det)
Definition at line 42 of file RE06DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 42 of file RE06DetectorMessenger.cc
References G4UIcommand::AvailableForStates(), fAbsMaterialCmd, fAddMaterialCmd, fDirectory, fGapMaterialCmd, fNumLayerCmd, fSerialCmd, fVerboseCmd, G4State_Idle, G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), G4UIcmdWithAString::SetCandidates(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), and G4UIcommand::SetRange().
RE06DetectorMessenger::~RE06DetectorMessenger () virtual
Definition at line 102 of file RE06DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 102 of file RE06DetectorMessenger.cc
References fAbsMaterialCmd, fDirectory, fGapMaterialCmd, fNumLayerCmd, and fSerialCmd.
Member Function Documentation
G4String RE06DetectorMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 136 of file RE06DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 136 of file RE06DetectorMessenger.cc
References G4UIcommand::ConvertToString(), fAbsMaterialCmd, fDetector, fGapMaterialCmd, fNumLayerCmd, fSerialCmd, fVerboseCmd, RE06DetectorConstruction::GetAbsorberMaterial(), RE06DetectorConstruction::GetGapMaterial(), RE06DetectorConstruction::GetNumberOfLayers(), RE06DetectorConstruction::GetVerboseLevel(), and RE06DetectorConstruction::IsSerial().
void RE06DetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 111 of file RE06DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 111 of file RE06DetectorMessenger.cc
References RE06DetectorConstruction::AddMaterial(), fAbsMaterialCmd, fAddMaterialCmd, fDetector, fGapMaterialCmd, fNumLayerCmd, fSerialCmd, fVerboseCmd, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithAnInteger::GetNewIntValue(), RE06DetectorConstruction::SetAbsorberMaterial(), RE06DetectorConstruction::SetGapMaterial(), RE06DetectorConstruction::SetNumberOfLayers(), RE06DetectorConstruction::SetSerialGeometry(), RE06DetectorConstruction::SetVerboseLevel(), and UpdateMaterialList().
void RE06DetectorMessenger::UpdateMaterialList () private
Definition at line 163 of file RE06DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 163 of file RE06DetectorMessenger.cc
References fAbsMaterialCmd, fGapMaterialCmd, G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), and G4UIcmdWithAString::SetCandidates().
Referenced by SetNewValue().
Member Data Documentation
G4UIcmdWithAString* RE06DetectorMessenger::fAbsMaterialCmd private
Definition at line 58 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file RE06DetectorMessenger.hh
Referenced by GetCurrentValue(), RE06DetectorMessenger(), SetNewValue(), UpdateMaterialList(), and ~RE06DetectorMessenger().
G4UIcmdWithABool* RE06DetectorMessenger::fAddMaterialCmd private
Definition at line 63 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file RE06DetectorMessenger.hh
Referenced by RE06DetectorMessenger(), and SetNewValue().
RE06DetectorConstruction* RE06DetectorMessenger::fDetector private
Definition at line 55 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file RE06DetectorMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIdirectory* RE06DetectorMessenger::fDirectory private
Definition at line 57 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file RE06DetectorMessenger.hh
Referenced by RE06DetectorMessenger(), and ~RE06DetectorMessenger().
G4UIcmdWithAString* RE06DetectorMessenger::fGapMaterialCmd private
Definition at line 59 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file RE06DetectorMessenger.hh
Referenced by GetCurrentValue(), RE06DetectorMessenger(), SetNewValue(), UpdateMaterialList(), and ~RE06DetectorMessenger().
G4UIcmdWithAnInteger* RE06DetectorMessenger::fNumLayerCmd private
Definition at line 60 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file RE06DetectorMessenger.hh
Referenced by GetCurrentValue(), RE06DetectorMessenger(), SetNewValue(), and ~RE06DetectorMessenger().
G4UIcmdWithABool* RE06DetectorMessenger::fSerialCmd private
Definition at line 61 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file RE06DetectorMessenger.hh
Referenced by GetCurrentValue(), RE06DetectorMessenger(), SetNewValue(), and ~RE06DetectorMessenger().
G4UIcmdWithAnInteger* RE06DetectorMessenger::fVerboseCmd private
Definition at line 62 of file RE06DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file RE06DetectorMessenger.hh
Referenced by GetCurrentValue(), RE06DetectorMessenger(), and SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06DetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/src/RE06DetectorMessenger.cc