ECCE @ EIC Software: UltraDetectorConstruction Class Reference
UltraDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/air_shower/include/UltraDetectorConstruction.hh>
Public Member Functions
UltraDetectorConstruction ()
~UltraDetectorConstruction ()
G4VPhysicalVolume * Construct ()
void ConstructSDandField ()
void SetReflectionType (G4String)
G4double GetLambdaMin () const
G4double GetLambdaMax () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void ConstructUVscope ()
void ConstructReflector ()
void SetReflectorOpticalProperties ()
void ConstructTableMaterials ()
Private Attributes
UltraDetectorMessenger * fDetectorMessenger
G4VPhysicalVolume * fWorld_phys
UltraFresnelLens * FresnelLens
G4OpticalSurface * fReflectorOpticalSurface
G4LogicalVolume * logicalPMT
G4LogicalVolume * fReflectorLog
G4String fReflectionType
G4bool fIsReflectorConstructed
G4double lambda_min
G4double lambda_max
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 62 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 62 of file UltraDetectorConstruction.hh
Constructor & Destructor Documentation
UltraDetectorConstruction::UltraDetectorConstruction ()
Definition at line 79 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 79 of file UltraDetectorConstruction.cc
References ConstructTableMaterials(), fDetectorMessenger, lambda_max, lambda_min, and nm.
UltraDetectorConstruction::~UltraDetectorConstruction ()
Definition at line 96 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 96 of file UltraDetectorConstruction.cc
References fDetectorMessenger, and fReflectorOpticalSurface.
Member Function Documentation
G4VPhysicalVolume * UltraDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 105 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 105 of file UltraDetectorConstruction.cc
References ConstructUVscope(), fIsReflectorConstructed, fWorld_phys, G4cout, G4endl, G4VisAttributes::GetInvisible(), G4Material::GetMaterial(), m, G4VisAttributes::SetForceWireframe(), G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
void UltraDetectorConstruction::ConstructReflector () private
Definition at line 352 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 352 of file UltraDetectorConstruction.cc
References G4MaterialPropertiesTable::AddProperty(), source.hepunit::c_light, cm, dielectric_dielectric, fIsReflectorConstructed, fReflectorLog, fReflectorOpticalSurface, fWorld_phys, G4RunManager::GeometryHasBeenModified(), G4MTRunManager::GetMasterRunManager(), G4Material::GetMaterial(), G4RunManager::GetRunManager(), source.hepunit::h_Planck, lambda_max, lambda_min, m, pi, G4VisAttributes::SetForceWireframe(), G4OpticalSurface::SetMaterialPropertiesTable(), G4OpticalSurface::SetModel(), G4OpticalSurface::SetType(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), unified, x, y, and z.
Referenced by SetReflectionType().
void UltraDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 156 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 156 of file UltraDetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4SDManager::GetSDMpointer(), logicalPMT, and G4VUserDetectorConstruction::SetSensitiveDetector().
void UltraDetectorConstruction::ConstructTableMaterials () private
Definition at line 165 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 165 of file UltraDetectorConstruction.cc
References a, G4Material::AddElement(), G4MaterialPropertiesTable::AddEntry(), G4MaterialPropertiesTable::AddProperty(), source.hepunit::c_light, cm3, energy, Acts::UnitConstants::g, G4cout, G4endl, G4Log(), G4Material::GetMaterialTable(), source.hepunit::h_Planck, kInfinity, lambda_max, lambda_min, mm, mole, nm, G4DRCALO::SETTING::Quartz, G4Material::SetMaterialPropertiesTable(), and z.
Referenced by UltraDetectorConstruction().
void UltraDetectorConstruction::ConstructUVscope () private
Definition at line 424 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 424 of file UltraDetectorConstruction.cc
References G4MaterialPropertiesTable::AddProperty(), source.hepunit::c_light, cm, dielectric_dielectric, FresnelLens, fWorld_phys, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4Material::GetMaterial(), UltraFresnelLens::GetPhysicalVolume(), UltraFresnelLens::GetThickness(), G4Tubs::GetZHalfLength(), groundfrontpainted, source.hepunit::h_Planck, lambda_max, lambda_min, logicalPMT, m, mm, pi, G4DRCALO::SETTING::Quartz, G4OpticalSurface::SetFinish(), G4OpticalSurface::SetMaterialPropertiesTable(), G4OpticalSurface::SetModel(), G4OpticalSurface::SetType(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), twopi, and unified.
Referenced by Construct().
G4double UltraDetectorConstruction::GetLambdaMax () const inline
Definition at line 75 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file UltraDetectorConstruction.hh
References lambda_max.
Referenced by UltraPrimaryGeneratorAction::GeneratePrimaries().
G4double UltraDetectorConstruction::GetLambdaMin () const inline
Definition at line 74 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file UltraDetectorConstruction.hh
References lambda_min.
Referenced by UltraPrimaryGeneratorAction::GeneratePrimaries().
void UltraDetectorConstruction::SetReflectionType (G4String rtype)
Definition at line 604 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 604 of file UltraDetectorConstruction.cc
References ConstructReflector(), fIsReflectorConstructed, fReflectionType, G4MTRunManager::GetMasterRunManager(), G4RunManager::GetRunManager(), G4RunManager::ReinitializeGeometry(), and SetReflectorOpticalProperties().
void UltraDetectorConstruction::SetReflectorOpticalProperties () private
Definition at line 407 of file UltraDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 407 of file UltraDetectorConstruction.cc
References fReflectionType, fReflectorOpticalSurface, G4cout, G4endl, groundfrontpainted, polishedfrontpainted, and G4OpticalSurface::SetFinish().
Referenced by SetReflectionType().
Member Data Documentation
UltraDetectorMessenger* UltraDetectorConstruction::fDetectorMessenger private
Definition at line 88 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file UltraDetectorConstruction.hh
Referenced by UltraDetectorConstruction(), and ~UltraDetectorConstruction().
G4bool UltraDetectorConstruction::fIsReflectorConstructed private
Definition at line 95 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file UltraDetectorConstruction.hh
Referenced by Construct(), ConstructReflector(), and SetReflectionType().
G4String UltraDetectorConstruction::fReflectionType private
Definition at line 94 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file UltraDetectorConstruction.hh
Referenced by SetReflectionType(), and SetReflectorOpticalProperties().
G4LogicalVolume* UltraDetectorConstruction::fReflectorLog private
Definition at line 93 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 93 of file UltraDetectorConstruction.hh
Referenced by ConstructReflector().
G4OpticalSurface* UltraDetectorConstruction::fReflectorOpticalSurface private
Definition at line 91 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file UltraDetectorConstruction.hh
Referenced by ConstructReflector(), SetReflectorOpticalProperties(), and ~UltraDetectorConstruction().
UltraFresnelLens* UltraDetectorConstruction::FresnelLens private
Definition at line 90 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file UltraDetectorConstruction.hh
Referenced by ConstructUVscope().
G4VPhysicalVolume* UltraDetectorConstruction::fWorld_phys private
Definition at line 89 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file UltraDetectorConstruction.hh
Referenced by Construct(), ConstructReflector(), and ConstructUVscope().
G4double UltraDetectorConstruction::lambda_max private
Definition at line 98 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 98 of file UltraDetectorConstruction.hh
Referenced by ConstructReflector(), ConstructTableMaterials(), ConstructUVscope(), GetLambdaMax(), and UltraDetectorConstruction().
G4double UltraDetectorConstruction::lambda_min private
Definition at line 97 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file UltraDetectorConstruction.hh
Referenced by ConstructReflector(), ConstructTableMaterials(), ConstructUVscope(), GetLambdaMin(), and UltraDetectorConstruction().
G4LogicalVolume* UltraDetectorConstruction::logicalPMT private
Definition at line 92 of file UltraDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file UltraDetectorConstruction.hh
Referenced by ConstructSDandField(), and ConstructUVscope().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/air_shower/include/UltraDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/air_shower/src/UltraDetectorConstruction.cc