ECCE @ EIC Software: G4WentzelVIModel Class Reference
G4WentzelVIModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WentzelVIModel.hh>
Public Member Functions
G4WentzelVIModel (G4bool comb=true, const G4String &nam="WentzelVIUni")
virtual ~G4WentzelVIModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual void StartTracking (G4Track *) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double KineticEnergy, G4double AtomicNumber, G4double AtomicWeight=0., G4double cut=DBL_MAX, G4double emax=DBL_MAX) override
virtual G4ThreeVector & SampleScattering (const G4ThreeVector &, G4double safety) override
virtual G4double ComputeTruePathLengthLimit (const G4Track &track, G4double &currentMinimalStep) override
virtual G4double ComputeGeomPathLength (G4double truePathLength) override
virtual G4double ComputeTrueStepLength (G4double geomStepLength) override
void SetFixedCut (G4double)
G4double GetFixedCut () const
void SetWVICrossSection (G4WentzelOKandVIxSection *)
G4WentzelOKandVIxSection * GetWVICrossSection ()
void SetUseSecondMoment (G4bool)
G4bool UseSecondMoment () const
G4PhysicsTable * GetSecondMomentTable ()
G4double SecondMoment (const G4ParticleDefinition *, const G4MaterialCutsCouple *, G4double kineticEnergy)
void SetSingleScatteringFactor (G4double)
void DefineMaterial (const G4MaterialCutsCouple *)
Public Member Functions inherited from G4VMscModel
G4VMscModel (const G4String &nam)
~G4VMscModel () override
void InitialiseParameters (const G4ParticleDefinition *)
void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double tmax) override
void SetStepLimitType (G4MscStepLimitType)
void SetLateralDisplasmentFlag (G4bool val)
void SetRangeFactor (G4double)
void SetGeomFactor (G4double)
void SetSkin (G4double)
void SetLambdaLimit (G4double)
void SetSafetyFactor (G4double)
void SetSampleZ (G4bool)
G4VEnergyLossProcess * GetIonisation () const
void SetIonisation (G4VEnergyLossProcess *, const G4ParticleDefinition *part)
G4double ComputeSafety (const G4ThreeVector &position, G4double limit=DBL_MAX)
G4double ComputeGeomLimit (const G4Track &, G4double &presafety, G4double limit)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double GetEnergy (const G4ParticleDefinition *part, G4double range, const G4MaterialCutsCouple *couple)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy, G4double logKinEnergy)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
G4double ComputeTransportXSectionPerVolume (G4double cosTheta)
void SetupParticle (const G4ParticleDefinition *)
Protected Member Functions inherited from G4VMscModel
G4ParticleChangeForMSC * GetParticleChangeForMSC (const G4ParticleDefinition *p=nullptr)
G4double ConvertTrueToGeom (G4double &tLength, G4double &gLength)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
G4WentzelOKandVIxSection * wokvi
G4double tlimitminfix
G4double ssFactor
G4double invssFactor
G4double preKinEnergy
G4double tPathLength
G4double zPathLength
G4double lambdaeff
G4double currentRange
G4double cosTetMaxNuc
G4int currentMaterialIndex
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const G4ParticleDefinition * particle
G4ParticleChangeForMSC * fParticleChange
const G4DataVector * currentCuts
G4double invsqrt12
G4double fixedCut
G4double effKinEnergy
G4double cosThetaMin
G4double cosThetaMax
G4PhysicsTable * fSecondMoments
size_t idx2
G4int minNCollisions
G4int nelments
std::vector< G4double > xsecn
std::vector< G4double > prob
G4double xtsec
G4double numlimit
G4double lowEnergyLimit
G4bool singleScatteringMode
G4bool isCombined
G4bool useSecondMoment
Protected Attributes inherited from G4VMscModel
G4double facrange
G4double facgeom
G4double facsafety
G4double skin
G4double dtrl
G4double lambdalimit
G4double geomMin
G4double geomMax
G4ThreeVector fDisplacement
G4MscStepLimitType steppingAlgorithm
G4bool samplez
G4bool latDisplasment
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4double ComputeSecondMoment (const G4ParticleDefinition *, G4double kineticEnergy)
G4WentzelVIModel & operator= (const G4WentzelVIModel &right)=delete
G4WentzelVIModel (const G4WentzelVIModel &)=delete
Detailed Description
Definition at line 65 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4WentzelVIModel.hh
Constructor & Destructor Documentation
G4WentzelVIModel::G4WentzelVIModel (G4bool comb = true, const G4String & nam = "WentzelVIUni") explicit
Definition at line 73 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 73 of file G4WentzelVIModel.cc
References cosTetMaxNuc, currentCuts, currentMaterial, currentMaterialIndex, currentRange, effKinEnergy, eV, fixedCut, fParticleChange, invsqrt12, isCombined, lambdaeff, lowEnergyLimit, minNCollisions, mm, nelments, particle, preKinEnergy, prob, SetSingleScatteringFactor(), tlimitminfix, tPathLength, wokvi, xsecn, xtsec, and zPathLength.
G4WentzelVIModel::~G4WentzelVIModel () virtual
Definition at line 111 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 111 of file G4WentzelVIModel.cc
References fSecondMoments, G4VEmModel::IsMaster(), and wokvi.
G4WentzelVIModel::G4WentzelVIModel (const G4WentzelVIModel &) private delete
Member Function Documentation
G4double G4WentzelVIModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double KineticEnergy, G4double AtomicNumber, G4double AtomicWeight = 0., G4double cut = DBL_MAX, G4double emax = DBL_MAX) override virtual
Reimplemented from G4VEmModel.
Reimplemented in G4WentzelVIRelModel.
Definition at line 223 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 223 of file G4WentzelVIModel.cc
References G4WentzelOKandVIxSection::ComputeTransportCrossSectionPerAtom(), cosTetMaxNuc, Acts::VectorHelpers::cross(), G4VEmModel::CurrentCouple(), currentMaterial, DefineMaterial(), FatalException, fixedCut, G4Exception(), G4lrint(), lowEnergyLimit, G4WentzelOKandVIxSection::SetupKinematic(), SetupParticle(), G4WentzelOKandVIxSection::SetupTarget(), and wokvi.
G4double G4WentzelVIModel::ComputeGeomPathLength (G4double truePathLength) override virtual
Implements G4VMscModel.
Definition at line 365 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 365 of file G4WentzelVIModel.cc
References ComputeTransportXSectionPerVolume(), cosTetMaxNuc, cosThetaMin, currentCouple, currentMaterial, currentRange, DBL_MAX, e1, effKinEnergy, G4Exp(), G4VMscModel::GetEnergy(), G4VMscModel::GetTransportMeanFreePath(), lambdaeff, minNCollisions, numlimit, particle, preKinEnergy, G4WentzelOKandVIxSection::SetupKinematic(), singleScatteringMode, tPathLength, wokvi, xtsec, and zPathLength.
G4double G4WentzelVIModel::ComputeSecondMoment (const G4ParticleDefinition * p, G4double kineticEnergy) private
Definition at line 771 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 771 of file G4WentzelVIModel.cc
References G4WentzelOKandVIxSection::ComputeSecondTransportMoment(), cosTetMaxNuc, currentMaterial, currentMaterialIndex, fixedCut, G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), G4WentzelOKandVIxSection::SetupKinematic(), SetupParticle(), G4WentzelOKandVIxSection::SetupTarget(), and wokvi.
Referenced by Initialise(), and SecondMoment().
G4double G4WentzelVIModel::ComputeTransportXSectionPerVolume (G4double cosTheta) protected
Definition at line 716 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 716 of file G4WentzelVIModel.cc
References G4WentzelOKandVIxSection::ComputeElectronCrossSection(), G4WentzelOKandVIxSection::ComputeNuclearCrossSection(), G4WentzelOKandVIxSection::ComputeTransportCrossSectionPerAtom(), cosTetMaxNuc, currentMaterial, currentMaterialIndex, fixedCut, G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), nelments, prob, G4WentzelOKandVIxSection::SetupTarget(), wokvi, xsecn, and xtsec.
Referenced by ComputeGeomPathLength(), and ComputeTrueStepLength().
G4double G4WentzelVIModel::ComputeTruePathLengthLimit (const G4Track & track, G4double & currentMinimalStep) override virtual
Implements G4VMscModel.
Reimplemented in G4LowEWentzelVIModel.
Definition at line 267 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 267 of file G4WentzelVIModel.cc
References G4VMscModel::ComputeGeomLimit(), G4VMscModel::ComputeSafety(), G4VMscModel::ConvertTrueToGeom(), cosTetMaxNuc, cosThetaMax, currentCouple, currentMaterial, currentRange, DefineMaterial(), effKinEnergy, G4VMscModel::facgeom, G4VMscModel::facrange, G4VMscModel::facsafety, fGeomBoundary, fUseDistanceToBoundary, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), G4Material::GetRadlen(), G4VMscModel::GetRange(), G4StepPoint::GetSafety(), G4Track::GetStep(), G4StepPoint::GetStepStatus(), G4VMscModel::GetTransportMeanFreePath(), invssFactor, lambdaeff, max, min, particle, preKinEnergy, G4WentzelOKandVIxSection::SetupKinematic(), singleScatteringMode, G4InuclParticleNames::sp, G4VMscModel::steppingAlgorithm, tlimitminfix, and wokvi.
G4double G4WentzelVIModel::ComputeTrueStepLength (G4double geomStepLength) override virtual
Implements G4VMscModel.
Definition at line 409 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 409 of file G4WentzelVIModel.cc
References ComputeTransportXSectionPerVolume(), cosTetMaxNuc, cosThetaMin, Acts::VectorHelpers::cross(), currentCouple, currentMaterial, currentRange, DBL_MAX, e1, effKinEnergy, G4Log(), G4VMscModel::GetEnergy(), G4VMscModel::GetTransportMeanFreePath(), lambdaeff, min, minNCollisions, numlimit, particle, preKinEnergy, G4WentzelOKandVIxSection::SetupKinematic(), singleScatteringMode, ssFactor, tPathLength, wokvi, xtsec, and zPathLength.
void G4WentzelVIModel::DefineMaterial (const G4MaterialCutsCouple * cup)
Definition at line 211 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 211 of file G4WentzelVIModel.cc
References currentCouple, currentMaterial, currentMaterialIndex, G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), and G4VEmModel::SetCurrentCouple().
Referenced by ComputeCrossSectionPerAtom(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), Initialise(), and SecondMoment().
G4double G4WentzelVIModel::GetFixedCut () const inline
Definition at line 217 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 217 of file G4WentzelVIModel.hh
References fixedCut.
G4PhysicsTable * G4WentzelVIModel::GetSecondMomentTable () inline
Definition at line 255 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 255 of file G4WentzelVIModel.hh
References fSecondMoments.
Referenced by InitialiseLocal().
G4WentzelOKandVIxSection * G4WentzelVIModel::GetWVICrossSection () inline
Definition at line 234 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 234 of file G4WentzelVIModel.hh
References wokvi.
Referenced by G4WentzelVIRelModel::DefineMaterial().
void G4WentzelVIModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) override virtual
Implements G4VEmModel.
Reimplemented in G4WentzelVIRelModel.
Definition at line 122 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 122 of file G4WentzelVIModel.cc
References ComputeSecondMoment(), cosThetaMax, currentCuts, currentRange, DefineMaterial(), e, emax, CEMC_TOWER::emin, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), fParticleChange, fSecondMoments, G4lrint(), G4VEmModel::GetCrossSectionTable(), G4PhysicsTable::GetFlag(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4VMscModel::GetParticleChangeForMSC(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4VEmModel::HighEnergyActivationLimit(), G4VEmModel::HighEnergyLimit(), G4WentzelOKandVIxSection::Initialise(), G4VMscModel::InitialiseParameters(), G4EmParameters::Instance(), isCombined, G4VEmModel::IsMaster(), G4VEmModel::LowEnergyActivationLimit(), G4VEmModel::LowEnergyLimit(), max, min, n, G4EmParameters::NumberOfBinsPerDecade(), CLHEP::pi, G4VEmModel::PolarAngleLimit(), G4PhysicsTableHelper::PreparePhysicsTable(), G4PhysicsVector::PutValue(), SetupParticle(), useSecondMoment, and wokvi.
Referenced by G4TablesForExtrapolator::ComputeTrasportXS(), and G4WentzelVIRelModel::Initialise().
void G4WentzelVIModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) override virtual
Reimplemented from G4VEmModel.
Definition at line 202 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 202 of file G4WentzelVIModel.cc
References fSecondMoments, and GetSecondMomentTable().
G4WentzelVIModel& G4WentzelVIModel::operator= (const G4WentzelVIModel & right) private delete
G4ThreeVector & G4WentzelVIModel::SampleScattering (const G4ThreeVector & oldDirection, G4double safety) override virtual
Implements G4VMscModel.
Definition at line 506 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 506 of file G4WentzelVIModel.cc
References cosThetaMin, currentCouple, currentMaterial, currentMaterialIndex, d, DBL_MAX, dir, dx, dy, effKinEnergy, G4VMscModel::fDisplacement, fixedCut, CLHEP::HepRandomEngine::flat(), fParticleChange, G4Exp(), G4Log(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), invsqrt12, lambdaeff, G4VMscModel::latDisplasment, lowEnergyLimit, particle, phi, preKinEnergy, prob, G4ParticleChangeForMSC::ProposeMomentumDirection(), r, CLHEP::Hep3Vector::rotateUz(), G4WentzelOKandVIxSection::SampleSingleScattering(), SecondMoment(), CLHEP::Hep3Vector::set(), G4WentzelOKandVIxSection::SetupTarget(), G4INCL::DeJongSpin::shoot(), singleScatteringMode, Acts::Test::step(), tPathLength, twopi, useSecondMoment, wokvi, x1, x2, xsecn, xtsec, z, G4InuclParticleNames::z0, z1, z2, and zPathLength.
G4double G4WentzelVIModel::SecondMoment (const G4ParticleDefinition * part, const G4MaterialCutsCouple * couple, G4double kineticEnergy) inline
Definition at line 263 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 263 of file G4WentzelVIModel.hh
References ComputeSecondMoment(), currentMaterialIndex, DefineMaterial(), fSecondMoments, idx2, useSecondMoment, and x.
Referenced by SampleScattering().
void G4WentzelVIModel::SetFixedCut (G4double val) inline
Definition at line 210 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 210 of file G4WentzelVIModel.hh
References fixedCut.
void G4WentzelVIModel::SetSingleScatteringFactor (G4double val)
Definition at line 801 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 801 of file G4WentzelVIModel.cc
References invssFactor, and ssFactor.
Referenced by G4LowEWentzelVIModel::G4LowEWentzelVIModel(), and G4WentzelVIModel().
void G4WentzelVIModel::SetupParticle (const G4ParticleDefinition * p) inline protected
Definition at line 199 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 199 of file G4WentzelVIModel.hh
References particle, G4WentzelOKandVIxSection::SetupParticle(), and wokvi.
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), ComputeSecondMoment(), Initialise(), and StartTracking().
void G4WentzelVIModel::SetUseSecondMoment (G4bool val) inline
Definition at line 241 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 241 of file G4WentzelVIModel.hh
References useSecondMoment.
void G4WentzelVIModel::SetWVICrossSection (G4WentzelOKandVIxSection * ptr) inline
Definition at line 224 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 224 of file G4WentzelVIModel.hh
References wokvi.
Referenced by G4WentzelVIRelModel::G4WentzelVIRelModel().
void G4WentzelVIModel::StartTracking (G4Track * track) override virtual
Reimplemented from G4VEmModel.
Definition at line 255 of file G4WentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 255 of file G4WentzelVIModel.cc
References G4Track::GetParticleDefinition(), and SetupParticle().
G4bool G4WentzelVIModel::UseSecondMoment () const inline
Definition at line 248 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 248 of file G4WentzelVIModel.hh
References useSecondMoment.
Member Data Documentation
G4double G4WentzelVIModel::cosTetMaxNuc protected
Definition at line 154 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), ComputeGeomPathLength(), ComputeSecondMoment(), ComputeTransportXSectionPerVolume(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), and G4WentzelVIModel().
G4double G4WentzelVIModel::cosThetaMax protected
Definition at line 173 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4WentzelVIModel.hh
Referenced by ComputeTruePathLengthLimit(), and Initialise().
G4double G4WentzelVIModel::cosThetaMin protected
Definition at line 172 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), and SampleScattering().
const G4MaterialCutsCouple* G4WentzelVIModel::currentCouple protected
Definition at line 158 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIRelModel::DefineMaterial(), DefineMaterial(), and SampleScattering().
const G4DataVector* G4WentzelVIModel::currentCuts protected
Definition at line 163 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIModel(), and Initialise().
const G4Material* G4WentzelVIModel::currentMaterial protected
Definition at line 159 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), ComputeGeomPathLength(), ComputeSecondMoment(), ComputeTransportXSectionPerVolume(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIRelModel::DefineMaterial(), DefineMaterial(), G4WentzelVIModel(), and SampleScattering().
G4int G4WentzelVIModel::currentMaterialIndex protected
Definition at line 157 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4WentzelVIModel.hh
Referenced by ComputeSecondMoment(), ComputeTransportXSectionPerVolume(), G4WentzelVIRelModel::DefineMaterial(), DefineMaterial(), G4WentzelVIModel(), SampleScattering(), and SecondMoment().
G4double G4WentzelVIModel::currentRange protected
Definition at line 153 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIModel(), and Initialise().
G4double G4WentzelVIModel::effKinEnergy protected
Definition at line 169 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIModel(), and SampleScattering().
G4double G4WentzelVIModel::fixedCut protected
Definition at line 166 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4WentzelVIModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeSecondMoment(), ComputeTransportXSectionPerVolume(), G4WentzelVIModel(), GetFixedCut(), SampleScattering(), and SetFixedCut().
G4ParticleChangeForMSC* G4WentzelVIModel::fParticleChange protected
Definition at line 162 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIModel(), Initialise(), and SampleScattering().
G4PhysicsTable* G4WentzelVIModel::fSecondMoments protected
Definition at line 175 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 175 of file G4WentzelVIModel.hh
Referenced by GetSecondMomentTable(), Initialise(), InitialiseLocal(), SecondMoment(), and ~G4WentzelVIModel().
size_t G4WentzelVIModel::idx2 protected
Definition at line 176 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4WentzelVIModel.hh
Referenced by SecondMoment().
G4double G4WentzelVIModel::invsqrt12 protected
Definition at line 165 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIModel(), and SampleScattering().
G4double G4WentzelVIModel::invssFactor protected
Definition at line 146 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4WentzelVIModel.hh
Referenced by ComputeTruePathLengthLimit(), and SetSingleScatteringFactor().
G4bool G4WentzelVIModel::isCombined protected
Definition at line 192 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 192 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIModel(), and Initialise().
G4double G4WentzelVIModel::lambdaeff protected
Definition at line 152 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIModel(), and SampleScattering().
G4double G4WentzelVIModel::lowEnergyLimit protected
Definition at line 188 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), G4WentzelVIModel(), and SampleScattering().
G4int G4WentzelVIModel::minNCollisions protected
Definition at line 179 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), and G4WentzelVIModel().
G4int G4WentzelVIModel::nelments protected
Definition at line 180 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4WentzelVIModel.hh
Referenced by ComputeTransportXSectionPerVolume(), and G4WentzelVIModel().
G4double G4WentzelVIModel::numlimit protected
Definition at line 185 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), and ComputeTrueStepLength().
const G4ParticleDefinition* G4WentzelVIModel::particle protected
Definition at line 161 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIModel(), SampleScattering(), and SetupParticle().
G4double G4WentzelVIModel::preKinEnergy protected
Definition at line 149 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 149 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIModel(), and SampleScattering().
std::vector<G4double> G4WentzelVIModel::prob protected
Definition at line 182 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4WentzelVIModel.hh
Referenced by ComputeTransportXSectionPerVolume(), G4WentzelVIModel(), and SampleScattering().
G4bool G4WentzelVIModel::singleScatteringMode protected
Definition at line 191 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 191 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), and SampleScattering().
G4double G4WentzelVIModel::ssFactor protected
Definition at line 145 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4WentzelVIModel.hh
Referenced by ComputeTrueStepLength(), and SetSingleScatteringFactor().
G4double G4WentzelVIModel::tlimitminfix protected
Definition at line 144 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4WentzelVIModel.hh
Referenced by G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), and G4WentzelVIModel().
G4double G4WentzelVIModel::tPathLength protected
Definition at line 150 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), G4WentzelVIModel(), and SampleScattering().
G4bool G4WentzelVIModel::useSecondMoment protected
Definition at line 193 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 193 of file G4WentzelVIModel.hh
Referenced by Initialise(), SampleScattering(), SecondMoment(), SetUseSecondMoment(), and UseSecondMoment().
G4WentzelOKandVIxSection* G4WentzelVIModel::wokvi protected
Definition at line 142 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 142 of file G4WentzelVIModel.hh
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), ComputeCrossSectionPerAtom(), ComputeGeomPathLength(), ComputeSecondMoment(), ComputeTransportXSectionPerVolume(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4WentzelVIModel(), GetWVICrossSection(), Initialise(), SampleScattering(), SetupParticle(), SetWVICrossSection(), and ~G4WentzelVIModel().
std::vector<G4double> G4WentzelVIModel::xsecn protected
Definition at line 181 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4WentzelVIModel.hh
Referenced by ComputeTransportXSectionPerVolume(), G4WentzelVIModel(), and SampleScattering().
G4double G4WentzelVIModel::xtsec protected
Definition at line 184 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), ComputeTransportXSectionPerVolume(), ComputeTrueStepLength(), G4WentzelVIModel(), and SampleScattering().
G4double G4WentzelVIModel::zPathLength protected
Definition at line 151 of file G4WentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4WentzelVIModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), G4WentzelVIModel(), and SampleScattering().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WentzelVIModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4WentzelVIModel.cc