ECCE @ EIC Software: G4VIsotopeTable Class Reference
G4VIsotopeTable Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4VIsotopeTable.hh>
Public Member Functions
G4VIsotopeTable ()
G4VIsotopeTable (const G4String &)
G4VIsotopeTable (const G4VIsotopeTable &)
G4VIsotopeTable & operator= (const G4VIsotopeTable &)
virtual ~G4VIsotopeTable ()
virtual G4IsotopeProperty * GetIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float)=0
virtual G4IsotopeProperty * GetIsotopeByIsoLvl (G4int Z, G4int A, G4int level=0)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void DumpTable (G4int Zmin=1, G4int Zmax=118)
const G4String & GetName () const
Private Attributes
G4String fName
G4int verboseLevel
Detailed Description
Definition at line 44 of file G4VIsotopeTable.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VIsotopeTable.hh
Constructor & Destructor Documentation
G4VIsotopeTable::G4VIsotopeTable ()
Definition at line 44 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VIsotopeTable.cc
G4VIsotopeTable::G4VIsotopeTable (const G4String & name) explicit
Definition at line 49 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VIsotopeTable.cc
G4VIsotopeTable::G4VIsotopeTable (const G4VIsotopeTable & right)
Definition at line 54 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VIsotopeTable.cc
G4VIsotopeTable::~G4VIsotopeTable () virtual
Definition at line 68 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VIsotopeTable.cc
Member Function Documentation
void G4VIsotopeTable::DumpTable (G4int Zmin = 1, G4int Zmax = 118)
Definition at line 80 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 80 of file G4VIsotopeTable.cc
References A(), G4IsotopeProperty::DumpInfo(), GetIsotope(), Z, and Zmax.
virtual G4IsotopeProperty* G4VIsotopeTable::GetIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) pure virtual
Implemented in G4NuclideTable, and G4IsotopeMagneticMomentTable.
Referenced by DumpTable(), G4IonTable::FindIsotope(), and GetIsotopeByIsoLvl().
G4IsotopeProperty * G4VIsotopeTable::GetIsotopeByIsoLvl (G4int Z, G4int A, G4int level = 0) virtual
Reimplemented in G4NuclideTable, and G4IsotopeMagneticMomentTable.
Definition at line 72 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VIsotopeTable.cc
References GetIsotope().
const G4String & G4VIsotopeTable::GetName (void) const inline
Definition at line 101 of file G4VIsotopeTable.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VIsotopeTable.hh
References fName.
Referenced by G4IonTable::RegisterIsotopeTable().
G4int G4VIsotopeTable::GetVerboseLevel () const inline
Definition at line 107 of file G4VIsotopeTable.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VIsotopeTable.hh
References verboseLevel.
G4VIsotopeTable & G4VIsotopeTable::operator= (const G4VIsotopeTable & right)
Definition at line 59 of file G4VIsotopeTable.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VIsotopeTable.cc
References fName, and verboseLevel.
void G4VIsotopeTable::SetVerboseLevel (G4int level) inline
Definition at line 113 of file G4VIsotopeTable.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VIsotopeTable.hh
References verboseLevel.
Member Data Documentation
G4String G4VIsotopeTable::fName private
Definition at line 96 of file G4VIsotopeTable.hh.
View newest version in sPHENIX GitHub at line 96 of file G4VIsotopeTable.hh
Referenced by GetName(), and operator=().
G4int G4VIsotopeTable::verboseLevel private
Definition at line 97 of file G4VIsotopeTable.hh.
View newest version in sPHENIX GitHub at line 97 of file G4VIsotopeTable.hh
Referenced by GetVerboseLevel(), operator=(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4VIsotopeTable.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4VIsotopeTable.cc