ECCE @ EIC Software: G4XnpElasticLowE Class Reference
G4XnpElasticLowE Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XnpElasticLowE.hh>
Public Member Functions
G4XnpElasticLowE ()
virtual ~G4XnpElasticLowE ()
G4bool operator== (const G4XnpElasticLowE &right) const
G4bool operator!= (const G4XnpElasticLowE &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual void Print () const
virtual G4String Name () const
virtual G4double HighLimit () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double LowLimit () const
Private Member Functions
G4XnpElasticLowE (const G4XnpElasticLowE &right)
const G4XnpElasticLowE & operator= (const G4XnpElasticLowE &right)
Private Attributes
G4PhysicsVector * _sigma
G4double _eMin
G4double _eMax
Static Private Attributes
static const G4double _lowLimit = 0.
static const G4double _highLimit = 3.*GeV
static const G4double _sigmaTable [101]
static const G4int _tableSize = 101
static const G4double _eMinTable = 1.8964808
static const G4double _eStepLog = 0.01
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 51 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 51 of file G4XnpElasticLowE.hh
Constructor & Destructor Documentation
G4XnpElasticLowE::G4XnpElasticLowE ()
Definition at line 88 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 88 of file G4XnpElasticLowE.cc
References _eMax, _eMin, _eMinTable, _eStepLog, _highLimit, _lowLimit, _sigma, _sigmaTable, _tableSize, G4Exp(), G4Log(), GeV, millibarn, and G4PhysicsVector::PutValue().
G4XnpElasticLowE::~G4XnpElasticLowE () virtual
Definition at line 114 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 114 of file G4XnpElasticLowE.cc
References _sigma.
G4XnpElasticLowE::G4XnpElasticLowE (const G4XnpElasticLowE & right) private
Member Function Documentation
G4double G4XnpElasticLowE::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 133 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 133 of file G4XnpElasticLowE.cc
References _eMax, _eMin, _sigma, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4PhysicsVector::GetValue(), G4InuclParticleNames::neutron, G4Neutron::NeutronDefinition(), G4InuclParticleNames::proton, and G4Proton::ProtonDefinition().
virtual const G4CrossSectionVector* G4XnpElasticLowE::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 65 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 65 of file G4XnpElasticLowE.hh
virtual G4double G4XnpElasticLowE::HighLimit () const inline virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 73 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 73 of file G4XnpElasticLowE.hh
References _highLimit.
G4bool G4XnpElasticLowE::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 184 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 184 of file G4XnpElasticLowE.cc
References _highLimit, _lowLimit, and G4VCrossSectionSource::InLimits().
G4String G4XnpElasticLowE::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 177 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 177 of file G4XnpElasticLowE.cc
Referenced by Print().
G4bool G4XnpElasticLowE::operator!= (const G4XnpElasticLowE & right) const
Definition at line 127 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 127 of file G4XnpElasticLowE.cc
const G4XnpElasticLowE& G4XnpElasticLowE::operator= (const G4XnpElasticLowE & right) private
G4bool G4XnpElasticLowE::operator== (const G4XnpElasticLowE & right) const
Definition at line 121 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 121 of file G4XnpElasticLowE.cc
void G4XnpElasticLowE::Print (void) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 159 of file G4XnpElasticLowE.cc.
View newest version in sPHENIX GitHub at line 159 of file G4XnpElasticLowE.cc
References _sigma, _tableSize, e, G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetValue(), GeV, millibarn, Name(), and G4VCrossSectionSource::Print().
Member Data Documentation
G4double G4XnpElasticLowE::_eMax private
Definition at line 93 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 93 of file G4XnpElasticLowE.hh
Referenced by CrossSection(), and G4XnpElasticLowE().
G4double G4XnpElasticLowE::_eMin private
Definition at line 92 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 92 of file G4XnpElasticLowE.hh
Referenced by CrossSection(), and G4XnpElasticLowE().
const G4double G4XnpElasticLowE::_eMinTable = 1.8964808 static private
Definition at line 88 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 88 of file G4XnpElasticLowE.hh
Referenced by G4XnpElasticLowE().
const G4double G4XnpElasticLowE::_eStepLog = 0.01 static private
Definition at line 89 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 89 of file G4XnpElasticLowE.hh
Referenced by G4XnpElasticLowE().
const G4double G4XnpElasticLowE::_highLimit = 3.*GeV static private
Definition at line 85 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 85 of file G4XnpElasticLowE.hh
Referenced by G4XnpElasticLowE(), HighLimit(), and IsValid().
const G4double G4XnpElasticLowE::_lowLimit = 0. static private
Definition at line 84 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 84 of file G4XnpElasticLowE.hh
Referenced by G4XnpElasticLowE(), and IsValid().
G4PhysicsVector* G4XnpElasticLowE::_sigma private
Definition at line 91 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 91 of file G4XnpElasticLowE.hh
Referenced by CrossSection(), G4XnpElasticLowE(), Print(), and ~G4XnpElasticLowE().
const G4double G4XnpElasticLowE::_sigmaTable static private
Initial value:
=
{
  1500.0,
  248.20, 93.38, 55.26, 44.50, 41.33, 38.48, 37.20, 35.98,
  35.02, 34.47, 32.48, 30.76, 29.46, 28.53, 27.84, 27.20,
  26.53, 25.95, 25.59, 25.46, 25.00, 24.49, 24.08, 23.86,
  23.17, 22.70, 21.88, 21.48, 20.22, 19.75, 18.97, 18.39,
  17.98, 17.63, 17.21, 16.72, 16.68, 16.58, 16.42, 16.22,
  15.98, 15.71, 15.42, 15.14, 14.87, 14.65, 14.44, 14.26,
  14.10, 13.95, 13.80, 13.64, 13.47, 13.29, 13.09, 12.89,
  12.68, 12.47, 12.27, 12.06, 11.84, 11.76, 11.69, 11.60,
  11.50, 11.41, 11.29, 11.17, 11.06, 10.93, 10.81, 10.68,
  10.56, 10.44, 10.33, 10.21, 10.12, 10.03,  9.96,  9.89,
  9.83,  9.80,  9.77,  9.75,  9.74,  9.74,  9.74,  9.76,
  9.73,  9.70,  9.68,  9.65,  9.63,  9.60,  9.57,  9.55,
  9.52,  9.49,  9.46,  9.43
}
Definition at line 86 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 86 of file G4XnpElasticLowE.hh
Referenced by G4XnpElasticLowE().
const G4int G4XnpElasticLowE::_tableSize = 101 static private
Definition at line 87 of file G4XnpElasticLowE.hh.
View newest version in sPHENIX GitHub at line 87 of file G4XnpElasticLowE.hh
Referenced by G4XnpElasticLowE(), and Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XnpElasticLowE.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XnpElasticLowE.cc