ECCE @ EIC Software: G4PolarizedComptonModel Class Reference
G4PolarizedComptonModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedComptonModel.hh>
Public Member Functions
G4PolarizedComptonModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="Polarized-Compton")
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A, G4double cut, G4double emax) override
G4double ComputeAsymmetryPerAtom (G4double gammaEnergy, G4double Z)
virtual ~G4PolarizedComptonModel ()
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
void SetTargetPolarization (const G4ThreeVector &pTarget)
void SetBeamPolarization (const G4ThreeVector &pBeam)
const G4ThreeVector & GetTargetPolarization () const
const G4ThreeVector & GetBeamPolarization () const
const G4ThreeVector & GetFinalGammaPolarization () const
const G4ThreeVector & GetFinalElectronPolarization () const
Public Member Functions inherited from G4KleinNishinaCompton
G4KleinNishinaCompton (const G4ParticleDefinition *p=nullptr, const G4String &nam="Klein-Nishina")
virtual ~G4KleinNishinaCompton ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void PrintWarning (const G4DynamicParticle *, G4int, G4double grej, G4double onecos, G4double phi, const G4String) const
G4PolarizedComptonModel & operator= (const G4PolarizedComptonModel &right)=delete
G4PolarizedComptonModel (const G4PolarizedComptonModel &)=delete
Private Attributes
G4PolarizedComptonCrossSection * crossSectionCalculator
G4StokesVector theBeamPolarization
G4StokesVector theTargetPolarization
G4StokesVector finalGammaPolarization
G4StokesVector finalElectronPolarization
G4int verboseLevel
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4KleinNishinaCompton
G4ParticleDefinition * theGamma
G4ParticleDefinition * theElectron
G4ParticleChangeForGamma * fParticleChange
G4double lowestSecondaryEnergy
Detailed Description
Definition at line 60 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4PolarizedComptonModel.hh
Constructor & Destructor Documentation
G4PolarizedComptonModel::G4PolarizedComptonModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "Polarized-Compton") explicit
Definition at line 71 of file G4PolarizedComptonModel.cc.
View newest version in sPHENIX GitHub at line 71 of file G4PolarizedComptonModel.cc
References crossSectionCalculator.
G4PolarizedComptonModel::~G4PolarizedComptonModel () virtual
Definition at line 81 of file G4PolarizedComptonModel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4PolarizedComptonModel.cc
References crossSectionCalculator.
G4PolarizedComptonModel::G4PolarizedComptonModel (const G4PolarizedComptonModel &) private delete
Member Function Documentation
G4double G4PolarizedComptonModel::ComputeAsymmetryPerAtom (G4double gammaEnergy, G4double Z)
Definition at line 87 of file G4PolarizedComptonModel.cc.
View newest version in sPHENIX GitHub at line 87 of file G4PolarizedComptonModel.cc
References source.hepunit::electron_mass_c2, G4cout, G4endl, G4Log(), G4InuclParticleNames::k0, k1, and sqr().
Referenced by ComputeCrossSectionPerAtom().
G4double G4PolarizedComptonModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * pd, G4double kinEnergy, G4double Z, G4double A, G4double cut, G4double emax) override virtual
Reimplemented from G4KleinNishinaCompton.
Definition at line 106 of file G4PolarizedComptonModel.cc.
View newest version in sPHENIX GitHub at line 106 of file G4PolarizedComptonModel.cc
References ComputeAsymmetryPerAtom(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4StokesVector::p3(), theBeamPolarization, theTargetPolarization, and CLHEP::Hep3Vector::z().
const G4ThreeVector & G4PolarizedComptonModel::GetBeamPolarization () const inline
Definition at line 125 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PolarizedComptonModel.hh
References theBeamPolarization.
const G4ThreeVector & G4PolarizedComptonModel::GetFinalElectronPolarization () const inline
Definition at line 133 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4PolarizedComptonModel.hh
References finalElectronPolarization.
const G4ThreeVector & G4PolarizedComptonModel::GetFinalGammaPolarization () const inline
Definition at line 129 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4PolarizedComptonModel.hh
References finalGammaPolarization.
const G4ThreeVector & G4PolarizedComptonModel::GetTargetPolarization () const inline
Definition at line 121 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PolarizedComptonModel.hh
References theTargetPolarization.
G4PolarizedComptonModel& G4PolarizedComptonModel::operator= (const G4PolarizedComptonModel & right) private delete
void G4PolarizedComptonModel::PrintWarning (const G4DynamicParticle * dp, G4int nloop, G4double grej, G4double onecos, G4double phi, const G4String sss) const private
Definition at line 419 of file G4PolarizedComptonModel.cc.
View newest version in sPHENIX GitHub at line 419 of file G4PolarizedComptonModel.cc
References G4Exception(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetPolarization(), JustWarning, and MeV.
Referenced by SampleSecondaries().
void G4PolarizedComptonModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * , const G4DynamicParticle * aDynamicGamma, G4double tmin, G4double maxEnergy) override virtual
Reimplemented from G4KleinNishinaCompton.
Definition at line 127 of file G4PolarizedComptonModel.cc.
View newest version in sPHENIX GitHub at line 127 of file G4PolarizedComptonModel.cc
References kdfinder::abs(), crossSectionCalculator, e, edep, source.hepunit::electron_mass_c2, epsilon(), finalElectronPolarization, finalGammaPolarization, CLHEP::HepRandomEngine::flatArray(), G4KleinNishinaCompton::fParticleChange, fStopAndKill, G4cout, G4endl, G4Exp(), G4Log(), G4ParticleChangeForGamma::GetCurrentTrack(), G4PolarizationHelper::GetFrame(), G4PolarizationManager::GetInstance(), G4DynamicParticle::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4DynamicParticle::GetMomentumDirection(), G4LogicalVolume::GetName(), G4PolarizedComptonCrossSection::GetPol2(), G4PolarizedComptonCrossSection::GetPol3(), G4DynamicParticle::GetPolarization(), G4Track::GetVolume(), G4PolarizationManager::GetVolumePolarization(), G4PolarizedComptonCrossSection::Initialize(), G4StokesVector::InvRotateAz(), G4PolarizationManager::IsPolarized(), G4VEmModel::LowEnergyLimit(), G4KleinNishinaCompton::lowestSecondaryEnergy, CLHEP::Hep3Vector::mag(), nlooplim, G4StokesVector::p1(), G4StokesVector::p2(), G4StokesVector::p3(), PrintWarning(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4ParticleChangeForGamma::ProposePolarization(), G4VParticleChange::ProposeTrackStatus(), G4StokesVector::RotateAz(), CLHEP::Hep3Vector::rotateUz(), G4StokesVector::SetPhoton(), G4DynamicParticle::SetPolarization(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), sqr(), theBeamPolarization, G4KleinNishinaCompton::theElectron, theTargetPolarization, twopi, CLHEP::Hep3Vector::unit(), and verboseLevel.
void G4PolarizedComptonModel::SetBeamPolarization (const G4ThreeVector & pBeam) inline
Definition at line 117 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PolarizedComptonModel.hh
References theBeamPolarization.
Referenced by G4PolarizedCompton::ComputeAsymmetry().
void G4PolarizedComptonModel::SetTargetPolarization (const G4ThreeVector & pTarget) inline
Definition at line 113 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PolarizedComptonModel.hh
References theTargetPolarization.
Referenced by G4PolarizedCompton::ComputeAsymmetry().
Member Data Documentation
G4PolarizedComptonCrossSection* G4PolarizedComptonModel::crossSectionCalculator private
Definition at line 100 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PolarizedComptonModel.hh
Referenced by G4PolarizedComptonModel(), SampleSecondaries(), and ~G4PolarizedComptonModel().
G4StokesVector G4PolarizedComptonModel::finalElectronPolarization private
Definition at line 106 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4PolarizedComptonModel.hh
Referenced by GetFinalElectronPolarization(), and SampleSecondaries().
G4StokesVector G4PolarizedComptonModel::finalGammaPolarization private
Definition at line 105 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4PolarizedComptonModel.hh
Referenced by GetFinalGammaPolarization(), and SampleSecondaries().
G4StokesVector G4PolarizedComptonModel::theBeamPolarization private
Definition at line 102 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PolarizedComptonModel.hh
Referenced by ComputeCrossSectionPerAtom(), GetBeamPolarization(), SampleSecondaries(), and SetBeamPolarization().
G4StokesVector G4PolarizedComptonModel::theTargetPolarization private
Definition at line 103 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PolarizedComptonModel.hh
Referenced by ComputeCrossSectionPerAtom(), GetTargetPolarization(), SampleSecondaries(), and SetTargetPolarization().
G4int G4PolarizedComptonModel::verboseLevel private
Definition at line 108 of file G4PolarizedComptonModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PolarizedComptonModel.hh
Referenced by SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedComptonModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedComptonModel.cc