ECCE @ EIC Software: G4MuonMinusBoundDecay Class Reference
G4MuonMinusBoundDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuonMinusBoundDecay.hh>
Public Member Functions
G4MuonMinusBoundDecay ()
~G4MuonMinusBoundDecay ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Static Public Member Functions
static G4double GetMuonCaptureRate (G4int Z, G4int A)
static G4double GetMuonDecayRate (G4int Z, G4int A, G4double muMass, G4double nuclMass)
static G4double GetMuonDecayRate (G4int Z)
static G4double GetMuonZeff (G4int Z)
Private Member Functions
void AddNewParticle (G4DynamicParticle *dp, G4double time)
G4MuonMinusBoundDecay & operator= (const G4MuonMinusBoundDecay &right)
G4MuonMinusBoundDecay (const G4MuonMinusBoundDecay &)
Private Attributes
G4HadFinalState result
G4double fMuMass
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 71 of file G4MuonMinusBoundDecay.hh.
View newest version in sPHENIX GitHub at line 71 of file G4MuonMinusBoundDecay.hh
Constructor & Destructor Documentation
G4MuonMinusBoundDecay::G4MuonMinusBoundDecay ()
Definition at line 66 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 66 of file G4MuonMinusBoundDecay.cc
References fMuMass, G4ParticleDefinition::GetPDGMass(), and G4MuonMinus::MuonMinus().
G4MuonMinusBoundDecay::~G4MuonMinusBoundDecay ()
Definition at line 74 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 74 of file G4MuonMinusBoundDecay.cc
G4MuonMinusBoundDecay::G4MuonMinusBoundDecay (const G4MuonMinusBoundDecay &) private
Member Function Documentation
void G4MuonMinusBoundDecay::AddNewParticle (G4DynamicParticle * dp, G4double time) inline private
Definition at line 110 of file G4MuonMinusBoundDecay.hh.
View newest version in sPHENIX GitHub at line 110 of file G4MuonMinusBoundDecay.hh
References G4HadFinalState::AddSecondary(), result, and G4HadSecondary::SetTime().
Referenced by ApplyYourself().
G4HadFinalState * G4MuonMinusBoundDecay::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 80 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 80 of file G4MuonMinusBoundDecay.cc
References A(), AddNewParticle(), G4AntiNeutrinoE::AntiNeutrinoE(), G4Nucleus::AtomicMass(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4HadFinalState::Clear(), dir, CLHEP::HepLorentzVector::e(), G4Electron::Electron(), source.hepunit::electron_mass_c2, fMuMass, G4Log(), G4RandomDirection(), G4UniformRand, G4Nucleus::GetA_asInt(), G4HadProjectile::GetBoundEnergy(), G4HadProjectile::GetGlobalTime(), GetMuonCaptureRate(), GetMuonDecayRate(), G4Nucleus::GetZ_asInt(), isAlive, G4InuclParticleNames::lambda, CLHEP::HepLorentzVector::mag2(), G4NeutrinoMu::NeutrinoMu(), result, G4HadProjectile::SetGlobalTime(), G4HadFinalState::SetStatusChange(), stopAndKill, Acts::VectorHelpers::time(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), x, xmax, xmin, and Z.
G4double G4MuonMinusBoundDecay::GetMuonCaptureRate (G4int Z, G4int A) static
Definition at line 181 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 181 of file G4MuonMinusBoundDecay.cc
References A(), kdfinder::abs(), GetMuonZeff(), G4InuclParticleNames::lambda, microsecond, r1, r2, t1, and Z.
Referenced by ApplyYourself().
G4double G4MuonMinusBoundDecay::GetMuonDecayRate (G4int Z, G4int A, G4double muMass, G4double nuclMass) static
Definition at line 371 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 371 of file G4MuonMinusBoundDecay.cc
References A(), source.hepunit::fine_structure_const, G4InuclParticleNames::lambda, microsecond, x, and Z.
Referenced by ApplyYourself(), and GetMuonDecayRate().
G4double G4MuonMinusBoundDecay::GetMuonDecayRate (G4int Z) static
Definition at line 364 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 364 of file G4MuonMinusBoundDecay.cc
References A(), G4lrint(), GetMuonDecayRate(), G4NucleiProperties::GetNuclearMass(), G4NistManager::Instance(), and G4MuonMinus::MuonMinus().
G4double G4MuonMinusBoundDecay::GetMuonZeff (G4int Z) static
Definition at line 337 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 337 of file G4MuonMinusBoundDecay.cc
References max, maxZ, min, and Z.
Referenced by GetMuonCaptureRate().
void G4MuonMinusBoundDecay::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 436 of file G4MuonMinusBoundDecay.cc.
View newest version in sPHENIX GitHub at line 436 of file G4MuonMinusBoundDecay.cc
G4MuonMinusBoundDecay& G4MuonMinusBoundDecay::operator= (const G4MuonMinusBoundDecay & right) private
Member Data Documentation
G4double G4MuonMinusBoundDecay::fMuMass private
Definition at line 103 of file G4MuonMinusBoundDecay.hh.
View newest version in sPHENIX GitHub at line 103 of file G4MuonMinusBoundDecay.hh
Referenced by ApplyYourself(), and G4MuonMinusBoundDecay().
G4HadFinalState G4MuonMinusBoundDecay::result private
Definition at line 102 of file G4MuonMinusBoundDecay.hh.
View newest version in sPHENIX GitHub at line 102 of file G4MuonMinusBoundDecay.hh
Referenced by AddNewParticle(), and ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuonMinusBoundDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4MuonMinusBoundDecay.cc