ECCE @ EIC Software: G4ParallelWorldScoringProcess Class Reference
G4ParallelWorldScoringProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4ParallelWorldScoringProcess.hh>
Public Member Functions
G4ParallelWorldScoringProcess (const G4String &processName="ParaWorldScore", G4ProcessType theType=fParameterisation)
virtual ~G4ParallelWorldScoringProcess ()
void SetParallelWorld (G4String parallelWorldName)
void SetParallelWorld (G4VPhysicalVolume *parallelWorld)
G4bool IsAtRestRequired (G4ParticleDefinition *partDef)
void StartTracking (G4Track *)
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
void Verbose (const G4Step &) const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
void CopyStep (const G4Step &step)
Private Attributes
G4Step * fGhostStep
G4StepPoint * fGhostPreStepPoint
G4StepPoint * fGhostPostStepPoint
G4VParticleChange aDummyParticleChange
G4ParticleChange xParticleChange
G4TransportationManager * fTransportationManager
G4PathFinder * fPathFinder
G4String fGhostWorldName
G4VPhysicalVolume * fGhostWorld
G4Navigator * fGhostNavigator
G4int fNavigatorID
G4TouchableHandle fOldGhostTouchable
G4TouchableHandle fNewGhostTouchable
G4FieldTrack fFieldTrack
G4double fGhostSafety
G4bool fOnBoundary
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 67 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ParallelWorldScoringProcess.hh
Constructor & Destructor Documentation
G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess (const G4String & processName = "ParaWorldScore", G4ProcessType theType = fParameterisation)
Definition at line 53 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ParallelWorldScoringProcess.cc
References aDummyParticleChange, fGhostPostStepPoint, fGhostPreStepPoint, fGhostSafety, fGhostStep, fGhostWorld, fOnBoundary, fPathFinder, fTransportationManager, G4cout, G4endl, G4PathFinder::GetInstance(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VProcess::GetProcessName(), G4TransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, and G4VProcess::verboseLevel.
G4ParallelWorldScoringProcess::~G4ParallelWorldScoringProcess () virtual
Definition at line 78 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ParallelWorldScoringProcess.cc
References fGhostStep.
Member Function Documentation
G4VParticleChange * G4ParallelWorldScoringProcess::AlongStepDoIt (const G4Track & track, const G4Step &) virtual
Implements G4VProcess.
Definition at line 393 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 393 of file G4ParallelWorldScoringProcess.cc
References G4VParticleChange::Initialize(), and G4VProcess::pParticleChange.
G4double G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 327 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 327 of file G4ParallelWorldScoringProcess.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PathFinder::ComputeStep(), DBL_MAX, fFieldTrack, fGhostNavigator, fGhostSafety, fNavigatorID, fOnBoundary, fPathFinder, G4ThreadLocal, G4Track::GetCurrentStepNumber(), G4Track::GetVolume(), kDoNot, kSharedOther, kSharedTransport, kUnique, NotCandidateForSelection, and G4FieldTrackUpdator::Update().
G4VParticleChange * G4ParallelWorldScoringProcess::AtRestDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 201 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 201 of file G4ParallelWorldScoringProcess.cc
References CopyStep(), fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetSensitiveDetector(), G4LogicalVolume::GetSensitiveDetector(), G4StepPoint::GetTouchableHandle(), G4VTouchable::GetVolume(), G4VSensitiveDetector::Hit(), G4VParticleChange::Initialize(), G4VProcess::pParticleChange, G4StepPoint::SetSensitiveDetector(), G4StepPoint::SetTouchableHandle(), Verbose(), and G4VProcess::verboseLevel.
G4double G4ParallelWorldScoringProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 188 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 188 of file G4ParallelWorldScoringProcess.cc
References DBL_MAX, and Forced.
void G4ParallelWorldScoringProcess::CopyStep (const G4Step & step) private
Definition at line 403 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 403 of file G4ParallelWorldScoringProcess.cc
References fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fOnBoundary, fPostStepDoItProc, G4Step::GetControlFlag(), G4Step::GetNonIonizingEnergyDeposit(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4Step::SetControlFlag(), G4Step::SetNonIonizingEnergyDeposit(), G4Step::SetStepLength(), G4StepPoint::SetStepStatus(), G4Step::SetTotalEnergyDeposit(), and G4Step::SetTrack().
Referenced by AtRestDoIt(), and PostStepDoIt().
G4bool G4ParallelWorldScoringProcess::IsAtRestRequired (G4ParticleDefinition * partDef)
Definition at line 113 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 113 of file G4ParallelWorldScoringProcess.cc
References G4ParticleDefinition::GetParticleName(), and G4ParticleDefinition::GetPDGEncoding().
G4VParticleChange * G4ParallelWorldScoringProcess::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 258 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 258 of file G4ParallelWorldScoringProcess.cc
References CopyStep(), G4PathFinder::CreateTouchableHandle(), fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fPathFinder, G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetSensitiveDetector(), G4LogicalVolume::GetSensitiveDetector(), G4StepPoint::GetTouchableHandle(), G4VTouchable::GetVolume(), G4VSensitiveDetector::Hit(), G4VParticleChange::Initialize(), G4VProcess::pParticleChange, G4StepPoint::SetSensitiveDetector(), G4StepPoint::SetTouchableHandle(), Verbose(), and G4VProcess::verboseLevel.
G4double G4ParallelWorldScoringProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 243 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 243 of file G4ParallelWorldScoringProcess.cc
References DBL_MAX, and StronglyForced.
void G4ParallelWorldScoringProcess::SetParallelWorld (G4String parallelWorldName)
Definition at line 89 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ParallelWorldScoringProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4TransportationManager::GetNavigator(), and G4TransportationManager::GetParallelWorld().
void G4ParallelWorldScoringProcess::SetParallelWorld (G4VPhysicalVolume * parallelWorld)
Definition at line 101 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ParallelWorldScoringProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4VPhysicalVolume::GetName(), and G4TransportationManager::GetNavigator().
void G4ParallelWorldScoringProcess::StartTracking (G4Track * trk) virtual
Reimplemented from G4VProcess.
Definition at line 144 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 144 of file G4ParallelWorldScoringProcess.cc
References G4TransportationManager::ActivateNavigator(), G4PathFinder::CreateTouchableHandle(), FatalException, fGhostNavigator, fGhostPostStepPoint, fGhostPreStepPoint, fGhostSafety, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fPathFinder, fTransportationManager, fUndefined, G4Exception(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4PathFinder::PrepareNewTrack(), G4StepPoint::SetStepStatus(), and G4StepPoint::SetTouchableHandle().
void G4ParallelWorldScoringProcess::Verbose (const G4Step & step) const
Definition at line 427 of file G4ParallelWorldScoringProcess.cc.
View newest version in sPHENIX GitHub at line 427 of file G4ParallelWorldScoringProcess.cc
References fGhostStep, G4cout, G4endl, G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4VTouchable::GetReplicaNumber(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4Step::GetTrack(), MeV, and mm.
Referenced by AtRestDoIt(), and PostStepDoIt().
Member Data Documentation
G4VParticleChange G4ParallelWorldScoringProcess::aDummyParticleChange private
Definition at line 141 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ParallelWorldScoringProcess.hh
Referenced by G4ParallelWorldScoringProcess().
G4FieldTrack G4ParallelWorldScoringProcess::fFieldTrack private
Definition at line 156 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParallelWorldScoringProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4Navigator* G4ParallelWorldScoringProcess::fGhostNavigator private
Definition at line 152 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ParallelWorldScoringProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), SetParallelWorld(), and StartTracking().
G4StepPoint* G4ParallelWorldScoringProcess::fGhostPostStepPoint private
Definition at line 139 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ParallelWorldScoringProcess.hh
Referenced by AtRestDoIt(), CopyStep(), G4ParallelWorldScoringProcess(), PostStepDoIt(), and StartTracking().
G4StepPoint* G4ParallelWorldScoringProcess::fGhostPreStepPoint private
Definition at line 138 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ParallelWorldScoringProcess.hh
Referenced by AtRestDoIt(), CopyStep(), G4ParallelWorldScoringProcess(), PostStepDoIt(), and StartTracking().
G4double G4ParallelWorldScoringProcess::fGhostSafety private
Definition at line 157 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParallelWorldScoringProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess(), and StartTracking().
G4Step* G4ParallelWorldScoringProcess::fGhostStep private
Definition at line 137 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ParallelWorldScoringProcess.hh
Referenced by AtRestDoIt(), CopyStep(), G4ParallelWorldScoringProcess(), PostStepDoIt(), Verbose(), and ~G4ParallelWorldScoringProcess().
G4VPhysicalVolume* G4ParallelWorldScoringProcess::fGhostWorld private
Definition at line 151 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParallelWorldScoringProcess.hh
Referenced by G4ParallelWorldScoringProcess(), and SetParallelWorld().
G4String G4ParallelWorldScoringProcess::fGhostWorldName private
Definition at line 150 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParallelWorldScoringProcess.hh
Referenced by SetParallelWorld().
G4int G4ParallelWorldScoringProcess::fNavigatorID private
Definition at line 153 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParallelWorldScoringProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4TouchableHandle G4ParallelWorldScoringProcess::fNewGhostTouchable private
Definition at line 155 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ParallelWorldScoringProcess.hh
Referenced by AtRestDoIt(), PostStepDoIt(), and StartTracking().
G4TouchableHandle G4ParallelWorldScoringProcess::fOldGhostTouchable private
Definition at line 154 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParallelWorldScoringProcess.hh
Referenced by AtRestDoIt(), PostStepDoIt(), and StartTracking().
G4bool G4ParallelWorldScoringProcess::fOnBoundary private
Definition at line 158 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParallelWorldScoringProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), AtRestDoIt(), CopyStep(), G4ParallelWorldScoringProcess(), PostStepDoIt(), and StartTracking().
G4PathFinder* G4ParallelWorldScoringProcess::fPathFinder private
Definition at line 145 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ParallelWorldScoringProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess(), PostStepDoIt(), and StartTracking().
G4TransportationManager* G4ParallelWorldScoringProcess::fTransportationManager private
Definition at line 144 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParallelWorldScoringProcess.hh
Referenced by G4ParallelWorldScoringProcess(), SetParallelWorld(), and StartTracking().
G4ParticleChange G4ParallelWorldScoringProcess::xParticleChange private
Definition at line 142 of file G4ParallelWorldScoringProcess.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ParallelWorldScoringProcess.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4ParallelWorldScoringProcess.hh
geant4/tree/geant4-10.6-release/source/processes/scoring/src/G4ParallelWorldScoringProcess.cc