ECCE @ EIC Software: G4VModularPhysicsList Class Reference
G4VModularPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VModularPhysicsList.hh>
Inherits G4VUserPhysicsList.
Inherited by B3PhysicsList, B3PhysicsList, BrachyPhysicsList, doiPETPhysicsList, EICPhysicsList, ExUCNPhysicsList, F04PhysicsList, F05PhysicsList, F06PhysicsList, FTF_BIC, FTFP_BERT, FTFP_BERT_ATL, FTFP_BERT_HP, FTFP_BERT_TRV, FTFQGSP_BERT, G4HumanPhantomPhysicsList, GammaKnifePhysicsList, GammaRayTelPhysicsList, HadrontherapyPhysicsList, IORTPhysicsList, LBE, ML2PhysicsList, NuBeam, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, pyG4VModularPhysicsList::CB_G4VModularPhysicsList, QBBC, QGS_BIC, QGSP_BERT, QGSP_BERT_HP, QGSP_BIC, QGSP_BIC_AllHP, QGSP_BIC_HP, QGSP_FTFP_BERT, QPhysicsList, Shielding, STCyclotronPhysicsList, UltraPhysicsList, and XrayFluoPhysicsList.
Public Member Functions
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
virtual void SetCuts ()
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Static Public Member Functions
static const G4VMPLManager & GetSubInstanceManager ()
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Protected Types
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Member Functions
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Protected Attributes
G4int verboseLevel
G4int g4vmplInstanceID
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 92 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VModularPhysicsList.hh
Member Typedef Documentation
typedef G4VMPLData::G4PhysConstVectorData G4VModularPhysicsList::G4PhysConstVector protected
Definition at line 146 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 146 of file G4VModularPhysicsList.hh
Constructor & Destructor Documentation
G4VModularPhysicsList::G4VModularPhysicsList ()
Definition at line 52 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 52 of file G4VModularPhysicsList.cc
References G4VUPLSplitter< T >::CreateSubInstance(), g4vmplInstanceID, and G4VMPLsubInstanceManager.
G4VModularPhysicsList::~G4VModularPhysicsList () virtual
Definition at line 59 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VModularPhysicsList.cc
References G4MT_physicsVector.
G4VModularPhysicsList::G4VModularPhysicsList (const G4VModularPhysicsList & right) protected
Definition at line 68 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VModularPhysicsList.cc
References G4VUPLSplitter< T >::CreateSubInstance(), g4vmplInstanceID, and G4VMPLsubInstanceManager.
Member Function Documentation
void G4VModularPhysicsList::ConstructParticle (void) override virtual
Implements G4VUserPhysicsList.
Reimplemented in PhysicsList, PhysicsList, LBE, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, ML2PhysicsList, PhysicsList, PhysicsList, F04PhysicsList, IORTPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, doiPETPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, BrachyPhysicsList, PhysicsList, XrayFluoPhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, GammaRayTelPhysicsList, STCyclotronPhysicsList, PhysicsList, HadrontherapyPhysicsList, PhysicsList, G4HumanPhantomPhysicsList, ExUCNPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, GammaKnifePhysicsList, and EICPhysicsList.
Definition at line 106 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 106 of file G4VModularPhysicsList.cc
References G4MT_physicsVector.
Referenced by F05PhysicsList::ConstructParticle(), F04PhysicsList::ConstructParticle(), and export_G4VModularPhysicsList().
void G4VModularPhysicsList::ConstructProcess (void) override virtual
Implements G4VUserPhysicsList.
Reimplemented in PhysicsList, PhysicsList, LBE, PhysicsList, IORTPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, ML2PhysicsList, PhysicsList, PhysicsList, F04PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, UltraPhysicsList, doiPETPhysicsList, GammaRayTelPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, HadrontherapyPhysicsList, XrayFluoPhysicsList, PhysicsList, BrachyPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, GammaKnifePhysicsList, F05PhysicsList, F06PhysicsList, PhysicsList, PhysicsList, STCyclotronPhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, PhysicsList, G4HumanPhantomPhysicsList, ExUCNPhysicsList, PhysicsList, PhysicsList, and PhysicsList.
Definition at line 126 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 126 of file G4VModularPhysicsList.cc
References G4VUserPhysicsList::AddTransportation(), and G4MT_physicsVector.
Referenced by ExUCNPhysicsList::ConstructProcess(), F06PhysicsList::ConstructProcess(), F05PhysicsList::ConstructProcess(), F04PhysicsList::ConstructProcess(), and export_G4VModularPhysicsList().
G4int G4VModularPhysicsList::GetInstanceID () const inline
Definition at line 162 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 162 of file G4VModularPhysicsList.hh
References g4vmplInstanceID.
Referenced by operator=().
const G4VPhysicsConstructor * G4VModularPhysicsList::GetPhysics (G4int index) const
Definition at line 343 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 343 of file G4VModularPhysicsList.cc
References G4MT_physicsVector.
Referenced by GammaRayTelPhysicsList::AddPackage(), PhysicsList::AddPackage(), and F04PhysicsList::F04PhysicsList().
const G4VPhysicsConstructor * G4VModularPhysicsList::GetPhysics (const G4String & name) const
Definition at line 352 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 352 of file G4VModularPhysicsList.cc
References G4MT_physicsVector.
const G4VPhysicsConstructor * G4VModularPhysicsList::GetPhysicsWithType (G4int physics_type) const
Definition at line 362 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 362 of file G4VModularPhysicsList.cc
References G4MT_physicsVector.
const G4VMPLManager & G4VModularPhysicsList::GetSubInstanceManager () inline static
Definition at line 168 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VModularPhysicsList.hh
References G4VMPLsubInstanceManager.
Referenced by G4PhysicsListWorkspace::G4PhysicsListWorkspace().
G4int G4VModularPhysicsList::GetVerboseLevel () const inline
Definition at line 156 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 156 of file G4VModularPhysicsList.hh
References verboseLevel.
Referenced by G4PhysListRegistry::GetModularPhysicsList(), and G4PhysListFactory::GetReferencePhysList().
G4VModularPhysicsList & G4VModularPhysicsList::operator= (const G4VModularPhysicsList & right) protected
Definition at line 74 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VModularPhysicsList.cc
References G4VUPLSplitter< T >::CreateSubInstance(), G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::directoryPhysicsTable, G4VUserPhysicsList::fDisableCheckParticleList, G4VUserPhysicsList::fIsCheckedForRetrievePhysicsTable, G4VUserPhysicsList::fIsRestoredCutValues, G4VUserPhysicsList::fRetrievePhysicsTable, G4VUserPhysicsList::fStoredInAscii, G4MT_physicsVector, g4vmplInstanceID, G4VMPLsubInstanceManager, G4VUserPhysicsList::g4vuplInstanceID, GetInstanceID(), G4VUserPhysicsList::isSetDefaultCutValue, G4VUPLSplitter< T >::offset, G4VUserPhysicsList::subInstanceManager, and verboseLevel.
void G4VModularPhysicsList::RegisterPhysics (G4VPhysicsConstructor * fPhysics)
Definition at line 138 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 138 of file G4VModularPhysicsList.cc
References G4cout, G4endl, G4Exception(), G4MT_physicsVector, G4State_PreInit, G4StateManager::GetCurrentState(), G4VPhysicsConstructor::GetPhysicsName(), G4VPhysicsConstructor::GetPhysicsType(), G4StateManager::GetStateManager(), JustWarning, and verboseLevel.
Referenced by GammaRayTelPhysicsList::AddPackage(), PhysicsList::AddPackage(), B3PhysicsList::B3PhysicsList(), EICPhysicsList::EICPhysicsList(), export_G4VModularPhysicsList(), ExUCNPhysicsList::ExUCNPhysicsList(), F04PhysicsList::F04PhysicsList(), F05PhysicsList::F05PhysicsList(), F06PhysicsList::F06PhysicsList(), FTF_BIC::FTF_BIC(), FTFP_BERT::FTFP_BERT(), FTFP_BERT_ATL::FTFP_BERT_ATL(), FTFP_BERT_HP::FTFP_BERT_HP(), FTFP_BERT_TRV::FTFP_BERT_TRV(), FTFQGSP_BERT::FTFQGSP_BERT(), G4PhysListRegistry::GetModularPhysicsList(), PHG4Reco::Init(), main(), NuBeam::NuBeam(), QBBC::QBBC(), QGS_BIC::QGS_BIC(), QGSP_BERT::QGSP_BERT(), QGSP_BERT_HP::QGSP_BERT_HP(), QGSP_BIC::QGSP_BIC(), QGSP_BIC_AllHP::QGSP_BIC_AllHP(), QGSP_BIC_HP::QGSP_BIC_HP(), QGSP_FTFP_BERT::QGSP_FTFP_BERT(), QPhysicsList::QPhysicsList(), G4PhysListFactoryMessenger::SetNewValue(), and Shielding::Shielding().
void G4VModularPhysicsList::RemovePhysics (G4VPhysicsConstructor * fPhysics)
Definition at line 284 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 284 of file G4VModularPhysicsList.cc
References G4cout, G4endl, G4Exception(), G4MT_physicsVector, G4State_PreInit, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), JustWarning, and verboseLevel.
void G4VModularPhysicsList::RemovePhysics (G4int type)
Definition at line 254 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 254 of file G4VModularPhysicsList.cc
References G4cout, G4endl, G4Exception(), G4MT_physicsVector, G4State_PreInit, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), JustWarning, and verboseLevel.
void G4VModularPhysicsList::RemovePhysics (const G4String & name)
Definition at line 313 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 313 of file G4VModularPhysicsList.cc
References G4cout, G4endl, G4Exception(), G4MT_physicsVector, G4State_PreInit, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), JustWarning, and verboseLevel.
void G4VModularPhysicsList::ReplacePhysics (G4VPhysicsConstructor * fPhysics)
Definition at line 196 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 196 of file G4VModularPhysicsList.cc
References G4cout, G4endl, G4Exception(), G4MT_physicsVector, G4State_PreInit, G4StateManager::GetCurrentState(), G4VPhysicsConstructor::GetPhysicsName(), G4VPhysicsConstructor::GetPhysicsType(), G4StateManager::GetStateManager(), JustWarning, and verboseLevel.
Referenced by G4PhysListRegistry::GetModularPhysicsList(), G4PhysListFactory::GetReferencePhysList(), main(), and HistoManager::SetIonPhysics().
void G4VModularPhysicsList::SetVerboseLevel (G4int value)
Definition at line 373 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 373 of file G4VModularPhysicsList.cc
References G4MT_physicsVector, and verboseLevel.
Referenced by B3PhysicsList::B3PhysicsList(), BrachyPhysicsList::BrachyPhysicsList(), doiPETPhysicsList::doiPETPhysicsList(), EICPhysicsList::EICPhysicsList(), F04PhysicsList::F04PhysicsList(), FTF_BIC::FTF_BIC(), FTFP_BERT::FTFP_BERT(), FTFP_BERT_ATL::FTFP_BERT_ATL(), FTFP_BERT_HP::FTFP_BERT_HP(), FTFP_BERT_TRV::FTFP_BERT_TRV(), FTFQGSP_BERT::FTFQGSP_BERT(), G4HumanPhantomPhysicsList::G4HumanPhantomPhysicsList(), GammaKnifePhysicsList::GammaKnifePhysicsList(), GammaRayTelPhysicsList::GammaRayTelPhysicsList(), G4PhysListRegistry::GetModularPhysicsList(), G4PhysListFactory::GetReferencePhysList(), HadrontherapyPhysicsList::HadrontherapyPhysicsList(), IORTPhysicsList::IORTPhysicsList(), LBE::LBE(), main(), ML2PhysicsList::ML2PhysicsList(), NuBeam::NuBeam(), PhysicsList::PhysicsList(), QBBC::QBBC(), QGS_BIC::QGS_BIC(), QGSP_BERT::QGSP_BERT(), QGSP_BERT_HP::QGSP_BERT_HP(), QGSP_BIC::QGSP_BIC(), QGSP_BIC_AllHP::QGSP_BIC_AllHP(), QGSP_BIC_HP::QGSP_BIC_HP(), QGSP_FTFP_BERT::QGSP_FTFP_BERT(), QPhysicsList::QPhysicsList(), Shielding::Shielding(), UltraPhysicsList::UltraPhysicsList(), and XrayFluoPhysicsList::XrayFluoPhysicsList().
void G4VModularPhysicsList::TerminateWorker () override virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 383 of file G4VModularPhysicsList.cc.
View newest version in sPHENIX GitHub at line 383 of file G4VModularPhysicsList.cc
References G4MT_physicsVector, and G4VUserPhysicsList::TerminateWorker().
Member Data Documentation
G4int G4VModularPhysicsList::g4vmplInstanceID protected
Definition at line 147 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VModularPhysicsList.hh
Referenced by G4VModularPhysicsList(), GetInstanceID(), and operator=().
G4VMPLManager G4VModularPhysicsList::G4VMPLsubInstanceManager static protected
Definition at line 148 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 148 of file G4VModularPhysicsList.hh
Referenced by G4VModularPhysicsList(), GetSubInstanceManager(), and operator=().
G4int G4VModularPhysicsList::verboseLevel protected
Definition at line 145 of file G4VModularPhysicsList.hh.
View newest version in sPHENIX GitHub at line 145 of file G4VModularPhysicsList.hh
Referenced by GammaKnifePhysicsList::AddPhysicsList(), XrayFluoPhysicsList::AddPhysicsList(), HadrontherapyPhysicsList::AddPhysicsList(), PhysicsList::AddPhysicsList(), GammaRayTelPhysicsList::AddPhysicsList(), ML2PhysicsList::AddPhysicsList(), IORTPhysicsList::AddPhysicsList(), GetVerboseLevel(), operator=(), PhysicsList::RegisterConstructor(), RegisterPhysics(), RemovePhysics(), ReplacePhysics(), PhysicsList::SetBuilderList0(), PhysicsList::SetBuilderList1(), PhysicsList::SetBuilderList2(), GammaKnifePhysicsList::SetCuts(), G4HumanPhantomPhysicsList::SetCuts(), GammaRayTelPhysicsList::SetCuts(), STCyclotronPhysicsList::SetCuts(), QGSP_BERT_HP::SetCuts(), BrachyPhysicsList::SetCuts(), XrayFluoPhysicsList::SetCuts(), UltraPhysicsList::SetCuts(), FTFP_BERT_HP::SetCuts(), IORTPhysicsList::SetCuts(), doiPETPhysicsList::SetCuts(), LBE::SetCuts(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VModularPhysicsList.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VModularPhysicsList.cc