ECCE @ EIC Software: G4BGGPionInelasticXS Class Reference
G4BGGPionInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGPionInelasticXS.hh>
Public Member Functions
G4BGGPionInelasticXS (const G4ParticleDefinition *)
~G4BGGPionInelasticXS () final
G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat) final
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm, const G4Material *mat) final
G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat) final
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void CrossSectionDescription (std::ostream &) const final
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4double CoulombFactorPiPlus (G4double kinEnergy, G4int Z)
G4double FactorPiMinus (G4double kinEnergy)
G4BGGPionInelasticXS & operator= (const G4BGGPionInelasticXS &right)
G4BGGPionInelasticXS (const G4BGGPionInelasticXS &)
Private Attributes
G4double fGlauberEnergy
G4double fLowEnergy
G4double fLowestEnergy
const G4ParticleDefinition * theProton
const G4ParticleDefinition * thePiPlus
G4Pow * fG4pow
G4ComponentGGHadronNucleusXsc * fGlauber
G4UPiNuclearCrossSection * fPion
G4HadronNucleonXsc * fHadron
G4bool isPiplus
G4bool isMaster
Static Private Attributes
static G4double theGlauberFacPiPlus [93] = {0.0}
static G4double theGlauberFacPiMinus [93] = {0.0}
static G4double theLowEPiPlus [93] = {0.0}
static G4double theLowEPiMinus [93] = {0.0}
static G4int theA [93] = {0}
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 65 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BGGPionInelasticXS.hh
Constructor & Destructor Documentation
G4BGGPionInelasticXS::G4BGGPionInelasticXS (const G4ParticleDefinition * p) explicit
Definition at line 66 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 66 of file G4BGGPionInelasticXS.cc
References fG4pow, fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fLowestEnergy, fPion, G4Pow::GetInstance(), CLHEP::GeV, G4HadronicParameters::Instance(), isMaster, isPiplus, CLHEP::MeV, G4PionPlus::PionPlus(), G4Proton::Proton(), G4VCrossSectionDataSet::SetForAllAtomsAndEnergies(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), thePiPlus, theProton, and G4VCrossSectionDataSet::verboseLevel.
G4BGGPionInelasticXS::~G4BGGPionInelasticXS () final
Definition at line 91 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 91 of file G4BGGPionInelasticXS.cc
References fHadron.
G4BGGPionInelasticXS::G4BGGPionInelasticXS (const G4BGGPionInelasticXS &) private
Member Function Documentation
void G4BGGPionInelasticXS::BuildPhysicsTable (const G4ParticleDefinition & p) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 176 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 176 of file G4BGGPionInelasticXS.cc
References A(), G4UPiNuclearCrossSection::BuildPhysicsTable(), CoulombFactorPiPlus(), FactorPiMinus(), FatalException, fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fPion, G4cout, G4endl, G4Exception(), G4lrint(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4NistManager::GetAtomicMassAmu(), G4UPiNuclearCrossSection::GetInelasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4ParticleDefinition::GetParticleName(), G4NistManager::Instance(), isMaster, isPiplus, mom, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetKineticEnergy(), theA, theGlauberFacPiMinus, theGlauberFacPiPlus, theLowEPiMinus, theLowEPiPlus, thePiPlus, and G4VCrossSectionDataSet::verboseLevel.
G4double G4BGGPionInelasticXS::CoulombFactorPiPlus (G4double kinEnergy, G4int Z) private
Definition at line 277 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 277 of file G4BGGPionInelasticXS.cc
References G4NuclearRadii::CoulombFactor(), theA, and thePiPlus.
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
void G4BGGPionInelasticXS::CrossSectionDescription (std::ostream & outFile) const final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 293 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 293 of file G4BGGPionInelasticXS.cc
G4double G4BGGPionInelasticXS::FactorPiMinus (G4double kinEnergy) private
Definition at line 285 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 285 of file G4BGGPionInelasticXS.cc
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::GetElementCrossSection (const G4DynamicParticle * dp, G4int Z, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 118 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 118 of file G4BGGPionInelasticXS.cc
References barn, CoulombFactorPiPlus(), Acts::VectorHelpers::cross(), FactorPiMinus(), fGlauber, fGlauberEnergy, fLowEnergy, fLowestEnergy, fPion, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4UPiNuclearCrossSection::GetInelasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), GetIsoCrossSection(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), isPiplus, max, min, theA, theGlauberFacPiMinus, theGlauberFacPiPlus, theLowEPiMinus, theLowEPiPlus, G4VCrossSectionDataSet::verboseLevel, and Z.
G4double G4BGGPionInelasticXS::GetIsoCrossSection (const G4DynamicParticle * dp, G4int Z, G4int A, const G4Isotope * iso = nullptr, const G4Element * elm = nullptr, const G4Material * mat = nullptr) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 152 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 152 of file G4BGGPionInelasticXS.cc
References barn, Acts::VectorHelpers::cross(), fHadron, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4HadronNucleonXsc::GetInelasticHadronNucleonXsc(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4HadronNucleonXsc::HadronNucleonXscNS(), theProton, and G4VCrossSectionDataSet::verboseLevel.
Referenced by GetElementCrossSection().
G4bool G4BGGPionInelasticXS::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 99 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 99 of file G4BGGPionInelasticXS.cc
G4bool G4BGGPionInelasticXS::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * elm, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 107 of file G4BGGPionInelasticXS.cc.
View newest version in sPHENIX GitHub at line 107 of file G4BGGPionInelasticXS.cc
G4BGGPionInelasticXS& G4BGGPionInelasticXS::operator= (const G4BGGPionInelasticXS & right) private
Member Data Documentation
G4Pow* G4BGGPionInelasticXS::fG4pow private
Definition at line 114 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 114 of file G4BGGPionInelasticXS.hh
Referenced by G4BGGPionInelasticXS().
G4ComponentGGHadronNucleusXsc* G4BGGPionInelasticXS::fGlauber private
Definition at line 116 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 116 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionInelasticXS(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::fGlauberEnergy private
Definition at line 101 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionInelasticXS(), and GetElementCrossSection().
G4HadronNucleonXsc* G4BGGPionInelasticXS::fHadron private
Definition at line 118 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 118 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionInelasticXS(), GetIsoCrossSection(), and ~G4BGGPionInelasticXS().
G4double G4BGGPionInelasticXS::fLowEnergy private
Definition at line 102 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 102 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionInelasticXS(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::fLowestEnergy private
Definition at line 103 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 103 of file G4BGGPionInelasticXS.hh
Referenced by G4BGGPionInelasticXS(), and GetElementCrossSection().
G4UPiNuclearCrossSection* G4BGGPionInelasticXS::fPion private
Definition at line 117 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 117 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionInelasticXS(), and GetElementCrossSection().
G4bool G4BGGPionInelasticXS::isMaster private
Definition at line 120 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 120 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), and G4BGGPionInelasticXS().
G4bool G4BGGPionInelasticXS::isPiplus private
Definition at line 119 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 119 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionInelasticXS(), and GetElementCrossSection().
G4int G4BGGPionInelasticXS::theA = {0} static private
Definition at line 109 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 109 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactorPiPlus(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::theGlauberFacPiMinus = {0.0} static private
Definition at line 106 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 106 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::theGlauberFacPiPlus = {0.0} static private
Definition at line 105 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 105 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::theLowEPiMinus = {0.0} static private
Definition at line 108 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionInelasticXS::theLowEPiPlus = {0.0} static private
Definition at line 107 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 107 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
const G4ParticleDefinition* G4BGGPionInelasticXS::thePiPlus private
Definition at line 112 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 112 of file G4BGGPionInelasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactorPiPlus(), and G4BGGPionInelasticXS().
const G4ParticleDefinition* G4BGGPionInelasticXS::theProton private
Definition at line 111 of file G4BGGPionInelasticXS.hh.
View newest version in sPHENIX GitHub at line 111 of file G4BGGPionInelasticXS.hh
Referenced by G4BGGPionInelasticXS(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGPionInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4BGGPionInelasticXS.cc