ECCE @ EIC Software: G4VUserDetectorConstruction Class Reference
G4VUserDetectorConstruction Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUserDetectorConstruction.hh>
Inherited by B01DetectorConstruction, B02DetectorConstruction, B03DetectorConstruction, B1DetectorConstruction, B1DetectorConstruction, B1DetectorConstruction, B2aDetectorConstruction, B2bDetectorConstruction, B2bDetectorConstruction, B3DetectorConstruction, B3DetectorConstruction, B4cDetectorConstruction, B4dDetectorConstruction, B4DetectorConstruction, B4DetectorConstruction, B5DetectorConstruction, BrachyDetectorConstruction, CCalDetectorConstruction, CexmcSetup, CML2WorldConstruction, Collimator100BeamLine, Collimator40BeamLine, Collimator50BeamLine, Collimator60BeamLine, Collimator70BeamLine, Collimator80BeamLine, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction0, DetectorConstruction0, DetectorConstruction0, DicomDetectorConstruction, DMXDetectorConstruction, doiPETDetectorConstruction, ElectronBenchmarkDetector, eRositaDetectorConstruction, ExErrorDetectorConstruction, ExGflash1DetectorConstruction, ExGflash2DetectorConstruction, ExGflash3DetectorConstruction, ExGflashDetectorConstruction, ExN01DetectorConstruction, ExN02DetectorConstruction, ExN03DetectorConstruction, ExN04DetectorConstruction, ExN04DetectorConstruction, ExP01DetectorConstruction, ExP02DetConstrReader, ExP02DetectorConstruction, ExTGDetectorConstruction, ExTGDetectorConstructionWithCpp, ExTGDetectorConstructionWithCuts, ExTGDetectorConstructionWithSD, ExUCNDetectorConstruction, EzDetectorConstruction, F01DetectorConstruction, F02DetectorConstruction, F03DetectorConstruction, F04DetectorConstruction, F05DetectorConstruction, F06DetectorConstruction, FCALTestbeamSetup, FFDetectorConstruction, FW::DD4hepG4::GeoConstruction, FW::Geant4::MMDetectorConstruction, G01DetectorConstruction, G02DetectorConstruction, G03DetectorConstruction, G04DetectorConstruction, G3toG4DetectorConstruction, G4HumanPhantomConstruction, GammaKnifeDetectorConstruction, GammaRayTelDetectorConstruction, GB01DetectorConstruction, GB02DetectorConstruction, GB03DetectorConstruction, GB04DetectorConstruction, GB05DetectorConstruction, GB06DetectorConstruction, GB07DetectorConstruction, GeometryConstruction, H02DetectorConstruction, LaserDrivenBeamLine, LXeDetectorConstruction, MyDetectorConstruction, OpNoviceDetectorConstruction, Par01DetectorConstruction, Par02DetectorConstruction, PassiveCarbonBeamLine, PassiveProtonBeamLine, PHG4PhenixDetector, PurgMagDetectorConstruction, pyG4VUserDetectorConstruction::CB_G4VUserDetectorConstruction, QDetectorConstruction, QDetectorConstruction, RE01DetectorConstruction, RE02DetectorConstruction, RE03DetectorConstruction, RE04DetectorConstruction, RE05DetectorConstruction, RE06DetectorConstruction, read_gdml.MyDetectorConstruction, read_gdml.MyDetectorConstruction, RMC01DetectorConstruction, STCyclotronDetectorConstruction, test.MyDetectorConstruction, test.MyDetectorConstruction, test.MyDetectorConstruction, TrentoPassiveProtonBeamLine, TSDetectorConstruction, UltraDetectorConstruction, WLSDetectorConstruction, XDetectorConstruction, XrayFluoDetectorConstruction, XrayFluoGeometry, XrayFluoMercuryDetectorConstruction, XrayFluoPlaneDetectorConstruction, and XrayTelDetectorConstruction.
Public Member Functions
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()=0
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Protected Member Functions
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Private Attributes
std::vector
< G4VUserParallelWorld * > parallelWorld
Detailed Description
Definition at line 49 of file G4VUserDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VUserDetectorConstruction.hh
Constructor & Destructor Documentation
G4VUserDetectorConstruction::G4VUserDetectorConstruction ()
Definition at line 41 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VUserDetectorConstruction.cc
G4VUserDetectorConstruction::~G4VUserDetectorConstruction () virtual
Definition at line 44 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VUserDetectorConstruction.cc
Member Function Documentation
void G4VUserDetectorConstruction::CloneF () virtual
Definition at line 108 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 108 of file G4VUserDetectorConstruction.cc
References G4FieldManager::Clone(), FatalException, G4Exception(), G4LogicalVolumeStore::GetInstance(), it, second, and G4LogicalVolume::SetFieldManager().
void G4VUserDetectorConstruction::CloneSD () virtual
Definition at line 154 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 154 of file G4VUserDetectorConstruction.cc
References G4VSensitiveDetector::Clone(), FatalException, G4Exception(), G4VSensitiveDetector::GetFullPathName(), G4LogicalVolumeStore::GetInstance(), G4VSensitiveDetector::GetName(), it, second, and G4LogicalVolume::SetSensitiveDetector().
virtual G4VPhysicalVolume* G4VUserDetectorConstruction::Construct () pure virtual
Implemented in RE02DetectorConstruction, DetectorConstruction, CexmcSetup, GammaRayTelDetectorConstruction, TSDetectorConstruction, DetectorConstruction, CML2WorldConstruction, XrayFluoDetectorConstruction, DetectorConstruction, F01DetectorConstruction, F02DetectorConstruction, F03DetectorConstruction, DicomDetectorConstruction, XrayFluoMercuryDetectorConstruction, UltraDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DMXDetectorConstruction, DetectorConstruction, ExN03DetectorConstruction, PurgMagDetectorConstruction, XrayFluoPlaneDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, doiPETDetectorConstruction, DetectorConstruction, Collimator100BeamLine, Collimator40BeamLine, Collimator50BeamLine, Collimator60BeamLine, Collimator70BeamLine, Collimator80BeamLine, XrayTelDetectorConstruction, DetectorConstruction, ExErrorDetectorConstruction, DetectorConstruction, WLSDetectorConstruction, LaserDrivenBeamLine, DetectorConstruction, DetectorConstruction, DetectorConstruction, G02DetectorConstruction, RMC01DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, B4cDetectorConstruction, B4dDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, FCALTestbeamSetup, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, B4DetectorConstruction, B4DetectorConstruction, F04DetectorConstruction, F06DetectorConstruction, DetectorConstruction, ExN02DetectorConstruction, Par02DetectorConstruction, G03DetectorConstruction, ExP01DetectorConstruction, F05DetectorConstruction, FFDetectorConstruction, DetectorConstruction, LXeDetectorConstruction, DetectorConstruction, DetectorConstruction, BrachyDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, B5DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, RE04DetectorConstruction, eRositaDetectorConstruction, XrayFluoGeometry, B2aDetectorConstruction, B2bDetectorConstruction, DetectorConstruction0, DetectorConstruction0, DetectorConstruction, ExUCNDetectorConstruction, DetectorConstruction0, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, ElectronBenchmarkDetector, B2bDetectorConstruction, ExGflashDetectorConstruction, DetectorConstruction, DetectorConstruction, TrentoPassiveProtonBeamLine, STCyclotronDetectorConstruction, GB04DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DicomPartialDetectorConstruction, DetectorConstruction, ExN01DetectorConstruction, DetectorConstruction, PassiveCarbonBeamLine, PassiveProtonBeamLine, DetectorConstruction, GB01DetectorConstruction, GB02DetectorConstruction, GB06DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, MyDetectorConstruction, DetectorConstruction, G3toG4DetectorConstruction, B3DetectorConstruction, B3DetectorConstruction, DetectorConstruction, ExGflash1DetectorConstruction, ExGflash3DetectorConstruction, GammaKnifeDetectorConstruction, GB07DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, ExGflash2DetectorConstruction, G01DetectorConstruction, ExP02DetConstrReader, RE06DetectorConstruction, B01DetectorConstruction, B02DetectorConstruction, GB03DetectorConstruction, GB05DetectorConstruction, GeometryConstruction, DetectorConstruction, DetectorConstruction, OpNoviceDetectorConstruction, DetectorConstruction, EzDetectorConstruction, QDetectorConstruction, QDetectorConstruction, DetectorConstruction, ExN04DetectorConstruction, ExP02DetectorConstruction, RE05DetectorConstruction, B1DetectorConstruction, B1DetectorConstruction, B03DetectorConstruction, Par01DetectorConstruction, G04DetectorConstruction, ExTGDetectorConstruction, ExTGDetectorConstructionWithCpp, ExTGDetectorConstructionWithCuts, ExTGDetectorConstructionWithSD, RE01DetectorConstruction, RE03DetectorConstruction, B1DetectorConstruction, G4HumanPhantomConstruction, DetectorConstruction, XDetectorConstruction, pyG4VUserDetectorConstruction::CB_G4VUserDetectorConstruction, ExN04DetectorConstruction, CCalDetectorConstruction, DetectorConstruction, H02DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, FW::DD4hepG4::GeoConstruction, DetectorConstruction, PHG4PhenixDetector, and FW::Geant4::MMDetectorConstruction.
Referenced by read_gdml.MyDetectorConstruction::Construct(), test.MyDetectorConstruction::Construct(), export_G4VUserDetectorConstruction(), G4RunManager::InitializeGeometry(), and G4ErrorRunManagerHelper::SetUserInitialization().
G4int G4VUserDetectorConstruction::ConstructParallelGeometries ()
Definition at line 64 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VUserDetectorConstruction.cc
References parallelWorld.
Referenced by G4RunManager::InitializeGeometry().
void G4VUserDetectorConstruction::ConstructParallelSD ()
Definition at line 76 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VUserDetectorConstruction.cc
References parallelWorld.
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::InitializeGeometry().
void G4VUserDetectorConstruction::ConstructSDandField () virtual
Reimplemented in RE02DetectorConstruction, DetectorConstruction, DicomDetectorConstruction, TSDetectorConstruction, GammaRayTelDetectorConstruction, XrayFluoDetectorConstruction, F01DetectorConstruction, F02DetectorConstruction, F03DetectorConstruction, XrayFluoMercuryDetectorConstruction, UltraDetectorConstruction, DetectorConstruction, DetectorConstruction, DMXDetectorConstruction, XrayFluoPlaneDetectorConstruction, DetectorConstruction, PurgMagDetectorConstruction, DetectorConstruction, WLSDetectorConstruction, DetectorConstruction, LaserDrivenBeamLine, DetectorConstruction, DetectorConstruction, B01DetectorConstruction, DetectorConstruction, B4cDetectorConstruction, B4dDetectorConstruction, DetectorConstruction, F04DetectorConstruction, Par02DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, FCALTestbeamSetup, B4DetectorConstruction, B4DetectorConstruction, F06DetectorConstruction, DetectorConstruction, F05DetectorConstruction, DetectorConstruction, LXeDetectorConstruction, ElectronBenchmarkDetector, B5DetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, B2aDetectorConstruction, B2bDetectorConstruction, ExUCNDetectorConstruction, B2bDetectorConstruction, ExGflashDetectorConstruction, DetectorConstruction, STCyclotronDetectorConstruction, GB04DetectorConstruction, DetectorConstruction, DetectorConstruction, GB01DetectorConstruction, GB02DetectorConstruction, GB06DetectorConstruction, DetectorConstruction, DetectorConstruction, G4HumanPhantomConstruction, B3DetectorConstruction, B3DetectorConstruction, ExGflash1DetectorConstruction, ExGflash3DetectorConstruction, RE06DetectorConstruction, GB07DetectorConstruction, ExGflash2DetectorConstruction, GB03DetectorConstruction, GB05DetectorConstruction, DetectorConstruction, RE05DetectorConstruction, DetectorConstruction, Par01DetectorConstruction, G04DetectorConstruction, ExTGDetectorConstructionWithSD, RE01DetectorConstruction, RE03DetectorConstruction, XDetectorConstruction, DetectorConstruction, DetectorConstruction, DetectorConstruction, and DetectorConstruction.
Definition at line 94 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 94 of file G4VUserDetectorConstruction.cc
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::InitializeGeometry().
G4int G4VUserDetectorConstruction::GetNumberOfParallelWorld () const
Definition at line 83 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 83 of file G4VUserDetectorConstruction.cc
References parallelWorld.
Referenced by GetParallelWorld().
G4VUserParallelWorld * G4VUserDetectorConstruction::GetParallelWorld (G4int i) const
Definition at line 86 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 86 of file G4VUserDetectorConstruction.cc
References GetNumberOfParallelWorld(), and parallelWorld.
Referenced by RE06DetectorConstruction::SetSerialGeometry(), and HadrontherapyDetectorConstruction::UpdateGeometry().
void G4VUserDetectorConstruction::RegisterParallelWorld (G4VUserParallelWorld * aPW)
Definition at line 47 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VUserDetectorConstruction.cc
References FatalErrorInArgument, G4Exception(), G4VUserParallelWorld::GetName(), and parallelWorld.
Referenced by LaserDrivenBeamLine::LaserDrivenBeamLine(), main(), PassiveCarbonBeamLine::PassiveCarbonBeamLine(), PassiveProtonBeamLine::PassiveProtonBeamLine(), and TrentoPassiveProtonBeamLine::TrentoPassiveProtonBeamLine().
void G4VUserDetectorConstruction::SetSensitiveDetector (const G4String & logVolName, G4VSensitiveDetector * aSD, G4bool multi = false) protected
Definition at line 205 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 205 of file G4VUserDetectorConstruction.cc
References FatalErrorInArgument, G4Exception(), G4LogicalVolumeStore::GetInstance(), G4VSensitiveDetector::GetName(), and pos().
Referenced by H02DetectorConstruction::Construct(), XDetectorConstruction::ConstructSDandField(), ExTGDetectorConstructionWithSD::ConstructSDandField(), RE01DetectorConstruction::ConstructSDandField(), RE05DetectorConstruction::ConstructSDandField(), G4HumanPhantomConstruction::ConstructSDandField(), B3DetectorConstruction::ConstructSDandField(), STCyclotronDetectorConstruction::ConstructSDandField(), B2aDetectorConstruction::ConstructSDandField(), B2bDetectorConstruction::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), FCALTestbeamSetup::ConstructSDandField(), B4cDetectorConstruction::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), B01DetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), UltraDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), TSDetectorConstruction::ConstructSDandField(), DicomDetectorConstruction::ConstructSDandField(), MyDetectorConstruction::SetSDtoScoreVoxel(), GB03DetectorConstruction::SetupDetectors(), and RE06DetectorConstruction::SetupDetectors().
void G4VUserDetectorConstruction::SetSensitiveDetector (G4LogicalVolume * logVol, G4VSensitiveDetector * aSD) protected
Definition at line 240 of file G4VUserDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 240 of file G4VUserDetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4MultiSensitiveDetector::AddSD(), G4Exception(), G4VSensitiveDetector::GetName(), G4LogicalVolume::GetName(), G4SDManager::GetSDMpointer(), G4LogicalVolume::GetSensitiveDetector(), JustWarning, and G4LogicalVolume::SetSensitiveDetector().
Member Data Documentation
std::vector<G4VUserParallelWorld*> G4VUserDetectorConstruction::parallelWorld private
Definition at line 73 of file G4VUserDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VUserDetectorConstruction.hh
Referenced by ConstructParallelGeometries(), ConstructParallelSD(), GetNumberOfParallelWorld(), GetParallelWorld(), and RegisterParallelWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VUserDetectorConstruction.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VUserDetectorConstruction.cc