ECCE @ EIC Software: G4UIcommand Class Reference
G4UIcommand Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcommand.hh>
Public Member Functions
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
virtual G4int DoIt (G4String parameterList)
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
size_t GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
size_t GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Static Public Member Functions
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Protected Types
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Protected Member Functions
G4int CheckNewValue (const char *newValue)
Protected Attributes
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Private Member Functions
void G4UIcommandCommonConstructorCode (const char *theCommandPath)
G4int TypeCheck (const char *t)
G4int RangeCheck (const char *t)
G4int IsInt (const char *str, short maxLength)
G4int IsDouble (const char *str)
G4int ExpectExponent (const char *str)
yystype Expression (void)
yystype LogicalORExpression (void)
yystype LogicalANDExpression (void)
yystype EqualityExpression (void)
yystype RelationalExpression (void)
yystype AdditiveExpression (void)
yystype MultiplicativeExpression (void)
yystype UnaryExpression (void)
yystype PrimaryExpression (void)
G4int Eval2 (yystype arg1, G4int op, yystype arg2)
G4int CompareInt (G4int arg1, G4int op, G4int arg2)
G4int CompareDouble (G4double arg1, G4int op, G4double arg2)
tokenNum Yylex (void)
unsigned IndexOf (const char *)
unsigned IsParameter (const char *)
G4int G4UIpGetc (void)
G4int G4UIpUngetc (G4int c)
G4int Backslash (G4int c)
G4int Follow (G4int expect, G4int ifyes, G4int ifno)
G4String TokenToStr (G4int token)
void PrintToken (void)
Private Attributes
G4UImessenger * messenger
G4String commandPath
G4String commandName
G4String rangeString
std::vector< G4UIparameter * > parameter
std::vector< G4String > commandGuidance
std::vector< G4ApplicationState > availabelStateList
G4String rangeBuf
G4int bp
tokenNum token
yystype yylval
std::vector< yystype > newVal
G4int paramERR
Detailed Description
Definition at line 50 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 50 of file G4UIcommand.hh
Member Typedef Documentation
using G4UIcommand::tokenNum = G4UItokenNum::tokenNum protected
Definition at line 218 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 218 of file G4UIcommand.hh
using G4UIcommand::yystype = G4UItokenNum::yystype protected
Definition at line 217 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 217 of file G4UIcommand.hh
Constructor & Destructor Documentation
G4UIcommand::G4UIcommand ()
Definition at line 43 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 43 of file G4UIcommand.cc
G4UIcommand::G4UIcommand (const char * theCommandPath, G4UImessenger * theMessenger, G4bool tBB = true)
Definition at line 50 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 50 of file G4UIcommand.cc
References availabelStateList, G4cerr, G4endl, G4State_Abort, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_Init, G4State_PreInit, and G4UIcommandCommonConstructorCode().
G4UIcommand::~G4UIcommand () virtual
Definition at line 103 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 103 of file G4UIcommand.cc
References G4UImanager::GetUIpointer(), parameter, and G4UImanager::RemoveCommand().
Member Function Documentation
yystype G4UIcommand::AdditiveExpression (void) private
Definition at line 830 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 830 of file G4UIcommand.cc
References G4cerr, G4endl, MultiplicativeExpression(), paramERR, and token.
Referenced by RelationalExpression().
void G4UIcommand::AvailableForStates (G4ApplicationState s1)
Definition at line 243 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 243 of file G4UIcommand.cc
References availabelStateList.
Referenced by B2aDetectorMessenger::B2aDetectorMessenger(), B2bDetectorMessenger::B2bDetectorMessenger(), BrachyPhysicsListMessenger::BrachyPhysicsListMessenger(), CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcEventActionMessenger::CexmcEventActionMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcPhysicsManagerMessenger::CexmcPhysicsManagerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), CexmcProductionModelMessenger::CexmcProductionModelMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), CexmcSensitiveDetectorMessenger::CexmcSensitiveDetectorMessenger(), ClusteringAlgoMessenger::ClusteringAlgoMessenger(), G4AnalysisMessengerHelper::CreateSetAxisCommand(), G4AnalysisMessengerHelper::CreateSetAxisLogCommand(), G4AnalysisMessengerHelper::CreateSetBinsCommand(), G4AnalysisMessengerHelper::CreateSetTitleCommand(), G4AnalysisMessengerHelper::CreateSetValuesCommand(), DetectorMessenger::DetectorMessenger(), DicomIntersectVolume::DicomIntersectVolume(), DMXEventActionMessenger::DMXEventActionMessenger(), doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger(), ElectronBenchmarkDetectorMessenger::ElectronBenchmarkDetectorMessenger(), EventActionMessenger::EventActionMessenger(), ExErrorDetectorMessenger::ExErrorDetectorMessenger(), ExGflashMessenger::ExGflashMessenger(), ExN02DetectorMessenger::ExN02DetectorMessenger(), ExN03DetectorMessenger::ExN03DetectorMessenger(), ExP01DetectorMessenger::ExP01DetectorMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F01FieldMessenger::F01FieldMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F02FieldMessenger::F02FieldMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F03FieldMessenger::F03FieldMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04FieldMessenger::F04FieldMessenger(), F04PhysicsListMessenger::F04PhysicsListMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), F04RunActionMessenger::F04RunActionMessenger(), FCALTBEventActionMessenger::FCALTBEventActionMessenger(), Fun4AllMessenger::Fun4AllMessenger(), G02DetectorMessenger::G02DetectorMessenger(), G03DetectorMessenger::G03DetectorMessenger(), G4AdjointPhysicsMessenger::G4AdjointPhysicsMessenger(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4BlineTracerMessenger::G4BlineTracerMessenger(), G4DeexParametersMessenger::G4DeexParametersMessenger(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4EmMessenger::G4EmMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4ErrorMessenger::G4ErrorMessenger(), G4EvManMessenger::G4EvManMessenger(), G4FastSimulationMessenger::G4FastSimulationMessenger(), G4GDMLMessenger::G4GDMLMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4GlobalMagFieldMessenger::G4GlobalMagFieldMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4HumanPhantomMessenger::G4HumanPhantomMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4MonopoleFieldMessenger::G4MonopoleFieldMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4NeutronKillerMessenger::G4NeutronKillerMessenger(), G4NuclideTableMessenger::G4NuclideTableMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleHPMessenger::G4ParticleHPMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4PhysListFactoryMessenger::G4PhysListFactoryMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger(), G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4SchedulerMessenger::G4SchedulerMessenger(), G4StackingMessenger::G4StackingMessenger(), G4TBFieldMessenger::G4TBFieldMessenger(), G4UCNBoundaryProcessMessenger::G4UCNBoundaryProcessMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), GammaKnifePhysicsListMessenger::GammaKnifePhysicsListMessenger(), GammaRayTelAnalysisMessenger::GammaRayTelAnalysisMessenger(), GammaRayTelDetectorMessenger::GammaRayTelDetectorMessenger(), GammaRayTelPhysicsListMessenger::GammaRayTelPhysicsListMessenger(), GB03DetectorMessenger::GB03DetectorMessenger(), GFlashShowerModelMessenger::GFlashShowerModelMessenger(), HadrontherapyDetectorMessenger::HadrontherapyDetectorMessenger(), HadrontherapyEventActionMessenger::HadrontherapyEventActionMessenger(), HadrontherapyParameterMessenger::HadrontherapyParameterMessenger(), HadrontherapyPhysicsListMessenger::HadrontherapyPhysicsListMessenger(), HistoManagerMessenger::HistoManagerMessenger(), IORTDetectorMessenger::IORTDetectorMessenger(), IORTEventActionMessenger::IORTEventActionMessenger(), IORTGeometryMessenger::IORTGeometryMessenger(), IORTPhysicsListMessenger::IORTPhysicsListMessenger(), LXeDetectorMessenger::LXeDetectorMessenger(), ML2PhysicsListMessenger::ML2PhysicsListMessenger(), NeutronHPMessenger::NeutronHPMessenger(), OpNovicePrimaryGeneratorMessenger::OpNovicePrimaryGeneratorMessenger(), PhysicsListMessenger::PhysicsListMessenger(), PrimaryGeneratorMessenger::PrimaryGeneratorMessenger(), RE06DetectorMessenger::RE06DetectorMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), RMC01DetectorMessenger::RMC01DetectorMessenger(), RunActionMessenger::RunActionMessenger(), RunMessenger::RunMessenger(), G4GenericMessenger::Command::SetStates(), STCyclotronDetectorMessenger::STCyclotronDetectorMessenger(), StepLimiterMessenger::StepLimiterMessenger(), TrackingMessenger::TrackingMessenger(), WLSDetectorMessenger::WLSDetectorMessenger(), WLSPrimaryGeneratorMessenger::WLSPrimaryGeneratorMessenger(), WLSRunActionMessenger::WLSRunActionMessenger(), WLSSteppingActionMessenger::WLSSteppingActionMessenger(), XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoEventActionMessenger::XrayFluoEventActionMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoMercuryPrimaryGeneratorMessenger::XrayFluoMercuryPrimaryGeneratorMessenger(), XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), XrayFluoPlanePrimaryGeneratorMessenger::XrayFluoPlanePrimaryGeneratorMessenger(), and XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger().
void G4UIcommand::AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
Definition at line 249 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 249 of file G4UIcommand.cc
References availabelStateList.
void G4UIcommand::AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
Definition at line 257 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 257 of file G4UIcommand.cc
References availabelStateList.
void G4UIcommand::AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
Definition at line 267 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 267 of file G4UIcommand.cc
References availabelStateList.
void G4UIcommand::AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
Definition at line 279 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 279 of file G4UIcommand.cc
References availabelStateList.
G4int G4UIcommand::Backslash (G4int c) private
G4String G4UIcommand::CategoryOf (const char * unitName) static
Definition at line 319 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 319 of file G4UIcommand.cc
References G4UnitDefinition::GetCategory().
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithBestUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithBestUnit(), G4UIcmdWithADoubleAndUnit::DoIt(), G4UIcmdWith3VectorAndUnit::DoIt(), G4MatScanMessenger::G4MatScanMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIparameter::SetDefaultUnit(), and TrackingMessenger::TrackingMessenger().
G4int G4UIcommand::CheckNewValue (const char * newValue) protected
Definition at line 511 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 511 of file G4UIcommand.cc
References fParameterOutOfRange, G4String::isNull(), RangeCheck(), and rangeString.
Referenced by DoIt().
void G4UIcommand::CommandFailed (G4int errCode, G4ExceptionDescription & ed) inline
Definition at line 201 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 201 of file G4UIcommand.hh
References commandFailureCode, and failureDescription.
Referenced by G4ScoreQuantityMessenger::CheckMeshPS(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4ParticleGunMessenger::SetNewValue(), G4ScoreQuantityMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4ProcessTableMessenger::SetNewValue(), G4ProcessManagerMessenger::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), and G4UserPhysicsListMessenger::SetNewValue().
void G4UIcommand::CommandFailed (G4ExceptionDescription & ed) inline
Definition at line 203 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 203 of file G4UIcommand.hh
References commandFailureCode, and failureDescription.
G4int G4UIcommand::CompareDouble (G4double arg1, G4int op, G4double arg2) private
Definition at line 1034 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1034 of file G4UIcommand.cc
References EQ, G4cerr, G4endl, GE, GT, LE, LT, NE, and paramERR.
Referenced by Eval2().
G4int G4UIcommand::CompareInt (G4int arg1, G4int op, G4int arg2) private
Definition at line 1009 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1009 of file G4UIcommand.cc
References EQ, G4cerr, G4endl, GE, GT, LE, LT, NE, and paramERR.
Referenced by Eval2().
G4ThreeVector G4UIcommand::ConvertTo3Vector (const char * st) static
Definition at line 478 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 478 of file G4UIcommand.cc
Referenced by G4AnyType::Ref< ValueType >::FromString(), G4UIcmdWith3Vector::GetNew3VectorValue(), G4VisCommandsViewerSet::SetNewValue(), and G4AttCheck::Standard().
G4bool G4UIcommand::ConvertToBool (const char * st) static
Definition at line 440 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 440 of file G4UIcommand.cc
References G4String::toUpper(), and v.
Referenced by G4AnyType::Ref< ValueType >::FromString(), G4HepRepMessenger::G4HepRepMessenger(), G4UIcmdWithABool::GetNewBoolValue(), G4InteractorMessenger::SetNewValue(), G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), G4VisCommandAbortReviewKeptEvents::SetNewValue(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4NtupleMessenger::SetNewValue(), G4P1Messenger::SetNewValue(), G4H2Messenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4P2Messenger::SetNewValue(), G4HnMessenger::SetNewValue(), G4VisCommandSceneActivateModel::SetNewValue(), G4H1Messenger::SetNewValue(), G4VisCommandDrawOnlyToBeKeptEvents::SetNewValue(), G4VisCommandEnable::SetNewValue(), G4OpticalPhysicsMessenger::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandGeometrySetDaughtersInvisible::SetNewValue(), G4VisCommandGeometrySetForceAuxEdgeVisible::SetNewValue(), G4VisCommandGeometrySetForceSolid::SetNewValue(), G4VisCommandGeometrySetForceWireframe::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), and G4VisCommandGeometrySetVisibility::SetNewValue().
G4ThreeVector G4UIcommand::ConvertToDimensioned3Vector (const char * st) static
Definition at line 488 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 488 of file G4UIcommand.cc
References ValueOf().
Referenced by G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4GenericMessenger::SetNewValue(), and G4AttCheck::Standard().
G4double G4UIcommand::ConvertToDimensionedDouble (const char * st) static
Definition at line 466 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 466 of file G4UIcommand.cc
References ValueOf().
Referenced by G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4VisCommandsViewerSet::SetNewValue(), G4GenericMessenger::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), and G4AttCheck::Standard().
G4double G4UIcommand::ConvertToDouble (const char * st) static
Definition at line 458 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 458 of file G4UIcommand.cc
Referenced by DicomFileMgr::AddCT2Density(), DicomFileMgr::AddMaterial(), DicomFileMgr::AddMaterialDensity(), G4UIcmdWithADoubleAndUnit::DoIt(), G4UIcmdWith3VectorAndUnit::DoIt(), G4AnalysisMessengerHelper::GetBinData(), G4UIcmdWithADouble::GetNewDoubleValue(), G4AnalysisMessengerHelper::GetValueData(), main(), DicomDetectorConstruction::ReadPhantomDataFile(), DicomDetectorConstruction::ReadVoxelDensities(), DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial(), DicomFileMgr::SetCompression(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), DicomIntersectVolume::SetNewValue(), and CexmcScenePrimitivesMessenger::SetNewValue().
G4int G4UIcommand::ConvertToInt (const char * st) static
Definition at line 450 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 450 of file G4UIcommand.cc
Referenced by DicomFileMgr::AddCT2Density(), G4AnalysisMessengerHelper::GetBinData(), G4UIcmdWithAnInteger::GetNewIntValue(), DicomIntersectVolume::GetPhysicalVolumes(), main(), DicomFileStructure::ReadData(), G4ParticleHPMessenger::SetNewValue(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4NtupleMessenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4P1Messenger::SetNewValue(), G4P2Messenger::SetNewValue(), G4H2Messenger::SetNewValue(), G4HnMessenger::SetNewValue(), G4PlotMessenger::SetNewValue(), G4H1Messenger::SetNewValue(), G4TrackingMessenger::SetNewValue(), and G4DNAChemistryManager::SetNewValue().
G4String G4UIcommand::ConvertToString (G4bool boolVal) static
Definition at line 375 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 375 of file G4UIcommand.cc
Referenced by G4tgrParameterMgr::AddParameterNumber(), ExTGRCRegionCutsMgr::AddRegionCuts(), G4MPImanager::BeamOn(), G4tgbRotationMatrix::BuildG4RotMatrix(), G4HepRepFileSceneHandler::CheckFileOpen(), G4tgbPlaceParameterisation::CheckNExtraData(), G4tgbVolume::CheckNoSolidParams(), G4tgrUtils::CheckWLsize(), G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit(), RE01TrackerHit::CreateAttValues(), SensitiveDetectorHit::CreateAttValues(), RE01CalorimeterHit::CreateAttValues(), RE05CalorimeterHit::CreateAttValues(), RE01Trajectory::CreateAttValues(), B5HodoscopeHit::CreateAttValues(), B5HadCalorimeterHit::CreateAttValues(), B5DriftChamberHit::CreateAttValues(), B5EmCalorimeterHit::CreateAttValues(), G4RichTrajectory::CreateAttValues(), F04Trajectory::CreateAttValues(), WLSTrajectory::CreateAttValues(), G4SmoothTrajectory::CreateAttValues(), G4Trajectory::CreateAttValues(), RE04Trajectory::CreateAttValues(), G4TheMTRayTracer::CreateBitMap(), G4TrajectoriesModel::CreateCurrentAttValues(), Par02Output::CreateNtuples(), G4UIcmdWithADoubleAndUnit::DoIt(), G4UIcmdWith3VectorAndUnit::DoIt(), G4tgrFileIn::DumpException(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpPVPlacement(), G4tgbGeometryDumper::DumpRotationMatrix(), DicomBeamBlock::DumpToFile(), DicomBeamCompensator::DumpToFile(), DicomBeamWedge::DumpToFile(), ExTGRCRegionData::ExTGRCRegionData(), G4tgbVolume::FindOrConstructG4Solid(), G4MolecularConfiguration::G4MolecularConfiguration(), G4tgrMaterialSimple::GetComponent(), G4HepRepMessenger::GetCurrentValue(), ExN04StackingActionMessenger::GetCurrentValue(), RE05StackingActionMessenger::GetCurrentValue(), GB03DetectorMessenger::GetCurrentValue(), RE06DetectorMessenger::GetCurrentValue(), G4GMocrenMessenger::GetCurrentValue(), DetectorConstructionMessenger::GetCurrentValue(), G4EvManMessenger::GetCurrentValue(), G4MatScanMessenger::GetCurrentValue(), G4RTMessenger::GetCurrentValue(), G4tgrMessenger::GetCurrentValue(), G4GeometryMessenger::GetCurrentValue(), G4ParticleGunMessenger::GetCurrentValue(), G4TrackingMessenger::GetCurrentValue(), G4PolarizationMessenger::GetCurrentValue(), G4MoleculeShootMessenger::GetCurrentValue(), G4ScoringMessenger::GetCurrentValue(), G4ProcessTableMessenger::GetCurrentValue(), G4DecayTableMessenger::GetCurrentValue(), G4SchedulerMessenger::GetCurrentValue(), G4ProductionCutsTableMessenger::GetCurrentValue(), G4RunMessenger::GetCurrentValue(), G4ParticlePropertyMessenger::GetCurrentValue(), G4ProcessManagerMessenger::GetCurrentValue(), G4UIcontrolMessenger::GetCurrentValue(), G4UserPhysicsListMessenger::GetCurrentValue(), G4ParticleMessenger::GetCurrentValue(), G4DNAChemistryManager::GetCurrentValue(), G4VITSteppingVerbose::GetCurrentValue(), G4VisCommandViewerDolly::GetCurrentValue(), G4VisCommandViewerScale::GetCurrentValue(), G4VisCommandViewerZoom::GetCurrentValue(), G4tgrUtils::GetDouble(), G4tgrMaterialSimple::GetFraction(), G4tgbGeometryDumper::GetIsotopeName(), DicomIntersectVolume::GetLogicalVolumes(), G4ScoreLogColorMap::GetMapColor(), G4tgbGeometryDumper::GetObjectName(), DicomIntersectVolume::GetPhysicalVolumes(), G4tgrUtils::GetRotationFromDirection(), G4tgrVolume::GetVolume(), G4EnergySplitter::GetVoxelID(), G4MolecularConfiguration::IonizeMolecule(), main(), G4MolecularConfiguration::MoveOneElectron(), G4DNAMolecularReactionTable::PrintTable(), DicomPartialDetectorConstruction::ReadPhantomDataFile(), DicomDetectorConstruction::ReadPhantomDataFile(), DicomDetectorConstruction::ReadPhantomDataNew(), DicomDetectorConstruction::ReadVoxelDensities(), DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial(), G4MolecularConfiguration::RemoveElectron(), ExTGRCRegionData::SetCutsData(), G4VisCommandsViewerSet::SetNewValue(), G4GenericMessenger::SetNewValue(), DicomIntersectVolume::SetNewValue(), G4AttCheck::Standard(), Par02Output::StartAnalysis(), and G4TheMTRayTracer::Trace().
G4String G4UIcommand::ConvertToString (G4int intValue) static
Definition at line 382 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 382 of file G4UIcommand.cc
G4String G4UIcommand::ConvertToString (G4double doubleValue) static
Definition at line 390 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 390 of file G4UIcommand.cc
References G4UImanager::DoublePrecisionStr().
G4String G4UIcommand::ConvertToString (G4double doubleValue, const char * unitName) static
Definition at line 401 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 401 of file G4UIcommand.cc
References G4UImanager::DoublePrecisionStr(), and ValueOf().
G4String G4UIcommand::ConvertToString (G4ThreeVector vec) static
Definition at line 415 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 415 of file G4UIcommand.cc
References G4UImanager::DoublePrecisionStr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4String G4UIcommand::ConvertToString (G4ThreeVector vec, const char * unitName) static
Definition at line 426 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 426 of file G4UIcommand.cc
References G4UImanager::DoublePrecisionStr(), ValueOf(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4int G4UIcommand::DoIt (G4String parameterList) virtual
Reimplemented in G4UIcmdWith3VectorAndUnit, and G4UIcmdWithADoubleAndUnit.
Definition at line 126 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 126 of file G4UIcommand.cc
References G4String::append(), CheckNewValue(), fParameterOutOfRange, fParameterUnreadable, G4UImessenger::GetCurrentValue(), G4String::index(), G4Threading::IsMasterThread(), G4String::isNull(), messenger, parameter, G4UImessenger::SetNewValue(), and workerThreadOnly.
Referenced by G4UImanager::ApplyCommand(), G4UIcmdWithADoubleAndUnit::DoIt(), and G4UIcmdWith3VectorAndUnit::DoIt().
yystype G4UIcommand::EqualityExpression (void) private
Definition at line 770 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 770 of file G4UIcommand.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, EQ, Eval2(), G4cerr, G4endl, G4UItokenNum::yystype::I, NE, paramERR, RelationalExpression(), token, G4UItokenNum::yystype::type, and Yylex().
Referenced by LogicalANDExpression().
G4int G4UIcommand::Eval2 (yystype arg1, G4int op, yystype arg2) private
Definition at line 928 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 928 of file G4UIcommand.cc
References commandName, CompareDouble(), CompareInt(), G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, D(), G4cerr, G4endl, G4UItokenNum::yystype::I, I, G4UItokenNum::IDENTIFIER, IndexOf(), newVal, paramERR, parameter, rangeString, G4UItokenNum::yystype::S, and G4UItokenNum::yystype::type.
Referenced by EqualityExpression(), and RelationalExpression().
G4int G4UIcommand::ExpectExponent (const char * str) private
Definition at line 588 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 588 of file G4UIcommand.cc
References IsInt().
Referenced by IsDouble().
yystype G4UIcommand::Expression (void) private
Definition at line 688 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 688 of file G4UIcommand.cc
References G4cerr, G4endl, and LogicalORExpression().
Referenced by PrimaryExpression(), and RangeCheck().
G4int G4UIcommand::Follow (G4int expect, G4int ifyes, G4int ifno) private
Definition at line 1151 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1151 of file G4UIcommand.cc
References c, G4UIpGetc(), and G4UIpUngetc().
Referenced by Yylex().
void G4UIcommand::G4UIcommandCommonConstructorCode (const char * theCommandPath) private
Definition at line 83 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 83 of file G4UIcommand.cc
References G4UImanager::AddNewCommand(), G4UImanager::GetMasterUIpointer(), G4UImanager::GetUIpointer(), and G4Threading::IsWorkerThread().
Referenced by G4UIcommand().
G4int G4UIcommand::G4UIpGetc (void) private
Definition at line 1162 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1162 of file G4UIcommand.cc
References bp, BTOF::length, and rangeString.
Referenced by Follow(), and Yylex().
G4int G4UIcommand::G4UIpUngetc (G4int c) private
Definition at line 1170 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1170 of file G4UIcommand.cc
References bp, G4cerr, G4endl, paramERR, and rangeString.
Referenced by Follow(), and Yylex().
const G4String& G4UIcommand::GetCommandName () const inline
Definition at line 140 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 140 of file G4UIcommand.hh
References commandName.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIcommand(), G4GenericMessenger::GetCurrentValue(), G4NtupleMessenger::SetNewValue(), G4GenericMessenger::SetNewValue(), DicomIntersectVolume::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4AnalysisMessengerHelper::WarnAboutParameters().
const G4String& G4UIcommand::GetCommandPath () const inline
Definition at line 138 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 138 of file G4UIcommand.hh
References commandPath.
Referenced by G4UIcommandTree::AddNewCommand(), G4UImessenger::AddUIcommand(), G4ScoreQuantityMessenger::CheckMeshPS(), G4UIGAG::CodeGenJavaTree(), G4UIGainServer::CodeGenJavaTree(), G4UIGAG::CodeGenTclTree(), export_G4UIcommand(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), operator!=(), operator==(), G4UIcommandTree::RemoveCommand(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), G4UIGAG::SendDisableList(), G4UIGainServer::SendDisableList(), DicomIntersectVolume::SetNewValue(), G4ScoreQuantityMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), G4GenericMessenger::Command::SetUnit(), G4UIGAG::UpdateParamVal(), and G4UIGainServer::UpdateParamVal().
G4String G4UIcommand::GetCurrentValue ()
Definition at line 238 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 238 of file G4UIcommand.cc
References G4UImessenger::GetCurrentValue(), and messenger.
Referenced by export_G4UIcommand(), and G4UImanager::GetCurrentValues().
G4String& G4UIcommand::GetFailureDescription () inline
Definition at line 207 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 207 of file G4UIcommand.hh
References failureDescription.
Referenced by G4UImanager::ApplyCommand().
size_t G4UIcommand::GetGuidanceEntries () const inline
Definition at line 134 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 134 of file G4UIcommand.hh
References commandGuidance.
Referenced by G4UIGAG::CodeGenTclTree(), G4VVisCommand::CopyGuidanceFrom(), G4UIcommandTree::CreateHTML(), export_G4UIcommand(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4GenericMessenger::Command::SetUnit().
const G4String& G4UIcommand::GetGuidanceLine (G4int i) const inline
Definition at line 136 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 136 of file G4UIcommand.hh
References commandGuidance.
Referenced by G4UIGAG::CodeGenTclTree(), G4VVisCommand::CopyGuidanceFrom(), G4UIcommandTree::CreateHTML(), export_G4UIcommand(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), and G4GenericMessenger::Command::SetUnit().
G4UImessenger* G4UIcommand::GetMessenger () const inline
Definition at line 148 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 148 of file G4UIcommand.hh
References messenger.
Referenced by G4GenericMessenger::Command::SetUnit().
G4UIparameter* G4UIcommand::GetParameter (G4int i) const inline
Definition at line 144 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 144 of file G4UIcommand.hh
References parameter.
Referenced by G4UIcmdWithADoubleAndUnit::ConvertToStringWithBestUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithBestUnit(), G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit(), G4UIcmdWith3VectorAndUnit::ConvertToStringWithDefaultUnit(), G4VVisCommand::CopyParametersFrom(), G4UIcommandTree::CreateHTML(), G4UIcmdWithADoubleAndUnit::DoIt(), G4UIcmdWith3VectorAndUnit::DoIt(), G4VMPIsession::ExecCommand(), G4UIterminal::ExecuteCommand(), export_G4UIcommand(), G4UImanager::GetCurrentStringValue(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), G4UIcmdWithNucleusLimits::SetDefaultValue(), G4GenericMessenger::Command::SetUnit(), G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), and G4UIcmdWith3VectorAndUnit::SetUnitCandidates().
size_t G4UIcommand::GetParameterEntries () const inline
Definition at line 142 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 142 of file G4UIcommand.hh
References parameter.
Referenced by G4VVisCommand::CopyParametersFrom(), G4UIcommandTree::CreateHTML(), export_G4UIcommand(), G4UImanager::GetCurrentStringValue(), G4UIGainServer::GetNewTreeValues(), G4UIGAG::GetNewTreeValues(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), G4InteractorMessenger::SetNewValue(), G4NtupleMessenger::SetNewValue(), G4P1Messenger::SetNewValue(), G4P2Messenger::SetNewValue(), G4H2Messenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4HnMessenger::SetNewValue(), G4PlotMessenger::SetNewValue(), G4H1Messenger::SetNewValue(), and G4AnalysisMessengerHelper::WarnAboutParameters().
const G4String& G4UIcommand::GetRange () const inline
Definition at line 132 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 132 of file G4UIcommand.hh
References rangeString.
Referenced by G4UIcommandTree::CreateHTML(), export_G4UIcommand(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), and G4GenericMessenger::Command::SetUnit().
std::vector<G4ApplicationState>* G4UIcommand::GetStateList () inline
Definition at line 146 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 146 of file G4UIcommand.hh
References availabelStateList.
Referenced by G4UIcommandTree::CreateHTML(), and pyG4UIcommand::f_GetStateList().
const G4String G4UIcommand::GetTitle () const inline
Definition at line 169 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 169 of file G4UIcommand.hh
References commandGuidance.
Referenced by export_G4UIcommand(), G4UIGainServer::GetNewTreeStructure(), G4UIGAG::GetNewTreeStructure(), and G4UIcommandTree::GetTitle().
G4int G4UIcommand::IfCommandFailed () inline
Definition at line 205 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 205 of file G4UIcommand.hh
References commandFailureCode.
Referenced by G4UImanager::ApplyCommand().
unsigned G4UIcommand::IndexOf (const char * nam) private
Definition at line 1060 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1060 of file G4UIcommand.cc
References G4cerr, G4endl, paramERR, parameter, and pname().
Referenced by Eval2().
G4bool G4UIcommand::IsAvailable ()
Definition at line 293 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 293 of file G4UIcommand.cc
References availabelStateList, G4StateManager::GetCurrentState(), and G4StateManager::GetStateManager().
Referenced by G4UImanager::ApplyCommand(), export_G4UIcommand(), G4UIGAG::SendDisableList(), and G4UIGainServer::SendDisableList().
G4int G4UIcommand::IsDouble (const char * str) private
Definition at line 597 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 597 of file G4UIcommand.cc
References ExpectExponent().
Referenced by TypeCheck(), and Yylex().
G4int G4UIcommand::IsInt (const char * str, short maxLength) private
Definition at line 564 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 564 of file G4UIcommand.cc
References G4cerr, G4endl, and BTOF::length.
Referenced by ExpectExponent(), TypeCheck(), and Yylex().
unsigned G4UIcommand::IsParameter (const char * nam) private
Definition at line 1078 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1078 of file G4UIcommand.cc
References parameter, and pname().
Referenced by Yylex().
G4bool G4UIcommand::IsWorkerThreadOnly () const inline
Definition at line 193 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 193 of file G4UIcommand.hh
References workerThreadOnly.
Referenced by G4UIcommandTree::RemoveCommand().
void G4UIcommand::List () virtual
Definition at line 352 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 352 of file G4UIcommand.cc
References commandGuidance, commandPath, G4cout, G4endl, G4String::isNull(), parameter, rangeString, and workerThreadOnly.
Referenced by export_G4UIcommand(), G4UIcommandTree::ListCurrent(), G4UIcommandTree::ListCurrentWithNum(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
yystype G4UIcommand::LogicalANDExpression (void) private
Definition at line 734 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 734 of file G4UIcommand.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::CONSTSTRING, G4UItokenNum::yystype::D, EqualityExpression(), G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, G4UItokenNum::LOGICALAND, paramERR, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by LogicalORExpression().
yystype G4UIcommand::LogicalORExpression (void) private
Definition at line 699 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 699 of file G4UIcommand.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::CONSTSTRING, G4UItokenNum::yystype::D, G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, LogicalANDExpression(), G4UItokenNum::LOGICALOR, paramERR, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by Expression().
yystype G4UIcommand::MultiplicativeExpression (void) private
Definition at line 842 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 842 of file G4UIcommand.cc
References G4cerr, G4endl, paramERR, token, and UnaryExpression().
Referenced by AdditiveExpression().
G4bool G4UIcommand::operator!= (const G4UIcommand & right) const
Definition at line 119 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 119 of file G4UIcommand.cc
References commandPath, and GetCommandPath().
G4bool G4UIcommand::operator== (const G4UIcommand & right) const
Definition at line 114 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 114 of file G4UIcommand.cc
References commandPath, and GetCommandPath().
yystype G4UIcommand::PrimaryExpression (void) private
Definition at line 891 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 891 of file G4UIcommand.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, Expression(), G4cerr, G4endl, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, paramERR, G4UItokenNum::yystype::S, token, G4UItokenNum::yystype::type, Yylex(), and yylval.
Referenced by UnaryExpression().
void G4UIcommand::PrintToken (void) private
G4int G4UIcommand::RangeCheck (const char * t) private
Definition at line 657 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 657 of file G4UIcommand.cc
References bp, G4UItokenNum::CONSTINT, Expression(), G4cerr, G4endl, G4UItokenNum::yystype::I, newVal, paramERR, parameter, rangeString, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by CheckNewValue().
yystype G4UIcommand::RelationalExpression (void) private
Definition at line 801 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 801 of file G4UIcommand.cc
References AdditiveExpression(), G4UItokenNum::CONSTINT, Eval2(), G4cerr, G4endl, GE, GT, G4UItokenNum::yystype::I, LE, LT, token, G4UItokenNum::yystype::type, and Yylex().
Referenced by EqualityExpression().
void G4UIcommand::ResetFailure () inline
Definition at line 209 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 209 of file G4UIcommand.hh
References commandFailureCode, and failureDescription.
Referenced by G4UImanager::ApplyCommand(), and G4UIcontrolMessenger::SetNewValue().
void G4UIcommand::SetGuidance (const char * aGuidance) inline
Definition at line 160 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 160 of file G4UIcommand.hh
References commandGuidance.
Referenced by B2aDetectorMessenger::B2aDetectorMessenger(), B2bDetectorMessenger::B2bDetectorMessenger(), BrachyPhysicsListMessenger::BrachyPhysicsListMessenger(), CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcEventActionMessenger::CexmcEventActionMessenger(), CexmcMessenger::CexmcMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcPhysicsManagerMessenger::CexmcPhysicsManagerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), CexmcProductionModelMessenger::CexmcProductionModelMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), CexmcSensitiveDetectorMessenger::CexmcSensitiveDetectorMessenger(), ClusteringAlgoMessenger::ClusteringAlgoMessenger(), CML2MainMessenger::CML2MainMessenger(), CML2PrimaryGenerationActionMessenger::CML2PrimaryGenerationActionMessenger(), G4VVisCommand::CopyGuidanceFrom(), G4CascadeParamMessenger::CreateDirectory(), G4AnalysisMessengerHelper::CreateHnDirectory(), G4AnalysisMessengerHelper::CreateSetAxisCommand(), G4AnalysisMessengerHelper::CreateSetAxisLogCommand(), G4AnalysisMessengerHelper::CreateSetBinsCommand(), G4AnalysisMessengerHelper::CreateSetTitleCommand(), G4AnalysisMessengerHelper::CreateSetValuesCommand(), G4GenericMessenger::DeclareMethod(), G4GenericMessenger::DeclareMethodWithUnit(), G4GenericMessenger::DeclareProperty(), G4GenericMessenger::DeclarePropertyWithUnit(), DetectorConstructionMessenger::DetectorConstructionMessenger(), DetectorMessenger::DetectorMessenger(), DicomIntersectVolume::DicomIntersectVolume(), DMXEventActionMessenger::DMXEventActionMessenger(), DMXRunActionMessenger::DMXRunActionMessenger(), doiPETAnalysisMessenger::doiPETAnalysisMessenger(), doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger(), ElectronBenchmarkDetectorMessenger::ElectronBenchmarkDetectorMessenger(), EventActionMessenger::EventActionMessenger(), ExErrorDetectorMessenger::ExErrorDetectorMessenger(), ExGflashMessenger::ExGflashMessenger(), ExN02DetectorMessenger::ExN02DetectorMessenger(), ExN03DetectorMessenger::ExN03DetectorMessenger(), ExP01DetectorMessenger::ExP01DetectorMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F01FieldMessenger::F01FieldMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F02FieldMessenger::F02FieldMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F03FieldMessenger::F03FieldMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04EventActionMessenger::F04EventActionMessenger(), F04FieldMessenger::F04FieldMessenger(), F04PhysicsListMessenger::F04PhysicsListMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), F04RunActionMessenger::F04RunActionMessenger(), F04SteppingActionMessenger::F04SteppingActionMessenger(), FCALTBEventActionMessenger::FCALTBEventActionMessenger(), G4ScoreQuantityMessenger::FilterCommands(), Fun4AllMessenger::Fun4AllMessenger(), G02DetectorMessenger::G02DetectorMessenger(), G03DetectorMessenger::G03DetectorMessenger(), G4AdjointPhysicsMessenger::G4AdjointPhysicsMessenger(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4BlineTracerMessenger::G4BlineTracerMessenger(), G4DecayTableMessenger::G4DecayTableMessenger(), G4DeexParametersMessenger::G4DeexParametersMessenger(), G4DMmessenger::G4DMmessenger(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4EmMessenger::G4EmMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4ErrorMessenger::G4ErrorMessenger(), G4EvManMessenger::G4EvManMessenger(), G4FastSimulationMessenger::G4FastSimulationMessenger(), G4GDMLMessenger::G4GDMLMessenger(), G4GenericMessenger::G4GenericMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4GlobalMagFieldMessenger::G4GlobalMagFieldMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4HumanPhantomMessenger::G4HumanPhantomMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4InteractorMessenger::G4InteractorMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4ModelCmdActive< M >::G4ModelCmdActive(), G4ModelCmdAddInt< M >::G4ModelCmdAddInt(), G4ModelCmdAddInterval< M >::G4ModelCmdAddInterval(), G4ModelCmdAddIntervalContext< M >::G4ModelCmdAddIntervalContext(), G4ModelCmdAddString< M >::G4ModelCmdAddString(), G4ModelCmdAddValue< M >::G4ModelCmdAddValue(), G4ModelCmdAddValueContext< M >::G4ModelCmdAddValueContext(), G4ModelCmdApplyColour< M >::G4ModelCmdApplyColour(), G4ModelCmdApplyStringColour< M >::G4ModelCmdApplyStringColour(), G4ModelCmdCreateContextDir< M >::G4ModelCmdCreateContextDir(), G4ModelCmdDraw< M >::G4ModelCmdDraw(), G4ModelCmdInvert< M >::G4ModelCmdInvert(), G4ModelCmdReset< M >::G4ModelCmdReset(), G4ModelCmdSetAuxPtsFillStyle< M >::G4ModelCmdSetAuxPtsFillStyle(), G4ModelCmdSetAuxPtsSize< M >::G4ModelCmdSetAuxPtsSize(), G4ModelCmdSetAuxPtsSizeType< M >::G4ModelCmdSetAuxPtsSizeType(), G4ModelCmdSetAuxPtsType< M >::G4ModelCmdSetAuxPtsType(), G4ModelCmdSetAuxPtsVisible< M >::G4ModelCmdSetAuxPtsVisible(), G4ModelCmdSetDrawAuxPts< M >::G4ModelCmdSetDrawAuxPts(), G4ModelCmdSetDrawLine< M >::G4ModelCmdSetDrawLine(), G4ModelCmdSetDrawStepPts< M >::G4ModelCmdSetDrawStepPts(), G4ModelCmdSetLineVisible< M >::G4ModelCmdSetLineVisible(), G4ModelCmdSetStepPtsFillStyle< M >::G4ModelCmdSetStepPtsFillStyle(), G4ModelCmdSetStepPtsSize< M >::G4ModelCmdSetStepPtsSize(), G4ModelCmdSetStepPtsSizeType< M >::G4ModelCmdSetStepPtsSizeType(), G4ModelCmdSetStepPtsType< M >::G4ModelCmdSetStepPtsType(), G4ModelCmdSetStepPtsVisible< M >::G4ModelCmdSetStepPtsVisible(), G4ModelCmdSetString< M >::G4ModelCmdSetString(), G4ModelCmdSetTimeSliceInterval< M >::G4ModelCmdSetTimeSliceInterval(), G4ModelCmdVerbose< M >::G4ModelCmdVerbose(), G4MonopoleFieldMessenger::G4MonopoleFieldMessenger(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4NeutronKillerMessenger::G4NeutronKillerMessenger(), G4NistMessenger::G4NistMessenger(), G4NuclideTableMessenger::G4NuclideTableMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleHPMessenger::G4ParticleHPMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4PersistencyCenterMessenger::G4PersistencyCenterMessenger(), G4PhysListFactoryMessenger::G4PhysListFactoryMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger(), G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4SchedulerMessenger::G4SchedulerMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4SDmessenger::G4SDmessenger(), G4StackingMessenger::G4StackingMessenger(), G4TBFieldMessenger::G4TBFieldMessenger(), G4tgrMessenger::G4tgrMessenger(), G4TrackingMessenger::G4TrackingMessenger(), G4UCNBoundaryProcessMessenger::G4UCNBoundaryProcessMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UnitsMessenger::G4UnitsMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandDrawLogicalVolume::G4VisCommandDrawLogicalVolume(), G4VisCommandDrawTree::G4VisCommandDrawTree(), G4VisCommandDrawView::G4VisCommandDrawView(), G4VisCommandDrawVolume::G4VisCommandDrawVolume(), G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour(), G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible(), G4VisCommandGeometrySetForceAuxEdgeVisible::G4VisCommandGeometrySetForceAuxEdgeVisible(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle(), G4VisCommandGeometrySetForceSolid::G4VisCommandGeometrySetForceSolid(), G4VisCommandGeometrySetForceWireframe::G4VisCommandGeometrySetForceWireframe(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandGeometrySetLineWidth::G4VisCommandGeometrySetLineWidth(), G4VisCommandGeometrySetVisibility::G4VisCommandGeometrySetVisibility(), G4VisCommandListManagerList< Manager >::G4VisCommandListManagerList(), G4VisCommandListManagerSelect< Manager >::G4VisCommandListManagerSelect(), G4VisCommandManagerMode< Manager >::G4VisCommandManagerMode(), G4VisCommandModelCreate< Factory >::G4VisCommandModelCreate(), G4VisCommandOpen::G4VisCommandOpen(), G4VisCommandSceneAddGPS::G4VisCommandSceneAddGPS(), G4VisCommandSetArrow3DLineSegmentsPerCircle::G4VisCommandSetArrow3DLineSegmentsPerCircle(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetExtentForField::G4VisCommandSetExtentForField(), G4VisCommandSetLineWidth::G4VisCommandSetLineWidth(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandSetTextLayout::G4VisCommandSetTextLayout(), G4VisCommandSetTextSize::G4VisCommandSetTextSize(), G4VisCommandSetTouchable::G4VisCommandSetTouchable(), G4VisCommandSetVolumeForField::G4VisCommandSetVolumeForField(), G4VisCommandSpecify::G4VisCommandSpecify(), G4VisCommandsTouchable::G4VisCommandsTouchable(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerCentreOn::G4VisCommandViewerCentreOn(), G4VisCommandViewerDefaultHiddenEdge::G4VisCommandViewerDefaultHiddenEdge(), G4VisCommandViewerDefaultStyle::G4VisCommandViewerDefaultStyle(), GammaKnifeMessenger::GammaKnifeMessenger(), GammaKnifePhysicsListMessenger::GammaKnifePhysicsListMessenger(), GammaRayTelAnalysisMessenger::GammaRayTelAnalysisMessenger(), GammaRayTelDetectorMessenger::GammaRayTelDetectorMessenger(), GammaRayTelPhysicsListMessenger::GammaRayTelPhysicsListMessenger(), GB03DetectorMessenger::GB03DetectorMessenger(), GFlashShowerModelMessenger::GFlashShowerModelMessenger(), HadrontherapyAnalysisFileMessenger::HadrontherapyAnalysisFileMessenger(), HadrontherapyDetectorMessenger::HadrontherapyDetectorMessenger(), HadrontherapyEventActionMessenger::HadrontherapyEventActionMessenger(), HadrontherapyParameterMessenger::HadrontherapyParameterMessenger(), HadrontherapyPhysicsListMessenger::HadrontherapyPhysicsListMessenger(), HadrontherapyPrimaryGeneratorMessenger::HadrontherapyPrimaryGeneratorMessenger(), HadrontherapyStepMaxMessenger::HadrontherapyStepMaxMessenger(), HistoManagerMessenger::HistoManagerMessenger(), HistoMessenger::HistoMessenger(), IORTDetectorMessenger::IORTDetectorMessenger(), IORTEventActionMessenger::IORTEventActionMessenger(), IORTGeometryMessenger::IORTGeometryMessenger(), IORTPhysicsListMessenger::IORTPhysicsListMessenger(), IORTStepMaxMessenger::IORTStepMaxMessenger(), LXeDetectorMessenger::LXeDetectorMessenger(), LXeEventMessenger::LXeEventMessenger(), ML2PhysicsListMessenger::ML2PhysicsListMessenger(), ML2StepMaxMessenger::ML2StepMaxMessenger(), MyKleinNishinaMessenger::MyKleinNishinaMessenger(), NeutronHPMessenger::NeutronHPMessenger(), OpNovicePrimaryGeneratorMessenger::OpNovicePrimaryGeneratorMessenger(), PhysicsListMessenger::PhysicsListMessenger(), PrimaryGeneratorMessenger::PrimaryGeneratorMessenger(), G4ScoreQuantityMessenger::QuantityCommands(), RE05PrimaryGeneratorMessenger::RE05PrimaryGeneratorMessenger(), RE05StackingActionMessenger::RE05StackingActionMessenger(), RE06DetectorMessenger::RE06DetectorMessenger(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), RMC01DetectorMessenger::RMC01DetectorMessenger(), RunActionMessenger::RunActionMessenger(), RunMessenger::RunMessenger(), G4GenericMessenger::Command::SetGuidance(), G4GenericMessenger::SetGuidance(), G4VisCommandModelCreate< Factory >::SetNewValue(), G4GenericMessenger::Command::SetUnit(), StackingMessenger::StackingMessenger(), STCyclotronDetectorMessenger::STCyclotronDetectorMessenger(), StepLimiterMessenger::StepLimiterMessenger(), StepMaxMessenger::StepMaxMessenger(), TrackingMessenger::TrackingMessenger(), WLSDetectorMessenger::WLSDetectorMessenger(), WLSEventActionMessenger::WLSEventActionMessenger(), WLSPrimaryGeneratorMessenger::WLSPrimaryGeneratorMessenger(), WLSRunActionMessenger::WLSRunActionMessenger(), WLSSteppingActionMessenger::WLSSteppingActionMessenger(), XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoEventActionMessenger::XrayFluoEventActionMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoMercuryPrimaryGeneratorMessenger::XrayFluoMercuryPrimaryGeneratorMessenger(), XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), XrayFluoPlanePrimaryGeneratorMessenger::XrayFluoPlanePrimaryGeneratorMessenger(), XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger(), and XrayFluoStepMaxMessenger::XrayFluoStepMaxMessenger().
void G4UIcommand::SetParameter (G4UIparameter *const newParameter) inline
Definition at line 151 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 151 of file G4UIcommand.hh
References newVal, and parameter.
Referenced by CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), G4VVisCommand::CopyParametersFrom(), G4AnalysisMessengerHelper::CreateSetAxisCommand(), G4AnalysisMessengerHelper::CreateSetAxisLogCommand(), G4AnalysisMessengerHelper::CreateSetBinsCommand(), G4AnalysisMessengerHelper::CreateSetTitleCommand(), G4AnalysisMessengerHelper::CreateSetValuesCommand(), G4GenericMessenger::DeclareMethod(), G4GenericMessenger::DeclareProperty(), G4ScoreQuantityMessenger::FilterCommands(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmExtraParametersMessenger::G4EmExtraParametersMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4InteractorMessenger::G4InteractorMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4ModelCmdApplyColour< M >::G4ModelCmdApplyColour(), G4ModelCmdApplyStringColour< M >::G4ModelCmdApplyStringColour(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour(), G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible(), G4VisCommandGeometrySetForceAuxEdgeVisible::G4VisCommandGeometrySetForceAuxEdgeVisible(), G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle(), G4VisCommandGeometrySetForceSolid::G4VisCommandGeometrySetForceSolid(), G4VisCommandGeometrySetForceWireframe::G4VisCommandGeometrySetForceWireframe(), G4VisCommandGeometrySetLineStyle::G4VisCommandGeometrySetLineStyle(), G4VisCommandGeometrySetLineWidth::G4VisCommandGeometrySetLineWidth(), G4VisCommandGeometrySetVisibility::G4VisCommandGeometrySetVisibility(), G4VisCommandOpen::G4VisCommandOpen(), G4VisCommandSceneAddArrow::G4VisCommandSceneAddArrow(), G4VisCommandSceneAddAxes::G4VisCommandSceneAddAxes(), G4VisCommandSceneAddLine::G4VisCommandSceneAddLine(), G4VisCommandSceneAddLogicalVolume::G4VisCommandSceneAddLogicalVolume(), G4VisCommandSceneAddLogo::G4VisCommandSceneAddLogo(), G4VisCommandSceneAddScale::G4VisCommandSceneAddScale(), G4VisCommandSceneAddText::G4VisCommandSceneAddText(), G4VisCommandSceneAddText2D::G4VisCommandSceneAddText2D(), G4VisCommandSetColour::G4VisCommandSetColour(), G4VisCommandSetExtentForField::G4VisCommandSetExtentForField(), G4VisCommandSetTextColour::G4VisCommandSetTextColour(), G4VisCommandSetTouchable::G4VisCommandSetTouchable(), G4VisCommandSpecify::G4VisCommandSpecify(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerAddCutawayPlane::G4VisCommandViewerAddCutawayPlane(), G4VisCommandViewerCentreOn::G4VisCommandViewerCentreOn(), G4VisCommandViewerChangeCutawayPlane::G4VisCommandViewerChangeCutawayPlane(), G4VisCommandViewerColourByDensity::G4VisCommandViewerColourByDensity(), HistoMessenger::HistoMessenger(), G4ScoreQuantityMessenger::QuantityCommands(), RMC01AnalysisManagerMessenger::RMC01AnalysisManagerMessenger(), and TrackingMessenger::TrackingMessenger().
void G4UIcommand::SetRange (const char * rs) inline
Definition at line 124 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 124 of file G4UIcommand.hh
References rangeString.
Referenced by CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcEventActionMessenger::CexmcEventActionMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcProductionModelMessenger::CexmcProductionModelMessenger(), CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger(), ClusteringAlgoMessenger::ClusteringAlgoMessenger(), DMXEventActionMessenger::DMXEventActionMessenger(), doiPETAnalysisMessenger::doiPETAnalysisMessenger(), doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger(), EventActionMessenger::EventActionMessenger(), ExGflashMessenger::ExGflashMessenger(), ExN03DetectorMessenger::ExN03DetectorMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04FieldMessenger::F04FieldMessenger(), F04PhysicsListMessenger::F04PhysicsListMessenger(), F04RunActionMessenger::F04RunActionMessenger(), FCALTBEventActionMessenger::FCALTBEventActionMessenger(), G4DecayTableMessenger::G4DecayTableMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4EvManMessenger::G4EvManMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4GlobalMagFieldMessenger::G4GlobalMagFieldMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4MPImessenger::G4MPImessenger(), G4NistMessenger::G4NistMessenger(), G4NuclideTableMessenger::G4NuclideTableMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleHPMessenger::G4ParticleHPMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4PersistencyCenterMessenger::G4PersistencyCenterMessenger(), G4PolarizationMessenger::G4PolarizationMessenger(), G4ProcessManagerMessenger::G4ProcessManagerMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger(), G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4SchedulerMessenger::G4SchedulerMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4StackingMessenger::G4StackingMessenger(), G4tgrMessenger::G4tgrMessenger(), G4TrackingMessenger::G4TrackingMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandSetArrow3DLineSegmentsPerCircle::G4VisCommandSetArrow3DLineSegmentsPerCircle(), G4VisCommandSetLineWidth::G4VisCommandSetLineWidth(), G4VisCommandSetTextSize::G4VisCommandSetTextSize(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), GammaKnifePhysicsListMessenger::GammaKnifePhysicsListMessenger(), GammaRayTelDetectorMessenger::GammaRayTelDetectorMessenger(), GammaRayTelPhysicsListMessenger::GammaRayTelPhysicsListMessenger(), GB03DetectorMessenger::GB03DetectorMessenger(), HadrontherapyEventActionMessenger::HadrontherapyEventActionMessenger(), HadrontherapyStepMaxMessenger::HadrontherapyStepMaxMessenger(), HistoMessenger::HistoMessenger(), IORTEventActionMessenger::IORTEventActionMessenger(), IORTPhysicsListMessenger::IORTPhysicsListMessenger(), IORTStepMaxMessenger::IORTStepMaxMessenger(), ML2StepMaxMessenger::ML2StepMaxMessenger(), MyKleinNishinaMessenger::MyKleinNishinaMessenger(), PhysicsListMessenger::PhysicsListMessenger(), PrimaryGeneratorMessenger::PrimaryGeneratorMessenger(), RE05StackingActionMessenger::RE05StackingActionMessenger(), RE06DetectorMessenger::RE06DetectorMessenger(), RunActionMessenger::RunActionMessenger(), RunMessenger::RunMessenger(), G4GenericMessenger::Command::SetRange(), G4GenericMessenger::Command::SetUnit(), StepLimiterMessenger::StepLimiterMessenger(), StepMaxMessenger::StepMaxMessenger(), WLSDetectorMessenger::WLSDetectorMessenger(), WLSPrimaryGeneratorMessenger::WLSPrimaryGeneratorMessenger(), WLSRunActionMessenger::WLSRunActionMessenger(), WLSSteppingActionMessenger::WLSSteppingActionMessenger(), XrayFluoEventActionMessenger::XrayFluoEventActionMessenger(), XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger(), and XrayFluoStepMaxMessenger::XrayFluoStepMaxMessenger().
void G4UIcommand::SetToBeBroadcasted (G4bool val) inline
Definition at line 183 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 183 of file G4UIcommand.hh
References toBeBroadcasted.
Referenced by G4UIcommandTree::AddNewCommand(), ElectronBenchmarkDetectorMessenger::ElectronBenchmarkDetectorMessenger(), ExGflashMessenger::ExGflashMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), G4GDMLMessenger::G4GDMLMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), LXeDetectorMessenger::LXeDetectorMessenger(), G4GenericMessenger::Command::SetToBeBroadcasted(), and WLSDetectorMessenger::WLSDetectorMessenger().
void G4UIcommand::SetToBeFlushed (G4bool val) inline
Definition at line 187 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 187 of file G4UIcommand.hh
References toBeFlushed.
Referenced by G4GenericMessenger::Command::SetToBeFlushed().
void G4UIcommand::SetWorkerThreadOnly (G4bool val = true) inline
Definition at line 191 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 191 of file G4UIcommand.hh
References workerThreadOnly.
Referenced by G4UIcommandTree::AddNewCommand(), and G4GenericMessenger::Command::SetWorkerThreadOnly().
G4bool G4UIcommand::ToBeBroadcasted () const inline
Definition at line 185 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 185 of file G4UIcommand.hh
References toBeBroadcasted.
Referenced by G4UIcommandTree::AddNewCommand(), and G4UImanager::ApplyCommand().
G4bool G4UIcommand::ToBeFlushed () const inline
Definition at line 189 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 189 of file G4UIcommand.hh
References toBeFlushed.
G4String G4UIcommand::TokenToStr (G4int token) private
G4int G4UIcommand::TypeCheck (const char * t) private
Definition at line 523 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 523 of file G4UIcommand.cc
References G4cerr, G4endl, IsDouble(), IsInt(), and parameter.
yystype G4UIcommand::UnaryExpression (void) private
Definition at line 854 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 854 of file G4UIcommand.cc
References G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, G4cerr, G4endl, G4UItokenNum::yystype::I, paramERR, PrimaryExpression(), token, G4UItokenNum::yystype::type, and Yylex().
Referenced by MultiplicativeExpression().
G4String G4UIcommand::UnitsList (const char * unitCategory) static
Definition at line 324 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 324 of file G4UIcommand.cc
References G4cerr, G4endl, G4UnitDefinition::GetUnitsTable(), and k.
Referenced by G4MatScanMessenger::G4MatScanMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4UIparameter::SetDefaultUnit(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), G4UIcmdWith3VectorAndUnit::SetUnitCategory(), and TrackingMessenger::TrackingMessenger().
G4double G4UIcommand::ValueOf (const char * unitName) static
Definition at line 312 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 312 of file G4UIcommand.cc
References G4UnitDefinition::GetValueOf().
Referenced by ConvertToDimensioned3Vector(), ConvertToDimensionedDouble(), G4VVisCommand::ConvertToDoublePair(), G4VVisCommand::ConvertToString(), ConvertToString(), G4UIcmdWithADoubleAndUnit::DoIt(), G4UIcmdWith3VectorAndUnit::DoIt(), G4UIcmdWithADoubleAndUnit::GetNewUnitValue(), G4UIcmdWith3VectorAndUnit::GetNewUnitValue(), G4VisCommandViewerAddCutawayPlane::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), TrackingMessenger::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), G4MonopolePhysicsMessenger::SetNewValue(), G4MatScanMessenger::SetNewValue(), G4VisCommandSetExtentForField::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4EmExtraParametersMessenger::SetNewValue(), G4VisCommandViewerChangeCutawayPlane::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4UserPhysicsListMessenger::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
tokenNum G4UIcommand::Yylex (void) private
Definition at line 1093 of file G4UIcommand.cc.
View newest version in sPHENIX GitHub at line 1093 of file G4UIcommand.cc
References c, G4UItokenNum::CONSTDOUBLE, G4UItokenNum::CONSTINT, G4UItokenNum::yystype::D, G4String::data(), EQ, Follow(), G4cerr, G4endl, G4UIpGetc(), G4UIpUngetc(), GE, GT, G4UItokenNum::yystype::I, G4UItokenNum::IDENTIFIER, IsDouble(), IsInt(), IsParameter(), LE, G4UItokenNum::LOGICALAND, G4UItokenNum::LOGICALOR, LT, NE, paramERR, G4UItokenNum::yystype::S, t, and yylval.
Referenced by EqualityExpression(), LogicalANDExpression(), LogicalORExpression(), PrimaryExpression(), RangeCheck(), RelationalExpression(), and UnaryExpression().
Member Data Documentation
std::vector<G4ApplicationState> G4UIcommand::availabelStateList private
Definition at line 121 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 121 of file G4UIcommand.hh
Referenced by AvailableForStates(), G4UIcommand(), GetStateList(), and IsAvailable().
G4int G4UIcommand::bp private
Definition at line 251 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 251 of file G4UIcommand.hh
Referenced by G4UIpGetc(), G4UIpUngetc(), and RangeCheck().
G4int G4UIcommand::commandFailureCode protected
Definition at line 197 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 197 of file G4UIcommand.hh
Referenced by CommandFailed(), IfCommandFailed(), and ResetFailure().
std::vector<G4String> G4UIcommand::commandGuidance private
Definition at line 120 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 120 of file G4UIcommand.hh
Referenced by GetGuidanceEntries(), GetGuidanceLine(), GetTitle(), List(), and SetGuidance().
G4String G4UIcommand::commandName private
Definition at line 117 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 117 of file G4UIcommand.hh
Referenced by Eval2(), and GetCommandName().
G4String G4UIcommand::commandPath private
Definition at line 116 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 116 of file G4UIcommand.hh
Referenced by GetCommandPath(), List(), operator!=(), and operator==().
G4String G4UIcommand::failureDescription protected
Definition at line 198 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 198 of file G4UIcommand.hh
Referenced by CommandFailed(), GetFailureDescription(), and ResetFailure().
G4UImessenger* G4UIcommand::messenger private
Definition at line 115 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 115 of file G4UIcommand.hh
Referenced by DoIt(), GetCurrentValue(), and GetMessenger().
std::vector<yystype> G4UIcommand::newVal private
Definition at line 254 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 254 of file G4UIcommand.hh
Referenced by Eval2(), RangeCheck(), and SetParameter().
G4int G4UIcommand::paramERR private
Definition at line 255 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 255 of file G4UIcommand.hh
Referenced by AdditiveExpression(), CompareDouble(), CompareInt(), EqualityExpression(), Eval2(), G4UIpUngetc(), IndexOf(), LogicalANDExpression(), LogicalORExpression(), MultiplicativeExpression(), PrimaryExpression(), RangeCheck(), UnaryExpression(), and Yylex().
std::vector<G4UIparameter*> G4UIcommand::parameter private
Definition at line 119 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 119 of file G4UIcommand.hh
Referenced by DoIt(), Eval2(), GetParameter(), GetParameterEntries(), IndexOf(), IsParameter(), List(), RangeCheck(), SetParameter(), TypeCheck(), and ~G4UIcommand().
G4String G4UIcommand::rangeBuf private
Definition at line 250 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 250 of file G4UIcommand.hh
G4String G4UIcommand::rangeString private
Definition at line 118 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 118 of file G4UIcommand.hh
Referenced by CheckNewValue(), Eval2(), G4UIpGetc(), G4UIpUngetc(), GetRange(), List(), RangeCheck(), and SetRange().
G4bool G4UIcommand::toBeBroadcasted protected
Definition at line 178 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 178 of file G4UIcommand.hh
Referenced by SetToBeBroadcasted(), and ToBeBroadcasted().
G4bool G4UIcommand::toBeFlushed protected
Definition at line 179 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 179 of file G4UIcommand.hh
Referenced by SetToBeFlushed(), and ToBeFlushed().
tokenNum G4UIcommand::token private
Definition at line 252 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 252 of file G4UIcommand.hh
Referenced by AdditiveExpression(), EqualityExpression(), LogicalANDExpression(), LogicalORExpression(), MultiplicativeExpression(), PrimaryExpression(), RangeCheck(), RelationalExpression(), and UnaryExpression().
G4bool G4UIcommand::workerThreadOnly protected
Definition at line 180 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 180 of file G4UIcommand.hh
Referenced by DoIt(), IsWorkerThreadOnly(), List(), and SetWorkerThreadOnly().
yystype G4UIcommand::yylval private
Definition at line 253 of file G4UIcommand.hh.
View newest version in sPHENIX GitHub at line 253 of file G4UIcommand.hh
Referenced by PrimaryExpression(), and Yylex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcommand.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIcommand.cc