ECCE @ EIC Software: G4StatDouble Class Reference
G4StatDouble Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4StatDouble.hh>
Public Member Functions
G4StatDouble ()
G4StatDouble (G4double)
virtual ~G4StatDouble ()
G4StatDouble (const G4StatDouble &)=default
G4StatDouble & operator= (const G4double &rhs)
G4StatDouble & operator= (const G4StatDouble &rhs)
G4StatDouble & operator+= (const G4double &rhs)
G4StatDouble & operator+= (const G4StatDouble &rhs)
void reset ()
void fill (G4double x, G4double weight=1.)
void scale (G4double)
G4double mean () const
G4double rms ()
G4double mean (G4double ext_sum_w) const
G4double rms (G4double ext_sum_w, G4int ext_n)
void add (const G4StatDouble *)
G4int n () const
G4double sum_w () const
G4double sum_w2 () const
G4double sum_wx () const
G4double sum_wx2 () const
Protected Member Functions
G4double rms (G4double sum_wx, G4double sum_wx2, G4double sum_w, G4int n)
Protected Attributes
G4double m_sum_wx
G4double m_sum_wx2
G4int m_n
G4double m_sum_w
G4double m_sum_w2
G4double m_scale
Detailed Description
Definition at line 44 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 44 of file G4StatDouble.hh
Constructor & Destructor Documentation
G4StatDouble::G4StatDouble ()
Definition at line 38 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 38 of file G4StatDouble.cc
References reset().
G4StatDouble::G4StatDouble (G4double x)
Definition at line 43 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 43 of file G4StatDouble.cc
References fill(), and reset().
G4StatDouble::~G4StatDouble () virtual
Definition at line 59 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 59 of file G4StatDouble.cc
G4StatDouble::G4StatDouble (const G4StatDouble &) default
Member Function Documentation
void G4StatDouble::add (const G4StatDouble * ptr)
Definition at line 166 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 166 of file G4StatDouble.cc
References m_n, m_sum_w, m_sum_w2, m_sum_wx, m_sum_wx2, n(), sum_w(), sum_w2(), sum_wx(), and sum_wx2().
Referenced by operator+=().
void G4StatDouble::fill (G4double x, G4double weight = 1.)
Definition at line 62 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 62 of file G4StatDouble.cc
References G4cout, G4endl, INT_MAX, m_n, m_sum_w, m_sum_w2, m_sum_wx, m_sum_wx2, and weight.
Referenced by G4StatDouble(), operator+=(), and operator=().
G4double G4StatDouble::mean () const
Definition at line 82 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 82 of file G4StatDouble.cc
References m_scale, m_sum_w, and m_sum_wx.
Referenced by mean().
G4double G4StatDouble::mean (G4double ext_sum_w) const
Definition at line 92 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 92 of file G4StatDouble.cc
References m_sum_w, and mean().
G4int G4StatDouble::n () const inline
Definition at line 97 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 97 of file G4StatDouble.hh
References m_n.
Referenced by add().
G4StatDouble& G4StatDouble::operator+= (const G4double & rhs) inline
Definition at line 72 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 72 of file G4StatDouble.hh
References fill().
G4StatDouble& G4StatDouble::operator+= (const G4StatDouble & rhs) inline
Definition at line 74 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 74 of file G4StatDouble.hh
References add().
G4StatDouble& G4StatDouble::operator= (const G4double & rhs) inline
Definition at line 56 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 56 of file G4StatDouble.hh
References fill(), and reset().
G4StatDouble& G4StatDouble::operator= (const G4StatDouble & rhs) inline
Definition at line 62 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 62 of file G4StatDouble.hh
References m_n, m_scale, m_sum_w, m_sum_w2, m_sum_wx, and m_sum_wx2.
void G4StatDouble::reset ()
Definition at line 49 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 49 of file G4StatDouble.cc
References m_n, m_scale, m_sum_w, m_sum_w2, m_sum_wx, and m_sum_wx2.
Referenced by G4StatDouble(), and operator=().
G4double G4StatDouble::rms ()
Definition at line 145 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 145 of file G4StatDouble.cc
References m_n, m_sum_w, m_sum_wx, and m_sum_wx2.
Referenced by hijwds(), pyrvch(), pyrvgl(), pyrvgw(), pyrvi1(), pyrvi2(), pyrvi3(), pyrvne(), and rms().
G4double G4StatDouble::rms (G4double ext_sum_w, G4int ext_n)
Definition at line 153 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 153 of file G4StatDouble.cc
References m_sum_wx, m_sum_wx2, and rms().
G4double G4StatDouble::rms (G4double sum_wx, G4double sum_wx2, G4double sum_w, G4int n) protected
Definition at line 107 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 107 of file G4StatDouble.cc
References m_scale, max, G4InuclParticleNames::nn, and tmp.
void G4StatDouble::scale (G4double value)
Definition at line 77 of file G4StatDouble.cc.
View newest version in sPHENIX GitHub at line 77 of file G4StatDouble.cc
References m_scale.
G4double G4StatDouble::sum_w () const inline
Definition at line 98 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 98 of file G4StatDouble.hh
References m_sum_w.
Referenced by add().
G4double G4StatDouble::sum_w2 () const inline
Definition at line 99 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 99 of file G4StatDouble.hh
References m_sum_w2.
Referenced by add().
G4double G4StatDouble::sum_wx () const inline
Definition at line 100 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 100 of file G4StatDouble.hh
References m_sum_wx.
Referenced by add().
G4double G4StatDouble::sum_wx2 () const inline
Definition at line 101 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 101 of file G4StatDouble.hh
References m_sum_wx2.
Referenced by add().
Member Data Documentation
G4int G4StatDouble::m_n protected
Definition at line 111 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 111 of file G4StatDouble.hh
Referenced by add(), fill(), n(), operator=(), reset(), and rms().
G4double G4StatDouble::m_scale protected
Definition at line 114 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 114 of file G4StatDouble.hh
Referenced by mean(), operator=(), reset(), rms(), and scale().
G4double G4StatDouble::m_sum_w protected
Definition at line 112 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 112 of file G4StatDouble.hh
Referenced by add(), fill(), mean(), operator=(), reset(), rms(), and sum_w().
G4double G4StatDouble::m_sum_w2 protected
Definition at line 113 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 113 of file G4StatDouble.hh
Referenced by add(), fill(), operator=(), reset(), and sum_w2().
G4double G4StatDouble::m_sum_wx protected
Definition at line 109 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 109 of file G4StatDouble.hh
Referenced by add(), fill(), mean(), operator=(), reset(), rms(), and sum_wx().
G4double G4StatDouble::m_sum_wx2 protected
Definition at line 110 of file G4StatDouble.hh.
View newest version in sPHENIX GitHub at line 110 of file G4StatDouble.hh
Referenced by add(), fill(), operator=(), reset(), rms(), and sum_wx2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4StatDouble.hh
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/src/G4StatDouble.cc