ECCE @ EIC Software: RE01TrackerHit Class Reference
RE01TrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01TrackerHit.hh>
Public Member Functions
RE01TrackerHit ()
virtual ~RE01TrackerHit ()
void * operator new (size_t)
void operator delete (void *aHit)
virtual void Draw ()
virtual void Print ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
void SetEdep (G4double de)
G4double GetEdep () const
void SetPos (G4ThreeVector xyz)
void SetTrackID (G4int i)
G4int GetTrackID () const
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
Private Attributes
G4double fEdep
G4ThreeVector fPos
G4int fTrackID
Detailed Description
Definition at line 43 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 43 of file RE01TrackerHit.hh
Constructor & Destructor Documentation
RE01TrackerHit::RE01TrackerHit ()
Definition at line 47 of file RE01TrackerHit.cc.
View newest version in sPHENIX GitHub at line 47 of file RE01TrackerHit.cc
RE01TrackerHit::~RE01TrackerHit () virtual
Definition at line 52 of file RE01TrackerHit.cc.
View newest version in sPHENIX GitHub at line 52 of file RE01TrackerHit.cc
Member Function Documentation
std::vector< G4AttValue > * RE01TrackerHit::CreateAttValues () const virtual
Reimplemented from G4VHit.
Definition at line 100 of file RE01TrackerHit.cc.
View newest version in sPHENIX GitHub at line 100 of file RE01TrackerHit.cc
References G4UIcommand::ConvertToString(), fEdep, fPos, fTrackID, G4BestUnit, MeV, and Acts::Test::values.
void RE01TrackerHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 56 of file RE01TrackerHit.cc.
View newest version in sPHENIX GitHub at line 56 of file RE01TrackerHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, fPos, G4VVisManager::GetConcreteInstance(), G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
const std::map< G4String, G4AttDef > * RE01TrackerHit::GetAttDefs () const virtual
Reimplemented from G4VHit.
Definition at line 72 of file RE01TrackerHit.cc.
View newest version in sPHENIX GitHub at line 72 of file RE01TrackerHit.cc
References energy, G4AttDefStore::GetInstance(), and pos().
G4double RE01TrackerHit::GetEdep () const inline
Definition at line 61 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 61 of file RE01TrackerHit.hh
References fEdep.
G4int RE01TrackerHit::GetTrackID () const inline
Definition at line 67 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 67 of file RE01TrackerHit.hh
References fTrackID.
void RE01TrackerHit::operator delete (void * aHit) inline
Definition at line 88 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 88 of file RE01TrackerHit.hh
References RE01TrackerHitAllocator.
void * RE01TrackerHit::operator new (size_t) inline
Definition at line 81 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 81 of file RE01TrackerHit.hh
References RE01TrackerHitAllocator.
void RE01TrackerHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 123 of file RE01TrackerHit.cc.
View newest version in sPHENIX GitHub at line 123 of file RE01TrackerHit.cc
References fEdep, fPos, fTrackID, G4cout, G4endl, and keV.
void RE01TrackerHit::SetEdep (G4double de) inline
Definition at line 59 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 59 of file RE01TrackerHit.hh
References fEdep.
Referenced by RE01TrackerSD::ProcessHits().
void RE01TrackerHit::SetPos (G4ThreeVector xyz) inline
Definition at line 63 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 63 of file RE01TrackerHit.hh
References fPos.
Referenced by RE01TrackerSD::ProcessHits().
void RE01TrackerHit::SetTrackID (G4int i) inline
Definition at line 65 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 65 of file RE01TrackerHit.hh
References fTrackID.
Referenced by RE01TrackerSD::ProcessHits().
Member Data Documentation
G4double RE01TrackerHit::fEdep private
Definition at line 71 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 71 of file RE01TrackerHit.hh
Referenced by CreateAttValues(), GetEdep(), Print(), and SetEdep().
G4ThreeVector RE01TrackerHit::fPos private
Definition at line 72 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 72 of file RE01TrackerHit.hh
Referenced by CreateAttValues(), Draw(), Print(), and SetPos().
G4int RE01TrackerHit::fTrackID private
Definition at line 73 of file RE01TrackerHit.hh.
View newest version in sPHENIX GitHub at line 73 of file RE01TrackerHit.hh
Referenced by CreateAttValues(), GetTrackID(), Print(), and SetTrackID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01TrackerHit.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01TrackerHit.cc