ECCE @ EIC Software: G4AtimaFluctuations Class Reference
G4AtimaFluctuations Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4AtimaFluctuations.hh>
Public Member Functions
G4AtimaFluctuations (const G4String &nam="IonFlucAtima")
virtual ~G4AtimaFluctuations ()
virtual G4double SampleFluctuations (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmax, G4double length, G4double meanLoss) override
virtual G4double Dispersion (const G4Material *, const G4DynamicParticle *, G4double tmax, G4double length) override
virtual void InitialiseMe (const G4ParticleDefinition *) override
virtual void SetParticleAndCharge (const G4ParticleDefinition *, G4double q2) override
Public Member Functions inherited from G4VEmFluctuationModel
G4VEmFluctuationModel (const G4String &nam)
virtual ~G4VEmFluctuationModel ()
const G4String & GetName () const
Private Member Functions
G4double EnergyTable_interpolate (const G4double *table, G4double xval, const G4double *y)
G4AtimaFluctuations & operator= (const G4AtimaFluctuations &right)=delete
G4AtimaFluctuations (const G4AtimaFluctuations &)=delete
Private Attributes
G4UniversalFluctuation uniFluct
const G4ParticleDefinition * particle
G4Pow * g4calc
G4double particleMass
G4double charge
G4double chargeSquare
G4double effChargeSquare
G4double MLN10
G4double atomic_mass_unit
G4double dedx_constant
G4double electron_mass
G4double fine_structure
G4double domega2dx_constant
G4double minLoss
G4double kineticEnergy
G4double beta2
Static Private Attributes
static G4double stepE = 0.0
static G4double tableE [200] = {0.0}
static const G4double ls_X_coefficients_a [110][200]
static const G4double ls_X_coefficients_ahi [110][200]
static const G4double element_atomic_weights [110]
Detailed Description
Definition at line 58 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 58 of file G4AtimaFluctuations.hh
Constructor & Destructor Documentation
G4AtimaFluctuations::G4AtimaFluctuations (const G4String & nam = "IonFlucAtima") explicit
Definition at line 74 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 74 of file G4AtimaFluctuations.cc
References atomic_mass_unit, beta2, dedx_constant, domega2dx_constant, electron_mass, fine_structure, g4calc, G4Exp(), G4Pow::GetInstance(), kineticEnergy, MLN10, stepE, and tableE.
G4AtimaFluctuations::~G4AtimaFluctuations () virtual
Definition at line 104 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 104 of file G4AtimaFluctuations.cc
G4AtimaFluctuations::G4AtimaFluctuations (const G4AtimaFluctuations &) private delete
Member Function Documentation
G4double G4AtimaFluctuations::Dispersion (const G4Material * mat, const G4DynamicParticle * dp, G4double tmax, G4double length) override virtual
Implements G4VEmFluctuationModel.
Definition at line 146 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 146 of file G4AtimaFluctuations.cc
References G4InuclParticleNames::ap, Acts::Test::at, atomic_mass_unit, beta2, cm, cm3, domega2dx_constant, e6, electron_mass, element_atomic_weights, EnergyTable_interpolate(), f, fine_structure, Acts::UnitConstants::g, g4calc, G4Exp(), G4Log(), G4lrint(), G4NistManager::GetAtomicMassAmu(), G4DynamicParticle::GetDefinition(), G4Material::GetDensity(), G4Material::GetIonisation(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4IonisParamMat::GetZeffective(), G4NistManager::Instance(), kineticEnergy, ls_X_coefficients_a, ls_X_coefficients_ahi, max, min, G4Pow::powA(), tableE, v3, v4, X, z, and G4Pow::Z23().
Referenced by SampleFluctuations().
G4double G4AtimaFluctuations::EnergyTable_interpolate (const G4double * table, G4double xval, const G4double * y) private
Definition at line 216 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 216 of file G4AtimaFluctuations.cc
References G4Log(), max, min, MLN10, num, r, stepE, and x.
Referenced by Dispersion().
void G4AtimaFluctuations::InitialiseMe (const G4ParticleDefinition * part) override virtual
Reimplemented from G4VEmFluctuationModel.
Definition at line 109 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 109 of file G4AtimaFluctuations.cc
References charge, chargeSquare, effChargeSquare, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4UniversalFluctuation::InitialiseMe(), part, particle, particleMass, and uniFluct.
G4AtimaFluctuations& G4AtimaFluctuations::operator= (const G4AtimaFluctuations & right) private delete
G4double G4AtimaFluctuations::SampleFluctuations (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmax, G4double length, G4double meanLoss) override virtual
Implements G4VEmFluctuationModel.
Definition at line 122 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 122 of file G4AtimaFluctuations.cc
References Dispersion(), G4MaterialCutsCouple::GetMaterial(), material(), minLoss, and G4INCL::DeJongSpin::shoot().
void G4AtimaFluctuations::SetParticleAndCharge (const G4ParticleDefinition * part, G4double q2) override virtual
Reimplemented from G4VEmFluctuationModel.
Definition at line 201 of file G4AtimaFluctuations.cc.
View newest version in sPHENIX GitHub at line 201 of file G4AtimaFluctuations.cc
References charge, chargeSquare, effChargeSquare, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), part, particle, particleMass, G4UniversalFluctuation::SetParticleAndCharge(), and uniFluct.
Member Data Documentation
G4double G4AtimaFluctuations::atomic_mass_unit private
Definition at line 106 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
G4double G4AtimaFluctuations::beta2 private
Definition at line 122 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 122 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
G4double G4AtimaFluctuations::charge private
Definition at line 101 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AtimaFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
G4double G4AtimaFluctuations::chargeSquare private
Definition at line 102 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AtimaFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
G4double G4AtimaFluctuations::dedx_constant private
Definition at line 107 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AtimaFluctuations.hh
Referenced by G4AtimaFluctuations().
G4double G4AtimaFluctuations::domega2dx_constant private
Definition at line 110 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
G4double G4AtimaFluctuations::effChargeSquare private
Definition at line 103 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AtimaFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
G4double G4AtimaFluctuations::electron_mass private
Definition at line 108 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
const G4double G4AtimaFluctuations::element_atomic_weights static private
Definition at line 116 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AtimaFluctuations.hh
Referenced by Dispersion().
G4double G4AtimaFluctuations::fine_structure private
Definition at line 109 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
G4Pow* G4AtimaFluctuations::g4calc private
Definition at line 98 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
G4double G4AtimaFluctuations::kineticEnergy private
Definition at line 121 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 121 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
const G4double G4AtimaFluctuations::ls_X_coefficients_a static private
Definition at line 114 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AtimaFluctuations.hh
Referenced by Dispersion().
const G4double G4AtimaFluctuations::ls_X_coefficients_ahi static private
Definition at line 115 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AtimaFluctuations.hh
Referenced by Dispersion().
G4double G4AtimaFluctuations::minLoss private
Definition at line 119 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 119 of file G4AtimaFluctuations.hh
Referenced by SampleFluctuations().
G4double G4AtimaFluctuations::MLN10 private
Definition at line 105 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AtimaFluctuations.hh
Referenced by EnergyTable_interpolate(), and G4AtimaFluctuations().
const G4ParticleDefinition* G4AtimaFluctuations::particle private
Definition at line 96 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AtimaFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
G4double G4AtimaFluctuations::particleMass private
Definition at line 100 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AtimaFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
G4double G4AtimaFluctuations::stepE = 0.0 static private
Definition at line 112 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AtimaFluctuations.hh
Referenced by EnergyTable_interpolate(), and G4AtimaFluctuations().
G4double G4AtimaFluctuations::tableE = {0.0} static private
Definition at line 113 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AtimaFluctuations.hh
Referenced by Dispersion(), and G4AtimaFluctuations().
G4UniversalFluctuation G4AtimaFluctuations::uniFluct private
Definition at line 95 of file G4AtimaFluctuations.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AtimaFluctuations.hh
Referenced by InitialiseMe(), and SetParticleAndCharge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4AtimaFluctuations.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4AtimaFluctuations.cc