ECCE @ EIC Software: CLHEP::MTwistEngine Class Reference
CLHEP::MTwistEngine Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/MTwistEngine.h>
Public Member Functions
MTwistEngine ()
MTwistEngine (long seed)
MTwistEngine (int rowIndex, int colIndex)
MTwistEngine (std::istream &is)
virtual ~MTwistEngine ()
double flat ()
void flatArray (const int size, double *vect)
void setSeed (long seed, int)
void setSeeds (const long *seeds, int)
void saveStatus (const char filename[]="MTwist.conf") const
void restoreStatus (const char filename[]="MTwist.conf")
void showStatus () const
operator double ()
operator float ()
operator unsigned int ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Public Attributes
static const unsigned int VECTOR_STATE_SIZE = 626
Private Types
enum { NminusM = 227, M = 397, N = 624 }
Private Attributes
unsigned int mt [624]
int count624
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Definition at line 34 of file MTwistEngine.h.
View newest version in sPHENIX GitHub at line 34 of file MTwistEngine.h
Member Enumeration Documentation
anonymous enum private
Enumerator:
NminusM
M
N
Definition at line 90 of file MTwistEngine.h.
View newest version in sPHENIX GitHub at line 90 of file MTwistEngine.h
Constructor & Destructor Documentation
CLHEP::MTwistEngine::MTwistEngine ()
Definition at line 63 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 63 of file MTwistEngine.cc
References kdfinder::abs(), count624, flat(), CLHEP::HepRandom::getTheTableSeeds(), mask, and setSeeds().
CLHEP::MTwistEngine::MTwistEngine (long seed)
Definition at line 80 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 80 of file MTwistEngine.cc
References count624, flat(), seed, and setSeeds().
CLHEP::MTwistEngine::MTwistEngine (int rowIndex, int colIndex)
Definition at line 89 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 89 of file MTwistEngine.cc
References kdfinder::abs(), col, count624, flat(), CLHEP::HepRandom::getTheTableSeeds(), mask, and setSeeds().
CLHEP::MTwistEngine::MTwistEngine (std::istream & is)
Definition at line 105 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 105 of file MTwistEngine.cc
CLHEP::MTwistEngine::~MTwistEngine () virtual
Definition at line 111 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 111 of file MTwistEngine.cc
Member Function Documentation
std::string CLHEP::MTwistEngine::beginTag () static
Definition at line 343 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 343 of file MTwistEngine.cc
static std::string CLHEP::MTwistEngine::engineName () inline static
Definition at line 77 of file MTwistEngine.h.
View newest version in sPHENIX GitHub at line 77 of file MTwistEngine.h
Referenced by restoreStatus().
double CLHEP::MTwistEngine::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 113 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 113 of file MTwistEngine.cc
References count624, M, mt, N, CLHEP::HepRandomEngine::nearlyTwoToMinus_54(), NminusM, CLHEP::HepRandomEngine::twoToMinus_32(), CLHEP::HepRandomEngine::twoToMinus_53(), x1, and y.
Referenced by flatArray(), and MTwistEngine().
void CLHEP::MTwistEngine::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 146 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 146 of file MTwistEngine.cc
References flat().
std::istream & CLHEP::MTwistEngine::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 325 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 325 of file MTwistEngine.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::MTwistEngine::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 365 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 365 of file MTwistEngine.cc
References getState().
std::istream & CLHEP::MTwistEngine::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 347 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 347 of file MTwistEngine.cc
References count624, CLHEP::MarkerLen, mt, and CLHEP::HepRandomEngine::theSeed.
Referenced by get().
bool CLHEP::MTwistEngine::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 374 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 374 of file MTwistEngine.cc
References count624, mt, and VECTOR_STATE_SIZE.
std::string CLHEP::MTwistEngine::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 61 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 61 of file MTwistEngine.cc
CLHEP::MTwistEngine::operator double () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 232 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 232 of file MTwistEngine.cc
References G4AblaRandom::flat().
CLHEP::MTwistEngine::operator float () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 236 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 236 of file MTwistEngine.cc
References N, x1, and y.
CLHEP::MTwistEngine::operator unsigned int () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 267 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 267 of file MTwistEngine.cc
References N, x1, and y.
std::ostream & CLHEP::MTwistEngine::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 298 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 298 of file MTwistEngine.cc
References count624, mt, gammaraytel::pr, and CLHEP::HepRandomEngine::theSeed.
std::vector< unsigned long > CLHEP::MTwistEngine::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 315 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 315 of file MTwistEngine.cc
References count624, mt, and v.
void CLHEP::MTwistEngine::restoreStatus (const char filename[] = "MTwist.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 198 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 198 of file MTwistEngine.cc
References CLHEP::HepRandomEngine::checkFile(), count624, engineName(), in, mt, and CLHEP::HepRandomEngine::theSeed.
void CLHEP::MTwistEngine::saveStatus (const char filename[] = "MTwist.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 187 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 187 of file MTwistEngine.cc
References count624, mt, and CLHEP::HepRandomEngine::theSeed.
void CLHEP::MTwistEngine::setSeed (long seed, int k) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 150 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 150 of file MTwistEngine.cc
References int(), k, mt, and CLHEP::HepRandomEngine::theSeed.
Referenced by setSeeds().
void CLHEP::MTwistEngine::setSeeds (const long * seeds, int k) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 178 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 178 of file MTwistEngine.cc
References mt, setSeed(), and CLHEP::HepRandomEngine::theSeeds.
Referenced by MTwistEngine().
void CLHEP::MTwistEngine::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 213 of file MTwistEngine.cc.
View newest version in sPHENIX GitHub at line 213 of file MTwistEngine.cc
References count624, mt, and CLHEP::HepRandomEngine::theSeed.
Member Data Documentation
int CLHEP::MTwistEngine::count624 private
Definition at line 88 of file MTwistEngine.h.
View newest version in sPHENIX GitHub at line 88 of file MTwistEngine.h
Referenced by flat(), getState(), MTwistEngine(), put(), restoreStatus(), saveStatus(), and showStatus().
unsigned int CLHEP::MTwistEngine::mt[624] private
Definition at line 87 of file MTwistEngine.h.
View newest version in sPHENIX GitHub at line 87 of file MTwistEngine.h
Referenced by flat(), getState(), put(), restoreStatus(), saveStatus(), setSeed(), setSeeds(), and showStatus().
const unsigned int CLHEP::MTwistEngine::VECTOR_STATE_SIZE = 626 static
Definition at line 83 of file MTwistEngine.h.
View newest version in sPHENIX GitHub at line 83 of file MTwistEngine.h
Referenced by getState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/MTwistEngine.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/MTwistEngine.cc