ECCE @ EIC Software: G4ParticlePropertyTable Class Reference
G4ParticlePropertyTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticlePropertyTable.hh>
Public Member Functions
G4bool operator== (const G4ParticlePropertyTable &right) const
G4bool operator!= (const G4ParticlePropertyTable &right) const
virtual ~G4ParticlePropertyTable ()
G4ParticlePropertyData * GetParticleProperty (const G4String &aParticleName)
G4ParticlePropertyData * GetParticleProperty (const G4ParticleDefinition *aParticle)
G4bool SetParticleProperty (const G4ParticlePropertyData &newProperty)
void Clear ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Static Public Member Functions
static G4ParticlePropertyTable * GetParticlePropertyTable ()
Protected Member Functions
G4ParticlePropertyTable ()
G4ParticlePropertyTable (const G4ParticlePropertyTable &right)
G4ParticlePropertyTable & operator= (const G4ParticlePropertyTable &right)
Protected Attributes
G4ParticleTable * fParticleTable
std::vector
< G4ParticlePropertyData * > arrayDataObject
Private Attributes
G4int verboseLevel
Static Private Attributes
static G4ThreadLocal
G4ParticlePropertyTable * fgParticlePropertyTable = nullptr
Detailed Description
Definition at line 47 of file G4ParticlePropertyTable.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticlePropertyTable.hh
Constructor & Destructor Documentation
G4ParticlePropertyTable::G4ParticlePropertyTable () protected
Definition at line 64 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ParticlePropertyTable.cc
References fParticleTable, and G4ParticleTable::GetParticleTable().
Referenced by GetParticlePropertyTable().
G4ParticlePropertyTable::G4ParticlePropertyTable (const G4ParticlePropertyTable & right) protected
Definition at line 71 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ParticlePropertyTable.cc
References fParticleTable, G4ParticleTable::GetParticleTable(), and right.
G4ParticlePropertyTable::~G4ParticlePropertyTable () virtual
Definition at line 55 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ParticlePropertyTable.cc
References arrayDataObject, and incremental_prev_tag::idx.
Member Function Documentation
void G4ParticlePropertyTable::Clear ()
Definition at line 100 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ParticlePropertyTable.cc
References arrayDataObject, and incremental_prev_tag::idx.
Referenced by G4VParticlePropertyReporter::~G4VParticlePropertyReporter(), and G4VParticlePropertyRetriever::~G4VParticlePropertyRetriever().
G4ParticlePropertyData * G4ParticlePropertyTable::GetParticleProperty (const G4String & aParticleName)
Definition at line 109 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 109 of file G4ParticlePropertyTable.cc
References G4ParticleTable::FindParticle(), and fParticleTable.
Referenced by G4VParticlePropertyReporter::FillList(), and G4TextPPRetriever::ModifyPropertyTable().
G4ParticlePropertyData * G4ParticlePropertyTable::GetParticleProperty (const G4ParticleDefinition * aParticle)
Definition at line 118 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ParticlePropertyTable.cc
References arrayDataObject, G4ParticleDefinition::GetAntiPDGEncoding(), G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetLeptonNumber(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGiConjugation(), G4ParticleDefinition::GetPDGiGParity(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), G4ParticlePropertyData::NumberOfQuarkFlavor, G4ParticlePropertyData::theAntiPDGEncoding, G4ParticlePropertyData::theAntiQuarkContent, G4ParticleDefinition::theAntiQuarkContent, G4ParticlePropertyData::theBaryonNumber, G4ParticlePropertyData::theLeptonNumber, G4ParticlePropertyData::thePDGCharge, G4ParticlePropertyData::thePDGEncoding, G4ParticlePropertyData::thePDGiConjugation, G4ParticlePropertyData::thePDGiGParity, G4ParticlePropertyData::thePDGiIsospin, G4ParticlePropertyData::thePDGiIsospin3, G4ParticlePropertyData::thePDGiParity, G4ParticlePropertyData::thePDGiSpin, G4ParticlePropertyData::thePDGLifeTime, G4ParticlePropertyData::thePDGMagneticMoment, G4ParticlePropertyData::thePDGMass, G4ParticlePropertyData::thePDGWidth, G4ParticlePropertyData::theQuarkContent, and G4ParticleDefinition::theQuarkContent.
G4ParticlePropertyTable * G4ParticlePropertyTable::GetParticlePropertyTable () static
Definition at line 45 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ParticlePropertyTable.cc
References fgParticlePropertyTable, and G4ParticlePropertyTable().
Referenced by G4VParticlePropertyReporter::G4VParticlePropertyReporter(), and G4VParticlePropertyRetriever::G4VParticlePropertyRetriever().
G4int G4ParticlePropertyTable::GetVerboseLevel () const
G4bool G4ParticlePropertyTable::operator!= (const G4ParticlePropertyTable & right) const
Definition at line 94 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 94 of file G4ParticlePropertyTable.cc
G4ParticlePropertyTable & G4ParticlePropertyTable::operator= (const G4ParticlePropertyTable & right) protected
Definition at line 78 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ParticlePropertyTable.cc
References fParticleTable, and verboseLevel.
G4bool G4ParticlePropertyTable::operator== (const G4ParticlePropertyTable & right) const
Definition at line 88 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ParticlePropertyTable.cc
G4bool G4ParticlePropertyTable::SetParticleProperty (const G4ParticlePropertyData & newProperty)
Definition at line 148 of file G4ParticlePropertyTable.cc.
View newest version in sPHENIX GitHub at line 148 of file G4ParticlePropertyTable.cc
References G4ParticlePropertyData::fAntiPDGEncodingModified, G4ParticlePropertyData::fAntiQuarkContentModified, G4ParticlePropertyData::fBaryonNumberModified, G4ParticleTable::FindParticle(), G4ParticlePropertyData::fLeptonNumberModified, fParticleTable, G4ParticlePropertyData::fPDGChargeModified, G4ParticlePropertyData::fPDGEncodingModified, G4ParticlePropertyData::fPDGiConjugationModified, G4ParticlePropertyData::fPDGiGParityModified, G4ParticlePropertyData::fPDGiIsospin3Modified, G4ParticlePropertyData::fPDGiIsospinModified, G4ParticlePropertyData::fPDGiParityModified, G4ParticlePropertyData::fPDGiSpinModified, G4ParticlePropertyData::fPDGLifeTimeModified, G4ParticlePropertyData::fPDGMagneticMomentModified, G4ParticlePropertyData::fPDGMassModified, G4ParticlePropertyData::fPDGWidthModified, G4ParticlePropertyData::fQuarkContentModified, G4cout, G4endl, G4State_PreInit, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4ParticlePropertyData::NumberOfQuarkFlavor, G4ParticlePropertyData::theAntiPDGEncoding, G4ParticleDefinition::theAntiPDGEncoding, G4ParticlePropertyData::theAntiQuarkContent, G4ParticleDefinition::theAntiQuarkContent, G4ParticlePropertyData::theBaryonNumber, G4ParticleDefinition::theBaryonNumber, G4ParticlePropertyData::theLeptonNumber, G4ParticleDefinition::theLeptonNumber, G4ParticlePropertyData::theParticleName, G4ParticlePropertyData::thePDGCharge, G4ParticleDefinition::thePDGCharge, G4ParticlePropertyData::thePDGEncoding, G4ParticleDefinition::thePDGEncoding, G4ParticlePropertyData::thePDGiConjugation, G4ParticleDefinition::thePDGiConjugation, G4ParticlePropertyData::thePDGiGParity, G4ParticleDefinition::thePDGiGParity, G4ParticlePropertyData::thePDGiIsospin, G4ParticleDefinition::thePDGiIsospin, G4ParticlePropertyData::thePDGiIsospin3, G4ParticleDefinition::thePDGiIsospin3, G4ParticlePropertyData::thePDGiParity, G4ParticleDefinition::thePDGiParity, G4ParticleDefinition::thePDGIsospin, G4ParticleDefinition::thePDGIsospin3, G4ParticlePropertyData::thePDGiSpin, G4ParticleDefinition::thePDGiSpin, G4ParticlePropertyData::thePDGLifeTime, G4ParticleDefinition::thePDGLifeTime, G4ParticlePropertyData::thePDGMagneticMoment, G4ParticleDefinition::thePDGMagneticMoment, G4ParticlePropertyData::thePDGMass, G4ParticleDefinition::thePDGMass, G4ParticleDefinition::thePDGSpin, G4ParticlePropertyData::theQuarkContent, G4ParticleDefinition::theQuarkContent, and verboseLevel.
Referenced by G4TextPPRetriever::ModifyPropertyTable().
void G4ParticlePropertyTable::SetVerboseLevel (G4int value)
Member Data Documentation
std::vector<G4ParticlePropertyData*> G4ParticlePropertyTable::arrayDataObject protected
Definition at line 104 of file G4ParticlePropertyTable.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticlePropertyTable.hh
Referenced by Clear(), GetParticleProperty(), and ~G4ParticlePropertyTable().
G4ThreadLocal G4ParticlePropertyTable * G4ParticlePropertyTable::fgParticlePropertyTable = nullptr static private
Definition at line 101 of file G4ParticlePropertyTable.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticlePropertyTable.hh
Referenced by GetParticlePropertyTable().
G4ParticleTable* G4ParticlePropertyTable::fParticleTable protected
Definition at line 97 of file G4ParticlePropertyTable.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticlePropertyTable.hh
Referenced by G4ParticlePropertyTable(), GetParticleProperty(), operator=(), and SetParticleProperty().
G4int G4ParticlePropertyTable::verboseLevel private
Definition at line 100 of file G4ParticlePropertyTable.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParticlePropertyTable.hh
Referenced by operator=(), and SetParticleProperty().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticlePropertyTable.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4ParticlePropertyTable.cc