ECCE @ EIC Software: G4ChipsNeutronInelasticXS Class Reference
G4ChipsNeutronInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsNeutronInelasticXS.hh>
Public Member Functions
G4ChipsNeutronInelasticXS ()
~G4ChipsNeutronInelasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
virtual G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
G4double CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum)
G4double CrossSectionLin (G4int targZ, G4int targN, G4double P)
G4double CrossSectionLog (G4int targZ, G4int targN, G4double lP)
G4double CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP)
G4double EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double *Y)
Private Attributes
G4double * lastLEN
G4double * lastHEN
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
G4double HEthresh
std::vector< G4double * > * LEN
std::vector< G4double * > * HEN
G4int j
std::vector< G4int > colN
std::vector< G4int > colZ
std::vector< G4double > colP
std::vector< G4double > colTH
std::vector< G4double > colCS
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 45 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ChipsNeutronInelasticXS.hh
Constructor & Destructor Documentation
G4ChipsNeutronInelasticXS::G4ChipsNeutronInelasticXS ()
Definition at line 56 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ChipsNeutronInelasticXS.cc
References HEN, HEthresh, lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, and LEN.
G4ChipsNeutronInelasticXS::~G4ChipsNeutronInelasticXS ()
Definition at line 71 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ChipsNeutronInelasticXS.cc
References HEN, and LEN.
Member Function Documentation
G4double G4ChipsNeutronInelasticXS::CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum) private
Definition at line 182 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 182 of file G4ChipsNeutronInelasticXS.cc
References CrossSectionFormula(), CrossSectionLin(), CrossSectionLog(), EquLinearFit(), G4cerr, G4endl, G4Log(), HEN, k, lastHEN, lastLEN, lastTH, LEN, n, nH, nL, P, and THmin.
Referenced by GetChipsCrossSection().
void G4ChipsNeutronInelasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 82 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ChipsNeutronInelasticXS.cc
G4double G4ChipsNeutronInelasticXS::CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP) private
Definition at line 1257 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 1257 of file G4ChipsNeutronInelasticXS.cc
References a, c, d, e, G4cerr, G4endl, G4Exp(), G4Log(), Acts::UnitConstants::h, HEthresh, LE, P, and r.
Referenced by CalculateCrossSection(), CrossSectionLin(), and CrossSectionLog().
G4double G4ChipsNeutronInelasticXS::CrossSectionLin (G4int targZ, G4int targN, G4double P) private
Definition at line 263 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 263 of file G4ChipsNeutronInelasticXS.cc
References CrossSectionFormula(), G4cerr, G4cout, G4endl, G4Exp(), G4Log(), HEthresh, in, G4InuclParticleNames::nn, pos(), Z1, and Z2.
Referenced by CalculateCrossSection().
G4double G4ChipsNeutronInelasticXS::CrossSectionLog (G4int targZ, G4int targN, G4double lP) private
Definition at line 1251 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 1251 of file G4ChipsNeutronInelasticXS.cc
References CrossSectionFormula(), G4Exp(), and P.
Referenced by CalculateCrossSection().
static const char* G4ChipsNeutronInelasticXS::Default_Name () inline static
Definition at line 55 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ChipsNeutronInelasticXS.hh
Referenced by G4ChipsComponentXS::G4ChipsComponentXS().
G4double G4ChipsNeutronInelasticXS::EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double * Y) private
Definition at line 1340 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 1340 of file G4ChipsNeutronInelasticXS.cc
References d, G4cerr, and G4endl.
Referenced by CalculateCrossSection().
G4double G4ChipsNeutronInelasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg) virtual
!The slave functions must provide cross-sections in millibarns (mb) !! (not in IU)
Definition at line 111 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ChipsNeutronInelasticXS.cc
References CalculateCrossSection(), colCS, colN, colP, colTH, colZ, in, j, lastCS, lastI, lastN, lastP, lastTH, lastZ, and millibarn.
Referenced by GetIsoCrossSection().
G4double G4ChipsNeutronInelasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 98 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ChipsNeutronInelasticXS.cc
References GetChipsCrossSection(), and G4DynamicParticle::GetTotalMomentum().
G4bool G4ChipsNeutronInelasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 90 of file G4ChipsNeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ChipsNeutronInelasticXS.cc
Member Data Documentation
std::vector<G4double> G4ChipsNeutronInelasticXS::colCS private
Definition at line 101 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ChipsNeutronInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsNeutronInelasticXS::colN private
Definition at line 97 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ChipsNeutronInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsNeutronInelasticXS::colP private
Definition at line 99 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ChipsNeutronInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsNeutronInelasticXS::colTH private
Definition at line 100 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ChipsNeutronInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsNeutronInelasticXS::colZ private
Definition at line 98 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ChipsNeutronInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double*>* G4ChipsNeutronInelasticXS::HEN private
Definition at line 94 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChipsNeutronInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsNeutronInelasticXS(), and ~G4ChipsNeutronInelasticXS().
G4double G4ChipsNeutronInelasticXS::HEthresh private
Definition at line 92 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsNeutronInelasticXS.hh
Referenced by CrossSectionFormula(), CrossSectionLin(), and G4ChipsNeutronInelasticXS().
G4int G4ChipsNeutronInelasticXS::j private
Definition at line 96 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChipsNeutronInelasticXS.hh
Referenced by GetChipsCrossSection().
G4double G4ChipsNeutronInelasticXS::lastCS private
Definition at line 90 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ChipsNeutronInelasticXS.hh
Referenced by G4ChipsNeutronInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsNeutronInelasticXS::lastHEN private
Definition at line 85 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsNeutronInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsNeutronInelasticXS().
G4int G4ChipsNeutronInelasticXS::lastI private
Definition at line 91 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ChipsNeutronInelasticXS.hh
Referenced by G4ChipsNeutronInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsNeutronInelasticXS::lastLEN private
Definition at line 84 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsNeutronInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsNeutronInelasticXS().
G4int G4ChipsNeutronInelasticXS::lastN private
Definition at line 86 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsNeutronInelasticXS.hh
Referenced by G4ChipsNeutronInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsNeutronInelasticXS::lastP private
Definition at line 88 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsNeutronInelasticXS.hh
Referenced by G4ChipsNeutronInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsNeutronInelasticXS::lastTH private
Definition at line 89 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChipsNeutronInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsNeutronInelasticXS(), and GetChipsCrossSection().
G4int G4ChipsNeutronInelasticXS::lastZ private
Definition at line 87 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsNeutronInelasticXS.hh
Referenced by G4ChipsNeutronInelasticXS(), and GetChipsCrossSection().
std::vector<G4double*>* G4ChipsNeutronInelasticXS::LEN private
Definition at line 93 of file G4ChipsNeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChipsNeutronInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsNeutronInelasticXS(), and ~G4ChipsNeutronInelasticXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsNeutronInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsNeutronInelasticXS.cc