ECCE @ EIC Software: G4VEmAngularDistribution Class Reference
G4VEmAngularDistribution Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmAngularDistribution.hh>
Public Member Functions
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, const G4Material *)=0
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Protected Attributes
G4ThreeVector fLocalDirection
Private Member Functions
G4VEmAngularDistribution & operator= (const G4VEmAngularDistribution &right)=delete
G4VEmAngularDistribution (const G4VEmAngularDistribution &)=delete
Private Attributes
G4String fName
Detailed Description
Definition at line 59 of file G4VEmAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VEmAngularDistribution.hh
Constructor & Destructor Documentation
G4VEmAngularDistribution::G4VEmAngularDistribution (const G4String & name) explicit
Definition at line 54 of file G4VEmAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VEmAngularDistribution.cc
G4VEmAngularDistribution::~G4VEmAngularDistribution () virtual
Definition at line 60 of file G4VEmAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VEmAngularDistribution.cc
G4VEmAngularDistribution::G4VEmAngularDistribution (const G4VEmAngularDistribution &) private delete
Member Function Documentation
const G4String & G4VEmAngularDistribution::GetName (void) const inline
Definition at line 109 of file G4VEmAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VEmAngularDistribution.hh
References fName.
Referenced by G4EmModelManager::DumpModelList().
G4VEmAngularDistribution& G4VEmAngularDistribution::operator= (const G4VEmAngularDistribution & right) private delete
virtual G4ThreeVector& G4VEmAngularDistribution::SampleDirection (const G4DynamicParticle * dp, G4double finalTotalEnergy, G4int Z, const G4Material *) pure virtual
Implemented in G4Generator2BS, G4Generator2BN, G4PenelopeBremsstrahlungAngular, G4ModifiedTsai, G4RayleighAngularGenerator, G4PhotoElectricAngularGeneratorSauterGavrila, G4DNABornAngle, G4DNARuddAngle, G4AngleDirect, G4PhotoElectricAngularGeneratorSimple, G4DeltaAngle, G4SauterGavrilaAngularDistribution, G4DeltaAngleFreeScat, G4DipBustGenerator, and G4PhotoElectricAngularGeneratorPolarized.
Referenced by G4SynchrotronRadiation::PostStepDoIt(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), SampleDirectionForShell(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), and G4BetheBlochModel::SampleSecondaries().
G4ThreeVector & G4VEmAngularDistribution::SampleDirectionForShell (const G4DynamicParticle * dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material * mat) virtual
Reimplemented in G4DNABornAngle, G4DNARuddAngle, and G4DeltaAngle.
Definition at line 65 of file G4VEmAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VEmAngularDistribution.cc
References SampleDirection().
Referenced by G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), and G4MicroElecInelasticModel::SampleSecondaries().
void G4VEmAngularDistribution::SamplePairDirections (const G4DynamicParticle * dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector & dirElectron, G4ThreeVector & dirPositron, G4int Z = 0, const G4Material * mat = nullptr) virtual
Reimplemented in G4ModifiedTsai, and G4DipBustGenerator.
Definition at line 76 of file G4VEmAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VEmAngularDistribution.cc
References G4DynamicParticle::GetMomentumDirection().
Referenced by G4BetheHeitlerModel::SampleSecondaries(), and G4PairProductionRelModel::SampleSecondaries().
Member Data Documentation
G4ThreeVector G4VEmAngularDistribution::fLocalDirection protected
Definition at line 97 of file G4VEmAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 97 of file G4VEmAngularDistribution.hh
Referenced by G4PhotoElectricAngularGeneratorPolarized::SampleDirection(), G4DeltaAngleFreeScat::SampleDirection(), G4DipBustGenerator::SampleDirection(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4PhotoElectricAngularGeneratorSimple::SampleDirection(), G4DeltaAngle::SampleDirection(), G4AngleDirect::SampleDirection(), G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4Generator2BN::SampleDirection(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4ModifiedTsai::SampleDirection(), G4Generator2BS::SampleDirection(), G4DNABornAngle::SampleDirectionForShell(), and G4DNARuddAngle::SampleDirectionForShell().
G4String G4VEmAngularDistribution::fName private
Definition at line 106 of file G4VEmAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VEmAngularDistribution.hh
Referenced by GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VEmAngularDistribution.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4VEmAngularDistribution.cc