ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/g3routines.F File Reference
g3routines.F File Reference
#include "G3toG4.inc"
Macros
#define CALL_GEANT
Functions/Subroutines
subroutine ksvolu (name, shape, nmed, par, npar, ivol)
subroutine kspos (name, num, moth, x, y, z, irot, only)
subroutine ksposp (name, num, moth, x, y, z, irot, only, par, npar)
subroutine ksatt (name, attr, ival)
subroutine ksrotm (irot, theta1, phi1, theta2, phi2, theta3, phi3)
subroutine ksdvn (name, moth, ndiv, iaxis)
subroutine ksdvt (name, moth, step, iaxis, numed, ndvmx)
subroutine ksdvx (name, moth, ndiv, iaxis, step, c0, numed, ndvmx)
subroutine ksdvn2 (name, moth, ndiv, iaxis, c0, numed)
subroutine ksdvt2 (name, moth, step, iaxis, c0, numed, ndvmx)
subroutine ksmate (imate, name, a, z, dens, radl, absl, ubf, nwbf)
subroutine ksmixt (imate, name, a, z, dens, nlmat, wmat)
subroutine kstmed (itmed, name, nmat, isvol, ifield, fieldm, tmaxfd, stemax, deemax, epsil, stmin, ubuf, nwbuf)
subroutine kstpar (itmed, chpar, parval)
subroutine kspart (ipart, chpar, itrtyp, amass, charge, tlife, ub, nwb)
subroutine ksdk (ipart, bratio, mode)
subroutine ksdet (chset, chdet, nv, chnam, nbits, idtyp, nwhi, nwdi, iset, idet)
subroutine ksdetv (chset, chdet, idtyp, nwhi, nwdi, iset, idet)
subroutine ksdeta (chset, chdet, chali, nwhi, nwdi, iali)
subroutine ksdeth (chset, chdet, nh, chnam, nbits, orig, fact)
subroutine ksdetd (chset, chdet, nd, chnam, nbits)
subroutine ksdetu (chset, chdet, nupar, upar)
subroutine kgclos
subroutine checkshape (name, shape, par, npar)
Macro Definition Documentation
#define CALL_GEANT
Function/Subroutine Documentation
subroutine checkshape (character name, character shape, real, dimension(*) par, integer npar)
Definition at line 949 of file g3routines.F.
View newest version in sPHENIX GitHub at line 949 of file g3routines.F
References print(), c2_factory< float_type >::sqrt(), and CLHEP::HepBoost::tt().
Referenced by ksvolu().
subroutine kgclos ()
Definition at line 923 of file g3routines.F.
View newest version in sPHENIX GitHub at line 923 of file g3routines.F
References check_lines(), and g3main().
Referenced by tog4().
subroutine ksatt (character name, character attr, integer ival)
Definition at line 168 of file g3routines.F.
View newest version in sPHENIX GitHub at line 168 of file g3routines.F
References a, and check_lines().
subroutine ksdet (character chset, character chdet, integer nv, character, dimension(nv) chnam, integer, dimension(nv) nbits, integer idtyp, integer nwhi, integer nwdi, integer iset, integer idet)
Definition at line 689 of file g3routines.F.
View newest version in sPHENIX GitHub at line 689 of file g3routines.F
References a, aitocp(), astocp(), check_lines(), k, and max.
Referenced by tog4().
subroutine ksdeta (character chset, character chdet, character chali, integer nwhi, integer nwdi, integer iali)
Definition at line 765 of file g3routines.F.
View newest version in sPHENIX GitHub at line 765 of file g3routines.F
References a, and check_lines().
subroutine ksdetd (character chset, character chdet, integer nd, character, dimension(nd) chnam, integer, dimension(nd) nbits)
Definition at line 844 of file g3routines.F.
View newest version in sPHENIX GitHub at line 844 of file g3routines.F
References a, aitocp(), astocp(), check_lines(), k, and max.
Referenced by tog4().
subroutine ksdeth (character chset, character chdet, integer nh, character, dimension(nh) chnam, integer, dimension(nh) nbits, real, dimension(nh) orig, real, dimension(nh) fact)
Definition at line 797 of file g3routines.F.
View newest version in sPHENIX GitHub at line 797 of file g3routines.F
References a, aitocp(), artocp(), astocp(), check_lines(), k, and max.
Referenced by tog4().
subroutine ksdetu (character chset, character chdet, integer nupar, real, dimension(nupar) upar)
Definition at line 885 of file g3routines.F.
View newest version in sPHENIX GitHub at line 885 of file g3routines.F
References a, check_lines(), g3ldpar(), k, and max.
Referenced by tog4().
subroutine ksdetv (character chset, character chdet, integer idtyp, integer nwhi, integer nwdi, integer iset, integer idet)
Definition at line 732 of file g3routines.F.
View newest version in sPHENIX GitHub at line 732 of file g3routines.F
References a, and check_lines().
subroutine ksdk (integer ipart, real, dimension(6) bratio, integer, dimension(6) mode)
Definition at line 652 of file g3routines.F.
View newest version in sPHENIX GitHub at line 652 of file g3routines.F
References aitocp(), artocp(), check_lines(), and ipart.
Referenced by G4UCNMicroRoughnessHelper::IntIminus(), and G4UCNMicroRoughnessHelper::ProbIminus().
subroutine ksdvn (character name, character moth, integer ndiv, integer iaxis)
Definition at line 243 of file g3routines.F.
View newest version in sPHENIX GitHub at line 243 of file g3routines.F
References a, and check_lines().
subroutine ksdvn2 (character name, character moth, integer ndiv, integer iaxis, real c0, integer numed)
Definition at line 349 of file g3routines.F.
View newest version in sPHENIX GitHub at line 349 of file g3routines.F
References a, check_lines(), and rtocp().
Referenced by tog4().
subroutine ksdvt (character name, character moth, real step, integer iaxis, integer numed, integer ndvmx)
Definition at line 276 of file g3routines.F.
View newest version in sPHENIX GitHub at line 276 of file g3routines.F
References a, check_lines(), and rtocp().
subroutine ksdvt2 (character name, character moth, real step, integer iaxis, real c0, integer numed, integer ndvmx)
Definition at line 384 of file g3routines.F.
View newest version in sPHENIX GitHub at line 384 of file g3routines.F
References a, check_lines(), and rtocp().
subroutine ksdvx (character name, character moth, integer ndiv, integer iaxis, real step, real c0, integer numed, integer ndvmx)
Definition at line 311 of file g3routines.F.
View newest version in sPHENIX GitHub at line 311 of file g3routines.F
References a, check_lines(), and rtocp().
subroutine ksmate (integer imate, character, dimension(*) name, real a, real z, real dens, real radl, real absl, real, dimension(nwbf) ubf, integer nwbf)
Definition at line 420 of file g3routines.F.
View newest version in sPHENIX GitHub at line 420 of file g3routines.F
References a, check_lines(), g3ldpar(), k, max, rtocp(), and z.
Referenced by tog4().
subroutine ksmixt (integer imate, character, dimension(*) name, real, dimension(*) a, real, dimension(*) z, real dens, integer nlmat, real, dimension(*) wmat)
Definition at line 463 of file g3routines.F.
View newest version in sPHENIX GitHub at line 463 of file g3routines.F
References a, artocp(), check_lines(), k, max, rtocp(), and z.
Referenced by tog4().
subroutine kspart (integer ipart, character, dimension(*) chpar, integer itrtyp, real amass, real charge, real tlife, real, dimension(nwb) ub, integer nwb)
Definition at line 604 of file g3routines.F.
View newest version in sPHENIX GitHub at line 604 of file g3routines.F
References a, charge, check_lines(), g3ldpar(), ipart, k, max, and rtocp().
subroutine kspos (character name, integer num, character moth, real x, real y, real z, integer irot, character only)
Definition at line 75 of file g3routines.F.
View newest version in sPHENIX GitHub at line 75 of file g3routines.F
References a, check_lines(), num, rtocp(), x, y, and z.
Referenced by tog4().
subroutine ksposp (character name, integer num, character moth, real x, real y, real z, integer irot, character only, real, dimension(npar) par, integer npar)
Definition at line 112 of file g3routines.F.
View newest version in sPHENIX GitHub at line 112 of file g3routines.F
References a, check_lines(), g3ldpar(), k, max, num, print(), rtocp(), x, y, and z.
Referenced by tog4().
subroutine ksrotm (integer irot, real theta1, real phi1, real theta2, real phi2, real theta3, real phi3)
Definition at line 201 of file g3routines.F.
View newest version in sPHENIX GitHub at line 201 of file g3routines.F
References check_lines(), and rtocp().
Referenced by tog4().
subroutine kstmed (integer itmed, character, dimension(*) name, integer nmat, integer isvol, integer ifield, real fieldm, real tmaxfd, real stemax, real deemax, real epsil, real stmin, real, dimension(nwbuf) ubuf, integer nwbuf)
Definition at line 513 of file g3routines.F.
View newest version in sPHENIX GitHub at line 513 of file g3routines.F
References a, check_lines(), g3ldpar(), k, max, and rtocp().
Referenced by tog4().
subroutine kstpar (integer itmed, character, dimension(*) chpar, real parval)
Definition at line 569 of file g3routines.F.
View newest version in sPHENIX GitHub at line 569 of file g3routines.F
References a, charge, check_lines(), ipart, and x.
subroutine ksvolu (character name, character shape, integer nmed, real, dimension(npar) par, integer npar, integer ivol)
Definition at line 33 of file g3routines.F.
View newest version in sPHENIX GitHub at line 33 of file g3routines.F
References a, check_lines(), checkshape(), g3ldpar(), k, and max.
Referenced by tog4().