ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_kinetics.cc File Reference
MCGIDI_kinetics.cc File Reference
#include <string.h>
#include <cmath>
#include "MCGIDI.h"
Functions
int MCGIDI_kinetics_2BodyReaction (statusMessageReporting *smr, MCGIDI_angular *angular, double K, double mu, double phi, MCGIDI_sampledProductsData *outgoingData)
int MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum (statusMessageReporting *, double beta, double e_kinetic_com, double mu, double phi, double m3cc, double m4cc, MCGIDI_sampledProductsData *outgoingData)
int MCGIDI_kinetics_COM2Lab (statusMessageReporting *smr, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, double masses[3])
Function Documentation
int MCGIDI_kinetics_2BodyReaction (statusMessageReporting * smr, MCGIDI_angular * angular, double K, double mu, double phi, MCGIDI_sampledProductsData * outgoingData)
Definition at line 18 of file MCGIDI_kinetics.cc.
View newest version in sPHENIX GitHub at line 18 of file MCGIDI_kinetics.cc
References e, m2, m3, MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum(), MCGIDI_angular_s::productMass_MeV, MCGIDI_angular_s::projectileMass_MeV, MCGIDI_angular_s::residualMass_MeV, MCGIDI_angular_s::targetMass_MeV, and x.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_kinetics_COM2Lab (statusMessageReporting * smr, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, double masses[3])
Definition at line 105 of file MCGIDI_kinetics.cc.
View newest version in sPHENIX GitHub at line 105 of file MCGIDI_kinetics.cc
References a, b, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_decaySamplingInfo_s::mu, smr_setReportError2, smr_unknownID, xDataTOM_frame_centerOfMass, and xDataTOM_frame_lab.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum (statusMessageReporting * , double beta, double e_kinetic_com, double mu, double phi, double m3cc, double m4cc, MCGIDI_sampledProductsData * outgoingData)
Definition at line 38 of file MCGIDI_kinetics.cc.
View newest version in sPHENIX GitHub at line 38 of file MCGIDI_kinetics.cc
References e, MCGIDI_sampledProductsData_s::isVelocity, MCGIDI_sampledProductsData_s::kineticEnergy, MCGIDI_speedOfLight_cm_sec, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, MCGIDI_sampledProductsData_s::pz_vz, and x.
Referenced by MCGIDI_kinetics_2BodyReaction().