ECCE @ EIC Software: G4LegendrePolynomial Class Reference
G4LegendrePolynomial Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4LegendrePolynomial.hh>
Public Member Functions
G4double GetCoefficient (size_t i, size_t order)
G4double EvalLegendrePoly (G4int order, G4double x)
G4double EvalAssocLegendrePoly (G4int l, G4int m, G4double x, std::map< G4int, std::map< G4int, G4double > > *cache=NULL)
Static Public Member Functions
static size_t GetNCoefficients (size_t order)
Protected Member Functions
void BuildUpToOrder (size_t order)
Protected Attributes
std::vector< std::vector
< G4double > > fCoefficients
Detailed Description
Definition at line 50 of file G4LegendrePolynomial.hh.
View newest version in sPHENIX GitHub at line 50 of file G4LegendrePolynomial.hh
Member Function Documentation
void G4LegendrePolynomial::BuildUpToOrder (size_t order) protected
Definition at line 123 of file G4LegendrePolynomial.cc.
View newest version in sPHENIX GitHub at line 123 of file G4LegendrePolynomial.cc
References G4cout, and G4endl.
G4double G4LegendrePolynomial::EvalAssocLegendrePoly (G4int l, G4int m, G4double x, std::map< G4int, std::map< G4int, G4double > > * cache = NULL)
Definition at line 49 of file G4LegendrePolynomial.cc.
View newest version in sPHENIX GitHub at line 49 of file G4LegendrePolynomial.cc
References G4Pow::factorial(), G4Exp(), G4Log(), G4Pow::GetInstance(), G4Pow::logfactorial(), m, x, and x2.
Referenced by G4PolarizationTransition::GenerateGammaPhi(), and G4PolarizationTransition::SampleGammaTransition().
G4double G4LegendrePolynomial::EvalLegendrePoly (G4int order, G4double x)
Definition at line 43 of file G4LegendrePolynomial.cc.
View newest version in sPHENIX GitHub at line 43 of file G4LegendrePolynomial.cc
G4double G4LegendrePolynomial::GetCoefficient (size_t i, size_t order)
Definition at line 34 of file G4LegendrePolynomial.cc.
View newest version in sPHENIX GitHub at line 34 of file G4LegendrePolynomial.cc
Referenced by G4PolarizationTransition::GenerateGammaCosTheta().
static size_t G4LegendrePolynomial::GetNCoefficients (size_t order) inline static
Definition at line 54 of file G4LegendrePolynomial.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LegendrePolynomial.hh
Referenced by G4PolarizationTransition::GenerateGammaCosTheta().
Member Data Documentation
std::vector< std::vector<G4double> > G4LegendrePolynomial::fCoefficients protected
Definition at line 64 of file G4LegendrePolynomial.hh.
View newest version in sPHENIX GitHub at line 64 of file G4LegendrePolynomial.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4LegendrePolynomial.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4LegendrePolynomial.cc