ECCE @ EIC Software: G4RayShooter Class Reference
G4RayShooter Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4RayShooter.hh>
Public Member Functions
G4RayShooter ()
virtual ~G4RayShooter ()
void Shoot (G4Event *evt, G4ThreeVector vtx, G4ThreeVector direc)
Private Member Functions
void SetInitialValues ()
Private Attributes
G4ParticleDefinition * particle_definition
G4ParticleMomentum particle_momentum_direction
G4double particle_energy
G4ThreeVector particle_position
G4double particle_time
G4ThreeVector particle_polarization
Detailed Description
Definition at line 48 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 48 of file G4RayShooter.hh
Constructor & Destructor Documentation
G4RayShooter::G4RayShooter ()
Definition at line 38 of file G4RayShooter.cc.
View newest version in sPHENIX GitHub at line 38 of file G4RayShooter.cc
References SetInitialValues().
G4RayShooter::~G4RayShooter () virtual
Definition at line 54 of file G4RayShooter.cc.
View newest version in sPHENIX GitHub at line 54 of file G4RayShooter.cc
Member Function Documentation
void G4RayShooter::SetInitialValues () private
Definition at line 43 of file G4RayShooter.cc.
View newest version in sPHENIX GitHub at line 43 of file G4RayShooter.cc
References GeV, particle_definition, particle_energy, particle_momentum_direction, particle_polarization, particle_position, particle_time, and zero.
Referenced by G4RayShooter().
void G4RayShooter::Shoot (G4Event * evt, G4ThreeVector vtx, G4ThreeVector direc)
Definition at line 58 of file G4RayShooter.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RayShooter.cc
References G4Event::AddPrimaryVertex(), FatalException, G4ParticleTable::FindParticle(), G4Exception(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), mass, particle, particle_definition, particle_energy, particle_polarization, particle_time, G4PrimaryParticle::SetKineticEnergy(), G4PrimaryParticle::SetMass(), G4PrimaryParticle::SetMomentumDirection(), G4PrimaryParticle::SetPolarization(), G4PrimaryVertex::SetPrimary(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4TheRayTracer::CreateBitMap(), and G4MaterialScanner::DoScan().
Member Data Documentation
G4ParticleDefinition* G4RayShooter::particle_definition private
Definition at line 64 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RayShooter.hh
Referenced by SetInitialValues(), and Shoot().
G4double G4RayShooter::particle_energy private
Definition at line 66 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RayShooter.hh
Referenced by SetInitialValues(), and Shoot().
G4ParticleMomentum G4RayShooter::particle_momentum_direction private
Definition at line 65 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RayShooter.hh
Referenced by SetInitialValues().
G4ThreeVector G4RayShooter::particle_polarization private
Definition at line 69 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RayShooter.hh
Referenced by SetInitialValues(), and Shoot().
G4ThreeVector G4RayShooter::particle_position private
Definition at line 67 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RayShooter.hh
Referenced by SetInitialValues().
G4double G4RayShooter::particle_time private
Definition at line 68 of file G4RayShooter.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RayShooter.hh
Referenced by SetInitialValues(), and Shoot().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4RayShooter.hh
geant4/tree/geant4-10.6-release/source/event/src/G4RayShooter.cc