ECCE @ EIC Software: G4PolarizedPEEffectModel Class Reference
G4PolarizedPEEffectModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedPEEffectModel.hh>
Public Member Functions
G4PolarizedPEEffectModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="Polarized-PhotoElectric")
void Initialise (const G4ParticleDefinition *pd, const G4DataVector &dv) override
virtual ~G4PolarizedPEEffectModel ()
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
Public Member Functions inherited from G4PEEffectFluoModel
G4PEEffectFluoModel (const G4String &nam="PhotoElectric")
virtual ~G4PEEffectFluoModel ()
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A, G4double, G4double) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
G4PolarizedPEEffectModel & operator= (const G4PolarizedPEEffectModel &right)=delete
G4PolarizedPEEffectModel (const G4PolarizedPEEffectModel &)=delete
Private Attributes
G4PolarizedPEEffectCrossSection * crossSectionCalculator
G4StokesVector theBeamPolarization
G4StokesVector finalElectronPolarization
G4int verboseLevel
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 63 of file G4PolarizedPEEffectModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PolarizedPEEffectModel.hh
Constructor & Destructor Documentation
G4PolarizedPEEffectModel::G4PolarizedPEEffectModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "Polarized-PhotoElectric") explicit
Definition at line 67 of file G4PolarizedPEEffectModel.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PolarizedPEEffectModel.cc
G4PolarizedPEEffectModel::~G4PolarizedPEEffectModel () virtual
Definition at line 77 of file G4PolarizedPEEffectModel.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PolarizedPEEffectModel.cc
References crossSectionCalculator.
G4PolarizedPEEffectModel::G4PolarizedPEEffectModel (const G4PolarizedPEEffectModel &) private delete
Member Function Documentation
void G4PolarizedPEEffectModel::Initialise (const G4ParticleDefinition * pd, const G4DataVector & dv) override virtual
Reimplemented from G4PEEffectFluoModel.
Definition at line 84 of file G4PolarizedPEEffectModel.cc.
View newest version in sPHENIX GitHub at line 84 of file G4PolarizedPEEffectModel.cc
References crossSectionCalculator, and G4PEEffectFluoModel::Initialise().
G4PolarizedPEEffectModel& G4PolarizedPEEffectModel::operator= (const G4PolarizedPEEffectModel & right) private delete
void G4PolarizedPEEffectModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Reimplemented from G4PEEffectFluoModel.
Definition at line 94 of file G4PolarizedPEEffectModel.cc.
View newest version in sPHENIX GitHub at line 94 of file G4PolarizedPEEffectModel.cc
References CLHEP::Hep3Vector::cross(), crossSectionCalculator, G4cout, G4endl, G4VEmModel::GetCurrentElement(), G4PolarizationHelper::GetFrame(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4PolarizedPEEffectCrossSection::GetPol2(), G4DynamicParticle::GetPolarization(), G4PolarizationHelper::GetRandomFrame(), G4PolarizedPEEffectCrossSection::Initialize(), G4StokesVector::InvRotateAz(), CLHEP::Hep3Vector::mag(), num, G4StokesVector::p1(), G4StokesVector::p2(), G4StokesVector::p3(), G4StokesVector::RotateAz(), G4PEEffectFluoModel::SampleSecondaries(), G4VPolarizedCrossSection::SetMaterial(), G4StokesVector::SetPhoton(), verboseLevel, and G4StokesVector::ZERO.
Member Data Documentation
G4PolarizedPEEffectCrossSection* G4PolarizedPEEffectModel::crossSectionCalculator private
Definition at line 97 of file G4PolarizedPEEffectModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4PolarizedPEEffectModel.hh
Referenced by Initialise(), SampleSecondaries(), and ~G4PolarizedPEEffectModel().
G4StokesVector G4PolarizedPEEffectModel::finalElectronPolarization private
Definition at line 101 of file G4PolarizedPEEffectModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PolarizedPEEffectModel.hh
G4StokesVector G4PolarizedPEEffectModel::theBeamPolarization private
Definition at line 99 of file G4PolarizedPEEffectModel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4PolarizedPEEffectModel.hh
G4int G4PolarizedPEEffectModel::verboseLevel private
Definition at line 103 of file G4PolarizedPEEffectModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PolarizedPEEffectModel.hh
Referenced by SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedPEEffectModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedPEEffectModel.cc