ECCE @ EIC Software: G4VAnnihilationCollision Class Reference
G4VAnnihilationCollision Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VAnnihilationCollision.hh>
Public Member Functions
G4VAnnihilationCollision ()
virtual ~G4VAnnihilationCollision ()
G4bool operator== (const G4VAnnihilationCollision &right) const
G4bool operator!= (const G4VAnnihilationCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual G4String GetName () const =0
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const
G4ParticleDefinition * GetOutgoingParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
Protected Member Functions inherited from G4VCollision
G4int GetNumberOfPartons (const G4ParticleDefinition *aP) const
virtual const G4CollisionVector * GetComponents () const
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const =0
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const =0
Private Member Functions
double BrWigInt0 (const double x, const double gamma, const double m0) const
G4double BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const
double BrWigInv (const double x, const double gamma, const double m0) const
double SampleResonanceMass (const double poleMass, const double width, const double minMass, const double maxMass) const
Private Attributes
G4VAngularDistribution * theAngularDistribution
Detailed Description
Definition at line 55 of file G4VAnnihilationCollision.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VAnnihilationCollision.hh
Constructor & Destructor Documentation
G4VAnnihilationCollision::G4VAnnihilationCollision ()
Definition at line 43 of file G4VAnnihilationCollision.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VAnnihilationCollision.cc
References theAngularDistribution.
G4VAnnihilationCollision::~G4VAnnihilationCollision () virtual
Definition at line 49 of file G4VAnnihilationCollision.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VAnnihilationCollision.cc
References theAngularDistribution.
Member Function Documentation
double G4VAnnihilationCollision::BrWigInt0 (const double x, const double gamma, const double m0) const inline private
Definition at line 81 of file G4VAnnihilationCollision.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VAnnihilationCollision.hh
Referenced by BrWigInt1().
G4double G4VAnnihilationCollision::BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 84 of file G4VAnnihilationCollision.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VAnnihilationCollision.hh
References BrWigInt0(), and G4Log().
double G4VAnnihilationCollision::BrWigInv (const double x, const double gamma, const double m0) const inline private
Definition at line 87 of file G4VAnnihilationCollision.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VAnnihilationCollision.hh
G4KineticTrackVector * G4VAnnihilationCollision::FinalState (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 58 of file G4VAnnihilationCollision.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VAnnihilationCollision.cc
References CLHEP::HepLorentzVector::boostVector(), G4KineticTrack::Get4Momentum(), GetOutgoingParticle(), G4KineticTrack::GetPosition(), and CLHEP::HepLorentzVector::m().
virtual const G4VAngularDistribution* G4VAnnihilationCollision::GetAngularDistribution () const inline virtual
Implements G4VCollision.
Definition at line 69 of file G4VAnnihilationCollision.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VAnnihilationCollision.hh
References theAngularDistribution.
virtual const G4ParticleDefinition* G4VAnnihilationCollision::GetOutgoingParticle (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const protected pure virtual
Implemented in G4ConcreteMesonBaryonToResonance.
Referenced by FinalState().
G4bool G4VAnnihilationCollision::operator!= (const G4VAnnihilationCollision & right) const
G4bool G4VAnnihilationCollision::operator== (const G4VAnnihilationCollision & right) const
double G4VAnnihilationCollision::SampleResonanceMass (const double poleMass, const double width, const double minMass, const double maxMass) const private
Member Data Documentation
G4VAngularDistribution* G4VAnnihilationCollision::theAngularDistribution private
Definition at line 96 of file G4VAnnihilationCollision.hh.
View newest version in sPHENIX GitHub at line 96 of file G4VAnnihilationCollision.hh
Referenced by G4VAnnihilationCollision(), GetAngularDistribution(), and ~G4VAnnihilationCollision().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VAnnihilationCollision.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4VAnnihilationCollision.cc