ECCE @ EIC Software: G4DigiCollection Class Reference
G4DigiCollection Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4TDigiCollection.hh>
Public Member Functions
G4DigiCollection ()
G4DigiCollection (G4String detName, G4String colNam)
virtual ~G4DigiCollection ()
G4bool operator== (const G4DigiCollection &right) const
Public Member Functions inherited from G4VDigiCollection
G4VDigiCollection ()
G4VDigiCollection (G4String DMnam, G4String colNam)
virtual ~G4VDigiCollection ()
G4bool operator== (const G4VDigiCollection &right) const
virtual void DrawAllDigi ()
virtual void PrintAllDigi ()
const G4String & GetName () const
const G4String & GetDMname () const
virtual G4VDigi * GetDigi (size_t) const
virtual size_t GetSize () const
Protected Attributes
void * theCollection
Protected Attributes inherited from G4VDigiCollection
G4String collectionName
G4String DMname
Detailed Description
Definition at line 47 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 47 of file G4TDigiCollection.hh
Constructor & Destructor Documentation
G4DigiCollection::G4DigiCollection ()
Definition at line 37 of file G4TDigiCollection.cc.
View newest version in sPHENIX GitHub at line 37 of file G4TDigiCollection.cc
References aDCAllocator_G4MT_TLS_().
G4DigiCollection::G4DigiCollection (G4String detName, G4String colNam)
Definition at line 40 of file G4TDigiCollection.cc.
View newest version in sPHENIX GitHub at line 40 of file G4TDigiCollection.cc
References aDCAllocator_G4MT_TLS_().
G4DigiCollection::~G4DigiCollection () virtual
Definition at line 44 of file G4TDigiCollection.cc.
View newest version in sPHENIX GitHub at line 44 of file G4TDigiCollection.cc
References aDCAllocator_G4MT_TLS_().
Member Function Documentation
G4bool G4DigiCollection::operator== (const G4DigiCollection & right) const
Definition at line 47 of file G4TDigiCollection.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TDigiCollection.cc
References aDCAllocator_G4MT_TLS_(), and G4VDigiCollection::collectionName.
Member Data Documentation
void* G4DigiCollection::theCollection protected
Definition at line 56 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 56 of file G4TDigiCollection.hh
Referenced by G4TDigiCollection< T >::entries(), G4TDigiCollection< T >::G4TDigiCollection(), G4TDigiCollection< T >::GetDigi(), G4TDigiCollection< T >::GetSize(), G4TDigiCollection< T >::GetVector(), G4TDigiCollection< T >::insert(), and G4TDigiCollection< T >::operator[]().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4TDigiCollection.hh
geant4/tree/geant4-10.6-release/source/digits_hits/digits/src/G4TDigiCollection.cc