ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_target.cc File Reference
MCGIDI_target.cc File Reference
#include <map>
#include <string.h>
#include <cmath>
#include "MCGIDI.h"
#include "MCGIDI_misc.h"
#include <xDataTOM_importXML_private.h>
Functions
static int _MCGIDI_target_releaseAndReturnOne (statusMessageReporting *smr, MCGIDI_target *target)
MCGIDI_target * MCGIDI_target_new (statusMessageReporting *smr)
int MCGIDI_target_initialize (statusMessageReporting *, MCGIDI_target *target)
MCGIDI_target * MCGIDI_target_newRead (statusMessageReporting *smr, const char *fileName)
int MCGIDI_target_readFromMapViaPoPIDs (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_map *map, const char *evaluation, int projectile_PoPID, int target_PoPID)
int MCGIDI_target_readFromMap (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_map *map, const char *evaluation, const char *projectileName, const char *targetName)
MCGIDI_target * MCGIDI_target_newReadFromMapViaPoPIDs (statusMessageReporting *smr, MCGIDI_map *map, const char *evaluation, int projectile_PoPID, int target_PoPID)
MCGIDI_target * MCGIDI_target_newReadFromMap (statusMessageReporting *smr, MCGIDI_map *map, const char *evaluation, const char *projectileName, const char *targetName)
MCGIDI_target * MCGIDI_target_free (statusMessageReporting *smr, MCGIDI_target *target)
int MCGIDI_target_release (statusMessageReporting *smr, MCGIDI_target *target)
int MCGIDI_target_read (statusMessageReporting *smr, MCGIDI_target *target, const char *fileName)
char const * MCGIDI_target_getAttributesValue (statusMessageReporting *, MCGIDI_target *target, char const *name)
int MCGIDI_target_getTemperatures (statusMessageReporting *, MCGIDI_target *target, double *temperatures)
int MCGIDI_target_readHeatedTarget (statusMessageReporting *smr, MCGIDI_target *target, int index)
MCGIDI_target_heated * MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded (statusMessageReporting *smr, MCGIDI_target *target, int index)
MCGIDI_target_heated * MCGIDI_target_getHeatedTargetAtTIndex (statusMessageReporting *smr, MCGIDI_target *target, int index)
int MCGIDI_target_numberOfReactions (statusMessageReporting *smr, MCGIDI_target *target)
enum MCGIDI_reactionType MCGIDI_target_getReactionTypeAtIndex (statusMessageReporting *smr, MCGIDI_target *target, int index)
MCGIDI_reaction * MCGIDI_target_getReactionAtIndex (MCGIDI_target *target, int index)
MCGIDI_reaction * MCGIDI_target_getReactionAtIndex_smr (statusMessageReporting *smr, MCGIDI_target *target, int index)
int MCGIDI_target_numberOfProductionReactions (statusMessageReporting *, MCGIDI_target *)
double MCGIDI_target_getTotalCrossSectionAtTAndE (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_quantitiesLookupModes &modes, bool sampling)
int MCGIDI_target_getDomain (statusMessageReporting *smr, MCGIDI_target *target, double *EMin, double *EMax)
double MCGIDI_target_getIndexReactionCrossSectionAtE (statusMessageReporting *smr, MCGIDI_target *target, int index, MCGIDI_quantitiesLookupModes &modes, bool sampling)
int MCGIDI_target_sampleReaction (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_quantitiesLookupModes &modes, double totalXSec, double(*userrng)(void *), void *rngState)
int MCGIDI_target_sampleNullReactionProductsAtE (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productDatas)
int MCGIDI_target_sampleIndexReactionProductsAtE (statusMessageReporting *smr, MCGIDI_target *target, int index, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productData)
double MCGIDI_target_getIndexReactionFinalQ (statusMessageReporting *smr, MCGIDI_target *target, int index, MCGIDI_quantitiesLookupModes &modes)
std::map< int, enum
MCGIDI_transportability >
const * MCGIDI_target_getUniqueProducts (statusMessageReporting *smr, MCGIDI_target *target)
int MCGIDI_target_recast (statusMessageReporting *smr, MCGIDI_target *target, GIDI_settings &settings)
Function Documentation
static int _MCGIDI_target_releaseAndReturnOne (statusMessageReporting * smr, MCGIDI_target * target) static
Definition at line 520 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 520 of file MCGIDI_target.cc
References MCGIDI_target_release().
Referenced by MCGIDI_target_read().
MCGIDI_target* MCGIDI_target_free (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 114 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 114 of file MCGIDI_target.cc
References MCGIDI_target_release(), and smr_freeMemory().
Referenced by MCGIDI_target_new(), and G4GIDI_target::~G4GIDI_target().
char const* MCGIDI_target_getAttributesValue (statusMessageReporting * , MCGIDI_target * target, char const * name)
Definition at line 245 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 245 of file MCGIDI_target.cc
References MCGIDI_target_s::attributes, and xDataTOMAL_getAttributesValue().
int MCGIDI_target_getDomain (statusMessageReporting * smr, MCGIDI_target * target, double * EMin, double * EMax)
Definition at line 382 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 382 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, MCGIDI_target_heated_getReactionsDomain(), and MCGIDI_target_numberOfReactions().
MCGIDI_target_heated* MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 289 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 289 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_readHeatedTarget(), MCGIDI_target_s::nHeatedTargets, smr_setReportError2, and smr_unknownID.
MCGIDI_target_heated* MCGIDI_target_getHeatedTargetAtTIndex (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 301 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 301 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_s::nHeatedTargets, smr_setReportError2, and smr_unknownID.
double MCGIDI_target_getIndexReactionCrossSectionAtE (statusMessageReporting * smr, MCGIDI_target * target, int index, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 402 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 402 of file MCGIDI_target.cc
References MCGIDI_quantitiesLookupModes::getTemperature(), MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_heated_getIndexReactionCrossSectionAtE(), MCGIDI_target_s::nReadHeatedTargets, MCGIDI_target_s::readHeatedTargets, and MCGIDI_target_heated_info_s::temperature.
Referenced by MCGIDI_target_sampleReaction(), G4GIDI_target::sampleChannelCrossSectionAtE(), and G4GIDI_target::sumChannelCrossSectionAtE().
double MCGIDI_target_getIndexReactionFinalQ (statusMessageReporting * smr, MCGIDI_target * target, int index, MCGIDI_quantitiesLookupModes & modes)
Definition at line 493 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 493 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getIndexReactionFinalQ().
MCGIDI_reaction* MCGIDI_target_getReactionAtIndex (MCGIDI_target * target, int index)
Definition at line 333 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 333 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getReactionAtIndex().
MCGIDI_reaction* MCGIDI_target_getReactionAtIndex_smr (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 340 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 340 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getReactionAtIndex_smr().
enum MCGIDI_reactionType MCGIDI_target_getReactionTypeAtIndex (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 323 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 323 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, MCGIDI_reaction_getReactionType(), MCGIDI_reactionType_unknown_e, and MCGIDI_target_heated_getReactionAtIndex_smr().
int MCGIDI_target_getTemperatures (statusMessageReporting * , MCGIDI_target * target, double * temperatures)
Definition at line 252 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 252 of file MCGIDI_target.cc
References MCGIDI_target_s::heatedTargets, MCGIDI_target_s::nHeatedTargets, and MCGIDI_target_heated_info_s::temperature.
Referenced by G4GIDI_target::getTemperatures().
double MCGIDI_target_getTotalCrossSectionAtTAndE (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 358 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 358 of file MCGIDI_target.cc
References MCGIDI_quantitiesLookupModes::getTemperature(), MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_heated_getTotalCrossSectionAtE(), MCGIDI_target_s::nReadHeatedTargets, MCGIDI_target_s::readHeatedTargets, and MCGIDI_target_heated_info_s::temperature.
Referenced by G4GIDI_target::getTotalCrossSectionAtE().
std::map<int, enum MCGIDI_transportability> const* MCGIDI_target_getUniqueProducts (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 501 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 501 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getUniqueProducts().
int MCGIDI_target_initialize (statusMessageReporting * , MCGIDI_target * target)
Definition at line 44 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 44 of file MCGIDI_target.cc
Referenced by MCGIDI_target_new(), MCGIDI_target_read(), and MCGIDI_target_release().
MCGIDI_target* MCGIDI_target_new (statusMessageReporting * smr)
Definition at line 33 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 33 of file MCGIDI_target.cc
References MCGIDI_target_free(), MCGIDI_target_initialize(), and smr_malloc2.
Referenced by MCGIDI_target_newRead().
MCGIDI_target* MCGIDI_target_newRead (statusMessageReporting * smr, const char * fileName)
Definition at line 52 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 52 of file MCGIDI_target.cc
References MCGIDI_target_new(), MCGIDI_target_read(), and smr_freeMemory().
Referenced by G4GIDI_target::init(), MCGIDI_target_newReadFromMap(), and MCGIDI_target_newReadFromMapViaPoPIDs().
MCGIDI_target* MCGIDI_target_newReadFromMap (statusMessageReporting * smr, MCGIDI_map * map, const char * evaluation, const char * projectileName, const char * targetName)
Definition at line 99 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 99 of file MCGIDI_target.cc
References MCGIDI_map_findTarget(), MCGIDI_target_newRead(), and smr_freeMemory().
MCGIDI_target* MCGIDI_target_newReadFromMapViaPoPIDs (statusMessageReporting * smr, MCGIDI_map * map, const char * evaluation, int projectile_PoPID, int target_PoPID)
Definition at line 85 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 85 of file MCGIDI_target.cc
References MCGIDI_map_findTargetViaPoPIDs(), MCGIDI_target_newRead(), and smr_freeMemory().
int MCGIDI_target_numberOfProductionReactions (statusMessageReporting * , MCGIDI_target *)
Definition at line 347 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 347 of file MCGIDI_target.cc
References MCGIDI_target_heated_numberOfProductionReactions().
Referenced by G4GIDI_target::getNumberOfProductionChannels().
int MCGIDI_target_numberOfReactions (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 316 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 316 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_numberOfReactions().
Referenced by G4GIDI_target::getChannelIDs(), G4GIDI_target::getNumberOfChannels(), G4GIDI_target::init(), MCGIDI_target_getDomain(), and MCGIDI_target_sampleReaction().
int MCGIDI_target_read (statusMessageReporting * smr, MCGIDI_target * target, const char * fileName)
Definition at line 143 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 143 of file MCGIDI_target.cc
References _MCGIDI_target_releaseAndReturnOne(), MCGIDI_target_s::absPath, MCGIDI_target_s::baseHeatedTarget, MCGIDI_target_heated_info_s::contents, MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_misc_getAbsPath(), MCGIDI_misc_setMessageError_Element(), MCGIDI_target_initialize(), MCGIDI_target_readHeatedTarget(), MCGIDI_target_release(), xDataXML_element_s::name, MCGIDI_target_s::nHeatedTargets, MCGIDI_target_heated_info_s::ordinal, MCGIDI_target_heated_info_s::path, MCGIDI_target_s::path, MCGIDI_target_s::readHeatedTargets, smr_allocateCopyString2, smr_malloc2, smr_setReportError2, smr_setReportError2p, smr_unknownID, MCGIDI_target_heated_info_s::temperature, xDataXML_convertAttributeToDouble(), xDataXML_freeDoc(), xDataXML_getAttributesValueInElement(), xDataXML_getDocumentsElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), and xDataXML_importFile2().
Referenced by MCGIDI_target_newRead(), MCGIDI_target_readFromMap(), and MCGIDI_target_readFromMapViaPoPIDs().
int MCGIDI_target_readFromMap (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_map * map, const char * evaluation, const char * projectileName, const char * targetName)
Definition at line 74 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 74 of file MCGIDI_target.cc
References MCGIDI_map_findTarget(), and MCGIDI_target_read().
int MCGIDI_target_readFromMapViaPoPIDs (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_map * map, const char * evaluation, int projectile_PoPID, int target_PoPID)
Definition at line 63 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 63 of file MCGIDI_target.cc
References MCGIDI_map_findTargetViaPoPIDs(), and MCGIDI_target_read().
int MCGIDI_target_readHeatedTarget (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 262 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 262 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_heated_newRead(), MCGIDI_target_s::nHeatedTargets, MCGIDI_target_s::nReadHeatedTargets, MCGIDI_target_heated_s::ordinal, MCGIDI_target_heated_info_s::ordinal, MCGIDI_target_heated_info_s::path, MCGIDI_target_heated_s::projectilePOP, MCGIDI_target_s::projectilePOP, MCGIDI_target_s::readHeatedTargets, smr_setReportError2, smr_unknownID, MCGIDI_target_heated_s::targetPOP, MCGIDI_target_s::targetPOP, and MCGIDI_target_heated_info_s::temperature.
Referenced by MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded(), MCGIDI_target_read(), and G4GIDI_target::readTemperature().
int MCGIDI_target_recast (statusMessageReporting * smr, MCGIDI_target * target, GIDI_settings & settings)
Definition at line 508 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 508 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_heated_recast(), MCGIDI_target_s::nReadHeatedTargets, and MCGIDI_target_s::readHeatedTargets.
int MCGIDI_target_release (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 123 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 123 of file MCGIDI_target.cc
References MCGIDI_target_s::absPath, MCGIDI_target_s::attributes, MCGIDI_target_heated_info_s::contents, MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_heated_free(), MCGIDI_target_initialize(), MCGIDI_target_s::nHeatedTargets, MCGIDI_target_heated_info_s::path, MCGIDI_target_s::path, MCGIDI_target_s::readHeatedTargets, smr_freeMemory(), and xDataTOMAL_release().
Referenced by _MCGIDI_target_releaseAndReturnOne(), MCGIDI_target_free(), and MCGIDI_target_read().
int MCGIDI_target_sampleIndexReactionProductsAtE (statusMessageReporting * smr, MCGIDI_target * target, int index, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productData)
Definition at line 485 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 485 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_sampleIndexReactionProductsAtE().
int MCGIDI_target_sampleNullReactionProductsAtE (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productDatas)
Definition at line 461 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 461 of file MCGIDI_target.cc
References MCGIDI_sampledProductsData_s::birthTimeSec, MCGIDI_sampledProductsData_s::delayedNeutronIndex, MCGIDI_sampledProductsData_s::delayedNeutronRate, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_decaySamplingInfo_s::isVelocity, MCGIDI_sampledProductsData_s::isVelocity, MCGIDI_sampledProductsData_s::kineticEnergy, MCGIDI_POP_s::mass_MeV, MCGIDI_sampledProducts_addProduct(), MCGIDI_speedOfLight_cm_sec, MCGIDI_sampledProductsDatas_s::numberOfProducts, MCGIDI_sampledProductsData_s::pop, MCGIDI_target_s::projectilePOP, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, and MCGIDI_sampledProductsData_s::pz_vz.
int MCGIDI_target_sampleReaction (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_quantitiesLookupModes & modes, double totalXSec, double(*)(void *) userrng, void * rngState)
Definition at line 426 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 426 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, e, MCGIDI_reaction_s::EMin, MCGIDI_quantitiesLookupModes::getCrossSectionMode(), MCGIDI_quantitiesLookupModes::getGroupIndex(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_quantitiesLookupModes::getTemperature(), MCGIDI_nullReaction, MCGIDI_quantityLookupMode_grouped, MCGIDI_target_getIndexReactionCrossSectionAtE(), MCGIDI_target_heated_getReactionAtIndex(), MCGIDI_target_numberOfReactions(), smr_setReportError2, smr_unknownID, MCGIDI_reaction_s::thresholdGroupDomain, and MCGIDI_reaction_s::thresholdGroupIndex.