ECCE @ EIC Software: Par01EMShowerModel Class Reference
Par01EMShowerModel Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01EMShowerModel.hh>
Public Member Functions
Par01EMShowerModel (G4String, G4Region *)
Par01EMShowerModel (G4String)
~Par01EMShowerModel ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool ModelTrigger (const G4FastTrack &)
virtual void DoIt (const G4FastTrack &, G4FastStep &)
Public Member Functions inherited from G4VFastSimulationModel
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Private Member Functions
void AssignSpotAndCallHit (const Par01EnergySpot &eSpot)
void FillFakeStep (const Par01EnergySpot &eSpot)
void Explode (const G4FastTrack &)
void BuildDetectorResponse ()
Private Attributes
G4Step * fFakeStep
G4StepPoint * fFakePreStepPoint
G4StepPoint * fFakePostStepPoint
G4TouchableHandle fTouchableHandle
G4Navigator * fpNavigator
G4bool fNaviSetup
G4Material * fCsI
std::vector< Par01EnergySpot > feSpotList
Detailed Description
Definition at line 47 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 47 of file Par01EMShowerModel.hh
Constructor & Destructor Documentation
Par01EMShowerModel::Par01EMShowerModel (G4String modelName, G4Region * envelope)
Definition at line 48 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 48 of file Par01EMShowerModel.cc
References fCsI, fFakePostStepPoint, fFakePreStepPoint, fFakeStep, fNaviSetup, fpNavigator, fTouchableHandle, G4Step::GetPostStepPoint(), and G4Step::GetPreStepPoint().
Par01EMShowerModel::Par01EMShowerModel (G4String modelName)
Definition at line 62 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 62 of file Par01EMShowerModel.cc
References fCsI, fFakePostStepPoint, fFakePreStepPoint, fFakeStep, fNaviSetup, fpNavigator, fTouchableHandle, G4Step::GetPostStepPoint(), and G4Step::GetPreStepPoint().
Par01EMShowerModel::~Par01EMShowerModel ()
Definition at line 76 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 76 of file Par01EMShowerModel.cc
References fFakeStep, and fpNavigator.
Member Function Documentation
void Par01EMShowerModel::AssignSpotAndCallHit (const Par01EnergySpot & eSpot) private
Definition at line 212 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 212 of file Par01EMShowerModel.cc
References fFakeStep, FillFakeStep(), G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), and G4VSensitiveDetector::Hit().
Referenced by BuildDetectorResponse().
void Par01EMShowerModel::BuildDetectorResponse () private
Definition at line 195 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 195 of file Par01EMShowerModel.cc
References AssignSpotAndCallHit(), and feSpotList.
Referenced by DoIt().
void Par01EMShowerModel::DoIt (const G4FastTrack & fastTrack, G4FastStep & fastStep) virtual
Implements G4VFastSimulationModel.
Definition at line 102 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 102 of file Par01EMShowerModel.cc
References BuildDetectorResponse(), Explode(), G4Track::GetKineticEnergy(), G4FastTrack::GetPrimaryTrack(), G4FastStep::KillPrimaryTrack(), G4FastStep::ProposePrimaryTrackPathLength(), and G4FastStep::ProposeTotalEnergyDeposited().
void Par01EMShowerModel::Explode (const G4FastTrack & fastTrack) private
Definition at line 120 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 120 of file Par01EMShowerModel.cc
References a, b, C(), CLHEP::Hep3Vector::cross(), fCsI, feSpotList, G4NistManager::FindOrBuildMaterial(), G4UniformRand, G4Gamma::GammaDefinition(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4FastTrack::GetPrimaryTrack(), G4Material::GetRadlen(), G4NistManager::Instance(), MeV, CLHEP::Hep3Vector::orthogonal(), phi, r, Par01EnergySpot::SetEnergy(), Par01EnergySpot::SetPosition(), G4INCL::DeJongSpin::shoot(), t, twopi, y, and z.
Referenced by DoIt().
void Par01EMShowerModel::FillFakeStep (const Par01EnergySpot & eSpot) private
Definition at line 241 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 241 of file Par01EMShowerModel.cc
References fFakePreStepPoint, fFakeStep, fNaviSetup, fpNavigator, fTouchableHandle, Par01EnergySpot::GetEnergy(), Par01EnergySpot::GetPosition(), G4TransportationManager::GetTransportationManager(), G4Step::SetTotalEnergyDeposit(), and G4StepPoint::SetTouchableHandle().
Referenced by AssignSpotAndCallHit().
G4bool Par01EMShowerModel::IsApplicable (const G4ParticleDefinition & particleType) virtual
Implements G4VFastSimulationModel.
Definition at line 84 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 84 of file Par01EMShowerModel.cc
References G4Electron::ElectronDefinition(), G4Gamma::GammaDefinition(), and G4Positron::PositronDefinition().
G4bool Par01EMShowerModel::ModelTrigger (const G4FastTrack & fastTrack) virtual
Implements G4VFastSimulationModel.
Definition at line 94 of file Par01EMShowerModel.cc.
View newest version in sPHENIX GitHub at line 94 of file Par01EMShowerModel.cc
References G4Track::GetKineticEnergy(), G4FastTrack::GetPrimaryTrack(), and MeV.
Member Data Documentation
G4Material* Par01EMShowerModel::fCsI private
Definition at line 81 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 81 of file Par01EMShowerModel.hh
Referenced by Explode(), and Par01EMShowerModel().
std::vector<Par01EnergySpot> Par01EMShowerModel::feSpotList private
Definition at line 83 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 83 of file Par01EMShowerModel.hh
Referenced by BuildDetectorResponse(), and Explode().
G4StepPoint * Par01EMShowerModel::fFakePostStepPoint private
Definition at line 77 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 77 of file Par01EMShowerModel.hh
Referenced by Par01EMShowerModel().
G4StepPoint* Par01EMShowerModel::fFakePreStepPoint private
Definition at line 77 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 77 of file Par01EMShowerModel.hh
Referenced by FillFakeStep(), and Par01EMShowerModel().
G4Step* Par01EMShowerModel::fFakeStep private
Definition at line 76 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 76 of file Par01EMShowerModel.hh
Referenced by AssignSpotAndCallHit(), FillFakeStep(), Par01EMShowerModel(), and ~Par01EMShowerModel().
G4bool Par01EMShowerModel::fNaviSetup private
Definition at line 80 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 80 of file Par01EMShowerModel.hh
Referenced by FillFakeStep(), and Par01EMShowerModel().
G4Navigator* Par01EMShowerModel::fpNavigator private
Definition at line 79 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 79 of file Par01EMShowerModel.hh
Referenced by FillFakeStep(), Par01EMShowerModel(), and ~Par01EMShowerModel().
G4TouchableHandle Par01EMShowerModel::fTouchableHandle private
Definition at line 78 of file Par01EMShowerModel.hh.
View newest version in sPHENIX GitHub at line 78 of file Par01EMShowerModel.hh
Referenced by FillFakeStep(), and Par01EMShowerModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01EMShowerModel.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01EMShowerModel.cc