ECCE @ EIC Software: cheprep::AbstractXMLWriter Class Reference
cheprep::AbstractXMLWriter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/AbstractXMLWriter.h>
Public Member Functions
AbstractXMLWriter (std::string aDefaultNameSpace)
virtual ~AbstractXMLWriter ()
virtual void openTag (std::string ns, std::string name)=0
virtual void printTag (std::string ns, std::string name)=0
virtual void setAttribute (std::string ns, std::string name, std::string value)=0
virtual void setAttribute (std::string ns, std::string name, double value)=0
virtual void close ()=0
virtual void openDoc (std::string version="1.0", std::string encoding="", bool standalone=false)=0
virtual void closeDoc (bool force=false)=0
virtual void openTag (std::string name)=0
virtual void closeTag ()=0
virtual void printTag (std::string name)=0
virtual void setAttribute (std::string name, char *value)=0
virtual void setAttribute (std::string name, std::string value)=0
virtual void setAttribute (std::string name, std::vector< double > value)=0
virtual void setAttribute (std::string name, int64 value)=0
virtual void setAttribute (std::string name, int value)=0
virtual void setAttribute (std::string name, bool value)=0
virtual void setAttribute (std::string name, double value)=0
Protected Attributes
std::string defaultNameSpace
Detailed Description
Definition at line 14 of file AbstractXMLWriter.h.
View newest version in sPHENIX GitHub at line 14 of file AbstractXMLWriter.h
Constructor & Destructor Documentation
cheprep::AbstractXMLWriter::AbstractXMLWriter (std::string aDefaultNameSpace) inline
Definition at line 17 of file AbstractXMLWriter.h.
View newest version in sPHENIX GitHub at line 17 of file AbstractXMLWriter.h
virtual cheprep::AbstractXMLWriter::~AbstractXMLWriter () inline virtual
Definition at line 19 of file AbstractXMLWriter.h.
View newest version in sPHENIX GitHub at line 19 of file AbstractXMLWriter.h
Member Function Documentation
virtual void cheprep::AbstractXMLWriter::close () pure virtual
Implemented in cheprep::BHepRepWriter, and cheprep::XMLWriter.
virtual void cheprep::AbstractXMLWriter::closeDoc (bool force = false) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void cheprep::AbstractXMLWriter::closeTag () pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void cheprep::AbstractXMLWriter::openDoc (std::string version = "1.0", std::string encoding = "", bool standalone = false) pure virtual
Implemented in cheprep::BHepRepWriter, and cheprep::XMLWriter.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void cheprep::AbstractXMLWriter::openTag (std::string ns, std::string name) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void cheprep::AbstractXMLWriter::openTag (std::string name) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::printTag (std::string ns, std::string name) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void cheprep::AbstractXMLWriter::printTag (std::string name) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string ns, std::string name, std::string value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string ns, std::string name, double value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, char * value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, std::string value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, std::vector< double > value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, int64 value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, int value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, bool value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
virtual void cheprep::AbstractXMLWriter::setAttribute (std::string name, double value) pure virtual
Implemented in cheprep::XMLWriter, and cheprep::BHepRepWriter.
Member Data Documentation
std::string cheprep::AbstractXMLWriter::defaultNameSpace protected
Definition at line 42 of file AbstractXMLWriter.h.
View newest version in sPHENIX GitHub at line 42 of file AbstractXMLWriter.h
Referenced by cheprep::BHepRepWriter::openTag(), cheprep::XMLWriter::openTag(), cheprep::BHepRepWriter::printTag(), and cheprep::XMLWriter::printTag().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/AbstractXMLWriter.h