ECCE @ EIC Software: G4eAdjointMultipleScattering Class Reference
G4eAdjointMultipleScattering Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4eAdjointMultipleScattering.hh>
Public Member Functions
G4eAdjointMultipleScattering (const G4String &processName="msc")
virtual ~G4eAdjointMultipleScattering ()
void StartTracking (G4Track *) override
G4bool IsApplicable (const G4ParticleDefinition &p) final
void PrintInfo () override
Public Member Functions inherited from G4VMultipleScattering
G4VMultipleScattering (const G4String &name="msc", G4ProcessType type=fElectromagnetic)
virtual ~G4VMultipleScattering ()
virtual void ProcessDescription (std::ostream &outFile) const override
void PreparePhysicsTable (const G4ParticleDefinition &) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
void StartTracking (G4Track *) override
G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimalStep, G4double &currentSafety, G4GPILSelection *selection) override
G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4ForceCondition *condition) override
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimalStep, G4double &currentSafety)
G4VEmModel * SelectModel (G4double kinEnergy, size_t idx)
void AddEmModel (G4int order, G4VEmModel *, const G4Region *region=nullptr)
void SetEmModel (G4VMscModel *, size_t index=0)
G4VMscModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
void SetIonisation (G4VEnergyLossProcess *)
G4bool LateralDisplasmentFlag () const
void SetLateralDisplasmentFlag (G4bool val)
G4double Skin () const
void SetSkin (G4double val)
G4double RangeFactor () const
void SetRangeFactor (G4double val)
G4double GeomFactor () const
G4double PolarAngleLimit () const
G4MscStepLimitType StepLimitType () const
void SetStepLimitType (G4MscStepLimitType val)
G4double LowestKinEnergy () const
void SetLowestKinEnergy (G4double val)
const G4ParticleDefinition * FirstParticle () const
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
void InitialiseProcess (const G4ParticleDefinition *) override
Protected Member Functions inherited from G4VMultipleScattering
virtual void StreamProcessInfo (std::ostream &) const
G4double GetMeanFreePath (const G4Track &track, G4double, G4ForceCondition *condition) override
G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimalStep, G4double &currentSafety) override
G4int NumberOfModels () const
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Attributes
G4bool isInitialized
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VMultipleScattering
G4ParticleChangeForMSC fParticleChange
Detailed Description
Definition at line 59 of file G4eAdjointMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 59 of file G4eAdjointMultipleScattering.hh
Constructor & Destructor Documentation
G4eAdjointMultipleScattering::G4eAdjointMultipleScattering (const G4String & processName = "msc") explicit
Definition at line 55 of file G4eAdjointMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 55 of file G4eAdjointMultipleScattering.cc
References isInitialized.
G4eAdjointMultipleScattering::~G4eAdjointMultipleScattering () virtual
Definition at line 63 of file G4eAdjointMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 63 of file G4eAdjointMultipleScattering.cc
Member Function Documentation
void G4eAdjointMultipleScattering::InitialiseProcess (const G4ParticleDefinition *) override protected virtual
Implements G4VMultipleScattering.
Definition at line 75 of file G4eAdjointMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 75 of file G4eAdjointMultipleScattering.cc
References G4VMultipleScattering::AddEmModel(), G4VMultipleScattering::EmModel(), isInitialized, and G4VMultipleScattering::SetEmModel().
G4bool G4eAdjointMultipleScattering::IsApplicable (const G4ParticleDefinition & p) final virtual
Implements G4VMultipleScattering.
Definition at line 68 of file G4eAdjointMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 68 of file G4eAdjointMultipleScattering.cc
References G4ParticleDefinition::GetPDGCharge(), and G4ParticleDefinition::IsShortLived().
void G4eAdjointMultipleScattering::PrintInfo () override virtual
Reimplemented from G4VMultipleScattering.
Definition at line 85 of file G4eAdjointMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 85 of file G4eAdjointMultipleScattering.cc
References fUseDistanceToBoundary, G4cout, G4endl, G4VMultipleScattering::GeomFactor(), G4VMultipleScattering::LateralDisplasmentFlag(), G4VMultipleScattering::RangeFactor(), G4VMultipleScattering::Skin(), and G4VMultipleScattering::StepLimitType().
void G4eAdjointMultipleScattering::StartTracking (G4Track *) override virtual
Reimplemented from G4VProcess.
Definition at line 98 of file G4eAdjointMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 98 of file G4eAdjointMultipleScattering.cc
References G4Electron::Electron(), and G4VMultipleScattering::StartTracking().
Member Data Documentation
G4bool G4eAdjointMultipleScattering::isInitialized private
Definition at line 84 of file G4eAdjointMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 84 of file G4eAdjointMultipleScattering.hh
Referenced by G4eAdjointMultipleScattering(), and InitialiseProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4eAdjointMultipleScattering.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4eAdjointMultipleScattering.cc