ECCE @ EIC Software: G4ErrorTrackLengthTarget Class Reference
G4ErrorTrackLengthTarget Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorTrackLengthTarget.hh>
Public Member Functions
G4ErrorTrackLengthTarget (const G4double maxTrkLength)
virtual ~G4ErrorTrackLengthTarget ()
virtual G4double GetDistanceFromPoint (const G4ThreeVector &, const G4ThreeVector &) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &) const
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double GetMeanFreePath (const class G4Track &track, G4double, G4ForceCondition *)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual void Dump (const G4String &msg) const
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Public Member Functions inherited from G4ErrorTarget
G4ErrorTarget ()
virtual ~G4ErrorTarget ()
virtual G4bool TargetReached (const G4Step *)
G4ErrorTargetType GetType () const
Private Attributes
G4double theMaximumTrackLength
G4VParticleChange theParticleChange
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VDiscreteProcess
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)=0
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Protected Attributes inherited from G4ErrorTarget
G4ErrorTargetType theType
Detailed Description
Definition at line 53 of file G4ErrorTrackLengthTarget.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ErrorTrackLengthTarget.hh
Constructor & Destructor Documentation
G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget (const G4double maxTrkLength)
Definition at line 46 of file G4ErrorTrackLengthTarget.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ErrorTrackLengthTarget.cc
References G4ProcessManager::AddDiscreteProcess(), G4ErrorTarget_TrkL, G4Exception(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4ParticleDefinition::IsShortLived(), particle, G4ProcessManager::RemoveProcess(), G4ParticleTableIterator< K, V >::reset(), RunMustBeAborted, G4ProcessVector::size(), theParticleIterator, G4ErrorTarget::theType, and G4ParticleTableIterator< K, V >::value().
virtual G4ErrorTrackLengthTarget::~G4ErrorTrackLengthTarget () inline virtual
Definition at line 60 of file G4ErrorTrackLengthTarget.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ErrorTrackLengthTarget.hh
Member Function Documentation
void G4ErrorTrackLengthTarget::Dump (const G4String & msg) const virtual
Implements G4ErrorTarget.
Definition at line 131 of file G4ErrorTrackLengthTarget.cc.
View newest version in sPHENIX GitHub at line 131 of file G4ErrorTrackLengthTarget.cc
References G4cout, G4endl, and theMaximumTrackLength.
virtual G4double G4ErrorTrackLengthTarget::GetDistanceFromPoint (const G4ThreeVector & , const G4ThreeVector &) const inline virtual
Reimplemented from G4ErrorTarget.
Definition at line 65 of file G4ErrorTrackLengthTarget.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ErrorTrackLengthTarget.hh
References DBL_MAX.
virtual G4double G4ErrorTrackLengthTarget::GetDistanceFromPoint (const G4ThreeVector &) const inline virtual
Reimplemented from G4ErrorTarget.
Definition at line 68 of file G4ErrorTrackLengthTarget.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ErrorTrackLengthTarget.hh
References DBL_MAX.
G4double G4ErrorTrackLengthTarget::GetMeanFreePath (const class G4Track & track, G4double , G4ForceCondition *) virtual
Definition at line 108 of file G4ErrorTrackLengthTarget.cc.
View newest version in sPHENIX GitHub at line 108 of file G4ErrorTrackLengthTarget.cc
References G4cout, G4endl, G4Track::GetTrackLength(), theMaximumTrackLength, and G4ErrorPropagatorData::verbose().
Referenced by PostStepGetPhysicalInteractionLength().
G4VParticleChange * G4ErrorTrackLengthTarget::PostStepDoIt (const G4Track & aTrack, const G4Step &) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 123 of file G4ErrorTrackLengthTarget.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ErrorTrackLengthTarget.cc
References G4VParticleChange::Initialize(), and theParticleChange.
G4double G4ErrorTrackLengthTarget::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 98 of file G4ErrorTrackLengthTarget.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ErrorTrackLengthTarget.cc
References GetMeanFreePath(), and NotForced.
Member Data Documentation
G4double G4ErrorTrackLengthTarget::theMaximumTrackLength private
Definition at line 87 of file G4ErrorTrackLengthTarget.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ErrorTrackLengthTarget.hh
Referenced by Dump(), and GetMeanFreePath().
G4VParticleChange G4ErrorTrackLengthTarget::theParticleChange private
Definition at line 88 of file G4ErrorTrackLengthTarget.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ErrorTrackLengthTarget.hh
Referenced by PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorTrackLengthTarget.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorTrackLengthTarget.cc