ECCE @ EIC Software: G4TemplateRNGHelper< T > Class Template Reference
G4TemplateRNGHelper< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4RNGHelper.hh>
Public Types
typedef std::vector< T > SeedsQueue
typedef SeedsQueue::size_type SeedsQueueSize_type
Public Member Functions
virtual ~G4TemplateRNGHelper ()
virtual const T GetSeed (const G4int &sdId)
void AddOneSeed (const T &seed)
void Fill (G4double *dbl, G4int nev, G4int nev_tot, G4int nrpe)
void Refill (G4double *dbl, G4int nev)
const SeedsQueueSize_type GetNumberSeeds () const
virtual void Clear ()
template<>
G4TemplateRNGHelper< G4long > * GetInstance ()
template<>
G4TemplateRNGHelper< G4long > * GetInstanceIfExist ()
template<>
G4TemplateRNGHelper< G4String > * GetInstance ()
template<>
G4TemplateRNGHelper< G4String > * GetInstanceIfExist ()
Static Public Member Functions
static G4TemplateRNGHelper< T > * GetInstance ()
static G4TemplateRNGHelper< T > * GetInstanceIfExist ()
Protected Attributes
SeedsQueue seeds
G4int offset
G4int nev_filled
G4int nev_total
G4int nRandParEvent
Private Member Functions
G4TemplateRNGHelper ()
template<>
G4TemplateRNGHelper< G4long > * instance
template<>
G4TemplateRNGHelper< G4String > * instance
Static Private Attributes
static G4TemplateRNGHelper< T > * instance
Detailed Description
template<class T>
class G4TemplateRNGHelper< T >
Definition at line 46 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 46 of file G4RNGHelper.hh
Member Typedef Documentation
template<class T> typedef std::vector<T> G4TemplateRNGHelper< T >::SeedsQueue
Definition at line 52 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RNGHelper.hh
template<class T> typedef SeedsQueue::size_type G4TemplateRNGHelper< T >::SeedsQueueSize_type
Definition at line 53 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RNGHelper.hh
Constructor & Destructor Documentation
template<class T > G4TemplateRNGHelper< T >::~G4TemplateRNGHelper () virtual
Definition at line 82 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 82 of file G4RNGHelper.cc
References JA::Clear(), and instance.
template<class T> G4TemplateRNGHelper< T >::G4TemplateRNGHelper () inline private
Definition at line 114 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RNGHelper.hh
References G4TemplateRNGHelper< T >::nev_filled, G4TemplateRNGHelper< T >::nev_total, G4TemplateRNGHelper< T >::nRandParEvent, and G4TemplateRNGHelper< T >::offset.
Member Function Documentation
template<class T> void G4TemplateRNGHelper< T >::AddOneSeed (const T & seed) inline
Definition at line 74 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 74 of file G4RNGHelper.hh
References G4TemplateRNGHelper< T >::seeds.
template<class T> virtual void G4TemplateRNGHelper< T >::Clear () inline virtual
Definition at line 102 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 102 of file G4RNGHelper.hh
References G4TemplateRNGHelper< T >::seeds.
template<class T> void G4TemplateRNGHelper< T >::Fill (G4double * dbl, G4int nev, G4int nev_tot, G4int nrpe) inline
Definition at line 77 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RNGHelper.hh
References L, G4TemplateRNGHelper< T >::nev_filled, G4TemplateRNGHelper< T >::nev_total, G4TemplateRNGHelper< T >::nRandParEvent, G4TemplateRNGHelper< T >::offset, and G4TemplateRNGHelper< T >::seeds.
Referenced by G4MTRunManager::InitializeEventLoop().
template<class T > G4TemplateRNGHelper< T > * G4TemplateRNGHelper< T >::GetInstance (void) static
Definition at line 37 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 37 of file G4RNGHelper.cc
References instance.
Referenced by G4WorkerRunManager::GenerateEvent(), G4MTRunManager::InitializeEventLoop(), G4MTRunManager::RefillSeeds(), G4MTRunManager::SetUpAnEvent(), and G4MTRunManager::SetUpNEvents().
template<> G4TemplateRNGHelper< G4long > * G4TemplateRNGHelper< G4long >::GetInstance (void)
Definition at line 52 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 52 of file G4RNGHelper.cc
References instance.
template<> G4TemplateRNGHelper< G4String > * G4TemplateRNGHelper< G4String >::GetInstance (void)
Definition at line 67 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 67 of file G4RNGHelper.cc
References instance.
template<class T > G4TemplateRNGHelper< T > * G4TemplateRNGHelper< T >::GetInstanceIfExist () static
Definition at line 46 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 46 of file G4RNGHelper.cc
References instance.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
template<> G4TemplateRNGHelper< G4long > * G4TemplateRNGHelper< G4long >::GetInstanceIfExist ()
Definition at line 61 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 61 of file G4RNGHelper.cc
References instance.
template<> G4TemplateRNGHelper< G4String > * G4TemplateRNGHelper< G4String >::GetInstanceIfExist ()
Definition at line 76 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 76 of file G4RNGHelper.cc
References instance.
template<class T> const SeedsQueueSize_type G4TemplateRNGHelper< T >::GetNumberSeeds () const inline
Definition at line 99 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 99 of file G4RNGHelper.hh
References G4TemplateRNGHelper< T >::seeds.
template<class T> virtual const T G4TemplateRNGHelper< T >::GetSeed (const G4int & sdId) inline virtual
Definition at line 58 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 58 of file G4RNGHelper.hh
References FatalException, G4Exception(), G4TemplateRNGHelper< T >::offset, seed, G4TemplateRNGHelper< T >::seeds, and T.
Referenced by G4WorkerRunManager::GenerateEvent(), G4MTRunManager::SetUpAnEvent(), and G4MTRunManager::SetUpNEvents().
template<> G4TemplateRNGHelper< G4long > * G4TemplateRNGHelper< G4long >::instance () private
Definition at line 31 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 31 of file G4RNGHelper.cc
template<> G4TemplateRNGHelper< G4String > * G4TemplateRNGHelper< G4String >::instance () private
Definition at line 34 of file G4RNGHelper.cc.
View newest version in sPHENIX GitHub at line 34 of file G4RNGHelper.cc
template<class T> void G4TemplateRNGHelper< T >::Refill (G4double * dbl, G4int nev) inline
Definition at line 88 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RNGHelper.hh
References L, G4TemplateRNGHelper< T >::nev_filled, G4TemplateRNGHelper< T >::nRandParEvent, G4TemplateRNGHelper< T >::offset, and G4TemplateRNGHelper< T >::seeds.
Referenced by G4MTRunManager::RefillSeeds().
Member Data Documentation
template<class T> G4TemplateRNGHelper<T>* G4TemplateRNGHelper< T >::instance static private
Definition at line 123 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 123 of file G4RNGHelper.hh
template<class T> G4int G4TemplateRNGHelper< T >::nev_filled protected
Definition at line 109 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 109 of file G4RNGHelper.hh
Referenced by G4TemplateRNGHelper< T >::Fill(), G4TemplateRNGHelper< T >::G4TemplateRNGHelper(), and G4TemplateRNGHelper< T >::Refill().
template<class T> G4int G4TemplateRNGHelper< T >::nev_total protected
Definition at line 110 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RNGHelper.hh
Referenced by G4TemplateRNGHelper< T >::Fill(), and G4TemplateRNGHelper< T >::G4TemplateRNGHelper().
template<class T> G4int G4TemplateRNGHelper< T >::nRandParEvent protected
Definition at line 111 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RNGHelper.hh
Referenced by G4TemplateRNGHelper< T >::Fill(), G4TemplateRNGHelper< T >::G4TemplateRNGHelper(), and G4TemplateRNGHelper< T >::Refill().
template<class T> G4int G4TemplateRNGHelper< T >::offset protected
Definition at line 108 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 108 of file G4RNGHelper.hh
Referenced by G4TemplateRNGHelper< T >::Fill(), G4TemplateRNGHelper< T >::G4TemplateRNGHelper(), G4TemplateRNGHelper< T >::GetSeed(), and G4TemplateRNGHelper< T >::Refill().
template<class T> SeedsQueue G4TemplateRNGHelper< T >::seeds protected
Definition at line 105 of file G4RNGHelper.hh.
View newest version in sPHENIX GitHub at line 105 of file G4RNGHelper.hh
Referenced by G4TemplateRNGHelper< T >::AddOneSeed(), G4TemplateRNGHelper< T >::Clear(), G4TemplateRNGHelper< T >::Fill(), G4TemplateRNGHelper< T >::GetNumberSeeds(), G4TemplateRNGHelper< T >::GetSeed(), and G4TemplateRNGHelper< T >::Refill().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4RNGHelper.hh
geant4/tree/geant4-10.6-release/source/run/src/G4RNGHelper.cc