ECCE @ EIC Software: G4AnyType::Ref< ValueType > Class Template Reference
G4AnyType::Ref< ValueType > Class Template Reference
Public Member Functions
Ref (ValueType &value)
virtual const std::type_info & TypeInfo () const
virtual Placeholder * Clone () const
virtual void * Address () const
virtual std::string ToString () const
virtual void FromString (const std::string &val)
template<>
void FromString (const std::string &val)
template<>
void FromString (const std::string &val)
template<>
void FromString (const std::string &val)
Public Member Functions inherited from G4AnyType::Placeholder
Placeholder ()
virtual ~Placeholder ()
Public Attributes
ValueType & fRef
Detailed Description
template<typename ValueType>
class G4AnyType::Ref< ValueType >
Definition at line 142 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 142 of file G4AnyType.hh
Constructor & Destructor Documentation
template<typename ValueType > G4AnyType::Ref< ValueType >::Ref (ValueType & value) inline
Constructor
Definition at line 145 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 145 of file G4AnyType.hh
Referenced by G4AnyType::Ref< ValueType >::Clone().
Member Function Documentation
template<typename ValueType > virtual void* G4AnyType::Ref< ValueType >::Address () const inline virtual
Address
Implements G4AnyType::Placeholder.
Definition at line 155 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 155 of file G4AnyType.hh
References G4AnyType::Ref< ValueType >::fRef.
template<typename ValueType > virtual Placeholder* G4AnyType::Ref< ValueType >::Clone () const inline virtual
Clone
Implements G4AnyType::Placeholder.
Definition at line 151 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 151 of file G4AnyType.hh
References G4AnyType::Ref< ValueType >::fRef, and G4AnyType::Ref< ValueType >::Ref().
template<typename ValueType > virtual void G4AnyType::Ref< ValueType >::FromString (const std::string & val) inline virtual
FromString
Implements G4AnyType::Placeholder.
Definition at line 165 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 165 of file G4AnyType.hh
References G4AnyType::Ref< ValueType >::fRef.
template<> void G4AnyType::Ref< bool >::FromString (const std::string & val) inline virtual
Specializations
Implements G4AnyType::Placeholder.
Definition at line 182 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 182 of file G4AnyType.hh
References G4UIcommand::ConvertToBool().
template<> void G4AnyType::Ref< G4String >::FromString (const std::string & val) inline virtual
FromString
Implements G4AnyType::Placeholder.
Definition at line 186 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 186 of file G4AnyType.hh
template<> void G4AnyType::Ref< G4ThreeVector >::FromString (const std::string & val) inline virtual
FromString
Implements G4AnyType::Placeholder.
Definition at line 191 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 191 of file G4AnyType.hh
References G4UIcommand::ConvertTo3Vector().
template<typename ValueType > virtual std::string G4AnyType::Ref< ValueType >::ToString () const inline virtual
ToString
Implements G4AnyType::Placeholder.
Definition at line 159 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 159 of file G4AnyType.hh
References G4AnyType::Ref< ValueType >::fRef.
template<typename ValueType > virtual const std::type_info& G4AnyType::Ref< ValueType >::TypeInfo () const inline virtual
Query
Implements G4AnyType::Placeholder.
Definition at line 147 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 147 of file G4AnyType.hh
Member Data Documentation
template<typename ValueType > ValueType& G4AnyType::Ref< ValueType >::fRef
representation
Definition at line 170 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 170 of file G4AnyType.hh
Referenced by G4AnyType::Ref< ValueType >::Address(), any_cast(), G4AnyType::Ref< ValueType >::Clone(), G4AnyType::Ref< ValueType >::FromString(), and G4AnyType::Ref< ValueType >::ToString().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyType.hh