ECCE @ EIC Software: ScreenSD Class Reference
ScreenSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/include/ScreenSD.hh>
Public Member Functions
ScreenSD (const G4String &name)
virtual ~ScreenSD ()
virtual void Initialize (G4HCofThisEvent *hce)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hce)
ScreenSD (const G4String &name)
virtual ~ScreenSD ()
virtual void Initialize (G4HCofThisEvent *hce)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hce)
ScreenSD (const G4String &name)
virtual ~ScreenSD ()
virtual void Initialize (G4HCofThisEvent *hce)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hce)
ScreenSD (const G4String &name)
virtual ~ScreenSD ()
virtual void Initialize (G4HCofThisEvent *hce)
virtual G4bool ProcessHits (G4Step *step, G4TouchableHistory *history)
virtual void EndOfEvent (G4HCofThisEvent *hce)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 40 of file ScreenSD.hh.
View newest version in sPHENIX GitHub at line 40 of file ScreenSD.hh
Constructor & Destructor Documentation
ScreenSD::ScreenSD (const G4String & name)
Definition at line 43 of file ScreenSD.cc.
View newest version in sPHENIX GitHub at line 43 of file ScreenSD.cc
ScreenSD::~ScreenSD () virtual
Definition at line 49 of file ScreenSD.cc.
View newest version in sPHENIX GitHub at line 49 of file ScreenSD.cc
ScreenSD::ScreenSD (const G4String & name)
virtual ScreenSD::~ScreenSD () virtual
ScreenSD::ScreenSD (const G4String & name)
virtual ScreenSD::~ScreenSD () virtual
ScreenSD::ScreenSD (const G4String & name)
virtual ScreenSD::~ScreenSD () virtual
Member Function Documentation
void ScreenSD::EndOfEvent (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 104 of file ScreenSD.cc.
View newest version in sPHENIX GitHub at line 104 of file ScreenSD.cc
virtual void ScreenSD::EndOfEvent (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
virtual void ScreenSD::EndOfEvent (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
virtual void ScreenSD::EndOfEvent (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
void ScreenSD::Initialize (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 54 of file ScreenSD.cc.
View newest version in sPHENIX GitHub at line 54 of file ScreenSD.cc
virtual void ScreenSD::Initialize (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
virtual void ScreenSD::Initialize (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
virtual void ScreenSD::Initialize (G4HCofThisEvent * hce) virtual
Reimplemented from G4VSensitiveDetector.
virtual G4bool ScreenSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
G4bool ScreenSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
Definition at line 59 of file ScreenSD.cc.
View newest version in sPHENIX GitHub at line 59 of file ScreenSD.cc
References G4VAnalysisManager::AddNtupleRow(), cm, G4VAnalysisManager::FillNtupleDColumn(), G4VAnalysisManager::FillNtupleIColumn(), G4Track::GetDefinition(), G4StepPoint::GetGlobalTime(), G4VTouchable::GetHistory(), G4StepPoint::GetKineticEnergy(), G4ParticleDefinition::GetPDGEncoding(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4NavigationHistory::GetTopTransform(), G4StepPoint::GetTouchable(), G4Step::GetTrack(), G4Track::GetTrackID(), G4ToolsAnalysisManager::Instance(), MeV, ns, Acts::VectorHelpers::time(), track, G4AffineTransform::TransformPoint(), CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
virtual G4bool ScreenSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
virtual G4bool ScreenSD::ProcessHits (G4Step * step, G4TouchableHistory * history) virtual
Implements G4VSensitiveDetector.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/include/ScreenSD.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/factory/shared/include/ScreenSD.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/genericPL/shared/include/ScreenSD.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/shared/include/ScreenSD.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/src/ScreenSD.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/factory/shared/src/ScreenSD.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/genericPL/shared/src/ScreenSD.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/shared/src/ScreenSD.cc