ECCE @ EIC Software: G4PhaseSpaceDecayChannel Class Reference
G4PhaseSpaceDecayChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4PhaseSpaceDecayChannel.hh>
Public Types
enum { MAX_N_DAUGHTERS =4 }
Public Member Functions
G4PhaseSpaceDecayChannel (G4int Verbose=1)
G4PhaseSpaceDecayChannel (const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
G4bool SetDaughterMasses (G4double masses[])
G4bool SampleDaughterMasses ()
virtual ~G4PhaseSpaceDecayChannel ()
virtual G4DecayProducts * DecayIt (G4double)
G4bool IsOKWithParentMass (G4double parentMass)
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Static Public Member Functions
static G4double Pmx (G4double e, G4double p1, G4double p2)
Private Member Functions
G4DecayProducts * OneBodyDecayIt ()
G4DecayProducts * TwoBodyDecayIt ()
G4DecayProducts * ThreeBodyDecayIt ()
G4DecayProducts * ManyBodyDecayIt ()
Private Attributes
G4Cache< G4double > current_parent_mass
G4bool useGivenDaughterMass
G4double givenDaughterMasses [MAX_N_DAUGHTERS]
Additional Inherited Members
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Protected Attributes inherited from G4VDecayChannel
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 45 of file G4PhaseSpaceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 45 of file G4PhaseSpaceDecayChannel.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
MAX_N_DAUGHTERS
Definition at line 48 of file G4PhaseSpaceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 48 of file G4PhaseSpaceDecayChannel.hh
Constructor & Destructor Documentation
G4PhaseSpaceDecayChannel::G4PhaseSpaceDecayChannel (G4int Verbose = 1)
Definition at line 50 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PhaseSpaceDecayChannel.cc
G4PhaseSpaceDecayChannel::G4PhaseSpaceDecayChannel (const G4String & theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String & theDaughterName1, const G4String & theDaughterName2 = "", const G4String & theDaughterName3 = "", const G4String & theDaughterName4 = "")
Definition at line 57 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PhaseSpaceDecayChannel.cc
G4PhaseSpaceDecayChannel::~G4PhaseSpaceDecayChannel () virtual
Definition at line 77 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PhaseSpaceDecayChannel.cc
Member Function Documentation
G4DecayProducts * G4PhaseSpaceDecayChannel::DecayIt (G4double parentMass) virtual
Implements G4VDecayChannel.
Definition at line 81 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4PhaseSpaceDecayChannel.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), current_parent_mass, G4VDecayChannel::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_parent_mass, G4VDecayChannel::GetVerboseLevel(), ManyBodyDecayIt(), G4VDecayChannel::numberOfDaughters, OneBodyDecayIt(), G4VDecayChannel::parent_name, G4Cache< VALTYPE >::Put(), ThreeBodyDecayIt(), and TwoBodyDecayIt().
G4bool G4PhaseSpaceDecayChannel::IsOKWithParentMass (G4double parentMass) virtual
Reimplemented from G4VDecayChannel.
Definition at line 726 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 726 of file G4PhaseSpaceDecayChannel.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), givenDaughterMasses, G4VDecayChannel::IsOKWithParentMass(), G4VDecayChannel::numberOfDaughters, and useGivenDaughterMass.
G4DecayProducts * G4PhaseSpaceDecayChannel::ManyBodyDecayIt () private
Definition at line 453 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 453 of file G4PhaseSpaceDecayChannel.cc
References CLHEP::HepLorentzVector::boost(), current_parent_mass, G4VDecayChannel::daughters_name, G4DecayProducts::DumpInfo(), G4cout, G4endl, G4Exception(), G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_daughters_mass, G4VDecayChannel::G4MT_parent, G4UniformRand, G4Cache< VALTYPE >::Get(), G4DynamicParticle::Get4Momentum(), G4ParticleDefinition::GetParticleName(), G4VDecayChannel::GetVerboseLevel(), GeV, givenDaughterMasses, Acts::index2, JustWarning, G4VDecayChannel::numberOfDaughters, G4VDecayChannel::parent_name, phi, Pmx(), G4DecayProducts::PushProducts(), rad, G4DynamicParticle::Set4Momentum(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4InuclParticleNames::sm, twopi, useGivenDaughterMass, weight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DecayIt().
G4DecayProducts * G4PhaseSpaceDecayChannel::OneBodyDecayIt () private
Definition at line 127 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 127 of file G4PhaseSpaceDecayChannel.cc
References current_parent_mass, G4DecayProducts::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4Cache< VALTYPE >::Get(), G4VDecayChannel::GetVerboseLevel(), givenDaughterMasses, G4DecayProducts::PushProducts(), G4DynamicParticle::SetMass(), and useGivenDaughterMass.
Referenced by DecayIt().
G4double G4PhaseSpaceDecayChannel::Pmx (G4double e, G4double p1, G4double p2) static
Definition at line 739 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 739 of file G4PhaseSpaceDecayChannel.cc
References e.
Referenced by G4DalitzDecayChannel::DecayIt(), ManyBodyDecayIt(), and TwoBodyDecayIt().
G4bool G4PhaseSpaceDecayChannel::SampleDaughterMasses ()
Definition at line 720 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 720 of file G4PhaseSpaceDecayChannel.cc
References useGivenDaughterMass.
G4bool G4PhaseSpaceDecayChannel::SetDaughterMasses (G4double masses[])
Definition at line 711 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 711 of file G4PhaseSpaceDecayChannel.cc
References givenDaughterMasses, incremental_prev_tag::idx, G4VDecayChannel::numberOfDaughters, and useGivenDaughterMass.
G4DecayProducts * G4PhaseSpaceDecayChannel::ThreeBodyDecayIt () private
Definition at line 262 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 262 of file G4PhaseSpaceDecayChannel.cc
References current_parent_mass, G4DecayProducts::DumpInfo(), G4VDecayChannel::DynamicalMass(), energy, G4cout, G4endl, G4Exception(), G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_daughters_mass, G4VDecayChannel::G4MT_daughters_width, G4VDecayChannel::G4MT_parent, G4UniformRand, G4Cache< VALTYPE >::Get(), G4ParticleDefinition::GetParticleName(), G4VDecayChannel::GetVerboseLevel(), GeV, givenDaughterMasses, JustWarning, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), phi, G4DecayProducts::PushProducts(), rad, G4VDecayChannel::rangeMass, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), twopi, and useGivenDaughterMass.
Referenced by DecayIt().
G4DecayProducts * G4PhaseSpaceDecayChannel::TwoBodyDecayIt () private
Definition at line 157 of file G4PhaseSpaceDecayChannel.cc.
View newest version in sPHENIX GitHub at line 157 of file G4PhaseSpaceDecayChannel.cc
References current_parent_mass, G4DecayProducts::DumpInfo(), G4VDecayChannel::DynamicalMass(), e, G4cout, G4endl, G4Exception(), G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_daughters_mass, G4VDecayChannel::G4MT_daughters_width, G4VDecayChannel::G4MT_parent, G4UniformRand, G4Cache< VALTYPE >::Get(), G4ParticleDefinition::GetParticleName(), G4VDecayChannel::GetVerboseLevel(), GeV, givenDaughterMasses, JustWarning, phi, Pmx(), G4DecayProducts::PushProducts(), rad, G4VDecayChannel::rangeMass, twopi, and useGivenDaughterMass.
Referenced by DecayIt().
Member Data Documentation
G4Cache<G4double> G4PhaseSpaceDecayChannel::current_parent_mass private
Definition at line 78 of file G4PhaseSpaceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PhaseSpaceDecayChannel.hh
Referenced by DecayIt(), ManyBodyDecayIt(), OneBodyDecayIt(), ThreeBodyDecayIt(), and TwoBodyDecayIt().
G4double G4PhaseSpaceDecayChannel::givenDaughterMasses[MAX_N_DAUGHTERS] private
Definition at line 84 of file G4PhaseSpaceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4PhaseSpaceDecayChannel.hh
Referenced by IsOKWithParentMass(), ManyBodyDecayIt(), OneBodyDecayIt(), SetDaughterMasses(), ThreeBodyDecayIt(), and TwoBodyDecayIt().
G4bool G4PhaseSpaceDecayChannel::useGivenDaughterMass private
Definition at line 83 of file G4PhaseSpaceDecayChannel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PhaseSpaceDecayChannel.hh
Referenced by IsOKWithParentMass(), ManyBodyDecayIt(), OneBodyDecayIt(), SampleDaughterMasses(), SetDaughterMasses(), ThreeBodyDecayIt(), and TwoBodyDecayIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4PhaseSpaceDecayChannel.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4PhaseSpaceDecayChannel.cc