ECCE @ EIC Software: G4BOptrForceCollisionTrackData Class Reference
G4BOptrForceCollisionTrackData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptrForceCollisionTrackData.hh>
Public Member Functions
G4BOptrForceCollisionTrackData (const G4BOptrForceCollision *)
~G4BOptrForceCollisionTrackData ()
void Print () const
G4bool IsFreeFromBiasing () const
Public Member Functions inherited from G4VAuxiliaryTrackInformation
G4VAuxiliaryTrackInformation ()
virtual ~G4VAuxiliaryTrackInformation ()
Private Member Functions
void Reset ()
Private Attributes
const G4BOptrForceCollision * fForceCollisionOperator
ForceCollisionState fForceCollisionState
Friends
class G4BOptrForceCollision
Detailed Description
Definition at line 52 of file G4BOptrForceCollisionTrackData.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BOptrForceCollisionTrackData.hh
Constructor & Destructor Documentation
G4BOptrForceCollisionTrackData::G4BOptrForceCollisionTrackData (const G4BOptrForceCollision * optr)
Definition at line 29 of file G4BOptrForceCollisionTrackData.cc.
View newest version in sPHENIX GitHub at line 29 of file G4BOptrForceCollisionTrackData.cc
References fForceCollisionState.
G4BOptrForceCollisionTrackData::~G4BOptrForceCollisionTrackData ()
Definition at line 36 of file G4BOptrForceCollisionTrackData.cc.
View newest version in sPHENIX GitHub at line 36 of file G4BOptrForceCollisionTrackData.cc
References fForceCollisionOperator, fForceCollisionState, G4Exception(), G4VBiasingOperator::GetName(), and JustWarning.
Member Function Documentation
G4bool G4BOptrForceCollisionTrackData::IsFreeFromBiasing () const inline
Definition at line 64 of file G4BOptrForceCollisionTrackData.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BOptrForceCollisionTrackData.hh
References fForceCollisionState.
Referenced by G4BOptrForceCollision::EndTracking(), and G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation().
void G4BOptrForceCollisionTrackData::Print (void) const virtual
Reimplemented from G4VAuxiliaryTrackInformation.
Definition at line 51 of file G4BOptrForceCollisionTrackData.cc.
View newest version in sPHENIX GitHub at line 51 of file G4BOptrForceCollisionTrackData.cc
References fForceCollisionOperator, fForceCollisionState, G4cout, G4endl, and G4VBiasingOperator::GetName().
void G4BOptrForceCollisionTrackData::Reset () inline private
Definition at line 72 of file G4BOptrForceCollisionTrackData.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BOptrForceCollisionTrackData.hh
References fForceCollisionOperator, and fForceCollisionState.
Referenced by G4BOptrForceCollision::OperationApplied(), and G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
Friends And Related Function Documentation
friend class G4BOptrForceCollision friend
Definition at line 54 of file G4BOptrForceCollisionTrackData.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BOptrForceCollisionTrackData.hh
Member Data Documentation
const G4BOptrForceCollision* G4BOptrForceCollisionTrackData::fForceCollisionOperator private
Definition at line 69 of file G4BOptrForceCollisionTrackData.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BOptrForceCollisionTrackData.hh
Referenced by Print(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), Reset(), and ~G4BOptrForceCollisionTrackData().
ForceCollisionState G4BOptrForceCollisionTrackData::fForceCollisionState private
Definition at line 70 of file G4BOptrForceCollisionTrackData.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BOptrForceCollisionTrackData.hh
Referenced by G4BOptrForceCollisionTrackData(), IsFreeFromBiasing(), G4BOptrForceCollision::OperationApplied(), Print(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), Reset(), and ~G4BOptrForceCollisionTrackData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptrForceCollisionTrackData.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptrForceCollisionTrackData.cc