ECCE @ EIC Software: G4WilsonRadius Class Reference
G4WilsonRadius Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4WilsonRadius.hh>
Public Member Functions
G4WilsonRadius ()
~G4WilsonRadius ()
G4double GetWilsonRMSRadius (G4double A)
G4double GetWilsonRadius (G4double A)
Private Attributes
G4double r0sq
G4double factor
G4double third
Detailed Description
Definition at line 78 of file G4WilsonRadius.hh.
View newest version in sPHENIX GitHub at line 78 of file G4WilsonRadius.hh
Constructor & Destructor Documentation
G4WilsonRadius::G4WilsonRadius ()
Definition at line 68 of file G4WilsonRadius.cc.
View newest version in sPHENIX GitHub at line 68 of file G4WilsonRadius.cc
References factor, fermi, r0sq, and third.
G4WilsonRadius::~G4WilsonRadius ()
Definition at line 77 of file G4WilsonRadius.cc.
View newest version in sPHENIX GitHub at line 77 of file G4WilsonRadius.cc
Member Function Documentation
G4double G4WilsonRadius::GetWilsonRadius (G4double A)
Definition at line 103 of file G4WilsonRadius.cc.
View newest version in sPHENIX GitHub at line 103 of file G4WilsonRadius.cc
References GetWilsonRMSRadius(), r, and r0sq.
Referenced by G4WilsonAbrasionModel::ApplyYourself(), and G4NuclearAbrasionGeometry::G4NuclearAbrasionGeometry().
G4double G4WilsonRadius::GetWilsonRMSRadius (G4double A)
Definition at line 81 of file G4WilsonRadius.cc.
View newest version in sPHENIX GitHub at line 81 of file G4WilsonRadius.cc
References G4Pow::A13(), factor, G4Pow::GetInstance(), r, and radius.
Referenced by G4TripathiLightCrossSection::GetElementCrossSection(), and GetWilsonRadius().
Member Data Documentation
G4double G4WilsonRadius::factor private
Definition at line 89 of file G4WilsonRadius.hh.
View newest version in sPHENIX GitHub at line 89 of file G4WilsonRadius.hh
Referenced by G4WilsonRadius(), and GetWilsonRMSRadius().
G4double G4WilsonRadius::r0sq private
Definition at line 88 of file G4WilsonRadius.hh.
View newest version in sPHENIX GitHub at line 88 of file G4WilsonRadius.hh
Referenced by G4WilsonRadius(), and GetWilsonRadius().
G4double G4WilsonRadius::third private
Definition at line 90 of file G4WilsonRadius.hh.
View newest version in sPHENIX GitHub at line 90 of file G4WilsonRadius.hh
Referenced by G4WilsonRadius().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4WilsonRadius.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4WilsonRadius.cc