ECCE @ EIC Software: F04Trajectory Class Reference
F04Trajectory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04Trajectory.hh>
Public Member Functions
F04Trajectory ()
F04Trajectory (const G4Track *aTrack)
F04Trajectory (F04Trajectory &)
virtual ~F04Trajectory ()
void * operator new (size_t)
void operator delete (void *)
int operator== (const F04Trajectory &right) const
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4ThreeVector GetInitialMomentum () const
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void AppendStep (const G4Step *aStep)
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ParticleDefinition * GetParticleDefinition ()
virtual int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
virtual void DrawTrajectory () const
Private Attributes
TrajectoryPointContainer * fpPointsContainer
G4int fTrackID
G4int fParentID
G4double fPDGCharge
G4int fPDGEncoding
G4String fParticleName
G4ThreeVector fInitialMomentum
Detailed Description
Definition at line 49 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 49 of file F04Trajectory.hh
Constructor & Destructor Documentation
F04Trajectory::F04Trajectory ()
Definition at line 51 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 51 of file F04Trajectory.cc
F04Trajectory::F04Trajectory (const G4Track * aTrack)
Definition at line 58 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 58 of file F04Trajectory.cc
References fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fpPointsContainer, fTrackID, G4Track::GetDefinition(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), and G4Track::GetTrackID().
F04Trajectory::F04Trajectory (F04Trajectory & right)
Definition at line 74 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 74 of file F04Trajectory.cc
References fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fpPointsContainer, and fTrackID.
F04Trajectory::~F04Trajectory () virtual
Definition at line 93 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 93 of file F04Trajectory.cc
References fpPointsContainer.
Member Function Documentation
void F04Trajectory::AppendStep (const G4Step * aStep) virtual
Implements G4VTrajectory.
Definition at line 114 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 114 of file F04Trajectory.cc
References fpPointsContainer.
std::vector< G4AttValue > * F04Trajectory::CreateAttValues () const virtual
Reimplemented from G4VTrajectory.
Definition at line 186 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 186 of file F04Trajectory.cc
References G4UIcommand::ConvertToString(), fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fTrackID, G4BestUnit, G4cout, GetAttDefs(), GetPointEntries(), CLHEP::Hep3Vector::mag(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * F04Trajectory::GetAttDefs () const virtual
Reimplemented from G4VTrajectory.
Definition at line 144 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 144 of file F04Trajectory.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues().
G4double F04Trajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 75 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 75 of file F04Trajectory.hh
References fPDGCharge.
G4ThreeVector F04Trajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 77 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 77 of file F04Trajectory.hh
References fInitialMomentum.
G4int F04Trajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 73 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 73 of file F04Trajectory.hh
References fParentID.
G4ParticleDefinition * F04Trajectory::GetParticleDefinition ()
Definition at line 121 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 121 of file F04Trajectory.cc
References fParticleName, and G4ParticleTable::GetParticleTable().
G4String F04Trajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 74 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 74 of file F04Trajectory.hh
References fParticleName.
G4int F04Trajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 76 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 76 of file F04Trajectory.hh
References fPDGEncoding.
virtual G4VTrajectoryPoint* F04Trajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Definition at line 89 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 89 of file F04Trajectory.hh
References fpPointsContainer.
virtual int F04Trajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Definition at line 87 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 87 of file F04Trajectory.hh
References fpPointsContainer.
Referenced by CreateAttValues(), and MergeTrajectory().
G4int F04Trajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 72 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 72 of file F04Trajectory.hh
References fTrackID.
void F04Trajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Definition at line 128 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 128 of file F04Trajectory.cc
References fpPointsContainer, GetPointEntries(), and second.
void F04Trajectory::operator delete (void * aTrajectory) inline
Definition at line 120 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 120 of file F04Trajectory.hh
References F04TrajectoryAllocator.
void * F04Trajectory::operator new (size_t) inline
Definition at line 114 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 114 of file F04Trajectory.hh
References F04TrajectoryAllocator.
int F04Trajectory::operator== (const F04Trajectory & right) const inline
Definition at line 67 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 67 of file F04Trajectory.hh
void F04Trajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4VTrajectory.
Definition at line 105 of file F04Trajectory.cc.
View newest version in sPHENIX GitHub at line 105 of file F04Trajectory.cc
References G4VTrajectory::ShowTrajectory().
Member Data Documentation
G4ThreeVector F04Trajectory::fInitialMomentum private
Definition at line 108 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 108 of file F04Trajectory.hh
Referenced by CreateAttValues(), F04Trajectory(), and GetInitialMomentum().
G4int F04Trajectory::fParentID private
Definition at line 104 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 104 of file F04Trajectory.hh
Referenced by CreateAttValues(), F04Trajectory(), and GetParentID().
G4String F04Trajectory::fParticleName private
Definition at line 107 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 107 of file F04Trajectory.hh
Referenced by CreateAttValues(), F04Trajectory(), GetParticleDefinition(), and GetParticleName().
G4double F04Trajectory::fPDGCharge private
Definition at line 105 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 105 of file F04Trajectory.hh
Referenced by CreateAttValues(), F04Trajectory(), and GetCharge().
G4int F04Trajectory::fPDGEncoding private
Definition at line 106 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 106 of file F04Trajectory.hh
Referenced by CreateAttValues(), F04Trajectory(), and GetPDGEncoding().
TrajectoryPointContainer* F04Trajectory::fpPointsContainer private
Definition at line 101 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 101 of file F04Trajectory.hh
Referenced by AppendStep(), F04Trajectory(), GetPoint(), GetPointEntries(), MergeTrajectory(), and ~F04Trajectory().
G4int F04Trajectory::fTrackID private
Definition at line 103 of file F04Trajectory.hh.
View newest version in sPHENIX GitHub at line 103 of file F04Trajectory.hh
Referenced by CreateAttValues(), F04Trajectory(), and GetTrackID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04Trajectory.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04Trajectory.cc