ECCE @ EIC Software: G4VUserActionInitialization Class Reference
G4VUserActionInitialization Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUserActionInitialization.hh>
Inherited by ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, B01ActionInitialization, B02ActionInitialization, B03ActionInitialization, B1ActionInitialization, B1ActionInitialization, B1ConActionInitialization, B2ActionInitialization, B2ActionInitialization, B2ActionInitialization, B3aActionInitialization, B3bActionInitialization, B4aActionInitialization, B4bActionInitialization, B4cActionInitialization, B4dActionInitialization, B5ActionInitialization, BrachyActionInitialization, CCalActionInitializer, Dicom2ActionInitialization, DicomActionInitialization, DMXActionInitializer, doiPETActionInitialization, ElectronActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, ExTGActionInitialization, ExUCNActionInitialization, F01ActionInitialization, F02ActionInitialization, F03ActionInitialization, F04ActionInitialization, F05ActionInitialization, F06ActionInitialization, FCALActionInitialization, FFActionInitialization, G01ActionInitialization, G04ActionInitialization, G3toG4ActionInitialization, G4HumanPhantomActionInitialization, GammaKnifeActionInitialization, GammaRayTelActionInitializer, GB01ActionInitialization, GB02ActionInitialization, GB03ActionInitialization, GB04ActionInitialization, GB05ActionInitialization, GB06ActionInitialization, GB07ActionInitialization, HadrontherapyActionInitialization, LXeActionInitialization, OpNoviceActionInitialization, Par01ActionInitialization, Par02ActionInitialization, PurgMagActionInitializer, RE01ActionInitialization, RE02ActionInitialization, RE03ActionInitialization, RE04ActionInitialization, RE05ActionInitialization, RE06ActionInitialization, STCyclotronActionInitialization, TSActionInitialization, UltraActionInitializer, WLSActionInitialization, XActionInitialization, XrayFluoActionInitializer, and XrayTelActionInitializer.
Public Member Functions
G4VUserActionInitialization ()
virtual ~G4VUserActionInitialization ()
virtual void Build () const =0
virtual void BuildForMaster () const
virtual G4VSteppingVerbose * InitializeSteppingVerbose () const
Protected Member Functions
void SetUserAction (G4VUserPrimaryGeneratorAction *) const
void SetUserAction (G4UserRunAction *) const
void SetUserAction (G4UserEventAction *) const
void SetUserAction (G4UserStackingAction *) const
void SetUserAction (G4UserTrackingAction *) const
void SetUserAction (G4UserSteppingAction *) const
Detailed Description
Definition at line 58 of file G4VUserActionInitialization.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VUserActionInitialization.hh
Constructor & Destructor Documentation
G4VUserActionInitialization::G4VUserActionInitialization ()
Definition at line 29 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 29 of file G4VUserActionInitialization.cc
G4VUserActionInitialization::~G4VUserActionInitialization () virtual
Definition at line 32 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 32 of file G4VUserActionInitialization.cc
Member Function Documentation
virtual void G4VUserActionInitialization::Build () const pure virtual
Implemented in Par02ActionInitialization, TSActionInitialization, FFActionInitialization, ActionInitialization, doiPETActionInitialization, F01ActionInitialization, F02ActionInitialization, F03ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, WLSActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, XrayTelActionInitializer, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, B2ActionInitialization, B2ActionInitialization, B3aActionInitialization, B3bActionInitialization, B4aActionInitialization, B4bActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ElectronActionInitialization, LXeActionInitialization, OpNoviceActionInitialization, B2ActionInitialization, ActionInitialization, GammaKnifeActionInitialization, PurgMagActionInitializer, ActionInitialization, XrayFluoActionInitializer, ActionInitialization, F04ActionInitialization, ActionInitialization, ExGflashActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, GammaRayTelActionInitializer, DMXActionInitializer, B4cActionInitialization, B4dActionInitialization, B1ConActionInitialization, B01ActionInitialization, B02ActionInitialization, B03ActionInitialization, GB01ActionInitialization, GB02ActionInitialization, GB04ActionInitialization, GB05ActionInitialization, GB06ActionInitialization, GB07ActionInitialization, G3toG4ActionInitialization, DicomActionInitialization, ActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, Par01ActionInitialization, ExTGActionInitialization, UltraActionInitializer, CCalActionInitializer, HadrontherapyActionInitialization, G4HumanPhantomActionInitialization, FCALActionInitialization, B1ActionInitialization, B5ActionInitialization, ExUCNActionInitialization, F05ActionInitialization, F06ActionInitialization, Dicom2ActionInitialization, G01ActionInitialization, G04ActionInitialization, RE03ActionInitialization, B1ActionInitialization, ActionInitialization, STCyclotronActionInitialization, XActionInitialization, ActionInitialization, RE01ActionInitialization, RE02ActionInitialization, RE04ActionInitialization, RE05ActionInitialization, RE06ActionInitialization, BrachyActionInitialization, ActionInitialization, GB03ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, and ActionInitialization.
Referenced by tbbTask::execute(), G4RunManager::SetUserInitialization(), and G4MTRunManagerKernel::StartThread().
void G4VUserActionInitialization::BuildForMaster (void) const virtual
Reimplemented in Par02ActionInitialization, TSActionInitialization, FFActionInitialization, ActionInitialization, doiPETActionInitialization, F01ActionInitialization, F02ActionInitialization, F03ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, WLSActionInitialization, XrayTelActionInitializer, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, PurgMagActionInitializer, XrayFluoActionInitializer, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, GammaRayTelActionInitializer, DMXActionInitializer, B2ActionInitialization, B2ActionInitialization, B3aActionInitialization, B3bActionInitialization, B4aActionInitialization, B4bActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ElectronActionInitialization, LXeActionInitialization, OpNoviceActionInitialization, B2ActionInitialization, ActionInitialization, UltraActionInitializer, CCalActionInitializer, GammaKnifeActionInitialization, ActionInitialization, F04ActionInitialization, ActionInitialization, ExGflashActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, B4cActionInitialization, B4dActionInitialization, B1ConActionInitialization, B01ActionInitialization, B02ActionInitialization, B03ActionInitialization, GB01ActionInitialization, GB02ActionInitialization, GB04ActionInitialization, GB05ActionInitialization, GB06ActionInitialization, GB07ActionInitialization, G3toG4ActionInitialization, DicomActionInitialization, ActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, ExGflashActionInitialization, Par01ActionInitialization, ExTGActionInitialization, RE01ActionInitialization, RE02ActionInitialization, RE04ActionInitialization, RE05ActionInitialization, RE06ActionInitialization, HadrontherapyActionInitialization, G4HumanPhantomActionInitialization, FCALActionInitialization, B1ActionInitialization, B5ActionInitialization, GB03ActionInitialization, ExUCNActionInitialization, F05ActionInitialization, F06ActionInitialization, Dicom2ActionInitialization, G01ActionInitialization, G04ActionInitialization, B1ActionInitialization, ActionInitialization, STCyclotronActionInitialization, ActionInitialization, BrachyActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, and ActionInitialization.
Definition at line 35 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 35 of file G4VUserActionInitialization.cc
Referenced by G4MTRunManager::SetUserInitialization().
G4VSteppingVerbose * G4VUserActionInitialization::InitializeSteppingVerbose () const virtual
Reimplemented in F01ActionInitialization, F02ActionInitialization, F03ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, ActionInitialization, PurgMagActionInitializer, XrayFluoActionInitializer, F04ActionInitialization, F05ActionInitialization, and FCALActionInitialization.
Definition at line 56 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VUserActionInitialization.cc
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
void G4VUserActionInitialization::SetUserAction (G4VUserPrimaryGeneratorAction * action) const protected
Definition at line 38 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VUserActionInitialization.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
Referenced by BrachyActionInitialization::Build(), GB03ActionInitialization::Build(), STCyclotronActionInitialization::Build(), RE01ActionInitialization::Build(), RE02ActionInitialization::Build(), RE04ActionInitialization::Build(), RE05ActionInitialization::Build(), RE06ActionInitialization::Build(), XActionInitialization::Build(), FCALActionInitialization::Build(), F05ActionInitialization::Build(), F06ActionInitialization::Build(), Dicom2ActionInitialization::Build(), UltraActionInitializer::Build(), B5ActionInitialization::Build(), G01ActionInitialization::Build(), G04ActionInitialization::Build(), RE03ActionInitialization::Build(), HadrontherapyActionInitialization::Build(), B1ActionInitialization::Build(), CCalActionInitializer::Build(), G4HumanPhantomActionInitialization::Build(), ExUCNActionInitialization::Build(), G3toG4ActionInitialization::Build(), DicomActionInitialization::Build(), GammaRayTelActionInitializer::Build(), B4cActionInitialization::Build(), B4dActionInitialization::Build(), DMXActionInitializer::Build(), ExGflashActionInitialization::Build(), Par01ActionInitialization::Build(), B1ConActionInitialization::Build(), ExTGActionInitialization::Build(), B01ActionInitialization::Build(), B02ActionInitialization::Build(), B03ActionInitialization::Build(), GB01ActionInitialization::Build(), GB02ActionInitialization::Build(), GB04ActionInitialization::Build(), GB05ActionInitialization::Build(), GB06ActionInitialization::Build(), GB07ActionInitialization::Build(), F04ActionInitialization::Build(), PurgMagActionInitializer::Build(), GammaKnifeActionInitialization::Build(), XrayFluoActionInitializer::Build(), B3aActionInitialization::Build(), B3bActionInitialization::Build(), B4aActionInitialization::Build(), B4bActionInitialization::Build(), ElectronActionInitialization::Build(), LXeActionInitialization::Build(), OpNoviceActionInitialization::Build(), B2ActionInitialization::Build(), ActionInitialization::Build(), XrayTelActionInitializer::Build(), WLSActionInitialization::Build(), doiPETActionInitialization::Build(), F01ActionInitialization::Build(), F03ActionInitialization::Build(), F02ActionInitialization::Build(), FFActionInitialization::Build(), TSActionInitialization::Build(), Par02ActionInitialization::Build(), STCyclotronActionInitialization::BuildForMaster(), FCALActionInitialization::BuildForMaster(), Dicom2ActionInitialization::BuildForMaster(), HadrontherapyActionInitialization::BuildForMaster(), B1ActionInitialization::BuildForMaster(), B5ActionInitialization::BuildForMaster(), ExUCNActionInitialization::BuildForMaster(), B01ActionInitialization::BuildForMaster(), DicomActionInitialization::BuildForMaster(), B4dActionInitialization::BuildForMaster(), B4cActionInitialization::BuildForMaster(), ExTGActionInitialization::BuildForMaster(), RE06ActionInitialization::BuildForMaster(), RE01ActionInitialization::BuildForMaster(), B02ActionInitialization::BuildForMaster(), B03ActionInitialization::BuildForMaster(), RE05ActionInitialization::BuildForMaster(), RE02ActionInitialization::BuildForMaster(), B1ConActionInitialization::BuildForMaster(), UltraActionInitializer::BuildForMaster(), GammaKnifeActionInitialization::BuildForMaster(), F04ActionInitialization::BuildForMaster(), ElectronActionInitialization::BuildForMaster(), DMXActionInitializer::BuildForMaster(), B3aActionInitialization::BuildForMaster(), GammaRayTelActionInitializer::BuildForMaster(), B4bActionInitialization::BuildForMaster(), OpNoviceActionInitialization::BuildForMaster(), LXeActionInitialization::BuildForMaster(), B4aActionInitialization::BuildForMaster(), B3bActionInitialization::BuildForMaster(), B2ActionInitialization::BuildForMaster(), ActionInitialization::BuildForMaster(), PurgMagActionInitializer::BuildForMaster(), XrayFluoActionInitializer::BuildForMaster(), XrayTelActionInitializer::BuildForMaster(), WLSActionInitialization::BuildForMaster(), doiPETActionInitialization::BuildForMaster(), FFActionInitialization::BuildForMaster(), TSActionInitialization::BuildForMaster(), and Par02ActionInitialization::BuildForMaster().
void G4VUserActionInitialization::SetUserAction (G4UserRunAction * action) const protected
Definition at line 41 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VUserActionInitialization.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
void G4VUserActionInitialization::SetUserAction (G4UserEventAction * action) const protected
Definition at line 44 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VUserActionInitialization.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
void G4VUserActionInitialization::SetUserAction (G4UserStackingAction * action) const protected
Definition at line 47 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VUserActionInitialization.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
void G4VUserActionInitialization::SetUserAction (G4UserTrackingAction * action) const protected
Definition at line 50 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VUserActionInitialization.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
void G4VUserActionInitialization::SetUserAction (G4UserSteppingAction * action) const protected
Definition at line 53 of file G4VUserActionInitialization.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VUserActionInitialization.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VUserActionInitialization.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VUserActionInitialization.cc