ECCE @ EIC Software: G4empCrossSection Class Reference
G4empCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4empCrossSection.hh>
Public Member Functions
G4empCrossSection (const G4String &nam="")
virtual ~G4empCrossSection ()
std::vector< G4double > GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)
G4double CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass, const G4Material *mat)
std::vector< G4double > Probabilities (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)
void SetTotalCS (G4double)
Public Member Functions inherited from G4VhShellCrossSection
G4VhShellCrossSection (const G4String &xname="")
virtual ~G4VhShellCrossSection ()
G4int SelectRandomShell (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)
const G4String & GetName () const
Private Member Functions
G4empCrossSection (const G4empCrossSection &)
G4empCrossSection & operator= (const G4empCrossSection &right)
Private Attributes
G4double totalCS
G4int flag
G4PaulKxsModel * paulShellK
G4OrlicLiXsModel * orlicShellLi
Detailed Description
Definition at line 52 of file G4empCrossSection.hh.
View newest version in sPHENIX GitHub at line 52 of file G4empCrossSection.hh
Constructor & Destructor Documentation
G4empCrossSection::G4empCrossSection (const G4String & nam = "")
Definition at line 42 of file G4empCrossSection.cc.
View newest version in sPHENIX GitHub at line 42 of file G4empCrossSection.cc
References flag, G4cout, G4endl, orlicShellLi, and paulShellK.
G4empCrossSection::~G4empCrossSection () virtual
Definition at line 63 of file G4empCrossSection.cc.
View newest version in sPHENIX GitHub at line 63 of file G4empCrossSection.cc
References orlicShellLi, and paulShellK.
G4empCrossSection::G4empCrossSection (const G4empCrossSection &) private
Member Function Documentation
G4double G4empCrossSection::CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass, const G4Material * mat) virtual
Implements G4VhShellCrossSection.
Definition at line 105 of file G4empCrossSection.cc.
View newest version in sPHENIX GitHub at line 105 of file G4empCrossSection.cc
References G4PaulKxsModel::CalculateKCrossSection(), G4OrlicLiXsModel::CalculateL1CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), fKShell, fL1Shell, fL2Shell, fL3Shell, flag, G4ParticleDefinition::GetPDGMass(), orlicShellLi, paulShellK, and G4Proton::Proton().
std::vector< G4double > G4empCrossSection::GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material * mat) virtual
Implements G4VhShellCrossSection.
Definition at line 69 of file G4empCrossSection.cc.
View newest version in sPHENIX GitHub at line 69 of file G4empCrossSection.cc
References G4PaulKxsModel::CalculateKCrossSection(), G4OrlicLiXsModel::CalculateL1CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), flag, G4ParticleDefinition::GetPDGMass(), orlicShellLi, paulShellK, and G4Proton::Proton().
Referenced by Probabilities().
G4empCrossSection& G4empCrossSection::operator= (const G4empCrossSection & right) private
std::vector< G4double > G4empCrossSection::Probabilities (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material * mat) virtual
Implements G4VhShellCrossSection.
Definition at line 136 of file G4empCrossSection.cc.
View newest version in sPHENIX GitHub at line 136 of file G4empCrossSection.cc
References GetCrossSection(), and totalCS.
void G4empCrossSection::SetTotalCS (G4double val) virtual
Reimplemented from G4VhShellCrossSection.
Definition at line 158 of file G4empCrossSection.cc.
View newest version in sPHENIX GitHub at line 158 of file G4empCrossSection.cc
References totalCS.
Member Data Documentation
G4int G4empCrossSection::flag private
Definition at line 85 of file G4empCrossSection.hh.
View newest version in sPHENIX GitHub at line 85 of file G4empCrossSection.hh
Referenced by CrossSection(), G4empCrossSection(), and GetCrossSection().
G4OrlicLiXsModel* G4empCrossSection::orlicShellLi private
Definition at line 88 of file G4empCrossSection.hh.
View newest version in sPHENIX GitHub at line 88 of file G4empCrossSection.hh
Referenced by CrossSection(), G4empCrossSection(), GetCrossSection(), and ~G4empCrossSection().
G4PaulKxsModel* G4empCrossSection::paulShellK private
Definition at line 87 of file G4empCrossSection.hh.
View newest version in sPHENIX GitHub at line 87 of file G4empCrossSection.hh
Referenced by CrossSection(), G4empCrossSection(), GetCrossSection(), and ~G4empCrossSection().
G4double G4empCrossSection::totalCS private
Definition at line 84 of file G4empCrossSection.hh.
View newest version in sPHENIX GitHub at line 84 of file G4empCrossSection.hh
Referenced by Probabilities(), and SetTotalCS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4empCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4empCrossSection.cc