ECCE @ EIC Software: G4DNAEmfietzoglouIonisationModel Class Reference
G4DNAEmfietzoglouIonisationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAEmfietzoglouIonisationModel.hh>
Public Member Functions
G4DNAEmfietzoglouIonisationModel (const G4ParticleDefinition *p=0, const G4String &nam="DNAEmfietzoglouIonisationModel")
virtual ~G4DNAEmfietzoglouIonisationModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &=*(new G4DataVector()))
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
G4double DifferentialCrossSection (G4ParticleDefinition *aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
void SelectFasterComputation (G4bool input)
void SelectStationary (G4bool input)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Types
typedef std::map< G4String,
G4String, std::less< G4String > > MapFile
typedef std::map< G4String,
G4DNACrossSectionDataSet
*, std::less< G4String > > MapData
typedef std::map< G4double,
std::map< G4double, G4double > > TriDimensionMap
typedef std::map< G4double,
std::vector< G4double > > VecMap
Private Member Functions
G4double RandomizeEjectedElectronEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomTransferedEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
G4int RandomSelect (G4double energy, const G4String &particle)
G4DNAEmfietzoglouIonisationModel & operator= (const G4DNAEmfietzoglouIonisationModel &right)
G4DNAEmfietzoglouIonisationModel (const G4DNAEmfietzoglouIonisationModel &)
Private Attributes
G4bool fasterCode
G4bool statCode
const std::vector< G4double > * fpMolWaterDensity
G4VAtomDeexcitation * fAtomDeexcitation
std::map< G4String, G4double,
std::less< G4String > > lowEnergyLimit
std::map< G4String, G4double,
std::less< G4String > > highEnergyLimit
G4bool isInitialised
G4int verboseLevel
MapFile tableFile
MapData tableData
G4DNAEmfietzoglouWaterIonisationStructure waterStructure
TriDimensionMap eDiffCrossSectionData [6]
TriDimensionMap eNrjTransfData [6]
TriDimensionMap pDiffCrossSectionData [6]
std::vector< G4double > eTdummyVec
VecMap eVecm
VecMap eProbaShellMap [6]
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 52 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DNAEmfietzoglouIonisationModel.hh
Member Typedef Documentation
typedef std::map<G4String, G4DNACrossSectionDataSet*, std::less<G4String> > G4DNAEmfietzoglouIonisationModel::MapData private
Definition at line 114 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4DNAEmfietzoglouIonisationModel.hh
typedef std::map<G4String, G4String, std::less<G4String> > G4DNAEmfietzoglouIonisationModel::MapFile private
Definition at line 111 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4DNAEmfietzoglouIonisationModel.hh
typedef std::map<G4double, std::map<G4double, G4double> > G4DNAEmfietzoglouIonisationModel::TriDimensionMap private
Definition at line 152 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4DNAEmfietzoglouIonisationModel.hh
typedef std::map<G4double, std::vector<G4double> > G4DNAEmfietzoglouIonisationModel::VecMap private
Definition at line 161 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4DNAEmfietzoglouIonisationModel.hh
Constructor & Destructor Documentation
G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel (const G4ParticleDefinition * p = 0, const G4String & nam = "DNAEmfietzoglouIonisationModel")
Definition at line 52 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4DNAEmfietzoglouIonisationModel.cc
References eV, fasterCode, fAtomDeexcitation, fParticleChangeForGamma, fpMolWaterDensity, G4cout, G4endl, keV, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), statCode, and verboseLevel.
G4DNAEmfietzoglouIonisationModel::~G4DNAEmfietzoglouIonisationModel () virtual
Definition at line 92 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 92 of file G4DNAEmfietzoglouIonisationModel.cc
References eVecm, pos(), and tableData.
G4DNAEmfietzoglouIonisationModel::G4DNAEmfietzoglouIonisationModel (const G4DNAEmfietzoglouIonisationModel &) private
Member Function Documentation
G4double G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 239 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 239 of file G4DNAEmfietzoglouIonisationModel.cc
References cm, G4Electron::ElectronDefinition(), eV, FatalException, G4DNACrossSectionDataSet::FindValue(), G4cout, G4endl, G4Exception(), G4Material::GetIndex(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), pos(), tableData, and verboseLevel.
G4double G4DNAEmfietzoglouIonisationModel::DifferentialCrossSection (G4ParticleDefinition * aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
Definition at line 555 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 555 of file G4DNAEmfietzoglouIonisationModel.cc
References e, eDiffCrossSectionData, G4Electron::ElectronDefinition(), eTdummyVec, eV, eVecm, G4DNAEmfietzoglouWaterIonisationStructure::IonisationEnergy(), k, QuadInterpolator(), t1, t2, and waterStructure.
Referenced by RandomizeEjectedElectronEnergy().
void G4DNAEmfietzoglouIonisationModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector & = *(new G4DataVector())) virtual
Implements G4VEmModel.
Definition at line 111 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 111 of file G4DNAEmfietzoglouIonisationModel.cc
References G4LossTableManager::AtomDeexcitation(), eDiffCrossSectionData, G4InuclParticleNames::electron, G4Electron::ElectronDefinition(), eNrjTransfData, eProbaShellMap, eTdummyVec, eV, eVecm, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, fpMolWaterDensity, G4cout, G4endl, G4Exception(), G4Material::GetMaterial(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4LossTableManager::Instance(), G4DNAMolecularMaterial::Instance(), isInitialised, keV, G4DNACrossSectionDataSet::LoadData(), G4VEmModel::LowEnergyLimit(), m, tableData, tableFile, and verboseLevel.
G4double G4DNAEmfietzoglouIonisationModel::Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 658 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 658 of file G4DNAEmfietzoglouIonisationModel.cc
References a, b, d1, d2, e1, and fasterCode.
Referenced by QuadInterpolator(), and RandomTransferedEnergy().
G4DNAEmfietzoglouIonisationModel& G4DNAEmfietzoglouIonisationModel::operator= (const G4DNAEmfietzoglouIonisationModel & right) private
G4double G4DNAEmfietzoglouIonisationModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 723 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 723 of file G4DNAEmfietzoglouIonisationModel.cc
References Interpolate().
Referenced by DifferentialCrossSection(), and RandomTransferedEnergy().
G4double G4DNAEmfietzoglouIonisationModel::RandomizeEjectedElectronEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 445 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 445 of file G4DNAEmfietzoglouIonisationModel.cc
References DifferentialCrossSection(), G4Electron::ElectronDefinition(), eV, G4UniformRand, G4DNAEmfietzoglouWaterIonisationStructure::IonisationEnergy(), k, Acts::Test::step(), and waterStructure.
Referenced by SampleSecondaries().
G4double G4DNAEmfietzoglouIonisationModel::RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 808 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 808 of file G4DNAEmfietzoglouIonisationModel.cc
References eV, G4DNAEmfietzoglouWaterIonisationStructure::IonisationEnergy(), RandomTransferedEnergy(), and waterStructure.
Referenced by SampleSecondaries().
G4int G4DNAEmfietzoglouIonisationModel::RandomSelect (G4double energy, const G4String & particle) private
Definition at line 749 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 749 of file G4DNAEmfietzoglouIonisationModel.cc
References FatalException, G4VEMDataSet::FindValue(), G4Exception(), G4UniformRand, G4DNACrossSectionDataSet::GetComponent(), n, G4DNACrossSectionDataSet::NumberOfComponents(), pos(), and tableData.
Referenced by SampleSecondaries().
G4double G4DNAEmfietzoglouIonisationModel::RandomTransferedEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 830 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 830 of file G4DNAEmfietzoglouIonisationModel.cc
References e, G4Electron::ElectronDefinition(), eNrjTransfData, eProbaShellMap, eTdummyVec, G4UniformRand, Interpolate(), k, k1, k2, and QuadInterpolator().
Referenced by RandomizeEjectedElectronEnergyFromCumulatedDcs().
void G4DNAEmfietzoglouIonisationModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * particle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 298 of file G4DNAEmfietzoglouIonisationModel.cc.
View newest version in sPHENIX GitHub at line 298 of file G4DNAEmfietzoglouIonisationModel.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4DNAChemistryManager::CreateWaterMolecule(), eIonizedMolecule, G4Electron::Electron(), source.hepunit::electron_mass_c2, eV, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, G4cout, G4endl, G4Exception(), G4VAtomDeexcitation::GenerateParticles(), G4VEmModel::GetAngularDistribution(), G4VAtomDeexcitation::GetAtomicShell(), G4ParticleChangeForGamma::GetCurrentTrack(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4VEmModel::HighEnergyLimit(), G4DNAChemistryManager::Instance(), G4DNAEmfietzoglouWaterIonisationStructure::IonisationEnergy(), k, G4VEmModel::LowEnergyLimit(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), RandomSelect(), G4VEmAngularDistribution::SampleDirectionForShell(), CLHEP::Hep3Vector::set(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), statCode, CLHEP::Hep3Vector::unit(), verboseLevel, waterStructure, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4DNAEmfietzoglouIonisationModel::SelectFasterComputation (G4bool input) inline
Definition at line 178 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 178 of file G4DNAEmfietzoglouIonisationModel.hh
References fasterCode.
Referenced by G4EmDNAPhysics_option5::ConstructProcess().
void G4DNAEmfietzoglouIonisationModel::SelectStationary (G4bool input) inline
Definition at line 185 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4DNAEmfietzoglouIonisationModel.hh
References statCode.
Member Data Documentation
TriDimensionMap G4DNAEmfietzoglouIonisationModel::eDiffCrossSectionData[6] private
Definition at line 154 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by DifferentialCrossSection(), and Initialise().
TriDimensionMap G4DNAEmfietzoglouIonisationModel::eNrjTransfData[6] private
Definition at line 155 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by Initialise(), and RandomTransferedEnergy().
VecMap G4DNAEmfietzoglouIonisationModel::eProbaShellMap[6] private
Definition at line 165 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by Initialise(), and RandomTransferedEnergy().
std::vector<G4double> G4DNAEmfietzoglouIonisationModel::eTdummyVec private
Definition at line 159 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and RandomTransferedEnergy().
VecMap G4DNAEmfietzoglouIonisationModel::eVecm private
Definition at line 163 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and ~G4DNAEmfietzoglouIonisationModel().
G4bool G4DNAEmfietzoglouIonisationModel::fasterCode private
Definition at line 93 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 93 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by G4DNAEmfietzoglouIonisationModel(), Initialise(), Interpolate(), SampleSecondaries(), and SelectFasterComputation().
G4VAtomDeexcitation* G4DNAEmfietzoglouIonisationModel::fAtomDeexcitation private
Definition at line 101 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by G4DNAEmfietzoglouIonisationModel(), Initialise(), and SampleSecondaries().
G4ParticleChangeForGamma* G4DNAEmfietzoglouIonisationModel::fParticleChangeForGamma protected
Definition at line 89 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by G4DNAEmfietzoglouIonisationModel(), Initialise(), and SampleSecondaries().
const std::vector<G4double>* G4DNAEmfietzoglouIonisationModel::fpMolWaterDensity private
Definition at line 98 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by G4DNAEmfietzoglouIonisationModel(), and Initialise().
std::map<G4String, G4double, std::less<G4String> > G4DNAEmfietzoglouIonisationModel::highEnergyLimit private
Definition at line 104 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNAEmfietzoglouIonisationModel.hh
G4bool G4DNAEmfietzoglouIonisationModel::isInitialised private
Definition at line 106 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by Initialise().
std::map<G4String, G4double, std::less<G4String> > G4DNAEmfietzoglouIonisationModel::lowEnergyLimit private
Definition at line 103 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4DNAEmfietzoglouIonisationModel.hh
TriDimensionMap G4DNAEmfietzoglouIonisationModel::pDiffCrossSectionData[6] private
Definition at line 157 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4DNAEmfietzoglouIonisationModel.hh
G4bool G4DNAEmfietzoglouIonisationModel::statCode private
Definition at line 95 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 95 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by G4DNAEmfietzoglouIonisationModel(), SampleSecondaries(), and SelectStationary().
MapData G4DNAEmfietzoglouIonisationModel::tableData private
Definition at line 115 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by CrossSectionPerVolume(), Initialise(), RandomSelect(), and ~G4DNAEmfietzoglouIonisationModel().
MapFile G4DNAEmfietzoglouIonisationModel::tableFile private
Definition at line 112 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by Initialise().
G4int G4DNAEmfietzoglouIonisationModel::verboseLevel private
Definition at line 107 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel(), Initialise(), and SampleSecondaries().
G4DNAEmfietzoglouWaterIonisationStructure G4DNAEmfietzoglouIonisationModel::waterStructure private
Definition at line 119 of file G4DNAEmfietzoglouIonisationModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4DNAEmfietzoglouIonisationModel.hh
Referenced by DifferentialCrossSection(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAEmfietzoglouIonisationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAEmfietzoglouIonisationModel.cc