ECCE @ EIC Software: G4VParticleChange Class Reference
G4VParticleChange Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4VParticleChange.hh>
Public Member Functions
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
virtual G4Step * UpdateStepForPostStep (G4Step *Step)
virtual void Initialize (const G4Track &)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
virtual G4bool CheckIt (const G4Track &)
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Protected Attributes
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 93 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VParticleChange.hh
Constructor & Destructor Documentation
G4VParticleChange::G4VParticleChange ()
Definition at line 47 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VParticleChange.cc
References debugFlag, and theListOfSecondaries.
G4VParticleChange::~G4VParticleChange () virtual
Definition at line 72 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VParticleChange.cc
References G4cout, theListOfSecondaries, theNumberOfSecondaries, and verboseLevel.
G4VParticleChange::G4VParticleChange (const G4VParticleChange & right) protected
Definition at line 88 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 88 of file G4VParticleChange.cc
References G4FastVector< Type, N >::SetElement(), theListOfSecondaries, and theNumberOfSecondaries.
Member Function Documentation
void G4VParticleChange::AddSecondary (G4Track * aSecondary)
Definition at line 170 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 170 of file G4VParticleChange.cc
References CheckSecondary(), debugFlag, fSetSecondaryWeightByProcess, G4cout, G4endl, G4Exception(), JustWarning, G4FastVector< Type, N >::SetElement(), G4Track::SetWeight(), theListOfSecondaries, theNumberOfSecondaries, theParentWeight, theSizeOftheListOfSecondaries, and verboseLevel.
Referenced by G4ParticleChangeForGamma::AddSecondary(), G4ParticleChange::AddSecondary(), G4eplusAnnihilation::AtRestDoIt(), G4FastStep::CreateSecondaryTrack(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4VEnergyLossProcess::FillSecondariesAlongStep(), SplitProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
G4bool G4VParticleChange::CheckIt (const G4Track &) virtual
Reimplemented in G4FastStep, G4ParticleChange, G4ParticleChangeForDecay, G4ParticleChangeForLoss, G4ParticleChangeForMSC, and G4ParticleChangeForGamma.
Definition at line 315 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 315 of file G4VParticleChange.cc
References accuracyForException, accuracyForWarning, DumpInfo(), EventMustBeAborted, G4cout, G4endl, G4Exception(), G4ThreadLocal, m, MeV, mm, theLocalEnergyDeposit, and theTrueStepLength.
Referenced by G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), and G4FastStep::CheckIt().
G4bool G4VParticleChange::CheckSecondary (G4Track & aTrack) protected
Definition at line 397 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 397 of file G4VParticleChange.cc
References accuracyForException, accuracyForWarning, DumpInfo(), EventMustBeAborted, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4Track::GetDefinition(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), m, MeV, ns, G4Track::SetKineticEnergy(), G4Track::SetMomentumDirection(), theParentGlobalTime, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by AddSecondary().
void G4VParticleChange::Clear ()
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4MuonicAtomDecay::DecayIt(), CexmcHadronicProcess::FillTotalResult(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), CexmcHadronicProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
void G4VParticleChange::ClearDebugFlag ()
Referenced by G4ErrorEnergyLoss::AlongStepDoIt().
void G4VParticleChange::DumpInfo () const virtual
Reimplemented in G4FastStep, G4ParticleChange, G4ParticleChangeForLoss, G4ParticleChangeForTransport, G4ParticleChangeForDecay, G4ParticleChangeForMSC, and G4ParticleChangeForGamma.
Definition at line 251 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 251 of file G4VParticleChange.cc
References fAlive, fKillTrackAndSecondaries, fPostponeToNextEvent, fStopAndKill, fStopButAlive, fSuspend, G4cout, G4endl, GetSecondary(), MeV, mm, theFirstStepInVolume, theLastStepInVolume, theLocalEnergyDeposit, theNonIonizingEnergyDeposit, theNumberOfSecondaries, theStatusChange, theSteppingControlFlag, and theTrueStepLength.
Referenced by CheckIt(), CheckSecondary(), G4ParticleChangeForGamma::DumpInfo(), G4ParticleChangeForMSC::DumpInfo(), G4ParticleChangeForDecay::DumpInfo(), G4ParticleChangeForLoss::DumpInfo(), G4ParticleChange::DumpInfo(), G4FastStep::DumpInfo(), and G4SteppingVerbose::VerboseParticleChange().
G4double G4VParticleChange::GetAccuracyForException () const protected
Definition at line 512 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 512 of file G4VParticleChange.cc
References accuracyForException.
Referenced by G4FastStep::CheckIt().
G4double G4VParticleChange::GetAccuracyForWarning () const protected
Definition at line 507 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 507 of file G4VParticleChange.cc
References accuracyForWarning.
Referenced by G4FastStep::CheckIt().
G4bool G4VParticleChange::GetDebugFlag () const
G4bool G4VParticleChange::GetFirstStepInVolume () const
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep().
G4bool G4VParticleChange::GetLastStepInVolume () const
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep().
G4double G4VParticleChange::GetLocalEnergyDeposit () const
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess::PostStepDoIt(), and G4VEnergyLossProcess::PostStepDoIt().
G4double G4VParticleChange::GetNonIonizingEnergyDeposit () const
G4int G4VParticleChange::GetNumberOfSecondaries () const
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
G4double G4VParticleChange::GetParentWeight () const
Referenced by G4VEnergyLossProcess::AlongStepDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4VEmProcess::PostStepDoIt(), and G4VEnergyLossProcess::PostStepDoIt().
G4Track* G4VParticleChange::GetSecondary (G4int anIndex) const
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4HadronicProcess::CheckEnergyMomentumConservation(), DumpInfo(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), SplitProcess::PostStepDoIt(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
G4SteppingControl G4VParticleChange::GetSteppingControl () const
G4TrackStatus G4VParticleChange::GetTrackStatus () const
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ParticleChange::CheckIt(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokePSDIP(), CexmcHadronicProcess::PostStepDoIt(), G4FastSimulationManagerProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4BiasingProcessInterface::PostStepDoIt().
G4double G4VParticleChange::GetTrueStepLength () const
G4int G4VParticleChange::GetVerboseLevel () const
G4double G4VParticleChange::GetWeight () const
Referenced by G4BOptnLeadingParticle::ApplyFinalStateBiasing().
virtual void G4VParticleChange::Initialize (const G4Track &) virtual
Reimplemented in G4FastStep, G4ParticleChange, G4ParticleChangeForDecay, G4ParticleChangeForTransport, G4ParticleChangeForMSC, and G4ParticleChangeForNothing.
Referenced by G4ParallelWorldProcess::AlongStepDoIt(), G4WeightCutOffProcess::AlongStepDoIt(), G4ScoreSplittingProcess::AlongStepDoIt(), G4ParallelWorldScoringProcess::AlongStepDoIt(), G4ImportanceProcess::AlongStepDoIt(), G4WeightWindowProcess::AlongStepDoIt(), G4FastSimulationManagerProcess::AlongStepDoIt(), G4ParallelWorldProcess::AtRestDoIt(), G4ScoreSplittingProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4ParticleChangeForDecay::Initialize(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), G4VErrorLimitProcess::PostStepDoIt(), G4ElectronCapture::PostStepDoIt(), G4ErrorTrackLengthTarget::PostStepDoIt(), G4LowECapture::PostStepDoIt(), G4NeutronKiller::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), and G4ScreenedNuclearRecoil::PostStepDoIt().
void G4VParticleChange::InitializeLocalEnergyDeposit (const G4Track &) protected
void G4VParticleChange::InitializeParentGlobalTime (const G4Track &) protected
void G4VParticleChange::InitializeParentWeight (const G4Track &) protected
void G4VParticleChange::InitializeSecondaries (const G4Track &) protected
Referenced by G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), and G4ParticleChangeForLoss::InitializeForPostStep().
void G4VParticleChange::InitializeStatusChange (const G4Track &) protected
void G4VParticleChange::InitializeStepInVolumeFlags (const G4Track &) protected
void G4VParticleChange::InitializeSteppingControl (const G4Track &) protected
void G4VParticleChange::InitializeTrueStepLength (const G4Track &) protected
G4bool G4VParticleChange::IsParentWeightSetByProcess () const
Definition at line 526 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 526 of file G4VParticleChange.cc
G4bool G4VParticleChange::IsSecondaryWeightSetByProcess () const
G4bool G4VParticleChange::operator!= (const G4VParticleChange & right) const
Definition at line 165 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 165 of file G4VParticleChange.cc
G4VParticleChange & G4VParticleChange::operator= (const G4VParticleChange & right) protected
Definition at line 115 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 115 of file G4VParticleChange.cc
References debugFlag, fSetSecondaryWeightByProcess, G4cout, isParentWeightProposed, G4FastVector< Type, N >::SetElement(), theFirstStepInVolume, theLastStepInVolume, theListOfSecondaries, theLocalEnergyDeposit, theNonIonizingEnergyDeposit, theNumberOfSecondaries, theParentGlobalTime, theParentWeight, theStatusChange, theSteppingControlFlag, theTrueStepLength, and verboseLevel.
Referenced by G4FastStep::operator=().
G4bool G4VParticleChange::operator== (const G4VParticleChange & right) const
Definition at line 159 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 159 of file G4VParticleChange.cc
void G4VParticleChange::ProposeFirstStepInVolume (G4bool flag)
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4Transportation::PostStepDoIt(), and G4CoupledTransportation::PostStepDoIt().
void G4VParticleChange::ProposeLastStepInVolume (G4bool flag)
Referenced by G4Transportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), and G4ITTransportation::PostStepDoIt().
void G4VParticleChange::ProposeLocalEnergyDeposit (G4double anEnergyPart)
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4NuclearStopping::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4DNAMolecularDissociation::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4OpBoundaryProcess::DoAbsorption(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepDoIt(), DMXSpecialCuts::PostStepDoIt(), G4SpecialCuts::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4ElectronCapture::PostStepDoIt(), G4LowECapture::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSIonisationModel::SampleSecondaries(), G4LEPTSPositroniumModel::SampleSecondaries(), G4LEPTSVibExcitationModel::SampleSecondaries(), G4LEPTSRotExcitationModel::SampleSecondaries(), G4LEPTSAttachmentModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNAMeltonAttachmentModel::SampleSecondaries(), G4DNASancheExcitationModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4DNATransformElectronModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
void G4VParticleChange::ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
Referenced by G4NuclearStopping::AlongStepDoIt(), G4PhononReflection::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
void G4VParticleChange::ProposeParentWeight (G4double finalWeight)
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4AdjointPhotoElectricModel::CorrectPostStepWeight(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4VEmAdjointModel::CorrectPostStepWeight(), G4BOptnCloning::GenerateBiasingFinalState(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), and G4AdjointeIonisationModel::SampleSecondaries().
void G4VParticleChange::ProposeSteppingControl (G4SteppingControl StepControlFlag)
Referenced by G4ScoreSplittingProcess::PostStepDoIt().
void G4VParticleChange::ProposeTrackStatus (G4TrackStatus status)
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4BiasingProcessInterface::AlongStepDoIt(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4DNAMolecularDissociation::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4DNABrownianTransportation::Diffusion(), G4OpBoundaryProcess::DoAbsorption(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4FastStep::KillPrimaryTrack(), G4ImportanceProcess::KillTrack(), G4WeightWindowProcess::KillTrack(), G4DNAElectronHoleRecombination::MakeReaction(), PrtOpBoundaryProcess::PostStepDoIt(), G4EicDircOpBoundaryProcess::PostStepDoIt(), G4PhononDownconversion::PostStepDoIt(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepDoIt(), G4SpecialCuts::PostStepDoIt(), DMXSpecialCuts::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4DNASecondOrderReaction::PostStepDoIt(), G4ElectronCapture::PostStepDoIt(), G4LowECapture::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4NeutronKiller::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNLoss::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4FastSimulationManagerProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4BiasingProcessInterface::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSPositroniumModel::SampleSecondaries(), G4LEPTSAttachmentModel::SampleSecondaries(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNAMeltonAttachmentModel::SampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4DNATransformElectronModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4eeToHadronsMultiModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
void G4VParticleChange::ProposeTrueStepLength (G4double truePathLength)
Referenced by G4ITTransportation::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), and G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
void G4VParticleChange::ProposeWeight (G4double finalWeight)
Referenced by G4VEnergyLossProcess::AlongStepDoIt(), G4EmBiasingManager::ApplyDirectionalSplitting(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4SamplingPostStepAction::DoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4SamplingPostStepAction::Split().
void G4VParticleChange::SetDebugFlag ()
void G4VParticleChange::SetNumberOfSecondaries (G4int totSecondaries)
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4DNAMolecularDissociation::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4SingleScatter::DoCollisionStep(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4VEnergyLossProcess::FillSecondariesAlongStep(), CexmcHadronicProcess::FillTotalResult(), G4BOptnCloning::GenerateBiasingFinalState(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4PhononScattering::PostStepDoIt(), SplitProcess::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4SamplingPostStepAction::Split(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
void G4VParticleChange::SetParentWeightByProcess (G4bool)
Definition at line 521 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 521 of file G4VParticleChange.cc
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4AdjointPhotoElectricModel::CorrectPostStepWeight(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4VEmAdjointModel::CorrectPostStepWeight(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), and G4AdjointeIonisationModel::SampleSecondaries().
void G4VParticleChange::SetSecondaryWeightByProcess (G4bool)
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4AdjointPhotoElectricModel::CorrectPostStepWeight(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4VEmAdjointModel::CorrectPostStepWeight(), CexmcHadronicProcess::FillTotalResult(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4BOptnCloning::GenerateBiasingFinalState(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4HadronicProcess::InitialiseLocal(), SplitProcess::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4BiasingProcessInterface::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), and G4AdjointeIonisationModel::SampleSecondaries().
void G4VParticleChange::SetVerboseLevel (G4int vLevel)
Referenced by SplitProcess::PostStepDoIt().
G4Step * G4VParticleChange::UpdateStepForAlongStep (G4Step * Step) virtual
Reimplemented in G4ParticleChange, G4ParticleChangeForMSC, G4ParticleChangeForTransport, G4ParticleChangeForLoss, G4ParticleChangeForOccurenceBiasing, and G4ParticleChangeForNothing.
Definition at line 227 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 227 of file G4VParticleChange.cc
References G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetWeight(), isParentWeightProposed, G4StepPoint::SetWeight(), theParentWeight, and UpdateStepInfo().
Referenced by G4SteppingManager::InvokeAlongStepDoItProcs(), and G4ParticleChangeForOccurenceBiasing::UpdateStepForAlongStep().
G4Step * G4VParticleChange::UpdateStepForAtRest (G4Step * Step) virtual
Reimplemented in G4FastStep, G4ParticleChange, G4ParticleChangeForDecay, G4ParticleChangeForTransport, G4ParticleChangeForGamma, G4ParticleChangeForOccurenceBiasing, and G4ParticleChangeForNothing.
Definition at line 218 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 218 of file G4VParticleChange.cc
References G4Step::GetPostStepPoint(), isParentWeightProposed, G4StepPoint::SetWeight(), theParentWeight, and UpdateStepInfo().
Referenced by G4SteppingManager::InvokeAtRestDoItProcs().
G4Step * G4VParticleChange::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented in G4FastStep, G4ParticleChange, G4ParticleChangeForDecay, G4ParticleChangeForTransport, G4ParticleChangeForMSC, G4ParticleChangeForLoss, G4ParticleChangeForGamma, G4ParticleChangeForOccurenceBiasing, and G4ParticleChangeForNothing.
Definition at line 238 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 238 of file G4VParticleChange.cc
References G4Step::GetPostStepPoint(), isParentWeightProposed, G4StepPoint::SetWeight(), theParentWeight, and UpdateStepInfo().
Referenced by G4SteppingManager::InvokePSDIP(), and G4ParticleChangeForOccurenceBiasing::UpdateStepForPostStep().
G4Step * G4VParticleChange::UpdateStepInfo (G4Step * Step) protected
Definition at line 201 of file G4VParticleChange.cc.
View newest version in sPHENIX GitHub at line 201 of file G4VParticleChange.cc
References G4Step::AddNonIonizingEnergyDeposit(), G4Step::AddTotalEnergyDeposit(), G4Step::ClearFirstStepFlag(), G4Step::ClearLastStepFlag(), G4Step::SetControlFlag(), G4Step::SetFirstStepFlag(), G4Step::SetLastStepFlag(), G4Step::SetStepLength(), theFirstStepInVolume, theLastStepInVolume, theLocalEnergyDeposit, theNonIonizingEnergyDeposit, theSteppingControlFlag, and theTrueStepLength.
Referenced by UpdateStepForAlongStep(), G4ParticleChangeForDecay::UpdateStepForAtRest(), UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForDecay::UpdateStepForPostStep(), UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
Member Data Documentation
const G4double G4VParticleChange::accuracyForException = 0.001 static protected
Definition at line 317 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 317 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), CheckIt(), CheckSecondary(), and GetAccuracyForException().
const G4double G4VParticleChange::accuracyForWarning = 1.0e-9 static protected
Definition at line 316 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 316 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), CheckIt(), CheckSecondary(), and GetAccuracyForWarning().
G4bool G4VParticleChange::debugFlag protected
Definition at line 313 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 313 of file G4VParticleChange.hh
Referenced by AddSecondary(), G4ParticleChangeForGamma::G4ParticleChangeForGamma(), G4ParticleChangeForLoss::G4ParticleChangeForLoss(), G4VParticleChange(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForPostStep(), and G4FastStep::UpdateStepForPostStep().
G4bool G4VParticleChange::fSetSecondaryWeightByProcess protected
Definition at line 285 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 285 of file G4VParticleChange.hh
Referenced by AddSecondary(), operator=(), and G4ParticleChangeForLoss::operator=().
G4bool G4VParticleChange::isParentWeightProposed protected
Definition at line 283 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 283 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForGamma::InitializeForPostStep(), operator=(), G4ParticleChangeForLoss::operator=(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForDecay::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), and UpdateStepForPostStep().
G4bool G4VParticleChange::theFirstStepInVolume protected
Definition at line 277 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 277 of file G4VParticleChange.hh
Referenced by DumpInfo(), operator=(), and UpdateStepInfo().
G4bool G4VParticleChange::theLastStepInVolume protected
Definition at line 278 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 278 of file G4VParticleChange.hh
Referenced by DumpInfo(), operator=(), and UpdateStepInfo().
G4TrackFastVector* G4VParticleChange::theListOfSecondaries protected
Definition at line 244 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 244 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForRadDecay::AddSecondary(), AddSecondary(), G4VParticleChange(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4FastStep::operator=(), and ~G4VParticleChange().
G4double G4VParticleChange::theLocalEnergyDeposit protected
Definition at line 259 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 259 of file G4VParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4FastStep::operator=(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and UpdateStepInfo().
G4double G4VParticleChange::theNonIonizingEnergyDeposit protected
Definition at line 268 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 268 of file G4VParticleChange.hh
Referenced by DumpInfo(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), operator=(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and UpdateStepInfo().
G4int G4VParticleChange::theNumberOfSecondaries protected
Definition at line 247 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 247 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForRadDecay::AddSecondary(), AddSecondary(), DumpInfo(), G4VParticleChange(), G4ParticleChangeForNothing::Initialize(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4FastStep::operator=(), and ~G4VParticleChange().
G4double G4VParticleChange::theParentGlobalTime protected
Definition at line 288 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 288 of file G4VParticleChange.hh
Referenced by CheckSecondary(), and operator=().
G4double G4VParticleChange::theParentWeight protected
Definition at line 281 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 281 of file G4VParticleChange.hh
Referenced by AddSecondary(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForDecay::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), and UpdateStepForPostStep().
G4int G4VParticleChange::theSizeOftheListOfSecondaries protected
Definition at line 250 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 250 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForRadDecay::AddSecondary(), AddSecondary(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForTransport::operator=(), and G4FastStep::operator=().
G4TrackStatus G4VParticleChange::theStatusChange protected
Definition at line 253 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 253 of file G4VParticleChange.hh
Referenced by DumpInfo(), G4ParticleChangeForNothing::Initialize(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4FastStep::operator=(), and G4ParticleChangeForMSC::UpdateStepForAlongStep().
G4SteppingControl G4VParticleChange::theSteppingControlFlag protected
Definition at line 256 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 256 of file G4VParticleChange.hh
Referenced by DumpInfo(), G4ParticleChangeForGamma::G4ParticleChangeForGamma(), G4ParticleChangeForLoss::G4ParticleChangeForLoss(), G4FastStep::Initialize(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4FastStep::operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), and UpdateStepInfo().
G4double G4VParticleChange::theTrueStepLength protected
Definition at line 273 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 273 of file G4VParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), operator=(), G4FastStep::operator=(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), and UpdateStepInfo().
G4int G4VParticleChange::verboseLevel protected
Definition at line 292 of file G4VParticleChange.hh.
View newest version in sPHENIX GitHub at line 292 of file G4VParticleChange.hh
Referenced by G4ParticleChangeForRadDecay::AddSecondary(), AddSecondary(), G4FastStep::G4FastStep(), G4ParticleChange::G4ParticleChange(), G4ParticleChangeForDecay::G4ParticleChangeForDecay(), G4ParticleChangeForGamma::G4ParticleChangeForGamma(), G4ParticleChangeForLoss::G4ParticleChangeForLoss(), G4ParticleChangeForMSC::G4ParticleChangeForMSC(), G4ParticleChangeForTransport::G4ParticleChangeForTransport(), G4ParticleChangeForDecay::operator=(), G4ParticleChangeForMSC::operator=(), G4ParticleChangeForTransport::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), operator=(), G4ParticleChangeForLoss::operator=(), G4ParticleChangeForTransport::UpdateStepForAtRest(), G4FastStep::~G4FastStep(), G4ParticleChange::~G4ParticleChange(), G4ParticleChangeForDecay::~G4ParticleChangeForDecay(), G4ParticleChangeForGamma::~G4ParticleChangeForGamma(), G4ParticleChangeForLoss::~G4ParticleChangeForLoss(), G4ParticleChangeForMSC::~G4ParticleChangeForMSC(), G4ParticleChangeForTransport::~G4ParticleChangeForTransport(), and ~G4VParticleChange().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4VParticleChange.hh
geant4/tree/geant4-10.6-release/source/track/src/G4VParticleChange.cc