ECCE @ EIC Software: G4LMsdGenerator Class Reference
G4LMsdGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LMsdGenerator.hh>
Public Member Functions
G4LMsdGenerator (const G4String &name="LMsdGenerator")
~G4LMsdGenerator ()
G4bool IsApplicable (const G4HadProjectile &thePrimary, G4Nucleus &theNucleus)
G4HadFinalState * ApplyYourself (const G4HadProjectile &thePrimary, G4Nucleus &theNucleus)
G4double SampleMx (const G4HadProjectile *aParticle)
G4double SampleT (const G4HadProjectile *aParticle, G4double Mx)
void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4LMsdGenerator (const G4LMsdGenerator &right)
const G4LMsdGenerator & operator= (const G4LMsdGenerator &right)
int operator== (const G4LMsdGenerator &right) const
int operator!= (const G4LMsdGenerator &right) const
Private Attributes
G4int fPDGencoding
Static Private Attributes
static const G4double fMxBdata [23][2]
static const G4double fProbMx [60][2]
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 59 of file G4LMsdGenerator.hh.
View newest version in sPHENIX GitHub at line 59 of file G4LMsdGenerator.hh
Constructor & Destructor Documentation
G4LMsdGenerator::G4LMsdGenerator (const G4String & name = "LMsdGenerator")
Definition at line 45 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 45 of file G4LMsdGenerator.cc
References fPDGencoding.
G4LMsdGenerator::~G4LMsdGenerator ()
Definition at line 54 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 54 of file G4LMsdGenerator.cc
G4LMsdGenerator::G4LMsdGenerator (const G4LMsdGenerator & right) private
Member Function Documentation
G4HadFinalState * G4LMsdGenerator::ApplyYourself (const G4HadProjectile & thePrimary, G4Nucleus & theNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 112 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 112 of file G4LMsdGenerator.cc
References a, A(), G4HadFinalState::AddSecondary(), G4Alpha::Alpha(), b, B(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), c, G4HadFinalState::Clear(), G4INCL::ClusterDecay::decay(), G4KineticTrack::Decay(), G4Deuteron::Deuteron(), CLHEP::HepLorentzVector::e(), fPDGencoding, G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4NucleiProperties::GetNuclearMass(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), CLHEP::GeV, G4He3::He3(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::MeV, phi, G4Proton::Proton(), SampleMx(), SampleT(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetLocalEnergyDeposit(), G4HadFinalState::SetMomentumChange(), G4HadFinalState::SetStatusChange(), stopAndKill, t, G4HadronicInteraction::theParticleChange, G4Triton::Triton(), CLHEP::twopi, CLHEP::Hep3Vector::unit(), v1, CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
G4bool G4LMsdGenerator::IsApplicable (const G4HadProjectile & thePrimary, G4Nucleus & theNucleus) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 76 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 76 of file G4LMsdGenerator.cc
References G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), CLHEP::MeV, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), and G4Proton::Proton().
void G4LMsdGenerator::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 59 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 59 of file G4LMsdGenerator.cc
References G4HadronicInteraction::GetModelName().
int G4LMsdGenerator::operator!= (const G4LMsdGenerator & right) const private
const G4LMsdGenerator& G4LMsdGenerator::operator= (const G4LMsdGenerator & right) private
int G4LMsdGenerator::operator== (const G4LMsdGenerator & right) const private
G4double G4LMsdGenerator::SampleMx (const G4HadProjectile * aParticle)
Definition at line 290 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 290 of file G4LMsdGenerator.cc
References G4ParticleTable::FindParticle(), fPDGencoding, fProbMx, G4UniformRand, G4HadProjectile::GetDefinition(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), CLHEP::GeV, G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), and G4Proton::Proton().
Referenced by ApplyYourself().
G4double G4LMsdGenerator::SampleT (const G4HadProjectile * aParticle, G4double Mx)
Definition at line 440 of file G4LMsdGenerator.cc.
View newest version in sPHENIX GitHub at line 440 of file G4LMsdGenerator.cc
References b, fMxBdata, G4Log(), G4UniformRand, G4HadProjectile::GetKineticEnergy(), CLHEP::GeV, and t.
Referenced by ApplyYourself().
Member Data Documentation
const G4double G4LMsdGenerator::fMxBdata static private
Initial value:
=
{
  {1.09014,      17.8620},
  {1.12590,      19.2831},
  {1.18549,      17.6907},
  {1.21693,      16.4760},
  {1.25194,      15.3867},
  {1.26932,      14.4236},
  {1.29019,      13.2931},
  {1.30755,      12.2882},
  {1.31790,      11.4509},
  {1.33888,      10.6969},
  {1.34911,      9.44130},
  {1.37711,      8.56148},
  {1.39101,      7.76593},
  {1.42608,      6.88582},
  {1.48593,      6.13019},
  {1.53179,      5.87723},
  {1.58111,      5.37308},
  {1.64105,      4.95217},
  {1.69037,      4.44803},
  {1.81742,      3.89879},
  {1.88096,      3.68693},
  {1.95509,      3.43278},
  {2.02219,      3.30445}
}
Definition at line 94 of file G4LMsdGenerator.hh.
View newest version in sPHENIX GitHub at line 94 of file G4LMsdGenerator.hh
Referenced by SampleT().
G4int G4LMsdGenerator::fPDGencoding private
Definition at line 92 of file G4LMsdGenerator.hh.
View newest version in sPHENIX GitHub at line 92 of file G4LMsdGenerator.hh
Referenced by ApplyYourself(), G4LMsdGenerator(), and SampleMx().
const G4double G4LMsdGenerator::fProbMx static private
Definition at line 95 of file G4LMsdGenerator.hh.
View newest version in sPHENIX GitHub at line 95 of file G4LMsdGenerator.hh
Referenced by SampleMx().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LMsdGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4LMsdGenerator.cc