ECCE @ EIC Software: doiPETEventAction Class Reference
doiPETEventAction Class Reference
Event action class.
#include <geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETEventAction.hh>
Public Member Functions
doiPETEventAction ()
virtual ~doiPETEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4int printModulo
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Event action class.
Definition at line 51 of file doiPETEventAction.hh.
View newest version in sPHENIX GitHub at line 51 of file doiPETEventAction.hh
Constructor & Destructor Documentation
doiPETEventAction::doiPETEventAction ()
Definition at line 61 of file doiPETEventAction.cc.
View newest version in sPHENIX GitHub at line 61 of file doiPETEventAction.cc
References printModulo.
doiPETEventAction::~doiPETEventAction () virtual
Definition at line 67 of file doiPETEventAction.cc.
View newest version in sPHENIX GitHub at line 67 of file doiPETEventAction.cc
Member Function Documentation
void doiPETEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 71 of file doiPETEventAction.cc.
View newest version in sPHENIX GitHub at line 71 of file doiPETEventAction.cc
References G4cout, G4endl, G4Event::GetEventID(), and printModulo.
void doiPETEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 81 of file doiPETEventAction.cc.
View newest version in sPHENIX GitHub at line 81 of file doiPETEventAction.cc
References doiPETAnalysis::CalulateAcquisitionTime(), doiPETRun::Clear(), doiPETRun::FindInteractingCrystal(), G4cout, G4endl, G4MUTEX_INITIALIZER, G4Event::GetEventID(), doiPETAnalysis::GetInstance(), G4RunManager::GetNonConstCurrentRun(), G4RunManager::GetRunManager(), printModulo, doiPETAnalysis::ResetNumberOfHits(), and doiPETAnalysis::SetEventID().
Member Data Documentation
G4int doiPETEventAction::printModulo private
Definition at line 62 of file doiPETEventAction.hh.
View newest version in sPHENIX GitHub at line 62 of file doiPETEventAction.hh
Referenced by BeginOfEventAction(), doiPETEventAction(), and EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/src/doiPETEventAction.cc