ECCE @ EIC Software: G4ShellData Class Reference
G4ShellData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ShellData.hh>
Public Member Functions
G4ShellData (G4int minZ=1, G4int maxZ=100, G4bool isOccupancy=false)
~G4ShellData ()
size_t NumberOfShells (G4int Z) const
G4int ShellId (G4int Z, G4int shellIndex) const
G4double ShellOccupancyProbability (G4int Z, G4int shellIndex) const
const std::vector< G4double > & ShellIdVector (G4int Z) const
G4double BindingEnergy (G4int Z, G4int shellIndex) const
void SetOccupancyData ()
void LoadData (const G4String &fileName)
void PrintData () const
G4int SelectRandomShell (G4int Z) const
Private Member Functions
G4ShellData & operator= (const G4ShellData &right)
G4ShellData (const G4ShellData &)
const std::vector< G4double > & ShellVector (G4int Z) const
Private Attributes
G4int zMin
G4int zMax
G4bool occupancyData
std::map< G4int, std::vector
< G4double > *, std::less
< G4int > > idMap
std::map< G4int, G4DataVector
*, std::less< G4int > > bindingMap
std::vector< G4int > nShells
std::map< G4int, std::vector
< G4double > *, std::less
< G4int > > occupancyPdfMap
Detailed Description
Definition at line 51 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ShellData.hh
Constructor & Destructor Documentation
G4ShellData::G4ShellData (G4int minZ = 1, G4int maxZ = 100, G4bool isOccupancy = false)
Definition at line 50 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ShellData.cc
G4ShellData::~G4ShellData ()
Definition at line 55 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ShellData.cc
References bindingMap, idMap, occupancyData, occupancyPdfMap, and pos().
G4ShellData::G4ShellData (const G4ShellData &) private
Member Function Documentation
G4double G4ShellData::BindingEnergy (G4int Z, G4int shellIndex) const
Definition at line 165 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 165 of file G4ShellData.cc
References bindingMap, pos(), zMax, and zMin.
Referenced by G4AtomicTransitionManager::Initialise(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
void G4ShellData::LoadData (const G4String & fileName)
Definition at line 233 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 233 of file G4ShellData.cc
References a, bindingMap, e, FatalException, file, G4Exception(), idMap, k, MeV, n, nShells, occupancyData, occupancyPdfMap, scale, ShellIdVector(), Z, zMax, and zMin.
Referenced by G4LivermoreComptonModel::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4AtomicTransitionManager::Initialise(), G4LowEPComptonModel::Initialise(), and G4LowEPPolarizedComptonModel::Initialise().
size_t G4ShellData::NumberOfShells (G4int Z) const
Definition at line 83 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ShellData.cc
References n, nShells, z, zMax, and zMin.
Referenced by G4AtomicTransitionManager::Initialise(), and SelectRandomShell().
G4ShellData& G4ShellData::operator= (const G4ShellData & right) private
void G4ShellData::PrintData (void) const
Definition at line 186 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 186 of file G4ShellData.cc
References bindingMap, e, G4cout, G4endl, idMap, keV, nShells, occupancyData, occupancyPdfMap, Z, zMax, and zMin.
G4int G4ShellData::SelectRandomShell (G4int Z) const
Definition at line 362 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 362 of file G4ShellData.cc
References FatalErrorInArgument, G4Exception(), G4UniformRand, NumberOfShells(), ShellVector(), and zMax.
Referenced by G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
void G4ShellData::SetOccupancyData () inline
Definition at line 69 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ShellData.hh
References occupancyData.
Referenced by G4LivermoreComptonModel::Initialise(), G4LivermoreComptonModifiedModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4LowEPComptonModel::Initialise(), and G4LowEPPolarizedComptonModel::Initialise().
G4int G4ShellData::ShellId (G4int Z, G4int shellIndex) const
Definition at line 120 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 120 of file G4ShellData.cc
References idMap, n, pos(), zMax, and zMin.
Referenced by G4AtomicTransitionManager::Initialise().
const std::vector< G4double > & G4ShellData::ShellIdVector (G4int Z) const
Definition at line 96 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ShellData.cc
References FatalErrorInArgument, G4Exception(), idMap, pos(), and zMax.
Referenced by LoadData().
G4double G4ShellData::ShellOccupancyProbability (G4int Z, G4int shellIndex) const
Definition at line 142 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 142 of file G4ShellData.cc
References idMap, pos(), zMax, and zMin.
const std::vector< G4double > & G4ShellData::ShellVector (G4int Z) const private
Definition at line 110 of file G4ShellData.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ShellData.cc
References G4Exception(), JustWarning, occupancyPdfMap, pos(), and zMax.
Referenced by SelectRandomShell().
Member Data Documentation
std::map<G4int,G4DataVector*,std::less<G4int> > G4ShellData::bindingMap private
Definition at line 92 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ShellData.hh
Referenced by BindingEnergy(), LoadData(), PrintData(), and ~G4ShellData().
std::map<G4int,std::vector<G4double>*,std::less<G4int> > G4ShellData::idMap private
Definition at line 91 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ShellData.hh
Referenced by LoadData(), PrintData(), ShellId(), ShellIdVector(), ShellOccupancyProbability(), and ~G4ShellData().
std::vector<G4int> G4ShellData::nShells private
Definition at line 93 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ShellData.hh
Referenced by LoadData(), NumberOfShells(), and PrintData().
G4bool G4ShellData::occupancyData private
Definition at line 89 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ShellData.hh
Referenced by LoadData(), PrintData(), SetOccupancyData(), and ~G4ShellData().
std::map<G4int,std::vector<G4double>*,std::less<G4int> > G4ShellData::occupancyPdfMap private
Definition at line 94 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ShellData.hh
Referenced by LoadData(), PrintData(), ShellVector(), and ~G4ShellData().
G4int G4ShellData::zMax private
Definition at line 87 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ShellData.hh
Referenced by BindingEnergy(), LoadData(), NumberOfShells(), PrintData(), SelectRandomShell(), ShellId(), ShellIdVector(), ShellOccupancyProbability(), and ShellVector().
G4int G4ShellData::zMin private
Definition at line 86 of file G4ShellData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ShellData.hh
Referenced by BindingEnergy(), LoadData(), NumberOfShells(), PrintData(), ShellId(), and ShellOccupancyProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ShellData.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4ShellData.cc