ECCE @ EIC Software: acts/blob/master/Examples/Scripts/MaterialMaping/Mat_map_surface_plot_ratio.C File Reference
Mat_map_surface_plot_ratio.C File Reference
#include "Mat_map_surface_plot.cpp"
Functions
void plot_ratio (std::vector< TH2F * > Map_prop, std::vector< TH2F * > Map_geant, const sinfo &surface_info, const std::string &name)
Draw and save the ratio plots.
void Mat_map_surface_plot_ratio (std::string input_file_prop="", std::string input_file_geant="", std::string json_surface_file="", int nbprocess=-1, std::string name="", std::string name_prop="", std::string name_geant="")
Function Documentation
void Mat_map_surface_plot_ratio (std::string input_file_prop = "", std::string input_file_geant = "", std::string json_surface_file = "", int nbprocess = -1, std::string name = "", std::string name_prop = "", std::string name_geant = "")
Plot the material ratio between the geantino scan and the map validation for each surface. If a surface map json file is specify it is parse to associate name to the different surface id nbprocess : number of parameter to be processed name : name of the output directory. name_prop : name of the output directory for the map valdation. name_geant : name of the output directory for the geantino scan. The map valdation and geantino scan plots are only saved if name_prop and name_geant are defined. The parsing of the Json surface map file (use to associate the name to the volumes) might not work with version of root newer that version 6.18.04
Definition at line 94 of file Mat_map_surface_plot_ratio.C.
View newest version in sPHENIX GitHub at line 94 of file Mat_map_surface_plot_ratio.C
References Fill(), hist, plot(), and plot_ratio().
void plot_ratio (std::vector< TH2F * > Map_prop, std::vector< TH2F * > Map_geant, const sinfo & surface_info, const std::string & name)
Draw and save the ratio plots.
Definition at line 13 of file Mat_map_surface_plot_ratio.C.
View newest version in sPHENIX GitHub at line 13 of file Mat_map_surface_plot_ratio.C
References c1, sinfo::id, sinfo::idname, sinfo::name, sinfo::pos, surface(), nlohmann::to_string(), and sinfo::type.
Referenced by Mat_map_surface_plot_ratio().