ECCE @ EIC Software: ExN04MuonHit Class Reference
ExN04MuonHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04MuonHit.hh>
Public Member Functions
ExN04MuonHit ()
~ExN04MuonHit ()
ExN04MuonHit (const ExN04MuonHit &right)
const ExN04MuonHit & operator= (const ExN04MuonHit &right)
G4bool operator== (const ExN04MuonHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
virtual void Draw ()
virtual void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos ()
ExN04MuonHit ()
~ExN04MuonHit ()
ExN04MuonHit (const ExN04MuonHit &right)
const ExN04MuonHit & operator= (const ExN04MuonHit &right)
G4bool operator== (const ExN04MuonHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
void Draw ()
void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos ()
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
G4double fedep
G4ThreeVector fpos
G4double edep
G4ThreeVector pos
Detailed Description
Definition at line 39 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 39 of file ExN04MuonHit.hh
Constructor & Destructor Documentation
ExN04MuonHit::ExN04MuonHit ()
Definition at line 41 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 41 of file ExN04MuonHit.cc
ExN04MuonHit::~ExN04MuonHit ()
Definition at line 47 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 47 of file ExN04MuonHit.cc
ExN04MuonHit::ExN04MuonHit (const ExN04MuonHit & right)
Definition at line 52 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 52 of file ExN04MuonHit.cc
References fedep, and fpos.
ExN04MuonHit::ExN04MuonHit ()
ExN04MuonHit::~ExN04MuonHit ()
ExN04MuonHit::ExN04MuonHit (const ExN04MuonHit & right)
Member Function Documentation
void ExN04MuonHit::AddEdep (G4double de) inline
Definition at line 54 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04MuonHit.hh
References fedep.
Referenced by ExN04MuonSD::ProcessHits().
void ExN04MuonHit::AddEdep (G4double de) inline
Definition at line 78 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 78 of file ExN04MuonHit.hh
References edep.
void ExN04MuonHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 74 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 74 of file ExN04MuonHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, fpos, G4VVisManager::GetConcreteInstance(), G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
void ExN04MuonHit::Draw () virtual
Reimplemented from G4VHit.
G4double ExN04MuonHit::GetEdep () inline
Definition at line 55 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04MuonHit.hh
References fedep.
Referenced by MarshaledExN04MuonHit::marshal1().
G4double ExN04MuonHit::GetEdep () inline
Definition at line 80 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 80 of file ExN04MuonHit.hh
References edep.
G4ThreeVector ExN04MuonHit::GetPos () inline
Definition at line 57 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04MuonHit.hh
References fpos.
Referenced by MarshaledExN04MuonHit::marshal2(), and ExN04MuonSD::ProcessHits().
G4ThreeVector ExN04MuonHit::GetPos () inline
Definition at line 84 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 84 of file ExN04MuonHit.hh
References pos.
void ExN04MuonHit::operator delete (void * aHit) inline
Definition at line 76 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN04MuonHit.hh
References G4Allocator< Type >::FreeSingle().
void ExN04MuonHit::operator delete (void * aHit) inline
void * ExN04MuonHit::operator new (size_t) inline
Definition at line 69 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04MuonHit.hh
References G4Allocator< Type >::MallocSingle().
void* ExN04MuonHit::operator new (size_t) inline
const ExN04MuonHit & ExN04MuonHit::operator= (const ExN04MuonHit & right)
Definition at line 60 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 60 of file ExN04MuonHit.cc
References fedep, and fpos.
const ExN04MuonHit& ExN04MuonHit::operator= (const ExN04MuonHit & right)
G4bool ExN04MuonHit::operator== (const ExN04MuonHit & right) const
Definition at line 68 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 68 of file ExN04MuonHit.cc
G4bool ExN04MuonHit::operator== (const ExN04MuonHit & right) const
void ExN04MuonHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 89 of file ExN04MuonHit.cc.
View newest version in sPHENIX GitHub at line 89 of file ExN04MuonHit.cc
void ExN04MuonHit::Print () virtual
Reimplemented from G4VHit.
void ExN04MuonHit::SetEdep (G4double de) inline
Definition at line 53 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 53 of file ExN04MuonHit.hh
References fedep.
Referenced by ExN04MuonSD::ProcessHits(), and MarshaledExN04MuonHit::unmarshal1().
void ExN04MuonHit::SetEdep (G4double de) inline
Definition at line 76 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN04MuonHit.hh
References edep.
void ExN04MuonHit::SetPos (G4ThreeVector xyz) inline
Definition at line 56 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 56 of file ExN04MuonHit.hh
References fpos.
Referenced by ExN04MuonSD::ProcessHits(), and MarshaledExN04MuonHit::unmarshal2().
void ExN04MuonHit::SetPos (G4ThreeVector xyz) inline
Definition at line 82 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 82 of file ExN04MuonHit.hh
References pos.
Member Data Documentation
G4double ExN04MuonHit::edep private
Definition at line 64 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN04MuonHit.hh
Referenced by AddEdep(), GetEdep(), and SetEdep().
G4double ExN04MuonHit::fedep private
Definition at line 60 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 60 of file ExN04MuonHit.hh
Referenced by AddEdep(), ExN04MuonHit(), GetEdep(), operator=(), and SetEdep().
G4ThreeVector ExN04MuonHit::fpos private
Definition at line 61 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 61 of file ExN04MuonHit.hh
Referenced by Draw(), ExN04MuonHit(), GetPos(), operator=(), and SetPos().
G4ThreeVector ExN04MuonHit::pos private
Definition at line 70 of file ExN04MuonHit.hh.
View newest version in sPHENIX GitHub at line 70 of file ExN04MuonHit.hh
Referenced by GetPos(), and SetPos().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04MuonHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04MuonHit.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04MuonHit.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04MuonHit.cc