ECCE @ EIC Software: G4DNAChampionElasticModel Class Reference
G4DNAChampionElasticModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAChampionElasticModel.hh>
Public Member Functions
G4DNAChampionElasticModel (const G4ParticleDefinition *p=0, const G4String &nam="DNAChampionElasticModel")
virtual ~G4DNAChampionElasticModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
void SetKillBelowThreshold (G4double threshold)
G4double GetKillBelowThreshold ()
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Types
typedef std::map< G4double,
std::vector< G4double > > VecMap
typedef std::map< G4double,
std::map< G4double, G4double > > TriDimensionMap
Private Member Functions
G4double Theta (G4double k, G4double integrDiff)
G4double LinLinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
G4double RandomizeCosTheta (G4double k)
G4DNAChampionElasticModel & operator= (const G4DNAChampionElasticModel &right)
G4DNAChampionElasticModel (const G4DNAChampionElasticModel &)
Private Attributes
VecMap eVecm
TriDimensionMap eDiffCrossSectionData
std::vector< G4double > eTdummyVec
const std::vector< G4double > * fpMolWaterDensity
G4DNACrossSectionDataSet * fpData
G4int verboseLevel
G4bool isInitialised
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 40 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 40 of file G4DNAChampionElasticModel.hh
Member Typedef Documentation
typedef std::map<G4double, std::map<G4double, G4double> > G4DNAChampionElasticModel::TriDimensionMap private
Definition at line 84 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DNAChampionElasticModel.hh
typedef std::map<G4double, std::vector<G4double> > G4DNAChampionElasticModel::VecMap private
Definition at line 82 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DNAChampionElasticModel.hh
Constructor & Destructor Documentation
G4DNAChampionElasticModel::G4DNAChampionElasticModel (const G4ParticleDefinition * p = 0, const G4String & nam = "DNAChampionElasticModel")
Definition at line 43 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 43 of file G4DNAChampionElasticModel.cc
References eV, fParticleChangeForGamma, fpData, fpMolWaterDensity, G4cout, G4endl, G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), MeV, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), and verboseLevel.
G4DNAChampionElasticModel::~G4DNAChampionElasticModel () virtual
Definition at line 76 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4DNAChampionElasticModel.cc
References eVecm, and fpData.
G4DNAChampionElasticModel::G4DNAChampionElasticModel (const G4DNAChampionElasticModel &) private
Member Function Documentation
G4double G4DNAChampionElasticModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 230 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 230 of file G4DNAChampionElasticModel.cc
References cm, eV, G4DNACrossSectionDataSet::FindValue(), fpData, G4cout, G4endl, G4Material::GetIndex(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), and verboseLevel.
G4double G4DNAChampionElasticModel::GetKillBelowThreshold () inline
Definition at line 67 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4DNAChampionElasticModel.hh
References G4Exception(), and JustWarning.
void G4DNAChampionElasticModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 87 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 87 of file G4DNAChampionElasticModel.cc
References cm, e, eDiffCrossSectionData, eTdummyVec, eV, eVecm, FatalException, fParticleChangeForGamma, fpData, fpMolWaterDensity, G4cout, G4endl, G4Exception(), G4Material::GetMaterial(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4DNAMolecularMaterial::Initialize(), G4DNAMolecularMaterial::Instance(), isInitialised, G4DNACrossSectionDataSet::LoadData(), G4VEmModel::LowEnergyLimit(), MeV, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), and verboseLevel.
G4double G4DNAChampionElasticModel::LinLinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 381 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 381 of file G4DNAChampionElasticModel.cc
References d1, d2, and e1.
Referenced by QuadInterpolator().
G4double G4DNAChampionElasticModel::LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 367 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 367 of file G4DNAChampionElasticModel.cc
References d1, d2, and G4Exp().
G4double G4DNAChampionElasticModel::LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 395 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 395 of file G4DNAChampionElasticModel.cc
References a, and b.
G4DNAChampionElasticModel& G4DNAChampionElasticModel::operator= (const G4DNAChampionElasticModel & right) private
G4double G4DNAChampionElasticModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 411 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 411 of file G4DNAChampionElasticModel.cc
References LinLinInterpolate().
Referenced by Theta().
G4double G4DNAChampionElasticModel::RandomizeCosTheta (G4double k) private
Definition at line 448 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 448 of file G4DNAChampionElasticModel.cc
References eV, G4UniformRand, pi, Theta(), and theta().
Referenced by SampleSecondaries().
void G4DNAChampionElasticModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * aDynamicElectron, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 277 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 277 of file G4DNAChampionElasticModel.cc
References CLHEP::Hep3Vector::cross(), fParticleChangeForGamma, G4cout, G4endl, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), CLHEP::Hep3Vector::orthogonal(), phi, pi, G4ParticleChangeForGamma::ProposeMomentumDirection(), RandomizeCosTheta(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), CLHEP::Hep3Vector::unit(), and verboseLevel.
void G4DNAChampionElasticModel::SetKillBelowThreshold (G4double threshold)
Definition at line 466 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 466 of file G4DNAChampionElasticModel.cc
References G4Exception(), and JustWarning.
G4double G4DNAChampionElasticModel::Theta (G4double k, G4double integrDiff) private
Definition at line 316 of file G4DNAChampionElasticModel.cc.
View newest version in sPHENIX GitHub at line 316 of file G4DNAChampionElasticModel.cc
References eDiffCrossSectionData, eTdummyVec, eVecm, k, QuadInterpolator(), t1, t2, and theta().
Referenced by RandomizeCosTheta().
Member Data Documentation
TriDimensionMap G4DNAChampionElasticModel::eDiffCrossSectionData private
Definition at line 85 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DNAChampionElasticModel.hh
Referenced by Initialise(), and Theta().
std::vector<G4double> G4DNAChampionElasticModel::eTdummyVec private
Definition at line 86 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4DNAChampionElasticModel.hh
Referenced by Initialise(), and Theta().
VecMap G4DNAChampionElasticModel::eVecm private
Definition at line 83 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DNAChampionElasticModel.hh
Referenced by Initialise(), Theta(), and ~G4DNAChampionElasticModel().
G4ParticleChangeForGamma* G4DNAChampionElasticModel::fParticleChangeForGamma protected
Definition at line 95 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 95 of file G4DNAChampionElasticModel.hh
Referenced by G4DNAChampionElasticModel(), Initialise(), and SampleSecondaries().
G4DNACrossSectionDataSet* G4DNAChampionElasticModel::fpData private
Definition at line 92 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4DNAChampionElasticModel.hh
Referenced by CrossSectionPerVolume(), G4DNAChampionElasticModel(), Initialise(), and ~G4DNAChampionElasticModel().
const std::vector<G4double>* G4DNAChampionElasticModel::fpMolWaterDensity private
Definition at line 89 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DNAChampionElasticModel.hh
Referenced by G4DNAChampionElasticModel(), and Initialise().
G4bool G4DNAChampionElasticModel::isInitialised private
Definition at line 99 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4DNAChampionElasticModel.hh
Referenced by Initialise().
G4int G4DNAChampionElasticModel::verboseLevel private
Definition at line 98 of file G4DNAChampionElasticModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4DNAChampionElasticModel.hh
Referenced by CrossSectionPerVolume(), G4DNAChampionElasticModel(), Initialise(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAChampionElasticModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAChampionElasticModel.cc