ECCE @ EIC Software: G4VisCommandSceneShowExtents Class Reference
G4VisCommandSceneShowExtents Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsScene.hh>
Public Member Functions
G4VisCommandSceneShowExtents ()
virtual ~G4VisCommandSceneShowExtents ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommandScene
G4VVisCommandScene ()
virtual ~G4VVisCommandScene ()
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4VisCommandSceneShowExtents (const G4VisCommandSceneShowExtents &)
G4VisCommandSceneShowExtents & operator= (const G4VisCommandSceneShowExtents &)
Private Attributes
G4UIcmdWithoutParameter * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommandScene
G4String CurrentSceneName ()
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 140 of file G4VisCommandsScene.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VisCommandsScene.hh
Constructor & Destructor Documentation
G4VisCommandSceneShowExtents::G4VisCommandSceneShowExtents ()
Definition at line 827 of file G4VisCommandsScene.cc.
View newest version in sPHENIX GitHub at line 827 of file G4VisCommandsScene.cc
References fpCommand.
G4VisCommandSceneShowExtents::~G4VisCommandSceneShowExtents () virtual
Definition at line 832 of file G4VisCommandsScene.cc.
View newest version in sPHENIX GitHub at line 832 of file G4VisCommandsScene.cc
References fpCommand.
G4VisCommandSceneShowExtents::G4VisCommandSceneShowExtents (const G4VisCommandSceneShowExtents &) private
Member Function Documentation
G4String G4VisCommandSceneShowExtents::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 836 of file G4VisCommandsScene.cc.
View newest version in sPHENIX GitHub at line 836 of file G4VisCommandsScene.cc
G4VisCommandSceneShowExtents& G4VisCommandSceneShowExtents::operator= (const G4VisCommandSceneShowExtents &) private
void G4VisCommandSceneShowExtents::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 840 of file G4VisCommandsScene.cc.
View newest version in sPHENIX GitHub at line 840 of file G4VisCommandsScene.cc
References G4VVisCommand::DrawExtent(), G4VVisCommand::fpVisManager, G4cout, G4endl, G4Scene::GetExtent(), G4VisManager::GetVerbosity(), and G4VisManager::warnings.
Member Data Documentation
G4UIcmdWithoutParameter* G4VisCommandSceneShowExtents::fpCommand private
Definition at line 149 of file G4VisCommandsScene.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VisCommandsScene.hh
Referenced by G4VisCommandSceneShowExtents(), and ~G4VisCommandSceneShowExtents().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsScene.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsScene.cc