ECCE @ EIC Software: G4WeightCutOffProcess Class Reference
G4WeightCutOffProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4WeightCutOffProcess.hh>
Public Member Functions
G4WeightCutOffProcess (G4double wsurvival, G4double wlimit, G4double isource, G4VIStore *istore, const G4String &aName="WeightCutOffProcess", G4bool para=false)
virtual ~G4WeightCutOffProcess ()
void SetParallelWorld (const G4String &parallelWorldName)
void SetParallelWorld (G4VPhysicalVolume *parallelWorld)
void StartTracking (G4Track *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
const G4String & GetName () const
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
void CopyStep (const G4Step &step)
G4WeightCutOffProcess (const G4WeightCutOffProcess &)
G4WeightCutOffProcess & operator= (const G4WeightCutOffProcess &)
Private Attributes
G4Step * fGhostStep
G4StepPoint * fGhostPreStepPoint
G4StepPoint * fGhostPostStepPoint
G4ParticleChange * fParticleChange
G4double fWeightSurvival
G4double fWeightLimit
G4double fSourceImportance
G4VIStore * fIStore
G4TransportationManager * fTransportationManager
G4PathFinder * fPathFinder
G4String fGhostWorldName
G4VPhysicalVolume * fGhostWorld
G4Navigator * fGhostNavigator
G4int fNavigatorID
G4TouchableHandle fOldGhostTouchable
G4TouchableHandle fNewGhostTouchable
G4FieldTrack fFieldTrack
G4double fGhostSafety
G4bool fOnBoundary
G4bool fParaflag
G4FieldTrack fEndTrack
ELimited feLimited
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 57 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 57 of file G4WeightCutOffProcess.hh
Constructor & Destructor Documentation
G4WeightCutOffProcess::G4WeightCutOffProcess (G4double wsurvival, G4double wlimit, G4double isource, G4VIStore * istore, const G4String & aName = "WeightCutOffProcess", G4bool para = false)
Definition at line 54 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 54 of file G4WeightCutOffProcess.cc
References FatalException, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fParticleChange, fPathFinder, fTransportationManager, G4cout, G4endl, G4Exception(), G4PathFinder::GetInstance(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VProcess::GetProcessName(), G4TransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, and G4VProcess::verboseLevel.
G4WeightCutOffProcess::~G4WeightCutOffProcess () virtual
Definition at line 93 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 93 of file G4WeightCutOffProcess.cc
References fParticleChange.
G4WeightCutOffProcess::G4WeightCutOffProcess (const G4WeightCutOffProcess &) private
Member Function Documentation
G4VParticleChange * G4WeightCutOffProcess::AlongStepDoIt (const G4Track & track, const G4Step &) virtual
Implements G4VProcess.
Definition at line 383 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 383 of file G4WeightCutOffProcess.cc
References G4VParticleChange::Initialize(), and G4VProcess::pParticleChange.
G4double G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 296 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 296 of file G4WeightCutOffProcess.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PathFinder::ComputeStep(), DBL_MAX, feLimited, fEndTrack, fFieldTrack, fGhostNavigator, fGhostSafety, fNavigatorID, fOnBoundary, fParaflag, fPathFinder, G4Track::GetCurrentStepNumber(), G4Track::GetVolume(), kDoNot, kSharedOther, kSharedTransport, kUnique, NotCandidateForSelection, and G4FieldTrackUpdator::Update().
G4VParticleChange * G4WeightCutOffProcess::AtRestDoIt (const G4Track & , const G4Step &) virtual
Implements G4VProcess.
Definition at line 377 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 377 of file G4WeightCutOffProcess.cc
G4double G4WeightCutOffProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) virtual
Implements G4VProcess.
Definition at line 370 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 370 of file G4WeightCutOffProcess.cc
void G4WeightCutOffProcess::CopyStep (const G4Step & step) private
Definition at line 393 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 393 of file G4WeightCutOffProcess.cc
References fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fOnBoundary, fPostStepDoItProc, G4Step::GetControlFlag(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4Step::SetControlFlag(), G4Step::SetStepLength(), G4StepPoint::SetStepStatus(), G4Step::SetTotalEnergyDeposit(), and G4Step::SetTrack().
Referenced by PostStepDoIt().
const G4String & G4WeightCutOffProcess::GetName (void) const
Definition at line 290 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 290 of file G4WeightCutOffProcess.cc
References G4VProcess::theProcessName.
G4WeightCutOffProcess& G4WeightCutOffProcess::operator= (const G4WeightCutOffProcess &) private
G4VParticleChange * G4WeightCutOffProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Implements G4VProcess.
Definition at line 187 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 187 of file G4WeightCutOffProcess.cc
References CopyStep(), G4PathFinder::CreateTouchableHandle(), fGhostPostStepPoint, fGhostPreStepPoint, fIStore, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fParaflag, fParticleChange, fPathFinder, fSourceImportance, fStopAndKill, fWeightLimit, fWeightSurvival, G4UniformRand, G4VIStore::GetImportance(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4VTouchable::GetReplicaNumber(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4Track::GetWeight(), G4ParticleChange::Initialize(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), Acts::IntegrationTest::R, G4StepPoint::SetTouchableHandle(), and w.
G4double G4WeightCutOffProcess::PostStepGetPhysicalInteractionLength (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 175 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 175 of file G4WeightCutOffProcess.cc
References DBL_MAX, and Forced.
void G4WeightCutOffProcess::SetParallelWorld (const G4String & parallelWorldName)
Definition at line 106 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 106 of file G4WeightCutOffProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4TransportationManager::GetNavigator(), and G4TransportationManager::GetParallelWorld().
Referenced by G4WeightCutOffConfigurator::Configure().
void G4WeightCutOffProcess::SetParallelWorld (G4VPhysicalVolume * parallelWorld)
Definition at line 118 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 118 of file G4WeightCutOffProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4VPhysicalVolume::GetName(), and G4TransportationManager::GetNavigator().
void G4WeightCutOffProcess::StartTracking (G4Track * trk) virtual
Reimplemented from G4VProcess.
Definition at line 134 of file G4WeightCutOffProcess.cc.
View newest version in sPHENIX GitHub at line 134 of file G4WeightCutOffProcess.cc
References G4TransportationManager::ActivateNavigator(), G4PathFinder::CreateTouchableHandle(), FatalException, fGhostNavigator, fGhostPostStepPoint, fGhostPreStepPoint, fGhostSafety, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fParaflag, fPathFinder, fTransportationManager, G4Exception(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4PathFinder::PrepareNewTrack(), and G4StepPoint::SetTouchableHandle().
Member Data Documentation
ELimited G4WeightCutOffProcess::feLimited private
Definition at line 154 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 154 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4FieldTrack G4WeightCutOffProcess::fEndTrack private
Definition at line 153 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 153 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4FieldTrack G4WeightCutOffProcess::fFieldTrack private
Definition at line 148 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 148 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4Navigator* G4WeightCutOffProcess::fGhostNavigator private
Definition at line 144 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 144 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), SetParallelWorld(), and StartTracking().
G4StepPoint* G4WeightCutOffProcess::fGhostPostStepPoint private
Definition at line 123 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 123 of file G4WeightCutOffProcess.hh
Referenced by CopyStep(), G4WeightCutOffProcess(), PostStepDoIt(), and StartTracking().
G4StepPoint* G4WeightCutOffProcess::fGhostPreStepPoint private
Definition at line 122 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 122 of file G4WeightCutOffProcess.hh
Referenced by CopyStep(), G4WeightCutOffProcess(), PostStepDoIt(), and StartTracking().
G4double G4WeightCutOffProcess::fGhostSafety private
Definition at line 149 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 149 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4Step* G4WeightCutOffProcess::fGhostStep private
Definition at line 121 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 121 of file G4WeightCutOffProcess.hh
Referenced by CopyStep(), and G4WeightCutOffProcess().
G4VPhysicalVolume* G4WeightCutOffProcess::fGhostWorld private
Definition at line 143 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 143 of file G4WeightCutOffProcess.hh
Referenced by SetParallelWorld().
G4String G4WeightCutOffProcess::fGhostWorldName private
Definition at line 142 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 142 of file G4WeightCutOffProcess.hh
Referenced by SetParallelWorld().
G4VIStore* G4WeightCutOffProcess::fIStore private
Definition at line 132 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 132 of file G4WeightCutOffProcess.hh
Referenced by PostStepDoIt().
G4int G4WeightCutOffProcess::fNavigatorID private
Definition at line 145 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 145 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4TouchableHandle G4WeightCutOffProcess::fNewGhostTouchable private
Definition at line 147 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 147 of file G4WeightCutOffProcess.hh
Referenced by PostStepDoIt(), and StartTracking().
G4TouchableHandle G4WeightCutOffProcess::fOldGhostTouchable private
Definition at line 146 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 146 of file G4WeightCutOffProcess.hh
Referenced by PostStepDoIt(), and StartTracking().
G4bool G4WeightCutOffProcess::fOnBoundary private
Definition at line 150 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 150 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), CopyStep(), PostStepDoIt(), and StartTracking().
G4bool G4WeightCutOffProcess::fParaflag private
Definition at line 152 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 152 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4ParticleChange* G4WeightCutOffProcess::fParticleChange private
Definition at line 128 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 128 of file G4WeightCutOffProcess.hh
Referenced by G4WeightCutOffProcess(), PostStepDoIt(), and ~G4WeightCutOffProcess().
G4PathFinder* G4WeightCutOffProcess::fPathFinder private
Definition at line 137 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 137 of file G4WeightCutOffProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess(), PostStepDoIt(), and StartTracking().
G4double G4WeightCutOffProcess::fSourceImportance private
Definition at line 131 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 131 of file G4WeightCutOffProcess.hh
Referenced by PostStepDoIt().
G4TransportationManager* G4WeightCutOffProcess::fTransportationManager private
Definition at line 136 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 136 of file G4WeightCutOffProcess.hh
Referenced by G4WeightCutOffProcess(), SetParallelWorld(), and StartTracking().
G4double G4WeightCutOffProcess::fWeightLimit private
Definition at line 130 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 130 of file G4WeightCutOffProcess.hh
Referenced by PostStepDoIt().
G4double G4WeightCutOffProcess::fWeightSurvival private
Definition at line 129 of file G4WeightCutOffProcess.hh.
View newest version in sPHENIX GitHub at line 129 of file G4WeightCutOffProcess.hh
Referenced by PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4WeightCutOffProcess.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4WeightCutOffProcess.cc