ECCE @ EIC Software: G4PenelopeOscillator Class Reference
G4PenelopeOscillator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeOscillator.hh>
Public Member Functions
G4PenelopeOscillator ()
G4PenelopeOscillator (const G4PenelopeOscillator &)
~G4PenelopeOscillator ()
G4PenelopeOscillator & operator= (const G4PenelopeOscillator &)
G4bool operator== (const G4PenelopeOscillator &) const
G4bool operator> (const G4PenelopeOscillator &) const
G4bool operator< (const G4PenelopeOscillator &) const
G4double GetHartreeFactor ()
void SetHartreeFactor (G4double hf)
G4double GetIonisationEnergy ()
void SetIonisationEnergy (G4double ie)
G4double GetResonanceEnergy () const
void SetResonanceEnergy (G4double re)
G4double GetOscillatorStrength ()
void SetOscillatorStrength (G4double ostr)
G4int GetShellFlag ()
void SetShellFlag (G4int theflag)
G4double GetParentZ ()
void SetParentZ (G4double parZ)
G4int GetParentShellID ()
void SetParentShellID (G4int psID)
G4double GetCutoffRecoilResonantEnergy ()
void SetCutoffRecoilResonantEnergy (G4double ene)
Private Attributes
G4double hartreeFactor
G4double ionisationEnergy
G4double resonanceEnergy
G4double oscillatorStrength
G4int shellFlag
G4double parentZ
G4int parentShellID
G4double cutoffRecoilResonantEnergy
Detailed Description
Definition at line 47 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PenelopeOscillator.hh
Constructor & Destructor Documentation
G4PenelopeOscillator::G4PenelopeOscillator ()
Definition at line 38 of file G4PenelopeOscillator.cc.
View newest version in sPHENIX GitHub at line 38 of file G4PenelopeOscillator.cc
G4PenelopeOscillator::G4PenelopeOscillator (const G4PenelopeOscillator & right)
Definition at line 46 of file G4PenelopeOscillator.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PenelopeOscillator.cc
References cutoffRecoilResonantEnergy, hartreeFactor, ionisationEnergy, oscillatorStrength, parentShellID, parentZ, resonanceEnergy, and shellFlag.
G4PenelopeOscillator::~G4PenelopeOscillator () inline
Definition at line 54 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 54 of file G4PenelopeOscillator.hh
Member Function Documentation
G4double G4PenelopeOscillator::GetCutoffRecoilResonantEnergy () inline
Definition at line 84 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 84 of file G4PenelopeOscillator.hh
References cutoffRecoilResonantEnergy.
Referenced by G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), and G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron().
G4double G4PenelopeOscillator::GetHartreeFactor () inline
Definition at line 63 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PenelopeOscillator.hh
References hartreeFactor.
Referenced by G4PenelopeComptonModel::DifferentialCrossSection().
G4double G4PenelopeOscillator::GetIonisationEnergy () inline
Definition at line 66 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 66 of file G4PenelopeOscillator.hh
References ionisationEnergy.
Referenced by G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeComptonModel::DifferentialCrossSection(), and G4PenelopeComptonModel::KleinNishinaCrossSection().
G4double G4PenelopeOscillator::GetOscillatorStrength () inline
Definition at line 72 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PenelopeOscillator.hh
References oscillatorStrength.
Referenced by G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeComptonModel::KleinNishinaCrossSection(), and G4PenelopeComptonModel::OscillatorTotalCrossSection().
G4int G4PenelopeOscillator::GetParentShellID () inline
Definition at line 81 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 81 of file G4PenelopeOscillator.hh
References parentShellID.
G4double G4PenelopeOscillator::GetParentZ () inline
Definition at line 78 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PenelopeOscillator.hh
References parentZ.
Referenced by G4PenelopeIonisationCrossSection::CrossSection(), and G4PenelopeIonisationCrossSection::FindShellIDIndex().
G4double G4PenelopeOscillator::GetResonanceEnergy () const inline
Definition at line 69 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PenelopeOscillator.hh
References resonanceEnergy.
Referenced by G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsElectron(), G4PenelopeIonisationXSHandler::ComputeShellCrossSectionsPositron(), G4PenelopeIonisationCrossSection::CrossSection(), and G4PenelopeOscillatorResEnergyComparator::operator()().
G4int G4PenelopeOscillator::GetShellFlag () inline
Definition at line 75 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 75 of file G4PenelopeOscillator.hh
References shellFlag.
Referenced by G4PenelopeIonisationCrossSection::CrossSection(), and G4PenelopeIonisationCrossSection::FindShellIDIndex().
G4bool G4PenelopeOscillator::operator< (const G4PenelopeOscillator & right) const
Definition at line 96 of file G4PenelopeOscillator.cc.
View newest version in sPHENIX GitHub at line 96 of file G4PenelopeOscillator.cc
References ionisationEnergy.
G4PenelopeOscillator & G4PenelopeOscillator::operator= (const G4PenelopeOscillator & right)
Definition at line 60 of file G4PenelopeOscillator.cc.
View newest version in sPHENIX GitHub at line 60 of file G4PenelopeOscillator.cc
References cutoffRecoilResonantEnergy, hartreeFactor, ionisationEnergy, oscillatorStrength, parentShellID, parentZ, resonanceEnergy, and shellFlag.
G4bool G4PenelopeOscillator::operator== (const G4PenelopeOscillator & right) const
Definition at line 78 of file G4PenelopeOscillator.cc.
View newest version in sPHENIX GitHub at line 78 of file G4PenelopeOscillator.cc
References ionisationEnergy.
G4bool G4PenelopeOscillator::operator> (const G4PenelopeOscillator & right) const
Definition at line 87 of file G4PenelopeOscillator.cc.
View newest version in sPHENIX GitHub at line 87 of file G4PenelopeOscillator.cc
References ionisationEnergy.
void G4PenelopeOscillator::SetCutoffRecoilResonantEnergy (G4double ene) inline
Definition at line 85 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 85 of file G4PenelopeOscillator.hh
References cutoffRecoilResonantEnergy.
void G4PenelopeOscillator::SetHartreeFactor (G4double hf) inline
Definition at line 64 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 64 of file G4PenelopeOscillator.hh
References hartreeFactor, and gammaraytel::hf.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
void G4PenelopeOscillator::SetIonisationEnergy (G4double ie) inline
Definition at line 67 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PenelopeOscillator.hh
References ionisationEnergy.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
void G4PenelopeOscillator::SetOscillatorStrength (G4double ostr) inline
Definition at line 73 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PenelopeOscillator.hh
References oscillatorStrength.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
void G4PenelopeOscillator::SetParentShellID (G4int psID) inline
Definition at line 82 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 82 of file G4PenelopeOscillator.hh
References parentShellID.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
void G4PenelopeOscillator::SetParentZ (G4double parZ) inline
Definition at line 79 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 79 of file G4PenelopeOscillator.hh
References parentZ.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
void G4PenelopeOscillator::SetResonanceEnergy (G4double re) inline
Definition at line 70 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PenelopeOscillator.hh
References resonanceEnergy.
void G4PenelopeOscillator::SetShellFlag (G4int theflag) inline
Definition at line 76 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PenelopeOscillator.hh
References shellFlag.
Referenced by G4PenelopeOscillatorManager::BuildOscillatorTable().
Member Data Documentation
G4double G4PenelopeOscillator::cutoffRecoilResonantEnergy private
Definition at line 95 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetCutoffRecoilResonantEnergy(), operator=(), and SetCutoffRecoilResonantEnergy().
G4double G4PenelopeOscillator::hartreeFactor private
Definition at line 85 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 85 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetHartreeFactor(), operator=(), and SetHartreeFactor().
G4double G4PenelopeOscillator::ionisationEnergy private
Definition at line 89 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetIonisationEnergy(), operator<(), operator=(), operator==(), operator>(), and SetIonisationEnergy().
G4double G4PenelopeOscillator::oscillatorStrength private
Definition at line 91 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetOscillatorStrength(), operator=(), and SetOscillatorStrength().
G4int G4PenelopeOscillator::parentShellID private
Definition at line 94 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetParentShellID(), operator=(), and SetParentShellID().
G4double G4PenelopeOscillator::parentZ private
Definition at line 93 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetParentZ(), operator=(), and SetParentZ().
G4double G4PenelopeOscillator::resonanceEnergy private
Definition at line 90 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetResonanceEnergy(), operator=(), and SetResonanceEnergy().
G4int G4PenelopeOscillator::shellFlag private
Definition at line 92 of file G4PenelopeOscillator.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PenelopeOscillator.hh
Referenced by G4PenelopeOscillator(), GetShellFlag(), operator=(), and SetShellFlag().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeOscillator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4PenelopeOscillator.cc