ECCE @ EIC Software: G4TWorkspacePool< T > Class Template Reference
G4TWorkspacePool< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4TWorkspacePool.hh>
Public Member Functions
T * CreateWorkspace ()
void CreateAndUseWorkspace ()
T * FindOrCreateWorkspace ()
T * GetWorkspace ()
void Recycle (T *myWrkSpace)
void CleanUpAndDestroyAllWorkspaces ()
G4TWorkspacePool ()
~G4TWorkspacePool ()
Static Private Attributes
static G4ThreadLocal T * fMyWorkspace =0
Detailed Description
template<class T>
class G4TWorkspacePool< T >
Definition at line 53 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 53 of file G4TWorkspacePool.hh
Constructor & Destructor Documentation
template<class T > G4TWorkspacePool< T >::G4TWorkspacePool () inline
Definition at line 80 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TWorkspacePool.hh
template<class T > G4TWorkspacePool< T >::~G4TWorkspacePool () inline
Definition at line 81 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 81 of file G4TWorkspacePool.hh
Member Function Documentation
template<class T > void G4TWorkspacePool< T >::CleanUpAndDestroyAllWorkspaces () inline
Definition at line 147 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 147 of file G4TWorkspacePool.hh
Referenced by G4WorkerThread::DestroyGeometryAndPhysicsVector().
template<class T > void G4TWorkspacePool< T >::CreateAndUseWorkspace () inline
Definition at line 120 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 120 of file G4TWorkspacePool.hh
Referenced by G4WorkerThread::BuildGeometryAndPhysicsVector().
template<class T > T * G4TWorkspacePool< T >::CreateWorkspace () inline
Definition at line 92 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 92 of file G4TWorkspacePool.hh
References FatalException, G4Exception(), and T.
template<class T > T * G4TWorkspacePool< T >::FindOrCreateWorkspace () inline
Definition at line 126 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 126 of file G4TWorkspacePool.hh
References T.
template<class T > T* G4TWorkspacePool< T >::GetWorkspace () inline
Definition at line 69 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TWorkspacePool.hh
References G4TWorkspacePool< T >::fMyWorkspace.
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
template<class T > void G4TWorkspacePool< T >::Recycle (T * myWrkSpace) inline
Definition at line 140 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 140 of file G4TWorkspacePool.hh
Member Data Documentation
template<class T > G4ThreadLocal T * G4TWorkspacePool< T >::fMyWorkspace =0 static private
Definition at line 85 of file G4TWorkspacePool.hh.
View newest version in sPHENIX GitHub at line 85 of file G4TWorkspacePool.hh
Referenced by G4TWorkspacePool< T >::GetWorkspace().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4TWorkspacePool.hh