ECCE @ EIC Software: GB01BOptrMultiParticleChangeCrossSection Class Reference
GB01BOptrMultiParticleChangeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB01/include/GB01BOptrMultiParticleChangeCrossSection.hh>
Public Member Functions
GB01BOptrMultiParticleChangeCrossSection ()
virtual ~GB01BOptrMultiParticleChangeCrossSection ()
void AddParticle (G4String particleName)
void StartTracking (const G4Track *track)
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartRun ()
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
Private Attributes
std::map< const
G4ParticleDefinition
*, GB01BOptrChangeCrossSection * > fBOptrForParticle
std::vector< const
G4ParticleDefinition * > fParticlesToBias
GB01BOptrChangeCrossSection * fCurrentOperator
G4int fnInteractions
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 53 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 53 of file GB01BOptrMultiParticleChangeCrossSection.hh
Constructor & Destructor Documentation
GB01BOptrMultiParticleChangeCrossSection::GB01BOptrMultiParticleChangeCrossSection ()
Definition at line 40 of file GB01BOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 40 of file GB01BOptrMultiParticleChangeCrossSection.cc
virtual GB01BOptrMultiParticleChangeCrossSection::~GB01BOptrMultiParticleChangeCrossSection () inline virtual
Definition at line 56 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 56 of file GB01BOptrMultiParticleChangeCrossSection.hh
Member Function Documentation
void GB01BOptrMultiParticleChangeCrossSection::AddParticle (G4String particleName)
Definition at line 46 of file GB01BOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 46 of file GB01BOptrMultiParticleChangeCrossSection.cc
References fBOptrForParticle, G4ParticleTable::FindParticle(), fParticlesToBias, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), JustWarning, and particle.
Referenced by GB01DetectorConstruction::ConstructSDandField().
void GB01BOptrMultiParticleChangeCrossSection::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 106 of file GB01BOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 106 of file GB01BOptrMultiParticleChangeCrossSection.cc
References fCurrentOperator, fnInteractions, and G4VBiasingOperator::ReportOperationApplied().
virtual G4VBiasingOperation* GB01BOptrMultiParticleChangeCrossSection::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 77 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 77 of file GB01BOptrMultiParticleChangeCrossSection.hh
virtual G4VBiasingOperation* GB01BOptrMultiParticleChangeCrossSection::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 80 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 80 of file GB01BOptrMultiParticleChangeCrossSection.hh
G4VBiasingOperation * GB01BOptrMultiParticleChangeCrossSection::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) private virtual
Implements G4VBiasingOperator.
Definition at line 71 of file GB01BOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 71 of file GB01BOptrMultiParticleChangeCrossSection.cc
References fCurrentOperator, fnInteractions, G4Track::GetParentID(), G4VBiasingOperator::GetProposedOccurenceBiasingOperation(), and G4Track::GetWeight().
void GB01BOptrMultiParticleChangeCrossSection::StartTracking (const G4Track * track) virtual
Reimplemented from G4VBiasingOperator.
Definition at line 89 of file GB01BOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 89 of file GB01BOptrMultiParticleChangeCrossSection.cc
References fBOptrForParticle, fCurrentOperator, fnInteractions, G4Track::GetParticleDefinition(), and it.
Member Data Documentation
std::map< const G4ParticleDefinition*, GB01BOptrChangeCrossSection* > GB01BOptrMultiParticleChangeCrossSection::fBOptrForParticle private
Definition at line 106 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 106 of file GB01BOptrMultiParticleChangeCrossSection.hh
Referenced by AddParticle(), and StartTracking().
GB01BOptrChangeCrossSection* GB01BOptrMultiParticleChangeCrossSection::fCurrentOperator private
Definition at line 108 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 108 of file GB01BOptrMultiParticleChangeCrossSection.hh
Referenced by OperationApplied(), ProposeOccurenceBiasingOperation(), and StartTracking().
G4int GB01BOptrMultiParticleChangeCrossSection::fnInteractions private
Definition at line 111 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 111 of file GB01BOptrMultiParticleChangeCrossSection.hh
Referenced by OperationApplied(), ProposeOccurenceBiasingOperation(), and StartTracking().
std::vector< const G4ParticleDefinition* > GB01BOptrMultiParticleChangeCrossSection::fParticlesToBias private
Definition at line 107 of file GB01BOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 107 of file GB01BOptrMultiParticleChangeCrossSection.hh
Referenced by AddParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB01/include/GB01BOptrMultiParticleChangeCrossSection.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB01/src/GB01BOptrMultiParticleChangeCrossSection.cc