ECCE @ EIC Software: G4KaonPlusField Class Reference
G4KaonPlusField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4KaonPlusField.hh>
Public Member Functions
G4KaonPlusField (G4V3DNucleus *nucleus, G4double coeff=0.35 *CLHEP::fermi)
virtual ~G4KaonPlusField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
virtual G4double GetCoeff ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
Private Member Functions
G4KaonPlusField (const G4KaonPlusField &right)
const G4KaonPlusField & operator= (const G4KaonPlusField &right)
G4bool operator== (const G4KaonPlusField &right) const
G4bool operator!= (const G4KaonPlusField &right) const
Private Attributes
G4double theCoeff
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 47 of file G4KaonPlusField.hh.
View newest version in sPHENIX GitHub at line 47 of file G4KaonPlusField.hh
Constructor & Destructor Documentation
G4KaonPlusField::G4KaonPlusField (G4V3DNucleus * nucleus, G4double coeff = 0.35*CLHEP::fermi)
Definition at line 49 of file G4KaonPlusField.cc.
View newest version in sPHENIX GitHub at line 49 of file G4KaonPlusField.cc
References theCoeff.
G4KaonPlusField::~G4KaonPlusField () virtual
Definition at line 56 of file G4KaonPlusField.cc.
View newest version in sPHENIX GitHub at line 56 of file G4KaonPlusField.cc
G4KaonPlusField::G4KaonPlusField (const G4KaonPlusField & right) private
Member Function Documentation
G4double G4KaonPlusField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 77 of file G4KaonPlusField.cc.
View newest version in sPHENIX GitHub at line 77 of file G4KaonPlusField.cc
References A(), G4V3DNucleus::GetCharge(), G4Pow::GetInstance(), G4V3DNucleus::GetMassNumber(), MeV, G4VNuclearField::theNucleus, Z, and G4Pow::Z13().
Referenced by GetField().
virtual G4double G4KaonPlusField::GetCoeff () inline virtual
Reimplemented from G4VNuclearField.
Definition at line 62 of file G4KaonPlusField.hh.
View newest version in sPHENIX GitHub at line 62 of file G4KaonPlusField.hh
References theCoeff.
G4double G4KaonPlusField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 59 of file G4KaonPlusField.cc.
View newest version in sPHENIX GitHub at line 59 of file G4KaonPlusField.cc
References A(), G4InuclSpecialFunctions::bindingEnergy(), GetBarrier(), G4NucleiProperties::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4VNuclearDensity::GetDensity(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, G4KaonPlus::KaonPlus(), CLHEP::Hep3Vector::mag(), source.hepunit::neutron_mass_c2, pi, source.hepunit::proton_mass_c2, G4VNuclearField::radius, theCoeff, G4VNuclearField::theNucleus, and Z.
G4bool G4KaonPlusField::operator!= (const G4KaonPlusField & right) const private
const G4KaonPlusField& G4KaonPlusField::operator= (const G4KaonPlusField & right) private
G4bool G4KaonPlusField::operator== (const G4KaonPlusField & right) const private
Member Data Documentation
G4double G4KaonPlusField::theCoeff private
Definition at line 65 of file G4KaonPlusField.hh.
View newest version in sPHENIX GitHub at line 65 of file G4KaonPlusField.hh
Referenced by G4KaonPlusField(), GetCoeff(), and GetField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4KaonPlusField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4KaonPlusField.cc