ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/graphics_reps/pyG4VisAttributes.cc File Reference
pyG4VisAttributes.cc File Reference
#include <boost/python.hpp>
#include "G4AttDef.hh"
#include "G4VisAttributes.hh"
Namespaces
namespace pyG4VisAttributes
Functions
void export_G4VisAttributes ()
Variables
void(G4VisAttributes::* pyG4VisAttributes::f1_SetColor)(const G4Color &)
void(G4VisAttributes::* pyG4VisAttributes::f2_SetColor)(G4double, G4double, G4double, G4double)
void(G4VisAttributes::* pyG4VisAttributes::f1_SetColour)(const G4Colour &)
void(G4VisAttributes::* pyG4VisAttributes::f2_SetColour)(G4double, G4double, G4double, G4double)
Function Documentation
void export_G4VisAttributes ()
Definition at line 67 of file pyG4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 67 of file pyG4VisAttributes.cc
References G4VisAttributes::dashed, G4VisAttributes::dotted, pyG4VisAttributes::f1_SetColor, pyG4VisAttributes::f1_SetColour, pyG4VisAttributes::f2_SetColor, pyG4VisAttributes::f2_SetColour, G4VisAttributes::GetColor(), G4VisAttributes::GetColour(), G4VisAttributes::GetForcedDrawingStyle(), G4VisAttributes::GetInvisible(), G4VisAttributes::GetLineStyle(), G4VisAttributes::GetLineWidth(), G4VisAttributes::IsDaughtersInvisible(), G4VisAttributes::IsForceAuxEdgeVisible(), G4VisAttributes::IsForceDrawingStyle(), G4VisAttributes::IsVisible(), G4VisAttributes::SetAttDefs(), G4VisAttributes::SetAttValues(), G4VisAttributes::SetDaughtersInvisible(), G4VisAttributes::SetForceAuxEdgeVisible(), G4VisAttributes::SetForceSolid(), G4VisAttributes::SetForceWireframe(), G4VisAttributes::SetLineStyle(), G4VisAttributes::SetLineWidth(), G4VisAttributes::SetVisibility(), G4VisAttributes::solid, G4VisAttributes::unbroken, and G4VisAttributes::wireframe.
Referenced by BOOST_PYTHON_MODULE().