ECCE @ EIC Software: CLHEP::HepBoost Class Reference
CLHEP::HepBoost Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/Boost.h>
Public Member Functions
HepBoost ()
HepBoost (const HepBoost &m)
HepBoost (HepBoost &&m)=default
HepBoost & operator= (const HepBoost &m)
HepBoost & operator= (HepBoost &&m)=default
HepBoost & set (double betaX, double betaY, double betaZ)
HepBoost (double betaX, double betaY, double betaZ)
HepBoost & set (const HepRep4x4Symmetric &m)
HepBoost (const HepRep4x4Symmetric &m)
HepBoost & set (Hep3Vector direction, double beta)
HepBoost (Hep3Vector direction, double beta)
HepBoost & set (const Hep3Vector &boost)
HepBoost (const Hep3Vector &boost)
HepBoost & set (const HepBoostX &boost)
HepBoost & set (const HepBoostY &boost)
HepBoost & set (const HepBoostZ &boost)
HepBoost (const HepBoostX &boost)
HepBoost (const HepBoostY &boost)
HepBoost (const HepBoostZ &boost)
double beta () const
double gamma () const
Hep3Vector boostVector () const
Hep3Vector getDirection () const
Hep3Vector direction () const
double xx () const
double xy () const
double xz () const
double xt () const
double yx () const
double yy () const
double yz () const
double yt () const
double zx () const
double zy () const
double zz () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
HepRep4x4 rep4x4 () const
HepRep4x4Symmetric rep4x4Symmetric () const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
int compare (const HepBoost &b) const
bool operator== (const HepBoost &b) const
bool operator!= (const HepBoost &b) const
bool operator<= (const HepBoost &b) const
bool operator>= (const HepBoost &b) const
bool operator< (const HepBoost &b) const
bool operator> (const HepBoost &b) const
bool isIdentity () const
double distance2 (const HepBoost &b) const
double distance2 (const HepBoostX &bx) const
double distance2 (const HepBoostY &by) const
double distance2 (const HepBoostZ &bz) const
double distance2 (const HepRotation &r) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &b) const
bool isNear (const HepBoost &b, double epsilon=Hep4RotationInterface::tolerance) const
double howNear (const HepRotation &r) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
HepLorentzVector operator() (const HepLorentzVector &p) const
HepLorentzVector operator* (const HepLorentzVector &p) const
HepLorentzRotation operator* (const HepBoost &b) const
HepLorentzRotation operator* (const HepRotation &r) const
HepLorentzRotation operator* (const HepLorentzRotation &lt) const
HepBoost inverse () const
HepBoost & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepLorentzVector vectorMultiplication (const HepLorentzVector &w) const
HepLorentzRotation matrixMultiplication (const HepRep4x4 &m) const
HepLorentzRotation matrixMultiplication (const HepRep4x4Symmetric &m) const
HepBoost (double xx, double xy, double xz, double xt, double yy, double yz, double yt, double zz, double zt, double tt)
void setBoost (double bx, double by, double bz)
Protected Attributes
HepRep4x4Symmetric rep_
Friends
HepBoost inverseOf (const HepBoost &lt)
Detailed Description
Author
Definition at line 42 of file Boost.h.
View newest version in sPHENIX GitHub at line 42 of file Boost.h
Constructor & Destructor Documentation
CLHEP::HepBoost::HepBoost () inline
Referenced by decompose().
CLHEP::HepBoost::HepBoost (const HepBoost & m) inline
CLHEP::HepBoost::HepBoost (HepBoost && m) inline default
CLHEP::HepBoost::HepBoost (double betaX, double betaY, double betaZ) inline
CLHEP::HepBoost::HepBoost (const HepRep4x4Symmetric & m) inline
CLHEP::HepBoost::HepBoost (Hep3Vector direction, double beta) inline
CLHEP::HepBoost::HepBoost (const Hep3Vector & boost) inline
CLHEP::HepBoost::HepBoost (const HepBoostX & boost) inline
CLHEP::HepBoost::HepBoost (const HepBoostY & boost) inline
CLHEP::HepBoost::HepBoost (const HepBoostZ & boost) inline
CLHEP::HepBoost::HepBoost (double xx, double xy, double xz, double xt, double yy, double yz, double yt, double zz, double zt, double tt) inline protected
Member Function Documentation
double CLHEP::HepBoost::beta () const inline
Referenced by airy2(), airy2d(), dokinematics(), genevent(), getqvec(), print(), py4jet(), py6frm(), pyadsh(), pyapps(), pycjdc(), pygaga(), pygbeh(), pyhext(), pyinom(), pymihk(), pymsin(), pynjdc(), pyprep(), pysfdc(), pythrg(), and pywidt().
Hep3Vector CLHEP::HepBoost::boostVector () const inline
Referenced by decompose(), CLHEP::HepLorentzRotation::decompose(), and print().
HepLorentzVector CLHEP::HepBoost::col1 () const inline
HepLorentzVector CLHEP::HepBoost::col2 () const inline
HepLorentzVector CLHEP::HepBoost::col3 () const inline
HepLorentzVector CLHEP::HepBoost::col4 () const inline
int CLHEP::HepBoost::compare (const HepBoost & b) const inline
void CLHEP::HepBoost::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 69 of file Boost.cc.
View newest version in sPHENIX GitHub at line 69 of file Boost.cc
References boostVector(), and HepBoost().
void CLHEP::HepBoost::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 76 of file Boost.cc.
View newest version in sPHENIX GitHub at line 76 of file Boost.cc
References boostVector().
void CLHEP::HepBoost::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 81 of file Boost.cc.
View newest version in sPHENIX GitHub at line 81 of file Boost.cc
References boostVector(), and HepBoost().
void CLHEP::HepBoost::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 88 of file Boost.cc.
View newest version in sPHENIX GitHub at line 88 of file Boost.cc
References boostVector().
Hep3Vector CLHEP::HepBoost::direction () const inline
double CLHEP::HepBoost::distance2 (const HepBoost & b) const inline
Referenced by CLHEP::HepBoostX::distance2(), CLHEP::HepBoostZ::distance2(), CLHEP::HepBoostY::distance2(), distance2(), CLHEP::HepLorentzRotation::distance2(), howNear(), isNear(), and CLHEP::HepLorentzRotation::isNear().
double CLHEP::HepBoost::distance2 (const HepBoostX & bx) const inline
double CLHEP::HepBoost::distance2 (const HepBoostY & by) const inline
double CLHEP::HepBoost::distance2 (const HepBoostZ & bz) const inline
double CLHEP::HepBoost::distance2 (const HepRotation & r) const
Definition at line 95 of file Boost.cc.
View newest version in sPHENIX GitHub at line 95 of file Boost.cc
References norm2(), and CLHEP::HepRotation::norm2().
double CLHEP::HepBoost::distance2 (const HepLorentzRotation & lt) const
Definition at line 101 of file Boost.cc.
View newest version in sPHENIX GitHub at line 101 of file Boost.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
double CLHEP::HepBoost::gamma () const inline
Referenced by print(), and pyveto().
Hep3Vector CLHEP::HepBoost::getDirection () const inline
static double CLHEP::HepBoost::getTolerance () inline static
double CLHEP::HepBoost::howNear (const HepBoost & b) const inline
double CLHEP::HepBoost::howNear (const HepRotation & r) const
Definition at line 110 of file Boost.cc.
View newest version in sPHENIX GitHub at line 110 of file Boost.cc
References distance2().
double CLHEP::HepBoost::howNear (const HepLorentzRotation & lt) const
Definition at line 114 of file Boost.cc.
View newest version in sPHENIX GitHub at line 114 of file Boost.cc
References distance2().
HepBoost CLHEP::HepBoost::inverse () const inline
HepBoost& CLHEP::HepBoost::invert () inline
bool CLHEP::HepBoost::isIdentity () const inline
bool CLHEP::HepBoost::isNear (const HepBoost & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoost::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 118 of file Boost.cc.
View newest version in sPHENIX GitHub at line 118 of file Boost.cc
References norm2(), and CLHEP::HepRotation::norm2().
bool CLHEP::HepBoost::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 125 of file Boost.cc.
View newest version in sPHENIX GitHub at line 125 of file Boost.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
HepLorentzRotation CLHEP::HepBoost::matrixMultiplication (const HepRep4x4 & m) const protected
Definition at line 180 of file Boost.cc.
View newest version in sPHENIX GitHub at line 180 of file Boost.cc
References r, rep4x4Symmetric(), CLHEP::HepRep4x4::tt_, CLHEP::HepRep4x4Symmetric::tt_, CLHEP::HepRep4x4::tx_, CLHEP::HepRep4x4::ty_, CLHEP::HepRep4x4::tz_, CLHEP::HepRep4x4::xt_, CLHEP::HepRep4x4Symmetric::xt_, CLHEP::HepRep4x4::xx_, CLHEP::HepRep4x4Symmetric::xx_, CLHEP::HepRep4x4::xy_, CLHEP::HepRep4x4Symmetric::xy_, CLHEP::HepRep4x4::xz_, CLHEP::HepRep4x4Symmetric::xz_, CLHEP::HepRep4x4::yt_, CLHEP::HepRep4x4Symmetric::yt_, CLHEP::HepRep4x4::yx_, CLHEP::HepRep4x4::yy_, CLHEP::HepRep4x4Symmetric::yy_, CLHEP::HepRep4x4::yz_, CLHEP::HepRep4x4Symmetric::yz_, CLHEP::HepRep4x4::zt_, CLHEP::HepRep4x4Symmetric::zt_, CLHEP::HepRep4x4::zx_, CLHEP::HepRep4x4::zy_, CLHEP::HepRep4x4::zz_, and CLHEP::HepRep4x4Symmetric::zz_.
Referenced by operator*().
HepLorentzRotation CLHEP::HepBoost::matrixMultiplication (const HepRep4x4Symmetric & m) const protected
Definition at line 205 of file Boost.cc.
View newest version in sPHENIX GitHub at line 205 of file Boost.cc
References r, rep4x4Symmetric(), CLHEP::HepRep4x4Symmetric::tt_, CLHEP::HepRep4x4Symmetric::xt_, CLHEP::HepRep4x4Symmetric::xx_, CLHEP::HepRep4x4Symmetric::xy_, CLHEP::HepRep4x4Symmetric::xz_, CLHEP::HepRep4x4Symmetric::yt_, CLHEP::HepRep4x4Symmetric::yy_, CLHEP::HepRep4x4Symmetric::yz_, CLHEP::HepRep4x4Symmetric::zt_, and CLHEP::HepRep4x4Symmetric::zz_.
double CLHEP::HepBoost::norm2 () const
Definition at line 138 of file Boost.cc.
View newest version in sPHENIX GitHub at line 138 of file Boost.cc
References rep_, CLHEP::HepRep4x4Symmetric::xt_, CLHEP::HepRep4x4Symmetric::yt_, and CLHEP::HepRep4x4Symmetric::zt_.
Referenced by distance2(), CLHEP::HepLorentzRotation::distance2(), isNear(), CLHEP::HepLorentzRotation::isNear(), and CLHEP::HepLorentzRotation::norm2().
bool CLHEP::HepBoost::operator!= (const HepBoost & b) const inline
HepLorentzVector CLHEP::HepBoost::operator() (const HepLorentzVector & p) const inline
HepLorentzVector CLHEP::HepBoost::operator* (const HepLorentzVector & p) const inline
HepLorentzRotation CLHEP::HepBoost::operator* (const HepBoost & b) const
Definition at line 235 of file Boost.cc.
View newest version in sPHENIX GitHub at line 235 of file Boost.cc
References matrixMultiplication(), and rep_.
HepLorentzRotation CLHEP::HepBoost::operator* (const HepRotation & r) const
Definition at line 240 of file Boost.cc.
View newest version in sPHENIX GitHub at line 240 of file Boost.cc
References matrixMultiplication(), and CLHEP::HepRotation::rep4x4().
HepLorentzRotation CLHEP::HepBoost::operator* (const HepLorentzRotation & lt) const
Definition at line 230 of file Boost.cc.
View newest version in sPHENIX GitHub at line 230 of file Boost.cc
References matrixMultiplication(), and CLHEP::HepLorentzRotation::rep4x4().
bool CLHEP::HepBoost::operator< (const HepBoost & b) const inline
bool CLHEP::HepBoost::operator<= (const HepBoost & b) const inline
HepBoost& CLHEP::HepBoost::operator= (const HepBoost & m) inline
HepBoost& CLHEP::HepBoost::operator= (HepBoost && m) inline default
bool CLHEP::HepBoost::operator== (const HepBoost & b) const inline
bool CLHEP::HepBoost::operator> (const HepBoost & b) const inline
bool CLHEP::HepBoost::operator>= (const HepBoost & b) const inline
std::ostream & CLHEP::HepBoost::print (std::ostream & os) const
Definition at line 246 of file Boost.cc.
View newest version in sPHENIX GitHub at line 246 of file Boost.cc
References beta(), boostVector(), gamma(), CLHEP::Hep3Vector::mag(), norm, rep_, and CLHEP::HepRep4x4Symmetric::tt_.
void CLHEP::HepBoost::rectify ()
Definition at line 145 of file Boost.cc.
View newest version in sPHENIX GitHub at line 145 of file Boost.cc
References G4InuclParticleNames::gam, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), tt(), xt(), yt(), and zt().
HepRep4x4 CLHEP::HepBoost::rep4x4 () const inline
Referenced by CLHEP::HepLorentzRotation::set().
HepRep4x4Symmetric CLHEP::HepBoost::rep4x4Symmetric () const inline
Referenced by matrixMultiplication().
HepLorentzVector CLHEP::HepBoost::row1 () const inline
HepLorentzVector CLHEP::HepBoost::row2 () const inline
HepLorentzVector CLHEP::HepBoost::row3 () const inline
HepLorentzVector CLHEP::HepBoost::row4 () const inline
HepBoost & CLHEP::HepBoost::set (double betaX, double betaY, double betaZ)
Definition at line 21 of file Boost.cc.
View newest version in sPHENIX GitHub at line 21 of file Boost.cc
References rep_, CLHEP::HepRep4x4Symmetric::tt_, CLHEP::HepRep4x4Symmetric::xt_, CLHEP::HepRep4x4Symmetric::xx_, CLHEP::HepRep4x4Symmetric::xy_, CLHEP::HepRep4x4Symmetric::xz_, CLHEP::HepRep4x4Symmetric::yt_, CLHEP::HepRep4x4Symmetric::yy_, CLHEP::HepRep4x4Symmetric::yz_, CLHEP::HepRep4x4Symmetric::zt_, and CLHEP::HepRep4x4Symmetric::zz_.
Referenced by CLHEP::HepRotationY::decompose(), CLHEP::HepRotationZ::decompose(), CLHEP::HepRotationX::decompose(), and CLHEP::HepLorentzRotation::decompose().
HepBoost & CLHEP::HepBoost::set (const HepRep4x4Symmetric & m)
Definition at line 42 of file Boost.cc.
View newest version in sPHENIX GitHub at line 42 of file Boost.cc
References rep_.
HepBoost & CLHEP::HepBoost::set (Hep3Vector direction, double beta)
Definition at line 47 of file Boost.cc.
View newest version in sPHENIX GitHub at line 47 of file Boost.cc
References BTOF::length, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
HepBoost & CLHEP::HepBoost::set (const Hep3Vector & boost)
Definition at line 61 of file Boost.cc.
View newest version in sPHENIX GitHub at line 61 of file Boost.cc
References CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
HepBoost& CLHEP::HepBoost::set (const HepBoostX & boost) inline
HepBoost& CLHEP::HepBoost::set (const HepBoostY & boost) inline
HepBoost& CLHEP::HepBoost::set (const HepBoostZ & boost) inline
void CLHEP::HepBoost::setBoost (double bx, double by, double bz) inline protected
static double CLHEP::HepBoost::setTolerance (double tol) inline static
double CLHEP::HepBoost::tt () const inline
Referenced by checkshape(), hijels(), hijing(), pygfxx(), pyhistfu(), pypdpo(), pystfu(), and rectify().
double CLHEP::HepBoost::tx () const inline
Referenced by pyfscr(), pyhistfu(), pypdpo(), and pystfu().
double CLHEP::HepBoost::ty () const inline
Referenced by pyfscr().
double CLHEP::HepBoost::tz () const inline
Referenced by pyfscr().
HepLorentzVector CLHEP::HepBoost::vectorMultiplication (const HepLorentzVector & w) const inline protected
double CLHEP::HepBoost::xt () const inline
Referenced by fjet(), fjetrig(), g(), ghvq(), gphoton(), pyxdif(), and rectify().
double CLHEP::HepBoost::xx () const inline
double CLHEP::HepBoost::xy () const inline
double CLHEP::HepBoost::xz () const inline
double CLHEP::HepBoost::yt () const inline
Referenced by rectify().
double CLHEP::HepBoost::yx () const inline
double CLHEP::HepBoost::yy () const inline
double CLHEP::HepBoost::yz () const inline
double CLHEP::HepBoost::zt () const inline
Referenced by rectify().
double CLHEP::HepBoost::zx () const inline
double CLHEP::HepBoost::zy () const inline
double CLHEP::HepBoost::zz () const inline
Friends And Related Function Documentation
HepBoost inverseOf (const HepBoost & lt) friend
Member Data Documentation
HepRep4x4Symmetric CLHEP::HepBoost::rep_ protected
Definition at line 237 of file Boost.h.
View newest version in sPHENIX GitHub at line 237 of file Boost.h
Referenced by norm2(), operator*(), print(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/Boost.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/Boost.cc