ECCE @ EIC Software: CCalEcalOrganization Class Reference
CCalEcalOrganization Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalEcalOrganization.hh>
Public Member Functions
CCalEcalOrganization ()
~CCalEcalOrganization ()
virtual unsigned int GetUnitID (const G4Step *aStep) const
Public Member Functions inherited from CCalVOrganization
CCalVOrganization ()
virtual ~CCalVOrganization ()
virtual G4int Levels (const G4Step *) const
virtual void DetectorLevel (const G4Step *, G4int &, G4int *, G4String *) const
Additional Inherited Members
Protected Attributes inherited from CCalVOrganization
CCaloOrganization theOrg
Detailed Description
Definition at line 35 of file CCalEcalOrganization.hh.
View newest version in sPHENIX GitHub at line 35 of file CCalEcalOrganization.hh
Constructor & Destructor Documentation
CCalEcalOrganization::CCalEcalOrganization () inline
Definition at line 39 of file CCalEcalOrganization.hh.
View newest version in sPHENIX GitHub at line 39 of file CCalEcalOrganization.hh
CCalEcalOrganization::~CCalEcalOrganization ()
Definition at line 36 of file CCalEcalOrganization.cc.
View newest version in sPHENIX GitHub at line 36 of file CCalEcalOrganization.cc
References G4cout, and G4endl.
Member Function Documentation
unsigned int CCalEcalOrganization::GetUnitID (const G4Step * aStep) const virtual
Implements CCalVOrganization.
Definition at line 41 of file CCalEcalOrganization.cc.
View newest version in sPHENIX GitHub at line 41 of file CCalEcalOrganization.cc
References G4TouchableHistory::GetHistoryDepth(), G4Step::GetPreStepPoint(), G4TouchableHistory::GetReplicaNumber(), G4StepPoint::GetTouchable(), and incremental_prev_tag::idx.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalEcalOrganization.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalEcalOrganization.cc