ECCE @ EIC Software: G4ErrorGeomVolumeTarget Class Reference
G4ErrorGeomVolumeTarget Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorGeomVolumeTarget.hh>
Public Member Functions
G4ErrorGeomVolumeTarget (const G4String &name)
virtual ~G4ErrorGeomVolumeTarget ()
virtual G4bool TargetReached (const G4Step *aStep)
virtual void Dump (const G4String &msg) const
Public Member Functions inherited from G4ErrorTarget
G4ErrorTarget ()
virtual ~G4ErrorTarget ()
virtual G4double GetDistanceFromPoint (const G4ThreeVector &, const G4ThreeVector &) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &) const
G4ErrorTargetType GetType () const
Private Attributes
G4String theName
Additional Inherited Members
Protected Attributes inherited from G4ErrorTarget
G4ErrorTargetType theType
Detailed Description
Definition at line 47 of file G4ErrorGeomVolumeTarget.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ErrorGeomVolumeTarget.hh
Constructor & Destructor Documentation
G4ErrorGeomVolumeTarget::G4ErrorGeomVolumeTarget (const G4String & name)
Definition at line 42 of file G4ErrorGeomVolumeTarget.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ErrorGeomVolumeTarget.cc
References G4ErrorTarget_GeomVolume, theName, and G4ErrorTarget::theType.
virtual G4ErrorGeomVolumeTarget::~G4ErrorGeomVolumeTarget () inline virtual
Definition at line 52 of file G4ErrorGeomVolumeTarget.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ErrorGeomVolumeTarget.hh
Member Function Documentation
void G4ErrorGeomVolumeTarget::Dump (const G4String & msg) const virtual
Implements G4ErrorTarget.
Definition at line 72 of file G4ErrorGeomVolumeTarget.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ErrorGeomVolumeTarget.cc
References G4cout, G4endl, and theName.
G4bool G4ErrorGeomVolumeTarget::TargetReached (const G4Step * aStep) virtual
Reimplemented from G4ErrorTarget.
Definition at line 50 of file G4ErrorGeomVolumeTarget.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ErrorGeomVolumeTarget.cc
References G4cout, G4endl, G4VPhysicalVolume::GetName(), G4Track::GetNextVolume(), G4Step::GetTrack(), theName, and G4ErrorPropagatorData::verbose().
Member Data Documentation
G4String G4ErrorGeomVolumeTarget::theName private
Definition at line 61 of file G4ErrorGeomVolumeTarget.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ErrorGeomVolumeTarget.hh
Referenced by Dump(), G4ErrorGeomVolumeTarget(), and TargetReached().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorGeomVolumeTarget.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorGeomVolumeTarget.cc