ECCE @ EIC Software: FW::Geant4::MMRunAction Class Reference
FW::Geant4::MMRunAction Class Reference
The material mapping run action.
#include <acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMRunAction.hpp>
Public Member Functions
MMRunAction ()
Constructor.
~MMRunAction () override
Destructor.
void BeginOfRunAction (const G4Run *) finaloverride
void EndOfRunAction (const G4Run *) finaloverride
Interface method at the end of the run.
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Static Public Member Functions
static MMRunAction * Instance ()
Static access method.
Static Private Attributes
static MMRunAction * fgInstance = nullptr
Instance of the EventAction.
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
The material mapping run action.
The MMRunAction class is the implementation of the Geant4 class G4UserRunAction. It initiates the run an resets the EventAction
Definition at line 33 of file MMRunAction.hpp.
View newest version in sPHENIX GitHub at line 33 of file MMRunAction.hpp
Constructor & Destructor Documentation
FW::Geant4::MMRunAction::MMRunAction ()
Constructor.
Definition at line 18 of file MMRunAction.cpp.
View newest version in sPHENIX GitHub at line 18 of file MMRunAction.cpp
References fgInstance.
FW::Geant4::MMRunAction::~MMRunAction () override
Destructor.
Definition at line 26 of file MMRunAction.cpp.
View newest version in sPHENIX GitHub at line 26 of file MMRunAction.cpp
Member Function Documentation
void FW::Geant4::MMRunAction::BeginOfRunAction (const G4Run * aRun) final override virtual
Interface method at the begin of the run
Note
resets the event action
Reimplemented from G4UserRunAction.
Definition at line 34 of file MMRunAction.cpp.
View newest version in sPHENIX GitHub at line 34 of file MMRunAction.cpp
References G4cout, G4endl, G4Run::GetRunID(), FW::Geant4::MMEventAction::Instance(), and FW::Geant4::MMEventAction::Reset().
void FW::Geant4::MMRunAction::EndOfRunAction (const G4Run * aRun) final override virtual
Interface method at the end of the run.
Reimplemented from G4UserRunAction.
Definition at line 40 of file MMRunAction.cpp.
View newest version in sPHENIX GitHub at line 40 of file MMRunAction.cpp
References G4cout, G4endl, and G4Run::GetNumberOfEvent().
FW::Geant4::MMRunAction * FW::Geant4::MMRunAction::Instance () static
Static access method.
Definition at line 30 of file MMRunAction.cpp.
View newest version in sPHENIX GitHub at line 30 of file MMRunAction.cpp
Member Data Documentation
FW::Geant4::MMRunAction * FW::Geant4::MMRunAction::fgInstance = nullptr static private
Instance of the EventAction.
Definition at line 53 of file MMRunAction.hpp.
View newest version in sPHENIX GitHub at line 53 of file MMRunAction.hpp
Referenced by MMRunAction().
The documentation for this class was generated from the following files:
acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMRunAction.hpp
acts/blob/master/Examples/Algorithms/Geant4/src/MMRunAction.cpp