ECCE @ EIC Software: G4ITNavigator2 Class Reference
G4ITNavigator2 Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITNavigator2.hh>
Classes
struct G4NavigatorState
struct G4SaveNavigatorState
Public Member Functions
G4ITNavigator2 ()
virtual ~G4ITNavigator2 ()
G4ITNavigatorState_Lock2 * GetNavigatorState ()
void SetNavigatorState (G4ITNavigatorState_Lock2 *)
void NewNavigatorState ()
void NewNavigatorState (const G4TouchableHistory &h)
void ResetNavigatorState ()
G4VPhysicalVolume * NewNavigatorStateAndLocate (const G4ThreeVector &p, const G4ThreeVector &direction)
void CheckNavigatorState () const
std::shared_ptr
< G4ITNavigatorState_Lock2 > GetSnapshotOfState ()
void ResetFromSnapshot (std::shared_ptr< G4ITNavigatorState_Lock2 >)
virtual G4double ComputeStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
G4double CheckNextStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
virtual G4VPhysicalVolume * ResetHierarchyAndLocate (const G4ThreeVector &point, const G4ThreeVector &direction, const G4TouchableHistory &h)
virtual G4VPhysicalVolume * LocateGlobalPointAndSetup (const G4ThreeVector &point, const G4ThreeVector *direction=0, const G4bool pRelativeSearch=true, const G4bool ignoreDirection=true)
EInside InsideCurrentVolume (const G4ThreeVector &globalPoint) const
void GetRandomInCurrentVolume (G4ThreeVector &rndmPoint) const
virtual void LocateGlobalPointWithinVolume (const G4ThreeVector &position)
void LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector &position, const G4ThreeVector &direction, G4TouchableHandle &oldTouchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, const G4ThreeVector &direction, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void SetGeometricallyLimitedStep ()
virtual G4double ComputeSafety (const G4ThreeVector &globalpoint, const G4double pProposedMaxLength=DBL_MAX, const G4bool keepState=true)
virtual G4bool RecheckDistanceToCurrentBoundary (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double CurrentProposedStepLength, G4double *prDistance, G4double *prNewSafety=0) const
G4VPhysicalVolume * GetWorldVolume () const
void SetWorldVolume (G4VPhysicalVolume *pWorld)
G4GRSVolume * CreateGRSVolume () const
G4GRSSolid * CreateGRSSolid () const
G4TouchableHistory * CreateTouchableHistory () const
G4TouchableHistory * CreateTouchableHistory (const G4NavigationHistory *) const
virtual G4TouchableHistoryHandle CreateTouchableHistoryHandle () const
virtual G4ThreeVector GetLocalExitNormal (G4bool *valid)
virtual G4ThreeVector GetLocalExitNormalAndCheck (const G4ThreeVector &point, G4bool *valid)
virtual G4ThreeVector GetGlobalExitNormal (const G4ThreeVector &point, G4bool *valid)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
G4bool IsActive () const
void Activate (G4bool flag)
G4bool EnteredDaughterVolume () const
G4bool ExitedMotherVolume () const
void CheckMode (G4bool mode)
G4bool IsCheckModeActive () const
void SetPushVerbosity (G4bool mode)
void PrintState () const
const G4AffineTransform & GetGlobalToLocalTransform () const
const G4AffineTransform GetLocalToGlobalTransform () const
G4AffineTransform GetMotherToDaughterTransform (G4VPhysicalVolume *dVolume, G4int dReplicaNo, EVolume dVolumeType)
void ResetStackAndState ()
G4int SeverityOfZeroStepping (G4int *noZeroSteps) const
G4ThreeVector GetCurrentLocalCoordinate () const
G4ThreeVector NetTranslation () const
G4RotationMatrix NetRotation () const
void EnableBestSafety (G4bool value=false)
Public Attributes
G4NavigatorState * fpNavigatorState
G4VPhysicalVolume * fTopPhysical
G4bool fCheck
G4bool fWarnPush
G4NormalNavigation fnormalNav
G4VoxelNavigation fvoxelNav
G4ParameterisedNavigation fparamNav
G4ReplicaNavigation freplicaNav
G4RegularNavigation fregularNav
G4VoxelSafety * fpVoxelSafety
Static Public Attributes
static const G4int fMaxNav = 8
Protected Member Functions
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &rGlobPoint) const
G4ThreeVector ComputeLocalAxis (const G4ThreeVector &pVec) const
virtual void ResetState ()
EVolume VolumeType (const G4VPhysicalVolume *pVol) const
EVolume CharacteriseDaughters (const G4LogicalVolume *pLog) const
G4int GetDaughtersRegularStructureId (const G4LogicalVolume *pLog) const
virtual void SetupHierarchy ()
Protected Attributes
G4double kCarTolerance
G4int fVerbose
Private Member Functions
G4ITNavigator2 (const G4ITNavigator2 &)
G4ITNavigator2 & operator= (const G4ITNavigator2 &)
void ComputeStepLog (const G4ThreeVector &pGlobalpoint, G4double moveLenSq) const
Private Attributes
G4bool fActive
G4int fActionThreshold_NoZeroSteps
G4int fAbandonThreshold_NoZeroSteps
Friends
std::ostream & operator<< (std::ostream &os, const G4ITNavigator2 &n)
Detailed Description
Definition at line 101 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ITNavigator2.hh
Constructor & Destructor Documentation
G4ITNavigator2::G4ITNavigator2 ()
Definition at line 99 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ITNavigator2.cc
References fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, fActive, fnormalNav, fpNavigatorState, fpVoxelSafety, fregularNav, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, and G4RegularNavigation::SetNormalNavigation().
G4ITNavigator2::~G4ITNavigator2 () virtual
Definition at line 122 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 122 of file G4ITNavigator2.cc
References fpVoxelSafety.
G4ITNavigator2::G4ITNavigator2 (const G4ITNavigator2 &) private
Member Function Documentation
void G4ITNavigator2::Activate (G4bool flag) inline
EVolume G4ITNavigator2::CharacteriseDaughters (const G4LogicalVolume * pLog) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
void G4ITNavigator2::CheckMode (G4bool mode) inline
void G4ITNavigator2::CheckNavigatorState () const
Definition at line 708 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 708 of file G4ITNavigator2.cc
References FatalException, fpNavigatorState, and G4Exception().
G4double G4ITNavigator2::CheckNextStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety)
Definition at line 1375 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1375 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, ComputeStep(), fpNavigatorState, and Acts::Test::step().
G4ThreeVector G4ITNavigator2::ComputeLocalAxis (const G4ThreeVector & pVec) const inline protected
Referenced by ComputeStep(), and RecheckDistanceToCurrentBoundary().
G4ThreeVector G4ITNavigator2::ComputeLocalPoint (const G4ThreeVector & rGlobPoint) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointWithinVolume(), and RecheckDistanceToCurrentBoundary().
G4double G4ITNavigator2::ComputeSafety (const G4ThreeVector & globalpoint, const G4double pProposedMaxLength = DBL_MAX, const G4bool keepState = true) virtual
Definition at line 1924 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1924 of file G4ITNavigator2.cc
References CharacteriseDaughters(), CheckNavigatorStateIsValid, ComputeLocalPoint(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4RegularNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), FatalException, fEnteredDaughter, fExitedMother, fHistory, fnormalNav, fparamNav, fpNavigatorState, fPreviousSafety, fPreviousSftOrigin, fpVoxelSafety, fregularNav, freplicaNav, fStepEndPoint, fVerbose, fvoxelNav, G4cout, G4endl, G4Exception(), GetDaughtersRegularStructureId(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetVoxelHeader(), kCarTolerance, kExternal, kNormal, kParameterised, kReplica, LocateGlobalPointWithinVolume(), and PrintState().
G4double G4ITNavigator2::ComputeStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety) virtual
Definition at line 924 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 924 of file G4ITNavigator2.cc
References CharacteriseDaughters(), CheckNavigatorStateIsValid, G4VPhysicalVolume::CheckOverlaps(), ComputeLocalAxis(), ComputeLocalPoint(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), ComputeStepLog(), incremental_prev_tag::desc, EventMustBeAborted, fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fCalculatedExitNormal, fChangedGrandMotherRefFrame, fEnteredDaughter, fEntering, fExitedMother, fExiting, fExitNormal, fExitNormalGlobalFrame, fGrandMotherExitNormal, fHistory, fLastLocatedPointLocal, fLastStepEndPointLocal, fLastStepWasZero, fLastTriedStepComputation, fLocatedOnEdge, fnormalNav, fNumberZeroSteps, fparamNav, fPreviousSafety, fPreviousSftOrigin, fPushed, fregularNav, freplicaNav, fStepEndPoint, fValidExitNormal, fVerbose, fvoxelNav, fWarnPush, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4VPhysicalVolume::GetCopyNo(), GetDaughtersRegularStructureId(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4LogicalVolume::GetVoxelHeader(), JustWarning, kCarTolerance, kExternal, kInfinity, kNormal, kParameterised, kReplica, LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), message(), min, PrintState(), G4VSolid::SurfaceNormal(), and G4AffineTransform::TransformAxis().
Referenced by CheckNextStep().
void G4ITNavigator2::ComputeStepLog (const G4ThreeVector & pGlobalpoint, G4double moveLenSq) const private
Definition at line 2340 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2340 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, fHistory, fLastLocatedPointLocal, fPreviousSafety, fPreviousSftOrigin, G4cerr, G4cout, G4endl, G4Exception(), G4ThreadLocal, JustWarning, kCarTolerance, message(), mm, and sqr().
Referenced by ComputeStep().
G4GRSSolid* G4ITNavigator2::CreateGRSSolid () const inline
G4GRSVolume* G4ITNavigator2::CreateGRSVolume () const inline
G4TouchableHistory* G4ITNavigator2::CreateTouchableHistory () const inline
Referenced by CreateTouchableHistoryHandle().
G4TouchableHistory* G4ITNavigator2::CreateTouchableHistory (const G4NavigationHistory *) const inline
G4TouchableHistoryHandle G4ITNavigator2::CreateTouchableHistoryHandle () const virtual
Definition at line 2266 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2266 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, and CreateTouchableHistory().
void G4ITNavigator2::EnableBestSafety (G4bool value = false) inline
G4bool G4ITNavigator2::EnteredDaughterVolume () const inline
Referenced by GetLocalExitNormal().
G4bool G4ITNavigator2::ExitedMotherVolume () const inline
G4ThreeVector G4ITNavigator2::GetCurrentLocalCoordinate () const inline
G4int G4ITNavigator2::GetDaughtersRegularStructureId (const G4LogicalVolume * pLog) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
G4ThreeVector G4ITNavigator2::GetGlobalExitNormal (const G4ThreeVector & point, G4bool * valid) virtual
Definition at line 1771 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1771 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, fCalculatedExitNormal, fEntering, fExiting, fExitNormalGlobalFrame, fLastTriedStepComputation, fStepEndPoint, fVerbose, G4endl, G4Exception(), GetLocalExitNormalAndCheck(), GetLocalToGlobalTransform(), GetVerboseLevel(), JustWarning, kCarTolerance, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), message(), CLHEP::perMillion, perMillion, SetVerboseLevel(), G4AffineTransform::TransformAxis(), and CLHEP::Hep3Vector::unit().
const G4AffineTransform& G4ITNavigator2::GetGlobalToLocalTransform () const inline
Referenced by GetLocalExitNormalAndCheck(), and InsideCurrentVolume().
G4ThreeVector G4ITNavigator2::GetLocalExitNormal (G4bool * valid) virtual
Definition at line 1521 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1521 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, incremental_prev_tag::desc, G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), EnteredDaughterVolume(), FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fCalculatedExitNormal, fCheck, fEntering, fExitedMother, fExiting, fGrandMotherExitNormal, fHistory, fLastLocatedPointLocal, fLastStepEndPointLocal, fLastTriedStepComputation, fVerbose, G4endl, G4Exception(), G4VSolid::GetEntityType(), GetMotherToDaughterTransform(), G4VSolid::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetSolid(), G4VSolid::Inside(), JustWarning, kCarTolerance, kInside, kOutside, kSurface, CLHEP::Hep3Vector::mag2(), message(), CLHEP::perMillion, G4VSolid::SurfaceNormal(), G4AffineTransform::TransformPoint(), and VolumeType().
Referenced by GetLocalExitNormalAndCheck().
G4ThreeVector G4ITNavigator2::GetLocalExitNormalAndCheck (const G4ThreeVector & point, G4bool * valid) virtual
Definition at line 1735 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1735 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, fLastTriedStepComputation, GetGlobalToLocalTransform(), GetLocalExitNormal(), and G4AffineTransform::TransformPoint().
Referenced by GetGlobalExitNormal().
const G4AffineTransform G4ITNavigator2::GetLocalToGlobalTransform () const inline
Referenced by GetGlobalExitNormal(), and GetRandomInCurrentVolume().
G4AffineTransform G4ITNavigator2::GetMotherToDaughterTransform (G4VPhysicalVolume * dVolume, G4int dReplicaNo, EVolume dVolumeType)
Definition at line 1683 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1683 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), FatalException, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetRotation(), G4VPhysicalVolume::GetTranslation(), kExternal, kNormal, kParameterised, kReplica, and G4LogicalVolume::SetSolid().
Referenced by GetLocalExitNormal().
G4ITNavigatorState_Lock2 * G4ITNavigator2::GetNavigatorState ()
Definition at line 723 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 723 of file G4ITNavigator2.cc
References fpNavigatorState.
void G4ITNavigator2::GetRandomInCurrentVolume (G4ThreeVector & rndmPoint) const
Definition at line 2534 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2534 of file G4ITNavigator2.cc
References G4VSolid::CalculateExtent(), fHistory, G4UniformRand, GetLocalToGlobalTransform(), G4VSolid::Inside(), kInside, BoundingBox::kMax, BoundingBox::kMin, kXAxis, kYAxis, kZAxis, max, min, and G4AffineTransform::TransformPoint().
std::shared_ptr<G4ITNavigatorState_Lock2> G4ITNavigator2::GetSnapshotOfState () inline
G4int G4ITNavigator2::GetVerboseLevel () const inline
Referenced by GetGlobalExitNormal().
G4VPhysicalVolume* G4ITNavigator2::GetWorldVolume () const inline
EInside G4ITNavigator2::InsideCurrentVolume (const G4ThreeVector & globalPoint) const
Definition at line 2522 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2522 of file G4ITNavigator2.cc
References fHistory, GetGlobalToLocalTransform(), Acts::Test::transform, and G4AffineTransform::TransformPoint().
G4bool G4ITNavigator2::IsActive () const inline
G4bool G4ITNavigator2::IsCheckModeActive () const inline
G4VPhysicalVolume * G4ITNavigator2::LocateGlobalPointAndSetup (const G4ThreeVector & point, const G4ThreeVector * direction = 0, const G4bool pRelativeSearch = true, const G4bool ignoreDirection = true) virtual
Definition at line 158 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 158 of file G4ITNavigator2.cc
References G4ReplicaNavigation::BackLocate(), CharacteriseDaughters(), CheckNavigatorStateIsValid, G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), G4ReplicaNavigation::ComputeTransformation(), CLHEP::Hep3Vector::dot(), FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fChangedGrandMotherRefFrame, fCheck, fEnteredDaughter, fEntering, fExitedMother, fExiting, fGrandMotherExitNormal, fHistory, fLastLocatedPointLocal, fLastTriedStepComputation, fLocatedOnEdge, fLocatedOutsideWorld, fnormalNav, fparamNav, fregularNav, freplicaNav, fValidExitNormal, fVerbose, fvoxelNav, fWasLimitedByGeometry, G4cout, G4endl, G4Exception(), GetDaughtersRegularStructureId(), G4VPhysicalVolume::GetLogicalVolume(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetVoxelHeader(), G4VSolid::Inside(), kExternal, kNormal, kOutside, kParameterised, kReplica, kSurface, G4RegularNavigation::LevelLocate(), G4NormalNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4VoxelNavigation::LevelLocate(), G4ReplicaNavigation::LevelLocate(), CLHEP::normal(), PrintState(), ResetStackAndState(), G4LogicalVolume::SetSolid(), G4VSolid::SurfaceNormal(), G4LogicalVolume::UpdateMaterial(), and VolumeType().
Referenced by ComputeStep(), NewNavigatorStateAndLocate(), and ResetHierarchyAndLocate().
void G4ITNavigator2::LocateGlobalPointAndUpdateTouchable (const G4ThreeVector & position, const G4ThreeVector & direction, G4VTouchable * touchableToUpdate, const G4bool RelativeSearch = true) inline
void G4ITNavigator2::LocateGlobalPointAndUpdateTouchable (const G4ThreeVector & position, G4VTouchable * touchableToUpdate, const G4bool RelativeSearch = true) inline
void G4ITNavigator2::LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector & position, const G4ThreeVector & direction, G4TouchableHandle & oldTouchableToUpdate, const G4bool RelativeSearch = true) inline
void G4ITNavigator2::LocateGlobalPointWithinVolume (const G4ThreeVector & position) virtual
Definition at line 630 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 630 of file G4ITNavigator2.cc
References CharacteriseDaughters(), CheckNavigatorStateIsValid, ComputeLocalPoint(), FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fChangedGrandMotherRefFrame, fEnteredDaughter, fEntering, fExitedMother, fExiting, fHistory, fLastLocatedPointLocal, fLastTriedStepComputation, fparamNav, fVerbose, fvoxelNav, fWasLimitedByGeometry, G4cout, G4endl, G4Exception(), GetDaughtersRegularStructureId(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetVoxelHeader(), kExternal, kNormal, kParameterised, kReplica, G4ParameterisedNavigation::ParamVoxelLocate(), and G4VoxelNavigation::VoxelLocate().
Referenced by ComputeSafety(), and ComputeStep().
G4RotationMatrix G4ITNavigator2::NetRotation () const inline
G4ThreeVector G4ITNavigator2::NetTranslation () const inline
void G4ITNavigator2::NewNavigatorState ()
Definition at line 741 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 741 of file G4ITNavigator2.cc
References FatalException, fHistory, fpNavigatorState, fTopPhysical, G4Exception(), and SetupHierarchy().
void G4ITNavigator2::NewNavigatorState (const G4TouchableHistory & h)
Definition at line 758 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 758 of file G4ITNavigator2.cc
References FatalException, fHistory, fLastTriedStepComputation, fpNavigatorState, fTopPhysical, G4Exception(), G4TouchableHistory::GetHistory(), and SetupHierarchy().
G4VPhysicalVolume * G4ITNavigator2::NewNavigatorStateAndLocate (const G4ThreeVector & p, const G4ThreeVector & direction)
Definition at line 776 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 776 of file G4ITNavigator2.cc
References FatalException, fHistory, fpNavigatorState, fTopPhysical, G4Exception(), LocateGlobalPointAndSetup(), and SetupHierarchy().
G4ITNavigator2& G4ITNavigator2::operator= (const G4ITNavigator2 &) private
void G4ITNavigator2::PrintState () const
Definition at line 2276 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2276 of file G4ITNavigator2.cc
References CheckNavigatorStateIsValid, fBlockedPhysicalVolume, fBlockedReplicaNo, fEntering, fExiting, fExitNormal, fLastLocatedPointLocal, fLastStepWasZero, fPreviousSafety, fPreviousSftOrigin, fValidExitNormal, fVerbose, G4cout, and G4endl.
Referenced by ComputeSafety(), ComputeStep(), and LocateGlobalPointAndSetup().
G4bool G4ITNavigator2::RecheckDistanceToCurrentBoundary (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double CurrentProposedStepLength, G4double * prDistance, G4double * prNewSafety = 0) const virtual
Definition at line 2100 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2100 of file G4ITNavigator2.cc
References G4LogicalVolume::CharacteriseDaughters(), ComputeLocalAxis(), ComputeLocalPoint(), DBL_MAX, G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), FatalException, fBlockedPhysicalVolume, fEnteredDaughter, fHistory, fLastTriedStepComputation, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4VPhysicalVolume::GetTranslation(), G4VSolid::Inside(), kInside, kOutside, kReplica, and min.
void G4ITNavigator2::ResetFromSnapshot (std::shared_ptr< G4ITNavigatorState_Lock2 >) inline
G4VPhysicalVolume * G4ITNavigator2::ResetHierarchyAndLocate (const G4ThreeVector & point, const G4ThreeVector & direction, const G4TouchableHistory & h) virtual
Definition at line 130 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 130 of file G4ITNavigator2.cc
References fHistory, fLastTriedStepComputation, G4TouchableHistory::GetHistory(), LocateGlobalPointAndSetup(), and SetupHierarchy().
void G4ITNavigator2::ResetNavigatorState ()
Definition at line 736 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 736 of file G4ITNavigator2.cc
References fpNavigatorState.
void G4ITNavigator2::ResetStackAndState () inline
Referenced by LocateGlobalPointAndSetup().
void G4ITNavigator2::ResetState () protected virtual
Definition at line 1413 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1413 of file G4ITNavigator2.cc
References fBlockedPhysicalVolume, fBlockedReplicaNo, fCalculatedExitNormal, fChangedGrandMotherRefFrame, fEnteredDaughter, fEntering, fExitedMother, fExiting, fExitNormal, fExitNormalGlobalFrame, fGrandMotherExitNormal, fLastLocatedPointLocal, fLastStepWasZero, fLocatedOnEdge, fLocatedOutsideWorld, fNumberZeroSteps, fPreviousSafety, fPreviousSftOrigin, fPushed, fValidExitNormal, fWasLimitedByGeometry, and kInfinity.
void G4ITNavigator2::SetGeometricallyLimitedStep () inline
void G4ITNavigator2::SetNavigatorState (G4ITNavigatorState_Lock2 * navState)
Definition at line 728 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 728 of file G4ITNavigator2.cc
References fpNavigatorState, and SetupHierarchy().
void G4ITNavigator2::SetPushVerbosity (G4bool mode) inline
void G4ITNavigator2::SetupHierarchy () protected virtual
Definition at line 1452 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 1452 of file G4ITNavigator2.cc
References G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), G4ReplicaNavigation::ComputeTransformation(), FatalException, fHistory, freplicaNav, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4VPVParameterisation::IsNested(), kExternal, kNormal, kParameterised, kReplica, G4TouchableHistory::MoveUpHistory(), G4LogicalVolume::SetSolid(), and G4LogicalVolume::UpdateMaterial().
Referenced by NewNavigatorState(), NewNavigatorStateAndLocate(), ResetHierarchyAndLocate(), and SetNavigatorState().
void G4ITNavigator2::SetVerboseLevel (G4int level) inline
Referenced by GetGlobalExitNormal().
void G4ITNavigator2::SetWorldVolume (G4VPhysicalVolume * pWorld) inline
G4int G4ITNavigator2::SeverityOfZeroStepping (G4int * noZeroSteps) const inline
EVolume G4ITNavigator2::VolumeType (const G4VPhysicalVolume * pVol) const inline protected
Referenced by GetLocalExitNormal(), and LocateGlobalPointAndSetup().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4ITNavigator2 & n) friend
Definition at line 2444 of file G4ITNavigator2.cc.
View newest version in sPHENIX GitHub at line 2444 of file G4ITNavigator2.cc
Member Data Documentation
G4int G4ITNavigator2::fAbandonThreshold_NoZeroSteps private
Definition at line 421 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 421 of file G4ITNavigator2.hh
Referenced by ComputeStep(), and G4ITNavigator2().
G4int G4ITNavigator2::fActionThreshold_NoZeroSteps private
Definition at line 419 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 419 of file G4ITNavigator2.hh
Referenced by ComputeStep(), and G4ITNavigator2().
G4bool G4ITNavigator2::fActive private
Definition at line 416 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 416 of file G4ITNavigator2.hh
Referenced by G4ITNavigator2().
G4bool G4ITNavigator2::fCheck
Definition at line 585 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 585 of file G4ITNavigator2.hh
Referenced by GetLocalExitNormal(), and LocateGlobalPointAndSetup().
const G4int G4ITNavigator2::fMaxNav = 8 static
Definition at line 104 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ITNavigator2.hh
G4NormalNavigation G4ITNavigator2::fnormalNav
Definition at line 593 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 593 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), G4ITNavigator2(), and LocateGlobalPointAndSetup().
G4ParameterisedNavigation G4ITNavigator2::fparamNav
Definition at line 595 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 595 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
G4NavigatorState* G4ITNavigator2::fpNavigatorState
Definition at line 541 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 541 of file G4ITNavigator2.hh
Referenced by CheckNavigatorState(), CheckNextStep(), ComputeSafety(), G4ITNavigator2(), GetNavigatorState(), NewNavigatorState(), NewNavigatorStateAndLocate(), ResetNavigatorState(), and SetNavigatorState().
G4VoxelSafety* G4ITNavigator2::fpVoxelSafety
Definition at line 598 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 598 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), G4ITNavigator2(), and ~G4ITNavigator2().
G4RegularNavigation G4ITNavigator2::fregularNav
Definition at line 597 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 597 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), G4ITNavigator2(), and LocateGlobalPointAndSetup().
G4ReplicaNavigation G4ITNavigator2::freplicaNav
Definition at line 596 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 596 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and SetupHierarchy().
G4VPhysicalVolume* G4ITNavigator2::fTopPhysical
Definition at line 579 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 579 of file G4ITNavigator2.hh
Referenced by NewNavigatorState(), and NewNavigatorStateAndLocate().
G4int G4ITNavigator2::fVerbose protected
Definition at line 411 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 411 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), and PrintState().
G4VoxelNavigation G4ITNavigator2::fvoxelNav
Definition at line 594 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 594 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
G4bool G4ITNavigator2::fWarnPush
Definition at line 588 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 588 of file G4ITNavigator2.hh
Referenced by ComputeStep().
G4double G4ITNavigator2::kCarTolerance protected
Definition at line 408 of file G4ITNavigator2.hh.
View newest version in sPHENIX GitHub at line 408 of file G4ITNavigator2.hh
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), G4ITNavigator2(), GetGlobalExitNormal(), and GetLocalExitNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITNavigator2.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITNavigator2.cc