ECCE @ EIC Software: G4TrajectoryDrawByEncounteredVolume Class Reference
G4TrajectoryDrawByEncounteredVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByEncounteredVolume.hh>
Public Member Functions
G4TrajectoryDrawByEncounteredVolume (const G4String &name="Unspecified", G4VisTrajContext *context=0)
virtual ~G4TrajectoryDrawByEncounteredVolume ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const
virtual void Print (std::ostream &ostr) const
void SetDefault (const G4String &)
void SetDefault (const G4Colour &)
void Set (const G4String &pvname, const G4String &colour)
void Set (const G4String &pvname, const G4Colour &colour)
Public Member Functions inherited from G4VTrajectoryModel
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Private Attributes
G4ModelColourMap< G4String > fMap
G4Colour fDefault
Detailed Description
Definition at line 43 of file G4TrajectoryDrawByEncounteredVolume.hh.
View newest version in sPHENIX GitHub at line 43 of file G4TrajectoryDrawByEncounteredVolume.hh
Constructor & Destructor Documentation
G4TrajectoryDrawByEncounteredVolume::G4TrajectoryDrawByEncounteredVolume (const G4String & name = "Unspecified", G4VisTrajContext * context = 0)
Definition at line 39 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 39 of file G4TrajectoryDrawByEncounteredVolume.cc
G4TrajectoryDrawByEncounteredVolume::~G4TrajectoryDrawByEncounteredVolume () virtual
Definition at line 44 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 44 of file G4TrajectoryDrawByEncounteredVolume.cc
Member Function Documentation
void G4TrajectoryDrawByEncounteredVolume::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const virtual
Implements G4VTrajectoryModel.
Definition at line 47 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TrajectoryDrawByEncounteredVolume.cc
References G4VTrajectoryPoint::CreateAttValues(), G4TrajectoryDrawerUtils::DrawLineAndPoints(), fDefault, G4String::first(), fMap, G4cout, G4endl, G4Exception(), G4ModelColourMap< T >::GetBasicMap(), G4ModelColourMap< T >::GetColour(), G4VTrajectoryModel::GetContext(), G4RichTrajectory::GetPoint(), G4RichTrajectory::GetPointEntries(), G4VTrajectoryModel::GetVerbose(), JustWarning, G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and G4VisTrajContext::SetLineColour().
void G4TrajectoryDrawByEncounteredVolume::Print (std::ostream & ostr) const virtual
Implements G4VTrajectoryModel.
Definition at line 139 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 139 of file G4TrajectoryDrawByEncounteredVolume.cc
References fDefault, fMap, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and G4ModelColourMap< T >::Print().
void G4TrajectoryDrawByEncounteredVolume::Set (const G4String & pvname, const G4String & colour)
Definition at line 127 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 127 of file G4TrajectoryDrawByEncounteredVolume.cc
References fMap, and G4ModelColourMap< T >::Set().
void G4TrajectoryDrawByEncounteredVolume::Set (const G4String & pvname, const G4Colour & colour)
Definition at line 133 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 133 of file G4TrajectoryDrawByEncounteredVolume.cc
References fMap.
void G4TrajectoryDrawByEncounteredVolume::SetDefault (const G4String & colour)
Definition at line 103 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 103 of file G4TrajectoryDrawByEncounteredVolume.cc
References G4Exception(), G4Colour::GetColour(), and JustWarning.
void G4TrajectoryDrawByEncounteredVolume::SetDefault (const G4Colour & colour)
Definition at line 121 of file G4TrajectoryDrawByEncounteredVolume.cc.
View newest version in sPHENIX GitHub at line 121 of file G4TrajectoryDrawByEncounteredVolume.cc
References fDefault.
Member Data Documentation
G4Colour G4TrajectoryDrawByEncounteredVolume::fDefault private
Definition at line 69 of file G4TrajectoryDrawByEncounteredVolume.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TrajectoryDrawByEncounteredVolume.hh
Referenced by Draw(), Print(), and SetDefault().
G4ModelColourMap<G4String> G4TrajectoryDrawByEncounteredVolume::fMap private
Definition at line 68 of file G4TrajectoryDrawByEncounteredVolume.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrajectoryDrawByEncounteredVolume.hh
Referenced by Draw(), Print(), and Set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByEncounteredVolume.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryDrawByEncounteredVolume.cc