ECCE @ EIC Software: G4teoCrossSection Class Reference
G4teoCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4teoCrossSection.hh>
Public Member Functions
G4teoCrossSection (const G4String &name)
virtual ~G4teoCrossSection ()
std::vector< G4double > GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy=0, const G4Material *mat=0)
G4double CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass, const G4Material *mat)
std::vector< G4double > Probabilities (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy=0, const G4Material *mat=0)
void SetTotalCS (G4double)
Public Member Functions inherited from G4VhShellCrossSection
G4VhShellCrossSection (const G4String &xname="")
virtual ~G4VhShellCrossSection ()
G4int SelectRandomShell (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy, const G4Material *mat)
const G4String & GetName () const
Private Member Functions
G4teoCrossSection (const G4teoCrossSection &)
G4teoCrossSection & operator= (const G4teoCrossSection &right)
Private Attributes
G4double totalCS
G4VecpssrKModel * ecpssrShellK
G4VecpssrLiModel * ecpssrShellLi
G4VecpssrMiModel * ecpssrShellMi
Detailed Description
Definition at line 55 of file G4teoCrossSection.hh.
View newest version in sPHENIX GitHub at line 55 of file G4teoCrossSection.hh
Constructor & Destructor Documentation
G4teoCrossSection::G4teoCrossSection (const G4String & name)
Definition at line 49 of file G4teoCrossSection.cc.
View newest version in sPHENIX GitHub at line 49 of file G4teoCrossSection.cc
References ecpssrShellK, ecpssrShellLi, ecpssrShellMi, G4cout, and G4endl.
G4teoCrossSection::~G4teoCrossSection () virtual
Definition at line 74 of file G4teoCrossSection.cc.
View newest version in sPHENIX GitHub at line 74 of file G4teoCrossSection.cc
References ecpssrShellK, ecpssrShellLi, and ecpssrShellMi.
G4teoCrossSection::G4teoCrossSection (const G4teoCrossSection &) private
Member Function Documentation
G4double G4teoCrossSection::CrossSection (G4int Z, G4AtomicShellEnumerator shell, G4double incidentEnergy, G4double mass, const G4Material * mat) virtual
Implements G4VhShellCrossSection.
Definition at line 109 of file G4teoCrossSection.cc.
View newest version in sPHENIX GitHub at line 109 of file G4teoCrossSection.cc
References G4VecpssrKModel::CalculateCrossSection(), G4VecpssrLiModel::CalculateL1CrossSection(), G4VecpssrLiModel::CalculateL2CrossSection(), G4VecpssrLiModel::CalculateL3CrossSection(), G4VecpssrMiModel::CalculateM1CrossSection(), G4VecpssrMiModel::CalculateM2CrossSection(), G4VecpssrMiModel::CalculateM3CrossSection(), G4VecpssrMiModel::CalculateM4CrossSection(), G4VecpssrMiModel::CalculateM5CrossSection(), ecpssrShellK, ecpssrShellLi, ecpssrShellMi, fKShell, fL1Shell, fL2Shell, fL3Shell, fM1Shell, fM2Shell, fM3Shell, fM4Shell, and fM5Shell.
std::vector< G4double > G4teoCrossSection::GetCrossSection (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy = 0, const G4Material * mat = 0) virtual
Implements G4VhShellCrossSection.
Definition at line 81 of file G4teoCrossSection.cc.
View newest version in sPHENIX GitHub at line 81 of file G4teoCrossSection.cc
References G4VecpssrKModel::CalculateCrossSection(), G4VecpssrLiModel::CalculateL1CrossSection(), G4VecpssrLiModel::CalculateL2CrossSection(), G4VecpssrLiModel::CalculateL3CrossSection(), G4VecpssrMiModel::CalculateM1CrossSection(), G4VecpssrMiModel::CalculateM2CrossSection(), G4VecpssrMiModel::CalculateM3CrossSection(), G4VecpssrMiModel::CalculateM4CrossSection(), G4VecpssrMiModel::CalculateM5CrossSection(), ecpssrShellK, ecpssrShellLi, and ecpssrShellMi.
Referenced by Probabilities().
G4teoCrossSection& G4teoCrossSection::operator= (const G4teoCrossSection & right) private
std::vector< G4double > G4teoCrossSection::Probabilities (G4int Z, G4double incidentEnergy, G4double mass, G4double deltaEnergy = 0, const G4Material * mat = 0) virtual
Implements G4VhShellCrossSection.
Definition at line 170 of file G4teoCrossSection.cc.
View newest version in sPHENIX GitHub at line 170 of file G4teoCrossSection.cc
References GetCrossSection(), and totalCS.
void G4teoCrossSection::SetTotalCS (G4double val) virtual
Reimplemented from G4VhShellCrossSection.
Definition at line 189 of file G4teoCrossSection.cc.
View newest version in sPHENIX GitHub at line 189 of file G4teoCrossSection.cc
References totalCS.
Member Data Documentation
G4VecpssrKModel* G4teoCrossSection::ecpssrShellK private
Definition at line 87 of file G4teoCrossSection.hh.
View newest version in sPHENIX GitHub at line 87 of file G4teoCrossSection.hh
Referenced by CrossSection(), G4teoCrossSection(), GetCrossSection(), and ~G4teoCrossSection().
G4VecpssrLiModel* G4teoCrossSection::ecpssrShellLi private
Definition at line 88 of file G4teoCrossSection.hh.
View newest version in sPHENIX GitHub at line 88 of file G4teoCrossSection.hh
Referenced by CrossSection(), G4teoCrossSection(), GetCrossSection(), and ~G4teoCrossSection().
G4VecpssrMiModel* G4teoCrossSection::ecpssrShellMi private
Definition at line 89 of file G4teoCrossSection.hh.
View newest version in sPHENIX GitHub at line 89 of file G4teoCrossSection.hh
Referenced by CrossSection(), G4teoCrossSection(), GetCrossSection(), and ~G4teoCrossSection().
G4double G4teoCrossSection::totalCS private
Definition at line 85 of file G4teoCrossSection.hh.
View newest version in sPHENIX GitHub at line 85 of file G4teoCrossSection.hh
Referenced by Probabilities(), and SetTotalCS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4teoCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4teoCrossSection.cc