ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Para.cc File Reference
pyG4Para.cc File Reference
#include <boost/python.hpp>
#include "G4Para.hh"
Namespaces
namespace pyG4Para
Functions
G4Para * pyG4Para::CreatePara (const G4String &name, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
void export_G4Para ()
Function Documentation
void export_G4Para ()
Definition at line 55 of file pyG4Para.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4Para.cc
References pyG4Para::CreatePara(), G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetXHalfLength(), G4Para::GetYHalfLength(), G4Para::GetZHalfLength(), init(), G4Para::SetAllParameters(), G4Para::SetAlpha(), G4Para::SetTanAlpha(), G4Para::SetThetaAndPhi(), G4Para::SetXHalfLength(), G4Para::SetYHalfLength(), and G4Para::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().