ECCE @ EIC Software: G4NucleiPropertiesTheoreticalTable Class Reference
G4NucleiPropertiesTheoreticalTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4NucleiPropertiesTheoreticalTable.hh>
Public Types
enum { nEntries = 8979, shortTableSize = 137 }
Public Member Functions
~G4NucleiPropertiesTheoreticalTable ()
Private Member Functions
G4NucleiPropertiesTheoreticalTable ()
Static Private Member Functions
static G4double GetMassExcess (G4int Z, G4int A)
static G4double GetNuclearMass (G4int Z, G4int A)
static G4double GetAtomicMass (G4int Z, G4int A)
static G4double GetBindingEnergy (G4int Z, G4int A)
static G4bool IsInTable (G4int Z, G4int A)
static G4int GetIndex (G4int Z, G4int A)
static G4double ElectronicBindingEnergy (G4int Z)
Static Private Attributes
static const G4double AtomicMassExcess [nEntries]
static const G4int indexArray [2][nEntries]
static const G4int shortTable [shortTableSize]
Friends
class G4NucleiProperties
Detailed Description
Definition at line 48 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 48 of file G4NucleiPropertiesTheoreticalTable.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
nEntries
shortTableSize
Definition at line 60 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 60 of file G4NucleiPropertiesTheoreticalTable.hh
Constructor & Destructor Documentation
G4NucleiPropertiesTheoreticalTable::G4NucleiPropertiesTheoreticalTable () inline private
Definition at line 53 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 53 of file G4NucleiPropertiesTheoreticalTable.hh
G4NucleiPropertiesTheoreticalTable::~G4NucleiPropertiesTheoreticalTable () inline
Definition at line 58 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 58 of file G4NucleiPropertiesTheoreticalTable.hh
Member Function Documentation
G4double G4NucleiPropertiesTheoreticalTable::ElectronicBindingEnergy (G4int Z) static private
Definition at line 120 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 120 of file G4NucleiPropertiesTheoreticalTableA.cc
References MeV.
Referenced by GetNuclearMass().
G4double G4NucleiPropertiesTheoreticalTable::GetAtomicMass (G4int Z, G4int A) static private
Definition at line 98 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 98 of file G4NucleiPropertiesTheoreticalTableA.cc
References source.hepunit::amu_c2, AtomicMassExcess, GetIndex(), and MeV.
Referenced by G4NucleiProperties::GetAtomicMass(), and GetNuclearMass().
G4double G4NucleiPropertiesTheoreticalTable::GetBindingEnergy (G4int Z, G4int A) static private
Definition at line 84 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 84 of file G4NucleiPropertiesTheoreticalTableA.cc
References AtomicMassExcess, GetIndex(), and MeV.
Referenced by G4NucleiProperties::GetBindingEnergy().
G4int G4NucleiPropertiesTheoreticalTable::GetIndex (G4int Z, G4int A) static private
Definition at line 40 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 40 of file G4NucleiPropertiesTheoreticalTableA.cc
References EventMustBeAborted, G4Exception(), indexArray, and shortTable.
Referenced by GetAtomicMass(), GetBindingEnergy(), GetMassExcess(), GetNuclearMass(), and IsInTable().
G4double G4NucleiPropertiesTheoreticalTable::GetMassExcess (G4int Z, G4int A) static private
Definition at line 74 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 74 of file G4NucleiPropertiesTheoreticalTableA.cc
References AtomicMassExcess, GetIndex(), and MeV.
Referenced by G4NucleiProperties::GetMassExcess().
G4double G4NucleiPropertiesTheoreticalTable::GetNuclearMass (G4int Z, G4int A) static private
Definition at line 110 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 110 of file G4NucleiPropertiesTheoreticalTableA.cc
References source.hepunit::electron_mass_c2, ElectronicBindingEnergy(), GetAtomicMass(), and GetIndex().
Referenced by G4NucleiProperties::GetNuclearMass().
G4bool G4NucleiPropertiesTheoreticalTable::IsInTable (G4int Z, G4int A) static private
Definition at line 125 of file G4NucleiPropertiesTheoreticalTableA.cc.
View newest version in sPHENIX GitHub at line 125 of file G4NucleiPropertiesTheoreticalTableA.cc
References GetIndex().
Referenced by G4NucleiProperties::GetAtomicMass(), G4NucleiProperties::GetBindingEnergy(), G4NucleiProperties::GetMassExcess(), and G4NucleiProperties::GetNuclearMass().
Friends And Related Function Documentation
friend class G4NucleiProperties friend
Definition at line 64 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 64 of file G4NucleiPropertiesTheoreticalTable.hh
Member Data Documentation
const G4double G4NucleiPropertiesTheoreticalTable::AtomicMassExcess static private
Definition at line 93 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 93 of file G4NucleiPropertiesTheoreticalTable.hh
Referenced by GetAtomicMass(), GetBindingEnergy(), and GetMassExcess().
const G4int G4NucleiPropertiesTheoreticalTable::indexArray static private
Definition at line 98 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 98 of file G4NucleiPropertiesTheoreticalTable.hh
Referenced by GetIndex().
const G4int G4NucleiPropertiesTheoreticalTable::shortTable static private
Initial value:
=
{
    0,   19,   41 ,  65,   91,  119,  150,  183,  218,  255,
  294,  335,  377,  421,  466,  513,  561,  610,  660,  711,
  764,  818,  873,  928,  984, 1042, 1101, 1161, 1222, 1284,
 1347, 1411, 1476, 1542, 1609, 1677, 1746, 1816, 1887, 1958,
 2031, 2105, 2180, 2256, 2332, 2410, 2489, 2569, 2649, 2731,
 2814, 2897, 2981, 3065, 3151, 3237, 3324, 3411, 3500, 3589,
 3678, 3768, 3858, 3950, 4042, 4134, 4227, 4321, 4416, 4511,
 4606, 4702, 4799, 4896, 4993, 5092, 5191, 5290, 5389, 5490,
 5591, 5692, 5793, 5895, 5998, 6101, 6204, 6308, 6412, 6516,
 6620, 6725, 6830, 6936, 7042, 7149, 7254, 7356, 7455, 7551,
 7644, 7734, 7821, 7905, 7986, 8064, 8138, 8209, 8277, 8342,
 8404, 8463, 8519, 8572, 8622, 8668, 8711, 8751, 8788, 8822,
 8852, 8879, 8903, 8924, 8941, 8955, 8966, 8974, 8978,    0,
    0,    0,    0,    0,    0,    0, 8979
}
Definition at line 104 of file G4NucleiPropertiesTheoreticalTable.hh.
View newest version in sPHENIX GitHub at line 104 of file G4NucleiPropertiesTheoreticalTable.hh
Referenced by GetIndex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4NucleiPropertiesTheoreticalTable.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4NucleiPropertiesTheoreticalTableA.cc
geant4/tree/geant4-10.6-release/source/particles/management/src/G4NucleiPropertiesTheoreticalTableB.cc