ECCE @ EIC Software: G4InteractionContent Class Reference
G4InteractionContent Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4InteractionContent.hh>
Public Member Functions
G4InteractionContent ()
G4InteractionContent (G4VSplitableHadron *aPrimaryParticipant)
~G4InteractionContent ()
G4bool operator< (const G4InteractionContent &right) const
G4VSplitableHadron * GetProjectile () const
G4VSplitableHadron * GetTarget () const
void SetProjectileNucleon (G4Nucleon *aNucleon)
G4Nucleon * GetProjectileNucleon () const
void SetTargetNucleon (G4Nucleon *aNucleon)
G4Nucleon * GetTargetNucleon () const
void SetTarget (G4VSplitableHadron *aTarget)
G4int GetNumberOfSoftCollisions ()
G4int GetNumberOfHardCollisions ()
void SetNumberOfSoftCollisions (int)
void SetNumberOfHardCollisions (int)
G4int GetNumberOfDiffractiveCollisions ()
void SetNumberOfDiffractiveCollisions (int)
void SplitHadrons ()
void SetInteractionTime (G4double aValue)
G4double GetInteractionTime () const
void SetStatus (G4int aValue)
G4int GetStatus () const
Private Member Functions
G4InteractionContent & operator= (const G4InteractionContent &right)
G4InteractionContent (const G4InteractionContent &right)
G4bool operator== (const G4InteractionContent &right) const
G4bool operator!= (const G4InteractionContent &right) const
Private Attributes
G4VSplitableHadron * theTarget
G4VSplitableHadron * theProjectile
G4Nucleon * theProjectileNucleon
G4Nucleon * theTargetNucleon
G4int theNumberOfHard
G4int theNumberOfSoft
G4int theNumberOfDiffractive
G4double theInteractionTime
G4int curStatus
Detailed Description
Definition at line 45 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 45 of file G4InteractionContent.hh
Constructor & Destructor Documentation
G4InteractionContent::G4InteractionContent () inline
Definition at line 48 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 48 of file G4InteractionContent.hh
G4InteractionContent::G4InteractionContent (G4VSplitableHadron * aPrimaryParticipant)
Definition at line 41 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 41 of file G4InteractionContent.cc
References theProjectile, theProjectileNucleon, theTarget, and theTargetNucleon.
G4InteractionContent::~G4InteractionContent ()
Definition at line 51 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 51 of file G4InteractionContent.cc
G4InteractionContent::G4InteractionContent (const G4InteractionContent & right) private
Member Function Documentation
G4double G4InteractionContent::GetInteractionTime () const
Definition at line 63 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 63 of file G4InteractionContent.cc
References theInteractionTime.
Referenced by G4FTFPartHelperForSortInT(), G4FTFParticipants::GetList(), and operator<().
G4int G4InteractionContent::GetNumberOfDiffractiveCollisions () inline
Definition at line 164 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 164 of file G4InteractionContent.hh
References theNumberOfDiffractive.
G4int G4InteractionContent::GetNumberOfHardCollisions () inline
Definition at line 149 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 149 of file G4InteractionContent.hh
References theNumberOfHard.
G4int G4InteractionContent::GetNumberOfSoftCollisions () inline
Definition at line 144 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 144 of file G4InteractionContent.hh
References theNumberOfSoft.
Referenced by G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
G4VSplitableHadron * G4InteractionContent::GetProjectile () const inline
Definition at line 109 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 109 of file G4InteractionContent.hh
References theProjectile.
Referenced by G4FTFModel::BuildStrings(), G4QGSParticipants::CreateStrings(), G4FTFModel::ExciteParticipants(), G4FTFModel::GetStrings(), G4QGSParticipants::PerformSoftCollisions(), G4QGSParticipants::PrepareInitialState(), G4FTFModel::PutOnMassShell(), and G4FTFParticipants::ShiftInteractionTime().
G4Nucleon * G4InteractionContent::GetProjectileNucleon () const inline
Definition at line 129 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 129 of file G4InteractionContent.hh
References theProjectileNucleon.
Referenced by G4FTFModel::ExciteParticipants().
G4int G4InteractionContent::GetStatus () const
Definition at line 69 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 69 of file G4InteractionContent.cc
References curStatus.
Referenced by G4FTFModel::BuildStrings(), G4FTFModel::ExciteParticipants(), and G4QGSParticipants::GetList().
G4VSplitableHadron * G4InteractionContent::GetTarget (void) const inline
Definition at line 114 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 114 of file G4InteractionContent.hh
References theTarget.
Referenced by G4QGSParticipants::CreateStrings(), G4FTFModel::ExciteParticipants(), G4QGSParticipants::GetList(), G4QGSParticipants::PerformDiffractiveCollisions(), G4QGSParticipants::PerformSoftCollisions(), and G4FTFParticipants::ShiftInteractionTime().
G4Nucleon * G4InteractionContent::GetTargetNucleon () const inline
Definition at line 139 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 139 of file G4InteractionContent.hh
References theTargetNucleon.
Referenced by G4FTFModel::ExciteParticipants(), and G4QGSParticipants::GetList().
G4bool G4InteractionContent::operator!= (const G4InteractionContent & right) const private
G4bool G4InteractionContent::operator< (const G4InteractionContent & right) const
Definition at line 55 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 55 of file G4InteractionContent.cc
References GetInteractionTime().
G4InteractionContent& G4InteractionContent::operator= (const G4InteractionContent & right) private
G4bool G4InteractionContent::operator== (const G4InteractionContent & right) const private
void G4InteractionContent::SetInteractionTime (G4double aValue)
Definition at line 60 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 60 of file G4InteractionContent.cc
References theInteractionTime.
Referenced by G4FTFParticipants::GetList().
void G4InteractionContent::SetNumberOfDiffractiveCollisions (int nCol) inline
Definition at line 169 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 169 of file G4InteractionContent.hh
References theNumberOfDiffractive.
Referenced by G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4InteractionContent::SetNumberOfHardCollisions (int nCol) inline
Definition at line 159 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 159 of file G4InteractionContent.hh
References theNumberOfHard.
void G4InteractionContent::SetNumberOfSoftCollisions (int nCol) inline
Definition at line 154 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 154 of file G4InteractionContent.hh
References theNumberOfSoft.
Referenced by G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4InteractionContent::SetProjectileNucleon (G4Nucleon * aNucleon) inline
Definition at line 124 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 124 of file G4InteractionContent.hh
References theProjectileNucleon.
Referenced by G4FTFParticipants::GetList().
void G4InteractionContent::SetStatus (G4int aValue)
Definition at line 66 of file G4InteractionContent.cc.
View newest version in sPHENIX GitHub at line 66 of file G4InteractionContent.cc
References curStatus.
Referenced by G4FTFModel::ExciteParticipants(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4InteractionContent::SetTarget (G4VSplitableHadron * aTarget) inline
Definition at line 119 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 119 of file G4InteractionContent.hh
References theTarget.
Referenced by G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4InteractionContent::SetTargetNucleon (G4Nucleon * aNucleon) inline
Definition at line 134 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 134 of file G4InteractionContent.hh
References theTargetNucleon.
Referenced by G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4InteractionContent::SplitHadrons () inline
Definition at line 174 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 174 of file G4InteractionContent.hh
References G4VSplitableHadron::SplitUp(), theProjectile, and theTarget.
Member Data Documentation
G4int G4InteractionContent::curStatus private
Definition at line 104 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 104 of file G4InteractionContent.hh
Referenced by GetStatus(), and SetStatus().
G4double G4InteractionContent::theInteractionTime private
Definition at line 103 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 103 of file G4InteractionContent.hh
Referenced by GetInteractionTime(), and SetInteractionTime().
G4int G4InteractionContent::theNumberOfDiffractive private
Definition at line 101 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 101 of file G4InteractionContent.hh
Referenced by GetNumberOfDiffractiveCollisions(), and SetNumberOfDiffractiveCollisions().
G4int G4InteractionContent::theNumberOfHard private
Definition at line 99 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 99 of file G4InteractionContent.hh
Referenced by GetNumberOfHardCollisions(), and SetNumberOfHardCollisions().
G4int G4InteractionContent::theNumberOfSoft private
Definition at line 100 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 100 of file G4InteractionContent.hh
Referenced by GetNumberOfSoftCollisions(), and SetNumberOfSoftCollisions().
G4VSplitableHadron* G4InteractionContent::theProjectile private
Definition at line 94 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4InteractionContent.hh
Referenced by G4InteractionContent(), GetProjectile(), and SplitHadrons().
G4Nucleon* G4InteractionContent::theProjectileNucleon private
Definition at line 96 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 96 of file G4InteractionContent.hh
Referenced by G4InteractionContent(), GetProjectileNucleon(), and SetProjectileNucleon().
G4VSplitableHadron* G4InteractionContent::theTarget private
Definition at line 93 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4InteractionContent.hh
Referenced by G4InteractionContent(), GetTarget(), SetTarget(), and SplitHadrons().
G4Nucleon* G4InteractionContent::theTargetNucleon private
Definition at line 97 of file G4InteractionContent.hh.
View newest version in sPHENIX GitHub at line 97 of file G4InteractionContent.hh
Referenced by G4InteractionContent(), GetTargetNucleon(), and SetTargetNucleon().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4InteractionContent.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/src/G4InteractionContent.cc