ECCE @ EIC Software: G4VPreCompoundTransitions Class Reference
G4VPreCompoundTransitions Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4VPreCompoundTransitions.hh>
Public Member Functions
G4VPreCompoundTransitions ()
virtual ~G4VPreCompoundTransitions ()
virtual G4double CalculateProbability (const G4Fragment &aFragment)=0
virtual void PerformTransition (G4Fragment &aFragment)=0
G4double GetTransitionProb1 () const
G4double GetTransitionProb2 () const
G4double GetTransitionProb3 () const
void UseNGB (G4bool use)
void UseCEMtr (G4bool use)
Protected Attributes
G4bool useNGB
G4bool useCEMtr
G4double TransitionProb1
G4double TransitionProb2
G4double TransitionProb3
Private Member Functions
G4VPreCompoundTransitions (const G4VPreCompoundTransitions &)
const G4VPreCompoundTransitions & operator= (const G4VPreCompoundTransitions &right)
G4bool operator== (const G4VPreCompoundTransitions &right) const
G4bool operator!= (const G4VPreCompoundTransitions &right) const
Detailed Description
Definition at line 38 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 38 of file G4VPreCompoundTransitions.hh
Constructor & Destructor Documentation
G4VPreCompoundTransitions::G4VPreCompoundTransitions ()
Definition at line 34 of file G4VPreCompoundTransitions.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VPreCompoundTransitions.cc
G4VPreCompoundTransitions::~G4VPreCompoundTransitions () virtual
Definition at line 39 of file G4VPreCompoundTransitions.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VPreCompoundTransitions.cc
G4VPreCompoundTransitions::G4VPreCompoundTransitions (const G4VPreCompoundTransitions &) private
Member Function Documentation
virtual G4double G4VPreCompoundTransitions::CalculateProbability (const G4Fragment & aFragment) pure virtual
Implemented in G4PreCompoundTransitions, and G4GNASHTransitions.
Referenced by G4PreCompoundModel::DeExcite().
G4double G4VPreCompoundTransitions::GetTransitionProb1 () const inline
Definition at line 77 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VPreCompoundTransitions.hh
References TransitionProb1.
Referenced by G4PreCompoundModel::DeExcite().
G4double G4VPreCompoundTransitions::GetTransitionProb2 () const inline
Definition at line 81 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VPreCompoundTransitions.hh
References TransitionProb2.
Referenced by G4PreCompoundModel::DeExcite().
G4double G4VPreCompoundTransitions::GetTransitionProb3 () const inline
Definition at line 85 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VPreCompoundTransitions.hh
References TransitionProb3.
Referenced by G4PreCompoundModel::DeExcite().
G4bool G4VPreCompoundTransitions::operator!= (const G4VPreCompoundTransitions & right) const private
const G4VPreCompoundTransitions& G4VPreCompoundTransitions::operator= (const G4VPreCompoundTransitions & right) private
G4bool G4VPreCompoundTransitions::operator== (const G4VPreCompoundTransitions & right) const private
virtual void G4VPreCompoundTransitions::PerformTransition (G4Fragment & aFragment) pure virtual
Implemented in G4PreCompoundTransitions, and G4GNASHTransitions.
Referenced by G4PreCompoundModel::DeExcite().
void G4VPreCompoundTransitions::UseCEMtr (G4bool use) inline
Definition at line 57 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VPreCompoundTransitions.hh
References useCEMtr.
Referenced by G4PreCompoundModel::InitialiseModel().
void G4VPreCompoundTransitions::UseNGB (G4bool use) inline
Definition at line 55 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VPreCompoundTransitions.hh
References useNGB.
Referenced by G4PreCompoundModel::InitialiseModel().
Member Data Documentation
G4double G4VPreCompoundTransitions::TransitionProb1 protected
Definition at line 71 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VPreCompoundTransitions.hh
Referenced by G4PreCompoundTransitions::CalculateProbability(), GetTransitionProb1(), and G4PreCompoundTransitions::PerformTransition().
G4double G4VPreCompoundTransitions::TransitionProb2 protected
Definition at line 72 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VPreCompoundTransitions.hh
Referenced by G4PreCompoundTransitions::CalculateProbability(), GetTransitionProb2(), and G4PreCompoundTransitions::PerformTransition().
G4double G4VPreCompoundTransitions::TransitionProb3 protected
Definition at line 73 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VPreCompoundTransitions.hh
Referenced by G4PreCompoundTransitions::CalculateProbability(), GetTransitionProb3(), and G4PreCompoundTransitions::PerformTransition().
G4bool G4VPreCompoundTransitions::useCEMtr protected
Definition at line 69 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VPreCompoundTransitions.hh
Referenced by G4PreCompoundTransitions::CalculateProbability(), and UseCEMtr().
G4bool G4VPreCompoundTransitions::useNGB protected
Definition at line 68 of file G4VPreCompoundTransitions.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPreCompoundTransitions.hh
Referenced by G4PreCompoundTransitions::CalculateProbability(), and UseNGB().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4VPreCompoundTransitions.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4VPreCompoundTransitions.cc