ECCE @ EIC Software: G4RTWorkerInitialization Class Reference
G4RTWorkerInitialization Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTWorkerInitialization.hh>
Public Member Functions
G4RTWorkerInitialization ()
virtual ~G4RTWorkerInitialization ()
virtual void WorkerRunStart () const
virtual void WorkerRunEnd () const
Public Member Functions inherited from G4UserWorkerInitialization
G4UserWorkerInitialization ()
virtual ~G4UserWorkerInitialization ()
virtual void WorkerInitialize () const
virtual void WorkerStart () const
virtual void WorkerStop () const
Static Private Attributes
static G4ThreadLocal const
G4UserRunAction * theUserRunAction = 0
static G4ThreadLocal const
G4VUserPrimaryGeneratorAction * theUserPrimaryGeneratorAction = 0
static G4ThreadLocal const
G4UserEventAction * theUserEventAction = 0
static G4ThreadLocal const
G4UserStackingAction * theUserStackingAction = 0
static G4ThreadLocal const
G4UserTrackingAction * theUserTrackingAction = 0
static G4ThreadLocal const
G4UserSteppingAction * theUserSteppingAction = 0
static G4ThreadLocal
G4RTRunAction * theRTRunAction = 0
static G4ThreadLocal
G4RTPrimaryGeneratorAction * theRTPrimaryGeneratorAction = 0
static G4ThreadLocal
G4RTTrackingAction * theRTTrackingAction = 0
static G4ThreadLocal
G4RTSteppingAction * theRTSteppingAction = 0
Detailed Description
Definition at line 44 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 44 of file G4RTWorkerInitialization.hh
Constructor & Destructor Documentation
G4RTWorkerInitialization::G4RTWorkerInitialization ()
Definition at line 56 of file G4RTWorkerInitialization.cc.
View newest version in sPHENIX GitHub at line 56 of file G4RTWorkerInitialization.cc
G4RTWorkerInitialization::~G4RTWorkerInitialization () virtual
Definition at line 59 of file G4RTWorkerInitialization.cc.
View newest version in sPHENIX GitHub at line 59 of file G4RTWorkerInitialization.cc
Member Function Documentation
void G4RTWorkerInitialization::WorkerRunEnd () const virtual
Reimplemented from G4UserWorkerInitialization.
Definition at line 88 of file G4RTWorkerInitialization.cc.
View newest version in sPHENIX GitHub at line 88 of file G4RTWorkerInitialization.cc
References G4WorkerRunManager::GetWorkerRunManager(), G4WorkerRunManager::SetUserAction(), theUserEventAction, theUserPrimaryGeneratorAction, theUserRunAction, theUserStackingAction, theUserSteppingAction, and theUserTrackingAction.
void G4RTWorkerInitialization::WorkerRunStart () const virtual
Reimplemented from G4UserWorkerInitialization.
Definition at line 62 of file G4RTWorkerInitialization.cc.
View newest version in sPHENIX GitHub at line 62 of file G4RTWorkerInitialization.cc
References G4RunManager::GetUserEventAction(), G4RunManager::GetUserPrimaryGeneratorAction(), G4RunManager::GetUserRunAction(), G4RunManager::GetUserStackingAction(), G4RunManager::GetUserSteppingAction(), G4RunManager::GetUserTrackingAction(), G4WorkerRunManager::GetWorkerRunManager(), G4RTPrimaryGeneratorAction::SetUp(), G4WorkerRunManager::SetUserAction(), theRTPrimaryGeneratorAction, theRTRunAction, theRTSteppingAction, theRTTrackingAction, theUserEventAction, theUserPrimaryGeneratorAction, theUserRunAction, theUserStackingAction, theUserSteppingAction, and theUserTrackingAction.
Member Data Documentation
G4ThreadLocal G4RTPrimaryGeneratorAction * G4RTWorkerInitialization::theRTPrimaryGeneratorAction = 0 static private
Definition at line 69 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunStart().
G4ThreadLocal G4RTRunAction * G4RTWorkerInitialization::theRTRunAction = 0 static private
Definition at line 68 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunStart().
G4ThreadLocal G4RTSteppingAction * G4RTWorkerInitialization::theRTSteppingAction = 0 static private
Definition at line 71 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunStart().
G4ThreadLocal G4RTTrackingAction * G4RTWorkerInitialization::theRTTrackingAction = 0 static private
Definition at line 70 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunStart().
G4ThreadLocal const G4UserEventAction * G4RTWorkerInitialization::theUserEventAction = 0 static private
Definition at line 63 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunEnd(), and WorkerRunStart().
G4ThreadLocal const G4VUserPrimaryGeneratorAction * G4RTWorkerInitialization::theUserPrimaryGeneratorAction = 0 static private
Definition at line 62 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunEnd(), and WorkerRunStart().
G4ThreadLocal const G4UserRunAction * G4RTWorkerInitialization::theUserRunAction = 0 static private
Definition at line 61 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunEnd(), and WorkerRunStart().
G4ThreadLocal const G4UserStackingAction * G4RTWorkerInitialization::theUserStackingAction = 0 static private
Definition at line 64 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunEnd(), and WorkerRunStart().
G4ThreadLocal const G4UserSteppingAction * G4RTWorkerInitialization::theUserSteppingAction = 0 static private
Definition at line 66 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunEnd(), and WorkerRunStart().
G4ThreadLocal const G4UserTrackingAction * G4RTWorkerInitialization::theUserTrackingAction = 0 static private
Definition at line 65 of file G4RTWorkerInitialization.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RTWorkerInitialization.hh
Referenced by WorkerRunEnd(), and WorkerRunStart().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTWorkerInitialization.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RTWorkerInitialization.cc