ECCE @ EIC Software: G4ParticleHPContEnergyAngular Class Reference
G4ParticleHPContEnergyAngular Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPContEnergyAngular.hh>
Public Member Functions
G4ParticleHPContEnergyAngular (G4ParticleDefinition *proj)
~G4ParticleHPContEnergyAngular ()
void Init (std::istream &aDataFile)
G4double MeanEnergyOfThisInteraction ()
G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass)
void ClearHistories ()
Public Member Functions inherited from G4VParticleHPEnergyAngular
G4VParticleHPEnergyAngular ()
virtual ~G4VParticleHPEnergyAngular ()
void SetProjectileRP (G4ReactionProduct *aIncidentParticleRP)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4ReactionProduct * GetCMS ()
void SetQValue (G4double aValue)
Private Attributes
G4double theTargetCode
G4int theAngularRep
G4int nEnergy
G4int theInterpolation
G4InterpolationManager theManager
G4ParticleHPContAngularPar * theAngular
G4Cache< G4double > currentMeanEnergy
G4Cache
< G4ParticleHPContAngularPar * > fCacheAngular
G4ParticleDefinition * theProjectile
Additional Inherited Members
Protected Member Functions inherited from G4VParticleHPEnergyAngular
G4double GetQValue ()
Detailed Description
Definition at line 48 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPContEnergyAngular.hh
Constructor & Destructor Documentation
G4ParticleHPContEnergyAngular::G4ParticleHPContEnergyAngular (G4ParticleDefinition * proj) inline
Definition at line 52 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPContEnergyAngular.hh
References currentMeanEnergy, fCacheAngular, nEnergy, G4Cache< VALTYPE >::Put(), theAngular, theAngularRep, theInterpolation, and theTargetCode.
G4ParticleHPContEnergyAngular::~G4ParticleHPContEnergyAngular () inline
Definition at line 64 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPContEnergyAngular.hh
References fCacheAngular, G4Cache< VALTYPE >::Get(), and theAngular.
Member Function Documentation
void G4ParticleHPContEnergyAngular::ClearHistories () virtual
Reimplemented from G4VParticleHPEnergyAngular.
Definition at line 126 of file G4ParticleHPContEnergyAngular.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPContEnergyAngular.cc
References nEnergy, and theAngular.
void G4ParticleHPContEnergyAngular::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 70 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPContEnergyAngular.hh
References G4InterpolationManager::Init(), G4ParticleHPContAngularPar::Init(), nEnergy, G4ParticleHPContAngularPar::PrepareTableInterpolation(), G4ParticleHPContAngularPar::SetInterpolation(), theAngular, theAngularRep, theInterpolation, theManager, theProjectile, and theTargetCode.
G4double G4ParticleHPContEnergyAngular::MeanEnergyOfThisInteraction () virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 109 of file G4ParticleHPContEnergyAngular.cc.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPContEnergyAngular.cc
References currentMeanEnergy, G4Cache< VALTYPE >::Get(), and G4Cache< VALTYPE >::Put().
Referenced by Sample().
G4ReactionProduct * G4ParticleHPContEnergyAngular::Sample (G4double anEnergy, G4double massCode, G4double mass) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 36 of file G4ParticleHPContEnergyAngular.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPContEnergyAngular.cc
References G4ParticleHPContAngularPar::BuildByInterpolation(), G4ParticleHPContAngularPar::ClearHistories(), currentMeanEnergy, fCacheAngular, G4cout, G4endl, G4Cache< VALTYPE >::Get(), G4ParticleHPContAngularPar::GetEnergy(), G4ReactionProduct::GetMass(), G4ParticleHPContAngularPar::GetNEnergies(), G4VParticleHPEnergyAngular::GetProjectileRP(), G4InterpolationManager::GetScheme(), G4VParticleHPEnergyAngular::GetTarget(), it, MeanEnergyOfThisInteraction(), G4ParticleHPContAngularPar::MeanEnergyOfThisInteraction(), nEnergy, G4Cache< VALTYPE >::Put(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPContAngularPar::SetInterpolation(), G4ParticleHPContAngularPar::SetPrimary(), G4ParticleHPContAngularPar::SetTarget(), G4ParticleHPContAngularPar::SetTargetCode(), theAngular, theAngularRep, theInterpolation, theManager, theProjectile, and theTargetCode.
Member Data Documentation
G4Cache<G4double> G4ParticleHPContEnergyAngular::currentMeanEnergy private
Definition at line 104 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleHPContEnergyAngular.hh
Referenced by G4ParticleHPContEnergyAngular(), MeanEnergyOfThisInteraction(), and Sample().
G4Cache<G4ParticleHPContAngularPar*> G4ParticleHPContEnergyAngular::fCacheAngular private
Definition at line 105 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPContEnergyAngular.hh
Referenced by G4ParticleHPContEnergyAngular(), Sample(), and ~G4ParticleHPContEnergyAngular().
G4int G4ParticleHPContEnergyAngular::nEnergy private
Definition at line 97 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPContEnergyAngular.hh
Referenced by ClearHistories(), G4ParticleHPContEnergyAngular(), Init(), and Sample().
G4ParticleHPContAngularPar* G4ParticleHPContEnergyAngular::theAngular private
Definition at line 102 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPContEnergyAngular.hh
Referenced by ClearHistories(), G4ParticleHPContEnergyAngular(), Init(), Sample(), and ~G4ParticleHPContEnergyAngular().
G4int G4ParticleHPContEnergyAngular::theAngularRep private
Definition at line 96 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPContEnergyAngular.hh
Referenced by G4ParticleHPContEnergyAngular(), Init(), and Sample().
G4int G4ParticleHPContEnergyAngular::theInterpolation private
Definition at line 99 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPContEnergyAngular.hh
Referenced by G4ParticleHPContEnergyAngular(), Init(), and Sample().
G4InterpolationManager G4ParticleHPContEnergyAngular::theManager private
Definition at line 101 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPContEnergyAngular.hh
Referenced by Init(), and Sample().
G4ParticleDefinition* G4ParticleHPContEnergyAngular::theProjectile private
Definition at line 106 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPContEnergyAngular.hh
Referenced by Init(), and Sample().
G4double G4ParticleHPContEnergyAngular::theTargetCode private
Definition at line 95 of file G4ParticleHPContEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPContEnergyAngular.hh
Referenced by G4ParticleHPContEnergyAngular(), Init(), and Sample().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPContEnergyAngular.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPContEnergyAngular.cc