ECCE @ EIC Software: ExGflash3DetectorConstruction Class Reference
ExGflash3DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/include/ExGflash3DetectorConstruction.hh>
Public Member Functions
ExGflash3DetectorConstruction ()
~ExGflash3DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4Region * fRegion
Static Private Attributes
static G4ThreadLocal
GFlashShowerModel * fFastShowerModel = 0
static G4ThreadLocal
GFlashHomoShowerParameterisation * fParameterisation = 0
static G4ThreadLocal
GFlashParticleBounds * fParticleBounds = 0
static G4ThreadLocal
GFlashHitMaker * fHitMaker = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 45 of file ExGflash3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 45 of file ExGflash3DetectorConstruction.hh
Constructor & Destructor Documentation
ExGflash3DetectorConstruction::ExGflash3DetectorConstruction ()
Definition at line 70 of file ExGflash3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 70 of file ExGflash3DetectorConstruction.cc
References G4cout, and G4endl.
ExGflash3DetectorConstruction::~ExGflash3DetectorConstruction ()
Definition at line 78 of file ExGflash3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 78 of file ExGflash3DetectorConstruction.cc
References fFastShowerModel, fHitMaker, fParameterisation, and fParticleBounds.
Member Function Documentation
G4VPhysicalVolume * ExGflash3DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 88 of file ExGflash3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 88 of file ExGflash3DetectorConstruction.cc
References G4Region::AddRootLogicalVolume(), cm, G4NistManager::FindOrBuildMaterial(), fRegion, G4cout, G4endl, G4VisAttributes::GetInvisible(), G4NistManager::Instance(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and BTOF::zpos.
void ExGflash3DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 190 of file ExGflash3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 190 of file ExGflash3DetectorConstruction.cc
References fFastShowerModel, fHitMaker, fParameterisation, fParticleBounds, fRegion, G4cout, G4endl, G4Region::GetMaterialIterator(), GFlashShowerModel::SetHitMaker(), GFlashHitMaker::SetNameOfWorldWithSD(), GFlashShowerModel::SetParameterisation(), and GFlashShowerModel::SetParticleBounds().
Member Data Documentation
G4ThreadLocal GFlashShowerModel * ExGflash3DetectorConstruction::fFastShowerModel = 0 static private
Definition at line 58 of file ExGflash3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 58 of file ExGflash3DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash3DetectorConstruction().
G4ThreadLocal GFlashHitMaker * ExGflash3DetectorConstruction::fHitMaker = 0 static private
Definition at line 61 of file ExGflash3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 61 of file ExGflash3DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash3DetectorConstruction().
G4ThreadLocal GFlashHomoShowerParameterisation * ExGflash3DetectorConstruction::fParameterisation = 0 static private
Definition at line 59 of file ExGflash3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 59 of file ExGflash3DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash3DetectorConstruction().
G4ThreadLocal GFlashParticleBounds * ExGflash3DetectorConstruction::fParticleBounds = 0 static private
Definition at line 60 of file ExGflash3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file ExGflash3DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflash3DetectorConstruction().
G4Region* ExGflash3DetectorConstruction::fRegion private
Definition at line 56 of file ExGflash3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 56 of file ExGflash3DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/include/ExGflash3DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/src/ExGflash3DetectorConstruction.cc