ECCE @ EIC Software: G4KokoulinMuonNuclearXS Class Reference
G4KokoulinMuonNuclearXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4KokoulinMuonNuclearXS.hh>
Public Member Functions
G4KokoulinMuonNuclearXS ()
virtual ~G4KokoulinMuonNuclearXS ()
virtual void CrossSectionDescription (std::ostream &) const
G4bool IsElementApplicable (const G4DynamicParticle *particle, G4int Z, const G4Material *)
G4double GetElementCrossSection (const G4DynamicParticle *particle, G4int Z, const G4Material *)
void BuildPhysicsTable (const G4ParticleDefinition &)
void BuildCrossSectionTable ()
G4double ComputeDDMicroscopicCrossSection (G4double incidentKE, G4double Z, G4double A, G4double epsilon)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
G4double ComputeMicroscopicCrossSection (G4double incidentKE, G4double A)
G4KokoulinMuonNuclearXS & operator= (const G4KokoulinMuonNuclearXS &right)
G4KokoulinMuonNuclearXS (const G4KokoulinMuonNuclearXS &)
Private Attributes
G4double LowestKineticEnergy
G4double HighestKineticEnergy
G4int TotBin
G4double CutFixed
G4bool isInitialized
G4bool isMaster
Static Private Attributes
static G4PhysicsVector * theCrossSection [MAXZMUN] = {0}
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 52 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 52 of file G4KokoulinMuonNuclearXS.hh
Constructor & Destructor Documentation
G4KokoulinMuonNuclearXS::G4KokoulinMuonNuclearXS ()
Definition at line 58 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 58 of file G4KokoulinMuonNuclearXS.cc
G4KokoulinMuonNuclearXS::~G4KokoulinMuonNuclearXS () virtual
Definition at line 64 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 64 of file G4KokoulinMuonNuclearXS.cc
References isMaster, MAXZMUN, and theCrossSection.
G4KokoulinMuonNuclearXS::G4KokoulinMuonNuclearXS (const G4KokoulinMuonNuclearXS &) private
Member Function Documentation
void G4KokoulinMuonNuclearXS::BuildCrossSectionTable ()
Definition at line 107 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 107 of file G4KokoulinMuonNuclearXS.cc
References A(), ComputeMicroscopicCrossSection(), energy, G4PhysicsVector::Energy(), G4lrint(), G4NistManager::GetAtomicMassAmu(), G4Element::GetElementTable(), G4Element::GetNumberOfElements(), HighestKineticEnergy, G4NistManager::Instance(), LowestKineticEnergy, MAXZMUN, G4PhysicsVector::PutValue(), theCrossSection, TotBin, and Z.
Referenced by BuildPhysicsTable().
void G4KokoulinMuonNuclearXS::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 95 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 95 of file G4KokoulinMuonNuclearXS.cc
References BuildCrossSectionTable(), isInitialized, isMaster, MAXZMUN, and theCrossSection.
G4double G4KokoulinMuonNuclearXS::ComputeDDMicroscopicCrossSection (G4double incidentKE, G4double Z, G4double A, G4double epsilon)
Definition at line 182 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 182 of file G4KokoulinMuonNuclearXS.cc
References CutFixed, source.hepunit::fine_structure_const, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGMass(), GeV, microbarn, G4MuonMinus::MuonMinus(), pi, source.hepunit::proton_mass_c2, v, v1, and v2.
Referenced by ComputeMicroscopicCrossSection(), and G4MuonVDNuclearModel::MakeSamplingTable().
G4double G4KokoulinMuonNuclearXS::ComputeMicroscopicCrossSection (G4double incidentKE, G4double A) private
Definition at line 137 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 137 of file G4KokoulinMuonNuclearXS.cc
References ak1, ak2, ComputeDDMicroscopicCrossSection(), CutFixed, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGMass(), hhh, max, G4MuonMinus::MuonMinus(), source.hepunit::proton_mass_c2, and x.
Referenced by BuildCrossSectionTable().
void G4KokoulinMuonNuclearXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 76 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 76 of file G4KokoulinMuonNuclearXS.cc
static const char* G4KokoulinMuonNuclearXS::Default_Name () inline static
Definition at line 59 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4KokoulinMuonNuclearXS.hh
Referenced by G4MuonVDNuclearModel::G4MuonVDNuclearModel().
G4double G4KokoulinMuonNuclearXS::GetElementCrossSection (const G4DynamicParticle * particle, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 221 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 221 of file G4KokoulinMuonNuclearXS.cc
References G4DynamicParticle::GetKineticEnergy(), theCrossSection, G4PhysicsVector::Value(), and Z.
G4bool G4KokoulinMuonNuclearXS::IsElementApplicable (const G4DynamicParticle * particle, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 88 of file G4KokoulinMuonNuclearXS.cc.
View newest version in sPHENIX GitHub at line 88 of file G4KokoulinMuonNuclearXS.cc
G4KokoulinMuonNuclearXS& G4KokoulinMuonNuclearXS::operator= (const G4KokoulinMuonNuclearXS & right) private
Member Data Documentation
G4double G4KokoulinMuonNuclearXS::CutFixed private
Definition at line 90 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4KokoulinMuonNuclearXS.hh
Referenced by ComputeDDMicroscopicCrossSection(), and ComputeMicroscopicCrossSection().
G4double G4KokoulinMuonNuclearXS::HighestKineticEnergy private
Definition at line 88 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4KokoulinMuonNuclearXS.hh
Referenced by BuildCrossSectionTable().
G4bool G4KokoulinMuonNuclearXS::isInitialized private
Definition at line 91 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4KokoulinMuonNuclearXS.hh
Referenced by BuildPhysicsTable().
G4bool G4KokoulinMuonNuclearXS::isMaster private
Definition at line 92 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4KokoulinMuonNuclearXS.hh
Referenced by BuildPhysicsTable(), and ~G4KokoulinMuonNuclearXS().
G4double G4KokoulinMuonNuclearXS::LowestKineticEnergy private
Definition at line 87 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4KokoulinMuonNuclearXS.hh
Referenced by BuildCrossSectionTable().
G4PhysicsVector * G4KokoulinMuonNuclearXS::theCrossSection = {0} static private
Definition at line 85 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4KokoulinMuonNuclearXS.hh
Referenced by BuildCrossSectionTable(), BuildPhysicsTable(), GetElementCrossSection(), and ~G4KokoulinMuonNuclearXS().
G4int G4KokoulinMuonNuclearXS::TotBin private
Definition at line 89 of file G4KokoulinMuonNuclearXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4KokoulinMuonNuclearXS.hh
Referenced by BuildCrossSectionTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4KokoulinMuonNuclearXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4KokoulinMuonNuclearXS.cc