ECCE @ EIC Software: G4INCL::NNToMultiPionsChannel Class Reference
G4INCL::NNToMultiPionsChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNNToMultiPionsChannel.hh>
Public Member Functions
NNToMultiPionsChannel (const G4int, Particle *, Particle *)
virtual ~NNToMultiPionsChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
void inter2Part (const G4double p)
void pn_ppPim ()
void pn_pnPi0 ()
void pn_nnPip ()
void pp_nnPipPip ()
void nn_ppPimPim ()
void pn_pnPipPim ()
void pn_pnPi0Pi0 ()
void pp_ppPipPim ()
void nn_nnPipPim ()
void pp_ppPi0Pi0 ()
void nn_nnPi0Pi0 ()
void pp_pnPipPi0 ()
void pn_ppPimPi0 ()
void pn_nnPipPi0 ()
void nn_pnPimPi0 ()
void pp_pnPipPi0Pi0 ()
void nn_pnPimPi0Pi0 ()
void pn_nnPipPi0Pi0 ()
void pp_ppPipPimPi0 ()
void nn_nnPipPimPi0 ()
void pp_ppPi0Pi0Pi0 ()
void nn_nnPi0Pi0Pi0 ()
void pp_pnPipPipPim ()
void pp_nnPipPipPi0 ()
void pn_ppPimPi0Pi0 ()
void pn_ppPimPimPip ()
void pn_pnPi0PipPim ()
void pn_pnPi0Pi0Pi0 ()
void pn_nnPipPipPim ()
void nn_pnPipPimPim ()
void nn_ppPimPimPi0 ()
void pp_nnPipPipPi0Pi0 ()
void pp_nnPipPipPipPim ()
void nn_ppPi0Pi0PimPim ()
void nn_ppPipPimPimPim ()
void pp_ppPi0Pi0Pi0Pi0 ()
void nn_nnPi0Pi0Pi0Pi0 ()
void pn_pnPi0Pi0Pi0Pi0 ()
void pp_ppPipPi0Pi0Pim ()
void nn_nnPipPi0Pi0Pim ()
void pn_pnPipPi0Pi0Pim ()
void pp_ppPipPipPimPim ()
void nn_nnPipPipPimPim ()
void pn_pnPipPipPimPim ()
void pp_pnPipPi0Pi0Pi0 ()
void pn_nnPipPi0Pi0Pi0 ()
void pp_nnPipPi0Pi0Pi0 ()
void pp_pnPipPipPi0Pim ()
void pn_nnPipPipPi0Pim ()
void pp_nnPipPipPi0Pim ()
void nn_pnPi0Pi0Pi0Pim ()
void pn_ppPi0Pi0Pi0Pim ()
void nn_pnPipPi0PimPim ()
void pn_ppPipPi0PimPim ()
void isospinRepartition ()
Private Attributes
G4int npion
G4int iso1
G4int iso2
G4int isosp [4]
Particle * particle1
Particle * particle2
Static Private Attributes
static const G4double angularSlope = 6.
Detailed Description
Definition at line 47 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNNToMultiPionsChannel.hh
Constructor & Destructor Documentation
G4INCL::NNToMultiPionsChannel::NNToMultiPionsChannel (const G4int npi, Particle * p1, Particle * p2)
Definition at line 51 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
G4INCL::NNToMultiPionsChannel::~NNToMultiPionsChannel () virtual
Definition at line 61 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLNNToMultiPionsChannel.cc
Member Function Documentation
void G4INCL::NNToMultiPionsChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 65 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLNNToMultiPionsChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), angularSlope, G4INCL::PhaseSpaceGenerator::generateBiased(), G4INCL::ParticleTable::getIsospin(), G4INCL::ParticleTable::getNucleonType(), G4INCL::ParticleTable::getPionType(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), iso1, iso2, isosp, isospinRepartition(), npion, particle1, particle2, G4InuclParticleNames::pion(), G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::KinematicsUtils::totalEnergyInCM(), and zero.
void G4INCL::NNToMultiPionsChannel::inter2Part (const G4double p) private
Definition at line 557 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 557 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, G4INCL::Random::shoot(), and boost::swap().
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::isospinRepartition () private
Definition at line 100 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 100 of file G4INCLNNToMultiPionsChannel.cc
References G4INCL::Random::getAdapter(), inter2Part(), iso1, iso2, isosp, nn_nnPi0Pi0(), nn_nnPi0Pi0Pi0(), nn_nnPi0Pi0Pi0Pi0(), nn_nnPipPi0Pi0Pim(), nn_nnPipPim(), nn_nnPipPimPi0(), nn_nnPipPipPimPim(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), npion, pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_pnPi0(), pn_pnPi0Pi0(), pn_pnPi0Pi0Pi0(), pn_pnPi0Pi0Pi0Pi0(), pn_pnPi0PipPim(), pn_pnPipPi0Pi0Pim(), pn_pnPipPim(), pn_pnPipPipPimPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), G4InuclParticleNames::pp, pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), pp_pnPipPipPim(), pp_ppPi0Pi0(), pp_ppPi0Pi0Pi0(), pp_ppPi0Pi0Pi0Pi0(), pp_ppPipPi0Pi0Pim(), pp_ppPipPim(), pp_ppPipPimPi0(), pp_ppPipPipPimPim(), and G4INCL::Random::shoot().
Referenced by fillFinalState().
void G4INCL::NNToMultiPionsChannel::nn_nnPi0Pi0 () private
Definition at line 262 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 262 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_nnPi0Pi0Pi0 () private
Definition at line 326 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 326 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_nnPi0Pi0Pi0Pi0 () private
Definition at line 428 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 428 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_nnPipPi0Pi0Pim () private
Definition at line 446 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 446 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_nnPipPim () private
Definition at line 254 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 254 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_nnPipPimPi0 () private
Definition at line 316 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 316 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_nnPipPipPimPim () private
Definition at line 464 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 464 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_pnPi0Pi0Pi0Pim () private
Definition at line 524 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 524 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_pnPimPi0 () private
Definition at line 284 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 284 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_pnPimPi0Pi0 () private
Definition at line 297 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 297 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_pnPipPi0PimPim () private
Definition at line 540 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 540 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_pnPipPimPim () private
Definition at line 376 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 376 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_ppPi0Pi0PimPim () private
Definition at line 406 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 406 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_ppPimPim () private
Definition at line 236 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 236 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_ppPimPimPi0 () private
Definition at line 383 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 383 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::nn_ppPipPimPimPim () private
Definition at line 414 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 414 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_nnPip () private
Definition at line 225 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 225 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_nnPipPi0 () private
Definition at line 278 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 278 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_nnPipPi0Pi0 () private
Definition at line 304 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 304 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_nnPipPi0Pi0Pi0 () private
Definition at line 484 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 484 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_nnPipPipPi0Pim () private
Definition at line 508 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 508 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_nnPipPipPim () private
Definition at line 369 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 369 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPi0 () private
Definition at line 222 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 222 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPi0Pi0 () private
Definition at line 246 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 246 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPi0Pi0Pi0 () private
Definition at line 364 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 364 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPi0Pi0Pi0Pi0 () private
Definition at line 434 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 434 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPi0PipPim () private
Definition at line 359 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 359 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPipPi0Pi0Pim () private
Definition at line 452 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 452 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPipPim () private
Definition at line 242 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 242 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_pnPipPipPimPim () private
Definition at line 470 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 470 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_ppPi0Pi0Pi0Pim () private
Definition at line 532 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 532 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_ppPim () private
Definition at line 217 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 217 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_ppPimPi0 () private
Definition at line 272 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 272 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_ppPimPi0Pi0 () private
Definition at line 345 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 345 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_ppPimPimPip () private
Definition at line 352 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 352 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pn_ppPipPi0PimPim () private
Definition at line 548 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 548 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_nnPipPi0Pi0Pi0 () private
Definition at line 492 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 492 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
void G4INCL::NNToMultiPionsChannel::pp_nnPipPip () private
Definition at line 230 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 230 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_nnPipPipPi0 () private
Definition at line 338 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 338 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_nnPipPipPi0Pi0 () private
Definition at line 390 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 390 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_nnPipPipPi0Pim () private
Definition at line 516 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 516 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
void G4INCL::NNToMultiPionsChannel::pp_nnPipPipPipPim () private
Definition at line 398 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 398 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_pnPipPi0 () private
Definition at line 266 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 266 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_pnPipPi0Pi0 () private
Definition at line 290 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 290 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_pnPipPi0Pi0Pi0 () private
Definition at line 476 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 476 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_pnPipPipPi0Pim () private
Definition at line 500 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 500 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_pnPipPipPim () private
Definition at line 331 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 331 of file G4INCLNNToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPi0Pi0 () private
Definition at line 258 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 258 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPi0Pi0Pi0 () private
Definition at line 321 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 321 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPi0Pi0Pi0Pi0 () private
Definition at line 422 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 422 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPipPi0Pi0Pim () private
Definition at line 440 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 440 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPipPim () private
Definition at line 250 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 250 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPipPimPi0 () private
Definition at line 311 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 311 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNToMultiPionsChannel::pp_ppPipPipPimPim () private
Definition at line 458 of file G4INCLNNToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 458 of file G4INCLNNToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
Member Data Documentation
const G4double G4INCL::NNToMultiPionsChannel::angularSlope = 6. static private
Definition at line 61 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState().
G4int G4INCL::NNToMultiPionsChannel::iso1 private
Definition at line 56 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState(), inter2Part(), isospinRepartition(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), pp_nnPipPi0Pi0Pi0(), pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPi0Pim(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), and pp_pnPipPipPim().
G4int G4INCL::NNToMultiPionsChannel::iso2 private
Definition at line 57 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState(), inter2Part(), isospinRepartition(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), pp_nnPipPi0Pi0Pi0(), pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPi0Pim(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), and pp_pnPipPipPim().
G4int G4INCL::NNToMultiPionsChannel::isosp[4] private
Definition at line 58 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState(), isospinRepartition(), nn_nnPi0Pi0(), nn_nnPi0Pi0Pi0(), nn_nnPi0Pi0Pi0Pi0(), nn_nnPipPi0Pi0Pim(), nn_nnPipPim(), nn_nnPipPimPi0(), nn_nnPipPipPimPim(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), NNToMultiPionsChannel(), pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_pnPi0(), pn_pnPi0Pi0(), pn_pnPi0Pi0Pi0(), pn_pnPi0Pi0Pi0Pi0(), pn_pnPi0PipPim(), pn_pnPipPi0Pi0Pim(), pn_pnPipPim(), pn_pnPipPipPimPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), pp_nnPipPi0Pi0Pi0(), pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPi0Pim(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), pp_pnPipPipPim(), pp_ppPi0Pi0(), pp_ppPi0Pi0Pi0(), pp_ppPi0Pi0Pi0Pi0(), pp_ppPipPi0Pi0Pim(), pp_ppPipPim(), pp_ppPipPimPi0(), and pp_ppPipPipPimPim().
G4int G4INCL::NNToMultiPionsChannel::npion private
Definition at line 55 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState(), and isospinRepartition().
Particle* G4INCL::NNToMultiPionsChannel::particle1 private
Definition at line 59 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NNToMultiPionsChannel::particle2 private
Definition at line 59 of file G4INCLNNToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLNNToMultiPionsChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNNToMultiPionsChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNNToMultiPionsChannel.cc