ECCE @ EIC Software: CML2Convergence Class Reference
CML2Convergence Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Convergence.hh>
Public Member Functions
CML2Convergence ()
CML2Convergence (G4int seed, G4int saving_in_Selected_Voxels_every_events, G4String FileExperimentalData, G4String FileExperimentalDataOut, G4bool bCompareExp, G4int maxNumberOfEvents, G4int nRecycling, G4int nMaxLoops)
~CML2Convergence (void)
void add (const G4Step *aStep)
G4bool stopRun ()
void setMaxNumberOfEvents (G4int val)
G4double getMaxNumberOfEvents ()
CML2ExpVoxels * getExpVoxels ()
void saveResults ()
void setNewGeometry ()
int getNMaxLoops ()
Private Member Functions
G4bool convergenceCriteria ()
Private Attributes
std::vector< Svoxel > voxels
CML2ExpVoxels * ML2ExpVoxels
G4String fileExperimentalData
G4bool bCompareExp
G4int maxNumberOfEvents
G4int nGeometry
G4int nAccumulatedEvents
int nMaxLoops
int idCurrentLoop
Detailed Description
Definition at line 52 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 52 of file ML2Convergence.hh
Constructor & Destructor Documentation
CML2Convergence::CML2Convergence (void)
Definition at line 46 of file ML2Convergence.cc.
View newest version in sPHENIX GitHub at line 46 of file ML2Convergence.cc
CML2Convergence::CML2Convergence (G4int seed, G4int saving_in_Selected_Voxels_every_events, G4String FileExperimentalData, G4String FileExperimentalDataOut, G4bool bCompareExp, G4int maxNumberOfEvents, G4int nRecycling, G4int nMaxLoops)
Definition at line 49 of file ML2Convergence.cc.
View newest version in sPHENIX GitHub at line 49 of file ML2Convergence.cc
References bCompareExp, fileExperimentalData, G4cout, G4endl, idCurrentLoop, CML2ExpVoxels::loadData(), maxNumberOfEvents, ML2ExpVoxels, nAccumulatedEvents, nGeometry, nMaxLoops, and CML2ExpVoxels::setRecycling().
CML2Convergence::~CML2Convergence (void)
Definition at line 80 of file ML2Convergence.cc.
View newest version in sPHENIX GitHub at line 80 of file ML2Convergence.cc
References ML2ExpVoxels.
Member Function Documentation
void CML2Convergence::add (const G4Step * aStep)
Definition at line 86 of file ML2Convergence.cc.
View newest version in sPHENIX GitHub at line 86 of file ML2Convergence.cc
References CML2ExpVoxels::add(), G4Step::GetTotalEnergyDeposit(), and ML2ExpVoxels.
Referenced by CML2SteppingAction::UserSteppingAction().
G4bool CML2Convergence::convergenceCriteria () private
Definition at line 113 of file ML2Convergence.cc.
View newest version in sPHENIX GitHub at line 113 of file ML2Convergence.cc
References bCompareExp, G4cout, G4endl, CML2ExpVoxels::getMaxNumberOfEvents(), maxNumberOfEvents, ML2ExpVoxels, nGeometry, and CML2ExpVoxels::resetNEventsInVoxels().
Referenced by stopRun().
CML2ExpVoxels* CML2Convergence::getExpVoxels () inline
Definition at line 62 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 62 of file ML2Convergence.hh
References ML2ExpVoxels.
G4double CML2Convergence::getMaxNumberOfEvents () inline
Definition at line 61 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 61 of file ML2Convergence.hh
References maxNumberOfEvents.
int CML2Convergence::getNMaxLoops () inline
Definition at line 65 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 65 of file ML2Convergence.hh
References nMaxLoops.
Referenced by CML2RunAction::BeginOfRunAction().
void CML2Convergence::saveResults () inline
Definition at line 63 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 63 of file ML2Convergence.hh
References ML2ExpVoxels, and CML2ExpVoxels::saveResults().
Referenced by CML2RunAction::EndOfRunAction().
void CML2Convergence::setMaxNumberOfEvents (G4int val) inline
Definition at line 60 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 60 of file ML2Convergence.hh
void CML2Convergence::setNewGeometry () inline
Definition at line 64 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 64 of file ML2Convergence.hh
References idCurrentLoop, nGeometry, and nMaxLoops.
G4bool CML2Convergence::stopRun ()
Definition at line 95 of file ML2Convergence.cc.
View newest version in sPHENIX GitHub at line 95 of file ML2Convergence.cc
References convergenceCriteria(), idCurrentLoop, and ML2ExpVoxels.
Referenced by main().
Member Data Documentation
G4bool CML2Convergence::bCompareExp private
Definition at line 74 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 74 of file ML2Convergence.hh
Referenced by CML2Convergence(), and convergenceCriteria().
G4String CML2Convergence::fileExperimentalData private
Definition at line 72 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 72 of file ML2Convergence.hh
Referenced by CML2Convergence().
int CML2Convergence::idCurrentLoop private
Definition at line 76 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 76 of file ML2Convergence.hh
Referenced by CML2Convergence(), setNewGeometry(), and stopRun().
G4int CML2Convergence::maxNumberOfEvents private
Definition at line 75 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2Convergence.hh
Referenced by CML2Convergence(), convergenceCriteria(), and getMaxNumberOfEvents().
CML2ExpVoxels* CML2Convergence::ML2ExpVoxels private
Definition at line 70 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 70 of file ML2Convergence.hh
Referenced by add(), CML2Convergence(), convergenceCriteria(), getExpVoxels(), saveResults(), stopRun(), and ~CML2Convergence().
G4int CML2Convergence::nAccumulatedEvents private
Definition at line 75 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2Convergence.hh
Referenced by CML2Convergence().
G4int CML2Convergence::nGeometry private
Definition at line 75 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2Convergence.hh
Referenced by CML2Convergence(), convergenceCriteria(), and setNewGeometry().
int CML2Convergence::nMaxLoops private
Definition at line 76 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 76 of file ML2Convergence.hh
Referenced by CML2Convergence(), getNMaxLoops(), and setNewGeometry().
std::vector<Svoxel> CML2Convergence::voxels private
Definition at line 69 of file ML2Convergence.hh.
View newest version in sPHENIX GitHub at line 69 of file ML2Convergence.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Convergence.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Convergence.cc