ECCE @ EIC Software: MyPrimaryGeneratorActionFromFile Class Reference
MyPrimaryGeneratorActionFromFile Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/MyPrimaryGeneratorActionFromFile.hh>
Public Member Functions
MyPrimaryGeneratorActionFromFile ()
virtual ~MyPrimaryGeneratorActionFromFile ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *anEvent)
G4ParticleGun * GetParticleGun () const
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Public Member Functions inherited from G4VStateDependent
G4VStateDependent (G4bool bottom=false)
virtual ~G4VStateDependent ()
G4bool operator== (const G4VStateDependent &right) const
G4bool operator!= (const G4VStateDependent &right) const
Private Attributes
G4ParticleGun * fParticleGun
const DetectorConstruction * fDetector
Static Private Attributes
static MyFileReader * fileReader = 0
Detailed Description
Definition at line 48 of file MyPrimaryGeneratorActionFromFile.hh.
View newest version in sPHENIX GitHub at line 48 of file MyPrimaryGeneratorActionFromFile.hh
Constructor & Destructor Documentation
MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile ()
Definition at line 62 of file MyPrimaryGeneratorActionFromFile.cc.
View newest version in sPHENIX GitHub at line 62 of file MyPrimaryGeneratorActionFromFile.cc
References fDetector, fileReader, G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), MeV, particle, G4ParticleGun::SetParticleDefinition(), and G4ParticleGun::SetParticleEnergy().
MyPrimaryGeneratorActionFromFile::~MyPrimaryGeneratorActionFromFile () virtual
Definition at line 82 of file MyPrimaryGeneratorActionFromFile.cc.
View newest version in sPHENIX GitHub at line 82 of file MyPrimaryGeneratorActionFromFile.cc
References G4StateManager::DeregisterDependent(), fileReader, fParticleGun, and G4StateManager::GetStateManager().
Member Function Documentation
void MyPrimaryGeneratorActionFromFile::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 93 of file MyPrimaryGeneratorActionFromFile.cc.
View newest version in sPHENIX GitHub at line 93 of file MyPrimaryGeneratorActionFromFile.cc
References eV, fDetector, fileReader, fParticleGun, G4RandomDirection(), G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), MyFileReader::GetAnEvent(), DetectorConstruction::GetCytoThickness(), DetectorConstruction::GetNuclRadius(), m, radius, G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and thickness.
G4ParticleGun* MyPrimaryGeneratorActionFromFile::GetParticleGun (void) const inline
Definition at line 60 of file MyPrimaryGeneratorActionFromFile.hh.
View newest version in sPHENIX GitHub at line 60 of file MyPrimaryGeneratorActionFromFile.hh
References fParticleGun.
G4bool MyPrimaryGeneratorActionFromFile::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
Definition at line 134 of file MyPrimaryGeneratorActionFromFile.cc.
View newest version in sPHENIX GitHub at line 134 of file MyPrimaryGeneratorActionFromFile.cc
References eV, G4ParticleTable::FindParticle(), fParticleGun, G4State_Idle, G4ParticleTable::GetParticleTable(), particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
Member Data Documentation
const DetectorConstruction* MyPrimaryGeneratorActionFromFile::fDetector private
Definition at line 68 of file MyPrimaryGeneratorActionFromFile.hh.
View newest version in sPHENIX GitHub at line 68 of file MyPrimaryGeneratorActionFromFile.hh
Referenced by GeneratePrimaries(), and MyPrimaryGeneratorActionFromFile().
MyFileReader * MyPrimaryGeneratorActionFromFile::fileReader = 0 static private
Definition at line 66 of file MyPrimaryGeneratorActionFromFile.hh.
View newest version in sPHENIX GitHub at line 66 of file MyPrimaryGeneratorActionFromFile.hh
Referenced by GeneratePrimaries(), MyPrimaryGeneratorActionFromFile(), and ~MyPrimaryGeneratorActionFromFile().
G4ParticleGun* MyPrimaryGeneratorActionFromFile::fParticleGun private
Definition at line 67 of file MyPrimaryGeneratorActionFromFile.hh.
View newest version in sPHENIX GitHub at line 67 of file MyPrimaryGeneratorActionFromFile.hh
Referenced by GeneratePrimaries(), GetParticleGun(), MyPrimaryGeneratorActionFromFile(), Notify(), and ~MyPrimaryGeneratorActionFromFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/MyPrimaryGeneratorActionFromFile.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/MyPrimaryGeneratorActionFromFile.cc