ECCE @ EIC Software: G4WeightWindowProcess Class Reference
G4WeightWindowProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4WeightWindowProcess.hh>
Public Member Functions
G4WeightWindowProcess (const G4VWeightWindowAlgorithm &aWeightWindowAlgorithm, const G4VWeightWindowStore &aWWStore, const G4VTrackTerminator *TrackTerminator, G4PlaceOfAction placeOfAction, const G4String &aName="WeightWindowProcess", G4bool para=false)
virtual ~G4WeightWindowProcess ()
void SetParallelWorld (const G4String &parallelWorldName)
void SetParallelWorld (G4VPhysicalVolume *parallelWorld)
void StartTracking (G4Track *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual void KillTrack () const
virtual const G4String & GetName () const
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Public Member Functions inherited from G4VTrackTerminator
G4VTrackTerminator ()
virtual ~G4VTrackTerminator ()
Private Member Functions
G4WeightWindowProcess (const G4WeightWindowProcess &)
G4WeightWindowProcess & operator= (const G4WeightWindowProcess &)
void CopyStep (const G4Step &step)
Private Attributes
G4Step * fGhostStep
G4StepPoint * fGhostPreStepPoint
G4StepPoint * fGhostPostStepPoint
G4ParticleChange * fParticleChange
const G4VWeightWindowAlgorithm & fWeightWindowAlgorithm
const G4VWeightWindowStore & fWeightWindowStore
G4SamplingPostStepAction * fPostStepAction
G4PlaceOfAction fPlaceOfAction
G4TransportationManager * fTransportationManager
G4PathFinder * fPathFinder
G4String fGhostWorldName
G4VPhysicalVolume * fGhostWorld
G4Navigator * fGhostNavigator
G4int fNavigatorID
G4TouchableHandle fOldGhostTouchable
G4TouchableHandle fNewGhostTouchable
G4FieldTrack fFieldTrack
G4double fGhostSafety
G4bool fOnBoundary
G4bool fParaflag
G4FieldTrack fEndTrack
ELimited feLimited
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Protected Attributes inherited from G4VTrackTerminator
G4double kCarTolerance
Detailed Description
Definition at line 61 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 61 of file G4WeightWindowProcess.hh
Constructor & Destructor Documentation
G4WeightWindowProcess::G4WeightWindowProcess (const G4VWeightWindowAlgorithm & aWeightWindowAlgorithm, const G4VWeightWindowStore & aWWStore, const G4VTrackTerminator * TrackTerminator, G4PlaceOfAction placeOfAction, const G4String & aName = "WeightWindowProcess", G4bool para = false)
Definition at line 54 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 54 of file G4WeightWindowProcess.cc
References FatalException, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fParaflag, fParticleChange, fPathFinder, fPostStepAction, fTransportationManager, G4cout, G4endl, G4Exception(), G4PathFinder::GetInstance(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VProcess::GetProcessName(), G4TransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, and G4VProcess::verboseLevel.
G4WeightWindowProcess::~G4WeightWindowProcess () virtual
Definition at line 102 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 102 of file G4WeightWindowProcess.cc
References fParticleChange, and fPostStepAction.
G4WeightWindowProcess::G4WeightWindowProcess (const G4WeightWindowProcess &) private
Member Function Documentation
G4VParticleChange * G4WeightWindowProcess::AlongStepDoIt (const G4Track & track, const G4Step &) virtual
Implements G4VProcess.
Definition at line 388 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 388 of file G4WeightWindowProcess.cc
References G4VParticleChange::Initialize(), and G4VProcess::pParticleChange.
G4double G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 301 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 301 of file G4WeightWindowProcess.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PathFinder::ComputeStep(), DBL_MAX, feLimited, fEndTrack, fFieldTrack, fGhostNavigator, fGhostSafety, fNavigatorID, fOnBoundary, fParaflag, fPathFinder, G4Track::GetCurrentStepNumber(), G4Track::GetVolume(), kDoNot, kSharedOther, kSharedTransport, kUnique, NotCandidateForSelection, and G4FieldTrackUpdator::Update().
G4VParticleChange * G4WeightWindowProcess::AtRestDoIt (const G4Track & , const G4Step &) virtual
Implements G4VProcess.
Definition at line 382 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 382 of file G4WeightWindowProcess.cc
G4double G4WeightWindowProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) virtual
Implements G4VProcess.
Definition at line 375 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 375 of file G4WeightWindowProcess.cc
void G4WeightWindowProcess::CopyStep (const G4Step & step) private
Definition at line 398 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 398 of file G4WeightWindowProcess.cc
References fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fOnBoundary, fPostStepDoItProc, G4Step::GetControlFlag(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4Step::SetControlFlag(), G4Step::SetStepLength(), G4StepPoint::SetStepStatus(), G4Step::SetTotalEnergyDeposit(), and G4Step::SetTrack().
Referenced by PostStepDoIt().
const G4String & G4WeightWindowProcess::GetName (void) const virtual
Implements G4VTrackTerminator.
Definition at line 295 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 295 of file G4WeightWindowProcess.cc
References G4VProcess::GetProcessName().
void G4WeightWindowProcess::KillTrack () const virtual
Implements G4VTrackTerminator.
Definition at line 290 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 290 of file G4WeightWindowProcess.cc
References fParticleChange, fStopAndKill, and G4VParticleChange::ProposeTrackStatus().
G4WeightWindowProcess& G4WeightWindowProcess::operator= (const G4WeightWindowProcess &) private
G4VParticleChange * G4WeightWindowProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Implements G4VProcess.
Definition at line 200 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 200 of file G4WeightWindowProcess.cc
References G4VWeightWindowAlgorithm::Calculate(), CopyStep(), G4PathFinder::CreateTouchableHandle(), G4SamplingPostStepAction::DoIt(), fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fParaflag, fParticleChange, fPathFinder, fPlaceOfAction, fPostStepAction, fWeightWindowAlgorithm, fWeightWindowStore, G4Track::GetKineticEnergy(), G4VWeightWindowStore::GetLowerWeight(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4VTouchable::GetReplicaNumber(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4Track::GetWeight(), G4ParticleChange::Initialize(), G4VTrackTerminator::kCarTolerance, onBoundary, onBoundaryAndCollision, onCollision, and G4StepPoint::SetTouchableHandle().
G4double G4WeightWindowProcess::PostStepGetPhysicalInteractionLength (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 187 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 187 of file G4WeightWindowProcess.cc
References DBL_MAX, and Forced.
void G4WeightWindowProcess::SetParallelWorld (const G4String & parallelWorldName)
Definition at line 118 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 118 of file G4WeightWindowProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4TransportationManager::GetNavigator(), and G4TransportationManager::GetParallelWorld().
Referenced by G4WeightWindowConfigurator::Configure().
void G4WeightWindowProcess::SetParallelWorld (G4VPhysicalVolume * parallelWorld)
Definition at line 130 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 130 of file G4WeightWindowProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4VPhysicalVolume::GetName(), and G4TransportationManager::GetNavigator().
void G4WeightWindowProcess::StartTracking (G4Track * trk) virtual
Reimplemented from G4VProcess.
Definition at line 146 of file G4WeightWindowProcess.cc.
View newest version in sPHENIX GitHub at line 146 of file G4WeightWindowProcess.cc
References G4TransportationManager::ActivateNavigator(), G4PathFinder::CreateTouchableHandle(), FatalException, fGhostNavigator, fGhostPostStepPoint, fGhostPreStepPoint, fGhostSafety, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fParaflag, fPathFinder, fTransportationManager, G4Exception(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4PathFinder::PrepareNewTrack(), and G4StepPoint::SetTouchableHandle().
Member Data Documentation
ELimited G4WeightWindowProcess::feLimited private
Definition at line 166 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 166 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4FieldTrack G4WeightWindowProcess::fEndTrack private
Definition at line 165 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 165 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4FieldTrack G4WeightWindowProcess::fFieldTrack private
Definition at line 160 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 160 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4Navigator* G4WeightWindowProcess::fGhostNavigator private
Definition at line 156 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 156 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), SetParallelWorld(), and StartTracking().
G4StepPoint* G4WeightWindowProcess::fGhostPostStepPoint private
Definition at line 140 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 140 of file G4WeightWindowProcess.hh
Referenced by CopyStep(), G4WeightWindowProcess(), PostStepDoIt(), and StartTracking().
G4StepPoint* G4WeightWindowProcess::fGhostPreStepPoint private
Definition at line 139 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 139 of file G4WeightWindowProcess.hh
Referenced by CopyStep(), G4WeightWindowProcess(), PostStepDoIt(), and StartTracking().
G4double G4WeightWindowProcess::fGhostSafety private
Definition at line 161 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 161 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4Step* G4WeightWindowProcess::fGhostStep private
Definition at line 138 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 138 of file G4WeightWindowProcess.hh
Referenced by CopyStep(), and G4WeightWindowProcess().
G4VPhysicalVolume* G4WeightWindowProcess::fGhostWorld private
Definition at line 155 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 155 of file G4WeightWindowProcess.hh
Referenced by SetParallelWorld().
G4String G4WeightWindowProcess::fGhostWorldName private
Definition at line 154 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 154 of file G4WeightWindowProcess.hh
Referenced by SetParallelWorld().
G4int G4WeightWindowProcess::fNavigatorID private
Definition at line 157 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 157 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4TouchableHandle G4WeightWindowProcess::fNewGhostTouchable private
Definition at line 159 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 159 of file G4WeightWindowProcess.hh
Referenced by PostStepDoIt(), and StartTracking().
G4TouchableHandle G4WeightWindowProcess::fOldGhostTouchable private
Definition at line 158 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 158 of file G4WeightWindowProcess.hh
Referenced by PostStepDoIt(), and StartTracking().
G4bool G4WeightWindowProcess::fOnBoundary private
Definition at line 162 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 162 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), CopyStep(), PostStepDoIt(), and StartTracking().
G4bool G4WeightWindowProcess::fParaflag private
Definition at line 164 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 164 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess(), PostStepDoIt(), and StartTracking().
G4ParticleChange* G4WeightWindowProcess::fParticleChange private
Definition at line 142 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 142 of file G4WeightWindowProcess.hh
Referenced by G4WeightWindowProcess(), KillTrack(), PostStepDoIt(), and ~G4WeightWindowProcess().
G4PathFinder* G4WeightWindowProcess::fPathFinder private
Definition at line 149 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 149 of file G4WeightWindowProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess(), PostStepDoIt(), and StartTracking().
G4PlaceOfAction G4WeightWindowProcess::fPlaceOfAction private
Definition at line 146 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 146 of file G4WeightWindowProcess.hh
Referenced by PostStepDoIt().
G4SamplingPostStepAction* G4WeightWindowProcess::fPostStepAction private
Definition at line 145 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 145 of file G4WeightWindowProcess.hh
Referenced by G4WeightWindowProcess(), PostStepDoIt(), and ~G4WeightWindowProcess().
G4TransportationManager* G4WeightWindowProcess::fTransportationManager private
Definition at line 148 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 148 of file G4WeightWindowProcess.hh
Referenced by G4WeightWindowProcess(), SetParallelWorld(), and StartTracking().
const G4VWeightWindowAlgorithm& G4WeightWindowProcess::fWeightWindowAlgorithm private
Definition at line 143 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 143 of file G4WeightWindowProcess.hh
Referenced by PostStepDoIt().
const G4VWeightWindowStore& G4WeightWindowProcess::fWeightWindowStore private
Definition at line 144 of file G4WeightWindowProcess.hh.
View newest version in sPHENIX GitHub at line 144 of file G4WeightWindowProcess.hh
Referenced by PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4WeightWindowProcess.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4WeightWindowProcess.cc