ECCE @ EIC Software: __1DSortOut Class Reference
__1DSortOut Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDMap.hh>
Classes
struct sortOutNDim
Public Member Functions
__1DSortOut (size_t dimension)
__1DSortOut (const __1DSortOut &right)
int GetDimension ()
G4KDNode_Base * GetMidle (size_t &)
std::deque< G4KDNode_Base * >
::iterator Insert (G4KDNode_Base *)
G4KDNode_Base * PopOutMiddle ()
void Sort ()
void Erase (std::deque< G4KDNode_Base * >::iterator &)
size_t Size ()
Protected Attributes
std::deque< G4KDNode_Base * > fContainer
sortOutNDim fSortOutNDim
Detailed Description
Definition at line 57 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 57 of file G4KDMap.hh
Constructor & Destructor Documentation
__1DSortOut::__1DSortOut (size_t dimension)
Definition at line 41 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 41 of file G4KDMap.cc
__1DSortOut::__1DSortOut (const __1DSortOut & right)
Definition at line 46 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 46 of file G4KDMap.cc
Member Function Documentation
void __1DSortOut::Erase (std::deque< G4KDNode_Base * >::iterator &)
Definition at line 85 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 85 of file G4KDMap.cc
References fContainer.
int __1DSortOut::GetDimension ()
Definition at line 51 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 51 of file G4KDMap.cc
References __1DSortOut::sortOutNDim::fDimension, and fSortOutNDim.
G4KDNode_Base * __1DSortOut::GetMidle (size_t & main_middle)
Definition at line 56 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 56 of file G4KDMap.cc
References fContainer.
Referenced by PopOutMiddle().
_deq_iterator __1DSortOut::Insert (G4KDNode_Base * pos)
Definition at line 63 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 63 of file G4KDMap.cc
References fContainer, and pos().
G4KDNode_Base * __1DSortOut::PopOutMiddle ()
Definition at line 68 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 68 of file G4KDMap.cc
References fContainer, GetMidle(), and pos().
size_t __1DSortOut::Size () inline
Definition at line 69 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 69 of file G4KDMap.hh
References fContainer.
void __1DSortOut::Sort ()
Definition at line 80 of file G4KDMap.cc.
View newest version in sPHENIX GitHub at line 80 of file G4KDMap.cc
References fContainer, and fSortOutNDim.
Member Data Documentation
std::deque<G4KDNode_Base*> __1DSortOut::fContainer protected
Definition at line 85 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 85 of file G4KDMap.hh
Referenced by Erase(), GetMidle(), Insert(), PopOutMiddle(), Size(), and Sort().
sortOutNDim __1DSortOut::fSortOutNDim protected
Definition at line 86 of file G4KDMap.hh.
View newest version in sPHENIX GitHub at line 86 of file G4KDMap.hh
Referenced by GetDimension(), and Sort().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDMap.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4KDMap.cc