ECCE @ EIC Software: B02PVolumeStore Class Reference
B02PVolumeStore Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/include/B02PVolumeStore.hh>
Public Member Functions
B02PVolumeStore ()
~B02PVolumeStore ()
void AddPVolume (const G4GeometryCell &cell)
const G4VPhysicalVolume * GetPVolume (const G4String &name) const
G4int Size ()
G4String GetPNames () const
Private Attributes
B02SetGeometryCell fSetGeometryCell
Detailed Description
Definition at line 52 of file B02PVolumeStore.hh.
View newest version in sPHENIX GitHub at line 52 of file B02PVolumeStore.hh
Constructor & Destructor Documentation
B02PVolumeStore::B02PVolumeStore ()
Definition at line 46 of file B02PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 46 of file B02PVolumeStore.cc
B02PVolumeStore::~B02PVolumeStore ()
Definition at line 50 of file B02PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 50 of file B02PVolumeStore.cc
Member Function Documentation
void B02PVolumeStore::AddPVolume (const G4GeometryCell & cell)
Definition at line 54 of file B02PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 54 of file B02PVolumeStore.cc
References fSetGeometryCell, G4cout, G4endl, and it.
Referenced by B02ImportanceDetectorConstruction::Construct().
G4String B02PVolumeStore::GetPNames () const
Definition at line 89 of file B02PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 89 of file B02PVolumeStore.cc
References fSetGeometryCell, G4VPhysicalVolume::GetName(), and it.
Referenced by B02ImportanceDetectorConstruction::ListPhysNamesAsG4String().
const G4VPhysicalVolume * B02PVolumeStore::GetPVolume (const G4String & name) const
Definition at line 71 of file B02PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 71 of file B02PVolumeStore.cc
References fSetGeometryCell, G4cout, G4endl, G4VPhysicalVolume::GetName(), and it.
Referenced by B02ImportanceDetectorConstruction::GetGeometryCell(), and B02ImportanceDetectorConstruction::GetPhysicalVolumeByName().
G4int B02PVolumeStore::Size ()
Definition at line 110 of file B02PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 110 of file B02PVolumeStore.cc
References fSetGeometryCell.
Referenced by B02ImportanceDetectorConstruction::CreateImportanceStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
Member Data Documentation
B02SetGeometryCell B02PVolumeStore::fSetGeometryCell private
Definition at line 63 of file B02PVolumeStore.hh.
View newest version in sPHENIX GitHub at line 63 of file B02PVolumeStore.hh
Referenced by AddPVolume(), GetPNames(), GetPVolume(), and Size().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/include/B02PVolumeStore.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/src/B02PVolumeStore.cc