ECCE @ EIC Software: G4VSceneHandler Class Reference
G4VSceneHandler Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VSceneHandler.hh>
Public Types
enum MarkerSizeType { world, screen }
Public Member Functions
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void AddSolid (const G4Box &)
virtual void AddSolid (const G4Cons &)
virtual void AddSolid (const G4Orb &)
virtual void AddSolid (const G4Para &)
virtual void AddSolid (const G4Sphere &)
virtual void AddSolid (const G4Torus &)
virtual void AddSolid (const G4Trap &)
virtual void AddSolid (const G4Trd &)
virtual void AddSolid (const G4Tubs &)
virtual void AddSolid (const G4Ellipsoid &)
virtual void AddSolid (const G4Polycone &)
virtual void AddSolid (const G4Polyhedra &)
virtual void AddSolid (const G4TessellatedSolid &)
virtual void AddSolid (const G4VSolid &)
virtual void AddCompound (const G4VTrajectory &)
virtual void AddCompound (const G4VHit &)
virtual void AddCompound (const G4VDigi &)
virtual void AddCompound (const G4THitsMap< G4double > &)
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual void AddPrimitive (const G4Polyline &)=0
virtual void AddPrimitive (const G4Scale &)
virtual void AddPrimitive (const G4Text &)=0
virtual void AddPrimitive (const G4Circle &)=0
virtual void AddPrimitive (const G4Square &)=0
virtual void AddPrimitive (const G4Polymarker &)
virtual void AddPrimitive (const G4Polyhedron &)=0
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
virtual void ClearTransientStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Protected Member Functions
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Private Member Functions
G4VSceneHandler (const G4VSceneHandler &)
G4VSceneHandler & operator= (const G4VSceneHandler &)
Friends
class G4VViewer
std::ostream & operator<< (std::ostream &os, const G4VSceneHandler &s)
Detailed Description
Definition at line 61 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VSceneHandler.hh
Member Enumeration Documentation
enum G4VSceneHandler::MarkerSizeType
Enumerator:
world
screen
Definition at line 68 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VSceneHandler.hh
Constructor & Destructor Documentation
G4VSceneHandler::G4VSceneHandler (G4VGraphicsSystem & system, G4int id, const G4String & name = "")
Definition at line 96 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 96 of file G4VSceneHandler.cc
References fName, fpScene, fSceneHandlerId, fSystem, fTransientsDrawnThisEvent, fTransientsDrawnThisRun, G4VisManager::GetInstance(), G4VGraphicsSystem::GetName(), G4VisManager::GetTransientsDrawnThisEvent(), and G4VisManager::GetTransientsDrawnThisRun().
G4VSceneHandler::~G4VSceneHandler () virtual
Definition at line 127 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 127 of file G4VSceneHandler.cc
References fViewerList.
G4VSceneHandler::G4VSceneHandler (const G4VSceneHandler &) private
Member Function Documentation
void G4VSceneHandler::AddCompound (const G4VTrajectory & traj) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 320 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 320 of file G4VSceneHandler.cc
References G4VTrajectory::DrawTrajectory(), FatalException, fpModel, and G4Exception().
Referenced by G4VRML1FileSceneHandler::AddCompound(), G4VRML2FileSceneHandler::AddCompound(), G4HepRepFileSceneHandler::AddCompound(), G4HepRepSceneHandler::AddCompound(), G4DAWNFILESceneHandler::AddCompound(), and G4GMocrenFileSceneHandler::AddCompound().
void G4VSceneHandler::AddCompound (const G4VHit & hit) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 332 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 332 of file G4VSceneHandler.cc
References Draw().
void G4VSceneHandler::AddCompound (const G4VDigi & digi) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 337 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 337 of file G4VSceneHandler.cc
References Draw().
void G4VSceneHandler::AddCompound (const G4THitsMap< G4double > & hits) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 342 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 342 of file G4VSceneHandler.cc
References G4VScoringMesh::DrawMesh(), G4String::first(), G4cout, G4endl, G4ScoringManager::GetMesh(), GetName(), G4ScoringManager::GetNumberOfMesh(), G4VScoringMesh::GetScoreMap(), G4ScoringManager::GetScoringManagerIfExist(), hits(), and G4VScoringMesh::IsActive().
void G4VSceneHandler::AddCompound (const G4THitsMap< G4StatDouble > & hits) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 385 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 385 of file G4VSceneHandler.cc
References G4VScoringMesh::DrawMesh(), G4String::first(), G4cout, G4endl, G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4VScoringMesh::GetScoreMap(), G4ScoringManager::GetScoringManagerIfExist(), hits(), and G4VScoringMesh::IsActive().
virtual void G4VSceneHandler::AddPrimitive (const G4Polyline &) pure virtual
Implements G4VGraphicsScene.
Implemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
Referenced by G4XXXSceneHandler::AddPrimitive(), G4DAWNFILESceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddPrimitive(), G4XXXFileSceneHandler::AddPrimitive(), G4VRML2FileSceneHandler::AddPrimitive(), G4VRML1FileSceneHandler::AddPrimitive(), G4XXXStoredSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), G4XXXSGSceneHandler::AddPrimitive(), AddPrimitive(), and RequestPrimitives().
void G4VSceneHandler::AddPrimitive (const G4Scale & scale) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VTreeSceneHandler, G4XXXSceneHandler, and G4RayTracerSceneHandler.
Definition at line 432 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 432 of file G4VSceneHandler.cc
References AddPrimitive(), fpModel, fpScene, G4Scale::GetAnnotation(), G4Scale::GetAnnotationSize(), G4Scale::GetAutoPlacing(), G4VVisCommand::GetCurrentTextColour(), G4Scale::GetDirection(), G4Scene::GetExtent(), G4Scale::GetLength(), G4VModel::GetTransformation(), G4Visible::GetVisAttributes(), G4VisExtent::GetXmax(), G4VisExtent::GetXmin(), G4VisExtent::GetYmax(), G4VisExtent::GetYmin(), G4VisExtent::GetZmax(), G4VisExtent::GetZmin(), halfpi, BTOF::length, r1, r2, G4Visible::SetVisAttributes(), G4Polyline::transform(), G4Scale::x, xmax, xmin, G4Scale::y, ymax, ymin, and G4Scale::z.
virtual void G4VSceneHandler::AddPrimitive (const G4Text &) pure virtual
Implements G4VGraphicsScene.
Implemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
virtual void G4VSceneHandler::AddPrimitive (const G4Circle &) pure virtual
Implements G4VGraphicsScene.
Implemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
virtual void G4VSceneHandler::AddPrimitive (const G4Square &) pure virtual
Implements G4VGraphicsScene.
Implemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
void G4VSceneHandler::AddPrimitive (const G4Polymarker & polymarker) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VTreeSceneHandler, G4XXXSceneHandler, and G4RayTracerSceneHandler.
Definition at line 536 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 536 of file G4VSceneHandler.cc
References AddPrimitive(), G4Polymarker::circles, G4Polymarker::dots, G4Polymarker::GetMarkerType(), G4VMarker::SetPosition(), G4VMarker::SetScreenSize(), G4VMarker::SetWorldSize(), square(), and G4Polymarker::squares.
virtual void G4VSceneHandler::AddPrimitive (const G4Polyhedron &) pure virtual
Implements G4VGraphicsScene.
Implemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXFileSceneHandler, G4GMocrenFileSceneHandler, G4VTreeSceneHandler, G4DAWNFILESceneHandler, G4RayTracerSceneHandler, and G4XXXSceneHandler.
void G4VSceneHandler::AddSolid (const G4Box & box) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4XXXSGSceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4XXXStoredSceneHandler, and G4XXXFileSceneHandler.
Definition at line 249 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 249 of file G4VSceneHandler.cc
References AddSolidT().
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4VRML1FileSceneHandler::AddSolid(), G4VRML2FileSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4DAWNFILESceneHandler::AddSolid(), and G4GMocrenFileSceneHandler::AddSolid().
void G4VSceneHandler::AddSolid (const G4Cons & cons) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 268 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 268 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4Orb & orb) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 272 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 272 of file G4VSceneHandler.cc
References AddSolidWithAuxiliaryEdges().
void G4VSceneHandler::AddSolid (const G4Para & para) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 276 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 276 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4Sphere & sphere) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 280 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 280 of file G4VSceneHandler.cc
References AddSolidWithAuxiliaryEdges().
void G4VSceneHandler::AddSolid (const G4Torus & torus) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 284 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 284 of file G4VSceneHandler.cc
References AddSolidWithAuxiliaryEdges().
void G4VSceneHandler::AddSolid (const G4Trap & trap) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 288 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 288 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4Trd & trd) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 292 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 292 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4Tubs & tubs) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 296 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 296 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 300 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 300 of file G4VSceneHandler.cc
References AddSolidWithAuxiliaryEdges().
void G4VSceneHandler::AddSolid (const G4Polycone & polycone) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 304 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 304 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4Polyhedra & polyhedra) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 308 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 308 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4TessellatedSolid & tess) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 312 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 312 of file G4VSceneHandler.cc
References AddSolidT().
void G4VSceneHandler::AddSolid (const G4VSolid & solid) virtual
Implements G4VGraphicsScene.
Reimplemented in G4GMocrenFileSceneHandler, G4XXXSGSceneHandler, G4DAWNFILESceneHandler, G4HepRepSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4XXXFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 316 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 316 of file G4VSceneHandler.cc
References AddSolidT().
template<class T > void G4VSceneHandler::AddSolidT (const T & solid)
Definition at line 223 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 223 of file G4VSceneHandler.cc
Referenced by AddSolid().
template<class T > void G4VSceneHandler::AddSolidWithAuxiliaryEdges (const T & solid)
Definition at line 231 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 231 of file G4VSceneHandler.cc
References G4VisAttributes::SetForceAuxEdgeVisible().
Referenced by AddSolid().
void G4VSceneHandler::AddViewerToList (G4VViewer * pView)
Definition at line 428 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 428 of file G4VSceneHandler.cc
References fViewerList.
void G4VSceneHandler::BeginModeling () virtual
Reimplemented in G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VTreeSceneHandler, and G4ASCIITreeSceneHandler.
Definition at line 210 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 210 of file G4VSceneHandler.cc
Referenced by G4VTreeSceneHandler::BeginModeling(), G4DAWNFILESceneHandler::BeginModeling(), G4GMocrenFileSceneHandler::BeginModeling(), G4HepRepSceneHandler::BeginModeling(), G4HepRepFileSceneHandler::BeginModeling(), G4GMocrenFileSceneHandler::GFBeginModeling(), and ProcessScene().
void G4VSceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4GMocrenFileSceneHandler, and G4DAWNFILESceneHandler.
Definition at line 163 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 163 of file G4VSceneHandler.cc
References FatalException, and G4Exception().
Referenced by G4GMocrenFileSceneHandler::BeginPrimitives(), G4XXXStoredSceneHandler::BeginPrimitives(), G4HepRepSceneHandler::BeginPrimitives(), G4XXXSGSceneHandler::BeginPrimitives(), and RequestPrimitives().
void G4VSceneHandler::BeginPrimitives2D (const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VGraphicsScene.
Reimplemented in G4HepRepFileSceneHandler.
Definition at line 187 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 187 of file G4VSceneHandler.cc
References FatalException, and G4Exception().
Referenced by G4HepRepFileSceneHandler::BeginPrimitives2D().
void G4VSceneHandler::ClearStore () virtual
Reimplemented in G4XXXSGSceneHandler, G4XXXStoredSceneHandler, and G4RayTracerSceneHandler.
Definition at line 218 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 218 of file G4VSceneHandler.cc
Referenced by G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), and G4VViewer::ProcessView().
void G4VSceneHandler::ClearTransientStore () virtual
Reimplemented in G4XXXSGSceneHandler, G4HepRepFileSceneHandler, G4XXXStoredSceneHandler, G4DAWNFILESceneHandler, G4GMocrenFileSceneHandler, G4VRML1FileSceneHandler, and G4VRML2FileSceneHandler.
Definition at line 220 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 220 of file G4VSceneHandler.cc
Referenced by G4VisManager::ClearTransientStoreIfMarked(), G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), G4VisCommandViewerClearTransients::SetNewValue(), and G4VisCommandViewerRebuild::SetNewValue().
G4DisplacedSolid * G4VSceneHandler::CreateCutawaySolid () protected virtual
Definition at line 937 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 937 of file G4VSceneHandler.cc
Referenced by CreateModelingParameters().
G4ModelingParameters * G4VSceneHandler::CreateModelingParameters ()
Definition at line 834 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 834 of file G4VSceneHandler.cc
References G4ModelingParameters::cloud, G4ViewParameters::cloud, CreateCutawaySolid(), CreateSectionSolid(), fpViewer, G4ViewParameters::GetCBDAlgorithmNumber(), G4ViewParameters::GetCBDParameters(), G4ViewParameters::GetDefaultVisAttributes(), G4ViewParameters::GetDrawingStyle(), G4ViewParameters::GetExplodeCentre(), G4ViewParameters::GetExplodeFactor(), G4ViewParameters::GetNoOfSides(), G4ViewParameters::GetNumberOfCloudPoints(), G4VisManager::GetVerbosity(), G4ViewParameters::GetVisAttributesModifiers(), G4ViewParameters::GetVisibleDensity(), G4ModelingParameters::hlhsr, G4ViewParameters::hlhsr, G4ModelingParameters::hlr, G4ViewParameters::hlr, G4ModelingParameters::hsr, G4ViewParameters::hsr, G4ViewParameters::IsCulling(), G4ViewParameters::IsCullingCovered(), G4ViewParameters::IsCullingInvisible(), G4ViewParameters::IsCutaway(), G4ViewParameters::IsDensityCulling(), G4ViewParameters::IsSection(), G4ModelingParameters::SetCBDAlgorithmNumber(), G4ModelingParameters::SetCBDParameters(), G4ModelingParameters::SetCutawaySolid(), G4ModelingParameters::SetExplodeCentre(), G4ModelingParameters::SetExplodeFactor(), G4ModelingParameters::SetNumberOfCloudPoints(), G4ModelingParameters::SetSectionSolid(), G4ModelingParameters::SetVisAttributesModifiers(), G4ModelingParameters::SetWarning(), G4VisManager::warnings, G4ModelingParameters::wf, and G4ViewParameters::wireframe.
Referenced by DrawEndOfRunModels(), DrawEvent(), and ProcessScene().
G4DisplacedSolid * G4VSceneHandler::CreateSectionSolid () protected virtual
Definition at line 900 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 900 of file G4VSceneHandler.cc
References a, HepGeom::Plane3D< T >::a(), angle, b, HepGeom::Plane3D< T >::b(), HepGeom::Plane3D< T >::c(), c, HepGeom::BasicVector3D< T >::cross(), HepGeom::Plane3D< T >::d(), d, HepGeom::BasicVector3D< T >::dot(), e, fpScene, fpViewer, G4Scene::GetExtent(), G4VisExtent::GetExtentCentre(), G4VisExtent::GetExtentRadius(), G4ViewParameters::GetSectionPlane(), G4VViewer::GetViewParameters(), G4ViewParameters::IsSection(), HepGeom::BasicVector3D< T >::mag(), radius, and G4InuclParticleNames::sp.
Referenced by CreateModelingParameters().
void G4VSceneHandler::DrawEndOfRunModels ()
Definition at line 813 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 813 of file G4VSceneHandler.cc
References CreateModelingParameters(), fpModel, fpScene, and G4ModelingParameters::SetEvent().
Referenced by G4VisManager::EndOfRun(), and ProcessScene().
void G4VSceneHandler::DrawEvent (const G4Event * event)
Definition at line 792 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 792 of file G4VSceneHandler.cc
References CreateModelingParameters(), fpModel, fpScene, and G4ModelingParameters::SetEvent().
Referenced by G4VisManager::EndOfEvent(), and ProcessScene().
void G4VSceneHandler::EndModeling () virtual
Reimplemented in G4HepRepFileSceneHandler, G4HepRepSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4GMocrenFileSceneHandler, G4DAWNFILESceneHandler, G4VTreeSceneHandler, and G4ASCIITreeSceneHandler.
Definition at line 213 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 213 of file G4VSceneHandler.cc
References fpModel.
Referenced by G4VTreeSceneHandler::EndModeling(), G4DAWNFILESceneHandler::EndModeling(), G4GMocrenFileSceneHandler::EndModeling(), G4HepRepSceneHandler::EndModeling(), G4HepRepFileSceneHandler::EndModeling(), G4GMocrenFileSceneHandler::GFEndModeling(), and ProcessScene().
void G4VSceneHandler::EndPrimitives () virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, G4VRML1FileSceneHandler, G4VRML2FileSceneHandler, G4GMocrenFileSceneHandler, and G4DAWNFILESceneHandler.
Definition at line 175 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 175 of file G4VSceneHandler.cc
References FatalException, fNestingDepth, fReadyForTransients, fTransientsDrawnThisEvent, fTransientsDrawnThisRun, and G4Exception().
Referenced by G4GMocrenFileSceneHandler::EndPrimitives(), G4XXXStoredSceneHandler::EndPrimitives(), G4HepRepSceneHandler::EndPrimitives(), G4XXXSGSceneHandler::EndPrimitives(), and RequestPrimitives().
void G4VSceneHandler::EndPrimitives2D () virtual
Implements G4VGraphicsScene.
Reimplemented in G4HepRepFileSceneHandler.
Definition at line 198 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 198 of file G4VSceneHandler.cc
References FatalException, fNestingDepth, fProcessing2D, fReadyForTransients, fTransientsDrawnThisEvent, fTransientsDrawnThisRun, and G4Exception().
Referenced by G4HepRepFileSceneHandler::EndPrimitives2D().
G4bool G4VSceneHandler::GetAuxEdgeVisible (const G4VisAttributes * pVisAttribs)
Definition at line 1105 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1105 of file G4VSceneHandler.cc
References fpViewer, G4VViewer::GetViewParameters(), G4ViewParameters::IsAuxEdgeVisible(), and G4VisAttributes::IsForcedAuxEdgeVisible().
const G4Colour& G4VSceneHandler::GetColor ()
Referenced by G4HepRepSceneHandler::AddPrimitive(), G4HepRepSceneHandler::getColorFor(), and G4HepRepSceneHandler::setMarker().
const G4Colour& G4VSceneHandler::GetColour ()
Referenced by GetTextColour().
G4VViewer* G4VSceneHandler::GetCurrentViewer () const
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4HepRepSceneHandler::close(), and G4HepRepSceneHandler::closeHepRep().
G4ViewParameters::DrawingStyle G4VSceneHandler::GetDrawingStyle (const G4VisAttributes * pVisAttribs)
Definition at line 1046 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1046 of file G4VSceneHandler.cc
References G4VisAttributes::cloud, G4ViewParameters::cloud, G4ViewParameters::GetDrawingStyle(), G4ViewParameters::hlhsr, G4ViewParameters::hlr, G4ViewParameters::hsr, G4VisAttributes::solid, G4VisAttributes::wireframe, and G4ViewParameters::wireframe.
Referenced by G4XXXSceneHandler::AddPrimitive(), G4XXXFileSceneHandler::AddPrimitive(), G4XXXStoredSceneHandler::AddPrimitive(), G4XXXSGSceneHandler::AddPrimitive(), and RequestPrimitives().
const G4VisExtent & G4VSceneHandler::GetExtent () const virtual
Reimplemented from G4VGraphicsScene.
Definition at line 136 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 136 of file G4VSceneHandler.cc
References fpScene, and G4Scene::GetExtent().
G4VGraphicsSystem* G4VSceneHandler::GetGraphicsSystem () const
Referenced by G4ASCIITreeSceneHandler::BeginModeling(), G4ASCIITreeSceneHandler::EndModeling(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VisCommandViewerList::SetNewValue(), G4ASCIITreeSceneHandler::WriteHeader(), G4HepRepSceneHandler::~G4HepRepSceneHandler(), and G4HepRepViewer::~G4HepRepViewer().
G4double G4VSceneHandler::GetLineWidth (const G4VisAttributes * pVisAttribs)
Definition at line 1036 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1036 of file G4VSceneHandler.cc
References fpViewer, and G4VisAttributes::GetLineWidth().
G4double G4VSceneHandler::GetMarkerDiameter (const G4VMarker & , MarkerSizeType &)
G4double G4VSceneHandler::GetMarkerRadius (const G4VMarker & , MarkerSizeType &)
Referenced by G4HepRepSceneHandler::setMarker().
G4double G4VSceneHandler::GetMarkerSize (const G4VMarker & marker, G4VSceneHandler::MarkerSizeType & markerSizeType)
Definition at line 1114 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1114 of file G4VSceneHandler.cc
References G4VMarker::GetScreenSize(), G4VMarker::GetWorldSize(), and Acts::Test::world.
Referenced by G4XXXSceneHandler::AddPrimitive(), G4XXXFileSceneHandler::AddPrimitive(), G4XXXStoredSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), and G4XXXSGSceneHandler::AddPrimitive().
G4bool G4VSceneHandler::GetMarkForClearingTransientStore () const
Referenced by G4VisManager::ClearTransientStoreIfMarked().
G4VModel* G4VSceneHandler::GetModel () const
Referenced by G4GMocrenFileSceneHandler::AddDetector(), and G4GMocrenFileSceneHandler::AddSolid().
const G4String& G4VSceneHandler::GetName () const
Referenced by G4GMocrenFileSceneHandler::AddCompound(), AddCompound(), G4GMocrenFileSceneHandler::AddSolid(), G4HepRepSceneHandler::closeHepRep(), G4VViewer::G4VViewer(), G4VisCommandSceneHandlerList::SetNewValue(), G4VisCommandSceneNotifyHandlers::SetNewValue(), G4VisCommandViewerRefresh::SetNewValue(), and G4VisCommandViewerUpdate::SetNewValue().
G4int G4VSceneHandler::GetNoOfSides (const G4VisAttributes * pVisAttribs)
Definition at line 1137 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1137 of file G4VSceneHandler.cc
References fpViewer, G4cout, G4endl, G4VisAttributes::GetForcedLineSegmentsPerCircle(), G4VisAttributes::GetMinLineSegmentsPerCircle(), G4ViewParameters::GetNoOfSides(), G4VViewer::GetViewParameters(), and G4VisAttributes::IsForceLineSegmentsPerCircle().
Referenced by RequestPrimitives().
G4int G4VSceneHandler::GetNumberOfCloudPoints (const G4VisAttributes * pVisAttribs) const
Definition at line 1092 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1092 of file G4VSceneHandler.cc
References G4VisAttributes::cloud.
Referenced by RequestPrimitives().
const G4Transform3D& G4VSceneHandler::GetObjectTransformation () const
G4Scene* G4VSceneHandler::GetScene () const
Referenced by G4VVisCommand::CheckSceneAndNotifyHandlers(), G4HepRepSceneHandler::closeHepRep(), G4GMocrenFileSceneHandler::GFBeginModeling(), G4VVisCommand::RefreshIfRequired(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSceneNotifyHandlers::SetNewValue(), G4VisCommandViewerRefresh::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), G4VisCommandViewerUpdate::SetNewValue(), and G4RayTracerViewer::SetView().
G4int G4VSceneHandler::GetSceneHandlerId () const
const G4Colour& G4VSceneHandler::GetTextColor (const G4Text &)
const G4Colour & G4VSceneHandler::GetTextColour (const G4Text & text)
Definition at line 1027 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1027 of file G4VSceneHandler.cc
References GetColour(), G4VVisCommand::GetCurrentTextColour(), and G4Visible::GetVisAttributes().
Referenced by G4HepRepFileSceneHandler::AddPrimitive().
G4bool G4VSceneHandler::GetTransientsDrawnThisEvent () const
Referenced by G4VisManager::ClearTransientStoreIfMarked().
G4bool G4VSceneHandler::GetTransientsDrawnThisRun () const
Referenced by G4VisManager::ClearTransientStoreIfMarked().
G4int G4VSceneHandler::GetViewCount () const
const G4ViewerList& G4VSceneHandler::GetViewerList () const
G4int G4VSceneHandler::IncrementViewCount ()
G4bool G4VSceneHandler::IsReadyForTransients () const
void G4VSceneHandler::LoadAtts (const G4Visible & visible, G4AttHolder * holder) protected
Definition at line 967 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 967 of file G4VSceneHandler.cc
References G4AttHolder::AddAtts(), G4VHit::CreateAttValues(), G4VTrajectoryPoint::CreateAttValues(), G4VTrajectory::CreateAttValues(), G4VisAttributes::CreateAttValues(), G4TrajectoriesModel::CreateCurrentAttValues(), G4PhysicalVolumeModel::CreateCurrentAttValues(), fpModel, G4VHit::GetAttDefs(), G4TrajectoriesModel::GetAttDefs(), G4VTrajectoryPoint::GetAttDefs(), G4VTrajectory::GetAttDefs(), G4VisAttributes::GetAttDefs(), G4PhysicalVolumeModel::GetAttDefs(), G4HitsModel::GetCurrentHit(), G4TrajectoriesModel::GetCurrentTrajectory(), G4VTrajectory::GetPoint(), G4VTrajectory::GetPointEntries(), and G4Visible::GetVisAttributes().
G4VSceneHandler& G4VSceneHandler::operator= (const G4VSceneHandler &) private
void G4VSceneHandler::PostAddSolid () virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, and G4VTreeSceneHandler.
Definition at line 153 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 153 of file G4VSceneHandler.cc
References fProcessingSolid, fpVisAttribs, fReadyForTransients, fTransientsDrawnThisEvent, and fTransientsDrawnThisRun.
Referenced by G4XXXStoredSceneHandler::PostAddSolid(), G4HepRepSceneHandler::PostAddSolid(), and G4XXXSGSceneHandler::PostAddSolid().
void G4VSceneHandler::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes & visAttribs) virtual
Implements G4VGraphicsScene.
Reimplemented in G4XXXSGSceneHandler, G4HepRepSceneHandler, G4XXXStoredSceneHandler, and G4VTreeSceneHandler.
Definition at line 146 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 146 of file G4VSceneHandler.cc
References fObjectTransformation, fProcessingSolid, and fpVisAttribs.
Referenced by G4VTreeSceneHandler::PreAddSolid(), G4XXXStoredSceneHandler::PreAddSolid(), G4HepRepSceneHandler::PreAddSolid(), and G4XXXSGSceneHandler::PreAddSolid().
void G4VSceneHandler::ProcessScene () protected virtual
Definition at line 660 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 660 of file G4VSceneHandler.cc
References BeginModeling(), G4VisManager::confirmations, CreateModelingParameters(), DrawEndOfRunModels(), DrawEvent(), EndModeling(), fMarkForClearingTransientStore, fpModel, fpScene, fReadyForTransients, G4cout, G4endl, G4Exception(), G4State_GeomClosed, G4State_Idle, G4VVisManager::GetConcreteInstance(), G4RunManager::GetCurrentRun(), G4StateManager::GetCurrentState(), G4Run::GetEventVector(), G4Scene::GetExtent(), G4VisManager::GetInstance(), G4MTRunManager::GetMasterRunManager(), G4VisExtent::GetNullExtent(), G4Scene::GetRefreshAtEndOfEvent(), G4Scene::GetRefreshAtEndOfRun(), G4VisManager::GetRequestedEvent(), G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), G4VisManager::GetVerbosity(), G4Threading::IsMultithreadedApplication(), JustWarning, G4VisManager::SetEventRefreshing(), and G4VisManager::warnings.
Referenced by G4VViewer::ProcessView().
void G4VSceneHandler::RemoveViewerFromList (G4VViewer * pView)
Definition at line 571 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 571 of file G4VSceneHandler.cc
References fViewerList, and G4ViewerList::remove().
Referenced by G4VViewer::~G4VViewer().
void G4VSceneHandler::RequestPrimitives (const G4VSolid & solid) protected virtual
Reimplemented in G4ASCIITreeSceneHandler, and G4RayTracerSceneHandler.
Definition at line 584 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 584 of file G4VSceneHandler.cc
References AddPrimitive(), BeginPrimitives(), G4ViewParameters::cloud, G4Polymarker::dots, EndPrimitives(), G4VisManager::errors, fObjectTransformation, fpModel, fpViewer, fpVisAttribs, G4cerr, G4endl, GetDrawingStyle(), G4PhysicalVolumeModel::GetFullPVPath(), G4VSolid::GetName(), GetNoOfSides(), G4ViewParameters::GetNumberOfCloudPoints(), GetNumberOfCloudPoints(), G4VSolid::GetPointOnSurface(), G4VSolid::GetPolyhedron(), G4VisManager::GetVerbosity(), G4VViewer::GetViewParameters(), G4ViewParameters::hlhsr, G4ViewParameters::hlr, G4ViewParameters::hsr, HepPolyhedron::ResetNumberOfRotationSteps(), G4VMarker::screen, G4Polymarker::SetMarkerType(), HepPolyhedron::SetNumberOfRotationSteps(), G4VMarker::SetSize(), G4Visible::SetVisAttributes(), and G4ViewParameters::wireframe.
void G4VSceneHandler::SetCurrentViewer (G4VViewer *)
void G4VSceneHandler::SetMarkForClearingTransientStore (G4bool)
Referenced by G4VisManager::ClearTransientStoreIfMarked(), G4VisManager::EndOfEvent(), G4VisManager::EndOfRun(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), and G4VisCommandViewerClearTransients::SetNewValue().
void G4VSceneHandler::SetModel (G4VModel *)
void G4VSceneHandler::SetName (const G4String &)
void G4VSceneHandler::SetObjectTransformation (const G4Transform3D &)
void G4VSceneHandler::SetScene (G4Scene * pScene) virtual
Definition at line 575 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 575 of file G4VSceneHandler.cc
References fpScene, and fViewerList.
void G4VSceneHandler::SetTransientsDrawnThisEvent (G4bool)
Referenced by G4VisManager::BeginOfEvent().
void G4VSceneHandler::SetTransientsDrawnThisRun (G4bool)
Referenced by G4VisManager::BeginOfRun().
G4ViewerList& G4VSceneHandler::SetViewerList ()
Friends And Related Function Documentation
friend class G4VViewer friend
Definition at line 63 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VSceneHandler.hh
std::ostream& operator<< (std::ostream & os, const G4VSceneHandler & s) friend
Definition at line 1157 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1157 of file G4VSceneHandler.cc
Member Data Documentation
const G4Transform3D G4VSceneHandler::fIdentityTransformation protected
Definition at line 363 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 363 of file G4VSceneHandler.hh
G4bool G4VSceneHandler::fMarkForClearingTransientStore protected
Definition at line 351 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 351 of file G4VSceneHandler.hh
Referenced by ProcessScene().
G4String G4VSceneHandler::fName protected
Definition at line 346 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 346 of file G4VSceneHandler.hh
Referenced by G4VSceneHandler(), and operator<<().
G4int G4VSceneHandler::fNestingDepth protected
Definition at line 361 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 361 of file G4VSceneHandler.hh
Referenced by EndPrimitives(), and EndPrimitives2D().
G4Transform3D G4VSceneHandler::fObjectTransformation protected
Definition at line 359 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 359 of file G4VSceneHandler.hh
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), PreAddSolid(), and RequestPrimitives().
G4VModel* G4VSceneHandler::fpModel protected
Definition at line 358 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 358 of file G4VSceneHandler.hh
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), AddCompound(), G4GMocrenFileSceneHandler::AddDetector(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddPrimitive(), AddPrimitive(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4RayTracerSceneHandler::BuildVisAttsMap(), G4XXXSGSceneHandler::CreateCurrentItem(), DrawEndOfRunModels(), DrawEvent(), EndModeling(), G4HepRepSceneHandler::getGeometryOrEventInstance(), G4HepRepSceneHandler::isEventData(), LoadAtts(), ProcessScene(), G4ASCIITreeSceneHandler::RequestPrimitives(), and RequestPrimitives().
G4bool G4VSceneHandler::fProcessing2D protected
Definition at line 357 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 357 of file G4VSceneHandler.hh
Referenced by G4GMocrenFileSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddPrimitive(), and EndPrimitives2D().
G4bool G4VSceneHandler::fProcessingSolid protected
Definition at line 356 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 356 of file G4VSceneHandler.hh
Referenced by G4XXXStoredSceneHandler::EndPrimitives(), PostAddSolid(), and PreAddSolid().
G4Scene* G4VSceneHandler::fpScene protected
Definition at line 350 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 350 of file G4VSceneHandler.hh
Referenced by AddPrimitive(), CreateSectionSolid(), DrawEndOfRunModels(), DrawEvent(), G4ASCIITreeSceneHandler::EndModeling(), G4RayTracerSceneHandler::G4RayTracerSceneHandler(), G4VSceneHandler(), GetExtent(), operator<<(), ProcessScene(), and SetScene().
G4VViewer* G4VSceneHandler::fpViewer protected
Definition at line 349 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 349 of file G4VSceneHandler.hh
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4XXXSceneHandler::AddPrimitive(), G4XXXFileSceneHandler::AddPrimitive(), G4XXXStoredSceneHandler::AddPrimitive(), G4XXXSGSceneHandler::AddPrimitive(), G4XXXFileSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::ClearTransientStore(), G4XXXStoredSceneHandler::ClearTransientStore(), G4HepRepFileSceneHandler::ClearTransientStore(), CreateModelingParameters(), CreateSectionSolid(), GetAuxEdgeVisible(), GetLineWidth(), GetNoOfSides(), G4GMocrenFileSceneHandler::IsVisible(), and RequestPrimitives().
const G4VisAttributes* G4VSceneHandler::fpVisAttribs protected
Definition at line 362 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 362 of file G4VSceneHandler.hh
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4RayTracerSceneHandler::BuildVisAttsMap(), G4HepRepSceneHandler::dontWrite(), G4HepRepSceneHandler::getColorFor(), G4GMocrenFileSceneHandler::IsVisible(), PostAddSolid(), PreAddSolid(), RequestPrimitives(), G4HepRepSceneHandler::setMarker(), and G4HepRepSceneHandler::setVisibility().
G4bool G4VSceneHandler::fReadyForTransients protected
Definition at line 352 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 352 of file G4VSceneHandler.hh
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), EndPrimitives(), EndPrimitives2D(), G4HepRepSceneHandler::isEventData(), PostAddSolid(), and ProcessScene().
const G4int G4VSceneHandler::fSceneHandlerId protected
Definition at line 345 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 345 of file G4VSceneHandler.hh
Referenced by G4VSceneHandler().
G4VGraphicsSystem& G4VSceneHandler::fSystem protected
Definition at line 344 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 344 of file G4VSceneHandler.hh
Referenced by G4VSceneHandler().
G4bool G4VSceneHandler::fTransientsDrawnThisEvent protected
Definition at line 354 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 354 of file G4VSceneHandler.hh
Referenced by EndPrimitives(), EndPrimitives2D(), G4VSceneHandler(), and PostAddSolid().
G4bool G4VSceneHandler::fTransientsDrawnThisRun protected
Definition at line 355 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 355 of file G4VSceneHandler.hh
Referenced by EndPrimitives(), EndPrimitives2D(), G4VSceneHandler(), and PostAddSolid().
G4int G4VSceneHandler::fViewCount protected
Definition at line 347 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 347 of file G4VSceneHandler.hh
G4ViewerList G4VSceneHandler::fViewerList protected
Definition at line 348 of file G4VSceneHandler.hh.
View newest version in sPHENIX GitHub at line 348 of file G4VSceneHandler.hh
Referenced by AddViewerToList(), operator<<(), RemoveViewerFromList(), SetScene(), and ~G4VSceneHandler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VSceneHandler.cc