ECCE @ EIC Software: RE03DetectorConstruction Class Reference
RE03DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE03/include/RE03DetectorConstruction.hh>
Public Member Functions
RE03DetectorConstruction ()
virtual ~RE03DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void SetupGeometry ()
Private Attributes
G4Material * fAir
G4Material * fWater
G4VPhysicalVolume * fWorldPhys
G4VPhysicalVolume * fPhantomPhys
G4bool fConstructed
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 40 of file RE03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 40 of file RE03DetectorConstruction.hh
Constructor & Destructor Documentation
RE03DetectorConstruction::RE03DetectorConstruction ()
Definition at line 54 of file RE03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 54 of file RE03DetectorConstruction.cc
RE03DetectorConstruction::~RE03DetectorConstruction () virtual
Definition at line 61 of file RE03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 61 of file RE03DetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * RE03DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 65 of file RE03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 65 of file RE03DetectorConstruction.cc
References DefineMaterials(), fConstructed, fWorldPhys, and SetupGeometry().
void RE03DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 113 of file RE03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 113 of file RE03DetectorConstruction.cc
void RE03DetectorConstruction::DefineMaterials (void) private
Definition at line 77 of file RE03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 77 of file RE03DetectorConstruction.cc
References fAir, G4NistManager::FindOrBuildMaterial(), fWater, and G4NistManager::Instance().
Referenced by Construct().
void RE03DetectorConstruction::SetupGeometry () private
Definition at line 87 of file RE03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 87 of file RE03DetectorConstruction.cc
References fAir, fPhantomPhys, fWater, fWorldPhys, m, G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
Referenced by Construct().
Member Data Documentation
G4Material* RE03DetectorConstruction::fAir private
Definition at line 55 of file RE03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file RE03DetectorConstruction.hh
Referenced by DefineMaterials(), and SetupGeometry().
G4bool RE03DetectorConstruction::fConstructed private
Definition at line 59 of file RE03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 59 of file RE03DetectorConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* RE03DetectorConstruction::fPhantomPhys private
Definition at line 58 of file RE03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 58 of file RE03DetectorConstruction.hh
Referenced by SetupGeometry().
G4Material* RE03DetectorConstruction::fWater private
Definition at line 56 of file RE03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 56 of file RE03DetectorConstruction.hh
Referenced by DefineMaterials(), and SetupGeometry().
G4VPhysicalVolume* RE03DetectorConstruction::fWorldPhys private
Definition at line 57 of file RE03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 57 of file RE03DetectorConstruction.hh
Referenced by Construct(), and SetupGeometry().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE03/include/RE03DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE03/src/RE03DetectorConstruction.cc