ECCE @ EIC Software: G4tgbMaterial Class Reference
G4tgbMaterial Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterial.hh>
Public Member Functions
G4tgbMaterial ()
virtual ~G4tgbMaterial ()
G4tgbMaterial (G4tgrMaterial *tgr)
virtual G4Material * BuildG4Material ()=0
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfMaterials () const
G4double GetA () const
G4double GetZ () const
const G4String & GetType () const
G4tgrMaterial * GetTgrMate () const
Protected Attributes
G4tgrMaterial * theTgrMate
G4Material * theG4Mate
Friends
std::ostream & operator<< (std::ostream &, const G4tgbMaterial &)
Detailed Description
Definition at line 51 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 51 of file G4tgbMaterial.hh
Constructor & Destructor Documentation
G4tgbMaterial::G4tgbMaterial ()
Definition at line 40 of file G4tgbMaterial.cc.
View newest version in sPHENIX GitHub at line 40 of file G4tgbMaterial.cc
G4tgbMaterial::~G4tgbMaterial () virtual
Definition at line 46 of file G4tgbMaterial.cc.
View newest version in sPHENIX GitHub at line 46 of file G4tgbMaterial.cc
G4tgbMaterial::G4tgbMaterial (G4tgrMaterial * tgr)
Definition at line 51 of file G4tgbMaterial.cc.
View newest version in sPHENIX GitHub at line 51 of file G4tgbMaterial.cc
Member Function Documentation
virtual G4Material* G4tgbMaterial::BuildG4Material () pure virtual
Implemented in G4tgbMaterialSimple, G4tgbMaterialMixtureByNoAtoms, G4tgbMaterialMixtureByVolume, and G4tgbMaterialMixtureByWeight.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Material().
G4double G4tgbMaterial::GetA () const inline
Definition at line 79 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 79 of file G4tgbMaterial.hh
References G4tgrMaterial::GetA(), and theTgrMate.
G4double G4tgbMaterial::GetDensity () const inline
Definition at line 69 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgbMaterial.hh
References G4tgrMaterial::GetDensity(), and theTgrMate.
Referenced by operator<<().
const G4String& G4tgbMaterial::GetName (void) const inline
Definition at line 64 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 64 of file G4tgbMaterial.hh
References G4tgrMaterial::GetName(), and theTgrMate.
Referenced by G4tgbMaterialSimple::BuildG4Material(), G4tgbMaterialMgr::CopyMaterials(), and operator<<().
G4int G4tgbMaterial::GetNumberOfMaterials () const inline
Definition at line 74 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 74 of file G4tgbMaterial.hh
References G4tgrMaterial::GetNumberOfComponents(), and theTgrMate.
G4tgrMaterial* G4tgbMaterial::GetTgrMate () const inline
Definition at line 95 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 95 of file G4tgbMaterial.hh
References theTgrMate.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Material().
const G4String& G4tgbMaterial::GetType () const inline
Definition at line 89 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 89 of file G4tgbMaterial.hh
References G4tgrMaterial::GetType(), and theTgrMate.
G4double G4tgbMaterial::GetZ () const inline
Definition at line 84 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 84 of file G4tgbMaterial.hh
References G4tgrMaterial::GetZ(), and theTgrMate.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const G4tgbMaterial &) friend
Member Data Documentation
G4Material* G4tgbMaterial::theG4Mate protected
Definition at line 103 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 103 of file G4tgbMaterial.hh
G4tgrMaterial* G4tgbMaterial::theTgrMate protected
Definition at line 102 of file G4tgbMaterial.hh.
View newest version in sPHENIX GitHub at line 102 of file G4tgbMaterial.hh
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgbMaterialSimple::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::G4tgbMaterialMixtureByNoAtoms(), G4tgbMaterialMixtureByVolume::G4tgbMaterialMixtureByVolume(), G4tgbMaterialMixtureByWeight::G4tgbMaterialMixtureByWeight(), G4tgbMaterialSimple::G4tgbMaterialSimple(), GetA(), G4tgbMaterialMixture::GetComponent(), GetDensity(), G4tgbMaterialMixture::GetFraction(), GetName(), GetNumberOfMaterials(), GetTgrMate(), GetType(), GetZ(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterial.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterial.cc