ECCE @ EIC Software: G4CrossSectionDataSetRegistry Class Reference
G4CrossSectionDataSetRegistry Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionDataSetRegistry.hh>
Public Member Functions
~G4CrossSectionDataSetRegistry ()
void Register (G4VCrossSectionDataSet *)
void DeRegister (G4VCrossSectionDataSet *)
void Register (G4VComponentCrossSection *)
void DeRegister (G4VComponentCrossSection *)
void DeleteComponent (G4VComponentCrossSection *)
void Clean ()
G4VCrossSectionDataSet * GetCrossSectionDataSet (const G4String &name, G4bool warning=true)
G4VComponentCrossSection * GetComponentCrossSection (const G4String &name)
Static Public Member Functions
static
G4CrossSectionDataSetRegistry * Instance ()
Private Member Functions
G4CrossSectionDataSetRegistry ()
Private Attributes
std::vector
< G4VCrossSectionDataSet * > xSections
std::vector
< G4VComponentCrossSection * > xComponents
Static Private Attributes
static G4ThreadLocal
G4CrossSectionDataSetRegistry * instance = nullptr
Friends
class G4ThreadLocalSingleton< G4CrossSectionDataSetRegistry >
Detailed Description
Definition at line 55 of file G4CrossSectionDataSetRegistry.hh.
View newest version in sPHENIX GitHub at line 55 of file G4CrossSectionDataSetRegistry.hh
Constructor & Destructor Documentation
G4CrossSectionDataSetRegistry::~G4CrossSectionDataSetRegistry ()
Definition at line 89 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 89 of file G4CrossSectionDataSetRegistry.cc
References Clean().
G4CrossSectionDataSetRegistry::G4CrossSectionDataSetRegistry () private
Definition at line 86 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 86 of file G4CrossSectionDataSetRegistry.cc
Member Function Documentation
void G4CrossSectionDataSetRegistry::Clean ()
Definition at line 94 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 94 of file G4CrossSectionDataSetRegistry.cc
References n, xComponents, and xSections.
Referenced by ~G4CrossSectionDataSetRegistry().
void G4CrossSectionDataSetRegistry::DeleteComponent (G4VComponentCrossSection * p)
Definition at line 169 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 169 of file G4CrossSectionDataSetRegistry.cc
References n, and xComponents.
void G4CrossSectionDataSetRegistry::DeRegister (G4VCrossSectionDataSet * p)
Definition at line 129 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 129 of file G4CrossSectionDataSetRegistry.cc
References n, and xSections.
Referenced by G4VComponentCrossSection::~G4VComponentCrossSection(), and G4VCrossSectionDataSet::~G4VCrossSectionDataSet().
void G4CrossSectionDataSetRegistry::DeRegister (G4VComponentCrossSection * p)
Definition at line 154 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 154 of file G4CrossSectionDataSetRegistry.cc
References n, and xComponents.
G4VComponentCrossSection * G4CrossSectionDataSetRegistry::GetComponentCrossSection (const G4String & name)
Definition at line 206 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 206 of file G4CrossSectionDataSetRegistry.cc
References xComponents.
Referenced by G4AntiNuclElastic::G4AntiNuclElastic(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFParameters::G4FTFParameters(), and G4VHadronPhysics::InelasticXS().
G4VCrossSectionDataSet * G4CrossSectionDataSetRegistry::GetCrossSectionDataSet (const G4String & name, G4bool warning = true)
Definition at line 184 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 184 of file G4CrossSectionDataSetRegistry.cc
References G4CrossSectionFactoryRegistry::GetFactory(), G4CrossSectionFactoryRegistry::Instance(), G4VBaseXSFactory::Instantiate(), and xSections.
Referenced by G4NeutronCrossSectionXS::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4ChipsComponentXS::G4ChipsComponentXS(), G4ChipsElasticModel::G4ChipsElasticModel(), G4ChipsKaonZeroElasticXS::G4ChipsKaonZeroElasticXS(), G4ChipsKaonZeroInelasticXS::G4ChipsKaonZeroInelasticXS(), G4QMDReaction::G4QMDReaction(), and G4QuasiElRatios::G4QuasiElRatios().
G4CrossSectionDataSetRegistry * G4CrossSectionDataSetRegistry::Instance (void) static
Definition at line 77 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 77 of file G4CrossSectionDataSetRegistry.cc
References instance, and G4ThreadLocalSingleton< T >::Instance().
Referenced by G4INCLXXNeutronBuilder::Build(), LBE::ConstructHad(), G4NeutronCrossSectionXS::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4AntiNuclElastic::G4AntiNuclElastic(), G4ChipsComponentXS::G4ChipsComponentXS(), G4ChipsElasticModel::G4ChipsElasticModel(), G4ChipsKaonZeroElasticXS::G4ChipsKaonZeroElasticXS(), G4ChipsKaonZeroInelasticXS::G4ChipsKaonZeroInelasticXS(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFParameters::G4FTFParameters(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4QMDReaction::G4QMDReaction(), G4QuasiElRatios::G4QuasiElRatios(), G4VComponentCrossSection::G4VComponentCrossSection(), G4VCrossSectionDataSet::G4VCrossSectionDataSet(), and G4VHadronPhysics::InelasticXS().
void G4CrossSectionDataSetRegistry::Register (G4VCrossSectionDataSet * p)
Definition at line 118 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 118 of file G4CrossSectionDataSetRegistry.cc
References xSections.
Referenced by G4VComponentCrossSection::G4VComponentCrossSection(), and G4VCrossSectionDataSet::G4VCrossSectionDataSet().
void G4CrossSectionDataSetRegistry::Register (G4VComponentCrossSection * p)
Definition at line 143 of file G4CrossSectionDataSetRegistry.cc.
View newest version in sPHENIX GitHub at line 143 of file G4CrossSectionDataSetRegistry.cc
References xComponents.
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4CrossSectionDataSetRegistry > friend
Definition at line 57 of file G4CrossSectionDataSetRegistry.hh.
View newest version in sPHENIX GitHub at line 57 of file G4CrossSectionDataSetRegistry.hh
Member Data Documentation
G4ThreadLocal G4CrossSectionDataSetRegistry * G4CrossSectionDataSetRegistry::instance = nullptr static private
Definition at line 93 of file G4CrossSectionDataSetRegistry.hh.
View newest version in sPHENIX GitHub at line 93 of file G4CrossSectionDataSetRegistry.hh
Referenced by Instance().
std::vector<G4VComponentCrossSection*> G4CrossSectionDataSetRegistry::xComponents private
Definition at line 96 of file G4CrossSectionDataSetRegistry.hh.
View newest version in sPHENIX GitHub at line 96 of file G4CrossSectionDataSetRegistry.hh
Referenced by Clean(), DeleteComponent(), DeRegister(), GetComponentCrossSection(), and Register().
std::vector<G4VCrossSectionDataSet*> G4CrossSectionDataSetRegistry::xSections private
Definition at line 95 of file G4CrossSectionDataSetRegistry.hh.
View newest version in sPHENIX GitHub at line 95 of file G4CrossSectionDataSetRegistry.hh
Referenced by Clean(), DeRegister(), GetCrossSectionDataSet(), and Register().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionDataSetRegistry.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4CrossSectionDataSetRegistry.cc