ECCE @ EIC Software: G4ShellEMDataSet Class Reference
G4ShellEMDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ShellEMDataSet.hh>
Public Member Functions
G4ShellEMDataSet (G4int Z, G4VDataSetAlgorithm *algo, G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4ShellEMDataSet ()
virtual G4double FindValue (G4double energy, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *energies, G4DataVector *data, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *energies, G4DataVector *data, G4DataVector *log_energies, G4DataVector *log_data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool LoadNonLogData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Protected Member Functions
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4VDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Member Functions
G4String FullFileName (const G4String &fileName) const
G4ShellEMDataSet ()
G4ShellEMDataSet (const G4ShellEMDataSet &copy)
G4ShellEMDataSet & operator= (const G4ShellEMDataSet &right)
Private Attributes
std::vector< G4VEMDataSet * > components
G4int z
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 59 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ShellEMDataSet.hh
Constructor & Destructor Documentation
G4ShellEMDataSet::G4ShellEMDataSet (G4int Z, G4VDataSetAlgorithm * algo, G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 63 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ShellEMDataSet.cc
References algorithm, FatalErrorInArgument, and G4Exception().
G4ShellEMDataSet::~G4ShellEMDataSet () virtual
Definition at line 76 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ShellEMDataSet.cc
References algorithm, and CleanUpComponents().
G4ShellEMDataSet::G4ShellEMDataSet () private
G4ShellEMDataSet::G4ShellEMDataSet (const G4ShellEMDataSet & copy) private
Member Function Documentation
virtual void G4ShellEMDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 74 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ShellEMDataSet.hh
References components.
Referenced by LoadData(), and LoadNonLogData().
void G4ShellEMDataSet::CleanUpComponents (void) protected
Definition at line 388 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 388 of file G4ShellEMDataSet.cc
References components.
Referenced by LoadData(), LoadNonLogData(), and ~G4ShellEMDataSet().
G4double G4ShellEMDataSet::FindValue (G4double energy, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ShellEMDataSet.cc
References components.
G4String G4ShellEMDataSet::FullFileName (const G4String & fileName) const private
Definition at line 398 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 398 of file G4ShellEMDataSet.cc
References G4Exception(), JustWarning, and z.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
const G4VDataSetAlgorithm* G4ShellEMDataSet::GetAlgorithm () const inline protected
Definition at line 100 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ShellEMDataSet.hh
References algorithm.
virtual const G4VEMDataSet* G4ShellEMDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 73 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ShellEMDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), PrintData(), and SaveData().
virtual const G4DataVector& G4ShellEMDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 78 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ShellEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetData().
virtual const G4DataVector& G4ShellEMDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 77 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ShellEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetEnergies().
virtual const G4DataVector& G4ShellEMDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 80 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ShellEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogData().
virtual const G4DataVector& G4ShellEMDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 79 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ShellEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogEnergies().
G4double G4ShellEMDataSet::GetUnitData () const inline protected
Definition at line 99 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ShellEMDataSet.hh
References unitData.
G4double G4ShellEMDataSet::GetUnitEnergies () const inline protected
Definition at line 98 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ShellEMDataSet.hh
References unitEnergies.
G4bool G4ShellEMDataSet::LoadData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 159 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 159 of file G4ShellEMDataSet.cc
References a, AddComponent(), algorithm, CleanUpComponents(), G4VDataSetAlgorithm::Clone(), e, FatalException, FullFileName(), G4Exception(), in, k, message(), unitData, and unitEnergies.
G4bool G4ShellEMDataSet::LoadNonLogData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 243 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 243 of file G4ShellEMDataSet.cc
References a, AddComponent(), algorithm, CleanUpComponents(), G4VDataSetAlgorithm::Clone(), FatalException, FullFileName(), G4Exception(), in, k, message(), unitData, and unitEnergies.
virtual size_t G4ShellEMDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 75 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ShellEMDataSet.hh
References components.
Referenced by PrintData(), and SaveData().
G4ShellEMDataSet& G4ShellEMDataSet::operator= (const G4ShellEMDataSet & right) private
void G4ShellEMDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 101 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ShellEMDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4VEMDataSet::PrintData().
virtual G4double G4ShellEMDataSet::RandomSelect (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 94 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ShellEMDataSet.hh
G4bool G4ShellEMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4VEMDataSet.
Definition at line 316 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 316 of file G4ShellEMDataSet.cc
References FatalException, FullFileName(), G4Exception(), GetComponent(), G4VEMDataSet::GetData(), G4VEMDataSet::GetEnergies(), k, left, message(), n, NumberOfComponents(), unitData, and unitEnergies.
void G4ShellEMDataSet::SetEnergiesData (G4DataVector * energies, G4DataVector * data, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 119 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 119 of file G4ShellEMDataSet.cc
References components, FatalErrorInArgument, G4Exception(), and G4VEMDataSet::SetEnergiesData().
void G4ShellEMDataSet::SetLogEnergiesData (G4DataVector * energies, G4DataVector * data, G4DataVector * log_energies, G4DataVector * log_data, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 137 of file G4ShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 137 of file G4ShellEMDataSet.cc
References components, FatalErrorInArgument, G4Exception(), and G4VEMDataSet::SetLogEnergiesData().
Member Data Documentation
G4VDataSetAlgorithm* G4ShellEMDataSet::algorithm private
Definition at line 117 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ShellEMDataSet.hh
Referenced by G4ShellEMDataSet(), GetAlgorithm(), LoadData(), LoadNonLogData(), and ~G4ShellEMDataSet().
std::vector<G4VEMDataSet*> G4ShellEMDataSet::components private
Definition at line 113 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ShellEMDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), SetEnergiesData(), and SetLogEnergiesData().
G4double G4ShellEMDataSet::unitData private
Definition at line 120 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ShellEMDataSet.hh
Referenced by GetUnitData(), LoadData(), LoadNonLogData(), and SaveData().
G4double G4ShellEMDataSet::unitEnergies private
Definition at line 119 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ShellEMDataSet.hh
Referenced by GetUnitEnergies(), LoadData(), LoadNonLogData(), and SaveData().
G4int G4ShellEMDataSet::z private
Definition at line 115 of file G4ShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ShellEMDataSet.hh
Referenced by FullFileName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ShellEMDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4ShellEMDataSet.cc