ECCE @ EIC Software: G4RDDopplerProfile Class Reference
G4RDDopplerProfile Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDDopplerProfile.hh>
Public Member Functions
G4RDDopplerProfile (G4int minZ=1, G4int maxZ=100)
~G4RDDopplerProfile ()
size_t NumberOfProfiles (G4int Z) const
const G4RDVEMDataSet * Profiles (G4int Z) const
const G4RDVEMDataSet * Profile (G4int Z, G4int ShellIndex) const
void PrintData () const
G4double RandomSelectMomentum (G4int Z, G4int shellIndex) const
Private Member Functions
G4RDDopplerProfile & operator= (const G4RDDopplerProfile &right)
G4RDDopplerProfile (const G4RDDopplerProfile &)
void LoadBiggsP (const G4String &fileName)
void LoadProfile (const G4String &fileName, G4int Z)
Private Attributes
std::map< G4int,
G4RDVEMDataSet *, std::less
< G4int > > profileMap
std::vector< G4int > nShells
G4int zMin
G4int zMax
size_t nBiggs
std::vector< G4double > biggsP
Detailed Description
Definition at line 51 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RDDopplerProfile.hh
Constructor & Destructor Documentation
G4RDDopplerProfile::G4RDDopplerProfile (G4int minZ = 1, G4int maxZ = 100)
Definition at line 54 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 54 of file G4RDDopplerProfile.cc
References LoadBiggsP(), LoadProfile(), nBiggs, Z, zMax, and zMin.
G4RDDopplerProfile::~G4RDDopplerProfile ()
Definition at line 68 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 68 of file G4RDDopplerProfile.cc
References pos(), and profileMap.
G4RDDopplerProfile::G4RDDopplerProfile (const G4RDDopplerProfile &) private
Member Function Documentation
void G4RDDopplerProfile::LoadBiggsP (const G4String & fileName) private
Definition at line 118 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 118 of file G4RDDopplerProfile.cc
References biggsP, FatalException, file, G4Exception(), nBiggs, and s1.
Referenced by G4RDDopplerProfile().
void G4RDDopplerProfile::LoadProfile (const G4String & fileName, G4int Z) private
Definition at line 160 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 160 of file G4RDDopplerProfile.cc
References G4RDVEMDataSet::AddComponent(), biggsP, G4RDVDataSetAlgorithm::Clone(), FatalException, file, G4Exception(), nBiggs, nShells, profileMap, s1, and Z.
Referenced by G4RDDopplerProfile().
size_t G4RDDopplerProfile::NumberOfProfiles (G4int Z) const
Definition at line 80 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 80 of file G4RDDopplerProfile.cc
References n, nShells, zMax, and zMin.
G4RDDopplerProfile& G4RDDopplerProfile::operator= (const G4RDDopplerProfile & right) private
void G4RDDopplerProfile::PrintData (void) const
Definition at line 108 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 108 of file G4RDDopplerProfile.cc
References G4RDVEMDataSet::PrintData(), Profiles(), Z, zMax, and zMin.
const G4RDVEMDataSet * G4RDDopplerProfile::Profile (G4int Z, G4int ShellIndex) const
Definition at line 100 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 100 of file G4RDDopplerProfile.cc
References G4RDVEMDataSet::GetComponent(), and Profiles().
const G4RDVEMDataSet * G4RDDopplerProfile::Profiles (G4int Z) const
Definition at line 88 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 88 of file G4RDDopplerProfile.cc
References FatalException, G4Exception(), pos(), profileMap, and zMax.
Referenced by PrintData(), Profile(), and RandomSelectMomentum().
G4double G4RDDopplerProfile::RandomSelectMomentum (G4int Z, G4int shellIndex) const
Definition at line 225 of file G4RDDopplerProfile.cc.
View newest version in sPHENIX GitHub at line 225 of file G4RDDopplerProfile.cc
References Profiles(), and G4RDVEMDataSet::RandomSelect().
Referenced by G4LowEnergyCompton::PostStepDoIt(), and G4LowEnergyPolarizedCompton::PostStepDoIt().
Member Data Documentation
std::vector<G4double> G4RDDopplerProfile::biggsP private
Definition at line 83 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RDDopplerProfile.hh
Referenced by LoadBiggsP(), and LoadProfile().
size_t G4RDDopplerProfile::nBiggs private
Definition at line 81 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RDDopplerProfile.hh
Referenced by G4RDDopplerProfile(), LoadBiggsP(), and LoadProfile().
std::vector<G4int> G4RDDopplerProfile::nShells private
Definition at line 76 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RDDopplerProfile.hh
Referenced by LoadProfile(), and NumberOfProfiles().
std::map<G4int,G4RDVEMDataSet*,std::less<G4int> > G4RDDopplerProfile::profileMap private
Definition at line 75 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RDDopplerProfile.hh
Referenced by LoadProfile(), Profiles(), and ~G4RDDopplerProfile().
G4int G4RDDopplerProfile::zMax private
Definition at line 79 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RDDopplerProfile.hh
Referenced by G4RDDopplerProfile(), NumberOfProfiles(), PrintData(), and Profiles().
G4int G4RDDopplerProfile::zMin private
Definition at line 78 of file G4RDDopplerProfile.hh.
View newest version in sPHENIX GitHub at line 78 of file G4RDDopplerProfile.hh
Referenced by G4RDDopplerProfile(), NumberOfProfiles(), and PrintData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDDopplerProfile.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDDopplerProfile.cc