ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcAngularRange.hh File Reference
CexmcAngularRange.hh File Reference
#include <vector>
#include <iosfwd>
#include <G4Types.hh>
Classes
struct CexmcAngularRange
Typedefs
typedef std::vector
< CexmcAngularRange > CexmcAngularRangeList
Functions
G4bool operator< (const CexmcAngularRange &left, const CexmcAngularRange &right)
void GetNormalizedAngularRange (const CexmcAngularRangeList &src, CexmcAngularRangeList &dst)
void GetAngularGaps (const CexmcAngularRangeList &src, CexmcAngularRangeList &dst)
std::ostream & operator<< (std::ostream &out, const CexmcAngularRange &angularRange)
std::ostream & operator<< (std::ostream &out, const CexmcAngularRangeList &angularRanges)
Typedef Documentation
typedef std::vector< CexmcAngularRange > CexmcAngularRangeList
Definition at line 72 of file CexmcAngularRange.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcAngularRange.hh
Function Documentation
void GetAngularGaps (const CexmcAngularRangeList & src, CexmcAngularRangeList & dst)
Definition at line 82 of file CexmcAngularRange.cc.
View newest version in sPHENIX GitHub at line 82 of file CexmcAngularRange.cc
References GetNormalizedAngularRange(), and k.
Referenced by CexmcEventAction::EndOfEventAction(), and CexmcRunAction::PrintResults().
void GetNormalizedAngularRange (const CexmcAngularRangeList & src, CexmcAngularRangeList & dst)
Definition at line 51 of file CexmcAngularRange.cc.
View newest version in sPHENIX GitHub at line 51 of file CexmcAngularRange.cc
References E, epsilon(), and k.
Referenced by GetAngularGaps(), and CexmcProductionModel::IsGoodCandidateForAngularRange().
G4bool operator< (const CexmcAngularRange & left, const CexmcAngularRange & right) inline
Definition at line 85 of file CexmcAngularRange.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcAngularRange.hh
References CexmcAngularRange::bottom, and CexmcAngularRange::top.
std::ostream& operator<< (std::ostream & out, const CexmcAngularRange & angularRange)
Definition at line 115 of file CexmcAngularRange.cc.
View newest version in sPHENIX GitHub at line 115 of file CexmcAngularRange.cc
References CexmcAngularRange::bottom, CexmcAngularRange::index, CLHEP::prec, and CexmcAngularRange::top.
std::ostream& operator<< (std::ostream & out, const CexmcAngularRangeList & angularRanges)
Definition at line 135 of file CexmcAngularRange.cc.
View newest version in sPHENIX GitHub at line 135 of file CexmcAngularRange.cc