ECCE @ EIC Software: G4VTrackTerminator Class Reference
G4VTrackTerminator Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4VTrackTerminator.hh>
Public Member Functions
G4VTrackTerminator ()
virtual ~G4VTrackTerminator ()
virtual void KillTrack () const =0
virtual const G4String & GetName () const =0
Protected Attributes
G4double kCarTolerance
Detailed Description
Definition at line 52 of file G4VTrackTerminator.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VTrackTerminator.hh
Constructor & Destructor Documentation
G4VTrackTerminator::G4VTrackTerminator ()
Definition at line 38 of file G4VTrackTerminator.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VTrackTerminator.cc
References G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), and kCarTolerance.
G4VTrackTerminator::~G4VTrackTerminator () virtual
Definition at line 43 of file G4VTrackTerminator.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VTrackTerminator.cc
Member Function Documentation
virtual const G4String& G4VTrackTerminator::GetName () const pure virtual
Implemented in G4WeightWindowProcess, and G4ImportanceProcess.
virtual void G4VTrackTerminator::KillTrack () const pure virtual
Implemented in G4WeightWindowProcess, and G4ImportanceProcess.
Referenced by G4SamplingPostStepAction::DoIt().
Member Data Documentation
G4double G4VTrackTerminator::kCarTolerance protected
Definition at line 64 of file G4VTrackTerminator.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VTrackTerminator.hh
Referenced by G4VTrackTerminator(), G4ImportanceProcess::PostStepDoIt(), and G4WeightWindowProcess::PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4VTrackTerminator.hh
geant4/tree/geant4-10.6-release/source/processes/transportation/src/G4VTrackTerminator.cc