ECCE @ EIC Software: G4CollectionNameVector Class Reference
G4CollectionNameVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4CollectionNameVector.hh>
Public Member Functions
G4CollectionNameVector ()
virtual ~G4CollectionNameVector ()
void insert (G4String str)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 35 of file G4CollectionNameVector.hh.
View newest version in sPHENIX GitHub at line 35 of file G4CollectionNameVector.hh
Constructor & Destructor Documentation
G4CollectionNameVector::G4CollectionNameVector () inline
Definition at line 38 of file G4CollectionNameVector.hh.
View newest version in sPHENIX GitHub at line 38 of file G4CollectionNameVector.hh
virtual G4CollectionNameVector::~G4CollectionNameVector () inline virtual
Definition at line 39 of file G4CollectionNameVector.hh.
View newest version in sPHENIX GitHub at line 39 of file G4CollectionNameVector.hh
Member Function Documentation
void G4CollectionNameVector::insert (G4String str) inline
Definition at line 41 of file G4CollectionNameVector.hh.
View newest version in sPHENIX GitHub at line 41 of file G4CollectionNameVector.hh
Referenced by B2TrackerSD::B2TrackerSD(), B4cCalorimeterSD::B4cCalorimeterSD(), B5DriftChamberSD::B5DriftChamberSD(), B5EmCalorimeterSD::B5EmCalorimeterSD(), B5HadCalorimeterSD::B5HadCalorimeterSD(), B5HodoscopeSD::B5HodoscopeSD(), CCaloSD::CCaloSD(), DMXPmtSD::DMXPmtSD(), DMXScintSD::DMXScintSD(), eRositaTrackerSD::eRositaTrackerSD(), ExGflash1SensitiveDetector::ExGflash1SensitiveDetector(), ExGflash2SensitiveDetector::ExGflash2SensitiveDetector(), ExGflash3SensitiveDetector::ExGflash3SensitiveDetector(), ExGflashSensitiveDetector::ExGflashSensitiveDetector(), ExN02TrackerSD::ExN02TrackerSD(), ExN04CalorimeterSD::ExN04CalorimeterSD(), ExN04MuonSD::ExN04MuonSD(), ExN04TrackerSD::ExN04TrackerSD(), ExP01TrackerSD::ExP01TrackerSD(), ExTGTrackerSD::ExTGTrackerSD(), F01CalorimeterSD::F01CalorimeterSD(), F02CalorimeterSD::F02CalorimeterSD(), F03CalorimeterSD::F03CalorimeterSD(), G4HumanPhantomSD::G4HumanPhantomSD(), GammaRayTelAnticoincidenceSD::GammaRayTelAnticoincidenceSD(), GammaRayTelCalorimeterSD::GammaRayTelCalorimeterSD(), GammaRayTelTrackerSD::GammaRayTelTrackerSD(), H02MuonSD::H02MuonSD(), HadrontherapyDetectorSD::HadrontherapyDetectorSD(), LXePMTSD::LXePMTSD(), LXeScintSD::LXeScintSD(), Par01CalorimeterSD::Par01CalorimeterSD(), RE01CalorimeterSD::RE01CalorimeterSD(), RE01TrackerSD::RE01TrackerSD(), RE05CalorimeterSD::RE05CalorimeterSD(), RE05MuonSD::RE05MuonSD(), RE05TrackerSD::RE05TrackerSD(), G4MultiFunctionalDetector::RegisterPrimitive(), RMC01SD::RMC01SD(), SensitiveDetector::SensitiveDetector(), TrackerSD::TrackerSD(), UltraPMTSD::UltraPMTSD(), WLSPhotonDetSD::WLSPhotonDetSD(), XAluminumElectrodeSensitivity::XAluminumElectrodeSensitivity(), XrayFluoHPGeSD::XrayFluoHPGeSD(), and XrayFluoSD::XrayFluoSD().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4CollectionNameVector.hh