ECCE @ EIC Software: G4XmlAnalysisReader Class Reference
G4XmlAnalysisReader Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/xml/include/G4XmlAnalysisReader.hh>
Public Member Functions
G4XmlAnalysisReader (G4bool isMaster=true)
virtual ~G4XmlAnalysisReader ()
tools::aida::ntuple * GetNtuple () const
tools::aida::ntuple * GetNtuple (G4int ntupleId) const
Public Member Functions inherited from G4ToolsAnalysisReader
G4ToolsAnalysisReader (const G4String &type, G4bool isMaster=true)
virtual ~G4ToolsAnalysisReader ()
tools::histo::h1d * GetH1 (G4int id, G4bool warn=true) const
tools::histo::h2d * GetH2 (G4int id, G4bool warn=true) const
tools::histo::h3d * GetH3 (G4int id, G4bool warn=true) const
tools::histo::p1d * GetP1 (G4int id, G4bool warn=true) const
tools::histo::p2d * GetP2 (G4int id, G4bool warn=true) const
Public Member Functions inherited from G4VAnalysisReader
G4VAnalysisReader (const G4String &type, G4bool isMaster)
virtual ~G4VAnalysisReader ()
void SetFileName (const G4String &fileName)
G4String GetFileName () const
G4int ReadH1 (const G4String &h1Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadH2 (const G4String &h2Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadH3 (const G4String &h3Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadP1 (const G4String &h1Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadP2 (const G4String &h2Name, const G4String &fileName="", const G4String &dirName="")
G4bool SetFirstHistoId (G4int firstId)
G4bool SetFirstH1Id (G4int firstId)
G4bool SetFirstH2Id (G4int firstId)
G4bool SetFirstH3Id (G4int firstId)
G4bool SetFirstProfileId (G4int firstId)
G4bool SetFirstP1Id (G4int firstId)
G4bool SetFirstP2Id (G4int firstId)
G4bool SetFirstNtupleId (G4int firstId)
G4int GetNtuple (const G4String &ntupleName, const G4String &fileName="", const G4String &dirName="")
G4bool SetNtupleIColumn (const G4String &columnName, G4int &value)
G4bool SetNtupleFColumn (const G4String &columnName, G4float &value)
G4bool SetNtupleDColumn (const G4String &columnName, G4double &value)
G4bool SetNtupleSColumn (const G4String &columnName, G4String &value)
G4bool SetNtupleIColumn (const G4String &columnName, std::vector< int > &vector)
G4bool SetNtupleFColumn (const G4String &columnName, std::vector< float > &vector)
G4bool SetNtupleDColumn (const G4String &columnName, std::vector< double > &vector)
G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, G4int &value)
G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, G4float &value)
G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, G4double &value)
G4bool SetNtupleSColumn (G4int ntupleId, const G4String &columnName, G4String &value)
G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, std::vector< int > &vector)
G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, std::vector< float > &vector)
G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, std::vector< double > &vector)
G4bool GetNtupleRow ()
G4bool GetNtupleRow (G4int ntupleId)
G4bool IsAscii () const
G4int GetNofH1s () const
G4int GetNofH2s () const
G4int GetNofH3s () const
G4int GetNofP1s () const
G4int GetNofP2s () const
G4int GetNofNtuples () const
G4int GetH1Id (const G4String &name, G4bool warn=true) const
G4int GetH2Id (const G4String &name, G4bool warn=true) const
G4int GetH3Id (const G4String &name, G4bool warn=true) const
G4int GetP1Id (const G4String &name, G4bool warn=true) const
G4int GetP2Id (const G4String &name, G4bool warn=true) const
G4int GetH1Nbins (G4int id) const
G4double GetH1Xmin (G4int id) const
G4double GetH1Xmax (G4int id) const
G4double GetH1Width (G4int id) const
G4int GetH2Nxbins (G4int id) const
G4double GetH2Xmin (G4int id) const
G4double GetH2Xmax (G4int id) const
G4double GetH2XWidth (G4int id) const
G4int GetH2Nybins (G4int id) const
G4double GetH2Ymin (G4int id) const
G4double GetH2Ymax (G4int id) const
G4double GetH2YWidth (G4int id) const
G4int GetH3Nxbins (G4int id) const
G4double GetH3Xmin (G4int id) const
G4double GetH3Xmax (G4int id) const
G4double GetH3XWidth (G4int id) const
G4int GetH3Nybins (G4int id) const
G4double GetH3Ymin (G4int id) const
G4double GetH3Ymax (G4int id) const
G4double GetH3YWidth (G4int id) const
G4int GetH3Nzbins (G4int id) const
G4double GetH3Zmin (G4int id) const
G4double GetH3Zmax (G4int id) const
G4double GetH3ZWidth (G4int id) const
G4int GetP1Nbins (G4int id) const
G4double GetP1Xmin (G4int id) const
G4double GetP1Xmax (G4int id) const
G4double GetP1XWidth (G4int id) const
G4double GetP1Ymin (G4int id) const
G4double GetP1Ymax (G4int id) const
G4int GetP2Nxbins (G4int id) const
G4double GetP2Xmin (G4int id) const
G4double GetP2Xmax (G4int id) const
G4double GetP2XWidth (G4int id) const
G4int GetP2Nybins (G4int id) const
G4double GetP2Ymin (G4int id) const
G4double GetP2Ymax (G4int id) const
G4double GetP2YWidth (G4int id) const
G4double GetP2Zmin (G4int id) const
G4double GetP2Zmax (G4int id) const
G4String GetH1Title (G4int id) const
G4String GetH1XAxisTitle (G4int id) const
G4String GetH1YAxisTitle (G4int id) const
G4String GetH2Title (G4int id) const
G4String GetH2XAxisTitle (G4int id) const
G4String GetH2YAxisTitle (G4int id) const
G4String GetH2ZAxisTitle (G4int id) const
G4String GetH3Title (G4int id) const
G4String GetH3XAxisTitle (G4int id) const
G4String GetH3YAxisTitle (G4int id) const
G4String GetH3ZAxisTitle (G4int id) const
G4String GetP1Title (G4int id) const
G4String GetP1XAxisTitle (G4int id) const
G4String GetP1YAxisTitle (G4int id) const
G4String GetP1ZAxisTitle (G4int id) const
G4String GetP2Title (G4int id) const
G4String GetP2XAxisTitle (G4int id) const
G4String GetP2YAxisTitle (G4int id) const
G4String GetP2ZAxisTitle (G4int id) const
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4String GetType () const
G4String GetFileType () const
Static Public Member Functions
static G4XmlAnalysisReader * Instance ()
Protected Member Functions
virtual G4int ReadH1Impl (const G4String &h1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName) final
virtual G4int ReadH2Impl (const G4String &h1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName) final
virtual G4int ReadH3Impl (const G4String &h1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName) final
virtual G4int ReadP1Impl (const G4String &h1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName) final
virtual G4int ReadP2Impl (const G4String &h1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName) final
virtual G4int ReadNtupleImpl (const G4String &ntupleName, const G4String &fileName, const G4String &dirName, G4bool isUserFileName) final
Protected Member Functions inherited from G4ToolsAnalysisReader
G4bool Reset ()
Protected Member Functions inherited from G4VAnalysisReader
void SetH1Manager (G4VH1Manager *h1Manager)
void SetH2Manager (G4VH2Manager *h2Manager)
void SetH3Manager (G4VH3Manager *h3Manager)
void SetP1Manager (G4VP1Manager *p1Manager)
void SetP2Manager (G4VP2Manager *p2Manager)
void SetNtupleManager (G4VRNtupleManager *ntupleManager)
void SetFileManager (G4BaseFileManager *fileManager)
Private Member Functions
tools::raxml_out * GetHandler (const G4String &fileName, const G4String &objectName, const G4String &objectType, const G4String &inFunction)
G4bool Reset ()
Private Attributes
G4XmlRNtupleManager * fNtupleManager
G4XmlRFileManager * fFileManager
Static Private Attributes
static G4XmlAnalysisReader * fgMasterInstance = nullptr
static G4ThreadLocal
G4XmlAnalysisReader * fgInstance = 0
Additional Inherited Members
Protected Attributes inherited from G4ToolsAnalysisReader
G4H1ToolsManager * fH1Manager
G4H2ToolsManager * fH2Manager
G4H3ToolsManager * fH3Manager
G4P1ToolsManager * fP1Manager
G4P2ToolsManager * fP2Manager
Detailed Description
Definition at line 53 of file G4XmlAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 53 of file G4XmlAnalysisReader.hh
Constructor & Destructor Documentation
G4XmlAnalysisReader::G4XmlAnalysisReader (G4bool isMaster = true) explicit
Definition at line 61 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 61 of file G4XmlAnalysisReader.cc
References FatalException, fFileManager, fgInstance, fgMasterInstance, fNtupleManager, G4VAnalysisReader::fState, G4Exception(), G4VAnalysisReader::SetFileManager(), and G4VAnalysisReader::SetNtupleManager().
G4XmlAnalysisReader::~G4XmlAnalysisReader () virtual
Definition at line 89 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 89 of file G4XmlAnalysisReader.cc
References fgInstance, fgMasterInstance, G4VAnalysisReader::fState, and G4AnalysisManagerState::GetIsMaster().
Member Function Documentation
tools::raxml_out * G4XmlAnalysisReader::GetHandler (const G4String & fileName, const G4String & objectName, const G4String & objectType, const G4String & inFunction) private
Definition at line 100 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 100 of file G4XmlAnalysisReader.cc
References G4String::append(), fFileManager, G4Exception(), G4XmlRFileManager::GetRFile(), it, JustWarning, G4XmlRFileManager::OpenRFile(), and propagation_timing::rfile.
Referenced by ReadH1Impl(), ReadH2Impl(), ReadH3Impl(), ReadNtupleImpl(), ReadP1Impl(), and ReadP2Impl().
tools::aida::ntuple* G4XmlAnalysisReader::GetNtuple () const
tools::aida::ntuple* G4XmlAnalysisReader::GetNtuple (G4int ntupleId) const
G4XmlAnalysisReader * G4XmlAnalysisReader::Instance (void) static
Definition at line 50 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 50 of file G4XmlAnalysisReader.cc
References G4Threading::IsWorkerThread().
G4int G4XmlAnalysisReader::ReadH1Impl (const G4String & h1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) final protected virtual
Implements G4VAnalysisReader.
Definition at line 166 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 166 of file G4XmlAnalysisReader.cc
References G4H1ToolsManager::AddH1(), G4ToolsAnalysisReader::fH1Manager, G4VAnalysisReader::fState, GetHandler(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), h1, h1d, G4Analysis::kInvalidId, and G4AnalysisVerbose::Message().
G4int G4XmlAnalysisReader::ReadH2Impl (const G4String & h1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) final protected virtual
Implements G4VAnalysisReader.
Definition at line 192 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 192 of file G4XmlAnalysisReader.cc
References G4H2ToolsManager::AddH2(), G4ToolsAnalysisReader::fH2Manager, G4VAnalysisReader::fState, GetHandler(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), h2, G4Analysis::kInvalidId, and G4AnalysisVerbose::Message().
G4int G4XmlAnalysisReader::ReadH3Impl (const G4String & h1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) final protected virtual
Implements G4VAnalysisReader.
Definition at line 218 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 218 of file G4XmlAnalysisReader.cc
References G4H3ToolsManager::AddH3(), G4ToolsAnalysisReader::fH3Manager, G4VAnalysisReader::fState, GetHandler(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), h3, G4Analysis::kInvalidId, and G4AnalysisVerbose::Message().
G4int G4XmlAnalysisReader::ReadNtupleImpl (const G4String & ntupleName, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) final protected virtual
Implements G4VAnalysisReader.
Definition at line 296 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 296 of file G4XmlAnalysisReader.cc
References fFileManager, fNtupleManager, G4VAnalysisReader::fState, GetHandler(), G4BaseFileManager::GetNtupleFileName(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kInvalidId, G4AnalysisVerbose::Message(), ntuple, and G4TRNtupleManager< TNTUPLE >::SetNtuple().
G4int G4XmlAnalysisReader::ReadP1Impl (const G4String & h1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) final protected virtual
Implements G4VAnalysisReader.
Definition at line 244 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 244 of file G4XmlAnalysisReader.cc
References G4P1ToolsManager::AddP1(), G4ToolsAnalysisReader::fP1Manager, G4VAnalysisReader::fState, GetHandler(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kInvalidId, and G4AnalysisVerbose::Message().
G4int G4XmlAnalysisReader::ReadP2Impl (const G4String & h1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) final protected virtual
Implements G4VAnalysisReader.
Definition at line 270 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 270 of file G4XmlAnalysisReader.cc
References G4P2ToolsManager::AddP2(), G4ToolsAnalysisReader::fP2Manager, G4VAnalysisReader::fState, GetHandler(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kInvalidId, and G4AnalysisVerbose::Message().
G4bool G4XmlAnalysisReader::Reset () private
Definition at line 146 of file G4XmlAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 146 of file G4XmlAnalysisReader.cc
References fNtupleManager, G4TRNtupleManager< TNTUPLE >::Reset(), and G4ToolsAnalysisReader::Reset().
Member Data Documentation
G4XmlRFileManager* G4XmlAnalysisReader::fFileManager private
Definition at line 97 of file G4XmlAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 97 of file G4XmlAnalysisReader.hh
Referenced by G4XmlAnalysisReader(), GetHandler(), and ReadNtupleImpl().
G4ThreadLocal G4XmlAnalysisReader * G4XmlAnalysisReader::fgInstance = 0 static private
Definition at line 85 of file G4XmlAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 85 of file G4XmlAnalysisReader.hh
Referenced by G4XmlAnalysisReader(), and ~G4XmlAnalysisReader().
G4XmlAnalysisReader * G4XmlAnalysisReader::fgMasterInstance = nullptr static private
Definition at line 84 of file G4XmlAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 84 of file G4XmlAnalysisReader.hh
Referenced by G4XmlAnalysisReader(), and ~G4XmlAnalysisReader().
G4XmlRNtupleManager* G4XmlAnalysisReader::fNtupleManager private
Definition at line 96 of file G4XmlAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 96 of file G4XmlAnalysisReader.hh
Referenced by G4XmlAnalysisReader(), ReadNtupleImpl(), and Reset().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/xml/include/G4XmlAnalysisReader.hh
geant4/tree/geant4-10.6-release/source/analysis/xml/src/G4XmlAnalysisReader.cc