ECCE @ EIC Software: G4XpipNTotal Class Reference
G4XpipNTotal Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XpipNTotal.hh>
Public Member Functions
G4XpipNTotal ()
virtual ~G4XpipNTotal ()
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4String Name () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsValid (G4double e) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Private Attributes
G4XPDGTotal thePDGData
std::vector< std::pair< double,
double > > theLowEData
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 35 of file G4XpipNTotal.hh.
View newest version in sPHENIX GitHub at line 35 of file G4XpipNTotal.hh
Constructor & Destructor Documentation
G4XpipNTotal::G4XpipNTotal ()
Definition at line 33 of file G4XpipNTotal.cc.
View newest version in sPHENIX GitHub at line 33 of file G4XpipNTotal.cc
References it, and theLowEData.
virtual G4XpipNTotal::~G4XpipNTotal () inline virtual
Definition at line 39 of file G4XpipNTotal.hh.
View newest version in sPHENIX GitHub at line 39 of file G4XpipNTotal.hh
Member Function Documentation
G4double G4XpipNTotal::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 63 of file G4XpipNTotal.cc.
View newest version in sPHENIX GitHub at line 63 of file G4XpipNTotal.cc
References G4XPDGTotal::CrossSection(), G4Exp(), G4Log(), G4KineticTrack::Get4Momentum(), it, MeV, millibarn, second, theLowEData, thePDGData, x, x1, x2, y, y1, and y2.
virtual const G4CrossSectionVector* G4XpipNTotal::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 41 of file G4XpipNTotal.hh.
View newest version in sPHENIX GitHub at line 41 of file G4XpipNTotal.hh
virtual G4String G4XpipNTotal::Name () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 42 of file G4XpipNTotal.hh.
View newest version in sPHENIX GitHub at line 42 of file G4XpipNTotal.hh
Member Data Documentation
std::vector<std::pair<double,double> > G4XpipNTotal::theLowEData private
Definition at line 45 of file G4XpipNTotal.hh.
View newest version in sPHENIX GitHub at line 45 of file G4XpipNTotal.hh
Referenced by CrossSection(), and G4XpipNTotal().
G4XPDGTotal G4XpipNTotal::thePDGData private
Definition at line 44 of file G4XpipNTotal.hh.
View newest version in sPHENIX GitHub at line 44 of file G4XpipNTotal.hh
Referenced by CrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XpipNTotal.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XpipNTotal.cc