ECCE @ EIC Software: G4IonTable Class Reference
G4IonTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4IonTable.hh>
Public Types
enum { numberOfElements = 118 }
typedef std::multimap< G4int,
const G4ParticleDefinition * > G4IonList
typedef std::multimap< G4int,
const G4ParticleDefinition * >
::iterator G4IonListIterator
Public Member Functions
G4IonTable ()
void SlaveG4IonTable ()
void WorkerG4IonTable ()
virtual ~G4IonTable ()
void DestroyWorkerG4IonTable ()
G4int GetNumberOfElements () const
void RegisterIsotopeTable (G4VIsotopeTable *table)
G4VIsotopeTable * GetIsotopeTable (size_t idx=0) const
void CreateAllIon ()
void CreateAllIsomer ()
void PrepareNuclideTable ()
void PreloadNuclide ()
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4int lvl)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4double E, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4double E, char flbChar, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4double E, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * GetIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J=0)
G4ParticleDefinition * GetIon (G4int encoding)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4int lvl)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4double E, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4double E, char flbChar, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4double E, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * FindIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J=0)
const G4String & GetIonName (G4int Z, G4int A, G4int lvl=0) const
const G4String & GetIonName (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float) const
const G4String & GetIonName (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float) const
const G4String & GetIonName (G4int Z, G4int A, G4int L, G4int lvl) const
G4double GetIonMass (G4int Z, G4int A, G4int L=0, G4int lvl=0) const
G4double GetNucleusMass (G4int Z, G4int A, G4int L=0, G4int lvl=0) const
G4double GetIsomerMass (G4int Z, G4int A, G4int lvl=0) const
G4double GetLifeTime (const G4ParticleDefinition *) const
G4double GetLifeTime (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float) const
G4double GetLifeTime (G4int Z, G4int A, G4double E, char flbChar) const
G4int Entries () const
G4ParticleDefinition * GetParticle (G4int index) const
G4bool Contains (const G4ParticleDefinition *particle) const
void Insert (const G4ParticleDefinition *particle)
void Remove (const G4ParticleDefinition *particle)
void clear ()
G4int size () const
void DumpTable (const G4String &particle_name="ALL") const
void InitializeLightIons ()
G4ParticleDefinition * GetMuonicAtom (G4Ions const *)
G4ParticleDefinition * GetMuonicAtom (G4int Z, G4int A)
Static Public Member Functions
static G4IonTable * GetIonTable ()
static G4bool IsIon (const G4ParticleDefinition *)
static G4bool IsAntiIon (const G4ParticleDefinition *)
static G4int GetNucleusEncoding (G4int Z, G4int A, G4double E=0.0, G4int lvl=0)
static G4int GetNucleusEncoding (G4int Z, G4int A, G4int L, G4double E=0.0, G4int lvl=0)
static G4bool GetNucleusByEncoding (G4int encoding, G4int &Z, G4int &A, G4double &E, G4int &lvl)
static G4bool GetNucleusByEncoding (G4int encoding, G4int &Z, G4int &A, G4int &L, G4double &E, G4int &lvl)
Static Public Attributes
static G4ThreadLocal G4IonList * fIonList = nullptr
static G4ThreadLocal
std::vector< G4VIsotopeTable * > * fIsotopeTableList = nullptr
static G4IonList * fIonListShadow = nullptr
static std::vector
< G4VIsotopeTable * > * fIsotopeTableListShadow = nullptr
static const G4String elementName [numberOfElements]
Protected Member Functions
G4IonTable (const G4IonTable &right)
G4IonTable & operator= (const G4IonTable &)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4int L, G4int lvl)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * FindIonInMaster (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J=0)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4int lvl=0)
G4ParticleDefinition * CreateIon (G4int Z, G4int A, G4int L, G4int lvl)
void InsertWorker (const G4ParticleDefinition *particle)
G4IsotopeProperty * FindIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb) const
G4IsotopeProperty * FindIsotope (G4int Z, G4int A, G4int lvl) const
G4ParticleDefinition * GetLightIon (G4int Z, G4int A) const
G4ParticleDefinition * GetLightAntiIon (G4int Z, G4int A) const
G4bool IsLightIon (const G4ParticleDefinition *) const
G4bool IsLightAntiIon (const G4ParticleDefinition *) const
void AddProcessManager (G4ParticleDefinition *)
G4int GetVerboseLevel () const
Private Attributes
G4NuclideTable * pNuclideTable
G4bool isIsomerCreated
G4int n_error
Detailed Description
Definition at line 64 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 64 of file G4IonTable.hh
Member Typedef Documentation
typedef std::multimap<G4int, const G4ParticleDefinition*> G4IonTable::G4IonList
Definition at line 73 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 73 of file G4IonTable.hh
typedef std::multimap<G4int, const G4ParticleDefinition*>::iterator G4IonTable::G4IonListIterator
Definition at line 74 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 74 of file G4IonTable.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
numberOfElements
Definition at line 326 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 326 of file G4IonTable.hh
Constructor & Destructor Documentation
G4IonTable::G4IonTable ()
Definition at line 121 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 121 of file G4IonTable.cc
References fIonList, fIonListShadow, fIsotopeTableList, fIsotopeTableListShadow, pNuclideTable, PrepareNuclideTable(), and RegisterIsotopeTable().
G4IonTable::G4IonTable (const G4IonTable & right) protected
G4IonTable::~G4IonTable () virtual
Definition at line 181 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 181 of file G4IonTable.cc
References fIonList, fIsotopeTableList, and G4NuclideTable::GetNuclideTable().
Member Function Documentation
void G4IonTable::AddProcessManager (G4ParticleDefinition * ion) protected
Definition at line 1477 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1477 of file G4IonTable.cc
References FatalException, G4cout, G4endl, G4Exception(), G4ParticleTable::GetGenericIon(), G4ParticleTable::GetGenericMuonicAtom(), G4ParticleDefinition::GetParticleDefinitionID(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), GetVerboseLevel(), G4ParticleDefinition::IsGeneralIon(), and G4ParticleDefinition::SetParticleDefinitionID().
Referenced by CreateIon(), and GetMuonicAtom().
void G4IonTable::clear (void)
Definition at line 1319 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1319 of file G4IonTable.cc
References fIonList, G4cout, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), GetVerboseLevel(), and JustWarning.
Referenced by G4ParticleTable::RemoveAllParticles().
G4bool G4IonTable::Contains (const G4ParticleDefinition * particle) const
Definition at line 1663 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1663 of file G4IonTable.cc
References A(), fIonListShadow, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), IsIon(), LL, and Z.
Referenced by Insert().
void G4IonTable::CreateAllIon ()
Definition at line 1602 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1602 of file G4IonTable.cc
References PreloadNuclide().
Referenced by G4ParticleMessenger::SetNewValue().
void G4IonTable::CreateAllIsomer ()
Definition at line 1608 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1608 of file G4IonTable.cc
References PreloadNuclide().
Referenced by G4ParticleMessenger::SetNewValue().
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb) protected
Definition at line 229 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 229 of file G4IonTable.cc
References AddProcessManager(), charge, E, G4DecayTable::entries(), eplus, FindIsotope(), G4Ions::FloatLevelBaseChar(), G4cout, G4endl, G4Exception(), G4VDecayChannel::GetDaughter(), G4DecayTable::GetDecayChannel(), G4IsotopeProperty::GetDecayTable(), G4IsotopeProperty::GetEnergy(), G4ParticleTable::GetGenericIon(), GetIonName(), G4IsotopeProperty::GetIsomerLevel(), G4IsotopeProperty::GetiSpin(), G4IsotopeProperty::GetLifeTime(), G4IsotopeProperty::GetMagneticMoment(), GetNucleusEncoding(), GetNucleusMass(), G4ParticleDefinition::GetParticleDefinitionID(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), GetVerboseLevel(), G4Threading::IsWorkerThread(), JustWarning, keV, mass, MeV, G4ParticleDefinition::SetAntiPDGEncoding(), and G4ParticleDefinition::SetPDGMagneticMoment().
Referenced by CreateIon(), and GetIon().
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb) protected
Definition at line 366 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 366 of file G4IonTable.cc
References AddProcessManager(), charge, CreateIon(), E, eplus, G4cout, G4endl, G4Exception(), G4ParticleTable::GetGenericIon(), GetIonName(), GetNucleusEncoding(), GetNucleusMass(), G4ParticleDefinition::GetParticleDefinitionID(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), GetVerboseLevel(), JustWarning, keV, mass, MeV, G4ParticleDefinition::SetAntiPDGEncoding(), and G4ParticleDefinition::SetPDGMagneticMoment().
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4int lvl = 0) protected
Definition at line 454 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 454 of file G4IonTable.cc
References CreateIon(), G4Exception(), and JustWarning.
G4ParticleDefinition * G4IonTable::CreateIon (G4int Z, G4int A, G4int L, G4int lvl) protected
Definition at line 464 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 464 of file G4IonTable.cc
References CreateIon(), G4Exception(), and JustWarning.
void G4IonTable::DestroyWorkerG4IonTable ()
Definition at line 203 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 203 of file G4IonTable.cc
References fIonList, fIsotopeTableList, and G4NuclideTable::GetNuclideTable().
Referenced by G4ParticleTable::DestroyWorkerG4ParticleTable().
void G4IonTable::DumpTable (const G4String & particle_name = "ALL") const
Definition at line 1440 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1440 of file G4IonTable.cc
References G4ParticleDefinition::DumpTable(), fIonList, G4ParticleDefinition::GetParticleName(), and incremental_prev_tag::idx.
G4int G4IonTable::Entries () const
Definition at line 1685 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1685 of file G4IonTable.cc
References fIonList.
Referenced by LBE::ConstructGeneral(), and GetParticle().
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int lvl = 0)
Definition at line 828 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 828 of file G4IonTable.cc
References A(), fIonList, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetLightIon(), GetNucleusEncoding(), GetVerboseLevel(), JustWarning, and Z.
Referenced by FindIon(), FindIonInMaster(), and GetIon().
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4int lvl)
Definition at line 879 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 879 of file G4IonTable.cc
References A(), FindIon(), fIonList, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), GetVerboseLevel(), JustWarning, LL, and Z.
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4double E, G4int J = 0)
Definition at line 703 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 703 of file G4IonTable.cc
References FindIon().
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 716 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 716 of file G4IonTable.cc
References A(), fIonList, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4NuclideTable::GetLevelTolerance(), GetLightIon(), GetNucleusEncoding(), GetVerboseLevel(), JustWarning, keV, pNuclideTable, and Z.
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4double E, char flbChar, G4int J = 0)
Definition at line 709 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 709 of file G4IonTable.cc
References FindIon(), and G4Ions::FloatLevelBase().
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4double E, G4int J = 0)
Definition at line 767 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 767 of file G4IonTable.cc
References FindIon().
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 780 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 780 of file G4IonTable.cc
References A(), FindIon(), fIonList, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4NuclideTable::GetLevelTolerance(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), GetVerboseLevel(), JustWarning, keV, LL, pNuclideTable, and Z.
G4ParticleDefinition * G4IonTable::FindIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J = 0)
Definition at line 773 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 773 of file G4IonTable.cc
References FindIon(), and G4Ions::FloatLevelBase().
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4int lvl = 0) protected
Definition at line 1767 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1767 of file G4IonTable.cc
References A(), fIonListShadow, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetNucleusEncoding(), and Z.
Referenced by GetIon().
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4int L, G4int lvl) protected
Definition at line 1796 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1796 of file G4IonTable.cc
References A(), FindIon(), fIonListShadow, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), LL, and Z.
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0) protected
Definition at line 1698 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1698 of file G4IonTable.cc
References A(), fIonListShadow, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4NuclideTable::GetLevelTolerance(), GetNucleusEncoding(), pNuclideTable, and Z.
G4ParticleDefinition * G4IonTable::FindIonInMaster (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0) protected
Definition at line 1731 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1731 of file G4IonTable.cc
References A(), FindIon(), fIonListShadow, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4NuclideTable::GetLevelTolerance(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), LL, pNuclideTable, and Z.
G4IsotopeProperty * G4IonTable::FindIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb) const protected
Definition at line 1564 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1564 of file G4IonTable.cc
References fIsotopeTableList, and G4VIsotopeTable::GetIsotope().
Referenced by CreateIon(), GetLifeTime(), and GetNucleusMass().
G4IsotopeProperty * G4IonTable::FindIsotope (G4int Z, G4int A, G4int lvl) const protected
Definition at line 1583 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1583 of file G4IonTable.cc
References fIsotopeTableList, and G4VIsotopeTable::GetIsotope().
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int lvl = 0)
Definition at line 483 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 483 of file G4IonTable.cc
References FindIon(), FindIonInMaster(), G4cout, G4endl, G4Exception(), G4MUTEXLOCK, G4MUTEXUNLOCK, GetVerboseLevel(), InsertWorker(), G4Threading::IsWorkerThread(), and JustWarning.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPFissionFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ExcitationHandler::BreakItUp(), G4EmCorrections::BuildCorrectionVector(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4ParticleHPInelasticCompFS::CompositeApply(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4ITDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4EmCalculator::FindIon(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4ECDecay::G4ECDecay(), G4ITDecay::G4ITDecay(), G4NeutronDecay::G4NeutronDecay(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TritonDecay::G4TritonDecay(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), GetIon(), GetMuonicAtom(), G4FissionProductYieldDist::GetParticleDefinition(), G4ChipsProtonElasticXS::GetQ2max(), G4ChipsHyperonElasticXS::GetQ2max(), G4ChipsPionPlusElasticXS::GetQ2max(), G4ChipsKaonPlusElasticXS::GetQ2max(), G4ChipsKaonMinusElasticXS::GetQ2max(), G4ChipsPionMinusElasticXS::GetQ2max(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ChipsNeutronElasticXS::GetQ2max(), G4BinaryCascade::HighEnergyModelFSProducts(), G4DNARuddIonisationExtendedModel::Initialise(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4InuclNuclei::makeDefinition(), PreloadNuclide(), G4BetheHeitler5DModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4QuasiElasticChannel::Scatter(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), DMXParticleSourceMessenger::SetNewValue(), G4AblaInterface::toG4ParticleDefinition(), G4INCLXXInterface::toG4ParticleDefinition(), and PHG4IonGun::UpdateParticle().
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4int lvl)
Definition at line 519 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 519 of file G4IonTable.cc
References CreateIon(), FindIon(), FindIonInMaster(), G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, GetIon(), GetVerboseLevel(), InsertWorker(), and G4Threading::IsWorkerThread().
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4double E, G4int J = 0)
Definition at line 569 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 569 of file G4IonTable.cc
References GetIon().
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 582 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 582 of file G4IonTable.cc
References CreateIon(), FindIon(), FindIonInMaster(), G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, GetVerboseLevel(), InsertWorker(), G4Threading::IsWorkerThread(), and keV.
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4double E, char flbChar, G4int J = 0)
Definition at line 575 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 575 of file G4IonTable.cc
References G4Ions::FloatLevelBase(), and GetIon().
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4double E, G4int J = 0)
Definition at line 619 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 619 of file G4IonTable.cc
References GetIon().
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb, G4int J = 0)
Definition at line 632 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 632 of file G4IonTable.cc
References CreateIon(), FindIon(), FindIonInMaster(), G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, GetIon(), GetVerboseLevel(), InsertWorker(), G4Threading::IsWorkerThread(), and keV.
G4ParticleDefinition * G4IonTable::GetIon (G4int Z, G4int A, G4int L, G4double E, char flbChar, G4int J = 0)
Definition at line 625 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 625 of file G4IonTable.cc
References G4Ions::FloatLevelBase(), and GetIon().
G4ParticleDefinition * G4IonTable::GetIon (G4int encoding)
Definition at line 681 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 681 of file G4IonTable.cc
References A(), E, G4cout, G4endl, G4Exception(), GetIon(), GetNucleusByEncoding(), GetVerboseLevel(), JustWarning, LL, and Z.
G4double G4IonTable::GetIonMass (G4int Z, G4int A, G4int L = 0, G4int lvl = 0) const
Definition at line 1309 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1309 of file G4IonTable.cc
References GetNucleusMass().
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4IonDEDXScalingICRU73::CreateReferenceParticles(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4TripathiCrossSection::GetElementCrossSection(), G4BinaryCascade::GetIonMass(), G4StatMFFragment::GetNuclearMass(), G4FTFModel::Init(), G4BinaryLightIonReaction::Interact(), and G4BinaryLightIonReaction::SetLighterAsProjectile().
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4int lvl = 0) const
Definition at line 1071 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1071 of file G4IonTable.cc
References A(), elementName, G4ThreadLocal, numberOfElements, pname(), G4AutoDelete::Register(), and Z.
Referenced by G4INCLXXInterface::ApplyYourself(), CreateIon(), GetIonName(), G4LENDManager::GetLENDTarget(), and GetMuonicAtom().
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) const
Definition at line 1022 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1022 of file G4IonTable.cc
References G4Ions::FloatLevelBaseChar(), G4ThreadLocal, GetIonName(), keV, pname(), and G4AutoDelete::Register().
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4int L, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) const
Definition at line 1055 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1055 of file G4IonTable.cc
References G4ThreadLocal, GetIonName(), LL, pname(), and G4AutoDelete::Register().
const G4String & G4IonTable::GetIonName (G4int Z, G4int A, G4int L, G4int lvl) const
Definition at line 1109 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1109 of file G4IonTable.cc
References G4ThreadLocal, GetIonName(), LL, pname(), and G4AutoDelete::Register().
static G4IonTable* G4IonTable::GetIonTable () inline static
Definition at line 77 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 77 of file G4IonTable.hh
References G4ParticleTable::GetIonTable(), and G4ParticleTable::GetParticleTable().
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4NRESP71M03::ApplyMechanismABE(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), G4IonDEDXScalingICRU73::CreateReferenceParticles(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4BetheHeitler5DModel::G4BetheHeitler5DModel(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), G4DNARuddIonisationExtendedModel::Initialise(), G4FissionProductYieldDist::Initialize(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4ParticleHPIsotropic::Sample(), G4ParticleHPContAngularPar::Sample(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), DMXParticleSourceMessenger::SetNewValue(), G4AblaInterface::toG4ParticleDefinition(), G4ParticleHPInelasticCompFS::two_body_reaction(), and PHG4IonGun::UpdateParticle().
G4double G4IonTable::GetIsomerMass (G4int Z, G4int A, G4int lvl = 0) const
Definition at line 1303 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1303 of file G4IonTable.cc
References GetNucleusMass().
G4VIsotopeTable * G4IonTable::GetIsotopeTable (size_t idx = 0) const
Definition at line 1553 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1553 of file G4IonTable.cc
References size().
G4double G4IonTable::GetLifeTime (const G4ParticleDefinition * particle) const
Definition at line 1827 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1827 of file G4IonTable.cc
References FatalException, G4Exception(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::IsGeneralIon(), and pNuclideTable.
Referenced by GetLifeTime().
G4double G4IonTable::GetLifeTime (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) const
Definition at line 1844 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1844 of file G4IonTable.cc
References FindIsotope(), and G4IsotopeProperty::GetLifeTime().
G4double G4IonTable::GetLifeTime (G4int Z, G4int A, G4double E, char flbChar) const
Definition at line 1838 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1838 of file G4IonTable.cc
References G4Ions::FloatLevelBase(), and GetLifeTime().
G4ParticleDefinition * G4IonTable::GetLightAntiIon (G4int Z, G4int A) const protected
Definition at line 1216 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1216 of file G4IonTable.cc
References antilightions::Init(), antilightions::p_alpha, antilightions::p_deuteron, antilightions::p_He3, antilightions::p_proton, and antilightions::p_triton.
G4ParticleDefinition * G4IonTable::GetLightIon (G4int Z, G4int A) const protected
Definition at line 1191 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1191 of file G4IonTable.cc
References lightions::Init(), lightions::p_alpha, lightions::p_deuteron, lightions::p_He3, lightions::p_proton, and lightions::p_triton.
Referenced by FindIon(), and GetNucleusMass().
G4ParticleDefinition * G4IonTable::GetMuonicAtom (G4Ions const * base)
Definition at line 1855 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1855 of file G4IonTable.cc
References A(), AddProcessManager(), G4MuonicAtomHelper::ConstructMuonicAtom(), FatalException, fIonList, fIonListShadow, G4Exception(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetIonName(), GetNucleusEncoding(), IsIon(), G4Threading::IsWorkerThread(), and Z.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), and GetMuonicAtom().
G4ParticleDefinition * G4IonTable::GetMuonicAtom (G4int Z, G4int A)
Definition at line 1935 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1935 of file G4IonTable.cc
References GetIon(), and GetMuonicAtom().
G4bool G4IonTable::GetNucleusByEncoding (G4int encoding, G4int & Z, G4int & A, G4double & E, G4int & lvl) static
Definition at line 967 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 967 of file G4IonTable.cc
References Z.
Referenced by GetIon().
G4bool G4IonTable::GetNucleusByEncoding (G4int encoding, G4int & Z, G4int & A, G4int & L, G4double & E, G4int & lvl) static
!!not supported for excitation states !!!
Definition at line 988 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 988 of file G4IonTable.cc
References LL, and Z.
G4int G4IonTable::GetNucleusEncoding (G4int Z, G4int A, G4double E = 0.0, G4int lvl = 0) static
Definition at line 926 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 926 of file G4IonTable.cc
Referenced by Contains(), CreateIon(), FindIon(), FindIonInMaster(), GetMuonicAtom(), G4LENDManager::GetNucleusEncoding(), GetNucleusEncoding(), GetNucleusMass(), Insert(), InsertWorker(), G4InuclNuclei::makeNuclearFragment(), and Remove().
G4int G4IonTable::GetNucleusEncoding (G4int Z, G4int A, G4int L, G4double E = 0.0, G4int lvl = 0) static
Definition at line 947 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 947 of file G4IonTable.cc
References GetNucleusEncoding().
G4double G4IonTable::GetNucleusMass (G4int Z, G4int A, G4int L = 0, G4int lvl = 0) const
Definition at line 1244 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1244 of file G4IonTable.cc
References A(), EventMustBeAborted, FindIsotope(), fIonList, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4IsotopeProperty::GetEnergy(), GetLightIon(), G4NucleiProperties::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), GetNucleusEncoding(), G4ParticleDefinition::GetPDGMass(), GetVerboseLevel(), mass, and Z.
Referenced by CreateIon(), GetIonMass(), and GetIsomerMass().
G4int G4IonTable::GetNumberOfElements () const inline
Definition at line 345 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 345 of file G4IonTable.hh
References numberOfElements.
G4ParticleDefinition * G4IonTable::GetParticle (G4int index) const
Definition at line 1639 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1639 of file G4IonTable.cc
References Entries(), fIonList, G4cout, G4endl, GetVerboseLevel(), and incremental_prev_tag::idx.
Referenced by LBE::ConstructGeneral().
G4int G4IonTable::GetVerboseLevel () const protected
Definition at line 1471 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1471 of file G4IonTable.cc
References G4ParticleTable::GetParticleTable(), and G4ParticleTable::GetVerboseLevel().
Referenced by AddProcessManager(), clear(), CreateIon(), FindIon(), GetIon(), GetNucleusMass(), GetParticle(), and Remove().
void G4IonTable::InitializeLightIons ()
Definition at line 173 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 173 of file G4IonTable.cc
References lightions::Init(), and antilightions::Init().
Referenced by G4RunManagerKernel::SetupPhysics().
void G4IonTable::Insert (const G4ParticleDefinition * particle)
Definition at line 1337 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1337 of file G4IonTable.cc
References A(), Contains(), fIonListShadow, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), IsIon(), LL, and Z.
Referenced by G4ParticleTable::Insert().
void G4IonTable::InsertWorker (const G4ParticleDefinition * particle) protected
Definition at line 1352 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1352 of file G4IonTable.cc
References A(), fIonList, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), GetNucleusEncoding(), G4ParticleDefinition::GetQuarkContent(), LL, and Z.
Referenced by GetIon().
G4bool G4IonTable::IsAntiIon (const G4ParticleDefinition * particle) static
Definition at line 1147 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1147 of file G4IonTable.cc
References G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetParticleName(), and G4ParticleDefinition::GetParticleType().
Referenced by G4ParticleDefinition::DumpTable(), and G4ParticleDefinition::G4ParticleDefinition().
G4bool G4IonTable::IsIon (const G4ParticleDefinition * particle) static
Definition at line 1124 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1124 of file G4IonTable.cc
References G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), and G4InuclParticleNames::proton.
Referenced by G4DynamicParticle::AllocateElectronOccupancy(), Contains(), G4ParticleDefinition::DumpTable(), G4ParticleDefinition::G4ParticleDefinition(), GetMuonicAtom(), G4ParticleTable::Insert(), Insert(), G4ParticleTable::Remove(), and Remove().
G4bool G4IonTable::IsLightAntiIon (const G4ParticleDefinition * particle) const protected
Definition at line 1181 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1181 of file G4IonTable.cc
References G4ParticleDefinition::GetParticleName().
G4bool G4IonTable::IsLightIon (const G4ParticleDefinition * particle) const protected
Definition at line 1172 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1172 of file G4IonTable.cc
References G4ParticleDefinition::GetParticleName().
G4IonTable& G4IonTable::operator= (const G4IonTable &) inline protected
Definition at line 92 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 92 of file G4IonTable.hh
void G4IonTable::PreloadNuclide ()
Definition at line 1620 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1620 of file G4IonTable.cc
References A(), G4NuclideTable::entries(), G4NuclideTable::GenerateNuclide(), G4IsotopeProperty::GetAtomicMass(), G4IsotopeProperty::GetAtomicNumber(), G4IsotopeProperty::GetEnergy(), GetIon(), G4NuclideTable::GetIsotopeByIndex(), isIsomerCreated, G4Threading::IsMultithreadedApplication(), pNuclideTable, and Z.
Referenced by CreateAllIon(), and CreateAllIsomer().
void G4IonTable::PrepareNuclideTable ()
Definition at line 1614 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1614 of file G4IonTable.cc
References G4NuclideTable::GetNuclideTable(), and pNuclideTable.
Referenced by G4IonTable().
void G4IonTable::RegisterIsotopeTable (G4VIsotopeTable * table)
Definition at line 1540 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1540 of file G4IonTable.cc
References fIsotopeTableList, and G4VIsotopeTable::GetName().
Referenced by G4IonTable().
void G4IonTable::Remove (const G4ParticleDefinition * particle)
Definition at line 1378 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1378 of file G4IonTable.cc
References A(), fIonListShadow, G4cout, G4endl, G4Exception(), G4State_PreInit, G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4StateManager::GetCurrentState(), GetNucleusEncoding(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetQuarkContent(), G4StateManager::GetStateManager(), GetVerboseLevel(), IsIon(), G4Threading::IsWorkerThread(), JustWarning, LL, and Z.
Referenced by G4ParticleTable::Remove().
G4int G4IonTable::size (void) const
Definition at line 1691 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 1691 of file G4IonTable.cc
References fIonList.
Referenced by GetIsotopeTable().
void G4IonTable::SlaveG4IonTable ()
Definition at line 149 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 149 of file G4IonTable.cc
References FatalException, and G4Exception().
void G4IonTable::WorkerG4IonTable ()
Definition at line 154 of file G4IonTable.cc.
View newest version in sPHENIX GitHub at line 154 of file G4IonTable.cc
References fIonList, fIonListShadow, fIsotopeTableList, fIsotopeTableListShadow, and it.
Referenced by G4ParticleTable::WorkerG4ParticleTable().
Member Data Documentation
const G4String G4IonTable::elementName static
Initial value:
= {
  "H",                                                                                                "He",
  "Li", "Be",                                                             "B",  "C",  "N",  "O", "F", "Ne",
  "Na", "Mg",                                                             "Al", "Si", "P", "S", "Cl", "Ar",
  "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr",
  "Rb", "Sr", "Y", "Zr", "Nb", "Mo","Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I",  "Xe",
  "Cs", "Ba",
              "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu",
                   "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn",
  "Fr", "Ra",
              "Ac", "Th", "Pa",  "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr",
              "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og"
}
Definition at line 327 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 327 of file G4IonTable.hh
Referenced by GetIonName().
G4ThreadLocal G4IonTable::G4IonList * G4IonTable::fIonList = nullptr static
Definition at line 315 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 315 of file G4IonTable.hh
Referenced by clear(), DestroyWorkerG4IonTable(), DumpTable(), Entries(), FindIon(), G4IonTable(), GetMuonicAtom(), GetNucleusMass(), GetParticle(), InsertWorker(), size(), WorkerG4IonTable(), and ~G4IonTable().
G4IonTable::G4IonList * G4IonTable::fIonListShadow = nullptr static
Definition at line 317 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 317 of file G4IonTable.hh
Referenced by Contains(), FindIonInMaster(), G4IonTable(), GetMuonicAtom(), Insert(), Remove(), and WorkerG4IonTable().
G4ThreadLocal std::vector< G4VIsotopeTable * > * G4IonTable::fIsotopeTableList = nullptr static
Definition at line 316 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 316 of file G4IonTable.hh
Referenced by DestroyWorkerG4IonTable(), FindIsotope(), G4IonTable(), RegisterIsotopeTable(), WorkerG4IonTable(), and ~G4IonTable().
std::vector< G4VIsotopeTable * > * G4IonTable::fIsotopeTableListShadow = nullptr static
Definition at line 318 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 318 of file G4IonTable.hh
Referenced by G4IonTable(), and WorkerG4IonTable().
G4bool G4IonTable::isIsomerCreated private
Definition at line 311 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 311 of file G4IonTable.hh
Referenced by PreloadNuclide().
G4int G4IonTable::n_error private
Definition at line 333 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 333 of file G4IonTable.hh
G4NuclideTable* G4IonTable::pNuclideTable private
Definition at line 310 of file G4IonTable.hh.
View newest version in sPHENIX GitHub at line 310 of file G4IonTable.hh
Referenced by FindIon(), FindIonInMaster(), G4IonTable(), GetLifeTime(), PreloadNuclide(), and PrepareNuclideTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4IonTable.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4IonTable.cc