ECCE @ EIC Software: HadrontherapyPrimaryGeneratorAction Class Reference
HadrontherapyPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyPrimaryGeneratorAction.hh>
Public Member Functions
HadrontherapyPrimaryGeneratorAction ()
~HadrontherapyPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
void setNewSource (G4bool Varbool)
void setCalculatedPhaseSpaceFileIN (G4String val)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Public Attributes
G4String PathSource
G4bool Readfile
G4bool NewSource
Static Public Attributes
static G4bool ReadFile
Private Member Functions
void SetDefaultPrimaryParticle ()
void setGunCalculatedPhaseSpace ()
Private Attributes
G4String calculatedPhaseSpaceFileIN
HadrontherapyPrimaryGeneratorMessenger * PrimaryGeneratorMessenger
G4ParticleGun * particleGuns
G4GeneralParticleSource * particleGun
G4double sigmaX
std::ofstream ofs
Detailed Description
Definition at line 42 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 42 of file HadrontherapyPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
HadrontherapyPrimaryGeneratorAction::HadrontherapyPrimaryGeneratorAction ()
Definition at line 55 of file HadrontherapyPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 55 of file HadrontherapyPrimaryGeneratorAction.cc
References particleGun, and SetDefaultPrimaryParticle().
HadrontherapyPrimaryGeneratorAction::~HadrontherapyPrimaryGeneratorAction ()
Definition at line 64 of file HadrontherapyPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 64 of file HadrontherapyPrimaryGeneratorAction.cc
References particleGun, and PrimaryGeneratorMessenger.
Member Function Documentation
void HadrontherapyPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 77 of file HadrontherapyPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 77 of file HadrontherapyPrimaryGeneratorAction.cc
References a, calculatedPhaseSpaceFileIN, dir, e, FatalException, G4ParticleTable::FindParticle(), G4Exception(), G4GeneralParticleSource::GeneratePrimaryVertex(), G4SingleParticleSource::GetAngDist(), G4GeneralParticleSource::GetCurrentSource(), G4SingleParticleSource::GetEneDist(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4ParticleDefinition::GetParticleName(), G4SingleParticleSource::GetParticlePosition(), G4ParticleTable::GetParticleTable(), in, NewSource, particleGun, pos(), G4SPSEneDistribution::SetMonoEnergy(), G4SingleParticleSource::SetParticleDefinition(), G4SPSAngDistribution::SetParticleMomentumDirection(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and BTOF::zpos.
void HadrontherapyPrimaryGeneratorAction::setCalculatedPhaseSpaceFileIN (G4String val) inline
Definition at line 58 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file HadrontherapyPrimaryGeneratorAction.hh
References calculatedPhaseSpaceFileIN.
Referenced by HadrontherapyPrimaryGeneratorMessenger::SetNewValue().
void HadrontherapyPrimaryGeneratorAction::SetDefaultPrimaryParticle () private
Definition at line 71 of file HadrontherapyPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 71 of file HadrontherapyPrimaryGeneratorAction.cc
Referenced by HadrontherapyPrimaryGeneratorAction().
void HadrontherapyPrimaryGeneratorAction::setGunCalculatedPhaseSpace () private
void HadrontherapyPrimaryGeneratorAction::setNewSource (G4bool Varbool) inline
Definition at line 54 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file HadrontherapyPrimaryGeneratorAction.hh
References NewSource.
Referenced by HadrontherapyPrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4String HadrontherapyPrimaryGeneratorAction::calculatedPhaseSpaceFileIN private
Definition at line 65 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file HadrontherapyPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and setCalculatedPhaseSpaceFileIN().
G4bool HadrontherapyPrimaryGeneratorAction::NewSource
Definition at line 57 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file HadrontherapyPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and setNewSource().
std::ofstream HadrontherapyPrimaryGeneratorAction::ofs private
Definition at line 75 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 75 of file HadrontherapyPrimaryGeneratorAction.hh
G4GeneralParticleSource* HadrontherapyPrimaryGeneratorAction::particleGun private
Definition at line 73 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file HadrontherapyPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), HadrontherapyPrimaryGeneratorAction(), and ~HadrontherapyPrimaryGeneratorAction().
G4ParticleGun* HadrontherapyPrimaryGeneratorAction::particleGuns private
Definition at line 69 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file HadrontherapyPrimaryGeneratorAction.hh
G4String HadrontherapyPrimaryGeneratorAction::PathSource
Definition at line 54 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file HadrontherapyPrimaryGeneratorAction.hh
HadrontherapyPrimaryGeneratorMessenger* HadrontherapyPrimaryGeneratorAction::PrimaryGeneratorMessenger private
Definition at line 68 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file HadrontherapyPrimaryGeneratorAction.hh
Referenced by ~HadrontherapyPrimaryGeneratorAction().
G4bool HadrontherapyPrimaryGeneratorAction::ReadFile static
Definition at line 52 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file HadrontherapyPrimaryGeneratorAction.hh
G4bool HadrontherapyPrimaryGeneratorAction::Readfile
Definition at line 56 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file HadrontherapyPrimaryGeneratorAction.hh
G4double HadrontherapyPrimaryGeneratorAction::sigmaX private
Definition at line 74 of file HadrontherapyPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 74 of file HadrontherapyPrimaryGeneratorAction.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyPrimaryGeneratorAction.cc