ECCE @ EIC Software: CML2WorldConstruction Class Reference
CML2WorldConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2WorldConstruction.hh>
Public Member Functions
CML2WorldConstruction (void)
~CML2WorldConstruction (void)
G4VPhysicalVolume * Construct ()
bool create (SInputData *inputData, bool bOnlyVisio)
CML2AcceleratorConstruction * getCML2AcceleratorConstruction ()
bool newGeometry ()
bool getWorldCreated ()
CML2PhantomConstruction * getPhantomWorld ()
CML2AcceleratorConstruction * getAcceleratorWorld ()
void checkVolumeOverlap ()
G4bool getbOnlyVisio ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Static Public Member Functions
static CML2WorldConstruction * GetInstance (void)
Private Attributes
bool bWorldCreated
CML2AcceleratorConstruction * acceleratorEnv
CML2PhantomConstruction * phantomEnv
G4VPhysicalVolume * PVWorld
CML2PhaseSpaces * phaseSpace
CML2PhaseSpaces * backScatteredPlane
G4bool bOnlyVisio
Static Private Attributes
static CML2WorldConstruction * instance = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 73 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2WorldConstruction.hh
Constructor & Destructor Documentation
CML2WorldConstruction::CML2WorldConstruction (void)
Definition at line 47 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 47 of file ML2WorldConstruction.cc
References acceleratorEnv, bOnlyVisio, bWorldCreated, CML2PhantomConstruction::GetInstance(), CML2AcceleratorConstruction::GetInstance(), and phantomEnv.
Referenced by GetInstance().
CML2WorldConstruction::~CML2WorldConstruction (void)
Definition at line 55 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 55 of file ML2WorldConstruction.cc
References backScatteredPlane, and phaseSpace.
Member Function Documentation
void CML2WorldConstruction::checkVolumeOverlap ()
Definition at line 144 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 144 of file ML2WorldConstruction.cc
References G4VPhysicalVolume::CheckOverlaps(), G4cout, G4endl, G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetNoDaughters(), int(), k, and PVWorld.
Referenced by main().
G4VPhysicalVolume * CML2WorldConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 72 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file ML2WorldConstruction.cc
References PVWorld.
Referenced by create().
bool CML2WorldConstruction::create (SInputData * inputData, bool bOnlyVisio)
Definition at line 77 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 77 of file ML2WorldConstruction.cc
References acceleratorEnv, G4Colour::Black(), bOnlyVisio, bWorldCreated, CML2PhantomConstruction::Construct(), Construct(), G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, SInputData::generalData, CML2AcceleratorConstruction::getAcceleratorName(), CML2PhantomConstruction::getPhantomName(), G4NistManager::Instance(), mm, SvoxelSegmentation::nX, SvoxelSegmentation::nY, SvoxelSegmentation::nZ, phantomEnv, PVWorld, SGeneralData::StartFileInputData, and SInputData::voxelSegmentation.
Referenced by main().
CML2AcceleratorConstruction* CML2WorldConstruction::getAcceleratorWorld () inline
Definition at line 92 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file ML2WorldConstruction.hh
References acceleratorEnv.
G4bool CML2WorldConstruction::getbOnlyVisio () inline
Definition at line 95 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file ML2WorldConstruction.hh
References bOnlyVisio.
CML2AcceleratorConstruction* CML2WorldConstruction::getCML2AcceleratorConstruction () inline
Definition at line 84 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2WorldConstruction.hh
References acceleratorEnv.
Referenced by main().
CML2WorldConstruction * CML2WorldConstruction::GetInstance (void) static
Definition at line 63 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 63 of file ML2WorldConstruction.cc
References CML2WorldConstruction(), and instance.
Referenced by main().
CML2PhantomConstruction* CML2WorldConstruction::getPhantomWorld () inline
Definition at line 91 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file ML2WorldConstruction.hh
References phantomEnv.
bool CML2WorldConstruction::getWorldCreated () inline
Definition at line 87 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file ML2WorldConstruction.hh
References bWorldCreated.
bool CML2WorldConstruction::newGeometry ()
Definition at line 168 of file ML2WorldConstruction.cc.
View newest version in sPHENIX GitHub at line 168 of file ML2WorldConstruction.cc
References acceleratorEnv, CML2PrimaryGenerationAction::GetInstance(), phantomEnv, and CML2PrimaryGenerationAction::setRotation().
Member Data Documentation
CML2AcceleratorConstruction* CML2WorldConstruction::acceleratorEnv private
Definition at line 100 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file ML2WorldConstruction.hh
Referenced by CML2WorldConstruction(), create(), getAcceleratorWorld(), getCML2AcceleratorConstruction(), and newGeometry().
CML2PhaseSpaces* CML2WorldConstruction::backScatteredPlane private
Definition at line 104 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file ML2WorldConstruction.hh
Referenced by ~CML2WorldConstruction().
G4bool CML2WorldConstruction::bOnlyVisio private
Definition at line 105 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file ML2WorldConstruction.hh
Referenced by CML2WorldConstruction(), create(), and getbOnlyVisio().
bool CML2WorldConstruction::bWorldCreated private
Definition at line 99 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file ML2WorldConstruction.hh
Referenced by CML2WorldConstruction(), create(), and getWorldCreated().
CML2WorldConstruction * CML2WorldConstruction::instance = 0 static private
Definition at line 97 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file ML2WorldConstruction.hh
Referenced by GetInstance().
CML2PhantomConstruction* CML2WorldConstruction::phantomEnv private
Definition at line 101 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file ML2WorldConstruction.hh
Referenced by CML2WorldConstruction(), create(), getPhantomWorld(), and newGeometry().
CML2PhaseSpaces* CML2WorldConstruction::phaseSpace private
Definition at line 103 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file ML2WorldConstruction.hh
Referenced by ~CML2WorldConstruction().
G4VPhysicalVolume* CML2WorldConstruction::PVWorld private
Definition at line 102 of file ML2WorldConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file ML2WorldConstruction.hh
Referenced by checkVolumeOverlap(), Construct(), and create().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2WorldConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2WorldConstruction.cc