ECCE @ EIC Software: CLHEP::RandBinomial Class Reference
CLHEP::RandBinomial Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandBinomial.h>
Public Member Functions
RandBinomial (HepRandomEngine &anEngine, long n=1, double p=0.5)
RandBinomial (HepRandomEngine *anEngine, long n=1, double p=0.5)
virtual ~RandBinomial ()
double fire ()
double fire (long n, double p)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, long n, double p)
double operator() ()
double operator() (long n, double p)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (long n, double p)
static void shootArray (const int size, double *vect, long n=1, double p=0.5)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, long n, double p)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, long n=1, double p=0.5)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Private Member Functions
static double genBinomial (HepRandomEngine *anEngine, long n, double p)
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
long defaultN
double defaultP
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 36 of file RandBinomial.h.
View newest version in sPHENIX GitHub at line 36 of file RandBinomial.h
Constructor & Destructor Documentation
CLHEP::RandBinomial::RandBinomial (HepRandomEngine & anEngine, long n = 1, double p = 0.5) inline
CLHEP::RandBinomial::RandBinomial (HepRandomEngine * anEngine, long n = 1, double p = 0.5) inline
CLHEP::RandBinomial::~RandBinomial () virtual
Definition at line 29 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 29 of file RandBinomial.cc
Member Function Documentation
static std::string CLHEP::RandBinomial::distributionName () inline static
Definition at line 98 of file RandBinomial.h.
View newest version in sPHENIX GitHub at line 98 of file RandBinomial.h
HepRandomEngine & CLHEP::RandBinomial::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 27 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 27 of file RandBinomial.cc
References localEngine.
double CLHEP::RandBinomial::fire () inline
Referenced by fireArray().
double CLHEP::RandBinomial::fire (long n, double p)
Definition at line 42 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 42 of file RandBinomial.cc
References genBinomial(), localEngine, and n.
void CLHEP::RandBinomial::fireArray (const int size, double * vect)
Definition at line 61 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 61 of file RandBinomial.cc
References defaultN, defaultP, fire(), and v.
void CLHEP::RandBinomial::fireArray (const int size, double * vect, long n, double p)
Definition at line 67 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 67 of file RandBinomial.cc
References fire(), and v.
double CLHEP::RandBinomial::genBinomial (HepRandomEngine * anEngine, long n, double p) static private
Definition at line 125 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 125 of file RandBinomial.cc
References b, c, C1_3, C1_6, C5_8, CLHEP_THREAD_LOCAL, DMAX_KM, E, f, CLHEP::HepRandomEngine::flat(), int(), CLHEP::L, CLHEP::m, min, n, CLHEP::nm, CLHEP::StirlingCorrection(), T, and X.
Referenced by fire(), and shoot().
std::istream & CLHEP::RandBinomial::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 341 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 341 of file RandBinomial.cc
References defaultN, defaultP, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandBinomial::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 26 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 26 of file RandBinomial.cc
Referenced by get(), and put().
double CLHEP::RandBinomial::operator() () inline virtual
Reimplemented from CLHEP::HepRandom.
double CLHEP::RandBinomial::operator() (long n, double p) inline
std::ostream & CLHEP::RandBinomial::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 330 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 330 of file RandBinomial.cc
References defaultN, defaultP, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
static double CLHEP::RandBinomial::shoot () inline static
Referenced by shootArray().
double CLHEP::RandBinomial::shoot (long n, double p) static
Definition at line 37 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 37 of file RandBinomial.cc
References genBinomial(), and CLHEP::HepRandom::getTheEngine().
static double CLHEP::RandBinomial::shoot (HepRandomEngine * anEngine) inline static
double CLHEP::RandBinomial::shoot (HepRandomEngine * anEngine, long n, double p) static
Definition at line 32 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 32 of file RandBinomial.cc
References genBinomial().
void CLHEP::RandBinomial::shootArray (const int size, double * vect, long n = 1, double p = 0.5) static
Definition at line 46 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 46 of file RandBinomial.cc
References shoot(), and v.
void CLHEP::RandBinomial::shootArray (HepRandomEngine * anEngine, const int size, double * vect, long n = 1, double p = 0.5) static
Definition at line 53 of file RandBinomial.cc.
View newest version in sPHENIX GitHub at line 53 of file RandBinomial.cc
References shoot(), and v.
Member Data Documentation
long CLHEP::RandBinomial::defaultN private
Definition at line 106 of file RandBinomial.h.
View newest version in sPHENIX GitHub at line 106 of file RandBinomial.h
Referenced by fireArray(), get(), and put().
double CLHEP::RandBinomial::defaultP private
Definition at line 107 of file RandBinomial.h.
View newest version in sPHENIX GitHub at line 107 of file RandBinomial.h
Referenced by fireArray(), get(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandBinomial::localEngine private
Definition at line 105 of file RandBinomial.h.
View newest version in sPHENIX GitHub at line 105 of file RandBinomial.h
Referenced by engine(), and fire().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandBinomial.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandBinomial.cc