ECCE @ EIC Software: G4INCL::InteractionAvatar::ViolationEEnergyFunctor Class Reference
G4INCL::InteractionAvatar::ViolationEEnergyFunctor Class Reference
RootFunctor-derived object for enforcing energy conservation in delta production.
Public Member Functions
ViolationEEnergyFunctor (Nucleus *const nucleus, Particle *const aParticle, const G4double totalEnergyBeforeInteraction, const G4bool localE)
Prepare for calling the () operator and setParticleEnergy.
virtual ~ViolationEEnergyFunctor ()
G4double operator() (const G4double x) const
Compute the energy-conservation violation.
void cleanUp (const G4bool success) const
Clean up after root finding.
void setParticleEnergy (const G4double energy) const
Set the energy of the particle.
Public Member Functions inherited from G4INCL::RootFunctor
virtual ~RootFunctor ()
Public Member Functions inherited from G4INCL::IFunction1D
IFunction1D ()
IFunction1D (const G4double x0, const G4double x1)
virtual ~IFunction1D ()
virtual G4double getXMinimum () const
Return the minimum allowed value of the independent variable.
virtual G4double getXMaximum () const
Return the maximum allowed value of the independent variable.
virtual G4double integrate (const G4double x0, const G4double x1, const G4double step=-1.) const
Integrate the function between two values.
IFunction1D * primitive () const
Return a pointer to the (numerical) primitive to this function.
InterpolationTable * inverseCDFTable (ManipulatorFunc fWrap=0, const G4int nNodes=60) const
Return a pointer to the inverse of the CDF of this function.
Private Attributes
G4double initialEnergy
Total energy before the interaction.
Nucleus * theNucleus
Pointer to the nucleus.
Particle * theParticle
The final-state particle.
G4double theEnergy
The initial energy of the particle.
ThreeVector theMomentum
The initial momentum of the particle.
G4double energyThreshold
Threshold for the energy of the particle.
const G4bool shouldUseLocalEnergy
Whether we should use local energy.
Additional Inherited Members
Public Types inherited from G4INCL::IFunction1D
typedef G4double(*const ManipulatorFunc)(const G4double)
Typedef to simplify the syntax of inverseCDFTable.
Protected Member Functions inherited from G4INCL::RootFunctor
RootFunctor (const G4double x0, const G4double x1)
Protected Attributes inherited from G4INCL::IFunction1D
G4double xMin
Minimum value of the independent variable.
G4double xMax
Maximum value of the independent variable.
Detailed Description
RootFunctor-derived object for enforcing energy conservation in delta production.
Definition at line 163 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 163 of file G4INCLInteractionAvatar.hh
Constructor & Destructor Documentation
G4INCL::InteractionAvatar::ViolationEEnergyFunctor::ViolationEEnergyFunctor (Nucleus *const nucleus, Particle *const aParticle, const G4double totalEnergyBeforeInteraction, const G4bool localE)
Prepare for calling the () operator and setParticleEnergy.
The constructor sets the private class members.
Definition at line 484 of file G4INCLInteractionAvatar.cc.
View newest version in sPHENIX GitHub at line 484 of file G4INCLInteractionAvatar.cc
virtual G4INCL::InteractionAvatar::ViolationEEnergyFunctor::~ViolationEEnergyFunctor () inline virtual
Definition at line 170 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 170 of file G4INCLInteractionAvatar.hh
Member Function Documentation
void G4INCL::InteractionAvatar::ViolationEEnergyFunctor::cleanUp (const G4bool success) const virtual
Clean up after root finding.
Implements G4INCL::RootFunctor.
Definition at line 540 of file G4INCLInteractionAvatar.cc.
View newest version in sPHENIX GitHub at line 540 of file G4INCLInteractionAvatar.cc
G4double G4INCL::InteractionAvatar::ViolationEEnergyFunctor::operator() (const G4double x) const virtual
Compute the energy-conservation violation.
Parameters
x scale factor for the particle energy
Returns
the energy-conservation violation
Implements G4INCL::IFunction1D.
Definition at line 497 of file G4INCLInteractionAvatar.cc.
View newest version in sPHENIX GitHub at line 497 of file G4INCLInteractionAvatar.cc
void G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy (const G4double energy) const
Set the energy of the particle.
Parameters
energy
Definition at line 502 of file G4INCLInteractionAvatar.cc.
View newest version in sPHENIX GitHub at line 502 of file G4INCLInteractionAvatar.cc
References kdfinder::abs(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::InteractionAvatar::locEAccuracy, G4INCL::InteractionAvatar::maxIterLocE, G4INCL::ParticleTable::minDeltaMass, G4INCL::ParticleTable::minDeltaMass2, G4INCL::InteractionAvatar::shouldUseLocalEnergy(), G4INCL::InteractionAvatar::theNucleus, and G4INCL::Nucleus::updatePotentialEnergy().
Member Data Documentation
G4double G4INCL::InteractionAvatar::ViolationEEnergyFunctor::energyThreshold private
Threshold for the energy of the particle.
The particle (a delta) cannot have less than this energy.
Definition at line 203 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 203 of file G4INCLInteractionAvatar.hh
G4double G4INCL::InteractionAvatar::ViolationEEnergyFunctor::initialEnergy private
Total energy before the interaction.
Definition at line 190 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 190 of file G4INCLInteractionAvatar.hh
const G4bool G4INCL::InteractionAvatar::ViolationEEnergyFunctor::shouldUseLocalEnergy private
Whether we should use local energy.
Definition at line 205 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 205 of file G4INCLInteractionAvatar.hh
G4double G4INCL::InteractionAvatar::ViolationEEnergyFunctor::theEnergy private
The initial energy of the particle.
Definition at line 196 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 196 of file G4INCLInteractionAvatar.hh
ThreeVector G4INCL::InteractionAvatar::ViolationEEnergyFunctor::theMomentum private
The initial momentum of the particle.
Definition at line 198 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 198 of file G4INCLInteractionAvatar.hh
Nucleus* G4INCL::InteractionAvatar::ViolationEEnergyFunctor::theNucleus private
Pointer to the nucleus.
Definition at line 192 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 192 of file G4INCLInteractionAvatar.hh
Particle* G4INCL::InteractionAvatar::ViolationEEnergyFunctor::theParticle private
The final-state particle.
Definition at line 194 of file G4INCLInteractionAvatar.hh.
View newest version in sPHENIX GitHub at line 194 of file G4INCLInteractionAvatar.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLInteractionAvatar.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLInteractionAvatar.cc