ECCE @ EIC Software: G4UIbridge Class Reference
G4UIbridge Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIbridge.hh>
Public Member Functions
G4UIbridge (G4UImanager *localUI, G4String dir)
~G4UIbridge ()
G4int ApplyCommand (const G4String &aCmd)
G4UImanager * LocalUI () const
G4String DirName () const
G4int DirLength () const
Private Attributes
G4UImanager * localUImanager
G4String dirName
Detailed Description
Definition at line 58 of file G4UIbridge.hh.
View newest version in sPHENIX GitHub at line 58 of file G4UIbridge.hh
Constructor & Destructor Documentation
G4UIbridge::G4UIbridge (G4UImanager * localUI, G4String dir)
Definition at line 35 of file G4UIbridge.cc.
View newest version in sPHENIX GitHub at line 35 of file G4UIbridge.cc
References dir, dirName, FatalException, G4Exception(), G4UImanager::GetMasterUIpointer(), and G4UImanager::RegisterBridge().
G4UIbridge::~G4UIbridge ()
Definition at line 60 of file G4UIbridge.cc.
View newest version in sPHENIX GitHub at line 60 of file G4UIbridge.cc
Member Function Documentation
G4int G4UIbridge::ApplyCommand (const G4String & aCmd)
Definition at line 65 of file G4UIbridge.cc.
View newest version in sPHENIX GitHub at line 65 of file G4UIbridge.cc
References G4UImanager::ApplyCommand(), and localUImanager.
G4int G4UIbridge::DirLength () const inline
Definition at line 75 of file G4UIbridge.hh.
View newest version in sPHENIX GitHub at line 75 of file G4UIbridge.hh
References dirName.
G4String G4UIbridge::DirName () const inline
Definition at line 73 of file G4UIbridge.hh.
View newest version in sPHENIX GitHub at line 73 of file G4UIbridge.hh
References dirName.
G4UImanager* G4UIbridge::LocalUI () const inline
Definition at line 71 of file G4UIbridge.hh.
View newest version in sPHENIX GitHub at line 71 of file G4UIbridge.hh
References localUImanager.
Referenced by G4UImanager::RegisterBridge().
Member Data Documentation
G4String G4UIbridge::dirName private
Definition at line 68 of file G4UIbridge.hh.
View newest version in sPHENIX GitHub at line 68 of file G4UIbridge.hh
Referenced by DirLength(), DirName(), and G4UIbridge().
G4UImanager* G4UIbridge::localUImanager private
Definition at line 67 of file G4UIbridge.hh.
View newest version in sPHENIX GitHub at line 67 of file G4UIbridge.hh
Referenced by ApplyCommand(), and LocalUI().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIbridge.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIbridge.cc