ECCE @ EIC Software: DicomNestedPhantomParameterisation Class Reference
DicomNestedPhantomParameterisation Class Reference
Implements a G4VNestedParameterisation.
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomNestedPhantomParameterisation.hh>
Public Types
typedef std::map< G4String,
G4VisAttributes * > ColourMap_t
Public Member Functions
DicomNestedPhantomParameterisation (const G4ThreeVector &voxelSize, std::vector< G4Material * > &mat, G4int fnZ_=0, G4int fnY_=0, G4int fnX_=0, G4String colorFile=defaultColorFile)
~DicomNestedPhantomParameterisation ()
G4Material * ComputeMaterial (G4VPhysicalVolume *currentVol, const G4int repNo, const G4VTouchable *parentTouch)
G4int GetNumberOfMaterials () const
G4Material * GetMaterial (G4int idx) const
unsigned int GetMaterialIndex (unsigned int copyNo) const
void SetMaterialIndices (size_t *matInd)
void SetNoVoxel (unsigned int nx, unsigned int ny, unsigned int nz)
void ComputeTransformation (const G4int no, G4VPhysicalVolume *currentPV) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
const ColourMap_t & GetColourMap () const
ColourMap_t & GetColourMap ()
Public Member Functions inherited from G4VNestedParameterisation
G4VNestedParameterisation ()
virtual ~G4VNestedParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int no, G4VPhysicalVolume *thisVol)
G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
Public Member Functions inherited from G4VVolumeMaterialScanner
G4VVolumeMaterialScanner ()
virtual ~G4VVolumeMaterialScanner ()
Static Public Attributes
static G4String defaultColorFile
Private Member Functions
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void ReadColourData (G4String)
Private Attributes
G4double fdX
G4double fdY
G4double fdZ
G4int fnX
G4int fnY
G4int fnZ
std::vector< G4Material * > fMaterials
size_t * fMaterialIndices
ColourMap_t fColours
std::map< G4int,
G4VisAttributes * > mColours
std::vector< G4double > fpZ
Detailed Description
Implements a G4VNestedParameterisation.
Definition at line 65 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 65 of file DicomNestedPhantomParameterisation.hh
Member Typedef Documentation
typedef std::map<G4String, G4VisAttributes*> DicomNestedPhantomParameterisation::ColourMap_t
Definition at line 68 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 68 of file DicomNestedPhantomParameterisation.hh
Constructor & Destructor Documentation
DicomNestedPhantomParameterisation::DicomNestedPhantomParameterisation (const G4ThreeVector & voxelSize, std::vector< G4Material * > & mat, G4int fnZ_ = 0, G4int fnY_ = 0, G4int fnX_ = 0, G4String colorFile = defaultColorFile)
Definition at line 51 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 51 of file DicomNestedPhantomParameterisation.cc
References ReadColourData().
DicomNestedPhantomParameterisation::~DicomNestedPhantomParameterisation ()
Definition at line 66 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 66 of file DicomNestedPhantomParameterisation.cc
Member Function Documentation
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Box & box, const G4int , const G4VPhysicalVolume *) const virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 222 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 222 of file DicomNestedPhantomParameterisation.cc
References fdX, fdY, fdZ, G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 110 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 110 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 112 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 112 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 114 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 114 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 116 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 116 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 118 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 118 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 120 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 120 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 122 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 122 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 124 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 124 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 126 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 126 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 128 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 128 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 130 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 130 of file DicomNestedPhantomParameterisation.hh
void DicomNestedPhantomParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VNestedParameterisation.
Definition at line 132 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 132 of file DicomNestedPhantomParameterisation.hh
G4Material * DicomNestedPhantomParameterisation::ComputeMaterial (G4VPhysicalVolume * currentVol, const G4int repNo, const G4VTouchable * parentTouch) virtual
Implements G4VNestedParameterisation.
Definition at line 108 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 108 of file DicomNestedPhantomParameterisation.cc
References fColours, G4String::first(), fMaterials, fnX, fnY, G4cout, G4endl, G4VVisManager::GetConcreteInstance(), G4VPhysicalVolume::GetLogicalVolume(), GetMaterialIndex(), G4VTouchable::GetReplicaNumber(), mColours, n, and G4LogicalVolume::SetVisAttributes().
void DicomNestedPhantomParameterisation::ComputeTransformation (const G4int no, G4VPhysicalVolume * currentPV) const virtual
Implements G4VNestedParameterisation.
Definition at line 208 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 208 of file DicomNestedPhantomParameterisation.cc
References fdZ, fnZ, and G4VPhysicalVolume::SetTranslation().
const ColourMap_t& DicomNestedPhantomParameterisation::GetColourMap () const inline
Definition at line 105 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 105 of file DicomNestedPhantomParameterisation.hh
References fColours.
ColourMap_t& DicomNestedPhantomParameterisation::GetColourMap () inline
Definition at line 106 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 106 of file DicomNestedPhantomParameterisation.hh
References fColours.
G4Material * DicomNestedPhantomParameterisation::GetMaterial (G4int idx) const virtual
Implements G4VNestedParameterisation.
Definition at line 199 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 199 of file DicomNestedPhantomParameterisation.cc
References fMaterials.
unsigned int DicomNestedPhantomParameterisation::GetMaterialIndex (unsigned int copyNo) const
Definition at line 178 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 178 of file DicomNestedPhantomParameterisation.cc
References fMaterialIndices.
Referenced by ComputeMaterial().
G4int DicomNestedPhantomParameterisation::GetNumberOfMaterials () const virtual
Implements G4VNestedParameterisation.
Definition at line 189 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 189 of file DicomNestedPhantomParameterisation.cc
References fMaterials.
void DicomNestedPhantomParameterisation::ReadColourData (G4String colourFile) private
Definition at line 71 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 71 of file DicomNestedPhantomParameterisation.cc
References FALSE, fColours, fin, mColours, and G4VisAttributes::SetVisibility().
Referenced by DicomNestedPhantomParameterisation().
void DicomNestedPhantomParameterisation::SetMaterialIndices (size_t * matInd) inline
Definition at line 94 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 94 of file DicomNestedPhantomParameterisation.hh
References fMaterialIndices.
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom().
void DicomNestedPhantomParameterisation::SetNoVoxel (unsigned int nx, unsigned int ny, unsigned int nz)
Definition at line 99 of file DicomNestedPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 99 of file DicomNestedPhantomParameterisation.cc
References fnX, fnY, and fnZ.
Referenced by DicomNestedParamDetectorConstruction::ConstructPhantom().
Member Data Documentation
G4String DicomNestedPhantomParameterisation::defaultColorFile static
Initial value:
=
        DicomHandler::GetDicomDataPath() + "/ColourMap.dat"
Definition at line 70 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 70 of file DicomNestedPhantomParameterisation.hh
ColourMap_t DicomNestedPhantomParameterisation::fColours private
Definition at line 145 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 145 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeMaterial(), GetColourMap(), and ReadColourData().
G4double DicomNestedPhantomParameterisation::fdX private
Definition at line 141 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 141 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeDimensions().
G4double DicomNestedPhantomParameterisation::fdY private
Definition at line 141 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 141 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeDimensions().
G4double DicomNestedPhantomParameterisation::fdZ private
Definition at line 141 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 141 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeDimensions(), and ComputeTransformation().
size_t* DicomNestedPhantomParameterisation::fMaterialIndices private
Definition at line 144 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 144 of file DicomNestedPhantomParameterisation.hh
Referenced by GetMaterialIndex(), and SetMaterialIndices().
std::vector<G4Material*> DicomNestedPhantomParameterisation::fMaterials private
Definition at line 143 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 143 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeMaterial(), GetMaterial(), and GetNumberOfMaterials().
G4int DicomNestedPhantomParameterisation::fnX private
Definition at line 142 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeMaterial(), and SetNoVoxel().
G4int DicomNestedPhantomParameterisation::fnY private
Definition at line 142 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeMaterial(), and SetNoVoxel().
G4int DicomNestedPhantomParameterisation::fnZ private
Definition at line 142 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeTransformation(), and SetNoVoxel().
std::vector<G4double> DicomNestedPhantomParameterisation::fpZ private
Definition at line 147 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 147 of file DicomNestedPhantomParameterisation.hh
std::map<G4int, G4VisAttributes*> DicomNestedPhantomParameterisation::mColours private
Definition at line 146 of file DicomNestedPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 146 of file DicomNestedPhantomParameterisation.hh
Referenced by ComputeMaterial(), and ReadColourData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomNestedPhantomParameterisation.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomNestedPhantomParameterisation.cc