ECCE @ EIC Software: G4VPhysicalVolume Class Reference
G4VPhysicalVolume Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VPhysicalVolume.hh>
Public Member Functions
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4VPhysicalVolume (const G4VPhysicalVolume &)=delete
G4VPhysicalVolume & operator= (const G4VPhysicalVolume &)=delete
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
virtual G4int GetMultiplicity () const
virtual EVolume VolumeType () const =0
virtual G4bool IsMany () const =0
virtual G4int GetCopyNo () const =0
virtual void SetCopyNo (G4int CopyNo)=0
virtual G4bool IsReplicated () const =0
virtual G4bool IsParameterised () const =0
virtual G4VPVParameterisation * GetParameterisation () const =0
virtual void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const =0
virtual G4bool IsRegularStructure () const =0
virtual G4int GetRegularStructureId () const =0
virtual G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int errMax=1)
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
EVolume DeduceVolumeType () const
Static Public Member Functions
static const G4PVManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions
void InitialiseWorker (G4VPhysicalVolume *pMasterObject, G4RotationMatrix *pRot, const G4ThreeVector &tlate)
void TerminateWorker (G4VPhysicalVolume *pMasterObject)
Protected Attributes
G4int instanceID
Static Protected Attributes
static G4GEOM_DLL G4PVManager subInstanceManager
Private Attributes
G4LogicalVolume * flogical = nullptr
G4String fname
G4LogicalVolume * flmother = nullptr
G4PVData * pvdata = nullptr
Detailed Description
Definition at line 78 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VPhysicalVolume.hh
Constructor & Destructor Documentation
G4VPhysicalVolume::G4VPhysicalVolume (G4RotationMatrix * pRot, const G4ThreeVector & tlate, const G4String & pName, G4LogicalVolume * pLogical, G4VPhysicalVolume * pMother)
Definition at line 54 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VPhysicalVolume.cc
References G4GeomSplitter< T >::CreateSubInstance(), G4PVData::frot, instanceID, pvdata, G4PhysicalVolumeStore::Register(), SetRotation(), SetTranslation(), subInstanceManager, G4PVData::tx, G4PVData::ty, G4PVData::tz, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4VPhysicalVolume::~G4VPhysicalVolume () virtual
Definition at line 91 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 91 of file G4VPhysicalVolume.cc
References G4PhysicalVolumeStore::DeRegister(), and pvdata.
G4VPhysicalVolume::G4VPhysicalVolume (const G4VPhysicalVolume &) delete
G4VPhysicalVolume::G4VPhysicalVolume (__void__ &)
Definition at line 79 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 79 of file G4VPhysicalVolume.cc
References G4GeomSplitter< T >::CreateSubInstance(), instanceID, G4PhysicalVolumeStore::Register(), and subInstanceManager.
Member Function Documentation
G4bool G4VPhysicalVolume::CheckOverlaps (G4int res = 1000, G4double tol = 0., G4bool verbose = true, G4int errMax = 1) virtual
Reimplemented in G4PVPlacement, G4PVParameterised, and G4VExternalPhysicalVolume.
Definition at line 213 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 213 of file G4VPhysicalVolume.cc
Referenced by G4Navigator::CheckOverlapsIterative(), CML2WorldConstruction::checkVolumeOverlap(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), and G4LogicalVolumeModel::DescribeYourselfTo().
void G4VPhysicalVolume::Clean () static
Definition at line 117 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 117 of file G4VPhysicalVolume.cc
References G4GeomSplitter< T >::FreeSlave(), and subInstanceManager.
Referenced by G4PhysicalVolumeStore::~G4PhysicalVolumeStore().
EVolume G4VPhysicalVolume::DeduceVolumeType () const inline
virtual G4int G4VPhysicalVolume::GetCopyNo () const pure virtual
Implemented in G4PVReplica, G4ReplicatedSlice, G4PVDivision, and G4PVPlacement.
Referenced by EICG4dRICHDetector::ActivateVolumeTree(), G4GMocrenFileSceneHandler::AddSolid(), G4PVPlacement::CheckOverlaps(), G4VoxelSafety::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), PHG4TpcDetector::ConstructTpcGasVolume(), G4PhysicalVolumeModel::DescribeAndDescend(), G4LogicalVolumeModel::DescribeYourselfTo(), G4tgbGeometryDumper::DumpPVPlacement(), G4ASCIITreeSceneHandler::EndModeling(), export_G4VPhysicalVolume(), PHG4ZDCSteppingAction::FindIndexSMD(), PHG4ZDCSteppingAction::FindIndexZDC(), EICG4dRICHDetector::GetPSST(), ePHENIXRICH::ePHENIXRICHConstruction::is_in_sector(), G4MultiNavigator::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITMultiNavigator::LocateGlobalPointAndSetup(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), B5HodoscopeSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), XrayFluoSD::ProcessHits(), G4PhysicalVolumeMassScene::ProcessVolume(), G4ReflectionFactory::ReflectPVPlacement(), G4ASCIITreeSceneHandler::RequestPrimitives(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), and EICG4LumiSteppingAction::UserSteppingAction().
const G4RotationMatrix * G4VPhysicalVolume::GetFrameRotation () const
Definition at line 200 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 200 of file G4VPhysicalVolume.cc
References G4MT_rot.
Referenced by G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), G4AdjointPosOnPhysVolGenerator::ComputeTransformationFromPhysVolToWorld(), export_G4VPhysicalVolume(), G4LatticeManager::LoadLattice(), G4LatticeManager::RegisterLattice(), DicomIntersectVolume::SetNewValue(), XDetectorConstruction::SetupGeometry(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
G4ThreeVector G4VPhysicalVolume::GetFrameTranslation () const
Definition at line 205 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 205 of file G4VPhysicalVolume.cc
References G4MT_tx, G4MT_ty, and G4MT_tz.
Referenced by DicomIntersectVolume::SetNewValue().
G4int G4VPhysicalVolume::GetInstanceID () const inline
G4LogicalVolume* G4VPhysicalVolume::GetLogicalVolume () const inline
Referenced by EICG4dRICHDetector::ActivateVolumeTree(), CML2ExpVoxels::add(), PHG4MicromegasDetector::add_geometry_node(), G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), G4LogicalVolume::AddDaughter(), G4GMocrenFileSceneHandler::AddSolid(), XrayFluoAnalysisManager::analyseStepping(), Par01PionShowerModel::AssignSpotAndCallHit(), Par01EMShowerModel::AssignSpotAndCallHit(), G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), G4ReplicaNavigation::BackLocate(), G4Region::BelongsTo(), PHG4mRICHDetector::build_aerogel(), PHG4mRICHDetector::build_holderBox(), PHG4mRICHDetector::build_mirror(), G4PhantomParameterisation::BuildContainerSolid(), UltraFresnelLens::BuildLens(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4Track::CalculateVelocityForOpticalPhoton(), G4PVDivision::CheckAndSetParameters(), G4PVPlacement::CheckOverlaps(), G4VReadOutGeometry::CheckROVolume(), CML2WorldConstruction::checkVolumeOverlap(), G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), DicomPhantomParameterisationColour::ComputeMaterial(), DicomNestedPhantomParameterisation::ComputeMaterial(), G4VPVParameterisation::ComputeMaterial(), CellParameterisation::ComputeMaterial(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4ITNavigator2::ComputeSafety(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4PhantomParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeSolid(), G4VNestedParameterisation::ComputeSolid(), G4PropagatorInField::ComputeStep(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), GB06ParallelWorldForSlices::Construct(), Par01ParallelWorldForPion::Construct(), ExGflash3ParallelWorld::Construct(), RE01CalorimeterROGeometry::Construct(), RE05CalorimeterParallelWorld::Construct(), ExTGDetectorConstructionWithCpp::Construct(), ExGflash2ParallelWorld::Construct(), RE04ParallelWorldConstruction::Construct(), HadrontherapyDetectorROGeometry::Construct(), B02ImportanceDetectorConstruction::Construct(), F04ElementField::Construct(), G02DetectorConstruction::Construct(), B03ImportanceDetectorConstruction::Construct(), G4tgbVolume::ConstructG4Volumes(), CCalG4Ecal::constructIn(), UltraDetectorConstruction::ConstructUVscope(), G4TheRayTracer::CreateBitMap(), ElectronBenchmarkDetector::CreateGeometry(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume(), DetectorConstruction::DefineVolumes(), G4RunManagerKernel::DefineWorldVolume(), G4GeometryManager::DeleteOptimisations(), G4VFieldModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), G4GeometryWorkspace::DestroyWorkspace(), G4GlobalFastSimulationManager::DisplayRegion(), PHG4GDMLWriteStructure::DivisionvolWrite(), G4GDMLWriteStructure::DivisionvolWrite(), G4TrajectoryDrawByOriginVolume::Draw(), G4VisManager::Draw(), PHG4GDMLUtility::Dump_G4_GDML(), PHG4GDMLUtility::Dump_GDML(), G4tgbGeometryDumper::DumpPhysVol(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpPVPlacement(), G4TrajectoryOriginVolumeFilter::Evaluate(), export_G4VPhysicalVolume(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), G4PropagatorInField::FindAndSetFieldManager(), G4VReadOutGeometry::FindROTouchable(), PHG4EICMvtxDetector::FindSensor(), PHG4MvtxDetector::FindSensor(), PHG4DisplayAction::FindVolumes(), G4FastTrack::FRecordsAffineTransformation(), G4PVDivision::G4PVDivision(), G4PVParameterised::G4PVParameterised(), G4PVPlacement::G4PVPlacement(), G4PVReplica::G4PVReplica(), G4ReplicatedSlice::G4ReplicatedSlice(), G4VExternalPhysicalVolume::G4VExternalPhysicalVolume(), G4GDMLRead::GeneratePhysvolName(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), EICG4ZDCDetector::GetAbsorberVolumeInfo(), EICG4ZDCDetector::GetActiveVolumeInfo(), G4Navigator::GetGlobalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4LogicalVolume::GetMass(), G4Channeling::GetMatData(), G4Channeling::GetMeanFreePath(), G4VTransitionRadiation::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4ITTransportationManager::GetParallelWorld(), G4TransportationManager::GetParallelWorld(), PhysicsList::GetRange(), G4tgbGeometryDumper::GetTopPhysVol(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4GeometryWorkspace::InitialisePhysicalVolumes(), G4BOptnForceCommonTruncatedExp::Initialize(), BeastMagnetDetector::InsertVolumes(), AllSiliconTrackerDetector::InsertVolumes(), PHG4BackwardHcalDetector::IsInBackwardHcal(), PHG4BarrelEcalDetector::IsInBarrelEcal(), PHG4BbcDetector::IsInBbc(), PHG4EPDDetector::IsInDetector(), EICG4ZDCDetector::IsInDetector(), EICG4BwdDetector::IsInDetector(), EICG4B0ECALDetector::IsInDetector(), PHG4TpcEndCapDetector::IsInDetector(), G4EicDircDetector::IsInDetector(), PHG4ForwardEcalDetector::IsInForwardEcal(), PHG4ForwardHcalDetector::IsInForwardHcal(), PHG4InttDetector::IsInIntt(), PHG4LFHcalDetector::IsInLFHcal(), G4WeightWindowStore::IsInWorld(), G4IStore::IsInWorld(), PHG4ZDCDetector::IsInZDC(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4LatticeManager::LoadLattice(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), G4ITNavigator2::LocateGlobalPointWithinVolume(), GFlashHitMaker::make(), RE06SteppingVerbose::NewStep(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), G4GDMLWriteParamvol::ParamvolAlgorithmWrite(), PHG4GDMLWriteParamvol::ParamvolAlgorithmWrite(), G4GDMLWriteParamvol::ParamvolWrite(), PHG4GDMLWriteParamvol::ParamvolWrite(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), SplitProcess::PostStepDoIt(), G4Channeling::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4StepLimiter::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4NavigationLogger::PreComputeStepLog(), ExN04CalorimeterSD::ProcessHits(), G4HumanPhantomSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4ReflectionFactory::ReflectPVDivision(), G4ReflectionFactory::ReflectPVPlacement(), G4ReflectionFactory::ReflectPVReplica(), G4LatticeManager::RegisterLattice(), PHG4GDMLWriteStructure::ReplicavolWrite(), G4GDMLWriteStructure::ReplicavolWrite(), G4PropagatorInField::ReportLoopingParticle(), G4NavigationLogger::ReportOutsideMother(), G4NavigationLogger::ReportVolumeAndIntersection(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VoxelSafety::SafetyForVoxelHeader(), G4VoxelSafety::SafetyForVoxelNode(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), G4LBLVtxDetector::SetActiveVolumes(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), G4LogicalVolume::SetFieldManager(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandsTouchable::SetNewValue(), G4RTPrimaryGeneratorAction::SetUp(), ParallelWorld::SetupChemistryGeometry(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), RE06ParallelWorld::SetupGeometry(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), G4ITNavigator2::SetupHierarchy(), G4GlobalFastSimulationManager::ShowSetup(), G4SteppingManager::Stepping(), G4ParallelWorldProcess::SwitchMaterial(), G4LogicalVolume::TotalVolumeEntities(), PHG4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLWriteStructure::TraverseVolumeTree(), G4Channeling::UpdateParameters(), PHG4InttSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), and G4MSSteppingAction::UserSteppingAction().
G4LogicalVolume* G4VPhysicalVolume::GetMotherLogical () const inline
Referenced by G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), G4GeometryManager::BuildOptimisations(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4AdjointPosOnPhysVolGenerator::ComputeTransformationFromPhysVolToWorld(), G4GeometryManager::DeleteOptimisations(), G4PhysicalVolumeStore::DeRegister(), G4GlobalFastSimulationManager::DisplayRegion(), G4tgbGeometryDumper::DumpPhysVol(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpPVPlacement(), G4tgbGeometryDumper::DumpPVReplica(), export_G4VPhysicalVolume(), G4tgbGeometryDumper::GetTopPhysVol(), G4OpBoundaryProcess::PostStepDoIt(), G4RunManager::ReOptimizeMotherOf(), and G4RegionStore::SetWorldVolume().
G4int G4VPhysicalVolume::GetMultiplicity () const virtual
Reimplemented in G4PVReplica, G4ReplicatedSlice, and G4PVDivision.
Definition at line 137 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 137 of file G4VPhysicalVolume.cc
Referenced by G4GMocrenFileSceneHandler::AddSolid(), export_G4VPhysicalVolume(), G4LogicalVolume::GetMass(), G4GDMLWriteParamvol::ParamvolAlgorithmWrite(), PHG4GDMLWriteParamvol::ParamvolAlgorithmWrite(), G4GDMLWriteParamvol::ParamvolWrite(), PHG4GDMLWriteParamvol::ParamvolWrite(), G4Region::ScanVolumeTree(), and G4LogicalVolume::TotalVolumeEntities().
const G4String& G4VPhysicalVolume::GetName () const inline
Referenced by G4TransportationManager::ActivateNavigator(), EICG4dRICHDetector::ActivateVolumeTree(), G4LogicalVolume::AddDaughter(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GDMLWrite::AddModule(), PHG4GDMLWrite::AddModule(), G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), PHG4GDMLWriteStructure::BorderSurfaceCache(), G4GDMLWriteStructure::BorderSurfaceCache(), G4SmartVoxelHeader::BuildNodes(), G4PVDivision::CheckAndSetParameters(), G4ReplicatedSlice::CheckAndSetParameters(), G4PVReplica::CheckOnlyDaughter(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4Navigator::CheckOverlapsIterative(), DMXStackingAction::ClassifyNewTrack(), G4VoxelSafety::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4ITNavigator2::ComputeSafety(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4PropagatorInField::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), G4WeightWindowConfigurator::Configure(), G4WeightCutOffConfigurator::Configure(), G4ImportanceConfigurator::Configure(), DMXParticleSource::ConfineSourceToVolume(), G4SPSPosDistribution::ConfineSourceToVolume(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDLiver::Construct(), G4MIRDRightScapula::Construct(), G4VoxelRightBreast::Construct(), G4MIRDBrain::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDThyroid::Construct(), G4MIRDHead::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDPancreas::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDRightArmBone::Construct(), G4MIRDUrinaryBladder::Construct(), G4tgbDetectorConstruction::Construct(), B02ImportanceDetectorConstruction::Construct(), B03ImportanceDetectorConstruction::Construct(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), G4tgbDetectorBuilder::ConstructDetector(), G4tgbVolume::ConstructG4PhysVol(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Ecal::constructIn(), G4FastSimulationPhysics::ConstructProcess(), B02ImportanceDetectorConstruction::CreateImportanceStore(), CCaloSD::createNewHit(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4PathFinder::CreateTouchableHandle(), G4ITPathFinder::CreateTouchableHandle(), B02ImportanceDetectorConstruction::CreateWeightWindowStore(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4TransportationManager::DeActivateNavigator(), G4DNAMolecularDissociation::DecayIt(), G4TransportationManager::DeRegisterNavigator(), G4ITTransportationManager::DeRegisterWorld(), G4TransportationManager::DeRegisterWorld(), G4LogicalVolumeModel::DescribeYourselfTo(), CCalVOrganization::DetectorLevel(), PHG4GDMLWriteStructure::DivisionvolWrite(), G4GDMLWriteStructure::DivisionvolWrite(), G4TrajectoryDrawByOriginVolume::Draw(), G4tgbVolumeMgr::DumpG4PhysVolLeaf(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpPVPlacement(), G4tgbGeometryDumper::DumpPVReplica(), G4RunManagerKernel::DumpRegion(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4tgbVolumeMgr::DumpSummary(), G4ExceptionHandler::DumpTrackInfo(), G4ASCIITreeSceneHandler::EndModeling(), G4TrajectoryOriginVolumeFilter::Evaluate(), export_G4VPhysicalVolume(), F04TrajectoryPoint::F04TrajectoryPoint(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), PHG4EICMvtxDetector::FindSensor(), PHG4MvtxDetector::FindSensor(), G4FastTrack::FRecordsAffineTransformation(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4IStore::G4IStore(), G4PVParameterised::G4PVParameterised(), G4PVReplica::G4PVReplica(), PHG4InttDetector::get_ActiveVolumeTuple(), G4Navigator::GetGlobalExitNormal(), G4PSEnergyDeposit3D::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4LatticeManager::GetLattice(), PHG4OuterHcalDetector::GetLayerTowerId(), PHG4InnerHcalDetector::GetLayerTowerId(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), PHG4mRICHSteppingAction::GetModuleID(), G4ModelingParameters::PVPointerCopyNo::GetName(), G4ITTransportationManager::GetNavigator(), G4TransportationManager::GetNavigator(), B03PVolumeStore::GetPNames(), B02PVolumeStore::GetPNames(), EICG4dRICHDetector::GetPSST(), B02PVolumeStore::GetPVolume(), B03PVolumeStore::GetPVolume(), CCaloSD::getStepInfo(), G4tgbVolumeMgr::GetTopPhysVol(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), AllSiliconTrackerDetector::InsertVolumes(), PHG4EnvelopeDetector::IsInEnvelope(), PHG4ForwardDualReadoutDetector::IsInForwardDualReadout(), PHG4EICMvtxDetector::IsInMvtx(), PHG4MvtxDetector::IsInMvtx(), PHG4EICMvtxDetector::IsSensor(), PHG4MvtxDetector::IsSensor(), DMXParticleSource::IsSourceConfined(), G4SPSPosDistribution::IsSourceConfined(), G4LatticeManager::LoadLattice(), G4MultiNavigator::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4ITMultiNavigator::LocateGlobalPointAndSetup(), main(), operator<<(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), PHG4ForwardDualReadoutSteppingAction::ParseG4VolumeName(), Path(), CCalG4Able::PhysicalVolume(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), PrtOpBoundaryProcess::PostStepDoIt(), G4EicDircOpBoundaryProcess::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), HadrontherapyStepMax::PostStepGetPhysicalInteractionLength(), IORTStepMax::PostStepGetPhysicalInteractionLength(), ML2StepMax::PostStepGetPhysicalInteractionLength(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4ITSteppingVerbose::PostStepVerbose(), G4NavigationLogger::PreComputeStepLog(), G4MultiNavigator::PrepareNavigators(), G4ITMultiNavigator::PrepareNavigators(), G4ITSteppingVerbose::PreStepVerbose(), WLSTrackingAction::PreUserTrackingAction(), G4MultiNavigator::PrintLimited(), G4PathFinder::PrintLimited(), G4ITMultiNavigator::PrintLimited(), G4ITPathFinder::PrintLimited(), G4Navigator::PrintState(), G4ITNavigator1::PrintState(), G4PropagatorInField::printStatus(), JA::PrintTree(), HadrontherapyDetectorSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), UltraPMTSD::ProcessHits(), G4PhysicalVolumeMassScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), G4ReflectionFactory::ReflectPVDivision(), G4ReflectionFactory::ReflectPVParameterised(), G4ReflectionFactory::ReflectPVPlacement(), G4ReflectionFactory::ReflectPVReplica(), G4tgbVolumeMgr::RegisterMe(), PHG4TTLDetector::RegisterPhysicalVolume(), PHG4Sector::PHG4SectorConstructor::RegisterPhysicalVolume(), ePHENIXRICH::ePHENIXRICHConstruction::RegisterPhysicalVolume(), G4PropagatorInField::ReportLoopingParticle(), G4PropagatorInField::ReportStuckParticle(), G4NavigationLogger::ReportVolumeAndIntersection(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VoxelSafety::SafetyForVoxelHeader(), G4Region::ScanVolumeTree(), G4LBLVtxDetector::SetActiveVolumes(), G4VisCommandsTouchable::SetNewValue(), G4WeightCutOffProcess::SetParallelWorld(), G4WeightWindowProcess::SetParallelWorld(), G4ParallelWorldScoringProcess::SetParallelWorld(), G4ParallelWorldProcess::SetParallelWorld(), G4IStore::SetParallelWorldVolume(), SteppingAction::SetupVolumeType(), G4WeightWindowStore::SetWorldVolume(), G4IStore::SetWorldVolume(), G4FastSimulationManagerProcess::SetWorldVolume(), G4GlobalFastSimulationManager::ShowSetup(), G4SteppingVerbose::ShowStep(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), G4GDMLRead::StripNames(), G4ErrorGeomVolumeTarget::TargetReached(), G4ITSteppingVerbose::TrackingEnded(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), PHG4RICHSteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), XrayTelSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), G4SteppingVerbose::VerboseTrack(), WLSTrajectoryPoint::WLSTrajectoryPoint(), G4VScoringMesh::WorkerConstruct(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
G4RotationMatrix * G4VPhysicalVolume::GetObjectRotation () const
Definition at line 167 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 167 of file G4VPhysicalVolume.cc
References GetRotation(), and CLHEP::HepRotation::inverse().
G4RotationMatrix G4VPhysicalVolume::GetObjectRotationValue () const
Definition at line 183 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 183 of file G4VPhysicalVolume.cc
References G4MT_rot.
Referenced by G4PhysicalVolumeModel::CreateCurrentAttValues(), export_G4VPhysicalVolume(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), and G4ReflectionFactory::ReflectPVPlacement().
G4ThreeVector G4VPhysicalVolume::GetObjectTranslation () const
Definition at line 195 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 195 of file G4VPhysicalVolume.cc
References G4MT_tx, G4MT_ty, and G4MT_tz.
Referenced by G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), G4GMocrenFileSceneHandler::AddSolid(), G4AdjointPosOnPhysVolGenerator::ComputeTransformationFromPhysVolToWorld(), GB06ParallelWorldForSlices::Construct(), export_G4VPhysicalVolume(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), G4ReflectionFactory::ReflectPVPlacement(), PHG4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLWriteStructure::TraverseVolumeTree(), and XrayFluoSteppingAction::UserSteppingAction().
virtual G4VPVParameterisation* G4VPhysicalVolume::GetParameterisation () const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, G4PVParameterised, and G4VExternalPhysicalVolume.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4SmartVoxelHeader::BuildNodes(), G4ParameterisedNavigation::ComputeSafety(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), export_G4VPhysicalVolume(), G4LogicalVolume::GetMass(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4ReflectionFactory::ReflectDaughters(), G4ReflectionFactory::ReflectPVDivision(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4Region::ScanVolumeTree(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
virtual G4int G4VPhysicalVolume::GetRegularStructureId () const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, and G4VExternalPhysicalVolume.
Referenced by G4GeometryManager::BuildOptimisations(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), DicomIntersectVolume::IsPhantomVolume(), G4EnergySplitter::IsPhantomVolume(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
virtual void G4VPhysicalVolume::GetReplicationData (EAxis & axis, G4int & nReplicas, G4double & width, G4double & offset, G4bool & consuming) const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, G4PVParameterised, and G4VExternalPhysicalVolume.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4ParameterisedNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4ReplicaNavigation::ComputeTransformation(), G4ReplicaNavigation::DistanceToOut(), G4ReplicaNavigation::Inside(), DicomIntersectVolume::IsPhantomVolume(), G4EnergySplitter::IsPhantomVolume(), G4ReflectionFactory::ReflectPVReplica(), PHG4GDMLWriteStructure::ReplicavolWrite(), G4GDMLWriteStructure::ReplicavolWrite(), and G4ASCIITreeSceneHandler::RequestPrimitives().
const G4RotationMatrix * G4VPhysicalVolume::GetRotation () const
Definition at line 152 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 152 of file G4VPhysicalVolume.cc
References G4MT_rot.
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4tgbPlaceParamCircle::ComputeTransformation(), G4LogicalVolumeModel::DescribeYourselfTo(), LXePMTHit::Draw(), G4tgbGeometryDumper::DumpPVPlacement(), G4PVPlacement::G4PVPlacement(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), GetObjectRotation(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4VoxelSafety::SafetyForVoxelNode(), G4PVReplica::TerminateWorker(), G4PVPlacement::~G4PVPlacement(), G4PVReplica::~G4PVReplica(), and G4ReplicatedSlice::~G4ReplicatedSlice().
G4RotationMatrix * G4VPhysicalVolume::GetRotation ()
Definition at line 157 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 157 of file G4VPhysicalVolume.cc
References G4MT_rot.
const G4PVManager & G4VPhysicalVolume::GetSubInstanceManager () static
Definition at line 132 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 132 of file G4VPhysicalVolume.cc
References subInstanceManager.
Referenced by G4GeometryWorkspace::G4GeometryWorkspace().
const G4ThreeVector G4VPhysicalVolume::GetTranslation () const
Definition at line 142 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 142 of file G4VPhysicalVolume.cc
References G4MT_tx, G4MT_ty, and G4MT_tz.
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4LogicalVolumeModel::DescribeYourselfTo(), LXePMTHit::Draw(), G4tgbGeometryDumper::DumpPVPlacement(), export_G4VPhysicalVolume(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4VoxelSafety::SafetyForVoxelNode(), and PHG4InttSteppingAction::UserSteppingAction().
void G4VPhysicalVolume::InitialiseWorker (G4VPhysicalVolume * pMasterObject, G4RotationMatrix * pRot, const G4ThreeVector & tlate) protected
Definition at line 104 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 104 of file G4VPhysicalVolume.cc
References SetRotation(), SetTranslation(), G4GeomSplitter< T >::SlaveCopySubInstanceArray(), and subInstanceManager.
Referenced by G4PVReplica::InitialiseWorker().
virtual G4bool G4VPhysicalVolume::IsMany () const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, and G4VExternalPhysicalVolume.
Referenced by export_G4VPhysicalVolume(), and G4ReflectionFactory::ReflectPVPlacement().
virtual G4bool G4VPhysicalVolume::IsParameterised () const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, G4VExternalPhysicalVolume, and G4PVParameterised.
Referenced by G4GDMLWrite::AddModule(), PHG4GDMLWrite::AddModule(), G4GMocrenFileSceneHandler::AddSolid(), G4tgbGeometryDumper::DumpPhysVol(), export_G4VPhysicalVolume(), G4PVParameterised::G4PVParameterised(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4Region::ScanVolumeTree(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
virtual G4bool G4VPhysicalVolume::IsRegularStructure () const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, and G4VExternalPhysicalVolume.
Referenced by G4ScoreSplittingProcess::PostStepDoIt().
virtual G4bool G4VPhysicalVolume::IsReplicated () const pure virtual
Implemented in G4PVReplica, G4PVPlacement, G4ReplicatedSlice, G4PVDivision, and G4VExternalPhysicalVolume.
Referenced by G4GDMLWrite::AddModule(), PHG4GDMLWrite::AddModule(), G4GMocrenFileSceneHandler::AddSolid(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4tgbGeometryDumper::DumpPhysVol(), export_G4VPhysicalVolume(), G4SmartVoxelHeader::G4SmartVoxelHeader(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), G4ReflectionFactory::ReflectDaughters(), G4ASCIITreeSceneHandler::RequestPrimitives(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
G4VPhysicalVolume& G4VPhysicalVolume::operator= (const G4VPhysicalVolume &) delete
G4bool G4VPhysicalVolume::operator== (const G4VPhysicalVolume & p) const inline
virtual void G4VPhysicalVolume::SetCopyNo (G4int CopyNo) pure virtual
Implemented in G4PVReplica, G4ReplicatedSlice, G4PVDivision, and G4PVPlacement.
Referenced by G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), export_G4VPhysicalVolume(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4VisCommandsTouchable::SetNewValue().
void G4VPhysicalVolume::SetLogicalVolume (G4LogicalVolume * pLogical) inline
Referenced by export_G4VPhysicalVolume(), LXeMainVolume::LXeMainVolume(), LXeWLSFiber::LXeWLSFiber(), and LXeWLSSlab::LXeWLSSlab().
void G4VPhysicalVolume::SetMotherLogical (G4LogicalVolume * pMother) inline
Referenced by G4ReplicatedSlice::CheckAndSetParameters(), export_G4VPhysicalVolume(), G4PVDivision::G4PVDivision(), G4PVParameterised::G4PVParameterised(), G4PVPlacement::G4PVPlacement(), G4PVReplica::G4PVReplica(), and G4VExternalPhysicalVolume::G4VExternalPhysicalVolume().
void G4VPhysicalVolume::SetName (const G4String & pName) inline
Referenced by G4RunManager::ConstructScoringWorlds(), export_G4VPhysicalVolume(), G4GDMLRead::GeneratePhysvolName(), G4VUserParallelWorld::GetWorld(), and G4GDMLRead::StripNames().
void G4VPhysicalVolume::SetRotation (G4RotationMatrix * pRot)
Definition at line 162 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 162 of file G4VPhysicalVolume.cc
References G4MT_rot.
Referenced by G4VDivisionParameterisation::ChangeRotMatrix(), G4PVDivision::CheckAndSetParameters(), G4ReplicatedSlice::CheckAndSetParameters(), G4PVReplica::CheckAndSetParameters(), PHG4EtaParameterization::ComputeTransformation(), PHG4EtaPhiParameterization::ComputeTransformation(), G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), B2bChamberParameterisation::ComputeTransformation(), ExN02ChamberParameterisation::ComputeTransformation(), UltraFresnelLensParameterisation::ComputeTransformation(), ExP01ChamberParameterisation::ComputeTransformation(), G02ChamberParameterisation::ComputeTransformation(), ChromosomeParameterisation::ComputeTransformation(), G4GDMLParameterisation::ComputeTransformation(), NeuronLoadDataFile::ComputeTransformation(), EICG4dRICHDetector::ConstructMe(), export_G4VPhysicalVolume(), G4PVPlacement::G4PVPlacement(), G4VPhysicalVolume(), G4PVReplica::InitialiseWorker(), and InitialiseWorker().
void G4VPhysicalVolume::SetTranslation (const G4ThreeVector & v)
Definition at line 147 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 147 of file G4VPhysicalVolume.cc
References G4MT_tx, G4MT_ty, G4MT_tz, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CML2PhantomConstruction::applyNewCentre(), PHG4InttFPHXParameterisation::ComputeTransformation(), PHG4EtaParameterization::ComputeTransformation(), PHG4EtaPhiParameterization::ComputeTransformation(), B5CellParameterisation::ComputeTransformation(), CellParameterisation::ComputeTransformation(), G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4PartialPhantomParameterisation::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), RE01CalorimeterParametrisation::ComputeTransformation(), RE01TrackerParametrisation::ComputeTransformation(), RE05CalorimeterParametrisation::ComputeTransformation(), RE05TrackerParametrisation::ComputeTransformation(), B2bChamberParameterisation::ComputeTransformation(), G4PhantomParameterisation::ComputeTransformation(), ExN02ChamberParameterisation::ComputeTransformation(), ExP01ChamberParameterisation::ComputeTransformation(), UltraFresnelLensParameterisation::ComputeTransformation(), G4ParameterisationTubsRho::ComputeTransformation(), RE04ParallelWorldParam::ComputeTransformation(), G4ParameterisationBoxX::ComputeTransformation(), G4ParameterisationParaX::ComputeTransformation(), G02ChamberParameterisation::ComputeTransformation(), G4ParameterisationConsRho::ComputeTransformation(), ChromosomeParameterisation::ComputeTransformation(), G4GDMLParameterisation::ComputeTransformation(), G4ParameterisationPolyconeRho::ComputeTransformation(), G4ParameterisationTrdX::ComputeTransformation(), G4ParameterisationPolyhedraRho::ComputeTransformation(), NeuronLoadDataFile::ComputeTransformation(), DicomNestedPhantomParameterisation::ComputeTransformation(), RE02NestedPhantomParameterisation::ComputeTransformation(), G4ReplicaNavigation::ComputeTransformation(), G4ParameterisationBoxY::ComputeTransformation(), G4ParameterisationTubsPhi::ComputeTransformation(), G4ParameterisationConsPhi::ComputeTransformation(), G4ParameterisationParaY::ComputeTransformation(), G4ParameterisationPolyconePhi::ComputeTransformation(), G4ParameterisationTrdY::ComputeTransformation(), G4ParameterisationPolyhedraPhi::ComputeTransformation(), G4ParameterisationConsZ::ComputeTransformation(), G4ParameterisationBoxZ::ComputeTransformation(), G4ParameterisationTubsZ::ComputeTransformation(), G4ParameterisationParaZ::ComputeTransformation(), G4ParameterisationPolyconeZ::ComputeTransformation(), G4ParameterisationTrdZ::ComputeTransformation(), G4ParameterisationPolyhedraZ::ComputeTransformation(), EICG4dRICHDetector::ConstructMe(), export_G4VPhysicalVolume(), G4VPhysicalVolume(), InitialiseWorker(), B5DetectorConstruction::SetArmAngle(), STCyclotronDetectorConstruction::SetFoilThickness(), GB03DetectorConstruction::SetNumberOfLayers(), RE06DetectorConstruction::SetNumberOfLayers(), RE06ParallelWorld::SetSerialGeometry(), RE06DetectorConstruction::SetSerialGeometry(), STCyclotronDetectorConstruction::SetTargetThickness(), and HadrontherapyDetectorConstruction::SetVirtualLayerPosition().
void G4VPhysicalVolume::TerminateWorker (G4VPhysicalVolume * pMasterObject) protected
Definition at line 126 of file G4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 126 of file G4VPhysicalVolume.cc
virtual EVolume G4VPhysicalVolume::VolumeType () const pure virtual
Implemented in G4PVPlacement, G4ReplicatedSlice, G4PVReplica, G4PVDivision, G4PVParameterised, and G4VExternalPhysicalVolume.
Referenced by G4LogicalVolume::AddDaughter().
Member Data Documentation
G4LogicalVolume* G4VPhysicalVolume::flmother = nullptr private
Definition at line 246 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 246 of file G4VPhysicalVolume.hh
G4LogicalVolume* G4VPhysicalVolume::flogical = nullptr private
Definition at line 242 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 242 of file G4VPhysicalVolume.hh
G4String G4VPhysicalVolume::fname private
Definition at line 245 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 245 of file G4VPhysicalVolume.hh
G4int G4VPhysicalVolume::instanceID protected
Definition at line 234 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 234 of file G4VPhysicalVolume.hh
Referenced by G4VPhysicalVolume().
G4PVData* G4VPhysicalVolume::pvdata = nullptr private
Definition at line 248 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 248 of file G4VPhysicalVolume.hh
Referenced by G4VPhysicalVolume(), and ~G4VPhysicalVolume().
G4PVManager G4VPhysicalVolume::subInstanceManager static protected
Definition at line 237 of file G4VPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 237 of file G4VPhysicalVolume.hh
Referenced by Clean(), G4VPhysicalVolume(), GetSubInstanceManager(), and InitialiseWorker().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VPhysicalVolume.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4VPhysicalVolume.cc