ECCE @ EIC Software: GIDI_settings_group Class Reference
GIDI_settings_group Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh>
Public Member Functions
GIDI_settings_group (std::string const &label="empty", int size=0)
GIDI_settings_group (std::string const &label, int length, double const *values)
GIDI_settings_group (std::string const &label, std::vector< double > const &boundaries)
GIDI_settings_group (GIDI_settings_group const &group)
GIDI_settings_group & operator= (const GIDI_settings_group &group)
~GIDI_settings_group ()
double operator[] (int const index) const
int size (void) const
int getNumberOfGroups (void) const
double const * pointer (void) const
void setFromCDoubleArray (int length, double *values)
std::string getLabel () const
int getGroupIndexFromEnergy (double energy, bool encloseOutOfRange) const
bool isLabel (std::string &label) const
void print (bool outline=false, int valuesPerLine=10) const
Private Member Functions
void initialize (std::string const &label, int size, int length, double const *values)
Private Attributes
std::string mLabel
std::vector< double > mBoundaries
Detailed Description
Definition at line 35 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 35 of file GIDI_settings.hh
Constructor & Destructor Documentation
GIDI_settings_group::GIDI_settings_group (std::string const & label = "empty", int size = 0)
Definition at line 14 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 14 of file GIDI_settings_group.cc
References initialize().
GIDI_settings_group::GIDI_settings_group (std::string const & label, int length, double const * values)
Definition at line 21 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 21 of file GIDI_settings_group.cc
References initialize().
GIDI_settings_group::GIDI_settings_group (std::string const & label, std::vector< double > const & boundaries)
Definition at line 28 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 28 of file GIDI_settings_group.cc
References initialize(), and int().
GIDI_settings_group::GIDI_settings_group (GIDI_settings_group const & group)
Definition at line 37 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 37 of file GIDI_settings_group.cc
References initialize(), mBoundaries, mLabel, and size().
GIDI_settings_group::~GIDI_settings_group ()
Definition at line 66 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 66 of file GIDI_settings_group.cc
Member Function Documentation
int GIDI_settings_group::getGroupIndexFromEnergy (double energy, bool encloseOutOfRange) const
Definition at line 72 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 72 of file GIDI_settings_group.cc
References int(), and mBoundaries.
Referenced by GIDI_settings_particle::getGroupIndexFromEnergy().
std::string GIDI_settings_group::getLabel () const inline
Definition at line 55 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 55 of file GIDI_settings.hh
References mLabel.
int GIDI_settings_group::getNumberOfGroups (void) const inline
Definition at line 51 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 51 of file GIDI_settings.hh
References mBoundaries.
Referenced by GIDI_settings_particle::getNumberOfGroups().
void GIDI_settings_group::initialize (std::string const & label, int size, int length, double const * values) private
Definition at line 44 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 44 of file GIDI_settings_group.cc
References BTOF::length, mBoundaries, and mLabel.
Referenced by GIDI_settings_group(), and operator=().
bool GIDI_settings_group::isLabel (std::string & label) const inline
Definition at line 57 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 57 of file GIDI_settings.hh
References mLabel.
GIDI_settings_group & GIDI_settings_group::operator= (const GIDI_settings_group & group)
Definition at line 57 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 57 of file GIDI_settings_group.cc
References initialize(), mBoundaries, mLabel, and size().
double GIDI_settings_group::operator[] (int const index) const inline
Definition at line 49 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 49 of file GIDI_settings.hh
References mBoundaries.
double const* GIDI_settings_group::pointer (void) const inline
Definition at line 52 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 52 of file GIDI_settings.hh
References mBoundaries.
Referenced by GIDI_settings_particle::setGroup().
void GIDI_settings_group::print (bool outline = false, int valuesPerLine = 10) const
Definition at line 100 of file GIDI_settings_group.cc.
View newest version in sPHENIX GitHub at line 100 of file GIDI_settings_group.cc
References buffer, mBoundaries, mLabel, and size().
void GIDI_settings_group::setFromCDoubleArray (int length, double * values)
int GIDI_settings_group::size (void) const inline
Definition at line 50 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 50 of file GIDI_settings.hh
References mBoundaries.
Referenced by GIDI_settings_group(), operator=(), print(), and GIDI_settings_particle::setGroup().
Member Data Documentation
std::vector<double> GIDI_settings_group::mBoundaries private
Definition at line 39 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 39 of file GIDI_settings.hh
Referenced by getGroupIndexFromEnergy(), getNumberOfGroups(), GIDI_settings_group(), initialize(), operator=(), operator[](), pointer(), print(), and size().
std::string GIDI_settings_group::mLabel private
Definition at line 38 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 38 of file GIDI_settings.hh
Referenced by getLabel(), GIDI_settings_group(), initialize(), isLabel(), operator=(), and print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/GIDI_settings_group.cc