ECCE @ EIC Software: G4NistMaterialBuilder Class Reference
G4NistMaterialBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4NistMaterialBuilder.hh>
Public Member Functions
G4NistMaterialBuilder (G4NistElementBuilder *, G4int verb=0)
~G4NistMaterialBuilder ()
G4Material * FindMaterial (const G4String &name) const
G4Material * FindOrBuildMaterial (const G4String &name, G4bool isotopes=true, G4bool warning=true)
G4Material * FindSimpleMaterial (G4int Z) const
G4Material * FindOrBuildSimpleMaterial (G4int Z, G4bool warning)
G4Material * ConstructNewMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4int > &nbAtoms, G4double dens, G4bool isotopes=true, G4State state=kStateSolid, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material * ConstructNewMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4double > &weight, G4double dens, G4bool isotopes=true, G4State state=kStateSolid, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material * ConstructNewGasMaterial (const G4String &name, const G4String &nameDB, G4double temp, G4double pres, G4bool isotopes=true)
G4Material * ConstructNewIdealGasMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4int > &nbAtoms, G4bool isotopes=true, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
void SetVerbose (G4int val)
void ListMaterials (const G4String &) const
void ListNistSimpleMaterials () const
void ListNistCompoundMaterials () const
void ListHepMaterials () const
void ListSpaceMaterials () const
void ListBioChemicalMaterials () const
const std::vector< G4String > & GetMaterialNames () const
G4double GetMeanIonisationEnergy (G4int index) const
G4double GetNominalDensity (G4int index) const
Private Member Functions
void Initialise ()
void NistSimpleMaterials ()
void NistCompoundMaterials ()
void NistCompoundMaterials2 ()
void HepAndNuclearMaterials ()
void SpaceMaterials ()
void BioChemicalMaterials ()
void AddMaterial (const G4String &nameMat, G4double dens, G4int Z=0, G4double pot=0.0, G4int ncomp=1, G4State=kStateSolid, G4bool stp=true)
void AddGas (const G4String &nameMat, G4double T, G4double P)
void AddElementByWeightFraction (G4int Z, G4double)
void AddElementByAtomCount (G4int Z, G4int)
void AddElementByWeightFraction (const G4String &name, G4double)
void AddElementByAtomCount (const G4String &name, G4int)
G4Material * BuildNistMaterial (const G4String &matname, G4bool warning)
G4Material * BuildMaterial (G4int idx)
void DumpElm (G4int) const
void DumpMix (G4int) const
Private Attributes
G4NistElementBuilder * elmBuilder
G4int verbose
G4int nMaterials
G4int nComponents
G4int nCurrent
G4int nElementary
G4int nNIST
G4int nHEP
G4int nSpace
std::vector< G4String > names
std::vector< G4String > chFormulas
std::vector< G4double > densities
std::vector< G4double > ionPotentials
std::vector< G4State > states
std::vector< G4double > fractions
std::vector< G4bool > atomCount
std::vector< G4int > components
std::vector< G4int > indexes
std::vector< G4int > elements
std::vector< G4int > matIndex
std::vector< G4bool > STP
std::vector< G4int > idxGas
std::vector< G4double > gasTemperature
std::vector< G4double > gasPressure
Detailed Description
Definition at line 69 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NistMaterialBuilder.hh
Constructor & Destructor Documentation
G4NistMaterialBuilder::G4NistMaterialBuilder (G4NistElementBuilder * eb, G4int verb = 0)
Definition at line 85 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 85 of file G4NistMaterialBuilder.cc
References Initialise().
G4NistMaterialBuilder::~G4NistMaterialBuilder ()
Definition at line 97 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 97 of file G4NistMaterialBuilder.cc
Member Function Documentation
void G4NistMaterialBuilder::AddElementByAtomCount (G4int Z, G4int nb) private
Definition at line 687 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 687 of file G4NistMaterialBuilder.cc
References AddElementByWeightFraction(), atomCount, nMaterials, and w.
Referenced by BioChemicalMaterials(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), HepAndNuclearMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), and SpaceMaterials().
void G4NistMaterialBuilder::AddElementByAtomCount (const G4String & name, G4int nb) private
Definition at line 696 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 696 of file G4NistMaterialBuilder.cc
References AddElementByWeightFraction(), atomCount, elmBuilder, G4NistElementBuilder::GetZ(), nMaterials, w, and Z.
void G4NistMaterialBuilder::AddElementByWeightFraction (G4int Z, G4double w) private
Definition at line 657 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 657 of file G4NistMaterialBuilder.cc
References atomCount, components, elements, fractions, imax, indexes, n, nComponents, nCurrent, nMaterials, and sum.
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), ConstructNewMaterial(), HepAndNuclearMaterials(), NistCompoundMaterials(), and NistCompoundMaterials2().
void G4NistMaterialBuilder::AddElementByWeightFraction (const G4String & name, G4double w) private
Definition at line 678 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 678 of file G4NistMaterialBuilder.cc
References AddElementByWeightFraction(), elmBuilder, G4NistElementBuilder::GetZ(), and Z.
void G4NistMaterialBuilder::AddGas (const G4String & nameMat, G4double T, G4double P) private
Definition at line 640 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 640 of file G4NistMaterialBuilder.cc
References G4cout, G4endl, gasPressure, gasTemperature, idxGas, names, and nMaterials.
Referenced by ConstructNewIdealGasMaterial(), ConstructNewMaterial(), and HepAndNuclearMaterials().
void G4NistMaterialBuilder::AddMaterial (const G4String & nameMat, G4double dens, G4int Z = 0, G4double pot = 0.0, G4int ncomp = 1, G4State state = kStateSolid, G4bool stp = true) private
Definition at line 457 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 457 of file G4NistMaterialBuilder.cc
References atomCount, chFormulas, CLHEP::cm3, components, densities, elements, CLHEP::eV, fractions, CLHEP::g, G4cout, G4endl, indexes, ionPotentials, matIndex, names, nComponents, nCurrent, nMaterials, states, STP, and verbose.
Referenced by BioChemicalMaterials(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), HepAndNuclearMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), and SpaceMaterials().
void G4NistMaterialBuilder::BioChemicalMaterials () private
Build biochemical materials used in G4DNA Applications. Materials are defined in bonded and unbonded forms according to the following schema: G4_MATERIAL: Molecule in its free state G4_DNA_MATERIAL: Molecule, considering atoms lost in bonding
Definition at line 1939 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 1939 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), and AddMaterial().
Referenced by Initialise().
G4Material * G4NistMaterialBuilder::BuildMaterial (G4int idx) private
Definition at line 171 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 171 of file G4NistMaterialBuilder.cc
References G4Material::AddElement(), atomCount, chFormulas, components, densities, elements, elmBuilder, FatalException, G4IonisParamMat::FindMeanExcitationEnergy(), G4NistElementBuilder::FindOrBuildElement(), fractions, G4cout, G4endl, G4Exception(), G4lrint(), gasPressure, gasTemperature, G4Material::GetIndex(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), incremental_prev_tag::idx, idxGas, indexes, ionPotentials, kStateGas, mat, matIndex, names, nMaterials, G4InuclParticleNames::nn, NTP_Temperature, G4Material::SetChemicalFormula(), G4IonisParamMat::SetMeanExcitationEnergy(), states, source.hepunit::STP_Pressure, t, verbose, and Z.
Referenced by BuildNistMaterial(), ConstructNewIdealGasMaterial(), and ConstructNewMaterial().
G4Material * G4NistMaterialBuilder::BuildNistMaterial (const G4String & matname, G4bool warning) private
Definition at line 122 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 122 of file G4NistMaterialBuilder.cc
References BuildMaterial(), G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4Material::GetMaterialTable(), mat, matIndex, names, nMaterials, and verbose.
Referenced by FindOrBuildMaterial(), and FindOrBuildSimpleMaterial().
G4Material * G4NistMaterialBuilder::ConstructNewGasMaterial (const G4String & name, const G4String & nameDB, G4double temp, G4double pres, G4bool isotopes = true)
Definition at line 347 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 347 of file G4NistMaterialBuilder.cc
References FindOrBuildMaterial(), G4cout, G4endl, G4Material::GetDensity(), G4Material::GetPressure(), G4Material::GetState(), G4Material::GetTemperature(), kStateGas, mat, and verbose.
Referenced by G4NistManager::ConstructNewGasMaterial().
G4Material * G4NistMaterialBuilder::ConstructNewIdealGasMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4int > & nbAtoms, G4bool isotopes = true, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 394 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 394 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddGas(), AddMaterial(), CLHEP::amu_c2, CLHEP::Avogadro, BuildMaterial(), elmBuilder, FindOrBuildMaterial(), G4cout, G4endl, G4NistElementBuilder::GetAtomicMassAmu(), G4NistElementBuilder::GetZ(), CLHEP::k_Boltzmann, kStateGas, mat, nMaterials, NTP_Temperature, CLHEP::STP_Pressure, and Z.
Referenced by G4NistManager::ConstructNewIdealGasMaterial().
G4Material * G4NistMaterialBuilder::ConstructNewMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4int > & nbAtoms, G4double dens, G4bool isotopes = true, G4State state = kStateSolid, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 246 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 246 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddGas(), AddMaterial(), BuildMaterial(), CLHEP::cm3, elmBuilder, FindOrBuildMaterial(), CLHEP::g, G4cout, G4endl, G4NistElementBuilder::GetZ(), kStateGas, mat, nMaterials, NTP_Temperature, and CLHEP::STP_Pressure.
Referenced by G4NistManager::ConstructNewMaterial().
G4Material * G4NistMaterialBuilder::ConstructNewMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4double > & weight, G4double dens, G4bool isotopes = true, G4State state = kStateSolid, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 297 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 297 of file G4NistMaterialBuilder.cc
References AddElementByWeightFraction(), AddGas(), AddMaterial(), BuildMaterial(), CLHEP::cm3, elmBuilder, FindOrBuildMaterial(), CLHEP::g, G4cout, G4endl, G4NistElementBuilder::GetZ(), kStateGas, mat, nMaterials, NTP_Temperature, and CLHEP::STP_Pressure.
void G4NistMaterialBuilder::DumpElm (G4int i) const private
Definition at line 607 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 607 of file G4NistMaterialBuilder.cc
References cm3, densities, eV, Acts::UnitConstants::g, G4cout, G4endl, ionPotentials, and names.
Referenced by ListNistSimpleMaterials().
void G4NistMaterialBuilder::DumpMix (G4int i) const private
Definition at line 618 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 618 of file G4NistMaterialBuilder.cc
References chFormulas, cm3, components, densities, elements, eV, fractions, Acts::UnitConstants::g, G4cout, G4endl, imax, indexes, ionPotentials, and names.
Referenced by ListBioChemicalMaterials(), ListHepMaterials(), ListNistCompoundMaterials(), and ListSpaceMaterials().
G4Material * G4NistMaterialBuilder::FindMaterial (const G4String & name) const inline
Definition at line 247 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 247 of file G4NistMaterialBuilder.hh
References G4Material::GetMaterialTable().
Referenced by G4NistManager::FindMaterial(), FindOrBuildMaterial(), and FindSimpleMaterial().
G4Material * G4NistMaterialBuilder::FindOrBuildMaterial (const G4String & name, G4bool isotopes = true, G4bool warning = true)
Definition at line 102 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 102 of file G4NistMaterialBuilder.cc
References BuildNistMaterial(), FindMaterial(), G4cout, G4endl, mat, and verbose.
Referenced by ConstructNewGasMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), and G4NistManager::FindOrBuildMaterial().
G4Material * G4NistMaterialBuilder::FindOrBuildSimpleMaterial (G4int Z, G4bool warning)
Definition at line 160 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 160 of file G4NistMaterialBuilder.cc
References BuildNistMaterial(), FindSimpleMaterial(), mat, and names.
Referenced by G4NistManager::FindOrBuildSimpleMaterial().
G4Material * G4NistMaterialBuilder::FindSimpleMaterial (G4int Z) const inline
Definition at line 262 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 262 of file G4NistMaterialBuilder.hh
References FindMaterial(), names, and nElementary.
Referenced by FindOrBuildSimpleMaterial(), and G4NistManager::FindSimpleMaterial().
const std::vector< G4String > & G4NistMaterialBuilder::GetMaterialNames () const inline
Definition at line 229 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 229 of file G4NistMaterialBuilder.hh
References names.
Referenced by G4NistManager::GetNistMaterialNames().
G4double G4NistMaterialBuilder::GetMeanIonisationEnergy (G4int index) const inline
Definition at line 235 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 235 of file G4NistMaterialBuilder.hh
References ionPotentials, and nMaterials.
Referenced by G4NistManager::GetMeanIonisationEnergy().
G4double G4NistMaterialBuilder::GetNominalDensity (G4int index) const inline
Definition at line 241 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 241 of file G4NistMaterialBuilder.hh
References densities, and nMaterials.
Referenced by G4NistManager::GetNominalDensity().
void G4NistMaterialBuilder::HepAndNuclearMaterials () private
Definition at line 1846 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 1846 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddElementByWeightFraction(), AddGas(), AddMaterial(), chFormulas, cm3, e, Acts::UnitConstants::g, hep_pascal, kelvin, kStateGas, kStateLiquid, nHEP, nMaterials, and source.hepunit::universe_mean_density.
Referenced by Initialise().
void G4NistMaterialBuilder::Initialise () private
Definition at line 708 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 708 of file G4NistMaterialBuilder.cc
References BioChemicalMaterials(), G4cout, G4endl, HepAndNuclearMaterials(), ListMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), SpaceMaterials(), and verbose.
Referenced by G4NistMaterialBuilder().
void G4NistMaterialBuilder::ListBioChemicalMaterials () const
Definition at line 594 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 594 of file G4NistMaterialBuilder.cc
References DumpMix(), G4cout, G4endl, nMaterials, and nSpace.
Referenced by ListMaterials().
void G4NistMaterialBuilder::ListHepMaterials () const
Definition at line 570 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 570 of file G4NistMaterialBuilder.cc
References DumpMix(), G4cout, G4endl, nHEP, and nNIST.
Referenced by ListMaterials().
void G4NistMaterialBuilder::ListMaterials (const G4String & mnam) const
Definition at line 522 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 522 of file G4NistMaterialBuilder.cc
References G4cout, G4endl, ListBioChemicalMaterials(), ListHepMaterials(), ListNistCompoundMaterials(), ListNistSimpleMaterials(), and ListSpaceMaterials().
Referenced by Initialise(), and G4NistManager::ListMaterials().
void G4NistMaterialBuilder::ListNistCompoundMaterials () const
Definition at line 557 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 557 of file G4NistMaterialBuilder.cc
References DumpMix(), G4cout, G4endl, nElementary, and nNIST.
Referenced by ListMaterials().
void G4NistMaterialBuilder::ListNistSimpleMaterials () const
Definition at line 545 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 545 of file G4NistMaterialBuilder.cc
References DumpElm(), G4cout, G4endl, and nElementary.
Referenced by ListMaterials().
void G4NistMaterialBuilder::ListSpaceMaterials () const
Definition at line 582 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 582 of file G4NistMaterialBuilder.cc
References DumpMix(), G4cout, G4endl, nHEP, and nSpace.
Referenced by ListMaterials().
void G4NistMaterialBuilder::NistCompoundMaterials () private
Definition at line 838 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 838 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddElementByWeightFraction(), AddMaterial(), chFormulas, e, kStateGas, and nMaterials.
Referenced by Initialise().
void G4NistMaterialBuilder::NistCompoundMaterials2 () private
Definition at line 1343 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 1343 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddElementByWeightFraction(), AddMaterial(), chFormulas, kStateGas, nMaterials, and nNIST.
Referenced by Initialise().
void G4NistMaterialBuilder::NistSimpleMaterials () private
Definition at line 725 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 725 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddMaterial(), chFormulas, e, kStateGas, nElementary, and nMaterials.
Referenced by Initialise().
void G4NistMaterialBuilder::SetVerbose (G4int val)
Definition at line 514 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 514 of file G4NistMaterialBuilder.cc
References elmBuilder, G4NistElementBuilder::SetVerbose(), and verbose.
Referenced by G4NistManager::SetVerbose().
void G4NistMaterialBuilder::SpaceMaterials () private
Definition at line 1907 of file G4NistMaterialBuilder.cc.
View newest version in sPHENIX GitHub at line 1907 of file G4NistMaterialBuilder.cc
References AddElementByAtomCount(), AddMaterial(), nMaterials, and nSpace.
Referenced by Initialise().
Member Data Documentation
std::vector<G4bool> G4NistMaterialBuilder::atomCount private
Definition at line 211 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 211 of file G4NistMaterialBuilder.hh
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), AddMaterial(), and BuildMaterial().
std::vector<G4String> G4NistMaterialBuilder::chFormulas private
Definition at line 205 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 205 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial(), BuildMaterial(), DumpMix(), HepAndNuclearMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), and NistSimpleMaterials().
std::vector<G4int> G4NistMaterialBuilder::components private
Definition at line 212 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 212 of file G4NistMaterialBuilder.hh
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
std::vector<G4double> G4NistMaterialBuilder::densities private
Definition at line 207 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 207 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial(), BuildMaterial(), DumpElm(), DumpMix(), and GetNominalDensity().
std::vector<G4int> G4NistMaterialBuilder::elements private
Definition at line 214 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 214 of file G4NistMaterialBuilder.hh
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
G4NistElementBuilder* G4NistMaterialBuilder::elmBuilder private
Definition at line 193 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 193 of file G4NistMaterialBuilder.hh
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), BuildMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), and SetVerbose().
std::vector<G4double> G4NistMaterialBuilder::fractions private
Definition at line 210 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 210 of file G4NistMaterialBuilder.hh
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
std::vector<G4double> G4NistMaterialBuilder::gasPressure private
Definition at line 220 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 220 of file G4NistMaterialBuilder.hh
Referenced by AddGas(), and BuildMaterial().
std::vector<G4double> G4NistMaterialBuilder::gasTemperature private
Definition at line 219 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 219 of file G4NistMaterialBuilder.hh
Referenced by AddGas(), and BuildMaterial().
std::vector<G4int> G4NistMaterialBuilder::idxGas private
Definition at line 218 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 218 of file G4NistMaterialBuilder.hh
Referenced by AddGas(), and BuildMaterial().
std::vector<G4int> G4NistMaterialBuilder::indexes private
Definition at line 213 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 213 of file G4NistMaterialBuilder.hh
Referenced by AddElementByWeightFraction(), AddMaterial(), BuildMaterial(), and DumpMix().
std::vector<G4double> G4NistMaterialBuilder::ionPotentials private
Definition at line 208 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 208 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial(), BuildMaterial(), DumpElm(), DumpMix(), and GetMeanIonisationEnergy().
std::vector<G4int> G4NistMaterialBuilder::matIndex private
Definition at line 215 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 215 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial(), BuildMaterial(), and BuildNistMaterial().
std::vector<G4String> G4NistMaterialBuilder::names private
Definition at line 204 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 204 of file G4NistMaterialBuilder.hh
Referenced by AddGas(), AddMaterial(), BuildMaterial(), BuildNistMaterial(), DumpElm(), DumpMix(), FindOrBuildSimpleMaterial(), FindSimpleMaterial(), and GetMaterialNames().
G4int G4NistMaterialBuilder::nComponents private
Definition at line 197 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 197 of file G4NistMaterialBuilder.hh
Referenced by AddElementByWeightFraction(), and AddMaterial().
G4int G4NistMaterialBuilder::nCurrent private
Definition at line 198 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 198 of file G4NistMaterialBuilder.hh
Referenced by AddElementByWeightFraction(), and AddMaterial().
G4int G4NistMaterialBuilder::nElementary private
Definition at line 199 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 199 of file G4NistMaterialBuilder.hh
Referenced by FindSimpleMaterial(), ListNistCompoundMaterials(), ListNistSimpleMaterials(), and NistSimpleMaterials().
G4int G4NistMaterialBuilder::nHEP private
Definition at line 201 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 201 of file G4NistMaterialBuilder.hh
Referenced by HepAndNuclearMaterials(), ListHepMaterials(), and ListSpaceMaterials().
G4int G4NistMaterialBuilder::nMaterials private
Definition at line 196 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 196 of file G4NistMaterialBuilder.hh
Referenced by AddElementByAtomCount(), AddElementByWeightFraction(), AddGas(), AddMaterial(), BuildMaterial(), BuildNistMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), GetMeanIonisationEnergy(), GetNominalDensity(), HepAndNuclearMaterials(), ListBioChemicalMaterials(), NistCompoundMaterials(), NistCompoundMaterials2(), NistSimpleMaterials(), and SpaceMaterials().
G4int G4NistMaterialBuilder::nNIST private
Definition at line 200 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 200 of file G4NistMaterialBuilder.hh
Referenced by ListHepMaterials(), ListNistCompoundMaterials(), and NistCompoundMaterials2().
G4int G4NistMaterialBuilder::nSpace private
Definition at line 202 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 202 of file G4NistMaterialBuilder.hh
Referenced by ListBioChemicalMaterials(), ListSpaceMaterials(), and SpaceMaterials().
std::vector<G4State> G4NistMaterialBuilder::states private
Definition at line 209 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 209 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial(), and BuildMaterial().
std::vector<G4bool> G4NistMaterialBuilder::STP private
Definition at line 216 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 216 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial().
G4int G4NistMaterialBuilder::verbose private
Definition at line 195 of file G4NistMaterialBuilder.hh.
View newest version in sPHENIX GitHub at line 195 of file G4NistMaterialBuilder.hh
Referenced by AddMaterial(), BuildMaterial(), BuildNistMaterial(), ConstructNewGasMaterial(), FindOrBuildMaterial(), Initialise(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4NistMaterialBuilder.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4NistMaterialBuilder.cc