ECCE @ EIC Software: G4StatMFChannel Class Reference
G4StatMFChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFChannel.hh>
Classes
struct DeleteFragment
Public Member Functions
G4StatMFChannel ()
~G4StatMFChannel ()
void CreateFragment (G4int A, G4int Z)
size_t GetMultiplicity (void)
G4bool CheckFragments (void)
G4double GetFragmentsCoulombEnergy (void)
G4double GetFragmentsEnergy (G4double T) const
G4FragmentVector * GetFragments (G4int anA, G4int anZ, G4double T)
Private Member Functions
G4StatMFChannel (const G4StatMFChannel &right)
G4StatMFChannel & operator= (const G4StatMFChannel &right)
G4bool operator== (const G4StatMFChannel &right) const
G4bool operator!= (const G4StatMFChannel &right) const
void CoulombImpulse (G4int anA, G4int anZ, G4double T)
void PlaceFragments (G4int anA)
void SolveEqOfMotion (G4int anA, G4int anZ, G4double T)
void FragmentsMomenta (G4int NF, G4int idx, G4double T)
G4ThreeVector RotateMomentum (G4ThreeVector Pa, G4ThreeVector V, G4ThreeVector P)
Private Attributes
std::deque< G4StatMFFragment * > _theFragments
G4int _NumOfNeutralFragments
G4int _NumOfChargedFragments
Detailed Description
Definition at line 40 of file G4StatMFChannel.hh.
View newest version in sPHENIX GitHub at line 40 of file G4StatMFChannel.hh
Constructor & Destructor Documentation
G4StatMFChannel::G4StatMFChannel ()
Definition at line 46 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4StatMFChannel.cc
G4StatMFChannel::~G4StatMFChannel ()
Definition at line 51 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4StatMFChannel.cc
References _theFragments.
G4StatMFChannel::G4StatMFChannel (const G4StatMFChannel & right) private
Member Function Documentation
G4bool G4StatMFChannel::CheckFragments (void)
Definition at line 59 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 59 of file G4StatMFChannel.cc
References _theFragments, A(), and Z.
Referenced by G4StatMF::BreakItUp().
void G4StatMFChannel::CoulombImpulse (G4int anA, G4int anZ, G4double T) private
Definition at line 136 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 136 of file G4StatMFChannel.cc
References _NumOfChargedFragments, FragmentsMomenta(), PlaceFragments(), and SolveEqOfMotion().
Referenced by GetFragments().
void G4StatMFChannel::CreateFragment (G4int A, G4int Z)
Definition at line 72 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4StatMFChannel.cc
References _NumOfChargedFragments, _NumOfNeutralFragments, and _theFragments.
Referenced by G4StatMFMicroCanonical::ChooseAandZ(), G4StatMFMicroPartition::ChooseZ(), and G4StatMFMacroCanonical::ChooseZ().
void G4StatMFChannel::FragmentsMomenta (G4int NF, G4int idx, G4double T) private
Definition at line 211 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 211 of file G4StatMFChannel.cc
References _theFragments, b, E, G4Exp(), G4RandomDirection(), G4UniformRand, H, incremental_prev_tag::idx, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), P1, P2, RotateMomentum(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), T, and twopi.
Referenced by CoulombImpulse(), and GetFragments().
G4FragmentVector * G4StatMFChannel::GetFragments (G4int anA, G4int anZ, G4double T)
Definition at line 118 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 118 of file G4StatMFChannel.cc
References _NumOfChargedFragments, _NumOfNeutralFragments, _theFragments, CoulombImpulse(), and FragmentsMomenta().
G4double G4StatMFChannel::GetFragmentsCoulombEnergy (void)
Definition at line 88 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 88 of file G4StatMFChannel.cc
References _theFragments.
Referenced by SolveEqOfMotion().
G4double G4StatMFChannel::GetFragmentsEnergy (G4double T) const
Definition at line 104 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 104 of file G4StatMFChannel.cc
References _theFragments.
Referenced by G4StatMF::CalcEnergy().
size_t G4StatMFChannel::GetMultiplicity (void) inline
Definition at line 64 of file G4StatMFChannel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4StatMFChannel.hh
References _theFragments.
Referenced by G4StatMF::BreakItUp().
G4bool G4StatMFChannel::operator!= (const G4StatMFChannel & right) const private
G4StatMFChannel& G4StatMFChannel::operator= (const G4StatMFChannel & right) private
G4bool G4StatMFChannel::operator== (const G4StatMFChannel & right) const private
void G4StatMFChannel::PlaceFragments (G4int anA) private
Definition at line 155 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 155 of file G4StatMFChannel.cc
References _theFragments, G4Pow::A13(), G4RandomDirection(), G4UniformRand, G4Pow::GetInstance(), G4StatMFParameters::Getr0(), CLHEP::Hep3Vector::mag2(), Acts::IntegrationTest::R, and G4Pow::Z13().
Referenced by CoulombImpulse().
G4ThreeVector G4StatMFChannel::RotateMomentum (G4ThreeVector Pa, G4ThreeVector V, G4ThreeVector P) private
Definition at line 429 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 429 of file G4StatMFChannel.cc
References CLHEP::Hep3Vector::cross(), N, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by FragmentsMomenta().
void G4StatMFChannel::SolveEqOfMotion (G4int anA, G4int anZ, G4double T) private
Definition at line 340 of file G4StatMFChannel.cc.
View newest version in sPHENIX GitHub at line 340 of file G4StatMFChannel.cc
References _NumOfChargedFragments, _theFragments, G4Pow::A13(), source.hepunit::elm_coupling, G4INCL::Eta, GetFragmentsCoulombEnergy(), G4Pow::GetInstance(), G4StatMFParameters::GetKappaCoulomb(), G4StatMFParameters::Getr0(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::Hep3Vector::set(), T, and G4Pow::Z13().
Referenced by CoulombImpulse().
Member Data Documentation
G4int G4StatMFChannel::_NumOfChargedFragments private
Definition at line 99 of file G4StatMFChannel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4StatMFChannel.hh
Referenced by CoulombImpulse(), CreateFragment(), GetFragments(), and SolveEqOfMotion().
G4int G4StatMFChannel::_NumOfNeutralFragments private
Definition at line 97 of file G4StatMFChannel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4StatMFChannel.hh
Referenced by CreateFragment(), and GetFragments().
std::deque<G4StatMFFragment*> G4StatMFChannel::_theFragments private
Definition at line 95 of file G4StatMFChannel.hh.
View newest version in sPHENIX GitHub at line 95 of file G4StatMFChannel.hh
Referenced by CheckFragments(), CreateFragment(), FragmentsMomenta(), GetFragments(), GetFragmentsCoulombEnergy(), GetFragmentsEnergy(), GetMultiplicity(), PlaceFragments(), SolveEqOfMotion(), and ~G4StatMFChannel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFChannel.cc