ECCE @ EIC Software: G4ThermalNeutrons Class Reference
G4ThermalNeutrons Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_elastic/include/G4ThermalNeutrons.hh>
Public Member Functions
G4ThermalNeutrons (G4int ver=1)
virtual ~G4ThermalNeutrons ()
void ConstructProcess () override
Public Member Functions inherited from G4VHadronPhysics
G4VHadronPhysics (const G4String &name="hInelastic", G4int verbose=0)
virtual ~G4VHadronPhysics ()
virtual void ConstructParticle ()
G4HadronicInteraction * BuildModel (G4VHadronModelBuilder *, G4double emin, G4double emax)
G4HadronicInteraction * NewModel (G4HadronicInteraction *, G4double emin, G4double emax)
void AddInelasticCrossSection (const G4String &, G4VCrossSectionDataSet *)
void AddInelasticCrossSection (const G4ParticleDefinition *, G4VCrossSectionDataSet *)
void AddElasticCrossSection (const G4String &, G4VCrossSectionDataSet *)
void AddElasticCrossSection (const G4ParticleDefinition *, G4VCrossSectionDataSet *)
void AddCaptureCrossSection (G4VCrossSectionDataSet *)
void AddFissionCrossSection (G4VCrossSectionDataSet *)
G4CrossSectionInelastic * InelasticXS (const G4String &componentName)
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Attributes
G4int verbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VHadronPhysics
G4HadronicProcess * FindInelasticProcess (const G4String &)
G4HadronicProcess * FindInelasticProcess (const G4ParticleDefinition *)
G4HadronicProcess * FindElasticProcess (const G4String &)
G4HadronicProcess * FindElasticProcess (const G4ParticleDefinition *)
G4HadronicProcess * FindCaptureProcess ()
G4HadronicProcess * FindFissionProcess ()
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 45 of file G4ThermalNeutrons.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ThermalNeutrons.hh
Constructor & Destructor Documentation
G4ThermalNeutrons::G4ThermalNeutrons (G4int ver = 1) explicit
Definition at line 51 of file G4ThermalNeutrons.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ThermalNeutrons.cc
G4ThermalNeutrons::~G4ThermalNeutrons () virtual
Definition at line 55 of file G4ThermalNeutrons.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ThermalNeutrons.cc
Member Function Documentation
void G4ThermalNeutrons::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 57 of file G4ThermalNeutrons.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ThermalNeutrons.cc
References G4HadronicProcess::AddDataSet(), CLHEP::eV, G4VHadronPhysics::FindElasticProcess(), G4cout, G4endl, G4HadronicProcess::GetHadronicInteractionList(), G4VPhysicsConstructor::GetPhysicsName(), G4Neutron::Neutron(), part, G4HadronicProcess::RegisterMe(), and verbose.
Member Data Documentation
G4int G4ThermalNeutrons::verbose private
Definition at line 54 of file G4ThermalNeutrons.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ThermalNeutrons.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_elastic/include/G4ThermalNeutrons.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_elastic/src/G4ThermalNeutrons.cc