ECCE @ EIC Software: G4BogackiShampine23 Class Reference
G4BogackiShampine23 Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4BogackiShampine23.hh>
Public Member Functions
G4BogackiShampine23 (G4EquationOfMotion *EqRhs, G4int numberOfVariables=6)
virtual void Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[]) override
void Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[], G4double dydxOutput[])
G4BogackiShampine23 (const G4BogackiShampine23 &)=delete
G4BogackiShampine23 & operator= (const G4BogackiShampine23 &)=delete
virtual G4double DistChord () const override
virtual G4int IntegratorOrder () const override
Public Member Functions inherited from G4MagIntegratorStepper
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, G4bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
G4MagIntegratorStepper (const G4MagIntegratorStepper &)=delete
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)=delete
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
G4bool IsFSAL () const
Private Member Functions
void makeStep (const G4double yInput[], const G4double dydx[], const G4double hstep, G4double yOutput[], G4double *dydxOutput=nullptr, G4double *yError=nullptr) const
Private Attributes
G4double fyIn [G4FieldTrack::ncompSVEC]
G4double fdydx [G4FieldTrack::ncompSVEC]
G4double fyOut [G4FieldTrack::ncompSVEC]
G4double fdydxOut [G4FieldTrack::ncompSVEC]
G4double fhstep = -1.0
Additional Inherited Members
Protected Member Functions inherited from G4MagIntegratorStepper
void SetIntegrationOrder (G4int order)
void SetFSAL (G4bool flag=true)
Detailed Description
Definition at line 50 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 50 of file G4BogackiShampine23.hh
Constructor & Destructor Documentation
G4BogackiShampine23::G4BogackiShampine23 (G4EquationOfMotion * EqRhs, G4int numberOfVariables = 6)
Definition at line 55 of file G4BogackiShampine23.cc.
View newest version in sPHENIX GitHub at line 55 of file G4BogackiShampine23.cc
References G4MagIntegratorStepper::SetFSAL(), and G4MagIntegratorStepper::SetIntegrationOrder().
G4BogackiShampine23::G4BogackiShampine23 (const G4BogackiShampine23 &) delete
Member Function Documentation
G4double G4BogackiShampine23::DistChord () const override virtual
Implements G4MagIntegratorStepper.
Definition at line 148 of file G4BogackiShampine23.cc.
View newest version in sPHENIX GitHub at line 148 of file G4BogackiShampine23.cc
References G4LineSection::Distline(), fdydx, fhstep, fyIn, fyOut, makeStep(), field_utils::makeVector(), and G4FieldTrack::ncompSVEC.
virtual G4int G4BogackiShampine23::IntegratorOrder () const inline override virtual
Implements G4MagIntegratorStepper.
Definition at line 74 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 74 of file G4BogackiShampine23.hh
void G4BogackiShampine23::makeStep (const G4double yInput[], const G4double dydx[], const G4double hstep, G4double yOutput[], G4double * dydxOutput = nullptr, G4double * yError = nullptr) const private
Definition at line 63 of file G4BogackiShampine23.cc.
View newest version in sPHENIX GitHub at line 63 of file G4BogackiShampine23.cc
References ak2, G4MagIntegratorStepper::GetNumberOfStateVariables(), G4MagIntegratorStepper::GetNumberOfVariables(), G4FieldTrack::ncompSVEC, and G4MagIntegratorStepper::RightHandSide().
Referenced by DistChord(), and Stepper().
G4BogackiShampine23& G4BogackiShampine23::operator= (const G4BogackiShampine23 &) delete
void G4BogackiShampine23::Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[]) override virtual
Implements G4MagIntegratorStepper.
Definition at line 116 of file G4BogackiShampine23.cc.
View newest version in sPHENIX GitHub at line 116 of file G4BogackiShampine23.cc
References field_utils::copy(), fdydx, fdydxOut, fhstep, fyIn, fyOut, and makeStep().
void G4BogackiShampine23::Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[], G4double dydxOutput[])
Definition at line 131 of file G4BogackiShampine23.cc.
View newest version in sPHENIX GitHub at line 131 of file G4BogackiShampine23.cc
References field_utils::copy(), fdydx, fdydxOut, fhstep, fyIn, fyOut, and makeStep().
Member Data Documentation
G4double G4BogackiShampine23::fdydx[G4FieldTrack::ncompSVEC] private
Definition at line 85 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BogackiShampine23.hh
Referenced by DistChord(), and Stepper().
G4double G4BogackiShampine23::fdydxOut[G4FieldTrack::ncompSVEC] private
Definition at line 85 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BogackiShampine23.hh
Referenced by Stepper().
G4double G4BogackiShampine23::fhstep = -1.0 private
Definition at line 89 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BogackiShampine23.hh
Referenced by DistChord(), and Stepper().
G4double G4BogackiShampine23::fyIn[G4FieldTrack::ncompSVEC] private
Definition at line 85 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BogackiShampine23.hh
Referenced by DistChord(), and Stepper().
G4double G4BogackiShampine23::fyOut[G4FieldTrack::ncompSVEC] private
Definition at line 85 of file G4BogackiShampine23.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BogackiShampine23.hh
Referenced by DistChord(), and Stepper().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4BogackiShampine23.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4BogackiShampine23.cc