ECCE @ EIC Software: XrayFluoSiLiDetectorType Class Reference
XrayFluoSiLiDetectorType Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoSiLiDetectorType.hh>
Public Member Functions
~XrayFluoSiLiDetectorType ()
G4String GetDetectorMaterial ()
G4double ResponseFunction (G4double)
G4double GetInfData (G4double, G4double, G4int)
G4double GetSupData (G4double, G4double, G4int)
void LoadResponseData (G4String)
void LoadEfficiencyData (G4String)
Public Member Functions inherited from XrayFluoVDetectorType
virtual ~XrayFluoVDetectorType ()
Static Public Member Functions
static XrayFluoSiLiDetectorType * GetInstance ()
Private Member Functions
XrayFluoSiLiDetectorType ()
Private Attributes
G4String detectorMaterial
const XrayFluoDataSet * efficiencySet
G4VDataSetAlgorithm * interpolation4
std::map< G4int, G4DataVector
*, std::less< G4int > > energyMap
std::map< G4int, G4DataVector
*, std::less< G4int > > dataMap
Static Private Attributes
static XrayFluoSiLiDetectorType * instance = 0
Additional Inherited Members
Protected Member Functions inherited from XrayFluoVDetectorType
XrayFluoVDetectorType ()
Detailed Description
Definition at line 48 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 48 of file XrayFluoSiLiDetectorType.hh
Constructor & Destructor Documentation
XrayFluoSiLiDetectorType::~XrayFluoSiLiDetectorType ()
Definition at line 57 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 57 of file XrayFluoSiLiDetectorType.cc
References dataMap, energyMap, interpolation4, and pos().
XrayFluoSiLiDetectorType::XrayFluoSiLiDetectorType () private
Definition at line 48 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 48 of file XrayFluoSiLiDetectorType.cc
References LoadEfficiencyData(), and LoadResponseData().
Referenced by GetInstance().
Member Function Documentation
G4String XrayFluoSiLiDetectorType::GetDetectorMaterial () virtual
Implements XrayFluoVDetectorType.
Definition at line 77 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 77 of file XrayFluoSiLiDetectorType.cc
References detectorMaterial.
G4double XrayFluoSiLiDetectorType::GetInfData (G4double , G4double random, G4int posIndex) virtual
Implements XrayFluoVDetectorType.
Definition at line 200 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 200 of file XrayFluoSiLiDetectorType.cc
References dataMap, energyMap, pos(), and Z.
Referenced by ResponseFunction().
XrayFluoSiLiDetectorType * XrayFluoSiLiDetectorType::GetInstance (void) static
Definition at line 84 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 84 of file XrayFluoSiLiDetectorType.cc
References instance, and XrayFluoSiLiDetectorType().
Referenced by XrayFluoPlaneDetectorConstruction::SetDetectorType(), XrayFluoMercuryDetectorConstruction::SetDetectorType(), and XrayFluoDetectorConstruction::SetDetectorType().
G4double XrayFluoSiLiDetectorType::GetSupData (G4double , G4double random, G4int posIndex) virtual
Implements XrayFluoVDetectorType.
Definition at line 259 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 259 of file XrayFluoSiLiDetectorType.cc
References dataMap, energyMap, pos(), and Z.
Referenced by ResponseFunction().
void XrayFluoSiLiDetectorType::LoadEfficiencyData (G4String fileName) virtual
Implements XrayFluoVDetectorType.
Definition at line 398 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 398 of file XrayFluoSiLiDetectorType.cc
References efficiencySet, interpolation4, and keV.
Referenced by XrayFluoSiLiDetectorType().
void XrayFluoSiLiDetectorType::LoadResponseData (G4String fileName) virtual
Implements XrayFluoVDetectorType.
Definition at line 309 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 309 of file XrayFluoSiLiDetectorType.cc
References a, dataMap, e, energyMap, FatalException, file, G4Exception(), k, keV, and Z.
Referenced by XrayFluoSiLiDetectorType().
G4double XrayFluoSiLiDetectorType::ResponseFunction (G4double energy) virtual
Implements XrayFluoVDetectorType.
Definition at line 96 of file XrayFluoSiLiDetectorType.cc.
View newest version in sPHENIX GitHub at line 96 of file XrayFluoSiLiDetectorType.cc
References efficiencySet, XrayFluoDataSet::FindValue(), G4UniformRand, GetInfData(), GetSupData(), and keV.
Member Data Documentation
std::map<G4int,G4DataVector*,std::less<G4int> > XrayFluoSiLiDetectorType::dataMap private
Definition at line 96 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 96 of file XrayFluoSiLiDetectorType.hh
Referenced by GetInfData(), GetSupData(), LoadResponseData(), and ~XrayFluoSiLiDetectorType().
G4String XrayFluoSiLiDetectorType::detectorMaterial private
Definition at line 83 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 83 of file XrayFluoSiLiDetectorType.hh
Referenced by GetDetectorMaterial().
const XrayFluoDataSet* XrayFluoSiLiDetectorType::efficiencySet private
Definition at line 86 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoSiLiDetectorType.hh
Referenced by LoadEfficiencyData(), and ResponseFunction().
std::map<G4int,G4DataVector*,std::less<G4int> > XrayFluoSiLiDetectorType::energyMap private
Definition at line 92 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 92 of file XrayFluoSiLiDetectorType.hh
Referenced by GetInfData(), GetSupData(), LoadResponseData(), and ~XrayFluoSiLiDetectorType().
XrayFluoSiLiDetectorType * XrayFluoSiLiDetectorType::instance = 0 static private
Definition at line 81 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 81 of file XrayFluoSiLiDetectorType.hh
Referenced by GetInstance().
G4VDataSetAlgorithm* XrayFluoSiLiDetectorType::interpolation4 private
Definition at line 88 of file XrayFluoSiLiDetectorType.hh.
View newest version in sPHENIX GitHub at line 88 of file XrayFluoSiLiDetectorType.hh
Referenced by LoadEfficiencyData(), and ~XrayFluoSiLiDetectorType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoSiLiDetectorType.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoSiLiDetectorType.cc