ECCE @ EIC Software: G4ChipsKaonZeroElasticXS Class Reference
G4ChipsKaonZeroElasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonZeroElasticXS.hh>
Public Member Functions
G4ChipsKaonZeroElasticXS ()
~G4ChipsKaonZeroElasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Attributes
G4ChipsKaonMinusElasticXS * theKMinusCS
G4ChipsKaonPlusElasticXS * theKPlusCS
G4double * lastLEN
G4double * lastHEN
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 49 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ChipsKaonZeroElasticXS.hh
Constructor & Destructor Documentation
G4ChipsKaonZeroElasticXS::G4ChipsKaonZeroElasticXS ()
Definition at line 56 of file G4ChipsKaonZeroElasticXS.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ChipsKaonZeroElasticXS.cc
References G4ChipsKaonPlusElasticXS::Default_Name(), G4ChipsKaonMinusElasticXS::Default_Name(), G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4CrossSectionDataSetRegistry::Instance(), lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, theKMinusCS, and theKPlusCS.
G4ChipsKaonZeroElasticXS::~G4ChipsKaonZeroElasticXS ()
Definition at line 73 of file G4ChipsKaonZeroElasticXS.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ChipsKaonZeroElasticXS.cc
Member Function Documentation
void G4ChipsKaonZeroElasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 78 of file G4ChipsKaonZeroElasticXS.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ChipsKaonZeroElasticXS.cc
static const char* G4ChipsKaonZeroElasticXS::Default_Name () inline static
Definition at line 59 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ChipsKaonZeroElasticXS.hh
Referenced by LBE::ConstructHad(), and G4ChipsComponentXS::G4ChipsComponentXS().
G4double G4ChipsKaonZeroElasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Definition at line 109 of file G4ChipsKaonZeroElasticXS.cc.
View newest version in sPHENIX GitHub at line 109 of file G4ChipsKaonZeroElasticXS.cc
References G4ChipsKaonPlusElasticXS::GetChipsCrossSection(), G4ChipsKaonMinusElasticXS::GetChipsCrossSection(), theKMinusCS, and theKPlusCS.
Referenced by GetIsoCrossSection().
G4double G4ChipsKaonZeroElasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 98 of file G4ChipsKaonZeroElasticXS.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ChipsKaonZeroElasticXS.cc
References GetChipsCrossSection(), G4DynamicParticle::GetTotalMomentum(), and N.
G4bool G4ChipsKaonZeroElasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 86 of file G4ChipsKaonZeroElasticXS.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsKaonZeroElasticXS.cc
Member Data Documentation
G4double G4ChipsKaonZeroElasticXS::lastCS private
Definition at line 86 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4double* G4ChipsKaonZeroElasticXS::lastHEN private
Definition at line 81 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4int G4ChipsKaonZeroElasticXS::lastI private
Definition at line 87 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4double* G4ChipsKaonZeroElasticXS::lastLEN private
Definition at line 80 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4int G4ChipsKaonZeroElasticXS::lastN private
Definition at line 82 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4double G4ChipsKaonZeroElasticXS::lastP private
Definition at line 84 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4double G4ChipsKaonZeroElasticXS::lastTH private
Definition at line 85 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4int G4ChipsKaonZeroElasticXS::lastZ private
Definition at line 83 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS().
G4ChipsKaonMinusElasticXS* G4ChipsKaonZeroElasticXS::theKMinusCS private
Definition at line 77 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS(), and GetChipsCrossSection().
G4ChipsKaonPlusElasticXS* G4ChipsKaonZeroElasticXS::theKPlusCS private
Definition at line 78 of file G4ChipsKaonZeroElasticXS.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ChipsKaonZeroElasticXS.hh
Referenced by G4ChipsKaonZeroElasticXS(), and GetChipsCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonZeroElasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsKaonZeroElasticXS.cc