ECCE @ EIC Software: G4PolarizedPairProductionCrossSection Class Reference
G4PolarizedPairProductionCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedPairProductionCrossSection.hh>
Public Member Functions
G4PolarizedPairProductionCrossSection ()
virtual void Initialize (G4double eps, G4double X, G4double phi, const G4StokesVector &p0, const G4StokesVector &p1, G4int flag=0) override
virtual G4double XSection (const G4StokesVector &pol2, const G4StokesVector &pol3) override
G4StokesVector GetPol2 () override
G4StokesVector GetPol3 () override
Public Member Functions inherited from G4VPolarizedCrossSection
G4VPolarizedCrossSection ()
virtual ~G4VPolarizedCrossSection ()
virtual G4double TotalXSection (G4double xmin, G4double xmax, G4double y, const G4StokesVector &pol0, const G4StokesVector &pol1)
G4double GetYmin ()
virtual G4double GetXmin (G4double y)
virtual G4double GetXmax (G4double y)
void SetMaterial (G4double A, G4double Z, G4double coul)
Private Member Functions
void InitializeMe ()
Private Attributes
G4StokesVector theFinalElectronPolarization
G4StokesVector theFinalPositronPolarization
Static Private Attributes
static G4bool scrnInitialized =false
static G4double SCRN [3][20]
Additional Inherited Members
Protected Member Functions inherited from G4VPolarizedCrossSection
void SetXmin (G4double xmin)
void SetXmax (G4double xmax)
void SetYmin (G4double ymin)
Protected Attributes inherited from G4VPolarizedCrossSection
G4double fXmin
G4double fXmax
G4double fYmin
G4double theA
G4double theZ
G4double fCoul
Detailed Description
Definition at line 52 of file G4PolarizedPairProductionCrossSection.hh.
View newest version in sPHENIX GitHub at line 52 of file G4PolarizedPairProductionCrossSection.hh
Constructor & Destructor Documentation
G4PolarizedPairProductionCrossSection::G4PolarizedPairProductionCrossSection ()
Definition at line 73 of file G4PolarizedPairProductionCrossSection.cc.
View newest version in sPHENIX GitHub at line 73 of file G4PolarizedPairProductionCrossSection.cc
References InitializeMe().
Member Function Documentation
G4StokesVector G4PolarizedPairProductionCrossSection::GetPol2 () override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 194 of file G4PolarizedPairProductionCrossSection.cc.
View newest version in sPHENIX GitHub at line 194 of file G4PolarizedPairProductionCrossSection.cc
References theFinalElectronPolarization.
G4StokesVector G4PolarizedPairProductionCrossSection::GetPol3 () override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 199 of file G4PolarizedPairProductionCrossSection.cc.
View newest version in sPHENIX GitHub at line 199 of file G4PolarizedPairProductionCrossSection.cc
References theFinalPositronPolarization.
void G4PolarizedPairProductionCrossSection::Initialize (G4double eps, G4double X, G4double phi, const G4StokesVector & p0, const G4StokesVector & p1, G4int flag = 0) override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 79 of file G4PolarizedPairProductionCrossSection.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PolarizedPairProductionCrossSection.cc
References Acts::Test::delta, source.hepunit::electron_mass_c2, G4VPolarizedCrossSection::fCoul, G4cout, G4endl, CLHEP::Hep3Vector::mag2(), SCRN, G4StokesVector::SetPhoton(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), theFinalElectronPolarization, theFinalPositronPolarization, G4VPolarizedCrossSection::theZ, Acts::UnitConstants::u, and CLHEP::Hep3Vector::z().
void G4PolarizedPairProductionCrossSection::InitializeMe () private
Definition at line 46 of file G4PolarizedPairProductionCrossSection.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PolarizedPairProductionCrossSection.cc
References SCRN, and scrnInitialized.
Referenced by G4PolarizedPairProductionCrossSection().
G4double G4PolarizedPairProductionCrossSection::XSection (const G4StokesVector & pol2, const G4StokesVector & pol3) override virtual
Implements G4VPolarizedCrossSection.
Definition at line 186 of file G4PolarizedPairProductionCrossSection.cc.
View newest version in sPHENIX GitHub at line 186 of file G4PolarizedPairProductionCrossSection.cc
References G4cout.
Member Data Documentation
G4double G4PolarizedPairProductionCrossSection::SCRN static private
Definition at line 74 of file G4PolarizedPairProductionCrossSection.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PolarizedPairProductionCrossSection.hh
Referenced by Initialize(), and InitializeMe().
G4bool G4PolarizedPairProductionCrossSection::scrnInitialized =false static private
Definition at line 73 of file G4PolarizedPairProductionCrossSection.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PolarizedPairProductionCrossSection.hh
Referenced by InitializeMe().
G4StokesVector G4PolarizedPairProductionCrossSection::theFinalElectronPolarization private
Definition at line 68 of file G4PolarizedPairProductionCrossSection.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PolarizedPairProductionCrossSection.hh
Referenced by GetPol2(), and Initialize().
G4StokesVector G4PolarizedPairProductionCrossSection::theFinalPositronPolarization private
Definition at line 69 of file G4PolarizedPairProductionCrossSection.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PolarizedPairProductionCrossSection.hh
Referenced by GetPol3(), and Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedPairProductionCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedPairProductionCrossSection.cc