ECCE @ EIC Software: G4OrderedTable Class Reference
G4OrderedTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4OrderedTable.hh>
Public Member Functions
G4OrderedTable ()
G4OrderedTable (size_t cap)
virtual ~G4OrderedTable ()
void clearAndDestroy ()
G4bool Store (const G4String &filename, G4bool ascii=false)
G4bool Retrieve (const G4String &filename, G4bool ascii=false)
Friends
std::ostream & operator<< (std::ostream &out, G4OrderedTable &table)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 56 of file G4OrderedTable.hh.
View newest version in sPHENIX GitHub at line 56 of file G4OrderedTable.hh
Constructor & Destructor Documentation
G4OrderedTable::G4OrderedTable ()
Definition at line 42 of file G4OrderedTable.cc.
View newest version in sPHENIX GitHub at line 42 of file G4OrderedTable.cc
G4OrderedTable::G4OrderedTable (size_t cap) explicit
Definition at line 47 of file G4OrderedTable.cc.
View newest version in sPHENIX GitHub at line 47 of file G4OrderedTable.cc
G4OrderedTable::~G4OrderedTable () virtual
Definition at line 52 of file G4OrderedTable.cc.
View newest version in sPHENIX GitHub at line 52 of file G4OrderedTable.cc
Member Function Documentation
void G4OrderedTable::clearAndDestroy () inline
Definition at line 89 of file G4OrderedTable.hh.
View newest version in sPHENIX GitHub at line 89 of file G4OrderedTable.hh
References a.
Referenced by Retrieve(), and G4SandiaTable::~G4SandiaTable().
G4bool G4OrderedTable::Retrieve (const G4String & filename, G4bool ascii = false)
Definition at line 109 of file G4OrderedTable.cc.
View newest version in sPHENIX GitHub at line 109 of file G4OrderedTable.cc
References clearAndDestroy(), G4cerr, G4endl, incremental_prev_tag::idx, in, G4DataVector::Retrieve(), and G4DataVector::T_G4DataVector.
G4bool G4OrderedTable::Store (const G4String & filename, G4bool ascii = false)
Definition at line 56 of file G4OrderedTable.cc.
View newest version in sPHENIX GitHub at line 56 of file G4OrderedTable.cc
References G4cerr, G4endl, and G4DataVector::T_G4DataVector.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, G4OrderedTable & table) friend
Definition at line 198 of file G4OrderedTable.cc.
View newest version in sPHENIX GitHub at line 198 of file G4OrderedTable.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4OrderedTable.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4OrderedTable.cc