ECCE @ EIC Software: WLSTrajectoryPoint Class Reference
WLSTrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSTrajectoryPoint.hh>
Public Member Functions
WLSTrajectoryPoint ()
WLSTrajectoryPoint (const G4Track *)
WLSTrajectoryPoint (const G4Step *)
WLSTrajectoryPoint (const WLSTrajectoryPoint &right)
virtual ~WLSTrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const WLSTrajectoryPoint &right) const
G4double GetTime () const
const G4ThreeVector GetMomentum () const
G4StepStatus GetStepStatus () const
G4String GetVolumeName () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4TrajectoryPoint
G4TrajectoryPoint ()
G4TrajectoryPoint (G4ThreeVector pos)
G4TrajectoryPoint (const G4TrajectoryPoint &right)
virtual ~G4TrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const G4TrajectoryPoint &right) const
const G4ThreeVector GetPosition () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
virtual const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
Private Attributes
G4double fTime
G4ThreeVector fMomentum
G4StepStatus fStepStatus
G4String fVolumeName
Detailed Description
Definition at line 49 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 49 of file WLSTrajectoryPoint.hh
Constructor & Destructor Documentation
WLSTrajectoryPoint::WLSTrajectoryPoint ()
Definition at line 53 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 53 of file WLSTrajectoryPoint.cc
WLSTrajectoryPoint::WLSTrajectoryPoint (const G4Track * aTrack)
Definition at line 76 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 76 of file WLSTrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, fUndefined, fVolumeName, G4Track::GetGlobalTime(), G4Track::GetMomentum(), G4VPhysicalVolume::GetName(), and G4Track::GetVolume().
WLSTrajectoryPoint::WLSTrajectoryPoint (const G4Step * aStep)
Definition at line 59 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 59 of file WLSTrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, fVolumeName, G4StepPoint::GetGlobalTime(), G4StepPoint::GetMomentum(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), and G4StepPoint::GetStepStatus().
WLSTrajectoryPoint::WLSTrajectoryPoint (const WLSTrajectoryPoint & right)
Definition at line 87 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 87 of file WLSTrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, and fVolumeName.
WLSTrajectoryPoint::~WLSTrajectoryPoint () virtual
Definition at line 98 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 98 of file WLSTrajectoryPoint.cc
Member Function Documentation
std::vector< G4AttValue > * WLSTrajectoryPoint::CreateAttValues () const virtual
Reimplemented from G4TrajectoryPoint.
Definition at line 134 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 134 of file WLSTrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, fVolumeName, G4BestUnit, G4cout, GetAttDefs(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * WLSTrajectoryPoint::GetAttDefs () const virtual
Reimplemented from G4TrajectoryPoint.
Definition at line 102 of file WLSTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 102 of file WLSTrajectoryPoint.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues().
const G4ThreeVector WLSTrajectoryPoint::GetMomentum () const inline
Definition at line 73 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 73 of file WLSTrajectoryPoint.hh
References fMomentum.
G4StepStatus WLSTrajectoryPoint::GetStepStatus () const inline
Definition at line 74 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 74 of file WLSTrajectoryPoint.hh
References fStepStatus.
G4double WLSTrajectoryPoint::GetTime () const inline
Definition at line 72 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 72 of file WLSTrajectoryPoint.hh
References fTime.
G4String WLSTrajectoryPoint::GetVolumeName () const inline
Definition at line 75 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 75 of file WLSTrajectoryPoint.hh
References fVolumeName.
void WLSTrajectoryPoint::operator delete (void * aTrajectoryPoint) inline
Definition at line 104 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 104 of file WLSTrajectoryPoint.hh
References WLSTrajPointAllocator.
void * WLSTrajectoryPoint::operator new (size_t) inline
Definition at line 97 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 97 of file WLSTrajectoryPoint.hh
References WLSTrajPointAllocator.
G4bool WLSTrajectoryPoint::operator== (const WLSTrajectoryPoint & right) const inline
Definition at line 67 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 67 of file WLSTrajectoryPoint.hh
Member Data Documentation
G4ThreeVector WLSTrajectoryPoint::fMomentum private
Definition at line 89 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 89 of file WLSTrajectoryPoint.hh
Referenced by CreateAttValues(), GetMomentum(), and WLSTrajectoryPoint().
G4StepStatus WLSTrajectoryPoint::fStepStatus private
Definition at line 90 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 90 of file WLSTrajectoryPoint.hh
Referenced by CreateAttValues(), GetStepStatus(), and WLSTrajectoryPoint().
G4double WLSTrajectoryPoint::fTime private
Definition at line 88 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 88 of file WLSTrajectoryPoint.hh
Referenced by CreateAttValues(), GetTime(), and WLSTrajectoryPoint().
G4String WLSTrajectoryPoint::fVolumeName private
Definition at line 91 of file WLSTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 91 of file WLSTrajectoryPoint.hh
Referenced by CreateAttValues(), GetVolumeName(), and WLSTrajectoryPoint().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSTrajectoryPoint.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSTrajectoryPoint.cc