ECCE @ EIC Software: G4DNAUeharaScreenedRutherfordElasticModel Class Reference
G4DNAUeharaScreenedRutherfordElasticModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAUeharaScreenedRutherfordElasticModel.hh>
Public Member Functions
G4DNAUeharaScreenedRutherfordElasticModel (const G4ParticleDefinition *p=0, const G4String &nam="DNAUeharaScreenedRutherfordElasticModel")
virtual ~G4DNAUeharaScreenedRutherfordElasticModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
void SelectFasterComputation (G4bool input)
void SetKillBelowThreshold (G4double threshold)
G4double GetKillBelowThreshold ()
void SelectHighEnergyLimit (G4double threshold)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4double RutherfordCrossSection (G4double energy, G4double z)
G4double ScreeningFactor (G4double energy, G4double z)
G4double BrennerZaiderRandomizeCosTheta (G4double k)
G4double CalculatePolynomial (G4double k, std::vector< G4double > &vec)
G4double ScreenedRutherfordRandomizeCosTheta (G4double k, G4double z)
G4DNAUeharaScreenedRutherfordElasticModel & operator= (const G4DNAUeharaScreenedRutherfordElasticModel &right)
G4DNAUeharaScreenedRutherfordElasticModel (const G4DNAUeharaScreenedRutherfordElasticModel &)
Private Attributes
G4double intermediateEnergyLimit
std::vector< G4double > betaCoeff
std::vector< G4double > deltaCoeff
std::vector< G4double > gamma035_10Coeff
std::vector< G4double > gamma10_100Coeff
std::vector< G4double > gamma100_200Coeff
const std::vector< G4double > * fpWaterDensity
G4int verboseLevel
G4bool fasterCode
G4bool isInitialised
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 36 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 36 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Constructor & Destructor Documentation
G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel (const G4ParticleDefinition * p = 0, const G4String & nam = "DNAUeharaScreenedRutherfordElasticModel")
Definition at line 41 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References eV, fasterCode, fParticleChangeForGamma, fpWaterDensity, G4cout, G4endl, G4VEmModel::HighEnergyLimit(), intermediateEnergyLimit, G4VEmModel::LowEnergyLimit(), MeV, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), and verboseLevel.
G4DNAUeharaScreenedRutherfordElasticModel::~G4DNAUeharaScreenedRutherfordElasticModel () virtual
Definition at line 83 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 83 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
G4DNAUeharaScreenedRutherfordElasticModel::G4DNAUeharaScreenedRutherfordElasticModel (const G4DNAUeharaScreenedRutherfordElasticModel &) private
Member Function Documentation
G4double G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta (G4double k) private
Definition at line 355 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 355 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References a, A(), b, B(), betaCoeff, C(), c1, c2, CalculatePolynomial(), cp, Acts::Test::delta, deltaCoeff, eV, fasterCode, G4Exp(), G4UniformRand, gamma035_10Coeff, gamma100_200Coeff, gamma10_100Coeff, and S().
Referenced by SampleSecondaries().
G4double G4DNAUeharaScreenedRutherfordElasticModel::CalculatePolynomial (G4double k, std::vector< G4double > & vec) private
Definition at line 527 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 527 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References k.
Referenced by BrennerZaiderRandomizeCosTheta().
G4double G4DNAUeharaScreenedRutherfordElasticModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 193 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 193 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References cm, eV, G4cout, G4endl, G4Material::GetIndex(), n, pi, RutherfordCrossSection(), ScreeningFactor(), verboseLevel, and z.
G4double G4DNAUeharaScreenedRutherfordElasticModel::GetKillBelowThreshold () inline
Definition at line 147 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
References G4Exception(), and JustWarning.
void G4DNAUeharaScreenedRutherfordElasticModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 91 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 91 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References betaCoeff, deltaCoeff, CLHEP::eV, eV, FatalException, fParticleChangeForGamma, fpWaterDensity, G4cout, G4endl, G4Exception(), gamma035_10Coeff, gamma100_200Coeff, gamma10_100Coeff, G4Material::GetMaterial(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4DNAMolecularMaterial::Instance(), isInitialised, JustWarning, CLHEP::keV, G4VEmModel::LowEnergyLimit(), MeV, and verboseLevel.
G4DNAUeharaScreenedRutherfordElasticModel& G4DNAUeharaScreenedRutherfordElasticModel::operator= (const G4DNAUeharaScreenedRutherfordElasticModel & right) private
G4double G4DNAUeharaScreenedRutherfordElasticModel::RutherfordCrossSection (G4double energy, G4double z) private
Definition at line 241 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 241 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References Acts::VectorHelpers::cross(), source.hepunit::e_squared, source.hepunit::electron_mass_c2, source.hepunit::epsilon0, BTOF::length, and pi.
Referenced by CrossSectionPerVolume().
void G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * aDynamicElectron, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 296 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 296 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References BrennerZaiderRandomizeCosTheta(), CLHEP::Hep3Vector::cross(), fParticleChangeForGamma, G4cout, G4endl, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), intermediateEnergyLimit, CLHEP::Hep3Vector::orthogonal(), phi, pi, G4ParticleChangeForGamma::ProposeMomentumDirection(), ScreenedRutherfordRandomizeCosTheta(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), CLHEP::Hep3Vector::unit(), verboseLevel, and z.
G4double G4DNAUeharaScreenedRutherfordElasticModel::ScreenedRutherfordRandomizeCosTheta (G4double k, G4double z) private
Definition at line 552 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 552 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References cp, fasterCode, G4UniformRand, n, and ScreeningFactor().
Referenced by SampleSecondaries().
G4double G4DNAUeharaScreenedRutherfordElasticModel::ScreeningFactor (G4double energy, G4double z) private
Definition at line 262 of file G4DNAUeharaScreenedRutherfordElasticModel.cc.
View newest version in sPHENIX GitHub at line 262 of file G4DNAUeharaScreenedRutherfordElasticModel.cc
References E, source.hepunit::electron_mass_c2, k, and keV.
Referenced by CrossSectionPerVolume(), and ScreenedRutherfordRandomizeCosTheta().
void G4DNAUeharaScreenedRutherfordElasticModel::SelectFasterComputation (G4bool input) inline
Definition at line 110 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
References fasterCode.
Referenced by G4EmDNAPhysics_option5::ConstructProcess().
void G4DNAUeharaScreenedRutherfordElasticModel::SelectHighEnergyLimit (G4double threshold) inline
Definition at line 119 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
References G4Exception(), JustWarning, CLHEP::keV, and G4VEmModel::SetHighEnergyLimit().
void G4DNAUeharaScreenedRutherfordElasticModel::SetKillBelowThreshold (G4double threshold) inline
Definition at line 134 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 134 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
References G4Exception(), and JustWarning.
Member Data Documentation
std::vector<G4double> G4DNAUeharaScreenedRutherfordElasticModel::betaCoeff private
Definition at line 71 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by BrennerZaiderRandomizeCosTheta(), and Initialise().
std::vector<G4double> G4DNAUeharaScreenedRutherfordElasticModel::deltaCoeff private
Definition at line 72 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 72 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by BrennerZaiderRandomizeCosTheta(), and Initialise().
G4bool G4DNAUeharaScreenedRutherfordElasticModel::fasterCode private
Definition at line 85 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel(), ScreenedRutherfordRandomizeCosTheta(), and SelectFasterComputation().
G4ParticleChangeForGamma* G4DNAUeharaScreenedRutherfordElasticModel::fParticleChangeForGamma protected
Definition at line 81 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by G4DNAUeharaScreenedRutherfordElasticModel(), Initialise(), and SampleSecondaries().
const std::vector<G4double>* G4DNAUeharaScreenedRutherfordElasticModel::fpWaterDensity private
Definition at line 78 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by G4DNAUeharaScreenedRutherfordElasticModel(), and Initialise().
std::vector<G4double> G4DNAUeharaScreenedRutherfordElasticModel::gamma035_10Coeff private
Definition at line 73 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by BrennerZaiderRandomizeCosTheta(), and Initialise().
std::vector<G4double> G4DNAUeharaScreenedRutherfordElasticModel::gamma100_200Coeff private
Definition at line 75 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by BrennerZaiderRandomizeCosTheta(), and Initialise().
std::vector<G4double> G4DNAUeharaScreenedRutherfordElasticModel::gamma10_100Coeff private
Definition at line 74 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by BrennerZaiderRandomizeCosTheta(), and Initialise().
G4double G4DNAUeharaScreenedRutherfordElasticModel::intermediateEnergyLimit private
Definition at line 68 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by G4DNAUeharaScreenedRutherfordElasticModel(), and SampleSecondaries().
G4bool G4DNAUeharaScreenedRutherfordElasticModel::isInitialised private
Definition at line 86 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by Initialise().
G4int G4DNAUeharaScreenedRutherfordElasticModel::verboseLevel private
Definition at line 84 of file G4DNAUeharaScreenedRutherfordElasticModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DNAUeharaScreenedRutherfordElasticModel.hh
Referenced by CrossSectionPerVolume(), G4DNAUeharaScreenedRutherfordElasticModel(), Initialise(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAUeharaScreenedRutherfordElasticModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAUeharaScreenedRutherfordElasticModel.cc