ECCE @ EIC Software: G4FluoTransition Class Reference
G4FluoTransition Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4FluoTransition.hh>
Public Member Functions
G4FluoTransition (G4int, const std::vector< G4int > &, const G4DataVector &, const G4DataVector &)
~G4FluoTransition ()
const std::vector< G4int > & OriginatingShellIds () const
const G4DataVector & TransitionEnergies () const
const G4DataVector & TransitionProbabilities () const
G4int FinalShellId () const
G4int OriginatingShellId (G4int index) const
G4double TransitionEnergy (G4int index) const
G4double TransitionProbability (G4int index) const
Private Attributes
G4int finalShellId
std::vector< G4int > originatingShellIds
G4DataVector transitionEnergies
G4DataVector transitionProbabilities
Detailed Description
Definition at line 51 of file G4FluoTransition.hh.
View newest version in sPHENIX GitHub at line 51 of file G4FluoTransition.hh
Constructor & Destructor Documentation
G4FluoTransition::G4FluoTransition (G4int finalShell, const std::vector< G4int > & ids, const G4DataVector & energies, const G4DataVector & prob)
Definition at line 39 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 39 of file G4FluoTransition.cc
G4FluoTransition::~G4FluoTransition ()
Definition at line 49 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 49 of file G4FluoTransition.cc
Member Function Documentation
G4int G4FluoTransition::FinalShellId () const
Definition at line 67 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 67 of file G4FluoTransition.cc
References finalShellId.
Referenced by G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
G4int G4FluoTransition::OriginatingShellId (G4int index) const
Definition at line 72 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 72 of file G4FluoTransition.cc
References originatingShellIds.
Referenced by G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
const std::vector< G4int > & G4FluoTransition::OriginatingShellIds () const
Definition at line 52 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 52 of file G4FluoTransition.cc
References originatingShellIds.
const G4DataVector & G4FluoTransition::TransitionEnergies () const
Definition at line 57 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 57 of file G4FluoTransition.cc
References transitionEnergies.
G4double G4FluoTransition::TransitionEnergy (G4int index) const
Definition at line 76 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FluoTransition.cc
References transitionEnergies.
const G4DataVector & G4FluoTransition::TransitionProbabilities () const
Definition at line 62 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 62 of file G4FluoTransition.cc
References transitionProbabilities.
Referenced by G4AtomicDeexcitation::SelectTypeOfTransition(), G4UAtomicDeexcitation::SelectTypeOfTransition(), and G4AtomicTransitionManager::TotalRadiativeTransitionProbability().
G4double G4FluoTransition::TransitionProbability (G4int index) const
Definition at line 80 of file G4FluoTransition.cc.
View newest version in sPHENIX GitHub at line 80 of file G4FluoTransition.cc
References transitionProbabilities.
Referenced by G4AtomicDeexcitation::SelectTypeOfTransition(), and G4UAtomicDeexcitation::SelectTypeOfTransition().
Member Data Documentation
G4int G4FluoTransition::finalShellId private
Definition at line 89 of file G4FluoTransition.hh.
View newest version in sPHENIX GitHub at line 89 of file G4FluoTransition.hh
Referenced by FinalShellId().
std::vector<G4int> G4FluoTransition::originatingShellIds private
Definition at line 90 of file G4FluoTransition.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FluoTransition.hh
Referenced by OriginatingShellId(), and OriginatingShellIds().
G4DataVector G4FluoTransition::transitionEnergies private
Definition at line 91 of file G4FluoTransition.hh.
View newest version in sPHENIX GitHub at line 91 of file G4FluoTransition.hh
Referenced by TransitionEnergies(), and TransitionEnergy().
G4DataVector G4FluoTransition::transitionProbabilities private
Definition at line 92 of file G4FluoTransition.hh.
View newest version in sPHENIX GitHub at line 92 of file G4FluoTransition.hh
Referenced by TransitionProbabilities(), and TransitionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4FluoTransition.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4FluoTransition.cc