ECCE @ EIC Software: G4VContinuousDiscreteProcess Class Reference
G4VContinuousDiscreteProcess Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4VContinuousDiscreteProcess.hh>
Public Member Functions
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)=0
virtual G4double GetContinuousStepLimit (const G4Track &aTrack, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)=0
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Member Functions
G4VContinuousDiscreteProcess ()
G4VContinuousDiscreteProcess & operator= (const G4VContinuousDiscreteProcess &right)
Private Attributes
G4GPILSelection valueGPILSelection
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 54 of file G4VContinuousDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VContinuousDiscreteProcess.hh
Constructor & Destructor Documentation
G4VContinuousDiscreteProcess::G4VContinuousDiscreteProcess (const G4String & aName, G4ProcessType aType = fNotDefined)
Definition at line 54 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VContinuousDiscreteProcess.cc
References G4VProcess::enableAtRestDoIt.
G4VContinuousDiscreteProcess::G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess & right)
Definition at line 65 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VContinuousDiscreteProcess.cc
G4VContinuousDiscreteProcess::~G4VContinuousDiscreteProcess () virtual
Definition at line 61 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VContinuousDiscreteProcess.cc
G4VContinuousDiscreteProcess::G4VContinuousDiscreteProcess () private
Definition at line 46 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VContinuousDiscreteProcess.cc
References G4Exception(), and JustWarning.
Member Function Documentation
G4VParticleChange * G4VContinuousDiscreteProcess::AlongStepDoIt (const G4Track & , const G4Step &) virtual
Implements G4VProcess.
Reimplemented in G4VMultipleScattering, G4VEnergyLossProcess, G4hImpactIonisation, G4eLowEnergyLoss, G4RDVeLowEnergyLoss, and G4AdjointForcedInteractionForGamma.
Definition at line 123 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 123 of file G4VContinuousDiscreteProcess.cc
References G4VProcess::ClearNumberOfInteractionLengthLeft(), and G4VProcess::pParticleChange.
G4double G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Reimplemented in G4VMultipleScattering, and G4VEnergyLossProcess.
Definition at line 133 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 133 of file G4VContinuousDiscreteProcess.cc
References CandidateForSelection, cm, G4DynamicParticle::DumpInfo(), G4cout, G4endl, GetContinuousStepLimit(), G4Track::GetDynamicParticle(), G4Track::GetMaterial(), G4Material::GetName(), G4VProcess::GetProcessName(), valueGPILSelection, and G4VProcess::verboseLevel.
virtual G4VParticleChange* G4VContinuousDiscreteProcess::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 98 of file G4VContinuousDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 98 of file G4VContinuousDiscreteProcess.hh
virtual G4double G4VContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 92 of file G4VContinuousDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VContinuousDiscreteProcess.hh
virtual G4double G4VContinuousDiscreteProcess::GetContinuousStepLimit (const G4Track & aTrack, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) protected pure virtual
Implemented in G4VMultipleScattering, G4VEnergyLossProcess, G4hImpactIonisation, G4eLowEnergyLoss, G4AdjointForcedInteractionForGamma, and G4RDVeLowEnergyLoss.
Referenced by AlongStepGetPhysicalInteractionLength().
G4GPILSelection G4VContinuousDiscreteProcess::GetGPILSelection () const inline protected
Definition at line 127 of file G4VContinuousDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VContinuousDiscreteProcess.hh
References valueGPILSelection.
virtual G4double G4VContinuousDiscreteProcess::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) protected pure virtual
Implemented in G4VMultipleScattering, G4VEnergyLossProcess, G4eLowEnergyLoss, G4hRDEnergyLoss, G4LowEnergyBremsstrahlung, G4AdjointForcedInteractionForGamma, G4LowEnergyIonisation, G4RDVeLowEnergyLoss, G4ePolarizedIonisation, and G4hImpactIonisation.
Referenced by PostStepGetPhysicalInteractionLength().
G4VContinuousDiscreteProcess& G4VContinuousDiscreteProcess::operator= (const G4VContinuousDiscreteProcess & right) private
G4VParticleChange * G4VContinuousDiscreteProcess::PostStepDoIt (const G4Track & , const G4Step &) virtual
Implements G4VProcess.
Reimplemented in G4VMultipleScattering, G4VEnergyLossProcess, G4hImpactIonisation, G4eLowEnergyLoss, G4hRDEnergyLoss, G4RDVeLowEnergyLoss, G4AdjointForcedInteractionForGamma, G4LowEnergyBremsstrahlung, and G4LowEnergyIonisation.
Definition at line 113 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 113 of file G4VContinuousDiscreteProcess.cc
References G4VProcess::ClearNumberOfInteractionLengthLeft(), and G4VProcess::pParticleChange.
Referenced by G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), and G4hImpactIonisation::PostStepDoIt().
G4double G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Reimplemented in G4VMultipleScattering, G4VEnergyLossProcess, G4ePolarizedIonisation, and G4AdjointForcedInteractionForGamma.
Definition at line 71 of file G4VContinuousDiscreteProcess.cc.
View newest version in sPHENIX GitHub at line 71 of file G4VContinuousDiscreteProcess.cc
References cm, G4VProcess::currentInteractionLength, DBL_MAX, G4DynamicParticle::DumpInfo(), G4cout, G4endl, G4Track::GetDynamicParticle(), G4Track::GetMaterial(), GetMeanFreePath(), G4Material::GetName(), G4VProcess::GetProcessName(), NotForced, G4VProcess::ResetNumberOfInteractionLengthLeft(), G4VProcess::SubtractNumberOfInteractionLengthLeft(), G4VProcess::theNumberOfInteractionLengthLeft, and G4VProcess::verboseLevel.
void G4VContinuousDiscreteProcess::SetGPILSelection (G4GPILSelection selection) inline protected
Definition at line 124 of file G4VContinuousDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 124 of file G4VContinuousDiscreteProcess.hh
References valueGPILSelection.
Member Data Documentation
G4GPILSelection G4VContinuousDiscreteProcess::valueGPILSelection private
Definition at line 120 of file G4VContinuousDiscreteProcess.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VContinuousDiscreteProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), GetGPILSelection(), and SetGPILSelection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4VContinuousDiscreteProcess.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4VContinuousDiscreteProcess.cc