ECCE @ EIC Software: MarshaledExN02TrackerHit Class Reference
MarshaledExN02TrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/MarshaledExN02TrackerHit.h>
Public Member Functions
MarshaledExN02TrackerHit (ExN02TrackerHit *objptr)
MarshaledExN02TrackerHit (void *buf, char chIsUnmarshaling= 'u')
~MarshaledExN02TrackerHit ()
ExN02TrackerHit * unmarshal ()
void unmarshalTo (ExN02TrackerHit *obj)
void marshal1 ()
void unmarshal1 ()
void marshal2 ()
void unmarshal2 ()
void marshal3 ()
void unmarshal3 ()
void marshal4 ()
void unmarshal4 ()
Public Member Functions inherited from MarshaledObj
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
Public Attributes
ExN02TrackerHit * param
ShadowedMarshaledExN02TrackerHit * Shadowed_param
Additional Inherited Members
Static Public Member Functions inherited from MarshaledObj
static int ROUND_UP (int x)
static int ROUND_UP (int x)
Protected Attributes inherited from MarshaledObj
int msh_typechoice
char * msh_buffer
char * msh_field_begin
size_t msh_size
char * msh_cursor
size_t msh_extent
bool msh_isUnmarshalDone
Detailed Description
Definition at line 22 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 22 of file MarshaledExN02TrackerHit.h
Constructor & Destructor Documentation
MarshaledExN02TrackerHit::MarshaledExN02TrackerHit (ExN02TrackerHit * objptr) inline
Definition at line 31 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 31 of file MarshaledExN02TrackerHit.h
References marshal1(), marshal2(), marshal3(), marshal4(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledExN02TrackerHit::MarshaledExN02TrackerHit (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 44 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 44 of file MarshaledExN02TrackerHit.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledExN02TrackerHit::~MarshaledExN02TrackerHit () inline
Definition at line 49 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 49 of file MarshaledExN02TrackerHit.h
Member Function Documentation
void MarshaledExN02TrackerHit::marshal1 () inline
Definition at line 92 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 92 of file MarshaledExN02TrackerHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN02TrackerHit::GetPos(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN02TrackerHit().
void MarshaledExN02TrackerHit::marshal2 () inline
Definition at line 149 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 149 of file MarshaledExN02TrackerHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN02TrackerHit::GetEdep(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN02TrackerHit().
void MarshaledExN02TrackerHit::marshal3 () inline
Definition at line 206 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 206 of file MarshaledExN02TrackerHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN02TrackerHit::GetTrackID(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN02TrackerHit().
void MarshaledExN02TrackerHit::marshal4 () inline
Definition at line 263 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 263 of file MarshaledExN02TrackerHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN02TrackerHit::GetChamberNb(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN02TrackerHit().
ExN02TrackerHit* MarshaledExN02TrackerHit::unmarshal () inline
Definition at line 55 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 55 of file MarshaledExN02TrackerHit.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, unmarshal1(), unmarshal2(), unmarshal3(), and unmarshal4().
Referenced by MarshaledG4HitsCollection::unmarshal1().
void MarshaledExN02TrackerHit::unmarshal1 () inline
Definition at line 133 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 133 of file MarshaledExN02TrackerHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN02TrackerHit::SetPos().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN02TrackerHit::unmarshal2 () inline
Definition at line 190 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 190 of file MarshaledExN02TrackerHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN02TrackerHit::SetEdep().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN02TrackerHit::unmarshal3 () inline
Definition at line 247 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 247 of file MarshaledExN02TrackerHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN02TrackerHit::SetTrackID().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN02TrackerHit::unmarshal4 () inline
Definition at line 304 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 304 of file MarshaledExN02TrackerHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN02TrackerHit::SetChamberNb().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN02TrackerHit::unmarshalTo (ExN02TrackerHit * obj) inline
Definition at line 75 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 75 of file MarshaledExN02TrackerHit.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, unmarshal1(), unmarshal2(), unmarshal3(), and unmarshal4().
Member Data Documentation
ExN02TrackerHit* MarshaledExN02TrackerHit::param
Definition at line 24 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 24 of file MarshaledExN02TrackerHit.h
Referenced by marshal1(), marshal2(), marshal3(), marshal4(), MarshaledExN02TrackerHit(), unmarshal(), unmarshal1(), unmarshal2(), unmarshal3(), unmarshal4(), and unmarshalTo().
ShadowedMarshaledExN02TrackerHit* MarshaledExN02TrackerHit::Shadowed_param
Definition at line 25 of file MarshaledExN02TrackerHit.h.
View newest version in sPHENIX GitHub at line 25 of file MarshaledExN02TrackerHit.h
Referenced by MarshaledExN02TrackerHit(), unmarshal(), and unmarshalTo().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/MarshaledExN02TrackerHit.h