ECCE @ EIC Software: G4HepRepFileSceneHandler Class Reference
G4HepRepFileSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepFileSceneHandler.hh>
Public Member Functions
G4HepRepFileSceneHandler (G4VGraphicsSystem &system, const G4String &name)
virtual ~G4HepRepFileSceneHandler ()
void AddSolid (const G4Box &)
void AddSolid (const G4Cons &)
void AddSolid (const G4Tubs &)
void AddSolid (const G4Trd &)
void AddSolid (const G4Trap &)
void AddSolid (const G4Sphere &)
void AddSolid (const G4Para &)
void AddSolid (const G4Torus &)
void AddSolid (const G4Polycone &)
void AddSolid (const G4Polyhedra &)
void AddSolid (const G4Orb &)
void AddSolid (const G4Ellipsoid &)
void AddSolid (const G4TessellatedSolid &)
void AddSolid (const G4VSolid &)
void AddCompound (const G4VTrajectory &)
void InitTrajectory ()
void AddCompound (const G4VHit &)
void InitHit ()
void AddCompound (const G4THitsMap< G4double > &hits)
void AddCompound (const G4THitsMap< G4StatDouble > &hits)
void AddCompound (const G4VDigi &digi)
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Polymarker &)
void AddPrimitive (const G4Scale &scale)
void BeginModeling ()
void EndModeling ()
void BeginPrimitives2D (const G4Transform3D &objectTransformation)
void EndPrimitives2D ()
void ClearTransientStore ()
G4HepRepFileXMLWriter * GetHepRepXMLWriter ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void BeginPrimitives (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Static Protected Attributes
static G4int fSceneIdCount = 0
Private Member Functions
void AddHepRepInstance (const char *primName, const G4Visible visible)
void CheckFileOpen ()
Private Attributes
G4HepRepFileXMLWriter * hepRepXMLWriter
int fileCounter
G4bool haveVisible
G4bool inPrimitives2D
G4bool warnedAbout3DText
G4bool warnedAbout2DMarkers
G4bool drawingTraj
G4bool doneInitTraj
G4bool drawingHit
G4bool doneInitHit
const G4VisTrajContext * trajContext
std::vector< G4AttValue > * trajAttValues
std::map< G4String, G4AttDef > * trajAttDefs
std::vector< G4AttValue > * hitAttValues
std::map< G4String, G4AttDef > * hitAttDefs
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Definition at line 58 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 58 of file G4HepRepFileSceneHandler.hh
Constructor & Destructor Documentation
G4HepRepFileSceneHandler::G4HepRepFileSceneHandler (G4VGraphicsSystem & system, const G4String & name)
Definition at line 69 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 69 of file G4HepRepFileSceneHandler.cc
References doneInitHit, doneInitTraj, drawingHit, drawingTraj, fileCounter, GetHepRepXMLWriter(), haveVisible, hepRepXMLWriter, hitAttDefs, hitAttValues, inPrimitives2D, trajAttDefs, trajAttValues, trajContext, warnedAbout2DMarkers, and warnedAbout3DText.
G4HepRepFileSceneHandler::~G4HepRepFileSceneHandler () virtual
Definition at line 92 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 92 of file G4HepRepFileSceneHandler.cc
Member Function Documentation
void G4HepRepFileSceneHandler::AddCompound (const G4VTrajectory & traj) virtual
Reimplemented from G4VSceneHandler.
Definition at line 528 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 528 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttDef(), G4HepRepFileXMLWriter::addAttValue(), G4VSceneHandler::AddCompound(), G4HepRepFileXMLWriter::addInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), G4HepRepFileXMLWriter::addType(), CheckFileOpen(), G4VTrajectoryPoint::CreateAttValues(), G4VTrajectory::CreateAttValues(), doneInitTraj, drawingTraj, error, FatalException, G4VSceneHandler::fpModel, G4cout, G4endl, G4Exception(), G4VTrajectoryPoint::GetAttDefs(), G4VTrajectory::GetAttDefs(), G4VTrajectoryPoint::GetAuxiliaryPoints(), G4VisTrajContext::GetAuxPtsColour(), G4VisTrajContext::GetAuxPtsSize(), G4VisTrajContext::GetAuxPtsType(), G4VisTrajContext::GetAuxPtsVisible(), G4Colour::GetBlue(), G4VisTrajContext::GetDrawAuxPts(), G4VisTrajContext::GetDrawStepPts(), G4Colour::GetGreen(), G4VTrajectory::GetPoint(), G4VTrajectory::GetPointEntries(), G4VTrajectoryPoint::GetPosition(), G4Colour::GetRed(), G4VisTrajContext::GetStepPtsColour(), G4VisTrajContext::GetStepPtsSize(), G4VisTrajContext::GetStepPtsType(), G4VisTrajContext::GetStepPtsVisible(), hepRepXMLWriter, InitTrajectory(), G4HepRepFileXMLWriter::prevTypeName, square(), G4Polymarker::squares, trajAttDefs, trajAttValues, trajContext, BlackHoleGeometry::visible, CLHEP::Hep3Vector::x(), HepGeom::BasicVector3D< T >::x(), CLHEP::Hep3Vector::y(), HepGeom::BasicVector3D< T >::y(), CLHEP::Hep3Vector::z(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddCompound (const G4VHit & hit) virtual
Reimplemented from G4VSceneHandler.
Definition at line 893 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 893 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttDef(), G4HepRepFileXMLWriter::addAttValue(), G4VSceneHandler::AddCompound(), G4HepRepFileXMLWriter::addInstance(), G4HepRepFileXMLWriter::addType(), CheckFileOpen(), G4VHit::CreateAttValues(), doneInitHit, drawingHit, error, G4cout, G4endl, G4VHit::GetAttDefs(), hepRepXMLWriter, hitAttDefs, hitAttValues, and G4HepRepFileXMLWriter::prevTypeName.
void G4HepRepFileSceneHandler::AddCompound (const G4THitsMap< G4double > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 85 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 85 of file G4HepRepFileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4HepRepFileSceneHandler::AddCompound (const G4THitsMap< G4StatDouble > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 88 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 88 of file G4HepRepFileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4HepRepFileSceneHandler::AddCompound (const G4VDigi & digi) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 91 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HepRepFileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4HepRepFileSceneHandler::AddHepRepInstance (const char * primName, const G4Visible visible) private
Definition at line 1321 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1321 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), G4HepRepFileXMLWriter::addInstance(), G4HepRepFileXMLWriter::addType(), CheckFileOpen(), drawingHit, drawingTraj, G4VSceneHandler::fpModel, G4VSceneHandler::fpViewer, G4VSceneHandler::fpVisAttribs, G4VSceneHandler::fReadyForTransients, G4cout, G4endl, G4Colour::GetBlue(), G4VisAttributes::GetColour(), G4HepRepMessenger::getCullInvisibles(), G4PhysicalVolumeModel::GetCurrentDepth(), G4PhysicalVolumeModel::GetCurrentLV(), G4PhysicalVolumeModel::GetCurrentMaterial(), G4PhysicalVolumeModel::GetCurrentPV(), G4Material::GetDensity(), G4PhysicalVolumeModel::GetDrawnPVPath(), G4VSolid::GetEntityType(), G4Colour::GetGreen(), G4HepRepMessenger::GetInstance(), G4VSolid::GetName(), G4Region::GetName(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), G4Material::GetRadlen(), G4Colour::GetRed(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSolid(), G4Material::GetState(), G4Visible::GetVisAttributes(), haveVisible, hepRepXMLWriter, G4LogicalVolume::IsRootRegion(), G4VisAttributes::IsVisible(), kg, kStateUndefined, G4TTL::layer, m, m3, material(), G4HepRepFileXMLWriter::prevTypeName, and G4HepRepFileXMLWriter::typeDepth.
Referenced by AddPrimitive(), and AddSolid().
void G4HepRepFileSceneHandler::AddPrimitive (const G4Polyline & polyline) virtual
Implements G4VSceneHandler.
Definition at line 1037 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1037 of file G4HepRepFileSceneHandler.cc
References AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), haveVisible, hepRepXMLWriter, InitHit(), InitTrajectory(), inPrimitives2D, G4VisAttributes::IsVisible(), warnedAbout2DMarkers, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddPrimitive (const G4Text & text) virtual
Implements G4VSceneHandler.
Definition at line 1125 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1125 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), AddHepRepInstance(), G4HepRepFileXMLWriter::addPrimitive(), G4cout, G4endl, G4Colour::GetBlue(), G4Colour::GetGreen(), G4VSceneHandler::GetMarkerSize(), G4Colour::GetRed(), G4Text::GetText(), G4VSceneHandler::GetTextColour(), G4Text::GetXOffset(), G4Text::GetYOffset(), haveVisible, hepRepXMLWriter, inPrimitives2D, warnedAbout3DText, and G4VSceneHandler::world.
void G4HepRepFileSceneHandler::AddPrimitive (const G4Circle & circle) virtual
Implements G4VSceneHandler.
Definition at line 1181 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1181 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), G4VSceneHandler::GetMarkerSize(), G4VMarker::GetPosition(), G4VMarker::GetWorldRadius(), haveVisible, hepRepXMLWriter, InitHit(), inPrimitives2D, G4VisAttributes::IsVisible(), warnedAbout2DMarkers, G4VSceneHandler::world, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddPrimitive (const G4Square & square) virtual
Implements G4VSceneHandler.
Definition at line 1227 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1227 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), G4VSceneHandler::GetMarkerSize(), G4VMarker::GetPosition(), G4VMarker::GetWorldRadius(), haveVisible, hepRepXMLWriter, InitHit(), inPrimitives2D, G4VisAttributes::IsVisible(), warnedAbout2DMarkers, G4VSceneHandler::world, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddPrimitive (const G4Polyhedron & polyhedron) virtual
Implements G4VSceneHandler.
Definition at line 1273 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1273 of file G4HepRepFileSceneHandler.cc
References AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), HepPolyhedron::GetNextNormal(), HepPolyhedron::GetNextVertex(), HepPolyhedron::GetNoFacets(), haveVisible, hepRepXMLWriter, InitHit(), G4VisAttributes::IsVisible(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddPrimitive (const G4Polymarker & line) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1078 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1078 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), G4VSceneHandler::GetMarkerSize(), haveVisible, hepRepXMLWriter, InitHit(), inPrimitives2D, G4VisAttributes::IsVisible(), warnedAbout2DMarkers, G4VSceneHandler::world, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 113 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 113 of file G4HepRepFileSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4HepRepFileSceneHandler::AddSolid (const G4Box & box) virtual
Reimplemented from G4VSceneHandler.
Definition at line 150 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 150 of file G4HepRepFileSceneHandler.cc
References AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, dx, dy, dz, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpViewer, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4VViewer::GetApplicableVisAttributes(), G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), G4VSolid::GetName(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), haveVisible, hepRepXMLWriter, InitHit(), G4VisAttributes::IsVisible(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddSolid (const G4Cons & cons) virtual
Reimplemented from G4VSceneHandler.
Definition at line 210 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 210 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), G4VSceneHandler::AddSolid(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpViewer, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4VViewer::GetApplicableVisAttributes(), G4HepRepMessenger::getCullInvisibles(), G4Cons::GetDeltaPhiAngle(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4HepRepMessenger::GetInstance(), G4VSolid::GetName(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4HepRepMessenger::getScale(), G4Cons::GetZHalfLength(), haveVisible, hepRepXMLWriter, InitHit(), G4VisAttributes::IsVisible(), CLHEP::HepRotation::phiX(), CLHEP::HepRotation::phiY(), CLHEP::HepRotation::phiZ(), pi, r, G4HepRepMessenger::renderCylAsPolygons(), twopi, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddSolid (const G4Tubs & tubs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 277 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 277 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), G4VSceneHandler::AddSolid(), drawingHit, drawingTraj, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpViewer, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4VViewer::GetApplicableVisAttributes(), G4HepRepMessenger::getCullInvisibles(), G4Tubs::GetDeltaPhiAngle(), G4Tubs::GetInnerRadius(), G4HepRepMessenger::GetInstance(), G4VSolid::GetName(), G4Tubs::GetOuterRadius(), G4HepRepMessenger::getScale(), G4Tubs::GetZHalfLength(), haveVisible, hepRepXMLWriter, InitHit(), G4VisAttributes::IsVisible(), CLHEP::HepRotation::phiX(), CLHEP::HepRotation::phiY(), CLHEP::HepRotation::phiZ(), pi, r, G4HepRepMessenger::renderCylAsPolygons(), twopi, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddSolid (const G4Trd & trd) virtual
Reimplemented from G4VSceneHandler.
Definition at line 346 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 346 of file G4HepRepFileSceneHandler.cc
References AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileXMLWriter::addPrimitive(), drawingHit, drawingTraj, dz, G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpViewer, G4VSceneHandler::fpVisAttribs, G4cout, G4endl, G4VViewer::GetApplicableVisAttributes(), G4HepRepMessenger::getCullInvisibles(), G4HepRepMessenger::GetInstance(), G4VSolid::GetName(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), haveVisible, hepRepXMLWriter, InitHit(), G4VisAttributes::IsVisible(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepFileSceneHandler::AddSolid (const G4Trap & trap) virtual
Reimplemented from G4VSceneHandler.
Definition at line 408 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 408 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Sphere & sphere) virtual
Reimplemented from G4VSceneHandler.
Definition at line 420 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 420 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Para & para) virtual
Reimplemented from G4VSceneHandler.
Definition at line 432 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 432 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Torus & torus) virtual
Reimplemented from G4VSceneHandler.
Definition at line 444 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 444 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Polycone & polycone) virtual
Reimplemented from G4VSceneHandler.
Definition at line 456 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 456 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Polyhedra & polyhedra) virtual
Reimplemented from G4VSceneHandler.
Definition at line 468 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 468 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Orb & orb) virtual
Reimplemented from G4VSceneHandler.
Definition at line 480 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 480 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) virtual
Reimplemented from G4VSceneHandler.
Definition at line 492 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 492 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4TessellatedSolid & tess) virtual
Reimplemented from G4VSceneHandler.
Definition at line 504 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 504 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::AddSolid (const G4VSolid & solid) virtual
Reimplemented from G4VSceneHandler.
Definition at line 516 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 516 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::AddSolid(), G4cout, G4endl, and G4VSolid::GetName().
void G4HepRepFileSceneHandler::BeginModeling () virtual
Reimplemented from G4VSceneHandler.
Definition at line 95 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 95 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::BeginModeling(), G4VisManager::CurrentTrajDrawModel(), G4VTrajectoryModel::GetContext(), G4VisManager::GetInstance(), and trajContext.
void G4HepRepFileSceneHandler::BeginPrimitives2D (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
Definition at line 109 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 109 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::BeginPrimitives2D(), G4cout, and G4endl.
void G4HepRepFileSceneHandler::CheckFileOpen () private
Definition at line 1547 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1547 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttDef(), G4HepRepFileXMLWriter::addAttValue(), G4UIcommand::ConvertToString(), fileCounter, G4cout, G4Date, G4endl, G4Version, G4HepRepMessenger::getFileDir(), G4HepRepMessenger::getFileName(), G4HepRepMessenger::GetInstance(), G4HepRepMessenger::getOverwrite(), hepRepXMLWriter, G4HepRepFileXMLWriter::isOpen, and G4HepRepFileXMLWriter::open().
Referenced by AddCompound(), and AddHepRepInstance().
void G4HepRepFileSceneHandler::ClearTransientStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 1591 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1591 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::fpViewer.
void G4HepRepFileSceneHandler::EndModeling () virtual
Reimplemented from G4VSceneHandler.
Definition at line 104 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 104 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::EndModeling().
void G4HepRepFileSceneHandler::EndPrimitives2D () virtual
Reimplemented from G4VSceneHandler.
Definition at line 117 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 117 of file G4HepRepFileSceneHandler.cc
References G4VSceneHandler::EndPrimitives2D(), G4cout, G4endl, and inPrimitives2D.
G4HepRepFileXMLWriter * G4HepRepFileSceneHandler::GetHepRepXMLWriter ()
Definition at line 1316 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1316 of file G4HepRepFileSceneHandler.cc
References hepRepXMLWriter.
Referenced by G4HepRepFileSceneHandler().
void G4HepRepFileSceneHandler::InitHit ()
Definition at line 1014 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1014 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), G4HepRepFileXMLWriter::addInstance(), doneInitHit, hepRepXMLWriter, hitAttDefs, and hitAttValues.
Referenced by AddPrimitive(), and AddSolid().
void G4HepRepFileSceneHandler::InitTrajectory ()
Definition at line 991 of file G4HepRepFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 991 of file G4HepRepFileSceneHandler.cc
References G4HepRepFileXMLWriter::addAttValue(), G4HepRepFileXMLWriter::addInstance(), doneInitTraj, hepRepXMLWriter, trajAttDefs, and trajAttValues.
Referenced by AddCompound(), and AddPrimitive().
Member Data Documentation
G4bool G4HepRepFileSceneHandler::doneInitHit private
Definition at line 156 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 156 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), G4HepRepFileSceneHandler(), and InitHit().
G4bool G4HepRepFileSceneHandler::doneInitTraj private
Definition at line 154 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 154 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), G4HepRepFileSceneHandler(), and InitTrajectory().
G4bool G4HepRepFileSceneHandler::drawingHit private
Definition at line 155 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 155 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), AddHepRepInstance(), AddPrimitive(), AddSolid(), and G4HepRepFileSceneHandler().
G4bool G4HepRepFileSceneHandler::drawingTraj private
Definition at line 153 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 153 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), AddHepRepInstance(), AddPrimitive(), AddSolid(), and G4HepRepFileSceneHandler().
int G4HepRepFileSceneHandler::fileCounter private
Definition at line 148 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 148 of file G4HepRepFileSceneHandler.hh
Referenced by CheckFileOpen(), and G4HepRepFileSceneHandler().
G4int G4HepRepFileSceneHandler::fSceneIdCount = 0 static protected
Definition at line 141 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 141 of file G4HepRepFileSceneHandler.hh
G4bool G4HepRepFileSceneHandler::haveVisible private
Definition at line 149 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 149 of file G4HepRepFileSceneHandler.hh
Referenced by AddHepRepInstance(), AddPrimitive(), AddSolid(), and G4HepRepFileSceneHandler().
G4HepRepFileXMLWriter* G4HepRepFileSceneHandler::hepRepXMLWriter private
Definition at line 144 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 144 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), AddHepRepInstance(), AddPrimitive(), AddSolid(), CheckFileOpen(), G4HepRepFileSceneHandler(), GetHepRepXMLWriter(), InitHit(), and InitTrajectory().
std::map<G4String,G4AttDef>* G4HepRepFileSceneHandler::hitAttDefs private
Definition at line 163 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 163 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), G4HepRepFileSceneHandler(), and InitHit().
std::vector<G4AttValue>* G4HepRepFileSceneHandler::hitAttValues private
Definition at line 162 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 162 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), G4HepRepFileSceneHandler(), and InitHit().
G4bool G4HepRepFileSceneHandler::inPrimitives2D private
Definition at line 150 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 150 of file G4HepRepFileSceneHandler.hh
Referenced by AddPrimitive(), EndPrimitives2D(), and G4HepRepFileSceneHandler().
std::map<G4String,G4AttDef>* G4HepRepFileSceneHandler::trajAttDefs private
Definition at line 161 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 161 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), G4HepRepFileSceneHandler(), and InitTrajectory().
std::vector<G4AttValue>* G4HepRepFileSceneHandler::trajAttValues private
Definition at line 160 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 160 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), G4HepRepFileSceneHandler(), and InitTrajectory().
const G4VisTrajContext* G4HepRepFileSceneHandler::trajContext private
Definition at line 158 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 158 of file G4HepRepFileSceneHandler.hh
Referenced by AddCompound(), BeginModeling(), and G4HepRepFileSceneHandler().
G4bool G4HepRepFileSceneHandler::warnedAbout2DMarkers private
Definition at line 152 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 152 of file G4HepRepFileSceneHandler.hh
Referenced by AddPrimitive(), and G4HepRepFileSceneHandler().
G4bool G4HepRepFileSceneHandler::warnedAbout3DText private
Definition at line 151 of file G4HepRepFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 151 of file G4HepRepFileSceneHandler.hh
Referenced by AddPrimitive(), and G4HepRepFileSceneHandler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepFileSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/G4HepRepFileSceneHandler.cc