ECCE @ EIC Software: CexmcTrackPointsInLeftRightSet Class Reference
CexmcTrackPointsInLeftRightSet Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPointsInLeftRightSet.hh>
Public Member Functions
CexmcTrackPointsInLeftRightSet (const G4String &name, const CexmcSetup *setup)
void PrintAll (void)
Public Member Functions inherited from CexmcTrackPoints
CexmcTrackPoints (const G4String &name)
void Initialize (G4HCofThisEvent *hcOfThisEvent)
void EndOfEvent (G4HCofThisEvent *hcOfThisEvent)
void DrawAll (void)
void clear (void)
Public Member Functions inherited from CexmcPrimitiveScorer
CexmcPrimitiveScorer (const G4String &name)
virtual ~CexmcPrimitiveScorer ()
void InitializeMessenger (void)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Static Public Member Functions
static CexmcSide GetSide (G4int index)
static G4int GetLeftRightBitsOffset (void)
Protected Member Functions
G4int GetIndex (G4Step *step)
Protected Member Functions inherited from CexmcTrackPoints
G4int GetTrackId (G4Step *step)
G4bool ProcessHits (G4Step *step, G4TouchableHistory *tHistory)
Protected Member Functions inherited from CexmcPrimitiveScorer
void PrintHeader (G4int nmbOfEntries) const
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Protected Attributes
const CexmcSetup * setup
Protected Attributes inherited from CexmcTrackPoints
CexmcTrackPointsCollection * eventMap
Static Protected Attributes
static const G4int leftRightBitsOffset = 24
Detailed Description
Definition at line 54 of file CexmcTrackPointsInLeftRightSet.hh.
View newest version in sPHENIX GitHub at line 54 of file CexmcTrackPointsInLeftRightSet.hh
Constructor & Destructor Documentation
CexmcTrackPointsInLeftRightSet::CexmcTrackPointsInLeftRightSet (const G4String & name, const CexmcSetup * setup)
Definition at line 54 of file CexmcTrackPointsInLeftRightSet.cc.
View newest version in sPHENIX GitHub at line 54 of file CexmcTrackPointsInLeftRightSet.cc
Member Function Documentation
G4int CexmcTrackPointsInLeftRightSet::GetIndex (G4Step * step) protected virtual
Reimplemented from CexmcTrackPoints.
Definition at line 61 of file CexmcTrackPointsInLeftRightSet.cc.
View newest version in sPHENIX GitHub at line 61 of file CexmcTrackPointsInLeftRightSet.cc
References G4Step::GetPreStepPoint(), CexmcTrackPoints::GetTrackId(), CexmcSetup::IsRightDetector(), leftRightBitsOffset, and setup.
G4int CexmcTrackPointsInLeftRightSet::GetLeftRightBitsOffset (void) inline static
Definition at line 88 of file CexmcTrackPointsInLeftRightSet.hh.
View newest version in sPHENIX GitHub at line 88 of file CexmcTrackPointsInLeftRightSet.hh
References leftRightBitsOffset.
CexmcSide CexmcTrackPointsInLeftRightSet::GetSide (G4int index) inline static
Definition at line 79 of file CexmcTrackPointsInLeftRightSet.hh.
View newest version in sPHENIX GitHub at line 79 of file CexmcTrackPointsInLeftRightSet.hh
References CexmcLeft, CexmcRight, and leftRightBitsOffset.
Referenced by CexmcTrackPointsDigitizer::Digitize().
void CexmcTrackPointsInLeftRightSet::PrintAll (void) virtual
Reimplemented from CexmcTrackPoints.
Definition at line 74 of file CexmcTrackPointsInLeftRightSet.cc.
View newest version in sPHENIX GitHub at line 74 of file CexmcTrackPointsInLeftRightSet.cc
References G4VTHitsMap< T, Map_t >::entries(), CexmcTrackPoints::eventMap, G4BestUnit, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), leftRightBitsOffset, and CexmcPrimitiveScorer::PrintHeader().
Member Data Documentation
const G4int CexmcTrackPointsInLeftRightSet::leftRightBitsOffset = 24 static protected
Definition at line 75 of file CexmcTrackPointsInLeftRightSet.hh.
View newest version in sPHENIX GitHub at line 75 of file CexmcTrackPointsInLeftRightSet.hh
Referenced by CexmcTrackPointsInCalorimeter::GetIndex(), GetIndex(), GetLeftRightBitsOffset(), CexmcTrackPointsInCalorimeter::GetRow(), GetSide(), CexmcTrackPointsInCalorimeter::PrintAll(), and PrintAll().
const CexmcSetup* CexmcTrackPointsInLeftRightSet::setup protected
Definition at line 67 of file CexmcTrackPointsInLeftRightSet.hh.
View newest version in sPHENIX GitHub at line 67 of file CexmcTrackPointsInLeftRightSet.hh
Referenced by CexmcTrackPointsInCalorimeter::GetIndex(), and GetIndex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPointsInLeftRightSet.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcTrackPointsInLeftRightSet.cc