ECCE @ EIC Software: G4GIDI Class Reference
G4GIDI Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4GIDI.hh>
Public Member Functions
G4GIDI (int ip, std::string &dataDirectory)
G4GIDI (int ip, std::list< std::string > &dataDirectory)
~G4GIDI ()
int numberOfDataDirectories (void)
int addDataDirectory (std::string &dataDirectory)
int removeDataDirectory (std::string &dataDirectory)
std::string getDataDirectoryAtIndex (int index)
std::vector< std::string > * getDataDirectories (void)
bool isThisDataAvailable (std::string &lib_name, int iZ, int iA, int iM=0)
bool isThisDataAvailable (std::string &lib_name, std::string &targetName)
char * dataFilename (std::string &lib_name, int iZ, int iA, int iM=0)
char * dataFilename (std::string &lib_name, std::string &targetName)
std::vector< std::string > * getNamesOfAvailableLibraries (int iZ, int iA, int iM=0)
std::vector< std::string > * getNamesOfAvailableLibraries (std::string &targetName)
std::vector< std::string > * getNamesOfAvailableTargets (void)
G4GIDI_target * readTarget (std::string &lib_name, int iZ, int iA, int iM=0, bool bind=true)
G4GIDI_target * readTarget (std::string &lib_name, std::string &targetName, bool bind=true)
G4GIDI_target * getAlreadyReadTarget (int iZ, int iA, int iM=0)
G4GIDI_target * getAlreadyReadTarget (std::string &targetName)
int freeTarget (int iZ, int iA, int iM=0)
int freeTarget (std::string &targetSymbol)
int freeTarget (G4GIDI_target *target)
std::vector< std::string > * getListOfReadTargetsNames (void)
Private Member Functions
int init (int ip)
Private Attributes
int projectileID
std::string projectile
std::list< G4GIDI_map * > dataDirectories
std::vector< G4GIDI_target * > targets
Detailed Description
Definition at line 43 of file G4GIDI.hh.
View newest version in sPHENIX GitHub at line 43 of file G4GIDI.hh
Constructor & Destructor Documentation
G4GIDI::G4GIDI (int ip, std::string & dataDirectory)
Definition at line 40 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 40 of file G4GIDI.cc
References init().
G4GIDI::G4GIDI (int ip, std::list< std::string > & dataDirectory)
Definition at line 48 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GIDI.cc
References init().
G4GIDI::~G4GIDI (void)
Definition at line 58 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 58 of file G4GIDI.cc
Member Function Documentation
int G4GIDI::addDataDirectory (std::string & dataDirectory)
Definition at line 110 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 110 of file G4GIDI.cc
char * G4GIDI::dataFilename (std::string & lib_name, int iZ, int iA, int iM = 0)
Definition at line 196 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 196 of file G4GIDI.cc
References G4GIDI_Misc_Z_A_m_ToName(), and smr_freeMemory().
char * G4GIDI::dataFilename (std::string & lib_name, std::string & targetName)
Definition at line 209 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 209 of file G4GIDI.cc
References MCGIDI_map_findTarget().
int G4GIDI::freeTarget (int iZ, int iA, int iM = 0)
Definition at line 363 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 363 of file G4GIDI.cc
References G4GIDI_Misc_Z_A_m_ToName(), and smr_freeMemory().
int G4GIDI::freeTarget (std::string & targetSymbol)
Definition at line 377 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 377 of file G4GIDI.cc
int G4GIDI::freeTarget (G4GIDI_target * target)
Definition at line 347 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 347 of file G4GIDI.cc
G4GIDI_target * G4GIDI::getAlreadyReadTarget (int iZ, int iA, int iM = 0)
Definition at line 321 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 321 of file G4GIDI.cc
References G4GIDI_Misc_Z_A_m_ToName(), and smr_freeMemory().
G4GIDI_target * G4GIDI::getAlreadyReadTarget (std::string & targetName)
Definition at line 335 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 335 of file G4GIDI.cc
vector< string > * G4GIDI::getDataDirectories (void)
Definition at line 157 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 157 of file G4GIDI.cc
References v.
string G4GIDI::getDataDirectoryAtIndex (int index)
Definition at line 140 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 140 of file G4GIDI.cc
vector< string > * G4GIDI::getListOfReadTargetsNames (void)
Definition at line 389 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 389 of file G4GIDI.cc
vector< string > * G4GIDI::getNamesOfAvailableLibraries (int iZ, int iA, int iM = 0)
Definition at line 237 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 237 of file G4GIDI.cc
References G4GIDI_Misc_Z_A_m_ToName(), and smr_freeMemory().
Referenced by G4LENDManager::GetLENDTarget(), and G4LENDManager::IsLENDTargetAvailable().
vector< string > * G4GIDI::getNamesOfAvailableLibraries (std::string & targetName)
Definition at line 251 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 251 of file G4GIDI.cc
References MCGIDI_mapEntry_s::evaluation, MCGIDI_map_findAllOfTarget(), MCGIDI_map_free(), MCGIDI_map_getFirstEntry(), and MCGIDI_map_getNextEntry().
vector< string > * G4GIDI::getNamesOfAvailableTargets (void)
Definition at line 271 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 271 of file G4GIDI.cc
References getNamesOfAvailableTargets_walker(), and MCGIDI_map_walkTree().
int G4GIDI::init (int ip) private
Definition at line 77 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 77 of file G4GIDI.cc
References printf().
bool G4GIDI::isThisDataAvailable (std::string & lib_name, int iZ, int iA, int iM = 0)
Definition at line 169 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 169 of file G4GIDI.cc
References b, G4GIDI_Misc_Z_A_m_ToName(), and smr_freeMemory().
Referenced by G4LENDManager::GetLENDTarget().
bool G4GIDI::isThisDataAvailable (std::string & lib_name, std::string & targetName)
Definition at line 183 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 183 of file G4GIDI.cc
References smr_freeMemory().
int G4GIDI::numberOfDataDirectories (void)
Definition at line 103 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 103 of file G4GIDI.cc
G4GIDI_target * G4GIDI::readTarget (std::string & lib_name, int iZ, int iA, int iM = 0, bool bind = true)
Definition at line 289 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 289 of file G4GIDI.cc
References G4GIDI_Misc_Z_A_m_ToName(), and smr_freeMemory().
Referenced by G4LENDManager::GetLENDTarget().
G4GIDI_target * G4GIDI::readTarget (std::string & lib_name, std::string & targetName, bool bind = true)
Definition at line 303 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 303 of file G4GIDI.cc
References smr_freeMemory().
int G4GIDI::removeDataDirectory (std::string & dataDirectory)
Definition at line 126 of file G4GIDI.cc.
View newest version in sPHENIX GitHub at line 126 of file G4GIDI.cc
Member Data Documentation
std::list<G4GIDI_map *> G4GIDI::dataDirectories private
Definition at line 48 of file G4GIDI.hh.
View newest version in sPHENIX GitHub at line 48 of file G4GIDI.hh
std::string G4GIDI::projectile private
Definition at line 47 of file G4GIDI.hh.
View newest version in sPHENIX GitHub at line 47 of file G4GIDI.hh
int G4GIDI::projectileID private
Definition at line 46 of file G4GIDI.hh.
View newest version in sPHENIX GitHub at line 46 of file G4GIDI.hh
std::vector<G4GIDI_target *> G4GIDI::targets private
Definition at line 49 of file G4GIDI.hh.
View newest version in sPHENIX GitHub at line 49 of file G4GIDI.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4GIDI.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4GIDI.cc