ECCE @ EIC Software: WLSSteppingAction Class Reference
WLSSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSSteppingAction.hh>
Public Member Functions
WLSSteppingAction (WLSDetectorConstruction *)
virtual ~WLSSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
void SetBounceLimit (G4int)
G4int GetNumberOfBounces ()
G4int GetNumberOfClad1Bounces ()
G4int GetNumberOfClad2Bounces ()
G4int GetNumberOfWLSBounces ()
G4int ResetSuccessCounter ()
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Member Functions
void ResetCounters ()
void SaveRandomStatus (G4String subDir)
Private Attributes
G4int fBounceLimit
G4int fCounterEnd
G4int fCounterMid
G4int fCounterBounce
G4int fCounterWLSBounce
G4int fCounterClad1Bounce
G4int fCounterClad2Bounce
G4double fInitGamma
G4double fInitTheta
G4OpBoundaryProcess * fOpProcess
WLSDetectorConstruction * fDetector
WLSSteppingActionMessenger * fSteppingMessenger
Static Private Attributes
static G4int fMaxRndmSave = 10000
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 47 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file WLSSteppingAction.hh
Constructor & Destructor Documentation
WLSSteppingAction::WLSSteppingAction (WLSDetectorConstruction * detector)
Definition at line 68 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 68 of file WLSSteppingAction.cc
References fBounceLimit, fCounterEnd, fCounterMid, fOpProcess, fSteppingMessenger, and ResetCounters().
WLSSteppingAction::~WLSSteppingAction () virtual
Definition at line 84 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 84 of file WLSSteppingAction.cc
References fSteppingMessenger.
Member Function Documentation
G4int WLSSteppingAction::GetNumberOfBounces ()
Definition at line 95 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 95 of file WLSSteppingAction.cc
References fCounterBounce.
G4int WLSSteppingAction::GetNumberOfClad1Bounces ()
Definition at line 99 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 99 of file WLSSteppingAction.cc
References fCounterClad1Bounce.
G4int WLSSteppingAction::GetNumberOfClad2Bounces ()
Definition at line 103 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 103 of file WLSSteppingAction.cc
References fCounterClad2Bounce.
G4int WLSSteppingAction::GetNumberOfWLSBounces ()
Definition at line 107 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 107 of file WLSSteppingAction.cc
References fCounterWLSBounce.
void WLSSteppingAction::ResetCounters () inline private
Definition at line 97 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 97 of file WLSSteppingAction.hh
References fCounterBounce, fCounterClad1Bounce, fCounterClad2Bounce, fCounterWLSBounce, fInitGamma, and fInitTheta.
Referenced by UserSteppingAction(), and WLSSteppingAction().
G4int WLSSteppingAction::ResetSuccessCounter ()
Definition at line 111 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 111 of file WLSSteppingAction.cc
References fCounterEnd.
void WLSSteppingAction::SaveRandomStatus (G4String subDir) inline private
Definition at line 117 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 117 of file WLSSteppingAction.cc
References G4UImanager::ApplyCommand(), fMaxRndmSave, G4RunManager::GetCurrentEvent(), G4RunManager::GetCurrentRun(), G4Event::GetEventID(), G4RunManager::GetRandomNumberStoreDir(), G4Run::GetRunID(), G4RunManager::GetRunManager(), and G4UImanager::GetUIpointer().
void WLSSteppingAction::SetBounceLimit (G4int i)
Definition at line 91 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 91 of file WLSSteppingAction.cc
References fBounceLimit.
void WLSSteppingAction::UserSteppingAction (const G4Step * theStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 145 of file WLSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 145 of file WLSSteppingAction.cc
References WLSUserTrackInformation::AddStatusFlag(), deg, Detection, G4ProcessVector::entries(), EscapedFromReadOut, EscapedFromSide, fAlive, fBounceLimit, fCounterBounce, fCounterClad1Bounce, fCounterClad2Bounce, fCounterEnd, fCounterMid, fCounterWLSBounce, fDetector, G4SDManager::FindSensitiveDetector(), fInitGamma, fOpProcess, FresnelReflection, FresnelRefraction, fStopAndKill, G4cout, G4endl, G4Track::GetCurrentStepNumber(), G4VPhysicalVolume::GetName(), G4Track::GetParentID(), G4StepPoint::GetPhysicalVolume(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4ProcessManager::GetPostStepProcessVector(), G4Step::GetPreStepPoint(), G4ParticleDefinition::GetProcessManager(), G4SDManager::GetSDMpointer(), G4OpBoundaryProcess::GetStatus(), G4Step::GetTrack(), G4Track::GetTrackStatus(), G4Track::GetUserInformation(), G4Track::GetVertexMomentumDirection(), WLSDetectorConstruction::GetWLSFiberEnd(), InsideOfFiber, WLSDetectorConstruction::IsPerfectFiber(), WLSUserTrackInformation::IsStatus(), LambertianReflection, LobeReflection, murderee, G4OpticalPhoton::OpticalPhoton(), OutsideOfFiber, WLSPhotonDetSD::ProcessHits_constStep(), rad, ReflectedAtMirror, ReflectedAtReadOut, ResetCounters(), SameMaterial, WLSUserTrackInformation::SetExitPosition(), G4Track::SetTrackStatus(), SpikeReflection, TotalInternalReflection, typeDoIt, Acts::Undefined, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, and CLHEP::Hep3Vector::z().
Member Data Documentation
G4int WLSSteppingAction::fBounceLimit private
Definition at line 69 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 69 of file WLSSteppingAction.hh
Referenced by SetBounceLimit(), UserSteppingAction(), and WLSSteppingAction().
G4int WLSSteppingAction::fCounterBounce private
Definition at line 75 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file WLSSteppingAction.hh
Referenced by GetNumberOfBounces(), ResetCounters(), and UserSteppingAction().
G4int WLSSteppingAction::fCounterClad1Bounce private
Definition at line 79 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 79 of file WLSSteppingAction.hh
Referenced by GetNumberOfClad1Bounces(), ResetCounters(), and UserSteppingAction().
G4int WLSSteppingAction::fCounterClad2Bounce private
Definition at line 81 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 81 of file WLSSteppingAction.hh
Referenced by GetNumberOfClad2Bounces(), ResetCounters(), and UserSteppingAction().
G4int WLSSteppingAction::fCounterEnd private
Definition at line 71 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file WLSSteppingAction.hh
Referenced by ResetSuccessCounter(), UserSteppingAction(), and WLSSteppingAction().
G4int WLSSteppingAction::fCounterMid private
Definition at line 73 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file WLSSteppingAction.hh
Referenced by UserSteppingAction(), and WLSSteppingAction().
G4int WLSSteppingAction::fCounterWLSBounce private
Definition at line 77 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file WLSSteppingAction.hh
Referenced by GetNumberOfWLSBounces(), ResetCounters(), and UserSteppingAction().
WLSDetectorConstruction* WLSSteppingAction::fDetector private
Definition at line 93 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 93 of file WLSSteppingAction.hh
Referenced by UserSteppingAction().
G4double WLSSteppingAction::fInitGamma private
Definition at line 84 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 84 of file WLSSteppingAction.hh
Referenced by ResetCounters(), and UserSteppingAction().
G4double WLSSteppingAction::fInitTheta private
Definition at line 86 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 86 of file WLSSteppingAction.hh
Referenced by ResetCounters().
G4int WLSSteppingAction::fMaxRndmSave = 10000 static private
Definition at line 91 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 91 of file WLSSteppingAction.hh
Referenced by SaveRandomStatus().
G4OpBoundaryProcess* WLSSteppingAction::fOpProcess private
Definition at line 88 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 88 of file WLSSteppingAction.hh
Referenced by UserSteppingAction(), and WLSSteppingAction().
WLSSteppingActionMessenger* WLSSteppingAction::fSteppingMessenger private
Definition at line 95 of file WLSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 95 of file WLSSteppingAction.hh
Referenced by WLSSteppingAction(), and ~WLSSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSSteppingAction.cc