ECCE @ EIC Software: MarshaledExN04CalorimeterHit Class Reference
MarshaledExN04CalorimeterHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledExN04CalorimeterHit.h>
Public Member Functions
MarshaledExN04CalorimeterHit (ExN04CalorimeterHit *objptr)
MarshaledExN04CalorimeterHit (void *buf, char chIsUnmarshaling= 'u')
~MarshaledExN04CalorimeterHit ()
ExN04CalorimeterHit * unmarshal ()
void unmarshalTo (ExN04CalorimeterHit *obj)
void marshal1 ()
void unmarshal1 ()
void marshal2 ()
void unmarshal2 ()
void marshal3 ()
void unmarshal3 ()
void marshal4 ()
void unmarshal4 ()
Public Member Functions inherited from MarshaledObj
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
Public Attributes
ExN04CalorimeterHit * param
ShadowedMarshaledExN04CalorimeterHit * Shadowed_param
Additional Inherited Members
Static Public Member Functions inherited from MarshaledObj
static int ROUND_UP (int x)
static int ROUND_UP (int x)
Protected Attributes inherited from MarshaledObj
int msh_typechoice
char * msh_buffer
char * msh_field_begin
size_t msh_size
char * msh_cursor
size_t msh_extent
bool msh_isUnmarshalDone
Detailed Description
Definition at line 22 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 22 of file MarshaledExN04CalorimeterHit.h
Constructor & Destructor Documentation
MarshaledExN04CalorimeterHit::MarshaledExN04CalorimeterHit (ExN04CalorimeterHit * objptr) inline
Definition at line 31 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 31 of file MarshaledExN04CalorimeterHit.h
References marshal1(), marshal2(), marshal3(), marshal4(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledExN04CalorimeterHit::MarshaledExN04CalorimeterHit (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 44 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 44 of file MarshaledExN04CalorimeterHit.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledExN04CalorimeterHit::~MarshaledExN04CalorimeterHit () inline
Definition at line 49 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 49 of file MarshaledExN04CalorimeterHit.h
Member Function Documentation
void MarshaledExN04CalorimeterHit::marshal1 () inline
Definition at line 92 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 92 of file MarshaledExN04CalorimeterHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN04CalorimeterHit::GetZ(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN04CalorimeterHit().
void MarshaledExN04CalorimeterHit::marshal2 () inline
Definition at line 149 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 149 of file MarshaledExN04CalorimeterHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN04CalorimeterHit::GetPhi(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN04CalorimeterHit().
void MarshaledExN04CalorimeterHit::marshal3 () inline
Definition at line 206 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 206 of file MarshaledExN04CalorimeterHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN04CalorimeterHit::GetEdep(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN04CalorimeterHit().
void MarshaledExN04CalorimeterHit::marshal4 () inline
Definition at line 263 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 263 of file MarshaledExN04CalorimeterHit.h
References MarshaledObj::EXTEND_BUFFER(), ExN04CalorimeterHit::GetPos(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledExN04CalorimeterHit().
ExN04CalorimeterHit* MarshaledExN04CalorimeterHit::unmarshal () inline
Definition at line 55 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 55 of file MarshaledExN04CalorimeterHit.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, unmarshal1(), unmarshal2(), unmarshal3(), and unmarshal4().
Referenced by MarshaledG4HitsCollection::unmarshal1().
void MarshaledExN04CalorimeterHit::unmarshal1 () inline
Definition at line 133 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 133 of file MarshaledExN04CalorimeterHit.h
References ExN04CalorimeterHit::GetPhi(), int(), MarshaledObj::msh_cursor, param, and ExN04CalorimeterHit::SetCellID().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN04CalorimeterHit::unmarshal2 () inline
Definition at line 190 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 190 of file MarshaledExN04CalorimeterHit.h
References ExN04CalorimeterHit::GetZ(), int(), MarshaledObj::msh_cursor, param, and ExN04CalorimeterHit::SetCellID().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN04CalorimeterHit::unmarshal3 () inline
Definition at line 247 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 247 of file MarshaledExN04CalorimeterHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN04CalorimeterHit::SetEdep().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN04CalorimeterHit::unmarshal4 () inline
Definition at line 304 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 304 of file MarshaledExN04CalorimeterHit.h
References int(), MarshaledObj::msh_cursor, param, and ExN04CalorimeterHit::SetPos().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledExN04CalorimeterHit::unmarshalTo (ExN04CalorimeterHit * obj) inline
Definition at line 75 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 75 of file MarshaledExN04CalorimeterHit.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, unmarshal1(), unmarshal2(), unmarshal3(), and unmarshal4().
Member Data Documentation
ExN04CalorimeterHit* MarshaledExN04CalorimeterHit::param
Definition at line 24 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 24 of file MarshaledExN04CalorimeterHit.h
Referenced by marshal1(), marshal2(), marshal3(), marshal4(), MarshaledExN04CalorimeterHit(), unmarshal(), unmarshal1(), unmarshal2(), unmarshal3(), unmarshal4(), and unmarshalTo().
ShadowedMarshaledExN04CalorimeterHit* MarshaledExN04CalorimeterHit::Shadowed_param
Definition at line 25 of file MarshaledExN04CalorimeterHit.h.
View newest version in sPHENIX GitHub at line 25 of file MarshaledExN04CalorimeterHit.h
Referenced by MarshaledExN04CalorimeterHit(), unmarshal(), and unmarshalTo().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledExN04CalorimeterHit.h