ECCE @ EIC Software: G4ecpssrBaseKxsModel Class Reference
G4ecpssrBaseKxsModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ecpssrBaseKxsModel.hh>
Public Member Functions
G4ecpssrBaseKxsModel ()
~G4ecpssrBaseKxsModel ()
G4double CalculateCrossSection (G4int, G4double, G4double)
G4double ExpIntFunction (G4int n, G4double x)
Public Member Functions inherited from G4VecpssrKModel
G4VecpssrKModel ()
virtual ~G4VecpssrKModel ()
Private Types
typedef std::map< double,
std::map< double, double > > TriDimensionMap
typedef std::map< double,
std::vector< double > > VecMap
Private Member Functions
G4ecpssrBaseKxsModel (const G4ecpssrBaseKxsModel &)
G4ecpssrBaseKxsModel & operator= (const G4ecpssrBaseKxsModel &right)
G4double FunctionFK (G4double k, G4double theta)
G4double LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
Private Attributes
TriDimensionMap FKData
std::vector< double > dummyVec
VecMap aVecMap
G4int verboseLevel
G4CrossSectionDataSet * tableC1
G4CrossSectionDataSet * tableC2
G4CrossSectionDataSet * tableC3
Detailed Description
Definition at line 38 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 38 of file G4ecpssrBaseKxsModel.hh
Member Typedef Documentation
typedef std::map<double, std::map<double, double> > G4ecpssrBaseKxsModel::TriDimensionMap private
Definition at line 75 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ecpssrBaseKxsModel.hh
typedef std::map<double, std::vector<double> > G4ecpssrBaseKxsModel::VecMap private
Definition at line 80 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ecpssrBaseKxsModel.hh
Constructor & Destructor Documentation
G4ecpssrBaseKxsModel::G4ecpssrBaseKxsModel ()
Definition at line 46 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ecpssrBaseKxsModel.cc
References aVecMap, dummyVec, FatalException, FKData, G4Exception(), G4CrossSectionDataSet::LoadData(), tableC1, tableC2, tableC3, verboseLevel, x, and y.
G4ecpssrBaseKxsModel::~G4ecpssrBaseKxsModel ()
Definition at line 114 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 114 of file G4ecpssrBaseKxsModel.cc
References tableC1, tableC2, and tableC3.
G4ecpssrBaseKxsModel::G4ecpssrBaseKxsModel (const G4ecpssrBaseKxsModel &) private
Member Function Documentation
G4double G4ecpssrBaseKxsModel::CalculateCrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrKModel.
Definition at line 197 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 197 of file G4ecpssrBaseKxsModel.cc
References G4Alpha::Alpha(), source.hepunit::amu_c2, barn, G4AtomicShell::BindingEnergy(), source.hepunit::Bohr_radius, C1, C2, C3, e, source.hepunit::electron_mass_c2, eplus, eV, ExpIntFunction(), G4CrossSectionDataSet::FindValue(), source.hepunit::fine_structure_const, FunctionFK(), G4cout, G4endl, G4Exp(), G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), GT, G4AtomicTransitionManager::Instance(), G4NistManager::Instance(), pi, G4Proton::Proton(), G4AtomicTransitionManager::Shell(), tableC1, tableC2, tableC3, verboseLevel, and x.
G4double G4ecpssrBaseKxsModel::ExpIntFunction (G4int n, G4double x)
Definition at line 125 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ecpssrBaseKxsModel.cc
References a, b, c, d, eps, G4cout, G4endl, G4Exp(), Acts::UnitConstants::h, n, and x.
Referenced by CalculateCrossSection().
G4double G4ecpssrBaseKxsModel::FunctionFK (G4double k, G4double theta) private
Definition at line 542 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 542 of file G4ecpssrBaseKxsModel.cc
References aVecMap, dummyVec, e, FKData, k, QuadInterpolator(), t1, and t2.
Referenced by CalculateCrossSection().
G4double G4ecpssrBaseKxsModel::LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 646 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 646 of file G4ecpssrBaseKxsModel.cc
References d1, d2, and G4Exp().
G4double G4ecpssrBaseKxsModel::LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 660 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 660 of file G4ecpssrBaseKxsModel.cc
References a, and b.
Referenced by QuadInterpolator().
G4ecpssrBaseKxsModel& G4ecpssrBaseKxsModel::operator= (const G4ecpssrBaseKxsModel & right) private
G4double G4ecpssrBaseKxsModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 675 of file G4ecpssrBaseKxsModel.cc.
View newest version in sPHENIX GitHub at line 675 of file G4ecpssrBaseKxsModel.cc
References LogLogInterpolate().
Referenced by FunctionFK().
Member Data Documentation
VecMap G4ecpssrBaseKxsModel::aVecMap private
Definition at line 81 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ecpssrBaseKxsModel.hh
Referenced by FunctionFK(), and G4ecpssrBaseKxsModel().
std::vector<double> G4ecpssrBaseKxsModel::dummyVec private
Definition at line 78 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ecpssrBaseKxsModel.hh
Referenced by FunctionFK(), and G4ecpssrBaseKxsModel().
TriDimensionMap G4ecpssrBaseKxsModel::FKData private
Definition at line 77 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ecpssrBaseKxsModel.hh
Referenced by FunctionFK(), and G4ecpssrBaseKxsModel().
G4CrossSectionDataSet* G4ecpssrBaseKxsModel::tableC1 private
Definition at line 85 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ecpssrBaseKxsModel.hh
Referenced by CalculateCrossSection(), G4ecpssrBaseKxsModel(), and ~G4ecpssrBaseKxsModel().
G4CrossSectionDataSet* G4ecpssrBaseKxsModel::tableC2 private
Definition at line 86 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ecpssrBaseKxsModel.hh
Referenced by CalculateCrossSection(), G4ecpssrBaseKxsModel(), and ~G4ecpssrBaseKxsModel().
G4CrossSectionDataSet* G4ecpssrBaseKxsModel::tableC3 private
Definition at line 87 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ecpssrBaseKxsModel.hh
Referenced by CalculateCrossSection(), G4ecpssrBaseKxsModel(), and ~G4ecpssrBaseKxsModel().
G4int G4ecpssrBaseKxsModel::verboseLevel private
Definition at line 83 of file G4ecpssrBaseKxsModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ecpssrBaseKxsModel.hh
Referenced by CalculateCrossSection(), and G4ecpssrBaseKxsModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ecpssrBaseKxsModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4ecpssrBaseKxsModel.cc