ECCE @ EIC Software: ExN04StackingAction Class Reference
ExN04StackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04StackingAction.hh>
Public Member Functions
ExN04StackingAction ()
virtual ~ExN04StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
void SetNRequestMuon (G4int val)
G4int GetNRequestMuon () const
void SetNRequestIsoMuon (G4int val)
G4int GetNRequestIsoMuon () const
void SetNIsolation (G4int val)
G4int GetNIsolation () const
void SetRoIAngle (G4double val)
G4double GetRoIAngle () const
ExN04StackingAction ()
virtual ~ExN04StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
void SetNRequestMuon (G4int val)
G4int GetNRequestMuon () const
void SetNRequestIsoMuon (G4int val)
G4int GetNRequestIsoMuon () const
void SetNIsolation (G4int val)
G4int GetNIsolation () const
void SetRoIAngle (G4double val)
G4double GetRoIAngle () const
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Member Functions
G4bool InsideRoI (const G4Track *aTrack, G4double ang)
G4VHitsCollection * GetCollection (G4String colName)
G4bool InsideRoI (const G4Track *aTrack, G4double ang)
G4VHitsCollection * GetCollection (G4String colName)
Private Attributes
ExN04TrackerHitsCollection * fTrkHits
ExN04MuonHitsCollection * fMuonHits
ExN04StackingActionMessenger * fMessenger
G4int fStage
G4int fReqMuon
G4int fReqIsoMuon
G4int fReqIso
G4double fAngRoI
ExN04TrackerHitsCollection * trkHits
ExN04MuonHitsCollection * muonHits
ExN04StackingActionMessenger * theMessenger
G4int stage
G4int reqMuon
G4int reqIsoMuon
G4int reqIso
G4double angRoI
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 43 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file ExN04StackingAction.hh
Constructor & Destructor Documentation
ExN04StackingAction::ExN04StackingAction ()
Definition at line 44 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file ExN04StackingAction.cc
References deg, fAngRoI, fMessenger, fReqIso, and fReqMuon.
ExN04StackingAction::~ExN04StackingAction () virtual
Definition at line 55 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 55 of file ExN04StackingAction.cc
References fMessenger.
ExN04StackingAction::ExN04StackingAction ()
virtual ExN04StackingAction::~ExN04StackingAction () virtual
Member Function Documentation
G4ClassificationOfNewTrack ExN04StackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 60 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 60 of file ExN04StackingAction.cc
References fAngRoI, fKill, fStage, fSuspend, fUrgent, fWaiting, G4Track::GetDefinition(), G4Track::GetParentID(), G4ParticleDefinition::GetPDGCharge(), G4Track::GetTrackStatus(), InsideRoI(), G4MuonMinus::MuonMinusDefinition(), and G4MuonPlus::MuonPlusDefinition().
virtual G4ClassificationOfNewTrack ExN04StackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
G4VHitsCollection* ExN04StackingAction::GetCollection (G4String colName) private
G4VHitsCollection * ExN04StackingAction::GetCollection (G4String colName) private
Definition at line 124 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 124 of file ExN04StackingAction.cc
References G4SDManager::GetCollectionID(), G4RunManager::GetCurrentEvent(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4RunManager::GetRunManager(), and G4SDManager::GetSDMpointer().
Referenced by InsideRoI(), and NewStage().
G4int ExN04StackingAction::GetNIsolation () const inline
Definition at line 57 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04StackingAction.hh
References fReqIso.
Referenced by ExN04StackingActionMessenger::GetCurrentValue().
G4int ExN04StackingAction::GetNIsolation () const inline
Definition at line 75 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN04StackingAction.hh
References reqIso.
G4int ExN04StackingAction::GetNRequestIsoMuon () const inline
Definition at line 55 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04StackingAction.hh
References fReqIsoMuon.
Referenced by ExN04StackingActionMessenger::GetCurrentValue().
G4int ExN04StackingAction::GetNRequestIsoMuon () const inline
Definition at line 73 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file ExN04StackingAction.hh
References reqIsoMuon.
G4int ExN04StackingAction::GetNRequestMuon () const inline
Definition at line 53 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file ExN04StackingAction.hh
References fReqMuon.
Referenced by ExN04StackingActionMessenger::GetCurrentValue().
G4int ExN04StackingAction::GetNRequestMuon () const inline
Definition at line 71 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04StackingAction.hh
References reqMuon.
G4double ExN04StackingAction::GetRoIAngle () const inline
Definition at line 59 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file ExN04StackingAction.hh
References fAngRoI.
Referenced by ExN04StackingActionMessenger::GetCurrentValue().
G4double ExN04StackingAction::GetRoIAngle () const inline
Definition at line 77 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file ExN04StackingAction.hh
References angRoI.
G4bool ExN04StackingAction::InsideRoI (const G4Track * aTrack, G4double ang) private
G4bool ExN04StackingAction::InsideRoI (const G4Track * aTrack, G4double ang) private
Definition at line 102 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 102 of file ExN04StackingAction.cc
References CLHEP::Hep3Vector::angle(), G4THitsCollection< T >::entries(), fMuonHits, G4cerr, G4endl, GetCollection(), and G4Track::GetPosition().
Referenced by ClassifyNewTrack().
void ExN04StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 139 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 139 of file ExN04StackingAction.cc
References CLHEP::Hep3Vector::angle(), G4StackManager::clear(), G4THitsCollection< T >::entries(), fAngRoI, fMuonHits, fReqIso, fReqIsoMuon, fReqMuon, fStage, fTrkHits, G4cerr, G4cout, G4endl, GetCollection(), G4StackManager::ReClassify(), and G4UserStackingAction::stackManager.
virtual void ExN04StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
void ExN04StackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 212 of file ExN04StackingAction.cc.
View newest version in sPHENIX GitHub at line 212 of file ExN04StackingAction.cc
References fMuonHits, fStage, and fTrkHits.
virtual void ExN04StackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
void ExN04StackingAction::SetNIsolation (G4int val) inline
Definition at line 56 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file ExN04StackingAction.hh
References fReqIso.
void ExN04StackingAction::SetNIsolation (G4int val) inline
Definition at line 74 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 74 of file ExN04StackingAction.hh
References reqIso.
void ExN04StackingAction::SetNRequestIsoMuon (G4int val) inline
Definition at line 54 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04StackingAction.hh
References fReqIsoMuon.
void ExN04StackingAction::SetNRequestIsoMuon (G4int val) inline
Definition at line 72 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 72 of file ExN04StackingAction.hh
References reqIsoMuon.
void ExN04StackingAction::SetNRequestMuon (G4int val) inline
Definition at line 52 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file ExN04StackingAction.hh
References fReqMuon.
void ExN04StackingAction::SetNRequestMuon (G4int val) inline
Definition at line 70 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file ExN04StackingAction.hh
References reqMuon.
void ExN04StackingAction::SetRoIAngle (G4double val) inline
Definition at line 58 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file ExN04StackingAction.hh
References fAngRoI.
void ExN04StackingAction::SetRoIAngle (G4double val) inline
Definition at line 76 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN04StackingAction.hh
References angRoI.
Member Data Documentation
G4double ExN04StackingAction::angRoI private
Definition at line 67 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN04StackingAction.hh
Referenced by GetRoIAngle(), and SetRoIAngle().
G4double ExN04StackingAction::fAngRoI private
Definition at line 73 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file ExN04StackingAction.hh
Referenced by ClassifyNewTrack(), ExN04StackingAction(), GetRoIAngle(), NewStage(), and SetRoIAngle().
ExN04StackingActionMessenger* ExN04StackingAction::fMessenger private
Definition at line 67 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN04StackingAction.hh
Referenced by ExN04StackingAction(), and ~ExN04StackingAction().
ExN04MuonHitsCollection* ExN04StackingAction::fMuonHits private
Definition at line 66 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file ExN04StackingAction.hh
Referenced by InsideRoI(), NewStage(), and PrepareNewEvent().
G4int ExN04StackingAction::fReqIso private
Definition at line 72 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 72 of file ExN04StackingAction.hh
Referenced by ExN04StackingAction(), GetNIsolation(), NewStage(), and SetNIsolation().
G4int ExN04StackingAction::fReqIsoMuon private
Definition at line 71 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04StackingAction.hh
Referenced by GetNRequestIsoMuon(), NewStage(), and SetNRequestIsoMuon().
G4int ExN04StackingAction::fReqMuon private
Definition at line 70 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file ExN04StackingAction.hh
Referenced by ExN04StackingAction(), GetNRequestMuon(), NewStage(), and SetNRequestMuon().
G4int ExN04StackingAction::fStage private
Definition at line 69 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04StackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
ExN04TrackerHitsCollection* ExN04StackingAction::fTrkHits private
Definition at line 65 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN04StackingAction.hh
Referenced by NewStage(), and PrepareNewEvent().
ExN04MuonHitsCollection* ExN04StackingAction::muonHits private
Definition at line 60 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file ExN04StackingAction.hh
G4int ExN04StackingAction::reqIso private
Definition at line 66 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file ExN04StackingAction.hh
Referenced by GetNIsolation(), and SetNIsolation().
G4int ExN04StackingAction::reqIsoMuon private
Definition at line 65 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN04StackingAction.hh
Referenced by GetNRequestIsoMuon(), and SetNRequestIsoMuon().
G4int ExN04StackingAction::reqMuon private
Definition at line 64 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN04StackingAction.hh
Referenced by GetNRequestMuon(), and SetNRequestMuon().
G4int ExN04StackingAction::stage private
Definition at line 63 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file ExN04StackingAction.hh
ExN04StackingActionMessenger* ExN04StackingAction::theMessenger private
Definition at line 61 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file ExN04StackingAction.hh
ExN04TrackerHitsCollection* ExN04StackingAction::trkHits private
Definition at line 59 of file ExN04StackingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file ExN04StackingAction.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04StackingAction.cc