ECCE @ EIC Software: StackingAction Class Reference
StackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/StackingAction.hh>
Public Member Functions
StackingAction ()
~StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
~StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
~StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
~StackingAction ()
void SetTrackSecondaries (G4bool value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction (EventAction *)
~StackingAction ()
void SetKillStatus (G4int value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
~StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
~StackingAction ()
void SetKillStatus (G4bool value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
virtual ~StackingAction ()
void SetKillStatus (G4bool value)
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
virtual ~StackingAction ()
void SetKillStatus (G4bool value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
virtual ~StackingAction ()
void SetKillStatus (G4bool value)
void SetKill (const G4String &name)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
virtual ~StackingAction ()
void SetKillAll (G4bool value)
void SetKillEM (G4bool value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
~StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
StackingAction ()
virtual ~StackingAction ()
virtual void NewStage ()
StackingAction ()
virtual ~StackingAction ()
virtual void NewStage ()
StackingAction ()
virtual ~StackingAction ()
virtual void NewStage ()
StackingAction ()
virtual ~StackingAction ()
virtual void NewStage ()
StackingAction ()
virtual ~StackingAction ()
virtual void NewStage ()
StackingAction ()
~StackingAction () override
void NewStage () override
StackingAction ()
virtual ~StackingAction ()
virtual void NewStage ()
StackingAction (DetectorConstruction *)
~StackingAction ()
virtual void SetKillStatus (G4bool value)
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
virtual void PrepareNewEvent ()
Private Attributes
G4bool fTrackSecondaries
StackingMessenger * fStackMessenger
EventAction * fEventAction
G4int fKillSecondary
G4int fPhotoGamma
G4int fComptGamma
G4int fPhotoAuger
G4int fComptAuger
G4int fPixeGamma
G4int fPixeAuger
G4int fElectronDNAGamma
G4int fElectronDNAAuger
G4int fProtonDNAGamma
G4int fProtonDNAAuger
G4int fHydrogenDNAGamma
G4int fHydrogenDNAAuger
G4int fAlphaDNAGamma
G4int fAlphaDNAAuger
G4int fAlphaPlusDNAGamma
G4int fAlphaPlusDNAAuger
G4int fHeliumDNAGamma
G4int fHeliumDNAAuger
G4int fGenericIonDNAGamma
G4int fGenericIonDNAAuger
G4bool fIDdefined
G4bool fKillSecondary
HistoManager * fHistoManager
const G4ParticleDefinition * fParticle
G4bool fKillAll
G4bool fKillEM
DetectorConstruction * fDetector
G4Material * fMatWall
G4double fZcav
G4EmCalculator * fEmCal
G4bool first
G4bool fKillTrack
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Stacking action class : manage the newly generated particles
One wishes do not track secondary neutrino.Therefore one kills it immediately, before created particles will put in a stack.
Stacking action class : manage the newly generated particles
Definition at line 41 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 41 of file StackingAction.hh
Constructor & Destructor Documentation
StackingAction::StackingAction ()
Definition at line 40 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 40 of file StackingAction.cc
StackingAction::~StackingAction ()
delete fStackMessenger;
Definition at line 46 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file StackingAction.cc
StackingAction::StackingAction ()
StackingAction::~StackingAction ()
StackingAction::StackingAction ()
StackingAction::~StackingAction ()
StackingAction::StackingAction ()
StackingAction::~StackingAction ()
StackingAction::StackingAction (EventAction * EA)
Definition at line 47 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file StackingAction.cc
References fStackMessenger.
StackingAction::~StackingAction ()
StackingAction::StackingAction ()
StackingAction::~StackingAction ()
StackingAction::StackingAction ()
StackingAction::~StackingAction ()
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () virtual
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () virtual
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () virtual
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () virtual
StackingAction::StackingAction ()
StackingAction::~StackingAction ()
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () inline virtual
Definition at line 48 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file StackingAction.hh
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () inline virtual
Definition at line 48 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file StackingAction.hh
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () inline virtual
Definition at line 48 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file StackingAction.hh
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () virtual
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () virtual
StackingAction::StackingAction ()
StackingAction::~StackingAction () inline override
Definition at line 38 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 38 of file StackingAction.hh
StackingAction::StackingAction ()
virtual StackingAction::~StackingAction () inline virtual
Definition at line 54 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file StackingAction.hh
StackingAction::StackingAction (DetectorConstruction * det)
Definition at line 47 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file StackingAction.cc
References fEmCal, first, fKillTrack, fMatWall, fStackMessenger, and fZcav.
StackingAction::~StackingAction ()
Member Function Documentation
G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track * track) virtual
Reimplemented from G4UserStackingAction.
Definition at line 52 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 52 of file StackingAction.cc
References charge, energy, G4VAnalysisManager::FillH1(), fUrgent, G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetParentID(), G4ParticleDefinition::GetPDGCharge(), and G4ToolsAnalysisManager::Instance().
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
virtual G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
void StackingAction::NewStage () override virtual
Reimplemented from G4UserStackingAction.
void StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 49 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file StackingAction.cc
References G4cout, G4endl, G4StackManager::GetNTotalTrack(), G4DNAChemistryManager::Instance(), G4DNAChemistryManager::Run(), and G4UserStackingAction::stackManager.
virtual void StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
virtual void StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
virtual void StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
virtual void StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
virtual void StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
void StackingAction::SetKill (const G4String & name)
Definition at line 106 of file StackingAction.cc.
View newest version in sPHENIX GitHub at line 106 of file StackingAction.cc
References G4ParticleTable::FindParticle(), fParticle, and G4ParticleTable::GetParticleTable().
void StackingAction::SetKillAll (G4bool value) inline
Definition at line 60 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file StackingAction.hh
References fKillAll.
void StackingAction::SetKillEM (G4bool value) inline
Definition at line 61 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file StackingAction.hh
References fKillEM.
void StackingAction::SetKillStatus (G4bool value)
void StackingAction::SetKillStatus (G4bool value) inline
Definition at line 49 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file StackingAction.hh
References fKillSecondary.
void StackingAction::SetKillStatus (G4bool value) inline
Definition at line 49 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file StackingAction.hh
References fKillSecondary.
void StackingAction::SetKillStatus (G4int value) inline
Definition at line 50 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file StackingAction.hh
References fKillSecondary.
virtual void StackingAction::SetKillStatus (G4bool value) inline virtual
Definition at line 52 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file StackingAction.hh
References fKillTrack.
void StackingAction::SetKillStatus (G4bool value)
void StackingAction::SetTrackSecondaries (G4bool value) inline
Definition at line 49 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file StackingAction.hh
References fTrackSecondaries.
Referenced by StackingMessenger::SetNewValue().
Member Data Documentation
G4int StackingAction::fAlphaDNAAuger private
Definition at line 74 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 74 of file StackingAction.hh
G4int StackingAction::fAlphaDNAGamma private
Definition at line 73 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file StackingAction.hh
G4int StackingAction::fAlphaPlusDNAAuger private
Definition at line 76 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file StackingAction.hh
G4int StackingAction::fAlphaPlusDNAGamma private
Definition at line 75 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file StackingAction.hh
G4int StackingAction::fComptAuger private
Definition at line 63 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file StackingAction.hh
G4int StackingAction::fComptGamma private
Definition at line 61 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file StackingAction.hh
DetectorConstruction* StackingAction::fDetector private
Definition at line 57 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file StackingAction.hh
G4int StackingAction::fElectronDNAAuger private
Definition at line 68 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file StackingAction.hh
G4int StackingAction::fElectronDNAGamma private
Definition at line 67 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file StackingAction.hh
G4EmCalculator* StackingAction::fEmCal private
Definition at line 62 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 62 of file StackingAction.hh
Referenced by StackingAction().
EventAction* StackingAction::fEventAction private
Definition at line 55 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file StackingAction.hh
G4int StackingAction::fGenericIonDNAAuger private
Definition at line 80 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 80 of file StackingAction.hh
G4int StackingAction::fGenericIonDNAGamma private
Definition at line 79 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 79 of file StackingAction.hh
G4int StackingAction::fHeliumDNAAuger private
Definition at line 78 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 78 of file StackingAction.hh
G4int StackingAction::fHeliumDNAGamma private
Definition at line 77 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file StackingAction.hh
HistoManager * StackingAction::fHistoManager private
Definition at line 69 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 69 of file StackingAction.hh
G4int StackingAction::fHydrogenDNAAuger private
Definition at line 72 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 72 of file StackingAction.hh
G4int StackingAction::fHydrogenDNAGamma private
Definition at line 71 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file StackingAction.hh
G4bool StackingAction::fIDdefined private
Definition at line 82 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 82 of file StackingAction.hh
G4bool StackingAction::first private
Definition at line 63 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file StackingAction.hh
Referenced by StackingAction().
G4bool StackingAction::fKillAll private
Definition at line 70 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file StackingAction.hh
Referenced by SetKillAll().
G4bool StackingAction::fKillEM private
Definition at line 71 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file StackingAction.hh
Referenced by SetKillEM().
G4bool StackingAction::fKillSecondary private
Definition at line 55 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file StackingAction.hh
G4bool StackingAction::fKillSecondary private
Definition at line 57 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file StackingAction.hh
Referenced by SetKillStatus().
G4bool StackingAction::fKillTrack private
Definition at line 64 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file StackingAction.hh
Referenced by SetKillStatus(), and StackingAction().
G4Material* StackingAction::fMatWall private
Definition at line 60 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file StackingAction.hh
Referenced by StackingAction().
const G4ParticleDefinition* StackingAction::fParticle private
Definition at line 73 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file StackingAction.hh
Referenced by SetKill().
G4int StackingAction::fPhotoAuger private
Definition at line 62 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 62 of file StackingAction.hh
G4int StackingAction::fPhotoGamma private
Definition at line 60 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file StackingAction.hh
G4int StackingAction::fPixeAuger private
Definition at line 65 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file StackingAction.hh
G4int StackingAction::fPixeGamma private
Definition at line 64 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file StackingAction.hh
G4int StackingAction::fProtonDNAAuger private
Definition at line 70 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file StackingAction.hh
G4int StackingAction::fProtonDNAGamma private
Definition at line 69 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 69 of file StackingAction.hh
StackingMessenger * StackingAction::fStackMessenger private
Definition at line 55 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file StackingAction.hh
Referenced by StackingAction().
G4bool StackingAction::fTrackSecondaries private
Definition at line 54 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file StackingAction.hh
Referenced by SetTrackSecondaries().
G4double StackingAction::fZcav private
Definition at line 61 of file StackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file StackingAction.hh
Referenced by StackingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/channeling/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/channeling/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/StackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/StackingAction.cc