ECCE @ EIC Software: G4ParticleHPIsotropic Class Reference
G4ParticleHPIsotropic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPIsotropic.hh>
Public Member Functions
G4ParticleHPIsotropic ()
~G4ParticleHPIsotropic ()
void Init (std::istream &aDataFile)
G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass)
G4double MeanEnergyOfThisInteraction ()
Public Member Functions inherited from G4VParticleHPEnergyAngular
G4VParticleHPEnergyAngular ()
virtual ~G4VParticleHPEnergyAngular ()
void SetProjectileRP (G4ReactionProduct *aIncidentParticleRP)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4ReactionProduct * GetCMS ()
void SetQValue (G4double aValue)
virtual void ClearHistories ()
Additional Inherited Members
Protected Member Functions inherited from G4VParticleHPEnergyAngular
G4double GetQValue ()
Detailed Description
Definition at line 38 of file G4ParticleHPIsotropic.hh.
View newest version in sPHENIX GitHub at line 38 of file G4ParticleHPIsotropic.hh
Constructor & Destructor Documentation
G4ParticleHPIsotropic::G4ParticleHPIsotropic () inline
Definition at line 42 of file G4ParticleHPIsotropic.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPIsotropic.hh
G4ParticleHPIsotropic::~G4ParticleHPIsotropic () inline
Definition at line 44 of file G4ParticleHPIsotropic.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPIsotropic.hh
Member Function Documentation
void G4ParticleHPIsotropic::Init (std::istream & aDataFile) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 48 of file G4ParticleHPIsotropic.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPIsotropic.cc
G4double G4ParticleHPIsotropic::MeanEnergyOfThisInteraction () inline virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 50 of file G4ParticleHPIsotropic.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPIsotropic.hh
G4ReactionProduct * G4ParticleHPIsotropic::Sample (G4double anEnergy, G4double massCode, G4double mass) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 52 of file G4ParticleHPIsotropic.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPIsotropic.cc
References A(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4Electron::Electron(), G4UniformRand, G4Gamma::Gamma(), G4IonTable::GetIonTable(), G4VParticleHPEnergyAngular::GetQValue(), G4ReactionProduct::GetTotalMomentum(), G4He3::He3(), max, MeV, G4Neutron::Neutron(), phi, G4Positron::Positron(), G4Proton::Proton(), G4ReactionProduct::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), theta(), G4Triton::Triton(), twopi, and Z.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPIsotropic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPIsotropic.cc