ECCE @ EIC Software: GammaRayTelMuonPhysics Class Reference
GammaRayTelMuonPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelMuonPhysics.hh>
Public Member Functions
GammaRayTelMuonPhysics (const G4String &name="muon")
virtual ~GammaRayTelMuonPhysics ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Attributes
G4MuMultipleScattering fMuPlusMultipleScattering
G4MuBremsstrahlung fMuPlusBremsstrahlung
G4MuPairProduction fMuPlusPairProduction
G4MuIonisation fMuPlusIonisation
G4MuMultipleScattering fMuMinusMultipleScattering
G4MuBremsstrahlung fMuMinusBremsstrahlung
G4MuPairProduction fMuMinusPairProduction
G4MuIonisation fMuMinusIonisation
G4MuonMinusCapture fMuMinusCaptureAtRest
G4hMultipleScattering fTauPlusMultipleScattering
G4hIonisation fTauPlusIonisation
G4hMultipleScattering fTauMinusMultipleScattering
G4hIonisation fTauMinusIonisation
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 54 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 54 of file GammaRayTelMuonPhysics.hh
Constructor & Destructor Documentation
GammaRayTelMuonPhysics::GammaRayTelMuonPhysics (const G4String & name = "muon")
Definition at line 42 of file GammaRayTelMuonPhysics.cc.
View newest version in sPHENIX GitHub at line 42 of file GammaRayTelMuonPhysics.cc
GammaRayTelMuonPhysics::~GammaRayTelMuonPhysics () virtual
Definition at line 47 of file GammaRayTelMuonPhysics.cc.
View newest version in sPHENIX GitHub at line 47 of file GammaRayTelMuonPhysics.cc
Member Function Documentation
void GammaRayTelMuonPhysics::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 51 of file GammaRayTelMuonPhysics.cc.
View newest version in sPHENIX GitHub at line 51 of file GammaRayTelMuonPhysics.cc
void GammaRayTelMuonPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 59 of file GammaRayTelMuonPhysics.cc.
View newest version in sPHENIX GitHub at line 59 of file GammaRayTelMuonPhysics.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4ProcessManager::AddRestProcess(), fMuMinusBremsstrahlung, fMuMinusCaptureAtRest, fMuMinusIonisation, fMuMinusMultipleScattering, fMuMinusPairProduction, fMuPlusBremsstrahlung, fMuPlusIonisation, fMuPlusMultipleScattering, fMuPlusPairProduction, fTauMinusIonisation, fTauMinusMultipleScattering, fTauPlusIonisation, fTauPlusMultipleScattering, G4ParticleDefinition::GetProcessManager(), idxAlongStep, idxPostStep, G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), ordInActive, G4ProcessManager::SetProcessOrdering(), G4TauMinus::TauMinus(), and G4TauPlus::TauPlus().
Member Data Documentation
G4MuBremsstrahlung GammaRayTelMuonPhysics::fMuMinusBremsstrahlung protected
Definition at line 78 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 78 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuonMinusCapture GammaRayTelMuonPhysics::fMuMinusCaptureAtRest protected
Definition at line 82 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 82 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuIonisation GammaRayTelMuonPhysics::fMuMinusIonisation protected
Definition at line 80 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 80 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuMultipleScattering GammaRayTelMuonPhysics::fMuMinusMultipleScattering protected
Definition at line 77 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 77 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuPairProduction GammaRayTelMuonPhysics::fMuMinusPairProduction protected
Definition at line 79 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 79 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuBremsstrahlung GammaRayTelMuonPhysics::fMuPlusBremsstrahlung protected
Definition at line 73 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 73 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuIonisation GammaRayTelMuonPhysics::fMuPlusIonisation protected
Definition at line 75 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 75 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuMultipleScattering GammaRayTelMuonPhysics::fMuPlusMultipleScattering protected
Definition at line 72 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 72 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4MuPairProduction GammaRayTelMuonPhysics::fMuPlusPairProduction protected
Definition at line 74 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelMuonPhysics::fTauMinusIonisation protected
Definition at line 89 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 89 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelMuonPhysics::fTauMinusMultipleScattering protected
Definition at line 88 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 88 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelMuonPhysics::fTauPlusIonisation protected
Definition at line 86 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 86 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelMuonPhysics::fTauPlusMultipleScattering protected
Definition at line 85 of file GammaRayTelMuonPhysics.hh.
View newest version in sPHENIX GitHub at line 85 of file GammaRayTelMuonPhysics.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelMuonPhysics.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelMuonPhysics.cc