ECCE @ EIC Software: G4PhysListFactory Class Reference
G4PhysListFactory Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/G4PhysListFactory.hh>
Public Member Functions
G4PhysListFactory ()
~G4PhysListFactory ()
G4VModularPhysicsList * GetReferencePhysList (const G4String &)
G4VModularPhysicsList * ReferencePhysList ()
G4bool IsReferencePhysList (const G4String &)
const std::vector< G4String > & AvailablePhysLists () const
const std::vector< G4String > & AvailablePhysListsEM () const
void SetVerbose (G4int val)
Private Attributes
G4String defName
std::vector< G4String > listnames_hadr
std::vector< G4String > listnames_em
size_t nlists_hadr
size_t nlists_em
G4int verbose
G4UImessenger * theMessenger
Detailed Description
Definition at line 45 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 45 of file G4PhysListFactory.hh
Constructor & Destructor Documentation
G4PhysListFactory::G4PhysListFactory ()
Definition at line 79 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PhysListFactory.cc
References listnames_em, listnames_hadr, nlists_em, nlists_hadr, and s1.
G4PhysListFactory::~G4PhysListFactory ()
Definition at line 101 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PhysListFactory.cc
References theMessenger.
Member Function Documentation
const std::vector< G4String > & G4PhysListFactory::AvailablePhysLists () const
Definition at line 246 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 246 of file G4PhysListFactory.cc
References listnames_hadr.
const std::vector< G4String > & G4PhysListFactory::AvailablePhysListsEM () const
Definition at line 252 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 252 of file G4PhysListFactory.cc
References listnames_em.
G4VModularPhysicsList * G4PhysListFactory::GetReferencePhysList (const G4String & name)
Definition at line 127 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 127 of file G4PhysListFactory.cc
References G4cout, G4endl, G4VModularPhysicsList::GetVerboseLevel(), listnames_em, n, nlists_em, G4VModularPhysicsList::ReplacePhysics(), G4VModularPhysicsList::SetVerboseLevel(), theMessenger, and verbose.
Referenced by GammaRayTelPhysicsList::AddPackage(), PhysicsList::AddPackage(), main(), and ReferencePhysList().
G4bool G4PhysListFactory::IsReferencePhysList (const G4String & name)
Definition at line 222 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 222 of file G4PhysListFactory.cc
References listnames_em, listnames_hadr, n, nlists_em, and nlists_hadr.
Referenced by main().
G4VModularPhysicsList * G4PhysListFactory::ReferencePhysList ()
Definition at line 107 of file G4PhysListFactory.cc.
View newest version in sPHENIX GitHub at line 107 of file G4PhysListFactory.cc
References defName, G4cout, G4endl, and GetReferencePhysList().
Referenced by main().
void G4PhysListFactory::SetVerbose (G4int val) inline
Definition at line 68 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PhysListFactory.hh
References verbose.
Member Data Documentation
G4String G4PhysListFactory::defName private
Definition at line 72 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PhysListFactory.hh
Referenced by ReferencePhysList().
std::vector<G4String> G4PhysListFactory::listnames_em private
Definition at line 74 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PhysListFactory.hh
Referenced by AvailablePhysListsEM(), G4PhysListFactory(), GetReferencePhysList(), and IsReferencePhysList().
std::vector<G4String> G4PhysListFactory::listnames_hadr private
Definition at line 73 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PhysListFactory.hh
Referenced by AvailablePhysLists(), G4PhysListFactory(), and IsReferencePhysList().
size_t G4PhysListFactory::nlists_em private
Definition at line 76 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PhysListFactory.hh
Referenced by G4PhysListFactory(), GetReferencePhysList(), and IsReferencePhysList().
size_t G4PhysListFactory::nlists_hadr private
Definition at line 75 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 75 of file G4PhysListFactory.hh
Referenced by G4PhysListFactory(), and IsReferencePhysList().
G4UImessenger* G4PhysListFactory::theMessenger private
Definition at line 78 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PhysListFactory.hh
Referenced by GetReferencePhysList(), and ~G4PhysListFactory().
G4int G4PhysListFactory::verbose private
Definition at line 77 of file G4PhysListFactory.hh.
View newest version in sPHENIX GitHub at line 77 of file G4PhysListFactory.hh
Referenced by GetReferencePhysList(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/G4PhysListFactory.hh
geant4/tree/geant4-10.6-release/source/physics_lists/lists/src/G4PhysListFactory.cc