ECCE @ EIC Software: G4ExcitationHandler Class Reference
G4ExcitationHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/handler/include/G4ExcitationHandler.hh>
Public Member Functions
G4ExcitationHandler ()
~G4ExcitationHandler ()
G4ReactionProductVector * BreakItUp (const G4Fragment &theInitialState)
void ModelDescription (std::ostream &outFile) const
void Initialise ()
void SetEvaporation (G4VEvaporation *ptr, G4bool isLocal=false)
void SetMultiFragmentation (G4VMultiFragmentation *ptr)
void SetFermiModel (G4VFermiBreakUp *ptr)
void SetPhotonEvaporation (G4VEvaporationChannel *ptr)
void SetDeexChannelsType (G4DeexChannelType val)
void SetMaxZForFermiBreakUp (G4int aZ)
void SetMaxAForFermiBreakUp (G4int anA)
void SetMaxAandZForFermiBreakUp (G4int anA, G4int aZ)
void SetMinEForMultiFrag (G4double anE)
G4VEvaporation * GetEvaporation ()
G4VMultiFragmentation * GetMultiFragmentation ()
G4VFermiBreakUp * GetFermiModel ()
G4VEvaporationChannel * GetPhotonEvaporation ()
void SetOPTxs (G4int opt)
void UseSICB ()
Private Member Functions
void SetParameters ()
void SortSecondaryFragment (G4Fragment *)
G4ExcitationHandler (const G4ExcitationHandler &right)
const G4ExcitationHandler & operator= (const G4ExcitationHandler &right)
G4bool operator== (const G4ExcitationHandler &right) const
G4bool operator!= (const G4ExcitationHandler &right) const
Private Attributes
G4VEvaporation * theEvaporation
G4VMultiFragmentation * theMultiFragmentation
G4VFermiBreakUp * theFermiModel
G4VEvaporationChannel * thePhotonEvaporation
G4IonTable * theTableOfIons
G4NistManager * nist
const G4ParticleDefinition * theElectron
const G4ParticleDefinition * theNeutron
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theDeuteron
const G4ParticleDefinition * theTriton
const G4ParticleDefinition * theHe3
const G4ParticleDefinition * theAlpha
G4int icID
G4int maxZForFermiBreakUp
G4int maxAForFermiBreakUp
G4int fVerbose
G4int fWarnings
G4double minEForMultiFrag
G4double minExcitation
G4double maxExcitation
G4bool isInitialised
G4bool isEvapLocal
G4bool isActive
std::vector< G4Fragment * > theResults
std::vector< G4Fragment * > results
std::vector< G4Fragment * > theEvapList
Detailed Description
Definition at line 62 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ExcitationHandler.hh
Constructor & Destructor Documentation
G4ExcitationHandler::G4ExcitationHandler () explicit
Definition at line 85 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitationHandler.cc
References G4Alpha::AlphaDefinition(), G4Deuteron::DeuteronDefinition(), G4Electron::Electron(), fVerbose, G4cout, G4endl, G4Pow::GetInstance(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4He3::He3Definition(), G4NistManager::Instance(), G4Neutron::NeutronDefinition(), nist, G4Proton::ProtonDefinition(), results, theAlpha, theDeuteron, theElectron, theEvapList, theEvaporation, theFermiModel, theHe3, theMultiFragmentation, theNeutron, thePhotonEvaporation, theProton, theResults, theTableOfIons, theTriton, and G4Triton::TritonDefinition().
G4ExcitationHandler::~G4ExcitationHandler ()
Definition at line 114 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 114 of file G4ExcitationHandler.cc
References isEvapLocal, theEvaporation, theFermiModel, and theMultiFragmentation.
G4ExcitationHandler::G4ExcitationHandler (const G4ExcitationHandler & right) private
Member Function Documentation
G4ReactionProductVector * G4ExcitationHandler::BreakItUp (const G4Fragment & theInitialState)
Definition at line 278 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 278 of file G4ExcitationHandler.cc
References A(), G4VFermiBreakUp::BreakFragment(), G4VEvaporation::BreakFragment(), G4VMultiFragmentation::BreakItUp(), e, fac, FatalException, G4Ions::FloatLevelBase(), fVerbose, fWarnings, G4cout, G4endl, G4Exception(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4IonTable::GetIon(), G4ParticleDefinition::GetPDGMass(), G4Fragment::GetZ_asInt(), icID, Initialise(), isActive, G4VFermiBreakUp::IsApplicable(), isInitialised, JustWarning, mass, maxAForFermiBreakUp, maxExcitation, maxZForFermiBreakUp, MeV, minEForMultiFrag, minExcitation, mom, noFloat, results, G4ReactionProduct::SetCreatorModel(), G4ReactionProduct::SetFormationTime(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), SortSecondaryFragment(), theAlpha, theDeuteron, theElectron, theEvapList, theEvaporation, theFermiModel, theHe3, theMultiFragmentation, theNeutron, theProton, theResults, theTableOfIons, theTriton, and Z.
Referenced by G4ParaFissionModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4PreCompoundDeexcitation::deExcite(), G4BinaryCascade::DeExcite(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), and G4PreCompoundModel::PerformEquilibriumEmission().
G4VEvaporation * G4ExcitationHandler::GetEvaporation ()
Definition at line 253 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 253 of file G4ExcitationHandler.cc
References SetParameters(), and theEvaporation.
Referenced by G4INCLXXInterface::G4INCLXXInterface().
G4VFermiBreakUp * G4ExcitationHandler::GetFermiModel ()
Definition at line 265 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 265 of file G4ExcitationHandler.cc
References SetParameters(), and theFermiModel.
G4VMultiFragmentation * G4ExcitationHandler::GetMultiFragmentation ()
Definition at line 259 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 259 of file G4ExcitationHandler.cc
References SetParameters(), and theMultiFragmentation.
G4VEvaporationChannel * G4ExcitationHandler::GetPhotonEvaporation ()
Definition at line 271 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 271 of file G4ExcitationHandler.cc
References SetParameters(), and thePhotonEvaporation.
void G4ExcitationHandler::Initialise ()
Definition at line 157 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 157 of file G4ExcitationHandler.cc
References G4DeexPrecoParameters::Dump(), fVerbose, G4cout, G4endl, G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetParameters(), G4VFermiBreakUp::Initialise(), G4VEvaporation::InitialiseChannels(), isActive, isInitialised, SetParameters(), theEvaporation, and theFermiModel.
Referenced by BreakItUp(), and G4PreCompoundModel::InitialiseModel().
void G4ExcitationHandler::ModelDescription (std::ostream & outFile) const
Definition at line 539 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 539 of file G4ExcitationHandler.cc
Referenced by G4BinaryCascade::ModelDescription(), and G4BinaryCascade::PropagateModelDescription().
G4bool G4ExcitationHandler::operator!= (const G4ExcitationHandler & right) const private
const G4ExcitationHandler& G4ExcitationHandler::operator= (const G4ExcitationHandler & right) private
G4bool G4ExcitationHandler::operator== (const G4ExcitationHandler & right) const private
void G4ExcitationHandler::SetDeexChannelsType (G4DeexChannelType val)
Definition at line 221 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 221 of file G4ExcitationHandler.cc
References fCombined, fDummy, fEvaporation, fGEM, fGEMVI, fVerbose, G4cout, G4endl, G4VEvaporation::GetNumberOfChannels(), G4Evaporation::InitialiseChannels(), isActive, G4Threading::IsMasterThread(), G4Evaporation::SetCombinedChannel(), G4Evaporation::SetDefaultChannel(), G4Evaporation::SetGEMChannel(), G4Evaporation::SetGEMVIChannel(), and theEvaporation.
Referenced by G4QMDReaction::G4QMDReaction().
void G4ExcitationHandler::SetEvaporation (G4VEvaporation * ptr, G4bool isLocal = false)
Definition at line 175 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ExcitationHandler.cc
References fVerbose, G4cout, G4endl, G4VEvaporation::GetPhotonEvaporation(), isEvapLocal, G4VEvaporation::SetFermiBreakUp(), SetPhotonEvaporation(), theEvaporation, and theFermiModel.
Referenced by G4QMDReaction::G4QMDReaction(), G4WilsonAbrasionModel::G4WilsonAbrasionModel(), SetParameters(), and G4WilsonAbrasionModel::SetUseAblation().
void G4ExcitationHandler::SetFermiModel (G4VFermiBreakUp * ptr)
Definition at line 198 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 198 of file G4ExcitationHandler.cc
References G4VEvaporation::SetFermiBreakUp(), theEvaporation, and theFermiModel.
Referenced by SetParameters().
void G4ExcitationHandler::SetMaxAandZForFermiBreakUp (G4int anA, G4int aZ) inline
Definition at line 168 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ExcitationHandler.hh
References SetMaxAForFermiBreakUp(), and SetMaxZForFermiBreakUp().
void G4ExcitationHandler::SetMaxAForFermiBreakUp (G4int anA) inline
Definition at line 163 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ExcitationHandler.hh
References maxAForFermiBreakUp.
Referenced by SetMaxAandZForFermiBreakUp().
void G4ExcitationHandler::SetMaxZForFermiBreakUp (G4int aZ) inline
Definition at line 158 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ExcitationHandler.hh
References maxZForFermiBreakUp.
Referenced by SetMaxAandZForFermiBreakUp().
void G4ExcitationHandler::SetMinEForMultiFrag (G4double anE) inline
Definition at line 174 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ExcitationHandler.hh
References minEForMultiFrag.
Referenced by B03PhysicsList::ConstructHad(), and G4EMDissociation::G4EMDissociation().
void G4ExcitationHandler::SetMultiFragmentation (G4VMultiFragmentation * ptr)
Definition at line 190 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 190 of file G4ExcitationHandler.cc
References theMultiFragmentation.
Referenced by SetParameters().
void G4ExcitationHandler::SetOPTxs (G4int opt) inline
Definition at line 179 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ExcitationHandler.hh
void G4ExcitationHandler::SetParameters () private
Definition at line 121 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ExcitationHandler.cc
References fDummy, fVerbose, G4cout, G4endl, G4Element::GetElementTable(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetParameters(), icID, isActive, max, maxExcitation, minEForMultiFrag, minExcitation, SetEvaporation(), SetFermiModel(), SetMultiFragmentation(), SetPhotonEvaporation(), G4VFermiBreakUp::SetVerbose(), theEvaporation, theFermiModel, theMultiFragmentation, thePhotonEvaporation, G4NuclearLevelData::UploadNuclearLevelData(), and Zmax.
Referenced by GetEvaporation(), GetFermiModel(), GetMultiFragmentation(), GetPhotonEvaporation(), and Initialise().
void G4ExcitationHandler::SetPhotonEvaporation (G4VEvaporationChannel * ptr)
Definition at line 208 of file G4ExcitationHandler.cc.
View newest version in sPHENIX GitHub at line 208 of file G4ExcitationHandler.cc
References fVerbose, G4cout, G4endl, G4VEvaporation::SetPhotonEvaporation(), theEvaporation, and thePhotonEvaporation.
Referenced by SetEvaporation(), and SetParameters().
void G4ExcitationHandler::SortSecondaryFragment (G4Fragment * frag) inline private
Definition at line 185 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 185 of file G4ExcitationHandler.hh
References A(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NistManager::GetIsotopeAbundance(), G4Fragment::GetZ_asInt(), minExcitation, nist, theEvapList, theResults, and Z.
Referenced by BreakItUp().
void G4ExcitationHandler::UseSICB () inline
Definition at line 182 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 182 of file G4ExcitationHandler.hh
Member Data Documentation
G4int G4ExcitationHandler::fVerbose private
Definition at line 137 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), G4ExcitationHandler(), Initialise(), SetDeexChannelsType(), SetEvaporation(), SetParameters(), and SetPhotonEvaporation().
G4int G4ExcitationHandler::fWarnings private
Definition at line 138 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ExcitationHandler.hh
Referenced by BreakItUp().
G4int G4ExcitationHandler::icID private
Definition at line 132 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and SetParameters().
G4bool G4ExcitationHandler::isActive private
Definition at line 146 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), Initialise(), SetDeexChannelsType(), and SetParameters().
G4bool G4ExcitationHandler::isEvapLocal private
Definition at line 145 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ExcitationHandler.hh
Referenced by SetEvaporation(), and ~G4ExcitationHandler().
G4bool G4ExcitationHandler::isInitialised private
Definition at line 144 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and Initialise().
G4int G4ExcitationHandler::maxAForFermiBreakUp private
Definition at line 135 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and SetMaxAForFermiBreakUp().
G4double G4ExcitationHandler::maxExcitation private
Definition at line 142 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and SetParameters().
G4int G4ExcitationHandler::maxZForFermiBreakUp private
Definition at line 134 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and SetMaxZForFermiBreakUp().
G4double G4ExcitationHandler::minEForMultiFrag private
Definition at line 140 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), SetMinEForMultiFrag(), and SetParameters().
G4double G4ExcitationHandler::minExcitation private
Definition at line 141 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), SetParameters(), and SortSecondaryFragment().
G4NistManager* G4ExcitationHandler::nist private
Definition at line 122 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ExcitationHandler.hh
Referenced by G4ExcitationHandler(), and SortSecondaryFragment().
std::vector<G4Fragment*> G4ExcitationHandler::results private
Definition at line 152 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
const G4ParticleDefinition* G4ExcitationHandler::theAlpha private
Definition at line 130 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
const G4ParticleDefinition* G4ExcitationHandler::theDeuteron private
Definition at line 127 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
const G4ParticleDefinition* G4ExcitationHandler::theElectron private
Definition at line 124 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
std::vector<G4Fragment*> G4ExcitationHandler::theEvapList private
Definition at line 155 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), G4ExcitationHandler(), and SortSecondaryFragment().
G4VEvaporation* G4ExcitationHandler::theEvaporation private
Definition at line 117 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), G4ExcitationHandler(), GetEvaporation(), Initialise(), SetDeexChannelsType(), SetEvaporation(), SetFermiModel(), SetParameters(), SetPhotonEvaporation(), and ~G4ExcitationHandler().
G4VFermiBreakUp* G4ExcitationHandler::theFermiModel private
Definition at line 119 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), G4ExcitationHandler(), GetFermiModel(), Initialise(), SetEvaporation(), SetFermiModel(), SetParameters(), and ~G4ExcitationHandler().
const G4ParticleDefinition* G4ExcitationHandler::theHe3 private
Definition at line 129 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
G4VMultiFragmentation* G4ExcitationHandler::theMultiFragmentation private
Definition at line 118 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), G4ExcitationHandler(), GetMultiFragmentation(), SetMultiFragmentation(), SetParameters(), and ~G4ExcitationHandler().
const G4ParticleDefinition* G4ExcitationHandler::theNeutron private
Definition at line 125 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
G4VEvaporationChannel* G4ExcitationHandler::thePhotonEvaporation private
Definition at line 120 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ExcitationHandler.hh
Referenced by G4ExcitationHandler(), GetPhotonEvaporation(), SetParameters(), and SetPhotonEvaporation().
const G4ParticleDefinition* G4ExcitationHandler::theProton private
Definition at line 126 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
std::vector<G4Fragment*> G4ExcitationHandler::theResults private
Definition at line 149 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), G4ExcitationHandler(), and SortSecondaryFragment().
G4IonTable* G4ExcitationHandler::theTableOfIons private
Definition at line 121 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
const G4ParticleDefinition* G4ExcitationHandler::theTriton private
Definition at line 128 of file G4ExcitationHandler.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ExcitationHandler.hh
Referenced by BreakItUp(), and G4ExcitationHandler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/handler/include/G4ExcitationHandler.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/handler/src/G4ExcitationHandler.cc