ECCE @ EIC Software: G4SextupoleMagField Class Reference
G4SextupoleMagField Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4SextupoleMagField.hh>
Public Member Functions
G4SextupoleMagField (G4double pGradient)
G4SextupoleMagField (G4double pGradient, G4ThreeVector pOrigin, G4RotationMatrix *pMatrix)
~G4SextupoleMagField ()
void GetFieldValue (const G4double yTrack[], G4double B[]) const
G4Field * Clone () const
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
virtual void GetFieldValue (const G4double Point[4], G4double *Bfield) const =0
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Private Attributes
G4double fGradient = 0.0
G4ThreeVector fOrigin = G4ThreeVector(0.0, 0.0, 0.0)
G4RotationMatrix * fpMatrix = nullptr
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 45 of file G4SextupoleMagField.hh.
View newest version in sPHENIX GitHub at line 45 of file G4SextupoleMagField.hh
Constructor & Destructor Documentation
G4SextupoleMagField::G4SextupoleMagField (G4double pGradient)
Definition at line 40 of file G4SextupoleMagField.cc.
View newest version in sPHENIX GitHub at line 40 of file G4SextupoleMagField.cc
References fGradient, and fpMatrix.
Referenced by Clone().
G4SextupoleMagField::G4SextupoleMagField (G4double pGradient, G4ThreeVector pOrigin, G4RotationMatrix * pMatrix)
Definition at line 46 of file G4SextupoleMagField.cc.
View newest version in sPHENIX GitHub at line 46 of file G4SextupoleMagField.cc
References fGradient, fOrigin, and fpMatrix.
G4SextupoleMagField::~G4SextupoleMagField ()
Definition at line 62 of file G4SextupoleMagField.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SextupoleMagField.cc
Member Function Documentation
G4Field * G4SextupoleMagField::Clone () const virtual
Reimplemented from G4Field.
Definition at line 55 of file G4SextupoleMagField.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SextupoleMagField.cc
References fGradient, fOrigin, fpMatrix, and G4SextupoleMagField().
void G4SextupoleMagField::GetFieldValue (const G4double yTrack[], G4double B[]) const
Definition at line 66 of file G4SextupoleMagField.cc.
View newest version in sPHENIX GitHub at line 66 of file G4SextupoleMagField.cc
References B(), and y.
Member Data Documentation
G4double G4SextupoleMagField::fGradient = 0.0 private
Definition at line 61 of file G4SextupoleMagField.hh.
View newest version in sPHENIX GitHub at line 61 of file G4SextupoleMagField.hh
Referenced by Clone(), and G4SextupoleMagField().
G4ThreeVector G4SextupoleMagField::fOrigin = G4ThreeVector(0.0, 0.0, 0.0) private
Definition at line 62 of file G4SextupoleMagField.hh.
View newest version in sPHENIX GitHub at line 62 of file G4SextupoleMagField.hh
Referenced by Clone(), and G4SextupoleMagField().
G4RotationMatrix* G4SextupoleMagField::fpMatrix = nullptr private
Definition at line 63 of file G4SextupoleMagField.hh.
View newest version in sPHENIX GitHub at line 63 of file G4SextupoleMagField.hh
Referenced by Clone(), and G4SextupoleMagField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4SextupoleMagField.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4SextupoleMagField.cc