ECCE @ EIC Software: G4ScoringRealWorld Class Reference
G4ScoringRealWorld Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringRealWorld.hh>
Public Member Functions
G4ScoringRealWorld (G4String lvName)
~G4ScoringRealWorld ()
virtual void List () const
virtual void Draw (RunScore *, G4VScoreColorMap *, G4int)
virtual void DrawColumn (RunScore *, G4VScoreColorMap *, G4int, G4int)
Public Member Functions inherited from G4VScoringMesh
G4VScoringMesh (const G4String &wName)
virtual ~G4VScoringMesh ()
void Construct (G4VPhysicalVolume *fWorldPhys)
void WorkerConstruct (G4VPhysicalVolume *fWorldPhys)
const G4String & GetWorldName () const
G4bool IsActive () const
void Activate (G4bool vl=true)
MeshShape GetShape () const
void Accumulate (G4THitsMap< G4double > *map)
void Accumulate (G4THitsMap< G4StatDouble > *map)
void Merge (const G4VScoringMesh *scMesh)
void Dump ()
void DrawMesh (const G4String &psName, G4VScoreColorMap *colorMap, G4int axflg=111)
void DrawMesh (const G4String &psName, G4int idxPlane, G4int iColumn, G4VScoreColorMap *colorMap)
void ResetScore ()
void SetSize (G4double size[3])
G4ThreeVector GetSize () const
void SetCenterPosition (G4double centerPosition[3])
G4ThreeVector GetTranslation () const
void RotateX (G4double delta)
void RotateY (G4double delta)
void RotateZ (G4double delta)
G4RotationMatrix GetRotationMatrix () const
void SetNumberOfSegments (G4int nSegment[3])
void GetNumberOfSegments (G4int nSegment[3])
void SetPrimitiveScorer (G4VPrimitiveScorer *ps)
void SetFilter (G4VSDFilter *filter)
void SetCurrentPrimitiveScorer (const G4String &name)
G4bool FindPrimitiveScorer (const G4String &psname)
G4bool IsCurrentPrimitiveScorerNull ()
G4String GetPSUnit (const G4String &psname)
G4String GetCurrentPSUnit ()
void SetCurrentPSUnit (const G4String &unit)
G4double GetPSUnitValue (const G4String &psname)
void SetDrawPSName (const G4String &psname)
void GetDivisionAxisNames (G4String divisionAxisNames[3])
void SetNullToCurrentPrimitiveScorer ()
void SetVerboseLevel (G4int vl)
MeshScoreMap GetScoreMap () const
G4bool ReadyForQuantity () const
void SetMeshElementLogical (G4LogicalVolume *val)
G4LogicalVolume * GetMeshElementLogical () const
void SetParallelWorldProcess (G4ParallelWorldProcess *proc)
G4ParallelWorldProcess * GetParallelWorldProcess () const
void GeometryHasBeenDestroyed ()
void SetCopyNumberLevel (G4int val)
G4int GetCopyNumberLevel () const
Protected Member Functions
virtual void SetupGeometry (G4VPhysicalVolume *)
Protected Member Functions inherited from G4VScoringMesh
G4VPrimitiveScorer * GetPrimitiveScorer (const G4String &name)
Protected Attributes
G4String logVolName
Protected Attributes inherited from G4VScoringMesh
G4String fWorldName
G4VPrimitiveScorer * fCurrentPS
G4bool fConstructed
G4bool fActive
MeshShape fShape
G4double fSize [3]
G4ThreeVector fCenterPosition
G4RotationMatrix * fRotationMatrix
G4int fNSegment [3]
MeshScoreMap fMap
G4MultiFunctionalDetector * fMFD
G4int verboseLevel
G4bool sizeIsSet
G4bool nMeshIsSet
G4String fDrawUnit
G4double fDrawUnitValue
G4String fDrawPSName
G4String fDivisionAxisNames [3]
G4LogicalVolume * fMeshElementLogical
G4ParallelWorldProcess * fParallelWorldProcess
G4bool fGeometryHasBeenDestroyed
G4int copyNumberLevel
Additional Inherited Members
Public Types inherited from G4VScoringMesh
enum MeshShape
using EventScore = G4THitsMap< G4double >
using RunScore = G4THitsMap< G4StatDouble >
using MeshScoreMap = std::map< G4String, RunScore * >
Detailed Description
Definition at line 34 of file G4ScoringRealWorld.hh.
View newest version in sPHENIX GitHub at line 34 of file G4ScoringRealWorld.hh
Constructor & Destructor Documentation
G4ScoringRealWorld::G4ScoringRealWorld (G4String lvName)
Definition at line 43 of file G4ScoringRealWorld.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ScoringRealWorld.cc
References G4VScoringMesh::fShape, logVolName, G4VScoringMesh::SetNumberOfSegments(), and G4VScoringMesh::SetSize().
G4ScoringRealWorld::~G4ScoringRealWorld ()
Definition at line 54 of file G4ScoringRealWorld.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ScoringRealWorld.cc
Member Function Documentation
virtual void G4ScoringRealWorld::Draw (RunScore * , G4VScoreColorMap * , G4int) inline virtual
Implements G4VScoringMesh.
Definition at line 52 of file G4ScoringRealWorld.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ScoringRealWorld.hh
virtual void G4ScoringRealWorld::DrawColumn (RunScore * , G4VScoreColorMap * , G4int , G4int) inline virtual
Implements G4VScoringMesh.
Definition at line 54 of file G4ScoringRealWorld.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ScoringRealWorld.hh
void G4ScoringRealWorld::List () const virtual
Reimplemented from G4VScoringMesh.
Definition at line 58 of file G4ScoringRealWorld.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ScoringRealWorld.cc
References G4cout, G4endl, G4VScoringMesh::List(), and logVolName.
void G4ScoringRealWorld::SetupGeometry (G4VPhysicalVolume *) protected virtual
Implements G4VScoringMesh.
Definition at line 64 of file G4ScoringRealWorld.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ScoringRealWorld.cc
References FatalException, G4VScoringMesh::fMeshElementLogical, G4VScoringMesh::fMFD, G4Exception(), G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), logVolName, G4VScoringMesh::SetNumberOfSegments(), and G4LogicalVolume::SetSensitiveDetector().
Member Data Documentation
G4String G4ScoringRealWorld::logVolName protected
Definition at line 45 of file G4ScoringRealWorld.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ScoringRealWorld.hh
Referenced by G4ScoringRealWorld(), List(), and SetupGeometry().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringRealWorld.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoringRealWorld.cc