ECCE @ EIC Software: G4FastList< OBJECT >::Watcher Class Reference
G4FastList< OBJECT >::Watcher Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh>
Public Types
enum Priority {
eExtreme, eHigh, eNormal, eLow,
eVeryLow
}
typedef G4FastList< OBJECT > list
Public Member Functions
Watcher ()
virtual ~Watcher ()
virtual G4String GetWatcherName ()
Priority GetPriority () const
void NotifyDeletingList (G4FastList< OBJECT > *)
virtual void NotifyAddObject (OBJECT *, G4FastList< OBJECT > *)
virtual void NotifyRemoveObject (OBJECT *, G4FastList< OBJECT > *)
void Watch (G4FastList< OBJECT > *fastList)
void StopWatching (G4FastList< OBJECT > *fastList, bool removeWatcher=true)
Protected Attributes
Priority fPriority
Private Attributes
std::set< G4FastList< OBJECT > * > fWatching
Detailed Description
template<class OBJECT>
class G4FastList< OBJECT >::Watcher
Definition at line 232 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 232 of file G4FastList.hh
Member Typedef Documentation
template<class OBJECT> typedef G4FastList<OBJECT> G4FastList< OBJECT >::Watcher::list
Definition at line 244 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 244 of file G4FastList.hh
Member Enumeration Documentation
template<class OBJECT> enum G4FastList::Watcher::Priority
Enumerator:
eExtreme
eHigh
eNormal
eLow
eVeryLow
Definition at line 235 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 235 of file G4FastList.hh
Constructor & Destructor Documentation
template<class OBJECT> G4FastList< OBJECT >::Watcher::Watcher () inline
Definition at line 246 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 246 of file G4FastList.hh
template<class OBJECT> virtual G4FastList< OBJECT >::Watcher::~Watcher () inline virtual
Definition at line 251 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 251 of file G4FastList.hh
Member Function Documentation
template<class OBJECT> Priority G4FastList< OBJECT >::Watcher::GetPriority () const inline
Definition at line 265 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 265 of file G4FastList.hh
Referenced by sortWatcher< OBJECT >::operator()().
template<class OBJECT> virtual G4String G4FastList< OBJECT >::Watcher::GetWatcherName () inline virtual
Reimplemented in G4FastList< OBJECT >::TWatcher< WATCHER_TYPE >.
Definition at line 261 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 261 of file G4FastList.hh
template<class OBJECT> virtual void G4FastList< OBJECT >::Watcher::NotifyAddObject (OBJECT * , G4FastList< OBJECT > *) inline virtual
Definition at line 274 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 274 of file G4FastList.hh
template<class OBJECT> void G4FastList< OBJECT >::Watcher::NotifyDeletingList (G4FastList< OBJECT > *) inline
Definition at line 271 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 271 of file G4FastList.hh
template<class OBJECT> virtual void G4FastList< OBJECT >::Watcher::NotifyRemoveObject (OBJECT * , G4FastList< OBJECT > *) inline virtual
Definition at line 275 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 275 of file G4FastList.hh
template<class OBJECT> void G4FastList< OBJECT >::Watcher::StopWatching (G4FastList< OBJECT > * fastList, bool removeWatcher = true) inline
Definition at line 286 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 286 of file G4FastList.hh
Referenced by G4ManyFastLists< G4Track >::Remove().
template<class OBJECT> void G4FastList< OBJECT >::Watcher::Watch (G4FastList< OBJECT > * fastList) inline
Definition at line 280 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 280 of file G4FastList.hh
Referenced by G4ManyFastLists< G4Track >::Add(), G4ManyFastLists< G4Track >::AddGlobalWatcher(), and PriorityList::NewMainList().
Member Data Documentation
template<class OBJECT> Priority G4FastList< OBJECT >::Watcher::fPriority protected
Definition at line 295 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 295 of file G4FastList.hh
Referenced by G4FastList< OBJECT >::Watcher< G4Track >::GetPriority(), and G4FastList< OBJECT >::Watcher< G4Track >::Watcher().
template<class OBJECT> std::set<G4FastList<OBJECT>*> G4FastList< OBJECT >::Watcher::fWatching private
Definition at line 298 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 298 of file G4FastList.hh
Referenced by G4FastList< OBJECT >::Watcher< G4Track >::StopWatching(), G4FastList< OBJECT >::Watcher< G4Track >::Watch(), and G4FastList< OBJECT >::Watcher< G4Track >::~Watcher().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh