ECCE @ EIC Software: CML2AccSaturn Class Reference
CML2AccSaturn Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2AccSaturn.hh>
Public Member Functions
CML2AccSaturn (void)
~CML2AccSaturn (void)
void Construct (G4VPhysicalVolume *PVWorld, G4double isoCentre)
G4double getBeforeJaws_Z_PhaseSpacePosition ()
void writeInfo ()
Public Member Functions inherited from CML2Accelerator
CML2Accelerator (void)
virtual ~CML2Accelerator (void)
void reset ()
void setJaw1X (G4double val)
void setJaw2X (G4double val)
void setJaw1Y (G4double val)
void setJaw2Y (G4double val)
void setIsoCentre (G4double val)
void setidEnergy (G4int val)
void setLeavesAx (G4double val)
void setLeavesBx (G4double val)
int getidEnergy ()
Static Public Member Functions
static CML2AccSaturn * GetInstance (void)
Private Member Functions
void buildMaterial_SSteel ()
void buildMaterial_XC10 ()
void buildMaterial_WNICU ()
void buildMaterial_Kapton ()
G4Material * getMaterial (const G4String materialName)
void SetJawAperture (G4int idJaw, G4ThreeVector &centre, G4ThreeVector halfSize, G4RotationMatrix *cRotation)
bool target ()
bool primaryCollimator ()
bool vacuumWindow ()
bool flatteningFilter ()
bool ionizationChamber ()
bool Jaw1X ()
bool Jaw2X ()
bool Jaw1Y ()
bool Jaw2Y ()
Private Attributes
CML2AccSaturnMessenger * accSaturnMessenger
G4Material * mat_XC10
G4Material * mat_WNICU
G4Material * mat_ssteel
G4Material * mat_Kapton
G4VPhysicalVolume * PVWorld
Static Private Attributes
static CML2AccSaturn * instance = 0
Additional Inherited Members
Public Attributes inherited from CML2Accelerator
G4double jaw1XAperture
G4double jaw2XAperture
G4double jaw1YAperture
G4double jaw2YAperture
G4double isoCentre
std::vector< G4double > vec_leavesA
std::vector< G4double > vec_leavesB
G4int idEnergy
Detailed Description
Definition at line 65 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 65 of file ML2AccSaturn.hh
Constructor & Destructor Documentation
CML2AccSaturn::CML2AccSaturn (void)
Definition at line 56 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 56 of file ML2AccSaturn.cc
CML2AccSaturn::~CML2AccSaturn (void)
Definition at line 66 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 66 of file ML2AccSaturn.cc
Member Function Documentation
void CML2AccSaturn::buildMaterial_Kapton () private
Definition at line 170 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 170 of file ML2AccSaturn.cc
References cm3, G4NistManager::FindOrBuildMaterial(), Acts::UnitConstants::g, and G4NistManager::Instance().
void CML2AccSaturn::buildMaterial_SSteel () private
Definition at line 124 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 124 of file ML2AccSaturn.cc
References cm3, G4NistManager::FindOrBuildMaterial(), Acts::UnitConstants::g, and G4NistManager::Instance().
void CML2AccSaturn::buildMaterial_WNICU () private
Definition at line 157 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 157 of file ML2AccSaturn.cc
References cm3, G4NistManager::FindOrBuildMaterial(), Acts::UnitConstants::g, and G4NistManager::Instance().
void CML2AccSaturn::buildMaterial_XC10 () private
Definition at line 144 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 144 of file ML2AccSaturn.cc
References cm3, G4NistManager::FindOrBuildMaterial(), Acts::UnitConstants::g, and G4NistManager::Instance().
void CML2AccSaturn::Construct (G4VPhysicalVolume * PVWorld, G4double isoCentre) virtual
Reimplemented from CML2Accelerator.
Definition at line 212 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 212 of file ML2AccSaturn.cc
bool CML2AccSaturn::flatteningFilter () private
Definition at line 432 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 432 of file ML2AccSaturn.cc
References G4Region::AddRootLogicalVolume(), cm, deg, G4Colour::Magenta(), mm, pos(), G4VisAttributes::SetForceSolid(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
G4double CML2AccSaturn::getBeforeJaws_Z_PhaseSpacePosition () inline virtual
Reimplemented from CML2Accelerator.
Definition at line 73 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2AccSaturn.hh
CML2AccSaturn * CML2AccSaturn::GetInstance (void) static
Definition at line 78 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 78 of file ML2AccSaturn.cc
References instance.
Referenced by CML2AcceleratorConstruction::design().
G4Material * CML2AccSaturn::getMaterial (const G4String materialName) private
Definition at line 185 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 185 of file ML2AccSaturn.cc
References G4cout, G4endl, and material().
bool CML2AccSaturn::ionizationChamber () private
Definition at line 515 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 515 of file ML2AccSaturn.cc
References G4Colour::Blue(), cm, deg, e, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), G4Colour::Magenta(), mm, and G4Colour::Red().
bool CML2AccSaturn::Jaw1X () private
Definition at line 643 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 643 of file ML2AccSaturn.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4VisAttributes::SetForceSolid(), G4LogicalVolume::SetRegion(), and G4VisAttributes::SetVisibility().
bool CML2AccSaturn::Jaw1Y () private
Definition at line 901 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 901 of file ML2AccSaturn.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4VisAttributes::SetForceSolid(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
bool CML2AccSaturn::Jaw2X () private
Definition at line 769 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 769 of file ML2AccSaturn.cc
References G4Colour::Blue(), cm, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
bool CML2AccSaturn::Jaw2Y () private
Definition at line 1006 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 1006 of file ML2AccSaturn.cc
References G4Colour::Blue(), cm, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4Colour::Red(), and CLHEP::Hep3Vector::set().
bool CML2AccSaturn::primaryCollimator () private
Definition at line 279 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 279 of file ML2AccSaturn.cc
References G4Colour::Blue(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4Colour::Red(), G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
void CML2AccSaturn::SetJawAperture (G4int idJaw, G4ThreeVector & centre, G4ThreeVector halfSize, G4RotationMatrix * cRotation) private
Definition at line 605 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 605 of file ML2AccSaturn.cc
References dx, dy, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::Hep3Vector::set(), theta(), x, y, and z.
bool CML2AccSaturn::target () private
Definition at line 227 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 227 of file ML2AccSaturn.cc
References cm, deg, G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4Colour::Grey(), G4NistManager::Instance(), mm, and CLHEP::Hep3Vector::set().
bool CML2AccSaturn::vacuumWindow () private
Definition at line 393 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 393 of file ML2AccSaturn.cc
References cm, deg, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
void CML2AccSaturn::writeInfo () virtual
Reimplemented from CML2Accelerator.
Definition at line 88 of file ML2AccSaturn.cc.
View newest version in sPHENIX GitHub at line 88 of file ML2AccSaturn.cc
References G4cout, G4endl, int(), and mm.
Member Data Documentation
CML2AccSaturnMessenger* CML2AccSaturn::accSaturnMessenger private
Definition at line 77 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2AccSaturn.hh
CML2AccSaturn * CML2AccSaturn::instance = 0 static private
Definition at line 79 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2AccSaturn.hh
G4Material * CML2AccSaturn::mat_Kapton private
Definition at line 85 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 85 of file ML2AccSaturn.hh
G4Material * CML2AccSaturn::mat_ssteel private
Definition at line 85 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 85 of file ML2AccSaturn.hh
G4Material * CML2AccSaturn::mat_WNICU private
Definition at line 85 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 85 of file ML2AccSaturn.hh
G4Material* CML2AccSaturn::mat_XC10 private
Definition at line 85 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 85 of file ML2AccSaturn.hh
G4VPhysicalVolume* CML2AccSaturn::PVWorld private
Definition at line 98 of file ML2AccSaturn.hh.
View newest version in sPHENIX GitHub at line 98 of file ML2AccSaturn.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2AccSaturn.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2AccSaturn.cc