ECCE @ EIC Software: G4VTwistedFaceted Class Reference
G4VTwistedFaceted Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistedFaceted.hh>
Classes
class LastState
class LastValue
class LastValueWithDoubleVector
class LastVector
Public Member Functions
G4VTwistedFaceted (const G4String &pname, G4double PhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph)
virtual ~G4VTwistedFaceted ()
virtual void ComputeDimensions (G4VPVParameterisation *, const G4int, const G4VPhysicalVolume *)
virtual void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
virtual G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
virtual G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
virtual G4double DistanceToIn (const G4ThreeVector &p) const
virtual G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcnorm=false, G4bool *validnorm=nullptr, G4ThreeVector *n=nullptr) const
virtual G4double DistanceToOut (const G4ThreeVector &p) const
virtual EInside Inside (const G4ThreeVector &p) const
virtual G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4ThreeVector GetPointOnSurface () const
G4ThreeVector GetPointInSolid (G4double z) const
virtual G4double GetCubicVolume ()
virtual G4double GetSurfaceArea ()
virtual void DescribeYourselfTo (G4VGraphicsScene &scene) const
virtual G4Polyhedron * CreatePolyhedron () const
virtual G4Polyhedron * GetPolyhedron () const
virtual std::ostream & StreamInfo (std::ostream &os) const
G4double GetTwistAngle () const
G4double GetDx1 () const
G4double GetDx2 () const
G4double GetDx3 () const
G4double GetDx4 () const
G4double GetDy1 () const
G4double GetDy2 () const
G4double GetDz () const
G4double GetPhi () const
G4double GetTheta () const
G4double GetAlpha () const
G4double Xcoef (G4double u, G4double phi, G4double ftg) const
G4double GetValueA (G4double phi) const
G4double GetValueB (G4double phi) const
G4double GetValueD (G4double phi) const
virtual G4VisExtent GetExtent () const
virtual G4GeometryType GetEntityType () const
G4VTwistedFaceted (__void__ &)
G4VTwistedFaceted (const G4VTwistedFaceted &rhs)
G4VTwistedFaceted & operator= (const G4VTwistedFaceted &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual G4VSolid * Clone () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Attributes
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Private Member Functions
void CreateSurfaces ()
Private Attributes
G4double fTheta
G4double fPhi
G4double fDy1
G4double fDx1
G4double fDx2
G4double fDy2
G4double fDx3
G4double fDx4
G4double fDz
G4double fDx
G4double fDy
G4double fAlph
G4double fTAlph
G4double fdeltaX
G4double fdeltaY
G4double fPhiTwist
G4VTwistSurface * fLowerEndcap
G4VTwistSurface * fUpperEndcap
G4VTwistSurface * fSide0
G4VTwistSurface * fSide90
G4VTwistSurface * fSide180
G4VTwistSurface * fSide270
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
LastState fLastInside
LastVector fLastNormal
LastValue fLastDistanceToIn
LastValue fLastDistanceToOut
LastValueWithDoubleVector fLastDistanceToInWithV
LastValueWithDoubleVector fLastDistanceToOutWithV
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Detailed Description
Definition at line 47 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VTwistedFaceted.hh
Constructor & Destructor Documentation
G4VTwistedFaceted::G4VTwistedFaceted (const G4String & pname, G4double PhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph)
Definition at line 61 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VTwistedFaceted.cc
References cm, CreateSurfaces(), deg, fAlph, FatalErrorInArgument, fCubicVolume, fdeltaX, fdeltaY, fDx, fDx1, fDx2, fDx3, fDx4, fDy, fDy1, fDy2, fDz, fPhi, fPhiTwist, fTAlph, fTheta, G4cout, G4endl, G4Exception(), G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4VSolid::GetName(), G4VSolid::kCarTolerance, message(), and pi.
G4VTwistedFaceted::~G4VTwistedFaceted () virtual
Definition at line 206 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 206 of file G4VTwistedFaceted.cc
References fLowerEndcap, fpPolyhedron, fSide0, fSide180, fSide270, fSide90, and fUpperEndcap.
G4VTwistedFaceted::G4VTwistedFaceted (__void__ & a)
Definition at line 191 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 191 of file G4VTwistedFaceted.cc
G4VTwistedFaceted::G4VTwistedFaceted (const G4VTwistedFaceted & rhs)
Definition at line 222 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 222 of file G4VTwistedFaceted.cc
References CreateSurfaces().
Member Function Documentation
void G4VTwistedFaceted::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 293 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 293 of file G4VTwistedFaceted.cc
References fDx, fDy, fDz, and CLHEP::Hep3Vector::set().
Referenced by CalculateExtent().
G4bool G4VTwistedFaceted::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 306 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 306 of file G4VTwistedFaceted.cc
References BoundingLimits(), and G4BoundingEnvelope::CalculateExtent().
void G4VTwistedFaceted::ComputeDimensions (G4VPVParameterisation * , const G4int , const G4VPhysicalVolume *) virtual
Reimplemented from G4VSolid.
Definition at line 280 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 280 of file G4VTwistedFaceted.cc
References FatalException, and G4Exception().
G4Polyhedron * G4VTwistedFaceted::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1130 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 1130 of file G4VTwistedFaceted.cc
References kdfinder::abs(), HepPolyhedron::createPolyhedron(), fLowerEndcap, fPhiTwist, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4VTwistSurface::GetFacets(), HepPolyhedron::GetNumberOfRotationSteps(), k, n, and twopi.
Referenced by GetPolyhedron().
void G4VTwistedFaceted::CreateSurfaces () private
Definition at line 944 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 944 of file G4VTwistedFaceted.cc
References deg, fAlph, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fLowerEndcap, fPhi, fPhiTwist, fSide0, fSide180, fSide270, fSide90, fTheta, fUpperEndcap, pi, and G4VTwistSurface::SetNeighbours().
Referenced by G4VTwistedFaceted(), and operator=().
void G4VTwistedFaceted::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 922 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 922 of file G4VTwistedFaceted.cc
References G4VGraphicsScene::AddSolid().
G4double G4VTwistedFaceted::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 483 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 483 of file G4VTwistedFaceted.cc
References G4VTwistSurface::DistanceToIn(), fLastDistanceToIn, fLastDistanceToInWithV, fLowerEndcap, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4cout, G4endl, Inside(), kInfinity, kInside, kSurface, CLHEP::normal(), G4VTwistedFaceted::LastValueWithDoubleVector::p, CLHEP::Hep3Vector::set(), SurfaceNormal(), G4VTwistedFaceted::LastValue::value, G4VTwistedFaceted::LastValueWithDoubleVector::value, G4VTwistedFaceted::LastValueWithDoubleVector::vec, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4VTwistedFaceted::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 584 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 584 of file G4VTwistedFaceted.cc
References G4VTwistSurface::DistanceTo(), FatalException, fLastDistanceToIn, fLowerEndcap, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4Exception(), Inside(), kInfinity, kInside, kOutside, kSurface, G4VTwistedFaceted::LastValue::p, CLHEP::Hep3Vector::set(), G4VTwistedFaceted::LastValue::value, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4VTwistedFaceted::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcnorm = false, G4bool * validnorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 673 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 673 of file G4VTwistedFaceted.cc
References G4VTwistSurface::DistanceToOut(), fLastDistanceToOutWithV, fLastNormal, fLowerEndcap, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4VTwistSurface::GetNormal(), Inside(), G4VTwistSurface::IsValidNorm(), kInfinity, kOutside, kSurface, CLHEP::normal(), G4VTwistedFaceted::LastValueWithDoubleVector::p, CLHEP::Hep3Vector::set(), G4VTwistedFaceted::LastVector::surface, SurfaceNormal(), G4VTwistedFaceted::LastValueWithDoubleVector::value, G4VTwistedFaceted::LastValueWithDoubleVector::vec, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4VTwistedFaceted::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 780 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 780 of file G4VTwistedFaceted.cc
References G4VTwistSurface::DistanceTo(), G4VSolid::DumpInfo(), FatalException, fLastDistanceToOut, fLowerEndcap, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4cout, G4endl, G4Exception(), Inside(), JustWarning, kInfinity, kInside, kOutside, kSurface, mm, G4VTwistedFaceted::LastValue::p, CLHEP::Hep3Vector::set(), G4VTwistedFaceted::LastValue::value, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4VTwistedFaceted::GetAlpha () const inline
Definition at line 121 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 121 of file G4VTwistedFaceted.hh
References fAlph.
Referenced by G4TwistedTrap::GetTiltAngleAlpha().
G4double G4VTwistedFaceted::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
Definition at line 298 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 298 of file G4VTwistedFaceted.hh
References fCubicVolume, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, and fDz.
G4double G4VTwistedFaceted::GetDx1 () const inline
Definition at line 112 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VTwistedFaceted.hh
References fDx1.
Referenced by G4TwistedTrd::GetX1HalfLength(), G4TwistedTrap::GetX1HalfLength(), and G4TwistedBox::GetXHalfLength().
G4double G4VTwistedFaceted::GetDx2 () const inline
Definition at line 113 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VTwistedFaceted.hh
References fDx2.
Referenced by G4TwistedTrap::GetX2HalfLength().
G4double G4VTwistedFaceted::GetDx3 () const inline
Definition at line 114 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VTwistedFaceted.hh
References fDx3.
Referenced by G4TwistedTrd::GetX2HalfLength(), and G4TwistedTrap::GetX3HalfLength().
G4double G4VTwistedFaceted::GetDx4 () const inline
Definition at line 115 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VTwistedFaceted.hh
References fDx4.
Referenced by G4TwistedTrap::GetX4HalfLength().
G4double G4VTwistedFaceted::GetDy1 () const inline
Definition at line 116 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VTwistedFaceted.hh
References fDy1.
Referenced by G4TwistedTrd::GetY1HalfLength(), G4TwistedTrap::GetY1HalfLength(), and G4TwistedBox::GetYHalfLength().
G4double G4VTwistedFaceted::GetDy2 () const inline
Definition at line 117 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 117 of file G4VTwistedFaceted.hh
References fDy2.
Referenced by G4TwistedTrd::GetY2HalfLength(), and G4TwistedTrap::GetY2HalfLength().
G4double G4VTwistedFaceted::GetDz () const inline
Definition at line 118 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VTwistedFaceted.hh
References fDz.
Referenced by G4TwistedBox::GetZHalfLength(), G4TwistedTrd::GetZHalfLength(), and G4TwistedTrap::GetZHalfLength().
G4GeometryType G4VTwistedFaceted::GetEntityType () const virtual
Implements G4VSolid.
Reimplemented in G4TwistedTrap, G4TwistedTrd, and G4TwistedBox.
Definition at line 993 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 993 of file G4VTwistedFaceted.cc
G4VisExtent G4VTwistedFaceted::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 931 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 931 of file G4VTwistedFaceted.cc
References fDx, fDy, and fDz.
G4double G4VTwistedFaceted::GetPhi () const inline
Definition at line 119 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VTwistedFaceted.hh
References fPhi.
Referenced by G4TwistedTrap::GetAzimuthalAnglePhi().
G4ThreeVector G4VTwistedFaceted::GetPointInSolid (G4double z) const
Definition at line 1023 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 1023 of file G4VTwistedFaceted.cc
References fdeltaX, fdeltaY, fDz, fPhiTwist, and phi.
G4ThreeVector G4VTwistedFaceted::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1042 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 1042 of file G4VTwistedFaceted.cc
References fDy1, fDy2, fLowerEndcap, fPhiTwist, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4cout, G4endl, G4VTwistSurface::GetBoundaryMax(), G4VTwistSurface::GetBoundaryMin(), G4VTwistSurface::GetSurfaceArea(), phi, G4INCL::DeJongSpin::shoot(), G4VTwistSurface::SurfacePoint(), Acts::UnitConstants::u, and y.
G4Polyhedron * G4VTwistedFaceted::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1002 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 1002 of file G4VTwistedFaceted.cc
References CreatePolyhedron(), fpPolyhedron, fRebuildPolyhedron, HepPolyhedron::GetNumberOfRotationSteps(), G4Polyhedron::GetNumberOfRotationStepsAtTimeOfCreation(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by G4TwistedBox::G4TwistedBox(), G4TwistedTrap::G4TwistedTrap(), G4TwistedTrd::G4TwistedTrd(), G4TwistedBox::operator=(), G4TwistedTrd::operator=(), and G4TwistedTrap::operator=().
G4double G4VTwistedFaceted::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
Definition at line 307 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 307 of file G4VTwistedFaceted.hh
References fSurfaceArea, and G4VSolid::GetSurfaceArea().
G4double G4VTwistedFaceted::GetTheta () const inline
Definition at line 120 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VTwistedFaceted.hh
References fTheta.
Referenced by G4TwistedTrap::GetPolarAngleTheta().
G4double G4VTwistedFaceted::GetTwistAngle () const inline
Definition at line 110 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VTwistedFaceted.hh
References fPhiTwist.
Referenced by G4TwistedBox::GetPhiTwist(), G4TwistedTrd::GetPhiTwist(), and G4TwistedTrap::GetPhiTwist().
G4double G4VTwistedFaceted::GetValueA (G4double phi) const inline
Definition at line 315 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 315 of file G4VTwistedFaceted.hh
References fDx2, fDx4, and fPhiTwist.
Referenced by Xcoef().
G4double G4VTwistedFaceted::GetValueB (G4double phi) const inline
Definition at line 327 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 327 of file G4VTwistedFaceted.hh
References fDy1, fDy2, and fPhiTwist.
Referenced by Inside(), and Xcoef().
G4double G4VTwistedFaceted::GetValueD (G4double phi) const inline
Definition at line 321 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 321 of file G4VTwistedFaceted.hh
References fDx1, fDx3, and fPhiTwist.
Referenced by Xcoef().
EInside G4VTwistedFaceted::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 326 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 326 of file G4VTwistedFaceted.cc
References fAlph, fdeltaX, fdeltaY, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fLastInside, fPhi, fPhiTwist, fTAlph, fTheta, G4cout, G4endl, GetValueB(), G4VTwistedFaceted::LastState::inside, G4VSolid::kCarTolerance, kInside, kOutside, kSurface, G4VTwistedFaceted::LastState::p, phi, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), Xcoef(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToIn(), and DistanceToOut().
G4VTwistedFaceted & G4VTwistedFaceted::operator= (const G4VTwistedFaceted & rhs)
Definition at line 244 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 244 of file G4VTwistedFaceted.cc
References CreateSurfaces(), fAlph, fCubicVolume, fdeltaX, fdeltaY, fDx, fDx1, fDx2, fDx3, fDx4, fDy, fDy1, fDy2, fDz, fLastDistanceToIn, fLastDistanceToInWithV, fLastDistanceToOut, fLastDistanceToOutWithV, fLastInside, fLastNormal, fLowerEndcap, fPhi, fPhiTwist, fpPolyhedron, fRebuildPolyhedron, fSide0, fSide180, fSide270, fSide90, fSurfaceArea, fTAlph, fTheta, fUpperEndcap, and G4VSolid::operator=().
Referenced by G4TwistedBox::operator=(), G4TwistedTrd::operator=(), and G4TwistedTrap::operator=().
std::ostream & G4VTwistedFaceted::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Reimplemented in G4TwistedTrap, G4TwistedTrd, and G4TwistedBox.
Definition at line 885 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 885 of file G4VTwistedFaceted.cc
References cm, degree, fAlph, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fPhi, fPhiTwist, fTheta, G4endl, and G4VSolid::GetName().
G4ThreeVector G4VTwistedFaceted::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 427 of file G4VTwistedFaceted.cc.
View newest version in sPHENIX GitHub at line 427 of file G4VTwistedFaceted.cc
References G4VTwistSurface::DistanceTo(), fLastNormal, fLowerEndcap, fSide0, fSide180, fSide270, fSide90, fUpperEndcap, G4VTwistSurface::GetNormal(), kInfinity, G4VTwistedFaceted::LastVector::p, CLHEP::Hep3Vector::set(), G4VTwistedFaceted::LastVector::surface, G4VTwistedFaceted::LastVector::vec, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToIn(), and DistanceToOut().
G4double G4VTwistedFaceted::Xcoef (G4double u, G4double phi, G4double ftg) const inline
Definition at line 333 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 333 of file G4VTwistedFaceted.hh
References GetValueA(), GetValueB(), and GetValueD().
Referenced by Inside().
Member Data Documentation
G4double G4VTwistedFaceted::fAlph private
Definition at line 171 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 171 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetAlpha(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fCubicVolume = 0.0 private
Definition at line 187 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 187 of file G4VTwistedFaceted.hh
Referenced by G4VTwistedFaceted(), GetCubicVolume(), and operator=().
G4double G4VTwistedFaceted::fdeltaX private
Definition at line 174 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 174 of file G4VTwistedFaceted.hh
Referenced by G4VTwistedFaceted(), GetPointInSolid(), Inside(), and operator=().
G4double G4VTwistedFaceted::fdeltaY private
Definition at line 175 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 175 of file G4VTwistedFaceted.hh
Referenced by G4VTwistedFaceted(), GetPointInSolid(), Inside(), and operator=().
G4double G4VTwistedFaceted::fDx private
Definition at line 168 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VTwistedFaceted.hh
Referenced by BoundingLimits(), G4VTwistedFaceted(), GetExtent(), and operator=().
G4double G4VTwistedFaceted::fDx1 private
Definition at line 159 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 159 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDx1(), GetValueD(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fDx2 private
Definition at line 160 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 160 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDx2(), GetValueA(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fDx3 private
Definition at line 163 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 163 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDx3(), GetValueD(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fDx4 private
Definition at line 164 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 164 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDx4(), GetValueA(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fDy private
Definition at line 169 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 169 of file G4VTwistedFaceted.hh
Referenced by BoundingLimits(), G4VTwistedFaceted(), GetExtent(), and operator=().
G4double G4VTwistedFaceted::fDy1 private
Definition at line 158 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 158 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDy1(), GetPointOnSurface(), GetValueB(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fDy2 private
Definition at line 162 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 162 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDy2(), GetPointOnSurface(), GetValueB(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fDz private
Definition at line 166 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 166 of file G4VTwistedFaceted.hh
Referenced by BoundingLimits(), CreateSurfaces(), G4VTwistedFaceted(), GetCubicVolume(), GetDz(), GetExtent(), GetPointInSolid(), Inside(), and operator=().
LastValue G4VTwistedFaceted::fLastDistanceToIn private
Definition at line 289 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 289 of file G4VTwistedFaceted.hh
Referenced by DistanceToIn(), and operator=().
LastValueWithDoubleVector G4VTwistedFaceted::fLastDistanceToInWithV private
Definition at line 291 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 291 of file G4VTwistedFaceted.hh
Referenced by DistanceToIn(), and operator=().
LastValue G4VTwistedFaceted::fLastDistanceToOut private
Definition at line 290 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 290 of file G4VTwistedFaceted.hh
Referenced by DistanceToOut(), and operator=().
LastValueWithDoubleVector G4VTwistedFaceted::fLastDistanceToOutWithV private
Definition at line 292 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 292 of file G4VTwistedFaceted.hh
Referenced by DistanceToOut(), and operator=().
LastState G4VTwistedFaceted::fLastInside private
Definition at line 287 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 287 of file G4VTwistedFaceted.hh
Referenced by Inside(), and operator=().
LastVector G4VTwistedFaceted::fLastNormal private
Definition at line 288 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 288 of file G4VTwistedFaceted.hh
Referenced by DistanceToOut(), operator=(), and SurfaceNormal().
G4VTwistSurface* G4VTwistedFaceted::fLowerEndcap private
Definition at line 179 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 179 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4VTwistedFaceted().
G4double G4VTwistedFaceted::fPhi private
Definition at line 156 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 156 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetPhi(), Inside(), operator=(), and StreamInfo().
G4double G4VTwistedFaceted::fPhiTwist private
Definition at line 177 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 177 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), G4VTwistedFaceted(), GetPointInSolid(), GetPointOnSurface(), GetTwistAngle(), GetValueA(), GetValueB(), GetValueD(), Inside(), operator=(), and StreamInfo().
G4Polyhedron* G4VTwistedFaceted::fpPolyhedron = nullptr mutable protected
Definition at line 147 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VTwistedFaceted.hh
Referenced by G4TwistedBox::G4TwistedBox(), G4TwistedTrap::G4TwistedTrap(), G4TwistedTrd::G4TwistedTrd(), GetPolyhedron(), G4TwistedBox::operator=(), G4TwistedTrd::operator=(), G4TwistedTrap::operator=(), operator=(), and ~G4VTwistedFaceted().
G4bool G4VTwistedFaceted::fRebuildPolyhedron = false mutable protected
Definition at line 146 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 146 of file G4VTwistedFaceted.hh
Referenced by GetPolyhedron(), and operator=().
G4VTwistSurface* G4VTwistedFaceted::fSide0 private
Definition at line 182 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 182 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4VTwistedFaceted().
G4VTwistSurface* G4VTwistedFaceted::fSide180 private
Definition at line 184 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 184 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4VTwistedFaceted().
G4VTwistSurface* G4VTwistedFaceted::fSide270 private
Definition at line 185 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 185 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4VTwistedFaceted().
G4VTwistSurface* G4VTwistedFaceted::fSide90 private
Definition at line 183 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 183 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4VTwistedFaceted().
G4double G4VTwistedFaceted::fSurfaceArea = 0.0 private
Definition at line 188 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 188 of file G4VTwistedFaceted.hh
Referenced by GetSurfaceArea(), and operator=().
G4double G4VTwistedFaceted::fTAlph private
Definition at line 172 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 172 of file G4VTwistedFaceted.hh
Referenced by G4VTwistedFaceted(), Inside(), and operator=().
G4double G4VTwistedFaceted::fTheta private
Definition at line 155 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 155 of file G4VTwistedFaceted.hh
Referenced by CreateSurfaces(), G4VTwistedFaceted(), GetTheta(), Inside(), operator=(), and StreamInfo().
G4VTwistSurface* G4VTwistedFaceted::fUpperEndcap private
Definition at line 180 of file G4VTwistedFaceted.hh.
View newest version in sPHENIX GitHub at line 180 of file G4VTwistedFaceted.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4VTwistedFaceted().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistedFaceted.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4VTwistedFaceted.cc