ECCE @ EIC Software: G4HadronPhysicsFTFP_BERT_HP Class Reference
G4HadronPhysicsFTFP_BERT_HP Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTFP_BERT_HP.hh>
Public Member Functions
G4HadronPhysicsFTFP_BERT_HP (G4int verbose=1)
G4HadronPhysicsFTFP_BERT_HP (const G4String &name, G4bool quasiElastic=false)
virtual ~G4HadronPhysicsFTFP_BERT_HP ()
Public Member Functions inherited from G4HadronPhysicsFTFP_BERT
G4HadronPhysicsFTFP_BERT (G4int verbose=1)
G4HadronPhysicsFTFP_BERT (const G4String &name, G4bool quasiElastic=false)
virtual ~G4HadronPhysicsFTFP_BERT ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Member Functions
virtual void Neutron () override
virtual void DumpBanner () override
virtual void ExtraConfiguration () override
Protected Member Functions inherited from G4HadronPhysicsFTFP_BERT
virtual void CreateModels ()
virtual void Proton ()
virtual void Pion ()
virtual void Kaon ()
virtual void Others ()
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes
double minBERT_neutron
Protected Attributes inherited from G4HadronPhysicsFTFP_BERT
G4bool QuasiElastic
G4double minFTFP_pion
G4double maxBERT_pion
G4double minFTFP_kaon
G4double maxBERT_kaon
G4double minFTFP_proton
G4double maxBERT_proton
G4double minFTFP_neutron
G4double maxBERT_neutron
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 44 of file G4HadronPhysicsFTFP_BERT_HP.hh.
View newest version in sPHENIX GitHub at line 44 of file G4HadronPhysicsFTFP_BERT_HP.hh
Constructor & Destructor Documentation
G4HadronPhysicsFTFP_BERT_HP::G4HadronPhysicsFTFP_BERT_HP (G4int verbose = 1)
Definition at line 62 of file G4HadronPhysicsFTFP_BERT_HP.cc.
View newest version in sPHENIX GitHub at line 62 of file G4HadronPhysicsFTFP_BERT_HP.cc
G4HadronPhysicsFTFP_BERT_HP::G4HadronPhysicsFTFP_BERT_HP (const G4String & name, G4bool quasiElastic = false)
Definition at line 66 of file G4HadronPhysicsFTFP_BERT_HP.cc.
View newest version in sPHENIX GitHub at line 66 of file G4HadronPhysicsFTFP_BERT_HP.cc
References MeV, and minBERT_neutron.
virtual G4HadronPhysicsFTFP_BERT_HP::~G4HadronPhysicsFTFP_BERT_HP () inline virtual
Definition at line 49 of file G4HadronPhysicsFTFP_BERT_HP.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HadronPhysicsFTFP_BERT_HP.hh
Member Function Documentation
void G4HadronPhysicsFTFP_BERT_HP::DumpBanner () override protected virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 72 of file G4HadronPhysicsFTFP_BERT_HP.cc.
View newest version in sPHENIX GitHub at line 72 of file G4HadronPhysicsFTFP_BERT_HP.cc
References G4cout, G4endl, GeV, G4HadronPhysicsFTFP_BERT::maxBERT_kaon, G4HadronPhysicsFTFP_BERT::maxBERT_neutron, G4HadronPhysicsFTFP_BERT::maxBERT_pion, G4HadronPhysicsFTFP_BERT::maxBERT_proton, G4HadronPhysicsFTFP_BERT::minFTFP_kaon, G4HadronPhysicsFTFP_BERT::minFTFP_neutron, G4HadronPhysicsFTFP_BERT::minFTFP_pion, and G4HadronPhysicsFTFP_BERT::minFTFP_proton.
void G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration () override protected virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 102 of file G4HadronPhysicsFTFP_BERT_HP.cc.
View newest version in sPHENIX GitHub at line 102 of file G4HadronPhysicsFTFP_BERT_HP.cc
References G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindFissionProcess(), G4HadronicParameters::Instance(), minBERT_neutron, G4InuclParticleNames::neutron, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
void G4HadronPhysicsFTFP_BERT_HP::Neutron () override protected virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 83 of file G4HadronPhysicsFTFP_BERT_HP.cc.
View newest version in sPHENIX GitHub at line 83 of file G4HadronPhysicsFTFP_BERT_HP.cc
References G4VPhysicsConstructor::AddBuilder(), G4HadronPhysicsFTFP_BERT::maxBERT_neutron, minBERT_neutron, G4HadronPhysicsFTFP_BERT::minFTFP_neutron, G4InuclParticleNames::neu, and G4HadronPhysicsFTFP_BERT::QuasiElastic.
Member Data Documentation
double G4HadronPhysicsFTFP_BERT_HP::minBERT_neutron protected
Definition at line 57 of file G4HadronPhysicsFTFP_BERT_HP.hh.
View newest version in sPHENIX GitHub at line 57 of file G4HadronPhysicsFTFP_BERT_HP.hh
Referenced by ExtraConfiguration(), G4HadronPhysicsFTFP_BERT_HP(), and Neutron().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTFP_BERT_HP.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsFTFP_BERT_HP.cc