ECCE @ EIC Software: G4QGSPLundStrFragmProtonBuilder Class Reference
G4QGSPLundStrFragmProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPLundStrFragmProtonBuilder.hh>
Public Member Functions
G4QGSPLundStrFragmProtonBuilder (G4bool quasiElastic=false)
virtual ~G4QGSPLundStrFragmProtonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4LundStringFragmentation * theStrFragm
G4double theMin
Detailed Description
Definition at line 55 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 55 of file G4QGSPLundStrFragmProtonBuilder.hh
Constructor & Destructor Documentation
G4QGSPLundStrFragmProtonBuilder::G4QGSPLundStrFragmProtonBuilder (G4bool quasiElastic = false)
Definition at line 47 of file G4QGSPLundStrFragmProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 47 of file G4QGSPLundStrFragmProtonBuilder.cc
References GeV, G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQuasiElastic, theStrFragm, theStringDecay, and theStringModel.
G4QGSPLundStrFragmProtonBuilder::~G4QGSPLundStrFragmProtonBuilder () virtual
Definition at line 78 of file G4QGSPLundStrFragmProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPLundStrFragmProtonBuilder.cc
References theQuasiElastic, theStrFragm, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSPLundStrFragmProtonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VProtonBuilder.
Definition at line 64 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QGSPLundStrFragmProtonBuilder.hh
void G4QGSPLundStrFragmProtonBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 70 of file G4QGSPLundStrFragmProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 70 of file G4QGSPLundStrFragmProtonBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicParameters::Instance(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSPLundStrFragmProtonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4QGSPLundStrFragmProtonBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4QGSPLundStrFragmProtonBuilder::theCascade private
Definition at line 73 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by G4QGSPLundStrFragmProtonBuilder().
G4double G4QGSPLundStrFragmProtonBuilder::theMin private
Definition at line 78 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by Build(), G4QGSPLundStrFragmProtonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSPLundStrFragmProtonBuilder::theModel private
Definition at line 72 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by Build(), and G4QGSPLundStrFragmProtonBuilder().
G4QuasiElasticChannel* G4QGSPLundStrFragmProtonBuilder::theQuasiElastic private
Definition at line 76 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by G4QGSPLundStrFragmProtonBuilder(), and ~G4QGSPLundStrFragmProtonBuilder().
G4LundStringFragmentation* G4QGSPLundStrFragmProtonBuilder::theStrFragm private
Definition at line 77 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by G4QGSPLundStrFragmProtonBuilder(), and ~G4QGSPLundStrFragmProtonBuilder().
G4ExcitedStringDecay* G4QGSPLundStrFragmProtonBuilder::theStringDecay private
Definition at line 75 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by G4QGSPLundStrFragmProtonBuilder(), and ~G4QGSPLundStrFragmProtonBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSPLundStrFragmProtonBuilder::theStringModel private
Definition at line 74 of file G4QGSPLundStrFragmProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSPLundStrFragmProtonBuilder.hh
Referenced by G4QGSPLundStrFragmProtonBuilder(), and ~G4QGSPLundStrFragmProtonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPLundStrFragmProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSPLundStrFragmProtonBuilder.cc