ECCE @ EIC Software: G4VDigiCollection Class Reference
G4VDigiCollection Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4VDigiCollection.hh>
Public Member Functions
G4VDigiCollection ()
G4VDigiCollection (G4String DMnam, G4String colNam)
virtual ~G4VDigiCollection ()
G4bool operator== (const G4VDigiCollection &right) const
virtual void DrawAllDigi ()
virtual void PrintAllDigi ()
const G4String & GetName () const
const G4String & GetDMname () const
virtual G4VDigi * GetDigi (size_t) const
virtual size_t GetSize () const
Protected Attributes
G4String collectionName
G4String DMname
Detailed Description
Definition at line 44 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VDigiCollection.hh
Constructor & Destructor Documentation
G4VDigiCollection::G4VDigiCollection ()
Definition at line 33 of file G4VDigiCollection.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VDigiCollection.cc
References collectionName, and DMname.
G4VDigiCollection::G4VDigiCollection (G4String DMnam, G4String colNam)
Definition at line 39 of file G4VDigiCollection.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VDigiCollection.cc
References collectionName, and DMname.
G4VDigiCollection::~G4VDigiCollection () virtual
Definition at line 45 of file G4VDigiCollection.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VDigiCollection.cc
Member Function Documentation
void G4VDigiCollection::DrawAllDigi () virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 54 of file G4VDigiCollection.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VDigiCollection.cc
Referenced by G4Event::Draw().
virtual G4VDigi* G4VDigiCollection::GetDigi (size_t) const inline virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 71 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VDigiCollection.hh
const G4String& G4VDigiCollection::GetDMname () const inline
Definition at line 64 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VDigiCollection.hh
References DMname.
const G4String& G4VDigiCollection::GetName (void) const inline
Definition at line 62 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VDigiCollection.hh
References collectionName.
Referenced by G4DigiManager::SetDigiCollection(), and G4VDigitizerModule::StoreDigiCollection().
virtual size_t G4VDigiCollection::GetSize () const inline virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 72 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VDigiCollection.hh
Referenced by G4DigiModel::DescribeYourselfTo().
G4bool G4VDigiCollection::operator== (const G4VDigiCollection & right) const
Definition at line 48 of file G4VDigiCollection.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VDigiCollection.cc
References collectionName, and DMname.
void G4VDigiCollection::PrintAllDigi () virtual
Reimplemented in G4TDigiCollection< T >.
Definition at line 57 of file G4VDigiCollection.cc.
View newest version in sPHENIX GitHub at line 57 of file G4VDigiCollection.cc
Member Data Documentation
G4String G4VDigiCollection::collectionName protected
Definition at line 58 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VDigiCollection.hh
Referenced by G4VDigiCollection(), GetName(), operator==(), G4DigiCollection::operator==(), and G4TDigiCollection< T >::operator==().
G4String G4VDigiCollection::DMname protected
Definition at line 59 of file G4VDigiCollection.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VDigiCollection.hh
Referenced by G4VDigiCollection(), GetDMname(), and operator==().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4VDigiCollection.hh
geant4/tree/geant4-10.6-release/source/digits_hits/digits/src/G4VDigiCollection.cc