ECCE @ EIC Software: G4AlphaBuilder Class Reference
G4AlphaBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4AlphaBuilder.hh>
Public Member Functions
G4AlphaBuilder ()
virtual ~G4AlphaBuilder ()
virtual void Build () finaloverride
void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4AlphaInelasticProcess * theAlphaInelastic
std::vector< G4VAlphaBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 46 of file G4AlphaBuilder.hh.
View newest version in sPHENIX GitHub at line 46 of file G4AlphaBuilder.hh
Constructor & Destructor Documentation
G4AlphaBuilder::G4AlphaBuilder ()
Definition at line 55 of file G4AlphaBuilder.cc.
View newest version in sPHENIX GitHub at line 55 of file G4AlphaBuilder.cc
References theAlphaInelastic.
virtual G4AlphaBuilder::~G4AlphaBuilder () inline virtual
Definition at line 50 of file G4AlphaBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4AlphaBuilder.hh
Member Function Documentation
void G4AlphaBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 42 of file G4AlphaBuilder.cc.
View newest version in sPHENIX GitHub at line 42 of file G4AlphaBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4Alpha::Alpha(), G4ParticleDefinition::GetProcessManager(), theAlphaInelastic, theModelCollections, and wasActivated.
void G4AlphaBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 60 of file G4AlphaBuilder.cc.
View newest version in sPHENIX GitHub at line 60 of file G4AlphaBuilder.cc
References ab, G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Member Data Documentation
G4AlphaInelasticProcess* G4AlphaBuilder::theAlphaInelastic private
Definition at line 56 of file G4AlphaBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4AlphaBuilder.hh
Referenced by Build(), and G4AlphaBuilder().
std::vector<G4VAlphaBuilder *> G4AlphaBuilder::theModelCollections private
Definition at line 58 of file G4AlphaBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4AlphaBuilder.hh
Referenced by Build(), and RegisterMe().
G4bool G4AlphaBuilder::wasActivated private
Definition at line 60 of file G4AlphaBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4AlphaBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4AlphaBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4AlphaBuilder.cc