ECCE @ EIC Software: G4VBiasingOperator Class Reference
G4VBiasingOperator Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4VBiasingOperator.hh>
Public Member Functions
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartRun ()
virtual void StartTracking (const G4Track *)
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Static Public Member Functions
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)=0
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)=0
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)=0
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Private Attributes
const G4String fName
std::vector< const
G4LogicalVolume * > fRootVolumes
std::map< const
G4LogicalVolume *, G4int > fDepthInTree
G4VBiasingOperation * fOccurenceBiasingOperation
G4VBiasingOperation * fFinalStateBiasingOperation
G4VBiasingOperation * fNonPhysicsBiasingOperation
const G4VBiasingOperation * fPreviousProposedOccurenceBiasingOperation
const G4VBiasingOperation * fPreviousProposedFinalStateBiasingOperation
const G4VBiasingOperation * fPreviousProposedNonPhysicsBiasingOperation
const G4VBiasingOperation * fPreviousAppliedOccurenceBiasingOperation
const G4VBiasingOperation * fPreviousAppliedFinalStateBiasingOperation
const G4VBiasingOperation * fPreviousAppliedNonPhysicsBiasingOperation
G4BiasingAppliedCase fPreviousBiasingAppliedCase
Static Private Attributes
static G4MapCache< const
G4LogicalVolume
*, G4VBiasingOperator * > fLogicalToSetupMap
static G4VectorCache
< G4VBiasingOperator * > fOperators
static G4Cache
< G4BiasingOperatorStateNotifier * > fStateNotifier
Friends
class G4BiasingOperatorStateNotifier
Detailed Description
Definition at line 180 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 180 of file G4VBiasingOperator.hh
Constructor & Destructor Documentation
G4VBiasingOperator::G4VBiasingOperator (G4String name)
Definition at line 36 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VBiasingOperator.cc
References fOperators, fStateNotifier, G4Cache< VALTYPE >::Get(), G4VectorCache< VALTYPE >::Push_back(), and G4Cache< VALTYPE >::Put().
G4VBiasingOperator::~G4VBiasingOperator () virtual
Definition at line 55 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VBiasingOperator.cc
Member Function Documentation
void G4VBiasingOperator::AttachTo (const G4LogicalVolume * logical)
Definition at line 59 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VBiasingOperator.cc
References G4MapCache< KEYTYPE, VALTYPE >::End(), G4MapCache< KEYTYPE, VALTYPE >::Find(), fLogicalToSetupMap, G4endl, G4Exception(), G4LogicalVolume::GetName(), GetName(), it, and JustWarning.
Referenced by GB05DetectorConstruction::ConstructSDandField(), GB07DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), and GB03DetectorConstruction::SetupBiasing().
virtual void G4VBiasingOperator::Configure () inline virtual
Reimplemented in G4BOptrForceCollision.
Definition at line 271 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 271 of file G4VBiasingOperator.hh
virtual void G4VBiasingOperator::ConfigureForWorker () inline virtual
Reimplemented in G4BOptrForceCollision.
Definition at line 274 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 274 of file G4VBiasingOperator.hh
virtual void G4VBiasingOperator::EndTracking () inline virtual
Reimplemented in G4BOptrForceCollision.
Definition at line 279 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 279 of file G4VBiasingOperator.hh
void G4VBiasingOperator::ExitBiasing (const G4Track * track, const G4BiasingProcessInterface * callingProcess) protected virtual
Reimplemented in GB02BOptrMultiParticleForceCollision, and G4BOptrForceCollision.
Definition at line 173 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 173 of file G4VBiasingOperator.cc
Referenced by ExitingBiasing().
void G4VBiasingOperator::ExitingBiasing (const G4Track * track, const G4BiasingProcessInterface * callingProcess)
Definition at line 152 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 152 of file G4VBiasingOperator.cc
References BAC_None, ExitBiasing(), fFinalStateBiasingOperation, fNonPhysicsBiasingOperation, fOccurenceBiasingOperation, fPreviousAppliedFinalStateBiasingOperation, fPreviousAppliedNonPhysicsBiasingOperation, fPreviousAppliedOccurenceBiasingOperation, fPreviousBiasingAppliedCase, fPreviousProposedFinalStateBiasingOperation, fPreviousProposedNonPhysicsBiasingOperation, and fPreviousProposedOccurenceBiasingOperation.
Referenced by GB02BOptrMultiParticleForceCollision::ExitBiasing().
G4VBiasingOperator * G4VBiasingOperator::GetBiasingOperator (const G4LogicalVolume * logical) static
Definition at line 78 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 78 of file G4VBiasingOperator.cc
References G4MapCache< KEYTYPE, VALTYPE >::End(), G4MapCache< KEYTYPE, VALTYPE >::Find(), fLogicalToSetupMap, and it.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength().
static const std::vector< G4VBiasingOperator* >& G4VBiasingOperator::GetBiasingOperators () inline static
Definition at line 293 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 293 of file G4VBiasingOperator.hh
References fOperators, and G4Cache< VALTYPE >::Get().
Referenced by G4BiasingProcessInterface::BuildPhysicsTable(), G4BiasingProcessInterface::BuildWorkerPhysicsTable(), G4BiasingProcessInterface::EndTracking(), and G4BiasingProcessInterface::StartTracking().
const G4String G4VBiasingOperator::GetName (void) const inline
Definition at line 288 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 288 of file G4VBiasingOperator.hh
References fName.
Referenced by AttachTo(), GB05DetectorConstruction::ConstructSDandField(), GB07DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), G4BOptrForceCollision::EndTracking(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4BOptrForceCollisionTrackData::Print(), GB04BOptrBremSplitting::StartRun(), GB03BOptrGeometryBasedBiasing::StartRun(), and G4BOptrForceCollisionTrackData::~G4BOptrForceCollisionTrackData().
G4BiasingAppliedCase G4VBiasingOperator::GetPreviousBiasingAppliedCase () const inline
Definition at line 291 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 291 of file G4VBiasingOperator.hh
References fPreviousBiasingAppliedCase.
const G4VBiasingOperation* G4VBiasingOperator::GetPreviousNonPhysicsAppliedOperation () inline
Definition at line 315 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 315 of file G4VBiasingOperator.hh
References fPreviousAppliedNonPhysicsBiasingOperation.
G4VBiasingOperation * G4VBiasingOperator::GetProposedFinalStateBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess)
Definition at line 92 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 92 of file G4VBiasingOperator.cc
References fFinalStateBiasingOperation, and ProposeFinalStateBiasingOperation().
Referenced by GB02BOptrMultiParticleForceCollision::ProposeFinalStateBiasingOperation().
G4VBiasingOperation * G4VBiasingOperator::GetProposedNonPhysicsBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess)
Definition at line 98 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 98 of file G4VBiasingOperator.cc
References fNonPhysicsBiasingOperation, and ProposeNonPhysicsBiasingOperation().
Referenced by GB02BOptrMultiParticleForceCollision::ProposeNonPhysicsBiasingOperation().
G4VBiasingOperation * G4VBiasingOperator::GetProposedOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess)
Definition at line 86 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 86 of file G4VBiasingOperator.cc
References fOccurenceBiasingOperation, and ProposeOccurenceBiasingOperation().
Referenced by GB02BOptrMultiParticleForceCollision::ProposeOccurenceBiasingOperation(), G4ChannelingOptrMultiParticleChangeCrossSection::ProposeOccurenceBiasingOperation(), and GB01BOptrMultiParticleChangeCrossSection::ProposeOccurenceBiasingOperation().
void G4VBiasingOperator::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * operationApplied, const G4VParticleChange * particleChangeProduced) protected virtual
Reimplemented in G4BOptrForceCollision, and GB02BOptrMultiParticleForceCollision.
Definition at line 175 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 175 of file G4VBiasingOperator.cc
Referenced by ReportOperationApplied().
void G4VBiasingOperator::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) protected virtual
Reimplemented in GB01BOptrMultiParticleChangeCrossSection, G4ChannelingOptrMultiParticleChangeCrossSection, GB01BOptrChangeCrossSection, G4ChannelingOptrChangeCrossSection, G4BOptrForceCollision, and GB02BOptrMultiParticleForceCollision.
Definition at line 179 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 179 of file G4VBiasingOperator.cc
virtual G4VBiasingOperation* G4VBiasingOperator::ProposeFinalStateBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) protected pure virtual
Implemented in GB06BOptrSplitAndKillByImportance, GB05BOptrSplitAndKillByCrossSection, GB01BOptrMultiParticleChangeCrossSection, G4ChannelingOptrChangeCrossSection, GB01BOptrChangeCrossSection, G4ChannelingOptrMultiParticleChangeCrossSection, GB03BOptrGeometryBasedBiasing, G4BOptrForceCollision, GB04BOptrBremSplitting, GB02BOptrMultiParticleForceCollision, GB07BOptrLeadingParticle, and BiasingOperator.
Referenced by GetProposedFinalStateBiasingOperation().
virtual G4VBiasingOperation* G4VBiasingOperator::ProposeNonPhysicsBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) protected pure virtual
Implemented in GB06BOptrSplitAndKillByImportance, GB05BOptrSplitAndKillByCrossSection, GB01BOptrMultiParticleChangeCrossSection, G4ChannelingOptrChangeCrossSection, GB01BOptrChangeCrossSection, G4ChannelingOptrMultiParticleChangeCrossSection, G4BOptrForceCollision, GB03BOptrGeometryBasedBiasing, BiasingOperator, GB04BOptrBremSplitting, GB02BOptrMultiParticleForceCollision, and GB07BOptrLeadingParticle.
Referenced by GetProposedNonPhysicsBiasingOperation().
virtual G4VBiasingOperation* G4VBiasingOperator::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) protected pure virtual
Implemented in GB06BOptrSplitAndKillByImportance, GB05BOptrSplitAndKillByCrossSection, G4ChannelingOptrChangeCrossSection, GB01BOptrMultiParticleChangeCrossSection, GB01BOptrChangeCrossSection, G4ChannelingOptrMultiParticleChangeCrossSection, GB03BOptrGeometryBasedBiasing, G4BOptrForceCollision, GB04BOptrBremSplitting, BiasingOperator, GB02BOptrMultiParticleForceCollision, and GB07BOptrLeadingParticle.
Referenced by GetProposedOccurenceBiasingOperation().
void G4VBiasingOperator::ReportOperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * operationApplied, const G4VParticleChange * particleChangeProduced)
Definition at line 104 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 104 of file G4VBiasingOperator.cc
References BAC_FinalState, BAC_None, BAC_NonPhysics, BAC_Occurence, fPreviousAppliedFinalStateBiasingOperation, fPreviousAppliedNonPhysicsBiasingOperation, fPreviousAppliedOccurenceBiasingOperation, fPreviousBiasingAppliedCase, G4Exception(), JustWarning, and OperationApplied().
Referenced by GB02BOptrMultiParticleForceCollision::OperationApplied(), G4ChannelingOptrMultiParticleChangeCrossSection::OperationApplied(), and GB01BOptrMultiParticleChangeCrossSection::OperationApplied().
void G4VBiasingOperator::ReportOperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced)
Definition at line 138 of file G4VBiasingOperator.cc.
View newest version in sPHENIX GitHub at line 138 of file G4VBiasingOperator.cc
References fPreviousAppliedFinalStateBiasingOperation, fPreviousAppliedOccurenceBiasingOperation, fPreviousBiasingAppliedCase, and OperationApplied().
virtual void G4VBiasingOperator::StartRun () inline virtual
Reimplemented in G4BOptrForceCollision, GB06BOptrSplitAndKillByImportance, GB05BOptrSplitAndKillByCrossSection, GB07BOptrLeadingParticle, G4ChannelingOptrChangeCrossSection, GB01BOptrChangeCrossSection, GB03BOptrGeometryBasedBiasing, and GB04BOptrBremSplitting.
Definition at line 276 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 276 of file G4VBiasingOperator.hh
virtual void G4VBiasingOperator::StartTracking (const G4Track *) inline virtual
Reimplemented in GB01BOptrMultiParticleChangeCrossSection, G4ChannelingOptrMultiParticleChangeCrossSection, GB02BOptrMultiParticleForceCollision, G4BOptrForceCollision, GB07BOptrLeadingParticle, and GB04BOptrBremSplitting.
Definition at line 278 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 278 of file G4VBiasingOperator.hh
Friends And Related Function Documentation
friend class G4BiasingOperatorStateNotifier friend
Definition at line 185 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 185 of file G4VBiasingOperator.hh
Member Data Documentation
std::map< const G4LogicalVolume*, G4int > G4VBiasingOperator::fDepthInTree private
Definition at line 333 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 333 of file G4VBiasingOperator.hh
G4VBiasingOperation* G4VBiasingOperator::fFinalStateBiasingOperation private
Definition at line 337 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 337 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), and GetProposedFinalStateBiasingOperation().
G4MapCache< const G4LogicalVolume *, G4VBiasingOperator * > G4VBiasingOperator::fLogicalToSetupMap static private
Definition at line 322 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 322 of file G4VBiasingOperator.hh
Referenced by AttachTo(), and GetBiasingOperator().
const G4String G4VBiasingOperator::fName private
Definition at line 319 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 319 of file G4VBiasingOperator.hh
Referenced by GetName().
G4VBiasingOperation* G4VBiasingOperator::fNonPhysicsBiasingOperation private
Definition at line 338 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 338 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), and GetProposedNonPhysicsBiasingOperation().
G4VBiasingOperation* G4VBiasingOperator::fOccurenceBiasingOperation private
Definition at line 336 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 336 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), and GetProposedOccurenceBiasingOperation().
G4VectorCache< G4VBiasingOperator * > G4VBiasingOperator::fOperators static private
Definition at line 324 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 324 of file G4VBiasingOperator.hh
Referenced by G4VBiasingOperator(), and GetBiasingOperators().
const G4VBiasingOperation* G4VBiasingOperator::fPreviousAppliedFinalStateBiasingOperation private
Definition at line 345 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 345 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), and ReportOperationApplied().
const G4VBiasingOperation* G4VBiasingOperator::fPreviousAppliedNonPhysicsBiasingOperation private
Definition at line 346 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 346 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), GetPreviousNonPhysicsAppliedOperation(), and ReportOperationApplied().
const G4VBiasingOperation* G4VBiasingOperator::fPreviousAppliedOccurenceBiasingOperation private
Definition at line 344 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 344 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), and ReportOperationApplied().
G4BiasingAppliedCase G4VBiasingOperator::fPreviousBiasingAppliedCase private
Definition at line 347 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 347 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing(), GetPreviousBiasingAppliedCase(), and ReportOperationApplied().
const G4VBiasingOperation* G4VBiasingOperator::fPreviousProposedFinalStateBiasingOperation private
Definition at line 342 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 342 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing().
const G4VBiasingOperation* G4VBiasingOperator::fPreviousProposedNonPhysicsBiasingOperation private
Definition at line 343 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 343 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing().
const G4VBiasingOperation* G4VBiasingOperator::fPreviousProposedOccurenceBiasingOperation private
Definition at line 341 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 341 of file G4VBiasingOperator.hh
Referenced by ExitingBiasing().
std::vector< const G4LogicalVolume* > G4VBiasingOperator::fRootVolumes private
Definition at line 332 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 332 of file G4VBiasingOperator.hh
G4Cache< G4BiasingOperatorStateNotifier * > G4VBiasingOperator::fStateNotifier static private
Definition at line 328 of file G4VBiasingOperator.hh.
View newest version in sPHENIX GitHub at line 328 of file G4VBiasingOperator.hh
Referenced by G4VBiasingOperator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4VBiasingOperator.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/management/src/G4VBiasingOperator.cc