ECCE @ EIC Software: G4THitsCollection< T > Class Template Reference
G4THitsCollection< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4THitsCollection.hh>
Public Member Functions
G4THitsCollection ()
G4THitsCollection (G4String detName, G4String colNam)
virtual ~G4THitsCollection ()
G4bool operator== (const G4THitsCollection< T > &right) const
void * operator new (size_t)
void operator delete (void *anHC)
virtual void DrawAllHits ()
virtual void PrintAllHits ()
T * operator[] (size_t i) const
std::vector< T * > * GetVector () const
G4int insert (T *aHit)
G4int entries () const
virtual G4VHit * GetHit (size_t i) const
virtual size_t GetSize () const
G4THitsCollection ()
G4THitsCollection (G4String detName, G4String colNam)
virtual ~G4THitsCollection ()
G4bool operator== (const G4THitsCollection< T > &right) const
void * operator new (size_t)
void operator delete (void *anHC)
virtual void DrawAllHits ()
virtual void PrintAllHits ()
T * operator[] (size_t i) const
std::vector< T * > * GetVector () const
G4int insert (T *aHit)
G4int entries () const
virtual G4VHit * GetHit (size_t i) const
virtual size_t GetSize () const
G4THitsCollection ()
G4THitsCollection (G4String detName, G4String colNam)
virtual ~G4THitsCollection ()
G4bool operator== (const G4THitsCollection< T > &right) const
void * operator new (size_t)
void operator delete (void *anHC)
virtual void DrawAllHits ()
virtual void PrintAllHits ()
T * operator[] (size_t i) const
std::vector< T * > * GetVector () const
size_t insert (T *aHit)
size_t entries () const
virtual G4VHit * GetHit (size_t i) const
virtual size_t GetSize () const
Public Member Functions inherited from G4HitsCollection
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
Public Member Functions inherited from G4VHitsCollection
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
G4String GetName ()
G4String GetSDname ()
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
G4String GetName ()
G4String GetSDname ()
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
const G4String & GetName () const
const G4String & GetSDname () const
void SetColID (G4int i)
G4int GetColID () const
Additional Inherited Members
Protected Attributes inherited from G4HitsCollection
void * theCollection
Detailed Description
template<class T>
class G4THitsCollection< T >
Definition at line 78 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 78 of file G4THitsCollection.hh
Constructor & Destructor Documentation
template<class T > G4THitsCollection< T >::G4THitsCollection ()
Definition at line 144 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 144 of file G4THitsCollection.hh
template<class T > G4THitsCollection< T >::G4THitsCollection (G4String detName, G4String colNam)
Definition at line 151 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 151 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T > G4THitsCollection< T >::~G4THitsCollection () virtual
Definition at line 159 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 159 of file G4THitsCollection.hh
template<class T> G4THitsCollection< T >::G4THitsCollection ()
template<class T> G4THitsCollection< T >::G4THitsCollection (G4String detName, G4String colNam)
template<class T> virtual G4THitsCollection< T >::~G4THitsCollection () virtual
template<class T> G4THitsCollection< T >::G4THitsCollection ()
template<class T> G4THitsCollection< T >::G4THitsCollection (G4String detName, G4String colNam)
template<class T> virtual G4THitsCollection< T >::~G4THitsCollection () virtual
Member Function Documentation
template<class T> virtual void G4THitsCollection< T >::DrawAllHits () virtual
Reimplemented from G4VHitsCollection.
template<class T > void G4THitsCollection< T >::DrawAllHits () virtual
Reimplemented from G4VHitsCollection.
Definition at line 173 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 173 of file G4THitsCollection.hh
References n.
Referenced by LXeEventAction::EndOfEventAction(), and DMXEventAction::EndOfEventAction().
template<class T> virtual void G4THitsCollection< T >::DrawAllHits () virtual
Reimplemented from G4VHitsCollection.
template<class T> size_t G4THitsCollection< T >::entries () const inline
Definition at line 106 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 106 of file G4THitsCollection.hh
References anHCAllocator_G4MT_TLS_(), and G4HitsCollection::theCollection.
template<class T> G4int G4THitsCollection< T >::entries () const inline
Definition at line 113 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 113 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
Referenced by GammaRayTelDigitizer::Digitize(), eRositaTrackerSD::EndOfEvent(), ExTGTrackerSD::EndOfEvent(), SensitiveDetector::EndOfEvent(), ExN02TrackerSD::EndOfEvent(), ExP01TrackerSD::EndOfEvent(), B2TrackerSD::EndOfEvent(), B4cCalorimeterSD::EndOfEvent(), DMXScintSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), TrackerSD::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), RE05EventAction::EndOfEventAction(), G4HumanPhantomEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), GammaRayTelEventAction::EndOfEventAction(), UltraEventAction::EndOfEventAction(), DMXEventAction::EndOfEventAction(), XrayFluoEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), CCaloSD::hitExists(), RE05StackingAction::InsideRoI(), ExN04StackingAction::InsideRoI(), RE01StackingAction::NewStage(), ExN04StackingAction::NewStage(), RE05StackingAction::NewStage(), ExN04MuonSD::ProcessHits(), RE05MuonSD::ProcessHits(), B5HodoscopeSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), and LXePMTSD::ProcessHits_constStep().
template<class T> G4int G4THitsCollection< T >::entries () const inline
Definition at line 146 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 146 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> virtual G4VHit* G4THitsCollection< T >::GetHit (size_t i) const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 115 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 115 of file G4THitsCollection.hh
References anHCAllocator_G4MT_TLS_(), and G4HitsCollection::theCollection.
template<class T> virtual G4VHit* G4THitsCollection< T >::GetHit (size_t i) const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 122 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 122 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
Referenced by XAluminumElectrodeSensitivity::EndOfEvent().
template<class T> virtual G4VHit* G4THitsCollection< T >::GetHit (size_t i) const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 155 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 155 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> virtual size_t G4THitsCollection< T >::GetSize () const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 120 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 120 of file G4THitsCollection.hh
References anHCAllocator_G4MT_TLS_(), and G4HitsCollection::theCollection.
template<class T> virtual size_t G4THitsCollection< T >::GetSize () const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 124 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 124 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
Referenced by XAluminumElectrodeSensitivity::EndOfEvent().
template<class T> virtual size_t G4THitsCollection< T >::GetSize () const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 157 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 157 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> std::vector<T*>* G4THitsCollection< T >::GetVector () const inline
Definition at line 92 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 92 of file G4THitsCollection.hh
References anHCAllocator_G4MT_TLS_(), and G4HitsCollection::theCollection.
template<class T> std::vector<T*>* G4THitsCollection< T >::GetVector () const inline
Definition at line 101 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 101 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> std::vector<T*>* G4THitsCollection< T >::GetVector () const inline
Definition at line 134 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 134 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> size_t G4THitsCollection< T >::insert (T * aHit) inline
Definition at line 97 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 97 of file G4THitsCollection.hh
References anHCAllocator_G4MT_TLS_(), and G4HitsCollection::theCollection.
template<class T> G4int G4THitsCollection< T >::insert (T * aHit) inline
Definition at line 104 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 104 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
Referenced by RMC01SD::EndOfEvent(), B5EmCalorimeterSD::Initialize(), B5HadCalorimeterSD::Initialize(), B4cCalorimeterSD::Initialize(), ExN04CalorimeterSD::ProcessHits(), G4HumanPhantomSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), ExN04MuonSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), RE05TrackerSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE05MuonSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), B5HodoscopeSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), LXeScintSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), B5DriftChamberSD::ProcessHits(), RE01TrackerSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), ExGflash2SensitiveDetector::ProcessHits(), ExN02TrackerSD::ProcessHits(), ExGflash1SensitiveDetector::ProcessHits(), F02CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), DMXScintSD::ProcessHits(), UltraPMTSD::ProcessHits(), TrackerSD::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), RMC01SD::ProcessHits(), XrayFluoSD::ProcessHits(), LXePMTSD::ProcessHits_constStep(), and CCaloSD::StoreHit().
template<class T> G4int G4THitsCollection< T >::insert (T * aHit) inline
Definition at line 137 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 137 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> void G4THitsCollection< T >::operator delete (void * anHC) inline
template<class T > void G4THitsCollection< T >::operator delete (void * anHC) inline
Definition at line 139 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 139 of file G4THitsCollection.hh
References anHCAllocator.
template<class T> void G4THitsCollection< T >::operator delete (void * anHC) inline
template<class T> void* G4THitsCollection< T >::operator new (size_t) inline
template<class T > void * G4THitsCollection< T >::operator new (size_t) inline
Definition at line 132 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 132 of file G4THitsCollection.hh
References anHCAllocator.
template<class T> void* G4THitsCollection< T >::operator new (size_t) inline
template<class T> G4bool G4THitsCollection< T >::operator== (const G4THitsCollection< T > & right) const
template<class T > G4bool G4THitsCollection< T >::operator== (const G4THitsCollection< T > & right) const
Definition at line 170 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 170 of file G4THitsCollection.hh
References G4VHitsCollection::collectionName.
template<class T> G4bool G4THitsCollection< T >::operator== (const G4THitsCollection< T > & right) const
template<class T> T* G4THitsCollection< T >::operator[] (size_t i) const inline
Definition at line 86 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 86 of file G4THitsCollection.hh
References anHCAllocator_G4MT_TLS_(), and G4HitsCollection::theCollection.
template<class T> T* G4THitsCollection< T >::operator[] (size_t i) const inline
Definition at line 98 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 98 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> T* G4THitsCollection< T >::operator[] (size_t i) const inline
Definition at line 131 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 131 of file G4THitsCollection.hh
References G4HitsCollection::theCollection.
template<class T> virtual void G4THitsCollection< T >::PrintAllHits () virtual
Reimplemented from G4VHitsCollection.
template<class T > void G4THitsCollection< T >::PrintAllHits () virtual
Reimplemented from G4VHitsCollection.
Definition at line 182 of file G4THitsCollection.hh.
View newest version in sPHENIX GitHub at line 182 of file G4THitsCollection.hh
References n.
Referenced by DMXScintSD::EndOfEvent(), DMXPmtSD::EndOfEvent(), and CCaloSD::PrintAll().
template<class T> virtual void G4THitsCollection< T >::PrintAllHits () virtual
Reimplemented from G4VHitsCollection.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4THitsCollection.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/G4THitsCollection.hh
geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4THitsCollection.hh