ECCE @ EIC Software: G4LDMBremsstrahlung Class Reference
G4LDMBremsstrahlung Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/G4LDMBremsstrahlung.hh>
Public Member Functions
G4LDMBremsstrahlung (const G4String &processName="ldmBrems")
virtual ~G4LDMBremsstrahlung ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *, G4double) override
Public Member Functions inherited from G4MuBremsstrahlung
G4MuBremsstrahlung (const G4String &processName="muBrems")
~G4MuBremsstrahlung ()=default
virtual void PrintInfo () override
void SetLowestKineticEnergy (G4double e)
virtual void ProcessDescription (std::ostream &) const override
Public Member Functions inherited from G4VEnergyLossProcess
G4VEnergyLossProcess (const G4String &name="EnergyLoss", G4ProcessType type=fElectromagnetic)
virtual ~G4VEnergyLossProcess ()
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
G4PhysicsTable * BuildDEDXTable (G4EmTableType tType=fRestricted)
G4PhysicsTable * BuildLambdaTable (G4EmTableType tType=fRestricted)
virtual void StartTracking (G4Track *) override
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4double SampleSubCutSecondaries (std::vector< G4Track * > &, const G4Step &, G4VEmModel *model, G4int matIdx)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
G4double GetDEDXDispersion (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double length)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double MeanFreePath (const G4Track &track)
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t &idx) const
void AddEmModel (G4int, G4VEmModel *, G4VEmFluctuationModel *fluc=0, const G4Region *region=nullptr)
void UpdateEmModel (const G4String &, G4double, G4double)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
G4int NumberOfModels () const
void SetFluctModel (G4VEmFluctuationModel *)
G4VEmFluctuationModel * FluctModel ()
void SetBaseParticle (const G4ParticleDefinition *p)
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * BaseParticle () const
const G4ParticleDefinition * SecondaryParticle () const
void ActivateSubCutoff (G4bool val, const G4Region *region=nullptr)
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
void ActivateForcedInteraction (G4double length, const G4String &region, G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void AddCollaborativeProcess (G4VEnergyLossProcess *)
void SetLossFluctuations (G4bool val)
void SetIntegral (G4bool val)
G4bool IsIntegral () const
void SetIonisation (G4bool val)
G4bool IsIonisationProcess () const
void SetLinearLossLimit (G4double val)
void SetStepFunction (G4double v1, G4double v2, G4bool lock=true)
void SetLowestEnergyLimit (G4double)
G4int NumberOfSubCutoffRegions () const
void SetDEDXTable (G4PhysicsTable *p, G4EmTableType tType)
void SetCSDARangeTable (G4PhysicsTable *pRange)
void SetRangeTableForLoss (G4PhysicsTable *p)
void SetSecondaryRangeTable (G4PhysicsTable *p)
void SetInverseRangeTable (G4PhysicsTable *p)
void SetLambdaTable (G4PhysicsTable *p)
void SetSubLambdaTable (G4PhysicsTable *p)
void SetDEDXBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
G4double MinKinEnergy () const
void SetMaxKinEnergy (G4double e)
G4double MaxKinEnergy () const
G4double CrossSectionBiasingFactor () const
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetKineticEnergy (G4double range, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4bool TablesAreBuilt () const
G4PhysicsTable * DEDXTable () const
G4PhysicsTable * DEDXTableForSubsec () const
G4PhysicsTable * DEDXunRestrictedTable () const
G4PhysicsTable * IonisationTable () const
G4PhysicsTable * IonisationTableForSubsec () const
G4PhysicsTable * CSDARangeTable () const
G4PhysicsTable * SecondaryRangeTable () const
G4PhysicsTable * RangeTableForLoss () const
G4PhysicsTable * InverseRangeTable () const
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * SubLambdaTable () const
const G4Element * GetCurrentElement () const
void SetDynamicMassCharge (G4double massratio, G4double charge2ratio)
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void InitialiseEnergyLossProcess (const G4ParticleDefinition *, const G4ParticleDefinition *) override
Private Member Functions
G4LDMBremsstrahlung & operator= (const G4LDMBremsstrahlung &right)=delete
G4LDMBremsstrahlung (const G4LDMBremsstrahlung &)=delete
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4MuBremsstrahlung
G4double lowestKinEnergy
G4bool isInitialised
Detailed Description
Definition at line 47 of file G4LDMBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 47 of file G4LDMBremsstrahlung.hh
Constructor & Destructor Documentation
G4LDMBremsstrahlung::G4LDMBremsstrahlung (const G4String & processName = "ldmBrems") explicit
Definition at line 56 of file G4LDMBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 56 of file G4LDMBremsstrahlung.cc
G4LDMBremsstrahlung::~G4LDMBremsstrahlung () virtual
Definition at line 63 of file G4LDMBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 63 of file G4LDMBremsstrahlung.cc
G4LDMBremsstrahlung::G4LDMBremsstrahlung (const G4LDMBremsstrahlung &) private delete
Member Function Documentation
void G4LDMBremsstrahlung::InitialiseEnergyLossProcess (const G4ParticleDefinition * , const G4ParticleDefinition *) override protected virtual
Reimplemented from G4MuBremsstrahlung.
Definition at line 83 of file G4LDMBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 83 of file G4LDMBremsstrahlung.cc
References G4VEnergyLossProcess::AddEmModel(), G4VEnergyLossProcess::EmModel(), Acts::UnitConstants::fm, G4EmParameters::Instance(), G4MuBremsstrahlung::isInitialised, G4EmParameters::MaxKinEnergy(), G4EmParameters::MinKinEnergy(), G4VEnergyLossProcess::SetEmModel(), G4VEmModel::SetHighEnergyLimit(), and G4VEmModel::SetLowEnergyLimit().
G4bool G4LDMBremsstrahlung::IsApplicable (const G4ParticleDefinition & p) override virtual
Reimplemented from G4MuBremsstrahlung.
Definition at line 68 of file G4LDMBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 68 of file G4LDMBremsstrahlung.cc
References G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), and MeV.
G4double G4LDMBremsstrahlung::MinPrimaryEnergy (const G4ParticleDefinition * , const G4Material * , G4double) override virtual
Reimplemented from G4MuBremsstrahlung.
Definition at line 75 of file G4LDMBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 75 of file G4LDMBremsstrahlung.cc
References G4VEnergyLossProcess::MinKinEnergy().
G4LDMBremsstrahlung& G4LDMBremsstrahlung::operator= (const G4LDMBremsstrahlung & right) private delete
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/G4LDMBremsstrahlung.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/src/G4LDMBremsstrahlung.cc