ECCE @ EIC Software: G4AssemblyStore Class Reference
G4AssemblyStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4AssemblyStore.hh>
Public Member Functions
G4AssemblyVolume * GetAssembly (unsigned int id, G4bool verbose=true) const
Static Public Member Functions
static void Register (G4AssemblyVolume *pAssembly)
static void DeRegister (G4AssemblyVolume *pAssembly)
static G4AssemblyStore * GetInstance ()
static void SetNotifier (G4VStoreNotifier *pNotifier)
static void Clean ()
Protected Member Functions
G4AssemblyStore ()
virtual ~G4AssemblyStore ()
Static Private Attributes
static G4AssemblyStore * fgInstance = nullptr
static G4ThreadLocal
G4VStoreNotifier * fgNotifier = nullptr
static G4ThreadLocal G4bool locked = false
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 59 of file G4AssemblyStore.hh.
View newest version in sPHENIX GitHub at line 59 of file G4AssemblyStore.hh
Constructor & Destructor Documentation
G4AssemblyStore::G4AssemblyStore () protected
Definition at line 53 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 53 of file G4AssemblyStore.cc
G4AssemblyStore::~G4AssemblyStore () protected virtual
Definition at line 63 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 63 of file G4AssemblyStore.cc
References Clean().
Member Function Documentation
void G4AssemblyStore::Clean () static
Definition at line 72 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 72 of file G4AssemblyStore.cc
References fgNotifier, G4cout, G4endl, GetInstance(), G4GeometryManager::IsGeometryClosed(), locked, G4VNotifier::NotifyDeRegistration(), and pos().
Referenced by G4RunManager::ReinitializeGeometry(), and ~G4AssemblyStore().
void G4AssemblyStore::DeRegister (G4AssemblyVolume * pAssembly) static
Definition at line 137 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 137 of file G4AssemblyStore.cc
References fgNotifier, GetInstance(), locked, and G4VNotifier::NotifyDeRegistration().
Referenced by G4AssemblyVolume::~G4AssemblyVolume().
G4AssemblyVolume * G4AssemblyStore::GetAssembly (unsigned int id, G4bool verbose = true) const
Definition at line 172 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 172 of file G4AssemblyStore.cc
References G4endl, G4Exception(), GetInstance(), JustWarning, and message().
Referenced by G4GDMLWriteStructure::AssemblyWrite(), G4AssemblyVolume::G4AssemblyVolume(), and G4GDMLWriteStructure::TraverseVolumeTree().
G4AssemblyStore * G4AssemblyStore::GetInstance (void) static
Definition at line 157 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 157 of file G4AssemblyStore.cc
References fgInstance.
Referenced by G4GDMLWriteStructure::AssemblyWrite(), Clean(), DeRegister(), G4AssemblyVolume::G4AssemblyVolume(), GetAssembly(), Register(), G4RunManager::ReinitializeGeometry(), SetNotifier(), G4GDMLWriteStructure::StructureWrite(), G4GDMLWriteStructure::TraverseVolumeTree(), and G4AssemblyVolume::~G4AssemblyVolume().
void G4AssemblyStore::Register (G4AssemblyVolume * pAssembly) static
Definition at line 127 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 127 of file G4AssemblyStore.cc
References fgNotifier, GetInstance(), and G4VNotifier::NotifyRegistration().
Referenced by G4AssemblyVolume::G4AssemblyVolume().
void G4AssemblyStore::SetNotifier (G4VStoreNotifier * pNotifier) static
Definition at line 117 of file G4AssemblyStore.cc.
View newest version in sPHENIX GitHub at line 117 of file G4AssemblyStore.cc
References fgNotifier, and GetInstance().
Member Data Documentation
G4AssemblyStore * G4AssemblyStore::fgInstance = nullptr static private
Definition at line 86 of file G4AssemblyStore.hh.
View newest version in sPHENIX GitHub at line 86 of file G4AssemblyStore.hh
Referenced by GetInstance().
G4ThreadLocal G4VStoreNotifier * G4AssemblyStore::fgNotifier = nullptr static private
Definition at line 87 of file G4AssemblyStore.hh.
View newest version in sPHENIX GitHub at line 87 of file G4AssemblyStore.hh
Referenced by Clean(), DeRegister(), Register(), and SetNotifier().
G4ThreadLocal G4bool G4AssemblyStore::locked = false static private
Definition at line 88 of file G4AssemblyStore.hh.
View newest version in sPHENIX GitHub at line 88 of file G4AssemblyStore.hh
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4AssemblyStore.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4AssemblyStore.cc