ECCE @ EIC Software: WLSUserTrackInformation Class Reference
WLSUserTrackInformation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSUserTrackInformation.hh>
Public Member Functions
WLSUserTrackInformation ()
virtual ~WLSUserTrackInformation ()
const G4ThreeVector & GetExitPosition () const
void SetExitPosition (const G4ThreeVector &pos)
G4bool AddStatusFlag (TrackStatus s)
G4bool IsStatus (TrackStatus s)
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
virtual void Print () const
const G4String & GetType () const
Private Attributes
G4int fStatus
G4ThreeVector fExitPosition
Additional Inherited Members
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Definition at line 61 of file WLSUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 61 of file WLSUserTrackInformation.hh
Constructor & Destructor Documentation
WLSUserTrackInformation::WLSUserTrackInformation ()
Definition at line 38 of file WLSUserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 38 of file WLSUserTrackInformation.cc
References fExitPosition, fStatus, and PHG4CellDefs::undefined.
WLSUserTrackInformation::~WLSUserTrackInformation () virtual
Definition at line 46 of file WLSUserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 46 of file WLSUserTrackInformation.cc
Member Function Documentation
G4bool WLSUserTrackInformation::AddStatusFlag (TrackStatus s)
Definition at line 50 of file WLSUserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 50 of file WLSUserTrackInformation.cc
References EscapedFromReadOut, EscapedFromSide, fStatus, InsideOfFiber, left, murderee, OutsideOfFiber, ReflectedAtMirror, ReflectedAtReadOut, right, and PHG4CellDefs::undefined.
Referenced by WLSTrackingAction::PreUserTrackingAction(), and WLSSteppingAction::UserSteppingAction().
const G4ThreeVector& WLSUserTrackInformation::GetExitPosition () const inline
Definition at line 69 of file WLSUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 69 of file WLSUserTrackInformation.hh
References fExitPosition.
G4bool WLSUserTrackInformation::IsStatus (TrackStatus s) inline
Definition at line 78 of file WLSUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 78 of file WLSUserTrackInformation.hh
References defined, fStatus, and PHG4CellDefs::undefined.
Referenced by WLSSteppingAction::UserSteppingAction().
void WLSUserTrackInformation::SetExitPosition (const G4ThreeVector & pos) inline
Definition at line 70 of file WLSUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 70 of file WLSUserTrackInformation.hh
References fExitPosition, and pos().
Referenced by WLSSteppingAction::UserSteppingAction().
Member Data Documentation
G4ThreeVector WLSUserTrackInformation::fExitPosition private
Definition at line 84 of file WLSUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 84 of file WLSUserTrackInformation.hh
Referenced by GetExitPosition(), SetExitPosition(), and WLSUserTrackInformation().
G4int WLSUserTrackInformation::fStatus private
Definition at line 83 of file WLSUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 83 of file WLSUserTrackInformation.hh
Referenced by AddStatusFlag(), IsStatus(), and WLSUserTrackInformation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSUserTrackInformation.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSUserTrackInformation.cc