ECCE @ EIC Software: G4INCL::NNOmegaToMultiPionsChannel Class Reference
G4INCL::NNOmegaToMultiPionsChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNNOmegaToMultiPionsChannel.hh>
Public Member Functions
NNOmegaToMultiPionsChannel (const G4int, Particle *, Particle *)
virtual ~NNOmegaToMultiPionsChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
void inter2Part (const G4double p)
void pn_ppPim ()
void pn_pnPi0 ()
void pn_nnPip ()
void pp_nnPipPip ()
void nn_ppPimPim ()
void pn_pnPipPim ()
void pn_pnPi0Pi0 ()
void pp_ppPipPim ()
void nn_nnPipPim ()
void pp_ppPi0Pi0 ()
void nn_nnPi0Pi0 ()
void pp_pnPipPi0 ()
void pn_ppPimPi0 ()
void pn_nnPipPi0 ()
void nn_pnPimPi0 ()
void pp_pnPipPi0Pi0 ()
void nn_pnPimPi0Pi0 ()
void pn_nnPipPi0Pi0 ()
void pp_ppPipPimPi0 ()
void nn_nnPipPimPi0 ()
void pp_ppPi0Pi0Pi0 ()
void nn_nnPi0Pi0Pi0 ()
void pp_pnPipPipPim ()
void pp_nnPipPipPi0 ()
void pn_ppPimPi0Pi0 ()
void pn_ppPimPimPip ()
void pn_pnPi0PipPim ()
void pn_pnPi0Pi0Pi0 ()
void pn_nnPipPipPim ()
void nn_pnPipPimPim ()
void nn_ppPimPimPi0 ()
void pp_nnPipPipPi0Pi0 ()
void pp_nnPipPipPipPim ()
void nn_ppPi0Pi0PimPim ()
void nn_ppPipPimPimPim ()
void pp_ppPi0Pi0Pi0Pi0 ()
void nn_nnPi0Pi0Pi0Pi0 ()
void pn_pnPi0Pi0Pi0Pi0 ()
void pp_ppPipPi0Pi0Pim ()
void nn_nnPipPi0Pi0Pim ()
void pn_pnPipPi0Pi0Pim ()
void pp_ppPipPipPimPim ()
void nn_nnPipPipPimPim ()
void pn_pnPipPipPimPim ()
void pp_pnPipPi0Pi0Pi0 ()
void pn_nnPipPi0Pi0Pi0 ()
void pp_nnPipPi0Pi0Pi0 ()
void pp_pnPipPipPi0Pim ()
void pn_nnPipPipPi0Pim ()
void pp_nnPipPipPi0Pim ()
void nn_pnPi0Pi0Pi0Pim ()
void pn_ppPi0Pi0Pi0Pim ()
void nn_pnPipPi0PimPim ()
void pn_ppPipPi0PimPim ()
void isospinRepartition ()
INCL_DECLARE_ALLOCATION_POOL (NNOmegaToMultiPionsChannel)
Private Attributes
G4int npion
G4int iso1
G4int iso2
G4int isosp [4]
Particle * particle1
Particle * particle2
Static Private Attributes
static const G4double angularSlope = 6.
Detailed Description
Definition at line 47 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNNOmegaToMultiPionsChannel.hh
Constructor & Destructor Documentation
G4INCL::NNOmegaToMultiPionsChannel::NNOmegaToMultiPionsChannel (const G4int npi, Particle * p1, Particle * p2)
Definition at line 51 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
G4INCL::NNOmegaToMultiPionsChannel::~NNOmegaToMultiPionsChannel () virtual
Definition at line 61 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLNNOmegaToMultiPionsChannel.cc
Member Function Documentation
void G4INCL::NNOmegaToMultiPionsChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 65 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLNNOmegaToMultiPionsChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), angularSlope, G4INCL::PhaseSpaceGenerator::generateBiased(), G4INCL::ParticleTable::getIsospin(), G4INCL::ParticleTable::getNucleonType(), G4INCL::ParticleTable::getPionType(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), iso1, iso2, isosp, isospinRepartition(), npion, G4INCL::Omega, particle1, particle2, G4InuclParticleNames::pion(), G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::KinematicsUtils::totalEnergyInCM(), and zero.
G4INCL::NNOmegaToMultiPionsChannel::INCL_DECLARE_ALLOCATION_POOL (NNOmegaToMultiPionsChannel) private
void G4INCL::NNOmegaToMultiPionsChannel::inter2Part (const G4double p) private
Definition at line 560 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 560 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, G4INCL::Random::shoot(), and boost::swap().
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::isospinRepartition () private
Definition at line 103 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 103 of file G4INCLNNOmegaToMultiPionsChannel.cc
References G4INCL::Random::getAdapter(), inter2Part(), iso1, iso2, isosp, nn_nnPi0Pi0(), nn_nnPi0Pi0Pi0(), nn_nnPi0Pi0Pi0Pi0(), nn_nnPipPi0Pi0Pim(), nn_nnPipPim(), nn_nnPipPimPi0(), nn_nnPipPipPimPim(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), npion, pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_pnPi0(), pn_pnPi0Pi0(), pn_pnPi0Pi0Pi0(), pn_pnPi0Pi0Pi0Pi0(), pn_pnPi0PipPim(), pn_pnPipPi0Pi0Pim(), pn_pnPipPim(), pn_pnPipPipPimPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), G4InuclParticleNames::pp, pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), pp_pnPipPipPim(), pp_ppPi0Pi0(), pp_ppPi0Pi0Pi0(), pp_ppPi0Pi0Pi0Pi0(), pp_ppPipPi0Pi0Pim(), pp_ppPipPim(), pp_ppPipPimPi0(), pp_ppPipPipPimPim(), and G4INCL::Random::shoot().
Referenced by fillFinalState().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPi0Pi0 () private
Definition at line 265 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 265 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPi0Pi0Pi0 () private
Definition at line 329 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 329 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPi0Pi0Pi0Pi0 () private
Definition at line 431 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 431 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPipPi0Pi0Pim () private
Definition at line 449 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 449 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPipPim () private
Definition at line 257 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 257 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPipPimPi0 () private
Definition at line 319 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 319 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_nnPipPipPimPim () private
Definition at line 467 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 467 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_pnPi0Pi0Pi0Pim () private
Definition at line 527 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 527 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_pnPimPi0 () private
Definition at line 287 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 287 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_pnPimPi0Pi0 () private
Definition at line 300 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 300 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_pnPipPi0PimPim () private
Definition at line 543 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 543 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_pnPipPimPim () private
Definition at line 379 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 379 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_ppPi0Pi0PimPim () private
Definition at line 409 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 409 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_ppPimPim () private
Definition at line 239 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 239 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_ppPimPimPi0 () private
Definition at line 386 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 386 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::nn_ppPipPimPimPim () private
Definition at line 417 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 417 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_nnPip () private
Definition at line 228 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 228 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_nnPipPi0 () private
Definition at line 281 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 281 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_nnPipPi0Pi0 () private
Definition at line 307 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 307 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_nnPipPi0Pi0Pi0 () private
Definition at line 487 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 487 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_nnPipPipPi0Pim () private
Definition at line 511 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 511 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_nnPipPipPim () private
Definition at line 372 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 372 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPi0 () private
Definition at line 225 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 225 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPi0Pi0 () private
Definition at line 249 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 249 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPi0Pi0Pi0 () private
Definition at line 367 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 367 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPi0Pi0Pi0Pi0 () private
Definition at line 437 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 437 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPi0PipPim () private
Definition at line 362 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 362 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPipPi0Pi0Pim () private
Definition at line 455 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 455 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPipPim () private
Definition at line 245 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 245 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_pnPipPipPimPim () private
Definition at line 473 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 473 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_ppPi0Pi0Pi0Pim () private
Definition at line 535 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 535 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_ppPim () private
Definition at line 220 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 220 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_ppPimPi0 () private
Definition at line 275 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 275 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_ppPimPi0Pi0 () private
Definition at line 348 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 348 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_ppPimPimPip () private
Definition at line 355 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 355 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pn_ppPipPi0PimPim () private
Definition at line 551 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 551 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_nnPipPi0Pi0Pi0 () private
Definition at line 495 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 495 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
void G4INCL::NNOmegaToMultiPionsChannel::pp_nnPipPip () private
Definition at line 233 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 233 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_nnPipPipPi0 () private
Definition at line 341 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 341 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_nnPipPipPi0Pi0 () private
Definition at line 393 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 393 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_nnPipPipPi0Pim () private
Definition at line 519 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 519 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
void G4INCL::NNOmegaToMultiPionsChannel::pp_nnPipPipPipPim () private
Definition at line 401 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 401 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_pnPipPi0 () private
Definition at line 269 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 269 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_pnPipPi0Pi0 () private
Definition at line 293 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 293 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_pnPipPi0Pi0Pi0 () private
Definition at line 479 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 479 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_pnPipPipPi0Pim () private
Definition at line 503 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 503 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_pnPipPipPim () private
Definition at line 334 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 334 of file G4INCLNNOmegaToMultiPionsChannel.cc
References iso1, iso2, and isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPi0Pi0 () private
Definition at line 261 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 261 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPi0Pi0Pi0 () private
Definition at line 324 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 324 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPi0Pi0Pi0Pi0 () private
Definition at line 425 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 425 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPipPi0Pi0Pim () private
Definition at line 443 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 443 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPipPim () private
Definition at line 253 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 253 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPipPimPi0 () private
Definition at line 314 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 314 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
void G4INCL::NNOmegaToMultiPionsChannel::pp_ppPipPipPimPim () private
Definition at line 461 of file G4INCLNNOmegaToMultiPionsChannel.cc.
View newest version in sPHENIX GitHub at line 461 of file G4INCLNNOmegaToMultiPionsChannel.cc
References isosp.
Referenced by isospinRepartition().
Member Data Documentation
const G4double G4INCL::NNOmegaToMultiPionsChannel::angularSlope = 6. static private
Definition at line 61 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState().
G4int G4INCL::NNOmegaToMultiPionsChannel::iso1 private
Definition at line 56 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState(), inter2Part(), isospinRepartition(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), pp_nnPipPi0Pi0Pi0(), pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPi0Pim(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), and pp_pnPipPipPim().
G4int G4INCL::NNOmegaToMultiPionsChannel::iso2 private
Definition at line 57 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState(), inter2Part(), isospinRepartition(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), pp_nnPipPi0Pi0Pi0(), pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPi0Pim(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), and pp_pnPipPipPim().
G4int G4INCL::NNOmegaToMultiPionsChannel::isosp[4] private
Definition at line 58 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState(), isospinRepartition(), nn_nnPi0Pi0(), nn_nnPi0Pi0Pi0(), nn_nnPi0Pi0Pi0Pi0(), nn_nnPipPi0Pi0Pim(), nn_nnPipPim(), nn_nnPipPimPi0(), nn_nnPipPipPimPim(), nn_pnPi0Pi0Pi0Pim(), nn_pnPimPi0(), nn_pnPimPi0Pi0(), nn_pnPipPi0PimPim(), nn_pnPipPimPim(), nn_ppPi0Pi0PimPim(), nn_ppPimPim(), nn_ppPimPimPi0(), nn_ppPipPimPimPim(), NNOmegaToMultiPionsChannel(), pn_nnPip(), pn_nnPipPi0(), pn_nnPipPi0Pi0(), pn_nnPipPi0Pi0Pi0(), pn_nnPipPipPi0Pim(), pn_nnPipPipPim(), pn_pnPi0(), pn_pnPi0Pi0(), pn_pnPi0Pi0Pi0(), pn_pnPi0Pi0Pi0Pi0(), pn_pnPi0PipPim(), pn_pnPipPi0Pi0Pim(), pn_pnPipPim(), pn_pnPipPipPimPim(), pn_ppPi0Pi0Pi0Pim(), pn_ppPim(), pn_ppPimPi0(), pn_ppPimPi0Pi0(), pn_ppPimPimPip(), pn_ppPipPi0PimPim(), pp_nnPipPi0Pi0Pi0(), pp_nnPipPip(), pp_nnPipPipPi0(), pp_nnPipPipPi0Pi0(), pp_nnPipPipPi0Pim(), pp_nnPipPipPipPim(), pp_pnPipPi0(), pp_pnPipPi0Pi0(), pp_pnPipPi0Pi0Pi0(), pp_pnPipPipPi0Pim(), pp_pnPipPipPim(), pp_ppPi0Pi0(), pp_ppPi0Pi0Pi0(), pp_ppPi0Pi0Pi0Pi0(), pp_ppPipPi0Pi0Pim(), pp_ppPipPim(), pp_ppPipPimPi0(), and pp_ppPipPipPimPim().
G4int G4INCL::NNOmegaToMultiPionsChannel::npion private
Definition at line 55 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState(), and isospinRepartition().
Particle* G4INCL::NNOmegaToMultiPionsChannel::particle1 private
Definition at line 59 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NNOmegaToMultiPionsChannel::particle2 private
Definition at line 59 of file G4INCLNNOmegaToMultiPionsChannel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLNNOmegaToMultiPionsChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNNOmegaToMultiPionsChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNNOmegaToMultiPionsChannel.cc