ECCE @ EIC Software: G4DNASmoluchowskiDiffusion Class Reference
G4DNASmoluchowskiDiffusion Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNASmoluchowskiDiffusion.hh>
Classes
struct BoundingBox
Public Member Functions
G4DNASmoluchowskiDiffusion (double epsilon=1e-5)
virtual ~G4DNASmoluchowskiDiffusion ()
double GetRandomDistance (double _time, double D)
double GetRandomTime (double distance, double D)
double EstimateCrossingTime (double proba, double distance, double D)
void PrepareReverseTable (double xmin, double xmax)
double GetInverseProbability (double proba)
double PlotInverse (double *x, double *)
double Plot (double *x, double *)
void InitialiseInverseProbability (double xmax=3e28)
Static Public Member Functions
static double ComputeS (double r, double D, double t)
static double ComputeDistance (double sTransform, double D, double t)
static double ComputeTime (double sTransform, double D, double r)
static double GetDifferential (double sTransform)
static double GetDensityProbability (double r, double _time, double D)
static double GetCumulativeProbability (double sTransform)
Public Attributes
std::vector< double > fInverse
int fNbins
double fEpsilon
Detailed Description
Definition at line 70 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 70 of file G4DNASmoluchowskiDiffusion.hh
Constructor & Destructor Documentation
G4DNASmoluchowskiDiffusion::G4DNASmoluchowskiDiffusion (double epsilon = 1e-5)
Definition at line 50 of file G4DNASmoluchowskiDiffusion.cc.
View newest version in sPHENIX GitHub at line 50 of file G4DNASmoluchowskiDiffusion.cc
References fEpsilon, fInverse, fNbins, and int().
G4DNASmoluchowskiDiffusion::~G4DNASmoluchowskiDiffusion () virtual
Definition at line 62 of file G4DNASmoluchowskiDiffusion.cc.
View newest version in sPHENIX GitHub at line 62 of file G4DNASmoluchowskiDiffusion.cc
Member Function Documentation
static double G4DNASmoluchowskiDiffusion::ComputeDistance (double sTransform, double D, double t) inline static
Definition at line 82 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DNASmoluchowskiDiffusion.hh
Referenced by GetRandomDistance().
static double G4DNASmoluchowskiDiffusion::ComputeS (double r, double D, double t) inline static
Definition at line 76 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 76 of file G4DNASmoluchowskiDiffusion.hh
static double G4DNASmoluchowskiDiffusion::ComputeTime (double sTransform, double D, double r) inline static
Definition at line 87 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 87 of file G4DNASmoluchowskiDiffusion.hh
References D().
Referenced by EstimateCrossingTime(), and GetRandomTime().
double G4DNASmoluchowskiDiffusion::EstimateCrossingTime (double proba, double distance, double D) inline
Definition at line 110 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DNASmoluchowskiDiffusion.hh
References ComputeTime(), and GetInverseProbability().
static double G4DNASmoluchowskiDiffusion::GetCumulativeProbability (double sTransform) inline static
Definition at line 304 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 304 of file G4DNASmoluchowskiDiffusion.hh
References G4Exp().
Referenced by G4DNASmoluchowskiDiffusion::BoundingBox::BoundingBox(), and PrepareReverseTable().
static double G4DNASmoluchowskiDiffusion::GetDensityProbability (double r, double _time, double D) inline static
Definition at line 129 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 129 of file G4DNASmoluchowskiDiffusion.hh
References G4Exp().
static double G4DNASmoluchowskiDiffusion::GetDifferential (double sTransform) inline static
Definition at line 123 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 123 of file G4DNASmoluchowskiDiffusion.hh
References G4Exp().
Referenced by Plot().
double G4DNASmoluchowskiDiffusion::GetInverseProbability (double proba) inline
Definition at line 310 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 310 of file G4DNASmoluchowskiDiffusion.hh
References fEpsilon, and fInverse.
Referenced by EstimateCrossingTime(), GetRandomDistance(), GetRandomTime(), and PlotInverse().
double G4DNASmoluchowskiDiffusion::GetRandomDistance (double _time, double D) inline
Definition at line 94 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 94 of file G4DNASmoluchowskiDiffusion.hh
References ComputeDistance(), G4UniformRand, and GetInverseProbability().
double G4DNASmoluchowskiDiffusion::GetRandomTime (double distance, double D) inline
Definition at line 103 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 103 of file G4DNASmoluchowskiDiffusion.hh
References ComputeTime(), G4UniformRand, and GetInverseProbability().
void G4DNASmoluchowskiDiffusion::InitialiseInverseProbability (double xmax = 3e28) inline
Definition at line 357 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 357 of file G4DNASmoluchowskiDiffusion.hh
References fNbins, PrepareReverseTable(), and xmax.
double G4DNASmoluchowskiDiffusion::Plot (double * x, double *) inline
Definition at line 351 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 351 of file G4DNASmoluchowskiDiffusion.hh
References GetDifferential().
double G4DNASmoluchowskiDiffusion::PlotInverse (double * x, double *) inline
Definition at line 346 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 346 of file G4DNASmoluchowskiDiffusion.hh
References GetInverseProbability().
void G4DNASmoluchowskiDiffusion::PrepareReverseTable (double xmin, double xmax) inline
Definition at line 263 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 263 of file G4DNASmoluchowskiDiffusion.hh
References e, fEpsilon, fInverse, fNbins, G4cout, G4endl, GetCumulativeProbability(), G4DNASmoluchowskiDiffusion::BoundingBox::Propose(), x, and xmax.
Referenced by InitialiseInverseProbability().
Member Data Documentation
double G4DNASmoluchowskiDiffusion::fEpsilon
Definition at line 372 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 372 of file G4DNASmoluchowskiDiffusion.hh
Referenced by G4DNASmoluchowskiDiffusion(), GetInverseProbability(), and PrepareReverseTable().
std::vector<double> G4DNASmoluchowskiDiffusion::fInverse
Definition at line 370 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 370 of file G4DNASmoluchowskiDiffusion.hh
Referenced by G4DNASmoluchowskiDiffusion(), GetInverseProbability(), and PrepareReverseTable().
int G4DNASmoluchowskiDiffusion::fNbins
Definition at line 371 of file G4DNASmoluchowskiDiffusion.hh.
View newest version in sPHENIX GitHub at line 371 of file G4DNASmoluchowskiDiffusion.hh
Referenced by G4DNASmoluchowskiDiffusion(), InitialiseInverseProbability(), and PrepareReverseTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNASmoluchowskiDiffusion.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNASmoluchowskiDiffusion.cc