ECCE @ EIC Software: G4GDMLReadSolids Class Reference
G4GDMLReadSolids Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadSolids.hh>
Classes
struct rzPointType
struct zplaneType
Public Member Functions
G4VSolid * GetSolid (const G4String &) const
G4SurfaceProperty * GetSurfaceProperty (const G4String &) const
virtual void SolidsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadMaterials
G4Element * GetElement (const G4String &, G4bool verbose=true) const
G4Isotope * GetIsotope (const G4String &, G4bool verbose=true) const
G4Material * GetMaterial (const G4String &, G4bool verbose=true) const
virtual void MaterialsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadDefine
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void SetupRead (const xercesc::DOMElement *const)=0
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)=0
virtual void Volume_contentRead (const xercesc::DOMElement *const)=0
virtual void StructureRead (const xercesc::DOMElement *const)=0
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
virtual G4LogicalVolume * GetVolume (const G4String &) const =0
virtual G4String GetSetup (const G4String &)=0
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
G4GDMLReadSolids ()
virtual ~G4GDMLReadSolids ()
void BooleanRead (const xercesc::DOMElement *const, const BooleanOp)
void BoxRead (const xercesc::DOMElement *const)
void ConeRead (const xercesc::DOMElement *const)
void ElconeRead (const xercesc::DOMElement *const)
void EllipsoidRead (const xercesc::DOMElement *const)
void EltubeRead (const xercesc::DOMElement *const)
void XtruRead (const xercesc::DOMElement *const)
void HypeRead (const xercesc::DOMElement *const)
void MultiUnionNodeRead (const xercesc::DOMElement *const, G4MultiUnion *const)
void MultiUnionRead (const xercesc::DOMElement *const)
void OrbRead (const xercesc::DOMElement *const)
void ParaRead (const xercesc::DOMElement *const)
void ParaboloidRead (const xercesc::DOMElement *const)
void PolyconeRead (const xercesc::DOMElement *const)
void GenericPolyconeRead (const xercesc::DOMElement *const)
void PolyhedraRead (const xercesc::DOMElement *const)
void GenericPolyhedraRead (const xercesc::DOMElement *const)
G4QuadrangularFacet * QuadrangularRead (const xercesc::DOMElement *const)
void ReflectedSolidRead (const xercesc::DOMElement *const)
void ScaledSolidRead (const xercesc::DOMElement *const)
G4ExtrudedSolid::ZSection SectionRead (const xercesc::DOMElement *const, G4double)
void SphereRead (const xercesc::DOMElement *const)
void TessellatedRead (const xercesc::DOMElement *const)
void TetRead (const xercesc::DOMElement *const)
void TorusRead (const xercesc::DOMElement *const)
void GenTrapRead (const xercesc::DOMElement *const)
void TrapRead (const xercesc::DOMElement *const)
void TrdRead (const xercesc::DOMElement *const)
void TubeRead (const xercesc::DOMElement *const)
void CutTubeRead (const xercesc::DOMElement *const)
void TwistedboxRead (const xercesc::DOMElement *const)
void TwistedtrapRead (const xercesc::DOMElement *const)
void TwistedtrdRead (const xercesc::DOMElement *const)
void TwistedtubsRead (const xercesc::DOMElement *const)
G4TriangularFacet * TriangularRead (const xercesc::DOMElement *const)
G4TwoVector TwoDimVertexRead (const xercesc::DOMElement *const, G4double)
zplaneType ZplaneRead (const xercesc::DOMElement *const)
rzPointType RZPointRead (const xercesc::DOMElement *const)
void OpticalSurfaceRead (const xercesc::DOMElement *const)
void PropertyRead (const xercesc::DOMElement *const, G4OpticalSurface *)
Protected Member Functions inherited from G4GDMLReadMaterials
G4GDMLReadMaterials ()
virtual ~G4GDMLReadMaterials ()
G4double AtomRead (const xercesc::DOMElement *const)
G4int CompositeRead (const xercesc::DOMElement *const, G4String &)
G4double DRead (const xercesc::DOMElement *const)
G4double PRead (const xercesc::DOMElement *const)
G4double TRead (const xercesc::DOMElement *const)
G4double MEERead (const xercesc::DOMElement *const)
void ElementRead (const xercesc::DOMElement *const)
G4double FractionRead (const xercesc::DOMElement *const, G4String &)
void IsotopeRead (const xercesc::DOMElement *const)
void MaterialRead (const xercesc::DOMElement *const)
void MixtureRead (const xercesc::DOMElement *const, G4Element *)
void MixtureRead (const xercesc::DOMElement *const, G4Material *)
void PropertyRead (const xercesc::DOMElement *const, G4Material *)
Protected Member Functions inherited from G4GDMLReadDefine
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Private Types
enum BooleanOp { UNION, SUBTRACTION, INTERSECTION }
Private Attributes
std::map< G4String,
G4MaterialPropertyVector * > mapOfMatPropVects
Additional Inherited Members
Protected Attributes inherited from G4GDMLReadDefine
std::map< G4String, G4double > quantityMap
std::map< G4String, G4ThreeVector > positionMap
std::map< G4String, G4ThreeVector > rotationMap
std::map< G4String, G4ThreeVector > scaleMap
std::map< G4String, G4GDMLMatrix > matrixMap
Detailed Description
Definition at line 54 of file G4GDMLReadSolids.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GDMLReadSolids.hh
Member Enumeration Documentation
enum G4GDMLReadSolids::BooleanOp private
Enumerator:
UNION
SUBTRACTION
INTERSECTION
Definition at line 56 of file G4GDMLReadSolids.hh.
View newest version in sPHENIX GitHub at line 56 of file G4GDMLReadSolids.hh
Constructor & Destructor Documentation
G4GDMLReadSolids::G4GDMLReadSolids () protected
Definition at line 72 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 72 of file G4GDMLReadSolids.cc
G4GDMLReadSolids::~G4GDMLReadSolids () protected virtual
Definition at line 76 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 76 of file G4GDMLReadSolids.cc
Member Function Documentation
void G4GDMLReadSolids::BooleanRead (const xercesc::DOMElement * const booleanElement, const BooleanOp op) protected
Definition at line 81 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 81 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLReadDefine::GetPosition(), G4GDMLReadDefine::GetRotation(), G4GDMLReadDefine::GetRotationMatrix(), GetSolid(), INTERSECTION, position, G4GDMLReadDefine::RefRead(), SUBTRACTION, G4GDMLRead::Transcode(), Acts::Test::transform, UNION, G4GDMLReadDefine::VectorRead(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SolidsRead().
void G4GDMLReadSolids::BoxRead (const xercesc::DOMElement * const boxElement) protected
Definition at line 178 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 178 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), x, y, and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::ConeRead (const xercesc::DOMElement * const coneElement) protected
Definition at line 228 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 228 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::CutTubeRead (const xercesc::DOMElement * const cuttubeElement) protected
Definition at line 2005 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2005 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), rmax(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4GDMLRead::Transcode(), and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::ElconeRead (const xercesc::DOMElement * const elconeElement) protected
Definition at line 296 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 296 of file G4GDMLReadSolids.cc
References dx, dy, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::EllipsoidRead (const xercesc::DOMElement * const ellipsoidElement) protected
Definition at line 347 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 347 of file G4GDMLReadSolids.cc
References KF_timing::ax, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::EltubeRead (const xercesc::DOMElement * const eltubeElement) protected
Definition at line 403 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 403 of file G4GDMLReadSolids.cc
References dx, dy, dz, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::GenericPolyconeRead (const xercesc::DOMElement * const polyconeElement) protected
Definition at line 953 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 953 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), RZPointRead(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::GenericPolyhedraRead (const xercesc::DOMElement * const polyhedraElement) protected
Definition at line 1132 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1132 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), G4GDMLEvaluator::EvaluateInteger(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), RZPointRead(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::GenTrapRead (const xercesc::DOMElement * const gtrapElement) protected
Definition at line 1690 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1690 of file G4GDMLReadSolids.cc
References dz, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
G4VSolid * G4GDMLReadSolids::GetSolid (const G4String & ref) const
Definition at line 2765 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2765 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), G4SolidStore::GetInstance(), and G4SolidStore::GetSolid().
Referenced by BooleanRead(), MultiUnionNodeRead(), ReflectedSolidRead(), ScaledSolidRead(), G03ColorReader::VolumeRead(), and G4GDMLReadStructure::VolumeRead().
G4SurfaceProperty * G4GDMLReadSolids::GetSurfaceProperty (const G4String & ref) const
Definition at line 2780 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2780 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), and G4SurfaceProperty::GetSurfacePropertyTable().
Referenced by G4GDMLReadStructure::BorderSurfaceRead(), and G4GDMLReadStructure::SkinSurfaceRead().
void G4GDMLReadSolids::HypeRead (const xercesc::DOMElement * const hypeElement) protected
Definition at line 515 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 515 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), rmax(), G4GDMLRead::Transcode(), and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::MultiUnionNodeRead (const xercesc::DOMElement * const unionNodeElement, G4MultiUnion * const multiUnionSolid) protected
Definition at line 577 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 577 of file G4GDMLReadSolids.cc
References G4MultiUnion::AddNode(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLReadDefine::GetPosition(), G4GDMLReadDefine::GetRotation(), G4GDMLReadDefine::GetRotationMatrix(), GetSolid(), position, G4GDMLReadDefine::RefRead(), G4GDMLRead::Transcode(), Acts::Test::transform, and G4GDMLReadDefine::VectorRead().
Referenced by MultiUnionRead().
void G4GDMLReadSolids::MultiUnionRead (const xercesc::DOMElement * const unionElement) protected
Definition at line 646 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 646 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), MultiUnionNodeRead(), G4GDMLRead::Transcode(), and G4MultiUnion::Voxelize().
Referenced by SolidsRead().
void G4GDMLReadSolids::OpticalSurfaceRead (const xercesc::DOMElement * const opticalsurfaceElement) protected
Definition at line 2560 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2560 of file G4GDMLReadSolids.cc
References dichroic, dielectric_dichroic, dielectric_dielectric, dielectric_LUT, dielectric_metal, etchedair, etchedlumirrorair, etchedlumirrorglue, etchedteflonair, etchedtioair, etchedtyvekair, etchedvm2000air, etchedvm2000glue, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, firsov, G4Exception(), G4GDMLRead::GenerateName(), glisur, ground, groundair, groundbackpainted, groundfrontpainted, groundlumirrorair, groundlumirrorglue, groundteflonair, groundtioair, groundtyvekair, groundvm2000air, groundvm2000glue, LUT, polished, polishedair, polishedbackpainted, polishedfrontpainted, polishedlumirrorair, polishedlumirrorglue, polishedteflonair, polishedtioair, polishedtyvekair, polishedvm2000air, polishedvm2000glue, PropertyRead(), G4GDMLRead::Transcode(), unified, and x_ray.
Referenced by SolidsRead().
void G4GDMLReadSolids::OrbRead (const xercesc::DOMElement * const orbElement) protected
Definition at line 704 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 704 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), r, and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::ParaboloidRead (const xercesc::DOMElement * const paraElement) protected
Definition at line 812 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 812 of file G4GDMLReadSolids.cc
References dz, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::ParaRead (const xercesc::DOMElement * const paraElement) protected
Definition at line 747 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 747 of file G4GDMLReadSolids.cc
References alpha, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), phi, theta(), G4GDMLRead::Transcode(), x, y, and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::PolyconeRead (const xercesc::DOMElement * const polyconeElement) protected
Definition at line 862 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 862 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), and ZplaneRead().
Referenced by SolidsRead().
void G4GDMLReadSolids::PolyhedraRead (const xercesc::DOMElement * const polyhedraElement) protected
Definition at line 1039 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1039 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), G4GDMLEvaluator::EvaluateInteger(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), and ZplaneRead().
Referenced by SolidsRead().
void G4GDMLReadSolids::PropertyRead (const xercesc::DOMElement * const propertyElement, G4OpticalSurface * opticalsurface) protected
Definition at line 2478 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2478 of file G4GDMLReadSolids.cc
References G4MaterialPropertiesTable::AddConstProperty(), G4MaterialPropertiesTable::AddProperty(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLMatrix::Get(), G4GDMLMatrix::GetCols(), G4OpticalSurface::GetMaterialPropertiesTable(), G4GDMLReadDefine::GetMatrix(), G4GDMLMatrix::GetRows(), G4PhysicsOrderedFreeVector::InsertValues(), mapOfMatPropVects, G4OpticalSurface::SetMaterialPropertiesTable(), G4GDMLRead::Strip(), and G4GDMLRead::Transcode().
Referenced by OpticalSurfaceRead().
G4QuadrangularFacet * G4GDMLReadSolids::QuadrangularRead (const xercesc::DOMElement * const quadrangularElement) protected
Definition at line 1222 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1222 of file G4GDMLReadSolids.cc
References ABSOLUTE, FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4GDMLReadDefine::GetPosition(), G4UnitDefinition::GetValueOf(), RELATIVE, and G4GDMLRead::Transcode().
Referenced by TessellatedRead().
void G4GDMLReadSolids::ReflectedSolidRead (const xercesc::DOMElement * const reflectedSolidElement) protected
Definition at line 1277 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1277 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4GDMLReadDefine::GetRotationMatrix(), GetSolid(), G4UnitDefinition::GetValueOf(), position, scale, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4GDMLRead::Transcode(), Acts::Test::transform, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SolidsRead().
G4GDMLReadSolids::rzPointType G4GDMLReadSolids::RZPointRead (const xercesc::DOMElement * const zplaneElement) protected
Definition at line 2443 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2443 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLReadSolids::rzPointType::r, G4GDMLRead::Transcode(), and G4GDMLReadSolids::rzPointType::z.
Referenced by GenericPolyconeRead(), and GenericPolyhedraRead().
void G4GDMLReadSolids::ScaledSolidRead (const xercesc::DOMElement * const scaledSolidElement) protected
Definition at line 1343 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1343 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLReadDefine::GetScale(), GetSolid(), G4GDMLReadDefine::RefRead(), scale, G4GDMLRead::Transcode(), Acts::Test::transform, G4GDMLReadDefine::VectorRead(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SolidsRead().
G4ExtrudedSolid::ZSection G4GDMLReadSolids::SectionRead (const xercesc::DOMElement * const sectionElement, G4double lunit) protected
Definition at line 1411 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1411 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), CLHEP::Hep2Vector::setX(), CLHEP::Hep2Vector::setY(), and G4GDMLRead::Transcode().
Referenced by XtruRead().
void G4GDMLReadSolids::SolidsRead (const xercesc::DOMElement * const solidsElement) virtual
Implements G4GDMLRead.
Definition at line 2701 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2701 of file G4GDMLReadSolids.cc
References BooleanRead(), BoxRead(), ConeRead(), CutTubeRead(), G4GDMLReadDefine::DefineRead(), ElconeRead(), EllipsoidRead(), EltubeRead(), FatalException, G4cout, G4endl, G4Exception(), GenericPolyconeRead(), GenericPolyhedraRead(), GenTrapRead(), HypeRead(), INTERSECTION, G4GDMLRead::LoopRead(), MultiUnionRead(), OpticalSurfaceRead(), OrbRead(), ParaboloidRead(), ParaRead(), PolyconeRead(), PolyhedraRead(), ReflectedSolidRead(), ScaledSolidRead(), G4GDMLRead::SolidsRead(), SphereRead(), SUBTRACTION, TessellatedRead(), TetRead(), TorusRead(), G4GDMLRead::Transcode(), TrapRead(), TrdRead(), TubeRead(), TwistedboxRead(), TwistedtrapRead(), TwistedtrdRead(), TwistedtubsRead(), UNION, and XtruRead().
void G4GDMLReadSolids::SphereRead (const xercesc::DOMElement * const sphereElement) protected
Definition at line 1454 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1454 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), rmax(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::TessellatedRead (const xercesc::DOMElement * const tessellatedElement) protected
Definition at line 1519 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1519 of file G4GDMLReadSolids.cc
References G4TessellatedSolid::AddFacet(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), QuadrangularRead(), G4TessellatedSolid::SetSolidClosed(), G4GDMLRead::Transcode(), and TriangularRead().
Referenced by SolidsRead().
void G4GDMLReadSolids::TetRead (const xercesc::DOMElement * const tetElement) protected
Definition at line 1575 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1575 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4GDMLReadDefine::GetPosition(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::TorusRead (const xercesc::DOMElement * const torusElement) protected
Definition at line 1628 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1628 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), rmax(), and G4GDMLRead::Transcode().
Referenced by SolidsRead().
void G4GDMLReadSolids::TrapRead (const xercesc::DOMElement * const trapElement) protected
Definition at line 1760 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1760 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), phi, theta(), G4GDMLRead::Transcode(), x1, x2, x3, x4, y1, y2, and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::TrdRead (const xercesc::DOMElement * const trdElement) protected
Definition at line 1839 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1839 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), x1, x2, y1, y2, and z.
Referenced by SolidsRead().
G4TriangularFacet * G4GDMLReadSolids::TriangularRead (const xercesc::DOMElement * const triangularElement) protected
Definition at line 1894 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1894 of file G4GDMLReadSolids.cc
References ABSOLUTE, FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4GDMLReadDefine::GetPosition(), G4UnitDefinition::GetValueOf(), RELATIVE, and G4GDMLRead::Transcode().
Referenced by TessellatedRead().
void G4GDMLReadSolids::TubeRead (const xercesc::DOMElement * const tubeElement) protected
Definition at line 1944 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 1944 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), rmax(), G4GDMLRead::Transcode(), and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::TwistedboxRead (const xercesc::DOMElement * const twistedboxElement) protected
Definition at line 2076 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2076 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), x, y, and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::TwistedtrapRead (const xercesc::DOMElement * const twistedtrapElement) protected
Definition at line 2135 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2135 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), x1, x2, x3, x4, y1, y2, and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::TwistedtrdRead (const xercesc::DOMElement * const twistedtrdElement) protected
Definition at line 2216 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2216 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4GDMLRead::Transcode(), x1, x2, y1, y2, and z.
Referenced by SolidsRead().
void G4GDMLReadSolids::TwistedtubsRead (const xercesc::DOMElement * const twistedtubsElement) protected
Definition at line 2281 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2281 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), phi, and G4GDMLRead::Transcode().
Referenced by SolidsRead().
G4TwoVector G4GDMLReadSolids::TwoDimVertexRead (const xercesc::DOMElement * const element, G4double lunit) protected
Definition at line 2375 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2375 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), CLHEP::Hep2Vector::setX(), CLHEP::Hep2Vector::setY(), and G4GDMLRead::Transcode().
Referenced by XtruRead().
void G4GDMLReadSolids::XtruRead (const xercesc::DOMElement * const xtruElement) protected
Definition at line 452 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 452 of file G4GDMLReadSolids.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), SectionRead(), G4GDMLRead::Transcode(), and TwoDimVertexRead().
Referenced by SolidsRead().
G4GDMLReadSolids::zplaneType G4GDMLReadSolids::ZplaneRead (const xercesc::DOMElement * const zplaneElement) protected
Definition at line 2409 of file G4GDMLReadSolids.cc.
View newest version in sPHENIX GitHub at line 2409 of file G4GDMLReadSolids.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLReadSolids::zplaneType::rmax, G4GDMLReadSolids::zplaneType::rmin, G4GDMLRead::Transcode(), and G4GDMLReadSolids::zplaneType::z.
Referenced by G4GDMLReadParamvol::Polycone_dimensionsRead(), PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), and PolyhedraRead().
Member Data Documentation
std::map<G4String, G4MaterialPropertyVector*> G4GDMLReadSolids::mapOfMatPropVects private
Definition at line 114 of file G4GDMLReadSolids.hh.
View newest version in sPHENIX GitHub at line 114 of file G4GDMLReadSolids.hh
Referenced by PropertyRead().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadSolids.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLReadSolids.cc