ECCE @ EIC Software: MuCrossSections Class Reference
MuCrossSections Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/MuCrossSections.hh>
Public Member Functions
MuCrossSections ()
~MuCrossSections ()
G4double CR_Macroscopic (const G4String &, const G4Material *, G4double, G4double)
G4double CR_PerAtom (const G4String &, const G4Element *, G4double, G4double)
Private Member Functions
G4double CRB_Mephi (G4double, G4double, G4double, G4double)
G4double CRK_Mephi (G4double, G4double, G4double, G4double)
G4double CRN_Mephi (G4double, G4double, G4double, G4double)
G4double CRP_Mephi (G4double, G4double, G4double, G4double)
Detailed Description
Definition at line 43 of file MuCrossSections.hh.
View newest version in sPHENIX GitHub at line 43 of file MuCrossSections.hh
Constructor & Destructor Documentation
MuCrossSections::MuCrossSections ()
Definition at line 43 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 43 of file MuCrossSections.cc
MuCrossSections::~MuCrossSections ()
Definition at line 48 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 48 of file MuCrossSections.cc
Member Function Documentation
G4double MuCrossSections::CR_Macroscopic (const G4String & process, const G4Material * material, G4double tkin, G4double ep)
Definition at line 53 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 53 of file MuCrossSections.cc
References G4Material::GetElementVector(), G4Material::GetNumberOfElements(), and G4Material::GetVecNbOfAtomsPerVolume().
Referenced by RunAction::ComputeTheory().
G4double MuCrossSections::CR_PerAtom (const G4String & process, const G4Element * element, G4double tkin, G4double ep)
Definition at line 74 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 74 of file MuCrossSections.cc
References a, source.hepunit::Avogadro, cm2, Acts::UnitConstants::g, G4Element::GetA(), G4Element::GetZ(), GeV, mole, and z.
double MuCrossSections::CRB_Mephi (G4double z, G4double a, G4double tkin, G4double ep) private
Definition at line 100 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 100 of file MuCrossSections.cc
References alpha, b, Acts::Test::delta, e, fe, sqrte, and v.
G4double MuCrossSections::CRK_Mephi (G4double z, G4double a, G4double tkin, G4double ep) private
Definition at line 179 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 179 of file MuCrossSections.cc
References a, alpha, e, G4cout, G4endl, and v.
G4double MuCrossSections::CRN_Mephi (G4double , G4double a, G4double tkin, G4double ep) private
Definition at line 225 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 225 of file MuCrossSections.cc
References alpha, e, v, v1, and v2.
G4double MuCrossSections::CRP_Mephi (G4double z, G4double a, G4double tkin, G4double ep) private
Definition at line 270 of file MuCrossSections.cc.
View newest version in sPHENIX GitHub at line 270 of file MuCrossSections.cc
References a, a0, alpha, e, e1, e3, fe, Acts::UnitConstants::fm, max, sqrte, sum, G4InuclParticleNames::xi0, and z2.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/MuCrossSections.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/MuCrossSections.cc