ECCE @ EIC Software: G4GeometryTolerance Class Reference
G4GeometryTolerance Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4GeometryTolerance.hh>
Public Member Functions
G4double GetSurfaceTolerance () const
G4double GetAngularTolerance () const
G4double GetRadialTolerance () const
~G4GeometryTolerance ()
Static Public Member Functions
static G4GeometryTolerance * GetInstance ()
Protected Member Functions
void SetSurfaceTolerance (G4double worldExtent)
G4GeometryTolerance ()
Private Attributes
G4double fCarTolerance
G4double fAngTolerance
G4double fRadTolerance
G4bool fInitialised
Static Private Attributes
static G4ThreadLocal
G4GeometryTolerance * fpInstance = 0
Friends
class G4GeometryManager
Detailed Description
Definition at line 55 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 55 of file G4GeometryTolerance.hh
Constructor & Destructor Documentation
G4GeometryTolerance::~G4GeometryTolerance ()
Definition at line 63 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GeometryTolerance.cc
G4GeometryTolerance::G4GeometryTolerance () protected
Definition at line 52 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 52 of file G4GeometryTolerance.cc
References E, fAngTolerance, fCarTolerance, fRadTolerance, mm, and rad.
Referenced by GetInstance().
Member Function Documentation
G4double G4GeometryTolerance::GetAngularTolerance () const
Definition at line 91 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 91 of file G4GeometryTolerance.cc
References fAngTolerance.
Referenced by G4ExtrudedSolid::AddGeneralPolygonFacets(), G4VTwistSurface::AmIOnLeftSide(), G4tgbVolume::FindOrConstructG4Solid(), G4Cons::G4Cons(), G4CutTubs::G4CutTubs(), G4ReplicaNavigation::G4ReplicaNavigation(), G4Sphere::G4Sphere(), G4Tubs::G4Tubs(), G4VTwistedFaceted::G4VTwistedFaceted(), G4AuxiliaryNavServices::ReportTolerances(), and G4Torus::SetAllParameters().
G4GeometryTolerance * G4GeometryTolerance::GetInstance (void) static
Definition at line 72 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 72 of file G4GeometryTolerance.cc
References fpInstance, G4GeometryTolerance(), and G4AutoDelete::Register().
Referenced by G4ExtrudedSolid::AddGeneralPolygonFacets(), G4NavigationLogger::AlongComputeStepLog(), G4VTwistSurface::AmIOnLeftSide(), G4tgbGeometryDumper::approxTo0(), G4tgbVolume::BuildSolidForDivision(), G4GeomTools::CheckSnip(), ExN02DetectorConstruction::Construct(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), DetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), G4GPSModel::DescribeYourselfTo(), G4GeomTools::DiskExtent(), G4TwistTubsHypeSide::DistanceToSurface(), G4tgbVolume::FindOrConstructG4Solid(), G4ArrowModel::G4ArrowModel(), G4ClippablePolygon::G4ClippablePolygon(), G4Cons::G4Cons(), G4CutTubs::G4CutTubs(), G4EnclosingCylinder::G4EnclosingCylinder(), G4IntersectingCone::G4IntersectingCone(), G4ITNavigator1::G4ITNavigator1(), G4ITNavigator2::G4ITNavigator2(), G4ITPathFinder::G4ITPathFinder(), G4MultiUnion::G4MultiUnion(), G4Navigator::G4Navigator(), G4OpBoundaryProcess::G4OpBoundaryProcess(), G4PathFinder::G4PathFinder(), G4PhantomParameterisation::G4PhantomParameterisation(), G4PolyconeSide::G4PolyconeSide(), G4PolyhedraSide::G4PolyhedraSide(), G4PolyPhiFace::G4PolyPhiFace(), G4PropagatorInField::G4PropagatorInField(), G4ReflectionFactory::G4ReflectionFactory(), G4RegularNavigation::G4RegularNavigation(), G4ReplicaNavigation::G4ReplicaNavigation(), G4Sphere::G4Sphere(), G4SteppingManager::G4SteppingManager(), G4Tubs::G4Tubs(), G4UCNBoundaryProcess::G4UCNBoundaryProcess(), G4VDivisionParameterisation::G4VDivisionParameterisation(), G4VFacet::G4VFacet(), G4VIntersectionLocator::G4VIntersectionLocator(), G4Voxelizer::G4Voxelizer(), G4VoxelNavigation::G4VoxelNavigation(), G4VoxelSafety::G4VoxelSafety(), G4VSolid::G4VSolid(), G4VTrackTerminator::G4VTrackTerminator(), G4VTwistedFaceted::G4VTwistedFaceted(), G4VTwistSurface::G4VTwistSurface(), G4TwistTubsFlatSide::GetAreaCode(), G4SolidExtentList::GetExtent(), G4tgrUtils::GetRotationFromDirection(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4ITStepProcessor::Initialize(), G4UnionSolid::Inside(), G4TwistTubsHypeSide::Inside(), G4TwistedTubs::Inside(), G4GeomTools::IsConvex(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), DicomVFileImage::operator+(), DicomPhantomZSliceHeader::operator+(), G4ForwardXrayTR::PostStepDoIt(), G4ErrorFreeTrajState::PropagateError(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4AuxiliaryNavServices::ReportTolerances(), G4Torus::SetAllParameters(), G4ErrorSurfaceTrajParam::SetParameters(), G4GeometryManager::SetWorldMaximumExtent(), G4GeomTools::SphereExtent(), and G4MagInt_Driver::WarnEndPointTooFar().
G4double G4GeometryTolerance::GetRadialTolerance () const
Definition at line 96 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 96 of file G4GeometryTolerance.cc
References fRadTolerance.
Referenced by G4TwistTubsHypeSide::DistanceToSurface(), G4ArrowModel::G4ArrowModel(), G4Cons::G4Cons(), G4CutTubs::G4CutTubs(), G4MultiUnion::G4MultiUnion(), G4ReplicaNavigation::G4ReplicaNavigation(), G4Sphere::G4Sphere(), G4Tubs::G4Tubs(), G4TwistTubsFlatSide::GetAreaCode(), G4UnionSolid::Inside(), G4TwistTubsHypeSide::Inside(), G4TwistedTubs::Inside(), DicomVFileImage::operator+(), DicomPhantomZSliceHeader::operator+(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4AuxiliaryNavServices::ReportTolerances(), and G4Torus::SetAllParameters().
G4double G4GeometryTolerance::GetSurfaceTolerance () const
Definition at line 86 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 86 of file G4GeometryTolerance.cc
References fCarTolerance.
Referenced by G4tgbGeometryDumper::approxTo0(), G4GeomTools::CheckSnip(), ExN02DetectorConstruction::Construct(), DetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), G4GPSModel::DescribeYourselfTo(), G4GeomTools::DiskExtent(), G4ClippablePolygon::G4ClippablePolygon(), G4EnclosingCylinder::G4EnclosingCylinder(), G4IntersectingCone::G4IntersectingCone(), G4ITNavigator1::G4ITNavigator1(), G4ITNavigator2::G4ITNavigator2(), G4ITPathFinder::G4ITPathFinder(), G4Navigator::G4Navigator(), G4OpBoundaryProcess::G4OpBoundaryProcess(), G4PathFinder::G4PathFinder(), G4PhantomParameterisation::G4PhantomParameterisation(), G4PolyconeSide::G4PolyconeSide(), G4PolyhedraSide::G4PolyhedraSide(), G4PolyPhiFace::G4PolyPhiFace(), G4PropagatorInField::G4PropagatorInField(), G4ReflectionFactory::G4ReflectionFactory(), G4RegularNavigation::G4RegularNavigation(), G4ReplicaNavigation::G4ReplicaNavigation(), G4SteppingManager::G4SteppingManager(), G4UCNBoundaryProcess::G4UCNBoundaryProcess(), G4VDivisionParameterisation::G4VDivisionParameterisation(), G4VFacet::G4VFacet(), G4VIntersectionLocator::G4VIntersectionLocator(), G4Voxelizer::G4Voxelizer(), G4VoxelNavigation::G4VoxelNavigation(), G4VoxelSafety::G4VoxelSafety(), G4VSolid::G4VSolid(), G4VTrackTerminator::G4VTrackTerminator(), G4VTwistSurface::G4VTwistSurface(), G4SolidExtentList::GetExtent(), G4tgrUtils::GetRotationFromDirection(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4ITStepProcessor::Initialize(), G4GeomTools::IsConvex(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4ForwardXrayTR::PostStepDoIt(), G4ErrorFreeTrajState::PropagateError(), G4AuxiliaryNavServices::ReportTolerances(), G4ErrorSurfaceTrajParam::SetParameters(), G4GeomTools::SphereExtent(), and G4MagInt_Driver::WarnEndPointTooFar().
void G4GeometryTolerance::SetSurfaceTolerance (G4double worldExtent) protected
Definition at line 106 of file G4GeometryTolerance.cc.
View newest version in sPHENIX GitHub at line 106 of file G4GeometryTolerance.cc
References E, fCarTolerance, fInitialised, fRadTolerance, G4cout, G4endl, G4Exception(), JustWarning, and mm.
Referenced by G4GeometryManager::SetWorldMaximumExtent().
Friends And Related Function Documentation
friend class G4GeometryManager friend
Definition at line 57 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 57 of file G4GeometryTolerance.hh
Member Data Documentation
G4double G4GeometryTolerance::fAngTolerance private
Definition at line 91 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 91 of file G4GeometryTolerance.hh
Referenced by G4GeometryTolerance(), and GetAngularTolerance().
G4double G4GeometryTolerance::fCarTolerance private
Definition at line 90 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GeometryTolerance.hh
Referenced by G4GeometryTolerance(), GetSurfaceTolerance(), and SetSurfaceTolerance().
G4bool G4GeometryTolerance::fInitialised private
Definition at line 93 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GeometryTolerance.hh
Referenced by SetSurfaceTolerance().
G4ThreadLocal G4GeometryTolerance * G4GeometryTolerance::fpInstance = 0 static private
Definition at line 89 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GeometryTolerance.hh
Referenced by GetInstance().
G4double G4GeometryTolerance::fRadTolerance private
Definition at line 92 of file G4GeometryTolerance.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GeometryTolerance.hh
Referenced by G4GeometryTolerance(), GetRadialTolerance(), and SetSurfaceTolerance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4GeometryTolerance.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4GeometryTolerance.cc