ECCE @ EIC Software: G4AttributeFilterT< T > Class Template Reference
G4AttributeFilterT< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4AttributeFilterT.hh>
Public Member Functions
G4AttributeFilterT (const G4String &name="Unspecified")
virtual ~G4AttributeFilterT ()
virtual bool Evaluate (const T &) const
virtual void Print (std::ostream &ostr) const
virtual void Clear ()
void Set (const G4String &name)
void AddInterval (const G4String &)
void AddValue (const G4String &)
Public Member Functions inherited from G4SmartFilter< T >
G4SmartFilter (const G4String &name)
virtual ~G4SmartFilter ()
G4bool Accept (const T &) const
virtual void PrintAll (std::ostream &ostr) const
virtual void Reset ()
void SetActive (const G4bool &)
G4bool GetActive () const
void SetInvert (const G4bool &)
G4bool GetInvert () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Public Member Functions inherited from G4VFilter< T >
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
G4String Name () const
G4String GetName () const
Private Types
enum Config { Interval, SingleValue }
typedef std::pair< G4String,
Config > Pair
typedef std::vector< Pair > ConfigVect
Private Attributes
G4String fAttName
ConfigVect fConfigVect
G4bool fFirst
G4bool fWarnedMissingAttribute
G4VAttValueFilter * filter
Additional Inherited Members
Public Types inherited from G4VFilter< T >
typedef T Type
Detailed Description
template<typename T>
class G4AttributeFilterT< T >
Definition at line 43 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 43 of file G4AttributeFilterT.hh
Member Typedef Documentation
template<typename T > typedef std::vector<Pair> G4AttributeFilterT< T >::ConfigVect private
Definition at line 72 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 72 of file G4AttributeFilterT.hh
template<typename T > typedef std::pair<G4String, Config> G4AttributeFilterT< T >::Pair private
Definition at line 71 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AttributeFilterT.hh
Member Enumeration Documentation
template<typename T > enum G4AttributeFilterT::Config private
Enumerator:
Interval
SingleValue
Definition at line 69 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 69 of file G4AttributeFilterT.hh
Constructor & Destructor Documentation
template<typename T > G4AttributeFilterT< T >::G4AttributeFilterT (const G4String & name = "Unspecified")
Definition at line 86 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 86 of file G4AttributeFilterT.hh
template<typename T > G4AttributeFilterT< T >::~G4AttributeFilterT () virtual
Definition at line 95 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AttributeFilterT.hh
References filter.
Member Function Documentation
template<typename T > void G4AttributeFilterT< T >::AddInterval (const G4String & interval)
Definition at line 204 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 204 of file G4AttributeFilterT.hh
References G4Exception(), and JustWarning.
template<typename T > void G4AttributeFilterT< T >::AddValue (const G4String & value)
Definition at line 223 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 223 of file G4AttributeFilterT.hh
References G4Exception(), and JustWarning.
template<typename T > void G4AttributeFilterT< T >::Clear () virtual
Implements G4SmartFilter< T >.
Definition at line 179 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 179 of file G4AttributeFilterT.hh
References filter.
template<typename T > G4bool G4AttributeFilterT< T >::Evaluate (const T & object) const virtual
Implements G4SmartFilter< T >.
Definition at line 102 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AttributeFilterT.hh
References G4AttUtils::ExtractAttDef(), G4AttUtils::ExtractAttValue(), filter, G4cout, G4endl, G4Exception(), G4AttFilterUtils::GetNewFilter(), G4AttValue::GetValue(), and JustWarning.
template<typename T > void G4AttributeFilterT< T >::Print (std::ostream & ostr) const virtual
Implements G4SmartFilter< T >.
Definition at line 187 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 187 of file G4AttributeFilterT.hh
References filter, and G4VFilter< T >::Name().
template<typename T > void G4AttributeFilterT< T >::Set (const G4String & name)
Definition at line 197 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 197 of file G4AttributeFilterT.hh
Member Data Documentation
template<typename T > G4String G4AttributeFilterT< T >::fAttName private
Definition at line 75 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 75 of file G4AttributeFilterT.hh
template<typename T > ConfigVect G4AttributeFilterT< T >::fConfigVect private
Definition at line 76 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AttributeFilterT.hh
template<typename T > G4bool G4AttributeFilterT< T >::fFirst mutable private
Definition at line 79 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 79 of file G4AttributeFilterT.hh
template<typename T > G4VAttValueFilter* G4AttributeFilterT< T >::filter mutable private
Definition at line 81 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 81 of file G4AttributeFilterT.hh
template<typename T > G4bool G4AttributeFilterT< T >::fWarnedMissingAttribute mutable private
Definition at line 80 of file G4AttributeFilterT.hh.
View newest version in sPHENIX GitHub at line 80 of file G4AttributeFilterT.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4AttributeFilterT.hh