ECCE @ EIC Software: ExN03DetectorConstruction Class Reference
ExN03DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ExN03geom/ExN03DetectorConstruction.hh>
Public Member Functions
ExN03DetectorConstruction ()
~ExN03DetectorConstruction ()
void SetAbsorberMaterial (G4String)
void SetAbsorberThickness (G4double)
void SetGapMaterial (G4String)
void SetGapThickness (G4double)
void SetCalorSizeYZ (G4double)
void SetNbOfLayers (G4int)
void SetMagField (G4double)
G4VPhysicalVolume * Construct ()
void UpdateGeometry ()
void PrintCalorParameters ()
G4double GetWorldSizeX ()
G4double GetWorldSizeYZ ()
G4double GetCalorThickness ()
G4double GetCalorSizeYZ ()
G4int GetNbOfLayers ()
G4Material * GetAbsorberMaterial ()
G4double GetAbsorberThickness ()
G4Material * GetGapMaterial ()
G4double GetGapThickness ()
const G4VPhysicalVolume * GetphysiWorld ()
const G4VPhysicalVolume * GetAbsorber ()
const G4VPhysicalVolume * GetGap ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void ComputeCalorParameters ()
G4VPhysicalVolume * ConstructCalorimeter ()
Private Attributes
G4Material * AbsorberMaterial
G4double AbsorberThickness
G4Material * GapMaterial
G4double GapThickness
G4int NbOfLayers
G4double LayerThickness
G4double CalorSizeYZ
G4double CalorThickness
G4Material * defaultMaterial
G4double WorldSizeYZ
G4double WorldSizeX
G4Box * solidWorld
G4LogicalVolume * logicWorld
G4VPhysicalVolume * physiWorld
G4Box * solidCalor
G4LogicalVolume * logicCalor
G4VPhysicalVolume * physiCalor
G4Box * solidLayer
G4LogicalVolume * logicLayer
G4VPhysicalVolume * physiLayer
G4Box * solidAbsorber
G4LogicalVolume * logicAbsorber
G4VPhysicalVolume * physiAbsorber
G4Box * solidGap
G4LogicalVolume * logicGap
G4VPhysicalVolume * physiGap
G4UniformMagField * magField
ExN03DetectorMessenger * detectorMessenger
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 48 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN03DetectorConstruction.hh
Constructor & Destructor Documentation
ExN03DetectorConstruction::ExN03DetectorConstruction ()
Definition at line 55 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 55 of file ExN03DetectorConstruction.cc
References AbsorberThickness, CalorSizeYZ, cm, ComputeCalorParameters(), DefineMaterials(), detectorMessenger, GapThickness, mm, NbOfLayers, SetAbsorberMaterial(), and SetGapMaterial().
ExN03DetectorConstruction::~ExN03DetectorConstruction ()
Definition at line 82 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 82 of file ExN03DetectorConstruction.cc
References detectorMessenger.
Member Function Documentation
void ExN03DetectorConstruction::ComputeCalorParameters () inline private
Definition at line 145 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 145 of file ExN03DetectorConstruction.hh
References AbsorberThickness, CalorSizeYZ, CalorThickness, GapThickness, LayerThickness, NbOfLayers, WorldSizeX, and WorldSizeYZ.
Referenced by ConstructCalorimeter(), and ExN03DetectorConstruction().
G4VPhysicalVolume * ExN03DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 87 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 87 of file ExN03DetectorConstruction.cc
References ConstructCalorimeter().
G4VPhysicalVolume * ExN03DetectorConstruction::ConstructCalorimeter () private
Definition at line 217 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 217 of file ExN03DetectorConstruction.cc
References AbsorberMaterial, AbsorberThickness, CalorSizeYZ, CalorThickness, G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), ComputeCalorParameters(), defaultMaterial, GapMaterial, GapThickness, G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), G4VisAttributes::GetInvisible(), G4Material::GetName(), kXAxis, LayerThickness, logicAbsorber, logicCalor, logicGap, logicLayer, logicWorld, NbOfLayers, G4GeometryManager::OpenGeometry(), physiAbsorber, physiCalor, physiGap, physiLayer, physiWorld, PrintCalorParameters(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), solidAbsorber, solidCalor, solidGap, solidLayer, solidWorld, WorldSizeX, and WorldSizeYZ.
Referenced by Construct(), and UpdateGeometry().
void ExN03DetectorConstruction::DefineMaterials () private
Definition at line 94 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 94 of file ExN03DetectorConstruction.cc
References a, G4Material::AddElement(), G4Element::AddIsotope(), G4Material::AddMaterial(), atmosphere, bar, C(), cm3, defaultMaterial, e, eV, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetIonisation(), G4Material::GetMaterialTable(), H, kelvin, kStateGas, mg, mole, n, N, pascal, perCent, G4IonisParamMat::SetMeanExcitationEnergy(), source.hepunit::STP_Temperature, source.hepunit::universe_mean_density, and z.
Referenced by ExN03DetectorConstruction().
const G4VPhysicalVolume* ExN03DetectorConstruction::GetAbsorber () inline
Definition at line 91 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file ExN03DetectorConstruction.hh
References physiAbsorber.
G4Material* ExN03DetectorConstruction::GetAbsorberMaterial () inline
Definition at line 84 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file ExN03DetectorConstruction.hh
References AbsorberMaterial.
G4double ExN03DetectorConstruction::GetAbsorberThickness () inline
Definition at line 85 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file ExN03DetectorConstruction.hh
References AbsorberThickness.
G4double ExN03DetectorConstruction::GetCalorSizeYZ () inline
Definition at line 80 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file ExN03DetectorConstruction.hh
References CalorSizeYZ.
G4double ExN03DetectorConstruction::GetCalorThickness () inline
Definition at line 79 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 79 of file ExN03DetectorConstruction.hh
References CalorThickness.
const G4VPhysicalVolume* ExN03DetectorConstruction::GetGap () inline
Definition at line 92 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file ExN03DetectorConstruction.hh
References physiGap.
G4Material* ExN03DetectorConstruction::GetGapMaterial () inline
Definition at line 87 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file ExN03DetectorConstruction.hh
References GapMaterial.
G4double ExN03DetectorConstruction::GetGapThickness () inline
Definition at line 88 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file ExN03DetectorConstruction.hh
References GapThickness.
G4int ExN03DetectorConstruction::GetNbOfLayers () inline
Definition at line 82 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file ExN03DetectorConstruction.hh
References NbOfLayers.
const G4VPhysicalVolume* ExN03DetectorConstruction::GetphysiWorld () inline
Definition at line 90 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file ExN03DetectorConstruction.hh
References physiWorld.
G4double ExN03DetectorConstruction::GetWorldSizeX () inline
Definition at line 76 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN03DetectorConstruction.hh
References WorldSizeX.
G4double ExN03DetectorConstruction::GetWorldSizeYZ () inline
Definition at line 77 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file ExN03DetectorConstruction.hh
References WorldSizeYZ.
void ExN03DetectorConstruction::PrintCalorParameters ()
Definition at line 382 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 382 of file ExN03DetectorConstruction.cc
References AbsorberMaterial, AbsorberThickness, G4cout, GapMaterial, GapThickness, G4Material::GetName(), mm, and NbOfLayers.
Referenced by ConstructCalorimeter().
void ExN03DetectorConstruction::SetAbsorberMaterial (G4String materialChoice)
Definition at line 394 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 394 of file ExN03DetectorConstruction.cc
References AbsorberMaterial, and G4Material::GetMaterial().
Referenced by ExN03DetectorConstruction(), and ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::SetAbsorberThickness (G4double val)
Definition at line 412 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 412 of file ExN03DetectorConstruction.cc
References AbsorberThickness.
Referenced by ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::SetCalorSizeYZ (G4double val)
Definition at line 428 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 428 of file ExN03DetectorConstruction.cc
References CalorSizeYZ.
Referenced by ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::SetGapMaterial (G4String materialChoice)
Definition at line 403 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 403 of file ExN03DetectorConstruction.cc
References GapMaterial, and G4Material::GetMaterial().
Referenced by ExN03DetectorConstruction(), and ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::SetGapThickness (G4double val)
Definition at line 420 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 420 of file ExN03DetectorConstruction.cc
References GapThickness.
Referenced by ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::SetMagField (G4double fieldValue)
Definition at line 446 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 446 of file ExN03DetectorConstruction.cc
References G4FieldManager::CreateChordFinder(), G4TransportationManager::GetFieldManager(), G4TransportationManager::GetTransportationManager(), magField, and G4FieldManager::SetDetectorField().
Referenced by ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::SetNbOfLayers (G4int val)
Definition at line 436 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 436 of file ExN03DetectorConstruction.cc
References NbOfLayers.
Referenced by ExN03DetectorMessenger::SetNewValue().
void ExN03DetectorConstruction::UpdateGeometry ()
Definition at line 468 of file ExN03DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 468 of file ExN03DetectorConstruction.cc
References ConstructCalorimeter(), G4RunManager::DefineWorldVolume(), and G4RunManager::GetRunManager().
Referenced by ExN03DetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* ExN03DetectorConstruction::AbsorberMaterial private
Definition at line 92 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), GetAbsorberMaterial(), PrintCalorParameters(), and SetAbsorberMaterial().
G4double ExN03DetectorConstruction::AbsorberThickness private
Definition at line 97 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), ExN03DetectorConstruction(), GetAbsorberThickness(), PrintCalorParameters(), and SetAbsorberThickness().
G4double ExN03DetectorConstruction::CalorSizeYZ private
Definition at line 105 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), ExN03DetectorConstruction(), GetCalorSizeYZ(), and SetCalorSizeYZ().
G4double ExN03DetectorConstruction::CalorThickness private
Definition at line 106 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), and GetCalorThickness().
G4Material* ExN03DetectorConstruction::defaultMaterial private
Definition at line 108 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 108 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and DefineMaterials().
ExN03DetectorMessenger* ExN03DetectorConstruction::detectorMessenger private
Definition at line 134 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 134 of file ExN03DetectorConstruction.hh
Referenced by ExN03DetectorConstruction(), and ~ExN03DetectorConstruction().
G4Material* ExN03DetectorConstruction::GapMaterial private
Definition at line 99 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), GetGapMaterial(), PrintCalorParameters(), and SetGapMaterial().
G4double ExN03DetectorConstruction::GapThickness private
Definition at line 100 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), ExN03DetectorConstruction(), GetGapThickness(), PrintCalorParameters(), and SetGapThickness().
G4double ExN03DetectorConstruction::LayerThickness private
Definition at line 103 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and ConstructCalorimeter().
G4LogicalVolume* ExN03DetectorConstruction::logicAbsorber private
Definition at line 125 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4LogicalVolume* ExN03DetectorConstruction::logicCalor private
Definition at line 117 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4LogicalVolume* ExN03DetectorConstruction::logicGap private
Definition at line 129 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 129 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4LogicalVolume* ExN03DetectorConstruction::logicLayer private
Definition at line 121 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4LogicalVolume* ExN03DetectorConstruction::logicWorld private
Definition at line 113 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 113 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4UniformMagField* ExN03DetectorConstruction::magField private
Definition at line 132 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 132 of file ExN03DetectorConstruction.hh
Referenced by SetMagField().
G4int ExN03DetectorConstruction::NbOfLayers private
Definition at line 102 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), ExN03DetectorConstruction(), GetNbOfLayers(), PrintCalorParameters(), and SetNbOfLayers().
G4VPhysicalVolume* ExN03DetectorConstruction::physiAbsorber private
Definition at line 126 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 126 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetAbsorber().
G4VPhysicalVolume* ExN03DetectorConstruction::physiCalor private
Definition at line 118 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 118 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4VPhysicalVolume* ExN03DetectorConstruction::physiGap private
Definition at line 130 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 130 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetGap().
G4VPhysicalVolume* ExN03DetectorConstruction::physiLayer private
Definition at line 122 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 122 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4VPhysicalVolume* ExN03DetectorConstruction::physiWorld private
Definition at line 114 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetphysiWorld().
G4Box* ExN03DetectorConstruction::solidAbsorber private
Definition at line 124 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 124 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Box* ExN03DetectorConstruction::solidCalor private
Definition at line 116 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Box* ExN03DetectorConstruction::solidGap private
Definition at line 128 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 128 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Box* ExN03DetectorConstruction::solidLayer private
Definition at line 120 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 120 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Box* ExN03DetectorConstruction::solidWorld private
Definition at line 112 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 112 of file ExN03DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4double ExN03DetectorConstruction::WorldSizeX private
Definition at line 110 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), and GetWorldSizeX().
G4double ExN03DetectorConstruction::WorldSizeYZ private
Definition at line 109 of file ExN03DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file ExN03DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), and GetWorldSizeYZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ExN03geom/ExN03DetectorConstruction.hh
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ExN03geom/ExN03DetectorConstruction.cc