ECCE @ EIC Software: G4INCL::Store Class Reference
G4INCL::Store Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLStore.hh>
Public Member Functions
Store (Config const *const config)
~Store ()
void add (Particle *p)
void add (ParticleList const &pL)
Add a list of particles to the Store.
void addParticleEntryAvatar (IAvatar *a)
Add one ParticleEntry avatar.
void addParticleEntryAvatars (IAvatarList const &al)
Add one ParticleEntry avatar.
void add (IAvatar *a)
IAvatarList const & getAvatars () const
void addIncomingParticle (Particle *const p)
void removeFromIncoming (Particle *const p)
void clearIncoming ()
Clear the incoming list.
void deleteIncoming ()
Clear the incoming list and delete the particles.
void particleHasBeenUpdated (Particle *const)
Notify the Store about a particle update.
void removeScheduledAvatars ()
Remove avatars that have been scheduled.
IAvatar * findSmallestTime ()
void timeStep (G4double step)
void particleHasBeenEjected (Particle *const)
void addToOutgoing (Particle *p)
add the particle to the outgoing particle list.
void addToOutgoing (ParticleList const &pl)
Add a list of particles to the outgoing particle list.
void particleHasBeenDestroyed (Particle *const)
void particleHasEntered (Particle *const particle)
Move a particle from incoming to inside.
ParticleList const & getIncomingParticles () const
ParticleList const & getOutgoingParticles () const
ParticleList extractDynamicalSpectators ()
Returns a list of dynamical spectators.
ParticleList const & getParticles () const
Book & getBook ()
G4int countCascading ()
Config const * getConfig ()
void clear ()
void clearInside ()
void clearOutgoing ()
void clearAvatars ()
void loadParticles (std::string const &filename)
G4int getLoadedA ()
G4int getLoadedZ ()
G4double getLoadedStoppingTime ()
std::string printParticleConfiguration ()
void writeParticles (std::string const &filename)
std::string printAvatars ()
G4bool containsCollisions () const
Static Public Member Functions
static G4bool avatarComparisonPredicate (IAvatar *lhs, IAvatar *rhs)
Comparison predicate for avatars.
Private Types
typedef std::multimap
< Particle *, IAvatar * >
::value_type PAPair
typedef std::multimap
< Particle *, IAvatar * >
::iterator PAIter
typedef std::pair< PAIter, PAIter > PAIterPair
typedef std::set< IAvatar * >
::const_iterator ASIter
Private Member Functions
Store (const Store &rhs)
Dummy copy constructor to shut up Coverity warnings.
Store & operator= (Store const &rhs)
Dummy assignment operator to shut up Coverity warnings.
void connectAvatarToParticle (IAvatar *const a, Particle *const p)
Connect an avatar to a particle.
void disconnectAvatarFromParticle (IAvatar *const a, Particle *const p)
Disconnect an avatar from a particle.
void removeAvatar (IAvatar *const a)
Remove an avatar from the list of avatars.
Private Attributes
std::multimap< Particle
*, IAvatar * > particleAvatarConnections
std::set< IAvatar * > avatarsToBeRemoved
Set of avatars to be removed.
IAvatarList avatarList
ParticleList incoming
ParticleList inside
ParticleList outgoing
ParticleList geomSpectators
G4double currentTime
Book theBook
G4int loadedA
G4int loadedZ
G4double loadedStoppingTime
Config const * theConfig
Detailed Description
The purpose of the Store object is to act as a "particle manager" that keeps track ofall the particles in our simulation. It also tracks the avatars and their connections to particles.
Definition at line 73 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 73 of file G4INCLStore.hh
Member Typedef Documentation
typedef std::set<IAvatar*>::const_iterator G4INCL::Store::ASIter private
Definition at line 406 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 406 of file G4INCLStore.hh
typedef std::multimap<Particle*, IAvatar*>::iterator G4INCL::Store::PAIter private
Definition at line 401 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 401 of file G4INCLStore.hh
typedef std::pair<PAIter, PAIter> G4INCL::Store::PAIterPair private
Definition at line 402 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 402 of file G4INCLStore.hh
typedef std::multimap<Particle*, IAvatar*>::value_type G4INCL::Store::PAPair private
Definition at line 400 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 400 of file G4INCLStore.hh
Constructor & Destructor Documentation
G4INCL::Store::Store (Config const *const config)
Store constructor
Definition at line 45 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 45 of file G4INCLStore.cc
G4INCL::Store::~Store ()
Store destructor
Definition at line 53 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLStore.cc
References clear(), G4INCL::Book::reset(), and theBook.
G4INCL::Store::Store (const Store & rhs) private
Dummy copy constructor to shut up Coverity warnings.
Member Function Documentation
void G4INCL::Store::add (Particle * p)
Add one particle to the store.
Particle objects don't know anything about avatars so this method will only do two things:
add the particle to the particle map ParticleID -> Particle*
add an empty entry for this particle into map AvatarID -> [ParticleID]
Definition at line 58 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLStore.cc
References inside.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::initializeParticles(), loadParticles(), particleHasEntered(), and G4INCL::StandardPropagationModel::registerAvatar().
void G4INCL::Store::add (ParticleList const & pL)
Add a list of particles to the Store.
This acts as if add(Particle *) was called on each element of the list.
Definition at line 62 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 62 of file G4INCLStore.cc
References inside.
void G4INCL::Store::add (IAvatar * a)
Add one avatar to the store
Avatars know about the particles they are associated with. Adding an avatar consists of the following steps:
Add the new avatar to the avatar list
Add any related new particles to the store by calling add(Particle*) (this should not happen, by the time we are adding avatars all particles should have already been added)
Connect the particles involved to the avatar in the map: particleAvatarConnections :: ParticleID -> [AvatarID]
Add the new avatar to the map: avatarParticleConnections :: AvatarID -> [ParticleID]
Definition at line 83 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 83 of file G4INCLStore.cc
References avatarList, connectAvatarToParticle(), e, and G4INCL::IAvatar::getParticles().
void G4INCL::Store::addIncomingParticle (Particle *const p)
Add a particle to the incoming list.
Parameters
p particle to add
Definition at line 95 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 95 of file G4INCLStore.cc
References incoming.
Referenced by addParticleEntryAvatar().
void G4INCL::Store::addParticleEntryAvatar (IAvatar * a)
Add one ParticleEntry avatar.
Definition at line 66 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 66 of file G4INCLStore.cc
References addIncomingParticle(), avatarList, connectAvatarToParticle(), e, and G4INCL::IAvatar::getParticles().
Referenced by addParticleEntryAvatars(), G4INCL::INCL::makeCompoundNucleus(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Store::addParticleEntryAvatars (IAvatarList const & al)
Add one ParticleEntry avatar.
Definition at line 78 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 78 of file G4INCLStore.cc
References a, addParticleEntryAvatar(), and e.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
void G4INCL::Store::addToOutgoing (Particle * p) inline
add the particle to the outgoing particle list.
Parameters
p pointer to the particle to be added
Definition at line 190 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 190 of file G4INCLStore.hh
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayMe(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), and G4INCL::INCL::makeProjectileRemnant().
void G4INCL::Store::addToOutgoing (ParticleList const & pl) inline
Add a list of particles to the outgoing particle list.
Parameters
pl list of particles to be added
Definition at line 196 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 196 of file G4INCLStore.hh
References e.
static G4bool G4INCL::Store::avatarComparisonPredicate (IAvatar * lhs, IAvatar * rhs) inline static
Comparison predicate for avatars.
avatarComparisonPredicate is used by the std::sort or std::min_element functions to compare the avatar objects according to their time.
Parameters
lhs pointer to the first avatar
rhs pointer to the second avatar
Returns
true iff lhs' time is smaller than rhs'.
Definition at line 352 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 352 of file G4INCLStore.hh
References G4INCL::IAvatar::getTime().
Referenced by findSmallestTime().
void G4INCL::Store::clear (void)
Clear all avatars and particles from the store.
Warning! This actually deletes the objects as well!
Definition at line 203 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 203 of file G4INCLStore.cc
References clearAvatars(), clearInside(), clearOutgoing(), INCL_WARN, and incoming.
Referenced by loadParticles(), and ~Store().
void G4INCL::Store::clearAvatars ()
Clear avatars only.
Definition at line 193 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 193 of file G4INCLStore.cc
References avatarList, avatarsToBeRemoved, e, and particleAvatarConnections.
Referenced by clear(), and G4INCL::StandardPropagationModel::propagate().
void G4INCL::Store::clearIncoming () inline
Clear the incoming list.
Definition at line 145 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 145 of file G4INCLStore.hh
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
void G4INCL::Store::clearInside ()
Clear all inside particles from the store.
Warning! This actually deletes the objects as well!
Definition at line 216 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 216 of file G4INCLStore.cc
References e, and inside.
Referenced by clear().
void G4INCL::Store::clearOutgoing ()
Clear all outgoing particles from the store.
Warning! This actually deletes the objects as well!
Definition at line 223 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 223 of file G4INCLStore.cc
References c, G4INCL::Cluster::deleteParticles(), e, and outgoing.
Referenced by clear(), and G4INCL::INCL::makeCompoundNucleus().
void G4INCL::Store::connectAvatarToParticle (IAvatar *const a, Particle *const p) private
Connect an avatar to a particle.
Adds the avatar to the list of avatars where the particle appears. This is typically called when the avatar is created.
Parameters
p the particle
a the avatar
Definition at line 99 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 99 of file G4INCLStore.cc
References particleAvatarConnections.
Referenced by add(), and addParticleEntryAvatar().
G4bool G4INCL::Store::containsCollisions () const
Definition at line 351 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 351 of file G4INCLStore.cc
References avatarList, G4INCL::CollisionAvatarType, and e.
G4int G4INCL::Store::countCascading () inline
Definition at line 261 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 261 of file G4INCLStore.hh
References e, and n.
void G4INCL::Store::deleteIncoming () inline
Clear the incoming list and delete the particles.
Definition at line 150 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 150 of file G4INCLStore.hh
References e.
Referenced by G4INCL::INCL::postCascade().
void G4INCL::Store::disconnectAvatarFromParticle (IAvatar *const a, Particle *const p) private
Disconnect an avatar from a particle.
Removes the avatar from the list of avatars where the particle appears. This is typically called when the avatar has been invalidated or realised.
Parameters
p the particle
a the avatar
Definition at line 103 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 103 of file G4INCLStore.cc
References INCL_WARN, and particleAvatarConnections.
Referenced by removeAvatar().
ParticleList G4INCL::Store::extractDynamicalSpectators () inline
Returns a list of dynamical spectators.
Looks in the outgoing list for particles without collisions and decays, removes them from outgoing and returns them in a list.
Returns
the (possibly empty) list of dynamical spectators
Definition at line 232 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 232 of file G4INCLStore.hh
References e, and G4INCL::UnorderedVector< T >::remove().
Referenced by G4INCL::INCL::makeProjectileRemnant().
IAvatar * G4INCL::Store::findSmallestTime ()
Find the avatar that has the smallest time.
Definition at line 142 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 142 of file G4INCLStore.cc
References avatarComparisonPredicate(), avatarList, and removeAvatar().
Referenced by G4INCL::StandardPropagationModel::propagate().
IAvatarList const& G4INCL::Store::getAvatars () const inline
Return the list of avatars
Definition at line 126 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 126 of file G4INCLStore.hh
Book& G4INCL::Store::getBook () inline
Return the pointer to the Book object which keeps track of various counters.
Definition at line 259 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 259 of file G4INCLStore.hh
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::CascadeAction::beforeAvatarDefaultAction(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::INCL::continueCascade(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::InteractionAvatar::enforceEnergyConservation(), G4INCL::Nucleus::fillEventInfo(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::INCL::initializeTarget(), G4INCL::Nucleus::insertParticle(), G4INCL::PauliStrictStandard::isBlocked(), G4INCL::Nucleus::isEventTransparent(), G4INCL::DecayAvatar::postInteraction(), G4INCL::BinaryCollisionAvatar::postInteraction(), G4INCL::SurfaceAvatar::postInteraction(), G4INCL::InteractionAvatar::postInteraction(), G4INCL::StandardPropagationModel::propagate(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
Config const* G4INCL::Store::getConfig () inline
Get the config object
Definition at line 273 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 273 of file G4INCLStore.hh
Referenced by G4INCL::SurfaceAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::InteractionAvatar::postInteraction(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
ParticleList const& G4INCL::Store::getIncomingParticles () const inline
Return the list of incoming particles (i.e. particles that have yet to enter the cascade).
Definition at line 217 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 217 of file G4INCLStore.hh
Referenced by G4INCL::INCL::continueCascade().
G4int G4INCL::Store::getLoadedA () inline
Get the value of the nucleus mass number that we read from file with loadParticles.
Definition at line 311 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 311 of file G4INCLStore.hh
G4double G4INCL::Store::getLoadedStoppingTime () inline
Get the value of the stopping time that we read from file with loadParticles.
Definition at line 323 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 323 of file G4INCLStore.hh
G4int G4INCL::Store::getLoadedZ () inline
Get the value of the nucleus charge number that we read from file with loadParticles.
Definition at line 317 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 317 of file G4INCLStore.hh
ParticleList const& G4INCL::Store::getOutgoingParticles () const inline
Return the list of outgoing particles (i.e. particles that have left the cascade).
Definition at line 223 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 223 of file G4INCLStore.hh
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::Nucleus::computeSeparationEnergyBalance(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingNeutralKaon(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::Nucleus::fillEventInfo(), G4INCL::Nucleus::getConservationBalance(), G4INCL::INCL::postCascade(), and G4INCL::Nucleus::print().
ParticleList const& G4INCL::Store::getParticles () const inline
Return the list of "active" particles (i.e. particles that can participate in collisions).
Definition at line 253 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 253 of file G4INCLStore.hh
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::computeCenterOfMass(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeTotalEnergy(), G4INCL::Nucleus::containsAntiKaon(), G4INCL::Nucleus::containsDeltas(), G4INCL::Nucleus::containsEtas(), G4INCL::Nucleus::containsKaon(), G4INCL::Nucleus::containsLambda(), G4INCL::Nucleus::containsOmegas(), G4INCL::Nucleus::containsSigma(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::Nucleus::decayInsideStrangeParticles(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), G4INCL::StandardPropagationModel::generateAllAvatars(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::PauliGlobal::isBlocked(), G4INCL::CDPP::isBlocked(), G4INCL::Nucleus::print(), and G4INCL::StandardPropagationModel::updateAvatars().
void G4INCL::Store::loadParticles (std::string const & filename)
Load particle configuration from ASCII file (see avatarPredictionTest).
Definition at line 239 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 239 of file G4INCLStore.cc
References A(), add(), clear(), E, in, INCL_FATAL, G4INCL::Book::incrementCascading(), loadedA, loadedStoppingTime, loadedZ, G4INCL::Particle::makeParticipant(), G4INCL::Neutron, G4INCL::Proton, G4INCL::Particle::setPotentialEnergy(), t, theBook, G4INCL::UnknownParticle, v, x, y, Z, and z.
Store& G4INCL::Store::operator= (Store const & rhs) private
Dummy assignment operator to shut up Coverity warnings.
void G4INCL::Store::particleHasBeenDestroyed (Particle * const p)
Remove the particle from the system. This also removes all avatars related to this particle.
Definition at line 181 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 181 of file G4INCLStore.cc
References inside, particleHasBeenUpdated(), and G4INCL::UnorderedVector< T >::remove().
Referenced by G4INCL::Nucleus::applyFinalState().
void G4INCL::Store::particleHasBeenEjected (Particle * const p)
Mark the particle as ejected. This removes it from the list of inside particles and removes all avatars related to this particle.
Definition at line 175 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 175 of file G4INCLStore.cc
References inside, particleHasBeenUpdated(), and G4INCL::UnorderedVector< T >::remove().
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), and G4INCL::Nucleus::emitInsideStrangeParticles().
void G4INCL::Store::particleHasBeenUpdated (Particle * const particle)
Notify the Store about a particle update.
Notify the Store that a particle has been updated. This schedules the removal of obsolete avatars and their disconnection from the particle.
Definition at line 127 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 127 of file G4INCLStore.cc
References avatarsToBeRemoved, and particleAvatarConnections.
Referenced by G4INCL::Nucleus::applyFinalState(), particleHasBeenDestroyed(), and particleHasBeenEjected().
void G4INCL::Store::particleHasEntered (Particle *const particle)
Move a particle from incoming to inside.
Parameters
particle pointer to a particle
Definition at line 188 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 188 of file G4INCLStore.cc
References add(), and removeFromIncoming().
Referenced by G4INCL::Nucleus::insertParticle().
std::string G4INCL::Store::printAvatars ()
Print the list of avatars
Definition at line 343 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 343 of file G4INCLStore.cc
References avatarList, and e.
std::string G4INCL::Store::printParticleConfiguration ()
Print the nucleon configuration of the nucleus.
Definition at line 286 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 286 of file G4INCLStore.cc
References A(), E, e, inside, G4INCL::Neutron, G4INCL::Proton, x, y, Z, and z.
Referenced by writeParticles().
void G4INCL::Store::removeAvatar (IAvatar *const a) private
Remove an avatar from the list of avatars.
Removes an avatar from the list of all avatars. The avatar is not deleted.
Parameters
a the avatar to remove
Definition at line 115 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 115 of file G4INCLStore.cc
References avatarList, disconnectAvatarFromParticle(), e, G4INCL::IAvatar::getParticles(), and G4INCL::UnorderedVector< T >::remove().
Referenced by findSmallestTime(), and removeScheduledAvatars().
void G4INCL::Store::removeFromIncoming (Particle *const p) inline
Add a particle to the incoming list.
Parameters
p particle to add
Definition at line 142 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 142 of file G4INCLStore.hh
Referenced by particleHasEntered().
void G4INCL::Store::removeScheduledAvatars ()
Remove avatars that have been scheduled.
Definition at line 134 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 134 of file G4INCLStore.cc
References a, avatarsToBeRemoved, e, and removeAvatar().
Referenced by G4INCL::Nucleus::applyFinalState().
void G4INCL::Store::timeStep (G4double step)
Make one time step: propagate particles and subtract the length of the step from the avatar times.
Definition at line 168 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 168 of file G4INCLStore.cc
References inside.
Referenced by G4INCL::StandardPropagationModel::propagate().
void G4INCL::Store::writeParticles (std::string const & filename)
Print the nucleon configuration of the nucleus.
Definition at line 337 of file G4INCLStore.cc.
View newest version in sPHENIX GitHub at line 337 of file G4INCLStore.cc
References printParticleConfiguration().
Member Data Documentation
IAvatarList G4INCL::Store::avatarList private
List of all avatars
Definition at line 412 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 412 of file G4INCLStore.hh
Referenced by add(), addParticleEntryAvatar(), clearAvatars(), containsCollisions(), findSmallestTime(), printAvatars(), and removeAvatar().
std::set<IAvatar*> G4INCL::Store::avatarsToBeRemoved private
Set of avatars to be removed.
Definition at line 405 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 405 of file G4INCLStore.hh
Referenced by clearAvatars(), particleHasBeenUpdated(), and removeScheduledAvatars().
G4double G4INCL::Store::currentTime private
The current time in the simulation
Definition at line 437 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 437 of file G4INCLStore.hh
ParticleList G4INCL::Store::geomSpectators private
List of geometrical spectators
Definition at line 432 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 432 of file G4INCLStore.hh
ParticleList G4INCL::Store::incoming private
List of incoming particles
Definition at line 417 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 417 of file G4INCLStore.hh
Referenced by addIncomingParticle(), and clear().
ParticleList G4INCL::Store::inside private
List of particles that are inside the nucleus
Definition at line 422 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 422 of file G4INCLStore.hh
Referenced by add(), clearInside(), particleHasBeenDestroyed(), particleHasBeenEjected(), printParticleConfiguration(), and timeStep().
G4int G4INCL::Store::loadedA private
The target nucleus mass number that was loaded from a particle file
Definition at line 447 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 447 of file G4INCLStore.hh
Referenced by loadParticles().
G4double G4INCL::Store::loadedStoppingTime private
The stopping time that was loaded from a particle file
Definition at line 457 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 457 of file G4INCLStore.hh
Referenced by loadParticles().
G4int G4INCL::Store::loadedZ private
The target nucleus charge number that was loaded from a particle file
Definition at line 452 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 452 of file G4INCLStore.hh
Referenced by loadParticles().
ParticleList G4INCL::Store::outgoing private
List of outgoing particles
Definition at line 427 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 427 of file G4INCLStore.hh
Referenced by clearOutgoing().
std::multimap<Particle*, IAvatar*> G4INCL::Store::particleAvatarConnections private
Map particle -> [avatar]
Definition at line 399 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 399 of file G4INCLStore.hh
Referenced by clearAvatars(), connectAvatarToParticle(), disconnectAvatarFromParticle(), and particleHasBeenUpdated().
Book G4INCL::Store::theBook private
The Book object keeps track of global counters
Definition at line 442 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 442 of file G4INCLStore.hh
Referenced by loadParticles(), and ~Store().
Config const* G4INCL::Store::theConfig private
Pointer to the Config object
Definition at line 462 of file G4INCLStore.hh.
View newest version in sPHENIX GitHub at line 462 of file G4INCLStore.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLStore.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLStore.cc