ECCE @ EIC Software: G4CrossSectionBuffer Class Reference
G4CrossSectionBuffer Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CrossSectionBuffer.hh>
Public Member Functions
G4CrossSectionBuffer (const G4ParticleDefinition *aA, const G4ParticleDefinition *aB)
G4bool InCharge (const G4ParticleDefinition *aA, const G4ParticleDefinition *aB) const
void push_back (G4double S, G4double x)
G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
void Print ()
Private Attributes
std::vector< std::pair
< G4double, G4double > > theData
const G4ParticleDefinition * theA
const G4ParticleDefinition * theB
Detailed Description
Definition at line 37 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 37 of file G4CrossSectionBuffer.hh
Constructor & Destructor Documentation
G4CrossSectionBuffer::G4CrossSectionBuffer (const G4ParticleDefinition * aA, const G4ParticleDefinition * aB) inline
Definition at line 41 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 41 of file G4CrossSectionBuffer.hh
Member Function Documentation
G4double G4CrossSectionBuffer::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const inline
Definition at line 65 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 65 of file G4CrossSectionBuffer.hh
References G4KineticTrack::Get4Momentum(), CLHEP::millibarn, theData, x1, x2, y1, and y2.
G4bool G4CrossSectionBuffer::InCharge (const G4ParticleDefinition * aA, const G4ParticleDefinition * aB) const inline
Definition at line 44 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 44 of file G4CrossSectionBuffer.hh
References theA, and theB.
void G4CrossSectionBuffer::Print (void) inline
Definition at line 109 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 109 of file G4CrossSectionBuffer.hh
References G4cerr, G4endl, CLHEP::millibarn, and theData.
void G4CrossSectionBuffer::push_back (G4double S, G4double x) inline
Definition at line 58 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 58 of file G4CrossSectionBuffer.hh
References S(), theData, and x.
Referenced by G4CollisionComposite::BufferCrossSection().
Member Data Documentation
const G4ParticleDefinition* G4CrossSectionBuffer::theA private
Definition at line 120 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 120 of file G4CrossSectionBuffer.hh
Referenced by InCharge().
const G4ParticleDefinition* G4CrossSectionBuffer::theB private
Definition at line 121 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 121 of file G4CrossSectionBuffer.hh
Referenced by InCharge().
std::vector<std::pair<G4double, G4double> > G4CrossSectionBuffer::theData private
Definition at line 118 of file G4CrossSectionBuffer.hh.
View newest version in sPHENIX GitHub at line 118 of file G4CrossSectionBuffer.hh
Referenced by CrossSection(), Print(), and push_back().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CrossSectionBuffer.hh