ECCE @ EIC Software: G4BoundingSphereScene Class Reference
G4BoundingSphereScene Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4BoundingSphereScene.hh>
Public Member Functions
G4BoundingSphereScene (G4VModel *pModel=0)
virtual ~G4BoundingSphereScene ()
G4VisExtent GetBoundingSphereExtent ()
const G4Point3D & GetCentre () const
G4double GetRadius () const
void SetCentre (const G4Point3D &centre)
void ResetBoundingSphere ()
void AccrueBoundingSphere (const G4Point3D &centre, G4double radius)
Public Member Functions inherited from G4PseudoScene
G4PseudoScene ()
virtual ~G4PseudoScene ()
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
void PostAddSolid ()
void AddSolid (const G4Box &solid)
void AddSolid (const G4Cons &solid)
void AddSolid (const G4Orb &solid)
void AddSolid (const G4Para &solid)
void AddSolid (const G4Sphere &solid)
void AddSolid (const G4Torus &solid)
void AddSolid (const G4Trap &solid)
void AddSolid (const G4Trd &solid)
void AddSolid (const G4Tubs &solid)
void AddSolid (const G4Ellipsoid &solid)
void AddSolid (const G4Polycone &solid)
void AddSolid (const G4Polyhedra &solid)
void AddSolid (const G4TessellatedSolid &solid)
void AddSolid (const G4VSolid &solid)
void AddCompound (const G4VTrajectory &)
void AddCompound (const G4VHit &)
void AddCompound (const G4VDigi &)
void AddCompound (const G4THitsMap< G4double > &)
void AddCompound (const G4THitsMap< G4StatDouble > &)
void BeginPrimitives (const G4Transform3D &)
void EndPrimitives ()
void BeginPrimitives2D (const G4Transform3D &)
void EndPrimitives2D ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Scale &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polymarker &)
void AddPrimitive (const G4Polyhedron &)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
virtual const G4VisExtent & GetExtent () const
Private Member Functions
void ProcessVolume (const G4VSolid &solid)
Private Attributes
G4VModel * fpModel
G4Point3D fCentre
G4double fRadius
Additional Inherited Members
Protected Attributes inherited from G4PseudoScene
const G4Transform3D * fpCurrentObjectTransformation
Detailed Description
Definition at line 40 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 40 of file G4BoundingSphereScene.hh
Constructor & Destructor Documentation
G4BoundingSphereScene::G4BoundingSphereScene (G4VModel * pModel = 0)
Definition at line 38 of file G4BoundingSphereScene.cc.
View newest version in sPHENIX GitHub at line 38 of file G4BoundingSphereScene.cc
G4BoundingSphereScene::~G4BoundingSphereScene () virtual
Definition at line 43 of file G4BoundingSphereScene.cc.
View newest version in sPHENIX GitHub at line 43 of file G4BoundingSphereScene.cc
Member Function Documentation
void G4BoundingSphereScene::AccrueBoundingSphere (const G4Point3D & centre, G4double radius)
Definition at line 71 of file G4BoundingSphereScene.cc.
View newest version in sPHENIX GitHub at line 71 of file G4BoundingSphereScene.cc
References HepGeom::BasicVector3D< T >::mag(), and HepGeom::BasicVector3D< T >::unit().
Referenced by ProcessVolume().
G4VisExtent G4BoundingSphereScene::GetBoundingSphereExtent ()
Definition at line 45 of file G4BoundingSphereScene.cc.
View newest version in sPHENIX GitHub at line 45 of file G4BoundingSphereScene.cc
References fCentre, and fRadius.
const G4Point3D& G4BoundingSphereScene::GetCentre () const inline
Definition at line 50 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 50 of file G4BoundingSphereScene.hh
References fCentre.
G4double G4BoundingSphereScene::GetRadius () const inline
Definition at line 52 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BoundingSphereScene.hh
References fRadius.
void G4BoundingSphereScene::ProcessVolume (const G4VSolid & solid) private virtual
Implements G4PseudoScene.
Definition at line 49 of file G4BoundingSphereScene.cc.
View newest version in sPHENIX GitHub at line 49 of file G4BoundingSphereScene.cc
References AccrueBoundingSphere(), G4PhysicalVolumeModel::CurtailDescent(), G4PseudoScene::fpCurrentObjectTransformation, fpModel, G4VSolid::GetExtent(), G4VisExtent::GetExtentCentre(), and G4VisExtent::GetExtentRadius().
void G4BoundingSphereScene::ResetBoundingSphere ()
Definition at line 64 of file G4BoundingSphereScene.cc.
View newest version in sPHENIX GitHub at line 64 of file G4BoundingSphereScene.cc
References fCentre, G4PseudoScene::fpCurrentObjectTransformation, and fRadius.
void G4BoundingSphereScene::SetCentre (const G4Point3D & centre) inline
Definition at line 54 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BoundingSphereScene.hh
References fCentre.
Member Data Documentation
G4Point3D G4BoundingSphereScene::fCentre private
Definition at line 70 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BoundingSphereScene.hh
Referenced by GetBoundingSphereExtent(), GetCentre(), ResetBoundingSphere(), and SetCentre().
G4VModel* G4BoundingSphereScene::fpModel private
Definition at line 69 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BoundingSphereScene.hh
Referenced by ProcessVolume().
G4double G4BoundingSphereScene::fRadius private
Definition at line 71 of file G4BoundingSphereScene.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BoundingSphereScene.hh
Referenced by GetBoundingSphereExtent(), GetRadius(), and ResetBoundingSphere().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4BoundingSphereScene.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4BoundingSphereScene.cc