ECCE @ EIC Software: G4tgbVolume Class Reference
G4tgbVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbVolume.hh>
Public Member Functions
G4tgbVolume ()
~G4tgbVolume ()
G4tgbVolume (G4tgrVolume *vol)
void ConstructG4Volumes (const G4tgrPlace *place, const G4LogicalVolume *parentLV)
G4VSolid * FindOrConstructG4Solid (const G4tgrSolid *vol)
G4LogicalVolume * ConstructG4LogVol (const G4VSolid *solid)
G4VPhysicalVolume * ConstructG4PhysVol (const G4tgrPlace *place, const G4LogicalVolume *currentLV, const G4LogicalVolume *parentLV)
void SetCutsInRange (G4LogicalVolume *logvol, std::map< G4String, G4double > cuts)
void SetCutsInEnergy (G4LogicalVolume *logvol, std::map< G4String, G4double > cuts)
void CheckNoSolidParams (const G4String &solidType, const unsigned int NoParamExpected, const unsigned int NoParam)
G4VSolid * BuildSolidForDivision (G4VSolid *parentSolid, EAxis axis)
const G4String & GetName () const
G4bool GetVisibility () const
const G4double * GetColour () const
Private Attributes
G4tgrVolume * theTgrVolume
G4AssemblyVolume * theG4AssemblyVolume
Detailed Description
Definition at line 65 of file G4tgbVolume.hh.
View newest version in sPHENIX GitHub at line 65 of file G4tgbVolume.hh
Constructor & Destructor Documentation
G4tgbVolume::G4tgbVolume ()
Definition at line 109 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 109 of file G4tgbVolume.cc
G4tgbVolume::~G4tgbVolume ()
Definition at line 116 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 116 of file G4tgbVolume.cc
G4tgbVolume::G4tgbVolume (G4tgrVolume * vol)
Definition at line 122 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 122 of file G4tgbVolume.cc
References theG4AssemblyVolume, and theTgrVolume.
Member Function Documentation
G4VSolid * G4tgbVolume::BuildSolidForDivision (G4VSolid * parentSolid, EAxis axis)
Definition at line 1183 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 1183 of file G4tgbVolume.cc
References FatalException, G4cout, G4endl, G4Exception(), G4GenericPolycone::GetCorner(), G4Tubs::GetDeltaPhiAngle(), G4Cons::GetDeltaPhiAngle(), G4GenericPolycone::GetEndPhi(), G4Polycone::GetEndPhi(), G4Polyhedra::GetEndPhi(), G4VSolid::GetEntityType(), G4VSolid::GetExtent(), G4Tubs::GetInnerRadius(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4GeometryTolerance::GetInstance(), GetName(), G4GenericPolycone::GetNumRZCorner(), G4Polyhedra::GetNumSide(), G4Polycone::GetOriginalParameters(), G4Polyhedra::GetOriginalParameters(), G4Tubs::GetOuterRadius(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4GenericPolycone::GetStartPhi(), G4Polycone::GetStartPhi(), G4Polyhedra::GetStartPhi(), G4Tubs::GetStartPhiAngle(), G4Cons::GetStartPhiAngle(), G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4tgrMessenger::GetVerboseLevel(), G4Box::GetXHalfLength(), G4Para::GetXHalfLength(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4VisExtent::GetXmax(), G4VisExtent::GetXmin(), G4Para::GetYHalfLength(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4VisExtent::GetYmax(), G4VisExtent::GetYmin(), G4Box::GetZHalfLength(), G4Trd::GetZHalfLength(), G4Para::GetZHalfLength(), G4Tubs::GetZHalfLength(), G4Cons::GetZHalfLength(), G4VisExtent::GetZmax(), G4VisExtent::GetZmin(), kXAxis, min, G4PolyconeHistorical::Num_z_planes, G4PolyhedraHistorical::Num_z_planes, CLHEP::Hep3Vector::phi(), r, G4PolyconeSideRZ::r, G4PolyconeHistorical::Rmax, G4PolyhedraHistorical::Rmax, G4PolyconeHistorical::Rmin, G4PolyhedraHistorical::Rmin, CLHEP::Hep3Vector::theta(), G4PolyconeSideRZ::z, z, G4PolyconeHistorical::Z_values, and G4PolyhedraHistorical::Z_values.
Referenced by ConstructG4PhysVol().
void G4tgbVolume::CheckNoSolidParams (const G4String & solidType, const unsigned int NoParamExpected, const unsigned int NoParam)
Definition at line 705 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 705 of file G4tgbVolume.cc
References G4UIcommand::ConvertToString(), FatalException, and G4Exception().
Referenced by FindOrConstructG4Solid().
G4LogicalVolume * G4tgbVolume::ConstructG4LogVol (const G4VSolid * solid)
Definition at line 724 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 724 of file G4tgbVolume.cc
References col, FatalException, G4tgbMaterialMgr::FindOrBuildG4Material(), G4cout, G4endl, G4Exception(), GetColour(), G4tgbMaterialMgr::GetInstance(), G4tgrVolume::GetMaterialName(), GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), G4tgrMessenger::GetVerboseLevel(), GetVisibility(), G4VisAttributes::SetColour(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and theTgrVolume.
Referenced by ConstructG4Volumes().
G4VPhysicalVolume * G4tgbVolume::ConstructG4PhysVol (const G4tgrPlace * place, const G4LogicalVolume * currentLV, const G4LogicalVolume * parentLV)
Definition at line 815 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 815 of file G4tgbVolume.cc
References kdfinder::abs(), G4AssemblyVolume::AddPlacedVolume(), BuildSolidForDivision(), CLHEP::HepRotation::colX(), CLHEP::HepRotation::colY(), CLHEP::HepRotation::colZ(), ConstructG4Volumes(), CLHEP::Hep3Vector::cross(), DivByNdiv, DivByNdivAndWidth, DivByWidth, FatalException, G4tgbVolumeMgr::FindG4LogVol(), G4tgbMaterialMgr::FindOrBuildG4Material(), G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix(), G4tgbVolumeMgr::FindVolume(), G4cerr, G4cout, G4endl, G4Exception(), G4tgbPlaceParameterisation::GetAxis(), G4tgrPlaceDivRep::GetAxis(), G4tgrVolume::GetCheckOverlaps(), G4tgrVolumeAssembly::GetComponentName(), G4tgrVolumeAssembly::GetComponentPos(), G4tgrVolumeAssembly::GetComponentRM(), G4tgrPlace::GetCopyNo(), G4tgrPlaceDivRep::GetDivType(), G4tgbRotationMatrixMgr::GetInstance(), G4tgbMaterialMgr::GetInstance(), G4tgbVolumeMgr::GetInstance(), G4tgrVolume::GetMaterialName(), GetName(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4tgbPlaceParameterisation::GetNCopies(), G4tgrPlaceDivRep::GetNDiv(), G4tgrVolumeAssembly::GetNoComponents(), G4tgrPlaceDivRep::GetOffset(), G4tgrPlaceParameterisation::GetParamType(), G4tgrVolumeDivision::GetPlaceDivision(), G4tgrPlace::GetPlacement(), G4tgrPlaceSimple::GetRotMatName(), G4LogicalVolume::GetSolid(), G4tgrPlace::GetType(), G4tgrVolume::GetType(), G4tgrMessenger::GetVerboseLevel(), G4tgrPlaceDivRep::GetWidth(), G4ReflectionFactory::Instance(), G4AssemblyVolume::MakeImprint(), G4ReflectionFactory::Place(), theG4AssemblyVolume, and theTgrVolume.
Referenced by ConstructG4Volumes().
void G4tgbVolume::ConstructG4Volumes (const G4tgrPlace * place, const G4LogicalVolume * parentLV)
Definition at line 130 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 130 of file G4tgbVolume.cc
References ConstructG4LogVol(), ConstructG4PhysVol(), ConstructG4Volumes(), G4tgbVolumeMgr::FindG4LogVol(), FindOrConstructG4Solid(), G4tgbVolumeMgr::FindVolume(), G4cout, G4endl, G4tgrVolumeMgr::GetChildren(), G4tgrPlace::GetCopyNo(), G4tgrVolumeMgr::GetInstance(), G4tgbVolumeMgr::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4tgrVolume::GetName(), GetName(), G4LogicalVolume::GetName(), G4tgrVolume::GetSolid(), G4tgrVolume::GetType(), G4tgrMessenger::GetVerboseLevel(), G4tgrPlace::GetVolume(), readPY::pl, G4tgbVolumeMgr::RegisterChildParentLVs(), G4tgbVolumeMgr::RegisterMe(), and theTgrVolume.
Referenced by G4tgbDetectorConstruction::Construct(), G4tgbDetectorBuilder::ConstructDetector(), ConstructG4PhysVol(), and ConstructG4Volumes().
G4VSolid * G4tgbVolume::FindOrConstructG4Solid (const G4tgrSolid * vol)
Definition at line 208 of file G4tgbVolume.cc.
View newest version in sPHENIX GitHub at line 208 of file G4tgbVolume.cc
References ABSOLUTE, G4TessellatedSolid::AddFacet(), CheckNoSolidParams(), G4UIcommand::ConvertToString(), deg, FatalException, G4tgbVolumeMgr::FindG4Solid(), G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix(), G4cout, G4endl, G4Exception(), G4GeometryTolerance::GetAngularTolerance(), G4VSolid::GetEntityType(), G4GeometryTolerance::GetInstance(), G4tgbRotationMatrixMgr::GetInstance(), G4tgbVolumeMgr::GetInstance(), G4tgrSolid::GetName(), G4tgrSolidBoolean::GetRelativePlace(), G4tgrSolid::GetRelativeRotMatName(), G4tgrSolidBoolean::GetSolid(), G4tgrSolid::GetSolidParams(), G4tgrSolid::GetType(), G4tgrMessenger::GetVerboseLevel(), offset, Acts::Test::phiDelta, pi, RELATIVE, and twopi.
Referenced by DicomIntersectVolume::BuildUserSolid(), and ConstructG4Volumes().
const G4double* G4tgbVolume::GetColour () const inline
Definition at line 109 of file G4tgbVolume.hh.
View newest version in sPHENIX GitHub at line 109 of file G4tgbVolume.hh
References G4tgrVolume::GetColour(), and theTgrVolume.
Referenced by ConstructG4LogVol().
const G4String& G4tgbVolume::GetName (void) const inline
Definition at line 107 of file G4tgbVolume.hh.
View newest version in sPHENIX GitHub at line 107 of file G4tgbVolume.hh
References G4tgrVolume::GetName(), and theTgrVolume.
Referenced by BuildSolidForDivision(), ConstructG4LogVol(), ConstructG4PhysVol(), ConstructG4Volumes(), and G4tgbVolumeMgr::RegisterMe().
G4bool G4tgbVolume::GetVisibility () const inline
Definition at line 108 of file G4tgbVolume.hh.
View newest version in sPHENIX GitHub at line 108 of file G4tgbVolume.hh
References G4tgrVolume::GetVisibility(), and theTgrVolume.
Referenced by ConstructG4LogVol().
void G4tgbVolume::SetCutsInEnergy (G4LogicalVolume * logvol, std::map< G4String, G4double > cuts)
void G4tgbVolume::SetCutsInRange (G4LogicalVolume * logvol, std::map< G4String, G4double > cuts)
Member Data Documentation
G4AssemblyVolume* G4tgbVolume::theG4AssemblyVolume private
Definition at line 116 of file G4tgbVolume.hh.
View newest version in sPHENIX GitHub at line 116 of file G4tgbVolume.hh
Referenced by ConstructG4PhysVol(), and G4tgbVolume().
G4tgrVolume* G4tgbVolume::theTgrVolume private
Definition at line 113 of file G4tgbVolume.hh.
View newest version in sPHENIX GitHub at line 113 of file G4tgbVolume.hh
Referenced by ConstructG4LogVol(), ConstructG4PhysVol(), ConstructG4Volumes(), G4tgbVolume(), GetColour(), GetName(), and GetVisibility().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbVolume.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbVolume.cc