ECCE @ EIC Software: G4ParticleHPField Class Reference
G4ParticleHPField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPField.hh>
Public Member Functions
G4ParticleHPField ()
~G4ParticleHPField ()
void InitY (G4int i, G4int n)
void SetData (G4int i, G4double x, G4int j, G4double y)
void SetEnergy (G4int i, G4double e)
void SetX (G4int i, G4double e)
void SetY (G4int i, G4int j, G4double x)
G4double GetEnergy (G4int i)
G4double GetX (G4int i)
G4double GetY (G4int i, G4int j)
G4ParticleHPFieldPoint & GetPoint (G4int i)
G4double GetY (G4double e, G4int j)
G4int GetFieldLength ()
void Dump ()
Private Member Functions
void Check (G4int i)
Private Attributes
G4ParticleHPFieldPoint * theData
G4int nEntries
G4int nPoints
Detailed Description
Definition at line 35 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPField.hh
Constructor & Destructor Documentation
G4ParticleHPField::G4ParticleHPField ()
Definition at line 37 of file G4ParticleHPField.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleHPField.cc
References nEntries, nPoints, G4ParticleHPFieldPoint::SetData(), and theData.
G4ParticleHPField::~G4ParticleHPField ()
Definition at line 45 of file G4ParticleHPField.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPField.cc
References theData.
Member Function Documentation
void G4ParticleHPField::Check (G4int i) private
Definition at line 104 of file G4ParticleHPField.cc.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleHPField.cc
References nEntries, nPoints, and theData.
Referenced by InitY(), SetData(), SetEnergy(), SetX(), and SetY().
void G4ParticleHPField::Dump ()
Definition at line 90 of file G4ParticleHPField.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleHPField.cc
References G4cout, G4endl, G4ParticleHPFieldPoint::GetDepth(), G4ParticleHPFieldPoint::GetX(), G4ParticleHPFieldPoint::GetY(), nEntries, and theData.
G4double G4ParticleHPField::GetEnergy (G4int i) inline
Definition at line 68 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPField.hh
References G4ParticleHPFieldPoint::GetX(), and theData.
G4int G4ParticleHPField::GetFieldLength () inline
Definition at line 75 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPField.hh
References nEntries.
G4ParticleHPFieldPoint& G4ParticleHPField::GetPoint (G4int i) inline
Definition at line 71 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPField.hh
References theData.
G4double G4ParticleHPField::GetX (G4int i) inline
Definition at line 69 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPField.hh
References G4ParticleHPFieldPoint::GetX(), and theData.
Referenced by GetY().
G4double G4ParticleHPField::GetY (G4int i, G4int j) inline
Definition at line 70 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPField.hh
References G4ParticleHPFieldPoint::GetY(), and theData.
G4double G4ParticleHPField::GetY (G4double e, G4int j)
Definition at line 47 of file G4ParticleHPField.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPField.cc
References e, G4ParticleHPFieldPoint::GetX(), GetX(), G4ParticleHPFieldPoint::GetY(), nEntries, theData, x, x1, x2, y, y1, and y2.
void G4ParticleHPField::InitY (G4int i, G4int n) inline
Definition at line 43 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPField.hh
References Check(), G4ParticleHPFieldPoint::InitY(), and theData.
void G4ParticleHPField::SetData (G4int i, G4double x, G4int j, G4double y) inline
Definition at line 48 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPField.hh
References Check(), G4ParticleHPFieldPoint::SetData(), and theData.
void G4ParticleHPField::SetEnergy (G4int i, G4double e) inline
Definition at line 53 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPField.hh
References Check(), G4ParticleHPFieldPoint::SetX(), and theData.
void G4ParticleHPField::SetX (G4int i, G4double e) inline
Definition at line 58 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPField.hh
References Check(), G4ParticleHPFieldPoint::SetX(), and theData.
void G4ParticleHPField::SetY (G4int i, G4int j, G4double x) inline
Definition at line 63 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPField.hh
References Check(), G4ParticleHPFieldPoint::SetY(), and theData.
Member Data Documentation
G4int G4ParticleHPField::nEntries private
Definition at line 84 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPField.hh
Referenced by Check(), Dump(), G4ParticleHPField(), GetFieldLength(), and GetY().
G4int G4ParticleHPField::nPoints private
Definition at line 85 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPField.hh
Referenced by Check(), and G4ParticleHPField().
G4ParticleHPFieldPoint* G4ParticleHPField::theData private
Definition at line 83 of file G4ParticleHPField.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPField.hh
Referenced by Check(), Dump(), G4ParticleHPField(), GetEnergy(), GetPoint(), GetX(), GetY(), InitY(), SetData(), SetEnergy(), SetX(), SetY(), and ~G4ParticleHPField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPField.cc