ECCE @ EIC Software: G4INCL::IChannel Class Reference
G4INCL::IChannel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLIChannel.hh>
Inherited by G4INCL::DeltaDecayChannel, G4INCL::DeltaProductionChannel, G4INCL::ElasticChannel, G4INCL::EtaNElasticChannel, G4INCL::EtaNToPiNChannel, G4INCL::EtaNToPiPiNChannel, G4INCL::NDeltaEtaProductionChannel, G4INCL::NDeltaOmegaProductionChannel, G4INCL::NDeltaToDeltaLKChannel, G4INCL::NDeltaToDeltaSKChannel, G4INCL::NDeltaToNLKChannel, G4INCL::NDeltaToNNKKbChannel, G4INCL::NDeltaToNSKChannel, G4INCL::NeutralKaonDecayChannel, G4INCL::NKbElasticChannel, G4INCL::NKbToL2piChannel, G4INCL::NKbToLpiChannel, G4INCL::NKbToNKb2piChannel, G4INCL::NKbToNKbChannel, G4INCL::NKbToNKbpiChannel, G4INCL::NKbToS2piChannel, G4INCL::NKbToSpiChannel, G4INCL::NKElasticChannel, G4INCL::NKToNK2piChannel, G4INCL::NKToNKChannel, G4INCL::NKToNKpiChannel, G4INCL::NLToNSChannel, G4INCL::NNEtaToMultiPionsChannel, G4INCL::NNOmegaToMultiPionsChannel, G4INCL::NNToMissingStrangenessChannel, G4INCL::NNToMultiPionsChannel, G4INCL::NNToNLK2piChannel, G4INCL::NNToNLKChannel, G4INCL::NNToNLKpiChannel, G4INCL::NNToNNEtaChannel, G4INCL::NNToNNKKbChannel, G4INCL::NNToNNOmegaChannel, G4INCL::NNToNSK2piChannel, G4INCL::NNToNSKChannel, G4INCL::NNToNSKpiChannel, G4INCL::NpiToLK2piChannel, G4INCL::NpiToLKChannel, G4INCL::NpiToLKpiChannel, G4INCL::NpiToMissingStrangenessChannel, G4INCL::NpiToNKKbChannel, G4INCL::NpiToSK2piChannel, G4INCL::NpiToSKChannel, G4INCL::NpiToSKpiChannel, G4INCL::NSToNLChannel, G4INCL::NSToNSChannel, G4INCL::NYElasticChannel, G4INCL::OmegaNElasticChannel, G4INCL::OmegaNToPiNChannel, G4INCL::OmegaNToPiPiNChannel, G4INCL::ParticleEntryChannel, G4INCL::PiNElasticChannel, G4INCL::PiNToDeltaChannel, G4INCL::PiNToEtaChannel, G4INCL::PiNToMultiPionsChannel, G4INCL::PiNToOmegaChannel, G4INCL::PionResonanceDecayChannel, G4INCL::RecombinationChannel, G4INCL::ReflectionChannel, G4INCL::SigmaZeroDecayChannel, G4INCL::StrangeAbsorbtionChannel, and G4INCL::TransmissionChannel.
Public Member Functions
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
virtual void fillFinalState (FinalState *fs)=0
Detailed Description
Channel generates a final state of an avatar.
Definition at line 57 of file G4INCLIChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLIChannel.hh
Constructor & Destructor Documentation
G4INCL::IChannel::IChannel () inline
Definition at line 59 of file G4INCLIChannel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLIChannel.hh
virtual G4INCL::IChannel::~IChannel () inline virtual
Definition at line 60 of file G4INCLIChannel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLIChannel.hh
Member Function Documentation
virtual void G4INCL::IChannel::fillFinalState (FinalState * fs) pure virtual
Implemented in G4INCL::RecombinationChannel, G4INCL::DeltaDecayChannel, G4INCL::ElasticChannel, G4INCL::PionResonanceDecayChannel, G4INCL::SigmaZeroDecayChannel, G4INCL::TransmissionChannel, G4INCL::ParticleEntryChannel, G4INCL::DeltaProductionChannel, G4INCL::NDeltaEtaProductionChannel, G4INCL::NDeltaOmegaProductionChannel, G4INCL::NeutralKaonDecayChannel, G4INCL::ReflectionChannel, G4INCL::StrangeAbsorbtionChannel, G4INCL::EtaNElasticChannel, G4INCL::EtaNToPiNChannel, G4INCL::EtaNToPiPiNChannel, G4INCL::NDeltaToDeltaLKChannel, G4INCL::NDeltaToDeltaSKChannel, G4INCL::NDeltaToNLKChannel, G4INCL::NDeltaToNNKKbChannel, G4INCL::NDeltaToNSKChannel, G4INCL::NKbElasticChannel, G4INCL::NKbToL2piChannel, G4INCL::NKbToLpiChannel, G4INCL::NKbToNKb2piChannel, G4INCL::NKbToNKbChannel, G4INCL::NKbToNKbpiChannel, G4INCL::NKbToS2piChannel, G4INCL::NKbToSpiChannel, G4INCL::NKElasticChannel, G4INCL::NKToNK2piChannel, G4INCL::NKToNKChannel, G4INCL::NKToNKpiChannel, G4INCL::NLToNSChannel, G4INCL::NNEtaToMultiPionsChannel, G4INCL::NNOmegaToMultiPionsChannel, G4INCL::NNToMissingStrangenessChannel, G4INCL::NNToMultiPionsChannel, G4INCL::NNToNLK2piChannel, G4INCL::NNToNLKChannel, G4INCL::NNToNLKpiChannel, G4INCL::NNToNNEtaChannel, G4INCL::NNToNNKKbChannel, G4INCL::NNToNNOmegaChannel, G4INCL::NNToNSK2piChannel, G4INCL::NNToNSKChannel, G4INCL::NNToNSKpiChannel, G4INCL::NpiToLK2piChannel, G4INCL::NpiToLKChannel, G4INCL::NpiToLKpiChannel, G4INCL::NpiToMissingStrangenessChannel, G4INCL::NpiToNKKbChannel, G4INCL::NpiToSK2piChannel, G4INCL::NpiToSKChannel, G4INCL::NpiToSKpiChannel, G4INCL::NSToNLChannel, G4INCL::NSToNSChannel, G4INCL::NYElasticChannel, G4INCL::OmegaNElasticChannel, G4INCL::OmegaNToPiNChannel, G4INCL::OmegaNToPiPiNChannel, G4INCL::PiNElasticChannel, G4INCL::PiNToDeltaChannel, G4INCL::PiNToEtaChannel, G4INCL::PiNToMultiPionsChannel, and G4INCL::PiNToOmegaChannel.
Referenced by G4INCL::SurfaceAvatar::fillFinalState(), G4INCL::IAvatar::fillFinalState(), and getFinalState().
FinalState * G4INCL::IChannel::getFinalState ()
Definition at line 50 of file G4INCLIChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLIChannel.cc
References fillFinalState(), and Acts::UnitConstants::fs.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLIChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLIChannel.cc