ECCE @ EIC Software: G4LENDCrossSection Class Reference
G4LENDCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDCrossSection.hh>
Public Member Functions
G4LENDCrossSection (const G4String name="")
~G4LENDCrossSection ()
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int, G4int, const G4Element *, const G4Material *)
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
void DumpLENDTargetInfo (G4bool force=false)
void ChangeDefaultEvaluation (G4String name_tmp)
void AllowNaturalAbundanceTarget ()
void AllowAnyCandidateTarget ()
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Protected Member Functions
void create_used_target_map ()
G4GIDI_target * get_target_from_map (G4int nuclear_code)
virtual G4double getLENDCrossSection (G4GIDI_target *, G4double, G4double)
G4double GetUltraLowEnergyExtrapolatedXS (G4double, G4double, G4double, G4double, G4double)
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes
G4ParticleDefinition * proj
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Private Member Functions
void recreate_used_target_map ()
Private Attributes
std::map< G4int,
G4LENDUsedTarget * > usedTarget_map
G4String default_evaluation
G4bool allow_nat
G4bool allow_any
G4LENDManager * lend_manager
Detailed Description
Definition at line 57 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 57 of file G4LENDCrossSection.hh
Constructor & Destructor Documentation
G4LENDCrossSection::G4LENDCrossSection (const G4String name = "")
Definition at line 118 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 118 of file G4LENDCrossSection.cc
References allow_any, allow_nat, default_evaluation, G4LENDManager::GetInstance(), lend_manager, MeV, proj, G4VCrossSectionDataSet::SetMaxKinEnergy(), and G4VCrossSectionDataSet::SetMinKinEnergy().
G4LENDCrossSection::~G4LENDCrossSection ()
Definition at line 137 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 137 of file G4LENDCrossSection.cc
References it, and usedTarget_map.
Member Function Documentation
void G4LENDCrossSection::AllowAnyCandidateTarget () inline
Definition at line 96 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LENDCrossSection.hh
void G4LENDCrossSection::AllowNaturalAbundanceTarget () inline
Definition at line 95 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 95 of file G4LENDCrossSection.hh
References allow_nat.
Referenced by G4NeutronLENDBuilder::Build(), and G4HadronElasticPhysicsLEND::ConstructProcess().
void G4LENDCrossSection::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VCrossSectionDataSet.
Reimplemented in G4LENDGammaCrossSection.
Definition at line 148 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 148 of file G4LENDCrossSection.cc
References create_used_target_map().
Referenced by G4LENDCombinedCrossSection::BuildPhysicsTable(), and G4LENDGammaCrossSection::BuildPhysicsTable().
void G4LENDCrossSection::ChangeDefaultEvaluation (G4String name_tmp) inline
Definition at line 94 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 94 of file G4LENDCrossSection.hh
References default_evaluation.
Referenced by G4NeutronLENDBuilder::Build(), and G4HadronElasticPhysicsLEND::ConstructProcess().
void G4LENDCrossSection::create_used_target_map () protected
Definition at line 310 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 310 of file G4LENDCrossSection.cc
References allow_any, allow_nat, G4LENDUsedTarget::AllowAny(), G4LENDUsedTarget::AllowNat(), default_evaluation, DumpLENDTargetInfo(), G4Element::GetElementTable(), G4Element::GetIsotope(), G4NistElementBuilder::GetIsotopeAbundance(), G4Isotope::Getm(), G4Isotope::GetN(), G4LENDManager::GetNistElementBuilder(), G4NistElementBuilder::GetNistFirstIsotopeN(), G4LENDManager::GetNucleusEncoding(), G4Element::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4NistElementBuilder::GetNumberOfNistIsotopes(), G4Isotope::GetZ(), G4Element::GetZ(), int(), lend_manager, proj, G4LENDManager::RequestChangeOfVerboseLevel(), usedTarget_map, and G4VCrossSectionDataSet::verboseLevel.
Referenced by G4LENDCombinedCrossSection::BuildPhysicsTable(), G4LENDGammaCrossSection::BuildPhysicsTable(), BuildPhysicsTable(), DumpLENDTargetInfo(), and recreate_used_target_map().
void G4LENDCrossSection::DumpLENDTargetInfo (G4bool force = false)
Definition at line 389 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 389 of file G4LENDCrossSection.cc
References create_used_target_map(), G4cout, G4endl, G4VCrossSectionDataSet::GetName(), G4ParticleDefinition::GetParticleName(), G4LENDManager::GetVerboseLevel(), it, lend_manager, proj, and usedTarget_map.
Referenced by create_used_target_map().
void G4LENDCrossSection::DumpPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 153 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 153 of file G4LENDCrossSection.cc
References barn, eV, G4cout, G4endl, G4Pow::GetInstance(), getLENDCrossSection(), G4VCrossSectionDataSet::GetName(), it, MeV, G4Pow::powA(), proj, and usedTarget_map.
G4GIDI_target * G4LENDCrossSection::get_target_from_map (G4int nuclear_code) protected
Definition at line 381 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 381 of file G4LENDCrossSection.cc
References usedTarget_map.
Referenced by GetIsoCrossSection(), and IsIsoApplicable().
G4double G4LENDCrossSection::GetIsoCrossSection (const G4DynamicParticle * dp, G4int iZ, G4int iA, const G4Isotope * isotope, const G4Element * , const G4Material * material) virtual
Reimplemented from G4VCrossSectionDataSet.
Reimplemented in G4LENDGammaCrossSection.
Definition at line 83 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 83 of file G4LENDCrossSection.cc
References FatalException, G4Exception(), get_target_from_map(), G4DynamicParticle::GetKineticEnergy(), getLENDCrossSection(), G4Isotope::Getm(), G4VCrossSectionDataSet::GetName(), G4LENDManager::GetNucleusEncoding(), G4Material::GetTemperature(), lend_manager, and message().
Referenced by G4LENDCombinedCrossSection::GetIsoCrossSection(), G4LENDGammaCrossSection::GetIsoCrossSection(), G4LENDCombinedCrossSection::SelectChannel(), and G4LENDGammaCrossSection::SelectChannel().
virtual G4double G4LENDCrossSection::getLENDCrossSection (G4GIDI_target * , G4double , G4double) inline protected virtual
Reimplemented in G4LENDInelasticCrossSection, G4LENDCaptureCrossSection, G4LENDElasticCrossSection, and G4LENDFissionCrossSection.
Definition at line 130 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 130 of file G4LENDCrossSection.hh
Referenced by DumpPhysicsTable(), and GetIsoCrossSection().
G4double G4LENDCrossSection::GetUltraLowEnergyExtrapolatedXS (G4double x1, G4double x2, G4double y1, G4double y2, G4double ke) protected
Definition at line 371 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 371 of file G4LENDCrossSection.cc
References a, b, and y1.
Referenced by G4LENDCaptureCrossSection::getLENDCrossSection(), G4LENDElasticCrossSection::getLENDCrossSection(), G4LENDFissionCrossSection::getLENDCrossSection(), and G4LENDInelasticCrossSection::getLENDCrossSection().
G4bool G4LENDCrossSection::IsIsoApplicable (const G4DynamicParticle * dp, G4int iZ, G4int iA, const G4Element * element, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 46 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 46 of file G4LENDCrossSection.cc
References get_target_from_map(), G4DynamicParticle::GetDefinition(), G4Element::GetIsotope(), G4DynamicParticle::GetKineticEnergy(), G4VCrossSectionDataSet::GetMaxKinEnergy(), G4VCrossSectionDataSet::GetMinKinEnergy(), G4Isotope::GetN(), G4LENDManager::GetNucleusEncoding(), G4Element::GetNumberOfIsotopes(), lend_manager, and proj.
void G4LENDCrossSection::recreate_used_target_map () private
Definition at line 296 of file G4LENDCrossSection.cc.
View newest version in sPHENIX GitHub at line 296 of file G4LENDCrossSection.cc
References create_used_target_map(), it, and usedTarget_map.
Member Data Documentation
G4bool G4LENDCrossSection::allow_any private
Definition at line 120 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 120 of file G4LENDCrossSection.hh
Referenced by create_used_target_map(), and G4LENDCrossSection().
G4bool G4LENDCrossSection::allow_nat private
Definition at line 119 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 119 of file G4LENDCrossSection.hh
Referenced by AllowNaturalAbundanceTarget(), create_used_target_map(), and G4LENDCrossSection().
G4String G4LENDCrossSection::default_evaluation private
Definition at line 118 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 118 of file G4LENDCrossSection.hh
Referenced by ChangeDefaultEvaluation(), create_used_target_map(), and G4LENDCrossSection().
G4LENDManager* G4LENDCrossSection::lend_manager private
Definition at line 122 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 122 of file G4LENDCrossSection.hh
Referenced by create_used_target_map(), DumpLENDTargetInfo(), G4LENDCrossSection(), GetIsoCrossSection(), and IsIsoApplicable().
G4ParticleDefinition* G4LENDCrossSection::proj protected
Definition at line 127 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 127 of file G4LENDCrossSection.hh
Referenced by create_used_target_map(), DumpLENDTargetInfo(), DumpPhysicsTable(), G4LENDCaptureCrossSection::G4LENDCaptureCrossSection(), G4LENDCombinedCrossSection::G4LENDCombinedCrossSection(), G4LENDCrossSection(), G4LENDElasticCrossSection::G4LENDElasticCrossSection(), G4LENDFissionCrossSection::G4LENDFissionCrossSection(), G4LENDGammaCrossSection::G4LENDGammaCrossSection(), G4LENDInelasticCrossSection::G4LENDInelasticCrossSection(), and IsIsoApplicable().
std::map< G4int , G4LENDUsedTarget* > G4LENDCrossSection::usedTarget_map private
Definition at line 96 of file G4LENDCrossSection.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LENDCrossSection.hh
Referenced by create_used_target_map(), DumpLENDTargetInfo(), DumpPhysicsTable(), get_target_from_map(), recreate_used_target_map(), and ~G4LENDCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDCrossSection.cc