ECCE @ EIC Software: G4UIcmdWithADoubleAndUnit Class Reference
G4UIcmdWithADoubleAndUnit Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWithADoubleAndUnit.hh>
Public Member Functions
G4UIcmdWithADoubleAndUnit (const char *theCommandPath, G4UImessenger *theMessenger)
virtual G4int DoIt (G4String parameterList)
G4String ConvertToStringWithBestUnit (G4double val)
G4String ConvertToStringWithDefaultUnit (G4double val)
void SetParameterName (const char *theName, G4bool omittable, G4bool currentAsDefault=false)
void SetDefaultValue (G4double defVal)
void SetUnitCategory (const char *unitCategory)
void SetUnitCandidates (const char *candidateList)
void SetDefaultUnit (const char *defUnit)
Public Member Functions inherited from G4UIcommand
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
size_t GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
size_t GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Static Public Member Functions
static G4double GetNewDoubleValue (const char *paramString)
static G4double GetNewDoubleRawValue (const char *paramString)
static G4double GetNewUnitValue (const char *paramString)
Static Public Member Functions inherited from G4UIcommand
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Additional Inherited Members
Protected Types inherited from G4UIcommand
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Protected Member Functions inherited from G4UIcommand
G4int CheckNewValue (const char *newValue)
Protected Attributes inherited from G4UIcommand
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Detailed Description
Definition at line 40 of file G4UIcmdWithADoubleAndUnit.hh.
View newest version in sPHENIX GitHub at line 40 of file G4UIcmdWithADoubleAndUnit.hh
Constructor & Destructor Documentation
G4UIcmdWithADoubleAndUnit::G4UIcmdWithADoubleAndUnit (const char * theCommandPath, G4UImessenger * theMessenger)
Definition at line 38 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 38 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIparameter::SetParameterName().
Member Function Documentation
G4String G4UIcmdWithADoubleAndUnit::ConvertToStringWithBestUnit (G4double val)
Definition at line 110 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 110 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::CategoryOf(), G4BestUnit, G4UIcommand::GetParameter(), and G4UIparameter::GetParameterCandidates().
Referenced by ConvertToStringWithDefaultUnit(), and G4MoleculeShootMessenger::GetCurrentValue().
G4String G4UIcmdWithADoubleAndUnit::ConvertToStringWithDefaultUnit (G4double val)
Definition at line 123 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 123 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::ConvertToString(), ConvertToStringWithBestUnit(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetParameter(), and G4UIparameter::IsOmittable().
G4int G4UIcmdWithADoubleAndUnit::DoIt (G4String parameterList) virtual
Reimplemented from G4UIcommand.
Definition at line 48 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 48 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::CategoryOf(), G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToString(), G4UIcommand::DoIt(), fParameterOutOfCandidates, G4UIcommand::GetParameter(), and G4UIcommand::ValueOf().
G4double G4UIcmdWithADoubleAndUnit::GetNewDoubleRawValue (const char * paramString) static
Definition at line 87 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 87 of file G4UIcmdWithADoubleAndUnit.cc
G4double G4UIcmdWithADoubleAndUnit::GetNewDoubleValue (const char * paramString) static
Definition at line 82 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 82 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::ConvertToDimensionedDouble().
Referenced by G4ModelCmdSetAuxPtsSize< M >::Apply(), G4ModelCmdSetStepPtsSize< M >::Apply(), HadrontherapyStepMaxMessenger::SetNewValue(), RE05StackingActionMessenger::SetNewValue(), XrayFluoStepMaxMessenger::SetNewValue(), PrimaryGeneratorMessenger::SetNewValue(), F04PrimaryGeneratorMessenger::SetNewValue(), PhysicsListMessenger::SetNewValue(), StepMaxMessenger::SetNewValue(), CCalPrimaryGeneratorMessenger::SetNewValue(), GammaKnifePhysicsListMessenger::SetNewValue(), ElectronBenchmarkDetectorMessenger::SetNewValue(), StepLimiterMessenger::SetNewValue(), GammaRayTelPhysicsListMessenger::SetNewValue(), F01PrimaryGeneratorMessenger::SetNewValue(), F02PrimaryGeneratorMessenger::SetNewValue(), F03PrimaryGeneratorMessenger::SetNewValue(), F04DetectorMessenger::SetNewValue(), F04FieldMessenger::SetNewValue(), WLSPrimaryGeneratorMessenger::SetNewValue(), XrayFluoPhysicsListMessenger::SetNewValue(), LXeDetectorMessenger::SetNewValue(), ExN02DetectorMessenger::SetNewValue(), ClusteringAlgoMessenger::SetNewValue(), OpNovicePrimaryGeneratorMessenger::SetNewValue(), ExN03DetectorMessenger::SetNewValue(), F01FieldMessenger::SetNewValue(), F02FieldMessenger::SetNewValue(), F03FieldMessenger::SetNewValue(), ExP01DetectorMessenger::SetNewValue(), B2aDetectorMessenger::SetNewValue(), B2bDetectorMessenger::SetNewValue(), G4MonopoleFieldMessenger::SetNewValue(), IORTStepMaxMessenger::SetNewValue(), F02DetectorMessenger::SetNewValue(), G4TBFieldMessenger::SetNewValue(), G4HadronicEPTestMessenger::SetNewValue(), ExErrorDetectorMessenger::SetNewValue(), F01DetectorMessenger::SetNewValue(), G4RTMessenger::SetNewValue(), F03DetectorMessenger::SetNewValue(), GammaRayTelDigitizerMessenger::SetNewValue(), G4GeometryMessenger::SetNewValue(), G4NeutronKillerMessenger::SetNewValue(), G4RadioactivationMessenger::SetNewValue(), XrayFluoDetectorMessenger::SetNewValue(), WLSDetectorMessenger::SetNewValue(), G4ParticleGunMessenger::SetNewValue(), IORTPhysicsListMessenger::SetNewValue(), ML2StepMaxMessenger::SetNewValue(), G4ErrorMessenger::SetNewValue(), G4NuclideTableMessenger::SetNewValue(), CML2Acc1Messenger::SetNewValue(), DMXDetectorMessenger::SetNewValue(), XrayFluoMercuryDetectorMessenger::SetNewValue(), GammaRayTelDetectorMessenger::SetNewValue(), XrayFluoPlaneDetectorMessenger::SetNewValue(), GammaRayTelPrimaryGeneratorMessenger::SetNewValue(), CML2Acc2Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), CML2PrimaryGenerationActionMessenger::SetNewValue(), doiPETAnalysisMessenger::SetNewValue(), GFlashShowerModelMessenger::SetNewValue(), CexmcPhysicsManagerMessenger::SetNewValue(), G4RadioactiveDecayBaseMessenger::SetNewValue(), CexmcPrimaryGeneratorActionMessenger::SetNewValue(), G4INCLXXInterfaceMessenger::SetNewValue(), CexmcParticleGunMessenger::SetNewValue(), CexmcChargeExchangeReconstructorMessenger::SetNewValue(), HistoManagerMessenger::SetNewValue(), CexmcReconstructorMessenger::SetNewValue(), doiPETDetectorConstructionMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4AdjointPhysicsMessenger::SetNewValue(), RMC01DetectorMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4EmExtraParametersMessenger::SetNewValue(), G4MoleculeShootMessenger::SetNewValue(), G4SchedulerMessenger::SetNewValue(), G4EmParametersMessenger::SetNewValue(), G4ProductionCutsTableMessenger::SetNewValue(), G4ParticlePropertyMessenger::SetNewValue(), G4UserPhysicsListMessenger::SetNewValue(), G4RadioactiveDecaymessenger::SetNewValue(), PrimaryKiller::SetNewValue(), G4GeneralParticleSourceMessenger::SetNewValue(), G4AdjointSimMessenger::SetNewValue(), and G4VisCommandViewerDolly::SetNewValue().
G4double G4UIcmdWithADoubleAndUnit::GetNewUnitValue (const char * paramString) static
Definition at line 98 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 98 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::ValueOf().
Referenced by G4GeometryMessenger::SetNewValue(), CML2Acc1Messenger::SetNewValue(), CML2AccSaturnMessenger::SetNewValue(), and CML2Acc2Messenger::SetNewValue().
void G4UIcmdWithADoubleAndUnit::SetDefaultUnit (const char * defUnit)
Definition at line 161 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 161 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::CategoryOf(), G4UIcommand::GetParameter(), G4UIparameter::SetDefaultValue(), G4UIparameter::SetOmittable(), and SetUnitCategory().
Referenced by CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcPhysicsManagerMessenger::CexmcPhysicsManagerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AcceleratorConstructionMessenger::CML2AcceleratorConstructionMessenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2PrimaryGenerationActionMessenger::CML2PrimaryGenerationActionMessenger(), ElectronBenchmarkDetectorMessenger::ElectronBenchmarkDetectorMessenger(), ExErrorDetectorMessenger::ExErrorDetectorMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F01FieldMessenger::F01FieldMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F02FieldMessenger::F02FieldMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F03FieldMessenger::F03FieldMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04FieldMessenger::F04FieldMessenger(), F04PhysicsListMessenger::F04PhysicsListMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), G4ErrorMessenger::G4ErrorMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4NuclideTableMessenger::G4NuclideTableMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger(), G4RTMessenger::G4RTMessenger(), G4SchedulerMessenger::G4SchedulerMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4TBFieldMessenger::G4TBFieldMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), GFlashShowerModelMessenger::GFlashShowerModelMessenger(), LXeDetectorMessenger::LXeDetectorMessenger(), OpNovicePrimaryGeneratorMessenger::OpNovicePrimaryGeneratorMessenger(), RE05StackingActionMessenger::RE05StackingActionMessenger(), G4GenericMessenger::Command::SetUnit(), WLSDetectorMessenger::WLSDetectorMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), and XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger().
void G4UIcmdWithADoubleAndUnit::SetDefaultValue (G4double defVal)
Definition at line 143 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 143 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::GetParameter(), and G4UIparameter::SetDefaultValue().
Referenced by CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CML2Acc1Messenger::CML2Acc1Messenger(), CML2Acc2Messenger::CML2Acc2Messenger(), CML2AcceleratorConstructionMessenger::CML2AcceleratorConstructionMessenger(), CML2AccSaturnMessenger::CML2AccSaturnMessenger(), CML2PrimaryGenerationActionMessenger::CML2PrimaryGenerationActionMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4NuclideTableMessenger::G4NuclideTableMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger(), G4RTMessenger::G4RTMessenger(), G4SchedulerMessenger::G4SchedulerMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), OpNovicePrimaryGeneratorMessenger::OpNovicePrimaryGeneratorMessenger(), and WLSPrimaryGeneratorMessenger::WLSPrimaryGeneratorMessenger().
void G4UIcmdWithADoubleAndUnit::SetParameterName (const char * theName, G4bool omittable, G4bool currentAsDefault = false)
Definition at line 135 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 135 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIparameter::SetCurrentAsDefault(), G4UIparameter::SetOmittable(), and G4UIparameter::SetParameterName().
Referenced by B2aDetectorMessenger::B2aDetectorMessenger(), B2bDetectorMessenger::B2bDetectorMessenger(), CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcPhysicsManagerMessenger::CexmcPhysicsManagerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), ClusteringAlgoMessenger::ClusteringAlgoMessenger(), G4GenericMessenger::DeclareMethodWithUnit(), G4GenericMessenger::DeclarePropertyWithUnit(), doiPETAnalysisMessenger::doiPETAnalysisMessenger(), doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger(), ElectronBenchmarkDetectorMessenger::ElectronBenchmarkDetectorMessenger(), ExErrorDetectorMessenger::ExErrorDetectorMessenger(), ExN02DetectorMessenger::ExN02DetectorMessenger(), ExN03DetectorMessenger::ExN03DetectorMessenger(), ExP01DetectorMessenger::ExP01DetectorMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F01FieldMessenger::F01FieldMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F02FieldMessenger::F02FieldMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F03FieldMessenger::F03FieldMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04FieldMessenger::F04FieldMessenger(), F04PhysicsListMessenger::F04PhysicsListMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), G4AdjointPhysicsMessenger::G4AdjointPhysicsMessenger(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4ModelCmdApplyDoubleAndUnit< M >::G4ModelCmdApplyDoubleAndUnit(), G4MonopoleFieldMessenger::G4MonopoleFieldMessenger(), G4NeutronKillerMessenger::G4NeutronKillerMessenger(), G4NuclideTableMessenger::G4NuclideTableMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticlePropertyMessenger::G4ParticlePropertyMessenger(), G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4TBFieldMessenger::G4TBFieldMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), GammaKnifePhysicsListMessenger::GammaKnifePhysicsListMessenger(), GammaRayTelDetectorMessenger::GammaRayTelDetectorMessenger(), GammaRayTelPhysicsListMessenger::GammaRayTelPhysicsListMessenger(), GFlashShowerModelMessenger::GFlashShowerModelMessenger(), HadrontherapyStepMaxMessenger::HadrontherapyStepMaxMessenger(), HistoManagerMessenger::HistoManagerMessenger(), IORTPhysicsListMessenger::IORTPhysicsListMessenger(), IORTStepMaxMessenger::IORTStepMaxMessenger(), LXeDetectorMessenger::LXeDetectorMessenger(), ML2StepMaxMessenger::ML2StepMaxMessenger(), OpNovicePrimaryGeneratorMessenger::OpNovicePrimaryGeneratorMessenger(), PhysicsListMessenger::PhysicsListMessenger(), PrimaryGeneratorMessenger::PrimaryGeneratorMessenger(), RE05StackingActionMessenger::RE05StackingActionMessenger(), G4GenericMessenger::Command::SetUnit(), StepLimiterMessenger::StepLimiterMessenger(), StepMaxMessenger::StepMaxMessenger(), WLSDetectorMessenger::WLSDetectorMessenger(), WLSPrimaryGeneratorMessenger::WLSPrimaryGeneratorMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), and XrayFluoStepMaxMessenger::XrayFluoStepMaxMessenger().
void G4UIcmdWithADoubleAndUnit::SetUnitCandidates (const char * candidateList)
Definition at line 154 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 154 of file G4UIcmdWithADoubleAndUnit.cc
References G4UIcommand::GetParameter(), and G4UIparameter::SetParameterCandidates().
Referenced by CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcPhysicsManagerMessenger::CexmcPhysicsManagerMessenger(), CexmcPrimaryGeneratorActionMessenger::CexmcPrimaryGeneratorActionMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), and SetUnitCategory().
void G4UIcmdWithADoubleAndUnit::SetUnitCategory (const char * unitCategory)
Definition at line 149 of file G4UIcmdWithADoubleAndUnit.cc.
View newest version in sPHENIX GitHub at line 149 of file G4UIcmdWithADoubleAndUnit.cc
References SetUnitCandidates(), and G4UIcommand::UnitsList().
Referenced by B2aDetectorMessenger::B2aDetectorMessenger(), B2bDetectorMessenger::B2bDetectorMessenger(), doiPETAnalysisMessenger::doiPETAnalysisMessenger(), doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger(), ExErrorDetectorMessenger::ExErrorDetectorMessenger(), ExN02DetectorMessenger::ExN02DetectorMessenger(), ExN03DetectorMessenger::ExN03DetectorMessenger(), ExP01DetectorMessenger::ExP01DetectorMessenger(), F04PhysicsListMessenger::F04PhysicsListMessenger(), G4AdjointPhysicsMessenger::G4AdjointPhysicsMessenger(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4GeometryMessenger::G4GeometryMessenger(), G4HadronicEPTestMessenger::G4HadronicEPTestMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4ModelCmdSetTimeSliceInterval< M >::G4ModelCmdSetTimeSliceInterval(), G4MonopoleFieldMessenger::G4MonopoleFieldMessenger(), G4NeutronKillerMessenger::G4NeutronKillerMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4SchedulerMessenger::G4SchedulerMessenger(), GammaKnifePhysicsListMessenger::GammaKnifePhysicsListMessenger(), GammaRayTelDetectorMessenger::GammaRayTelDetectorMessenger(), GammaRayTelPhysicsListMessenger::GammaRayTelPhysicsListMessenger(), GFlashShowerModelMessenger::GFlashShowerModelMessenger(), HadrontherapyStepMaxMessenger::HadrontherapyStepMaxMessenger(), HistoManagerMessenger::HistoManagerMessenger(), IORTPhysicsListMessenger::IORTPhysicsListMessenger(), IORTStepMaxMessenger::IORTStepMaxMessenger(), ML2StepMaxMessenger::ML2StepMaxMessenger(), OpNovicePrimaryGeneratorMessenger::OpNovicePrimaryGeneratorMessenger(), PhysicsListMessenger::PhysicsListMessenger(), PrimaryGeneratorMessenger::PrimaryGeneratorMessenger(), SetDefaultUnit(), G4GenericMessenger::Command::SetUnit(), StepLimiterMessenger::StepLimiterMessenger(), StepMaxMessenger::StepMaxMessenger(), WLSDetectorMessenger::WLSDetectorMessenger(), WLSPrimaryGeneratorMessenger::WLSPrimaryGeneratorMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), and XrayFluoStepMaxMessenger::XrayFluoStepMaxMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWithADoubleAndUnit.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIcmdWithADoubleAndUnit.cc