ECCE @ EIC Software: G4RPGPionInelastic Class Reference
G4RPGPionInelastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGPionInelastic.hh>
Public Member Functions
G4RPGPionInelastic (const G4String &modelName="RPGPionInelastic")
~G4RPGPionInelastic ()
Public Member Functions inherited from G4RPGInelastic
G4RPGInelastic (const G4String &modelName="RPGInelastic")
virtual ~G4RPGInelastic ()
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)=0
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Member Functions
G4int GetMultiplicityT12 (G4double KE) const
G4int GetMultiplicityT32 (G4double KE) const
std::vector< G4int > GetFSPartTypesForT32 (G4int mult, G4double KE, G4int tindex) const
std::vector< G4int > GetFSPartTypesForT12 (G4int mult, G4double KE, G4int tindex) const
std::vector< G4int > GetFSPartTypesForPipP (G4int mult, G4double KE) const
std::vector< G4int > GetFSPartTypesForPimN (G4int mult, G4double KE) const
std::vector< G4int > GetFSPartTypesForPipN (G4int mult, G4double KE) const
std::vector< G4int > GetFSPartTypesForPimP (G4int mult, G4double KE) const
Protected Member Functions inherited from G4RPGInelastic
G4double Pmltpc (G4int np, G4int nm, G4int nz, G4int n, G4double b, G4double c)
G4int Factorial (G4int n)
G4bool MarkLeadingStrangeParticle (const G4ReactionProduct &currentParticle, const G4ReactionProduct &targetParticle, G4ReactionProduct &leadParticle)
void SetUpPions (const G4int np, const G4int nm, const G4int nz, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
void GetNormalizationConstant (const G4double availableEnergy, G4double &n, G4double &anpn)
void CalculateMomenta (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, const G4DynamicParticle *originalTarget, G4ReactionProduct &modifiedOriginal, G4Nucleus &targetNucleus, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged, G4bool &targetHasChanged, G4bool quasiElastic)
void SetUpChange (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged)
std::pair< G4int, G4double > interpolateEnergy (G4double ke) const
G4int sampleFlat (std::vector< G4double > sigma) const
void CheckQnums (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4double Q, G4double B, G4double S)
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Static Protected Attributes
static const G4int pipPindex [8][2]
static const G4int pimPindex [8][2]
static const G4int T32_2bfs [2][2][2]
static const G4int T32_3bfs [2][7][3]
static const G4int T32_4bfs [2][15][4]
static const G4int T32_5bfs [2][24][5]
static const G4int T32_6bfs [2][5][6]
static const G4int T32_7bfs [2][6][7]
static const G4int T32_8bfs [2][7][8]
static const G4int T32_9bfs [2][8][9]
static const G4int T12_2bfs [2][5][2]
static const G4int T12_3bfs [2][13][3]
static const G4int T12_4bfs [2][22][4]
static const G4int T12_5bfs [2][31][5]
static const G4int T12_6bfs [2][6][6]
static const G4int T12_7bfs [2][7][7]
static const G4int T12_8bfs [2][8][8]
static const G4int T12_9bfs [2][9][9]
static G4ThreadLocal G4double pipPtot [30]
static G4ThreadLocal G4double pimPtot [30]
static G4ThreadLocal G4double t12_dSigma_dMult [8][30]
static G4ThreadLocal G4double t32_dSigma_dMult [8][30]
static const G4float pipPCrossSections [74][30]
static const G4float pimPCrossSections [101][30]
Additional Inherited Members
Protected Types inherited from G4RPGInelastic
enum {
pi0, pip, pim, kp,
km, k0, k0b, pro,
neu, lam, sp, s0,
sm, xi0, xim, om,
ap, an
}
Protected Attributes inherited from G4RPGInelastic
G4RPGFragmentation fragmentation
G4RPGTwoCluster twoCluster
G4RPGPionSuppression pionSuppression
G4RPGStrangeProduction strangeProduction
G4RPGTwoBody twoBody
G4ParticleDefinition * particleDef [18]
Detailed Description
Definition at line 41 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 41 of file G4RPGPionInelastic.hh
Constructor & Destructor Documentation
G4RPGPionInelastic::G4RPGPionInelastic (const G4String & modelName = "RPGPionInelastic")
Definition at line 32 of file G4RPGPionInelastic.cc.
View newest version in sPHENIX GitHub at line 32 of file G4RPGPionInelastic.cc
References GeV, k, pimPCrossSections, pimPindex, pimPtot, pipPCrossSections, pipPindex, pipPtot, G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), start(), t12_dSigma_dMult, and t32_dSigma_dMult.
G4RPGPionInelastic::~G4RPGPionInelastic () inline
Definition at line 47 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 47 of file G4RPGPionInelastic.hh
Member Function Documentation
std::vector<G4int> G4RPGPionInelastic::GetFSPartTypesForPimN (G4int mult, G4double KE) const inline protected
Definition at line 64 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RPGPionInelastic.hh
References GetFSPartTypesForT32().
Referenced by G4RPGPiMinusInelastic::InitialCollision().
std::vector<G4int> G4RPGPionInelastic::GetFSPartTypesForPimP (G4int mult, G4double KE) const inline protected
Definition at line 70 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RPGPionInelastic.hh
References GetFSPartTypesForT12().
Referenced by G4RPGPiMinusInelastic::InitialCollision().
std::vector<G4int> G4RPGPionInelastic::GetFSPartTypesForPipN (G4int mult, G4double KE) const inline protected
Definition at line 67 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RPGPionInelastic.hh
References GetFSPartTypesForT12().
Referenced by G4RPGPiPlusInelastic::InitialCollision().
std::vector<G4int> G4RPGPionInelastic::GetFSPartTypesForPipP (G4int mult, G4double KE) const inline protected
Definition at line 61 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RPGPionInelastic.hh
References GetFSPartTypesForT32().
Referenced by G4RPGPiPlusInelastic::InitialCollision().
std::vector< G4int > G4RPGPionInelastic::GetFSPartTypesForT12 (G4int mult, G4double KE, G4int tindex) const protected
Definition at line 185 of file G4RPGPionInelastic.cc.
View newest version in sPHENIX GitHub at line 185 of file G4RPGPionInelastic.cc
References G4cout, G4endl, G4RPGInelastic::interpolateEnergy(), k, pimPCrossSections, pimPindex, G4RPGInelastic::sampleFlat(), start(), T12_2bfs, T12_3bfs, T12_4bfs, T12_5bfs, T12_6bfs, T12_7bfs, T12_8bfs, and T12_9bfs.
Referenced by GetFSPartTypesForPimP(), and GetFSPartTypesForPipN().
std::vector< G4int > G4RPGPionInelastic::GetFSPartTypesForT32 (G4int mult, G4double KE, G4int tindex) const protected
Definition at line 137 of file G4RPGPionInelastic.cc.
View newest version in sPHENIX GitHub at line 137 of file G4RPGPionInelastic.cc
References G4cout, G4endl, G4RPGInelastic::interpolateEnergy(), k, pipPCrossSections, pipPindex, G4RPGInelastic::sampleFlat(), start(), T32_2bfs, T32_3bfs, T32_4bfs, T32_5bfs, T32_6bfs, T32_7bfs, T32_8bfs, and T32_9bfs.
Referenced by GetFSPartTypesForPimN(), and GetFSPartTypesForPipP().
G4int G4RPGPionInelastic::GetMultiplicityT12 (G4double KE) const protected
Definition at line 98 of file G4RPGPionInelastic.cc.
View newest version in sPHENIX GitHub at line 98 of file G4RPGPionInelastic.cc
References G4RPGInelastic::interpolateEnergy(), k, G4RPGInelastic::sampleFlat(), and t12_dSigma_dMult.
Referenced by G4RPGPiMinusInelastic::InitialCollision(), and G4RPGPiPlusInelastic::InitialCollision().
G4int G4RPGPionInelastic::GetMultiplicityT32 (G4double KE) const protected
Definition at line 117 of file G4RPGPionInelastic.cc.
View newest version in sPHENIX GitHub at line 117 of file G4RPGPionInelastic.cc
References G4RPGInelastic::interpolateEnergy(), k, G4RPGInelastic::sampleFlat(), and t32_dSigma_dMult.
Referenced by G4RPGPiMinusInelastic::InitialCollision(), and G4RPGPiPlusInelastic::InitialCollision().
Member Data Documentation
const G4float G4RPGPionInelastic::pimPCrossSections static protected
Definition at line 100 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 100 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic(), and GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::pimPindex static protected
Initial value:
=
 {{0, 4}, {5,17}, {18,39}, {40,70}, {71,76}, {77,83}, {84,91}, {92,100}}
Definition at line 74 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 74 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic(), and GetFSPartTypesForT12().
G4ThreadLocal G4double G4RPGPionInelastic::pimPtot static protected
Definition at line 95 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic().
const G4float G4RPGPionInelastic::pipPCrossSections static protected
Definition at line 99 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 99 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic(), and GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::pipPindex static protected
Initial value:
=
 {{0, 1}, {2, 8}, {9,23}, {24,47}, {48,52}, {53,58}, {59,65}, {66,73}}
Definition at line 73 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 73 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic(), and GetFSPartTypesForT32().
G4ThreadLocal G4double G4RPGPionInelastic::pipPtot static protected
Definition at line 94 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic().
const G4int G4RPGPionInelastic::T12_2bfs static protected
Initial value:
=
  {{{pro,pim}, {neu,pi0}, {lam,k0}, {s0,k0}, {sm,kp}},
   {{neu,pip}, {pro,pi0}, {lam,kp}, {s0,kp}, {sp,k0}}}
Definition at line 85 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_3bfs static protected
Initial value:
=
  {{{pro,pim,pi0}, {neu,pip,pim}, {neu,pi0,pi0}, {lam,k0,pi0},
    {lam,kp,pim},  {sm,k0,pip},   {sm,kp,pi0},   {sp,k0,pim},
    {s0,kp,pim},   {s0,k0,pi0},   {pro,k0,km},   {neu,kp,km},
    {neu,k0,k0b}},
   {{neu,pip,pi0}, {pro,pip,pim}, {pro,pi0,pi0}, {lam,kp,pi0},
    {lam,k0,pip},  {sp,kp,pim},   {sp,k0,pi0},   {sm,kp,pip},
    {s0,k0,pip},   {s0,kp,pi0},   {neu,kp,k0b},  {pro,k0,k0b},
    {pro,kp,km}}}
Definition at line 86 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_4bfs static protected
Initial value:
=
  {{{pro,pip,pim,pim}, {pro,pim,pi0,pi0}, {neu,pip,pim,pi0},
    {neu,pi0,pi0,pi0}, {lam,k0,pip,pim},  {lam,k0,pi0,pi0},
    {lam,kp,pim,pi0},  {s0,k0,pip,pim},   {s0,k0,pi0,pi0},
    {s0,kp,pim,pi0},   {sp,kp,pim,pim},   {sp,k0,pim,pi0},
    {sm,kp,pip,pim},   {sm,kp,pi0,pi0},   {sm,k0,pip,pi0},
    {pro,pim,kp,km},   {pro,pim,k0,k0b},  {pro,pi0,k0,km},
    {neu,pip,k0,km},   {neu,pi0,k0,k0b},  {neu,pi0,kp,km},
    {neu,pim,kp,k0b}},
   {{neu,pip,pip,pim},  {neu,pip,pi0,pi0}, {pro,pip,pim,pi0},
    {pro,pi0,pi0,pi0},  {lam,kp,pip,pim},  {lam,kp,pi0,pi0},
    {lam,k0,pip,pi0},   {s0,kp,pip,pim},   {s0,kp,pi0,pi0},
    {s0,k0,pip,pi0},    {sm,k0,pip,pip},   {sm,kp,pip,pi0},
    {sp,k0,pip,pim},    {sp,k0,pi0,pi0},   {sp,kp,pim,pi0},
    {neu,pip,k0,k0b},   {neu,pip,kp,km},   {neu,pi0,kp,k0b},
    {pro,pim,kp,k0b},   {pro,pi0,kp,km},   {pro,pi0,k0,k0b},
    {pro,pip,k0,km}}}
Definition at line 87 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_5bfs static protected
Initial value:
=
  {{{pro,pip,pim,pim,pi0}, {pro,pim,pi0,pi0,pi0}, {neu,pip,pip,pim,pim},
    {neu,pip,pim,pi0,pi0}, {neu,pi0,pi0,pi0,pi0}, {lam,k0,pip,pim,pi0},
    {lam,kp,pim,pi0,pi0},  {lam,kp,pip,pim,pim},  {lam,k0,pi0,pi0,pi0},
    {s0,kp,pip,pim,pim},   {s0,kp,pim,pi0,pi0},   {s0,k0,pip,pim,pi0},
    {s0,k0,pi0,pi0,pi0},   {sp,k0,pip,pim,pim},   {sp,k0,pim,pi0,pi0},
    {sp,kp,pim,pim,pi0},   {sm,k0,pip,pip,pim},   {sm,k0,pip,pi0,pi0},
    {sm,kp,pip,pim,pi0},   {sm,kp,pi0,pi0,pi0},   {pro,pim,pi0,kp,km},
    {pro,pim,pi0,k0,k0b},  {pro,pip,pim,k0,km},   {pro,pi0,pi0,k0,km},
    {pro,pim,pim,kp,k0b},  {neu,pip,pim,kp,km},   {neu,pip,pim,k0,k0b},
    {neu,pip,pi0,k0,km},   {neu,pim,pi0,kp,k0b},  {neu,pi0,pi0,k0,k0b},
    {neu,pi0,pi0,kp,km}},
   {{neu,pip,pip,pim,pi0}, {neu,pip,pi0,pi0,pi0}, {pro,pip,pip,pim,pim},
    {pro,pip,pim,pi0,pi0}, {pro,pi0,pi0,pi0,pi0}, {lam,kp,pip,pim,pi0},
    {lam,k0,pip,pi0,pi0},  {lam,k0,pip,pip,pim},  {lam,kp,pi0,pi0,pi0},
    {s0,k0,pip,pip,pim},   {s0,k0,pip,pi0,pi0},   {s0,kp,pip,pim,pi0},
    {s0,kp,pi0,pi0,pi0},   {sm,kp,pip,pip,pim},   {sm,kp,pip,pi0,pi0},
    {sm,k0,pip,pip,pi0},   {sp,kp,pip,pim,pim},   {sp,kp,pim,pi0,pi0},
    {sp,k0,pip,pim,pi0},   {sp,k0,pi0,pi0,pi0},   {neu,pip,pi0,k0,k0b},
    {neu,pip,pi0,kp,km},   {neu,pip,pim,kp,k0b},  {neu,pi0,pi0,kp,k0b},
    {neu,pip,pip,k0,km},   {pro,pip,pim,k0,k0b},  {pro,pip,pim,kp,km},
    {pro,pim,pi0,kp,k0b},  {pro,pip,pi0,k0,km},   {pro,pi0,pi0,kp,km},
    {pro,pi0,pi0,k0,k0b}}}
Definition at line 88 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_6bfs static protected
Initial value:
=
{{{pro,pip,pip,pim,pim,pim}, {pro,pip,pim,pim,pi0,pi0},
  {pro,pim,pi0,pi0,pi0,pi0}, {neu,pip,pip,pim,pim,pi0},
  {neu,pip,pim,pi0,pi0,pi0}, {neu,pi0,pi0,pi0,pi0,pi0}},
 {{neu,pip,pip,pip,pim,pim}, {neu,pip,pip,pim,pi0,pi0},
  {neu,pip,pi0,pi0,pi0,pi0}, {pro,pip,pip,pim,pim,pi0},
  {pro,pip,pim,pi0,pi0,pi0}, {pro,pi0,pi0,pi0,pi0,pi0}}}
Definition at line 89 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_7bfs static protected
Initial value:
=
{{{pro,pip,pip,pim,pim,pim,pi0}, {pro,pip,pim,pim,pi0,pi0,pi0},
  {pro,pim,pi0,pi0,pi0,pi0,pi0}, {neu,pip,pip,pip,pim,pim,pim},
  {neu,pip,pip,pim,pim,pi0,pi0}, {neu,pip,pim,pi0,pi0,pi0,pi0},
  {neu,pi0,pi0,pi0,pi0,pi0,pi0}},
 {{neu,pip,pip,pip,pim,pim,pi0}, {neu,pip,pip,pim,pi0,pi0,pi0},
  {neu,pip,pi0,pi0,pi0,pi0,pi0}, {pro,pip,pip,pip,pim,pim,pim},
  {pro,pip,pip,pim,pim,pi0,pi0}, {pro,pip,pim,pi0,pi0,pi0,pi0},
  {pro,pi0,pi0,pi0,pi0,pi0,pi0}}}
Definition at line 90 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_8bfs static protected
Initial value:
=
{{{pro,pip,pip,pip,pim,pim,pim,pim}, {pro,pip,pip,pim,pim,pim,pi0,pi0},
  {pro,pip,pim,pim,pi0,pi0,pi0,pi0}, {pro,pim,pi0,pi0,pi0,pi0,pi0,pi0},
  {neu,pi0,pi0,pi0,pi0,pi0,pi0,pi0}, {neu,pip,pim,pi0,pi0,pi0,pi0,pi0},
  {neu,pip,pip,pim,pim,pi0,pi0,pi0}, {neu,pip,pip,pip,pim,pim,pim,pi0}},
 {{neu,pip,pip,pip,pip,pim,pim,pim}, {neu,pip,pip,pip,pim,pim,pi0,pi0},
  {neu,pip,pip,pim,pi0,pi0,pi0,pi0}, {neu,pip,pi0,pi0,pi0,pi0,pi0,pi0},
  {pro,pi0,pi0,pi0,pi0,pi0,pi0,pi0}, {pro,pip,pim,pi0,pi0,pi0,pi0,pi0},
  {pro,pip,pip,pim,pim,pi0,pi0,pi0}, {pro,pip,pip,pip,pim,pim,pim,pi0}}}
Definition at line 91 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
const G4int G4RPGPionInelastic::T12_9bfs static protected
Initial value:
=
{{{pro,pip,pip,pip,pim,pim,pim,pim,pi0}, {pro,pip,pip,pim,pim,pim,pi0,pi0,pi0},
  {pro,pip,pim,pim,pi0,pi0,pi0,pi0,pi0}, {pro,pim,pi0,pi0,pi0,pi0,pi0,pi0,pi0},
  {neu,pi0,pi0,pi0,pi0,pi0,pi0,pi0,pi0}, {neu,pip,pim,pi0,pi0,pi0,pi0,pi0,pi0},
  {neu,pip,pip,pim,pim,pi0,pi0,pi0,pi0}, {neu,pip,pip,pip,pim,pim,pim,pi0,pi0},
  {neu,pip,pip,pip,pip,pim,pim,pim,pim}},
 {{neu,pip,pip,pip,pip,pim,pim,pim,pi0}, {neu,pip,pip,pip,pim,pim,pi0,pi0,pi0},
  {neu,pip,pip,pim,pi0,pi0,pi0,pi0,pi0}, {neu,pip,pi0,pi0,pi0,pi0,pi0,pi0,pi0},
  {pro,pi0,pi0,pi0,pi0,pi0,pi0,pi0,pi0}, {pro,pip,pim,pi0,pi0,pi0,pi0,pi0,pi0},
  {pro,pip,pip,pim,pim,pi0,pi0,pi0,pi0}, {pro,pip,pip,pip,pim,pim,pim,pi0,pi0},
  {pro,pip,pip,pip,pip,pim,pim,pim,pim}}}
Definition at line 92 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT12().
G4ThreadLocal G4double G4RPGPionInelastic::t12_dSigma_dMult static protected
Definition at line 96 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 96 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic(), and GetMultiplicityT12().
const G4int G4RPGPionInelastic::T32_2bfs static protected
Initial value:
=
  {{{pro,pip}, {sp,kp}},
   {{neu,pim}, {sm,k0}}}
Definition at line 76 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_3bfs static protected
Initial value:
=
  {{{pro,pip,pi0}, {neu,pip,pip}, {sp,kp,pi0}, {sp,k0,pip},
    {s0,kp,pip},   {lam,kp,pip},  {pro,kp,k0b}},
   {{neu,pim,pi0}, {pro,pim,pim}, {sm,k0,pi0}, {sm,kp,pim},
    {s0,k0,pim},   {lam,k0,pim},  {neu,k0,km}}}
Definition at line 77 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_4bfs static protected
Initial value:
=
  {{{pro,pip,pip,pim},{pro,pip,pi0,pi0},{neu,pip,pip,pi0},
    {sp,kp,pip,pim},  {sp,kp,pi0,pi0},  {sp,k0,pip,pi0},
    {s0,k0,pip,pip},  {s0,kp,pip,pi0},  {lam,kp,pip,pi0},
    {lam,k0,pip,pip}, {sm,kp,pip,pip},  {pro,pip,kp,km},
    {pro,pip,k0,k0b}, {pro,pi0,kp,k0b}, {neu,pip,kp,k0b}},
   {{neu,pip,pim,pim},{neu,pim,pi0,pi0},{pro,pim,pim,pi0},
    {sm,k0,pip,pim},  {sm,k0,pi0,pi0},  {sm,kp,pim,pi0},
    {s0,kp,pim,pim},  {s0,k0,pim,pi0},  {lam,k0,pim,pi0},
    {lam,kp,pim,pim}, {sp,k0,pim,pim},  {neu,pim,k0,k0b},
    {neu,pim,kp,km},  {neu,pi0,k0,km},  {pro,pim,k0,km}}}
Definition at line 78 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 78 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_5bfs static protected
Initial value:
=
  {{{pro,pip,pip,pim,pi0}, {pro,pip,pi0,pi0,pi0}, {neu,pip,pip,pip,pim},
    {neu,pip,pip,pi0,pi0}, {sp,kp,pip,pim,pi0},   {sp,kp,pi0,pi0,pi0},
    {sp,k0,pip,pip,pim},   {sp,k0,pip,pi0,pi0},   {lam,k0,pip,pip,pi0},
    {lam,kp,pip,pip,pim},  {lam,kp,pip,pi0,pi0},  {s0,kp,pip,pip,pim},
    {s0,kp,pip,pi0,pi0},   {s0,k0,pip,pip,pi0},   {sm,kp,pip,pip,pi0},
    {sm,k0,pip,pip,pip},   {pro,pip,pim,kp,k0b},  {pro,pip,pip,k0,km},
    {pro,pip,pi0,kp,km},   {pro,pip,pi0,k0,k0b},  {pro,pi0,pi0,kp,k0b},
    {neu,pip,pip,kp,km},   {neu,pip,pip,k0,k0b},  {neu,pip,pi0,kp,k0b}},
   {{neu,pip,pim,pim,pi0}, {neu,pim,pi0,pi0,pi0}, {pro,pip,pim,pim,pim},
    {pro,pim,pim,pi0,pi0}, {sm,k0,pip,pim,pi0},   {sm,k0,pi0,pi0,pi0},
    {sm,kp,pip,pim,pim},   {sm,kp,pim,pi0,pi0},   {lam,kp,pim,pim,pi0},
    {lam,k0,pip,pim,pim},  {lam,k0,pim,pi0,pi0},  {s0,k0,pip,pim,pim},
    {s0,k0,pim,pi0,pi0},   {s0,kp,pim,pim,pi0},   {sp,k0,pim,pim,pi0},
    {sp,kp,pim,pim,pim},   {neu,pip,pim,k0,km},   {neu,pim,pim,kp,k0b},
    {neu,pim,pi0,k0,k0b},  {neu,pim,pi0,kp,km},   {neu,pi0,pi0,k0,km},
    {pro,pim,pim,k0,k0b},  {pro,pim,pim,kp,km},   {pro,pim,pi0,k0,km}}}
Definition at line 79 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_6bfs static protected
Initial value:
=
{{{pro,pip,pip,pip,pim,pim}, {pro,pip,pip,pim,pi0,pi0},
  {pro,pip,pi0,pi0,pi0,pi0}, {neu,pip,pip,pi0,pi0,pi0},
  {neu,pip,pip,pip,pim,pi0}},
 {{neu,pip,pip,pim,pim,pim}, {neu,pip,pim,pim,pi0,pi0},
  {neu,pim,pi0,pi0,pi0,pi0}, {pro,pim,pim,pi0,pi0,pi0},
  {pro,pip,pim,pim,pim,pi0}}}
Definition at line 80 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_7bfs static protected
Initial value:
=
{{{pro,pip,pip,pip,pim,pim,pi0}, {pro,pip,pip,pim,pi0,pi0,pi0},
  {pro,pip,pi0,pi0,pi0,pi0,pi0}, {neu,pip,pip,pip,pip,pim,pim},
  {neu,pip,pip,pip,pim,pi0,pi0}, {neu,pip,pip,pi0,pi0,pi0,pi0}},
 {{neu,pip,pip,pim,pim,pim,pi0}, {neu,pip,pim,pim,pi0,pi0,pi0},
  {neu,pim,pi0,pi0,pi0,pi0,pi0}, {pro,pip,pip,pim,pim,pim,pim},
  {pro,pip,pim,pim,pim,pi0,pi0}, {pro,pim,pim,pi0,pi0,pi0,pi0}}}
Definition at line 81 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_8bfs static protected
Initial value:
=
{{{pro,pip,pip,pip,pip,pim,pim,pim}, {pro,pip,pip,pip,pim,pim,pi0,pi0},
  {pro,pip,pip,pim,pi0,pi0,pi0,pi0}, {pro,pip,pi0,pi0,pi0,pi0,pi0,pi0},
  {neu,pip,pip,pip,pip,pim,pim,pi0}, {neu,pip,pip,pip,pim,pi0,pi0,pi0},
  {neu,pip,pip,pi0,pi0,pi0,pi0,pi0}},
 {{neu,pip,pip,pip,pim,pim,pim,pim}, {neu,pip,pip,pim,pim,pim,pi0,pi0},
  {neu,pip,pim,pim,pi0,pi0,pi0,pi0}, {neu,pim,pi0,pi0,pi0,pi0,pi0,pi0},
  {pro,pip,pip,pim,pim,pim,pim,pi0}, {pro,pip,pim,pim,pim,pi0,pi0,pi0},
  {pro,pim,pim,pi0,pi0,pi0,pi0,pi0}}}
Definition at line 82 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
const G4int G4RPGPionInelastic::T32_9bfs static protected
Initial value:
=
{{{pro,pip,pip,pip,pip,pim,pim,pim,pi0}, {pro,pip,pip,pip,pim,pim,pi0,pi0,pi0},
  {pro,pip,pip,pim,pi0,pi0,pi0,pi0,pi0}, {pro,pip,pi0,pi0,pi0,pi0,pi0,pi0,pi0},
  {neu,pip,pip,pip,pip,pip,pim,pim,pim}, {neu,pip,pip,pip,pip,pim,pim,pi0,pi0},
  {neu,pip,pip,pip,pim,pi0,pi0,pi0,pi0}, {neu,pip,pip,pi0,pi0,pi0,pi0,pi0,pi0}},
 {{neu,pip,pip,pip,pim,pim,pim,pim,pi0}, {neu,pip,pip,pim,pim,pim,pi0,pi0,pi0},
  {neu,pip,pim,pim,pi0,pi0,pi0,pi0,pi0}, {neu,pim,pi0,pi0,pi0,pi0,pi0,pi0,pi0},
  {pro,pip,pip,pip,pim,pim,pim,pim,pim}, {pro,pip,pip,pim,pim,pim,pim,pi0,pi0},
  {pro,pip,pim,pim,pim,pi0,pi0,pi0,pi0}, {pro,pim,pim,pi0,pi0,pi0,pi0,pi0,pi0}}}
Definition at line 83 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RPGPionInelastic.hh
Referenced by GetFSPartTypesForT32().
G4ThreadLocal G4double G4RPGPionInelastic::t32_dSigma_dMult static protected
Definition at line 97 of file G4RPGPionInelastic.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RPGPionInelastic.hh
Referenced by G4RPGPionInelastic(), and GetMultiplicityT32().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGPionInelastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/src/G4RPGPionInelastic.cc