ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Polyhedra.cc File Reference
pyG4Polyhedra.cc File Reference
#include <boost/python.hpp>
#include <memory>
#include "G4Polyhedra.hh"
Namespaces
namespace pyG4Polyhedra
Functions
G4Polyhedra * pyG4Polyhedra::f1_CreatePolyhedra (const G4String &name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numZPlanes, const std::vector< G4double > &zPlane, const std::vector< G4double > &rInner, const std::vector< G4double > &rOuter)
G4Polyhedra * pyG4Polyhedra::f2_CreatePolyhedra (const G4String &name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numRZ, const std::vector< G4double > &r, const std::vector< G4double > &z)
void export_G4Polyhedra ()
Function Documentation
void export_G4Polyhedra ()
Definition at line 92 of file pyG4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 92 of file pyG4Polyhedra.cc
References pyG4Polyhedra::f1_CreatePolyhedra(), pyG4Polyhedra::f2_CreatePolyhedra(), G4Polyhedra::GetEndPhi(), G4Polyhedra::GetNumRZCorner(), G4Polyhedra::GetNumSide(), G4Polyhedra::GetStartPhi(), G4Polyhedra::IsGeneric(), and G4Polyhedra::IsOpen().
Referenced by BOOST_PYTHON_MODULE().