ECCE @ EIC Software: pyG4Material Namespace Reference
pyG4Material Namespace Reference
Functions
list f_GetFractionVector (const G4Material *material)
list f_GetAtomsVector (const G4Material *material)
list f_GetVecNbOfAtomsPerVolume (const G4Material *material)
list f_GetAtomicNumDensityVector (const G4Material *material)
void Print (G4Material &mat)
Variables
void(G4Material::* f1_AddElement)(G4Element *, G4int) = &G4Material::AddElement
void(G4Material::* f2_AddElement)(G4Element *, G4double) = &G4Material::AddElement
G4Material *(* f1_GetMaterial)(const G4String &, G4bool) = &G4Material::GetMaterial
G4Material *(* f2_GetMaterial)(G4double, G4double, G4double) = &G4Material::GetMaterial
G4Material *(* f3_GetMaterial)(size_t, G4double) = &G4Material::GetMaterial
Function Documentation
list pyG4Material::f_GetAtomicNumDensityVector (const G4Material * material)
Definition at line 91 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 91 of file pyG4Material.cc
Referenced by export_G4Material().
list pyG4Material::f_GetAtomsVector (const G4Material * material)
Definition at line 69 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 69 of file pyG4Material.cc
Referenced by export_G4Material().
list pyG4Material::f_GetFractionVector (const G4Material * material)
Definition at line 58 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 58 of file pyG4Material.cc
Referenced by export_G4Material().
list pyG4Material::f_GetVecNbOfAtomsPerVolume (const G4Material * material)
Definition at line 80 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 80 of file pyG4Material.cc
Referenced by export_G4Material().
void pyG4Material::Print (G4Material & mat)
Definition at line 103 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 103 of file pyG4Material.cc
References G4cout, and mat.
Variable Documentation
void(G4Material::* pyG4Material::f1_AddElement)(G4Element *, G4int) = &G4Material::AddElement
Definition at line 42 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 42 of file pyG4Material.cc
Referenced by export_G4Material().
G4Material*(* pyG4Material::f1_GetMaterial)(const G4String &, G4bool) = &G4Material::GetMaterial
Definition at line 48 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 48 of file pyG4Material.cc
Referenced by export_G4Material().
void(G4Material::* pyG4Material::f2_AddElement)(G4Element *, G4double) = &G4Material::AddElement
Definition at line 44 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 44 of file pyG4Material.cc
Referenced by export_G4Material().
G4Material*(* pyG4Material::f2_GetMaterial)(G4double, G4double, G4double) = &G4Material::GetMaterial
Definition at line 50 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 50 of file pyG4Material.cc
Referenced by export_G4Material().
G4Material*(* pyG4Material::f3_GetMaterial)(size_t, G4double) = &G4Material::GetMaterial
Definition at line 52 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 52 of file pyG4Material.cc
Referenced by export_G4Material().