ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/PoPs_private.h File Reference
PoPs_private.h File Reference
Classes
struct unitsDB_s
struct PoPs_s
Typedefs
typedef struct unitsDB_s unitsDB
typedef struct PoPs_s PoPs
Functions
int PoPs_releasePrivate (statusMessageReporting *smr)
char const * unitsDB_addUnitIfNeeded (statusMessageReporting *smr, char const *unit)
int unitsDB_index (statusMessageReporting *smr, char const *unit)
char const * unitsDB_stringFromIndex (statusMessageReporting *smr, int index)
Typedef Documentation
typedef struct PoPs_s PoPs
Definition at line 15 of file PoPs_private.h.
View newest version in sPHENIX GitHub at line 15 of file PoPs_private.h
typedef struct unitsDB_s unitsDB
Definition at line 14 of file PoPs_private.h.
View newest version in sPHENIX GitHub at line 14 of file PoPs_private.h
Function Documentation
int PoPs_releasePrivate (statusMessageReporting * smr)
Definition at line 98 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 98 of file PoPs.cc
References PoPs_s::allocated, PoPs_s::numberOfParticles, PoP_free(), PoPs_s::pops, popsRoot, smr_freeMemory(), PoPs_s::sorted, and unitsDB_release().
Referenced by PoPs_release().
char const* unitsDB_addUnitIfNeeded (statusMessageReporting * smr, char const * unit)
Definition at line 700 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 700 of file PoPs.cc
References unitsDB_s::allocated, unitsDB_s::numberOfUnits, smr_allocateCopyString2, smr_freeMemory(), smr_malloc2, unitsRoot, and unitsDB_s::unsorted.
Referenced by PoP_makeParticle(), and PoPs_particleLoadInfo().
int unitsDB_index (statusMessageReporting * smr, char const * unit)
Definition at line 725 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 725 of file PoPs.cc
References unitsDB_s::numberOfUnits, unitsRoot, and unitsDB_s::unsorted.
char const* unitsDB_stringFromIndex (statusMessageReporting * smr, int index)
Definition at line 737 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 737 of file PoPs.cc
References unitsDB_s::numberOfUnits, PoPs_smr_ID, smr_setReportError2, unitsRoot, and unitsDB_s::unsorted.