ECCE @ EIC Software: XrayFluoMercuryPrimaryGeneratorAction Class Reference
XrayFluoMercuryPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoMercuryPrimaryGeneratorAction.hh>
Public Member Functions
XrayFluoMercuryPrimaryGeneratorAction (const XrayFluoMercuryDetectorConstruction *)
~XrayFluoMercuryPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
void SetGlobalFlag (G4bool val)
void SetSpectrum (G4String val)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * particleGun
const
XrayFluoMercuryDetectorConstruction * XrayFluoDetector
XrayFluoMercuryPrimaryGeneratorMessenger * gunMessenger
XrayFluoRunAction * runManager
G4bool globalFlag
G4String spectrum
Detailed Description
Definition at line 51 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 51 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction (const XrayFluoMercuryDetectorConstruction * XrayFluoDC)
Definition at line 53 of file XrayFluoMercuryPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 53 of file XrayFluoMercuryPrimaryGeneratorAction.cc
References cm, G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleTable::GetParticleTable(), XrayFluoMercuryDetectorConstruction::GetWorldSizeZ(), gunMessenger, keV, particle, particleGun, runManager, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and XrayFluoDetector.
XrayFluoMercuryPrimaryGeneratorAction::~XrayFluoMercuryPrimaryGeneratorAction ()
Definition at line 87 of file XrayFluoMercuryPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 87 of file XrayFluoMercuryPrimaryGeneratorAction.cc
References G4cout, G4endl, gunMessenger, particleGun, and runManager.
Member Function Documentation
void XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 99 of file XrayFluoMercuryPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 99 of file XrayFluoMercuryPrimaryGeneratorAction.cc
References a, alpha, XrayFluoAnalysisManager::analysePrimaryGenerator(), static_analysis_results::analysis(), deg, XrayFluoDataSet::FindValue(), G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), XrayFluoRunAction::GetData(), XrayFluoRunAction::GetDataSum(), XrayFluoRunAction::GetEnergies(), XrayFluoRunAction::GetGammaSet(), XrayFluoAnalysisManager::getInstance(), XrayFluoMercuryDetectorConstruction::GetMercuryDia(), XrayFluoMercuryDetectorConstruction::GetOpticAperture(), XrayFluoMercuryDetectorConstruction::GetOrbitInclination(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleDefinition::GetParticleName(), XrayFluoMercuryDetectorConstruction::GetSunDia(), XrayFluoMercuryDetectorConstruction::GetWorldSizeZ(), globalFlag, keV, m, particle, particleGun, phi, pi, rad, runManager, G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), spectrum, sum, theta(), XrayFluoDetector, and G4InuclParticleNames::z0.
void XrayFluoMercuryPrimaryGeneratorAction::SetGlobalFlag (G4bool val) inline
Definition at line 63 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 63 of file XrayFluoMercuryPrimaryGeneratorAction.hh
References globalFlag.
Referenced by XrayFluoMercuryPrimaryGeneratorMessenger::SetNewValue().
void XrayFluoMercuryPrimaryGeneratorAction::SetSpectrum (G4String val) inline
Definition at line 73 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoMercuryPrimaryGeneratorAction.hh
References spectrum.
Referenced by XrayFluoMercuryPrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4bool XrayFluoMercuryPrimaryGeneratorAction::globalFlag private
Definition at line 91 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 91 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetGlobalFlag().
XrayFluoMercuryPrimaryGeneratorMessenger* XrayFluoMercuryPrimaryGeneratorAction::gunMessenger private
Definition at line 86 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Referenced by XrayFluoMercuryPrimaryGeneratorAction(), and ~XrayFluoMercuryPrimaryGeneratorAction().
G4ParticleGun* XrayFluoMercuryPrimaryGeneratorAction::particleGun private
Definition at line 73 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction(), and ~XrayFluoMercuryPrimaryGeneratorAction().
XrayFluoRunAction* XrayFluoMercuryPrimaryGeneratorAction::runManager private
Definition at line 87 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 87 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction(), and ~XrayFluoMercuryPrimaryGeneratorAction().
G4String XrayFluoMercuryPrimaryGeneratorAction::spectrum private
Definition at line 106 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 106 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetSpectrum().
const XrayFluoMercuryDetectorConstruction* XrayFluoMercuryPrimaryGeneratorAction::XrayFluoDetector private
Definition at line 83 of file XrayFluoMercuryPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 83 of file XrayFluoMercuryPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and XrayFluoMercuryPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoMercuryPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoMercuryPrimaryGeneratorAction.cc