ECCE @ EIC Software: CLHEP::HepJamesRandom Class Reference
CLHEP::HepJamesRandom Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/JamesRandom.h>
Public Member Functions
HepJamesRandom (std::istream &is)
HepJamesRandom ()
HepJamesRandom (long seed)
HepJamesRandom (int rowIndex, int colIndex)
virtual ~HepJamesRandom ()
double flat ()
void flatArray (const int size, double *vect)
void setSeed (long seed, int dum=0)
void setSeeds (const long *seeds, int dum=0)
void saveStatus (const char filename[]="JamesRand.conf") const
void restoreStatus (const char filename[]="JamesRand.conf")
void showStatus () const
operator double ()
operator float ()
operator unsigned int ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Public Attributes
static const unsigned int VECTOR_STATE_SIZE = 202
Private Attributes
double u [97]
double c
double cd
double cm
int i97
int j97
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Definition at line 43 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 43 of file JamesRandom.h
Constructor & Destructor Documentation
CLHEP::HepJamesRandom::HepJamesRandom (std::istream & is)
Definition at line 102 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 102 of file JamesRandom.cc
CLHEP::HepJamesRandom::HepJamesRandom ()
Definition at line 69 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 69 of file JamesRandom.cc
References kdfinder::abs(), CLHEP::HepRandom::getTheTableSeeds(), mask, seed, setSeed(), setSeeds(), and CLHEP::HepRandomEngine::theSeed.
CLHEP::HepJamesRandom::HepJamesRandom (long seed)
Definition at line 62 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 62 of file JamesRandom.cc
References setSeed(), setSeeds(), and CLHEP::HepRandomEngine::theSeed.
CLHEP::HepJamesRandom::HepJamesRandom (int rowIndex, int colIndex)
Definition at line 86 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 86 of file JamesRandom.cc
References kdfinder::abs(), col, CLHEP::HepRandom::getTheTableSeeds(), mask, seed, setSeed(), setSeeds(), and CLHEP::HepRandomEngine::theSeed.
CLHEP::HepJamesRandom::~HepJamesRandom () virtual
Definition at line 108 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 108 of file JamesRandom.cc
Member Function Documentation
std::string CLHEP::HepJamesRandom::beginTag () static
Definition at line 329 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 329 of file JamesRandom.cc
static std::string CLHEP::HepJamesRandom::engineName () inline static
Definition at line 91 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 91 of file JamesRandom.h
Referenced by restoreStatus().
double CLHEP::HepJamesRandom::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 235 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 235 of file JamesRandom.cc
References c, cd, cm, i97, j97, and u.
Referenced by flatArray().
void CLHEP::HepJamesRandom::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 260 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 260 of file JamesRandom.cc
References flat().
std::istream & CLHEP::HepJamesRandom::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 312 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 312 of file JamesRandom.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::HepJamesRandom::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 377 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 377 of file JamesRandom.cc
References getState().
std::istream & CLHEP::HepJamesRandom::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 333 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 333 of file JamesRandom.cc
References c, cd, cm, i97, j97, CLHEP::MarkerLen, CLHEP::possibleKeywordInput(), CLHEP::HepRandomEngine::theSeed, u, v, and VECTOR_STATE_SIZE.
Referenced by get(), and restoreStatus().
bool CLHEP::HepJamesRandom::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 386 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 386 of file JamesRandom.cc
References c, cd, cm, i97, j97, CLHEP::DoubConv::longs2double(), t, u, and VECTOR_STATE_SIZE.
std::string CLHEP::HepJamesRandom::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 60 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 60 of file JamesRandom.cc
CLHEP::HepJamesRandom::operator double () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 270 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 270 of file JamesRandom.cc
References G4AblaRandom::flat().
CLHEP::HepJamesRandom::operator float () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 274 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 274 of file JamesRandom.cc
References G4AblaRandom::flat().
CLHEP::HepJamesRandom::operator unsigned int () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 278 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 278 of file JamesRandom.cc
References G4AblaRandom::flat(), int(), and Acts::UnitConstants::u.
std::ostream & CLHEP::HepJamesRandom::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 283 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 283 of file JamesRandom.cc
References put(), and v.
std::vector< unsigned long > CLHEP::HepJamesRandom::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 293 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 293 of file JamesRandom.cc
References c, cd, cm, CLHEP::DoubConv::dto2longs(), j97, t, u, and v.
Referenced by put(), and saveStatus().
void CLHEP::HepJamesRandom::restoreStatus (const char filename[] = "JamesRand.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 123 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 123 of file JamesRandom.cc
References c, cd, CLHEP::HepRandomEngine::checkFile(), cm, engineName(), getState(), i97, in, j97, CLHEP::possibleKeywordInput(), CLHEP::HepRandomEngine::theSeed, u, v, and VECTOR_STATE_SIZE.
void CLHEP::HepJamesRandom::saveStatus (const char filename[] = "JamesRand.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 110 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 110 of file JamesRandom.cc
References put(), and v.
void CLHEP::HepJamesRandom::setSeed (long seed, int dum = 0) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 177 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 177 of file JamesRandom.cc
References c, cd, cm, i97, j97, k, CLHEP::m, CLHEP::mm, n, CLHEP::s, seed, t, CLHEP::HepRandomEngine::theSeed, and u.
Referenced by HepJamesRandom(), and setSeeds().
void CLHEP::HepJamesRandom::setSeeds (const long * seeds, int dum = 0) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 229 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 229 of file JamesRandom.cc
References CLHEP::L, setSeed(), and CLHEP::HepRandomEngine::theSeeds.
Referenced by HepJamesRandom().
void CLHEP::HepJamesRandom::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 161 of file JamesRandom.cc.
View newest version in sPHENIX GitHub at line 161 of file JamesRandom.cc
References c, cd, cm, i97, j97, CLHEP::HepRandomEngine::theSeed, and u.
Member Data Documentation
double CLHEP::HepJamesRandom::c private
Definition at line 103 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 103 of file JamesRandom.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
double CLHEP::HepJamesRandom::cd private
Definition at line 103 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 103 of file JamesRandom.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
double CLHEP::HepJamesRandom::cm private
Definition at line 103 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 103 of file JamesRandom.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
int CLHEP::HepJamesRandom::i97 private
Definition at line 104 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 104 of file JamesRandom.h
Referenced by flat(), getState(), restoreStatus(), setSeed(), and showStatus().
int CLHEP::HepJamesRandom::j97 private
Definition at line 104 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 104 of file JamesRandom.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
double CLHEP::HepJamesRandom::u[97] private
Definition at line 102 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 102 of file JamesRandom.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
const unsigned int CLHEP::HepJamesRandom::VECTOR_STATE_SIZE = 202 static
Definition at line 97 of file JamesRandom.h.
View newest version in sPHENIX GitHub at line 97 of file JamesRandom.h
Referenced by getState(), and restoreStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/JamesRandom.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/JamesRandom.cc