ECCE @ EIC Software: UltraRunAction Class Reference
UltraRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/air_shower/include/UltraRunAction.hh>
Public Member Functions
UltraRunAction ()
~UltraRunAction ()
void BeginOfRunAction (const G4Run *aRun)
void EndOfRunAction (const G4Run *aRun)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4int saveRndm
G4int luxury
G4int seed
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 49 of file UltraRunAction.hh.
View newest version in sPHENIX GitHub at line 49 of file UltraRunAction.hh
Constructor & Destructor Documentation
UltraRunAction::UltraRunAction ()
Definition at line 51 of file UltraRunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file UltraRunAction.cc
References luxury, saveRndm, and seed.
UltraRunAction::~UltraRunAction ()
Definition at line 60 of file UltraRunAction.cc.
View newest version in sPHENIX GitHub at line 60 of file UltraRunAction.cc
Member Function Documentation
void UltraRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 65 of file UltraRunAction.cc.
View newest version in sPHENIX GitHub at line 65 of file UltraRunAction.cc
References G4VAnalysisManager::CreateH1(), G4cout, G4endl, G4Run::GetRunID(), G4ToolsAnalysisManager::Instance(), G4UserRunAction::IsMaster(), luxury, G4VAnalysisManager::OpenFile(), saveRndm, seed, G4VAnalysisManager::SetFirstHistoId(), and Acts::VectorHelpers::time().
void UltraRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 104 of file UltraRunAction.cc.
View newest version in sPHENIX GitHub at line 104 of file UltraRunAction.cc
References G4VAnalysisManager::CloseFile(), G4cout, G4endl, G4Run::GetRunID(), G4ToolsAnalysisManager::Instance(), G4UserRunAction::IsMaster(), saveRndm, and G4VAnalysisManager::Write().
Member Data Documentation
G4int UltraRunAction::luxury private
Definition at line 63 of file UltraRunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file UltraRunAction.hh
Referenced by BeginOfRunAction(), and UltraRunAction().
G4int UltraRunAction::saveRndm private
Definition at line 62 of file UltraRunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file UltraRunAction.hh
Referenced by BeginOfRunAction(), EndOfRunAction(), and UltraRunAction().
G4int UltraRunAction::seed private
Definition at line 64 of file UltraRunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file UltraRunAction.hh
Referenced by BeginOfRunAction(), and UltraRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/air_shower/include/UltraRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/air_shower/src/UltraRunAction.cc