ECCE @ EIC Software: G4RadioactiveDecayBase Class Reference
G4RadioactiveDecayBase Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactiveDecayBase.hh>
Public Member Functions
G4RadioactiveDecayBase (const G4String &processName="RadioactiveDecayBase")
~G4RadioactiveDecayBase ()
virtual void ProcessDescription (std::ostream &outFile) const
G4bool IsApplicable (const G4ParticleDefinition &)
G4DecayTable * GetDecayTable (const G4ParticleDefinition *)
void SelectAVolume (const G4String aVolume)
void DeselectAVolume (const G4String aVolume)
void SelectAllVolumes ()
void DeselectAllVolumes ()
void SetICM (G4bool icm)
void SetARM (G4bool arm)
G4DecayTable * LoadDecayTable (const G4ParticleDefinition &theParentNucleus)
void AddUserDecayDataFile (G4int Z, G4int A, G4String filename)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetNucleusLimits (G4NucleusLimits theNucleusLimits1)
G4NucleusLimits GetNucleusLimits () const
void SetDecayDirection (const G4ThreeVector &theDir)
const G4ThreeVector & GetDecayDirection () const
void SetDecayHalfAngle (G4double halfAngle=0.*CLHEP::deg)
G4double GetDecayHalfAngle () const
void SetDecayCollimation (const G4ThreeVector &theDir, G4double halfAngle=0.*CLHEP::deg)
void BuildPhysicsTable (const G4ParticleDefinition &)
G4VParticleChange * DecayIt (const G4Track &theTrack, const G4Step &theStep)
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
void DecayAnalog (const G4Track &theTrack)
G4DecayProducts * DoDecay (const G4ParticleDefinition &theParticleDef)
void CollimateDecay (G4DecayProducts *products)
void CollimateDecayProduct (G4DynamicParticle *product)
G4ThreeVector ChooseCollimationDirection () const
G4double GetMeanFreePath (const G4Track &theTrack, G4double previousStepSize, G4ForceCondition *condition)
G4double GetMeanLifeTime (const G4Track &theTrack, G4ForceCondition *condition)
Protected Attributes
G4ParticleChangeForRadDecay fParticleChangeForRadDecay
G4RadioactiveDecayBaseMessenger * theRadioactiveDecayBaseMessenger
G4PhotonEvaporation * photonEvaporation
std::vector< G4String > ValidVolumes
bool isAllVolumesMode
DecayTableMap * dkmap
Static Protected Attributes
static const G4double levelTolerance = 10.0*eV
Private Member Functions
void StreamInfo (std::ostream &os, const G4String &endline)
G4RadioactiveDecayBase (const G4RadioactiveDecayBase &right)
G4RadioactiveDecayBase & operator= (const G4RadioactiveDecayBase &right)
G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)
G4VParticleChange * AtRestDoIt (const G4Track &theTrack, const G4Step &theStep)
G4VParticleChange * PostStepDoIt (const G4Track &theTrack, const G4Step &theStep)
Private Attributes
G4NucleusLimits theNucleusLimits
G4bool isInitialised
G4bool applyICM
G4bool applyARM
G4ThreeVector forceDecayDirection
G4double forceDecayHalfAngle
G4String dirPath
std::map< G4int, G4String > theUserRadioactiveDataFiles
G4RadioactiveDecayMode theRadDecayMode
G4double fRemainderLifeTime
G4int verboseLevel
Static Private Attributes
static const G4ThreeVector origin
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 64 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RadioactiveDecayBase.hh
Constructor & Destructor Documentation
G4RadioactiveDecayBase::G4RadioactiveDecayBase (const G4String & processName = "RadioactiveDecayBase")
Definition at line 108 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 108 of file G4RadioactiveDecayBase.cc
References applyARM, applyICM, dirPath, dkmap, FatalException, fParticleChangeForRadDecay, fRadioactiveDecay, G4cout, G4endl, G4Exception(), GetVerboseLevel(), G4HadronicProcessStore::Instance(), isAllVolumesMode, photonEvaporation, G4VProcess::pParticleChange, G4PhotonEvaporation::RDMForced(), G4HadronicProcessStore::RegisterExtraProcess(), SelectAllVolumes(), G4PhotonEvaporation::SetICM(), G4VProcess::SetProcessSubType(), theRadioactiveDecayBaseMessenger, and theUserRadioactiveDataFiles.
G4RadioactiveDecayBase::~G4RadioactiveDecayBase ()
Definition at line 180 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 180 of file G4RadioactiveDecayBase.cc
References dkmap, photonEvaporation, and theRadioactiveDecayBaseMessenger.
G4RadioactiveDecayBase::G4RadioactiveDecayBase (const G4RadioactiveDecayBase & right) private
Member Function Documentation
void G4RadioactiveDecayBase::AddUserDecayDataFile (G4int Z, G4int A, G4String filename)
Definition at line 896 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 896 of file G4RadioactiveDecayBase.cc
References FatalException, INPUTHEPMC::filename, G4cout, G4endl, G4Exception(), theUserRadioactiveDataFiles, and Z.
Referenced by G4RadioactiveDecayBaseMessenger::SetNewValue().
G4VParticleChange* G4RadioactiveDecayBase::AtRestDoIt (const G4Track & theTrack, const G4Step & theStep) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 242 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 242 of file G4RadioactiveDecayBase.hh
References DecayIt().
G4double G4RadioactiveDecayBase::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 233 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 233 of file G4RadioactiveDecayBase.hh
References G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), and fRemainderLifeTime.
void G4RadioactiveDecayBase::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Definition at line 443 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 443 of file G4RadioactiveDecayBase.cc
References G4cout, G4GenericIon::GenericIon(), G4HadronicProcessStore::Instance(), isInitialised, G4Threading::IsMasterThread(), G4HadronicProcessStore::RegisterParticleForExtraProcess(), and StreamInfo().
G4ThreeVector G4RadioactiveDecayBase::ChooseCollimationDirection () const protected
Definition at line 1263 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 1263 of file G4RadioactiveDecayBase.cc
References deg, dir, forceDecayDirection, forceDecayHalfAngle, G4cout, G4endl, G4UniformRand, GetVerboseLevel(), origin, CLHEP::Hep3Vector::phi(), phi, pi, CLHEP::Hep3Vector::setPhi(), CLHEP::Hep3Vector::setTheta(), and CLHEP::Hep3Vector::theta().
Referenced by CollimateDecayProduct().
void G4RadioactiveDecayBase::CollimateDecay (G4DecayProducts * products) protected
Definition at line 1219 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 1219 of file G4RadioactiveDecayBase.cc
References alpha, CollimateDecayProduct(), G4Electron::Definition(), G4Alpha::Definition(), G4Triton::Definition(), G4Proton::Definition(), G4Positron::Definition(), G4Neutron::Definition(), G4Gamma::Definition(), deg, G4InuclParticleNames::electron, G4DecayProducts::entries(), forceDecayDirection, forceDecayHalfAngle, G4cout, G4endl, G4DynamicParticle::GetParticleDefinition(), GetVerboseLevel(), G4InuclParticleNames::neutron, origin, G4InuclParticleNames::positron, G4InuclParticleNames::proton, and G4InuclParticleNames::triton.
Referenced by DoDecay().
void G4RadioactiveDecayBase::CollimateDecayProduct (G4DynamicParticle * product) protected
Definition at line 1248 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 1248 of file G4RadioactiveDecayBase.cc
References ChooseCollimationDirection(), G4cout, G4endl, G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), origin, and G4DynamicParticle::SetMomentumDirection().
Referenced by CollimateDecay().
void G4RadioactiveDecayBase::DecayAnalog (const G4Track & theTrack) protected
Definition at line 1086 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 1086 of file G4RadioactiveDecayBase.cc
References G4ParticleChangeForRadDecay::AddSecondary(), G4DecayProducts::Boost(), G4VProcess::ClearNumberOfInteractionLengthLeft(), cm, DoDecay(), G4DecayProducts::DumpInfo(), G4DecayProducts::entries(), fParticleChangeForRadDecay, fStopAndKill, fStopButAlive, G4cout, G4endl, G4UniformRand, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetLocalTime(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), G4Track::GetPosition(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), GetVerboseLevel(), G4DecayProducts::IsChecked(), IT, KshellEC, ns, NshellEC, G4DecayProducts::PopProducts(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForDecay::ProposeLocalTime(), G4VParticleChange::ProposeTrackStatus(), G4Track::SetCreatorModelIndex(), G4Track::SetGoodForTrackingFlag(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), theRadDecayMode, x, y, and z.
Referenced by G4Radioactivation::DecayIt(), and DecayIt().
G4VParticleChange * G4RadioactiveDecayBase::DecayIt (const G4Track & theTrack, const G4Step & theStep)
Definition at line 919 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 919 of file G4RadioactiveDecayBase.cc
References G4VProcess::ClearNumberOfInteractionLengthLeft(), DecayAnalog(), G4DecayTable::entries(), fParticleChangeForRadDecay, fStopAndKill, G4cout, G4endl, GetDecayTable(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetName(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), G4Track::GetVolume(), G4Track::GetWeight(), G4ParticleChangeForDecay::Initialize(), isAllVolumesMode, IsApplicable(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4VParticleChange::SetNumberOfSecondaries(), and ValidVolumes.
Referenced by AtRestDoIt(), and PostStepDoIt().
void G4RadioactiveDecayBase::DeselectAllVolumes ()
Definition at line 326 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 326 of file G4RadioactiveDecayBase.cc
References G4cout, G4endl, GetVerboseLevel(), isAllVolumesMode, and ValidVolumes.
Referenced by G4RadioactiveDecayBaseMessenger::SetNewValue().
void G4RadioactiveDecayBase::DeselectAVolume (const G4String aVolume)
Definition at line 268 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 268 of file G4RadioactiveDecayBase.cc
References G4cout, G4endl, G4Exception(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), GetVerboseLevel(), isAllVolumesMode, JustWarning, ValidVolumes, and Acts::Test::volume.
Referenced by G4RadioactiveDecayBaseMessenger::SetNewValue().
G4DecayProducts * G4RadioactiveDecayBase::DoDecay (const G4ParticleDefinition & theParticleDef) protected
Definition at line 1180 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 1180 of file G4RadioactiveDecayBase.cc
References CollimateDecay(), G4VDecayChannel::DecayIt(), FatalException, G4cout, G4endl, G4Exception(), GetDecayTable(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), GetVerboseLevel(), MeV, G4DecayTable::SelectADecayChannel(), and theRadDecayMode.
Referenced by DecayAnalog(), and G4Radioactivation::DecayIt().
const G4ThreeVector& G4RadioactiveDecayBase::GetDecayDirection () const inline
Definition at line 135 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 135 of file G4RadioactiveDecayBase.hh
References forceDecayDirection.
G4double G4RadioactiveDecayBase::GetDecayHalfAngle () const inline
Definition at line 143 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 143 of file G4RadioactiveDecayBase.hh
References forceDecayHalfAngle.
G4DecayTable * G4RadioactiveDecayBase::GetDecayTable (const G4ParticleDefinition * aNucleus)
Definition at line 226 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 226 of file G4RadioactiveDecayBase.cc
References dkmap, G4ParticleDefinition::GetParticleName(), and LoadDecayTable().
Referenced by DecayIt(), and DoDecay().
G4double G4RadioactiveDecayBase::GetMeanFreePath (const G4Track & theTrack, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 378 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 378 of file G4RadioactiveDecayBase.cc
References source.hepunit::c_light, DBL_MAX, DBL_MIN, G4cout, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGLifeTime(), G4DynamicParticle::GetTotalMomentum(), GetVerboseLevel(), GeV, JustWarning, keV, and m.
G4double G4RadioactiveDecayBase::GetMeanLifeTime (const G4Track & theTrack, G4ForceCondition * condition) protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 342 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 342 of file G4RadioactiveDecayBase.cc
References DBL_MAX, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), GetVerboseLevel(), GeV, and ns.
Referenced by G4Radioactivation::GetMeanLifeTime().
G4NucleusLimits G4RadioactiveDecayBase::GetNucleusLimits () const inline
Definition at line 129 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 129 of file G4RadioactiveDecayBase.hh
References theNucleusLimits.
G4int G4RadioactiveDecayBase::GetVerboseLevel () const inline
Definition at line 119 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 119 of file G4RadioactiveDecayBase.hh
References verboseLevel.
Referenced by G4Radioactivation::CalculateChainsFromParent(), ChooseCollimationDirection(), CollimateDecay(), CollimateDecayProduct(), G4Radioactivation::ConvolveSourceTimeProfile(), DecayAnalog(), G4Radioactivation::DecayIt(), DecayIt(), DeselectAllVolumes(), DeselectAVolume(), DoDecay(), G4Radioactivation::G4Radioactivation(), G4RadioactiveDecayBase(), G4Radioactivation::GetChainsFromParent(), G4Radioactivation::GetDecayTime(), GetMeanFreePath(), GetMeanLifeTime(), LoadDecayTable(), SelectAllVolumes(), SelectAVolume(), G4Radioactivation::SetDecayBias(), and G4Radioactivation::SetSourceTimeProfile().
G4bool G4RadioactiveDecayBase::IsApplicable (const G4ParticleDefinition & aParticle) virtual
Reimplemented from G4VProcess.
Definition at line 204 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 204 of file G4RadioactiveDecayBase.cc
References A(), G4NucleusLimits::GetAMax(), G4NucleusLimits::GetAMin(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGLifeTime(), G4NucleusLimits::GetZMax(), G4NucleusLimits::GetZMin(), theNucleusLimits, and Z.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4Radioactivation::DecayIt(), and DecayIt().
G4DecayTable * G4RadioactiveDecayBase::LoadDecayTable (const G4ParticleDefinition & theParentNucleus)
Definition at line 509 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 509 of file G4RadioactiveDecayBase.cc
References a, A(), kdfinder::abs(), allowed, Alpha, applyARM, b, BDNeutron, BDProton, Beta2Minus, Beta2Plus, BetaMinus, BetaPlus, c, dirPath, G4DecayTable::DumpInfo(), G4DecayTable::entries(), FatalException, file, G4Ions::FloatLevelBase(), G4Exception(), G4VDecayChannel::GetBR(), G4DecayTable::GetDecayChannel(), G4NuclearDecay::GetDecayMode(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), G4DecayTable::Insert(), IT, JustWarning, keV, KshellEC, levelTolerance, LshellEC, MeV, MshellEC, Neutron, Neutron2, noFloat, NshellEC, photonEvaporation, Proton, Proton2, RDM_ERROR, G4ECDecay::SetARM(), G4ITDecay::SetARM(), G4VDecayChannel::SetBR(), SpFission, G4String::strip(), theUserRadioactiveDataFiles, Triton, and Z.
Referenced by GetDecayTable(), and G4Radioactivation::GetDecayTable1().
G4RadioactiveDecayBase& G4RadioactiveDecayBase::operator= (const G4RadioactiveDecayBase & right) private
G4VParticleChange* G4RadioactiveDecayBase::PostStepDoIt (const G4Track & theTrack, const G4Step & theStep) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 247 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 247 of file G4RadioactiveDecayBase.hh
References DecayIt().
void G4RadioactiveDecayBase::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4VProcess.
Reimplemented in G4Radioactivation.
Definition at line 170 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 170 of file G4RadioactiveDecayBase.cc
void G4RadioactiveDecayBase::SelectAllVolumes ()
Definition at line 302 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 302 of file G4RadioactiveDecayBase.cc
References G4cout, G4endl, G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), GetVerboseLevel(), isAllVolumesMode, ValidVolumes, and Acts::Test::volume.
Referenced by G4RadioactiveDecayBase(), and G4RadioactiveDecayBaseMessenger::SetNewValue().
void G4RadioactiveDecayBase::SelectAVolume (const G4String aVolume)
Definition at line 242 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 242 of file G4RadioactiveDecayBase.cc
References G4cout, G4endl, G4Exception(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), GetVerboseLevel(), JustWarning, ValidVolumes, and Acts::Test::volume.
Referenced by G4RadioactiveDecayBaseMessenger::SetNewValue().
void G4RadioactiveDecayBase::SetARM (G4bool arm) inline
Definition at line 107 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 107 of file G4RadioactiveDecayBase.hh
References applyARM.
void G4RadioactiveDecayBase::SetDecayCollimation (const G4ThreeVector & theDir, G4double halfAngle = 0.*CLHEP::deg) inline
Definition at line 147 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 147 of file G4RadioactiveDecayBase.hh
References SetDecayDirection(), and SetDecayHalfAngle().
void G4RadioactiveDecayBase::SetDecayDirection (const G4ThreeVector & theDir) inline
Definition at line 131 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 131 of file G4RadioactiveDecayBase.hh
References forceDecayDirection, and CLHEP::Hep3Vector::unit().
Referenced by SetDecayCollimation().
void G4RadioactiveDecayBase::SetDecayHalfAngle (G4double halfAngle = 0.*CLHEP::deg) inline
Definition at line 139 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 139 of file G4RadioactiveDecayBase.hh
References CLHEP::deg, forceDecayHalfAngle, max, and min.
Referenced by SetDecayCollimation().
void G4RadioactiveDecayBase::SetICM (G4bool icm) inline
Definition at line 104 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 104 of file G4RadioactiveDecayBase.hh
References applyICM.
void G4RadioactiveDecayBase::SetNucleusLimits (G4NucleusLimits theNucleusLimits1) inline
Definition at line 122 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 122 of file G4RadioactiveDecayBase.hh
References theNucleusLimits.
void G4RadioactiveDecayBase::SetVerboseLevel (G4int value) inline
Definition at line 116 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 116 of file G4RadioactiveDecayBase.hh
References verboseLevel.
void G4RadioactiveDecayBase::StreamInfo (std::ostream & os, const G4String & endline) private
Definition at line 462 of file G4RadioactiveDecayBase.cc.
View newest version in sPHENIX GitHub at line 462 of file G4RadioactiveDecayBase.cc
References G4EmParameters::Auger(), G4EmParameters::AugerCascade(), G4EmParameters::BeardenFluoDir(), G4DeexPrecoParameters::CorrelatedGamma(), G4EmParameters::DeexcitationIgnoreCut(), G4EmParameters::Fluo(), G4NuclearLevelData::GetInstance(), G4DeexPrecoParameters::GetInternalConversionFlag(), G4DeexPrecoParameters::GetMaxLifeTime(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::GetTwoJMAX(), G4EmParameters::Instance(), CLHEP::prec, CLHEP::ps, and G4DeexPrecoParameters::StoreICLevelData().
Referenced by BuildPhysicsTable().
Member Data Documentation
G4bool G4RadioactiveDecayBase::applyARM private
Definition at line 204 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 204 of file G4RadioactiveDecayBase.hh
Referenced by G4RadioactiveDecayBase(), LoadDecayTable(), and SetARM().
G4bool G4RadioactiveDecayBase::applyICM private
Definition at line 203 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 203 of file G4RadioactiveDecayBase.hh
Referenced by G4RadioactiveDecayBase(), and SetICM().
G4String G4RadioactiveDecayBase::dirPath private
Definition at line 212 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 212 of file G4RadioactiveDecayBase.hh
Referenced by G4RadioactiveDecayBase(), and LoadDecayTable().
DecayTableMap* G4RadioactiveDecayBase::dkmap protected
Definition at line 187 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 187 of file G4RadioactiveDecayBase.hh
Referenced by G4RadioactiveDecayBase(), GetDecayTable(), G4Radioactivation::GetDecayTable1(), and ~G4RadioactiveDecayBase().
G4ThreeVector G4RadioactiveDecayBase::forceDecayDirection private
Definition at line 207 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 207 of file G4RadioactiveDecayBase.hh
Referenced by ChooseCollimationDirection(), CollimateDecay(), GetDecayDirection(), and SetDecayDirection().
G4double G4RadioactiveDecayBase::forceDecayHalfAngle private
Definition at line 208 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 208 of file G4RadioactiveDecayBase.hh
Referenced by ChooseCollimationDirection(), CollimateDecay(), GetDecayHalfAngle(), and SetDecayHalfAngle().
G4ParticleChangeForRadDecay G4RadioactiveDecayBase::fParticleChangeForRadDecay protected
Definition at line 176 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 176 of file G4RadioactiveDecayBase.hh
Referenced by DecayAnalog(), G4Radioactivation::DecayIt(), DecayIt(), and G4RadioactiveDecayBase().
G4double G4RadioactiveDecayBase::fRemainderLifeTime private
Definition at line 227 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 227 of file G4RadioactiveDecayBase.hh
Referenced by AtRestGetPhysicalInteractionLength().
bool G4RadioactiveDecayBase::isAllVolumesMode protected
Definition at line 182 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 182 of file G4RadioactiveDecayBase.hh
Referenced by G4Radioactivation::DecayIt(), DecayIt(), DeselectAllVolumes(), DeselectAVolume(), G4RadioactiveDecayBase(), and SelectAllVolumes().
G4bool G4RadioactiveDecayBase::isInitialised private
Definition at line 201 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 201 of file G4RadioactiveDecayBase.hh
Referenced by BuildPhysicsTable().
const G4double G4RadioactiveDecayBase::levelTolerance = 10.0*eV static protected
Definition at line 184 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 184 of file G4RadioactiveDecayBase.hh
Referenced by G4Radioactivation::CalculateChainsFromParent(), and LoadDecayTable().
const G4ThreeVector G4RadioactiveDecayBase::origin static private
Definition at line 209 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 209 of file G4RadioactiveDecayBase.hh
Referenced by ChooseCollimationDirection(), CollimateDecay(), and CollimateDecayProduct().
G4PhotonEvaporation* G4RadioactiveDecayBase::photonEvaporation protected
Definition at line 179 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 179 of file G4RadioactiveDecayBase.hh
Referenced by G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecayBase(), LoadDecayTable(), and ~G4RadioactiveDecayBase().
G4NucleusLimits G4RadioactiveDecayBase::theNucleusLimits private
Definition at line 199 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 199 of file G4RadioactiveDecayBase.hh
Referenced by GetNucleusLimits(), IsApplicable(), and SetNucleusLimits().
G4RadioactiveDecayMode G4RadioactiveDecayBase::theRadDecayMode private
Definition at line 218 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 218 of file G4RadioactiveDecayBase.hh
Referenced by DecayAnalog(), and DoDecay().
G4RadioactiveDecayBaseMessenger* G4RadioactiveDecayBase::theRadioactiveDecayBaseMessenger protected
Definition at line 178 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 178 of file G4RadioactiveDecayBase.hh
Referenced by G4RadioactiveDecayBase(), and ~G4RadioactiveDecayBase().
std::map<G4int, G4String> G4RadioactiveDecayBase::theUserRadioactiveDataFiles private
Definition at line 215 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 215 of file G4RadioactiveDecayBase.hh
Referenced by AddUserDecayDataFile(), G4RadioactiveDecayBase(), and LoadDecayTable().
std::vector<G4String> G4RadioactiveDecayBase::ValidVolumes protected
Definition at line 181 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 181 of file G4RadioactiveDecayBase.hh
Referenced by G4Radioactivation::DecayIt(), DecayIt(), DeselectAllVolumes(), DeselectAVolume(), SelectAllVolumes(), and SelectAVolume().
G4int G4RadioactiveDecayBase::verboseLevel private
Definition at line 228 of file G4RadioactiveDecayBase.hh.
View newest version in sPHENIX GitHub at line 228 of file G4RadioactiveDecayBase.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactiveDecayBase.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4RadioactiveDecayBase.cc