ECCE @ EIC Software: G4ProcessTableMessenger Class Reference
G4ProcessTableMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessTableMessenger.hh>
Public Member Functions
G4ProcessTableMessenger (G4ProcessTable *pTable)
virtual ~G4ProcessTableMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
virtual G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4String GetProcessTypeName (G4ProcessType aType) const
G4int GetProcessType (const G4String &aTypeName) const
void SetNumberOfProcessType ()
G4ProcessTableMessenger (const G4ProcessTableMessenger &)
G4ProcessTableMessenger ()
Private Attributes
G4ProcessTable * theProcessTable
G4UIdirectory * thisDirectory
G4UIcmdWithAnInteger * verboseCmd
G4UIcmdWithAString * listCmd
G4UIcommand * dumpCmd
G4UIcommand * activateCmd
G4UIcommand * inactivateCmd
G4UIcommand * procVerboseCmd
G4String currentProcessTypeName
G4String currentProcessName
G4String currentParticleName
Static Private Attributes
static G4ThreadLocal G4int NumberOfProcessType = 10
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 64 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ProcessTableMessenger.hh
Constructor & Destructor Documentation
G4ProcessTableMessenger::G4ProcessTableMessenger (G4ProcessTable * pTable)
Definition at line 67 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ProcessTableMessenger.cc
References activateCmd, G4UIcommand::AvailableForStates(), dumpCmd, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_Init, G4State_PreInit, G4VProcess::GetProcessTypeName(), incremental_prev_tag::idx, inactivateCmd, listCmd, NumberOfProcessType, procVerboseCmd, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), SetNumberOfProcessType(), G4UIcommand::SetParameter(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcommand::SetRange(), thisDirectory, and verboseCmd.
G4ProcessTableMessenger::~G4ProcessTableMessenger () virtual
Definition at line 161 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 161 of file G4ProcessTableMessenger.cc
References activateCmd, dumpCmd, inactivateCmd, listCmd, procVerboseCmd, thisDirectory, and verboseCmd.
G4ProcessTableMessenger::G4ProcessTableMessenger (const G4ProcessTableMessenger &) inline private
Definition at line 81 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ProcessTableMessenger.hh
G4ProcessTableMessenger::G4ProcessTableMessenger () inline private
Definition at line 83 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ProcessTableMessenger.hh
Member Function Documentation
G4String G4ProcessTableMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 353 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 353 of file G4ProcessTableMessenger.cc
References G4UIcommand::ConvertToString(), currentParticleName, currentProcessName, currentProcessTypeName, G4ProcessTable::GetVerboseLevel(), listCmd, theProcessTable, and verboseCmd.
G4int G4ProcessTableMessenger::GetProcessType (const G4String & aTypeName) const private
Definition at line 379 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 379 of file G4ProcessTableMessenger.cc
References G4VProcess::GetProcessTypeName(), incremental_prev_tag::idx, and NumberOfProcessType.
Referenced by SetNewValue().
G4String G4ProcessTableMessenger::GetProcessTypeName (G4ProcessType aType) const private
Definition at line 373 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 373 of file G4ProcessTableMessenger.cc
References G4VProcess::GetProcessTypeName().
void G4ProcessTableMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 173 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 173 of file G4ProcessTableMessenger.cc
References activateCmd, G4UImanager::ApplyCommand(), G4UIcommand::CommandFailed(), G4ParticleTable::contains(), currentParticleName, currentProcessName, currentProcessTypeName, dumpCmd, G4ProcessTable::DumpInfo(), G4ParticleTable::FindParticle(), G4ProcessTable::FindProcesses(), G4cout, G4endl, G4ProcessTable::GetNameList(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ParticleTable::GetParticleTable(), G4VProcess::GetProcessName(), GetProcessType(), G4VProcess::GetProcessType(), G4UImanager::GetUIpointer(), incremental_prev_tag::idx, inactivateCmd, G4String::isNull(), G4ProcessVector::length(), listCmd, procVerboseCmd, G4ProcessTable::SetProcessActivation(), G4ProcessTable::SetVerboseLevel(), G4VProcess::SetVerboseLevel(), theProcessTable, and verboseCmd.
void G4ProcessTableMessenger::SetNumberOfProcessType () private
Definition at line 393 of file G4ProcessTableMessenger.cc.
View newest version in sPHENIX GitHub at line 393 of file G4ProcessTableMessenger.cc
References G4String::contains(), FatalException, G4Exception(), G4VProcess::GetProcessTypeName(), incremental_prev_tag::idx, and NumberOfProcessType.
Referenced by G4ProcessTableMessenger().
Member Data Documentation
G4UIcommand* G4ProcessTableMessenger::activateCmd private
Definition at line 92 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), SetNewValue(), and ~G4ProcessTableMessenger().
G4String G4ProcessTableMessenger::currentParticleName private
Definition at line 98 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ProcessTableMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4String G4ProcessTableMessenger::currentProcessName private
Definition at line 97 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ProcessTableMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4String G4ProcessTableMessenger::currentProcessTypeName private
Definition at line 96 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ProcessTableMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIcommand* G4ProcessTableMessenger::dumpCmd private
Definition at line 91 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), SetNewValue(), and ~G4ProcessTableMessenger().
G4UIcommand* G4ProcessTableMessenger::inactivateCmd private
Definition at line 93 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), SetNewValue(), and ~G4ProcessTableMessenger().
G4UIcmdWithAString* G4ProcessTableMessenger::listCmd private
Definition at line 90 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ProcessTableMessenger().
G4ThreadLocal G4int G4ProcessTableMessenger::NumberOfProcessType = 10 static private
Definition at line 77 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), GetProcessType(), and SetNumberOfProcessType().
G4UIcommand* G4ProcessTableMessenger::procVerboseCmd private
Definition at line 94 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), SetNewValue(), and ~G4ProcessTableMessenger().
G4ProcessTable* G4ProcessTableMessenger::theProcessTable private
Definition at line 83 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ProcessTableMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIdirectory* G4ProcessTableMessenger::thisDirectory private
Definition at line 88 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), and ~G4ProcessTableMessenger().
G4UIcmdWithAnInteger* G4ProcessTableMessenger::verboseCmd private
Definition at line 89 of file G4ProcessTableMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ProcessTableMessenger.hh
Referenced by G4ProcessTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ProcessTableMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessTableMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4ProcessTableMessenger.cc