ECCE @ EIC Software: G4ElectroVDNuclearModel Class Reference
G4ElectroVDNuclearModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/include/G4ElectroVDNuclearModel.hh>
Public Member Functions
G4ElectroVDNuclearModel ()
~G4ElectroVDNuclearModel ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
virtual void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4DynamicParticle * CalculateEMVertex (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
void CalculateHadronicVertex (G4DynamicParticle *incident, G4Nucleus &target)
Private Attributes
G4double leptonKE
G4double photonEnergy
G4double photonQ2
G4ElectroNuclearCrossSection * electroXS
G4PhotoNuclearCrossSection * gammaXS
G4TheoFSGenerator * ftfp
G4LundStringFragmentation * theFragmentation
G4ExcitedStringDecay * theStringDecay
G4CascadeInterface * bert
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 49 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ElectroVDNuclearModel.hh
Constructor & Destructor Documentation
G4ElectroVDNuclearModel::G4ElectroVDNuclearModel ()
Definition at line 62 of file G4ElectroVDNuclearModel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ElectroVDNuclearModel.cc
References bert, G4PhotoNuclearCrossSection::Default_Name(), G4ElectroNuclearCrossSection::Default_Name(), electroXS, G4HadronicInteractionRegistry::FindModel(), ftfp, gammaXS, G4HadronicInteractionRegistry::Instance(), G4CrossSectionDataSetRegistry::Instance(), PeV, G4VIntraNuclearTransportModel::SetDeExcitation(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), theFragmentation, and theStringDecay.
G4ElectroVDNuclearModel::~G4ElectroVDNuclearModel ()
Definition at line 97 of file G4ElectroVDNuclearModel.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ElectroVDNuclearModel.cc
References theFragmentation, and theStringDecay.
Member Function Documentation
G4HadFinalState * G4ElectroVDNuclearModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 119 of file G4ElectroVDNuclearModel.cc.
View newest version in sPHENIX GitHub at line 119 of file G4ElectroVDNuclearModel.cc
References CalculateEMVertex(), CalculateHadronicVertex(), G4HadFinalState::Clear(), dM, electroXS, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4ElectroNuclearCrossSection::GetElementCrossSection(), G4ElectroNuclearCrossSection::GetEquivalentPhotonEnergy(), G4ElectroNuclearCrossSection::GetEquivalentPhotonQ2(), G4HadProjectile::GetKineticEnergy(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetZ_asInt(), isAlive, leptonKE, mat, G4Neutron::Neutron(), photonEnergy, photonQ2, G4Proton::Proton(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetMomentumChange(), G4HadFinalState::SetStatusChange(), G4HadronicInteraction::theParticleChange, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
G4DynamicParticle * G4ElectroVDNuclearModel::CalculateEMVertex (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) private
Definition at line 155 of file G4ElectroVDNuclearModel.cc.
View newest version in sPHENIX GitHub at line 155 of file G4ElectroVDNuclearModel.cc
References CLHEP::Hep3Vector::cross(), dir, dM, electroXS, G4UniformRand, G4Gamma::Gamma(), gammaXS, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4PhotoNuclearCrossSection::GetElementCrossSection(), G4ParticleDefinition::GetPDGMass(), G4ElectroNuclearCrossSection::GetVirtualFactor(), G4Nucleus::GetZ_asInt(), leptonKE, mat, G4Neutron::Neutron(), CLHEP::Hep3Vector::orthogonal(), phi, G4InuclParticleNames::photon, photonEnergy, photonQ2, G4Proton::Proton(), G4HadFinalState::SetEnergyChange(), G4DynamicParticle::SetKineticEnergy(), G4HadFinalState::SetMomentumChange(), G4HadronicInteraction::theParticleChange, twopi, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by ApplyYourself().
void G4ElectroVDNuclearModel::CalculateHadronicVertex (G4DynamicParticle * incident, G4Nucleus & target) private
Definition at line 208 of file G4ElectroVDNuclearModel.cc.
View newest version in sPHENIX GitHub at line 208 of file G4ElectroVDNuclearModel.cc
References G4HadFinalState::AddSecondaries(), G4TheoFSGenerator::ApplyYourself(), G4CascadeInterface::ApplyYourself(), bert, ftfp, G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), GeV, G4PionZero::PionZero(), and G4HadronicInteraction::theParticleChange.
Referenced by ApplyYourself().
void G4ElectroVDNuclearModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 103 of file G4ElectroVDNuclearModel.cc.
View newest version in sPHENIX GitHub at line 103 of file G4ElectroVDNuclearModel.cc
Member Data Documentation
G4CascadeInterface* G4ElectroVDNuclearModel::bert private
Definition at line 79 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ElectroVDNuclearModel.hh
Referenced by CalculateHadronicVertex(), and G4ElectroVDNuclearModel().
G4ElectroNuclearCrossSection* G4ElectroVDNuclearModel::electroXS private
Definition at line 73 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ElectroVDNuclearModel.hh
Referenced by ApplyYourself(), CalculateEMVertex(), and G4ElectroVDNuclearModel().
G4TheoFSGenerator* G4ElectroVDNuclearModel::ftfp private
Definition at line 76 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ElectroVDNuclearModel.hh
Referenced by CalculateHadronicVertex(), and G4ElectroVDNuclearModel().
G4PhotoNuclearCrossSection* G4ElectroVDNuclearModel::gammaXS private
Definition at line 74 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ElectroVDNuclearModel.hh
Referenced by CalculateEMVertex(), and G4ElectroVDNuclearModel().
G4double G4ElectroVDNuclearModel::leptonKE private
Definition at line 69 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ElectroVDNuclearModel.hh
Referenced by ApplyYourself(), and CalculateEMVertex().
G4double G4ElectroVDNuclearModel::photonEnergy private
Definition at line 70 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ElectroVDNuclearModel.hh
Referenced by ApplyYourself(), and CalculateEMVertex().
G4double G4ElectroVDNuclearModel::photonQ2 private
Definition at line 71 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ElectroVDNuclearModel.hh
Referenced by ApplyYourself(), and CalculateEMVertex().
G4LundStringFragmentation* G4ElectroVDNuclearModel::theFragmentation private
Definition at line 77 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ElectroVDNuclearModel.hh
Referenced by G4ElectroVDNuclearModel(), and ~G4ElectroVDNuclearModel().
G4ExcitedStringDecay* G4ElectroVDNuclearModel::theStringDecay private
Definition at line 78 of file G4ElectroVDNuclearModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ElectroVDNuclearModel.hh
Referenced by G4ElectroVDNuclearModel(), and ~G4ElectroVDNuclearModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/include/G4ElectroVDNuclearModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/src/G4ElectroVDNuclearModel.cc