ECCE @ EIC Software: G4INCL::SigmaZeroDecayChannel Class Reference
G4INCL::SigmaZeroDecayChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLSigmaZeroDecayChannel.hh>
Public Member Functions
SigmaZeroDecayChannel (Particle *, ThreeVector const &)
virtual ~SigmaZeroDecayChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Static Public Member Functions
static G4double computeDecayTime (Particle *p)
Private Member Functions
void sampleAngles (G4double *, G4double *, G4double *)
INCL_DECLARE_ALLOCATION_POOL (SigmaZeroDecayChannel)
Private Attributes
Particle * theParticle
ThreeVector const incidentDirection
Detailed Description
Definition at line 49 of file G4INCLSigmaZeroDecayChannel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4INCLSigmaZeroDecayChannel.hh
Constructor & Destructor Documentation
G4INCL::SigmaZeroDecayChannel::SigmaZeroDecayChannel (Particle * p, ThreeVector const & dir)
Definition at line 46 of file G4INCLSigmaZeroDecayChannel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4INCLSigmaZeroDecayChannel.cc
G4INCL::SigmaZeroDecayChannel::~SigmaZeroDecayChannel () virtual
Definition at line 50 of file G4INCLSigmaZeroDecayChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLSigmaZeroDecayChannel.cc
Member Function Documentation
G4double G4INCL::SigmaZeroDecayChannel::computeDecayTime (Particle * p) static
Definition at line 53 of file G4INCLSigmaZeroDecayChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLSigmaZeroDecayChannel.cc
References G4INCL::Particle::getMass(), G4INCL::Particle::getMomentum(), G4INCL::ParticleTable::getWidth(), G4INCL::ThreeVector::mag(), G4INCL::Random::shoot(), G4INCL::SigmaZero, and t.
Referenced by G4INCL::StandardPropagationModel::generateDecays().
void G4INCL::SigmaZeroDecayChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 69 of file G4INCLSigmaZeroDecayChannel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4INCLSigmaZeroDecayChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), G4INCL::Particle::adjustEnergyFromMomentum(), e, G4INCL::ParticleTable::getINCLMass(), G4INCL::Particle::getMass(), G4INCL::Particle::getPosition(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), incidentDirection, G4INCL::Lambda, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::ThreeVector::perp(), phi, G4INCL::Photon, sampleAngles(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), t1, t2, and theParticle.
G4INCL::SigmaZeroDecayChannel::INCL_DECLARE_ALLOCATION_POOL (SigmaZeroDecayChannel) private
void G4INCL::SigmaZeroDecayChannel::sampleAngles (G4double * ctet_par, G4double * stet_par, G4double * phi_par) private
Definition at line 61 of file G4INCLSigmaZeroDecayChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLSigmaZeroDecayChannel.cc
References kdfinder::abs(), G4INCL::Random::shoot(), G4INCL::Math::sign(), and G4INCL::Math::twoPi.
Referenced by fillFinalState().
Member Data Documentation
ThreeVector const G4INCL::SigmaZeroDecayChannel::incidentDirection private
Definition at line 61 of file G4INCLSigmaZeroDecayChannel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4INCLSigmaZeroDecayChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::SigmaZeroDecayChannel::theParticle private
Definition at line 60 of file G4INCLSigmaZeroDecayChannel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLSigmaZeroDecayChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLSigmaZeroDecayChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLSigmaZeroDecayChannel.cc