ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_pop.cc File Reference
MCGIDI_pop.cc File Reference
#include <string.h>
#include <PoPs.h>
#include "MCGIDI.h"
Functions
MCGIDI_POPs * MCGIDI_POPs_new (statusMessageReporting *smr, int size)
int MCGIDI_POPs_initial (statusMessageReporting *, MCGIDI_POPs *pops, int size)
void * MCGIDI_POPs_free (MCGIDI_POPs *pops)
int MCGIDI_POPs_release (MCGIDI_POPs *pops)
MCGIDI_POP * MCGIDI_POPs_addParticleIfNeeded (statusMessageReporting *smr, MCGIDI_POPs *pops, char const *name, double mass_MeV, double level_MeV, MCGIDI_POP *parent, int globalParticle)
int MCGIDI_POPs_findParticleIndex (MCGIDI_POPs *pops, char const *name)
MCGIDI_POP * MCGIDI_POPs_findParticle (MCGIDI_POPs *pops, char const *name)
void MCGIDI_POPs_writeSortedList (MCGIDI_POPs *pops, FILE *f)
void MCGIDI_POPs_printSortedList (MCGIDI_POPs *pops)
MCGIDI_POP * MCGIDI_POP_new (statusMessageReporting *smr, char const *name, double mass_MeV, double level_MeV, MCGIDI_POP *parent)
MCGIDI_POP * MCGIDI_POP_free (MCGIDI_POP *pop)
MCGIDI_POP * MCGIDI_POP_release (MCGIDI_POP *pop)
double MCGIDI_POP_getMass_MeV (MCGIDI_POP *pop)
Function Documentation
MCGIDI_POP* MCGIDI_POP_free (MCGIDI_POP * pop)
Definition at line 191 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 191 of file MCGIDI_pop.cc
References MCGIDI_POP_release(), and smr_freeMemory().
Referenced by MCGIDI_POPs_release().
double MCGIDI_POP_getMass_MeV (MCGIDI_POP * pop)
Definition at line 212 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 212 of file MCGIDI_pop.cc
References MCGIDI_POP_s::mass_MeV.
Referenced by MCGIDI_product_getMass_MeV(), MCGIDI_target_heated_getProjectileMass_MeV(), and MCGIDI_target_heated_getTargetMass_MeV().
MCGIDI_POP* MCGIDI_POP_new (statusMessageReporting * smr, char const * name, double mass_MeV, double level_MeV, MCGIDI_POP * parent)
Definition at line 165 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 165 of file MCGIDI_pop.cc
References A(), MCGIDI_POP_s::A, MCGIDI_POP_s::gammas, MCGIDI_POP_s::level, MCGIDI_POP_s::level_MeV, m, MCGIDI_POP_s::m, MCGIDI_POP_s::mass_MeV, MCGIDI_miscNameToZAm(), MCGIDI_POP_s::name, MCGIDI_POP_s::next, MCGIDI_POP_s::numberOfGammaBranchs, MCGIDI_POP_s::parent, smr_allocateCopyString2, smr_freeMemory(), smr_malloc2, Z, and MCGIDI_POP_s::Z.
Referenced by MCGIDI_POPs_addParticleIfNeeded().
MCGIDI_POP* MCGIDI_POP_release (MCGIDI_POP * pop)
Definition at line 201 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 201 of file MCGIDI_pop.cc
References MCGIDI_POP_s::gammas, MCGIDI_POP_s::name, MCGIDI_POP_s::numberOfGammaBranchs, and smr_freeMemory().
Referenced by MCGIDI_POP_free().
MCGIDI_POP* MCGIDI_POPs_addParticleIfNeeded (statusMessageReporting * smr, MCGIDI_POPs * pops, char const * name, double mass_MeV, double level_MeV, MCGIDI_POP * parent, int globalParticle)
Definition at line 67 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 67 of file MCGIDI_pop.cc
References MCGIDI_POPs_s::first, MCGIDI_POP_s::globalPoPsIndex, MCGIDI_POPs_s::increment, MCGIDI_POPs_s::last, lPoPs_addParticleIfNeeded(), MCGIDI_POP_new(), MCGIDI_POPs_findParticleIndex(), MCGIDI_POP_s::next, MCGIDI_POPs_s::numberOfPOPs, MCGIDI_POPs_s::size, smr_freeMemory(), smr_malloc2, and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_target_heated_parseParticle(), and MCGIDI_target_heated_parseParticleLevel().
MCGIDI_POP* MCGIDI_POPs_findParticle (MCGIDI_POPs * pops, char const * name)
Definition at line 133 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 133 of file MCGIDI_pop.cc
References MCGIDI_POPs_findParticleIndex(), and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_particle_getInternalID(), MCGIDI_product_parseFromTOM(), MCGIDI_target_heated_parseParticleGammas(), and MCGIDI_target_heated_read().
int MCGIDI_POPs_findParticleIndex (MCGIDI_POPs * pops, char const * name)
Definition at line 104 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 104 of file MCGIDI_pop.cc
References max, min, MCGIDI_POP_s::name, MCGIDI_POPs_s::numberOfPOPs, and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_POPs_addParticleIfNeeded(), and MCGIDI_POPs_findParticle().
void* MCGIDI_POPs_free (MCGIDI_POPs * pops)
Definition at line 41 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 41 of file MCGIDI_pop.cc
References MCGIDI_POPs_release(), and smr_freeMemory().
int MCGIDI_POPs_initial (statusMessageReporting * , MCGIDI_POPs * pops, int size)
Definition at line 30 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 30 of file MCGIDI_pop.cc
References MCGIDI_POPs_s::increment.
Referenced by MCGIDI_POPs_new(), MCGIDI_POPs_release(), and MCGIDI_target_heated_initialize().
MCGIDI_POPs* MCGIDI_POPs_new (statusMessageReporting * smr, int size)
Definition at line 19 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 19 of file MCGIDI_pop.cc
References MCGIDI_POPs_initial(), smr_freeMemory(), and smr_malloc2.
void MCGIDI_POPs_printSortedList (MCGIDI_POPs * pops)
Definition at line 153 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 153 of file MCGIDI_pop.cc
References MCGIDI_POPs_writeSortedList().
int MCGIDI_POPs_release (MCGIDI_POPs * pops)
Definition at line 51 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI_pop.cc
References MCGIDI_POPs_s::first, MCGIDI_POP_free(), MCGIDI_POPs_initial(), MCGIDI_POP_s::next, smr_freeMemory(), and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_POPs_free(), and MCGIDI_target_heated_release().
void MCGIDI_POPs_writeSortedList (MCGIDI_POPs * pops, FILE * f)
Definition at line 143 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 143 of file MCGIDI_pop.cc
References MCGIDI_POP_s::mass_MeV, MCGIDI_POP_s::name, MCGIDI_POPs_s::numberOfPOPs, and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_POPs_printSortedList().