ECCE @ EIC Software: G4EmExtraPhysics Class Reference
G4EmExtraPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/include/G4EmExtraPhysics.hh>
Public Member Functions
G4EmExtraPhysics (G4int ver=1)
G4EmExtraPhysics (const G4String &name)
virtual ~G4EmExtraPhysics ()
void ConstructParticle ()
void ConstructProcess ()
void Synch (G4bool val)
void SynchAll (G4bool val)
void GammaNuclear (G4bool val)
void LENDGammaNuclear (G4bool val)
void ElectroNuclear (G4bool val)
void MuonNuclear (G4bool val)
void GammaToMuMu (G4bool val)
void PositronToMuMu (G4bool val)
void PositronToHadrons (G4bool val)
void GammaToMuMuFactor (G4double val)
void PositronToMuMuFactor (G4double val)
void PositronToHadronsFactor (G4double val)
void NeutrinoActivated (G4bool val)
void NuETotXscActivated (G4bool val)
void SetNuEleCcBias (G4double bf)
void SetNuEleNcBias (G4double bf)
void SetNuNucleusBias (G4double bf)
void SetNuDetectorName (const G4String &dn)
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
void ConstructGammaElectroNuclear ()
void ConstructLENDGammaNuclear (G4CascadeInterface *cascade, G4PhotoNuclearProcess *gnuc)
Private Attributes
G4bool gnActivated
G4bool eActivated
G4bool gLENDActivated
G4bool munActivated
G4bool synActivated
G4bool synActivatedForAll
G4bool gmumuActivated
G4bool pmumuActivated
G4bool phadActivated
G4bool fNuActivated
G4bool fNuETotXscActivated
G4double gmumuFactor
G4double pmumuFactor
G4double phadFactor
G4double fNuEleCcBias
G4double fNuEleNcBias
G4double fNuNucleusBias
G4String fNuDetectorName
G4EmMessenger * theMessenger
G4int verbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 53 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 53 of file G4EmExtraPhysics.hh
Constructor & Destructor Documentation
G4EmExtraPhysics::G4EmExtraPhysics (G4int ver = 1)
Definition at line 109 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 109 of file G4EmExtraPhysics.cc
References bEmExtra, G4cout, G4endl, G4VPhysicsConstructor::SetPhysicsType(), theMessenger, and verbose.
G4EmExtraPhysics::G4EmExtraPhysics (const G4String & name)
Definition at line 136 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 136 of file G4EmExtraPhysics.cc
G4EmExtraPhysics::~G4EmExtraPhysics () virtual
Definition at line 140 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 140 of file G4EmExtraPhysics.cc
References theMessenger.
Member Function Documentation
void G4EmExtraPhysics::ConstructGammaElectroNuclear () private
Definition at line 377 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 377 of file G4EmExtraPhysics.cc
References G4GammaGeneralProcess::AddHadProcess(), ConstructLENDGammaNuclear(), eActivated, G4Electron::Electron(), G4Gamma::Gamma(), G4LossTableManager::GetGammaGeneralProcess(), G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4PhysicsListHelper::GetPhysicsListHelper(), gLENDActivated, G4HadronicParameters::Instance(), G4LossTableManager::Instance(), G4Positron::Positron(), G4HadronicProcess::RegisterMe(), G4PhysicsListHelper::RegisterProcess(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), and G4InuclParticleNames::sp.
Referenced by ConstructProcess().
void G4EmExtraPhysics::ConstructLENDGammaNuclear (G4CascadeInterface * cascade, G4PhotoNuclearProcess * gnuc) private
Definition at line 429 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 429 of file G4EmExtraPhysics.cc
References G4HadronicProcess::AddDataSet(), G4LENDModel::DumpLENDTargetInfo(), G4Exception(), G4Gamma::Gamma(), JustWarning, message(), MeV, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
Referenced by ConstructGammaElectroNuclear().
void G4EmExtraPhysics::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 241 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 241 of file G4EmExtraPhysics.cc
References G4AntiNeutrinoE::AntiNeutrinoE(), G4AntiNeutrinoMu::AntiNeutrinoMu(), G4AntiNeutrinoTau::AntiNeutrinoTau(), G4Electron::Electron(), G4Gamma::Gamma(), G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), G4NeutrinoE::NeutrinoE(), G4NeutrinoMu::NeutrinoMu(), G4NeutrinoTau::NeutrinoTau(), and G4Positron::Positron().
void G4EmExtraPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 257 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 257 of file G4EmExtraPhysics.cc
References G4HadronicProcess::AddDataSet(), G4GammaGeneralProcess::AddMMProcess(), G4AntiNeutrinoE::AntiNeutrinoE(), G4AntiNeutrinoMu::AntiNeutrinoMu(), G4AntiNeutrinoTau::AntiNeutrinoTau(), ConstructGammaElectroNuclear(), G4InuclParticleNames::electron, G4Electron::Electron(), fNuActivated, fNuDetectorName, fNuEleCcBias, fNuEleNcBias, fNuETotXscActivated, fNuNucleusBias, G4cout, G4endl, G4Gamma::Gamma(), G4LossTableManager::GetGammaGeneralProcess(), G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGStable(), G4PhysicsListHelper::GetPhysicsListHelper(), gmumuActivated, gmumuFactor, gnActivated, G4LossTableManager::Instance(), max, munActivated, G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), G4NeutrinoE::NeutrinoE(), G4NeutrinoMu::NeutrinoMu(), G4NeutrinoTau::NeutrinoTau(), particle, phadActivated, phadFactor, pmumuActivated, pmumuFactor, G4InuclParticleNames::positron, G4Positron::Positron(), G4HadronicProcess::RegisterMe(), G4PhysicsListHelper::RegisterProcess(), G4MuNeutrinoNucleusProcess::SetBiasingFactor(), G4NeutrinoElectronProcess::SetBiasingFactor(), G4NeutrinoElectronTotXsc::SetBiasingFactors(), G4NeutrinoElectronProcess::SetBiasingFactors(), G4eeToHadrons::SetCrossSecFactor(), G4AnnihiToMuPair::SetCrossSecFactor(), G4GammaConversionToMuons::SetCrossSecFactor(), G4InuclParticleNames::sp, synActivated, synActivatedForAll, and verbose.
void G4EmExtraPhysics::ElectroNuclear (G4bool val)
Definition at line 167 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 167 of file G4EmExtraPhysics.cc
References eActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::GammaNuclear (G4bool val)
Definition at line 157 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 157 of file G4EmExtraPhysics.cc
References gnActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::GammaToMuMu (G4bool val)
Definition at line 177 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 177 of file G4EmExtraPhysics.cc
References gmumuActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::GammaToMuMuFactor (G4double val)
Definition at line 192 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 192 of file G4EmExtraPhysics.cc
References gmumuFactor.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::LENDGammaNuclear (G4bool val)
Definition at line 162 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 162 of file G4EmExtraPhysics.cc
References gLENDActivated.
Referenced by G4EmMessenger::SetNewValue(), and Shielding::Shielding().
void G4EmExtraPhysics::MuonNuclear (G4bool val)
Definition at line 172 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 172 of file G4EmExtraPhysics.cc
References munActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::NeutrinoActivated (G4bool val)
Definition at line 209 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 209 of file G4EmExtraPhysics.cc
References fNuActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::NuETotXscActivated (G4bool val)
Definition at line 214 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 214 of file G4EmExtraPhysics.cc
References fNuETotXscActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::PositronToHadrons (G4bool val)
Definition at line 187 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 187 of file G4EmExtraPhysics.cc
References phadActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::PositronToHadronsFactor (G4double val)
Definition at line 202 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 202 of file G4EmExtraPhysics.cc
References phadFactor.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::PositronToMuMu (G4bool val)
Definition at line 182 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 182 of file G4EmExtraPhysics.cc
References pmumuActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::PositronToMuMuFactor (G4double val)
Definition at line 197 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 197 of file G4EmExtraPhysics.cc
References pmumuFactor.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::SetNuDetectorName (const G4String & dn)
Definition at line 234 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 234 of file G4EmExtraPhysics.cc
References fNuDetectorName.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::SetNuEleCcBias (G4double bf)
Definition at line 219 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 219 of file G4EmExtraPhysics.cc
References fNuEleCcBias.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::SetNuEleNcBias (G4double bf)
Definition at line 224 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 224 of file G4EmExtraPhysics.cc
References fNuEleNcBias.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::SetNuNucleusBias (G4double bf)
Definition at line 229 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 229 of file G4EmExtraPhysics.cc
References fNuNucleusBias.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::Synch (G4bool val)
Definition at line 146 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 146 of file G4EmExtraPhysics.cc
References synActivated.
Referenced by G4EmMessenger::SetNewValue().
void G4EmExtraPhysics::SynchAll (G4bool val)
Definition at line 151 of file G4EmExtraPhysics.cc.
View newest version in sPHENIX GitHub at line 151 of file G4EmExtraPhysics.cc
References synActivated, and synActivatedForAll.
Referenced by G4EmMessenger::SetNewValue().
Member Data Documentation
G4bool G4EmExtraPhysics::eActivated private
Definition at line 95 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 95 of file G4EmExtraPhysics.hh
Referenced by ConstructGammaElectroNuclear(), and ElectroNuclear().
G4bool G4EmExtraPhysics::fNuActivated private
Definition at line 103 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 103 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and NeutrinoActivated().
G4String G4EmExtraPhysics::fNuDetectorName private
Definition at line 113 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 113 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and SetNuDetectorName().
G4double G4EmExtraPhysics::fNuEleCcBias private
Definition at line 109 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 109 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and SetNuEleCcBias().
G4double G4EmExtraPhysics::fNuEleNcBias private
Definition at line 110 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 110 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and SetNuEleNcBias().
G4bool G4EmExtraPhysics::fNuETotXscActivated private
Definition at line 104 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 104 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and NuETotXscActivated().
G4double G4EmExtraPhysics::fNuNucleusBias private
Definition at line 111 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 111 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and SetNuNucleusBias().
G4bool G4EmExtraPhysics::gLENDActivated private
Definition at line 96 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 96 of file G4EmExtraPhysics.hh
Referenced by ConstructGammaElectroNuclear(), and LENDGammaNuclear().
G4bool G4EmExtraPhysics::gmumuActivated private
Definition at line 100 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 100 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and GammaToMuMu().
G4double G4EmExtraPhysics::gmumuFactor private
Definition at line 106 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 106 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and GammaToMuMuFactor().
G4bool G4EmExtraPhysics::gnActivated private
Definition at line 94 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 94 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and GammaNuclear().
G4bool G4EmExtraPhysics::munActivated private
Definition at line 97 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 97 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and MuonNuclear().
G4bool G4EmExtraPhysics::phadActivated private
Definition at line 102 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 102 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and PositronToHadrons().
G4double G4EmExtraPhysics::phadFactor private
Definition at line 108 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 108 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and PositronToHadronsFactor().
G4bool G4EmExtraPhysics::pmumuActivated private
Definition at line 101 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 101 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and PositronToMuMu().
G4double G4EmExtraPhysics::pmumuFactor private
Definition at line 107 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 107 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and PositronToMuMuFactor().
G4bool G4EmExtraPhysics::synActivated private
Definition at line 98 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 98 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), Synch(), and SynchAll().
G4bool G4EmExtraPhysics::synActivatedForAll private
Definition at line 99 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 99 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and SynchAll().
G4EmMessenger* G4EmExtraPhysics::theMessenger private
Definition at line 115 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 115 of file G4EmExtraPhysics.hh
Referenced by G4EmExtraPhysics(), and ~G4EmExtraPhysics().
G4int G4EmExtraPhysics::verbose private
Definition at line 116 of file G4EmExtraPhysics.hh.
View newest version in sPHENIX GitHub at line 116 of file G4EmExtraPhysics.hh
Referenced by ConstructProcess(), and G4EmExtraPhysics().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/include/G4EmExtraPhysics.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/src/G4EmExtraPhysics.cc