ECCE @ EIC Software: G4eIonisationSpectrum Class Reference
G4eIonisationSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4eIonisationSpectrum.hh>
Public Member Functions
G4eIonisationSpectrum ()
~G4eIonisationSpectrum ()
G4double Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition *pd=0) const
G4double AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition *pd=0) const
G4double SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition *pd=0) const
G4double MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z=0, const G4ParticleDefinition *pd=0) const
G4double Excitation (G4int Z, G4double e) const
void PrintData () const
Public Member Functions inherited from G4VEnergySpectrum
G4VEnergySpectrum ()
virtual ~G4VEnergySpectrum ()
Private Member Functions
G4double IntSpectrum (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double AverageValue (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double Function (G4double x, const G4DataVector &p) const
G4eIonisationSpectrum (const G4eIonisationSpectrum &)
G4eIonisationSpectrum & operator= (const G4eIonisationSpectrum &right)
Private Attributes
G4eIonisationParameters * theParam
G4double lowestE
G4double factor
G4int iMax
G4int verbose
Detailed Description
Definition at line 63 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 63 of file G4eIonisationSpectrum.hh
Constructor & Destructor Documentation
G4eIonisationSpectrum::G4eIonisationSpectrum ()
Definition at line 61 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 61 of file G4eIonisationSpectrum.cc
References theParam.
G4eIonisationSpectrum::~G4eIonisationSpectrum ()
Definition at line 71 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 71 of file G4eIonisationSpectrum.cc
References theParam.
G4eIonisationSpectrum::G4eIonisationSpectrum (const G4eIonisationSpectrum &) private
Member Function Documentation
G4double G4eIonisationSpectrum::AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 172 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 172 of file G4eIonisationSpectrum.cc
References AverageValue(), G4InuclSpecialFunctions::bindingEnergy(), source.hepunit::electron_mass_c2, energy, Function(), G4cout, G4endl, iMax, G4AtomicTransitionManager::Instance(), IntSpectrum(), keV, lowestE, max, MaxEnergyOfSecondaries(), MeV, min, G4eIonisationParameters::Parameter(), theParam, G4InuclParticleNames::tm, verbose, x, x1, and x2.
G4double G4eIonisationSpectrum::AverageValue (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 516 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 516 of file G4eIonisationSpectrum.cc
References dx, G4Exp(), iMax, max, sum, x1, x2, y1, and y2.
Referenced by AverageEnergy().
G4double G4eIonisationSpectrum::Excitation (G4int Z, G4double e) const inline virtual
Implements G4VEnergySpectrum.
Definition at line 128 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 128 of file G4eIonisationSpectrum.hh
References G4eIonisationParameters::Excitation(), and theParam.
G4double G4eIonisationSpectrum::Function (G4double x, const G4DataVector & p) const inline private
Definition at line 118 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eIonisationSpectrum.hh
References f, iMax, and x.
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4double G4eIonisationSpectrum::IntSpectrum (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 432 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 432 of file G4eIonisationSpectrum.cc
References dx, G4cout, G4endl, G4Exp(), iMax, max, sum, x1, x2, y1, and y2.
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4double G4eIonisationSpectrum::MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 600 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 600 of file G4eIonisationSpectrum.cc
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4eIonisationSpectrum& G4eIonisationSpectrum::operator= (const G4eIonisationSpectrum & right) private
void G4eIonisationSpectrum::PrintData (void) const virtual
Implements G4VEnergySpectrum.
Definition at line 595 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 595 of file G4eIonisationSpectrum.cc
References G4eIonisationParameters::PrintData(), and theParam.
G4double G4eIonisationSpectrum::Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 77 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 77 of file G4eIonisationSpectrum.cc
References G4InuclSpecialFunctions::bindingEnergy(), source.hepunit::electron_mass_c2, energy, Function(), G4cout, G4endl, iMax, G4AtomicTransitionManager::Instance(), IntSpectrum(), keV, lowestE, max, MaxEnergyOfSecondaries(), min, G4eIonisationParameters::Parameter(), theParam, G4InuclParticleNames::tm, verbose, x, x1, and x2.
G4double G4eIonisationSpectrum::SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 264 of file G4eIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 264 of file G4eIonisationSpectrum.cc
References G4InuclSpecialFunctions::bindingEnergy(), dx, source.hepunit::electron_mass_c2, energy, factor, Function(), G4cout, G4endl, G4Exp(), G4UniformRand, iMax, G4AtomicTransitionManager::Instance(), IntSpectrum(), keV, lowestE, max, MaxEnergyOfSecondaries(), MeV, min, G4eIonisationParameters::Parameter(), theParam, G4InuclParticleNames::tm, verbose, x, x1, x2, z1, and z2.
Member Data Documentation
G4double G4eIonisationSpectrum::factor private
Definition at line 112 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eIonisationSpectrum.hh
Referenced by SampleEnergy().
G4int G4eIonisationSpectrum::iMax private
Definition at line 113 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eIonisationSpectrum.hh
Referenced by AverageEnergy(), AverageValue(), Function(), IntSpectrum(), Probability(), and SampleEnergy().
G4double G4eIonisationSpectrum::lowestE private
Definition at line 111 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eIonisationSpectrum.hh
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4eIonisationParameters* G4eIonisationSpectrum::theParam private
Definition at line 110 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eIonisationSpectrum.hh
Referenced by AverageEnergy(), Excitation(), G4eIonisationSpectrum(), PrintData(), Probability(), SampleEnergy(), and ~G4eIonisationSpectrum().
G4int G4eIonisationSpectrum::verbose private
Definition at line 114 of file G4eIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eIonisationSpectrum.hh
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4eIonisationSpectrum.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4eIonisationSpectrum.cc