ECCE @ EIC Software: G4XXXStoredViewer Class Reference
G4XXXStoredViewer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXStoredViewer.hh>
Public Member Functions
G4XXXStoredViewer (G4VSceneHandler &, const G4String &name)
virtual ~G4XXXStoredViewer ()
void SetView ()
void ClearView ()
void DrawView ()
void ShowView ()
Public Member Functions inherited from G4VViewer
G4VViewer (G4VSceneHandler &, G4int id, const G4String &name="")
virtual ~G4VViewer ()
virtual void Initialise ()
virtual void ResetView ()
void RefreshView ()
virtual void FinishView ()
std::vector< G4ThreeVector > ComputeFlyThrough (G4Vector3D *)
const G4String & GetName () const
const G4String & GetShortName () const
void SetName (const G4String &)
G4int GetViewId () const
G4VSceneHandler * GetSceneHandler () const
const G4ViewParameters & GetViewParameters () const
const G4ViewParameters & GetDefaultViewParameters () const
virtual const std::vector
< G4ModelingParameters::VisAttributesModifier > * GetPrivateVisAttributesModifiers () const
void SetViewParameters (const G4ViewParameters &vp)
void SetDefaultViewParameters (const G4ViewParameters &vp)
const G4VisAttributes * GetApplicableVisAttributes (const G4VisAttributes *) const
void SetNeedKernelVisit (G4bool need)
void NeedKernelVisit ()
void ProcessView ()
Protected Member Functions
void KernelVisitDecision ()
G4bool CompareForKernelVisit (G4ViewParameters &)
void DrawFromStore ()
Protected Member Functions inherited from G4VViewer
void SetTouchable (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath)
void TouchableSetVisibility (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, G4bool visibility)
void TouchableSetColour (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, const G4Colour &)
Protected Attributes
G4ViewParameters fLastVP
Protected Attributes inherited from G4VViewer
G4VSceneHandler & fSceneHandler
G4int fViewId
G4String fName
G4String fShortName
G4ViewParameters fVP
G4ViewParameters fDefaultVP
G4bool fNeedKernelVisit
Detailed Description
Definition at line 38 of file G4XXXStoredViewer.hh.
View newest version in sPHENIX GitHub at line 38 of file G4XXXStoredViewer.hh
Constructor & Destructor Documentation
G4XXXStoredViewer::G4XXXStoredViewer (G4VSceneHandler & sceneHandler, const G4String & name)
Definition at line 42 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 42 of file G4XXXStoredViewer.cc
G4XXXStoredViewer::~G4XXXStoredViewer () virtual
Definition at line 46 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 46 of file G4XXXStoredViewer.cc
Member Function Documentation
void G4XXXStoredViewer::ClearView (void) virtual
Implements G4VViewer.
Definition at line 54 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 54 of file G4XXXStoredViewer.cc
References G4cout, and G4endl.
G4bool G4XXXStoredViewer::CompareForKernelVisit (G4ViewParameters & lastVP) protected
Definition at line 112 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 112 of file G4XXXStoredViewer.cc
References G4VViewer::fVP, G4ViewParameters::GetBackgroundColour(), G4ViewParameters::GetCBDAlgorithmNumber(), G4ViewParameters::GetCBDParameters(), G4VisAttributes::GetColour(), G4ViewParameters::GetDefaultTextVisAttributes(), G4ViewParameters::GetDefaultVisAttributes(), G4ViewParameters::GetDrawingStyle(), G4ViewParameters::GetExplodeFactor(), G4ViewParameters::GetNoOfSides(), G4ViewParameters::GetNumberOfCloudPoints(), G4ViewParameters::GetVisAttributesModifiers(), G4ViewParameters::GetVisibleDensity(), G4ViewParameters::IsAuxEdgeVisible(), G4ViewParameters::IsCulling(), G4ViewParameters::IsCullingCovered(), G4ViewParameters::IsCullingInvisible(), G4ViewParameters::IsDensityCulling(), G4ViewParameters::IsExplode(), and G4ViewParameters::IsMarkerNotHidden().
Referenced by KernelVisitDecision().
void G4XXXStoredViewer::DrawFromStore () protected
Definition at line 157 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 157 of file G4XXXStoredViewer.cc
References G4VViewer::fName, and G4VViewer::fSceneHandler.
Referenced by DrawView().
void G4XXXStoredViewer::DrawView () virtual
Implements G4VViewer.
Definition at line 60 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 60 of file G4XXXStoredViewer.cc
References DrawFromStore(), G4VViewer::FinishView(), G4VViewer::fNeedKernelVisit, G4cout, G4endl, KernelVisitDecision(), and G4VViewer::ProcessView().
void G4XXXStoredViewer::KernelVisitDecision () protected
Definition at line 98 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 98 of file G4XXXStoredViewer.cc
References CompareForKernelVisit(), fLastVP, G4VViewer::fSceneHandler, G4VViewer::fVP, and G4VViewer::NeedKernelVisit().
Referenced by DrawView().
void G4XXXStoredViewer::SetView () virtual
Implements G4VViewer.
Definition at line 48 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 48 of file G4XXXStoredViewer.cc
References G4cout, and G4endl.
void G4XXXStoredViewer::ShowView (void) virtual
Reimplemented from G4VViewer.
Definition at line 92 of file G4XXXStoredViewer.cc.
View newest version in sPHENIX GitHub at line 92 of file G4XXXStoredViewer.cc
References G4cout, and G4endl.
Member Data Documentation
G4ViewParameters G4XXXStoredViewer::fLastVP protected
Definition at line 50 of file G4XXXStoredViewer.hh.
View newest version in sPHENIX GitHub at line 50 of file G4XXXStoredViewer.hh
Referenced by KernelVisitDecision().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXStoredViewer.hh
geant4/tree/geant4-10.6-release/source/visualization/XXX/src/G4XXXStoredViewer.cc