ECCE @ EIC Software: B3DetectorConstruction Class Reference
B3DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3DetectorConstruction.hh>
Public Member Functions
B3DetectorConstruction ()
virtual ~B3DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
B3DetectorConstruction ()
virtual ~B3DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void DefineMaterials ()
Private Attributes
G4bool fCheckOverlaps
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction class to define materials and geometry.
Crystals are positioned in Ring, with an appropriate rotation matrix. Several copies of Ring are placed in the full detector.
Definition at line 44 of file B3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 44 of file B3DetectorConstruction.hh
Constructor & Destructor Documentation
B3DetectorConstruction::B3DetectorConstruction ()
Definition at line 50 of file B3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 50 of file B3DetectorConstruction.cc
References DefineMaterials().
B3DetectorConstruction::~B3DetectorConstruction () virtual
Definition at line 59 of file B3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 59 of file B3DetectorConstruction.cc
B3DetectorConstruction::B3DetectorConstruction ()
virtual B3DetectorConstruction::~B3DetectorConstruction () virtual
Member Function Documentation
G4VPhysicalVolume * B3DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 82 of file B3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 82 of file B3DetectorConstruction.cc
References cm, deg, Acts::Test::dX, Acts::Test::dY, fCheckOverlaps, G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, BlackHoleGeometry::gap, G4VisAttributes::GetInvisible(), G4Material::GetMaterialTable(), G4NistManager::Instance(), mm, phi, physWorld, CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), G4LogicalVolume::SetVisAttributes(), Acts::Test::transform, and twopi.
virtual G4VPhysicalVolume* B3DetectorConstruction::Construct () virtual
Implements G4VUserDetectorConstruction.
virtual void B3DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
void B3DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 252 of file B3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 252 of file B3DetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4SDManager::GetSDMpointer(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VUserDetectorConstruction::SetSensitiveDetector(), and G4SDManager::SetVerboseLevel().
void B3DetectorConstruction::DefineMaterials () private
Definition at line 64 of file B3DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 64 of file B3DetectorConstruction.cc
References G4Material::AddElement(), cm3, G4NistManager::FindOrBuildElement(), Acts::UnitConstants::g, and G4NistManager::Instance().
Referenced by B3DetectorConstruction().
void B3DetectorConstruction::DefineMaterials () private
Member Data Documentation
G4bool B3DetectorConstruction::fCheckOverlaps private
Definition at line 57 of file B3DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 57 of file B3DetectorConstruction.hh
Referenced by Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/include/B3DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/src/B3DetectorConstruction.cc
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/src/B3DetectorConstruction.cc