ECCE @ EIC Software: G3MatTable Class Reference
G3MatTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MatTable.hh>
Public Member Functions
G3MatTable ()
virtual ~G3MatTable ()
G4Material * get (G4int id) const
void put (G4int id, G4Material *material)
void Clear ()
Private Attributes
G3MaterialVector * fMatVector
Detailed Description
Definition at line 52 of file G3MatTable.hh.
View newest version in sPHENIX GitHub at line 52 of file G3MatTable.hh
Constructor & Destructor Documentation
G3MatTable::G3MatTable ()
Definition at line 32 of file G3MatTable.cc.
View newest version in sPHENIX GitHub at line 32 of file G3MatTable.cc
References fMatVector.
G3MatTable::~G3MatTable () virtual
Definition at line 37 of file G3MatTable.cc.
View newest version in sPHENIX GitHub at line 37 of file G3MatTable.cc
References Clear(), and fMatVector.
Member Function Documentation
void G3MatTable::Clear ()
Definition at line 58 of file G3MatTable.cc.
View newest version in sPHENIX GitHub at line 58 of file G3MatTable.cc
References a, and fMatVector.
Referenced by ~G3MatTable().
G4Material * G3MatTable::get (G4int id) const
Definition at line 43 of file G3MatTable.cc.
View newest version in sPHENIX GitHub at line 43 of file G3MatTable.cc
References fMatVector, G3MatTableEntry::GetID(), and G3MatTableEntry::GetMaterial().
Referenced by G4gstmed().
void G3MatTable::put (G4int id, G4Material * material)
Definition at line 52 of file G3MatTable.cc.
View newest version in sPHENIX GitHub at line 52 of file G3MatTable.cc
References fMatVector.
Referenced by G4gsmate(), and G4gsmixt().
Member Data Documentation
G3MaterialVector* G3MatTable::fMatVector private
Definition at line 66 of file G3MatTable.hh.
View newest version in sPHENIX GitHub at line 66 of file G3MatTable.hh
Referenced by Clear(), G3MatTable(), get(), put(), and ~G3MatTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MatTable.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3MatTable.cc