ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/pyEzgeom.cc File Reference
pyEzgeom.cc File Reference
#include <boost/python.hpp>
#include "EzDetectorConstruction.hh"
#include "G4EzWorld.hh"
#include "G4EzVolume.hh"
#include "G4RunManager.hh"
#include "G4VSensitiveDetector.hh"
Namespaces
namespace pyEZgeom
Functions
void pyEZgeom::Construct ()
void pyEZgeom::ResetWorld (G4double dx, G4double dy, G4double dz)
void pyEZgeom::ResizeWorld (G4double dx, G4double dy, G4double dz)
void pyEZgeom::SetWorldMaterial (G4Material *amaterial)
void pyEZgeom::SetWorldVisibility (G4bool qvis)
pyEZgeom::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_CreateTubeVolume, CreateTubeVolume, 4, 6) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_CreateConeVolume
BOOST_PYTHON_MODULE (_ezgeom)
Variables
pyEZgeom::CreateConeVolume
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_CreateSphereVolume,
CreateSphereVolume,
3, 7) G4VPhysicalVolume
*(G4EzVolume G4VPhysicalVolume
*(G4EzVolume::* pyEZgeom::f2_PlaceIt)(const G4Transform3D &, G4int, G4EzVolume *) = &G4EzVolume::PlaceIt
void(G4EzVolume::* pyEZgeom::f1_SetColor)(const G4Color &) = &G4EzVolume::SetColor
void(G4EzVolume::* pyEZgeom::f2_SetColor)(G4double, G4double, G4double) = &G4EzVolume::SetColor
Function Documentation
BOOST_PYTHON_MODULE (_ezgeom)
Definition at line 115 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 115 of file pyEzgeom.cc
References pyEMSTDpl::Construct(), G4EzVolume::CreateBoxVolume(), G4EzVolume::CreateConeVolume(), G4EzVolume::CreateOrbVolume(), G4EzVolume::CreateSphereVolume(), G4EzVolume::CreateTubeVolume(), pyG4VisAttributes::f1_SetColor, pyEZgeom::f2_PlaceIt, pyG4VisAttributes::f2_SetColor, G4EzVolume::GetMaterial(), G4EzVolume::GetSolid(), G4EzVolume::ReplicateIt(), pyEZgeom::ResetWorld(), pyEZgeom::ResizeWorld(), G4EzVolume::SetMaterial(), G4EzVolume::SetSensitiveDetector(), G4EzVolume::SetSolid(), G4EzVolume::SetVisibility(), pyEZgeom::SetWorldMaterial(), pyEZgeom::SetWorldVisibility(), and G4EzVolume::VoxelizeIt().