ECCE @ EIC Software: G4ParticleHPProduct Class Reference
G4ParticleHPProduct Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPProduct.hh>
Classes
struct toBeCached
Public Member Functions
G4ParticleHPProduct ()
~G4ParticleHPProduct ()
void Init (std::istream &aDataFile, G4ParticleDefinition *projectile)
G4int GetMultiplicity (G4double anEnergy)
G4ReactionProductVector * Sample (G4double anEnergy, G4int nParticles)
G4double GetMeanYield (G4double anEnergy)
void SetProjectileRP (G4ReactionProduct *aIncidentPart)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4double MeanEnergyOfThisInteraction ()
G4double GetQValue ()
G4double GetMassCode ()
G4double GetMass ()
Private Attributes
G4double theMassCode
G4double theMass
G4int theIsomerFlag
G4double theGroundStateQValue
G4double theActualStateQValue
G4int theDistLaw
G4ParticleHPVector theYield
G4VParticleHPEnergyAngular * theDist
G4Cache< toBeCached > fCache
G4HPMultiMethod theMultiplicityMethod
Detailed Description
Definition at line 52 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPProduct.hh
Constructor & Destructor Documentation
G4ParticleHPProduct::G4ParticleHPProduct () inline
Definition at line 65 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPProduct.hh
References fCache, G4HPMultiBetweenInts, G4HPMultiPoisson, G4Cache< VALTYPE >::Put(), theActualStateQValue, theDist, theDistLaw, theGroundStateQValue, theIsomerFlag, theMass, theMassCode, and theMultiplicityMethod.
G4ParticleHPProduct::~G4ParticleHPProduct () inline
Definition at line 94 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPProduct.hh
References theDist.
Member Function Documentation
G4double G4ParticleHPProduct::GetMass () inline
Definition at line 222 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 222 of file G4ParticleHPProduct.hh
References theMass.
G4double G4ParticleHPProduct::GetMassCode () inline
Definition at line 221 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 221 of file G4ParticleHPProduct.hh
References theMassCode.
G4double G4ParticleHPProduct::GetMeanYield (G4double anEnergy) inline
Definition at line 174 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ParticleHPProduct.hh
References G4ParticleHPVector::GetY(), and theYield.
G4int G4ParticleHPProduct::GetMultiplicity (G4double anEnergy)
Definition at line 44 of file G4ParticleHPProduct.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPProduct.cc
References fCache, G4cout, G4endl, G4HPMultiPoisson, G4Poisson(), G4Cache< VALTYPE >::Get(), G4ParticleHPVector::GetY(), CLHEP::RandFlat::shoot(), theDist, theMass, theMassCode, theMultiplicityMethod, and theYield.
Referenced by G4ParticleHPEnAngCorrelation::Sample().
G4ReactionProduct* G4ParticleHPProduct::GetProjectileRP () inline
Definition at line 194 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 194 of file G4ParticleHPProduct.hh
References fCache, and G4Cache< VALTYPE >::Get().
G4double G4ParticleHPProduct::GetQValue () inline
Definition at line 214 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 214 of file G4ParticleHPProduct.hh
References theActualStateQValue.
Referenced by G4ParticleHPEnAngCorrelation::Sample().
G4ReactionProduct* G4ParticleHPProduct::GetTarget (void) inline
Definition at line 189 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 189 of file G4ParticleHPProduct.hh
References fCache, and G4Cache< VALTYPE >::Get().
void G4ParticleHPProduct::Init (std::istream & aDataFile, G4ParticleDefinition * projectile) inline
Definition at line 99 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPProduct.hh
References CLHEP::eV, G4cout, G4endl, G4ParticleHPVector::Hash(), G4VParticleHPEnergyAngular::Init(), G4ParticleHPVector::Init(), G4VParticleHPEnergyAngular::SetQValue(), theActualStateQValue, theDist, theDistLaw, theGroundStateQValue, theIsomerFlag, theMass, theMassCode, and theYield.
Referenced by G4ParticleHPEnAngCorrelation::Init().
G4double G4ParticleHPProduct::MeanEnergyOfThisInteraction () inline
Definition at line 199 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 199 of file G4ParticleHPProduct.hh
References fCache, G4Cache< VALTYPE >::Get(), G4VParticleHPEnergyAngular::MeanEnergyOfThisInteraction(), and theDist.
Referenced by G4ParticleHPEnAngCorrelation::Sample().
G4ReactionProductVector * G4ParticleHPProduct::Sample (G4double anEnergy, G4int nParticles)
Definition at line 105 of file G4ParticleHPProduct.cc.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPProduct.cc
References G4VParticleHPEnergyAngular::ClearHistories(), fCache, G4cout, G4endl, G4Cache< VALTYPE >::Get(), G4ReactionProduct::GetDefinition(), G4ReactionProduct::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4VParticleHPEnergyAngular::Sample(), G4VParticleHPEnergyAngular::SetProjectileRP(), G4VParticleHPEnergyAngular::SetTarget(), theDist, theMass, theMassCode, and tmp.
Referenced by G4ParticleHPEnAngCorrelation::Sample(), and G4ParticleHPEnAngCorrelation::SampleOne().
void G4ParticleHPProduct::SetProjectileRP (G4ReactionProduct * aIncidentPart) inline
Definition at line 179 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPProduct.hh
References fCache, and G4Cache< VALTYPE >::Get().
void G4ParticleHPProduct::SetTarget (G4ReactionProduct * aTarget) inline
Definition at line 184 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ParticleHPProduct.hh
References fCache, and G4Cache< VALTYPE >::Get().
Member Data Documentation
G4Cache<toBeCached> G4ParticleHPProduct::fCache private
Definition at line 239 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 239 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), GetMultiplicity(), GetProjectileRP(), GetTarget(), MeanEnergyOfThisInteraction(), Sample(), SetProjectileRP(), and SetTarget().
G4double G4ParticleHPProduct::theActualStateQValue private
Definition at line 232 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 232 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), GetQValue(), and Init().
G4VParticleHPEnergyAngular* G4ParticleHPProduct::theDist private
Definition at line 235 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 235 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), GetMultiplicity(), Init(), MeanEnergyOfThisInteraction(), Sample(), and ~G4ParticleHPProduct().
G4int G4ParticleHPProduct::theDistLaw private
Definition at line 233 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 233 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), and Init().
G4double G4ParticleHPProduct::theGroundStateQValue private
Definition at line 231 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 231 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), and Init().
G4int G4ParticleHPProduct::theIsomerFlag private
Definition at line 230 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), and Init().
G4double G4ParticleHPProduct::theMass private
Definition at line 229 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 229 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), GetMass(), GetMultiplicity(), Init(), and Sample().
G4double G4ParticleHPProduct::theMassCode private
Definition at line 228 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 228 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), GetMassCode(), GetMultiplicity(), Init(), and Sample().
G4HPMultiMethod G4ParticleHPProduct::theMultiplicityMethod private
Definition at line 241 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 241 of file G4ParticleHPProduct.hh
Referenced by G4ParticleHPProduct(), and GetMultiplicity().
G4ParticleHPVector G4ParticleHPProduct::theYield private
Definition at line 234 of file G4ParticleHPProduct.hh.
View newest version in sPHENIX GitHub at line 234 of file G4ParticleHPProduct.hh
Referenced by GetMeanYield(), GetMultiplicity(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPProduct.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPProduct.cc