ECCE @ EIC Software: ExGflash1SensitiveDetector Class Reference
ExGflash1SensitiveDetector Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflash1SensitiveDetector.hh>
Public Member Functions
ExGflash1SensitiveDetector (G4String, ExGflash1DetectorConstruction *det)
~ExGflash1SensitiveDetector ()
virtual void Initialize (G4HCofThisEvent *)
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual G4bool ProcessHits (G4GFlashSpot *aSpot, G4TouchableHistory *)
virtual void EndOfEvent (G4HCofThisEvent *)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Public Member Functions inherited from G4VGFlashSensitiveDetector
G4VGFlashSensitiveDetector ()
G4VGFlashSensitiveDetector (const G4VGFlashSensitiveDetector &)
virtual ~G4VGFlashSensitiveDetector ()
G4bool operator== (const G4VGFlashSensitiveDetector &right) const
G4bool operator!= (const G4VGFlashSensitiveDetector &right) const
G4bool Hit (G4GFlashSpot *aSpot)
Private Attributes
ExGflashHitsCollection * fCaloHitsCollection
ExGflash1DetectorConstruction * fDetector
G4int fHCID
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 45 of file ExGflash1SensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 45 of file ExGflash1SensitiveDetector.hh
Constructor & Destructor Documentation
ExGflash1SensitiveDetector::ExGflash1SensitiveDetector (G4String name, ExGflash1DetectorConstruction * det)
Definition at line 44 of file ExGflash1SensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 44 of file ExGflash1SensitiveDetector.cc
References G4VSensitiveDetector::collectionName, and G4CollectionNameVector::insert().
ExGflash1SensitiveDetector::~ExGflash1SensitiveDetector ()
Definition at line 54 of file ExGflash1SensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 54 of file ExGflash1SensitiveDetector.cc
Member Function Documentation
void ExGflash1SensitiveDetector::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 69 of file ExGflash1SensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 69 of file ExGflash1SensitiveDetector.cc
void ExGflash1SensitiveDetector::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 59 of file ExGflash1SensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 59 of file ExGflash1SensitiveDetector.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, fCaloHitsCollection, fHCID, G4VSensitiveDetector::GetCollectionID(), and G4VSensitiveDetector::SensitiveDetectorName.
G4bool ExGflash1SensitiveDetector::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) virtual
Implements G4VSensitiveDetector.
Definition at line 74 of file ExGflash1SensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 74 of file ExGflash1SensitiveDetector.cc
References e, fCaloHitsCollection, fDetector, ExGflash1DetectorConstruction::GetCristal(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4TouchableHistory::GetVolume(), G4THitsCollection< T >::insert(), ExGflashHit::SetCrystalNum(), ExGflashHit::SetEdep(), and ExGflashHit::SetPos().
G4bool ExGflash1SensitiveDetector::ProcessHits (G4GFlashSpot * aSpot, G4TouchableHistory * ROhist) virtual
Implements G4VGFlashSensitiveDetector.
Definition at line 105 of file ExGflash1SensitiveDetector.cc.
View newest version in sPHENIX GitHub at line 105 of file ExGflash1SensitiveDetector.cc
References e, fCaloHitsCollection, fDetector, ExGflash1DetectorConstruction::GetCristal(), GFlashEnergySpot::GetEnergy(), G4GFlashSpot::GetEnergySpot(), GFlashEnergySpot::GetPosition(), G4GFlashSpot::GetTouchableHandle(), G4VTouchable::GetVolume(), G4THitsCollection< T >::insert(), ExGflashHit::SetCrystalNum(), ExGflashHit::SetEdep(), and ExGflashHit::SetPos().
Member Data Documentation
ExGflashHitsCollection* ExGflash1SensitiveDetector::fCaloHitsCollection private
Definition at line 57 of file ExGflash1SensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 57 of file ExGflash1SensitiveDetector.hh
Referenced by Initialize(), and ProcessHits().
ExGflash1DetectorConstruction* ExGflash1SensitiveDetector::fDetector private
Definition at line 58 of file ExGflash1SensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 58 of file ExGflash1SensitiveDetector.hh
Referenced by ProcessHits().
G4int ExGflash1SensitiveDetector::fHCID private
Definition at line 59 of file ExGflash1SensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 59 of file ExGflash1SensitiveDetector.hh
Referenced by Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflash1SensitiveDetector.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/src/ExGflash1SensitiveDetector.cc