ECCE @ EIC Software: G4LENDFission Class Reference
G4LENDFission Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDFission.hh>
Public Member Functions
G4LENDFission (G4ParticleDefinition *pd)
~G4LENDFission ()
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
Public Member Functions inherited from G4LENDModel
G4LENDModel (G4String name="LENDModel")
~G4LENDModel ()
void ChangeDefaultEvaluation (G4String name)
void AllowNaturalAbundanceTarget ()
void AllowAnyCandidateTarget ()
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpLENDTargetInfo (G4bool force=false)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void InitialiseModel ()
Additional Inherited Members
Protected Member Functions inherited from G4LENDModel
void create_used_target_map ()
void recreate_used_target_map ()
G4GIDI_target * get_target_from_map (G4int nuclear_code)
G4HadFinalState * returnUnchanged (const G4HadProjectile &aTrack, G4HadFinalState *theResult)
Protected Attributes inherited from G4LENDModel
G4ParticleDefinition * proj
G4LENDManager * lend_manager
std::map< G4int,
G4LENDUsedTarget * > usedTarget_map
Detailed Description
Definition at line 46 of file G4LENDFission.hh.
View newest version in sPHENIX GitHub at line 46 of file G4LENDFission.hh
Constructor & Destructor Documentation
G4LENDFission::G4LENDFission (G4ParticleDefinition * pd) inline
Definition at line 51 of file G4LENDFission.hh.
View newest version in sPHENIX GitHub at line 51 of file G4LENDFission.hh
References G4LENDModel::create_used_target_map(), and G4LENDModel::proj.
G4LENDFission::~G4LENDFission () inline
Definition at line 61 of file G4LENDFission.hh.
View newest version in sPHENIX GitHub at line 61 of file G4LENDFission.hh
Member Function Documentation
G4HadFinalState * G4LENDFission::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Reimplemented from G4LENDModel.
Definition at line 31 of file G4LENDFission.cc.
View newest version in sPHENIX GitHub at line 31 of file G4LENDFission.cc
References G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), G4Gamma::Gamma(), G4LENDModel::get_target_from_map(), G4Nucleus::GetA_asInt(), G4GIDI_target::getFissionFinalState(), G4HadProjectile::GetGlobalTime(), G4IonTable::GetIonTable(), G4Nucleus::GetIsotope(), G4HadProjectile::GetKineticEnergy(), G4Isotope::Getm(), G4HadProjectile::GetMaterial(), G4LENDManager::GetNucleusEncoding(), G4HadFinalState::GetNumberOfSecondaries(), G4HadFinalState::GetSecondary(), G4Material::GetTemperature(), G4Nucleus::GetZ_asInt(), int(), G4LENDModel::lend_manager, MeV, MyRNG(), G4Neutron::Neutron(), G4LENDModel::returnUnchanged(), second, G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetStatusChange(), stopAndKill, G4HadronicInteraction::theParticleChange, and Acts::VectorHelpers::time().
const std::pair< G4double, G4double > G4LENDFission::GetFatalEnergyCheckLevels () const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 103 of file G4LENDFission.cc.
View newest version in sPHENIX GitHub at line 103 of file G4LENDFission.cc
References DBL_MAX, and perCent.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDFission.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDFission.cc