ECCE @ EIC Software: G4VTransactionManager Class Reference
G4VTransactionManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VTransactionManager.hh>
Public Member Functions
G4VTransactionManager ()
virtual ~G4VTransactionManager ()
void SetVerboseLevel (int v)
virtual G4bool SelectReadFile (std::string obj, std::string file)=0
virtual G4bool SelectWriteFile (std::string obj, std::string file)=0
virtual G4bool StartUpdate ()=0
virtual G4bool StartRead ()=0
virtual void Commit ()=0
virtual void Abort ()=0
Protected Attributes
G4int m_verbose
Detailed Description
Definition at line 40 of file G4VTransactionManager.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VTransactionManager.hh
Constructor & Destructor Documentation
G4VTransactionManager::G4VTransactionManager () inline
Definition at line 43 of file G4VTransactionManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VTransactionManager.hh
virtual G4VTransactionManager::~G4VTransactionManager () inline virtual
Definition at line 46 of file G4VTransactionManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VTransactionManager.hh
Member Function Documentation
virtual void G4VTransactionManager::Abort () pure virtual
Referenced by G4PersistencyManager::Retrieve(), and G4PersistencyManager::Store().
virtual void G4VTransactionManager::Commit () pure virtual
Referenced by G4PersistencyManager::Retrieve(), and G4PersistencyManager::Store().
virtual G4bool G4VTransactionManager::SelectReadFile (std::string obj, std::string file) pure virtual
virtual G4bool G4VTransactionManager::SelectWriteFile (std::string obj, std::string file) pure virtual
void G4VTransactionManager::SetVerboseLevel (int v) inline
Definition at line 50 of file G4VTransactionManager.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VTransactionManager.hh
References m_verbose, and v.
Referenced by G4PersistencyManager::SetVerboseLevel().
virtual G4bool G4VTransactionManager::StartRead () pure virtual
virtual G4bool G4VTransactionManager::StartUpdate () pure virtual
Member Data Documentation
G4int G4VTransactionManager::m_verbose protected
Definition at line 72 of file G4VTransactionManager.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VTransactionManager.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VTransactionManager.hh