ECCE @ EIC Software: F04SimpleSolenoid Class Reference
F04SimpleSolenoid Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04SimpleSolenoid.hh>
Public Member Functions
F04SimpleSolenoid (G4double, G4double, G4LogicalVolume *, G4ThreeVector)
Default constructor.
virtual ~F04SimpleSolenoid ()
Destructor.
virtual G4double GetLength ()
GetLength() returns the length of the solenoid.
virtual G4double GetWidth ()
GetWidth() returns the solenoid diameter.
virtual G4double GetHeight ()
GetHeight() returns the solenoid diameter.
void SetFringeZ (G4double z)
SetFringeZ(G4double) sets the solenoid fringe field z-length.
G4double GetFringeZ ()
GetFringeZ() returns the solenoid fringe field z-length.
G4bool IsOutside (G4ThreeVector &local) const
IsOutside() returns true when outside the solenoid.
G4bool IsWithin (G4ThreeVector &local) const
IsWithin() returns true when inside the solenoid.
virtual void AddFieldValue (const G4double point[4], G4double field[6]) const
Public Member Functions inherited from F04ElementField
F04ElementField (const G4ThreeVector, G4LogicalVolume *)
Constructor.
void Construct ()
the actual implementation constructs the F04ElementField
virtual ~F04ElementField ()
Destructor.
void SetMaxStep (G4double stp)
SetMaxStep(G4double) sets the max. step size.
G4double GetMaxStep ()
GetMaxStep() returns the max. step size.
void SetColor (G4String c)
SetColor(G4String) sets the color.
G4String GetColor ()
GetColor() returns the color.
void SetGlobalPoint (const G4double point[4])
bool IsInBoundingBox (const G4double point[4]) const
Private Attributes
G4double fBfield
G4double fFringeZ
G4double fFieldLength
G4double fFieldRadius
Additional Inherited Members
Static Public Member Functions inherited from F04ElementField
static G4VisAttributes * GetVisAttribute (G4String color)
GetVisAttribute() returns the appropriate G4VisAttributes.
Protected Attributes inherited from F04ElementField
G4LogicalVolume * fVolume
G4AffineTransform fGlobal2local
Detailed Description
Definition at line 43 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 43 of file F04SimpleSolenoid.hh
Constructor & Destructor Documentation
F04SimpleSolenoid::F04SimpleSolenoid (G4double Bz, G4double fz, G4LogicalVolume * lv, G4ThreeVector c)
Default constructor.
Definition at line 41 of file F04SimpleSolenoid.cc.
View newest version in sPHENIX GitHub at line 41 of file F04SimpleSolenoid.cc
References Acts::IntegrationTest::Bz, fBfield, fFieldLength, fFieldRadius, fFringeZ, F04ElementField::fVolume, and G4LogicalVolume::GetSolid().
virtual F04SimpleSolenoid::~F04SimpleSolenoid () inline virtual
Destructor.
Definition at line 51 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 51 of file F04SimpleSolenoid.hh
Member Function Documentation
void F04SimpleSolenoid::AddFieldValue (const G4double point[4], G4double field[6]) const virtual
AddFieldValue() adds the field for this solenoid into field[]. point[] is in global coordinates.
Implements F04ElementField.
Reimplemented in F04FocusSolenoid.
Definition at line 54 of file F04SimpleSolenoid.cc.
View newest version in sPHENIX GitHub at line 54 of file F04SimpleSolenoid.cc
References B(), fBfield, F04ElementField::fGlobal2local, G4AffineTransform::Inverse(), IsOutside(), local, G4AffineTransform::TransformAxis(), and G4AffineTransform::TransformPoint().
G4double F04SimpleSolenoid::GetFringeZ () inline
GetFringeZ() returns the solenoid fringe field z-length.
Definition at line 66 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 66 of file F04SimpleSolenoid.hh
References fFringeZ.
virtual G4double F04SimpleSolenoid::GetHeight () inline virtual
GetHeight() returns the solenoid diameter.
Implements F04ElementField.
Definition at line 60 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 60 of file F04SimpleSolenoid.hh
References fFieldRadius.
virtual G4double F04SimpleSolenoid::GetLength () inline virtual
GetLength() returns the length of the solenoid.
Implements F04ElementField.
Definition at line 54 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 54 of file F04SimpleSolenoid.hh
References fFieldLength.
virtual G4double F04SimpleSolenoid::GetWidth () inline virtual
GetWidth() returns the solenoid diameter.
Implements F04ElementField.
Definition at line 57 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 57 of file F04SimpleSolenoid.hh
References fFieldRadius.
G4bool F04SimpleSolenoid::IsOutside (G4ThreeVector & local) const
IsOutside() returns true when outside the solenoid.
Definition at line 75 of file F04SimpleSolenoid.cc.
View newest version in sPHENIX GitHub at line 75 of file F04SimpleSolenoid.cc
References fFieldLength, fFieldRadius, r, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by F04FocusSolenoid::AddFieldValue(), and AddFieldValue().
G4bool F04SimpleSolenoid::IsWithin (G4ThreeVector & local) const
IsWithin() returns true when inside the solenoid.
Definition at line 85 of file F04SimpleSolenoid.cc.
View newest version in sPHENIX GitHub at line 85 of file F04SimpleSolenoid.cc
References fFieldLength, fFieldRadius, r, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void F04SimpleSolenoid::SetFringeZ (G4double z) inline
SetFringeZ(G4double) sets the solenoid fringe field z-length.
Definition at line 63 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 63 of file F04SimpleSolenoid.hh
References fFringeZ, and z.
Member Data Documentation
G4double F04SimpleSolenoid::fBfield private
Definition at line 80 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 80 of file F04SimpleSolenoid.hh
Referenced by AddFieldValue(), and F04SimpleSolenoid().
G4double F04SimpleSolenoid::fFieldLength private
Definition at line 84 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 84 of file F04SimpleSolenoid.hh
Referenced by F04SimpleSolenoid(), GetLength(), IsOutside(), and IsWithin().
G4double F04SimpleSolenoid::fFieldRadius private
Definition at line 85 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 85 of file F04SimpleSolenoid.hh
Referenced by F04SimpleSolenoid(), GetHeight(), GetWidth(), IsOutside(), and IsWithin().
G4double F04SimpleSolenoid::fFringeZ private
Definition at line 82 of file F04SimpleSolenoid.hh.
View newest version in sPHENIX GitHub at line 82 of file F04SimpleSolenoid.hh
Referenced by F04SimpleSolenoid(), GetFringeZ(), and SetFringeZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04SimpleSolenoid.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04SimpleSolenoid.cc