ECCE @ EIC Software: G4RTRun Class Reference
G4RTRun Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTRun.hh>
Public Member Functions
G4RTRun ()
virtual ~G4RTRun ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4THitsMap< G4Colour > * GetMap () const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Member Functions
G4Colour GetSurfaceColour (G4RayTrajectoryPoint *)
G4Colour GetMixedColour (G4Colour, G4Colour, G4double)
G4Colour Attenuate (G4RayTrajectoryPoint *, G4Colour)
G4bool ValidColour (const G4VisAttributes *)
Private Attributes
G4THitsMap< G4Colour > * colorMap
G4Colour backgroundColour
G4ThreeVector lightDirection
G4double attenuationLength
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Definition at line 50 of file G4RTRun.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RTRun.hh
Constructor & Destructor Documentation
G4RTRun::G4RTRun ()
Definition at line 46 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 46 of file G4RTRun.cc
References attenuationLength, G4TheRayTracer::attenuationLength, backgroundColour, G4TheRayTracer::backgroundColour, colorMap, lightDirection, G4TheRayTracer::lightDirection, and G4TheMTRayTracer::theInstance.
G4RTRun::~G4RTRun () virtual
Definition at line 55 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 55 of file G4RTRun.cc
References G4VTHitsMap< T, Map_t >::clear(), and colorMap.
Member Function Documentation
G4Colour G4RTRun::Attenuate (G4RayTrajectoryPoint * point, G4Colour sourceCol) private
Definition at line 152 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 152 of file G4RTRun.cc
References attenuationLength, G4Colour::GetAlpha(), G4Colour::GetBlue(), G4VisAttributes::GetColour(), G4Colour::GetGreen(), G4RayTrajectoryPoint::GetPreStepAtt(), G4Colour::GetRed(), G4RayTrajectoryPoint::GetStepLength(), ValidColour(), and BlackHoleGeometry::visible.
Referenced by RecordEvent().
G4THitsMap<G4Colour>* G4RTRun::GetMap () const inline
Definition at line 63 of file G4RTRun.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RTRun.hh
References colorMap.
Referenced by G4TheMTRayTracer::CreateBitMap().
G4Colour G4RTRun::GetMixedColour (G4Colour surfCol, G4Colour transCol, G4double weight) private
Definition at line 143 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 143 of file G4RTRun.cc
References alpha, G4Colour::GetAlpha(), G4Colour::GetBlue(), G4Colour::GetGreen(), G4Colour::GetRed(), and weight.
Referenced by GetSurfaceColour(), and RecordEvent().
G4Colour G4RTRun::GetSurfaceColour (G4RayTrajectoryPoint * point) private
Definition at line 95 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 95 of file G4RTRun.cc
References G4Colour::GetAlpha(), G4Colour::GetBlue(), G4VisAttributes::GetColour(), G4Colour::GetGreen(), GetMixedColour(), G4RayTrajectoryPoint::GetPostStepAtt(), G4RayTrajectoryPoint::GetPreStepAtt(), G4Colour::GetRed(), G4RayTrajectoryPoint::GetSurfaceNormal(), lightDirection, CLHEP::normal(), ValidColour(), and weight.
Referenced by RecordEvent().
void G4RTRun::Merge (const G4Run * aLocalRun) virtual
Reimplemented from G4Run.
Definition at line 88 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 88 of file G4RTRun.cc
References colorMap, and G4Run::Merge().
void G4RTRun::RecordEvent (const G4Event * evt) virtual
Reimplemented from G4Run.
Definition at line 61 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 61 of file G4RTRun.cc
References G4VTHitsMap< T, Map_t >::add(), Attenuate(), backgroundColour, colorMap, G4Colour::GetAlpha(), G4Event::GetEventID(), GetMixedColour(), G4RayTrajectory::GetPointC(), G4RayTrajectory::GetPointEntries(), G4RayTrajectoryPoint::GetPostStepAtt(), GetSurfaceColour(), G4Event::GetTrajectoryContainer(), and weight.
G4bool G4RTRun::ValidColour (const G4VisAttributes * visAtt) private
Definition at line 180 of file G4RTRun.cc.
View newest version in sPHENIX GitHub at line 180 of file G4RTRun.cc
References G4VisAttributes::GetForcedDrawingStyle(), G4VisAttributes::IsForceDrawingStyle(), G4VisAttributes::IsVisible(), and G4VisAttributes::wireframe.
Referenced by Attenuate(), and GetSurfaceColour().
Member Data Documentation
G4double G4RTRun::attenuationLength private
Definition at line 68 of file G4RTRun.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RTRun.hh
Referenced by Attenuate(), and G4RTRun().
G4Colour G4RTRun::backgroundColour private
Definition at line 66 of file G4RTRun.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RTRun.hh
Referenced by G4RTRun(), and RecordEvent().
G4THitsMap<G4Colour>* G4RTRun::colorMap private
Definition at line 60 of file G4RTRun.hh.
View newest version in sPHENIX GitHub at line 60 of file G4RTRun.hh
Referenced by G4RTRun(), GetMap(), Merge(), RecordEvent(), and ~G4RTRun().
G4ThreeVector G4RTRun::lightDirection private
Definition at line 67 of file G4RTRun.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RTRun.hh
Referenced by G4RTRun(), and GetSurfaceColour().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTRun.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RTRun.cc