ECCE @ EIC Software: G4coutDestination Class Reference
G4coutDestination Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4coutDestination.hh>
Public Types
using Transformer = std::function< G4bool(G4String &)>
Public Member Functions
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
virtual G4int ReceiveG4cout (const G4String &msg)
virtual G4int ReceiveG4cerr (const G4String &msg)
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Protected Attributes
std::vector< Transformer > transformersCout
std::vector< Transformer > transformersCerr
Static Protected Attributes
static G4MTGLOB_DLL
G4coutDestination * masterG4coutDestination = nullptr
Detailed Description
Definition at line 45 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 45 of file G4coutDestination.hh
Member Typedef Documentation
using G4coutDestination::Transformer = std::function<G4bool(G4String&)>
Definition at line 61 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 61 of file G4coutDestination.hh
Constructor & Destructor Documentation
G4coutDestination::G4coutDestination () default
G4coutDestination::~G4coutDestination () virtual
Definition at line 38 of file G4coutDestination.cc.
View newest version in sPHENIX GitHub at line 38 of file G4coutDestination.cc
Member Function Documentation
void G4coutDestination::AddCerrTransformer (const Transformer & t) inline
Definition at line 66 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 66 of file G4coutDestination.hh
References transformersCerr.
Referenced by G4MTcoutDestination::HandleFileCerr().
void G4coutDestination::AddCerrTransformer (Transformer && t) inline
Definition at line 68 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 68 of file G4coutDestination.hh
References t, and transformersCerr.
void G4coutDestination::AddCoutTransformer (const Transformer & t) inline
Definition at line 62 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 62 of file G4coutDestination.hh
References transformersCout.
Referenced by G4MTcoutDestination::AddMasterOutput(), G4MTcoutDestination::HandleFileCout(), and G4MTcoutDestination::SetDefaultOutput().
void G4coutDestination::AddCoutTransformer (Transformer && t) inline
Definition at line 64 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 64 of file G4coutDestination.hh
References t, and transformersCout.
G4int G4coutDestination::ReceiveG4cerr (const G4String & msg) virtual
Reimplemented in G4UIGainServer, G4UIterminal, G4MulticoutDestination, G4UIGAG, G4FilecoutDestination, G4UIsession, G4BuffercoutDestination, G4MasterForwardcoutDestination, G4LockcoutDestination, G4ZMQServer, G4PyCoutDestination, G4VMPIsession, and PHG4UIsession.
Definition at line 53 of file G4coutDestination.cc.
View newest version in sPHENIX GitHub at line 53 of file G4coutDestination.cc
Referenced by G4LockcoutDestination::ReceiveG4cerr(), and ReceiveG4cerr_().
G4int G4coutDestination::ReceiveG4cerr_ (const G4String & msg)
Definition at line 79 of file G4coutDestination.cc.
View newest version in sPHENIX GitHub at line 79 of file G4coutDestination.cc
References m, ReceiveG4cerr(), t, transformersCerr, and transformersCout.
Referenced by G4MasterForwardcoutDestination::ReceiveG4cerr().
G4int G4coutDestination::ReceiveG4cout (const G4String & msg) virtual
Reimplemented in G4UIGainServer, G4UIterminal, G4MulticoutDestination, G4UIGAG, G4FilecoutDestination, G4UIsession, G4BuffercoutDestination, G4MasterForwardcoutDestination, G4LockcoutDestination, G4ZMQServer, G4PyCoutDestination, G4VMPIsession, and PHG4UIsession.
Definition at line 47 of file G4coutDestination.cc.
View newest version in sPHENIX GitHub at line 47 of file G4coutDestination.cc
Referenced by G4MTcoutDestination::DumpBuffer(), G4LockcoutDestination::ReceiveG4cout(), and ReceiveG4cout_().
G4int G4coutDestination::ReceiveG4cout_ (const G4String & msg)
Definition at line 59 of file G4coutDestination.cc.
View newest version in sPHENIX GitHub at line 59 of file G4coutDestination.cc
References m, ReceiveG4cout(), and transformersCout.
Referenced by G4MasterForwardcoutDestination::ReceiveG4cout().
void G4coutDestination::ResetTransformers () virtual
Definition at line 42 of file G4coutDestination.cc.
View newest version in sPHENIX GitHub at line 42 of file G4coutDestination.cc
References transformersCerr, and transformersCout.
Member Data Documentation
G4coutDestination * G4coutDestination::masterG4coutDestination = nullptr static protected
Definition at line 94 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 94 of file G4coutDestination.hh
Referenced by G4MasterForwardcoutDestination::ReceiveG4cerr(), and G4MasterForwardcoutDestination::ReceiveG4cout().
std::vector<Transformer> G4coutDestination::transformersCerr protected
Definition at line 97 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 97 of file G4coutDestination.hh
Referenced by AddCerrTransformer(), ReceiveG4cerr_(), and ResetTransformers().
std::vector<Transformer> G4coutDestination::transformersCout protected
Definition at line 96 of file G4coutDestination.hh.
View newest version in sPHENIX GitHub at line 96 of file G4coutDestination.hh
Referenced by AddCoutTransformer(), ReceiveG4cerr_(), ReceiveG4cout_(), and ResetTransformers().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4coutDestination.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4coutDestination.cc