ECCE @ EIC Software: XrayTelDetectorConstruction Class Reference
XrayTelDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelDetectorConstruction.hh>
Public Member Functions
XrayTelDetectorConstruction ()
~XrayTelDetectorConstruction ()
G4VPhysicalVolume * Construct ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void ConstructTelescope ()
void ConstructFocalPlane ()
Private Attributes
G4double world_x
G4double world_y
G4double world_z
G4VPhysicalVolume * physicalWorld
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 59 of file XrayTelDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 59 of file XrayTelDetectorConstruction.hh
Constructor & Destructor Documentation
XrayTelDetectorConstruction::XrayTelDetectorConstruction ()
Definition at line 74 of file XrayTelDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 74 of file XrayTelDetectorConstruction.cc
References cm, world_x, world_y, and world_z.
XrayTelDetectorConstruction::~XrayTelDetectorConstruction ()
Definition at line 81 of file XrayTelDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 81 of file XrayTelDetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * XrayTelDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 84 of file XrayTelDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 84 of file XrayTelDetectorConstruction.cc
References cm3, ConstructFocalPlane(), ConstructTelescope(), E, Acts::UnitConstants::g, G4VisAttributes::GetInvisible(), kelvin, kStateGas, mole, pascal, physicalWorld, world_x, world_y, and world_z.
void XrayTelDetectorConstruction::ConstructFocalPlane () private
Definition at line 341 of file XrayTelDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 341 of file XrayTelDetectorConstruction.cc
References cm, cm3, deg, e, Acts::UnitConstants::g, m, mm, mole, and physicalWorld.
Referenced by Construct().
void XrayTelDetectorConstruction::ConstructTelescope () private
Definition at line 127 of file XrayTelDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 127 of file XrayTelDetectorConstruction.cc
References G4Material::AddElement(), C(), cm, cm3, deg, Acts::UnitConstants::g, G4VisAttributes::GetInvisible(), H, mm, mole, physicalWorld, and G4LogicalVolume::SetVisAttributes().
Referenced by Construct().
Member Data Documentation
G4VPhysicalVolume* XrayTelDetectorConstruction::physicalWorld private
Definition at line 74 of file XrayTelDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file XrayTelDetectorConstruction.hh
Referenced by Construct(), ConstructFocalPlane(), and ConstructTelescope().
G4double XrayTelDetectorConstruction::world_x private
Definition at line 69 of file XrayTelDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file XrayTelDetectorConstruction.hh
Referenced by Construct(), and XrayTelDetectorConstruction().
G4double XrayTelDetectorConstruction::world_y private
Definition at line 70 of file XrayTelDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 70 of file XrayTelDetectorConstruction.hh
Referenced by Construct(), and XrayTelDetectorConstruction().
G4double XrayTelDetectorConstruction::world_z private
Definition at line 71 of file XrayTelDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 71 of file XrayTelDetectorConstruction.hh
Referenced by Construct(), and XrayTelDetectorConstruction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/src/XrayTelDetectorConstruction.cc