ECCE @ EIC Software: G4TwistTrapAlphaSide Class Reference
G4TwistTrapAlphaSide Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistTrapAlphaSide.hh>
Public Member Functions
G4TwistTrapAlphaSide (const G4String &name, G4double PhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph, G4double AngleSide)
virtual ~G4TwistTrapAlphaSide ()
virtual G4ThreeVector GetNormal (const G4ThreeVector &xx, G4bool isGlobal=false)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate=kValidateWithTol)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[])
G4TwistTrapAlphaSide (__void__ &)
Public Member Functions inherited from G4VTwistSurface
G4VTwistSurface (const G4String &name)
G4VTwistSurface (const G4String &name, const G4RotationMatrix &rot, const G4ThreeVector &tlate, G4int handedness, const EAxis axis1, const EAxis axis2, G4double axis0min=-kInfinity, G4double axis1min=-kInfinity, G4double axis0max=kInfinity, G4double axis1max=kInfinity)
virtual ~G4VTwistSurface ()
virtual G4int AmIOnLeftSide (const G4ThreeVector &me, const G4ThreeVector &vec, G4bool withTol=true)
virtual G4double DistanceToBoundary (G4int areacode, G4ThreeVector &xx, const G4ThreeVector &p)
virtual G4double DistanceToIn (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceToOut (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceTo (const G4ThreeVector &gp, G4ThreeVector &gxx)
void DebugPrint () const
virtual G4String GetName () const
virtual void GetBoundaryParameters (const G4int &areacode, G4ThreeVector &d, G4ThreeVector &x0, G4int &boundarytype) const
virtual G4ThreeVector GetBoundaryAtPZ (G4int areacode, const G4ThreeVector &p) const
G4double DistanceToPlaneWithV (const G4ThreeVector &p, const G4ThreeVector &v, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &t1, const G4ThreeVector &t2, G4ThreeVector &xx, G4ThreeVector &n)
G4double DistanceToLine (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &d, G4ThreeVector &xx)
G4bool IsAxis0 (G4int areacode) const
G4bool IsAxis1 (G4int areacode) const
G4bool IsOutside (G4int areacode) const
G4bool IsInside (G4int areacode, G4bool testbitmode=false) const
G4bool IsBoundary (G4int areacode, G4bool testbitmode=false) const
G4bool IsCorner (G4int areacode, G4bool testbitmode=false) const
G4bool IsValidNorm () const
G4bool IsSameBoundary (G4VTwistSurface *surface1, G4int areacode1, G4VTwistSurface *surface2, G4int areacode2) const
G4int GetAxisType (G4int areacode, G4int whichaxis) const
G4ThreeVector ComputeGlobalPoint (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &gp) const
G4ThreeVector ComputeGlobalDirection (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalDirection (const G4ThreeVector &gp) const
void SetAxis (G4int i, const EAxis axis)
void SetNeighbours (G4VTwistSurface *ax0min, G4VTwistSurface *ax1min, G4VTwistSurface *ax0max, G4VTwistSurface *ax1max)
G4int GetNode (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetFace (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetEdgeVisibility (G4int i, G4int j, G4int m, G4int n, G4int number, G4int orientation)
G4VTwistSurface (__void__ &)
Private Member Functions
virtual G4int GetAreaCode (const G4ThreeVector &xx, G4bool withTol=true)
virtual void SetCorners ()
virtual void SetBoundaries ()
void GetPhiUAtX (G4ThreeVector p, G4double &phi, G4double &u)
G4ThreeVector ProjectPoint (const G4ThreeVector &p, G4bool isglobal=false)
virtual G4ThreeVector SurfacePoint (G4double phi, G4double u, G4bool isGlobal=false)
virtual G4double GetBoundaryMin (G4double phi)
virtual G4double GetBoundaryMax (G4double phi)
virtual G4double GetSurfaceArea ()
virtual void GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside)
G4ThreeVector NormAng (G4double phi, G4double u)
G4double GetValueA (G4double phi)
G4double GetValueB (G4double phi)
G4double GetValueD (G4double phi)
G4double Xcoef (G4double u, G4double phi)
Private Attributes
G4double fTheta
G4double fPhi
G4double fDy1
G4double fDx1
G4double fDx2
G4double fDy2
G4double fDx3
G4double fDx4
G4double fDz
G4double fAlph
G4double fTAlph
G4double fPhiTwist
G4double fAngleSide
G4double fDx4plus2
G4double fDx4minus2
G4double fDx3plus1
G4double fDx3minus1
G4double fDy2plus1
G4double fDy2minus1
G4double fa1md1
G4double fa2md2
G4double fdeltaX
G4double fdeltaY
Additional Inherited Members
Public Types inherited from G4VTwistSurface
enum EValidate { kDontValidate = 0, kValidateWithTol = 1, kValidateWithoutTol = 2, kUninitialized = 3 }
Static Public Attributes inherited from G4VTwistSurface
static const G4int sOutside = 0x00000000
static const G4int sInside = 0x10000000
static const G4int sBoundary = 0x20000000
static const G4int sCorner = 0x40000000
static const G4int sC0Min1Min = 0x40000101
static const G4int sC0Max1Min = 0x40000201
static const G4int sC0Max1Max = 0x40000202
static const G4int sC0Min1Max = 0x40000102
static const G4int sAxisMin = 0x00000101
static const G4int sAxisMax = 0x00000202
static const G4int sAxisX = 0x00000404
static const G4int sAxisY = 0x00000808
static const G4int sAxisZ = 0x00000C0C
static const G4int sAxisRho = 0x00001010
static const G4int sAxisPhi = 0x00001414
static const G4int sAxis0 = 0x0000FF00
static const G4int sAxis1 = 0x000000FF
static const G4int sSizeMask = 0x00000303
static const G4int sAxisMask = 0x0000FCFC
static const G4int sAreaMask = 0XF0000000
Protected Member Functions inherited from G4VTwistSurface
G4VTwistSurface ** GetNeighbours ()
G4int GetNeighbours (G4int areacode, G4VTwistSurface *surfaces[])
G4ThreeVector GetCorner (G4int areacode) const
void GetBoundaryAxis (G4int areacode, EAxis axis[]) const
void GetBoundaryLimit (G4int areacode, G4double limit[]) const
virtual void SetBoundary (const G4int &axiscode, const G4ThreeVector &direction, const G4ThreeVector &x0, const G4int &boundarytype)
void SetCorner (G4int areacode, G4double x, G4double y, G4double z)
Protected Attributes inherited from G4VTwistSurface
EAxis fAxis [2]
G4double fAxisMin [2]
G4double fAxisMax [2]
CurrentStatus fCurStatWithV
CurrentStatus fCurStat
G4RotationMatrix fRot
G4ThreeVector fTrans
G4int fHandedness
G4SurfCurNormal fCurrentNormal
G4bool fIsValidNorm
G4double kCarTolerance
Detailed Description
Definition at line 41 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 41 of file G4TwistTrapAlphaSide.hh
Constructor & Destructor Documentation
G4TwistTrapAlphaSide::G4TwistTrapAlphaSide (const G4String & name, G4double PhiTwist, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlph, G4double AngleSide)
Definition at line 41 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 41 of file G4TwistTrapAlphaSide.cc
References fa1md1, fa2md2, fAlph, fAngleSide, G4VTwistSurface::fAxis, G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, fdeltaX, fdeltaY, fDx1, fDx2, fDx3, fDx3minus1, fDx3plus1, fDx4, fDx4minus2, fDx4plus2, fDy1, fDy2, fDy2minus1, fDy2plus1, fDz, G4VTwistSurface::fIsValidNorm, fPhi, fPhiTwist, G4VTwistSurface::fRot, fTAlph, fTheta, G4VTwistSurface::fTrans, kInfinity, kYAxis, kZAxis, CLHEP::HepRotation::rotateZ(), CLHEP::Hep3Vector::set(), SetBoundaries(), and SetCorners().
G4TwistTrapAlphaSide::~G4TwistTrapAlphaSide () virtual
Definition at line 125 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 125 of file G4TwistTrapAlphaSide.cc
G4TwistTrapAlphaSide::G4TwistTrapAlphaSide (__void__ & a)
Definition at line 112 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 112 of file G4TwistTrapAlphaSide.cc
Member Function Documentation
G4int G4TwistTrapAlphaSide::DistanceToSurface (const G4ThreeVector & gp, const G4ThreeVector & gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate = kValidateWithTol) virtual
Implements G4VTwistSurface.
Definition at line 188 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 188 of file G4TwistTrapAlphaSide.cc
References Intersection::areacode, c, G4VTwistSurface::ComputeGlobalPoint(), G4VTwistSurface::ComputeLocalDirection(), G4VTwistSurface::ComputeLocalPoint(), Intersection::distance, DistanceSort(), G4VTwistSurface::DistanceToPlaneWithV(), EqualIntersection(), fa1md1, false, FatalException, G4VTwistSurface::fCurStatWithV, fdeltaX, fdeltaY, fDx3minus1, fDx3plus1, fDx4minus2, fDx4plus2, fDy1, fDz, G4JTPolynomialSolver::FindRoots(), fPhiTwist, fTAlph, G4cout, G4endl, G4Exception(), G4VSURFACENXX, GetAreaCode(), G4VTwistSurface::CurrentStatus::GetAreacode(), G4VTwistSurface::CurrentStatus::GetDistance(), G4VTwistSurface::CurrentStatus::GetNXX(), GetPhiUAtX(), G4VTwistSurface::CurrentStatus::GetXX(), G4VTwistSurface::CurrentStatus::IsDone(), G4VTwistSurface::IsInside(), G4VTwistSurface::IsOutside(), G4VTwistSurface::CurrentStatus::IsValid(), Intersection::isvalid, k, G4VTwistSurface::kCarTolerance, kInfinity, G4VTwistSurface::kValidateWithoutTol, G4VTwistSurface::kValidateWithTol, L, NormAng(), num, phi, Intersection::phi, pi, G4VTwistSurface::CurrentStatus::ResetfDone(), CLHEP::Hep3Vector::set(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), G4VTwistSurface::sOutside, SurfacePoint(), theta(), true, Acts::UnitConstants::u, Intersection::u, v, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4int G4TwistTrapAlphaSide::DistanceToSurface (const G4ThreeVector & gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[]) virtual
Implements G4VTwistSurface.
Definition at line 684 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 684 of file G4TwistTrapAlphaSide.cc
References G4VTwistSurface::ComputeGlobalPoint(), G4VTwistSurface::ComputeLocalPoint(), G4VTwistSurface::DistanceToPlane(), G4VTwistSurface::fCurStat, fPhiTwist, G4cout, G4endl, G4VSURFACENXX, G4VTwistSurface::CurrentStatus::GetAreacode(), GetBoundaryMax(), G4VTwistSurface::CurrentStatus::GetDistance(), G4VTwistSurface::CurrentStatus::GetNXX(), GetPhiUAtX(), G4VTwistSurface::CurrentStatus::GetXX(), G4VTwistSurface::CurrentStatus::IsDone(), G4VTwistSurface::kCarTolerance, G4VTwistSurface::kDontValidate, kInfinity, NormAng(), G4VTwistSurface::CurrentStatus::ResetfDone(), CLHEP::Hep3Vector::set(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), G4VTwistSurface::sOutside, SurfacePoint(), and xx.
G4int G4TwistTrapAlphaSide::GetAreaCode (const G4ThreeVector & xx, G4bool withTol = true) private virtual
Implements G4VTwistSurface.
Definition at line 785 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 785 of file G4TwistTrapAlphaSide.cc
References FatalException, G4VTwistSurface::fAxis, G4VTwistSurface::fAxisMax, G4VTwistSurface::fAxisMin, G4cout, G4endl, G4Exception(), GetBoundaryMax(), GetBoundaryMin(), GetPhiUAtX(), G4VTwistSurface::kCarTolerance, kYAxis, kZAxis, phi, G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, G4VTwistSurface::sAxisY, G4VTwistSurface::sAxisZ, G4VTwistSurface::sBoundary, G4VTwistSurface::sCorner, G4VTwistSurface::sInside, and CLHEP::Hep3Vector::z().
Referenced by DistanceToSurface().
G4double G4TwistTrapAlphaSide::GetBoundaryMax (G4double phi) inline private virtual
Implements G4VTwistSurface.
Definition at line 200 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 200 of file G4TwistTrapAlphaSide.hh
References GetValueB().
Referenced by DistanceToSurface(), and GetAreaCode().
G4double G4TwistTrapAlphaSide::GetBoundaryMin (G4double phi) inline private virtual
Implements G4VTwistSurface.
Definition at line 194 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 194 of file G4TwistTrapAlphaSide.hh
References GetValueB().
Referenced by GetAreaCode().
void G4TwistTrapAlphaSide::GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside) private virtual
Implements G4VTwistSurface.
Definition at line 1103 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4TwistTrapAlphaSide.cc
References b, fDz, fPhiTwist, G4VTwistSurface::GetEdgeVisibility(), G4VTwistSurface::GetFace(), G4VTwistSurface::GetNode(), GetValueB(), k, n, phi, SurfacePoint(), Acts::UnitConstants::u, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and z.
G4ThreeVector G4TwistTrapAlphaSide::GetNormal (const G4ThreeVector & xx, G4bool isGlobal = false) virtual
Implements G4VTwistSurface.
Definition at line 134 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 134 of file G4TwistTrapAlphaSide.cc
References G4VTwistSurface::ComputeGlobalDirection(), G4VTwistSurface::ComputeLocalPoint(), G4VTwistSurface::fCurrentNormal, G4cout, G4endl, GetPhiUAtX(), G4VTwistSurface::kCarTolerance, CLHEP::normal(), G4VTwistSurface::G4SurfCurNormal::normal, NormAng(), G4VTwistSurface::G4SurfCurNormal::p, phi, Acts::UnitConstants::u, CLHEP::Hep3Vector::unit(), and xx.
void G4TwistTrapAlphaSide::GetPhiUAtX (G4ThreeVector p, G4double & phi, G4double & u) private
Definition at line 1033 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 1033 of file G4TwistTrapAlphaSide.cc
References fa1md1, fdeltaX, fdeltaY, fDx1, fDx2, fDx3, fDx3minus1, fDx3plus1, fDx4, fDx4minus2, fDx4plus2, fDy1, fDz, fPhiTwist, fTAlph, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToSurface(), GetAreaCode(), GetNormal(), and ProjectPoint().
G4double G4TwistTrapAlphaSide::GetSurfaceArea () inline private virtual
Implements G4VTwistSurface.
Definition at line 206 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 206 of file G4TwistTrapAlphaSide.hh
References fa1md1, fa2md2, fDy1, fDy2, fDz, and fTAlph.
G4double G4TwistTrapAlphaSide::GetValueA (G4double phi) inline private
Definition at line 152 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 152 of file G4TwistTrapAlphaSide.hh
References fDx4minus2, fDx4plus2, and fPhiTwist.
Referenced by Xcoef().
G4double G4TwistTrapAlphaSide::GetValueB (G4double phi) inline private
Definition at line 164 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 164 of file G4TwistTrapAlphaSide.hh
References fDy2minus1, fDy2plus1, and fPhiTwist.
Referenced by GetBoundaryMax(), GetBoundaryMin(), GetFacets(), and Xcoef().
G4double G4TwistTrapAlphaSide::GetValueD (G4double phi) inline private
Definition at line 158 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 158 of file G4TwistTrapAlphaSide.hh
References fDx3minus1, fDx3plus1, and fPhiTwist.
Referenced by Xcoef().
G4ThreeVector G4TwistTrapAlphaSide::NormAng (G4double phi, G4double u) inline private
Definition at line 215 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 215 of file G4TwistTrapAlphaSide.hh
References fa1md1, fdeltaX, fdeltaY, fDx2, fDx3minus1, fDx3plus1, fDx4, fDx4minus2, fDy1, fDz, fPhiTwist, fTAlph, and CLHEP::Hep3Vector::unit().
Referenced by DistanceToSurface(), and GetNormal().
G4ThreeVector G4TwistTrapAlphaSide::ProjectPoint (const G4ThreeVector & p, G4bool isglobal = false) private
Definition at line 1066 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 1066 of file G4TwistTrapAlphaSide.cc
References G4VTwistSurface::fRot, G4VTwistSurface::fTrans, GetPhiUAtX(), CLHEP::HepRotation::inverse(), phi, SurfacePoint(), Acts::UnitConstants::u, and xx.
void G4TwistTrapAlphaSide::SetBoundaries () private virtual
Implements G4VTwistSurface.
Definition at line 987 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 987 of file G4TwistTrapAlphaSide.cc
References FatalException, G4VTwistSurface::fAxis, G4Exception(), G4VTwistSurface::GetCorner(), kYAxis, kZAxis, G4VTwistSurface::sAxis0, G4VTwistSurface::sAxis1, G4VTwistSurface::sAxisMax, G4VTwistSurface::sAxisMin, G4VTwistSurface::sAxisY, G4VTwistSurface::sAxisZ, G4VTwistSurface::sC0Max1Max, G4VTwistSurface::sC0Max1Min, G4VTwistSurface::sC0Min1Max, G4VTwistSurface::sC0Min1Min, G4VTwistSurface::SetBoundary(), and CLHEP::Hep3Vector::unit().
Referenced by G4TwistTrapAlphaSide().
void G4TwistTrapAlphaSide::SetCorners () private virtual
Implements G4VTwistSurface.
Definition at line 918 of file G4TwistTrapAlphaSide.cc.
View newest version in sPHENIX GitHub at line 918 of file G4TwistTrapAlphaSide.cc
References FatalException, G4VTwistSurface::fAxis, fdeltaX, fdeltaY, fDx1, fDx2, fDx3, fDx4, fDy1, fDy2, fDz, fPhiTwist, fTAlph, G4Exception(), kYAxis, kZAxis, G4VTwistSurface::sC0Max1Max, G4VTwistSurface::sC0Max1Min, G4VTwistSurface::sC0Min1Max, G4VTwistSurface::sC0Min1Min, G4VTwistSurface::SetCorner(), x, y, and z.
Referenced by G4TwistTrapAlphaSide().
G4ThreeVector G4TwistTrapAlphaSide::SurfacePoint (G4double phi, G4double u, G4bool isGlobal = false) inline private virtual
Implements G4VTwistSurface.
Definition at line 180 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 180 of file G4TwistTrapAlphaSide.hh
References fdeltaX, fdeltaY, fDz, fPhiTwist, G4VTwistSurface::fRot, G4VTwistSurface::fTrans, and Xcoef().
Referenced by DistanceToSurface(), GetFacets(), and ProjectPoint().
G4double G4TwistTrapAlphaSide::Xcoef (G4double u, G4double phi) inline private
Definition at line 171 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 171 of file G4TwistTrapAlphaSide.hh
References fTAlph, GetValueA(), GetValueB(), and GetValueD().
Referenced by SurfacePoint().
Member Data Documentation
G4double G4TwistTrapAlphaSide::fa1md1 private
Definition at line 140 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 140 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), GetSurfaceArea(), and NormAng().
G4double G4TwistTrapAlphaSide::fa2md2 private
Definition at line 141 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 141 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), and GetSurfaceArea().
G4double G4TwistTrapAlphaSide::fAlph private
Definition at line 127 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 127 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide().
G4double G4TwistTrapAlphaSide::fAngleSide private
Definition at line 132 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 132 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide().
G4double G4TwistTrapAlphaSide::fdeltaX private
Definition at line 143 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 143 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), NormAng(), SetCorners(), and SurfacePoint().
G4double G4TwistTrapAlphaSide::fdeltaY private
Definition at line 144 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 144 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), NormAng(), SetCorners(), and SurfacePoint().
G4double G4TwistTrapAlphaSide::fDx1 private
Definition at line 118 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 118 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), GetPhiUAtX(), and SetCorners().
G4double G4TwistTrapAlphaSide::fDx2 private
Definition at line 119 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 119 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), GetPhiUAtX(), NormAng(), and SetCorners().
G4double G4TwistTrapAlphaSide::fDx3 private
Definition at line 122 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 122 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), GetPhiUAtX(), and SetCorners().
G4double G4TwistTrapAlphaSide::fDx3minus1 private
Definition at line 137 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 137 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), GetValueD(), and NormAng().
G4double G4TwistTrapAlphaSide::fDx3plus1 private
Definition at line 136 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 136 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), GetValueD(), and NormAng().
G4double G4TwistTrapAlphaSide::fDx4 private
Definition at line 123 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 123 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), GetPhiUAtX(), NormAng(), and SetCorners().
G4double G4TwistTrapAlphaSide::fDx4minus2 private
Definition at line 135 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 135 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), GetValueA(), and NormAng().
G4double G4TwistTrapAlphaSide::fDx4plus2 private
Definition at line 134 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 134 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), and GetValueA().
G4double G4TwistTrapAlphaSide::fDy1 private
Definition at line 117 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 117 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), GetSurfaceArea(), NormAng(), and SetCorners().
G4double G4TwistTrapAlphaSide::fDy2 private
Definition at line 121 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 121 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), GetSurfaceArea(), and SetCorners().
G4double G4TwistTrapAlphaSide::fDy2minus1 private
Definition at line 139 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 139 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), and GetValueB().
G4double G4TwistTrapAlphaSide::fDy2plus1 private
Definition at line 138 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 138 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide(), and GetValueB().
G4double G4TwistTrapAlphaSide::fDz private
Definition at line 125 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 125 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetFacets(), GetPhiUAtX(), GetSurfaceArea(), NormAng(), SetCorners(), and SurfacePoint().
G4double G4TwistTrapAlphaSide::fPhi private
Definition at line 115 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 115 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide().
G4double G4TwistTrapAlphaSide::fPhiTwist private
Definition at line 130 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 130 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetFacets(), GetPhiUAtX(), GetValueA(), GetValueB(), GetValueD(), NormAng(), SetCorners(), and SurfacePoint().
G4double G4TwistTrapAlphaSide::fTAlph private
Definition at line 128 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 128 of file G4TwistTrapAlphaSide.hh
Referenced by DistanceToSurface(), G4TwistTrapAlphaSide(), GetPhiUAtX(), GetSurfaceArea(), NormAng(), SetCorners(), and Xcoef().
G4double G4TwistTrapAlphaSide::fTheta private
Definition at line 114 of file G4TwistTrapAlphaSide.hh.
View newest version in sPHENIX GitHub at line 114 of file G4TwistTrapAlphaSide.hh
Referenced by G4TwistTrapAlphaSide().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistTrapAlphaSide.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4TwistTrapAlphaSide.cc