ECCE @ EIC Software: G4ENDFTapeRead Class Reference
G4ENDFTapeRead Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ENDFTapeRead.hh>
Public Member Functions
G4ENDFTapeRead (G4String FileLocation, G4String FileName, G4FFGEnumerations::YieldType WhichYield, G4FFGEnumerations::FissionCause WhichCause)
G4ENDFTapeRead (G4String FileLocation, G4String FileName, G4FFGEnumerations::YieldType WhichYield, G4FFGEnumerations::FissionCause WhichCause, G4int Verbosity)
G4ENDFTapeRead (std::istringstream &dataStream, G4FFGEnumerations::YieldType WhichYield, G4FFGEnumerations::FissionCause WhichCause, G4int Verbosity)
G4double * G4GetEnergyGroupValues (void)
G4int G4GetNumberOfEnergyGroups (void)
G4int G4GetNumberOfFissionProducts (void)
G4ENDFYieldDataContainer * G4GetYield (G4int WhichYield)
void G4SetVerbosity (G4int WhatVerbosity)
~G4ENDFTapeRead (void)
Protected Member Functions
void Initialize (G4String dataFile)
void Initialize (std::istringstream &dataStream)
Private Member Functions
void ReadInData (std::istringstream &dataStream)
Private Attributes
G4int EnergyGroups_
G4double * EnergyGroupValues_
G4int Verbosity_
G4TableTemplate
< G4ENDFYieldDataContainer > * YieldContainerTable_
const G4FFGEnumerations::YieldType YieldType_
Detailed Description
G4ENDFTapeRead is a class designed to read in data from unformatted ENDF data tapes for MT = 454 or MT = 459, which correspond to independent fission yields and cumulative fission yields, respectively. The data is stored internally and can be recalled one product at a time by calling G4GetNextYield().
Definition at line 48 of file G4ENDFTapeRead.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ENDFTapeRead.hh
Constructor & Destructor Documentation
G4ENDFTapeRead::G4ENDFTapeRead (G4String FileLocation, G4String FileName, G4FFGEnumerations::YieldType WhichYield, G4FFGEnumerations::FissionCause WhichCause)
Default constructor
Usage:
FileLocation: the absolute path to the file
FileName: the name of the data file
WhichYield: INDEPENDENT or CUMULATIVE
WhichCause: SPONTANEOUS or N_INDUCED
Notes: The data will be read in immediately upon construction.
Definition at line 48 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ENDFTapeRead.cc
References Initialize().
G4ENDFTapeRead::G4ENDFTapeRead (G4String FileLocation, G4String FileName, G4FFGEnumerations::YieldType WhichYield, G4FFGEnumerations::FissionCause WhichCause, G4int Verbosity)
Overloaded constructor
Usage:
FileLocation: the absolute path to the file
FileName: the name of the data file
WhichYield: INDEPENDENT or CUMULATIVE
WhichCause: SPONTANEOUS or N_INDUCED
Verbosity: Verbosity level
Notes: The data will be read in immediately upon construction.
Definition at line 61 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ENDFTapeRead.cc
References Initialize().
G4ENDFTapeRead::G4ENDFTapeRead (std::istringstream & dataStream, G4FFGEnumerations::YieldType WhichYield, G4FFGEnumerations::FissionCause WhichCause, G4int Verbosity)
Overloaded constructor
Usage:
DataFile: The absolute path to the data file
WhichYield: INDEPENDENT or CUMULATIVE
WhichCause: SPONTANEOUS or N_INDUCED
Verbosity: Verbosity level
Notes: The data will be read in immediately upon construction.
Definition at line 75 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ENDFTapeRead.cc
References Initialize().
G4ENDFTapeRead::~G4ENDFTapeRead (void)
Default Deconstructor
Definition at line 551 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 551 of file G4ENDFTapeRead.cc
References EnergyGroupValues_, G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, and YieldContainerTable_.
Member Function Documentation
G4double * G4ENDFTapeRead::G4GetEnergyGroupValues (void)
Returns and array containing the values of each of the energy groups
Usage: No arguments required
Notes:
Definition at line 121 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ENDFTapeRead.cc
References EnergyGroupValues_, G4FFG_FUNCTIONENTER__, and G4FFG_FUNCTIONLEAVE__.
Referenced by G4FissionProductYieldDist::Initialize().
G4int G4ENDFTapeRead::G4GetNumberOfEnergyGroups (void)
Returns the number of energy yield groups that were extracted from the ENDF tape file
Usage: No arguments required
Notes:
Definition at line 130 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 130 of file G4ENDFTapeRead.cc
References EnergyGroups_, G4FFG_FUNCTIONENTER__, and G4FFG_FUNCTIONLEAVE__.
Referenced by G4FissionProductYieldDist::Initialize().
G4int G4ENDFTapeRead::G4GetNumberOfFissionProducts (void)
Returns the number of fission products that were extracted from the ENDF tape file
Usage: No arguments required
Notes:
Definition at line 139 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 139 of file G4ENDFTapeRead.cc
References G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, G4TableTemplate< T >::G4GetNumberOfElements(), and YieldContainerTable_.
Referenced by G4FissionProductYieldDist::MakeTrees(), and G4FissionProductYieldDist::ReadProbabilities().
G4ENDFYieldDataContainer * G4ENDFTapeRead::G4GetYield (G4int WhichYield)
Returns the data for the requested fission product
Usage:
WhichYield: 0-based index of the fission product for which to get the yield data
Notes:
This will return a pointer to the next G4FissionYieldContainer. NULL will be returned if no more fission containers exist.
Definition at line 150 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 150 of file G4ENDFTapeRead.cc
References G4FFG_DATA_FUNCTIONENTER__, G4FFG_DATA_FUNCTIONLEAVE__, G4TableTemplate< T >::G4GetContainer(), and YieldContainerTable_.
Referenced by G4FissionProductYieldDist::ReadProbabilities().
void G4ENDFTapeRead::G4SetVerbosity (G4int WhatVerbosity)
Sets the verbosity levels
Usage:
WhichVerbosity: Combination of levels
Notes:
SILENT: All verbose output is repressed
UPDATES: Only high-level internal changes are reported
DAUGHTER_INFO: Displays information about daughter product sampling
NEUTRON_INFO: Displays information about neutron sampling
GAMMA_INFO: Displays information about gamma sampling
ALPHA_INFO: Displays information about alpha sampling
MOMENTUM_INFO: Displays information about momentum balancing
EXTRAPOLATION_INTERPOLATION_INFO: Displays information about any data extrapolation or interpolation that occurs
DEBUG: Reports program flow as it steps through functions
PRINT_ALL: Displays any and all output
Definition at line 165 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 165 of file G4ENDFTapeRead.cc
References G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, and Verbosity_.
Referenced by G4FissionProductYieldDist::G4SetVerbosity().
void G4ENDFTapeRead::Initialize (G4String dataFile) protected
Initialize is a common function called by all constructors.
Definition at line 88 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ENDFTapeRead.cc
References G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), and in.
Referenced by G4ENDFTapeRead().
void G4ENDFTapeRead::Initialize (std::istringstream & dataStream) protected
Initialize is a common function calles by all constructors
Definition at line 97 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ENDFTapeRead.cc
References e, EnergyGroups_, EnergyGroupValues_, G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, ReadInData(), and YieldContainerTable_.
void G4ENDFTapeRead::ReadInData (std::istringstream & dataStream) private
Read in the data from an ENDF data tape.
Definition at line 175 of file G4ENDFTapeRead.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ENDFTapeRead.cc
References b, EnergyGroups_, EnergyGroupValues_, error, G4Exception(), G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, G4TableTemplate< T >::G4GetNewContainer(), G4FFGEnumerations::GROUND_STATE, JustWarning, G4FFGEnumerations::META_1, G4FFGEnumerations::META_2, G4ENDFYieldDataContainer::SetMetaState(), G4ENDFYieldDataContainer::SetProduct(), G4ENDFYieldDataContainer::SetYieldError(), G4ENDFYieldDataContainer::SetYieldProbability(), YieldContainerTable_, and YieldType_.
Referenced by Initialize().
Member Data Documentation
G4int G4ENDFTapeRead::EnergyGroups_ private
Stores the number corresponding to the fission cause that will be extracted Counter for the number of energy groups that were extracted
Definition at line 158 of file G4ENDFTapeRead.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ENDFTapeRead.hh
Referenced by G4GetNumberOfEnergyGroups(), Initialize(), and ReadInData().
G4double* G4ENDFTapeRead::EnergyGroupValues_ private
Array containing the values of the extracted energy groups
Definition at line 160 of file G4ENDFTapeRead.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ENDFTapeRead.hh
Referenced by G4GetEnergyGroupValues(), Initialize(), ReadInData(), and ~G4ENDFTapeRead().
G4int G4ENDFTapeRead::Verbosity_ private
Verbosity level
Definition at line 162 of file G4ENDFTapeRead.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ENDFTapeRead.hh
Referenced by G4SetVerbosity().
G4TableTemplate< G4ENDFYieldDataContainer >* G4ENDFTapeRead::YieldContainerTable_ private
Storage for the extracted data
Definition at line 164 of file G4ENDFTapeRead.hh.
View newest version in sPHENIX GitHub at line 164 of file G4ENDFTapeRead.hh
Referenced by G4GetNumberOfFissionProducts(), G4GetYield(), Initialize(), ReadInData(), and ~G4ENDFTapeRead().
const G4FFGEnumerations::YieldType G4ENDFTapeRead::YieldType_ private
Stores the number corresponding to the yield type that will be extracted
Definition at line 166 of file G4ENDFTapeRead.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ENDFTapeRead.hh
Referenced by ReadInData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ENDFTapeRead.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ENDFTapeRead.cc