ECCE @ EIC Software: HadrontherapyEventAction Class Reference
HadrontherapyEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyEventAction.hh>
Public Member Functions
HadrontherapyEventAction ()
~HadrontherapyEventAction ()
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
void SetPrintModulo (G4int val)
void SetDrawFlag (G4String val)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4String drawFlag
G4int hitsCollectionID
G4int printModulo
HadrontherapyEventActionMessenger * pointerEventMessenger
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 38 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 38 of file HadrontherapyEventAction.hh
Constructor & Destructor Documentation
HadrontherapyEventAction::HadrontherapyEventAction ()
Definition at line 45 of file HadrontherapyEventAction.cc.
View newest version in sPHENIX GitHub at line 45 of file HadrontherapyEventAction.cc
References hitsCollectionID, and pointerEventMessenger.
HadrontherapyEventAction::~HadrontherapyEventAction ()
Definition at line 53 of file HadrontherapyEventAction.cc.
View newest version in sPHENIX GitHub at line 53 of file HadrontherapyEventAction.cc
References pointerEventMessenger.
Member Function Documentation
void HadrontherapyEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Definition at line 59 of file HadrontherapyEventAction.cc.
View newest version in sPHENIX GitHub at line 59 of file HadrontherapyEventAction.cc
References G4SDManager::GetSDMpointer(), and hitsCollectionID.
void HadrontherapyEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 67 of file HadrontherapyEventAction.cc.
View newest version in sPHENIX GitHub at line 67 of file HadrontherapyEventAction.cc
References Fill(), HadrontherapyMatrix::GetInstance(), Acts::UnitConstants::h, hitsCollectionID, k, and MeV.
void HadrontherapyEventAction::SetDrawFlag (G4String val) inline
Definition at line 53 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 53 of file HadrontherapyEventAction.hh
References drawFlag.
Referenced by HadrontherapyEventActionMessenger::SetNewValue().
void HadrontherapyEventAction::SetPrintModulo (G4int val) inline
Definition at line 48 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 48 of file HadrontherapyEventAction.hh
References printModulo.
Referenced by HadrontherapyEventActionMessenger::SetNewValue().
Member Data Documentation
G4String HadrontherapyEventAction::drawFlag private
Definition at line 56 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 56 of file HadrontherapyEventAction.hh
Referenced by SetDrawFlag().
G4int HadrontherapyEventAction::hitsCollectionID private
Definition at line 60 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 60 of file HadrontherapyEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), and HadrontherapyEventAction().
HadrontherapyEventActionMessenger* HadrontherapyEventAction::pointerEventMessenger private
Definition at line 63 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 63 of file HadrontherapyEventAction.hh
Referenced by HadrontherapyEventAction(), and ~HadrontherapyEventAction().
G4int HadrontherapyEventAction::printModulo private
Definition at line 62 of file HadrontherapyEventAction.hh.
View newest version in sPHENIX GitHub at line 62 of file HadrontherapyEventAction.hh
Referenced by SetPrintModulo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyEventAction.cc