ECCE @ EIC Software: G4Pow Class Reference
G4Pow Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4Pow.hh>
Public Member Functions
~G4Pow ()
G4double Z13 (G4int Z) const
G4double A13 (G4double A) const
G4double Z23 (G4int Z) const
G4double A23 (G4double A) const
G4double logZ (G4int Z) const
G4double logA (G4double A) const
G4double logX (G4double x) const
G4double log10Z (G4int Z) const
G4double log10A (G4double A) const
G4double expA (G4double A) const
G4double powZ (G4int Z, G4double y) const
G4double powA (G4double A, G4double y) const
G4double powN (G4double x, G4int n) const
G4double factorial (G4int Z) const
G4double logfactorial (G4int Z) const
Static Public Member Functions
static G4Pow * GetInstance ()
Private Member Functions
G4Pow ()
G4double A13Low (const G4double, const bool) const
G4double A13High (const G4double, const bool) const
G4double logBase (G4double x) const
Private Attributes
const G4double onethird
const G4int max2
G4double maxA
G4double maxLowA
G4double maxA2
G4double maxAexp
G4DataVector ener
G4DataVector logen
G4DataVector pz13
G4DataVector lowa13
G4DataVector lz
G4DataVector lz2
G4DataVector fexp
G4DataVector fact
G4DataVector logfact
Static Private Attributes
static G4Pow * fpInstance = 0
Detailed Description
Definition at line 55 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 55 of file G4Pow.hh
Constructor & Destructor Documentation
G4Pow::~G4Pow ()
Definition at line 130 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 130 of file G4Pow.cc
G4Pow::G4Pow () private
Definition at line 66 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 66 of file G4Pow.cc
References ener, f, fact, FatalException, fexp, G4Exception(), G4Exp(), G4Log(), G4Threading::IsWorkerThread(), logen, logfact, lowa13, lz, lz2, max2, maxA, maxA2, maxAexp, maxLowA, maxZ, onethird, powN(), pz13, and x.
Member Function Documentation
G4double G4Pow::A13 (G4double A) const
Definition at line 135 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 135 of file G4Pow.cc
References a, A(), A13High(), A13Low(), and maxLowA.
Referenced by A23(), G4LFission::Atomas(), G4AntiNuclElastic::CalculateAm(), G4DiffuseElasticV2::CalculateAm(), G4NuclNuclDiffuseElastic::CalculateAm(), G4DiffuseElastic::CalculateAm(), G4DiffuseElasticV2::CalculateNuclearRad(), G4NuclNuclDiffuseElastic::CalculateNuclearRad(), G4DiffuseElastic::CalculateNuclearRad(), G4StatMFMacroCanonical::CalculateTemperature(), G4FermiMomentum::cbrt(), G4QMDMeanField::DoClusterJudgment(), G4ionEffectiveCharge::EffectiveCharge(), G4KM_NucleonEqRhs::EvaluateRhsGivenB(), G4IonFluctuations::Factor(), G4StatMFMacroTemperature::FragsExcitEnergy(), G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), G4QMDParameters::G4QMDParameters(), G4fissionEvent::G4SmpNugDist(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4SigmaPlusField::GetBarrier(), G4SigmaMinusField::GetBarrier(), G4StatMFMicroPartition::GetCoulombEnergy(), G4TripathiLightCrossSection::GetElementCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4QMDNucleus::GetNuclearMass(), G4StatMFMicroPartition::GetPartitionEnergy(), G4WilsonRadius::GetWilsonRMSRadius(), G4NistManager::GetZ13(), G4mplIonisationWithDeltaModel::Initialise(), G4mplIonisationModel::Initialise(), MCGIDI_KalbachMann_S_a_or_b(), G4StatMFChannel::PlaceFragments(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4DipBustGenerator::SampleCosTheta(), G4BetheHeitlerModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4WentzelOKandVIxSection::SampleSingleScattering(), G4QMDGroundStateNucleus::samplingMomentum(), G4ParticleHPKallbachMannSyst::SeparationEnergy(), and G4StatMFChannel::SolveEqOfMotion().
G4double G4Pow::A13High (const G4double a, const bool invert) const private
Definition at line 147 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 147 of file G4Pow.cc
References G4Exp(), G4Log(), maxA, onethird, pz13, and x.
Referenced by A13().
G4double G4Pow::A13Low (const G4double a, const bool invert) const private
Definition at line 162 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 162 of file G4Pow.cc
References lowa13, onethird, x, and y.
Referenced by A13().
G4double G4Pow::A23 (G4double A) const inline
Definition at line 142 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 142 of file G4Pow.hh
References A13(), and x.
Referenced by G4LFission::Atomas(), G4AtimaEnergyLossModel::Bethek_dedx_e(), G4DiffuseElasticV2::CalculateNuclearRad(), G4DiffuseElastic::CalculateNuclearRad(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4IonisParamMat::ComputeIonParameters(), G4QMDMeanField::DoClusterJudgment(), G4ionEffectiveCharge::EffectiveCharge(), G4KM_NucleonEqRhs::G4KM_NucleonEqRhs(), G4NuclearAbrasionGeometry::GetExcitationEnergyOfProjectile(), G4NuclearAbrasionGeometry::GetExcitationEnergyOfTarget(), G4QMDNucleus::GetNuclearMass(), G4ParticleHPJENDLHEData::getXSfromThisIsotope(), G4ComponentBarNucleonNucleusXsc::LoadData(), and G4ParticleHPKallbachMannSyst::SeparationEnergy().
G4double G4Pow::expA (G4double A) const inline
Definition at line 217 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Pow.hh
References a, A(), fexp, G4Exp(), maxAexp, onethird, and x.
Referenced by G4IonFluctuations::Factor(), powA(), and powZ().
G4double G4Pow::factorial (G4int Z) const inline
Definition at line 246 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 246 of file G4Pow.hh
References fact, and Z.
Referenced by G4LegendrePolynomial::EvalAssocLegendrePoly().
G4Pow * G4Pow::GetInstance (void) static
Definition at line 54 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 54 of file G4Pow.cc
References fpInstance.
Referenced by G4ParticleHPKallbachMannSyst::A(), G4FTFAnnihilation::Annihilate(), G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4LFission::Atomas(), G4FissionBarrier::BarashenkovFissionBarrier(), G4HadPhaseSpaceKopylov::BetaKopylov(), G4CascadeFinalStateAlgorithm::BetaKopylov(), G4WilsonAblationModel::BreakItUp(), G4UPiNuclearCrossSection::BuildPhysicsTable(), G4ParticleHPNBodyPhaseSpace::C(), G4QMDMeanField::Cal2BodyQuantities(), G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), G4QuasiElRatios::CalcElTot(), G4StatMFMacroTetraNucleon::CalcEnergy(), G4StatMFMacroTriNucleon::CalcEnergy(), G4StatMFMacroBiNucleon::CalcEnergy(), G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMFMacroMultiNucleon::CalcEntropy(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4IonsKoxCrossSection::calCeValue(), G4StatMFFragment::CalcExcitationEnergy(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMacroTriNucleon::CalcMeanMultiplicity(), G4StatMFMacroTetraNucleon::CalcMeanMultiplicity(), G4StatMFMacroBiNucleon::CalcMeanMultiplicity(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), G4StatMFMicroPartition::CalcPartitionProbability(), G4QuasiElRatios::CalcQF2IN_Ratio(), G4HadronCrossSections::CalcScatteringCrossSections(), G4AntiNuclElastic::CalculateAm(), G4DiffuseElasticV2::CalculateAm(), G4NuclNuclDiffuseElastic::CalculateAm(), G4DiffuseElastic::CalculateAm(), G4MuonVDNuclearModel::CalculateEMVertex(), G4DiffuseElasticV2::CalculateNuclearRad(), G4NuclNuclDiffuseElastic::CalculateNuclearRad(), G4DiffuseElastic::CalculateNuclearRad(), G4StatMFMacroCanonical::CalculateTemperature(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4StatMFMacroMultiNucleon::CalcZARatio(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDMeanField::CalGraduate(), G4FermiMomentum::cbrt(), G4Reggeons::Chi_pomeron(), G4Reggeons::Chi_reggeon(), G4QGSDiffractiveExcitation::ChooseP(), G4DiffractiveExcitation::ChooseP(), G4SingleDiffractiveExcitation::ChooseX(), G4StatMFMacroCanonical::ChooseZ(), G4Clebsch::ClebschGordanCoeff(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4GoudsmitSaundersonMscModel::ComputeGeomPathLength(), G4IonisParamMat::ComputeIonParameters(), G4KalbachCrossSection::ComputePowerParameter(), G4GoudsmitSaundersonMscModel::ComputeTrueStepLength(), G4Fancy3DNucleus::CoulombBarrier(), G4StatMFMicroPartition::CoulombFreeEnergy(), G4DiffractiveExcitation::CreateStrings(), G4XAqmTotal::CrossSection(), G4XAqmElastic::CrossSection(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4ChipsAntiBaryonInelasticXS::CrossSectionFormula(), G4QMDMeanField::DoClusterJudgment(), G4ProjectileFragmentCrossSection::doit(), G4ParticleHPFissionData::DumpPhysicsTable(), G4ParticleHPCaptureData::DumpPhysicsTable(), G4ParticleHPElasticData::DumpPhysicsTable(), G4ParticleHPInelasticData::DumpPhysicsTable(), G4LENDCrossSection::DumpPhysicsTable(), G4LegendrePolynomial::EvalAssocLegendrePoly(), G4KM_NucleonEqRhs::EvaluateRhsGivenB(), G4FPYSamplingOps::EvaluateWattConstants(), G4QuarkExchange::ExciteParticipants(), G4NuclearAbrasionGeometry::F(), G4VCrossSectionSource::FcrossX(), G4InuclSpecialFunctions::FermiEnergy(), G4JTPolynomialSolver::FindRoots(), G4CompetitiveFission::FissionKineticEnergy(), G4StatMFMacroTemperature::FragsExcitEnergy(), G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4AtimaFluctuations::G4AtimaFluctuations(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4InuclSpecialFunctions::G4cbrt(), G4EmCorrections::G4EmCorrections(), G4ExcitationHandler::G4ExcitationHandler(), G4FermiPhaseSpaceDecay::G4FermiPhaseSpaceDecay(), G4GEMChannel::G4GEMChannel(), G4GEMProbability::G4GEMProbability(), G4Generator2BS::G4Generator2BS(), G4FissionProductYieldDist::G4GetFission(), G4HadronCrossSections::G4HadronCrossSections(), G4HadronNucleonXsc::G4HadronNucleonXsc(), G4ICRU49NuclearStoppingModel::G4ICRU49NuclearStoppingModel(), G4IonCoulombCrossSection::G4IonCoulombCrossSection(), G4ionEffectiveCharge::G4ionEffectiveCharge(), G4IonFluctuations::G4IonFluctuations(), G4IonisParamElm::G4IonisParamElm(), G4IonisParamMat::G4IonisParamMat(), G4KM_NucleonEqRhs::G4KM_NucleonEqRhs(), G4LevelManager::G4LevelManager(), G4LevelReader::G4LevelReader(), G4LindhardSorensenData::G4LindhardSorensenData(), G4NistManager::G4NistManager(), G4NuclearFermiDensity::G4NuclearFermiDensity(), G4NuclearLevelData::G4NuclearLevelData(), G4NuclearShellModelDensity::G4NuclearShellModelDensity(), G4PreCompoundEmission::G4PreCompoundEmission(), G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), G4QMDParameters::G4QMDParameters(), G4FPYSamplingOps::G4SampleWatt(), G4ScreeningMottCrossSection::G4ScreeningMottCrossSection(), G4fissionEvent::G4SmpGEng(), G4fissionEvent::G4SmpNEngCf252(), G4fissionEvent::G4SmpNuDistDataPu239(), G4fissionEvent::G4SmpNuDistDataPu239_241(), G4fissionEvent::G4SmpNuDistDataU232_234_236_238(), G4fissionEvent::G4SmpNuDistDataU233_235(), G4fissionEvent::G4SmpNuDistDataU235(), G4fissionEvent::G4SmpNuDistDataU238(), G4fissionEvent::G4SmpNugDist(), G4VEmissionProbability::G4VEmissionProbability(), G4VPreCompoundFragment::G4VPreCompoundFragment(), G4WentzelOKandVIxSection::G4WentzelOKandVIxSection(), G4ParticleHPMadlandNixSpectrum::Gamma25(), G4QMDParticipant::Get4Momentum(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonElCrSc(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4SigmaPlusField::GetBarrier(), G4SigmaMinusField::GetBarrier(), G4AntiProtonField::GetBarrier(), G4KaonMinusField::GetBarrier(), G4PionPlusField::GetBarrier(), G4KaonPlusField::GetBarrier(), G4PionMinusField::GetBarrier(), G4ProtonField::GetBarrier(), G4ParticleHPInterpolator::GetBinIntegral(), G4HadronCrossSections::GetCaptureCrossSection(), G4EMDissociationSpectrum::GetClosestApproach(), G4AntiNuclElastic::GetcosTeta1(), G4StatMFMicroPartition::GetCoulombEnergy(), G4NeutronInelasticCrossSection::GetCrossSection(), G4EMDissociationCrossSection::GetCrossSectionForProjectile(), G4TripathiCrossSection::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsSihverCrossSection::GetElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4StatMFFragment::GetEnergy(), G4ChipsHyperonElasticXS::GetExchangeT(), G4ChipsPionPlusElasticXS::GetExchangeT(), G4ChipsAntiBaryonElasticXS::GetExchangeT(), G4ChipsPionMinusElasticXS::GetExchangeT(), G4NuclearAbrasionGeometry::GetExcitationEnergyOfProjectile(), G4NuclearAbrasionGeometry::GetExcitationEnergyOfTarget(), G4EMDissociationSpectrum::GetGeneralE2Spectrum(), G4NuclNuclDiffuseElastic::GetHadronNucleonXscNS(), G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4LundStringFragmentation::GetLightConeZ(), G4QGSMFragmentation::GetLightConeZ(), G4InuclParamMomDst::GetMomentum(), G4QMDNucleus::GetNuclearMass(), G4StatMFMicroPartition::GetPartitionEnergy(), G4QMDMeanField::GetPotential(), G4ProtonInelasticCrossSection::GetProtonCrossSection(), G4ChipsHyperonElasticXS::GetPTables(), G4ChipsPionPlusElasticXS::GetPTables(), G4ChipsPionMinusElasticXS::GetPTables(), G4ChipsAntiBaryonElasticXS::GetPTables(), G4ChipsHyperonElasticXS::GetTabValues(), G4ChipsPionPlusElasticXS::GetTabValues(), G4ChipsPionMinusElasticXS::GetTabValues(), G4ChipsAntiBaryonElasticXS::GetTabValues(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), G4QMDMeanField::GetTotalPotential(), G4ParticleHPInterpolator::GetWeightedBinIntegral(), G4WilsonRadius::GetWilsonRMSRadius(), G4ParticleHPJENDLHEData::getXSfromThisIsotope(), G4ParticleHPMadlandNixSpectrum::GIntegral(), G4Bessel::I0(), G4Bessel::I1(), G4FTFParameters::InitForInteraction(), G4mplIonisationWithDeltaModel::Initialise(), G4mplIonisationModel::Initialise(), G4PhotonEvaporation::InitialiseGRData(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4ParticleHPVector::Integrate(), G4PiNuclearCrossSection::Interpolate(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4PolarizationTransition::LnFactorial(), G4ComponentBarNucleonNucleusXsc::LoadData(), G4ParticleHPMadlandNixSpectrum::Madland(), MCGIDI_energy_NBodyPhaseSpacePDF_callback(), MCGIDI_KalbachMann_S_a_or_b(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), G4LightMedia::NeutronExchange(), G4LightMedia::OmegaMinusExchange(), G4NuclearAbrasionGeometry::P(), G4QMDGroundStateNucleus::packNucleons(), G4LightMedia::PionPlusExchange(), G4StatMFChannel::PlaceFragments(), G4AntiNeutronAnnihilationAtRest::Poisso(), G4ParticleHPNBodyPhaseSpace::Prob(), G4LightMedia::ProtonExchange(), ptwXY_f_integrate(), ptwXY_LogLogToLinLin(), ptwXY_pow_callback(), G4LEHadronProtonElastic::RandCosThetaDipPen(), G4InuclSpecialFunctions::randomInuclPowers(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4DipBustGenerator::SampleCosTheta(), G4AntiNuclElastic::SampleInvariantT(), G4HadronElastic::SampleInvariantT(), G4ChargeExchange::SampleT(), G4QGSMSplitableHadron::SampleX(), G4QGSParticipants::SampleX(), G4QMDGroundStateNucleus::samplingMomentum(), G4ParticleHPKallbachMannSyst::SeparationEnergy(), G4FissionProductYieldDist::SetNubar(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4StatMFChannel::SolveEqOfMotion(), G4LundStringFragmentation::Splitup(), stirf(), G4ChipsProtonInelasticXS::ThresholdMomentum(), G4ChipsPionPlusInelasticXS::ThresholdMomentum(), G4Clebsch::TriangleCoeff(), G4Clebsch::Wigner6J(), G4Clebsch::WignerLittleD(), G4LightMedia::XiMinusExchange(), G4LightMedia::XiZeroExchange(), and G4BigBanger::xProbability().
G4double G4Pow::log10A (G4double A) const inline
Definition at line 212 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 212 of file G4Pow.hh
References logX(), and lz.
G4double G4Pow::log10Z (G4int Z) const inline
Definition at line 207 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 207 of file G4Pow.hh
References lz, and Z.
G4double G4Pow::logA (G4double A) const inline
Definition at line 176 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 176 of file G4Pow.hh
References logBase().
G4double G4Pow::logBase (G4double x) const inline private
Definition at line 153 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 153 of file G4Pow.hh
References G4Log(), lz, lz2, max2, maxA, maxA2, onethird, and x.
Referenced by logA(), and logX().
G4double G4Pow::logfactorial (G4int Z) const inline
Definition at line 251 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 251 of file G4Pow.hh
References logfact, and Z.
Referenced by G4Clebsch::ClebschGordanCoeff(), G4LegendrePolynomial::EvalAssocLegendrePoly(), G4PolarizationTransition::LnFactorial(), G4PreCompoundEmission::rho(), G4Clebsch::TriangleCoeff(), G4Clebsch::Wigner6J(), and G4Clebsch::WignerLittleD().
G4double G4Pow::logX (G4double x) const inline
Definition at line 181 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Pow.hh
References a, ener, G4Log(), logBase(), logen, maxA, and x.
Referenced by log10A(), and powA().
G4double G4Pow::logZ (G4int Z) const inline
Definition at line 148 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 148 of file G4Pow.hh
References lz, and Z.
Referenced by G4StatMFMicroPartition::CalcPartitionProbability(), G4MuonVDNuclearModel::CalculateEMVertex(), G4ScreeningMottCrossSection::FormFactor2ExpHof(), G4ScreeningMottCrossSection::FormFactor2Gauss(), G4GEMProbability::G4GEMProbability(), G4IonisParamElm::G4IonisParamElm(), G4IonisParamMat::G4IonisParamMat(), G4LevelReader::G4LevelReader(), G4NeutronInelasticCrossSection::GetCrossSection(), G4NistManager::GetLOGZ(), and G4LindhardSorensenData::InitialiseData().
G4double G4Pow::powA (G4double A, G4double y) const inline
Definition at line 241 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 241 of file G4Pow.hh
References expA(), and logX().
Referenced by G4FTFAnnihilation::Annihilate(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4LFission::Atomas(), G4AtimaEnergyLossModel::Bethek_dedx_e(), G4WilsonAblationModel::BreakItUp(), G4UPiNuclearCrossSection::BuildPhysicsTable(), G4ParticleHPNBodyPhaseSpace::C(), G4QuasiElRatios::CalcElTot(), G4IonsKoxCrossSection::calCeValue(), G4QuasiElRatios::CalcQF2IN_Ratio(), G4HadronCrossSections::CalcScatteringCrossSections(), G4DiffuseElasticV2::CalculateNuclearRad(), G4DiffuseElastic::CalculateNuclearRad(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4QMDMeanField::CalGraduate(), G4Reggeons::Chi_pomeron(), G4Reggeons::Chi_reggeon(), G4QGSDiffractiveExcitation::ChooseP(), G4DiffractiveExcitation::ChooseP(), G4SingleDiffractiveExcitation::ChooseX(), G4GoudsmitSaundersonMscModel::ComputeGeomPathLength(), G4GoudsmitSaundersonMscModel::ComputeTrueStepLength(), G4XAqmElastic::CrossSection(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4ChipsAntiBaryonInelasticXS::CrossSectionFormula(), G4AtimaEnergyLossModel::dedx_n(), G4NonEquilibriumEvaporator::deExcite(), G4AtimaFluctuations::Dispersion(), G4ProjectileFragmentCrossSection::doit(), G4ParticleHPFissionData::DumpPhysicsTable(), G4ParticleHPCaptureData::DumpPhysicsTable(), G4ParticleHPElasticData::DumpPhysicsTable(), G4ParticleHPInelasticData::DumpPhysicsTable(), G4LENDCrossSection::DumpPhysicsTable(), G4FPYSamplingOps::EvaluateWattConstants(), G4QuarkExchange::ExciteParticipants(), G4NuclearAbrasionGeometry::F(), G4IonFluctuations::Factor(), G4VCrossSectionSource::FcrossX(), G4QMDParameters::G4QMDParameters(), G4fissionEvent::G4SmpGEng(), G4fissionEvent::G4SmpNEngCf252(), G4fissionEvent::G4SmpNuDistDataU233_235(), G4fissionEvent::G4SmpNugDist(), G4ParticleHPMadlandNixSpectrum::Gamma25(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonElCrSc(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4ParticleHPInterpolator::GetBinIntegral(), G4HadronCrossSections::GetCaptureCrossSection(), G4EMDissociationSpectrum::GetClosestApproach(), G4EMDissociationCrossSection::GetCrossSectionForProjectile(), G4TripathiCrossSection::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4ChipsPionPlusElasticXS::GetExchangeT(), G4ChipsHyperonElasticXS::GetExchangeT(), G4ChipsPionMinusElasticXS::GetExchangeT(), G4ChipsAntiBaryonElasticXS::GetExchangeT(), G4EMDissociationSpectrum::GetGeneralE2Spectrum(), G4NuclNuclDiffuseElastic::GetHadronNucleonXscNS(), G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection(), G4LundStringFragmentation::GetLightConeZ(), G4QGSMFragmentation::GetLightConeZ(), G4QMDMeanField::GetPotential(), G4ProtonInelasticCrossSection::GetProtonCrossSection(), G4ChipsHyperonElasticXS::GetPTables(), G4ChipsPionPlusElasticXS::GetPTables(), G4ChipsPionMinusElasticXS::GetPTables(), G4ChipsAntiBaryonElasticXS::GetPTables(), G4ChipsHyperonElasticXS::GetTabValues(), G4ChipsPionPlusElasticXS::GetTabValues(), G4ChipsAntiBaryonElasticXS::GetTabValues(), G4ChipsPionMinusElasticXS::GetTabValues(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), G4QMDMeanField::GetTotalPotential(), G4ParticleHPInterpolator::GetWeightedBinIntegral(), G4ParticleHPMadlandNixSpectrum::GIntegral(), G4FTFParameters::InitForInteraction(), G4ParticleHPVector::Integrate(), G4PiNuclearCrossSection::Interpolate(), G4ParticleHPMadlandNixSpectrum::Madland(), MCGIDI_energy_NBodyPhaseSpacePDF_callback(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), G4QMDGroundStateNucleus::packNucleons(), G4ParticleHPNBodyPhaseSpace::Prob(), ptwXY_f_integrate(), ptwXY_LogLogToLinLin(), ptwXY_pow_callback(), G4LEHadronProtonElastic::RandCosThetaDipPen(), G4QGSMSplitableHadron::SampleX(), G4QGSParticipants::SampleX(), G4ParticleHPKallbachMannSyst::SeparationEnergy(), G4FissionProductYieldDist::SetNubar(), G4AtimaEnergyLossModel::sezi_dedx_e(), G4AtimaEnergyLossModel::sezi_p_se(), G4LundStringFragmentation::Splitup(), stirf(), G4ChipsProtonInelasticXS::ThresholdMomentum(), and G4ChipsPionPlusInelasticXS::ThresholdMomentum().
G4double G4Pow::powN (G4double x, G4int n) const
Definition at line 174 of file G4Pow.cc.
View newest version in sPHENIX GitHub at line 174 of file G4Pow.cc
References kdfinder::abs(), n, G4InuclParticleNames::nn, x, and y.
Referenced by G4ParticleHPKallbachMannSyst::A(), G4QMDReaction::ApplyYourself(), G4HadPhaseSpaceKopylov::BetaKopylov(), G4FermiPhaseSpaceDecay::BetaKopylov(), G4CascadeFinalStateAlgorithm::BetaKopylov(), G4ParticleHPNBodyPhaseSpace::C(), G4QMDMeanField::Cal2BodyQuantities(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4XAqmTotal::CrossSection(), G4NonEquilibriumEvaporator::deExcite(), G4DensityEffectCalculator::DEll(), G4DensityEffectCalculator::DeltaOnceSolved(), G4DensityEffectCalculator::DFRho(), G4ProjectileFragmentCrossSection::doit(), G4DensityEffectCalculator::Ell(), G4NuclearAbrasionGeometry::F(), G4DensityEffectCalculator::FermiDeltaCalculation(), G4JTPolynomialSolver::FindRoots(), G4ScreeningMottCrossSection::FormFactor2UniformHelm(), G4DensityEffectCalculator::FRho(), G4Pow(), G4fissionEvent::G4SmpNEngCf252(), G4fissionEvent::G4SmpNuDistDataPu239(), G4fissionEvent::G4SmpNuDistDataPu239_241(), G4fissionEvent::G4SmpNuDistDataU232_234_236_238(), G4fissionEvent::G4SmpNuDistDataU233_235(), G4fissionEvent::G4SmpNuDistDataU235(), G4fissionEvent::G4SmpNuDistDataU238(), G4InuclParamMomDst::GetMomentum(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4Bessel::I0(), G4Bessel::I1(), G4HETCFragment::IntegrateEmissionProbability(), G4AntiNeutronAnnihilationAtRest::Poisso(), G4PreCompoundNucleon::ProbabilityDistributionFunction(), G4PreCompoundIon::ProbabilityDistributionFunction(), G4NuclearRadii::RadiusECS(), G4InuclSpecialFunctions::randomInuclPowers(), G4QGSMSplitableHadron::SampleX(), G4FissionProductYieldDist::SetNubar(), and G4BigBanger::xProbability().
G4double G4Pow::powZ (G4int Z, G4double y) const inline
Definition at line 236 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 236 of file G4Pow.hh
References expA(), and lz.
Referenced by G4WilsonAblationModel::BreakItUp(), G4HadronCrossSections::CalcScatteringCrossSections(), G4KalbachCrossSection::ComputePowerParameter(), G4DensityEffectCalculator::DeltaOnceSolved(), G4DensityEffectCalculator::Ell(), G4ICRU49NuclearStoppingModel::InitialiseArray(), G4PhotonEvaporation::InitialiseGRData(), G4NuclearRadii::Radius(), G4NuclearRadii::RadiusRMS(), G4HadronElastic::SampleInvariantT(), G4ChargeExchange::SampleT(), and G4IonCoulombCrossSection::SetScreenRSquare().
G4double G4Pow::Z13 (G4int Z) const inline
Definition at line 131 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 131 of file G4Pow.hh
References pz13, and Z.
Referenced by G4NeutronEvaporationProbability::CalcAlphaParam(), G4GEMProbability::CalcAlphaParam(), G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4GEMCoulombBarrier::CalcCompoundRadius(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMicroPartition::CalcPartitionProbability(), G4GEMProbability::CalcProbability(), G4HadronCrossSections::CalcScatteringCrossSections(), G4StatMFMacroCanonical::CalculateTemperature(), G4GEMProbabilityVI::ComputeTotalProbability(), G4Fancy3DNucleus::CoulombBarrier(), G4CompetitiveFission::FissionKineticEnergy(), G4ScreeningMottCrossSection::FormFactor2UniformHelm(), G4StatMFMacroTemperature::FragsExcitEnergy(), G4InuclSpecialFunctions::G4cbrt(), G4GEMCoulombBarrier::G4GEMCoulombBarrier(), G4GEMProbabilityVI::G4GEMProbabilityVI(), G4IonisParamElm::G4IonisParamElm(), G4LevelManager::G4LevelManager(), G4NuclearFermiDensity::G4NuclearFermiDensity(), G4AntiProtonField::GetBarrier(), G4KaonMinusField::GetBarrier(), G4KaonPlusField::GetBarrier(), G4PionPlusField::GetBarrier(), G4PionMinusField::GetBarrier(), G4ProtonField::GetBarrier(), G4StatMFMicroPartition::GetCoulombEnergy(), G4NeutronInelasticCrossSection::GetCrossSection(), G4IonsSihverCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4HadronCrossSections::GetFissionCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4NuclearLevelData::GetLevelDensity(), G4StatMFMicroPartition::GetPartitionEnergy(), G4NistManager::GetZ13(), G4WentzelOKandVIxSection::InitialiseA(), G4VPreCompoundFragment::Initialize(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4ICRU49NuclearStoppingModel::NuclearStoppingPower(), G4StatMFChannel::PlaceFragments(), G4NuclearRadii::Radius(), G4NuclearRadii::RadiusCB(), G4NuclearRadii::RadiusECS(), G4NuclearRadii::RadiusHNGG(), G4NuclearRadii::RadiusKNGG(), G4NuclearRadii::RadiusND(), G4NuclearRadii::RadiusNNGG(), G4Generator2BS::SampleDirection(), G4AntiNuclElastic::SampleInvariantT(), G4HadronElastic::SampleInvariantT(), G4GEMChannel::SampleKineticEnergy(), G4IonCoulombCrossSection::SetScreenRSquare(), G4ScreeningMottCrossSection::SetupKinematic(), G4StatMFChannel::SolveEqOfMotion(), G4EvaporationProbability::TotalProbability(), and Z23().
G4double G4Pow::Z23 (G4int Z) const inline
Definition at line 136 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 136 of file G4Pow.hh
References x, and Z13().
Referenced by G4FissionBarrier::BarashenkovFissionBarrier(), G4NeutronEvaporationProbability::CalcBetaParam(), G4GEMProbability::CalcBetaParam(), G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), G4StatMFMacroTetraNucleon::CalcEnergy(), G4StatMFMacroTriNucleon::CalcEnergy(), G4StatMFMacroBiNucleon::CalcEnergy(), G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMFMacroMultiNucleon::CalcEntropy(), G4StatMFFragment::CalcExcitationEnergy(), G4StatMFMacroTetraNucleon::CalcMeanMultiplicity(), G4StatMFMacroTriNucleon::CalcMeanMultiplicity(), G4StatMFMacroBiNucleon::CalcMeanMultiplicity(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), G4StatMFMicroPartition::CalcPartitionProbability(), G4StatMFMacroMultiNucleon::CalcZARatio(), G4StatMFMacroCanonical::ChooseZ(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4AtimaFluctuations::Dispersion(), G4InuclSpecialFunctions::FermiEnergy(), G4NuclearShellModelDensity::G4NuclearShellModelDensity(), G4AntiNuclElastic::GetcosTeta1(), G4StatMFMicroPartition::GetCoulombEnergy(), G4LindhardSorensenData::GetDeltaL(), G4StatMFFragment::GetEnergy(), G4StatMFMicroPartition::GetPartitionEnergy(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4HETCFragment::IntegrateEmissionProbability(), G4HadronElastic::SampleInvariantT(), and G4WentzelOKandVIxSection::SetupTarget().
Member Data Documentation
G4DataVector G4Pow::ener private
Definition at line 118 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 118 of file G4Pow.hh
Referenced by G4Pow(), and logX().
G4DataVector G4Pow::fact private
Definition at line 125 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 125 of file G4Pow.hh
Referenced by factorial(), and G4Pow().
G4DataVector G4Pow::fexp private
Definition at line 124 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 124 of file G4Pow.hh
Referenced by expA(), and G4Pow().
G4Pow * G4Pow::fpInstance = 0 static private
Definition at line 108 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 108 of file G4Pow.hh
Referenced by GetInstance().
G4DataVector G4Pow::logen private
Definition at line 119 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 119 of file G4Pow.hh
Referenced by G4Pow(), and logX().
G4DataVector G4Pow::logfact private
Definition at line 126 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 126 of file G4Pow.hh
Referenced by G4Pow(), and logfactorial().
G4DataVector G4Pow::lowa13 private
Definition at line 121 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 121 of file G4Pow.hh
Referenced by A13Low(), and G4Pow().
G4DataVector G4Pow::lz private
Definition at line 122 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 122 of file G4Pow.hh
Referenced by G4Pow(), log10A(), log10Z(), logBase(), logZ(), and powZ().
G4DataVector G4Pow::lz2 private
Definition at line 123 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 123 of file G4Pow.hh
Referenced by G4Pow(), and logBase().
const G4int G4Pow::max2 private
Definition at line 111 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Pow.hh
Referenced by G4Pow(), and logBase().
G4double G4Pow::maxA private
Definition at line 113 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 113 of file G4Pow.hh
Referenced by A13High(), G4Pow(), logBase(), and logX().
G4double G4Pow::maxA2 private
Definition at line 115 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 115 of file G4Pow.hh
Referenced by G4Pow(), and logBase().
G4double G4Pow::maxAexp private
Definition at line 116 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 116 of file G4Pow.hh
Referenced by expA(), and G4Pow().
G4double G4Pow::maxLowA private
Definition at line 114 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 114 of file G4Pow.hh
Referenced by A13(), and G4Pow().
const G4double G4Pow::onethird private
Definition at line 110 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 110 of file G4Pow.hh
Referenced by A13High(), A13Low(), expA(), G4Pow(), and logBase().
G4DataVector G4Pow::pz13 private
Definition at line 120 of file G4Pow.hh.
View newest version in sPHENIX GitHub at line 120 of file G4Pow.hh
Referenced by A13High(), G4Pow(), and Z13().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4Pow.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4Pow.cc