ECCE @ EIC Software: G4VisCommandSceneAddEventID::EventID Struct Reference
G4VisCommandSceneAddEventID::EventID Struct Reference
Public Member Functions
EventID (ForWhat w, G4VisManager *vm, G4int size, G4double x, G4double y, G4Text::Layout layout)
void operator() (G4VGraphicsScene &, const G4Transform3D &, const G4ModelingParameters *)
Public Attributes
ForWhat fForWhat
G4VisManager * fpVisManager
G4int fSize
G4double fX
G4double fY
G4Text::Layout fLayout
Detailed Description
Definition at line 141 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 141 of file G4VisCommandsSceneAdd.hh
Constructor & Destructor Documentation
G4VisCommandSceneAddEventID::EventID::EventID (ForWhat w, G4VisManager * vm, G4int size, G4double x, G4double y, G4Text::Layout layout) inline
Definition at line 142 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 142 of file G4VisCommandsSceneAdd.hh
Member Function Documentation
void G4VisCommandSceneAddEventID::EventID::operator() (G4VGraphicsScene & sceneHandler, const G4Transform3D & , const G4ModelingParameters * mp)
Definition at line 718 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 718 of file G4VisCommandsSceneAdd.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives2D(), G4VGraphicsScene::EndPrimitives2D(), G4RunManager::GetCurrentRun(), G4Event::GetEventID(), G4Run::GetEventVector(), G4MTRunManager::GetMasterRunManager(), G4Run::GetNumberOfEventToBeProcessed(), G4Run::GetRunID(), G4RunManager::GetRunManager(), G4Threading::IsMultithreadedApplication(), nEvents, and G4VMarker::SetScreenSize().
Member Data Documentation
ForWhat G4VisCommandSceneAddEventID::EventID::fForWhat
Definition at line 147 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VisCommandsSceneAdd.hh
G4Text::Layout G4VisCommandSceneAddEventID::EventID::fLayout
Definition at line 151 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 151 of file G4VisCommandsSceneAdd.hh
G4VisManager* G4VisCommandSceneAddEventID::EventID::fpVisManager
Definition at line 148 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 148 of file G4VisCommandsSceneAdd.hh
G4int G4VisCommandSceneAddEventID::EventID::fSize
Definition at line 149 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VisCommandsSceneAdd.hh
G4double G4VisCommandSceneAddEventID::EventID::fX
Definition at line 150 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 150 of file G4VisCommandsSceneAdd.hh
G4double G4VisCommandSceneAddEventID::EventID::fY
Definition at line 150 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 150 of file G4VisCommandsSceneAdd.hh
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSceneAdd.cc