ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM.cc File Reference
xDataTOM.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include "xDataTOM_importXML_private.h"
#include "xDataTOM_private.h"
Macros
#define PATH_MAX 4096
Functions
static int xDataTOME_initializeElement (statusMessageReporting *smr, xDataTOM_element *element, xDataTOM_element *parent, int ordinal, int index, char const *name)
static void xDataTOME_displayTree (statusMessageReporting *smr, xDataTOM_element *element, int printAttributes, int level)
static int xDataTOM_initialize_xData (statusMessageReporting *smr, xDataTOM_xDataInfo *xDataInfo)
xDataTOM_TOM * xDataTOM_importFile (statusMessageReporting *smr, const char *fileName)
xDataTOM_TOM * xDataTOM_mallocTOM (statusMessageReporting *smr)
int xDataTOM_initializeTOM (statusMessageReporting *smr, xDataTOM_TOM *TOM)
void * xDataTOM_freeTOM (statusMessageReporting *, xDataTOM_TOM **TOM)
int xDataTOM_setFileNameTOM (statusMessageReporting *smr, xDataTOM_TOM *TOM, const char *fileName)
void xDataTOM_displayTree (statusMessageReporting *smr, xDataTOM_TOM *TOM, int printAttributes)
xDataTOM_element * xDataTOM_mallocElement (statusMessageReporting *smr, xDataTOM_element *parent, int ordinal, int index, char const *name)
void xDataTOM_freeElement (xDataTOM_element **element)
void xDataTOM_releaseElement (xDataTOM_element *element)
xDataTOM_element * xDataTOM_addElementInElement (statusMessageReporting *smr, xDataTOM_element *parent, int index, char const *name)
xDataTOM_element * xDataTOM_getDocumentsElement (xDataTOM_TOM *TOM)
xDataTOM_element * xDataTOME_getFirstElement (xDataTOM_element *element)
xDataTOM_element * xDataTOME_getNextElement (xDataTOM_element *element)
xDataTOM_element * xDataTOME_getOneElementByName (statusMessageReporting *smr, xDataTOM_element *element, char const *name, int required)
int xDataTOM_numberOfElementsByName (statusMessageReporting *, xDataTOM_element *element, char const *name)
int xDataTOME_addAttribute (statusMessageReporting *smr, xDataTOM_element *element, char const *name, char const *value)
char const * xDataTOM_getAttributesValueInElement (xDataTOM_element *element, char const *name)
int xDataTOME_copyAttributionList (statusMessageReporting *smr, xDataTOM_attributionList *desc, xDataTOM_element *element)
int xDataTOME_convertAttributeToInteger (statusMessageReporting *smr, xDataTOM_element *element, char const *name, int *n)
int xDataTOME_convertAttributeToDouble (statusMessageReporting *smr, xDataTOM_element *element, char const *name, double *d)
int xDataTOME_getInterpolation (statusMessageReporting *smr, xDataTOM_element *element, int index, enum xDataTOM_interpolationFlag *independent, enum xDataTOM_interpolationFlag *dependent, enum xDataTOM_interpolationQualifier *qualifier)
void xDataTOMAL_initial (statusMessageReporting *, xDataTOM_attributionList *attributes)
void xDataTOMAL_release (xDataTOM_attributionList *attributes)
int xDataTOMAL_addAttribute (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, char const *value)
char const * xDataTOMAL_getAttributesValue (xDataTOM_attributionList *attributes, char const *name)
int xDataTOMAL_copyAttributionList (statusMessageReporting *smr, xDataTOM_attributionList *desc, xDataTOM_attributionList *src)
int xDataTOMAL_convertAttributeToInteger (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, int *n)
int xDataTOMAL_convertAttributeToDouble (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, double *d)
void * xData_initializeData (statusMessageReporting *smr, xDataTOM_element *TE, char const *ID, size_t size)
int xDataTOM_isXDataID (xDataTOM_element *TE, char const *ID)
xDataTOM_xDataInfo * xDataTOME_getXData (xDataTOM_element *TE)
void * xDataTOME_getXDataIfID (statusMessageReporting *smr, xDataTOM_element *TE, char const *ID)
Variables
int xDataTOM_smrLibraryID = smr_unknownID
Macro Definition Documentation
#define PATH_MAX 4096
Definition at line 31 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 31 of file xDataTOM.cc
Referenced by xDataTOM_setFileNameTOM().
Function Documentation
void* xData_initializeData (statusMessageReporting * smr, xDataTOM_element * TE, char const * ID, size_t size)
Definition at line 479 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 479 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::element, xDataTOM_xDataInfo_s::ID, smr_malloc2, and xDataTOM_element_s::xDataInfo.
Referenced by xDataXML_initializeData().
xDataTOM_element* xDataTOM_addElementInElement (statusMessageReporting * smr, xDataTOM_element * parent, int index, char const * name)
Definition at line 188 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 188 of file xDataTOM.cc
References xDataTOM_element_s::children, xDataTOM_element_s::next, xDataTOM_element_s::numberOfChildren, and xDataTOM_mallocElement().
Referenced by xDataXML_constructTOM().
void xDataTOM_displayTree (statusMessageReporting * smr, xDataTOM_TOM * TOM, int printAttributes)
Definition at line 114 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 114 of file xDataTOM.cc
References xDataTOM_element_s::children, xDataTOM_TOM_s::root, and xDataTOME_displayTree().
void xDataTOM_freeElement (xDataTOM_element ** element)
Definition at line 139 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 139 of file xDataTOM.cc
References smr_freeMemory(), and xDataTOM_releaseElement().
Referenced by xDataTOM_releaseElement().
void* xDataTOM_freeTOM (statusMessageReporting * , xDataTOM_TOM ** TOM)
Definition at line 78 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 78 of file xDataTOM.cc
References xDataTOM_TOM_s::fileName, xDataTOM_TOM_s::realFileName, xDataTOM_TOM_s::root, smr_freeMemory(), and xDataTOM_releaseElement().
Referenced by MCGIDI_target_heated_read(), and xDataXML_importFile().
char const* xDataTOM_getAttributesValueInElement (xDataTOM_element * element, char const * name)
Definition at line 286 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 286 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_getAttributesValue().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_misc_getProductFrame(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_read(), and xDataTOM_getLinksElement2().
xDataTOM_element* xDataTOM_getDocumentsElement (xDataTOM_TOM * TOM)
Definition at line 223 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 223 of file xDataTOM.cc
References xDataTOM_element_s::children, and xDataTOM_TOM_s::root.
Referenced by MCGIDI_target_heated_read().
xDataTOM_TOM* xDataTOM_importFile (statusMessageReporting * smr, const char * fileName)
Definition at line 44 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM.cc
References xDataXML_importFile().
Referenced by MCGIDI_target_heated_read().
static int xDataTOM_initialize_xData (statusMessageReporting * smr, xDataTOM_xDataInfo * xDataInfo) static
Definition at line 472 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 472 of file xDataTOM.cc
Referenced by xDataTOME_initializeElement().
int xDataTOM_initializeTOM (statusMessageReporting * smr, xDataTOM_TOM * TOM)
Definition at line 68 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 68 of file xDataTOM.cc
References xDataTOM_TOM_s::fileName, xDataTOM_TOM_s::realFileName, xDataTOM_TOM_s::root, smr_isOk(), and xDataTOME_initializeElement().
Referenced by xDataTOM_mallocTOM().
int xDataTOM_isXDataID (xDataTOM_element * TE, char const * ID)
Definition at line 491 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 491 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::ID, and xDataTOM_element_s::xDataInfo.
xDataTOM_element* xDataTOM_mallocElement (statusMessageReporting * smr, xDataTOM_element * parent, int ordinal, int index, char const * name)
Definition at line 125 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 125 of file xDataTOM.cc
References smr_freeMemory(), smr_malloc2, and xDataTOME_initializeElement().
Referenced by xDataTOM_addElementInElement().
xDataTOM_TOM* xDataTOM_mallocTOM (statusMessageReporting * smr)
Definition at line 54 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 54 of file xDataTOM.cc
References smr_freeMemory(), smr_malloc2, and xDataTOM_initializeTOM().
Referenced by xDataXML_importFile().
int xDataTOM_numberOfElementsByName (statusMessageReporting * , xDataTOM_element * element, char const * name)
Definition at line 268 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 268 of file xDataTOM.cc
References n, xDataTOM_element_s::name, xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_target_heated_read().
void xDataTOM_releaseElement (xDataTOM_element * element)
Definition at line 148 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 148 of file xDataTOM.cc
References xDataTOM_element_s::attributes, xDataTOM_xDataInfo_s::axes, xDataTOM_element_s::children, xDataTOM_xDataInfo_s::ID, xDataTOM_element_s::name, xDataTOM_element_s::next, xDataTOM_element_s::parent, printf(), smr_freeMemory(), xDataTOM_element_s::xDataInfo, xDataTOM_axes_release(), xDataTOM_freeElement(), xDataTOM_KalbachMann_free(), xDataTOM_KalbachMann_ID, xDataTOM_polynomial_free(), xDataTOM_polynomial_ID, xDataTOM_regionsW_XYs_LegendreSeries_free(), xDataTOM_regionsW_XYs_LegendreSeries_ID, xDataTOM_regionsXYs_free(), xDataTOM_regionsXYs_ID, xDataTOM_V_W_XYs_free(), xDataTOM_V_W_XYs_ID, xDataTOM_V_W_XYs_LegendreSeries_free(), xDataTOM_V_W_XYs_LegendreSeries_ID, xDataTOM_W_XYs_freeFrom_xDataInfo(), xDataTOM_W_XYs_ID, xDataTOM_W_XYs_LegendreSeries_free(), xDataTOM_W_XYs_LegendreSeries_ID, xDataTOM_XYs_free(), xDataTOM_XYs_ID, and xDataTOMAL_release().
Referenced by xDataTOM_freeElement(), and xDataTOM_freeTOM().
int xDataTOM_setFileNameTOM (statusMessageReporting * smr, xDataTOM_TOM * TOM, const char * fileName)
Definition at line 94 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 94 of file xDataTOM.cc
References xDataTOM_TOM_s::fileName, PATH_MAX, xDataTOM_TOM_s::realFileName, smr_allocateCopyString2, and smr_freeMemory().
Referenced by xDataXML_importFile().
int xDataTOMAL_addAttribute (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, char const * value)
Definition at line 376 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 376 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, check_license::err(), xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, xDataTOM_attributionList_s::number, smr_allocateCopyString2, smr_freeMemory(), smr_malloc2, and xDataTOM_attribute_s::value.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), xDataTOMAL_copyAttributionList(), and xDataTOME_addAttribute().
int xDataTOMAL_convertAttributeToDouble (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, double * d)
Definition at line 450 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 450 of file xDataTOM.cc
References e, smr_setReportError2, xDataTOM_smrLibraryID, and xDataTOMAL_getAttributesValue().
Referenced by xDataTOME_convertAttributeToDouble().
int xDataTOMAL_convertAttributeToInteger (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, int * n)
Definition at line 433 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 433 of file xDataTOM.cc
References e, int(), smr_setReportError2, xDataTOM_smrLibraryID, and xDataTOMAL_getAttributesValue().
Referenced by xDataTOME_convertAttributeToInteger().
int xDataTOMAL_copyAttributionList (statusMessageReporting * smr, xDataTOM_attributionList * desc, xDataTOM_attributionList * src)
Definition at line 415 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 415 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, check_license::err(), xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, xDataTOM_attribute_s::value, xDataTOMAL_addAttribute(), xDataTOMAL_initial(), and xDataTOMAL_release().
Referenced by MCGIDI_target_heated_read(), and xDataTOME_copyAttributionList().
char const* xDataTOMAL_getAttributesValue (xDataTOM_attributionList * attributes, char const * name)
Definition at line 403 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 403 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, and xDataTOM_attribute_s::value.
Referenced by MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_target_getAttributesValue(), xDataTOM_getAttributesValueInElement(), xDataTOMAL_convertAttributeToDouble(), and xDataTOMAL_convertAttributeToInteger().
void xDataTOMAL_initial (statusMessageReporting * , xDataTOM_attributionList * attributes)
Definition at line 353 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 353 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, and xDataTOM_attributionList_s::number.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), MCGIDI_reaction_initialize2(), xDataTOMAL_copyAttributionList(), xDataTOMAL_release(), and xDataTOME_initializeElement().
void xDataTOMAL_release (xDataTOM_attributionList * attributes)
Definition at line 361 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 361 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, smr_freeMemory(), xDataTOM_attribute_s::value, and xDataTOMAL_initial().
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), MCGIDI_reaction_release(), MCGIDI_target_heated_release(), MCGIDI_target_release(), xDataTOM_releaseElement(), and xDataTOMAL_copyAttributionList().
int xDataTOME_addAttribute (statusMessageReporting * smr, xDataTOM_element * element, char const * name, char const * value)
Definition at line 279 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 279 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_addAttribute().
Referenced by xDataXML_constructTOM().
int xDataTOME_convertAttributeToDouble (statusMessageReporting * smr, xDataTOM_element * element, char const * name, double * d)
Definition at line 307 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 307 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_convertAttributeToDouble().
Referenced by MCGIDI_target_heated_parseParticleGammas().
int xDataTOME_convertAttributeToInteger (statusMessageReporting * smr, xDataTOM_element * element, char const * name, int * n)
Definition at line 300 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 300 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_convertAttributeToInteger().
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_product_parseFromTOM(), and MCGIDI_reaction_parseFromTOM().
int xDataTOME_copyAttributionList (statusMessageReporting * smr, xDataTOM_attributionList * desc, xDataTOM_element * element)
Definition at line 293 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 293 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_copyAttributionList().
Referenced by MCGIDI_reaction_parseFromTOM().
static void xDataTOME_displayTree (statusMessageReporting * smr, xDataTOM_element * element, int printAttributes, int level) static
Definition at line 326 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 326 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, xDataTOM_element_s::attributes, xDataTOM_element_s::index, xDataTOM_attribute_s::name, xDataTOM_element_s::name, xDataTOM_attribute_s::next, printf(), xDataTOM_attribute_s::value, xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by xDataTOM_displayTree().
xDataTOM_element* xDataTOME_getFirstElement (xDataTOM_element * element)
Definition at line 230 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 230 of file xDataTOM.cc
References xDataTOM_element_s::children.
Referenced by MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_read(), xDataTOM_numberOfElementsByName(), xDataTOME_displayTree(), and xDataTOME_getOneElementByName().
int xDataTOME_getInterpolation (statusMessageReporting * smr, xDataTOM_element * element, int index, enum xDataTOM_interpolationFlag * independent, enum xDataTOM_interpolationFlag * dependent, enum xDataTOM_interpolationQualifier * qualifier)
Definition at line 314 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 314 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::ID, xDataTOM_element_s::xDataInfo, and xDataTOM_axes_getInterpolation().
Referenced by MCGIDI_fromTOM_interpolation(), and MCGIDI_reaction_parseFromTOM().
xDataTOM_element* xDataTOME_getNextElement (xDataTOM_element * element)
Definition at line 238 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 238 of file xDataTOM.cc
References xDataTOM_element_s::next.
Referenced by MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_read(), xDataTOM_numberOfElementsByName(), xDataTOME_displayTree(), and xDataTOME_getOneElementByName().
xDataTOM_element* xDataTOME_getOneElementByName (statusMessageReporting * smr, xDataTOM_element * element, char const * name, int required)
Definition at line 246 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 246 of file xDataTOM.cc
References n, xDataTOM_element_s::name, smr_setReportError2, smr_unknownID, xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_read(), and MCGIDI_uncorrelated_parseFromTOM().
xDataTOM_xDataInfo* xDataTOME_getXData (xDataTOM_element * TE)
Definition at line 504 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 504 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::ID, and xDataTOM_element_s::xDataInfo.
Referenced by xDataTOME_getXDataIfID().
void* xDataTOME_getXDataIfID (statusMessageReporting * smr, xDataTOM_element * TE, char const * ID)
Definition at line 512 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 512 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, xDataTOM_element_s::name, smr_setReportError2, xDataTOM_smrLibraryID, and xDataTOME_getXData().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
static int xDataTOME_initializeElement (statusMessageReporting * smr, xDataTOM_element * element, xDataTOM_element * parent, int ordinal, int index, char const * name) static
Definition at line 207 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 207 of file xDataTOM.cc
References xDataTOM_element_s::attributes, xDataTOM_element_s::children, xDataTOM_element_s::index, xDataTOM_element_s::name, xDataTOM_element_s::next, xDataTOM_element_s::numberOfChildren, xDataTOM_element_s::ordinal, xDataTOM_element_s::parent, smr_allocateCopyString2, xDataTOM_element_s::xDataInfo, xDataTOM_initialize_xData(), and xDataTOMAL_initial().
Referenced by xDataTOM_initializeTOM(), and xDataTOM_mallocElement().
Variable Documentation
int xDataTOM_smrLibraryID = smr_unknownID
Definition at line 34 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 34 of file xDataTOM.cc
Referenced by xDataTOM_axes_getInterpolation(), xDataTOM_axes_getLabel(), xDataTOM_axes_getUnit(), xDataTOM_interpolation_getFromString(), xDataTOM_interpolation_set(), xDataTOM_interpolation_setFromString(), xDataTOM_setMessageError_ReturnInt(), xDataTOM_subAxes_initialize(), xDataTOMAL_convertAttributeToDouble(), xDataTOMAL_convertAttributeToInteger(), xDataTOME_getXDataIfID(), xDataTOMMisc_getAbsPath(), xDataXML_addElementToRoot(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_endXMLParsing(), xDataXML_getCommonData(), xDataXML_getOneElementByTagName(), xDataXML_importFile2(), xDataXML_initializeDoc(), xDataXML_is_xDataType(), xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_stringTo_double(), xDataXML_stringTo_xDataTOM_Int(), xDataXML_stringToDoubles(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().