ECCE @ EIC Software: G4AdjointSimManager Class Reference
G4AdjointSimManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4AdjointSimManager.hh>
Public Member Functions
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void EndOfRunAction (const G4Run *aRun)
void RunAdjointSimulation (G4int nb_evt)
G4int GetNbEvtOfLastRun ()
void SetAdjointTrackingMode (G4bool aBool)
G4bool GetAdjointTrackingMode ()
G4bool GetAdjointSimMode ()
G4bool GetDidAdjParticleReachTheExtSource ()
void RegisterAtEndOfAdjointTrack ()
void RegisterAdjointPrimaryWeight (G4double aWeight)
void ResetDidOneAdjPartReachExtSourceDuringEvent ()
G4int GetIDOfLastAdjParticleReachingExtSource ()
G4ThreeVector GetPositionAtEndOfLastAdjointTrack (size_t i=0)
G4ThreeVector GetDirectionAtEndOfLastAdjointTrack (size_t i=0)
G4double GetEkinAtEndOfLastAdjointTrack (size_t i=0)
G4double GetEkinNucAtEndOfLastAdjointTrack (size_t i=0)
G4double GetWeightAtEndOfLastAdjointTrack (size_t i=0)
G4double GetCosthAtEndOfLastAdjointTrack (size_t i=0)
const G4String & GetFwdParticleNameAtEndOfLastAdjointTrack ()
G4int GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack (size_t i=0)
G4int GetFwdParticleIndexAtEndOfLastAdjointTrack (size_t i=0)
size_t GetNbOfAdointTracksReachingTheExternalSurface ()
void ClearEndOfAdjointTrackInfoVectors ()
G4ParticleDefinition * GetLastGeneratedFwdPrimaryParticle ()
std::vector
< G4ParticleDefinition * > * GetListOfPrimaryFwdParticles ()
size_t GetNbOfPrimaryFwdParticles ()
G4bool DefineSphericalExtSource (G4double radius, G4ThreeVector pos)
G4bool DefineSphericalExtSourceWithCentreAtTheCentreOfAVolume (G4double radius, const G4String &volume_name)
G4bool DefineExtSourceOnTheExtSurfaceOfAVolume (const G4String &volume_name)
void SetExtSourceEmax (G4double Emax)
G4bool DefineSphericalAdjointSource (G4double radius, G4ThreeVector pos)
G4bool DefineSphericalAdjointSourceWithCentreAtTheCentreOfAVolume (G4double radius, const G4String &volume_name)
G4bool DefineAdjointSourceOnTheExtSurfaceOfAVolume (const G4String &volume_name)
void SetAdjointSourceEmin (G4double Emin)
void SetAdjointSourceEmax (G4double Emax)
G4double GetAdjointSourceArea ()
void ConsiderParticleAsPrimary (const G4String &particle_name)
void NeglectParticleAsPrimary (const G4String &particle_name)
void SetPrimaryIon (G4ParticleDefinition *adjointIon, G4ParticleDefinition *fwdIon)
const G4String & GetPrimaryIonName ()
void SetNormalisationMode (G4int n)
G4int GetNormalisationMode ()
G4double GetNumberNucleonsInIon ()
void SetAdjointEventAction (G4UserEventAction *anAction)
void SetAdjointSteppingAction (G4UserSteppingAction *anAction)
void SetAdjointStackingAction (G4UserStackingAction *anAction)
void SetAdjointRunAction (G4UserRunAction *anAction)
void UseUserStackingActionInFwdTrackingPhase (G4bool aBool)
void UseUserTrackingActionInFwdTrackingPhase (G4bool aBool)
void SetNbOfPrimaryFwdGammasPerEvent (G4int)
void SetNbAdjointPrimaryGammasPerEvent (G4int)
void SetNbAdjointPrimaryElectronsPerEvent (G4int)
void SwitchToAdjointSimulationMode ()
void BackToFwdSimulationMode ()
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Static Public Member Functions
static G4AdjointSimManager * GetInstance ()
Private Member Functions
void SetRestOfAdjointActions ()
void SetAdjointPrimaryRunAndStackingActions ()
void SetAdjointActions ()
void ResetRestOfUserActions ()
void ResetUserPrimaryRunAndStackingActions ()
void ResetUserActions ()
void DefineUserActions ()
G4AdjointSimManager ()
~G4AdjointSimManager ()
Private Attributes
G4AdjointSimMessenger * theMessenger
bool user_action_already_defined
G4UserRunAction * fUserRunAction
G4UserEventAction * fUserEventAction
G4VUserPrimaryGeneratorAction * fUserPrimaryGeneratorAction
G4UserTrackingAction * fUserTrackingAction
G4UserSteppingAction * fUserSteppingAction
G4UserStackingAction * fUserStackingAction
bool use_user_StackingAction
bool use_user_TrackingAction
G4UserRunAction * theAdjointRunAction
G4UserEventAction * theAdjointEventAction
G4AdjointPrimaryGeneratorAction * theAdjointPrimaryGeneratorAction
G4AdjointTrackingAction * theAdjointTrackingAction
G4AdjointSteppingAction * theAdjointSteppingAction
G4AdjointStackingAction * theAdjointStackingAction
G4bool adjoint_tracking_mode
G4bool adjoint_sim_mode
std::vector< G4ThreeVector > last_pos_vec
std::vector< G4ThreeVector > last_direction_vec
std::vector< G4double > last_ekin_vec
std::vector< G4double > last_ekin_nuc_vec
std::vector< G4double > last_cos_th_vec
std::vector< G4double > last_weight_vec
std::vector< G4int > last_fwd_part_PDGEncoding_vec
std::vector< G4int > last_fwd_part_index_vec
std::vector< G4int > ID_of_last_particle_that_reach_the_ext_source_vec
G4ThreeVector last_pos
G4ThreeVector last_direction
G4double last_ekin
G4double last_ekin_nuc
G4double last_cos_th
G4String last_fwd_part_name
G4int last_fwd_part_PDGEncoding
G4int last_fwd_part_index
G4double last_weight
G4int ID_of_last_particle_that_reach_the_ext_source
G4int nb_evt_of_last_run
G4int normalisation_mode
G4double area_of_the_adjoint_source
G4double nb_nuc
G4double theAdjointPrimaryWeight
G4bool welcome_message
Static Private Attributes
static G4ThreadLocal
G4AdjointSimManager * instance = 0
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 149 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4AdjointSimManager.hh
Constructor & Destructor Documentation
G4AdjointSimManager::G4AdjointSimManager () private
Definition at line 69 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 69 of file G4AdjointSimManager.cc
References adjoint_sim_mode, G4AdjointPrimaryGeneratorAction::GetListOfPrimaryFwdParticles(), nb_nuc, normalisation_mode, G4AdjointTrackingAction::SetListOfPrimaryFwdParticles(), theAdjointPrimaryGeneratorAction, theAdjointStackingAction, theAdjointSteppingAction, theAdjointTrackingAction, theMessenger, use_user_StackingAction, use_user_TrackingAction, user_action_already_defined, and welcome_message.
Referenced by GetInstance().
G4AdjointSimManager::~G4AdjointSimManager () private
Definition at line 121 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 121 of file G4AdjointSimManager.cc
References theAdjointEventAction, theAdjointPrimaryGeneratorAction, theAdjointRunAction, theAdjointStackingAction, theAdjointSteppingAction, theAdjointTrackingAction, and theMessenger.
Member Function Documentation
void G4AdjointSimManager::BackToFwdSimulationMode ()
Definition at line 220 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 220 of file G4AdjointSimManager.cc
References adjoint_sim_mode, and ResetUserActions().
Referenced by RunAdjointSimulation().
void G4AdjointSimManager::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 662 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 662 of file G4AdjointSimManager.cc
References G4UserRunAction::BeginOfRunAction(), and fUserRunAction.
void G4AdjointSimManager::ClearEndOfAdjointTrackInfoVectors ()
Definition at line 423 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 423 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::ClearEndOfAdjointTrackInfoVectors(), and theAdjointTrackingAction.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
void G4AdjointSimManager::ConsiderParticleAsPrimary (const G4String & particle_name)
Definition at line 580 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 580 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::ConsiderParticleAsPrimary(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointPhysicsList::ConstructEM(), and G4AdjointSimMessenger::SetNewValue().
G4bool G4AdjointSimManager::DefineAdjointSourceOnTheExtSurfaceOfAVolume (const G4String & volume_name)
Definition at line 556 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 556 of file G4AdjointSimManager.cc
References G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), area_of_the_adjoint_source, G4AdjointCrossSurfChecker::GetInstance(), G4AdjointPrimaryGeneratorAction::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
G4bool G4AdjointSimManager::DefineExtSourceOnTheExtSurfaceOfAVolume (const G4String & volume_name)
Definition at line 522 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 522 of file G4AdjointSimManager.cc
References G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), and G4AdjointCrossSurfChecker::GetInstance().
Referenced by G4AdjointSimMessenger::SetNewValue().
G4bool G4AdjointSimManager::DefineSphericalAdjointSource (G4double radius, G4ThreeVector pos)
Definition at line 535 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 535 of file G4AdjointSimManager.cc
References G4AdjointCrossSurfChecker::AddaSphericalSurface(), area_of_the_adjoint_source, G4AdjointCrossSurfChecker::GetInstance(), G4AdjointPrimaryGeneratorAction::SetSphericalAdjointPrimarySource(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
G4bool G4AdjointSimManager::DefineSphericalAdjointSourceWithCentreAtTheCentreOfAVolume (G4double radius, const G4String & volume_name)
Definition at line 545 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 545 of file G4AdjointSimManager.cc
References G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), area_of_the_adjoint_source, G4AdjointCrossSurfChecker::GetInstance(), G4AdjointPrimaryGeneratorAction::SetSphericalAdjointPrimarySource(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
G4bool G4AdjointSimManager::DefineSphericalExtSource (G4double radius, G4ThreeVector pos)
Definition at line 507 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 507 of file G4AdjointSimManager.cc
References G4AdjointCrossSurfChecker::AddaSphericalSurface(), and G4AdjointCrossSurfChecker::GetInstance().
Referenced by G4AdjointSimMessenger::SetNewValue().
G4bool G4AdjointSimManager::DefineSphericalExtSourceWithCentreAtTheCentreOfAVolume (G4double radius, const G4String & volume_name)
Definition at line 514 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 514 of file G4AdjointSimManager.cc
References G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), and G4AdjointCrossSurfChecker::GetInstance().
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::DefineUserActions () private
Definition at line 308 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 308 of file G4AdjointSimManager.cc
References fUserEventAction, fUserPrimaryGeneratorAction, fUserRunAction, fUserStackingAction, fUserSteppingAction, fUserTrackingAction, G4RunManager::GetRunManager(), G4RunManager::GetUserEventAction(), G4RunManager::GetUserPrimaryGeneratorAction(), G4RunManager::GetUserRunAction(), G4RunManager::GetUserStackingAction(), G4RunManager::GetUserSteppingAction(), G4RunManager::GetUserTrackingAction(), G4AdjointSteppingAction::SetUserForwardSteppingAction(), theAdjointSteppingAction, and user_action_already_defined.
Referenced by SetAdjointActions(), SetAdjointPrimaryRunAndStackingActions(), and SetRestOfAdjointActions().
void G4AdjointSimManager::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 676 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 676 of file G4AdjointSimManager.cc
References adjoint_sim_mode, G4UserRunAction::EndOfRunAction(), fUserRunAction, and theAdjointRunAction.
G4bool G4AdjointSimManager::GetAdjointSimMode () inline
Definition at line 165 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 165 of file G4AdjointSimManager.hh
References adjoint_sim_mode.
Referenced by RMC01AnalysisManager::BeginOfRun().
G4double G4AdjointSimManager::GetAdjointSourceArea () inline
Definition at line 205 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 205 of file G4AdjointSimManager.hh
References area_of_the_adjoint_source.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
G4bool G4AdjointSimManager::GetAdjointTrackingMode ()
Definition at line 322 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetIsAdjointTrackingMode(), and theAdjointTrackingAction.
G4double G4AdjointSimManager::GetCosthAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 396 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 396 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetCosthAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
G4bool G4AdjointSimManager::GetDidAdjParticleReachTheExtSource ()
Definition at line 350 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 350 of file G4AdjointSimManager.cc
References GetNbOfAdointTracksReachingTheExternalSurface().
Referenced by SetAdjointTrackingMode().
G4ThreeVector G4AdjointSimManager::GetDirectionAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 376 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 376 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetDirectionAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
G4double G4AdjointSimManager::GetEkinAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 381 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 381 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetEkinAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
Referenced by RMC01AnalysisManager::EndOfEventForAdjointSimulation().
G4double G4AdjointSimManager::GetEkinNucAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 386 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 386 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetEkinNucAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
G4int G4AdjointSimManager::GetFwdParticleIndexAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 412 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 412 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetLastFwdParticleIndex(), and theAdjointTrackingAction.
const G4String & G4AdjointSimManager::GetFwdParticleNameAtEndOfLastAdjointTrack ()
Definition at line 401 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 401 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetFwdParticleNameAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
G4int G4AdjointSimManager::GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 406 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 406 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
Referenced by RMC01AnalysisManager::EndOfEventForAdjointSimulation().
G4int G4AdjointSimManager::GetIDOfLastAdjParticleReachingExtSource () inline
Definition at line 172 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 172 of file G4AdjointSimManager.hh
References ID_of_last_particle_that_reach_the_ext_source.
G4AdjointSimManager * G4AdjointSimManager::GetInstance (void) static
Definition at line 133 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 133 of file G4AdjointSimManager.cc
References G4AdjointSimManager(), and instance.
Referenced by RMC01AnalysisManager::BeginOfRun(), G4AdjointPrimaryGeneratorAction::ComputeEnergyDistWeight(), RMC01AnalysisManager::ComputeMeanEdepAndError(), G4AdjointPhysicsList::ConstructEM(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), RMC01AnalysisManager::EndOfRun(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), and main().
G4ParticleDefinition * G4AdjointSimManager::GetLastGeneratedFwdPrimaryParticle ()
Definition at line 692 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 692 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::GetLastGeneratedFwdPrimaryParticle(), and theAdjointPrimaryGeneratorAction.
std::vector< G4ParticleDefinition * > * G4AdjointSimManager::GetListOfPrimaryFwdParticles ()
Definition at line 357 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 357 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::GetListOfPrimaryFwdParticles(), and theAdjointPrimaryGeneratorAction.
G4int G4AdjointSimManager::GetNbEvtOfLastRun () inline
Definition at line 161 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 161 of file G4AdjointSimManager.hh
References nb_evt_of_last_run.
Referenced by RMC01AnalysisManager::BeginOfRun(), G4AdjointPrimaryGeneratorAction::ComputeEnergyDistWeight(), RMC01AnalysisManager::ComputeMeanEdepAndError(), and RMC01AnalysisManager::EndOfRun().
size_t G4AdjointSimManager::GetNbOfAdointTracksReachingTheExternalSurface ()
Definition at line 417 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 417 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetNbOfAdointTracksReachingTheExternalSurface(), and theAdjointTrackingAction.
Referenced by RMC01AnalysisManager::EndOfEventForAdjointSimulation(), and GetDidAdjParticleReachTheExtSource().
size_t G4AdjointSimManager::GetNbOfPrimaryFwdParticles ()
Definition at line 363 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 363 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::GetListOfPrimaryFwdParticles(), and theAdjointPrimaryGeneratorAction.
G4int G4AdjointSimManager::GetNormalisationMode () inline
Definition at line 212 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 212 of file G4AdjointSimManager.hh
References normalisation_mode.
G4double G4AdjointSimManager::GetNumberNucleonsInIon () inline
Definition at line 213 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 213 of file G4AdjointSimManager.hh
References nb_nuc.
G4ThreeVector G4AdjointSimManager::GetPositionAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 370 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 370 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetPositionAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
const G4String & G4AdjointSimManager::GetPrimaryIonName ()
Definition at line 605 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 605 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::GetPrimaryIonName(), and theAdjointPrimaryGeneratorAction.
G4double G4AdjointSimManager::GetWeightAtEndOfLastAdjointTrack (size_t i = 0)
Definition at line 391 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 391 of file G4AdjointSimManager.cc
References G4AdjointTrackingAction::GetWeightAtEndOfLastAdjointTrack(), and theAdjointTrackingAction.
Referenced by RMC01AnalysisManager::EndOfEventForAdjointSimulation().
void G4AdjointSimManager::NeglectParticleAsPrimary (const G4String & particle_name)
Definition at line 586 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 586 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::NeglectParticleAsPrimary(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::RegisterAdjointPrimaryWeight (G4double aWeight)
Definition at line 611 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 611 of file G4AdjointSimManager.cc
References G4AdjointSteppingAction::SetPrimWeight(), theAdjointPrimaryWeight, and theAdjointSteppingAction.
void G4AdjointSimManager::RegisterAtEndOfAdjointTrack ()
Definition at line 429 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 429 of file G4AdjointSimManager.cc
References G4ParticleTable::FindParticle(), G4ParticleDefinition::GetBaryonNumber(), G4AdjointSteppingAction::GetLastEkin(), G4AdjointSteppingAction::GetLastMomentum(), G4AdjointSteppingAction::GetLastPartDef(), G4AdjointSteppingAction::GetLastPosition(), G4AdjointSteppingAction::GetLastWeight(), G4AdjointPrimaryGeneratorAction::GetListOfPrimaryFwdParticles(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGEncoding(), ID_of_last_particle_that_reach_the_ext_source, ID_of_last_particle_that_reach_the_ext_source_vec, last_cos_th, last_cos_th_vec, last_direction, last_direction_vec, last_ekin, last_ekin_nuc, last_ekin_nuc_vec, last_ekin_vec, last_fwd_part_index, last_fwd_part_index_vec, last_fwd_part_name, last_fwd_part_PDGEncoding, last_fwd_part_PDGEncoding_vec, last_pos, last_pos_vec, last_weight, last_weight_vec, CLHEP::Hep3Vector::mag(), nb_nuc, G4String::remove(), theAdjointPrimaryGeneratorAction, theAdjointSteppingAction, and CLHEP::Hep3Vector::z().
Referenced by SetAdjointTrackingMode().
void G4AdjointSimManager::ResetDidOneAdjPartReachExtSourceDuringEvent ()
Definition at line 697 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 697 of file G4AdjointSimManager.cc
References G4AdjointSteppingAction::ResetDidOneAdjPartReachExtSourceDuringEvent(), and theAdjointSteppingAction.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
void G4AdjointSimManager::ResetRestOfUserActions () private
Definition at line 283 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 283 of file G4AdjointSimManager.cc
References fUserEventAction, fUserSteppingAction, fUserTrackingAction, and G4RunManager::GetRunManager().
Referenced by SetAdjointTrackingMode().
void G4AdjointSimManager::ResetUserActions () private
Definition at line 268 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 268 of file G4AdjointSimManager.cc
References fUserEventAction, fUserPrimaryGeneratorAction, fUserRunAction, fUserStackingAction, fUserSteppingAction, fUserTrackingAction, and G4RunManager::GetRunManager().
Referenced by BackToFwdSimulationMode().
void G4AdjointSimManager::ResetUserPrimaryRunAndStackingActions () private
Definition at line 297 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 297 of file G4AdjointSimManager.cc
References fUserPrimaryGeneratorAction, fUserRunAction, fUserStackingAction, and G4RunManager::GetRunManager().
void G4AdjointSimManager::RunAdjointSimulation (G4int nb_evt)
Definition at line 140 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 140 of file G4AdjointSimManager.cc
References BackToFwdSimulationMode(), G4RunManager::BeamOn(), G4cout, G4AdjointPrimaryGeneratorAction::GetNbOfAdjointPrimaryTypes(), G4RunManager::GetRunManager(), nb_evt_of_last_run, G4RunManager::sequentialRM, SwitchToAdjointSimulationMode(), theAdjointPrimaryGeneratorAction, and welcome_message.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetAdjointActions () private
Definition at line 229 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 229 of file G4AdjointSimManager.cc
References DefineUserActions(), fUserStackingAction, fUserTrackingAction, G4RunManager::GetRunManager(), G4AdjointTrackingAction::SetUserForwardTrackingAction(), G4AdjointStackingAction::SetUserFwdStackingAction(), theAdjointEventAction, theAdjointPrimaryGeneratorAction, theAdjointStackingAction, theAdjointSteppingAction, theAdjointTrackingAction, use_user_StackingAction, use_user_TrackingAction, and user_action_already_defined.
Referenced by SwitchToAdjointSimulationMode().
void G4AdjointSimManager::SetAdjointEventAction (G4UserEventAction * anAction)
Definition at line 619 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 619 of file G4AdjointSimManager.cc
References theAdjointEventAction.
Referenced by main().
void G4AdjointSimManager::SetAdjointPrimaryRunAndStackingActions () private
Definition at line 251 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 251 of file G4AdjointSimManager.cc
References DefineUserActions(), fUserStackingAction, G4RunManager::GetRunManager(), G4AdjointStackingAction::SetUserFwdStackingAction(), theAdjointPrimaryGeneratorAction, theAdjointRunAction, theAdjointStackingAction, use_user_StackingAction, and user_action_already_defined.
void G4AdjointSimManager::SetAdjointRunAction (G4UserRunAction * anAction)
Definition at line 638 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 638 of file G4AdjointSimManager.cc
References theAdjointRunAction.
Referenced by main().
void G4AdjointSimManager::SetAdjointSourceEmax (G4double Emax)
Definition at line 574 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 574 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::SetEmax(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetAdjointSourceEmin (G4double Emin)
Definition at line 568 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 568 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::SetEmin(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetAdjointStackingAction (G4UserStackingAction * anAction)
Definition at line 631 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 631 of file G4AdjointSimManager.cc
References G4AdjointStackingAction::SetUserAdjointStackingAction(), and theAdjointStackingAction.
void G4AdjointSimManager::SetAdjointSteppingAction (G4UserSteppingAction * anAction)
Definition at line 625 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 625 of file G4AdjointSimManager.cc
References G4AdjointSteppingAction::SetUserAdjointSteppingAction(), and theAdjointSteppingAction.
void G4AdjointSimManager::SetAdjointTrackingMode (G4bool aBool)
Definition at line 327 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 327 of file G4AdjointSimManager.cc
References adjoint_tracking_mode, GetDidAdjParticleReachTheExtSource(), RegisterAtEndOfAdjointTrack(), ResetRestOfUserActions(), G4AdjointStackingAction::SetAdjointMode(), G4AdjointStackingAction::SetKillTracks(), SetRestOfAdjointActions(), and theAdjointStackingAction.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
void G4AdjointSimManager::SetExtSourceEmax (G4double Emax)
Definition at line 529 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 529 of file G4AdjointSimManager.cc
References G4AdjointSteppingAction::SetExtSourceEMax(), and theAdjointSteppingAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetNbAdjointPrimaryElectronsPerEvent (G4int nb)
Definition at line 656 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 656 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::SetNbAdjointPrimaryElectronsPerEvent(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetNbAdjointPrimaryGammasPerEvent (G4int nb)
Definition at line 650 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 650 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::SetNbAdjointPrimaryGammasPerEvent(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetNbOfPrimaryFwdGammasPerEvent (G4int nb)
Definition at line 644 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 644 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::SetNbPrimaryFwdGammasPerEvent(), and theAdjointPrimaryGeneratorAction.
Referenced by G4AdjointSimMessenger::SetNewValue().
void G4AdjointSimManager::SetNormalisationMode (G4int n) inline
Definition at line 211 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 211 of file G4AdjointSimManager.hh
References n, and normalisation_mode.
void G4AdjointSimManager::SetPrimaryIon (G4ParticleDefinition * adjointIon, G4ParticleDefinition * fwdIon)
Definition at line 599 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 599 of file G4AdjointSimManager.cc
References G4AdjointPrimaryGeneratorAction::SetPrimaryIon(), and theAdjointPrimaryGeneratorAction.
void G4AdjointSimManager::SetRestOfAdjointActions () private
Definition at line 191 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 191 of file G4AdjointSimManager.cc
References DefineUserActions(), G4RunManager::GetRunManager(), theAdjointEventAction, theAdjointSteppingAction, theAdjointTrackingAction, and user_action_already_defined.
Referenced by SetAdjointTrackingMode().
void G4AdjointSimManager::SwitchToAdjointSimulationMode ()
Definition at line 207 of file G4AdjointSimManager.cc.
View newest version in sPHENIX GitHub at line 207 of file G4AdjointSimManager.cc
References adjoint_sim_mode, ID_of_last_particle_that_reach_the_ext_source, SetAdjointActions(), theAdjointPrimaryGeneratorAction, and G4AdjointPrimaryGeneratorAction::UpdateListOfPrimaryParticles().
Referenced by RunAdjointSimulation().
void G4AdjointSimManager::UseUserStackingActionInFwdTrackingPhase (G4bool aBool) inline
Definition at line 224 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 224 of file G4AdjointSimManager.hh
References use_user_StackingAction.
void G4AdjointSimManager::UseUserTrackingActionInFwdTrackingPhase (G4bool aBool) inline
Definition at line 225 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 225 of file G4AdjointSimManager.hh
References use_user_TrackingAction.
Member Data Documentation
G4bool G4AdjointSimManager::adjoint_sim_mode private
Definition at line 301 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 301 of file G4AdjointSimManager.hh
Referenced by BackToFwdSimulationMode(), EndOfRunAction(), G4AdjointSimManager(), GetAdjointSimMode(), and SwitchToAdjointSimulationMode().
G4bool G4AdjointSimManager::adjoint_tracking_mode private
Definition at line 300 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 300 of file G4AdjointSimManager.hh
Referenced by SetAdjointTrackingMode().
G4double G4AdjointSimManager::area_of_the_adjoint_source private
Definition at line 333 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 333 of file G4AdjointSimManager.hh
Referenced by DefineAdjointSourceOnTheExtSurfaceOfAVolume(), DefineSphericalAdjointSource(), DefineSphericalAdjointSourceWithCentreAtTheCentreOfAVolume(), and GetAdjointSourceArea().
G4UserEventAction* G4AdjointSimManager::fUserEventAction private
Definition at line 281 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 281 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), ResetRestOfUserActions(), and ResetUserActions().
G4VUserPrimaryGeneratorAction* G4AdjointSimManager::fUserPrimaryGeneratorAction private
Definition at line 282 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 282 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), ResetUserActions(), and ResetUserPrimaryRunAndStackingActions().
G4UserRunAction* G4AdjointSimManager::fUserRunAction private
Definition at line 280 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 280 of file G4AdjointSimManager.hh
Referenced by BeginOfRunAction(), DefineUserActions(), EndOfRunAction(), ResetUserActions(), and ResetUserPrimaryRunAndStackingActions().
G4UserStackingAction* G4AdjointSimManager::fUserStackingAction private
Definition at line 285 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 285 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), ResetUserActions(), ResetUserPrimaryRunAndStackingActions(), SetAdjointActions(), and SetAdjointPrimaryRunAndStackingActions().
G4UserSteppingAction* G4AdjointSimManager::fUserSteppingAction private
Definition at line 284 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 284 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), ResetRestOfUserActions(), and ResetUserActions().
G4UserTrackingAction* G4AdjointSimManager::fUserTrackingAction private
Definition at line 283 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 283 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), ResetRestOfUserActions(), ResetUserActions(), and SetAdjointActions().
G4int G4AdjointSimManager::ID_of_last_particle_that_reach_the_ext_source private
Definition at line 326 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 326 of file G4AdjointSimManager.hh
Referenced by GetIDOfLastAdjParticleReachingExtSource(), RegisterAtEndOfAdjointTrack(), and SwitchToAdjointSimulationMode().
std::vector<G4int> G4AdjointSimManager::ID_of_last_particle_that_reach_the_ext_source_vec private
Definition at line 313 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 313 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4ThreadLocal G4AdjointSimManager * G4AdjointSimManager::instance = 0 static private
Definition at line 249 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 249 of file G4AdjointSimManager.hh
Referenced by GetInstance().
G4double G4AdjointSimManager::last_cos_th private
Definition at line 321 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 321 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4double> G4AdjointSimManager::last_cos_th_vec private
Definition at line 309 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 309 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4ThreeVector G4AdjointSimManager::last_direction private
Definition at line 319 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 319 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4ThreeVector> G4AdjointSimManager::last_direction_vec private
Definition at line 306 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 306 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4double G4AdjointSimManager::last_ekin private
Definition at line 320 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 320 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4double G4AdjointSimManager::last_ekin_nuc private
Definition at line 320 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 320 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4double> G4AdjointSimManager::last_ekin_nuc_vec private
Definition at line 308 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 308 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4double> G4AdjointSimManager::last_ekin_vec private
Definition at line 307 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 307 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4int G4AdjointSimManager::last_fwd_part_index private
Definition at line 324 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 324 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4int> G4AdjointSimManager::last_fwd_part_index_vec private
Definition at line 312 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 312 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4String G4AdjointSimManager::last_fwd_part_name private
Definition at line 322 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 322 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4int G4AdjointSimManager::last_fwd_part_PDGEncoding private
Definition at line 323 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 323 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4int> G4AdjointSimManager::last_fwd_part_PDGEncoding_vec private
Definition at line 311 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 311 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4ThreeVector G4AdjointSimManager::last_pos private
Definition at line 318 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 318 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4ThreeVector> G4AdjointSimManager::last_pos_vec private
Definition at line 305 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 305 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4double G4AdjointSimManager::last_weight private
Definition at line 325 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 325 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
std::vector<G4double> G4AdjointSimManager::last_weight_vec private
Definition at line 310 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 310 of file G4AdjointSimManager.hh
Referenced by RegisterAtEndOfAdjointTrack().
G4int G4AdjointSimManager::nb_evt_of_last_run private
Definition at line 328 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 328 of file G4AdjointSimManager.hh
Referenced by GetNbEvtOfLastRun(), and RunAdjointSimulation().
G4double G4AdjointSimManager::nb_nuc private
Definition at line 334 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 334 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), GetNumberNucleonsInIon(), and RegisterAtEndOfAdjointTrack().
G4int G4AdjointSimManager::normalisation_mode private
Definition at line 329 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 329 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), GetNormalisationMode(), and SetNormalisationMode().
G4UserEventAction* G4AdjointSimManager::theAdjointEventAction private
Definition at line 292 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 292 of file G4AdjointSimManager.hh
Referenced by SetAdjointActions(), SetAdjointEventAction(), SetRestOfAdjointActions(), and ~G4AdjointSimManager().
G4AdjointPrimaryGeneratorAction* G4AdjointSimManager::theAdjointPrimaryGeneratorAction private
Definition at line 293 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 293 of file G4AdjointSimManager.hh
Referenced by ConsiderParticleAsPrimary(), DefineAdjointSourceOnTheExtSurfaceOfAVolume(), DefineSphericalAdjointSource(), DefineSphericalAdjointSourceWithCentreAtTheCentreOfAVolume(), G4AdjointSimManager(), GetLastGeneratedFwdPrimaryParticle(), GetListOfPrimaryFwdParticles(), GetNbOfPrimaryFwdParticles(), GetPrimaryIonName(), NeglectParticleAsPrimary(), RegisterAtEndOfAdjointTrack(), RunAdjointSimulation(), SetAdjointActions(), SetAdjointPrimaryRunAndStackingActions(), SetAdjointSourceEmax(), SetAdjointSourceEmin(), SetNbAdjointPrimaryElectronsPerEvent(), SetNbAdjointPrimaryGammasPerEvent(), SetNbOfPrimaryFwdGammasPerEvent(), SetPrimaryIon(), SwitchToAdjointSimulationMode(), and ~G4AdjointSimManager().
G4double G4AdjointSimManager::theAdjointPrimaryWeight private
Definition at line 335 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 335 of file G4AdjointSimManager.hh
Referenced by RegisterAdjointPrimaryWeight().
G4UserRunAction* G4AdjointSimManager::theAdjointRunAction private
Definition at line 291 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 291 of file G4AdjointSimManager.hh
Referenced by EndOfRunAction(), SetAdjointPrimaryRunAndStackingActions(), SetAdjointRunAction(), and ~G4AdjointSimManager().
G4AdjointStackingAction* G4AdjointSimManager::theAdjointStackingAction private
Definition at line 296 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 296 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), SetAdjointActions(), SetAdjointPrimaryRunAndStackingActions(), SetAdjointStackingAction(), SetAdjointTrackingMode(), and ~G4AdjointSimManager().
G4AdjointSteppingAction* G4AdjointSimManager::theAdjointSteppingAction private
Definition at line 295 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 295 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), G4AdjointSimManager(), RegisterAdjointPrimaryWeight(), RegisterAtEndOfAdjointTrack(), ResetDidOneAdjPartReachExtSourceDuringEvent(), SetAdjointActions(), SetAdjointSteppingAction(), SetExtSourceEmax(), SetRestOfAdjointActions(), and ~G4AdjointSimManager().
G4AdjointTrackingAction* G4AdjointSimManager::theAdjointTrackingAction private
Definition at line 294 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 294 of file G4AdjointSimManager.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), G4AdjointSimManager(), GetAdjointTrackingMode(), GetCosthAtEndOfLastAdjointTrack(), GetDirectionAtEndOfLastAdjointTrack(), GetEkinAtEndOfLastAdjointTrack(), GetEkinNucAtEndOfLastAdjointTrack(), GetFwdParticleIndexAtEndOfLastAdjointTrack(), GetFwdParticleNameAtEndOfLastAdjointTrack(), GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack(), GetNbOfAdointTracksReachingTheExternalSurface(), GetPositionAtEndOfLastAdjointTrack(), GetWeightAtEndOfLastAdjointTrack(), SetAdjointActions(), SetRestOfAdjointActions(), and ~G4AdjointSimManager().
G4AdjointSimMessenger* G4AdjointSimManager::theMessenger private
Definition at line 275 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 275 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), and ~G4AdjointSimManager().
bool G4AdjointSimManager::use_user_StackingAction private
Definition at line 286 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 286 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), SetAdjointActions(), SetAdjointPrimaryRunAndStackingActions(), and UseUserStackingActionInFwdTrackingPhase().
bool G4AdjointSimManager::use_user_TrackingAction private
Definition at line 287 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 287 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), SetAdjointActions(), and UseUserTrackingActionInFwdTrackingPhase().
bool G4AdjointSimManager::user_action_already_defined private
Definition at line 279 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 279 of file G4AdjointSimManager.hh
Referenced by DefineUserActions(), G4AdjointSimManager(), SetAdjointActions(), SetAdjointPrimaryRunAndStackingActions(), and SetRestOfAdjointActions().
G4bool G4AdjointSimManager::welcome_message private
Definition at line 343 of file G4AdjointSimManager.hh.
View newest version in sPHENIX GitHub at line 343 of file G4AdjointSimManager.hh
Referenced by G4AdjointSimManager(), and RunAdjointSimulation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4AdjointSimManager.hh
geant4/tree/geant4-10.6-release/source/run/src/G4AdjointSimManager.cc