ECCE @ EIC Software: G4ParticleHPWattSpectrum Class Reference
G4ParticleHPWattSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPWattSpectrum.hh>
Public Member Functions
G4ParticleHPWattSpectrum ()
~G4ParticleHPWattSpectrum ()
void Init (std::istream &aDataFile)
G4double GetFractionalProbability (G4double anEnergy)
G4double Sample (G4double anEnergy)
Public Member Functions inherited from G4VParticleHPEDis
G4VParticleHPEDis ()
virtual ~G4VParticleHPEDis ()
Private Member Functions
G4double Watt (G4double anEnergy, G4double a, G4double b)
Private Attributes
G4double expm1
G4ParticleHPVector theFractionalProb
G4ParticleHPVector theApar
G4ParticleHPVector theBpar
Detailed Description
Definition at line 44 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPWattSpectrum.hh
Constructor & Destructor Documentation
G4ParticleHPWattSpectrum::G4ParticleHPWattSpectrum () inline
Definition at line 47 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPWattSpectrum.hh
References expm1, and G4Exp().
G4ParticleHPWattSpectrum::~G4ParticleHPWattSpectrum () inline
Definition at line 51 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPWattSpectrum.hh
Member Function Documentation
G4double G4ParticleHPWattSpectrum::GetFractionalProbability (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 62 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPWattSpectrum.hh
References G4ParticleHPVector::GetY(), and theFractionalProb.
void G4ParticleHPWattSpectrum::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEDis.
Definition at line 55 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPWattSpectrum.hh
References CLHEP::eV, G4ParticleHPVector::Init(), theApar, theBpar, and theFractionalProb.
G4double G4ParticleHPWattSpectrum::Sample (G4double anEnergy) virtual
Implements G4VParticleHPEDis.
Definition at line 35 of file G4ParticleHPWattSpectrum.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPWattSpectrum.cc
References a, b, eV, G4cout, G4endl, G4Log(), G4UniformRand, G4ParticleHPVector::GetY(), max, theApar, and theBpar.
G4double G4ParticleHPWattSpectrum::Watt (G4double anEnergy, G4double a, G4double b) inline private
Definition at line 71 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPWattSpectrum.hh
References energy, CLHEP::eV, and G4Exp().
Member Data Documentation
G4double G4ParticleHPWattSpectrum::expm1 private
Definition at line 80 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPWattSpectrum.hh
Referenced by G4ParticleHPWattSpectrum().
G4ParticleHPVector G4ParticleHPWattSpectrum::theApar private
Definition at line 84 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPWattSpectrum.hh
Referenced by Init(), and Sample().
G4ParticleHPVector G4ParticleHPWattSpectrum::theBpar private
Definition at line 85 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPWattSpectrum.hh
Referenced by Init(), and Sample().
G4ParticleHPVector G4ParticleHPWattSpectrum::theFractionalProb private
Definition at line 82 of file G4ParticleHPWattSpectrum.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPWattSpectrum.hh
Referenced by GetFractionalProbability(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPWattSpectrum.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPWattSpectrum.cc