ECCE @ EIC Software: G4SoftStringBuilder Class Reference
G4SoftStringBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4SoftStringBuilder.hh>
Public Member Functions
G4SoftStringBuilder ()
~G4SoftStringBuilder ()
G4ExcitedString * BuildString (G4PartonPair *aPair)
Private Member Functions
G4SoftStringBuilder (const G4SoftStringBuilder &right)
G4bool operator== (const G4SoftStringBuilder &right) const
G4bool operator!= (const G4SoftStringBuilder &right) const
Detailed Description
Definition at line 35 of file G4SoftStringBuilder.hh.
View newest version in sPHENIX GitHub at line 35 of file G4SoftStringBuilder.hh
Constructor & Destructor Documentation
G4SoftStringBuilder::G4SoftStringBuilder ()
Definition at line 31 of file G4SoftStringBuilder.cc.
View newest version in sPHENIX GitHub at line 31 of file G4SoftStringBuilder.cc
G4SoftStringBuilder::~G4SoftStringBuilder ()
Definition at line 35 of file G4SoftStringBuilder.cc.
View newest version in sPHENIX GitHub at line 35 of file G4SoftStringBuilder.cc
G4SoftStringBuilder::G4SoftStringBuilder (const G4SoftStringBuilder & right) private
Member Function Documentation
G4ExcitedString * G4SoftStringBuilder::BuildString (G4PartonPair * aPair)
Definition at line 41 of file G4SoftStringBuilder.cc.
View newest version in sPHENIX GitHub at line 41 of file G4SoftStringBuilder.cc
References G4cout, G4endl, G4Parton::Get4Momentum(), G4PartonPair::GetDirection(), G4PartonPair::GetParton1(), G4PartonPair::GetParton2(), G4Parton::GetPDGcode(), and G4Parton::GetX().
G4bool G4SoftStringBuilder::operator!= (const G4SoftStringBuilder & right) const private
G4bool G4SoftStringBuilder::operator== (const G4SoftStringBuilder & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4SoftStringBuilder.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4SoftStringBuilder.cc