ECCE @ EIC Software: G4DiffractiveExcitation Class Reference
G4DiffractiveExcitation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4DiffractiveExcitation.hh>
Classes
struct CommonVariables
Public Member Functions
G4DiffractiveExcitation ()
virtual ~G4DiffractiveExcitation ()
virtual G4bool ExciteParticipants (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4FTFParameters *theParameters, G4ElasticHNScattering *theElastic) const
virtual void CreateStrings (G4VSplitableHadron *aHadron, G4bool isProjectile, G4ExcitedString *&FirstString, G4ExcitedString *&SecondString, G4FTFParameters *theParameters) const
Private Member Functions
G4DiffractiveExcitation (const G4DiffractiveExcitation &right)
const G4DiffractiveExcitation & operator= (const G4DiffractiveExcitation &right)
G4bool operator== (const G4DiffractiveExcitation &right) const
G4bool operator!= (const G4DiffractiveExcitation &right) const
G4double LambdaF (G4double sqrM, G4double sqrM1, G4double sqrM2) const
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
G4double ChooseP (G4double Pmin, G4double Pmax) const
G4double GetQuarkFractionOfKink (G4double zmin, G4double zmax) const
void UnpackMeson (G4int IdPDG, G4int &Q1, G4int &Q2) const
void UnpackBaryon (G4int IdPDG, G4int &Q1, G4int &Q2, G4int &Q3) const
G4int NewNucleonId (G4int Q1, G4int Q2, G4int Q3) const
G4int ExciteParticipants_doChargeExchange (G4VSplitableHadron *projectile, G4VSplitableHadron *target, G4FTFParameters *theParameters, G4ElasticHNScattering *theElastic, CommonVariables &common) const
G4bool ExciteParticipants_doDiffraction (G4VSplitableHadron *projectile, G4VSplitableHadron *target, G4FTFParameters *theParameters, CommonVariables &common) const
G4bool ExciteParticipants_doNonDiffraction (G4VSplitableHadron *projectile, G4VSplitableHadron *target, G4FTFParameters *theParameters, CommonVariables &common) const
Detailed Description
Definition at line 52 of file G4DiffractiveExcitation.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DiffractiveExcitation.hh
Constructor & Destructor Documentation
G4DiffractiveExcitation::G4DiffractiveExcitation ()
Definition at line 79 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 79 of file G4DiffractiveExcitation.cc
G4DiffractiveExcitation::~G4DiffractiveExcitation () virtual
Definition at line 84 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 84 of file G4DiffractiveExcitation.cc
G4DiffractiveExcitation::G4DiffractiveExcitation (const G4DiffractiveExcitation & right) private
Definition at line 1423 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1423 of file G4DiffractiveExcitation.cc
Member Function Documentation
G4double G4DiffractiveExcitation::ChooseP (G4double Pmin, G4double Pmax) const private
Definition at line 1316 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1316 of file G4DiffractiveExcitation.cc
References G4cout, G4endl, G4UniformRand, G4Pow::GetInstance(), P, and G4Pow::powA().
Referenced by ExciteParticipants_doDiffraction(), and ExciteParticipants_doNonDiffraction().
void G4DiffractiveExcitation::CreateStrings (G4VSplitableHadron * aHadron, G4bool isProjectile, G4ExcitedString *& FirstString, G4ExcitedString *& SecondString, G4FTFParameters * theParameters) const virtual
Definition at line 989 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 989 of file G4DiffractiveExcitation.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4Exp(), G4Log(), G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4Parton::Get4Momentum(), G4Parton::GetDefinition(), G4Pow::GetInstance(), G4VSplitableHadron::GetNextParton(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetParticleType(), G4Parton::GetPDGcode(), G4ParticleDefinition::GetPDGEncoding(), G4VSplitableHadron::GetPosition(), G4FTFParameters::GetProjMinDiffMass(), G4FTFParameters::GetPt2Kink(), GetQuarkFractionOfKink(), G4FTFParameters::GetQuarkProbabilitiesAtGluonSplitUp(), G4VSplitableHadron::GetStatus(), G4FTFParameters::GetTarMinDiffMass(), G4VSplitableHadron::GetTimeOfCreation(), CLHEP::HepLorentzVector::getZ(), CLHEP::Hep3Vector::mag(), CLHEP::HepLorentzVector::mag(), MeV, pi, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), CLHEP::Hep3Vector::set(), G4Parton::Set4Momentum(), CLHEP::HepLorentzVector::setE(), G4ExcitedString::SetPosition(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), CLHEP::HepLorentzVector::setT(), G4ExcitedString::SetTimeOfCreation(), G4VSplitableHadron::SplitUp(), sqr(), start(), tmp, CLHEP::HepLorentzVector::transform(), twopi, CLHEP::HepLorentzVector::vect(), x1, x3, Y, and Ymax.
Referenced by G4FTFModel::BuildStrings().
G4bool G4DiffractiveExcitation::ExciteParticipants (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4FTFParameters * theParameters, G4ElasticHNScattering * theElastic) const virtual
Definition at line 89 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 89 of file G4DiffractiveExcitation.cc
References kdfinder::abs(), G4DiffractiveExcitation::CommonVariables::absProjectilePDGcode, G4DiffractiveExcitation::CommonVariables::absTargetPDGcode, CLHEP::HepLorentzVector::boostVector(), G4DiffractiveExcitation::CommonVariables::BrW, common(), ExciteParticipants_doChargeExchange(), ExciteParticipants_doDiffraction(), ExciteParticipants_doNonDiffraction(), G4cout, G4endl, G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4SampleResonance::GetMinimumMass(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4FTFParameters::GetProcProb(), G4FTFParameters::GetProjMinDiffMass(), G4FTFParameters::GetProjMinNonDiffMass(), G4FTFParameters::GetTarMinDiffMass(), G4FTFParameters::GetTarMinNonDiffMass(), if(), G4VSplitableHadron::IncrementCollisionCount(), CLHEP::HepLorentzRotation::inverse(), G4DiffractiveExcitation::CommonVariables::M0projectile, G4DiffractiveExcitation::CommonVariables::M0projectile2, G4DiffractiveExcitation::CommonVariables::M0target, G4DiffractiveExcitation::CommonVariables::M0target2, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, G4DiffractiveExcitation::CommonVariables::MminProjectile, G4DiffractiveExcitation::CommonVariables::MminTarget, G4DiffractiveExcitation::CommonVariables::Pprojectile, G4DiffractiveExcitation::CommonVariables::ProbExc, G4DiffractiveExcitation::CommonVariables::ProbOfDiffraction, G4DiffractiveExcitation::CommonVariables::ProbProjectileDiffraction, G4DiffractiveExcitation::CommonVariables::ProbTargetDiffraction, G4DiffractiveExcitation::CommonVariables::ProjectileDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::ProjectileDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::ProjectileNonDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::ProjectileNonDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::ProjectilePDGcode, G4DiffractiveExcitation::CommonVariables::Ptarget, G4DiffractiveExcitation::CommonVariables::PZcms, G4DiffractiveExcitation::CommonVariables::PZcms2, G4DiffractiveExcitation::CommonVariables::Qmomentum, CLHEP::HepLorentzVector::rapidity(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4DiffractiveExcitation::CommonVariables::S, G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), G4DiffractiveExcitation::CommonVariables::SqrtS, G4DiffractiveExcitation::CommonVariables::TargetDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::TargetDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::TargetNonDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::TargetNonDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::TargetPDGcode, G4DiffractiveExcitation::CommonVariables::toCms, G4DiffractiveExcitation::CommonVariables::toLab, CLHEP::HepLorentzVector::transform(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by G4FTFModel::ExciteParticipants().
G4int G4DiffractiveExcitation::ExciteParticipants_doChargeExchange (G4VSplitableHadron * projectile, G4VSplitableHadron * target, G4FTFParameters * theParameters, G4ElasticHNScattering * theElastic, G4DiffractiveExcitation::CommonVariables & common) const private
Definition at line 326 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 326 of file G4DiffractiveExcitation.cc
References kdfinder::abs(), G4DiffractiveExcitation::CommonVariables::absProjectilePDGcode, G4DiffractiveExcitation::CommonVariables::absTargetPDGcode, G4DiffractiveExcitation::CommonVariables::BrW, G4ElasticHNScattering::ElasticScattering(), G4ParticleTable::FindParticle(), G4cout, G4endl, G4UniformRand, G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4FTFParameters::GetDeltaProbAtQuarkExchange(), G4SampleResonance::GetMinimumMass(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), G4FTFParameters::GetProbOfSameQuarkExchange(), G4VSplitableHadron::GetStatus(), if(), G4DiffractiveExcitation::CommonVariables::M0projectile, G4DiffractiveExcitation::CommonVariables::M0projectile2, G4DiffractiveExcitation::CommonVariables::M0target, G4DiffractiveExcitation::CommonVariables::M0target2, CLHEP::HepLorentzVector::mag(), MeV, G4DiffractiveExcitation::CommonVariables::MminProjectile, G4DiffractiveExcitation::CommonVariables::MminTarget, NewNucleonId(), G4DiffractiveExcitation::CommonVariables::Pprojectile, G4DiffractiveExcitation::CommonVariables::ProbExc, G4DiffractiveExcitation::CommonVariables::ProbOfDiffraction, G4DiffractiveExcitation::CommonVariables::ProbProjectileDiffraction, G4DiffractiveExcitation::CommonVariables::ProbTargetDiffraction, G4DiffractiveExcitation::CommonVariables::ProjectileDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::ProjectileNonDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::ProjectilePDGcode, G4DiffractiveExcitation::CommonVariables::Ptarget, G4DiffractiveExcitation::CommonVariables::PZcms, G4DiffractiveExcitation::CommonVariables::PZcms2, G4DiffractiveExcitation::CommonVariables::S, G4SampleResonance::SampleMass(), G4VSplitableHadron::Set4Momentum(), G4VSplitableHadron::SetDefinition(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SetStatus(), sqr(), G4DiffractiveExcitation::CommonVariables::SqrtS, G4DiffractiveExcitation::CommonVariables::TargetDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::TargetNonDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::TargetPDGcode, G4DiffractiveExcitation::CommonVariables::toLab, CLHEP::HepLorentzVector::transform(), UnpackBaryon(), and UnpackMeson().
Referenced by ExciteParticipants().
G4bool G4DiffractiveExcitation::ExciteParticipants_doDiffraction (G4VSplitableHadron * projectile, G4VSplitableHadron * target, G4FTFParameters * theParameters, G4DiffractiveExcitation::CommonVariables & common) const private
Definition at line 795 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 795 of file G4DiffractiveExcitation.cc
References ChooseP(), G4cout, G4endl, G4UniformRand, GaussianPt(), G4FTFParameters::GetAvaragePt2ofElasticScattering(), G4VSplitableHadron::GetSoftCollisionCount(), G4VSplitableHadron::GetStatus(), if(), G4DiffractiveExcitation::CommonVariables::M0projectile, G4DiffractiveExcitation::CommonVariables::M0projectile2, G4DiffractiveExcitation::CommonVariables::M0target, G4DiffractiveExcitation::CommonVariables::M0target2, G4DiffractiveExcitation::CommonVariables::maxPtSquare, CLHEP::HepLorentzVector::minus(), CLHEP::HepLorentzVector::plus(), G4DiffractiveExcitation::CommonVariables::PMinusMax, G4DiffractiveExcitation::CommonVariables::PMinusMin, G4DiffractiveExcitation::CommonVariables::PMinusNew, G4DiffractiveExcitation::CommonVariables::PPlusNew, G4DiffractiveExcitation::CommonVariables::Pprojectile, G4DiffractiveExcitation::CommonVariables::ProbProjectileDiffraction, G4DiffractiveExcitation::CommonVariables::ProjectileDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::ProjectileDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::ProjMassT, G4DiffractiveExcitation::CommonVariables::ProjMassT2, G4DiffractiveExcitation::CommonVariables::Pt2, G4DiffractiveExcitation::CommonVariables::Ptarget, G4DiffractiveExcitation::CommonVariables::PZcms, G4DiffractiveExcitation::CommonVariables::PZcms2, G4DiffractiveExcitation::CommonVariables::Qminus, G4DiffractiveExcitation::CommonVariables::Qmomentum, G4DiffractiveExcitation::CommonVariables::Qplus, G4DiffractiveExcitation::CommonVariables::S, CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SetStatus(), sqr(), G4DiffractiveExcitation::CommonVariables::SqrtS, G4DiffractiveExcitation::CommonVariables::TargetDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::TargetDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::TargMassT, G4DiffractiveExcitation::CommonVariables::TargMassT2, G4DiffractiveExcitation::CommonVariables::TMinusNew, G4DiffractiveExcitation::CommonVariables::TPlusMax, G4DiffractiveExcitation::CommonVariables::TPlusMin, G4DiffractiveExcitation::CommonVariables::TPlusNew, and CLHEP::HepLorentzVector::vect().
Referenced by ExciteParticipants().
G4bool G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction (G4VSplitableHadron * projectile, G4VSplitableHadron * target, G4FTFParameters * theParameters, G4DiffractiveExcitation::CommonVariables & common) const private
Definition at line 903 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 903 of file G4DiffractiveExcitation.cc
References ChooseP(), G4cout, G4endl, G4UniformRand, GaussianPt(), G4FTFParameters::GetAveragePt2(), G4FTFParameters::GetProbLogDistr(), G4FTFParameters::GetProbLogDistrPrD(), if(), G4DiffractiveExcitation::CommonVariables::maxPtSquare, CLHEP::HepLorentzVector::minus(), CLHEP::HepLorentzVector::plus(), G4DiffractiveExcitation::CommonVariables::PMinusMax, G4DiffractiveExcitation::CommonVariables::PMinusMin, G4DiffractiveExcitation::CommonVariables::PMinusNew, G4DiffractiveExcitation::CommonVariables::Pprojectile, G4DiffractiveExcitation::CommonVariables::ProjectileNonDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::ProjectileNonDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::ProjMassT, G4DiffractiveExcitation::CommonVariables::ProjMassT2, G4DiffractiveExcitation::CommonVariables::Pt2, G4DiffractiveExcitation::CommonVariables::Ptarget, G4DiffractiveExcitation::CommonVariables::PZcms, G4DiffractiveExcitation::CommonVariables::PZcms2, G4DiffractiveExcitation::CommonVariables::Qminus, G4DiffractiveExcitation::CommonVariables::Qmomentum, G4DiffractiveExcitation::CommonVariables::Qplus, G4DiffractiveExcitation::CommonVariables::S, CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SetStatus(), sqr(), G4DiffractiveExcitation::CommonVariables::SqrtS, G4DiffractiveExcitation::CommonVariables::TargetNonDiffStateMinMass, G4DiffractiveExcitation::CommonVariables::TargetNonDiffStateMinMass2, G4DiffractiveExcitation::CommonVariables::TargMassT, G4DiffractiveExcitation::CommonVariables::TargMassT2, G4DiffractiveExcitation::CommonVariables::TPlusMax, G4DiffractiveExcitation::CommonVariables::TPlusMin, G4DiffractiveExcitation::CommonVariables::TPlusNew, and CLHEP::HepLorentzVector::vect().
Referenced by ExciteParticipants().
G4ThreeVector G4DiffractiveExcitation::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 1333 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1333 of file G4DiffractiveExcitation.cc
References G4Exp(), G4Log(), G4UniformRand, phi, and twopi.
Referenced by ExciteParticipants_doDiffraction(), and ExciteParticipants_doNonDiffraction().
G4double G4DiffractiveExcitation::GetQuarkFractionOfKink (G4double zmin, G4double zmax) const private
Definition at line 1350 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1350 of file G4DiffractiveExcitation.cc
References G4UniformRand, sqr(), and z.
Referenced by CreateStrings().
G4double G4DiffractiveExcitation::LambdaF (G4double sqrM, G4double sqrM1, G4double sqrM2) const private
G4int G4DiffractiveExcitation::NewNucleonId (G4int Q1, G4int Q2, G4int Q3) const private
Definition at line 1400 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1400 of file G4DiffractiveExcitation.cc
Referenced by ExciteParticipants_doChargeExchange().
G4bool G4DiffractiveExcitation::operator!= (const G4DiffractiveExcitation & right) const private
Definition at line 1448 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1448 of file G4DiffractiveExcitation.cc
const G4DiffractiveExcitation & G4DiffractiveExcitation::operator= (const G4DiffractiveExcitation & right) private
Definition at line 1431 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1431 of file G4DiffractiveExcitation.cc
G4bool G4DiffractiveExcitation::operator== (const G4DiffractiveExcitation & right) const private
Definition at line 1440 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1440 of file G4DiffractiveExcitation.cc
void G4DiffractiveExcitation::UnpackBaryon (G4int IdPDG, G4int & Q1, G4int & Q2, G4int & Q3) const private
Definition at line 1389 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1389 of file G4DiffractiveExcitation.cc
Referenced by ExciteParticipants_doChargeExchange().
void G4DiffractiveExcitation::UnpackMeson (G4int IdPDG, G4int & Q1, G4int & Q2) const private
Definition at line 1368 of file G4DiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 1368 of file G4DiffractiveExcitation.cc
References kdfinder::abs(), G4UniformRand, and max.
Referenced by ExciteParticipants_doChargeExchange().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4DiffractiveExcitation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4DiffractiveExcitation.cc