ECCE @ EIC Software: G4FissionBarrier Class Reference
G4FissionBarrier Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionBarrier.hh>
Public Member Functions
G4FissionBarrier ()
~G4FissionBarrier () override
G4double FissionBarrier (G4int A, G4int Z, G4double U) const final
Public Member Functions inherited from G4VFissionBarrier
G4VFissionBarrier ()
virtual ~G4VFissionBarrier ()
Private Member Functions
G4double BarashenkovFissionBarrier (G4int A, G4int Z) const
G4FissionBarrier (const G4FissionBarrier &right)
const G4FissionBarrier & operator= (const G4FissionBarrier &right)
G4bool operator== (const G4FissionBarrier &right) const
G4bool operator!= (const G4FissionBarrier &right) const
Private Attributes
const
G4CameronShellPlusPairingCorrections * SPtr
Detailed Description
Definition at line 42 of file G4FissionBarrier.hh.
View newest version in sPHENIX GitHub at line 42 of file G4FissionBarrier.hh
Constructor & Destructor Documentation
G4FissionBarrier::G4FissionBarrier () explicit
Definition at line 40 of file G4FissionBarrier.cc.
View newest version in sPHENIX GitHub at line 40 of file G4FissionBarrier.cc
References G4ShellCorrection::GetCameronShellPlusPairingCorrections(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetShellCorrection(), and SPtr.
G4FissionBarrier::~G4FissionBarrier () override
Definition at line 46 of file G4FissionBarrier.cc.
View newest version in sPHENIX GitHub at line 46 of file G4FissionBarrier.cc
G4FissionBarrier::G4FissionBarrier (const G4FissionBarrier & right) private
Member Function Documentation
G4double G4FissionBarrier::BarashenkovFissionBarrier (G4int A, G4int Z) const private
Definition at line 60 of file G4FissionBarrier.cc.
View newest version in sPHENIX GitHub at line 60 of file G4FissionBarrier.cc
References A(), D(), d, G4Pow::GetInstance(), k, CLHEP::MeV, N, x, Z, and G4Pow::Z23().
G4double G4FissionBarrier::FissionBarrier (G4int A, G4int Z, G4double U) const final virtual
Implements G4VFissionBarrier.
Definition at line 50 of file G4FissionBarrier.cc.
View newest version in sPHENIX GitHub at line 50 of file G4FissionBarrier.cc
References A(), CLHEP::GeV, and Z.
G4bool G4FissionBarrier::operator!= (const G4FissionBarrier & right) const private
const G4FissionBarrier& G4FissionBarrier::operator= (const G4FissionBarrier & right) private
G4bool G4FissionBarrier::operator== (const G4FissionBarrier & right) const private
Member Data Documentation
const G4CameronShellPlusPairingCorrections* G4FissionBarrier::SPtr private
Definition at line 61 of file G4FissionBarrier.hh.
View newest version in sPHENIX GitHub at line 61 of file G4FissionBarrier.hh
Referenced by G4FissionBarrier().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionBarrier.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/src/G4FissionBarrier.cc