ECCE @ EIC Software: G4ErrorPropagator Class Reference
G4ErrorPropagator Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorPropagator.hh>
Public Member Functions
G4ErrorPropagator ()
~G4ErrorPropagator ()
G4Track * InitG4Track (G4ErrorTrajState &initialTS)
G4int Propagate (G4ErrorTrajState *currentTS, const G4ErrorTarget *target, G4ErrorMode mode=G4ErrorMode_PropForwards)
G4int PropagateOneStep (G4ErrorTrajState *currentTS)
G4int MakeOneStep (G4ErrorFreeTrajState *currentTS_FREE)
G4ErrorFreeTrajState * InitFreeTrajState (G4ErrorTrajState *currentTS)
void GetFinalTrajState (G4ErrorTrajState *currentTS, G4ErrorFreeTrajState *currentTS_FREE, const G4ErrorTarget *target)
void InvokePreUserTrackingAction (G4Track *fpTrack)
void InvokePostUserTrackingAction (G4Track *fpTrack)
G4bool CheckIfLastStep (G4Track *aTrack)
const G4ErrorTrajState * GetInitialTrajState () const
G4double GetStepLength () const
void SetStepLength (const G4double sl)
void SetStepN (const G4int sn)
Private Member Functions
G4int MakeSteps (G4ErrorFreeTrajState *currentTS_FREE)
Private Attributes
G4double theStepLength
G4ErrorTrajState * theInitialTrajState
G4int theStepN
G4Track * theG4Track
G4SteppingManager * fpSteppingManager
G4int verbose
G4bool thePropIsInitialized
Detailed Description
Definition at line 53 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ErrorPropagator.hh
Constructor & Destructor Documentation
G4ErrorPropagator::G4ErrorPropagator ()
Definition at line 56 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ErrorPropagator.cc
References fpSteppingManager, G4cout, G4endl, G4EventManager::GetEventManager(), G4TrackingManager::GetSteppingManager(), G4EventManager::GetTrackingManager(), thePropIsInitialized, G4ErrorPropagatorData::verbose(), and verbose.
G4ErrorPropagator::~G4ErrorPropagator () inline
Definition at line 58 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ErrorPropagator.hh
Member Function Documentation
G4bool G4ErrorPropagator::CheckIfLastStep (G4Track * aTrack)
Definition at line 526 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 526 of file G4ErrorPropagator.cc
References FatalException, fStopAndKill, G4cout, G4endl, G4ErrorState_StoppedAtTarget, G4Exception(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4Track::GetNextVolume(), G4ErrorPropagatorData::GetState(), G4Track::GetTrackStatus(), JustWarning, message(), and verbose.
Referenced by MakeSteps(), and ProcessEvent().
void G4ErrorPropagator::GetFinalTrajState (G4ErrorTrajState * currentTS, G4ErrorFreeTrajState * currentTS_FREE, const G4ErrorTarget * target)
Definition at line 480 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 480 of file G4ErrorPropagator.cc
References FatalException, G4cout, G4endl, G4ErrorState_StoppedAtTarget, G4ErrorTarget_TrkL, G4eTS_FREE, G4eTS_OS, G4Exception(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorTrajState::GetPosition(), G4ErrorPropagatorData::GetState(), G4ErrorTanPlaneTarget::GetTangentPlane(), G4ErrorTrajState::GetTSType(), G4ErrorTarget::GetType(), and verbose.
Referenced by Propagate(), and PropagateOneStep().
const G4ErrorTrajState* G4ErrorPropagator::GetInitialTrajState () const inline
Definition at line 98 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ErrorPropagator.hh
References theInitialTrajState.
G4double G4ErrorPropagator::GetStepLength () const inline
Definition at line 101 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ErrorPropagator.hh
References theStepLength.
G4ErrorFreeTrajState * G4ErrorPropagator::InitFreeTrajState (G4ErrorTrajState * currentTS)
Definition at line 452 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 452 of file G4ErrorPropagator.cc
References FatalException, G4eTS_FREE, G4eTS_OS, G4Exception(), G4ErrorTrajState::GetTSType(), and message().
Referenced by Propagate(), and PropagateOneStep().
G4Track * G4ErrorPropagator::InitG4Track (G4ErrorTrajState & initialTS)
Definition at line 254 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 254 of file G4ErrorPropagator.cc
References eplus, FatalException, G4ParticleTable::FindParticle(), fpSteppingManager, G4cout, G4endl, G4Exception(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4ErrorTrajState::GetMomentum(), G4ParticleTable::GetParticleTable(), G4ErrorTrajState::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ErrorTrajState::GetPosition(), G4ParticleDefinition::GetProcessManager(), G4SteppingManager::GetProcessNumber(), G4SteppingManager::GetStep(), InvokePreUserTrackingAction(), message(), particle, G4DynamicParticle::SetCharge(), G4ErrorTrajState::SetG4Track(), G4SteppingManager::SetInitialStep(), G4Track::SetParentID(), G4DynamicParticle::SetPolarization(), G4Track::SetStep(), G4ProcessManager::StartTracking(), theG4Track, and verbose.
Referenced by Propagate(), and PropagateOneStep().
void G4ErrorPropagator::InvokePostUserTrackingAction (G4Track * fpTrack)
Definition at line 630 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 630 of file G4ErrorPropagator.cc
References G4EventManager::GetEventManager(), and G4EventManager::GetUserTrackingAction().
Referenced by ProcessEvent(), and Propagate().
void G4ErrorPropagator::InvokePreUserTrackingAction (G4Track * fpTrack)
Definition at line 617 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 617 of file G4ErrorPropagator.cc
References G4EventManager::GetEventManager(), and G4EventManager::GetUserTrackingAction().
Referenced by InitG4Track().
G4int G4ErrorPropagator::MakeOneStep (G4ErrorFreeTrajState * currentTS_FREE)
Definition at line 358 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 358 of file G4ErrorPropagator.cc
References fpSteppingManager, G4cout, G4endl, G4ErrorState_StoppedAtTarget, G4ErrorState_TargetCloserThanBoundary, G4ErrorTarget_GeomVolume, G4Exception(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4Step::GetPostStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4ErrorPropagatorData::GetState(), G4Track::GetStep(), G4Track::GetStepLength(), G4ErrorPropagatorData::GetTarget(), G4ErrorTarget::GetType(), G4Track::IncrementCurrentStepNumber(), JustWarning, message(), G4ErrorFreeTrajState::PropagateError(), G4ErrorPropagatorData::SetState(), G4SteppingManager::Stepping(), theG4Track, theStepLength, G4ErrorFreeTrajState::Update(), and verbose.
Referenced by MakeSteps(), and PropagateOneStep().
G4int G4ErrorPropagator::MakeSteps (G4ErrorFreeTrajState * currentTS_FREE) private
Definition at line 332 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 332 of file G4ErrorPropagator.cc
References CheckIfLastStep(), fAlive, fStopButAlive, G4Track::GetTrackStatus(), MakeOneStep(), theG4Track, and theStepLength.
Referenced by Propagate().
G4int G4ErrorPropagator::Propagate (G4ErrorTrajState * currentTS, const G4ErrorTarget * target, G4ErrorMode mode = G4ErrorMode_PropForwards)
Definition at line 71 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ErrorPropagator.cc
References G4ErrorTarget::Dump(), G4ProcessManager::EndTracking(), G4BestUnit, G4cout, G4endl, G4ErrorState_StoppedAtTarget, G4Exception(), G4Track::GetDefinition(), G4ErrorPropagatorData::GetErrorPropagatorData(), GetFinalTrajState(), G4Track::GetKineticEnergy(), G4ErrorPropagatorData::GetMode(), G4ErrorTrajState::GetMomentum(), G4ErrorTrajState::GetParticleType(), G4ParticleDefinition::GetProcessManager(), G4ErrorPropagatorData::GetState(), InitFreeTrajState(), InitG4Track(), InvokePostUserTrackingAction(), JustWarning, HepGeom::BasicVector3D< T >::mag(), MakeSteps(), message(), MeV, G4ErrorPropagatorData::SetMode(), G4ErrorPropagatorData::SetTarget(), theG4Track, and verbose.
Referenced by G4ErrorPropagatorManager::Propagate().
G4int G4ErrorPropagator::PropagateOneStep (G4ErrorTrajState * currentTS)
Definition at line 181 of file G4ErrorPropagator.cc.
View newest version in sPHENIX GitHub at line 181 of file G4ErrorPropagator.cc
References FatalException, G4BestUnit, G4cout, G4endl, G4ErrorState_PreInit, G4Exception(), G4State_GeomClosed, G4StateManager::GetCurrentState(), G4ErrorPropagatorData::GetErrorPropagatorData(), GetFinalTrajState(), G4ErrorPropagatorData::GetMode(), G4ErrorTrajState::GetMomentum(), G4ErrorTrajState::GetParticleType(), G4ErrorPropagatorData::GetState(), G4StateManager::GetStateManager(), G4ErrorPropagatorData::GetTarget(), InitFreeTrajState(), InitG4Track(), JustWarning, HepGeom::BasicVector3D< T >::mag(), MakeOneStep(), message(), MeV, theG4Track, theStepN, and verbose.
Referenced by G4ErrorPropagatorManager::PropagateOneStep().
void G4ErrorPropagator::SetStepLength (const G4double sl) inline
Definition at line 104 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ErrorPropagator.hh
References theStepLength.
void G4ErrorPropagator::SetStepN (const G4int sn) inline
Definition at line 107 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ErrorPropagator.hh
References sn, and theStepN.
Referenced by G4ErrorPropagatorManager::InitTrackPropagation().
Member Data Documentation
G4SteppingManager* G4ErrorPropagator::fpSteppingManager private
Definition at line 125 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ErrorPropagator.hh
Referenced by G4ErrorPropagator(), InitG4Track(), and MakeOneStep().
G4Track* G4ErrorPropagator::theG4Track private
Definition at line 123 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ErrorPropagator.hh
Referenced by InitG4Track(), MakeOneStep(), MakeSteps(), Propagate(), and PropagateOneStep().
G4ErrorTrajState* G4ErrorPropagator::theInitialTrajState private
Definition at line 119 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ErrorPropagator.hh
Referenced by GetInitialTrajState().
G4bool G4ErrorPropagator::thePropIsInitialized private
Definition at line 129 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ErrorPropagator.hh
Referenced by G4ErrorPropagator().
G4double G4ErrorPropagator::theStepLength private
Definition at line 117 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ErrorPropagator.hh
Referenced by GetStepLength(), MakeOneStep(), MakeSteps(), and SetStepLength().
G4int G4ErrorPropagator::theStepN private
Definition at line 121 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ErrorPropagator.hh
Referenced by PropagateOneStep(), and SetStepN().
G4int G4ErrorPropagator::verbose private
Definition at line 127 of file G4ErrorPropagator.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ErrorPropagator.hh
Referenced by CheckIfLastStep(), G4ErrorPropagator(), GetFinalTrajState(), InitG4Track(), MakeOneStep(), Propagate(), and PropagateOneStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorPropagator.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorPropagator.cc