ECCE @ EIC Software: Par01DetectorConstruction Class Reference
Par01DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01DetectorConstruction.hh>
Public Member Functions
Par01DetectorConstruction ()
virtual ~Par01DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4LogicalVolume * fCrystalLog
G4LogicalVolume * fTowerLog
G4int fnX
G4int fnY
G4int fnXhad
G4int fnYhad
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 40 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 40 of file Par01DetectorConstruction.hh
Constructor & Destructor Documentation
Par01DetectorConstruction::Par01DetectorConstruction ()
Definition at line 56 of file Par01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 56 of file Par01DetectorConstruction.cc
Par01DetectorConstruction::~Par01DetectorConstruction () virtual
Definition at line 61 of file Par01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 61 of file Par01DetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * Par01DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 66 of file Par01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 66 of file Par01DetectorConstruction.cc
References G4Region::AddRootLogicalVolume(), cm, fCrystalLog, G4NistManager::FindOrBuildMaterial(), fnX, fnXhad, fnY, fnYhad, fTowerLog, G4cout, G4endl, G4VisAttributes::GetInvisible(), G4Region::GetProductionCuts(), G4NistManager::Instance(), mm, G4VisAttributes::SetForceWireframe(), G4ProductionCuts::SetProductionCuts(), G4Region::SetProductionCuts(), and G4LogicalVolume::SetVisAttributes().
void Par01DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 268 of file Par01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 268 of file Par01DetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCrystalLog, fnX, fnXhad, fnY, fnYhad, fTowerLog, G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), G4SDManager::GetSDMpointer(), and G4LogicalVolume::SetSensitiveDetector().
Member Data Documentation
G4LogicalVolume* Par01DetectorConstruction::fCrystalLog private
Definition at line 51 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 51 of file Par01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4int Par01DetectorConstruction::fnX private
Definition at line 53 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 53 of file Par01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4int Par01DetectorConstruction::fnXhad private
Definition at line 54 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file Par01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4int Par01DetectorConstruction::fnY private
Definition at line 53 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 53 of file Par01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4int Par01DetectorConstruction::fnYhad private
Definition at line 54 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file Par01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4LogicalVolume* Par01DetectorConstruction::fTowerLog private
Definition at line 52 of file Par01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 52 of file Par01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01DetectorConstruction.cc