ECCE @ EIC Software: G4QGSPProtonBuilder Class Reference
G4QGSPProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPProtonBuilder.hh>
Public Member Functions
G4QGSPProtonBuilder (G4bool quasiElastic=false)
virtual ~G4QGSPProtonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4QGSMFragmentation * theQGSM
G4double theMin
Detailed Description
Definition at line 58 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QGSPProtonBuilder.hh
Constructor & Destructor Documentation
G4QGSPProtonBuilder::G4QGSPProtonBuilder (G4bool quasiElastic = false)
Definition at line 51 of file G4QGSPProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 51 of file G4QGSPProtonBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSPProtonBuilder::~G4QGSPProtonBuilder () virtual
Definition at line 81 of file G4QGSPProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 81 of file G4QGSPProtonBuilder.cc
References theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSPProtonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VProtonBuilder.
Definition at line 65 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QGSPProtonBuilder.hh
void G4QGSPProtonBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 73 of file G4QGSPProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 73 of file G4QGSPProtonBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicParameters::Instance(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSPProtonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 68 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4QGSPProtonBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4QGSPProtonBuilder::theCascade private
Definition at line 74 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSPProtonBuilder.hh
Referenced by G4QGSPProtonBuilder().
G4double G4QGSPProtonBuilder::theMin private
Definition at line 79 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QGSPProtonBuilder.hh
Referenced by Build(), G4QGSPProtonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSPProtonBuilder::theModel private
Definition at line 73 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QGSPProtonBuilder.hh
Referenced by Build(), and G4QGSPProtonBuilder().
G4QGSMFragmentation* G4QGSPProtonBuilder::theQGSM private
Definition at line 78 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPProtonBuilder.hh
Referenced by G4QGSPProtonBuilder(), and ~G4QGSPProtonBuilder().
G4QuasiElasticChannel* G4QGSPProtonBuilder::theQuasiElastic private
Definition at line 77 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSPProtonBuilder.hh
Referenced by G4QGSPProtonBuilder(), and ~G4QGSPProtonBuilder().
G4ExcitedStringDecay* G4QGSPProtonBuilder::theStringDecay private
Definition at line 76 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSPProtonBuilder.hh
Referenced by G4QGSPProtonBuilder(), and ~G4QGSPProtonBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSPProtonBuilder::theStringModel private
Definition at line 75 of file G4QGSPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSPProtonBuilder.hh
Referenced by G4QGSPProtonBuilder(), and ~G4QGSPProtonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSPProtonBuilder.cc