ECCE @ EIC Software: UltraFresnelLensParameterisation Class Reference
UltraFresnelLensParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/air_shower/include/UltraFresnelLensParameterisation.hh>
Public Member Functions
UltraFresnelLensParameterisation (UltraFresnelLens *)
virtual ~UltraFresnelLensParameterisation ()
void ComputeTransformation (const G4int GrooveNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Cons &Groove, const G4int GrooveNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
UltraFresnelLens * FresnelLens
G4int NumberOfGrooves
G4double GrooveWidth
G4double dZOffset
Detailed Description
Definition at line 70 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 70 of file UltraFresnelLensParameterisation.hh
Constructor & Destructor Documentation
UltraFresnelLensParameterisation::UltraFresnelLensParameterisation (UltraFresnelLens * Lens)
Definition at line 55 of file UltraFresnelLensParameterisation.cc.
View newest version in sPHENIX GitHub at line 55 of file UltraFresnelLensParameterisation.cc
References dZOffset, FresnelLens, UltraFresnelLens::GetGrooveWidth(), UltraFresnelLens::GetNumberOfGrooves(), UltraFresnelLens::GetSagita(), GrooveWidth, and NumberOfGrooves.
UltraFresnelLensParameterisation::~UltraFresnelLensParameterisation () virtual
Definition at line 68 of file UltraFresnelLensParameterisation.cc.
View newest version in sPHENIX GitHub at line 68 of file UltraFresnelLensParameterisation.cc
Member Function Documentation
void UltraFresnelLensParameterisation::ComputeDimensions (G4Cons & Groove, const G4int GrooveNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file UltraFresnelLensParameterisation.cc.
View newest version in sPHENIX GitHub at line 96 of file UltraFresnelLensParameterisation.cc
References FatalException, G4cout, G4endl, G4Exception(), mm, G4Cons::SetInnerRadiusMinusZ(), G4Cons::SetInnerRadiusPlusZ(), G4Cons::SetOuterRadiusMinusZ(), G4Cons::SetOuterRadiusPlusZ(), and G4Cons::SetZHalfLength().
void UltraFresnelLensParameterisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 87 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 88 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 90 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 92 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 93 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 94 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 95 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 96 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 97 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 97 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 98 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 98 of file UltraFresnelLensParameterisation.hh
void UltraFresnelLensParameterisation::ComputeTransformation (const G4int GrooveNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 74 of file UltraFresnelLensParameterisation.cc.
View newest version in sPHENIX GitHub at line 74 of file UltraFresnelLensParameterisation.cc
References FatalException, G4Exception(), Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
Member Data Documentation
G4double UltraFresnelLensParameterisation::dZOffset private
Definition at line 105 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 105 of file UltraFresnelLensParameterisation.hh
Referenced by UltraFresnelLensParameterisation().
UltraFresnelLens* UltraFresnelLensParameterisation::FresnelLens private
Definition at line 102 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 102 of file UltraFresnelLensParameterisation.hh
Referenced by UltraFresnelLensParameterisation().
G4double UltraFresnelLensParameterisation::GrooveWidth private
Definition at line 104 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 104 of file UltraFresnelLensParameterisation.hh
Referenced by UltraFresnelLensParameterisation().
G4int UltraFresnelLensParameterisation::NumberOfGrooves private
Definition at line 103 of file UltraFresnelLensParameterisation.hh.
View newest version in sPHENIX GitHub at line 103 of file UltraFresnelLensParameterisation.hh
Referenced by UltraFresnelLensParameterisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/air_shower/include/UltraFresnelLensParameterisation.hh
geant4/tree/geant4-10.6-release/examples/advanced/air_shower/src/UltraFresnelLensParameterisation.cc