ECCE @ EIC Software: G4VoxelLimits Class Reference
G4VoxelLimits Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VoxelLimits.hh>
Public Member Functions
G4VoxelLimits ()
~G4VoxelLimits ()
void AddLimit (const EAxis pAxis, const G4double pMin, const G4double pMax)
G4double GetMaxXExtent () const
G4double GetMaxYExtent () const
G4double GetMaxZExtent () const
G4double GetMinXExtent () const
G4double GetMinYExtent () const
G4double GetMinZExtent () const
G4double GetMaxExtent (const EAxis pAxis) const
G4double GetMinExtent (const EAxis pAxis) const
G4bool IsXLimited () const
G4bool IsYLimited () const
G4bool IsZLimited () const
G4bool IsLimited () const
G4bool IsLimited (const EAxis pAxis) const
G4bool ClipToLimits (G4ThreeVector &pStart, G4ThreeVector &pEnd) const
G4bool Inside (const G4ThreeVector &pVec) const
G4int OutCode (const G4ThreeVector &pVec) const
Private Attributes
G4double fxAxisMin = -kInfinity
G4double fxAxisMax = kInfinity
G4double fyAxisMin = -kInfinity
G4double fyAxisMax = kInfinity
G4double fzAxisMin = -kInfinity
G4double fzAxisMax = kInfinity
Detailed Description
Definition at line 52 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VoxelLimits.hh
Constructor & Destructor Documentation
G4VoxelLimits::G4VoxelLimits ()
Definition at line 39 of file G4VoxelLimits.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VoxelLimits.cc
G4VoxelLimits::~G4VoxelLimits ()
Definition at line 43 of file G4VoxelLimits.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VoxelLimits.cc
Member Function Documentation
void G4VoxelLimits::AddLimit (const EAxis pAxis, const G4double pMin, const G4double pMax)
Definition at line 52 of file G4VoxelLimits.cc.
View newest version in sPHENIX GitHub at line 52 of file G4VoxelLimits.cc
References fxAxisMax, fxAxisMin, fyAxisMax, fyAxisMin, fzAxisMax, fzAxisMin, kXAxis, kYAxis, kZAxis, pMax, and pMin.
Referenced by G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4ClippablePolygon::ClipAlongOneAxis(), G4VSolid::ClipPolygon(), G4DrawVoxels::ComputeVoxelPolyhedra(), and G4SmartVoxelHeader::RefineNodes().
G4bool G4VoxelLimits::ClipToLimits (G4ThreeVector & pStart, G4ThreeVector & pEnd) const
Definition at line 88 of file G4VoxelLimits.cc.
View newest version in sPHENIX GitHub at line 88 of file G4VoxelLimits.cc
References fxAxisMax, fxAxisMin, fyAxisMax, fyAxisMin, fzAxisMax, fzAxisMin, OutCode(), true, CLHEP::Hep3Vector::x(), x1, x2, CLHEP::Hep3Vector::y(), y1, y2, CLHEP::Hep3Vector::z(), z1, and z2.
Referenced by G4VSolid::ClipPolygonToSimpleLimits(), and G4ClippablePolygon::ClipToSimpleLimits().
G4double G4VoxelLimits::GetMaxExtent (const EAxis pAxis) const
Referenced by G4SmartVoxelHeader::BuildNodes(), G4GenericPolycone::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4Torus::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4TessellatedSolid::CalculateExtent(), G4ClippablePolygon::ClipAlongOneAxis(), and G4SolidExtentList::G4SolidExtentList().
G4double G4VoxelLimits::GetMaxXExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
G4double G4VoxelLimits::GetMaxYExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
G4double G4VoxelLimits::GetMaxZExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
G4double G4VoxelLimits::GetMinExtent (const EAxis pAxis) const
Referenced by G4SmartVoxelHeader::BuildNodes(), G4GenericPolycone::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4Torus::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4TessellatedSolid::CalculateExtent(), G4ClippablePolygon::ClipAlongOneAxis(), and G4SolidExtentList::G4SolidExtentList().
G4double G4VoxelLimits::GetMinXExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
G4double G4VoxelLimits::GetMinYExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
G4double G4VoxelLimits::GetMinZExtent () const
Referenced by G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ReflectedSolid::CalculateExtent(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4VSolid::ClipPolygon(), G4BoundingEnvelope::ClipVoxelByPlanes(), and operator<<().
G4bool G4VoxelLimits::Inside (const G4ThreeVector & pVec) const
Referenced by G4VSolid::ClipPolygonToSimpleLimits(), and G4ClippablePolygon::ClipToSimpleLimits().
G4bool G4VoxelLimits::IsLimited () const
Referenced by G4SmartVoxelHeader::BuildNodes(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4BoundingEnvelope::CalculateExtent(), G4ClippablePolygon::Clip(), G4ClippablePolygon::ClipAlongOneAxis(), G4VSolid::ClipPolygon(), G4SolidExtentList::G4SolidExtentList(), and G4ClippablePolygon::PartialClip().
G4bool G4VoxelLimits::IsLimited (const EAxis pAxis) const
G4bool G4VoxelLimits::IsXLimited () const
Referenced by G4VSolid::ClipPolygon(), operator<<(), OutCode(), and G4SmartVoxelHeader::RefineNodes().
G4bool G4VoxelLimits::IsYLimited () const
Referenced by G4VSolid::ClipPolygon(), operator<<(), OutCode(), and G4SmartVoxelHeader::RefineNodes().
G4bool G4VoxelLimits::IsZLimited () const
Referenced by G4VSolid::ClipPolygon(), operator<<(), OutCode(), and G4SmartVoxelHeader::RefineNodes().
G4int G4VoxelLimits::OutCode (const G4ThreeVector & pVec) const
Definition at line 233 of file G4VoxelLimits.cc.
View newest version in sPHENIX GitHub at line 233 of file G4VoxelLimits.cc
References fxAxisMax, fxAxisMin, fyAxisMax, fyAxisMin, fzAxisMax, fzAxisMin, IsXLimited(), IsYLimited(), IsZLimited(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ClipToLimits().
Member Data Documentation
G4double G4VoxelLimits::fxAxisMax = kInfinity private
Definition at line 118 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VoxelLimits.hh
Referenced by AddLimit(), ClipToLimits(), and OutCode().
G4double G4VoxelLimits::fxAxisMin = -kInfinity private
Definition at line 118 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VoxelLimits.hh
Referenced by AddLimit(), ClipToLimits(), and OutCode().
G4double G4VoxelLimits::fyAxisMax = kInfinity private
Definition at line 119 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VoxelLimits.hh
Referenced by AddLimit(), ClipToLimits(), and OutCode().
G4double G4VoxelLimits::fyAxisMin = -kInfinity private
Definition at line 119 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VoxelLimits.hh
Referenced by AddLimit(), ClipToLimits(), and OutCode().
G4double G4VoxelLimits::fzAxisMax = kInfinity private
Definition at line 120 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VoxelLimits.hh
Referenced by AddLimit(), ClipToLimits(), and OutCode().
G4double G4VoxelLimits::fzAxisMin = -kInfinity private
Definition at line 120 of file G4VoxelLimits.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VoxelLimits.hh
Referenced by AddLimit(), ClipToLimits(), and OutCode().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VoxelLimits.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4VoxelLimits.cc