ECCE @ EIC Software: G4IsotopeMagneticMomentTable Class Reference
G4IsotopeMagneticMomentTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/utils/include/G4IsotopeMagneticMomentTable.hh>
Public Types
typedef std::vector
< G4IsotopeProperty * > G4IsotopeList
typedef std::vector< G4String > G4IsotopeNameList
Public Member Functions
G4IsotopeMagneticMomentTable ()
virtual ~G4IsotopeMagneticMomentTable ()
virtual G4bool FindIsotope (G4IsotopeProperty *property)
virtual G4IsotopeProperty * GetIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float)
virtual G4IsotopeProperty * GetIsotopeByIsoLvl (G4int Z, G4int A, G4int lvl=0)
Public Member Functions inherited from G4VIsotopeTable
G4VIsotopeTable ()
G4VIsotopeTable (const G4String &)
G4VIsotopeTable (const G4VIsotopeTable &)
G4VIsotopeTable & operator= (const G4VIsotopeTable &)
virtual ~G4VIsotopeTable ()
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void DumpTable (G4int Zmin=1, G4int Zmax=118)
const G4String & GetName () const
Protected Member Functions
G4IsotopeMagneticMomentTable (const G4IsotopeMagneticMomentTable &right)
G4IsotopeMagneticMomentTable & operator= (const G4IsotopeMagneticMomentTable &right)
Private Member Functions
G4int GetVerboseLevel () const
Private Attributes
G4IsotopeList fIsotopeList
Static Private Attributes
static const G4double levelTolerance = 2.0*keV
static const G4double nuclearMagneton = eplus*hbar_Planck/2./(proton_mass_c2 /c_squared)
Detailed Description
Definition at line 53 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 53 of file G4IsotopeMagneticMomentTable.hh
Member Typedef Documentation
typedef std::vector<G4IsotopeProperty*> G4IsotopeMagneticMomentTable::G4IsotopeList
Definition at line 62 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 62 of file G4IsotopeMagneticMomentTable.hh
typedef std::vector<G4String> G4IsotopeMagneticMomentTable::G4IsotopeNameList
Definition at line 63 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 63 of file G4IsotopeMagneticMomentTable.hh
Constructor & Destructor Documentation
G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable ()
Definition at line 56 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 56 of file G4IsotopeMagneticMomentTable.cc
References file, fIsotopeList, G4cout, G4endl, G4Exception(), GetVerboseLevel(), JustWarning, MeV, nuclearMagneton, G4IsotopeProperty::SetAtomicMass(), G4IsotopeProperty::SetAtomicNumber(), G4IsotopeProperty::SetEnergy(), G4IsotopeProperty::SetIsomerLevel(), G4IsotopeProperty::SetiSpin(), and G4IsotopeProperty::SetMagneticMoment().
G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable (const G4IsotopeMagneticMomentTable & right) protected
Definition at line 142 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 142 of file G4IsotopeMagneticMomentTable.cc
G4IsotopeMagneticMomentTable::~G4IsotopeMagneticMomentTable () virtual
Definition at line 133 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 133 of file G4IsotopeMagneticMomentTable.cc
References fIsotopeList.
Member Function Documentation
G4bool G4IsotopeMagneticMomentTable::FindIsotope (G4IsotopeProperty * property) virtual
Definition at line 155 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 155 of file G4IsotopeMagneticMomentTable.cc
References fIsotopeList, G4IsotopeProperty::GetAtomicMass(), G4IsotopeProperty::GetAtomicNumber(), G4IsotopeProperty::GetEnergy(), G4IsotopeProperty::GetIsomerLevel(), and levelTolerance.
G4IsotopeProperty * G4IsotopeMagneticMomentTable::GetIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) virtual
Implements G4VIsotopeTable.
Definition at line 194 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 194 of file G4IsotopeMagneticMomentTable.cc
References A(), E, fIsotopeList, G4IsotopeProperty::GetAtomicMass(), G4IsotopeProperty::GetAtomicNumber(), G4IsotopeProperty::GetEnergy(), levelTolerance, and Z.
G4IsotopeProperty * G4IsotopeMagneticMomentTable::GetIsotopeByIsoLvl (G4int Z, G4int A, G4int lvl = 0) virtual
Reimplemented from G4VIsotopeTable.
Definition at line 233 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 233 of file G4IsotopeMagneticMomentTable.cc
References A(), fIsotopeList, G4IsotopeProperty::GetAtomicMass(), G4IsotopeProperty::GetAtomicNumber(), G4IsotopeProperty::GetIsomerLevel(), and Z.
G4int G4IsotopeMagneticMomentTable::GetVerboseLevel () const inline private
Definition at line 116 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 116 of file G4IsotopeMagneticMomentTable.hh
References G4ParticleTable::GetParticleTable(), and G4ParticleTable::GetVerboseLevel().
Referenced by G4IsotopeMagneticMomentTable().
G4IsotopeMagneticMomentTable & G4IsotopeMagneticMomentTable::operator= (const G4IsotopeMagneticMomentTable & right) protected
Definition at line 149 of file G4IsotopeMagneticMomentTable.cc.
View newest version in sPHENIX GitHub at line 149 of file G4IsotopeMagneticMomentTable.cc
Member Data Documentation
G4IsotopeList G4IsotopeMagneticMomentTable::fIsotopeList private
Definition at line 108 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 108 of file G4IsotopeMagneticMomentTable.hh
Referenced by FindIsotope(), G4IsotopeMagneticMomentTable(), GetIsotope(), GetIsotopeByIsoLvl(), and ~G4IsotopeMagneticMomentTable().
const G4double G4IsotopeMagneticMomentTable::levelTolerance = 2.0*keV static private
Definition at line 110 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 110 of file G4IsotopeMagneticMomentTable.hh
Referenced by FindIsotope(), and GetIsotope().
const G4double G4IsotopeMagneticMomentTable::nuclearMagneton = eplus*hbar_Planck/2./(proton_mass_c2 /c_squared) static private
Definition at line 111 of file G4IsotopeMagneticMomentTable.hh.
View newest version in sPHENIX GitHub at line 111 of file G4IsotopeMagneticMomentTable.hh
Referenced by G4IsotopeMagneticMomentTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/utils/include/G4IsotopeMagneticMomentTable.hh
geant4/tree/geant4-10.6-release/source/particles/utils/src/G4IsotopeMagneticMomentTable.cc