ECCE @ EIC Software: G4H1ToolsManager Class Reference
G4H1ToolsManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4H1ToolsManager.hh>
Public Member Functions
G4H1ToolsManager (const G4AnalysisManagerState &state)
virtual ~G4H1ToolsManager ()
G4int AddH1 (const G4String &name, tools::histo::h1d *h1d)
void AddH1Vector (const std::vector< tools::histo::h1d * > &h1Vector)
tools::histo::h1d * GetH1 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::h1d * >
::iterator BeginH1 ()
std::vector< tools::histo::h1d * >
::iterator EndH1 ()
std::vector< tools::histo::h1d * >
::const_iterator BeginConstH1 () const
std::vector< tools::histo::h1d * >
::const_iterator EndConstH1 () const
const std::vector
< tools::histo::h1d * > & GetH1Vector () const
const std::vector
< G4HnInformation * > & GetHnVector () const
Public Member Functions inherited from G4VH1Manager
G4VH1Manager ()
virtual ~G4VH1Manager ()
G4VH1Manager (const G4VH1Manager &rhs)=delete
G4VH1Manager & operator= (const G4VH1Manager &rhs)=delete
Public Member Functions inherited from G4THnManager< tools::histo::h1d >
G4THnManager (const G4AnalysisManagerState &state, const G4String &hnType)
virtual ~G4THnManager ()
G4bool Reset ()
G4bool IsEmpty () const
Protected Member Functions
virtual G4int CreateH1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binScheme="linear") final
virtual G4int CreateH1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none") final
virtual G4bool SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear") final
virtual G4bool SetH1 (G4int id, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none") final
virtual G4bool ScaleH1 (G4int id, G4double factor) final
virtual G4bool FillH1 (G4int id, G4double value, G4double weight=1.0) final
virtual G4int GetH1Id (const G4String &name, G4bool warn=true) const final
virtual G4int GetH1Nbins (G4int id) const final
virtual G4double GetH1Xmin (G4int id) const final
virtual G4double GetH1Xmax (G4int id) const final
virtual G4double GetH1Width (G4int id) const final
virtual G4bool SetH1Title (G4int id, const G4String &title) final
virtual G4bool SetH1XAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetH1YAxisTitle (G4int id, const G4String &title) final
virtual G4String GetH1Title (G4int id) const final
virtual G4String GetH1XAxisTitle (G4int id) const final
virtual G4String GetH1YAxisTitle (G4int id) const final
virtual G4bool WriteOnAscii (std::ofstream &output) final
virtual std::shared_ptr
< G4HnManager > GetHnManager () final
Protected Member Functions inherited from G4THnManager< tools::histo::h1d >
void AddTVector (const std::vector< tools::histo::h1d * > &tVector)
std::vector< tools::histo::h1d * >
::iterator BeginT ()
std::vector< tools::histo::h1d * >
::iterator EndT ()
std::vector< tools::histo::h1d * >
::const_iterator BeginConstT () const
std::vector< tools::histo::h1d * >
::const_iterator EndConstT () const
tools::histo::h1d * GetTInFunction (G4int id, G4String functionName, G4bool warn=true, G4bool onlyIfActive=true) const
G4int RegisterT (tools::histo::h1d *t, const G4String &name)
G4int GetTId (const G4String &name, G4bool warn=true) const
Private Member Functions
void AddH1Information (const G4String &name, const G4String &unitName, const G4String &fcnName, G4BinScheme binScheme) const
Static Private Attributes
static const G4int kDimension = 1
Additional Inherited Members
Protected Attributes inherited from G4THnManager< tools::histo::h1d >
const G4AnalysisManagerState & fState
std::vector< tools::histo::h1d * > fTVector
std::map< G4String, G4int > fNameIdMap
std::shared_ptr< G4HnManager > fHnManager
Detailed Description
Definition at line 51 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4H1ToolsManager.hh
Constructor & Destructor Documentation
G4H1ToolsManager::G4H1ToolsManager (const G4AnalysisManagerState & state) explicit
Definition at line 48 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 48 of file G4H1ToolsManager.cc
G4H1ToolsManager::~G4H1ToolsManager () virtual
Definition at line 54 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4H1ToolsManager.cc
Member Function Documentation
G4int G4H1ToolsManager::AddH1 (const G4String & name, tools::histo::h1d * h1d)
Definition at line 492 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 492 of file G4H1ToolsManager.cc
References AddH1Information(), G4THnManager< tools::histo::h1d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h1d >::RegisterT().
Referenced by G4CsvAnalysisReader::ReadH1Impl(), G4XmlAnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH1Impl(), and G4Hdf5AnalysisReader::ReadH1Impl().
void G4H1ToolsManager::AddH1Information (const G4String & name, const G4String & unitName, const G4String & fcnName, G4BinScheme binScheme) const private
Definition at line 185 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 185 of file G4H1ToolsManager.cc
References G4HnInformation::AddDimension(), G4THnManager< tools::histo::h1d >::fHnManager, and kDimension.
Referenced by AddH1(), and CreateH1().
void G4H1ToolsManager::AddH1Vector (const std::vector< tools::histo::h1d * > & h1Vector)
Definition at line 516 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 516 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::AddTVector().
Referenced by G4XmlAnalysisManager::WriteH1(), G4CsvAnalysisManager::WriteH1(), G4Hdf5AnalysisManager::WriteH1(), and G4RootAnalysisManager::WriteH1().
std::vector< tools::histo::h1d * >::const_iterator G4H1ToolsManager::BeginConstH1 () const inline
Definition at line 160 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 160 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::BeginConstT().
std::vector< tools::histo::h1d * >::iterator G4H1ToolsManager::BeginH1 () inline
Definition at line 153 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::BeginT().
G4int G4H1ToolsManager::CreateH1 (const G4String & name, const G4String & title, G4int nbins, G4double xmin, G4double xmax, const G4String & unitName = "none", const G4String & fcnName = "none", const G4String & binScheme = "linear") final protected virtual
Implements G4VH1Manager.
Definition at line 199 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 199 of file G4H1ToolsManager.cc
References AddH1Information(), G4THnManager< tools::histo::h1d >::fState, G4Analysis::GetBinScheme(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h1d >::RegisterT().
G4int G4H1ToolsManager::CreateH1 (const G4String & name, const G4String & title, const std::vector< G4double > & edges, const G4String & unitName = "none", const G4String & fcnName = "none") final protected virtual
Implements G4VH1Manager.
Definition at line 231 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 231 of file G4H1ToolsManager.cc
References AddH1Information(), G4THnManager< tools::histo::h1d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h1d >::RegisterT().
std::vector< tools::histo::h1d * >::const_iterator G4H1ToolsManager::EndConstH1 () const inline
Definition at line 164 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 164 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::EndConstT().
std::vector< tools::histo::h1d * >::iterator G4H1ToolsManager::EndH1 () inline
Definition at line 156 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 156 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::EndT().
G4bool G4H1ToolsManager::FillH1 (G4int id, G4double value, G4double weight = 1.0) final protected virtual
Implements G4VH1Manager.
Definition at line 330 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 330 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4THnManager< tools::histo::h1d >::fState, G4AnalysisManagerState::GetIsActivation(), G4THnManager< tools::histo::h1d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kX, G4AnalysisVerbose::Message(), and weight.
tools::histo::h1d * G4H1ToolsManager::GetH1 (G4int id, G4bool warn = true, G4bool onlyIfActive = true) const
Definition at line 523 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 523 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTInFunction().
G4int G4H1ToolsManager::GetH1Id (const G4String & name, G4bool warn = true) const final protected virtual
Implements G4VH1Manager.
Definition at line 356 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 356 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTId().
G4int G4H1ToolsManager::GetH1Nbins (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 362 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 362 of file G4H1ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::h1d >::GetTInFunction(), and G4Analysis::kX.
G4String G4H1ToolsManager::GetH1Title (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 427 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 427 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTInFunction(), and G4Analysis::GetTitle().
const std::vector< tools::histo::h1d * > & G4H1ToolsManager::GetH1Vector () const inline
Definition at line 167 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 167 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::fTVector.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisManager::WriteH1(), G4CsvAnalysisManager::WriteH1(), G4Hdf5AnalysisManager::WriteH1(), and G4RootAnalysisManager::WriteH1().
G4double G4H1ToolsManager::GetH1Width (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 391 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 391 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4THnManager< tools::histo::h1d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kX.
G4String G4H1ToolsManager::GetH1XAxisTitle (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 437 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 437 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h1d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H1ToolsManager::GetH1Xmax (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 382 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 382 of file G4H1ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::h1d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H1ToolsManager::GetH1Xmin (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 371 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 371 of file G4H1ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::h1d >::GetTInFunction(), and G4Analysis::kX.
G4String G4H1ToolsManager::GetH1YAxisTitle (G4int id) const final protected virtual
Implements G4VH1Manager.
Definition at line 446 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 446 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h1d >::GetTInFunction(), and G4Analysis::kY.
std::shared_ptr< G4HnManager > G4H1ToolsManager::GetHnManager () inline final protected virtual
Implements G4VH1Manager.
Definition at line 173 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 173 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::fHnManager.
const std::vector< G4HnInformation * > & G4H1ToolsManager::GetHnVector () const inline
Definition at line 170 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 170 of file G4H1ToolsManager.hh
References G4THnManager< tools::histo::h1d >::fHnManager.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisManager::WriteH1(), G4CsvAnalysisManager::WriteH1(), G4Hdf5AnalysisManager::WriteH1(), and G4RootAnalysisManager::WriteH1().
G4bool G4H1ToolsManager::ScaleH1 (G4int id, G4double factor) final protected virtual
Implements G4VH1Manager.
Definition at line 321 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 321 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTInFunction().
G4bool G4H1ToolsManager::SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String & unitName = "none", const G4String & fcnName = "none", const G4String & binSchemeName = "linear") final protected virtual
Implements G4VH1Manager.
Definition at line 259 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 259 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4THnManager< tools::histo::h1d >::fState, G4Analysis::GetBinScheme(), G4THnManager< tools::histo::h1d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4H1ToolsManager::SetH1 (G4int id, const std::vector< G4double > & edges, const G4String & unitName = "none", const G4String & fcnName = "none") final protected virtual
Implements G4VH1Manager.
Definition at line 290 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 290 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4THnManager< tools::histo::h1d >::fState, G4THnManager< tools::histo::h1d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4H1ToolsManager::SetH1Title (G4int id, const G4String & title) final protected virtual
Implements G4VH1Manager.
Definition at line 400 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 400 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTInFunction(), and SetTitle().
G4bool G4H1ToolsManager::SetH1XAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH1Manager.
Definition at line 409 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 409 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTInFunction(), G4Analysis::kX, and G4Analysis::SetAxisTitle().
G4bool G4H1ToolsManager::SetH1YAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH1Manager.
Definition at line 418 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 418 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::GetTInFunction(), G4Analysis::kY, and G4Analysis::SetAxisTitle().
G4bool G4H1ToolsManager::WriteOnAscii (std::ofstream & output) final protected virtual
Implements G4VH1Manager.
Definition at line 455 of file G4H1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 455 of file G4H1ToolsManager.cc
References G4THnManager< tools::histo::h1d >::fHnManager, G4THnManager< tools::histo::h1d >::fState, G4THnManager< tools::histo::h1d >::fTVector, G4endl, G4AnalysisManagerState::GetVerboseL3(), h1, and G4AnalysisVerbose::Message().
Member Data Documentation
const G4int G4H1ToolsManager::kDimension = 1 static private
Definition at line 148 of file G4H1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 148 of file G4H1ToolsManager.hh
Referenced by AddH1Information().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4H1ToolsManager.hh
geant4/tree/geant4-10.6-release/source/analysis/hntools/src/G4H1ToolsManager.cc