ECCE @ EIC Software: G4AnyMethod::FuncRef< S, T > Struct Template Reference
G4AnyMethod::FuncRef< S, T > Struct Template Reference
Public Member Functions
FuncRef (S(T::*f)())
virtual void operator() (void *obj)
virtual void operator() (void *, const std::string &)
virtual Placeholder * Clone () const
virtual const std::type_info & ArgType (size_t) const
Public Member Functions inherited from G4AnyMethod::Placeholder
Placeholder ()
virtual ~Placeholder ()
Public Attributes
S(T::* fRef)()
Detailed Description
template<class S, class T>
struct G4AnyMethod::FuncRef< S, T >
Definition at line 157 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 157 of file G4AnyMethod.hh
Constructor & Destructor Documentation
template<class S , class T > G4AnyMethod::FuncRef< S, T >::FuncRef (S(T::*)() f) inline
Definition at line 158 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 158 of file G4AnyMethod.hh
Referenced by G4AnyMethod::FuncRef< S, T >::Clone().
Member Function Documentation
template<class S , class T > virtual const std::type_info& G4AnyMethod::FuncRef< S, T >::ArgType (size_t) const inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 169 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 169 of file G4AnyMethod.hh
References void().
template<class S , class T > virtual Placeholder* G4AnyMethod::FuncRef< S, T >::Clone () const inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 166 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 166 of file G4AnyMethod.hh
References G4AnyMethod::FuncRef< S, T >::fRef, and G4AnyMethod::FuncRef< S, T >::FuncRef().
template<class S , class T > virtual void G4AnyMethod::FuncRef< S, T >::operator() (void * obj) inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 160 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 160 of file G4AnyMethod.hh
References G4AnyMethod::FuncRef< S, T >::fRef, and T.
template<class S , class T > virtual void G4AnyMethod::FuncRef< S, T >::operator() (void * , const std::string &) inline virtual
Implements G4AnyMethod::Placeholder.
Definition at line 163 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 163 of file G4AnyMethod.hh
Member Data Documentation
template<class S , class T > S(T::* G4AnyMethod::FuncRef< S, T >::fRef)()
Definition at line 172 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 172 of file G4AnyMethod.hh
Referenced by G4AnyMethod::FuncRef< S, T >::Clone(), and G4AnyMethod::FuncRef< S, T >::operator()().
The documentation for this struct was generated from the following file:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyMethod.hh