ECCE @ EIC Software: G4PolarizedMollerCrossSection Class Reference
G4PolarizedMollerCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedMollerCrossSection.hh>
Public Member Functions
G4PolarizedMollerCrossSection ()
virtual ~G4PolarizedMollerCrossSection ()
void Initialize (G4double x, G4double y, G4double phi, const G4StokesVector &p0, const G4StokesVector &p1, G4int flag=0) override
G4double XSection (const G4StokesVector &pol2, const G4StokesVector &pol3) override
G4double TotalXSection (G4double xmin, G4double xmax, G4double y, const G4StokesVector &pol0, const G4StokesVector &pol1) override
G4StokesVector GetPol2 () override
G4StokesVector GetPol3 () override
Public Member Functions inherited from G4VPolarizedCrossSection
G4VPolarizedCrossSection ()
virtual ~G4VPolarizedCrossSection ()
G4double GetYmin ()
virtual G4double GetXmin (G4double y)
virtual G4double GetXmax (G4double y)
void SetMaterial (G4double A, G4double Z, G4double coul)
Private Attributes
G4double phi0
G4ThreeVector phi2
G4ThreeVector phi3
Additional Inherited Members
Protected Member Functions inherited from G4VPolarizedCrossSection
void SetXmin (G4double xmin)
void SetXmax (G4double xmax)
void SetYmin (G4double ymin)
Protected Attributes inherited from G4VPolarizedCrossSection
G4double fXmin
G4double fXmax
G4double fYmin
G4double theA
G4double theZ
G4double fCoul
Detailed Description
Definition at line 52 of file G4PolarizedMollerCrossSection.hh.
View newest version in sPHENIX GitHub at line 52 of file G4PolarizedMollerCrossSection.hh
Constructor & Destructor Documentation
G4PolarizedMollerCrossSection::G4PolarizedMollerCrossSection ()
Definition at line 51 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 51 of file G4PolarizedMollerCrossSection.cc
References G4VPolarizedCrossSection::SetXmax().
G4PolarizedMollerCrossSection::~G4PolarizedMollerCrossSection () virtual
Definition at line 56 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PolarizedMollerCrossSection.cc
Member Function Documentation
G4StokesVector G4PolarizedMollerCrossSection::GetPol2 () override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 263 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 263 of file G4PolarizedMollerCrossSection.cc
References phi0, and phi2.
G4StokesVector G4PolarizedMollerCrossSection::GetPol3 () override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 269 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 269 of file G4PolarizedMollerCrossSection.cc
References phi0, and phi3.
void G4PolarizedMollerCrossSection::Initialize (G4double x, G4double y, G4double phi, const G4StokesVector & p0, const G4StokesVector & p1, G4int flag = 0) override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 57 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PolarizedMollerCrossSection.cc
References source.hepunit::classic_electr_radius, e, e2, f, f2, G4StokesVector::IsZero(), phi0, phi2, phi3, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and zz.
G4double G4PolarizedMollerCrossSection::TotalXSection (G4double xmin, G4double xmax, G4double y, const G4StokesVector & pol0, const G4StokesVector & pol1) override virtual
Reimplemented from G4VPolarizedCrossSection.
Definition at line 227 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 227 of file G4PolarizedMollerCrossSection.cc
References source.hepunit::classic_electr_radius, G4cout, G4endl, twopi, CLHEP::Hep3Vector::x(), x, xmin, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4PolarizedMollerCrossSection::XSection (const G4StokesVector & pol2, const G4StokesVector & pol3) override virtual
Implements G4VPolarizedCrossSection.
Definition at line 214 of file G4PolarizedMollerCrossSection.cc.
View newest version in sPHENIX GitHub at line 214 of file G4PolarizedMollerCrossSection.cc
References G4StokesVector::IsZero(), phi0, phi2, and phi3.
Member Data Documentation
G4double G4PolarizedMollerCrossSection::phi0 private
Definition at line 69 of file G4PolarizedMollerCrossSection.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PolarizedMollerCrossSection.hh
Referenced by GetPol2(), GetPol3(), Initialize(), and XSection().
G4ThreeVector G4PolarizedMollerCrossSection::phi2 private
Definition at line 71 of file G4PolarizedMollerCrossSection.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PolarizedMollerCrossSection.hh
Referenced by GetPol2(), Initialize(), and XSection().
G4ThreeVector G4PolarizedMollerCrossSection::phi3 private
Definition at line 73 of file G4PolarizedMollerCrossSection.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PolarizedMollerCrossSection.hh
Referenced by GetPol3(), Initialize(), and XSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedMollerCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedMollerCrossSection.cc