ECCE @ EIC Software: ExN04CalorimeterParametrisation Class Reference
ExN04CalorimeterParametrisation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04CalorimeterParametrisation.hh>
Public Member Functions
ExN04CalorimeterParametrisation ()
virtual ~ExN04CalorimeterParametrisation ()
virtual void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
virtual void ComputeDimensions (G4Tubs &calorimeterLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
ExN04CalorimeterParametrisation ()
virtual ~ExN04CalorimeterParametrisation ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Tubs &calorimeterLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4double fexpHall_x
G4double fexpHall_y
G4double fexpHall_z
G4double ftrkTubs_rmax
G4double ftrkTubs_rmin
G4double ftrkTubs_dz
G4double ftrkTubs_sphi
G4double ftrkTubs_dphi
G4int fnotrkLayers
G4double ftracker_radius [5]
G4double ftracker_thick
G4double ftracker_length [5]
G4double fcaloTubs_rmax
G4double fcaloTubs_rmin
G4double fcaloTubs_dz
G4double fcaloTubs_sphi
G4double fcaloTubs_dphi
G4int fnocaloLayers
G4double fabsorber_thick
G4double fscinti_thick
G4int fsegmentsinZ
G4double fcaloRing_rmax
G4double fcaloRing_rmin
G4double fcaloRing_dz
G4double fcaloRing_sphi
G4double fcaloRing_dphi
G4int fsegmentsinPhi
G4double fcaloCell_rmax
G4double fcaloCell_rmin
G4double fcaloCell_dz
G4double fcaloCell_sphi
G4double fcaloCell_dphi
G4int fnomucounter
G4double fmuBox_radius
G4double fmuBox_width
G4double fmuBox_thick
G4double fmuBox_length
G4double expHall_x
G4double expHall_y
G4double expHall_z
G4double trkTubs_rmax
G4double trkTubs_rmin
G4double trkTubs_dz
G4double trkTubs_sphi
G4double trkTubs_dphi
G4int notrkLayers
G4double tracker_radius [5]
G4double tracker_thick
G4double tracker_length [5]
G4double caloTubs_rmax
G4double caloTubs_rmin
G4double caloTubs_dz
G4double caloTubs_sphi
G4double caloTubs_dphi
G4int nocaloLayers
G4double absorber_thick
G4double scinti_thick
G4int segmentsinZ
G4double caloRing_rmax
G4double caloRing_rmin
G4double caloRing_dz
G4double caloRing_sphi
G4double caloRing_dphi
G4int segmentsinPhi
G4double caloCell_rmax
G4double caloCell_rmin
G4double caloCell_dz
G4double caloCell_sphi
G4double caloCell_dphi
G4int nomucounter
G4double muBox_radius
G4double muBox_width
G4double muBox_thick
G4double muBox_length
Detailed Description
Definition at line 54 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04CalorimeterParametrisation.hh
Constructor & Destructor Documentation
ExN04CalorimeterParametrisation::ExN04CalorimeterParametrisation ()
ExN04CalorimeterParametrisation::~ExN04CalorimeterParametrisation () virtual
Definition at line 45 of file ExN04CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 45 of file ExN04CalorimeterParametrisation.cc
ExN04CalorimeterParametrisation::ExN04CalorimeterParametrisation ()
virtual ExN04CalorimeterParametrisation::~ExN04CalorimeterParametrisation () virtual
Member Function Documentation
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Tubs & calorimeterLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 59 of file ExN04CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 59 of file ExN04CalorimeterParametrisation.cc
References fabsorber_thick, fcaloTubs_dphi, fcaloTubs_dz, fcaloTubs_rmin, fcaloTubs_sphi, fscinti_thick, G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Tubs & calorimeterLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 65 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 67 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 68 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 68 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 69 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 70 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 70 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 69 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 71 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 72 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 72 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 71 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 73 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 73 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 74 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 74 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 73 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 73 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 75 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 75 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 76 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 77 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 77 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 78 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 78 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 77 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 77 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 79 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 79 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 79 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 79 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 81 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 81 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 83 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 83 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 85 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 85 of file ExN04CalorimeterParametrisation.hh
virtual void ExN04CalorimeterParametrisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 87 of file ExN04CalorimeterParametrisation.hh
void ExN04CalorimeterParametrisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 51 of file ExN04CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 51 of file ExN04CalorimeterParametrisation.cc
References Acts::Test::origin().
void ExN04CalorimeterParametrisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Member Data Documentation
G4double ExN04CalorimeterParametrisation::absorber_thick private
Definition at line 54 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloCell_dphi private
Definition at line 69 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloCell_dz private
Definition at line 67 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloCell_rmax private
Definition at line 65 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloCell_rmin private
Definition at line 66 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 66 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloCell_sphi private
Definition at line 68 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 68 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloRing_dphi private
Definition at line 62 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 62 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloRing_dz private
Definition at line 60 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 60 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloRing_rmax private
Definition at line 58 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 58 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloRing_rmin private
Definition at line 59 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 59 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloRing_sphi private
Definition at line 61 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 61 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloTubs_dphi private
Definition at line 51 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 51 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloTubs_dz private
Definition at line 49 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 49 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloTubs_rmax private
Definition at line 47 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 47 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloTubs_rmin private
Definition at line 48 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::caloTubs_sphi private
Definition at line 50 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 50 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::expHall_x private
Definition at line 32 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 32 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::expHall_y private
Definition at line 33 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 33 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::expHall_z private
Definition at line 34 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 34 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fabsorber_thick private
Definition at line 54 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloCell_dphi private
Definition at line 69 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloCell_dz private
Definition at line 67 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloCell_rmax private
Definition at line 65 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloCell_rmin private
Definition at line 66 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 66 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloCell_sphi private
Definition at line 68 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 68 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloRing_dphi private
Definition at line 62 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 62 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloRing_dz private
Definition at line 60 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 60 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloRing_rmax private
Definition at line 58 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 58 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloRing_rmin private
Definition at line 59 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 59 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloRing_sphi private
Definition at line 61 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 61 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloTubs_dphi private
Definition at line 51 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 51 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloTubs_dz private
Definition at line 49 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 49 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloTubs_rmax private
Definition at line 47 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 47 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloTubs_rmin private
Definition at line 48 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fcaloTubs_sphi private
Definition at line 50 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 50 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fexpHall_x private
Definition at line 32 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 32 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fexpHall_y private
Definition at line 33 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 33 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fexpHall_z private
Definition at line 34 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 34 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fmuBox_length private
Definition at line 75 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fmuBox_radius private
Definition at line 72 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 72 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fmuBox_thick private
Definition at line 74 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 74 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fmuBox_width private
Definition at line 73 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 73 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::fnocaloLayers private
Definition at line 53 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 53 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::fnomucounter private
Definition at line 71 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::fnotrkLayers private
Definition at line 42 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 42 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::fscinti_thick private
Definition at line 55 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::fsegmentsinPhi private
Definition at line 64 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::fsegmentsinZ private
Definition at line 57 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftracker_length[5] private
Definition at line 45 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 45 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftracker_radius[5] private
Definition at line 43 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 43 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftracker_thick private
Definition at line 44 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 44 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftrkTubs_dphi private
Definition at line 40 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 40 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftrkTubs_dz private
Definition at line 38 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 38 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftrkTubs_rmax private
Definition at line 36 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 36 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftrkTubs_rmin private
Definition at line 37 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 37 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::ftrkTubs_sphi private
Definition at line 39 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 39 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::muBox_length private
Definition at line 75 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::muBox_radius private
Definition at line 72 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 72 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::muBox_thick private
Definition at line 74 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 74 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::muBox_width private
Definition at line 73 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 73 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::nocaloLayers private
Definition at line 53 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 53 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::nomucounter private
Definition at line 71 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::notrkLayers private
Definition at line 42 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 42 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::scinti_thick private
Definition at line 55 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::segmentsinPhi private
Definition at line 64 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN04CalorimeterParametrisation.hh
G4int ExN04CalorimeterParametrisation::segmentsinZ private
Definition at line 57 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::tracker_length[5] private
Definition at line 45 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 45 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::tracker_radius[5] private
Definition at line 43 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 43 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::tracker_thick private
Definition at line 44 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 44 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::trkTubs_dphi private
Definition at line 40 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 40 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::trkTubs_dz private
Definition at line 38 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 38 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::trkTubs_rmax private
Definition at line 36 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 36 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::trkTubs_rmin private
Definition at line 37 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 37 of file ExN04CalorimeterParametrisation.hh
G4double ExN04CalorimeterParametrisation::trkTubs_sphi private
Definition at line 39 of file ExN04CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 39 of file ExN04CalorimeterParametrisation.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04CalorimeterParametrisation.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04DetectorParameterDef.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04DetectorParameterDef.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04CalorimeterParametrisation.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04CalorimeterParametrisation.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04CalorimeterParametrisation.cc