ECCE @ EIC Software: B03ImportanceDetectorConstruction Class Reference
B03ImportanceDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/include/B03ImportanceDetectorConstruction.hh>
Public Member Functions
B03ImportanceDetectorConstruction (G4String worldName)
~B03ImportanceDetectorConstruction ()
const G4VPhysicalVolume & GetPhysicalVolumeByName (const G4String &name) const
G4VPhysicalVolume & GetWorldVolumeAddress () const
G4String ListPhysNamesAsG4String ()
G4String GetCellName (G4int i)
G4GeometryCell GetGeometryCell (G4int i)
G4VPhysicalVolume * GetWorldVolume ()
void SetSensitive ()
virtual void ConstructSD ()
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Member Functions
virtual void Construct ()
Private Attributes
B03PVolumeStore fPVolumeStore
std::vector< G4LogicalVolume * > fLogicalVolumeVector
G4VPhysicalVolume * fGhostWorld
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 46 of file B03ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 46 of file B03ImportanceDetectorConstruction.hh
Constructor & Destructor Documentation
B03ImportanceDetectorConstruction::B03ImportanceDetectorConstruction (G4String worldName)
Definition at line 57 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 57 of file B03ImportanceDetectorConstruction.cc
B03ImportanceDetectorConstruction::~B03ImportanceDetectorConstruction ()
Definition at line 65 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 65 of file B03ImportanceDetectorConstruction.cc
References fLogicalVolumeVector.
Member Function Documentation
void B03ImportanceDetectorConstruction::Construct (void) private virtual
Implements G4VUserParallelWorld.
Definition at line 72 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file B03ImportanceDetectorConstruction.cc
References B03PVolumeStore::AddPVolume(), cm, deg, fGhostWorld, fLogicalVolumeVector, fPVolumeStore, G4cout, G4endl, GetCellName(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4VUserParallelWorld::GetWorld(), and SetSensitive().
void B03ImportanceDetectorConstruction::ConstructSD () virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 261 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 261 of file B03ImportanceDetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4PSTrackLength::DivideByVelocity(), fCurrent_In, fLogicalVolumeVector, G4SDManager::GetSDMpointer(), it, G4PSTrackLength::MultiplyKineticEnergy(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VSensitiveDetector::SetFilter(), G4VUserParallelWorld::SetSensitiveDetector(), G4PSTrackLength::Weighted(), and G4PSNofCollision::Weighted().
G4String B03ImportanceDetectorConstruction::GetCellName (G4int i)
Definition at line 199 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 199 of file B03ImportanceDetectorConstruction.cc
Referenced by Construct(), B03RunAction::EndOfRunAction(), and GetGeometryCell().
G4GeometryCell B03ImportanceDetectorConstruction::GetGeometryCell (G4int i)
Definition at line 212 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 212 of file B03ImportanceDetectorConstruction.cc
References fGhostWorld, fPVolumeStore, G4cout, G4endl, GetCellName(), and B03PVolumeStore::GetPVolume().
Referenced by main().
const G4VPhysicalVolume & B03ImportanceDetectorConstruction::GetPhysicalVolumeByName (const G4String & name) const
Definition at line 186 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 186 of file B03ImportanceDetectorConstruction.cc
References fPVolumeStore, and B03PVolumeStore::GetPVolume().
G4VPhysicalVolume * B03ImportanceDetectorConstruction::GetWorldVolume ()
Definition at line 235 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 235 of file B03ImportanceDetectorConstruction.cc
References fGhostWorld.
G4VPhysicalVolume & B03ImportanceDetectorConstruction::GetWorldVolumeAddress () const
Definition at line 229 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 229 of file B03ImportanceDetectorConstruction.cc
References fGhostWorld.
Referenced by main().
G4String B03ImportanceDetectorConstruction::ListPhysNamesAsG4String ()
Definition at line 192 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 192 of file B03ImportanceDetectorConstruction.cc
References fPVolumeStore, and B03PVolumeStore::GetPNames().
void B03ImportanceDetectorConstruction::SetSensitive ()
Definition at line 241 of file B03ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 241 of file B03ImportanceDetectorConstruction.cc
Referenced by Construct().
Member Data Documentation
G4VPhysicalVolume* B03ImportanceDetectorConstruction::fGhostWorld private
Definition at line 73 of file B03ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file B03ImportanceDetectorConstruction.hh
Referenced by Construct(), GetGeometryCell(), GetWorldVolume(), and GetWorldVolumeAddress().
std::vector< G4LogicalVolume * > B03ImportanceDetectorConstruction::fLogicalVolumeVector private
Definition at line 69 of file B03ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file B03ImportanceDetectorConstruction.hh
Referenced by Construct(), ConstructSD(), and ~B03ImportanceDetectorConstruction().
B03PVolumeStore B03ImportanceDetectorConstruction::fPVolumeStore private
Definition at line 66 of file B03ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file B03ImportanceDetectorConstruction.hh
Referenced by Construct(), GetGeometryCell(), GetPhysicalVolumeByName(), and ListPhysNamesAsG4String().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/include/B03ImportanceDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/src/B03ImportanceDetectorConstruction.cc