ECCE @ EIC Software: G4WendtFissionFragmentGenerator Class Reference
G4WendtFissionFragmentGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4WendtFissionFragmentGenerator.hh>
Public Member Functions
G4HadFinalState * ApplyYourself (const G4HadProjectile &projectile, G4int Z, G4int A)
void InitializeANucleus (const G4int A, const G4int Z, const G4int M, const G4String &dataDirectory)
~G4WendtFissionFragmentGenerator ()
Static Public Member Functions
static
G4WendtFissionFragmentGenerator * GetInstance ()
Private Member Functions
G4WendtFissionFragmentGenerator ()
G4WendtFissionFragmentGenerator (G4WendtFissionFragmentGenerator const &)
void operator= (G4WendtFissionFragmentGenerator const &)
Private Attributes
std::map< const G4int,
G4FissionFragmentGenerator * > fissionIsotopes
G4ParticleHPNames fileNames
G4int Verbosity_
Static Private Attributes
static G4ThreadLocal
G4WendtFissionFragmentGenerator * instance = NULL
Detailed Description
Definition at line 42 of file G4WendtFissionFragmentGenerator.hh.
View newest version in sPHENIX GitHub at line 42 of file G4WendtFissionFragmentGenerator.hh
Constructor & Destructor Documentation
G4WendtFissionFragmentGenerator::~G4WendtFissionFragmentGenerator ()
Definition at line 190 of file G4WendtFissionFragmentGenerator.cc.
View newest version in sPHENIX GitHub at line 190 of file G4WendtFissionFragmentGenerator.cc
References fissionIsotopes.
G4WendtFissionFragmentGenerator::G4WendtFissionFragmentGenerator () private
Definition at line 41 of file G4WendtFissionFragmentGenerator.cc.
View newest version in sPHENIX GitHub at line 41 of file G4WendtFissionFragmentGenerator.cc
References G4FFGDefaultValues::Verbosity, and Verbosity_.
Referenced by GetInstance().
G4WendtFissionFragmentGenerator::G4WendtFissionFragmentGenerator (G4WendtFissionFragmentGenerator const &) private
Member Function Documentation
G4HadFinalState * G4WendtFissionFragmentGenerator::ApplyYourself (const G4HadProjectile & projectile, G4int Z, G4int A)
Definition at line 60 of file G4WendtFissionFragmentGenerator.cc.
View newest version in sPHENIX GitHub at line 60 of file G4WendtFissionFragmentGenerator.cc
References fissionIsotopes, G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, G4FissionFragmentGenerator::G4MakeIsotopeCode(), and stopAndKill.
Referenced by G4ParticleHPChannel::ApplyYourself().
static G4WendtFissionFragmentGenerator* G4WendtFissionFragmentGenerator::GetInstance (void) inline static
Definition at line 46 of file G4WendtFissionFragmentGenerator.hh.
View newest version in sPHENIX GitHub at line 46 of file G4WendtFissionFragmentGenerator.hh
References G4WendtFissionFragmentGenerator(), and instance.
void G4WendtFissionFragmentGenerator::InitializeANucleus (const G4int A, const G4int Z, const G4int M, const G4String & dataDirectory)
Definition at line 105 of file G4WendtFissionFragmentGenerator.cc.
View newest version in sPHENIX GitHub at line 105 of file G4WendtFissionFragmentGenerator.cc
References A(), kdfinder::abs(), fileNames, fissionIsotopes, G4FissionFragmentGenerator::G4MakeIsotopeCode(), G4FissionFragmentGenerator::G4SetCause(), G4FissionFragmentGenerator::G4SetIncidentEnergy(), G4FissionFragmentGenerator::G4SetIsotope(), G4FissionFragmentGenerator::G4SetMetaState(), G4FissionFragmentGenerator::G4SetSamplingScheme(), G4FissionFragmentGenerator::G4SetYieldType(), G4ParticleHPDataUsed::GetA(), G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPDataUsed::GetZ(), G4FFGEnumerations::GROUND_STATE, in, G4FFGEnumerations::INDEPENDENT, G4FissionFragmentGenerator::InitializeFissionProductYieldClass(), G4FFGEnumerations::META_1, G4FFGEnumerations::META_2, G4FFGEnumerations::NEUTRON_INDUCED, G4FFGEnumerations::NORMAL, G4FFGDefaultValues::ThermalNeutronEnergy, and Z.
Referenced by G4ParticleHPChannel::UpdateData().
void G4WendtFissionFragmentGenerator::operator= (G4WendtFissionFragmentGenerator const &) private
Member Data Documentation
G4ParticleHPNames G4WendtFissionFragmentGenerator::fileNames private
Definition at line 65 of file G4WendtFissionFragmentGenerator.hh.
View newest version in sPHENIX GitHub at line 65 of file G4WendtFissionFragmentGenerator.hh
Referenced by InitializeANucleus().
std::map< const G4int, G4FissionFragmentGenerator* > G4WendtFissionFragmentGenerator::fissionIsotopes private
A map of all the fission isotopes loaded at initialization
Definition at line 64 of file G4WendtFissionFragmentGenerator.hh.
View newest version in sPHENIX GitHub at line 64 of file G4WendtFissionFragmentGenerator.hh
Referenced by ApplyYourself(), InitializeANucleus(), and ~G4WendtFissionFragmentGenerator().
G4ThreadLocal G4WendtFissionFragmentGenerator * G4WendtFissionFragmentGenerator::instance = NULL static private
Definition at line 60 of file G4WendtFissionFragmentGenerator.hh.
View newest version in sPHENIX GitHub at line 60 of file G4WendtFissionFragmentGenerator.hh
Referenced by GetInstance().
G4int G4WendtFissionFragmentGenerator::Verbosity_ private
Definition at line 67 of file G4WendtFissionFragmentGenerator.hh.
View newest version in sPHENIX GitHub at line 67 of file G4WendtFissionFragmentGenerator.hh
Referenced by G4WendtFissionFragmentGenerator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4WendtFissionFragmentGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4WendtFissionFragmentGenerator.cc