ECCE @ EIC Software: G4ParticleHPContAngularPar Class Reference
G4ParticleHPContAngularPar Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPContAngularPar.hh>
Classes
struct toBeCached
Public Member Functions
G4ParticleHPContAngularPar ()
G4ParticleHPContAngularPar (G4ParticleDefinition *projectile)
~G4ParticleHPContAngularPar ()
void Init (std::istream &aDataFile, G4ParticleDefinition *projectile)
G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass, G4int angularRep, G4int interpol)
G4double GetEnergy ()
void SetPrimary (G4ReactionProduct *aPrimary)
void SetTarget (G4ReactionProduct *aTarget)
void SetTargetCode (G4double aTargetCode)
void SetInterpolation (G4int theInterpolation)
void BuildByInterpolation (G4double anEnergy, G4InterpolationScheme aScheme, G4ParticleHPContAngularPar &store1, G4ParticleHPContAngularPar &store2)
void PrepareTableInterpolation (const G4ParticleHPContAngularPar *angularPrev)
G4double MeanEnergyOfThisInteraction ()
G4int GetNEnergies () const
G4int GetNDiscreteEnergies () const
std::set< G4double > GetEnergiesTransformed () const
G4int GetNEnergiesTransformed () const
G4double GetMinEner () const
G4double GetMaxEner () const
std::map< G4double, G4int > GetDiscreteEnergiesOwn () const
G4ParticleHPList * GetAngDataList () const
void ClearHistories ()
void Dump ()
Private Member Functions
void cacheInit ()
Private Attributes
G4double theEnergy
G4int nEnergies
G4int nDiscreteEnergies
G4int nAngularParameters
G4InterpolationManager theManager
G4ParticleHPList * theAngular
G4ParticleHPInterpolator theInt
G4Cache< toBeCached * > fCache
G4ParticleDefinition * theProjectile
G4bool adjustResult
G4double theMinEner
G4double theMaxEner
std::set< G4double > theEnergiesTransformed
std::set< G4double > theDiscreteEnergies
std::map< G4double, G4int > theDiscreteEnergiesOwn
Detailed Description
Definition at line 48 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPContAngularPar.hh
Constructor & Destructor Documentation
G4ParticleHPContAngularPar::G4ParticleHPContAngularPar () inline
Definition at line 66 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPContAngularPar.hh
References adjustResult, DBL_MAX, fCache, nAngularParameters, nDiscreteEnergies, nEnergies, G4Cache< VALTYPE >::Put(), theAngular, theEnergy, theMaxEner, theMinEner, and theProjectile.
G4ParticleHPContAngularPar::G4ParticleHPContAngularPar (G4ParticleDefinition * projectile)
Definition at line 62 of file G4ParticleHPContAngularPar.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPContAngularPar.cc
References adjustResult, cacheInit(), DBL_MAX, fCache, G4Cache< VALTYPE >::Get(), nAngularParameters, nDiscreteEnergies, nEnergies, theAngular, theEnergy, theMaxEner, theMinEner, and theProjectile.
G4ParticleHPContAngularPar::~G4ParticleHPContAngularPar () inline
Definition at line 84 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPContAngularPar.hh
References fCache, G4Cache< VALTYPE >::Get(), and theAngular.
Member Function Documentation
void G4ParticleHPContAngularPar::BuildByInterpolation (G4double anEnergy, G4InterpolationScheme aScheme, G4ParticleHPContAngularPar & store1, G4ParticleHPContAngularPar & store2)
Definition at line 736 of file G4ParticleHPContAngularPar.cc.
View newest version in sPHENIX GitHub at line 736 of file G4ParticleHPContAngularPar.cc
References Dump(), E, e1, e2, Acts::eT, G4cout, G4endl, GetDiscreteEnergiesOwn(), GetEnergiesTransformed(), GetEnergy(), G4ParticleHPList::GetLabel(), GetMaxEner(), GetMinEner(), GetNDiscreteEnergies(), GetNEnergies(), GetNEnergiesTransformed(), G4InterpolationManager::GetScheme(), G4ParticleHPList::GetValue(), G4ParticleHPInterpolator::Interpolate(), G4ParticleHPInterpolator::Interpolate2(), nAngularParameters, nDiscreteEnergies, nEnergies, G4ParticleHPList::SetLabel(), G4ParticleHPList::SetValue(), theAngular, theDiscreteEnergies, theEnergy, theInt, theManager, theMaxEner, theMinEner, and val2.
Referenced by G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::cacheInit () inline private
Definition at line 207 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 207 of file G4ParticleHPContAngularPar.hh
References G4ParticleHPContAngularPar::toBeCached::currentMeanEnergy, fCache, G4ParticleHPContAngularPar::toBeCached::fresh, G4Cache< VALTYPE >::Put(), and G4ParticleHPContAngularPar::toBeCached::remaining_energy.
Referenced by ClearHistories(), G4ParticleHPContAngularPar(), and Sample().
void G4ParticleHPContAngularPar::ClearHistories () inline
Definition at line 179 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPContAngularPar.hh
References cacheInit(), fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::Dump ()
Definition at line 889 of file G4ParticleHPContAngularPar.cc.
View newest version in sPHENIX GitHub at line 889 of file G4ParticleHPContAngularPar.cc
References G4ParticleHPList::Dump(), G4cout, G4endl, nAngularParameters, nDiscreteEnergies, nEnergies, theAngular, and theEnergy.
Referenced by BuildByInterpolation().
G4ParticleHPList* G4ParticleHPContAngularPar::GetAngDataList () const inline
Definition at line 174 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ParticleHPContAngularPar.hh
References theAngular.
std::map<G4double,G4int> G4ParticleHPContAngularPar::GetDiscreteEnergiesOwn () const inline
Definition at line 170 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ParticleHPContAngularPar.hh
References theDiscreteEnergiesOwn.
Referenced by BuildByInterpolation().
std::set<G4double> G4ParticleHPContAngularPar::GetEnergiesTransformed () const inline
Definition at line 154 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPContAngularPar.hh
References theEnergiesTransformed.
Referenced by BuildByInterpolation().
G4double G4ParticleHPContAngularPar::GetEnergy () inline
Definition at line 95 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPContAngularPar.hh
References G4cout, G4endl, nEnergies, and theEnergy.
Referenced by BuildByInterpolation(), and G4ParticleHPContEnergyAngular::Sample().
G4double G4ParticleHPContAngularPar::GetMaxEner () const inline
Definition at line 166 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ParticleHPContAngularPar.hh
References theMaxEner.
Referenced by BuildByInterpolation(), and PrepareTableInterpolation().
G4double G4ParticleHPContAngularPar::GetMinEner () const inline
Definition at line 162 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ParticleHPContAngularPar.hh
References theMinEner.
Referenced by BuildByInterpolation(), and PrepareTableInterpolation().
G4int G4ParticleHPContAngularPar::GetNDiscreteEnergies () const inline
Definition at line 150 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParticleHPContAngularPar.hh
References nDiscreteEnergies.
Referenced by BuildByInterpolation(), and PrepareTableInterpolation().
G4int G4ParticleHPContAngularPar::GetNEnergies () const inline
Definition at line 146 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ParticleHPContAngularPar.hh
References nEnergies.
Referenced by BuildByInterpolation(), PrepareTableInterpolation(), and G4ParticleHPContEnergyAngular::Sample().
G4int G4ParticleHPContAngularPar::GetNEnergiesTransformed () const inline
Definition at line 158 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParticleHPContAngularPar.hh
References theEnergiesTransformed.
Referenced by BuildByInterpolation().
void G4ParticleHPContAngularPar::Init (std::istream & aDataFile, G4ParticleDefinition * projectile)
Definition at line 81 of file G4ParticleHPContAngularPar.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPContAngularPar.cc
References adjustResult, eV, G4ParticleHPList::Init(), max, min, nAngularParameters, nDiscreteEnergies, nEnergies, G4ParticleHPList::SetLabel(), theAngular, theEnergy, theMaxEner, theMinEner, and theProjectile.
Referenced by G4ParticleHPContEnergyAngular::Init().
G4double G4ParticleHPContAngularPar::MeanEnergyOfThisInteraction () inline
Definition at line 130 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ParticleHPContAngularPar.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::PrepareTableInterpolation (const G4ParticleHPContAngularPar * angularPrev)
Definition at line 696 of file G4ParticleHPContAngularPar.cc.
View newest version in sPHENIX GitHub at line 696 of file G4ParticleHPContAngularPar.cc
References G4ParticleHPList::GetLabel(), GetMaxEner(), GetMinEner(), GetNDiscreteEnergies(), GetNEnergies(), nDiscreteEnergies, nEnergies, theAngular, theDiscreteEnergies, theDiscreteEnergiesOwn, theEnergiesTransformed, theMaxEner, and theMinEner.
Referenced by G4ParticleHPContEnergyAngular::Init().
G4ReactionProduct * G4ParticleHPContAngularPar::Sample (G4double anEnergy, G4double massCode, G4double mass, G4int angularRep, G4int interpol)
Definition at line 105 of file G4ParticleHPContAngularPar.cc.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPContAngularPar.cc
References A(), adjustResult, G4Alpha::Alpha(), source.hepunit::amu_c2, cacheInit(), Acts::Test::delta, G4Deuteron::Deuteron(), e1, e2, G4Electron::Electron(), eV, fCache, G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), G4Cache< VALTYPE >::Get(), G4ParticleHPInterpolator::GetBinIntegral(), G4InterpolationManager::GetInverseScheme(), G4IonTable::GetIonTable(), G4ParticleHPList::GetLabel(), G4ReactionProduct::GetMass(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4InterpolationManager::GetScheme(), G4ReactionProduct::GetTotalMomentum(), G4ParticleHPList::GetValue(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPInterpolator::GetWeightedBinIntegral(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetY(), G4He3::He3(), G4ParticleHPLegendreStore::Init(), G4InterpolationManager::Init(), G4ParticleHPInterpolator::Interpolate(), it, max, min, nAngularParameters, nDiscreteEnergies, nEnergies, G4Neutron::Neutron(), phi, G4Positron::Positron(), G4Proton::Proton(), G4ParticleHPKallbachMannSyst::Sample(), G4ParticleHPVector::Sample(), G4ParticleHPLegendreStore::SampleMax(), G4ParticleHPLegendreStore::SetCoeff(), G4ReactionProduct::SetDefinition(), G4ParticleHPVector::SetInterpolationManager(), G4ReactionProduct::SetKineticEnergy(), G4ParticleHPLegendreStore::SetManager(), G4ReactionProduct::SetMomentum(), G4ParticleHPVector::SetX(), G4ParticleHPVector::SetY(), theAngular, theInt, theManager, theProjectile, theta(), G4Triton::Triton(), true, twopi, x, x1, x2, y, y1, y2, and Z.
Referenced by G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::SetInterpolation (G4int theInterpolation) inline
Definition at line 118 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParticleHPContAngularPar.hh
References G4InterpolationManager::Init(), nEnergies, and theManager.
Referenced by G4ParticleHPContEnergyAngular::Init(), and G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::SetPrimary (G4ReactionProduct * aPrimary) inline
Definition at line 103 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPContAngularPar.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::SetTarget (G4ReactionProduct * aTarget) inline
Definition at line 108 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPContAngularPar.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPContEnergyAngular::Sample().
void G4ParticleHPContAngularPar::SetTargetCode (G4double aTargetCode) inline
Definition at line 113 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPContAngularPar.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPContEnergyAngular::Sample().
Member Data Documentation
G4bool G4ParticleHPContAngularPar::adjustResult private
Definition at line 218 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 218 of file G4ParticleHPContAngularPar.hh
Referenced by G4ParticleHPContAngularPar(), Init(), and Sample().
G4Cache< toBeCached* > G4ParticleHPContAngularPar::fCache private
Definition at line 206 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 206 of file G4ParticleHPContAngularPar.hh
Referenced by cacheInit(), ClearHistories(), G4ParticleHPContAngularPar(), MeanEnergyOfThisInteraction(), Sample(), SetPrimary(), SetTarget(), SetTargetCode(), and ~G4ParticleHPContAngularPar().
G4int G4ParticleHPContAngularPar::nAngularParameters private
Definition at line 196 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), Dump(), G4ParticleHPContAngularPar(), Init(), and Sample().
G4int G4ParticleHPContAngularPar::nDiscreteEnergies private
Definition at line 194 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 194 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), Dump(), G4ParticleHPContAngularPar(), GetNDiscreteEnergies(), Init(), PrepareTableInterpolation(), and Sample().
G4int G4ParticleHPContAngularPar::nEnergies private
Definition at line 192 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), Dump(), G4ParticleHPContAngularPar(), GetEnergy(), GetNEnergies(), Init(), PrepareTableInterpolation(), Sample(), and SetInterpolation().
G4ParticleHPList* G4ParticleHPContAngularPar::theAngular private
Definition at line 200 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 200 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), Dump(), G4ParticleHPContAngularPar(), GetAngDataList(), Init(), PrepareTableInterpolation(), Sample(), and ~G4ParticleHPContAngularPar().
std::set<G4double> G4ParticleHPContAngularPar::theDiscreteEnergies private
Definition at line 225 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 225 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), and PrepareTableInterpolation().
std::map<G4double,G4int> G4ParticleHPContAngularPar::theDiscreteEnergiesOwn private
Definition at line 226 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ParticleHPContAngularPar.hh
Referenced by GetDiscreteEnergiesOwn(), and PrepareTableInterpolation().
std::set<G4double> G4ParticleHPContAngularPar::theEnergiesTransformed private
Definition at line 224 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 224 of file G4ParticleHPContAngularPar.hh
Referenced by GetEnergiesTransformed(), GetNEnergiesTransformed(), and PrepareTableInterpolation().
G4double G4ParticleHPContAngularPar::theEnergy private
Definition at line 190 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 190 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), Dump(), G4ParticleHPContAngularPar(), GetEnergy(), and Init().
G4ParticleHPInterpolator G4ParticleHPContAngularPar::theInt private
Definition at line 202 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 202 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), and Sample().
G4InterpolationManager G4ParticleHPContAngularPar::theManager private
Definition at line 198 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 198 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), Sample(), and SetInterpolation().
G4double G4ParticleHPContAngularPar::theMaxEner private
Definition at line 223 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 223 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), G4ParticleHPContAngularPar(), GetMaxEner(), Init(), and PrepareTableInterpolation().
G4double G4ParticleHPContAngularPar::theMinEner private
Definition at line 222 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 222 of file G4ParticleHPContAngularPar.hh
Referenced by BuildByInterpolation(), G4ParticleHPContAngularPar(), GetMinEner(), Init(), and PrepareTableInterpolation().
G4ParticleDefinition* G4ParticleHPContAngularPar::theProjectile private
Definition at line 214 of file G4ParticleHPContAngularPar.hh.
View newest version in sPHENIX GitHub at line 214 of file G4ParticleHPContAngularPar.hh
Referenced by G4ParticleHPContAngularPar(), Init(), and Sample().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPContAngularPar.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPContAngularPar.cc