ECCE @ EIC Software: G4ProtonPHPBuilder Class Reference
G4ProtonPHPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4ProtonPHPBuilder.hh>
Public Member Functions
G4ProtonPHPBuilder ()
virtual ~G4ProtonPHPBuilder ()
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theMax
G4ParticleHPInelastic * theParticlePHPModel
Detailed Description
Definition at line 46 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ProtonPHPBuilder.hh
Constructor & Destructor Documentation
G4ProtonPHPBuilder::G4ProtonPHPBuilder ()
Definition at line 34 of file G4ProtonPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 34 of file G4ProtonPHPBuilder.cc
References MeV, theMax, theMin, and theParticlePHPModel.
virtual G4ProtonPHPBuilder::~G4ProtonPHPBuilder () inline virtual
Definition at line 50 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ProtonPHPBuilder.hh
Member Function Documentation
void G4ProtonPHPBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 48 of file G4ProtonPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ProtonPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4HadronicInteraction::SetMinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theMax, theMin, and theParticlePHPModel.
void G4ProtonPHPBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 42 of file G4ProtonPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ProtonPHPBuilder.cc
References G4cout, and G4endl.
virtual void G4ProtonPHPBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 59 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ProtonPHPBuilder.hh
References theMax.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels().
virtual void G4ProtonPHPBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 55 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ProtonPHPBuilder.hh
References theMin.
Member Data Documentation
G4double G4ProtonPHPBuilder::theMax private
Definition at line 68 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ProtonPHPBuilder.hh
Referenced by Build(), G4ProtonPHPBuilder(), and SetMaxEnergy().
G4double G4ProtonPHPBuilder::theMin private
Definition at line 67 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ProtonPHPBuilder.hh
Referenced by Build(), G4ProtonPHPBuilder(), and SetMinEnergy().
G4ParticleHPInelastic* G4ProtonPHPBuilder::theParticlePHPModel private
Definition at line 69 of file G4ProtonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ProtonPHPBuilder.hh
Referenced by Build(), and G4ProtonPHPBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4ProtonPHPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4ProtonPHPBuilder.cc