ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4ModelingParameters.cc File Reference
G4ModelingParameters.cc File Reference
#include "G4ModelingParameters.hh"
#include "G4ios.hh"
#include "G4VisAttributes.hh"
#include "G4ExceptionSeverity.hh"
#include "G4SystemOfUnits.hh"
#include "G4VSolid.hh"
#include "G4DisplacedSolid.hh"
#include "G4VPhysicalVolume.hh"
#include "G4PhysicalVolumeModel.hh"
#include "G4UnitsTable.hh"
Functions
std::ostream & operator<< (std::ostream &os, const G4ModelingParameters &mp)
std::ostream & operator<< (std::ostream &os, const G4ModelingParameters::PVNameCopyNoPath &path)
std::ostream & operator<< (std::ostream &os, const std::vector< G4ModelingParameters::VisAttributesModifier > &vams)
Function Documentation
std::ostream& operator<< (std::ostream & os, const G4ModelingParameters & mp)
Definition at line 157 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 157 of file G4ModelingParameters.cc
References G4ModelingParameters::cloud, cm3, G4ModelingParameters::fCBDAlgorithmNumber, G4ModelingParameters::fCBDParameters, G4ModelingParameters::fCullCovered, G4ModelingParameters::fCulling, G4ModelingParameters::fCullInvisible, G4ModelingParameters::fDensityCulling, G4ModelingParameters::fDrawingStyle, G4ModelingParameters::fExplodeCentre, G4ModelingParameters::fExplodeFactor, G4ModelingParameters::fNoOfSides, G4ModelingParameters::fNumberOfCloudPoints, G4ModelingParameters::fpCutawaySolid, G4ModelingParameters::fpDefaultVisAttributes, G4ModelingParameters::fpEvent, G4ModelingParameters::fpSectionSolid, G4ModelingParameters::fVisAttributesModifiers, G4ModelingParameters::fVisibleDensity, G4ModelingParameters::fWarning, Acts::UnitConstants::g, G4BestUnit, G4ModelingParameters::hlhsr, G4ModelingParameters::hlr, G4ModelingParameters::hsr, and G4ModelingParameters::wf.
std::ostream& operator<< (std::ostream & os, const G4ModelingParameters::PVNameCopyNoPath & path)
Definition at line 343 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 343 of file G4ModelingParameters.cc
References k.
std::ostream& operator<< (std::ostream & os, const std::vector< G4ModelingParameters::VisAttributesModifier > & vams)
Definition at line 389 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 389 of file G4ModelingParameters.cc
References c, G4VisAttributes::cloud, G4VisAttributes::dashed, G4VisAttributes::dotted, G4VisAttributes::GetColour(), G4VisAttributes::GetForcedDrawingStyle(), G4VisAttributes::GetForcedLineSegmentsPerCircle(), G4VisAttributes::GetForcedNumberOfCloudPoints(), G4VisAttributes::GetLineStyle(), G4VisAttributes::GetLineWidth(), G4VisAttributes::IsDaughtersInvisible(), G4VisAttributes::IsForceAuxEdgeVisible(), G4VisAttributes::IsForcedAuxEdgeVisible(), G4VisAttributes::IsForceDrawingStyle(), G4VisAttributes::IsVisible(), G4VisAttributes::solid, G4VisAttributes::unbroken, G4ModelingParameters::VASColour, G4ModelingParameters::VASDaughtersInvisible, G4ModelingParameters::VASForceAuxEdgeVisible, G4ModelingParameters::VASForceCloud, G4ModelingParameters::VASForceLineSegmentsPerCircle, G4ModelingParameters::VASForceNumberOfCloudPoints, G4ModelingParameters::VASForceSolid, G4ModelingParameters::VASForceWireframe, G4ModelingParameters::VASLineStyle, G4ModelingParameters::VASLineWidth, G4ModelingParameters::VASVisibility, and G4VisAttributes::wireframe.