ECCE @ EIC Software: CCalRotationMatrixFactory Class Reference
CCalRotationMatrixFactory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalRotationMatrixFactory.hh>
Public Member Functions
~CCalRotationMatrixFactory ()
G4RotationMatrix * findMatrix (const G4String &)
G4RotationMatrix * AddMatrix (const G4String &name, G4double th1, G4double phi1, G4double th2, G4double phi2, G4double th3, G4double phi3)
Static Public Member Functions
static CCalRotationMatrixFactory * getInstance ()
static CCalRotationMatrixFactory * getInstance (const G4String &rotfile)
static void setFileName (const G4String &rotfile)
Private Member Functions
CCalRotationMatrixFactory ()
Private Attributes
G4RotationMatrixTable theMatrices
Static Private Attributes
static CCalRotationMatrixFactory * instance = 0
static G4String file =""
Detailed Description
Definition at line 45 of file CCalRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 45 of file CCalRotationMatrixFactory.hh
Constructor & Destructor Documentation
CCalRotationMatrixFactory::~CCalRotationMatrixFactory ()
Definition at line 84 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 84 of file CCalRotationMatrixFactory.cc
References theMatrices.
CCalRotationMatrixFactory::CCalRotationMatrixFactory () private
Definition at line 217 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 217 of file CCalRotationMatrixFactory.cc
References AddMatrix(), deg, FatalException, file, findDO(), G4cout, G4endl, G4Exception(), openGeomFile(), and theMatrices.
Referenced by getInstance().
Member Function Documentation
G4RotationMatrix * CCalRotationMatrixFactory::AddMatrix (const G4String & name, G4double th1, G4double phi1, G4double th2, G4double phi2, G4double th3, G4double phi3)
Definition at line 105 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 105 of file CCalRotationMatrixFactory.cc
References deg, G4cout, G4endl, CLHEP::HepRotation::invert(), CLHEP::HepRotation::rotateAxes(), and theMatrices.
Referenced by CCalRotationMatrixFactory(), CCalG4Ecal::constructGlobal(), and CCalG4Ecal::constructIn().
G4RotationMatrix * CCalRotationMatrixFactory::findMatrix (const G4String & rot)
!!Maybe a treatment on not-found case needed.
Definition at line 92 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 92 of file CCalRotationMatrixFactory.cc
References it, and theMatrices.
Referenced by CCalG4Ecal::constructGlobal(), and CCalG4Ecal::constructIn().
CCalRotationMatrixFactory * CCalRotationMatrixFactory::getInstance () static
Definition at line 60 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 60 of file CCalRotationMatrixFactory.cc
References CCalRotationMatrixFactory(), file, G4cerr, G4endl, and instance.
Referenced by CCalDetectorConstruction::Construct(), CCalG4Ecal::constructGlobal(), CCalG4Ecal::constructIn(), and getInstance().
CCalRotationMatrixFactory * CCalRotationMatrixFactory::getInstance (const G4String & rotfile) static
Definition at line 46 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 46 of file CCalRotationMatrixFactory.cc
References file, G4cerr, G4endl, and getInstance().
void CCalRotationMatrixFactory::setFileName (const G4String & rotfile) static
Definition at line 75 of file CCalRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 75 of file CCalRotationMatrixFactory.cc
References file, G4cerr, and G4endl.
Member Data Documentation
G4String CCalRotationMatrixFactory::file ="" static private
Definition at line 64 of file CCalRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 64 of file CCalRotationMatrixFactory.hh
Referenced by CCalRotationMatrixFactory(), getInstance(), and setFileName().
CCalRotationMatrixFactory * CCalRotationMatrixFactory::instance = 0 static private
Definition at line 63 of file CCalRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalRotationMatrixFactory.hh
Referenced by getInstance().
G4RotationMatrixTable CCalRotationMatrixFactory::theMatrices private
Definition at line 66 of file CCalRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 66 of file CCalRotationMatrixFactory.hh
Referenced by AddMatrix(), CCalRotationMatrixFactory(), findMatrix(), and ~CCalRotationMatrixFactory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalRotationMatrixFactory.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalRotationMatrixFactory.cc