ECCE @ EIC Software: acts/blob/master/Tests/UnitTests/Core/Material/MaterialPropertiesTests.cpp File Reference
MaterialPropertiesTests.cpp File Reference
#include <boost/test/unit_test.hpp>
#include <limits>
#include <vector>
#include "Acts/Material/MaterialProperties.hpp"
#include "Acts/Tests/CommonHelpers/FloatComparisons.hpp"
Functions
BOOST_AUTO_TEST_CASE (construct_simple)
BOOST_AUTO_TEST_CASE (construct_compound)
BOOST_AUTO_TEST_CASE (scale_thickness)
Variables
static constexpr auto eps = 2 * std::numeric_limits<float>::epsilon()
static const
Acts::MaterialProperties a (1., 2., 3., 4., 5., 1.)
static const
Acts::MaterialProperties b (2., 4., 6., 8., 10., 2.)
static const
Acts::MaterialProperties c (4., 8., 12., 16., 20., 3.)
static const std::vector
< Acts::MaterialProperties > components = {a, b, c}
Function Documentation
BOOST_AUTO_TEST_CASE (construct_simple)
construct from material and thickness
Definition at line 21 of file MaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file MaterialPropertiesTests.cpp
References CHECK_CLOSE_REL, eps, Acts::MaterialProperties::material(), Acts::MaterialProperties::thickness(), Acts::MaterialProperties::thicknessInL0(), and Acts::MaterialProperties::thicknessInX0().
BOOST_AUTO_TEST_CASE (construct_compound)
Definition at line 42 of file MaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 42 of file MaterialPropertiesTests.cpp
References a, b, c, CHECK_CLOSE_REL, eps, Acts::Material::L0(), Acts::Material::massDensity(), Acts::MaterialProperties::material(), Acts::MaterialProperties::thickness(), Acts::MaterialProperties::thicknessInL0(), Acts::MaterialProperties::thicknessInX0(), and Acts::Material::X0().
BOOST_AUTO_TEST_CASE (scale_thickness)
Definition at line 69 of file MaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 69 of file MaterialPropertiesTests.cpp
References CHECK_CLOSE_REL, eps, Acts::Material::massDensity(), mat, Acts::MaterialProperties::material(), Acts::MaterialProperties::scaleThickness(), Acts::MaterialProperties::thickness(), Acts::MaterialProperties::thicknessInL0(), and Acts::MaterialProperties::thicknessInX0().
Variable Documentation
const Acts::MaterialProperties a(1., 2., 3., 4., 5., 1.) static
Referenced by airy1(), airy1d(), airy2(), airy2d(), aiz(), ar3jet(), BOOST_AUTO_TEST_CASE(), calcta(), calcxsection(), ei(), fg(), fgp(), gauss1(), gauss2(), gauss3(), gauss4(), getinsudared(), getltimemax(), getmdmin(), getnatmdmin(), getneff(), getneffmax(), getpdfxint(), getscatterer(), getspliti(), gettemp(), gettempmax(), getxsecint(), hijwds(), i1mcry(), ksatt(), ksdet(), ksdeta(), ksdetd(), ksdeth(), ksdetu(), ksdetv(), ksdvn(), ksdvn2(), ksdvt(), ksdvt2(), ksdvx(), ksmate(), ksmixt(), kspart(), kspos(), ksposp(), kstmed(), kstpar(), ksvolu(), ludecy(), luerrm(), medderiv(), medinit(), mednextevt(), npart(), nthick(), odeint(), pybksb(), pydecy(), pyeig4(), pyerrm(), pyfint(), pygau2(), pygaus(), pygrvv(), pygrvw(), pyhiinki(), pyhistat(), pyinbm(), pyinki(), pyjurf(), pyldcm(), pymirm(), pyresd(), pyrvg1(), pyrvg2(), pyrvg3(), pyrvg4(), pyrvi1(), pyrvi2(), pyrvi3(), pyslha(), pystat(), pystbh(), pysugi(), pytbbc(), pytbhb(), pytbhg(), pytbhq(), pytbhs(), pythag(), pyuedc(), pyxdin(), pyxxz6(), and tog4().
const Acts::MaterialProperties b(2., 4., 6., 8., 10., 2.) static
Referenced by __attribute__(), __example_6.f__(), nanoflann::L2_Adaptor< T, DataSource, _DistanceType >::accum_dist(), nanoflann::L2_Simple_Adaptor< double, kdfinder::KDPointCloud< double > >::accum_dist(), G4GaussLegendreQ::AccurateIntegral(), G4GHEKinematicsVector::Add(), MultiArray< TVector3 >::Add(), addBinding(), AddFlowToParent(), airy2(), airy2d(), G4NuclNuclDiffuseElastic::AmplitudeGla(), AnalyticFieldModel::AnalyticFieldModel(), G4ErrorMatrix::apply(), G4ErrorSymMatrix::apply(), G4LEnp::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4ExtrudedSolid::ApproxSurfaceNormal(), G4Trap::ApproxSurfaceNormal(), G4ErrorSymMatrix::assign(), G4EmCorrections::BarkasCorrection(), CLHEP::Hep3Vector::beta(), G4AnalyticalPolSolver::BiquadRoots(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4CollisionComposite::BufferCrossSection(), KFParticle_eventReconstruction::buildChain(), G4IonDEDXHandler::BuildDEDXTable(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::buildFrameWork(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4HadronCrossSections::CalcScatteringCrossSections(), calcta(), HelixKalman::calculate_dpdb(), HelixKalmanFilter::calculate_dpdb(), G4hhElastic::CalculateBQ(), G4INCL::CrossSectionsMultiPions::calculateNNAngularSlope(), G4INCL::CrossSectionsINCL46::calculateNNAngularSlope(), calcxsection(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4ViewParameters::CatmullRomCubicSplineInterpolation(), G4SynchrotronRadiation::Chebyshev(), Acts::LayerCreator::checkBinning(), G4GeomTools::CheckSnip(), PHTpcClusterMover::circle_circle_intersection(), PHActsSiliconSeeding::circleCircleIntersection(), G4GeomTools::ClosestPointOnTriangle(), G4NeutrinoNucleusModel::CoherentPion(), CLHEP::Hep3Vector::coLinearRapidity(), G03ColorReader::ColorRead(), G03ColorWriter::ColorWrite(), PgPostApplication::commit(), G4GeomTools::comp_ellint_2(), boost::python::map_indexing_suite< Container, NoProxy, final_map_derived_policies< Container, NoProxy > >::compare_index(), boost::python::vector_indexing_suite< Container, NoProxy, final_vector_derived_policies< Container, NoProxy > >::compare_index(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::completeBinning(), G4CrystalUnitCell::ComputeCellVolume(), G4KalbachCrossSection::ComputeCrossSection(), G4XrayRayleighModel::ComputeCrossSectionPerAtom(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4hBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4MuBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4UrbanMscModel::ComputeTheta0(), G4UrbanAdjointMscModel::ComputeTheta0(), Acts::GenericCuboidVolumeBounds::construct(), Acts::TGeoDetectorElement::construct(), nlohmann::detail::external_constructor< value_t::boolean >::construct(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), Acts::ConvexPolygonBoundsBase::convex_impl(), G4ReduciblePolygon::CopyVertices(), G4AngularDistributionPP::CosTheta(), G4AngularDistributionNP::CosTheta(), MuCrossSections::CRB_Mephi(), G4ReduciblePolygon::Create(), PgPostBankManager::createBank(), Acts::SurfaceArrayCreator::createEquidistantAxis(), Acts::createGrid2D(), Acts::createGrid3D(), G4BoundingEnvelope::CreateListOfPlanes(), G4GenericPolycone::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4VSceneHandler::CreateSectionSolid(), Acts::Seedfinder< external_spacepoint_t >::createSeedsForGroup(), Acts::SurfaceArrayCreator::createVariableAxis(), G4AdjointCrossSurfChecker::CrossingASphere(), csz__huft_build(), csz__Inflate_block(), csz__Inflate_codes(), csz__Inflate_dynamic(), csz__Inflate_stored(), G4AnalyticalPolSolver::CubicRoots(), G4DataInterpolation::CubicSplineInterpolation(), oncsSub_idmvtxv2::decode(), CLHEP::HepLorentzRotation::decompose(), Acts::GenericCuboidVolumeBounds::decomposeToSurfaces(), CLHEP::Hep3Vector::deltaR(), CLHEP::HepLorentzVector::deltaR(), destroyBindings(), Acts::SurfaceArrayCreator::determineBinCount(), CLHEP::HepRotationZ::distance2(), CLHEP::HepRotationY::distance2(), CLHEP::HepRotationX::distance2(), CLHEP::HepRotation::distance2(), Acts::EllipseBounds::distanceToBoundary(), G4CutTubs::DistanceToIn(), G4Tubs::DistanceToIn(), G4Cons::DistanceToIn(), G4Sphere::DistanceToIn(), G4Trap::DistanceToIn(), G4GenericTrap::DistanceToOut(), G4CutTubs::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Tubs::DistanceToOut(), G4Cons::DistanceToOut(), G4Sphere::DistanceToOut(), G4Trap::DistanceToOut(), G4ReplicaNavigation::DistanceToOutRad(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4GenericTrap::DistToPlane(), G4GenericTrap::DistToTriangle(), G4Abla::dmin1(), SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4cluster_eval(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_gseed_eval(), SvtxEvaluator::do_gtrack_eval(), SvtxEvaluator::do_hit_eval(), SvtxEvaluator::do_info_eval(), SvtxEvaluator::do_track_eval(), SvtxEvaluator::do_track_match(), SvtxEvaluator::do_vertex_eval(), SvtxEvaluator::do_vtx_eval_light(), doContent(), Acts::GenericCuboidVolumeBounds::draw(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::draw(), G4ScoreLogColorMap::DrawColorChartText(), G4VScoreColorMap::DrawColorChartText(), ei(), kdfinder::CircleFit< T >::eigen2x2(), kdfinder::elementsort(), G4GeomTools::EllipsePerimeter(), G4GeomTools::EllipticConeLateralArea(), PHG4TrackFastSim::enable_vertexing(), B0TrackFastSim::enable_vertexing(), LiteCaloEval::End(), eval_max(), eval_min(), G4ecpssrBaseKxsModel::ExpIntFunction(), G4ecpssrBaseLixsModel::ExpIntFunction(), Par01EMShowerModel::Explode(), G4PolyconeSide::Extent(), G4IonFluctuations::Factor(), G4DataInterpolation::FastCubicSpline(), G4LivermorePolarizedGammaConversionModel::Fdtan(), FermiMotion(), fg(), fgp(), HelixHough::fillBins(), fillEvent(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMomentum(), sPHENIXTracker::findHelicesParallelOneHelicity(), sPHENIXSeedFinder::findHelicesParallelOneHelicity(), Acts::RiddersPropagator< propagator_t >::fitLinear(), G4LivermorePolarizedGammaConversionModel::Fln(), PHTpcTrackFollower::followTracks(), G4StatMFChannel::FragmentsMomenta(), G4AllocatorPool::Free(), G4LivermorePolarizedGammaConversionModel::Ftan(), G4ErrorMatrix::G4ErrorMatrix(), G4GaussJacobiQ::G4GaussJacobiQ(), G4RandomDirection(), G4ReduciblePolygon::G4ReduciblePolygon(), G4fissionEvent::G4SmpNEngCf252(), G4fissionEvent::G4SmpWatt(), G4Solver< Function >::G4Solver(), G4SwapObj(), G4SwapPtr(), G4VXTRenergyLoss::G4VXTRenergyLoss(), MyGamma::GamCf(), GammaFit(), gauss1(), gauss2(), gauss3(), gauss4(), G4Abla::gcf(), CLHEP::RandBinomial::genBinomial(), CLHEP::RandChiSquare::genChiSquare(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), CLHEP::RandGamma::genGamma(), MultiArray< TVector3 >::Get(), kdfinder::get_track_color(), G4AdjointCSManager::GetAdjointSigma(), G4ParticleHPInterpolator::GetBinIntegral(), G4EMDissociationSpectrum::GetClosestApproach(), G4VXTRenergyLoss::GetComptonPerAtom(), G4IonDEDXHandler::GetDEDX(), G4ChargeExchangeProcess::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4NuclNuclDiffuseElastic::GetErfSer(), G4TwistBoxSide::GetFacets(), G4TwistTrapAlphaSide::GetFacets(), G4PhotoNuclearCrossSection::GetFunctions(), G4ElectroNuclearCrossSection::GetFunctions(), G4EMDissociationSpectrum::GetGeneralE1Spectrum(), G4EMDissociationSpectrum::GetGeneralE2Spectrum(), getinsudared(), G4CrystalUnitCell::GetIntCosAng(), G4CrystalUnitCell::GetIntSp2(), G4IonsShenCrossSection::GetIsoCrossSection(), PHG4HcalDetector::GetLength(), PHG4SteppingAction::GetLightCorrection(), ALICEKF::GetLineClusterResiduals(), G4DefaultLinearColorMap::GetMapColor(), G4ScoreLogColorMap::GetMapColor(), G4AdjointCSManager::GetMaxAdjTotalCS(), G4AdjointCSManager::GetMaxFwdTotalCS(), Acts::FsmwMode1dFinder::getMode(), G4PenelopeBremsstrahlungFS::GetMomentumIntegral(), getpdfxint(), G4RDPhotoElectricAngularGeneratorSauterGavrila::GetPhotoElectronDirection(), G4Polyhedra::GetPointOnSurface(), G4EllipticalCone::GetPointOnSurface(), MultiArray< TVector3 >::GetPtr(), G4CrystalUnitCell::GetRecIntSp2(), ActsFatras::detail::GeneralMixture::getSemigauss(), getspliti(), G4AdjointCSManager::GetTotalAdjointCS(), G4AdjointCSManager::GetTotalForwardCS(), G4LENDCrossSection::GetUltraLowEnergyExtrapolatedXS(), G4Trap::GetVertices(), G4ElectroNuclearCrossSection::GetVirtualFactor(), G4ParticleHPInterpolator::GetWeightedBinIntegral(), G4PolynomialPDF::GetX(), getxsecint(), G4ParticleHPMadlandNixSpectrum::GIntegral(), kdfinder::CircleFit< T >::GradientHessian(), PgPostBankBackupManager::HashPdbCalChan(), i1mcry(), PHG4CylinderCellGeom_Spacalv1::identify(), G4EmCorrections::Initialise(), G4NucleiModel::initializeCascad(), G4PenelopeRayleighModel::InitializeSamplingAlgorithm(), CaloCalibEmc_Pi0::InitRun(), LiteCaloEval::InitRun(), G4Trap::Inside(), G4GaussLegendreQ::Integral(), G4ParticleHPVector::Integrate(), G4FSALDormandPrince745::Interpolate(), G4DNABornIonisationModel2::Interpolate(), G4DNABornIonisationModel1::Interpolate(), G4MicroElecInelasticModel::Interpolate(), G4DNAEmfietzoglouIonisationModel::Interpolate(), G4DNACPA100IonisationModel::Interpolate(), G4DormandPrince745::Interpolate5thOrder(), G4DormandPrinceRK56::Interpolate_high(), G4BogackiShampine45::InterpolateHigh(), G4Hype::IntersectHype(), Acts::CylinderSurface::intersectionSolver(), PrimaryGeneratorAction2::InverseCumul(), G4GIDI::isThisDataAvailable(), G4INCL::NKbElasticChannel::KaonMomentum(), G4INCL::NKbToSpiChannel::KaonMomentum(), G4INCL::NpiToLKChannel::KaonMomentum(), G4INCL::NpiToSKChannel::KaonMomentum(), G4INCL::NKbToLpiChannel::KaonMomentum(), G4INCL::NKbToNKbChannel::KaonMomentum(), ALICEKF::line_fit(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4DNASancheExcitationModel::LinInterpolate(), G4EMDataSet::LoadData(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4ecpssrBaseKxsModel::LogLogInterpolate(), G4ecpssrBaseLixsModel::LogLogInterpolate(), G4MuElecElasticModel::LogLogInterpolate(), G4MicroElecElasticModel::LogLogInterpolate(), G4DNAIonElasticModel::LogLogInterpolate(), G4DNACPA100ElasticModel::LogLogInterpolate(), G4MuElecInelasticModel::LogLogInterpolate(), G4DNAChampionElasticModel::LogLogInterpolate(), G4DNAELSEPAElasticModel::LogLogInterpolate(), G4DNAPTBElasticModel::LogLogInterpolate(), G4UCNBoundaryProcess::Loss(), ludecy(), main(), G4Trap::MakePlanes(), G4JpegCoder::makeYCC(), EmcCluster::max(), G4Abla::max(), max3(), max4(), MCGIDI_energy_sampleEvaporation(), MCGIDI_energy_sampleSimpleMaxwellianFission(), MCGIDI_kinetics_COM2Lab(), md5_process(), medderiv(), EmcCluster::min(), G4Abla::min(), min3(), G4Abla::mod(), moveToFreeBindingList(), MultiArray< TVector3 >::MultiArray(), oncsSub_idmvtxv0::mvtx_decode(), oncsSub_idmvtxv1::mvtx_decode(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK(), G4INCL::CrossSectionsStrangeness::NDeltaToNLK(), G4INCL::CrossSectionsStrangeness::NDeltaToNSK(), nf_exponentialIntegral(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), CLHEP::HepLorentzRotation::norm2(), nthick(), odeint(), CLHEP::operator!=(), G4::MoleculeCounter::TimePrecision::operator()(), G4RayTracerSceneHandler::PathLessThan::operator()(), CLHEP::HepBoostX::operator*(), CLHEP::HepBoostZ::operator*(), CLHEP::HepBoostY::operator*(), G4ErrorSymMatrix::operator-(), G4ErrorMatrix::operator-(), CLHEP::operator<(), CLHEP::operator<<(), CLHEP::operator<=(), G4Solver< Function >::operator=(), CLHEP::operator==(), CLHEP::operator>(), CLHEP::operator>=(), G4PenelopeComptonModel::OscillatorTotalCrossSection(), kdfinder::Helix< T >::pathLengths(), PgPostBankBackupStorage::PgPostBankBackupStorage(), PgPostBankWrapper::PgPostBankWrapper(), CLHEP::RandPoissonQ::poissonDeviateSmall(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::production3Sp(), PHSimpleKFProp::PropagateTrack(), prt_get_momentum_from_tof(), pybksb(), pydecy(), pyfint(), pygamm(), pygau2(), pygaus(), pygrvs(), pygrvv(), pygrvw(), pyhigamm(), pyhimult(), pyhirand(), pyhispen(), pyhixtot(), pymign(), pymirm(), pymult(), pypole(), pyrand(), pyresd(), pyrvg1(), pyrvg2(), pyrvg3(), pyrvg4(), pyrvi1(), pyrvi2(), pyrvi3(), pyspen(), pysugi(), pytbhs(), pythag(), pyuedc(), pyxtot(), pyxxz6(), G4AnalyticalPolSolver::QuadRoots(), G4AnalyticalPolSolver::QuarticRoots(), G4GaussLegendreQ::QuickIntegral(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4ScreeningMottCrossSection::RatioMottRutherfordCosT(), G4RPGTwoBody::ReactionStage(), CCalVisualisable::readFile(), G4ENDFTapeRead::ReadInData(), kdfinder::LinearFit< T >::RegularFit(), G4GeometryManager::ReportVoxelStats(), G4MuonRadiativeDecayChannelWithSpin::rn3dim(), kdfinder::LinearFit< T >::RobustFit(), G4ParticleHPWattSpectrum::Sample(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4LEpp::SampleInvariantT(), G4LEnp::SampleInvariantT(), G4GoudsmitSaundersonMscModel::SampleMSC(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4LMsdGenerator::SampleT(), PHG4Reco::save_DST_geometry(), PHPythia8::save_event_weight(), PHPythia8::save_integrated_luminosity(), JetHepMCLoader::saveQAPlots(), SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::scan_for_primaries(), ActsFatras::detail::GeneralMixture::semigauss(), CLHEP::HepLorentzRotation::set(), MultiArray< TVector3 >::Set(), PHG4CylinderGeom_Spacalv2::set_azimuthal_seg_visible(), PHG4Reco::set_decayer_active(), EventEvaluatorEIC::set_do_BECAL(), EventEvaluatorEIC::set_do_BLACKHOLE(), EventEvaluator::set_do_CEMC(), EventEvaluatorEIC::set_do_CEMC(), CaloEvaluator::set_do_cluster_eval(), EventEvaluator::set_do_CLUSTERS(), EventEvaluatorEIC::set_do_CLUSTERS(), EventEvaluatorEIC::set_do_DRCALO(), EventEvaluatorEIC::set_do_EEMC(), EventEvaluatorEIC::set_do_EEMCG(), EventEvaluatorEIC::set_do_EHCAL(), EventEvaluatorEIC::set_do_FEMC(), EventEvaluatorEIC::set_do_FHCAL(), EventEvaluatorEIC::set_do_FOCAL(), EventEvaluator::set_do_GEOMETRY(), EventEvaluatorEIC::set_do_GEOMETRY(), CaloEvaluator::set_do_gpoint_eval(), CaloEvaluator::set_do_gshower_eval(), EventEvaluator::set_do_HCALIN(), EventEvaluatorEIC::set_do_HCALIN(), EventEvaluator::set_do_HCALOUT(), EventEvaluatorEIC::set_do_HCALOUT(), EventEvaluator::set_do_HEPMC(), EventEvaluatorEIC::set_do_HEPMC(), EventEvaluator::set_do_HITS(), EventEvaluatorEIC::set_do_HITS(), EventEvaluatorEIC::set_do_HITS_ABSORBER(), EventEvaluatorEIC::set_do_HITS_CALO(), EventEvaluatorEIC::set_do_LFHCAL(), EventEvaluator::set_do_MCPARTICLES(), EventEvaluatorEIC::set_do_MCPARTICLES(), EventEvaluatorEIC::set_do_PID_LogLikelihood(), EventEvaluator::set_do_PROJECTIONS(), EventEvaluatorEIC::set_do_PROJECTIONS(), EventEvaluator::set_do_store_event_level_info(), EventEvaluatorEIC::set_do_store_event_level_info(), CaloEvaluator::set_do_tower_eval(), EventEvaluator::set_do_TRACKS(), EventEvaluatorEIC::set_do_TRACKS(), EventEvaluator::set_do_VERTEX(), EventEvaluatorEIC::set_do_VERTEX(), PHG4EventHeaderv1::set_ImpactParameter(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), JetEvaluator::set_strict(), CaloEvaluator::set_strict(), EventEvaluator::set_strict(), SvtxEvaluator::set_strict(), EventEvaluatorEIC::set_strict(), PHG4DSTReader::set_tower_zero_sup(), G4INCLXXInterfaceStore::SetAccurateProjectile(), G4INCL::Config::setBackToSpectator(), G4INCL::BinaryCollisionAvatar::setBias(), G4Colour::SetBlue(), G4hhElastic::SetBq(), G4hhElastic::SetBQ(), G4hhElastic::SetBqQ(), CCalVisualisable::setColor(), CCalVisualisable::setColorBlue(), G4GeometryCellStep::SetCrossBoundary(), PHG4BackwardHcalSubsystem::SetDetailed(), PHG4ForwardEcalSubsystem::SetDetailed(), PHG4LFHcalSubsystem::SetDetailed(), PHG4ForwardHcalSubsystem::SetDetailed(), PHG4TTLSubsystem::SetDetailed(), PHG4Reco::setDisableUserActions(), LXePMTHit::SetDrawit(), LXeTrajectory::SetDrawTrajectory(), G4OpticalPhysics::SetFiniteRiseTime(), LXeEventAction::SetForceDrawNoPhotons(), LXeEventAction::SetForceDrawPhotons(), LXeTrajectory::SetForceDrawTrajectory(), LXeUserTrackInformation::SetForceDrawTrajectory(), LXeTrajectory::SetForceNoDrawTrajectory(), G4IonCoulombScatteringModel::SetHeavyIonCorr(), G4BOptnForceCommonTruncatedExp::SetInteractionOccured(), G4OpticalPhysics::SetInvokeSD(), TrackInformation::SetIsFirstTankX(), PHG4HcalSteppingAction::SetLightScintModel(), PHG4HcalSubsystem::SetLightScintModel(), LXeDetectorConstruction::SetMainVolumeOn(), LXeSteppingAction::SetOneStepPrimaries(), G4LivermorePolarizedComptonModel::SetPhi(), G4LowEnergyPolarizedCompton::SetPhi(), G4LowEPPolarizedComptonModel::SetPhi(), G4LivermorePolarizedGammaConversionModel::SetPsi(), G4NavigationLogger::SetReportSoftWarnings(), PHNode::setResetFlag(), PHG4TruthSubsystem::SetSaveOnlyEmbeded(), G4LatticeLogical::SetScatteringConstant(), LXeDetectorConstruction::SetSphereOn(), PHPy8ParticleTrigger::SetStableParticleOnly(), PHG4HcalSubsystem::SetTiltViaNcross(), QAG4SimulationTracking::setUniqueTrackingMatch(), LXeDetectorConstruction::SetWLSSlabOn(), G4AtimaEnergyLossModel::sezi_dedx_e(), Acts::detail::Grid< external_spacepoint_t >::size(), PHG4TrackFastSim::Smearing(), B0TrackFastSim::Smearing(), Acts::sortDetElementsByID(), FW::Options::sortFCChhDetElements(), G4ForwardXrayTR::SpectralDensity(), G4PAIySection::SplainPAI(), G4PAIxSection::SplainPAI(), HelixHough::splitIntoBins(), storeAtts(), HadrontherapyLet::StoreLetAscii(), G4ErrorSymMatrix::sub(), G4GHEKinematicsVector::Sub(), G4PAIySection::SumOverBordCerenkov(), G4PAIxSection::SumOverBordCerenkov(), G4PAIySection::SumOverBorder(), G4PAIxSection::SumOverBorder(), G4PAIySection::SumOverBorderdEdx(), G4PAIxSection::SumOverBorderdEdx(), G4PAIxSection::SumOverBordMM(), G4PAIySection::SumOverBordPlasmon(), G4PAIxSection::SumOverBordPlasmon(), G4PAIxSection::SumOverBordResonance(), G4PAIySection::SumOverInterCerenkov(), G4PAIxSection::SumOverInterCerenkov(), G4PAIxSection::SumOverInterMM(), G4PAIySection::SumOverInterPlasmon(), G4PAIxSection::SumOverInterPlasmon(), G4PAIxSection::SumOverInterResonance(), G4PAIySection::SumOverInterval(), G4PAIxSection::SumOverInterval(), G4PAIySection::SumOverIntervaldEdx(), G4PAIxSection::SumOverIntervaldEdx(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), G4Trap::SurfaceNormal(), kdfinder::LinearFit< T >::SWAP(), nlohmann::detail::to_json(), nlohmann::json_pointer< BasicJsonType >::to_string(), G4GeomTools::TriangulatePolygon(), PHHepMCGenHelper::use_beam_bunch_sim(), MyJetAnalysis::use_initial_vertex(), kdfinder::vertexsort(), FW::RootMaterialWriter::write(), simpleRandom::xMD5Transform(), G4IonYangFluctuationModel::YangFluctuationModel(), and G4LossTableManager::~G4LossTableManager().
const Acts::MaterialProperties c(4., 8., 12., 16., 20., 3.) static
Referenced by aiz(), ar3jet(), biz(), BOOST_AUTO_TEST_CASE(), i1mcry(), ludecy(), nthick(), pycbal(), pydecy(), pyfint(), pygrvv(), pygrvw(), pyhirand(), pyhixtot(), pymirm(), pyrand(), pyresd(), pyrnm3(), pyrnmq(), pytbdy(), pyuedc(), pyxtot(), and pyxxz6().
const std::vector<Acts::MaterialProperties> components = {a, b, c} static
Definition at line 40 of file MaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 40 of file MaterialPropertiesTests.cpp
Referenced by G4INCL::Nucleus::applyFinalState(), PHG4CylinderStripDetector::ConstructMe(), det::createTkLayoutTrackerEndcap(), G4CrossSectionPatch::CrossSection(), G4CrossSectionComposite::CrossSection(), G4CollisionNN::G4CollisionNN(), G4CrossSectionPatch::IsValid(), G4CrossSectionComposite::IsValid(), G4INCL::SurfaceAvatar::postInteraction(), G4VCrossSectionSource::Print(), G4VCollision::Print(), and G4VCrossSectionSource::PrintAll().
constexpr auto eps = 2 * std::numeric_limits<float>::epsilon() static
Definition at line 17 of file MaterialPropertiesTests.cpp.
View newest version in sPHENIX GitHub at line 17 of file MaterialPropertiesTests.cpp
Referenced by BOOST_AUTO_TEST_CASE().