ECCE @ EIC Software: XrayFluoSD Class Reference
XrayFluoSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoSD.hh>
Public Member Functions
XrayFluoSD (G4String, XrayFluoDetectorConstruction *)
XrayFluoSD (G4String, XrayFluoPlaneDetectorConstruction *)
XrayFluoSD (G4String, XrayFluoMercuryDetectorConstruction *)
~XrayFluoSD ()
void Initialize (G4HCofThisEvent *)
void EndOfEvent (G4HCofThisEvent *)
void clear ()
void DrawAll ()
void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Protected Member Functions
G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Private Attributes
XrayFluoSensorHitsCollection * HPGeCollection
XrayFluoDetectorConstruction * Detector
XrayFluoPlaneDetectorConstruction * planeDetector
XrayFluoMercuryDetectorConstruction * mercuryDetector
G4int * HitHPGeID
Additional Inherited Members
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 55 of file XrayFluoSD.hh.
View newest version in sPHENIX GitHub at line 55 of file XrayFluoSD.hh
Constructor & Destructor Documentation
XrayFluoSD::XrayFluoSD (G4String name, XrayFluoDetectorConstruction * det)
Definition at line 53 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 53 of file XrayFluoSD.cc
References G4VSensitiveDetector::collectionName, Detector, G4cout, G4endl, HitHPGeID, and G4CollectionNameVector::insert().
XrayFluoSD::XrayFluoSD (G4String name, XrayFluoPlaneDetectorConstruction * det)
Definition at line 67 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 67 of file XrayFluoSD.cc
References G4VSensitiveDetector::collectionName, G4cout, G4endl, HitHPGeID, G4CollectionNameVector::insert(), and planeDetector.
XrayFluoSD::XrayFluoSD (G4String name, XrayFluoMercuryDetectorConstruction * det)
Definition at line 80 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 80 of file XrayFluoSD.cc
References G4VSensitiveDetector::collectionName, G4cout, G4endl, HitHPGeID, G4CollectionNameVector::insert(), and mercuryDetector.
XrayFluoSD::~XrayFluoSD ()
Definition at line 95 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 95 of file XrayFluoSD.cc
References G4cout, G4endl, and HitHPGeID.
Member Function Documentation
void XrayFluoSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 199 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 199 of file XrayFluoSD.cc
void XrayFluoSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 204 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 204 of file XrayFluoSD.cc
void XrayFluoSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 189 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 189 of file XrayFluoSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), and HPGeCollection.
void XrayFluoSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 107 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 107 of file XrayFluoSD.cc
References G4VSensitiveDetector::collectionName, Detector, XrayFluoMercuryDetectorConstruction::GetNbOfPixels(), XrayFluoPlaneDetectorConstruction::GetNbOfPixels(), XrayFluoDetectorConstruction::GetNbOfPixels(), HitHPGeID, HPGeCollection, mercuryDetector, planeDetector, and G4VSensitiveDetector::SensitiveDetectorName.
void XrayFluoSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 209 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 209 of file XrayFluoSD.cc
G4bool XrayFluoSD::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VSensitiveDetector.
Definition at line 127 of file XrayFluoSD.cc.
View newest version in sPHENIX GitHub at line 127 of file XrayFluoSD.cc
References XrayFluoSensorHit::AddEnergy(), Detector, edep, G4cout, G4endl, G4VPhysicalVolume::GetCopyNo(), XrayFluoMercuryDetectorConstruction::GetNbOfPixels(), XrayFluoPlaneDetectorConstruction::GetNbOfPixels(), XrayFluoDetectorConstruction::GetNbOfPixels(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4TouchableHistory::GetVolume(), HitHPGeID, HPGeCollection, G4THitsCollection< T >::insert(), mercuryDetector, planeDetector, and G4VSensitiveDetector::verboseLevel.
Member Data Documentation
XrayFluoDetectorConstruction* XrayFluoSD::Detector private
Definition at line 77 of file XrayFluoSD.hh.
View newest version in sPHENIX GitHub at line 77 of file XrayFluoSD.hh
Referenced by Initialize(), ProcessHits(), and XrayFluoSD().
G4int* XrayFluoSD::HitHPGeID private
Definition at line 81 of file XrayFluoSD.hh.
View newest version in sPHENIX GitHub at line 81 of file XrayFluoSD.hh
Referenced by Initialize(), ProcessHits(), XrayFluoSD(), and ~XrayFluoSD().
XrayFluoSensorHitsCollection* XrayFluoSD::HPGeCollection private
Definition at line 76 of file XrayFluoSD.hh.
View newest version in sPHENIX GitHub at line 76 of file XrayFluoSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
XrayFluoMercuryDetectorConstruction* XrayFluoSD::mercuryDetector private
Definition at line 79 of file XrayFluoSD.hh.
View newest version in sPHENIX GitHub at line 79 of file XrayFluoSD.hh
Referenced by Initialize(), ProcessHits(), and XrayFluoSD().
XrayFluoPlaneDetectorConstruction* XrayFluoSD::planeDetector private
Definition at line 78 of file XrayFluoSD.hh.
View newest version in sPHENIX GitHub at line 78 of file XrayFluoSD.hh
Referenced by Initialize(), ProcessHits(), and XrayFluoSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoSD.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoSD.cc