ECCE @ EIC Software: DMXRunAction Class Reference
DMXRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXRunAction.hh>
Public Member Functions
DMXRunAction ()
~DMXRunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
void SetsavehitsFile (G4String val)
void SetsavepmtFile (G4String val)
void SetsavehistFile (G4String val)
G4String GetsavehitsFile () const
G4String GetsavepmtFile () const
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Member Functions
void Book ()
Private Attributes
G4String savehitsFile
G4String savepmtFile
G4String savehistFile
DMXRunActionMessenger * runMessenger
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 54 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file DMXRunAction.hh
Constructor & Destructor Documentation
DMXRunAction::DMXRunAction ()
Definition at line 58 of file DMXRunAction.cc.
View newest version in sPHENIX GitHub at line 58 of file DMXRunAction.cc
References runMessenger, savehistFile, savehitsFile, and savepmtFile.
DMXRunAction::~DMXRunAction ()
Definition at line 68 of file DMXRunAction.cc.
View newest version in sPHENIX GitHub at line 68 of file DMXRunAction.cc
References runMessenger.
Member Function Documentation
void DMXRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 77 of file DMXRunAction.cc.
View newest version in sPHENIX GitHub at line 77 of file DMXRunAction.cc
References Book(), G4cout, G4endl, G4Run::GetRunID(), and G4UserRunAction::IsMaster().
void DMXRunAction::Book () private
Definition at line 97 of file DMXRunAction.cc.
View newest version in sPHENIX GitHub at line 97 of file DMXRunAction.cc
References G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::FinishNtuple(), G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), savehistFile, G4VAnalysisManager::SetFirstHistoId(), and G4VAnalysisManager::SetFirstNtupleId().
Referenced by BeginOfRunAction().
void DMXRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 92 of file DMXRunAction.cc.
View newest version in sPHENIX GitHub at line 92 of file DMXRunAction.cc
G4String DMXRunAction::GetsavehitsFile () const inline
Definition at line 69 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file DMXRunAction.hh
References savehitsFile.
Referenced by DMXEventAction::writeScintHitsToFile().
G4String DMXRunAction::GetsavepmtFile () const inline
Definition at line 70 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 70 of file DMXRunAction.hh
References savepmtFile.
Referenced by DMXEventAction::writePmtHitsToFile().
void DMXRunAction::SetsavehistFile (G4String val) inline
Definition at line 67 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file DMXRunAction.hh
References savehistFile.
Referenced by DMXRunActionMessenger::SetNewValue().
void DMXRunAction::SetsavehitsFile (G4String val) inline
Definition at line 65 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file DMXRunAction.hh
References savehitsFile.
Referenced by DMXRunActionMessenger::SetNewValue().
void DMXRunAction::SetsavepmtFile (G4String val) inline
Definition at line 66 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file DMXRunAction.hh
References savepmtFile.
Referenced by DMXRunActionMessenger::SetNewValue().
Member Data Documentation
DMXRunActionMessenger* DMXRunAction::runMessenger private
Definition at line 80 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 80 of file DMXRunAction.hh
Referenced by DMXRunAction(), and ~DMXRunAction().
G4String DMXRunAction::savehistFile private
Definition at line 78 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 78 of file DMXRunAction.hh
Referenced by Book(), DMXRunAction(), and SetsavehistFile().
G4String DMXRunAction::savehitsFile private
Definition at line 76 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 76 of file DMXRunAction.hh
Referenced by DMXRunAction(), GetsavehitsFile(), and SetsavehitsFile().
G4String DMXRunAction::savepmtFile private
Definition at line 77 of file DMXRunAction.hh.
View newest version in sPHENIX GitHub at line 77 of file DMXRunAction.hh
Referenced by DMXRunAction(), GetsavepmtFile(), and SetsavepmtFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/src/DMXRunAction.cc