ECCE @ EIC Software: G4RDAugerTransition Class Reference
G4RDAugerTransition Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAugerTransition.hh>
Public Member Functions
G4RDAugerTransition (G4int finalShell, std::vector< G4int > transIds, const std::map< G4int, std::vector< G4int >, std::less< G4int > > *idMap, const std::map< G4int, G4DataVector, std::less< G4int > > *energyMap, const std::map< G4int, G4DataVector, std::less< G4int > > *probabilityMap)
~G4RDAugerTransition ()
const std::vector< G4int > * AugerOriginatingShellIds (G4int startShellId) const
const std::vector< G4int > * TransitionOriginatingShellIds () const
const G4DataVector * AugerTransitionEnergies (G4int startShellId) const
const G4DataVector * AugerTransitionProbabilities (G4int startShellId) const
G4int FinalShellId () const
G4int AugerOriginatingShellId (G4int index, G4int startShellId) const
G4double AugerTransitionEnergy (G4int index, G4int startShellId) const
G4double AugerTransitionProbability (G4int index, G4int startShellId) const
G4int TransitionOriginatingShellId (G4int index) const
Private Attributes
G4int finalShellId
std::map< G4int, std::vector
< G4int >, std::less< G4int > > augerOriginatingShellIdsMap
std::map< G4int, G4DataVector,
std::less< G4int > > augerTransitionEnergiesMap
std::map< G4int, G4DataVector,
std::less< G4int > > augerTransitionProbabilitiesMap
std::vector< G4int > transitionOriginatingShellIds
Detailed Description
Definition at line 54 of file G4RDAugerTransition.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RDAugerTransition.hh
Constructor & Destructor Documentation
G4RDAugerTransition::G4RDAugerTransition (G4int finalShell, std::vector< G4int > transIds, const std::map< G4int, std::vector< G4int >, std::less< G4int > > * idMap, const std::map< G4int, G4DataVector, std::less< G4int > > * energyMap, const std::map< G4int, G4DataVector, std::less< G4int > > * probabilityMap)
Definition at line 44 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 44 of file G4RDAugerTransition.cc
References augerOriginatingShellIdsMap, augerTransitionEnergiesMap, augerTransitionProbabilitiesMap, finalShellId, and transitionOriginatingShellIds.
G4RDAugerTransition::~G4RDAugerTransition ()
Definition at line 58 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RDAugerTransition.cc
Member Function Documentation
G4int G4RDAugerTransition::AugerOriginatingShellId (G4int index, G4int startShellId) const
Definition at line 122 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 122 of file G4RDAugerTransition.cc
References AugerOriginatingShellIds(), n, and pos().
const std::vector< G4int > * G4RDAugerTransition::AugerOriginatingShellIds (G4int startShellId) const
Definition at line 66 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 66 of file G4RDAugerTransition.cc
References augerOriginatingShellIdsMap, G4cout, and G4endl.
Referenced by AugerOriginatingShellId().
const G4DataVector * G4RDAugerTransition::AugerTransitionEnergies (G4int startShellId) const
Definition at line 95 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 95 of file G4RDAugerTransition.cc
References augerTransitionEnergiesMap.
Referenced by AugerTransitionEnergy().
G4double G4RDAugerTransition::AugerTransitionEnergy (G4int index, G4int startShellId) const
Definition at line 135 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 135 of file G4RDAugerTransition.cc
References AugerTransitionEnergies(), energy, and pos().
Referenced by G4RDAtomicDeexcitation::GenerateAuger().
const G4DataVector * G4RDAugerTransition::AugerTransitionProbabilities (G4int startShellId) const
Definition at line 107 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 107 of file G4RDAugerTransition.cc
References augerTransitionProbabilitiesMap.
Referenced by AugerTransitionProbability(), and G4RDAtomicDeexcitation::GenerateAuger().
G4double G4RDAugerTransition::AugerTransitionProbability (G4int index, G4int startShellId) const
Definition at line 149 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 149 of file G4RDAugerTransition.cc
References AugerTransitionProbabilities(), and pos().
Referenced by G4RDAtomicDeexcitation::GenerateAuger().
G4int G4RDAugerTransition::FinalShellId () const
Definition at line 114 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 114 of file G4RDAugerTransition.cc
References finalShellId.
Referenced by G4RDAtomicDeexcitation::GenerateAuger().
G4int G4RDAugerTransition::TransitionOriginatingShellId (G4int index) const
Definition at line 162 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 162 of file G4RDAugerTransition.cc
References transitionOriginatingShellIds.
const std::vector< G4int > * G4RDAugerTransition::TransitionOriginatingShellIds () const
Definition at line 85 of file G4RDAugerTransition.cc.
View newest version in sPHENIX GitHub at line 85 of file G4RDAugerTransition.cc
References transitionOriginatingShellIds.
Referenced by G4RDAtomicDeexcitation::GenerateAuger().
Member Data Documentation
std::map<G4int,std::vector<G4int>,std::less<G4int> > G4RDAugerTransition::augerOriginatingShellIdsMap private
Definition at line 115 of file G4RDAugerTransition.hh.
View newest version in sPHENIX GitHub at line 115 of file G4RDAugerTransition.hh
Referenced by AugerOriginatingShellIds(), and G4RDAugerTransition().
std::map<G4int,G4DataVector,std::less<G4int> > G4RDAugerTransition::augerTransitionEnergiesMap private
Definition at line 116 of file G4RDAugerTransition.hh.
View newest version in sPHENIX GitHub at line 116 of file G4RDAugerTransition.hh
Referenced by AugerTransitionEnergies(), and G4RDAugerTransition().
std::map<G4int,G4DataVector,std::less<G4int> > G4RDAugerTransition::augerTransitionProbabilitiesMap private
Definition at line 117 of file G4RDAugerTransition.hh.
View newest version in sPHENIX GitHub at line 117 of file G4RDAugerTransition.hh
Referenced by AugerTransitionProbabilities(), and G4RDAugerTransition().
G4int G4RDAugerTransition::finalShellId private
Definition at line 114 of file G4RDAugerTransition.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RDAugerTransition.hh
Referenced by FinalShellId(), and G4RDAugerTransition().
std::vector<G4int> G4RDAugerTransition::transitionOriginatingShellIds private
Definition at line 118 of file G4RDAugerTransition.hh.
View newest version in sPHENIX GitHub at line 118 of file G4RDAugerTransition.hh
Referenced by G4RDAugerTransition(), TransitionOriginatingShellId(), and TransitionOriginatingShellIds().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAugerTransition.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDAugerTransition.cc