ECCE @ EIC Software: G4UImessenger Class Reference
G4UImessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UImessenger.hh>
Inherited by B2aDetectorMessenger, B2bDetectorMessenger, B2bDetectorMessenger, BrachyDetectorMessenger, BrachyPhysicsListMessenger, CCalPrimaryGeneratorMessenger, CexmcChargeExchangeReconstructorMessenger, CexmcEnergyDepositDigitizerMessenger, CexmcEventActionMessenger, CexmcParticleGunMessenger, CexmcPhysicsManagerMessenger, CexmcPrimaryGeneratorActionMessenger, CexmcProductionModelMessenger, CexmcReconstructorMessenger, CexmcRunManagerMessenger, CexmcScenePrimitivesMessenger, CexmcSensitiveDetectorMessenger, ClusteringAlgoMessenger, CML2Acc1Messenger, CML2Acc2Messenger, CML2AcceleratorConstructionMessenger, CML2AccSaturnMessenger, CML2MainMessenger, CML2Ph_FullWaterMessenger, CML2PhantomConstructionMessenger, CML2PrimaryGenerationActionMessenger, CML2RunActionMessenger, Collimator100BeamLineMessenger, Collimator40BeamLineMessenger, Collimator50BeamLineMessenger, Collimator60BeamLineMessenger, Collimator70BeamLineMessenger, Collimator80BeamLineMessenger, DetectorConstructionMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DicomIntersectVolume, DMXDetectorMessenger, DMXEventActionMessenger, DMXParticleSourceMessenger, DMXRunActionMessenger, DMXStackingActionMessenger, DMXSteppingActionMessenger, doiPETAnalysisMessenger, doiPETDetectorConstructionMessenger, ElectronBenchmarkDetectorMessenger, EventActionMessenger, EventActionMessenger, EventActionMessenger, EventActionMessenger, ExErrorDetectorMessenger, ExGflashMessenger, ExN02DetectorMessenger, ExN03DetectorMessenger, ExN04PrimaryGeneratorMessenger, ExN04PrimaryGeneratorMessenger, ExN04StackingActionMessenger, ExN04StackingActionMessenger, ExP01DetectorMessenger, F01DetectorMessenger, F01FieldMessenger, F01PrimaryGeneratorMessenger, F02DetectorMessenger, F02FieldMessenger, F02PrimaryGeneratorMessenger, F03DetectorMessenger, F03FieldMessenger, F03PrimaryGeneratorMessenger, F04DetectorMessenger, F04EventActionMessenger, F04FieldMessenger, F04PhysicsListMessenger, F04PrimaryGeneratorMessenger, F04RunActionMessenger, F04SteppingActionMessenger, FCALTBEventActionMessenger, Fun4AllMessenger, G02DetectorMessenger, G03DetectorMessenger, G4AdjointPhysicsMessenger, G4AdjointSimMessenger, G4AnalysisMessenger, G4ASCIITreeMessenger, G4BlineTracerMessenger, G4CascadeParamMessenger, G4DecayTableMessenger, G4DeexParametersMessenger, G4DMmessenger, G4DNAChemistryManager, G4EmExtraParametersMessenger, G4EmLowEParametersMessenger, G4EmMessenger, G4EmParametersMessenger, G4ErrorMessenger, G4EvManMessenger, G4FastSimulationMessenger, G4FileMessenger, G4GDMLMessenger, G4GeneralParticleSourceMessenger, G4GenericMessenger, G4GeometryMessenger, G4GlobalMagFieldMessenger, G4GMocrenMessenger, G4H1Messenger, G4H2Messenger, G4H3Messenger, G4HadronicEPTestMessenger, G4HepRepMessenger, G4HnMessenger, G4HumanPhantomMessenger, G4INCLXXInterfaceMessenger, G4InteractorMessenger, G4LocalThreadCoutMessenger, G4MatScanMessenger, G4ModelCmdCreateContextDir< M >, G4MoleculeGunMessenger, G4MoleculeShootMessenger, G4MonopoleFieldMessenger, G4MonopolePhysicsMessenger, G4MPImessenger, G4NeutronKillerMessenger, G4NistMessenger, G4NtupleMessenger, G4NuclideTableMessenger, G4OpenGLViewerMessenger, G4OpticalPhysicsMessenger, G4P1Messenger, G4P2Messenger, G4ParticleGunMessenger, G4ParticleHPMessenger, G4ParticleMessenger, G4ParticlePropertyMessenger, G4PersistencyCenterMessenger, G4PhysListFactoryMessenger, G4PlotMessenger, G4PolarizationMessenger, G4ProcessManagerMessenger, G4ProcessTableMessenger, G4ProductionCutsTableMessenger, G4Pythia6DecayerMessenger, G4Pythia6DecayerMessenger, G4RadioactivationMessenger, G4RadioactiveDecayBaseMessenger, G4RadioactiveDecaymessenger, G4ReactionTableMessenger, G4RTMessenger, G4RunMessenger, G4SchedulerMessenger, G4ScoreQuantityMessenger, G4ScoringMessenger, G4SDmessenger, G4StackingMessenger, G4TBFieldMessenger, G4tgrMessenger, G4TrackingMessenger, G4TScoreNtupleWriterMessenger< T >, G4UCNBoundaryProcessMessenger, G4UIcontrolMessenger, G4UnitsMessenger, G4UserPhysicsListMessenger, G4VisCommandListManagerList< Manager >, G4VisCommandListManagerSelect< Manager >, G4VisCommandManagerMode< Manager >, G4VITSteppingVerbose [private], G4VModelCommand< T >, G4VModelCommand< M >, G4VVisCommand, GammaKnifeDetectorMessenger, GammaKnifeMessenger, GammaKnifePhysicsListMessenger, GammaRayTelAnalysisMessenger, GammaRayTelDetectorMessenger, GammaRayTelDigitizerMessenger, GammaRayTelPhysicsListMessenger, GammaRayTelPrimaryGeneratorMessenger, GB03DetectorMessenger, GFlashShowerModelMessenger, H02PrimaryGeneratorMessenger, HadrontherapyAnalysisFileMessenger, HadrontherapyDetectorMessenger, HadrontherapyEventActionMessenger, HadrontherapyGeometryMessenger, HadrontherapyModulatorMessenger, HadrontherapyParameterMessenger, HadrontherapyPhysicsListMessenger, HadrontherapyPrimaryGeneratorMessenger, HadrontherapyStepMaxMessenger, HepMCG4AsciiReaderMessenger, HepMCG4AsciiReaderMessenger, HepMCG4PythiaMessenger, HepMCG4PythiaMessenger, HistoManagerMessenger, HistoMessenger, HistoMessenger, HistoMessenger, HistoMessenger, IORTDetectorMessenger, IORTEventActionMessenger, IORTGeometryMessenger, IORTPhysicsListMessenger, IORTPrimaryGeneratorMessenger, IORTStepMaxMessenger, LaserDrivenBeamLineMessenger, LXeDetectorMessenger, LXeEventMessenger, LXeSteppingMessenger, ML2PhysicsListMessenger, ML2StepMaxMessenger, MyKleinNishinaMessenger, NeutronHPMessenger, NeutronHPMessenger, NeutronHPMessenger, NeutronHPMessenger, NeutronHPMessenger, OpNovicePrimaryGeneratorMessenger, PassiveCarbonBeamLineMessenger, PassiveProtonBeamLineMessenger, PerspectiveVisActionMessenger, PhysicsList, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, PrimaryKiller, PrimaryKiller, RE01PrimaryGeneratorMessenger, RE05PrimaryGeneratorMessenger, RE05StackingActionMessenger, RE06DetectorMessenger, RMC01AnalysisManagerMessenger, RMC01DetectorMessenger, RunActionMessenger, RunActionMessenger, RunActionMessenger, RunActionMessenger, RunMessenger, RunMessenger, StackingMessenger, StackingMessenger, StackingMessenger, StackingMessenger, StackingMessenger, StackingMessenger, StackingMessenger, STCyclotronDetectorMessenger, STCyclotronPrimaryGeneratorActionMessenger, STCyclotronRunActionMessenger, StepLimiterMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, StepMaxMessenger, TrackingMessenger, TrentoPassiveProtonBeamLineMessenger, UltraDetectorMessenger, WLSDetectorMessenger, WLSEventActionMessenger, WLSPrimaryGeneratorMessenger, WLSRunActionMessenger, WLSSteppingActionMessenger, XrayFluoAnalysisMessenger, XrayFluoDetectorMessenger, XrayFluoEventActionMessenger, XrayFluoMercuryDetectorMessenger, XrayFluoMercuryPrimaryGeneratorMessenger, XrayFluoMercuryPrimaryGeneratorMessenger, XrayFluoPhysicsListMessenger, XrayFluoPlaneDetectorMessenger, XrayFluoPlanePrimaryGeneratorMessenger, XrayFluoPrimaryGeneratorMessenger, and XrayFluoStepMaxMessenger.
Public Member Functions
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Member Functions
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 46 of file G4UImessenger.hh.
View newest version in sPHENIX GitHub at line 46 of file G4UImessenger.hh
Constructor & Destructor Documentation
G4UImessenger::G4UImessenger ()
Definition at line 37 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 37 of file G4UImessenger.cc
G4UImessenger::G4UImessenger (const G4String & path, const G4String & dsc, G4bool commandsToBeBroadcasted = true)
Definition at line 42 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4UImessenger.cc
References CreateDirectory().
G4UImessenger::~G4UImessenger () virtual
Definition at line 49 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 49 of file G4UImessenger.cc
References baseDir.
Member Function Documentation
void G4UImessenger::AddUIcommand (G4UIcommand * newCommand) protected
Definition at line 126 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 126 of file G4UImessenger.cc
References G4cerr, G4endl, and G4UIcommand::GetCommandPath().
G4String G4UImessenger::BtoS (G4bool b) protected
Definition at line 81 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 81 of file G4UImessenger.cc
G4bool G4UImessenger::CommandsShouldBeInMaster () const inline
Definition at line 95 of file G4UImessenger.hh.
View newest version in sPHENIX GitHub at line 95 of file G4UImessenger.hh
References commandsShouldBeInMaster.
template<typename T > T * G4UImessenger::CreateCommand (const G4String & cname, const G4String & dsc) protected
Definition at line 100 of file G4UImessenger.hh.
View newest version in sPHENIX GitHub at line 100 of file G4UImessenger.hh
References baseDirName, and T.
void G4UImessenger::CreateDirectory (const G4String & path, const G4String & dsc, G4bool commandsToBeBroadcasted = true) protected
Definition at line 132 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 132 of file G4UImessenger.cc
References G4String::append(), baseDir, baseDirName, G4UImanager::GetUIpointer(), and gammaraytel::tree.
Referenced by G4MoleculeShootMessenger::G4MoleculeShootMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), and G4UImessenger().
G4String G4UImessenger::DtoS (G4double a) protected
Definition at line 74 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 74 of file G4UImessenger.cc
References a.
Referenced by G4ScoreQuantityMessenger::FilterCommands(), and G4UIcontrolMessenger::SetNewValue().
G4String G4UImessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented in G4VisCommandSceneAddVolume, G4VisCommandSceneAddUserAction, G4VisCommandSceneAddTrajectories, G4VisCommandSceneAddText2D, G4VisCommandSceneAddText, G4VisCommandSceneAddScale, G4VisCommandSceneAddPSHits, G4VisCommandSceneAddMagneticField, G4VisCommandViewerZoom, G4VisCommandViewerUpdate, G4VisCommandSceneAddLogo2D, G4VisCommandViewerSelect, G4VisCommandSceneAddLogo, G4VisCommandViewerScale, G4VisCommandGeometrySetVisibility, G4VisCommandSceneAddLogicalVolume, G4VisCommandViewerSave, G4VisCommandGeometrySetLineWidth, G4VisCommandViewerRebuild, G4VisCommandGeometrySetLineStyle, G4VisCommandSceneAddLine2D, G4VisCommandViewerRefresh, G4VisCommandGeometrySetForceWireframe, G4VisCommandViewerReset, G4VisCommandSceneAddLine, G4VisCommandGeometrySetForceLineSegmentsPerCircle, G4VisCommandViewerPan, G4VisCommandSceneAddHits, G4VisCommandGeometrySetForceSolid, G4VisCommandViewerList, G4VisCommandSceneAddGhosts, G4VisCommandViewerInterpolate, G4VisCommandSceneAddGPS, G4VisCommandGeometrySetForceAuxEdgeVisible, G4VisCommandViewerFlush, G4VisCommandGeometrySetDaughtersInvisible, G4VisCommandSceneAddFrame, G4VisCommandViewerDolly, G4VisCommandGeometrySetColour, G4VisCommandSceneAddElectricField, G4VisCommandManagerMode< Manager >, G4VisCommandViewerCreate, G4VisCommandSceneAddExtent, G4VisCommandViewerCopyViewFrom, G4VisCommandViewerColourByDensity, G4VisCommandSceneShowExtents, G4GeneralParticleSourceMessenger, G4VisCommandSetVolumeForField, G4VisCommandSceneAddEventID, G4VisCommandViewerClone, G4VisCommandSceneSelect, G4VisCommandSetTouchable, G4VisCommandSceneAddDigis, G4VITSteppingVerbose, G4VisCommandViewerClearVisAttributesModifiers, G4VisCommandListManagerSelect< Manager >, G4VisCommandSceneNotifyHandlers, G4VisCommandSetTextSize, G4VisCommandVerbose, G4DNAChemistryManager, G4VisCommandViewerClearTransients, G4VisCommandSceneList, G4VisCommandSetTextLayout, G4VisCommandReviewKeptEvents, G4ParticleMessenger, G4MoleculeGunMessenger, G4VisCommandViewerClearCutawayPlanes, G4VisCommandSceneAddDate, G4VisCommandSceneEndOfRunAction, G4VisCommandSetTextColour, G4VisCommandList, G4UserPhysicsListMessenger, G4VisCommandViewerClear, G4UIcontrolMessenger, G4VisCommandSceneAddAxes, G4ProcessManagerMessenger, G4VisCommandSceneEndOfEventAction, G4VisCommandSetLineWidth, G4VisCommandSceneHandlerSelect, G4ParticlePropertyMessenger, G4ProductionCutsTableMessenger, G4RunMessenger, G4DecayTableMessenger, G4SchedulerMessenger, G4VisCommandViewerChangeCutawayPlane, G4ScoringMessenger, G4MoleculeShootMessenger, G4ProcessTableMessenger, G4VisCommandSetExtentForField, G4ScoreQuantityMessenger, G4PolarizationMessenger, G4VisCommandEnable, G4VisCommandGeometryRestore, G4VisCommandSceneCreate, G4VisCommandSceneHandlerList, G4TrackingMessenger, HepMCG4PythiaMessenger, HepMCG4PythiaMessenger, GFlashShowerModelMessenger, G4VisCommandSceneAddArrow2D, G4ParticleGunMessenger, G4PersistencyCenterMessenger, G4GeometryMessenger, G4VisCommandViewerCentreOn, G4VisCommandSetColour, G4tgrMessenger, G4RTMessenger, G4VisCommandDrawOnlyToBeKeptEvents, G4VisCommandGeometryList, G4VModelCommand< T >, G4VModelCommand< M >, G4VisCommandModelCreate< Factory >, G4VisCommandSceneActivateModel, G4VisCommandSceneHandlerCreate, G4VisCommandViewerDefaultStyle, DetectorConstructionMessenger, G4EvManMessenger, G4GenericMessenger, G4MatScanMessenger, G4VisCommandListManagerList< Manager >, ExN04PrimaryGeneratorMessenger, G4MPImessenger, G4GMocrenMessenger, H02PrimaryGeneratorMessenger, RE06DetectorMessenger, G4VisCommandSceneAddArrow, G4ASCIITreeMessenger, GB03DetectorMessenger, ExN04PrimaryGeneratorMessenger, ExN04StackingActionMessenger, RE01PrimaryGeneratorMessenger, RE05PrimaryGeneratorMessenger, RE05StackingActionMessenger, G4VisCommandsViewerSet, HepMCG4AsciiReaderMessenger, HepMCG4AsciiReaderMessenger, G4VisCommandViewerAddCutawayPlane, ExN04StackingActionMessenger, G4HepRepMessenger, G4VisCommandSetArrow3DLineSegmentsPerCircle, G4VisCommandsTouchableSet, G4VisCommandAbortReviewKeptEvents, G4VisCommandSceneHandlerAttach, G4VisCommandsTouchable, and G4VisCommandViewerDefaultHiddenEdge.
Definition at line 54 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UImessenger.cc
Referenced by G4UIcommand::DoIt(), and G4UIcommand::GetCurrentValue().
G4String G4UImessenger::ItoS (G4int i) protected
Definition at line 67 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 67 of file G4UImessenger.cc
Referenced by G4ParticleGunMessenger::GetCurrentValue().
G4bool G4UImessenger::operator== (const G4UImessenger & messenger) const
Definition at line 63 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 63 of file G4UImessenger.cc
void G4UImessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented in G4ModelCmdApplyString< M >, G4ModelCmdApplyInteger< M >, G4VisCommandSceneAddVolume, G4VisCommandSceneAddUserAction, G4ModelCmdApplyDoubleAndUnit< M >, G4VisCommandSceneAddTrajectories, G4VisCommandSceneAddText2D, G4VisCommandSceneAddText, G4VisCommandSceneAddScale, G4ModelCmdApplyDouble< M >, G4VisCommandSceneAddPSHits, G4VisCommandSceneAddMagneticField, G4VisCommandViewerZoom, G4VisCommandViewerUpdate, G4VisCommandSceneAddLogo2D, G4ModelCmdApplyNull< M >, G4VisCommandViewerSelect, G4VisCommandSceneAddLogo, G4VisCommandViewerScale, G4VisCommandGeometrySetVisibility, G4VisCommandSceneAddLogicalVolume, G4VisCommandViewerSave, G4VisCommandGeometrySetLineWidth, G4VisCommandViewerRebuild, G4VisCommandGeometrySetLineStyle, G4VisCommandSceneAddLine2D, G4ModelCmdApplyBool< M >, G4VisCommandViewerRefresh, G4VisCommandGeometrySetForceWireframe, G4VisCommandViewerReset, G4VisCommandSceneAddLine, G4VisCommandGeometrySetForceLineSegmentsPerCircle, G4VisCommandViewerPan, G4VisCommandSceneAddHits, G4VisCommandGeometrySetForceSolid, G4VisCommandViewerList, G4VisCommandSceneAddGhosts, G4VisCommandViewerInterpolate, G4VisCommandSceneAddGPS, G4VisCommandGeometrySetForceAuxEdgeVisible, G4VisCommandViewerFlush, G4VisCommandGeometrySetDaughtersInvisible, G4VisCommandSceneAddFrame, G4VisCommandViewerDolly, G4VisCommandGeometrySetColour, G4VisCommandSceneAddElectricField, G4VisCommandManagerMode< Manager >, G4VisCommandViewerCreate, G4ModelCmdApplyColour< M >, G4VisCommandSceneAddExtent, G4VisCommandViewerCopyViewFrom, G4VisCommandViewerColourByDensity, G4VisCommandSceneShowExtents, G4VisCommandSetVolumeForField, G4AdjointSimMessenger, G4GeneralParticleSourceMessenger, G4VisCommandSceneAddEventID, G4VisCommandViewerClone, G4VisCommandSceneSelect, G4VisCommandSetTouchable, G4VisCommandSceneAddDigis, G4VisCommandViewerClearVisAttributesModifiers, G4VisCommandListManagerSelect< Manager >, G4VITSteppingVerbose, G4VisCommandSceneNotifyHandlers, G4VisCommandSetTextSize, G4VisCommandVerbose, G4VisCommandViewerClearTransients, G4DNAChemistryManager, G4VisCommandSceneList, G4VisCommandSetTextLayout, G4VisCommandReviewKeptEvents, G4ParticleMessenger, G4VisCommandViewerClearCutawayPlanes, G4MoleculeGunMessenger, G4VisCommandSceneAddDate, G4VisCommandSceneEndOfRunAction, G4VisCommandSpecify, G4VisCommandSetTextColour, PrimaryKiller, PrimaryKiller, G4VisCommandList, G4RadioactiveDecaymessenger, G4UserPhysicsListMessenger, G4NistMessenger, G4VisCommandViewerClear, G4VisCommandSceneAddAxes, G4UIcontrolMessenger, G4VisCommandOpen, G4VisCommandSceneEndOfEventAction, G4VisCommandSetLineWidth, G4VisCommandInitialize, G4VisCommandSceneHandlerSelect, G4ProcessManagerMessenger, DMXParticleSourceMessenger, G4ParticlePropertyMessenger, G4ProductionCutsTableMessenger, G4RunMessenger, CML2MainMessenger, G4DeexParametersMessenger, G4VisCommandViewerChangeCutawayPlane, DetectorMessenger, G4DecayTableMessenger, G4SchedulerMessenger, G4EmParametersMessenger, G4VisCommandDrawVolume, G4AnalysisMessenger, G4MoleculeShootMessenger, G4EmExtraParametersMessenger, G4EmLowEParametersMessenger, G4ProcessTableMessenger, DetectorMessenger, G4ScoringMessenger, G4OpticalPhysicsMessenger, G4VisCommandSetExtentForField, RMC01DetectorMessenger, G4UCNBoundaryProcessMessenger, CexmcEnergyDepositDigitizerMessenger, G4AdjointPhysicsMessenger, G4BlineTracerMessenger, G4VisCommandEnable, G4VisCommandGeometryRestore, G4VisCommandSceneCreate, G4VisCommandSceneHandlerList, CML2AcceleratorConstructionMessenger, CML2PhantomConstructionMessenger, PhysicsListMessenger, DetectorMessenger, PhysicsListMessenger, G4PolarizationMessenger, doiPETDetectorConstructionMessenger, RMC01AnalysisManagerMessenger, DetectorMessenger, G4ScoreQuantityMessenger, CexmcChargeExchangeReconstructorMessenger, CexmcParticleGunMessenger, CexmcReconstructorMessenger, CexmcRunManagerMessenger, CexmcScenePrimitivesMessenger, DetectorMessenger, DetectorMessenger, HistoManagerMessenger, PrimaryGeneratorMessenger, G4INCLXXInterfaceMessenger, G4TrackingMessenger, CexmcPrimaryGeneratorActionMessenger, CexmcProductionModelMessenger, CexmcSensitiveDetectorMessenger, PhysicsListMessenger, DetectorMessenger, PhysicsList, CexmcPhysicsManagerMessenger, ML2PhysicsListMessenger, HepMCG4PythiaMessenger, HepMCG4PythiaMessenger, G4RadioactiveDecayBaseMessenger, G4VisCommandSceneAddArrow2D, CexmcEventActionMessenger, doiPETAnalysisMessenger, GammaRayTelPrimaryGeneratorMessenger, CML2Acc2Messenger, CML2AccSaturnMessenger, CML2Ph_FullWaterMessenger, CML2PrimaryGenerationActionMessenger, XrayFluoAnalysisMessenger, StackingMessenger, GFlashShowerModelMessenger, GammaRayTelDetectorMessenger, HadrontherapyAnalysisFileMessenger, CML2Acc1Messenger, DMXDetectorMessenger, DMXEventActionMessenger, XrayFluoMercuryDetectorMessenger, XrayFluoPlaneDetectorMessenger, EventActionMessenger, EventActionMessenger, EventActionMessenger, StackingMessenger, G4ErrorMessenger, G4GlobalMagFieldMessenger, G4NuclideTableMessenger, G4VisCommandDrawLogicalVolume, G4VisCommandViewerCentreOn, IORTDetectorMessenger, IORTPhysicsListMessenger, ML2StepMaxMessenger, DMXRunActionMessenger, G02DetectorMessenger, G4ParticleGunMessenger, G4GDMLMessenger, G4EmMessenger, GammaRayTelDigitizerMessenger, IORTGeometryMessenger, CML2RunActionMessenger, DMXStackingActionMessenger, DMXSteppingActionMessenger, XrayFluoDetectorMessenger, WLSDetectorMessenger, G4GeometryMessenger, G4RadioactivationMessenger, G4FastSimulationMessenger, G4NeutronKillerMessenger, G4Pythia6DecayerMessenger, GammaRayTelAnalysisMessenger, Collimator100BeamLineMessenger, Collimator40BeamLineMessenger, Collimator50BeamLineMessenger, Collimator60BeamLineMessenger, Collimator70BeamLineMessenger, Collimator80BeamLineMessenger, RunMessenger, PhysicsListMessenger, EventActionMessenger, DetectorMessenger, G4PersistencyCenterMessenger, G4VisCommandSetColour, G4ModelCmdApplyStringColour< M >, G4TBFieldMessenger, IORTEventActionMessenger, IORTPrimaryGeneratorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, HistoMessenger, HistoMessenger, ExErrorDetectorMessenger, F01DetectorMessenger, F03DetectorMessenger, HistoMessenger, DetectorMessenger, WLSRunActionMessenger, G03DetectorMessenger, G4HadronicEPTestMessenger, G4CascadeParamMessenger, G4DMmessenger, G4RTMessenger, IORTStepMaxMessenger, XrayFluoMercuryPrimaryGeneratorMessenger, XrayFluoMercuryPrimaryGeneratorMessenger, B2aDetectorMessenger, B2bDetectorMessenger, DetectorMessenger, G4Pythia6DecayerMessenger, G4MonopoleFieldMessenger, F02DetectorMessenger, HistoMessenger, DicomIntersectVolume, DetectorMessenger, PhysicsListMessenger, B2bDetectorMessenger, G4H1Messenger, G4SDmessenger, G4TScoreNtupleWriterMessenger< T >, G4PhysListFactoryMessenger, G4VisCommandDrawOnlyToBeKeptEvents, G4VisCommandGeometryList, FCALTBEventActionMessenger, XrayFluoPlanePrimaryGeneratorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, F01FieldMessenger, F02FieldMessenger, F03FieldMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, PhysicsListMessenger, DetectorMessenger, PhysicsListMessenger, ExP01DetectorMessenger, DetectorMessenger, G4GenericMessenger, G4tgrMessenger, G4VisCommandModelCreate< Factory >, G4VisCommandSceneActivateModel, G4VisCommandSceneHandlerCreate, G4VisCommandViewerDefaultStyle, ExN03DetectorMessenger, XrayFluoEventActionMessenger, XrayFluoPrimaryGeneratorMessenger, PhysicsListMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, DetectorMessenger, PhysicsListMessenger, G4MonopolePhysicsMessenger, ClusteringAlgoMessenger, RunActionMessenger, DetectorMessenger, DetectorMessenger, OpNovicePrimaryGeneratorMessenger, PrimaryGeneratorMessenger, DetectorMessenger, G4FileMessenger, G4UnitsMessenger, G4MatScanMessenger, HadrontherapyModulatorMessenger, PhysicsListMessenger, XrayFluoPhysicsListMessenger, DetectorMessenger, PhysicsListMessenger, PhysicsListMessenger, DetectorMessenger, DetectorMessenger, PhysicsListMessenger, RunActionMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, F04PhysicsListMessenger, DetectorMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, LXeDetectorMessenger, ExN02DetectorMessenger, ExGflashMessenger, DetectorMessenger, G4HnMessenger, G4PlotMessenger, G4LocalThreadCoutMessenger, G4VisCommandListManagerList< Manager >, BrachyDetectorMessenger, GammaRayTelPhysicsListMessenger, HadrontherapyPrimaryGeneratorMessenger, PhysicsListMessenger, PrimaryGeneratorMessenger, DetectorMessenger, PhysicsListMessenger, PrimaryGeneratorMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, PrimaryGeneratorMessenger, RunActionMessenger, PrimaryGeneratorMessenger, PhysicsListMessenger, DetectorConstructionMessenger, RunActionMessenger, F01PrimaryGeneratorMessenger, F02PrimaryGeneratorMessenger, F03PrimaryGeneratorMessenger, F04DetectorMessenger, F04FieldMessenger, F04RunActionMessenger, PrimaryGeneratorMessenger, PhysicsListMessenger, WLSPrimaryGeneratorMessenger, PhysicsListMessenger, PrimaryGeneratorMessenger, G4H2Messenger, G4H3Messenger, G4P1Messenger, G4P2Messenger, G4EvManMessenger, G4StackingMessenger, G4GMocrenMessenger, STCyclotronDetectorMessenger, StepMaxMessenger, StepMaxMessenger, PrimaryGeneratorMessenger, StepMaxMessenger, StackingMessenger, PrimaryGeneratorMessenger, StepMaxMessenger, PrimaryGeneratorMessenger, StepMaxMessenger, PrimaryGeneratorMessenger, RunMessenger, NeutronHPMessenger, NeutronHPMessenger, NeutronHPMessenger, StepMaxMessenger, NeutronHPMessenger, DetectorMessenger, DetectorMessenger, PrimaryGeneratorMessenger, PrimaryGeneratorMessenger, StepLimiterMessenger, WLSEventActionMessenger, WLSSteppingActionMessenger, NeutronHPMessenger, TrackingMessenger, G4NtupleMessenger, G4VisCommandSceneAddArrow, G4ASCIITreeMessenger, PhysicsListMessenger, CCalPrimaryGeneratorMessenger, GammaKnifePhysicsListMessenger, G4HumanPhantomMessenger, StepMaxMessenger, StepMaxMessenger, StackingMessenger, StepMaxMessenger, StepMaxMessenger, StackingMessenger, ExN04PrimaryGeneratorMessenger, StackingMessenger, DetectorMessenger, DetectorMessenger, StepMaxMessenger, ElectronBenchmarkDetectorMessenger, MyKleinNishinaMessenger, StackingMessenger, StepMaxMessenger, StepMaxMessenger, G4MPImessenger, StepMaxMessenger, G4VisCommandDrawView, G4VisCommandsViewerSet, DetectorMessenger, PhysicsListMessenger, PrimaryGeneratorMessenger, HadrontherapyPhysicsListMessenger, XrayFluoStepMaxMessenger, H02PrimaryGeneratorMessenger, F04EventActionMessenger, F04PrimaryGeneratorMessenger, PhysicsListMessenger, PhysicsListMessenger, RE06DetectorMessenger, G4VisCommandViewerAddCutawayPlane, HadrontherapyDetectorMessenger, DetectorMessenger, GB03DetectorMessenger, PhysicsListMessenger, PhysicsListMessenger, PhysicsListMessenger, LXeEventMessenger, ExN04PrimaryGeneratorMessenger, ExN04StackingActionMessenger, RE01PrimaryGeneratorMessenger, RE05PrimaryGeneratorMessenger, RE05StackingActionMessenger, GammaKnifeMessenger, HadrontherapyGeometryMessenger, TrentoPassiveProtonBeamLineMessenger, LaserDrivenBeamLineMessenger, PassiveCarbonBeamLineMessenger, PassiveProtonBeamLineMessenger, HepMCG4AsciiReaderMessenger, HepMCG4AsciiReaderMessenger, DetectorMessenger, StepMaxMessenger, G4ReactionTableMessenger, G4HepRepMessenger, G4OpenGLViewerMessenger, GammaKnifeDetectorMessenger, HadrontherapyEventActionMessenger, HadrontherapyParameterMessenger, PrimaryGeneratorMessenger, ExN04StackingActionMessenger, F04SteppingActionMessenger, LXeSteppingMessenger, G4VisCommandSetArrow3DLineSegmentsPerCircle, G4VisCommandsTouchableSet, HadrontherapyStepMaxMessenger, STCyclotronPrimaryGeneratorActionMessenger, STCyclotronRunActionMessenger, UltraDetectorMessenger, BrachyPhysicsListMessenger, PerspectiveVisActionMessenger, G4VisCommandAbortReviewKeptEvents, G4VisCommandSceneHandlerAttach, G4VisCommandsTouchable, G4ParticleHPMessenger, G4VisCommandViewerDefaultHiddenEdge, G4InteractorMessenger, G4VisCommandDrawTree, and Fun4AllMessenger.
Definition at line 60 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 60 of file G4UImessenger.cc
Referenced by G4UIcommand::DoIt().
G4bool G4UImessenger::StoB (G4String s) protected
Definition at line 115 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 115 of file G4UImessenger.cc
References G4String::toUpper(), and v.
Referenced by G4LocalThreadCoutMessenger::SetNewValue(), G4CascadeParamMessenger::SetNewValue(), and G4ScoreQuantityMessenger::SetNewValue().
G4double G4UImessenger::StoD (G4String s) protected
Definition at line 106 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 106 of file G4UImessenger.cc
References t.
Referenced by G4ScoreQuantityMessenger::FParticleWithEnergyCommand(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4MatScanMessenger::SetNewValue(), G4ScoreQuantityMessenger::SetNewValue(), G4PolarizationMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
G4int G4UImessenger::StoI (G4String s) protected
Definition at line 88 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 88 of file G4UImessenger.cc
References t.
Referenced by G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4ScoringMessenger::MeshBinCommand(), G4GMocrenMessenger::SetNewValue(), G4LocalThreadCoutMessenger::SetNewValue(), G4MatScanMessenger::SetNewValue(), G4ScoreQuantityMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), and G4UIcontrolMessenger::SetNewValue().
G4long G4UImessenger::StoL (G4String s) protected
Definition at line 97 of file G4UImessenger.cc.
View newest version in sPHENIX GitHub at line 97 of file G4UImessenger.cc
References t.
Referenced by G4RunMessenger::SetNewValue().
Member Data Documentation
G4UIdirectory* G4UImessenger::baseDir protected
Definition at line 85 of file G4UImessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4UImessenger.hh
Referenced by CreateDirectory(), and ~G4UImessenger().
G4String G4UImessenger::baseDirName protected
Definition at line 86 of file G4UImessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4UImessenger.hh
Referenced by CreateCommand(), and CreateDirectory().
G4bool G4UImessenger::commandsShouldBeInMaster protected
Definition at line 93 of file G4UImessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4UImessenger.hh
Referenced by CommandsShouldBeInMaster().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UImessenger.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UImessenger.cc