ECCE @ EIC Software: G4Generator2BS Class Reference
G4Generator2BS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4Generator2BS.hh>
Public Member Functions
G4Generator2BS (const G4String &name="")
virtual ~G4Generator2BS ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double out_energy, G4int Z, const G4Material *mat=nullptr)
void PrintGeneratorInformation () const
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Protected Member Functions
G4double RejectionFunction (G4double value) const
Private Member Functions
G4Generator2BS & operator= (const G4Generator2BS &right)=delete
G4Generator2BS (const G4Generator2BS &)=delete
Private Attributes
G4double fz
G4double ratio
G4double ratio1
G4double ratio2
G4double delta
G4Pow * g4pow
G4int nwarn
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 64 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 64 of file G4Generator2BS.hh
Constructor & Destructor Documentation
G4Generator2BS::G4Generator2BS (const G4String & name = "") explicit
Definition at line 63 of file G4Generator2BS.cc.
View newest version in sPHENIX GitHub at line 63 of file G4Generator2BS.cc
References g4pow, G4Pow::GetInstance(), and nwarn.
G4Generator2BS::~G4Generator2BS () virtual
Definition at line 71 of file G4Generator2BS.cc.
View newest version in sPHENIX GitHub at line 71 of file G4Generator2BS.cc
G4Generator2BS::G4Generator2BS (const G4Generator2BS &) private delete
Member Function Documentation
G4Generator2BS& G4Generator2BS::operator= (const G4Generator2BS & right) private delete
void G4Generator2BS::PrintGeneratorInformation () const
Definition at line 136 of file G4Generator2BS.cc.
View newest version in sPHENIX GitHub at line 136 of file G4Generator2BS.cc
References G4cout, and G4endl.
G4double G4Generator2BS::RejectionFunction (G4double value) const inline protected
Definition at line 101 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Generator2BS.hh
References delta, fz, G4Log(), ratio, ratio1, ratio2, x, y, and y2.
Referenced by SampleDirection().
G4ThreeVector & G4Generator2BS::SampleDirection (const G4DynamicParticle * dp, G4double out_energy, G4int Z, const G4Material * mat = nullptr) virtual
Implements G4VEmAngularDistribution.
Definition at line 74 of file G4Generator2BS.cc.
View newest version in sPHENIX GitHub at line 74 of file G4Generator2BS.cc
References source.hepunit::electron_mass_c2, energy, G4VEmAngularDistribution::fLocalDirection, fz, G4cout, G4endl, g4pow, G4UniformRand, G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetTotalEnergy(), max, MeV, nwarn, phi, ratio, ratio1, ratio2, RejectionFunction(), CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), twopi, y, ymax, and G4Pow::Z13().
Referenced by G4Generator2BN::SampleDirection().
Member Data Documentation
G4double G4Generator2BS::delta private
Definition at line 94 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4Generator2BS.hh
Referenced by RejectionFunction().
G4double G4Generator2BS::fz private
Definition at line 90 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4Generator2BS.hh
Referenced by RejectionFunction(), and SampleDirection().
G4Pow* G4Generator2BS::g4pow private
Definition at line 96 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Generator2BS.hh
Referenced by G4Generator2BS(), and SampleDirection().
G4int G4Generator2BS::nwarn private
Definition at line 97 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4Generator2BS.hh
Referenced by G4Generator2BS(), and SampleDirection().
G4double G4Generator2BS::ratio private
Definition at line 91 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4Generator2BS.hh
Referenced by RejectionFunction(), and SampleDirection().
G4double G4Generator2BS::ratio1 private
Definition at line 92 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4Generator2BS.hh
Referenced by RejectionFunction(), and SampleDirection().
G4double G4Generator2BS::ratio2 private
Definition at line 93 of file G4Generator2BS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4Generator2BS.hh
Referenced by RejectionFunction(), and SampleDirection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4Generator2BS.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4Generator2BS.cc