ECCE @ EIC Software: G4NuclearFermiDensity Class Reference
G4NuclearFermiDensity Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4NuclearFermiDensity.hh>
Public Member Functions
G4NuclearFermiDensity (G4int anA, G4int aZ)
~G4NuclearFermiDensity ()
G4double GetRelativeDensity (const G4ThreeVector &aPosition) const
G4double GetRadius (const G4double maxRelativeDenisty) const
G4double GetDeriv (const G4ThreeVector &aPosition) const
Public Member Functions inherited from G4VNuclearDensity
G4VNuclearDensity ()
virtual ~G4VNuclearDensity ()
G4double GetDensity (const G4ThreeVector &aPosition) const
Private Attributes
G4int theA
G4double theR
const G4double a
Additional Inherited Members
Protected Member Functions inherited from G4VNuclearDensity
void Setrho0 (G4double arho0)
G4double Getrho0 () const
Detailed Description
Definition at line 40 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 40 of file G4NuclearFermiDensity.hh
Constructor & Destructor Documentation
G4NuclearFermiDensity::G4NuclearFermiDensity (G4int anA, G4int aZ)
Definition at line 33 of file G4NuclearFermiDensity.cc.
View newest version in sPHENIX GitHub at line 33 of file G4NuclearFermiDensity.cc
References a, fermi, G4Pow::GetInstance(), pi, pi2, G4VNuclearDensity::Setrho0(), sqr(), theA, theR, and G4Pow::Z13().
G4NuclearFermiDensity::~G4NuclearFermiDensity ()
Definition at line 42 of file G4NuclearFermiDensity.cc.
View newest version in sPHENIX GitHub at line 42 of file G4NuclearFermiDensity.cc
Member Function Documentation
G4double G4NuclearFermiDensity::GetDeriv (const G4ThreeVector & aPosition) const inline virtual
Implements G4VNuclearDensity.
Definition at line 57 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 57 of file G4NuclearFermiDensity.hh
References a, G4Exp(), G4VNuclearDensity::GetDensity(), G4VNuclearDensity::Getrho0(), CLHEP::Hep3Vector::mag(), sqr(), and theR.
G4double G4NuclearFermiDensity::GetRadius (const G4double maxRelativeDenisty) const inline virtual
Implements G4VNuclearDensity.
Definition at line 51 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 51 of file G4NuclearFermiDensity.hh
References a, DBL_MAX, G4Exp(), G4Log(), and theR.
G4double G4NuclearFermiDensity::GetRelativeDensity (const G4ThreeVector & aPosition) const inline virtual
Implements G4VNuclearDensity.
Definition at line 46 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 46 of file G4NuclearFermiDensity.hh
References a, G4Exp(), CLHEP::Hep3Vector::mag(), and theR.
Member Data Documentation
const G4double G4NuclearFermiDensity::a private
Definition at line 67 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NuclearFermiDensity.hh
Referenced by G4NuclearFermiDensity(), GetDeriv(), GetRadius(), and GetRelativeDensity().
G4int G4NuclearFermiDensity::theA private
Definition at line 65 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 65 of file G4NuclearFermiDensity.hh
Referenced by G4NuclearFermiDensity().
G4double G4NuclearFermiDensity::theR private
Definition at line 66 of file G4NuclearFermiDensity.hh.
View newest version in sPHENIX GitHub at line 66 of file G4NuclearFermiDensity.hh
Referenced by G4NuclearFermiDensity(), GetDeriv(), GetRadius(), and GetRelativeDensity().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4NuclearFermiDensity.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4NuclearFermiDensity.cc