ECCE @ EIC Software: CML2ExpVoxels Class Reference
CML2ExpVoxels Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2ExpVoxels.hh>
Public Member Functions
CML2ExpVoxels (G4bool bHasExperimentalData, G4int saving_in_Selected_Voxels_every_events, G4int seed, G4String FileExperimentalData, G4String FileExperimentalDataOut)
~CML2ExpVoxels (void)
void add (G4ThreeVector pos, G4double depEnergy, G4double density)
void add (const G4Step *aStep)
std::vector< Svoxel > getVoxels ()
void setRecycling (int recycling)
void saveResults (void)
void resetNEventsInVoxels ()
G4int getMinNumberOfEvents ()
G4int getMaxNumberOfEvents ()
G4bool loadData ()
Private Member Functions
void saveHeader ()
void calculateNormalizedEd (std::vector< Svoxel > &vec_voxels)
Private Attributes
std::vector< Svoxel > vec_voxels
G4int * nVoxelsgeometry
G4ThreeVector minZone
G4ThreeVector maxZone
G4int nCurves
G4int * startCurve
G4int * stopCurve
G4double * chi2Factor
G4String headerText1
G4String headerText2
G4String fullFileIn
G4String fullFileOut
G4String seedName
G4String loopName
SGeneralData * generalData
G4int nParticle
G4int nTotalEvents
G4int saving_in_Selected_Voxels_every_events
G4int nRecycling
G4bool bHasExperimentalData
Detailed Description
Definition at line 51 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 51 of file ML2ExpVoxels.hh
Constructor & Destructor Documentation
CML2ExpVoxels::CML2ExpVoxels (G4bool bHasExperimentalData, G4int saving_in_Selected_Voxels_every_events, G4int seed, G4String FileExperimentalData, G4String FileExperimentalDataOut)
Definition at line 48 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 48 of file ML2ExpVoxels.cc
References a, bHasExperimentalData, fullFileIn, fullFileOut, maxZone, minZone, nParticle, nRecycling, nTotalEvents, saving_in_Selected_Voxels_every_events, seedName, and CLHEP::Hep3Vector::set().
CML2ExpVoxels::~CML2ExpVoxels (void)
Definition at line 70 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 70 of file ML2ExpVoxels.cc
References chi2Factor, nVoxelsgeometry, startCurve, and stopCurve.
Member Function Documentation
void CML2ExpVoxels::add (G4ThreeVector pos, G4double depEnergy, G4double density)
Referenced by CML2Convergence::add().
void CML2ExpVoxels::add (const G4Step * aStep)
Definition at line 169 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 169 of file ML2ExpVoxels.cc
References dir, dose, G4Material::GetDensity(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), int(), maxZone, minZone, nRecycling, nTotalEvents, nVoxelsgeometry, particle, pos(), saveResults(), saving_in_Selected_Voxels_every_events, and vec_voxels.
void CML2ExpVoxels::calculateNormalizedEd (std::vector< Svoxel > & vec_voxels) private
Definition at line 290 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 290 of file ML2ExpVoxels.cc
References chi2Factor, d2, n, nCurves, startCurve, stopCurve, and v.
Referenced by saveResults().
G4int CML2ExpVoxels::getMaxNumberOfEvents ()
Definition at line 239 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 239 of file ML2ExpVoxels.cc
References int(), n, nVoxelsgeometry, and vec_voxels.
Referenced by CML2Convergence::convergenceCriteria().
G4int CML2ExpVoxels::getMinNumberOfEvents ()
Definition at line 229 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 229 of file ML2ExpVoxels.cc
References int(), n, nEvents, and vec_voxels.
std::vector<Svoxel> CML2ExpVoxels::getVoxels () inline
Definition at line 59 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 59 of file ML2ExpVoxels.hh
References vec_voxels.
G4bool CML2ExpVoxels::loadData (void)
Definition at line 77 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 77 of file ML2ExpVoxels.cc
References a, bHasExperimentalData, chi2Factor, Svoxel::depEnergy, Svoxel::depEnergy2, Svoxel::depEnergyNorm, Svoxel::depEnergyNormError, expDose, Svoxel::expDose, fullFileIn, G4cout, G4endl, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), Svoxel::halfSize, headerText1, headerText2, in, joule, kg, maxZone, minZone, nCurves, Svoxel::nEvents, nVoxelsgeometry, Svoxel::pos, pos(), resetNEventsInVoxels(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), startCurve, stopCurve, vec_voxels, and Svoxel::volumeId.
Referenced by CML2Convergence::CML2Convergence().
void CML2ExpVoxels::resetNEventsInVoxels ()
Definition at line 163 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 163 of file ML2ExpVoxels.cc
References int(), nVoxelsgeometry, and vec_voxels.
Referenced by CML2Convergence::convergenceCriteria(), and loadData().
void CML2ExpVoxels::saveHeader () private
Definition at line 249 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 249 of file ML2ExpVoxels.cc
References chi2Factor, fullFileOut, G4endl, headerText1, nCurves, seedName, startCurve, and stopCurve.
Referenced by saveResults().
void CML2ExpVoxels::saveResults (void)
Definition at line 268 of file ML2ExpVoxels.cc.
View newest version in sPHENIX GitHub at line 268 of file ML2ExpVoxels.cc
References demo::app, calculateNormalizedEd(), fullFileOut, G4endl, int(), joule, kg, mm, nEvents, nTotalEvents, saveHeader(), seedName, and vec_voxels.
Referenced by add(), and CML2Convergence::saveResults().
void CML2ExpVoxels::setRecycling (int recycling) inline
Definition at line 60 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 60 of file ML2ExpVoxels.hh
References nRecycling.
Referenced by CML2Convergence::CML2Convergence().
Member Data Documentation
G4bool CML2ExpVoxels::bHasExperimentalData private
Definition at line 84 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2ExpVoxels.hh
Referenced by CML2ExpVoxels(), and loadData().
G4double* CML2ExpVoxels::chi2Factor private
Definition at line 78 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 78 of file ML2ExpVoxels.hh
Referenced by calculateNormalizedEd(), loadData(), saveHeader(), and ~CML2ExpVoxels().
G4String CML2ExpVoxels::fullFileIn private
Definition at line 79 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2ExpVoxels.hh
Referenced by CML2ExpVoxels(), and loadData().
G4String CML2ExpVoxels::fullFileOut private
Definition at line 79 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2ExpVoxels.hh
Referenced by CML2ExpVoxels(), saveHeader(), and saveResults().
SGeneralData* CML2ExpVoxels::generalData private
Definition at line 81 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 81 of file ML2ExpVoxels.hh
G4String CML2ExpVoxels::headerText1 private
Definition at line 79 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2ExpVoxels.hh
Referenced by loadData(), and saveHeader().
G4String CML2ExpVoxels::headerText2 private
Definition at line 79 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2ExpVoxels.hh
Referenced by loadData().
G4String CML2ExpVoxels::loopName private
Definition at line 80 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 80 of file ML2ExpVoxels.hh
G4ThreeVector CML2ExpVoxels::maxZone private
Definition at line 75 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2ExpVoxels.hh
Referenced by add(), CML2ExpVoxels(), and loadData().
G4ThreeVector CML2ExpVoxels::minZone private
Definition at line 75 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2ExpVoxels.hh
Referenced by add(), CML2ExpVoxels(), and loadData().
G4int CML2ExpVoxels::nCurves private
Definition at line 76 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 76 of file ML2ExpVoxels.hh
Referenced by calculateNormalizedEd(), loadData(), and saveHeader().
G4int CML2ExpVoxels::nParticle private
Definition at line 82 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 82 of file ML2ExpVoxels.hh
Referenced by CML2ExpVoxels().
G4int CML2ExpVoxels::nRecycling private
Definition at line 83 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 83 of file ML2ExpVoxels.hh
Referenced by add(), CML2ExpVoxels(), and setRecycling().
G4int CML2ExpVoxels::nTotalEvents private
Definition at line 83 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 83 of file ML2ExpVoxels.hh
Referenced by add(), CML2ExpVoxels(), and saveResults().
G4int* CML2ExpVoxels::nVoxelsgeometry private
Definition at line 74 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 74 of file ML2ExpVoxels.hh
Referenced by add(), getMaxNumberOfEvents(), loadData(), resetNEventsInVoxels(), and ~CML2ExpVoxels().
G4int CML2ExpVoxels::saving_in_Selected_Voxels_every_events private
Definition at line 83 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 83 of file ML2ExpVoxels.hh
Referenced by add(), and CML2ExpVoxels().
G4String CML2ExpVoxels::seedName private
Definition at line 80 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 80 of file ML2ExpVoxels.hh
Referenced by CML2ExpVoxels(), saveHeader(), and saveResults().
G4int* CML2ExpVoxels::startCurve private
Definition at line 77 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2ExpVoxels.hh
Referenced by calculateNormalizedEd(), loadData(), saveHeader(), and ~CML2ExpVoxels().
G4int * CML2ExpVoxels::stopCurve private
Definition at line 77 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2ExpVoxels.hh
Referenced by calculateNormalizedEd(), loadData(), saveHeader(), and ~CML2ExpVoxels().
std::vector<Svoxel> CML2ExpVoxels::vec_voxels private
Definition at line 73 of file ML2ExpVoxels.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2ExpVoxels.hh
Referenced by add(), getMaxNumberOfEvents(), getMinNumberOfEvents(), getVoxels(), loadData(), resetNEventsInVoxels(), and saveResults().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2ExpVoxels.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2ExpVoxels.cc