ECCE @ EIC Software: g4alt::G4PhysListFactory Class Reference
g4alt::G4PhysListFactory Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/G4PhysListFactoryAlt.hh>
Public Member Functions
G4PhysListFactory ()
~G4PhysListFactory ()
G4VModularPhysicsList * GetReferencePhysList (const G4String &)
G4VModularPhysicsList * ReferencePhysList ()
void SetDefaultReferencePhysList (const G4String &name="")
G4bool IsReferencePhysList (const G4String &)
const std::vector< G4String > & AvailablePhysLists () const
const std::vector< G4String > & AvailablePhysListsEM () const
void PrintAvailablePhysLists () const
void SetVerbose (G4int val)
G4int GetVerbose () const
void SetUnknownFatal (G4int val)
G4int GetUnknownFatal () const
Detailed Description
Definition at line 45 of file G4PhysListFactoryAlt.hh.
View newest version in sPHENIX GitHub at line 45 of file G4PhysListFactoryAlt.hh
Constructor & Destructor Documentation
G4PhysListFactory::G4PhysListFactory ()
Definition at line 43 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 43 of file G4PhysListFactoryAlt.cc
G4PhysListFactory::~G4PhysListFactory ()
Definition at line 47 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PhysListFactoryAlt.cc
Member Function Documentation
const std::vector< G4String > & G4PhysListFactory::AvailablePhysLists () const
Definition at line 73 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 73 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::AvailablePhysLists(), and G4PhysListRegistry::Instance().
const std::vector< G4String > & G4PhysListFactory::AvailablePhysListsEM () const
Definition at line 79 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::AvailablePhysListsEM(), and G4PhysListRegistry::Instance().
G4VModularPhysicsList * G4PhysListFactory::GetReferencePhysList (const G4String & name)
Definition at line 62 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::GetModularPhysicsList(), and G4PhysListRegistry::Instance().
Referenced by main().
G4int G4PhysListFactory::GetUnknownFatal () const
Definition at line 104 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 104 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::GetUnknownFatal(), and G4PhysListRegistry::Instance().
G4int G4PhysListFactory::GetVerbose () const
Definition at line 94 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 94 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::GetVerbose(), and G4PhysListRegistry::Instance().
G4bool G4PhysListFactory::IsReferencePhysList (const G4String & name)
Definition at line 67 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::Instance(), and G4PhysListRegistry::IsReferencePhysList().
void G4PhysListFactory::PrintAvailablePhysLists () const
Definition at line 84 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 84 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::Instance(), and G4PhysListRegistry::PrintAvailablePhysLists().
G4VModularPhysicsList * G4PhysListFactory::ReferencePhysList ()
Definition at line 56 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::GetModularPhysicsListFromEnv(), and G4PhysListRegistry::Instance().
Referenced by main().
void G4PhysListFactory::SetDefaultReferencePhysList (const G4String & name = "")
Definition at line 50 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::Instance(), and G4PhysListRegistry::SetUserDefaultPhysList().
Referenced by main().
void G4PhysListFactory::SetUnknownFatal (G4int val)
Definition at line 99 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 99 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::Instance(), and G4PhysListRegistry::SetUnknownFatal().
void G4PhysListFactory::SetVerbose (G4int val)
Definition at line 89 of file G4PhysListFactoryAlt.cc.
View newest version in sPHENIX GitHub at line 89 of file G4PhysListFactoryAlt.cc
References G4PhysListRegistry::Instance(), and G4PhysListRegistry::SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/G4PhysListFactoryAlt.hh
geant4/tree/geant4-10.6-release/source/physics_lists/lists/src/G4PhysListFactoryAlt.cc