ECCE @ EIC Software: G4PAIPhotData Class Reference
G4PAIPhotData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIPhotData.hh>
Public Member Functions
G4PAIPhotData (G4double tmin, G4double tmax, G4int verbose)
~G4PAIPhotData ()
void Initialise (const G4MaterialCutsCouple *, G4double cut, G4PAIPhotModel *)
G4double DEDXPerVolume (G4int coupleIndex, G4double scaledTkin, G4double cut) const
G4double CrossSectionPerVolume (G4int coupleIndex, G4double scaledTkin, G4double tcut, G4double tmax) const
G4double GetPlasmonRatio (G4int coupleIndex, G4double scaledTkin) const
G4double SampleAlongStepTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
G4double SampleAlongStepPhotonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
G4double SampleAlongStepPlasmonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
G4double SamplePostStepTransfer (G4int coupleIndex, G4double scaledTkin) const
G4double SamplePostStepPhotonTransfer (G4int coupleIndex, G4double scaledTkin) const
G4double SamplePostStepPlasmonTransfer (G4int coupleIndex, G4double scaledTkin) const
Private Member Functions
G4double GetEnergyTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4double GetEnergyPhotonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4double GetEnergyPlasmonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4PAIPhotData & operator= (const G4PAIPhotData &right)=delete
G4PAIPhotData (const G4PAIPhotData &)=delete
Private Attributes
G4int fTotBin
G4double fLowestKineticEnergy
G4double fHighestKineticEnergy
G4PhysicsLogVector * fParticleEnergyVector
G4PAIxSection fPAIxSection
G4SandiaTable fSandia
std::vector< G4PhysicsTable * > fPAIxscBank
std::vector< G4PhysicsTable * > fPAIphotonBank
std::vector< G4PhysicsTable * > fPAIplasmonBank
std::vector< G4PhysicsTable * > fPAIdEdxBank
std::vector< G4PhysicsLogVector * > fdEdxTable
std::vector< G4PhysicsLogVector * > fdNdxCutTable
std::vector< G4PhysicsLogVector * > fdNdxCutPhotonTable
std::vector< G4PhysicsLogVector * > fdNdxCutPlasmonTable
std::vector< G4PhysicsLogVector * > fdEdxCutTable
Detailed Description
Definition at line 65 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PAIPhotData.hh
Constructor & Destructor Documentation
G4PAIPhotData::G4PAIPhotData (G4double tmin, G4double tmax, G4int verbose) explicit
Definition at line 58 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PAIPhotData.cc
References G4cout, G4endl, GeV, keV, max, MeV, and TeV.
G4PAIPhotData::~G4PAIPhotData ()
Definition at line 93 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 93 of file G4PAIPhotData.cc
References n.
G4PAIPhotData::G4PAIPhotData (const G4PAIPhotData &) private delete
Member Function Documentation
G4double G4PAIPhotData::CrossSectionPerVolume (G4int coupleIndex, G4double scaledTkin, G4double tcut, G4double tmax) const
Definition at line 307 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 307 of file G4PAIPhotData.cc
References Acts::VectorHelpers::cross(), and one.
Referenced by G4PAIPhotModel::CrossSectionPerVolume().
G4double G4PAIPhotData::DEDXPerVolume (G4int coupleIndex, G4double scaledTkin, G4double cut) const
Definition at line 271 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 271 of file G4PAIPhotData.cc
References one.
Referenced by G4PAIPhotModel::ComputeDEDXPerVolume().
G4double G4PAIPhotData::GetEnergyPhotonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 940 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 940 of file G4PAIPhotData.cc
References G4PhysicsVector::Energy(), G4UniformRand, G4PhysicsVector::GetVectorLength(), v, G4PhysicsVector::Value(), x1, x2, y1, and y2.
G4double G4PAIPhotData::GetEnergyPlasmonTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 1001 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 1001 of file G4PAIPhotData.cc
References G4PhysicsVector::Energy(), G4UniformRand, G4PhysicsVector::GetVectorLength(), v, G4PhysicsVector::Value(), x1, x2, y1, and y2.
G4double G4PAIPhotData::GetEnergyTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 889 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 889 of file G4PAIPhotData.cc
References G4PhysicsVector::Energy(), G4UniformRand, G4PhysicsVector::GetVectorLength(), v, G4PhysicsVector::Value(), x1, x2, y1, and y2.
G4double G4PAIPhotData::GetPlasmonRatio (G4int coupleIndex, G4double scaledTkin) const
Definition at line 370 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 370 of file G4PAIPhotData.cc
References Acts::VectorHelpers::cross(), and one.
Referenced by G4PAIPhotModel::SampleSecondaries().
void G4PAIPhotData::Initialise (const G4MaterialCutsCouple * couple, G4double cut, G4PAIPhotModel * model)
Definition at line 126 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 126 of file G4PAIPhotData.cc
References G4PAIPhotModel::ComputeMaxEnergy(), eV, G4cout, G4endl, G4ProductionCutsTable::GetEnergyCutsVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), idxG4ElectronCut, idxG4GammaCut, G4PhysicsTable::insertAt(), k, keV, mat, n, source.hepunit::proton_mass_c2, G4PhysicsFreeVector::PutValue(), G4PhysicsVector::PutValue(), t, and G4PhysicsVector::Value().
Referenced by G4PAIPhotModel::Initialise().
G4PAIPhotData& G4PAIPhotData::operator= (const G4PAIPhotData & right) private delete
G4double G4PAIPhotData::SampleAlongStepPhotonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
Definition at line 527 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 527 of file G4PAIPhotData.cc
References e1, e2, G4PhysicsVector::Energy(), G4Poisson(), G4UniformRand, one, position, v1, and v2.
Referenced by G4PAIPhotModel::SampleFluctuations().
G4double G4PAIPhotData::SampleAlongStepPlasmonTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
Definition at line 619 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 619 of file G4PAIPhotData.cc
References e1, e2, G4PhysicsVector::Energy(), G4Poisson(), G4UniformRand, one, position, v1, and v2.
Referenced by G4PAIPhotModel::SampleFluctuations().
G4double G4PAIPhotData::SampleAlongStepTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double stepFactor) const
Definition at line 435 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 435 of file G4PAIPhotData.cc
References e1, e2, G4PhysicsVector::Energy(), G4Poisson(), G4UniformRand, one, position, v1, and v2.
G4double G4PAIPhotData::SamplePostStepPhotonTransfer (G4int coupleIndex, G4double scaledTkin) const
Definition at line 770 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 770 of file G4PAIPhotData.cc
References G4UniformRand, and position.
Referenced by G4PAIPhotModel::SampleSecondaries().
G4double G4PAIPhotData::SamplePostStepPlasmonTransfer (G4int coupleIndex, G4double scaledTkin) const
Definition at line 828 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 828 of file G4PAIPhotData.cc
References G4UniformRand, and position.
Referenced by G4PAIPhotModel::SampleSecondaries().
G4double G4PAIPhotData::SamplePostStepTransfer (G4int coupleIndex, G4double scaledTkin) const
Definition at line 714 of file G4PAIPhotData.cc.
View newest version in sPHENIX GitHub at line 714 of file G4PAIPhotData.cc
References G4UniformRand, and position.
Member Data Documentation
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdEdxCutTable private
Definition at line 134 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 134 of file G4PAIPhotData.hh
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdEdxTable private
Definition at line 128 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 128 of file G4PAIPhotData.hh
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdNdxCutPhotonTable private
Definition at line 131 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 131 of file G4PAIPhotData.hh
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdNdxCutPlasmonTable private
Definition at line 132 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 132 of file G4PAIPhotData.hh
std::vector<G4PhysicsLogVector*> G4PAIPhotData::fdNdxCutTable private
Definition at line 130 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PAIPhotData.hh
G4double G4PAIPhotData::fHighestKineticEnergy private
Definition at line 116 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PAIPhotData.hh
G4double G4PAIPhotData::fLowestKineticEnergy private
Definition at line 115 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PAIPhotData.hh
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIdEdxBank private
Definition at line 127 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PAIPhotData.hh
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIphotonBank private
Definition at line 124 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PAIPhotData.hh
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIplasmonBank private
Definition at line 125 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PAIPhotData.hh
std::vector<G4PhysicsTable*> G4PAIPhotData::fPAIxscBank private
Definition at line 123 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 123 of file G4PAIPhotData.hh
G4PAIxSection G4PAIPhotData::fPAIxSection private
Definition at line 120 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 120 of file G4PAIPhotData.hh
G4PhysicsLogVector* G4PAIPhotData::fParticleEnergyVector private
Definition at line 118 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 118 of file G4PAIPhotData.hh
G4SandiaTable G4PAIPhotData::fSandia private
Definition at line 121 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PAIPhotData.hh
G4int G4PAIPhotData::fTotBin private
Definition at line 114 of file G4PAIPhotData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PAIPhotData.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIPhotData.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PAIPhotData.cc