ECCE @ EIC Software: G4hZiegler1985p Class Reference
G4hZiegler1985p Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hZiegler1985p.hh>
Public Member Functions
G4hZiegler1985p ()
~G4hZiegler1985p ()
G4bool HasMaterial (const G4Material *material)
G4double StoppingPower (const G4Material *material, G4double kineticEnergy)
G4double ElectronicStoppingPower (G4double z, G4double kineticEnergy) const
Public Member Functions inherited from G4VhElectronicStoppingPower
G4VhElectronicStoppingPower ()
virtual ~G4VhElectronicStoppingPower ()
Private Attributes
const G4double protonMassAMU
Static Private Attributes
static const G4double a [92][8]
Additional Inherited Members
Protected Member Functions inherited from G4VhElectronicStoppingPower
G4double HeEffChargeSquare (const G4double z, const G4double kineticEnergyHe) const
G4double GetHeMassAMU () const
Detailed Description
Definition at line 59 of file G4hZiegler1985p.hh.
View newest version in sPHENIX GitHub at line 59 of file G4hZiegler1985p.hh
Constructor & Destructor Documentation
G4hZiegler1985p::G4hZiegler1985p ()
Definition at line 168 of file G4hZiegler1985p.cc.
View newest version in sPHENIX GitHub at line 168 of file G4hZiegler1985p.cc
G4hZiegler1985p::~G4hZiegler1985p ()
Definition at line 174 of file G4hZiegler1985p.cc.
View newest version in sPHENIX GitHub at line 174 of file G4hZiegler1985p.cc
Member Function Documentation
G4double G4hZiegler1985p::ElectronicStoppingPower (G4double z, G4double kineticEnergy) const virtual
Implements G4VhElectronicStoppingPower.
Definition at line 203 of file G4hZiegler1985p.cc.
View newest version in sPHENIX GitHub at line 203 of file G4hZiegler1985p.cc
References a, e, keV, protonMassAMU, and T.
Referenced by StoppingPower().
G4bool G4hZiegler1985p::HasMaterial (const G4Material * material) virtual
Implements G4VhElectronicStoppingPower.
Definition at line 179 of file G4hZiegler1985p.cc.
View newest version in sPHENIX GitHub at line 179 of file G4hZiegler1985p.cc
References false, and G4Material::GetNumberOfElements().
G4double G4hZiegler1985p::StoppingPower (const G4Material * material, G4double kineticEnergy) virtual
Implements G4VhElectronicStoppingPower.
Definition at line 187 of file G4hZiegler1985p.cc.
View newest version in sPHENIX GitHub at line 187 of file G4hZiegler1985p.cc
References ElectronicStoppingPower(), G4Material::GetNumberOfElements(), G4Material::GetZ(), and z.
Member Data Documentation
const G4double G4hZiegler1985p::a static private
Definition at line 80 of file G4hZiegler1985p.hh.
View newest version in sPHENIX GitHub at line 80 of file G4hZiegler1985p.hh
Referenced by ElectronicStoppingPower().
const G4double G4hZiegler1985p::protonMassAMU private
Definition at line 79 of file G4hZiegler1985p.hh.
View newest version in sPHENIX GitHub at line 79 of file G4hZiegler1985p.hh
Referenced by ElectronicStoppingPower().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hZiegler1985p.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4hZiegler1985p.cc