ECCE @ EIC Software: G4SamplingPostStepAction Class Reference
G4SamplingPostStepAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4SamplingPostStepAction.hh>
Public Member Functions
G4SamplingPostStepAction (const G4VTrackTerminator &TrackTerminator)
~G4SamplingPostStepAction ()
void DoIt (const G4Track &aTrack, G4ParticleChange *aParticleChange, const G4Nsplit_Weight &nw)
Private Member Functions
void Split (const G4Track &aTrack, const G4Nsplit_Weight &nw, G4ParticleChange *aParticleChange)
Private Attributes
const G4VTrackTerminator & fTrackTerminator
Detailed Description
Definition at line 48 of file G4SamplingPostStepAction.hh.
View newest version in sPHENIX GitHub at line 48 of file G4SamplingPostStepAction.hh
Constructor & Destructor Documentation
G4SamplingPostStepAction::G4SamplingPostStepAction (const G4VTrackTerminator & TrackTerminator) explicit
Definition at line 44 of file G4SamplingPostStepAction.cc.
View newest version in sPHENIX GitHub at line 44 of file G4SamplingPostStepAction.cc
G4SamplingPostStepAction::~G4SamplingPostStepAction ()
Definition at line 49 of file G4SamplingPostStepAction.cc.
View newest version in sPHENIX GitHub at line 49 of file G4SamplingPostStepAction.cc
Member Function Documentation
void G4SamplingPostStepAction::DoIt (const G4Track & aTrack, G4ParticleChange * aParticleChange, const G4Nsplit_Weight & nw)
Definition at line 53 of file G4SamplingPostStepAction.cc.
View newest version in sPHENIX GitHub at line 53 of file G4SamplingPostStepAction.cc
References FatalException, G4Nsplit_Weight::fN, fTrackTerminator, G4Nsplit_Weight::fW, G4Exception(), G4VTrackTerminator::KillTrack(), G4VParticleChange::ProposeWeight(), and Split().
Referenced by G4ImportanceProcess::PostStepDoIt(), and G4WeightWindowProcess::PostStepDoIt().
void G4SamplingPostStepAction::Split (const G4Track & aTrack, const G4Nsplit_Weight & nw, G4ParticleChange * aParticleChange) private
Definition at line 87 of file G4SamplingPostStepAction.cc.
View newest version in sPHENIX GitHub at line 87 of file G4SamplingPostStepAction.cc
References G4ParticleChange::AddSecondary(), FatalException, G4Nsplit_Weight::fN, G4Nsplit_Weight::fW, G4Exception(), G4Track::GetMomentumDirection(), G4VParticleChange::ProposeWeight(), G4VParticleChange::SetNumberOfSecondaries(), and G4Track::SetWeight().
Referenced by DoIt().
Member Data Documentation
const G4VTrackTerminator& G4SamplingPostStepAction::fTrackTerminator private
Definition at line 72 of file G4SamplingPostStepAction.hh.
View newest version in sPHENIX GitHub at line 72 of file G4SamplingPostStepAction.hh
Referenced by DoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4SamplingPostStepAction.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4SamplingPostStepAction.cc