ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/statusMessageReporting.h File Reference
statusMessageReporting.h File Reference
#include <stdio.h>
#include <stdarg.h>
Classes
struct statusMessageReport
struct statusMessageReporting
Macros
#define smr_unknownID 0
#define smr_tooManyIDs 1
#define smr_invalidID 2
#define smr_errnoID 3
#define smr_smrID 4
#define smr_maximumNumberOfRegisteredLibraries 128
#define smr_maximumFileNameSize 1024
#define smr_codeNULL 0
#define smr_codeFileIO -1
#define smr_codeMemoryAllocating -2
#define smr_malloc2(smr, size, zero, forItem) smr_malloc(smr, size, zero, forItem, __FILE__, __LINE__, __func__)
#define smr_realloc2(smr, old, size, forItem) smr_realloc(smr, old, size, forItem, __FILE__, __LINE__, __func__)
#define smr_allocateCopyString2(smr, s, forItem) smr_allocateCopyString(smr, s, forItem, __FILE__, __LINE__, __func__)
#define smr_allocateCopyStringN2(smr, s, n, forItem) smr_allocateCopyStringN(smr, s, n, forItem, __FILE__, __LINE__, __func__)
#define smr_setReportInfo2(smr, libraryID, code, fmt,...) smr_setReportInfo(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
#define smr_setReportInfo2p(smr, libraryID, code, fmt) smr_setReportInfo(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt)
#define smr_vsetReportInfo2(smr, libraryID, code, fmt, args) smr_vsetReportInfo(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
#define smr_setReportWarning2(smr, libraryID, code, fmt,...) smr_setReportWarning(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
#define smr_setReportWarning2p(smr, libraryID, code, fmt) smr_setReportWarning(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt)
#define smr_vsetReportWarning2(smr, libraryID, code, fmt, args) smr_vsetReportWarning(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
#define smr_setReportError2(smr, libraryID, code, fmt,...) smr_setReportError(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
#define smr_setReportError2p(smr, libraryID, code, fmt) smr_setReportError(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt)
#define smr_vsetReportError2(smr, libraryID, code, fmt, args) smr_vsetReportError(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
#define smr_setReportInfo3(smr, userInterface, libraryID, code, fmt,...) smr_setReportInfo(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
#define smr_setReportInfo3p(smr, userInterface, libraryID, code, fmt) smr_setReportInfo(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt)
#define smr_vsetReportInfo3(smr, userInterface, libraryID, code, fmt, args) smr_vsetReportInfo(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
#define smr_setReportWarning3(smr, userInterface, libraryID, code, fmt,...) smr_setReportWarning(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
#define smr_setReportWarning3p(smr, userInterface, libraryID, code, fmt) smr_setReportWarning(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt)
#define smr_vsetReportWarning3(smr, userInterface, libraryID, code, fmt, args) smr_vsetReportWarning(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
#define smr_setReportError3(smr, userInterface, libraryID, code, fmt,...) smr_setReportError(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
#define smr_setReportError3p(smr, userInterface, libraryID, code, fmt) smr_setReportError(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt)
#define smr_vsetReportError3(smr, userInterface, libraryID, code, fmt, args) smr_vsetReportError(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Typedefs
typedef char *(* smr_userInterface)(void *userData)
typedef struct statusMessageReport statusMessageReport
typedef struct
statusMessageReporting statusMessageReporting
Enumerations
enum smr_status { smr_status_Ok = 0, smr_status_Info, smr_status_Warning, smr_status_Error }
Functions
int smr_setup (void)
int smr_cleanup (void)
int smr_registerLibrary (char const *libraryName)
int smr_numberOfRegisteredLibraries (void)
char const * smr_getRegisteredLibrariesName (int ID)
statusMessageReporting * smr_new (statusMessageReporting *smr, enum smr_status verbosity, int append)
int smr_initialize (statusMessageReporting *smr, enum smr_status verbosity, int append)
void smr_release (statusMessageReporting *smr)
void * smr_free (statusMessageReporting **smr)
statusMessageReporting * smr_clone (statusMessageReporting *smr)
int smr_setReportInfo (statusMessageReporting *smr, void *userInterface, char const *file, int line, char const *function, int libraryID, int code, char const *fmt,...)
int smr_vsetReportInfo (statusMessageReporting *smr, void *userInterface, char const *file, int line, char const *function, int libraryID, int code, char const *fmt, va_list *args)
int smr_setReportWarning (statusMessageReporting *smr, void *userInterface, char const *file, int line, char const *function, int libraryID, int code, char const *fmt,...)
int smr_vsetReportWarning (statusMessageReporting *smr, void *userInterface, char const *file, int line, char const *function, int libraryID, int code, char const *fmt, va_list *args)
int smr_setReportError (statusMessageReporting *smr, void *userInterface, char const *file, int line, char const *function, int libraryID, int code, char const *fmt,...)
int smr_vsetReportError (statusMessageReporting *smr, void *userInterface, char const *file, int line, char const *function, int libraryID, int code, char const *fmt, va_list *args)
enum smr_status smr_highestStatus (statusMessageReporting *smr)
int smr_isOk (statusMessageReporting *smr)
int smr_isInfo (statusMessageReporting *smr)
int smr_isWarning (statusMessageReporting *smr)
int smr_isError (statusMessageReporting *smr)
int smr_isWarningOrError (statusMessageReporting *smr)
int smr_isReportOk (statusMessageReport *report)
int smr_isReportInfo (statusMessageReport *report)
int smr_isReportWarning (statusMessageReport *report)
int smr_isReportError (statusMessageReport *report)
int smr_isReportWarningOrError (statusMessageReport *report)
int smr_numberOfReports (statusMessageReporting *smr)
statusMessageReport * smr_firstReport (statusMessageReporting *smr)
statusMessageReport * smr_nextReport (statusMessageReport *report)
enum smr_status smr_getVerbosity (statusMessageReporting *smr)
int smr_getAppend (statusMessageReporting *smr)
int smr_getLibraryID (statusMessageReport *report)
int smr_getCode (statusMessageReport *report)
int smr_getLine (statusMessageReport *report)
char const * smr_getFile (statusMessageReport *report)
char const * smr_getFunction (statusMessageReport *report)
char const * smr_getMessage (statusMessageReport *report)
char * smr_copyMessage (statusMessageReport *report)
char * smr_copyFullMessage (statusMessageReport *report)
void smr_print (statusMessageReporting *smr, int clear)
void smr_write (statusMessageReporting *smr, FILE *f, int clear)
void smr_reportPrint (statusMessageReport *report)
void smr_reportWrite (statusMessageReport *report, FILE *f)
char const * smr_statusToString (enum smr_status status)
char * smr_allocateFormatMessage (char const *fmt,...)
char * smr_vallocateFormatMessage (char const *fmt, va_list *args)
void * smr_malloc (statusMessageReporting *smr, size_t size, int zero, char const *forItem, char const *file, int line, char const *function)
void * smr_realloc (statusMessageReporting *smr, void *pOld, size_t size, char const *forItem, char const *file, int line, char const *function)
void * smr_freeMemory (void **p)
char * smr_allocateCopyString (statusMessageReporting *smr, char const *s, char const *forItem, char const *file, int line, char const *function)
char * smr_allocateCopyStringN (statusMessageReporting *smr, char const *s, size_t n, char const *forItem, char const *file, int line, char const *function)
Macro Definition Documentation
#define smr_allocateCopyString2 (smr, s, forItem) smr_allocateCopyString(smr, s, forItem, __FILE__, __LINE__, __func__)
Definition at line 113 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 113 of file statusMessageReporting.h
Referenced by MCGIDI_POP_new(), MCGIDI_product_parseFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_read(), MCGIDI_target_read(), PoP_copyParticle(), PoP_makeAlias(), PoP_makeParticle(), PoPs_particleLoadInfo(), unitsDB_addUnitIfNeeded(), xDataTOM_axis_initialize(), xDataTOM_setFileNameTOM(), xDataTOMAL_addAttribute(), xDataTOME_initializeElement(), and xDataXML_setFileName().
#define smr_allocateCopyStringN2 (smr, s, n, forItem) smr_allocateCopyStringN(smr, s, n, forItem, __FILE__, __LINE__, __func__)
Definition at line 114 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 114 of file statusMessageReporting.h
#define smr_codeFileIO -1
Definition at line 25 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 25 of file statusMessageReporting.h
#define smr_codeMemoryAllocating -2
Definition at line 26 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 26 of file statusMessageReporting.h
#define smr_codeNULL 0
Definition at line 24 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 24 of file statusMessageReporting.h
Referenced by smr_reportInitialize().
#define smr_errnoID 3
Definition at line 19 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 19 of file statusMessageReporting.h
Referenced by smr_setup().
#define smr_invalidID 2
Definition at line 18 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 18 of file statusMessageReporting.h
Referenced by smr_setReport(), and smr_setup().
#define smr_malloc2 (smr, size, zero, forItem) smr_malloc(smr, size, zero, forItem, __FILE__, __LINE__, __func__)
Definition at line 111 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 111 of file statusMessageReporting.h
Referenced by _MCGIDI_map_addEntry(), _MCGIDI_map_findTargetViaPoPIDs2(), G4GIDI_Misc_Z_A_m_ToName(), G4GIDI_target::init(), MCGIDI_angular_new(), MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_new(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_distribution_new(), MCGIDI_energy_new(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_energyAngular_new(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_new(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), MCGIDI_map_getFullPath(), MCGIDI_map_new(), MCGIDI_map_readFile(), MCGIDI_map_toXMLString(), MCGIDI_misc_getAbsPath(), MCGIDI_outputChannel_new(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_particle_new(), MCGIDI_POP_new(), MCGIDI_POPs_addParticleIfNeeded(), MCGIDI_POPs_new(), MCGIDI_product_new(), MCGIDI_reaction_new(), MCGIDI_target_heated_new(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_read(), MCGIDI_target_new(), MCGIDI_target_read(), PoP_new(), PoPs_addParticleIfNeeded(), PoPs_copyAddParticleIfNeeded(), smr_new(), smr_reportNew(), unitsDB_addUnitIfNeeded(), xData_initializeData(), xDataTOM_axes_initialize(), xDataTOM_axis_new(), xDataTOM_KalbachMann_initialize(), xDataTOM_LegendreSeries_initialize(), xDataTOM_mallocElement(), xDataTOM_mallocTOM(), xDataTOM_polynomial_initialize(), xDataTOM_regionsW_XYs_LegendreSeries_initialize(), xDataTOM_V_W_XYs_initialize(), xDataTOM_V_W_XYs_LegendreSeries_initialize(), xDataTOM_W_XYs_initialize(), xDataTOM_W_XYs_LegendreSeries_initialize(), xDataTOM_W_XYs_new(), xDataTOMAL_addAttribute(), xDataTOMMisc_getAbsPath(), xDataXML_addElementToRoot(), xDataXML_getElementsByTagName(), xDataXML_getTraceback2(), xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_mallocDoc(), xDataXML_regionsXYsToTOM(), xDataXML_XYsDataToTOM(), and xDataXML_XYsDataToTOM2().
#define smr_maximumFileNameSize 1024
Definition at line 23 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 23 of file statusMessageReporting.h
Referenced by smr_setReport().
#define smr_maximumNumberOfRegisteredLibraries 128
Definition at line 22 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 22 of file statusMessageReporting.h
Referenced by smr_getRegisteredLibrariesName(), smr_registerLibrary(), and smr_setup().
#define smr_realloc2 (smr, old, size, forItem) smr_realloc(smr, old, size, forItem, __FILE__, __LINE__, __func__)
Definition at line 112 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 112 of file statusMessageReporting.h
Referenced by MCGIDI_particle_getInternalID(), MCGIDI_reaction_addReturnProduct(), MCGIDI_sampledProducts_remalloc(), smr_setReport(), and xDataXML_parseCharacterData().
#define smr_setReportError2 (smr, libraryID, code, fmt, ...) smr_setReportError(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
Definition at line 122 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 122 of file statusMessageReporting.h
Referenced by lPoPs_addParticleIfNeeded(), MCGIDI_angular_parseFromTOM(), MCGIDI_angular_sampleMu(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_energy_sampleEnergy(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_kinetics_COM2Lab(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), MCGIDI_map_readFile(), MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), MCGIDI_misc_PQUStringToDouble(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_miscNameToZAm(), MCGIDI_miscNameToZAm_getLevel(), MCGIDI_outputChannel_getProductAtIndex(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_particleMass_AMU(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), MCGIDI_product_sampleMu(), MCGIDI_reaction_getCrossSectionAtE(), MCGIDI_reaction_ParseDetermineReactionProducts(), MCGIDI_reaction_parseFromTOM(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded(), MCGIDI_target_getHeatedTargetAtTIndex(), MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_target_heated_getTotalCrossSectionAtE(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_read(), MCGIDI_target_heated_recast(), MCGIDI_target_read(), MCGIDI_target_readHeatedTarget(), MCGIDI_target_sampleReaction(), PoP_getMassInUnitOf(), PoP_makeAlias(), PoPs_getAtomsIndex_atIndex(), PoPs_getGenre_atIndex(), PoPs_getMassInUnitOf_atIndex(), PoPs_getName_atIndex(), PoPs_getZ_A_l_atIndex(), PoPs_hasNucleus_atIndex(), PoPs_particleLoadInfo(), PoPs_particleMass_AMU(), MCGIDI_samplingSettings::setProductMultiplicityBias(), unitsDB_stringFromIndex(), xDataTOM_axes_getInterpolation(), xDataTOM_axes_getLabel(), xDataTOM_axes_getUnit(), xDataTOM_getLinksElement(), xDataTOM_getLinksElement2(), xDataTOM_getLinksElement3(), xDataTOM_interpolation_getFromString(), xDataTOM_interpolation_set(), xDataTOM_interpolation_setFromString(), xDataTOM_subAxes_initialize(), xDataTOMAL_convertAttributeToDouble(), xDataTOMAL_convertAttributeToInteger(), xDataTOME_getOneElementByName(), xDataTOME_getXDataIfID(), and xDataXML_importFile2().
#define smr_setReportError2p (smr, libraryID, code, fmt) smr_setReportError(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt)
Definition at line 123 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 123 of file statusMessageReporting.h
Referenced by MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_misc_getAbsPath(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_read(), xDataTOM_subAxes_initialize(), xDataTOMMisc_getAbsPath(), and xDataXML_initializeDoc().
#define smr_setReportError3 (smr, userInterface, libraryID, code, fmt, ...) smr_setReportError(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
Definition at line 132 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 132 of file statusMessageReporting.h
Referenced by MCGIDI_map_readFile(), xDataXML_addElementToRoot(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_endXMLParsing(), xDataXML_getCommonData(), xDataXML_getOneElementByTagName(), xDataXML_is_xDataType(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_stringTo_double(), xDataXML_stringTo_xDataTOM_Int(), xDataXML_stringToDoubles(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), and xDataXML_xDataTypeConvertAttributes().
#define smr_setReportError3p (smr, userInterface, libraryID, code, fmt) smr_setReportError(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt)
Definition at line 133 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 133 of file statusMessageReporting.h
Referenced by MCGIDI_map_readFile(), xDataXML_axesElememtToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().
#define smr_setReportInfo2 (smr, libraryID, code, fmt, ...) smr_setReportInfo(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
Definition at line 116 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 116 of file statusMessageReporting.h
#define smr_setReportInfo2p (smr, libraryID, code, fmt) smr_setReportInfo(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt)
Definition at line 117 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 117 of file statusMessageReporting.h
#define smr_setReportInfo3 (smr, userInterface, libraryID, code, fmt, ...) smr_setReportInfo(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
Definition at line 126 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 126 of file statusMessageReporting.h
Referenced by _MCGIDI_map_findAllOfTargetViaPoPIDs2(), _MCGIDI_map_findTargetViaPoPIDs2(), MCGIDI_map_findTargetViaPoPIDs(), MCGIDI_map_getTargetsFullPath(), and MCGIDI_map_toXMLString().
#define smr_setReportInfo3p (smr, userInterface, libraryID, code, fmt) smr_setReportInfo(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt)
Definition at line 127 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 127 of file statusMessageReporting.h
Referenced by MCGIDI_map_getTargetsFullPath().
#define smr_setReportWarning2 (smr, libraryID, code, fmt, ...) smr_setReportWarning(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
Definition at line 119 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 119 of file statusMessageReporting.h
#define smr_setReportWarning2p (smr, libraryID, code, fmt) smr_setReportWarning(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt)
Definition at line 120 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 120 of file statusMessageReporting.h
#define smr_setReportWarning3 (smr, userInterface, libraryID, code, fmt, ...) smr_setReportWarning(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, __VA_ARGS__)
Definition at line 129 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 129 of file statusMessageReporting.h
#define smr_setReportWarning3p (smr, userInterface, libraryID, code, fmt) smr_setReportWarning(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt)
Definition at line 130 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 130 of file statusMessageReporting.h
#define smr_smrID 4
Definition at line 20 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 20 of file statusMessageReporting.h
Referenced by smr_allocateCopyString(), smr_cleanup(), smr_realloc(), and smr_setup().
#define smr_tooManyIDs 1
Definition at line 17 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 17 of file statusMessageReporting.h
Referenced by smr_registerLibrary(), and smr_setup().
#define smr_unknownID 0
Definition at line 16 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 16 of file statusMessageReporting.h
Referenced by _MCGIDI_map_findAllOfTargetViaPoPIDs2(), _MCGIDI_map_findTargetViaPoPIDs2(), MCGIDI_angular_parseFromTOM(), MCGIDI_angular_sampleMu(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_energy_sampleEnergy(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_kinetics_COM2Lab(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), MCGIDI_map_findTargetViaPoPIDs(), MCGIDI_map_getTargetsFullPath(), MCGIDI_map_readFile(), MCGIDI_map_toXMLString(), MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf(), MCGIDI_misc_getAbsPath(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_misc_PQUStringToDouble(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_misc_setMessageError_Element(), MCGIDI_miscNameToZAm(), MCGIDI_miscNameToZAm_getLevel(), MCGIDI_outputChannel_getProductAtIndex(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_particleMass_AMU(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), MCGIDI_product_sampleMu(), MCGIDI_reaction_getCrossSectionAtE(), MCGIDI_reaction_ParseDetermineReactionProducts(), MCGIDI_reaction_parseFromTOM(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded(), MCGIDI_target_getHeatedTargetAtTIndex(), MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_target_heated_getTotalCrossSectionAtE(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_read(), MCGIDI_target_heated_recast(), MCGIDI_target_read(), MCGIDI_target_readHeatedTarget(), MCGIDI_target_sampleReaction(), PoPs_particleLoadInfo(), PoPs_particleMass_AMU(), MCGIDI_samplingSettings::setProductMultiplicityBias(), smr_reportInitialize(), smr_setup(), xDataTOM_getLinksElement(), xDataTOM_getLinksElement2(), xDataTOM_getLinksElement3(), and xDataTOME_getOneElementByName().
#define smr_vsetReportError2 (smr, libraryID, code, fmt, args) smr_vsetReportError(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Definition at line 124 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 124 of file statusMessageReporting.h
#define smr_vsetReportError3 (smr, userInterface, libraryID, code, fmt, args) smr_vsetReportError(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Definition at line 134 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 134 of file statusMessageReporting.h
#define smr_vsetReportInfo2 (smr, libraryID, code, fmt, args) smr_vsetReportInfo(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Definition at line 118 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 118 of file statusMessageReporting.h
#define smr_vsetReportInfo3 (smr, userInterface, libraryID, code, fmt, args) smr_vsetReportInfo(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Definition at line 128 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 128 of file statusMessageReporting.h
#define smr_vsetReportWarning2 (smr, libraryID, code, fmt, args) smr_vsetReportWarning(smr, NULL, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Definition at line 121 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 121 of file statusMessageReporting.h
#define smr_vsetReportWarning3 (smr, userInterface, libraryID, code, fmt, args) smr_vsetReportWarning(smr, userInterface, __FILE__, __LINE__, __func__, libraryID, code, fmt, args)
Definition at line 131 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 131 of file statusMessageReporting.h
Typedef Documentation
typedef char*(* smr_userInterface)(void *userData)
Definition at line 28 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 28 of file statusMessageReporting.h
typedef struct statusMessageReport statusMessageReport
typedef struct statusMessageReporting statusMessageReporting
Enumeration Type Documentation
enum smr_status
Enumerator:
smr_status_Ok
smr_status_Info
smr_status_Warning
smr_status_Error
Definition at line 27 of file statusMessageReporting.h.
View newest version in sPHENIX GitHub at line 27 of file statusMessageReporting.h
Function Documentation
char* smr_allocateCopyString (statusMessageReporting * smr, char const * s, char const * forItem, char const * file, int line, char const * function)
Definition at line 652 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 652 of file statusMessageReporting.cc
References c, smr_setReportError(), and smr_smrID.
Referenced by MCGIDI_particle_getInternalID().
char* smr_allocateCopyStringN (statusMessageReporting * smr, char const * s, size_t n, char const * forItem, char const * file, int line, char const * function)
Definition at line 665 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 665 of file statusMessageReporting.cc
References c, n, and smr_malloc().
char* smr_allocateFormatMessage (char const * fmt, ...)
Definition at line 568 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 568 of file statusMessageReporting.cc
References smr_vallocateFormatMessage().
Referenced by _MCGIDI_map_smrUserInterface(), smr_copyFullMessage(), smr_copyMessage(), and xDataXML_smrUserInterface().
int smr_cleanup (void)
Definition at line 64 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 64 of file statusMessageReporting.cc
References numberOfRegisteredLibraries, registeredLibraries, smr_freeMemory(), smr_smrID, and smrIsSetup.
statusMessageReporting* smr_clone (statusMessageReporting * smr)
Definition at line 131 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 131 of file statusMessageReporting.cc
References statusMessageReporting::append, smr_new(), and statusMessageReporting::verbosity.
char* smr_copyFullMessage (statusMessageReport * report)
Definition at line 514 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 514 of file statusMessageReporting.cc
References statusMessageReport::fileName, statusMessageReport::function, statusMessageReport::line, statusMessageReport::message, smr_allocateFormatMessage(), smr_status_Ok, and statusMessageReport::status.
char* smr_copyMessage (statusMessageReport * report)
Definition at line 505 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 505 of file statusMessageReporting.cc
References statusMessageReport::message, smr_allocateFormatMessage(), smr_status_Ok, and statusMessageReport::status.
statusMessageReport* smr_firstReport (statusMessageReporting * smr)
Definition at line 424 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 424 of file statusMessageReporting.cc
References statusMessageReporting::report, smr_status_Ok, and statusMessageReport::status.
Referenced by smr_highestStatus(), smr_numberOfReports(), smr_release(), smr_setReport(), and smr_write().
void* smr_free (statusMessageReporting ** smr)
Definition at line 154 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 154 of file statusMessageReporting.cc
References smr_freeMemory(), and smr_release().
void* smr_freeMemory (void ** p)
Definition at line 640 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 640 of file statusMessageReporting.cc
Referenced by _MCGIDI_map_addEntry(), G4GIDI::dataFilename(), G4GIDI::freeTarget(), G4GIDI_Z_AMass(), G4GIDI::getAlreadyReadTarget(), G4GIDI::getNamesOfAvailableLibraries(), G4GIDI::isThisDataAvailable(), MCGIDI_angular_free(), MCGIDI_angularEnergy_free(), MCGIDI_angularEnergy_release(), MCGIDI_distribution_free(), MCGIDI_energy_free(), MCGIDI_energyAngular_free(), MCGIDI_energyAngular_release(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_KalbachMann_free(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_KalbachMann_release(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), MCGIDI_map_free(), MCGIDI_map_release(), MCGIDI_misc_setMessageError_Element(), MCGIDI_outputChannel_free(), MCGIDI_outputChannel_release(), MCGIDI_particle_free(), MCGIDI_particle_freeInternalList(), MCGIDI_particle_release(), MCGIDI_POP_free(), MCGIDI_POP_new(), MCGIDI_POP_release(), MCGIDI_POPs_addParticleIfNeeded(), MCGIDI_POPs_free(), MCGIDI_POPs_new(), MCGIDI_POPs_release(), MCGIDI_product_free(), MCGIDI_product_release(), MCGIDI_reaction_free(), MCGIDI_reaction_release(), MCGIDI_sampledProducts_release(), MCGIDI_sampling_pdfsOfX_release(), MCGIDI_sampling_pdfsOfXGivenW_release(), MCGIDI_target_free(), MCGIDI_target_heated_free(), MCGIDI_target_heated_new(), MCGIDI_target_heated_newRead(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_release(), MCGIDI_target_newRead(), MCGIDI_target_newReadFromMap(), MCGIDI_target_newReadFromMapViaPoPIDs(), MCGIDI_target_release(), PoP_free(), PoP_release(), PoPs_addParticleIfNeeded(), PoPs_copyAddParticleIfNeeded(), PoPs_particleLoadInfo(), PoPs_releasePrivate(), G4GIDI::readTarget(), smr_cleanup(), smr_free(), smr_release(), smr_reportRelease(), unitsDB_addUnitIfNeeded(), unitsDB_release(), xDataTOM_axes_release(), xDataTOM_axis_initialize(), xDataTOM_axis_new(), xDataTOM_axis_release(), xDataTOM_freeElement(), xDataTOM_freeTOM(), xDataTOM_KalbachMann_free(), xDataTOM_KalbachMann_initialize(), xDataTOM_KalbachMann_release(), xDataTOM_LegendreSeries_release(), xDataTOM_mallocElement(), xDataTOM_mallocTOM(), xDataTOM_polynomial_free(), xDataTOM_polynomial_initialize(), xDataTOM_polynomial_release(), xDataTOM_regionsW_XYs_LegendreSeries_free(), xDataTOM_regionsW_XYs_LegendreSeries_release(), xDataTOM_regionsXYs_free(), xDataTOM_releaseElement(), xDataTOM_setFileNameTOM(), xDataTOM_V_W_XYs_free(), xDataTOM_V_W_XYs_initialize(), xDataTOM_V_W_XYs_LegendreSeries_free(), xDataTOM_W_XYs_free(), xDataTOM_W_XYs_initialize(), xDataTOM_W_XYs_LegendreSeries_free(), xDataTOM_W_XYs_LegendreSeries_release(), xDataTOM_W_XYs_new(), xDataTOM_W_XYs_release(), xDataTOM_XYs_free(), xDataTOM_XYs_release(), xDataTOMAL_addAttribute(), xDataTOMAL_release(), xDataXML_addElementToRoot(), xDataXML_axesToTOM(), xDataXML_freeDoc(), xDataXML_freeElement(), xDataXML_freeElementItems(), xDataXML_freeElementList(), xDataXML_initializeData(), xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_setFileName(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYsToTOM(), xDataXML_XYsDataToTOM(), xDataXML_XYsDataToTOM2(), and G4GIDI_target::~G4GIDI_target().
int smr_getAppend (statusMessageReporting * smr)
Definition at line 449 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 449 of file statusMessageReporting.cc
References statusMessageReporting::append.
int smr_getCode (statusMessageReport * report)
Definition at line 465 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 465 of file statusMessageReporting.cc
References statusMessageReport::code.
char const* smr_getFile (statusMessageReport * report)
Definition at line 481 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 481 of file statusMessageReporting.cc
References statusMessageReport::fileName.
char const* smr_getFunction (statusMessageReport * report)
Definition at line 489 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 489 of file statusMessageReporting.cc
References statusMessageReport::function.
int smr_getLibraryID (statusMessageReport * report)
Definition at line 457 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 457 of file statusMessageReporting.cc
References statusMessageReport::libraryID.
int smr_getLine (statusMessageReport * report)
Definition at line 473 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 473 of file statusMessageReporting.cc
References statusMessageReport::line.
char const* smr_getMessage (statusMessageReport * report)
Definition at line 497 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 497 of file statusMessageReporting.cc
References statusMessageReport::message.
char const* smr_getRegisteredLibrariesName (int ID)
Definition at line 101 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 101 of file statusMessageReporting.cc
References registeredLibraries, and smr_maximumNumberOfRegisteredLibraries.
enum smr_status smr_getVerbosity (statusMessageReporting * smr)
Definition at line 441 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 441 of file statusMessageReporting.cc
References smr_status_Ok, and statusMessageReporting::verbosity.
enum smr_status smr_highestStatus (statusMessageReporting * smr)
Definition at line 322 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 322 of file statusMessageReporting.cc
References smr_firstReport(), smr_nextReport(), smr_status_Ok, and statusMessageReport::status.
Referenced by smr_isError(), smr_isInfo(), smr_isOk(), smr_isWarning(), and smr_isWarningOrError().
int smr_initialize (statusMessageReporting * smr, enum smr_status verbosity, int append)
Definition at line 120 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 120 of file statusMessageReporting.cc
References statusMessageReporting::append, statusMessageReporting::report, smr_reportInitialize(), and statusMessageReporting::verbosity.
Referenced by G4GIDI_map::G4GIDI_map(), G4GIDI_target::init(), smr_new(), and smr_release().
int smr_isError (statusMessageReporting * smr)
Definition at line 355 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 355 of file statusMessageReporting.cc
References smr_highestStatus(), and smr_status_Error.
int smr_isInfo (statusMessageReporting * smr)
Definition at line 341 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 341 of file statusMessageReporting.cc
References smr_highestStatus(), and smr_status_Info.
int smr_isOk (statusMessageReporting * smr)
Definition at line 334 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 334 of file statusMessageReporting.cc
References smr_highestStatus(), and smr_status_Ok.
Referenced by G4GIDI_map::G4GIDI_map(), G4GIDI_target::getFinalState(), G4GIDI_target::init(), MCGIDI_angular_parseFromTOM(), MCGIDI_angular_sampleMu(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_sampleEnergy(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_KalbachMann_sampleEp(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), MCGIDI_map_findTargetViaPoPIDs(), MCGIDI_map_initialize(), MCGIDI_map_readFile(), MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_miscNameToZAm(), MCGIDI_outputChannel_getFinalQ(), MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_particle_getInternalID(), MCGIDI_product_parsePolynomialMultiplicity(), MCGIDI_target_heated_read(), PoPs_particleReadDatabase(), xDataTOM_initializeTOM(), xDataXML_constructTOM(), xDataXML_endXMLParsing(), xDataXML_importFile2(), xDataXML_initializeDoc(), xDataXML_parseCharacterData(), and xDataXML_parseStartElement().
int smr_isReportError (statusMessageReport * report)
Definition at line 395 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 395 of file statusMessageReporting.cc
References smr_status_Error, and statusMessageReport::status.
int smr_isReportInfo (statusMessageReport * report)
Definition at line 379 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 379 of file statusMessageReporting.cc
References smr_status_Info, and statusMessageReport::status.
int smr_isReportOk (statusMessageReport * report)
Definition at line 371 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 371 of file statusMessageReporting.cc
References smr_status_Ok, and statusMessageReport::status.
int smr_isReportWarning (statusMessageReport * report)
Definition at line 387 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 387 of file statusMessageReporting.cc
References smr_status_Warning, and statusMessageReport::status.
int smr_isReportWarningOrError (statusMessageReport * report)
Definition at line 403 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 403 of file statusMessageReporting.cc
References smr_status_Error, smr_status_Warning, and statusMessageReport::status.
int smr_isWarning (statusMessageReporting * smr)
Definition at line 348 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 348 of file statusMessageReporting.cc
References smr_highestStatus(), and smr_status_Warning.
int smr_isWarningOrError (statusMessageReporting * smr)
Definition at line 362 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 362 of file statusMessageReporting.cc
References smr_highestStatus(), smr_status_Error, and smr_status_Warning.
void* smr_malloc (statusMessageReporting * smr, size_t size, int zero, char const * forItem, char const * file, int line, char const * function)
Definition at line 611 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 611 of file statusMessageReporting.cc
References c, and smr_realloc().
Referenced by smr_allocateCopyStringN().
statusMessageReporting* smr_new (statusMessageReporting * smr, enum smr_status verbosity, int append)
Definition at line 109 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 109 of file statusMessageReporting.cc
References smr_initialize(), and smr_malloc2.
Referenced by smr_clone().
statusMessageReport* smr_nextReport (statusMessageReport * report)
Definition at line 433 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 433 of file statusMessageReporting.cc
References statusMessageReport::next.
Referenced by smr_highestStatus(), smr_numberOfReports(), smr_release(), and smr_write().
int smr_numberOfRegisteredLibraries (void)
Definition at line 94 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 94 of file statusMessageReporting.cc
References numberOfRegisteredLibraries.
int smr_numberOfReports (statusMessageReporting * smr)
Definition at line 411 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 411 of file statusMessageReporting.cc
References n, statusMessageReporting::report, smr_firstReport(), smr_nextReport(), smr_status_Ok, and statusMessageReport::status.
void smr_print (statusMessageReporting * smr, int clear)
Definition at line 523 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 523 of file statusMessageReporting.cc
References smr_write().
Referenced by G4GIDI_map::G4GIDI_map(), G4GIDI_target::getChannelsID(), G4GIDI_target::getElasticFinalState(), G4GIDI_target::getFinalState(), and G4GIDI_target::init().
void* smr_realloc (statusMessageReporting * smr, void * pOld, size_t size, char const * forItem, char const * file, int line, char const * function)
Definition at line 628 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 628 of file statusMessageReporting.cc
References smr_setReportError(), and smr_smrID.
Referenced by smr_malloc().
int smr_registerLibrary (char const * libraryName)
Definition at line 78 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 78 of file statusMessageReporting.cc
References numberOfRegisteredLibraries, registeredLibraries, smr_maximumNumberOfRegisteredLibraries, smr_tooManyIDs, and smrIsSetup.
void smr_release (statusMessageReporting * smr)
Definition at line 139 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 139 of file statusMessageReporting.cc
References statusMessageReporting::append, smr_firstReport(), smr_freeMemory(), smr_initialize(), smr_nextReport(), smr_reportRelease(), and statusMessageReporting::verbosity.
Referenced by smr_free(), smr_setReport(), smr_write(), G4GIDI_map::~G4GIDI_map(), and G4GIDI_target::~G4GIDI_target().
void smr_reportPrint (statusMessageReport * report)
Definition at line 541 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 541 of file statusMessageReporting.cc
References smr_reportWrite().
void smr_reportWrite (statusMessageReport * report, FILE * f)
Definition at line 548 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 548 of file statusMessageReporting.cc
References statusMessageReport::fileName, statusMessageReport::function, statusMessageReport::line, and statusMessageReport::message.
Referenced by smr_reportPrint(), and smr_write().
int smr_setReportError (statusMessageReporting * smr, void * userInterface, char const * file, int line, char const * function, int libraryID, int code, char const * fmt, ...)
Definition at line 302 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 302 of file statusMessageReporting.cc
References smr_setReport(), and smr_status_Error.
Referenced by MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_misc_setMessageError_Element(), PoPs_particleIndex_smr(), smr_allocateCopyString(), smr_realloc(), and xDataTOM_setMessageError_ReturnInt().
int smr_setReportInfo (statusMessageReporting * smr, void * userInterface, char const * file, int line, char const * function, int libraryID, int code, char const * fmt, ...)
Definition at line 262 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 262 of file statusMessageReporting.cc
References smr_setReport(), and smr_status_Info.
int smr_setReportWarning (statusMessageReporting * smr, void * userInterface, char const * file, int line, char const * function, int libraryID, int code, char const * fmt, ...)
Definition at line 282 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 282 of file statusMessageReporting.cc
References smr_setReport(), and smr_status_Warning.
int smr_setup (void)
Definition at line 42 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 42 of file statusMessageReporting.cc
References errnoLibrary, invalidLibrary, numberOfRegisteredLibraries, registeredLibraries, smr_errnoID, smr_invalidID, smr_maximumNumberOfRegisteredLibraries, smr_smrID, smr_tooManyIDs, smr_unknownID, smrIsSetup, smrLibrary, tooManyLibrary, and unknownLibrary.
char const* smr_statusToString (enum smr_status status)
Definition at line 555 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 555 of file statusMessageReporting.cc
References smr_status_Error, smr_status_Info, smr_status_Ok, smr_status_Warning, statusStringError, statusStringInfo, statusStringInvalid, statusStringOk, and statusStringWarning.
char* smr_vallocateFormatMessage (char const * fmt, va_list * args)
Definition at line 581 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 581 of file statusMessageReporting.cc
References buffer, message(), n, SMR_IncrementMessageSize, and SMR_InitialMessageSize.
Referenced by MCGIDI_misc_setMessageError_Element(), smr_allocateFormatMessage(), and smr_setReport().
int smr_vsetReportError (statusMessageReporting * smr, void * userInterface, char const * file, int line, char const * function, int libraryID, int code, char const * fmt, va_list * args)
Definition at line 315 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 315 of file statusMessageReporting.cc
References smr_setReport(), and smr_status_Error.
Referenced by MCGIDI_misc_setMessageError_Element().
int smr_vsetReportInfo (statusMessageReporting * smr, void * userInterface, char const * file, int line, char const * function, int libraryID, int code, char const * fmt, va_list * args)
Definition at line 275 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 275 of file statusMessageReporting.cc
References smr_setReport(), and smr_status_Info.
int smr_vsetReportWarning (statusMessageReporting * smr, void * userInterface, char const * file, int line, char const * function, int libraryID, int code, char const * fmt, va_list * args)
Definition at line 295 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 295 of file statusMessageReporting.cc
References smr_setReport(), and smr_status_Warning.
void smr_write (statusMessageReporting * smr, FILE * f, int clear)
Definition at line 530 of file statusMessageReporting.cc.
View newest version in sPHENIX GitHub at line 530 of file statusMessageReporting.cc
References smr_firstReport(), smr_nextReport(), smr_release(), and smr_reportWrite().
Referenced by smr_print().