ECCE @ EIC Software: G4ExcitedStringDecay Class Reference
G4ExcitedStringDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4ExcitedStringDecay.hh>
Public Member Functions
G4ExcitedStringDecay ()
G4ExcitedStringDecay (G4VLongitudinalStringDecay *aStringDecay)
virtual ~G4ExcitedStringDecay ()
virtual G4KineticTrackVector * FragmentStrings (const G4ExcitedStringVector *theStrings)
Public Member Functions inherited from G4VStringFragmentation
G4VStringFragmentation ()
virtual ~G4VStringFragmentation ()
Private Member Functions
G4ExcitedStringDecay (const G4ExcitedStringDecay &right)
const G4ExcitedStringDecay & operator= (const G4ExcitedStringDecay &right)
G4bool operator== (const G4ExcitedStringDecay &right) const
G4bool operator!= (const G4ExcitedStringDecay &right) const
G4KineticTrackVector * FragmentString (const G4ExcitedString &theString)
G4bool EnergyAndMomentumCorrector (G4KineticTrackVector *Output, G4LorentzVector &TotalCollisionMom)
Private Attributes
G4VLongitudinalStringDecay * theStringDecay
Detailed Description
Definition at line 37 of file G4ExcitedStringDecay.hh.
View newest version in sPHENIX GitHub at line 37 of file G4ExcitedStringDecay.hh
Constructor & Destructor Documentation
G4ExcitedStringDecay::G4ExcitedStringDecay ()
Definition at line 38 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 38 of file G4ExcitedStringDecay.cc
G4ExcitedStringDecay::G4ExcitedStringDecay (G4VLongitudinalStringDecay * aStringDecay)
Definition at line 42 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ExcitedStringDecay.cc
G4ExcitedStringDecay::~G4ExcitedStringDecay () virtual
Definition at line 56 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedStringDecay.cc
G4ExcitedStringDecay::G4ExcitedStringDecay (const G4ExcitedStringDecay & right) private
Definition at line 48 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ExcitedStringDecay.cc
Member Function Documentation
G4bool G4ExcitedStringDecay::EnergyAndMomentumCorrector (G4KineticTrackVector * Output, G4LorentzVector & TotalCollisionMom) private
Definition at line 327 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 327 of file G4ExcitedStringDecay.cc
References G4KineticTrackVector::Boost(), CLHEP::HepLorentzVector::boostVector(), E, CLHEP::HepLorentzVector::e(), FALSE, G4cout, G4endl, CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::m2(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), Scale(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setVect(), sqr(), TRUE, and CLHEP::HepLorentzVector::vect().
Referenced by FragmentStrings().
G4KineticTrackVector * G4ExcitedStringDecay::FragmentString (const G4ExcitedString & theString) private
Definition at line 80 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ExcitedStringDecay.cc
References G4VLongitudinalStringDecay::FragmentString(), and theStringDecay.
Referenced by FragmentStrings().
G4KineticTrackVector * G4ExcitedStringDecay::FragmentStrings (const G4ExcitedStringVector * theStrings) virtual
Implements G4VStringFragmentation.
Definition at line 87 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 87 of file G4ExcitedStringDecay.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), CLHEP::HepLorentzVector::e(), EnergyAndMomentumCorrector(), FragmentString(), G4cout, G4endl, G4KineticTrack::GetDefinition(), G4SampleResonance::GetMinimumMass(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), G4ParticleDefinition::IsShortLived(), CLHEP::Hep3Vector::mag2(), MeV, perMillion, G4SampleResonance::SampleMass(), CLHEP::HepLorentzVector::setE(), G4KineticTrack::SetPosition(), sqr(), and CLHEP::HepLorentzVector::vect().
G4bool G4ExcitedStringDecay::operator!= (const G4ExcitedStringDecay & right) const private
Definition at line 74 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ExcitedStringDecay.cc
const G4ExcitedStringDecay & G4ExcitedStringDecay::operator= (const G4ExcitedStringDecay & right) private
Definition at line 61 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ExcitedStringDecay.cc
G4bool G4ExcitedStringDecay::operator== (const G4ExcitedStringDecay & right) const private
Definition at line 68 of file G4ExcitedStringDecay.cc.
View newest version in sPHENIX GitHub at line 68 of file G4ExcitedStringDecay.cc
Member Data Documentation
G4VLongitudinalStringDecay* G4ExcitedStringDecay::theStringDecay private
Definition at line 56 of file G4ExcitedStringDecay.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedStringDecay.hh
Referenced by FragmentString().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4ExcitedStringDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/src/G4ExcitedStringDecay.cc