ECCE @ EIC Software: G4HadProjectile Class Reference
G4HadProjectile Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadProjectile.hh>
Public Member Functions
G4HadProjectile ()
G4HadProjectile (const G4Track &aT)
G4HadProjectile (const G4DynamicParticle &aT)
~G4HadProjectile ()
void Initialise (const G4Track &aT)
const G4Material * GetMaterial () const
const G4ParticleDefinition * GetDefinition () const
const G4LorentzVector & Get4Momentum () const
const G4ThreeVector & GetMomentumDirection () const
G4LorentzRotation & GetTrafoToLab ()
G4double GetKineticEnergy () const
G4double GetTotalEnergy () const
G4double GetTotalMomentum () const
G4double GetGlobalTime () const
G4double GetBoundEnergy () const
void SetGlobalTime (G4double t)
void SetBoundEnergy (G4double e)
Private Member Functions
void InitialiseLocal (const G4DynamicParticle *)
G4HadProjectile & operator= (const G4HadProjectile &right)
G4HadProjectile (const G4HadProjectile &)
Private Attributes
const G4Material * theMat
const G4ParticleDefinition * theDef
G4LorentzVector theMom
G4LorentzRotation toLabFrame
G4ThreeVector theDirection
G4double theMass
G4double theKinEnergy
G4double theTime
G4double theBoundEnergy
Detailed Description
Definition at line 39 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 39 of file G4HadProjectile.hh
Constructor & Destructor Documentation
G4HadProjectile::G4HadProjectile ()
Definition at line 30 of file G4HadProjectile.cc.
View newest version in sPHENIX GitHub at line 30 of file G4HadProjectile.cc
References CLHEP::Hep3Vector::set(), CLHEP::HepLorentzVector::set(), theDef, theDirection, theKinEnergy, theMass, and theMom.
G4HadProjectile::G4HadProjectile (const G4Track & aT)
Definition at line 40 of file G4HadProjectile.cc.
View newest version in sPHENIX GitHub at line 40 of file G4HadProjectile.cc
References Initialise().
G4HadProjectile::G4HadProjectile (const G4DynamicParticle & aT)
Definition at line 45 of file G4HadProjectile.cc.
View newest version in sPHENIX GitHub at line 45 of file G4HadProjectile.cc
References InitialiseLocal().
G4HadProjectile::~G4HadProjectile ()
Definition at line 51 of file G4HadProjectile.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HadProjectile.cc
G4HadProjectile::G4HadProjectile (const G4HadProjectile &) private
Member Function Documentation
const G4LorentzVector & G4HadProjectile::Get4Momentum () const inline
Definition at line 91 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HadProjectile.hh
References theMom.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BinaryCascade::BuildLateParticleCollisions(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CascadeInterface::createBullet(), G4BinaryCascade::DebugFinalEpConservation(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4ReactionProduct::operator=(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4LENDModel::returnUnchanged(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), and G4RPGNeutronInelastic::SlowNeutron().
G4double G4HadProjectile::GetBoundEnergy () const inline
Definition at line 126 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 126 of file G4HadProjectile.hh
References theBoundEnergy.
Referenced by G4MuMinusCapturePrecompound::ApplyYourself(), and G4MuonMinusBoundDecay::ApplyYourself().
const G4ParticleDefinition * G4HadProjectile::GetDefinition () const inline
Definition at line 86 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HadProjectile.hh
References theDef.
Referenced by G4INCLXXInterface::AccurateProjectile(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BinaryCascade::BuildLateParticleCollisions(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CascadeInterface::createBullet(), G4FissionFragmentGenerator::G4GenerateFission(), G4EnergyRangeManager::GetHadronicInteraction(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4NuMuNucleusCcModel::IsApplicable(), G4DiffuseElasticV2::IsApplicable(), G4NuMuNucleusNcModel::IsApplicable(), G4NeutrinoNucleusModel::IsApplicable(), G4DiffuseElastic::IsApplicable(), G4hhElastic::IsApplicable(), G4LMsdGenerator::IsApplicable(), G4CascadeInterface::IsApplicable(), G4ReactionProduct::operator=(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4LMsdGenerator::SampleMx(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), and G4INCLXXInterface::toINCLParticleSpecies().
G4double G4HadProjectile::GetGlobalTime () const inline
Definition at line 121 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 121 of file G4HadProjectile.hh
References theTime.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDFission::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4HadronStoppingProcess::AtRestDoIt(), and G4FissionLibrary::SampleMult().
G4double G4HadProjectile::GetKineticEnergy () const inline
Definition at line 116 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 116 of file G4HadProjectile.hh
References theKinEnergy.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4LENDGammaModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LENDInelastic::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4EnergyRangeManager::GetHadronicInteraction(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4LMsdGenerator::IsApplicable(), G4CascadeInterface::NoInteraction(), G4ReactionProduct::operator=(), G4LENDModel::returnUnchanged(), G4RPGReaction::Rotate(), G4LMsdGenerator::SampleT(), and G4INCLXXInterface::toINCLKineticEnergy().
const G4Material * G4HadProjectile::GetMaterial () const inline
Definition at line 81 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadProjectile.hh
References theMat.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4LENDorBERTModel::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ParticleHPElastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4LENDCombinedModel::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDGammaModel::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPChannel::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
const G4ThreeVector & G4HadProjectile::GetMomentumDirection () const inline
Definition at line 101 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HadProjectile.hh
References theDirection.
G4double G4HadProjectile::GetTotalEnergy (void) const inline
Definition at line 106 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 106 of file G4HadProjectile.hh
References CLHEP::HepLorentzVector::e(), and theMom.
Referenced by G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LFission::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RPGKMinusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4HadronicProcess::CheckResult(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4NuMuNucleusCcModel::IsApplicable(), G4NuMuNucleusNcModel::IsApplicable(), G4NeutrinoNucleusModel::IsApplicable(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4double G4HadProjectile::GetTotalMomentum () const inline
Definition at line 111 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 111 of file G4HadProjectile.hh
References CLHEP::HepLorentzVector::pz(), and theMom.
Referenced by G4LightMedia::AntiLambdaExchange(), G4LightMedia::AntiNeutronExchange(), G4LightMedia::AntiOmegaMinusExchange(), G4LightMedia::AntiProtonExchange(), G4LightMedia::AntiSigmaMinusExchange(), G4LightMedia::AntiSigmaPlusExchange(), G4LightMedia::AntiXiMinusExchange(), G4LightMedia::AntiXiZeroExchange(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4LightMedia::KaonPlusExchange(), G4LightMedia::KaonZeroShortExchange(), G4LightMedia::LambdaExchange(), G4LightMedia::NeutronExchange(), G4LightMedia::OmegaMinusExchange(), G4LightMedia::PionPlusExchange(), G4LightMedia::ProtonExchange(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4LightMedia::SigmaMinusExchange(), G4LightMedia::SigmaPlusExchange(), G4LightMedia::XiMinusExchange(), and G4LightMedia::XiZeroExchange().
G4LorentzRotation & G4HadProjectile::GetTrafoToLab () inline
Definition at line 96 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 96 of file G4HadProjectile.hh
References toLabFrame.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
void G4HadProjectile::Initialise (const G4Track & aT)
Definition at line 54 of file G4HadProjectile.cc.
View newest version in sPHENIX GitHub at line 54 of file G4HadProjectile.cc
References G4Track::GetDynamicParticle(), G4Track::GetMaterial(), InitialiseLocal(), theBoundEnergy, theMat, and theTime.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4HadProjectile(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
void G4HadProjectile::InitialiseLocal (const G4DynamicParticle * dp) private
Definition at line 65 of file G4HadProjectile.cc.
View newest version in sPHENIX GitHub at line 65 of file G4HadProjectile.cc
References G4DynamicParticle::Get4Momentum(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzRotation::inverse(), CLHEP::HepLorentzVector::phi(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), CLHEP::HepLorentzVector::set(), theDef, theDirection, theKinEnergy, theMass, theMom, CLHEP::HepLorentzVector::theta(), and toLabFrame.
Referenced by G4HadProjectile(), and Initialise().
G4HadProjectile& G4HadProjectile::operator= (const G4HadProjectile & right) private
void G4HadProjectile::SetBoundEnergy (G4double e) inline
Definition at line 136 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 136 of file G4HadProjectile.hh
References e, and theBoundEnergy.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), and G4MuonicAtomDecay::DecayIt().
void G4HadProjectile::SetGlobalTime (G4double t) inline
Definition at line 131 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 131 of file G4HadProjectile.hh
References t, and theTime.
Referenced by G4MuonMinusBoundDecay::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), and G4MuonicAtomDecay::DecayIt().
Member Data Documentation
G4double G4HadProjectile::theBoundEnergy private
Definition at line 78 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadProjectile.hh
Referenced by GetBoundEnergy(), Initialise(), and SetBoundEnergy().
const G4ParticleDefinition* G4HadProjectile::theDef private
Definition at line 71 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 71 of file G4HadProjectile.hh
Referenced by G4HadProjectile(), GetDefinition(), and InitialiseLocal().
G4ThreeVector G4HadProjectile::theDirection private
Definition at line 74 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadProjectile.hh
Referenced by G4HadProjectile(), GetMomentumDirection(), and InitialiseLocal().
G4double G4HadProjectile::theKinEnergy private
Definition at line 76 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadProjectile.hh
Referenced by G4HadProjectile(), GetKineticEnergy(), and InitialiseLocal().
G4double G4HadProjectile::theMass private
Definition at line 75 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HadProjectile.hh
Referenced by G4HadProjectile(), and InitialiseLocal().
const G4Material* G4HadProjectile::theMat private
Definition at line 70 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HadProjectile.hh
Referenced by GetMaterial(), and Initialise().
G4LorentzVector G4HadProjectile::theMom private
Definition at line 72 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HadProjectile.hh
Referenced by G4HadProjectile(), Get4Momentum(), GetTotalEnergy(), GetTotalMomentum(), and InitialiseLocal().
G4double G4HadProjectile::theTime private
Definition at line 77 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HadProjectile.hh
Referenced by GetGlobalTime(), Initialise(), and SetGlobalTime().
G4LorentzRotation G4HadProjectile::toLabFrame private
Definition at line 73 of file G4HadProjectile.hh.
View newest version in sPHENIX GitHub at line 73 of file G4HadProjectile.hh
Referenced by GetTrafoToLab(), and InitialiseLocal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadProjectile.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4HadProjectile.cc