ECCE @ EIC Software: GMocrenDataPrimitive< T > Class Template Reference
GMocrenDataPrimitive< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/gMocren/include/G4GMocrenIO.hh>
Public Member Functions
GMocrenDataPrimitive ()
~GMocrenDataPrimitive ()
GMocrenDataPrimitive< T > & operator= (const GMocrenDataPrimitive< T > &_right)
GMocrenDataPrimitive< T > & operator+ (const GMocrenDataPrimitive< T > &_right)
GMocrenDataPrimitive< T > & operator+= (const GMocrenDataPrimitive< T > &_right)
void clear ()
void clearImage ()
void setSize (int _size[3])
void getSize (int _size[3])
void setScale (double &_scale)
double getScale ()
void setMinMax (T _minmax[2])
void getMinMax (T _minmax[2])
void setImage (std::vector< T * > &_image)
void addImage (T *_image)
std::vector< T * > & getImage ()
T * getImage (int _z)
void setCenterPosition (float _center[3])
void getCenterPosition (float _center[3])
void setName (std::string &_name)
std::string getName ()
Protected Attributes
int kSize [3]
double kScale
T kMinmax [2]
float kCenter [3]
std::vector< T * > kImage
std::string kDataName
Detailed Description
template<typename T>
class GMocrenDataPrimitive< T >
Definition at line 50 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 50 of file G4GMocrenIO.hh
Constructor & Destructor Documentation
template<typename T > GMocrenDataPrimitive< T >::GMocrenDataPrimitive ()
Definition at line 59 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 59 of file G4GMocrenIO.cc
References clear().
template<typename T > GMocrenDataPrimitive< T >::~GMocrenDataPrimitive ()
Definition at line 63 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GMocrenIO.cc
Member Function Documentation
template<typename T> void GMocrenDataPrimitive< T >::addImage (T * _image)
Definition at line 216 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 216 of file G4GMocrenIO.cc
Referenced by GMocrenDataPrimitive< T >::operator+(), G4GMocrenIO::retrieveData2(), G4GMocrenIO::retrieveData3(), G4GMocrenIO::retrieveData4(), and G4GMocrenIO::setModalityImage().
template<typename T > void GMocrenDataPrimitive< T >::clear (void)
Definition at line 167 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 167 of file G4GMocrenIO.cc
References T.
Referenced by G4GMocrenIO::initialize().
template<typename T > void GMocrenDataPrimitive< T >::clearImage ()
Definition at line 179 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 179 of file G4GMocrenIO.cc
Referenced by G4GMocrenIO::clearModalityImage().
template<typename T > void GMocrenDataPrimitive< T >::getCenterPosition (float _center[3])
Definition at line 233 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 233 of file G4GMocrenIO.cc
Referenced by G4GMocrenIO::getModalityCenterPosition().
template<typename T > std::vector< T * > & GMocrenDataPrimitive< T >::getImage ()
Definition at line 220 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 220 of file G4GMocrenIO.cc
Referenced by G4GMocrenIO::getModalityImage(), G4GMocrenIO::storeData2(), G4GMocrenIO::storeData3(), and G4GMocrenIO::storeData4().
template<typename T > T * GMocrenDataPrimitive< T >::getImage (int _z)
Definition at line 224 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 224 of file G4GMocrenIO.cc
template<typename T> void GMocrenDataPrimitive< T >::getMinMax (T _minmax[2])
Definition at line 207 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 207 of file G4GMocrenIO.cc
Referenced by G4GMocrenIO::convertDensityToHU(), G4GMocrenIO::getModalityImageMax(), G4GMocrenIO::getModalityImageMin(), G4GMocrenIO::getModalityImageMinMax(), G4GMocrenIO::storeData2(), G4GMocrenIO::storeData3(), and G4GMocrenIO::storeData4().
template<typename T > std::string GMocrenDataPrimitive< T >::getName (void)
Definition at line 241 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 241 of file G4GMocrenIO.cc
template<typename T > double GMocrenDataPrimitive< T >::getScale ()
Definition at line 199 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 199 of file G4GMocrenIO.cc
Referenced by G4GMocrenIO::getModalityImageScale(), G4GMocrenIO::storeData2(), G4GMocrenIO::storeData3(), and G4GMocrenIO::storeData4().
template<typename T > void GMocrenDataPrimitive< T >::getSize (int _size[3])
Definition at line 191 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 191 of file G4GMocrenIO.cc
Referenced by G4GMocrenIO::getModalityImageSize(), G4GMocrenIO::storeData2(), G4GMocrenIO::storeData3(), and G4GMocrenIO::storeData4().
template<typename T> GMocrenDataPrimitive< T > & GMocrenDataPrimitive< T >::operator+ (const GMocrenDataPrimitive< T > & _right)
Definition at line 92 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 92 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::addImage(), DOSERANGE, G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), GMocrenDataPrimitive< T >::kCenter, GMocrenDataPrimitive< T >::kImage, GMocrenDataPrimitive< T >::kSize, num, GMocrenDataPrimitive< T >::setCenterPosition(), GMocrenDataPrimitive< T >::setMinMax(), GMocrenDataPrimitive< T >::setScale(), GMocrenDataPrimitive< T >::setSize(), T, and z.
template<typename T> GMocrenDataPrimitive< T > & GMocrenDataPrimitive< T >::operator+= (const GMocrenDataPrimitive< T > & _right)
Definition at line 134 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 134 of file G4GMocrenIO.cc
References DOSERANGE, G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), GMocrenDataPrimitive< T >::kCenter, GMocrenDataPrimitive< T >::kImage, GMocrenDataPrimitive< T >::kMinmax, GMocrenDataPrimitive< T >::kSize, num, and z.
template<typename T> GMocrenDataPrimitive< T > & GMocrenDataPrimitive< T >::operator= (const GMocrenDataPrimitive< T > & _right)
Definition at line 73 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 73 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::kCenter, GMocrenDataPrimitive< T >::kImage, GMocrenDataPrimitive< T >::kMinmax, GMocrenDataPrimitive< T >::kScale, GMocrenDataPrimitive< T >::kSize, num, T, and z.
template<typename T > void GMocrenDataPrimitive< T >::setCenterPosition (float _center[3])
Definition at line 229 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 229 of file G4GMocrenIO.cc
Referenced by GMocrenDataPrimitive< T >::operator+(), and G4GMocrenIO::setModalityCenterPosition().
template<typename T> void GMocrenDataPrimitive< T >::setImage (std::vector< T * > & _image)
Definition at line 212 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 212 of file G4GMocrenIO.cc
template<typename T> void GMocrenDataPrimitive< T >::setMinMax (T _minmax[2])
Definition at line 203 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 203 of file G4GMocrenIO.cc
Referenced by GMocrenDataPrimitive< T >::operator+(), G4GMocrenIO::retrieveData2(), G4GMocrenIO::retrieveData3(), G4GMocrenIO::retrieveData4(), and G4GMocrenIO::setModalityImageMinMax().
template<typename T > void GMocrenDataPrimitive< T >::setName (std::string & _name)
Definition at line 237 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 237 of file G4GMocrenIO.cc
template<typename T > void GMocrenDataPrimitive< T >::setScale (double & _scale)
Definition at line 195 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 195 of file G4GMocrenIO.cc
Referenced by GMocrenDataPrimitive< T >::operator+(), G4GMocrenIO::retrieveData2(), G4GMocrenIO::retrieveData3(), G4GMocrenIO::retrieveData4(), and G4GMocrenIO::setModalityImageScale().
template<typename T > void GMocrenDataPrimitive< T >::setSize (int _size[3])
Definition at line 187 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 187 of file G4GMocrenIO.cc
Referenced by GMocrenDataPrimitive< T >::operator+(), G4GMocrenIO::retrieveData2(), G4GMocrenIO::retrieveData3(), G4GMocrenIO::retrieveData4(), and G4GMocrenIO::setModalityImageSize().
Member Data Documentation
template<typename T> float GMocrenDataPrimitive< T >::kCenter[3] protected
Definition at line 55 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 55 of file G4GMocrenIO.hh
Referenced by GMocrenDataPrimitive< T >::operator+(), GMocrenDataPrimitive< T >::operator+=(), and GMocrenDataPrimitive< T >::operator=().
template<typename T> std::string GMocrenDataPrimitive< T >::kDataName protected
Definition at line 57 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 57 of file G4GMocrenIO.hh
template<typename T> std::vector<T *> GMocrenDataPrimitive< T >::kImage protected
Definition at line 56 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 56 of file G4GMocrenIO.hh
Referenced by GMocrenDataPrimitive< T >::operator+(), GMocrenDataPrimitive< T >::operator+=(), and GMocrenDataPrimitive< T >::operator=().
template<typename T> T GMocrenDataPrimitive< T >::kMinmax[2] protected
Definition at line 54 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GMocrenIO.hh
Referenced by GMocrenDataPrimitive< T >::operator+=(), and GMocrenDataPrimitive< T >::operator=().
template<typename T> double GMocrenDataPrimitive< T >::kScale protected
Definition at line 53 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 53 of file G4GMocrenIO.hh
Referenced by GMocrenDataPrimitive< T >::operator=().
template<typename T> int GMocrenDataPrimitive< T >::kSize[3] protected
Definition at line 52 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 52 of file G4GMocrenIO.hh
Referenced by GMocrenDataPrimitive< T >::operator+(), GMocrenDataPrimitive< T >::operator+=(), and GMocrenDataPrimitive< T >::operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/gMocren/include/G4GMocrenIO.hh
geant4/tree/geant4-10.6-release/source/visualization/gMocren/src/G4GMocrenIO.cc