ECCE @ EIC Software: G4INCLXXPionBuilder Class Reference
G4INCLXXPionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4INCLXXPionBuilder.hh>
Public Member Functions
G4INCLXXPionBuilder ()
virtual ~G4INCLXXPionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPionBuilder
G4VPionBuilder ()=default
virtual ~G4VPionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4INCLXXInterface * theModel
G4double theMin
G4double theMax
Detailed Description
Builder for pion processes using the INCL++ intra-nuclear cascade model.
By default the INCL++ model is used for projectile energies 0 - 20 GeV.
The builder uses INCL++ cascade model with G4ExcitationHandler de-excitation. This is implemented in interface G4INCLXXInterface.
See Also
G4INCLXXInterface
G4INCLXXProtonBuilder
G4INCLXXNeutronBuilder
Definition at line 56 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLXXPionBuilder.hh
Constructor & Destructor Documentation
G4INCLXXPionBuilder::G4INCLXXPionBuilder ()
Definition at line 35 of file G4INCLXXPionBuilder.cc.
View newest version in sPHENIX GitHub at line 35 of file G4INCLXXPionBuilder.cc
References GeV, G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual G4INCLXXPionBuilder::~G4INCLXXPionBuilder () inline virtual
Definition at line 60 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLXXPionBuilder.hh
Member Function Documentation
virtual void G4INCLXXPionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPionBuilder.
Definition at line 62 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4INCLXXPionBuilder.hh
void G4INCLXXPionBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 45 of file G4INCLXXPionBuilder.cc.
View newest version in sPHENIX GitHub at line 45 of file G4INCLXXPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4INCLXXPionBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 54 of file G4INCLXXPionBuilder.cc.
View newest version in sPHENIX GitHub at line 54 of file G4INCLXXPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4INCLXXPionBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLXXPionBuilder.hh
References theMax.
virtual void G4INCLXXPionBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 66 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLXXPionBuilder.hh
References theMin.
Referenced by G4HadronPhysicsINCLXX::Pion().
Member Data Documentation
G4double G4INCLXXPionBuilder::theMax private
Definition at line 73 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4INCLXXPionBuilder.hh
Referenced by Build(), G4INCLXXPionBuilder(), and SetMaxEnergy().
G4double G4INCLXXPionBuilder::theMin private
Definition at line 72 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLXXPionBuilder.hh
Referenced by Build(), G4INCLXXPionBuilder(), and SetMinEnergy().
G4INCLXXInterface* G4INCLXXPionBuilder::theModel private
Definition at line 71 of file G4INCLXXPionBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4INCLXXPionBuilder.hh
Referenced by Build(), and G4INCLXXPionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4INCLXXPionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4INCLXXPionBuilder.cc