ECCE @ EIC Software: HEPREP::HepRepDefinition Class Reference
HEPREP::HepRepDefinition Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepDefinition.h>
Public Member Functions
virtual ~HepRepDefinition ()
Destructor.
virtual void addAttDef (std::string name, std::string desc, std::string category, std::string extra)=0
virtual void addAttDef (HepRepAttDef *attDef)=0
virtual HepRepAttDef * getAttDef (std::string name)=0
virtual std::set< HepRepAttDef * > getAttDefsFromNode ()=0
virtual HepRepAttDef * getAttDefFromNode (std::string lowerCaseName)=0
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
virtual void addAttValue (HepRepAttValue *attValue)=0
virtual void addAttValue (std::string key, char *value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::string value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int64 value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, bool value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::vector< double > value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double red, double green, double blue, double alpha=1.0, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual HepRepAttValue * removeAttValue (std::string key)=0
virtual HepRepAttValue * getAttValue (std::string name)=0
virtual std::set
< HepRepAttValue * > getAttValuesFromNode ()=0
virtual HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)=0
Detailed Description
HepRepDefinition interface.
Author
Mark Donszelmann
Definition at line 27 of file HepRepDefinition.h.
View newest version in sPHENIX GitHub at line 27 of file HepRepDefinition.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepDefinition::~HepRepDefinition () inline virtual
Destructor.
Definition at line 31 of file HepRepDefinition.h.
View newest version in sPHENIX GitHub at line 31 of file HepRepDefinition.h
Member Function Documentation
virtual void HEPREP::HepRepDefinition::addAttDef (std::string name, std::string desc, std::string category, std::string extra) pure virtual
Adds an attdef.
Parameters
name name of the definition.
desc description of the definition.
category category of the definition.
extra extra info of the definition.
Implemented in cheprep::DefaultHepRepDefinition.
Referenced by G4HepRepSceneHandler::addAttDefs(), G4HepRepSceneHandler::addTopLevelAttributes(), and G4HepRepSceneHandler::getGeometryRootType().
virtual void HEPREP::HepRepDefinition::addAttDef (HepRepAttDef * attDef) pure virtual
Adds an attdef.
Parameters
attDef to be added.
Implemented in cheprep::DefaultHepRepDefinition.
virtual HepRepAttDef* HEPREP::HepRepDefinition::getAttDef (std::string name) pure virtual
Return a named attribute definition searched on this node and any parent nodes.
Parameters
name of attribute definition.
Returns
attribute definition.
Implemented in cheprep::DefaultHepRepType, and cheprep::DefaultHepRepDefinition.
virtual HepRepAttDef* HEPREP::HepRepDefinition::getAttDefFromNode (std::string lowerCaseName) pure virtual
Returns a named attribute definition defined on this node.
Parameters
lowerCaseName name of the attribute in lower case.
Returns
attribute definition.
Implemented in cheprep::DefaultHepRepDefinition.
Referenced by cheprep::DefaultHepRepType::getAttDef().
virtual std::set<HepRepAttDef *> HEPREP::HepRepDefinition::getAttDefsFromNode () pure virtual
Returns a collection of all attribute definitions defined on this node.
Returns
collection of attributes definitions.
Implemented in cheprep::DefaultHepRepDefinition.
Referenced by cheprep::XMLHepRepWriter::write().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepDefinition.h