ECCE @ EIC Software: G4Scintillation Class Reference
G4Scintillation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4Scintillation.hh>
Public Member Functions
G4Scintillation (const G4String &processName="Scintillation", G4ProcessType type=fElectromagnetic)
~G4Scintillation ()
G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
void BuildPhysicsTable (const G4ParticleDefinition &aParticleType) override
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *) override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
G4VParticleChange * AtRestDoIt (const G4Track &aTrack, const G4Step &aStep) override
G4double GetScintillationYieldByParticleType (const G4Track &aTrack, const G4Step &aStep)
void SetTrackSecondariesFirst (const G4bool state)
G4bool GetTrackSecondariesFirst () const
void SetFiniteRiseTime (const G4bool state)
G4bool GetFiniteRiseTime () const
void SetScintillationYieldFactor (const G4double yieldfactor)
G4double GetScintillationYieldFactor () const
void SetScintillationExcitationRatio (const G4double ratio)
G4double GetScintillationExcitationRatio () const
G4PhysicsTable * GetFastIntegralTable () const
G4PhysicsTable * GetSlowIntegralTable () const
void AddSaturation (G4EmSaturation *sat)
void RemoveSaturation ()
G4EmSaturation * GetSaturation () const
void SetScintillationByParticleType (const G4bool)
G4bool GetScintillationByParticleType () const
void SetScintillationTrackInfo (const G4bool trackType)
G4bool GetScintillationTrackInfo () const
void SetStackPhotons (const G4bool)
G4bool GetStackPhotons () const
G4int GetNumPhotons () const
void DumpPhysicsTable () const
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
void BuildThePhysicsTable ()
Protected Attributes
G4PhysicsTable * fFastIntegralTable
G4PhysicsTable * fSlowIntegralTable
Private Member Functions
G4Scintillation (const G4Scintillation &right)=delete
G4Scintillation & operator= (const G4Scintillation &right)=delete
G4double single_exp (G4double t, G4double tau2)
G4double bi_exp (G4double t, G4double tau1, G4double tau2)
G4double sample_time (G4double tau1, G4double tau2)
Private Attributes
G4bool fTrackSecondariesFirst
G4bool fFiniteRiseTime
G4double fYieldFactor
G4double fExcitationRatio
G4bool fScintillationByParticleType
G4bool fScintillationTrackInfo
G4bool fStackingFlag
G4int fNumPhotons
G4EmSaturation * fEmSaturation
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 87 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Scintillation.hh
Constructor & Destructor Documentation
G4Scintillation::G4Scintillation (const G4String & processName = "Scintillation", G4ProcessType type = fElectromagnetic) explicit
Definition at line 79 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 79 of file G4Scintillation.cc
References fFastIntegralTable, fScintillation, fSlowIntegralTable, G4cout, G4endl, G4VProcess::GetProcessName(), G4VProcess::SetProcessSubType(), and G4VProcess::verboseLevel.
G4Scintillation::~G4Scintillation ()
Definition at line 107 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 107 of file G4Scintillation.cc
References G4PhysicsTable::clearAndDestroy(), fFastIntegralTable, and fSlowIntegralTable.
G4Scintillation::G4Scintillation (const G4Scintillation & right) private delete
Member Function Documentation
void G4Scintillation::AddSaturation (G4EmSaturation * sat) inline
Definition at line 339 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 339 of file G4Scintillation.hh
References fEmSaturation.
Referenced by G4OpticalPhysics::ConstructProcess().
G4VParticleChange * G4Scintillation::AtRestDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 145 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 145 of file G4Scintillation.cc
References PostStepDoIt().
G4double G4Scintillation::bi_exp (G4double t, G4double tau1, G4double tau2) inline private
Definition at line 400 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 400 of file G4Scintillation.hh
Referenced by sample_time().
void G4Scintillation::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 125 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 125 of file G4Scintillation.cc
References BuildThePhysicsTable(), G4PhysicsTable::clearAndDestroy(), fFastIntegralTable, and fSlowIntegralTable.
void G4Scintillation::BuildThePhysicsTable () protected
Definition at line 468 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 468 of file G4Scintillation.cc
References G4PhysicsVector::Energy(), fFastIntegralTable, fSlowIntegralTable, G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), G4MaterialPropertiesTable::GetProperty(), G4PhysicsVector::GetVectorLength(), G4PhysicsTable::insertAt(), kFASTCOMPONENT, and kSLOWCOMPONENT.
Referenced by BuildPhysicsTable().
void G4Scintillation::DumpPhysicsTable () const
Definition at line 826 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 826 of file G4Scintillation.cc
References G4PhysicsVector::DumpValues(), G4PhysicsTable::entries(), fFastIntegralTable, fSlowIntegralTable, and v.
G4PhysicsTable * G4Scintillation::GetFastIntegralTable () const inline
Definition at line 333 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 333 of file G4Scintillation.hh
References fFastIntegralTable.
G4bool G4Scintillation::GetFiniteRiseTime () const inline
Definition at line 297 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 297 of file G4Scintillation.hh
References fFiniteRiseTime.
G4double G4Scintillation::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition * condition) override virtual
Implements G4VRestDiscreteProcess.
Definition at line 635 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 635 of file G4Scintillation.cc
References DBL_MAX, and StronglyForced.
G4double G4Scintillation::GetMeanLifeTime (const G4Track & aTrack, G4ForceCondition * condition) override virtual
Implements G4VRestDiscreteProcess.
Definition at line 649 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 649 of file G4Scintillation.cc
References DBL_MAX, and Forced.
G4int G4Scintillation::GetNumPhotons () const inline
Definition at line 387 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 387 of file G4Scintillation.hh
References fNumPhotons.
G4EmSaturation * G4Scintillation::GetSaturation () const inline
Definition at line 351 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 351 of file G4Scintillation.hh
References fEmSaturation.
G4bool G4Scintillation::GetScintillationByParticleType () const inline
Definition at line 357 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 357 of file G4Scintillation.hh
References fScintillationByParticleType.
G4double G4Scintillation::GetScintillationExcitationRatio () const inline
Definition at line 321 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 321 of file G4Scintillation.hh
References fExcitationRatio.
G4bool G4Scintillation::GetScintillationTrackInfo () const inline
Definition at line 369 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 369 of file G4Scintillation.hh
References fScintillationTrackInfo.
G4double G4Scintillation::GetScintillationYieldByParticleType (const G4Track & aTrack, const G4Step & aStep)
Definition at line 681 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 681 of file G4Scintillation.cc
References G4Alpha::AlphaDefinition(), G4Deuteron::DeuteronDefinition(), G4Electron::ElectronDefinition(), FatalException, fGeomBoundary, fStopButAlive, G4cout, G4endl, G4Exception(), G4Gamma::GammaDefinition(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4StepPoint::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4Track::GetMaterial(), G4Material::GetMaterialPropertiesTable(), G4PhysicsVector::GetMaxEnergy(), G4PhysicsOrderedFreeVector::GetMaxValue(), G4Track::GetParentID(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), G4Track::GetVertexKineticEnergy(), JustWarning, kALPHASCINTILLATIONYIELD, kDEUTERONSCINTILLATIONYIELD, kELECTRONSCINTILLATIONYIELD, kIONSCINTILLATIONYIELD, kPROTONSCINTILLATIONYIELD, kTRITONSCINTILLATIONYIELD, MeV, G4Neutron::NeutronDefinition(), G4Proton::ProtonDefinition(), G4Triton::TritonDefinition(), and G4PhysicsVector::Value().
Referenced by PostStepDoIt().
G4double G4Scintillation::GetScintillationYieldFactor () const inline
Definition at line 309 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 309 of file G4Scintillation.hh
References fYieldFactor.
G4PhysicsTable * G4Scintillation::GetSlowIntegralTable () const inline
Definition at line 327 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 327 of file G4Scintillation.hh
References fSlowIntegralTable.
G4bool G4Scintillation::GetStackPhotons () const inline
Definition at line 381 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 381 of file G4Scintillation.hh
References fStackingFlag.
G4bool G4Scintillation::GetTrackSecondariesFirst () const inline
Definition at line 285 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 285 of file G4Scintillation.hh
References fTrackSecondariesFirst.
G4bool G4Scintillation::IsApplicable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 119 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 119 of file G4Scintillation.cc
References G4ParticleDefinition::GetPDGCharge(), and G4ParticleDefinition::IsShortLived().
Referenced by DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4OpticalPhysics::ConstructProcess(), and PHG4Reco::InitRun().
G4Scintillation& G4Scintillation::operator= (const G4Scintillation & right) private delete
G4VParticleChange * G4Scintillation::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 158 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 158 of file G4Scintillation.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, CLHEP::Hep3Vector::cross(), Acts::Test::delta, fAlive, Fast, fEmSaturation, fExcitationRatio, fFastIntegralTable, fFiniteRiseTime, fNumPhotons, fScintillationByParticleType, fScintillationTrackInfo, fSlowIntegralTable, fStackingFlag, fSuspend, fTrackSecondariesFirst, fYieldFactor, G4cout, G4endl, G4Poisson(), G4UniformRand, G4DynamicParticle::GetDefinition(), G4Step::GetDeltaPosition(), G4Track::GetDynamicParticle(), G4PhysicsOrderedFreeVector::GetEnergy(), G4StepPoint::GetGlobalTime(), G4Material::GetIndex(), G4Track::GetMaterial(), G4Material::GetMaterialPropertiesTable(), G4PhysicsOrderedFreeVector::GetMaxValue(), G4VParticleChange::GetNumberOfSecondaries(), G4ParticleDefinition::GetPDGCharge(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4MaterialPropertiesTable::GetProperty(), GetScintillationYieldByParticleType(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), G4StepPoint::GetVelocity(), G4ParticleChange::Initialize(), kFASTCOMPONENT, kFASTSCINTILLATIONRISETIME, kFASTTIMECONSTANT, kRESOLUTIONSCALE, kSCINTILLATIONYIELD, kSLOWCOMPONENT, kSLOWSCINTILLATIONRISETIME, kSLOWTIMECONSTANT, kYIELDRATIO, min, ns, G4OpticalPhoton::OpticalPhoton(), Acts::VectorHelpers::perp(), phi, G4VRestDiscreteProcess::PostStepDoIt(), G4VParticleChange::ProposeTrackStatus(), sample_time(), G4DynamicParticle::SetKineticEnergy(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetParentID(), G4DynamicParticle::SetPolarization(), G4Track::SetTouchableHandle(), G4INCL::DeJongSpin::shoot(), Slow, twopi, CLHEP::Hep3Vector::unit(), G4VProcess::verboseLevel, G4EmSaturation::VisibleEnergyDepositionAtAStep(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by AtRestDoIt().
void G4Scintillation::RemoveSaturation () inline
Definition at line 345 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 345 of file G4Scintillation.hh
References fEmSaturation.
Referenced by SetScintillationByParticleType().
G4double G4Scintillation::sample_time (G4double tau1, G4double tau2) private
Definition at line 658 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 658 of file G4Scintillation.cc
References bi_exp(), d, G4UniformRand, single_exp(), and t.
Referenced by PostStepDoIt().
void G4Scintillation::SetFiniteRiseTime (const G4bool state) inline
Definition at line 291 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 291 of file G4Scintillation.hh
References fFiniteRiseTime.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetFiniteRiseTime().
void G4Scintillation::SetScintillationByParticleType (const G4bool scintType)
Definition at line 621 of file G4Scintillation.cc.
View newest version in sPHENIX GitHub at line 621 of file G4Scintillation.cc
References fEmSaturation, fScintillationByParticleType, G4Exception(), JustWarning, and RemoveSaturation().
Referenced by G4OpticalPhysics::ConstructProcess().
void G4Scintillation::SetScintillationExcitationRatio (const G4double ratio) inline
Definition at line 315 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 315 of file G4Scintillation.hh
References fExcitationRatio, and ratio.
Referenced by DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationExcitationRatio().
void G4Scintillation::SetScintillationTrackInfo (const G4bool trackType) inline
Definition at line 363 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 363 of file G4Scintillation.hh
References fScintillationTrackInfo.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationTrackInfo().
void G4Scintillation::SetScintillationYieldFactor (const G4double yieldfactor) inline
Definition at line 303 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 303 of file G4Scintillation.hh
References fYieldFactor.
Referenced by DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4OpticalPhysics::ConstructProcess(), PHG4Reco::InitRun(), and G4OpticalPhysics::SetScintillationYieldFactor().
void G4Scintillation::SetStackPhotons (const G4bool stackingFlag) inline
Definition at line 375 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 375 of file G4Scintillation.hh
References fStackingFlag.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetScintillationStackPhotons().
void G4Scintillation::SetTrackSecondariesFirst (const G4bool state) inline
Definition at line 279 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 279 of file G4Scintillation.hh
References fTrackSecondariesFirst.
Referenced by DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4OpticalPhysics::ConstructProcess(), and PHG4Reco::InitRun().
G4double G4Scintillation::single_exp (G4double t, G4double tau2) inline private
Definition at line 394 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 394 of file G4Scintillation.hh
Referenced by sample_time().
Member Data Documentation
G4EmSaturation* G4Scintillation::fEmSaturation private
Definition at line 270 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 270 of file G4Scintillation.hh
Referenced by AddSaturation(), GetSaturation(), PostStepDoIt(), RemoveSaturation(), and SetScintillationByParticleType().
G4double G4Scintillation::fExcitationRatio private
Definition at line 250 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 250 of file G4Scintillation.hh
Referenced by GetScintillationExcitationRatio(), PostStepDoIt(), and SetScintillationExcitationRatio().
G4PhysicsTable* G4Scintillation::fFastIntegralTable protected
Definition at line 240 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 240 of file G4Scintillation.hh
Referenced by BuildPhysicsTable(), BuildThePhysicsTable(), DumpPhysicsTable(), G4Scintillation(), GetFastIntegralTable(), PostStepDoIt(), and ~G4Scintillation().
G4bool G4Scintillation::fFiniteRiseTime private
Definition at line 246 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 246 of file G4Scintillation.hh
Referenced by GetFiniteRiseTime(), PostStepDoIt(), and SetFiniteRiseTime().
G4int G4Scintillation::fNumPhotons private
Definition at line 258 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 258 of file G4Scintillation.hh
Referenced by GetNumPhotons(), and PostStepDoIt().
G4bool G4Scintillation::fScintillationByParticleType private
Definition at line 252 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 252 of file G4Scintillation.hh
Referenced by GetScintillationByParticleType(), PostStepDoIt(), and SetScintillationByParticleType().
G4bool G4Scintillation::fScintillationTrackInfo private
Definition at line 254 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 254 of file G4Scintillation.hh
Referenced by GetScintillationTrackInfo(), PostStepDoIt(), and SetScintillationTrackInfo().
G4PhysicsTable* G4Scintillation::fSlowIntegralTable protected
Definition at line 241 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 241 of file G4Scintillation.hh
Referenced by BuildPhysicsTable(), BuildThePhysicsTable(), DumpPhysicsTable(), G4Scintillation(), GetSlowIntegralTable(), PostStepDoIt(), and ~G4Scintillation().
G4bool G4Scintillation::fStackingFlag private
Definition at line 256 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 256 of file G4Scintillation.hh
Referenced by GetStackPhotons(), PostStepDoIt(), and SetStackPhotons().
G4bool G4Scintillation::fTrackSecondariesFirst private
Definition at line 245 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 245 of file G4Scintillation.hh
Referenced by GetTrackSecondariesFirst(), PostStepDoIt(), and SetTrackSecondariesFirst().
G4double G4Scintillation::fYieldFactor private
Definition at line 248 of file G4Scintillation.hh.
View newest version in sPHENIX GitHub at line 248 of file G4Scintillation.hh
Referenced by GetScintillationYieldFactor(), PostStepDoIt(), and SetScintillationYieldFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4Scintillation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/src/G4Scintillation.cc