ECCE @ EIC Software: G4ChipsProtonInelasticXS Class Reference
G4ChipsProtonInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsProtonInelasticXS.hh>
Public Member Functions
G4ChipsProtonInelasticXS ()
~G4ChipsProtonInelasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
virtual G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
G4double CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum)
G4double CrossSectionLin (G4int targZ, G4int targN, G4double P)
G4double CrossSectionLog (G4int targZ, G4int targN, G4double lP)
G4double CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP)
G4double ThresholdMomentum (G4int targZ, G4int targN)
G4double EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double *Y)
Private Attributes
G4double * lastLEN
G4double * lastHEN
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
std::vector< G4double * > * LEN
std::vector< G4double * > * HEN
G4int j
std::vector< G4int > colN
std::vector< G4int > colZ
std::vector< G4double > colP
std::vector< G4double > colTH
std::vector< G4double > colCS
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 44 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ChipsProtonInelasticXS.hh
Constructor & Destructor Documentation
G4ChipsProtonInelasticXS::G4ChipsProtonInelasticXS ()
Definition at line 57 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ChipsProtonInelasticXS.cc
References HEN, lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, and LEN.
G4ChipsProtonInelasticXS::~G4ChipsProtonInelasticXS ()
Definition at line 73 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ChipsProtonInelasticXS.cc
References HEN, and LEN.
Member Function Documentation
G4double G4ChipsProtonInelasticXS::CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum) private
Definition at line 184 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 184 of file G4ChipsProtonInelasticXS.cc
References CrossSectionFormula(), CrossSectionLin(), CrossSectionLog(), EquLinearFit(), G4cout, G4endl, G4Log(), HEN, k, lastHEN, lastLEN, lastTH, LEN, n, nH, nL, P, and THmin.
Referenced by GetChipsCrossSection().
void G4ChipsProtonInelasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 84 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsProtonInelasticXS.cc
G4double G4ChipsProtonInelasticXS::CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP) private
Definition at line 358 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 358 of file G4ChipsProtonInelasticXS.cc
References a, c, d, e, G4cerr, G4endl, G4Exp(), G4Log(), Acts::UnitConstants::h, LE, P, and r.
Referenced by CalculateCrossSection(), CrossSectionLin(), and CrossSectionLog().
G4double G4ChipsProtonInelasticXS::CrossSectionLin (G4int targZ, G4int targN, G4double P) private
Definition at line 279 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 279 of file G4ChipsProtonInelasticXS.cc
References CrossSectionFormula(), G4cerr, G4endl, G4Exp(), G4Log(), pos(), and ThresholdMomentum().
Referenced by CalculateCrossSection().
G4double G4ChipsProtonInelasticXS::CrossSectionLog (G4int targZ, G4int targN, G4double lP) private
Definition at line 352 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 352 of file G4ChipsProtonInelasticXS.cc
References CrossSectionFormula(), G4Exp(), and P.
Referenced by CalculateCrossSection().
static const char* G4ChipsProtonInelasticXS::Default_Name () inline static
Definition at line 53 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ChipsProtonInelasticXS.hh
Referenced by G4ChipsComponentXS::G4ChipsComponentXS().
G4double G4ChipsProtonInelasticXS::EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double * Y) private
Definition at line 435 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 435 of file G4ChipsProtonInelasticXS.cc
References d, G4cerr, and G4endl.
Referenced by CalculateCrossSection().
G4double G4ChipsProtonInelasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg) virtual
!The slave functions must provide cross-sections in millibarns (mb) !! (not in IU)
Definition at line 113 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 113 of file G4ChipsProtonInelasticXS.cc
References CalculateCrossSection(), colCS, colN, colP, colTH, colZ, in, j, lastCS, lastI, lastN, lastP, lastTH, lastZ, and millibarn.
Referenced by GetIsoCrossSection().
G4double G4ChipsProtonInelasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 102 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ChipsProtonInelasticXS.cc
References GetChipsCrossSection(), and G4DynamicParticle::GetTotalMomentum().
G4bool G4ChipsProtonInelasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 92 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsProtonInelasticXS.cc
G4double G4ChipsProtonInelasticXS::ThresholdMomentum (G4int targZ, G4int targN) private
Definition at line 262 of file G4ChipsProtonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 262 of file G4ChipsProtonInelasticXS.cc
References dE, G4Proton::Definition(), G4Pow::GetInstance(), G4ParticleDefinition::GetPDGMass(), G4Pow::powA(), G4Proton::Proton(), and T.
Referenced by CrossSectionLin().
Member Data Documentation
std::vector<G4double> G4ChipsProtonInelasticXS::colCS private
Definition at line 96 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChipsProtonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsProtonInelasticXS::colN private
Definition at line 92 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsProtonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsProtonInelasticXS::colP private
Definition at line 94 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChipsProtonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsProtonInelasticXS::colTH private
Definition at line 95 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChipsProtonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsProtonInelasticXS::colZ private
Definition at line 93 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChipsProtonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double*>* G4ChipsProtonInelasticXS::HEN private
Definition at line 89 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChipsProtonInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsProtonInelasticXS(), and ~G4ChipsProtonInelasticXS().
G4int G4ChipsProtonInelasticXS::j private
Definition at line 91 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ChipsProtonInelasticXS.hh
Referenced by GetChipsCrossSection().
G4double G4ChipsProtonInelasticXS::lastCS private
Definition at line 86 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsProtonInelasticXS.hh
Referenced by G4ChipsProtonInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsProtonInelasticXS::lastHEN private
Definition at line 81 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChipsProtonInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsProtonInelasticXS().
G4int G4ChipsProtonInelasticXS::lastI private
Definition at line 87 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsProtonInelasticXS.hh
Referenced by G4ChipsProtonInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsProtonInelasticXS::lastLEN private
Definition at line 80 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChipsProtonInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsProtonInelasticXS().
G4int G4ChipsProtonInelasticXS::lastN private
Definition at line 82 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChipsProtonInelasticXS.hh
Referenced by G4ChipsProtonInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsProtonInelasticXS::lastP private
Definition at line 84 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsProtonInelasticXS.hh
Referenced by G4ChipsProtonInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsProtonInelasticXS::lastTH private
Definition at line 85 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsProtonInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsProtonInelasticXS(), and GetChipsCrossSection().
G4int G4ChipsProtonInelasticXS::lastZ private
Definition at line 83 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsProtonInelasticXS.hh
Referenced by G4ChipsProtonInelasticXS(), and GetChipsCrossSection().
std::vector<G4double*>* G4ChipsProtonInelasticXS::LEN private
Definition at line 88 of file G4ChipsProtonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsProtonInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsProtonInelasticXS(), and ~G4ChipsProtonInelasticXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsProtonInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsProtonInelasticXS.cc