ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/nf_Legendre.h File Reference
nf_Legendre.h File Reference
#include <nf_utilities.h>
#include <ptwXY.h>
Classes
struct nf_Legendre_s
Macros
#define nf_Legendre_minMaxOrder 4
#define nf_Legendre_maxMaxOrder 64
#define nf_Legendre_sizeIncrement 8
Typedefs
typedef struct nf_Legendre_s nf_Legendre
typedef nfu_status(* nf_Legendre_GaussianQuadrature_callback)(double x, double *y, void *argList)
Functions
nf_Legendre * nf_Legendre_new (int initialSize, int maxOrder, double *Cls, nfu_status *status)
nfu_status nf_Legendre_setup (nf_Legendre *nfL, int initialSize, int maxOrder)
nfu_status nf_Legendre_release (nf_Legendre *nfL)
nf_Legendre * nf_Legendre_free (nf_Legendre *nfL)
nf_Legendre * nf_Legendre_clone (nf_Legendre *nfL, nfu_status *status)
nfu_status nf_Legendre_reallocateCls (nf_Legendre *Legendre, int size, int forceSmallerResize)
int nf_Legendre_maxOrder (nf_Legendre *Legendre)
int nf_Legendre_allocated (nf_Legendre *Legendre)
double nf_Legendre_getCl (nf_Legendre *Legendre, int l, nfu_status *status)
nfu_status nf_Legendre_setCl (nf_Legendre *Legendre, int l, double Cl)
nfu_status nf_Legendre_normalize (nf_Legendre *Legendre)
double nf_Legendre_evauluateAtMu (nf_Legendre *nfL, double mu, nfu_status *status)
double nf_Legendre_PofL_atMu (int l, double mu)
ptwXYPoints * nf_Legendre_to_ptwXY (nf_Legendre *nfL, double accuracy, int biSectionMax, int checkForRoots, nfu_status *status)
nf_Legendre * nf_Legendre_from_ptwXY (ptwXYPoints *ptwXY, int maxOrder, nfu_status *status)
nfu_status nf_Legendre_GaussianQuadrature (int degree, double x1, double x2, nf_Legendre_GaussianQuadrature_callback func, void *argList, double *integral)
Macro Definition Documentation
#define nf_Legendre_maxMaxOrder 64
Definition at line 18 of file nf_Legendre.h.
View newest version in sPHENIX GitHub at line 18 of file nf_Legendre.h
Referenced by nf_Legendre_from_ptwXY(), nf_Legendre_reallocateCls(), and nf_Legendre_setup().
#define nf_Legendre_minMaxOrder 4
Definition at line 17 of file nf_Legendre.h.
View newest version in sPHENIX GitHub at line 17 of file nf_Legendre.h
Referenced by nf_Legendre_reallocateCls().
#define nf_Legendre_sizeIncrement 8
Definition at line 19 of file nf_Legendre.h.
View newest version in sPHENIX GitHub at line 19 of file nf_Legendre.h
Referenced by nf_Legendre_setCl().
Typedef Documentation
typedef struct nf_Legendre_s nf_Legendre
Definition at line 21 of file nf_Legendre.h.
View newest version in sPHENIX GitHub at line 21 of file nf_Legendre.h
typedef nfu_status(* nf_Legendre_GaussianQuadrature_callback)(double x, double *y, void *argList)
Definition at line 29 of file nf_Legendre.h.
View newest version in sPHENIX GitHub at line 29 of file nf_Legendre.h
Function Documentation
int nf_Legendre_allocated (nf_Legendre * Legendre)
Definition at line 112 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 112 of file nf_Legendre.cc
References nf_Legendre_s::allocated.
nf_Legendre* nf_Legendre_clone (nf_Legendre * nfL, nfu_status * status)
Definition at line 70 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 70 of file nf_Legendre.cc
References nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, and nf_Legendre_new().
double nf_Legendre_evauluateAtMu (nf_Legendre * nfL, double mu, nfu_status * status)
Definition at line 160 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 160 of file nf_Legendre.cc
References nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, nf_Legendre_PofL_atMu(), nfu_Okay, nfu_XOutsideDomain, and P.
Referenced by nf_Legendre_to_ptwXY2().
nf_Legendre* nf_Legendre_free (nf_Legendre * nfL)
Definition at line 61 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 61 of file nf_Legendre.cc
References nf_Legendre_release(), and nfu_free().
Referenced by nf_Legendre_from_ptwXY().
nf_Legendre* nf_Legendre_from_ptwXY (ptwXYPoints * ptwXY, int maxOrder, nfu_status * status)
Definition at line 250 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 250 of file nf_Legendre.cc
References check_license::err(), nf_Legendre_from_ptwXY_callback_s::f1, f1, nf_Legendre_from_ptwXY_callback_s::f2, f2, int(), nf_Legendre_from_ptwXY_callback_s::l, nf_Legendre_from_ptwXY_callback_s::mu1, nf_Legendre_from_ptwXY_callback_s::mu2, n, nf_Legendre_free(), nf_Legendre_from_ptwXY_callback(), nf_Legendre_GaussianQuadrature(), nf_Legendre_maxMaxOrder, nf_Legendre_new(), nf_Legendre_setCl(), nfu_Okay, nfu_XOutsideDomain, ptwXY_getStatus(), ptwXY_getXYPairAtIndex(), and ptwXY_length().
nfu_status nf_Legendre_GaussianQuadrature (int degree, double x1, double x2, nf_Legendre_GaussianQuadrature_callback func, void * argList, double * integral)
Definition at line 63 of file nf_Legendre_GaussianQuadrature.cc.
View newest version in sPHENIX GitHub at line 63 of file nf_Legendre_GaussianQuadrature.cc
References func, GaussianQuadrature_degrees, nf_Legendre_GaussianQuadrature_degree::n, n, nfu_Okay, nSets, sqrt_inv3, sum, nf_Legendre_GaussianQuadrature_degree::weights, x, x1, and nf_Legendre_GaussianQuadrature_degree::xis.
Referenced by nf_Legendre_from_ptwXY(), and ptwXY_integrateWithFunction2().
double nf_Legendre_getCl (nf_Legendre * Legendre, int l, nfu_status * status)
Definition at line 119 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 119 of file nf_Legendre.cc
References nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, nfu_badIndex, and nfu_Okay.
int nf_Legendre_maxOrder (nf_Legendre * Legendre)
Definition at line 105 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 105 of file nf_Legendre.cc
References nf_Legendre_s::maxOrder.
nf_Legendre* nf_Legendre_new (int initialSize, int maxOrder, double * Cls, nfu_status * status)
Definition at line 23 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 23 of file nf_Legendre.cc
References nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, nf_Legendre_setup(), nfu_free(), nfu_malloc(), nfu_mallocError, and nfu_Okay.
Referenced by nf_Legendre_clone(), and nf_Legendre_from_ptwXY().
nfu_status nf_Legendre_normalize (nf_Legendre * Legendre)
Definition at line 146 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 146 of file nf_Legendre.cc
References nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, nfu_divByZero, nfu_Okay, and norm.
double nf_Legendre_PofL_atMu (int l, double mu)
Definition at line 175 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 175 of file nf_Legendre.cc
Referenced by nf_Legendre_evauluateAtMu(), and nf_Legendre_from_ptwXY_callback().
nfu_status nf_Legendre_reallocateCls (nf_Legendre * Legendre, int size, int forceSmallerResize)
Definition at line 77 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 77 of file nf_Legendre.cc
References nf_Legendre_s::allocated, nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, nf_Legendre_maxMaxOrder, nf_Legendre_minMaxOrder, nfu_mallocError, nfu_Okay, and nfu_realloc().
Referenced by nf_Legendre_setCl(), and nf_Legendre_setup().
nfu_status nf_Legendre_release (nf_Legendre * nfL)
Definition at line 52 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 52 of file nf_Legendre.cc
References nf_Legendre_s::allocated, nf_Legendre_s::Cls, nfu_free(), and nfu_Okay.
Referenced by nf_Legendre_free().
nfu_status nf_Legendre_setCl (nf_Legendre * Legendre, int l, double Cl)
Definition at line 131 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 131 of file nf_Legendre.cc
References nf_Legendre_s::allocated, nf_Legendre_s::Cls, nf_Legendre_s::maxOrder, nf_Legendre_reallocateCls(), nf_Legendre_sizeIncrement, nfu_badIndex, and nfu_Okay.
Referenced by nf_Legendre_from_ptwXY().
nfu_status nf_Legendre_setup (nf_Legendre * nfL, int initialSize, int maxOrder)
Definition at line 40 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 40 of file nf_Legendre.cc
References nf_Legendre_s::maxOrder, nf_Legendre_maxMaxOrder, and nf_Legendre_reallocateCls().
Referenced by nf_Legendre_new().
ptwXYPoints* nf_Legendre_to_ptwXY (nf_Legendre * nfL, double accuracy, int biSectionMax, int checkForRoots, nfu_status * status)
Definition at line 219 of file nf_Legendre.cc.
View newest version in sPHENIX GitHub at line 219 of file nf_Legendre.cc
References dx, nf_Legendre_s::maxOrder, n, nf_Legendre_to_ptwXY2(), nfu_Okay, and ptwXY_createFromFunction().