ECCE @ EIC Software: GFlashEnergySpot Class Reference
GFlashEnergySpot Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashEnergySpot.hh>
Public Member Functions
GFlashEnergySpot ()
GFlashEnergySpot (const G4ThreeVector &point, G4double E)
~GFlashEnergySpot ()
void SetEnergy (const G4double &E)
G4double GetEnergy () const
void SetPosition (const G4ThreeVector &point)
G4ThreeVector GetPosition () const
Private Attributes
G4double Energy
G4ThreeVector Point
Detailed Description
Definition at line 46 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 46 of file GFlashEnergySpot.hh
Constructor & Destructor Documentation
GFlashEnergySpot::GFlashEnergySpot ()
Definition at line 43 of file GFlashEnergySpot.cc.
View newest version in sPHENIX GitHub at line 43 of file GFlashEnergySpot.cc
GFlashEnergySpot::GFlashEnergySpot (const G4ThreeVector & point, G4double E)
Definition at line 45 of file GFlashEnergySpot.cc.
View newest version in sPHENIX GitHub at line 45 of file GFlashEnergySpot.cc
References E, Energy, and Point.
GFlashEnergySpot::~GFlashEnergySpot ()
Definition at line 52 of file GFlashEnergySpot.cc.
View newest version in sPHENIX GitHub at line 52 of file GFlashEnergySpot.cc
Member Function Documentation
G4double GFlashEnergySpot::GetEnergy () const inline
Definition at line 55 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 55 of file GFlashEnergySpot.hh
References Energy.
Referenced by ExGflash1SensitiveDetector::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash2SensitiveDetector::ProcessHits().
G4ThreeVector GFlashEnergySpot::GetPosition () const inline
Definition at line 58 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 58 of file GFlashEnergySpot.hh
References Point.
Referenced by GFlashHitMaker::make(), ExGflash2SensitiveDetector::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash1SensitiveDetector::ProcessHits().
void GFlashEnergySpot::SetEnergy (const G4double & E) inline
Definition at line 54 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 54 of file GFlashEnergySpot.hh
References E, and Energy.
Referenced by GFlashShowerModel::ElectronDoIt().
void GFlashEnergySpot::SetPosition (const G4ThreeVector & point) inline
Definition at line 57 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 57 of file GFlashEnergySpot.hh
References Point.
Referenced by GFlashShowerModel::ElectronDoIt().
Member Data Documentation
G4double GFlashEnergySpot::Energy private
Definition at line 62 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 62 of file GFlashEnergySpot.hh
Referenced by GetEnergy(), GFlashEnergySpot(), and SetEnergy().
G4ThreeVector GFlashEnergySpot::Point private
Definition at line 63 of file GFlashEnergySpot.hh.
View newest version in sPHENIX GitHub at line 63 of file GFlashEnergySpot.hh
Referenced by GetPosition(), GFlashEnergySpot(), and SetPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashEnergySpot.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/GFlashEnergySpot.cc