ECCE @ EIC Software: pyEZgeom Namespace Reference
pyEZgeom Namespace Reference
Functions
void Construct ()
void ResetWorld (G4double dx, G4double dy, G4double dz)
void ResizeWorld (G4double dx, G4double dy, G4double dz)
void SetWorldMaterial (G4Material *amaterial)
void SetWorldVisibility (G4bool qvis)
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_CreateTubeVolume, CreateTubeVolume, 4, 6) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_CreateConeVolume
Variables
CreateConeVolume
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_CreateSphereVolume,
CreateSphereVolume,
3, 7) G4VPhysicalVolume
*(G4EzVolume G4VPhysicalVolume
*(G4EzVolume::* f2_PlaceIt)(const G4Transform3D &, G4int, G4EzVolume *) = &G4EzVolume::PlaceIt
void(G4EzVolume::* f1_SetColor)(const G4Color &) = &G4EzVolume::SetColor
void(G4EzVolume::* f2_SetColor)(G4double, G4double, G4double) = &G4EzVolume::SetColor
Function Documentation
pyEZgeom::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_CreateTubeVolume , CreateTubeVolume , 4 , 6)
void pyEZgeom::Construct ()
Definition at line 51 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 51 of file pyEzgeom.cc
References G4RunManager::GetRunManager().
void pyEZgeom::ResetWorld (G4double dx, G4double dy, G4double dz)
Definition at line 57 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 57 of file pyEzgeom.cc
References G4EzWorld::Reset().
Referenced by BOOST_PYTHON_MODULE().
void pyEZgeom::ResizeWorld (G4double dx, G4double dy, G4double dz)
Definition at line 62 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 62 of file pyEzgeom.cc
References G4EzWorld::Resize().
Referenced by BOOST_PYTHON_MODULE().
void pyEZgeom::SetWorldMaterial (G4Material * amaterial)
Definition at line 68 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 68 of file pyEzgeom.cc
References G4EzWorld::SetMaterial().
Referenced by BOOST_PYTHON_MODULE().
void pyEZgeom::SetWorldVisibility (G4bool qvis)
Definition at line 74 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 74 of file pyEzgeom.cc
References G4EzWorld::SetVisibility().
Referenced by BOOST_PYTHON_MODULE().
Variable Documentation
pyEZgeom::CreateConeVolume
Definition at line 85 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 85 of file pyEzgeom.cc
void(G4EzVolume::* pyEZgeom::f1_SetColor)(const G4Color &) = &G4EzVolume::SetColor
Definition at line 103 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 103 of file pyEzgeom.cc
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_CreateSphereVolume, CreateSphereVolume, 3, 7) G4VPhysicalVolume*(G4EzVolume G4VPhysicalVolume*(G4EzVolume::* pyEZgeom::f2_PlaceIt)(const G4Transform3D &, G4int, G4EzVolume *) = &G4EzVolume::PlaceIt
Definition at line 95 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 95 of file pyEzgeom.cc
Referenced by BOOST_PYTHON_MODULE().
void(G4EzVolume::* pyEZgeom::f2_SetColor)(G4double, G4double, G4double) = &G4EzVolume::SetColor
Definition at line 104 of file pyEzgeom.cc.
View newest version in sPHENIX GitHub at line 104 of file pyEzgeom.cc