ECCE @ EIC Software: G4XNNTotalLowE Class Reference
G4XNNTotalLowE Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XNNTotalLowE.hh>
Public Member Functions
G4XNNTotalLowE ()
virtual ~G4XNNTotalLowE ()
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual G4String Name () const
virtual G4double HighLimit () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double LowLimit () const
Private Types
typedef std::map< const
G4ParticleDefinition
*, G4LowEXsection *, std::less
< const G4ParticleDefinition * > > LowEMap
Private Member Functions
G4XNNTotalLowE (const G4XNNTotalLowE &right)
const G4XNNTotalLowE & operator= (const G4XNNTotalLowE &right)
Private Attributes
std::map< const
G4ParticleDefinition
*, G4LowEXsection *, std::less
< const G4ParticleDefinition * > > theCrossSections
Static Private Attributes
static const G4double ppTot [29]
static const G4double ss [29]
static const G4double npTot [29]
static const G4int tableSize = 29
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 40 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 40 of file G4XNNTotalLowE.hh
Member Typedef Documentation
typedef std::map<const G4ParticleDefinition *, G4LowEXsection*, std::less<const G4ParticleDefinition *> > G4XNNTotalLowE::LowEMap private
Definition at line 72 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 72 of file G4XNNTotalLowE.hh
Constructor & Destructor Documentation
G4XNNTotalLowE::G4XNNTotalLowE ()
Definition at line 53 of file G4XNNTotalLowE.cc.
View newest version in sPHENIX GitHub at line 53 of file G4XNNTotalLowE.cc
References it, G4Neutron::NeutronDefinition(), npTot, G4InuclParticleNames::pp, ppTot, G4Proton::ProtonDefinition(), ss, tableSize, and theCrossSections.
G4XNNTotalLowE::~G4XNNTotalLowE () virtual
Definition at line 72 of file G4XNNTotalLowE.cc.
View newest version in sPHENIX GitHub at line 72 of file G4XNNTotalLowE.cc
References G4Neutron::NeutronDefinition(), G4Proton::ProtonDefinition(), and theCrossSections.
G4XNNTotalLowE::G4XNNTotalLowE (const G4XNNTotalLowE & right) private
Member Function Documentation
G4double G4XNNTotalLowE::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 79 of file G4XNNTotalLowE.cc.
View newest version in sPHENIX GitHub at line 79 of file G4XNNTotalLowE.cc
References G4VCrossSectionSource::FindKeyParticle(), G4KineticTrack::Get4Momentum(), and theCrossSections.
virtual const G4CrossSectionVector* G4XNNTotalLowE::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 50 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 50 of file G4XNNTotalLowE.hh
virtual G4double G4XNNTotalLowE::HighLimit () const inline virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 54 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 54 of file G4XNNTotalLowE.hh
References CLHEP::GeV.
G4bool G4XNNTotalLowE::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 111 of file G4XNNTotalLowE.cc.
View newest version in sPHENIX GitHub at line 111 of file G4XNNTotalLowE.cc
References GeV.
G4String G4XNNTotalLowE::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 104 of file G4XNNTotalLowE.cc.
View newest version in sPHENIX GitHub at line 104 of file G4XNNTotalLowE.cc
const G4XNNTotalLowE& G4XNNTotalLowE::operator= (const G4XNNTotalLowE & right) private
Member Data Documentation
const G4double G4XNNTotalLowE::npTot static private
Initial value:
=
{
4250, 1380, 770, 585, 465, 300, 232, 175, 140, 100, 80, 63, 50, 40, 35, 34, 34, 36.5, 37., 37.7, 38, 39, 39.8, 40.5, 40.7, 41, 41.2, 41.5, 41.5
}
Definition at line 67 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 67 of file G4XNNTotalLowE.hh
Referenced by G4XNNTotalLowE().
const G4double G4XNNTotalLowE::ppTot static private
Initial value:
=
{
  2000, 600, 250, 180, 138, 92, 75, 57, 46, 35, 29.5, 25.5, 25, 24, 23.7, 25, 29, 39, 44, 47, 48, 48, 47.5, 47, 45.6, 45, 43.3, 42.9, 42.9
}
Definition at line 65 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 65 of file G4XNNTotalLowE.hh
Referenced by G4XNNTotalLowE().
const G4double G4XNNTotalLowE::ss static private
Initial value:
=
{
 1877.05, 1879.58, 1882.69, 1884.8, 1886.95, 1891.89, 1895.27, 1899.9, 1904.67, 1913.36, 1921.18, 1933.56, 1949.82, 1990.11, 2025.14, 2059.03, 2101.89, 2166.47, 2201.01, 2236.36, 2289.27, 2377.17, 2426.86, 2500.18, 2602.91, 2733.62, 2925.49, 3002.71
}
Definition at line 66 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 66 of file G4XNNTotalLowE.hh
Referenced by G4XNNTotalLowE().
const G4int G4XNNTotalLowE::tableSize = 29 static private
Definition at line 68 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 68 of file G4XNNTotalLowE.hh
Referenced by G4XNNTotalLowE().
std::map<const G4ParticleDefinition *, G4LowEXsection *, std::less<const G4ParticleDefinition *> > G4XNNTotalLowE::theCrossSections private
Definition at line 71 of file G4XNNTotalLowE.hh.
View newest version in sPHENIX GitHub at line 71 of file G4XNNTotalLowE.hh
Referenced by CrossSection(), G4XNNTotalLowE(), and ~G4XNNTotalLowE().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XNNTotalLowE.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XNNTotalLowE.cc