ECCE @ EIC Software: G4RDAugerData Class Reference
G4RDAugerData Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAugerData.hh>
Public Member Functions
G4RDAugerData ()
~G4RDAugerData ()
size_t NumberOfVacancies (G4int Z) const
G4int VacancyId (G4int Z, G4int vacancyIndex) const
size_t NumberOfTransitions (G4int Z, G4int vacancyIndex) const
G4int StartShellId (G4int Z, G4int initialVacancyIndex, G4int transitionShellIndex) const
G4double StartShellEnergy (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
G4double StartShellProb (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
size_t NumberOfAuger (G4int Z, G4int initIndex, G4int vacancyId) const
size_t AugerShellId (G4int Z, G4int vacancyIndex, G4int transId, G4int augerIndex) const
std::vector< G4RDAugerTransition > LoadData (G4int Z)
void BuildAugerTransitionTable ()
void PrintData (G4int Z)
G4RDAugerTransition * GetAugerTransition (G4int Z, G4int vacancyShellIndex)
std::vector
< G4RDAugerTransition > * GetAugerTransitions (G4int Z)
Private Types
typedef std::map< G4int,
std::vector
< G4RDAugerTransition >
, std::less< G4int > > trans_Table
Private Attributes
trans_Table augerTransitionTable
std::vector< G4int > nInitShells
std::vector< G4int > numberOfVacancies
Detailed Description
Definition at line 53 of file G4RDAugerData.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RDAugerData.hh
Member Typedef Documentation
typedef std::map<G4int,std::vector<G4RDAugerTransition>,std::less<G4int> > G4RDAugerData::trans_Table private
Definition at line 113 of file G4RDAugerData.hh.
View newest version in sPHENIX GitHub at line 113 of file G4RDAugerData.hh
Constructor & Destructor Documentation
G4RDAugerData::G4RDAugerData ()
Definition at line 50 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 50 of file G4RDAugerData.cc
References BuildAugerTransitionTable(), n, numberOfVacancies, and pos().
G4RDAugerData::~G4RDAugerData ()
Definition at line 66 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 66 of file G4RDAugerData.cc
Member Function Documentation
size_t G4RDAugerData::AugerShellId (G4int Z, G4int vacancyIndex, G4int transId, G4int augerIndex) const
Definition at line 179 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 179 of file G4RDAugerData.cc
References augerTransitionTable, FatalException, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
void G4RDAugerData::BuildAugerTransitionTable ()
Definition at line 479 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 479 of file G4RDAugerData.cc
References augerTransitionTable, G4DataVector::contains(), G4cout, G4endl, G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Element::GetZ(), LoadData(), m, material(), G4TrackingService::nMaterials, and Z.
Referenced by G4RDAugerData().
G4RDAugerTransition * G4RDAugerData::GetAugerTransition (G4int Z, G4int vacancyShellIndex)
Definition at line 551 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 551 of file G4RDAugerData.cc
References augerTransitionTable, and Z.
Referenced by G4RDAtomicTransitionManager::ReachableAugerShell().
std::vector< G4RDAugerTransition > * G4RDAugerData::GetAugerTransitions (G4int Z)
Definition at line 560 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 560 of file G4RDAugerData.cc
References augerTransitionTable, and Z.
std::vector< G4RDAugerTransition > G4RDAugerData::LoadData (G4int Z)
Definition at line 257 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 257 of file G4RDAugerData.cc
References a, e, FatalException, file, G4Exception(), k, MeV, n, nInitShells, numberOfVacancies, and Z.
Referenced by BuildAugerTransitionTable().
size_t G4RDAugerData::NumberOfAuger (G4int Z, G4int initIndex, G4int vacancyId) const
Definition at line 161 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 161 of file G4RDAugerData.cc
References augerTransitionTable, FatalException, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
size_t G4RDAugerData::NumberOfTransitions (G4int Z, G4int vacancyIndex) const
Definition at line 142 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 142 of file G4RDAugerData.cc
References augerTransitionTable, FatalException, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
size_t G4RDAugerData::NumberOfVacancies (G4int Z) const
Definition at line 113 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 113 of file G4RDAugerData.cc
References numberOfVacancies, and Z.
Referenced by G4RDAtomicTransitionManager::NumberOfReachableAugerShells().
void G4RDAugerData::PrintData (G4int Z)
Definition at line 520 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 520 of file G4RDAugerData.cc
References a, AugerShellId(), e, G4cout, G4endl, k, MeV, NumberOfAuger(), NumberOfTransitions(), numberOfVacancies, StartShellEnergy(), StartShellId(), StartShellProb(), and Z.
G4double G4RDAugerData::StartShellEnergy (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
Definition at line 216 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 216 of file G4RDAugerData.cc
References augerTransitionTable, energy, FatalException, G4Exception(), and numberOfVacancies.
Referenced by PrintData().
G4int G4RDAugerData::StartShellId (G4int Z, G4int initialVacancyIndex, G4int transitionShellIndex) const
Definition at line 196 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 196 of file G4RDAugerData.cc
References augerTransitionTable, FatalException, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
G4double G4RDAugerData::StartShellProb (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
Definition at line 236 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 236 of file G4RDAugerData.cc
References augerTransitionTable, FatalException, G4Exception(), and numberOfVacancies.
Referenced by PrintData().
G4int G4RDAugerData::VacancyId (G4int Z, G4int vacancyIndex) const
Definition at line 118 of file G4RDAugerData.cc.
View newest version in sPHENIX GitHub at line 118 of file G4RDAugerData.cc
References augerTransitionTable, FatalException, G4Exception(), n, and numberOfVacancies.
Member Data Documentation
trans_Table G4RDAugerData::augerTransitionTable private
Definition at line 114 of file G4RDAugerData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RDAugerData.hh
Referenced by AugerShellId(), BuildAugerTransitionTable(), GetAugerTransition(), GetAugerTransitions(), NumberOfAuger(), NumberOfTransitions(), StartShellEnergy(), StartShellId(), StartShellProb(), and VacancyId().
std::vector<G4int> G4RDAugerData::nInitShells private
Definition at line 121 of file G4RDAugerData.hh.
View newest version in sPHENIX GitHub at line 121 of file G4RDAugerData.hh
Referenced by LoadData().
std::vector<G4int> G4RDAugerData::numberOfVacancies private
Definition at line 122 of file G4RDAugerData.hh.
View newest version in sPHENIX GitHub at line 122 of file G4RDAugerData.hh
Referenced by AugerShellId(), G4RDAugerData(), LoadData(), NumberOfAuger(), NumberOfTransitions(), NumberOfVacancies(), PrintData(), StartShellEnergy(), StartShellId(), StartShellProb(), and VacancyId().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAugerData.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDAugerData.cc