ECCE @ EIC Software: G4ITFinder< T > Class Template Reference
G4ITFinder< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4AllITFinder.hh>
Public Member Functions
virtual ~G4ITFinder ()
virtual void Clear ()
virtual void SetVerboseLevel (G4int level)
virtual G4int GetVerboseLevel ()
virtual void Push (G4Track *track)
virtual G4ITType GetITType ()
virtual void UpdatePositionMap ()
G4KDTreeResultHandle FindNearestInRange (const T *point, int key, G4double)
G4KDTreeResultHandle FindNearest (const G4ThreeVector &, int key)
G4KDTreeResultHandle FindNearest (const T *, int key)
G4KDTreeResultHandle FindNearestInRange (const G4ThreeVector &, int key, G4double)
G4KDTreeResultHandle FindNearest (const T *, const T *)
Public Member Functions inherited from G4VITFinder
G4VITFinder ()
virtual ~G4VITFinder ()
Static Public Member Functions
static G4ITFinder * Instance ()
static void iUpdatePositionMap ()
Private Types
typedef std::map< int, G4KDTree * > TreeMap
Private Member Functions
G4ITFinder ()
Private Attributes
TreeMap fTree
int fVerbose
Static Private Attributes
static G4ThreadLocal G4ITFinder * fInstance
Detailed Description
template<typename T>
class G4ITFinder< T >
Localize the nearest neighbor For now, G4KDTree is used
Definition at line 62 of file G4AllITFinder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4AllITFinder.hh
Member Typedef Documentation
template<typename T > typedef std::map<int, G4KDTree*> G4ITFinder< T >::TreeMap private
Definition at line 82 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ITFinder.hh
Constructor & Destructor Documentation
template<typename T > G4ITFinder< T >::G4ITFinder () private
template<typename T > virtual G4ITFinder< T >::~G4ITFinder () virtual
Member Function Documentation
template<typename T > virtual void G4ITFinder< T >::Clear () virtual
Implements G4VITFinder.
template<typename T > G4KDTreeResultHandle G4ITFinder< T >::FindNearest (const G4ThreeVector & , int key)
Referenced by G4AllITFinder::FindNearest().
template<typename T > G4KDTreeResultHandle G4ITFinder< T >::FindNearest (const T * , int key)
template<typename T > G4KDTreeResultHandle G4ITFinder< T >::FindNearest (const T * , const T *)
template<typename T > G4KDTreeResultHandle G4ITFinder< T >::FindNearestInRange (const T * point, int key, G4double)
Referenced by G4AllITFinder::FindNearestInRange(), and G4DNAElectronHoleRecombination::FindReactant().
template<typename T > G4KDTreeResultHandle G4ITFinder< T >::FindNearestInRange (const G4ThreeVector & , int key, G4double)
template<typename T > virtual G4ITType G4ITFinder< T >::GetITType () inline virtual
Implements G4VITFinder.
Definition at line 104 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ITFinder.hh
template<typename T > virtual G4int G4ITFinder< T >::GetVerboseLevel () inline virtual
Implements G4VITFinder.
Definition at line 97 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ITFinder.hh
References G4ITFinder< T >::fVerbose.
template<typename T > static G4ITFinder* G4ITFinder< T >::Instance () static
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), G4AllITFinder::FindNearest(), G4AllITFinder::FindNearestInRange(), G4DNAElectronHoleRecombination::FindReactant(), G4DNAMolecularReaction::MakeReaction(), and G4DNAMoleculeEncounterStepper::Prepare().
template<typename T > static void G4ITFinder< T >::iUpdatePositionMap () static
template<typename T > virtual void G4ITFinder< T >::Push (G4Track * track) virtual
Implements G4VITFinder.
Referenced by G4DNAMolecularReaction::MakeReaction().
template<typename T > virtual void G4ITFinder< T >::SetVerboseLevel (G4int level) inline virtual
Implements G4VITFinder.
Definition at line 92 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ITFinder.hh
References G4ITFinder< T >::fVerbose.
template<typename T > virtual void G4ITFinder< T >::UpdatePositionMap () virtual
Implements G4VITFinder.
Referenced by G4DNAMoleculeEncounterStepper::Prepare().
Member Data Documentation
template<typename T > G4ThreadLocal G4ITFinder* G4ITFinder< T >::fInstance static private
Definition at line 79 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ITFinder.hh
template<typename T > TreeMap G4ITFinder< T >::fTree private
Definition at line 83 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ITFinder.hh
template<typename T > int G4ITFinder< T >::fVerbose private
Definition at line 85 of file G4ITFinder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ITFinder.hh
Referenced by G4ITFinder< T >::GetVerboseLevel(), and G4ITFinder< T >::SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4AllITFinder.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITFinder.hh