ECCE @ EIC Software: LXeWLSSlab Class Reference
LXeWLSSlab Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeWLSSlab.hh>
Public Member Functions
LXeWLSSlab (G4RotationMatrix *pRot, const G4ThreeVector &tlate, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, LXeDetectorConstruction *c)
Public Member Functions inherited from G4PVPlacement
G4PVPlacement (G4RotationMatrix *pRot, const G4ThreeVector &tlate, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (const G4Transform3D &Transform3D, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4LogicalVolume *pMotherLogical, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
G4PVPlacement (const G4Transform3D &Transform3D, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother, G4bool pMany, G4int pCopyNo, G4bool pSurfChk=false)
virtual ~G4PVPlacement ()
G4int GetCopyNo () const
void SetCopyNo (G4int CopyNo)
G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int maxErr=1)
G4PVPlacement (__void__ &)
G4PVPlacement (const G4PVPlacement &)=delete
G4PVPlacement & operator= (const G4PVPlacement &)=delete
G4bool IsMany () const
G4bool IsReplicated () const
G4bool IsParameterised () const
G4VPVParameterisation * GetParameterisation () const
void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const
G4bool IsRegularStructure () const
G4int GetRegularStructureId () const
EVolume VolumeType () const
Public Member Functions inherited from G4VPhysicalVolume
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4VPhysicalVolume (const G4VPhysicalVolume &)=delete
G4VPhysicalVolume & operator= (const G4VPhysicalVolume &)=delete
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
virtual G4int GetMultiplicity () const
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
EVolume DeduceVolumeType () const
Private Member Functions
void CopyValues ()
Private Attributes
LXeDetectorConstruction * fConstructor
G4int fNfibers
G4double fScint_x
G4double fScint_y
G4double fScint_z
G4double fSlab_z
Static Private Attributes
static G4LogicalVolume * fScintSlab_log = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicalVolume
static const G4PVManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions inherited from G4VPhysicalVolume
void InitialiseWorker (G4VPhysicalVolume *pMasterObject, G4RotationMatrix *pRot, const G4ThreeVector &tlate)
void TerminateWorker (G4VPhysicalVolume *pMasterObject)
Protected Attributes inherited from G4VPhysicalVolume
G4int instanceID
Static Protected Attributes inherited from G4VPhysicalVolume
static G4GEOM_DLL G4PVManager subInstanceManager
Detailed Description
Definition at line 43 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 43 of file LXeWLSSlab.hh
Constructor & Destructor Documentation
LXeWLSSlab::LXeWLSSlab (G4RotationMatrix * pRot, const G4ThreeVector & tlate, G4LogicalVolume * pMotherLogical, G4bool pMany, G4int pCopyNo, LXeDetectorConstruction * c)
Definition at line 43 of file LXeWLSSlab.cc.
View newest version in sPHENIX GitHub at line 43 of file LXeWLSSlab.cc
References CopyValues(), deg, fConstructor, fNfibers, fScint_x, fScint_y, fScintSlab_log, fSlab_z, G4Material::GetMaterial(), CLHEP::HepRotation::rotateY(), G4VPhysicalVolume::SetLogicalVolume(), and Y.
Member Function Documentation
void LXeWLSSlab::CopyValues () private
Definition at line 84 of file LXeWLSSlab.cc.
View newest version in sPHENIX GitHub at line 84 of file LXeWLSSlab.cc
References fConstructor, fNfibers, fScint_x, fScint_y, fScint_z, fSlab_z, LXeDetectorConstruction::GetNFibers(), LXeDetectorConstruction::GetScintX(), LXeDetectorConstruction::GetScintY(), LXeDetectorConstruction::GetScintZ(), and LXeDetectorConstruction::GetSlabZ().
Referenced by LXeWLSSlab().
Member Data Documentation
LXeDetectorConstruction* LXeWLSSlab::fConstructor private
Definition at line 58 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 58 of file LXeWLSSlab.hh
Referenced by CopyValues(), and LXeWLSSlab().
G4int LXeWLSSlab::fNfibers private
Definition at line 62 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 62 of file LXeWLSSlab.hh
Referenced by CopyValues(), and LXeWLSSlab().
G4double LXeWLSSlab::fScint_x private
Definition at line 63 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 63 of file LXeWLSSlab.hh
Referenced by CopyValues(), and LXeWLSSlab().
G4double LXeWLSSlab::fScint_y private
Definition at line 64 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 64 of file LXeWLSSlab.hh
Referenced by CopyValues(), and LXeWLSSlab().
G4double LXeWLSSlab::fScint_z private
Definition at line 65 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 65 of file LXeWLSSlab.hh
Referenced by CopyValues().
G4LogicalVolume * LXeWLSSlab::fScintSlab_log = nullptr static private
Definition at line 60 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 60 of file LXeWLSSlab.hh
Referenced by LXeWLSSlab().
G4double LXeWLSSlab::fSlab_z private
Definition at line 66 of file LXeWLSSlab.hh.
View newest version in sPHENIX GitHub at line 66 of file LXeWLSSlab.hh
Referenced by CopyValues(), and LXeWLSSlab().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeWLSSlab.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeWLSSlab.cc