ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/externals/expat/src/xmlrole.cc File Reference
xmlrole.cc File Reference
#include <stddef.h>
#include "expat_external.h"
#include "internal.h"
#include "xmlrole.h"
#include "ascii.h"
Macros
#define MIN_BYTES_PER_CHAR(enc) ((enc)->minBytesPerChar)
#define setTopLevel(state) ((state)->handler = internalSubset)
Typedefs
typedef int PTRCALL PROLOG_HANDLER (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
Functions
static int FASTCALL common (PROLOG_STATE *state, int tok)
static int PTRCALL prolog0 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL prolog1 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL prolog2 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL doctype0 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL doctype1 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL doctype2 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL doctype3 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL doctype4 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL doctype5 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL internalSubset (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity0 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity1 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity2 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity3 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity4 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity5 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity6 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity7 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity8 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity9 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL entity10 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL notation0 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL notation1 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL notation2 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL notation3 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL notation4 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist0 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist1 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist2 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist3 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist4 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist5 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist6 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist7 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist8 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL attlist9 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element0 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element1 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element2 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element3 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element4 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element5 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element6 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL element7 (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL declClose (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
static int PTRCALL error (PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
void XmlPrologStateInit (PROLOG_STATE *state)
Variables
static const char KW_ANY []
static const char KW_ATTLIST []
static const char KW_CDATA []
static const char KW_DOCTYPE []
static const char KW_ELEMENT []
static const char KW_EMPTY []
static const char KW_ENTITIES []
static const char KW_ENTITY []
static const char KW_FIXED []
static const char KW_ID []
static const char KW_IDREF []
static const char KW_IDREFS []
static const char KW_IMPLIED []
static const char KW_NDATA []
static const char KW_NMTOKEN []
static const char KW_NMTOKENS []
static const char KW_NOTATION []
static const char KW_PCDATA []
static const char KW_PUBLIC []
static const char KW_REQUIRED []
static const char KW_SYSTEM []
static PROLOG_HANDLER prolog0
static PROLOG_HANDLER prolog1
static PROLOG_HANDLER prolog2
static PROLOG_HANDLER doctype0
static PROLOG_HANDLER doctype1
static PROLOG_HANDLER doctype2
static PROLOG_HANDLER doctype3
static PROLOG_HANDLER doctype4
static PROLOG_HANDLER doctype5
static PROLOG_HANDLER internalSubset
static PROLOG_HANDLER entity0
static PROLOG_HANDLER entity1
static PROLOG_HANDLER entity2
static PROLOG_HANDLER entity3
static PROLOG_HANDLER entity4
static PROLOG_HANDLER entity5
static PROLOG_HANDLER entity6
static PROLOG_HANDLER entity7
static PROLOG_HANDLER entity8
static PROLOG_HANDLER entity9
static PROLOG_HANDLER entity10
static PROLOG_HANDLER notation0
static PROLOG_HANDLER notation1
static PROLOG_HANDLER notation2
static PROLOG_HANDLER notation3
static PROLOG_HANDLER notation4
static PROLOG_HANDLER attlist0
static PROLOG_HANDLER attlist1
static PROLOG_HANDLER attlist2
static PROLOG_HANDLER attlist3
static PROLOG_HANDLER attlist4
static PROLOG_HANDLER attlist5
static PROLOG_HANDLER attlist6
static PROLOG_HANDLER attlist7
static PROLOG_HANDLER attlist8
static PROLOG_HANDLER attlist9
static PROLOG_HANDLER element0
static PROLOG_HANDLER element1
static PROLOG_HANDLER element2
static PROLOG_HANDLER element3
static PROLOG_HANDLER element4
static PROLOG_HANDLER element5
static PROLOG_HANDLER element6
static PROLOG_HANDLER element7
static PROLOG_HANDLER declClose
static PROLOG_HANDLER error
Macro Definition Documentation
#define MIN_BYTES_PER_CHAR (enc) ((enc)->minBytesPerChar)
Definition at line 93 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 93 of file xmlrole.cc
Referenced by attlist8(), element2(), internalSubset(), prolog0(), and prolog1().
#define setTopLevel (state) ((state)->handler = internalSubset)
Definition at line 102 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 102 of file xmlrole.cc
Referenced by attlist1(), declClose(), entity10(), entity5(), and notation4().
Typedef Documentation
typedef int PTRCALL PROLOG_HANDLER(PROLOG_STATE *state, int tok, const char *ptr, const char *end, const ENCODING *enc)
Definition at line 105 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 105 of file xmlrole.cc
Function Documentation
static int PTRCALL attlist0 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 758 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 758 of file xmlrole.cc
References attlist1, common(), XML_ROLE_ATTLIST_ELEMENT_NAME, XML_ROLE_ATTLIST_NONE, XML_TOK_NAME, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL attlist1 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 776 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 776 of file xmlrole.cc
References attlist2, common(), setTopLevel, XML_ROLE_ATTLIST_NONE, XML_ROLE_ATTRIBUTE_NAME, XML_TOK_DECL_CLOSE, XML_TOK_NAME, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL attlist2 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 797 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 797 of file xmlrole.cc
References attlist3, attlist5, attlist8, common(), int(), KW_CDATA, KW_ENTITIES, KW_ENTITY, KW_ID, KW_IDREF, KW_IDREFS, KW_NMTOKEN, KW_NMTOKENS, KW_NOTATION, XML_ROLE_ATTLIST_NONE, XML_ROLE_ATTRIBUTE_TYPE_CDATA, XML_TOK_NAME, XML_TOK_OPEN_PAREN, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL attlist3 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 838 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 838 of file xmlrole.cc
References attlist4, common(), XML_ROLE_ATTLIST_NONE, XML_ROLE_ATTRIBUTE_ENUM_VALUE, XML_TOK_NAME, XML_TOK_NMTOKEN, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL attlist4 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 857 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 857 of file xmlrole.cc
References attlist3, attlist8, common(), XML_ROLE_ATTLIST_NONE, XML_TOK_CLOSE_PAREN, XML_TOK_OR, and XML_TOK_PROLOG_S.
static int PTRCALL attlist5 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 877 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 877 of file xmlrole.cc
References attlist6, common(), XML_ROLE_ATTLIST_NONE, XML_TOK_OPEN_PAREN, and XML_TOK_PROLOG_S.
static int PTRCALL attlist6 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 894 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 894 of file xmlrole.cc
References attlist7, common(), XML_ROLE_ATTLIST_NONE, XML_ROLE_ATTRIBUTE_NOTATION_VALUE, XML_TOK_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL attlist7 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 911 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 911 of file xmlrole.cc
References attlist6, attlist8, common(), XML_ROLE_ATTLIST_NONE, XML_TOK_CLOSE_PAREN, XML_TOK_OR, and XML_TOK_PROLOG_S.
static int PTRCALL attlist8 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 932 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 932 of file xmlrole.cc
References attlist1, attlist9, common(), KW_FIXED, KW_IMPLIED, KW_REQUIRED, MIN_BYTES_PER_CHAR, XML_ROLE_ATTLIST_NONE, XML_ROLE_DEFAULT_ATTRIBUTE_VALUE, XML_ROLE_IMPLIED_ATTRIBUTE_VALUE, XML_ROLE_REQUIRED_ATTRIBUTE_VALUE, XML_TOK_LITERAL, XML_TOK_POUND_NAME, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL attlist9 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 972 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 972 of file xmlrole.cc
References attlist1, common(), XML_ROLE_ATTLIST_NONE, XML_ROLE_FIXED_ATTRIBUTE_VALUE, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int FASTCALL common (PROLOG_STATE * state, int tok) static
Definition at line 1309 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1309 of file xmlrole.cc
References error, XML_ROLE_ERROR, and XML_TOK_PARAM_ENTITY_REF.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), __pythia_main.f__(), G4FTFModel::AdjustNucleons(), airy1(), airy1d(), airy2(), airy2d(), aiz(), alphas(), G4FTFAnnihilation::Annihilate(), ar3jet(), aran9(), arorie(), atrobo(), attflv(), attlist0(), attlist1(), attlist2(), attlist3(), attlist4(), attlist5(), attlist6(), attlist7(), attlist8(), attlist9(), attrad(), avscatcen(), biz(), calcta(), calcxsection(), cleanup(), compressevent(), converttohepmc(), crsjet(), declClose(), deriv(), doctype0(), doctype1(), doctype2(), doctype3(), doctype4(), doctype5(), dofistatescat(), doinstatescat(), dokinematics(), ei(), eixint(), element0(), element1(), element2(), element3(), element4(), element5(), element6(), element7(), entity0(), entity1(), entity10(), entity2(), entity3(), entity4(), entity5(), entity6(), entity7(), entity8(), entity9(), G4DiffractiveExcitation::ExciteParticipants(), expai(), expaid(), fgp1(), fgp2(), fgp3(), fhhiggscorr(), fhin(), fhsetflags(), fhsetpara(), fjet(), fjetrig(), flap(), flap1(), flap2(), fnjet(), fnkick(), fnkick2(), fnstru(), fnstrum(), fnstrus(), ftot(), ftotjet(), ftotrig(), g(), generatez(), genevent(), getcentrality(), getdeltat(), getinspliti(), getinsudafast(), getinsudakov(), getinsudared(), getltimemax(), getmass(), getmd(), getmdmax(), getmdmin(), getnatmdmin(), getneff(), getneffmax(), getnewmass(), getpdf(), getpdfxint(), getpdfxintexact(), getpnorad1(), getproba(), getqvec(), getscatterer(), getspliti(), getsscat(), getsudakov(), gett(), gettemp(), gettempmax(), getxsecint(), ghvq(), gmin(), gphoton(), hep2g4(), hiboost(), hifun(), hijcrs(), hijcsc(), hijels(), hijflv(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), hijsrt(), hijwds(), hiptdi(), hirnd(), hirnd2(), hirobo(), init(), initpythia(), insudaint(), internalSubset(), intpgghigh(), intpgglow(), intpqghigh(), intpqglow(), intpqq(), isprimhadron(), isprimstring(), issecstring(), jetini(), jewel(), klu(), lu1ent(), lu2ent(), lu3ent(), lu4ent(), luboei(), lucell(), luchge(), luclus(), lucomp(), ludecy(), luedit(), lueevt(), luerrm(), luexec(), lufowo(), lugive(), luhepc(), luindf(), lujmas(), lujoin(), lukfdi(), lulist(), luname(), luonia(), luprep(), luptdi(), luradk(), lurobo(), lushow(), lusphe(), lustrf(), lutabu(), lutest(), luthru(), luupda(), lux3jt(), lux4jt(), luxdif(), luxjet(), luxkfl(), luxtot(), luzdis(), main(), makebranch(), makecascade(), makeinsplit(), makesplitting(), makestrings(), makestrings_minl(), makestrings_vac(), maxscatcen(), medderiv(), medinit(), mednextevt(), notation0(), notation1(), notation2(), notation3(), notation4(), npart(), nthick(), odeint(), omg0(), parton(), pdfint(), pevrec(), phase(), pickvtx(), plu(), printtime(), profile(), prolog0(), prolog1(), prolog2(), py1ent(), py2ent(), py2frm(), py3ent(), py4ent(), py4frm(), py4jet(), py4jts(), py4jtw(), py6frm(), pyadsh(), pyalem(), pyalps(), pyangl(), pyapps(), pybesq(), pyboei(), pybook(), pycell(), pychge(), pycjdc(), pyckbd(), pyclus(), pycomp(), pycttr(), pydcyk(), pydecy(), pydiff(), pydisg(), pydocu(), pydump(), pyedit(), pyeevt(), pyerrm(), pyevnt(), pyevnw(), pyevol(), pyevwt(), pyexec(), pyfact(), pyfeyn(), pyfill(), pyfint(), pyfisb(), pyfowo(), pyfram(), pyfscr(), pygaga(), pygfxx(), pyggam(), pygive(), pyglui(), pygram(), pygraw(), pyh2xx(), pyhepc(), pyhext(), pyhfth(), pyhggm(), pyhidiff(), pyhifram(), pyhii3au(), pyhiinit(), pyhiinki(), pyhiinre(), pyhikcut(), pyhiklim(), pyhikmap(), pyhimaxi(), pyhimult(), pyhiovly(), pyhirand(), pyhiremn(), pyhiresd(), pyhiscat(), pyhisigh(), pyhispen(), pyhisspa(), pyhist(), pyhistat(), pyhistfe(), pyhistfu(), pyhitest(), pyhithia(), pyhiw1au(), pyhiw2au(), pyhiwidt(), pyhixtot(), pyi3au(), pyinbm(), pyindf(), pyinit(), pyinki(), pyinom(), pyinpr(), pyinre(), pyjmas(), pyjoin(), pyk(), pykcut(), pykfdi(), pykfin(), pyklim(), pykmap(), pylhef(), pylist(), pylogo(), pymass(), pymaxi(), pymemx(), pymewt(), pymign(), pymihg(), pymihk(), pymirm(), pymrun(), pymsin(), pymult(), pyname(), pynjdc(), pynmes(), pynull(), pyofsh(), pyonia(), pyonof(), pyoper(), pyovly(), pyp(), pypdel(), pypdfl(), pypdfu(), pypdga(), pypdpi(), pypdpo(), pypdpr(), pypile(), pyplot(), pypole(), pyprep(), pyptdi(), pyptfs(), pyptis(), pyptmi(), pyqqbh(), pyr(), pyradk(), pyrand(), pyreco(), pyremn(), pyresd(), pyrget(), pyrghm(), pyrnmq(), pyrobo(), pyrset(), pyrvch(), pyrvg1(), pyrvg2(), pyrvg3(), pyrvg4(), pyrvgl(), pyrvgw(), pyrvi1(), pyrvi2(), pyrvi3(), pyrvne(), pyrvsb(), pyrvsf(), pysave(), pyscat(), pysfdc(), pysgex(), pysghf(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyshow(), pysigh(), pyslha(), pyspen(), pysphe(), pyspli(), pysspa(), pystat(), pystbh(), pystfe(), pystfu(), pystop(), pystrf(), pysubh(), pysugi(), pytabu(), pytaud(), pytbbc(), pytbbn(), pytbdy(), pytbhb(), pytbhg(), pytbhq(), pytecm(), pytest(), pythia(), pythrg(), pythru(), pytune(), pyuedc(), pyupda(), pyupev(), pyupin(), pyupre(), pyveto(), pyw1au(), pyw2au(), pywaux(), pywdkk(), pywidt(), pywidx(), pyx3jt(), pyx4jt(), pyxdif(), pyxdin(), pyxjet(), pyxkfl(), pyxtee(), pyxtot(), pyxued(), pyxxz6(), pyzdis(), quench(), rkstepper(), rlu(), rluget(), rluset(), romg(), scatprimfunc(), setb(), splitfncint(), ssmssm(), sugra(), test(), ulalps(), ulangl(), ulmass(), upevnt(), upinit(), upveto(), vegas(), visaje(), wdsax(), wdsax1(), wdsax2(), and xsecint().
static int PTRCALL declClose (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1282 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1282 of file xmlrole.cc
References common(), prolog_state::role_none, setTopLevel, XML_TOK_DECL_CLOSE, and XML_TOK_PROLOG_S.
static int PTRCALL doctype0 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 221 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 221 of file xmlrole.cc
References common(), doctype1, XML_ROLE_DOCTYPE_NAME, XML_ROLE_DOCTYPE_NONE, XML_TOK_NAME, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL doctype1 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 239 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 239 of file xmlrole.cc
References common(), doctype2, doctype3, internalSubset, KW_PUBLIC, KW_SYSTEM, prolog2, XML_ROLE_DOCTYPE_CLOSE, XML_ROLE_DOCTYPE_INTERNAL_SUBSET, XML_ROLE_DOCTYPE_NONE, XML_TOK_DECL_CLOSE, XML_TOK_NAME, XML_TOK_OPEN_BRACKET, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL doctype2 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 269 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 269 of file xmlrole.cc
References common(), doctype3, XML_ROLE_DOCTYPE_NONE, XML_ROLE_DOCTYPE_PUBLIC_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL doctype3 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 286 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 286 of file xmlrole.cc
References common(), doctype4, XML_ROLE_DOCTYPE_NONE, XML_ROLE_DOCTYPE_SYSTEM_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL doctype4 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 303 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 303 of file xmlrole.cc
References common(), internalSubset, prolog2, XML_ROLE_DOCTYPE_CLOSE, XML_ROLE_DOCTYPE_INTERNAL_SUBSET, XML_ROLE_DOCTYPE_NONE, XML_TOK_DECL_CLOSE, XML_TOK_OPEN_BRACKET, and XML_TOK_PROLOG_S.
static int PTRCALL doctype5 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 323 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 323 of file xmlrole.cc
References common(), prolog2, XML_ROLE_DOCTYPE_CLOSE, XML_ROLE_DOCTYPE_NONE, XML_TOK_DECL_CLOSE, and XML_TOK_PROLOG_S.
static int PTRCALL element0 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 989 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 989 of file xmlrole.cc
References common(), element1, XML_ROLE_ELEMENT_NAME, XML_ROLE_ELEMENT_NONE, XML_TOK_NAME, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL element1 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1007 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1007 of file xmlrole.cc
References common(), declClose, element2, KW_ANY, KW_EMPTY, prolog_state::level, prolog_state::role_none, XML_ROLE_CONTENT_ANY, XML_ROLE_CONTENT_EMPTY, XML_ROLE_ELEMENT_NONE, XML_ROLE_GROUP_OPEN, XML_TOK_NAME, XML_TOK_OPEN_PAREN, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL element2 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1037 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1037 of file xmlrole.cc
References common(), element3, element6, element7, KW_PCDATA, prolog_state::level, MIN_BYTES_PER_CHAR, XML_ROLE_CONTENT_ELEMENT, XML_ROLE_CONTENT_ELEMENT_OPT, XML_ROLE_CONTENT_ELEMENT_PLUS, XML_ROLE_CONTENT_ELEMENT_REP, XML_ROLE_CONTENT_PCDATA, XML_ROLE_ELEMENT_NONE, XML_ROLE_GROUP_OPEN, XML_TOK_NAME, XML_TOK_NAME_ASTERISK, XML_TOK_NAME_PLUS, XML_TOK_NAME_QUESTION, XML_TOK_OPEN_PAREN, XML_TOK_POUND_NAME, XML_TOK_PREFIXED_NAME, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL element3 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1077 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1077 of file xmlrole.cc
References common(), declClose, element4, prolog_state::role_none, XML_ROLE_ELEMENT_NONE, XML_ROLE_GROUP_CLOSE, XML_ROLE_GROUP_CLOSE_REP, XML_TOK_CLOSE_PAREN, XML_TOK_CLOSE_PAREN_ASTERISK, XML_TOK_OR, and XML_TOK_PROLOG_S.
static int PTRCALL element4 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1102 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1102 of file xmlrole.cc
References common(), element5, XML_ROLE_CONTENT_ELEMENT, XML_ROLE_ELEMENT_NONE, XML_TOK_NAME, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL element5 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1120 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1120 of file xmlrole.cc
References common(), declClose, element4, prolog_state::role_none, XML_ROLE_ELEMENT_NONE, XML_ROLE_GROUP_CLOSE_REP, XML_TOK_CLOSE_PAREN_ASTERISK, XML_TOK_OR, and XML_TOK_PROLOG_S.
static int PTRCALL element6 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1141 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1141 of file xmlrole.cc
References common(), element7, prolog_state::level, XML_ROLE_CONTENT_ELEMENT, XML_ROLE_CONTENT_ELEMENT_OPT, XML_ROLE_CONTENT_ELEMENT_PLUS, XML_ROLE_CONTENT_ELEMENT_REP, XML_ROLE_ELEMENT_NONE, XML_ROLE_GROUP_OPEN, XML_TOK_NAME, XML_TOK_NAME_ASTERISK, XML_TOK_NAME_PLUS, XML_TOK_NAME_QUESTION, XML_TOK_OPEN_PAREN, XML_TOK_PREFIXED_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL element7 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1171 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1171 of file xmlrole.cc
References common(), declClose, element6, prolog_state::level, prolog_state::role_none, XML_ROLE_ELEMENT_NONE, XML_ROLE_GROUP_CHOICE, XML_ROLE_GROUP_CLOSE, XML_ROLE_GROUP_CLOSE_OPT, XML_ROLE_GROUP_CLOSE_PLUS, XML_ROLE_GROUP_CLOSE_REP, XML_ROLE_GROUP_SEQUENCE, XML_TOK_CLOSE_PAREN, XML_TOK_CLOSE_PAREN_ASTERISK, XML_TOK_CLOSE_PAREN_PLUS, XML_TOK_CLOSE_PAREN_QUESTION, XML_TOK_COMMA, XML_TOK_OR, and XML_TOK_PROLOG_S.
static int PTRCALL entity0 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 442 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 442 of file xmlrole.cc
References common(), entity1, entity2, XML_ROLE_ENTITY_NONE, XML_ROLE_GENERAL_ENTITY_NAME, XML_TOK_NAME, XML_TOK_PERCENT, and XML_TOK_PROLOG_S.
static int PTRCALL entity1 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 462 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 462 of file xmlrole.cc
References common(), entity7, XML_ROLE_ENTITY_NONE, XML_ROLE_PARAM_ENTITY_NAME, XML_TOK_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL entity10 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 644 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 644 of file xmlrole.cc
References common(), setTopLevel, XML_ROLE_ENTITY_COMPLETE, XML_ROLE_ENTITY_NONE, XML_TOK_DECL_CLOSE, and XML_TOK_PROLOG_S.
static int PTRCALL entity2 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 479 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 479 of file xmlrole.cc
References common(), declClose, entity3, entity4, KW_PUBLIC, KW_SYSTEM, prolog_state::role_none, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_VALUE, XML_TOK_LITERAL, XML_TOK_NAME, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL entity3 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 507 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 507 of file xmlrole.cc
References common(), entity4, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_PUBLIC_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL entity4 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 524 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 524 of file xmlrole.cc
References common(), entity5, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_SYSTEM_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL entity5 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 541 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 541 of file xmlrole.cc
References common(), entity6, KW_NDATA, setTopLevel, XML_ROLE_ENTITY_COMPLETE, XML_ROLE_ENTITY_NONE, XML_TOK_DECL_CLOSE, XML_TOK_NAME, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL entity6 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 564 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 564 of file xmlrole.cc
References common(), declClose, prolog_state::role_none, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_NOTATION_NAME, XML_TOK_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL entity7 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 582 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 582 of file xmlrole.cc
References common(), declClose, entity8, entity9, KW_PUBLIC, KW_SYSTEM, prolog_state::role_none, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_VALUE, XML_TOK_LITERAL, XML_TOK_NAME, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL entity8 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 610 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 610 of file xmlrole.cc
References common(), entity9, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_PUBLIC_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL entity9 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 627 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 627 of file xmlrole.cc
References common(), entity10, XML_ROLE_ENTITY_NONE, XML_ROLE_ENTITY_SYSTEM_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL error (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 1299 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1299 of file xmlrole.cc
References XML_ROLE_NONE.
static int PTRCALL internalSubset (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 340 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 340 of file xmlrole.cc
References attlist0, common(), doctype5, element0, entity0, KW_ATTLIST, KW_ELEMENT, KW_ENTITY, KW_NOTATION, MIN_BYTES_PER_CHAR, notation0, XML_ROLE_ATTLIST_NONE, XML_ROLE_COMMENT, XML_ROLE_DOCTYPE_NONE, XML_ROLE_ELEMENT_NONE, XML_ROLE_ENTITY_NONE, XML_ROLE_NONE, XML_ROLE_NOTATION_NONE, XML_ROLE_PARAM_ENTITY_REF, XML_ROLE_PI, XML_TOK_CLOSE_BRACKET, XML_TOK_COMMENT, XML_TOK_DECL_OPEN, XML_TOK_NONE, XML_TOK_PARAM_ENTITY_REF, XML_TOK_PI, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL notation0 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 661 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 661 of file xmlrole.cc
References common(), notation1, XML_ROLE_NOTATION_NAME, XML_ROLE_NOTATION_NONE, XML_TOK_NAME, and XML_TOK_PROLOG_S.
static int PTRCALL notation1 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 678 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 678 of file xmlrole.cc
References common(), KW_PUBLIC, KW_SYSTEM, notation2, notation3, XML_ROLE_NOTATION_NONE, XML_TOK_NAME, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL notation2 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 702 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 702 of file xmlrole.cc
References common(), notation4, XML_ROLE_NOTATION_NONE, XML_ROLE_NOTATION_PUBLIC_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL notation3 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 719 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 719 of file xmlrole.cc
References common(), declClose, prolog_state::role_none, XML_ROLE_NOTATION_NONE, XML_ROLE_NOTATION_SYSTEM_ID, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL notation4 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 737 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 737 of file xmlrole.cc
References common(), declClose, prolog_state::role_none, setTopLevel, XML_ROLE_NOTATION_NO_SYSTEM_ID, XML_ROLE_NOTATION_NONE, XML_ROLE_NOTATION_SYSTEM_ID, XML_TOK_DECL_CLOSE, XML_TOK_LITERAL, and XML_TOK_PROLOG_S.
static int PTRCALL prolog0 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 132 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 132 of file xmlrole.cc
References common(), doctype0, error, KW_DOCTYPE, MIN_BYTES_PER_CHAR, prolog1, XML_ROLE_COMMENT, XML_ROLE_DOCTYPE_NONE, XML_ROLE_INSTANCE_START, XML_ROLE_NONE, XML_ROLE_PI, XML_ROLE_XML_DECL, XML_TOK_BOM, XML_TOK_COMMENT, XML_TOK_DECL_OPEN, XML_TOK_INSTANCE_START, XML_TOK_PI, XML_TOK_PROLOG_S, XML_TOK_XML_DECL, and XmlNameMatchesAscii.
static int PTRCALL prolog1 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 169 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 169 of file xmlrole.cc
References common(), doctype0, error, KW_DOCTYPE, MIN_BYTES_PER_CHAR, XML_ROLE_COMMENT, XML_ROLE_DOCTYPE_NONE, XML_ROLE_INSTANCE_START, XML_ROLE_NONE, XML_ROLE_PI, XML_TOK_BOM, XML_TOK_COMMENT, XML_TOK_DECL_OPEN, XML_TOK_INSTANCE_START, XML_TOK_PI, XML_TOK_PROLOG_S, and XmlNameMatchesAscii.
static int PTRCALL prolog2 (PROLOG_STATE * state, int tok, const char * ptr, const char * end, const ENCODING * enc) static
Definition at line 200 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 200 of file xmlrole.cc
References common(), error, XML_ROLE_COMMENT, XML_ROLE_INSTANCE_START, XML_ROLE_NONE, XML_ROLE_PI, XML_TOK_COMMENT, XML_TOK_INSTANCE_START, XML_TOK_PI, and XML_TOK_PROLOG_S.
void XmlPrologStateInit (PROLOG_STATE * state)
Definition at line 1320 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 1320 of file xmlrole.cc
References prolog0.
Referenced by parserInit().
Variable Documentation
PROLOG_HANDLER attlist0 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by internalSubset().
PROLOG_HANDLER attlist1 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist0(), attlist8(), and attlist9().
PROLOG_HANDLER attlist2 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist1().
PROLOG_HANDLER attlist3 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist2(), and attlist4().
PROLOG_HANDLER attlist4 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist3().
PROLOG_HANDLER attlist5 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist2().
PROLOG_HANDLER attlist6 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist5(), and attlist7().
PROLOG_HANDLER attlist7 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist6().
PROLOG_HANDLER attlist8 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist2(), attlist4(), and attlist7().
PROLOG_HANDLER attlist9 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by attlist8().
PROLOG_HANDLER declClose static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element1(), element3(), element5(), element7(), entity2(), entity6(), entity7(), notation3(), and notation4().
PROLOG_HANDLER doctype0 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by prolog0(), and prolog1().
PROLOG_HANDLER doctype1 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by doctype0().
PROLOG_HANDLER doctype2 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by doctype1().
PROLOG_HANDLER doctype3 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by doctype1(), and doctype2().
PROLOG_HANDLER doctype4 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by doctype3().
PROLOG_HANDLER doctype5 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by internalSubset().
PROLOG_HANDLER element0 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by internalSubset().
PROLOG_HANDLER element1 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element0().
PROLOG_HANDLER element2 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element1().
PROLOG_HANDLER element3 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element2().
PROLOG_HANDLER element4 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element3(), and element5().
PROLOG_HANDLER element5 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element4().
PROLOG_HANDLER element6 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element2(), and element7().
PROLOG_HANDLER element7 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by element2(), and element6().
PROLOG_HANDLER entity0 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by internalSubset().
PROLOG_HANDLER entity1 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity0().
PROLOG_HANDLER entity10 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity9().
PROLOG_HANDLER entity2 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity0().
PROLOG_HANDLER entity3 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity2().
PROLOG_HANDLER entity4 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity2(), and entity3().
PROLOG_HANDLER entity5 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity4().
PROLOG_HANDLER entity6 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity5().
PROLOG_HANDLER entity7 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity1().
PROLOG_HANDLER entity8 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity7().
PROLOG_HANDLER entity9 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by entity7(), and entity8().
PROLOG_HANDLER error static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4AttCheck::Check(), G4ParameterisationPolyconeZ::CheckParametersValidity(), common(), Run::ComputeFluenceError(), Acts::Seedfinder< external_spacepoint_t >::createSeedsForGroup(), Rossegger::Ephi(), Rossegger::Ephi_(), Rossegger::Er(), Rossegger::Er_(), G4PVDivision::ErrorInAxis(), G4ReplicatedSlice::ErrorInAxis(), errorOf1DHistograms(), errorOf2DHistograms(), TpcSpaceChargeReconstructionHelper::extrapolate_phi2(), TpcSpaceChargeReconstructionHelper::extrapolate_z(), Rossegger::Ez(), Rossegger::Ez_(), Acts::IterativeVertexFinder< vfitter_t, sfinder_t >::fillPerigeesToFit(), AngleIndexList::getRangeList(), AngleIndexList::getRangeListSimple(), InitializeWidget(), Acts::GainMatrixSmoother< parameters_t >::operator()(), Acts::GainMatrixUpdater< parameters_t >::operator()(), operator<<(), Run::PrintFluence(), MicromegasClusterizer::process_event(), ProcessEvent(), prolog0(), prolog1(), prolog2(), G4ENDFTapeRead::ReadInData(), Rossegger::Rmn(), Rossegger::Rmn1(), Rossegger::Rmn1_(), Rossegger::Rmn2(), Rossegger::Rmn2_(), Rossegger::Rmn_(), Rossegger::Rnk(), Rossegger::Rnk_(), Rossegger::RPrime(), Rossegger::RPrime_(), SvtxTrack_v1::set_dca2d_error(), SvtxTrack_v2::set_dca2d_error(), SvtxTrack_v1::set_dca3d_xy_error(), SvtxTrack_v2::set_dca3d_xy_error(), SvtxTrack_v1::set_dca3d_z_error(), SvtxTrack_v2::set_dca3d_z_error(), TpcSpaceChargeReconstructionHelper::split(), G4AttCheck::Standard(), G4BulirschStoer::try_step(), and Run::WriteActivity().
PROLOG_HANDLER internalSubset static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by doctype1(), and doctype4().
const char KW_ANY[] static
Initial value:
= {
    ASCII_A, ASCII_N, ASCII_Y, '\0' }
Definition at line 37 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 37 of file xmlrole.cc
Referenced by element1().
const char KW_ATTLIST[] static
Initial value:
= {
    ASCII_A, ASCII_T, ASCII_T, ASCII_L, ASCII_I, ASCII_S, ASCII_T, '\0' }
Definition at line 39 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 39 of file xmlrole.cc
Referenced by internalSubset().
const char KW_CDATA[] static
Initial value:
= {
    ASCII_C, ASCII_D, ASCII_A, ASCII_T, ASCII_A, '\0' }
Definition at line 41 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 41 of file xmlrole.cc
Referenced by attlist2().
const char KW_DOCTYPE[] static
Initial value:
= {
    ASCII_D, ASCII_O, ASCII_C, ASCII_T, ASCII_Y, ASCII_P, ASCII_E, '\0' }
Definition at line 43 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 43 of file xmlrole.cc
Referenced by prolog0(), and prolog1().
const char KW_ELEMENT[] static
Initial value:
= {
    ASCII_E, ASCII_L, ASCII_E, ASCII_M, ASCII_E, ASCII_N, ASCII_T, '\0' }
Definition at line 45 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 45 of file xmlrole.cc
Referenced by internalSubset().
const char KW_EMPTY[] static
Initial value:
= {
    ASCII_E, ASCII_M, ASCII_P, ASCII_T, ASCII_Y, '\0' }
Definition at line 47 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 47 of file xmlrole.cc
Referenced by element1().
const char KW_ENTITIES[] static
Initial value:
= {
    ASCII_E, ASCII_N, ASCII_T, ASCII_I, ASCII_T, ASCII_I, ASCII_E, ASCII_S,
    '\0' }
Definition at line 49 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 49 of file xmlrole.cc
Referenced by attlist2().
const char KW_ENTITY[] static
Initial value:
= {
    ASCII_E, ASCII_N, ASCII_T, ASCII_I, ASCII_T, ASCII_Y, '\0' }
Definition at line 52 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 52 of file xmlrole.cc
Referenced by attlist2(), and internalSubset().
const char KW_FIXED[] static
Initial value:
= {
    ASCII_F, ASCII_I, ASCII_X, ASCII_E, ASCII_D, '\0' }
Definition at line 54 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 54 of file xmlrole.cc
Referenced by attlist8().
const char KW_ID[] static
Initial value:
= {
    ASCII_I, ASCII_D, '\0' }
Definition at line 56 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 56 of file xmlrole.cc
Referenced by attlist2().
const char KW_IDREF[] static
Initial value:
= {
    ASCII_I, ASCII_D, ASCII_R, ASCII_E, ASCII_F, '\0' }
Definition at line 58 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 58 of file xmlrole.cc
Referenced by attlist2().
const char KW_IDREFS[] static
Initial value:
= {
    ASCII_I, ASCII_D, ASCII_R, ASCII_E, ASCII_F, ASCII_S, '\0' }
Definition at line 60 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 60 of file xmlrole.cc
Referenced by attlist2().
const char KW_IMPLIED[] static
Initial value:
= {
    ASCII_I, ASCII_M, ASCII_P, ASCII_L, ASCII_I, ASCII_E, ASCII_D, '\0' }
Definition at line 66 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 66 of file xmlrole.cc
Referenced by attlist8().
const char KW_NDATA[] static
Initial value:
= {
    ASCII_N, ASCII_D, ASCII_A, ASCII_T, ASCII_A, '\0' }
Definition at line 72 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 72 of file xmlrole.cc
Referenced by entity5().
const char KW_NMTOKEN[] static
Initial value:
= {
    ASCII_N, ASCII_M, ASCII_T, ASCII_O, ASCII_K, ASCII_E, ASCII_N, '\0' }
Definition at line 74 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 74 of file xmlrole.cc
Referenced by attlist2().
const char KW_NMTOKENS[] static
Initial value:
= {
    ASCII_N, ASCII_M, ASCII_T, ASCII_O, ASCII_K, ASCII_E, ASCII_N, ASCII_S,
    '\0' }
Definition at line 76 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 76 of file xmlrole.cc
Referenced by attlist2().
const char KW_NOTATION[] static
Initial value:
=
    { ASCII_N, ASCII_O, ASCII_T, ASCII_A, ASCII_T, ASCII_I, ASCII_O, ASCII_N,
      '\0' }
Definition at line 79 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 79 of file xmlrole.cc
Referenced by attlist2(), and internalSubset().
const char KW_PCDATA[] static
Initial value:
= {
    ASCII_P, ASCII_C, ASCII_D, ASCII_A, ASCII_T, ASCII_A, '\0' }
Definition at line 82 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 82 of file xmlrole.cc
Referenced by element2().
const char KW_PUBLIC[] static
Initial value:
= {
    ASCII_P, ASCII_U, ASCII_B, ASCII_L, ASCII_I, ASCII_C, '\0' }
Definition at line 84 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 84 of file xmlrole.cc
Referenced by doctype1(), entity2(), entity7(), and notation1().
const char KW_REQUIRED[] static
Initial value:
= {
    ASCII_R, ASCII_E, ASCII_Q, ASCII_U, ASCII_I, ASCII_R, ASCII_E, ASCII_D,
    '\0' }
Definition at line 86 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 86 of file xmlrole.cc
Referenced by attlist8().
const char KW_SYSTEM[] static
Initial value:
= {
    ASCII_S, ASCII_Y, ASCII_S, ASCII_T, ASCII_E, ASCII_M, '\0' }
Definition at line 89 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 89 of file xmlrole.cc
Referenced by doctype1(), entity2(), entity7(), and notation1().
PROLOG_HANDLER notation0 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by internalSubset().
PROLOG_HANDLER notation1 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by notation0().
PROLOG_HANDLER notation2 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by notation1().
PROLOG_HANDLER notation3 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by notation1().
PROLOG_HANDLER notation4 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by notation2().
PROLOG_HANDLER prolog0 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by XmlPrologStateInit().
PROLOG_HANDLER prolog1 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by prolog0().
PROLOG_HANDLER prolog2 static
Definition at line 112 of file xmlrole.cc.
View newest version in sPHENIX GitHub at line 112 of file xmlrole.cc
Referenced by doctype1(), doctype4(), and doctype5().