ECCE @ EIC Software: G4NeutronInelasticXS Class Reference
G4NeutronInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutronInelasticXS.hh>
Public Member Functions
G4NeutronInelasticXS ()
~G4NeutronInelasticXS () final
G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *) final
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *, const G4Material *) final
G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *) final
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso, const G4Element *elm, const G4Material *mat) final
const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void CrossSectionDescription (std::ostream &) const final
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
void Initialise (G4int Z)
void InitialiseOnFly (G4int Z)
const G4String & FindDirectoryPath ()
const G4PhysicsVector * GetPhysicsVector (G4int Z)
G4PhysicsVector * RetrieveVector (std::ostringstream &in, G4bool warn)
G4double IsoCrossSection (G4double ekin, G4double logekin, G4int Z, G4int A)
G4NeutronInelasticXS & operator= (const G4NeutronInelasticXS &right)
G4NeutronInelasticXS (const G4NeutronInelasticXS &)
Private Attributes
G4ComponentGGHadronNucleusXsc * ggXsection
G4NistManager * nist
const G4ParticleDefinition * neutron
std::vector< G4double > temp
G4bool isMaster
Static Private Attributes
static G4ElementData * data = nullptr
static G4double coeff [MAXZINEL] = {1.0}
static G4double aeff [MAXZINEL] = {1.0}
static const G4int amin [MAXZINEL]
static const G4int amax [MAXZINEL]
static G4String gDataDirectory = ""
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 59 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4NeutronInelasticXS.hh
Constructor & Destructor Documentation
G4NeutronInelasticXS::G4NeutronInelasticXS () explicit
Definition at line 94 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 94 of file G4NeutronInelasticXS.cc
References G4cout, G4endl, ggXsection, G4NistManager::Instance(), isMaster, MAXZINEL, nist, G4VCrossSectionDataSet::SetForAllAtomsAndEnergies(), temp, and G4VCrossSectionDataSet::verboseLevel.
G4NeutronInelasticXS::~G4NeutronInelasticXS () final
Definition at line 110 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 110 of file G4NeutronInelasticXS.cc
References data, and isMaster.
G4NeutronInelasticXS::G4NeutronInelasticXS (const G4NeutronInelasticXS &) private
Member Function Documentation
void G4NeutronInelasticXS::BuildPhysicsTable (const G4ParticleDefinition & p) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 288 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 288 of file G4NeutronInelasticXS.cc
References FatalException, FindDirectoryPath(), G4cout, G4endl, G4Exception(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4ParticleDefinition::GetParticleName(), G4ProductionCutsTable::GetProductionCutsTable(), Initialise(), isMaster, mat, max, MAXZINEL, min, G4VCrossSectionDataSet::verboseLevel, and Z.
void G4NeutronInelasticXS::CrossSectionDescription (std::ostream & outFile) const final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 115 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 115 of file G4NeutronInelasticXS.cc
static const char* G4NeutronInelasticXS::Default_Name () inline static
Definition at line 67 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NeutronInelasticXS.hh
Referenced by G4INCLXXNeutronBuilder::Build(), G4NeutronCrossSectionXS::ConstructProcess(), and G4HadronPhysicsFTFQGSP_BERT::CreateModels().
const G4String & G4NeutronInelasticXS::FindDirectoryPath () private
Definition at line 346 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 346 of file G4NeutronInelasticXS.cc
References FatalException, G4Exception(), and gDataDirectory.
Referenced by BuildPhysicsTable(), and Initialise().
G4double G4NeutronInelasticXS::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 139 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 139 of file G4NeutronInelasticXS.cc
References aeff, CLHEP::barn, coeff, G4cout, G4endl, G4ComponentGGHadronNucleusXsc::GetInelasticElementCrossSection(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), GetPhysicsVector(), ggXsection, MAXZINEL, CLHEP::MeV, neutron, G4VCrossSectionDataSet::verboseLevel, and Z.
G4double G4NeutronInelasticXS::GetIsoCrossSection (const G4DynamicParticle * aParticle, G4int Z, G4int A, const G4Isotope * iso, const G4Element * elm, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 171 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 171 of file G4NeutronInelasticXS.cc
References A(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), IsoCrossSection(), and Z.
const G4PhysicsVector * G4NeutronInelasticXS::GetPhysicsVector (G4int Z) private
Definition at line 336 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 336 of file G4NeutronInelasticXS.cc
References InitialiseOnFly().
Referenced by GetElementCrossSection(), and IsoCrossSection().
void G4NeutronInelasticXS::Initialise (G4int Z) private
Definition at line 378 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 378 of file G4NeutronInelasticXS.cc
References A(), aeff, amax, amin, coeff, FindDirectoryPath(), gDataDirectory, G4NistManager::GetAtomicMassAmu(), G4ComponentGGHadronNucleusXsc::GetInelasticElementCrossSection(), G4PhysicsVector::GetMaxEnergy(), G4PhysicsVector::GetVectorLength(), ggXsection, neutron, nist, nmax, RetrieveVector(), v, v1, and Z.
Referenced by BuildPhysicsTable(), and InitialiseOnFly().
void G4NeutronInelasticXS::InitialiseOnFly (G4int Z) private
Definition at line 365 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 365 of file G4NeutronInelasticXS.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and Initialise().
Referenced by GetPhysicsVector().
G4bool G4NeutronInelasticXS::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 125 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 125 of file G4NeutronInelasticXS.cc
G4bool G4NeutronInelasticXS::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * , const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 132 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 132 of file G4NeutronInelasticXS.cc
G4double G4NeutronInelasticXS::IsoCrossSection (G4double ekin, G4double logekin, G4int Z, G4int A) private
Definition at line 182 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 182 of file G4NeutronInelasticXS.cc
References aeff, amax, amin, CLHEP::barn, coeff, emax, G4cout, G4endl, G4ComponentGGHadronNucleusXsc::GetInelasticElementCrossSection(), GetPhysicsVector(), ggXsection, MAXZINEL, CLHEP::MeV, neutron, G4VCrossSectionDataSet::verboseLevel, and Z.
Referenced by GetIsoCrossSection(), and SelectIsotope().
G4NeutronInelasticXS& G4NeutronInelasticXS::operator= (const G4NeutronInelasticXS & right) private
G4PhysicsVector * G4NeutronInelasticXS::RetrieveVector (std::ostringstream & in, G4bool warn) private
Definition at line 415 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 415 of file G4NeutronInelasticXS.cc
References FatalException, G4cout, G4endl, G4Exception(), G4PhysicsLogVector::Retrieve(), v, and G4VCrossSectionDataSet::verboseLevel.
Referenced by Initialise().
const G4Isotope * G4NeutronInelasticXS::SelectIsotope (const G4Element * anElement, G4double kinEnergy, G4double logE) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 236 of file G4NeutronInelasticXS.cc.
View newest version in sPHENIX GitHub at line 236 of file G4NeutronInelasticXS.cc
References amin, G4UniformRand, G4Element::GetIsotope(), G4Isotope::GetN(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZasInt(), IsoCrossSection(), MAXZINEL, G4InuclParticleNames::nn, sum, temp, and Z.
Member Data Documentation
G4double G4NeutronInelasticXS::aeff = {1.0} static private
Definition at line 118 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 118 of file G4NeutronInelasticXS.hh
Referenced by GetElementCrossSection(), Initialise(), and IsoCrossSection().
const G4int G4NeutronInelasticXS::amax static private
Initial value:
= {
  0,
  2,   4,   7,   9, 11,  13,  15,  18,  19,  22,
 23,  26,  27,  30, 31,  34,  37,  40,  41,  48,
 45,  50,  51,  54, 55,  58,  59,  64,  65,  70,
 71,  76,  75,   0,  0,   0,   0,   0,   0,  96,
  0, 100,   0,   0,  0, 110, 109, 116, 115, 124,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0, 181, 186,  0,   0,   0, 198, 197,   0,
  0, 208, 209,   0,  0,   0,   0,   0,   0,   0,
  0, 238}
Definition at line 120 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 120 of file G4NeutronInelasticXS.hh
Referenced by Initialise(), and IsoCrossSection().
const G4int G4NeutronInelasticXS::amin static private
Initial value:
= {
  0,
  1,   4,   6,   9, 10,  12,  14,  16,  19,  20,
 23,  24,  27,  28, 31,  32,  35,  36,  39,  40,
 45,  46,  50,  50, 55,  54,  59,  58,  63,  64,
 69,  70,  75,   0,  0,   0,   0,   0,   0,  90,
  0,  92,   0,   0,  0, 102, 107, 106, 113, 112,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0, 181, 180,  0,   0,   0, 192, 197,   0,
  0, 204, 209,   0,  0,   0,   0,   0,   0,   0,
  0, 235}
Definition at line 119 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 119 of file G4NeutronInelasticXS.hh
Referenced by Initialise(), IsoCrossSection(), and SelectIsotope().
G4double G4NeutronInelasticXS::coeff = {1.0} static private
Definition at line 117 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 117 of file G4NeutronInelasticXS.hh
Referenced by GetElementCrossSection(), Initialise(), and IsoCrossSection().
G4ElementData * G4NeutronInelasticXS::data = nullptr static private
Definition at line 116 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 116 of file G4NeutronInelasticXS.hh
Referenced by ~G4NeutronInelasticXS().
G4String G4NeutronInelasticXS::gDataDirectory = "" static private
Definition at line 121 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 121 of file G4NeutronInelasticXS.hh
Referenced by FindDirectoryPath(), and Initialise().
G4ComponentGGHadronNucleusXsc* G4NeutronInelasticXS::ggXsection private
Definition at line 107 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 107 of file G4NeutronInelasticXS.hh
Referenced by G4NeutronInelasticXS(), GetElementCrossSection(), Initialise(), and IsoCrossSection().
G4bool G4NeutronInelasticXS::isMaster private
Definition at line 114 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 114 of file G4NeutronInelasticXS.hh
Referenced by BuildPhysicsTable(), G4NeutronInelasticXS(), and ~G4NeutronInelasticXS().
const G4ParticleDefinition* G4NeutronInelasticXS::neutron private
Definition at line 110 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 110 of file G4NeutronInelasticXS.hh
Referenced by GetElementCrossSection(), Initialise(), and IsoCrossSection().
G4NistManager* G4NeutronInelasticXS::nist private
Definition at line 108 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4NeutronInelasticXS.hh
Referenced by G4NeutronInelasticXS(), and Initialise().
std::vector<G4double> G4NeutronInelasticXS::temp private
Definition at line 112 of file G4NeutronInelasticXS.hh.
View newest version in sPHENIX GitHub at line 112 of file G4NeutronInelasticXS.hh
Referenced by G4NeutronInelasticXS(), and SelectIsotope().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutronInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4NeutronInelasticXS.cc