ECCE @ EIC Software: G4CompetitiveFission Class Reference
G4CompetitiveFission Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4CompetitiveFission.hh>
Public Member Functions
G4CompetitiveFission ()
~G4CompetitiveFission () override
G4Fragment * EmittedFragment (G4Fragment *theNucleus) override
G4double GetEmissionProbability (G4Fragment *theNucleus) override
void SetFissionBarrier (G4VFissionBarrier *aBarrier)
void SetEmissionStrategy (G4VEmissionProbability *aFissionProb)
void SetLevelDensityParameter (G4VLevelDensityParameter *aLevelDensity)
G4double GetFissionBarrier (void) const
G4double GetLevelDensityParameter (void) const
G4double GetMaximalKineticEnergy (void) const
Public Member Functions inherited from G4VEvaporationChannel
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual void Initialise ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void Dump () const
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Private Member Functions
G4int FissionAtomicNumber (G4int A)
G4double MassDistribution (G4double x, G4int A)
G4int FissionCharge (G4int A, G4int Z, G4double Af)
G4double FissionKineticEnergy (G4int A, G4int Z, G4int Af1, G4int Zf1, G4int Af2, G4int Zf2, G4double U, G4double Tmax)
G4double Ratio (G4double A, G4double A11, G4double B1, G4double A00) const
G4double SymmetricRatio (G4int A, G4double A11) const
G4double AsymmetricRatio (G4int A, G4double A11) const
G4double LocalExp (G4double x) const
G4CompetitiveFission (const G4CompetitiveFission &right)
const G4CompetitiveFission & operator= (const G4CompetitiveFission &right)
G4bool operator== (const G4CompetitiveFission &right) const
G4bool operator!= (const G4CompetitiveFission &right) const
Private Attributes
G4double maxKineticEnergy
G4double fissionBarrier
G4double fissionProbability
G4VFissionBarrier * theFissionBarrierPtr
G4VEmissionProbability * theFissionProbabilityPtr
G4VLevelDensityParameter * theLevelDensityPtr
G4PairingCorrection * pairingCorrection
G4bool myOwnFissionProbability
G4bool myOwnFissionBarrier
G4bool myOwnLevelDensity
G4FissionParameters theParam
Additional Inherited Members
Protected Attributes inherited from G4VEvaporationChannel
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 46 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 46 of file G4CompetitiveFission.hh
Constructor & Destructor Documentation
G4CompetitiveFission::G4CompetitiveFission () explicit
Definition at line 49 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 49 of file G4CompetitiveFission.cc
References fissionBarrier, fissionProbability, G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetPairingCorrection(), maxKineticEnergy, myOwnFissionBarrier, myOwnFissionProbability, myOwnLevelDensity, pairingCorrection, theFissionBarrierPtr, theFissionProbabilityPtr, and theLevelDensityPtr.
G4CompetitiveFission::~G4CompetitiveFission () override
Definition at line 64 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 64 of file G4CompetitiveFission.cc
References myOwnFissionBarrier, myOwnFissionProbability, myOwnLevelDensity, theFissionBarrierPtr, theFissionProbabilityPtr, and theLevelDensityPtr.
G4CompetitiveFission::G4CompetitiveFission (const G4CompetitiveFission & right) private
Member Function Documentation
G4double G4CompetitiveFission::AsymmetricRatio (G4int A, G4double A11) const inline private
Definition at line 148 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 148 of file G4CompetitiveFission.hh
References Ratio().
Referenced by FissionKineticEnergy().
G4Fragment * G4CompetitiveFission::EmittedFragment (G4Fragment * theNucleus) override virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 92 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 92 of file G4CompetitiveFission.cc
References A(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4FissionParameters::DefineParameters(), FissionAtomicNumber(), fissionBarrier, FissionCharge(), FissionKineticEnergy(), G4RandomDirection(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4PairingCorrection::GetFissionPairingCorrection(), G4Fragment::GetGroundStateMass(), G4Fragment::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4Fragment::GetZ_asInt(), pairingCorrection, G4Fragment::SetMomentum(), G4Fragment::SetZandA_asInt(), theParam, Z, Z1, and Z2.
G4int G4CompetitiveFission::FissionAtomicNumber (G4int A) private
Definition at line 196 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 196 of file G4CompetitiveFission.cc
References C1, C2, G4lrint(), G4UniformRand, G4FissionParameters::GetA1(), G4FissionParameters::GetA2(), G4FissionParameters::GetAs(), G4FissionParameters::GetSigma2(), G4FissionParameters::GetSigmaS(), G4FissionParameters::GetW(), MassDistribution(), max, theParam, and w.
Referenced by EmittedFragment().
G4int G4CompetitiveFission::FissionCharge (G4int A, G4int Z, G4double Af) private
Definition at line 274 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 274 of file G4CompetitiveFission.cc
References A(), G4lrint(), and G4INCL::DeJongSpin::shoot().
Referenced by EmittedFragment().
G4double G4CompetitiveFission::FissionKineticEnergy (G4int A, G4int Z, G4int Af1, G4int Zf1, G4int Af2, G4int Zf2, G4double U, G4double Tmax) private
Definition at line 295 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 295 of file G4CompetitiveFission.cc
References A11, A12, A21, A22, AsymmetricRatio(), G4UniformRand, G4FissionParameters::GetA1(), G4FissionParameters::GetA2(), G4FissionParameters::GetAs(), G4Pow::GetInstance(), G4FissionParameters::GetSigma1(), G4FissionParameters::GetSigma2(), G4FissionParameters::GetSigmaS(), G4FissionParameters::GetW(), LocalExp(), max, CLHEP::MeV, G4INCL::DeJongSpin::shoot(), SymmetricRatio(), theParam, x1, x2, Z, and G4Pow::Z13().
Referenced by EmittedFragment().
G4double G4CompetitiveFission::GetEmissionProbability (G4Fragment * theNucleus) override virtual
Implements G4VEvaporationChannel.
Definition at line 71 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 71 of file G4CompetitiveFission.cc
References A(), G4VEmissionProbability::EmissionProbability(), G4VFissionBarrier::FissionBarrier(), fissionBarrier, fissionProbability, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4PairingCorrection::GetFissionPairingCorrection(), G4Fragment::GetZ_asInt(), maxKineticEnergy, pairingCorrection, theFissionBarrierPtr, theFissionProbabilityPtr, and Z.
G4double G4CompetitiveFission::GetFissionBarrier (void) const inline
Definition at line 122 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 122 of file G4CompetitiveFission.hh
References fissionBarrier.
G4double G4CompetitiveFission::GetLevelDensityParameter (void) const inline
G4double G4CompetitiveFission::GetMaximalKineticEnergy (void) const inline
Definition at line 127 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 127 of file G4CompetitiveFission.hh
References maxKineticEnergy.
G4double G4CompetitiveFission::LocalExp (G4double x) const inline private
Definition at line 160 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 160 of file G4CompetitiveFission.hh
References kdfinder::abs(), and G4Exp().
Referenced by FissionKineticEnergy(), and MassDistribution().
G4double G4CompetitiveFission::MassDistribution (G4double x, G4int A) private
Definition at line 252 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 252 of file G4CompetitiveFission.cc
References G4FissionParameters::GetA1(), G4FissionParameters::GetA2(), G4FissionParameters::GetAs(), G4FissionParameters::GetSigma1(), G4FissionParameters::GetSigma2(), G4FissionParameters::GetSigmaS(), G4FissionParameters::GetW(), LocalExp(), theParam, w, y1, y2, z1, and z2.
Referenced by FissionAtomicNumber().
G4bool G4CompetitiveFission::operator!= (const G4CompetitiveFission & right) const private
const G4CompetitiveFission& G4CompetitiveFission::operator= (const G4CompetitiveFission & right) private
G4bool G4CompetitiveFission::operator== (const G4CompetitiveFission & right) const private
G4double G4CompetitiveFission::Ratio (G4double A, G4double A11, G4double B1, G4double A00) const inline private
Definition at line 133 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 133 of file G4CompetitiveFission.hh
References A(), A00, and x.
Referenced by AsymmetricRatio(), and SymmetricRatio().
void G4CompetitiveFission::SetEmissionStrategy (G4VEmissionProbability * aFissionProb)
Definition at line 376 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 376 of file G4CompetitiveFission.cc
References myOwnFissionProbability, and theFissionProbabilityPtr.
Referenced by G4INCLXXInterface::G4INCLXXInterface().
void G4CompetitiveFission::SetFissionBarrier (G4VFissionBarrier * aBarrier)
Definition at line 368 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 368 of file G4CompetitiveFission.cc
References myOwnFissionBarrier, and theFissionBarrierPtr.
void G4CompetitiveFission::SetLevelDensityParameter (G4VLevelDensityParameter * aLevelDensity)
Definition at line 384 of file G4CompetitiveFission.cc.
View newest version in sPHENIX GitHub at line 384 of file G4CompetitiveFission.cc
References myOwnLevelDensity, and theLevelDensityPtr.
Referenced by G4INCLXXInterface::G4INCLXXInterface().
G4double G4CompetitiveFission::SymmetricRatio (G4int A, G4double A11) const inline private
Definition at line 154 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 154 of file G4CompetitiveFission.hh
References Ratio().
Referenced by FissionKineticEnergy().
Member Data Documentation
G4double G4CompetitiveFission::fissionBarrier private
Definition at line 101 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 101 of file G4CompetitiveFission.hh
Referenced by EmittedFragment(), G4CompetitiveFission(), GetEmissionProbability(), and GetFissionBarrier().
G4double G4CompetitiveFission::fissionProbability private
Definition at line 102 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 102 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), and GetEmissionProbability().
G4double G4CompetitiveFission::maxKineticEnergy private
Definition at line 100 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 100 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), GetEmissionProbability(), and GetMaximalKineticEnergy().
G4bool G4CompetitiveFission::myOwnFissionBarrier private
Definition at line 115 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 115 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), SetFissionBarrier(), and ~G4CompetitiveFission().
G4bool G4CompetitiveFission::myOwnFissionProbability private
Definition at line 114 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 114 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), SetEmissionStrategy(), and ~G4CompetitiveFission().
G4bool G4CompetitiveFission::myOwnLevelDensity private
Definition at line 116 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 116 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), SetLevelDensityParameter(), and ~G4CompetitiveFission().
G4PairingCorrection* G4CompetitiveFission::pairingCorrection private
Definition at line 112 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 112 of file G4CompetitiveFission.hh
Referenced by EmittedFragment(), G4CompetitiveFission(), and GetEmissionProbability().
G4VFissionBarrier* G4CompetitiveFission::theFissionBarrierPtr private
Definition at line 105 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 105 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), GetEmissionProbability(), SetFissionBarrier(), and ~G4CompetitiveFission().
G4VEmissionProbability* G4CompetitiveFission::theFissionProbabilityPtr private
Definition at line 108 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 108 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), GetEmissionProbability(), SetEmissionStrategy(), and ~G4CompetitiveFission().
G4VLevelDensityParameter* G4CompetitiveFission::theLevelDensityPtr private
Definition at line 111 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 111 of file G4CompetitiveFission.hh
Referenced by G4CompetitiveFission(), SetLevelDensityParameter(), and ~G4CompetitiveFission().
G4FissionParameters G4CompetitiveFission::theParam private
Definition at line 118 of file G4CompetitiveFission.hh.
View newest version in sPHENIX GitHub at line 118 of file G4CompetitiveFission.hh
Referenced by EmittedFragment(), FissionAtomicNumber(), FissionKineticEnergy(), and MassDistribution().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4CompetitiveFission.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/src/G4CompetitiveFission.cc