ECCE @ EIC Software: G4VisCommandGeometrySetColour Class Reference
G4VisCommandGeometrySetColour Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh>
Public Member Functions
G4VisCommandGeometrySetColour ()
virtual ~G4VisCommandGeometrySetColour ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Private Member Functions
G4VisCommandGeometrySetColour (const G4VisCommandGeometrySetColour &)
G4VisCommandGeometrySetColour & operator= (const G4VisCommandGeometrySetColour &)
Private Attributes
G4UIcommand * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Types inherited from G4VVisCommandGeometry
typedef std::map
< G4LogicalVolume *, const
G4VisAttributes * >
::const_iterator VisAttsMapIterator
Protected Member Functions inherited from G4VVisCommandGeometrySet
void Set (G4String logVolName, const G4VVisCommandGeometrySetFunction &, G4int requestedDepth)
void SetLVVisAtts (G4LogicalVolume *, const G4VVisCommandGeometrySetFunction &, G4int depth, G4int requestedDepth)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommandGeometry
static std::map
< G4LogicalVolume *, const
G4VisAttributes * > fVisAttsMap
Detailed Description
Definition at line 178 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 178 of file G4VisCommandsGeometrySet.hh
Constructor & Destructor Documentation
G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour ()
Definition at line 104 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 104 of file G4VisCommandsGeometrySet.cc
References fpCommand, G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), and G4UIcommand::SetParameter().
G4VisCommandGeometrySetColour::~G4VisCommandGeometrySetColour () virtual
Definition at line 137 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 137 of file G4VisCommandsGeometrySet.cc
References fpCommand.
G4VisCommandGeometrySetColour::G4VisCommandGeometrySetColour (const G4VisCommandGeometrySetColour &) private
Member Function Documentation
G4String G4VisCommandGeometrySetColour::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 142 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 142 of file G4VisCommandsGeometrySet.cc
G4VisCommandGeometrySetColour& G4VisCommandGeometrySetColour::operator= (const G4VisCommandGeometrySetColour &) private
void G4VisCommandGeometrySetColour::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 148 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 148 of file G4VisCommandsGeometrySet.cc
References G4ArrayOps::Set().
Member Data Documentation
G4UIcommand* G4VisCommandGeometrySetColour::fpCommand private
Definition at line 187 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 187 of file G4VisCommandsGeometrySet.hh
Referenced by G4VisCommandGeometrySetColour(), and ~G4VisCommandGeometrySetColour().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsGeometrySet.cc