ECCE @ EIC Software: G4InuclNuclei Class Reference
G4InuclNuclei Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclNuclei.hh>
Public Member Functions
G4InuclNuclei ()
G4InuclNuclei (const G4DynamicParticle &dynPart, Model model=DefaultModel)
G4InuclNuclei (G4int a, G4int z, G4double exc=0., Model model=DefaultModel)
G4InuclNuclei (const G4LorentzVector &mom, G4int a, G4int z, G4double exc=0., Model model=DefaultModel)
G4InuclNuclei (G4double ekin, G4int a, G4int z, G4double exc, Model model=DefaultModel)
G4InuclNuclei (const G4Fragment &aFragment, Model model=DefaultModel)
G4InuclNuclei (G4V3DNucleus *a3DNucleus, Model model=DefaultModel)
virtual ~G4InuclNuclei ()
G4InuclNuclei (const G4InuclNuclei &right)
G4InuclNuclei & operator= (const G4InuclNuclei &right)
G4bool operator== (const G4InuclNuclei &right)
void fill (G4int a, G4int z, G4double exc=0., Model model=DefaultModel)
void fill (const G4LorentzVector &mom, G4int a, G4int z, G4double exc=0., Model model=DefaultModel)
void fill (G4double ekin, G4int a, G4int z, G4double exc, Model model=DefaultModel)
void copy (const G4Fragment &aFragment, Model model=DefaultModel)
void copy (G4V3DNucleus *a3DNucleus, Model model=DefaultModel)
void clear ()
void setExitationEnergy (G4double e)
void setExitonConfiguration (const G4ExitonConfiguration &config)
void clearExitonConfiguration ()
G4int getA () const
G4int getZ () const
G4double getNucleiMass () const
G4double getExitationEnergy () const
G4double getExitationEnergyInGeV () const
const G4ExitonConfiguration & getExitonConfiguration () const
virtual void print (std::ostream &os) const
G4Fragment makeG4Fragment () const
operator G4Fragment () const
Public Member Functions inherited from G4InuclParticle
G4InuclParticle ()
G4InuclParticle (const G4DynamicParticle &dynPart, Model model=DefaultModel)
G4InuclParticle (const G4LorentzVector &mom, Model model=DefaultModel)
virtual ~G4InuclParticle ()
G4InuclParticle (const G4InuclParticle &right)
G4InuclParticle & operator= (const G4InuclParticle &right)
G4bool operator== (const G4InuclParticle &right)
G4bool operator!= (const G4InuclParticle &right)
void setEnergy ()
void setMomentum (const G4LorentzVector &mom)
void setKineticEnergy (G4double ekin)
void setMass (G4double mass)
G4double getMass () const
G4double getCharge () const
G4double getKineticEnergy () const
G4double getEnergy () const
G4double getMomModule () const
G4LorentzVector getMomentum () const
const G4ParticleDefinition * getDefinition () const
const G4DynamicParticle & getDynamicParticle () const
void setModel (Model model)
Model getModel () const
Static Public Member Functions
static G4double getNucleiMass (G4int a, G4int z, G4double exc=0.)
Static Protected Member Functions
static G4ParticleDefinition * makeDefinition (G4int a, G4int z)
static G4ParticleDefinition * makeNuclearFragment (G4int a, G4int z)
Private Attributes
G4ExitonConfiguration theExitonConfiguration
Additional Inherited Members
Public Types inherited from G4InuclParticle
enum Model {
DefaultModel, bullet, target, EPCollider,
INCascader, NonEquilib, Equilib, Fissioner,
BigBanger, PreCompound, Coalescence
}
Protected Member Functions inherited from G4InuclParticle
G4InuclParticle (const G4ParticleDefinition *pd, Model model=DefaultModel)
G4InuclParticle (const G4ParticleDefinition *pd, const G4LorentzVector &mom, Model model=DefaultModel)
G4InuclParticle (const G4ParticleDefinition *pd, G4double ekin, Model model=DefaultModel)
void setDefinition (const G4ParticleDefinition *pd)
Detailed Description
Definition at line 67 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 67 of file G4InuclNuclei.hh
Constructor & Destructor Documentation
G4InuclNuclei::G4InuclNuclei () inline
Definition at line 69 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 69 of file G4InuclNuclei.hh
G4InuclNuclei::G4InuclNuclei (const G4DynamicParticle & dynPart, Model model = DefaultModel) inline
Definition at line 71 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 71 of file G4InuclNuclei.hh
G4InuclNuclei::G4InuclNuclei (G4int a, G4int z, G4double exc = 0., Model model = DefaultModel) inline
Definition at line 74 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 74 of file G4InuclNuclei.hh
References setExitationEnergy().
G4InuclNuclei::G4InuclNuclei (const G4LorentzVector & mom, G4int a, G4int z, G4double exc = 0., Model model = DefaultModel) inline
Definition at line 79 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 79 of file G4InuclNuclei.hh
References setExitationEnergy().
G4InuclNuclei::G4InuclNuclei (G4double ekin, G4int a, G4int z, G4double exc, Model model = DefaultModel) inline
Definition at line 85 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 85 of file G4InuclNuclei.hh
References setExitationEnergy().
G4InuclNuclei::G4InuclNuclei (const G4Fragment & aFragment, G4InuclParticle::Model model = DefaultModel)
Definition at line 81 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 81 of file G4InuclNuclei.cc
References copy().
G4InuclNuclei::G4InuclNuclei (G4V3DNucleus * a3DNucleus, G4InuclParticle::Model model = DefaultModel)
Definition at line 127 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 127 of file G4InuclNuclei.cc
References copy().
virtual G4InuclNuclei::~G4InuclNuclei () inline virtual
Definition at line 95 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 95 of file G4InuclNuclei.hh
G4InuclNuclei::G4InuclNuclei (const G4InuclNuclei & right) inline
Definition at line 98 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 98 of file G4InuclNuclei.hh
Member Function Documentation
void G4InuclNuclei::clear (void)
Definition at line 176 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 176 of file G4InuclNuclei.cc
References clearExitonConfiguration(), G4InuclParticle::DefaultModel, G4InuclParticle::setDefinition(), and G4InuclParticle::setModel().
Referenced by G4CascadeCoalescence::makeLightIon().
void G4InuclNuclei::clearExitonConfiguration () inline
Definition at line 134 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 134 of file G4InuclNuclei.hh
References G4ExitonConfiguration::clear(), and theExitonConfiguration.
Referenced by clear(), and fill().
void G4InuclNuclei::copy (const G4Fragment & aFragment, Model model = DefaultModel)
Definition at line 87 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 87 of file G4InuclNuclei.cc
References fill(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetMomentum(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfChargedHoles(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetZ_asInt(), GeV, G4ExitonConfiguration::neutronHoles, G4ExitonConfiguration::neutronQuasiParticles, G4ExitonConfiguration::protonHoles, G4ExitonConfiguration::protonQuasiParticles, and theExitonConfiguration.
Referenced by G4InuclNuclei().
void G4InuclNuclei::copy (G4V3DNucleus * a3DNucleus, Model model = DefaultModel)
Definition at line 133 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 133 of file G4InuclNuclei.cc
References G4Nucleon::AreYouHit(), G4Proton::Definition(), G4Neutron::Definition(), fill(), G4V3DNucleus::GetCharge(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNextNucleon(), G4Nucleon::GetParticleType(), if(), G4ExitonConfiguration::neutronHoles, G4ExitonConfiguration::protonHoles, G4V3DNucleus::StartLoop(), and theExitonConfiguration.
void G4InuclNuclei::fill (G4int a, G4int z, G4double exc = 0., Model model = DefaultModel) inline
Definition at line 111 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 111 of file G4InuclNuclei.hh
Referenced by copy(), G4CascadeInterface::createBullet(), G4IntraNucleiCascader::createTarget(), G4CascadeInterface::createTarget(), G4CascadeCoalescence::makeLightIon(), G4CascadeRecoilMaker::makeRecoilNuclei(), and G4IntraNucleiCascader::releaseSecondary().
void G4InuclNuclei::fill (const G4LorentzVector & mom, G4int a, G4int z, G4double exc = 0., G4InuclParticle::Model model = DefaultModel)
Definition at line 158 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 158 of file G4InuclNuclei.cc
References clearExitonConfiguration(), makeDefinition(), G4InuclParticle::setDefinition(), setExitationEnergy(), G4InuclParticle::setModel(), and G4InuclParticle::setMomentum().
void G4InuclNuclei::fill (G4double ekin, G4int a, G4int z, G4double exc, G4InuclParticle::Model model = DefaultModel)
Definition at line 167 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 167 of file G4InuclNuclei.cc
References clearExitonConfiguration(), makeDefinition(), G4InuclParticle::setDefinition(), setExitationEnergy(), G4InuclParticle::setKineticEnergy(), and G4InuclParticle::setModel().
G4int G4InuclNuclei::getA () const inline
Definition at line 136 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 136 of file G4InuclNuclei.hh
References G4ParticleDefinition::GetAtomicMass(), and G4InuclParticle::getDefinition().
Referenced by G4InuclCollider::collide(), G4CascadeCheckBalance::collide(), G4NucleiModel::generateModel(), G4CascadeColliderBase::inelasticInteractionPossible(), G4IntraNucleiCascader::initialize(), G4NucleiModel::initializeCascad(), makeG4Fragment(), print(), G4InteractionCase::set(), and G4IntraNucleiCascader::setupCascade().
G4double G4InuclNuclei::getExitationEnergy () const inline
Definition at line 143 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 143 of file G4InuclNuclei.hh
References G4InuclParticle::getMass(), getNucleiMass(), CLHEP::GeV, and CLHEP::MeV.
Referenced by getExitationEnergyInGeV(), and print().
G4double G4InuclNuclei::getExitationEnergyInGeV () const inline
Definition at line 147 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 147 of file G4InuclNuclei.hh
References getExitationEnergy(), and CLHEP::GeV.
const G4ExitonConfiguration& G4InuclNuclei::getExitonConfiguration () const inline
Definition at line 149 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 149 of file G4InuclNuclei.hh
References theExitonConfiguration.
G4double G4InuclNuclei::getNucleiMass () const inline
Definition at line 139 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 139 of file G4InuclNuclei.hh
References G4InuclParticle::getDefinition(), G4ParticleDefinition::GetPDGMass(), CLHEP::GeV, and CLHEP::MeV.
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), G4CascadeRecoilMaker::deltaM(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), getExitationEnergy(), G4CascadeDeexciteBase::makeFragment(), makeNuclearFragment(), G4CascadeRecoilMaker::makeRecoilFragment(), and setExitationEnergy().
G4double G4InuclNuclei::getNucleiMass (G4int a, G4int z, G4double exc = 0.) static
Definition at line 276 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 276 of file G4InuclNuclei.cc
References G4NucleiProperties::GetNuclearMass(), GeV, mass, and MeV.
G4int G4InuclNuclei::getZ () const inline
Definition at line 137 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 137 of file G4InuclNuclei.hh
References G4ParticleDefinition::GetAtomicNumber(), and G4InuclParticle::getDefinition().
Referenced by G4InuclCollider::collide(), G4IntraNucleiCascader::generateCascade(), G4NucleiModel::generateModel(), G4CascadeColliderBase::inelasticInteractionPossible(), G4IntraNucleiCascader::initialize(), G4NucleiModel::initializeCascad(), makeG4Fragment(), print(), and G4IntraNucleiCascader::setupCascade().
G4ParticleDefinition * G4InuclNuclei::makeDefinition (G4int a, G4int z) static protected
Definition at line 204 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 204 of file G4InuclNuclei.cc
References G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), and makeNuclearFragment().
Referenced by fill().
G4Fragment G4InuclNuclei::makeG4Fragment () const
Definition at line 105 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 105 of file G4InuclNuclei.cc
References getA(), G4InuclParticle::getMomentum(), getZ(), GeV, G4ExitonConfiguration::neutronHoles, G4ExitonConfiguration::neutronQuasiParticles, G4ExitonConfiguration::protonHoles, G4ExitonConfiguration::protonQuasiParticles, G4Fragment::SetNumberOfExcitedParticle(), G4Fragment::SetNumberOfHoles(), and theExitonConfiguration.
G4ParticleDefinition * G4InuclNuclei::makeNuclearFragment (G4int a, G4int z) static protected
Definition at line 229 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 229 of file G4InuclNuclei.cc
References a, eplus, G4cerr, G4endl, getNucleiMass(), G4IonTable::GetNucleusEncoding(), GeV, G4TemplateAutoLock< _Mutex_t >::lock(), mass, MeV, G4ParticleDefinition::SetAntiPDGEncoding(), G4TemplateAutoLock< _Mutex_t >::unlock(), and z.
Referenced by makeDefinition().
G4InuclNuclei::operator G4Fragment () const
Definition at line 120 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 120 of file G4InuclNuclei.cc
G4InuclNuclei & G4InuclNuclei::operator= (const G4InuclNuclei & right)
Definition at line 284 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 284 of file G4InuclNuclei.cc
References G4InuclParticle::operator=(), and theExitonConfiguration.
G4bool G4InuclNuclei::operator== (const G4InuclNuclei & right) inline
Definition at line 105 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 105 of file G4InuclNuclei.hh
References theExitonConfiguration.
void G4InuclNuclei::print (std::ostream & os) const virtual
Reimplemented from G4InuclParticle.
Definition at line 294 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 294 of file G4InuclNuclei.cc
References G4ExitonConfiguration::empty(), G4endl, getA(), G4InuclParticle::getDefinition(), getExitationEnergy(), G4InuclParticle::getMass(), G4ParticleDefinition::GetParticleName(), getZ(), G4InuclParticle::print(), and theExitonConfiguration.
void G4InuclNuclei::setExitationEnergy (G4double e)
Definition at line 185 of file G4InuclNuclei.cc.
View newest version in sPHENIX GitHub at line 185 of file G4InuclNuclei.cc
References G4InuclParticle::getKineticEnergy(), G4InuclParticle::getMass(), getNucleiMass(), GeV, MeV, G4InuclParticle::setKineticEnergy(), and G4InuclParticle::setMass().
Referenced by G4InuclEvaporation::BreakItUp(), fill(), and G4InuclNuclei().
void G4InuclNuclei::setExitonConfiguration (const G4ExitonConfiguration & config) inline
Definition at line 130 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 130 of file G4InuclNuclei.hh
References theExitonConfiguration.
Referenced by G4CascadeRecoilMaker::makeRecoilNuclei().
Member Data Documentation
G4ExitonConfiguration G4InuclNuclei::theExitonConfiguration private
Definition at line 167 of file G4InuclNuclei.hh.
View newest version in sPHENIX GitHub at line 167 of file G4InuclNuclei.hh
Referenced by clearExitonConfiguration(), copy(), getExitonConfiguration(), makeG4Fragment(), operator=(), operator==(), print(), and setExitonConfiguration().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclNuclei.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InuclNuclei.cc