ECCE @ EIC Software: G4NuclideTableMessenger Class Reference
G4NuclideTableMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4NuclideTableMessenger.hh>
Public Member Functions
G4NuclideTableMessenger (G4NuclideTable *nuclideTable=0)
virtual ~G4NuclideTableMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4NuclideTableMessenger (const G4NuclideTableMessenger &)
Private Attributes
G4NuclideTable * theNuclideTable
G4UIdirectory * thisDirectory
G4UIcmdWithADoubleAndUnit * lifetimeCmd
G4UIcmdWithADoubleAndUnit * lToleranceCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 54 of file G4NuclideTableMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file G4NuclideTableMessenger.hh
Constructor & Destructor Documentation
G4NuclideTableMessenger::G4NuclideTableMessenger (G4NuclideTable * nuclideTable = 0)
particle/manage/nuclide/min_halflife
particle/manage/nuclide/level_tolerance
Definition at line 50 of file G4NuclideTableMessenger.cc.
View newest version in sPHENIX GitHub at line 50 of file G4NuclideTableMessenger.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, lifetimeCmd, lToleranceCmd, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and thisDirectory.
G4NuclideTableMessenger::~G4NuclideTableMessenger () virtual
Definition at line 81 of file G4NuclideTableMessenger.cc.
View newest version in sPHENIX GitHub at line 81 of file G4NuclideTableMessenger.cc
References lifetimeCmd, lToleranceCmd, and thisDirectory.
G4NuclideTableMessenger::G4NuclideTableMessenger (const G4NuclideTableMessenger &) inline private
Definition at line 64 of file G4NuclideTableMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4NuclideTableMessenger.hh
Member Function Documentation
void G4NuclideTableMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 88 of file G4NuclideTableMessenger.cc.
View newest version in sPHENIX GitHub at line 88 of file G4NuclideTableMessenger.cc
References G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), lifetimeCmd, lToleranceCmd, G4NuclideTable::SetLevelTolerance(), G4NuclideTable::SetThresholdOfHalfLife(), and theNuclideTable.
Member Data Documentation
G4UIcmdWithADoubleAndUnit* G4NuclideTableMessenger::lifetimeCmd private
Definition at line 70 of file G4NuclideTableMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4NuclideTableMessenger.hh
Referenced by G4NuclideTableMessenger(), SetNewValue(), and ~G4NuclideTableMessenger().
G4UIcmdWithADoubleAndUnit* G4NuclideTableMessenger::lToleranceCmd private
Definition at line 71 of file G4NuclideTableMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NuclideTableMessenger.hh
Referenced by G4NuclideTableMessenger(), SetNewValue(), and ~G4NuclideTableMessenger().
G4NuclideTable* G4NuclideTableMessenger::theNuclideTable private
Definition at line 64 of file G4NuclideTableMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4NuclideTableMessenger.hh
Referenced by SetNewValue().
G4UIdirectory* G4NuclideTableMessenger::thisDirectory private
Definition at line 69 of file G4NuclideTableMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NuclideTableMessenger.hh
Referenced by G4NuclideTableMessenger(), and ~G4NuclideTableMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4NuclideTableMessenger.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4NuclideTableMessenger.cc