ECCE @ EIC Software: G4hNuclearStoppingModel Class Reference
G4hNuclearStoppingModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hNuclearStoppingModel.hh>
Public Member Functions
G4hNuclearStoppingModel (const G4String &name)
~G4hNuclearStoppingModel ()
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
G4double HighEnergyLimit (const G4ParticleDefinition *, const G4Material *) const
G4double LowEnergyLimit (const G4ParticleDefinition *, const G4Material *) const
G4double HighEnergyLimit (const G4ParticleDefinition *) const
G4double LowEnergyLimit (const G4ParticleDefinition *) const
G4bool IsInCharge (const G4DynamicParticle *, const G4Material *) const
G4bool IsInCharge (const G4ParticleDefinition *, const G4Material *) const
void SetNuclearStoppingFluctuationsOn ()
void SetNuclearStoppingFluctuationsOff ()
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4hNuclearStoppingModel (G4hNuclearStoppingModel &)
G4hNuclearStoppingModel & operator= (const G4hNuclearStoppingModel &right)
void InitializeMe ()
G4double StoppingPower (const G4Material *material, G4double kineticEnergy, G4double z1, G4double m1) const
Private Attributes
G4VhNuclearStoppingPower * nStopingPowerTable
G4double factorPDG2AMU
G4double theZieglerFactor
G4String modelName
G4double lowEnergyLimit
G4double highEnergyLimit
Detailed Description
Definition at line 60 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4hNuclearStoppingModel.hh
Constructor & Destructor Documentation
G4hNuclearStoppingModel::G4hNuclearStoppingModel (const G4String & name)
Definition at line 69 of file G4hNuclearStoppingModel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4hNuclearStoppingModel.cc
References InitializeMe().
G4hNuclearStoppingModel::~G4hNuclearStoppingModel ()
Definition at line 111 of file G4hNuclearStoppingModel.cc.
View newest version in sPHENIX GitHub at line 111 of file G4hNuclearStoppingModel.cc
References nStopingPowerTable.
G4hNuclearStoppingModel::G4hNuclearStoppingModel (G4hNuclearStoppingModel &) private
Member Function Documentation
G4double G4hNuclearStoppingModel::HighEnergyLimit (const G4ParticleDefinition * , const G4Material *) const inline virtual
Implements G4VLowEnergyModel.
Definition at line 76 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4hNuclearStoppingModel.hh
References highEnergyLimit.
G4double G4hNuclearStoppingModel::HighEnergyLimit (const G4ParticleDefinition *) const inline virtual
Implements G4VLowEnergyModel.
Definition at line 84 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4hNuclearStoppingModel.hh
References highEnergyLimit.
void G4hNuclearStoppingModel::InitializeMe () private
Definition at line 77 of file G4hNuclearStoppingModel.cc.
View newest version in sPHENIX GitHub at line 77 of file G4hNuclearStoppingModel.cc
References cm2, eV, factorPDG2AMU, G4cout, G4endl, highEnergyLimit, lowEnergyLimit, MeV, modelName, nStopingPowerTable, source.hepunit::proton_mass_c2, G4VhNuclearStoppingPower::SetNuclearStoppingFluctuationsOff(), and theZieglerFactor.
Referenced by G4hNuclearStoppingModel().
G4bool G4hNuclearStoppingModel::IsInCharge (const G4DynamicParticle * , const G4Material *) const inline virtual
Implements G4VLowEnergyModel.
Definition at line 90 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4hNuclearStoppingModel.hh
G4bool G4hNuclearStoppingModel::IsInCharge (const G4ParticleDefinition * , const G4Material *) const inline virtual
Implements G4VLowEnergyModel.
Definition at line 94 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4hNuclearStoppingModel.hh
G4double G4hNuclearStoppingModel::LowEnergyLimit (const G4ParticleDefinition * , const G4Material *) const inline virtual
Implements G4VLowEnergyModel.
Definition at line 80 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4hNuclearStoppingModel.hh
References lowEnergyLimit.
G4double G4hNuclearStoppingModel::LowEnergyLimit (const G4ParticleDefinition *) const inline virtual
Implements G4VLowEnergyModel.
Definition at line 87 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4hNuclearStoppingModel.hh
References lowEnergyLimit.
G4hNuclearStoppingModel& G4hNuclearStoppingModel::operator= (const G4hNuclearStoppingModel & right) private
void G4hNuclearStoppingModel::SetNuclearStoppingFluctuationsOff () inline
Definition at line 101 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4hNuclearStoppingModel.hh
References nStopingPowerTable, and G4VhNuclearStoppingPower::SetNuclearStoppingFluctuationsOff().
void G4hNuclearStoppingModel::SetNuclearStoppingFluctuationsOn () inline
Definition at line 98 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4hNuclearStoppingModel.hh
References nStopingPowerTable, and G4VhNuclearStoppingPower::SetNuclearStoppingFluctuationsOn().
G4double G4hNuclearStoppingModel::StoppingPower (const G4Material * material, G4double kineticEnergy, G4double z1, G4double m1) const private
Definition at line 151 of file G4hNuclearStoppingModel.cc.
View newest version in sPHENIX GitHub at line 151 of file G4hNuclearStoppingModel.cc
References Acts::UnitConstants::g, G4Element::GetA(), G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Element::GetZ(), mole, nStopingPowerTable, and z2.
Referenced by TheValue().
G4double G4hNuclearStoppingModel::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 118 of file G4hNuclearStoppingModel.cc.
View newest version in sPHENIX GitHub at line 118 of file G4hNuclearStoppingModel.cc
References kdfinder::abs(), energy, eplus, factorPDG2AMU, G4DynamicParticle::GetCharge(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), StoppingPower(), theZieglerFactor, and z1.
G4double G4hNuclearStoppingModel::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 134 of file G4hNuclearStoppingModel.cc.
View newest version in sPHENIX GitHub at line 134 of file G4hNuclearStoppingModel.cc
References kdfinder::abs(), eplus, factorPDG2AMU, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), StoppingPower(), theZieglerFactor, and z1.
Member Data Documentation
G4double G4hNuclearStoppingModel::factorPDG2AMU private
Definition at line 123 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 123 of file G4hNuclearStoppingModel.hh
Referenced by InitializeMe(), and TheValue().
G4double G4hNuclearStoppingModel::highEnergyLimit private
Definition at line 131 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4hNuclearStoppingModel.hh
Referenced by HighEnergyLimit(), and InitializeMe().
G4double G4hNuclearStoppingModel::lowEnergyLimit private
Definition at line 130 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4hNuclearStoppingModel.hh
Referenced by InitializeMe(), and LowEnergyLimit().
G4String G4hNuclearStoppingModel::modelName private
Definition at line 129 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4hNuclearStoppingModel.hh
Referenced by InitializeMe().
G4VhNuclearStoppingPower* G4hNuclearStoppingModel::nStopingPowerTable private
Definition at line 121 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4hNuclearStoppingModel.hh
Referenced by InitializeMe(), SetNuclearStoppingFluctuationsOff(), SetNuclearStoppingFluctuationsOn(), StoppingPower(), and ~G4hNuclearStoppingModel().
G4double G4hNuclearStoppingModel::theZieglerFactor private
Definition at line 126 of file G4hNuclearStoppingModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4hNuclearStoppingModel.hh
Referenced by InitializeMe(), and TheValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hNuclearStoppingModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4hNuclearStoppingModel.cc