ECCE @ EIC Software: CML2RunAction Class Reference
CML2RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2RunAction.hh>
Public Member Functions
CML2RunAction (CML2Convergence *convergence, G4int nBeam, G4bool bOnlyVisio, G4int voxelX, G4int voxelY, G4int voxelz)
~CML2RunAction (void)
virtual G4Run * GenerateRun ()
void BeginOfRunAction (const G4Run *aRun)
void EndOfRunAction (const G4Run *aRun)
void setActualLoop (G4int nL)
void ChangeOutputFileName (G4String name)
G4int CopyNo (G4int ix, G4int iy, G4int iz)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4bool bRotationTranslationFileNames
CML2Convergence * convergence
G4Timer MyTime
G4double loopElapsedTime
G4int nBeam
G4int nLoop
G4bool bOnlyVisio
G4String filename
std::vector< G4String > fSDName
G4int fNx
G4int fNy
G4int fNz
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 54 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file ML2RunAction.hh
Constructor & Destructor Documentation
CML2RunAction::CML2RunAction (CML2Convergence * convergence, G4int nBeam, G4bool bOnlyVisio, G4int voxelX, G4int voxelY, G4int voxelz)
Definition at line 51 of file ML2RunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file ML2RunAction.cc
References bOnlyVisio, bRotationTranslationFileNames, convergence, fSDName, nBeam, and nLoop.
CML2RunAction::~CML2RunAction (void)
Definition at line 63 of file ML2RunAction.cc.
View newest version in sPHENIX GitHub at line 63 of file ML2RunAction.cc
References fSDName.
Member Function Documentation
void CML2RunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 76 of file ML2RunAction.cc.
View newest version in sPHENIX GitHub at line 76 of file ML2RunAction.cc
References bOnlyVisio, bRotationTranslationFileNames, convergence, G4cout, G4endl, CML2AcceleratorConstruction::getCurrentRotationString(), CML2PhantomConstruction::getCurrentTranslationString(), CML2PhantomConstruction::GetInstance(), CML2AcceleratorConstruction::GetInstance(), CML2Convergence::getNMaxLoops(), G4Run::GetRunID(), MyTime, nBeam, nLoop, G4Timer::Start(), CML2PhantomConstruction::writeInfo(), and CML2AcceleratorConstruction::writeInfo().
void CML2RunAction::ChangeOutputFileName (G4String name) inline
Definition at line 64 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file ML2RunAction.hh
References filename.
G4int CML2RunAction::CopyNo (G4int ix, G4int iy, G4int iz) inline
Definition at line 68 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file ML2RunAction.hh
References fNx, and fNz.
Referenced by EndOfRunAction().
void CML2RunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 114 of file ML2RunAction.cc.
View newest version in sPHENIX GitHub at line 114 of file ML2RunAction.cc
References convergence, CopyNo(), ML2Run::DumpAllScorer(), file, fNx, fNy, fNz, G4cout, G4endl, ML2Run::GetHitsMap(), G4Timer::GetUserElapsed(), gray, G4UserRunAction::IsMaster(), loopElapsedTime, MyTime, CML2Convergence::saveResults(), and G4Timer::Stop().
G4Run * CML2RunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 68 of file ML2RunAction.cc.
View newest version in sPHENIX GitHub at line 68 of file ML2RunAction.cc
References fSDName.
void CML2RunAction::setActualLoop (G4int nL) inline
Definition at line 62 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file ML2RunAction.hh
References nL, and nLoop.
Member Data Documentation
G4bool CML2RunAction::bOnlyVisio private
Definition at line 78 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 78 of file ML2RunAction.hh
Referenced by BeginOfRunAction(), and CML2RunAction().
G4bool CML2RunAction::bRotationTranslationFileNames private
Definition at line 73 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2RunAction.hh
Referenced by BeginOfRunAction(), and CML2RunAction().
CML2Convergence* CML2RunAction::convergence private
Definition at line 74 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 74 of file ML2RunAction.hh
Referenced by BeginOfRunAction(), CML2RunAction(), and EndOfRunAction().
G4String CML2RunAction::filename private
Definition at line 79 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2RunAction.hh
Referenced by ChangeOutputFileName().
G4int CML2RunAction::fNx private
Definition at line 84 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2RunAction.hh
Referenced by CopyNo(), and EndOfRunAction().
G4int CML2RunAction::fNy private
Definition at line 84 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2RunAction.hh
Referenced by EndOfRunAction().
G4int CML2RunAction::fNz private
Definition at line 84 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2RunAction.hh
Referenced by CopyNo(), and EndOfRunAction().
std::vector<G4String> CML2RunAction::fSDName private
Definition at line 81 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 81 of file ML2RunAction.hh
Referenced by CML2RunAction(), GenerateRun(), and ~CML2RunAction().
G4double CML2RunAction::loopElapsedTime private
Definition at line 76 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 76 of file ML2RunAction.hh
Referenced by EndOfRunAction().
G4Timer CML2RunAction::MyTime private
Definition at line 75 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2RunAction.hh
Referenced by BeginOfRunAction(), and EndOfRunAction().
G4int CML2RunAction::nBeam private
Definition at line 77 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2RunAction.hh
Referenced by BeginOfRunAction(), and CML2RunAction().
G4int CML2RunAction::nLoop private
Definition at line 77 of file ML2RunAction.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2RunAction.hh
Referenced by BeginOfRunAction(), CML2RunAction(), and setActualLoop().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2RunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2RunAction.cc