ECCE @ EIC Software: G4MuElecCrossSectionDataSet Class Reference
G4MuElecCrossSectionDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MuElecCrossSectionDataSet.hh>
Public Member Functions
G4MuElecCrossSectionDataSet (G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4MuElecCrossSectionDataSet ()
virtual G4double FindValue (G4double e, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *values, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *x, G4DataVector *values, G4DataVector *log_x, G4DataVector *log_values, G4int componentId)
virtual G4bool LoadData (const G4String &argFileName)
virtual G4bool LoadNonLogData (const G4String &argFileName)
virtual G4bool SaveData (const G4String &argFileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
G4String FullFileName (const G4String &argFileName) const
G4MuElecCrossSectionDataSet ()
G4MuElecCrossSectionDataSet (const G4MuElecCrossSectionDataSet &copy)
G4MuElecCrossSectionDataSet & operator= (const G4MuElecCrossSectionDataSet &right)
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4VDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Attributes
std::vector< G4VEMDataSet * > components
G4int z
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 37 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 37 of file G4MuElecCrossSectionDataSet.hh
Constructor & Destructor Documentation
G4MuElecCrossSectionDataSet::G4MuElecCrossSectionDataSet (G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 37 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 37 of file G4MuElecCrossSectionDataSet.cc
References z.
G4MuElecCrossSectionDataSet::~G4MuElecCrossSectionDataSet () virtual
Definition at line 46 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 46 of file G4MuElecCrossSectionDataSet.cc
References algorithm, and CleanUpComponents().
G4MuElecCrossSectionDataSet::G4MuElecCrossSectionDataSet () private
G4MuElecCrossSectionDataSet::G4MuElecCrossSectionDataSet (const G4MuElecCrossSectionDataSet & copy) private
Member Function Documentation
virtual void G4MuElecCrossSectionDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 54 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4MuElecCrossSectionDataSet.hh
References components.
Referenced by LoadData(), and LoadNonLogData().
void G4MuElecCrossSectionDataSet::CleanUpComponents (void) private
Definition at line 534 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 534 of file G4MuElecCrossSectionDataSet.cc
References components.
Referenced by LoadData(), LoadNonLogData(), and ~G4MuElecCrossSectionDataSet().
G4double G4MuElecCrossSectionDataSet::FindValue (G4double e, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 454 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 454 of file G4MuElecCrossSectionDataSet.cc
References components.
Referenced by G4MuElecElasticModel::CrossSectionPerVolume(), and G4MuElecInelasticModel::CrossSectionPerVolume().
G4String G4MuElecCrossSectionDataSet::FullFileName (const G4String & argFileName) const private
Definition at line 435 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 435 of file G4MuElecCrossSectionDataSet.cc
References FatalException, and G4Exception().
Referenced by LoadData(), LoadNonLogData(), and SaveData().
const G4VDataSetAlgorithm* G4MuElecCrossSectionDataSet::GetAlgorithm () const inline private
Definition at line 110 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 110 of file G4MuElecCrossSectionDataSet.hh
References algorithm.
Referenced by LoadData(), and LoadNonLogData().
virtual const G4VEMDataSet* G4MuElecCrossSectionDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 51 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 51 of file G4MuElecCrossSectionDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), PrintData(), G4MuElecInelasticModel::RandomSelect(), and SaveData().
virtual const G4DataVector& G4MuElecCrossSectionDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 63 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 63 of file G4MuElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetData().
virtual const G4DataVector& G4MuElecCrossSectionDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 60 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 60 of file G4MuElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetEnergies().
Referenced by SaveData().
virtual const G4DataVector& G4MuElecCrossSectionDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 69 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 69 of file G4MuElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogData().
virtual const G4DataVector& G4MuElecCrossSectionDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 66 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 66 of file G4MuElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogEnergies().
G4double G4MuElecCrossSectionDataSet::GetUnitData () const inline private
Definition at line 109 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 109 of file G4MuElecCrossSectionDataSet.hh
References unitData.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4double G4MuElecCrossSectionDataSet::GetUnitEnergies () const inline private
Definition at line 108 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4MuElecCrossSectionDataSet.hh
References unitEnergies.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4bool G4MuElecCrossSectionDataSet::LoadData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 54 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 54 of file G4MuElecCrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
Referenced by G4MuElecElasticModel::Initialise(), and G4MuElecInelasticModel::Initialise().
G4bool G4MuElecCrossSectionDataSet::LoadNonLogData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 221 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 221 of file G4MuElecCrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
virtual size_t G4MuElecCrossSectionDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 57 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MuElecCrossSectionDataSet.hh
References components.
Referenced by PrintData(), G4MuElecInelasticModel::RandomSelect(), and SaveData().
G4MuElecCrossSectionDataSet& G4MuElecCrossSectionDataSet::operator= (const G4MuElecCrossSectionDataSet & right) private
void G4MuElecCrossSectionDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 472 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 472 of file G4MuElecCrossSectionDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4VEMDataSet::PrintData().
virtual G4double G4MuElecCrossSectionDataSet::RandomSelect (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 85 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MuElecCrossSectionDataSet.hh
G4bool G4MuElecCrossSectionDataSet::SaveData (const G4String & argFileName) const virtual
Implements G4VEMDataSet.
Definition at line 366 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 366 of file G4MuElecCrossSectionDataSet.cc
References FatalException, FullFileName(), G4Exception(), GetComponent(), G4VEMDataSet::GetData(), GetEnergies(), GetUnitData(), GetUnitEnergies(), k, left, message(), n, and NumberOfComponents().
void G4MuElecCrossSectionDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 490 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 490 of file G4MuElecCrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetEnergiesData().
void G4MuElecCrossSectionDataSet::SetLogEnergiesData (G4DataVector * x, G4DataVector * values, G4DataVector * log_x, G4DataVector * log_values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 511 of file G4MuElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 511 of file G4MuElecCrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetLogEnergiesData().
Member Data Documentation
G4VDataSetAlgorithm* G4MuElecCrossSectionDataSet::algorithm private
Definition at line 103 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 103 of file G4MuElecCrossSectionDataSet.hh
Referenced by GetAlgorithm(), and ~G4MuElecCrossSectionDataSet().
std::vector<G4VEMDataSet*> G4MuElecCrossSectionDataSet::components private
Definition at line 99 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 99 of file G4MuElecCrossSectionDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), SetEnergiesData(), and SetLogEnergiesData().
G4double G4MuElecCrossSectionDataSet::unitData private
Definition at line 106 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MuElecCrossSectionDataSet.hh
Referenced by GetUnitData().
G4double G4MuElecCrossSectionDataSet::unitEnergies private
Definition at line 105 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 105 of file G4MuElecCrossSectionDataSet.hh
Referenced by GetUnitEnergies().
G4int G4MuElecCrossSectionDataSet::z private
Definition at line 101 of file G4MuElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 101 of file G4MuElecCrossSectionDataSet.hh
Referenced by G4MuElecCrossSectionDataSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MuElecCrossSectionDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4MuElecCrossSectionDataSet.cc