ECCE @ EIC Software: G4MTRunManagerKernel Class Reference
G4MTRunManagerKernel Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4MTRunManagerKernel.hh>
Public Member Functions
G4MTRunManagerKernel ()
virtual ~G4MTRunManagerKernel ()
void SetUpDecayChannels ()
void BroadcastAbortRun (G4bool softAbort)
Public Member Functions inherited from G4RunManagerKernel
G4RunManagerKernel ()
virtual ~G4RunManagerKernel ()
void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void WorkerDefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void SetPhysics (G4VUserPhysicsList *uPhys)
void InitializePhysics ()
G4bool RunInitialization (G4bool fakeRun=false)
void RunTermination ()
void WorkerUpdateWorldVolume ()
void UpdateRegion ()
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
void GeometryHasBeenModified ()
void PhysicsHasBeenModified ()
G4EventManager * GetEventManager () const
G4StackManager * GetStackManager () const
G4TrackingManager * GetTrackingManager () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
G4PrimaryTransformer * GetPrimaryTransformer () const
const G4String & GetVersionString () const
void SetVerboseLevel (G4int vl)
void SetGeometryToBeOptimized (G4bool vl)
G4int GetNumberOfParallelWorld () const
void SetNumberOfParallelWorld (G4int i)
G4VUserPhysicsList * GetPhysicsList () const
G4VPhysicalVolume * GetCurrentWorld () const
G4int GetNumberOfStaticAllocators () const
Static Public Member Functions
static void StartThread (G4WorkerThread *context)
static G4WorkerThread * GetWorkerThread ()
Static Public Member Functions inherited from G4RunManagerKernel
static G4RunManagerKernel * GetRunManagerKernel ()
Protected Member Functions
void SetupShadowProcess () const
Protected Member Functions inherited from G4RunManagerKernel
G4RunManagerKernel (RMKType rmkType)
void SetupDefaultRegion ()
void SetupPhysics ()
void ResetNavigator ()
void BuildPhysicsTables (G4bool fakeRun)
void CheckRegions ()
void PropagateGenericIonID ()
Static Private Attributes
static G4ThreadLocal
G4WorkerThread * wThreadContext = 0
static std::vector
< G4WorkerRunManager * > * workerRMvector = 0
Additional Inherited Members
Public Types inherited from G4RunManagerKernel
enum RMKType { sequentialRMK, masterRMK, workerRMK }
Protected Attributes inherited from G4RunManagerKernel
RMKType runManagerKernelType
G4Region * defaultRegion
G4Region * defaultRegionForParallelWorld
G4bool geometryNeedsToBeClosed
Detailed Description
Definition at line 65 of file G4MTRunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4MTRunManagerKernel.hh
Constructor & Destructor Documentation
G4MTRunManagerKernel::G4MTRunManagerKernel ()
Definition at line 38 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 38 of file G4MTRunManagerKernel.cc
References FatalException, G4Exception(), G4Threading::SetMultithreadedApplication(), G4TemplateAutoLock< _Mutex_t >::unlock(), and workerRMvector.
G4MTRunManagerKernel::~G4MTRunManagerKernel () virtual
Definition at line 54 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 54 of file G4MTRunManagerKernel.cc
References FatalException, G4Exception(), and workerRMvector.
Member Function Documentation
void G4MTRunManagerKernel::BroadcastAbortRun (G4bool softAbort)
Definition at line 244 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 244 of file G4MTRunManagerKernel.cc
References workerRMvector.
Referenced by G4MTRunManager::AbortRun().
G4WorkerThread * G4MTRunManagerKernel::GetWorkerThread () static
Definition at line 102 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 102 of file G4MTRunManagerKernel.cc
References wThreadContext.
void G4MTRunManagerKernel::SetUpDecayChannels ()
Definition at line 227 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 227 of file G4MTRunManagerKernel.cc
References G4DecayTable::entries(), G4VDecayChannel::GetDaughter(), G4DecayTable::GetDecayChannel(), G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), G4ParticleTableIterator< K, V >::reset(), and G4ParticleTableIterator< K, V >::value().
Referenced by G4MTRunManager::InitializeEventLoop().
void G4MTRunManagerKernel::SetupShadowProcess () const protected virtual
Reimplemented from G4RunManagerKernel.
Definition at line 72 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4MTRunManagerKernel.cc
References G4RunManagerKernel::SetupShadowProcess().
void G4MTRunManagerKernel::StartThread (G4WorkerThread * context) static
!!!!!!!!!!!!!!!!!!!!!!!!! !!!!! IMPORTANT !!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!
Definition at line 105 of file G4MTRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 105 of file G4MTRunManagerKernel.cc
References G4VUserActionInitialization::Build(), G4WorkerThread::BuildGeometryAndPhysicsVector(), G4UserWorkerThreadInitialization::CreateWorkerRunManager(), G4WorkerThread::DestroyGeometryAndPhysicsVector(), G4WorkerRunManager::DoWork(), G4Threading::G4SetThreadId(), G4MTRunManager::getMasterRandomEngine(), G4MTRunManager::GetMasterRunManager(), G4RunManager::GetNonConstUserActionInitialization(), G4MTRunManager::GetPinAffinity(), G4WorkerThread::GetThreadId(), G4UImanager::GetUIpointer(), G4RunManager::GetUserActionInitialization(), G4RunManager::GetUserDetectorConstruction(), G4RunManager::GetUserPhysicsList(), G4RunManager::GetUserWorkerInitialization(), G4RunManager::GetUserWorkerThreadInitialization(), G4RunManager::Initialize(), G4VUserActionInitialization::InitializeSteppingVerbose(), G4TemplateAutoLock< _Mutex_t >::lock(), G4VSteppingVerbose::SetInstance(), G4WorkerThread::SetPinAffinity(), G4UImanager::SetUpForAThread(), G4UserWorkerThreadInitialization::SetupRNGEngine(), G4WorkerRunManager::SetUserInitialization(), G4WorkerRunManager::SetWorkerThread(), G4TemplateAutoLock< _Mutex_t >::unlock(), G4UserWorkerInitialization::WorkerInitialize(), workerRMvector, G4UserWorkerInitialization::WorkerStart(), G4UserWorkerInitialization::WorkerStop(), G4Threading::WorkerThreadJoinsPool(), G4Threading::WorkerThreadLeavesPool(), and wThreadContext.
Member Data Documentation
std::vector< G4WorkerRunManager * > * G4MTRunManagerKernel::workerRMvector = 0 static private
Definition at line 92 of file G4MTRunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4MTRunManagerKernel.hh
Referenced by BroadcastAbortRun(), G4MTRunManagerKernel(), StartThread(), and ~G4MTRunManagerKernel().
G4ThreadLocal G4WorkerThread * G4MTRunManagerKernel::wThreadContext = 0 static private
Definition at line 81 of file G4MTRunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4MTRunManagerKernel.hh
Referenced by GetWorkerThread(), and StartThread().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4MTRunManagerKernel.hh
geant4/tree/geant4-10.6-release/source/run/src/G4MTRunManagerKernel.cc