ECCE @ EIC Software: G4SPSAngDistribution Class Reference
G4SPSAngDistribution Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4SPSAngDistribution.hh>
Public Member Functions
G4SPSAngDistribution ()
~G4SPSAngDistribution ()
void SetAngDistType (G4String)
void DefineAngRefAxes (G4String, G4ThreeVector)
void SetMinTheta (G4double)
void SetMinPhi (G4double)
void SetMaxTheta (G4double)
void SetMaxPhi (G4double)
void SetBeamSigmaInAngR (G4double)
void SetBeamSigmaInAngX (G4double)
void SetBeamSigmaInAngY (G4double)
void UserDefAngTheta (G4ThreeVector)
void UserDefAngPhi (G4ThreeVector)
void SetFocusPoint (G4ThreeVector)
void SetParticleMomentumDirection (G4ParticleMomentum aMomentumDirection)
void SetUseUserAngAxis (G4bool)
void SetUserWRTSurface (G4bool)
void SetPosDistribution (G4SPSPosDistribution *a)
void SetBiasRndm (G4SPSRandomGenerator *a)
void ReSetHist (G4String)
void SetVerbosity (G4int a)
G4String GetDistType ()
G4double GetMinTheta ()
G4double GetMaxTheta ()
G4double GetMinPhi ()
G4double GetMaxPhi ()
G4ThreeVector GetDirection ()
G4ParticleMomentum GenerateOne ()
Private Member Functions
void GenerateFocusedFlux (G4ParticleMomentum &outputMom)
void GenerateIsotropicFlux (G4ParticleMomentum &outputMom)
void GenerateCosineLawFlux (G4ParticleMomentum &outputMom)
void GenerateBeamFlux (G4ParticleMomentum &outputMom)
void GeneratePlanarFlux (G4ParticleMomentum &outputMom)
void GenerateUserDefFlux (G4ParticleMomentum &outputMom)
G4double GenerateUserDefTheta ()
G4double GenerateUserDefPhi ()
Private Attributes
G4String AngDistType
G4ThreeVector AngRef1
G4ThreeVector AngRef2
G4ThreeVector AngRef3
G4double MinTheta
G4double MaxTheta
G4double MinPhi
G4double MaxPhi
G4double DR
G4double DX
G4double DY
G4double Theta
G4double Phi
G4ThreeVector FocusPoint
G4bool IPDFThetaExist
G4bool IPDFPhiExist
G4PhysicsOrderedFreeVector UDefThetaH
G4PhysicsOrderedFreeVector IPDFThetaH
G4PhysicsOrderedFreeVector UDefPhiH
G4PhysicsOrderedFreeVector IPDFPhiH
G4String UserDistType
G4bool UserWRTSurface
G4bool UserAngRef
G4ParticleMomentum particle_momentum_direction
G4SPSPosDistribution * posDist
G4SPSRandomGenerator * angRndm
G4int verbosityLevel
G4PhysicsOrderedFreeVector ZeroPhysVector
G4Mutex mutex
Detailed Description
Andrea Dotti Feb 2015 Important: This is a shared class between threads. Only one thread should use the set-methods here. Note that this is exactly what is achieved using UI commands. If you use the set methods to set defaults in your application take care that only one thread is executing them. In addition take care of calling these methods before the run is started Do not use these setters during the event loop
Definition at line 174 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 174 of file G4SPSAngDistribution.hh
Constructor & Destructor Documentation
G4SPSAngDistribution::G4SPSAngDistribution ()
Definition at line 55 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SPSAngDistribution.cc
References AngDistType, AngRef1, AngRef2, AngRef3, DR, DX, DY, FocusPoint, G4MUTEXINIT, CLHEP::HepXHat, CLHEP::HepYHat, CLHEP::HepZHat, IPDFPhiExist, IPDFThetaExist, MaxPhi, MaxTheta, MinPhi, MinTheta, particle_momentum_direction, pi, twopi, UserAngRef, UserDistType, UserWRTSurface, verbosityLevel, and zero.
G4SPSAngDistribution::~G4SPSAngDistribution ()
Definition at line 84 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 84 of file G4SPSAngDistribution.cc
References G4MUTEXDESTROY.
Member Function Documentation
void G4SPSAngDistribution::DefineAngRefAxes (G4String refname, G4ThreeVector ref)
Definition at line 107 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 107 of file G4SPSAngDistribution.cc
References AngRef1, AngRef2, AngRef3, CLHEP::Hep3Vector::cross(), G4cout, G4endl, true, CLHEP::Hep3Vector::unit(), UserAngRef, and verbosityLevel.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::GenerateBeamFlux (G4ParticleMomentum & outputMom) private
Definition at line 255 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 255 of file G4SPSAngDistribution.cc
References AngDistType, AngRef1, AngRef2, AngRef3, DR, DX, DY, G4cout, G4endl, G4UniformRand, phi, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4INCL::DeJongSpin::shoot(), theta(), twopi, UserAngRef, verbosityLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GenerateOne().
void G4SPSAngDistribution::GenerateCosineLawFlux (G4ParticleMomentum & outputMom) private
Definition at line 375 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 375 of file G4SPSAngDistribution.cc
References AngRef1, AngRef2, AngRef3, angRndm, G4cout, G4endl, G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandTheta(), G4SPSPosDistribution::GetSideRefVec1(), G4SPSPosDistribution::GetSideRefVec2(), G4SPSPosDistribution::GetSideRefVec3(), G4SPSPosDistribution::GetSourcePosType(), MaxPhi, MaxTheta, MinPhi, MinTheta, Phi, posDist, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), UserAngRef, verbosityLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GenerateOne().
void G4SPSAngDistribution::GenerateFocusedFlux (G4ParticleMomentum & outputMom) private
Definition at line 301 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 301 of file G4SPSAngDistribution.cc
References FocusPoint, G4cout, G4endl, G4SPSPosDistribution::GetParticlePos(), posDist, and verbosityLevel.
Referenced by GenerateOne().
void G4SPSAngDistribution::GenerateIsotropicFlux (G4ParticleMomentum & outputMom) private
Definition at line 310 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 310 of file G4SPSAngDistribution.cc
References AngRef1, AngRef2, AngRef3, angRndm, G4cout, G4endl, G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandTheta(), G4SPSPosDistribution::GetSideRefVec1(), G4SPSPosDistribution::GetSideRefVec2(), G4SPSPosDistribution::GetSideRefVec3(), G4SPSPosDistribution::GetSourcePosType(), MaxPhi, MaxTheta, MinPhi, MinTheta, Phi, posDist, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), UserAngRef, verbosityLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GenerateOne().
G4ParticleMomentum G4SPSAngDistribution::GenerateOne ()
Definition at line 656 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 656 of file G4SPSAngDistribution.cc
References AngDistType, G4cout, G4endl, GenerateBeamFlux(), GenerateCosineLawFlux(), GenerateFocusedFlux(), GenerateIsotropicFlux(), GeneratePlanarFlux(), GenerateUserDefFlux(), and particle_momentum_direction.
Referenced by G4SingleParticleSource::GeneratePrimaryVertex().
void G4SPSAngDistribution::GeneratePlanarFlux (G4ParticleMomentum & outputMom) private
Definition at line 439 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 439 of file G4SPSAngDistribution.cc
References G4cout, G4endl, and verbosityLevel.
Referenced by GenerateOne().
void G4SPSAngDistribution::GenerateUserDefFlux (G4ParticleMomentum & outputMom) private
Definition at line 450 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 450 of file G4SPSAngDistribution.cc
References AngRef1, AngRef2, AngRef3, angRndm, G4cout, G4endl, GenerateUserDefPhi(), GenerateUserDefTheta(), G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandTheta(), G4SPSPosDistribution::GetSideRefVec1(), G4SPSPosDistribution::GetSideRefVec2(), G4SPSPosDistribution::GetSideRefVec3(), MaxPhi, MaxTheta, MinPhi, MinTheta, particle_momentum_direction, Phi, posDist, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), Theta, twopi, UserAngRef, UserDistType, UserWRTSurface, verbosityLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GenerateOne().
G4double G4SPSAngDistribution::GenerateUserDefPhi () private
Definition at line 594 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 594 of file G4SPSAngDistribution.cc
References G4cout, G4endl, G4UniformRand, G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFPhiExist, IPDFPhiH, sum, UDefPhiH, G4TemplateAutoLock< _Mutex_t >::unlock(), and UserDistType.
Referenced by GenerateUserDefFlux().
G4double G4SPSAngDistribution::GenerateUserDefTheta () private
Definition at line 548 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 548 of file G4SPSAngDistribution.cc
References G4cout, G4endl, G4UniformRand, G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFThetaExist, IPDFThetaH, sum, UDefThetaH, G4TemplateAutoLock< _Mutex_t >::unlock(), and UserDistType.
Referenced by GenerateUserDefFlux().
G4ThreeVector G4SPSAngDistribution::GetDirection ()
Definition at line 215 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 215 of file G4SPSAngDistribution.cc
References particle_momentum_direction.
Referenced by G4GeneralParticleSource::ListSource().
G4String G4SPSAngDistribution::GetDistType ()
Definition at line 210 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 210 of file G4SPSAngDistribution.cc
References AngDistType.
Referenced by G4GeneralParticleSource::ListSource().
G4double G4SPSAngDistribution::GetMaxPhi ()
Definition at line 214 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 214 of file G4SPSAngDistribution.cc
References MaxPhi.
G4double G4SPSAngDistribution::GetMaxTheta ()
Definition at line 212 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 212 of file G4SPSAngDistribution.cc
References MaxTheta.
G4double G4SPSAngDistribution::GetMinPhi ()
Definition at line 213 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 213 of file G4SPSAngDistribution.cc
References MinPhi.
G4double G4SPSAngDistribution::GetMinTheta ()
Definition at line 211 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 211 of file G4SPSAngDistribution.cc
References MinTheta.
void G4SPSAngDistribution::ReSetHist (G4String atype)
Definition at line 641 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 641 of file G4SPSAngDistribution.cc
References false, G4cout, G4endl, IPDFPhiExist, IPDFPhiH, IPDFThetaExist, IPDFThetaH, UDefPhiH, UDefThetaH, and ZeroPhysVector.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetAngDistType (G4String atype)
Definition at line 90 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 90 of file G4SPSAngDistribution.cc
References AngDistType, false, G4cout, G4endl, IPDFPhiExist, IPDFPhiH, IPDFThetaExist, IPDFThetaH, MaxTheta, pi, UDefPhiH, UDefThetaH, and ZeroPhysVector.
Referenced by G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator(), G4AdjointPrimaryGenerator::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSAngDistribution::SetBeamSigmaInAngR (G4double r)
Definition at line 153 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 153 of file G4SPSAngDistribution.cc
References DR, and r.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetBeamSigmaInAngX (G4double r)
Definition at line 159 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 159 of file G4SPSAngDistribution.cc
References DX, and r.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetBeamSigmaInAngY (G4double r)
Definition at line 165 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 165 of file G4SPSAngDistribution.cc
References DY, and r.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetBiasRndm (G4SPSRandomGenerator * a)
Definition at line 184 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 184 of file G4SPSAngDistribution.cc
References a, and angRndm.
Referenced by G4SingleParticleSource::G4SingleParticleSource().
void G4SPSAngDistribution::SetFocusPoint (G4ThreeVector input)
Definition at line 230 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 230 of file G4SPSAngDistribution.cc
References FocusPoint.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetMaxPhi (G4double maxp)
Definition at line 147 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 147 of file G4SPSAngDistribution.cc
References MaxPhi.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetMaxTheta (G4double maxt)
Definition at line 141 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 141 of file G4SPSAngDistribution.cc
References MaxTheta.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSAngDistribution::SetMinPhi (G4double minp)
Definition at line 135 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 135 of file G4SPSAngDistribution.cc
References MinPhi.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetMinTheta (G4double mint)
Definition at line 129 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 129 of file G4SPSAngDistribution.cc
References MinTheta.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSAngDistribution::SetParticleMomentumDirection (G4ParticleMomentum aMomentumDirection)
Definition at line 171 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 171 of file G4SPSAngDistribution.cc
References particle_momentum_direction, and CLHEP::Hep3Vector::unit().
Referenced by G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex(), G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), and G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetPosDistribution (G4SPSPosDistribution * a)
Definition at line 178 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 178 of file G4SPSAngDistribution.cc
References a, and posDist.
Referenced by G4SingleParticleSource::G4SingleParticleSource().
void G4SPSAngDistribution::SetUserWRTSurface (G4bool wrtSurf)
Definition at line 236 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 236 of file G4SPSAngDistribution.cc
References UserWRTSurface.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetUseUserAngAxis (G4bool userang)
Definition at line 247 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 247 of file G4SPSAngDistribution.cc
References UserAngRef.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::SetVerbosity (G4int a)
Definition at line 190 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 190 of file G4SPSAngDistribution.cc
References a, and verbosityLevel.
Referenced by G4SingleParticleSource::SetVerbosity().
void G4SPSAngDistribution::UserDefAngPhi (G4ThreeVector input)
Definition at line 217 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 217 of file G4SPSAngDistribution.cc
References G4cout, G4endl, G4PhysicsOrderedFreeVector::InsertValues(), UDefPhiH, UserDistType, verbosityLevel, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSAngDistribution::UserDefAngTheta (G4ThreeVector input)
Definition at line 197 of file G4SPSAngDistribution.cc.
View newest version in sPHENIX GitHub at line 197 of file G4SPSAngDistribution.cc
References G4cout, G4endl, G4PhysicsOrderedFreeVector::InsertValues(), UDefThetaH, UserDistType, verbosityLevel, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
Member Data Documentation
G4String G4SPSAngDistribution::AngDistType private
Definition at line 228 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 228 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateBeamFlux(), GenerateOne(), GetDistType(), and SetAngDistType().
G4ThreeVector G4SPSAngDistribution::AngRef1 private
Definition at line 229 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 229 of file G4SPSAngDistribution.hh
Referenced by DefineAngRefAxes(), G4SPSAngDistribution(), GenerateBeamFlux(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), and GenerateUserDefFlux().
G4ThreeVector G4SPSAngDistribution::AngRef2 private
Definition at line 229 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 229 of file G4SPSAngDistribution.hh
Referenced by DefineAngRefAxes(), G4SPSAngDistribution(), GenerateBeamFlux(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), and GenerateUserDefFlux().
G4ThreeVector G4SPSAngDistribution::AngRef3 private
Definition at line 229 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 229 of file G4SPSAngDistribution.hh
Referenced by DefineAngRefAxes(), G4SPSAngDistribution(), GenerateBeamFlux(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), and GenerateUserDefFlux().
G4SPSRandomGenerator* G4SPSAngDistribution::angRndm private
Definition at line 247 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 247 of file G4SPSAngDistribution.hh
Referenced by GenerateCosineLawFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), and SetBiasRndm().
G4double G4SPSAngDistribution::DR private
Definition at line 231 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 231 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateBeamFlux(), and SetBeamSigmaInAngR().
G4double G4SPSAngDistribution::DX private
Definition at line 231 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 231 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateBeamFlux(), and SetBeamSigmaInAngX().
G4double G4SPSAngDistribution::DY private
Definition at line 231 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 231 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateBeamFlux(), and SetBeamSigmaInAngY().
G4ThreeVector G4SPSAngDistribution::FocusPoint private
Definition at line 233 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 233 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateFocusedFlux(), and SetFocusPoint().
G4bool G4SPSAngDistribution::IPDFPhiExist private
Definition at line 234 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 234 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateUserDefPhi(), ReSetHist(), and SetAngDistType().
G4PhysicsOrderedFreeVector G4SPSAngDistribution::IPDFPhiH private
Definition at line 238 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 238 of file G4SPSAngDistribution.hh
Referenced by GenerateUserDefPhi(), ReSetHist(), and SetAngDistType().
G4bool G4SPSAngDistribution::IPDFThetaExist private
Definition at line 234 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 234 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateUserDefTheta(), ReSetHist(), and SetAngDistType().
G4PhysicsOrderedFreeVector G4SPSAngDistribution::IPDFThetaH private
Definition at line 236 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 236 of file G4SPSAngDistribution.hh
Referenced by GenerateUserDefTheta(), ReSetHist(), and SetAngDistType().
G4double G4SPSAngDistribution::MaxPhi private
Definition at line 230 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 230 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), GetMaxPhi(), and SetMaxPhi().
G4double G4SPSAngDistribution::MaxTheta private
Definition at line 230 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 230 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), GetMaxTheta(), SetAngDistType(), and SetMaxTheta().
G4double G4SPSAngDistribution::MinPhi private
Definition at line 230 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 230 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), GetMinPhi(), and SetMinPhi().
G4double G4SPSAngDistribution::MinTheta private
Definition at line 230 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 230 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), GetMinTheta(), and SetMinTheta().
G4Mutex G4SPSAngDistribution::mutex private
Definition at line 254 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 254 of file G4SPSAngDistribution.hh
G4ParticleMomentum G4SPSAngDistribution::particle_momentum_direction private
Definition at line 244 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 244 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateOne(), GenerateUserDefFlux(), GetDirection(), and SetParticleMomentumDirection().
G4double G4SPSAngDistribution::Phi private
Definition at line 232 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 232 of file G4SPSAngDistribution.hh
Referenced by GenerateCosineLawFlux(), GenerateIsotropicFlux(), and GenerateUserDefFlux().
G4SPSPosDistribution* G4SPSAngDistribution::posDist private
Definition at line 246 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 246 of file G4SPSAngDistribution.hh
Referenced by GenerateCosineLawFlux(), GenerateFocusedFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), and SetPosDistribution().
G4double G4SPSAngDistribution::Theta private
Definition at line 232 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 232 of file G4SPSAngDistribution.hh
Referenced by GenerateUserDefFlux().
G4PhysicsOrderedFreeVector G4SPSAngDistribution::UDefPhiH private
Definition at line 237 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 237 of file G4SPSAngDistribution.hh
Referenced by GenerateUserDefPhi(), ReSetHist(), SetAngDistType(), and UserDefAngPhi().
G4PhysicsOrderedFreeVector G4SPSAngDistribution::UDefThetaH private
Definition at line 235 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 235 of file G4SPSAngDistribution.hh
Referenced by GenerateUserDefTheta(), ReSetHist(), SetAngDistType(), and UserDefAngTheta().
G4bool G4SPSAngDistribution::UserAngRef private
Definition at line 242 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 242 of file G4SPSAngDistribution.hh
Referenced by DefineAngRefAxes(), G4SPSAngDistribution(), GenerateBeamFlux(), GenerateCosineLawFlux(), GenerateIsotropicFlux(), GenerateUserDefFlux(), and SetUseUserAngAxis().
G4String G4SPSAngDistribution::UserDistType private
Definition at line 239 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 239 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateUserDefFlux(), GenerateUserDefPhi(), GenerateUserDefTheta(), UserDefAngPhi(), and UserDefAngTheta().
G4bool G4SPSAngDistribution::UserWRTSurface private
Definition at line 240 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 240 of file G4SPSAngDistribution.hh
Referenced by G4SPSAngDistribution(), GenerateUserDefFlux(), and SetUserWRTSurface().
G4int G4SPSAngDistribution::verbosityLevel private
Definition at line 250 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 250 of file G4SPSAngDistribution.hh
Referenced by DefineAngRefAxes(), G4SPSAngDistribution(), GenerateBeamFlux(), GenerateCosineLawFlux(), GenerateFocusedFlux(), GenerateIsotropicFlux(), GeneratePlanarFlux(), GenerateUserDefFlux(), SetVerbosity(), UserDefAngPhi(), and UserDefAngTheta().
G4PhysicsOrderedFreeVector G4SPSAngDistribution::ZeroPhysVector private
Definition at line 252 of file G4SPSAngDistribution.hh.
View newest version in sPHENIX GitHub at line 252 of file G4SPSAngDistribution.hh
Referenced by ReSetHist(), and SetAngDistType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4SPSAngDistribution.hh
geant4/tree/geant4-10.6-release/source/event/src/G4SPSAngDistribution.cc