ECCE @ EIC Software: G4StateManager Class Reference
G4StateManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4StateManager.hh>
Public Member Functions
~G4StateManager ()
const G4ApplicationState & GetCurrentState () const
const G4ApplicationState & GetPreviousState () const
G4bool SetNewState (const G4ApplicationState &requestedState)
G4bool SetNewState (const G4ApplicationState &requestedState, const char *msg)
G4bool RegisterDependent (G4VStateDependent *aDependent, G4bool bottom=false)
G4bool DeregisterDependent (G4VStateDependent *aDependent)
G4VStateDependent * RemoveDependent (const G4VStateDependent *aDependent)
G4String GetStateString (const G4ApplicationState &aState) const
void SetSuppressAbortion (G4int i)
G4int GetSuppressAbortion () const
const char * GetMessage () const
void SetExceptionHandler (G4VExceptionHandler *eh)
G4VExceptionHandler * GetExceptionHandler () const
Static Public Member Functions
static G4StateManager * GetStateManager ()
static void SetVerboseLevel (G4int val)
Private Member Functions
G4StateManager ()
G4StateManager (const G4StateManager &right)
G4StateManager & operator= (const G4StateManager &right)
G4bool operator== (const G4StateManager &right) const
G4bool operator!= (const G4StateManager &right) const
Private Attributes
G4ApplicationState theCurrentState
G4ApplicationState thePreviousState
std::vector< G4VStateDependent * > theDependentsList
G4VStateDependent * theBottomDependent
G4int suppressAbortion
const char * msgptr
G4VExceptionHandler * exceptionHandler
Static Private Attributes
static G4ThreadLocal
G4StateManager * theStateManager = 0
static G4int verboseLevel = 0
Detailed Description
Definition at line 60 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 60 of file G4StateManager.hh
Constructor & Destructor Documentation
G4StateManager::~G4StateManager ()
Definition at line 57 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4StateManager.cc
References G4iosFinalization(), theDependentsList, and theStateManager.
G4StateManager::G4StateManager () private
Definition at line 44 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 44 of file G4StateManager.cc
References G4iosInitialization().
Referenced by GetStateManager().
G4StateManager::G4StateManager (const G4StateManager & right) private
Definition at line 90 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 90 of file G4StateManager.cc
Member Function Documentation
G4bool G4StateManager::DeregisterDependent (G4VStateDependent * aDependent)
Definition at line 161 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 161 of file G4StateManager.cc
References theDependentsList, and tmp.
Referenced by G4VStateDependent::~G4VStateDependent(), and MyPrimaryGeneratorActionFromFile::~MyPrimaryGeneratorActionFromFile().
const G4ApplicationState & G4StateManager::GetCurrentState () const
Definition at line 181 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 181 of file G4StateManager.cc
References theCurrentState.
Referenced by G4RunManager::AbortEvent(), G4RunManager::AbortRun(), G4MTRunManager::AbortRun(), G4ProcessManager::ActivateProcess(), G4MTcoutDestination::AddMasterOutput(), G4RunManager::ConfirmBeamOnCondition(), G4RunManagerKernel::DefineWorldVolume(), G4EventManager::DoProcessing(), G4ExceptionHandler::DumpTrackInfo(), export_G4StateManager(), G4ParticleDefinition::G4ParticleDefinition(), G4UIGAG::G4UIGAG(), G4UIGainServer::G4UIGainServer(), G4EventManager::GetUserInformation(), G4ProcessManager::InActivateProcess(), G4ErrorPropagatorManager::InitGeant4e(), G4RunManager::Initialize(), G4RunManager::InitializeGeometry(), G4RunManagerKernel::InitializePhysics(), G4RunManager::InitializePhysics(), G4UIcommand::IsAvailable(), G4DeexPrecoParameters::IsLocked(), G4EmParameters::IsLocked(), G4VUIshell::MakePrompt(), G4UItcsh::MakePrompt(), G4ExceptionHandler::Notify(), G4UIGAG::NotifyStateChange(), G4UIGainServer::NotifyStateChange(), G4VSceneHandler::ProcessScene(), G4ErrorPropagator::PropagateOneStep(), G4VModularPhysicsList::RegisterPhysics(), G4ParticleTable::Remove(), G4IonTable::Remove(), G4VModularPhysicsList::RemovePhysics(), G4VModularPhysicsList::ReplacePhysics(), G4RunManagerKernel::RunInitialization(), G4MaterialScanner::Scan(), G4UIGAG::SessionStart(), G4UIGainServer::SessionStart(), G4MTcoutDestination::SetDefaultOutput(), G4ParticlePropertyTable::SetParticleProperty(), G4EventManager::SetUserInformation(), G4VelocityTable::SetVelocityTableProperties(), G4TheRayTracer::Trace(), G4TheMTRayTracer::Trace(), G4RunManagerKernel::UpdateRegion(), G4UIGAG::UpdateState(), G4UIGainServer::UpdateState(), G4RunManagerKernel::WorkerDefineWorldVolume(), G4ParticleDefinition::~G4ParticleDefinition(), G4RunManager::~G4RunManager(), and G4RunManagerKernel::~G4RunManagerKernel().
G4VExceptionHandler* G4StateManager::GetExceptionHandler () const inline
Referenced by G4Exception().
const char* G4StateManager::GetMessage () const inline
const G4ApplicationState & G4StateManager::GetPreviousState () const
Definition at line 187 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 187 of file G4StateManager.cc
References thePreviousState.
Referenced by export_G4StateManager(), and G4VisStateDependent::Notify().
G4StateManager * G4StateManager::GetStateManager () static
Definition at line 132 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 132 of file G4StateManager.cc
References G4StateManager(), and theStateManager.
Referenced by G4RunManager::AbortEvent(), G4RunManager::AbortRun(), G4MTRunManager::AbortRun(), G4ProcessManager::ActivateProcess(), HadrontherapyInteractionParameters::BeamOn(), G4ErrorPropagatorManager::CloseGeometry(), G4RunManager::ConfirmBeamOnCondition(), G4TheRayTracer::CreateBitMap(), G4UIcommandTree::CreateHTML(), G4RunManagerKernel::DefineWorldVolume(), G4MaterialScanner::DoScan(), G4ExceptionHandler::DumpTrackInfo(), export_G4StateManager(), pyG4Exception::f2_G4Exception(), G4EmParameters::G4EmParameters(), G4EventManager::G4EventManager(), G4Exception(), G4MTcoutDestination::G4MTcoutDestination(), G4ParticleDefinition::G4ParticleDefinition(), G4RunManagerKernel::G4RunManagerKernel(), G4UIGAG::G4UIGAG(), G4UIGainServer::G4UIGainServer(), G4VExceptionHandler::G4VExceptionHandler(), G4VStateDependent::G4VStateDependent(), G4UIcontrolMessenger::GetCurrentValue(), G4DNAMolecularMaterial::GetDensityTableFor(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), G4ProcessManager::InActivateProcess(), G4ErrorPropagatorManager::InitGeant4e(), G4RunManager::Initialize(), G4RunManager::InitializeGeometry(), G4RunManagerKernel::InitializePhysics(), G4RunManager::InitializePhysics(), G4UIcommand::IsAvailable(), G4VUIshell::MakePrompt(), G4UItcsh::MakePrompt(), G4VisStateDependent::Notify(), G4ExceptionHandler::Notify(), G4DNAMolecularMaterial::Notify(), G4UImanager::Notify(), G4UIGAG::NotifyStateChange(), G4UIGainServer::NotifyStateChange(), G4ErrorPropagatorManager::PrintG4State(), G4VSceneHandler::ProcessScene(), G4ErrorPropagator::PropagateOneStep(), PyG4ExceptionHandler::PyG4ExceptionHandler(), G4VModularPhysicsList::RegisterPhysics(), G4ParticleTable::Remove(), G4IonTable::Remove(), G4VModularPhysicsList::RemovePhysics(), G4VModularPhysicsList::ReplacePhysics(), G4RunManagerKernel::RunInitialization(), G4RunManagerKernel::RunTermination(), G4MaterialScanner::Scan(), G4UIGAG::SessionStart(), G4UIGainServer::SessionStart(), DetectorConstruction::SetAbsorberThickness(), DetectorConstruction::SetCalorSizeYZ(), F04DetectorConstruction::SetCaptureMgntB1(), F04DetectorConstruction::SetCaptureMgntB2(), F04DetectorConstruction::SetCaptureMgntLength(), F04DetectorConstruction::SetCaptureMgntRadius(), G4DeexPrecoParameters::SetDefaults(), F04DetectorConstruction::SetDegraderPos(), F04DetectorConstruction::SetDegraderRadius(), F04DetectorConstruction::SetDegraderThickness(), DetectorConstruction::SetGapThickness(), DetectorConstruction::SetNbOfLayers(), G4UIcontrolMessenger::SetNewValue(), G4ParticlePropertyTable::SetParticleProperty(), F04DetectorConstruction::SetTargetAngle(), F04DetectorConstruction::SetTargetPos(), F04DetectorConstruction::SetTargetRadius(), F04DetectorConstruction::SetTargetThickness(), F04DetectorConstruction::SetTransferMgntB(), F04DetectorConstruction::SetTransferMgntLength(), F04DetectorConstruction::SetTransferMgntPos(), F04DetectorConstruction::SetTransferMgntRadius(), G4VelocityTable::SetVelocityTableProperties(), F04DetectorConstruction::SetWorldSizeR(), F04DetectorConstruction::SetWorldSizeZ(), SignalHandler(), G4TheRayTracer::Trace(), G4TheMTRayTracer::Trace(), G4RunManagerKernel::UpdateRegion(), G4UIGAG::UpdateState(), G4UIGainServer::UpdateState(), G4MPImanager::UpdateStatus(), G4RunManagerKernel::WorkerDefineWorldVolume(), G4ParticleDefinition::~G4ParticleDefinition(), G4RunManager::~G4RunManager(), G4RunManagerKernel::~G4RunManagerKernel(), G4VStateDependent::~G4VStateDependent(), and MyPrimaryGeneratorActionFromFile::~MyPrimaryGeneratorActionFromFile().
G4String G4StateManager::GetStateString (const G4ApplicationState & aState) const
Definition at line 258 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 258 of file G4StateManager.cc
References G4State_Abort, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_Init, G4State_PreInit, and G4State_Quit.
Referenced by G4UIcommandTree::CreateHTML(), G4RunManagerKernel::DefineWorldVolume(), export_G4StateManager(), G4UIGAG::G4UIGAG(), G4UIGainServer::G4UIGainServer(), G4RunManagerKernel::InitializePhysics(), G4UIGAG::NotifyStateChange(), G4UIGainServer::NotifyStateChange(), G4UIGAG::SessionStart(), G4UIGainServer::SessionStart(), SetNewState(), G4TheMTRayTracer::Trace(), and G4RunManagerKernel::WorkerDefineWorldVolume().
G4int G4StateManager::GetSuppressAbortion () const inline
G4bool G4StateManager::operator!= (const G4StateManager & right) const private
Definition at line 124 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 124 of file G4StateManager.cc
G4StateManager & G4StateManager::operator= (const G4StateManager & right) private
Definition at line 102 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 102 of file G4StateManager.cc
References exceptionHandler, msgptr, suppressAbortion, theBottomDependent, theCurrentState, theDependentsList, and thePreviousState.
G4bool G4StateManager::operator== (const G4StateManager & right) const private
Definition at line 118 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 118 of file G4StateManager.cc
G4bool G4StateManager::RegisterDependent (G4VStateDependent * aDependent, G4bool bottom = false)
Definition at line 142 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 142 of file G4StateManager.cc
References theBottomDependent, and theDependentsList.
Referenced by G4VStateDependent::G4VStateDependent().
G4VStateDependent * G4StateManager::RemoveDependent (const G4VStateDependent * aDependent)
Definition at line 238 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 238 of file G4StateManager.cc
References theDependentsList, and tmp.
void G4StateManager::SetExceptionHandler (G4VExceptionHandler * eh) inline
Referenced by G4VExceptionHandler::G4VExceptionHandler().
G4bool G4StateManager::SetNewState (const G4ApplicationState & requestedState)
Definition at line 193 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 193 of file G4StateManager.cc
Referenced by G4ErrorPropagatorManager::CloseGeometry(), G4TheRayTracer::CreateBitMap(), G4RunManagerKernel::DefineWorldVolume(), G4EventManager::DoProcessing(), G4MaterialScanner::DoScan(), G4RunManagerKernel::G4RunManagerKernel(), G4RunManager::Initialize(), G4RunManager::InitializeGeometry(), G4RunManagerKernel::InitializePhysics(), G4RunManager::InitializePhysics(), G4RunManagerKernel::RunInitialization(), G4RunManagerKernel::RunTermination(), G4RunManagerKernel::WorkerDefineWorldVolume(), G4RunManager::~G4RunManager(), and G4RunManagerKernel::~G4RunManagerKernel().
G4bool G4StateManager::SetNewState (const G4ApplicationState & requestedState, const char * msg)
Definition at line 197 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 197 of file G4StateManager.cc
References G4cout, G4endl, G4State_Abort, G4State_EventProc, GetStateString(), msgptr, G4VStateDependent::Notify(), suppressAbortion, theBottomDependent, theCurrentState, theDependentsList, thePreviousState, and verboseLevel.
void G4StateManager::SetSuppressAbortion (G4int i) inline
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4StateManager::SetVerboseLevel (G4int val) static
Definition at line 284 of file G4StateManager.cc.
View newest version in sPHENIX GitHub at line 284 of file G4StateManager.cc
References verboseLevel.
Member Data Documentation
G4VExceptionHandler* G4StateManager::exceptionHandler private
Definition at line 124 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4StateManager.hh
Referenced by operator=().
const char* G4StateManager::msgptr private
Definition at line 123 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4StateManager.hh
Referenced by operator=(), and SetNewState().
G4int G4StateManager::suppressAbortion private
Definition at line 122 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 122 of file G4StateManager.hh
Referenced by operator=(), and SetNewState().
G4VStateDependent* G4StateManager::theBottomDependent private
Definition at line 121 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4StateManager.hh
Referenced by operator=(), RegisterDependent(), and SetNewState().
G4ApplicationState G4StateManager::theCurrentState private
Definition at line 118 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 118 of file G4StateManager.hh
Referenced by GetCurrentState(), operator=(), and SetNewState().
std::vector<G4VStateDependent*> G4StateManager::theDependentsList private
Definition at line 120 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4StateManager.hh
Referenced by DeregisterDependent(), operator=(), RegisterDependent(), RemoveDependent(), SetNewState(), and ~G4StateManager().
G4ApplicationState G4StateManager::thePreviousState private
Definition at line 119 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4StateManager.hh
Referenced by GetPreviousState(), operator=(), and SetNewState().
G4ThreadLocal G4StateManager * G4StateManager::theStateManager = 0 static private
Definition at line 117 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4StateManager.hh
Referenced by GetStateManager(), and ~G4StateManager().
G4int G4StateManager::verboseLevel = 0 static private
Definition at line 125 of file G4StateManager.hh.
View newest version in sPHENIX GitHub at line 125 of file G4StateManager.hh
Referenced by SetNewState(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4StateManager.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4StateManager.cc