ECCE @ EIC Software: G4EqEMFieldWithSpin Class Reference
G4EqEMFieldWithSpin Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4EqEMFieldWithSpin.hh>
Public Member Functions
G4EqEMFieldWithSpin (G4ElectroMagneticField *emField)
~G4EqEMFieldWithSpin ()
void SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double mass)
void EvaluateRhsGivenB (const G4double y[], const G4double Field[], G4double dydx[]) const
void SetAnomaly (G4double a)
G4double GetAnomaly () const
Public Member Functions inherited from G4EquationOfMotion
G4EquationOfMotion (G4Field *Field)
virtual ~G4EquationOfMotion ()
virtual void EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const =0
void RightHandSide (const G4double y[], G4double dydx[]) const
void EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const
void GetFieldValue (const G4double Point[4], G4double Field[]) const
const G4Field * GetFieldObj () const
G4Field * GetFieldObj ()
void SetFieldObj (G4Field *pField)
Private Attributes
G4double charge
G4double mass
G4double magMoment
G4double spin
G4double fElectroMagCof
G4double fMassCof
G4double omegac
G4double anomaly
G4double beta
G4double gamma
Detailed Description
Definition at line 43 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 43 of file G4EqEMFieldWithSpin.hh
Constructor & Destructor Documentation
G4EqEMFieldWithSpin::G4EqEMFieldWithSpin (G4ElectroMagneticField * emField)
Definition at line 38 of file G4EqEMFieldWithSpin.cc.
View newest version in sPHENIX GitHub at line 38 of file G4EqEMFieldWithSpin.cc
G4EqEMFieldWithSpin::~G4EqEMFieldWithSpin ()
Definition at line 45 of file G4EqEMFieldWithSpin.cc.
View newest version in sPHENIX GitHub at line 45 of file G4EqEMFieldWithSpin.cc
Member Function Documentation
void G4EqEMFieldWithSpin::EvaluateRhsGivenB (const G4double y[], const G4double Field[], G4double dydx[]) const
Definition at line 78 of file G4EqEMFieldWithSpin.cc.
View newest version in sPHENIX GitHub at line 78 of file G4EqEMFieldWithSpin.cc
References anomaly, beta, source.hepunit::c_light, charge, CLHEP::Hep3Vector::cross(), fElectroMagCof, fMassCof, gamma, CLHEP::Hep3Vector::mag2(), omegac, Acts::UnitConstants::u, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4EqEMFieldWithSpin::GetAnomaly () const inline
Definition at line 62 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 62 of file G4EqEMFieldWithSpin.hh
References anomaly.
void G4EqEMFieldWithSpin::SetAnomaly (G4double a) inline
Definition at line 61 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 61 of file G4EqEMFieldWithSpin.hh
References a, and anomaly.
void G4EqEMFieldWithSpin::SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double mass) virtual
Implements G4EquationOfMotion.
Definition at line 50 of file G4EqEMFieldWithSpin.cc.
View newest version in sPHENIX GitHub at line 50 of file G4EqEMFieldWithSpin.cc
References kdfinder::abs(), anomaly, beta, source.hepunit::c_light, source.hepunit::c_squared, charge, E, eplus, fElectroMagCof, fMassCof, gamma, G4ChargeState::GetCharge(), G4ChargeState::GetMagneticDipoleMoment(), G4ChargeState::GetSpin(), source.hepunit::hbar_Planck, magMoment, mass, omegac, spin, and sqr().
Member Data Documentation
G4double G4EqEMFieldWithSpin::anomaly private
Definition at line 72 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 72 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), GetAnomaly(), SetAnomaly(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::beta private
Definition at line 73 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 73 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::charge private
Definition at line 67 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::fElectroMagCof private
Definition at line 69 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 69 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::fMassCof private
Definition at line 70 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 70 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::gamma private
Definition at line 73 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 73 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::magMoment private
Definition at line 67 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EqEMFieldWithSpin.hh
Referenced by SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::mass private
Definition at line 67 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EqEMFieldWithSpin.hh
Referenced by SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::omegac private
Definition at line 72 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 72 of file G4EqEMFieldWithSpin.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4EqEMFieldWithSpin::spin private
Definition at line 67 of file G4EqEMFieldWithSpin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EqEMFieldWithSpin.hh
Referenced by SetChargeMomentumMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4EqEMFieldWithSpin.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4EqEMFieldWithSpin.cc