ECCE @ EIC Software: G4LEHadronProtonElastic Class Reference
G4LEHadronProtonElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LEHadronProtonElastic.hh>
Public Member Functions
G4LEHadronProtonElastic ()
~G4LEHadronProtonElastic ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double RandCosThetaDipPen ()
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 56 of file G4LEHadronProtonElastic.hh.
View newest version in sPHENIX GitHub at line 56 of file G4LEHadronProtonElastic.hh
Constructor & Destructor Documentation
G4LEHadronProtonElastic::G4LEHadronProtonElastic ()
Definition at line 44 of file G4LEHadronProtonElastic.cc.
View newest version in sPHENIX GitHub at line 44 of file G4LEHadronProtonElastic.cc
References MeV, G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4LEHadronProtonElastic::~G4LEHadronProtonElastic ()
Definition at line 51 of file G4LEHadronProtonElastic.cc.
View newest version in sPHENIX GitHub at line 51 of file G4LEHadronProtonElastic.cc
References G4HadFinalState::Clear(), and G4HadronicInteraction::theParticleChange.
Member Function Documentation
G4HadFinalState * G4LEHadronProtonElastic::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronElastic.
Definition at line 57 of file G4LEHadronProtonElastic.cc.
View newest version in sPHENIX GitHub at line 57 of file G4LEHadronProtonElastic.cc
References A(), kdfinder::abs(), G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), E, G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalEnergy(), G4DynamicParticle::GetTotalEnergy(), G4HadProjectile::GetTotalMomentum(), G4DynamicParticle::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, halfpi, P, phi, pi, G4Proton::Proton(), source.hepunit::proton_mass_c2, Q, G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4HadFinalState::SetEnergyChange(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetMomentumChange(), G4HadronicInteraction::theParticleChange, theta(), twopi, CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), Z, and CLHEP::HepLorentzVector::z().
G4double G4LEHadronProtonElastic::RandCosThetaDipPen ()
Definition at line 277 of file G4LEHadronProtonElastic.cc.
View newest version in sPHENIX GitHub at line 277 of file G4LEHadronProtonElastic.cc
References G4UniformRand, G4Pow::GetInstance(), G4Pow::powA(), and x.
Referenced by SampleInvariantT().
G4double G4LEHadronProtonElastic::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) virtual
Reimplemented from G4HadronElastic.
Definition at line 254 of file G4LEHadronProtonElastic.cc.
View newest version in sPHENIX GitHub at line 254 of file G4LEHadronProtonElastic.cc
References G4ParticleDefinition::GetPDGMass(), RandCosThetaDipPen(), and t.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LEHadronProtonElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4LEHadronProtonElastic.cc