ECCE @ EIC Software: G4RDShellData Class Reference
G4RDShellData Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDShellData.hh>
Public Member Functions
G4RDShellData (G4int minZ=1, G4int maxZ=100, G4bool isOccupancy=false)
~G4RDShellData ()
size_t NumberOfShells (G4int Z) const
G4int ShellId (G4int Z, G4int shellIndex) const
G4double ShellOccupancyProbability (G4int Z, G4int shellIndex) const
const std::vector< G4double > & ShellIdVector (G4int Z) const
G4double BindingEnergy (G4int Z, G4int shellIndex) const
void SetOccupancyData ()
void LoadData (const G4String &fileName)
void PrintData () const
G4int SelectRandomShell (G4int Z) const
Private Member Functions
G4RDShellData & operator= (const G4RDShellData &right)
G4RDShellData (const G4RDShellData &)
const std::vector< G4double > & ShellVector (G4int Z) const
Private Attributes
G4int zMin
G4int zMax
G4bool occupancyData
std::map< G4int, std::vector
< G4double > *, std::less
< G4int > > idMap
std::map< G4int, G4DataVector
*, std::less< G4int > > bindingMap
std::vector< G4int > nShells
std::map< G4int, std::vector
< G4double > *, std::less
< G4int > > occupancyPdfMap
Detailed Description
Definition at line 51 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RDShellData.hh
Constructor & Destructor Documentation
G4RDShellData::G4RDShellData (G4int minZ = 1, G4int maxZ = 100, G4bool isOccupancy = false)
Definition at line 52 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 52 of file G4RDShellData.cc
G4RDShellData::~G4RDShellData ()
Definition at line 57 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 57 of file G4RDShellData.cc
References bindingMap, idMap, occupancyData, occupancyPdfMap, and pos().
G4RDShellData::G4RDShellData (const G4RDShellData &) private
Member Function Documentation
G4double G4RDShellData::BindingEnergy (G4int Z, G4int shellIndex) const
Definition at line 167 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 167 of file G4RDShellData.cc
References bindingMap, pos(), zMax, and zMin.
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), G4LowEnergyCompton::PostStepDoIt(), and G4LowEnergyPolarizedCompton::PostStepDoIt().
void G4RDShellData::LoadData (const G4String & fileName)
Definition at line 235 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 235 of file G4RDShellData.cc
References a, bindingMap, e, FatalException, file, G4Exception(), idMap, k, MeV, n, nShells, occupancyData, occupancyPdfMap, s1, scale, ShellIdVector(), Z, zMax, and zMin.
Referenced by G4LowEnergyCompton::BuildPhysicsTable(), G4LowEnergyPolarizedCompton::BuildPhysicsTable(), and G4RDAtomicTransitionManager::G4RDAtomicTransitionManager().
size_t G4RDShellData::NumberOfShells (G4int Z) const
Definition at line 85 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 85 of file G4RDShellData.cc
References n, nShells, z, zMax, and zMin.
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), and SelectRandomShell().
G4RDShellData& G4RDShellData::operator= (const G4RDShellData & right) private
void G4RDShellData::PrintData (void) const
Definition at line 188 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 188 of file G4RDShellData.cc
References bindingMap, e, G4cout, G4endl, idMap, keV, nShells, occupancyData, occupancyPdfMap, Z, zMax, and zMin.
G4int G4RDShellData::SelectRandomShell (G4int Z) const
Definition at line 359 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 359 of file G4RDShellData.cc
References FatalException, G4Exception(), G4UniformRand, nShells, NumberOfShells(), ShellVector(), and zMax.
Referenced by G4LowEnergyCompton::PostStepDoIt(), and G4LowEnergyPolarizedCompton::PostStepDoIt().
void G4RDShellData::SetOccupancyData () inline
Definition at line 69 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RDShellData.hh
References occupancyData.
Referenced by G4LowEnergyCompton::G4LowEnergyCompton(), and G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton().
G4int G4RDShellData::ShellId (G4int Z, G4int shellIndex) const
Definition at line 122 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 122 of file G4RDShellData.cc
References idMap, n, pos(), zMax, and zMin.
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager().
const std::vector< G4double > & G4RDShellData::ShellIdVector (G4int Z) const
Definition at line 98 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 98 of file G4RDShellData.cc
References FatalException, G4Exception(), idMap, pos(), and zMax.
Referenced by LoadData().
G4double G4RDShellData::ShellOccupancyProbability (G4int Z, G4int shellIndex) const
Definition at line 144 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 144 of file G4RDShellData.cc
References idMap, pos(), zMax, and zMin.
const std::vector< G4double > & G4RDShellData::ShellVector (G4int Z) const private
Definition at line 110 of file G4RDShellData.cc.
View newest version in sPHENIX GitHub at line 110 of file G4RDShellData.cc
References FatalException, G4Exception(), occupancyPdfMap, pos(), and zMax.
Referenced by SelectRandomShell().
Member Data Documentation
std::map<G4int,G4DataVector*,std::less<G4int> > G4RDShellData::bindingMap private
Definition at line 92 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RDShellData.hh
Referenced by BindingEnergy(), LoadData(), PrintData(), and ~G4RDShellData().
std::map<G4int,std::vector<G4double>*,std::less<G4int> > G4RDShellData::idMap private
Definition at line 91 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RDShellData.hh
Referenced by LoadData(), PrintData(), ShellId(), ShellIdVector(), ShellOccupancyProbability(), and ~G4RDShellData().
std::vector<G4int> G4RDShellData::nShells private
Definition at line 93 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 93 of file G4RDShellData.hh
Referenced by LoadData(), NumberOfShells(), PrintData(), and SelectRandomShell().
G4bool G4RDShellData::occupancyData private
Definition at line 89 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RDShellData.hh
Referenced by LoadData(), PrintData(), SetOccupancyData(), and ~G4RDShellData().
std::map<G4int,std::vector<G4double>*,std::less<G4int> > G4RDShellData::occupancyPdfMap private
Definition at line 94 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RDShellData.hh
Referenced by LoadData(), PrintData(), ShellVector(), and ~G4RDShellData().
G4int G4RDShellData::zMax private
Definition at line 87 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RDShellData.hh
Referenced by BindingEnergy(), LoadData(), NumberOfShells(), PrintData(), SelectRandomShell(), ShellId(), ShellIdVector(), ShellOccupancyProbability(), and ShellVector().
G4int G4RDShellData::zMin private
Definition at line 86 of file G4RDShellData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RDShellData.hh
Referenced by BindingEnergy(), LoadData(), NumberOfShells(), PrintData(), ShellId(), and ShellOccupancyProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDShellData.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDShellData.cc