ECCE @ EIC Software: CLHEP::DualRand::Tausworthe Class Reference
CLHEP::DualRand::Tausworthe Class Reference
Public Member Functions
Tausworthe ()
Tausworthe (unsigned int seed)
operator unsigned int ()
void put (std::ostream &os) const
void put (std::vector< unsigned long > &v) const
void get (std::istream &is)
bool get (std::vector< unsigned long >::const_iterator &iv)
Private Attributes
int wordIndex
unsigned int words [4]
Detailed Description
Definition at line 108 of file DualRand.h.
View newest version in sPHENIX GitHub at line 108 of file DualRand.h
Constructor & Destructor Documentation
CLHEP::DualRand::Tausworthe::Tausworthe ()
Definition at line 311 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 311 of file DualRand.cc
References wordIndex, and words.
CLHEP::DualRand::Tausworthe::Tausworthe (unsigned int seed)
Definition at line 318 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 318 of file DualRand.cc
References seed.
Member Function Documentation
void CLHEP::DualRand::Tausworthe::get (std::istream & is)
Definition at line 404 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 404 of file DualRand.cc
References CLHEP::MarkerLen.
Referenced by CLHEP::DualRand::getState(), and CLHEP::DualRand::restoreStatus().
bool CLHEP::DualRand::Tausworthe::get (std::vector< unsigned long >::const_iterator & iv)
Definition at line 434 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 434 of file DualRand.cc
CLHEP::DualRand::Tausworthe::operator unsigned int ()
Definition at line 325 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 325 of file DualRand.cc
void CLHEP::DualRand::Tausworthe::put (std::ostream & os) const
Definition at line 382 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 382 of file DualRand.cc
References gammaraytel::pr.
Referenced by CLHEP::DualRand::put(), and CLHEP::DualRand::showStatus().
void CLHEP::DualRand::Tausworthe::put (std::vector< unsigned long > & v) const
Definition at line 397 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 397 of file DualRand.cc
Member Data Documentation
int CLHEP::DualRand::Tausworthe::wordIndex private
Definition at line 118 of file DualRand.h.
View newest version in sPHENIX GitHub at line 118 of file DualRand.h
Referenced by Tausworthe().
unsigned int CLHEP::DualRand::Tausworthe::words[4] private
Definition at line 119 of file DualRand.h.
View newest version in sPHENIX GitHub at line 119 of file DualRand.h
Referenced by Tausworthe().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/DualRand.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/DualRand.cc