ECCE @ EIC Software: G4LivermorePolarizedGammaConversionModel Class Reference
G4LivermorePolarizedGammaConversionModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermorePolarizedGammaConversionModel.hh>
Public Member Functions
G4LivermorePolarizedGammaConversionModel (const G4ParticleDefinition *p=0, const G4String &nam="LivermorePolarizedGammaConversion")
virtual ~G4LivermorePolarizedGammaConversionModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0, G4double cut=0, G4double emax=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void ReadData (size_t Z, const char *path=0)
G4double ScreenFunction1 (G4double screenVariable)
G4double ScreenFunction2 (G4double screenVariable)
G4ThreeVector GetRandomPolarization (G4ThreeVector &direction0)
G4ThreeVector GetPerpendicularPolarization (const G4ThreeVector &direction0, const G4ThreeVector &polarization0) const
G4ThreeVector SetPerpendicularVector (G4ThreeVector &a)
void SystemOfRefChange (G4ThreeVector &direction0, G4ThreeVector &direction1, G4ThreeVector &polarization0)
G4double SetPhi (G4double)
G4double SetPsi (G4double, G4double)
void SetTheta (G4double *, G4double *, G4double)
G4double Poli (G4double, G4double, G4double, G4double)
G4double Fln (G4double, G4double, G4double)
G4double Encu (G4double *, G4double *, G4double)
G4double Flor (G4double *, G4double)
G4double Glor (G4double *, G4double)
G4double Fdlor (G4double *, G4double)
G4double Fintlor (G4double *, G4double)
G4double Finvlor (G4double *, G4double, G4double)
G4double Ftan (G4double *, G4double)
G4double Fdtan (G4double *, G4double)
G4double Finttan (G4double *, G4double)
G4double Finvtan (G4double *, G4double, G4double)
G4LivermorePolarizedGammaConversionModel & operator= (const G4LivermorePolarizedGammaConversionModel &right)
G4LivermorePolarizedGammaConversionModel (const G4LivermorePolarizedGammaConversionModel &)
Private Attributes
G4ParticleChangeForGamma * fParticleChange
G4double lowEnergyLimit
G4bool isInitialised
G4int verboseLevel
G4double smallEnergy
G4double Psi
G4double Phi
Static Private Attributes
static G4int maxZ = 99
static G4LPhysicsFreeVector * data [100] = {0}
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 42 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 42 of file G4LivermorePolarizedGammaConversionModel.hh
Constructor & Destructor Documentation
G4LivermorePolarizedGammaConversionModel::G4LivermorePolarizedGammaConversionModel (const G4ParticleDefinition * p = 0, const G4String & nam = "LivermorePolarizedGammaConversion")
Definition at line 50 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4LivermorePolarizedGammaConversionModel.cc
References source.hepunit::electron_mass_c2, fParticleChange, G4cout, G4endl, lowEnergyLimit, Phi, Psi, and verboseLevel.
G4LivermorePolarizedGammaConversionModel::~G4LivermorePolarizedGammaConversionModel () virtual
Definition at line 75 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 75 of file G4LivermorePolarizedGammaConversionModel.cc
References G4VEmModel::IsMaster(), and maxZ.
G4LivermorePolarizedGammaConversionModel::G4LivermorePolarizedGammaConversionModel (const G4LivermorePolarizedGammaConversionModel &) private
Member Function Documentation
G4double G4LivermorePolarizedGammaConversionModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0, G4double cut = 0, G4double emax = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 220 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 220 of file G4LivermorePolarizedGammaConversionModel.cc
References G4cout, G4endl, G4PhysicsVector::GetVectorLength(), InitialiseForElement(), lowEnergyLimit, maxZ, MeV, n, G4PhysicsVector::Value(), and verboseLevel.
G4double G4LivermorePolarizedGammaConversionModel::Encu (G4double * p_p1, G4double * p_p2, G4double x0) private
Definition at line 855 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 855 of file G4LivermorePolarizedGammaConversionModel.cc
References x, and xmax.
Referenced by SetPhi(), and SetPsi().
G4double G4LivermorePolarizedGammaConversionModel::Fdlor (G4double * p_p1, G4double x) private
Definition at line 906 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 906 of file G4LivermorePolarizedGammaConversionModel.cc
References A(), pi, and w.
G4double G4LivermorePolarizedGammaConversionModel::Fdtan (G4double * p_p1, G4double x) private
Definition at line 960 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 960 of file G4LivermorePolarizedGammaConversionModel.cc
References b.
G4double G4LivermorePolarizedGammaConversionModel::Fintlor (G4double * p_p1, G4double x) private
Definition at line 920 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 920 of file G4LivermorePolarizedGammaConversionModel.cc
References A(), pi, and w.
Referenced by SetPhi().
G4double G4LivermorePolarizedGammaConversionModel::Finttan (G4double * p_p1, G4double x) private
Definition at line 971 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 971 of file G4LivermorePolarizedGammaConversionModel.cc
Referenced by SetPhi().
G4double G4LivermorePolarizedGammaConversionModel::Finvlor (G4double * p_p1, G4double x, G4double r) private
Definition at line 933 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 933 of file G4LivermorePolarizedGammaConversionModel.cc
References pi, and w.
Referenced by SetPhi().
G4double G4LivermorePolarizedGammaConversionModel::Finvtan (G4double * p_p1, G4double cnor, G4double r) private
Definition at line 983 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 983 of file G4LivermorePolarizedGammaConversionModel.cc
References G4Exp().
Referenced by SetPhi().
G4double G4LivermorePolarizedGammaConversionModel::Fln (G4double a, G4double b, G4double x) private
Definition at line 839 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 839 of file G4LivermorePolarizedGammaConversionModel.cc
References b.
Referenced by SetPhi(), and SetPsi().
G4double G4LivermorePolarizedGammaConversionModel::Flor (G4double * p_p1, G4double x) private
Definition at line 880 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 880 of file G4LivermorePolarizedGammaConversionModel.cc
References pi, and w.
Referenced by SetPsi().
G4double G4LivermorePolarizedGammaConversionModel::Ftan (G4double * p_p1, G4double x) private
Definition at line 949 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 949 of file G4LivermorePolarizedGammaConversionModel.cc
References b.
Referenced by SetPsi().
G4ThreeVector G4LivermorePolarizedGammaConversionModel::GetPerpendicularPolarization (const G4ThreeVector & direction0, const G4ThreeVector & polarization0) const private
Definition at line 1042 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 1042 of file G4LivermorePolarizedGammaConversionModel.cc
References CLHEP::Hep3Vector::dot().
Referenced by SampleSecondaries().
G4ThreeVector G4LivermorePolarizedGammaConversionModel::GetRandomPolarization (G4ThreeVector & direction0) private
Definition at line 1016 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 1016 of file G4LivermorePolarizedGammaConversionModel.cc
References a0, angle, c, CLHEP::Hep3Vector::cross(), G4UniformRand, ds::rand1, SetPerpendicularVector(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SampleSecondaries().
G4double G4LivermorePolarizedGammaConversionModel::Glor (G4double * p_p1, G4double x) private
Definition at line 893 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 893 of file G4LivermorePolarizedGammaConversionModel.cc
References A(), pi, and w.
Referenced by SetPhi().
void G4LivermorePolarizedGammaConversionModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector & cuts) virtual
Implements G4VEmModel.
Definition at line 89 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 89 of file G4LivermorePolarizedGammaConversionModel.cc
References fParticleChange, G4cout, G4endl, G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4VEmModel::GetParticleChangeForGamma(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), GeV, G4VEmModel::HighEnergyLimit(), G4VEmModel::InitialiseElementSelectors(), isInitialised, G4VEmModel::IsMaster(), G4VEmModel::LowEnergyLimit(), material(), maxZ, MeV, ReadData(), verboseLevel, and Z.
void G4LivermorePolarizedGammaConversionModel::InitialiseForElement (const G4ParticleDefinition * , G4int Z) virtual
Reimplemented from G4VEmModel.
Definition at line 1086 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 1086 of file G4LivermorePolarizedGammaConversionModel.cc
References ReadData(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by ComputeCrossSectionPerAtom().
void G4LivermorePolarizedGammaConversionModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) virtual
Reimplemented from G4VEmModel.
Definition at line 144 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 144 of file G4LivermorePolarizedGammaConversionModel.cc
References G4VEmModel::GetElementSelectors(), and G4VEmModel::SetElementSelectors().
G4double G4LivermorePolarizedGammaConversionModel::MinPrimaryEnergy (const G4Material * , const G4ParticleDefinition * , G4double) virtual
Reimplemented from G4VEmModel.
Definition at line 152 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 152 of file G4LivermorePolarizedGammaConversionModel.cc
References lowEnergyLimit.
G4LivermorePolarizedGammaConversionModel& G4LivermorePolarizedGammaConversionModel::operator= (const G4LivermorePolarizedGammaConversionModel & right) private
G4double G4LivermorePolarizedGammaConversionModel::Poli (G4double a, G4double b, G4double c, G4double x) private
Definition at line 825 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 825 of file G4LivermorePolarizedGammaConversionModel.cc
References x.
Referenced by SetPhi(), and SetPsi().
void G4LivermorePolarizedGammaConversionModel::ReadData (size_t Z, const char * path = 0) private
Definition at line 160 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 160 of file G4LivermorePolarizedGammaConversionModel.cc
References FatalException, fin, G4cout, G4endl, G4Exception(), verboseLevel, and Z.
Referenced by Initialise(), and InitialiseForElement().
void G4LivermorePolarizedGammaConversionModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicGamma, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 268 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 268 of file G4LivermorePolarizedGammaConversionModel.cc
References e, G4Electron::Electron(), source.hepunit::electron_mass_c2, epsilon(), fParticleChange, fStopAndKill, G4cout, G4endl, G4Exp(), G4UniformRand, G4DynamicParticle::GetDefinition(), G4Element::GetfCoulomb(), G4Element::GetIonisation(), G4DynamicParticle::GetKineticEnergy(), G4IonisParamElm::GetlogZ3(), G4DynamicParticle::GetMomentumDirection(), GetPerpendicularPolarization(), G4DynamicParticle::GetPolarization(), GetRandomPolarization(), G4IonisParamElm::GetZ3(), CLHEP::Hep3Vector::howOrthogonal(), CLHEP::Hep3Vector::isOrthogonal(), lowEnergyLimit, CLHEP::Hep3Vector::mag(), max, MeV, min, particle, Phi, phi, G4Positron::Positron(), G4VParticleChange::ProposeTrackStatus(), Psi, ScreenFunction1(), ScreenFunction2(), G4VEmModel::SelectRandomAtom(), SetPhi(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), SetPsi(), SetTheta(), smallEnergy, SystemOfRefChange(), and verboseLevel.
G4double G4LivermorePolarizedGammaConversionModel::ScreenFunction1 (G4double screenVariable) private
Definition at line 545 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 545 of file G4LivermorePolarizedGammaConversionModel.cc
Referenced by SampleSecondaries().
G4double G4LivermorePolarizedGammaConversionModel::ScreenFunction2 (G4double screenVariable) private
Definition at line 561 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 561 of file G4LivermorePolarizedGammaConversionModel.cc
Referenced by SampleSecondaries().
G4ThreeVector G4LivermorePolarizedGammaConversionModel::SetPerpendicularVector (G4ThreeVector & a) private
Definition at line 999 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 999 of file G4LivermorePolarizedGammaConversionModel.cc
References dx, dy, dz, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by GetRandomPolarization().
G4double G4LivermorePolarizedGammaConversionModel::SetPhi (G4double Energy) private
Definition at line 591 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 591 of file G4LivermorePolarizedGammaConversionModel.cc
References c1, Encu(), Fintlor(), Finttan(), Finvlor(), Finvtan(), Fln(), G4UniformRand, Glor(), MeV, n, n1, pi, readPY::pl, Poli(), pt, r1, and r2.
Referenced by SampleSecondaries().
G4double G4LivermorePolarizedGammaConversionModel::SetPsi (G4double Energy, G4double PhiLocal) private
Definition at line 699 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 699 of file G4LivermorePolarizedGammaConversionModel.cc
References a, b, Encu(), Fln(), Flor(), Ftan(), G4UniformRand, MeV, pi, Poli(), r1, and r2.
Referenced by SampleSecondaries().
void G4LivermorePolarizedGammaConversionModel::SetTheta (G4double * p_cosTheta, G4double * p_sinTheta, G4double Energy) private
Definition at line 576 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 576 of file G4LivermorePolarizedGammaConversionModel.cc
References G4UniformRand.
Referenced by SampleSecondaries().
void G4LivermorePolarizedGammaConversionModel::SystemOfRefChange (G4ThreeVector & direction0, G4ThreeVector & direction1, G4ThreeVector & polarization0) private
Definition at line 1062 of file G4LivermorePolarizedGammaConversionModel.cc.
View newest version in sPHENIX GitHub at line 1062 of file G4LivermorePolarizedGammaConversionModel.cc
References CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), and CLHEP::Hep3Vector::unit().
Referenced by SampleSecondaries().
Member Data Documentation
G4LPhysicsFreeVector * G4LivermorePolarizedGammaConversionModel::data = {0} static private
Definition at line 137 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 137 of file G4LivermorePolarizedGammaConversionModel.hh
G4ParticleChangeForGamma* G4LivermorePolarizedGammaConversionModel::fParticleChange private
Definition at line 79 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 79 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by G4LivermorePolarizedGammaConversionModel(), Initialise(), and SampleSecondaries().
G4bool G4LivermorePolarizedGammaConversionModel::isInitialised private
Definition at line 84 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by Initialise().
G4double G4LivermorePolarizedGammaConversionModel::lowEnergyLimit private
Definition at line 81 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4LivermorePolarizedGammaConversionModel(), MinPrimaryEnergy(), and SampleSecondaries().
G4int G4LivermorePolarizedGammaConversionModel::maxZ = 99 static private
Definition at line 136 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 136 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by ComputeCrossSectionPerAtom(), Initialise(), and ~G4LivermorePolarizedGammaConversionModel().
G4double G4LivermorePolarizedGammaConversionModel::Phi private
Definition at line 130 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by G4LivermorePolarizedGammaConversionModel(), and SampleSecondaries().
G4double G4LivermorePolarizedGammaConversionModel::Psi private
Definition at line 130 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by G4LivermorePolarizedGammaConversionModel(), and SampleSecondaries().
G4double G4LivermorePolarizedGammaConversionModel::smallEnergy private
Definition at line 129 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by SampleSecondaries().
G4int G4LivermorePolarizedGammaConversionModel::verboseLevel private
Definition at line 85 of file G4LivermorePolarizedGammaConversionModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4LivermorePolarizedGammaConversionModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4LivermorePolarizedGammaConversionModel(), Initialise(), ReadData(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermorePolarizedGammaConversionModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4LivermorePolarizedGammaConversionModel.cc