ECCE @ EIC Software: emcalculator Namespace Reference
emcalculator Namespace Reference
Functions
def CalculatePhotonCrossSection
def CalculateDEDX
Variables
list __all__ [ 'CalculatePhotonCrossSection', 'CalculateDEDX' ]
Detailed Description
# ==================================================================
#   Python module (Python3)
#
#   Calculation of photon cross section and stopping power for
#   chared particles
#
#                                              Q, 2005
# ==================================================================
Function Documentation
def emcalculator.CalculateDEDX (part, mat, elist, verbose = 0, plist = ["eIoni", eBrem, muIoni, muBrems, hIoni)
Calculate stopping powers for a give particle, material and
a list of energy, returing stopping power for the components of
"Ionization", "Radiation" and total one.
Arguments:
  part:     particle name
  mat:      material name
  elist:    list of energy
  verbose:  verbose level [0]
  plist:    list of process name
            (electron ionization/electron brems/
             muon ionization/muon brems/hadron ionization) [StandardEM set]
Keys of index:
  "ioni":   ionization
  "brems":  Bremsstrahlung
  "tot":    total
Example:
  dedx_list= CalculateDEDX(...)
  value= dedx_list[energy_index]["ioni"]
Definition at line 88 of file emcalculator.py.
View newest version in sPHENIX GitHub at line 88 of file emcalculator.py
References if(), and print().
Referenced by CalculatePhotonCrossSection().
def emcalculator.CalculatePhotonCrossSection (mat, elist, verbose = 0, plist = ["compt", phot, conv)
Calculate photon cross section for a given material and
a list of energy, returing a list of cross sections for
the components of "Copmton scattering", "rayleigh scattering",
"photoelectric effect", "pair creation" and total one.
Arguments:
  mat:      material name
  elist:    list of energy
  verbose:  verbose level [0]
  plist:    list of process name
            (compton/rayleigh/photoelectic/conversion) [StandardEM set]
Keys of index:
  "compt":     Compton Scattering
  "rayleigh":  Rayleigh Scattering
  "phot" :     photoelectric effect
  "conv" :     pair Creation
  "tot"  :     total
Example:
  xsec_list= CalculatePhotonCrossSection(...)
  value= xsec_list[energy_index]["compt"]
Definition at line 22 of file emcalculator.py.
View newest version in sPHENIX GitHub at line 22 of file emcalculator.py
References CalculateDEDX(), if(), and print().
Variable Documentation
list emcalculator.__all__ [ 'CalculatePhotonCrossSection', 'CalculateDEDX' ]
Definition at line 16 of file emcalculator.py.
View newest version in sPHENIX GitHub at line 16 of file emcalculator.py