ECCE @ EIC Software: G4DiffuseElasticV2 Class Reference
G4DiffuseElasticV2 Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4DiffuseElasticV2.hh>
Public Member Functions
G4DiffuseElasticV2 ()
virtual ~G4DiffuseElasticV2 ()
virtual G4bool IsApplicable (const G4HadProjectile &, G4Nucleus &)
void Initialise ()
void InitialiseOnFly (G4double Z, G4double A)
void BuildAngleTable ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double NeutronTuniform (G4int Z)
void SetPlabLowLimit (G4double value)
void SetHEModelLowLimit (G4double value)
void SetQModelLowLimit (G4double value)
void SetLowestEnergyLimit (G4double value)
void SetRecoilKinEnergyLimit (G4double value)
G4double SampleTableT (const G4ParticleDefinition *aParticle, G4double p, G4double Z, G4double A)
G4double SampleThetaCMS (const G4ParticleDefinition *aParticle, G4double p, G4double A)
G4double SampleTableThetaCMS (const G4ParticleDefinition *aParticle, G4double p, G4double Z, G4double A)
G4double GetScatteringAngle (G4int iMomentum, unsigned long iAngle, G4double position)
G4double SampleThetaLab (const G4HadProjectile *aParticle, G4double tmass, G4double A)
G4double CalculateZommerfeld (G4double beta, G4double Z1, G4double Z2)
G4double CalculateAm (G4double momentum, G4double n, G4double Z)
G4double CalculateNuclearRad (G4double A)
G4double ThetaCMStoThetaLab (const G4DynamicParticle *aParticle, G4double tmass, G4double thetaCMS)
G4double ThetaLabToThetaCMS (const G4DynamicParticle *aParticle, G4double tmass, G4double thetaLab)
G4double BesselJzero (G4double z)
G4double BesselJone (G4double z)
G4double DampFactor (G4double z)
G4double BesselOneByArg (G4double z)
G4double GetDiffElasticSumProbA (G4double alpha)
G4double GetIntegrandFunction (G4double theta)
G4double GetNuclearRadius ()
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4double lowEnergyRecoilLimit
G4double lowEnergyLimitHE
G4double lowEnergyLimitQ
G4double lowestEnergyLimit
G4double plabLowLimit
G4int fEnergyBin
unsigned long fAngleBin
G4PhysicsLogVector * fEnergyVector
std::vector< std::vector
< std::vector< double > * > * > fEnergyAngleVectorBank
std::vector< std::vector
< std::vector< double > * > * > fEnergySumVectorBank
std::vector< std::vector
< double > * > * fEnergyAngleVector
std::vector< std::vector
< double > * > * fEnergySumVector
std::vector< G4double > fElementNumberVector
std::vector< G4String > fElementNameVector
const G4ParticleDefinition * fParticle
G4double fWaveVector
G4double fAtomicWeight
G4double fAtomicNumber
G4double fNuclearRadius
G4double fBeta
G4double fZommerfeld
G4double fAm
G4bool fAddCoulomb
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 61 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 61 of file G4DiffuseElasticV2.hh
Constructor & Destructor Documentation
G4DiffuseElasticV2::G4DiffuseElasticV2 ()
Definition at line 76 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 76 of file G4DiffuseElasticV2.cc
References fAddCoulomb, fAm, fAngleBin, fAtomicNumber, fAtomicWeight, fBeta, fEnergyAngleVector, fEnergyBin, fEnergySumVector, fEnergyVector, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, G4HadronicInteraction::GetMaxEnergy(), GeV, G4HadronicParameters::Instance(), keV, lowEnergyLimitHE, lowEnergyLimitQ, lowEnergyRecoilLimit, lowestEnergyLimit, MeV, G4Neutron::Neutron(), plabLowLimit, G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4HadronicInteraction::theMaxEnergy, G4HadronicInteraction::theMinEnergy, theNeutron, theProton, and G4HadronicInteraction::verboseLevel.
G4DiffuseElasticV2::~G4DiffuseElasticV2 () virtual
Definition at line 115 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 115 of file G4DiffuseElasticV2.cc
References fEnergyVector.
Member Function Documentation
G4double G4DiffuseElasticV2::BesselJone (G4double z) inline
Definition at line 267 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 267 of file G4DiffuseElasticV2.hh
Referenced by BesselOneByArg(), and GetDiffElasticSumProbA().
G4double G4DiffuseElasticV2::BesselJzero (G4double z) inline
Definition at line 215 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 215 of file G4DiffuseElasticV2.hh
Referenced by GetDiffElasticSumProbA().
G4double G4DiffuseElasticV2::BesselOneByArg (G4double z) inline
Definition at line 342 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 342 of file G4DiffuseElasticV2.hh
References BesselJone(), x, and x2.
Referenced by GetDiffElasticSumProbA().
void G4DiffuseElasticV2::BuildAngleTable ()
Definition at line 435 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 435 of file G4DiffuseElasticV2.cc
References a, CalculateAm(), CalculateZommerfeld(), Acts::Test::delta, G4PhysicsVector::Energy(), fAddCoulomb, fAm, fAngleBin, fAtomicNumber, fBeta, fEnergyAngleVector, fEnergyBin, fEnergySumVector, fEnergyVector, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, GetIntegrandFunction(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, G4Integrator< T, F >::Legendre10(), CLHEP::pi, sum, and z.
Referenced by Initialise(), and InitialiseOnFly().
G4double G4DiffuseElasticV2::CalculateAm (G4double momentum, G4double n, G4double Z) inline
Definition at line 375 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 375 of file G4DiffuseElasticV2.hh
References G4Pow::A13(), CLHEP::Bohr_radius, fAm, G4Pow::GetInstance(), CLHEP::hbarc, k, and n.
Referenced by BuildAngleTable().
G4double G4DiffuseElasticV2::CalculateNuclearRad (G4double A) inline
Definition at line 390 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 390 of file G4DiffuseElasticV2.hh
References G4Pow::A13(), G4Pow::A23(), kdfinder::abs(), CLHEP::fermi, fNuclearRadius, G4Pow::GetInstance(), G4Pow::powA(), and Acts::IntegrationTest::R.
Referenced by Initialise(), and InitialiseOnFly().
G4double G4DiffuseElasticV2::CalculateZommerfeld (G4double beta, G4double Z1, G4double Z2) inline
Definition at line 364 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 364 of file G4DiffuseElasticV2.hh
References CLHEP::fine_structure_const, and fZommerfeld.
Referenced by BuildAngleTable().
G4double G4DiffuseElasticV2::DampFactor (G4double z) inline
Definition at line 319 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 319 of file G4DiffuseElasticV2.hh
References f2, f3, and f4.
Referenced by GetDiffElasticSumProbA().
G4double G4DiffuseElasticV2::GetDiffElasticSumProbA (G4double alpha)
Definition at line 164 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 164 of file G4DiffuseElasticV2.cc
References BesselJone(), BesselJzero(), BesselOneByArg(), DampFactor(), Acts::Test::delta, e1, e2, fAddCoulomb, fAm, fermi, fNuclearRadius, fParticle, fWaveVector, fZommerfeld, G4Exp(), G4InuclParticleNames::lambda, pi, theNeutron, theProton, and theta().
Referenced by GetIntegrandFunction().
G4double G4DiffuseElasticV2::GetIntegrandFunction (G4double theta)
Definition at line 257 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 257 of file G4DiffuseElasticV2.cc
References GetDiffElasticSumProbA(), and CLHEP::pi.
Referenced by BuildAngleTable().
G4double G4DiffuseElasticV2::GetNuclearRadius () inline
Definition at line 129 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 129 of file G4DiffuseElasticV2.hh
G4double G4DiffuseElasticV2::GetScatteringAngle (G4int iMomentum, unsigned long iAngle, G4double position)
Definition at line 507 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 507 of file G4DiffuseElasticV2.cc
References fEnergyAngleVector, G4UniformRand, x1, x2, y1, and y2.
Referenced by SampleTableThetaCMS().
void G4DiffuseElasticV2::Initialise ()
Definition at line 128 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 128 of file G4DiffuseElasticV2.cc
References BuildAngleTable(), CalculateNuclearRad(), fAtomicNumber, fAtomicWeight, fElementNameVector, fElementNumberVector, fEnergyAngleVector, fEnergyAngleVectorBank, fEnergySumVector, fEnergySumVectorBank, fNuclearRadius, G4cout, G4endl, G4NistManager::GetAtomicMassAmu(), G4Element::GetElementTable(), G4Element::GetNumberOfElements(), G4NistManager::Instance(), and G4HadronicInteraction::verboseLevel.
void G4DiffuseElasticV2::InitialiseOnFly (G4double Z, G4double A)
Definition at line 408 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 408 of file G4DiffuseElasticV2.cc
References BuildAngleTable(), CalculateNuclearRad(), fAtomicNumber, fAtomicWeight, fElementNumberVector, fEnergyAngleVector, fEnergyAngleVectorBank, fEnergySumVector, fEnergySumVectorBank, fNuclearRadius, G4cout, G4endl, G4NistManager::GetAtomicMassAmu(), G4NistManager::Instance(), G4HadronicInteraction::verboseLevel, and Z.
Referenced by SampleTableThetaCMS().
G4bool G4DiffuseElasticV2::IsApplicable (const G4HadProjectile & projectile, G4Nucleus & nucleus) inline virtual
Reimplemented from G4HadronicInteraction.
Definition at line 170 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 170 of file G4DiffuseElasticV2.hh
References G4HadProjectile::GetDefinition(), G4Nucleus::GetZ_asInt(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), and G4Proton::Proton().
G4double G4DiffuseElasticV2::NeutronTuniform (G4int Z)
Definition at line 310 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 310 of file G4DiffuseElasticV2.cc
References G4Exp().
Referenced by SampleInvariantT().
G4double G4DiffuseElasticV2::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 273 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 273 of file G4DiffuseElasticV2.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), fParticle, G4UniformRand, G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag(), NeutronTuniform(), SampleTableT(), t, theNeutron, and CLHEP::HepLorentzVector::vect().
G4double G4DiffuseElasticV2::SampleTableT (const G4ParticleDefinition * aParticle, G4double p, G4double Z, G4double A)
Definition at line 324 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 324 of file G4DiffuseElasticV2.cc
References alpha, SampleTableThetaCMS(), and t.
Referenced by SampleInvariantT().
G4double G4DiffuseElasticV2::SampleTableThetaCMS (const G4ParticleDefinition * aParticle, G4double p, G4double Z, G4double A)
Definition at line 339 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 339 of file G4DiffuseElasticV2.cc
References G4PhysicsVector::Energy(), fAngleBin, fElementNumberVector, fEnergyAngleVector, fEnergyAngleVectorBank, fEnergyBin, fEnergySumVector, fEnergySumVectorBank, fEnergyVector, G4PhysicsVector::FindBin(), G4UniformRand, G4ParticleDefinition::GetPDGMass(), GetScatteringAngle(), InitialiseOnFly(), and position.
Referenced by SampleTableT().
G4double G4DiffuseElasticV2::SampleThetaCMS (const G4ParticleDefinition * aParticle, G4double p, G4double A)
G4double G4DiffuseElasticV2::SampleThetaLab (const G4HadProjectile * aParticle, G4double tmass, G4double A)
void G4DiffuseElasticV2::SetHEModelLowLimit (G4double value) inline
Definition at line 194 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 194 of file G4DiffuseElasticV2.hh
References lowEnergyLimitHE.
void G4DiffuseElasticV2::SetLowestEnergyLimit (G4double value) inline
Definition at line 204 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 204 of file G4DiffuseElasticV2.hh
References lowestEnergyLimit.
void G4DiffuseElasticV2::SetPlabLowLimit (G4double value) inline
Definition at line 189 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 189 of file G4DiffuseElasticV2.hh
References plabLowLimit.
void G4DiffuseElasticV2::SetQModelLowLimit (G4double value) inline
Definition at line 199 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 199 of file G4DiffuseElasticV2.hh
References lowEnergyLimitQ.
void G4DiffuseElasticV2::SetRecoilKinEnergyLimit (G4double value) inline
Definition at line 184 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 184 of file G4DiffuseElasticV2.hh
References lowEnergyRecoilLimit.
G4double G4DiffuseElasticV2::ThetaCMStoThetaLab (const G4DynamicParticle * aParticle, G4double tmass, G4double thetaCMS)
Definition at line 552 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 552 of file G4DiffuseElasticV2.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, G4UniformRand, G4DynamicParticle::Get4Momentum(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag(), phi, CLHEP::Hep3Vector::theta(), twopi, v1, CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4DiffuseElasticV2::ThetaLabToThetaCMS (const G4DynamicParticle * aParticle, G4double tmass, G4double thetaLab)
Definition at line 610 of file G4DiffuseElasticV2.cc.
View newest version in sPHENIX GitHub at line 610 of file G4DiffuseElasticV2.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, G4UniformRand, G4DynamicParticle::Get4Momentum(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalMomentum(), phi, CLHEP::Hep3Vector::theta(), twopi, v1, G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4bool G4DiffuseElasticV2::fAddCoulomb private
Definition at line 166 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 166 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), and GetDiffElasticSumProbA().
G4double G4DiffuseElasticV2::fAm private
Definition at line 165 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 165 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), CalculateAm(), G4DiffuseElasticV2(), and GetDiffElasticSumProbA().
unsigned long G4DiffuseElasticV2::fAngleBin private
Definition at line 144 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 144 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), and SampleTableThetaCMS().
G4double G4DiffuseElasticV2::fAtomicNumber private
Definition at line 161 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 161 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), Initialise(), and InitialiseOnFly().
G4double G4DiffuseElasticV2::fAtomicWeight private
Definition at line 160 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 160 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), Initialise(), and InitialiseOnFly().
G4double G4DiffuseElasticV2::fBeta private
Definition at line 163 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 163 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), and G4DiffuseElasticV2().
std::vector<G4String> G4DiffuseElasticV2::fElementNameVector private
Definition at line 156 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 156 of file G4DiffuseElasticV2.hh
Referenced by Initialise().
std::vector<G4double> G4DiffuseElasticV2::fElementNumberVector private
Definition at line 155 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 155 of file G4DiffuseElasticV2.hh
Referenced by Initialise(), InitialiseOnFly(), and SampleTableThetaCMS().
std::vector<std::vector<double>*>* G4DiffuseElasticV2::fEnergyAngleVector private
Definition at line 151 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 151 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), GetScatteringAngle(), Initialise(), InitialiseOnFly(), and SampleTableThetaCMS().
std::vector<std::vector<std::vector<double>*>*> G4DiffuseElasticV2::fEnergyAngleVectorBank private
Definition at line 148 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 148 of file G4DiffuseElasticV2.hh
Referenced by Initialise(), InitialiseOnFly(), and SampleTableThetaCMS().
G4int G4DiffuseElasticV2::fEnergyBin private
Definition at line 143 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 143 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), and SampleTableThetaCMS().
std::vector<std::vector<double>*>* G4DiffuseElasticV2::fEnergySumVector private
Definition at line 152 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 152 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), Initialise(), InitialiseOnFly(), and SampleTableThetaCMS().
std::vector<std::vector<std::vector<double>*>*> G4DiffuseElasticV2::fEnergySumVectorBank private
Definition at line 149 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 149 of file G4DiffuseElasticV2.hh
Referenced by Initialise(), InitialiseOnFly(), and SampleTableThetaCMS().
G4PhysicsLogVector* G4DiffuseElasticV2::fEnergyVector private
Definition at line 146 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 146 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), SampleTableThetaCMS(), and ~G4DiffuseElasticV2().
G4double G4DiffuseElasticV2::fNuclearRadius private
Definition at line 162 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 162 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), CalculateNuclearRad(), G4DiffuseElasticV2(), GetDiffElasticSumProbA(), Initialise(), and InitialiseOnFly().
const G4ParticleDefinition* G4DiffuseElasticV2::fParticle private
Definition at line 158 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 158 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), GetDiffElasticSumProbA(), and SampleInvariantT().
G4double G4DiffuseElasticV2::fWaveVector private
Definition at line 159 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 159 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), G4DiffuseElasticV2(), and GetDiffElasticSumProbA().
G4double G4DiffuseElasticV2::fZommerfeld private
Definition at line 164 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 164 of file G4DiffuseElasticV2.hh
Referenced by BuildAngleTable(), CalculateZommerfeld(), G4DiffuseElasticV2(), and GetDiffElasticSumProbA().
G4double G4DiffuseElasticV2::lowEnergyLimitHE private
Definition at line 138 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 138 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), and SetHEModelLowLimit().
G4double G4DiffuseElasticV2::lowEnergyLimitQ private
Definition at line 139 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 139 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), and SetQModelLowLimit().
G4double G4DiffuseElasticV2::lowEnergyRecoilLimit private
Definition at line 137 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 137 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), and SetRecoilKinEnergyLimit().
G4double G4DiffuseElasticV2::lowestEnergyLimit private
Definition at line 140 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 140 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), and SetLowestEnergyLimit().
G4double G4DiffuseElasticV2::plabLowLimit private
Definition at line 141 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 141 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), and SetPlabLowLimit().
G4ParticleDefinition* G4DiffuseElasticV2::theNeutron private
Definition at line 135 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 135 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), GetDiffElasticSumProbA(), and SampleInvariantT().
G4ParticleDefinition* G4DiffuseElasticV2::theProton private
Definition at line 129 of file G4DiffuseElasticV2.hh.
View newest version in sPHENIX GitHub at line 129 of file G4DiffuseElasticV2.hh
Referenced by G4DiffuseElasticV2(), and GetDiffElasticSumProbA().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4DiffuseElasticV2.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4DiffuseElasticV2.cc