ECCE @ EIC Software: G4HumanPhantomConstruction Class Reference
G4HumanPhantomConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomConstruction.hh>
Public Member Functions
G4HumanPhantomConstruction ()
~G4HumanPhantomConstruction ()
G4VPhysicalVolume * Construct ()
void SetBodyPartSensitivity (G4String, G4bool)
void SetPhantomSex (G4String)
void SetPhantomModel (G4String)
void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
G4VPhysicalVolume * ConstructWorld ()
Private Attributes
G4HumanPhantomMaterial * material
G4HumanPhantomMessenger * messenger
G4String model
G4String sex
std::map< std::string, G4bool > sensitivities
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 41 of file G4HumanPhantomConstruction.hh.
View newest version in sPHENIX GitHub at line 41 of file G4HumanPhantomConstruction.hh
Constructor & Destructor Documentation
G4HumanPhantomConstruction::G4HumanPhantomConstruction ()
Definition at line 58 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 58 of file G4HumanPhantomConstruction.cc
References material, and messenger.
G4HumanPhantomConstruction::~G4HumanPhantomConstruction ()
Definition at line 64 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 64 of file G4HumanPhantomConstruction.cc
References material, and messenger.
Member Function Documentation
G4VPhysicalVolume * G4HumanPhantomConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 70 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 70 of file G4HumanPhantomConstruction.cc
References G4BasePhantomBuilder::BuildBrain(), G4BasePhantomBuilder::BuildHead(), G4BasePhantomBuilder::BuildLeftAdrenal(), G4BasePhantomBuilder::BuildLeftArmBone(), G4BasePhantomBuilder::BuildLeftBreast(), G4BasePhantomBuilder::BuildLeftClavicle(), G4BasePhantomBuilder::BuildLeftKidney(), G4BasePhantomBuilder::BuildLeftLeg(), G4BasePhantomBuilder::BuildLeftLegBone(), G4BasePhantomBuilder::BuildLeftOvary(), G4BasePhantomBuilder::BuildLeftScapula(), G4BasePhantomBuilder::BuildLowerLargeIntestine(), G4BasePhantomBuilder::BuildMiddleLowerSpine(), G4BasePhantomBuilder::BuildPancreas(), G4BasePhantomBuilder::BuildPelvis(), G4BasePhantomBuilder::BuildRibCage(), G4BasePhantomBuilder::BuildRightAdrenal(), G4BasePhantomBuilder::BuildRightArmBone(), G4BasePhantomBuilder::BuildRightBreast(), G4BasePhantomBuilder::BuildRightClavicle(), G4BasePhantomBuilder::BuildRightKidney(), G4BasePhantomBuilder::BuildRightLeg(), G4BasePhantomBuilder::BuildRightLegBone(), G4BasePhantomBuilder::BuildRightOvary(), G4BasePhantomBuilder::BuildRightScapula(), G4BasePhantomBuilder::BuildSkull(), G4BasePhantomBuilder::BuildSmallIntestine(), G4BasePhantomBuilder::BuildSpleen(), G4BasePhantomBuilder::BuildStomach(), G4BasePhantomBuilder::BuildThymus(), G4BasePhantomBuilder::BuildTrunk(), G4BasePhantomBuilder::BuildUpperLargeIntestine(), G4BasePhantomBuilder::BuildUpperSpine(), G4BasePhantomBuilder::BuildUrinaryBladder(), G4BasePhantomBuilder::BuildUterus(), G4BasePhantomBuilder::BuildVoxelLeftBreast(), G4BasePhantomBuilder::BuildVoxelRightBreast(), ConstructWorld(), G4cout, G4endl, G4BasePhantomBuilder::GetPhantom(), material, sensitivities, G4BasePhantomBuilder::SetModel(), G4BasePhantomBuilder::SetMotherVolume(), and sex.
void G4HumanPhantomConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 282 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 282 of file G4HumanPhantomConstruction.cc
References G4SDManager::AddNewDetector(), G4cout, G4endl, G4SDManager::GetSDMpointer(), G4VUserDetectorConstruction::SetSensitiveDetector(), and sex.
G4VPhysicalVolume * G4HumanPhantomConstruction::ConstructWorld () private
Definition at line 204 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 204 of file G4HumanPhantomConstruction.cc
References G4VisAttributes::GetInvisible(), m, material, G4VisAttributes::SetForceSolid(), G4LogicalVolume::SetVisAttributes(), and Acts::Test::world.
Referenced by Construct().
void G4HumanPhantomConstruction::SetBodyPartSensitivity (G4String , G4bool)
Definition at line 199 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 199 of file G4HumanPhantomConstruction.cc
References G4cout, and G4endl.
Referenced by G4HumanPhantomMessenger::AddBodyPart().
void G4HumanPhantomConstruction::SetPhantomModel (G4String newModel)
Definition at line 249 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 249 of file G4HumanPhantomConstruction.cc
References G4cout, and G4endl.
Referenced by G4HumanPhantomMessenger::SetNewValue().
void G4HumanPhantomConstruction::SetPhantomSex (G4String newSex)
Definition at line 233 of file G4HumanPhantomConstruction.cc.
View newest version in sPHENIX GitHub at line 233 of file G4HumanPhantomConstruction.cc
References G4cout, G4endl, and sex.
Referenced by G4HumanPhantomMessenger::SetNewValue().
Member Data Documentation
G4HumanPhantomMaterial* G4HumanPhantomConstruction::material private
Definition at line 56 of file G4HumanPhantomConstruction.hh.
View newest version in sPHENIX GitHub at line 56 of file G4HumanPhantomConstruction.hh
Referenced by Construct(), ConstructWorld(), G4HumanPhantomConstruction(), and ~G4HumanPhantomConstruction().
G4HumanPhantomMessenger* G4HumanPhantomConstruction::messenger private
Definition at line 57 of file G4HumanPhantomConstruction.hh.
View newest version in sPHENIX GitHub at line 57 of file G4HumanPhantomConstruction.hh
Referenced by G4HumanPhantomConstruction(), and ~G4HumanPhantomConstruction().
G4String G4HumanPhantomConstruction::model private
Definition at line 60 of file G4HumanPhantomConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4HumanPhantomConstruction.hh
std::map<std::string,G4bool> G4HumanPhantomConstruction::sensitivities private
Definition at line 62 of file G4HumanPhantomConstruction.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HumanPhantomConstruction.hh
Referenced by Construct().
G4String G4HumanPhantomConstruction::sex private
Definition at line 61 of file G4HumanPhantomConstruction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4HumanPhantomConstruction.hh
Referenced by Construct(), ConstructSDandField(), and SetPhantomSex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4HumanPhantomConstruction.cc