ECCE @ EIC Software: G4hPairProductionModel Class Reference
G4hPairProductionModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4hPairProductionModel.hh>
Public Member Functions
G4hPairProductionModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="hPairProd")
virtual ~G4hPairProductionModel ()
Public Member Functions inherited from G4MuPairProductionModel
G4MuPairProductionModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="muPairProd")
virtual ~G4MuPairProductionModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double) override
void SetLowestKineticEnergy (G4double e)
void SetParticle (const G4ParticleDefinition *)
G4MuPairProductionModel & operator= (const G4MuPairProductionModel &right)=delete
G4MuPairProductionModel (const G4MuPairProductionModel &)=delete
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double ComputeDMicroscopicCrossSection (G4double tkin, G4double Z, G4double pairEnergy) override
Protected Member Functions inherited from G4MuPairProductionModel
G4double ComputMuPairLoss (G4double Z, G4double tkin, G4double cut, G4double tmax)
G4double ComputeMicroscopicCrossSection (G4double tkin, G4double Z, G4double cut)
G4double MaxSecondaryEnergyForElement (G4double kineticEnergy, G4double Z)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
G4hPairProductionModel & operator= (const G4hPairProductionModel &right)=delete
G4hPairProductionModel (const G4hPairProductionModel &)=delete
Additional Inherited Members
Protected Attributes inherited from G4MuPairProductionModel
const G4ParticleDefinition * particle
G4NistManager * nist
G4double factorForCross
G4double sqrte
G4double particleMass
G4double z13
G4double z23
G4double lnZ
G4int currentZ
G4ParticleDefinition * theElectron
G4ParticleDefinition * thePositron
G4ParticleChangeForLoss * fParticleChange
G4double minPairEnergy
G4double lowestKinEnergy
G4int nzdat
G4int nYBinPerDecade
size_t nbiny
size_t nbine
G4double ymin
G4double dy
G4double emin
G4double emax
G4bool fTableToFile
Static Protected Attributes inherited from G4MuPairProductionModel
static const G4double xgi [8]
static const G4double wgi [8]
Detailed Description
Definition at line 55 of file G4hPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4hPairProductionModel.hh
Constructor & Destructor Documentation
G4hPairProductionModel::G4hPairProductionModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "hPairProd") explicit
Definition at line 57 of file G4hPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4hPairProductionModel.cc
G4hPairProductionModel::~G4hPairProductionModel () virtual
Definition at line 64 of file G4hPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 64 of file G4hPairProductionModel.cc
G4hPairProductionModel::G4hPairProductionModel (const G4hPairProductionModel &) private delete
Member Function Documentation
G4double G4hPairProductionModel::ComputeDMicroscopicCrossSection (G4double tkin, G4double Z, G4double pairEnergy) override protected virtual
Reimplemented from G4MuPairProductionModel.
Definition at line 69 of file G4hPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4hPairProductionModel.cc
References a0, Acts::VectorHelpers::cross(), e, e3, CLHEP::electron_mass_c2, source.hepunit::electron_mass_c2, G4MuPairProductionModel::factorForCross, fe, Acts::UnitConstants::fm, G4Exp(), G4Log(), G4MuPairProductionModel::particleMass, G4MuPairProductionModel::sqrte, sum, G4MuPairProductionModel::wgi, G4MuPairProductionModel::xgi, G4InuclParticleNames::xi0, G4MuPairProductionModel::z13, z2, and G4MuPairProductionModel::z23.
G4hPairProductionModel& G4hPairProductionModel::operator= (const G4hPairProductionModel & right) private delete
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4hPairProductionModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4hPairProductionModel.cc