ECCE @ EIC Software: pyG4LogicalVolume Namespace Reference
pyG4LogicalVolume Namespace Reference
Variables
void(G4LogicalVolume::* f1_SetVisAttributes)(const G4VisAttributes *) = &G4LogicalVolume::SetVisAttributes
void(G4LogicalVolume::* f2_SetVisAttributes)(const G4VisAttributes &) = &G4LogicalVolume::SetVisAttributes
G4VSolid *(G4LogicalVolume::* f1_GetSolid)() const = &G4LogicalVolume::GetSolid
void(G4LogicalVolume::* f1_SetSolid)(G4VSolid *) = &G4LogicalVolume::SetSolid
Variable Documentation
G4VSolid*(G4LogicalVolume::* pyG4LogicalVolume::f1_GetSolid)() const = &G4LogicalVolume::GetSolid
Definition at line 57 of file pyG4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 57 of file pyG4LogicalVolume.cc
Referenced by export_G4LogicalVolume().
void(G4LogicalVolume::* pyG4LogicalVolume::f1_SetSolid)(G4VSolid *) = &G4LogicalVolume::SetSolid
Definition at line 59 of file pyG4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 59 of file pyG4LogicalVolume.cc
Referenced by export_G4LogicalVolume().
void(G4LogicalVolume::* pyG4LogicalVolume::f1_SetVisAttributes)(const G4VisAttributes *) = &G4LogicalVolume::SetVisAttributes
Definition at line 51 of file pyG4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 51 of file pyG4LogicalVolume.cc
Referenced by export_G4LogicalVolume().
void(G4LogicalVolume::* pyG4LogicalVolume::f2_SetVisAttributes)(const G4VisAttributes &) = &G4LogicalVolume::SetVisAttributes
Definition at line 54 of file pyG4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4LogicalVolume.cc
Referenced by export_G4LogicalVolume().