ECCE @ EIC Software: macros/blob/master/common/G4_DSTReader_EICDetector.C File Reference
G4_DSTReader_EICDetector.C File Reference
#include <GlobalVariables.C>
#include <g4eval/PHG4DSTReader.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4DSTREADER
Macros
#define MACRO_G4DSTREADEREICDETECTOR_C
Functions
void G4DSTreader_EICDetectorInit ()
void G4DSTreader_EICDetector (const string &outputFile="G4sPHENIXCells.root")
Variables
bool Enable::DSTREADER = false
int Enable::DSTREADER_VERBOSITY = 0
bool G4DSTREADER::save_g4_raw = true
double G4DSTREADER::tower_zero_supp = 1.e-6
Macro Definition Documentation
#define MACRO_G4DSTREADEREICDETECTOR_C
Definition at line 2 of file G4_DSTReader_EICDetector.C.
View newest version in sPHENIX GitHub at line 2 of file G4_DSTReader_EICDetector.C
Function Documentation
void G4DSTreader_EICDetector (const string & outputFile = "G4sPHENIXCells.root")
debug output on screen?
Definition at line 34 of file G4_DSTReader_EICDetector.C.
View newest version in sPHENIX GitHub at line 34 of file G4_DSTReader_EICDetector.C
References PHG4DSTReader::AddNode(), PHG4DSTReader::AddTower(), Enable::BARREL, Enable::BLACKHOLE, Enable::CEMC_TOWER, Enable::CTTL, Enable::DIRC, Enable::DSTREADER_VERBOSITY, Enable::EEMC_TOWER, Enable::EEMCH_TOWER, Enable::EGEM, Enable::ETTL, Enable::FEMC_TOWER, Enable::FGEM, Enable::FHCAL_TOWER, Enable::FST, Enable::FTTL, Enable::HCALIN_TOWER, Enable::HCALOUT_TOWER, Enable::HFARFWD_VIRTUAL_DETECTORS_IP6, Enable::HFARFWD_VIRTUAL_DETECTORS_IP8, Fun4AllServer::instance(), max, Enable::mRICH, Enable::PIPE, Enable::PIPE_ABSORBER, Fun4AllServer::registerSubsystem(), Enable::RICH, Enable::RWELL, G4DSTREADER::save_g4_raw, PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHG4DSTReader::set_tower_zero_sup(), G4DSTREADER::tower_zero_supp, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_runEvaluators().
void G4DSTreader_EICDetectorInit ()
Definition at line 33 of file G4_DSTReader_EICDetector.C.
View newest version in sPHENIX GitHub at line 33 of file G4_DSTReader_EICDetector.C