ECCE @ EIC Software: G4HadronicParameters Class Reference
G4HadronicParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadronicParameters.hh>
Public Member Functions
~G4HadronicParameters ()
G4double GetMaxEnergy () const
G4double GetMinEnergyTransitionFTF_Cascade () const
G4double GetMaxEnergyTransitionFTF_Cascade () const
G4double GetMinEnergyTransitionQGS_FTF () const
G4double GetMaxEnergyTransitionQGS_FTF () const
Static Public Member Functions
static G4HadronicParameters * Instance ()
Private Member Functions
G4HadronicParameters ()
Private Attributes
G4double fMaxEnergy
G4double fMinEnergyTransitionFTF_Cascade
G4double fMaxEnergyTransitionFTF_Cascade
G4double fMinEnergyTransitionQGS_FTF
G4double fMaxEnergyTransitionQGS_FTF
Static Private Attributes
static G4HadronicParameters * sInstance = nullptr
Detailed Description
Definition at line 49 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HadronicParameters.hh
Constructor & Destructor Documentation
G4HadronicParameters::~G4HadronicParameters ()
Definition at line 59 of file G4HadronicParameters.cc.
View newest version in sPHENIX GitHub at line 59 of file G4HadronicParameters.cc
G4HadronicParameters::G4HadronicParameters () private
Definition at line 62 of file G4HadronicParameters.cc.
View newest version in sPHENIX GitHub at line 62 of file G4HadronicParameters.cc
References fMaxEnergy, fMaxEnergyTransitionFTF_Cascade, fMaxEnergyTransitionQGS_FTF, fMinEnergyTransitionFTF_Cascade, fMinEnergyTransitionQGS_FTF, CLHEP::GeV, and CLHEP::TeV.
Member Function Documentation
G4double G4HadronicParameters::GetMaxEnergy () const inline
Definition at line 86 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HadronicParameters.hh
References fMaxEnergy.
Referenced by BiasingOperation::BiasingOperation(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4IonPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4HadronicInteraction::G4HadronicInteraction(), and G4QGSPKaonBuilder::G4QGSPKaonBuilder().
G4double G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade () const inline
Definition at line 93 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 93 of file G4HadronicParameters.hh
References fMaxEnergyTransitionFTF_Cascade.
Referenced by G4EmExtraPhysics::ConstructGammaElectroNuclear(), G4IonPhysicsPHP::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::CreateModels(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4BertiniKaonBuilder::G4BertiniKaonBuilder(), G4BertiniNeutronBuilder::G4BertiniNeutronBuilder(), G4BertiniPiKBuilder::G4BertiniPiKBuilder(), G4BertiniPionBuilder::G4BertiniPionBuilder(), G4BertiniProtonBuilder::G4BertiniProtonBuilder(), G4BinaryAlphaBuilder::G4BinaryAlphaBuilder(), G4BinaryDeuteronBuilder::G4BinaryDeuteronBuilder(), G4BinaryHe3Builder::G4BinaryHe3Builder(), G4BinaryNeutronBuilder::G4BinaryNeutronBuilder(), G4BinaryProtonBuilder::G4BinaryProtonBuilder(), G4BinaryTritonBuilder::G4BinaryTritonBuilder(), G4HadronPhysicsFTF_BIC::G4HadronPhysicsFTF_BIC(), G4HadronPhysicsFTFP_BERT::G4HadronPhysicsFTFP_BERT(), G4HadronPhysicsFTFP_BERT_TRV::G4HadronPhysicsFTFP_BERT_TRV(), G4HadronPhysicsQGS_BIC::G4HadronPhysicsQGS_BIC(), G4HadronPhysicsQGSP_BERT::G4HadronPhysicsQGSP_BERT(), G4HadronPhysicsQGSP_BIC::G4HadronPhysicsQGSP_BIC(), and G4HadronPhysicsQGSP_FTFP_BERT::G4HadronPhysicsQGSP_FTFP_BERT().
G4double G4HadronicParameters::GetMaxEnergyTransitionQGS_FTF () const inline
Definition at line 100 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 100 of file G4HadronicParameters.hh
References fMaxEnergyTransitionQGS_FTF.
Referenced by G4HadronPhysicsQGSP_BIC_HP::CreateModels(), G4HadronPhysicsQGS_BIC::G4HadronPhysicsQGS_BIC(), G4HadronPhysicsQGSP_BERT::G4HadronPhysicsQGSP_BERT(), and G4HadronPhysicsQGSP_BIC::G4HadronPhysicsQGSP_BIC().
G4double G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade () const inline
Definition at line 90 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HadronicParameters.hh
References fMinEnergyTransitionFTF_Cascade.
Referenced by G4EmExtraPhysics::ConstructGammaElectroNuclear(), G4IonPhysicsPHP::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::CreateModels(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronPhysicsFTFP_BERT::G4HadronPhysicsFTFP_BERT(), G4HadronPhysicsFTFP_BERT_TRV::G4HadronPhysicsFTFP_BERT_TRV(), G4HadronPhysicsQGS_BIC::G4HadronPhysicsQGS_BIC(), G4HadronPhysicsQGSP_BERT::G4HadronPhysicsQGSP_BERT(), G4HadronPhysicsQGSP_BIC::G4HadronPhysicsQGSP_BIC(), and G4HadronPhysicsQGSP_FTFP_BERT::G4HadronPhysicsQGSP_FTFP_BERT().
G4double G4HadronicParameters::GetMinEnergyTransitionQGS_FTF () const inline
Definition at line 97 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4HadronicParameters.hh
References fMinEnergyTransitionQGS_FTF.
Referenced by G4HadronPhysicsQGSP_BERT::G4HadronPhysicsQGSP_BERT(), G4HadronPhysicsQGSP_BIC::G4HadronPhysicsQGSP_BIC(), G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder(), G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder(), G4QGSBinaryPiKBuilder::G4QGSBinaryPiKBuilder(), G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder(), G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder(), G4QGSPKaonBuilder::G4QGSPKaonBuilder(), G4QGSPNeutronBuilder::G4QGSPNeutronBuilder(), G4QGSPPiKBuilder::G4QGSPPiKBuilder(), G4QGSPPionBuilder::G4QGSPPionBuilder(), and G4QGSPProtonBuilder::G4QGSPProtonBuilder().
G4HadronicParameters * G4HadronicParameters::Instance (void) static
Definition at line 50 of file G4HadronicParameters.cc.
View newest version in sPHENIX GitHub at line 50 of file G4HadronicParameters.cc
References sInstance.
Referenced by BiasingOperation::BiasingOperation(), G4BertiniElectroNuclearBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4QGSBinaryKaonBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4QGSPPiKBuilder::Build(), G4QGSPPionBuilder::Build(), G4QGSPProtonBuilder::Build(), G4QGSBinaryNeutronBuilder::Build(), G4QGSPNeutronBuilder::Build(), G4CrossSectionElastic::BuildPhysicsTable(), G4CrossSectionInelastic::BuildPhysicsTable(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4IonPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::CreateModels(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsINCLXX::ExtraConfiguration(), G4BertiniKaonBuilder::G4BertiniKaonBuilder(), G4BertiniNeutronBuilder::G4BertiniNeutronBuilder(), G4BertiniPiKBuilder::G4BertiniPiKBuilder(), G4BertiniPionBuilder::G4BertiniPionBuilder(), G4BertiniProtonBuilder::G4BertiniProtonBuilder(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4BinaryAlphaBuilder::G4BinaryAlphaBuilder(), G4BinaryDeuteronBuilder::G4BinaryDeuteronBuilder(), G4BinaryHe3Builder::G4BinaryHe3Builder(), G4BinaryNeutronBuilder::G4BinaryNeutronBuilder(), G4BinaryProtonBuilder::G4BinaryProtonBuilder(), G4BinaryTritonBuilder::G4BinaryTritonBuilder(), G4ChargeExchange::G4ChargeExchange(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronElastic::G4HadronElastic(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4HadronicInteraction::G4HadronicInteraction(), G4HadronPhysicsFTF_BIC::G4HadronPhysicsFTF_BIC(), G4HadronPhysicsFTFP_BERT::G4HadronPhysicsFTFP_BERT(), G4HadronPhysicsFTFP_BERT_TRV::G4HadronPhysicsFTFP_BERT_TRV(), G4HadronPhysicsQGS_BIC::G4HadronPhysicsQGS_BIC(), G4HadronPhysicsQGSP_BERT::G4HadronPhysicsQGSP_BERT(), G4HadronPhysicsQGSP_BIC::G4HadronPhysicsQGSP_BIC(), G4HadronPhysicsQGSP_FTFP_BERT::G4HadronPhysicsQGSP_FTFP_BERT(), G4hhElastic::G4hhElastic(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4LowEGammaNuclearModel::G4LowEGammaNuclearModel(), G4NeutrinoElectronCcModel::G4NeutrinoElectronCcModel(), G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), G4NeutronRadCapture::G4NeutronRadCapture(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder(), G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder(), G4QGSBinaryPiKBuilder::G4QGSBinaryPiKBuilder(), G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder(), G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder(), G4QGSPKaonBuilder::G4QGSPKaonBuilder(), G4QGSPNeutronBuilder::G4QGSPNeutronBuilder(), G4QGSPPiKBuilder::G4QGSPPiKBuilder(), G4QGSPPionBuilder::G4QGSPPionBuilder(), G4QGSPProtonBuilder::G4QGSPProtonBuilder(), and Shielding::Shielding().
Member Data Documentation
G4double G4HadronicParameters::fMaxEnergy private
Definition at line 78 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronicParameters.hh
Referenced by G4HadronicParameters(), and GetMaxEnergy().
G4double G4HadronicParameters::fMaxEnergyTransitionFTF_Cascade private
Definition at line 80 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HadronicParameters.hh
Referenced by G4HadronicParameters(), and GetMaxEnergyTransitionFTF_Cascade().
G4double G4HadronicParameters::fMaxEnergyTransitionQGS_FTF private
Definition at line 82 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HadronicParameters.hh
Referenced by G4HadronicParameters(), and GetMaxEnergyTransitionQGS_FTF().
G4double G4HadronicParameters::fMinEnergyTransitionFTF_Cascade private
Definition at line 79 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HadronicParameters.hh
Referenced by G4HadronicParameters(), and GetMinEnergyTransitionFTF_Cascade().
G4double G4HadronicParameters::fMinEnergyTransitionQGS_FTF private
Definition at line 81 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadronicParameters.hh
Referenced by G4HadronicParameters(), and GetMinEnergyTransitionQGS_FTF().
G4HadronicParameters * G4HadronicParameters::sInstance = nullptr static private
Definition at line 76 of file G4HadronicParameters.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadronicParameters.hh
Referenced by Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadronicParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4HadronicParameters.cc