ECCE @ EIC Software: G4PhysListRegistry Class Reference
G4PhysListRegistry Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/G4PhysListRegistry.hh>
Public Member Functions
~G4PhysListRegistry ()
void AddFactory (G4String name, G4VBasePhysListStamper *)
void AddPhysicsExtension (G4String name, G4String procname)
G4VModularPhysicsList * GetModularPhysicsList (const G4String &name)
G4VModularPhysicsList * GetModularPhysicsListFromEnv ()
G4bool IsReferencePhysList (G4String nam) const
const std::vector< G4String > & AvailablePhysLists () const
const std::vector< G4String > & AvailablePhysicsExtensions () const
const std::vector< G4String > & AvailablePhysListsEM () const
void PrintAvailablePhysLists () const
G4bool DeconstructPhysListName (const G4String &name, G4String &plBase, std::vector< G4String > &physExt, std::vector< G4int > &replace, G4int verbose=0) const
G4bool FindLongestMatch (const G4String &workName, const G4String &searchName, const std::vector< G4String > &validNames, G4String &bestMatch, G4int verbose=0) const
void SetVerbose (G4int val)
G4int GetVerbose () const
void SetUnknownFatal (G4int val)
G4int GetUnknownFatal () const
void SetUserDefaultPhysList (const G4String &name="")
G4String GetUserDefaultPhysList () const
G4String GetSystemDefaultPhysList () const
Static Public Member Functions
static G4PhysListRegistry * Instance ()
Private Member Functions
G4PhysListRegistry ()
Private Attributes
std::map< G4String,
G4VBasePhysListStamper * > factories
std::map< G4String, G4String > physicsExtensions
G4int verbose
G4int unknownFatal
G4String userDefault
throw an exception if unsatisfiable?
G4String systemDefault
use this if $PHYSLIST isn't set
std::vector< G4String > availBasePhysLists
std::vector< G4String > availExtensions
Static Private Attributes
static G4ThreadLocal
G4PhysListRegistry * theInstance = 0
Detailed Description
Definition at line 56 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 56 of file G4PhysListRegistry.hh
Constructor & Destructor Documentation
G4PhysListRegistry::~G4PhysListRegistry ()
Definition at line 100 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 100 of file G4PhysListRegistry.cc
G4PhysListRegistry::G4PhysListRegistry () private
Definition at line 92 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 92 of file G4PhysListRegistry.cc
References SetUserDefaultPhysList().
Referenced by Instance().
Member Function Documentation
void G4PhysListRegistry::AddFactory (G4String name, G4VBasePhysListStamper * factory)
Definition at line 110 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 110 of file G4PhysListRegistry.cc
References factories.
Referenced by G4PhysListStamper< T >::G4PhysListStamper().
void G4PhysListRegistry::AddPhysicsExtension (G4String name, G4String procname)
Definition at line 115 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 115 of file G4PhysListRegistry.cc
References physicsExtensions.
Referenced by Instance(), and main().
const std::vector< G4String > & G4PhysListRegistry::AvailablePhysicsExtensions () const
Definition at line 389 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 389 of file G4PhysListRegistry.cc
References availExtensions, and physicsExtensions.
Referenced by AvailablePhysListsEM(), and DeconstructPhysListName().
const std::vector< G4String > & G4PhysListRegistry::AvailablePhysLists () const
Definition at line 378 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 378 of file G4PhysListRegistry.cc
References availBasePhysLists, and factories.
Referenced by g4alt::G4PhysListFactory::AvailablePhysLists(), DeconstructPhysListName(), and PrintAvailablePhysLists().
const std::vector< G4String > & G4PhysListRegistry::AvailablePhysListsEM () const
Definition at line 400 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 400 of file G4PhysListRegistry.cc
References AvailablePhysicsExtensions().
Referenced by g4alt::G4PhysListFactory::AvailablePhysListsEM().
G4bool G4PhysListRegistry::DeconstructPhysListName (const G4String & name, G4String & plBase, std::vector< G4String > & physExt, std::vector< G4int > & replace, G4int verbose = 0) const
Definition at line 231 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 231 of file G4PhysListRegistry.cc
References G4PhysicsConstructorRegistry::AvailablePhysicsConstructors(), AvailablePhysicsExtensions(), AvailablePhysLists(), c, G4String::data(), doReplace, FindLongestMatch(), G4cout, G4endl, G4PhysicsConstructorRegistry::Instance(), isCtorName, G4PhysicsConstructorRegistry::IsKnownPhysicsConstructor(), and physicsExtensions.
Referenced by GetModularPhysicsList(), and IsReferencePhysList().
G4bool G4PhysListRegistry::FindLongestMatch (const G4String & workName, const G4String & searchName, const std::vector< G4String > & validNames, G4String & bestMatch, G4int verbose = 0) const
Definition at line 341 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 341 of file G4PhysListRegistry.cc
References G4cout, G4endl, and n.
Referenced by DeconstructPhysListName().
G4VModularPhysicsList * G4PhysListRegistry::GetModularPhysicsList (const G4String & name)
Definition at line 122 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 122 of file G4PhysListRegistry.cc
References DeconstructPhysListName(), doReplace, factories, FatalException, G4cout, G4endl, G4Exception(), G4PhysicsConstructorRegistry::GetPhysicsConstructor(), G4VModularPhysicsList::GetVerboseLevel(), G4PhysicsConstructorRegistry::Instance(), isCtorName, physicsExtensions, readPY::pl, G4VModularPhysicsList::RegisterPhysics(), G4VModularPhysicsList::ReplacePhysics(), G4VModularPhysicsList::SetVerboseLevel(), unknownFatal, and verbose.
Referenced by GetModularPhysicsListFromEnv(), and g4alt::G4PhysListFactory::GetReferencePhysList().
G4VModularPhysicsList * G4PhysListRegistry::GetModularPhysicsListFromEnv ()
Definition at line 201 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 201 of file G4PhysListRegistry.cc
References G4cout, G4endl, GetModularPhysicsList(), and userDefault.
Referenced by g4alt::G4PhysListFactory::ReferencePhysList().
G4String G4PhysListRegistry::GetSystemDefaultPhysList () const inline
Definition at line 102 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PhysListRegistry.hh
References systemDefault.
G4int G4PhysListRegistry::GetUnknownFatal () const inline
Definition at line 95 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PhysListRegistry.hh
References unknownFatal.
Referenced by g4alt::G4PhysListFactory::GetUnknownFatal().
G4String G4PhysListRegistry::GetUserDefaultPhysList () const inline
Definition at line 98 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 98 of file G4PhysListRegistry.hh
References userDefault.
G4int G4PhysListRegistry::GetVerbose () const inline
Definition at line 92 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PhysListRegistry.hh
References verbose.
Referenced by g4alt::G4PhysListFactory::GetVerbose().
G4PhysListRegistry * G4PhysListRegistry::Instance (void) static
Definition at line 64 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 64 of file G4PhysListRegistry.cc
References AddPhysicsExtension(), G4PhysListRegistry(), G4ThreadLocal, and theInstance.
Referenced by g4alt::G4PhysListFactory::AvailablePhysLists(), g4alt::G4PhysListFactory::AvailablePhysListsEM(), G4PhysListStamper< T >::G4PhysListStamper(), g4alt::G4PhysListFactory::GetReferencePhysList(), g4alt::G4PhysListFactory::GetUnknownFatal(), g4alt::G4PhysListFactory::GetVerbose(), g4alt::G4PhysListFactory::IsReferencePhysList(), main(), g4alt::G4PhysListFactory::PrintAvailablePhysLists(), g4alt::G4PhysListFactory::ReferencePhysList(), g4alt::G4PhysListFactory::SetDefaultReferencePhysList(), g4alt::G4PhysListFactory::SetUnknownFatal(), and g4alt::G4PhysListFactory::SetVerbose().
G4bool G4PhysListRegistry::IsReferencePhysList (G4String nam) const
Definition at line 222 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 222 of file G4PhysListRegistry.cc
References DeconstructPhysListName().
Referenced by g4alt::G4PhysListFactory::IsReferencePhysList().
void G4PhysListRegistry::PrintAvailablePhysLists () const
Definition at line 408 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 408 of file G4PhysListRegistry.cc
References AvailablePhysLists(), G4cout, G4endl, G4PhysicsConstructorRegistry::Instance(), G4PhysicsConstructorRegistry::IsKnownPhysicsConstructor(), n, and physicsExtensions.
Referenced by g4alt::G4PhysListFactory::PrintAvailablePhysLists().
void G4PhysListRegistry::SetUnknownFatal (G4int val) inline
Definition at line 94 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PhysListRegistry.hh
References unknownFatal.
Referenced by g4alt::G4PhysListFactory::SetUnknownFatal().
void G4PhysListRegistry::SetUserDefaultPhysList (const G4String & name = "")
Definition at line 104 of file G4PhysListRegistry.cc.
View newest version in sPHENIX GitHub at line 104 of file G4PhysListRegistry.cc
References systemDefault, and userDefault.
Referenced by G4PhysListRegistry(), and g4alt::G4PhysListFactory::SetDefaultReferencePhysList().
void G4PhysListRegistry::SetVerbose (G4int val) inline
Definition at line 91 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PhysListRegistry.hh
References verbose.
Referenced by g4alt::G4PhysListFactory::SetVerbose().
Member Data Documentation
std::vector<G4String> G4PhysListRegistry::availBasePhysLists mutable private
use this if user hasn't set userDefault or attempts to set the userDefault=""
Definition at line 124 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PhysListRegistry.hh
Referenced by AvailablePhysLists().
std::vector<G4String> G4PhysListRegistry::availExtensions mutable private
Definition at line 125 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PhysListRegistry.hh
Referenced by AvailablePhysicsExtensions().
std::map<G4String, G4VBasePhysListStamper*> G4PhysListRegistry::factories private
Definition at line 110 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 110 of file G4PhysListRegistry.hh
Referenced by AddFactory(), AvailablePhysLists(), and GetModularPhysicsList().
std::map<G4String, G4String> G4PhysListRegistry::physicsExtensions private
Definition at line 111 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 111 of file G4PhysListRegistry.hh
Referenced by AddPhysicsExtension(), AvailablePhysicsExtensions(), DeconstructPhysListName(), GetModularPhysicsList(), and PrintAvailablePhysLists().
G4String G4PhysListRegistry::systemDefault private
use this if $PHYSLIST isn't set
Definition at line 116 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PhysListRegistry.hh
Referenced by GetSystemDefaultPhysList(), and SetUserDefaultPhysList().
G4ThreadLocal G4PhysListRegistry * G4PhysListRegistry::theInstance = 0 static private
Definition at line 108 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PhysListRegistry.hh
Referenced by Instance().
G4int G4PhysListRegistry::unknownFatal private
Definition at line 114 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PhysListRegistry.hh
Referenced by GetModularPhysicsList(), GetUnknownFatal(), and SetUnknownFatal().
G4String G4PhysListRegistry::userDefault private
throw an exception if unsatisfiable?
Definition at line 115 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PhysListRegistry.hh
Referenced by GetModularPhysicsListFromEnv(), GetUserDefaultPhysList(), and SetUserDefaultPhysList().
G4int G4PhysListRegistry::verbose private
Definition at line 113 of file G4PhysListRegistry.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PhysListRegistry.hh
Referenced by GetModularPhysicsList(), GetVerbose(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/G4PhysListRegistry.hh
geant4/tree/geant4-10.6-release/source/physics_lists/lists/src/G4PhysListRegistry.cc