ECCE @ EIC Software: macros/blob/master/common/G4_HToF.C File Reference
G4_HToF.C File Reference
#include <GlobalVariables.C>
#include <fun4all/Fun4AllServer.h>
#include <g4etof/PHG4ECAPToFSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
Namespaces
namespace Enable
namespace HTOF
Macros
#define MACRO_G4HToF_C
Functions
void HTOFInit ()
void HTOFSetup (PHG4Reco *g4Reco)
void HTOF_Reco ()
Variables
bool Enable::HTOF = false
bool Enable::HTOF_GAS = false
bool Enable::HTOF_OVERLAPCHECK = true
int Enable::HTOF_VERBOSITY = 0
int HTOF::f_gas_lyr = 6.
int HTOF::f_mrpc_lyr = 7.
int HTOF::b_gas_lyr = 6.
int HTOF::b_mrpc_lyr = 7.
int HTOF::pcb_lyr = 3.
int HTOF::mylar_lyr = 4.
int HTOF::cu_lyr = 4.
int HTOF::carbon_lyr = 4.
int HTOF::honeycomb_lyr = 2.
double HTOF::z_start = 287.
double HTOF::R_in = 15.0
double HTOF::R_out = 170.
double HTOF::gas_gap = 0.0220
double HTOF::mrpc_thick = 0.04
double HTOF::pcb_thick = 0.06
double HTOF::cu_thick = 0.003
double HTOF::carbon_thick = 0.01
double HTOF::mylar_thick = 0.04
double HTOF::honeycomb_thick = 0.75
double HTOF::tof_width = (f_gas_lyr + b_gas_lyr) * gas_gap + (f_mrpc_lyr + b_mrpc_lyr) * mrpc_thick + carbon_lyr * carbon_thick + pcb_lyr * pcb_thick + cu_lyr * cu_thick + mylar_lyr * mylar_thick + honeycomb_lyr * honeycomb_thick
double HTOF::z_end = (z_start + tof_width)
Macro Definition Documentation
#define MACRO_G4HToF_C
Definition at line 2 of file G4_HToF.C.
View newest version in sPHENIX GitHub at line 2 of file G4_HToF.C
Function Documentation
void HTOF_Reco ()
Definition at line 116 of file G4_HToF.C.
View newest version in sPHENIX GitHub at line 116 of file G4_HToF.C
References Enable::HTOF_VERBOSITY, Fun4AllServer::instance(), max, and Enable::VERBOSITY.
void HTOFInit ()
Definition at line 52 of file G4_HToF.C.
View newest version in sPHENIX GitHub at line 52 of file G4_HToF.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, HTOF::R_out, HTOF::z_end, and HTOF::z_start.
Referenced by G4Init().
void HTOFSetup (PHG4Reco * g4Reco)
Definition at line 59 of file G4_HToF.C.
View newest version in sPHENIX GitHub at line 59 of file G4_HToF.C
References Enable::ABSORBER, PHG4TrackFastSim::add_zplane_state(), HTOF::b_gas_lyr, HTOF::carbon_thick, HTOF::cu_thick, HTOF::f_gas_lyr, TRACKING::FastKalmanFilter(), HTOF::gas_gap, HTOF::honeycomb_thick, Enable::HTOF_GAS, Enable::HTOF_OVERLAPCHECK, Enable::HTOF_VERBOSITY, Fun4AllServer::instance(), max, HTOF::mrpc_thick, HTOF::mylar_thick, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), HTOF::pcb_thick, TRACKING::ProjectionNames, HTOF::R_in, HTOF::R_out, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), HTOF::z_end, and HTOF::z_start.
Referenced by G4Setup().