ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_axes.cc File Reference
xDataTOM_axes.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_axes_initialize (statusMessageReporting *smr, xDataTOM_axes *axes, int numberOfAxes)
int xDataTOM_axes_release (xDataTOM_axes *axes)
char const * xDataTOM_axes_getLabel (statusMessageReporting *smr, xDataTOM_axes *axes, int index)
char const * xDataTOM_axes_getUnit (statusMessageReporting *smr, xDataTOM_axes *axes, int index)
int xDataTOM_axes_getInterpolation (statusMessageReporting *smr, xDataTOM_axes *axes, int index, enum xDataTOM_interpolationFlag *independent, enum xDataTOM_interpolationFlag *dependent, enum xDataTOM_interpolationQualifier *qualifier)
int xDataTOM_subAxes_initialize (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, enum xDataTOM_subAxesType type, int offset, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataTOM_subAxes_release (xDataTOM_subAxes *subAxes)
char const * xDataTOM_subAxes_getLabel (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, int index)
char const * xDataTOM_subAxes_getUnit (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, int index)
xDataTOM_axis * xDataTOM_axis_new (statusMessageReporting *smr, int index, char const *label, char const *unit, xDataTOM_interpolation *interpolation)
int xDataTOM_axis_initialize (statusMessageReporting *smr, xDataTOM_axis *axis, int index, char const *label, char const *unit, xDataTOM_interpolation *interpolation)
xDataTOM_axis * xDataTOM_axis_release (statusMessageReporting *, xDataTOM_axis *axis)
enum xDataTOM_frame xDataTOM_axis_stringToFrame (statusMessageReporting *, char const *frame)
char const * xDataTOM_axis_frameToString (statusMessageReporting *, enum xDataTOM_frame frame)
Variables
static char const * xDataTOM_frame_labString = "lab"
static char const * xDataTOM_frame_centerOfMassString = "centerOfMass"
static char const * xDataTOM_frame_invalidString = "invalid"
Function Documentation
int xDataTOM_axes_getInterpolation (statusMessageReporting * smr, xDataTOM_axes * axes, int index, enum xDataTOM_interpolationFlag * independent, enum xDataTOM_interpolationFlag * dependent, enum xDataTOM_interpolationQualifier * qualifier)
Definition at line 66 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 66 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_interpolation_s::dependent, xDataTOM_axis_s::interpolation, xDataTOM_axes_s::numberOfAxes, xDataTOM_interpolation_s::qualifier, smr_setReportError2, and xDataTOM_smrLibraryID.
Referenced by xDataTOME_getInterpolation().
char const* xDataTOM_axes_getLabel (statusMessageReporting * smr, xDataTOM_axes * axes, int index)
Definition at line 44 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axis_s::label, xDataTOM_axes_s::numberOfAxes, smr_setReportError2, and xDataTOM_smrLibraryID.
Referenced by xDataTOM_subAxes_getLabel(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsDataToTOM().
char const* xDataTOM_axes_getUnit (statusMessageReporting * smr, xDataTOM_axes * axes, int index)
Definition at line 55 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 55 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axes_s::numberOfAxes, smr_setReportError2, xDataTOM_axis_s::unit, and xDataTOM_smrLibraryID.
Referenced by MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), and xDataTOM_subAxes_getUnit().
int xDataTOM_axes_initialize (statusMessageReporting * smr, xDataTOM_axes * axes, int numberOfAxes)
Definition at line 21 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 21 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axes_s::numberOfAxes, and smr_malloc2.
Referenced by xDataXML_axesToTOM().
int xDataTOM_axes_release (xDataTOM_axes * axes)
Definition at line 31 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 31 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axes_s::numberOfAxes, smr_freeMemory(), and xDataTOM_axis_release().
Referenced by xDataTOM_releaseElement().
char const* xDataTOM_axis_frameToString (statusMessageReporting * , enum xDataTOM_frame frame)
Definition at line 191 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 191 of file xDataTOM_axes.cc
References xDataTOM_frame_centerOfMass, xDataTOM_frame_centerOfMassString, xDataTOM_frame_invalidString, xDataTOM_frame_lab, and xDataTOM_frame_labString.
int xDataTOM_axis_initialize (statusMessageReporting * smr, xDataTOM_axis * axis, int index, char const * label, char const * unit, xDataTOM_interpolation * interpolation)
Definition at line 155 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 155 of file xDataTOM_axes.cc
References check_license::err(), xDataTOM_axis_s::index, xDataTOM_axis_s::interpolation, xDataTOM_axis_s::label, smr_allocateCopyString2, smr_freeMemory(), xDataTOM_axis_s::unit, and xDataTOM_interpolation_copy().
Referenced by xDataTOM_axis_new(), and xDataXML_axesToTOM().
xDataTOM_axis* xDataTOM_axis_new (statusMessageReporting * smr, int index, char const * label, char const * unit, xDataTOM_interpolation * interpolation)
Definition at line 144 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 144 of file xDataTOM_axes.cc
References smr_freeMemory(), smr_malloc2, and xDataTOM_axis_initialize().
xDataTOM_axis* xDataTOM_axis_release (statusMessageReporting * , xDataTOM_axis * axis)
Definition at line 172 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 172 of file xDataTOM_axes.cc
References xDataTOM_axis_s::index, xDataTOM_axis_s::label, smr_freeMemory(), and xDataTOM_axis_s::unit.
Referenced by xDataTOM_axes_release(), and xDataXML_axesToTOM().
enum xDataTOM_frame xDataTOM_axis_stringToFrame (statusMessageReporting * , char const * frame)
Definition at line 182 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 182 of file xDataTOM_axes.cc
References xDataTOM_frame_centerOfMass, xDataTOM_frame_invalid, and xDataTOM_frame_lab.
Referenced by MCGIDI_misc_getProductFrame().
char const* xDataTOM_subAxes_getLabel (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, int index)
Definition at line 126 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 126 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes, xDataTOM_subAxes_s::offset, and xDataTOM_axes_getLabel().
char const* xDataTOM_subAxes_getUnit (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, int index)
Definition at line 133 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 133 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes, xDataTOM_subAxes_s::offset, and xDataTOM_axes_getUnit().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf().
int xDataTOM_subAxes_initialize (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, enum xDataTOM_subAxesType type, int offset, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 89 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 89 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes, xDataTOM_subAxes_s::interpolation, xDataTOM_axes_s::numberOfAxes, offset, xDataTOM_subAxes_s::offset, smr_setReportError2, smr_setReportError2p, xDataTOM_subAxes_s::type, xDataTOM_interpolation_copy(), xDataTOM_interpolation_set(), xDataTOM_interpolationFlag_linear, xDataTOM_interpolationQualifier_none, xDataTOM_smrLibraryID, and xDataTOM_subAxesType_intepolationAxes.
Referenced by xDataTOM_KalbachMann_initialize(), xDataTOM_polynomial_initialize(), xDataTOM_V_W_XYs_initialize(), xDataTOM_V_W_XYs_LegendreSeries_initialize(), xDataTOM_W_XYs_initialize(), xDataTOM_W_XYs_LegendreSeries_initialize(), and xDataXML_XYsDataToTOM().
int xDataTOM_subAxes_release (xDataTOM_subAxes * subAxes)
Definition at line 118 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 118 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes.
Referenced by xDataTOM_KalbachMann_release(), xDataTOM_polynomial_release(), xDataTOM_W_XYs_release(), and xDataTOM_XYs_release().
Variable Documentation
char const* xDataTOM_frame_centerOfMassString = "centerOfMass" static
Definition at line 16 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 16 of file xDataTOM_axes.cc
Referenced by xDataTOM_axis_frameToString().
char const* xDataTOM_frame_invalidString = "invalid" static
Definition at line 17 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 17 of file xDataTOM_axes.cc
Referenced by xDataTOM_axis_frameToString().
char const* xDataTOM_frame_labString = "lab" static
Definition at line 15 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 15 of file xDataTOM_axes.cc
Referenced by xDataTOM_axis_frameToString().