ECCE @ EIC Software: G4BaryonSplitter Class Reference
G4BaryonSplitter Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4BaryonSplitter.hh>
Public Member Functions
G4BaryonSplitter ()
G4bool SplitBarion (G4int PDGCode, G4int *q_or_qqbar, G4int *qbar_or_qq)
G4bool FindDiquark (G4int PDGCode, G4int Quark, G4int *Diquark)
const G4SPBaryon & GetSPBaryon (G4int PDGCode)
Private Attributes
G4SPBaryonTable theBaryons
Detailed Description
Definition at line 36 of file G4BaryonSplitter.hh.
View newest version in sPHENIX GitHub at line 36 of file G4BaryonSplitter.hh
Constructor & Destructor Documentation
G4BaryonSplitter::G4BaryonSplitter ()
Definition at line 34 of file G4BaryonSplitter.cc.
View newest version in sPHENIX GitHub at line 34 of file G4BaryonSplitter.cc
References G4AntiLambda::AntiLambda(), G4AntiNeutron::AntiNeutron(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiSigmaZero::AntiSigmaZero(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), G4ParticleTable::GetParticleTable(), G4SPBaryonTable::insert(), G4Lambda::Lambda(), G4Neutron::Neutron(), G4OmegaMinus::OmegaMinus(), G4Proton::Proton(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), theBaryons, G4XiMinus::XiMinus(), and G4XiZero::XiZero().
Member Function Documentation
G4bool G4BaryonSplitter::FindDiquark (G4int PDGCode, G4int Quark, G4int * Diquark)
Definition at line 89 of file G4BaryonSplitter.cc.
View newest version in sPHENIX GitHub at line 89 of file G4BaryonSplitter.cc
References G4SPBaryon::FindDiquark(), G4SPBaryonTable::GetBaryon(), G4ParticleTable::GetParticleTable(), and theBaryons.
const G4SPBaryon & G4BaryonSplitter::GetSPBaryon (G4int PDGCode)
Definition at line 81 of file G4BaryonSplitter.cc.
View newest version in sPHENIX GitHub at line 81 of file G4BaryonSplitter.cc
References G4SPBaryonTable::GetBaryon(), G4ParticleTable::GetParticleTable(), and theBaryons.
G4bool G4BaryonSplitter::SplitBarion (G4int PDGCode, G4int * q_or_qqbar, G4int * qbar_or_qq)
Definition at line 65 of file G4BaryonSplitter.cc.
View newest version in sPHENIX GitHub at line 65 of file G4BaryonSplitter.cc
References FALSE, G4SPBaryonTable::GetBaryon(), G4ParticleTable::GetParticleTable(), G4SPBaryon::SampleQuarkAndDiquark(), theBaryons, and TRUE.
Referenced by G4QGSMSplitableHadron::GetValenceQuarkFlavors().
Member Data Documentation
G4SPBaryonTable G4BaryonSplitter::theBaryons private
Definition at line 45 of file G4BaryonSplitter.hh.
View newest version in sPHENIX GitHub at line 45 of file G4BaryonSplitter.hh
Referenced by FindDiquark(), G4BaryonSplitter(), GetSPBaryon(), and SplitBarion().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4BaryonSplitter.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4BaryonSplitter.cc