ECCE @ EIC Software: G4UserPhysicsListMessenger Class Reference
G4UserPhysicsListMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4UserPhysicsListMessenger.hh>
Public Member Functions
G4UserPhysicsListMessenger (G4VUserPhysicsList *pParticleList)
virtual ~G4UserPhysicsListMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
virtual G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Attributes
G4VUserPhysicsList * thePhysicsList
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Private Member Functions
G4UserPhysicsListMessenger ()
Private Attributes
G4UIdirectory * theDirectory
G4UIcmdWithADoubleAndUnit * setCutCmd
G4UIcommand * setCutRCmd
G4UIcommand * setCutForAGivenParticleCmd
G4UIcmdWithAString * getCutForAGivenParticleCmd
G4UIcmdWithAnInteger * verboseCmd
G4UIcmdWithoutParameter * dumpListCmd
G4UIcmdWithAString * addProcManCmd
G4UIcmdWithAString * buildPTCmd
G4UIcmdWithAString * storeCmd
G4UIcmdWithAString * retrieveCmd
G4UIcmdWithAnInteger * asciiCmd
G4UIcommand * applyCutsCmd
G4UIcmdWithAString * dumpCutValuesCmd
G4UIcmdWithAnInteger * dumpOrdParamCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Detailed Description
Definition at line 77 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4UserPhysicsListMessenger.hh
Constructor & Destructor Documentation
G4UserPhysicsListMessenger::G4UserPhysicsListMessenger () inline private
Definition at line 81 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4UserPhysicsListMessenger.hh
G4UserPhysicsListMessenger::G4UserPhysicsListMessenger (G4VUserPhysicsList * pParticleList)
Definition at line 57 of file G4UserPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UserPhysicsListMessenger.cc
References addProcManCmd, applyCutsCmd, asciiCmd, G4UIcommand::AvailableForStates(), buildPTCmd, G4UIcommand::CategoryOf(), dumpCutValuesCmd, dumpListCmd, dumpOrdParamCmd, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_Init, G4State_PreInit, getCutForAGivenParticleCmd, retrieveCmd, G4UIcmdWithAString::SetCandidates(), setCutCmd, setCutForAGivenParticleCmd, setCutRCmd, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIparameter::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIparameter::SetParameterRange(), G4UIcommand::SetRange(), G4UIcommand::SetToBeBroadcasted(), storeCmd, theDirectory, G4UIcommand::UnitsList(), and verboseCmd.
G4UserPhysicsListMessenger::~G4UserPhysicsListMessenger () virtual
Definition at line 209 of file G4UserPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 209 of file G4UserPhysicsListMessenger.cc
References addProcManCmd, applyCutsCmd, asciiCmd, buildPTCmd, dumpCutValuesCmd, dumpListCmd, dumpOrdParamCmd, getCutForAGivenParticleCmd, retrieveCmd, setCutCmd, setCutForAGivenParticleCmd, setCutRCmd, storeCmd, theDirectory, and verboseCmd.
Member Function Documentation
G4String G4UserPhysicsListMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 330 of file G4UserPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 330 of file G4UserPhysicsListMessenger.cc
References addProcManCmd, asciiCmd, buildPTCmd, G4UIcommand::ConvertToString(), G4VUserPhysicsList::GetDefaultCutValue(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4VUserPhysicsList::GetPhysicsTableDirectory(), G4VUserPhysicsList::GetVerboseLevel(), G4VUserPhysicsList::IsPhysicsTableRetrieved(), G4VUserPhysicsList::IsStoredInAscii(), particle, retrieveCmd, G4UIcmdWithAString::SetCandidates(), setCutCmd, storeCmd, thePhysicsList, G4ParticleTableIterator< K, V >::value(), and verboseCmd.
void G4UserPhysicsListMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 228 of file G4UserPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 228 of file G4UserPhysicsListMessenger.cc
References G4VUserPhysicsList::AddProcessManager(), addProcManCmd, applyCutsCmd, asciiCmd, G4VUserPhysicsList::BuildPhysicsTable(), buildPTCmd, G4UIcommand::CommandFailed(), dumpCutValuesCmd, G4VUserPhysicsList::DumpCutValuesTable(), G4VUserPhysicsList::DumpList(), dumpListCmd, G4PhysicsListHelper::DumpOrdingParameterTable(), dumpOrdParamCmd, G4cout, G4endl, getCutForAGivenParticleCmd, G4VUserPhysicsList::GetCutValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ParticleTable::GetParticleTable(), G4PhysicsListHelper::GetPhysicsListHelper(), G4ParticleDefinition::GetProcessManager(), mm, particle, G4VUserPhysicsList::PreparePhysicsTable(), G4VUserPhysicsList::ResetPhysicsTableRetrieved(), G4VUserPhysicsList::ResetStoredInAscii(), retrieveCmd, G4VUserPhysicsList::SetApplyCuts(), setCutCmd, setCutForAGivenParticleCmd, setCutRCmd, G4VUserPhysicsList::SetCuts(), G4VUserPhysicsList::SetCutsForRegion(), G4VUserPhysicsList::SetCutValue(), G4VUserPhysicsList::SetDefaultCutValue(), G4VUserPhysicsList::SetPhysicsTableRetrieved(), G4VUserPhysicsList::SetStoredInAscii(), G4VUserPhysicsList::SetVerboseLevel(), storeCmd, G4VUserPhysicsList::StorePhysicsTable(), thePhysicsList, G4UIcommand::ValueOf(), and verboseCmd.
Member Data Documentation
G4UIcmdWithAString* G4UserPhysicsListMessenger::addProcManCmd private
Definition at line 102 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 102 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcommand* G4UserPhysicsListMessenger::applyCutsCmd private
Definition at line 107 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 107 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAnInteger* G4UserPhysicsListMessenger::asciiCmd private
Definition at line 106 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 106 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAString* G4UserPhysicsListMessenger::buildPTCmd private
Definition at line 103 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 103 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAString* G4UserPhysicsListMessenger::dumpCutValuesCmd private
Definition at line 108 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 108 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithoutParameter* G4UserPhysicsListMessenger::dumpListCmd private
Definition at line 101 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 101 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAnInteger* G4UserPhysicsListMessenger::dumpOrdParamCmd private
Definition at line 109 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 109 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAString* G4UserPhysicsListMessenger::getCutForAGivenParticleCmd private
Definition at line 99 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 99 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAString* G4UserPhysicsListMessenger::retrieveCmd private
Definition at line 105 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 105 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithADoubleAndUnit* G4UserPhysicsListMessenger::setCutCmd private
Definition at line 96 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcommand* G4UserPhysicsListMessenger::setCutForAGivenParticleCmd private
Definition at line 98 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 98 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcommand* G4UserPhysicsListMessenger::setCutRCmd private
Definition at line 97 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 97 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIcmdWithAString* G4UserPhysicsListMessenger::storeCmd private
Definition at line 104 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 104 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
G4UIdirectory* G4UserPhysicsListMessenger::theDirectory private
Definition at line 95 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 95 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), and ~G4UserPhysicsListMessenger().
G4VUserPhysicsList* G4UserPhysicsListMessenger::thePhysicsList protected
Definition at line 92 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4UserPhysicsListMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIcmdWithAnInteger* G4UserPhysicsListMessenger::verboseCmd private
Definition at line 100 of file G4UserPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 100 of file G4UserPhysicsListMessenger.hh
Referenced by G4UserPhysicsListMessenger(), GetCurrentValue(), SetNewValue(), and ~G4UserPhysicsListMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4UserPhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/source/run/src/G4UserPhysicsListMessenger.cc