ECCE @ EIC Software: G4LENDModel Class Reference
G4LENDModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDModel.hh>
Public Member Functions
G4LENDModel (G4String name="LENDModel")
~G4LENDModel ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
void ChangeDefaultEvaluation (G4String name)
void AllowNaturalAbundanceTarget ()
void AllowAnyCandidateTarget ()
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpLENDTargetInfo (G4bool force=false)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void InitialiseModel ()
Protected Member Functions
void create_used_target_map ()
void recreate_used_target_map ()
G4GIDI_target * get_target_from_map (G4int nuclear_code)
G4HadFinalState * returnUnchanged (const G4HadProjectile &aTrack, G4HadFinalState *theResult)
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes
G4ParticleDefinition * proj
G4LENDManager * lend_manager
std::map< G4int,
G4LENDUsedTarget * > usedTarget_map
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Private Attributes
G4String default_evaluation
G4bool allow_nat
G4bool allow_any
Detailed Description
Definition at line 51 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 51 of file G4LENDModel.hh
Constructor & Destructor Documentation
G4LENDModel::G4LENDModel (G4String name = "LENDModel")
Definition at line 47 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4LENDModel.cc
References allow_any, allow_nat, default_evaluation, eV, G4LENDManager::GetInstance(), lend_manager, MeV, proj, G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4LENDModel::~G4LENDModel ()
Definition at line 67 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 67 of file G4LENDModel.cc
References it, and usedTarget_map.
Member Function Documentation
void G4LENDModel::AllowAnyCandidateTarget () inline
Definition at line 64 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4LENDModel.hh
References allow_any, and recreate_used_target_map().
void G4LENDModel::AllowNaturalAbundanceTarget () inline
Definition at line 63 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LENDModel.hh
References allow_nat, and recreate_used_target_map().
Referenced by G4NeutronLENDBuilder::Build(), and G4HadronElasticPhysicsLEND::ConstructProcess().
G4HadFinalState * G4LENDModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Implements G4HadronicInteraction.
Reimplemented in G4LENDInelastic, G4LENDFission, G4LENDCapture, G4LENDElastic, G4LENDGammaModel, G4LENDCombinedModel, and G4LENDorBERTModel.
Definition at line 158 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 158 of file G4LENDModel.cc
References G4HadFinalState::AddSecondary(), G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4GIDI_target::getElasticFinalState(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4Nucleus::GetIsotope(), G4HadProjectile::GetKineticEnergy(), G4Isotope::Getm(), G4ReactionProduct::GetMass(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4LENDManager::GetNucleusEncoding(), G4ParticleDefinition::GetPDGMass(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), source.hepunit::k_Boltzmann, lend_manager, G4ReactionProduct::Lorentz(), mass, MeV, CLHEP::Hep3Vector::phi(), phi, second, G4DynamicParticle::SetDefinition(), G4HadFinalState::SetEnergyChange(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetMomentumChange(), G4ReactionProduct::SetTotalEnergy(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4INCL::DeJongSpin::shoot(), CLHEP::Hep3Vector::theta(), theta(), theTarget, tP, twopi, usedTarget_map, v, and CLHEP::HepLorentzVector::vect().
Referenced by G4LENDCombinedModel::ApplyYourself(), and G4LENDGammaModel::ApplyYourself().
void G4LENDModel::BuildPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4HadronicInteraction.
Definition at line 66 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LENDModel.hh
References recreate_used_target_map().
void G4LENDModel::ChangeDefaultEvaluation (G4String name) inline
Definition at line 62 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4LENDModel.hh
References default_evaluation, and recreate_used_target_map().
Referenced by G4NeutronLENDBuilder::Build(), and G4HadronElasticPhysicsLEND::ConstructProcess().
void G4LENDModel::create_used_target_map () protected
Definition at line 93 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 93 of file G4LENDModel.cc
References allow_any, allow_nat, G4LENDUsedTarget::AllowAny(), G4LENDUsedTarget::AllowNat(), default_evaluation, DumpLENDTargetInfo(), G4Element::GetElementTable(), G4Element::GetIsotope(), G4NistElementBuilder::GetIsotopeAbundance(), G4Isotope::Getm(), G4Isotope::GetN(), G4LENDManager::GetNistElementBuilder(), G4NistElementBuilder::GetNistFirstIsotopeN(), G4LENDManager::GetNucleusEncoding(), G4Element::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4NistElementBuilder::GetNumberOfNistIsotopes(), G4Isotope::GetZ(), G4Element::GetZ(), int(), lend_manager, proj, G4LENDManager::RequestChangeOfVerboseLevel(), usedTarget_map, and G4HadronicInteraction::verboseLevel.
Referenced by G4LENDorBERTModel::BuildPhysicsTable(), G4LENDCombinedModel::BuildPhysicsTable(), G4LENDGammaModel::BuildPhysicsTable(), DumpLENDTargetInfo(), G4LENDCapture::G4LENDCapture(), G4LENDElastic::G4LENDElastic(), G4LENDFission::G4LENDFission(), G4LENDInelastic::G4LENDInelastic(), and recreate_used_target_map().
void G4LENDModel::DumpLENDTargetInfo (G4bool force = false)
Definition at line 275 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 275 of file G4LENDModel.cc
References create_used_target_map(), G4cout, G4endl, G4HadronicInteraction::GetModelName(), G4ParticleDefinition::GetParticleName(), G4LENDManager::GetVerboseLevel(), it, lend_manager, proj, and usedTarget_map.
Referenced by G4LENDBertiniGammaElectroNuclearBuilder::Build(), G4EmExtraPhysics::ConstructLENDGammaNuclear(), G4HadronElasticPhysicsLEND::ConstructProcess(), and create_used_target_map().
G4GIDI_target * G4LENDModel::get_target_from_map (G4int nuclear_code) protected
Definition at line 267 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 267 of file G4LENDModel.cc
References usedTarget_map.
Referenced by G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LENDCombinedModel::HasData(), and G4LENDGammaModel::HasData().
void G4LENDModel::recreate_used_target_map () protected
Definition at line 77 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 77 of file G4LENDModel.cc
References create_used_target_map(), it, and usedTarget_map.
Referenced by AllowAnyCandidateTarget(), AllowNaturalAbundanceTarget(), BuildPhysicsTable(), and ChangeDefaultEvaluation().
G4HadFinalState * G4LENDModel::returnUnchanged (const G4HadProjectile & aTrack, G4HadFinalState * theResult) protected
Definition at line 253 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 253 of file G4LENDModel.cc
References G4Exception(), G4HadProjectile::Get4Momentum(), G4HadProjectile::GetKineticEnergy(), G4HadronicInteraction::GetModelName(), CLHEP::HepLorentzVector::getV(), G4LENDManager::GetVerboseLevel(), JustWarning, lend_manager, message(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetMomentumChange(), and CLHEP::Hep3Vector::unit().
Referenced by G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), and G4LENDFission::ApplyYourself().
Member Data Documentation
G4bool G4LENDModel::allow_any private
Definition at line 73 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4LENDModel.hh
Referenced by AllowAnyCandidateTarget(), create_used_target_map(), and G4LENDModel().
G4bool G4LENDModel::allow_nat private
Definition at line 72 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LENDModel.hh
Referenced by AllowNaturalAbundanceTarget(), create_used_target_map(), and G4LENDModel().
G4String G4LENDModel::default_evaluation private
Definition at line 71 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4LENDModel.hh
Referenced by ChangeDefaultEvaluation(), create_used_target_map(), and G4LENDModel().
G4LENDManager* G4LENDModel::lend_manager protected
Definition at line 84 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4LENDModel.hh
Referenced by ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), create_used_target_map(), DumpLENDTargetInfo(), G4LENDModel(), G4LENDCombinedModel::HasData(), G4LENDGammaModel::HasData(), and returnUnchanged().
G4ParticleDefinition* G4LENDModel::proj protected
Definition at line 83 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LENDModel.hh
Referenced by G4LENDCombinedModel::ApplyYourself(), G4LENDGammaModel::ApplyYourself(), create_used_target_map(), DumpLENDTargetInfo(), G4LENDCapture::G4LENDCapture(), G4LENDCombinedModel::G4LENDCombinedModel(), G4LENDElastic::G4LENDElastic(), G4LENDFission::G4LENDFission(), G4LENDGammaModel::G4LENDGammaModel(), G4LENDInelastic::G4LENDInelastic(), G4LENDModel(), and G4LENDorBERTModel::G4LENDorBERTModel().
std::map< G4int , G4LENDUsedTarget* > G4LENDModel::usedTarget_map protected
Definition at line 85 of file G4LENDModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4LENDModel.hh
Referenced by ApplyYourself(), create_used_target_map(), DumpLENDTargetInfo(), get_target_from_map(), recreate_used_target_map(), and ~G4LENDModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDModel.cc