ECCE @ EIC Software: CexmcTrackingAction Class Reference
CexmcTrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackingAction.hh>
Public Member Functions
CexmcTrackingAction (CexmcPhysicsManager *physicsManager)
void PreUserTrackingAction (const G4Track *track)
void BeginOfEventAction (void)
Public Member Functions inherited from G4UserTrackingAction
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
virtual void PostUserTrackingAction (const G4Track *)
Private Member Functions
void ResetOutputParticleTrackId (void)
void ResetOutputParticleDecayProductCopyNumber (void)
void SetupIncidentParticleTrackInfo (const G4Track *track)
Private Attributes
CexmcPhysicsManager * physicsManager
const G4LogicalVolume * targetVolume
G4int outputParticleTrackId
G4int outputParticleDecayProductCopyNumber
G4ParticleDefinition * incidentParticle
G4ParticleDefinition * outputParticle
G4ParticleDefinition * nucleusOutputParticle
Additional Inherited Members
Protected Attributes inherited from G4UserTrackingAction
G4TrackingManager * fpTrackingManager
Detailed Description
Definition at line 56 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcTrackingAction.hh
Constructor & Destructor Documentation
CexmcTrackingAction::CexmcTrackingAction (CexmcPhysicsManager * physicsManager) explicit
Definition at line 58 of file CexmcTrackingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file CexmcTrackingAction.cc
References CexmcIncompleteProductionModel, CexmcWeirdException, CexmcPhysicsManager::GetProductionModel(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), CexmcSetup::GetVolume(), incidentParticle, nucleusOutputParticle, outputParticle, physicsManager, CexmcSetup::Target, and targetVolume.
Member Function Documentation
void CexmcTrackingAction::BeginOfEventAction (void) inline
Definition at line 104 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 104 of file CexmcTrackingAction.hh
References ResetOutputParticleDecayProductCopyNumber(), and ResetOutputParticleTrackId().
Referenced by CexmcEventAction::BeginOfEventAction().
void CexmcTrackingAction::PreUserTrackingAction (const G4Track * track) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 84 of file CexmcTrackingAction.cc.
View newest version in sPHENIX GitHub at line 84 of file CexmcTrackingAction.cc
References CexmcBeamParticleTrack, CexmcInsipidTrack, CexmcNucleusParticleTrack, CexmcOutputParticleDecayProductTrack, CexmcOutputParticleTrack, CexmcStudiedProcessFullName(), G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetParentID(), G4VProcess::GetProcessName(), G4Track::GetTrackID(), G4Track::GetUserInformation(), incidentParticle, nucleusOutputParticle, CexmcPhysicsManager::OnlyBeamParticleCanTriggerStudiedProcess(), outputParticle, outputParticleDecayProductCopyNumber, outputParticleTrackId, physicsManager, SetupIncidentParticleTrackInfo(), and G4Track::SetUserInformation().
void CexmcTrackingAction::ResetOutputParticleDecayProductCopyNumber (void) inline private
Definition at line 97 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 97 of file CexmcTrackingAction.hh
References outputParticleDecayProductCopyNumber.
Referenced by BeginOfEventAction().
void CexmcTrackingAction::ResetOutputParticleTrackId (void) inline private
Definition at line 91 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 91 of file CexmcTrackingAction.hh
References CexmcInvalidTrackId(), and outputParticleTrackId.
Referenced by BeginOfEventAction().
void CexmcTrackingAction::SetupIncidentParticleTrackInfo (const G4Track * track) private
Definition at line 159 of file CexmcTrackingAction.cc.
View newest version in sPHENIX GitHub at line 159 of file CexmcTrackingAction.cc
References CexmcIncidentParticleTrackInfo::ActivateStudiedProcess(), G4Track::GetUserInformation(), G4Track::GetVolume(), physicsManager, CexmcPhysicsManager::ResampleTrackLengthInTarget(), targetVolume, and Acts::Test::volume.
Referenced by PreUserTrackingAction().
Member Data Documentation
G4ParticleDefinition* CexmcTrackingAction::incidentParticle private
Definition at line 83 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 83 of file CexmcTrackingAction.hh
Referenced by CexmcTrackingAction(), and PreUserTrackingAction().
G4ParticleDefinition* CexmcTrackingAction::nucleusOutputParticle private
Definition at line 87 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 87 of file CexmcTrackingAction.hh
Referenced by CexmcTrackingAction(), and PreUserTrackingAction().
G4ParticleDefinition* CexmcTrackingAction::outputParticle private
Definition at line 85 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcTrackingAction.hh
Referenced by CexmcTrackingAction(), and PreUserTrackingAction().
G4int CexmcTrackingAction::outputParticleDecayProductCopyNumber private
Definition at line 80 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 80 of file CexmcTrackingAction.hh
Referenced by PreUserTrackingAction(), and ResetOutputParticleDecayProductCopyNumber().
G4int CexmcTrackingAction::outputParticleTrackId private
Definition at line 78 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 78 of file CexmcTrackingAction.hh
Referenced by PreUserTrackingAction(), and ResetOutputParticleTrackId().
CexmcPhysicsManager* CexmcTrackingAction::physicsManager private
Definition at line 74 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 74 of file CexmcTrackingAction.hh
Referenced by CexmcTrackingAction(), PreUserTrackingAction(), and SetupIncidentParticleTrackInfo().
const G4LogicalVolume* CexmcTrackingAction::targetVolume private
Definition at line 76 of file CexmcTrackingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcTrackingAction.hh
Referenced by CexmcTrackingAction(), and SetupIncidentParticleTrackInfo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcTrackingAction.cc