ECCE @ EIC Software: G4SDStructure Class Reference
G4SDStructure Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4SDStructure.hh>
Public Member Functions
G4SDStructure (const G4String &aPath)
~G4SDStructure ()
G4bool operator== (const G4SDStructure &right) const
void AddNewDetector (G4VSensitiveDetector *aSD, const G4String &treeStructure)
void Activate (const G4String &aName, G4bool sensitiveFlag)
void Initialize (G4HCofThisEvent *HCE)
void Terminate (G4HCofThisEvent *HCE)
G4VSensitiveDetector * FindSensitiveDetector (const G4String &aName, G4bool warning=true)
G4VSensitiveDetector * GetSD (const G4String &aName)
void ListTree ()
void SetVerboseLevel (G4int vl)
Private Member Functions
G4SDStructure * FindSubDirectory (const G4String &subD)
G4String ExtractDirName (const G4String &aPath)
void RemoveSD (G4VSensitiveDetector *)
Private Attributes
std::vector< G4SDStructure * > structure
std::vector
< G4VSensitiveDetector * > detector
G4String pathName
G4String dirName
G4int verboseLevel
Detailed Description
Definition at line 46 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 46 of file G4SDStructure.hh
Constructor & Destructor Documentation
G4SDStructure::G4SDStructure (const G4String & aPath)
Definition at line 33 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 33 of file G4SDStructure.cc
References dirName, G4String::last(), pathName, and G4String::remove().
Referenced by AddNewDetector().
G4SDStructure::~G4SDStructure ()
Definition at line 47 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 47 of file G4SDStructure.cc
References detector, and structure.
Member Function Documentation
void G4SDStructure::Activate (const G4String & aName, G4bool sensitiveFlag)
Definition at line 126 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 126 of file G4SDStructure.cc
References Activate(), G4VSensitiveDetector::Activate(), detector, ExtractDirName(), FindSubDirectory(), G4String::first(), G4cout, G4endl, GetSD(), G4String::isNull(), pathName, G4String::remove(), and structure.
Referenced by Activate(), and G4SDManager::Activate().
void G4SDStructure::AddNewDetector (G4VSensitiveDetector * aSD, const G4String & treeStructure)
Definition at line 60 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 60 of file G4SDStructure.cc
References AddNewDetector(), detector, ExtractDirName(), FindSubDirectory(), G4Exception(), G4SDStructure(), G4VSensitiveDetector::GetName(), GetSD(), G4String::isNull(), JustWarning, pathName, G4String::prepend(), G4String::remove(), RemoveSD(), and structure.
Referenced by AddNewDetector(), and G4SDManager::AddNewDetector().
G4String G4SDStructure::ExtractDirName (const G4String & aPath) private
Definition at line 118 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 118 of file G4SDStructure.cc
References G4String::first(), and G4String::remove().
Referenced by Activate(), AddNewDetector(), and FindSensitiveDetector().
G4VSensitiveDetector * G4SDStructure::FindSensitiveDetector (const G4String & aName, G4bool warning = true)
Definition at line 162 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 162 of file G4SDStructure.cc
References ExtractDirName(), FindSensitiveDetector(), FindSubDirectory(), G4String::first(), G4cout, G4endl, GetSD(), pathName, and G4String::remove().
Referenced by FindSensitiveDetector(), and G4SDManager::FindSensitiveDetector().
G4SDStructure * G4SDStructure::FindSubDirectory (const G4String & subD) private
Definition at line 98 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 98 of file G4SDStructure.cc
References structure.
Referenced by Activate(), AddNewDetector(), and FindSensitiveDetector().
G4VSensitiveDetector * G4SDStructure::GetSD (const G4String & aName)
Definition at line 105 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 105 of file G4SDStructure.cc
References detector.
Referenced by Activate(), AddNewDetector(), and FindSensitiveDetector().
void G4SDStructure::Initialize (G4HCofThisEvent * HCE)
Definition at line 193 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 193 of file G4SDStructure.cc
References detector, and structure.
Referenced by G4SDManager::PrepareNewEvent().
void G4SDStructure::ListTree ()
Definition at line 213 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 213 of file G4SDStructure.cc
References detector, G4cout, G4endl, pathName, and structure.
Referenced by G4SDManager::ListTree().
G4bool G4SDStructure::operator== (const G4SDStructure & right) const
Definition at line 55 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SDStructure.cc
void G4SDStructure::RemoveSD (G4VSensitiveDetector * sd) private
Definition at line 112 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 112 of file G4SDStructure.cc
References detector.
Referenced by AddNewDetector().
void G4SDStructure::SetVerboseLevel (G4int vl) inline
Definition at line 75 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 75 of file G4SDStructure.hh
References detector, structure, and verboseLevel.
Referenced by G4SDManager::SetVerboseLevel().
void G4SDStructure::Terminate (G4HCofThisEvent * HCE)
Definition at line 203 of file G4SDStructure.cc.
View newest version in sPHENIX GitHub at line 203 of file G4SDStructure.cc
References detector, and structure.
Referenced by G4SDManager::TerminateCurrentEvent().
Member Data Documentation
std::vector<G4VSensitiveDetector*> G4SDStructure::detector private
Definition at line 69 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 69 of file G4SDStructure.hh
Referenced by Activate(), AddNewDetector(), GetSD(), Initialize(), ListTree(), RemoveSD(), SetVerboseLevel(), Terminate(), and ~G4SDStructure().
G4String G4SDStructure::dirName private
Definition at line 71 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 71 of file G4SDStructure.hh
Referenced by G4SDStructure().
G4String G4SDStructure::pathName private
Definition at line 70 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 70 of file G4SDStructure.hh
Referenced by Activate(), AddNewDetector(), FindSensitiveDetector(), G4SDStructure(), and ListTree().
std::vector<G4SDStructure*> G4SDStructure::structure private
Definition at line 68 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 68 of file G4SDStructure.hh
Referenced by Activate(), AddNewDetector(), FindSubDirectory(), Initialize(), ListTree(), SetVerboseLevel(), Terminate(), and ~G4SDStructure().
G4int G4SDStructure::verboseLevel private
Definition at line 72 of file G4SDStructure.hh.
View newest version in sPHENIX GitHub at line 72 of file G4SDStructure.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4SDStructure.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4SDStructure.cc