ECCE @ EIC Software: G4HadFinalState Class Reference
G4HadFinalState Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadFinalState.hh>
Public Member Functions
G4HadFinalState ()
G4int GetNumberOfSecondaries () const
void SetEnergyChange (G4double anEnergy)
G4double GetEnergyChange () const
void SetMomentumChange (const G4ThreeVector &aV)
void SetMomentumChange (G4double x, G4double y, G4double z)
const G4ThreeVector & GetMomentumChange () const
void AddSecondary (G4DynamicParticle *aP, G4int mod=-1)
void AddSecondary (const G4HadSecondary &aHS)
void SetStatusChange (G4HadFinalStateStatus aS)
G4HadFinalStateStatus GetStatusChange () const
void Clear ()
const G4LorentzRotation & GetTrafoToLab () const
void SetTrafoToLab (const G4LorentzRotation &aT)
void SetWeightChange (G4double aW)
G4double GetWeightChange () const
G4HadSecondary * GetSecondary (size_t i)
const G4HadSecondary * GetSecondary (size_t i) const
void SetLocalEnergyDeposit (G4double aE)
G4double GetLocalEnergyDeposit () const
void ClearSecondaries ()
void AddSecondaries (const std::vector< G4HadSecondary > &addSecs)
void AddSecondaries (const G4HadFinalState &addHFS)
void AddSecondaries (const G4HadFinalState *addHFS)
Private Attributes
G4ThreeVector theDirection
G4double theEnergy
std::vector< G4HadSecondary > theSecs
G4HadFinalStateStatus theStat
G4LorentzRotation theT
G4double theW
G4double theEDep
Detailed Description
Definition at line 45 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 45 of file G4HadFinalState.hh
Constructor & Destructor Documentation
G4HadFinalState::G4HadFinalState ()
Definition at line 35 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 35 of file G4HadFinalState.cc
Member Function Documentation
void G4HadFinalState::AddSecondaries (const std::vector< G4HadSecondary > & addSecs)
Definition at line 62 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 62 of file G4HadFinalState.cc
References theSecs.
Referenced by AddSecondaries(), G4HadronStoppingProcess::AtRestDoIt(), G4HadLeadBias::Bias(), G4MuonVDNuclearModel::CalculateHadronicVertex(), and G4ElectroVDNuclearModel::CalculateHadronicVertex().
void G4HadFinalState::AddSecondaries (const G4HadFinalState & addHFS) inline
Definition at line 92 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HadFinalState.hh
References AddSecondaries(), and theSecs.
void G4HadFinalState::AddSecondaries (const G4HadFinalState * addHFS) inline
Definition at line 96 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 96 of file G4HadFinalState.hh
References AddSecondaries(), and theSecs.
void G4HadFinalState::AddSecondary (G4DynamicParticle * aP, G4int mod = -1) inline
Definition at line 61 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 61 of file G4HadFinalState.hh
References theSecs, and theW.
Referenced by G4MuMinusCapturePrecompound::AddNewParticle(), G4EmCaptureCascade::AddNewParticle(), G4MuonMinusBoundDecay::AddNewParticle(), G4ParticleHPFinalState::adjust_final_state(), G4BinaryLightIonReaction::ApplyYourself(), G4LEnp::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4LEpp::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LENDFission::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4NeutrinoNucleusModel::CoherentPion(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CascadeInterface::copyOutputToHadronicResult(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMeson(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4NeutrinoNucleusModel::RecoilDeexcitation(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), G4RPGProtonInelastic::SlowProton(), and G4ParticleHPInelasticCompFS::use_nresp71_model().
void G4HadFinalState::AddSecondary (const G4HadSecondary & aHS) inline
Definition at line 65 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 65 of file G4HadFinalState.hh
References theSecs.
void G4HadFinalState::Clear ()
Definition at line 67 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 67 of file G4HadFinalState.cc
References ClearSecondaries(), isAlive, CLHEP::Hep3Vector::set(), theDirection, theEDep, theEnergy, theStat, and theW.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4LEnp::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4CascadeInterface::NoInteraction(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4CascadeInterface::Propagate(), G4RPGInelastic::SetUpChange(), G4LEHadronProtonElastic::~G4LEHadronProtonElastic(), G4LEnp::~G4LEnp(), G4LFission::~G4LFission(), and G4MuMinusCapturePrecompound::~G4MuMinusCapturePrecompound().
void G4HadFinalState::ClearSecondaries () inline
Definition at line 87 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 87 of file G4HadFinalState.hh
References theSecs.
Referenced by G4HadLeadBias::Bias(), and Clear().
G4double G4HadFinalState::GetEnergyChange () const inline
Definition at line 54 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 54 of file G4HadFinalState.hh
References theEnergy.
Referenced by G4HadLeadBias::Bias(), G4HadronicProcess::CheckResult(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4NeutrinoElectronProcess::PostStepDoIt().
G4double G4HadFinalState::GetLocalEnergyDeposit () const inline
Definition at line 84 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HadFinalState.hh
References theEDep.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4HadronicProcess::CheckResult(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4MuNeutrinoNucleusProcess::PostStepDoIt().
const G4ThreeVector& G4HadFinalState::GetMomentumChange () const inline
Definition at line 59 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 59 of file G4HadFinalState.hh
References theDirection.
Referenced by G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4NeutrinoElectronProcess::PostStepDoIt().
G4int G4HadFinalState::GetNumberOfSecondaries () const inline
Definition at line 51 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 51 of file G4HadFinalState.hh
References theSecs.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4ParticleHPInelasticBaseFS::BaseApply(), G4HadLeadBias::Bias(), G4HadronicProcess::CheckResult(), G4ParticleHPInelasticCompFS::CompositeApply(), G4MuonicAtomDecay::DecayIt(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
G4HadSecondary * G4HadFinalState::GetSecondary (size_t i)
Definition at line 79 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 79 of file G4HadFinalState.cc
References theSecs.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LFission::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4HadLeadBias::Bias(), G4HadronicProcess::CheckResult(), G4MuonicAtomDecay::DecayIt(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
const G4HadSecondary * G4HadFinalState::GetSecondary (size_t i) const
Definition at line 88 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 88 of file G4HadFinalState.cc
References theSecs.
G4HadFinalStateStatus G4HadFinalState::GetStatusChange () const inline
Definition at line 69 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 69 of file G4HadFinalState.hh
References theStat.
Referenced by G4HadronStoppingProcess::AtRestDoIt(), G4HadLeadBias::Bias(), G4HadronicProcess::CheckResult(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), and CexmcHadronicProcess::FillTotalResult().
const G4LorentzRotation& G4HadFinalState::GetTrafoToLab () const inline
Definition at line 72 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HadFinalState.hh
References theT.
Referenced by G4MuonicAtomDecay::FillResult().
G4double G4HadFinalState::GetWeightChange () const inline
Definition at line 78 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadFinalState.hh
References theW.
Referenced by G4BinaryCascade::DebugEpConservation(), and G4BinaryCascade::DebugFinalEpConservation().
void G4HadFinalState::SetEnergyChange (G4double anEnergy)
Definition at line 39 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HadFinalState.cc
References G4cout, G4endl, and theEnergy.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::NoInteraction(), G4LENDModel::returnUnchanged(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
void G4HadFinalState::SetLocalEnergyDeposit (G4double aE) inline
Definition at line 82 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HadFinalState.hh
References theEDep.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4NeutrinoNucleusModel::CoherentPion(), and G4NeutrinoNucleusModel::FinalBarion().
void G4HadFinalState::SetMomentumChange (const G4ThreeVector & aV) inline
Definition at line 56 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 56 of file G4HadFinalState.hh
References theDirection.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LENDModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonVDNuclearModel::CalculateEMVertex(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4LENDModel::returnUnchanged(), and G4RPGInelastic::SetUpChange().
void G4HadFinalState::SetMomentumChange (G4double x, G4double y, G4double z)
Definition at line 50 of file G4HadFinalState.cc.
View newest version in sPHENIX GitHub at line 50 of file G4HadFinalState.cc
References kdfinder::abs(), G4cout, G4endl, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::set(), and theDirection.
void G4HadFinalState::SetStatusChange (G4HadFinalStateStatus aS) inline
Definition at line 67 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HadFinalState.hh
References theStat.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4ParticleHPElastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDFission::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4MuonVDNuclearModel::CalculateEMVertex(), G4ParticleHPInelasticCompFS::CompositeApply(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::NoInteraction(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), G4RPGProtonInelastic::SlowProton(), and G4ParticleHPInelasticCompFS::use_nresp71_model().
void G4HadFinalState::SetTrafoToLab (const G4LorentzRotation & aT) inline
Definition at line 74 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadFinalState.hh
References theT.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
void G4HadFinalState::SetWeightChange (G4double aW) inline
Definition at line 76 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadFinalState.hh
References theW.
Member Data Documentation
G4ThreeVector G4HadFinalState::theDirection private
Definition at line 101 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HadFinalState.hh
Referenced by Clear(), GetMomentumChange(), and SetMomentumChange().
G4double G4HadFinalState::theEDep private
Definition at line 107 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 107 of file G4HadFinalState.hh
Referenced by Clear(), GetLocalEnergyDeposit(), and SetLocalEnergyDeposit().
G4double G4HadFinalState::theEnergy private
Definition at line 102 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 102 of file G4HadFinalState.hh
Referenced by Clear(), GetEnergyChange(), and SetEnergyChange().
std::vector<G4HadSecondary> G4HadFinalState::theSecs private
Definition at line 103 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 103 of file G4HadFinalState.hh
Referenced by AddSecondaries(), AddSecondary(), ClearSecondaries(), GetNumberOfSecondaries(), and GetSecondary().
G4HadFinalStateStatus G4HadFinalState::theStat private
Definition at line 104 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 104 of file G4HadFinalState.hh
Referenced by Clear(), GetStatusChange(), and SetStatusChange().
G4LorentzRotation G4HadFinalState::theT private
Definition at line 105 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 105 of file G4HadFinalState.hh
Referenced by GetTrafoToLab(), and SetTrafoToLab().
G4double G4HadFinalState::theW private
Definition at line 106 of file G4HadFinalState.hh.
View newest version in sPHENIX GitHub at line 106 of file G4HadFinalState.hh
Referenced by AddSecondary(), Clear(), GetWeightChange(), and SetWeightChange().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadFinalState.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4HadFinalState.cc