ECCE @ EIC Software: coresoftware/blob/master/generators/hijing/examples/example_1.f File Reference
example_1.f File Reference
Functions/Subroutines
program __example_1.f__
function ran (NSEED)
Function/Subroutine Documentation
program __example_1.f__ ()
Definition at line 10 of file example_1.f.
View newest version in sPHENIX GitHub at line 10 of file example_1.f
References common(), HiMain1::eatt(), efrm, hijing(), hijset(), iap, HijJet2::iasg(), iat, izp, izt, HiMain1::jatt(), HijJet2::k1sg(), HijJet2::k2sg(), HiMain2::katt(), HijJet1::kfpj(), HijJet1::kftj(), luchge(), HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HijJet2::njsg(), HiMain1::np(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HiMain1::nt(), HijJet1::ntj(), HiMain2::patt(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), proj, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), PHTimer::stop(), targ, ulmass(), and x.
function ran (NSEED)
Definition at line 103 of file example_1.f.
View newest version in sPHENIX GitHub at line 103 of file example_1.f
References RanSeed::nseed(), and rlu().
Referenced by G4RPGReaction::AddBlackTrackParticles(), G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), G4LFission::ApplyYourself(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4ECDecay::DecayIt(), G4Abla::DeexcitationAblaxx(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), G4ChipsProtonElasticXS::GetExchangeT(), G4ChipsKaonPlusElasticXS::GetExchangeT(), G4ChipsPionPlusElasticXS::GetExchangeT(), G4ChipsHyperonElasticXS::GetExchangeT(), G4ChipsPionMinusElasticXS::GetExchangeT(), G4ChipsKaonMinusElasticXS::GetExchangeT(), G4ChipsNeutronElasticXS::GetExchangeT(), G4ChipsAntiBaryonElasticXS::GetExchangeT(), G4PhononDownconversion::MakeTTSecondaries(), G4RPGReaction::normal(), G4RPGReaction::NuclearReaction(), G4AntiNeutronAnnihilationAtRest::Poisso(), ran(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().