ECCE @ EIC Software: CanvasInTab Class Reference
CanvasInTab Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/plot/include/CanvasInTab.hh>
Public Member Functions
CanvasInTab (const TGWindow *p, UInt_t w, UInt_t h)
virtual ~CanvasInTab ()
size_t AddCanvas (const char *name="New tab")
TCanvas * GetCanvas (int i)
size_t GetNCanvas () const
void SaveCanvas ()
Private Attributes
TGTab * fpTab
std::vector
< TRootEmbeddedCanvas * > fEcanvas
TGLayoutHints * fHintPlots
Detailed Description
Definition at line 36 of file CanvasInTab.hh.
View newest version in sPHENIX GitHub at line 36 of file CanvasInTab.hh
Constructor & Destructor Documentation
CanvasInTab::CanvasInTab (const TGWindow * p, UInt_t w, UInt_t h)
Definition at line 70 of file CanvasInTab.cc.
View newest version in sPHENIX GitHub at line 70 of file CanvasInTab.cc
References g4zmq::exit(), fHintPlots, and fpTab.
CanvasInTab::~CanvasInTab () virtual
Definition at line 108 of file CanvasInTab.cc.
View newest version in sPHENIX GitHub at line 108 of file CanvasInTab.cc
Member Function Documentation
size_t CanvasInTab::AddCanvas (const char * name = "New tab")
Definition at line 121 of file CanvasInTab.cc.
View newest version in sPHENIX GitHub at line 121 of file CanvasInTab.cc
References fEcanvas, fHintPlots, and fpTab.
Referenced by ProcessSingleFile().
TCanvas * CanvasInTab::GetCanvas (int i)
Definition at line 140 of file CanvasInTab.cc.
View newest version in sPHENIX GitHub at line 140 of file CanvasInTab.cc
References fEcanvas.
Referenced by ProcessSingleFile().
size_t CanvasInTab::GetNCanvas () const inline
Definition at line 49 of file CanvasInTab.hh.
View newest version in sPHENIX GitHub at line 49 of file CanvasInTab.hh
References fEcanvas.
Referenced by ProcessSingleFile().
void CanvasInTab::SaveCanvas ()
Definition at line 145 of file CanvasInTab.cc.
View newest version in sPHENIX GitHub at line 145 of file CanvasInTab.cc
References fEcanvas, fpTab, and SaveFileDialog().
Member Data Documentation
std::vector<TRootEmbeddedCanvas*> CanvasInTab::fEcanvas private
Definition at line 40 of file CanvasInTab.hh.
View newest version in sPHENIX GitHub at line 40 of file CanvasInTab.hh
Referenced by AddCanvas(), GetCanvas(), GetNCanvas(), and SaveCanvas().
TGLayoutHints* CanvasInTab::fHintPlots private
Definition at line 41 of file CanvasInTab.hh.
View newest version in sPHENIX GitHub at line 41 of file CanvasInTab.hh
Referenced by AddCanvas(), and CanvasInTab().
TGTab* CanvasInTab::fpTab private
Definition at line 39 of file CanvasInTab.hh.
View newest version in sPHENIX GitHub at line 39 of file CanvasInTab.hh
Referenced by AddCanvas(), CanvasInTab(), and SaveCanvas().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/plot/include/CanvasInTab.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/plot/src/CanvasInTab.cc