ECCE @ EIC Software: G4VScoringMesh Class Reference
G4VScoringMesh Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoringMesh.hh>
Public Types
enum MeshShape
using EventScore = G4THitsMap< G4double >
using RunScore = G4THitsMap< G4StatDouble >
using MeshScoreMap = std::map< G4String, RunScore * >
Public Member Functions
G4VScoringMesh (const G4String &wName)
virtual ~G4VScoringMesh ()
void Construct (G4VPhysicalVolume *fWorldPhys)
void WorkerConstruct (G4VPhysicalVolume *fWorldPhys)
virtual void List () const
const G4String & GetWorldName () const
G4bool IsActive () const
void Activate (G4bool vl=true)
MeshShape GetShape () const
void Accumulate (G4THitsMap< G4double > *map)
void Accumulate (G4THitsMap< G4StatDouble > *map)
void Merge (const G4VScoringMesh *scMesh)
void Dump ()
void DrawMesh (const G4String &psName, G4VScoreColorMap *colorMap, G4int axflg=111)
void DrawMesh (const G4String &psName, G4int idxPlane, G4int iColumn, G4VScoreColorMap *colorMap)
virtual void Draw (RunScore *map, G4VScoreColorMap *colorMap, G4int axflg=111)=0
virtual void DrawColumn (RunScore *map, G4VScoreColorMap *colorMap, G4int idxProj, G4int idxColumn)=0
void ResetScore ()
void SetSize (G4double size[3])
G4ThreeVector GetSize () const
void SetCenterPosition (G4double centerPosition[3])
G4ThreeVector GetTranslation () const
void RotateX (G4double delta)
void RotateY (G4double delta)
void RotateZ (G4double delta)
G4RotationMatrix GetRotationMatrix () const
void SetNumberOfSegments (G4int nSegment[3])
void GetNumberOfSegments (G4int nSegment[3])
void SetPrimitiveScorer (G4VPrimitiveScorer *ps)
void SetFilter (G4VSDFilter *filter)
void SetCurrentPrimitiveScorer (const G4String &name)
G4bool FindPrimitiveScorer (const G4String &psname)
G4bool IsCurrentPrimitiveScorerNull ()
G4String GetPSUnit (const G4String &psname)
G4String GetCurrentPSUnit ()
void SetCurrentPSUnit (const G4String &unit)
G4double GetPSUnitValue (const G4String &psname)
void SetDrawPSName (const G4String &psname)
void GetDivisionAxisNames (G4String divisionAxisNames[3])
void SetNullToCurrentPrimitiveScorer ()
void SetVerboseLevel (G4int vl)
MeshScoreMap GetScoreMap () const
G4bool ReadyForQuantity () const
void SetMeshElementLogical (G4LogicalVolume *val)
G4LogicalVolume * GetMeshElementLogical () const
void SetParallelWorldProcess (G4ParallelWorldProcess *proc)
G4ParallelWorldProcess * GetParallelWorldProcess () const
void GeometryHasBeenDestroyed ()
void SetCopyNumberLevel (G4int val)
G4int GetCopyNumberLevel () const
Protected Member Functions
virtual void SetupGeometry (G4VPhysicalVolume *fWorldPhys)=0
G4VPrimitiveScorer * GetPrimitiveScorer (const G4String &name)
Protected Attributes
G4String fWorldName
G4VPrimitiveScorer * fCurrentPS
G4bool fConstructed
G4bool fActive
MeshShape fShape
G4double fSize [3]
G4ThreeVector fCenterPosition
G4RotationMatrix * fRotationMatrix
G4int fNSegment [3]
MeshScoreMap fMap
G4MultiFunctionalDetector * fMFD
G4int verboseLevel
G4bool sizeIsSet
G4bool nMeshIsSet
G4String fDrawUnit
G4double fDrawUnitValue
G4String fDrawPSName
G4String fDivisionAxisNames [3]
G4LogicalVolume * fMeshElementLogical
G4ParallelWorldProcess * fParallelWorldProcess
G4bool fGeometryHasBeenDestroyed
G4int copyNumberLevel
Detailed Description
Definition at line 53 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VScoringMesh.hh
Member Typedef Documentation
using G4VScoringMesh::EventScore = G4THitsMap< G4double >
Definition at line 57 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VScoringMesh.hh
using G4VScoringMesh::MeshScoreMap = std::map< G4String, RunScore* >
Definition at line 59 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VScoringMesh.hh
using G4VScoringMesh::RunScore = G4THitsMap< G4StatDouble >
Definition at line 58 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VScoringMesh.hh
Member Enumeration Documentation
enum G4VScoringMesh::MeshShape
Definition at line 56 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VScoringMesh.hh
Constructor & Destructor Documentation
G4VScoringMesh::G4VScoringMesh (const G4String & wName)
Definition at line 45 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VScoringMesh.cc
References G4SDManager::AddNewDetector(), fDivisionAxisNames, fMFD, fNSegment, fSize, and G4SDManager::GetSDMpointer().
G4VScoringMesh::~G4VScoringMesh () virtual
Definition at line 61 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VScoringMesh.cc
Member Function Documentation
void G4VScoringMesh::Accumulate (G4THitsMap< G4double > * map)
Definition at line 314 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 314 of file G4VScoringMesh.cc
References fMap, G4cout, G4endl, G4VHitsCollection::GetName(), G4VTHitsMap< T, Map_t >::GetSize(), G4VTHitsMap< T, Map_t >::PrintAllHits(), and verboseLevel.
Referenced by GammaKnifeController::AccumulateAllHits(), and G4MPIscorerMerger::UnPackAndMerge().
void G4VScoringMesh::Accumulate (G4THitsMap< G4StatDouble > * map)
Definition at line 334 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 334 of file G4VScoringMesh.cc
References fMap, G4cout, G4endl, G4VHitsCollection::GetName(), G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >::GetSize(), G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >::PrintAllHits(), and verboseLevel.
void G4VScoringMesh::Activate (G4bool vl = true) inline
Definition at line 88 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VScoringMesh.hh
References fActive.
void G4VScoringMesh::Construct (G4VPhysicalVolume * fWorldPhys)
Definition at line 354 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 354 of file G4VScoringMesh.cc
References fConstructed, fGeometryHasBeenDestroyed, fWorldName, G4cout, G4endl, ResetScore(), SetupGeometry(), and verboseLevel.
Referenced by G4RunManager::ConstructScoringWorlds().
virtual void G4VScoringMesh::Draw (RunScore * map, G4VScoreColorMap * colorMap, G4int axflg = 111) pure virtual
Implemented in G4ScoringBox, G4ScoringRealWorld, and G4ScoringCylinder.
Referenced by DrawMesh().
virtual void G4VScoringMesh::DrawColumn (RunScore * map, G4VScoreColorMap * colorMap, G4int idxProj, G4int idxColumn) pure virtual
Implemented in G4ScoringBox, G4ScoringRealWorld, and G4ScoringCylinder.
Referenced by DrawMesh().
void G4VScoringMesh::DrawMesh (const G4String & psName, G4VScoreColorMap * colorMap, G4int axflg = 111)
Definition at line 288 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 288 of file G4VScoringMesh.cc
References Draw(), fDrawPSName, fDrawUnit, fDrawUnitValue, fMap, G4cerr, G4endl, GetPSUnit(), and GetPSUnitValue().
Referenced by G4VSceneHandler::AddCompound(), and G4ScoringManager::DrawMesh().
void G4VScoringMesh::DrawMesh (const G4String & psName, G4int idxPlane, G4int iColumn, G4VScoreColorMap * colorMap)
Definition at line 301 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 301 of file G4VScoringMesh.cc
References DrawColumn(), fDrawPSName, fDrawUnit, fDrawUnitValue, fMap, G4cerr, G4endl, GetPSUnit(), and GetPSUnitValue().
void G4VScoringMesh::Dump ()
Definition at line 275 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 275 of file G4VScoringMesh.cc
References fMap, fWorldName, G4cout, and G4endl.
G4bool G4VScoringMesh::FindPrimitiveScorer (const G4String & psname)
Definition at line 175 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 175 of file G4VScoringMesh.cc
References fMap.
Referenced by G4ScoreQuantityMessenger::CheckMeshPS().
void G4VScoringMesh::GeometryHasBeenDestroyed () inline
Definition at line 223 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 223 of file G4VScoringMesh.hh
References fGeometryHasBeenDestroyed, and fMeshElementLogical.
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
G4int G4VScoringMesh::GetCopyNumberLevel () const inline
Definition at line 236 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 236 of file G4VScoringMesh.hh
References copyNumberLevel.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
G4String G4VScoringMesh::GetCurrentPSUnit ()
Definition at line 190 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 190 of file G4VScoringMesh.cc
References fCurrentPS, G4cerr, G4endl, and G4VPrimitiveScorer::GetUnit().
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4VScoringMesh::GetDivisionAxisNames (G4String divisionAxisNames[3])
Definition at line 221 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 221 of file G4VScoringMesh.cc
References fDivisionAxisNames.
Referenced by G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), and PHG4ScoringManager::makeScoringHistograms().
G4LogicalVolume* G4VScoringMesh::GetMeshElementLogical () const inline
Definition at line 212 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 212 of file G4VScoringMesh.hh
References fMeshElementLogical.
Referenced by G4WorkerRunManager::ConstructScoringWorlds().
void G4VScoringMesh::GetNumberOfSegments (G4int nSegment[3])
Definition at line 105 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 105 of file G4VScoringMesh.cc
References fNSegment.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), PHG4ScoringManager::makeScoringHistograms(), G4ScoreQuantityMessenger::SetNewValue(), and G4VScoreWriter::SetScoringMesh().
G4ParallelWorldProcess* G4VScoringMesh::GetParallelWorldProcess () const inline
Definition at line 221 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 221 of file G4VScoringMesh.hh
References fParallelWorldProcess.
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
G4VPrimitiveScorer * G4VScoringMesh::GetPrimitiveScorer (const G4String & name) protected
Definition at line 225 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 225 of file G4VScoringMesh.cc
References fMFD, G4VPrimitiveScorer::GetName(), G4MultiFunctionalDetector::GetNumberOfPrimitives(), and G4MultiFunctionalDetector::GetPrimitive().
Referenced by GetPSUnit(), GetPSUnitValue(), and SetCurrentPrimitiveScorer().
G4String G4VScoringMesh::GetPSUnit (const G4String & psname)
Definition at line 181 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 181 of file G4VScoringMesh.cc
References fMap, GetPrimitiveScorer(), and G4VPrimitiveScorer::GetUnit().
Referenced by DrawMesh(), G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), and PHG4ScoringManager::makeScoringHistograms().
G4double G4VScoringMesh::GetPSUnitValue (const G4String & psname)
Definition at line 212 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 212 of file G4VScoringMesh.cc
References fMap, GetPrimitiveScorer(), and G4VPrimitiveScorer::GetUnitValue().
Referenced by DrawMesh(), G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), and PHG4ScoringManager::makeScoringHistograms().
G4RotationMatrix G4VScoringMesh::GetRotationMatrix () const inline
Definition at line 128 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 128 of file G4VScoringMesh.hh
References fRotationMatrix, and CLHEP::HepRotation::IDENTITY.
Referenced by G4GMocrenFileSceneHandler::AddSolid().
MeshScoreMap G4VScoringMesh::GetScoreMap () const inline
Definition at line 171 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 171 of file G4VScoringMesh.hh
References fMap.
Referenced by G4VSceneHandler::AddCompound(), G4MPIscorerMerger::CalculatePackSize(), G4PSHitsModel::DescribeYourselfTo(), G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), PHG4ScoringManager::makeScoringHistograms(), Merge(), G4MPIscorerMerger::Pack(), GammaKnifeController::PrepareHitsAccumulation(), and GammaKnifeController::StoreHits().
MeshShape G4VScoringMesh::GetShape () const inline
Definition at line 91 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VScoringMesh.hh
References fShape.
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), PHG4ScoringManager::makeScoringHistograms(), G4ScoreQuantityMessenger::SetNewValue(), and G4ScoringMessenger::SetNewValue().
G4ThreeVector G4VScoringMesh::GetSize () const
Definition at line 85 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VScoringMesh.cc
References fSize, and sizeIsSet.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), PHG4ScoringManager::makeScoringHistograms(), and G4ScoreQuantityMessenger::SetNewValue().
G4ThreeVector G4VScoringMesh::GetTranslation () const inline
Definition at line 120 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VScoringMesh.hh
References fCenterPosition.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and PHG4ScoringManager::makeScoringHistograms().
const G4String& G4VScoringMesh::GetWorldName () const inline
Definition at line 82 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VScoringMesh.hh
References fWorldName.
Referenced by G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), PHG4ScoringManager::makeScoringHistograms(), G4ScoringMessenger::SetNewValue(), and G4MPIscorerMerger::UnPackAndMerge().
G4bool G4VScoringMesh::IsActive () const inline
Definition at line 85 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VScoringMesh.hh
References fActive.
Referenced by G4VSceneHandler::AddCompound(), and G4PSHitsModel::DescribeYourselfTo().
G4bool G4VScoringMesh::IsCurrentPrimitiveScorerNull () inline
Definition at line 147 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VScoringMesh.hh
References fCurrentPS.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4VScoringMesh::List () const virtual
Reimplemented in G4ScoringBox, G4ScoringCylinder, and G4ScoringRealWorld.
Definition at line 236 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 236 of file G4VScoringMesh.cc
References cm, fCenterPosition, fMFD, fNSegment, fRotationMatrix, G4cout, G4endl, G4VPrimitiveScorer::GetFilter(), G4VSDFilter::GetName(), G4VPrimitiveScorer::GetName(), G4MultiFunctionalDetector::GetNumberOfPrimitives(), G4MultiFunctionalDetector::GetPrimitive(), CLHEP::Hep3Vector::x(), CLHEP::HepRotation::xx(), CLHEP::HepRotation::xy(), CLHEP::HepRotation::xz(), CLHEP::Hep3Vector::y(), CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), CLHEP::Hep3Vector::z(), CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
Referenced by G4ScoringRealWorld::List(), G4ScoringCylinder::List(), G4ScoringBox::List(), and PHG4ScoringManager::makeScoringHistograms().
void G4VScoringMesh::Merge (const G4VScoringMesh * scMesh)
Definition at line 390 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 390 of file G4VScoringMesh.cc
References fMap, G4cout, G4endl, GetScoreMap(), and verboseLevel.
Referenced by G4ScoringManager::Merge().
G4bool G4VScoringMesh::ReadyForQuantity () const inline
Definition at line 174 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 174 of file G4VScoringMesh.hh
References nMeshIsSet, and sizeIsSet.
Referenced by SetPrimitiveScorer().
void G4VScoringMesh::ResetScore ()
Definition at line 65 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VScoringMesh.cc
References fMap, G4cout, G4endl, and verboseLevel.
Referenced by Construct(), and WorkerConstruct().
void G4VScoringMesh::RotateX (G4double delta)
Definition at line 108 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 108 of file G4VScoringMesh.cc
References fRotationMatrix, and CLHEP::HepRotation::rotateX().
Referenced by GammaKnifeController::RotateBack(), GammaKnifeController::RotateForward(), and G4ScoringMessenger::SetNewValue().
void G4VScoringMesh::RotateY (G4double delta)
Definition at line 113 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 113 of file G4VScoringMesh.cc
References fRotationMatrix, and CLHEP::HepRotation::rotateY().
Referenced by G4ScoringMessenger::SetNewValue().
void G4VScoringMesh::RotateZ (G4double delta)
Definition at line 118 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 118 of file G4VScoringMesh.cc
References fRotationMatrix, and CLHEP::HepRotation::rotateZ().
Referenced by GammaKnifeController::RotateBack(), GammaKnifeController::RotateForward(), and G4ScoringMessenger::SetNewValue().
void G4VScoringMesh::SetCenterPosition (G4double centerPosition[3])
Definition at line 91 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 91 of file G4VScoringMesh.cc
References fCenterPosition.
Referenced by G4ScoringMessenger::SetNewValue().
void G4VScoringMesh::SetCopyNumberLevel (G4int val) inline
Definition at line 234 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 234 of file G4VScoringMesh.hh
References copyNumberLevel.
void G4VScoringMesh::SetCurrentPrimitiveScorer (const G4String & name)
Definition at line 167 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 167 of file G4VScoringMesh.cc
References fCurrentPS, G4cerr, G4endl, and GetPrimitiveScorer().
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4VScoringMesh::SetCurrentPSUnit (const G4String & unit)
Definition at line 202 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 202 of file G4VScoringMesh.cc
References fCurrentPS, G4cerr, G4endl, and G4VPrimitiveScorer::SetUnit().
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4VScoringMesh::SetDrawPSName (const G4String & psname) inline
Definition at line 160 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 160 of file G4VScoringMesh.hh
References fDrawPSName.
void G4VScoringMesh::SetFilter (G4VSDFilter * filter)
Definition at line 147 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 147 of file G4VScoringMesh.cc
References fCurrentPS, G4cerr, G4cout, G4endl, G4VPrimitiveScorer::GetFilter(), G4VSDFilter::GetName(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::SetFilter(), and verboseLevel.
Referenced by G4ScoreQuantityMessenger::FParticleCommand(), G4ScoreQuantityMessenger::FParticleWithEnergyCommand(), and G4ScoreQuantityMessenger::SetNewValue().
void G4VScoringMesh::SetMeshElementLogical (G4LogicalVolume * val) inline
Definition at line 210 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 210 of file G4VScoringMesh.hh
References fMeshElementLogical.
Referenced by G4WorkerRunManager::ConstructScoringWorlds().
void G4VScoringMesh::SetNullToCurrentPrimitiveScorer () inline
Definition at line 166 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 166 of file G4VScoringMesh.hh
References fCurrentPS.
Referenced by G4ScoreQuantityMessenger::CheckMeshPS().
void G4VScoringMesh::SetNumberOfSegments (G4int nSegment[3])
Definition at line 94 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 94 of file G4VScoringMesh.cc
References fNSegment, fShape, G4Exception(), JustWarning, message(), and nMeshIsSet.
Referenced by G4ScoringRealWorld::G4ScoringRealWorld(), G4ScoringMessenger::MeshBinCommand(), and G4ScoringRealWorld::SetupGeometry().
void G4VScoringMesh::SetParallelWorldProcess (G4ParallelWorldProcess * proc) inline
Definition at line 219 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 219 of file G4VScoringMesh.hh
References fParallelWorldProcess.
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
void G4VScoringMesh::SetPrimitiveScorer (G4VPrimitiveScorer * ps)
Definition at line 123 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 123 of file G4VScoringMesh.cc
References fCurrentPS, fMap, fMFD, fNSegment, fWorldName, G4cerr, G4cout, G4endl, G4VPrimitiveScorer::GetName(), ReadyForQuantity(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VPrimitiveScorer::SetNijk(), and verboseLevel.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4VScoringMesh::SetSize (G4double size[3])
Definition at line 74 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VScoringMesh.cc
References fSize, G4Exception(), JustWarning, message(), and sizeIsSet.
Referenced by G4ScoringRealWorld::G4ScoringRealWorld(), and G4ScoringMessenger::SetNewValue().
virtual void G4VScoringMesh::SetupGeometry (G4VPhysicalVolume * fWorldPhys) protected pure virtual
Implemented in G4ScoringBox, G4ScoringCylinder, and G4ScoringRealWorld.
Referenced by Construct().
void G4VScoringMesh::SetVerboseLevel (G4int vl) inline
Definition at line 168 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VScoringMesh.hh
References verboseLevel.
Referenced by G4ScoringManager::RegisterScoringMesh().
void G4VScoringMesh::WorkerConstruct (G4VPhysicalVolume * fWorldPhys)
Definition at line 372 of file G4VScoringMesh.cc.
View newest version in sPHENIX GitHub at line 372 of file G4VScoringMesh.cc
References fConstructed, fGeometryHasBeenDestroyed, fMeshElementLogical, fMFD, G4cout, G4endl, G4VPhysicalVolume::GetName(), ResetScore(), G4LogicalVolume::SetSensitiveDetector(), and verboseLevel.
Referenced by G4WorkerRunManager::ConstructScoringWorlds().
Member Data Documentation
G4int G4VScoringMesh::copyNumberLevel protected
Definition at line 230 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 230 of file G4VScoringMesh.hh
Referenced by GetCopyNumberLevel(), and SetCopyNumberLevel().
G4bool G4VScoringMesh::fActive protected
Definition at line 185 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 185 of file G4VScoringMesh.hh
Referenced by Activate(), and IsActive().
G4ThreeVector G4VScoringMesh::fCenterPosition protected
Definition at line 189 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 189 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), GetTranslation(), List(), SetCenterPosition(), G4ScoringCylinder::SetupGeometry(), and G4ScoringBox::SetupGeometry().
G4bool G4VScoringMesh::fConstructed protected
Definition at line 184 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 184 of file G4VScoringMesh.hh
Referenced by Construct(), and WorkerConstruct().
G4VPrimitiveScorer* G4VScoringMesh::fCurrentPS protected
Definition at line 183 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 183 of file G4VScoringMesh.hh
Referenced by GetCurrentPSUnit(), IsCurrentPrimitiveScorerNull(), SetCurrentPrimitiveScorer(), SetCurrentPSUnit(), SetFilter(), SetNullToCurrentPrimitiveScorer(), and SetPrimitiveScorer().
G4String G4VScoringMesh::fDivisionAxisNames[3] protected
Definition at line 205 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 205 of file G4VScoringMesh.hh
Referenced by G4ScoringBox::G4ScoringBox(), G4ScoringCylinder::G4ScoringCylinder(), G4VScoringMesh(), and GetDivisionAxisNames().
G4String G4VScoringMesh::fDrawPSName protected
Definition at line 203 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 203 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), DrawMesh(), and SetDrawPSName().
G4String G4VScoringMesh::fDrawUnit protected
Definition at line 201 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 201 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), and DrawMesh().
G4double G4VScoringMesh::fDrawUnitValue protected
Definition at line 202 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 202 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), and DrawMesh().
G4bool G4VScoringMesh::fGeometryHasBeenDestroyed protected
Definition at line 217 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 217 of file G4VScoringMesh.hh
Referenced by Construct(), GeometryHasBeenDestroyed(), and WorkerConstruct().
MeshScoreMap G4VScoringMesh::fMap protected
Definition at line 193 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 193 of file G4VScoringMesh.hh
Referenced by Accumulate(), DrawMesh(), Dump(), FindPrimitiveScorer(), GetPSUnit(), GetPSUnitValue(), GetScoreMap(), Merge(), ResetScore(), and SetPrimitiveScorer().
G4LogicalVolume* G4VScoringMesh::fMeshElementLogical protected
Definition at line 207 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 207 of file G4VScoringMesh.hh
Referenced by GeometryHasBeenDestroyed(), GetMeshElementLogical(), SetMeshElementLogical(), G4ScoringRealWorld::SetupGeometry(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), and WorkerConstruct().
G4MultiFunctionalDetector* G4VScoringMesh::fMFD protected
Definition at line 194 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 194 of file G4VScoringMesh.hh
Referenced by G4VScoringMesh(), GetPrimitiveScorer(), List(), SetPrimitiveScorer(), G4ScoringRealWorld::SetupGeometry(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), and WorkerConstruct().
G4int G4VScoringMesh::fNSegment[3] protected
Definition at line 191 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 191 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), G4VScoringMesh(), G4ScoringBox::GetIndex(), GetNumberOfSegments(), G4ScoringBox::GetReplicaPosition(), G4ScoringBox::GetXYZ(), List(), SetNumberOfSegments(), SetPrimitiveScorer(), G4ScoringCylinder::SetupGeometry(), and G4ScoringBox::SetupGeometry().
G4ParallelWorldProcess* G4VScoringMesh::fParallelWorldProcess protected
Definition at line 216 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 216 of file G4VScoringMesh.hh
Referenced by GetParallelWorldProcess(), and SetParallelWorldProcess().
G4RotationMatrix* G4VScoringMesh::fRotationMatrix protected
Definition at line 190 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 190 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), GetRotationMatrix(), List(), RotateX(), RotateY(), RotateZ(), G4ScoringCylinder::SetupGeometry(), and G4ScoringBox::SetupGeometry().
MeshShape G4VScoringMesh::fShape protected
Definition at line 186 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 186 of file G4VScoringMesh.hh
Referenced by G4ScoringBox::G4ScoringBox(), G4ScoringCylinder::G4ScoringCylinder(), G4ScoringRealWorld::G4ScoringRealWorld(), GetShape(), and SetNumberOfSegments().
G4double G4VScoringMesh::fSize[3] protected
Definition at line 188 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 188 of file G4VScoringMesh.hh
Referenced by G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), G4VScoringMesh(), G4ScoringBox::GetReplicaPosition(), GetSize(), G4ScoringCylinder::List(), G4ScoringBox::List(), G4ScoringCylinder::SetRMax(), SetSize(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), and G4ScoringCylinder::SetZSize().
G4String G4VScoringMesh::fWorldName protected
Definition at line 182 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 182 of file G4VScoringMesh.hh
Referenced by Construct(), Dump(), GetWorldName(), G4ScoringCylinder::List(), G4ScoringBox::List(), SetPrimitiveScorer(), G4ScoringCylinder::SetupGeometry(), and G4ScoringBox::SetupGeometry().
G4bool G4VScoringMesh::nMeshIsSet protected
Definition at line 199 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 199 of file G4VScoringMesh.hh
Referenced by ReadyForQuantity(), and SetNumberOfSegments().
G4bool G4VScoringMesh::sizeIsSet protected
Definition at line 198 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 198 of file G4VScoringMesh.hh
Referenced by GetSize(), ReadyForQuantity(), and SetSize().
G4int G4VScoringMesh::verboseLevel protected
Definition at line 196 of file G4VScoringMesh.hh.
View newest version in sPHENIX GitHub at line 196 of file G4VScoringMesh.hh
Referenced by Accumulate(), Construct(), Merge(), ResetScore(), SetFilter(), SetPrimitiveScorer(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), SetVerboseLevel(), and WorkerConstruct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoringMesh.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4VScoringMesh.cc