ECCE @ EIC Software: G4ParticleHPFSFissionFS Class Reference
G4ParticleHPFSFissionFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFSFissionFS.hh>
Classes
struct toBeCached
Public Member Functions
G4ParticleHPFSFissionFS ()
~G4ParticleHPFSFissionFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aFSType, G4ParticleDefinition *)
G4DynamicParticleVector * ApplyYourself (G4int Prompt, G4int delayed, G4double *decayconst)
G4ParticleHPFinalState * New ()
G4double GetMass ()
void SampleNeutronMult (G4int &all, G4int &Prompt, G4int &delayed, G4double energy, G4int off)
void SetNeutronRP (const G4ReactionProduct &aNeutron)
void SetTarget (const G4ReactionProduct &aTarget)
G4DynamicParticleVector * GetPhotons ()
G4ParticleHPFissionERelease * GetEnergyRelease ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
virtual G4double GetXsec (G4double)
virtual G4ParticleHPVector * GetXsec ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Member Functions
G4HadFinalState * ApplyYourself (const G4HadProjectile &)
Private Attributes
G4ParticleHPParticleYield theFinalStateNeutrons
G4ParticleHPEnergyDistribution thePromptNeutronEnDis
G4ParticleHPEnergyDistribution theDelayedNeutronEnDis
G4ParticleHPAngular theNeutronAngularDis
G4ParticleHPPhotonDist theFinalStatePhotons
G4ParticleHPFissionERelease theEnergyRelease
G4Cache< toBeCached > fCache
G4ParticleHPNames theNames
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 45 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPFSFissionFS.hh
Constructor & Destructor Documentation
G4ParticleHPFSFissionFS::G4ParticleHPFSFissionFS () inline
Definition at line 56 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPFSFissionFS.hh
References G4ParticleHPFinalState::hasXsec.
Referenced by New().
G4ParticleHPFSFissionFS::~G4ParticleHPFSFissionFS () inline
Definition at line 57 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleHPFSFissionFS.hh
Member Function Documentation
G4DynamicParticleVector * G4ParticleHPFSFissionFS::ApplyYourself (G4int Prompt, G4int delayed, G4double * decayconst)
Definition at line 103 of file G4ParticleHPFSFissionFS.cc.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPFSFissionFS.cc
References fCache, G4Cache< VALTYPE >::Get(), G4ParticleHPParticleYield::GetDecayConstant(), G4ReactionProduct::GetKineticEnergy(), it, G4ReactionProduct::Lorentz(), G4Neutron::Neutron(), G4ParticleHPEnergyDistribution::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4DynamicParticle::SetMomentum(), theDelayedNeutronEnDis, theFinalStateNeutrons, theNeutronAngularDis, and thePromptNeutronEnDis.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
G4HadFinalState* G4ParticleHPFSFissionFS::ApplyYourself (const G4HadProjectile &) inline private virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 103 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPFSFissionFS.hh
G4ParticleHPFissionERelease* G4ParticleHPFSFissionFS::GetEnergyRelease () inline
Definition at line 96 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPFSFissionFS.hh
References theEnergyRelease.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
G4double G4ParticleHPFSFissionFS::GetMass () inline
Definition at line 71 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPFSFissionFS.hh
References G4ParticleHPParticleYield::GetTargetMass(), and theFinalStateNeutrons.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
G4DynamicParticleVector * G4ParticleHPFSFissionFS::GetPhotons ()
Definition at line 177 of file G4ParticleHPFSFissionFS.cc.
View newest version in sPHENIX GitHub at line 177 of file G4ParticleHPFSFissionFS.cc
References fCache, G4Cache< VALTYPE >::Get(), G4ReactionProduct::GetKineticEnergy(), G4ParticleHPPhotonDist::GetPhotons(), G4ReactionProduct::Lorentz(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetMomentum(), and theFinalStatePhotons.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
void G4ParticleHPFSFissionFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aFSType, G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Definition at line 45 of file G4ParticleHPFSFissionFS.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPFSFissionFS.cc
References INPUTHEPMC::filename, G4cout, G4endl, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPFinalState::hasAnyData, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPFissionERelease::Init(), G4ParticleHPEnergyDistribution::Init(), G4ParticleHPAngular::Init(), G4ParticleHPPhotonDist::InitAngular(), G4ParticleHPParticleYield::InitDelayed(), G4ParticleHPPhotonDist::InitEnergies(), G4ParticleHPParticleYield::InitMean(), G4ParticleHPPhotonDist::InitMean(), G4ParticleHPParticleYield::InitPrompt(), G4ParticleHPFinalState::SetAZMs(), theDelayedNeutronEnDis, theEnergyRelease, theFinalStateNeutrons, theFinalStatePhotons, theNames, theNeutronAngularDis, and thePromptNeutronEnDis.
Referenced by G4ParticleHPFissionFS::Init().
G4ParticleHPFinalState* G4ParticleHPFSFissionFS::New () inline virtual
Implements G4ParticleHPFinalState.
Definition at line 65 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPFSFissionFS.hh
References G4ParticleHPFSFissionFS().
void G4ParticleHPFSFissionFS::SampleNeutronMult (G4int & all, G4int & Prompt, G4int & delayed, G4double energy, G4int off)
Definition at line 153 of file G4ParticleHPFSFissionFS.cc.
View newest version in sPHENIX GitHub at line 153 of file G4ParticleHPFSFissionFS.cc
References G4Poisson(), G4ParticleHPParticleYield::GetDelayed(), G4ParticleHPParticleYield::GetMean(), G4ParticleHPParticleYield::GetPrompt(), and theFinalStateNeutrons.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
void G4ParticleHPFSFissionFS::SetNeutronRP (const G4ReactionProduct & aNeutron) inline
Definition at line 82 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPFSFissionFS.hh
References fCache, G4Cache< VALTYPE >::Get(), G4ParticleHPAngular::SetProjectileRP(), and theNeutronAngularDis.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
void G4ParticleHPFSFissionFS::SetTarget (const G4ReactionProduct & aTarget) inline
Definition at line 88 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPFSFissionFS.hh
References fCache, G4Cache< VALTYPE >::Get(), G4ParticleHPAngular::SetTarget(), and theNeutronAngularDis.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
Member Data Documentation
G4Cache<toBeCached> G4ParticleHPFSFissionFS::fCache private
Definition at line 113 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPFSFissionFS.hh
Referenced by ApplyYourself(), GetPhotons(), SetNeutronRP(), and SetTarget().
G4ParticleHPEnergyDistribution G4ParticleHPFSFissionFS::theDelayedNeutronEnDis private
Definition at line 107 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPFSFissionFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPFissionERelease G4ParticleHPFSFissionFS::theEnergyRelease private
Definition at line 111 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPFSFissionFS.hh
Referenced by GetEnergyRelease(), and Init().
G4ParticleHPParticleYield G4ParticleHPFSFissionFS::theFinalStateNeutrons private
Definition at line 105 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPFSFissionFS.hh
Referenced by ApplyYourself(), GetMass(), Init(), and SampleNeutronMult().
G4ParticleHPPhotonDist G4ParticleHPFSFissionFS::theFinalStatePhotons private
Definition at line 110 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPFSFissionFS.hh
Referenced by GetPhotons(), and Init().
G4ParticleHPNames G4ParticleHPFSFissionFS::theNames private
Definition at line 114 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPFSFissionFS.hh
Referenced by Init().
G4ParticleHPAngular G4ParticleHPFSFissionFS::theNeutronAngularDis private
Definition at line 108 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPFSFissionFS.hh
Referenced by ApplyYourself(), Init(), SetNeutronRP(), and SetTarget().
G4ParticleHPEnergyDistribution G4ParticleHPFSFissionFS::thePromptNeutronEnDis private
Definition at line 106 of file G4ParticleHPFSFissionFS.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPFSFissionFS.hh
Referenced by ApplyYourself(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFSFissionFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPFSFissionFS.cc