ECCE @ EIC Software: G4ImportanceAlgorithm Class Reference
G4ImportanceAlgorithm Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4ImportanceAlgorithm.hh>
Public Member Functions
G4ImportanceAlgorithm ()
virtual ~G4ImportanceAlgorithm ()
virtual G4Nsplit_Weight Calculate (G4double ipre, G4double ipost, G4double init_w) const
Public Member Functions inherited from G4VImportanceAlgorithm
G4VImportanceAlgorithm ()
virtual ~G4VImportanceAlgorithm ()
Private Member Functions
void Error (const G4String &m) const
void Warning (const G4String &m) const
Private Attributes
G4bool fWarned = false
Detailed Description
Definition at line 40 of file G4ImportanceAlgorithm.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ImportanceAlgorithm.hh
Constructor & Destructor Documentation
G4ImportanceAlgorithm::G4ImportanceAlgorithm ()
Definition at line 42 of file G4ImportanceAlgorithm.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ImportanceAlgorithm.cc
G4ImportanceAlgorithm::~G4ImportanceAlgorithm () virtual
Definition at line 46 of file G4ImportanceAlgorithm.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ImportanceAlgorithm.cc
Member Function Documentation
G4Nsplit_Weight G4ImportanceAlgorithm::Calculate (G4double ipre, G4double ipost, G4double init_w) const virtual
Implements G4VImportanceAlgorithm.
Definition at line 51 of file G4ImportanceAlgorithm.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ImportanceAlgorithm.cc
References Error(), G4Nsplit_Weight::fN, G4Nsplit_Weight::fW, fWarned, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4UniformRand, r, and Warning().
void G4ImportanceAlgorithm::Error (const G4String & m) const private
Definition at line 132 of file G4ImportanceAlgorithm.cc.
View newest version in sPHENIX GitHub at line 132 of file G4ImportanceAlgorithm.cc
References FatalException, and G4Exception().
Referenced by Calculate().
void G4ImportanceAlgorithm::Warning (const G4String & m) const private
Definition at line 138 of file G4ImportanceAlgorithm.cc.
View newest version in sPHENIX GitHub at line 138 of file G4ImportanceAlgorithm.cc
References G4Exception(), and JustWarning.
Referenced by Calculate().
Member Data Documentation
G4bool G4ImportanceAlgorithm::fWarned = false mutable private
Definition at line 63 of file G4ImportanceAlgorithm.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ImportanceAlgorithm.hh
Referenced by Calculate().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4ImportanceAlgorithm.hh
geant4/tree/geant4-10.6-release/source/geometry/biasing/src/G4ImportanceAlgorithm.cc