ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/PoPs.h File Reference
PoPs.h File Reference
#include <statusMessageReporting.h>
Classes
struct PoP_s
Macros
#define POPS_VERSION_MAJOR 1
#define POPS_VERSION_MINOR 0
#define POPS_VERSION_PATCHLEVEL 5
#define PoPs_packageSymbol "PoPs (properties of particles)"
#define PoPs_packageName PoPs_packageSymbol " (properties of particles)"
Typedefs
typedef struct PoP_s PoP
Enumerations
enum PoPs_errorTokens { PoPs_errorToken_Okay, PoPs_errorToken_badName, PoPs_errorToken_badIndex, PoPs_errorToken_badUnitConversion }
enum PoPs_genre {
PoPs_genre_invalid, PoPs_genre_unknown, PoPs_genre_alias, PoPs_genre_photon,
PoPs_genre_lepton, PoPs_genre_quark, PoPs_genre_meson, PoPs_genre_baryon,
PoPs_genre_nucleus, PoPs_genre_atom
}
Functions
const char * PoPs_version (void)
int PoPs_versionMajor (void)
int PoPs_versionMinor (void)
int PoPs_versionPatchLevel (void)
int PoPs_register (void)
int PoPs_readDatabase (statusMessageReporting *smr, char const *fileName)
int PoPs_release (statusMessageReporting *smr)
PoP * PoPs_addParticleIfNeeded (statusMessageReporting *smr, PoP *pop)
PoP * PoPs_copyAddParticleIfNeeded (statusMessageReporting *smr, PoP *pop)
PoP * PoPs_addAliasIfNeeded (statusMessageReporting *smr, char const *name, char const *alias)
int PoPs_numberOfParticle (void)
int PoPs_particleIndex (char const *name)
int PoPs_particleIndex_smr (statusMessageReporting *smr, char const *name, char const *file, int line, char const *func)
char const * PoPs_getName_atIndex (statusMessageReporting *smr, int index)
double PoPs_getMassInUnitOf (statusMessageReporting *smr, char const *name, char const *unit)
double PoPs_getMassInUnitOf_atIndex (statusMessageReporting *smr, int index, char const *unit)
enum PoPs_genre PoPs_getGenre (statusMessageReporting *smr, char const *name)
enum PoPs_genre PoPs_getGenre_atIndex (statusMessageReporting *smr, int index)
int PoPs_getZ_A_l (statusMessageReporting *smr, char const *name, int *Z, int *A, int *l)
int PoPs_getZ_A_l_atIndex (statusMessageReporting *smr, int index, int *Z, int *A, int *l)
int PoPs_hasNucleus (statusMessageReporting *smr, char const *name, int protonIsNucleus)
int PoPs_hasNucleus_atIndex (statusMessageReporting *smr, int index, int protonIsNucleus)
char const * PoPs_getAtomsName (statusMessageReporting *smr, char const *name)
char const * PoPs_getAtomsName_atIndex (statusMessageReporting *smr, int index)
int PoPs_getAtomsIndex (statusMessageReporting *smr, char const *name)
int PoPs_getAtomsIndex_atIndex (statusMessageReporting *smr, int index)
PoP * PoPs_getParticle_atIndex (int index)
char const * PoPs_genreTokenToString (enum PoPs_genre genre)
void PoPs_print (int sorted)
void PoPs_write (FILE *f, int sorted)
PoP * PoP_new (statusMessageReporting *smr)
int PoP_initialize (statusMessageReporting *smr, PoP *pop)
int PoP_release (PoP *pop)
PoP * PoP_free (PoP *pop)
int PoP_copyParticle (statusMessageReporting *smr, PoP *desc, PoP *src)
PoP * PoP_makeParticle (statusMessageReporting *smr, enum PoPs_genre genre, char const *name, double mass, char const *massUnit)
int PoP_setZ_A_l (statusMessageReporting *smr, PoP *pop, int Z, int A, int l)
int PoP_getIndex (PoP *pop)
char const * PoP_getName (PoP *pop)
int PoPs_particleReadDatabase (statusMessageReporting *smr, char const *name)
PoP * PoPs_particleCreateLoadInfo (statusMessageReporting *smr, const char *name)
int PoPs_particleLoadInfo (statusMessageReporting *smr, const char *name, PoP *pop)
double PoP_getMassInUnitOf (statusMessageReporting *smr, PoP *pop, char const *unit)
PoP * PoP_makeAlias (statusMessageReporting *smr, char const *name, char const *alias)
int PoPs_unitConversionRatio (char const *_from, char const *_to, double *ratio)
int lPoPs_addParticleIfNeeded (statusMessageReporting *smr, char const *name, char const *special)
int PoPs_setBDFLS_File (char const *name)
Variables
int PoPs_smr_ID
Macro Definition Documentation
#define PoPs_packageName PoPs_packageSymbol " (properties of particles)"
Definition at line 32 of file PoPs.h.
View newest version in sPHENIX GitHub at line 32 of file PoPs.h
#define PoPs_packageSymbol "PoPs (properties of particles)"
Definition at line 31 of file PoPs.h.
View newest version in sPHENIX GitHub at line 31 of file PoPs.h
#define POPS_VERSION_MAJOR 1
Definition at line 27 of file PoPs.h.
View newest version in sPHENIX GitHub at line 27 of file PoPs.h
Referenced by PoPs_version(), and PoPs_versionMajor().
#define POPS_VERSION_MINOR 0
Definition at line 28 of file PoPs.h.
View newest version in sPHENIX GitHub at line 28 of file PoPs.h
Referenced by PoPs_version(), and PoPs_versionMinor().
#define POPS_VERSION_PATCHLEVEL 5
Definition at line 29 of file PoPs.h.
View newest version in sPHENIX GitHub at line 29 of file PoPs.h
Referenced by PoPs_version(), and PoPs_versionPatchLevel().
Typedef Documentation
typedef struct PoP_s PoP
Definition at line 33 of file PoPs.h.
View newest version in sPHENIX GitHub at line 33 of file PoPs.h
Enumeration Type Documentation
enum PoPs_errorTokens
Enumerator:
PoPs_errorToken_Okay
PoPs_errorToken_badName
PoPs_errorToken_badIndex
PoPs_errorToken_badUnitConversion
Definition at line 35 of file PoPs.h.
View newest version in sPHENIX GitHub at line 35 of file PoPs.h
enum PoPs_genre
Enumerator:
PoPs_genre_invalid
PoPs_genre_unknown
PoPs_genre_alias
PoPs_genre_photon
PoPs_genre_lepton
PoPs_genre_quark
PoPs_genre_meson
PoPs_genre_baryon
PoPs_genre_nucleus
PoPs_genre_atom
Definition at line 36 of file PoPs.h.
View newest version in sPHENIX GitHub at line 36 of file PoPs.h
Function Documentation
int lPoPs_addParticleIfNeeded (statusMessageReporting * smr, char const * name, char const * special)
Definition at line 36 of file lPoPs.cc.
View newest version in sPHENIX GitHub at line 36 of file lPoPs.cc
References A(), PoP_s::index, int(), lPoPs_ZSymbol(), PoP_free(), PoP_makeAlias(), PoPs_addParticleIfNeeded(), PoPs_errorToken_badName, PoPs_particleCreateLoadInfo(), PoPs_particleIndex(), PoPs_smr_ID, smr_setReportError2, and Z.
Referenced by _MCGIDI_map_addEntry(), MCGIDI_map_findAllOfTarget(), MCGIDI_map_findTarget(), MCGIDI_map_initialize(), MCGIDI_POPs_addParticleIfNeeded(), and PoPs_particleReadDatabase().
int PoP_copyParticle (statusMessageReporting * smr, PoP * desc, PoP * src)
Definition at line 567 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 567 of file PoPs.cc
References PoP_s::A, PoP_s::aliasIndex, PoP_s::genre, PoP_s::index, PoP_s::l, PoP_s::mass, PoP_s::massUnit, PoP_s::name, PoP_s::properIndex, smr_allocateCopyString2, and PoP_s::Z.
Referenced by PoPs_copyAddParticleIfNeeded().
PoP* PoP_free (PoP * pop)
Definition at line 558 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 558 of file PoPs.cc
References PoP_release(), and smr_freeMemory().
Referenced by lPoPs_addParticleIfNeeded(), PoP_makeAlias(), PoP_makeParticle(), PoP_new(), PoPs_addAliasIfNeeded(), PoPs_copyAddParticleIfNeeded(), PoPs_particleCreateLoadInfo(), PoPs_particleReadDatabase(), and PoPs_releasePrivate().
int PoP_getIndex (PoP * pop)
Definition at line 612 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 612 of file PoPs.cc
References PoP_s::index.
double PoP_getMassInUnitOf (statusMessageReporting * smr, PoP * pop, char const * unit)
Definition at line 626 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 626 of file PoPs.cc
References mass, PoP_s::mass, PoP_s::massUnit, PoPs_errorToken_badUnitConversion, PoPs_smr_ID, PoPs_unitConversionRatio(), ratio, and smr_setReportError2.
Referenced by PoPs_getMassInUnitOf_atIndex().
char const* PoP_getName (PoP * pop)
Definition at line 619 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 619 of file PoPs.cc
References PoP_s::name.
int PoP_initialize (statusMessageReporting * smr, PoP * pop)
Definition at line 533 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 533 of file PoPs.cc
References PoP_s::A, PoP_s::aliasIndex, PoP_s::genre, PoP_s::index, PoP_s::mass, PoP_s::massUnit, PoP_s::name, PoPs_genre_unknown, PoP_s::properIndex, and PoP_s::Z.
Referenced by PoP_new(), and PoP_release().
PoP* PoP_makeAlias (statusMessageReporting * smr, char const * name, char const * alias)
Definition at line 647 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 647 of file PoPs.cc
References PoP_s::aliasIndex, PoP_s::genre, PoP_s::name, PoP_free(), PoP_new(), PoPs_s::pops, PoPs_errorToken_badName, PoPs_genre_alias, PoPs_particleIndex(), PoPs_smr_ID, popsRoot, PoP_s::properIndex, smr_allocateCopyString2, and smr_setReportError2.
Referenced by lPoPs_addParticleIfNeeded(), and PoPs_addAliasIfNeeded().
PoP* PoP_makeParticle (statusMessageReporting * smr, enum PoPs_genre genre, char const * name, double mass, char const * massUnit)
Definition at line 585 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 585 of file PoPs.cc
References PoP_s::genre, mass, PoP_s::mass, PoP_s::massUnit, PoP_s::name, PoP_free(), PoP_new(), smr_allocateCopyString2, and unitsDB_addUnitIfNeeded().
PoP* PoP_new (statusMessageReporting * smr)
Definition at line 522 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 522 of file PoPs.cc
References PoP_free(), PoP_initialize(), and smr_malloc2.
Referenced by PoP_makeAlias(), PoP_makeParticle(), and PoPs_particleCreateLoadInfo().
int PoP_release (PoP * pop)
Definition at line 549 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 549 of file PoPs.cc
References PoP_s::name, PoP_initialize(), and smr_freeMemory().
Referenced by PoP_free().
int PoP_setZ_A_l (statusMessageReporting * smr, PoP * pop, int Z, int A, int l)
Definition at line 602 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 602 of file PoPs.cc
References PoP_s::A, A(), PoP_s::l, Z, and PoP_s::Z.
PoP* PoPs_addAliasIfNeeded (statusMessageReporting * smr, char const * name, char const * alias)
Definition at line 179 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 179 of file PoPs.cc
References PoP_s::index, PoP_free(), PoP_makeAlias(), and PoPs_addParticleIfNeeded().
Referenced by MCGIDI_map_initialize().
PoP* PoPs_addParticleIfNeeded (statusMessageReporting * smr, PoP * pop)
Definition at line 113 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 113 of file PoPs.cc
References PoP_s::aliasIndex, PoPs_s::allocated, PoP_s::genre, incrementalSize, PoP_s::index, PoP_s::name, PoPs_s::numberOfParticles, PoPs_s::pops, PoPs_genre_alias, PoPs_particleProperIndex(), PoPs_sortedParticleIndex(), popsRoot, PoP_s::properIndex, smr_freeMemory(), smr_malloc2, and PoPs_s::sorted.
Referenced by lPoPs_addParticleIfNeeded(), PoPs_addAliasIfNeeded(), PoPs_copyAddParticleIfNeeded(), and PoPs_particleReadDatabase().
PoP* PoPs_copyAddParticleIfNeeded (statusMessageReporting * smr, PoP * pop)
Definition at line 153 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 153 of file PoPs.cc
References PoP_s::name, PoP_copyParticle(), PoP_free(), PoPs_s::pops, PoPs_addParticleIfNeeded(), PoPs_particleIndex(), popsRoot, smr_freeMemory(), and smr_malloc2.
char const* PoPs_genreTokenToString (enum PoPs_genre genre)
Definition at line 446 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 446 of file PoPs.cc
References PoPs_genre_atom, PoPs_genre_invalid, and PoPs_genreStrings.
Referenced by PoPs_write().
int PoPs_getAtomsIndex (statusMessageReporting * smr, char const * name)
Definition at line 397 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 397 of file PoPs.cc
References PoPs_getAtomsIndex_atIndex(), and PoPs_particleIndex_smr().
int PoPs_getAtomsIndex_atIndex (statusMessageReporting * smr, int index)
Definition at line 407 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 407 of file PoPs.cc
References PoP_s::genre, PoP_s::name, PoPs_s::numberOfParticles, PoPs_s::pops, PoPs_errorToken_badIndex, PoPs_genre_atom, PoPs_genre_nucleus, PoPs_particleIndex_smr(), PoPs_smr_ID, popsRoot, and smr_setReportError2.
Referenced by PoPs_getAtomsIndex(), and PoPs_getAtomsName_atIndex().
char const* PoPs_getAtomsName (statusMessageReporting * smr, char const * name)
Definition at line 377 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 377 of file PoPs.cc
References PoPs_getAtomsName_atIndex(), and PoPs_particleIndex_smr().
char const* PoPs_getAtomsName_atIndex (statusMessageReporting * smr, int index)
Definition at line 387 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 387 of file PoPs.cc
References PoP_s::name, PoPs_s::pops, PoPs_getAtomsIndex_atIndex(), and popsRoot.
Referenced by PoPs_getAtomsName().
enum PoPs_genre PoPs_getGenre (statusMessageReporting * smr, char const * name)
Definition at line 301 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 301 of file PoPs.cc
References PoP_s::genre, PoPs_s::pops, PoPs_genre_invalid, PoPs_particleIndex_smr(), and popsRoot.
enum PoPs_genre PoPs_getGenre_atIndex (statusMessageReporting * smr, int index)
Definition at line 311 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 311 of file PoPs.cc
References PoP_s::genre, PoPs_s::numberOfParticles, PoPs_s::pops, PoPs_errorToken_badIndex, PoPs_genre_invalid, PoPs_smr_ID, popsRoot, and smr_setReportError2.
double PoPs_getMassInUnitOf (statusMessageReporting * smr, char const * name, char const * unit)
Definition at line 265 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 265 of file PoPs.cc
References PoPs_getMassInUnitOf_atIndex(), and PoPs_particleIndex_smr().
double PoPs_getMassInUnitOf_atIndex (statusMessageReporting * smr, int index, char const * unit)
Definition at line 286 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 286 of file PoPs.cc
References mass, PoPs_s::numberOfParticles, PoP_getMassInUnitOf(), PoPs_s::pops, PoPs_errorToken_badIndex, PoPs_smr_ID, popsRoot, and smr_setReportError2.
Referenced by PoPs_getMassInUnitOf().
char const* PoPs_getName_atIndex (statusMessageReporting * smr, int index)
Definition at line 275 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 275 of file PoPs.cc
References PoP_s::name, PoPs_s::numberOfParticles, PoPs_s::pops, PoPs_errorToken_badIndex, PoPs_smr_ID, popsRoot, and smr_setReportError2.
Referenced by MCGIDI_map_findTargetViaPoPIDs().
PoP* PoPs_getParticle_atIndex (int index)
Definition at line 438 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 438 of file PoPs.cc
References PoPs_s::numberOfParticles, PoPs_s::pops, and popsRoot.
int PoPs_getZ_A_l (statusMessageReporting * smr, char const * name, int * Z, int * A, int * l)
Definition at line 325 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 325 of file PoPs.cc
References PoPs_getZ_A_l_atIndex(), and PoPs_particleIndex_smr().
int PoPs_getZ_A_l_atIndex (statusMessageReporting * smr, int index, int * Z, int * A, int * l)
Definition at line 335 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 335 of file PoPs.cc
References PoP_s::A, PoPs_s::numberOfParticles, PoPs_s::pops, PoPs_errorToken_badIndex, PoPs_smr_ID, popsRoot, smr_setReportError2, and PoP_s::Z.
Referenced by PoPs_getZ_A_l().
int PoPs_hasNucleus (statusMessageReporting * smr, char const * name, int protonIsNucleus)
Definition at line 349 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 349 of file PoPs.cc
References PoPs_hasNucleus_atIndex(), and PoPs_particleIndex_smr().
Referenced by PoPs_write().
int PoPs_hasNucleus_atIndex (statusMessageReporting * smr, int index, int protonIsNucleus)
Definition at line 359 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 359 of file PoPs.cc
References PoP_s::genre, PoP_s::name, PoPs_s::numberOfParticles, PoPs_s::pops, PoPs_errorToken_badIndex, PoPs_genre_atom, PoPs_genre_nucleus, PoPs_smr_ID, popsRoot, and smr_setReportError2.
Referenced by PoPs_hasNucleus().
int PoPs_numberOfParticle (void)
Definition at line 197 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 197 of file PoPs.cc
References PoPs_s::numberOfParticles, and popsRoot.
PoP* PoPs_particleCreateLoadInfo (statusMessageReporting * smr, const char * name)
Definition at line 61 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 61 of file PoPs_data.cc
References PoP_free(), PoP_new(), and PoPs_particleLoadInfo().
Referenced by lPoPs_addParticleIfNeeded(), and PoPs_particleReadDatabase().
int PoPs_particleIndex (char const * name)
Definition at line 204 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 204 of file PoPs.cc
References PoP_s::index, PoPs_particleProperIndex(), PoPs_sortedParticleIndex(), popsRoot, and PoPs_s::sorted.
Referenced by lPoPs_addParticleIfNeeded(), MCGIDI_reaction_ParseDetermineReactionProducts(), MCGIDI_reaction_particleChanges(), PoP_makeAlias(), PoPs_copyAddParticleIfNeeded(), and PoPs_particleIndex_smr().
int PoPs_particleIndex_smr (statusMessageReporting * smr, char const * name, char const * file, int line, char const * func)
Definition at line 216 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 216 of file PoPs.cc
References PoPs_errorToken_badName, PoPs_particleIndex(), PoPs_smr_ID, and smr_setReportError().
Referenced by PoPs_getAtomsIndex(), PoPs_getAtomsIndex_atIndex(), PoPs_getAtomsName(), PoPs_getGenre(), PoPs_getMassInUnitOf(), PoPs_getZ_A_l(), and PoPs_hasNucleus().
int PoPs_particleLoadInfo (statusMessageReporting * smr, const char * name, PoP * pop)
Definition at line 73 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 73 of file PoPs_data.cc
References PoP_s::A, PoP_s::genre, PoPDatas::genre, PoP_s::l, mass, PoP_s::mass, PoP_s::massUnit, n, N, PoPDatas::N, PoP_s::name, PoPDatas::nuclearLevel, PoPDatas, PoPs_getBDFLS_mass(), smr_allocateCopyString2, smr_freeMemory(), smr_setReportError2, smr_unknownID, unitsDB_addUnitIfNeeded(), PoP_s::Z, and PoPDatas::Z.
Referenced by PoPs_particleCreateLoadInfo().
int PoPs_particleReadDatabase (statusMessageReporting * smr, char const * name)
Definition at line 36 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 36 of file PoPs_data.cc
References PoP_s::A, PoP_s::genre, lPoPs_addParticleIfNeeded(), n1, PoP_free(), PoPDatas, PoPs_addParticleIfNeeded(), PoPs_genre_atom, PoPs_particleCreateLoadInfo(), smr_isOk(), and PoP_s::Z.
Referenced by PoPs_readDatabase().
void PoPs_print (int sorted)
Definition at line 455 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 455 of file PoPs.cc
References PoPs_write().
int PoPs_readDatabase (statusMessageReporting * smr, char const * fileName)
Definition at line 81 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 81 of file PoPs.cc
References PoPs_particleReadDatabase().
int PoPs_register (void)
Definition at line 73 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 73 of file PoPs.cc
References referenceCount.
int PoPs_release (statusMessageReporting * smr)
Definition at line 88 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 88 of file PoPs.cc
References PoPs_releasePrivate(), and referenceCount.
int PoPs_setBDFLS_File (char const * name)
Definition at line 121 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 121 of file PoPs_data.cc
References BDFLS_Data.
int PoPs_unitConversionRatio (char const * _from, char const * _to, double * ratio)
Definition at line 748 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 748 of file PoPs.cc
References conversions, n, and unitConversions_s::ratio.
Referenced by PoP_getMassInUnitOf().
const char* PoPs_version (void)
Definition at line 59 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 59 of file PoPs.cc
References POPS_VERSION_MAJOR, POPS_VERSION_MINOR, POPS_VERSION_PATCHLEVEL, and versionStr.
int PoPs_versionMajor (void)
Definition at line 67 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 67 of file PoPs.cc
References POPS_VERSION_MAJOR.
int PoPs_versionMinor (void)
Definition at line 68 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 68 of file PoPs.cc
References POPS_VERSION_MINOR.
int PoPs_versionPatchLevel (void)
Definition at line 69 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 69 of file PoPs.cc
References POPS_VERSION_PATCHLEVEL.
void PoPs_write (FILE * f, int sorted)
Definition at line 462 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 462 of file PoPs.cc
References PoP_s::A, PoP_s::aliasIndex, PoP_s::genre, PoP_s::index, PoP_s::l, PoP_s::mass, PoP_s::massUnit, PoP_s::name, PoPs_s::numberOfParticles, unitsDB_s::numberOfUnits, PoPs_s::pops, PoPs_genre_alias, PoPs_genreTokenToString(), PoPs_hasNucleus(), PoPs_particleProperIndex(), popsRoot, PoPs_s::sorted, unitsRoot, unitsDB_s::unsorted, and PoP_s::Z.
Referenced by PoPs_print().
Variable Documentation
int PoPs_smr_ID
Definition at line 35 of file PoPs.cc.
View newest version in sPHENIX GitHub at line 35 of file PoPs.cc
Referenced by lPoPs_addParticleIfNeeded(), PoP_getMassInUnitOf(), PoP_makeAlias(), PoPs_getAtomsIndex_atIndex(), PoPs_getGenre_atIndex(), PoPs_getMassInUnitOf_atIndex(), PoPs_getName_atIndex(), PoPs_getZ_A_l_atIndex(), PoPs_hasNucleus_atIndex(), PoPs_particleIndex_smr(), and unitsDB_stringFromIndex().