ECCE @ EIC Software: G4RootNtupleManager Class Reference
G4RootNtupleManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootNtupleManager.hh>
Public Member Functions
G4RootNtupleManager (const G4AnalysisManagerState &state, G4int nofMainManagers, G4bool rowWise, G4bool rowMode)
virtual ~G4RootNtupleManager ()
Public Member Functions inherited from G4TNtupleManager< tools::wroot::ntuple >
G4TNtupleManager (const G4AnalysisManagerState &state)
~G4TNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Types
using NtupleType = tools::wroot::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Private Member Functions
void SetNtupleDirectory (tools::wroot::directory *directory)
void SetFileManager (std::shared_ptr< G4RootFileManager > fileManager)
void CreateTNtuple (NtupleDescriptionType *ntupleDescription)
virtual void CreateTNtupleFromBooking (NtupleDescriptionType *ntupleDescription) final
virtual void FinishTNtuple (NtupleDescriptionType *ntupleDescription, G4bool fromBooking) final
virtual G4bool Reset (G4bool deleteNtuple)
virtual G4bool Merge ()
const std::vector
< NtupleDescriptionType * > & GetNtupleDescriptionVector () const
G4RootMainNtupleManager * GetMainNtupleManager (G4int index) const
unsigned int GetBasketSize () const
unsigned int GetBasketEntries () const
void SetCreateMode ()
void SetNtupleRowWise (G4bool rowWise, G4bool rowMode)
Private Attributes
G4NtupleCreateMode fCreateMode
std::shared_ptr
< G4RootFileManager > fFileManager
tools::wroot::directory * fNtupleDirectory
std::vector
< G4RootMainNtupleManager * > fMainNtupleManagers
G4bool fRowWise
G4bool fRowMode
Friends
class G4RootAnalysisManager
class G4RootMainNtupleManager
class G4RootMpiAnalysisManager
class G4RootMpiNtupleManager
Additional Inherited Members
Protected Member Functions inherited from G4TNtupleManager< tools::wroot::ntuple >
virtual void CreateNtuplesFromBooking ()
G4bool IsEmpty () const
virtual G4int CreateNtuple (const G4String &name, const G4String &title) override
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual void FinishNtuple (G4int ntupleId) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool AddNtupleRow (G4int ntupleId) override
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
tools::wroot::ntuple * GetNtuple () const
tools::wroot::ntuple * GetNtuple (G4int ntupleId) const
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const override
std::vector
< tools::wroot::ntuple * >
::iterator BeginNtuple ()
std::vector
< tools::wroot::ntuple * >
::iterator EndNtuple ()
std::vector
< tools::wroot::ntuple * >
::const_iterator BeginConstNtuple () const
std::vector
< tools::wroot::ntuple * >
::const_iterator EndConstNtuple () const
Protected Attributes inherited from G4TNtupleManager< tools::wroot::ntuple >
std::vector
< G4TNtupleDescription
< tools::wroot::ntuple > * > fNtupleDescriptionVector
std::vector
< tools::wroot::ntuple * > fNtupleVector
Detailed Description
Definition at line 65 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RootNtupleManager.hh
Member Typedef Documentation
using G4RootNtupleManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType> private
Definition at line 81 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RootNtupleManager.hh
using G4RootNtupleManager::NtupleType = tools::wroot::ntuple private
Definition at line 80 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RootNtupleManager.hh
Constructor & Destructor Documentation
G4RootNtupleManager::G4RootNtupleManager (const G4AnalysisManagerState & state, G4int nofMainManagers, G4bool rowWise, G4bool rowMode) explicit
Definition at line 40 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 40 of file G4RootNtupleManager.cc
References fMainNtupleManagers, G4BaseAnalysisManager::fState, and G4RootMainNtupleManager.
G4RootNtupleManager::~G4RootNtupleManager () virtual
Definition at line 58 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RootNtupleManager.cc
Member Function Documentation
void G4RootNtupleManager::CreateTNtuple (NtupleDescriptionType * ntupleDescription) private
Definition at line 133 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 133 of file G4RootNtupleManager.cc
References fFileManager, G4TNtupleDescription< TNTUPLE >::fIsNtupleOwner, G4TNtupleDescription< TNTUPLE >::fNtuple, G4TNtupleDescription< TNTUPLE >::fNtupleBooking, fNtupleDirectory, G4TNtupleManager< tools::wroot::ntuple >::fNtupleVector, fRowWise, G4endl, G4Exception(), JustWarning, and ntuple.
Referenced by CreateTNtupleFromBooking(), and FinishTNtuple().
void G4RootNtupleManager::CreateTNtupleFromBooking (NtupleDescriptionType * ntupleDescription) final private virtual
Definition at line 158 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 158 of file G4RootNtupleManager.cc
References CreateTNtuple(), fCreateMode, fFileManager, and fMainNtupleManagers.
void G4RootNtupleManager::FinishTNtuple (NtupleDescriptionType * ntupleDescription, G4bool fromBooking) final private virtual
Definition at line 180 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 180 of file G4RootNtupleManager.cc
References CreateTNtuple(), fCreateMode, fFileManager, fMainNtupleManagers, G4TNtupleDescription< TNTUPLE >::fNtupleBooking, and SetCreateMode().
unsigned int G4RootNtupleManager::GetBasketEntries () const private
Definition at line 270 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 270 of file G4RootNtupleManager.cc
References fFileManager, G4Exception(), and JustWarning.
Referenced by G4RootMainNtupleManager::GetBasketEntries().
unsigned int G4RootNtupleManager::GetBasketSize () const private
Definition at line 256 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 256 of file G4RootNtupleManager.cc
References fFileManager, G4Exception(), and JustWarning.
Referenced by G4RootMainNtupleManager::CreateNtuple().
G4RootMainNtupleManager * G4RootNtupleManager::GetMainNtupleManager (G4int index) const private
Definition at line 242 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 242 of file G4RootNtupleManager.cc
References fMainNtupleManagers, G4Exception(), and JustWarning.
Referenced by G4RootAnalysisManager::CreateNtupleManagers().
const std::vector< G4TNtupleDescription< tools::wroot::ntuple > * > & G4RootNtupleManager::GetNtupleDescriptionVector () const inline private
Definition at line 139 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 139 of file G4RootNtupleManager.hh
References G4TNtupleManager< tools::wroot::ntuple >::fNtupleDescriptionVector.
Referenced by G4RootMainNtupleManager::CreateNtuplesFromBooking(), and G4RootMainNtupleManager::GetNtupleDescriptionVector().
G4bool G4RootNtupleManager::Merge () private virtual
Reimplemented in G4RootMpiNtupleManager.
Definition at line 229 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 229 of file G4RootNtupleManager.cc
References fMainNtupleManagers.
Referenced by G4RootMpiAnalysisManager::WriteNtuple(), and G4RootAnalysisManager::WriteNtuple().
G4bool G4RootNtupleManager::Reset (G4bool deleteNtuple) private virtual
Reimplemented from G4TNtupleManager< tools::wroot::ntuple >.
Definition at line 209 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 209 of file G4RootNtupleManager.cc
References fCreateMode, fMainNtupleManagers, G4TNtupleManager< tools::wroot::ntuple >::fNtupleDescriptionVector, and G4TNtupleManager< TNTUPLE >::Reset().
Referenced by G4RootMpiAnalysisManager::Reset(), and G4RootAnalysisManager::ResetNtuple().
void G4RootNtupleManager::SetCreateMode () private
Definition at line 66 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 66 of file G4RootNtupleManager.cc
References fCreateMode, fFileManager, fMainNtupleManagers, fNtupleDirectory, G4BaseAnalysisManager::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), kUndefined, and G4AnalysisVerbose::Message().
Referenced by FinishTNtuple().
void G4RootNtupleManager::SetFileManager (std::shared_ptr< G4RootFileManager > fileManager) inline private
Definition at line 135 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 135 of file G4RootNtupleManager.hh
References fFileManager.
Referenced by G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), and G4RootAnalysisManager::CreateNtupleManagers().
void G4RootNtupleManager::SetNtupleDirectory (tools::wroot::directory * directory) inline private
Definition at line 131 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 131 of file G4RootNtupleManager.hh
References fNtupleDirectory.
Referenced by G4RootMpiAnalysisManager::OpenFileImpl(), and G4RootAnalysisManager::OpenFileImpl().
void G4RootNtupleManager::SetNtupleRowWise (G4bool rowWise, G4bool rowMode) private
Definition at line 119 of file G4RootNtupleManager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4RootNtupleManager.cc
References fMainNtupleManagers, fRowMode, and fRowWise.
Referenced by G4RootAnalysisManager::SetNtupleRowWise().
Friends And Related Function Documentation
friend class G4RootAnalysisManager friend
Definition at line 67 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RootNtupleManager.hh
friend class G4RootMainNtupleManager friend
Definition at line 68 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RootNtupleManager.hh
Referenced by G4RootNtupleManager().
friend class G4RootMpiAnalysisManager friend
Definition at line 69 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RootNtupleManager.hh
friend class G4RootMpiNtupleManager friend
Definition at line 70 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RootNtupleManager.hh
Member Data Documentation
G4NtupleCreateMode G4RootNtupleManager::fCreateMode private
Definition at line 120 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4RootNtupleManager.hh
Referenced by CreateTNtupleFromBooking(), FinishTNtuple(), Reset(), and SetCreateMode().
std::shared_ptr<G4RootFileManager> G4RootNtupleManager::fFileManager private
Definition at line 121 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4RootNtupleManager.hh
Referenced by CreateTNtuple(), CreateTNtupleFromBooking(), FinishTNtuple(), GetBasketEntries(), GetBasketSize(), G4RootMpiNtupleManager::Send(), SetCreateMode(), and SetFileManager().
std::vector<G4RootMainNtupleManager*> G4RootNtupleManager::fMainNtupleManagers private
Definition at line 123 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4RootNtupleManager.hh
Referenced by CreateTNtupleFromBooking(), FinishTNtuple(), G4RootNtupleManager(), GetMainNtupleManager(), Merge(), Reset(), SetCreateMode(), and SetNtupleRowWise().
tools::wroot::directory* G4RootNtupleManager::fNtupleDirectory private
Definition at line 122 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 122 of file G4RootNtupleManager.hh
Referenced by CreateTNtuple(), SetCreateMode(), and SetNtupleDirectory().
G4bool G4RootNtupleManager::fRowMode private
Definition at line 125 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 125 of file G4RootNtupleManager.hh
Referenced by G4RootMpiNtupleManager::Send(), and SetNtupleRowWise().
G4bool G4RootNtupleManager::fRowWise private
Definition at line 124 of file G4RootNtupleManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RootNtupleManager.hh
Referenced by CreateTNtuple(), G4RootMpiNtupleManager::Send(), and SetNtupleRowWise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/root/src/G4RootNtupleManager.cc