ECCE @ EIC Software: G4tgrFileIn Class Reference
G4tgrFileIn Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrFileIn.hh>
Public Member Functions
G4tgrFileIn ()
~G4tgrFileIn ()
G4int GetWordsInLine (std::vector< G4String > &wl)
void ErrorInLine ()
G4int Nline ()
const G4String & GetName ()
void OpenNewFile (const char *filename)
G4bool EndOfFile ()
void Close ()
void DumpException (const G4String &sent)
Static Public Member Functions
static G4tgrFileIn & GetInstance (const G4String &name)
static G4tgrFileIn & GetInstanceOpened (const G4String &name)
Private Member Functions
G4tgrFileIn (const G4String &name)
Private Attributes
std::vector< std::ifstream * > theFiles
std::vector< G4int > theLineNo
std::vector< G4String > theNames
G4int theCurrentFile
G4String theName
Static Private Attributes
static G4ThreadLocal
std::vector< G4tgrFileIn * > * theInstances = 0
Detailed Description
Definition at line 45 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 45 of file G4tgrFileIn.hh
Constructor & Destructor Documentation
G4tgrFileIn::G4tgrFileIn ()
Definition at line 49 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgrFileIn.cc
References theInstances.
Referenced by GetInstance().
G4tgrFileIn::~G4tgrFileIn ()
Definition at line 57 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgrFileIn.cc
References theInstances.
G4tgrFileIn::G4tgrFileIn (const G4String & name) inline private
Definition at line 77 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 77 of file G4tgrFileIn.hh
Member Function Documentation
void G4tgrFileIn::Close ()
Definition at line 415 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 415 of file G4tgrFileIn.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), theCurrentFile, and theFiles.
Referenced by EndOfFile().
void G4tgrFileIn::DumpException (const G4String & sent)
Definition at line 431 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 431 of file G4tgrFileIn.cc
References G4UIcommand::ConvertToString(), FatalException, G4Exception(), theCurrentFile, theLineNo, and theName.
Referenced by GetWordsInLine(), and G4tgrFileReader::ReadFiles().
G4bool G4tgrFileIn::EndOfFile ()
Definition at line 376 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 376 of file G4tgrFileIn.cc
References Close(), G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), theCurrentFile, and theFiles.
Referenced by GetWordsInLine().
void G4tgrFileIn::ErrorInLine ()
Definition at line 367 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 367 of file G4tgrFileIn.cc
References G4cerr, theCurrentFile, theLineNo, and theNames.
Referenced by GetWordsInLine().
G4tgrFileIn & G4tgrFileIn::GetInstance (const G4String & name) static
Definition at line 71 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 71 of file G4tgrFileIn.cc
References INPUTHEPMC::filename, G4tgrFileIn(), instance, OpenNewFile(), theCurrentFile, and theInstances.
Referenced by DicomFileMgr::Convert(), GetInstanceOpened(), and G4tgrFileReader::ReadFiles().
G4tgrFileIn & G4tgrFileIn::GetInstanceOpened (const G4String & name) static
Definition at line 122 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 122 of file G4tgrFileIn.cc
References FatalException, INPUTHEPMC::filename, G4Exception(), GetInstance(), and GetName().
const G4String& G4tgrFileIn::GetName (void) inline
Definition at line 68 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgrFileIn.hh
References theName.
Referenced by GetInstanceOpened().
G4int G4tgrFileIn::GetWordsInLine (std::vector< G4String > & wl)
Definition at line 140 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 140 of file G4tgrFileIn.cc
References G4String::append(), DumpException(), EndOfFile(), check_license::err(), ErrorInLine(), FatalException, G4cout, G4endl, G4Exception(), G4tgrMessenger::GetVerboseLevel(), OpenNewFile(), theCurrentFile, theFiles, and theLineNo.
Referenced by DicomFileMgr::Convert(), and G4tgrFileReader::ReadFiles().
G4int G4tgrFileIn::Nline () inline
Definition at line 66 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgrFileIn.hh
References theCurrentFile, and theLineNo.
void G4tgrFileIn::OpenNewFile (const char * filename)
Definition at line 100 of file G4tgrFileIn.cc.
View newest version in sPHENIX GitHub at line 100 of file G4tgrFileIn.cc
References FatalException, fin, G4Exception(), theCurrentFile, theFiles, theLineNo, and theNames.
Referenced by GetInstance(), and GetWordsInLine().
Member Data Documentation
G4int G4tgrFileIn::theCurrentFile private
Definition at line 88 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 88 of file G4tgrFileIn.hh
Referenced by Close(), DumpException(), EndOfFile(), ErrorInLine(), GetInstance(), GetWordsInLine(), Nline(), and OpenNewFile().
std::vector< std::ifstream* > G4tgrFileIn::theFiles private
Definition at line 81 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 81 of file G4tgrFileIn.hh
Referenced by Close(), EndOfFile(), GetWordsInLine(), and OpenNewFile().
G4ThreadLocal std::vector< G4tgrFileIn * > * G4tgrFileIn::theInstances = 0 static private
Definition at line 91 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 91 of file G4tgrFileIn.hh
Referenced by G4tgrFileIn(), GetInstance(), and ~G4tgrFileIn().
std::vector<G4int> G4tgrFileIn::theLineNo private
Definition at line 83 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 83 of file G4tgrFileIn.hh
Referenced by DumpException(), ErrorInLine(), GetWordsInLine(), Nline(), and OpenNewFile().
G4String G4tgrFileIn::theName private
Definition at line 94 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 94 of file G4tgrFileIn.hh
Referenced by DumpException(), and GetName().
std::vector<G4String> G4tgrFileIn::theNames private
Definition at line 86 of file G4tgrFileIn.hh.
View newest version in sPHENIX GitHub at line 86 of file G4tgrFileIn.hh
Referenced by ErrorInLine(), and OpenNewFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrFileIn.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrFileIn.cc