ECCE @ EIC Software: F01PrimaryGeneratorAction Class Reference
F01PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01PrimaryGeneratorAction.hh>
Public Member Functions
F01PrimaryGeneratorAction (F01DetectorConstruction *)
virtual ~F01PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
void SetRndmFlag (G4String val)
void SetXVertex (G4double x)
void SetYVertex (G4double y)
void SetZVertex (G4double z)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Static Public Member Functions
static G4String GetPrimaryName ()
Private Attributes
G4ParticleGun * fParticleGun
F01DetectorConstruction * fDetector
F01PrimaryGeneratorMessenger * fGunMessenger
G4String fRndmFlag
G4double fXVertex
G4double fYVertex
G4double fZVertex
G4bool fVertexDefined
Static Private Attributes
static G4ParticleDefinition * fgPrimaryParticle = 0
Detailed Description
Definition at line 49 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 49 of file F01PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
F01PrimaryGeneratorAction::F01PrimaryGeneratorAction (F01DetectorConstruction * det)
Definition at line 55 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 55 of file F01PrimaryGeneratorAction.cc
References fDetector, fgPrimaryParticle, fGunMessenger, G4ParticleTable::FindParticle(), fParticleGun, fXVertex, fYVertex, fZVertex, F01DetectorConstruction::GetAbsorberThickness(), F01DetectorConstruction::GetAbsorberZpos(), G4ParticleTable::GetParticleTable(), GeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
F01PrimaryGeneratorAction::~F01PrimaryGeneratorAction () virtual
Definition at line 94 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 94 of file F01PrimaryGeneratorAction.cc
References fGunMessenger, and fParticleGun.
Member Function Documentation
void F01PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 102 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 102 of file F01PrimaryGeneratorAction.cc
References fDetector, fgPrimaryParticle, fParticleGun, fRndmFlag, fVertexDefined, fXVertex, fYVertex, fZVertex, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), F01DetectorConstruction::GetAbsorberRadius(), F01DetectorConstruction::GetAbsorberThickness(), F01DetectorConstruction::GetAbsorberZpos(), G4ParticleGun::GetParticleDefinition(), G4VPrimaryGenerator::SetParticlePosition(), twopi, and G4InuclParticleNames::z0.
G4String F01PrimaryGeneratorAction::GetPrimaryName () static
Definition at line 137 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 137 of file F01PrimaryGeneratorAction.cc
References fgPrimaryParticle, and G4ParticleDefinition::GetParticleName().
void F01PrimaryGeneratorAction::SetRndmFlag (G4String val) inline
Definition at line 57 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file F01PrimaryGeneratorAction.hh
References fRndmFlag.
Referenced by F01PrimaryGeneratorMessenger::SetNewValue().
void F01PrimaryGeneratorAction::SetXVertex (G4double x)
Definition at line 154 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 154 of file F01PrimaryGeneratorAction.cc
References fVertexDefined, fXVertex, G4cout, G4endl, mm, and x.
Referenced by F01PrimaryGeneratorMessenger::SetNewValue().
void F01PrimaryGeneratorAction::SetYVertex (G4double y)
Definition at line 164 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 164 of file F01PrimaryGeneratorAction.cc
References fVertexDefined, fYVertex, G4cout, G4endl, mm, and y.
Referenced by F01PrimaryGeneratorMessenger::SetNewValue().
void F01PrimaryGeneratorAction::SetZVertex (G4double z)
Definition at line 144 of file F01PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 144 of file F01PrimaryGeneratorAction.cc
References fVertexDefined, fZVertex, G4cout, G4endl, mm, and z.
Referenced by F01PrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
F01DetectorConstruction* F01PrimaryGeneratorAction::fDetector private
Definition at line 66 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), and GeneratePrimaries().
G4ParticleDefinition * F01PrimaryGeneratorAction::fgPrimaryParticle = 0 static private
Definition at line 71 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), GeneratePrimaries(), and GetPrimaryName().
F01PrimaryGeneratorMessenger* F01PrimaryGeneratorAction::fGunMessenger private
Definition at line 68 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), and ~F01PrimaryGeneratorAction().
G4ParticleGun* F01PrimaryGeneratorAction::fParticleGun private
Definition at line 65 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), GeneratePrimaries(), and ~F01PrimaryGeneratorAction().
G4String F01PrimaryGeneratorAction::fRndmFlag private
Definition at line 69 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file F01PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmFlag().
G4bool F01PrimaryGeneratorAction::fVertexDefined private
Definition at line 73 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file F01PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), SetXVertex(), SetYVertex(), and SetZVertex().
G4double F01PrimaryGeneratorAction::fXVertex private
Definition at line 72 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), GeneratePrimaries(), and SetXVertex().
G4double F01PrimaryGeneratorAction::fYVertex private
Definition at line 72 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), GeneratePrimaries(), and SetYVertex().
G4double F01PrimaryGeneratorAction::fZVertex private
Definition at line 72 of file F01PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file F01PrimaryGeneratorAction.hh
Referenced by F01PrimaryGeneratorAction(), GeneratePrimaries(), and SetZVertex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field01/src/F01PrimaryGeneratorAction.cc