ECCE @ EIC Software: G4PersistencyCenter Class Reference
G4PersistencyCenter Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4PersistencyCenter.hh>
Public Member Functions
void SelectSystem (std::string systemName)
const std::string CurrentSystem ()
void SetHepMCObjyReaderFile (std::string file)
std::string CurrentHepMCObjyReaderFile ()
void SetStoreMode (std::string objName, StoreMode mode)
void SetRetrieveMode (std::string objName, G4bool mode)
StoreMode CurrentStoreMode (std::string objName)
G4bool CurrentRetrieveMode (std::string objName)
G4bool SetWriteFile (std::string objName, std::string writeFileName)
G4bool SetReadFile (std::string objName, std::string readFileName)
std::string CurrentWriteFile (std::string objName)
std::string CurrentReadFile (std::string objName)
std::string CurrentObject (std::string file)
void AddHCIOmanager (std::string detName, std::string colName)
std::string CurrentHCIOmanager ()
void AddDCIOmanager (std::string detName)
std::string CurrentDCIOmanager ()
void PrintAll ()
G4PersistencyManager * CurrentPersistencyManager ()
void SetPersistencyManager (G4PersistencyManager *pm, std::string name)
G4PersistencyManager * GetPersistencyManager (std::string nam)
void RegisterPersistencyManager (G4PersistencyManager *pm)
void DeletePersistencyManager ()
void SetVerboseLevel (int v)
int VerboseLevel ()
Static Public Member Functions
static G4PersistencyCenter * GetPersistencyCenter ()
Private Member Functions
G4PersistencyCenter ()
~G4PersistencyCenter ()
std::string PadString (std::string name, unsigned int width)
Private Attributes
G4PersistencyCenterMessenger * f_theMessenger
G4PersistencyManager * f_currentManager
std::string f_currentSystemName
PMap f_theCatalog
ObjMap f_wrObj
ObjMap f_rdObj
FileMap f_writeFileName
FileMap f_readFileName
StoreMap f_writeFileMode
BoolMap f_readFileMode
G4int m_verbose
G4FileUtilities f_ut
Static Private Attributes
static G4ThreadLocal
G4PersistencyCenter * f_thePointer = 0
Detailed Description
Definition at line 63 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PersistencyCenter.hh
Constructor & Destructor Documentation
G4PersistencyCenter::G4PersistencyCenter () private
Definition at line 45 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 45 of file G4PersistencyCenter.cc
References f_currentManager, f_rdObj, f_readFileMode, f_readFileName, f_theMessenger, f_writeFileMode, f_writeFileName, f_wrObj, kOff, kOn, and kRecycle.
Referenced by GetPersistencyCenter().
G4PersistencyCenter::~G4PersistencyCenter () private
Definition at line 79 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PersistencyCenter.cc
References f_currentManager, and f_theMessenger.
Member Function Documentation
void G4PersistencyCenter::AddDCIOmanager (std::string detName)
Definition at line 282 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 282 of file G4PersistencyCenter.cc
References G4VDCIOentry::CreateDCIOmanager(), G4cerr, G4endl, G4DCIOcatalog::GetDCIOcatalog(), and G4DCIOcatalog::GetEntry().
void G4PersistencyCenter::AddHCIOmanager (std::string detName, std::string colName)
Definition at line 261 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 261 of file G4PersistencyCenter.cc
References G4VHCIOentry::CreateHCIOmanager(), G4cerr, G4endl, G4HCIOcatalog::GetEntry(), and G4HCIOcatalog::GetHCIOcatalog().
Referenced by G4PersistencyCenterMessenger::SetNewValue().
std::string G4PersistencyCenter::CurrentDCIOmanager ()
Definition at line 297 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 297 of file G4PersistencyCenter.cc
References G4DCIOcatalog::CurrentDCIOmanager(), and G4DCIOcatalog::GetDCIOcatalog().
std::string G4PersistencyCenter::CurrentHCIOmanager ()
Definition at line 275 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 275 of file G4PersistencyCenter.cc
References G4HCIOcatalog::CurrentHCIOmanager(), and G4HCIOcatalog::GetHCIOcatalog().
Referenced by G4PersistencyCenterMessenger::GetCurrentValue().
std::string G4PersistencyCenter::CurrentHepMCObjyReaderFile ()
Definition at line 145 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 145 of file G4PersistencyCenter.cc
References CurrentReadFile(), and CurrentRetrieveMode().
std::string G4PersistencyCenter::CurrentObject (std::string file)
Definition at line 248 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 248 of file G4PersistencyCenter.cc
References f_readFileName, and f_writeFileName.
G4PersistencyManager* G4PersistencyCenter::CurrentPersistencyManager () inline
Definition at line 124 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PersistencyCenter.hh
References f_currentManager.
Referenced by G4PersistencyManager::GetPersistencyManager().
std::string G4PersistencyCenter::CurrentReadFile (std::string objName)
Definition at line 238 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 238 of file G4PersistencyCenter.cc
References f_readFileName.
Referenced by CurrentHepMCObjyReaderFile(), G4PersistencyCenterMessenger::GetCurrentValue(), PrintAll(), and G4PersistencyManager::Retrieve().
G4bool G4PersistencyCenter::CurrentRetrieveMode (std::string objName)
Definition at line 187 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 187 of file G4PersistencyCenter.cc
References f_readFileMode, and f_readFileName.
Referenced by CurrentHepMCObjyReaderFile(), PrintAll(), and G4PersistencyManager::Retrieve().
StoreMode G4PersistencyCenter::CurrentStoreMode (std::string objName)
Definition at line 177 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 177 of file G4PersistencyCenter.cc
References f_writeFileMode, f_writeFileName, and kOff.
Referenced by G4PersistencyCenterMessenger::GetCurrentValue(), PrintAll(), and G4PersistencyManager::Store().
const std::string G4PersistencyCenter::CurrentSystem () inline
Definition at line 73 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PersistencyCenter.hh
References f_currentSystemName.
Referenced by G4PersistencyCenterMessenger::GetCurrentValue(), and PrintAll().
std::string G4PersistencyCenter::CurrentWriteFile (std::string objName)
Definition at line 228 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 228 of file G4PersistencyCenter.cc
References f_writeFileName.
Referenced by G4PersistencyCenterMessenger::GetCurrentValue(), PrintAll(), and G4PersistencyManager::Store().
void G4PersistencyCenter::DeletePersistencyManager ()
Definition at line 397 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 397 of file G4PersistencyCenter.cc
References f_currentManager.
G4PersistencyCenter * G4PersistencyCenter::GetPersistencyCenter () static
Definition at line 86 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 86 of file G4PersistencyCenter.cc
References f_thePointer, and G4PersistencyCenter().
Referenced by G4PersistencyManagerT< T >::G4PersistencyManagerT(), G4VDCIOentry::G4VDCIOentry(), G4VHCIOentry::G4VHCIOentry(), and G4PersistencyManager::GetPersistencyManager().
G4PersistencyManager * G4PersistencyCenter::GetPersistencyManager (std::string nam)
Definition at line 383 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 383 of file G4PersistencyCenter.cc
References f_theCatalog.
Referenced by SelectSystem().
std::string G4PersistencyCenter::PadString (std::string name, unsigned int width) private
Definition at line 411 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 411 of file G4PersistencyCenter.cc
Referenced by PrintAll().
void G4PersistencyCenter::PrintAll (void)
Definition at line 304 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 304 of file G4PersistencyCenter.cc
References CurrentReadFile(), CurrentRetrieveMode(), CurrentStoreMode(), CurrentSystem(), CurrentWriteFile(), f_rdObj, f_wrObj, file, G4cout, G4endl, G4DCIOcatalog::GetDCIOcatalog(), G4HCIOcatalog::GetHCIOcatalog(), kOff, kOn, kRecycle, PadString(), G4DCIOcatalog::PrintDCIOmanager(), G4DCIOcatalog::PrintEntries(), G4HCIOcatalog::PrintEntries(), and G4HCIOcatalog::PrintHCIOmanager().
Referenced by G4PersistencyCenterMessenger::SetNewValue().
void G4PersistencyCenter::RegisterPersistencyManager (G4PersistencyManager * pm)
Definition at line 391 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 391 of file G4PersistencyCenter.cc
References f_theCatalog, G4PersistencyManager::GetName(), and Acts::UnitConstants::pm.
void G4PersistencyCenter::SelectSystem (std::string systemName)
Definition at line 94 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 94 of file G4PersistencyCenter.cc
References G4PersistencyManager::Create(), f_currentManager, f_currentSystemName, G4cout, G4endl, GetPersistencyManager(), m_verbose, Acts::UnitConstants::pm, and G4PersistencyManager::SetVerboseLevel().
Referenced by G4PersistencyCenterMessenger::SetNewValue().
void G4PersistencyCenter::SetHepMCObjyReaderFile (std::string file)
Definition at line 137 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 137 of file G4PersistencyCenter.cc
References SetReadFile(), and SetRetrieveMode().
void G4PersistencyCenter::SetPersistencyManager (G4PersistencyManager * pm, std::string name)
Definition at line 375 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 375 of file G4PersistencyCenter.cc
References f_currentManager, f_currentSystemName, and Acts::UnitConstants::pm.
G4bool G4PersistencyCenter::SetReadFile (std::string objName, std::string readFileName)
Definition at line 210 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 210 of file G4PersistencyCenter.cc
References f_readFileName, f_ut, G4FileUtilities::FileExists(), G4cerr, and G4endl.
Referenced by SetHepMCObjyReaderFile().
void G4PersistencyCenter::SetRetrieveMode (std::string objName, G4bool mode)
Definition at line 166 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 166 of file G4PersistencyCenter.cc
References f_readFileMode, f_readFileName, G4cerr, and G4endl.
Referenced by SetHepMCObjyReaderFile().
void G4PersistencyCenter::SetStoreMode (std::string objName, StoreMode mode)
Definition at line 155 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 155 of file G4PersistencyCenter.cc
References f_writeFileMode, f_writeFileName, G4cerr, and G4endl.
Referenced by G4PersistencyCenterMessenger::SetNewValue().
void G4PersistencyCenter::SetVerboseLevel (int v)
Definition at line 404 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 404 of file G4PersistencyCenter.cc
References f_currentManager, m_verbose, G4PersistencyManager::SetVerboseLevel(), and v.
Referenced by G4PersistencyCenterMessenger::SetNewValue().
G4bool G4PersistencyCenter::SetWriteFile (std::string objName, std::string writeFileName)
Definition at line 197 of file G4PersistencyCenter.cc.
View newest version in sPHENIX GitHub at line 197 of file G4PersistencyCenter.cc
References f_writeFileName, G4cerr, and G4endl.
Referenced by G4PersistencyCenterMessenger::SetNewValue().
int G4PersistencyCenter::VerboseLevel () inline
Definition at line 142 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PersistencyCenter.hh
References m_verbose.
Referenced by G4PersistencyManager::G4PersistencyManager(), G4VDCIOentry::G4VDCIOentry(), G4VHCIOentry::G4VHCIOentry(), and G4PersistencyCenterMessenger::GetCurrentValue().
Member Data Documentation
G4PersistencyManager* G4PersistencyCenter::f_currentManager private
Definition at line 159 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 159 of file G4PersistencyCenter.hh
Referenced by CurrentPersistencyManager(), DeletePersistencyManager(), G4PersistencyCenter(), SelectSystem(), SetPersistencyManager(), SetVerboseLevel(), and ~G4PersistencyCenter().
std::string G4PersistencyCenter::f_currentSystemName private
Definition at line 160 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 160 of file G4PersistencyCenter.hh
Referenced by CurrentSystem(), SelectSystem(), and SetPersistencyManager().
ObjMap G4PersistencyCenter::f_rdObj private
Definition at line 163 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 163 of file G4PersistencyCenter.hh
Referenced by G4PersistencyCenter(), and PrintAll().
BoolMap G4PersistencyCenter::f_readFileMode private
Definition at line 167 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 167 of file G4PersistencyCenter.hh
Referenced by CurrentRetrieveMode(), G4PersistencyCenter(), and SetRetrieveMode().
FileMap G4PersistencyCenter::f_readFileName private
Definition at line 165 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 165 of file G4PersistencyCenter.hh
Referenced by CurrentObject(), CurrentReadFile(), CurrentRetrieveMode(), G4PersistencyCenter(), SetReadFile(), and SetRetrieveMode().
PMap G4PersistencyCenter::f_theCatalog private
Definition at line 161 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 161 of file G4PersistencyCenter.hh
Referenced by GetPersistencyManager(), and RegisterPersistencyManager().
G4PersistencyCenterMessenger* G4PersistencyCenter::f_theMessenger private
Definition at line 157 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 157 of file G4PersistencyCenter.hh
Referenced by G4PersistencyCenter(), and ~G4PersistencyCenter().
G4ThreadLocal G4PersistencyCenter * G4PersistencyCenter::f_thePointer = 0 static private
Definition at line 158 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 158 of file G4PersistencyCenter.hh
Referenced by GetPersistencyCenter().
G4FileUtilities G4PersistencyCenter::f_ut private
Definition at line 170 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PersistencyCenter.hh
Referenced by SetReadFile().
StoreMap G4PersistencyCenter::f_writeFileMode private
Definition at line 166 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PersistencyCenter.hh
Referenced by CurrentStoreMode(), G4PersistencyCenter(), and SetStoreMode().
FileMap G4PersistencyCenter::f_writeFileName private
Definition at line 164 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 164 of file G4PersistencyCenter.hh
Referenced by CurrentObject(), CurrentStoreMode(), CurrentWriteFile(), G4PersistencyCenter(), SetStoreMode(), and SetWriteFile().
ObjMap G4PersistencyCenter::f_wrObj private
Definition at line 162 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 162 of file G4PersistencyCenter.hh
Referenced by G4PersistencyCenter(), and PrintAll().
G4int G4PersistencyCenter::m_verbose private
Definition at line 168 of file G4PersistencyCenter.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PersistencyCenter.hh
Referenced by SelectSystem(), SetVerboseLevel(), and VerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4PersistencyCenter.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4PersistencyCenter.cc