ECCE @ EIC Software: CexmcScenePrimitivesMessenger Class Reference
CexmcScenePrimitivesMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcScenePrimitivesMessenger.hh>
Public Member Functions
CexmcScenePrimitivesMessenger (CexmcScenePrimitives *scenePrimitives)
~CexmcScenePrimitivesMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CexmcScenePrimitives * scenePrimitives
G4UIcmdWith3Vector * drawRadialLine
G4UIcmdWithoutParameter * clearRadialLines
G4UIcmdWithABool * markTargetCenter
G4UIcmdWithABool * highlightInnerCrystals
G4UIcommand * setColour
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 56 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcScenePrimitivesMessenger.hh
Constructor & Destructor Documentation
CexmcScenePrimitivesMessenger::CexmcScenePrimitivesMessenger (CexmcScenePrimitives * scenePrimitives) explicit
Definition at line 57 of file CexmcScenePrimitivesMessenger.cc.
View newest version in sPHENIX GitHub at line 57 of file CexmcScenePrimitivesMessenger.cc
References G4UIcommand::AvailableForStates(), clearRadialLines, drawRadialLine, G4State_Idle, G4State_PreInit, highlightInnerCrystals, markTargetCenter, setColour, G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcommand::SetRange(), and CexmcMessenger::visDirName.
CexmcScenePrimitivesMessenger::~CexmcScenePrimitivesMessenger ()
Definition at line 125 of file CexmcScenePrimitivesMessenger.cc.
View newest version in sPHENIX GitHub at line 125 of file CexmcScenePrimitivesMessenger.cc
References clearRadialLines, drawRadialLine, highlightInnerCrystals, markTargetCenter, and setColour.
Member Function Documentation
void CexmcScenePrimitivesMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 135 of file CexmcScenePrimitivesMessenger.cc.
View newest version in sPHENIX GitHub at line 135 of file CexmcScenePrimitivesMessenger.cc
References CexmcInnerCrystalsHl_SP, CexmcRadialLine_SP, CexmcTargetCenterMark_SP, clearRadialLines, CexmcScenePrimitives::ClearRadialLines(), G4UIcommand::ConvertToDouble(), drawRadialLine, CexmcScenePrimitives::DrawRadialLine(), G4Colour::GetBlue(), G4Colour::GetColour(), G4Colour::GetGreen(), G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4Colour::GetRed(), highlightInnerCrystals, CexmcScenePrimitives::HighlightInnerCrystals(), markTargetCenter, CexmcScenePrimitives::MarkTargetCenter(), scenePrimitives, setColour, and CexmcScenePrimitives::SetColour().
Member Data Documentation
G4UIcmdWithoutParameter* CexmcScenePrimitivesMessenger::clearRadialLines private
Definition at line 72 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcScenePrimitivesMessenger.hh
Referenced by CexmcScenePrimitivesMessenger(), SetNewValue(), and ~CexmcScenePrimitivesMessenger().
G4UIcmdWith3Vector* CexmcScenePrimitivesMessenger::drawRadialLine private
Definition at line 70 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file CexmcScenePrimitivesMessenger.hh
Referenced by CexmcScenePrimitivesMessenger(), SetNewValue(), and ~CexmcScenePrimitivesMessenger().
G4UIcmdWithABool* CexmcScenePrimitivesMessenger::highlightInnerCrystals private
Definition at line 76 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcScenePrimitivesMessenger.hh
Referenced by CexmcScenePrimitivesMessenger(), SetNewValue(), and ~CexmcScenePrimitivesMessenger().
G4UIcmdWithABool* CexmcScenePrimitivesMessenger::markTargetCenter private
Definition at line 74 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file CexmcScenePrimitivesMessenger.hh
Referenced by CexmcScenePrimitivesMessenger(), SetNewValue(), and ~CexmcScenePrimitivesMessenger().
CexmcScenePrimitives* CexmcScenePrimitivesMessenger::scenePrimitives private
Definition at line 68 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcScenePrimitivesMessenger.hh
Referenced by SetNewValue().
G4UIcommand* CexmcScenePrimitivesMessenger::setColour private
Definition at line 78 of file CexmcScenePrimitivesMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file CexmcScenePrimitivesMessenger.hh
Referenced by CexmcScenePrimitivesMessenger(), SetNewValue(), and ~CexmcScenePrimitivesMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcScenePrimitivesMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcScenePrimitivesMessenger.cc