ECCE @ EIC Software: G4HadronNucleonXsc Class Reference
G4HadronNucleonXsc Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronNucleonXsc.hh>
Public Member Functions
G4HadronNucleonXsc ()
~G4HadronNucleonXsc ()
G4double HadronNucleonXsc (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double HadronNucleonXscPDG (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double HadronNucleonXscNS (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double KaonNucleonXscNS (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double KaonNucleonXscGG (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double KaonNucleonXscVG (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double HyperonNucleonXscNS (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double SCBMesonNucleonXscNS (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double HadronNucleonXscVU (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double HadronNucleonXscEL (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double CoulombBarrier (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
G4double GetHadronNucleonXscEL (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetHadronNucleonXscPDG (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetHadronNucleonXscNS (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetKaonNucleonXscGG (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetHyperonNucleonXscNS (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetHadronNucleonXscVU (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetCoulombBarrier (const G4DynamicParticle *dp, const G4ParticleDefinition *p)
G4double GetTotalHadronNucleonXsc () const
G4double GetElasticHadronNucleonXsc () const
G4double GetInelasticHadronNucleonXsc () const
void CrossSectionDescription (std::ostream &) const
Private Member Functions
G4double CalcMandelstamS (G4double ekin1, G4double mass1, G4double mass2)
G4double CalculateEcmValue (G4double ekin1, G4double mass1, G4double mass2)
Private Attributes
G4double fTotalXsc
G4double fElasticXsc
G4double fInelasticXsc
G4double fHypTotXscCof
G4Pow * g4calc
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theNeutron
const G4ParticleDefinition * theAProton
const G4ParticleDefinition * theANeutron
const G4ParticleDefinition * thePiPlus
const G4ParticleDefinition * thePiMinus
const G4ParticleDefinition * thePiZero
const G4ParticleDefinition * theD
const G4ParticleDefinition * theT
const G4ParticleDefinition * theA
const G4ParticleDefinition * theHe3
const G4ParticleDefinition * theKPlus
const G4ParticleDefinition * theKMinus
const G4ParticleDefinition * theK0S
const G4ParticleDefinition * theK0L
const G4ParticleDefinition * theL
const G4ParticleDefinition * theAntiL
const G4ParticleDefinition * theSPlus
const G4ParticleDefinition * theASPlus
const G4ParticleDefinition * theSMinus
const G4ParticleDefinition * theASMinus
const G4ParticleDefinition * theS0
const G4ParticleDefinition * theAS0
const G4ParticleDefinition * theXiMinus
const G4ParticleDefinition * theXi0
const G4ParticleDefinition * theAXiMinus
const G4ParticleDefinition * theAXi0
const G4ParticleDefinition * theOmega
const G4ParticleDefinition * theAOmega
const G4ParticleDefinition * theLambdaCPlus
const G4ParticleDefinition * theALambdaCPlus
const G4ParticleDefinition * theOmegaC0
const G4ParticleDefinition * theAOmegaC0
const G4ParticleDefinition * theSigmaCPlus
const G4ParticleDefinition * theASigmaCPlus
const G4ParticleDefinition * theSigmacPP
const G4ParticleDefinition * theASigmacPP
const G4ParticleDefinition * theSigmaC0
const G4ParticleDefinition * theASigmaC0
const G4ParticleDefinition * theXiCPlus
const G4ParticleDefinition * theAXiCPlus
const G4ParticleDefinition * theXiC0
const G4ParticleDefinition * theAXiC0
const G4ParticleDefinition * theLambdaB
const G4ParticleDefinition * theALambdaB
const G4ParticleDefinition * theOmegaBMinus
const G4ParticleDefinition * theAOmegaBMinus
const G4ParticleDefinition * theSigmaBMinus
const G4ParticleDefinition * theASigmaBMinus
const G4ParticleDefinition * theSigmaBPlus
const G4ParticleDefinition * theASigmaBPlus
const G4ParticleDefinition * theSigmaB0
const G4ParticleDefinition * theASigmaB0
const G4ParticleDefinition * theXiBMinus
const G4ParticleDefinition * theAXiBMinus
const G4ParticleDefinition * theXiB0
const G4ParticleDefinition * theAXiB0
const G4ParticleDefinition * theBMeson0
const G4ParticleDefinition * theABMeson0
const G4ParticleDefinition * theDMeson0
const G4ParticleDefinition * theADMeson0
const G4ParticleDefinition * theBsMeson0
const G4ParticleDefinition * theABsMeson0
const G4ParticleDefinition * theBcMesonPlus
const G4ParticleDefinition * theBcMesonMinus
const G4ParticleDefinition * theDsMesonPlus
const G4ParticleDefinition * theDsMesonMinus
const G4ParticleDefinition * theDMesonPlus
const G4ParticleDefinition * theDMesonMinus
const G4ParticleDefinition * theBMesonPlus
const G4ParticleDefinition * theBMesonMinus
const G4ParticleDefinition * theEta
const G4ParticleDefinition * theEtaPrime
const G4ParticleDefinition * theEtaC
const G4ParticleDefinition * theJPsi
const G4ParticleDefinition * theUpsilon
Detailed Description
Definition at line 50 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 50 of file G4HadronNucleonXsc.hh
Constructor & Destructor Documentation
G4HadronNucleonXsc::G4HadronNucleonXsc () explicit
Definition at line 125 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 125 of file G4HadronNucleonXsc.cc
References G4Alpha::Alpha(), G4AntiBMesonZero::AntiBMesonZero(), G4AntiBsMesonZero::AntiBsMesonZero(), G4AntiDMesonZero::AntiDMesonZero(), G4AntiLambda::AntiLambda(), G4AntiLambdab::AntiLambdab(), G4AntiLambdacPlus::AntiLambdacPlus(), G4AntiNeutron::AntiNeutron(), G4AntiOmegabMinus::AntiOmegabMinus(), G4AntiOmegacZero::AntiOmegacZero(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmabMinus::AntiSigmabMinus(), G4AntiSigmabPlus::AntiSigmabPlus(), G4AntiSigmabZero::AntiSigmabZero(), G4AntiSigmacPlus::AntiSigmacPlus(), G4AntiSigmacPlusPlus::AntiSigmacPlusPlus(), G4AntiSigmacZero::AntiSigmacZero(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiSigmaZero::AntiSigmaZero(), G4AntiXibMinus::AntiXibMinus(), G4AntiXibZero::AntiXibZero(), G4AntiXicPlus::AntiXicPlus(), G4AntiXicZero::AntiXicZero(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), G4BcMesonMinus::BcMesonMinus(), G4BcMesonPlus::BcMesonPlus(), G4BMesonMinus::BMesonMinus(), G4BMesonPlus::BMesonPlus(), G4BMesonZero::BMesonZero(), G4BsMesonZero::BsMesonZero(), G4Deuteron::Deuteron(), G4DMesonMinus::DMesonMinus(), G4DMesonPlus::DMesonPlus(), G4DMesonZero::DMesonZero(), G4DsMesonMinus::DsMesonMinus(), G4DsMesonPlus::DsMesonPlus(), G4Eta::Eta(), G4Etac::Etac(), G4EtaPrime::EtaPrime(), fHypTotXscCof, g4calc, G4Gamma::Gamma(), G4Pow::GetInstance(), G4He3::He3(), G4JPsi::JPsi(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), G4Lambda::Lambda(), G4Lambdab::Lambdab(), G4LambdacPlus::LambdacPlus(), G4Neutron::Neutron(), G4OmegabMinus::OmegabMinus(), G4OmegacZero::OmegacZero(), G4OmegaMinus::OmegaMinus(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4Proton::Proton(), G4SigmabMinus::SigmabMinus(), G4SigmabPlus::SigmabPlus(), G4SigmabZero::SigmabZero(), G4SigmacPlus::SigmacPlus(), G4SigmacPlusPlus::SigmacPlusPlus(), G4SigmacZero::SigmacZero(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), theA, theABMeson0, theABsMeson0, theADMeson0, theALambdaB, theALambdaCPlus, theANeutron, theAntiL, theAOmega, theAOmegaBMinus, theAOmegaC0, theAProton, theAS0, theASigmaB0, theASigmaBMinus, theASigmaBPlus, theASigmaC0, theASigmaCPlus, theASigmacPP, theASMinus, theASPlus, theAXi0, theAXiB0, theAXiBMinus, theAXiC0, theAXiCPlus, theAXiMinus, theBcMesonMinus, theBcMesonPlus, theBMeson0, theBMesonMinus, theBMesonPlus, theBsMeson0, theD, theDMeson0, theDMesonMinus, theDMesonPlus, theDsMesonMinus, theDsMesonPlus, theEta, theEtaC, theEtaPrime, theGamma, theHe3, theJPsi, theK0L, theK0S, theKMinus, theKPlus, theL, theLambdaB, theLambdaCPlus, theNeutron, theOmega, theOmegaBMinus, theOmegaC0, thePiMinus, thePiPlus, thePiZero, theProton, theS0, theSigmaB0, theSigmaBMinus, theSigmaBPlus, theSigmaC0, theSigmaCPlus, theSigmacPP, theSMinus, theSPlus, theT, theUpsilon, theXi0, theXiB0, theXiBMinus, theXiC0, theXiCPlus, theXiMinus, G4Triton::Triton(), G4Upsilon::Upsilon(), G4XibMinus::XibMinus(), G4XibZero::XibZero(), G4XicPlus::XicPlus(), G4XicZero::XicZero(), G4XiMinus::XiMinus(), and G4XiZero::XiZero().
G4HadronNucleonXsc::~G4HadronNucleonXsc ()
Definition at line 214 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 214 of file G4HadronNucleonXsc.cc
Member Function Documentation
G4double G4HadronNucleonXsc::CalcMandelstamS (G4double ekin1, G4double mass1, G4double mass2) inline private
Definition at line 130 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 130 of file G4HadronNucleonXsc.hh
Referenced by HadronNucleonXscEL(), HadronNucleonXscNS(), and HadronNucleonXscPDG().
G4double G4HadronNucleonXsc::CalculateEcmValue (G4double ekin1, G4double mass1, G4double mass2) inline private
Definition at line 133 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 133 of file G4HadronNucleonXsc.hh
G4double G4HadronNucleonXsc::CoulombBarrier (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 1465 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 1465 of file G4HadronNucleonXsc.cc
References CLHEP::fermi, fermi, source.hepunit::fine_structure_const, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, ratio, theKPlus, thePiPlus, and theProton.
Referenced by GetCoulombBarrier(), and HadronNucleonXscPDG().
void G4HadronNucleonXsc::CrossSectionDescription (std::ostream & outFile) const
Definition at line 217 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 217 of file G4HadronNucleonXsc.cc
G4double G4HadronNucleonXsc::GetCoulombBarrier (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 117 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 117 of file G4HadronNucleonXsc.hh
References CoulombBarrier(), G4DynamicParticle::GetDefinition(), and G4DynamicParticle::GetKineticEnergy().
G4double G4HadronNucleonXsc::GetElasticHadronNucleonXsc () const inline
Definition at line 123 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 123 of file G4HadronNucleonXsc.hh
References fElasticXsc.
Referenced by G4BGGNucleonElasticXS::GetIsoCrossSection(), and G4BGGPionElasticXS::GetIsoCrossSection().
G4double G4HadronNucleonXsc::GetHadronNucleonXscEL (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 93 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 93 of file G4HadronNucleonXsc.hh
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and HadronNucleonXscEL().
G4double G4HadronNucleonXsc::GetHadronNucleonXscNS (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 101 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HadronNucleonXsc.hh
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and HadronNucleonXscNS().
Referenced by G4hhElastic::SetParametersCMS().
G4double G4HadronNucleonXsc::GetHadronNucleonXscPDG (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 97 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 97 of file G4HadronNucleonXsc.hh
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and HadronNucleonXscPDG().
G4double G4HadronNucleonXsc::GetHadronNucleonXscVU (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 113 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 113 of file G4HadronNucleonXsc.hh
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and HadronNucleonXscVU().
G4double G4HadronNucleonXsc::GetHyperonNucleonXscNS (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 109 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 109 of file G4HadronNucleonXsc.hh
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and HyperonNucleonXscNS().
G4double G4HadronNucleonXsc::GetInelasticHadronNucleonXsc () const inline
Definition at line 124 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 124 of file G4HadronNucleonXsc.hh
References fInelasticXsc.
Referenced by G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXscVU(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), and G4BGGPionInelasticXS::GetIsoCrossSection().
G4double G4HadronNucleonXsc::GetKaonNucleonXscGG (const G4DynamicParticle * dp, const G4ParticleDefinition * p) inline
Definition at line 105 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 105 of file G4HadronNucleonXsc.hh
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and KaonNucleonXscGG().
G4double G4HadronNucleonXsc::GetTotalHadronNucleonXsc () const inline
Definition at line 122 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 122 of file G4HadronNucleonXsc.hh
References fTotalXsc.
G4double G4HadronNucleonXsc::HadronNucleonXsc (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 229 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 229 of file G4HadronNucleonXsc.cc
References kdfinder::abs(), G4ParticleDefinition::GetPDGEncoding(), HadronNucleonXscNS(), HyperonNucleonXscNS(), KaonNucleonXscNS(), pdg, and SCBMesonNucleonXscNS().
Referenced by G4ComponentGGHadronNucleusXsc::ComputeCrossSections().
G4double G4HadronNucleonXsc::HadronNucleonXscEL (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 1403 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 1403 of file G4HadronNucleonXsc.cc
References CalcMandelstamS(), fElasticXsc, fInelasticXsc, fTotalXsc, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGMass(), invGeV2, CLHEP::millibarn, CLHEP::neutron_mass_c2, CLHEP::proton_mass_c2, theAProton, theGamma, theK0L, theK0S, theKMinus, theKPlus, theNeutron, thePiMinus, thePiPlus, theProton, x1, and x2.
Referenced by G4ComponentGGHadronNucleusXsc::GetHadronNucleonXsc(), and GetHadronNucleonXscEL().
G4double G4HadronNucleonXsc::HadronNucleonXscNS (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 460 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 460 of file G4HadronNucleonXsc.cc
References CalcMandelstamS(), cofLogE, cofLogT, G4NuclearRadii::CoulombFactor(), ekinmin, fElasticXsc, fInelasticXsc, fTotalXsc, g4calc, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), HadronNucleonXscPDG(), invGeV, invGeV2, LE, max, MeV, CLHEP::millibarn, min, minLogP, G4InuclParticleNames::neutron, pMax, pMin, G4Pow::powN(), G4InuclParticleNames::proton, G4InuclParticleNames::sp, theANeutron, theAProton, theKMinus, theKPlus, theNeutron, thePiMinus, thePiPlus, theProton, x, x1, x2, and y.
Referenced by G4ComponentGGNuclNuclXsc::ComputeCrossSections(), GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), HadronNucleonXsc(), HyperonNucleonXscNS(), KaonNucleonXscNS(), and SCBMesonNucleonXscNS().
G4double G4HadronNucleonXsc::HadronNucleonXscPDG (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 274 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 274 of file G4HadronNucleonXsc.cc
References CalcMandelstamS(), CoulombBarrier(), fElasticXsc, fInelasticXsc, fTotalXsc, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), H, invGeV, invGeV2, MeV, CLHEP::millibarn, G4InuclParticleNames::neutron, P, G4InuclParticleNames::proton, theANeutron, theAProton, theGamma, theK0L, theK0S, theKMinus, theKPlus, theNeutron, thePiMinus, thePiPlus, theProton, theSMinus, and x.
Referenced by GetHadronNucleonXscPDG(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscPDG(), and HadronNucleonXscNS().
G4double G4HadronNucleonXsc::HadronNucleonXscVU (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 1253 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 1253 of file G4HadronNucleonXsc.cc
References kdfinder::abs(), fElasticXsc, fInelasticXsc, fTotalXsc, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), invGeV, mass, CLHEP::millibarn, min, G4InuclParticleNames::neutron, G4InuclParticleNames::proton, theNeutron, and theProton.
Referenced by GetHadronNucleonXscVU(), and G4ComponentGGHadronNucleusXsc::GetHNinelasticXscVU().
G4double G4HadronNucleonXsc::HyperonNucleonXscNS (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 1104 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 1104 of file G4HadronNucleonXsc.cc
References fElasticXsc, fInelasticXsc, fTotalXsc, HadronNucleonXscNS(), theALambdaB, theALambdaCPlus, theAntiL, theAOmega, theAOmegaBMinus, theAOmegaC0, theAS0, theASigmaB0, theASigmaBMinus, theASigmaBPlus, theASigmaC0, theASigmaCPlus, theASigmacPP, theASMinus, theASPlus, theAXi0, theAXiB0, theAXiBMinus, theAXiC0, theAXiCPlus, theAXiMinus, theL, theLambdaB, theLambdaCPlus, theOmega, theOmegaBMinus, theOmegaC0, theProton, theS0, theSigmaB0, theSigmaBMinus, theSigmaBPlus, theSigmaC0, theSigmaCPlus, theSigmacPP, theSMinus, theSPlus, theXi0, theXiB0, theXiBMinus, theXiC0, theXiCPlus, and theXiMinus.
Referenced by GetHyperonNucleonXscNS(), and HadronNucleonXsc().
G4double G4HadronNucleonXsc::KaonNucleonXscGG (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 903 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 903 of file G4HadronNucleonXsc.cc
References fElasticXsc, fInelasticXsc, fTotalXsc, KaonNucleonXscVG(), theK0L, theK0S, theKMinus, and theKPlus.
Referenced by G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), and GetKaonNucleonXscGG().
G4double G4HadronNucleonXsc::KaonNucleonXscNS (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 929 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 929 of file G4HadronNucleonXsc.cc
References fElasticXsc, fInelasticXsc, fTotalXsc, HadronNucleonXscNS(), theK0L, theK0S, theKMinus, and theKPlus.
Referenced by G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), and HadronNucleonXsc().
G4double G4HadronNucleonXsc::KaonNucleonXscVG (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 955 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 955 of file G4HadronNucleonXsc.cc
References cofLogE, cofLogT, G4NuclearRadii::CoulombFactor(), fElasticXsc, fInelasticXsc, fTotalXsc, G4Exp(), G4Log(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), invGeV, LE, max, CLHEP::millibarn, min, minLogP, G4InuclParticleNames::neutron, pMax, pMin, G4InuclParticleNames::proton, G4InuclParticleNames::sp, theKMinus, theKPlus, theNeutron, and theProton.
Referenced by KaonNucleonXscGG().
G4double G4HadronNucleonXsc::SCBMesonNucleonXscNS (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin)
Definition at line 1181 of file G4HadronNucleonXsc.cc.
View newest version in sPHENIX GitHub at line 1181 of file G4HadronNucleonXsc.cc
References fElasticXsc, fInelasticXsc, fTotalXsc, HadronNucleonXscNS(), theABMeson0, theABsMeson0, theADMeson0, theBcMesonMinus, theBcMesonPlus, theBMeson0, theBMesonMinus, theBMesonPlus, theBsMeson0, theDMeson0, theDMesonMinus, theDMesonPlus, theDsMesonMinus, theDsMesonPlus, theEta, theEtaC, theEtaPrime, theJPsi, thePiPlus, and theUpsilon.
Referenced by HadronNucleonXsc().
Member Data Documentation
G4double G4HadronNucleonXsc::fElasticXsc private
Definition at line 134 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 134 of file G4HadronNucleonXsc.hh
Referenced by GetElasticHadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), HadronNucleonXscVU(), HyperonNucleonXscNS(), KaonNucleonXscGG(), KaonNucleonXscNS(), KaonNucleonXscVG(), and SCBMesonNucleonXscNS().
G4double G4HadronNucleonXsc::fHypTotXscCof private
Definition at line 137 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 137 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc().
G4double G4HadronNucleonXsc::fInelasticXsc private
Definition at line 134 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 134 of file G4HadronNucleonXsc.hh
Referenced by GetInelasticHadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), HadronNucleonXscVU(), HyperonNucleonXscNS(), KaonNucleonXscGG(), KaonNucleonXscNS(), KaonNucleonXscVG(), and SCBMesonNucleonXscNS().
G4double G4HadronNucleonXsc::fTotalXsc private
Definition at line 134 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 134 of file G4HadronNucleonXsc.hh
Referenced by GetTotalHadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), HadronNucleonXscVU(), HyperonNucleonXscNS(), KaonNucleonXscGG(), KaonNucleonXscNS(), KaonNucleonXscVG(), and SCBMesonNucleonXscNS().
G4Pow* G4HadronNucleonXsc::g4calc private
Definition at line 138 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 138 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HadronNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theA private
Definition at line 150 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 150 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc().
const G4ParticleDefinition* G4HadronNucleonXsc::theABMeson0 private
Definition at line 202 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 202 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theABsMeson0 private
Definition at line 206 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 206 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theADMeson0 private
Definition at line 204 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 204 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theALambdaB private
Definition at line 187 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 187 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theALambdaCPlus private
Definition at line 173 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 173 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theANeutron private
Definition at line 144 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 144 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscNS(), and HadronNucleonXscPDG().
const G4ParticleDefinition* G4HadronNucleonXsc::theAntiL private
Definition at line 158 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 158 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAOmega private
Definition at line 170 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 170 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAOmegaBMinus private
Definition at line 189 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 189 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAOmegaC0 private
Definition at line 175 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 175 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAProton private
Definition at line 143 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 143 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), and HadronNucleonXscPDG().
const G4ParticleDefinition* G4HadronNucleonXsc::theAS0 private
Definition at line 164 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 164 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASigmaB0 private
Definition at line 195 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 195 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASigmaBMinus private
Definition at line 191 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 191 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASigmaBPlus private
Definition at line 193 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 193 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASigmaC0 private
Definition at line 181 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 181 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASigmaCPlus private
Definition at line 177 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 177 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASigmacPP private
Definition at line 179 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 179 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASMinus private
Definition at line 162 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 162 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theASPlus private
Definition at line 160 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 160 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAXi0 private
Definition at line 168 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 168 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAXiB0 private
Definition at line 199 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 199 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAXiBMinus private
Definition at line 197 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 197 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAXiC0 private
Definition at line 185 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 185 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAXiCPlus private
Definition at line 183 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 183 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theAXiMinus private
Definition at line 167 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 167 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theBcMesonMinus private
Definition at line 208 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 208 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theBcMesonPlus private
Definition at line 207 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 207 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theBMeson0 private
Definition at line 201 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 201 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theBMesonMinus private
Definition at line 214 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 214 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theBMesonPlus private
Definition at line 213 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 213 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theBsMeson0 private
Definition at line 205 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 205 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theD private
Definition at line 148 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 148 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc().
const G4ParticleDefinition* G4HadronNucleonXsc::theDMeson0 private
Definition at line 203 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 203 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theDMesonMinus private
Definition at line 212 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 212 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theDMesonPlus private
Definition at line 211 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 211 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theDsMesonMinus private
Definition at line 210 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 210 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theDsMesonPlus private
Definition at line 209 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 209 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theEta private
Definition at line 215 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 215 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theEtaC private
Definition at line 217 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 217 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theEtaPrime private
Definition at line 216 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 216 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theGamma private
Definition at line 140 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 140 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), and HadronNucleonXscPDG().
const G4ParticleDefinition* G4HadronNucleonXsc::theHe3 private
Definition at line 151 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 151 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc().
const G4ParticleDefinition* G4HadronNucleonXsc::theJPsi private
Definition at line 218 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 218 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theK0L private
Definition at line 156 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 156 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscPDG(), KaonNucleonXscGG(), and KaonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theK0S private
Definition at line 155 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 155 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscPDG(), KaonNucleonXscGG(), and KaonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theKMinus private
Definition at line 154 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 154 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), KaonNucleonXscGG(), KaonNucleonXscNS(), and KaonNucleonXscVG().
const G4ParticleDefinition* G4HadronNucleonXsc::theKPlus private
Definition at line 153 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 153 of file G4HadronNucleonXsc.hh
Referenced by CoulombBarrier(), G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), KaonNucleonXscGG(), KaonNucleonXscNS(), and KaonNucleonXscVG().
const G4ParticleDefinition* G4HadronNucleonXsc::theL private
Definition at line 157 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 157 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theLambdaB private
Definition at line 186 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 186 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theLambdaCPlus private
Definition at line 172 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 172 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theNeutron private
Definition at line 142 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 142 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), HadronNucleonXscVU(), and KaonNucleonXscVG().
const G4ParticleDefinition* G4HadronNucleonXsc::theOmega private
Definition at line 169 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 169 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theOmegaBMinus private
Definition at line 188 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 188 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theOmegaC0 private
Definition at line 174 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 174 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::thePiMinus private
Definition at line 146 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 146 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), and HadronNucleonXscPDG().
const G4ParticleDefinition* G4HadronNucleonXsc::thePiPlus private
Definition at line 145 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 145 of file G4HadronNucleonXsc.hh
Referenced by CoulombBarrier(), G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::thePiZero private
Definition at line 147 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 147 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc().
const G4ParticleDefinition* G4HadronNucleonXsc::theProton private
Definition at line 141 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 141 of file G4HadronNucleonXsc.hh
Referenced by CoulombBarrier(), G4HadronNucleonXsc(), HadronNucleonXscEL(), HadronNucleonXscNS(), HadronNucleonXscPDG(), HadronNucleonXscVU(), HyperonNucleonXscNS(), and KaonNucleonXscVG().
const G4ParticleDefinition* G4HadronNucleonXsc::theS0 private
Definition at line 163 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 163 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSigmaB0 private
Definition at line 194 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 194 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSigmaBMinus private
Definition at line 190 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 190 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSigmaBPlus private
Definition at line 192 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 192 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSigmaC0 private
Definition at line 180 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 180 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSigmaCPlus private
Definition at line 176 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 176 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSigmacPP private
Definition at line 178 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 178 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSMinus private
Definition at line 161 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 161 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), HadronNucleonXscPDG(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theSPlus private
Definition at line 159 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 159 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theT private
Definition at line 149 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 149 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc().
const G4ParticleDefinition* G4HadronNucleonXsc::theUpsilon private
Definition at line 219 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 219 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and SCBMesonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theXi0 private
Definition at line 166 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 166 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theXiB0 private
Definition at line 198 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 198 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theXiBMinus private
Definition at line 196 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 196 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theXiC0 private
Definition at line 184 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 184 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theXiCPlus private
Definition at line 182 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 182 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
const G4ParticleDefinition* G4HadronNucleonXsc::theXiMinus private
Definition at line 165 of file G4HadronNucleonXsc.hh.
View newest version in sPHENIX GitHub at line 165 of file G4HadronNucleonXsc.hh
Referenced by G4HadronNucleonXsc(), and HyperonNucleonXscNS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronNucleonXsc.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4HadronNucleonXsc.cc