ECCE @ EIC Software: G4ProtonField Class Reference
G4ProtonField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4ProtonField.hh>
Public Member Functions
G4ProtonField (G4V3DNucleus *nucleus)
virtual ~G4ProtonField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
virtual G4double GetCoeff ()
Private Member Functions
G4ProtonField (const G4ProtonField &right)
const G4ProtonField & operator= (const G4ProtonField &right)
G4bool operator== (const G4ProtonField &right) const
G4bool operator!= (const G4ProtonField &right) const
G4double GetDensity (const G4ThreeVector &aPosition)
G4double GetFermiMomentum (const G4double aDensity)
Private Attributes
G4int theA
G4int theZ
G4double theBarrier
G4double theRadius
G4FermiMomentum theFermi
const G4VNuclearDensity * theDensity
std::vector< G4double > theFermiMomBuffer
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 48 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ProtonField.hh
Constructor & Destructor Documentation
G4ProtonField::G4ProtonField (G4V3DNucleus * nucleus)
Definition at line 47 of file G4ProtonField.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ProtonField.cc
References fermi, GetBarrier(), G4V3DNucleus::GetCharge(), GetDensity(), GetFermiMomentum(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetOuterRadius(), G4FermiMomentum::Init(), m, theA, theBarrier, theFermi, theFermiMomBuffer, G4VNuclearField::theNucleus, theRadius, and theZ.
G4ProtonField::~G4ProtonField () virtual
Definition at line 79 of file G4ProtonField.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ProtonField.cc
G4ProtonField::G4ProtonField (const G4ProtonField & right) private
Member Function Documentation
G4double G4ProtonField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 98 of file G4ProtonField.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ProtonField.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4Pow::GetInstance(), MeV, theA, theZ, and G4Pow::Z13().
Referenced by G4ProtonField().
G4double G4ProtonField::GetDensity (const G4ThreeVector & aPosition) inline private
Definition at line 68 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ProtonField.hh
References G4VNuclearDensity::GetDensity(), and theDensity.
Referenced by G4ProtonField().
G4double G4ProtonField::GetFermiMomentum (const G4double aDensity) inline private
Definition at line 72 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ProtonField.hh
References G4FermiMomentum::GetFermiMomentum(), and theFermi.
Referenced by G4ProtonField().
G4double G4ProtonField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 82 of file G4ProtonField.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ProtonField.cc
References fermi, CLHEP::Hep3Vector::mag(), source.hepunit::proton_mass_c2, theBarrier, theFermiMomBuffer, x, x1, x2, y, y1, and y2.
G4bool G4ProtonField::operator!= (const G4ProtonField & right) const private
const G4ProtonField& G4ProtonField::operator= (const G4ProtonField & right) private
G4bool G4ProtonField::operator== (const G4ProtonField & right) const private
Member Data Documentation
G4int G4ProtonField::theA private
Definition at line 77 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ProtonField.hh
Referenced by G4ProtonField(), and GetBarrier().
G4double G4ProtonField::theBarrier private
Definition at line 79 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ProtonField.hh
Referenced by G4ProtonField(), and GetField().
const G4VNuclearDensity* G4ProtonField::theDensity private
Definition at line 82 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ProtonField.hh
Referenced by GetDensity().
G4FermiMomentum G4ProtonField::theFermi private
Definition at line 81 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ProtonField.hh
Referenced by G4ProtonField(), and GetFermiMomentum().
std::vector<G4double> G4ProtonField::theFermiMomBuffer private
Definition at line 84 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ProtonField.hh
Referenced by G4ProtonField(), and GetField().
G4double G4ProtonField::theRadius private
Definition at line 80 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ProtonField.hh
Referenced by G4ProtonField().
G4int G4ProtonField::theZ private
Definition at line 78 of file G4ProtonField.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ProtonField.hh
Referenced by G4ProtonField(), and GetBarrier().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4ProtonField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4ProtonField.cc