ECCE @ EIC Software: G4FastPathHadronicCrossSection::fastPathEntry Struct Reference
G4FastPathHadronicCrossSection::fastPathEntry Struct Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4FastPathHadronicCrossSection.hh>
Public Member Functions
fastPathEntry (const G4ParticleDefinition *par, const G4Material *mat, G4double min_cutoff)
~fastPathEntry ()
G4double GetCrossSection (G4double ene) const
void Initialize (G4CrossSectionDataStore *)
Public Attributes
const G4ParticleDefinition *const particle
const G4Material *const material
const G4double min_cutoff
XSParam * physicsVector
Detailed Description
Definition at line 54 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 54 of file G4FastPathHadronicCrossSection.hh
Constructor & Destructor Documentation
fastPathEntry::fastPathEntry (const G4ParticleDefinition * par, const G4Material * mat, G4double min_cutoff)
Definition at line 65 of file G4FastPathHadronicCrossSection.cc.
View newest version in sPHENIX GitHub at line 65 of file G4FastPathHadronicCrossSection.cc
References DBG.
fastPathEntry::~fastPathEntry ()
Definition at line 79 of file G4FastPathHadronicCrossSection.cc.
View newest version in sPHENIX GitHub at line 79 of file G4FastPathHadronicCrossSection.cc
References DBG, G4Material::GetName(), G4ParticleDefinition::GetParticleName(), material, min_cutoff, particle, and physicsVector.
Member Function Documentation
G4double G4FastPathHadronicCrossSection::fastPathEntry::GetCrossSection (G4double ene) const inline
Definition at line 58 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 58 of file G4FastPathHadronicCrossSection.hh
References physicsVector, and G4PhysicsVector::Value().
Referenced by G4CrossSectionDataStore::GetCrossSection().
void fastPathEntry::Initialize (G4CrossSectionDataStore * xsds)
Definition at line 95 of file G4FastPathHadronicCrossSection.cc.
View newest version in sPHENIX GitHub at line 95 of file G4FastPathHadronicCrossSection.cc
References e, G4CrossSectionDataStore::GetCrossSection(), G4CrossSectionDataStore::GetFastPathControlFlags(), G4CrossSectionDataStore::GetFastPathParameters(), G4FastPathHadronicCrossSection::controlFlag::initializationPhase, material, max, min, min_cutoff, particle, physicsVector, G4PhysicsFreeVector::PutValue(), G4FastPathHadronicCrossSection::fastPathParameters::sampleCount, G4FastPathHadronicCrossSection::fastPathParameters::sampleMax, G4FastPathHadronicCrossSection::fastPathParameters::sampleMin, G4DynamicParticle::SetKineticEnergy(), G4FastPathHadronicCrossSection::controlFlag::useFastPathIfAvailable, and x.
Referenced by G4CrossSectionDataStore::BuildPhysicsTable().
Member Data Documentation
const G4Material* const G4FastPathHadronicCrossSection::fastPathEntry::material
Definition at line 61 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 61 of file G4FastPathHadronicCrossSection.hh
Referenced by Initialize(), operator<<(), and ~fastPathEntry().
const G4double G4FastPathHadronicCrossSection::fastPathEntry::min_cutoff
Definition at line 62 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 62 of file G4FastPathHadronicCrossSection.hh
Referenced by G4CrossSectionDataStore::GetCrossSection(), Initialize(), operator<<(), and ~fastPathEntry().
const G4ParticleDefinition* const G4FastPathHadronicCrossSection::fastPathEntry::particle
Definition at line 60 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 60 of file G4FastPathHadronicCrossSection.hh
Referenced by Initialize(), operator<<(), and ~fastPathEntry().
XSParam* G4FastPathHadronicCrossSection::fastPathEntry::physicsVector
Definition at line 64 of file G4FastPathHadronicCrossSection.hh.
View newest version in sPHENIX GitHub at line 64 of file G4FastPathHadronicCrossSection.hh
Referenced by GetCrossSection(), Initialize(), operator<<(), and ~fastPathEntry().
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4FastPathHadronicCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4FastPathHadronicCrossSection.cc