ECCE @ EIC Software: G4RKG3_Stepper Class Reference
G4RKG3_Stepper Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4RKG3_Stepper.hh>
Public Member Functions
G4RKG3_Stepper (G4Mag_EqRhs *EqRhs)
~G4RKG3_Stepper ()
void Stepper (const G4double yIn[], const G4double dydx[], G4double h, G4double yOut[], G4double yErr[])
G4double DistChord () const
void StepNoErr (const G4double tIn[8], const G4double dydx[6], G4double Step, G4double tOut[8], G4double B[3])
void StepWithEst (const G4double tIn[8], const G4double dydx[6], G4double Step, G4double tOut[8], G4double &alpha2, G4double &beta2, const G4double B1[3], G4double B2[3])
G4int IntegratorOrder () const
Public Member Functions inherited from G4MagIntegratorStepper
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, G4bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
G4MagIntegratorStepper (const G4MagIntegratorStepper &)=delete
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)=delete
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
G4bool IsFSAL () const
Private Attributes
G4ThreeVector fyInitial
G4ThreeVector fyMidPoint
G4ThreeVector fyFinal
G4ThreeVector fpInitial
G4ThreeVector BfldIn
G4double hStep = 0.0
Additional Inherited Members
Protected Member Functions inherited from G4MagIntegratorStepper
void SetIntegrationOrder (G4int order)
void SetFSAL (G4bool flag=true)
Detailed Description
Definition at line 43 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 43 of file G4RKG3_Stepper.hh
Constructor & Destructor Documentation
G4RKG3_Stepper::G4RKG3_Stepper (G4Mag_EqRhs * EqRhs)
Definition at line 35 of file G4RKG3_Stepper.cc.
View newest version in sPHENIX GitHub at line 35 of file G4RKG3_Stepper.cc
G4RKG3_Stepper::~G4RKG3_Stepper ()
Definition at line 40 of file G4RKG3_Stepper.cc.
View newest version in sPHENIX GitHub at line 40 of file G4RKG3_Stepper.cc
Member Function Documentation
G4double G4RKG3_Stepper::DistChord () const virtual
Implements G4MagIntegratorStepper.
Definition at line 196 of file G4RKG3_Stepper.cc.
View newest version in sPHENIX GitHub at line 196 of file G4RKG3_Stepper.cc
References G4LineSection::Distline(), fyFinal, fyInitial, and fyMidPoint.
G4int G4RKG3_Stepper::IntegratorOrder () const inline virtual
Implements G4MagIntegratorStepper.
Definition at line 88 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RKG3_Stepper.hh
void G4RKG3_Stepper::StepNoErr (const G4double tIn[8], const G4double dydx[6], G4double Step, G4double tOut[8], G4double B[3])
Definition at line 130 of file G4RKG3_Stepper.cc.
View newest version in sPHENIX GitHub at line 130 of file G4RKG3_Stepper.cc
References c1, c2, G4EquationOfMotion::EvaluateRhsGivenB(), G4EquationOfMotion::EvaluateRhsReturnB(), G4MagIntegratorStepper::GetEquationOfMotion(), and mom.
Referenced by Stepper().
void G4RKG3_Stepper::Stepper (const G4double yIn[], const G4double dydx[], G4double h, G4double yOut[], G4double yErr[]) virtual
Implements G4MagIntegratorStepper.
Definition at line 44 of file G4RKG3_Stepper.cc.
View newest version in sPHENIX GitHub at line 44 of file G4RKG3_Stepper.cc
References B(), BfldIn, G4EquationOfMotion::EvaluateRhsGivenB(), fpInitial, fyFinal, fyInitial, fyMidPoint, G4MagIntegratorStepper::GetEquationOfMotion(), Acts::UnitConstants::h, hStep, and StepNoErr().
void G4RKG3_Stepper::StepWithEst (const G4double tIn[8], const G4double dydx[6], G4double Step, G4double tOut[8], G4double & alpha2, G4double & beta2, const G4double B1[3], G4double B2[3])
Definition at line 109 of file G4RKG3_Stepper.cc.
View newest version in sPHENIX GitHub at line 109 of file G4RKG3_Stepper.cc
References FatalException, and G4Exception().
Member Data Documentation
G4ThreeVector G4RKG3_Stepper::BfldIn private
Definition at line 96 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 96 of file G4RKG3_Stepper.hh
Referenced by Stepper().
G4ThreeVector G4RKG3_Stepper::fpInitial private
Definition at line 95 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RKG3_Stepper.hh
Referenced by Stepper().
G4ThreeVector G4RKG3_Stepper::fyFinal private
Definition at line 92 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RKG3_Stepper.hh
Referenced by DistChord(), and Stepper().
G4ThreeVector G4RKG3_Stepper::fyInitial private
Definition at line 92 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RKG3_Stepper.hh
Referenced by DistChord(), and Stepper().
G4ThreeVector G4RKG3_Stepper::fyMidPoint private
Definition at line 92 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RKG3_Stepper.hh
Referenced by DistChord(), and Stepper().
G4double G4RKG3_Stepper::hStep = 0.0 private
Definition at line 97 of file G4RKG3_Stepper.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RKG3_Stepper.hh
Referenced by Stepper().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4RKG3_Stepper.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4RKG3_Stepper.cc