ECCE @ EIC Software: DMXEventActionMessenger Class Reference
DMXEventActionMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXEventActionMessenger.hh>
Public Member Functions
DMXEventActionMessenger (DMXEventAction *)
~DMXEventActionMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
DMXEventAction * eventAction
G4UIdirectory * dmxDirectory
G4UIdirectory * drawDirectory
G4UIcmdWithAString * DrawTrksCmd
G4UIcmdWithAString * DrawColsCmd
G4UIcmdWithABool * DrawHitsCmd
G4UIcmdWithABool * SavePmtCmd
G4UIcmdWithABool * SaveHitsCmd
G4UIcmdWithAnInteger * PrintCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 55 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file DMXEventActionMessenger.hh
Constructor & Destructor Documentation
DMXEventActionMessenger::DMXEventActionMessenger (DMXEventAction * EvAct)
Definition at line 56 of file DMXEventActionMessenger.cc.
View newest version in sPHENIX GitHub at line 56 of file DMXEventActionMessenger.cc
References G4UIcommand::AvailableForStates(), dmxDirectory, DrawColsCmd, drawDirectory, DrawHitsCmd, DrawTrksCmd, G4State_Idle, PrintCmd, SaveHitsCmd, SavePmtCmd, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), and G4UIcommand::SetRange().
DMXEventActionMessenger::~DMXEventActionMessenger ()
Definition at line 109 of file DMXEventActionMessenger.cc.
View newest version in sPHENIX GitHub at line 109 of file DMXEventActionMessenger.cc
References dmxDirectory, DrawColsCmd, drawDirectory, DrawHitsCmd, DrawTrksCmd, PrintCmd, SaveHitsCmd, and SavePmtCmd.
Member Function Documentation
void DMXEventActionMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 123 of file DMXEventActionMessenger.cc.
View newest version in sPHENIX GitHub at line 123 of file DMXEventActionMessenger.cc
References t.
Member Data Documentation
G4UIdirectory* DMXEventActionMessenger::dmxDirectory private
Definition at line 66 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
G4UIcmdWithAString* DMXEventActionMessenger::DrawColsCmd private
Definition at line 69 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
G4UIdirectory* DMXEventActionMessenger::drawDirectory private
Definition at line 67 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
G4UIcmdWithABool* DMXEventActionMessenger::DrawHitsCmd private
Definition at line 70 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
G4UIcmdWithAString* DMXEventActionMessenger::DrawTrksCmd private
Definition at line 68 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
DMXEventAction* DMXEventActionMessenger::eventAction private
Definition at line 64 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file DMXEventActionMessenger.hh
G4UIcmdWithAnInteger* DMXEventActionMessenger::PrintCmd private
Definition at line 73 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
G4UIcmdWithABool* DMXEventActionMessenger::SaveHitsCmd private
Definition at line 72 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
G4UIcmdWithABool* DMXEventActionMessenger::SavePmtCmd private
Definition at line 71 of file DMXEventActionMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file DMXEventActionMessenger.hh
Referenced by DMXEventActionMessenger(), and ~DMXEventActionMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXEventActionMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/src/DMXEventActionMessenger.cc