ECCE @ EIC Software: cheprep::DefaultHepRepDefinition Class Reference
cheprep::DefaultHepRepDefinition Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepDefinition.h>
Public Member Functions
DefaultHepRepDefinition ()
~DefaultHepRepDefinition ()
void addAttDef (HEPREP::HepRepAttDef *hepRepAttDef)
void addAttDef (std::string name, std::string desc, std::string type, std::string extra)
std::set< HEPREP::HepRepAttDef * > getAttDefsFromNode ()
HEPREP::HepRepAttDef * getAttDefFromNode (std::string lowerCaseName)
HEPREP::HepRepAttDef * getAttDef (std::string name)=0
HEPREP::HepRepAttValue * getAttValue (std::string name)=0
Public Member Functions inherited from cheprep::DefaultHepRepAttribute
DefaultHepRepAttribute ()
~DefaultHepRepAttribute ()
std::set
< HEPREP::HepRepAttValue * > getAttValuesFromNode ()
void addAttValue (HEPREP::HepRepAttValue *hepRepAttValue)
void addAttValue (std::string key, char *value, int showLabel)
void addAttValue (std::string key, std::string value, int showLabel)
void addAttValue (std::string key, int value, int showLabel)
void addAttValue (std::string key, int64 value, int showLabel)
void addAttValue (std::string key, double value, int showLabel)
void addAttValue (std::string key, bool value, int showLabel)
void addAttValue (std::string key, std::vector< double > value, int showLabel)
void addAttValue (std::string key, double red, double green, double blue, double alpha, int showLabel)
HEPREP::HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)
HEPREP::HepRepAttValue * removeAttValue (std::string key)
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
Public Member Functions inherited from HEPREP::HepRepDefinition
virtual ~HepRepDefinition ()
Destructor.
Private Attributes
std::map< std::string,
HEPREP::HepRepAttDef * > attDefs
Detailed Description
Definition at line 21 of file DefaultHepRepDefinition.h.
View newest version in sPHENIX GitHub at line 21 of file DefaultHepRepDefinition.h
Constructor & Destructor Documentation
cheprep::DefaultHepRepDefinition::DefaultHepRepDefinition ()
Definition at line 17 of file DefaultHepRepDefinition.cc.
View newest version in sPHENIX GitHub at line 17 of file DefaultHepRepDefinition.cc
cheprep::DefaultHepRepDefinition::~DefaultHepRepDefinition ()
Definition at line 21 of file DefaultHepRepDefinition.cc.
View newest version in sPHENIX GitHub at line 21 of file DefaultHepRepDefinition.cc
References getAttDefsFromNode().
Member Function Documentation
void cheprep::DefaultHepRepDefinition::addAttDef (HEPREP::HepRepAttDef * attDef) virtual
Adds an attdef.
Parameters
attDef to be added.
Implements HEPREP::HepRepDefinition.
Definition at line 36 of file DefaultHepRepDefinition.cc.
View newest version in sPHENIX GitHub at line 36 of file DefaultHepRepDefinition.cc
References attDefs, and HEPREP::HepRepAttDef::getLowerCaseName().
Referenced by addAttDef().
void cheprep::DefaultHepRepDefinition::addAttDef (std::string name, std::string desc, std::string category, std::string extra) virtual
Adds an attdef.
Parameters
name name of the definition.
desc description of the definition.
category category of the definition.
extra extra info of the definition.
Implements HEPREP::HepRepDefinition.
Definition at line 42 of file DefaultHepRepDefinition.cc.
View newest version in sPHENIX GitHub at line 42 of file DefaultHepRepDefinition.cc
References addAttDef().
HEPREP::HepRepAttDef* cheprep::DefaultHepRepDefinition::getAttDef (std::string name) pure virtual
Return a named attribute definition searched on this node and any parent nodes.
Parameters
name of attribute definition.
Returns
attribute definition.
Implements HEPREP::HepRepDefinition.
Implemented in cheprep::DefaultHepRepType.
HepRepAttDef * cheprep::DefaultHepRepDefinition::getAttDefFromNode (std::string lowerCaseName) virtual
Returns a named attribute definition defined on this node.
Parameters
lowerCaseName name of the attribute in lower case.
Returns
attribute definition.
Implements HEPREP::HepRepDefinition.
Definition at line 46 of file DefaultHepRepDefinition.cc.
View newest version in sPHENIX GitHub at line 46 of file DefaultHepRepDefinition.cc
References attDefs, int(), and Acts::Test::transform.
set< HepRepAttDef * > cheprep::DefaultHepRepDefinition::getAttDefsFromNode () virtual
Returns a collection of all attribute definitions defined on this node.
Returns
collection of attributes definitions.
Implements HEPREP::HepRepDefinition.
Definition at line 28 of file DefaultHepRepDefinition.cc.
View newest version in sPHENIX GitHub at line 28 of file DefaultHepRepDefinition.cc
References attDefs.
Referenced by ~DefaultHepRepDefinition().
HEPREP::HepRepAttValue* cheprep::DefaultHepRepDefinition::getAttValue (std::string name) pure virtual
Returns the attValue specified by name. This attValue is normally searched on the node itself and then on its type, moving up the typetree.
Parameters
name of attribute value.
Returns
attribute value.
Implements cheprep::DefaultHepRepAttribute.
Implemented in cheprep::DefaultHepRepType.
Member Data Documentation
std::map<std::string, HEPREP::HepRepAttDef*> cheprep::DefaultHepRepDefinition::attDefs private
Definition at line 24 of file DefaultHepRepDefinition.h.
View newest version in sPHENIX GitHub at line 24 of file DefaultHepRepDefinition.h
Referenced by addAttDef(), getAttDefFromNode(), and getAttDefsFromNode().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepDefinition.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/DefaultHepRepDefinition.cc