ECCE @ EIC Software: CLHEP::HepBoostY Class Reference
CLHEP::HepBoostY Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/BoostY.h>
Public Member Functions
HepBoostY ()
HepBoostY (const HepBoostY &b)
HepBoostY (HepBoostY &&b)=default
HepBoostY & operator= (const HepBoostY &m)
HepBoostY & operator= (HepBoostY &&m)=default
HepBoostY & set (double beta)
HepBoostY (double beta)
double beta () const
double gamma () const
Hep3Vector boostVector () const
Hep3Vector getDirection () const
double xx () const
double xy () const
double xz () const
double xt () const
double yx () const
double yy () const
double yz () const
double yt () const
double zx () const
double zy () const
double zz () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
HepRep4x4 rep4x4 () const
HepRep4x4Symmetric rep4x4Symmetric () const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
int compare (const HepBoostY &b) const
bool operator== (const HepBoostY &b) const
bool operator!= (const HepBoostY &b) const
bool operator<= (const HepBoostY &b) const
bool operator>= (const HepBoostY &b) const
bool operator< (const HepBoostY &b) const
bool operator> (const HepBoostY &b) const
bool isIdentity () const
double distance2 (const HepBoostY &b) const
double distance2 (const HepBoost &b) const
double distance2 (const HepRotation &r) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoostY &b) const
double howNear (const HepBoost &b) const
double howNear (const HepRotation &r) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoostY &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepBoost &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepBoostY operator* (const HepBoostY &b) const
HepLorentzRotation operator* (const HepBoost &b) const
HepLorentzRotation operator* (const HepRotation &r) const
HepLorentzRotation operator* (const HepLorentzRotation &lt) const
HepBoostY inverse () const
HepBoostY & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepLorentzVector vectorMultiplication (const HepLorentzVector &w) const
HepLorentzRotation matrixMultiplication (const HepRep4x4 &m) const
HepLorentzRotation matrixMultiplication (const HepRep4x4Symmetric &m) const
HepBoostY (double beta, double gamma)
Protected Attributes
double beta_
double gamma_
Friends
HepBoostY inverseOf (const HepBoostY &b)
Detailed Description
Author
Definition at line 41 of file BoostY.h.
View newest version in sPHENIX GitHub at line 41 of file BoostY.h
Constructor & Destructor Documentation
CLHEP::HepBoostY::HepBoostY () inline
Referenced by operator*().
CLHEP::HepBoostY::HepBoostY (const HepBoostY & b) inline
CLHEP::HepBoostY::HepBoostY (HepBoostY && b) inline default
CLHEP::HepBoostY::HepBoostY (double beta) inline
CLHEP::HepBoostY::HepBoostY (double beta, double gamma) inline protected
Member Function Documentation
double CLHEP::HepBoostY::beta () const inline
Referenced by operator*().
Hep3Vector CLHEP::HepBoostY::boostVector () const inline
Referenced by decompose().
HepLorentzVector CLHEP::HepBoostY::col1 () const inline
HepLorentzVector CLHEP::HepBoostY::col2 () const inline
HepLorentzVector CLHEP::HepBoostY::col3 () const inline
HepLorentzVector CLHEP::HepBoostY::col4 () const inline
int CLHEP::HepBoostY::compare (const HepBoostY & b) const inline
void CLHEP::HepBoostY::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 56 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 56 of file BoostY.cc
References boostVector().
void CLHEP::HepBoostY::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 63 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 63 of file BoostY.cc
References boostVector().
void CLHEP::HepBoostY::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 68 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 68 of file BoostY.cc
References boostVector().
void CLHEP::HepBoostY::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 75 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 75 of file BoostY.cc
References boostVector().
double CLHEP::HepBoostY::distance2 (const HepBoostY & b) const inline
Referenced by distance2(), and isNear().
double CLHEP::HepBoostY::distance2 (const HepBoost & b) const
Definition at line 82 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 82 of file BoostY.cc
References CLHEP::HepBoost::distance2().
double CLHEP::HepBoostY::distance2 (const HepRotation & r) const
Definition at line 86 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 86 of file BoostY.cc
References norm2(), and CLHEP::HepRotation::norm2().
double CLHEP::HepBoostY::distance2 (const HepLorentzRotation & lt) const
Definition at line 92 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 92 of file BoostY.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
double CLHEP::HepBoostY::gamma () const inline
Hep3Vector CLHEP::HepBoostY::getDirection () const inline
static double CLHEP::HepBoostY::getTolerance () inline static
double CLHEP::HepBoostY::howNear (const HepBoostY & b) const inline
double CLHEP::HepBoostY::howNear (const HepBoost & b) const inline
double CLHEP::HepBoostY::howNear (const HepRotation & r) const inline
double CLHEP::HepBoostY::howNear (const HepLorentzRotation & lt) const inline
HepBoostY CLHEP::HepBoostY::inverse () const inline
HepBoostY& CLHEP::HepBoostY::invert () inline
bool CLHEP::HepBoostY::isIdentity () const inline
bool CLHEP::HepBoostY::isNear (const HepBoostY & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoostY::isNear (const HepBoost & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoostY::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 101 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 101 of file BoostY.cc
References norm2(), and CLHEP::HepRotation::norm2().
bool CLHEP::HepBoostY::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 108 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 108 of file BoostY.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
HepLorentzRotation CLHEP::HepBoostY::matrixMultiplication (const HepRep4x4 & m) const protected
HepLorentzRotation CLHEP::HepBoostY::matrixMultiplication (const HepRep4x4Symmetric & m) const protected
double CLHEP::HepBoostY::norm2 () const inline
Referenced by distance2(), and isNear().
bool CLHEP::HepBoostY::operator!= (const HepBoostY & b) const inline
HepLorentzVector CLHEP::HepBoostY::operator() (const HepLorentzVector & w) const inline
HepLorentzVector CLHEP::HepBoostY::operator* (const HepLorentzVector & w) const inline
HepBoostY CLHEP::HepBoostY::operator* (const HepBoostY & b) const
Definition at line 138 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 138 of file BoostY.cc
References beta(), and HepBoostY().
HepLorentzRotation CLHEP::HepBoostY::operator* (const HepBoost & b) const
Definition at line 141 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 141 of file BoostY.cc
References b.
HepLorentzRotation CLHEP::HepBoostY::operator* (const HepRotation & r) const
Definition at line 145 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 145 of file BoostY.cc
References r.
HepLorentzRotation CLHEP::HepBoostY::operator* (const HepLorentzRotation & lt) const
Definition at line 149 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 149 of file BoostY.cc
bool CLHEP::HepBoostY::operator< (const HepBoostY & b) const inline
bool CLHEP::HepBoostY::operator<= (const HepBoostY & b) const inline
HepBoostY& CLHEP::HepBoostY::operator= (const HepBoostY & m) inline
HepBoostY& CLHEP::HepBoostY::operator= (HepBoostY && m) inline default
bool CLHEP::HepBoostY::operator== (const HepBoostY & b) const inline
bool CLHEP::HepBoostY::operator> (const HepBoostY & b) const inline
bool CLHEP::HepBoostY::operator>= (const HepBoostY & b) const inline
std::ostream & CLHEP::HepBoostY::print (std::ostream & os) const
Definition at line 156 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 156 of file BoostY.cc
References beta_, and gamma_.
void CLHEP::HepBoostY::rectify ()
Definition at line 121 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 121 of file BoostY.cc
References beta_, and gamma_.
HepRep4x4 CLHEP::HepBoostY::rep4x4 () const
Definition at line 38 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 38 of file BoostY.cc
References beta_, and gamma_.
HepRep4x4Symmetric CLHEP::HepBoostY::rep4x4Symmetric () const
Definition at line 46 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 46 of file BoostY.cc
References beta_, and gamma_.
HepLorentzVector CLHEP::HepBoostY::row1 () const inline
HepLorentzVector CLHEP::HepBoostY::row2 () const inline
HepLorentzVector CLHEP::HepBoostY::row3 () const inline
HepLorentzVector CLHEP::HepBoostY::row4 () const inline
HepBoostY & CLHEP::HepBoostY::set (double beta)
Definition at line 22 of file BoostY.cc.
View newest version in sPHENIX GitHub at line 22 of file BoostY.cc
References beta_, and gamma_.
static double CLHEP::HepBoostY::setTolerance (double tol) inline static
double CLHEP::HepBoostY::tt () const inline
double CLHEP::HepBoostY::tx () const inline
double CLHEP::HepBoostY::ty () const inline
double CLHEP::HepBoostY::tz () const inline
HepLorentzVector CLHEP::HepBoostY::vectorMultiplication (const HepLorentzVector & w) const inline protected
double CLHEP::HepBoostY::xt () const inline
double CLHEP::HepBoostY::xx () const inline
double CLHEP::HepBoostY::xy () const inline
double CLHEP::HepBoostY::xz () const inline
double CLHEP::HepBoostY::yt () const inline
double CLHEP::HepBoostY::yx () const inline
double CLHEP::HepBoostY::yy () const inline
double CLHEP::HepBoostY::yz () const inline
double CLHEP::HepBoostY::zt () const inline
double CLHEP::HepBoostY::zx () const inline
double CLHEP::HepBoostY::zy () const inline
double CLHEP::HepBoostY::zz () const inline
Friends And Related Function Documentation
HepBoostY inverseOf (const HepBoostY & b) friend
Member Data Documentation
double CLHEP::HepBoostY::beta_ protected
Definition at line 211 of file BoostY.h.
View newest version in sPHENIX GitHub at line 211 of file BoostY.h
Referenced by print(), rectify(), rep4x4(), rep4x4Symmetric(), and set().
double CLHEP::HepBoostY::gamma_ protected
Definition at line 212 of file BoostY.h.
View newest version in sPHENIX GitHub at line 212 of file BoostY.h
Referenced by print(), rectify(), rep4x4(), rep4x4Symmetric(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/BoostY.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/BoostY.cc