ECCE @ EIC Software: G4INCL::CrossSections Namespace Reference
G4INCL::CrossSections Namespace Reference
Functions
G4double elastic (Particle const *const p1, Particle const *const p2)
G4double total (Particle const *const p1, Particle const *const p2)
G4double NDeltaToNN (Particle const *const p1, Particle const *const p2)
G4double NNToNDelta (Particle const *const p1, Particle const *const p2)
G4double NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2)
G4double piNToDelta (Particle const *const p1, Particle const *const p2)
G4double piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2)
G4double piNToEtaN (Particle const *const p1, Particle const *const p2)
G4double piNToOmegaN (Particle const *const p1, Particle const *const p2)
G4double piNToEtaPrimeN (Particle const *const p1, Particle const *const p2)
G4double etaNToPiN (Particle const *const p1, Particle const *const p2)
G4double etaNToPiPiN (Particle const *const p1, Particle const *const p2)
G4double omegaNToPiN (Particle const *const p1, Particle const *const p2)
G4double omegaNToPiPiN (Particle const *const p1, Particle const *const p2)
G4double etaPrimeNToPiN (Particle const *const p1, Particle const *const p2)
G4double NNToNNEta (Particle const *const p1, Particle const *const p2)
G4double NNToNNEtaExclu (Particle const *const p1, Particle const *const p2)
G4double NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
G4double NNToNDeltaEta (Particle const *const p1, Particle const *const p2)
G4double NNToNNOmega (Particle const *const p1, Particle const *const p2)
G4double NNToNNOmegaExclu (Particle const *const p1, Particle const *const p2)
G4double NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
G4double NNToNDeltaOmega (Particle const *const p1, Particle const *const p2)
G4double NNToNLK (Particle const *const p1, Particle const *const p2)
Strange cross sections.
G4double NNToNSK (Particle const *const p1, Particle const *const p2)
G4double NNToNLKpi (Particle const *const p1, Particle const *const p2)
G4double NNToNSKpi (Particle const *const p1, Particle const *const p2)
G4double NNToNLK2pi (Particle const *const p1, Particle const *const p2)
G4double NNToNSK2pi (Particle const *const p1, Particle const *const p2)
G4double NNToNNKKb (Particle const *const p1, Particle const *const p2)
G4double NNToMissingStrangeness (Particle const *const p1, Particle const *const p2)
G4double NDeltaToNLK (Particle const *const p1, Particle const *const p2)
G4double NDeltaToNSK (Particle const *const p1, Particle const *const p2)
G4double NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2)
G4double NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2)
G4double NDeltaToNNKKb (Particle const *const p1, Particle const *const p2)
G4double NpiToLK (Particle const *const p1, Particle const *const p2)
G4double NpiToSK (Particle const *const p1, Particle const *const p2)
G4double p_pimToSzKz (Particle const *const p1, Particle const *const p2)
G4double p_pimToSmKp (Particle const *const p1, Particle const *const p2)
G4double p_pizToSzKp (Particle const *const p1, Particle const *const p2)
G4double NpiToLKpi (Particle const *const p1, Particle const *const p2)
G4double NpiToSKpi (Particle const *const p1, Particle const *const p2)
G4double NpiToLK2pi (Particle const *const p1, Particle const *const p2)
G4double NpiToSK2pi (Particle const *const p1, Particle const *const p2)
G4double NpiToNKKb (Particle const *const p1, Particle const *const p2)
G4double NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2)
G4double NLToNS (Particle const *const p1, Particle const *const p2)
G4double NSToNL (Particle const *const p1, Particle const *const p2)
G4double NSToNS (Particle const *const p1, Particle const *const p2)
G4double NKToNK (Particle const *const p1, Particle const *const p2)
G4double NKToNKpi (Particle const *const p1, Particle const *const p2)
G4double NKToNK2pi (Particle const *const p1, Particle const *const p2)
G4double NKbToNKb (Particle const *const p1, Particle const *const p2)
G4double NKbToSpi (Particle const *const p1, Particle const *const p2)
G4double NKbToLpi (Particle const *const p1, Particle const *const p2)
G4double NKbToS2pi (Particle const *const p1, Particle const *const p2)
G4double NKbToL2pi (Particle const *const p1, Particle const *const p2)
G4double NKbToNKbpi (Particle const *const p1, Particle const *const p2)
G4double NKbToNKb2pi (Particle const *const p1, Particle const *const p2)
G4double NYelastic (Particle const *const p1, Particle const *const p2)
G4double NKbelastic (Particle const *const p1, Particle const *const p2)
G4double NKelastic (Particle const *const p1, Particle const *const p2)
G4double calculateNNAngularSlope (G4double energyCM, G4int iso)
Calculate the slope of the NN DDXS.
G4double interactionDistanceNN (const ParticleSpecies &aSpecies, const G4double kineticEnergy)
Compute the "interaction distance".
G4double interactionDistancePiN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
G4double interactionDistanceKN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
G4double interactionDistanceKbarN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
G4double interactionDistanceYN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
void setCrossSections (ICrossSections *c)
void deleteCrossSections ()
void initialize (Config const *const theConfig)
Function Documentation
G4double G4INCL::CrossSections::calculateNNAngularSlope (G4double energyCM, G4int iso)
Calculate the slope of the NN DDXS.
Parameters
energyCM energy in the CM frame, in MeV
iso total isospin of the system
Returns
the slope of the angular distribution, in (GeV/c)^(-2)
Definition at line 308 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 308 of file G4INCLCrossSections.cc
Referenced by G4INCL::ElasticChannel::fillFinalState().
void G4INCL::CrossSections::deleteCrossSections ()
Definition at line 462 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 462 of file G4INCLCrossSections.cc
Referenced by G4INCL::INCL::~INCL().
G4double G4INCL::CrossSections::elastic (Particle const *const p1, Particle const *const p2)
Definition at line 56 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 56 of file G4INCLCrossSections.cc
Referenced by G4QMDReaction::ApplyYourself(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4EmLEPTSPhysics::ConstructProcess(), and G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::etaNToPiN (Particle const *const p1, Particle const *const p2)
Definition at line 96 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 96 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::etaNToPiPiN (Particle const *const p1, Particle const *const p2)
Definition at line 100 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 100 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::etaPrimeNToPiN (Particle const *const p1, Particle const *const p2)
Definition at line 112 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 112 of file G4INCLCrossSections.cc
void G4INCL::CrossSections::initialize (Config const *const theConfig)
Definition at line 467 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 467 of file G4INCLCrossSections.cc
References G4INCL::Config::getCrossSectionsType(), G4INCL::Config::getMaxNumberMultipions(), G4INCL::INCL46CrossSections, INCL_WARN, G4INCL::MultiPionsAndResonancesCrossSections, G4INCL::MultiPionsCrossSections, setCrossSections(), G4INCL::StrangenessCrossSections, and G4INCL::TruncatedMultiPionsCrossSections.
Referenced by G4INCL::INCL::INCL().
G4double G4INCL::CrossSections::interactionDistanceKbarN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
Defined on the basis of the average value of the Kbar-N cross sections at the given kinetic energy.
Returns
the interaction distance
Definition at line 400 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 400 of file G4INCLCrossSections.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::Particle::getMass(), G4INCL::KMinus, G4INCL::KZeroBar, max, G4INCL::Neutron, G4INCL::Proton, G4INCL::Particle::setEnergy(), G4INCL::Math::tenPi, and total().
Referenced by G4INCL::INCL::initUniverseRadius().
G4double G4INCL::CrossSections::interactionDistanceKN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
Defined on the basis of the average value of the K-N cross sections at the given kinetic energy.
Returns
the interaction distance
Definition at line 376 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 376 of file G4INCLCrossSections.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::Particle::getMass(), G4INCL::KPlus, G4INCL::KZero, max, G4INCL::Neutron, G4INCL::Proton, G4INCL::Particle::setEnergy(), G4INCL::Math::tenPi, and total().
Referenced by G4INCL::INCL::initUniverseRadius().
G4double G4INCL::CrossSections::interactionDistanceNN (const ParticleSpecies & aSpecies, const G4double kineticEnergy)
Compute the "interaction distance".
Defined on the basis of the average value of the N-N cross sections at the given kinetic energy.
Returns
the interaction distance
Definition at line 345 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 345 of file G4INCLCrossSections.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::Particle::getMass(), max, G4INCL::Neutron, G4INCL::Proton, G4INCL::Particle::setEnergy(), G4INCL::Math::tenPi, G4INCL::ParticleSpecies::theA, and total().
Referenced by G4INCL::INCL::initMaxInteractionDistance(), and G4INCL::INCL::initUniverseRadius().
G4double G4INCL::CrossSections::interactionDistancePiN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
Defined on the basis of the average value of the pi-N cross sections at the given kinetic energy.
Returns
the interaction distance
Definition at line 312 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 312 of file G4INCLCrossSections.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::Particle::getMass(), max, G4INCL::Neutron, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::Particle::setEnergy(), G4INCL::Math::tenPi, and total().
Referenced by G4INCL::INCL::initUniverseRadius().
G4double G4INCL::CrossSections::interactionDistanceYN (const G4double projectileKineticEnergy)
Compute the "interaction distance".
Defined on the basis of the average value of the Y-N cross sections at the given kinetic energy.
Returns
the interaction distance
Definition at line 424 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 424 of file G4INCLCrossSections.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::Particle::getMass(), G4INCL::Lambda, max, G4INCL::Neutron, G4INCL::Proton, G4INCL::Particle::setEnergy(), G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, G4INCL::Math::tenPi, and total().
Referenced by G4INCL::INCL::initUniverseRadius().
G4double G4INCL::CrossSections::NDeltaToDeltaLK (Particle const *const p1, Particle const *const p2)
Definition at line 200 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 200 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NDeltaToDeltaSK (Particle const *const p1, Particle const *const p2)
Definition at line 203 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 203 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NDeltaToNLK (Particle const *const p1, Particle const *const p2)
Definition at line 194 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 194 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NDeltaToNN (Particle const *const p1, Particle const *const p2)
Definition at line 64 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 64 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NDeltaToNNKKb (Particle const *const p1, Particle const *const p2)
Definition at line 207 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 207 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NDeltaToNSK (Particle const *const p1, Particle const *const p2)
Definition at line 197 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 197 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbelastic (Particle const *const p1, Particle const *const p2)
Definition at line 154 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 154 of file G4INCLCrossSections.cc
G4double G4INCL::CrossSections::NKbToL2pi (Particle const *const p1, Particle const *const p2)
Definition at line 295 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 295 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbToLpi (Particle const *const p1, Particle const *const p2)
Definition at line 287 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 287 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbToNKb (Particle const *const p1, Particle const *const p2)
Definition at line 279 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 279 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbToNKb2pi (Particle const *const p1, Particle const *const p2)
Definition at line 303 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 303 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbToNKbpi (Particle const *const p1, Particle const *const p2)
Definition at line 299 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 299 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbToS2pi (Particle const *const p1, Particle const *const p2)
Definition at line 291 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 291 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKbToSpi (Particle const *const p1, Particle const *const p2)
Definition at line 283 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 283 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKelastic (Particle const *const p1, Particle const *const p2)
Definition at line 158 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 158 of file G4INCLCrossSections.cc
G4double G4INCL::CrossSections::NKToNK (Particle const *const p1, Particle const *const p2)
Definition at line 267 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 267 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKToNK2pi (Particle const *const p1, Particle const *const p2)
Definition at line 275 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 275 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NKToNKpi (Particle const *const p1, Particle const *const p2)
Definition at line 271 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 271 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NLToNS (Particle const *const p1, Particle const *const p2)
Definition at line 255 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 255 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToMissingStrangeness (Particle const *const p1, Particle const *const p2)
Definition at line 190 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 190 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNDelta (Particle const *const p1, Particle const *const p2)
Definition at line 68 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 68 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNDeltaEta (Particle const *const p1, Particle const *const p2)
Definition at line 128 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 128 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNDeltaOmega (Particle const *const p1, Particle const *const p2)
Definition at line 145 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 145 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNLK (Particle const *const p1, Particle const *const p2)
Strange cross sections.
Definition at line 162 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 162 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNLK2pi (Particle const *const p1, Particle const *const p2)
Definition at line 178 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 178 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNLKpi (Particle const *const p1, Particle const *const p2)
Definition at line 170 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 170 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNNEta (Particle const *const p1, Particle const *const p2)
Definition at line 116 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 116 of file G4INCLCrossSections.cc
G4double G4INCL::CrossSections::NNToNNEtaExclu (Particle const *const p1, Particle const *const p2)
Definition at line 120 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 120 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNNEtaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Definition at line 124 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 124 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNNKKb (Particle const *const p1, Particle const *const p2)
Definition at line 186 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 186 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNNOmega (Particle const *const p1, Particle const *const p2)
Definition at line 133 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 133 of file G4INCLCrossSections.cc
G4double G4INCL::CrossSections::NNToNNOmegaExclu (Particle const *const p1, Particle const *const p2)
Definition at line 137 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 137 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNNOmegaxPi (const G4int xpi, Particle const *const p1, Particle const *const p2)
Definition at line 141 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 141 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNSK (Particle const *const p1, Particle const *const p2)
Definition at line 166 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 166 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNSK2pi (Particle const *const p1, Particle const *const p2)
Definition at line 182 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 182 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToNSKpi (Particle const *const p1, Particle const *const p2)
Definition at line 174 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 174 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NNToxPiNN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Definition at line 72 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 72 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToLK (Particle const *const p1, Particle const *const p2)
Definition at line 211 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 211 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToLK2pi (Particle const *const p1, Particle const *const p2)
Definition at line 239 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 239 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToLKpi (Particle const *const p1, Particle const *const p2)
Definition at line 231 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 231 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToMissingStrangeness (Particle const *const p1, Particle const *const p2)
Definition at line 251 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 251 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToNKKb (Particle const *const p1, Particle const *const p2)
Definition at line 247 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 247 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToSK (Particle const *const p1, Particle const *const p2)
Definition at line 215 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 215 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToSK2pi (Particle const *const p1, Particle const *const p2)
Definition at line 243 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 243 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NpiToSKpi (Particle const *const p1, Particle const *const p2)
Definition at line 235 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 235 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NSToNL (Particle const *const p1, Particle const *const p2)
Definition at line 259 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 259 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NSToNS (Particle const *const p1, Particle const *const p2)
Definition at line 263 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 263 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::NYelastic (Particle const *const p1, Particle const *const p2)
Definition at line 150 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 150 of file G4INCLCrossSections.cc
G4double G4INCL::CrossSections::omegaNToPiN (Particle const *const p1, Particle const *const p2)
Definition at line 104 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 104 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::omegaNToPiPiN (Particle const *const p1, Particle const *const p2)
Definition at line 108 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 108 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::p_pimToSmKp (Particle const *const p1, Particle const *const p2)
Definition at line 219 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 219 of file G4INCLCrossSections.cc
Referenced by G4INCL::NpiToSKChannel::fillFinalState().
G4double G4INCL::CrossSections::p_pimToSzKz (Particle const *const p1, Particle const *const p2)
Definition at line 223 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 223 of file G4INCLCrossSections.cc
Referenced by G4INCL::NpiToSKChannel::fillFinalState().
G4double G4INCL::CrossSections::p_pizToSzKp (Particle const *const p1, Particle const *const p2)
Definition at line 227 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 227 of file G4INCLCrossSections.cc
Referenced by G4INCL::NpiToSKChannel::fillFinalState().
G4double G4INCL::CrossSections::piNToDelta (Particle const *const p1, Particle const *const p2)
Definition at line 76 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 76 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::piNToEtaN (Particle const *const p1, Particle const *const p2)
Definition at line 84 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 84 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::piNToEtaPrimeN (Particle const *const p1, Particle const *const p2)
Definition at line 92 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 92 of file G4INCLCrossSections.cc
G4double G4INCL::CrossSections::piNToOmegaN (Particle const *const p1, Particle const *const p2)
Definition at line 88 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 88 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
G4double G4INCL::CrossSections::piNToxPiN (const G4int xpi, Particle const *const p1, Particle const *const p2)
Definition at line 80 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 80 of file G4INCLCrossSections.cc
Referenced by G4INCL::BinaryCollisionAvatar::getChannel().
void G4INCL::CrossSections::setCrossSections (ICrossSections * c)
Definition at line 458 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 458 of file G4INCLCrossSections.cc
References c.
Referenced by initialize().
G4double G4INCL::CrossSections::total (Particle const *const p1, Particle const *const p2)
Definition at line 60 of file G4INCLCrossSections.cc.
View newest version in sPHENIX GitHub at line 60 of file G4INCLCrossSections.cc
Referenced by G4ParticleHPThermalScattering::ApplyYourself(), G4Voxelizer::BuildBitmasks(), G4Voxelizer::BuildReduceVoxels2(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4ParticleHPThermalScattering::get_secondary_energy_from_E_P_E_isoAng(), G4INCL::BinaryCollisionAvatar::getChannel(), G4Volant::getTotalMass(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPList::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4ParticleHPVector::Init(), G4ParticleHPVector::IntegrateAndNormalise(), G4GeneralParticleSourceData::IntensityNormalise(), interactionDistanceKbarN(), interactionDistanceKN(), interactionDistanceNN(), interactionDistancePiN(), interactionDistanceYN(), G4SPBaryon::MatchDiQuarkAndGetQuark(), Acts::MaterialComposition::MaterialComposition(), G4VUserMPIrunMerger::Merge(), G4MPIscorerMerger::Merge(), G4INCL::InteractionAvatar::preInteractionBlocking(), CexmcRunAction::PrintResults(), G4ParticleHPThermalScattering::readAnE_P_E_isoAng(), G4GeometryManager::ReportVoxelStats(), G4LENDCombinedCrossSection::SelectChannel(), G4LENDGammaCrossSection::SelectChannel(), and G4Voxelizer::Voxelize().