ECCE @ EIC Software: PhysicsList Class Reference
PhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysicsList.hh>
Inherits G4VModularPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4UImessenger, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VUserPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, G4VUserPhysicsList, G4VUserPhysicsList, G4VModularPhysicsList, G4VModularPhysicsList, and G4VModularPhysicsList.
Public Member Functions
PhysicsList ()
~PhysicsList ()
void ConstructParticle ()
void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void SetCuts ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
void SetCutForPositron (G4double)
PhysicsList ()
~PhysicsList ()
void ConstructParticle ()
void ConstructProcess ()
void AddPhysicsList (const G4String &name)
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void AddStepMax ()
G4StepLimiter * GetStepMaxProcess ()
PhysicsList ()
virtual ~PhysicsList ()
void SetGammaCut (G4double)
void SetElectronCut (G4double)
void SetPositronCut (G4double)
void SetProtonCut (G4double)
PhysicsList ()
~PhysicsList ()
void SetGammaCut (G4double)
void SetElectronCut (G4double)
void SetPositronCut (G4double)
void SetProtonCut (G4double)
PhysicsList ()
virtual ~PhysicsList ()
void ConstructParticle ()
void SetCuts ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
void SetCutForPositron (G4double)
void AddPhysicsList (const G4String &name)
void ConstructProcess ()
void AddStepMax ()
void AddPackage (const G4String &name)
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void AddPhysicsList (const G4String &name)
PhysicsList (DetectorConstruction *)
~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void AddDecay ()
void AddRadioactiveDecay ()
void AddStepMax ()
void GetRange (G4double)
G4VProcess * GetProcess (const G4String &) const
PhysicsList (DetectorConstruction *ptr)
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void SetXTRModel (const G4String &name)
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddDecay ()
void AddRadioactiveDecay ()
void AddStepMax ()
StepMax * GetStepMaxProcess ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddDecay ()
void AddStepMax ()
StepMax * GetStepMaxProcess ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void AddStepMax ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void SetAnalyticSR (G4bool val)
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void AddStepMax ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
PhysicsList ()
~PhysicsList ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void ConstructHighEnergy ()
void AddStepMax ()
void SetGammaToMuPairFac (G4double)
void SetAnnihiToMuPairFac (G4double)
void SetAnnihiToHadronFac (G4double)
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
StepMax * GetStepMaxProcess ()
PhysicsList (DetectorConstruction *)
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void SetCuts ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void AddStepMax ()
PhysicsList ()
~PhysicsList ()
PhysicsList ()
~PhysicsList ()
PhysicsList ()
~PhysicsList ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void SetCuts ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void SetLDMPhotonMass (G4double val)
void SetLDMHiMass (G4double val)
PhysicsList ()
~PhysicsList ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void List ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructProcess ()
virtual void SetCuts ()
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
virtual ~PhysicsList ()
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
virtual ~PhysicsList ()
PhysicsList ()
virtual ~PhysicsList ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
PhysicsList ()
virtual ~PhysicsList ()
void SetGammaCut (G4double)
void SetElectronCut (G4double)
void SetPositronCut (G4double)
void SetProtonCut (G4double)
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
void AddMaxStepSize ()
PhysicsList ()
~PhysicsList () override
void ConstructParticle () override
void ConstructProcess () override
void RegisterConstructor (const G4String &name)
PhysicsList ()
virtual ~PhysicsList ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
PhysicsList ()
virtual ~PhysicsList ()
void SetGammaCut (G4double)
void SetElectronCut (G4double)
void SetPositronCut (G4double)
void SetProtonCut (G4double)
void SetNumberOfSplit (G4int numberOfSplit)
G4int GetNumberOfSplit ()
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
PhysicsList ()
virtual ~PhysicsList ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddTrackingCut ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddDecay ()
void AddStepMax ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddDecay ()
void AddStepMax ()
PhysicsList (DetectorConstruction *)
~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
virtual void SetCuts ()
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
void AddPhysicsList (const G4String &name)
virtual void ConstructProcess ()
void AddStepMax ()
PhysicsList ()
virtual ~PhysicsList ()
void ConstructParticle ()
void ConstructProcess ()
void AddPhysicsList (const G4String &)
void SetVerbose (G4int val)
PhysicsList ()
virtual ~PhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void AddPhysicsList (const G4String &name)
void AddStepMax ()
PhysicsList ()
~PhysicsList ()
virtual void SetCuts ()
PhysicsList ()
~PhysicsList ()
PhysicsList ()
~PhysicsList ()
virtual void ConstructParticle ()
virtual void SetCuts ()
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Protected Member Functions
void ConstructBosons ()
void ConstructLeptons ()
void ConstructBarions ()
void ConstructGeneral ()
void ConstructEM ()
void ConstructParticle ()
void ConstructProcess ()
void SetCuts ()
void ConstructParticle ()
void ConstructProcess ()
void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructBarions ()
void ConstructGeneral ()
void ConstructEM ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructGeneral ()
void ConstructEM ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructBarions ()
void ConstructGeneral ()
void ConstructEM ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructBarions ()
void ConstructGeneral ()
void ConstructEM ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructBarions ()
void ConstructGeneral ()
void ConstructEM ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void SetCuts ()
virtual void SetCuts ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Private Member Functions
void AddStepMax ()
void ConstructEM ()
void AddIonGasModels ()
PhysicsList & operator= (const PhysicsList &right)
PhysicsList (const PhysicsList &)
void AddDarkMatter ()
void SetBuilderList0 (G4bool flagHP=false)
void SetBuilderList1 (G4bool flagHP=false)
void SetBuilderList2 ()
PhysicsList & operator= (const PhysicsList &right)
PhysicsList (const PhysicsList &)
Private Attributes
G4double cutForGamma
G4double cutForElectron
G4double cutForPositron
G4double currentDefaultCut
G4VPhysicsConstructor * emPhysicsList
G4String emName
PhysicsListMessenger * pMessenger
G4String fEmName
G4VPhysicsConstructor * fEmPhysicsList
G4VPhysicsConstructor * fDecPhysicsList
G4StepLimiter * fStepMaxProcess = nullptr
PhysicsListMessenger * fMessenger
G4double cutForProton
G4double fCutForGamma
G4double fCutForElectron
G4double fCutForPositron
G4double fCutForProton
G4EmConfigurator em_config
G4bool helIsRegisted
G4bool bicIsRegisted
G4bool biciIsRegisted
G4bool locIonIonInelasticIsRegistered
G4bool radioactiveDecayIsRegisted
G4VPhysicsConstructor * decPhysicsList
std::vector
< G4VPhysicsConstructor * > hadronPhys
DetectorConstruction * fDet
G4VPhysicsConstructor * fDecayPhysicsList
TransitionRadiationPhysics * fXTRPhysicsList
G4int fVerbose
G4bool fSRType
PhysicsListMessenger * fMess
G4DecayPhysics * fDecayPhysics
G4VPhysicsConstructor * fMuNuclPhysicsList
G4VPhysicsConstructor * fDecayPhysics
G4VPhysicsConstructor * fHadPhysicsList
StepMax * fStepMaxProcess
PhysicsListMessenger * fMes
G4bool fHelIsRegisted
G4bool fBicIsRegisted
G4bool fBiciIsRegisted
std::vector
< G4VPhysicsConstructor * > fHadronPhys
DetectorConstruction * fDetectorConstruction
G4bool fGnucIsRegisted
G4bool fStopIsRegisted
G4double fLDMPhotonMass
G4double fLDMHiMass
G4bool fLDMPhoton
G4bool fLDMHi
G4VPhysicsConstructor * fParticleList
G4PhysListFactoryMessenger * fFactMessenger
G4VPhysicsConstructor * fHadronElastic
G4VPhysicsConstructor * fHadronInelastic
G4VPhysicsConstructor * fIonElastic
G4VPhysicsConstructor * fIonInelastic
G4VPhysicsConstructor * fGammaNuclear
G4VPhysicsConstructor * fElectromagnetic
G4VPhysicsConstructor * fDecay
G4VPhysicsConstructor * fRadioactiveDecay
G4VPhysicsConstructor * fEmDNAPhysicsList
G4EmDNAChemistry * fEmDNAChemistryList
G4EmDNAChemistry_option1 * fEmDNAChemistryList1
G4String fPhysDNAName
std::unique_ptr
< G4VPhysicsConstructor > fDNAPhysicsList
std::unique_ptr
< G4EmDNAChemistry_option2 > fChemistryList_option2
G4EmDNAPhysicsActivator * fDNAActivator
G4bool fHadronic
G4UIcmdWithAnInteger * fpNumberOfSplit
G4double fNumberOfSplit
DetectorConstruction * fDetector
G4bool fIonIsRegisted
Static Private Attributes
static G4ThreadLocal StepMax * fStepMaxProcess
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 46 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 46 of file PhysicsList.hh
Constructor & Destructor Documentation
PhysicsList::PhysicsList ()
RegisterPhysics(new G4HadronElasticPhysicsXS(verb));
Definition at line 42 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 42 of file PhysicsList.cc
References currentDefaultCut, cutForElectron, cutForGamma, cutForPositron, emName, emPhysicsList, G4LossTableManager::Instance(), mm, pMessenger, and G4VModularPhysicsList::SetVerboseLevel().
PhysicsList::~PhysicsList ()
Definition at line 64 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 64 of file PhysicsList.cc
References pMessenger.
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList (DetectorConstruction * det)
Definition at line 84 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 84 of file PhysicsList.cc
References AddPhysicsList(), eV, fMessenger, G4ProductionCutsTable::GetProductionCutsTable(), GeV, mm, G4VUserPhysicsList::SetDefaultCutValue(), G4ProductionCutsTable::SetEnergyRange(), and G4VModularPhysicsList::SetVerboseLevel().
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList (DetectorConstruction * ptr)
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList (DetectorConstruction *)
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList (const PhysicsList &) private
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList () explicit
PhysicsList::~PhysicsList () override
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList (DetectorConstruction *)
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList (const PhysicsList &) private
PhysicsList::PhysicsList ()
virtual PhysicsList::~PhysicsList () virtual
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
PhysicsList::PhysicsList ()
PhysicsList::~PhysicsList ()
Member Function Documentation
void PhysicsList::AddDarkMatter () private
Definition at line 207 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 207 of file PhysicsList.cc
References G4ProcessManager::AddProcess(), fLDMPhoton, G4cout, G4endl, G4ParticleDefinition::GetProcessManager(), and G4Proton::Proton().
void PhysicsList::AddDecay ()
void PhysicsList::AddDecay ()
void PhysicsList::AddDecay ()
void PhysicsList::AddDecay ()
Definition at line 244 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 244 of file PhysicsList.cc
References G4VUserPhysicsList::GetParticleIterator(), G4PhysicsListHelper::GetPhysicsListHelper(), G4Decay::IsApplicable(), particle, and G4PhysicsListHelper::RegisterProcess().
void PhysicsList::AddDecay ()
void PhysicsList::AddIonGasModels () private
Definition at line 284 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 284 of file PhysicsList.cc
References em_config, G4LossTableManager::EmConfigurator(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4LossTableManager::Instance(), MeV, source.hepunit::proton_mass_c2, G4EmConfigurator::SetExtraEmModel(), and TeV.
void PhysicsList::AddMaxStepSize ()
Definition at line 227 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 227 of file PhysicsList.cc
References G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4PhysicsListHelper::GetPhysicsListHelper(), and G4PhysicsListHelper::RegisterProcess().
void PhysicsList::AddPackage (const G4String & name)
Definition at line 95 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 95 of file PhysicsList.cc
References G4VModularPhysicsList::GetPhysics(), G4PhysListFactory::GetReferencePhysList(), G4VModularPhysicsList::RegisterPhysics(), and tmp.
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String &)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
Definition at line 190 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 190 of file PhysicsList.cc
References emName, emPhysicsList, G4cout, G4endl, and G4VModularPhysicsList::verboseLevel.
Referenced by PhysicsList(), and PhysicsListMessenger::SetNewValue().
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddPhysicsList (const G4String & name)
void PhysicsList::AddRadioactiveDecay ()
void PhysicsList::AddRadioactiveDecay ()
Definition at line 263 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 263 of file PhysicsList.cc
References G4GenericIon::GenericIon(), G4NuclideTable::GetInstance(), G4PhysicsListHelper::GetPhysicsListHelper(), picosecond, G4PhysicsListHelper::RegisterProcess(), G4RadioactiveDecay::SetARM(), and G4NuclideTable::SetThresholdOfHalfLife().
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
Definition at line 164 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 164 of file PhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), fMessenger, G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), StepMax::IsApplicable(), and particle.
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax ()
void PhysicsList::AddStepMax () private
void PhysicsList::AddTrackingCut ()
void PhysicsList::AddTrackingCut ()
Definition at line 191 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 191 of file PhysicsList.cc
References G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4PhysicsListHelper::GetPhysicsListHelper(), particle, and G4PhysicsListHelper::RegisterProcess().
void PhysicsList::AddTrackingCut ()
void PhysicsList::AddTrackingCut ()
void PhysicsList::AddTrackingCut ()
void PhysicsList::AddTrackingCut ()
void PhysicsList::AddTrackingCut ()
void PhysicsList::ConstructBarions () protected
Definition at line 79 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 79 of file PhysicsList.cc
References G4GenericIon::GenericIonDefinition(), and G4Proton::ProtonDefinition().
void PhysicsList::ConstructBarions () protected
void PhysicsList::ConstructBarions () protected
void PhysicsList::ConstructBarions () protected
void PhysicsList::ConstructBarions () protected
void PhysicsList::ConstructBosons () protected
Definition at line 63 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.cc
References G4Gamma::GammaDefinition().
void PhysicsList::ConstructBosons () protected
void PhysicsList::ConstructBosons () protected
void PhysicsList::ConstructBosons () protected
void PhysicsList::ConstructBosons () protected
void PhysicsList::ConstructBosons () protected
void PhysicsList::ConstructEM () private
void PhysicsList::ConstructEM () protected
Definition at line 129 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 129 of file PhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4VMultipleScattering::AddEmModel(), G4ProcessManager::AddProcess(), em_config, G4LossTableManager::EmConfigurator(), eV, G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), GeV, G4VAtomDeexcitation::InitialiseForNewRun(), G4LossTableManager::Instance(), keV, MeV, particle, G4VEmModel::SetActivationHighEnergyLimit(), G4VEmModel::SetActivationLowEnergyLimit(), G4LossTableManager::SetAtomDeexcitation(), G4VAtomDeexcitation::SetAuger(), G4VEmProcess::SetEmModel(), G4EmConfigurator::SetExtraEmModel(), G4VAtomDeexcitation::SetFluo(), G4VAtomDeexcitation::SetPIXE(), and TeV.
void PhysicsList::ConstructEM () protected
void PhysicsList::ConstructEM () protected
void PhysicsList::ConstructEM () protected
void PhysicsList::ConstructEM () protected
void PhysicsList::ConstructEM () protected
void PhysicsList::ConstructGeneral () protected
Definition at line 298 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 298 of file PhysicsList.cc
void PhysicsList::ConstructGeneral () protected
void PhysicsList::ConstructGeneral () protected
void PhysicsList::ConstructGeneral () protected
void PhysicsList::ConstructGeneral () protected
void PhysicsList::ConstructGeneral () protected
void PhysicsList::ConstructHighEnergy ()
Definition at line 124 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 124 of file PhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4Gamma::Gamma(), G4ParticleDefinition::GetProcessManager(), particle, and G4Positron::Positron().
void PhysicsList::ConstructLeptons () protected
Definition at line 70 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 70 of file PhysicsList.cc
References G4Electron::ElectronDefinition(), and G4Positron::PositronDefinition().
void PhysicsList::ConstructLeptons () protected
void PhysicsList::ConstructLeptons () protected
void PhysicsList::ConstructLeptons () protected
void PhysicsList::ConstructLeptons () protected
void PhysicsList::ConstructLeptons () protected
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 116 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 116 of file PhysicsList.cc
References G4Alpha::AlphaDefinition(), G4AntiKaonZero::AntiKaonZeroDefinition(), G4AntiNeutrinoE::AntiNeutrinoEDefinition(), G4AntiNeutrinoMu::AntiNeutrinoMuDefinition(), G4AntiNeutron::AntiNeutronDefinition(), G4AntiProton::AntiProtonDefinition(), G4ChargedGeantino::ChargedGeantinoDefinition(), G4Deuteron::DeuteronDefinition(), G4Electron::ElectronDefinition(), G4Eta::EtaDefinition(), G4EtaPrime::EtaPrimeDefinition(), G4Gamma::GammaDefinition(), G4Geantino::GeantinoDefinition(), G4GenericIon::GenericIonDefinition(), G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), G4KaonZero::KaonZeroDefinition(), G4KaonZeroLong::KaonZeroLongDefinition(), G4KaonZeroShort::KaonZeroShortDefinition(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), G4NeutrinoE::NeutrinoEDefinition(), G4NeutrinoMu::NeutrinoMuDefinition(), G4Neutron::NeutronDefinition(), G4OpticalPhoton::OpticalPhotonDefinition(), G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), G4PionZero::PionZeroDefinition(), G4Positron::PositronDefinition(), G4Proton::ProtonDefinition(), and G4Triton::TritonDefinition().
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructParticle () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess (void) virtual
G4EmParameters::Instance()->SetFluo(true);
Reimplemented from G4VModularPhysicsList.
Definition at line 169 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 169 of file PhysicsList.cc
References G4VUserPhysicsList::AddTransportation(), G4VPhysicsConstructor::ConstructProcess(), emPhysicsList, G4EmProcessOptions::SetBuildCSDARange(), G4EmProcessOptions::SetDEDXBinningForCSDARange(), G4EmProcessOptions::SetMaxEnergyForCSDARange(), G4EmProcessOptions::SetVerbose(), and TeV.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () override virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
virtual void PhysicsList::ConstructProcess () protected virtual
Reimplemented from G4VModularPhysicsList.
G4int PhysicsList::GetNumberOfSplit ()
Definition at line 525 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 525 of file PhysicsList.cc
References fNumberOfSplit.
G4VProcess * PhysicsList::GetProcess (const G4String & processName) const
Definition at line 317 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 317 of file PhysicsList.cc
References G4GenericIon::GenericIon(), G4ProcessManager::GetProcessList(), G4ProcessManager::GetProcessListLength(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), and k.
void PhysicsList::GetRange (G4double val)
Definition at line 299 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 299 of file PhysicsList.cc
References G4Electron::Electron(), fDet, G4BestUnit, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4LogicalVolume::GetMaterialCutsCouple(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4LossTableManager::GetRange(), DetectorConstruction::GetWorld(), G4LossTableManager::Instance(), and part.
G4StepLimiter* PhysicsList::GetStepMaxProcess () inline
Definition at line 60 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 60 of file PhysicsList.hh
References fStepMaxProcess.
StepMax* PhysicsList::GetStepMaxProcess () inline
Definition at line 62 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hh
References fStepMaxProcess.
StepMax* PhysicsList::GetStepMaxProcess () inline
Definition at line 62 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hh
References fStepMaxProcess.
StepMax* PhysicsList::GetStepMaxProcess () inline
Definition at line 63 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.hh
References fStepMaxProcess.
void PhysicsList::List ()
Definition at line 333 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 333 of file PhysicsList.cc
References G4cout, and G4endl.
PhysicsList& PhysicsList::operator= (const PhysicsList & right) private
PhysicsList& PhysicsList::operator= (const PhysicsList & right) private
void PhysicsList::RegisterConstructor (const G4String & name)
void PhysicsList::RegisterConstructor (const G4String & name)
Definition at line 110 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 110 of file PhysicsList.cc
References fEmDNAChemistryList, fEmDNAChemistryList1, fEmDNAPhysicsList, fPhysDNAName, G4cout, G4endl, G4VPhysicsConstructor::SetVerboseLevel(), and G4VModularPhysicsList::verboseLevel.
void PhysicsList::RegisterConstructor (const G4String & name)
void PhysicsList::RegisterConstructor (const G4String & name)
void PhysicsList::RegisterConstructor (const G4String & name)
void PhysicsList::RegisterConstructor (const G4String & name)
void PhysicsList::RegisterConstructor (const G4String & name)
void PhysicsList::SetAnalyticSR (G4bool val) inline
Definition at line 56 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 56 of file PhysicsList.hh
References fSRType.
void PhysicsList::SetAnnihiToHadronFac (G4double fac)
Definition at line 166 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 166 of file PhysicsList.cc
References G4ProcessTable::FindProcess(), G4cout, G4endl, G4ProcessTable::GetProcessTable(), and G4eeToHadrons::SetCrossSecFactor().
void PhysicsList::SetAnnihiToMuPairFac (G4double fac)
Definition at line 153 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 153 of file PhysicsList.cc
References G4ProcessTable::FindProcess(), G4cout, G4endl, G4ProcessTable::GetProcessTable(), and G4AnnihiToMuPair::SetCrossSecFactor().
void PhysicsList::SetBuilderList0 (G4bool flagHP = false) private
Definition at line 291 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 291 of file PhysicsList.cc
References fHadronPhys, and G4VModularPhysicsList::verboseLevel.
void PhysicsList::SetBuilderList1 (G4bool flagHP = false) private
Definition at line 306 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 306 of file PhysicsList.cc
References fHadronPhys, and G4VModularPhysicsList::verboseLevel.
void PhysicsList::SetBuilderList2 () private
Definition at line 321 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 321 of file PhysicsList.cc
References fHadronPhys, and G4VModularPhysicsList::verboseLevel.
void PhysicsList::SetCutForElectron (G4double)
void PhysicsList::SetCutForElectron (G4double cut)
Definition at line 238 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 238 of file PhysicsList.cc
References cutForElectron, G4Electron::Electron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by PhysicsListMessenger::SetNewValue().
void PhysicsList::SetCutForGamma (G4double)
void PhysicsList::SetCutForGamma (G4double cut)
Definition at line 230 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 230 of file PhysicsList.cc
References cutForGamma, G4Gamma::Gamma(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by PhysicsListMessenger::SetNewValue().
void PhysicsList::SetCutForPositron (G4double)
void PhysicsList::SetCutForPositron (G4double cut)
Definition at line 246 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 246 of file PhysicsList.cc
References cutForPositron, G4Positron::Positron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by PhysicsListMessenger::SetNewValue().
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 218 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 218 of file PhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, G4VUserPhysicsList::DumpCutValuesTable(), and G4VUserPhysicsList::SetCutValue().
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
virtual void PhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
void PhysicsList::SetElectronCut (G4double val)
Definition at line 231 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 231 of file PhysicsList.cc
References fCutForElectron.
void PhysicsList::SetElectronCut (G4double)
void PhysicsList::SetElectronCut (G4double)
void PhysicsList::SetElectronCut (G4double)
void PhysicsList::SetGammaCut (G4double val)
Definition at line 224 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 224 of file PhysicsList.cc
References fCutForGamma.
void PhysicsList::SetGammaCut (G4double)
void PhysicsList::SetGammaCut (G4double)
void PhysicsList::SetGammaCut (G4double)
void PhysicsList::SetGammaToMuPairFac (G4double fac)
Definition at line 140 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 140 of file PhysicsList.cc
References G4ProcessTable::FindProcess(), G4cout, G4endl, G4ProcessTable::GetProcessTable(), and G4GammaConversionToMuons::SetCrossSecFactor().
void PhysicsList::SetLDMHiMass (G4double val)
Definition at line 231 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 231 of file PhysicsList.cc
References fLDMHi, and fLDMHiMass.
void PhysicsList::SetLDMPhotonMass (G4double val)
Definition at line 221 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 221 of file PhysicsList.cc
References fLDMPhoton, fLDMPhotonMass, G4cout, G4endl, and GeV.
void PhysicsList::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 115 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 115 of file PhysicsList.cc
References fNumberOfSplit, fpNumberOfSplit, and G4UIcmdWithAnInteger::GetNewIntValue().
void PhysicsList::SetNumberOfSplit (G4int numberOfSplit)
Definition at line 521 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 521 of file PhysicsList.cc
References fNumberOfSplit.
void PhysicsList::SetPositronCut (G4double val)
Definition at line 238 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 238 of file PhysicsList.cc
References fCutForPositron.
void PhysicsList::SetPositronCut (G4double)
void PhysicsList::SetPositronCut (G4double)
void PhysicsList::SetPositronCut (G4double)
void PhysicsList::SetProtonCut (G4double val)
Definition at line 245 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 245 of file PhysicsList.cc
References fCutForProton.
void PhysicsList::SetProtonCut (G4double)
void PhysicsList::SetProtonCut (G4double)
void PhysicsList::SetProtonCut (G4double)
void PhysicsList::SetVerbose (G4int val) inline
Definition at line 70 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file PhysicsList.hh
References fVerbose.
void PhysicsList::SetXTRModel (const G4String & name)
Definition at line 210 of file PhysicsList.cc.
View newest version in sPHENIX GitHub at line 210 of file PhysicsList.cc
References fXTRPhysicsList, and TransitionRadiationPhysics::SetXTRModel().
Member Data Documentation
G4bool PhysicsList::biciIsRegisted private
Definition at line 73 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 73 of file PhysicsList.hh
G4bool PhysicsList::bicIsRegisted private
Definition at line 72 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 72 of file PhysicsList.hh
G4double PhysicsList::currentDefaultCut private
Definition at line 65 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file PhysicsList.hh
Referenced by PhysicsList().
G4double PhysicsList::cutForElectron private
Definition at line 63 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.hh
Referenced by PhysicsList(), SetCutForElectron(), and SetCuts().
G4double PhysicsList::cutForGamma private
Definition at line 62 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hh
Referenced by PhysicsList(), SetCutForGamma(), and SetCuts().
G4double PhysicsList::cutForPositron private
Definition at line 64 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file PhysicsList.hh
Referenced by PhysicsList(), SetCutForPositron(), and SetCuts().
G4double PhysicsList::cutForProton private
Definition at line 74 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::decPhysicsList private
Definition at line 79 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 79 of file PhysicsList.hh
G4EmConfigurator PhysicsList::em_config private
Definition at line 65 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file PhysicsList.hh
Referenced by AddIonGasModels(), and ConstructEM().
G4String PhysicsList::emName private
Definition at line 68 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 68 of file PhysicsList.hh
Referenced by AddPhysicsList(), and PhysicsList().
G4VPhysicsConstructor * PhysicsList::emPhysicsList private
Definition at line 67 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 67 of file PhysicsList.hh
Referenced by AddPhysicsList(), ConstructProcess(), and PhysicsList().
G4bool PhysicsList::fBiciIsRegisted private
Definition at line 70 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file PhysicsList.hh
G4bool PhysicsList::fBicIsRegisted private
Definition at line 69 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file PhysicsList.hh
std::unique_ptr<G4EmDNAChemistry_option2> PhysicsList::fChemistryList_option2 private
Definition at line 53 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 53 of file PhysicsList.hh
G4double PhysicsList::fCutForElectron private
Definition at line 57 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 57 of file PhysicsList.hh
Referenced by SetElectronCut().
G4double PhysicsList::fCutForGamma private
Definition at line 56 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 56 of file PhysicsList.hh
Referenced by SetGammaCut().
G4double PhysicsList::fCutForPositron private
Definition at line 58 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 58 of file PhysicsList.hh
Referenced by SetPositronCut().
G4double PhysicsList::fCutForProton private
Definition at line 59 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 59 of file PhysicsList.hh
Referenced by SetProtonCut().
G4VPhysicsConstructor* PhysicsList::fDecay private
Definition at line 56 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 56 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fDecayPhysics private
Definition at line 63 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.hh
G4VPhysicsConstructor * PhysicsList::fDecayPhysics private
Definition at line 64 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file PhysicsList.hh
G4VPhysicsConstructor * PhysicsList::fDecayPhysicsList private
Definition at line 75 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 75 of file PhysicsList.hh
G4VPhysicsConstructor * PhysicsList::fDecPhysicsList private
Definition at line 66 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 66 of file PhysicsList.hh
DetectorConstruction* PhysicsList::fDet private
Definition at line 71 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 71 of file PhysicsList.hh
Referenced by GetRange().
DetectorConstruction* PhysicsList::fDetector private
Definition at line 62 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hh
DetectorConstruction* PhysicsList::fDetectorConstruction private
Definition at line 76 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 76 of file PhysicsList.hh
G4EmDNAPhysicsActivator* PhysicsList::fDNAActivator private
Definition at line 70 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file PhysicsList.hh
std::unique_ptr<G4VPhysicsConstructor> PhysicsList::fDNAPhysicsList private
Definition at line 52 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 52 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fElectromagnetic private
Definition at line 55 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 55 of file PhysicsList.hh
G4EmDNAChemistry * PhysicsList::fEmDNAChemistryList private
Definition at line 61 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 61 of file PhysicsList.hh
Referenced by RegisterConstructor().
G4EmDNAChemistry_option1 * PhysicsList::fEmDNAChemistryList1 private
Definition at line 62 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hh
Referenced by RegisterConstructor().
G4VPhysicsConstructor * PhysicsList::fEmDNAPhysicsList private
Definition at line 60 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 60 of file PhysicsList.hh
Referenced by RegisterConstructor().
G4String PhysicsList::fEmName private
Definition at line 60 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 60 of file PhysicsList.hh
G4VPhysicsConstructor * PhysicsList::fEmPhysicsList private
Definition at line 65 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file PhysicsList.hh
G4PhysListFactoryMessenger* PhysicsList::fFactMessenger private
Definition at line 79 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 79 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fGammaNuclear private
Definition at line 54 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 54 of file PhysicsList.hh
G4bool PhysicsList::fGnucIsRegisted private
Definition at line 90 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 90 of file PhysicsList.hh
G4VPhysicsConstructor * PhysicsList::fHadPhysicsList private
Definition at line 64 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fHadronElastic private
Definition at line 50 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysicsList.hh
G4bool PhysicsList::fHadronic private
Definition at line 74 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fHadronInelastic private
Definition at line 51 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 51 of file PhysicsList.hh
std::vector< G4VPhysicsConstructor * > PhysicsList::fHadronPhys private
Definition at line 75 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 75 of file PhysicsList.hh
Referenced by SetBuilderList0(), SetBuilderList1(), and SetBuilderList2().
G4bool PhysicsList::fHelIsRegisted private
Definition at line 68 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 68 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fIonElastic private
Definition at line 52 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 52 of file PhysicsList.hh
G4VPhysicsConstructor* PhysicsList::fIonInelastic private
Definition at line 53 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 53 of file PhysicsList.hh
G4bool PhysicsList::fIonIsRegisted private
Definition at line 63 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.hh
G4bool PhysicsList::fLDMHi private
Definition at line 86 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 86 of file PhysicsList.hh
Referenced by SetLDMHiMass().
G4double PhysicsList::fLDMHiMass private
Definition at line 83 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 83 of file PhysicsList.hh
Referenced by SetLDMHiMass().
G4bool PhysicsList::fLDMPhoton private
Definition at line 85 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 85 of file PhysicsList.hh
Referenced by AddDarkMatter(), and SetLDMPhotonMass().
G4double PhysicsList::fLDMPhotonMass private
Definition at line 82 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 82 of file PhysicsList.hh
Referenced by SetLDMPhotonMass().
PhysicsListMessenger* PhysicsList::fMes private
Definition at line 79 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 79 of file PhysicsList.hh
PhysicsListMessenger* PhysicsList::fMess private
Definition at line 63 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.hh
PhysicsListMessenger * PhysicsList::fMessenger private
Definition at line 70 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file PhysicsList.hh
Referenced by AddStepMax(), and PhysicsList().
G4VPhysicsConstructor* PhysicsList::fMuNuclPhysicsList private
Definition at line 57 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 57 of file PhysicsList.hh
G4double PhysicsList::fNumberOfSplit private
Definition at line 87 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 87 of file PhysicsList.hh
Referenced by GetNumberOfSplit(), SetNewValue(), and SetNumberOfSplit().
G4VPhysicsConstructor* PhysicsList::fParticleList private
Definition at line 75 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 75 of file PhysicsList.hh
G4String PhysicsList::fPhysDNAName private
Definition at line 63 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file PhysicsList.hh
Referenced by RegisterConstructor().
G4UIcmdWithAnInteger* PhysicsList::fpNumberOfSplit private
Definition at line 81 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 81 of file PhysicsList.hh
Referenced by SetNewValue().
G4VPhysicsConstructor* PhysicsList::fRadioactiveDecay private
Definition at line 57 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 57 of file PhysicsList.hh
G4bool PhysicsList::fSRType private
Definition at line 62 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysicsList.hh
Referenced by SetAnalyticSR().
StepMax * PhysicsList::fStepMaxProcess = nullptr private
Definition at line 68 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 68 of file PhysicsList.hh
Referenced by GetStepMaxProcess().
StepMax* PhysicsList::fStepMaxProcess private
Definition at line 77 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 77 of file PhysicsList.hh
G4ThreadLocal StepMax* PhysicsList::fStepMaxProcess static private
Definition at line 83 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 83 of file PhysicsList.hh
G4bool PhysicsList::fStopIsRegisted private
Definition at line 91 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 91 of file PhysicsList.hh
G4int PhysicsList::fVerbose private
Definition at line 80 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 80 of file PhysicsList.hh
Referenced by SetVerbose().
TransitionRadiationPhysics* PhysicsList::fXTRPhysicsList private
Definition at line 77 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 77 of file PhysicsList.hh
Referenced by SetXTRModel().
std::vector<G4VPhysicsConstructor*> PhysicsList::hadronPhys private
Definition at line 80 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 80 of file PhysicsList.hh
G4bool PhysicsList::helIsRegisted private
Definition at line 71 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 71 of file PhysicsList.hh
G4bool PhysicsList::locIonIonInelasticIsRegistered private
Definition at line 74 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file PhysicsList.hh
PhysicsListMessenger * PhysicsList::pMessenger private
Definition at line 70 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file PhysicsList.hh
Referenced by PhysicsList(), and ~PhysicsList().
G4bool PhysicsList::radioactiveDecayIsRegisted private
Definition at line 75 of file PhysicsList.hh.
View newest version in sPHENIX GitHub at line 75 of file PhysicsList.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/userPrimaryGenerator/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/geometry/transforms/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/include/PhysicsList.hh
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/userPrimaryGenerator/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/geometry/transforms/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/src/PhysicsList.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/src/PhysicsList.cc