ECCE @ EIC Software: G4hParametrisedLossModel Class Reference
G4hParametrisedLossModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hParametrisedLossModel.hh>
Public Member Functions
G4hParametrisedLossModel (const G4String &name)
~G4hParametrisedLossModel ()
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const
G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const
G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4String ModelName () const
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4hParametrisedLossModel (G4hParametrisedLossModel &)
G4hParametrisedLossModel & operator= (const G4hParametrisedLossModel &right)
void InitializeMe ()
G4double StoppingPower (const G4Material *material, G4double kineticEnergy)
G4bool MolecIsInZiegler1988 (const G4Material *material)
void SetExpStopPower125 (G4double value)
G4double ChemicalFactor (G4double kineticEnergy, G4double eloss125) const
Private Attributes
G4VhElectronicStoppingPower * eStopingPowerTable
G4double theZieglerFactor
G4String modelName
G4double lowEnergyLimit
G4double highEnergyLimit
G4double expStopPower125
Detailed Description
Definition at line 60 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4hParametrisedLossModel.hh
Constructor & Destructor Documentation
G4hParametrisedLossModel::G4hParametrisedLossModel (const G4String & name)
Definition at line 74 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 74 of file G4hParametrisedLossModel.cc
References InitializeMe().
G4hParametrisedLossModel::~G4hParametrisedLossModel ()
Definition at line 127 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 127 of file G4hParametrisedLossModel.cc
References eStopingPowerTable.
G4hParametrisedLossModel::G4hParametrisedLossModel (G4hParametrisedLossModel &) private
Member Function Documentation
G4double G4hParametrisedLossModel::ChemicalFactor (G4double kineticEnergy, G4double eloss125) const private
Definition at line 389 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 389 of file G4hParametrisedLossModel.cc
References expStopPower125, G4Exp(), keV, and source.hepunit::proton_mass_c2.
Referenced by StoppingPower().
G4double G4hParametrisedLossModel::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 178 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 178 of file G4hParametrisedLossModel.cc
References highEnergyLimit.
G4double G4hParametrisedLossModel::HighEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 192 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 192 of file G4hParametrisedLossModel.cc
References highEnergyLimit.
void G4hParametrisedLossModel::InitializeMe () private
Definition at line 82 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 82 of file G4hParametrisedLossModel.cc
References cm2, eStopingPowerTable, eV, expStopPower125, G4cout, G4endl, highEnergyLimit, keV, lowEnergyLimit, MeV, modelName, and theZieglerFactor.
Referenced by G4hParametrisedLossModel().
G4bool G4hParametrisedLossModel::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 199 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 199 of file G4hParametrisedLossModel.cc
G4bool G4hParametrisedLossModel::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 207 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 207 of file G4hParametrisedLossModel.cc
G4double G4hParametrisedLossModel::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 170 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 170 of file G4hParametrisedLossModel.cc
References lowEnergyLimit.
G4double G4hParametrisedLossModel::LowEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 185 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 185 of file G4hParametrisedLossModel.cc
References lowEnergyLimit.
G4String G4hParametrisedLossModel::ModelName () const inline
Definition at line 92 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4hParametrisedLossModel.hh
References modelName.
G4bool G4hParametrisedLossModel::MolecIsInZiegler1988 (const G4Material * material) private
Definition at line 290 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 290 of file G4hParametrisedLossModel.cc
References false, G4Material::GetChemicalFormula(), G4Material::GetState(), G4Material::GetTotNbOfAtomsPerVolume(), kStateGas, numberOfMolecula, SetExpStopPower125(), theState, and true.
Referenced by StoppingPower().
G4hParametrisedLossModel& G4hParametrisedLossModel::operator= (const G4hParametrisedLossModel & right) private
void G4hParametrisedLossModel::SetExpStopPower125 (G4double value) inline private
Definition at line 109 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4hParametrisedLossModel.hh
References expStopPower125.
Referenced by MolecIsInZiegler1988().
G4double G4hParametrisedLossModel::StoppingPower (const G4Material * material, G4double kineticEnergy) private
Definition at line 215 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 215 of file G4hParametrisedLossModel.cc
References ChemicalFactor(), G4VhElectronicStoppingPower::ElectronicStoppingPower(), eStopingPowerTable, G4Material::GetAtomicNumDensityVector(), G4Material::GetAtomsVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Material::GetTotNbOfAtomsPerVolume(), G4Element::GetZ(), G4Material::GetZ(), G4VhElectronicStoppingPower::HasMaterial(), keV, modelName, MolecIsInZiegler1988(), G4VhElectronicStoppingPower::StoppingPower(), and z.
Referenced by TheValue().
G4double G4hParametrisedLossModel::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 134 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 134 of file G4hParametrisedLossModel.cc
References G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), lowEnergyLimit, modelName, source.hepunit::proton_mass_c2, StoppingPower(), and theZieglerFactor.
G4double G4hParametrisedLossModel::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 151 of file G4hParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 151 of file G4hParametrisedLossModel.cc
References G4ParticleDefinition::GetPDGMass(), lowEnergyLimit, modelName, source.hepunit::proton_mass_c2, StoppingPower(), and theZieglerFactor.
Member Data Documentation
G4VhElectronicStoppingPower* G4hParametrisedLossModel::eStopingPowerTable private
Definition at line 114 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4hParametrisedLossModel.hh
Referenced by InitializeMe(), StoppingPower(), and ~G4hParametrisedLossModel().
G4double G4hParametrisedLossModel::expStopPower125 private
Definition at line 124 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 124 of file G4hParametrisedLossModel.hh
Referenced by ChemicalFactor(), InitializeMe(), and SetExpStopPower125().
G4double G4hParametrisedLossModel::highEnergyLimit private
Definition at line 122 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4hParametrisedLossModel.hh
Referenced by HighEnergyLimit(), and InitializeMe().
G4double G4hParametrisedLossModel::lowEnergyLimit private
Definition at line 121 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4hParametrisedLossModel.hh
Referenced by InitializeMe(), LowEnergyLimit(), and TheValue().
G4String G4hParametrisedLossModel::modelName private
Definition at line 119 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4hParametrisedLossModel.hh
Referenced by InitializeMe(), ModelName(), StoppingPower(), and TheValue().
G4double G4hParametrisedLossModel::theZieglerFactor private
Definition at line 116 of file G4hParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4hParametrisedLossModel.hh
Referenced by InitializeMe(), and TheValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hParametrisedLossModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4hParametrisedLossModel.cc