ECCE @ EIC Software: G4FissionProbability Class Reference
G4FissionProbability Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionProbability.hh>
Public Member Functions
G4FissionProbability ()
~G4FissionProbability () override
G4double EmissionProbability (const G4Fragment &fragment, G4double MaximalKineticEnergy) override
void SetEvaporationLevelDensityParameter (G4VLevelDensityParameter *aLevelDensity)
void SetFissionLevelDensityParameter (G4VLevelDensityParameter *aLevelDensity)
G4FissionProbability (const G4FissionProbability &right)=delete
const G4FissionProbability & operator= (const G4FissionProbability &right)=delete
G4bool operator== (const G4FissionProbability &right) const =delete
G4bool operator!= (const G4FissionProbability &right) const =delete
Public Member Functions inherited from G4VEmissionProbability
G4VEmissionProbability (G4int Z, G4int A)
virtual ~G4VEmissionProbability ()
void Initialise ()
virtual G4double ComputeProbability (G4double anEnergy, G4double CB)
G4int GetZ (void) const
G4int GetA (void) const
void SetDecayKinematics (G4int Z, G4int A, G4double rmass, G4double fmass)
G4double GetRecoilExcitation () const
void SetEvapExcitation (G4double exc)
G4double GetProbability () const
void ResetProbability ()
G4double SampleEnergy ()
Private Attributes
G4VLevelDensityParameter * theEvapLDP
G4VLevelDensityParameter * theFissLDP
G4PairingCorrection * fPairCorr
bool ownEvapLDP
bool ownFissLDP
Additional Inherited Members
Protected Member Functions inherited from G4VEmissionProbability
void ResetIntegrator (size_t nbin, G4double de, G4double eps)
G4double IntegrateProbability (G4double elow, G4double ehigh, G4double CB)
Protected Attributes inherited from G4VEmissionProbability
G4int OPTxs
G4int pVerbose
G4int theZ
G4int theA
G4int resZ
G4int resA
G4double pMass
G4double pEvapMass
G4double pResMass
G4double pProbability
G4NuclearLevelData * pNuclearLevelData
G4Pow * pG4pow
Detailed Description
Definition at line 39 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 39 of file G4FissionProbability.hh
Constructor & Destructor Documentation
G4FissionProbability::G4FissionProbability () explicit
Definition at line 44 of file G4FissionProbability.cc.
View newest version in sPHENIX GitHub at line 44 of file G4FissionProbability.cc
References fPairCorr, G4NuclearLevelData::GetInstance(), and G4NuclearLevelData::GetPairingCorrection().
G4FissionProbability::~G4FissionProbability () override
Definition at line 54 of file G4FissionProbability.cc.
View newest version in sPHENIX GitHub at line 54 of file G4FissionProbability.cc
References ownEvapLDP, ownFissLDP, theEvapLDP, and theFissLDP.
G4FissionProbability::G4FissionProbability (const G4FissionProbability & right) delete
Member Function Documentation
G4double G4FissionProbability::EmissionProbability (const G4Fragment & fragment, G4double MaximalKineticEnergy) override virtual
Reimplemented from G4VEmissionProbability.
Definition at line 61 of file G4FissionProbability.cc.
View newest version in sPHENIX GitHub at line 61 of file G4FissionProbability.cc
References A(), fPairCorr, G4Exp(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4PairingCorrection::GetFissionPairingCorrection(), G4PairingCorrection::GetPairingCorrection(), G4Fragment::GetZ_asInt(), G4VLevelDensityParameter::LevelDensityParameter(), pi, theEvapLDP, theFissLDP, and Z.
G4bool G4FissionProbability::operator!= (const G4FissionProbability & right) const delete
const G4FissionProbability& G4FissionProbability::operator= (const G4FissionProbability & right) delete
G4bool G4FissionProbability::operator== (const G4FissionProbability & right) const delete
void G4FissionProbability::SetEvaporationLevelDensityParameter (G4VLevelDensityParameter * aLevelDensity) inline
Definition at line 51 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 51 of file G4FissionProbability.hh
References ownEvapLDP, and theEvapLDP.
void G4FissionProbability::SetFissionLevelDensityParameter (G4VLevelDensityParameter * aLevelDensity) inline
Definition at line 59 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 59 of file G4FissionProbability.hh
References ownFissLDP, and theFissLDP.
Referenced by G4INCLXXInterface::G4INCLXXInterface().
Member Data Documentation
G4PairingCorrection* G4FissionProbability::fPairCorr private
Definition at line 76 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FissionProbability.hh
Referenced by EmissionProbability(), and G4FissionProbability().
bool G4FissionProbability::ownEvapLDP private
Definition at line 77 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FissionProbability.hh
Referenced by SetEvaporationLevelDensityParameter(), and ~G4FissionProbability().
bool G4FissionProbability::ownFissLDP private
Definition at line 78 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FissionProbability.hh
Referenced by SetFissionLevelDensityParameter(), and ~G4FissionProbability().
G4VLevelDensityParameter* G4FissionProbability::theEvapLDP private
Definition at line 74 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FissionProbability.hh
Referenced by EmissionProbability(), SetEvaporationLevelDensityParameter(), and ~G4FissionProbability().
G4VLevelDensityParameter* G4FissionProbability::theFissLDP private
Definition at line 75 of file G4FissionProbability.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FissionProbability.hh
Referenced by EmissionProbability(), SetFissionLevelDensityParameter(), and ~G4FissionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionProbability.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/src/G4FissionProbability.cc