ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/clparse.cc File Reference
clparse.cc File Reference
#include "globals.hh"
#include <fstream>
#include "G4Tokenizer.hh"
#include "G3toG4.hh"
#include "G3EleTable.hh"
#include "G3VolTable.hh"
#include "G3MatTable.hh"
#include "G3MedTable.hh"
#include "G3RotTable.hh"
#include "G3PartTable.hh"
#include "G3DetTable.hh"
#include "G3SensVolVector.hh"
#include <stdlib.h>
Functions
char gSeparator ('_')
G4int G3CLTokens (G4String *line, G4String *tokens)
void G3CLEval (G4String *tokens, char *select)
void PG4gsvolu (G4String *tokens)
void PG4gspos (G4String *tokens)
void PG4gsposp (G4String *tokens)
void PG4gsatt (G4String *tokens)
void PG4gsrotm (G4String *tokens)
void PG4gsdvn (G4String *tokens)
void PG4gsdvt (G4String *tokens)
void PG4gsdvx (G4String *tokens)
void PG4gsdvn2 (G4String *tokens)
void PG4gsdvt2 (G4String *tokens)
void PG4gsmate (G4String *tokens)
void PG4gsmixt (G4String *tokens)
void PG4gstmed (G4String *tokens)
void PG4gstpar (G4String *tokens)
void PG4gspart (G4String *tokens)
void PG4gsdk (G4String *tokens)
void PG4gsdet (G4String *tokens)
void PG4gsdetv (G4String *tokens)
void PG4gsdeta (G4String *tokens)
void PG4gsdeth (G4String *tokens)
void PG4gsdetd (G4String *tokens)
void PG4gsdetu (G4String *tokens)
void PG4ggclos ()
void G3CLRead (G4String &fname, char *select=0)
G4int G3CLTokens (G4String *line, G4String tokens[])
void G3CLEval (G4String tokens[], char *select)
void G3fillParams (G4String *tokens, const char *ptypes)
Variables
std::ofstream ofile
G3VolTable G3Vol
G3MatTable G3Mat
G3MedTable G3Med
G3RotTable G3Rot
G3PartTable G3Part
G3DetTable G3Det
G3EleTable G3Ele
G3SensVolVector G3SensVol
G4int narray
G4int Ipar [1000]
G4double Rpar [1000]
G4String Spar [1000]
Function Documentation
void G3CLEval (G4String * tokens, char * select)
Referenced by G3CLRead().
void G3CLEval (G4String tokens[], char * select)
Definition at line 170 of file clparse.cc.
View newest version in sPHENIX GitHub at line 170 of file clparse.cc
References G4endl, ofile, PG4ggclos(), PG4gsatt(), PG4gsdet(), PG4gsdeta(), PG4gsdetd(), PG4gsdeth(), PG4gsdetu(), PG4gsdetv(), PG4gsdk(), PG4gsdvn(), PG4gsdvn2(), PG4gsdvt(), PG4gsdvt2(), PG4gsdvx(), PG4gsmate(), PG4gsmixt(), PG4gspart(), PG4gspos(), PG4gsposp(), PG4gsrotm(), PG4gstmed(), PG4gstpar(), and PG4gsvolu().
void G3CLRead (G4String & fname, char * select = 0)
Definition at line 98 of file clparse.cc.
View newest version in sPHENIX GitHub at line 98 of file clparse.cc
References G3CLEval(), G3CLTokens(), G4endl, ofile, and G4String::readLine().
Referenced by G4BuildGeom().
G4int G3CLTokens (G4String * line, G4String * tokens)
Referenced by G3CLRead().
G4int G3CLTokens (G4String * line, G4String tokens[])
Definition at line 134 of file clparse.cc.
View newest version in sPHENIX GitHub at line 134 of file clparse.cc
void G3fillParams (G4String * tokens, const char * ptypes)
Definition at line 218 of file clparse.cc.
View newest version in sPHENIX GitHub at line 218 of file clparse.cc
References kdfinder::abs(), G4endl, Ipar, k, narray, ofile, and Rpar.
Referenced by PG4gsatt(), PG4gsdet(), PG4gsdeta(), PG4gsdetd(), PG4gsdeth(), PG4gsdetu(), PG4gsdetv(), PG4gsdk(), PG4gsdvn(), PG4gsdvn2(), PG4gsdvt(), PG4gsdvt2(), PG4gsdvx(), PG4gsmate(), PG4gsmixt(), PG4gspart(), PG4gspos(), PG4gsposp(), PG4gsrotm(), PG4gstmed(), PG4gstpar(), and PG4gsvolu().
char gSeparator ('_')
void PG4ggclos ()
Definition at line 31 of file G4ggclos.cc.
View newest version in sPHENIX GitHub at line 31 of file G4ggclos.cc
References G4ggclos().
Referenced by G3CLEval().
void PG4gsatt (G4String * tokens)
Definition at line 32 of file G4gsatt.cc.
View newest version in sPHENIX GitHub at line 32 of file G4gsatt.cc
References G3fillParams(), G4gsatt(), Ipar, PTgsatt, and Spar.
Referenced by G3CLEval().
void PG4gsdet (G4String * tokens)
Definition at line 31 of file G4gsdet.cc.
View newest version in sPHENIX GitHub at line 31 of file G4gsdet.cc
References G3fillParams(), G4gsdet(), Ipar, PTgsdet, and Spar.
Referenced by G3CLEval().
void PG4gsdeta (G4String * tokens)
Definition at line 37 of file G4gsdeta.cc.
View newest version in sPHENIX GitHub at line 37 of file G4gsdeta.cc
References G3fillParams(), G4gsdeta(), Ipar, PTgsdeta, and Spar.
Referenced by G3CLEval().
void PG4gsdetd (G4String * tokens)
Definition at line 33 of file G4gsdetd.cc.
View newest version in sPHENIX GitHub at line 33 of file G4gsdetd.cc
References G3fillParams(), G4gsdetd(), Ipar, PTgsdetd, and Spar.
Referenced by G3CLEval().
void PG4gsdeth (G4String * tokens)
Definition at line 33 of file G4gsdeth.cc.
View newest version in sPHENIX GitHub at line 33 of file G4gsdeth.cc
References G3fillParams(), G4gsdeth(), Ipar, PTgsdeth, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsdetu (G4String * tokens)
Definition at line 30 of file G4gsdetu.cc.
View newest version in sPHENIX GitHub at line 30 of file G4gsdetu.cc
References G4String::data(), G3fillParams(), G4gsdetu(), Ipar, PTgsdetu, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsdetv (G4String * tokens)
Definition at line 35 of file G4gsdetv.cc.
View newest version in sPHENIX GitHub at line 35 of file G4gsdetv.cc
References G3fillParams(), G4gsdetv(), Ipar, PTgsdetv, and Spar.
Referenced by G3CLEval().
void PG4gsdk (G4String * tokens)
Definition at line 32 of file G4gsdk.cc.
View newest version in sPHENIX GitHub at line 32 of file G4gsdk.cc
References G3fillParams(), G4gsdk(), Ipar, ipart, PTgsdk, and Rpar.
Referenced by G3CLEval().
void PG4gsdvn (G4String * tokens)
Definition at line 37 of file G4gsdvn.cc.
View newest version in sPHENIX GitHub at line 37 of file G4gsdvn.cc
References G3fillParams(), G4gsdvn(), Ipar, PTgsdvn, and Spar.
Referenced by G3CLEval().
void PG4gsdvn2 (G4String * tokens)
Definition at line 40 of file G4gsdvn2.cc.
View newest version in sPHENIX GitHub at line 40 of file G4gsdvn2.cc
References G3fillParams(), G4gsdvn2(), Ipar, PTgsdvn2, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsdvt (G4String * tokens)
Definition at line 40 of file G4gsdvt.cc.
View newest version in sPHENIX GitHub at line 40 of file G4gsdvt.cc
References G3fillParams(), G4gsdvt(), Ipar, PTgsdvt, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsdvt2 (G4String * tokens)
Definition at line 40 of file G4gsdvt2.cc.
View newest version in sPHENIX GitHub at line 40 of file G4gsdvt2.cc
References G3fillParams(), G4gsdvt2(), Ipar, PTgsdvt2, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsdvx (G4String * tokens)
Definition at line 39 of file G4gsdvx.cc.
View newest version in sPHENIX GitHub at line 39 of file G4gsdvx.cc
References G3fillParams(), G4gsdvx(), Ipar, PTgsdvx, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsmate (G4String * tokens)
Definition at line 41 of file G4gsmate.cc.
View newest version in sPHENIX GitHub at line 41 of file G4gsmate.cc
References a, G3fillParams(), G4gsmate(), Ipar, PTgsmate, Rpar, Spar, and z.
Referenced by G3CLEval().
void PG4gsmixt (G4String * tokens)
Definition at line 42 of file G4gsmixt.cc.
View newest version in sPHENIX GitHub at line 42 of file G4gsmixt.cc
References a, kdfinder::abs(), G4String::data(), G3fillParams(), G4gsmixt(), Ipar, PTgsmixt, Rpar, Spar, and z.
Referenced by G3CLEval().
void PG4gspart (G4String * tokens)
Definition at line 32 of file G4gspart.cc.
View newest version in sPHENIX GitHub at line 32 of file G4gspart.cc
References charge, G3fillParams(), G4gspart(), Ipar, ipart, PTgspart, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gspos (G4String * tokens)
Definition at line 41 of file G4gspos.cc.
View newest version in sPHENIX GitHub at line 41 of file G4gspos.cc
References G3fillParams(), G4gspos(), Ipar, num, PTgspos, Rpar, Spar, x, y, and z.
Referenced by G3CLEval().
void PG4gsposp (G4String * tokens)
Definition at line 41 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 41 of file G4gsposp.cc
References G3fillParams(), G4gsposp(), Ipar, num, PTgsposp, Rpar, Spar, x, y, and z.
Referenced by G3CLEval().
void PG4gsrotm (G4String * tokens)
Definition at line 34 of file G4gsrotm.cc.
View newest version in sPHENIX GitHub at line 34 of file G4gsrotm.cc
References G3fillParams(), G4gsrotm(), Ipar, PTgsrotm, and Rpar.
Referenced by G3CLEval().
void PG4gstmed (G4String * tokens)
Definition at line 43 of file G4gstmed.cc.
View newest version in sPHENIX GitHub at line 43 of file G4gstmed.cc
References G3fillParams(), G4gstmed(), Ipar, PTgstmed, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gstpar (G4String * tokens)
Definition at line 31 of file G4gstpar.cc.
View newest version in sPHENIX GitHub at line 31 of file G4gstpar.cc
References G3fillParams(), G4gstpar(), Ipar, PTgstpar, Rpar, and Spar.
Referenced by G3CLEval().
void PG4gsvolu (G4String * tokens)
Definition at line 36 of file G4gsvolu.cc.
View newest version in sPHENIX GitHub at line 36 of file G4gsvolu.cc
References G3fillParams(), G4gsvolu(), Ipar, PTgsvolu, Rpar, and Spar.
Referenced by G3CLEval().
Variable Documentation
G3DetTable G3Det
Definition at line 58 of file clparse.cc.
View newest version in sPHENIX GitHub at line 58 of file clparse.cc
Referenced by G4BuildGeom(), and G4gsdeta().
G3EleTable G3Ele
Definition at line 59 of file clparse.cc.
View newest version in sPHENIX GitHub at line 59 of file clparse.cc
Referenced by G4gsmate(), and G4gsmixt().
G3MatTable G3Mat
Definition at line 54 of file clparse.cc.
View newest version in sPHENIX GitHub at line 54 of file clparse.cc
Referenced by G4gsmate(), G4gsmixt(), and G4gstmed().
G3MedTable G3Med
Definition at line 55 of file clparse.cc.
View newest version in sPHENIX GitHub at line 55 of file clparse.cc
Referenced by G3toG4BuildLVTree(), and G4gstmed().
G3PartTable G3Part
Definition at line 57 of file clparse.cc.
View newest version in sPHENIX GitHub at line 57 of file clparse.cc
Referenced by G4BuildGeom().
G3RotTable G3Rot
Definition at line 56 of file clparse.cc.
View newest version in sPHENIX GitHub at line 56 of file clparse.cc
Referenced by G3toG4BuildPVTree(), G4gsrotm(), and GetTransform3D().
G3SensVolVector G3SensVol
Definition at line 60 of file clparse.cc.
View newest version in sPHENIX GitHub at line 60 of file clparse.cc
Referenced by G3toG4BuildLVTree().
G3VolTable G3Vol
Definition at line 53 of file clparse.cc.
View newest version in sPHENIX GitHub at line 53 of file clparse.cc
Referenced by G3VolTableEntry::AddG3Pos(), G4BuildGeom(), G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4CreateVTE(), G4ggclos(), G4gsbool(), G4gsdvn(), G4gsdvn2(), G4gsdvt(), G4gsdvt2(), G4gspos(), G4gsposp(), G4gsvolu(), and G3VolTableEntry::GetMasterClone().
G4int Ipar[1000]
Definition at line 65 of file clparse.cc.
View newest version in sPHENIX GitHub at line 65 of file clparse.cc
Referenced by G3fillParams(), PG4gsatt(), PG4gsdet(), PG4gsdeta(), PG4gsdetd(), PG4gsdeth(), PG4gsdetu(), PG4gsdetv(), PG4gsdk(), PG4gsdvn(), PG4gsdvn2(), PG4gsdvt(), PG4gsdvt2(), PG4gsdvx(), PG4gsmate(), PG4gsmixt(), PG4gspart(), PG4gspos(), PG4gsposp(), PG4gsrotm(), PG4gstmed(), PG4gstpar(), and PG4gsvolu().
G4int narray
Definition at line 63 of file clparse.cc.
View newest version in sPHENIX GitHub at line 63 of file clparse.cc
Referenced by G3fillParams().
std::ofstream ofile
Definition at line 44 of file clparse.cc.
View newest version in sPHENIX GitHub at line 44 of file clparse.cc
Referenced by G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), PHTpcEventExporter::exportEvent(), G3CLEval(), G3CLRead(), G3fillParams(), if(), main(), runLCELoop(), G4GMocrenIO::storeData2(), G4GMocrenIO::storeData3(), and G4GMocrenIO::storeData4().
G4double Rpar[1000]
Definition at line 66 of file clparse.cc.
View newest version in sPHENIX GitHub at line 66 of file clparse.cc
Referenced by G3Division::CreateEnvelope(), G3Division::CreateSolid(), G3Division::Dvn(), G3Division::Dvn2(), G3Division::Dvt(), G3Division::Dvt2(), G3fillParams(), PG4gsdeth(), PG4gsdetu(), PG4gsdk(), PG4gsdvn2(), PG4gsdvt(), PG4gsdvt2(), PG4gsdvx(), PG4gsmate(), PG4gsmixt(), PG4gspart(), PG4gspos(), PG4gsposp(), PG4gsrotm(), PG4gstmed(), PG4gstpar(), PG4gsvolu(), and G3Division::SetRangeAndAxis().
G4String Spar[1000]
Definition at line 67 of file clparse.cc.
View newest version in sPHENIX GitHub at line 67 of file clparse.cc
Referenced by PG4gsatt(), PG4gsdet(), PG4gsdeta(), PG4gsdetd(), PG4gsdeth(), PG4gsdetu(), PG4gsdetv(), PG4gsdvn(), PG4gsdvn2(), PG4gsdvt(), PG4gsdvt2(), PG4gsdvx(), PG4gsmate(), PG4gsmixt(), PG4gspart(), PG4gspos(), PG4gsposp(), PG4gstmed(), PG4gstpar(), and PG4gsvolu().