ECCE @ EIC Software: RE01EventAction Class Reference
RE01EventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01EventAction.hh>
Public Member Functions
RE01EventAction ()
virtual ~RE01EventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
void PrintPrimary (G4PrimaryParticle *pp, G4int ind)
Private Attributes
G4int fTrackerCollID
G4int fCalorimeterCollID
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 39 of file RE01EventAction.hh.
View newest version in sPHENIX GitHub at line 39 of file RE01EventAction.hh
Constructor & Destructor Documentation
RE01EventAction::RE01EventAction ()
Definition at line 50 of file RE01EventAction.cc.
View newest version in sPHENIX GitHub at line 50 of file RE01EventAction.cc
RE01EventAction::~RE01EventAction () virtual
Definition at line 56 of file RE01EventAction.cc.
View newest version in sPHENIX GitHub at line 56 of file RE01EventAction.cc
Member Function Documentation
void RE01EventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Definition at line 60 of file RE01EventAction.cc.
View newest version in sPHENIX GitHub at line 60 of file RE01EventAction.cc
References fCalorimeterCollID, fTrackerCollID, G4SDManager::GetCollectionID(), and G4SDManager::GetSDMpointer().
void RE01EventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 72 of file RE01EventAction.cc.
View newest version in sPHENIX GitHub at line 72 of file RE01EventAction.cc
References G4TrajectoryContainer::entries(), G4THitsCollection< T >::entries(), fCalorimeterCollID, G4UserEventAction::fpEventManager, fTrackerCollID, G4cout, G4endl, G4Event::GetEventID(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4PrimaryParticle::GetNext(), G4Event::GetNumberOfPrimaryVertex(), G4PrimaryVertex::GetPrimary(), G4Event::GetPrimaryVertex(), G4PrimaryVertex::GetT0(), G4Event::GetTrajectoryContainer(), G4EventManager::GetVerboseLevel(), G4PrimaryVertex::GetX0(), G4PrimaryVertex::GetY0(), G4PrimaryVertex::GetZ0(), GeV, ns, G4InuclParticleNames::pp, PrintPrimary(), and RE01Trajectory::ShowTrajectory().
void RE01EventAction::PrintPrimary (G4PrimaryParticle * pp, G4int ind) private
Definition at line 168 of file RE01EventAction.cc.
View newest version in sPHENIX GitHub at line 168 of file RE01EventAction.cc
References G4cout, G4endl, G4PrimaryParticle::GetDaughter(), G4PrimaryParticle::GetG4code(), G4PrimaryParticle::GetMomentum(), G4PrimaryParticle::GetNext(), G4ParticleDefinition::GetParticleName(), G4PrimaryParticle::GetPDGcode(), G4PrimaryParticle::GetTrackID(), and GeV.
Referenced by EndOfEventAction().
Member Data Documentation
G4int RE01EventAction::fCalorimeterCollID private
Definition at line 51 of file RE01EventAction.hh.
View newest version in sPHENIX GitHub at line 51 of file RE01EventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
G4int RE01EventAction::fTrackerCollID private
Definition at line 50 of file RE01EventAction.hh.
View newest version in sPHENIX GitHub at line 50 of file RE01EventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01EventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01EventAction.cc