ECCE @ EIC Software: CCalHcal Class Reference
CCalHcal Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHcal.hh>
Public Member Functions
CCalHcal (const G4String &name)
virtual ~CCalHcal ()
G4String getGenMat () const
G4double getDy_2Cal () const
G4double getDx_2Cal () const
G4double getXposCal () const
G4String getBoxMat () const
G4int getNBox () const
G4double getDy_2Box () const
G4double getDx_2Box () const
G4double getWallThickBox () const
G4double getXposBox (unsigned int i) const
G4int getNLayerScnt () const
G4int getTypeScnt (unsigned int i) const
G4int getMotherScnt (unsigned int i) const
G4double getXposScnt (unsigned int i) const
G4int getNLayerAbs () const
G4int getTypeAbs (unsigned int i) const
G4int getMotherAbs (unsigned int i) const
G4double getXposAbs (unsigned int i) const
G4String getAbsMat () const
G4int getNAbsorber () const
G4double getDy_2Abs () const
G4double getDx_2Abs (unsigned int i) const
G4String getScntMat () const
G4String getWrapMat () const
G4String getPlasMat () const
G4int getNScintillator () const
G4double getDy_2ScntLay (unsigned int i) const
G4double getDx_2ScntLay (unsigned int i) const
G4double getDx_2Wrap (unsigned int i) const
G4double getDx_2FrontP (unsigned int i) const
G4double getDx_2BackP (unsigned int i) const
G4double getDx_2Scnt (unsigned int i) const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual G4int readFile ()
virtual void constructDaughters ()
Protected Member Functions inherited from CCalDetector
G4int buildFromFile ()
Private Attributes
G4String genMaterial
G4double dy_2Cal
G4double dx_2Cal
G4double xposCal
G4String boxMaterial
G4int nBox
G4double dy_2Box
G4double dx_2Box
G4double wallThickBox
G4double * xposBox
G4int nLayerScnt
G4int * typeLayerScnt
G4int * mothLayerScnt
G4double * xposLayerScnt
G4int nLayerAbs
G4int * typeLayerAbs
G4int * mothLayerAbs
G4double * xposLayerAbs
G4String absMaterial
G4int nAbsorber
G4double dy_2Absorber
G4double * dx_2Absorber
G4String scntMaterial
G4String wrapMaterial
G4String plasMaterial
G4int nScintillator
G4double * dy_2ScntLayer
G4double * dx_2ScntLayer
G4double * dx_2Wrapper
G4double * dx_2FrontPlastic
G4double * dx_2BackPlastic
G4double * dx_2Scintillator
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Detailed Description
Definition at line 35 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 35 of file CCalHcal.hh
Constructor & Destructor Documentation
CCalHcal::CCalHcal (const G4String & name)
Definition at line 37 of file CCalHcal.cc.
View newest version in sPHENIX GitHub at line 37 of file CCalHcal.cc
CCalHcal::~CCalHcal () virtual
Definition at line 43 of file CCalHcal.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalHcal.cc
References dx_2Absorber, dx_2BackPlastic, dx_2FrontPlastic, dx_2Scintillator, dx_2ScntLayer, dx_2Wrapper, dy_2ScntLayer, mothLayerAbs, mothLayerScnt, typeLayerAbs, typeLayerScnt, xposBox, xposLayerAbs, and xposLayerScnt.
Member Function Documentation
void CCalHcal::constructDaughters () protected virtual
Implements CCalDetector.
Reimplemented in CCalG4Hcal.
Definition at line 192 of file CCalHcal.cc.
View newest version in sPHENIX GitHub at line 192 of file CCalHcal.cc
G4String CCalHcal::getAbsMat () const inline
Definition at line 61 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalHcal.hh
References absMaterial.
Referenced by CCalG4Hcal::constructAbsorberLayer().
G4String CCalHcal::getBoxMat () const inline
Definition at line 47 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 47 of file CCalHcal.hh
References boxMaterial.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getDx_2Abs (unsigned int i) const inline
Definition at line 64 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 64 of file CCalHcal.hh
References dx_2Absorber.
Referenced by CCalG4Hcal::constructAbsorberLayer().
G4double CCalHcal::getDx_2BackP (unsigned int i) const inline
Definition at line 73 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 73 of file CCalHcal.hh
References dx_2BackPlastic.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4double CCalHcal::getDx_2Box () const inline
Definition at line 50 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 50 of file CCalHcal.hh
References dx_2Box.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getDx_2Cal () const inline
Definition at line 45 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 45 of file CCalHcal.hh
References dx_2Cal.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getDx_2FrontP (unsigned int i) const inline
Definition at line 72 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 72 of file CCalHcal.hh
References dx_2FrontPlastic.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4double CCalHcal::getDx_2Scnt (unsigned int i) const inline
Definition at line 74 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 74 of file CCalHcal.hh
References dx_2Scintillator.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4double CCalHcal::getDx_2ScntLay (unsigned int i) const inline
Definition at line 70 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 70 of file CCalHcal.hh
References dx_2ScntLayer.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4double CCalHcal::getDx_2Wrap (unsigned int i) const inline
Definition at line 71 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 71 of file CCalHcal.hh
References dx_2Wrapper.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4double CCalHcal::getDy_2Abs () const inline
Definition at line 63 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalHcal.hh
References dy_2Absorber.
Referenced by CCalG4Hcal::constructAbsorberLayer().
G4double CCalHcal::getDy_2Box () const inline
Definition at line 49 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 49 of file CCalHcal.hh
References dy_2Box.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getDy_2Cal () const inline
Definition at line 44 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 44 of file CCalHcal.hh
References dy_2Cal.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getDy_2ScntLay (unsigned int i) const inline
Definition at line 69 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 69 of file CCalHcal.hh
References dy_2ScntLayer.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4String CCalHcal::getGenMat () const inline
Definition at line 43 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 43 of file CCalHcal.hh
References genMaterial.
Referenced by CCalG4Hcal::constructIn(), and CCalG4Hcal::constructScintillatorLayer().
G4int CCalHcal::getMotherAbs (unsigned int i) const inline
Definition at line 59 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 59 of file CCalHcal.hh
References mothLayerAbs.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getMotherScnt (unsigned int i) const inline
Definition at line 55 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 55 of file CCalHcal.hh
References mothLayerScnt.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getNAbsorber () const inline
Definition at line 62 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalHcal.hh
References nAbsorber.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getNBox () const inline
Definition at line 48 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 48 of file CCalHcal.hh
References nBox.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getNLayerAbs () const inline
Definition at line 57 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 57 of file CCalHcal.hh
References nLayerAbs.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getNLayerScnt () const inline
Definition at line 53 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalHcal.hh
References nLayerScnt.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getNScintillator () const inline
Definition at line 68 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 68 of file CCalHcal.hh
References nScintillator.
Referenced by CCalG4Hcal::constructIn().
G4String CCalHcal::getPlasMat () const inline
Definition at line 67 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 67 of file CCalHcal.hh
References plasMaterial.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4String CCalHcal::getScntMat () const inline
Definition at line 65 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 65 of file CCalHcal.hh
References scntMaterial.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4int CCalHcal::getTypeAbs (unsigned int i) const inline
Definition at line 58 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 58 of file CCalHcal.hh
References typeLayerAbs.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::getTypeScnt (unsigned int i) const inline
Definition at line 54 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalHcal.hh
References typeLayerScnt.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getWallThickBox () const inline
Definition at line 51 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalHcal.hh
References wallThickBox.
Referenced by CCalG4Hcal::constructIn().
G4String CCalHcal::getWrapMat () const inline
Definition at line 66 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 66 of file CCalHcal.hh
References wrapMaterial.
Referenced by CCalG4Hcal::constructScintillatorLayer().
G4double CCalHcal::getXposAbs (unsigned int i) const inline
Definition at line 60 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 60 of file CCalHcal.hh
References xposLayerAbs.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getXposBox (unsigned int i) const inline
Definition at line 52 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalHcal.hh
References xposBox.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getXposCal () const inline
Definition at line 46 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 46 of file CCalHcal.hh
References xposCal.
Referenced by CCalG4Hcal::constructIn().
G4double CCalHcal::getXposScnt (unsigned int i) const inline
Definition at line 56 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 56 of file CCalHcal.hh
References xposLayerScnt.
Referenced by CCalG4Hcal::constructIn().
G4int CCalHcal::readFile () protected virtual
Implements CCalDetector.
Definition at line 74 of file CCalHcal.cc.
View newest version in sPHENIX GitHub at line 74 of file CCalHcal.cc
References absMaterial, boxMaterial, dx_2Absorber, dx_2BackPlastic, dx_2Box, dx_2Cal, dx_2FrontPlastic, dx_2Scintillator, dx_2ScntLayer, dx_2Wrapper, dy_2Absorber, dy_2Box, dy_2Cal, dy_2ScntLayer, CCalDetector::File(), findDO(), G4cout, G4endl, genMaterial, jump(), mothLayerAbs, mothLayerScnt, nAbsorber, nBox, nLayerAbs, nLayerScnt, nScintillator, openGeomFile(), CCalDetector::pathName, plasMaterial, readName(), scntMaterial, tab(), typeLayerAbs, typeLayerScnt, wallThickBox, wrapMaterial, xposBox, xposCal, xposLayerAbs, and xposLayerScnt.
Member Data Documentation
G4String CCalHcal::absMaterial private
Definition at line 103 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 103 of file CCalHcal.hh
Referenced by getAbsMat(), and readFile().
G4String CCalHcal::boxMaterial private
Definition at line 86 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 86 of file CCalHcal.hh
Referenced by getBoxMat(), and readFile().
G4double* CCalHcal::dx_2Absorber private
Definition at line 106 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 106 of file CCalHcal.hh
Referenced by getDx_2Abs(), readFile(), and ~CCalHcal().
G4double* CCalHcal::dx_2BackPlastic private
Definition at line 116 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 116 of file CCalHcal.hh
Referenced by getDx_2BackP(), readFile(), and ~CCalHcal().
G4double CCalHcal::dx_2Box private
Definition at line 89 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 89 of file CCalHcal.hh
Referenced by getDx_2Box(), and readFile().
G4double CCalHcal::dx_2Cal private
Definition at line 83 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 83 of file CCalHcal.hh
Referenced by getDx_2Cal(), and readFile().
G4double* CCalHcal::dx_2FrontPlastic private
Definition at line 115 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 115 of file CCalHcal.hh
Referenced by getDx_2FrontP(), readFile(), and ~CCalHcal().
G4double* CCalHcal::dx_2Scintillator private
Definition at line 117 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 117 of file CCalHcal.hh
Referenced by getDx_2Scnt(), readFile(), and ~CCalHcal().
G4double* CCalHcal::dx_2ScntLayer private
Definition at line 113 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 113 of file CCalHcal.hh
Referenced by getDx_2ScntLay(), readFile(), and ~CCalHcal().
G4double* CCalHcal::dx_2Wrapper private
Definition at line 114 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 114 of file CCalHcal.hh
Referenced by getDx_2Wrap(), readFile(), and ~CCalHcal().
G4double CCalHcal::dy_2Absorber private
Definition at line 105 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 105 of file CCalHcal.hh
Referenced by getDy_2Abs(), and readFile().
G4double CCalHcal::dy_2Box private
Definition at line 88 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 88 of file CCalHcal.hh
Referenced by getDy_2Box(), and readFile().
G4double CCalHcal::dy_2Cal private
Definition at line 82 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 82 of file CCalHcal.hh
Referenced by getDy_2Cal(), and readFile().
G4double* CCalHcal::dy_2ScntLayer private
Definition at line 112 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 112 of file CCalHcal.hh
Referenced by getDy_2ScntLay(), readFile(), and ~CCalHcal().
G4String CCalHcal::genMaterial private
Definition at line 81 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 81 of file CCalHcal.hh
Referenced by getGenMat(), and readFile().
G4int* CCalHcal::mothLayerAbs private
Definition at line 100 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 100 of file CCalHcal.hh
Referenced by getMotherAbs(), readFile(), and ~CCalHcal().
G4int* CCalHcal::mothLayerScnt private
Definition at line 95 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalHcal.hh
Referenced by getMotherScnt(), readFile(), and ~CCalHcal().
G4int CCalHcal::nAbsorber private
Definition at line 104 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 104 of file CCalHcal.hh
Referenced by getNAbsorber(), and readFile().
G4int CCalHcal::nBox private
Definition at line 87 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 87 of file CCalHcal.hh
Referenced by getNBox(), and readFile().
G4int CCalHcal::nLayerAbs private
Definition at line 98 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 98 of file CCalHcal.hh
Referenced by getNLayerAbs(), and readFile().
G4int CCalHcal::nLayerScnt private
Definition at line 93 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 93 of file CCalHcal.hh
Referenced by getNLayerScnt(), and readFile().
G4int CCalHcal::nScintillator private
Definition at line 111 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 111 of file CCalHcal.hh
Referenced by getNScintillator(), and readFile().
G4String CCalHcal::plasMaterial private
Definition at line 110 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 110 of file CCalHcal.hh
Referenced by getPlasMat(), and readFile().
G4String CCalHcal::scntMaterial private
Definition at line 108 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 108 of file CCalHcal.hh
Referenced by getScntMat(), and readFile().
G4int* CCalHcal::typeLayerAbs private
Definition at line 99 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 99 of file CCalHcal.hh
Referenced by getTypeAbs(), readFile(), and ~CCalHcal().
G4int* CCalHcal::typeLayerScnt private
Definition at line 94 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 94 of file CCalHcal.hh
Referenced by getTypeScnt(), readFile(), and ~CCalHcal().
G4double CCalHcal::wallThickBox private
Definition at line 90 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 90 of file CCalHcal.hh
Referenced by getWallThickBox(), and readFile().
G4String CCalHcal::wrapMaterial private
Definition at line 109 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 109 of file CCalHcal.hh
Referenced by getWrapMat(), and readFile().
G4double* CCalHcal::xposBox private
Definition at line 91 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 91 of file CCalHcal.hh
Referenced by getXposBox(), readFile(), and ~CCalHcal().
G4double CCalHcal::xposCal private
Definition at line 84 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 84 of file CCalHcal.hh
Referenced by getXposCal(), and readFile().
G4double* CCalHcal::xposLayerAbs private
Definition at line 101 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 101 of file CCalHcal.hh
Referenced by getXposAbs(), readFile(), and ~CCalHcal().
G4double* CCalHcal::xposLayerScnt private
Definition at line 96 of file CCalHcal.hh.
View newest version in sPHENIX GitHub at line 96 of file CCalHcal.hh
Referenced by getXposScnt(), readFile(), and ~CCalHcal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHcal.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalHcal.cc