ECCE @ EIC Software: G4WeightWindowStore Class Reference
G4WeightWindowStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4WeightWindowStore.hh>
Public Member Functions
virtual G4double GetLowerWeight (const G4GeometryCell &gCell, G4double partEnergy) const
virtual G4bool IsKnown (const G4GeometryCell &gCell) const
void Clear ()
void SetWorldVolume ()
void SetParallelWorldVolume (const G4String &paraName)
virtual const G4VPhysicalVolume & GetWorldVolume () const
virtual const G4VPhysicalVolume * GetParallelWorldVolumePointer () const
void AddLowerWeights (const G4GeometryCell &gCell, const std::vector< G4double > &lowerWeights)
void AddUpperEboundLowerWeightPairs (const G4GeometryCell &gCell, const G4UpperEnergyToLowerWeightMap &enWeMap)
void SetGeneralUpperEnergyBounds (const std::set< G4double, std::less< G4double > > &enBounds)
Public Member Functions inherited from G4VWeightWindowStore
G4VWeightWindowStore ()
virtual ~G4VWeightWindowStore ()
Static Public Member Functions
static G4WeightWindowStore * GetInstance ()
static G4WeightWindowStore * GetInstance (const G4String &ParallelWorldName)
Protected Member Functions
G4WeightWindowStore ()
G4WeightWindowStore (const G4String &ParallelWorldName)
~G4WeightWindowStore ()
Private Member Functions
G4bool IsInWorld (const G4VPhysicalVolume &) const
void Error (const G4String &m) const
void SetInternalIterator (const G4GeometryCell &gCell) const
Private Attributes
const G4VPhysicalVolume * fWorldVolume = nullptr
std::set< G4double, std::less
< G4double > > fGeneralUpperEnergyBounds
G4GeometryCellWeight fCellToUpEnBoundLoWePairsMap
G4GeometryCellWeight::const_iterator fCurrentIterator
Static Private Attributes
static G4ThreadLocal
G4WeightWindowStore * fInstance = nullptr
Detailed Description
Definition at line 45 of file G4WeightWindowStore.hh.
View newest version in sPHENIX GitHub at line 45 of file G4WeightWindowStore.hh
Constructor & Destructor Documentation
G4WeightWindowStore::G4WeightWindowStore () explicit protected
Definition at line 44 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 44 of file G4WeightWindowStore.cc
Referenced by GetInstance().
G4WeightWindowStore::G4WeightWindowStore (const G4String & ParallelWorldName) explicit protected
Definition at line 54 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 54 of file G4WeightWindowStore.cc
G4WeightWindowStore::~G4WeightWindowStore () protected
Definition at line 64 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 64 of file G4WeightWindowStore.cc
Member Function Documentation
void G4WeightWindowStore::AddLowerWeights (const G4GeometryCell & gCell, const std::vector< G4double > & lowerWeights)
Definition at line 164 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 164 of file G4WeightWindowStore.cc
References Error(), fCellToUpEnBoundLoWePairsMap, fGeneralUpperEnergyBounds, IsKnown(), and it.
Referenced by B01DetectorConstruction::CreateWeightWindowStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
void G4WeightWindowStore::AddUpperEboundLowerWeightPairs (const G4GeometryCell & gCell, const G4UpperEnergyToLowerWeightMap & enWeMap)
Definition at line 196 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 196 of file G4WeightWindowStore.cc
References Error(), fCellToUpEnBoundLoWePairsMap, and IsKnown().
void G4WeightWindowStore::Clear ()
Definition at line 131 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 131 of file G4WeightWindowStore.cc
References fCellToUpEnBoundLoWePairsMap.
void G4WeightWindowStore::Error (const G4String & m) const private
Definition at line 222 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 222 of file G4WeightWindowStore.cc
References FatalException, and G4Exception().
Referenced by AddLowerWeights(), AddUpperEboundLowerWeightPairs(), GetLowerWeight(), and SetGeneralUpperEnergyBounds().
G4WeightWindowStore * G4WeightWindowStore::GetInstance (void) static
Definition at line 233 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 233 of file G4WeightWindowStore.cc
References fInstance, and G4WeightWindowStore().
Referenced by G4WeightWindowBiasing::ConstructProcess(), B01DetectorConstruction::CreateWeightWindowStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
G4WeightWindowStore * G4WeightWindowStore::GetInstance (const G4String & ParallelWorldName) static
Definition at line 248 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 248 of file G4WeightWindowStore.cc
References fInstance, G4cout, G4endl, and G4WeightWindowStore().
G4double G4WeightWindowStore::GetLowerWeight (const G4GeometryCell & gCell, G4double partEnergy) const virtual
Implements G4VWeightWindowStore.
Definition at line 69 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 69 of file G4WeightWindowStore.cc
References Error(), fCellToUpEnBoundLoWePairsMap, fCurrentIterator, G4endl, it, and SetInternalIterator().
const G4VPhysicalVolume * G4WeightWindowStore::GetParallelWorldVolumePointer () const virtual
Definition at line 158 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 158 of file G4WeightWindowStore.cc
References fWorldVolume.
const G4VPhysicalVolume & G4WeightWindowStore::GetWorldVolume () const virtual
Implements G4VWeightWindowStore.
Definition at line 152 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 152 of file G4WeightWindowStore.cc
References fWorldVolume.
G4bool G4WeightWindowStore::IsInWorld (const G4VPhysicalVolume & aVolume) const private
Definition at line 108 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 108 of file G4WeightWindowStore.cc
References fWorldVolume, G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::IsAncestor().
Referenced by IsKnown().
G4bool G4WeightWindowStore::IsKnown (const G4GeometryCell & gCell) const virtual
Implements G4VWeightWindowStore.
Definition at line 119 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 119 of file G4WeightWindowStore.cc
References fCellToUpEnBoundLoWePairsMap, fCurrentIterator, G4GeometryCell::GetPhysicalVolume(), IsInWorld(), and SetInternalIterator().
Referenced by AddLowerWeights(), and AddUpperEboundLowerWeightPairs().
void G4WeightWindowStore::SetGeneralUpperEnergyBounds (const std::set< G4double, std::less< G4double > > & enBounds)
Definition at line 212 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 212 of file G4WeightWindowStore.cc
References Error(), and fGeneralUpperEnergyBounds.
Referenced by B01DetectorConstruction::CreateWeightWindowStore(), and B02ImportanceDetectorConstruction::CreateWeightWindowStore().
void G4WeightWindowStore::SetInternalIterator (const G4GeometryCell & gCell) const private
Definition at line 102 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 102 of file G4WeightWindowStore.cc
References fCellToUpEnBoundLoWePairsMap, and fCurrentIterator.
Referenced by GetLowerWeight(), and IsKnown().
void G4WeightWindowStore::SetParallelWorldVolume (const G4String & paraName)
Definition at line 145 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 145 of file G4WeightWindowStore.cc
References fWorldVolume, G4TransportationManager::GetParallelWorld(), and G4TransportationManager::GetTransportationManager().
void G4WeightWindowStore::SetWorldVolume ()
Definition at line 136 of file G4WeightWindowStore.cc.
View newest version in sPHENIX GitHub at line 136 of file G4WeightWindowStore.cc
References fWorldVolume, G4cout, G4endl, G4VPhysicalVolume::GetName(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetTransportationManager(), and G4Navigator::GetWorldVolume().
Member Data Documentation
G4GeometryCellWeight G4WeightWindowStore::fCellToUpEnBoundLoWePairsMap private
Definition at line 106 of file G4WeightWindowStore.hh.
View newest version in sPHENIX GitHub at line 106 of file G4WeightWindowStore.hh
Referenced by AddLowerWeights(), AddUpperEboundLowerWeightPairs(), Clear(), GetLowerWeight(), IsKnown(), and SetInternalIterator().
G4GeometryCellWeight::const_iterator G4WeightWindowStore::fCurrentIterator mutable private
Definition at line 107 of file G4WeightWindowStore.hh.
View newest version in sPHENIX GitHub at line 107 of file G4WeightWindowStore.hh
Referenced by GetLowerWeight(), IsKnown(), and SetInternalIterator().
std::set<G4double, std::less<G4double> > G4WeightWindowStore::fGeneralUpperEnergyBounds private
Definition at line 105 of file G4WeightWindowStore.hh.
View newest version in sPHENIX GitHub at line 105 of file G4WeightWindowStore.hh
Referenced by AddLowerWeights(), and SetGeneralUpperEnergyBounds().
G4ThreadLocal G4WeightWindowStore * G4WeightWindowStore::fInstance = nullptr static private
Definition at line 109 of file G4WeightWindowStore.hh.
View newest version in sPHENIX GitHub at line 109 of file G4WeightWindowStore.hh
Referenced by GetInstance().
const G4VPhysicalVolume* G4WeightWindowStore::fWorldVolume = nullptr private
Definition at line 103 of file G4WeightWindowStore.hh.
View newest version in sPHENIX GitHub at line 103 of file G4WeightWindowStore.hh
Referenced by GetParallelWorldVolumePointer(), GetWorldVolume(), IsInWorld(), SetParallelWorldVolume(), and SetWorldVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4WeightWindowStore.hh
geant4/tree/geant4-10.6-release/source/geometry/biasing/src/G4WeightWindowStore.cc