ECCE @ EIC Software: G4ModelColourMap< T > Class Template Reference
G4ModelColourMap< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelColourMap.hh>
Public Member Functions
G4ModelColourMap ()
virtual ~G4ModelColourMap ()
void Set (const T &, const G4Colour &)
void Set (const T &, const G4String &)
G4Colour & operator[] (const T &quantity)
const std::map< T, G4Colour > & GetBasicMap () const
bool GetColour (const T &, G4Colour &) const
void Print (std::ostream &ostr) const
Private Attributes
std::map< T, G4Colour > fMap
Detailed Description
template<typename T>
class G4ModelColourMap< T >
Definition at line 40 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ModelColourMap.hh
Constructor & Destructor Documentation
template<typename T > G4ModelColourMap< T >::G4ModelColourMap ()
Definition at line 70 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ModelColourMap.hh
template<typename T > G4ModelColourMap< T >::~G4ModelColourMap () virtual
Definition at line 73 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ModelColourMap.hh
Member Function Documentation
template<typename T > const std::map< T, G4Colour > & G4ModelColourMap< T >::GetBasicMap () const
Definition at line 104 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ModelColourMap.hh
Referenced by G4TrajectoryDrawByEncounteredVolume::Draw().
template<typename T> bool G4ModelColourMap< T >::GetColour (const T & quantity, G4Colour & colour) const
Definition at line 109 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ModelColourMap.hh
Referenced by G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), and G4TrajectoryDrawByCharge::Draw().
template<typename T> G4Colour & G4ModelColourMap< T >::operator[] (const T & quantity)
Definition at line 67 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ModelColourMap.hh
template<typename T > void G4ModelColourMap< T >::Print (std::ostream & ostr) const
Definition at line 123 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ModelColourMap.hh
References G4endl.
Referenced by G4TrajectoryDrawByOriginVolume::Print(), G4TrajectoryDrawByParticleID::Print(), G4TrajectoryDrawByEncounteredVolume::Print(), and G4TrajectoryDrawByCharge::Print().
template<typename T> void G4ModelColourMap< T >::Set (const T & quantity, const G4Colour & colour)
Definition at line 98 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ModelColourMap.hh
Referenced by G4TrajectoryDrawByOriginVolume::Set(), G4TrajectoryDrawByParticleID::Set(), G4TrajectoryDrawByEncounteredVolume::Set(), and G4TrajectoryDrawByCharge::Set().
template<typename T> void G4ModelColourMap< T >::Set (const T & quantity, const G4String & colour)
Definition at line 77 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ModelColourMap.hh
References G4Exception(), G4Colour::GetColour(), JustWarning, and G4ArrayOps::Set().
Member Data Documentation
template<typename T> std::map<T, G4Colour> G4ModelColourMap< T >::fMap private
Definition at line 61 of file G4ModelColourMap.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ModelColourMap.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelColourMap.hh