ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/Plot.C File Reference
Plot.C File Reference
#include "TF1.h"
#include "TH2.h"
#include "TH2D.h"
#include "TH1.h"
#include "TMath.h"
#include <string.h>
#include "TGraph.h"
#include <map>
Functions
void norm_th1_per_bin_width_per_primaries (TH1D *histo, int total_primaries)
void norm_th2_per_bin_width_per_primaries (TH2D *histo, int total_primaries)
void Plot ()
Function Documentation
void norm_th1_per_bin_width_per_primaries (TH1D * histo, int total_primaries)
Definition at line 12 of file Plot.C.
View newest version in sPHENIX GitHub at line 12 of file Plot.C
Referenced by Plot().
void norm_th2_per_bin_width_per_primaries (TH2D * histo, int total_primaries)
Definition at line 33 of file Plot.C.
View newest version in sPHENIX GitHub at line 33 of file Plot.C
Referenced by Plot().
void Plot ()
Definition at line 62 of file Plot.C.
View newest version in sPHENIX GitHub at line 62 of file Plot.C
References color(), e6, f, leg, max, norm_th1_per_bin_width_per_primaries(), norm_th2_per_bin_width_per_primaries(), and system().