ECCE @ EIC Software: G4HETCFragment Class Reference
G4HETCFragment Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCFragment.hh>
Public Member Functions
G4HETCFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4HETCFragment ()
G4double CalcEmissionProbability (const G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundFragment
G4VPreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4VPreCompoundFragment ()
void Initialize (const G4Fragment &aFragment)
virtual G4double SampleKineticEnergy (const G4Fragment &aFragment)=0
G4bool IsItPossible (const G4Fragment &aFragment) const
G4ReactionProduct * GetReactionProduct () const
G4int GetA () const
G4int GetZ () const
G4int GetRestA () const
G4int GetRestZ () const
G4double GetBindingEnergy () const
G4double GetEnergyThreshold () const
G4double GetEmissionProbability () const
G4double GetNuclearMass () const
G4double GetRestNuclearMass () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Protected Member Functions
virtual G4double K (const G4Fragment &aFragment)=0
virtual G4double GetSpinFactor () const =0
virtual G4double GetAlpha () const =0
virtual G4double GetBeta () const =0
G4double BetaRand (G4int N, G4int L) const
Private Member Functions
G4double IntegrateEmissionProbability (G4double &Low, G4double &Up, const G4Fragment &aFragment)
G4HETCFragment ()
G4HETCFragment (const G4HETCFragment &right)
const G4HETCFragment & operator= (const G4HETCFragment &right)
G4bool operator== (const G4HETCFragment &right) const
G4bool operator!= (const G4HETCFragment &right) const
Private Attributes
G4double r2norm
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundFragment
G4NuclearLevelData * fNucData
G4DeexPrecoParameters * theParameters
G4Pow * g4calc
G4int theA
G4int theZ
G4int theResA
G4int theResZ
G4int theFragA
G4int theFragZ
G4double theResA13
G4double theBindingEnergy
G4double theMinKinEnergy
G4double theMaxKinEnergy
G4double theResMass
G4double theReducedMass
G4double theMass
G4double theEmissionProbability
G4double theCoulombBarrier
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 39 of file G4HETCFragment.hh.
View newest version in sPHENIX GitHub at line 39 of file G4HETCFragment.hh
Constructor & Destructor Documentation
G4HETCFragment::G4HETCFragment (const G4ParticleDefinition * part, G4VCoulombBarrier * aCoulombBarrier)
Definition at line 39 of file G4HETCFragment.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HETCFragment.cc
References G4DeexPrecoParameters::GetR0(), CLHEP::hbarc, CLHEP::pi, r2norm, and G4VPreCompoundFragment::theParameters.
G4HETCFragment::~G4HETCFragment () virtual
Definition at line 47 of file G4HETCFragment.cc.
View newest version in sPHENIX GitHub at line 47 of file G4HETCFragment.cc
G4HETCFragment::G4HETCFragment () private
G4HETCFragment::G4HETCFragment (const G4HETCFragment & right) private
Member Function Documentation
G4double G4HETCFragment::BetaRand (G4int N, G4int L) const inline protected
Definition at line 78 of file G4HETCFragment.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HETCFragment.hh
References G4INCL::DeJongSpin::shoot(), Y1, and Y2.
Referenced by G4HETCChargedFragment::SampleKineticEnergy(), and G4HETCNeutron::SampleKineticEnergy().
G4double G4HETCFragment::CalcEmissionProbability (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundFragment.
Definition at line 51 of file G4HETCFragment.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HETCFragment.cc
References G4VPreCompoundFragment::GetEnergyThreshold(), IntegrateEmissionProbability(), G4VPreCompoundFragment::theCoulombBarrier, G4VPreCompoundFragment::theEmissionProbability, and G4VPreCompoundFragment::theMaxKinEnergy.
virtual G4double G4HETCFragment::GetAlpha () const protected pure virtual
Implements G4VPreCompoundFragment.
Implemented in G4HETCNeutron, G4HETCDeuteron, G4HETCAlpha, G4HETCHe3, G4HETCProton, and G4HETCTriton.
Referenced by IntegrateEmissionProbability().
virtual G4double G4HETCFragment::GetBeta () const protected pure virtual
Implements G4VPreCompoundFragment.
Implemented in G4HETCNeutron, G4HETCDeuteron, G4HETCAlpha, G4HETCHe3, G4HETCProton, and G4HETCTriton.
Referenced by IntegrateEmissionProbability().
virtual G4double G4HETCFragment::GetSpinFactor () const protected pure virtual
Implemented in G4HETCNeutron, G4HETCDeuteron, G4HETCAlpha, G4HETCHe3, G4HETCProton, and G4HETCTriton.
Referenced by IntegrateEmissionProbability().
G4double G4HETCFragment::IntegrateEmissionProbability (G4double & Low, G4double & Up, const G4Fragment & aFragment) private
Definition at line 67 of file G4HETCFragment.cc.
View newest version in sPHENIX GitHub at line 67 of file G4HETCFragment.cc
References A(), G4VPreCompoundFragment::fNucData, G4VPreCompoundFragment::g4calc, GetAlpha(), GetBeta(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), GetSpinFactor(), H, K(), max, N, P, G4INCL::PhysicalConstants::Pf, pi2, G4Pow::powN(), r2norm, G4VPreCompoundFragment::theA, G4VPreCompoundFragment::theFragA, G4VPreCompoundFragment::theFragZ, G4VPreCompoundFragment::theReducedMass, G4VPreCompoundFragment::theResA, G4VPreCompoundFragment::theResZ, X, Y, and G4Pow::Z23().
Referenced by CalcEmissionProbability().
virtual G4double G4HETCFragment::K (const G4Fragment & aFragment) protected pure virtual
Implemented in G4HETCNeutron, G4HETCDeuteron, G4HETCAlpha, G4HETCHe3, G4HETCProton, and G4HETCTriton.
Referenced by IntegrateEmissionProbability().
G4bool G4HETCFragment::operator!= (const G4HETCFragment & right) const private
const G4HETCFragment& G4HETCFragment::operator= (const G4HETCFragment & right) private
G4bool G4HETCFragment::operator== (const G4HETCFragment & right) const private
Member Data Documentation
G4double G4HETCFragment::r2norm private
Definition at line 75 of file G4HETCFragment.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HETCFragment.hh
Referenced by G4HETCFragment(), and IntegrateEmissionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCFragment.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4HETCFragment.cc