ECCE @ EIC Software: G4DNASmoluchowskiReactionModel Class Reference
G4DNASmoluchowskiReactionModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNASmoluchowskiReactionModel.hh>
Public Member Functions
G4DNASmoluchowskiReactionModel ()
virtual ~G4DNASmoluchowskiReactionModel ()
G4DNASmoluchowskiReactionModel (const G4DNASmoluchowskiReactionModel &)=delete
G4DNASmoluchowskiReactionModel & operator= (const G4DNASmoluchowskiReactionModel &)=delete
virtual void Initialise (const G4MolecularConfiguration *, const G4Track &)
virtual void InitialiseToPrint (const G4MolecularConfiguration *)
virtual G4double GetReactionRadius (const G4MolecularConfiguration *, const G4MolecularConfiguration *)
virtual G4double GetReactionRadius (const G4int)
virtual G4bool FindReaction (const G4Track &, const G4Track &, G4double, G4double &, G4bool)
Public Member Functions inherited from G4VDNAReactionModel
G4VDNAReactionModel ()
G4VDNAReactionModel (const G4VDNAReactionModel &)=delete
G4VDNAReactionModel & operator= (const G4VDNAReactionModel &)=delete
virtual ~G4VDNAReactionModel ()
void SetReactionTable (const G4DNAMolecularReactionTable *)
const G4DNAMolecularReactionTable * GetReactionTable ()
Private Attributes
const std::vector< const
G4DNAMolecularReactionData * > * fpReactionData
Additional Inherited Members
Protected Attributes inherited from G4VDNAReactionModel
const G4DNAMolecularReactionTable * fpReactionTable
Detailed Description
G4DNASmoluchowskiReactionModel should be used for very fast reactions (high reaction rate) : the reactions between reactants occuring at encounter. When the time step is constrained this model uses brownian bridge : "Absorbing (Smoluchowski) boundary condition" Reference : On the simulation of diffusion processes close to boundaries, N. J. B. Green, Molecular Physics, 65: 6, 1399 — 1408(1988)
Definition at line 63 of file G4DNASmoluchowskiReactionModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4DNASmoluchowskiReactionModel.hh
Constructor & Destructor Documentation
G4DNASmoluchowskiReactionModel::G4DNASmoluchowskiReactionModel ()
Definition at line 35 of file G4DNASmoluchowskiReactionModel.cc.
View newest version in sPHENIX GitHub at line 35 of file G4DNASmoluchowskiReactionModel.cc
G4DNASmoluchowskiReactionModel::~G4DNASmoluchowskiReactionModel () virtual default
G4DNASmoluchowskiReactionModel::G4DNASmoluchowskiReactionModel (const G4DNASmoluchowskiReactionModel &) delete
Member Function Documentation
G4bool G4DNASmoluchowskiReactionModel::FindReaction (const G4Track & __trackA, const G4Track & __trackB, G4double __reactionRadius, G4double & __separationDistance, G4bool __alongStepReaction) virtual
Implements G4VDNAReactionModel.
Definition at line 67 of file G4DNASmoluchowskiReactionModel.cc.
View newest version in sPHENIX GitHub at line 67 of file G4DNASmoluchowskiReactionModel.cc
References D(), G4Exp(), G4UniformRand, G4Step::GetDeltaTime(), GetMolecule(), G4StepPoint::GetPosition(), G4Track::GetPosition(), G4Step::GetPreStepPoint(), G4Track::GetStep(), and k.
G4double G4DNASmoluchowskiReactionModel::GetReactionRadius (const G4MolecularConfiguration * pMol1, const G4MolecularConfiguration * pMol2) virtual
Implements G4VDNAReactionModel.
Definition at line 54 of file G4DNASmoluchowskiReactionModel.cc.
View newest version in sPHENIX GitHub at line 54 of file G4DNASmoluchowskiReactionModel.cc
References G4VDNAReactionModel::fpReactionTable, G4DNAMolecularReactionData::GetEffectiveReactionRadius(), and G4DNAMolecularReactionTable::GetReactionData().
G4double G4DNASmoluchowskiReactionModel::GetReactionRadius (const G4int __i) virtual
Implements G4VDNAReactionModel.
Definition at line 61 of file G4DNASmoluchowskiReactionModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4DNASmoluchowskiReactionModel.cc
void G4DNASmoluchowskiReactionModel::Initialise (const G4MolecularConfiguration * pMolecule, const G4Track &) virtual
Reimplemented from G4VDNAReactionModel.
Definition at line 43 of file G4DNASmoluchowskiReactionModel.cc.
View newest version in sPHENIX GitHub at line 43 of file G4DNASmoluchowskiReactionModel.cc
References fpReactionData, G4VDNAReactionModel::fpReactionTable, and G4DNAMolecularReactionTable::GetReactionData().
void G4DNASmoluchowskiReactionModel::InitialiseToPrint (const G4MolecularConfiguration * pMolecule) virtual
Implements G4VDNAReactionModel.
Definition at line 49 of file G4DNASmoluchowskiReactionModel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4DNASmoluchowskiReactionModel.cc
References fpReactionData, G4VDNAReactionModel::fpReactionTable, and G4DNAMolecularReactionTable::GetReactionData().
G4DNASmoluchowskiReactionModel& G4DNASmoluchowskiReactionModel::operator= (const G4DNASmoluchowskiReactionModel &) delete
Member Data Documentation
const std::vector<const G4DNAMolecularReactionData*>* G4DNASmoluchowskiReactionModel::fpReactionData private
Definition at line 85 of file G4DNASmoluchowskiReactionModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DNASmoluchowskiReactionModel.hh
Referenced by Initialise(), and InitialiseToPrint().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNASmoluchowskiReactionModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNASmoluchowskiReactionModel.cc