ECCE @ EIC Software: G4HadronPhysicsQGSP_FTFP_BERT Class Reference
G4HadronPhysicsQGSP_FTFP_BERT Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGSP_FTFP_BERT.hh>
Public Member Functions
G4HadronPhysicsQGSP_FTFP_BERT (G4int verbose=1)
G4HadronPhysicsQGSP_FTFP_BERT (const G4String &name, G4bool quasiElastic=true)
Public Member Functions inherited from G4HadronPhysicsQGSP_BERT
G4HadronPhysicsQGSP_BERT (G4int verbose=1)
G4HadronPhysicsQGSP_BERT (const G4String &name, G4bool quasiElastic=true)
virtual ~G4HadronPhysicsQGSP_BERT ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Attributes
G4bool QuasiElastic
Protected Attributes inherited from G4HadronPhysicsQGSP_BERT
G4bool QuasiElasticFTF
G4bool QuasiElasticQGS
G4double minQGSP_proton
G4double minQGSP_neutron
G4double minQGSP_pik
G4double minFTFP_proton
G4double minFTFP_neutron
G4double minFTFP_pik
G4double maxFTFP_proton
G4double maxFTFP_neutron
G4double maxFTFP_pik
G4double minBERT_proton
G4double minBERT_neutron
G4double minBERT_pik
G4double maxBERT_proton
G4double maxBERT_neutron
G4double maxBERT_pik
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4HadronPhysicsQGSP_BERT
void CreateModels ()
virtual void Neutron ()
virtual void Proton ()
virtual void Pion ()
virtual void Kaon ()
virtual void Others ()
virtual void DumpBanner ()
virtual void ExtraConfiguration ()
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 48 of file G4HadronPhysicsQGSP_FTFP_BERT.hh.
View newest version in sPHENIX GitHub at line 48 of file G4HadronPhysicsQGSP_FTFP_BERT.hh
Constructor & Destructor Documentation
G4HadronPhysicsQGSP_FTFP_BERT::G4HadronPhysicsQGSP_FTFP_BERT (G4int verbose = 1)
Definition at line 46 of file G4HadronPhysicsQGSP_FTFP_BERT.cc.
View newest version in sPHENIX GitHub at line 46 of file G4HadronPhysicsQGSP_FTFP_BERT.cc
G4HadronPhysicsQGSP_FTFP_BERT::G4HadronPhysicsQGSP_FTFP_BERT (const G4String & name, G4bool quasiElastic = true)
Definition at line 49 of file G4HadronPhysicsQGSP_FTFP_BERT.cc.
View newest version in sPHENIX GitHub at line 49 of file G4HadronPhysicsQGSP_FTFP_BERT.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4HadronPhysicsQGSP_BERT::maxBERT_neutron, G4HadronPhysicsQGSP_BERT::maxBERT_pik, G4HadronPhysicsQGSP_BERT::maxBERT_proton, G4HadronPhysicsQGSP_BERT::minFTFP_neutron, G4HadronPhysicsQGSP_BERT::minFTFP_pik, and G4HadronPhysicsQGSP_BERT::minFTFP_proton.
Member Data Documentation
G4bool G4HadronPhysicsQGSP_FTFP_BERT::QuasiElastic protected
Definition at line 55 of file G4HadronPhysicsQGSP_FTFP_BERT.hh.
View newest version in sPHENIX GitHub at line 55 of file G4HadronPhysicsQGSP_FTFP_BERT.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGSP_FTFP_BERT.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsQGSP_FTFP_BERT.cc