ECCE @ EIC Software: G4TrajectoryEncounteredVolumeFilter Class Reference
G4TrajectoryEncounteredVolumeFilter Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryEncounteredVolumeFilter.hh>
Public Member Functions
G4TrajectoryEncounteredVolumeFilter (const G4String &name="Unspecified")
virtual ~G4TrajectoryEncounteredVolumeFilter ()
virtual bool Evaluate (const G4VTrajectory &) const
virtual void Print (std::ostream &ostr) const
virtual void Clear ()
void Add (const G4String &volume)
Public Member Functions inherited from G4SmartFilter< G4VTrajectory >
G4SmartFilter (const G4String &name)
virtual ~G4SmartFilter ()
G4bool Accept (const G4VTrajectory &) const
virtual void PrintAll (std::ostream &ostr) const
virtual void Reset ()
void SetActive (const G4bool &)
G4bool GetActive () const
void SetInvert (const G4bool &)
G4bool GetInvert () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Public Member Functions inherited from G4VFilter< G4VTrajectory >
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
G4String Name () const
G4String GetName () const
Private Attributes
std::vector< G4String > fVolumes
Additional Inherited Members
Public Types inherited from G4VFilter< G4VTrajectory >
typedef G4VTrajectory Type
Detailed Description
Definition at line 39 of file G4TrajectoryEncounteredVolumeFilter.hh.
View newest version in sPHENIX GitHub at line 39 of file G4TrajectoryEncounteredVolumeFilter.hh
Constructor & Destructor Documentation
G4TrajectoryEncounteredVolumeFilter::G4TrajectoryEncounteredVolumeFilter (const G4String & name = "Unspecified")
Definition at line 38 of file G4TrajectoryEncounteredVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 38 of file G4TrajectoryEncounteredVolumeFilter.cc
G4TrajectoryEncounteredVolumeFilter::~G4TrajectoryEncounteredVolumeFilter () virtual
Definition at line 42 of file G4TrajectoryEncounteredVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 42 of file G4TrajectoryEncounteredVolumeFilter.cc
Member Function Documentation
void G4TrajectoryEncounteredVolumeFilter::Add (const G4String & volume)
Definition at line 82 of file G4TrajectoryEncounteredVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 82 of file G4TrajectoryEncounteredVolumeFilter.cc
References fVolumes.
void G4TrajectoryEncounteredVolumeFilter::Clear () virtual
Implements G4SmartFilter< G4VTrajectory >.
Definition at line 100 of file G4TrajectoryEncounteredVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 100 of file G4TrajectoryEncounteredVolumeFilter.cc
References fVolumes.
bool G4TrajectoryEncounteredVolumeFilter::Evaluate (const G4VTrajectory & traj) const virtual
Implements G4SmartFilter< G4VTrajectory >.
Definition at line 45 of file G4TrajectoryEncounteredVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 45 of file G4TrajectoryEncounteredVolumeFilter.cc
References G4VTrajectoryPoint::CreateAttValues(), fVolumes, G4Exception(), G4RichTrajectory::GetPoint(), G4RichTrajectory::GetPointEntries(), and JustWarning.
void G4TrajectoryEncounteredVolumeFilter::Print (std::ostream & ostr) const virtual
Implements G4SmartFilter< G4VTrajectory >.
Definition at line 88 of file G4TrajectoryEncounteredVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 88 of file G4TrajectoryEncounteredVolumeFilter.cc
References fVolumes, and G4endl.
Member Data Documentation
std::vector<G4String> G4TrajectoryEncounteredVolumeFilter::fVolumes private
Definition at line 63 of file G4TrajectoryEncounteredVolumeFilter.hh.
View newest version in sPHENIX GitHub at line 63 of file G4TrajectoryEncounteredVolumeFilter.hh
Referenced by Add(), Clear(), Evaluate(), and Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryEncounteredVolumeFilter.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryEncounteredVolumeFilter.cc