ECCE @ EIC Software: G4Pythia6DecayerMessenger Class Reference
G4Pythia6DecayerMessenger Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4decayer/G4Pythia6DecayerMessenger.hh>
Public Member Functions
G4Pythia6DecayerMessenger (G4Pythia6Decayer *pythia6Decayer)
virtual ~G4Pythia6DecayerMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String string)
G4Pythia6DecayerMessenger (G4Pythia6Decayer *pythia6Decayer)
virtual ~G4Pythia6DecayerMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String string)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4Pythia6DecayerMessenger ()
Not implemented.
G4Pythia6DecayerMessenger (const G4Pythia6DecayerMessenger &right)
Not implemented.
G4Pythia6DecayerMessenger & operator= (const G4Pythia6DecayerMessenger &r)
Not implemented.
G4Pythia6DecayerMessenger ()
Not implemented.
G4Pythia6DecayerMessenger (const G4Pythia6DecayerMessenger &right)
Not implemented.
G4Pythia6DecayerMessenger & operator= (const G4Pythia6DecayerMessenger &r)
Not implemented.
Private Attributes
G4Pythia6Decayer * fPythia6Decayer
associated class
G4UIdirectory * fDirectory
command directory
G4UIcmdWithAnInteger * fVerboseCmd
command: verbose
G4UIcmdWithAnInteger * fDecayTypeCmd
command: forceDEcayeType
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Messenger class that defines commands for G4Pythia6Decayer.
Implements command
/pythia6Decayer/verbose [level]
/pythia6Decayer/forceDecayType [decayType]
Definition at line 51 of file G4Pythia6DecayerMessenger.hh.
View newest version in sPHENIX GitHub at line 51 of file G4Pythia6DecayerMessenger.hh
Constructor & Destructor Documentation
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger (G4Pythia6Decayer * pythia6Decayer)
Standard constructor
Definition at line 55 of file G4Pythia6DecayerMessenger.cc.
View newest version in sPHENIX GitHub at line 55 of file G4Pythia6DecayerMessenger.cc
References G4UIcommand::AvailableForStates(), fDecayTypeCmd, fDirectory, fVerboseCmd, G4State_Idle, kMaxDecay, kSemiElectronic, G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), and G4UIcommand::SetRange().
G4Pythia6DecayerMessenger::~G4Pythia6DecayerMessenger () virtual
Destructor
Definition at line 86 of file G4Pythia6DecayerMessenger.cc.
View newest version in sPHENIX GitHub at line 86 of file G4Pythia6DecayerMessenger.cc
References fDecayTypeCmd, fDirectory, and fVerboseCmd.
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger () private
Not implemented.
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger (const G4Pythia6DecayerMessenger & right) private
Not implemented.
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger (G4Pythia6Decayer * pythia6Decayer)
virtual G4Pythia6DecayerMessenger::~G4Pythia6DecayerMessenger () virtual
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger () private
Not implemented.
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger (const G4Pythia6DecayerMessenger & right) private
Not implemented.
Member Function Documentation
G4Pythia6DecayerMessenger& G4Pythia6DecayerMessenger::operator= (const G4Pythia6DecayerMessenger & r) private
Not implemented.
G4Pythia6DecayerMessenger& G4Pythia6DecayerMessenger::operator= (const G4Pythia6DecayerMessenger & r) private
Not implemented.
virtual void G4Pythia6DecayerMessenger::SetNewValue (G4UIcommand * command, G4String string) virtual
Reimplemented from G4UImessenger.
void G4Pythia6DecayerMessenger::SetNewValue (G4UIcommand * command, G4String string) virtual
Apply command to the associated object.
Reimplemented from G4UImessenger.
Definition at line 101 of file G4Pythia6DecayerMessenger.cc.
View newest version in sPHENIX GitHub at line 101 of file G4Pythia6DecayerMessenger.cc
References fDecayTypeCmd, G4Pythia6Decayer::ForceDecayType(), fPythia6Decayer, fVerboseCmd, G4UIcmdWithAnInteger::GetNewIntValue(), and G4Pythia6Decayer::SetVerboseLevel().
Member Data Documentation
G4UIcmdWithAnInteger * G4Pythia6DecayerMessenger::fDecayTypeCmd private
command: forceDEcayeType
Definition at line 74 of file G4Pythia6DecayerMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4Pythia6DecayerMessenger.hh
Referenced by G4Pythia6DecayerMessenger(), SetNewValue(), and ~G4Pythia6DecayerMessenger().
G4UIdirectory * G4Pythia6DecayerMessenger::fDirectory private
command directory
Definition at line 72 of file G4Pythia6DecayerMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4Pythia6DecayerMessenger.hh
Referenced by G4Pythia6DecayerMessenger(), and ~G4Pythia6DecayerMessenger().
G4Pythia6Decayer * G4Pythia6DecayerMessenger::fPythia6Decayer private
associated class
Definition at line 71 of file G4Pythia6DecayerMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Pythia6DecayerMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAnInteger * G4Pythia6DecayerMessenger::fVerboseCmd private
command: verbose
Definition at line 73 of file G4Pythia6DecayerMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4Pythia6DecayerMessenger.hh
Referenced by G4Pythia6DecayerMessenger(), SetNewValue(), and ~G4Pythia6DecayerMessenger().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4decayer/G4Pythia6DecayerMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/include/G4Pythia6DecayerMessenger.hh
coresoftware/blob/master/simulation/g4simulation/g4decayer/G4Pythia6DecayerMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/src/G4Pythia6DecayerMessenger.cc