ECCE @ EIC Software: G4Decay Class Reference
G4Decay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/decay/include/G4Decay.hh>
Public Member Functions
G4Decay (const G4String &processName="Decay")
virtual ~G4Decay ()
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4VParticleChange * AtRestDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual G4bool IsApplicable (const G4ParticleDefinition &) override
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual void StartTracking (G4Track *) override
virtual void EndTracking () override
void SetExtDecayer (G4VExtDecayer *)
const G4VExtDecayer * GetExtDecayer () const
G4double GetRemainderLifeTime () const
virtual void ProcessDescription (std::ostream &outFile) const override
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4VParticleChange * DecayIt (const G4Track &aTrack, const G4Step &aStep)
virtual void DaughterPolarization (const G4Track &aTrack, G4DecayProducts *products)
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *condition) override
Protected Attributes
G4int verboseLevel
const G4double HighestValue
G4double fRemainderLifeTime
G4ParticleChangeForDecay fParticleChangeForDecay
G4VExtDecayer * pExtDecayer
Private Member Functions
G4Decay (const G4Decay &right)
G4Decay & operator= (const G4Decay &right)
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 62 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 62 of file G4Decay.hh
Constructor & Destructor Documentation
G4Decay::G4Decay (const G4String & processName = "Decay")
Definition at line 62 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 62 of file G4Decay.cc
References DECAY, fParticleChangeForDecay, G4cout, G4endl, G4VProcess::GetVerboseLevel(), G4VProcess::pParticleChange, and G4VProcess::SetProcessSubType().
G4Decay::~G4Decay () virtual
Definition at line 81 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 81 of file G4Decay.cc
References pExtDecayer.
G4Decay::G4Decay (const G4Decay & right) private
Member Function Documentation
G4VParticleChange * G4Decay::AtRestDoIt (const G4Track & aTrack, const G4Step & aStep) inline override virtual
Reimplemented from G4VRestDiscreteProcess.
Reimplemented in G4DecayWithSpin.
Definition at line 183 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 183 of file G4Decay.hh
References DecayIt().
G4double G4Decay::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) override virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 477 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 477 of file G4Decay.cc
References DBL_MIN, fRemainderLifeTime, G4Track::GetDynamicParticle(), GetMeanLifeTime(), G4DynamicParticle::GetPreAssignedDecayProperTime(), G4Track::GetProperTime(), NotForced, and G4VProcess::theNumberOfInteractionLengthLeft.
void G4Decay::BuildPhysicsTable (const G4ParticleDefinition &) override virtual
Reimplemented from G4VProcess.
Definition at line 175 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 175 of file G4Decay.cc
void G4Decay::DaughterPolarization (const G4Track & aTrack, G4DecayProducts * products) protected virtual
Reimplemented in G4PionDecayMakeSpin.
Definition at line 386 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 386 of file G4Decay.cc
Referenced by DecayIt().
G4VParticleChange * G4Decay::DecayIt (const G4Track & aTrack, const G4Step & aStep) protected virtual
Definition at line 180 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 180 of file G4Decay.cc
References G4VParticleChange::AddSecondary(), G4DecayProducts::Boost(), G4VProcess::ClearNumberOfInteractionLengthLeft(), cm, DaughterPolarization(), G4VDecayChannel::DecayIt(), G4DecayProducts::DumpInfo(), G4DecayTable::entries(), G4DecayProducts::entries(), FatalException, fParticleChangeForDecay, fRemainderLifeTime, fStopAndKill, fStopButAlive, G4cout, G4endl, G4Exception(), G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughterName(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetLocalTime(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4VDecayChannel::GetNumberOfDaughters(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGStable(), G4Track::GetPosition(), G4DynamicParticle::GetPreAssignedDecayProducts(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4VDecayChannel::GetVerboseLevel(), G4VProcess::GetVerboseLevel(), GeV, G4VExtDecayer::ImportDecayProducts(), G4ParticleChangeForDecay::Initialize(), G4DecayProducts::IsChecked(), G4VDecayChannel::IsOKWithParentMass(), JustWarning, MeV, ns, pExtDecayer, G4DecayProducts::PopProducts(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForDecay::ProposeLocalTime(), G4VParticleChange::ProposeTrackStatus(), G4DecayTable::SelectADecayChannel(), G4Track::SetGoodForTrackingFlag(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4VDecayChannel::SetVerboseLevel(), x, y, and z.
Referenced by G4DecayWithSpin::AtRestDoIt(), AtRestDoIt(), G4DecayWithSpin::PostStepDoIt(), and PostStepDoIt().
void G4Decay::EndTracking () override virtual
Reimplemented from G4VProcess.
Definition at line 401 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 401 of file G4Decay.cc
References G4VProcess::ClearNumberOfInteractionLengthLeft(), and G4VProcess::currentInteractionLength.
const G4VExtDecayer * G4Decay::GetExtDecayer () const inline
Definition at line 193 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 193 of file G4Decay.hh
References pExtDecayer.
G4double G4Decay::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 129 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 129 of file G4Decay.cc
References source.hepunit::c_light, DBL_MAX, DBL_MIN, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), G4DynamicParticle::GetTotalMomentum(), G4VProcess::GetVerboseLevel(), GeV, and HighestValue.
Referenced by PostStepGetPhysicalInteractionLength().
G4double G4Decay::GetMeanLifeTime (const G4Track & aTrack, G4ForceCondition * condition) override protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 100 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 100 of file G4Decay.cc
References G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), G4VProcess::GetVerboseLevel(), and ns.
Referenced by AtRestGetPhysicalInteractionLength().
G4double G4Decay::GetRemainderLifeTime () const inline
Definition at line 199 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 199 of file G4Decay.hh
References fRemainderLifeTime.
G4bool G4Decay::IsApplicable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 88 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 88 of file G4Decay.cc
References G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), and MeV.
Referenced by XrayFluoPhysicsList::AddDecay(), PhysicsList::AddDecay(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), G4DecayPhysics::ConstructProcess(), and GammaRayTelGeneralPhysics::ConstructProcess().
G4Decay& G4Decay::operator= (const G4Decay & right) private
G4VParticleChange * G4Decay::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VRestDiscreteProcess.
Reimplemented in G4DecayWithSpin.
Definition at line 507 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 507 of file G4Decay.cc
References DecayIt(), fParticleChangeForDecay, fStopAndKill, fStopButAlive, G4Track::GetTrackStatus(), and G4ParticleChangeForDecay::Initialize().
G4double G4Decay::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 410 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 410 of file G4Decay.cc
References source.hepunit::c_light, cm, G4VProcess::currentInteractionLength, DBL_MAX, G4DynamicParticle::DumpInfo(), fRemainderLifeTime, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetMass(), G4Track::GetMaterial(), GetMeanFreePath(), G4Material::GetName(), G4ParticleDefinition::GetPDGLifeTime(), G4DynamicParticle::GetPreAssignedDecayProperTime(), G4Track::GetProperTime(), G4DynamicParticle::GetTotalMomentum(), NotForced, perMillion, G4VProcess::SubtractNumberOfInteractionLengthLeft(), G4VProcess::theNumberOfInteractionLengthLeft, and verboseLevel.
void G4Decay::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Reimplemented in G4DecayWithSpin, and G4PionDecayMakeSpin.
Definition at line 521 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 521 of file G4Decay.cc
References G4VProcess::GetProcessName().
void G4Decay::SetExtDecayer (G4VExtDecayer * val)
Definition at line 497 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 497 of file G4Decay.cc
References DECAY_External, pExtDecayer, and G4VProcess::SetProcessSubType().
Referenced by P6DExtDecayerPhysics::ConstructProcess().
void G4Decay::StartTracking (G4Track *) override virtual
Reimplemented from G4VProcess.
Definition at line 393 of file G4Decay.cc.
View newest version in sPHENIX GitHub at line 393 of file G4Decay.cc
References G4VProcess::currentInteractionLength, fRemainderLifeTime, and G4VProcess::ResetNumberOfInteractionLengthLeft().
Member Data Documentation
G4ParticleChangeForDecay G4Decay::fParticleChangeForDecay protected
Definition at line 176 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 176 of file G4Decay.hh
Referenced by DecayIt(), G4Decay(), G4DecayWithSpin::PostStepDoIt(), and PostStepDoIt().
G4double G4Decay::fRemainderLifeTime protected
Definition at line 173 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 173 of file G4Decay.hh
Referenced by G4DecayWithSpin::AtRestDoIt(), AtRestGetPhysicalInteractionLength(), DecayIt(), GetRemainderLifeTime(), PostStepGetPhysicalInteractionLength(), and StartTracking().
const G4double G4Decay::HighestValue protected
Definition at line 170 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 170 of file G4Decay.hh
Referenced by GetMeanFreePath().
G4VExtDecayer* G4Decay::pExtDecayer protected
Definition at line 179 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 179 of file G4Decay.hh
Referenced by DecayIt(), GetExtDecayer(), SetExtDecayer(), and ~G4Decay().
G4int G4Decay::verboseLevel protected
Definition at line 162 of file G4Decay.hh.
View newest version in sPHENIX GitHub at line 162 of file G4Decay.hh
Referenced by PostStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/decay/include/G4Decay.hh
geant4/tree/geant4-10.6-release/source/processes/decay/src/G4Decay.cc