ECCE @ EIC Software: G4AtomicShell Class Reference
G4AtomicShell Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4AtomicShell.hh>
Public Member Functions
G4AtomicShell (G4int id, G4double e)
G4double BindingEnergy () const
G4int ShellId () const
Private Member Functions
G4AtomicShell & operator= (const G4AtomicShell &right)=delete
G4AtomicShell (const G4AtomicShell &)=delete
Private Attributes
G4int identifier
G4double bindingEnergy
Detailed Description
Definition at line 54 of file G4AtomicShell.hh.
View newest version in sPHENIX GitHub at line 54 of file G4AtomicShell.hh
Constructor & Destructor Documentation
G4AtomicShell::G4AtomicShell (G4int id, G4double e) inline explicit
Definition at line 61 of file G4AtomicShell.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AtomicShell.hh
G4AtomicShell::G4AtomicShell (const G4AtomicShell &) private delete
Member Function Documentation
G4double G4AtomicShell::BindingEnergy () const inline
Definition at line 79 of file G4AtomicShell.hh.
View newest version in sPHENIX GitHub at line 79 of file G4AtomicShell.hh
References bindingEnergy.
Referenced by G4VAtomDeexcitation::AlongStepDeexcitation(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4OrlicLiXsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4hImpactIonisation::PostStepDoIt(), G4PenelopeOscillatorManager::ReadElementData(), G4LivermoreIonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), and G4PenelopeIonisationModel::SampleSecondaries().
G4AtomicShell& G4AtomicShell::operator= (const G4AtomicShell & right) private delete
G4int G4AtomicShell::ShellId () const inline
Definition at line 84 of file G4AtomicShell.hh.
View newest version in sPHENIX GitHub at line 84 of file G4AtomicShell.hh
References identifier.
Referenced by G4UAtomicDeexcitation::GenerateParticles(), and G4hImpactIonisation::PostStepDoIt().
Member Data Documentation
G4double G4AtomicShell::bindingEnergy private
Definition at line 75 of file G4AtomicShell.hh.
View newest version in sPHENIX GitHub at line 75 of file G4AtomicShell.hh
Referenced by BindingEnergy().
G4int G4AtomicShell::identifier private
Definition at line 74 of file G4AtomicShell.hh.
View newest version in sPHENIX GitHub at line 74 of file G4AtomicShell.hh
Referenced by ShellId().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4AtomicShell.hh