ECCE @ EIC Software: G4XAqmElastic Class Reference
G4XAqmElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XAqmElastic.hh>
Public Member Functions
G4XAqmElastic ()
virtual ~G4XAqmElastic ()
G4bool operator== (const G4XAqmElastic &right) const
G4bool operator!= (const G4XAqmElastic &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual G4String Name () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Private Member Functions
G4XAqmElastic (const G4XAqmElastic &right)
const G4XAqmElastic & operator= (const G4XAqmElastic &right)
Static Private Attributes
static const G4double _lowLimit = 0.
static const G4double _highLimit = DBL_MAX
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 50 of file G4XAqmElastic.hh.
View newest version in sPHENIX GitHub at line 50 of file G4XAqmElastic.hh
Constructor & Destructor Documentation
G4XAqmElastic::G4XAqmElastic ()
Definition at line 57 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 57 of file G4XAqmElastic.cc
G4XAqmElastic::~G4XAqmElastic () virtual
Definition at line 64 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 64 of file G4XAqmElastic.cc
G4XAqmElastic::G4XAqmElastic (const G4XAqmElastic & right) private
Member Function Documentation
G4double G4XAqmElastic::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 80 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 80 of file G4XAqmElastic.cc
References G4XAqmTotal::CrossSection(), G4Pow::GetInstance(), and G4Pow::powA().
Referenced by G4XMesonBaryonElastic::CrossSection().
virtual const G4CrossSectionVector* G4XAqmElastic::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 64 of file G4XAqmElastic.hh.
View newest version in sPHENIX GitHub at line 64 of file G4XAqmElastic.hh
G4bool G4XAqmElastic::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 109 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 109 of file G4XAqmElastic.cc
References _highLimit, _lowLimit, and G4VCrossSectionSource::InLimits().
G4String G4XAqmElastic::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 102 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 102 of file G4XAqmElastic.cc
G4bool G4XAqmElastic::operator!= (const G4XAqmElastic & right) const
Definition at line 74 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 74 of file G4XAqmElastic.cc
const G4XAqmElastic& G4XAqmElastic::operator= (const G4XAqmElastic & right) private
G4bool G4XAqmElastic::operator== (const G4XAqmElastic & right) const
Definition at line 68 of file G4XAqmElastic.cc.
View newest version in sPHENIX GitHub at line 68 of file G4XAqmElastic.cc
Member Data Documentation
const G4double G4XAqmElastic::_highLimit = DBL_MAX static private
Definition at line 80 of file G4XAqmElastic.hh.
View newest version in sPHENIX GitHub at line 80 of file G4XAqmElastic.hh
Referenced by IsValid().
const G4double G4XAqmElastic::_lowLimit = 0. static private
Definition at line 79 of file G4XAqmElastic.hh.
View newest version in sPHENIX GitHub at line 79 of file G4XAqmElastic.hh
Referenced by IsValid().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XAqmElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XAqmElastic.cc