ECCE @ EIC Software: G03ColorWriter Class Reference
G03ColorWriter Class Reference
GDML writer for the color attributes.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G03/include/G03ColorWriter.hh>
Public Member Functions
G03ColorWriter ()
~G03ColorWriter ()
void AddExtension (xercesc::DOMElement *volumeElement, const G4LogicalVolume *const vol)
void ExtensionWrite (xercesc::DOMElement *element)
void ColorWrite (xercesc::DOMElement *volumeElement, const G4VisAttributes *const att)
G4bool BookAttribute (const G4VisAttributes *const att)
Public Member Functions inherited from G4GDMLWriteStructure
G4GDMLWriteStructure ()
virtual ~G4GDMLWriteStructure ()
virtual void StructureWrite (xercesc::DOMElement *)
void AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const)
void SetEnergyCutsExport (G4bool)
void SetSDExport (G4bool)
G4int GetMaxExportLevel () const
void SetMaxExportLevel (G4int)
Public Member Functions inherited from G4GDMLWriteParamvol
virtual void ParamvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
virtual void ParamvolAlgorithmWrite (xercesc::DOMElement *paramvolElement, const G4VPhysicalVolume *const paramvol)
Public Member Functions inherited from G4GDMLWriteSetup
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)
Public Member Functions inherited from G4GDMLWriteSolids
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void UserinfoWrite (xercesc::DOMElement *)
G4String GenerateName (const G4String &, const void *const)
Private Attributes
std::vector< const
G4VisAttributes * > fAttribs
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Protected Member Functions inherited from G4GDMLWriteStructure
void DivisionvolWrite (xercesc::DOMElement *, const G4PVDivision *const)
void PhysvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const topVol, const G4Transform3D &transform, const G4String &moduleName)
void ReplicavolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
void AssemblyWrite (xercesc::DOMElement *, const int assemblyID)
G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const topVol, const G4int depth)
void SurfacesWrite ()
void BorderSurfaceCache (const G4LogicalBorderSurface *const)
void SkinSurfaceCache (const G4LogicalSkinSurface *const)
const G4LogicalBorderSurface * GetBorderSurface (const G4VPhysicalVolume *const)
const G4LogicalSkinSurface * GetSkinSurface (const G4LogicalVolume *const)
G4bool FindOpticalSurface (const G4SurfaceProperty *)
void ExportEnergyCuts (const G4LogicalVolume *const)
void ExportSD (const G4LogicalVolume *const)
Protected Attributes inherited from G4GDMLWriteStructure
xercesc::DOMElement * structureElement
std::vector
< xercesc::DOMElement * > borderElementVec
std::vector
< xercesc::DOMElement * > skinElementVec
std::map< const
G4LogicalVolume
*, G4GDMLAuxListType > auxmap
Static Protected Attributes inherited from G4GDMLWriteSolids
static const G4int maxTransforms = 8
Detailed Description
GDML writer for the color attributes.
Definition at line 48 of file G03ColorWriter.hh.
View newest version in sPHENIX GitHub at line 48 of file G03ColorWriter.hh
Constructor & Destructor Documentation
G03ColorWriter::G03ColorWriter ()
Definition at line 39 of file G03ColorWriter.cc.
View newest version in sPHENIX GitHub at line 39 of file G03ColorWriter.cc
G03ColorWriter::~G03ColorWriter ()
Definition at line 46 of file G03ColorWriter.cc.
View newest version in sPHENIX GitHub at line 46 of file G03ColorWriter.cc
Member Function Documentation
void G03ColorWriter::AddExtension (xercesc::DOMElement * volumeElement, const G4LogicalVolume *const vol) virtual
Reimplemented from G4GDMLWrite.
Definition at line 52 of file G03ColorWriter.cc.
View newest version in sPHENIX GitHub at line 52 of file G03ColorWriter.cc
References ColorWrite(), and G4LogicalVolume::GetVisAttributes().
G4bool G03ColorWriter::BookAttribute (const G4VisAttributes *const att)
Definition at line 104 of file G03ColorWriter.cc.
View newest version in sPHENIX GitHub at line 104 of file G03ColorWriter.cc
References fAttribs, and pos().
Referenced by ColorWrite().
void G03ColorWriter::ColorWrite (xercesc::DOMElement * volumeElement, const G4VisAttributes *const att)
Definition at line 73 of file G03ColorWriter.cc.
View newest version in sPHENIX GitHub at line 73 of file G03ColorWriter.cc
References a, b, BookAttribute(), color(), G4GDMLWrite::extElement, Acts::UnitConstants::g, G4cout, G4endl, G4GDMLWrite::GenerateName(), G4Colour::GetAlpha(), G4Colour::GetBlue(), G4VisAttributes::GetColor(), G4Colour::GetGreen(), G4Colour::GetRed(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), and r.
Referenced by AddExtension().
void G03ColorWriter::ExtensionWrite (xercesc::DOMElement * element) virtual
Reimplemented from G4GDMLWrite.
Definition at line 61 of file G03ColorWriter.cc.
View newest version in sPHENIX GitHub at line 61 of file G03ColorWriter.cc
References G4GDMLWrite::extElement, G4cout, G4endl, and G4GDMLWrite::NewElement().
Member Data Documentation
std::vector<const G4VisAttributes*> G03ColorWriter::fAttribs private
Definition at line 66 of file G03ColorWriter.hh.
View newest version in sPHENIX GitHub at line 66 of file G03ColorWriter.hh
Referenced by BookAttribute().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G03/include/G03ColorWriter.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G03/src/G03ColorWriter.cc