ECCE @ EIC Software: TransitionRadiationPhysics Class Reference
TransitionRadiationPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/TransitionRadiationPhysics.hh>
Public Member Functions
TransitionRadiationPhysics (G4int verb, DetectorConstruction *ptr)
virtual ~TransitionRadiationPhysics ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void SetXTRModel (const G4String &name)
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Attributes
DetectorConstruction * fDetector
G4int fVerbose
G4String fXTRModel
Static Private Attributes
static G4ThreadLocal
G4VXTRenergyLoss * fXTRProcess = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 44 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 44 of file TransitionRadiationPhysics.hh
Constructor & Destructor Documentation
TransitionRadiationPhysics::TransitionRadiationPhysics (G4int verb, DetectorConstruction * ptr)
Definition at line 53 of file TransitionRadiationPhysics.cc.
View newest version in sPHENIX GitHub at line 53 of file TransitionRadiationPhysics.cc
TransitionRadiationPhysics::~TransitionRadiationPhysics () virtual
Definition at line 63 of file TransitionRadiationPhysics.cc.
View newest version in sPHENIX GitHub at line 63 of file TransitionRadiationPhysics.cc
Member Function Documentation
virtual void TransitionRadiationPhysics::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 51 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 51 of file TransitionRadiationPhysics.hh
void TransitionRadiationPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 68 of file TransitionRadiationPhysics.cc.
View newest version in sPHENIX GitHub at line 68 of file TransitionRadiationPhysics.cc
References G4ProcessManager::AddDiscreteProcess(), G4Electron::Electron(), fDetector, RadiatorDescription::fFoilMaterial, RadiatorDescription::fFoilNumber, RadiatorDescription::fFoilThickness, RadiatorDescription::fGasMaterial, RadiatorDescription::fGasThickness, RadiatorDescription::fLogicalVolume, fVerbose, fXTRModel, fXTRProcess, G4cout, G4endl, DetectorConstruction::GetAbsorberMaterial(), G4ParticleDefinition::GetProcessManager(), DetectorConstruction::GetRadiatorDescription(), G4Positron::Positron(), and G4VProcess::SetVerboseLevel().
void TransitionRadiationPhysics::SetXTRModel (const G4String & name) inline
Definition at line 58 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 58 of file TransitionRadiationPhysics.hh
References fXTRModel.
Referenced by PhysicsList::SetXTRModel().
Member Data Documentation
DetectorConstruction* TransitionRadiationPhysics::fDetector private
Definition at line 58 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 58 of file TransitionRadiationPhysics.hh
Referenced by ConstructProcess().
G4int TransitionRadiationPhysics::fVerbose private
Definition at line 63 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 63 of file TransitionRadiationPhysics.hh
Referenced by ConstructProcess().
G4String TransitionRadiationPhysics::fXTRModel private
Definition at line 64 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 64 of file TransitionRadiationPhysics.hh
Referenced by ConstructProcess(), and SetXTRModel().
G4ThreadLocal G4VXTRenergyLoss * TransitionRadiationPhysics::fXTRProcess = nullptr static private
Definition at line 66 of file TransitionRadiationPhysics.hh.
View newest version in sPHENIX GitHub at line 66 of file TransitionRadiationPhysics.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/TransitionRadiationPhysics.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/TransitionRadiationPhysics.cc