ECCE @ EIC Software: G4QuadrupoleMagField Class Reference
G4QuadrupoleMagField Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4QuadrupoleMagField.hh>
Public Member Functions
G4QuadrupoleMagField (G4double pGradient)
G4QuadrupoleMagField (G4double pGradient, G4ThreeVector pOrigin, G4RotationMatrix *pMatrix)
~G4QuadrupoleMagField ()
void GetFieldValue (const G4double yTrack[], G4double B[]) const
G4Field * Clone () const
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
virtual void GetFieldValue (const G4double Point[4], G4double *Bfield) const =0
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Private Attributes
G4double fGradient = 0.0
G4ThreeVector fOrigin = G4ThreeVector(0.0, 0.0, 0.0)
G4RotationMatrix * fpMatrix = nullptr
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 48 of file G4QuadrupoleMagField.hh.
View newest version in sPHENIX GitHub at line 48 of file G4QuadrupoleMagField.hh
Constructor & Destructor Documentation
G4QuadrupoleMagField::G4QuadrupoleMagField (G4double pGradient)
Definition at line 40 of file G4QuadrupoleMagField.cc.
View newest version in sPHENIX GitHub at line 40 of file G4QuadrupoleMagField.cc
References fGradient, and fpMatrix.
Referenced by Clone().
G4QuadrupoleMagField::G4QuadrupoleMagField (G4double pGradient, G4ThreeVector pOrigin, G4RotationMatrix * pMatrix)
Definition at line 48 of file G4QuadrupoleMagField.cc.
View newest version in sPHENIX GitHub at line 48 of file G4QuadrupoleMagField.cc
References fGradient, fOrigin, and fpMatrix.
G4QuadrupoleMagField::~G4QuadrupoleMagField ()
Definition at line 66 of file G4QuadrupoleMagField.cc.
View newest version in sPHENIX GitHub at line 66 of file G4QuadrupoleMagField.cc
Member Function Documentation
G4Field * G4QuadrupoleMagField::Clone () const virtual
Reimplemented from G4Field.
Definition at line 59 of file G4QuadrupoleMagField.cc.
View newest version in sPHENIX GitHub at line 59 of file G4QuadrupoleMagField.cc
References fGradient, fOrigin, fpMatrix, and G4QuadrupoleMagField().
void G4QuadrupoleMagField::GetFieldValue (const G4double yTrack[], G4double B[]) const
Definition at line 72 of file G4QuadrupoleMagField.cc.
View newest version in sPHENIX GitHub at line 72 of file G4QuadrupoleMagField.cc
References fGradient, fOrigin, fpMatrix, CLHEP::HepRotation::inverse(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4QuadrupoleMagField::fGradient = 0.0 private
Definition at line 64 of file G4QuadrupoleMagField.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QuadrupoleMagField.hh
Referenced by Clone(), G4QuadrupoleMagField(), and GetFieldValue().
G4ThreeVector G4QuadrupoleMagField::fOrigin = G4ThreeVector(0.0, 0.0, 0.0) private
Definition at line 65 of file G4QuadrupoleMagField.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QuadrupoleMagField.hh
Referenced by Clone(), G4QuadrupoleMagField(), and GetFieldValue().
G4RotationMatrix* G4QuadrupoleMagField::fpMatrix = nullptr private
Definition at line 66 of file G4QuadrupoleMagField.hh.
View newest version in sPHENIX GitHub at line 66 of file G4QuadrupoleMagField.hh
Referenced by Clone(), G4QuadrupoleMagField(), and GetFieldValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4QuadrupoleMagField.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4QuadrupoleMagField.cc