ECCE @ EIC Software: G4SteppingManager Class Reference
G4SteppingManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4SteppingManager.hh>
Public Member Functions
G4SteppingManager ()
~G4SteppingManager ()
const G4TrackVector * GetSecondary () const
void SetUserAction (G4UserSteppingAction *apAction)
G4Track * GetTrack () const
void SetVerboseLevel (G4int vLevel)
void SetVerbose (G4VSteppingVerbose *)
G4Step * GetStep () const
void SetNavigator (G4Navigator *value)
G4StepStatus Stepping ()
void SetInitialStep (G4Track *valueTrack)
void GetProcessNumber ()
G4double GetPhysicalStep ()
G4double GetGeometricalStep ()
G4double GetCorrectedStep ()
G4bool GetPreStepPointIsGeom ()
G4bool GetFirstStep ()
G4StepStatus GetfStepStatus ()
G4double GetTempInitVelocity ()
G4double GetTempVelocity ()
G4double GetMass ()
G4double GetsumEnergyChange ()
G4VParticleChange * GetfParticleChange ()
G4Track * GetfTrack ()
G4TrackVector * GetfSecondary ()
G4Step * GetfStep ()
G4StepPoint * GetfPreStepPoint ()
G4StepPoint * GetfPostStepPoint ()
G4VPhysicalVolume * GetfCurrentVolume ()
G4VSensitiveDetector * GetfSensitive ()
G4VProcess * GetfCurrentProcess ()
G4ProcessVector * GetfAtRestDoItVector ()
G4ProcessVector * GetfAlongStepDoItVector ()
G4ProcessVector * GetfPostStepDoItVector ()
G4ProcessVector * GetfAlongStepGetPhysIntVector ()
G4ProcessVector * GetfPostStepGetPhysIntVector ()
G4ProcessVector * GetfAtRestGetPhysIntVector ()
G4double GetcurrentMinimumStep ()
G4double GetnumberOfInteractionLengthLeft ()
size_t GetfAtRestDoItProcTriggered ()
size_t GetfAlongStepDoItProcTriggered ()
size_t GetfPostStepDoItProcTriggered ()
G4int GetfN2ndariesAtRestDoIt ()
G4int GetfN2ndariesAlongStepDoIt ()
G4int GetfN2ndariesPostStepDoIt ()
G4Navigator * GetfNavigator ()
G4int GetverboseLevel ()
size_t GetMAXofAtRestLoops ()
size_t GetMAXofAlongStepLoops ()
size_t GetMAXofPostStepLoops ()
G4SelectedAtRestDoItVector * GetfSelectedAtRestDoItVector ()
G4SelectedAlongStepDoItVector * GetfSelectedAlongStepDoItVector ()
G4SelectedPostStepDoItVector * GetfSelectedPostStepDoItVector ()
G4double GetfPreviousStepSize ()
const G4TouchableHandle & GetTouchableHandle ()
G4SteppingControl GetStepControlFlag ()
G4UserSteppingAction * GetUserAction ()
G4double GetphysIntLength ()
G4ForceCondition GetfCondition ()
G4GPILSelection GetfGPILSelection ()
Public Attributes
G4bool KillVerbose
Private Member Functions
void DefinePhysicalStepLength ()
void InvokeAtRestDoItProcs ()
void InvokeAlongStepDoItProcs ()
void InvokePostStepDoItProcs ()
void InvokePSDIP (size_t)
G4double CalculateSafety ()
void ApplyProductionCut (G4Track *)
Private Attributes
G4UserSteppingAction * fUserSteppingAction
G4VSteppingVerbose * fVerbose
G4double PhysicalStep
G4double GeometricalStep
G4double CorrectedStep
G4bool PreStepPointIsGeom
G4bool FirstStep
G4StepStatus fStepStatus
G4double TempInitVelocity
G4double TempVelocity
G4double Mass
G4double sumEnergyChange
G4VParticleChange * fParticleChange
G4Track * fTrack
G4TrackVector * fSecondary
G4Step * fStep
G4StepPoint * fPreStepPoint
G4StepPoint * fPostStepPoint
G4VPhysicalVolume * fCurrentVolume
G4VSensitiveDetector * fSensitive
G4VProcess * fCurrentProcess
G4ProcessVector * fAtRestDoItVector
G4ProcessVector * fAlongStepDoItVector
G4ProcessVector * fPostStepDoItVector
G4ProcessVector * fAtRestGetPhysIntVector
G4ProcessVector * fAlongStepGetPhysIntVector
G4ProcessVector * fPostStepGetPhysIntVector
size_t MAXofAtRestLoops
size_t MAXofAlongStepLoops
size_t MAXofPostStepLoops
size_t fAtRestDoItProcTriggered
size_t fAlongStepDoItProcTriggered
size_t fPostStepDoItProcTriggered
G4int fN2ndariesAtRestDoIt
G4int fN2ndariesAlongStepDoIt
G4int fN2ndariesPostStepDoIt
G4Navigator * fNavigator
G4int verboseLevel
G4SelectedAtRestDoItVector * fSelectedAtRestDoItVector
G4SelectedAlongStepDoItVector * fSelectedAlongStepDoItVector
G4SelectedPostStepDoItVector * fSelectedPostStepDoItVector
G4double fPreviousStepSize
G4TouchableHandle fTouchableHandle
G4SteppingControl StepControlFlag
G4double kCarTolerance
G4double proposedSafety
G4ThreeVector endpointSafOrigin
G4double endpointSafety
G4double physIntLength
G4ForceCondition fCondition
G4GPILSelection fGPILSelection
Detailed Description
Definition at line 91 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 91 of file G4SteppingManager.hh
Constructor & Destructor Documentation
G4SteppingManager::G4SteppingManager ()
Definition at line 55 of file G4SteppingManager.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SteppingManager.cc
References DBL_MAX, fPostStepPoint, fPreStepPoint, fSecondary, fSelectedAlongStepDoItVector, fSelectedAtRestDoItVector, fSelectedPostStepDoItVector, fStep, fVerbose, G4GeometryTolerance::GetInstance(), G4VSteppingVerbose::GetInstance(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4GeometryTolerance::GetSurfaceTolerance(), G4TransportationManager::GetTransportationManager(), kCarTolerance, KillVerbose, G4Step::NewSecondaryVector(), physIntLength, G4VSteppingVerbose::SetInstance(), SetNavigator(), and SizeOfSelectedDoItVector.
G4SteppingManager::~G4SteppingManager ()
Definition at line 96 of file G4SteppingManager.cc.
View newest version in sPHENIX GitHub at line 96 of file G4SteppingManager.cc
References G4Step::DeleteSecondaryVector(), fSelectedAlongStepDoItVector, fSelectedAtRestDoItVector, fSelectedPostStepDoItVector, fStep, fTouchableHandle, fUserSteppingAction, fVerbose, and KillVerbose.
Member Function Documentation
void G4SteppingManager::ApplyProductionCut (G4Track * aSecondary) private
Definition at line 639 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 639 of file G4SteppingManager2.cc
References kdfinder::abs(), G4Step::AddTotalEnergyDeposit(), CalculateSafety(), DBL_MIN, fPreStepPoint, fStep, G4DynamicParticle::GetCharge(), G4ProductionCutsTable::GetCoupleIndex(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4ProductionCutsTable::GetEnergyCutsVector(), G4ProductionCuts::GetIndex(), G4Track::GetKineticEnergy(), G4StepPoint::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetRange(), G4LossTableManager::Instance(), G4Track::IsGoodForTracking(), and G4Track::SetKineticEnergy().
Referenced by InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), and InvokePSDIP().
G4double G4SteppingManager::CalculateSafety () inline private
Definition at line 489 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 489 of file G4SteppingManager.hh
References endpointSafety, endpointSafOrigin, fPostStepPoint, G4StepPoint::GetPosition(), kCarTolerance, and max.
Referenced by ApplyProductionCut(), and InvokePSDIP().
void G4SteppingManager::DefinePhysicalStepLength () private
Definition at line 127 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 127 of file G4SteppingManager2.cc
References CandidateForSelection, Conditionally, DBL_MAX, G4VSteppingVerbose::DPSLAlongStep(), G4VSteppingVerbose::DPSLPostStep(), G4VSteppingVerbose::DPSLStarted(), ExclusivelyForced, fAlongStepDoItProc, FatalException, fCondition, fCurrentProcess, fExclusivelyForcedProc, fGeomBoundary, fGPILSelection, Forced, fPostStepDoItProc, fPostStepDoItProcTriggered, fPreviousStepSize, fSelectedPostStepDoItVector, fStep, fStepStatus, fTrack, fVerbose, G4Exception(), G4Step::GetPostStepPoint(), InActivated, MAXofAlongStepLoops, MAXofPostStepLoops, NotForced, PhysicalStep, physIntLength, proposedSafety, G4StepPoint::SetProcessDefinedStep(), StronglyForced, and verboseLevel.
Referenced by Stepping().
G4double G4SteppingManager::GetCorrectedStep () inline
Definition at line 306 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 306 of file G4SteppingManager.hh
References CorrectedStep.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetcurrentMinimumStep ()
size_t G4SteppingManager::GetfAlongStepDoItProcTriggered () inline
Definition at line 402 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 402 of file G4SteppingManager.hh
References fAtRestDoItProcTriggered.
Referenced by G4VSteppingVerbose::CopyState().
G4ProcessVector * G4SteppingManager::GetfAlongStepDoItVector () inline
Definition at line 370 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 370 of file G4SteppingManager.hh
References fAlongStepDoItVector.
Referenced by G4VSteppingVerbose::CopyState().
G4ProcessVector * G4SteppingManager::GetfAlongStepGetPhysIntVector () inline
Definition at line 381 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 381 of file G4SteppingManager.hh
References fAlongStepGetPhysIntVector.
Referenced by G4VSteppingVerbose::CopyState().
size_t G4SteppingManager::GetfAtRestDoItProcTriggered () inline
Definition at line 399 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 399 of file G4SteppingManager.hh
References fAtRestDoItProcTriggered.
Referenced by G4VSteppingVerbose::CopyState().
G4ProcessVector * G4SteppingManager::GetfAtRestDoItVector () inline
Definition at line 367 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 367 of file G4SteppingManager.hh
References fAtRestDoItVector.
Referenced by G4VSteppingVerbose::CopyState().
G4ProcessVector * G4SteppingManager::GetfAtRestGetPhysIntVector () inline
Definition at line 377 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 377 of file G4SteppingManager.hh
References fAtRestGetPhysIntVector.
Referenced by G4VSteppingVerbose::CopyState().
G4ForceCondition G4SteppingManager::GetfCondition () inline
Definition at line 451 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 451 of file G4SteppingManager.hh
References fCondition.
Referenced by G4VSteppingVerbose::CopyState().
G4VProcess * G4SteppingManager::GetfCurrentProcess () inline
Definition at line 363 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 363 of file G4SteppingManager.hh
References fCurrentProcess.
Referenced by G4VSteppingVerbose::CopyState().
G4VPhysicalVolume * G4SteppingManager::GetfCurrentVolume () inline
Definition at line 357 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 357 of file G4SteppingManager.hh
References fCurrentVolume.
Referenced by G4VSteppingVerbose::CopyState().
G4GPILSelection G4SteppingManager::GetfGPILSelection () inline
Definition at line 454 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 454 of file G4SteppingManager.hh
References fGPILSelection.
Referenced by G4VSteppingVerbose::CopyState().
G4bool G4SteppingManager::GetFirstStep () inline
Definition at line 314 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 314 of file G4SteppingManager.hh
References FirstStep.
Referenced by G4VSteppingVerbose::CopyState().
G4int G4SteppingManager::GetfN2ndariesAlongStepDoIt () inline
Definition at line 411 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 411 of file G4SteppingManager.hh
References fN2ndariesAlongStepDoIt.
Referenced by G4VSteppingVerbose::CopyState(), and LXeSteppingAction::UserSteppingAction().
G4int G4SteppingManager::GetfN2ndariesAtRestDoIt () inline
Definition at line 408 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 408 of file G4SteppingManager.hh
References fN2ndariesAtRestDoIt.
Referenced by G4VSteppingVerbose::CopyState(), and LXeSteppingAction::UserSteppingAction().
G4int G4SteppingManager::GetfN2ndariesPostStepDoIt () inline
Definition at line 414 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 414 of file G4SteppingManager.hh
References fN2ndariesPostStepDoIt.
Referenced by G4VSteppingVerbose::CopyState(), and LXeSteppingAction::UserSteppingAction().
G4Navigator * G4SteppingManager::GetfNavigator () inline
Definition at line 418 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 418 of file G4SteppingManager.hh
References fNavigator.
Referenced by G4VSteppingVerbose::CopyState().
G4VParticleChange * G4SteppingManager::GetfParticleChange () inline
Definition at line 336 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 336 of file G4SteppingManager.hh
References fParticleChange.
Referenced by G4VSteppingVerbose::CopyState().
size_t G4SteppingManager::GetfPostStepDoItProcTriggered () inline
Definition at line 405 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 405 of file G4SteppingManager.hh
References fPostStepDoItProcTriggered.
Referenced by G4VSteppingVerbose::CopyState().
G4ProcessVector * G4SteppingManager::GetfPostStepDoItVector () inline
Definition at line 373 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 373 of file G4SteppingManager.hh
References fPostStepDoItVector.
Referenced by G4VSteppingVerbose::CopyState().
G4ProcessVector * G4SteppingManager::GetfPostStepGetPhysIntVector () inline
Definition at line 385 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 385 of file G4SteppingManager.hh
References fPostStepGetPhysIntVector.
Referenced by G4VSteppingVerbose::CopyState().
G4StepPoint * G4SteppingManager::GetfPostStepPoint () inline
Definition at line 353 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 353 of file G4SteppingManager.hh
References fPostStepPoint.
Referenced by G4VSteppingVerbose::CopyState().
G4StepPoint * G4SteppingManager::GetfPreStepPoint () inline
Definition at line 350 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 350 of file G4SteppingManager.hh
References fPreStepPoint.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetfPreviousStepSize () inline
Definition at line 437 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 437 of file G4SteppingManager.hh
References fPreviousStepSize.
Referenced by G4VSteppingVerbose::CopyState().
G4TrackVector * G4SteppingManager::GetfSecondary () inline
Definition at line 344 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 344 of file G4SteppingManager.hh
References fStep, and G4Step::GetfSecondary().
Referenced by G4VSteppingVerbose::CopyState(), G4TrackingManager::GimmeSecondaries(), and LXeSteppingAction::UserSteppingAction().
G4SelectedAlongStepDoItVector * G4SteppingManager::GetfSelectedAlongStepDoItVector () inline
Definition at line 429 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 429 of file G4SteppingManager.hh
References fSelectedAlongStepDoItVector.
Referenced by G4VSteppingVerbose::CopyState().
G4SelectedAtRestDoItVector * G4SteppingManager::GetfSelectedAtRestDoItVector () inline
Definition at line 425 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 425 of file G4SteppingManager.hh
References fSelectedAtRestDoItVector.
Referenced by G4VSteppingVerbose::CopyState().
G4SelectedPostStepDoItVector * G4SteppingManager::GetfSelectedPostStepDoItVector () inline
Definition at line 433 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 433 of file G4SteppingManager.hh
References fSelectedPostStepDoItVector.
Referenced by G4VSteppingVerbose::CopyState().
G4VSensitiveDetector * G4SteppingManager::GetfSensitive () inline
Definition at line 360 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 360 of file G4SteppingManager.hh
References fSensitive.
Referenced by G4VSteppingVerbose::CopyState().
G4Step * G4SteppingManager::GetfStep () inline
Definition at line 347 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 347 of file G4SteppingManager.hh
References fStep.
Referenced by G4VSteppingVerbose::CopyState(), and G4ExceptionHandler::DumpTrackInfo().
G4StepStatus G4SteppingManager::GetfStepStatus () inline
Definition at line 318 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 318 of file G4SteppingManager.hh
References fStepStatus.
Referenced by G4VSteppingVerbose::CopyState().
G4Track * G4SteppingManager::GetfTrack () inline
Definition at line 340 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 340 of file G4SteppingManager.hh
References fTrack.
Referenced by G4VSteppingVerbose::CopyState(), and G4ExceptionHandler::DumpTrackInfo().
G4double G4SteppingManager::GetGeometricalStep () inline
Definition at line 302 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 302 of file G4SteppingManager.hh
References GeometricalStep.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetMass () inline
Definition at line 328 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 328 of file G4SteppingManager.hh
References Mass.
Referenced by G4VSteppingVerbose::CopyState().
size_t G4SteppingManager::GetMAXofAlongStepLoops () inline
Definition at line 392 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 392 of file G4SteppingManager.hh
References MAXofAlongStepLoops.
Referenced by G4VSteppingVerbose::CopyState().
size_t G4SteppingManager::GetMAXofAtRestLoops () inline
Definition at line 389 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 389 of file G4SteppingManager.hh
References MAXofAtRestLoops.
Referenced by G4VSteppingVerbose::CopyState().
size_t G4SteppingManager::GetMAXofPostStepLoops () inline
Definition at line 395 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 395 of file G4SteppingManager.hh
References MAXofPostStepLoops.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetnumberOfInteractionLengthLeft ()
G4double G4SteppingManager::GetPhysicalStep () inline
Definition at line 298 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 298 of file G4SteppingManager.hh
References PhysicalStep.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetphysIntLength () inline
Definition at line 448 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 448 of file G4SteppingManager.hh
References physIntLength.
Referenced by G4VSteppingVerbose::CopyState().
G4bool G4SteppingManager::GetPreStepPointIsGeom () inline
Definition at line 310 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 310 of file G4SteppingManager.hh
References PreStepPointIsGeom.
Referenced by G4VSteppingVerbose::CopyState().
void G4SteppingManager::GetProcessNumber ()
Definition at line 55 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SteppingManager2.cc
References G4ProcessVector::entries(), fAlongStepDoItVector, fAlongStepGetPhysIntVector, FatalException, fAtRestDoItVector, fAtRestGetPhysIntVector, fPostStepDoItVector, fPostStepGetPhysIntVector, fTrack, G4cerr, G4cout, G4endl, G4Exception(), G4ProcessManager::GetAlongStepProcessVector(), G4ProcessManager::GetAtRestProcessVector(), G4Track::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ProcessManager::GetPostStepProcessVector(), G4ParticleDefinition::GetProcessManager(), MAXofAlongStepLoops, MAXofAtRestLoops, MAXofPostStepLoops, Acts::UnitConstants::pm, SizeOfSelectedDoItVector, typeDoIt, and typeGPIL.
Referenced by G4ErrorPropagator::InitG4Track(), and G4TrackingManager::ProcessOneTrack().
const G4TrackVector * G4SteppingManager::GetSecondary () const inline
Definition at line 458 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 458 of file G4SteppingManager.hh
References fStep, and G4Step::GetSecondary().
G4Step * G4SteppingManager::GetStep () const inline
Definition at line 485 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 485 of file G4SteppingManager.hh
References fStep.
Referenced by G4ErrorPropagator::InitG4Track(), and G4TrackingManager::ProcessOneTrack().
G4SteppingControl G4SteppingManager::GetStepControlFlag () inline
Definition at line 445 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 445 of file G4SteppingManager.hh
References StepControlFlag.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetsumEnergyChange () inline
Definition at line 332 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 332 of file G4SteppingManager.hh
References sumEnergyChange.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetTempInitVelocity () inline
Definition at line 322 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 322 of file G4SteppingManager.hh
References TempInitVelocity.
Referenced by G4VSteppingVerbose::CopyState().
G4double G4SteppingManager::GetTempVelocity () inline
Definition at line 325 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 325 of file G4SteppingManager.hh
References TempVelocity.
Referenced by G4VSteppingVerbose::CopyState().
const G4TouchableHandle & G4SteppingManager::GetTouchableHandle () inline
Definition at line 441 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 441 of file G4SteppingManager.hh
References fTouchableHandle.
Referenced by G4VSteppingVerbose::CopyState().
G4Track * G4SteppingManager::GetTrack () const inline
Definition at line 473 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 473 of file G4SteppingManager.hh
References fTrack.
Referenced by G4TrackingMessenger::SetNewValue().
G4UserSteppingAction * G4SteppingManager::GetUserAction () inline
Definition at line 469 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 469 of file G4SteppingManager.hh
References fUserSteppingAction.
Referenced by G4VSteppingVerbose::CopyState().
G4int G4SteppingManager::GetverboseLevel () inline
Definition at line 421 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 421 of file G4SteppingManager.hh
References verboseLevel.
Referenced by G4VSteppingVerbose::CopyState(), and RE01SteppingAction::UserSteppingAction().
void G4SteppingManager::InvokeAlongStepDoItProcs () private
Definition at line 415 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 415 of file G4SteppingManager2.cc
References G4VProcess::AlongStepDoIt(), G4VSteppingVerbose::AlongStepDoItOneByOne(), ApplyProductionCut(), G4VParticleChange::Clear(), DBL_MIN, G4ProcessVector::entries(), fAlive, FatalException, fCurrentProcess, fExclusivelyForcedProc, fN2ndariesAlongStepDoIt, fParticleChange, fSecondary, fStep, fStepStatus, fStopAndKill, fStopButAlive, fTrack, fVerbose, G4Exception(), G4ParticleDefinition::GetApplyCutsFlag(), G4ProcessManager::GetAtRestProcessVector(), G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4VParticleChange::GetNumberOfSecondaries(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4VParticleChange::GetSecondary(), G4Track::GetTrackID(), G4VParticleChange::GetTrackStatus(), G4Track::GetTrackStatus(), MAXofAlongStepLoops, MAXofAtRestLoops, Acts::UnitConstants::pm, G4Track::SetCreatorProcess(), G4Track::SetParentID(), G4Track::SetTrackStatus(), G4VParticleChange::UpdateStepForAlongStep(), G4Step::UpdateTrack(), and verboseLevel.
Referenced by Stepping().
void G4SteppingManager::InvokeAtRestDoItProcs () private
Definition at line 281 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 281 of file G4SteppingManager2.cc
References ApplyProductionCut(), G4VProcess::AtRestDoIt(), G4VProcess::AtRestGPIL(), G4VParticleChange::Clear(), DBL_MAX, DBL_MIN, G4ProcessVector::entries(), FatalException, fAtRestDoItProcTriggered, fCondition, fCurrentProcess, fN2ndariesAtRestDoIt, Forced, fParticleChange, fSecondary, fSelectedAtRestDoItVector, fStep, fStopAndKill, fStopButAlive, fTrack, G4Exception(), G4ParticleDefinition::GetApplyCutsFlag(), G4ProcessManager::GetAtRestProcessVector(), G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4VParticleChange::GetNumberOfSecondaries(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4Step::GetPostStepPoint(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4VParticleChange::GetSecondary(), G4Track::GetTrackID(), InActivated, JustWarning, MAXofAtRestLoops, NotForced, Acts::UnitConstants::pm, G4Track::SetCreatorProcess(), G4Track::SetParentID(), G4StepPoint::SetProcessDefinedStep(), G4Step::SetStepLength(), G4Track::SetStepLength(), G4Track::SetTrackStatus(), G4VParticleChange::UpdateStepForAtRest(), and G4Step::UpdateTrack().
Referenced by Stepping().
void G4SteppingManager::InvokePostStepDoItProcs () private
Definition at line 514 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 514 of file G4SteppingManager2.cc
References ExclusivelyForced, fExclusivelyForcedProc, Forced, fPostStepDoItProc, fStep, fStepStatus, fStopAndKill, fTrack, fWorldBoundary, G4Track::GetNextVolume(), G4Step::GetPostStepPoint(), G4Track::GetTrackStatus(), InActivated, InvokePSDIP(), MAXofPostStepLoops, NotForced, G4StepPoint::SetStepStatus(), and StronglyForced.
Referenced by Stepping().
void G4SteppingManager::InvokePSDIP (size_t np) private
Definition at line 557 of file G4SteppingManager2.cc.
View newest version in sPHENIX GitHub at line 557 of file G4SteppingManager2.cc
References ApplyProductionCut(), CalculateSafety(), G4VParticleChange::Clear(), DBL_MIN, G4ProcessVector::entries(), FatalException, fCurrentProcess, fN2ndariesPostStepDoIt, fParticleChange, fSecondary, fStep, fStopButAlive, fTrack, fVerbose, G4Exception(), G4ParticleDefinition::GetApplyCutsFlag(), G4ProcessManager::GetAtRestProcessVector(), G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4VParticleChange::GetNumberOfSecondaries(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4Step::GetPostStepPoint(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4VParticleChange::GetSecondary(), G4Track::GetTrackID(), G4VParticleChange::GetTrackStatus(), Acts::UnitConstants::pm, G4VProcess::PostStepDoIt(), G4VSteppingVerbose::PostStepDoItOneByOne(), G4Track::SetCreatorProcess(), G4Track::SetParentID(), G4StepPoint::SetSafety(), G4Track::SetTrackStatus(), G4VParticleChange::UpdateStepForPostStep(), G4Step::UpdateTrack(), and verboseLevel.
Referenced by InvokePostStepDoItProcs().
void G4SteppingManager::SetInitialStep (G4Track * valueTrack)
Definition at line 255 of file G4SteppingManager.cc.
View newest version in sPHENIX GitHub at line 255 of file G4SteppingManager.cc
References CorrectedStep, G4Navigator::CreateTouchableHistory(), fAlive, false, FatalException, fCurrentVolume, FirstStep, fNavigator, fParticleChange, fPostponeToNextEvent, fPreviousStepSize, fStep, fStepStatus, fStopAndKill, fStopButAlive, fSuspend, fTouchableHandle, fTrack, fUndefined, fVerbose, G4cerr, G4cout, G4endl, G4Exception(), GeometricalStep, G4Track::GetCurrentStepNumber(), G4Track::GetDynamicParticle(), G4Track::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4DynamicParticle::GetMass(), G4Track::GetMomentumDirection(), G4Track::GetParentID(), G4Track::GetPosition(), G4VPhysicalVolume::GetRegularStructureId(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4VTouchable::GetVolume(), G4Track::GetVolume(), G4Step::InitializeStep(), G4Navigator::LocateGlobalPointAndSetup(), Mass, PhysicalStep, PreStepPointIsGeom, G4Navigator::ResetHierarchyAndLocate(), G4Track::SetLogicalVolumeAtVertex(), G4Track::SetNextTouchableHandle(), G4Track::SetOriginTouchableHandle(), G4Track::SetTouchableHandle(), G4Track::SetTrackStatus(), G4Track::SetVertexKineticEnergy(), G4Track::SetVertexMomentumDirection(), G4Track::SetVertexPosition(), sumEnergyChange, TempInitVelocity, TempVelocity, G4VSteppingVerbose::TrackingStarted(), and verboseLevel.
Referenced by G4ErrorPropagator::InitG4Track(), and G4TrackingManager::ProcessOneTrack().
void G4SteppingManager::SetNavigator (G4Navigator * value) inline
Definition at line 462 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 462 of file G4SteppingManager.hh
References fNavigator.
Referenced by G4SteppingManager(), and G4ErrorPropagatorManager::StartNavigator().
void G4SteppingManager::SetUserAction (G4UserSteppingAction * apAction) inline
Definition at line 466 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 466 of file G4SteppingManager.hh
References fUserSteppingAction.
Referenced by G4TrackingManager::SetUserAction().
void G4SteppingManager::SetVerbose (G4VSteppingVerbose * yourVerbose) inline
Definition at line 481 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 481 of file G4SteppingManager.hh
References fVerbose.
void G4SteppingManager::SetVerboseLevel (G4int vLevel) inline
Definition at line 477 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 477 of file G4SteppingManager.hh
References verboseLevel.
Referenced by RE06SteppingVerbose::InitializeTimers(), and G4ErrorPropagatorManager::SetSteppingManagerVerboseLevel().
G4StepStatus G4SteppingManager::Stepping ()
Definition at line 115 of file G4SteppingManager.cc.
View newest version in sPHENIX GitHub at line 115 of file G4SteppingManager.cc
References G4Track::AddTrackLength(), G4VSteppingVerbose::AlongStepDoItAllDone(), G4VSteppingVerbose::AtRestDoItInvoked(), AvoidHitInvocation, G4Step::CopyPostToPreStepPoint(), DefinePhysicalStepLength(), endpointSafety, endpointSafOrigin, fAtRestDoItProc, fCurrentVolume, fN2ndariesAlongStepDoIt, fN2ndariesAtRestDoIt, fN2ndariesPostStepDoIt, fPostStepPoint, fPreviousStepSize, fSensitive, fStep, fStepStatus, fStopAndKill, fStopButAlive, fTrack, fUserSteppingAction, fVerbose, G4Step::GetControlFlag(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetNextTouchableHandle(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4LogicalVolume::GetRegion(), G4Region::GetRegionalSteppingAction(), G4Step::GetStepLength(), G4Track::GetTrackStatus(), G4VSensitiveDetector::Hit(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), InvokePostStepDoItProcs(), kCarTolerance, max, MAXofAtRestLoops, G4VSteppingVerbose::NewStep(), PhysicalStep, G4VSteppingVerbose::PostStepDoItAllDone(), proposedSafety, G4Step::ResetTotalEnergyDeposit(), G4Step::SetPointerToVectorOfAuxiliaryPoints(), G4StepPoint::SetSafety(), G4VSteppingVerbose::SetSilent(), G4Step::SetStepLength(), G4Track::SetStepLength(), G4StepPoint::SetStepStatus(), G4Track::SetTouchableHandle(), G4Step::SetTrack(), G4Track::SetTrackStatus(), StepControlFlag, G4VSteppingVerbose::StepInfo(), G4Step::UpdateTrack(), G4UserSteppingAction::UserSteppingAction(), and verboseLevel.
Referenced by G4ErrorPropagator::MakeOneStep(), and G4TrackingManager::ProcessOneTrack().
Member Data Documentation
G4double G4SteppingManager::CorrectedStep private
Definition at line 212 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 212 of file G4SteppingManager.hh
Referenced by GetCorrectedStep(), and SetInitialStep().
G4double G4SteppingManager::endpointSafety private
Definition at line 278 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 278 of file G4SteppingManager.hh
Referenced by CalculateSafety(), and Stepping().
G4ThreeVector G4SteppingManager::endpointSafOrigin private
Definition at line 277 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 277 of file G4SteppingManager.hh
Referenced by CalculateSafety(), and Stepping().
size_t G4SteppingManager::fAlongStepDoItProcTriggered private
Definition at line 250 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 250 of file G4SteppingManager.hh
G4ProcessVector* G4SteppingManager::fAlongStepDoItVector private
Definition at line 238 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 238 of file G4SteppingManager.hh
Referenced by GetfAlongStepDoItVector(), and GetProcessNumber().
G4ProcessVector* G4SteppingManager::fAlongStepGetPhysIntVector private
Definition at line 242 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 242 of file G4SteppingManager.hh
Referenced by GetfAlongStepGetPhysIntVector(), and GetProcessNumber().
size_t G4SteppingManager::fAtRestDoItProcTriggered private
Definition at line 249 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 249 of file G4SteppingManager.hh
Referenced by GetfAlongStepDoItProcTriggered(), GetfAtRestDoItProcTriggered(), and InvokeAtRestDoItProcs().
G4ProcessVector* G4SteppingManager::fAtRestDoItVector private
Definition at line 237 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 237 of file G4SteppingManager.hh
Referenced by GetfAtRestDoItVector(), and GetProcessNumber().
G4ProcessVector* G4SteppingManager::fAtRestGetPhysIntVector private
Definition at line 241 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 241 of file G4SteppingManager.hh
Referenced by GetfAtRestGetPhysIntVector(), and GetProcessNumber().
G4ForceCondition G4SteppingManager::fCondition private
Definition at line 282 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 282 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetfCondition(), and InvokeAtRestDoItProcs().
G4VProcess* G4SteppingManager::fCurrentProcess private
Definition at line 232 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 232 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetfCurrentProcess(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), and InvokePSDIP().
G4VPhysicalVolume* G4SteppingManager::fCurrentVolume private
Definition at line 230 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 230 of file G4SteppingManager.hh
Referenced by GetfCurrentVolume(), SetInitialStep(), and Stepping().
G4GPILSelection G4SteppingManager::fGPILSelection private
Definition at line 283 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 283 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), and GetfGPILSelection().
G4bool G4SteppingManager::FirstStep private
Definition at line 214 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 214 of file G4SteppingManager.hh
Referenced by GetFirstStep(), and SetInitialStep().
G4int G4SteppingManager::fN2ndariesAlongStepDoIt private
Definition at line 254 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 254 of file G4SteppingManager.hh
Referenced by GetfN2ndariesAlongStepDoIt(), InvokeAlongStepDoItProcs(), and Stepping().
G4int G4SteppingManager::fN2ndariesAtRestDoIt private
Definition at line 253 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 253 of file G4SteppingManager.hh
Referenced by GetfN2ndariesAtRestDoIt(), InvokeAtRestDoItProcs(), and Stepping().
G4int G4SteppingManager::fN2ndariesPostStepDoIt private
Definition at line 255 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 255 of file G4SteppingManager.hh
Referenced by GetfN2ndariesPostStepDoIt(), InvokePSDIP(), and Stepping().
G4Navigator* G4SteppingManager::fNavigator private
Definition at line 259 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 259 of file G4SteppingManager.hh
Referenced by GetfNavigator(), SetInitialStep(), and SetNavigator().
G4VParticleChange* G4SteppingManager::fParticleChange private
Definition at line 223 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 223 of file G4SteppingManager.hh
Referenced by GetfParticleChange(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), InvokePSDIP(), and SetInitialStep().
size_t G4SteppingManager::fPostStepDoItProcTriggered private
Definition at line 251 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 251 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), and GetfPostStepDoItProcTriggered().
G4ProcessVector* G4SteppingManager::fPostStepDoItVector private
Definition at line 239 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 239 of file G4SteppingManager.hh
Referenced by GetfPostStepDoItVector(), and GetProcessNumber().
G4ProcessVector* G4SteppingManager::fPostStepGetPhysIntVector private
Definition at line 243 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 243 of file G4SteppingManager.hh
Referenced by GetfPostStepGetPhysIntVector(), and GetProcessNumber().
G4StepPoint* G4SteppingManager::fPostStepPoint private
Definition at line 228 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 228 of file G4SteppingManager.hh
Referenced by CalculateSafety(), G4SteppingManager(), GetfPostStepPoint(), and Stepping().
G4StepPoint* G4SteppingManager::fPreStepPoint private
Definition at line 227 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 227 of file G4SteppingManager.hh
Referenced by ApplyProductionCut(), G4SteppingManager(), and GetfPreStepPoint().
G4double G4SteppingManager::fPreviousStepSize private
Definition at line 267 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 267 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetfPreviousStepSize(), SetInitialStep(), and Stepping().
G4TrackVector* G4SteppingManager::fSecondary private
Definition at line 225 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 225 of file G4SteppingManager.hh
Referenced by G4SteppingManager(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), and InvokePSDIP().
G4SelectedAlongStepDoItVector* G4SteppingManager::fSelectedAlongStepDoItVector private
Definition at line 264 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 264 of file G4SteppingManager.hh
Referenced by G4SteppingManager(), GetfSelectedAlongStepDoItVector(), and ~G4SteppingManager().
G4SelectedAtRestDoItVector* G4SteppingManager::fSelectedAtRestDoItVector private
Definition at line 263 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 263 of file G4SteppingManager.hh
Referenced by G4SteppingManager(), GetfSelectedAtRestDoItVector(), InvokeAtRestDoItProcs(), and ~G4SteppingManager().
G4SelectedPostStepDoItVector* G4SteppingManager::fSelectedPostStepDoItVector private
Definition at line 265 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 265 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), G4SteppingManager(), GetfSelectedPostStepDoItVector(), and ~G4SteppingManager().
G4VSensitiveDetector* G4SteppingManager::fSensitive private
Definition at line 231 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 231 of file G4SteppingManager.hh
Referenced by GetfSensitive(), and Stepping().
G4Step* G4SteppingManager::fStep private
Definition at line 226 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 226 of file G4SteppingManager.hh
Referenced by ApplyProductionCut(), DefinePhysicalStepLength(), G4SteppingManager(), GetfSecondary(), GetfStep(), GetSecondary(), GetStep(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), InvokePostStepDoItProcs(), InvokePSDIP(), SetInitialStep(), Stepping(), and ~G4SteppingManager().
G4StepStatus G4SteppingManager::fStepStatus private
Definition at line 215 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 215 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetfStepStatus(), InvokeAlongStepDoItProcs(), InvokePostStepDoItProcs(), SetInitialStep(), and Stepping().
G4TouchableHandle G4SteppingManager::fTouchableHandle private
Definition at line 269 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 269 of file G4SteppingManager.hh
Referenced by GetTouchableHandle(), SetInitialStep(), and ~G4SteppingManager().
G4Track* G4SteppingManager::fTrack private
Definition at line 224 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 224 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetfTrack(), GetProcessNumber(), GetTrack(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), InvokePostStepDoItProcs(), InvokePSDIP(), SetInitialStep(), and Stepping().
G4UserSteppingAction* G4SteppingManager::fUserSteppingAction private
Definition at line 206 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 206 of file G4SteppingManager.hh
Referenced by GetUserAction(), SetUserAction(), Stepping(), and ~G4SteppingManager().
G4VSteppingVerbose* G4SteppingManager::fVerbose private
Definition at line 208 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 208 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), G4SteppingManager(), InvokeAlongStepDoItProcs(), InvokePSDIP(), SetInitialStep(), SetVerbose(), Stepping(), and ~G4SteppingManager().
G4double G4SteppingManager::GeometricalStep private
Definition at line 211 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 211 of file G4SteppingManager.hh
Referenced by GetGeometricalStep(), and SetInitialStep().
G4double G4SteppingManager::kCarTolerance private
Definition at line 273 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 273 of file G4SteppingManager.hh
Referenced by CalculateSafety(), G4SteppingManager(), and Stepping().
G4bool G4SteppingManager::KillVerbose
Definition at line 185 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 185 of file G4SteppingManager.hh
Referenced by G4SteppingManager(), and ~G4SteppingManager().
G4double G4SteppingManager::Mass private
Definition at line 219 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 219 of file G4SteppingManager.hh
Referenced by GetMass(), and SetInitialStep().
size_t G4SteppingManager::MAXofAlongStepLoops private
Definition at line 246 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 246 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetMAXofAlongStepLoops(), GetProcessNumber(), and InvokeAlongStepDoItProcs().
size_t G4SteppingManager::MAXofAtRestLoops private
Definition at line 245 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 245 of file G4SteppingManager.hh
Referenced by GetMAXofAtRestLoops(), GetProcessNumber(), InvokeAlongStepDoItProcs(), InvokeAtRestDoItProcs(), and Stepping().
size_t G4SteppingManager::MAXofPostStepLoops private
Definition at line 247 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 247 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetMAXofPostStepLoops(), GetProcessNumber(), and InvokePostStepDoItProcs().
G4double G4SteppingManager::PhysicalStep private
Definition at line 210 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 210 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetPhysicalStep(), SetInitialStep(), and Stepping().
G4double G4SteppingManager::physIntLength private
Definition at line 281 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 281 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), G4SteppingManager(), and GetphysIntLength().
G4bool G4SteppingManager::PreStepPointIsGeom private
Definition at line 213 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 213 of file G4SteppingManager.hh
Referenced by GetPreStepPointIsGeom(), and SetInitialStep().
G4double G4SteppingManager::proposedSafety private
Definition at line 275 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 275 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), and Stepping().
G4SteppingControl G4SteppingManager::StepControlFlag private
Definition at line 271 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 271 of file G4SteppingManager.hh
Referenced by GetStepControlFlag(), and Stepping().
G4double G4SteppingManager::sumEnergyChange private
Definition at line 221 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 221 of file G4SteppingManager.hh
Referenced by GetsumEnergyChange(), and SetInitialStep().
G4double G4SteppingManager::TempInitVelocity private
Definition at line 217 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 217 of file G4SteppingManager.hh
Referenced by GetTempInitVelocity(), and SetInitialStep().
G4double G4SteppingManager::TempVelocity private
Definition at line 218 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 218 of file G4SteppingManager.hh
Referenced by GetTempVelocity(), and SetInitialStep().
G4int G4SteppingManager::verboseLevel private
Definition at line 261 of file G4SteppingManager.hh.
View newest version in sPHENIX GitHub at line 261 of file G4SteppingManager.hh
Referenced by DefinePhysicalStepLength(), GetverboseLevel(), InvokeAlongStepDoItProcs(), InvokePSDIP(), SetInitialStep(), SetVerboseLevel(), and Stepping().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4SteppingManager.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4SteppingManager.cc
geant4/tree/geant4-10.6-release/source/tracking/src/G4SteppingManager2.cc