ECCE @ EIC Software: G4MagIntegratorStepper Class Reference
G4MagIntegratorStepper Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4MagIntegratorStepper.hh>
Public Member Functions
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, G4bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
G4MagIntegratorStepper (const G4MagIntegratorStepper &)=delete
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)=delete
virtual void Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[])=0
virtual G4double DistChord () const =0
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
virtual G4int IntegratorOrder () const =0
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
G4bool IsFSAL () const
Protected Member Functions
void SetIntegrationOrder (G4int order)
void SetFSAL (G4bool flag=true)
Private Attributes
G4EquationOfMotion * fEquation_Rhs = nullptr
const G4int fNoIntegrationVariables = 0
const G4int fNoStateVariables = 0
unsigned long fNoRHSCalls = 0UL
G4int fIntegrationOrder = -1
G4bool fIsFSAL = false
Detailed Description
Definition at line 47 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 47 of file G4MagIntegratorStepper.hh
Constructor & Destructor Documentation
G4MagIntegratorStepper::G4MagIntegratorStepper (G4EquationOfMotion * Equation, G4int numIntegrationVariables, G4int numStateVariables = 12, G4bool isFSAL = false)
Definition at line 37 of file G4MagIntegratorStepper.cc.
View newest version in sPHENIX GitHub at line 37 of file G4MagIntegratorStepper.cc
virtual G4MagIntegratorStepper::~G4MagIntegratorStepper () virtual default
G4MagIntegratorStepper::G4MagIntegratorStepper (const G4MagIntegratorStepper &) delete
Member Function Documentation
virtual G4double G4MagIntegratorStepper::DistChord () const pure virtual
Implemented in G4BogackiShampine45, G4HelixMixedStepper, G4DoLoMcPriRK34, G4TsitourasRK45, G4ExactHelixStepper, G4MagHelicalStepper, G4DormandPrince745, G4BogackiShampine23, G4MagErrorStepper, G4NystromRK4, G4RK547FEq1, G4RK547FEq2, G4RK547FEq3, G4ConstRK4, G4DormandPrinceRK78, G4CashKarpRKF45, G4HelixExplicitEuler, G4RKG3_Stepper, and G4DormandPrinceRK56.
G4EquationOfMotion* G4MagIntegratorStepper::GetEquationOfMotion () inline
Referenced by G4MagInt_Driver::GetEquationOfMotion(), G4NystromRK4::GetField(), G4NystromRK4::SetDistanceForConstantField(), G4RKG3_Stepper::StepNoErr(), and G4RKG3_Stepper::Stepper().
const G4EquationOfMotion* G4MagIntegratorStepper::GetEquationOfMotion () const inline
unsigned long G4MagIntegratorStepper::GetfNoRHSCalls () inline
G4int G4MagIntegratorStepper::GetNumberOfStateVariables () const inline
Referenced by G4BogackiShampine45::G4BogackiShampine45(), G4CashKarpRKF45::G4CashKarpRKF45(), G4SimpleRunge::G4SimpleRunge(), G4TsitourasRK45::G4TsitourasRK45(), G4RK547FEq2::makeStep(), G4RK547FEq3::makeStep(), G4RK547FEq1::makeStep(), G4BogackiShampine23::makeStep(), G4MagErrorStepper::Stepper(), and G4ConstRK4::Stepper().
G4int G4MagIntegratorStepper::GetNumberOfVariables () const inline
Referenced by G4ExplicitEuler::DumbStepper(), G4ImplicitEuler::DumbStepper(), G4ClassicalRK4::DumbStepper(), G4BogackiShampine45::GetLastDydx(), G4TsitourasRK45::Interpolate(), G4DoLoMcPriRK34::Interpolate(), G4DormandPrince745::Interpolate4thOrder(), G4DormandPrince745::Interpolate5thOrder(), G4DormandPrinceRK56::Interpolate_high(), G4DormandPrinceRK56::Interpolate_low(), G4BogackiShampine45::InterpolateHigh(), G4RK547FEq3::makeStep(), G4RK547FEq1::makeStep(), G4RK547FEq2::makeStep(), G4BogackiShampine23::makeStep(), PHG4OuterHcalFieldSetup::PHG4OuterHcalFieldSetup(), G4BlineTracer::ResetChordFinders(), G4DormandPrinceRK56::SetupInterpolate_high(), G4DormandPrinceRK56::SetupInterpolate_low(), G4DormandPrince745::SetupInterpolation5thOrder(), G4BogackiShampine45::SetupInterpolationHigh(), G4DormandPrinceRK56::Stepper(), G4DormandPrince745::Stepper(), G4CashKarpRKF45::Stepper(), G4MagErrorStepper::Stepper(), G4DoLoMcPriRK34::Stepper(), G4TsitourasRK45::Stepper(), G4DormandPrinceRK78::Stepper(), G4BogackiShampine45::Stepper(), G4TBMagneticFieldSetup::UpdateField(), and F02ElectricFieldSetup::UpdateIntegrator().
G4int G4MagIntegratorStepper::IntegrationOrder () inline
virtual G4int G4MagIntegratorStepper::IntegratorOrder () const pure virtual
Implemented in G4HelixMixedStepper, G4BogackiShampine45, G4RKG3_Stepper, G4DoLoMcPriRK34, G4TsitourasRK45, G4ExactHelixStepper, G4DormandPrince745, G4BogackiShampine23, G4ConstRK4, G4ClassicalRK4, G4NystromRK4, G4RK547FEq1, G4RK547FEq2, G4RK547FEq3, G4DormandPrinceRK78, G4HelixExplicitEuler, G4CashKarpRKF45, G4SimpleRunge, G4DormandPrinceRK56, G4HelixImplicitEuler, G4SimpleHeum, G4HelixHeum, G4HelixSimpleRunge, G4ImplicitEuler, and G4ExplicitEuler.
Referenced by G4MagInt_Driver::G4MagInt_Driver(), and G4MagErrorStepper::Stepper().
G4bool G4MagIntegratorStepper::IsFSAL () const inline
void G4MagIntegratorStepper::NormalisePolarizationVector (G4double vec[12]) inline
Referenced by G4SimpleHeum::DumbStepper(), and G4ClassicalRK4::DumbStepper().
void G4MagIntegratorStepper::NormaliseTangentVector (G4double vec[6]) inline
G4MagIntegratorStepper& G4MagIntegratorStepper::operator= (const G4MagIntegratorStepper &) delete
void G4MagIntegratorStepper::ResetfNORHSCalls () inline
void G4MagIntegratorStepper::RightHandSide (const G4double y[], G4double dydx[]) const inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4SimpleHeum::DumbStepper(), G4ImplicitEuler::DumbStepper(), G4SimpleRunge::DumbStepper(), G4ClassicalRK4::DumbStepper(), G4MagInt_Driver::GetDerivatives(), G4RK547FEq1::makeStep(), G4RK547FEq2::makeStep(), G4RK547FEq3::makeStep(), G4BogackiShampine23::makeStep(), G4DormandPrinceRK56::SetupInterpolate_high(), G4DormandPrinceRK56::SetupInterpolate_low(), G4DormandPrince745::SetupInterpolation5thOrder(), G4BogackiShampine45::SetupInterpolationHigh(), G4DormandPrinceRK56::Stepper(), G4DormandPrince745::Stepper(), G4CashKarpRKF45::Stepper(), G4MagErrorStepper::Stepper(), G4DoLoMcPriRK34::Stepper(), G4TsitourasRK45::Stepper(), G4DormandPrinceRK78::Stepper(), and G4BogackiShampine45::Stepper().
void G4MagIntegratorStepper::RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const inline
void G4MagIntegratorStepper::SetEquationOfMotion (G4EquationOfMotion * newEquation) inline
Referenced by G4MagInt_Driver::SetEquationOfMotion().
void G4MagIntegratorStepper::SetFSAL (G4bool flag = true) inline protected
Referenced by G4BogackiShampine23::G4BogackiShampine23().
void G4MagIntegratorStepper::SetIntegrationOrder (G4int order) inline protected
Referenced by G4BogackiShampine23::G4BogackiShampine23().
virtual void G4MagIntegratorStepper::Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[]) pure virtual
Implemented in G4HelixMixedStepper, G4BogackiShampine45, G4ExactHelixStepper, G4MagHelicalStepper, G4NystromRK4, G4DormandPrinceRK78, G4BogackiShampine23, G4TsitourasRK45, G4ConstRK4, G4DoLoMcPriRK34, G4MagErrorStepper, G4CashKarpRKF45, G4DormandPrince745, G4DormandPrinceRK56, G4RK547FEq1, G4RK547FEq2, G4RK547FEq3, and G4RKG3_Stepper.
Referenced by G4HelixMixedStepper::Stepper().
Member Data Documentation
G4EquationOfMotion* G4MagIntegratorStepper::fEquation_Rhs = nullptr private
Definition at line 124 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 124 of file G4MagIntegratorStepper.hh
G4int G4MagIntegratorStepper::fIntegrationOrder = -1 private
Definition at line 134 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 134 of file G4MagIntegratorStepper.hh
G4bool G4MagIntegratorStepper::fIsFSAL = false private
Definition at line 136 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 136 of file G4MagIntegratorStepper.hh
const G4int G4MagIntegratorStepper::fNoIntegrationVariables = 0 private
Definition at line 125 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 125 of file G4MagIntegratorStepper.hh
unsigned long G4MagIntegratorStepper::fNoRHSCalls = 0UL mutable private
Definition at line 128 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 128 of file G4MagIntegratorStepper.hh
const G4int G4MagIntegratorStepper::fNoStateVariables = 0 private
Definition at line 126 of file G4MagIntegratorStepper.hh.
View newest version in sPHENIX GitHub at line 126 of file G4MagIntegratorStepper.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4MagIntegratorStepper.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4MagIntegratorStepper.cc