ECCE @ EIC Software: G4ProductionCutsTableMessenger Class Reference
G4ProductionCutsTableMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4ProductionCutsTableMessenger.hh>
Public Member Functions
G4ProductionCutsTableMessenger (G4ProductionCutsTable *pTable)
virtual ~G4ProductionCutsTableMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
virtual G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Attributes
G4ProductionCutsTable * theCutsTable
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Private Member Functions
G4ProductionCutsTableMessenger ()
Private Attributes
G4UIdirectory * theDirectory
G4UIcmdWithAnInteger * verboseCmd
G4UIcmdWithADoubleAndUnit * setLowEdgeCmd
G4UIcmdWithADoubleAndUnit * setHighEdgeCmd
G4UIcmdWithADoubleAndUnit * setMaxEnergyCutCmd
G4UIcmdWithoutParameter * dumpCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Detailed Description
Definition at line 64 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ProductionCutsTableMessenger.hh
Constructor & Destructor Documentation
G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger () inline private
Definition at line 68 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ProductionCutsTableMessenger.hh
G4ProductionCutsTableMessenger::G4ProductionCutsTableMessenger (G4ProductionCutsTable * pTable)
Definition at line 50 of file G4ProductionCutsTableMessenger.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ProductionCutsTableMessenger.cc
References G4UIcommand::AvailableForStates(), dumpCmd, G4State_PreInit, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), setHighEdgeCmd, setLowEdgeCmd, setMaxEnergyCutCmd, G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), theDirectory, and verboseCmd.
G4ProductionCutsTableMessenger::~G4ProductionCutsTableMessenger () virtual
Definition at line 101 of file G4ProductionCutsTableMessenger.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ProductionCutsTableMessenger.cc
References dumpCmd, setHighEdgeCmd, setLowEdgeCmd, setMaxEnergyCutCmd, theDirectory, and verboseCmd.
Member Function Documentation
G4String G4ProductionCutsTableMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 137 of file G4ProductionCutsTableMessenger.cc.
View newest version in sPHENIX GitHub at line 137 of file G4ProductionCutsTableMessenger.cc
References G4UIcommand::ConvertToString(), G4ProductionCutsTable::GetHighEdgeEnergy(), G4ProductionCutsTable::GetLowEdgeEnergy(), G4ProductionCutsTable::GetMaxEnergyCut(), G4ProductionCutsTable::GetVerboseLevel(), setHighEdgeCmd, setLowEdgeCmd, setMaxEnergyCutCmd, theCutsTable, and verboseCmd.
void G4ProductionCutsTableMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 111 of file G4ProductionCutsTableMessenger.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ProductionCutsTableMessenger.cc
References dumpCmd, G4ProductionCutsTable::GetHighEdgeEnergy(), G4ProductionCutsTable::GetLowEdgeEnergy(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ProductionCutsTable::SetEnergyRange(), setHighEdgeCmd, setLowEdgeCmd, G4ProductionCutsTable::SetMaxEnergyCut(), setMaxEnergyCutCmd, G4ProductionCutsTable::SetVerboseLevel(), theCutsTable, and verboseCmd.
Member Data Documentation
G4UIcmdWithoutParameter* G4ProductionCutsTableMessenger::dumpCmd private
Definition at line 87 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ProductionCutsTableMessenger.hh
Referenced by G4ProductionCutsTableMessenger(), SetNewValue(), and ~G4ProductionCutsTableMessenger().
G4UIcmdWithADoubleAndUnit* G4ProductionCutsTableMessenger::setHighEdgeCmd private
Definition at line 85 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ProductionCutsTableMessenger.hh
Referenced by G4ProductionCutsTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ProductionCutsTableMessenger().
G4UIcmdWithADoubleAndUnit* G4ProductionCutsTableMessenger::setLowEdgeCmd private
Definition at line 84 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ProductionCutsTableMessenger.hh
Referenced by G4ProductionCutsTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ProductionCutsTableMessenger().
G4UIcmdWithADoubleAndUnit* G4ProductionCutsTableMessenger::setMaxEnergyCutCmd private
Definition at line 86 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ProductionCutsTableMessenger.hh
Referenced by G4ProductionCutsTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ProductionCutsTableMessenger().
G4ProductionCutsTable* G4ProductionCutsTableMessenger::theCutsTable protected
Definition at line 79 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ProductionCutsTableMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIdirectory* G4ProductionCutsTableMessenger::theDirectory private
Definition at line 82 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ProductionCutsTableMessenger.hh
Referenced by G4ProductionCutsTableMessenger(), and ~G4ProductionCutsTableMessenger().
G4UIcmdWithAnInteger* G4ProductionCutsTableMessenger::verboseCmd private
Definition at line 83 of file G4ProductionCutsTableMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ProductionCutsTableMessenger.hh
Referenced by G4ProductionCutsTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ProductionCutsTableMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4ProductionCutsTableMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4ProductionCutsTableMessenger.cc