ECCE @ EIC Software: G4HadronPhysicsFTFQGSP_BERT Class Reference
G4HadronPhysicsFTFQGSP_BERT Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTFQGSP_BERT.hh>
Public Member Functions
G4HadronPhysicsFTFQGSP_BERT (G4int verbose=1)
G4HadronPhysicsFTFQGSP_BERT (const G4String &name, G4bool quasiElastic=false)
virtual ~G4HadronPhysicsFTFQGSP_BERT ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
void CreateModels ()
Private Attributes
G4NeutronRadCapture * theNeutronCaptureModel
G4PreCompoundModel * thePreEquilib
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QGSMFragmentation * theQGSMFragmentation
G4ExcitationHandler * theHandler
G4TheoFSGenerator * theModel1
G4TheoFSGenerator * theModel2
G4TheoFSGenerator * theModel3
G4CascadeInterface * theBertini1
G4CascadeInterface * theBertini2
G4HadronCaptureProcess * theNeutronCaptureProcess
G4NeutronInelasticProcess * theNeutronInelastic
G4ProtonInelasticProcess * theProtonInelastic
G4PionMinusInelasticProcess * thePionMinusInelastic
G4PionPlusInelasticProcess * thePionPlusInelastic
G4KaonMinusInelasticProcess * theKaonMinusInelastic
G4KaonPlusInelasticProcess * theKaonPlusInelastic
G4KaonZeroLInelasticProcess * theKaonZeroLInelastic
G4KaonZeroSInelasticProcess * theKaonZeroSInelastic
G4LambdaInelasticProcess * theLambdaInelastic
G4AntiLambdaInelasticProcess * theAntiLambdaInelastic
G4SigmaMinusInelasticProcess * theSigmaMinusInelastic
G4AntiSigmaMinusInelasticProcess * theAntiSigmaMinusInelastic
G4SigmaPlusInelasticProcess * theSigmaPlusInelastic
G4AntiSigmaPlusInelasticProcess * theAntiSigmaPlusInelastic
G4XiZeroInelasticProcess * theXiZeroInelastic
G4AntiXiZeroInelasticProcess * theAntiXiZeroInelastic
G4XiMinusInelasticProcess * theXiMinusInelastic
G4AntiXiMinusInelasticProcess * theAntiXiMinusInelastic
G4OmegaMinusInelasticProcess * theOmegaMinusInelastic
G4AntiOmegaMinusInelasticProcess * theAntiOmegaMinusInelastic
G4AntiProtonInelasticProcess * theAntiProtonInelastic
G4AntiNeutronInelasticProcess * theAntiNeutronInelastic
G4AntiDeuteronInelasticProcess * theAntiDeuteronInelastic
G4AntiTritonInelasticProcess * theAntiTritonInelastic
G4AntiHe3InelasticProcess * theAntiHe3Inelastic
G4AntiAlphaInelasticProcess * theAntiAlphaInelastic
G4VCrossSectionDataSet * thePiXS
G4VCrossSectionDataSet * theKaonAndHyperonXS
G4VCrossSectionDataSet * theAntiNucleonXS
G4VCrossSectionDataSet * theNeutronInelasticXS
G4VCrossSectionDataSet * theNeutronCaptureXS
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 91 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HadronPhysicsFTFQGSP_BERT.hh
Constructor & Destructor Documentation
G4HadronPhysicsFTFQGSP_BERT::G4HadronPhysicsFTFQGSP_BERT (G4int verbose = 1)
Definition at line 78 of file G4HadronPhysicsFTFQGSP_BERT.cc.
View newest version in sPHENIX GitHub at line 78 of file G4HadronPhysicsFTFQGSP_BERT.cc
G4HadronPhysicsFTFQGSP_BERT::G4HadronPhysicsFTFQGSP_BERT (const G4String & name, G4bool quasiElastic = false)
Definition at line 127 of file G4HadronPhysicsFTFQGSP_BERT.cc.
View newest version in sPHENIX GitHub at line 127 of file G4HadronPhysicsFTFQGSP_BERT.cc
G4HadronPhysicsFTFQGSP_BERT::~G4HadronPhysicsFTFQGSP_BERT () virtual
Definition at line 235 of file G4HadronPhysicsFTFQGSP_BERT.cc.
View newest version in sPHENIX GitHub at line 235 of file G4HadronPhysicsFTFQGSP_BERT.cc
References theCascade, thePreEquilib, theQGSMFragmentation, theStringDecay, and theStringModel.
Member Function Documentation
void G4HadronPhysicsFTFQGSP_BERT::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 245 of file G4HadronPhysicsFTFQGSP_BERT.cc.
View newest version in sPHENIX GitHub at line 245 of file G4HadronPhysicsFTFQGSP_BERT.cc
References G4MesonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsFTFQGSP_BERT::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 259 of file G4HadronPhysicsFTFQGSP_BERT.cc.
View newest version in sPHENIX GitHub at line 259 of file G4HadronPhysicsFTFQGSP_BERT.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), G4AntiAlpha::AntiAlpha(), G4AntiDeuteron::AntiDeuteron(), G4AntiHe3::AntiHe3(), G4AntiLambda::AntiLambda(), G4AntiNeutron::AntiNeutron(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiTriton::AntiTriton(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), CreateModels(), G4ParticleDefinition::GetProcessManager(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), G4Lambda::Lambda(), G4Neutron::Neutron(), G4OmegaMinus::OmegaMinus(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), theAntiAlphaInelastic, theAntiDeuteronInelastic, theAntiHe3Inelastic, theAntiLambdaInelastic, theAntiNeutronInelastic, theAntiNucleonXS, theAntiOmegaMinusInelastic, theAntiProtonInelastic, theAntiSigmaMinusInelastic, theAntiSigmaPlusInelastic, theAntiTritonInelastic, theAntiXiMinusInelastic, theAntiXiZeroInelastic, theBertini1, theBertini2, theKaonAndHyperonXS, theKaonMinusInelastic, theKaonPlusInelastic, theKaonZeroLInelastic, theKaonZeroSInelastic, theLambdaInelastic, theModel1, theModel2, theModel3, theNeutronCaptureModel, theNeutronCaptureProcess, theNeutronInelastic, theNeutronInelasticXS, theOmegaMinusInelastic, thePionMinusInelastic, thePionPlusInelastic, thePiXS, theProtonInelastic, theSigmaMinusInelastic, theSigmaPlusInelastic, theXiMinusInelastic, theXiZeroInelastic, G4XiMinus::XiMinus(), and G4XiZero::XiZero().
void G4HadronPhysicsFTFQGSP_BERT::CreateModels () private
Definition at line 176 of file G4HadronPhysicsFTFQGSP_BERT.cc.
View newest version in sPHENIX GitHub at line 176 of file G4HadronPhysicsFTFQGSP_BERT.cc
References G4NeutronInelasticXS::Default_Name(), G4NeutronCaptureXS::Default_Name(), G4PionMinus::Definition(), G4cout, G4endl, G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4CrossSectionDataSetRegistry::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), theAntiNucleonXS, theBertini1, theBertini2, theCascade, theHandler, theKaonAndHyperonXS, theModel1, theModel2, theModel3, theNeutronCaptureModel, theNeutronCaptureXS, theNeutronInelasticXS, thePiXS, thePreEquilib, theQGSMFragmentation, theStringDecay, and theStringModel.
Referenced by ConstructProcess().
Member Data Documentation
G4AntiAlphaInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiAlphaInelastic private
Definition at line 149 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 149 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiDeuteronInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiDeuteronInelastic private
Definition at line 146 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 146 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiHe3InelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiHe3Inelastic private
Definition at line 148 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 148 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiLambdaInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiLambdaInelastic private
Definition at line 132 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 132 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiNeutronInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiNeutronInelastic private
Definition at line 145 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 145 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4VCrossSectionDataSet* G4HadronPhysicsFTFQGSP_BERT::theAntiNucleonXS private
Definition at line 153 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 153 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4AntiOmegaMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiOmegaMinusInelastic private
Definition at line 142 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 142 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiProtonInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiProtonInelastic private
Definition at line 144 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 144 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiSigmaMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiSigmaMinusInelastic private
Definition at line 134 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 134 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiSigmaPlusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiSigmaPlusInelastic private
Definition at line 136 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 136 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiTritonInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiTritonInelastic private
Definition at line 147 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 147 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiXiMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiXiMinusInelastic private
Definition at line 140 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 140 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4AntiXiZeroInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theAntiXiZeroInelastic private
Definition at line 138 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 138 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4CascadeInterface* G4HadronPhysicsFTFQGSP_BERT::theBertini1 private
Definition at line 117 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 117 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4CascadeInterface* G4HadronPhysicsFTFQGSP_BERT::theBertini2 private
Definition at line 118 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 118 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4GeneratorPrecompoundInterface* G4HadronPhysicsFTFQGSP_BERT::theCascade private
Definition at line 108 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 108 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels(), and ~G4HadronPhysicsFTFQGSP_BERT().
G4ExcitationHandler* G4HadronPhysicsFTFQGSP_BERT::theHandler private
Definition at line 112 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 112 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels().
G4VCrossSectionDataSet* G4HadronPhysicsFTFQGSP_BERT::theKaonAndHyperonXS private
Definition at line 152 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 152 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4KaonMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theKaonMinusInelastic private
Definition at line 126 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 126 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4KaonPlusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theKaonPlusInelastic private
Definition at line 127 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 127 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4KaonZeroLInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theKaonZeroLInelastic private
Definition at line 128 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 128 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4KaonZeroSInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theKaonZeroSInelastic private
Definition at line 129 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 129 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4LambdaInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theLambdaInelastic private
Definition at line 131 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 131 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4TheoFSGenerator* G4HadronPhysicsFTFQGSP_BERT::theModel1 private
Definition at line 114 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 114 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4TheoFSGenerator* G4HadronPhysicsFTFQGSP_BERT::theModel2 private
Definition at line 115 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 115 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4TheoFSGenerator* G4HadronPhysicsFTFQGSP_BERT::theModel3 private
Definition at line 116 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 116 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4NeutronRadCapture* G4HadronPhysicsFTFQGSP_BERT::theNeutronCaptureModel private
Definition at line 105 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 105 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4HadronCaptureProcess* G4HadronPhysicsFTFQGSP_BERT::theNeutronCaptureProcess private
Definition at line 120 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 120 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4VCrossSectionDataSet* G4HadronPhysicsFTFQGSP_BERT::theNeutronCaptureXS private
Definition at line 155 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 155 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels().
G4NeutronInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theNeutronInelastic private
Definition at line 122 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 122 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4VCrossSectionDataSet* G4HadronPhysicsFTFQGSP_BERT::theNeutronInelasticXS private
Definition at line 154 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 154 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4OmegaMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theOmegaMinusInelastic private
Definition at line 141 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 141 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4PionMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::thePionMinusInelastic private
Definition at line 124 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 124 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4PionPlusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::thePionPlusInelastic private
Definition at line 125 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 125 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4VCrossSectionDataSet* G4HadronPhysicsFTFQGSP_BERT::thePiXS private
Definition at line 151 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 151 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess(), and CreateModels().
G4PreCompoundModel* G4HadronPhysicsFTFQGSP_BERT::thePreEquilib private
Definition at line 107 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 107 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels(), and ~G4HadronPhysicsFTFQGSP_BERT().
G4ProtonInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theProtonInelastic private
Definition at line 123 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 123 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4QGSMFragmentation* G4HadronPhysicsFTFQGSP_BERT::theQGSMFragmentation private
Definition at line 111 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 111 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels(), and ~G4HadronPhysicsFTFQGSP_BERT().
G4SigmaMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theSigmaMinusInelastic private
Definition at line 133 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 133 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4SigmaPlusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theSigmaPlusInelastic private
Definition at line 135 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 135 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4ExcitedStringDecay* G4HadronPhysicsFTFQGSP_BERT::theStringDecay private
Definition at line 110 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 110 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels(), and ~G4HadronPhysicsFTFQGSP_BERT().
G4FTFModel* G4HadronPhysicsFTFQGSP_BERT::theStringModel private
Definition at line 109 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 109 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by CreateModels(), and ~G4HadronPhysicsFTFQGSP_BERT().
G4XiMinusInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theXiMinusInelastic private
Definition at line 139 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 139 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
G4XiZeroInelasticProcess* G4HadronPhysicsFTFQGSP_BERT::theXiZeroInelastic private
Definition at line 137 of file G4HadronPhysicsFTFQGSP_BERT.hh.
View newest version in sPHENIX GitHub at line 137 of file G4HadronPhysicsFTFQGSP_BERT.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTFQGSP_BERT.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsFTFQGSP_BERT.cc