ECCE @ EIC Software: CML2Ph_FullWater Class Reference
CML2Ph_FullWater Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Ph_FullWater.hh>
Public Member Functions
CML2Ph_FullWater ()
~CML2Ph_FullWater (void)
bool Construct (G4VPhysicalVolume *PVWorld, G4int voxelX, G4int voxelY, G4int voxelZ)
G4VPhysicalVolume * getPhysicalVolume ()
G4ThreeVector getHalfContainerSize ()
void writeInfo ()
Private Attributes
CML2Ph_FullWaterMessenger * fullWaterMessenger
G4VPhysicalVolume * PVWorld
G4VPhysicalVolume * fullWaterPhantomPV
G4ThreeVector centre
G4ThreeVector halfSize
G4ThreeVector fPhantomSize
Detailed Description
Definition at line 63 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 63 of file ML2Ph_FullWater.hh
Constructor & Destructor Documentation
CML2Ph_FullWater::CML2Ph_FullWater ()
Definition at line 53 of file ML2Ph_FullWater.cc.
View newest version in sPHENIX GitHub at line 53 of file ML2Ph_FullWater.cc
References centre, fPhantomSize, fullWaterMessenger, halfSize, mm, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
CML2Ph_FullWater::~CML2Ph_FullWater (void)
Definition at line 66 of file ML2Ph_FullWater.cc.
View newest version in sPHENIX GitHub at line 66 of file ML2Ph_FullWater.cc
Member Function Documentation
bool CML2Ph_FullWater::Construct (G4VPhysicalVolume * PVWorld, G4int voxelX, G4int voxelY, G4int voxelZ)
Definition at line 75 of file ML2Ph_FullWater.cc.
View newest version in sPHENIX GitHub at line 75 of file ML2Ph_FullWater.cc
References G4SDManager::AddNewDetector(), G4Region::AddRootLogicalVolume(), centre, G4NistManager::FindOrBuildMaterial(), fPhantomSize, fullWaterPhantomPV, G4cout, G4endl, G4SDManager::GetSDMpointer(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), halfSize, G4NistManager::Instance(), kXAxis, kYAxis, kZAxis, mm, PVWorld, G4Colour::Red(), G4MultiFunctionalDetector::RegisterPrimitive(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetSensitiveDetector(), G4VisAttributes::SetVisibility(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CML2PhantomConstruction::Construct().
G4ThreeVector CML2Ph_FullWater::getHalfContainerSize () inline
Definition at line 72 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 72 of file ML2Ph_FullWater.hh
References halfSize.
Referenced by CML2PhantomConstruction::design().
G4VPhysicalVolume* CML2Ph_FullWater::getPhysicalVolume () inline
Definition at line 71 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 71 of file ML2Ph_FullWater.hh
References PVWorld.
Referenced by CML2PhantomConstruction::Construct().
void CML2Ph_FullWater::writeInfo ()
Definition at line 70 of file ML2Ph_FullWater.cc.
View newest version in sPHENIX GitHub at line 70 of file ML2Ph_FullWater.cc
References centre, G4cout, G4endl, halfSize, and mm.
Referenced by CML2PhantomConstruction::Construct().
Member Data Documentation
G4ThreeVector CML2Ph_FullWater::centre private
Definition at line 87 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 87 of file ML2Ph_FullWater.hh
Referenced by CML2Ph_FullWater(), Construct(), and writeInfo().
G4ThreeVector CML2Ph_FullWater::fPhantomSize private
Definition at line 88 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 88 of file ML2Ph_FullWater.hh
Referenced by CML2Ph_FullWater(), and Construct().
CML2Ph_FullWaterMessenger* CML2Ph_FullWater::fullWaterMessenger private
Definition at line 82 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 82 of file ML2Ph_FullWater.hh
Referenced by CML2Ph_FullWater().
G4VPhysicalVolume* CML2Ph_FullWater::fullWaterPhantomPV private
Definition at line 85 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 85 of file ML2Ph_FullWater.hh
Referenced by Construct().
G4ThreeVector CML2Ph_FullWater::halfSize private
Definition at line 87 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 87 of file ML2Ph_FullWater.hh
Referenced by CML2Ph_FullWater(), Construct(), getHalfContainerSize(), and writeInfo().
G4VPhysicalVolume* CML2Ph_FullWater::PVWorld private
Definition at line 84 of file ML2Ph_FullWater.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2Ph_FullWater.hh
Referenced by Construct(), and getPhysicalVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Ph_FullWater.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Ph_FullWater.cc