ECCE @ EIC Software: XrayFluoAnalysisManager Class Reference
XrayFluoAnalysisManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoAnalysisManager.hh>
Public Member Functions
virtual ~XrayFluoAnalysisManager ()
void book ()
void finish ()
void analyseStepping (const G4Step *aStep)
void analyseEnergyDep (G4double eDep)
void analysePrimaryGenerator (G4double energy)
void PhaseSpaceOn ()
void PhaseSpaceOff ()
void SetOutputFileName (G4String)
const std::pair< G4double,
G4String > GetEmittedParticleEnergyAndType ()
void LoadGunData (G4String, G4bool)
void SetPhysicFlag (G4bool)
Static Public Member Functions
static XrayFluoAnalysisManager * getInstance ()
Private Member Functions
XrayFluoAnalysisManager ()
Private Attributes
G4String outputFileName
G4bool phaseSpaceFlag
G4bool physicFlag
std::vector< G4double > * gunParticleEnergies
std::vector< G4String > * gunParticleTypes
XrayFluoAnalysisMessenger * analisysMessenger
G4bool dataLoaded
G4int fParticleEnergyAndTypeIndex
Static Private Attributes
static XrayFluoAnalysisManager * instance = 0
Detailed Description
Definition at line 53 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 53 of file XrayFluoAnalysisManager.hh
Constructor & Destructor Documentation
XrayFluoAnalysisManager::~XrayFluoAnalysisManager () virtual
Definition at line 86 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoAnalysisManager.cc
References gunParticleEnergies, gunParticleTypes, G4ToolsAnalysisManager::Instance(), and instance.
XrayFluoAnalysisManager::XrayFluoAnalysisManager () private
Definition at line 68 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 68 of file XrayFluoAnalysisManager.cc
References analisysMessenger, dataLoaded, fParticleEnergyAndTypeIndex, G4cout, G4endl, and G4ToolsAnalysisManager::Instance().
Referenced by getInstance().
Member Function Documentation
void XrayFluoAnalysisManager::analyseEnergyDep (G4double eDep)
Definition at line 428 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 428 of file XrayFluoAnalysisManager.cc
References G4VAnalysisManager::FillH1(), G4ToolsAnalysisManager::Instance(), keV, and phaseSpaceFlag.
Referenced by XrayFluoEventAction::EndOfEventAction().
void XrayFluoAnalysisManager::analysePrimaryGenerator (G4double energy)
Definition at line 441 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 441 of file XrayFluoAnalysisManager.cc
References G4VAnalysisManager::FillH1(), G4ToolsAnalysisManager::Instance(), keV, and phaseSpaceFlag.
Referenced by XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction::GeneratePrimaries().
void XrayFluoAnalysisManager::analyseStepping (const G4Step * aStep)
Definition at line 241 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 241 of file XrayFluoAnalysisManager.cc
References G4VAnalysisManager::AddNtupleRow(), G4Electron::Definition(), G4Proton::Definition(), G4Gamma::Definition(), G4VSolid::DistanceToOut(), fGeomBoundary, G4VAnalysisManager::FillH1(), G4VAnalysisManager::FillNtupleDColumn(), G4VAnalysisManager::FillNtupleIColumn(), G4Track::GetCreatorProcess(), G4Track::GetCurrentStepNumber(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), XrayFluoDetectorConstruction::GetGeometryNavigator(), XrayFluoDetectorConstruction::GetInstance(), G4StepPoint::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMaterial(), G4DynamicParticle::GetMomentum(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4Track::GetNextVolume(), G4Track::GetParentID(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VProcess::GetProcessName(), G4LogicalVolume::GetSolid(), G4StepPoint::GetStepStatus(), G4Step::GetTrack(), G4Track::GetVertexPosition(), G4Track::GetVolume(), G4ToolsAnalysisManager::Instance(), keV, G4Navigator::LocateGlobalPointAndSetup(), momentum, part, phaseSpaceFlag, CLHEP::Hep3Vector::phi(), physicFlag, and CLHEP::Hep3Vector::theta().
Referenced by XrayFluoSteppingAction::UserSteppingAction().
void XrayFluoAnalysisManager::book ()
Definition at line 111 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 111 of file XrayFluoAnalysisManager.cc
References G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4VAnalysisManager::FinishNtuple(), G4cout, G4endl, G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), outputFileName, phaseSpaceFlag, G4VAnalysisManager::SetFirstHistoId(), G4VAnalysisManager::SetFirstNtupleId(), and G4VAnalysisManager::SetVerboseLevel().
Referenced by XrayFluoRunAction::BeginOfRunAction().
void XrayFluoAnalysisManager::finish ()
Definition at line 221 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 221 of file XrayFluoAnalysisManager.cc
References G4VAnalysisManager::CloseFile(), G4cout, G4endl, G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
Referenced by XrayFluoRunAction::EndOfRunAction().
const std::pair< G4double, G4String > XrayFluoAnalysisManager::GetEmittedParticleEnergyAndType ()
Definition at line 201 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 201 of file XrayFluoAnalysisManager.cc
References energy, fParticleEnergyAndTypeIndex, gunParticleEnergies, and gunParticleTypes.
Referenced by XrayFluoPrimaryGeneratorAction::GeneratePrimaries().
XrayFluoAnalysisManager * XrayFluoAnalysisManager::getInstance () static
Definition at line 101 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 101 of file XrayFluoAnalysisManager.cc
References instance, and XrayFluoAnalysisManager().
Referenced by XrayFluoPrimaryGeneratorAction::ActivatePhaseSpace(), XrayFluoRunAction::BeginOfRunAction(), XrayFluoEventAction::EndOfEventAction(), XrayFluoRunAction::EndOfRunAction(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoSimulation::RunSimulation(), and XrayFluoSteppingAction::UserSteppingAction().
void XrayFluoAnalysisManager::LoadGunData (G4String fileName, G4bool raileighFlag)
Definition at line 156 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 156 of file XrayFluoAnalysisManager.cc
References dataLoaded, energy, G4cout, G4endl, G4RootAnalysisReader::GetNtuple(), G4VAnalysisReader::GetNtupleRow(), gunParticleEnergies, gunParticleTypes, MeV, G4VAnalysisReader::SetNtupleDColumn(), G4VAnalysisReader::SetNtupleIColumn(), and G4VAnalysisReader::SetVerboseLevel().
Referenced by XrayFluoPrimaryGeneratorAction::ActivatePhaseSpace().
void XrayFluoAnalysisManager::PhaseSpaceOff () inline
Definition at line 78 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 78 of file XrayFluoAnalysisManager.hh
References phaseSpaceFlag.
void XrayFluoAnalysisManager::PhaseSpaceOn () inline
Definition at line 76 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 76 of file XrayFluoAnalysisManager.hh
References phaseSpaceFlag.
Referenced by XrayFluoSimulation::RunSimulation().
void XrayFluoAnalysisManager::SetOutputFileName (G4String newName)
Definition at line 453 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 453 of file XrayFluoAnalysisManager.cc
References outputFileName.
Referenced by XrayFluoAnalysisMessenger::SetNewValue().
void XrayFluoAnalysisManager::SetPhysicFlag (G4bool val)
Definition at line 234 of file XrayFluoAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 234 of file XrayFluoAnalysisManager.cc
References physicFlag.
Referenced by XrayFluoAnalysisMessenger::SetNewValue().
Member Data Documentation
XrayFluoAnalysisMessenger* XrayFluoAnalysisManager::analisysMessenger private
Definition at line 106 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 106 of file XrayFluoAnalysisManager.hh
Referenced by XrayFluoAnalysisManager().
G4bool XrayFluoAnalysisManager::dataLoaded private
Definition at line 108 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 108 of file XrayFluoAnalysisManager.hh
Referenced by LoadGunData(), and XrayFluoAnalysisManager().
G4int XrayFluoAnalysisManager::fParticleEnergyAndTypeIndex private
Definition at line 110 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 110 of file XrayFluoAnalysisManager.hh
Referenced by GetEmittedParticleEnergyAndType(), and XrayFluoAnalysisManager().
std::vector<G4double>* XrayFluoAnalysisManager::gunParticleEnergies private
Definition at line 99 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 99 of file XrayFluoAnalysisManager.hh
Referenced by GetEmittedParticleEnergyAndType(), LoadGunData(), and ~XrayFluoAnalysisManager().
std::vector<G4String>* XrayFluoAnalysisManager::gunParticleTypes private
Definition at line 100 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 100 of file XrayFluoAnalysisManager.hh
Referenced by GetEmittedParticleEnergyAndType(), LoadGunData(), and ~XrayFluoAnalysisManager().
XrayFluoAnalysisManager * XrayFluoAnalysisManager::instance = 0 static private
Definition at line 103 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 103 of file XrayFluoAnalysisManager.hh
Referenced by getInstance(), and ~XrayFluoAnalysisManager().
G4String XrayFluoAnalysisManager::outputFileName private
Definition at line 93 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 93 of file XrayFluoAnalysisManager.hh
Referenced by book(), and SetOutputFileName().
G4bool XrayFluoAnalysisManager::phaseSpaceFlag private
Definition at line 95 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 95 of file XrayFluoAnalysisManager.hh
Referenced by analyseEnergyDep(), analysePrimaryGenerator(), analyseStepping(), book(), PhaseSpaceOff(), and PhaseSpaceOn().
G4bool XrayFluoAnalysisManager::physicFlag private
Definition at line 97 of file XrayFluoAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 97 of file XrayFluoAnalysisManager.hh
Referenced by analyseStepping(), and SetPhysicFlag().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoAnalysisManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoAnalysisManager.cc