ECCE @ EIC Software: G4HadSecondary Class Reference
G4HadSecondary Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadSecondary.hh>
Public Member Functions
G4HadSecondary (G4DynamicParticle *aT, G4double aWeight=1, G4int mod=-1)
~G4HadSecondary ()
G4DynamicParticle * GetParticle ()
const G4DynamicParticle * GetParticle () const
G4double GetWeight () const
void SetWeight (G4double aW)
void SetTime (G4double aT)
G4double GetTime () const
void SetCreatorModelType (G4int idx)
G4int GetCreatorModelType () const
Private Member Functions
G4HadSecondary ()
Private Attributes
G4DynamicParticle * theP
G4double theWeight
G4double theTime
G4int theCreatorModel
Detailed Description
Definition at line 35 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 35 of file G4HadSecondary.hh
Constructor & Destructor Documentation
G4HadSecondary::G4HadSecondary (G4DynamicParticle * aT, G4double aWeight = 1, G4int mod = -1)
Definition at line 30 of file G4HadSecondary.cc.
View newest version in sPHENIX GitHub at line 30 of file G4HadSecondary.cc
References G4DynamicParticle::GetKineticEnergy().
G4HadSecondary::~G4HadSecondary ()
Definition at line 41 of file G4HadSecondary.cc.
View newest version in sPHENIX GitHub at line 41 of file G4HadSecondary.cc
G4HadSecondary::G4HadSecondary () inline private
Definition at line 53 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 53 of file G4HadSecondary.hh
Member Function Documentation
G4int G4HadSecondary::GetCreatorModelType () const inline
Definition at line 49 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HadSecondary.hh
References theCreatorModel.
Referenced by G4MuonicAtomDecay::FillResult(), and G4HadronicProcess::FillResult().
G4DynamicParticle* G4HadSecondary::GetParticle () inline
Definition at line 42 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 42 of file G4HadSecondary.hh
References theP.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPCaptureFS::ApplyYourself(), G4LFission::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4HadLeadBias::Bias(), G4HadronicProcess::CheckResult(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
const G4DynamicParticle* G4HadSecondary::GetParticle () const inline
Definition at line 43 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 43 of file G4HadSecondary.hh
References theP.
G4double G4HadSecondary::GetTime () const inline
Definition at line 47 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 47 of file G4HadSecondary.hh
References theTime.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4MuonicAtomDecay::DecayIt(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), and CexmcHadronicProcess::FillTotalResult().
G4double G4HadSecondary::GetWeight () const inline
Definition at line 44 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 44 of file G4HadSecondary.hh
References theWeight.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4HadLeadBias::Bias(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), and CexmcHadronicProcess::FillTotalResult().
void G4HadSecondary::SetCreatorModelType (G4int idx) inline
Definition at line 48 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 48 of file G4HadSecondary.hh
References incremental_prev_tag::idx, and theCreatorModel.
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), and G4NeutronRadCapture::ApplyYourself().
void G4HadSecondary::SetTime (G4double aT) inline
Definition at line 46 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 46 of file G4HadSecondary.hh
References theTime.
Referenced by G4MuMinusCapturePrecompound::AddNewParticle(), G4EmCaptureCascade::AddNewParticle(), G4MuonMinusBoundDecay::AddNewParticle(), G4BinaryLightIonReaction::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), and G4MuonicAtomDecay::DecayIt().
void G4HadSecondary::SetWeight (G4double aW) inline
Definition at line 45 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 45 of file G4HadSecondary.hh
References theWeight.
Member Data Documentation
G4int G4HadSecondary::theCreatorModel private
Definition at line 58 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 58 of file G4HadSecondary.hh
Referenced by GetCreatorModelType(), and SetCreatorModelType().
G4DynamicParticle* G4HadSecondary::theP private
Definition at line 53 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 53 of file G4HadSecondary.hh
Referenced by GetParticle().
G4double G4HadSecondary::theTime private
Definition at line 57 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 57 of file G4HadSecondary.hh
Referenced by GetTime(), and SetTime().
G4double G4HadSecondary::theWeight private
Definition at line 56 of file G4HadSecondary.hh.
View newest version in sPHENIX GitHub at line 56 of file G4HadSecondary.hh
Referenced by GetWeight(), and SetWeight().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4HadSecondary.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4HadSecondary.cc