ECCE @ EIC Software: G4MultiBodyMomentumDist Class Reference
G4MultiBodyMomentumDist Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4MultiBodyMomentumDist.hh>
Public Member Functions
~G4MultiBodyMomentumDist ()
Static Public Member Functions
static const
G4MultiBodyMomentumDist * GetInstance ()
static const G4VMultiBodyMomDst * GetDist (G4int is, G4int mult)
static void setVerboseLevel (G4int vb=0)
Private Member Functions
G4MultiBodyMomentumDist ()
const G4VMultiBodyMomDst * ChooseDist (G4int is, G4int mult) const
void passVerbose (G4int verbose)
G4MultiBodyMomentumDist (const G4MultiBodyMomentumDist &)
G4MultiBodyMomentumDist & operator= (const G4MultiBodyMomentumDist &)
Private Attributes
G4NuclNucl3BodyMomDst * nn3BodyDst
G4NuclNucl4BodyMomDst * nn4BodyDst
G4HadNucl3BodyMomDst * hn3BodyDst
G4HadNucl4BodyMomDst * hn4BodyDst
Static Private Attributes
static G4ThreadLocal
G4MultiBodyMomentumDist * theInstance = 0
Detailed Description
Definition at line 49 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 49 of file G4MultiBodyMomentumDist.hh
Constructor & Destructor Documentation
G4MultiBodyMomentumDist::~G4MultiBodyMomentumDist ()
Definition at line 68 of file G4MultiBodyMomentumDist.cc.
View newest version in sPHENIX GitHub at line 68 of file G4MultiBodyMomentumDist.cc
References hn3BodyDst, hn4BodyDst, nn3BodyDst, and nn4BodyDst.
G4MultiBodyMomentumDist::G4MultiBodyMomentumDist () private
Definition at line 62 of file G4MultiBodyMomentumDist.cc.
View newest version in sPHENIX GitHub at line 62 of file G4MultiBodyMomentumDist.cc
G4MultiBodyMomentumDist::G4MultiBodyMomentumDist (const G4MultiBodyMomentumDist &) private
Member Function Documentation
const G4VMultiBodyMomDst * G4MultiBodyMomentumDist::ChooseDist (G4int is, G4int mult) const private
Definition at line 93 of file G4MultiBodyMomentumDist.cc.
View newest version in sPHENIX GitHub at line 93 of file G4MultiBodyMomentumDist.cc
References hn3BodyDst, hn4BodyDst, G4InuclParticleNames::neu, nn3BodyDst, nn4BodyDst, G4InuclParticleNames::pro, and G4CascadeParameters::use3BodyMom().
Referenced by GetDist().
static const G4VMultiBodyMomDst* G4MultiBodyMomentumDist::GetDist (G4int is, G4int mult) inline static
Definition at line 56 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 56 of file G4MultiBodyMomentumDist.hh
References ChooseDist(), and GetInstance().
Referenced by G4CascadeFinalStateAlgorithm::ChooseGenerators().
const G4MultiBodyMomentumDist * G4MultiBodyMomentumDist::GetInstance (void) static
Definition at line 51 of file G4MultiBodyMomentumDist.cc.
View newest version in sPHENIX GitHub at line 51 of file G4MultiBodyMomentumDist.cc
References G4AutoDelete::Register().
Referenced by GetDist(), and setVerboseLevel().
G4MultiBodyMomentumDist& G4MultiBodyMomentumDist::operator= (const G4MultiBodyMomentumDist &) private
void G4MultiBodyMomentumDist::passVerbose (G4int verbose) private
Definition at line 82 of file G4MultiBodyMomentumDist.cc.
View newest version in sPHENIX GitHub at line 82 of file G4MultiBodyMomentumDist.cc
References hn3BodyDst, hn4BodyDst, nn3BodyDst, nn4BodyDst, and G4VMultiBodyMomDst::setVerboseLevel().
Referenced by setVerboseLevel().
void G4MultiBodyMomentumDist::setVerboseLevel (G4int vb = 0) static
Definition at line 78 of file G4MultiBodyMomentumDist.cc.
View newest version in sPHENIX GitHub at line 78 of file G4MultiBodyMomentumDist.cc
References GetInstance(), and passVerbose().
Referenced by G4CascadeFinalStateAlgorithm::SetVerboseLevel().
Member Data Documentation
G4HadNucl3BodyMomDst* G4MultiBodyMomentumDist::hn3BodyDst private
Definition at line 75 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 75 of file G4MultiBodyMomentumDist.hh
Referenced by ChooseDist(), passVerbose(), and ~G4MultiBodyMomentumDist().
G4HadNucl4BodyMomDst* G4MultiBodyMomentumDist::hn4BodyDst private
Definition at line 76 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MultiBodyMomentumDist.hh
Referenced by ChooseDist(), passVerbose(), and ~G4MultiBodyMomentumDist().
G4NuclNucl3BodyMomDst* G4MultiBodyMomentumDist::nn3BodyDst private
Definition at line 73 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 73 of file G4MultiBodyMomentumDist.hh
Referenced by ChooseDist(), passVerbose(), and ~G4MultiBodyMomentumDist().
G4NuclNucl4BodyMomDst* G4MultiBodyMomentumDist::nn4BodyDst private
Definition at line 74 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 74 of file G4MultiBodyMomentumDist.hh
Referenced by ChooseDist(), passVerbose(), and ~G4MultiBodyMomentumDist().
G4ThreadLocal G4MultiBodyMomentumDist * G4MultiBodyMomentumDist::theInstance = 0 static private
Definition at line 70 of file G4MultiBodyMomentumDist.hh.
View newest version in sPHENIX GitHub at line 70 of file G4MultiBodyMomentumDist.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4MultiBodyMomentumDist.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4MultiBodyMomentumDist.cc