ECCE @ EIC Software: G4FTFPPiKBuilder Class Reference
G4FTFPPiKBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPPiKBuilder.hh>
Public Member Functions
G4FTFPPiKBuilder (G4bool quasiElastic=false)
virtual ~G4FTFPPiKBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPiKBuilder
G4VPiKBuilder ()=default
virtual ~G4VPiKBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4LundStringFragmentation * theLund
G4double theMin
G4double theMax
Detailed Description
Definition at line 58 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4FTFPPiKBuilder.hh
Constructor & Destructor Documentation
G4FTFPPiKBuilder::G4FTFPPiKBuilder (G4bool quasiElastic = false)
Definition at line 51 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 51 of file G4FTFPPiKBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theLund, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFPPiKBuilder::~G4FTFPPiKBuilder () virtual
Definition at line 76 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FTFPPiKBuilder.cc
References theLund, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4FTFPPiKBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 65 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4FTFPPiKBuilder.hh
void G4FTFPPiKBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 85 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 85 of file G4FTFPPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPPiKBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 94 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 94 of file G4FTFPPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPPiKBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 103 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 103 of file G4FTFPPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPPiKBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 111 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 111 of file G4FTFPPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPPiKBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 119 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 119 of file G4FTFPPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPPiKBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 127 of file G4FTFPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 127 of file G4FTFPPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4FTFPPiKBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 74 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FTFPPiKBuilder.hh
References theMax.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
virtual void G4FTFPPiKBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 73 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFPPiKBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4FTFPPiKBuilder::theCascade private
Definition at line 80 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FTFPPiKBuilder.hh
Referenced by G4FTFPPiKBuilder().
G4LundStringFragmentation* G4FTFPPiKBuilder::theLund private
Definition at line 84 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 84 of file G4FTFPPiKBuilder.hh
Referenced by G4FTFPPiKBuilder(), and ~G4FTFPPiKBuilder().
G4double G4FTFPPiKBuilder::theMax private
Definition at line 86 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4FTFPPiKBuilder.hh
Referenced by Build(), G4FTFPPiKBuilder(), and SetMaxEnergy().
G4double G4FTFPPiKBuilder::theMin private
Definition at line 85 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4FTFPPiKBuilder.hh
Referenced by Build(), G4FTFPPiKBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFPPiKBuilder::theModel private
Definition at line 79 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFPPiKBuilder.hh
Referenced by Build(), and G4FTFPPiKBuilder().
G4QuasiElasticChannel* G4FTFPPiKBuilder::theQuasiElastic private
Definition at line 83 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FTFPPiKBuilder.hh
Referenced by G4FTFPPiKBuilder(), and ~G4FTFPPiKBuilder().
G4ExcitedStringDecay* G4FTFPPiKBuilder::theStringDecay private
Definition at line 82 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4FTFPPiKBuilder.hh
Referenced by G4FTFPPiKBuilder(), and ~G4FTFPPiKBuilder().
G4FTFModel* G4FTFPPiKBuilder::theStringModel private
Definition at line 81 of file G4FTFPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FTFPPiKBuilder.hh
Referenced by G4FTFPPiKBuilder(), and ~G4FTFPPiKBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPPiKBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFPPiKBuilder.cc