ECCE @ EIC Software: G4BlinePrimaryGeneratorAction Class Reference
G4BlinePrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlinePrimaryGeneratorAction.hh>
Public Member Functions
G4BlinePrimaryGeneratorAction ()
virtual ~G4BlinePrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
void SetUserPrimaryAction (G4VUserPrimaryGeneratorAction *anAction)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4VUserPrimaryGeneratorAction * fUserPrimaryAction
G4bool fFirstPartOfBline
G4ThreeVector fBlineStartPosition
G4double fT0
Detailed Description
Definition at line 59 of file G4BlinePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BlinePrimaryGeneratorAction.hh
Constructor & Destructor Documentation
G4BlinePrimaryGeneratorAction::G4BlinePrimaryGeneratorAction ()
Definition at line 50 of file G4BlinePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 50 of file G4BlinePrimaryGeneratorAction.cc
References fFirstPartOfBline, and fUserPrimaryAction.
G4BlinePrimaryGeneratorAction::~G4BlinePrimaryGeneratorAction () virtual
Definition at line 58 of file G4BlinePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 58 of file G4BlinePrimaryGeneratorAction.cc
Member Function Documentation
void G4BlinePrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 64 of file G4BlinePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 64 of file G4BlinePrimaryGeneratorAction.cc
References G4Event::AddPrimaryVertex(), G4ChargedGeantino::ChargedGeantino(), energy, fBlineStartPosition, fFirstPartOfBline, fT0, fUserPrimaryAction, G4Exception(), G4VUserPrimaryGeneratorAction::GeneratePrimaries(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4PrimaryVertex::GetPosition(), G4Event::GetPrimaryVertex(), G4PrimaryVertex::GetT0(), JustWarning, mass, MeV, particle, G4PrimaryParticle::SetCharge(), G4PrimaryParticle::SetMass(), and G4PrimaryVertex::SetPrimary().
void G4BlinePrimaryGeneratorAction::SetUserPrimaryAction (G4VUserPrimaryGeneratorAction * anAction) inline
Definition at line 67 of file G4BlinePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 67 of file G4BlinePrimaryGeneratorAction.hh
References fUserPrimaryAction.
Referenced by G4BlineTracer::ComputeBlines().
Member Data Documentation
G4ThreeVector G4BlinePrimaryGeneratorAction::fBlineStartPosition private
Definition at line 74 of file G4BlinePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 74 of file G4BlinePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4bool G4BlinePrimaryGeneratorAction::fFirstPartOfBline private
Definition at line 73 of file G4BlinePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file G4BlinePrimaryGeneratorAction.hh
Referenced by G4BlinePrimaryGeneratorAction(), and GeneratePrimaries().
G4double G4BlinePrimaryGeneratorAction::fT0 private
Definition at line 75 of file G4BlinePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BlinePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4VUserPrimaryGeneratorAction* G4BlinePrimaryGeneratorAction::fUserPrimaryAction private
Definition at line 72 of file G4BlinePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BlinePrimaryGeneratorAction.hh
Referenced by G4BlinePrimaryGeneratorAction(), GeneratePrimaries(), and SetUserPrimaryAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlinePrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/src/G4BlinePrimaryGeneratorAction.cc