ECCE @ EIC Software: G4INCL::BystrickyEvaluator< N > Struct Template Reference
G4INCL::BystrickyEvaluator< N > Struct Template Reference
Static Public Member Functions
static G4double eval (const G4double pLab, const G4double oneOverThreshold, HornerCoefficients< N > const &coeffs)
static G4double eval (const G4double pLab, const G4double oneOverThreshold, HornerCoefficients< N > const &coeffs)
static G4double eval (const G4double pLab, const G4double oneOverThreshold, HornerCoefficients< N > const &coeffs)
Detailed Description
template<G4int N>
struct G4INCL::BystrickyEvaluator< N >
Definition at line 47 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 47 of file G4INCLCrossSectionsMultiPions.cc
Member Function Documentation
template<G4int N> static G4double G4INCL::BystrickyEvaluator< N >::eval (const G4double pLab, const G4double oneOverThreshold, HornerCoefficients< N > const & coeffs) inline static
Definition at line 48 of file G4INCLCrossSectionsMultiPions.cc.
View newest version in sPHENIX GitHub at line 48 of file G4INCLCrossSectionsMultiPions.cc
References G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::ParticleTable::effectiveNucleonMass2, G4INCL::HornerEvaluator< M >::eval(), and x.
Referenced by G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), and G4INCL::CrossSectionsMultiPions::NNTwoPi().
template<G4int N> static G4double G4INCL::BystrickyEvaluator< N >::eval (const G4double pLab, const G4double oneOverThreshold, HornerCoefficients< N > const & coeffs) inline static
Definition at line 54 of file G4INCLCrossSectionsStrangeness.cc.
View newest version in sPHENIX GitHub at line 54 of file G4INCLCrossSectionsStrangeness.cc
References G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::ParticleTable::effectiveNucleonMass2, G4INCL::HornerEvaluator< M >::eval(), and x.
template<G4int N> static G4double G4INCL::BystrickyEvaluator< N >::eval (const G4double pLab, const G4double oneOverThreshold, HornerCoefficients< N > const & coeffs) inline static
Definition at line 54 of file G4INCLCrossSectionsMultiPionsAndResonances.cc.
View newest version in sPHENIX GitHub at line 54 of file G4INCLCrossSectionsMultiPionsAndResonances.cc
References G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::ParticleTable::effectiveNucleonMass2, G4INCL::HornerEvaluator< M >::eval(), and x.
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsMultiPions.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsMultiPionsAndResonances.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCrossSectionsStrangeness.cc