ECCE @ EIC Software: WLSDetectorConstruction Class Reference
WLSDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSDetectorConstruction.hh>
Public Member Functions
WLSDetectorConstruction ()
virtual ~WLSDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
G4VPhysicalVolume * ConstructDetector ()
virtual void ConstructSDandField ()
void SetWorldMaterial (G4String)
void SetWLSFiberMaterial (G4String)
void SetCoupleMaterial (G4String)
void SetPhotonDetGeometry (G4String)
void SetNumberOfCladding (G4int)
void SetWLSLength (G4double)
void SetWLSRadius (G4double)
void SetClad1Radius (G4double)
void SetClad2Radius (G4double)
void SetPhotonDetHalfLength (G4double)
void SetGap (G4double)
void SetPhotonDetAlignment (G4double)
void SetXYRatio (G4double)
void SetSurfaceRoughness (G4double)
void SetMirrorReflectivity (G4double)
void SetMirrorPolish (G4double)
void SetPhotonDetReflectivity (G4double)
void SetPhotonDetPolish (G4double)
void SetMirror (G4bool)
void SetBarLength (G4double)
void SetBarBase (G4double)
void SetHoleRadius (G4double)
void SetCoatingThickness (G4double)
void SetCoatingRadius (G4double)
G4double GetWLSFiberLength ()
G4double GetWLSFiberEnd ()
G4double GetWLSFiberRMax ()
G4double GetSurfaceRoughness ()
G4bool IsPerfectFiber ()
G4double GetBarLength ()
G4double GetBarBase ()
G4double GetHoleRadius ()
G4double GetHoleLength ()
G4double GetFiberRadius ()
G4double GetCoatingThickness ()
G4double GetCoatingRadius ()
G4Material * FindMaterial (G4String)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Static Public Member Functions
static G4RotationMatrix StringToRotationMatrix (G4String rotation)
Private Member Functions
void ConstructFiber ()
void UpdateGeometryParameters ()
Private Attributes
WLSMaterials * fMaterials
G4LogicalVolume * fLogicHole
G4LogicalVolume * fLogicWorld
G4VPhysicalVolume * fPhysiWorld
G4VPhysicalVolume * fPhysiHole
G4double fWorldSizeX
G4double fWorldSizeY
G4double fWorldSizeZ
G4double fWLSfiberRX
G4double fWLSfiberRY
G4double fWLSfiberZ
G4double fClad1RX
G4double fClad1RY
G4double fClad1Z
G4double fClad2RX
G4double fClad2RY
G4double fClad2Z
G4double fClrfiberHalfL
G4double fClrfiberZ
G4double fCoupleRX
G4double fCoupleRY
G4double fCoupleZ
G4double fMirrorRmax
G4double fMirrorZ
G4bool fMirrorToggle
G4String fMPPCShape
G4double fMPPCHalfL
G4double fMPPCZ
G4double fMPPCDist
G4double fMPPCTheta
G4double fWLSfiberOrigin
G4double fCoupleOrigin
G4double fMirrorOrigin
G4double fMPPCOriginX
G4double fMPPCOriginZ
G4int fNumOfCladLayers
G4double fMirrorPolish
G4double fMirrorReflectivity
G4double fMPPCPolish
G4double fMPPCReflectivity
G4double fExtrusionPolish
G4double fExtrusionReflectivity
G4double fSurfaceRoughness
G4double fXYRatio
G4double fBarLength
G4double fBarBase
G4double fHoleRadius
G4double fHoleLength
G4double fCoatingThickness
G4double fCoatingRadius
WLSDetectorMessenger * fDetectorMessenger
G4Cache< WLSPhotonDetSD * > fmppcSD
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 59 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 59 of file WLSDetectorConstruction.hh
Constructor & Destructor Documentation
WLSDetectorConstruction::WLSDetectorConstruction ()
Definition at line 67 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 67 of file WLSDetectorConstruction.cc
References deg, fBarBase, fBarLength, fClrfiberZ, fCoatingRadius, fCoatingThickness, fDetectorMessenger, fExtrusionPolish, fExtrusionReflectivity, fHoleLength, fHoleRadius, fMirrorPolish, fMirrorReflectivity, fMirrorToggle, fMirrorZ, fMPPCDist, fMPPCHalfL, fMPPCPolish, fMPPCReflectivity, fMPPCShape, fMPPCTheta, fMPPCZ, fNumOfCladLayers, fSurfaceRoughness, fWLSfiberOrigin, fWLSfiberRY, fWLSfiberZ, fXYRatio, m, mm, and nm.
WLSDetectorConstruction::~WLSDetectorConstruction () virtual
Definition at line 112 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 112 of file WLSDetectorConstruction.cc
References fDetectorMessenger, and fMaterials.
Member Function Documentation
G4VPhysicalVolume * WLSDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 120 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 120 of file WLSDetectorConstruction.cc
References G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), G4LogicalSkinSurface::CleanSurfaceTable(), G4LogicalBorderSurface::CleanSurfaceTable(), ConstructDetector(), fMaterials, fPhysiWorld, WLSMaterials::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), G4GeometryManager::OpenGeometry(), and UpdateGeometryParameters().
G4VPhysicalVolume * WLSDetectorConstruction::ConstructDetector ()
Definition at line 140 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 140 of file WLSDetectorConstruction.cc
References cm, ConstructFiber(), deg, dielectric_metal, eV, fExtrusionPolish, fExtrusionReflectivity, FindMaterial(), fLogicHole, fLogicWorld, fPhysiHole, fPhysiWorld, fWorldSizeX, fWorldSizeY, fWorldSizeZ, GetBarBase(), GetBarLength(), GetCoatingRadius(), GetCoatingThickness(), GetFiberRadius(), GetHoleLength(), GetHoleRadius(), glisur, ground, CLHEP::HepRotation::inverse(), mm, StringToRotationMatrix(), x, and y.
Referenced by Construct().
void WLSDetectorConstruction::ConstructFiber () private
Definition at line 372 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 372 of file WLSDetectorConstruction.cc
References G4MaterialPropertiesTable::AddProperty(), DBL_MAX, dielectric_dielectric, dielectric_metal, eV, FatalException, fClad1RX, fClad1RY, fClad1Z, fClad2RX, fClad2RY, fClad2Z, fClrfiberHalfL, fClrfiberZ, fCoupleOrigin, fCoupleRX, fCoupleRY, fCoupleZ, FindMaterial(), fLogicHole, fLogicWorld, fMirrorOrigin, fMirrorPolish, fMirrorReflectivity, fMirrorRmax, fMirrorToggle, fMirrorZ, fMPPCDist, fMPPCHalfL, fMPPCOriginX, fMPPCOriginZ, fMPPCPolish, fMPPCReflectivity, fMPPCShape, fMPPCTheta, fMPPCZ, fNumOfCladLayers, fPhysiHole, fSurfaceRoughness, fWLSfiberOrigin, fWLSfiberRX, fWLSfiberRY, fWLSfiberZ, fXYRatio, G4cerr, G4endl, G4Exception(), glisur, ground, ms, rad, G4OpticalSurface::SetMaterialPropertiesTable(), G4LogicalVolume::SetUserLimits(), and twopi.
Referenced by ConstructDetector().
void WLSDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 690 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 690 of file WLSDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fmppcSD, G4Cache< VALTYPE >::Get(), G4SDManager::GetSDMpointer(), G4Cache< VALTYPE >::Put(), and G4VUserDetectorConstruction::SetSensitiveDetector().
G4Material * WLSDetectorConstruction::FindMaterial (G4String name)
Definition at line 1059 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1059 of file WLSDetectorConstruction.cc
References G4Material::GetMaterial(), and material().
Referenced by ConstructDetector(), and ConstructFiber().
G4double WLSDetectorConstruction::GetBarBase ()
Definition at line 1001 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1001 of file WLSDetectorConstruction.cc
References fBarBase.
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetBarLength ()
Definition at line 997 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 997 of file WLSDetectorConstruction.cc
References fBarLength.
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetCoatingRadius ()
Definition at line 1022 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1022 of file WLSDetectorConstruction.cc
References fCoatingRadius.
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetCoatingThickness ()
Definition at line 1017 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1017 of file WLSDetectorConstruction.cc
References fCoatingThickness.
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetFiberRadius ()
Definition at line 1013 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1013 of file WLSDetectorConstruction.cc
References GetWLSFiberRMax().
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetHoleLength ()
Definition at line 1009 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1009 of file WLSDetectorConstruction.cc
References fHoleLength.
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetHoleRadius ()
Definition at line 1005 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1005 of file WLSDetectorConstruction.cc
References fHoleRadius.
Referenced by ConstructDetector().
G4double WLSDetectorConstruction::GetSurfaceRoughness ()
Definition at line 1042 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1042 of file WLSDetectorConstruction.cc
References fSurfaceRoughness.
G4double WLSDetectorConstruction::GetWLSFiberEnd ()
Definition at line 1026 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1026 of file WLSDetectorConstruction.cc
References fWLSfiberOrigin, and fWLSfiberZ.
Referenced by WLSSteppingAction::UserSteppingAction().
G4double WLSDetectorConstruction::GetWLSFiberLength ()
Definition at line 993 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 993 of file WLSDetectorConstruction.cc
References fWLSfiberZ.
G4double WLSDetectorConstruction::GetWLSFiberRMax ()
Definition at line 1033 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1033 of file WLSDetectorConstruction.cc
References fClad1RY, fClad2RY, fNumOfCladLayers, and fWLSfiberRY.
Referenced by GetFiberRadius().
G4bool WLSDetectorConstruction::IsPerfectFiber ()
Definition at line 1050 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1050 of file WLSDetectorConstruction.cc
References fMirrorPolish, fMirrorReflectivity, fMirrorToggle, fSurfaceRoughness, and fXYRatio.
Referenced by WLSSteppingAction::UserSteppingAction().
void WLSDetectorConstruction::SetBarBase (G4double side)
Definition at line 957 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 957 of file WLSDetectorConstruction.cc
References fBarBase, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetBarLength (G4double length)
Definition at line 948 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 948 of file WLSDetectorConstruction.cc
References fBarLength, G4RunManager::GetRunManager(), BTOF::length, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetClad1Radius (G4double radius)
Definition at line 829 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 829 of file WLSDetectorConstruction.cc
References fClad1RY, G4RunManager::GetRunManager(), radius, and G4RunManager::ReinitializeGeometry().
void WLSDetectorConstruction::SetClad2Radius (G4double radius)
Definition at line 838 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 838 of file WLSDetectorConstruction.cc
References fClad2RY, G4RunManager::GetRunManager(), radius, and G4RunManager::ReinitializeGeometry().
void WLSDetectorConstruction::SetCoatingRadius (G4double radius)
Definition at line 984 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 984 of file WLSDetectorConstruction.cc
References fCoatingRadius, G4RunManager::GetRunManager(), radius, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetCoatingThickness (G4double thick)
Definition at line 975 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 975 of file WLSDetectorConstruction.cc
References fCoatingThickness, G4RunManager::GetRunManager(), G4RunManager::ReinitializeGeometry(), and thick.
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetCoupleMaterial (G4String)
void WLSDetectorConstruction::SetGap (G4double gap)
Definition at line 857 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 857 of file WLSDetectorConstruction.cc
References fMPPCDist, BlackHoleGeometry::gap, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetHoleRadius (G4double radius)
Definition at line 966 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 966 of file WLSDetectorConstruction.cc
References fHoleRadius, G4RunManager::GetRunManager(), radius, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetMirror (G4bool flag)
Definition at line 928 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 928 of file WLSDetectorConstruction.cc
References fMirrorToggle, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetMirrorPolish (G4double polish)
Definition at line 888 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 888 of file WLSDetectorConstruction.cc
References fMirrorPolish, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetMirrorReflectivity (G4double reflectivity)
Definition at line 898 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 898 of file WLSDetectorConstruction.cc
References fMirrorReflectivity, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
void WLSDetectorConstruction::SetNumberOfCladding (G4int num)
Definition at line 801 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 801 of file WLSDetectorConstruction.cc
References fNumOfCladLayers, G4RunManager::GetRunManager(), num, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetPhotonDetAlignment (G4double theta)
Definition at line 866 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 866 of file WLSDetectorConstruction.cc
References fMPPCTheta, G4RunManager::GetRunManager(), G4RunManager::ReinitializeGeometry(), and theta().
void WLSDetectorConstruction::SetPhotonDetGeometry (G4String shape)
Definition at line 791 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 791 of file WLSDetectorConstruction.cc
References fMPPCShape, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetPhotonDetHalfLength (G4double halfL)
Definition at line 847 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 847 of file WLSDetectorConstruction.cc
References fMPPCHalfL, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
void WLSDetectorConstruction::SetPhotonDetPolish (G4double polish)
Definition at line 908 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 908 of file WLSDetectorConstruction.cc
References fMPPCPolish, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetPhotonDetReflectivity (G4double reflectivity)
Definition at line 918 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 918 of file WLSDetectorConstruction.cc
References fMPPCReflectivity, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
void WLSDetectorConstruction::SetSurfaceRoughness (G4double roughness)
Definition at line 878 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 878 of file WLSDetectorConstruction.cc
References fSurfaceRoughness, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetWLSFiberMaterial (G4String)
void WLSDetectorConstruction::SetWLSLength (G4double length)
Definition at line 811 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 811 of file WLSDetectorConstruction.cc
References fWLSfiberZ, G4RunManager::GetRunManager(), BTOF::length, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetWLSRadius (G4double radius)
Definition at line 820 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 820 of file WLSDetectorConstruction.cc
References fWLSfiberRY, G4RunManager::GetRunManager(), radius, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
void WLSDetectorConstruction::SetWorldMaterial (G4String)
void WLSDetectorConstruction::SetXYRatio (G4double r)
Definition at line 938 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 938 of file WLSDetectorConstruction.cc
References fXYRatio, G4RunManager::GetRunManager(), r, and G4RunManager::ReinitializeGeometry().
Referenced by WLSDetectorMessenger::SetNewValue().
G4RotationMatrix WLSDetectorConstruction::StringToRotationMatrix (G4String rotation) static
Definition at line 736 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 736 of file WLSDetectorConstruction.cc
References angle, deg, G4cerr, and G4endl.
Referenced by ConstructDetector().
void WLSDetectorConstruction::UpdateGeometryParameters () private
Definition at line 703 of file WLSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 703 of file WLSDetectorConstruction.cc
References cm, fClad1RX, fClad1RY, fClad1Z, fClad2RX, fClad2RY, fClad2Z, fClrfiberHalfL, fClrfiberZ, fCoupleOrigin, fCoupleRX, fCoupleRY, fCoupleZ, fMirrorOrigin, fMirrorRmax, fMirrorZ, fMPPCDist, fMPPCHalfL, fMPPCOriginX, fMPPCOriginZ, fMPPCTheta, fWLSfiberOrigin, fWLSfiberRX, fWLSfiberRY, fWLSfiberZ, fWorldSizeX, fWorldSizeY, fWorldSizeZ, and fXYRatio.
Referenced by Construct().
Member Data Documentation
G4double WLSDetectorConstruction::fBarBase private
Definition at line 196 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 196 of file WLSDetectorConstruction.hh
Referenced by GetBarBase(), SetBarBase(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fBarLength private
Definition at line 195 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 195 of file WLSDetectorConstruction.hh
Referenced by GetBarLength(), SetBarLength(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fClad1RX private
Definition at line 153 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 153 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClad1RY private
Definition at line 154 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 154 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetWLSFiberRMax(), SetClad1Radius(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClad1Z private
Definition at line 155 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 155 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClad2RX private
Definition at line 157 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 157 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClad2RY private
Definition at line 158 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 158 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetWLSFiberRMax(), SetClad2Radius(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClad2Z private
Definition at line 159 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 159 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClrfiberHalfL private
Definition at line 161 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 161 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fClrfiberZ private
Definition at line 162 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 162 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fCoatingRadius private
Definition at line 200 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 200 of file WLSDetectorConstruction.hh
Referenced by GetCoatingRadius(), SetCoatingRadius(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fCoatingThickness private
Definition at line 199 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 199 of file WLSDetectorConstruction.hh
Referenced by GetCoatingThickness(), SetCoatingThickness(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fCoupleOrigin private
Definition at line 179 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 179 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fCoupleRX private
Definition at line 164 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 164 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fCoupleRY private
Definition at line 165 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 165 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fCoupleZ private
Definition at line 166 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 166 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
WLSDetectorMessenger* WLSDetectorConstruction::fDetectorMessenger private
Definition at line 208 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 208 of file WLSDetectorConstruction.hh
Referenced by WLSDetectorConstruction(), and ~WLSDetectorConstruction().
G4double WLSDetectorConstruction::fExtrusionPolish private
Definition at line 190 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 190 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fExtrusionReflectivity private
Definition at line 191 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 191 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fHoleLength private
Definition at line 198 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 198 of file WLSDetectorConstruction.hh
Referenced by GetHoleLength(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fHoleRadius private
Definition at line 197 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 197 of file WLSDetectorConstruction.hh
Referenced by GetHoleRadius(), SetHoleRadius(), and WLSDetectorConstruction().
G4LogicalVolume* WLSDetectorConstruction::fLogicHole private
Definition at line 139 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 139 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and ConstructFiber().
G4LogicalVolume* WLSDetectorConstruction::fLogicWorld private
Definition at line 140 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 140 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and ConstructFiber().
WLSMaterials* WLSDetectorConstruction::fMaterials private
Definition at line 137 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 137 of file WLSDetectorConstruction.hh
Referenced by Construct(), and ~WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMirrorOrigin private
Definition at line 180 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 180 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fMirrorPolish private
Definition at line 186 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 186 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), IsPerfectFiber(), SetMirrorPolish(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMirrorReflectivity private
Definition at line 187 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 187 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), IsPerfectFiber(), SetMirrorReflectivity(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMirrorRmax private
Definition at line 168 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 168 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4bool WLSDetectorConstruction::fMirrorToggle private
Definition at line 170 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 170 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), IsPerfectFiber(), SetMirror(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMirrorZ private
Definition at line 169 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 169 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMPPCDist private
Definition at line 175 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 175 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), SetGap(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMPPCHalfL private
Definition at line 173 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 173 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), SetPhotonDetHalfLength(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMPPCOriginX private
Definition at line 181 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 181 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fMPPCOriginZ private
Definition at line 182 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 182 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fMPPCPolish private
Definition at line 188 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 188 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), SetPhotonDetPolish(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMPPCReflectivity private
Definition at line 189 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 189 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), SetPhotonDetReflectivity(), and WLSDetectorConstruction().
G4Cache<WLSPhotonDetSD*> WLSDetectorConstruction::fmppcSD private
Definition at line 209 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 209 of file WLSDetectorConstruction.hh
Referenced by ConstructSDandField().
G4String WLSDetectorConstruction::fMPPCShape private
Definition at line 172 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 172 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), SetPhotonDetGeometry(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMPPCTheta private
Definition at line 176 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 176 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), SetPhotonDetAlignment(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fMPPCZ private
Definition at line 174 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 174 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and WLSDetectorConstruction().
G4int WLSDetectorConstruction::fNumOfCladLayers private
Definition at line 184 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 184 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetWLSFiberRMax(), SetNumberOfCladding(), and WLSDetectorConstruction().
G4VPhysicalVolume* WLSDetectorConstruction::fPhysiHole private
Definition at line 143 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 143 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and ConstructFiber().
G4VPhysicalVolume* WLSDetectorConstruction::fPhysiWorld private
Definition at line 142 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 142 of file WLSDetectorConstruction.hh
Referenced by Construct(), and ConstructDetector().
G4double WLSDetectorConstruction::fSurfaceRoughness private
Definition at line 192 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 192 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetSurfaceRoughness(), IsPerfectFiber(), SetSurfaceRoughness(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fWLSfiberOrigin private
Definition at line 178 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 178 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetWLSFiberEnd(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fWLSfiberRX private
Definition at line 149 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 149 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fWLSfiberRY private
Definition at line 150 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 150 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetWLSFiberRMax(), SetWLSRadius(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fWLSfiberZ private
Definition at line 151 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 151 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), GetWLSFiberEnd(), GetWLSFiberLength(), SetWLSLength(), UpdateGeometryParameters(), and WLSDetectorConstruction().
G4double WLSDetectorConstruction::fWorldSizeX private
Definition at line 145 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 145 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fWorldSizeY private
Definition at line 146 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 146 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fWorldSizeZ private
Definition at line 147 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 147 of file WLSDetectorConstruction.hh
Referenced by ConstructDetector(), and UpdateGeometryParameters().
G4double WLSDetectorConstruction::fXYRatio private
Definition at line 193 of file WLSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 193 of file WLSDetectorConstruction.hh
Referenced by ConstructFiber(), IsPerfectFiber(), SetXYRatio(), UpdateGeometryParameters(), and WLSDetectorConstruction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSDetectorConstruction.cc