ECCE @ EIC Software: G4NeutronElectronElModel Class Reference
G4NeutronElectronElModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4NeutronElectronElModel.hh>
Public Member Functions
G4NeutronElectronElModel (const G4String &name="nu-e-elastic")
virtual ~G4NeutronElectronElModel ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
void Initialise ()
G4double XscIntegrand (G4double x)
G4double CalculateAm (G4double momentum)
G4double GetAm ()
G4double SampleSin2HalfTheta (G4double Tkin)
G4double GetTransfer (G4int iTkin, G4int iTransfer, G4double position)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4double fAm
G4double fM
G4double fM2
G4double fMv2
G4double fme
G4double fme2
G4double fee
G4double fee2
G4double fMinEnergy
G4double fMaxEnergy
G4int fEnergyBin
G4int fAngleBin
G4ParticleDefinition * theElectron
G4double fCutEnergy
G4PhysicsLogVector * fEnergyVector
G4PhysicsTable * fAngleTable
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 51 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 51 of file G4NeutronElectronElModel.hh
Constructor & Destructor Documentation
G4NeutronElectronElModel::G4NeutronElectronElModel (const G4String & name = "nu-e-elastic")
Definition at line 48 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4NeutronElectronElModel.cc
References e, G4Electron::Electron(), source.hepunit::electron_mass_c2, eV, fAngleBin, fAngleTable, fCutEnergy, fEnergyBin, fEnergyVector, fM, fM2, fMaxEnergy, fme, fme2, fMinEnergy, fMv2, GeV, Initialise(), MeV, source.hepunit::neutron_mass_c2, G4HadronElastic::SetLowestEnergyLimit(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), TeV, and theElectron.
G4NeutronElectronElModel::~G4NeutronElectronElModel () virtual
Definition at line 81 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4NeutronElectronElModel.cc
References G4PhysicsTable::clearAndDestroy(), fAngleTable, and fEnergyVector.
Member Function Documentation
G4HadFinalState * G4NeutronElectronElModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronElastic.
Definition at line 279 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 279 of file G4NeutronElectronElModel.cc
References G4HadFinalState::AddSecondary(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CalculateAm(), G4HadFinalState::Clear(), CLHEP::HepLorentzVector::e(), source.hepunit::electron_mass_c2, fAm, fCutEnergy, fee, fM, fme, G4UniformRand, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetZ_asInt(), G4HadronElastic::LowestEnergyLimit(), phi, SampleSin2HalfTheta(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetLocalEnergyDeposit(), G4HadFinalState::SetMomentumChange(), theElectron, G4HadronicInteraction::theParticleChange, CLHEP::twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and Z.
G4double G4NeutronElectronElModel::CalculateAm (G4double momentum) inline
Definition at line 101 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4NeutronElectronElModel.hh
References CLHEP::Bohr_radius, fAm, fee, fee2, fM, fme, fme2, CLHEP::hbarc, k, and momentum.
Referenced by ApplyYourself(), and Initialise().
G4double G4NeutronElectronElModel::GetAm () inline
Definition at line 71 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NeutronElectronElModel.hh
References fAm.
G4double G4NeutronElectronElModel::GetCutEnergy () inline
Definition at line 80 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4NeutronElectronElModel.hh
References fCutEnergy.
G4double G4NeutronElectronElModel::GetTransfer (G4int iTkin, G4int iTransfer, G4double position)
Definition at line 208 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 208 of file G4NeutronElectronElModel.cc
References Acts::Test::delta, epsilon(), fAngleBin, fAngleTable, G4UniformRand, x1, x2, y1, and y2.
Referenced by SampleSin2HalfTheta().
void G4NeutronElectronElModel::Initialise ()
Definition at line 134 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 134 of file G4NeutronElectronElModel.cc
References CalculateAm(), fAm, fAngleBin, fAngleTable, fEnergyBin, fEnergyVector, G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre96(), G4PhysicsFreeVector::PutValue(), sum, t1, t2, and XscIntegrand().
Referenced by G4NeutronElectronElModel().
G4bool G4NeutronElectronElModel::IsApplicable (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 109 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 109 of file G4NeutronElectronElModel.cc
References energy, fCutEnergy, fMaxEnergy, fMinEnergy, G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4HadProjectile::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), and Z.
void G4NeutronElectronElModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronElastic.
Definition at line 98 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 98 of file G4NeutronElectronElModel.cc
G4double G4NeutronElectronElModel::SampleSin2HalfTheta (G4double Tkin)
Definition at line 173 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 173 of file G4NeutronElectronElModel.cc
References fAngleBin, fAngleTable, fEnergyBin, G4UniformRand, GetTransfer(), and position.
Referenced by ApplyYourself().
void G4NeutronElectronElModel::SetCutEnergy (G4double ec) inline
Definition at line 79 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 79 of file G4NeutronElectronElModel.hh
References fCutEnergy.
G4double G4NeutronElectronElModel::XscIntegrand (G4double x)
Definition at line 256 of file G4NeutronElectronElModel.cc.
View newest version in sPHENIX GitHub at line 256 of file G4NeutronElectronElModel.cc
References fAm, fee, fee2, fM, fM2, fMv2, and x.
Referenced by Initialise().
Member Data Documentation
G4double G4NeutronElectronElModel::fAm private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by ApplyYourself(), CalculateAm(), GetAm(), Initialise(), and XscIntegrand().
G4int G4NeutronElectronElModel::fAngleBin private
Definition at line 90 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), GetTransfer(), Initialise(), and SampleSin2HalfTheta().
G4PhysicsTable* G4NeutronElectronElModel::fAngleTable private
Definition at line 94 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), GetTransfer(), Initialise(), SampleSin2HalfTheta(), and ~G4NeutronElectronElModel().
G4double G4NeutronElectronElModel::fCutEnergy private
Definition at line 92 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4NeutronElectronElModel.hh
Referenced by ApplyYourself(), G4NeutronElectronElModel(), GetCutEnergy(), IsApplicable(), and SetCutEnergy().
G4double G4NeutronElectronElModel::fee private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by ApplyYourself(), CalculateAm(), and XscIntegrand().
G4double G4NeutronElectronElModel::fee2 private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by CalculateAm(), and XscIntegrand().
G4int G4NeutronElectronElModel::fEnergyBin private
Definition at line 90 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), Initialise(), and SampleSin2HalfTheta().
G4PhysicsLogVector* G4NeutronElectronElModel::fEnergyVector private
Definition at line 93 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 93 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), Initialise(), and ~G4NeutronElectronElModel().
G4double G4NeutronElectronElModel::fM private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by ApplyYourself(), CalculateAm(), G4NeutronElectronElModel(), and XscIntegrand().
G4double G4NeutronElectronElModel::fM2 private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), and XscIntegrand().
G4double G4NeutronElectronElModel::fMaxEnergy private
Definition at line 89 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), and IsApplicable().
G4double G4NeutronElectronElModel::fme private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by ApplyYourself(), CalculateAm(), and G4NeutronElectronElModel().
G4double G4NeutronElectronElModel::fme2 private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by CalculateAm(), and G4NeutronElectronElModel().
G4double G4NeutronElectronElModel::fMinEnergy private
Definition at line 89 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), and IsApplicable().
G4double G4NeutronElectronElModel::fMv2 private
Definition at line 88 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronElectronElModel.hh
Referenced by G4NeutronElectronElModel(), and XscIntegrand().
G4ParticleDefinition* G4NeutronElectronElModel::theElectron private
Definition at line 91 of file G4NeutronElectronElModel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4NeutronElectronElModel.hh
Referenced by ApplyYourself(), and G4NeutronElectronElModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4NeutronElectronElModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4NeutronElectronElModel.cc