ECCE @ EIC Software: G4ParticleHPInelasticData Class Reference
G4ParticleHPInelasticData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInelasticData.hh>
Public Member Functions
G4ParticleHPInelasticData (G4ParticleDefinition *projectile=G4Neutron::Neutron())
~G4ParticleHPInelasticData ()
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int, G4int, const G4Element *, const G4Material *)
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, G4double aT)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
void IgnoreOnFlightDopplerBroadening ()
void EnableOnFlightDopplerBroadening ()
G4ParticleDefinition * GetProjectile ()
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4PhysicsTable * theCrossSections
G4bool onFlightDB
G4ParticleDefinition * theProjectile
G4ParticleHPData * theHPData
G4bool instanceOfWorker
G4double ke_cache
G4double xs_cache
const G4Element * element_cache
const G4Material * material_cache
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 53 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPInelasticData.hh
Constructor & Destructor Documentation
G4ParticleHPInelasticData::G4ParticleHPInelasticData (G4ParticleDefinition * projectile = G4Neutron::Neutron())
Definition at line 46 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPInelasticData.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), element_cache, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4He3::He3(), instanceOfWorker, G4Threading::IsMasterThread(), ke_cache, material_cache, message(), CLHEP::MeV, G4Neutron::Neutron(), onFlightDB, G4Proton::Proton(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), G4VCrossSectionDataSet::SetName(), theCrossSections, theHPData, theProjectile, G4Triton::Triton(), and xs_cache.
G4ParticleHPInelasticData::~G4ParticleHPInelasticData ()
Definition at line 112 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPInelasticData.cc
References G4PhysicsTable::clearAndDestroy(), instanceOfWorker, theCrossSections, and theHPData.
Member Function Documentation
void G4ParticleHPInelasticData::BuildPhysicsTable (const G4ParticleDefinition & projectile) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 165 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 165 of file G4ParticleHPInelasticData.cc
References G4PhysicsTable::clearAndDestroy(), G4cout, G4endl, G4ThreadLocal, G4Element::GetElementTable(), G4ParticleHPManager::GetInelasticCrossSections(), G4ParticleHPManager::GetInstance(), G4Element::GetNumberOfElements(), G4ParticleHPData::Instance(), G4Threading::IsWorkerThread(), G4ParticleHPData::MakePhysicsVector(), onFlightDB, G4PhysicsTable::push_back(), G4ParticleHPManager::RegisterInelasticCrossSections(), theCrossSections, and theHPData.
void G4ParticleHPInelasticData::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 374 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 374 of file G4ParticleHPInelasticData.cc
void G4ParticleHPInelasticData::DumpPhysicsTable (const G4ParticleDefinition & projectile) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 214 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 214 of file G4ParticleHPInelasticData.cc
References CLHEP::barn, CLHEP::eV, G4cout, G4endl, G4ThreadLocal, G4Element::GetElementTable(), G4Pow::GetInstance(), G4Element::GetNumberOfElements(), CLHEP::MeV, G4Pow::powA(), and theProjectile.
void G4ParticleHPInelasticData::EnableOnFlightDopplerBroadening () inline
Definition at line 86 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPInelasticData.hh
References onFlightDB.
G4double G4ParticleHPInelasticData::GetCrossSection (const G4DynamicParticle * projectile, const G4Element * anE, G4double aT)
Definition at line 267 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 267 of file G4ParticleHPInelasticData.cc
References kdfinder::abs(), eps, G4DynamicParticle::GetDefinition(), G4Element::GetIndex(), G4ReactionProduct::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4DynamicParticle::GetMomentum(), G4Element::GetN(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetThermalNucleus(), G4Element::GetZ(), CLHEP::k_Boltzmann, CLHEP::kelvin, G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag(), max, G4Neutron::Neutron(), onFlightDB, G4ReactionProduct::SetMomentum(), theCrossSections, and theProjectile.
Referenced by GetIsoCrossSection().
G4double G4ParticleHPInelasticData::GetIsoCrossSection (const G4DynamicParticle * dp, G4int , G4int , const G4Isotope * , const G4Element * element, const G4Material * material) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 138 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 138 of file G4ParticleHPInelasticData.cc
References element_cache, GetCrossSection(), G4DynamicParticle::GetKineticEnergy(), ke_cache, material(), material_cache, and xs_cache.
G4ParticleDefinition* G4ParticleHPInelasticData::GetProjectile () inline
Definition at line 88 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPInelasticData.hh
References theProjectile.
G4int G4ParticleHPInelasticData::GetVerboseLevel () const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 366 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 366 of file G4ParticleHPInelasticData.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::GetVerboseLevel().
void G4ParticleHPInelasticData::IgnoreOnFlightDopplerBroadening () inline
Definition at line 85 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPInelasticData.hh
References onFlightDB.
G4bool G4ParticleHPInelasticData::IsIsoApplicable (const G4DynamicParticle * dp, G4int , G4int , const G4Element * , const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 125 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleHPInelasticData.cc
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4VCrossSectionDataSet::GetMaxKinEnergy(), G4VCrossSectionDataSet::GetMinKinEnergy(), and theProjectile.
void G4ParticleHPInelasticData::SetVerboseLevel (G4int newValue) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 370 of file G4ParticleHPInelasticData.cc.
View newest version in sPHENIX GitHub at line 370 of file G4ParticleHPInelasticData.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::SetVerboseLevel().
Member Data Documentation
const G4Element* G4ParticleHPInelasticData::element_cache private
Definition at line 109 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPInelasticData.hh
Referenced by G4ParticleHPInelasticData(), and GetIsoCrossSection().
G4bool G4ParticleHPInelasticData::instanceOfWorker private
Definition at line 105 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPInelasticData.hh
Referenced by G4ParticleHPInelasticData(), and ~G4ParticleHPInelasticData().
G4double G4ParticleHPInelasticData::ke_cache private
Definition at line 107 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPInelasticData.hh
Referenced by G4ParticleHPInelasticData(), and GetIsoCrossSection().
const G4Material* G4ParticleHPInelasticData::material_cache private
Definition at line 110 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPInelasticData.hh
Referenced by G4ParticleHPInelasticData(), and GetIsoCrossSection().
G4bool G4ParticleHPInelasticData::onFlightDB private
Definition at line 99 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPInelasticData.hh
Referenced by BuildPhysicsTable(), EnableOnFlightDopplerBroadening(), G4ParticleHPInelasticData(), GetCrossSection(), and IgnoreOnFlightDopplerBroadening().
G4PhysicsTable* G4ParticleHPInelasticData::theCrossSections private
Definition at line 97 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPInelasticData.hh
Referenced by BuildPhysicsTable(), G4ParticleHPInelasticData(), GetCrossSection(), and ~G4ParticleHPInelasticData().
G4ParticleHPData* G4ParticleHPInelasticData::theHPData private
Definition at line 103 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPInelasticData.hh
Referenced by BuildPhysicsTable(), G4ParticleHPInelasticData(), and ~G4ParticleHPInelasticData().
G4ParticleDefinition* G4ParticleHPInelasticData::theProjectile private
Definition at line 101 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPInelasticData.hh
Referenced by DumpPhysicsTable(), G4ParticleHPInelasticData(), GetCrossSection(), GetProjectile(), and IsIsoApplicable().
G4double G4ParticleHPInelasticData::xs_cache private
Definition at line 108 of file G4ParticleHPInelasticData.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPInelasticData.hh
Referenced by G4ParticleHPInelasticData(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInelasticData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPInelasticData.cc