ECCE @ EIC Software: G4CrystalExtension Class Reference
G4CrystalExtension Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4CrystalExtension.hh>
Public Types
typedef G4double Elasticity [3][3][3][3]
typedef G4double ReducedElasticity [6][6]
Public Member Functions
G4CrystalExtension (G4Material *, const G4String &name="crystal")
~G4CrystalExtension ()
void Print () const
G4Material * GetMaterial ()
void SetMaterial (G4Material *aMat)
void SetUnitCell (G4CrystalUnitCell *aUC)
G4CrystalUnitCell * GetUnitCell () const
const Elasticity & GetElasticity () const
const ReducedElasticity & GetElReduced () const
G4double GetCijkl (G4int i, G4int j, G4int k, G4int l) const
void SetElReduced (const ReducedElasticity &mat)
void SetCpq (G4int p, G4int q, G4double value)
G4double GetCpq (G4int p, G4int q) const
G4CrystalAtomBase * GetAtomBase (const G4Element *anElement)
void AddAtomBase (const G4Element *anElement, G4CrystalAtomBase *aBase)
G4CrystalAtomBase * GetAtomBase (G4int anElIdx)
void AddAtomBase (G4int anElIdx, G4CrystalAtomBase *aLattice)
G4bool GetAtomPos (const G4Element *anEl, std::vector< G4ThreeVector > &vecout)
G4bool GetAtomPos (std::vector< G4ThreeVector > &vecout)
G4bool GetAtomPos (G4int anElIdx, std::vector< G4ThreeVector > &vecout)
G4complex ComputeStructureFactor (G4double kScatteringVector, G4int h, G4int k, G4int l)
G4complex ComputeStructureFactorGeometrical (G4int h, G4int k, G4int l)
void AddAtomicBond (G4AtomicBond *aBond)
G4AtomicBond * GetAtomicBond (G4int idx)
std::vector< G4AtomicBond * > GetAtomicBondVector ()
Public Member Functions inherited from G4VMaterialExtension
G4VMaterialExtension (const G4String &name)
virtual name ~G4VMaterialExtension ()
const std::size_t & GetHash () const
const G4String & GetName () const
Protected Attributes
Elasticity fElasticity
ReducedElasticity fElReduced
Protected Attributes inherited from G4VMaterialExtension
const G4String & fName
const std::size_t fHash
Private Attributes
G4Material * fMaterial
G4CrystalUnitCell * theUnitCell
std::map< const G4Element
*, G4CrystalAtomBase * > theCrystalAtomBaseMap
std::vector< G4AtomicBond * > theAtomicBondVector
Detailed Description
Definition at line 60 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CrystalExtension.hh
Member Typedef Documentation
typedef G4double G4CrystalExtension::Elasticity[3][3][3][3]
Definition at line 96 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 96 of file G4CrystalExtension.hh
typedef G4double G4CrystalExtension::ReducedElasticity[6][6]
Definition at line 97 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 97 of file G4CrystalExtension.hh
Constructor & Destructor Documentation
G4CrystalExtension::G4CrystalExtension (G4Material * mat, const G4String & name = "crystal")
Definition at line 39 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 39 of file G4CrystalExtension.cc
G4CrystalExtension::~G4CrystalExtension ()
Definition at line 46 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 46 of file G4CrystalExtension.cc
Member Function Documentation
void G4CrystalExtension::AddAtomBase (const G4Element * anElement, G4CrystalAtomBase * aBase) inline
Definition at line 128 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 128 of file G4CrystalExtension.hh
References theCrystalAtomBaseMap.
Referenced by AddAtomBase(), and GetAtomBase().
void G4CrystalExtension::AddAtomBase (G4int anElIdx, G4CrystalAtomBase * aLattice) inline
Definition at line 137 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 137 of file G4CrystalExtension.hh
References AddAtomBase(), fMaterial, and G4Material::GetElement().
void G4CrystalExtension::AddAtomicBond (G4AtomicBond * aBond) inline
Definition at line 175 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 175 of file G4CrystalExtension.hh
References theAtomicBondVector.
G4complex G4CrystalExtension::ComputeStructureFactor (G4double kScatteringVector, G4int h, G4int k, G4int l)
Definition at line 51 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 51 of file G4CrystalExtension.cc
References fMaterial, G4AtomicFormFactor::Get(), GetAtomBase(), G4Material::GetElementVector(), G4AtomicFormFactor::GetManager(), and CLHEP::pi.
G4complex G4CrystalExtension::ComputeStructureFactorGeometrical (G4int h, G4int k, G4int l)
Definition at line 83 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 83 of file G4CrystalExtension.cc
References fMaterial, GetAtomBase(), G4Material::GetElementVector(), G4CrystalAtomBase::GetPos(), and CLHEP::pi.
G4CrystalAtomBase * G4CrystalExtension::GetAtomBase (const G4Element * anElement)
Definition at line 120 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 120 of file G4CrystalExtension.cc
References AddAtomBase(), G4Exception(), G4Element::GetName(), JustWarning, and theCrystalAtomBaseMap.
Referenced by ComputeStructureFactor(), ComputeStructureFactorGeometrical(), GetAtomBase(), and GetAtomPos().
G4CrystalAtomBase* G4CrystalExtension::GetAtomBase (G4int anElIdx) inline
Definition at line 133 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 133 of file G4CrystalExtension.hh
References fMaterial, GetAtomBase(), and G4Material::GetElement().
G4AtomicBond* G4CrystalExtension::GetAtomicBond (G4int idx) inline
Definition at line 176 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 176 of file G4CrystalExtension.hh
References incremental_prev_tag::idx, and theAtomicBondVector.
std::vector<G4AtomicBond*> G4CrystalExtension::GetAtomicBondVector () inline
Definition at line 177 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 177 of file G4CrystalExtension.hh
References theAtomicBondVector.
G4bool G4CrystalExtension::GetAtomPos (const G4Element * anEl, std::vector< G4ThreeVector > & vecout)
Definition at line 133 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 133 of file G4CrystalExtension.cc
References G4CrystalUnitCell::FillAtomicPos(), GetAtomBase(), pos(), and theUnitCell.
Referenced by GetAtomPos().
G4bool G4CrystalExtension::GetAtomPos (std::vector< G4ThreeVector > & vecout)
Definition at line 145 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 145 of file G4CrystalExtension.cc
References fMaterial, GetAtomPos(), G4Material::GetElementVector(), and pos().
G4bool G4CrystalExtension::GetAtomPos (G4int anElIdx, std::vector< G4ThreeVector > & vecout) inline
Definition at line 148 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 148 of file G4CrystalExtension.hh
References fMaterial, GetAtomPos(), and G4Material::GetElement().
G4double G4CrystalExtension::GetCijkl (G4int i, G4int j, G4int k, G4int l) const inline
Definition at line 108 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 108 of file G4CrystalExtension.hh
References fElasticity, and k.
G4double G4CrystalExtension::GetCpq (G4int p, G4int q) const inline
Definition at line 116 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 116 of file G4CrystalExtension.hh
References fElReduced.
const Elasticity& G4CrystalExtension::GetElasticity () const inline
Definition at line 104 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 104 of file G4CrystalExtension.hh
References fElasticity.
const ReducedElasticity& G4CrystalExtension::GetElReduced () const inline
Definition at line 105 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 105 of file G4CrystalExtension.hh
References fElReduced.
G4Material* G4CrystalExtension::GetMaterial () inline
Definition at line 75 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CrystalExtension.hh
References fMaterial.
G4CrystalUnitCell* G4CrystalExtension::GetUnitCell () const inline
Definition at line 88 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 88 of file G4CrystalExtension.hh
References theUnitCell.
Referenced by G4LogicalCrystalVolume::GetBasis().
void G4CrystalExtension::Print (void) const inline virtual
Implements G4VMaterialExtension.
Definition at line 70 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 70 of file G4CrystalExtension.hh
void G4CrystalExtension::SetCpq (G4int p, G4int q, G4double value)
Definition at line 114 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 114 of file G4CrystalExtension.cc
References fElReduced.
void G4CrystalExtension::SetElReduced (const ReducedElasticity & mat)
Definition at line 104 of file G4CrystalExtension.cc.
View newest version in sPHENIX GitHub at line 104 of file G4CrystalExtension.cc
References fElReduced.
void G4CrystalExtension::SetMaterial (G4Material * aMat) inline
Definition at line 76 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CrystalExtension.hh
void G4CrystalExtension::SetUnitCell (G4CrystalUnitCell * aUC) inline
Definition at line 87 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 87 of file G4CrystalExtension.hh
References theUnitCell.
Member Data Documentation
Elasticity G4CrystalExtension::fElasticity protected
Definition at line 100 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 100 of file G4CrystalExtension.hh
Referenced by GetCijkl(), and GetElasticity().
ReducedElasticity G4CrystalExtension::fElReduced protected
Definition at line 101 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 101 of file G4CrystalExtension.hh
Referenced by GetCpq(), GetElReduced(), SetCpq(), and SetElReduced().
G4Material* G4CrystalExtension::fMaterial private
Definition at line 70 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 70 of file G4CrystalExtension.hh
Referenced by AddAtomBase(), ComputeStructureFactor(), ComputeStructureFactorGeometrical(), GetAtomBase(), GetAtomPos(), and GetMaterial().
std::vector<G4AtomicBond*> G4CrystalExtension::theAtomicBondVector private
Definition at line 172 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 172 of file G4CrystalExtension.hh
Referenced by AddAtomicBond(), GetAtomicBond(), and GetAtomicBondVector().
std::map<const G4Element*,G4CrystalAtomBase*> G4CrystalExtension::theCrystalAtomBaseMap private
Definition at line 123 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 123 of file G4CrystalExtension.hh
Referenced by AddAtomBase(), and GetAtomBase().
G4CrystalUnitCell* G4CrystalExtension::theUnitCell private
Definition at line 76 of file G4CrystalExtension.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CrystalExtension.hh
Referenced by GetAtomPos(), GetUnitCell(), and SetUnitCell().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4CrystalExtension.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4CrystalExtension.cc