ECCE @ EIC Software: CCalG4Hall Class Reference
CCalG4Hall Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Hall.hh>
Public Member Functions
CCalG4Hall (const G4String &name)
virtual ~CCalG4Hall ()
Public Member Functions inherited from CCalHall
CCalHall (const G4String &name)
virtual ~CCalHall ()
G4String getMaterial () const
G4double getDy_2Hall () const
G4double getDx_2Hall () const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Public Member Functions inherited from CCalG4Able
CCalG4Able (G4String name)
virtual ~CCalG4Able ()
G4VPhysicalVolume * PhysicalVolume (G4VPhysicalVolume *)
void setVisType (CCalVisualisable::visType, G4LogicalVolume *)
void setSensitivity (G4bool sens=true)
G4bool isSensitive () const
G4String G4Name () const
void setName (const G4String &name)
G4bool operator== (const CCalG4Able &right) const
Protected Member Functions
virtual G4VPhysicalVolume * constructIn (G4VPhysicalVolume *)
virtual void constructDaughters ()
Protected Member Functions inherited from CCalHall
virtual G4int readFile ()
Protected Member Functions inherited from CCalDetector
G4int buildFromFile ()
Protected Member Functions inherited from CCalG4Able
void AddCCalG4Able (CCalG4Able *)
virtual void constructSensitive ()
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Protected Attributes inherited from CCalG4Able
G4VPhysicalVolume * detPhysicalVolume
CCalG4AbleTable theG4DetectorsInside
G4String g4ableName
G4bool sensitivity
CCalVisualisable visProperties
G4VisAttributes * g4VisAtt [CCalVisualisable::TotalVisTypes]
Detailed Description
Definition at line 36 of file CCalG4Hall.hh.
View newest version in sPHENIX GitHub at line 36 of file CCalG4Hall.hh
Constructor & Destructor Documentation
CCalG4Hall::CCalG4Hall (const G4String & name)
Definition at line 53 of file CCalG4Hall.cc.
View newest version in sPHENIX GitHub at line 53 of file CCalG4Hall.cc
CCalG4Hall::~CCalG4Hall () virtual
Definition at line 56 of file CCalG4Hall.cc.
View newest version in sPHENIX GitHub at line 56 of file CCalG4Hall.cc
Member Function Documentation
void CCalG4Hall::constructDaughters () protected virtual
Reimplemented from CCalHall.
Definition at line 101 of file CCalG4Hall.cc.
View newest version in sPHENIX GitHub at line 101 of file CCalG4Hall.cc
References CCalG4Able::AddCCalG4Able(), CCalDetector::addDetector(), CCalG4Ecal::module1, and CCalG4Ecal::setType().
G4VPhysicalVolume * CCalG4Hall::constructIn (G4VPhysicalVolume * mother) protected virtual
Implements CCalG4Able.
Definition at line 62 of file CCalG4Hall.cc.
View newest version in sPHENIX GitHub at line 62 of file CCalG4Hall.cc
References CCalMaterialFactory::findMaterial(), G4cout, G4endl, CCalHall::getDx_2Hall(), CCalHall::getDy_2Hall(), CCalMaterialFactory::getInstance(), CCalHall::getMaterial(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), mm, CCalDetector::Name(), CCalVisualisable::PseudoVolumes, CCalG4Able::setVisType(), tab(), and Acts::Test::volume.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Hall.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalG4Hall.cc