ECCE @ EIC Software: AntiBaryonPhysics Class Reference
AntiBaryonPhysics Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.hh>
Public Member Functions
AntiBaryonPhysics ()
~AntiBaryonPhysics ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Attributes
G4TheoFSGenerator * ftfp
G4FTFModel * stringModel
G4ExcitedStringDecay * stringDecay
G4LundStringFragmentation * fragModel
G4GeneratorPrecompoundInterface * preCompoundModel
G4ComponentAntiNuclNuclearXS * theAntiNucleonXS
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 24 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 24 of file AntiBaryonPhysics.hh
Constructor & Destructor Documentation
AntiBaryonPhysics::AntiBaryonPhysics ()
Definition at line 48 of file AntiBaryonPhysics.cc.
View newest version in sPHENIX GitHub at line 48 of file AntiBaryonPhysics.cc
AntiBaryonPhysics::~AntiBaryonPhysics ()
Definition at line 58 of file AntiBaryonPhysics.cc.
View newest version in sPHENIX GitHub at line 58 of file AntiBaryonPhysics.cc
References fragModel, preCompoundModel, stringDecay, stringModel, and theAntiNucleonXS.
Member Function Documentation
void AntiBaryonPhysics::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 69 of file AntiBaryonPhysics.cc.
View newest version in sPHENIX GitHub at line 69 of file AntiBaryonPhysics.cc
void AntiBaryonPhysics::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 73 of file AntiBaryonPhysics.cc.
View newest version in sPHENIX GitHub at line 73 of file AntiBaryonPhysics.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddRestProcess(), G4AntiAlpha::AntiAlpha(), G4AntiDeuteron::AntiDeuteron(), G4AntiHe3::AntiHe3(), G4AntiLambda::AntiLambda(), G4AntiNeutron::AntiNeutron(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiTriton::AntiTriton(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), fragModel, ftfp, G4AntiNuclElastic::GetComponentCrossSection(), G4ParticleDefinition::GetProcessManager(), MeV, preCompoundModel, G4HadronicProcess::RegisterMe(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), stringDecay, stringModel, TeV, and theAntiNucleonXS.
Member Data Documentation
G4LundStringFragmentation* AntiBaryonPhysics::fragModel private
Definition at line 40 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 40 of file AntiBaryonPhysics.hh
Referenced by ConstructProcess(), and ~AntiBaryonPhysics().
G4TheoFSGenerator* AntiBaryonPhysics::ftfp private
Definition at line 37 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 37 of file AntiBaryonPhysics.hh
Referenced by ConstructProcess().
G4GeneratorPrecompoundInterface* AntiBaryonPhysics::preCompoundModel private
Definition at line 41 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 41 of file AntiBaryonPhysics.hh
Referenced by ConstructProcess(), and ~AntiBaryonPhysics().
G4ExcitedStringDecay* AntiBaryonPhysics::stringDecay private
Definition at line 39 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 39 of file AntiBaryonPhysics.hh
Referenced by ConstructProcess(), and ~AntiBaryonPhysics().
G4FTFModel* AntiBaryonPhysics::stringModel private
Definition at line 38 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 38 of file AntiBaryonPhysics.hh
Referenced by ConstructProcess(), and ~AntiBaryonPhysics().
G4ComponentAntiNuclNuclearXS* AntiBaryonPhysics::theAntiNucleonXS private
Definition at line 43 of file AntiBaryonPhysics.hh.
View newest version in sPHENIX GitHub at line 43 of file AntiBaryonPhysics.hh
Referenced by ConstructProcess(), and ~AntiBaryonPhysics().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.hh
coresoftware/blob/master/simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.cc