ECCE @ EIC Software: G4INCL::CoulombDistortion Namespace Reference
G4INCL::CoulombDistortion Namespace Reference
Functions
ParticleEntryAvatar * bringToSurface (Particle *p, Nucleus *const n)
Modify the momentum of an incoming particle and position it on the surface of the nucleus.
IAvatarList bringToSurface (Cluster *const c, Nucleus *const n)
Modify the momentum of an incoming cluster and position it on the surface of the target.
void distortOut (ParticleList const &pL, Nucleus const *const n)
Modify the momentum of an outgoing particle.
G4double maxImpactParameter (ParticleSpecies const &p, const G4double kinE, Nucleus const *const n)
Return the maximum impact parameter for Coulomb-distorted trajectories.
G4double maxImpactParameter (Particle const *const p, Nucleus const *const n)
Return the maximum impact parameter for Coulomb-distorted trajectories.
void setCoulomb (ICoulomb *const coulomb)
Set the Coulomb-distortion algorithm.
void deleteCoulomb ()
Delete the Coulomb-distortion object.
void initialize (Config const *const theConfig)
Initialize the Coulomb-distortion algorithm.
Detailed Description
Coulomb distortion
Function Documentation
ParticleEntryAvatar * G4INCL::CoulombDistortion::bringToSurface (Particle * p, Nucleus *const n)
Modify the momentum of an incoming particle and position it on the surface of the nucleus.
This method places Particle p on the surface of Nucleus n and modifies the direction of its momentum to be tangent to the Coulomb trajectory in that point.
The input particle has to be prepared with its asymptotic momentum. Its position is used only for the purpose of computing the asymptotic impact parameter; in other words, this method only uses the components of the position that are perpendicular to the momentum. The remaining component is not used, and can be set to any value.
This method returns a ParticleEntry avatar for the projectile.
Parameters
p incoming particle
n distorting nucleus
Returns
the ParticleEntryAvatar for the projectile particle
Definition at line 57 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLCoulombDistortion.cc
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
IAvatarList G4INCL::CoulombDistortion::bringToSurface (Cluster *const c, Nucleus *const n)
Modify the momentum of an incoming cluster and position it on the surface of the target.
Same as the Particle-based bringToSurface method, but for incoming heavy ions.
This method returns a list of ParticleEntry avatars for the participant nucleons
Parameters
c incoming heavy ion
n distorting nucleus
Returns
a list of ParticleEntryAvatars
Definition at line 61 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLCoulombDistortion.cc
void G4INCL::CoulombDistortion::deleteCoulomb ()
Delete the Coulomb-distortion object.
Definition at line 79 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 79 of file G4INCLCoulombDistortion.cc
Referenced by G4INCL::INCL::~INCL().
void G4INCL::CoulombDistortion::distortOut (ParticleList const & pL, Nucleus const *const n)
Modify the momentum of an outgoing particle.
Definition at line 65 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLCoulombDistortion.cc
Referenced by G4INCL::INCL::postCascade().
void G4INCL::CoulombDistortion::initialize (Config const *const theConfig)
Initialize the Coulomb-distortion algorithm.
Definition at line 84 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 84 of file G4INCLCoulombDistortion.cc
References G4INCL::Config::getCoulombType(), G4INCL::NoCoulomb, G4INCL::NonRelativisticCoulomb, and setCoulomb().
Referenced by G4INCL::INCL::INCL().
G4double G4INCL::CoulombDistortion::maxImpactParameter (ParticleSpecies const & p, const G4double kinE, Nucleus const *const n)
Return the maximum impact parameter for Coulomb-distorted trajectories.
Definition at line 69 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 69 of file G4INCLCoulombDistortion.cc
Referenced by maxImpactParameter(), G4INCL::INCL::prepareReaction(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
G4double G4INCL::CoulombDistortion::maxImpactParameter (Particle const *const p, Nucleus const *const n)
Return the maximum impact parameter for Coulomb-distorted trajectories.
Definition at line 73 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 73 of file G4INCLCoulombDistortion.cc
References G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getSpecies(), maxImpactParameter(), and n.
void G4INCL::CoulombDistortion::setCoulomb (ICoulomb *const coulomb)
Set the Coulomb-distortion algorithm.
Definition at line 77 of file G4INCLCoulombDistortion.cc.
View newest version in sPHENIX GitHub at line 77 of file G4INCLCoulombDistortion.cc
References coulomb.
Referenced by initialize().