ECCE @ EIC Software: G4PhysListUtil Class Reference
G4PhysListUtil Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/util/include/G4PhysListUtil.hh>
Static Public Member Functions
static G4HadronicProcess * FindInelasticProcess (const G4ParticleDefinition *)
static G4HadronicProcess * FindCaptureProcess (const G4ParticleDefinition *)
static G4HadronicProcess * FindFissionProcess (const G4ParticleDefinition *)
Private Member Functions
G4PhysListUtil ()
~G4PhysListUtil ()
Detailed Description
Definition at line 46 of file G4PhysListUtil.hh.
View newest version in sPHENIX GitHub at line 46 of file G4PhysListUtil.hh
Constructor & Destructor Documentation
G4PhysListUtil::G4PhysListUtil () private
G4PhysListUtil::~G4PhysListUtil () private
Member Function Documentation
G4HadronicProcess * G4PhysListUtil::FindCaptureProcess (const G4ParticleDefinition * p) static
Definition at line 62 of file G4PhysListUtil.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PhysListUtil.cc
References fCapture, G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), n, and G4ProcessVector::size().
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsFTFP_BERT_TRV::ExtraConfiguration(), G4HadronPhysicsQGS_BIC::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsFTF_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsFTFP_BERT::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), and G4HadronPhysicsINCLXX::ExtraConfiguration().
G4HadronicProcess * G4PhysListUtil::FindFissionProcess (const G4ParticleDefinition * p) static
Definition at line 79 of file G4PhysListUtil.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PhysListUtil.cc
References fFission, G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), n, and G4ProcessVector::size().
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), and G4HadronPhysicsINCLXX::ExtraConfiguration().
G4HadronicProcess * G4PhysListUtil::FindInelasticProcess (const G4ParticleDefinition * p) static
Definition at line 45 of file G4PhysListUtil.cc.
View newest version in sPHENIX GitHub at line 45 of file G4PhysListUtil.cc
References fHadronInelastic, G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), n, and G4ProcessVector::size().
Referenced by G4HadronPhysicsFTFP_BERT_TRV::ExtraConfiguration(), G4HadronPhysicsQGS_BIC::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsFTF_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), and G4HadronPhysicsFTFP_BERT::ExtraConfiguration().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/util/include/G4PhysListUtil.hh
geant4/tree/geant4-10.6-release/source/physics_lists/util/src/G4PhysListUtil.cc