ECCE @ EIC Software: PhysListEm19DStandard Class Reference
PhysListEm19DStandard Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PhysListEm19DStandard.hh>
Public Member Functions
PhysListEm19DStandard (G4int ver=0, const G4String &name="")
virtual ~PhysListEm19DStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Attributes
G4int verbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 50 of file PhysListEm19DStandard.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysListEm19DStandard.hh
Constructor & Destructor Documentation
PhysListEm19DStandard::PhysListEm19DStandard (G4int ver = 0, const G4String & name = "") explicit
Definition at line 105 of file PhysListEm19DStandard.cc.
View newest version in sPHENIX GitHub at line 105 of file PhysListEm19DStandard.cc
References bElectromagnetic, fUseSafetyPlus, G4EmParameters::Instance(), G4EmParameters::SetDefaults(), G4EmParameters::SetFluo(), G4EmParameters::SetLateralDisplacementAlg96(), G4EmParameters::SetMscStepLimitType(), G4EmParameters::SetNumberOfBinsPerDecade(), G4VPhysicsConstructor::SetPhysicsType(), G4EmParameters::SetVerbose(), and verbose.
PhysListEm19DStandard::~PhysListEm19DStandard () virtual
Definition at line 120 of file PhysListEm19DStandard.cc.
View newest version in sPHENIX GitHub at line 120 of file PhysListEm19DStandard.cc
Member Function Documentation
void PhysListEm19DStandard::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 125 of file PhysListEm19DStandard.cc.
View newest version in sPHENIX GitHub at line 125 of file PhysListEm19DStandard.cc
References G4Alpha::Alpha(), G4AntiProton::AntiProton(), G4Deuteron::Deuteron(), G4Electron::Electron(), G4Gamma::Gamma(), G4GenericIon::GenericIonDefinition(), G4He3::He3(), G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), G4Positron::Positron(), G4Proton::Proton(), and G4Triton::Triton().
void PhysListEm19DStandard::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 156 of file PhysListEm19DStandard.cc.
View newest version in sPHENIX GitHub at line 156 of file PhysListEm19DStandard.cc
References G4VMultipleScattering::AddEmModel(), G4cout, G4endl, G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4PhysicsListHelper::GetPhysicsListHelper(), G4VPhysicsConstructor::GetPhysicsName(), G4LossTableManager::Instance(), MeV, G4InuclParticleNames::mup, particle, G4InuclParticleNames::pip, G4InuclParticleNames::pp, G4PhysicsListHelper::RegisterProcess(), G4VEmModel::SetActivationLowEnergyLimit(), G4LossTableManager::SetAtomDeexcitation(), G4VMultipleScattering::SetEmModel(), G4VEmProcess::SetEmModel(), G4VEnergyLossProcess::SetEmModel(), G4VEnergyLossProcess::SetFluctModel(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), G4VEmProcess::SetMinKinEnergy(), G4VEnergyLossProcess::SetStepFunction(), um, and verbose.
Member Data Documentation
G4int PhysListEm19DStandard::verbose private
Definition at line 62 of file PhysListEm19DStandard.hh.
View newest version in sPHENIX GitHub at line 62 of file PhysListEm19DStandard.hh
Referenced by ConstructProcess(), and PhysListEm19DStandard().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PhysListEm19DStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/PhysListEm19DStandard.cc