ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_Misc.cc File Reference
xDataTOM_Misc.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include "xDataTOM_private.h"
Macros
#define nameValueLength 1024
Functions
static xDataTOM_element * xDataTOM_getLinksElement2 (statusMessageReporting *smr, xDataTOM_element *element, char const *link, char const *fullLink)
static int xDataTOM_getLinksElement3 (statusMessageReporting *smr, char const *nameValue, char *name, char *value, char const *fullLink)
char * xDataTOMMisc_getAbsPath (statusMessageReporting *smr, const char *fileName)
int xDataTOM_setMessageError_ReturnInt (int value, statusMessageReporting *smr, void *userInterface, const char *packageName, int lineNumber, int code, const char *fmt,...)
xDataTOM_element * xDataTOM_getLinksElement (statusMessageReporting *smr, xDataTOM_element *element, char const *link)
Macro Definition Documentation
#define nameValueLength 1024
Definition at line 22 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_Misc.cc
Referenced by xDataTOM_getLinksElement2(), and xDataTOM_getLinksElement3().
Function Documentation
xDataTOM_element* xDataTOM_getLinksElement (statusMessageReporting * smr, xDataTOM_element * element, char const * link)
Definition at line 89 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 89 of file xDataTOM_Misc.cc
References xDataTOM_element_s::parent, smr_setReportError2, smr_unknownID, and xDataTOM_getLinksElement2().
Referenced by MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM().
static xDataTOM_element * xDataTOM_getLinksElement2 (statusMessageReporting * smr, xDataTOM_element * element, char const * link, char const * fullLink) static
Definition at line 104 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 104 of file xDataTOM_Misc.cc
References xDataTOM_element_s::children, int(), n, xDataTOM_element_s::name, nameValueLength, xDataTOM_element_s::next, smr_setReportError2, smr_unknownID, xDataTOM_getAttributesValueInElement(), and xDataTOM_getLinksElement3().
Referenced by xDataTOM_getLinksElement().
static int xDataTOM_getLinksElement3 (statusMessageReporting * smr, char const * nameValue, char * name, char * value, char const * fullLink) static
Definition at line 138 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 138 of file xDataTOM_Misc.cc
References int(), n, nameValueLength, smr_setReportError2, and smr_unknownID.
Referenced by xDataTOM_getLinksElement2().
int xDataTOM_setMessageError_ReturnInt (int value, statusMessageReporting * smr, void * userInterface, const char * packageName, int lineNumber, int code, const char * fmt, ...)
Definition at line 76 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 76 of file xDataTOM_Misc.cc
References smr_setReportError(), and xDataTOM_smrLibraryID.
char* xDataTOMMisc_getAbsPath (statusMessageReporting * smr, const char * fileName)
Definition at line 29 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 29 of file xDataTOM_Misc.cc
References g4zmq::cwd(), int(), n, smr_malloc2, smr_setReportError2p, and xDataTOM_smrLibraryID.
Referenced by MCGIDI_target_heated_read().