ECCE @ EIC Software: G4GeneralParticleSourceData Class Reference
G4GeneralParticleSourceData Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4GeneralParticleSourceData.hh>
Public Member Functions
void AddASource (G4double intensity)
void DeleteASource (G4int idx)
void ClearSources ()
void IntensityNormalise ()
G4bool Normalised () const
G4SingleParticleSource * GetCurrentSource (G4int idx)
G4SingleParticleSource * GetCurrentSource () const
G4int GetSourceVectorSize () const
G4int GetIntensityVectorSize () const
G4double GetIntensity (G4int idx) const
G4double GetSourceProbability (G4int idx) const
void SetCurrentSourceIntensity (G4double)
void SetFlatSampling (G4bool fSamp)
G4bool GetFlatSampling () const
void SetMultipleVertex (G4bool flag)
G4bool GetMultipleVertex () const
G4int GetCurrentSourceIdx () const
void SetVerbosityAllSources (G4int vl)
void Lock ()
void Unlock ()
Static Public Member Functions
static
G4GeneralParticleSourceData * Instance ()
Private Member Functions
G4GeneralParticleSourceData ()
~G4GeneralParticleSourceData ()
Private Attributes
std::vector
< G4SingleParticleSource * > sourceVector
std::vector< G4double > sourceIntensity
std::vector< G4double > sourceProbability
G4bool multiple_vertex
G4bool flat_sampling
G4bool normalised
G4int currentSourceIdx
G4SingleParticleSource * currentSource
G4Mutex mutex
Detailed Description
Definition at line 63 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GeneralParticleSourceData.hh
Constructor & Destructor Documentation
G4GeneralParticleSourceData::G4GeneralParticleSourceData () private
Definition at line 67 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 67 of file G4GeneralParticleSourceData.cc
References currentSource, G4MUTEXINIT, sourceIntensity, sourceProbability, and sourceVector.
G4GeneralParticleSourceData::~G4GeneralParticleSourceData () private
Definition at line 83 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 83 of file G4GeneralParticleSourceData.cc
References G4MUTEXDESTROY, it, and sourceVector.
Member Function Documentation
void G4GeneralParticleSourceData::AddASource (G4double intensity)
Definition at line 142 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 142 of file G4GeneralParticleSourceData.cc
References currentSource, currentSourceIdx, normalised, sourceIntensity, and sourceVector.
Referenced by G4GeneralParticleSource::AddaSource().
void G4GeneralParticleSourceData::ClearSources ()
Definition at line 173 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 173 of file G4GeneralParticleSourceData.cc
References currentSource, currentSourceIdx, it, normalised, sourceIntensity, and sourceVector.
Referenced by G4GeneralParticleSource::ClearAll().
void G4GeneralParticleSourceData::DeleteASource (G4int idx)
Definition at line 151 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 151 of file G4GeneralParticleSourceData.cc
References currentSource, currentSourceIdx, false, GetCurrentSource(), GetIntensityVectorSize(), incremental_prev_tag::idx, normalised, sourceIntensity, and sourceVector.
Referenced by G4GeneralParticleSource::DeleteaSource().
G4SingleParticleSource * G4GeneralParticleSourceData::GetCurrentSource (G4int idx)
Definition at line 194 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 194 of file G4GeneralParticleSourceData.cc
References currentSource, currentSourceIdx, incremental_prev_tag::idx, and sourceVector.
Referenced by G4GeneralParticleSource::AddaSource(), G4GPSModel::DescribeYourselfTo(), G4GeneralParticleSource::G4GeneralParticleSource(), G4GeneralParticleSource::GeneratePrimaryVertex(), G4GeneralParticleSource::GetCurrentSource(), G4GeneralParticleSource::GetNumberOfParticles(), G4GeneralParticleSource::GetParticleDefinition(), G4GeneralParticleSource::GetParticleEnergy(), G4GeneralParticleSource::GetParticleMomentumDirection(), G4GeneralParticleSource::GetParticlePolarization(), G4GeneralParticleSource::GetParticlePosition(), G4GeneralParticleSource::GetParticleTime(), G4GeneralParticleSource::ListSource(), G4GeneralParticleSource::SetCurrentSourceto(), G4GeneralParticleSource::SetNumberOfParticles(), G4GeneralParticleSource::SetParticleCharge(), G4GeneralParticleSource::SetParticleDefinition(), G4GeneralParticleSource::SetParticlePolarization(), and G4GeneralParticleSource::SetParticleTime().
G4SingleParticleSource* G4GeneralParticleSourceData::GetCurrentSource () const inline
Definition at line 77 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GeneralParticleSourceData.hh
References currentSource.
Referenced by DeleteASource(), and IntensityNormalise().
G4int G4GeneralParticleSourceData::GetCurrentSourceIdx () const inline
Definition at line 92 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GeneralParticleSourceData.hh
References currentSourceIdx.
Referenced by G4GeneralParticleSource::GetCurrentSourceIndex(), and G4GeneralParticleSource::ListSource().
G4bool G4GeneralParticleSourceData::GetFlatSampling () const inline
Definition at line 87 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 87 of file G4GeneralParticleSourceData.hh
References flat_sampling.
Referenced by G4GeneralParticleSource::GeneratePrimaryVertex(), and G4GeneralParticleSource::ListSource().
G4double G4GeneralParticleSourceData::GetIntensity (G4int idx) const inline
Definition at line 81 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GeneralParticleSourceData.hh
References sourceIntensity.
Referenced by G4GeneralParticleSource::GetCurrentSourceIntensity(), and G4GeneralParticleSource::ListSource().
G4int G4GeneralParticleSourceData::GetIntensityVectorSize () const inline
Definition at line 80 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 80 of file G4GeneralParticleSourceData.hh
References sourceIntensity.
Referenced by DeleteASource(), G4GeneralParticleSource::DeleteaSource(), G4GeneralParticleSource::GeneratePrimaryVertex(), G4GeneralParticleSource::ListSource(), and G4GeneralParticleSource::SetCurrentSourceto().
G4bool G4GeneralParticleSourceData::GetMultipleVertex () const inline
Definition at line 90 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GeneralParticleSourceData.hh
References multiple_vertex.
Referenced by G4GeneralParticleSource::GeneratePrimaryVertex(), and G4GeneralParticleSource::ListSource().
G4double G4GeneralParticleSourceData::GetSourceProbability (G4int idx) const inline
Definition at line 82 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 82 of file G4GeneralParticleSourceData.hh
References sourceProbability.
Referenced by G4GeneralParticleSource::GeneratePrimaryVertex().
G4int G4GeneralParticleSourceData::GetSourceVectorSize () const inline
Definition at line 79 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GeneralParticleSourceData.hh
References sourceVector.
Referenced by G4GPSModel::DescribeYourselfTo(), and G4GeneralParticleSource::GetNumberofSource().
G4GeneralParticleSourceData * G4GeneralParticleSourceData::Instance (void) static
Definition at line 92 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 92 of file G4GeneralParticleSourceData.cc
References instance.
Referenced by G4GPSModel::DescribeYourselfTo(), and G4GeneralParticleSource::G4GeneralParticleSource().
void G4GeneralParticleSourceData::IntensityNormalise ()
Definition at line 99 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 99 of file G4GeneralParticleSourceData.cc
References flat_sampling, G4SingleParticleSource::GetBiasRndm(), GetCurrentSource(), normalised, G4SPSRandomGenerator::SetIntensityWeight(), sourceIntensity, sourceProbability, and G4INCL::CrossSections::total().
Referenced by G4GeneralParticleSource::IntensityNormalization().
void G4GeneralParticleSourceData::Lock ()
Definition at line 201 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 201 of file G4GeneralParticleSourceData.cc
References G4MUTEXLOCK.
Referenced by G4GeneralParticleSource::AddaSource(), G4GeneralParticleSource::GeneratePrimaryVertex(), and G4GeneralParticleSource::SetCurrentSourceIntensity().
G4bool G4GeneralParticleSourceData::Normalised () const inline
Definition at line 74 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GeneralParticleSourceData.hh
References normalised.
Referenced by G4GeneralParticleSource::ClearAll(), G4GeneralParticleSource::DeleteaSource(), G4GeneralParticleSource::GeneratePrimaryVertex(), G4GeneralParticleSource::IntensityNormalization(), and G4GeneralParticleSource::SetCurrentSourceIntensity().
void G4GeneralParticleSourceData::SetCurrentSourceIntensity (G4double intensity)
Definition at line 136 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 136 of file G4GeneralParticleSourceData.cc
References currentSourceIdx, normalised, and sourceIntensity.
Referenced by G4GeneralParticleSource::SetCurrentSourceIntensity().
void G4GeneralParticleSourceData::SetFlatSampling (G4bool fSamp) inline
Definition at line 86 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4GeneralParticleSourceData.hh
References flat_sampling.
Referenced by G4GeneralParticleSource::SetFlatSampling().
void G4GeneralParticleSourceData::SetMultipleVertex (G4bool flag) inline
Definition at line 89 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GeneralParticleSourceData.hh
References multiple_vertex.
Referenced by G4GeneralParticleSource::SetMultipleVertex().
void G4GeneralParticleSourceData::SetVerbosityAllSources (G4int vl)
Definition at line 184 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 184 of file G4GeneralParticleSourceData.cc
References it, and sourceVector.
Referenced by G4GeneralParticleSource::SetVerbosity().
void G4GeneralParticleSourceData::Unlock ()
Definition at line 206 of file G4GeneralParticleSourceData.cc.
View newest version in sPHENIX GitHub at line 206 of file G4GeneralParticleSourceData.cc
References G4MUTEXUNLOCK.
Referenced by G4GeneralParticleSource::AddaSource(), G4GeneralParticleSource::GeneratePrimaryVertex(), and G4GeneralParticleSource::SetCurrentSourceIntensity().
Member Data Documentation
G4SingleParticleSource* G4GeneralParticleSourceData::currentSource private
Definition at line 115 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 115 of file G4GeneralParticleSourceData.hh
Referenced by AddASource(), ClearSources(), DeleteASource(), G4GeneralParticleSourceData(), and GetCurrentSource().
G4int G4GeneralParticleSourceData::currentSourceIdx private
Definition at line 114 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4GeneralParticleSourceData.hh
Referenced by AddASource(), ClearSources(), DeleteASource(), GetCurrentSource(), GetCurrentSourceIdx(), and SetCurrentSourceIntensity().
G4bool G4GeneralParticleSourceData::flat_sampling private
Definition at line 111 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 111 of file G4GeneralParticleSourceData.hh
Referenced by GetFlatSampling(), IntensityNormalise(), and SetFlatSampling().
G4bool G4GeneralParticleSourceData::multiple_vertex private
Definition at line 110 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 110 of file G4GeneralParticleSourceData.hh
Referenced by GetMultipleVertex(), and SetMultipleVertex().
G4Mutex G4GeneralParticleSourceData::mutex private
Definition at line 116 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 116 of file G4GeneralParticleSourceData.hh
G4bool G4GeneralParticleSourceData::normalised private
Definition at line 112 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 112 of file G4GeneralParticleSourceData.hh
Referenced by AddASource(), ClearSources(), DeleteASource(), IntensityNormalise(), Normalised(), and SetCurrentSourceIntensity().
std::vector<G4double> G4GeneralParticleSourceData::sourceIntensity private
Definition at line 107 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GeneralParticleSourceData.hh
Referenced by AddASource(), ClearSources(), DeleteASource(), G4GeneralParticleSourceData(), GetIntensity(), GetIntensityVectorSize(), IntensityNormalise(), and SetCurrentSourceIntensity().
std::vector<G4double> G4GeneralParticleSourceData::sourceProbability private
Definition at line 108 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 108 of file G4GeneralParticleSourceData.hh
Referenced by G4GeneralParticleSourceData(), GetSourceProbability(), and IntensityNormalise().
std::vector<G4SingleParticleSource*> G4GeneralParticleSourceData::sourceVector private
Definition at line 106 of file G4GeneralParticleSourceData.hh.
View newest version in sPHENIX GitHub at line 106 of file G4GeneralParticleSourceData.hh
Referenced by AddASource(), ClearSources(), DeleteASource(), G4GeneralParticleSourceData(), GetCurrentSource(), GetSourceVectorSize(), SetVerbosityAllSources(), and ~G4GeneralParticleSourceData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4GeneralParticleSourceData.hh
geant4/tree/geant4-10.6-release/source/event/src/G4GeneralParticleSourceData.cc