ECCE @ EIC Software: XrayFluoPrimaryGeneratorAction Class Reference
XrayFluoPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPrimaryGeneratorAction.hh>
Public Member Functions
XrayFluoPrimaryGeneratorAction (const XrayFluoDetectorConstruction *)
~XrayFluoPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
void SetRndmFlag (G4String val)
void SetRndmVert (G4String val)
void SetSpectrum (G4String val)
void SetIsoVert (G4String val)
void ActivatePhaseSpace (G4String)
void SetRayleighFlag (G4bool)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * particleGun
const
XrayFluoDetectorConstruction * XrayFluoDetector
const XrayFluoRunAction * runAction
XrayFluoPrimaryGeneratorMessenger * gunMessenger
G4String rndmFlag
G4String beam
G4String spectrum
G4String isoVert
G4bool phaseSpaceGunFlag
G4bool rayleighFlag
G4ThreeVector detectorPosition
Detailed Description
Definition at line 54 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file XrayFluoPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction (const XrayFluoDetectorConstruction * XrayFluoDC)
Definition at line 54 of file XrayFluoPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 54 of file XrayFluoPrimaryGeneratorAction.cc
References cm, G4Gamma::Definition(), G4cout, G4endl, XrayFluoDetectorConstruction::GetWorldSizeZ(), gunMessenger, keV, particle, particleGun, runAction, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and XrayFluoDetector.
XrayFluoPrimaryGeneratorAction::~XrayFluoPrimaryGeneratorAction ()
Definition at line 109 of file XrayFluoPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 109 of file XrayFluoPrimaryGeneratorAction.cc
References gunMessenger, and particleGun.
Member Function Documentation
void XrayFluoPrimaryGeneratorAction::ActivatePhaseSpace (G4String fileName)
Definition at line 84 of file XrayFluoPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 84 of file XrayFluoPrimaryGeneratorAction.cc
References static_analysis_results::analysis(), cm, detectorPosition, XrayFluoDetectorConstruction::GetDetectorPosition(), XrayFluoAnalysisManager::getInstance(), XrayFluoAnalysisManager::LoadGunData(), phaseSpaceGunFlag, CLHEP::Hep3Vector::r(), rayleighFlag, CLHEP::Hep3Vector::setR(), and XrayFluoDetector.
Referenced by XrayFluoPrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 117 of file XrayFluoPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 117 of file XrayFluoPrimaryGeneratorAction.cc
References XrayFluoAnalysisManager::analysePrimaryGenerator(), static_analysis_results::analysis(), beam, cm, detectorPosition, Dx, Dy, energy, G4ParticleTable::FindParticle(), XrayFluoDataSet::FindValue(), G4cout, G4endl, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), XrayFluoRunAction::GetData(), XrayFluoRunAction::GetDataSum(), XrayFluoDetectorConstruction::GetDia3SizeXY(), XrayFluoAnalysisManager::GetEmittedParticleEnergyAndType(), XrayFluoRunAction::GetEnergies(), XrayFluoRunAction::GetGammaSet(), XrayFluoAnalysisManager::getInstance(), G4MTRunManager::GetMasterRunManager(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4RunManager::GetRunManager(), XrayFluoDetectorConstruction::GetSampleSizeXY(), G4RunManager::GetUserRunAction(), XrayFluoDetectorConstruction::GetWorldSizeZ(), isoVert, keV, m, mm, particle, particleGun, phaseSpaceGunFlag, phi, pi, rad, radius, rndmFlag, runAction, G4RunManager::sequentialRM, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), spectrum, sum, theta(), x, XrayFluoDetector, y, z, and G4InuclParticleNames::z0.
void XrayFluoPrimaryGeneratorAction::SetIsoVert (G4String val) inline
Definition at line 75 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 75 of file XrayFluoPrimaryGeneratorAction.hh
References isoVert.
Referenced by XrayFluoPrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPrimaryGeneratorAction::SetRayleighFlag (G4bool value)
Definition at line 101 of file XrayFluoPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 101 of file XrayFluoPrimaryGeneratorAction.cc
References rayleighFlag.
Referenced by XrayFluoPrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPrimaryGeneratorAction::SetRndmFlag (G4String val) inline
Definition at line 66 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file XrayFluoPrimaryGeneratorAction.hh
References rndmFlag.
Referenced by XrayFluoPrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPrimaryGeneratorAction::SetRndmVert (G4String val) inline
Definition at line 69 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file XrayFluoPrimaryGeneratorAction.hh
References beam.
Referenced by XrayFluoPrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPrimaryGeneratorAction::SetSpectrum (G4String val) inline
Definition at line 72 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file XrayFluoPrimaryGeneratorAction.hh
References spectrum.
Referenced by XrayFluoPrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4String XrayFluoPrimaryGeneratorAction::beam private
Definition at line 101 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 101 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmVert().
G4ThreeVector XrayFluoPrimaryGeneratorAction::detectorPosition private
Definition at line 115 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 115 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by ActivatePhaseSpace(), and GeneratePrimaries().
XrayFluoPrimaryGeneratorMessenger* XrayFluoPrimaryGeneratorAction::gunMessenger private
Definition at line 95 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 95 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by XrayFluoPrimaryGeneratorAction(), and ~XrayFluoPrimaryGeneratorAction().
G4String XrayFluoPrimaryGeneratorAction::isoVert private
Definition at line 107 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 107 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetIsoVert().
G4ParticleGun* XrayFluoPrimaryGeneratorAction::particleGun private
Definition at line 86 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), XrayFluoPrimaryGeneratorAction(), and ~XrayFluoPrimaryGeneratorAction().
G4bool XrayFluoPrimaryGeneratorAction::phaseSpaceGunFlag private
Definition at line 110 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 110 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by ActivatePhaseSpace(), and GeneratePrimaries().
G4bool XrayFluoPrimaryGeneratorAction::rayleighFlag private
Definition at line 113 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 113 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by ActivatePhaseSpace(), and SetRayleighFlag().
G4String XrayFluoPrimaryGeneratorAction::rndmFlag private
Definition at line 98 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 98 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmFlag().
const XrayFluoRunAction* XrayFluoPrimaryGeneratorAction::runAction private
Definition at line 92 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 92 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction().
G4String XrayFluoPrimaryGeneratorAction::spectrum private
Definition at line 104 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 104 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetSpectrum().
const XrayFluoDetectorConstruction* XrayFluoPrimaryGeneratorAction::XrayFluoDetector private
Definition at line 89 of file XrayFluoPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 89 of file XrayFluoPrimaryGeneratorAction.hh
Referenced by ActivatePhaseSpace(), GeneratePrimaries(), and XrayFluoPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoPrimaryGeneratorAction.cc