ECCE @ EIC Software: G4EmParameters Class Reference
G4EmParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmParameters.hh>
Public Member Functions
~G4EmParameters ()
void SetDefaults ()
void StreamInfo (std::ostream &os) const
void Dump () const
void SetLossFluctuations (G4bool val)
G4bool LossFluctuation () const
void SetBuildCSDARange (G4bool val)
G4bool BuildCSDARange () const
void SetLPM (G4bool val)
G4bool LPM () const
void SetSpline (G4bool val)
G4bool Spline () const
void SetUseCutAsFinalRange (G4bool val)
G4bool UseCutAsFinalRange () const
void SetApplyCuts (G4bool val)
G4bool ApplyCuts () const
void SetFluo (G4bool val)
G4bool Fluo () const
void SetBeardenFluoDir (G4bool val)
G4bool BeardenFluoDir () const
void SetAuger (G4bool val)
G4bool Auger () const
void SetAugerCascade (G4bool val)
G4bool AugerCascade () const
void SetPixe (G4bool val)
G4bool Pixe () const
void SetDeexcitationIgnoreCut (G4bool val)
G4bool DeexcitationIgnoreCut () const
void SetLateralDisplacement (G4bool val)
G4bool LateralDisplacement () const
void SetLateralDisplacementAlg96 (G4bool val)
G4bool LateralDisplacementAlg96 () const
void SetMuHadLateralDisplacement (G4bool val)
G4bool MuHadLateralDisplacement () const
void SetLatDisplacementBeyondSafety (G4bool val)
G4bool LatDisplacementBeyondSafety () const
void ActivateAngularGeneratorForIonisation (G4bool val)
G4bool UseAngularGeneratorForIonisation () const
void SetUseMottCorrection (G4bool val)
G4bool UseMottCorrection () const
void SetIntegral (G4bool val)
G4bool Integral () const
void SetBirksActive (G4bool val)
G4bool BirksActive () const
void SetUseICRU90Data (G4bool val)
G4bool UseICRU90Data () const
void SetDNAFast (G4bool val)
G4bool DNAFast () const
void SetDNAStationary (G4bool val)
G4bool DNAStationary () const
void SetDNAElectronMsc (G4bool val)
G4bool DNAElectronMsc () const
void SetGeneralProcessActive (G4bool val)
G4bool GeneralProcessActive () const
void SetEnableSamplingTable (G4bool val)
G4bool EnableSamplingTable () const
void SetEnablePolarisation (G4bool val)
G4bool EnablePolarisation () const
G4bool GetDirectionalSplitting () const
void SetDirectionalSplitting (G4bool v)
G4bool QuantumEntanglement () const
void SetQuantumEntanglement (G4bool v)
G4bool RetrieveMuDataFromFile () const
void SetRetrieveMuDataFromFile (G4bool v)
void SetOnIsolated (G4bool val)
G4bool OnIsolated () const
void ActivateDNA ()
void SetMinSubRange (G4double val)
G4double MinSubRange () const
void SetMinEnergy (G4double val)
G4double MinKinEnergy () const
void SetMaxEnergy (G4double val)
G4double MaxKinEnergy () const
void SetMaxEnergyForCSDARange (G4double val)
G4double MaxEnergyForCSDARange () const
void SetLowestElectronEnergy (G4double val)
G4double LowestElectronEnergy () const
void SetLowestMuHadEnergy (G4double val)
G4double LowestMuHadEnergy () const
void SetLowestTripletEnergy (G4double val)
G4double LowestTripletEnergy () const
void SetLinearLossLimit (G4double val)
G4double LinearLossLimit () const
void SetBremsstrahlungTh (G4double val)
G4double BremsstrahlungTh () const
void SetLambdaFactor (G4double val)
G4double LambdaFactor () const
void SetFactorForAngleLimit (G4double val)
G4double FactorForAngleLimit () const
void SetMscThetaLimit (G4double val)
G4double MscThetaLimit () const
void SetMscEnergyLimit (G4double val)
G4double MscEnergyLimit () const
void SetMscRangeFactor (G4double val)
G4double MscRangeFactor () const
void SetMscMuHadRangeFactor (G4double val)
G4double MscMuHadRangeFactor () const
void SetMscGeomFactor (G4double val)
G4double MscGeomFactor () const
void SetMscSafetyFactor (G4double val)
G4double MscSafetyFactor () const
void SetMscLambdaLimit (G4double val)
G4double MscLambdaLimit () const
void SetMscSkin (G4double val)
G4double MscSkin () const
void SetScreeningFactor (G4double val)
G4double ScreeningFactor () const
void SetMaxNIELEnergy (G4double val)
G4double MaxNIELEnergy () const
void SetMaxEnergyFor5DMuPair (G4double val)
G4double MaxEnergyFor5DMuPair () const
void SetStepFunction (G4double v1, G4double v2)
void SetStepFunctionMuHad (G4double v1, G4double v2)
void SetDirectionalSplittingRadius (G4double r)
G4double GetDirectionalSplittingRadius ()
void SetDirectionalSplittingTarget (const G4ThreeVector &v)
G4ThreeVector GetDirectionalSplittingTarget () const
void SetNumberOfBins (G4int val)
G4int NumberOfBins () const
void SetNumberOfBinsPerDecade (G4int val)
G4int NumberOfBinsPerDecade () const
void SetVerbose (G4int val)
G4int Verbose () const
void SetWorkerVerbose (G4int val)
G4int WorkerVerbose () const
void SetMscStepLimitType (G4MscStepLimitType val)
G4MscStepLimitType MscStepLimitType () const
void SetMscMuHadStepLimitType (G4MscStepLimitType val)
G4MscStepLimitType MscMuHadStepLimitType () const
void SetNuclearFormfactorType (G4NuclearFormfactorType val)
G4NuclearFormfactorType NuclearFormfactorType () const
void SetDNAeSolvationSubType (G4DNAModelSubType val)
G4DNAModelSubType DNAeSolvationSubType () const
void SetConversionType (G4int val)
G4int GetConversionType () const
void SetPIXECrossSectionModel (const G4String &)
const G4String & PIXECrossSectionModel ()
void SetPIXEElectronCrossSectionModel (const G4String &)
const G4String & PIXEElectronCrossSectionModel ()
void AddPAIModel (const G4String &particle, const G4String &region, const G4String &type)
const std::vector< G4String > & ParticlesPAI () const
const std::vector< G4String > & RegionsPAI () const
const std::vector< G4String > & TypesPAI () const
void AddMicroElec (const G4String &region)
const std::vector< G4String > & RegionsMicroElec () const
void AddDNA (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsDNA () const
const std::vector< G4String > & TypesDNA () const
void AddPhysics (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsPhysics () const
const std::vector< G4String > & TypesPhysics () const
void SetSubCutoff (G4bool val, const G4String &region="")
void SetDeexActiveRegion (const G4String &region, G4bool fdeex, G4bool fauger, G4bool fpixe)
void SetProcessBiasingFactor (const G4String &procname, G4double val, G4bool wflag)
void ActivateForcedInteraction (const G4String &procname, const G4String &region, G4double length, G4bool wflag)
void ActivateSecondaryBiasing (const G4String &name, const G4String &region, G4double factor, G4double energyLimit)
void SetEmSaturation (G4EmSaturation *)
G4EmSaturation * GetEmSaturation ()
void DefineRegParamForLoss (G4VEnergyLossProcess *, G4bool isElectron) const
void DefineRegParamForEM (G4VEmProcess *) const
void DefineRegParamForDeex (G4VAtomDeexcitation *) const
G4EmParameters (G4EmParameters &)=delete
G4EmParameters & operator= (const G4EmParameters &right)=delete
Static Public Member Functions
static G4EmParameters * Instance ()
Private Member Functions
G4EmParameters ()
void Initialise ()
G4bool IsLocked () const
void PrintWarning (G4ExceptionDescription &ed) const
Private Attributes
G4EmParametersMessenger * theMessenger
G4EmExtraParameters * fBParameters
G4EmLowEParameters * fCParameters
G4StateManager * fStateManager
G4EmSaturation * emSaturation
G4bool lossFluctuation
G4bool buildCSDARange
G4bool flagLPM
G4bool spline
G4bool cutAsFinalRange
G4bool applyCuts
G4bool lateralDisplacement
G4bool lateralDisplacementAlg96
G4bool muhadLateralDisplacement
G4bool latDisplacementBeyondSafety
G4bool useAngGeneratorForIonisation
G4bool useMottCorrection
G4bool integral
G4bool birks
G4bool fICRU90
G4bool gener
G4bool fSamplingTable
G4bool fPolarisation
G4bool fMuDataFromFile
G4bool onIsolated
G4bool fDNA
G4double minSubRange
G4double minKinEnergy
G4double maxKinEnergy
G4double maxKinEnergyCSDA
G4double max5DEnergyForMuPair
G4double lowestElectronEnergy
G4double lowestMuHadEnergy
G4double lowestTripletEnergy
G4double linLossLimit
G4double bremsTh
G4double lambdaFactor
G4double factorForAngleLimit
G4double thetaLimit
G4double energyLimit
G4double maxNIELEnergy
G4double rangeFactor
G4double rangeFactorMuHad
G4double geomFactor
G4double safetyFactor
G4double lambdaLimit
G4double skin
G4double factorScreen
G4int nbins
G4int nbinsPerDecade
G4int verbose
G4int workerVerbose
G4int tripletConv
G4MscStepLimitType mscStepLimit
G4MscStepLimitType mscStepLimitMuHad
G4NuclearFormfactorType nucFormfactor
Static Private Attributes
static G4EmParameters * theInstance = nullptr
Friends
std::ostream & operator<< (std::ostream &os, const G4EmParameters &)
Detailed Description
Definition at line 73 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 73 of file G4EmParameters.hh
Constructor & Destructor Documentation
G4EmParameters::~G4EmParameters ()
Definition at line 86 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 86 of file G4EmParameters.cc
References emSaturation, fBParameters, fCParameters, and theMessenger.
G4EmParameters::G4EmParameters (G4EmParameters &) delete
G4EmParameters::G4EmParameters () private
Definition at line 96 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 96 of file G4EmParameters.cc
References emSaturation, fBParameters, fCParameters, fStateManager, G4StateManager::GetStateManager(), Initialise(), G4NistManager::Instance(), and theMessenger.
Member Function Documentation
void G4EmParameters::ActivateAngularGeneratorForIonisation (G4bool val)
Definition at line 352 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 352 of file G4EmParameters.cc
References IsLocked(), and useAngGeneratorForIonisation.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option4::PhysListEmStandard_option4(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::ActivateDNA ()
Definition at line 518 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 518 of file G4EmParameters.cc
References fDNA, and IsLocked().
Referenced by AddDNA(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmDNAPhysicsActivator::G4EmDNAPhysicsActivator(), SetDNAElectronMsc(), SetDNAeSolvationSubType(), SetDNAFast(), and SetDNAStationary().
void G4EmParameters::ActivateForcedInteraction (const G4String & procname, const G4String & region, G4double length, G4bool wflag)
Definition at line 1141 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1141 of file G4EmParameters.cc
References G4EmExtraParameters::ActivateForcedInteraction(), fBParameters, gener, and IsLocked().
Referenced by G4EmProcessOptions::ActivateForcedInteraction().
void G4EmParameters::ActivateSecondaryBiasing (const G4String & name, const G4String & region, G4double factor, G4double energyLimit)
Definition at line 1151 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1151 of file G4EmParameters.cc
References G4EmExtraParameters::ActivateSecondaryBiasing(), fBParameters, and IsLocked().
Referenced by G4EmProcessOptions::ActivateSecondaryBiasing(), and G4EmProcessOptions::ActivateSecondaryBiasingForGamma().
void G4EmParameters::AddDNA (const G4String & region, const G4String & type)
Definition at line 1085 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1085 of file G4EmParameters.cc
References ActivateDNA(), G4EmLowEParameters::AddDNA(), fCParameters, and IsLocked().
void G4EmParameters::AddMicroElec (const G4String & region)
Definition at line 1074 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1074 of file G4EmParameters.cc
References G4EmLowEParameters::AddMicroElec(), fCParameters, and IsLocked().
void G4EmParameters::AddPAIModel (const G4String & particle, const G4String & region, const G4String & type)
Definition at line 1051 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1051 of file G4EmParameters.cc
References G4EmExtraParameters::AddPAIModel(), fBParameters, and IsLocked().
void G4EmParameters::AddPhysics (const G4String & region, const G4String & type)
Definition at line 1102 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1102 of file G4EmParameters.cc
References G4EmExtraParameters::AddPhysics(), fBParameters, and IsLocked().
Referenced by BiasedRDPhysics::BiasedRDPhysics(), LBE::ConstructGeneral(), DMXPhysicsList::DMXPhysicsList(), and G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics().
G4bool G4EmParameters::ApplyCuts () const
Definition at line 237 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 237 of file G4EmParameters.cc
References applyCuts.
Referenced by G4VEmProcess::PreparePhysicsTable().
G4bool G4EmParameters::Auger () const
Definition at line 270 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 270 of file G4EmParameters.cc
References G4EmLowEParameters::Auger(), and fCParameters.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4bool G4EmParameters::AugerCascade () const
Definition at line 281 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 281 of file G4EmParameters.cc
References G4EmLowEParameters::Auger(), and fCParameters.
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4bool G4EmParameters::BeardenFluoDir () const
Definition at line 259 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 259 of file G4EmParameters.cc
References G4EmLowEParameters::BeardenFluoDir(), and fCParameters.
Referenced by G4AtomicTransitionManager::Initialise(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4bool G4EmParameters::BirksActive () const
Definition at line 411 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 411 of file G4EmParameters.cc
References birks.
G4double G4EmParameters::BremsstrahlungTh () const
Definition at line 691 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 691 of file G4EmParameters.cc
References bremsTh.
Referenced by G4eBremsstrahlung::InitialiseEnergyLossProcess(), and G4eBremsstrahlung::StreamProcessInfo().
G4bool G4EmParameters::BuildCSDARange () const
Definition at line 193 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 193 of file G4EmParameters.cc
References buildCSDARange.
Referenced by G4LossTableManager::BuildTables(), G4EmCalculator::GetCSDARange(), G4EmCalculator::GetRange(), and G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::DeexcitationIgnoreCut () const
Definition at line 303 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 303 of file G4EmParameters.cc
References G4EmLowEParameters::DeexcitationIgnoreCut(), and fCParameters.
Referenced by G4ECDecay::DecayIt(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
void G4EmParameters::DefineRegParamForDeex (G4VAtomDeexcitation * ptr) const
Definition at line 1214 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1214 of file G4EmParameters.cc
References G4EmLowEParameters::DefineRegParamForDeex(), and fCParameters.
Referenced by G4EmModelActivator::ActivateEmOptions(), and G4VAtomDeexcitation::InitialiseAtomicDeexcitation().
void G4EmParameters::DefineRegParamForEM (G4VEmProcess * ptr) const
Definition at line 1166 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1166 of file G4EmParameters.cc
References G4EmExtraParameters::DefineRegParamForEM(), and fBParameters.
Referenced by G4VEmProcess::PreparePhysicsTable().
void G4EmParameters::DefineRegParamForLoss (G4VEnergyLossProcess * ptr, G4bool isElectron) const
Definition at line 1160 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1160 of file G4EmParameters.cc
References G4EmExtraParameters::DefineRegParamForLoss(), and fBParameters.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::DNAElectronMsc () const
Definition at line 458 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 458 of file G4EmParameters.cc
References G4EmLowEParameters::DNAElectronMsc(), and fCParameters.
G4DNAModelSubType G4EmParameters::DNAeSolvationSubType () const
Definition at line 1008 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1008 of file G4EmParameters.cc
References G4EmLowEParameters::DNAeSolvationSubType(), and fCParameters.
Referenced by G4CT_COUNT_IMPL(), and G4DNASolvationModelFactory::GetMacroDefinedModel().
G4bool G4EmParameters::DNAFast () const
Definition at line 434 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 434 of file G4EmParameters.cc
References G4EmLowEParameters::DNAFast(), and fCParameters.
G4bool G4EmParameters::DNAStationary () const
Definition at line 446 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 446 of file G4EmParameters.cc
References G4EmLowEParameters::DNAStationary(), and fCParameters.
void G4EmParameters::Dump () const
Definition at line 1344 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1344 of file G4EmParameters.cc
References G4cout, G4MUTEXLOCK, G4MUTEXUNLOCK, and StreamInfo().
Referenced by PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), and G4EmParametersMessenger::SetNewValue().
G4bool G4EmParameters::EnablePolarisation () const
Definition at line 391 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 391 of file G4EmParameters.cc
References fPolarisation.
G4bool G4EmParameters::EnableSamplingTable () const
Definition at line 513 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 513 of file G4EmParameters.cc
References fSamplingTable.
Referenced by G4SeltzerBergerModel::Initialise().
G4double G4EmParameters::FactorForAngleLimit () const
Definition at line 727 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 727 of file G4EmParameters.cc
References factorForAngleLimit.
Referenced by G4WentzelOKandVIxSection::Initialise(), and G4CoulombScattering::InitialiseProcess().
G4bool G4EmParameters::Fluo () const
Definition at line 248 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 248 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::Fluo().
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4bool G4EmParameters::GeneralProcessActive () const
Definition at line 472 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 472 of file G4EmParameters.cc
References gener.
G4int G4EmParameters::GetConversionType () const
Definition at line 1019 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1019 of file G4EmParameters.cc
References tripletConv.
Referenced by G4BetheHeitler5DModel::Initialise().
G4bool G4EmParameters::GetDirectionalSplitting () const
Definition at line 1182 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1182 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::GetDirectionalSplitting().
Referenced by G4EmBiasingManager::Initialise().
G4double G4EmParameters::GetDirectionalSplittingRadius ()
Definition at line 1209 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1209 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::GetDirectionalSplittingRadius().
Referenced by G4EmBiasingManager::Initialise().
G4ThreeVector G4EmParameters::GetDirectionalSplittingTarget () const
Definition at line 1198 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1198 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::GetDirectionalSplittingTarget().
Referenced by G4EmBiasingManager::Initialise().
G4EmSaturation * G4EmParameters::GetEmSaturation ()
Definition at line 524 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 524 of file G4EmParameters.cc
References emSaturation, and SetBirksActive().
Referenced by G4LossTableManager::EmSaturation().
void G4EmParameters::Initialise () private
Definition at line 118 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 118 of file G4EmParameters.cc
References applyCuts, birks, bremsTh, buildCSDARange, cutAsFinalRange, energyLimit, factorForAngleLimit, factorScreen, fDNA, fExponentialNF, fICRU90, flagLPM, fMinimal, fMuDataFromFile, fPolarisation, fSamplingTable, fUseSafety, gener, geomFactor, CLHEP::GeV, integral, CLHEP::keV, lambdaFactor, lambdaLimit, latDisplacementBeyondSafety, lateralDisplacement, lateralDisplacementAlg96, linLossLimit, lossFluctuation, lowestElectronEnergy, lowestMuHadEnergy, lowestTripletEnergy, max5DEnergyForMuPair, maxKinEnergy, maxKinEnergyCSDA, maxNIELEnergy, CLHEP::MeV, minKinEnergy, minSubRange, CLHEP::mm, mscStepLimit, mscStepLimitMuHad, muhadLateralDisplacement, nbins, nbinsPerDecade, nucFormfactor, onIsolated, CLHEP::pi, rangeFactor, rangeFactorMuHad, safetyFactor, skin, spline, CLHEP::TeV, thetaLimit, tripletConv, useAngGeneratorForIonisation, useMottCorrection, verbose, and workerVerbose.
Referenced by G4EmParameters(), and SetDefaults().
G4EmParameters * G4EmParameters::Instance (void) static
Definition at line 67 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 67 of file G4EmParameters.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and theInstance.
Referenced by G4EmModelActivator::ActivateEmOptions(), BiasedRDPhysics::BiasedRDPhysics(), G4GammaConversionToMuons::BuildPhysicsTable(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), BiasedRDPhysics::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), DMXPhysicsList::DMXPhysicsList(), EICPhysicsList::EICPhysicsList(), ElectromagneticPhysics::ElectromagneticPhysics(), FTFP_BERT_TRV::FTFP_BERT_TRV(), G4CT_COUNT_IMPL(), G4EmCalculator::G4EmCalculator(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmDNAPhysicsActivator::G4EmDNAPhysicsActivator(), G4EmLEPTSPhysics::G4EmLEPTSPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmModelActivator::G4EmModelActivator(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmProcessOptions::G4EmProcessOptions(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), G4LossTableBuilder::G4LossTableBuilder(), G4LossTableManager::G4LossTableManager(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), G4VAtomDeexcitation::G4VAtomDeexcitation(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMultipleScattering::G4VMultipleScattering(), G4DNASolvationModelFactory::GetMacroDefinedModel(), G4VMscModel::GetParticleChangeForMSC(), G4TablesForExtrapolator::Initialisation(), G4eplusTo2GammaOKVIModel::Initialise(), G4AtomicTransitionManager::Initialise(), G4BetheBlochModel::Initialise(), G4BetheHeitler5DModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4WentzelVIModel::Initialise(), G4EmBiasingManager::Initialise(), G4eSingleCoulombScatteringModel::Initialise(), G4BraggIonModel::Initialise(), G4SeltzerBergerModel::Initialise(), G4UrbanMscModel::Initialise(), G4BraggModel::Initialise(), G4MuPairProductionModel::Initialise(), G4WentzelOKandVIxSection::Initialise(), G4IonParametrisedLossModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4WentzelOKandVIxSection::InitialiseA(), G4VEmModel::InitialiseElementSelectors(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4UAtomicDeexcitation::InitialiseForNewRun(), G4VMscModel::InitialiseParameters(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), main(), G4CoulombScattering::MinPrimaryEnergy(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardSS::PhysListEmStandardSS(), PhysListEmStandardWVI::PhysListEmStandardWVI(), G4EmDataHandler::RetrievePhysicsTable(), G4RadioactiveDecayBase::StreamInfo(), G4RadioactiveDecay::StreamInfo(), G4CoulombScattering::StreamProcessInfo(), and G4eBremsstrahlung::StreamProcessInfo().
G4bool G4EmParameters::Integral () const
Definition at line 380 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 380 of file G4EmParameters.cc
References integral.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::IsLocked () const private
Definition at line 1361 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1361 of file G4EmParameters.cc
References fStateManager, G4State_Idle, G4State_Init, G4State_PreInit, G4StateManager::GetCurrentState(), and G4Threading::IsMasterThread().
Referenced by ActivateAngularGeneratorForIonisation(), ActivateDNA(), ActivateForcedInteraction(), ActivateSecondaryBiasing(), AddDNA(), AddMicroElec(), AddPAIModel(), AddPhysics(), SetApplyCuts(), SetAuger(), SetAugerCascade(), SetBeardenFluoDir(), SetBremsstrahlungTh(), SetBuildCSDARange(), SetConversionType(), SetDeexActiveRegion(), SetDeexcitationIgnoreCut(), SetDefaults(), SetDirectionalSplitting(), SetDirectionalSplittingRadius(), SetDirectionalSplittingTarget(), SetDNAElectronMsc(), SetDNAeSolvationSubType(), SetDNAFast(), SetDNAStationary(), SetEnablePolarisation(), SetEnableSamplingTable(), SetFactorForAngleLimit(), SetFluo(), SetGeneralProcessActive(), SetIntegral(), SetLambdaFactor(), SetLatDisplacementBeyondSafety(), SetLateralDisplacement(), SetLateralDisplacementAlg96(), SetLinearLossLimit(), SetLossFluctuations(), SetLowestElectronEnergy(), SetLowestMuHadEnergy(), SetLowestTripletEnergy(), SetLPM(), SetMaxEnergy(), SetMaxEnergyFor5DMuPair(), SetMaxEnergyForCSDARange(), SetMaxNIELEnergy(), SetMinEnergy(), SetMinSubRange(), SetMscEnergyLimit(), SetMscGeomFactor(), SetMscLambdaLimit(), SetMscMuHadRangeFactor(), SetMscMuHadStepLimitType(), SetMscRangeFactor(), SetMscSafetyFactor(), SetMscSkin(), SetMscStepLimitType(), SetMscThetaLimit(), SetMuHadLateralDisplacement(), SetNuclearFormfactorType(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), SetOnIsolated(), SetPixe(), SetPIXECrossSectionModel(), SetPIXEElectronCrossSectionModel(), SetProcessBiasingFactor(), SetQuantumEntanglement(), SetScreeningFactor(), SetSpline(), SetStepFunction(), SetStepFunctionMuHad(), SetSubCutoff(), SetUseCutAsFinalRange(), SetUseICRU90Data(), SetUseMottCorrection(), SetVerbose(), and SetWorkerVerbose().
G4double G4EmParameters::LambdaFactor () const
Definition at line 709 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 709 of file G4EmParameters.cc
References lambdaFactor.
Referenced by G4VEmProcess::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::LatDisplacementBeyondSafety () const
Definition at line 347 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 347 of file G4EmParameters.cc
References latDisplacementBeyondSafety.
Referenced by G4VMultipleScattering::PreparePhysicsTable().
G4bool G4EmParameters::LateralDisplacement () const
Definition at line 314 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 314 of file G4EmParameters.cc
References lateralDisplacement.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::PreparePhysicsTable().
G4bool G4EmParameters::LateralDisplacementAlg96 () const
Definition at line 325 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 325 of file G4EmParameters.cc
References lateralDisplacementAlg96.
Referenced by G4UrbanMscModel::Initialise().
G4double G4EmParameters::LinearLossLimit () const
Definition at line 673 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 673 of file G4EmParameters.cc
References linLossLimit.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::LossFluctuation () const
Definition at line 182 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 182 of file G4EmParameters.cc
References lossFluctuation.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4double G4EmParameters::LowestElectronEnergy () const
Definition at line 611 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 611 of file G4EmParameters.cc
References lowestElectronEnergy.
Referenced by G4EmCalculator::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4VEnergyLossProcess::G4VEnergyLossProcess(), and G4VEnergyLossProcess::PreparePhysicsTable().
G4double G4EmParameters::LowestMuHadEnergy () const
Definition at line 622 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 622 of file G4EmParameters.cc
References lowestMuHadEnergy.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4double G4EmParameters::LowestTripletEnergy () const
Definition at line 633 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 633 of file G4EmParameters.cc
References lowestTripletEnergy.
Referenced by G4eplusTo2GammaOKVIModel::Initialise().
G4bool G4EmParameters::LPM () const
Definition at line 204 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 204 of file G4EmParameters.cc
References flagLPM.
Referenced by G4eBremsstrahlung::InitialiseEnergyLossProcess(), and G4eBremsstrahlung::StreamProcessInfo().
G4double G4EmParameters::MaxEnergyFor5DMuPair () const
Definition at line 655 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 655 of file G4EmParameters.cc
References max5DEnergyForMuPair.
Referenced by G4GammaConversionToMuons::BuildPhysicsTable().
G4double G4EmParameters::MaxEnergyForCSDARange () const
Definition at line 600 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 600 of file G4EmParameters.cc
References maxKinEnergyCSDA.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4double G4EmParameters::MaxKinEnergy () const
Definition at line 581 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 581 of file G4EmParameters.cc
References maxKinEnergy.
Referenced by G4EmDNAPhysicsActivator::AddElectronModels0(), G4EmDNAPhysicsActivator::AddGenericIonModels0(), G4EmDNAPhysicsActivator::AddHeliumModels0(), G4EmDNAPhysicsActivator::AddProtonModels0(), G4VEmProcess::BuildLambdaTable(), G4VMscModel::GetParticleChangeForMSC(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VEmProcess::PrintWarning(), and G4VEmProcess::SetMinKinEnergyPrim().
G4double G4EmParameters::MaxNIELEnergy () const
Definition at line 644 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 644 of file G4EmParameters.cc
References maxNIELEnergy.
Referenced by G4EmLivermorePhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), and G4EmStandardPhysics_option4::ConstructProcess().
G4double G4EmParameters::MinKinEnergy () const
Definition at line 562 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 562 of file G4EmParameters.cc
References minKinEnergy.
Referenced by G4VEmProcess::BuildLambdaTable(), G4VMscModel::GetParticleChangeForMSC(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4LDMBremsstrahlung::InitialiseEnergyLossProcess(), G4hPairProduction::InitialiseEnergyLossProcess(), G4hBremsstrahlung::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4ePolarizedIonisation::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4eIonisation::InitialiseEnergyLossProcess(), G4eBremsstrahlung::InitialiseEnergyLossProcess(), G4MuBremsstrahlung::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4CoulombScattering::InitialiseProcess(), G4PolarizedGammaConversion::InitialiseProcess(), G4GammaGeneralProcess::InitialiseProcess(), G4ComptonScattering::InitialiseProcess(), G4PolarizedCompton::InitialiseProcess(), G4PolarizedPhotoElectricEffect::InitialiseProcess(), G4GammaConversion::InitialiseProcess(), G4PhotoElectricEffect::InitialiseProcess(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VEmProcess::PrintWarning(), and G4VEmProcess::SetMinKinEnergyPrim().
G4double G4EmParameters::MinSubRange () const
Definition at line 543 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 543 of file G4EmParameters.cc
References minSubRange.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4double G4EmParameters::MscEnergyLimit () const
Definition at line 763 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 763 of file G4EmParameters.cc
References energyLimit.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), and G4EmStandardPhysics_option2::ConstructProcess().
G4double G4EmParameters::MscGeomFactor () const
Definition at line 817 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 817 of file G4EmParameters.cc
References geomFactor.
Referenced by G4VMultipleScattering::GeomFactor(), and G4VMscModel::InitialiseParameters().
G4double G4EmParameters::MscLambdaLimit () const
Definition at line 853 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 853 of file G4EmParameters.cc
References lambdaLimit.
Referenced by G4VMscModel::InitialiseParameters().
G4double G4EmParameters::MscMuHadRangeFactor () const
Definition at line 799 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 799 of file G4EmParameters.cc
References rangeFactorMuHad.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::PreparePhysicsTable().
G4MscStepLimitType G4EmParameters::MscMuHadStepLimitType () const
Definition at line 984 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 984 of file G4EmParameters.cc
References mscStepLimitMuHad.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::PreparePhysicsTable().
G4double G4EmParameters::MscRangeFactor () const
Definition at line 781 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 781 of file G4EmParameters.cc
References rangeFactor.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::PreparePhysicsTable().
G4double G4EmParameters::MscSafetyFactor () const
Definition at line 835 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 835 of file G4EmParameters.cc
References safetyFactor.
Referenced by G4VMscModel::InitialiseParameters().
G4double G4EmParameters::MscSkin () const
Definition at line 871 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 871 of file G4EmParameters.cc
References skin.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::Skin().
G4MscStepLimitType G4EmParameters::MscStepLimitType () const
Definition at line 973 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 973 of file G4EmParameters.cc
References mscStepLimit.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::PreparePhysicsTable().
G4double G4EmParameters::MscThetaLimit () const
Definition at line 745 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 745 of file G4EmParameters.cc
References thetaLimit.
Referenced by G4CoulombScattering::InitialiseProcess(), G4CoulombScattering::MinPrimaryEnergy(), G4VMultipleScattering::PolarAngleLimit(), G4VEmProcess::PolarAngleLimit(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), and G4CoulombScattering::StreamProcessInfo().
G4bool G4EmParameters::MuHadLateralDisplacement () const
Definition at line 336 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 336 of file G4EmParameters.cc
References muhadLateralDisplacement.
Referenced by G4VMscModel::InitialiseParameters(), and G4VMultipleScattering::PreparePhysicsTable().
G4NuclearFormfactorType G4EmParameters::NuclearFormfactorType () const
Definition at line 996 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 996 of file G4EmParameters.cc
References nucFormfactor.
Referenced by G4eSingleCoulombScatteringModel::Initialise(), and G4WentzelOKandVIxSection::Initialise().
G4int G4EmParameters::NumberOfBins () const
Definition at line 920 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 920 of file G4EmParameters.cc
References nbins.
Referenced by G4VEmProcess::PrintWarning().
G4int G4EmParameters::NumberOfBinsPerDecade () const
Definition at line 939 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 939 of file G4EmParameters.cc
References nbinsPerDecade.
Referenced by G4VEmProcess::BuildLambdaTable(), G4LossTableBuilder::BuildTableForModel(), G4WentzelVIModel::Initialise(), G4VEmModel::InitialiseElementSelectors(), G4hhIonisation::InitialiseEnergyLossProcess(), G4mplIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4GammaGeneralProcess::InitialiseProcess(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4VEnergyLossProcess::StreamInfo().
G4bool G4EmParameters::OnIsolated () const
Definition at line 502 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 502 of file G4EmParameters.cc
References onIsolated.
Referenced by G4BetheHeitler5DModel::Initialise().
G4EmParameters& G4EmParameters::operator= (const G4EmParameters & right) delete
const std::vector< G4String > & G4EmParameters::ParticlesPAI () const
Definition at line 1059 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1059 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::ParticlesPAI().
Referenced by G4EmModelActivator::ActivatePAI().
G4bool G4EmParameters::Pixe () const
Definition at line 292 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 292 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::Pixe().
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation().
const G4String & G4EmParameters::PIXECrossSectionModel ()
Definition at line 1030 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1030 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::PIXECrossSectionModel().
Referenced by G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4UAtomicDeexcitation::InitialiseForNewRun().
const G4String & G4EmParameters::PIXEElectronCrossSectionModel ()
Definition at line 1041 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1041 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::PIXEElectronCrossSectionModel().
Referenced by G4PenelopeIonisationModel::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4UAtomicDeexcitation::InitialiseForNewRun().
void G4EmParameters::PrintWarning (G4ExceptionDescription & ed) const private
Definition at line 1046 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1046 of file G4EmParameters.cc
References G4Exception(), and JustWarning.
Referenced by SetBremsstrahlungTh(), SetFactorForAngleLimit(), SetLambdaFactor(), SetLinearLossLimit(), SetMaxEnergy(), SetMaxEnergyForCSDARange(), SetMinEnergy(), SetMinSubRange(), SetMscEnergyLimit(), SetMscGeomFactor(), SetMscLambdaLimit(), SetMscMuHadRangeFactor(), SetMscRangeFactor(), SetMscSafetyFactor(), SetMscSkin(), SetMscThetaLimit(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and SetScreeningFactor().
G4bool G4EmParameters::QuantumEntanglement () const
Definition at line 1171 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1171 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::QuantumEntanglement().
const std::vector< G4String > & G4EmParameters::RegionsDNA () const
Definition at line 1092 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1092 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::RegionsDNA().
Referenced by G4EmDNAPhysicsActivator::ConstructProcess().
const std::vector< G4String > & G4EmParameters::RegionsMicroElec () const
Definition at line 1080 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1080 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::RegionsMicroElec().
Referenced by G4EmModelActivator::ActivateMicroElec(), and G4EmModelActivator::G4EmModelActivator().
const std::vector< G4String > & G4EmParameters::RegionsPAI () const
Definition at line 1064 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1064 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::RegionsPAI().
Referenced by G4EmModelActivator::ActivatePAI(), and G4EmModelActivator::G4EmModelActivator().
const std::vector< G4String > & G4EmParameters::RegionsPhysics () const
Definition at line 1108 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1108 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::RegionsPhysics().
Referenced by G4EmModelActivator::ActivateEmOptions(), and G4EmModelActivator::G4EmModelActivator().
G4bool G4EmParameters::RetrieveMuDataFromFile () const
Definition at line 486 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 486 of file G4EmParameters.cc
References fMuDataFromFile.
Referenced by G4MuPairProductionModel::Initialise().
G4double G4EmParameters::ScreeningFactor () const
Definition at line 889 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 889 of file G4EmParameters.cc
References factorScreen.
Referenced by G4WentzelOKandVIxSection::InitialiseA().
void G4EmParameters::SetApplyCuts (G4bool val)
Definition at line 231 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 231 of file G4EmParameters.cc
References applyCuts, and IsLocked().
Referenced by G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmProcessOptions::SetApplyCuts(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetAuger (G4bool val)
Definition at line 264 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 264 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetAuger().
Referenced by DMXPhysicsList::DMXPhysicsList(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), and G4EmProcessOptions::SetAuger().
void G4EmParameters::SetAugerCascade (G4bool val)
Definition at line 275 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 275 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetAuger().
Referenced by G4EmModelActivator::ActivateEmOptions(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), BiasedRDPhysics::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), EICPhysicsList::EICPhysicsList(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), and G4EmStandardPhysicsSS::G4EmStandardPhysicsSS().
void G4EmParameters::SetBeardenFluoDir (G4bool val)
Definition at line 253 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 253 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetBeardenFluoDir().
void G4EmParameters::SetBirksActive (G4bool val)
Definition at line 396 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 396 of file G4EmParameters.cc
References birks, emSaturation, G4MUTEXLOCK, G4MUTEXUNLOCK, and G4EmSaturation::InitialiseG4Saturation().
Referenced by GetEmSaturation(), SetEmSaturation(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetBremsstrahlungTh (G4double val)
Definition at line 678 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 678 of file G4EmParameters.cc
References bremsTh, GeV, IsLocked(), and PrintWarning().
Referenced by G4EmProcessOptions::SetBremsstrahlungTh(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetBuildCSDARange (G4bool val)
Definition at line 187 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 187 of file G4EmParameters.cc
References buildCSDARange, and IsLocked().
Referenced by PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetBuildCSDARange(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetConversionType (G4int val)
Definition at line 1013 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1013 of file G4EmParameters.cc
References IsLocked(), and tripletConv.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetDeexActiveRegion (const G4String & region, G4bool fdeex, G4bool fauger, G4bool fpixe)
Definition at line 1125 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1125 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetDeexActiveRegion().
Referenced by G4EmModelActivator::ActivateEmOptions(), and G4EmProcessOptions::SetDeexcitationActiveRegion().
void G4EmParameters::SetDeexcitationIgnoreCut (G4bool val)
Definition at line 297 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 297 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetDeexcitationIgnoreCut().
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), and G4EmProcessOptions::SetDeexcitationIgnoreCuts().
void G4EmParameters::SetDefaults ()
Definition at line 109 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 109 of file G4EmParameters.cc
References fBParameters, fCParameters, G4EmLowEParameters::Initialise(), G4EmExtraParameters::Initialise(), Initialise(), and IsLocked().
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmLEPTSPhysics::G4EmLEPTSPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardSS::PhysListEmStandardSS(), and PhysListEmStandardWVI::PhysListEmStandardWVI().
void G4EmParameters::SetDirectionalSplitting (G4bool v)
Definition at line 1186 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1186 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetDirectionalSplitting().
void G4EmParameters::SetDirectionalSplittingRadius (G4double r)
Definition at line 1203 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1203 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetDirectionalSplittingRadius().
void G4EmParameters::SetDirectionalSplittingTarget (const G4ThreeVector & v)
Definition at line 1192 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1192 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetDirectionalSplittingTarget().
void G4EmParameters::SetDNAElectronMsc (G4bool val)
Definition at line 451 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 451 of file G4EmParameters.cc
References ActivateDNA(), fCParameters, IsLocked(), and G4EmLowEParameters::SetDNAElectronMsc().
void G4EmParameters::SetDNAeSolvationSubType (G4DNAModelSubType val)
Definition at line 1001 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1001 of file G4EmParameters.cc
References ActivateDNA(), fCParameters, IsLocked(), and G4EmLowEParameters::SetDNAeSolvationSubType().
void G4EmParameters::SetDNAFast (G4bool val)
Definition at line 427 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 427 of file G4EmParameters.cc
References ActivateDNA(), fCParameters, IsLocked(), and G4EmLowEParameters::SetDNAFast().
void G4EmParameters::SetDNAStationary (G4bool val)
Definition at line 439 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 439 of file G4EmParameters.cc
References ActivateDNA(), fCParameters, IsLocked(), and G4EmLowEParameters::SetDNAStationary().
void G4EmParameters::SetEmSaturation (G4EmSaturation * ptr)
Definition at line 477 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 477 of file G4EmParameters.cc
References emSaturation, and SetBirksActive().
void G4EmParameters::SetEnablePolarisation (G4bool val)
Definition at line 385 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 385 of file G4EmParameters.cc
References fPolarisation, and IsLocked().
void G4EmParameters::SetEnableSamplingTable (G4bool val)
Definition at line 507 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 507 of file G4EmParameters.cc
References fSamplingTable, and IsLocked().
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetFactorForAngleLimit (G4double val)
Definition at line 714 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 714 of file G4EmParameters.cc
References factorForAngleLimit, IsLocked(), and PrintWarning().
Referenced by G4EmProcessOptions::SetFactorForAngleLimit(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetFluo (G4bool val)
Definition at line 242 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 242 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetFluo().
Referenced by DMXPhysicsList::DMXPhysicsList(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), and G4EmProcessOptions::SetFluo().
void G4EmParameters::SetGeneralProcessActive (G4bool val)
Definition at line 463 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 463 of file G4EmParameters.cc
References fBParameters, gener, G4EmExtraParameters::Initialise(), and IsLocked().
Referenced by G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetIntegral (G4bool val)
Definition at line 374 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 374 of file G4EmParameters.cc
References integral, and IsLocked().
Referenced by G4EmProcessOptions::SetIntegral(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLambdaFactor (G4double val)
Definition at line 696 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 696 of file G4EmParameters.cc
References IsLocked(), lambdaFactor, and PrintWarning().
Referenced by G4EmProcessOptions::SetLambdaFactor(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLatDisplacementBeyondSafety (G4bool val)
Definition at line 341 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 341 of file G4EmParameters.cc
References IsLocked(), and latDisplacementBeyondSafety.
Referenced by G4EmProcessOptions::SetDisplacementBeyondSafety(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLateralDisplacement (G4bool val)
Definition at line 308 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 308 of file G4EmParameters.cc
References IsLocked(), and lateralDisplacement.
Referenced by G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmProcessOptions::SetMscLateralDisplacement(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLateralDisplacementAlg96 (G4bool val)
Definition at line 319 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 319 of file G4EmParameters.cc
References IsLocked(), and lateralDisplacementAlg96.
Referenced by G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmStandard_option3::PhysListEmStandard_option3(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLinearLossLimit (G4double val)
Definition at line 660 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 660 of file G4EmParameters.cc
References IsLocked(), linLossLimit, and PrintWarning().
Referenced by G4EmProcessOptions::SetLinearLossLimit(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLossFluctuations (G4bool val)
Definition at line 176 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 176 of file G4EmParameters.cc
References IsLocked(), and lossFluctuation.
Referenced by G4EmProcessOptions::SetLossFluctuations(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLowestElectronEnergy (G4double val)
Definition at line 605 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 605 of file G4EmParameters.cc
References IsLocked(), and lowestElectronEnergy.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLowestMuHadEnergy (G4double val)
Definition at line 616 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 616 of file G4EmParameters.cc
References IsLocked(), and lowestMuHadEnergy.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLowestTripletEnergy (G4double val)
Definition at line 627 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 627 of file G4EmParameters.cc
References IsLocked(), and lowestTripletEnergy.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetLPM (G4bool val)
Definition at line 198 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 198 of file G4EmParameters.cc
References flagLPM, and IsLocked().
Referenced by G4EmProcessOptions::SetLPMFlag(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMaxEnergy (G4double val)
Definition at line 567 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 567 of file G4EmParameters.cc
References e, G4lrint(), GeV, IsLocked(), max, maxKinEnergy, MeV, minKinEnergy, nbins, nbinsPerDecade, PrintWarning(), and TeV.
Referenced by DMXPhysicsList::DMXPhysicsList(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetMaxEnergy(), G4EmProcessOptions::SetMaxEnergyForMuons(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMaxEnergyFor5DMuPair (G4double val)
Definition at line 649 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 649 of file G4EmParameters.cc
References IsLocked(), and max5DEnergyForMuPair.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMaxEnergyForCSDARange (G4double val)
Definition at line 586 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 586 of file G4EmParameters.cc
References GeV, IsLocked(), maxKinEnergyCSDA, minKinEnergy, PrintWarning(), and TeV.
Referenced by PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetMaxEnergyForCSDARange(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMaxNIELEnergy (G4double val)
Definition at line 638 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 638 of file G4EmParameters.cc
References IsLocked(), and maxNIELEnergy.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMinEnergy (G4double val)
Definition at line 548 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 548 of file G4EmParameters.cc
References e, eV, G4lrint(), IsLocked(), maxKinEnergy, MeV, minKinEnergy, nbins, nbinsPerDecade, and PrintWarning().
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmProcessOptions::SetMinEnergy(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMinSubRange (G4double val)
Definition at line 530 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 530 of file G4EmParameters.cc
References IsLocked(), minSubRange, and PrintWarning().
Referenced by G4EmProcessOptions::SetMinSubRange(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscEnergyLimit (G4double val)
Definition at line 750 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 750 of file G4EmParameters.cc
References energyLimit, IsLocked(), and PrintWarning().
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscGeomFactor (G4double val)
Definition at line 804 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 804 of file G4EmParameters.cc
References geomFactor, IsLocked(), and PrintWarning().
Referenced by G4EmProcessOptions::SetMscGeomFactor(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscLambdaLimit (G4double val)
Definition at line 840 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 840 of file G4EmParameters.cc
References IsLocked(), lambdaLimit, and PrintWarning().
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscMuHadRangeFactor (G4double val)
Definition at line 786 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 786 of file G4EmParameters.cc
References IsLocked(), PrintWarning(), and rangeFactorMuHad.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscMuHadStepLimitType (G4MscStepLimitType val)
Definition at line 978 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 978 of file G4EmParameters.cc
References IsLocked(), and mscStepLimitMuHad.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscRangeFactor (G4double val)
Definition at line 768 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 768 of file G4EmParameters.cc
References IsLocked(), PrintWarning(), and rangeFactor.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option4::PhysListEmStandard_option4(), G4EmProcessOptions::SetMscRangeFactor(), G4EmParametersMessenger::SetNewValue(), and G4VMultipleScattering::SetRangeFactor().
void G4EmParameters::SetMscSafetyFactor (G4double val)
Definition at line 822 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 822 of file G4EmParameters.cc
References IsLocked(), PrintWarning(), and safetyFactor.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetMscSkin (G4double val)
Definition at line 858 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 858 of file G4EmParameters.cc
References IsLocked(), PrintWarning(), and skin.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), PhysListEmStandard_option4::PhysListEmStandard_option4(), G4EmParametersMessenger::SetNewValue(), G4EmProcessOptions::SetSkin(), and G4VMultipleScattering::SetSkin().
void G4EmParameters::SetMscStepLimitType (G4MscStepLimitType val)
Definition at line 967 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 967 of file G4EmParameters.cc
References IsLocked(), and mscStepLimit.
Referenced by DMXPhysicsList::DMXPhysicsList(), FTFP_BERT_TRV::FTFP_BERT_TRV(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), G4EmProcessOptions::SetMscStepLimitation(), G4EmParametersMessenger::SetNewValue(), and G4VMultipleScattering::SetStepLimitType().
void G4EmParameters::SetMscThetaLimit (G4double val)
Definition at line 732 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 732 of file G4EmParameters.cc
References IsLocked(), pi, PrintWarning(), and thetaLimit.
Referenced by G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardSS::PhysListEmStandardSS(), PhysListEmStandardWVI::PhysListEmStandardWVI(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetPolarAngleLimit().
void G4EmParameters::SetMuHadLateralDisplacement (G4bool val)
Definition at line 330 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 330 of file G4EmParameters.cc
References IsLocked(), and muhadLateralDisplacement.
Referenced by G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), G4EmProcessOptions::SetMscMuHadLateralDisplacement(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetNuclearFormfactorType (G4NuclearFormfactorType val)
Definition at line 990 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 990 of file G4EmParameters.cc
References IsLocked(), and nucFormfactor.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetNumberOfBins (G4int val)
Definition at line 906 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 906 of file G4EmParameters.cc
References G4lrint(), IsLocked(), maxKinEnergy, minKinEnergy, nbins, nbinsPerDecade, and PrintWarning().
Referenced by G4EmProcessOptions::SetDEDXBinning(), G4EmProcessOptions::SetLambdaBinning(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetNumberOfBinsPerDecade (G4int val)
Definition at line 925 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 925 of file G4EmParameters.cc
References G4lrint(), IsLocked(), maxKinEnergy, minKinEnergy, nbins, nbinsPerDecade, and PrintWarning().
Referenced by G4EmModelActivator::ActivateEmOptions(), DMXPhysicsList::DMXPhysicsList(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetOnIsolated (G4bool val)
Definition at line 496 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 496 of file G4EmParameters.cc
References IsLocked(), and onIsolated.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetPixe (G4bool val)
Definition at line 286 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 286 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetPixe().
Referenced by DMXPhysicsList::DMXPhysicsList(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), and G4EmProcessOptions::SetPIXE().
void G4EmParameters::SetPIXECrossSectionModel (const G4String & sss)
Definition at line 1024 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1024 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetPIXECrossSectionModel().
Referenced by G4EmProcessOptions::SetPIXECrossSectionModel().
void G4EmParameters::SetPIXEElectronCrossSectionModel (const G4String & sss)
Definition at line 1035 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1035 of file G4EmParameters.cc
References fCParameters, IsLocked(), and G4EmLowEParameters::SetPIXEElectronCrossSectionModel().
Referenced by G4EmPenelopePhysics::G4EmPenelopePhysics(), and G4EmProcessOptions::SetPIXEElectronCrossSectionModel().
void G4EmParameters::SetProcessBiasingFactor (const G4String & procname, G4double val, G4bool wflag)
Definition at line 1133 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1133 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetProcessBiasingFactor().
Referenced by G4EmProcessOptions::SetProcessBiasingFactor().
void G4EmParameters::SetQuantumEntanglement (G4bool v)
Definition at line 1176 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1176 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetQuantumEntanglement().
void G4EmParameters::SetRetrieveMuDataFromFile (G4bool v)
Definition at line 491 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 491 of file G4EmParameters.cc
References fMuDataFromFile, and v.
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetScreeningFactor (G4double val)
Definition at line 876 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 876 of file G4EmParameters.cc
References factorScreen, IsLocked(), and PrintWarning().
Referenced by G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetSpline (G4bool val)
Definition at line 209 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 209 of file G4EmParameters.cc
References IsLocked(), and spline.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetSplineFlag().
void G4EmParameters::SetStepFunction (G4double v1, G4double v2)
Definition at line 894 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 894 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetStepFunction().
Referenced by EICPhysicsList::EICPhysicsList(), ElectromagneticPhysics::ElectromagneticPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), and G4EmProcessOptions::SetStepFunction().
void G4EmParameters::SetStepFunctionMuHad (G4double v1, G4double v2)
Definition at line 900 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 900 of file G4EmParameters.cc
References fBParameters, IsLocked(), and G4EmExtraParameters::SetStepFunctionMuHad().
Referenced by EICPhysicsList::EICPhysicsList(), ElectromagneticPhysics::ElectromagneticPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), and G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI().
void G4EmParameters::SetSubCutoff (G4bool val, const G4String & region = "")
Definition at line 1118 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1118 of file G4EmParameters.cc
References fBParameters, gener, IsLocked(), and G4EmExtraParameters::SetSubCutoff().
Referenced by G4EmProcessOptions::SetSubCutoff().
void G4EmParameters::SetUseCutAsFinalRange (G4bool val)
Definition at line 220 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 220 of file G4EmParameters.cc
References cutAsFinalRange, and IsLocked().
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetUseCutAsFinalRange().
void G4EmParameters::SetUseICRU90Data (G4bool val)
Definition at line 416 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 416 of file G4EmParameters.cc
References fICRU90, and IsLocked().
Referenced by G4EmLowEPPhysics::G4EmLowEPPhysics(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetUseMottCorrection (G4bool val)
Definition at line 363 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 363 of file G4EmParameters.cc
References IsLocked(), and useMottCorrection.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), PhysListEmStandard_option4::PhysListEmStandard_option4(), and G4EmParametersMessenger::SetNewValue().
void G4EmParameters::SetVerbose (G4int val)
Definition at line 944 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 944 of file G4EmParameters.cc
References IsLocked(), min, verbose, and workerVerbose.
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), main(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmLivermore::PhysListEmLivermore(), PhysListEmPenelope::PhysListEmPenelope(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetVerbose().
void G4EmParameters::SetWorkerVerbose (G4int val)
Definition at line 956 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 956 of file G4EmParameters.cc
References IsLocked(), and workerVerbose.
Referenced by G4EmParametersMessenger::SetNewValue(), and G4EmProcessOptions::SetWorkerVerbose().
G4bool G4EmParameters::Spline () const
Definition at line 215 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 215 of file G4EmParameters.cc
References spline.
Referenced by G4VEnergyLossProcess::BuildDEDXTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4TablesForExtrapolator::Initialisation(), G4VEnergyLossProcess::LambdaPhysicsVector(), G4VEmProcess::LambdaPhysicsVector(), G4VEmProcess::PreparePhysicsTable(), G4LossTableManager::ResetParameters(), G4EmDataHandler::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrieveTable(), and G4VEnergyLossProcess::StreamInfo().
void G4EmParameters::StreamInfo (std::ostream & os) const
Definition at line 1219 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1219 of file G4EmParameters.cc
References applyCuts, G4EmLowEParameters::Auger(), G4EmLowEParameters::BeardenFluoDir(), birks, bremsTh, buildCSDARange, cutAsFinalRange, G4EmLowEParameters::DeexcitationIgnoreCut(), G4EmLowEParameters::DNAElectronMsc(), G4EmLowEParameters::DNAeSolvationSubType(), G4EmLowEParameters::DNAFast(), G4EmLowEParameters::DNAStationary(), energyLimit, factorForAngleLimit, factorScreen, fBParameters, fCParameters, fDNA, fICRU90, flagLPM, G4EmLowEParameters::Fluo(), fMuDataFromFile, fPolarisation, fSamplingTable, G4BestUnit, gener, geomFactor, G4EmExtraParameters::GetStepFunctionMuHadP1(), G4EmExtraParameters::GetStepFunctionMuHadP2(), G4EmExtraParameters::GetStepFunctionP1(), G4EmExtraParameters::GetStepFunctionP2(), CLHEP::GeV, integral, lambdaFactor, lambdaLimit, latDisplacementBeyondSafety, lateralDisplacement, lateralDisplacementAlg96, linLossLimit, lossFluctuation, lowestElectronEnergy, lowestMuHadEnergy, lowestTripletEnergy, max5DEnergyForMuPair, maxKinEnergy, maxKinEnergyCSDA, maxNIELEnergy, CLHEP::MeV, minKinEnergy, minSubRange, CLHEP::mm, mscStepLimit, mscStepLimitMuHad, muhadLateralDisplacement, nbins, nbinsPerDecade, nucFormfactor, onIsolated, G4EmLowEParameters::Pixe(), G4EmLowEParameters::PIXECrossSectionModel(), G4EmLowEParameters::PIXEElectronCrossSectionModel(), CLHEP::prec, G4EmExtraParameters::QuantumEntanglement(), CLHEP::rad, rangeFactor, rangeFactorMuHad, safetyFactor, skin, spline, thetaLimit, tripletConv, useAngGeneratorForIonisation, useMottCorrection, verbose, and workerVerbose.
Referenced by Dump(), and operator<<().
const std::vector< G4String > & G4EmParameters::TypesDNA () const
Definition at line 1097 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1097 of file G4EmParameters.cc
References fCParameters, and G4EmLowEParameters::TypesDNA().
Referenced by G4EmDNAPhysicsActivator::ConstructProcess().
const std::vector< G4String > & G4EmParameters::TypesPAI () const
Definition at line 1069 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1069 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::TypesPAI().
Referenced by G4EmModelActivator::ActivatePAI().
const std::vector< G4String > & G4EmParameters::TypesPhysics () const
Definition at line 1113 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1113 of file G4EmParameters.cc
References fBParameters, and G4EmExtraParameters::TypesPhysics().
Referenced by G4EmModelActivator::ActivateEmOptions().
G4bool G4EmParameters::UseAngularGeneratorForIonisation () const
Definition at line 358 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 358 of file G4EmParameters.cc
References useAngGeneratorForIonisation.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::UseCutAsFinalRange () const
Definition at line 226 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 226 of file G4EmParameters.cc
References cutAsFinalRange.
Referenced by G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4EmParameters::UseICRU90Data () const
Definition at line 422 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 422 of file G4EmParameters.cc
References fICRU90.
Referenced by G4IonParametrisedLossModel::Initialise().
G4bool G4EmParameters::UseMottCorrection () const
Definition at line 369 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 369 of file G4EmParameters.cc
References useMottCorrection.
G4int G4EmParameters::Verbose () const
Definition at line 951 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 951 of file G4EmParameters.cc
References verbose.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4EmModelActivator::ActivatePAI(), G4LossTableManager::G4LossTableManager(), G4BetheHeitler5DModel::Initialise(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4LossTableManager::ResetParameters(), and G4EmDataHandler::RetrievePhysicsTable().
G4int G4EmParameters::WorkerVerbose () const
Definition at line 962 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 962 of file G4EmParameters.cc
References workerVerbose.
Referenced by G4LossTableManager::G4LossTableManager(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4LossTableManager::ResetParameters().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4EmParameters & par) friend
Definition at line 1355 of file G4EmParameters.cc.
View newest version in sPHENIX GitHub at line 1355 of file G4EmParameters.cc
Member Data Documentation
G4bool G4EmParameters::applyCuts private
Definition at line 371 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 371 of file G4EmParameters.hh
Referenced by ApplyCuts(), Initialise(), SetApplyCuts(), and StreamInfo().
G4bool G4EmParameters::birks private
Definition at line 379 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 379 of file G4EmParameters.hh
Referenced by BirksActive(), Initialise(), SetBirksActive(), and StreamInfo().
G4double G4EmParameters::bremsTh private
Definition at line 397 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 397 of file G4EmParameters.hh
Referenced by BremsstrahlungTh(), Initialise(), SetBremsstrahlungTh(), and StreamInfo().
G4bool G4EmParameters::buildCSDARange private
Definition at line 367 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 367 of file G4EmParameters.hh
Referenced by BuildCSDARange(), Initialise(), SetBuildCSDARange(), and StreamInfo().
G4bool G4EmParameters::cutAsFinalRange private
Definition at line 370 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 370 of file G4EmParameters.hh
Referenced by Initialise(), SetUseCutAsFinalRange(), StreamInfo(), and UseCutAsFinalRange().
G4EmSaturation* G4EmParameters::emSaturation private
Definition at line 364 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 364 of file G4EmParameters.hh
Referenced by G4EmParameters(), GetEmSaturation(), SetBirksActive(), SetEmSaturation(), and ~G4EmParameters().
G4double G4EmParameters::energyLimit private
Definition at line 401 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 401 of file G4EmParameters.hh
Referenced by Initialise(), MscEnergyLimit(), SetMscEnergyLimit(), and StreamInfo().
G4double G4EmParameters::factorForAngleLimit private
Definition at line 399 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 399 of file G4EmParameters.hh
Referenced by FactorForAngleLimit(), Initialise(), SetFactorForAngleLimit(), and StreamInfo().
G4double G4EmParameters::factorScreen private
Definition at line 409 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 409 of file G4EmParameters.hh
Referenced by Initialise(), ScreeningFactor(), SetScreeningFactor(), and StreamInfo().
G4EmExtraParameters* G4EmParameters::fBParameters private
Definition at line 361 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 361 of file G4EmParameters.hh
Referenced by ActivateForcedInteraction(), ActivateSecondaryBiasing(), AddPAIModel(), AddPhysics(), DefineRegParamForEM(), DefineRegParamForLoss(), G4EmParameters(), GetDirectionalSplitting(), GetDirectionalSplittingRadius(), GetDirectionalSplittingTarget(), ParticlesPAI(), QuantumEntanglement(), RegionsPAI(), RegionsPhysics(), SetDefaults(), SetDirectionalSplitting(), SetDirectionalSplittingRadius(), SetDirectionalSplittingTarget(), SetGeneralProcessActive(), SetProcessBiasingFactor(), SetQuantumEntanglement(), SetStepFunction(), SetStepFunctionMuHad(), SetSubCutoff(), StreamInfo(), TypesPAI(), TypesPhysics(), and ~G4EmParameters().
G4EmLowEParameters* G4EmParameters::fCParameters private
Definition at line 362 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 362 of file G4EmParameters.hh
Referenced by AddDNA(), AddMicroElec(), Auger(), AugerCascade(), BeardenFluoDir(), DeexcitationIgnoreCut(), DefineRegParamForDeex(), DNAElectronMsc(), DNAeSolvationSubType(), DNAFast(), DNAStationary(), Fluo(), G4EmParameters(), Pixe(), PIXECrossSectionModel(), PIXEElectronCrossSectionModel(), RegionsDNA(), RegionsMicroElec(), SetAuger(), SetAugerCascade(), SetBeardenFluoDir(), SetDeexActiveRegion(), SetDeexcitationIgnoreCut(), SetDefaults(), SetDNAElectronMsc(), SetDNAeSolvationSubType(), SetDNAFast(), SetDNAStationary(), SetFluo(), SetPixe(), SetPIXECrossSectionModel(), SetPIXEElectronCrossSectionModel(), StreamInfo(), TypesDNA(), and ~G4EmParameters().
G4bool G4EmParameters::fDNA private
Definition at line 386 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 386 of file G4EmParameters.hh
Referenced by ActivateDNA(), Initialise(), and StreamInfo().
G4bool G4EmParameters::fICRU90 private
Definition at line 380 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 380 of file G4EmParameters.hh
Referenced by Initialise(), SetUseICRU90Data(), StreamInfo(), and UseICRU90Data().
G4bool G4EmParameters::flagLPM private
Definition at line 368 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 368 of file G4EmParameters.hh
Referenced by Initialise(), LPM(), SetLPM(), and StreamInfo().
G4bool G4EmParameters::fMuDataFromFile private
Definition at line 384 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 384 of file G4EmParameters.hh
Referenced by Initialise(), RetrieveMuDataFromFile(), SetRetrieveMuDataFromFile(), and StreamInfo().
G4bool G4EmParameters::fPolarisation private
Definition at line 383 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 383 of file G4EmParameters.hh
Referenced by EnablePolarisation(), Initialise(), SetEnablePolarisation(), and StreamInfo().
G4bool G4EmParameters::fSamplingTable private
Definition at line 382 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 382 of file G4EmParameters.hh
Referenced by EnableSamplingTable(), Initialise(), SetEnableSamplingTable(), and StreamInfo().
G4StateManager* G4EmParameters::fStateManager private
Definition at line 363 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 363 of file G4EmParameters.hh
Referenced by G4EmParameters(), and IsLocked().
G4bool G4EmParameters::gener private
Definition at line 381 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 381 of file G4EmParameters.hh
Referenced by ActivateForcedInteraction(), GeneralProcessActive(), Initialise(), SetGeneralProcessActive(), SetSubCutoff(), and StreamInfo().
G4double G4EmParameters::geomFactor private
Definition at line 405 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 405 of file G4EmParameters.hh
Referenced by Initialise(), MscGeomFactor(), SetMscGeomFactor(), and StreamInfo().
G4bool G4EmParameters::integral private
Definition at line 378 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 378 of file G4EmParameters.hh
Referenced by Initialise(), Integral(), SetIntegral(), and StreamInfo().
G4double G4EmParameters::lambdaFactor private
Definition at line 398 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 398 of file G4EmParameters.hh
Referenced by Initialise(), LambdaFactor(), SetLambdaFactor(), and StreamInfo().
G4double G4EmParameters::lambdaLimit private
Definition at line 407 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 407 of file G4EmParameters.hh
Referenced by Initialise(), MscLambdaLimit(), SetMscLambdaLimit(), and StreamInfo().
G4bool G4EmParameters::latDisplacementBeyondSafety private
Definition at line 375 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 375 of file G4EmParameters.hh
Referenced by Initialise(), LatDisplacementBeyondSafety(), SetLatDisplacementBeyondSafety(), and StreamInfo().
G4bool G4EmParameters::lateralDisplacement private
Definition at line 372 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 372 of file G4EmParameters.hh
Referenced by Initialise(), LateralDisplacement(), SetLateralDisplacement(), and StreamInfo().
G4bool G4EmParameters::lateralDisplacementAlg96 private
Definition at line 373 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 373 of file G4EmParameters.hh
Referenced by Initialise(), LateralDisplacementAlg96(), SetLateralDisplacementAlg96(), and StreamInfo().
G4double G4EmParameters::linLossLimit private
Definition at line 396 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 396 of file G4EmParameters.hh
Referenced by Initialise(), LinearLossLimit(), SetLinearLossLimit(), and StreamInfo().
G4bool G4EmParameters::lossFluctuation private
Definition at line 366 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 366 of file G4EmParameters.hh
Referenced by Initialise(), LossFluctuation(), SetLossFluctuations(), and StreamInfo().
G4double G4EmParameters::lowestElectronEnergy private
Definition at line 393 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 393 of file G4EmParameters.hh
Referenced by Initialise(), LowestElectronEnergy(), SetLowestElectronEnergy(), and StreamInfo().
G4double G4EmParameters::lowestMuHadEnergy private
Definition at line 394 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 394 of file G4EmParameters.hh
Referenced by Initialise(), LowestMuHadEnergy(), SetLowestMuHadEnergy(), and StreamInfo().
G4double G4EmParameters::lowestTripletEnergy private
Definition at line 395 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 395 of file G4EmParameters.hh
Referenced by Initialise(), LowestTripletEnergy(), SetLowestTripletEnergy(), and StreamInfo().
G4double G4EmParameters::max5DEnergyForMuPair private
Definition at line 392 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 392 of file G4EmParameters.hh
Referenced by Initialise(), MaxEnergyFor5DMuPair(), SetMaxEnergyFor5DMuPair(), and StreamInfo().
G4double G4EmParameters::maxKinEnergy private
Definition at line 390 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 390 of file G4EmParameters.hh
Referenced by Initialise(), MaxKinEnergy(), SetMaxEnergy(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
G4double G4EmParameters::maxKinEnergyCSDA private
Definition at line 391 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 391 of file G4EmParameters.hh
Referenced by Initialise(), MaxEnergyForCSDARange(), SetMaxEnergyForCSDARange(), and StreamInfo().
G4double G4EmParameters::maxNIELEnergy private
Definition at line 402 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 402 of file G4EmParameters.hh
Referenced by Initialise(), MaxNIELEnergy(), SetMaxNIELEnergy(), and StreamInfo().
G4double G4EmParameters::minKinEnergy private
Definition at line 389 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 389 of file G4EmParameters.hh
Referenced by Initialise(), MinKinEnergy(), SetMaxEnergy(), SetMaxEnergyForCSDARange(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
G4double G4EmParameters::minSubRange private
Definition at line 388 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 388 of file G4EmParameters.hh
Referenced by Initialise(), MinSubRange(), SetMinSubRange(), and StreamInfo().
G4MscStepLimitType G4EmParameters::mscStepLimit private
Definition at line 417 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 417 of file G4EmParameters.hh
Referenced by Initialise(), MscStepLimitType(), SetMscStepLimitType(), and StreamInfo().
G4MscStepLimitType G4EmParameters::mscStepLimitMuHad private
Definition at line 418 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 418 of file G4EmParameters.hh
Referenced by Initialise(), MscMuHadStepLimitType(), SetMscMuHadStepLimitType(), and StreamInfo().
G4bool G4EmParameters::muhadLateralDisplacement private
Definition at line 374 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 374 of file G4EmParameters.hh
Referenced by Initialise(), MuHadLateralDisplacement(), SetMuHadLateralDisplacement(), and StreamInfo().
G4int G4EmParameters::nbins private
Definition at line 411 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 411 of file G4EmParameters.hh
Referenced by Initialise(), NumberOfBins(), SetMaxEnergy(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
G4int G4EmParameters::nbinsPerDecade private
Definition at line 412 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 412 of file G4EmParameters.hh
Referenced by Initialise(), NumberOfBinsPerDecade(), SetMaxEnergy(), SetMinEnergy(), SetNumberOfBins(), SetNumberOfBinsPerDecade(), and StreamInfo().
G4NuclearFormfactorType G4EmParameters::nucFormfactor private
Definition at line 419 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 419 of file G4EmParameters.hh
Referenced by Initialise(), NuclearFormfactorType(), SetNuclearFormfactorType(), and StreamInfo().
G4bool G4EmParameters::onIsolated private
Definition at line 385 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 385 of file G4EmParameters.hh
Referenced by Initialise(), OnIsolated(), SetOnIsolated(), and StreamInfo().
G4double G4EmParameters::rangeFactor private
Definition at line 403 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 403 of file G4EmParameters.hh
Referenced by Initialise(), MscRangeFactor(), SetMscRangeFactor(), and StreamInfo().
G4double G4EmParameters::rangeFactorMuHad private
Definition at line 404 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 404 of file G4EmParameters.hh
Referenced by Initialise(), MscMuHadRangeFactor(), SetMscMuHadRangeFactor(), and StreamInfo().
G4double G4EmParameters::safetyFactor private
Definition at line 406 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 406 of file G4EmParameters.hh
Referenced by Initialise(), MscSafetyFactor(), SetMscSafetyFactor(), and StreamInfo().
G4double G4EmParameters::skin private
Definition at line 408 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 408 of file G4EmParameters.hh
Referenced by Initialise(), MscSkin(), SetMscSkin(), and StreamInfo().
G4bool G4EmParameters::spline private
Definition at line 369 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 369 of file G4EmParameters.hh
Referenced by Initialise(), SetSpline(), Spline(), and StreamInfo().
G4EmParameters * G4EmParameters::theInstance = nullptr static private
Definition at line 358 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 358 of file G4EmParameters.hh
Referenced by Instance().
G4EmParametersMessenger* G4EmParameters::theMessenger private
Definition at line 360 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 360 of file G4EmParameters.hh
Referenced by G4EmParameters(), and ~G4EmParameters().
G4double G4EmParameters::thetaLimit private
Definition at line 400 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 400 of file G4EmParameters.hh
Referenced by Initialise(), MscThetaLimit(), SetMscThetaLimit(), and StreamInfo().
G4int G4EmParameters::tripletConv private
Definition at line 415 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 415 of file G4EmParameters.hh
Referenced by GetConversionType(), Initialise(), SetConversionType(), and StreamInfo().
G4bool G4EmParameters::useAngGeneratorForIonisation private
Definition at line 376 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 376 of file G4EmParameters.hh
Referenced by ActivateAngularGeneratorForIonisation(), Initialise(), StreamInfo(), and UseAngularGeneratorForIonisation().
G4bool G4EmParameters::useMottCorrection private
Definition at line 377 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 377 of file G4EmParameters.hh
Referenced by Initialise(), SetUseMottCorrection(), StreamInfo(), and UseMottCorrection().
G4int G4EmParameters::verbose private
Definition at line 413 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 413 of file G4EmParameters.hh
Referenced by Initialise(), SetVerbose(), StreamInfo(), and Verbose().
G4int G4EmParameters::workerVerbose private
Definition at line 414 of file G4EmParameters.hh.
View newest version in sPHENIX GitHub at line 414 of file G4EmParameters.hh
Referenced by Initialise(), SetVerbose(), SetWorkerVerbose(), StreamInfo(), and WorkerVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmParameters.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmParameters.cc