ECCE @ EIC Software: RunActionMaster Class Reference
RunActionMaster Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/include/RunActionMaster.hh>
Public Member Functions
RunActionMaster ()
~RunActionMaster ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *arun)
virtual void EndOfRunAction (const G4Run *arun)
RunActionMaster (G4bool useNtuple, G4bool mergeNtuple)
~RunActionMaster ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *arun)
virtual void EndOfRunAction (const G4Run *arun)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4MPIntupleMerger * fMPIntupleMerger
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 35 of file RunActionMaster.hh.
View newest version in sPHENIX GitHub at line 35 of file RunActionMaster.hh
Constructor & Destructor Documentation
RunActionMaster::RunActionMaster ()
Definition at line 42 of file RunActionMaster.cc.
View newest version in sPHENIX GitHub at line 42 of file RunActionMaster.cc
RunActionMaster::~RunActionMaster ()
Definition at line 53 of file RunActionMaster.cc.
View newest version in sPHENIX GitHub at line 53 of file RunActionMaster.cc
RunActionMaster::RunActionMaster (G4bool useNtuple, G4bool mergeNtuple)
Definition at line 43 of file RunActionMaster.cc.
View newest version in sPHENIX GitHub at line 43 of file RunActionMaster.cc
References Analysis::Book(), fMPIntupleMerger, Analysis::GetAnalysis(), G4MPImanager::GetManager(), Analysis::SetMergeNtuple(), and Analysis::SetUseNtuple().
RunActionMaster::~RunActionMaster ()
Member Function Documentation
void RunActionMaster::BeginOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
Definition at line 59 of file RunActionMaster.cc.
View newest version in sPHENIX GitHub at line 59 of file RunActionMaster.cc
References Analysis::Book(), JA::Clear(), and Analysis::GetAnalysis().
virtual void RunActionMaster::BeginOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
void RunActionMaster::EndOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
Definition at line 68 of file RunActionMaster.cc.
View newest version in sPHENIX GitHub at line 68 of file RunActionMaster.cc
References Close(), e, test::fname, G4cout, G4endl, Analysis::GetAnalysis(), G4MPImanager::GetManager(), G4ScoringManager::GetScoringManager(), G4ScoringManager::GetScoringManagerIfExist(), incremental_prev_tag::idx, G4ToolsAnalysisManager::Instance(), it, m, G4VUserMPIrunMerger::Merge(), G4MPIhistoMerger::Merge(), G4MPIscorerMerger::Merge(), G4VUserMPIrunMerger::SetVerbosity(), G4MPIhistoMerger::SetVerbosity(), G4MPIscorerMerger::SetVerbosity(), and G4InuclParticleNames::sm.
virtual void RunActionMaster::EndOfRunAction (const G4Run * arun) virtual
Reimplemented from G4UserRunAction.
G4Run * RunActionMaster::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 47 of file RunActionMaster.cc.
View newest version in sPHENIX GitHub at line 47 of file RunActionMaster.cc
virtual G4Run* RunActionMaster::GenerateRun () virtual
Reimplemented from G4UserRunAction.
Member Data Documentation
G4MPIntupleMerger* RunActionMaster::fMPIntupleMerger private
Definition at line 47 of file RunActionMaster.hh.
View newest version in sPHENIX GitHub at line 47 of file RunActionMaster.hh
Referenced by RunActionMaster().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/include/RunActionMaster.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/include/RunActionMaster.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/src/RunActionMaster.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/src/RunActionMaster.cc