ECCE @ EIC Software: CexmcEventAction Class Reference
CexmcEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEventAction.hh>
Public Member Functions
CexmcEventAction (CexmcPhysicsManager *physicsManager, G4int verbose=0)
virtual ~CexmcEventAction ()
void BeginOfEventAction (const G4Event *event)
void EndOfEventAction (const G4Event *event)
void BeamParticleChangeHook (void)
void SetVerboseOnCexmcLevel (G4int value)
void SetVerboseDrawLevel (G4int value)
CexmcChargeExchangeReconstructor * GetReconstructor (void)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Static Public Member Functions
static CexmcEnergyDepositStore * MakeEnergyDepositStore (const CexmcEnergyDepositDigitizer *digitizer)
static CexmcTrackPointsStore * MakeTrackPointsStore (const CexmcTrackPointsDigitizer *digitizer)
static void PrintEnergyDeposit (const CexmcEnergyDepositStore *edStore)
static void PrintTrackPoints (const CexmcTrackPointsStore *tpStore)
static void PrintProductionModelData (const CexmcAngularRangeList &angularRanges, const CexmcProductionModelData &pmData)
Private Member Functions
void PrintReconstructedData (const CexmcAngularRangeList &angularRanges, const CexmcAngularRange &angularGap) const
void DrawTrajectories (const G4Event *event)
void DrawTrackPoints (const CexmcTrackPointsStore *tpStore) const
void DrawReconstructionData (void)
void UpdateRunHits (const CexmcAngularRangeList &aRangesReal, const CexmcAngularRangeList &aRangesRec, G4bool tpDigitizerHasTriggered, G4bool edDigitizerHasTriggered, G4bool edDigitizerMonitorHasTriggered, G4bool reconstructorHasTriggered, const CexmcAngularRange &aGap)
Private Attributes
CexmcPhysicsManager * physicsManager
CexmcChargeExchangeReconstructor * reconstructor
G4int verbose
G4int verboseDraw
CexmcEventActionMessenger * messenger
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 61 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 61 of file CexmcEventAction.hh
Constructor & Destructor Documentation
CexmcEventAction::CexmcEventAction (CexmcPhysicsManager * physicsManager, G4int verbose = 0) explicit
Definition at line 95 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 95 of file CexmcEventAction.cc
References G4DigiManager::AddNewModule(), CexmcEDDigitizerName, CexmcTPDigitizerName, G4DigiManager::GetDMpointer(), CexmcPhysicsManager::GetProductionModel(), messenger, physicsManager, and reconstructor.
CexmcEventAction::~CexmcEventAction () virtual
Definition at line 114 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 114 of file CexmcEventAction.cc
References messenger, and reconstructor.
Member Function Documentation
void CexmcEventAction::BeamParticleChangeHook (void)
Definition at line 121 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 121 of file CexmcEventAction.cc
References reconstructor, and CexmcChargeExchangeReconstructor::SetupBeamParticle().
Referenced by CexmcRunManager::BeamParticleChangeHook().
void CexmcEventAction::BeginOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 127 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 127 of file CexmcEventAction.cc
References CexmcTrackingAction::BeginOfEventAction(), G4RunManager::GetRunManager(), G4RunManager::GetUserTrackingAction(), physicsManager, and CexmcPhysicsManager::ResetNumberOfTriggeredStudiedInteractions().
void CexmcEventAction::DrawReconstructionData (void) private
Definition at line 649 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 649 of file CexmcEventAction.cc
References G4VisManager::Draw(), G4VMarker::filled, CexmcReconstructor::GetCalorimeterEPLeftWorldPosition(), CexmcReconstructor::GetCalorimeterEPRightWorldPosition(), G4VVisManager::GetConcreteInstance(), G4VisManager::GetCurrentGraphicsSystem(), CexmcReconstructor::GetTargetEPWorldPosition(), reconstructor, and G4VMarker::SetScreenSize().
Referenced by EndOfEventAction().
void CexmcEventAction::DrawTrackPoints (const CexmcTrackPointsStore * tpStore) const private
Definition at line 591 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 591 of file CexmcEventAction.cc
References CexmcTrackPointsStore::calorimeterTPLeft, CexmcTrackPointsStore::calorimeterTPRight, G4VisManager::Draw(), G4VMarker::filled, G4VVisManager::GetConcreteInstance(), G4VisManager::GetCurrentGraphicsSystem(), CexmcTrackPointInfo::IsValid(), CexmcTrackPointsStore::monitorTP, CexmcTrackPointInfo::positionWorld, G4VMarker::SetFillStyle(), G4VMarker::SetPosition(), G4VMarker::SetScreenSize(), G4Visible::SetVisAttributes(), CexmcTrackPointsStore::targetTPBeamParticle, CexmcTrackPointsStore::targetTPOutputParticle, CexmcTrackPointsStore::vetoCounterTPLeft, and CexmcTrackPointsStore::vetoCounterTPRight.
Referenced by EndOfEventAction().
void CexmcEventAction::DrawTrajectories (const G4Event * event) private
Definition at line 568 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 568 of file CexmcEventAction.cc
References G4VTrajectory::DrawTrajectory(), G4TrajectoryContainer::entries(), G4VVisManager::GetConcreteInstance(), G4VisManager::GetCurrentGraphicsSystem(), and G4Event::GetTrajectoryContainer().
Referenced by EndOfEventAction().
void CexmcEventAction::EndOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 803 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 803 of file CexmcEventAction.cc
References CexmcEDDigitizerName, CexmcTPDigitizerName, CexmcWeirdException, CLHEP::HepLorentzVector::cosTheta(), CexmcTrackPointsDigitizer::Digitize(), CexmcEnergyDepositDigitizer::Digitize(), DrawReconstructionData(), DrawTrackPoints(), DrawTrajectories(), e, CexmcEventInfo::EdTriggerIsOk(), G4cout, G4endl, GetAngularGaps(), G4DigiManager::GetDMpointer(), G4ParticleDefinition::GetPDGMass(), CexmcPhysicsManager::GetProductionModel(), CexmcChargeExchangeReconstructor::GetProductionModelData(), G4Event::GetUserInformation(), CexmcReconstructor::HasBasicTrigger(), CexmcChargeExchangeReconstructor::HasFullTrigger(), CexmcTrackPointsDigitizer::HasTriggered(), CexmcEnergyDepositDigitizer::HasTriggered(), CexmcTrackPointInfo::IsValid(), k, MakeEnergyDepositStore(), MakeTrackPointsStore(), CexmcTrackPointInfo::momentumAmp, CexmcEnergyDepositDigitizer::MonitorHasTriggered(), CexmcProductionModelData::outputParticleSCM, CexmcTrackPointInfo::particle, physicsManager, PrintEnergyDeposit(), PrintProductionModelData(), PrintReconstructedData(), PrintTrackPoints(), CexmcChargeExchangeReconstructor::Reconstruct(), reconstructor, G4Event::SetUserInformation(), CexmcTrackPointsStore::targetTPOutputParticle, UpdateRunHits(), verbose, verboseDraw, and CexmcException::what().
CexmcChargeExchangeReconstructor * CexmcEventAction::GetReconstructor (void) inline
Definition at line 179 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 179 of file CexmcEventAction.hh
References reconstructor.
CexmcEnergyDepositStore * CexmcEventAction::MakeEnergyDepositStore (const CexmcEnergyDepositDigitizer * digitizer) static
Definition at line 140 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 140 of file CexmcEventAction.cc
References CexmcEnergyDepositDigitizer::GetCalorimeterEDLeft(), CexmcEnergyDepositDigitizer::GetCalorimeterEDLeftCollection(), CexmcEnergyDepositDigitizer::GetCalorimeterEDLeftMaxX(), CexmcEnergyDepositDigitizer::GetCalorimeterEDLeftMaxY(), CexmcEnergyDepositDigitizer::GetCalorimeterEDRight(), CexmcEnergyDepositDigitizer::GetCalorimeterEDRightCollection(), CexmcEnergyDepositDigitizer::GetCalorimeterEDRightMaxX(), CexmcEnergyDepositDigitizer::GetCalorimeterEDRightMaxY(), CexmcEnergyDepositDigitizer::GetMonitorED(), CexmcEnergyDepositDigitizer::GetVetoCounterEDLeft(), and CexmcEnergyDepositDigitizer::GetVetoCounterEDRight().
Referenced by EndOfEventAction().
CexmcTrackPointsStore * CexmcEventAction::MakeTrackPointsStore (const CexmcTrackPointsDigitizer * digitizer) static
Definition at line 169 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 169 of file CexmcEventAction.cc
References CexmcTrackPointsDigitizer::GetCalorimeterTPLeft(), CexmcTrackPointsDigitizer::GetCalorimeterTPRight(), CexmcTrackPointsDigitizer::GetMonitorTP(), CexmcTrackPointsDigitizer::GetTargetTPBeamParticle(), CexmcTrackPointsDigitizer::GetTargetTPNucleusParticle(), CexmcTrackPointsDigitizer::GetTargetTPOutputParticle(), CexmcTrackPointsDigitizer::GetVetoCounterTPLeft(), and CexmcTrackPointsDigitizer::GetVetoCounterTPRight().
Referenced by EndOfEventAction().
void CexmcEventAction::PrintEnergyDeposit (const CexmcEnergyDepositStore * edStore) static
Definition at line 214 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 214 of file CexmcEventAction.cc
References CexmcEnergyDepositStore::calorimeterEDLeft, CexmcEnergyDepositStore::calorimeterEDLeftCollection, CexmcEnergyDepositStore::calorimeterEDRight, CexmcEnergyDepositStore::calorimeterEDRightCollection, G4BestUnit, G4cout, G4endl, CexmcEnergyDepositStore::monitorED, CexmcEnergyDepositStore::vetoCounterEDLeft, and CexmcEnergyDepositStore::vetoCounterEDRight.
Referenced by EndOfEventAction().
void CexmcEventAction::PrintProductionModelData (const CexmcAngularRangeList & angularRanges, const CexmcProductionModelData & pmData) static
Definition at line 263 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 263 of file CexmcEventAction.cc
References G4cout.
Referenced by EndOfEventAction().
void CexmcEventAction::PrintReconstructedData (const CexmcAngularRangeList & angularRanges, const CexmcAngularRange & angularGap) const private
Definition at line 272 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 272 of file CexmcEventAction.cc
References deg, G4BestUnit, G4cout, G4endl, CexmcReconstructor::GetCalorimeterEPLeftPosition(), CexmcReconstructor::GetCalorimeterEPRightPosition(), CexmcChargeExchangeReconstructor::GetNucleusOutputParticleMass(), CexmcChargeExchangeReconstructor::GetOutputParticleMass(), CexmcChargeExchangeReconstructor::GetProductionModelData(), CexmcReconstructor::GetTargetEPPosition(), CexmcReconstructor::GetTheAngle(), CexmcChargeExchangeReconstructor::HasAbsorbedEnergyCutTriggered(), CexmcChargeExchangeReconstructor::HasMassCutTriggered(), CexmcChargeExchangeReconstructor::IsAbsorbedEnergyCutUsed(), CexmcChargeExchangeReconstructor::IsMassCutUsed(), and reconstructor.
Referenced by EndOfEventAction().
void CexmcEventAction::PrintTrackPoints (const CexmcTrackPointsStore * tpStore) static
Definition at line 233 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 233 of file CexmcEventAction.cc
References angle, CexmcTrackPointsStore::calorimeterTPLeft, CexmcTrackPointsStore::calorimeterTPRight, deg, CexmcTrackPointInfo::directionWorld, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), CexmcTrackPointsStore::monitorTP, CexmcTrackPointInfo::particle, CexmcTrackPointsStore::targetTPBeamParticle, CexmcTrackPointsStore::targetTPNucleusParticle, CexmcTrackPointsStore::targetTPOutputParticle, CexmcTrackPointsStore::targetTPOutputParticleDecayProductParticle1, CexmcTrackPointsStore::targetTPOutputParticleDecayProductParticle2, CexmcTrackPointsStore::vetoCounterTPLeft, and CexmcTrackPointsStore::vetoCounterTPRight.
Referenced by EndOfEventAction().
void CexmcEventAction::SetVerboseDrawLevel (G4int value) inline
Definition at line 172 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 172 of file CexmcEventAction.hh
References verboseDraw.
Referenced by CexmcEventActionMessenger::SetNewValue().
void CexmcEventAction::SetVerboseOnCexmcLevel (G4int value) inline
Definition at line 166 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 166 of file CexmcEventAction.hh
References verbose.
Referenced by CexmcEventActionMessenger::SetNewValue().
void CexmcEventAction::UpdateRunHits (const CexmcAngularRangeList & aRangesReal, const CexmcAngularRangeList & aRangesRec, G4bool tpDigitizerHasTriggered, G4bool edDigitizerHasTriggered, G4bool edDigitizerMonitorHasTriggered, G4bool reconstructorHasTriggered, const CexmcAngularRange & aGap) private
Definition at line 672 of file CexmcEventAction.cc.
View newest version in sPHENIX GitHub at line 672 of file CexmcEventAction.cc
References G4RunManager::GetCurrentRun(), G4RunManager::GetRunManager(), CexmcRun::IncrementNmbOfFalseHitsTriggeredEDT(), CexmcRun::IncrementNmbOfFalseHitsTriggeredRec(), CexmcRun::IncrementNmbOfHitsSampled(), CexmcRun::IncrementNmbOfHitsSampledFull(), CexmcRun::IncrementNmbOfHitsTriggeredRealRange(), CexmcRun::IncrementNmbOfHitsTriggeredRecRange(), CexmcRun::IncrementNmbOfOrphanHits(), CexmcAngularRange::index, and k.
Referenced by EndOfEventAction().
Member Data Documentation
CexmcEventActionMessenger* CexmcEventAction::messenger private
Definition at line 162 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 162 of file CexmcEventAction.hh
Referenced by CexmcEventAction(), and ~CexmcEventAction().
CexmcPhysicsManager* CexmcEventAction::physicsManager private
Definition at line 149 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 149 of file CexmcEventAction.hh
Referenced by BeginOfEventAction(), CexmcEventAction(), and EndOfEventAction().
CexmcChargeExchangeReconstructor* CexmcEventAction::reconstructor private
Definition at line 151 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 151 of file CexmcEventAction.hh
Referenced by BeamParticleChangeHook(), CexmcEventAction(), DrawReconstructionData(), EndOfEventAction(), GetReconstructor(), PrintReconstructedData(), and ~CexmcEventAction().
G4int CexmcEventAction::verbose private
Definition at line 158 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 158 of file CexmcEventAction.hh
Referenced by EndOfEventAction(), and SetVerboseOnCexmcLevel().
G4int CexmcEventAction::verboseDraw private
Definition at line 160 of file CexmcEventAction.hh.
View newest version in sPHENIX GitHub at line 160 of file CexmcEventAction.hh
Referenced by EndOfEventAction(), and SetVerboseDrawLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcEventAction.cc