ECCE @ EIC Software: G4VCrossSectionDataSet Class Reference
G4VCrossSectionDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4VCrossSectionDataSet.hh>
Inherited by CexmcFakeCrossSectionData, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4BGGPionElasticXS, G4BGGPionInelasticXS, G4ChipsAntiBaryonElasticXS, G4ChipsAntiBaryonInelasticXS, G4ChipsHyperonElasticXS, G4ChipsHyperonInelasticXS, G4ChipsKaonMinusElasticXS, G4ChipsKaonMinusInelasticXS, G4ChipsKaonPlusElasticXS, G4ChipsKaonPlusInelasticXS, G4ChipsKaonZeroElasticXS, G4ChipsKaonZeroInelasticXS, G4ChipsNeutronElasticXS, G4ChipsNeutronInelasticXS, G4ChipsPionMinusElasticXS, G4ChipsPionMinusInelasticXS, G4ChipsPionPlusElasticXS, G4ChipsPionPlusInelasticXS, G4ChipsProtonElasticXS, G4ChipsProtonInelasticXS, G4CrossSectionElastic, G4CrossSectionInelastic, G4CrossSectionPairGG, G4ElectroNuclearCrossSection, G4EMDissociationCrossSection, G4GeneralSpaceNNCrossSection, G4HadronCaptureDataSet, G4HadronElasticDataSet, G4HadronFissionDataSet, G4HadronInelasticDataSet, G4IonProtonCrossSection, G4IonsKoxCrossSection, G4IonsShenCrossSection, G4IonsSihverCrossSection, G4KokoulinMuonNuclearXS, G4LENDCrossSection, G4MuNeutrinoNucleusTotXsc, G4NeutrinoElectronCcXsc, G4NeutrinoElectronNcXsc, G4NeutrinoElectronTotXsc, G4NeutronCaptureXS, G4NeutronElasticXS, G4NeutronElectronElXsc, G4NeutronInelasticCrossSection, G4NeutronInelasticXS, G4NucleonNuclearCrossSection, G4ParticleHPCaptureData, G4ParticleHPElasticData, G4ParticleHPFissionData, G4ParticleHPInelasticData, G4ParticleHPJENDLHEData, G4ParticleHPThermalScatteringData, G4ParticleInelasticXS, G4PhotoNuclearCrossSection, G4PiNuclearCrossSection, G4ProtonInelasticCrossSection, G4TripathiCrossSection, G4TripathiLightCrossSection, G4UPiNuclearCrossSection, and G4ZeroXS.
Public Member Functions
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Protected Member Functions
void SetName (const G4String &)
Protected Attributes
G4int verboseLevel
Private Member Functions
G4VCrossSectionDataSet & operator= (const G4VCrossSectionDataSet &right)
G4VCrossSectionDataSet (const G4VCrossSectionDataSet &)
Private Attributes
G4CrossSectionDataSetRegistry * registry
G4double minKinEnergy
G4double maxKinEnergy
G4bool isForAllAtomsAndEnergies
G4String name
Detailed Description
Definition at line 69 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VCrossSectionDataSet.hh
Constructor & Destructor Documentation
G4VCrossSectionDataSet::G4VCrossSectionDataSet (const G4String & nam = "")
Definition at line 49 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VCrossSectionDataSet.cc
References G4CrossSectionDataSetRegistry::Instance(), G4CrossSectionDataSetRegistry::Register(), and registry.
G4VCrossSectionDataSet::~G4VCrossSectionDataSet () virtual
Definition at line 58 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VCrossSectionDataSet.cc
References G4CrossSectionDataSetRegistry::DeRegister(), and registry.
G4VCrossSectionDataSet::G4VCrossSectionDataSet (const G4VCrossSectionDataSet &) private
Member Function Documentation
void G4VCrossSectionDataSet::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented in G4ParticleHPThermalScatteringData, G4BGGPionInelasticXS, G4BGGPionElasticXS, G4NeutronCaptureXS, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4NeutronElasticXS, G4NeutronInelasticXS, G4ParticleInelasticXS, G4LENDCrossSection, G4ParticleHPInelasticData, G4CrossSectionElastic, G4CrossSectionInelastic, G4ParticleHPElasticData, G4ParticleHPCaptureData, G4IonProtonCrossSection, G4ParticleHPFissionData, CexmcFakeCrossSectionData, G4CrossSectionPairGG, G4KokoulinMuonNuclearXS, G4ParticleHPJENDLHEData, G4UPiNuclearCrossSection, G4NucleonNuclearCrossSection, G4PiNuclearCrossSection, G4LENDCombinedCrossSection, and G4LENDGammaCrossSection.
Definition at line 171 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 171 of file G4VCrossSectionDataSet.cc
Referenced by G4CrossSectionPairGG::BuildPhysicsTable().
G4double G4VCrossSectionDataSet::ComputeCrossSection (const G4DynamicParticle * part, const G4Element * elm, const G4Material * mat = nullptr)
Definition at line 81 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 81 of file G4VCrossSectionDataSet.cc
References A(), GetElementCrossSection(), GetIsoCrossSection(), G4Element::GetIsotopeVector(), G4Isotope::GetN(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZasInt(), IsElementApplicable(), IsIsoApplicable(), and Z.
Referenced by GetCrossSection().
void G4VCrossSectionDataSet::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented in G4GeneralSpaceNNCrossSection, G4ParticleHPThermalScatteringData, G4ParticleHPInelasticData, G4BGGPionInelasticXS, G4BGGPionElasticXS, G4NeutronCaptureXS, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4NeutronElasticXS, G4NeutronInelasticXS, G4ParticleInelasticXS, G4ParticleHPCaptureData, G4ParticleHPElasticData, G4CrossSectionElastic, G4CrossSectionInelastic, G4ParticleHPFissionData, G4IonProtonCrossSection, G4IonsShenCrossSection, G4ZeroXS, G4UPiNuclearCrossSection, G4ElectroNuclearCrossSection, G4IonsKoxCrossSection, G4IonsSihverCrossSection, G4NucleonNuclearCrossSection, G4ChipsKaonZeroElasticXS, G4ChipsKaonZeroInelasticXS, G4KokoulinMuonNuclearXS, G4NeutronInelasticCrossSection, G4ChipsPionPlusInelasticXS, G4CrossSectionPairGG, G4ChipsKaonPlusInelasticXS, G4ChipsAntiBaryonElasticXS, G4ChipsKaonMinusElasticXS, G4ChipsNeutronElasticXS, G4ChipsNeutronInelasticXS, G4ChipsPionMinusElasticXS, G4ChipsPionMinusInelasticXS, G4PiNuclearCrossSection, G4ChipsHyperonElasticXS, G4ChipsHyperonInelasticXS, G4ChipsKaonMinusInelasticXS, G4ChipsKaonPlusElasticXS, G4ChipsPionPlusElasticXS, G4ChipsProtonElasticXS, G4ChipsProtonInelasticXS, G4HadronCaptureDataSet, G4ChipsAntiBaryonInelasticXS, G4HadronElasticDataSet, G4HadronInelasticDataSet, G4HadronFissionDataSet, and G4PhotoNuclearCrossSection.
Definition at line 177 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 177 of file G4VCrossSectionDataSet.cc
Referenced by G4CrossSectionDataStore::PrintCrossSectionHtml().
void G4VCrossSectionDataSet::DumpPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented in G4ParticleHPThermalScatteringData, G4LENDCrossSection, G4CrossSectionElastic, G4CrossSectionInelastic, G4ParticleHPInelasticData, G4ParticleHPElasticData, G4ParticleHPCaptureData, G4ParticleHPFissionData, CexmcFakeCrossSectionData, G4CrossSectionPairGG, G4ParticleHPJENDLHEData, and G4UPiNuclearCrossSection.
Definition at line 174 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 174 of file G4VCrossSectionDataSet.cc
bool G4VCrossSectionDataSet::ForAllAtomsAndEnergies () const inline
Definition at line 231 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 231 of file G4VCrossSectionDataSet.hh
References isForAllAtomsAndEnergies.
Referenced by G4CrossSectionDataStore::AddDataSet().
G4double G4VCrossSectionDataSet::GetCrossSection (const G4DynamicParticle * dp, const G4Element * elm, const G4Material * mat = nullptr) inline
Definition at line 188 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 188 of file G4VCrossSectionDataSet.hh
References ComputeCrossSection().
G4double G4VCrossSectionDataSet::GetElementCrossSection (const G4DynamicParticle * dynPart, G4int Z, const G4Material * mat = nullptr) virtual
Reimplemented in G4GeneralSpaceNNCrossSection, G4TripathiLightCrossSection, G4EMDissociationCrossSection, G4BGGPionInelasticXS, G4BGGPionElasticXS, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4CrossSectionElastic, G4CrossSectionInelastic, G4NeutronCaptureXS, G4NeutronElasticXS, G4NeutronInelasticXS, G4ParticleInelasticXS, G4IonProtonCrossSection, G4ElectroNuclearCrossSection, G4PhotoNuclearCrossSection, G4ZeroXS, G4CrossSectionPairGG, G4KokoulinMuonNuclearXS, G4ProtonInelasticCrossSection, G4IonsShenCrossSection, G4HadronCaptureDataSet, G4HadronElasticDataSet, G4HadronInelasticDataSet, G4IonsKoxCrossSection, G4IonsSihverCrossSection, G4NeutronElectronElXsc, G4HadronFissionDataSet, G4MuNeutrinoNucleusTotXsc, G4NucleonNuclearCrossSection, G4NeutronInelasticCrossSection, G4NeutrinoElectronTotXsc, G4TripathiCrossSection, G4NeutrinoElectronCcXsc, G4NeutrinoElectronNcXsc, and G4PiNuclearCrossSection.
Definition at line 114 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 114 of file G4VCrossSectionDataSet.cc
References FatalException, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), and MeV.
Referenced by G4CrossSectionPairGG::BuildPhysicsTable(), ComputeCrossSection(), and G4CrossSectionPairGG::GetElementCrossSection().
G4double G4VCrossSectionDataSet::GetIsoCrossSection (const G4DynamicParticle * dynPart, G4int Z, G4int A, const G4Isotope * iso = nullptr, const G4Element * elm = nullptr, const G4Material * mat = nullptr) virtual
Reimplemented in G4BGGPionInelasticXS, G4BGGPionElasticXS, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4NeutronCaptureXS, G4LENDCrossSection, G4NeutronElasticXS, G4NeutronInelasticXS, G4ParticleInelasticXS, G4ParticleHPThermalScatteringData, G4ChipsKaonZeroElasticXS, G4ChipsKaonZeroInelasticXS, G4IonsShenCrossSection, G4ParticleHPInelasticData, G4ChipsNeutronInelasticXS, G4ChipsPionPlusInelasticXS, G4ParticleHPElasticData, G4ChipsKaonPlusInelasticXS, G4ParticleHPCaptureData, G4ChipsAntiBaryonElasticXS, G4ChipsKaonMinusElasticXS, G4ChipsNeutronElasticXS, G4ChipsPionMinusElasticXS, G4ChipsPionMinusInelasticXS, G4ChipsHyperonElasticXS, G4ChipsHyperonInelasticXS, G4ChipsKaonMinusInelasticXS, G4ChipsKaonPlusElasticXS, G4ChipsPionPlusElasticXS, G4PhotoNuclearCrossSection, G4ChipsProtonElasticXS, G4ChipsProtonInelasticXS, G4ParticleHPFissionData, G4ChipsAntiBaryonInelasticXS, G4MuNeutrinoNucleusTotXsc, G4LENDGammaCrossSection, and G4LENDCombinedCrossSection.
Definition at line 130 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 130 of file G4VCrossSectionDataSet.cc
References FatalException, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4Element::GetName(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), and MeV.
Referenced by G4QMDReaction::ApplyYourself(), and ComputeCrossSection().
G4double G4VCrossSectionDataSet::GetMaxKinEnergy () const inline
Definition at line 221 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 221 of file G4VCrossSectionDataSet.hh
References maxKinEnergy.
Referenced by G4CrossSectionElastic::IsElementApplicable(), G4CrossSectionInelastic::IsElementApplicable(), G4ParticleHPFissionData::IsIsoApplicable(), G4ParticleHPCaptureData::IsIsoApplicable(), G4ParticleHPElasticData::IsIsoApplicable(), G4ParticleHPInelasticData::IsIsoApplicable(), and G4LENDCrossSection::IsIsoApplicable().
G4double G4VCrossSectionDataSet::GetMinKinEnergy () const inline
Definition at line 211 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 211 of file G4VCrossSectionDataSet.hh
References minKinEnergy.
Referenced by G4CrossSectionElastic::IsElementApplicable(), G4CrossSectionInelastic::IsElementApplicable(), G4ParticleHPFissionData::IsIsoApplicable(), G4ParticleHPCaptureData::IsIsoApplicable(), G4ParticleHPElasticData::IsIsoApplicable(), G4ParticleHPInelasticData::IsIsoApplicable(), and G4LENDCrossSection::IsIsoApplicable().
const G4String & G4VCrossSectionDataSet::GetName (void) const inline
Definition at line 226 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 226 of file G4VCrossSectionDataSet.hh
References name.
Referenced by G4CrossSectionPairGG::BuildPhysicsTable(), G4LENDCrossSection::DumpLENDTargetInfo(), G4CrossSectionPairGG::DumpPhysicsTable(), G4LENDCrossSection::DumpPhysicsTable(), G4LENDCrossSection::GetIsoCrossSection(), and G4CrossSectionDataStore::PrintCrossSectionHtml().
G4int G4VCrossSectionDataSet::GetVerboseLevel () const inline virtual
Reimplemented in G4ParticleHPInelasticData, G4ParticleHPElasticData, G4ParticleHPCaptureData, and G4ParticleHPFissionData.
Definition at line 196 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 196 of file G4VCrossSectionDataSet.hh
References verboseLevel.
G4bool G4VCrossSectionDataSet::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material * mat = nullptr) virtual
Reimplemented in G4GeneralSpaceNNCrossSection, G4TripathiLightCrossSection, G4EMDissociationCrossSection, G4ParticleHPBGGNucleonInelasticXS, G4BGGPionInelasticXS, G4BGGPionElasticXS, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4CrossSectionElastic, G4CrossSectionInelastic, G4NeutronCaptureXS, G4ElectroNuclearCrossSection, G4NeutronElasticXS, G4NeutronInelasticXS, G4ParticleInelasticXS, G4IonProtonCrossSection, G4KokoulinMuonNuclearXS, G4ZeroXS, G4CrossSectionPairGG, G4ProtonInelasticCrossSection, G4IonsShenCrossSection, G4HadronCaptureDataSet, G4PhotoNuclearCrossSection, G4HadronElasticDataSet, G4HadronInelasticDataSet, G4IonsKoxCrossSection, G4IonsSihverCrossSection, G4HadronFissionDataSet, G4NeutronElectronElXsc, G4NucleonNuclearCrossSection, G4UPiNuclearCrossSection, G4MuNeutrinoNucleusTotXsc, G4NeutronInelasticCrossSection, G4TripathiCrossSection, G4NeutrinoElectronTotXsc, G4NeutrinoElectronCcXsc, G4PiNuclearCrossSection, and G4NeutrinoElectronNcXsc.
Definition at line 64 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VCrossSectionDataSet.cc
Referenced by G4CrossSectionPairGG::BuildPhysicsTable(), ComputeCrossSection(), and G4CrossSectionPairGG::IsElementApplicable().
G4bool G4VCrossSectionDataSet::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * elm = nullptr, const G4Material * mat = nullptr) virtual
Reimplemented in G4LENDCrossSection, G4ParticleHPBGGNucleonInelasticXS, G4BGGPionInelasticXS, G4BGGPionElasticXS, G4BGGNucleonElasticXS, G4BGGNucleonInelasticXS, G4NeutronCaptureXS, G4NeutronElasticXS, G4NeutronInelasticXS, G4ParticleInelasticXS, G4ParticleHPThermalScatteringData, G4ChipsKaonZeroElasticXS, G4ChipsKaonZeroInelasticXS, G4ParticleHPInelasticData, G4ChipsNeutronInelasticXS, G4ChipsPionPlusInelasticXS, G4ParticleHPElasticData, G4ChipsKaonPlusInelasticXS, G4ParticleHPCaptureData, G4ChipsAntiBaryonElasticXS, G4ChipsKaonMinusElasticXS, G4ChipsNeutronElasticXS, G4ChipsPionMinusElasticXS, G4ChipsPionMinusInelasticXS, G4ChipsHyperonElasticXS, G4ChipsHyperonInelasticXS, G4ChipsKaonMinusInelasticXS, G4ChipsKaonPlusElasticXS, G4ChipsPionPlusElasticXS, G4ChipsProtonElasticXS, G4ChipsProtonInelasticXS, G4ParticleHPFissionData, G4ChipsAntiBaryonInelasticXS, G4PhotoNuclearCrossSection, and G4MuNeutrinoNucleusTotXsc.
Definition at line 72 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VCrossSectionDataSet.cc
Referenced by ComputeCrossSection().
G4VCrossSectionDataSet& G4VCrossSectionDataSet::operator= (const G4VCrossSectionDataSet & right) private
const G4Isotope * G4VCrossSectionDataSet::SelectIsotope (const G4Element * anElement, G4double kinEnergy, G4double logE) virtual
Reimplemented in G4NeutronCaptureXS, G4NeutronElasticXS, G4NeutronInelasticXS, and G4ParticleInelasticXS.
Definition at line 149 of file G4VCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 149 of file G4VCrossSectionDataSet.cc
References G4UniformRand, G4Element::GetIsotope(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), and sum.
void G4VCrossSectionDataSet::SetForAllAtomsAndEnergies (G4bool val) inline
Definition at line 236 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 236 of file G4VCrossSectionDataSet.hh
References isForAllAtomsAndEnergies.
Referenced by G4BGGNucleonElasticXS::G4BGGNucleonElasticXS(), G4BGGNucleonInelasticXS::G4BGGNucleonInelasticXS(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4ElectroNuclearCrossSection::G4ElectroNuclearCrossSection(), G4NeutronElasticXS::G4NeutronElasticXS(), G4NeutronInelasticXS::G4NeutronInelasticXS(), G4ParticleInelasticXS::G4ParticleInelasticXS(), and G4PhotoNuclearCrossSection::G4PhotoNuclearCrossSection().
void G4VCrossSectionDataSet::SetMaxKinEnergy (G4double value) inline
Definition at line 216 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 216 of file G4VCrossSectionDataSet.hh
References maxKinEnergy.
Referenced by G4AlphaPHPBuilder::Build(), G4ProtonPHPBuilder::Build(), G4He3PHPBuilder::Build(), G4DeuteronPHPBuilder::Build(), G4TritonPHPBuilder::Build(), G4CrossSectionElastic::BuildPhysicsTable(), G4CrossSectionInelastic::BuildPhysicsTable(), G4IonPhysicsPHP::ConstructProcess(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4CrossSectionElastic::G4CrossSectionElastic(), G4CrossSectionInelastic::G4CrossSectionInelastic(), G4LENDCrossSection::G4LENDCrossSection(), G4ParticleHPCaptureData::G4ParticleHPCaptureData(), G4ParticleHPElasticData::G4ParticleHPElasticData(), G4ParticleHPFissionData::G4ParticleHPFissionData(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4ParticleHPThermalScatteringData::G4ParticleHPThermalScatteringData(), and G4PiNuclearCrossSection::G4PiNuclearCrossSection().
void G4VCrossSectionDataSet::SetMinKinEnergy (G4double value) inline
Definition at line 206 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 206 of file G4VCrossSectionDataSet.hh
References minKinEnergy.
Referenced by G4AlphaPHPBuilder::Build(), G4ProtonPHPBuilder::Build(), G4He3PHPBuilder::Build(), G4DeuteronPHPBuilder::Build(), G4TritonPHPBuilder::Build(), IonPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4CrossSectionElastic::G4CrossSectionElastic(), G4CrossSectionInelastic::G4CrossSectionInelastic(), G4LENDCrossSection::G4LENDCrossSection(), G4ParticleHPCaptureData::G4ParticleHPCaptureData(), G4ParticleHPElasticData::G4ParticleHPElasticData(), G4ParticleHPFissionData::G4ParticleHPFissionData(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4ParticleHPThermalScatteringData::G4ParticleHPThermalScatteringData(), and G4PiNuclearCrossSection::G4PiNuclearCrossSection().
void G4VCrossSectionDataSet::SetName (const G4String & nam) inline protected
Definition at line 241 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 241 of file G4VCrossSectionDataSet.hh
Referenced by G4ParticleHPInelasticData::G4ParticleHPInelasticData().
void G4VCrossSectionDataSet::SetVerboseLevel (G4int value) inline virtual
Reimplemented in G4ParticleHPInelasticData, G4ParticleHPCaptureData, G4ParticleHPElasticData, and G4ParticleHPFissionData.
Definition at line 201 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 201 of file G4VCrossSectionDataSet.hh
References verboseLevel.
Member Data Documentation
G4bool G4VCrossSectionDataSet::isForAllAtomsAndEnergies private
Definition at line 182 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 182 of file G4VCrossSectionDataSet.hh
Referenced by ForAllAtomsAndEnergies(), and SetForAllAtomsAndEnergies().
G4double G4VCrossSectionDataSet::maxKinEnergy private
Definition at line 180 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 180 of file G4VCrossSectionDataSet.hh
Referenced by GetMaxKinEnergy(), and SetMaxKinEnergy().
G4double G4VCrossSectionDataSet::minKinEnergy private
Definition at line 179 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 179 of file G4VCrossSectionDataSet.hh
Referenced by GetMinKinEnergy(), and SetMinKinEnergy().
G4String G4VCrossSectionDataSet::name private
Definition at line 184 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 184 of file G4VCrossSectionDataSet.hh
Referenced by GetName().
G4CrossSectionDataSetRegistry* G4VCrossSectionDataSet::registry private
Definition at line 177 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 177 of file G4VCrossSectionDataSet.hh
Referenced by G4VCrossSectionDataSet(), and ~G4VCrossSectionDataSet().
G4int G4VCrossSectionDataSet::verboseLevel protected
Definition at line 170 of file G4VCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VCrossSectionDataSet.hh
Referenced by G4CrossSectionPairGG::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4NeutronInelasticXS::BuildPhysicsTable(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4ParticleInelasticXS::BuildPhysicsTable(), G4NeutronElasticXS::BuildPhysicsTable(), G4NeutronCaptureXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4LENDCrossSection::create_used_target_map(), G4BGGNucleonElasticXS::G4BGGNucleonElasticXS(), G4BGGNucleonInelasticXS::G4BGGNucleonInelasticXS(), G4BGGPionElasticXS::G4BGGPionElasticXS(), G4BGGPionInelasticXS::G4BGGPionInelasticXS(), G4CrossSectionPairGG::G4CrossSectionPairGG(), G4NeutronCaptureXS::G4NeutronCaptureXS(), G4NeutronElasticXS::G4NeutronElasticXS(), G4NeutronInelasticXS::G4NeutronInelasticXS(), G4ParticleInelasticXS::G4ParticleInelasticXS(), G4CrossSectionPairGG::GetElementCrossSection(), G4NeutronInelasticXS::GetElementCrossSection(), G4ParticleInelasticXS::GetElementCrossSection(), G4NeutronElasticXS::GetElementCrossSection(), G4NeutronCaptureXS::GetElementCrossSection(), G4BGGNucleonElasticXS::GetElementCrossSection(), G4BGGNucleonInelasticXS::GetElementCrossSection(), G4BGGPionElasticXS::GetElementCrossSection(), G4BGGPionInelasticXS::GetElementCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), GetVerboseLevel(), G4NeutronElasticXS::Initialise(), G4ParticleInelasticXS::IsoCrossSection(), G4NeutronElasticXS::IsoCrossSection(), G4NeutronInelasticXS::IsoCrossSection(), G4NeutronCaptureXS::IsoCrossSection(), G4NeutronInelasticXS::RetrieveVector(), G4NeutronCaptureXS::RetrieveVector(), G4ParticleInelasticXS::RetrieveVector(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4VCrossSectionDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4VCrossSectionDataSet.cc