ECCE @ EIC Software: G4ExtrudedSolid Class Reference
G4ExtrudedSolid Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4ExtrudedSolid.hh>
Classes
struct line
struct plane
struct ZSection
Public Member Functions
G4ExtrudedSolid (const G4String &pName, const std::vector< G4TwoVector > &polygon, const std::vector< ZSection > &zsections)
G4ExtrudedSolid (const G4String &pName, const std::vector< G4TwoVector > &polygon, G4double halfZ, const G4TwoVector &off1, G4double scale1, const G4TwoVector &off2, G4double scale2)
virtual ~G4ExtrudedSolid ()
G4int GetNofVertices () const
G4TwoVector GetVertex (G4int index) const
std::vector< G4TwoVector > GetPolygon () const
G4int GetNofZSections () const
ZSection GetZSection (G4int index) const
std::vector< ZSection > GetZSections () const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4ExtrudedSolid (__void__ &)
G4ExtrudedSolid (const G4ExtrudedSolid &rhs)
G4ExtrudedSolid & operator= (const G4ExtrudedSolid &rhs)
Public Member Functions inherited from G4TessellatedSolid
G4TessellatedSolid ()
virtual ~G4TessellatedSolid ()
G4TessellatedSolid (const G4String &name)
G4TessellatedSolid (__void__ &)
G4TessellatedSolid (const G4TessellatedSolid &ts)
G4TessellatedSolid & operator= (const G4TessellatedSolid &right)
G4TessellatedSolid & operator+= (const G4TessellatedSolid &right)
G4bool AddFacet (G4VFacet *aFacet)
G4VFacet * GetFacet (G4int i) const
G4int GetNumberOfFacets () const
virtual G4bool Normal (const G4ThreeVector &p, G4ThreeVector &n) const
virtual G4double SafetyFromOutside (const G4ThreeVector &p, G4bool aAccurate=false) const
virtual G4double SafetyFromInside (const G4ThreeVector &p, G4bool aAccurate=false) const
virtual G4ThreeVector GetPointOnSurface () const
virtual G4double GetSurfaceArea ()
virtual G4double GetCubicVolume ()
void SetSolidClosed (const G4bool t)
G4bool GetSolidClosed () const
void SetMaxVoxels (G4int max)
G4Voxelizer & GetVoxels ()
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4double GetMinXExtent () const
G4double GetMaxXExtent () const
G4double GetMinYExtent () const
G4double GetMaxYExtent () const
G4double GetMinZExtent () const
G4double GetMaxZExtent () const
virtual G4Polyhedron * CreatePolyhedron () const
virtual G4Polyhedron * GetPolyhedron () const
virtual void DescribeYourselfTo (G4VGraphicsScene &scene) const
virtual G4VisExtent GetExtent () const
G4int AllocatedMemoryWithoutVoxels ()
G4int AllocatedMemory ()
void DisplayAllocatedMemory ()
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
void ComputeProjectionParameters ()
void ComputeLateralPlanes ()
G4bool PointInPolygon (const G4ThreeVector &p) const
G4double DistanceToPolygonSqr (const G4ThreeVector &p) const
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
G4ThreeVector GetVertex (G4int iz, G4int ind) const
G4TwoVector ProjectPoint (const G4ThreeVector &point) const
G4bool IsSameLine (const G4TwoVector &p, const G4TwoVector &l1, const G4TwoVector &l2) const
G4bool IsSameLineSegment (const G4TwoVector &p, const G4TwoVector &l1, const G4TwoVector &l2) const
G4bool IsSameSide (const G4TwoVector &p1, const G4TwoVector &p2, const G4TwoVector &l1, const G4TwoVector &l2) const
G4bool IsPointInside (const G4TwoVector &a, const G4TwoVector &b, const G4TwoVector &c, const G4TwoVector &p) const
G4double GetAngle (const G4TwoVector &p0, const G4TwoVector &pa, const G4TwoVector &pb) const
G4VFacet * MakeDownFacet (G4int ind1, G4int ind2, G4int ind3) const
G4VFacet * MakeUpFacet (G4int ind1, G4int ind2, G4int ind3) const
G4bool AddGeneralPolygonFacets ()
G4bool MakeFacets ()
Private Attributes
G4int fNv
G4int fNz
std::vector< G4TwoVector > fPolygon
std::vector< ZSection > fZSections
std::vector< std::vector< G4int > > fTriangles
G4bool fIsConvex = false
G4GeometryType fGeometryType
G4int fSolidType = 0
std::vector< plane > fPlanes
std::vector< line > fLines
std::vector< G4double > fLengths
std::vector< G4double > fKScales
std::vector< G4double > fScale0s
std::vector< G4TwoVector > fKOffsets
std::vector< G4TwoVector > fOffset0s
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4TessellatedSolid
G4double kCarToleranceHalf
Detailed Description
Definition at line 71 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ExtrudedSolid.hh
Constructor & Destructor Documentation
G4ExtrudedSolid::G4ExtrudedSolid (const G4String & pName, const std::vector< G4TwoVector > & polygon, const std::vector< ZSection > & zsections)
Definition at line 66 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ExtrudedSolid.cc
References ComputeLateralPlanes(), ComputeProjectionParameters(), FatalErrorInArgument, FatalException, fIsConvex, fNv, fNz, fPolygon, fSolidType, fZSections, G4Exception(), G4GeomTools::IsConvex(), JustWarning, G4VSolid::kCarTolerance, G4TessellatedSolid::kCarToleranceHalf, MakeFacets(), message(), G4GeomTools::PolygonArea(), G4GeomTools::RemoveRedundantVertices(), and reverse.
Referenced by Clone().
G4ExtrudedSolid::G4ExtrudedSolid (const G4String & pName, const std::vector< G4TwoVector > & polygon, G4double halfZ, const G4TwoVector & off1, G4double scale1, const G4TwoVector & off2, G4double scale2)
Definition at line 189 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 189 of file G4ExtrudedSolid.cc
References ComputeLateralPlanes(), ComputeProjectionParameters(), FatalErrorInArgument, FatalException, fIsConvex, fNv, fPolygon, fSolidType, fZSections, G4Exception(), G4GeomTools::IsConvex(), JustWarning, G4VSolid::kCarTolerance, MakeFacets(), message(), G4GeomTools::PolygonArea(), G4GeomTools::RemoveRedundantVertices(), and reverse.
G4ExtrudedSolid::~G4ExtrudedSolid () virtual
Definition at line 333 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 333 of file G4ExtrudedSolid.cc
G4ExtrudedSolid::G4ExtrudedSolid (__void__ & a)
Definition at line 283 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 283 of file G4ExtrudedSolid.cc
G4ExtrudedSolid::G4ExtrudedSolid (const G4ExtrudedSolid & rhs)
Definition at line 293 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 293 of file G4ExtrudedSolid.cc
Member Function Documentation
G4bool G4ExtrudedSolid::AddGeneralPolygonFacets () private
Definition at line 637 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 637 of file G4ExtrudedSolid.cc
References G4TessellatedSolid::AddFacet(), angle, c1, c2, FatalException, fNv, fPolygon, fTriangles, G4Exception(), GetAngle(), G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), IsPointInside(), it, MakeDownFacet(), MakeUpFacet(), and pi.
Referenced by MakeFacets().
G4ThreeVector G4ExtrudedSolid::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 1070 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1070 of file G4ExtrudedSolid.cc
References a, b, DBL_MAX, fLengths, fNv, fPlanes, fPolygon, fSolidType, fZSections, in, k, max, PointInPolygon(), tmp, Acts::UnitConstants::u, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4ExtrudedSolid::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 1371 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1371 of file G4ExtrudedSolid.cc
References G4VSolid::DumpInfo(), dx, dy, G4ExtrudedSolid::ZSection::fOffset, fPolygon, G4ExtrudedSolid::ZSection::fScale, G4ExtrudedSolid::ZSection::fZ, G4Exception(), G4VSolid::GetName(), GetNofVertices(), GetNofZSections(), GetZSection(), JustWarning, kInfinity, max, message(), min, pMax, scale, CLHEP::Hep3Vector::set(), CLHEP::Hep2Vector::x(), CLHEP::Hep3Vector::x(), x, xmax, xmin, CLHEP::Hep2Vector::y(), CLHEP::Hep3Vector::y(), y, ymax, ymin, and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4ExtrudedSolid::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 1428 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1428 of file G4ExtrudedSolid.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), dx, dy, emax, CEMC_TOWER::emin, G4ExtrudedSolid::ZSection::fOffset, fPolygon, G4ExtrudedSolid::ZSection::fScale, G4ExtrudedSolid::ZSection::fZ, G4Exception(), G4VoxelLimits::GetMaxExtent(), G4VoxelLimits::GetMinExtent(), G4VSolid::GetName(), GetNofZSections(), GetZSection(), JustWarning, k, kInfinity, message(), pMax, scale, G4GeomTools::TriangulatePolygon(), CLHEP::Hep2Vector::x(), x1, x2, CLHEP::Hep2Vector::y(), y1, y2, and z.
G4VSolid * G4ExtrudedSolid::Clone () const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 850 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 850 of file G4ExtrudedSolid.cc
References G4ExtrudedSolid().
void G4ExtrudedSolid::ComputeLateralPlanes () private
Definition at line 373 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 373 of file G4ExtrudedSolid.cc
References fLengths, fLines, fPlanes, fPolygon, k, norm, CLHEP::Hep2Vector::x(), CLHEP::Hep2Vector::y(), and y.
Referenced by G4ExtrudedSolid().
void G4ExtrudedSolid::ComputeProjectionParameters () private
Definition at line 340 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 340 of file G4ExtrudedSolid.cc
References fKOffsets, fKScales, fNz, fOffset0s, fScale0s, fZSections, z1, and z2.
Referenced by G4ExtrudedSolid().
G4double G4ExtrudedSolid::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 1158 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1158 of file G4ExtrudedSolid.cc
References DBL_MAX, G4TessellatedSolid::DistanceToIn(), dz, fNz, fPlanes, fSolidType, fZSections, G4TessellatedSolid::kCarToleranceHalf, kInfinity, tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), G4InuclParticleNames::z0, and z1.
G4double G4ExtrudedSolid::DistanceToIn (const G4ThreeVector & p) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 1219 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1219 of file G4ExtrudedSolid.cc
References G4TessellatedSolid::DistanceToIn(), DistanceToPolygonSqr(), fPlanes, fSolidType, fZSections, in, max, PointInPolygon(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4ExtrudedSolid::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 1258 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1258 of file G4ExtrudedSolid.cc
References a, b, c, DBL_MAX, G4TessellatedSolid::DistanceToOut(), dz, fIsConvex, fNz, fPlanes, fSolidType, fZSections, G4TessellatedSolid::kCarToleranceHalf, CLHEP::Hep3Vector::set(), tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), G4InuclParticleNames::z0, and z1.
G4double G4ExtrudedSolid::DistanceToOut (const G4ThreeVector & p) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 1340 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1340 of file G4ExtrudedSolid.cc
References G4TessellatedSolid::DistanceToOut(), DistanceToPolygonSqr(), fPlanes, fSolidType, fZSections, in, max, min, PointInPolygon(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4ExtrudedSolid::DistanceToPolygonSqr (const G4ThreeVector & p) const inline private
Referenced by DistanceToIn(), DistanceToOut(), and Inside().
G4double G4ExtrudedSolid::GetAngle (const G4TwoVector & p0, const G4TwoVector & pa, const G4TwoVector & pb) const private
Definition at line 551 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 551 of file G4ExtrudedSolid.cc
References pi, t1, t2, CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by AddGeneralPolygonFacets().
G4GeometryType G4ExtrudedSolid::GetEntityType () const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 841 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 841 of file G4ExtrudedSolid.cc
References fGeometryType.
G4int G4ExtrudedSolid::GetNofVertices () const inline
Referenced by BoundingLimits(), PHG4GDMLWriteSolids::XtruWrite(), and G4GDMLWriteSolids::XtruWrite().
G4int G4ExtrudedSolid::GetNofZSections () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::XtruWrite(), and G4GDMLWriteSolids::XtruWrite().
std::vector<G4TwoVector> G4ExtrudedSolid::GetPolygon () const inline
G4TwoVector G4ExtrudedSolid::GetVertex (G4int index) const inline
Referenced by MakeDownFacet(), MakeFacets(), MakeUpFacet(), PHG4GDMLWriteSolids::XtruWrite(), and G4GDMLWriteSolids::XtruWrite().
G4ThreeVector G4ExtrudedSolid::GetVertex (G4int iz, G4int ind) const private
Definition at line 412 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 412 of file G4ExtrudedSolid.cc
References fPolygon, fZSections, and x.
ZSection G4ExtrudedSolid::GetZSection (G4int index) const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::XtruWrite(), and G4GDMLWriteSolids::XtruWrite().
std::vector<ZSection> G4ExtrudedSolid::GetZSections () const inline
EInside G4ExtrudedSolid::Inside (const G4ThreeVector & p) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 857 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 857 of file G4ExtrudedSolid.cc
References DistanceToPolygonSqr(), fNv, fNz, fPlanes, fPolygon, fSolidType, fTriangles, fZSections, G4TessellatedSolid::GetMaxXExtent(), G4TessellatedSolid::GetMaxYExtent(), G4TessellatedSolid::GetMaxZExtent(), G4TessellatedSolid::GetMinXExtent(), G4TessellatedSolid::GetMinYExtent(), G4TessellatedSolid::GetMinZExtent(), in, IsPointInside(), IsSameLineSegment(), it, G4TessellatedSolid::kCarToleranceHalf, kInside, kOutside, kSurface, max, PointInPolygon(), ProjectPoint(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4bool G4ExtrudedSolid::IsPointInside (const G4TwoVector & a, const G4TwoVector & b, const G4TwoVector & c, const G4TwoVector & p) const private
Definition at line 520 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 520 of file G4ExtrudedSolid.cc
References IsSameLineSegment(), IsSameSide(), CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by AddGeneralPolygonFacets(), and Inside().
G4bool G4ExtrudedSolid::IsSameLine (const G4TwoVector & p, const G4TwoVector & l1, const G4TwoVector & l2) const private
Definition at line 455 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 455 of file G4ExtrudedSolid.cc
References dy, G4TessellatedSolid::kCarToleranceHalf, CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by IsSameLineSegment().
G4bool G4ExtrudedSolid::IsSameLineSegment (const G4TwoVector & p, const G4TwoVector & l1, const G4TwoVector & l2) const private
Definition at line 485 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 485 of file G4ExtrudedSolid.cc
References IsSameLine(), G4TessellatedSolid::kCarToleranceHalf, max, min, CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by Inside(), and IsPointInside().
G4bool G4ExtrudedSolid::IsSameSide (const G4TwoVector & p1, const G4TwoVector & p2, const G4TwoVector & l1, const G4TwoVector & l2) const private
Definition at line 505 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 505 of file G4ExtrudedSolid.cc
References CLHEP::Hep2Vector::x(), and CLHEP::Hep2Vector::y().
Referenced by IsPointInside().
G4VFacet * G4ExtrudedSolid::MakeDownFacet (G4int ind1, G4int ind2, G4int ind3) const private
Definition at line 570 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 570 of file G4ExtrudedSolid.cc
References ABSOLUTE, Acts::VectorHelpers::cross(), GetVertex(), tmp, and CLHEP::Hep3Vector::z().
Referenced by AddGeneralPolygonFacets().
G4bool G4ExtrudedSolid::MakeFacets () private
Definition at line 761 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 761 of file G4ExtrudedSolid.cc
References ABSOLUTE, G4TessellatedSolid::AddFacet(), AddGeneralPolygonFacets(), fNv, fNz, fTriangles, GetVertex(), and G4TessellatedSolid::SetSolidClosed().
Referenced by G4ExtrudedSolid().
G4VFacet * G4ExtrudedSolid::MakeUpFacet (G4int ind1, G4int ind2, G4int ind3) const private
Definition at line 604 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 604 of file G4ExtrudedSolid.cc
References ABSOLUTE, Acts::VectorHelpers::cross(), fNz, GetVertex(), tmp, and CLHEP::Hep3Vector::z().
Referenced by AddGeneralPolygonFacets().
G4ExtrudedSolid & G4ExtrudedSolid::operator= (const G4ExtrudedSolid & rhs)
Definition at line 307 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 307 of file G4ExtrudedSolid.cc
References fGeometryType, fIsConvex, fKOffsets, fKScales, fLengths, fLines, fNv, fNz, fOffset0s, fPlanes, fPolygon, fScale0s, fSolidType, fTriangles, fZSections, and G4TessellatedSolid::operator=().
G4bool G4ExtrudedSolid::PointInPolygon (const G4ThreeVector & p) const inline private
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), and Inside().
G4TwoVector G4ExtrudedSolid::ProjectPoint (const G4ThreeVector & point) const private
Definition at line 424 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 424 of file G4ExtrudedSolid.cc
References fKOffsets, fKScales, fNz, fOffset0s, fScale0s, fZSections, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and G4InuclParticleNames::z0.
Referenced by Inside().
std::ostream & G4ExtrudedSolid::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 1519 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 1519 of file G4ExtrudedSolid.cc
References fGeometryType, fIsConvex, fNv, fNz, fPolygon, fZSections, G4endl, G4VSolid::GetName(), and mm.
G4ThreeVector G4ExtrudedSolid::SurfaceNormal (const G4ThreeVector & p) const virtual
Reimplemented from G4TessellatedSolid.
Definition at line 966 of file G4ExtrudedSolid.cc.
View newest version in sPHENIX GitHub at line 966 of file G4ExtrudedSolid.cc
References kdfinder::abs(), ApproxSurfaceNormal(), G4VSolid::DumpInfo(), fLengths, fNv, fPlanes, fPolygon, fSolidType, fZSections, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), JustWarning, k, G4TessellatedSolid::kCarToleranceHalf, message(), mm, G4TessellatedSolid::SurfaceNormal(), Acts::UnitConstants::u, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4GeometryType G4ExtrudedSolid::fGeometryType private
Definition at line 190 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 190 of file G4ExtrudedSolid.hh
Referenced by GetEntityType(), operator=(), and StreamInfo().
G4bool G4ExtrudedSolid::fIsConvex = false private
Definition at line 189 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 189 of file G4ExtrudedSolid.hh
Referenced by DistanceToOut(), G4ExtrudedSolid(), operator=(), and StreamInfo().
std::vector<G4TwoVector> G4ExtrudedSolid::fKOffsets private
Definition at line 201 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 201 of file G4ExtrudedSolid.hh
Referenced by ComputeProjectionParameters(), operator=(), and ProjectPoint().
std::vector<G4double> G4ExtrudedSolid::fKScales private
Definition at line 199 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 199 of file G4ExtrudedSolid.hh
Referenced by ComputeProjectionParameters(), operator=(), and ProjectPoint().
std::vector<G4double> G4ExtrudedSolid::fLengths private
Definition at line 197 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 197 of file G4ExtrudedSolid.hh
Referenced by ApproxSurfaceNormal(), ComputeLateralPlanes(), operator=(), and SurfaceNormal().
std::vector<line> G4ExtrudedSolid::fLines private
Definition at line 196 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ExtrudedSolid.hh
Referenced by ComputeLateralPlanes(), and operator=().
G4int G4ExtrudedSolid::fNv private
Definition at line 184 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ExtrudedSolid.hh
Referenced by AddGeneralPolygonFacets(), ApproxSurfaceNormal(), G4ExtrudedSolid(), Inside(), MakeFacets(), operator=(), StreamInfo(), and SurfaceNormal().
G4int G4ExtrudedSolid::fNz private
Definition at line 185 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 185 of file G4ExtrudedSolid.hh
Referenced by ComputeProjectionParameters(), DistanceToIn(), DistanceToOut(), G4ExtrudedSolid(), Inside(), MakeFacets(), MakeUpFacet(), operator=(), ProjectPoint(), and StreamInfo().
std::vector<G4TwoVector> G4ExtrudedSolid::fOffset0s private
Definition at line 202 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 202 of file G4ExtrudedSolid.hh
Referenced by ComputeProjectionParameters(), operator=(), and ProjectPoint().
std::vector<plane> G4ExtrudedSolid::fPlanes private
Definition at line 194 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 194 of file G4ExtrudedSolid.hh
Referenced by ApproxSurfaceNormal(), ComputeLateralPlanes(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
std::vector<G4TwoVector> G4ExtrudedSolid::fPolygon private
Definition at line 186 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 186 of file G4ExtrudedSolid.hh
Referenced by AddGeneralPolygonFacets(), ApproxSurfaceNormal(), BoundingLimits(), CalculateExtent(), ComputeLateralPlanes(), G4ExtrudedSolid(), GetVertex(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
std::vector<G4double> G4ExtrudedSolid::fScale0s private
Definition at line 200 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 200 of file G4ExtrudedSolid.hh
Referenced by ComputeProjectionParameters(), operator=(), and ProjectPoint().
G4int G4ExtrudedSolid::fSolidType = 0 private
Definition at line 192 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ExtrudedSolid.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4ExtrudedSolid(), Inside(), operator=(), and SurfaceNormal().
std::vector< std::vector<G4int> > G4ExtrudedSolid::fTriangles private
Definition at line 188 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 188 of file G4ExtrudedSolid.hh
Referenced by AddGeneralPolygonFacets(), Inside(), MakeFacets(), and operator=().
std::vector<ZSection> G4ExtrudedSolid::fZSections private
Definition at line 187 of file G4ExtrudedSolid.hh.
View newest version in sPHENIX GitHub at line 187 of file G4ExtrudedSolid.hh
Referenced by ApproxSurfaceNormal(), ComputeProjectionParameters(), DistanceToIn(), DistanceToOut(), G4ExtrudedSolid(), GetVertex(), Inside(), operator=(), ProjectPoint(), StreamInfo(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4ExtrudedSolid.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4ExtrudedSolid.cc